### ISSUE TITLE
[Suggestion]: Rock Candy trinker is too OP and causes lag when exploring on servers. Disable, nerf, or make harder to craft please.

### ISSUE THREAD

**Issue by legitswitch** [FTBTeam/FTB-Modpack-Issues#10]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

Problem:
The Rock Candy trinket is insanely OP in how fast it lets people fly over water (creative running fast). It makes boats useless and causes a lot of server lag from people abusing it when exploring new chunks.

Suggestion:
Nerf the speed of the Rock Candy trinket, make it much harder to make, or disable it outright?

**Comment by Sunekaer** [comment]
Wont be changed, if you run a server you can remove it from the loottable yourself but deleting "loot.add("1x losttrinkets:rock_candy", 1);" in \kubejs\server_scripts\mods\ftbstructures\structures.js
