### ISSUE TITLE
[Bug]: Shaped crafting from REI doesn't work in Sophisticated bacpack Crafting upgrade, unless entire crafting grid is used

### ISSUE THREAD

**Issue by jasoncollege24** [FTBTeam/FTB-Modpack-Issues#1002]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.0.2

### Describe the bug

When using REI to craft,  using the crafting upgrade in Sophisticated Backpacks, if the recipe doesn't use up all 9 spaces in the crafting grid, items are not placed in the correct locations for the recipe. This applies to recipes that have empty crafting grid slots.

This crafting works on other crafting tables/stations as far as I can tell.

### Steps to reproduce

1. Have a Sophisticated backpack, with the Crafting Upgrade equipped
2. Open said backpack, and switch to the crafting tab
3. Pick an item from REI to test with (Prosperity Gemstone is a great example)
4. Click the + to add it to the crafting grid
5. See that items are not in the required shape

### Expected behaviour

Recipes added to the Sophisticated Backpack crafting grid from REI should be properly shaped

### Screenshots

![Screenshot (60)](https://user-images.githubusercontent.com/22086680/175068097-40e90679-f0c5-4279-b461-5182773f0fcd.png)
![Screenshot (61)](https://user-images.githubusercontent.com/22086680/175068108-e7c2f9ef-9d82-4f2c-b965-f9d8dbc225d1.png)

### Additional information

This is on a server, located on my home LAN, running ubuntu 20.04. All players play in survival, and server side configs are all defaults, except RAM, which was allocated up to 6GB.

There is no log output for this problem, so no logs are included.

**Comment by Raidobw2** [comment]
I've made a report for it at https://github.com/shedaniel/RoughlyEnoughItems/issues/968
