### ISSUE TITLE
[Bug]: Duping with Immersive Engineering

### ISSUE THREAD

**Issue by Mundif** [FTBTeam/FTB-Modpack-Issues#1004]
### Modpack

FTB Presents Direwolf 20 1.18

### Modpack version

1.5.1

### Describe the bug

When crafting 2 IE hammers together they start duping, you get 1 fixed and those in crafting grid also stay, so you can pull forever, doesnt matter if any of hammers are damaged, happens anyway.

Similar  issue with tinkers seared and scorched tanks, when they got same fluid and same amount of it - they stack, if you have creosote oil in them and try to craft treated wood planks, when you pull treated planks, tanks dupe and jump into your inventory, creosote oil seems to be used though, because duped tanks after you pull just 8 treated planks got 3 buckets of oil while started full with 4 buckets, issue does not happen if you use single tank only stacked ones seem to dupe.

### Steps to reproduce

Craft IE hammers with eachother and dupe them as result.

Get stacked tinkers (2 tanks placed into craft will be enough) seared/scorched tanks with creosote oil inside and try to craft treated wood planks, you dupe tanks, oil gets used up though.

### Expected behaviour

Not dupe anything? :)

**Comment by Mundif** [comment]
Tried with 1.6.0, still happens, no changes.

**Comment by TheonlyTazz** [comment]
> Tried with 1.6.0, still happens, no changes.

Because this issue was placed just when I was a about to push 1.6.0...
I'm not sure if I can get it into 1.6.1, but I'll try to get it fixed asap
