### ISSUE TITLE
[Bug]: FTB Plexiglass Mountain 1.1.0 has bugged recipes for sticky piston, holy/unholy sap, and no recipe for using immersive constantan

### ISSUE THREAD

**Issue by Xalorous** [FTBTeam/FTB-Modpack-Issues#1005]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.0

### Describe the bug

Multiple recipes are now bugged:
* cannot use normal/blue/blood slimeballs to make sticky pistons
* sticky piston recipe only shows holy/unholy slime balls
* using REI 'show recipe' function to show malum holy sap recipe results in 17 pages of potions using fluid encapsulator but no recipe for holy (or unholy) sap
* immersive constantan was switched to constantan in every instance.  'usage' for constantan ingots in REI gives 17 pages of potions using fluid encapsulator - we need to be able to melt constantan and re-cast as thermal constantan

### Steps to reproduce

1. load game from 1.0.2 and upgrade to 1.1.0.  -OR- start new 1.1.0 game
1. look at recipe for sticky piston in REI, note only malum slimeballs are available
2. try to find the recipe to make holy sap
3. try to find usage for immersive engineering constantan ingots

### Expected behaviour

sticky piston recipe should allow any slimeball, immersive engineering constantan should melt into molten constantan, fluid encapsulator tab in REI should only show when appropriate.

### Additional information

I upgraded from 1.0.2 to 1.1.0 today.  Then these problems started.

**Comment by Raidobw2** [comment]
I notice the piston issue. I'll push that for hotfix today, you'll have another update tomorrow with a few more fixes

**Comment by Raidobw2** [comment]
I've added recipes in the hotfix to transmute most of the old materials to new ones as well. If you have a bunch of those materials, i suggest waiting for the hotfix

**Comment by Xalorous** [comment]
I voided the materials already, but then I backed down to the previous version of the pack due to the piston recipe issue.

Thank you for the quick response.

**Comment by Raidobw2** [comment]
Yes the app is acting a bit odd with updates, and it seems to create new tiles on the main menu (and new files everytime).

1.1.1 should be your target branch to play on if you can, since it has a bunch of fixes.
I messed up the changelog in the release unfortunately :o but I'll link it next update and for now the changes for 1.1.1 can be seen at https://paste.feed-the-beast.com/view/97d6890e.

Let me know if everything is alright later on and thanks for the report!
