### ISSUE TITLE
[Bug]: Unable to load into world

### ISSUE THREAD

**Issue by SilentZephyr02** [FTBTeam/FTB-Modpack-Issues#1006]
### Modpack

FTB University 

### Modpack version

1.16

### Log Files

https://bytebin.lucko.me/SwevgZiRmv

### Describe the bug

Trying to load into saved world, instead loads an error page 

### Steps to reproduce

Opening a saved world 

### Expected behaviour

Load into the world

### Screenshots

![Screenshot 2022-06-23 220555](https://user-images.githubusercontent.com/25911807/175274450-2a52a2d2-f628-4d16-81e6-9aa656ecd17d.png)

**Comment by aaronhowser1** [comment]
The log link doesn't work
![image](https://user-images.githubusercontent.com/15698722/176844858-eb01e21a-5b81-49dd-929a-457df1f2f4df.png)
