### ISSUE TITLE
[Bug]: New FE Angel Rings stop working when Flux Networks' Controller goes above 2.1 billion or so

### ISSUE THREAD

**Issue by Khaosina** [FTBTeam/FTB-Modpack-Issues#1007]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.6.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8966484/latest.log)

### Describe the bug

As the title says, the newly-added FE-powered Angel Rings stop working when a Flux Networks' Controller goes above 2.1 billion or so. I can't see the exact number but I'm guessing it's the 32 bit signed integer limit of 2,147,483,647.
Every 5-10 ticks or so, the Controller sends a full Resonant Angel Ring's worth of Power (16 million FE) to the Ring, as if the Ring had used all of its power in that small amount of time.

### Steps to reproduce

1. Add a Flux Plug to a high transfer power source or power storage (such as an Induction matrix from Mekanism).
2. Place down a Flux Controller.
3. Create/use a Flux network.
4. Set both the Plug and Controller to Bypass Limit. Controller will quickly go above 2 billion power or so.
5. Ring loses power and does not allow flight anymore.
6. Turn off Bypass Limit on Controller to fly again.

### Expected behaviour

Angel Ring and Flux Networks should behave normally and keep the Ring activated while Bypass Limit is turned on.

### Screenshots

- Flux Controller with more than 3 billion FE buffer

![image](https://user-images.githubusercontent.com/43579920/175282666-180a2d96-af1f-42ee-b562-e301b9be8fb9.png)

- The exact frame the click registered, from a video recorded at 60 fps, the Flux Controller sends 16 million FE somewhere (presumably to the Resonant Angel Ring that has a 16 million FE capacity)

![image](https://user-images.githubusercontent.com/43579920/175283789-3b146ea5-d274-4559-af92-7e533eee7abc.png)

- 10 frames later, from the same video, Controller sends another 16 million FE somewhere

![image](https://user-images.githubusercontent.com/43579920/175284741-4c2ef223-af79-443c-a8f7-f679de4b3c75.png)

### Additional information

- Tested it with all other FE-powered Angel Rings, same result but just with different output numbers on the Controller due to the different power capacities of each of the Rings.

- Also tested with the Flux Plug attached to a Quantum Entagoloporter, same results.

**Comment by TheonlyTazz** [comment]
now the question is, is this an issue from the FE Angel Rings, or FluxNetworks? 

in the meantime, just dont turn "bypass" limit off

**Comment by TheonlyTazz** [comment]
fixed

**Comment by Khaosina** [comment]
Doesn't seem to be fixed on my end, I can reproduce it exactly the same way as before, as well as in an instance with only Angel Rings, Flux Networks and Mekanism (for a creative power source) to rule out other mods interfering as best I could. 
I've made a post directly on their issues pages to try and see what's what.

**Comment by DenisMasterHerobrine** [comment]
This has been now fixed in v2.0.2 of Angel Ring, there were my mistake when calculating received/extracted RF from an energy source because it exceeds Integer's max value. The issue was on my (Angel Ring) end, sorry about that.
