### ISSUE TITLE
[Bug]: MythicBotany not showing in Lexica Botania

### ISSUE THREAD

**Issue by RoyalCube** [FTBTeam/FTB-Modpack-Issues#1008]
### Modpack

DW20 1.18

### Modpack version

1.6.0

### Describe the bug

In the previous version we had 2 chapters explaining Mythic Botany, they are gone in 1.6.0. Making it very dfficult to progress in botania since you need alfsteel to make gaia pylons and there is no guide on how to do it

### Steps to reproduce

Open lexica Botania and see for yourself

### Expected behaviour

See MythicBotany chapters

### Screenshots

![Screenshot_3](https://user-images.githubusercontent.com/35603498/175292193-a9fbccdf-2b7b-4cf3-a498-af09a4dd7d71.png)

**Comment by JosiahBull** [comment]
I am also having this issue on BetterMinecraft (I've modified it with just botania + mythicbotany).

**Comment by Remixed-Witch** [comment]
The Mythic Botany mod seems to have updated to fix this issue, I've not been able to test it as every time I try the pack with the new version it wont get past "Atlas Stitching"
