### ISSUE TITLE
[Bug]: FTB Presents Direwolf20 1.18 does not generate Superflat world

### ISSUE THREAD

**Issue by JacksonBailey** [FTBTeam/FTB-Modpack-Issues#1011]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.6.0

### Log Files

https://pste.ch/raw/hudumomete

### Describe the bug

Using the Superflat world type does not make the world flat.

### Steps to reproduce

1. Create a new world using Superflat for World Type
2. The world is not flat

### Expected behaviour

Superflat world type should be flat

### Additional information

This problem existed in previous versions as well but I didn't get around to submitting a bug.

**Comment by Sunekaer** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/813
