### ISSUE TITLE
[Bug]: Fluid Encapsulator recipes everywhere

### ISSUE THREAD

**Issue by dev-Finn** [FTBTeam/FTB-Modpack-Issues#1012]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

Every recipe has a tab for the thermal fluid encapsulator (thermal:bottler) which lists all potion recipes

### Steps to reproduce

Open Game

Go on server (freshly updated in our case) with existing world

Any REI recipe is affected, clicking into nothingness also opens the tab for the encapsulator

### Expected behaviour

Not this

### Screenshots

![grafik](https://user-images.githubusercontent.com/57416486/175367736-2da01ba7-faef-45d2-a7f7-037d2ea6b621.png)

![grafik](https://user-images.githubusercontent.com/57416486/175367931-57c32793-0ba4-4bda-9e8e-b74d352a6051.png)

**Comment by Raidobw2** [comment]
Thermal added new potion compat, this will probably need to be adjusted in REI. Tracked at https://github.com/shedaniel/RoughlyEnoughItems/issues/949

**Comment by MaxNeedsSnacks** [comment]
This has been fixed in REI and is now awaiting a pack update ^^

**Comment by Raidobw2** [comment]
Fixed in 1.2.0
