### ISSUE TITLE
[Bug]: Bedrock Silver Ore Extracts Regenerative Lead Cluster

### ISSUE THREAD

**Issue by sme23** [FTBTeam/FTB-Modpack-Issues#1013]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

When mining Bedrock Silver Ore using a pickaxe with the Extraction enchantment in order to remove the regenerative cluster for relocating, it will drop a Regenerative Lead Cluster instead of a Regenerative Silver Cluster.

In a test environment with only Bedrock Ores, Immersive Engineering, and JEI, this scenario does drop a Regenerative Silver Cluster.

### Steps to reproduce

1. Find (or place) a Bedrock Silver Ore block.
2. Break block using Netherite Pickaxe with Extraction enchantment
3. Block will drop Regenerative Lead Cluster

### Expected behaviour

Block to drop Regenerative Silver Cluster

### Additional information

Occurs to me that I've only tested this in this pack using blocks generated in version 1.0.0 and not with newly generated ones in version 1.1.1, if there's trouble reproducing this that may be the difference

**Comment by Raidobw2** [comment]
Oops, that's a copy-paste error on my part.
If you open `kubejs\data\dadobugbedrockores\loot_tables\blocks\bedrock_ie_silver_ore.json` with a text editor, near the end at line 168 you see this:
![image](https://user-images.githubusercontent.com/17010632/175435790-a18dfd1c-e187-4888-94bf-acaab7224668.png)
Change the word "lead" to "silver", save the file and type "/reload" in your game, this will fix it for now.
![image](https://user-images.githubusercontent.com/17010632/175435841-21c95c64-6924-4b18-b415-4fc447bf190e.png)
I'll push this in a 1.1.2, which might be in about a week

**Comment by Raidobw2** [comment]
Fixed in 1.2.0
