### ISSUE TITLE
[Bug]: Building gadget preview seems to not show properly

### ISSUE THREAD

**Issue by richhuff** [FTBTeam/FTB-Modpack-Issues#1015]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.6.0

### Describe the bug

After updating to 1.6.0, the building gadget is no longer showing the blocks to be placed in "build to me".
The building gadget settings also had to be reset after the update.

### Steps to reproduce

Have dirt in pocket storage or player inventory.
Set building gadget to dirt.
Point building gadget at a block surface to build from.
No "ghost" blocks appear.
Click and the blocks are placed.

If I reverted to 1.5.1 the blocks to be placed are visualized as expected.

### Expected behaviour

Blocks to be placed should be visualized.

### Additional information

System is Windows 10 on a AMD Ryzen 9 5950X with 64 GB memory and a EVGA GEForce RTX3070 GPU.

**Comment by Anomalous** [comment]
Likely related: in FTB Presents Direwolf20 1.18 modpack version 1.6.0, the preview of what blocks the PneumaticCraft jackhammer will break doesn't show up, and Minecolonies building previews don't work either.  The latter makes MineColonies more or less unplayable. If you walk around inside where the MineColonies building preview should be, there is an occasional flicker of "ghost" block visible for a fraction of a second. It seems probable that some common system used for these overlays is broken on 1.6.0.

**Comment by TheonlyTazz** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1009
