### ISSUE TITLE
[Bug]: Cannot silk touch budding blocks from Tinkers

### ISSUE THREAD

**Issue by Raidobw2** [FTBTeam/FTB-Modpack-Issues#1016]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.1

### Log Files

N/A

### Describe the bug

Cannot silk touch budding blocks from TiCo, but tooltip says otherwise
![image](https://user-images.githubusercontent.com/17010632/175432799-c1859cd1-bdaa-4f12-9cb9-aaa34ff5f0c5.png)

### Steps to reproduce

1. Look "budding" in REI
2. Over the block
3. Place it down
4. Mine with silktouch
5. Notice no budding block is given, but rather the normal crystal block is received

### Expected behaviour

Should be getting the budding variant

### Screenshots

N/A

### Additional information

N/A

**Comment by Raidobw2** [comment]
The content of this zip needs to go in "kubejs/data/tconstruct" to fix it
[tconstruct.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8972112/tconstruct.zip)
Then relaunching game or typing "/reload" in-game will reload those changes on the spot

**Comment by Raidobw2** [comment]
Knowing that the crystal growth can be slow, I'll see if I can come up with something interesting to speed it up

**Comment by IamStig** [comment]
A fix is great. But they can be moved with cardboard boxes. And speeding up? is it really necessary as the crystals grow on all 6 sides if placed correctly. I put 4 of each out and get about 240 on average each harvest with fortune III

**Comment by Raidobw2** [comment]
Thanks for the feedback! I see, so they already give quite an amount of crystals. And I would have used something along the lines of https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/fabric%2Fv12.0.0-alpha (the accelerators), although that has not been backported to 1.18.2 and that post also is for Fabric. Not something in my reach but thought I'd share anyways since it looks cool :P

**Comment by Raidobw2** [comment]
Removing fixed in-dev as a reminder for me to check to make alternatives (maybe?) to crystal growth. Maybe something like "toss in water" similar to AE2 seeds could at the same time familiarize players into AE2 "toss in water" kind of automation. I'll re update this issue very soon

**Comment by Raidobw2** [comment]
I went and added a recipe for the overgroth seed first, since that currently isn't available in loot (it will be in a future update):
![image](https://user-images.githubusercontent.com/17010632/185253882-153bc0e6-34f8-45e7-bd8e-6f4f07eda313.png)

Then you can grow crystals, but it still requires 40s for one to grow (which is still much faster than random ticks):
![image](https://user-images.githubusercontent.com/17010632/185254060-03babb85-70a9-4535-9cf1-370146fc30eb.png)
![image](https://user-images.githubusercontent.com/17010632/185253843-67539d18-dbc4-4dce-914c-b99e8efa7ccf.png)

**Comment by Raidobw2** [comment]
Fully fixed in 1.2.0
