### ISSUE TITLE
[Bug]: Conflict with mods

### ISSUE THREAD

**Issue by Aideenwolf** [FTBTeam/FTB-Modpack-Issues#1019]
### Modpack

Direwolf20 1.18

### Modpack version

1.6.0

### Describe the bug

MineColonies-1.18.2-1.0.828-BETA & Tempad-forge-1.18.2-1.2.4 have some kind of conflict.
When both of these are loaded the Building Preview for Mine Colonies is no longer visible.

### Steps to reproduce

1. Load any game
2. Use MineColonies build tool to create a new building
3. No Preview of building
4. Close game, & restart with Tempad-forge-1.18.2-1.2.4 disabled
5. Repeat 1&2

### Expected behaviour

Building preview of MineColonies buildings with building wand

**Comment by TheonlyTazz** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1009
