### ISSUE TITLE
[Bug]: Laser IO wrench not linking nodes

### ISSUE THREAD

**Issue by twoworlds** [FTBTeam/FTB-Modpack-Issues#1020]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.60

### Describe the bug

I updated my server and client to version 1.16. I placed some LaserIO Nodes and want to link them with the laser wrench. I get a short animation when SHIFT-right clicking the node with the wrench but the node is not marked as it used to be. It is impossible to link 2 nodes together.
I quickly started a singleplayer test world and there I get the same problem.

### Steps to reproduce

Place LaserIO nodes
Get LaserIO wrench
Shift - right click the LaserIO node with the LaserIO wrench
Nothin happens

### Expected behaviour

The selected node should turn green and can be connected to another node.

**Comment by twoworlds** [comment]
I quickly installed a new instance of the modpack and started a new world. Same problem occurs here.
In a fresh forge instance with just LaserIO, everything works as expected, so it seems to be some kind of interference with another mod from the modpack.

**Comment by TheonlyTazz** [comment]
I can only assume this is related to "Tempad"... Disable fancydoors in tempad_client.json and that should fix it

**Comment by TheonlyTazz** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1009
