### ISSUE TITLE
[Bug]: Create Mod overlays not showing

### ISSUE THREAD

**Issue by BubbaVB** [FTBTeam/FTB-Modpack-Issues#1021]
### Modpack

Direwolf20 1.18

### Modpack version

1.6.0

### Describe the bug

The overlays in the Create Mod are not showing.  In the screenshot what is on the left is what you should see and what is on the right is what you actual see.  Other examples but not in the screenshot:

- If you are looking at a chassis with the wrench  you don't see anything at all.
- When looking at a deployer you don't see the box for filtering but filtering does work.

The overlays worked in the prior versions of the DW20 1.18 mod pack.

### Steps to reproduce

Place a deployer, chasis, etc. in the world and attempt to see the overlay.  Have the wrench in hand.

### Expected behaviour

You would see the overlay.

### Screenshots

![Create Issue](https://user-images.githubusercontent.com/20612106/175560466-eb5e7b22-33a3-4ef0-9fd3-b11e1838e4ee.png)

**Comment by TheonlyTazz** [comment]
fixed in 1.6.1 which is out now
