### ISSUE TITLE
[Bug]: Direwolf20 1.18 v1.6.1 entities not rendering

### ISSUE THREAD

**Issue by wheeljuke** [FTBTeam/FTB-Modpack-Issues#1023]
### Modpack

FTB presents direwolf 20 1.18

### Modpack version

1.6.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8984453/latest.log)

### Describe the bug

all hand held items doesn't render and i assume entities such as botania sparks, spreaders and in general mobs also doesn't render(excluding create machines)

### Steps to reproduce

1. join existing world

### Expected behaviour

I expect ftb to release a patch to fix this bug

### Screenshots

![Uploading 截圖 2022-06-25 下午5.52.58.png…]()

**Comment by TheonlyTazz** [comment]
please reupload your screenshot

**Comment by wheeljuke** [comment]
<img width="1728" alt="截圖 2022-06-25 下午5 52 58" src="https://user-images.githubusercontent.com/37240580/175770735-5fd87137-0b8b-4a0a-bd39-b102dd7b89cd.png">

**Comment by wheeljuke** [comment]
<img width="1728" alt="截圖 2022-06-25 下午5 52 51" src="https://user-images.githubusercontent.com/37240580/175770773-46cbbc84-2555-4b9d-980b-d0701840a493.png">

**Comment by wheeljuke** [comment]
the uploading doesn't seem to work here's a link to the photo: https://drive.google.com/file/d/14aoeEVDZ3CT94lkP32YeZxzH2osgUsdp/view?usp=sharing

**Comment by TheonlyTazz** [comment]
would it be possible for you to upload your save bcause we have had a similar issue, which we couldnt resolve [982](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/982)
and i couldnt replicate it...

**Comment by wheeljuke** [comment]
somehow the game has fixed itself I restarted the computer and everything is normal

**Comment by TheonlyTazz** [comment]
this is similar to the issue that other person had, but as said, we couldnt replicate it

**Comment by wheeljuke** [comment]
> would it be possible for you to upload your save bcause we have had a similar issue, which we couldnt resolve [982](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/982) and i couldnt replicate it...

ok just a second

**Comment by wheeljuke** [comment]
here:
https://drive.google.com/file/d/1pJCp2q2ZzYl33yEr0sai6aRjMd4ZnY-Y/view?usp=sharing

**Comment by wheeljuke** [comment]
FYI the entities are just not rendering they're still there and as far as i can tell they're still functioning perfectly. Travel anchors still teleports, sparks still transfer mana, pickaxe still mines blocks and spreaders still spread mana.

**Comment by DeciTM** [comment]
Is it related that targeted blocks are no longer highlighted with Mining Gadgets?

**Comment by TheonlyTazz** [comment]
> Is it related that targeted blocks are no longer highlighted with Mining Gadgets?

no this has been fixed in 1.6.1 with the change on tempad_client.json, `fancydoors=false`

**Comment by wheeljuke** [comment]
oh well it happend again
https://drive.google.com/file/d/1ZtNnM5yK5mjvrGTfb7uGiSkmaN0Qs22h/view?usp=sharing

**Comment by InFuRiTy** [comment]
I have noticed that if you mess a lot with mod configs from the main menu, that triggers the render issue like 80% of the time.
Had to re-install the pack twice to get it to work again..
Others need to confirm this though. it might be just me.

**Comment by TheonlyTazz** [comment]
> I have noticed that if you mess a lot with mod configs from the main menu, that triggers the render issue like 80% of the time. Had to re-install the pack twice to get it to work again.. Others need to confirm this though. it might be just me.

changing around mod configs can lead to unexpected behaviour obviously. I would recommend, if you change something mod-related (especially rendering related) to always restart your client. 

i still havent been able to properly replicate it (with provided save file). So as long as this cant be consitently replicated i would recommend just restart your Client whenever you mess with settings
