### ISSUE TITLE
[Bug]: Mine Colonies Builders don't recognize Minecraft Clocks as Minecraft Clocks

### ISSUE THREAD

**Issue by AshenPheonix** [FTBTeam/FTB-Modpack-Issues#1025]
### Modpack

FTB Direwolf 1.18

### Modpack version

1.16.1

### Describe the bug

When Dark Oak Houses get to rank 5, you need to give them 1 minecraft:clock. In the required tab, it looks a bit off, but it is definitely the normal clock. There is no way to convince the builder to use the clock, however. I suspect it's not seeing the clock as a clock, but I don't see any reason why.

### Steps to reproduce

1. get a builder to rank 5+
2. get a Dark Oak house to rank 4 and attempt to increase to rank 5
3. attempt to complete the house. It requires 1 clock to finish

### Expected behaviour

You are allowed to give a clock to the builder to finish the build

### Screenshots

![request](https://user-images.githubusercontent.com/6516394/175772361-f465d2c3-ce3b-4020-b01f-e5ac06b6ccd6.png)
![her inventory](https://user-images.githubusercontent.com/6516394/175772360-b7c2bb2c-b82d-4611-95f5-c71912e7c661.png)

### Additional information

I've tried putting it directly in their inventory (see image), using the "fulfill" tab of her inventory, and the "required resources" tab of the builder hut interface. None of these work.

**Comment by IamStig** [comment]
I believe that is a known issue involving quark. From what I recall Quark changes the clock somehow and therefor Minecolonies doesn't recognise it. I submitted to both the issue (more than a year ago), Minecolonies blamed quark and neither wanted to resolve it.

**Comment by TheonlyTazz** [comment]
i tried disabling Quark's Clock Nerf to stop it from messing with the clock, lets see if that fixes it

**Comment by AshenPheonix** [comment]
I updated. It still does not seem to want to recognize the clock.

**Comment by IamStig** [comment]
I am assuming you deleted the clock and crafted a new one ..... right? as a previously crafted clock maybe doesn't reset the nbt or whatever.
If you did maybe someone will have a better answer.

**Comment by AshenPheonix** [comment]
Yes, I did. It stacked with the old ones. Deleted them and it still didn't help.
