### ISSUE TITLE
[Bug]: FTB University crafting Recipes not appearing in Multiplayer

### ISSUE THREAD

**Issue by nauthas** [FTBTeam/FTB-Modpack-Issues#1026]
### Modpack

FTB University 1.16

### Modpack version

1.6.1

### Log Files

https://gist.github.com/Juicysteak117/d2459d73925dac5872d6228185823669
https://gist.github.com/nauthas/ea96e16b9069f1cc0ee4dd05ea1a0f21
### Describe the bug

Whilst in Singleplayer all the crafting recipes are fine, upon joining a multiplayer server both me and the server host are unable to see anything seemingly involving a workbench or shapeless crafting. If you put the required items in the right side will appear blank, but clicking on the blank slot will still craft the item in question. JEI also doesn't show any of these crafting recipes as existing, but other crafting recipes like those requiring furnaces, or modded crafting inventories otherwise work fine. 

### Steps to reproduce

1. Log onto a server
2. Attempt to craft log into wood planks
3. Note the lack of resulting item appearing on the output
4. Clicking the Output still recieves the item
5. Check JEI for the recipe for Logs
6. Note they're missing

### Expected behaviour

JEI Should show missing crafting recipes, output preview should show up

### Screenshots

![image](https://user-images.githubusercontent.com/16505438/175774720-a6cb2041-24d3-4067-82f5-931427dace6c.png)
![image](https://user-images.githubusercontent.com/16505438/175774735-862c57fc-4215-4255-a739-1e80ad6ae26f.png)

### Additional information

Have Tried Multiple suggestions seen elsewhere, Including loading single player first then going into Multiplayer to no avail. 

The issue from a google search seems to be a broken mod as Direwolf 20s pack had a similar issue, except the broken mod there is not included in university.  (It was Oreberries)

The Error does not exist in the 1.5.0 version

EDIT: Can confirm this bug exists amongst other players too, someone on the discord had the same issue on their server independently, and when I tried to run my own server the result was the same

**Comment by Gabius678** [comment]
Same issue for me

**Comment by aaronhowser1** [comment]
Fixed in 1.6.2, it was Blood Magic causing it.
