### ISSUE TITLE
[Bug]: Tom's Simple Storage Crafting Terminal won't move items from REI recipe

### ISSUE THREAD

**Issue by NotPiffany** [FTBTeam/FTB-Modpack-Issues#1027]
### Modpack

FTB One

### Modpack version

1.1.0

### Describe the bug

When I try to use REI to craft recipes in the Tom's Simple Storage crafting terminal, the button mousing over that button gives me a  popup saying "Move Items is not supported with this recipe and this container."

### Steps to reproduce

1. Open the crafting terminal.
2. Search for an item (example: oak planks) in REI.
3. Click the item in the REI menu to bring up the recipe.
4. Mouse over the button that should move the crafting ingredients into the crafting table.
5. Get the annoying pop-up.

### Expected behaviour

I expect to be able to use the move items button to move ingredients into the crafting table automatically.

### Additional information

I checked the Tom's Simple Storage github first. He said it was fixed in the latest version of Tom's, and the issue is with REI.

**Comment by NotPiffany** [comment]
The problem persists in 1.3.0

**Comment by Semorphim** [comment]
Problem also occures with the Ender-Rift Crafting Terminal.
The Occultism Dimensional Storage works with REI Crafting.
