### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by bogie1989** [FTBTeam/FTB-Modpack-Issues#1028]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.6.1

### Describe the bug

Immersive engineering doesnt reconized the ftb contraptions uranium blocks as a heat source

### Steps to reproduce

Immersive engineering doesn't recognized the ftb contraptions uranium blocks as a heat source

place uranium block next to thermalelectric generator with blue ice no power gen

### Expected behaviour

no power gen

**Comment by TheonlyTazz** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/5349

**Comment by TheonlyTazz** [comment]
fixed in-dev, the block didnt had the tag
