### ISSUE TITLE
[Bug]: Blocks will not update if interacted with.

### ISSUE THREAD

**Issue by bwerry73** [FTBTeam/FTB-Modpack-Issues#1029]
### Modpack

DW20 1.18

### Modpack version

1.6.1

### Log Files

[2022-06-25-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8985659/2022-06-25-1.log.gz)

### Describe the bug

I cannot right click any object. If I break a block, it will not update.

### Steps to reproduce

Left click on a block
block breaks and updates
Right click on block
open interface

### Expected behaviour

Blocks should update

**Comment by Raidobw2** [comment]
Hello, are you inside claimed chunks or on a public server? Some public servers may have spawn protection turned on or some anti grief plugins. Please let us know and thanks
