### ISSUE TITLE
[Bug]: Sapphire doesn't generate? Though its needed for the resonant angel ring.

### ISSUE THREAD

**Issue by Rowley-dev** [FTBTeam/FTB-Modpack-Issues#1030]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

Sapphire required for resonant angel ring? Spent 3 hours looking. Theres no documentation for sapphire, or even if it spawns.

### Steps to reproduce

Sapphire

### Expected behaviour

Sapphire

**Comment by Raidobw2** [comment]
Hello, thanks for the report. I'll look up available options and see if changing it might be better.
For now you can get sapphire in other ways:
- Finding a Sapphire Creeper
- Locating a Sapphire vein with the Sampling Kit from Immersive Engineering and mining it with the Excavator machine
- Using Botania's Orechid functional flower to generate the ore

**Comment by Raidobw2** [comment]
I've decided to keep sapphire and ruby like they are now. I've added more ways to get them however. Here's a preview:
![image](https://user-images.githubusercontent.com/17010632/185042589-4f2c5f3c-1102-4363-90ba-3bc18195bd78.png)
![image](https://user-images.githubusercontent.com/17010632/185042618-04b82a1b-2c5b-4c9d-9eb1-d5059a8cd26a.png)
![image](https://user-images.githubusercontent.com/17010632/185042647-50b23768-d7ab-4333-b98a-49d846e85705.png)
![image](https://user-images.githubusercontent.com/17010632/185042668-2b26a72c-0ddb-4c59-bb4e-5543f338b1c9.png)
I hope that works, feel free to let me know if you have other requests concerning these materials

**Comment by Raidobw2** [comment]
Above info and recipes are in 1.2.0
