### ISSUE TITLE
[Bug]: RFTools Builder pump card does not replace fluids with configured replace block

### ISSUE THREAD

**Issue by vlaetansky** [FTBTeam/FTB-Modpack-Issues#1032]
### Modpack

Any modpack with RFTools Builder

### Modpack version

-

### Describe the bug

Title gets it pretty much covered, but the actual problem is not the mod itself but a [library](https://github.com/McJtyMods/McJtyLib), the fix was merged not that long time ago McJtyMods/McJtyLib#135, I have already tested the latest build on oceanblock and everything works as intended.

### Steps to reproduce

Tested on the latest Oceanblock
1. Take RFTools builder, pump card for it, any source of power and any fluid container (void trash can works)
2. Select an area with pump card and get it in the RFTools builder
3. Place an energy cell to the right of the RFTools builder and fluid container on the top
4. Start RFTools builder and watch liquid being pumped but no blocks placed

### Expected behaviour

Configured replace blocks (Dirt by default) being placed

### Additional information

McJtyMods/RFToolsBuilder#8
People are reporting here the same problem on multiple modpacks, personally I have encountered this issue on the latest version of Oceanblock.

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/176132195-f0979bb8-3367-464c-b63f-02ff8e4d7c5b.png)
Fixed in-dev
