### ISSUE TITLE
[Bug]: ME Level Emitter with Fuzzy Card puts server in infinite crash loop

### ISSUE THREAD

**Issue by quietust** [FTBTeam/FTB-Modpack-Issues#1034]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.6.1

### Log Files

[crash-2022-06-26_17.07.40-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8987680/crash-2022-06-26_17.07.40-server.txt)

### Describe the bug

Placing a Fuzzy card into a programmed ME Level Emitter causes the server to enter an infinite crash loop.

### Steps to reproduce

0. Make a save backup if necessary
1. Craft an ME Level Emitter and place it on a powered Cable
2. Craft a Fuzzy Card
3. Open the Level Emitter's UI and program it with an item type from JEI - in my case, I used a Draco Arcanus Sword
4. Install the Fuzzy Card
5. Watch the server crash
6. Revert to a backup, because the server now immediately crashes on startup

### Expected behaviour

Server doesn't crash

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/175927607-c7d8d914-cfa8-4615-9e82-fa0756e86f16.png)
could not replicate this issue. Would it be possible to send over a World Save?

**Comment by quietust** [comment]
The world snapshot I posted in #958 appears to be sufficient for reproducing this crash. It's possible it might be due to something special I've got connected to my ME system.

Also of note: I've disabled a handful of mods (primarily performance-enhancing ones) in my instance of the pack, so it's possible one of them might be masking this problem:
* BetterThirdPerson
* BlockShot
* Connectivity
* CrashUtilities
* Emojiful
* FTBAuxilium
* ItShallNotTick
* MineTogether
* SimpleDiscordRichPresence
* WYML

**Comment by quietust** [comment]
I've just confirmed that the crash only happens when my ME system has access to **fluids** - I disconnected everything, and the instant I inserted a non-empty Fluid Cell into my ME Drive the game crashed.
