### ISSUE TITLE
[Bug]: Quark food tooltip enabled despite having the same feature with Appleskin

### ISSUE THREAD

**Issue by tyreforhyred** [FTBTeam/FTB-Modpack-Issues#1037]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

Quark's food tooltip function is enabled alongside with Appleskin, causing edible items to show their food values twice on mouseover.

### Steps to reproduce

Mouse over an edible item.

### Expected behaviour

To only have one display of food value on an item.

### Screenshots

![foodtooltipoverlap](https://user-images.githubusercontent.com/76914208/176039509-7ac1a7e6-c955-411e-936b-7483c8279141.png)

**Comment by faanlez** [comment]
This is actually also an issue at least in the Direwolf20 pack, possibly others.

**Comment by Raidobw2** [comment]
Thanks, we'll fix it for both packs soon

**Comment by TheonlyTazz** [comment]
Fixed in DW20 In-dev
