### ISSUE TITLE
[Bug]: Game crash after pressing M to open the map

### ISSUE THREAD

**Issue by voughndjik** [FTBTeam/FTB-Modpack-Issues#1040]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.1

### Log Files

https://paste.feed-the-beast.com/view/64ed77fd

### Describe the bug

In game i tried to open the map by pressing M button and it crashed

### Steps to reproduce

version 1.1.1
multiplayer world 
open the map

### Expected behaviour

Open the map

**Comment by Raidobw2** [comment]
Linked to #996

**Comment by Raidobw2** [comment]
@voughndjik Make sure Forge is used to start the server, we have diagnosed that this problem happens if the server is started as a normal non-modded server.

Here is the server procedure if you shall need it https://go.ftb.team/create-a-server

**Comment by WebDragon** [comment]
Currently getting a crash, pressing M to open the map on 1.2.4 single-player
https://paste.feed-the-beast.com/view/e9b052b8
