### ISSUE TITLE
[Bug]: Server won't start

### ISSUE THREAD

**Issue by setycz** [FTBTeam/FTB-Modpack-Issues#1041]
### Modpack

FTB One

### Modpack version

1.2.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8999410/latest.log)

### Describe the bug

After the server is started, it stops and says "Failed to load datapacks, can't proceed with server load.", see the details in the attached log.

### Steps to reproduce

1. Download 1.2 server pack for windows (serverinstall_97_2229.exe)
2. Install the server with default values
3. start the server via ./start.bat

### Expected behaviour

Server will start

**Comment by setycz** [comment]
It looks like the issue is cause by travelanchors mod:
```
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.blockentity.BlockEntityRenderer
	at cpw.mods.securejarhandler@2.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more

[28čvn2022 10:48:18.785] [main/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegisterEvent dispatch for modid travelanchors
```

Maybe it is not server friendly, touching BlockEntityRenderer from a server looks suspicious... 

FYI: without this mod the server starts fine.

**Comment by halb** [comment]
Same on Linux.  Here are some logs.
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9001631/debug.log)
[ftb-one-1.2.0-bugreport.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9001632/ftb-one-1.2.0-bugreport.txt)

**Comment by Saereth** [comment]
Reported to mod dev, following up for an update asap once resolved
https://github.com/castcrafter/travel_anchors/issues/51

For now you may consider disabling the mod on your server (travel anchors) until we get a fix out.

**Comment by Saereth** [comment]
This is fixed in the current release version of the pack
