### ISSUE TITLE
[Bug]: Picking up Elementalcraft reservoirs either crashes the game/server or dublicates them

### ISSUE THREAD

**Issue by Zaplaro** [FTBTeam/FTB-Modpack-Issues#1043]
### Modpack

Direwolf20 1.18

### Modpack version

1.61

### Describe the bug

If you shift+right-click on the top half of an Elementalcraft Reservoir, you can place it down and break both and get 1 from each half. If you do the same on the bottom half, it will crash the server. When I tried it my singleplayer world was corrupted after that and cannot be  jonied no more.

### Steps to reproduce

1. Place an Element Reservoir
2. Shift+right-click to pick it up
3. Place the picked up block 

### Expected behaviour

Either the game crashing or dublicating the Reservoir

**Comment by TheonlyTazz** [comment]
Stop breaking stuff like this... its clear that Carry-On isnt intended to be able to pickup 2high blocks... I'll add it to the blacklist then
