### ISSUE TITLE
[Bug]: Compact Machines tunnels disconnect between the overworld and the compact machine itself

### ISSUE THREAD

**Issue by PaXilinski** [FTBTeam/FTB-Modpack-Issues#1044]
### Modpack

Direwolf20 1.18

### Modpack version

1.6.1

### Describe the bug

I noticed a problem with compact machines 4. Im using it for having my energy production in it and ore procrssing in another one. I havent been able to recreate it but the tunnels keep bugging out where they lose there binding between the worlds (overworld to comapct machine). I have to get into the compact machine remove the tunnel place it get out and update the pipes (i use bothe Pipez and Mekanism pipes). 

### Steps to reproduce

Havent been able to seems to happen at a random time.

- I tryed if its a problem with the backup when it tryes to take a backup it gets glitchy but that wasnt it
- I tryed to play around with chunkloading but didnt change a thing either

### Expected behaviour

The Tunnels should not be disconnecting between the worlds

### Additional information

Im trying to capture the excact problem and moment it happens ill keep testing and will update the issue

**Comment by PaXilinski** [comment]
Sorry for the late response. So it seems to be happening hwen i reload my world, the tunnels lose the connection to the Overworld

**Comment by TheonlyTazz** [comment]
this will be fixed in V4.4.0 of Compact Machines... unsure when this is getting released tho
[Compact Machine Issue](https://github.com/CompactMods/CompactMachines/issues/524#issuecomment-1156655483)

**Comment by sadovsf** [comment]
4.4.0 should be ready as i understand from this: https://github.com/CompactMods/CompactMachines/issues/532
