### ISSUE TITLE
[Bug]: Steel Ingot/Block from Immersive Engineering machines result in Mekanism Steel Ingot/Block

### ISSUE THREAD

**Issue by Mundif** [FTBTeam/FTB-Modpack-Issues#1046]
### Modpack

FTB Presents Direwolf 20 1.18

### Modpack version

1.6.1

### Describe the bug

As in Issue https://github.com/FTBTeam/FTB-Modpack-Issues/issues/993 https://imgur.com/a/QctG1Zc - IE machines produce Mek blocks and ingots, and steel ingot and block from JEI has no recipes for IE shown, some more like IE crusher - makes Mek steel dust instead of IE steel grit shown in JEI, anything steel related in IE is wonky I guess. 
I though it was fixed but kept needing to do /reload after world load to get it fixed, went digging myself into configs and found potential fix, change in priorities in immersiveengineering-common file, switching IE and Mek order. 
from 
preferredOres = ["ftbic", "mekanism", "immersiveengineering", "minecraft"]

to 
preferredOres = ["ftbic", "immersiveengineering", "mekanism", "minecraft"]

After doing so everything shows as it should on world load and dont need to force it with  /reload anymore.
I did delete everything and make fresh instal 3 times to make sure it wasnt my bad instal.

### Steps to reproduce

-above-

### Expected behaviour

Steel related recipes not being wonky with IE

### Screenshots

![161-1](https://user-images.githubusercontent.com/38189757/176392795-be4ef0f4-313c-4779-a299-04ef324a3fcd.jpeg)
![161-2](https://user-images.githubusercontent.com/38189757/176392812-6b116589-406f-4ad7-ab0a-fc8838fd77ee.jpeg)

**Comment by TheonlyTazz** [comment]
Thanks Mundif! i will be sure to put this in the next update!
