### ISSUE TITLE
[Bug]: Pink slime recipe *not sure if it is the pack or the mod

### ISSUE THREAD

**Issue by IamStig** [FTBTeam/FTB-Modpack-Issues#1047]
### Modpack

Direwolf20 1.18.2

### Modpack version

1.18.2

### Describe the bug

The recipe for pink slime ball is a glass pane with 300mb of pink slime, JEI shows that the result is a pink slime ball AND 300mb pink slime.
The actual result is a pink slime ball and 150mb water. 
Neither the JEI expected result nor the actual result seems to be right, from memory it was only the pink slime ball in the past. Even if something was changed to give a "bonus" fluid result either actual or JEI result is wrong (both can't be right).
Not sure if this is something the mod author has done or a recipe change by FTB was messed up. 

### Steps to reproduce

Check JEI
Get the IF machine that Pink Slime balls are made in (I forget what it is called) - add RF
Put Pink slime and a glass pane in machine
Check the actual result (a pink slime ball and 150mb water) against the JEI expected result of a pink slime ball and 300mb of pink slime
Stand back in awe while concentrating attention on the difference between water and pink slime as well as the difference between 300mb and 150mb.

### Expected behaviour

JEI and actual result to match.....and just the pink slime ball with no fluid

**Comment by quietust** [comment]
The actual recipe outputs Water, so I'm guessing this is a bug in JEI.
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/1.18/src/generated/resources/data/industrialforegoing/recipes/dissolution_chamber/pink_slime_ball.json

This also confuses the Applied Energistics 2 Pattern Encoder Terminal, and it probably also confuses the Pattern Grid from Refined Storage.

**Comment by IamStig** [comment]
It isn't a huge problem on RS, just delete the result slime in the pattern and void the water from the machine. I can't recall any process in that machine that has a fluid that is wanted from it so voiding all fluid output is simple enough. I guess AE2 is also simple to do.

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/177305697-c4d7915d-816f-40ff-b0e2-ed6326ced31b.png)
fixed in dev
