### ISSUE TITLE
[Bug]: Crash on world load after update

### ISSUE THREAD

**Issue by Albertostadas** [FTBTeam/FTB-Modpack-Issues#1048]
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Log Files

Crashlog
https://pste.ch/ahidugimey.rb
Log
https://pste.ch/qidamenuxi.md
Console Log
https://pste.ch/paqagatije.md

### Describe the bug

After updating the modpack from 2.0.9 to 2.12.1 a crash happens everytime I try to load my save from 2.0.9. When using a fresh instance with the old savefile, the problem persists.

### Steps to reproduce

1. Start a world in a version prior to version 2.12.0
2. Progress past an unknown stage
3. Update the modpack to version 2.12.1
4. Try to load said world

### Expected behaviour

I expect the world to load without crashing

### Screenshots

![40e859e36bebb97d287cee76d18eb58e](https://user-images.githubusercontent.com/12597884/176449833-d000601b-ec79-4f65-afd3-8d3492dc7abb.png)

**Comment by Albertostadas** [comment]
Updating PAE2 worked, thank you very much!

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

We may have something up our sleeves, some may call it a remaster, keep an eye out on our social media platforms for more information.
