### ISSUE TITLE
[Bug]: Stoneblock 2 gets stuck on loading

### ISSUE THREAD

**Issue by TheSirHunter** [FTBTeam/FTB-Modpack-Issues#1049]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.22.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9010757/latest.log)

### Describe the bug

When launching Stoneblock 2, it will load everything but get stuck at the end.

### Steps to reproduce

I don't know

### Expected behaviour

I expected to launch the game

### Screenshots

https://media.discordapp.net/attachments/805333374428119050/991692390874226768/unknown.png?width=1223&height=676

### Additional information

It was launching perfectly fine until a couple days ago, I don't know what caused this. It also for some reason launched correctly once and broke again.

**Comment by Raidobw2** [comment]
Try removing the minetogether mod from the mods folder, I know of an issue back then. Also if you have any antiviruses (avast, avg, acronis true image) running or a VPN, try to disable them temporarily to see if that resolves it. Let me know

**Comment by TheSirHunter** [comment]
Removing Minetogether worked, thank you so much!

**Comment by Raidobw2** [comment]
Cool, not sure why it's like so for some people but I'll keep it in mind for other users if this happens again. I'll close this as a result since removing it fixed it for you
