### ISSUE TITLE
[Bug]: Immersive Engineering Metal Press with Gear Mold

### ISSUE THREAD

**Issue by bogie1989** [FTBTeam/FTB-Modpack-Issues#1050]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.6.1

### Describe the bug

Gear Mold with the Metal Press is not pressing gears has power has right amount of ingots for the recipe works with plates and rods just fine havnt tested wire mold 

### Steps to reproduce

1. IE Metal Press
2.  Metal Press Mold: Gear inserted
3. 4 Ingots on belt

### Expected behaviour

press the 4 ingots in to a gear

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/32804875/176570410-421e0cbf-e1e3-4d07-84c2-72bd549f414c.png)

**Comment by bogie1989** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/32804875/176570705-67f2e55c-f05c-4eba-a017-5a2821e6ae8e.png)

**Comment by bogie1989** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/32804875/176570840-1334b8b6-600d-47b3-b700-438016908ec5.png)

**Comment by TheonlyTazz** [comment]
After some testing, it actually does work if a single itemstack of 4 or more is dropped.
Somehow items arent getting clumped up into stacks of 64 when dropping them one by one

**Comment by TheonlyTazz** [comment]
fixed in future update (v1.7.0)
