### ISSUE TITLE
[Bug]: FTB One won't download

### ISSUE THREAD

**Issue by BlazeTXO** [FTBTeam/FTB-Modpack-Issues#1053]
### Modpack

FTB ONE

### Modpack version

1.2.1

### Describe the bug

hay i been setting for a wile and with the ftb leacher the pack stays at 0.00 prepare to downlode help

### Steps to reproduce

1 ftb app
2 search FTB ONE
3 downlode the latis version

### Expected behaviour

to downlead the pack 

### Screenshots

![Capture](https://user-images.githubusercontent.com/108504223/176814147-c47539c8-5443-4cb8-8fee-d3655c676f3f.PNG)

### Additional information

i tride going to preveis versions but still 0.00

**Comment by Draylynn** [comment]
Open task manager; Kill Overwolf processes + Java.
Relaunch the FTB App, try again.
_Sometimes the connection can be interrupted, timeout for an array of reasons and it just needs a lil' kick._

If it continues, are you able to grab any logs to share? C:\Users\USERHERE\AppData\Local\.ftba\logs

**Comment by Raidobw2** [comment]
Hello @BlazeTXO, the log Draylynn referred to will help a lot with this problem. If you press Windows + R, you will be able to put `%localappdata%\.ftba\logs` in the box and press "Ok".
Take the `latest.log` file there and drag it to this window to upload it here.

Additionally, feel free to write in your native language, this will ease communication.
