### ISSUE TITLE
[Bug]: Sodium for forge is crashing FTB OceanBlock

### ISSUE THREAD

**Issue by SoftGuardian** [FTBTeam/FTB-Modpack-Issues#1055]
### Modpack

FTB OceanBlock

### Modpack version

1.14.0

### Log Files

https://pastebin.com/MwJzxGHY

### Describe the bug

Ports of sodium to forge were fine using in the pack in previous versions but now none of them works and crashes my game after a a couple of seconds from loading a world. It first starts out by rendering nothing but entities then when I move or brake a block it crashes. Optifine is terrible it doesn't change anything at all so I decided to use magnesium, halogen or rubidium and none of them worked. I'm guessing a mod is causing it?

### Steps to reproduce

1. Add any sodium port to forge 
2. Open/create a world
3. See the results

### Expected behaviour

I thought it worked with the pack before, or maybe I added an incompatible performance mod.

### Screenshots

![2022-07-01_13 10 13](https://user-images.githubusercontent.com/73778546/176891946-c5d4c771-8f4e-4759-8407-0b2601a4dc6c.png)

**Comment by TheonlyTazz** [comment]
Sodium isnt officially supported on Oceanblock.

**Comment by SoftGuardian** [comment]
I'm not saying it's sodium. It's magnesium, a port to forge. But I managed to solve it by changing betterendforge to betterenreforked
