### ISSUE TITLE
[Bug]: Claimed Chunks not editable after update

### ISSUE THREAD

**Issue by v-tron** [FTBTeam/FTB-Modpack-Issues#1057]
### Modpack

Direwolf20 1.18

### Modpack version

1.6.1

### Describe the bug

After updating from 1.4.1 to 1.6.1 the chunks I claimed when not in a team yet are shown as belonging to me only and not the team anymore. Beforehand all the chunks we claimed as players got shown as belonging to the team after we joined it. Furthermore I can't unclaim or force load these chunks anymore, even thought they belong to me. Chunks that were claimed after the teams creation are shown as belonging to the team and are modifyable.

### Steps to reproduce

1. Claim Chunks when not in a team
2. Create Team 
3. Update server
4. Chunks claimed before joining team are now owned by single players again and not the team and can't be modified anymore in the claim map

### Expected behaviour

Claimed Chunks belong to Team after update and are editable

**Comment by TheonlyTazz** [comment]
to fix this remedy short termed, you can unclaim them with 
`/ftbchunks admin unclaim_as <playername>`
