### ISSUE TITLE
[Bug]: FTB Revelation won't load whatsoever

### ISSUE THREAD

**Issue by dragonkid828** [FTBTeam/FTB-Modpack-Issues#1059]
### Modpack

FTB Revelation

### Modpack version

3.6.0

### Log Files

my logs: https://paste.atlauncher.com/view/ab7d2196-d45b-4a05-b895-6121517737e8
girlfriend's logs: https://paste.atlauncher.com/view/2e3b2b0e-6267-42c3-9337-27be2bdfea0a
logs of a brand new install: https://paste.atlauncher.com/view/c8ec2c13-fc07-4d63-b390-c9389b20d277

### Describe the bug

A few days ago, me and my girlfriend were trying to log into our server for Revelations that I host, and both our clients kept freezing at the exact same point. That point being the "7/7 mod initialization" load screen. This has never happened before, and I'm not sure what's causing it.

### Steps to reproduce

1. Boot up Revelation
2. Wait until the end of initialization
3. Game freezes

### Expected behaviour

Should go to the menu screen of Revelation

### Screenshots

https://i.imgur.com/l4qAk9Y.png

**Comment by Raidobw2** [comment]
Hello, try removing the mod file `MineTogether-1.12.2-2.4.5.jar` from all affected games (all clients as well as server). This is available in the FTB App from settings:
![image](https://user-images.githubusercontent.com/17010632/177020773-d6a6c9c1-d957-4e79-823d-c060a0caf17f.png)
Then Open Folder:
![image](https://user-images.githubusercontent.com/17010632/177020779-87ecdc7c-a99e-4e1c-b1c8-151599758b6b.png)
Open the mods folder:
![image](https://user-images.githubusercontent.com/17010632/177020787-909c72c4-5570-4820-abea-b22fa5aaa683.png)
Delete this file:
![image](https://user-images.githubusercontent.com/17010632/177020792-e0905bda-0d8f-49a9-8556-3aed67806bb8.png)

Let me know if that solves it. There has been similar loading problems on StoneBlock 2 for some people and this mod seems to have caused it.

**Comment by tailcat** [comment]
Had the same problem and the solution worked for me.  Using the FTB launcher had no problems with the modpack but in the normal minecraft launcher I encountered the problem.

**Comment by Raidobw2** [comment]
Awesome, glad to know that worked at least. I'll assume this will work for dragonkid828 as well, so I'll close this support request as it appears solved. I'll poke the CreeperHost team about it as well
