### ISSUE TITLE
[Bug]: Sentient Bow does not charge any Will into Tartatic Gems

### ISSUE THREAD

**Issue by yuu-electrum** [FTBTeam/FTB-Modpack-Issues#1061]
### Modpack

FTB Interactions

### Modpack version

2.12.0

### Describe the bug

Killing hostile mobs by ~~Infinity-enchanted~~ Sentient Bow does not charge the Gems with Will, as Sentient Sword still works for it. I am sure that the Bow had been gathering Will from defeated hostile entities.
Does the Sentient weapons degrades when their durabilities are consumed or killed the same type mobs too much? Then it makes sense.

### Steps to reproduce

1. Have the Sentient Bow and any kind of Tartatic Gems in your hand.
2. ~~Give it Infinity enchantment with Enchantment Table.~~
3. Kill any hostile mobs with the Bow.
4. You will see Gems keeping empty.

### Expected behaviour

Gems are charged with Will.

**Comment by yuu-electrum** [comment]
I found that a buggy result stays same even in newly-created world, and even if the weapon is not enchanted.

**Comment by KorewaLidesu** [comment]
I don't think Sentient Bow can be use to replace Sentient Sword
Maybe you just equip Sentient Bow at off-hand while sword one in main hand
*Minecraft logic of counting dmg from main hand wep*

**Comment by Saereth** [comment]
only weapons that implement IDemonWillWeapon drop wills, this includes the sentient sword, axe, scyuthe, pickaxe and shovel. The bow does not implement this method and therefor does not trigger will to be dropped from the target. If it works with a sentient item in your offhand its likely a bug that wont be fixed but there is no code for the bow to specifically drop will in 1.12.2 bm
