### ISSUE TITLE
[Bug]: Module routers & Bedrock ore's incapability

### ISSUE THREAD

**Issue by Killogoom** [FTBTeam/FTB-Modpack-Issues#1062]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.18.2

### Describe the bug

The mod modular routers doesn't seem to play nice with bedrock ores. I tried to use the breaker module on it to try and automate some ore collection, but it mined the block, as in the router mined the bedrock completely and now I have a hole in the world.

### Steps to reproduce

1. get a modular router
2. place on bedrock ore (I was using it on gold ore)
3. set up breaker module to dig right below the router (I make it with a netherite pick, overkill I know, but I thought why not.)
4. remove router to see your new hole to the void

### Expected behaviour

I thought I could use the breaker module to mine the block as an easy way to automate some ore until I could get the resources for something better.

### Screenshots

![Hole_In_The_World](https://user-images.githubusercontent.com/56934154/177031974-bfa9c5a8-0614-4e35-a357-696c64fcdada.png)

**Comment by Raidobw2** [comment]
I've relayed it to the mod authors, thanks for the report!

**Comment by Raidobw2** [comment]
I'll need to check this again for 1.3.0. I had to revert some changes in 1.2.0 since some compatibility broke.

I ensured the RFTools builder worked, so you can try that one for now

**Comment by Raidobw2** [comment]
Fixed the interaction in 1.2.1+
