### ISSUE TITLE
[Bug]: Game no respond before showing mojang logo with certain mods

### ISSUE THREAD

**Issue by ffflzsbhehe** [FTBTeam/FTB-Modpack-Issues#1066]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.6.1

### Log Files

https://pastebin.com/RhRKQAAx

### Describe the bug

gameversion:1.18.2 forge:40.1.52 java:17.0.2

mod pack:dw20 1.18   1.6.1

The game window showed itself but kept freezing (no response) on a white screen instead of showing the Mojang logo while other people froze for a short time and the game started.

I tried to uninstall some mods, but eventually, I found out that kubejs, thermal expansion and thermal foundation caused the game to freeze, or at least stopped freezing when I deleted them.

### Steps to reproduce

1. Open the game
2. experiencing no response with white screen
3. delete kubejs, thermal expansion and thermal foundation
4. Game started

### Expected behaviour

No respond if not delete kubejs, thermal expansion and thermal foundation

**Comment by Raidobw2** [comment]
Hi, if you leave the problematic mods in and wait 5 to 10 minutes without touching the window, does the white screen change into the Mojang logo? That white screen is where a lot of the mod loading happens, and sometimes can take some time to switch to the Mojang logo
