### ISSUE TITLE
[Bug]: Quark + Immersive Engineering allows infinite Nether Wart duplication

### ISSUE THREAD

**Issue by quietust** [FTBTeam/FTB-Modpack-Issues#1067]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.6.1

### Describe the bug

Quark changes the Nether Wart Block recipe to only require 2x2 and adds a new 3x3 recipe to make a "Nether Wart Sack" (which can be uncrafted and is thus compatible with Compacting Drawers).

However, Immersive Engineering's Crusher recipe still gives 9 Nether Wart from a single Block, allowing for rapid item duplication (compared to the Garden Cloche, anyways).

### Steps to reproduce

1. Craft 4 Nether Wart into a Nether Wart Block
2. Throw the Nether Wart Block into an Immersive Engineering Crusher
3. Get 9 Nether Wart back
4. Repeat as necessary
5. Profit

### Expected behaviour

Crusher should only give 4 Nether Wart

**Comment by TheonlyTazz** [comment]
thanks alot! fixed by disabling the nether wart sack
