### ISSUE TITLE
[Bug]: FTB Academy 1.16 Quests locked even after finished school

### ISSUE THREAD

**Issue by afolk2** [FTBTeam/FTB-Modpack-Issues#107]
### Modpack

FTB Academy 1.16

### Modpack version

1.2.0

### Describe the bug

On a LAN world with my wife. 
Sometimes she can open the quest book with no issues, other times a toast pops up that says "Quests Locked". Not sure what is causing the issue but if we join a team and then leave it she can access her quests again. 

### Steps to reproduce

Start a new world
Open to LAN
Both players finish the entrance school
Player 2 attempts to open quests. < This is the step that does not always reproduce

### Expected behaviour

Quests should open for player 2

**Comment by Raidobw2** [comment]
Hello,

If i remember correctly, the quest book is disabled in all schools, even when going back to them. Can you confirm that the locked quest book happens in the overworld?

Thank you

**Comment by afolk2** [comment]
Yes, it still happens when she is in the overworld. I have also tried to use the school commands to finish the school, but that doesn't help.

**Comment by aaronhowser1** [comment]
How is she leaving the school? 

Maybe try using the command `/school leave`. Have her empty her inventory first, since if it thinks she's in a school it'll clear her inventory.

**Comment by afolk2** [comment]
She tried the button at the beginning as well as the lever at the end.
After that I have tried /school leave and /school complete different times.
She gets teleported into the overworld and she got the xp for finishing it,
but the quests are still locked. I don't remember if I mentioned that if
she joins my team and then leaves or gets kicked out she can access her
quests again. Not sure if it's any help, but it seems like there is a
prerequisite command/quest that keeps her quests locked and for some reason
it doesn't register that hers is done until she shares mine.

**Comment by aaronhowser1** [comment]
These are the scripts related to quest locking:

```js
onEvent('ftbschools.enter_school', event => {
    event.player.data.ftbquests.reset('1EE1D41D7900B802')           //Spawn reward 1
    event.player.data.ftbquests.reset('56681E7921C8850C')           //Spawn reward 2
    event.player.data.ftbquests.reset('1A9737C80961AAB4')           //Spawn reward 3
    event.player.data.ftbquests.reset('6886D70CD60FC58D')           //Spawn reward 4
    event.player.data.ftbquests.reset('62D7A85E2334787A')           //Botania reward
    event.player.data.ftbquests.reset('08B0A46A97A2263B')           //Tech reward 1
    event.player.data.ftbquests.reset('156F049396904095')           //Tech reward 2
    event.player.data.ftbquests.reset('59B1E99A0D19ECC8')           //Astral reward 1
    event.player.data.ftbquests.reset('7145155A532E9978')           //Astral reward 2
    event.player.data.ftbquests.reset('790999AC867AF3EB')           //Astral reward 1
    event.player.data.ftbquests.reset('40C6F1B7A40D52E4')           //Astral reward 1
    event.player.data.ftbquests.locked = true
})

onEvent('ftbschools.leave_school', event => {
    event.player.data.ftbquests.locked = false
    event.player.data.ftbquests.reset('69C2EA7E97F09C40')           //Refined Storage School 1 quest
    event.player.data.ftbquests.reset('64252CFF8AE93B46')           //Refined Storage School 2 quest
    event.player.data.ftbquests.reset('585291CE81345383')           //Tech School quest
    event.player.data.ftbquests.reset('0124FAABD8D77026')           //Astral Sorcery School quest
    event.player.data.ftbquests.reset('746E96B3729981DC')           //Botania School quest
})
```

The resets aren't relevant, but it definitely should unlock after leaving.

**Comment by SilentLumi** [comment]
Tried to play with my friend too, tried "open to LAN" as well as a separate server, she constantly gets her questbook locked and no commands unlock the questing feature for her t_t

**Comment by manmaed** [comment]
@aaronhowser1 any word on this has this been fixed
this will auto close in 2 weeks if no response

**Comment by aaronhowser1** [comment]
It has not been
