### ISSUE TITLE
[Bug]: full client crash holding right click with manasteel shears on propelplant

### ISSUE THREAD

**Issue by Azutte** [FTBTeam/FTB-Modpack-Issues#1070]
### Modpack

direwolf20 1.18

### Modpack version

1.6.1

### Describe the bug

client crashes

### Steps to reproduce

hold manasteel shears, look at propelplant (note: you're supposed to use shears on these), hit right click

### Expected behaviour

harvests plant

**Comment by Raidobw2** [comment]
Hi, could you add your client crash log here? That will help a lot to fix this issue. Inside your modpack installation are a few folders like `config`, `mods`, `logs`... there is one named `crash-reports`, and you'll find the latest crash file in there. You can drag and drop it here, thanks in advance

**Comment by quietust** [comment]
I was able to reproduce the crash in my own world:
[crash-2022-07-05_17.07.50-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9050159/crash-2022-07-05_17.07.50-client.txt)

**Comment by Raidobw2** [comment]
I've written a message in the Mahou Tsukai Discord about this at https://discord.com/channels/626881973398536194/741099110375096340/994113928596574238 (you need to be in that server to access this link). I'll post a follow up later as well
![image](https://user-images.githubusercontent.com/17010632/177476126-83b47d40-4229-4828-b544-bb42da5199d9.png)

**Comment by stepsword** [comment]
update mahou, this is fixed on 34.25

**Comment by Raidobw2** [comment]
Awesome, thanks!
