### ISSUE TITLE
[Suggestion]: Add XNet Gases

### ISSUE THREAD

**Issue by danaYatsuta** [FTBTeam/FTB-Modpack-Issues#1073]
### Modpack

FTB Presents Direwolf20 1.18

### Mod suggestion

Link to mod: https://www.curseforge.com/minecraft/mc-mods/xnet-gases

It just adds mekanism gas support for XNet, which makes it possible to set up XNet system with mekanism gases involved.

**Comment by TheonlyTazz** [comment]
Added in V1.7.0
