### ISSUE TITLE
[Suggestion]: Color chickens eggs quite expensive for a chance of chicken from chickens mod

### ISSUE THREAD

**Issue by 252rer** [FTBTeam/FTB-Modpack-Issues#1074]
### Modpack

FTB One 1.2.1

### Is your suggestion related to a problem? Please describe.

I just went through 64 dandelions to make 8 "yellow chicken egg"s to have none of them spawn a chicken when thrown. Can we either get the spawn egg changed to this recipe instead or have it more like the original mod rate of only requiring one of a color dye to craft the low chance egg?
Edit: maybe a 2/4 dye per low chance egg instead if planning to add a mod with dye doubling would also work.

**Comment by Saereth** [comment]
passed on to chicken devs and it's received several updates since which will be in the new version
