### ISSUE TITLE
[Bug]: AE2 network crashes

### ISSUE THREAD

**Issue by KingAqua94** [FTBTeam/FTB-Modpack-Issues#1077]
### Mod

Applied Energistics 2

### Mod version

11.2.3

### Forge / Fabric version

40.1.19

### Modpack & version

FTB presents direwolf20 1.18 - 1.6.1

### What issue are you having?

I had an import bus attached to the bottom of a sink with an inverted toggle bus in the same block space using a fluix cable to attach them. I had a level emitter outputting a signal for the inverted toggle bus once I had 8,000 buckets of water in the system. My AE2 system would randomly stop working as if it had no power even though I had 2 full dense energy cells nearby. I have been trying to troubleshoot for about a week myself thinking I had something wrong. I noticed the flickering of the network seemed to sync with when the toggle bus received a signal from the level emitter. I disconnected these components and the flickering stopped.

### Steps to reproduce

I had a sink with an import bus attached to the bottom and an inverted toggle bus on the same block space with a fluix cable attaching them going straight down under the inverted toggle bus I had fluix cable branching to the side and then up with a level emitter facing the block space with the inverted toggle bus. I had at most 6 other channels being used on the same cable. There were no acceleration cards being used in the import bus. I was emitting a signal once I had 8,000 buckets of water in a 16k fluid storage cell. I was exporting the water to 3 thermal expansion photogenic insolators 2 of which have resonant upgrades.

**Comment by KingAqua94** [comment]
The game itself does not crash. The AE network simply stops working. I apologize for my confusing wording.

**Comment by Raidobw2** [comment]
Make sure you have sufficient channels available for your setup if power is not an issue. 8 per small cable, 32 per dense cable. Using smart cabling will help seeing channels. Additionally if you want to add your Minecraft world here with some file sharing like Google Drive, I can take a look at it and find out what's happening to cause it to flicker/turn off.
