### ISSUE TITLE
[Bug]: Datapack Error

### ISSUE THREAD

**Issue by Steelcityfan** [FTBTeam/FTB-Modpack-Issues#1078]
### Modpack

FTB OceanBlock

### Modpack version

1.16.5

### Describe the bug

Errors in currently selected datapacks prevented the world from loading. It happened after the game crashed twice.

### Steps to reproduce

1. Click on Singleplayer
2. Click on world
3. Error pops up

### Expected behaviour

I expected it not to go away even after restarting everything.

**Comment by TheonlyTazz** [comment]
Issue has been stale for over a month. Feel free to reopen if the issue still happen after the new update (coming out soon)
