### ISSUE TITLE
[Suggestion]: Add Materialis, Tinkers Construct addon

### ISSUE THREAD

**Issue by Mundif** [FTBTeam/FTB-Modpack-Issues#1079]
### Modpack

FTB Presents Direwolf 20 1.18

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/materialis

It adds many materials and abilities from variety of mods, while standard Tinkers is great I feel this mod gives much more choices and immersion to it while also enhancing other mods that way.

**Comment by TheonlyTazz** [comment]
After discussing this, we have decided to not add this mod for now
