### ISSUE TITLE
[Bug]: Missing/broken or invalid item tags

### ISSUE THREAD

**Issue by InFuRiTy** [FTBTeam/FTB-Modpack-Issues#1080]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.6.1

### Describe the bug

Some recipe paths for item crafting and materials processing require or display items as broken/mislabeled tags using the barrier item of vanilla mc.

These bugs carry over to any kind of auto-crafting or recipe automation. 

MOD: Create Deco
All variants of Andesite cage lamp recipes have incorrect tagged items

MOD: Create café 
Milk tea recipes use incorrect tagged items for all the outputs. eg. peach milk tea 

MODS: FTB IC, Thermal Series and mods with processing in general
Some materials, mainly metal alloys and multi-step items are incorrectly tagged as ores or raw ore variants which doesn't make sense

MOD: Industrial Foregoing
The Material Stonework Factory  machine uses the barrier item as means of step tracking in each recipe - **THIS IS NOT A BUG!!** 

### Steps to reproduce

Load into a world/server
Search in JEI for eg. netherite dust and see the recipes on how to get it
Click uses on the first barrier item you encounter

there are multiple recipes across many tabs that use broken, invalid or incorrect tagged items

### Expected behaviour

All of these recipes should have a valid origin path that makes them back-trackable  or  at least make sense

### Screenshots

https://ibb.co/album/Z15xJD

**Comment by TheonlyTazz** [comment]
All the Create Cafe items has been disabled in JEI, 

I shall go through each of them in the future and try to disable the recipes completly in a future update

**Comment by MacChuck** [comment]
What is the result of this? That create cafe items won't be craftable, or they just won't show up in JEI and be autocraftable?

**Comment by TheonlyTazz** [comment]
the Create Cafe items wont be craftable as we dont have said fruits in the game, and the mod that got used for that in 1.16 hasnt been updated to 1.18 yet (Pam's Trees and Pam's Crops)
