### ISSUE TITLE
[Bug]: Crash while loading world after updating to 1.7

### ISSUE THREAD

**Issue by PanieriLorenzo** [FTBTeam/FTB-Modpack-Issues#1082]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.7

### Log Files

Crash report:
https://pastebin.com/KRjyWMA3

Last lines from console log:
https://pastebin.com/W6scqFdD

### Describe the bug

The world was working in 1.6.1. When updating to 1.7, upon loading the world for the first time, the game crashes. When downgrading to 1.6.1 the world works again.

### Steps to reproduce

1. create a world in 1.6.1
2. do something in the world, I'm not exactly sure what triggers it, I've been playing for quite a bit
3. close
4. update to 1.7
5. open the world
6. the game crashes

### Expected behaviour

The game shouldn't crash when opening the world

### Additional information

I experienced a similar issue when updating from 1.3 but I was able to fix it by copying an older backup, however this time using an old backup didn't work.

**Comment by quietust** [comment]
For some reason, it failed to load `config/Mekanism/generator-storage.toml`. Maybe something in the file changed and now it's broken?

**Comment by PanieriLorenzo** [comment]
I have re-installed 1.7 fresh and moved the save and now it seems to be working. Maybe the instance got corrupted somehow. I'm closing the issue.
