### ISSUE TITLE
[Bug]: FTB Backups ignoring user defined backup limit

### ISSUE THREAD

**Issue by Diversion98** [FTBTeam/FTB-Modpack-Issues#1083]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

I've set in the backups config from FTB Backups to a max of 2 backups.
But it still keeps way more backups than 2.

### Steps to reproduce

1. edit ftbbackups config to set a max amount of backups
2. run the server and wait a couple of hours
3. see the server ignoring the max amount of backups kept

### Expected behaviour

respect the max amount of backups

### Additional information

config:

{
	"enabled": true,
	"command_permission_level": 3,
	"notify_op_only": false,
	"do_not_notify": false,
	"max_backups": 2,
	"backup_cron": "0 0 0/1 1/1 * ? *",
	"manual_backups_time": 0,
	"only_if_players_been_online": true,
	"additional_directories": []
}

**Comment by InFuRiTy** [comment]
Put "FTB Backups ignoring user defined backup limit " as the issue title.

also try deleting or moving all the backups from the folder and let it run again 
if it still goes beyond your set limit then it's definitely a bug..
older backup solutions from 1.7.10/1.12 versions would auto-delete any excess amount of backups if they were above the limit 
from 1.14 and above they kinda bug out or refuse to do it and just overwrite the latest entries depending on the limit value

**Comment by Raidobw2** [comment]
Thanks, I've reported it to the mod author just above. There isn't a more recent version of the mod for now in 1.18.2, so this may have to wait till a new build of the backup mod is released. If you want a maximum of 2 backups for now, you might have to use another backup mod for 1.18.2 on the server

**Comment by Diversion98** [comment]
> Put "FTB Backups ignoring user defined backup limit " as the issue title.
> 
> also try deleting or moving all the backups from the folder and let it run again if it still goes beyond your set limit then it's definitely a bug.. older backup solutions from 1.7.10/1.12 versions would auto-delete any excess amount of backups if they were above the limit from 1.14 and above they kinda bug out or refuse to do it and just overwrite the latest entries depending on the limit value

Yeah i deleted the backups a few times now but it still refuses to respect the config :p

I can say that the 1.16 version works fine tho as i created my own modpack with ftb backup.

**Comment by Raidobw2** [comment]
Should be fixed in 1.2.0, let me know otherwise
