### ISSUE TITLE
[Bug]: Crash when rendering CBMicroblock Stone Panel

### ISSUE THREAD

**Issue by molecules1** [FTBTeam/FTB-Modpack-Issues#1085]
### Modpack

FTB University 1.16

### Modpack version

1.7.0

### Log Files

Crash 1
[crash-2022-07-08_09.57.41-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9073945/crash-2022-07-08_09.57.41-client.txt)
Crash 2
[crash-2022-07-08_10.13.43-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9073944/crash-2022-07-08_10.13.43-client.txt)

### Describe the bug

Every time I go to search "panel" for the void miners I crash.  Crashy logs say under "Ingredient being rendered" that the CBMicroblock Stone Panel is causing a problem.

### Steps to reproduce

1. Search "panel" in JEI
2. Crash

### Expected behaviour

The game not to crash when searching "panel"

**Comment by molecules1** [comment]
Just got another crash, for the Stone Corner
[crash-2022-07-08_14.43.43-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9075187/crash-2022-07-08_14.43.43-client.txt)

**Comment by Raidobw2** [comment]
It looks like there's an issue at https://github.com/TheCBProject/CBMultipart/issues/104 for it, and that the mod's systems are pending a rewrite

**Comment by aaronhowser1** [comment]
2021 😩
I thought I hid all the multiblock stuff from JEI, maybe that got undone for some reason. I'll try to fix.
