### ISSUE TITLE
[Bug]: Mana spreader Beam

### ISSUE THREAD

**Issue by CrimsonBlaze513** [FTBTeam/FTB-Modpack-Issues#1086]
### Modpack

Direwolf20 1.18

### Modpack version

v1.7.0

### Describe the bug

Botania mana spreader beam is showing up through walls/floors.

### Steps to reproduce

Having an active mana spreader and then going behind a wall/floor.

### Expected behaviour

The mana beam to not be there

### Screenshots

![2022-07-08_19 28 16](https://user-images.githubusercontent.com/108965134/178088207-41648bd9-0216-4ee4-9f0b-a1eae4e8ac81.png)

**Comment by faanlez** [comment]
Did you perhaps do something that lets you see them through walls? Perhaps equip a curio of some kind without actually reading what it is for?

**Comment by Raidobw2** [comment]
Is Optifine installed / any other modifications?

**Comment by CrimsonBlaze513** [comment]
It was what Faanlez had suggested, I didn't realize I still had my manaseer monocle on. My apologies; I usually don't keep it on and forget it allows you to see the mana beams through the walls. Thank you.
