### ISSUE TITLE
[Bug]: 1-2 FPS on game makes it unplayable

### ISSUE THREAD

**Issue by Supergamer2E** [FTBTeam/FTB-Modpack-Issues#1089]
### Modpack

Plexiglass Mountain

### Modpack version

1.0.2 and 1.1.1

### Describe the bug

Whenever I load into a world, I am only getting 1-2 fps, with no signs of improvement over time.

### Steps to reproduce

1. Load Modpack
2. Load World

### Expected behaviour

Run games with better fps

**Comment by Raidobw2** [comment]
Hi, most likely due to mipmaps if your graphics card is AMD. Try this:

> Disabling mipmapping on an AMD graphics card will boost FPS. This is because AMD handles OpenGL mipmapping differently than NVIDIA does, and it makes the graphics card work super hard. Open the menu in-game and click "Options", then "Video Settings". Slide the "Mipmap Levels" slider to the left to "OFF", and resume playing.

Please close the issue if that did it!

**Comment by Supergamer2E** [comment]
That helped a lot! still pretty laggy, but it's more playable. anything you can think of to help with this?

**Comment by Raidobw2** [comment]
Yes, first try uncapping your FPS in game by setting Vsync to off. Then cap it right above your monitor's refresh rate. Most monitors have a refresh rate of 60 or 144 hertz. That means they refresh 60 or 144 times a second, so they'll display up to 60 or 144 FPS at most.
For instance if you have a 144Hz screen, you want to cap it near 160-170 FPS to help with lag spikes.

I have a 60Hz screen, so here's mine. I cap it at 80 FPS
![image](https://user-images.githubusercontent.com/17010632/178132625-0357b1cf-f5cc-413f-aab0-fee4a55fb8a9.png)

Also try enabling Forge's offthread render. That might help a lot too. See below:

> In your modpack folder, open the config folder and the file `forge-client.toml` with a text editor. Change the setting `alwaysSetupTerrainOffthread` to `true`, save the file, and start your game. This setting boosts FPS mostly in Singleplayer, since rendering will be done on a separate thread. It also solves lag related to block placement.

I hope that helps
