### ISSUE TITLE
[Bug, TheOneProbe]: Repairing TOP diamond helmet with another helmet crashes game 

### ISSUE THREAD

**Issue by Firepoppy5** [FTBTeam/FTB-Modpack-Issues#109]
### Modpack

FTB Oceanblock

### Modpack version

1.2.0

### Log Files

[crash-2021-10-09_19.17.55-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7316604/crash-2021-10-09_19.17.55-client.txt)

### Describe the bug

When to repair a diamond probe helmet in an anvil with a regular diamond helmet, the game crashes. Double checked with the same action with the same results

### Steps to reproduce

1. Go to anvil
2. open anvil
3. place damaged diamond probe helmet in first slot of anvil
4. shift-click damaged diamond helmet into second slot of anvil
5. wait while minecraft stops responding

### Expected behaviour

To repair a diamond probe helmet, using a regular diamond helmet

**Comment by TheonlyTazz** [comment]
fixed
