### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GrumpyChunks** [FTBTeam/FTB-Modpack-Issues#1090]
### Mod

FTB Industrial

### Mod version

1605.1.3-build.122

### Forge / Fabric version

36.2.26

### Modpack & version

FTB Ulitmate Aniversary

### What issue are you having?

There seems to be a fluid cell dupe bug. Steps to reproduce below.

### Steps to reproduce

1. Using an empty Thermal Magmatic Generator
2. Have three fluid cells containing lava in a single stack/slot
3. right click cells in to generator
4. only 1 cell empties, but the generator gets a full 2 buckets of lava
5. you can then remove 1 bucket of lava from the generator
6. you now have 1 bucket in the generator and 3 full fluid cells
7. repeat steps 2 - 6 until you have duplicated as much lava as you want

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
