### ISSUE TITLE
[Bug]: DW20 1.18 won't start FTB App

### ISSUE THREAD

**Issue by kom30** [FTBTeam/FTB-Modpack-Issues#1091]
### Mod

direwolf20 1.18

### Mod version

ftb 1.18.2-forge-40.1.25

### Forge / Fabric version

 1.18.2-forge-40.1.25

### Modpack & version

direwolf20 1.8.2

### What issue are you having?

game not starten

### Crashlogs

[latest.log](https://github.com/FTBTeam/FTB-Mods-Issues/files/8806070/latest.log)

### Steps to reproduce

cant

**Comment by Raidobw2** [comment]
If this is still an issue I'd recommend going to the FTB Discord https://go.ftb.team/discord. You can go in the support channel and ping me there directly, my name is "R3GEN" there.
