### ISSUE TITLE
[Bug]: Integrated Dynamics Squeezer dupe bug

### ISSUE THREAD

**Issue by senjinthedragon** [FTBTeam/FTB-Modpack-Issues#1092]
### Mod

Integrated Dynamics

### Mod version

IntegratedDynamics-1.18.2-1.10.17

### Forge / Fabric version

1.18.2-forge-40.1.25

### Modpack & version

FTB Presents Direwolf20 1.18 1.3.1

### What issue are you having?

Found a duplication bug with the squeezer from Integrated Dynamics.

### Steps to reproduce

1. Put down a squeezer
2. Put any item into squeezer
3. Pick up squeezer with shift-rightclick
4. Put back down squeezer
5. Your item will pop out and second copy will stay inside the squeezer
6. Goto 3, rinse and repeat

### Anything else to note?

Don't know if it's another mod that lets you pick it up with shift-rightclick.

**Comment by Raidobw2** [comment]
Hmm, normally that would have been fixed in #818, though your version of the pack is higher than there. Perhaps it's still an issue, I'll leave this opened for our modpack maintainer to see. Thanks for reporting

**Comment by TheonlyTazz** [comment]
fixed this, Integrated Dynamics is now blocked in Carryon
