### ISSUE TITLE
[Bug]: Repurposed Structures Ocean Pool doesnt generate treasure maps correctly

### ISSUE THREAD

**Issue by BadsyEdgecat** [FTBTeam/FTB-Modpack-Issues#1093]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

Ocean Lootr Pool for Repurposed Structures generates blank maps named "Buried Treasure Map".

### Steps to reproduce

Somehow create a Lootr chest with the correct pool (should be in the screenshot, if it works), and open new ones until it generates an incorrect map.

### Expected behaviour

The maps should be the vanilla Buried Treasure Maps.

### Screenshots

[https://cdn.discordapp.com/attachments/983080030248796230/995544568084828281/unknown.png](url)

Sorry, I dont know how to make this embed or if this link will even work.

**Comment by aaronhowser1** [comment]
Working image:

![](https://cdn.discordapp.com/attachments/983080030248796230/995544568084828281/unknown.png)

**Comment by Raidobw2** [comment]
I've checked a few maps, that might have been fixed... somehow. I could not reproduce it after obtaining a few maps from the chests and the minecraft loot tables themselves.
![image](https://user-images.githubusercontent.com/17010632/197991334-a01258d3-03b4-470d-82e8-e8189eb18b2a.png)
![image](https://user-images.githubusercontent.com/17010632/197991350-54c6b239-8075-4c49-8387-245f33e14736.png)
![image](https://user-images.githubusercontent.com/17010632/197991367-a560c564-ec3e-42ea-b3be-4913e9b37700.png)
![image](https://user-images.githubusercontent.com/17010632/197991400-60179853-ec5a-41f0-9687-2367853908d1.png)

This seems to be working in both those loot tables, so I'll mark as fixed:
![image](https://user-images.githubusercontent.com/17010632/197991473-23f2d11a-9a35-474e-a969-000103cf468c.png)

**Comment by Raidobw2** [comment]
1.2.1 is released and should work properly
