### ISSUE TITLE
[Bug]: Ars Nouveau mobs spawn inside my base even when well lit up

### ISSUE THREAD

**Issue by Skirty** [FTBTeam/FTB-Modpack-Issues#1094]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.7.0

### Describe the bug

Wilden mobs are spawning inside my base in well lit up areas. This is an issue with the version of Ars Nouveau in the current version of the pack. (There's an updated version of the mod which fixes this).

### Steps to reproduce

Go to any well lit area
You will find many Wilden mobs in the different iterations (and no other mobs because of the light level)

### Expected behaviour

To be safe from mobs spawning inside my buildings.

### Additional information

The issue is with the Ars Nouveau mod, as per this (and there's an updated version): https://github.com/baileyholl/Ars-Nouveau/issues/597

**Comment by TheonlyTazz** [comment]
fixed indev
