### ISSUE TITLE
[Bug]: IE blast furnace + iron block = mekanism steel block

### ISSUE THREAD

**Issue by Azutte** [FTBTeam/FTB-Modpack-Issues#1095]
### Modpack

direwolf20 1.18

### Modpack version

1.7.0

### Describe the bug

it outputs mek steel instead of IE steel

### Steps to reproduce

insert coal coke block, iron block into immersive engineering (regular) blast furnace multiblock, wait forever, it outputs a mekanism steel block

### Expected behaviour

it outputs IE steel block, but really it's fine since steel ingots craft to IE steel block anyway, but I might as well say something y'know?

**Comment by Raidobw2** [comment]
Thanks for the report, we'll have a look at it. That might however be intended, since unification methods try to make one material of a type be the only material (such as Mekanism steel be preferred here it seems). I'll leave it up for review, but this may possibly not change

**Comment by Mundif** [comment]
As in this issue, https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1046 It should have been fixed in 1.7.0, tried fresh pack instal? And/or check config file in issue.

**Comment by TheonlyTazz** [comment]
be sure to update your configs folder aswell when updating,
Immersive Engineering Config files had been changed in terms of priotization...
Not an Issue
