### ISSUE TITLE
[Suggestion]: Add Blood Magic to DW20 1.18

### ISSUE THREAD

**Issue by dinckelman** [FTBTeam/FTB-Modpack-Issues#1097]
### Modpack

https://feed-the-beast.com/modpack/ftb_presents_direwolf20_1_18

### Is your suggestion related to a problem? Please describe.

Blood Magic recently got a 1.18 release, and it's sufficiently functional to be included in this modpack. Most features (up to tier 4, and some tier 5) are present in its current state. More are being worked on regularly. 

Even in its current state, the mod provides a ton of utility, that requires player progression to be used. It would be a good fit for the general theme of the pack, and has been included in DW20 packs before

### Mod suggestion

[Blood Magic](https://www.curseforge.com/minecraft/mc-mods/blood-magic) is a famous magic mod, which utilizes a blood network to cast spells, and perform rituals. A lot of what Blood Magic offers, allows for more flexibility with automation, and convenient alternatives for items that already exist in other forms. For example, lava through Serenade of the Nether, or semi-infinite torch through the Blood Lamp sigil

**Comment by Raidobw2** [comment]
Thanks for the suggestion
