### ISSUE TITLE
[Suggestion]: Add backup path option to ftbbackups2 config

### ISSUE THREAD

**Issue by kylerhenry** [FTBTeam/FTB-Modpack-Issues#1103]
### Modpack

Any that use this mod

### Is your suggestion related to a problem? Please describe.

N/A

### Mod suggestion

https://github.com/FTBTeam/FTB-Backups

Currently the config is the following:
``` 
{
        // Allow the creation of backups automatically
	"enabled": true,
	// Permission level to use the /backup command
	"command_permission_level": 3,
	// Only send backup status to server ops
	"notify_op_only": true,
	// Don't send backup status at all
	"do_not_notify": false,
	// Maximum number of backups to keep
	"max_backups": 48,
	/* This is done with Javas implementation of cron, More info here 
	    (https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm)
	*/
	"backup_cron": "0 */30 * * * ?",
	// Time between manual backups using the command
	"manual_backups_time": 0,
	// Only run a backup if a player has been online since the last backup
	"only_if_players_been_online": true,
	// Additional directories to include in backup
	"additional_directories": []
} 
```
This suggestion would be to add the line below to control `backupsFolder` in the `Backups` enum in `src/main/java/com/feed_the_beast/mods/ftbbackups/Backups.java`. Currently this is hardcoded as
```
backupsFolder = FTBBackupsConfig.folder.trim().isEmpty() ? FMLPaths.GAMEDIR.get().resolve("backups").toFile() : new File(FTBBackupsConfig.folder);`
```
Suggested change to config:
```
// The path where backups will be saved
"backupsFolder": "./backups"
```

**Comment by Raidobw2** [comment]
Thanks for the suggestion, however that is unfortunately not behavior we can control as pack developers. This requires a change in the mod and I see you've linked your comment on the appropriate tracker for FTB Backups 2 https://www.curseforge.com/minecraft/mc-mods/ftb-backups-2 (thank you for writing it there too!).
If that feature makes it to a release version will be in the hands of our mod developers, then this will make it into the packs through normal update cycles. If you do need to specify a backup path, I suggest looking into other backup mods for the moment. I hope that helps a bit, and thanks for suggesting that change to FTB Backups 2
