### ISSUE TITLE
[Bug]: Graphic Issues [Need More Information]

### ISSUE THREAD

**Issue by subwayfootlongs** [FTBTeam/FTB-Modpack-Issues#1105]
i was playing my world for about 3 days i was changing graphics to get better fps i achieved that goal, but when the settings kicked in i noticed my ars lights and spells are not showing anything my lights are still there but not capable of being seen pls help and fix

### Mod

ars nouveau

### Mod version

latest direwolf20 pack

### Forge / Fabric version

latest direwolf20 pack

### Modpack & version

latest direwolf20 pack

### What issue are you having?

sorry i dont now wat version im playing on all i know its the latest version direwolf20 pack

![image](https://user-images.githubusercontent.com/109109220/178353261-df64f5f9-d430-46e7-bdf1-a0ccb61e0da1.png)

### Steps to reproduce

changing settings but nothing got to do with mods just normal minecraft settings

**Comment by Raidobw2** [comment]
Try checking your Video Settings for Particles, and if it's at minimal or decreased change it back to normal
