### ISSUE TITLE
[Bug]: JEI Searchbar Bug and Key binds

### ISSUE THREAD

**Issue by MCScarface** [FTBTeam/FTB-Modpack-Issues#1107]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.5.0/1.7.0

### Describe the bug

I just downloaded the modpack for the first time. When I tried to click on the JEI search bar with my mouse it wouldnt let me. it didnt do anything. Then when I went to change the key binds for select search bar it wouldnt let me do anytthing. When I clicked on the keybind it intantly turned into st\st\st and wouldnt let me assign a new key bind. That was the same for all keybinds I clicked. I also noticed when I hit R on a recipe it would open up the recipe, but when I hovered over any  other form of crafting on the top bar of the recipe screen it would make a repeated clicking sound and change to that menu .

### Steps to reproduce

1. Go to Inventory
2. Click on the search bar for JEI
Second bug
1. Go to ESC menu
2. go to options
3. Go to controls
4. go to keybinds
5. click on anykey bind
Third bug
1. Go to inventory
2. Click R on any item
3. hover over the different way of crafting

### Expected behaviour

The search bar wont let you select the search bar to type. The Key bind you click on will turn to st\st\st. And the craft option icon you hover over will make alot of clicking sounds and change over without you clicking it

### Screenshots

![Screenshot (31)](https://user-images.githubusercontent.com/107900826/178725327-c21d7fc9-a95e-4f7b-ae58-b713998f5471.png)
![Screenshot (32)](https://user-images.githubusercontent.com/107900826/178725341-36614f82-1174-4dda-b920-4febb05b284f.png)

**Comment by quietust** [comment]
Do you have any special input devices attached to your computer?

**Comment by MCScarface** [comment]
> Do you have any special input devices attached to your computer?

No I don’t. I just have my mouse, keyboard and dac, and mic connected to my PC. Although my mouse is connected to a USB port that is on my keyboard and not directly connected to my Pc

**Comment by Raidobw2** [comment]
Hi, what exactly did you mean by "dac" when talking about your keyboard? Any macros as well?

Also, did you try a computer restart and unplugging devices other than the keyboard and mouse?

**Comment by MCScarface** [comment]
> Hi, what exactly did you mean by "dac" when talking about your keyboard? Any macros as well?
> 
> Also, did you try a computer restart and unplugging devices other than the keyboard and mouse?

By Dac I mean a Dac for my headphones. Its just connected to the PC. No macros. I restarted the computer many times and re installed Direwolf 20 into many different versions and the same one again. After quietust asked me if I have special inputs the only thing I could think of is that my mouse was connected into a USB port in my keyboard. After I connected it directly to my PC it solved the problem thank you all!!!! Very helpfull!!!!!

**Comment by TheonlyTazz** [comment]
glad it got resolved :)

**Comment by MCScarface** [comment]
> in addition what @Raidobw2 said, i would recommend reinstalling the Direwolf20 Instance

Thank you very much for the tip. I did that many times and didnt help but quietust got me thinking maybe my mouse being connected to my keyboard was causing the issue and it was. Thank you

**Comment by quietust** [comment]
I'm actually surprised that made a difference, because USB devices should behave exactly the same no matter where they're plugged in - the only possible difference is that a device might not work *at all* because the parent device can't provide it with enough electrical power.
