### ISSUE TITLE
[Bug]: RFToolsPower accepted fuel source missing

### ISSUE THREAD

**Issue by neilio500** [FTBTeam/FTB-Modpack-Issues#1109]
### Modpack

FTB Direwolf 1.18

### Modpack version

1.7.0

### Describe the bug

RFToolsPower Coal generator will not accept Mekanisms Charcoal Block even though it accepts regular charcoal and regular coal blocks

### Steps to reproduce

1. Place Coal Generator from RFToolsPower
2. Try inserting Charcoal Block from Mekanism

### Expected behaviour

Should allow Charcoal Blocks

**Comment by Raidobw2** [comment]
Hello, this is not currently possible with the mod, but I can make a suggestion to RFTools Power.
Valid items come from the "Items" class
![image](https://user-images.githubusercontent.com/17010632/178903743-efe7a030-7ed1-43be-91ef-a9987c1e64eb.png)
And that class only uses items from the base game, hence why only normal coal and charcoal works currently
![image](https://user-images.githubusercontent.com/17010632/178903753-e54e7a68-8581-49e7-a245-009c1aa21626.png)

**Comment by Raidobw2** [comment]
I've relayed your suggestion to RFTools Power, see above
