### ISSUE TITLE
[Bug]: Superflat uses normal worldgen

### ISSUE THREAD

**Issue by Sigma-Erebus** [FTBTeam/FTB-Modpack-Issues#1110]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.7.0

### Describe the bug

Create a new superflat world, but it does not generate a superflat world

### Steps to reproduce

1. Launch game
2. Go to Singleplayer
3. Create new world
4. Select Creative mode (not sure if matters)
5. Set worldgen to superflat (default template)
6. Wait for world to gen
7. See that the generated world is not superflat

### Expected behaviour

When generating a superflat world, I expect a superflat world to be generated

### Screenshots

![image](https://user-images.githubusercontent.com/65902131/178926504-b83404de-1c0b-46c4-aa85-96888aa9465c.png)
"Superflat World Gen"

**Comment by TheonlyTazz** [comment]
This issue is caused by the mod "Terralith" which was originally a modpack. by disabling/removing that mod you can regain the ability to make a flat world.
On the modpack side, i cannot remove the Mod, but you can do so on your instance if u want to make a flatworld

**Comment by Sigma-Erebus** [comment]
I found that alternatively a mining dimension works as well
