### ISSUE TITLE
[Bug]: Client-side crash on FTB Chocolate

### ISSUE THREAD

**Issue by batman202012** [FTBTeam/FTB-Modpack-Issues#1113]
### Modpack

FTB Chocolate

### Modpack version

1.1.0

### Log Files

[crash-2022-07-10_16.40.17-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9114581/crash-2022-07-10_16.40.17-client.txt)
[crash-2022-07-10_20.45.10-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9114582/crash-2022-07-10_20.45.10-client.txt)
[crash-2022-07-13_23.23.19-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9114583/crash-2022-07-13_23.23.19-client.txt)

### Describe the bug

Modpack crashes on client when rendering framed blocks in game. Sometimes framed blocks are missing textures after teleporting (using /home or /tp). Might possibly be caused by ftb chunks chunk loading. I will make an edit after running some tests with the chunks unloaded.

### Steps to reproduce

Set several framed blocks side by side, teleport to and from location repeatedly until textures start glitching. Repeat enough and the game will crash.

### Expected behaviour

Client to not crash

**Comment by manmaed** [comment]
This  issue is now Stale
