### ISSUE TITLE
[Bug]: A few other random client crashes I've ran into that I have no idea how they happened

### ISSUE THREAD

**Issue by batman202012** [FTBTeam/FTB-Modpack-Issues#1114]
### Modpack

FTB Chocolate

### Modpack version

1.1.0

### Log Files

[crash-2022-07-10_19.45.50-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9114617/crash-2022-07-10_19.45.50-client.txt)
[crash-2022-07-11_13.01.37-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9114618/crash-2022-07-11_13.01.37-fml.txt)
[crash-2022-07-11_16.32.16-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9114619/crash-2022-07-11_16.32.16-client.txt)
[Uploading crash-2022-07-11_21.58.58-client.txt…]()
[crash-2022-07-08_21.33.07-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9114621/crash-2022-07-08_21.33.07-fml.txt)

### Describe the bug

Sometimes fml fails to load mods (check fml.txt files above) The other crash reports randomly happen during the game and I can't seem to find a traceback besides minecrafts renderer

### Steps to reproduce

Start FTB Chocolate 1.1.0 and sometimes mods fail to load or the renderer crashes the client (possibly related to https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1113 ?)

### Expected behaviour

Modpack to load properly first try and not randomly crash

**Comment by Raidobw2** [comment]
You can try removing CustomizableElytra for those crashes

**Comment by batman202012** [comment]
Thank you! I'll give it a try in the meantime while waiting for an update

**Comment by manmaed** [comment]
This  issue is now Stale
