### ISSUE TITLE
[Bug]: Item voiding with backpack sort

### ISSUE THREAD

**Issue by TuinderJ** [FTBTeam/FTB-Modpack-Issues#1117]
### Mod

Sophisticated Backpacks

### Mod version

sophisticatedbackpacks-1.18.2-3.17.9.616

### Forge / Fabric version

Forge Version: 40.1.54

### Modpack & version

Direwolf20 1.18 v1.7.0

### What issue are you having?

Shift + Middle Click seems to sort items in a backpack regardless of their memory slots. Doing this moved items out of the memory slots and didn't let anything else go into those slots. The backpack was practically full so when certain items no longer had a place to go, they got voided. This feature also forces stacks to be in 64 regardless of the stacking upgrade.

Upgrades:
Advanced Feeding upgrade: Filter-Whitelist; Taco
Stack Upgrade Tier 2
Advanced Pickup Upgrade: Filter-Blacklist; empty
Crafting Upgrade
Auto-smoking Upgrade: Filter-Blacklist; empty

### Steps to reproduce

1. Have a backpack with memory slots towards the bottom
3. Have the backpack filled with more items than can fit (after excluding memory slots that come after a non-memory slot)
4. Shift + Middle Click
5. Items are now voided

**Comment by Raidobw2** [comment]
Hi, can you check https://github.com/FTBTeam/FTB-Modpack-Issues/issues/923 and let us know if doing that keybind fixes it?

**Comment by TheonlyTazz** [comment]
closing this issue as it has become stale
