### ISSUE TITLE
[Major Bug]: FTB teams locks up Direwolf20 1.18 server when people team up on carry over world

### ISSUE THREAD

**Issue by mike3d2008** [FTBTeam/FTB-Modpack-Issues#1119]
### Mod

FTB Team

### Mod version

ftb-teams-forge-1802.2.6-build.51.jar

### Forge / Fabric version

1.18.2 40.1.47

### Modpack & version

migrations from Direwolf20 1.18 1.4.1 to 1.5.1

### What issue are you having?

ever since we moved from release from 1.4.1 to 1.5.1 the server stalls out on teams and freeze and when i check the teams folder in world/ftbteams there like 3-5 teams setup and have to delete them each time. i dont know why this keep happening but i keep telling the server member to refrain from teams making but some dont listen and wind up still freezing on reboot. we did a world carry over. on another note, server will keep stalling long and long as more maps item are made and they are in world/data and they are chunk.dat and map#.dat. i have to manually go in and delete them in order to make reboot faster. please fix this issue so server migration from revision from 1.5.1 to the next release will be easy and we dont have this headache, we have to world wipe 3 time each release already because of this and our discord member are not please with his bug on Direwolf20 1.18. this bug is unfriendly to world carryover.

### Steps to reproduce

just setup team and map item on previous rev of direwolf20 1.18 like 1.4.1 then upgrade to 1.5.1 and the bug should happen on world carry over.

**Comment by Raidobw2** [comment]
Hi, do you have more information on that world and have you tried updating to the most recent version to get mod updates? The most recent version is 1.7.0 https://www.feed-the-beast.com/modpack/95_ftb_presents_direwolf20_1_18/server-files

Useful information about this issue for us would be one or many of the following:
- Server specifications and if the storage is on a HDD or SSD
- Server logs and client logs
- Server world save

Thanks in advance

**Comment by mike3d2008** [comment]
we try not to update to the lastest beta due to how unstable they can be, but the world gen and such was a mess and the increase loading time on the world server keep rising, we run into world upgrade issues alot and get no where fast, were to the point of just wipe each release.

**Comment by Raidobw2** [comment]
Hi, you can copy-paste your save somwhere else to keep it safe, then you can update to 1.7.0 if you want to test. I highly recommend to update to newer versions, since they have more fixes. Please do so.

As well, I'm still requesting any of the information I've pointed above, without it we have no info that can help us pinpoint the problem. If you can get us the world that freezes and we can reproduce it, then we can certaintly fix it. So a world download is the best thing you can provide us with. Thanks again

**Comment by Raidobw2** [comment]
Issue is superseded by https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1229
