### ISSUE TITLE
[Bug]: Gold Catwalk not obtainable

### ISSUE THREAD

**Issue by StefinitelyLethal** [FTBTeam/FTB-Modpack-Issues#1120]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.7.0

### Describe the bug

Gold Catwalk recipe from Create Deco requires Gold Bars that are uncraftable. Instead they infinitely loop with other Gold Bars that are also uncraftable.

### Steps to reproduce

Check the recipe for the Gold Catwalk

### Expected behaviour

Crafting Gold Bars with gold ingots

**Comment by TheonlyTazz** [comment]
i really thought i fixed the conflicting gold bar issues, i have now changed it so, that CreateDeco bars are craftable, and can be shapeless crafted into the other variants and also be used for the catwalks
![image](https://user-images.githubusercontent.com/3908847/182836231-345a81fc-f4ea-4d8e-93bb-3bba059343df.png)
![image](https://user-images.githubusercontent.com/3908847/182836313-fe6787e2-e299-4247-9357-087b2de5a241.png)
![image](https://user-images.githubusercontent.com/3908847/182836342-7873e876-a132-47da-9b7f-e1952c6350cd.png)
