### ISSUE TITLE
[Bug]: game crashing loading the save

### ISSUE THREAD

**Issue by demongoamin** [FTBTeam/FTB-Modpack-Issues#1122]
### Modpack

direwolf20 1.18

### Modpack version

1.80

### Describe the bug

when i try to load my save it crashes on loading it is a save 

### Steps to reproduce

open the game
go to singleplayer
click on the savegame the load the save

### Expected behaviour

that i can load my save and play

### Additional information

it was a save off the 1.70 modpack

**Comment by demongoamin** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9140566/latest.log)

**Comment by demongoamin** [comment]
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9140602/console.log)

**Comment by Saereth** [comment]
looks like a lot of your server configs are corrupt. Try these steps:
Shut down the game
Go into your save folder and rename the serverconfig folder to serverconfig.old
Relaunch your world and see if its fixed
Let us know if this doesn't resolve your issue

**Comment by demongoamin** [comment]
i found what it was to let it crash it was OptiFine
