### ISSUE TITLE
[Suggestion]: Direwolf20 Seeds

### ISSUE THREAD

**Issue by lazycooken** [FTBTeam/FTB-Modpack-Issues#1124]
### Modpack

Direwolf20

### Is your suggestion related to a problem? Please describe.

make it so all seed can be used in composter.

**Comment by TheonlyTazz** [comment]
I just checked "Seeds" in JEI, and the only seeds i could find that arent compostable are (see bottom list)
I created a new .js file to add these seeds to the composter, if i have missed any, feel free to post the ids here
```
//priority: 100
onEvent('recipes.compostables', event => {

    const compostable = [
    "createcafe:cassava_seeds",
    "sushigocrafting:rice_seeds",
    "sushigocrafting:cucumber_seeds",
    "sushigocrafting:soy_seeds",
    "sushigocrafting:wasabi_seeds",
    "sushigocrafting:sesame_seeds",
    "sushigocrafting:sesame_seed",
    "thermal:hops_seeds",
    "bloodmagic:growing_doubt"]

    compostable.forEach((seed) => {
        event.add(seed, 0.33);
    });
})
```
