### ISSUE TITLE
[Bug]: Arboreal extractor generates enderslime on earth slime trees

### ISSUE THREAD

**Issue by albertquiroga** [FTBTeam/FTB-Modpack-Issues#1125]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.8.0

### Describe the bug

Using an arboreal extractor on greenearth logs surrounded by slimy leaves should generate slime, but it generates enderslime

### Steps to reproduce

1. Place earthslime grass
2. Place an earthslime sapling on top
3. Grow it with bonemeal
4. Place an arboreal extractor next to the tree's logs
5. The arboreal extractor will generate enderslime instead of regular slime

### Expected behaviour

The arboreal extractor should generate regular slime

**Comment by TheonlyTazz** [comment]
The only way to fix this is by disabling either the regular slime or the ender slime.
after some discussion we came to the conclusion its best to disable the ender slime variant
![image](https://user-images.githubusercontent.com/3908847/183151659-2c78fb3c-2dcf-4ee5-a94e-b78cabd290c7.png)
resulting in all greenheart log trees giving regular slime.

this is a temporary solution untill Tinkers comes up with proper trees for all variants
