### ISSUE TITLE
[Bug]: FTB Presents Direwolf20 1.18 v1.8.0 Server Instantly Crashing

### ISSUE THREAD

**Issue by Mig979** [FTBTeam/FTB-Modpack-Issues#1126]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.8.0

### Describe the bug

Upon starting the server files from the new version 1.8.0 on a VM (running on linux) that I use to host modpacks on the Oracle Cloud and the server instantly fails with the following lines:

WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-exports
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens
Error: Could not find or load main class cpw.mods.bootstraplauncher.BootstrapLauncher
Caused by: java.lang.ClassNotFoundException: cpw.mods.bootstraplauncher.BootstrapLauncher

This didn't seem to happen when I run it on my windows 10 pc, the java version I'm using on both machines is version 17.0.3

I tried installing the version 1.7.0 server files on the VM and that seems to work just fine, it's only the new version I'm having issues with. I have tried running the server with no extra java arguments and only 4GB of RAM and that didn't work either. 

Any ideas on how I could fix this issue?

### Steps to reproduce

1. download and install the server on my VM
2. start it
3. crash

### Expected behaviour

Server to start

**Comment by Raidobw2** [comment]
From the looks of what you posted, that looked like a partial Forge installation somehow. You could try reinstalling again from the server installer, that'd be the solution I'd use.

I'll drop the server procedure if people would come across this post and need it https://go.ftb.team/create-a-server

If you need more help feel free and reopen the issue

**Comment by Mig979** [comment]
I saw that the oracle cloud and google cloud were having issues yesterday in UK London due to the heatwave and that is where I have the server set up so I just assumed that was the issue and closed the issue. I tried it again today and everything worked just fine! Thank you for your support.
