### ISSUE TITLE
[Bug]: University 1.16 crashing

### ISSUE THREAD

**Issue by VolkerSchlegel** [FTBTeam/FTB-Modpack-Issues#1127]
### Modpack

FTB University 1.16

### Modpack version

latest

### Log Files

https://controlc.com/fc8e2069

### Describe the bug

As soon as the world starts rendering it crashes.

### Steps to reproduce

1. Generate a new world
2. crash

### Expected behaviour

MC not crashing

### Additional information

It worked fine for me for a while, first it started happening with new worlds, now I can't even load into my old world anymore.
I imported the pack into MultiMC so I can play offline and I've been playing on there the whole time.

**Comment by Raidobw2** [comment]
Try assigning a bit more than 4GB of RAM. Say 6GB would be good. University 1.16.5 has quite a large mod pool and can require more RAM than most packs to play smoothly.

If that doesn't do it, I'm not sure exactly what the error is as of now. I'd recommend a reinstall of the modpack, you can try the FTB App as well, maybe it's a quirk within your current files. Fresh files might help diagnose the actual problem

**Comment by Kakiking** [comment]
Ok, so with 10GB of RAM assigned it started, but all entities were not rendering and when I tried starting it today it didn't work again. Guess I'll try using the FTB App and reinstalling.

**Comment by Kakiking** [comment]
At first it loaded with the FTB App, but I only got ~30fps without anything running in the background and F3+A crashed it, starting it again and joining the world resulted in a crash as well... I hope reinstalling the modpack fixes it.

**Comment by Raidobw2** [comment]
For FPS issues try looking at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1130#issuecomment-1191028332, I've posted some helpful things there. If you try some and it works, let me know so I can close this issue if it's resolved
