### ISSUE TITLE
[Bug]: no full eccentric tome on player first startup in an running world

### ISSUE THREAD

**Issue by DietmarKrause** [FTBTeam/FTB-Modpack-Issues#1128]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.8.0

### Describe the bug

I understand that eccentric tome is new in direwolf20 1.18 Vers 1.8.0 and one should get a full new book on the first start. In my world i didnt get one

### Steps to reproduce

1. update modpack to 1.8.0
2. start your old world
3. after starting your old world you should get the eccentric tome book, full 

### Expected behaviour

i should get a full book of eccentric tome im my world after updating to the new pack version

**Comment by TheonlyTazz** [comment]
i forgot to use a diffrent tag in
kubejs/server_scripts/startingitems.js:
```js
//Starter Items
onEvent('player.logged_in', event => {
    // Check if player doesn't have "starting_items" stage yet
    if (!event.player.stages.has('starting_items')) {
        // Add the stage
        event.player.stages.add('starting_items')
```
if you change the 2 `starting_items` tags to something else, it will create a new event and give u the eccentric tome on login

**Comment by DietmarKrause** [comment]
i am not a genius in programing. Will there be a bugfix in the future so i get a new book later?

**Comment by Raidobw2** [comment]
Yes there will be a fix for it.

You can try this if you want:

1. Press Escape in-game and click "Open to LAN". Set "Allow Cheats" to ON and click "Start LAN World".
![image](https://user-images.githubusercontent.com/17010632/179915829-25e68b59-6eda-4732-82d6-f6dc86e33922.png)
2. Open the chat and paste the command `/kubejs stages remove @s starting_items` and press Enter.
3. Press Escape to open the menu and select "Save and Quit to Title".
4. When you have returned to the menu, select your world and join it.

According to what Tazz said, for now, you should have said new book in your existing world upon joining back that time.

**Comment by Raidobw2** [comment]
Until the pack is updated again, yes this will work to get the book
