### ISSUE TITLE
[Suggestion]: Make Eccentric Tome with all books craftable

### ISSUE THREAD

**Issue by danaYatsuta** [FTBTeam/FTB-Modpack-Issues#1129]
### Modpack

FTB Direwolf20 1.18

### Is your suggestion related to a problem? Please describe.

Currently full eccentric tome is only obtainable when logging into the world on 1.8.0 for the first time, but in case of book being lost there is no way to get it back. I think it would be convenient if you could just craft it with all books included at any time.

**Comment by Raidobw2** [comment]
Linked with #1128 as improvements

**Comment by TheonlyTazz** [comment]
changed the tag on the tome event to 
`  if (!event.player.stages.has("starting_tome")) {`

so everyone should get a new tome on pack update
