### ISSUE TITLE
[Bug]: Direwolf20 1.18 version 1.8.0 Crash after update

### ISSUE THREAD

**Issue by ciserman** [FTBTeam/FTB-Modpack-Issues#1130]
### Modpack

Direwolf20 1.18

### Modpack version

1.8.0

### Log Files

https://paste.feed-the-beast.com/view/05dc363a

### Describe the bug

Game crashes on load

### Steps to reproduce

Crashes on world load

### Expected behaviour

Game does not crash

**Comment by Raidobw2** [comment]
Please don't post raw logs, use any paste service such as https://paste.feed-the-beast.com/ or use a code block with three backticks before and after, we will appreciate it:

````
```
---- Minecraft Crash Report ----
// Don't do that.
 
Time: 7/19/22, 3:06 PM
Description: Exception in server tick loop
 
java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'
        at net.minecraft.server.level.ServerChunkCache.addRegionTicket(ServerChunkCache.java:429) ~[client-1.18.2-20220404.173914-srg.jar%23326!/:?] {re:classloading,pl:accesstransformer:B}
```
````

I've edited your post accordingly for you to see an example.

As for the error, try removing Optifine first and see if that fixes it. If not, feel free to post another log, I'll have a look again

**Comment by demongoamin** [comment]
i had the same problem i removed optifine and it works

**Comment by Telarith** [comment]
Same problem on my side. Definitely an optifine issue. Removed and it works but without it the game has so many frame stutters and very low FPS.

**Comment by Jaeiya** [comment]
Having the same issue. Is it possible for this to be fixed so that it works with Optifine?

**Comment by Jaeiya** [comment]
@Raidobw2 Thanks for the info! I'll try some of those tips.
