### ISSUE TITLE
[Bug]: direwolf1.18.2  v1.8.0 is not compatible with optifine.  Crashes during loading from save, cant make a new game either

### ISSUE THREAD

**Issue by laynx0880** [FTBTeam/FTB-Modpack-Issues#1131]
### Modpack

Direwolf1.18

### Modpack version

1.8.0

### Describe the bug

Fails to load

### Steps to reproduce

Put optifine in mods folder, try to start a game or load a save

### Expected behaviour

Game to load

**Comment by Saereth** [comment]
Optfine is closed source and not able to be distributed with the pack. We could not even begin to support this. Take it up with optifine or provide a crash log and at a minimum we can try to help you figure out which mod isnt playing nicely with it and you can take it up with the mod devs.
