### ISSUE TITLE
[Suggestion]:minor suggestion for craftin

### ISSUE THREAD

**Issue by lazycooken** [FTBTeam/FTB-Modpack-Issues#1135]
### Modpack

Direwolf20

### Is your suggestion related to a problem? Please describe.

 - make Deep slate furnace usable in furnace crafting recipes / mod quark.
-make wheat dough crafting usable with any water bucket type item / Farmer's delight.
-Iron furnace burning charcoal and coal bit too quickly, burning two bit for 1 item rather then 1 for 1 like regulars furnace/mod 
   INDUSTRIAL CONTRAPTIONS
-add tinker shovel, / tinker construct. why there no shovel??

**Comment by TheonlyTazz** [comment]
- Made all "Furnace use" recipe dynamicly use regular, blackstone and deepslate furnace
- Iron Furnace now fixed being able to smelt 12 items with 1 coal (150% effective)
- Tinkers Shovel wont be added, Tinkers changed it to using a Mattock (or Excavator for 3x3) or a Pickadze 
![image](https://user-images.githubusercontent.com/3908847/183157120-e8fca75f-cff7-4770-95bc-96b1eb87233a.png)
![image](https://user-images.githubusercontent.com/3908847/183157171-91cd0a61-64e6-4d1e-b4af-f24f532d5fd7.png)
