### ISSUE TITLE
[Bug]: Minecolonies Chunkloading config not working (Multiplayer only)

### ISSUE THREAD

**Issue by Kin-Seth** [FTBTeam/FTB-Modpack-Issues#1136]
### Modpack

Direwolf 1.18

### Modpack version

1.8.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9158371/latest.log)

### Describe the bug

Minecolonies has a set of config options for chunkloading. Essential for larger colonies to function. One of them enables a system to load the entire colony when any part is loaded by an owner/officer of the colony. The other sets the sensitivity of what is loaded. Even with this function enabled and set to maximum sensitivity, it will not properly chunkload the colony. Exact cause is unknown. This has been replicated by another player as well on the same pack.

Through troubleshooting, I have found that on initial server start, this config works correctly for a minute or two before resuming this incorrect behaviour, unloading the distant colony chunks.

Additionally, it has only been shown to be an issue in MP Servers. Singleplayer had correct behaviour and fully loaded entire colony, verified by visibly seeing a builder modify blocks via the FTB chunks map.

It is easy to tell via minimap/map as when you reach a certain distance from a colonist, they will cease to move on the minimap unntil the distance is closed again. Estimate is around 4-5 chunks away.

### Steps to reproduce

Configure Minecolonies to force load with a strictness of 1 for the chunkloading to ensure other factors do not affect chunk loading.
Start a Minecolony on a multiplayer server which occupies an extended space so that only a part of it would be naturally loaded.
Stand on the edge of the colony ensuring only a small part of it is loaded. Use the map to observe the colonists to see if they continue to work/move on the opposite end of the colony.
In accordance to this bug, distant colonists will be still and unmoving, but will resume their movement and activities when approached.

### Expected behaviour

With this config set, the entire colony should be active and functional (Colonists moving and working on map) when any part of it is loaded by an owner or officer of the colony.

### Screenshots

![image](https://user-images.githubusercontent.com/109715626/180190884-97bfe1d8-8ffe-48ef-b4e1-38f5804b3839.png) - Initial image, standing on edge of colony.
![image](https://user-images.githubusercontent.com/109715626/180190935-d8b6a5a8-861a-463a-9767-d545769b3c4d.png) - Note how the citizens near my position move while the others have not moved at all. One got far enough away it stopped and froze at the western gate. They froze at that boundary.
![image](https://user-images.githubusercontent.com/109715626/180191209-bfce4902-1932-4bcf-97ea-984daeb8f905.png) - As you can see, once I got closer, all of those dots on the bottom scattered as they loaded.

![image](https://user-images.githubusercontent.com/109715626/180191481-960f92e3-0a90-46e1-9a5f-29414ad2d29c.png) - The config settings in question

**Comment by Saereth** [comment]
I have initially been unsuccessful in reproducing this so I'm going to setup a fresh server with this tonight but I suspect the issue might be with the "it shall not tick mod", I will update again once I know more

**Comment by Kin-Seth** [comment]
I appears to mainly be an issue once a second person logs into the server on further testing. Another person who was having the issue added Minecolonies to the "It shall not tick" mod and it fixed the issue. Will test myself shortly.

**Comment by Saereth** [comment]
Yep that is what 8 suspected thanks for testing, let' me know what you
find. Ty

**Comment by TheonlyTazz** [comment]
This is indeed an issue because of "It Shall Not Tick" and the only real way is to disable that mod, which isn't going to happen for the time being,
I will however try and tweak the configs to try and get them to work better on servers
