### ISSUE TITLE
[Bug]: Invisible block for ProjectRed and CBMicroblock

### ISSUE THREAD

**Issue by Letimineur** [FTBTeam/FTB-Modpack-Issues#1138]
### Modpack

FTB University

### Modpack version

1.7.0

### Log Files

No log genereted for this error

### Describe the bug

Hello
I got a problem with some mods in TFB University 1.7.0 for minecraft 1.16.5
The mod in question are CBMicroBlock and ProjectRed.
Every item got there texture normaly but block have no texture ( translusant)
Everybody on the server as the issue, same if they play on solo game
Dedicated texture pack doesn't solve the issue
We didn't modify any thing in/from the mod pack

### Steps to reproduce

-install the modpack
- start a new solo game ( or go to a server with the modpack )
- craft/give any CBMicroBlock block => place it : it's invisible
- craft/give any ProjectRed Integration/Transmission ( illumination wark fine) => place it : it's invisible

### Expected behaviour

see the block

### Screenshots

![image](https://user-images.githubusercontent.com/88988600/180242722-dd3e15bc-75a9-44b1-afe1-dafcd41e7542.png)

**Comment by Raidobw2** [comment]
Try removing Magnesium and Magnesium extras and see if that solves it for now

**Comment by Letimineur** [comment]
That solve the problem for both mods.
Magnesium and Magnesium extras are not mandatory in the modpack ?
Does it mean the mod pack need an update to solve the probleme on servers ?

**Comment by Raidobw2** [comment]
Yup, that is correct the pack will need an update. And no they are performance mods, but can cause issues as you saw

**Comment by Letimineur** [comment]
I added calcium to the modpack and it solve the problem without having to remove magnesium
https://www.curseforge.com/minecraft/mc-mods/calcium
I did'nt find any new error caused by calcium for the moment

**Comment by Raidobw2** [comment]
Interesting, thanks for letting me know
