### ISSUE TITLE
[Bug]: Watchdog crash due to level generation IOWorker

### ISSUE THREAD

**Issue by mike3d2008** [FTBTeam/FTB-Modpack-Issues#1139]
### Modpack

Direwolf20 1.18

### Modpack version

1.8.0

### Log Files

[crash-2022-07-21_10.07.33-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9160344/crash-2022-07-21_10.07.33-server.txt)

### Describe the bug

server keeps crashing for no reason. we took away the RTP in hopes of fixing the issues and it did not help much

### Steps to reproduce

unable to determine the cause

### Expected behaviour

the server to run normally and not crash

### Additional information

were running like 7-9 people on the server at the same time.

**Comment by Sunekaer** [comment]
Could you try and set max-tick-time to -1 in your server properties?
Crashlogs from servers lagging out are often showing the wrong mods in the stack.

Once you have changed the max-tick-time I would recommend using spark to try and find whats causing the lag: https://spark.lucko.me/docs/guides/Finding-lag-spikes

**Comment by Raidobw2** [comment]
This issue is superseded by https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1229
