### ISSUE TITLE
[Bug, Krate]: Krate item filter popping out when sorting

### ISSUE THREAD

**Issue by xlSoulTaker** [FTBTeam/FTB-Modpack-Issues#114]
### Modpack

OceanBlock

### Modpack version

1.2.0

### Log Files

n/a

### Describe the bug

When sorting items in crate (I tried it with large crate), the item filter attached to the crate would go into its inventory which stops it filtering out unwanted items and you have to manually place it back. I dont know if this is just the mod itself or with the middle mouse to filter affecting the krates mod :)

### Steps to reproduce

1. get a crate from Krates mod
2. install item filter on the crate
3. press middle mouse when the pointer is hovering in crate inventory to sort inventory

### Expected behaviour

normal sorting without the filter popping out

**Comment by manmaed** [comment]
@Sunekaer @DinnerBeef @UnRealDinnerbone  any word on, this has this been fixed?
this will auto close in 2 weeks if no response
