### ISSUE TITLE
[Suggestion]: Add Mekanism Additions for Plastic Blocks, Glow Plates and Baby Mobs

### ISSUE THREAD

**Issue by FlavioF6799** [FTBTeam/FTB-Modpack-Issues#1141]
### Modpack

FTB Direwolf20 (1.18)

### Mod suggestion

I wanted Mekanism Additions be added in Direwolf20 1.18 pack, since they got better plastic blocks, which it's great decorations for trains (Create 0.5), also it has more good things for make bases, like glow plates, yet it has more new mobs like Baby Creeper

**Comment by TheonlyTazz** [comment]
added to V1.9
shouldnt cause any issues
