### ISSUE TITLE
[Bug]: Constantan not working on diamond level

### ISSUE THREAD

**Issue by Valicious** [FTBTeam/FTB-Modpack-Issues#1142]
### Modpack

Direwolf20 1.18

### Modpack version

1.8.0

### Describe the bug

A using the Tinkers Tools mod, the constantan pickaxe does not work on the specified level in its tool tip, the diamond level - cannot break diamonds or Redstone. The mining speed progress is slow and nothing drops.
![image](https://user-images.githubusercontent.com/20522769/180300466-ac1809ab-0101-458e-ba80-d8cb73cbef7a.png)

### Steps to reproduce

Full constantan tinker tool As seen in attached image.
Try to mine Diamonds or Redstone.

### Expected behaviour

The ore to break speedily and raw materials to be dropped.

**Comment by quietust** [comment]
Duplicate of #845 - you made a Pick**adze**, and those are hard-capped at a "Gold" harvest level.

**Comment by Valicious** [comment]
Got it. Thank you.
