### ISSUE TITLE
[Bug]: Crash when trying to render Supplementaries blocks picked up by Carry On

### ISSUE THREAD

**Issue by AhtenXevious** [FTBTeam/FTB-Modpack-Issues#1143]
### Modpack

FTB Direwolf20

### Modpack version

1.18

### Log Files

[crash-2022-07-21_00.26.53-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9162631/crash-2022-07-21_00.26.53-client.txt)

### Describe the bug

When placing items on the ground with Supplementaries (books, for example), if a player then shift+right clicks to pick it up with Carry On, it will crash the game of anyone within at least 130 blocks (in our testing). The player themselves wouldn't crash unless they went into third person mode.

### Steps to reproduce

1. Place a book or another item with the description "Placeable"
2. Shift+Right click the item to pick it up
3. Either have another player enter the area or go into third person mode

### Expected behaviour

Immediate Crash To Desktop

**Comment by quietust** [comment]
And CarryOn's blacklist grows ever larger...

**Comment by TheonlyTazz** [comment]
blacklisted supplementaries to be blacklisted in carryon... slowly but surely im not sure if the mod is even worth to be in the pack, with 90% being blackslisted :P
