### ISSUE TITLE
[Bug]: Crashes when starting singleplayer world

### ISSUE THREAD

**Issue by ReklessImpulse** [FTBTeam/FTB-Modpack-Issues#1144]
### Modpack

FTB direwolf20 1.18

### Modpack version

1.8.0

### Log Files

[crash-2022-07-21_19.17.29-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9163639/crash-2022-07-21_19.17.29-server.txt)

### Describe the bug

Game crashes after starting singleplayer world. 

### Steps to reproduce

1. Have optifine installed
2. Start singleplayer world

### Expected behaviour

Expected to not crash

### Screenshots

Not Applicable

### Additional information

First time looking at crash reports and I think there's a conflict with optifine and elemental craft, getting rid of optifine has fixed it.

**Comment by Raidobw2** [comment]
Hi, please see #1130 and one of my last comments on it. We can't support Optifine, however you can report the issue to Optifine itself and they can fix it. That's as much as I can do here, so I will be closing this issue
