### ISSUE TITLE
[Bug]: Modular Powersuits : Most keybinds not working/ Cannot toggle activatable modules

### ISSUE THREAD

**Issue by EinMannimInternet** [FTBTeam/FTB-Modpack-Issues#1145]
### Modpack

FTB Ultimate: Anniversary Edition

### Modpack version

1.3.0

### Describe the bug

Hello, new guy here.

pre Summary : Powerfist works, cycling through powerfist modules (keybind) works. Passive modules on the armor (ex. solar/kinetic generator) work. 
**All the other keybinds don't work**, Keybind GUI/Cosmetic GUI doesn't open, cannot check for flight control keybind because jetpack/rocketboots/glider doesn't activate.

In the item info it says that the default keybind for "open MPS keybind GUI" is set on k . I cannot open that. I rebound in main controls, it still doesn't open. After reading on some forums, I made sure to bind keys that aren't shared with other mods/functions, it still doesn't work.
The only keybind that seems to work is for "cycle tool forwards/backwards".
I gave up on the "keybind GUI" because I can access keybinds on the tinker table itself (perhaps I am misunderstanding the function?) and instead focused on the armor modules.

I have installed the glider first, but it wouldn't activate. I gave up on that because my shock absorber was working fine and instead I put my hopes in the jetpack/rocketboots combo. It doesn't work either. I also tried magnet and swim boost, no luck.

I checked my battery level and module tinkering (set jetpack to max power), I even took off the armor plating modules because some people were talking about weight, eventhough I cannot find any weight info in the tinkering table.

My inept conclusion is that I am having an issue with the keybinds simply not working, not allowing me to activate essential functions of the MPS mod.

### Steps to reproduce

IDK how to recreat my issue, I installed the modpack regularly, and tested in both singleplayer and on my server, aswell as survival and creative mode.

I only started rebinding keys after installing the modules and finding them not to work,

### Expected behaviour

No mean spirited sarcasm here, I expected the modules to work :P

### Additional information

I have looked in many forums, but cannot seem to find anyone with the exact same issues in the same modpack/version of the modular powersuits mod. 

**Any help would be very greatly appreciated :)**

**Comment by Raidobw2** [comment]
Looks like some tool modules aren't fully implemented in that version. The mod has an update available, I bet that would fix some of them.
For instance Silk Touch appears to work but not Blink or Leaf Blower. I think these are uninplemented in that version.
![image](https://user-images.githubusercontent.com/17010632/180578176-968ff700-d776-4700-ac4b-eea09712f401.png)


Updating Modular Powersuits and its library Numina could be a workaround for now, and as well as applying the fix at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/544#issuecomment-1054985955

You can delete those two:
![image](https://user-images.githubusercontent.com/17010632/180578271-950b6233-789b-45c9-8a8f-e6b79bdc4657.png)
And replace them with to see if that works:
https://www.curseforge.com/minecraft/mc-mods/modular-powersuits/files/3838049
https://www.curseforge.com/minecraft/mc-mods/numina/files/3838048

**Comment by EinMannimInternet** [comment]
Hello Raido! Thank you very much for the quick reply!

I updated the MPS and Numina files. The launcher then told me that i would have to update Refined Storage aswell (V1.9.18) so I did that and now it works :)))
I will now only have to check how to do that for my friends server too, but i guess he just has to update the same files right?

Again thank you very much for your help, building big stuff in survival is now fun again 👍 
_weee im flying_

**Comment by Raidobw2** [comment]
Yes they can do the same fixes. I think there's a sharing feature in the FTB App. Maybe you can try that and share your instance with your friends, that could be easy to give them the fix.
After clicking the modpack tile you end up in the Overview on the FTB App. You can then click Settings and this:
![image](https://user-images.githubusercontent.com/17010632/180592063-f02f4fca-b061-4b89-9ce3-f6f51f736a53.png)

In the Library your friends can then choose this in the top right:
![image](https://user-images.githubusercontent.com/17010632/180592073-ff4798bd-3400-4e99-8398-27a7bfcf69bb.png)
And use the share code option:
![image](https://user-images.githubusercontent.com/17010632/180592077-afb27b5f-74d1-413c-b76e-b859921b8256.png)

Also please leave this opened! This will be useful for me or other modpack developers (whoever updates this in fact) to keep track of issues we have to make sure are resolved when we update modpacks.

**Comment by EinMannimInternet** [comment]
Oh ok! I will try that later, thank you :) You modding guys are awesome btw, have a nice day!
