### ISSUE TITLE
[Bug]: No steel recipe

### ISSUE THREAD

**Issue by Domi101code** [FTBTeam/FTB-Modpack-Issues#1149]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

There is no way to get steel in the modpack. So you cant craft the solar panel from solar generation. There may be other recipes that use steel:

### Steps to reproduce

Just search in REI

### Expected behaviour

Empty Tag is shown

### Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/95288724/180475703-0321fc76-8afc-4cf5-87f0-c8800afdba49.png)

**Comment by MajorGhosty** [comment]
There are other recipes missing as well that are used in solar gen. (Invar, electrum, signalum, lumium, platinum)

**Comment by Raidobw2** [comment]
Thanks a lot!
