### ISSUE TITLE
[Bug]: .jar files are not jar files

### ISSUE THREAD

**Issue by 905Sunny** [FTBTeam/FTB-Modpack-Issues#115]
### Modpack

FTB OceanBlock

### Modpack version

1.3.0

### Describe the bug

Some jar files are detected as "not jar files" and the mods which triggered the issue are not detected.

### Steps to reproduce

1. Boot
2. See UI (shown in attachment
3. check the mod tab
4. mods not found

### Expected behaviour

no warning seen and those mods load as usual

### Screenshots

![jar files are not jar files](https://user-images.githubusercontent.com/44795811/136797243-a2f83d30-f63d-4a37-89e3-d067ab68c923.png)

**Comment by ALainxD** [comment]
Got the same, was updating from 1.2.0. But there is a button to continue to Main manue anyway

**Comment by Sunekaer** [comment]
Okay, so it should be fixed now, but you'll need to go to %LocalAppData%\.ftba\instances\.localCache and delete everything in the folder and then reinstall the pack.
Remember to backup your world first!
