### ISSUE TITLE
[Bug]: University 1.16 NullPointerException wont let me join world or receive crash report

### ISSUE THREAD

**Issue by chichiblur** [FTBTeam/FTB-Modpack-Issues#1150]
### Modpack

FTB University MC 1.16

### Modpack version

1.7.0

### Log Files

https://pste.ch/apixenixeh.md

### Describe the bug

I've had this world for a few days now, and for the most part it's run fine. I've had to start playing on a backup world because chisels and bits ruined my first one, but now the backup wont even load. I logged out of my world earlier this morning and now I can't get back in, though seemingly nothing has changed. I try to open the world and after I make it past "Loading world" the screen just loses all GUI and MC stops responding. The log says that a NullPointerException caused the server the close and it tells me that it generates a crash report, but as it closes, it has another NullPointerException, and so no crash report is ever generated, which I guess it why it gets stuck on a blank screen when I try to play on that world.

### Steps to reproduce

1. Go to link
2. See last few lines
3. NullPointerException and supposedly generated crash report is outlined in the bottom lines

### Expected behaviour

I'm not really sure whats going on, but I've noticed a lot off with chisels and bits. I also never encounter lag but for some reason when I aim my chisel at any block, the bigger chiseling settings make my computer go SUPER slow until I aim it away from a block.

**Comment by chichiblur** [comment]
![Screenshot (67)](https://user-images.githubusercontent.com/109626065/180567740-d68064a7-a9c1-481b-a26c-afdb89ef51e3.png)
blank loading screen of death

**Comment by Raidobw2** [comment]
Looks like a corrupted server config file (sometimes that is common). Try this:

> 1. Take an immediate copy of the world from the `saves` folder, store in a safe location.
> 2. In the `saves/world` folder, there is a `serverconfig` folder, open it.
> 3. Select all elements inside the `serverconfig` folder, and delete them. These are the corrupted files.
> 4. In the root of the modpack folder, there is a `defaultconfigs` folder. You'll open it and copy all the files inside.
> 5. You'll paste all those files in your world in the same `serverconfig` folder, which should be at `saves/world/serverconfig`.
> 6. Start the modpack and join the world, it should work.

Also for the performance part of Chisel & Bits, see #715 for more information.

Feel free to close this issue if that solves it. The corrupted server configs are a bug of Forge I'm assuming (since I keep seeing it in many modpacks) and I believe they could be due to power cuts or unusual ways of quitting the game, other than the "Save and quit to title" button.

**Comment by chichiblur** [comment]
> 

you are the love of my life thank you so much!!! everything is working perfectly

**Comment by Raidobw2** [comment]
Cool, glad to see that worked! Hopefully that won't happen again, if you want to try and prevent that kind of thing from happening simply make sure to keep quitting the game with the save button from the menu.

If anything else happens let us know, for now that's solved so I'll go ahead and close this 🙂

Cheers
