### ISSUE TITLE
[Bug]: Crafting Magebloom seed crashes the game

### ISSUE THREAD

**Issue by yellowincarnate** [FTBTeam/FTB-Modpack-Issues#1151]
### Modpack

One

### Modpack version

1.3.0

### Log Files

[crash-2022-07-22_16.49.45-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9172173/crash-2022-07-22_16.49.45-client.txt)
[crash-2022-07-22_16.59.07-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9172174/crash-2022-07-22_16.59.07-client.txt)

### Describe the bug

Unsure what logs may be useful - attempting to make magebloom seed has resulted in successive crashes.  Suspect that this might be Ars's enchanting apparatus, but not entirely sure. (Will need further validation).  Also might be related to the placement of enchantment apparatus at same level as the pedestals.

### Steps to reproduce

Place Arcane gems on pedestals, place wheat seed in Enchantment Apparatus.  Sound plays, but game crashes to desktop.

### Expected behaviour

Enchantment Apparatus should play short animation, then output correct recipie

**Comment by Raidobw2** [comment]
Hi, I've tried to reproduce that issue although I haven't been able to. Are you able to install another instance of FTB One to see if that is a problem with fresh files? I've attached what happens on my game when I do it. The sounds do play as well:

https://user-images.githubusercontent.com/17010632/180586188-3c4dde69-340f-41ed-9da5-59c16f4ab153.mp4

**Comment by yellowincarnate** [comment]
Yup, seems like mine somehow was corrupted.  Sorry for the false alarm
