### ISSUE TITLE
FTB One ~ Rubber/Latex (Updated Recipes)

### ISSUE THREAD

**Issue by Raidobw2** [FTBTeam/FTB-Modpack-Issues#1152]
### Discussed in https://github.com/FTBTeam/FTB-Modpack-Issues/discussions/1148

<div type='discussions-op-text'>

<sup>Originally posted by **AdamBundschuh** July 22, 2022</sup>
EDIT: I forgot you can get latex from a tree tap, the recipes should be updated for latex.

Latex can only be made with a centrifuge (rubber tree/sap/log -> centrifuge -> latex)

To make a centrifuge, you need rubber, which requires latex.

Unless you're lucky enough to find Slimes early on, you are locked out of all FTB Industrial.

I can't remember how FTB:Ultimate circumvented this, but I know you had access to rubber without hunting down slimes.

</div>

**Comment by Roboleo1010** [comment]
I agree, the tree tap way of getting rubber should be documented somewhere. If not in JEI, then at least in some sort of mod book or the mod overview book diesplayed in the inventory screen.
