### ISSUE TITLE
[Bug]: Aphorism Tiles can be edited by anyone even when chunk protected

### ISSUE THREAD

**Issue by Jacob-JA-Shanks** [FTBTeam/FTB-Modpack-Issues#1153]
### Modpack

FTB Direwolf 1.18

### Modpack version

1.8.0

### Describe the bug

We placed some Aphorism Tiles on our servers spawn area to give info and advice but found that other players can edit them even though spawn protection was turned on as well as FTB Chunks claimed and made private.

### Steps to reproduce

1. Switch on Spawn Protection
2. Claim Chunk and make Edit and Interaction Private
3. Place Aphorism Tile
4. Have another player who is not OP or part of the claimed chunk team attempt to edit sign

### Expected behaviour

Aphorism Tile should not be editable by non authorised players

**Comment by Raidobw2** [comment]
You might be able to use a Security Station from PneumaticCraft to "protect" them for the meantime.

Also, do normal signs behave the same way?

**Comment by Jacob-JA-Shanks** [comment]
That’s a good shout, I’ll pin a message for everyone.

We did test with regular signs using the same steps and they are safe to use
________________________________

**Comment by Jacob-JA-Shanks** [comment]
We attempted a test again with my provided steps with the addition of a configured service desk, unfortunately the Tiles can still be edited by non-authorised users
