### ISSUE TITLE
[Bug]: Pattern making in AE2 shows fluid on the wrong side

### ISSUE THREAD

**Issue by IamStig** [FTBTeam/FTB-Modpack-Issues#1157]
### Modpack

Direwolf20 1.18.2

### Modpack version

1.80

### Describe the bug

It is another JEI issue. JEI recipe for a water (and milk and possibly all other) bucket via the Fluid Encapsulator shows the fluid on the wrong side, so a pattern for a bucket of x shows INPUT Bucket OUTPUT xbucket + 1000mb of x

### Steps to reproduce

1 Go to Pattern grid
2 Search "Bucket"
3 Click on the bucket containing ... milk
4 Click the "Fluid Encapsulator" tab
5 Click the "+" button
6 Look in amazement

### Expected behaviour

Make a pattern with 1000mb of x plus a bucket that makes a bucket of x

### Screenshots

![2022-07-24_10 45 13](https://user-images.githubusercontent.com/20489424/180627553-4c3c61ad-ff89-4190-9294-055a29facb03.png)

**Comment by TheonlyTazz** [comment]
for now, the only fix i can see is
- click the Fluids checkbox
- pull Milk (or other) Fluid into the input and set amount
- remove Fluid from output

this isnt an optimal solution, but a quick workaround... i will forward this issue to the JEI issue tracker as it seems this issue also applies on AE2

**Comment by TheonlyTazz** [comment]
![grafik](https://user-images.githubusercontent.com/3908847/201187366-72926fff-0415-4eff-b2c7-2ad5d728d098.png)
fixed indev
