### ISSUE TITLE
[Bug]: Direwolf20 1.18 Linux fail to download

### ISSUE THREAD

**Issue by DarksideVT** [FTBTeam/FTB-Modpack-Issues#1158]
### Modpack

Direwolf20 1.18

### Modpack version

2234

### Log Files

491 Successful 266 Failed
https://pste.ch/zoyojitozo.pl

Continue anyway.
https://pste.ch/jovurutaxi.sql

### Describe the bug

With linux, the server does not download fully, having 266 Failed downloads. Additionally, the start.sh is not formatted correctly. https://pste.ch/ijopamevun.bash

### Steps to reproduce

1. wget https://feed-the-beast.com/modpack/95_ftb_presents_direwolf20_1_18/server-files
2. chmod +x linux
3. ./linux 95
4. follow prompts

### Expected behaviour

Direwolf20 1.18 Modpack v.2234 should be downloaded.

### Additional information

I've tried using the Windows server and the download also didn't work correctly.

**Comment by Rirush** [comment]
Had this issue for a few days now too. Modpack updates still don't work with the error `Error downloading : Get "": unsupported protocol scheme ""`, but clean installation of Direwolf20 1.18 version 1.8.0 now works.

**Comment by Raidobw2** [comment]
I've tried downloading both the 1.8.0 server files and the 1.7.0 client, and updating the client to 1.8.0 in the FTB App after. All works on my side at the moment, can one of you confirm if this is fixed? https://www.feed-the-beast.com/modpack/95_ftb_presents_direwolf20_1_18/server-files

Direwolf20 1.8.0 server
![image](https://user-images.githubusercontent.com/17010632/181134738-f2a63cbf-f2b9-491f-8a8b-221f0178be86.png)
268 mod files downloaded
![image](https://user-images.githubusercontent.com/17010632/181134786-987fdf2d-604c-48d9-ad86-f172bd660afe.png)

**Comment by Rirush** [comment]
Yes, new installations work and update without any issues now for me.

I can still reproduce this issue though on an older install that failed to update previously. Seems that the installer gets confused by empty URLs in `version.json`. Deleting this file causes it to update just fine.

Here's a termbin link to my `version.json`: https://termbin.com/eb3w6

**Comment by Raidobw2** [comment]
I think I'm seeing some differences in that version file. Maybe that was related to some API changes a few days back. Glad to see that you managed to install/update the pack properly now, what I've done is report the issue to our developers as well. It does look ok now, but I wanted to give them the info on what happened too, so I've forwarded your version file with a comparison to another version file.
@DarksideVT can retry if they want, it looks fixed now

I'll mark this as fixed, if anything else happens let me know and thanks
