### ISSUE TITLE
[Bug]: Failed to download FTB one server files

### ISSUE THREAD

**Issue by ming514810** [FTBTeam/FTB-Modpack-Issues#1159]
### Modpack

FTB one

### Modpack version

1.3.0

### Describe the bug

No mods have been downloaded, the mods folder is empty.

### Steps to reproduce

1. Run the serverinstall_97_2235.exe
2. No mods have been downloaded

### Expected behaviour

Should be download correctly

**Comment by beamreaching1** [comment]
I am running into a similar issue on Debian 11 flavor of Linux.

I run the install executable and get an error that is repeated 45 times.
`Error downloading : Get "": unsupported protocol scheme ""`

Then a little further down the installer confirms this with...
`Downloaded 75 successful, 45 failed, 0 incomplete.`
`Some downloads failed. Would you like to continue anyway? (y/n) [y]`

**Comment by quietust** [comment]
Presumably the same problem as #1158

**Comment by Raidobw2** [comment]
I believe I checked yesterday and the server installer for Direwolf20 1.18 worked (which has the same issue). For those that wanted to install FTB One servers, can you check if this is still an issue by downloading the server once? Thanks in advance

**Comment by beamreaching1** [comment]
I went ahead and tried the same install method on Linux and ran into the same error as before.

**Comment by Raidobw2** [comment]
Hmm. I've tried on Windows just now for FTB One and it works fine. I'll try Linux in a bit

FTB One server
![image](https://user-images.githubusercontent.com/17010632/181137465-9f7efe51-3dcb-468c-bb89-97205380ecb1.png)
162 mods downloaded
![image](https://user-images.githubusercontent.com/17010632/181137501-5b57ffff-ae6f-4695-935c-3a02a391d3d5.png)
