### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Faxeswe1** [FTBTeam/FTB-Modpack-Issues#1160]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

my windows defender didn't allow med to use it

### Describe the bug

 I dunno if this is only for me but i have a game that i have done alot in and it seemse like it has corrupted or something and it won't start it just crashes

### Steps to reproduce

1. Start FTB Crackpack if you have it installed.
2. When loaded in start a game (if you have one)

### Expected behaviour

i expected it would load in like usually and i could play

**Comment by Raidobw2** [comment]
Do you happen to have any game logs showing errors? Also, did you check if you had any backup files in the `backups` folder, in your modpack installation?

In any case you can also drop your save file here with a file sharing service such as Google Drive and I could take a look.

**Comment by Raidobw2** [comment]
Actually, after seeing the linked issue above, can you navigate to `C:\Windows\System32\drivers\etc` in your computer and open the `hosts` file? I believe there could be information that shouldn't be in that file. Simply open the `hosts` file with Notepad (right click and Open With) and remove all lines that contain something like minecraft/mojang/microsoft/xbox/forge, then restart the FTB App and Overwolf.

Let me know if it works after that
