### ISSUE TITLE
[Bug]: Direwolf 1.7.0 world wont open in 1.8.0

### ISSUE THREAD

**Issue by MCScarface** [FTBTeam/FTB-Modpack-Issues#1162]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.8.0

### Describe the bug

When i tried loading up my 1.7.0 World in 1.8.0 the game instantly closed and didnt give me any kind of log file or anything.

### Steps to reproduce

Start up direwolf 1.18.2 vs 1.8.0
go to singleplayer
open world from 1.7.0

### Expected behaviour

The game will close instantly

**Comment by Raidobw2** [comment]
Hello, would it be possible to have more information? Without a game log, an error message or a screenshot showing the error, I can't really guess accurately what happened. I don't know of issues upgrading from 1.7.0 to 1.8.0, hence why my request for more info

**Comment by ukmcplyr** [comment]
I think I might've just hit this bug whilst attempting to load an old pre-1.8.0 singleplayer save in 1.8.0.

[crash.log](https://pste.ch/qagabejota.rb)

[latest.log](https://pste.ch/elopevucak.md)

I'll try and grab a screenshot from the app as well as I *think* there may gave been a few lines at the very tail of the console log that didn't end up in latest.log.

**Comment by ukmcplyr** [comment]
Seems that OptiFine is again the culprit, I can load pre-1.8.0 saves and indeed create new singleplayer worlds (which broke too) with it removed.

Though still unsure if the bug I'm experiencing and @MCScarface 's are one and the same :smile:

**Comment by Raidobw2** [comment]
Your bug looks exactly like #1130, in there I have a big comment with a lot of info that might help about that! I'll still wait to see if the OP has more information about the issue, but at some point I will be closing this request if it becomes stagnant.

**Comment by ukmcplyr** [comment]
Bah. I did search but bviously not deeply enough! Ta for the pointer :+1:

**Comment by TheonlyTazz** [comment]
moving this over to #1130 and closing this issue
