### ISSUE TITLE
[Bug]: Instance Crashes Upon Loading

### ISSUE THREAD

**Issue by sonicrelapse** [FTBTeam/FTB-Modpack-Issues#1163]
### What Operating System

Windows 10

### App Version

202203051730-9df8355f62-release

### UI Version

9df8355f62

### Log Files

https://pste.ch/avelikilep

### Debug Code

FTB-DBGBEXELUKOVE

### Describe the bug

The instance either crashes before loading, or the world loads until 100% and freezes

### Steps to reproduce

Launch Oceanblock.
Create a world
Place Pipez Universal Pipe next to a long chain of Powah! hardened energy cables
At some point it should crash, locking you out permanently

### Expected behaviour

I expected my world to load

### Additional information

This might be a mod problem, but if that were the case, I want an error report. I don't get that when it crashes/freezes.

### Information

- [X] I have provided as much information as possible

**Comment by Raidobw2** [comment]
This should have been fixed at #138, make sure you update OceanBlock to the latest version. I can see Pipez is version 1.2.14 in your game but the latest in OceanBlock is 1.2.15, which should fix that issue
