### ISSUE TITLE
Errors in currently selected datapacks prevented the world from loading. 

### ISSUE THREAD

**Issue by Nite-Hare** [FTBTeam/FTB-Modpack-Issues#1165]
![Screenshot (76)](https://user-images.githubusercontent.com/13861237/163191885-04c8050c-9f7d-4654-bd05-1b20e006639b.png)

I'm currently playing the Direwolf Modpack 1.16 on the FTB launcher. I've put many hours into this world and when I tried to play I received this error. Any ideas?

[latest.log](https://github.com/FTBTeam/FTB-App/files/8481835/latest.log)

**Comment by Raidobw2** [comment]
Hello, have you added any mods? Right now it's stuck on reading the configuration for ProjectE I think `moze_intel.projecte.config.CustomEMCParser`. That's not in the base pack, so I'd recommend taking the mod out and seeing if the error is solved, try joining a copy of your world with the mod removed.
