### ISSUE TITLE
Creating Plates with hammer and ingot - Immersive Enginneering[Bug]: 

### ISSUE THREAD

**Issue by christophersellers33** [FTBTeam/FTB-Modpack-Issues#1166]
### What Operating System

Windows 10

### App Version

FTB Revelation 3.6.0

### UI Version

cant find

### Debug Code

FTB-DBGVEGIKOVOWI

### Describe the bug

Can not create metal plates using Immersive Engineer's Hammer and ingot (i.e. Inon Plate). 

### Steps to reproduce

1. Use Ingot and Engineer's Hammer in crafting GUI, 2x2 and 4x4.  
2. Should create plate based on type of ingot being used with the hammer. 

### Expected behaviour

Combined resources should create a metal plate

### Screenshots

N/A

### Additional information

N/A

### Information

- [X] I have provided as much information as possible

**Comment by MCDemon117** [comment]
The same thing happened to me but on the Beta, I tried with the IC2 Hammer as well and it didn't work, my issue should be listed that I did yesterday.

**Comment by Gaz492** [comment]
I'm going to close this one and reference it to a newer issue that contains a possible fix.

See issue #5175 for the potential fix.
