### ISSUE TITLE
[Bug]: Pipez pipes reset to neutral/not pulling setting, on mekanism machines, on exiting world (chunk unload?)

### ISSUE THREAD

**Issue by Azutte** [FTBTeam/FTB-Modpack-Issues#1170]
### Modpack

direwolf20 1.18

### Modpack version

1.8.0

### Describe the bug

See title. When I log out and come back in, the fluid pipes that I have connected to my Thermal Evaporation Plants are no longer in pull mode.

### Steps to reproduce

1. set up two of these https://ftb.fandom.com/wiki/Thermal_Evaporation_Plant
2. set up water going into one (sink?) 
3. set up pipez fluid pipes grabbing brine from one and putting it in the other
4. exit game
5. return 

### Expected behaviour

it stays in pull mode

### Additional information

obviously an answer is "use another kind of fluid transport"

I think this might be happening with my compact machines too? or some other kind of problem

**Comment by Raidobw2** [comment]
Thermal evaporation plants reform on chunk load I think. You could indeed try Mechanical Pipes from Mekanism itself. Pipez might auto update itself if the block it's pulling from is unformed or reverted into something that can't interact with fluids anymore. In any case we might but forwarding this to Pipez as an improvement

**Comment by TheonlyTazz** [comment]
https://github.com/henkelmax/pipez/issues/128  issue already on the pipez tracker, gotta wait till the mod is updated or atleast adressed by the Pipez dev
