### ISSUE TITLE
[Bug]: Missing mod on FTB client with linux server

### ISSUE THREAD

**Issue by ChrysixCore** [FTBTeam/FTB-Modpack-Issues#1173]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

It seems like there is Quarry Plus on the Linux server modset while it is missing in the client modlist.
Resulting in not being able to connect to the server.

(and the automated unpack of the tar.gz in the jre folder isn't working)

### Steps to reproduce

1. Install the current FTB One modpack on a Ubuntu 22.04 machine
2. Manually unpack the "ftb-one"/mc-server/jre/*.tar.gz (it didn't automatically unpack it on any of my attempts. So maybe add a tar -xvzf "targetfile.tar.gz")
3. Once the server started i tried to log in from my client system and it showed a error that i'm missing QuarryPlus v19.2 on the client.

### Expected behaviour

Unable to log in from the client system

**Comment by Raidobw2** [comment]
Hi, have you tried reinstalling the client and did the mod appear? Thanks for letting me know in advance

**Comment by ChrysixCore** [comment]
Hi, 
I just reinstalled the server and the client and it seems to work now.
Please let me know if you changed anything or if it was just some random incident. 
kind regards,

**Comment by Raidobw2** [comment]
Thanks for the reply, glad it works now! I am not aware of any changes to our infrastructure in the past day. This might have been a random incident, although if it happens again let us know here or on the FTB Discord https://go.ftb.team/discord.

Since that's resolved for now, I'll close the issue. Have fun playing!
