### ISSUE TITLE
[Bug]: Unequiping Blood Magic Living Armor pieces causes Server Crash

### ISSUE THREAD

**Issue by AmayaMaka** [FTBTeam/FTB-Modpack-Issues#1174]
### Modpack

FTB Oceanblock

### Modpack version

1.14.0

### Log Files

https://paste.feed-the-beast.com/view/2afbe631

### Describe the bug

Server crash on FTB Oceanblock whenever I remove my bloodmagic armor. The Crash report says something about slot 0 being "not in valid range".
This is repeatable for me, I've done it like 5 times.
It doesn't happen in singleplayer though.
When I first enter the world after a server restart, I'm able to remove the armor, but when I've been doing stuff, or after I've put it on again and try to remove it again, the server crashes again.

### Steps to reproduce

1. Log onto a server
2. Create Living Armor from Blood Magic using Arcane Ashes.
3. Equip Armor (full set, but uncertain if this matters)
5. Unequip Armor (any piece, via shift click OR via click and move, doesn't seem to matter)
6. Crash

### Expected behaviour

Able to unequip armor without crash

### Additional information

Because of the "slot 0" error, I've also tried this with a completely empty inventory, and gotten the same result.
I do have flux networks active, but they are not trying to charge my armor slots (should only be charging curios and hotbar).
As far as I know, I have nothing else that should be affecting my armor slots.
My Blood Magic Armor currently has: the level 1 slot upgrade, tough palms 4, healthy 3/4/5 (don't remember exact level) but this has happened multiple times before any point of leveling or having any of these upgrades as well.

**Comment by Raidobw2** [comment]
Looks to be an error with Flux Networks. Try removing wireless player charging completely in the Flux Networks Controller block and see if that solves the crashes for now

**Comment by TheonlyTazz** [comment]
Tried this on the latest dev, could not reproduce with updated bloodmagic.
Closing this issue as it has become stale, if this happens on the next update, feel free to create a new issue
