### ISSUE TITLE
[Bug]: Items disappearing with AE2/Functional Storage

### ISSUE THREAD

**Issue by readytodream** [FTBTeam/FTB-Modpack-Issues#1177]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.8.0

### Describe the bug

When using the import bus to add items into the storage network (a combination of AE2 and functional storage) some items go into the system and some disappear. There are also flickering items in the terminal like they keep appearing and disappearing.

### Steps to reproduce

I'm not sure how to reproduce it, sometimes it works fine and sometimes it doesn't. I've lost dimlets and another player lost all of the ores he had.

### Expected behaviour

When inputting items i expect them to not disappear.

### Additional information

Not really sure what else can help with this, let me know if there is anything.

**Comment by readytodream** [comment]
I realised a video of the flickering items thing might be useful.
https://user-images.githubusercontent.com/86254343/180904754-6dceae97-a9d5-4da3-a666-868475357fa7.mp4

**Comment by Raidobw2** [comment]
Odd, are there any export/import buses in a loop in your AE2 network? Are those books within a specific functional drawer somewhere? (if you have a picture of that drawer and the surrounding drawers, we'll take it!)

**Comment by readytodream** [comment]
There are no export/import bus loops, when I lost the dimlets they weren't in drawers but this specific flickering item is. Pictures are of the drawer with the flashing book in and the controller connection to ae2 system.
![java_nVgx0KoSET](https://user-images.githubusercontent.com/86254343/180910343-51e857e1-9483-468f-ab79-ee1ad09dd1b0.png)
![java_NBgsGmudu0](https://user-images.githubusercontent.com/86254343/180910353-fbb39324-a591-40a9-88f4-7c53fe5d7924.png)

**Comment by faanlez** [comment]
I've had this happen with Refined Storage and Functional Storage. Replacing the Storage Controller resolved it.

It probably has to do with how the drawers are linked and removing them without unlinking first can sometimes still keep their contents available despite the drawer being truly gone so you will void items that go into it but also able to get items out effectively duping them.

I would report this to Functional Storage as it's most likely on their end.

**Comment by Raidobw2** [comment]
I see, that's useful feedback, thanks to you both. We'll try and reproduce this in-game and likely report to Functional Storage in that case

**Comment by NilocTheDragon** [comment]
i have the same problem with items flickering, as in, disappearing and reappearing in uneven intervals, up to several times a second per kind of item... tho they aren't disappearing forever, just not showing on the terminal when disappearing, but they're still in the connected chest. i am also using modded storage, in my case it's sophisticated storage chests (problem persists with and w/o stack upgrades). okie, i wanted to try using vanilla storage before commenting this, and the problem went away after replacing every non-ae2(+addons) container with vanilla ones! ig it is pretty annoying cuz they're tiny, but at least i can now take stuff out of my me system without first clicking on the wrong item 20 times rahhh

i know this is old as fluff, but good luck :3
