### ISSUE TITLE
[Bug]: fps problem

### ISSUE THREAD

**Issue by BoxerMan431** [FTBTeam/FTB-Modpack-Issues#1179]
### Modpack

FTB University 1.16

### Modpack version

latest

### Describe the bug

hello, i just started to play university and i have a fps problem. How can i increase my fps?
my specs are : i5 10th gen, gtx 1060 ti, 16gb ram ( minecraft using 12gb of it ) and ssd ( game might be located at hdd )

### Steps to reproduce

.

### Expected behaviour

i want more fps if its possible

**Comment by Raidobw2** [comment]
Try a few things from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1130#issuecomment-1191028332 and let me know if that's any better

**Comment by BoxerMan431** [comment]
> Try a few things from [#1130 (comment)](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1130#issuecomment-1191028332) and let me know if that's any better

Hello, changing forge's config helped to increase couple of fps but it is still not playable.

**Comment by Raidobw2** [comment]
Have you tried more of the suggestions in that comment as well? There's not much else I'm aware of to increase FPS than those suggestions, that's literally all I know of

**Comment by BoxerMan431** [comment]
Well i get help from somewhere else and they suggest to download couple more mods. Here is their name ; entity culling, smoothBoot and performant instead of roadrunner which is already in the pack. I get 40-50 fps now. Not too much but still something.
