### ISSUE TITLE
[Bug]: Game crashes and you can't open the save

### ISSUE THREAD

**Issue by Disnejar** [FTBTeam/FTB-Modpack-Issues#118]
### Modpack

FTB University 1.16

### Modpack version

1.2.0

### Log Files

[crash-2021-10-11_17.05.06-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7323640/crash-2021-10-11_17.05.06-client.txt)

### Describe the bug

I was in a Ocean Piramid I guess and suddenly the game crashed. The crash screen said no mods where causing the problem, but the crash log said it had problems with rendering the forgotten mob from quark.

### Steps to reproduce

I think you just spawn a forgotten mob from quark.

### Expected behaviour

After you spawn the mob the game should crash.

### Additional information

It saves the world after it crashes and thus I can't use the save anymore because the bug just reappears.

**Comment by Disnejar** [comment]
Yeah I know, should I just delete the mod for now?

**Comment by zoller27osu** [comment]
I've seen and killed Forgotten and they've never given me any issues?
I did once irreparably corrupt my world by slipping and falling on a Woot block or something - the polygons went weird (stretching triangle hell) and then it crashed and I was unable to load the world even by editting the NBT to place me back at spawn.
Luckily we have auto backups though!
