### ISSUE TITLE
[Suggestion]: Add YAQOL

### ISSUE THREAD

**Issue by enderger** [FTBTeam/FTB-Modpack-Issues#1180]
### Modpack

FTB One

### Mod suggestion

Link: https://modrinth.com/mod/yaqol
YAQOL (pronounced "yeah, cool") is a mod which provides several quality of life additions to Minecraft. It has a similar development policy to the pack itself (don't break backwards compatibility needlessly, develop on a rolling release), and even in it's current state may complement the pack well (it currently has (char)coal chunks and a repairable tool system balanced to encourage some level of early exploration while keeping mending and other harder to obtain systems worthwhile). The development model also means that the two projects can mutally benefit each other (the mod adding content with the same backwards compatibility focus as the pack and the pack providing a source of bug reports and suggestions that help further refine the mod).

**Comment by Saereth** [comment]
It's not on curseforge so it's not available on our distribution network
