### ISSUE TITLE
Mahou/Tempad Rendering Incompatibility

### ISSUE THREAD

**Issue by CodexAdrian** [FTBTeam/FTB-Modpack-Issues#1181]
### Modpack

FTB One

### Modpack version

Latest

### Log Files

Mahou appears to have some rendering that is broken when Tempad is present in the pack. Very simple fix, change the Tempad client config to have “timedoorFancy” set to false, that should fix any of those issues.

### Describe the bug

Rendering not working with Mahou properly

### Steps to reproduce

Use something from mahou that renders something in world
Profit

### Expected behaviour

Rendering things properly

### Additional information

I’m the mod author of Tempad. Apologies for any inconvenience. I’m trying my best to fix this issue, this config is a temporary solution until I find a more permanent one.

**Comment by Raidobw2** [comment]
No problem, we appreciate the help. We'll do that config change for now. Thank you for your work as well!

**Comment by Saereth** [comment]
This render issue is now fixed in the update to ftb one 2.0 when we release it (soon)
