### ISSUE TITLE
[Bug]: SkyFactory 2 crashes when putting an item in loot recycle

### ISSUE THREAD

**Issue by Assasin164th** [FTBTeam/FTB-Modpack-Issues#1182]
### Mod

LootBags

### Mod version

1.7.10-2.0.16

### Forge / Fabric version

10.13.4.1614

### Modpack & version

FTB SkyFactory 2

### What issue are you having?

Hello, I play on SkyFactory 2. Every time any item gets into Loot Recycle, minecraft crashes.

### Steps to reproduce

A crash occurs every time any item enters the Loot Recycle, regardless of whether the player put it there or it was delivered there using pipes.

**Comment by Raidobw2** [comment]
SkyFactory 2 isn't a modpack made by Feed The Beast to my knowledge. Is it FTB Presents SkyFactory 2.5 instead you are talking about?

In any case if you have a crash log I can give you some advice on the crash, though since SF2 isn't our pack we won't be able to fix that.

**Comment by manmaed** [comment]
please respond to @Raidobw2 and make sure if you are playing SF2.5 to be running version 2.5.8
