### ISSUE TITLE
[Bug]: Cannot upgrade Quark Chests to Crates

### ISSUE THREAD

**Issue by tilda** [FTBTeam/FTB-Modpack-Issues#1183]
### Modpack

FTB Fiberglass Mountain

### Modpack version

1.1.1

### Describe the bug

The Chest -> Crate upgrades from Better Crates cannot be used to upgrade Quark Chests, which are normally crafted when using planks. Of course, you can still make vanilla chests using a crafting recipe but it's still extra friction that shouldn't be there.

### Steps to reproduce

1. Craft a Quark chest (i.e. Oak, etc variants) & a Better Crates upgrade (i.e. Chest -> wooden Crate)
2. Place down chest
3. Attempt to Shift+Right Click the chest with the Better Crates upgrade
4. See that it does not upgrade to a crate

### Expected behaviour

For the Quark chest to be upgraded to a Crate

**Comment by Raidobw2** [comment]
Oops, that's actually a mod issue.
Tracking at https://github.com/TheTestMod/BetterCrates/issues/9
