### ISSUE TITLE
[Bug]: Fluid Encapsulator Recipe not working Oceanblock

### ISSUE THREAD

**Issue by cholimba** [FTBTeam/FTB-Modpack-Issues#1184]
### Modpack

FTB Oceanblock

### Modpack version

1.14.0

### Describe the bug

Normally ur able to make dense construction blocks with the fluid transposer, cause it got renamed i guess it doesnt work in this mod pack. Would be great if u add the recipe to make dense construction blocks.

Construction Block Powder -----> Dense construction block

Would be awesome, cause there's no "fast" way to automate it unless with miners and Placers but they are buggy as hell.

The biggest problem is, that i need a lot of them for Singularities, but doing it by hand is ... special

### Steps to reproduce

Start the game and see that there is no recipe for it.

### Expected behaviour

add recipe into fluid encapsulator

**Comment by quietust** [comment]
Have you considered using an RFTools Builder with a Shape card to place the blocks underwater, then using another RFTools Builder with a Clearing Quarry card to mine them afterwards?

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/184312782-87f47d22-c6eb-4b9f-8f9a-2adea110cc20.png)
added
