### ISSUE TITLE
[Bug]: Raw Storage blocks have no crafting recipe

### ISSUE THREAD

**Issue by Staegrin** [FTBTeam/FTB-Modpack-Issues#1187]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.8.0

### Describe the bug

Uranium and Aluminum have no crafting recipe for their raw storage blocks. Both can only be created in the thermal multiservo press using the packing die 3x3

Iridium also doesn't have a recipe and sadly also doesn't have a raw storage block

### Steps to reproduce

1. Gather raw uranium or Aluminum
2. fill the 3x3 crafting grid
3. output?

### Expected behaviour

Have a shapeless recipe to make the storage blocks

### Screenshots

![2022-07-28_00 29 49](https://user-images.githubusercontent.com/8494635/181383761-f6783b47-6a64-46df-b7b5-a500c11f591f.png)
![2022-07-28_00 29 54](https://user-images.githubusercontent.com/8494635/181383762-7fa54de4-4e9d-4b85-9aea-3ab1499d3bfc.png)

**Comment by Staegrin** [comment]
Added 
  event.shapeless("immersiveengineering:raw_block_uranium", ["9x #forge:raw_materials/uranium"]);
  event.shapeless("#forge:storage_blocks/raw_aluminum", ["9x #forge:raw_materials/aluminum"]);
In the recipes.js as a fix
If #forge:storage_blocks/raw_uranium was used in the first recipe the mekanism storage block is created not the immersive engineering variant you would get from the multiservo press.

**Comment by Raidobw2** [comment]
Thank you for your help and the code snippet 🙂

**Comment by TheonlyTazz** [comment]
Thanks alot for the snippet! added it into the V1.9 indev and should come with the next update

**Comment by Staegrin** [comment]
My pleasure

**Comment by faanlez** [comment]
Uncompressing these in regular crafting is still missing.

**Comment by TheonlyTazz** [comment]
Woops! I'll add that tomorrow and follow up with a fix to be pasted in the server script, which will be implemented in future versions

**Comment by TheonlyTazz** [comment]
```
event.shapeless("9x #forge:raw_materials/uranium", ["immersiveengineering:raw_block_uranium"]);
event.shapeless("9x ftbic:aluminum_chunk", ["#forge:storage_blocks/raw_aluminum"]);

```
Added to the Server scripts should fix this issue, added it indev, will be included in the next version
