### ISSUE TITLE
[Bug]: Cannot complete Arc Furnace quest

### ISSUE THREAD

**Issue by swiftgeek75** [FTBTeam/FTB-Modpack-Issues#1189]
### Modpack

FTB Oceanblock

### Modpack version

1.14

### Describe the bug

Can't complete Arc Furnace quest after building arc furnace and having graphite. The graphite part of it works, but I've built the arc furnace three times and it won't get recognized for the quest.

### Steps to reproduce

Build an arc furnace

### Expected behaviour

Quest recognizes the arc furnace and completes

### Screenshots

![2022-07-28_14 06 52](https://user-images.githubusercontent.com/39579946/181637681-c5edbd6c-0319-4b51-99f0-7b8213f590aa.png)
![2022-07-28_14 06 37](https://user-images.githubusercontent.com/39579946/181637692-e2572f37-68c4-4244-806e-59e514640f4f.png)

**Comment by Raidobw2** [comment]
Continuation of #769. Looks like the task needs to be set to the actual block, currently it is set to:
![image](https://user-images.githubusercontent.com/17010632/181652189-118c789f-d302-44cd-8e60-8153e4822685.png)
Which does not correspond to anything, however changing it to this will fix it:
![image](https://user-images.githubusercontent.com/17010632/181652226-7b00f2b5-1af5-424a-9b24-ffe3ea28d08a.png)
![image](https://user-images.githubusercontent.com/17010632/181652415-fcbf37a2-892c-48fb-92f3-007127396e79.png)

As seen in-game by the targeted block:
![image](https://user-images.githubusercontent.com/17010632/181652250-3b10ff10-1d4e-48c8-9a72-47bbf683d20a.png)
path: `config\ftbquests\quests\chapters\immersive_engineering.snbt`, search "arcFurnace"

**Comment by swiftgeek75** [comment]
Cool - thanks for the quick response and the workaround. I'll try it out!
________________________________
