### ISSUE TITLE
[Bug]: Crash

### ISSUE THREAD

**Issue by Scuzmb** [FTBTeam/FTB-Modpack-Issues#1190]
### Mod

Suspected is extra utils 2, chicken mod

### Mod version

1.22.0

### Forge / Fabric version

14.23.5.2860 forge

### Modpack & version

FTB stoneblock 2 - 1.22.0

### What issue are you having?

Render crash

### Crashlogs

[crash-2022-07-29_01.15.20-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/9221373/crash-2022-07-29_01.15.20-client.txt)

### Steps to reproduce

I was just playing

**Comment by TheonlyTazz** [comment]
does this crash happen everytime you render said item transfer node?
