### ISSUE TITLE
[Bug]: Nuclear Reactor overloads everything while only outputting 5 zaps

### ISSUE THREAD

**Issue by GuiltyRegicide** [FTBTeam/FTB-Modpack-Issues#1191]
### Modpack

Ultimate-Anniversary

### Modpack version

1.16.5

### Describe the bug

![image](https://user-images.githubusercontent.com/58578426/181853563-f7ac460f-371a-4f74-b1d1-f049151efae7.png)
![image](https://user-images.githubusercontent.com/58578426/181853906-16eb0659-c583-41ac-b0ee-32c3657a7873.png)
Reactor overloads machines even though its outputting only 5 zaps a tic.

![image](https://user-images.githubusercontent.com/58578426/181853833-7ea398f4-f336-4bb1-a6bf-2b4f8484a03f.png)
 Even blows up a transformer.

### Steps to reproduce

1.Make reactor
2.Put in single rod and appropriate fans
3.connect machines 
4. they explode

### Expected behaviour

Reactor to output displayed energy levels and power connected machines properly.

**Comment by TheonlyTazz** [comment]
Thank you for your Issue, I will forward this issue to the corrosponding dev and hope this gets resolved

**Comment by Raidobw2** [comment]
This has been fixed in the mod at https://github.com/FTBTeam/FTB-Mods-Issues/issues/349 for 1.18+, though it might require a backport to 1.16.5 for the modpack
