### ISSUE TITLE
[Suggestion]: Add Rubidium & Oculus

### ISSUE THREAD

**Issue by enderger** [FTBTeam/FTB-Modpack-Issues#1192]
### Modpack

Most 1.18+ forge packs

### Is your suggestion related to a problem? Please describe.

FTB packs tend to be some of the most technically demanding versions of minecraft to exist, even causing our current-gen development machine to struggle to work smoothly. Additionally, many like to play with shaders that add visual flare to the game if their PC can handle it.

#### Description
Rubidium is a port of Sodium to the Forge modloader, and Oculus is the same for Iris. The former provides significant performance improvements in a redistributable and open package, while the latter provides beautiful shaders in very similar packaging.

#### Compatibility
Both mods appear to work out of the box on the latest version of FTB One and FTB Presents Direwolf20 1.18, with the only issues being a few minor visual bugs when shaders are enabled (when using shaders in DW20, Tinkers Construct fluids have rendering issues that are mitigated by enabling the `tankFluidModel` option, and Minecolonies shows minor rendering artifacts). FTB Plexiglass Mountain seems to fare significantly worse, with `AutoRegLib` throwing an `ArrayIndexOutOfBoundsExcepetion` when loading alongside Rubidium.

#### Links
Due to some browser issues, we're using Modrinth links. They also are on CF.
- Rubidium: https://modrinth.com/mod/rubidium
- Oculus: https://modrinth.com/mod/oculus

**Comment by TheonlyTazz** [comment]
As a player, feel free to add Rubidium and Oculus to the pack yourself, we at FTB are not going to add them by default.
