### ISSUE TITLE
[Suggestion]: Pre chunk generation

### ISSUE THREAD

**Issue by lazycooken** [FTBTeam/FTB-Modpack-Issues#1194]
### Modpack

DireWolf20

### Is your suggestion related to a problem? Please describe.

It be nice for server people and some people on single player to be able to generate chunks of the world before hand playing or at the start of a game with a command and to a set distance they wish.

**Comment by TheonlyTazz** [comment]
People can add World pregen mods themself, they are available on Curseforge and not going to be added to the pack
