### ISSUE TITLE
[Bug]: StoneBlock 2 world won't open

### ISSUE THREAD

**Issue by Malunyn** [FTBTeam/FTB-Modpack-Issues#1195]
### Modpack

FTB Presents Stoneblock2

### Modpack version

1.16.1

### Describe the bug

well, idk what i did but the game crashed and i cant open my world

### Steps to reproduce

nothing :P 
i did nothing

### Expected behaviour

nothing again

### Screenshots

![image](https://user-images.githubusercontent.com/81432667/181995266-4c05fffe-de39-4d64-95a9-25942d5e1d95.png)

### Additional information

everytime i try to reopen my world its the same screen again and again

**Comment by MichaelHillcox** [comment]
Please attach logs

**Comment by Raidobw2** [comment]
Please update StoneBlock 2 to the latest version 1.22.0. The 1.16.1 version of the modpack is quite old and still contains many issues, while the versions after that up to 1.22.0 (marked as beta) contain many fixes and fixes for game crashes, one which could apply to you.

That version of StoneBlock 2 is available on the FTB App https://www.feed-the-beast.com/app.

Once you've updated, if your world still doesn't load please attach the crash log as mentioned by Michael by clicking the green crash text and pasting the text inside https://paste.feed-the-beast.com/. Hit "create" after that and you can put the URL to the paste here. Thanks in advance!
