### ISSUE TITLE
[Bug]: Wont start / Crash

### ISSUE THREAD

**Issue by Ingelberg** [FTBTeam/FTB-Modpack-Issues#1199]
### Modpack

FTB Revelation

### Modpack version

BETA 3.6.0

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9236857/console.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9236861/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9236863/debug.log)

### Describe the bug

When launching through the FTB App, the app wont go past "Finishing up // Mantle". And nothing happens. Even when leaving it over night. 

When launching through any non official app, The window opens and starts loading. but when it comes to "7/7" the app is "not responding". Even if I leave it over night. 

Tried reinstalling Java, all the launchers. Tried allocating more ram (through the client and java argument). Reinstalled windows, both from just the settings and through a newly created usb. Nothing works!

### Steps to reproduce

Just clicking play. Cant not get it to crash.

### Expected behaviour

Launch FTB

**Comment by Raidobw2** [comment]
Try removing MineTogether from the mods and see if it still does that. Click "Settings" in the modpack general page, then "Open Folder". Open the "mods" folder and delete `MineTogether-1.12.2-2.4.5.jar`, then start your game and let me know if it works after

**Comment by Ingelberg** [comment]
It worked!! Thanks!!
