### ISSUE TITLE
[Bug]: Volumetric Flask causing Server Crash

### ISSUE THREAD

**Issue by SloppyClops** [FTBTeam/FTB-Modpack-Issues#1200]
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Log Files

[crash-2022-08-01_08.25.07-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9237332/crash-2022-08-01_08.25.07-server.txt)

### Describe the bug

I started setting up autocrafting and some recipes required fluids so I went with volumetric flask interfaces. I request some nanoprocessors and the server crashed like 5 seconds after I requested. When I restarted the server, the request still went through and it completed the process

### Steps to reproduce

For my exact case, you have to set up autocrafting for nanoprocessors but its more of just set up a bunch of autocrafting with volumetric flask interfaces

### Expected behaviour

The ME should autocraft without crashing the server

### Screenshots

![image](https://user-images.githubusercontent.com/110426879/182244035-2de8e018-56fd-40fa-99f2-d3c3074a4905.png)
![image](https://user-images.githubusercontent.com/110426879/182244080-e9f4b075-3c31-4c31-85e1-aba158032d4b.png)

**Comment by KorewaLidesu** [comment]
Can you try update PAE2 version?
Atleast that may be solution.
https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life/files/
