### ISSUE TITLE
[Bug]: External Storage on Ender Tank breaks RS network

### ISSUE THREAD

**Issue by ProbNotTrunks** [FTBTeam/FTB-Modpack-Issues#1203]
### Modpack

DireWolf20 1.18

### Modpack version

1.8.0

### Describe the bug

Attaching an external storage from Refined Storage to an Ender Tank causes the Refined Storage system to not allow the player to pull any items out of it. Problem was resolved when external storage on the tank was removed. All other external storages working just fine. You can insert items into the system but there is a slight desync in the fact that even if the item already exists in the system, the items you deposit show as a different item stack in the grid. Tried with both an empty and full ender tank. 

### Steps to reproduce

1. Attach external storage to ender tank using pre-existing RS network. 
2. Open refined storage network via grid or wireless grid. 
3. can not pull items out, de-sync of items. 

### Expected behaviour

expected external storage to read fluid data from ender tank and recognize the tank as valid fluid storage for the system to access. 

### Additional information

I can provide video evidence, just the video file was too large for this form.

**Comment by quietust** [comment]
Was the External Storage reconfigured to "Fluid" mode or was it still in the default "Item" mode?

**Comment by quietust** [comment]
Out of curiosity, was the External Storage connected to the _top/bottom_ of the Ender Tank or to one of its sides (to which fluid pipes normally cannot be connected)?

**Comment by ProbNotTrunks** [comment]
I made sure it was connected to one of the sides where pipes normally can
connect. I am not sure I tried on a different side or not.

**Comment by TheonlyTazz** [comment]
i actually just tried it with just RS and Endertanks and could not replicate it either.
Still curious why it borks on the Direwolf20 pack

**Comment by ProbNotTrunks** [comment]
So it DID bork when you tried it in the DW20 pack?

**Comment by TheonlyTazz** [comment]
it did on first play, after reloading the world:

fluids are still wonky, you can only take out 1 bucket of liquid at a time by clicking the liquid while having empty buckets in ur inventory and you need to close/open the gui after each bucket

items are working fine now and there is no desync

**Comment by ProbNotTrunks** [comment]
Ok. I will have to try again when I can. I don't think having 0 fluid
storage disks in my networks should matter since I am using an external
storage tank. But just want to try to replicate it again if I can.
