### ISSUE TITLE
[Bug]: Cyclic's Crushing Macerator has 2 recipes for the Wither Rose

### ISSUE THREAD

**Issue by Khaosina** [FTBTeam/FTB-Modpack-Issues#1205]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.8.0

### Describe the bug

Cyclic's Crushing Macerator has 2 recipes for the Wither Rose that appear in JEI. 
The first is a 1000 RF one that results in 2 black dye and a 50% chance at up to 5 extra black dye. 
The second is a 24000 RF one that should result in 2 soul sand and a 50% chance at up to 2 Ghast Tears.
Only the first recipe actually works in-game.

### Steps to reproduce

1. Put down a Cyclic Crushing Macerator with a power source.
2. Put Wither Roses in it.
3. Only receive Black Dye as a product, no Soul Sand or Ghast Tears as the recipe in JEI claims.

### Expected behaviour

One would expect the Soul Sand/Ghast Tears recipe to work, or for it to be removed/changed in JEI. It seemed like a nice way to get Ghast Tears.

### Screenshots

What's shown in JEI when viewing the Uses for Wither Roses in the Cyclic Crushing Macerator:
![image](https://user-images.githubusercontent.com/43579920/182625137-7d8064ad-facd-4763-9dbf-e3b48fedbfc2.png)

### Additional information

The Cyclic issues tracker has something open about this already, but the only acknowledgement has been the addition of a 1.18 label to the Issue:
https://github.com/Lothrazar/Cyclic/issues/2132#issue-1303226274

**Comment by TheonlyTazz** [comment]
added the recipe_id
`cyclic:crusher/cyan_dye` to the recipes_id's to remove, which fixes this issue,
should be fixed in v1.9
![image](https://user-images.githubusercontent.com/3908847/182797009-97e29c95-426a-4830-b7a4-4c26178a830d.png)
