### ISSUE TITLE
[Bug]: Powered Rails everywhere and other bugs when using latest D20 1.18 packaged installer Linux/Windows

### ISSUE THREAD

**Issue by magicalbeard** [FTBTeam/FTB-Modpack-Issues#1207]
### Modpack

Direwolf20

### Modpack version

1.18

### Log Files

Server Startup Logs:
https://pastebin.com/BA72Xew2

### Describe the bug

Textures and mods are not loading properly when installed from latest FTB D20 1,18 server installer package. Redstone rails and other artifacts are present throughout the map.

It does generate the following when destroying a block that is not rendering properly:
`[18:11:02] [Server thread/WARN]: Mismatch in destroy block pos: gj{x=0, y=0, z=0} gj{x=-105, y=77, z=-21}`

### Steps to reproduce

1. Install new D20 server using the "serverinstall_95_2234" Linux or Windows installation package (acheived by `chmod +x serverinstall_95_2234`, `./serverinstall_95_2234` - this was installed under /opt/minecraft as root.)
3. Replace "insert_jar_file" in start.sh with "minecraft_server.1.18.2.jar"
4. run start.sh
5. connect to server with a client running latest 1.18 FTB client

### Expected behaviour

Server should install and run without issue

### Screenshots

![unknown](https://user-images.githubusercontent.com/3375292/182679379-7c580f68-3c8d-499a-a46d-af8b356ceaf9.png)

**Comment by Sunekaer** [comment]
Your starting a vanilla minecraft server and not modded.
there should be a run.sh, use that instead.

**Comment by magicalbeard** [comment]
Thank you! in all the docs I could find it says to use start.sh - and run.sh didn't work out of the box because you need to point it at the correct JRE that is installed with the package, not use the environment JRE. 

Closing.

**Comment by Raidobw2** [comment]
Just for completion if someone else comes across this, that's caused by not having Java 17 on the base system when running the installer. The Forge installation will fail, and thus, the start script will not be populated properly.

The workaround is to install Java 17 and run the server installer again to download the files again.

This is reported at https://github.com/CreeperHost/modpacksch-serverdownloader/issues/14
