### ISSUE TITLE
[Bug]:  Malum Soul Stained Steel Scythe causing crash when attacking cows

### ISSUE THREAD

**Issue by VintageBadger** [FTBTeam/FTB-Modpack-Issues#1209]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.1.1

### Describe the bug

When hitting cows with the Soul Stained Steel Scythe from Malum, the server would crash. 

### Steps to reproduce

1. Spawn multiple cows
2. Hit cows with Soul Stained Steel Scythe

### Expected behaviour

Expecting the cows to be damaged and/or killed

### Additional information

We are currently playing on a MineTogether server though unsure if this is affecting the issue.

The Crude Scythe from Malum was able to attack both passive and hostile mobs without causing any issues.

**Comment by Raidobw2** [comment]
Hi, thanks for reporting. Do you have the crash log with the error? You can find it inside the modpack folder, in the `crash-reports` folder. They'll be labeled by date, the latest crash should be it. Thanks in advance

**Comment by VintageBadger** [comment]
[crash-2022-08-03_22.11.04-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9261635/crash-2022-08-03_22.11.04-server.txt)

**Comment by VintageBadger** [comment]
^sorry it took awhile I had to get the crash report from the server owner

**Comment by Raidobw2** [comment]
Awesome, thanks a bunch

**Comment by Raidobw2** [comment]
Hmm. I can't seem to be able to reproduce this in development. If there were more things involved than in the video, let me know, I'll test them. I've done a lot of mod updates, so it's possible one of them fixed this issue. I'll assume fixed for now

https://user-images.githubusercontent.com/17010632/185044887-e7d2e276-b054-4f48-95c2-1f055c77d0d9.mp4

**Comment by Raidobw2** [comment]
I assume that's fixed in 1.2.0, let me know otherwise
