### ISSUE TITLE
[Bug]: Orange Rose (Soul Ice) Hitbox

### ISSUE THREAD

**Issue by IanMcC99** [FTBTeam/FTB-Modpack-Issues#1210]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.0.2

### Describe the bug

Orange rose from soul ice have a hitbox that obstructs movement, unlike other flowers, which can be freely moved thorugh

### Steps to reproduce

Find flower, and attempt to walk through it

### Expected behaviour

Moving through the flower

**Comment by Raidobw2** [comment]
Please update your modpack to 1.1.1, Soul Ice had an update which fixed the hitbox. I believe I had also added in a recipe for that Orange Rose in 1.1.1, which you can convert to orange dye now.
