### ISSUE TITLE
[Bug]: AE2 JEI Crafting terminal doesn't correctly identify missing items

### ISSUE THREAD

**Issue by BallSmall500** [FTBTeam/FTB-Modpack-Issues#1212]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.8.0

### Log Files

Non applicable

### Describe the bug

When trying to craft using JEI integration, AE2 incorrectly says there is an item where it isn't. Updating AE2 doesn't solve it, and the bug doesn't reproduce on a clean environment with just AE2 and JEI.

![image](https://user-images.githubusercontent.com/110630872/182935422-b1a910bf-e540-436a-a74d-e7deb4998a0b.png)

There should be a red background on one of the quartz glass.

### Steps to reproduce

Using a AE2 crafting terminal having:
4 Iron ingots
1 Annihilation core
1 Formation core
1 Quartz glass

When you try to craft a Molecular assembler, you are missing 1 quartz glass but JEI doesn't let you know.

### Expected behaviour

On other recipes when you are missing items they have a red background, plus JEI tells you missing items will be skipped

### Screenshots

![image](https://user-images.githubusercontent.com/110630872/182936073-af0b7897-897f-4ade-b4e5-ae188ff7b014.png)

This is a complementary image to the expected behavior section.

### Additional information

The iron ingots are being pulled from a ME storage bus connected to a storage controller from Functional Storage. Another recipe that have the same problem for me is the Me Pattern provider, on which I have every item but 1 crafting table.

![image](https://user-images.githubusercontent.com/110630872/182936883-16dc9c61-9a35-473b-a468-6a10ad5070fc.png)

When moving the items into the crafting terminal:
![image](https://user-images.githubusercontent.com/110630872/182936941-0d090531-4e56-4911-88b3-629760d08ad8.png)

From my understanding other recipes when you have more than 1 missing item works fine.

**Comment by BallSmall500** [comment]
Updating AE2 and JEI also doesn't seem to solve the problem.

**Comment by TheonlyTazz** [comment]
I just tested on the latest in-dev:
![image](https://user-images.githubusercontent.com/3908847/183140153-cdbe742c-328e-461f-83e1-2b0ab294d93c.png)
and couldnt replicate
![image](https://user-images.githubusercontent.com/3908847/183140336-5f516327-8849-4d72-af78-4a6abd4984c3.png)

running
appliedenergistics2-11.1.5.jar
jei-1.18.2-9.7.1.232.jar
