### ISSUE TITLE
[Bug]: for tinkers construct your unable to make a 11x11 x11 smeltery

### ISSUE THREAD

**Issue by shadeslayer2040** [FTBTeam/FTB-Modpack-Issues#1214]
### Modpack

FTB Stoneblock 2

### Modpack version

1.22.0

### Describe the bug

its unable to create the smetry

### Steps to reproduce

make a sibngle player world 
go into creative 
get seared stone brick 
build it into a 11x11 with the floor also made of said brick
floor lvl of the wall place a smeltry controller and tank
fill the tank wit lava

### Expected behaviour

for the smeltry to work

**Comment by TheonlyTazz** [comment]
1.12 Smeltery can only be 11x11, with 9x9 internally, thus not an issue

**Comment by Raidobw2** [comment]
Please see Tazz's answer and if you need help setting the smeltery up, visit the community in the FTB Discord, there is a stoneblock channel https://go.ftb.team/discord
