### ISSUE TITLE
[Bug]: Inventory chargers not working while in bauble slots

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#1215]
### Modpack

FTB Academy 1.16.5

### Modpack version

1.3.0

### Describe the bug

When slotting inventory chargers in bauble slots (Flux Capacitor, infinity backpack) and set to charge mode, they do not charge any inventory, equipment, hotbar, or bauble slots. The inventory chargers RF also does not decrease.

### Steps to reproduce

Charge inventory chargers.
Equip in bauble slots.
Cry.

### Expected behaviour

ThEy HaD oNe JoB

### Screenshots

![Chargers](https://user-images.githubusercontent.com/77522101/182994072-ea2714d8-29a3-44ab-83df-dd34e86f317a.png)

**Comment by Raidobw2** [comment]
Odd, does it not work even after being activated with Shift + Right-Click?

**Comment by Avatarded** [comment]
Sorry for the late response, yeah I did everything. You can see they're all active because of the various graphical states they're in. Every one of them change graphical states while active and inactive to indicate their state.

**Comment by Raidobw2** [comment]
I see, thanks for the reply! I've just checked if Thermal had an update for 1.16.5 and there's many in fact. I've tested with a small instance with Curios and Thermal, and the interaction is fixed if both are on the latest version :)
So we can fix this, thanks for reporting
