### ISSUE TITLE
[Bug]: Blaze heads don't drop from Mob Masher

### ISSUE THREAD

**Issue by Neoacoya1** [FTBTeam/FTB-Modpack-Issues#1216]
### Modpack

OceanBlock

### Modpack version

1.12

### Log Files

N/A

### Describe the bug

Mob Mashers from Mob Grinding Utils do not produce Blaze heads. I had three mashers setup with +10 to decapitation on each as well as +10 looting and +10 sharpness. I went through at least 120 Blazes (produced via the Entity Spawner from the same mod) and did not receive any heads. The blaze rods, essence, and souls dropped as normal, but not a single head (items were being picked up by the Absorption Hopper from the same mod and being transferred to a Gold Chest from the Iron Chests mod). I know the setup is effective for Wither Skeletons, but for some reason it's not working on Blazes. Has anyone else experienced this or is my save file just bugged?

### Steps to reproduce

1.) Set up a Mob farm using the Entity Spawner from Mob Grinding Utils mod to produce Blazes.
2.) Kill Blazes using the Mob Masher from the Mob Grinding Utils mod. (Install 10 of the Decapitation, Sharpness, and Looting addons).
3.) See if heads drop.

### Expected behaviour

Occasionally received Blaze heads as a loot item.

**Comment by Neoacoya1** [comment]
Started a new save file on creative set it up again. Same problem. Went through 1000 Blazes and not a single head. Put Wither Skeletons in there and I walked away with 71 heads from the first 61 spawns. I think I can safely say that the drop rate is not at fault here.

**Comment by TheonlyTazz** [comment]
Please update to the latest 1.14 version,
Mobgrinding Utilities has been updated in v1.13 and if i recall correctly had fixed this issue.

**Comment by Raidobw2** [comment]
Possibly this was fixed only for 1.18.2?
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/782#issuecomment-1132261689
> Fixed in 1.18.2-0.4.38

1.16.5 does not have v0.4.38, so this is possibly not fixed / wont be fixed
![image](https://user-images.githubusercontent.com/17010632/183220897-6ba46ab6-d48b-4c35-a1ee-b7433f067cd5.png)

**Comment by Neoacoya1** [comment]
> Possibly this was fixed only for 1.18.2? [#782 (comment)](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/782#issuecomment-1132261689)
> 
> > Fixed in 1.18.2-0.4.38
> 
> 1.16.5 does not have v0.4.38, so this is possibly not fixed / wont be fixed ![image](https://user-images.githubusercontent.com/17010632/183220897-6ba46ab6-d48b-4c35-a1ee-b7433f067cd5.png)

Yeah, I guess they probably won't fix it in an older version then. Well, as long as it was fixed in the current version then I suppose it's no longer an issue. I'll just grab the items from creative to compensate until I update.

Thanks for the responses.

**Comment by Neoacoya1** [comment]
Have updated to 1.15.1.
Blaze heads are still not dropping.

**Comment by Neoacoya1** [comment]
Yeah, I thought of trying that; however, it won't update. I let the updater
run for over an hour, but it didn't advance past "Preparing."
I assume I could just delete the modpack and download the current version,
but I don't want to try in case it doesn't work.
If the issue has been fixed then it's fine. I'm just cheating to pull X
Blaze heads for X Spawns. It's an effective workaround.
