### ISSUE TITLE
[Bug]: Carry-on Mod may need to blacklist Integrated Dynamics cables

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#1217]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.8.0

### Log Files

https://pste.ch/adogaruxoj.pl

### Describe the bug

inadvertently did a carry-on pickup of an integrated dynamics cable attached at one end to the network and the other to an item exporter with card in it (but unconnected to any inventory at the moment) and immediate server crash

### Steps to reproduce

see above

### Expected behaviour

should not have been allowed to carry-on move the cable 

### Additional information

carryon-1.18.2-1.17.0.8.jar
IntegratedDynamics-1.18.2-1.11.5.jar

**Comment by GreyMario** [comment]
On behalf of the InDy guys: ...yeah, we know. This should be something CarryOn blacklists by default on principle (you have no reason to pick up network cable blocks with it) but it doesn't. While we probably _should_ do something to detect whatever this is and stop the crash, I think it's more prudent for CarryOn to hard blacklist this interaction.

...Actually, I'm surprised we don't have an issue report on this ourselves. Whatever's happening is clearly a situation we want to _not_ crash on, and it could just as well happen with mods that aren't CarryOn.

**Comment by GreyMario** [comment]
In the meantime, I'd say go ahead and blacklist anything that's a network component. Most components retain pertinent data if wrenched, anyway, so it's not like you need a special mechanism to pick up and move network pieces without destroying them.

**Comment by TheonlyTazz** [comment]
i shall just blacklist the whole mod from being picked up with carry-on as
most components retain data as you already mentioned, thanks GreyMario
