### ISSUE TITLE
[Bug]:  Thaumatorium "Ticking Block Entity" Crash after few hours after creating it

### ISSUE THREAD

**Issue by pllugger123** [FTBTeam/FTB-Modpack-Issues#1218]
### Modpack

FTB Infinity Evolved 

### Modpack version

3.1.0

### Log Files

[crash-2022-08-05_14.05.22-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9268309/crash-2022-08-05_14.05.22-server.txt)

### Describe the bug

After creating Thaumatorium, and a couple of hours of working with it, the world crashes at one moment, this is not the first time, and always as soon as I create Thaumatorium. The world is crashing with the error "Ticking block entity"

### Steps to reproduce

1. Run the build 2. create a Thaumatorium 3. Create a pair of thaum ingots with it

### Expected behaviour

the world is crumbling

**Comment by Gaz492** [comment]
You may have luck in recovering the world if you go to the config folder of the modpack, then open the forge.cfg file and setting the removeErroringTileEntities option to true.
If that doesn't work, your best bet is to restore a world backup as we are unlikely to release any bug fix updates to this modpack.
