### ISSUE TITLE
[Bug]: Crash to desktop when using mouse to add or remove upgrades from compacting drawers

### ISSUE THREAD

**Issue by PutNameHere42** [FTBTeam/FTB-Modpack-Issues#1219]
### Modpack

Direwolf 20 1.18

### Modpack version

1.8.0

### Log Files

[crash-2022-08-05_15.48.52-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9269358/crash-2022-08-05_15.48.52-client.txt)

### Describe the bug

As described in the title, the game freezes and crashes when the mouse is used to add or remove upgrades from compacting drawers. This happens regardless weather the drawer has items or not, it connected via pipes etc, or is linked to a controller. Using Shift+Click does not trigger the issue, but there's no way to remove said upgrades from existing drawers.

### Steps to reproduce

1. Place compacting drawer
2. Open upgrades inventory
3. Pick up an upgrade with the mouse cursor and click it into an empty slot. Immediate crash.
4. Also applicable with existing upgraded drawers. Simply mouse over an installed upgrade, click, immediate crash.

### Expected behaviour

No crash

### Additional information

The crash seems to revert some amount of player progress, but not block progress. For example, after reloading the world, the player position was reverted to 5~ minutes prior, but blocks placed during that time were not reverted. May be unrelated.

*Also posted to the Compact Storage issue tracker

**Comment by TheonlyTazz** [comment]
Thank you for already posting this on the Functional Storage Issue tracker, linking back here to we can keep this updated
https://github.com/Buuz135/FunctionalStorage/issues/67

**Comment by PutNameHere42** [comment]
[crash-2022-08-06_00.28.07-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9273894/crash-2022-08-06_00.28.07-client.txt)
I was actually able to replicate it. Clean install of the modpack, all default settings, nothing changed at all. Put down a compacting drawer, shift clicked in 3 diamond upgrades, shift click in one void upgrade. Click any upgrade, instant crash. Very strange that it seems hard to replicate.

**Comment by TheonlyTazz** [comment]
Fixed in v1.9.1
Upgrades are now locked once u have a void upgrade in
