### ISSUE TITLE
[Bug]: Ender Dust recipe incompatibility

### ISSUE THREAD

**Issue by Sean-1572** [FTBTeam/FTB-Modpack-Issues#122]
### Modpack

FTB Endeavour

### Modpack version

1.5.0

### Describe the bug

When grinding Ender Pearls in to ender dust in a pulveriser, the output item is called ender pearl dust which doesnt work in any of the corresponding recipes.

The ingame recipe book says that this is the way to create ender dust, but the name issue of the output is what I think is messing things up

### Steps to reproduce

1. Put an ender pearl in to a pulveriser
2. Creates ender pearl dust
3. Try to use it in a recipe to create wireless booster from applied energistics and you won't be able to

### Expected behaviour

Ender pearls to create ender dust for use in recipe

**Comment by Sunekaer** [comment]
Ill change pulverizer over to give the AE2 version of the dust
