### ISSUE TITLE
[Bug]: Game freezes and becomes unrecoverable when kicked or timed out from server

### ISSUE THREAD

**Issue by flleeppyy** [FTBTeam/FTB-Modpack-Issues#1222]
### Modpack

FTB Revelation

### Modpack version

3.6.0

### Log Files

[2022-08-05-3.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9274702/2022-08-05-3.log)

### Describe the bug

When being disconnected from the server by means of the connection timing out or something similar, the game will freeze and become "Suspended" in task manager. After hours of waiting it will not recover.

### Steps to reproduce

1. Join server
2. Play for a while
3. Some how manage to cause the server to freeze or time out, and or just kick yourself from console
4. When kicked, the game will freeze 

### Expected behaviour

Brings me to the multiplayer screen

### Screenshots

Just picture a frozen minecraft window with windows telling you that OpenJDK is not responding or something like that.

**Comment by TheonlyTazz** [comment]
Log file is empty, please provide correct logs files

**Comment by flleeppyy** [comment]
Updated

**Comment by flleeppyy** [comment]
Also the previous paste wasn't empty, you just have to wait a few minutes for the page to load it

**Comment by 5ully** [comment]
Does this happen when you use the FTB app too?

**Comment by flleeppyy** [comment]
I don't use the FTB app. It shouldn't make a difference what launcher I'm using.

**Comment by Raidobw2** [comment]
If Java becomes suspended in Task Manager, I'd check your antivirus if you have one. Acronis True Image, AVG, Avast are all that I've seen able to cause that.

A program does not get suspended randomly while actively running, unless it's managed by the system or by a 3rd party app such as antiviruses.

You got timed out from the server -- assuming other players are fine, this could come from your machine. If the server stopped for everyone else, something else is going on, let us know.

I'd double check RAM allocation as well, 6-7GB is good enough. Make sure that RAM is free. You could also remove Optifine as a test. I doubt it messes with network, but just to be safe.

**Comment by flleeppyy** [comment]
The only antivirus I have is Windows Defender. I disabled optifine, I'll see how it runs.
