### ISSUE TITLE
[Bug]: Pipez + Roost = Crash (FTB One)

### ISSUE THREAD

**Issue by AdamBundschuh** [FTBTeam/FTB-Modpack-Issues#1224]
### Modpack

FTB One

### Modpack version

1.3.0

### Log Files

First crash:
https://pste.ch/igibudoway.coffeescript

Second crash (trying to load back in):
https://pste.ch/qunefazeva.php

### Describe the bug

I placed down a line of item pipez (5 long). I wanted to place roosts along the sides of them, when I placed the first one down my game crashed. The screen froze up with an extremely weird animation, looked like my screen was minimizing in itself? Hard to explain, if I can re-create I will capture a video of it.

When loading back in after the crash, the client crashes again. Currently attempting to restore a backup so I can test more.

### Steps to reproduce

1. Place down a line of item pipez
2. Place a roost next to one of the pipez

### Expected behaviour

Not crashing

**Comment by AdamBundschuh** [comment]
Restored a backup, and tried it again, no crash. So not sure how to replicate.

Screenshot of pipez/roost setup that crashed it the first time (crash happened after placing the first roost)

![image](https://user-images.githubusercontent.com/82165558/183251952-b69833f5-d3d5-4ab3-a022-9b9dde0061f8.png)

**Comment by AdamBundschuh** [comment]
Ok, crashed again. 

https://pste.ch/adinupasiw.php

I added a second layer of roosts, put pipez between them same as bottom layer. That was fine. When I used the pipez wrench to sneak+rmb the outputs, the first 3-4 worked, then crashed.

**Comment by TheonlyTazz** [comment]
Try removing Optifine, it doesn't look compatible with this pack. If you use it for gaining FPS, try some of the alternatives at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1130#issuecomment-1191028332. If you want this fixed for Optifine, you'd need to report it to their issue tracker, since we don't support it. Let me know if that was the issue

**Comment by Raidobw2** [comment]
We're tracking this at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1098. See https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1098#issuecomment-1179818263 for some solutions and preventing that issue from happening again. In your case, adding a buffer with auto voiding (like some Storage Drawers) would likely help greatly in mitigating that crash.

Currently, the chickens mod is not updated: FTB One uses 1.0.7, and the Git repo still has version 1.0.7. So awaiting a 1.0.8 to have the fix included.

I'll shortly close this to avoid redundancy, if you are still having issues recovering the world at first let me know, I can help.

**Comment by Raidobw2** [comment]
I'll close this in favor of #1098 to avoid redundancy, thanks for reporting though!
