### ISSUE TITLE
[Suggestion]: Update JEI to latest, requires barely updating forge with it

### ISSUE THREAD

**Issue by ERBEpic** [FTBTeam/FTB-Modpack-Issues#1226]
### Modpack

FTB Sky Adventures

### Is your suggestion related to a problem? Please describe.

Currently the JEI version is missing bookmarking, so I suggest updating JEI to the latest version. Also, the latest version of JEI requires Forge 14.23.5.2816 whereas Sky Adventures is on 14.23.5.2796. From my limited testing, all the other mods seem to run the same on 14.23.5.2816 as they do on .2796.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/jei

**Comment by letmeadam** [comment]
JEI [1.12.2-4.13.1.228](https://www.curseforge.com/minecraft/mc-mods/jei/files/2643591) seems to work with the `Forge 14.23.5.2796` version in `v1.5.0` of the `FTB Sky Adventures` modpack: https://www.curseforge.com/minecraft/mc-mods/jei/files/2643591

I had been playing this modpack and missed that feature. After manually swapping the mod .jar file I can now bookmark items again, but it would be great if that was updated in the modpack itself ✨

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
