### ISSUE TITLE
[Bug]: Building Gadget ~ Preview Does Not Render

### ISSUE THREAD

**Issue by AdamBundschuh** [FTBTeam/FTB-Modpack-Issues#1228]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

When using the building gadget, there should be a ghost/preview of the blocks that will be placed.

### Steps to reproduce

Use the building gadget with any mode, no preview.

### Expected behaviour

Preview renders

**Comment by MichaelHillcox** [comment]
Disabled in BG atm. Not a bug
