### ISSUE TITLE
[Bug]: Spawn Blaze not crafting

### ISSUE THREAD

**Issue by blakewayy** [FTBTeam/FTB-Modpack-Issues#123]
### Modpack

FTB Sky Odyssey

### Modpack version

1.1.0

### Describe the bug

Spawn Blaze will not craft

### Steps to reproduce

See screenshots below for my setup - have tried inserting crafting items manually and via item conduits.

### Expected behaviour

Spawn Blaze should craft.

### Screenshots

![2021-10-12_18 32 26](https://user-images.githubusercontent.com/92360352/136913096-a7feaed7-d2a2-4b33-b19f-6d6453581c63.png)
![2021-10-12_18 41 47](https://user-images.githubusercontent.com/92360352/136913157-392e96c3-5bdc-4f57-ab3b-f9e79d7a2940.png)

**Comment by TheonlyTazz** [comment]
After looking at the scripts, i noticed that the "Spawn Blaze" Egg needs 27 (3x9) of cores. Adding any more, will break the crafting
![image](https://user-images.githubusercontent.com/3908847/184834044-0d40f610-c321-4052-8e34-3f9e36043624.png)
So this isnt actually an issue
![image](https://user-images.githubusercontent.com/3908847/184834166-24558c84-d019-423d-b1c3-b6d4a77dcda1.png)
