### ISSUE TITLE
[Bug]: Toms simple storage mod cannot craft with the REI "+" sign

### ISSUE THREAD

**Issue by 98ack** [FTBTeam/FTB-Modpack-Issues#1230]
### Modpack

FTB One

### Modpack version

1.3.0

### Log Files

[](url
[2022-08-07-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9278328/2022-08-07-1.log.gz)
)

### Describe the bug

The crafting terminal (Toms simple storage mod) won't allow me to move items to craft them out of the REI menu.  REI says, "Move items is not supported with this recipe and this container." For all crafts.

### Steps to reproduce

I hooked up a bunch of gold chests to a inventory connector then a crafting terminal.

### Expected behaviour

An error pops up when trying to move items to craft out of REI

### Screenshots

[](url
![SS](https://user-images.githubusercontent.com/110798887/183329782-ffeecba5-c326-4f70-af4e-969a3c9493bb.png)
)

**Comment by Semorphim** [comment]
Is there a config way to fix this or any compat-patch one could use quickly?
The same Error occures with the Ender-Rift Storage Solution.

**Comment by Raidobw2** [comment]
You can try updating REI, though this will probably have to be fixed within the REI mod so there wouldn't be a quick way to fix that as of now.

A workaround would be to swap REI for JEI, until REI supports Tom's Simple Storage
