### ISSUE TITLE
[Bug]: Client crash when trying to break Floating Botania flowers

### ISSUE THREAD

**Issue by Noon416** [FTBTeam/FTB-Modpack-Issues#1231]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.7.0

### Log Files

https://pastebin.com/nu6LGPpg

### Describe the bug

If you try to break any of Botania's Floating flowers with hand-tools (axe, pickaxe, sword, thermal tools, etc) or an open hand, it will crash the client immediately on the attempt to break the flower.

The choice of hand-tool used does not make a difference, nor does the choice of flower. 
It seems to crash when starts rendering the breaking graphic/overlay.

The flowers can be broken from a distance using something like an Ars Nouveau projectile break spell.
After the crash the client restarts OK. Also this does not crash a server, it is only a client-side crash.

This bug is not stated as fixed in 1.8.0.

### Steps to reproduce

Place any Botania Floating flower in the world
Try to break with any close up tool or hand
Client will immediately crash

### Expected behaviour

Attempting to break the flower should not crash the client

**Comment by TheonlyTazz** [comment]
Duplicate of #1088 https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1088
Please disable ´experimentalForgeLightPipelineEnabled´ in the meantime in
´forge-client.toml´ as that caused more issues than it did good, this has
been changed in 1.8.0 and so it is fixed
with

   - reverted ForgeLightPipeline settings 1088
   <https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1088>

**Comment by Noon416** [comment]
Sorry, I did look for other similar bugs and missed that one. All good now, thanks for the prompt response & resolution. :)
