### ISSUE TITLE
[Bug]: Using powered bedrock softlocks the game

### ISSUE THREAD

**Issue by v-tron** [FTBTeam/FTB-Modpack-Issues#1232]
### Modpack

Direwolf20 1.18

### Modpack version

1.9.0

### Describe the bug

A bug exists in cyclic regarding their powered bedrock block, this is the issue link for the Cyclic Git: 

https://github.com/Lothrazar/Cyclic/issues/2142

This bug makes the pack almost unplayable since not only teleports crash the client but also loading chunks too quickly (or loading certain chunks, not entirely sure) does. Crashes don't happen when the area you teleport into is chunkloaded (or only mekanism portals work, that could also be the case, haven't tested this extensively but I suspect the bug happens with chunk loading in general). I have also had several instances of my playerdata getting corrupted and also the chunks around the chunk where the bedrock was placed seemingly getting corrupted as well (area looks completely empty and there are invisible barriers preventing you from moving there. Blocks and entities however seem to still be there: chickens makle sounds and teleports into i.e. mekanism portals work but not a single block appears and the player can't move when stuck in the empty nothingness. 

This could only be rolled back by using backups. 

Since it was already fixed for 1.19 a fix for 1.18.2 should be straightforward as well. Maybe even as a hotfix since playerdata and chunk corruption is quite a bit more scary than simple client crashes.

### Steps to reproduce

1. Use powered bedrock
2. Try to use waystones or load chunks quickly by flying around (or load the wrong chunks, crashes seem to appear in the same areas for some weird reason).

### Expected behaviour

Client doesn't crash and player/world data doesn't get corrupted.

**Comment by v-tron** [comment]
I think this should be fixed in the latest Cyclic update: https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3946183

**Comment by v-tron** [comment]
Can we please get an update for this? It's been like a month

**Comment by v-tron** [comment]
@Raidobw2 Any chance to get an update for this? I have replaced the modpack manually to Cyclic Version 1.7.9 and it fixes the issue. Newest Cyclic Version doesn't work, probably because of a Forge Version mismatch.

**Comment by Raidobw2** [comment]
I'm currently not working on the maintenance for this pack, but I'll ask the team

**Comment by TheonlyTazz** [comment]
updated cyclic in current dev version, should be released soon
