### ISSUE TITLE
[Bug]: Tin not generating Resourceful Creepers Ore Creeper

### ISSUE THREAD

**Issue by githubuser1256** [FTBTeam/FTB-Modpack-Issues#1233]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.11 Beta

### Describe the bug

Tin does not generate Resourceful Creeper ore. The dev said it's because the config isn't setup correctly.

### Steps to reproduce

Create game. Create a mob farm. Look for a Tin creeper drops. You won't find any.

### Expected behaviour

Tin creepers should spawn

### Additional information

Feel free to contact the dev of Resourceful Creepers and CoFH.  They will tell you the same thing.

**Comment by Raidobw2** [comment]
Oversight on my part, thanks for the report, I'll add it for the next update

**Comment by Raidobw2** [comment]
Added a tin creeper in-dev
![image](https://user-images.githubusercontent.com/17010632/184270285-c3bf821b-7b6c-4d76-ba80-f37922ef2a77.png)

**Comment by Raidobw2** [comment]
Fixed in 1.2.0, thanks again for spotting that error
