### ISSUE TITLE
[Bug]:  recipe conflict  for wax and sealent

### ISSUE THREAD

**Issue by Aperson95** [FTBTeam/FTB-Modpack-Issues#1234]
### Modpack

Direwolf 20 

### Modpack version

1.8.0 / 1.9.0

### Describe the bug

i have found a recipe conflict that is not fixed in 1.9 still. I'm in 1.8 on the server i play on. its with slime ball - honey bottle. makes wax from Forbidden & arcanus  / wax and the chisels & bits / sealant

when look at the recipe for wax it shows the other way around but it seems to be a non fixed order recipe 

### Steps to reproduce

 slime ball - honey bottle in slot one and two of crafting 

### Expected behaviour

get the item that it not making due to the recipe for wax been shapeless 

### Screenshots

![image](https://user-images.githubusercontent.com/59780644/183577926-e6705152-cd12-4c88-a1a2-1684ab02de1b.png)
![image](https://user-images.githubusercontent.com/59780644/183577979-b30b5996-7871-445f-a921-5d299f2cb384.png)

![image](https://user-images.githubusercontent.com/59780644/183578328-6f81f670-3164-4f3c-acdf-e929d283b94b.png)

**Comment by TheonlyTazz** [comment]
Fixed in future version by making 2 seperate shaped recipes for both items
![image](https://user-images.githubusercontent.com/3908847/183844437-5eadb543-d713-44f3-a9f4-ea8967da3075.png)
![image](https://user-images.githubusercontent.com/3908847/183844473-5d9bc570-e301-42a3-b667-46ead3559f28.png)

**Comment by Aperson95** [comment]
thank you very much
