### ISSUE TITLE
[Bug]: Recipies for Industrial Foregoing Dissolusion Chamber turned invisible in JEI

### ISSUE THREAD

**Issue by PutNameHere42** [FTBTeam/FTB-Modpack-Issues#1236]
### Modpack

Direwolf 20 1.18

### Modpack version

1.9.0

### Describe the bug

The recipes all still exist as usual in game, but don't show up in JEI

### Steps to reproduce

1. Search for Dissolution Chamber
2. Press U
3. View Recipes

### Expected behaviour

The Recipes would visually show up in JEI

### Screenshots

![2022-08-09_09 21 58](https://user-images.githubusercontent.com/110678829/183608031-5fd00bbd-9cfc-4c03-bccc-dd149b3842cf.png)
![2022-08-09_09 21 59](https://user-images.githubusercontent.com/110678829/183608042-ee0ad721-b621-481d-9f22-73021f8d72c0.png)
![2022-08-09_09 22 30](https://user-images.githubusercontent.com/110678829/183608049-b8e1c6c3-5f67-4c59-b435-cb6ad14f80bf.png)
![2022-08-09_09 21 56](https://user-images.githubusercontent.com/110678829/183608052-142f97f4-e3f6-4cd3-bf43-bd50f42bc77a.png)

### Additional information

As seen in the screenshots, the Dissolution Chamber functions as normal, the issue seems to be solely JEI.

**Comment by Sigma-Erebus** [comment]
Don't know if it's an update on this or should be opened as a separate issue, But besides the Industrial foregoing recipes having dissapeared, so have the Create processing recipes. (Train tracks, casings, etc.)

**Comment by Sigma-Erebus** [comment]
This issue seems to be more widespread than just Industrial foregoing, I've also found Thermal Expansion suffering from it, the Magma crucible's recipes are completely empty. Surprisingly, the texture of the item being processed:
![image](https://user-images.githubusercontent.com/65902131/183736042-8f4cf89b-f81c-4f3b-b803-533d72bb849f.png)

**Comment by Sigma-Erebus** [comment]
Simply keeping this up to date with the mods which have lost their recipes, The tinker's smeltery is lacking them as well
![image](https://user-images.githubusercontent.com/65902131/183756674-fa2f9729-8135-4a08-a90d-d1e02e0b100b.png)

**Comment by TheonlyTazz** [comment]
This issue seems to be caused by the latest update of JEI.
I would suggest to downgrade JEI to `jei-1.18.2-9.7.1.232.jar` as it seems to be working there.
I will forward this to Mezz's JEI Issue Tracker
