### ISSUE TITLE
[Bug]: New Blood Magic Dungeon Dimension locks game with lag

### ISSUE THREAD

**Issue by Khaosina** [FTBTeam/FTB-Modpack-Issues#1237]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.9.0

### Log Files

Any logs I do have exceed maximum length on pste.ch, though I can't see anything in them that report any lag or anything to do with Blood Magic.

### Describe the bug

Joining Blood Magic's dungeon dimension with the new Pathway Ritual makes my single player world lag immensely and hang or crash. TheOneProbe says it's `Waiting for server...` for a while, the FTB Launcher crashes. As mentioned above, none of the logs seem to report anything unusual. Task Manager doesn't show any unusual CPU or Memory usage either.

### Steps to reproduce

1. Create Pathway to the Endless Realm ritual.
2. Enter the dimension by clicking the middle block on the pillar.
3. Encounter eternal lag on joining dimension, first room seems to have generated.
4. Force Java to close through Task Manager or wait for world crash.
5. Re-log in to world, same coordinates as before but no dungeon generated, lag is still there.
6. Cannot use commands or items to teleport out of the dimension due to lag.

### Expected behaviour

Shouldn't have lag in the dimension, game shouldn't hang

### Additional information

I went into the limited version of Demon Dungeons dimension in the previous version of the pack and mod, didn't encounter any lag and it worked just fine.
Tried to enter the dimension in a test world in the very same Instance, didn't encounter any lag issues whatsoever.

Tried my own workaround as suggested by `5ully_#6852` in the Discord server, edited my playerdata `.dat` file and `level.dat` files to be in a different dimension (overworld). I also deleted the Blood Magic dimension from the `dimensions` folder.
None of this worked.

**Comment by Khaosina** [comment]
Rolled back to 1.8.0, updated to 1.9.0 with the App. 
Got a datapack error at first, then relaunched and now it seems to work fine. Put my World into the `saves` folder, no lag at all in the Blood Magic dim now...

**Comment by IzzyIO** [comment]
Getting the same issues myself. I can't get through the first door without the game crashing.

**Comment by Raidobw2** [comment]
> I can't get through the first door without the game crashing.

Could it be possible for either of you to post that crash log found in the `crash-reports` folder? With a crash log we can forward information to the Blood Magic developers, thanks in advance

**Comment by IzzyIO** [comment]
Where does forge give crash reports? I'm having difficulty finding the folder. For me when it lags out, I have to kill the instance with the task manager, so I'm unsure if that would still generate a crash report.

**Comment by Raidobw2** [comment]
If you open the modpack folder, you'll find various folder like `config`, `mods`, `saves`. Next to all those folders is another folder called `crash-reports`. If the game crashes, that's where the logs for the crashes are.

If you cannot find a crash log in there, instead look for the `logs` folder. There, you'll find the `latest.log`. That is good too, that's the main game logs and errors can be in it just like a crash report would have them.

If you kill the instance, it won't generate a mod crash no, you are right in that aspect.

**Comment by IzzyIO** [comment]
Would it still generate something in the latest.log that would be useful if the instance is killed? Cause i can recreate the issue since the game runs fine if I'm not in the dungeon, so I've been doing other things.

**Comment by Raidobw2** [comment]
Yup, a `latest.log` is always useful to us and mod developers, even if you think there's no relevant info in it

**Comment by IzzyIO** [comment]
Okay I will recreate it, let it idle to a bit then kill it and upload the log.

**Comment by Raidobw2** [comment]
Thank you

**Comment by IzzyIO** [comment]
oddly enough, the lag to existence didn't occur. i will post it it happens tomorrow, but maybe Raidobw can post his log. My guess is it has to do the the massive generation of the dungeon.

**Comment by IzzyIO** [comment]
[2022-08-09-3.log.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9295593/2022-08-09-3.log.zip)
Here are some logs from around the time I had the issues, maybe they can be of use.

**Comment by Khaosina** [comment]
Tried to recreate the issue, it didn't crash this time but I waited a good 20 minutes after clicking `Save & Exit`, it never brought me back to the main menu nor did it crash, so I End Task'd it with Task Manager.

[latest.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9297930/latest.zip)

**Comment by IzzyIO** [comment]
Yep, just tried again and only got a few rooms in before I got stuck this time same as Khaosina mentioned. Here is my latest as well.
[latest.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9304037/latest.zip)
.

**Comment by TheonlyTazz** [comment]
It seems as if this new dungeon dimension is very prone to lag and i will disable it in update untill this gets resolved

**Comment by TheonlyTazz** [comment]
Big Thanks to R3GEN for helping me out on this one... By rolling back the Cyclic Version to 1.7.3, we managed to fix 2 big bugs in this update! 
Downgrading to Cyclic1.7.3 should fix the lag issues coming from generating the rooms

**Comment by Raidobw2** [comment]
I forgot to thanks Khaosina and IzzyIO as well for their logs! Thanks to you both for the quick information gather. Despite the logs not showing any significant information, it indicated that the issue lied somewhere else ;)

Which we found and fixed in the dev instance!
