### ISSUE TITLE
[Bug]: Server gets flooded with "Redstone input changed - updating network" massages after updating from 1.8 to 1.9

### ISSUE THREAD

**Issue by WildstyleTrinity** [FTBTeam/FTB-Modpack-Issues#1238]
### Modpack

Direwolf20 1.18

### Modpack version

1.90

### Describe the bug

The server output gets flooded with "Redstone input changed - updating network" after loading the world.
Connecting is possible and there is no obvious problem for the client.

The problem is since the server updated from 1.8 to 1.9.

### Steps to reproduce

Starting the server

### Expected behaviour

I would expect the massage to disappear after a while, but that's not the case.

### Screenshots

![Direwolf20_Server_issue](https://user-images.githubusercontent.com/110915257/183667165-bb313c88-ee50-4ecb-a9e6-df063905b38a.png)

**Comment by TheonlyTazz** [comment]
Is there anything that causes a redstone signal in your world?
Before releasing the update I made sure to test it on a server and haven't had that issue

**Comment by WildstyleTrinity** [comment]
We are a few people playing in this world for a while now. So yes, there are a lot of redstone signals in our world from various sources. 
FI: I have 3 rftools endergetic generators running with a mix of rftools transmitter/receiver and LaserIO to transmit the restone ticks needed. btw: It seems like the endergenic generators are also kinda broken. I can get it to run to a certain point before I cannot overcome a "Pearl arrived on idle" issue. Not seeing the pearl rendering in the generator makes it almost impossible to configure. :( But that's a different story.

**Comment by TheonlyTazz** [comment]
would it be possible to get a world download? i have been trying some things to replicate it but without avail, a world download would probably help pinpoint where the issue lies and can try to fix it accordingly

**Comment by WildstyleTrinity** [comment]
Sure. It's a big file (1GB) so I uploaded it to my Google Drive share:
https://drive.google.com/drive/folders/1P6AjzXjcUoAA_DrS_Uw83UOSTjaMJKZn?usp=sharing

Let me know if you need anything else. :)

**Comment by TheonlyTazz** [comment]
thanks, downloading as we speak!

**Comment by TheonlyTazz** [comment]
i have tried various things, unloading all bases, removing various redstone related items... no avail yet
and it only shows up in console, not even in the logs

**Comment by WildstyleTrinity** [comment]
So it has no effect on the game? If so, is it possible to get rid of the console massages ? The console it pretty useless if it gets spamed. :)

**Comment by TheonlyTazz** [comment]
could we possibly get the coords of the bases on this world, that way we can pinpoint where the issue lies

**Comment by TheonlyTazz** [comment]
I have found the Mod that is causing it:
https://github.com/Direwolf20-MC/LaserIO/blob/fe5a449173fbaa53dbdd9a45e23d6ac2bf54d710/src/main/java/com/direwolf20/laserio/common/blockentities/LaserNodeBE.java

I will forward this issue to LaserIO github to get this fixed

**Comment by Direwolf20-MC** [comment]
Resolved in v1.4.2 which I am releasing now - sorry about that :)

**Comment by WildstyleTrinity** [comment]
Awesome work from all of you. Thanks a lot for the quick help and solution. I will install 1.91 now. :)
