### ISSUE TITLE
Thermal Series configuration broken[Bug]: 

### ISSUE THREAD

**Issue by KeySleep** [FTBTeam/FTB-Modpack-Issues#1239]
### Modpack

FTB DW20 1.18.2

### Modpack version

1.90

### Describe the bug

The input/output configuration window for Thermal Series devices does not respond to clicks.

### Steps to reproduce

- Select any Thermal series machine and place it in the game world.
- Highlight the machine with the mouse cursor and right click to open the machine interface.
- Left click on the configuration gear icon.
- Left click on any face of the machine to try to add/remove an input.

On our server and clients there is no visible response to left clicking.

### Expected behaviour

Machine face should cycle between input, output, combination, special, and no interface.

### Additional information

Problem started after updating to 1.19 pack version.  Tested with three clients with varying rights (admin, op, player).  Server generally seems more unstable after installing the update as well.  Testing with a fresh install of 1.18 server files and clients appear to work normally.

**Comment by TheonlyTazz** [comment]
i have a feeling that this issue IS related to the JEI issues, because after i downgraded JEI to jei-1.18.2-9.7.1.232.jar i can now change the machine faces agaiN
![javaw_wacGKFqtFn](https://user-images.githubusercontent.com/3908847/183845550-f7c96add-cfac-4739-9b57-827e6c7e7635.gif)

**Comment by KeySleep** [comment]
I can confirm that rolling back JEI does fix this also.  Nice catch. :)
