### ISSUE TITLE
[Bug]: FTB Utils don't not recognize ops permissions

### ISSUE THREAD

**Issue by KeySleep** [FTBTeam/FTB-Modpack-Issues#1240]
### Modpack

FTB Direwolf 20 1.18.2

### Modpack version

1.90

### Describe the bug

After updating to the DW20 1.18.2 v1.90 patch, the FTB Utilities menus do not seem to recognize the ops level.  Changing the cheat settings appears to have no effect.  Even with cheat items enabled and the FTB icon showing a red wrench, items will not spawn in survival/adventure game modes.  

### Steps to reproduce

- Add player to Ops
- Stop server, verify player account has been added to ops list
- Restart server
- Log client in
- Enter inventory mode
- Click the FTB icon to bring up configuration menu
- Only cheats menu will show
- Enable ops spawn cheat option
- Escape and save
- Exit inventory mode and reload permissions
- Enter inventory mode again
- Control left click on the FTB wrench icon
- Icon should be red indicating spawn cheat mode is enabled
- Left click or shift left click any item in the JEI menu
- No item will spawn to inventory or the cursor

### Expected behaviour

Enabling spawn cheat for ops should allow op accounts to spawn items through the interface

### Additional information

Discovered this while trying to troubleshoot problems with Thermal interfaces.  Spawn mode does not work unless if in creative game mode.  Not a deal breaker, but annoying when trying to troubleshoot an issue.  Testing against a fresh install of the 1.18 server files and client shows the same config files and game world work correctly.

**Comment by KeySleep** [comment]
This appears resolved in 1.9.1 updates.  Thanks for looking into it.

**Comment by Raidobw2** [comment]
Alrighty, must have been to due the JEI issues, since they were fixed in 1.9.1 by reverting the JEI version. I'll close this then, I appreciate you got back to us!
