### ISSUE TITLE
[Bug]: Eternal "Loading World" when loading or creating a new world. "The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded."

### ISSUE THREAD

**Issue by Tari-Danime** [FTBTeam/FTB-Modpack-Issues#1243]
### Modpack

FTB Presents Skyfactory 3

### Modpack version

1.10.2

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9295182/latest.log)

### Describe the bug

A bug that completely prohibits world creation and world loading.

### Steps to reproduce

External Mods: JER [Just Enough Resources]

1: Open and load into FTB Presents Skyfactory 3
2: Create or load a world.

### Expected behaviour

Your game will not freeze, but will be stuck in "Loading World".

### Additional information

CurseForge Overwolf launcher is used to launch the Minecraft launcher.

**Comment by Raidobw2** [comment]
I'll assume this is an existing save that you had and no longer works. There's an issue sometimes that I believe can happen if one has a power cut or externally closes the game. A JSON file gets corrupted.

Go inside the files of the modpack and do this:

Open `config/island.json` with Notepad and paste all that code inside:
```
{
    "Tari28": {
        "playerName": "Tari28",
        "playerId": "b6b2fd45-712c-4f04-818b-2690d9a07caa",
        "islandName": "Island of Tari28",
        "posX": 64,
        "posY": 66,
        "posZ": -48
    },
    "spawn": {
        "playerName": "default_island",
        "playerId": null,
        "islandName": "spawn_island",
        "posX": 64,
        "posY": 66,
        "posZ": -48
    }
}
```

Then save the file and start your game, you should be in. Now note the coordinates of your island in XYZ and close the game.

In `config/island.json`, change your island's coordinates to what you noted. Let's say you noted (X = 200, Y = 72, Z = -2035), then you'll write this:
![image](https://user-images.githubusercontent.com/17010632/183782892-9977e98a-9296-47e7-92c1-ba3790a4c177.png)

Then save the file again.

Copy the file, paste it as is inside the `config` folder, you should end up with a second file like `island - Copy.json`. Rename that copy to `island_backup.json`.

Start your game again, and it should be fixed, this time, includes any commands to tp to your home island.

If you get this issue again, delete the original `config/island.json` file and copy-paste the copy `config/island_backup.json` in that same `config`.
Then rename the `island_backup - Copy.json` to `island.json` to use your backupped data more quickly this time around.

That's about all I can do, let me know if that worked

**Comment by Tari-Danime** [comment]
The island.json file got completely wiped. The world can now load and new world creation is possible.

Just to be clear, the islands position is based on where you spawn, or where the only dirt block was when a world is created, or something else?

**Comment by Raidobw2** [comment]
To my knowledge that should be the block of dirt where your island was first created if you used `/createislandfor Tari28` back then. If you set the coordinates right, I think they should send you back to your island (current base) with `/tptoisland Tari28`.

If your current base already was on spawn, you currently don't have to change anything in the file.

**Comment by Tari-Danime** [comment]
Alright. That fixes everything then. Only side effect is that my team was deleted, which is a little odd, but upon creating a new one, all claimed chunks are restored.

**Comment by Raidobw2** [comment]
You're welcomed, enjoy playing!
