### ISSUE TITLE
[Bug]: Thermal Recipes broken on JEI

### ISSUE THREAD

**Issue by Varsia** [FTBTeam/FTB-Modpack-Issues#1244]
### Modpack

FTB DW20 1.18

### Modpack version

1.9.0

### Describe the bug

Thermal Recipes (i.e. for the Igneous Extruder) are not showing items for recipes in JEI. In addition, for some items, looking for the recipes for items (i.e. cobblestone) the Thermal machines do not show up.

### Steps to reproduce

1. Open JEI
2. Select a thermal machine, for instance, the Igneous extruder (the machine this is most apparent on)
3. Look at uses for the machine - the item slots will be empty

### Expected behaviour

Items show up in slots for recipes

### Screenshots

![image](https://user-images.githubusercontent.com/72083529/183783167-8d5aaf16-a170-4f5f-a33f-eb7d538e50b1.png)

### Additional information

Weirdly, a couple of machines work - namely the macerator and redstone furnace. Most other machines, however, do not show recipes correctly, particularly those less used.

**Comment by Raidobw2** [comment]
Thanks for the report, however this is already reported at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1236, so I will close this issue to avoid redundancy. If you want to regain JEI, you could downgrade the modpack for now until a new update comes out
