### ISSUE TITLE
[Bug]: Carry-on wrong forbiddenTiles

### ISSUE THREAD

**Issue by JustJinxed** [FTBTeam/FTB-Modpack-Issues#1246]
### Mod

Config file issue (Carry On) - rftoolsutility:screen

### Mod version

carryon-1.18.2-1.17.0.8

### Forge / Fabric version

40.1.67

### Modpack & version

Direwolf20 1.18.2 (ver 1.8.0)

### What issue are you having?

forbiddenTiles in carryon-server.toml for the Carry On mod attempts to blacklist "rftools:screen" but the correct short name is "rftoolsutility:screen", same for the creative_screen.

(recent move maybe?)

### Crashlogs

none

### Steps to reproduce

1. Place a rftoolsutility screen and try to shift-right click it to open the UI
2. Carry On interferes

**Comment by TheonlyTazz** [comment]
Thank you for this Issue! I have fixed this indev and will push an update as soon as possible

**Comment by JustJinxed** [comment]
lol, I forgot to put in a topic on this one, thanks Tazz! you're awesome.
