### ISSUE TITLE
[Feature Request]: gravestone mod is highly inefficient with curiosAPI 

### ISSUE THREAD

**Issue by JustJinxed** [FTBTeam/FTB-Modpack-Issues#1247]
### Mod

Direwolf20 1.18.2 (ver 1.8.0)

### Description

Current gravestone mod we use in the pack will not re-equip curios. Upon asking for a enhancement req to consider adding curio support, henkelmax is unwilling due to the extra work the toolchain would cause (https://github.com/henkelmax/gravestone/issues/37). Can we maybe consider switching to [enigmaticgraves](https://www.curseforge.com/minecraft/mc-mods/enigmatic-graves)? 

Current mod solution has us having to re-equip all our curios every time we die when we retrieve our grave.

### Describe the solution you'd like

A switch to enigmaticgraves, which provides the same functionality AND curio support so people don't have to re-equip all their curios every time they die. 

### Describe alternatives you've considered

Three separate attempts have been made asking henkelmax to incorporate curio support. Pretty sure they're not going to budge given how the mod is meant to be cross accessible to as many modpacks as possible, and henkelmax doesn't want the extra headaches that come with updating external API reference changes. 

https://github.com/henkelmax/gravestone/issues/37
https://github.com/henkelmax/gravestone/issues/62
https://github.com/henkelmax/gravestone/issues/95

**Comment by TheonlyTazz** [comment]
Thank you for your suggestion of replacing Gravestone mod with Enigmaticgraves.

We do understand the reasoning, but we cannot switch mods like this with a pack update. This would break all existing graves and people will lose their items.

We will however take this in consideration for future modpacks!
