### ISSUE TITLE
[Bug]: Crash in IntegratedCrafting while editing Recipe in JEI

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#1248]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.9.0

### Log Files

https://pste.ch/alisacetun.pl
https://pste.ch/oweruhuruw.pl

### Describe the bug

trying to create a recipe card in the Logic Programmer, to put in the crafting interface of IntegratedCrafting, and there seem to be multiple ways to crash the game while trying to preview a recipe in JEI with the portable logic programmer open and set to accept a new recipe 

### Steps to reproduce

1. open logic programmer. 
2. click Recipe to set it up to accept a new recipe from jei or dragging items to it
3. search in JEI for the item you want to add to a Recipe variable card
4. click the item in JEI so you can preview its ingredients before adding it to the logic programmer so the card can be programmed with it
5. Boom. and apparently a Repeatable Boom.

### Expected behaviour

allowed to preview the recipe in JEI before clicking the [+] to add it to the logic programmer

### Screenshots

clicking this recipe will immediately crash the game
![2022-08-10_07 34 49](https://user-images.githubusercontent.com/1612570/183891496-67afe8b8-939b-48c3-b787-8cf5b9641b4d.png)
pressing 'u' to see the Uses of this ingot also immediately crashes the game
![2022-08-10_07 35 00](https://user-images.githubusercontent.com/1612570/183891561-589601ad-f8a0-4426-8ebf-acfa81700780.png)

### Additional information

apparently, it also crashes if you are in the logic programmer about to add a recipe, and hovering an item in your inventory and pressing 'u' to see the uses of it because you've forgotten the recipe you'd intended on adding what with all the crashes. ಠ_ಠ

Oh yes, definitely repeatable.

but for both of the above screenshots, this crash ONLY occurs while within the Logic Programmer ( specifically the Recipe pane; i honestly haven't tested other panes because its early, I'm cranky, and woke up to the new update only to immediately find a crashworthy bug. yay, me. )

**Comment by WebDragon** [comment]
for reference the JEI version is 

- jei-1.18.2-forge-10.1.3.240

and the IntegratedMods versions are 

- IntegratedCrafting-1.18.2-1.0.23
- IntegratedDynamics-1.18.2-1.11.7
- IntegratedTerminals-1.18.2-1.3.0
- IntegratedTunnels-1.18.2-1.8.13

**Comment by TheonlyTazz** [comment]
Thanks alot! i managed to replicate this issue with just the Mods you stated, and posted this issue on the IntegratedDynamics issue tracker.
Lets hope it gets resolved quickly

**Comment by met4000** [comment]
(I'm coming from a discussion on the InDy discord server)

InDy seems to rely on features (in this case `mezz.jei.api.gui.IRecipeLayout.getFluidStacks()`) from v9 that are removed in JEI v10 - see https://github.com/mezz/JustEnoughItems/commit/530ef6c8d604370bef850f3656a28beab56cbfba

Since there doesn't seem to be a beta or release version for JIE v10 in 1.18 on curseforge yet, I'm wondering if downgrading to the latest JEI release (v9.7.1.232, according to curseforge) would temporarily fix this until there's an official v10 release and mods like InDy update to the v10 API?

**Comment by TheonlyTazz** [comment]
this issue doesnt occurs on `jei-1.18.2-9.7.1.232.jar` - i just tested it on the instance with just jei and InDy, i'll be testing it on the Direwolf20 instance to be sure

**Comment by TheonlyTazz** [comment]
I am going to get a Hotfix out asap to rollback the jei version, as it also breaks various recipes viewing on servers

**Comment by v-tron** [comment]
Was about to report this, glad it has already been resolved
