### ISSUE TITLE
[Bug]: Mining turtle go missing 

### ISSUE THREAD

**Issue by lazycooken** [FTBTeam/FTB-Modpack-Issues#1249]
### Modpack

direwold20 

### Modpack version

1.8

### Describe the bug

Mining turtle will disappear

### Steps to reproduce

Place chest and turtle
label turtle
refuel turtle
run Quarry plugin
let run
after some time while turtle will not reappear. 

### Expected behaviour

not to disappear

### Additional information

was using Variable Size Quarry code 
[http://pastebin.com/rpXRAZs4](https://pastebin.com/rpXRAZs4)

**Comment by Raidobw2** [comment]
Hi, would you happen to have a world download? I can run a search in the blocks and check out if the Turtle is not hiding somewhere. If I can't find it, that could be a mod issue

If you also have approximate coordinates of your quarry, that will help as well, thanks in advance

**Comment by TheonlyTazz** [comment]
have tried to replicate this issue without any luck, using the various scripts, but turtle never despawned.
Issue got stale, going to close, feel free to reopen if issue does persist
