### ISSUE TITLE
[Bug]: Create recipe for Andesite Casing invalid

### ISSUE THREAD

**Issue by patryn2180** [FTBTeam/FTB-Modpack-Issues#1250]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.18

### Describe the bug

MOD Create: recipe for Andesite Casing only offers Deployer recipe.  But you need an andesite casing to create a deployer....Even reviewed Dires videos and tried the recipe he used in normal crafting grid.  Does not work. 
For reference:
Plank | Plank | Plank
Ande | Log   | Ande
Plank | Plank | Plank

### Steps to reproduce

review recipe for andesite casing
see only deployer recipe available
try earlier version recipe anyways
does not work

### Expected behaviour

expect to be able to create my first andesite casing without using a machine that requires an andesite casing

**Comment by quietust** [comment]
There are *two* recipes for the Andesite Casing - one involves using a Deployer, and the other involves right-clicking an Andesite Alloy on any Stripped Log.

**Comment by TheonlyTazz** [comment]
as quietust pointed out, you now make your first andesite casings manually bz using andesite alloy on stripped logs/wood

this has also been confirmed on the Createmod Issue tracker, therefor im not going to change it as it is intented
https://github.com/Creators-of-Create/Create/issues/3422
