### ISSUE TITLE
[Bug]:  World not loading since 1.9.0

### ISSUE THREAD

**Issue by SAMDIMAS123** [FTBTeam/FTB-Modpack-Issues#1251]
### Modpack

direwolf20 1.18

### Modpack version

1.9.0

### Describe the bug

my save game/world is not loading in, when i click to play my world the world does not load it gets stuck on a black screen where i only can see my hot bar or when i load in the chunks does not load and when i move of the chunk i fall of the chunk border and fall into the void

### Steps to reproduce

continue the world

### Expected behaviour

well what i expected is just to load in and continue

### Screenshots

![Uploading 20220810_214323.jpg…]()

**Comment by TheonlyTazz** [comment]
Thank you for your Issue.
Without the uploaded screenshot, or any logs, it will be hard for us to figure out what is actually causing this issue, could you perhaps provide additional information for us.

**Comment by Raidobw2** [comment]
I suggest waiting for the incoming hotfix, there seems to be a major bug with Cyclic in 1.9.0, which Tazz is currently fixing.

If you want to try one step ahead of time, remove Cyclic from the `mods` folder in your modpack instance and add this one instead: https://www.curseforge.com/minecraft/mc-mods/cyclic/files/3882353

If that fixes it make sure to close this issue! We've got 4 of them linked to the Cyclic update already somehow :P

**Comment by SAMDIMAS123** [comment]
but if i remove cyclic wil the mod be automatically be added if the hotfix
is out or do i have to add it myself?

**Comment by TheonlyTazz** [comment]
Use cyclic 1.9.3 in the meantime, that should work

**Comment by SAMDIMAS123** [comment]
but when i select witch version it says latest is 1.18.2-1.7.6 is latest
not 1.9?

[image: width=]
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by TheonlyTazz** [comment]
Sorry, j ment 1.7.3 not 1.9.3 (on phone)

**Comment by Raidobw2** [comment]
Hotfix 1.9.1 should now be available now on the FTB App, if you update this problem should be fixed and the Cyclic mod will be automatically set to the right version
Cheers :)
