### ISSUE TITLE
[Bug]: DireWolf20 1.18 1.9.0 server starts and then immediately crashes

### ISSUE THREAD

**Issue by JakeMoe** [FTBTeam/FTB-Modpack-Issues#1253]
### Modpack

DireWolf20 1.18

### Modpack version

1.9.0

### Log Files

[crash-2022-08-10_20.44.20-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9303954/crash-2022-08-10_20.44.20-server.txt)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9303957/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9303958/latest.log)

### Describe the bug

After upgrade from 1.8.0 to 1.9.0, my server loads and I can briefly see it's available in the client, but then crashes very shortly after finishing startup.  If I'm reading correctly, it looks like the Industrial Foregoing fisher is trying to get a loot table for Blood Magic and that's what's crashing?  Crash, latest, and debug logs attached.

I have a second, more recently started DW20-1.18 server which doesn't have this issue, but I haven't started Blood Magic or Industrial Foregoing yet on that one, so I presume that's why it's not having the issue.

### Steps to reproduce

1. Start server
2. Watch server finish preparing spawn and get to prompt
3. Watch server crash

### Expected behaviour

Not to crash  :-)

**Comment by Chocorean** [comment]
I just had to start the instance again and it worked here

**Comment by JakeMoe** [comment]
I had the issue just after I upgraded (which was shortly after it was released a day or two ago).  I restarted a few times with the same result.  I updated and restarted my Ubuntu server this morning and then tried launching the server to get the details for this ticket, and it's still happening.

**Comment by TheonlyTazz** [comment]
This is related to Bloodmagic breaking the fishing loottable, which is resolved by updating BloodMagic.
We will provide an update/hotfix to Direwolf20 soon to fix this aswell
