### ISSUE TITLE
[Bug]: DireWolf20 1.18 1.8.0 server issues with JEI

### ISSUE THREAD

**Issue by JakeMoe** [FTBTeam/FTB-Modpack-Issues#1254]
### Modpack

DireWolf20 1.18

### Modpack version

1.9.0

### Describe the bug

On a separate (newer) server to my other ticket, I'm having two issues with JEI:

1. I cannot configure the client settings; only server shows up when I click the wrench that says "JEI Config" while in JEI
2. Sometimes the little "+" symbol for "Move Items" to insert ingredients into the Tinkers' crafting station doesn't work. It doesn't seem to happen for vanilla crafting in the player's inventory or a crafting table.  Tried with and without adjacent inventories, and happened with both (I've had issues in the past with it not appearing when an inventory was adjacent, but that doesn't make a difference now).

Not sure what logs or screenshots would be useful for this; if you need any, please let me know.

### Steps to reproduce

1. Open JEI
2. Open settings
3. See only Server settings appear, Client is missing.

1. Open Tinkers' Crafting Station
2. Search for item to craft in JEI
3. Select item to see recipe
4. See no "+" sign next to the recipe for "Move Items"

### Expected behaviour

Be able to access setting and the Move Items button

**Comment by TheonlyTazz** [comment]
Downgrade the JEI to a v9 release Version, latest V10 version of JEI breaks
alot of things, this had slipped past me and will be fixed soon

Jake Moe ***@***.***> schrieb am Mi., 10. Aug. 2022, 23:07:

**Comment by JakeMoe** [comment]
All good, I can live with it temporarily, especially if it's going to "be fixed soon"  ;-)  I presume you mean fixed in the pack soon?  And actually fixed, or reverted?

**Comment by Raidobw2** [comment]
JEI's version will be reverted

**Comment by JakeMoe** [comment]
Cheers for that, one last question, any idea how soon an update will be out?  I'd hope within a few days?

**Comment by Raidobw2** [comment]
I don't have an ETA since I'm not affected to it as of now, but Tazz has been working on it today. We found and fixed some issues mostly by reverting some mods which had problems. It's going to be a hotfix and since he's working on it already, I'd say very soon, especially since we know JEI is essential for modded

**Comment by JakeMoe** [comment]
Cheers mate, looking forward to it  :-)
