### ISSUE TITLE
[Bug]: MPS Suit using energy from devices in hotbar instead of own Energy supply

### ISSUE THREAD

**Issue by EinMannimInternet** [FTBTeam/FTB-Modpack-Issues#1256]
### Modpack

FTB Ultimate: Anniversary Edition

### Modpack version

1.3.0

### Describe the bug

Hello there, me again about an MPS issue.

So anytime my Powersuit uses energy for ANY module, instead of using the actual energy of the suits dedicated battery, it will use energy from ANY electrical device I hold in my hotbar.
Example: I use the wireless access device from Ref.Storage, which has a very small energy charge compared to the MPS battery capacities. Whenever I start flying, falling, or leave my magnet or flight control on, it will empty the wireless device's energy before using the suits own energy. It also does this for the powertool. Whenever I hold it or use it whilst flying its energy goes down a lot faster, only its not as noticeable because of the very high battery capacity.

This is a very tedious issue, since my most used devices are constantly drained and I have to recharge them all the time. I also cant use important devices like the wireless access in midair, since they are drained immediatley.

I have grown somewhat used to this, since I can bypass the problem a little by charging stuff up with the MPS energy generators (kinetic, solar etc), but it still gets incredibly annoying after a while, especially during Inventory management.

### Steps to reproduce

equip MPS Armor, install any battery

install any module that uses power

hold any energy storage in hand, like powertool, battery, wireless access etc

use energy consuming module from the suit

notice; suit battery stays at 100%, energy of device in hand is drained first.

### Expected behaviour

Suit using its own energy storage instead of others

### Additional information

I had this issue even before I updated the MPS portion of the modpack, but just for clarity, I updated MPS (2.2.30), Numina (2.2.30), Refined Storage (1.9.18) and deleted a block of text in the files (Issue #544), so that the mods and recipes would actually work in the pack (Issue #1145).

When searching for this issue before writing this post, I could only find very old threads but no similar issues (perhaps i suck at googling?)

I was helped out quickly by a nice person the last time I posted here, and I would very greatly apprecciate it happening again :)

**Comment by Raidobw2** [comment]
Seems to happen only if Refined Storage is installed, I think earlier I saw that MPS has some extra integration with it, I'll investigate a bit more

**Comment by Raidobw2** [comment]
I've made a report to MPS ^ since that looks to be an issue with the Refined Storage integration.

The only workarounds as of now is to uninstall Refined Storage (which isn't really a solution when it's the only storage mod in FTBU AE)

Or, to not hold energy items in your main hand while doing actions.

I think Refined Storage can also open the terminal/grid from a keybind. Check your keybinds, that might do it. Then you could just leave the terminal somewhere in your inventory and use the keybind to open it instead, that might work.

**Comment by EinMannimInternet** [comment]
Yeah I got all my stuff on the Refined Storage Network so uninstalling is no option :P 
Well I guess I'll survive this no worries, the keybinds do help a little.

Thanks for the quick reply anyways, have a a nice day!

**Comment by Raidobw2** [comment]
Modular Powersuits build 31 came out a few hours ago and fixes this! (you need the updated Numina and Refined Storage)
