### ISSUE TITLE
[Suggestion]: Add JER and JER Integrations

### ISSUE THREAD

**Issue by PutNameHere42** [FTBTeam/FTB-Modpack-Issues#1258]
### Modpack

Direwolf 20 1.18

### Is your suggestion related to a problem? Please describe.

In the Direwolf20 1.18 pack it can often be difficult to know where exactly to find certain items, Nickel ore for example, or sponges. By adding JER and JER Integrations the player would be able to see at what Y level any ore is found most often, and other useful data such as what mobs, if any, drop a specific item, sponges dropping from Elder Guardians for example. I feel like this would be painless to add to the pack and provide a ton of useful information to any players weather they be in the Early or Late game.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer
This mod adds information about mob drops, plant drops, and dungeon loot, with percentage chance indicators and extra info such as loot obtained from player kills or looting. It also displays very easy to understand graphs of any ore distribution, very clearly letting the player know at what Y level they should mine to get, for example, Nickel ore. 
https://www.curseforge.com/minecraft/mc-mods/jer-integration
Adds further compatibility and loot tables to JER, enhancing its results and covering more mods.

**Comment by TheonlyTazz** [comment]
Added in the latest version
