### ISSUE TITLE
[Bug]:  Traveling and forcing world gen crashing game

### ISSUE THREAD

**Issue by Jrotica** [FTBTeam/FTB-Modpack-Issues#1259]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.9.0

### Describe the bug

When I fly around my world and get too far from my base the game stops generating the world. My game freezes saying waiting for server. I have to end task in task manager and go back into it to continue playing. I have had to restore from back up twice.

### Steps to reproduce

1. Go fast away from normal area
2. Break game

### Expected behaviour

Go far from base

### Additional information

Downgraded cyclic to Cyclic-1.18.2-1.7.3 and can't reproduce issue.

**Comment by Raidobw2** [comment]
Please update to the 1.9.1 hotfix and that should normally be resolved. If it is, feel free to close this support ticket!
