### ISSUE TITLE
[Bug]: Lag

### ISSUE THREAD

**Issue by 98ack** [FTBTeam/FTB-Modpack-Issues#1260]
### Modpack

FTB One

### Modpack version

1.30

### Log Files

[2022-08-11-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9313761/2022-08-11-1.log.gz)

### Describe the bug

Major server lag with toms storage: Inventory Connector and Item pipe.  As soon as a connect the pipe and make it pull from the storage connector I get some major lag on the server.

### Steps to reproduce

Connect a bunch of full chests to the inventory chest and try and pull a decent amount of items out of it with the item pipe.  Then add machines that are going to be requiring items and hook up a few.  The more you add the more lag you get.

### Expected behaviour

The tick rate will be about 10x in my case

### Screenshots

![image](https://user-images.githubusercontent.com/110798887/184288160-edb0e036-7dac-40e9-a7ea-35abcc27078a.png)

**Comment by Raidobw2** [comment]
Would you be able to obtain a spark report with `/spark profiler`? You can wait around 30 seconds while there is lag and use `/spark profiler --stop` to stop the profiler and put the link here. Thanks!

**Comment by 98ack** [comment]
https://spark.lucko.me/26PexTrAQz

**Comment by Raidobw2** [comment]
Hmm. The spark report shows very good information and it's super clear the pipes are causing lag. Would you be able to give us a copy of your world? I'd like to go see how many chests are connected, the filters, etc. so I can give better information to the mod author for optimizations

**Comment by Saereth** [comment]
this issue should now be resolved in the 2.0 update out soon
