### ISSUE TITLE
[Bug]: Annihilation plane permanently breaks bedrock ores

### ISSUE THREAD

**Issue by BibiFloris** [FTBTeam/FTB-Modpack-Issues#1261]
### Modpack

Plexiglass mountain

### Modpack version

1.1.1

### Describe the bug

Applied energistics 2 Annihilation plane permanently breaks bedrock ores.
Leaving a gap in the bedrock layer to the void

### Steps to reproduce

Find bedrock ore
Set up small network
Place plane
Ore is gone

### Expected behaviour

The block isn't broken. Optionall the resoucres enter the system

**Comment by Raidobw2** [comment]
I should have this fixed in-dev, though I think the annihilation plane doesn't drop materials. The bedrock ore isn't broken though!

Bedrock ores had a major compat patch and most block breaking things now work properly, which the exception of the plane not dropping materials

**Comment by Raidobw2** [comment]
I had to revert Bedrock Ores in the 1.2.0 that should be released today. I will check more about this issue for 1.3.0 and report to the mod author most likely

**Comment by Raidobw2** [comment]
Note: The RFTools builder should work well, try that one!

**Comment by Raidobw2** [comment]
I've got this fixed properly in 1.2.1. Integration between Bedrock Ores and the Annihilation Plane is not fully done yet, so I'll make a suggestion to the Bedrock Ores author.

I'll mark this as fixed for now since the block is no longer destroyed:
![image](https://user-images.githubusercontent.com/17010632/198970557-bc3f8ad3-e407-4c7c-b547-27591449d0af.png)

**Comment by Raidobw2** [comment]
I've suggested it to the Bedrock Ores author above ^

I will follow up with them if they had planned to fix it (if they can, since it's AE2 that's breaking the block) and potentially add the fixed interaction to the modpack later on

**Comment by Raidobw2** [comment]
Fixed the first part in the 1.2.1 update. For it not getting the blocks I've forwarded that to AE2, but it's out of my control currently, so I'll mark this as resolved for now
