### ISSUE TITLE
[Suggestion]: Add these 2 AE2 add-ons

### ISSUE THREAD

**Issue by BibiFloris** [FTBTeam/FTB-Modpack-Issues#1262]
### Modpack

Plexiglass mountain

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/lazierae2 :
A bunch of machines to automate AE2 crafting steps and
Specially the ME Requester is a block that makes working with an AE system a lot nice

https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics :
Allowing gasses into the AE2 network makes working and automating Mekanism a lot easier and more fun

**Comment by Raidobw2** [comment]
I've added Applied Mekanistics and XNet gases, but will not be adding LazierAE2.

My reason for not adding LazierAE2 is because channels are currently disabled, so I'd prefer if the player learned automating normal AE2 correctly in this pack. Using the rotation on Inscriber makes this a lot easier

**Comment by Raidobw2** [comment]
Applied Mekanistics is in 1.2.0!
