### ISSUE TITLE
[Bug]: Ghast disappearing shorter range but still attacking.

### ISSUE THREAD

**Issue by benten2000** [FTBTeam/FTB-Modpack-Issues#1263]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.9.1

### Describe the bug

When in the Nether Ghasts will disappear at a shorter range than vanilla, but when invisible they can still attack you and only reappear when they come back into the shorter range of the player.

### Steps to reproduce

1. Go to Nether
2. Spawn or find a Ghast (go around 45 blocks away and should disappear)

### Expected behaviour

Vanilla the Ghasts should stay visible even past 64 blocks and fade way wihen the world fades

### Additional information

After testing I found the mod causing it is ItShallNotTick-1.0.20-build.21.jar.
With it disabled the Ghast goes back to vanilla settings.

The config for it (itshallnottick-common.toml) has other mobs (wither, dragon, etc) on the ignore list so they behave normally so I'm unsure if the Ghast is meant to be like this on the pack otherwise it should be added to the ignore list to make its behaviour normal again.

**Comment by PutNameHere42** [comment]
I've also had this happen and its very annoying in some of the Incendium biomes where you have like 5 invisible ghasts shooting at you at once. Also seen in Dire's playthrough.

**Comment by TheonlyTazz** [comment]
this is weird behaviour tho, Itshallnottick should only be turned on when there are 2 or more players online.
Seeing how this has happened on Dire's playthrough aswell, makes me believe thats definetly unintended.
For now i will add the Ghasts to the ignorelist and will contact the devs about this
