### ISSUE TITLE
[Bug]: When you die it shows you lose all of your coins.

### ISSUE THREAD

**Issue by Fireball5939** [FTBTeam/FTB-Modpack-Issues#1266]
### Modpack

FTB Sky Odyssey

### Modpack version

1.3.0

### Describe the bug

When you die from any source in Sky Odyssey your coins get set to 0 until you reload the world.

### Steps to reproduce

1. Die from any source
2. Your coin count is set to 0
3. Leave the world.
4. Rejoin the world and now your coin count is back where it was.

### Expected behaviour

I expected for the coins to stay the same before death.

### Screenshots

![2022-08-13_12 37 13](https://user-images.githubusercontent.com/111195856/184504903-8bc2c748-4d52-48e9-99a3-8d47050fadc2.png)
![2022-08-13_12 37 42](https://user-images.githubusercontent.com/111195856/184504904-28f2fe61-7d41-4455-9c0a-2cf9673f701e.png)
![2022-08-13_12 38 02](https://user-images.githubusercontent.com/111195856/184504905-b1d22619-795b-44ad-b1e1-7b247d8717d1.png)
![2022-08-13_12 38 15](https://user-images.githubusercontent.com/111195856/184504906-42c12cd4-da9c-4ea2-8507-b31196f9ba98.png)
![2022-08-13_12 38 57](https://user-images.githubusercontent.com/111195856/184504907-c053d72c-5ce9-4625-b2b4-76acff05936f.png)
![2022-08-13_12 39 12](https://user-images.githubusercontent.com/111195856/184504909-27e435ee-8564-4bba-ac73-be96ab4e00b5.png)

**Comment by TheonlyTazz** [comment]
seeing how this is just a small visual issue, i will be closing this. the FTB Money mod is due for a complete rewrite and im afraid thats not something thats happening anytime soon
