### ISSUE TITLE
[Bug]: Inventory Cable Connector (Flitered) problem

### ISSUE THREAD

**Issue by EnriqueHayao** [FTBTeam/FTB-Modpack-Issues#1267]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

It make Inventory Connector detected a lot of slots that much more than it should be (one Obsidian Chest was be detected thousands of slots). It make the server lag even crash.

### Steps to reproduce

1.Connect Inventory Cable Connector (Flitered) to about 5 or more Obsidian Chests
2.Right click the Inventory Connector of the inventory system

### Expected behaviour

The server lag even crash

**Comment by Raidobw2** [comment]
This will be tracked at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1278. I'm also making a report to the mod author
