### ISSUE TITLE
[Bug]: Direwolf20 fails to download

### ISSUE THREAD

**Issue by colk** [FTBTeam/FTB-Modpack-Issues#1268]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.9.1

### Log Files

[FTB-DBGSULUSERUKI](https://pste.ch/ugavipimam)

### Describe the bug

I am attempting to download Direwolf20 1.18 1.9.1 pack and its failing to download most of the mod files needed it looks like it is failing to find the files needed

java.io.FileNotFoundException: File does not exist at URL. is repeated several times. 

If you download the server pack of the same mod it works fine so I did that and copied the mod files over to the client folder and its working fine

### Steps to reproduce

1. Open FTB app
2. Browse for the Direwolf20 pack
3. Download the 1.9.1 pack

### Expected behaviour

I expect the mod files to get downloaded by the FTB App

**Comment by Raidobw2** [comment]
Can you try reinstalling the FTB App from the website? https://www.feed-the-beast.com/app
Your current app is running a preview version from 2021 which is far far back `202105051826-09e11cc010-preview`

The latest one was actually released yesterday in fact, but there were also many other release builds after the preview version
![image](https://user-images.githubusercontent.com/17010632/184562992-2ca12980-bab3-4bf4-ad29-a4e3a962da51.png)

You can see that info in the FTB App Settings at the left (after you reinstalled)

**Comment by colk** [comment]
So with the newest launcher from the website it gets stuck my new FTB code is FTB-DBGCITICOWUDA

**Comment by Raidobw2** [comment]
Oh, now it looks like you got it downloaded correctly. The only thing I see is that apparently Minecraft is running out of memory?
It's saying this: `Minecraft exited with status code: 137`, which means it ran out of memory.

Closed all programs you don't need to play Minecraft, and try to give it more RAM. In the FTB App you can click the DW20 1.18 modpack tile to get into the Overview page. From there click Settings, and there will be a slider for you to adjust the RAM. I recommend no less than 6GB for this modpack, and high maximum as 8GB.

Try that and let me know if it loaded all the way to the main menu!

**Comment by colk** [comment]
Its set to 8GB already java seems to be ignoring it I only see it take up 4-5 GB of Ram which Java should I be using for this the one built into FTB or a custom one? This is the one I have installed on the machine. I have passed arguments and used the slider and java never wants to seem to use more than 4 GB I am reinstalling the pack to see if that helps

**Comment by Raidobw2** [comment]
Hmm. Can you try pressing play on the FTB App, which will load the modpack. Once the modpack begins loading, count about 5 seconds, then close the FTB App through the top of the window.

The modpack should still load in the background, you can see it in Activity Monitor.

After a maximum of 5 to 7 minutes, check if the modpack opened and the main menu window appeared.

If the modpack opened, that might be the same error as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/721, and I'll relay more information to the devs and close this ticket to avoid redundancy.

Let me know if that worked and thanks

**Comment by colk** [comment]
I tried that and once the Java application popped up in the task bar I closed FTB and it made it to the main menu. Here is my latest logs FTB-DBGALENOMAGIN if they help in anyway

**Comment by Raidobw2** [comment]
I see. Glad that it worked :) I think that's the only workaround for now. I'll pass the latest debug code to the app developers and I'll close this issue since it's fixed for now. The rest the app devs will handle it. Thanks for your help and have fun playing!
