### ISSUE TITLE
[Bug]: Chalk generates Stone with a NBT tag in dungeon loot

### ISSUE THREAD

**Issue by faanlez** [FTBTeam/FTB-Modpack-Issues#1269]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.9.1

### Describe the bug

The recent Chalk update added Chalk Boxes and they sometimes generate in dungeon loot but looks like one of those is broken somehow and becomes Stone with the Chalk Box NBT added to it. The loot has other Chalk Boxes working correctly.

### Steps to reproduce

1. Generate dungeon loot with `/setblock ~ ~ ~ minecraft:chest{LootTable:"chests/simple_dungeon"}`
2. Open the chest and look for a Stone block
3. That Stone block has the mentioned NBT tag

### Expected behaviour

The Stone block should be a Chalk Box.

### Additional information

The full NBT tag:
`tag: {Items: [{id: "minecraft:air", Count: 1b}, {id: "chalk:light_gray_chalk", Count: 1b, tag: {Damage: 0}}, {id: "minecraft:air", Count: 1b}, {id: "minecraft:air", Count: 1b}, {id: "minecraft:air", Count: 1b}, {id: "minecraft:air", Count: 1b}, {id: "minecraft:air", Count: 1b}, {id: "chalk:green_chalk", Count: 1b, tag: {Damage: 0}}, {id: "minecraft:air", Count: 1b}]}`

**Comment by TheonlyTazz** [comment]
correct, after checking the loottables of dungeon_chalk_loot.json i found
I forwarded it to the Issue tracker of Chalk and hope for a fix soon

```js
        {
          "type": "minecraft:item",
          "weight": 2,
          "name": "minecraft:stone",
          "functions": [
            {
              "function": "minecraft:set_nbt",
              "tag": "{Items: [{id: \"minecraft:air\", Count: 1b}, {id: \"chalk:light_gray_chalk\", Count: 1b, tag: {Damage: 0}}, {id: \"minecraft:air\", Count: 1b}, {id: \"minecraft:air\", Count: 1b}, {id: \"minecraft:air\", Count: 1b}, {id: \"minecraft:air\", Count: 1b}, {id: \"minecraft:air\", Count: 1b}, {id: \"chalk:green_chalk\", Count: 1b, tag: {Damage: 0}}, {id: \"minecraft:air\", Count: 1b}]}\n"
            }
          ]
        },```

**Comment by TheonlyTazz** [comment]
I have temporarily fixed this by modifiying the loot drops and imported them via KubeJS, this fix is already in the latest update
