### ISSUE TITLE
[Bug]: Black screen except when I open my inventory.

### ISSUE THREAD

**Issue by bigphil45** [FTBTeam/FTB-Modpack-Issues#1270]
### Modpack

Skyfactory 2.5

### Modpack version

2.5.8

### Log Files

I'm not sure how to access this. I see the "log" in the FTB launcher but I can't copy it.

### Describe the bug

I load into the world and the screen is completely black. The only time it is not black is when I open my inventory. I'm pretty sure I can still move and break stuff, it's just that I'm unable to see.

### Steps to reproduce

1. Load modpack
2. Load up a world

### Expected behaviour

I expected the screen to not be black

### Screenshots

<img width="1270" alt="Screenshot 2022-08-15 091716" src="https://user-images.githubusercontent.com/111289340/184642615-d16f3366-a322-473f-b96a-37a3f1a2797f.png">
<img width="1280" alt="Screenshot 2022-08-15 091931" src="https://user-images.githubusercontent.com/111289340/184642819-adc9c93f-a056-484e-aedc-e263e6add952.png">

### Additional information

I've looked up countless tutorials and looked at different fixes but cannot find anything. My driver is updated, I've selected 2gb, 4gb, 6gb, and 8gb of ram and the issue is present throughout. I have no resource pack on, this has also been an issue in the FTB Infinity Evolved modpack. I am perfectly able to use other mod websites for example, the void launcher but FTB has so many better modpacks so I would like to fix this issue.

**Comment by Raidobw2** [comment]
Can you load up the game, then fire up the Task Manager. Look which GPU the game is using and let me know. If your computer has a graphics card like Nvidia or AMD Radeon, then let me know as well so I can point you to the solution. I think this might be an issue with which GPU your computer is using. If your computer is a laptop, this could be even more the case since they usually have an integrated GPU and a dedicated GPU, both on.

**Comment by bigphil45** [comment]
I am on a laptop and I have the intel iris xe graphics.

**Comment by Raidobw2** [comment]
Hmm. Is this the only graphics that show up in Task Manager?

A user had a similar issue in FTB Infinity Evolved at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/749 and they apparently fixed it by updating the drivers. I know you said yours is up to date, but just in case, those drivers are obtained directly from the Intel site.

Also, does this happen in vanilla Minecraft in 1.7.10, without mods?

**Comment by RaycePenguin1** [comment]
Hey! im the user that had the problem in infinity evolved, you can fix it by seriously downgrading your drivers OR by updating it to the newest version cause they just fixed it! hope this helps :D

**Comment by RaycePenguin1** [comment]
if you have windows 11 it is still broken though
