### ISSUE TITLE
[Bug]: RFTools Quarry mines up bugged Forestry leaves which crashes game when viewed

### ISSUE THREAD

**Issue by minghinshi** [FTBTeam/FTB-Modpack-Issues#1271]
### Modpack

FTB University 1.12

### Modpack version

1.2.1

### Log Files

Looks like 3 identical crashes:
https://paste.ee/p/fIwn9
https://paste.ee/p/zVZra
https://paste.ee/p/RGiJK

### Describe the bug

I have 2 RFTools Quarry running in the Balanced planet with Clearing Silk Touch Quarry cards in them. They mine up not only resources, but things above ground as well like trees. Some trees, for some odd reason, have Forestry leaves which are mined as items due to silk touch. Some of these Forestry leaves have bugged names like "trees.grammar.leaves.type". Some of these bugged leaves are otherwise fine, but some of them seem to crash the game whenever rendered in an inventory, e.g. a diamond chest in my world. (TOP handles the issue likely by catching the exception and displaying an error message instead.)

### Steps to reproduce

1. Make an RFTools Quarry setup in the Balanced world
- Give it power
- Connect it to a sufficiently large storage to sample more leaves
2. Set up the silk touch quarry card
- Define the boundaries; the volume should contain a good number of leaves
- Put the card in the quarry and start it
3. Wait until the quarry somehow mines up a bugged leaf that can't be rendered
4. Game crashes

(Not very certain if this can reproduce the bug at the moment, I'll supplement additional information below)

### Expected behaviour

The leaves should not cause the diamond chest to crash the game when opened.

### Screenshots

![2022-08-15_23 28 46](https://user-images.githubusercontent.com/66774379/184669368-33468604-4715-49ec-b9a4-5830f38d4c4e.png)

### Additional information

- It is unclear whether holding the item / dropping the item on the floor / rendering the item in a storage drawer would cause the player to be "perma-banned" from the world, since every time the world loads up the same crash would happen immediately
- It is unclear whether this only happens with RFTools silk touch quarry, or silk touch tools in general. If it's the latter case I'll update the name of this issue to reflect this.

**Comment by minghinshi** [comment]
Update 1:
I went ahead and mined some leaves manually with a silk touch pickaxe, and they all dropped as regular origin leaves. RFTools might be the actual source of the problem. 
![image](https://user-images.githubusercontent.com/66774379/184673937-53b057c6-6557-4a9a-8195-c3e4f27b70ee.png)

**Comment by minghinshi** [comment]
Update 2:
I made a copy of the save and broke the chest, now the crash happens immediately after entering the world, which confirms my guess that you get "perma-banned".

**Comment by minghinshi** [comment]
Update 3:
I swapped out the silk touch cards for fortune cards and the bugged leaves no longer drop.

**Comment by Raidobw2** [comment]
Hmm. Unsure what a good solution would be for this one, or if there is one since mods in 1.12.2 are no longer updated. Currently your best workaround is to not use the silk touch card on the leaves. Code Chicken Lib (CCL) is throwing a graphics exception on those leaves. Maybe there's a way to disable something in CCL to prevent this, or to blacklist leaves from the builder.
