### ISSUE TITLE
[Suggestion]: Update FTB Chocolate's create mod to latest version

### ISSUE THREAD

**Issue by Iris-xii** [FTBTeam/FTB-Modpack-Issues#1272]
### Modpack

FTB Chocolate

### Is your suggestion related to a problem? Please describe.

Considering how popular of a mod it is I was surprised the latest version wasn't on the pack.
The suggestion is pretty much just updating that. That's all there is to it.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/create
(It is already in the pack, just not updated)

**Comment by manmaed** [comment]
This  issue is now Stale
