### ISSUE TITLE
[Suggestion]: Add Lazier AE2

### ISSUE THREAD

**Issue by mattague** [FTBTeam/FTB-Modpack-Issues#1273]
### Modpack

FTB Presents Direwolf20 1.18

### Is your suggestion related to a problem? Please describe.

I was looking for more in the way of making AE2 a bit simpler, and found this mod that adds a requester, to simplify autocrafting a little bit.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/lazierae2

Lazier AE2 adds a single that would make later game Applied Energistics a bit simpler, without requiring you to use it if you don't want to. I believe it is a pretty small mod, gets updated to fix bugs frequently, and would be a great fit for this modpack while requiring little in the way of extra work. The dev has shown a willingness to work with the community around various issues as well.

**Comment by TheonlyTazz** [comment]
LazierAE2 will not be added to the pack, as it makes the whole mod trivialized. One of the challenging factors of AE2 is how to handle with channels and learn to automate stuff. There are ways to make "Autocrafters/Stockkeeping" work in Vanilla AE2. Adding this mod just removes that aspect of AE2

**Comment by mattague** [comment]
Wasn't the whole purpose of this modpack to let you do things however you wanted? Isn't that the reason AE2 and refined storage are both in the pack? I like being able to interact with Mekism and Botania with AE2 and would rather not completely switch to refined storage.

**Comment by TheonlyTazz** [comment]
That is correct, feel free to add it yourself, but it will not get added to the pack by default
