### ISSUE TITLE
[Suggestion]: Peaceful friendly endgame

### ISSUE THREAD

**Issue by Raidobw2** [FTBTeam/FTB-Modpack-Issues#1274]
### Modpack

FTB Sky Odyssey

### Is your suggestion related to a problem? Please describe.

The netherstar locks the final EMC tools (Project EX: Mainly all the Final generator items) and also the Ultimate speed upgrade (Extra utilities 2: In this case for the Evil infused stuffs).

In order to get netherstars, you need soul sand and wither skeleton skulls to fight the wither. It's not possible to get wither skeleton skulls if playing on peaceful.

Maybe the wither skeleton skulls can have EMC added to them, or be obtainable another way? If that way to get them is made more difficult to stray players away from it in normal playthroughs, then that's probably fine.
E.g. Some kind of combination crafting or even Draconic Evolution crafting

Continuation of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/746

### Mod suggestion

N/A

**Comment by TheonlyTazz** [comment]
i added an alternative method to get a Data Model for DML, which includes a potion of decay
to achieve this, you need a brewingstand, fermented spider eye and ghast tear. This isnt to hard to get, but also not something u can do on day 1.

![image](https://user-images.githubusercontent.com/3908847/187181697-9a88f2ef-dab4-4b41-8dd2-e075dc37ba9c.png)
would like to get feedback on the recipe, and we can then add it to the update

**Comment by Raidobw2** [comment]
I like it!

**Comment by nowifi4u** [comment]
I guess I like it? You still have to kill 5 Wither Skeletons to be able to use the Data Model

**Comment by TheonlyTazz** [comment]
true, i totally forgot about that, i will look into giving it a data model that is actually usable

**Comment by GamingWithJanko** [comment]
Any updates yet?
