### ISSUE TITLE
[Bug]: No crafting recipe available for RF angel rings of angelring mod

### ISSUE THREAD

**Issue by Lauriichan** [FTBTeam/FTB-Modpack-Issues#1276]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

There are no recipes available for the energy angel rings of the angelring mod
Following items are not craftable:
- angelring:leadstone_angel_ring
- angelring:hardened_angel_ring
- angelring:reinforced_angel_ring
- angelring:resonant_angel_ring

Currently you can only craft the normal angelring and the energetic one.
In my opinion you should be in need to craft the leadstone one before the energetic one as the energetic one has a larger energy capacity.

### Steps to reproduce

1. Join a world
2. Search for any of the mentioned angelrings in REI
3. Check their crafting recipe
4. See that it doesn't exist

### Expected behaviour

The angel rings should be craftable

### Additional information

To compensate for this issue I temporarily added the crafting recipes on my own however they are probably not balanced but I'll provide them anyway. 
https://gist.github.com/Lauriichan/92d5ef7765188145fced2aa3e8c8bbfb

**Comment by Raidobw2** [comment]
Thank you for posting your code snippet as well!
