### ISSUE TITLE
[Bug]: Some materials don't exist making the mod SolarGeneration not possible to use

### ISSUE THREAD

**Issue by Lauriichan** [FTBTeam/FTB-Modpack-Issues#1277]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

There are some materials missing to craft the SolarGeneration solar panels.
The materials are:
- steel
- invar
- electrum
- signalum
- lumium
- platinum

Because of this you can't craft any of the SolarGeneration items making this mod completely useless

### Steps to reproduce

1. Join a world
2. Search for @SolarGeneration in REI
3. Check the crafting recipes of the solar panels
4. See that there are materials missing in the crafting recipe tree

### Expected behaviour

Being able to craft those solar panels with or without the missing materials

### Additional information

As I wanted to use these solar panels I made a temporary KubeJS script that just adds various item tags as a replacement to the missing material tags. I'll provide this script here for anyone to use but I don't think it is balanced in any way.
https://gist.github.com/Lauriichan/d65b1f4e19e669ef1899d4840e02cbb2

**Comment by Lauriichan** [comment]
Could be seen as a duplicate of #1149 because it mentions those materials in relation with SolarGeneration in the comments

**Comment by Raidobw2** [comment]
Thanks for the code snippet here too. You can leave it opened, here can be for solars, the other issue could be for steel in particular
