### ISSUE TITLE
[Bug]: EnderRift causes a lot of lag

### ISSUE THREAD

**Issue by Lauriichan** [FTBTeam/FTB-Modpack-Issues#1279]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

When actively using EnderRift with for example a quarry or another constant input of items it causes an huge amount of lag

### Steps to reproduce

1. Build a rift
2. Add a constant throughput of Items
  => I recommend using a fully enchanted QuarryPlus (Efficiency 5; Unbreaking 3; Luck 3)
3. Use a Automation Interface to insert the items (example construction below)

### Expected behaviour

Not a nearly doubled amount of lag when using the rift

### Screenshots

When Rift doesn't have a constant throughput of items
![Rift without constant item input](https://user-images.githubusercontent.com/41839265/185089428-2558ec1e-6fa1-4604-8d6b-ea7c641e5020.png)

When Rift has a constant throughput of items
![Rift with constant item input](https://user-images.githubusercontent.com/41839265/185089655-50714c3d-dd82-40bc-b16a-85889bb1bd63.png)

Used block structure for Rift
![2022-08-17_11 52 57](https://user-images.githubusercontent.com/41839265/185090212-73230a88-e499-41b7-b985-31b70ff8211a.png)

### Additional information

Even though there is the alternative of using Tom's Simple Storage Mod it is quite inconvenient using it because of the huge amount of chests required.
Maybe consider adding another Storage Mod that doesn't lag the server as much as Ender-Rift does it.
For example the known go-to Mods Refined Storage (currently 1.18.2 only) or Applied Energistics 2 (Has 1.19 alpha version)

### Hardware
CPU: Intel(R) Xeon(R) CPU E5-2450 v2 @ 2.50GHz (2 Sockets) (32 Cores)
RAM: 12 GB (Minecraft Server Ram) (6 GB Used)

**Comment by Lauriichan** [comment]
I made a [PR for Ender-Rift](https://github.com/gigaherz/Ender-Rift/pull/56) that should fix most of the lag issues with this mod
If we get lucky the owner of the mod accepts my PR

**Comment by Raidobw2** [comment]
Thank you!

**Comment by Lauriichan** [comment]
Something I didn't mention in the issue itself is that it is related to how the storage system handles items of the same type. It just works like a giant inventory with infinite space meaning every time a new item of any time is added it checks if there is a slot with that type and if so it checks if it can add items to that. This is a working but quite inefficient approach as you could just store items with the exact same NBT data in the same "slot". My PR does exactly that which "delays" the lag. Meaning it doesn't fully fix the issue but instead it delays it. So as long as you don't have about 2000 items with different NBT data in your Rift it shouldn't lag as much. It's an exponential lag increase the more item types you add to the system (In the current state its not items with the same nbt but instead the more items stacks)

**Comment by Lauriichan** [comment]
Is EnderRift still an issue in the modpack or is it no longer in there?

**Comment by Saereth** [comment]
It's good now, ty for your PR, we have a big update coming out for this pack this month so it'll be in there with the latest version

**Comment by Lauriichan** [comment]
Sounds good!

However if I remember correctly the developer told me that they might change some things in code before releasing it. And so far I didn't notice any EnderRift update on CurseForge therefore that issue will still exist if the developer doesn't do anything in that time.

**Comment by Lauriichan** [comment]
May I ask how this was fixed now?

Was the mod removed? I guess that's what has been done as the performance improvements of the mod were not yet published on CurseForge or any other platform
