### ISSUE TITLE
[Bug]: direworld20 1.18 deepslate inert crystal ore not accepted in enrichment chamber

### ISSUE THREAD

**Issue by Pinezerka** [FTBTeam/FTB-Modpack-Issues#1280]
### Modpack

direwolf20 1.18

### Modpack version

1.9.1

### Describe the bug

**deepslate** inert crystal ore not accepted in enrichment chamber

base inert crystal ore however dose work x2

### Steps to reproduce

![Screenshot 2022-08-17 222314](https://user-images.githubusercontent.com/39213507/185136527-8328a1f3-d51b-449f-8f57-426827ab4aeb.jpg)

### Expected behaviour

deepslate inert crystal ore working with enrichment chamber

**Comment by TheonlyTazz** [comment]
![grafik](https://user-images.githubusercontent.com/3908847/201186638-4ee6c75e-0673-439f-a5c7-6c6c8657dd83.png)
added
