### ISSUE TITLE
How to play the old Futurecraft?

### ISSUE THREAD

**Issue by Trep009** [FTBTeam/FTB-Modpack-Issues#1281]
### Modpack

Private Pack

### Is your suggestion related to a problem? Please describe.

Hi, i just want to know how to play private modpack, i have password but i dont know ehere to put it, thanks for any help and bye.

**Comment by Raidobw2** [comment]
Hi, this was a feature of the old FTB Launcher. The FTB App doesn't have pack codes anymore. Which modpack are you trying to find?

**Comment by Trep009** [comment]
The code was FUTURECRAFT

**Comment by Raidobw2** [comment]
Hi again, with the current FTB App that's currently not possible. I know two ways to get Futurecraft:
1. The old Legacy Launcher which is still available on the FTB Site https://www.feed-the-beast.com/app
Scroll down to the bottom of the page
![image](https://user-images.githubusercontent.com/17010632/185514206-ee1c7ede-7c20-44e5-84fc-50a021491c2f.png)

2. MultiMC can download 3rd party packs
![image](https://user-images.githubusercontent.com/17010632/185514300-9d1f2390-04e9-4f91-8d24-e2bd840d91eb.png)

Try either and let me know if you managed to get it!

**Comment by Raidobw2** [comment]
Hi @Trep009, did it work? If you install the pack from the old FTB Launcher you might have to move the pack to another launcher (the files). If you have to reinstall the Forge version for it, the CurseForge App might be a good candidate for that

**Comment by Trep009** [comment]
Hi @Raidobw2 thanks for all the help but im not home so i will try it when ill be at home and the MultiMC doesnt worked so i was trying FTB so i will try The FTB Legacy and thanks again for all the help.

**Comment by TheonlyTazz** [comment]
After testing for a while, i could not login onto the old FTB Launcher
remember: 
![image](https://user-images.githubusercontent.com/3908847/187183360-00eafd78-71ec-4298-81b3-a5f9778b526f.png)

and it seems the pack is not on curseforge

**Comment by Josifekjj** [comment]
Hi, i am trying to download the ftb legacy launcher but I dont have the button Under the big button.    I have multi mc but it has bugs. I want to play with friends so not multimc.

**Comment by Gaz492** [comment]
> Hi, i am trying to download the ftb legacy launcher but I dont have the button Under the big button. I have multi mc but it has bugs. I want to play with friends so not multimc.

The legacy launcher is no longer available to download, and if it was, it wouldn't work anyway as you wouldn't be able to login to your minecraft account.

**Comment by Josifekjj** [comment]
The only way to play this modpack is trough multi mc mentioned earlier. But it might not work for someone so if it doesnt, follow this tutorial: First download java8u51 then set it for the instance (modpack), then click versions - forge - customize - change version - set it to the newest (it has a star next to it, i think its 9.1.11.1345 or something like that)
And launch. This worked for me and should work for everyone

**Comment by Kurizek27** [comment]
> The only way to play this modpack is trough multi mc mentioned earlier. But it might not work for someone so if it doesnt, follow this tutorial: First download java8u51 then set it for the instance (modpack), then click versions - forge - customize - change version - set it to the newest (it has a star next to it, i think its 9.1.11.1345 or something like that) And launch. This worked for me and should work for everyone

where do i find java8u51? everywhere i look, there is only java development kit and 0 jre

**Comment by Josifekjj** [comment]
Hi, the jre8u51 is listed on the oracle website , but if you dont have an oracle account you cant download it, but some websites still do have it and this is one of them https://archive.org/download/Java_8_update_51/jre-8u51-windows-x64.zip (its a direct download!!!)
