### ISSUE TITLE
[Bug]:  Boat quest broken

### ISSUE THREAD

**Issue by ph1823** [FTBTeam/FTB-Modpack-Issues#1282]
### Modpack

FTP OceanBlock

### Modpack version

1.15.0

### Log Files

https://pste.ch/ajafefezid.md

### Describe the bug

The boat originally intended for the quest no longer exists.

### Steps to reproduce

1. Go to quest
2. Select Exploration
3. Select first quest
4. The inital boat is not found (mod remove ?)

### Expected behaviour

a valid boat

### Screenshots

![image](https://user-images.githubusercontent.com/8150089/185647356-29db65e4-9293-4965-a806-2e473a92889b.png)

### Additional information

How to fix this ? Because the only usable boat is very expensive..
Thank you.

**Comment by TheonlyTazz** [comment]
The actual boat for these quests still exist, but i had updated the FTB Quest mods to use a diffrent file format, which broke the "OR Filter" on the quest.
I will work on a fix as soon as possible.
If you have cheats enabled, you can use
`/ftbquests editing_mode true` to enable the editing mode of the quests. and then right click the quest
to complete instantly, or right click on the purple question block and edit the item to the small_cog you crafted.

If you are playing in Singleplayer mode and you don't have cheats enabled, you can go play on LAN and enable cheats there temporarily

**Comment by TheonlyTazz** [comment]
This got fixed in dev, you can either download the new v1.15.1 when its available or use this questfile


Treasurehunt Quest Files Oceanblock v1.15.1 (config/ftbquests/quests/chapters/treasure_hunt.snbt) 
https://gist.github.com/TheonlyTazz/54c78754690a196e206f0dad5ae723ac

**Comment by Raidobw2** [comment]
1.15.1 is jnow available, assuming fixed!
