### ISSUE TITLE
[Bug]: Quark dungeons generate in Blood Magic dimension

### ISSUE THREAD

**Issue by quietust** [FTBTeam/FTB-Modpack-Issues#1283]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.9.1

### Describe the bug

Quark's dungeons are generating in the void of the Blood Magic "Hidden Realm" dimension, whose biome is `bloodmagic:none`.

### Steps to reproduce

1. Perform the "Edge of the Hidden Realm" ritual in Blood Magic
2. Right-click on the Inversion Pillar and teleport to the Hidden Realm dimension
3. Look at the minimap and observe that there's probably a Quark dungeon very nearby.

### Expected behaviour

Quark dungeons shouldn't generate out in the void

### Screenshots

![image](https://user-images.githubusercontent.com/1005195/185722900-c780bbc6-174e-40dd-b582-c5d86fd1a379.png)

### Additional information

This is basically the same as #894, but with yet another dimension.

**Comment by Raidobw2** [comment]
Thanks for the report!

**Comment by Raidobw2** [comment]
I did a bad labeling manipulation, sorry. This is only fixed in a dev build
