### ISSUE TITLE
[Bug]: FTB One Crash (bug with evilcraft?)

### ISSUE THREAD

**Issue by rayorcol** [FTBTeam/FTB-Modpack-Issues#1287]
### Modpack

FTB One

### Modpack version

1.3.0

### Log Files

[crash-2022-08-23_21.08.42-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9410097/crash-2022-08-23_21.08.42-server.txt)

### Describe the bug

The game crashes when I throw a "Biome Extract" on the light emitted by an "Environmental Accumulator". I think it's a problem with the evilcraft mod.

### Steps to reproduce

1. Find an "Environmental Accumulator" naturally or with the command: "/setblock ~ ~ ~ evilcraft:environmental_accumulator"
2. Give a "Biome Extract" with the command: "/give @p evilcraft:biome_extract"
3. Drop the "Biome Extract" on the "environmental accumulator"
4. Wait for the end of the loading bar at the top of the screen
5. The game crash

### Expected behaviour

Normally the game should work

### Additional information

Forge version: 41.0.63

**Comment by Saereth** [comment]
the cause of this was found and fixed due some troubleshooting with interactions as well, update will have it sorted in 2.0
