### ISSUE TITLE
[Bug]: Chicken Catcher Does not work

### ISSUE THREAD

**Issue by JLeif** [FTBTeam/FTB-Modpack-Issues#1288]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

Chicken Catcher does not work, this breaks the flow of the mod.

### Steps to reproduce

1. Created Chicken Catcher
2. With Chicken Catcher selected in hand as the active item, Right-clicked a chicken
3. A Chicken does not appear in inventory

### Expected behaviour

Be able to catch Chicken with Chicken Catcher

**Comment by JLeif** [comment]
Ok, so the Chickener Catch DOES work. you have to hit a chicken with a Book first...
This should be noted in game, or a wiki or something...

**Comment by Raidobw2** [comment]
Relayed the suggestion to the mod author ^ so I'll close this current issue
