### ISSUE TITLE
[Bug]: OceanBlock Missing Recipe for Crystalized Menril Chunk on Squeezer

### ISSUE THREAD

**Issue by nicszerman** [FTBTeam/FTB-Modpack-Issues#1291]
### Modpack

FTB OceanBlock

### Modpack version

1.14

### Describe the bug

The recipe to make Crystalized Menril Chunk on a Squeezer using Menril Logs is missing. There is however the Mechanical Squeezer recipe.

### Steps to reproduce

Click R on Crystalized Menril Chunk in NEI.

### Expected behaviour

The recipe should show up in the NEI menu.

### Screenshots

![image](https://user-images.githubusercontent.com/14032356/186777456-a32c35de-9750-4d5a-b73d-9f565c112888.png)

**Comment by DinnerBeef** [comment]
Looks like this is the intended way of having the recipes according to the mod.

**Comment by nicszerman** [comment]
@DinnerBeef the recipe is not there. the posted issue is not about the recipe format, it's about the lack of a recipe.
