### ISSUE TITLE
[Bug]: Builder doesn't accept clock

### ISSUE THREAD

**Issue by kaiakrystal** [FTBTeam/FTB-Modpack-Issues#1296]
### Modpack

Minecraft colonies

### Modpack version

Direwolf 1.18

### Describe the bug

I'm not sure of the actual modpack or version, but...
In the Direwolf20 The Builder requires a clock to complete a build. I made a clock. She doesn't recognize it as the required item, thus cannot complete the build.

### Steps to reproduce

Level 4 Cowherd Hut requested.
Builder requests (minecraft) clock. 
Clock is made.
Clock is given directly to the builder.
Builder still does not recognize clock as required item.
Clock was put into warehouse. Couriers did not recognize clock as requested item.
Clock put into Builder Hut inventory - still not recognized.
Could not "FULFILL" request with Builder.

### Expected behaviour

Accept the clock and complete the level 4 cowherder hut build

**Comment by Raidobw2** [comment]
I think Quark adds a tag to the clock so it could make sense why that fails.

We'll need to report to the mod author since them fixing it to ignore tags seems like the best solution. I'm not actually sure you can fix this in your game at this moment, since every clock has that tag now.

**Comment by kaiakrystal** [comment]
Update: Went into creative mode and handed the clock over that way. It happened with another build, as well.

**Comment by Raidobw2** [comment]
Oh, glad that worked!

Apparently Minecolonies do not want to add compatibility for it despite the many reports, referring to https://github.com/ldtteam/minecolonies/issues/8019, https://github.com/ldtteam/minecolonies/issues/7913, etc, many more.

One solution in that case is to configure quark at `quark-common.toml` and disable the clock nerf, I'm guessing that will do it. You can try it if you want. Set the clock nerf to false.

To modpack dev next doing maintenance: Might as well remove other nerfs to prevent other weird compat issues. Switch all 4 to false, bring it back like vanilla?

![image](https://user-images.githubusercontent.com/17010632/187060045-38100290-61a3-45a2-a90a-45b221cce846.png)

**Comment by TheonlyTazz** [comment]
clock was already set to false, i will set the other 3 to false aswell
