### ISSUE TITLE
[Bug]: FTB One server crash during player exploring biome with Acaia related mod Productivebees

### ISSUE THREAD

**Issue by cbrathen** [FTBTeam/FTB-Modpack-Issues#1298]
### Modpack

FTB One

### Modpack version

1.3.0

### Log Files

[crash-2022-08-28_10.43.25-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9439420/crash-2022-08-28_10.43.25-server.txt)

### Describe the bug

Server worked fine until exploring biome with Acaia trees and it crashed several times. I've tried everything and the crashlogs displaying Acaia_bee_hive as a problem.
After isolating the mod and starting the server again exploring works fine.
Is there something with my setup or is it a bug in the modpack? I'm running a linuxserver on Gentoo with the Java environment that comes with the modpack.

Happy to help with as much logs as needed but I'll begin with the craschreport.

Kind regards
Christopher

### Steps to reproduce

1. Go to the savanna biome with Acaia trees.
2. Exploring.
3. After a while the server crashes.

### Expected behaviour

Exploring without crashes.

**Comment by cbrathen** [comment]
I've done some more testing and are now running the server on a new machine with a freshly installed version of the core server files. It's working with the old world files.

This is because I run in to another issue after I posted this report. Got fatal error from Java and did a memtest on my memory dimms with plenty of errors. So probably this is all because of bad memory sectors. My server setup is pretty old from 2012 so probably best to retire.

For now were running stable with all the mods active on the other machine.
Thanks anyway!

**Comment by TheonlyTazz** [comment]
Reading through your crash log, it is safe to assume that the server crashed due to having not enough calculation power;
as you said yourself, the specs arent to great, the Processor was released in 2007 (thats 15years ago) and you have specified these 2 flags:
`JVM Flags: 2 total; -Xmx2048M -Xms1024M`

you also said the server is running on a new machine and havent had any issues so far, i'll let this issue open for @Raidobw2 to have a double check and close, incase i missed something

**Comment by cbrathen** [comment]
Actually the server worked well before the memory started to behave strange. That flags with small amount of memory aloc was set after a few crashes to try pinpointing the issue. Normally there was 6GB dedicated to java.
But with a whole dimm with broken sectors it was doomed to run java on it.
FTB is working pretty well even on old hardware if you run enough memory for it. But DDR2 dimms is just so expensive today so I'm have to retire it as a gaming server.

Thanks for the development of FTB One. We're having a good time playing it :)

**Comment by Raidobw2** [comment]
The hardware definitely isn't top notch, but from what I understand of the error, there's a call that shouldn't have been made on that thread to access that variable.

I don't think that's hardware related, I think that's a legit mod bug, so I'll report it and the mod author will be able to check.

**Comment by JaisDK** [comment]
Should already be fixed, you just need to update PB

**Comment by JaisDK** [comment]
not sure you can update since the pack is still on 1.19 not 1.19.2

to prevent further crashing you can set the spawn rate of solitary nests to 0 in `serverconfigs/productivebees-server.toml`

**Comment by Raidobw2** [comment]
Awesome, thanks for the information, we'll do that :)
