### ISSUE TITLE
[Bug]: Recipe conflict for iron chests

### ISSUE THREAD

**Issue by OscarAblinger** [FTBTeam/FTB-Modpack-Issues#1299]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.9.1

### Describe the bug

Currently it's impossible to craft the uncolored Sophisticated Storage's Iron chests (e.g. "Spruce Iron Chest") since you'll always craft the Iron Chests version.

This could be fixed by either changing one of the recipes (e.g. having the Iron Chests one only accept the generic Chest (that other chests can be turned into)) or maybe allowing conversion from one into the other.

### Steps to reproduce

1. Try to craft the Sophisticated Storage Iron Chest

### Expected behaviour

I can craft both iron chests somehow.

### Screenshots

![image](https://user-images.githubusercontent.com/25868587/187076889-f413e3b6-7e5e-4036-8abb-c4eeb0d78f8f.png)
![image](https://user-images.githubusercontent.com/25868587/187076905-448188dd-3b11-4c9e-9303-1262ebb1af4e.png)

**Comment by OscarAblinger** [comment]
Just saw that the Spruce Chests that Sophisticated  storage accept are different spruce chests that require a redstone torch to be added.
Sorry for the confusion.

**Comment by macks2008** [comment]
@OscarAblinger If it's any consolation, I was similarly confused, so you helped me by opening this issue and documenting the solution.
