### ISSUE TITLE
[Bug]: Taskless quests don't trigger instantly

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Modpack-Issues#13]
### Modpack

FTB University 1.16

### Modpack version

1.2.0

### Describe the bug

Need to go through them all and fix

### Steps to reproduce

Obvious

### Expected behaviour

Obvious

**Comment by legitswitch** [comment]
Twilight Forest
![image](https://user-images.githubusercontent.com/88232383/136846085-f7641644-8070-4ffc-af9c-ecb654a0e241.png)

**Comment by legitswitch** [comment]
The quests are broken as in they don't complete. It was reported by multiple players on a server and I'm just taking a screenshot of which quests they are. I haven't done the quests myself.
