### ISSUE TITLE
[Bug]: Sky Odyssey Broke certain recipies

### ISSUE THREAD

**Issue by 5ully** [FTBTeam/FTB-Modpack-Issues#1300]
### Modpack

FTB Sky Odyssey

### Modpack version

1.4.0

### Log Files

n/a

### Describe the bug

With the latest update of Sky Odyssey at least 2 things broke, both should be fairly simple to fix:
The Flux from flux networks is no longer craftable, 1.3.0 had a recipe that was smelt redstone -> flux.

The second issue is a Black Hole Controller Issue:
The questbook is asking for one that does not have a recipe, replace the item the quest is asking for with the Black Hole Controller (2.0)

### Steps to reproduce

Open sky Odyssey 1.4.0

### Expected behaviour

n/a

### Additional information

@TheonlyTazz  Both of these should be simple fixes by just adding an extra recipe, that you might be able to pull from 1.3.0 since the flux recipe exists in that version and changing the quest requirement for Black Hole Controller from:
industrialforegoing:black_hole_controller -> industrialforegoing:black_hole_controller_reworked

**Comment by TheonlyTazz** [comment]
I'll fix them Monday, thanks alot!

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/187178415-73f1d8b2-7f54-46ee-a59d-6f9dd735f6be.png)
recipe got added, and the quest for the black hole controller got fixed aswell! pushing out hotfix later today
![image](https://user-images.githubusercontent.com/3908847/187178527-0a59cbb5-b82f-43fd-a686-33760fc22d21.png)
