### ISSUE TITLE
[Bug]: Changing the channel of a logistic module from pncr doesn't keep it changed, but instead it reverts itself after a few seconds

### ISSUE THREAD

**Issue by Rosewarden** [FTBTeam/FTB-Modpack-Issues#1301]
### Modpack

FTB Plexiglass Mountain

### Modpack version

Beta 1.1.1

### Describe the bug

When I setup the channel by right-clicking the logistic module then selecting the color, it changes it to the selected color but after a few seconds it reverts back to white. When I right-click the logistic module with a yellow dye (in my case), it keeps it changed and doesn't revert to white.

### Steps to reproduce

1. Right-click the logistic module with an empty hand. This menu should pop-up
![image](https://user-images.githubusercontent.com/112348780/187093116-d7d2c4e5-1aac-4d53-a8ef-e22470ed8000.png)
2. Change the channel to a different color
3. After a few seconds it "should" revert back to white.

### Expected behaviour

The module should remain on it's selected channel.

### Screenshots

This is WORKING the setup I currently have because I changed the channel by right-clicking the logistics module with a yellow dye.
![image](https://user-images.githubusercontent.com/112348780/187093191-0d082e2c-68ab-4649-95a0-e837e1576cfd.png)
![image](https://user-images.githubusercontent.com/112348780/187093199-6b94b4b0-f773-4812-88cf-c2ca1d343d7e.png)
![image](https://user-images.githubusercontent.com/112348780/187093203-028c4bbe-0ac9-44a6-b532-65750bf7e9fe.png)

**Comment by Rosewarden** [comment]
From the 3.4.0 changelog:

-  Fixed Redstone Modules not syncing settings properly on Reinforced or Advanced Pressure Tubes (only worked on basic tubes)

**Comment by Raidobw2** [comment]
I'll keep this opened while 1.2.0 is on the way (this is included within the changelog). Once it's shipped and I know it's fixed, I'll update this again. Thanks for the report

**Comment by Raidobw2** [comment]
Should be fixed in 1.2.0
