### ISSUE TITLE
[Bug]: Minecolony Villagers lose Inventory upon using Carry On on them.

### ISSUE THREAD

**Issue by suicreeps** [FTBTeam/FTB-Modpack-Issues#1302]
### Modpack

Direworlf20 1.18

### Modpack version

1.9.1

### Describe the bug

Minecolony villagers loose inventory when picking them up with carry on.

### Steps to reproduce

1. Shift Right Click any Minecolony villager (in my ex., the builder)

### Expected behaviour

Builder/Villager looses inventory, loss of construction materials....expected loss of required materials in tab.

**Comment by TheonlyTazz** [comment]
added Minecolonies to the blacklist of carryon
