### ISSUE TITLE
[Bug]: Plate Recipes using Forge Hammer or Engineer's Hammer do not work

### ISSUE THREAD

**Issue by AshraPlays** [FTBTeam/FTB-Modpack-Issues#1303]
### Modpack

FTB Sky Odyssey

### Modpack version

1.4.0

### Describe the bug

When trying to make plates using either the Forge Hammer or the Engineer's Hammer, it does nothing. Even when clicking from JEI to add the components, it does not work. The ingot and the hammer are placed in the crafting slots, but there is no output.

### Steps to reproduce

Open a crafting bench/ your inventory
Place either a Forge Hammer or an Engineer's Hammer in the crafting slot
Add an ingot with a plate recipe into another slot
There is no plate in the output slot

### Expected behaviour

Both hammers should work when trying to craft plates

### Screenshots

![Engineer Hammer](https://user-images.githubusercontent.com/112521266/187554141-64def736-6a04-429b-bfb4-f3fccd4b03a4.png)
![Forge Hammer](https://user-images.githubusercontent.com/112521266/187554145-60794777-11f6-4dc8-b695-32effedef658.png)
![Recipes](https://user-images.githubusercontent.com/112521266/187554147-67ee8ed3-57ce-4367-a975-96f3fc1720c2.png)

### Additional information

It does not matter which crafting inventory the materials are placed in, there is never a plate being output.

**Comment by AshraPlays** [comment]
I have tried inventory crafting, RS crafting, a crafting bench, and the arcane transmutation table, and none of them produce a plate.

**Comment by nowifi4u** [comment]
Thermal Expansion's Compactor thankfully works

**Comment by No-steve** [comment]
Same for 1.4.1

**Comment by nothub** [comment]
same for 1.4.2
