### ISSUE TITLE
Missing archwood Door Texture

### ISSUE THREAD

**Issue by satrn1** [FTBTeam/FTB-Modpack-Issues#1308]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

Archwood door appears as a purple and black texture

### Steps to reproduce

i dont know

### Expected behaviour

I expected a door

### Screenshots

![image](https://user-images.githubusercontent.com/107375160/188270036-a58b7b47-4f8e-4db5-bca7-7bc96a23683f.png)

**Comment by MiiWii0312** [comment]
I'm having the same issue and menril doors do the same thing.
