### ISSUE TITLE
[Bug]: Connected Glass: Connecting Tinted Glass can not be crafted

### ISSUE THREAD

**Issue by Vypir** [FTBTeam/FTB-Modpack-Issues#1309]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.9.1

### Describe the bug

Connected Glass Mod item Connecting Tinted Glass can not be crafted because it shares a recipe with the Cyclic mod Tempered Dark Glass.

I can't find a way to change which item is crafted from the two patterns.

### Steps to reproduce

1) Craft 4 Minecraft Tinted Glass
2) put them in a 2x2 crafting grid.

### Expected behaviour

I expect to be able to select which of the blocks are crafted when a block shares the same crafting recipe

**Comment by TheonlyTazz** [comment]
![grafik](https://user-images.githubusercontent.com/3908847/201182954-d1a82049-1c7b-4878-bb38-3963749a6f19.png)
removed the cyclic version from the crafting table
cyclic variant is still available via cutting table (all 3 variants are now)
![grafik](https://i.imgur.com/Ke0YmJ2.gif)
