### ISSUE TITLE
[Bug]: Crashing when i try to join a server

### ISSUE THREAD

**Issue by Reloada** [FTBTeam/FTB-Modpack-Issues#1310]
### Modpack

FTB One

### Modpack version

1.3.0

### Log Files

[crash-2022-09-06_08.30.56-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9494077/crash-2022-09-06_08.30.56-client.txt)
[crash-2022-09-06_08.14.49-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9494137/crash-2022-09-06_08.14.49-client.txt)

### Describe the bug

The problem started today after i crashed when playing.
I was looking in my inventory while playing on the server and it crashed.
After the crash i couldnt get back in.

When i try to connect to a server other friends are playing on my instance crashes.
It's the first time its happen and i tried to log on to the server again after restarting my PC with the same results.

I can start the game but not join the server.
I uploaded the first and last crash logs if one or the other helps

### Steps to reproduce

1. I start the game 
2. its loads up like it should
3. connect to server
4. just before loading the world is say "saving world" and closes the game(CTD).

### Expected behaviour

to connect to the server

**Comment by Raidobw2** [comment]
Hello, this is the same bug as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1098.

The quickest solution would be to restore a backup from your `backups` folder (it's next to the `mods` folder in your modpack files). You want to replace the `world/region/r.0.4.mca` file with the one of a backup.

Another solution would be to take the file `world/region/r.0.4.mca` and drop it here, I can fix it for you. If it's too big, use Google Drive. Note that I'm heading to sleep and will be busy for some time, so I may reply only in a bit more than half a day.

If you do know how to use 3rd party programs to modify the world save, you basically have to destroy the block at (162x, 59y, 2280z).

Read my linked issue 1098 for more info ^

**Comment by Reloada** [comment]
Thanks, i'll send this to the server admin and see if they can remove that block! 
Thanks again!

**Comment by Reloada** [comment]
The problem can be replicated when taking a chicken out of the roost after its full.

**Comment by Raidobw2** [comment]
I see, make sure to always empty the roost nests with cables (have an overflow in a trash can for example) and you should be able to avoid the issue for now. Chicken mod has not released another public build yet but they have fixed this in the development version to my knowledge.

If this ended up being fixed by your server admin make sure to close this issue!

**Comment by Reloada** [comment]
We are working around the problem for now, i'll close this case!
Thanks for all the help!
