### ISSUE TITLE
[Bug]: Crashes when i try to join a server or singleplayer world

### ISSUE THREAD

**Issue by einarorn228** [FTBTeam/FTB-Modpack-Issues#1311]
### Modpack

FTB Revelation

### Modpack version

3.6.0

### Log Files

[hs_err_pid10752.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9501245/hs_err_pid10752.log)

### Describe the bug

I installed the mod pack on FTB app and clicked play, then i waited for the mod pack to lunch.it lunched fine but when i went to join the multiplayer or singleplayer world it crashed.

### Steps to reproduce

1. install mod pack
2. press play 
3. wait for mod pack to lunch
4. try to join multiplayer or singleplayer world
5. game crashes when loading terrain poops up on screen

### Expected behaviour

To play the modpack

### Screenshots

![Screenshot 2022-09-06 224342](https://user-images.githubusercontent.com/112987935/188753212-376ed9b1-f15f-4ead-89fd-8e6470cd7f04.png)

**Comment by Raidobw2** [comment]
Do you have a graphics card from Nvidia or AMD or only an old CPU? That looks like one of the old bugs with Intel Hardware Acceleration on old CPUs.

Linked: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/693

Check the 2 notices in https://bugs.mojang.com/browse/MC-32606 with some given fixes. Try some of them or all and let me know if any worked.
