### ISSUE TITLE
[Bug]: SkyFactory 3 won't start

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Modpack-Issues#1312]
### Modpack

FTB SkyFactory3

### Modpack version

1.10.2

### Log Files

[crash-2022-09-08_01.43.14-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9523677/crash-2022-09-08_01.43.14-client.txt)

### Describe the bug

When i try and open up the pack, it goes to phase 2/7 and then just crashes.

### Steps to reproduce

any

### Expected behaviour

idk

### Screenshots

idk

### Additional information

Sky Factory 3 wont open just crashes

**Comment by Raidobw2** [comment]
Hi, your assigned RAM and Java looks fine, maybe it could be an issue with the modpack installation.

Can you try installing the modpack on the FTB App? It will use a more recent version of Java, plus I know it works there. The FTB App has different modpack versions and files then the ones from FTB still listed on CurseForge. Let me know and thanks
