### ISSUE TITLE
[Bug]: Game instance crashes before launching

### ISSUE THREAD

**Issue by ituitis-burhan19** [FTBTeam/FTB-Modpack-Issues#1315]
### Modpack

FTB: Plexiglass Mountain

### Modpack version

1.1.1

### Log Files

https://pste.ch/ewolobohoq.sql

### Describe the bug

When i tried to open the game it crashed. Then i asked to FTB discord and then i tried to solution on issue #1076 with changing java runtime arguments. Still crashed.

### Steps to reproduce

1. Downloaded game
2. Click play
3. Crash
4. Change java runtime to -Duser.language=en -Duser.country=US
5. Click play
6. Crash

### Expected behaviour

Open the game

**Comment by Raidobw2** [comment]
Hi,

If the arguments didn't work, maybe it's the game files that are having some kind of issue. Plexiglass Mountain also has version 1.2.0 out with some major fixes.

Try the following:
1. Close the FTB App and reopen it
2. Install Plexiglass Mountain 1.2.0 (beta version)
3. Add `-Duser.language=en -Duser.country=US` to the arguments if your computer's language/keyboard is in Turkish or has special characters
4. Start the game

If you still crash, you can post the crash log from `crash-reports` again as well as your game log in `logs` called `latest.log`.
The crash log mentioned: `One of more entry values did not copy to the correct id. Check log for details!`, so I'm hoping there will be more information about the error in the main log from `logs`.

Thanks

**Comment by ituitis-burhan19** [comment]
Changing version to 1.2.0 solved the problem. Thank you.

**Comment by Raidobw2** [comment]
Good to know, thanks for letting me know. Have fun playing 🙂
