### ISSUE TITLE
[Bug]: crashed when connecting server 

### ISSUE THREAD

**Issue by chrysoljq** [FTBTeam/FTB-Modpack-Issues#132]
### Modpack

FTB OceanBlock

### Modpack version

1.1.0

### Log Files

https://pste.ch/yupaseyedi.rb

### Describe the bug

I have come across this problem many times. I can join my single game but when connecting the server it crashes. 
Re-downloading the modpack helps me solve it, but my two friends' client crashes though their mobpacks are new.

### Steps to reproduce

*

### Expected behaviour

*

**Comment by MichaelHillcox** [comment]
Hay, please update your modpack and or manually update the MineTogether mod on your clients and server. If this does not fix your issue, please @ me
