### ISSUE TITLE
[Suggestion]: add Fishing Dangers mod

### ISSUE THREAD

**Issue by vietduckg10** [FTBTeam/FTB-Modpack-Issues#1321]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

Hi, 
I have a mod that relative to fishing. It will give player a chance to hook up any entity (tnt, mob,...) when they pull their fishing rod. You can config the chance player will hook something out of water and the chance of each entity in config pool.
Hope this mod can make OceanBlock more interesting.
Thank you.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/fishing-dangers

**Comment by Gaz492** [comment]
Thanks for your suggestion, unfortunately we are no longer adding new mods to this modpack, but we will take it into account for any future modpacks we make.
