### ISSUE TITLE
crashes i soon is i try to join a server

### ISSUE THREAD

**Issue by destroyer6555** [FTBTeam/FTB-Modpack-Issues#1323]
### Mod

stoneblock2

### Mod version

idk how to checkl

### Forge / Fabric version

newest one

### What issue are you having?

game crashes every time i try to join my server

### Steps to reproduce

i just try to join my server

**Comment by Raidobw2** [comment]
Which version of Stoneblock 2 are you playing? The latest on CurseForge and the latest on the FTB App are not the same. The most up to date version is 1.22.0 on the FTB App. CurseForge uses a deprecated version and has a notice to tell you to use the FTB App.

Also, do you have logs/error messages, etc? Your logs are in the `logs` folder inside the modpack files, in a file called `latest.log`. That one usually contains the errors.
