### ISSUE TITLE
[Bug]: When I do the quest to right click on the wooden chest to add the iron upgrade it won't mark the quest off on the list.

### ISSUE THREAD

**Issue by MarcusTaylor303** [FTBTeam/FTB-Modpack-Issues#1326]
### Modpack

Academy

### Modpack version

1.2

### Log Files

![Screen Shot 2022-09-15 at 8 12 46 PM](https://user-images.githubusercontent.com/90425469/190550628-88236567-112d-416a-8840-a3a838b5b279.png)
![Screen Shot 2022-09-15 at 8 13 03 PM](https://user-images.githubusercontent.com/90425469/190550640-f741766b-ee4f-4328-8422-b2f8fda093cc.png)

### Describe the bug

I get to the point where it has you take the iron chest upgrade out of the chest and upgrade the chest, and it doesn't mark it off the list.

### Steps to reproduce

I don't know

### Expected behaviour

It's supposed to mark off the quest.

**Comment by Raidobw2** [comment]
Interesting, for me it completes it when I right click with the upgrade. I don't really know what happened in your game or how that didn't work.

If that happens again for another quest, let me know.

To "fix" that one quest, follow those steps:
1. Press Escape, click Open to LAN
![image](https://user-images.githubusercontent.com/17010632/190612324-639e0bf3-9954-4871-9807-5cd89c796046.png)
2. Enable cheats and start LAN world
![image](https://user-images.githubusercontent.com/17010632/190612427-312d0aac-1e17-488c-90d5-90ceddfaf6b4.png)
3. Open chat, type `/ftbquests editing_mode`, press Enter
![image](https://user-images.githubusercontent.com/17010632/190612603-51c301d6-5ca6-4ec6-baf5-d3ac8388922c.png)
4. Open your quest book, right click the problematic quest, and click Complete Instantly. Choose yes
![image](https://user-images.githubusercontent.com/17010632/190612803-6b13d272-adc1-4712-8f3b-29050527b8c0.png)
5. To go back to normal quest mode, type `/ftbquests editing_mode` again
6. To go back to a normal world without LAN, simply exit your world and re-enter it

This works for any quest that you encounter a similar issue with, but also in other modpacks with FTB Quests, so remember it! :)

You can leave this opened until you finish playing haha (which could be a long time, no worries!), if you encounter other issues let me know through here

**Comment by manmaed** [comment]
@aaronhowser1 any word on this has this been fixed
this will auto close in 2 weeks if no response

**Comment by aaronhowser1** [comment]
It has not been
