### ISSUE TITLE
[Bug]: [Reap Mod]: Incompatibly with to plants 

### ISSUE THREAD

**Issue by ErdnusBuddha** [FTBTeam/FTB-Modpack-Issues#1328]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

I have tested which plants can be harvested with right click [Reap Mod] and I noticed that Magebloom seed [Ars Nouveau] and Flax seeds [Supplementaries] cannot be harvested this way.

### Steps to reproduce

1. Get Flax seeds, Magebloom seed 
2. grow them 
3. try to harvest them with rightclick

### Expected behaviour

The flax seeds should dropp 1x flax (& 1-2 flax seeds). 
The magebloom seed should dropp  1x Magebloom (& 1-2 seeds)

### Additional information

i am not sure if this is the kind of buggs that should be sent in here

**Comment by Raidobw2** [comment]
Reap only does vanilla crops I think. Maybe we can find another mod that does right clicking harvesting to add the missing crops to it, Quark can do it, or XPFromHarvest

**Comment by Saereth** [comment]
quark wasnt available at the time but is now in the pack so that should cover it in the update
