### ISSUE TITLE
[Bug]: FTB Presents Stoneblock 2 : Stuck at Downloading FTB files... 84%

### ISSUE THREAD

**Issue by josh-chez-sosh** [FTBTeam/FTB-Modpack-Issues#1329]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

all

### Log Files

downloader.js:23 Skipping {version: '2.6.3', path: 'C:\Users\OurElectricity\AppData\Roaming\gdlauncher…eblock 2\mods\ExtraCells-1.12.2-2.6.3aNIGHTLY.jar', sha1: 'd778c5043fd6c7822d4b1210eb190a41fc18d7d1', size: 2573646, tags: Array(0), …}](actions.js:2289 

Error: ENOENT: no such file or directory, open 'C:\Users\OurElectricity\AppData\Roaming\gdlauncher_next\instances\FTB Presents Stoneblock 2\config.json')](actions.js:2289 Error: ENOENT: no such file or directory, open 'C:\Users\OurElectricity\AppData\Roaming\gdlauncher_next\instances\FTB Presents Stoneblock 2\config.json')

[...]

skipping 
version: '2.6.3', path: 'C:\Users\OurElectricity\AppData\Roaming\gdlauncher…eblock 2\mods\ExtraCells-1.12.2-2.6.3aNIGHTLY.jar', sha1: 'd778c5043fd6c7822d4b1210eb190a41fc18d7d1', size: 2573646, tags: Array(0), …}

^^ this was like 50 times 

### Describe the bug

Installation stuck at "Downloading FTB files ... 84%"

### Steps to reproduce

Install the modpack on the default location

### Expected behaviour

installing the modpack

### Screenshots

![image](https://user-images.githubusercontent.com/63064323/190684719-a0de7fbd-3c53-43a1-abc5-0fc65a2331ec.png)

### Additional information

Thanks :D

**Comment by Raidobw2** [comment]
Hello, have you tested if it works with the FTB App?

**Comment by josh-chez-sosh** [comment]
It does work with the FTB App, thank you

**Comment by Raidobw2** [comment]
Awesome, it might have been an issue with the gdlauncher then.
The version of stoneblock2 is obsolete on curseforge, but on the ftb app it's the latest 1.22.0. Have fun then and i'll close this since it's solved
