### ISSUE TITLE
[Bug]: Sudden TPS lag from WYMLRandom.get() exceptions

### ISSUE THREAD

**Issue by legitswitch** [FTBTeam/FTB-Modpack-Issues#133]
### Modpack

FTB OceanBlock

### Modpack version

1.3

### Log Files

https://spark.lucko.me/NPNruWhWhB

### Describe the bug

TPS has decreased quite a bit due to WYML mod encountering exceptions upon calling the WYMLRandom.get() method.

### Steps to reproduce

Not sure, I think I noticed it started happening after using inControl mod to block spawns of squids, then removing it.

### Expected behaviour

TPS would be higher for the amount of players but now is noticeably lower.

### Screenshots

![image](https://user-images.githubusercontent.com/88232383/137349344-aecec52f-f0b4-4f12-94b8-62f37513e8a4.png)

### Additional information
My WYML config settings: 
https://hastebin.com/ofiyicipat.json

Java method being called:
https://github.com/ThePaul-T/WYML/blob/2185c3905ca860235289ad49abf7713fe257a087/common/src/main/java/net/creeperhost/wyml/WYMLRandom.java#L28

Issue on WYML GitHub:
https://github.com/ThePaul-T/WYML/issues/5

**Comment by Sunekaer** [comment]
https://github.com/ThePaul-T/WYML/issues/5

**Comment by Sunekaer** [comment]
Should be fixed in 1.4.0/1.4.1
