### ISSUE TITLE
[Suggestion]: Replace reference to transphobic joke in second quest of Academy 1.16

### ISSUE THREAD

**Issue by lempamo** [FTBTeam/FTB-Modpack-Issues#1332]
### Modpack

FTB Academy 1.16

### Is your suggestion related to a problem? Please describe.

The second quest in the modpack, "I'm a Lumberjack and I'm OK", is a reference to the lumberjack skit from Monty Python. In said skit, the titular lumberjack comes out as a trans woman over the course of the song, while the people around react in confusion and disgust. This sort of transphobia really should not be referenced as it makes myself (and other trans individuals) uncomfortable.

### Mod suggestion

I request that the name of the quest be changed to something that isn't a reference to a transphobic comedy sketch.

**Comment by juneaubelanger** [comment]
if this makes you incomfortable you should get help

**Comment by aaronhowser1** [comment]
When making the quest, I hadn't ever actually watched the Monty Python skit, and didn't know until now that it had transphobic content. The reference will be removed in the next update, thank you for bringing this to our attention
