### ISSUE TITLE
[Bug]: Hammer not working

### ISSUE THREAD

**Issue by Shramble** [FTBTeam/FTB-Modpack-Issues#1340]
### Modpack

FTB revelations 

### Modpack version

3.6.0

### Describe the bug

Hammer not working, tried all of them, unable to make plates
Tried all hammere, all ingots, none work

### Steps to reproduce

1.Go to FTB revelations
2.Take any hammer and any ingot
3. Place into crafting 

### Expected behaviour

Crafting of plates

**Comment by Raidobw2** [comment]
See #1289, you can downgrade the UniDict mod to https://www.curseforge.com/minecraft/mc-mods/unidict/files/3268501. You'll need to delete the old file, in the `mods` folder it's called `UniDict-1.12.2-3.0.10.jar`

I'll close this to avoid tracking duplicate issues, but thank you for reporting!
