### ISSUE TITLE
[Suggestion]: Maybe _Creosote oil_ and _Creosote oil_ should be equivalent

### ISSUE THREAD

**Issue by pson** [FTBTeam/FTB-Modpack-Issues#1342]
### Modpack

Direwolf20 1.18

### Is your suggestion related to a problem? Please describe.

I wanted to auto-craft Treated wood, and I had quite a lot of _Creosote oil_ (Immersive engineering), but when I made the recipe it was for _Creosote oil bucket_ (Thermal series). It took me quite a while to realize that _Creosote oil_ (IE) is not the same as _Creosote oil_ (TS), maybe they should be equivalent?

**Comment by TheonlyTazz** [comment]
![grafik](https://i.imgur.com/wEaXp8z.gif) both are interchangable in the recipe for treated wood,

when setting up the autocrafting recipes, u can replace the bucket manually with the creosote u have
