### ISSUE TITLE
[Bug]: Breaking a Roost deletes it's inventory

### ISSUE THREAD

**Issue by Mephie** [FTBTeam/FTB-Modpack-Issues#1345]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

Breaking a Roost with the pickaxe deletes its inventory.

### Steps to reproduce

Place roost.
Add chickens
Let slots fill
Ultimine your roost wall... lose a couple days.

### Expected behaviour

Chickens and loot fall to ground as entities.

**Comment by Raidobw2** [comment]
Thanks for reporting!

https://github.com/CreeperHost/Chickens/issues/16

There currently is no fix for 1.19, but there is one for 1.19.2. Once the pack jumps to 1.19.2, this will be fixed
