### ISSUE TITLE
[Bug]: Pipez / Chickens interactions

### ISSUE THREAD

**Issue by Mephie** [FTBTeam/FTB-Modpack-Issues#1346]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

Pipez has access to insert into all slots of Chicken Breeders.

Issues:
Setup A: Item Pipez pulling from breeder and inserting into another side.
If seeds runs out, pipez will take product chickens and shove them into the food slot.
They will be consumed as food for breeding.

Setup B: Item Pipez taking seed from a seed chest and populating a bunch of breeders.
Pipez will simply fill all slots with seeds, Food, Input Chickens, Product Chickens. everything.
Will corrupt world and crash on startup.

### Steps to reproduce

See above

### Expected behaviour

Seed slot should only accept seeds.

### Additional information

[crash-2022-09-25_18.26.58-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9642005/crash-2022-09-25_18.26.58-server.txt)

**Comment by Raidobw2** [comment]
I'll close this in favor of keeping https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1347. You can edit your messages with the "..." button at the right:
![image](https://user-images.githubusercontent.com/17010632/192462585-0917628a-7d74-4eb0-a49d-b599662e1eff.png)
