### ISSUE TITLE
[Bug]: server stopped suddenly and not turning on.

### ISSUE THREAD

**Issue by chandrix** [FTBTeam/FTB-Modpack-Issues#1348]
### Modpack

FTB stoneblock 2

### Modpack version

1.22.0

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9643045/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9643046/latest.log)

### Describe the bug

we set up the server and it worked fine for 2 days and then suddenly the server stopped when playing and the console shows this error 

"/chpregen current|dimID xDiameter zDiameter [chunksPerTick, default 5] [preventJoin, default true]
[04:52:00] [Server thread/INFO] [minecraft/DedicatedServer]: - OR -
[04:52:00] [Server thread/INFO] [minecraft/DedicatedServer]: /chpregen current|dimID xDiameter zDiameter xStartChunk zStartChunk [chunksPerTick, default 5] [preventJoin, default true]
[04:52:00] [Server thread/INFO] [minecraft/DedicatedServer]: - OR -"

### Steps to reproduce

Dunno how to reproduce as the server is not even turning on

### Expected behaviour

server should turn on but its not

**Comment by Raidobw2** [comment]
Hey, check directly in your server folder for a file named `pregenData.json`. If there is one, you can delete it. It's a pregeneration feature from the MineTogether mod, and it looks like there might be something odd going on with it on your server

Let me know if your server managed to boot up properly after that change in the files
