### ISSUE TITLE
[Bug]: [Extreme Reaktors]: Fuel Rod XRay

### ISSUE THREAD

**Issue by ErdnusBuddha** [FTBTeam/FTB-Modpack-Issues#1352]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

If you place a Reaktor Fuel Rod next to one of the folwing Blocks, you can see through solid Blocks:
- all Reactor Blocks except Reactor Casing and Glass

### Steps to reproduce

1. Get a Reactor Fuel Rod and the block's you want to test
2. Place place both Blocks next to each other 
3. look through the Fuel Rod 

### Expected behaviour

You Sould see the Block behind 

### Screenshots

![Bug reaktor](https://user-images.githubusercontent.com/113529444/192522449-6eb7d89c-ba99-4028-a649-8e38aef3a25f.png)

### Additional information

I have only tested the blocks on the screenshot, maybe there are some more

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/216846970-d87998ca-bca3-4f57-8979-6a359992dc68.png)
Looks like its resolved in the update, look for ftb 2.0 this month
