### ISSUE TITLE
[Bug]: infinity evolved crashes after launching single player world

### ISSUE THREAD

**Issue by Hello6122021** [FTBTeam/FTB-Modpack-Issues#1353]
### Modpack

FTB infinity evolved

### Modpack version

1.7.10

### Log Files

[crash-2022-09-28_10.16.08-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9662971/crash-2022-09-28_10.16.08-server.txt)

### Describe the bug

Hello, I have a problem with FTB infinity Evolved. When I started the game, everything was normal until the world loaded (single-player) and my game crashed. Before the world crashes, it shows the message 'server is closed'. I tried to change my spawn position and also gave the game more Ram (about 7,5gb). Still, it does not work. 

### Steps to reproduce

1. Load up infinity evolved on the FTB Launcher 
2. create a single-player world 
3. find bugged chunk/block(idk)
4. server closed message is shown
5. Minecraft crashes

### Expected behaviour

I can play my world without minecraft crashing

**Comment by Raidobw2** [comment]
Hi, is this on a fresh new world? Have you tried reinstalling the modpack on your client and the server as well?

I've found an old post similar to your crash at https://www.reddit.com/r/FeedTheBeastCrashes/comments/3dwiqo/ftb_infinity_crashing/, although this one refers to an IC2 error while your crash does not.
You can try removing IC2, Botania, or BiomesOPlenty to see which one caused your crash -- I currently don't really know from looking at the crash. I'd recommend to copy your world however to keep it if you have a base in it, until we can solve this.

There's a chance you get a "better" crash log after removing one of those mods, which might help more locating the issue. Let me know if anything changes after removing some mods, and make sure to post your next crash logs here! 🙂

**Comment by Hello6122021** [comment]
I've been playing a bit on this world and also tried to reinstall the mod pack. I don't know how to reinstall server. Although thanks for help.

**Comment by Hello6122021** [comment]
[crash-2022-09-29_13.51.00-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9674313/crash-2022-09-29_13.51.00-server.txt)

**Comment by Hello6122021** [comment]
> Hi, is this on a fresh new world? Have you tried reinstalling the modpack on your client and the server as well?
> 
> I've found an old post similar to your crash at https://www.reddit.com/r/FeedTheBeastCrashes/comments/3dwiqo/ftb_infinity_crashing/, although this one refers to an IC2 error while your crash does not. You can try removing IC2, Botania, or BiomesOPlenty to see which one caused your crash -- I currently don't really know from looking at the crash. I'd recommend to copy your world however to keep it if you have a base in it, until we can solve this.
> 
> There's a chance you get a "better" crash log after removing one of those mods, which might help more locating the issue. Let me know if anything changes after removing some mods, and make sure to post your next crash logs here! 🙂


I've been playing a bit on this world and also tried to reinstall the mod pack. I don't know how to reinstall server. Although thanks for help.

**Comment by Hello6122021** [comment]
> 

I tried starting the mod pack without botanic and Ic2, but it still does not work. Maybe this crash report will help:
[crash-2022-09-29_13.51.00-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9674313/crash-2022-09-29_13.51.00-server.txt)

**Comment by Raidobw2** [comment]
Hmm I see. It's still the same error but there's a second set of coordinates. The first coordinates were `(702,10,-678)` and the second ones `(699,4,-676)`. So the error seems to have happened close to the same location, possibly something around that area is placed and causing issues, or BiomesOPlenty is causing the problem since it's also in the crash again.

If you can manage to put your world here, I can look into it further and possibly fix it as well. You can use Google Drive or anything you want to share it.

Alternatively, if you want you can remove BiomesOPlenty and take a copy of the world to your singleplayer worlds. Then enter that world, and go around those 2 locations I pointed earlier.

**Comment by Hello6122021** [comment]
> Hmm I see. It's still the same error but there's a second set of coordinates. The first coordinates were `(702,10,-678)` and the second ones `(699,4,-676)`. So the error seems to have happened close to the same location, possibly something around that area is placed and causing issues, or BiomesOPlenty is causing the problem since it's also in the crash again.
> 
> If you can manage to put your world here, I can look into it further and possibly fix it as well. You can use Google Drive or anything you want to share it.
> 
> Alternatively, if you want you can remove BiomesOPlenty and take a copy of the world to your singleplayer worlds. Then enter that world, and go around those 2 locations I pointed earlier.
I tried to join the world, and it still crashes, even without BiomesOPlenty. This is the link for the single-player world:
https://drive.google.com/drive/folders/18LX5PKJZX41XibWWgaSSASnHObrjNyET?usp=sharing

**Comment by Hello6122021** [comment]
I tried to join the world, and it still crashes, even without BiomesOPlenty. This is the link for the single-player world:
https://drive.google.com/drive/folders/18LX5PKJZX41XibWWgaSSASnHObrjNyET?usp=sharing

**Comment by Hello6122021** [comment]
> I tried to join the world, and it still crashes, even without BiomesOPlenty. This is the link for the single-player world:
> https://drive.google.com/drive/folders/18LX5PKJZX41XibWWgaSSASnHObrjNyET?usp=sharing

I tried to join the world, and it still crashes, even without BiomesOPlenty. This is the link for the single-player world:
https://drive.google.com/drive/folders/18LX5PKJZX41XibWWgaSSASnHObrjNyET?usp=sharing

**Comment by Hello6122021** [comment]
> 

I tried to join the world, and it still crashes, even without BiomesOPlenty. This is the link for the single-player world:
https://drive.google.com/drive/folders/18LX5PKJZX41XibWWgaSSASnHObrjNyET?usp=sharing

**Comment by Hello6122021** [comment]
> Hmm I see. It's still the same error but there's a second set of coordinates. The first coordinates were `(702,10,-678)` and the second ones `(699,4,-676)`. So the error seems to have happened close to the same location, possibly something around that area is placed and causing issues, or BiomesOPlenty is causing the problem since it's also in the crash again.
> 
> If you can manage to put your world here, I can look into it further and possibly fix it as well. You can use Google Drive or anything you want to share it.
> 
> Alternatively, if you want you can remove BiomesOPlenty and take a copy of the world to your singleplayer worlds. Then enter that world, and go around those 2 locations I pointed earlier.

I tried to join the world, and it still crashes, even without BiomesOPlenty. This is the link for the single-player world:
https://drive.google.com/drive/folders/18LX5PKJZX41XibWWgaSSASnHObrjNyET?usp=sharing

**Comment by Raidobw2** [comment]
Thanks for the feedback, I have tried loading the world and seeing if it crashes, and on my side it never crashes (going to the coordinates I mentioned). I'm not sure what to do to make it crash.

Just confirming from your previous message, are you able to load the world in singleplayer properly?

As for reinstalling the server, first, you should keep the world files safe somewhere on your PC. Assuming you are renting a server from a hosting company, you would need to ask them to reinstall the server.
If you are hosting the server yourself, you can use the files from the Feed The Beast website: https://www.feed-the-beast.com/modpack/23_ftb_infinity_evolved_1_7/server-files.

I've removed the problematic chunk (43x, -43z) from the region file, what you can try to do is to put that file into a copy of your save and see if the game can regenerate it. I don't think you had anything in that chunk, it was far from your base.
[r.1.-2.mca.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9691423/r.1.-2.mca.txt)

Make sure you use a copy of your world, just another reminder.

Simply remove the `.txt` file extension from it (it will then be named `r.1.-2.mca`) and then overwrite the file in your `saves/world/region` folder with it. Then try to load the save again and let me know.

**Comment by Hello6122021** [comment]
I think u misunderstood something, this world has never been hosted on a server. I just played single-player, When I download the file you sent there is no file extension it is just named "r.1.-2.mca". Although, thanks for help by now.

**Comment by Raidobw2** [comment]
Ahh I see, yes I misunderstood thanks for clarifying. If there is no file extension you will need to enable them in Windows in the File Explorer. In the "View" tab is where you can enable extensions.

After you overwrite the region file (.mca) from my previous instructions, let me know if that works
