### ISSUE TITLE
[Bug]: Tired to read NBT tag that was to big

### ISSUE THREAD

**Issue by Spacecrafter** [FTBTeam/FTB-Modpack-Issues#1354]
### Modpack

FTB Oceanblock

### Modpack version

1.15.1/1.12.0

### Log Files

Logs from Host:
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9664578/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9664579/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9664580/latest.log)

Logs from joining Player:
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9664587/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9664589/latest.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9664590/console.log)

### Describe the bug

When my friends try to join the LAN session, they get the following error:
![unknown](https://user-images.githubusercontent.com/58488507/192771163-57b3a970-d16d-4e11-a9e5-1a4931a28b09.png)
The value of the bytes are always different and we tried everything we could find on the internet. Clearing inventory, destroying chunks ... 
But we cant find  the problem. When we load a backup it seems to work for some time but then the same problem happens again.

### Steps to reproduce

1. Host world to LAN
2. Try joining world with another account

### Expected behaviour

People should be joining properly

### Additional information

Maybe somone has an idea, but our hopes are vrey low ^^

**Comment by Raidobw2** [comment]
Hi, for the person having this issue, try this:
1. Update your sound drivers from the manufacturer. Most likely from the Intel site
2. Open the folder at `%localappdata%\.ftba\bin\versions` (paste it into the address bar of the File Explorer and press Enter)
3. Delete the `1.16.5-forge-36.2.39` folder if you are playing OceanBlock 1.15.1
4. Assuming you don't have any worlds, reinstall OceanBlock 1.15.1
5. Start the game and join the server
6. Let me know if it crashes still

I suspect the audio libraries to be corrupted maybe, which should be contained in that `1.16.5-forge-36.2.39` folder (called OpenAL).

Also let me know if you are using Flux Networks or Powah cables in your base, I know of some issues with them.

Thanks!

**Comment by Spacecrafter** [comment]
Thanks for your message in the first place.

Though we just found the Problem.

We had an ressource production with FTB Sluice Hammers and Mekanism logistical transporter. The auto hammers save their output, and there were quite a few thousand items stored in the hammers, you could see in the tooltip of the block. So the transporter tried to empty the hammer but the destination was full so tried to put it back but this didn´t work so there were many items in the transporter. See in the following screenshot:

![Screenshot_695](https://user-images.githubusercontent.com/58488507/192865598-67d571f4-3e7f-4981-8841-b33c0c0f14fd.png)

**Comment by Raidobw2** [comment]
I see, that's a lot of blocks indeed. Auto hammers can actually auto input/output, try putting your drawers directly adjacent to it and see if that works better
