### ISSUE TITLE
[Bug]: Can't use Resourcepacks

### ISSUE THREAD

**Issue by virtualgurel** [FTBTeam/FTB-Modpack-Issues#1356]
### Modpack

FTB Inferno

### Modpack version

1.0.0

### Log Files

https://mclo.gs/o3QUfU6

### Describe the bug

I'm trying to activate Latvian's Slightly Improved Font and Updated_Engineering_v1.5.1 resourcepacks. But game crashed while loading resourcepacks. I tried to active them separatly but it didn't work either.

### Steps to reproduce

1. Activate Updated_Engineering_v1.5.1 resourcepack
2. Game crashed.
3. Download and activate Sligtly Improved Font
4. Game crashed
5. Try to activate both at the same time
6. Game crashed

### Expected behaviour

Game doesn't crash.

### Additional information

I didn't add any other mod or changed the modpack any way. I'm using FTB App. Given RAM: 7.5 GB

**Comment by Saereth** [comment]
Hexerei bug, you can temporarily disable hexerei then set your textures and then relaunch with hexerei back.  Dev is aware of it and we will update once a fix is ready. https://github.com/JoeFoxe/Hexerei-1.18/issues/59

**Comment by virtualgurel** [comment]
Thanks, I can do that.

**Comment by Raidobw2** [comment]
Other workaround for those that still have the issue / get an error still:
1. Move mods outside of the `mods` folder temporarily
2. Start the game, enable the texture pack(s) you wanted to add in Main Menu and close game
3. Put the mods back into the `mods` folder
4. Start game, should work fine now
