### ISSUE TITLE
[Bug]: Infinite Gold in FTB Inferno

### ISSUE THREAD

**Issue by Hystings** [FTBTeam/FTB-Modpack-Issues#1363]
### Modpack

FTB Inferno

### Modpack version

1.0

### Describe the bug

The player can convert Carrots and Lava into Gold using the smeltery.

### Steps to reproduce

1. Using a smeltery, melt down 1 golden carrot. You will recieve 8 golden nuggets.
2. Pour gold onto a carrot, consuming 1 nugget of gold.
3. You are left with 7 nuggets of gold in the Smeltery, meaning Carrots and Lava can be used to infinitely generate gold.

### Expected behaviour

The smeltery should either melt carrots down into 1 nugget, or the cast should take 8 nuggets to make a golden carrot.

**Comment by legitswitch** [comment]
Open kubejs\server_scripts\mods\tinkers.js

Change the amount of gold needed to 80, as shown below.

`    event.custom({
        "type": "tconstruct:casting_table",
        "cast": {
            "item": "minecraft:carrot"
        },
        "cast_consumed": true,
        "fluid": {
            "tag": "forge:molten_gold",
            "amount": 80
        },
        "result": "minecraft:golden_carrot",
        "cooling_time": 74
    }).id('inferno:tinkercarrot')`

**Comment by Saereth** [comment]
Golden carrots can no longer be melted in the smelter as of next update
