### ISSUE TITLE
[Bug]: Crash in main menu due to Fancymenu

### ISSUE THREAD

**Issue by rblokker** [FTBTeam/FTB-Modpack-Issues#1364]
### Modpack

FTB Inferno

### Modpack version

1.0.0

### Log Files

[crash-2022-09-30_19.46.16-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9686941/crash-2022-09-30_19.46.16-client.txt)

### Describe the bug

Modpack loads fine.
When clicking on a button on the main menu, the game crashes.
When i remove the mod fancymenu and the extension, I am able to create a world and play.

### Steps to reproduce

1. Start the game
2. Click on "Single player" in the main menu

### Expected behaviour

Go to the menu to play/create a single player world

**Comment by Raidobw2** [comment]
Are you using a resourcepack and have you tried reinstalling?
Could be linked to https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1356

**Comment by Saereth** [comment]
yeah this looks similar to the resource pack reloading crash. which button is crashing for you? can you possibly zip your kubejs folder and provide a link to it for me? thanks

**Comment by rblokker** [comment]
Downloaded 1.0.1 today, fixt the issue for me.
