### ISSUE TITLE
[Bug]: Random(?) crashes (ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by Einhornyordle** [FTBTeam/FTB-Modpack-Issues#1365]
### Modpack

FTB Inferno

### Modpack version

1.0.0

### Log Files

Crash Report: https://paste.myftb.de/sucexirifi.properties
Log: https://paste.atlauncher.com/view/abaf3580-82d7-49c0-8250-643bdfeacbc6

### Describe the bug

The game seems to simply crash after some time

### Steps to reproduce

Just play FTB Inferno for some time, at some point the game will freeze for a few seconds until it closes.

### Expected behaviour

The game won't crash

### Additional information

I've set all graphic settings to fancy and enabled the shader that comes with the pack if that matters. If you tell me where to find the settings file I can send it here as well so you can try playing with the same settings as I do.

**Comment by Raidobw2** [comment]
Do you have Immersive Engineering machines yet? Thanks in advance

**Comment by Raidobw2** [comment]
Oh, I just realized sorry, that is the same crash as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1357. I recommend subscribing to the other issue to get updates on the situation. I'll close this to avoid duplicates for our tracking, but you can reply on the other issue if you want, we'll appreciate it and thanks!
