### ISSUE TITLE
[Bug]: kubejs error & warnings everytime I join my server

### ISSUE THREAD

**Issue by eb40957522** [FTBTeam/FTB-Modpack-Issues#1368]
### Modpack

FTB Inferno

### Modpack version

1.0.0

### Log Files

[server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9690752/server.txt)

### Describe the bug

kubejs errors every time I join my server. 

### Steps to reproduce

Join server

### Expected behaviour

No errors

### Screenshots

![dllhost_iKyxxP4Jry](https://user-images.githubusercontent.com/105841074/193418897-9d86be48-d748-4218-9782-ed1b47216096.png)

### Additional information

Server running on ubuntu20 server VM. Installed using official ftb linux installer

**Comment by Raidobw2** [comment]
Can you compare your `mods`, `config` and `kubejs` folders on your client/server? Normally they should be the same, but I'd recommend verifying in case a file is missing (or a script in the case of kubejs).

For instance make sure emojiful is installed on both ends. Also, you can copy-paste those folders from your client into your server to make sure they are the same.

Let me know if that solved it, otherwise that sounds like an issue with the script

**Comment by localzuk** [comment]
Seeing this exact same issue on a fresh install of server and client.

Copying the 3 folders from client to server does not fix this - that just causes the server to crash within seconds of trying to start it instead.

Looking at it, emojiful does not get installed by the server installer.

Putting emojiful on the server does not fix the error either. logs/kubejs/server.txt still has the line

`16:34:14] [ERR  ] Error occurred while handling event 'recipes': TypeError: Cannot call method "emoji_recipe" of undefined (server_scripts:emojiful.js#3)`

There's also the following, which is a warning, but error nontheless

`[16:34:15] [WARN ] Error creating recipe naturesaura:calling_spirit[kubejs:shaped]: {"type":"kubejs:shaped","result":{"item":"naturesaura:calling_spirit","count":3},"pattern":[" S ",""," N "],"key":{"S":{"item":"naturesaura:aura_bottle","type":"forge:nbt","nbt":"{stored_type:\"naturesaura:overworld\"}"},"N":{"item":"naturesaura:aura_bottle","type":"forge:nbt","nbt":"{stored_type:\"naturesaura:nether\"}"},"T":{"item":"naturesaura:tainted_gold"},"I":{"item":"naturesaura:infused_iron"},"G":{"item":"inferno:willinfusedsource"}}}: com.google.gson.JsonSyntaxException: Invalid pattern: each row must be the same width`

This is a bug with the server installer, not a general support request.

**Comment by Saereth** [comment]
please zip your server mod and kubejs folders so I can compare, seems like something isnt working right with the server install. 

You can manually patch this by using the kubejs and mods folder from the client and removing the following clientside mods:
      "mods/auudio_forge_1.0.3_MC_1.18-1.18.2.jar",
      "mods/beehive-tooltips-forge-1.4.2.jar",
      "mods/oculus-mc1.18.2-1.2.5a.jar",
      "mods/DarkModeEverywhere-1.18.1-1.0.2.jar",
      "mods/Ding-1.18-1.3.0.jar",
      "mods/extremesoundmuffler-3.29_forge-1.18.2.jar",
      "mods/fancymenu_forge_2.12.2_MC_1.18.2.jar",
      "mods/fm_audio_extension_forge_1.1.1_MC_1.18-1.18.2.jar",
      "mods/jumpoverfences-1.18-1.0.1.jar",
      "mods/lucent-1.18.2-1.2.2.jar",
      "mods/ReAuth-1.18-Forge-4.0.4.jar",
      "mods/rubidium-0.5.3a.jar",
      "mods/milk_of_magnesium-1.18.2_v1.3.4.jar",
      "mods/torohealth-1.18-forge-2.jar"

this is just a work around however, we will continue to investigate this

**Comment by localzuk** [comment]
Here's a link to the 2 folders zipped up from a fresh install from the server installer.

https://1drv.ms/u/s!Ah_oP3v7Glnv9lnNhBUWEYjGmQY8?e=mAuz1C

**Comment by Saereth** [comment]
yeah that mod folder is missing 11 mods, that'd be the problem

**Comment by Saereth** [comment]
For some reason the server install isnt sending the emojiful mod, I've opened a support request with our internal team to look into it

**Comment by localzuk** [comment]
OK, so putting both the mods folder (minus those mods listed) and the kubejs folder on the server caused a crash - complaining about ftb-hide.

So, instead, I just put emojiful and the kubejs folder, and it fixed the errors.

**Comment by Saereth** [comment]
ok yeah and our internal team has identified the issue and should be able to resolve it soon for future downloads
