### ISSUE TITLE
[Suggestions]: Speed multiplier for all treated wood plank variants

### ISSUE THREAD

**Issue by MisterZam** [FTBTeam/FTB-Modpack-Issues#1369]
### Modpack

FTB Inferno

### Is your suggestion related to a problem? Please describe.

We all know treated wood planks always look awesome to any given situation. Making a pathway using treated wood planks will make the whole colony aesthetic pleasing period. But if added with speed multiplier, it will make it aesthetically zoomies! 

### Mod suggestion

N/A

**Comment by MisterZam** [comment]
Hey adding speed multiplier to hempcrete too would be nice thanks devs 👯

**Comment by Saereth** [comment]
assigned myself and aaron, one of us will most likely get to it before 1.0.2
