### ISSUE TITLE
[Bug]: Permanent Nightvision on 1.0.1

### ISSUE THREAD

**Issue by Novasiri** [FTBTeam/FTB-Modpack-Issues#1370]
### Modpack

FTB Inferno

### Modpack version

1.0.1

### Describe the bug

On launching the world after updating from 1.0.0, the entire world is incredibly bright compared to prior. After eating a golden carrot, which gives night vision for 5 minuets, there's no visible change in light levels. No equipment on.

However, once the effect wears off, the world darkens temporarily before instantly brightening up again. There is no active effect on the character, and restarting the game doesn't darken the world at all, even when playing on Moody.

### Steps to reproduce

1. Enter into a world on 1.0.1 
2. Look around, notice how much brighter it is for some reason.
3. Eat a Golden Carrot, see no difference.
4. Wait for the effect to wear out to see the world go back to it's normal brightness.
5. Watch as it snaps back to being insanely bright again.

### Expected behaviour

Not having permanent night vision without the buff. It should NOT be this bright.

### Screenshots

![2022-10-02_04 13 58](https://user-images.githubusercontent.com/78075114/193454101-97caf7a4-fd0d-4f97-b870-a0e0aa60dd76.png)
![2022-10-02_05 24 02](https://user-images.githubusercontent.com/78075114/193454102-b2cca675-6ff7-4efd-ab24-071e43305abe.png)

### Additional information

This only seemed to happen upon the update to 1.0.1.. Going back to 1.0.0 seems to fix the issue.

**Comment by Saereth** [comment]
no mods or scripts related to nightvision were changed in 1.0.1, can you show me your video settings for darkness and brightness settings? Does a relog change this?

**Comment by Novasiri** [comment]
The only settings I've changed was setting brightness to Moody. Everything else is default with the pack, including the shaders. I did the same thing in 1.0.0 and this didn't occur.

I'd like to once again state that switch back to 1.0.0 fixes this super-bright world back to being dark as it's meant to be. Also making a new world in 1.0.1 has the same issue, things are extremely bright (As well as spawning in the overworld before insta-tping to the Nether with no hub..?). Relogging does absolutely nothing.

![image](https://user-images.githubusercontent.com/78075114/193473246-3e89f07f-a375-4702-8f56-74608355dc55.png)

Shaders, nothings been touched by my hand.
![image](https://user-images.githubusercontent.com/78075114/193473258-7589ae59-a35e-4e86-aba5-9e0409c5a1ec.png)
![image](https://user-images.githubusercontent.com/78075114/193473264-78c31146-a560-494d-8c14-80ee2550a948.png)
![image](https://user-images.githubusercontent.com/78075114/193473287-6a442515-0f87-47ae-91dc-d4fe84f355c5.png)

**Comment by Saereth** [comment]
look under your quality settings in video for true darkness, what is that set at

**Comment by Novasiri** [comment]
That is what it's set to.

![image](https://user-images.githubusercontent.com/78075114/193474242-e26b2a14-6f4d-4f3a-b7b6-8c5c338c1aa7.png)

**Comment by Saereth** [comment]
I see, cave darkness should be set to dark in the shaders, the shader config should not be shipping with the pack though so it will be removed for the next update, you'll need to manually adjust yours. I was able to reproduce the issue by turning shaders off, giving myself 10s of night vision and I could see the difference, with shaders on the brightness stays the same with nv or not, which seems to be that cave brightness setting. Also dynamic handheld lighting should be off, lucent controls that for this pack.

**Comment by Novasiri** [comment]
Sounds good! I'll make the changes right now.
