### ISSUE TITLE
[Bug]: Infernal Resources resource pack marked as being out of date

### ISSUE THREAD

**Issue by localzuk** [FTBTeam/FTB-Modpack-Issues#1371]
### Modpack

FTB Inferno

### Modpack version

1.0.1

### Describe the bug

Infernal Resources.zip resource pack, shipped with the modpack, is marked as being for an older version of Minecraft. It appears to still work with the pack though if you select it.

### Steps to reproduce

1. Go to Resource Packs
2. Look at the resource pack

### Expected behaviour

Should be able to see the resource pack as valid for the modpack

### Screenshots

![image](https://user-images.githubusercontent.com/998988/193462751-b95fc53c-8425-4a42-ac14-b3b9242f78f2.png)

**Comment by Saereth** [comment]
this should even be shipping with the pack, removed for next udpate
