### ISSUE TITLE
[Bug]: Minecolonies Stash

### ISSUE THREAD

**Issue by MisterZam** [FTBTeam/FTB-Modpack-Issues#1373]
### Modpack

FTB Inferno

### Modpack version

1.0.1

### Describe the bug

I think this is unintended but when you break the stash with items in it will drop nothing. All items inside will be voided. 

### Steps to reproduce

1. Put down the stash
2. Put any item inside
3. Break the stash
4. No items drop. Only the stash

### Expected behaviour

The stash and all the items inside will be dropped

**Comment by Saereth** [comment]
Opened a bug report with minecolonies, this would impact DW20 1.18 as well currently
https://github.com/ldtteam/minecolonies/issues/8690
