### ISSUE TITLE
[Bug]: shulker in a shulker in a shulker.... unlimited number of times

### ISSUE THREAD

**Issue by NoPro17** [FTBTeam/FTB-Modpack-Issues#1374]
### Modpack

FTB Inferno

### Modpack version

1.0.1

### Describe the bug

You can auto pick-up shulker boxes into a satchel when you have auto pick-up enabled on a satchel. Unlimited inventory only dependent on how many shulker boxes you have but they seem common enough to allow for it

### Steps to reproduce

1. enable auto pick-up on satchel
2. mine shulker
3. place satchel inside of another shulker
4. repeat

### Expected behaviour

mined shulker goes into inventory

### Additional information

cant place a shulker into another shulker or satchel from your inventory but you can place satchels into a shulker which is what lead me to find this

**Comment by tyler489** [comment]
This applies to most portable storages, Like i can place a shulker inside a backpack inside a me drive, inside a shulker, inside a satchel. I wouldn't recommend it, but you could do it.

**Comment by Raidobw2** [comment]
For dev: iirc Thermal has a server side config for backlisting items into satchels (e.g. shulker box)

**Comment by Saereth** [comment]
eh there's a bunch of inventory recursions you can do here, its fine, just remember if you nest too deeply you can run into issues with corrupting your player data. There are limited bag options in this pack so nesting is encouraged within reason
