### ISSUE TITLE
[Bug]: MineColonies & Capsules don't align.

### ISSUE THREAD

**Issue by TRoberts1001** [FTBTeam/FTB-Modpack-Issues#1375]
### Modpack

FTB Inferno

### Modpack version

1.0.1

### Describe the bug

The capsules granted by the quest system allow you to build colony buildings on the bedrock ceiling of the Nether, however it seems that these capsules are incomplete. EX: the Town hall appears to be missing 2 netherack, and the builders hut has an entire row and column of floor blocks missing. This is an issue that once used becomes unfixable as bedrock cannot be broken, rendering the capsules wasted and useless, and many buildings just sitting around unused.

### Steps to reproduce

1. Accept Quest rewards for creating town hall/builders hut
2. throw capsule where building is desired
3. break deepslate block and place colony block with correct orientation
4. building fences are placed, and colony block does not recognize the completed build around itself.

### Expected behaviour

The capsule will create a fully complete colony building ready to use.

### Screenshots

Examples of the placed blocks, right, and the single row of unplaced blocks according to the builders hut colony block.
![image](https://user-images.githubusercontent.com/15270472/193502807-46ab9538-8a7b-470e-ac3b-7a7a5e2ae419.png)
![image](https://user-images.githubusercontent.com/15270472/193502837-4fe21119-17c4-45ff-a52e-810fd556bb42.png)

**Comment by Saereth** [comment]
bedrock can be broken with the builders staff, and the capsules are ok minecolonies is just a bit weird with its requimements, it often doesnt actually need those blocks but either way the capsules are just there to provde you the majority of your starting point. 

Attack the bedrock with the building scepter and it will break for you so you can sculpt the land however you like.

**Comment by TRoberts1001** [comment]
I am still new to Mine Colonies. How do I get the colony blocks to complete despite missing certain blocks? EX my town hall is missing 2 netherack somewhere and I have absolutely no clue where.

**Comment by Saereth** [comment]
you just give the builder the netherrack and they complete it for you, you dont have to build it like a multiblock or anything like that your builders do that.

**Comment by TRoberts1001** [comment]
I just need to look up a Mine Colonies tutorial. Lol. No clue how to even set a builder if the builders hit isn't complete. But that one isn't too complicated to fix. 

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 3, 2022 at 6:25 PM, ***@***.***> wrote:   


you just give the builder the netherrack and they complete it for you, you dont have to build it like a multiblock or anything like that your builders do that.
