### ISSUE TITLE
[Bug]: Cant make warped chests anymore after update.

### ISSUE THREAD

**Issue by SoloGoose** [FTBTeam/FTB-Modpack-Issues#1378]
### Modpack

Inferno

### Modpack version

v1.0.1

### Describe the bug

Before the update we could make Warped chests from warped trees, after the update we cant. they make the old school chests instead

### Steps to reproduce

take warped planks and place in crafting grid to make a chest.

### Expected behaviour

I expected the chests to be green, instead of wood

**Comment by Saereth** [comment]
not a bug, the quark chest variants were always meant to be off, quark config just got reverted when the pack shipped. If you want to re-enable them yourselves you can without really negatively impacting the pack but I make no promises all the recipes are oredicted to work with the quark chests as development was always done with them off
