### ISSUE TITLE
[Bug]: Not able to go to Overworld by entering the normal nether portal described as the description in the quest

### ISSUE THREAD

**Issue by MAGXENO** [FTBTeam/FTB-Modpack-Issues#1379]
### Modpack

FTB Inferno

### Modpack version

1.0.1

### Describe the bug

After we defeated the Void Worm. The "Escape" quest said we can use the normal nether portal to go back to overworld. However, we are not able to escape and will teleport back to nether automatically.  Also, the "Escape" quest are not able completed even with a progression of 100%. Cannot to get 12 obsidians reward, either.  Can't begin the Avaritia mod. 

### Steps to reproduce

Finish all the pre-quest until "Escape"
Go into the nether portal 
Will be in the overworld for 1-2 sec and then teleport back to nether
With a message "No escape for you"
The quest with the 100% completed but not able to reward the 12 obsidians 

### Expected behaviour

Unlock Overworld stage automatically instead of type command myself

### Screenshots

![PX@6N2~K$PJU3SQ3D5JG`91](https://user-images.githubusercontent.com/60274372/193659038-f49473bd-2b29-4e0e-b83a-fcd8ad746c6b.png)
![8HW}RMQI 712U$CP}FI2JVD](https://user-images.githubusercontent.com/60274372/193659046-2edb07a9-adc2-42f2-81d4-0c81c0a603ee.png)

**Comment by Saereth** [comment]
duplicate https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1377
fixed in 1.0.2 update which will be out this week

**Comment by GoldenIsy** [comment]
I still have this Issue. The Quest stands at 100% but doesnt complete. After killing the worm I still get teleported back.
