### ISSUE TITLE
[Bug, Pipez]: Pipez keeps server crashing

### ISSUE THREAD

**Issue by saikokami** [FTBTeam/FTB-Modpack-Issues#138]
### Modpack

FTB OceanBlock

### Modpack version

1.3.0

### Describe the bug

I placed down a pipe (see step 1) and then the server keeps crashing.
I fixed it by removing the tesseract mod and then i was able to join and break the pipe.
Then i moved the mod back in and the server was running fine.
Console: http://prntscr.com/1waem3e
Please ask me if u have a question.

### Steps to reproduce

1. Placed Pipe: http://prntscr.com/1wadgpt
2. Error: http://prntscr.com/1wadhz3

### Expected behaviour

Server should not crash.

**Comment by saikokami** [comment]
> Crashlog please

https://pste.ch/binosofoye.pl

**Comment by Raidobw2** [comment]
Definitely a mod issue, Ticking Entity, maxhenkel.pipez X supermartijn642.tesseract.

I have not created a ticket on either side, Sunekaer, but I would aim towards pipez since they handle extraction logic.

**Comment by gdharron** [comment]
I also had this issue the other night where someone hooked up a pipez to a tesseract and it broke the world until I was able to rollback and determine from crash log it was na tesseract.

**Comment by Raidobw2** [comment]
Seems to be resolved, a mod update could be done, if not already up to date.
![image](https://user-images.githubusercontent.com/17010632/142719798-cc57f142-cf98-4297-8efe-f8e9ff2a8977.png)
