### ISSUE TITLE
[Bug]: Immersive Engineering progression blocked

### ISSUE THREAD

**Issue by NoPro17** [FTBTeam/FTB-Modpack-Issues#1382]
### Modpack

FTB Inferno

### Modpack version

1.0.1

### Describe the bug

mechanics hut does not produce the workbench required to progress into immersive engineering, the materials to build the workbench are in the inventory of the hut, have also tried with the items in the worker inventory

level one hut and the worker just paths around 2 sides of the hut
level two hut and the worker will enter but just wander around then go back to pathing the same two sides, for me this is east and south side

on checking on recipes within the hut i noticed that under recipes the ui shows architects cutter recipes

### Steps to reproduce

1. are no steps to reproduce

### Expected behaviour

workbench to be made

### Screenshots

![2022-10-03_16 36 29](https://user-images.githubusercontent.com/114872296/193705392-2bb8dbd3-40b3-4b88-9afd-882b884ebb57.png)

![2022-10-03_16 47 55](https://user-images.githubusercontent.com/114872296/193705438-13ef9d30-4c79-4d0f-81e0-89ab05ca3543.png)
![2022-10-03_16 48 33](https://user-images.githubusercontent.com/114872296/193705495-3e951012-e986-4403-a33f-8de3eb7b6a8c.png)

**Comment by KuroPeach** [comment]
You need to request the workbench in the mailbox

**Comment by Saereth** [comment]
What Kuro said, you need to request it from the postbox, I tested this in game to verify it is working, if you still have issues with it mfeel free to respond and I'll reopen
