### ISSUE TITLE
[Bug]: Missing Mobs for Soulshard config

### ISSUE THREAD

**Issue by jmg302** [FTBTeam/FTB-Modpack-Issues#1385]
### Modpack

FTB Inferno

### Modpack version

1.0.0

### Describe the bug

Soulshard mod Missing Ars Nouveau

Unable to destroy spawners or get souls from mobs

Checked soulshards.json and didn't find mobs listed.

### Steps to reproduce

Attempt to destroy Ars Nouveau Spawner and nothing will occur.

### Expected behaviour

Souls collected and Spawners destoryed

**Comment by Saereth** [comment]
what ars nouveau spawners are you talking about? There shouldnt be any

**Comment by Saereth** [comment]
No responspe, cant confirm/reproduce. Reopen if you can get a list of mobs you think need to be added

**Comment by Nagapito** [comment]
There is a wilden striker spawner in this structure 
![image](https://user-images.githubusercontent.com/4959346/197387672-2c09d0b8-5f08-4f25-b4d8-9ff0bb8d03e1.png)
More precisely here
![image](https://user-images.githubusercontent.com/4959346/197387696-d7394bbf-120a-4ef3-9265-b24023aea0f3.png)
