### ISSUE TITLE
[Bug]: When a player into the end, logging again, the kubejs reports an error. 

### ISSUE THREAD

**Issue by KuroPeach** [FTBTeam/FTB-Modpack-Issues#1386]
### Modpack

FTB Inferno

### Modpack version

1.0.1

### Describe the bug

When a player into the end, logging again, the kubejs reports an error, should it be getTags?

### Steps to reproduce

non

### Expected behaviour

fix it

### Screenshots

![image](https://user-images.githubusercontent.com/19620848/193741757-ade06b27-23e6-4ebc-ab68-a4cb95522292.png)
![image](https://user-images.githubusercontent.com/19620848/193741778-efd9dc2f-c2e7-4fdf-a7de-bde579063bef.png)

**Comment by TheonlyTazz** [comment]
fixed in dev, the crosspos.forEach section is redundant and has been removed in the next update

**Comment by KuroPeach** [comment]
New kubejs error. 
![image](https://user-images.githubusercontent.com/19620848/194107324-afe75634-523a-4329-82f9-b4804fe4707e.png)
![image](https://user-images.githubusercontent.com/19620848/194107265-e0c1b315-12fc-4775-a859-5298e24192b8.png)
