### ISSUE TITLE
[Suggestion]: Minecolonies Fortress Reskin Schematic

### ISSUE THREAD

**Issue by Revv1e** [FTBTeam/FTB-Modpack-Issues#1387]
### Modpack

FTB Inferno

### Mod suggestion

Minecolonies:
This is probably a bit unreasonable to ask, and not necessary to add, but, considering the very flat amount of build space the player has in the nether roof, and the many prospects of being invaded by mobs, as well as helpful for the newer players in terms of building a city, making an alternative style for the minecolonies buildings based on the Fortress Style might make for a more interesting base building, and easier since it works in a very modular way. Of course it would need to be modified to look more nether-y as well as a few extra blocks and such to gate each upgrade...and a lot of time, but having alternate styles might add more variety and fun to things for people, specially since its easy to make a cohesive town with the Fortress style!

**Comment by Saereth** [comment]
if a group of people want to volunteer and do something like that I'd love to include it into the pack. I wont personally have time to commit to something like that however, it's a huge amount of work! I'd definitely love to see it though.
