### ISSUE TITLE
[Suggestion]: Add appropriate tool to break warped drawers

### ISSUE THREAD

**Issue by MisterZam** [FTBTeam/FTB-Modpack-Issues#1388]
### Modpack

FTB Inferno

### Is your suggestion related to a problem? Please describe.

Warped drawers takes forever to break. Please add a tool that makes them be broken faster

**Comment by Saereth** [comment]
this is a bug with storage drawers and for them to fix, there is an open issue over there now. 
https://github.com/jaquadro/StorageDrawers/issues/1027
When they get it sorted we'll update
