### ISSUE TITLE
[Bug, Chisel&Bits]: Outdated Chisel & Bits Version Causes World Infinite Loading

### ISSUE THREAD

**Issue by EpicGazel** [FTBTeam/FTB-Modpack-Issues#139]
### Modpack

FTB OceanBlock

### Modpack version

1.2.0 & 1.3.0

### Describe the bug

FTB OceanBlock is using version 0.3.4-RELEASE of Chisel and Bits from Mar 10, 2021, the most updated versions are 1.0.12 and 1.0.35-ALPHA for 1.16.5. Upon using C&B in my world, it caused it to get stuck on the "loading world 0%" screen with varying percentages with a "preparing worlds" with percent also in the debug log. I slowly removed every mod until I narrowed it down to the C&B mod. This is when I discovered the out-of-date version. I have not tested the updated version yet but removing this mod is what allowed me to load my world again. Notably, this issue only began happening after I first placed chisel and bits planes around villagers and their work stands.

### Steps to reproduce

1. Create an FTB OceanBlock World
2. Build a structure with Chisel and Bits
3. Save & Quit
4. Attempt to reload the world (May require restart first)

### Expected behaviour

The game should not get stuck on the world loading screen.

### Screenshots

![image_2021-10-15_194347](https://user-images.githubusercontent.com/20029624/137564853-a5141af7-9200-45bd-ad20-980626de1b3a.png)

### Additional information

I would recommend updating to a newer version of Chisel and Bits. Likely 1.0.12 or 1.0.35-ALPHA.

**Comment by EpicGazel** [comment]
It was upon removal and updating the mod to the 1.0.35-ALPHA version that allowed me in. I don't know what other issues it may cause but I have found none and have been able to access my world now with no issue. Notably, the C&B issue occurred after leaving and attempting to reload the world for the first time after first using C&B in the world (placing bits). However, the inability to reload seemed inconsistent.

You can see the world in the attached link for what it's worth, the version of it before I was able to fix the issue.
https://drive.google.com/file/d/16yhczTPbi91lrgQlVE8ZlsB3W0g4hsVR/view?usp=sharing

**Comment by Raidobw2** [comment]
I've confirmed with the world you sent that it won't open. Tried with 1.2.0 and 1.6.0.
I updated Chisel & Bits to their latest release, now old of 3 days only `chiselsandbits-1.0.43.jar`, and it indeed works.
This is the only Chisel & Bits "blocks" there were near the villagers. Didn't take much to prevent it from opening, definitely a mod issue that appears to have been fixed.
![image](https://user-images.githubusercontent.com/17010632/140242755-07e543bf-4d10-4a19-826f-01ae2dfd6da9.png)
`chiselsandbits-1.0.43.jar` is now available Sunekaer, up to you if that's worth updating. As usual it would probably be worth to check the changelogs just in case.

**Comment by Sunekaer** [comment]
Yes updating will fix some things, but it will also introduce other issues 
Current pack version: 
![image](https://user-images.githubusercontent.com/18720460/140283273-55e8c0ce-9d86-4903-88ac-5707e3e9891e.png)
1.0.43: 
![image](https://user-images.githubusercontent.com/18720460/140283288-55fc94cc-3cf2-4f9f-a333-13efe0c0b81d.png)

As you can see, the wholes become black.
The update has fixed some of the issues I had with 1.0.35-ALPHA but there is still other issues.

**Comment by Sunekaer** [comment]
These things is why i havent updated C&B
