### ISSUE TITLE
[Bug]: Link to Server Files directs to 404 error out of FTB app

### ISSUE THREAD

**Issue by EdgeOfTheHill** [FTBTeam/FTB-Modpack-Issues#1393]
### Modpack

Cotton

### Modpack version

1.1.0

### Describe the bug

When trying to downloaded the updated modpack to upload to my server, the link from the app to download server files results in a 404 error as shown in this link: https://feed-the-beast.com/modpacks/86/server/2057

### Steps to reproduce

1. Navigate to Cotton modpack on FTB App
2. Enter into the Versions tab
3. Click server files in the top right on the latest modpack version
4. Directed to 404 error

### Expected behaviour

To begin download of server files

**Comment by MichaelHillcox** [comment]
Oh whoops, that page is missing... the new website was a complete rewrite and apparently that go missed. For now, you can go to the modpack page on the website, go to versions and download the server files from there.

**Comment by MichaelHillcox** [comment]
Sorted this issue, it'll be released soon
