### ISSUE TITLE
[Bug]: No more invasions

### ISSUE THREAD

**Issue by lordeyahyahyah** [FTBTeam/FTB-Modpack-Issues#1397]
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Describe the bug

After receiving message in chat that an invasion is about to occur, nothing happens. Started to happen seemingly randomly in version 1.0.1. Still persisting in 1.0.2.

### Steps to reproduce

1. See warning message in chat for incoming invasion
2. Nothing

### Expected behaviour

1. See message in chat for incoming invasion
2. See portal open in close vicinity as well as a timer/healthbar appear at top of screen
3. Enemies spawn in around portal

**Comment by Raidobw2** [comment]
Hi, thanks for reporting. Would you be able to add your game logs as well as kubejs logs? That would help a lot!

They are located in the `logs` folder.
- The first one is called `latest.log`, you can add it here directly.
- The other ones are in the `kubejs` folder inside that logs folder (full path `logs/kubejs`). You can zip the three files in there and put them here as well.

Thanks a lot in advance!

**Comment by lordeyahyahyah** [comment]
Thanks for getting back. After I posted the report it did actually work after the third or fourth dud invasion, but I'll be sure to post the logs if it happens again.

**Comment by lordeyahyahyah** [comment]
Happened again. Here are the logs right after it happened.

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9738740/latest.log)
[kubejs logs.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9738741/kubejs.logs.zip)

**Comment by Raidobw2** [comment]
Thanks for posting your logs! I didn't see anything in particular in those logs (nor the mention of an invasion) but I'm not sure how the invasion system works within KubeJS. I'll pass the issue to my collegue Saereth, potentially he has an idea of how this happened

**Comment by Saereth** [comment]
I added more debug outputs for the invasion code to track down these edge cases, will be enabled in 1.0.3

**Comment by Raidobw2** [comment]
@lordeyahyahyah If you happen to update to 1.0.3 (It's currently out now!) and an invasion happens again, may I ask if you could put the same logs here again? Saereth's extra debug outputs would be helpful for us! Thanks in advance!

**Comment by Saereth** [comment]
I ended up getting to the bottom of this, should be fixed now in 1.0.3 entirely, if you have any more issues with this feel free to let me know and I'll reopen
