### ISSUE TITLE
[Bug]: Ender IO alloy smelter destroying and disappearing

### ISSUE THREAD

**Issue by SometimesClueless** [FTBTeam/FTB-Modpack-Issues#1400]
### Modpack

FTB Stoneblock 2

### Modpack version

Latest one

### Describe the bug

I've been following ChosenArchitect with his StoneBlock 2 series and I am currently on episode 6.

He's making a alloy smelter from Ender IO and attaching it to his magma generator from Extra Utilities. Now I did notice a difference in sound when he placed the smelter next to the generator. Perfectly normal, his was from 2019, mine is in 2022, so it must have been updated. However, when I place my smelter down just like he did, my generator blows up and gets destroyed. 

I fixed this by placing the smelter elsewhere and power it wirelessly with a battery and gps marker. I put in my iron ingots and ender eyes and BANG! My smelter, my iron ingots and ender eyes are now all gone. No damage to the base but they're gone. 

Have they nerfed this for early game or is this a bug???

Edit: I was building something else in the area I had placed the alloy smelter and noticed I was hitting an invisible block. Saved and reloaded my game, to find the blasted alloy smelter one block in front of where I had placed it, with my iron ingots inside and the pulsating iron ingots all smelted up. So I didn't lose anything.

I am able to place it down again and use it normally but it does keep disappearing so I right clicked on it and it reappeared.

### Steps to reproduce

1. Make an Alloy smelter from Ender IO.
2. Place it in front of a Magma Generator from Extra Utilities.
 - Lose your magma generator -

1. Place Alloy smelter away from the area.
2. Use a GPS marker on the smelter and place in Energy Transfer Node from Cyclic.
3. Place a iron ingot and ender eye into the powered smelter.
 - you lose the smelter, ingots and eye -

### Expected behaviour

I was trying to make a pulsating iron ingot.

**Comment by Raidobw2** [comment]
Looks like this is something new from EnderIO and now has "energy overflow" -- see https://github.com/SleepyTrousers/EnderIO/issues/5107#issuecomment-491105232. You can try the configuration change, and that will also be what we'll use in a future version of StoneBlock 2

**Comment by tyler489** [comment]
A later update for 1.12 enderio has that off by default

**Comment by SometimesClueless** [comment]
> Looks like this is something new from EnderIO and now has "energy overflow" -- see [SleepyTrousers/EnderIO#5107 (comment)](https://github.com/SleepyTrousers/EnderIO/issues/5107#issuecomment-491105232). You can try the configuration change, and that will also be what we'll use in a future version of StoneBlock 2

Thank you, I have followed the comment and changed the code as mentioned. Apparently, it's not off by default. Guess I'm on an older version of EnderIO?

Should I be updating the mods? I know when I downloaded the pack, it did have an Update button at the top that I did click, so I assume I'm on whatever the latest version. But I know from past experience that updating some mods individually has lead to game crashes. So I only want to update when it's all OK to do so.

**Comment by Raidobw2** [comment]
Updating EnderIO should be safe if you want to, just make sure to take a copy of your world before loading in the world. I don't recall them having any major changes last update we pushed to StoneBlock 2.

In any case try the configuration change (on the latest EnderIO version if you want) and if you want you can let me know if that works
