### ISSUE TITLE
[Bug]: FTB One missing steel nugget for Leadstone Solar Panel recipe

### ISSUE THREAD

**Issue by sealilymarron** [FTBTeam/FTB-Modpack-Issues#1401]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

In the latest update of FTB One, the Leadstone Solar Panel from Solar Generation mod cannot be made because the recipe requires forge:nuggets/steel but there are no steel nuggets in the modpack.

Related: Steel Tank Wall from Tanky also suffers from a similar problem lacking steel ingots.

### Steps to reproduce

1. In the inventory/JEI, search for "Solar"
2. Click Leadstone Solar Panel
3. View the recipe. Observe the red icons in the bottom row.
4. Mouseover the missing ingredients. Observe it says "Empty tag: forge:nuggets/steel"
5. In the inventory/JEI, search for "steel"
6. Observe that no steel nuggets are found

### Expected behaviour

The Leadstone Solar Panel can be crafted with ingredients available in the modpack

### Screenshots

![image](https://user-images.githubusercontent.com/17656770/194673965-28366874-f5c1-4303-866d-48ccf0c74f07.png)
![image](https://user-images.githubusercontent.com/17656770/194674363-0056b2db-e30d-46ba-a2fa-8756760a2f57.png)

**Comment by Raidobw2** [comment]
Linked with https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1277, thanks for reporting
