### ISSUE TITLE
[Bug]: Crashing when heading into new chunks

### ISSUE THREAD

**Issue by Minithra** [FTBTeam/FTB-Modpack-Issues#1404]
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Log Files

https://mclo.gs/sHSnmF8

### Describe the bug

Heading away from my base to explore new lands, crashed as I started uncovering new chunks. Has happened 3 times so far, it's always fine on reload.

### Steps to reproduce

Be on the roof of the nether, run straight into a random direction into unexplored chunks (maybe speed matters? I have boots with a bit of extra speed)

### Expected behaviour

New chunks, no crash.

**Comment by Raidobw2** [comment]
Please see https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1357 for the main issue, Michael has put a temporary fix on his comment where you can get a modified rubidium file -- or removing Rubidium would also work
