### ISSUE TITLE
[Bug]: almost infinite iron ingots

### ISSUE THREAD

**Issue by Toxz21** [FTBTeam/FTB-Modpack-Issues#1408]
### Modpack

skyfactory 1

### Modpack version

1.0.4

### Describe the bug

i was crafting some construcition wands to place and hammer gravel and when i ran out of sticks suddenly there was like 500,000,000 overstacked iron ingotsin the crafting grid, i have tried reproducing the bug but it doesn't want to happen anymore.

### Steps to reproduce

crafting iron construction wands

### Expected behaviour

to get construction wands an the irpn to be the number of ingots there were left

**Comment by Toxz21** [comment]
sorry for all the misspelling im not english

**Comment by Raidobw2** [comment]
Hi, this should be reported to https://github.com/DarkPacks/SkyFactory-One/issues, we don't own nor maintain this modpack, it is made by another developer, Darkosto.

I will be closing this issue as a result, you should be able to copy paste your issue on the other tracker I linked
