### ISSUE TITLE
[Bug]: Crash when finished applying resource packs

### ISSUE THREAD

**Issue by DangerChamp** [FTBTeam/FTB-Modpack-Issues#1409]
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Log Files

https://pste.ch/degubiyumo.pl

### Describe the bug

When I clicked done in the resource packs menu it suddenly crashed. I didn't apply any resource backs by the way.

### Steps to reproduce

1. Go on resource packs 
2. Don't apply any resource packs
3. Click done
4. Game crashes

### Expected behaviour

Not to crash

**Comment by Raidobw2** [comment]
See https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1356, your crash log and the one in that issue are the same. I'll be closing this to avoid tracking multiple similar issues, but thank you for reporting the issue
