### ISSUE TITLE
[Bug]: Unobtanable items make FTB Oceanblock unable to complete

### ISSUE THREAD

**Issue by LuciusV** [FTBTeam/FTB-Modpack-Issues#141]
### Modpack

FTB Oceanblock

### Modpack version

1.3.0

### Describe the bug

1. Draconium chest (Draconic Evolution mod), required for "Storage" chapter quest, is uncraftable
2. Dense Construction Block (Building Gadgets mod), required for "Endgame" chapter quest and for **crafting Dense construction Block singularity, is uncraftable, making impossible to craft Ultimate singulatity and making whole pack uncompletable**

### Steps to reproduce

Open questbook or JEI and look for recipes

### Expected behaviour

Expected working recipes

**Comment by Sunekaer** [comment]
Draconium chest had a recipe added in update 1.3.0 what launcher you using sounds like some files didn't get updated.
Dense Construction Block is obtained by placing Construction Block Powder in water.

**Comment by LuciusV** [comment]
I am usiing multiMC, I'll try to reinstall and report

**Comment by LuciusV** [comment]
I reinstalled 1.3.0 and now there are no problems with both items. Sorry for wrong report.
