### ISSUE TITLE
[Suggestion]: Dragon Minion waves during Ender Dragon fight seem impossible.

### ISSUE THREAD

**Issue by CreatorBurden** [FTBTeam/FTB-Modpack-Issues#1411]
### Modpack

FTB Inferno 1.0.2

### Is your suggestion related to a problem? Please describe.

You have 30 seconds per minion wave, at least for the first one as I've never made it passed it, to kill around 8 elite monsters, 2 of which are usually phantoms. They seem overtuned for the extremely limited time available. The final wave for boss gates were already doubled but that had no effect on the minion waves during this fight.

### Mod suggestion

Simply increase the time available, maybe to 1 minute, in order to still keep it challenging but make it far less frustrating to have a single phantom in orbit that you cannot kill in time.

**Comment by VeikkoV** [comment]
its not even just the wavelength being ludicrously short (practically impossible for solo players), but also just the fact that all mobs are flying except for shulkers. 9 times out of 10 you lose simply because one of the vexes or phantoms decides to want to ruin your last remnants of hope and just wanders out of the range to hard reset your 73rd desperate attempt.
Personally after roughly 7-8 hours of attempting these waves and its starting to feel like this wasn't even meant to be defeated without a decent sized team.

**Comment by Saereth** [comment]
The waves are not meant to be defeated. They open in response to fighting the dragon and then reset after the timer runs out. It's more of a mechanic of a continual onslaught of ads throughout the fight. Basically, you need to prioritize taking out any particularly troublesome mobs from the waves and generally ignore the rest, but that's up to the player to prioritize.

You are not required to complete the waves in this fight to defeat the dragon.

**Comment by CreatorBurden** [comment]
The dragon is completely immune to damage during the waves and the waves instantly respawn upon damaging the dragon once, am I supposed to whittle her down with single hits between the failed waves?

**Comment by Saereth** [comment]
This seems to be a bug actually we are looking into it

**Comment by CreatorBurden** [comment]
She only starts spawning waves once youve dealt maybe 10% of he health, so based on the waves I assumed you had to succeed at the waves in order to be able to continue damaging her, hence my confusion as to why the waves seemed impossible.

**Comment by Saereth** [comment]
Just to demystify things.. Currently, the waves happen by 25% chance anytime you inflict damage, but she wont spawn waves more often than once every 45s and not if a gate is currently active.

**Comment by CreatorBurden** [comment]
There is no delay between gates at all for me, they instantly respawn upon her taking a single hit once it fails. Though ive noticed that even her crystals cannot effect her HP, she doesnt regen when they are up nor do they damage her if you break them while they are healing.

**Comment by CreatorBurden** [comment]
After some further testing in a new test world, it seems like the shotgun I was using was breaking her in some way, using just vanilla weapons the dragon is still immune to damage for most of the fight, especially when the minion portal is up, but she is, albeit VERY slowly, dying. Would take easily an hour to kill her this way, but its working?

**Comment by Saereth** [comment]
the gates last 45s, roughly, so yeah its normal they respawn almost instantly

**Comment by CreatorBurden** [comment]
The first wave has a 30 second timer.

**Comment by Saereth** [comment]
@CreatorBurden yeah her armor is way too high right now, the wave timing is intended but she's getting far too much damage reduction, looking to fix it for weds update

**Comment by CreatorBurden** [comment]
Understood, I wanted to make sure it wasnt something oddly specific with what I was using, hence my further testing. With the way the fight looks, esp since it says wave 1/4 on the minion waves I assumed completing them was required. At least the song during the fight is a banger, def going to need the music disc from this.
