### ISSUE TITLE
[Suggestion]: Reliquary Items Uncraftable

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#1412]
### Modpack

Inferno

### Is your suggestion related to a problem? Please describe.

Reliquary mob drops are still used in various reliquary recipes but do not have ways of obtaining them, like the slime pearl, or the tome of alkehistory. 

Also maybe increase the charm fragment drop chance, they seem REALLY rare. 

### Mod suggestion

No.

**Comment by Raidobw2** [comment]
This has been reported already at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1410, although I will add your comment about the charm fragment there. I'll close this to avoid duplicate issue tracking, but thanks for reporting!
