### ISSUE TITLE
[Bug]: MineColony University Upgrade T3 > T4

### ISSUE THREAD

**Issue by MillerV7** [FTBTeam/FTB-Modpack-Issues#1414]
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Log Files

N/A

### Describe the bug

T3 > T4 University does not have the Swamp Jaw Mossy Tooth as a requirement to upgrade and the builder will materialize it out of thin air and place it on the pedestal even though I have not done the fight.
Note: This is also a issue for T2 > T3 but there's already a report for that.

### Steps to reproduce

1.Have a Tier 3 University
2. Go to the Building Options Tab
3. Press the Upgrade button

### Expected behaviour

The Swamp jaw Mossy Tooth should be in the Needed Item to Upgrade tab, and the builder should not materialize it out of thin air.

### Screenshots

https://imgur.com/a/G63vee4
https://prnt.sc/y6ptPshf88oC

**Comment by Saereth** [comment]
this is fixed in next update, minecolonies glitchiness
