### ISSUE TITLE
[Bug]: Upgrading Tinkers Travelers Armour to Plate Armor does not update tinker stats

### ISSUE THREAD

**Issue by Nagapito** [FTBTeam/FTB-Modpack-Issues#1415]
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Describe the bug

When you upgrade a Tinkers Traveler Armor to a Plate Armor it should change the number of upgrades and defense slots since that is one of the big reasons to upgrade the gear...

But, the gear upgraded on the smiting table does not update and the Plate Armor keeps the same slot numbers as the Traveler Armor..

### Steps to reproduce

Craft Plate Armor
See that available slots are the same as travelers armor instead of supposed plate armor slots

### Expected behaviour

Upgraded Plate armour shouls have expected defense slots

**Comment by Saereth** [comment]
There is no intrinsic way to upgrade that armor with tinkers nor did we add that functionality, if you slot extra modifiers and such onto your armor and want to keep them you should just make a fresh set to upgrade to cobalt. This may be something we do some custom scripting for in the future but it isnt on the list of things to do currently.

**Comment by Nagapito** [comment]
I think you misunderstood the situation...

Cobalt plate is supposed to have 1 upgrade slot, 1 ability slot and 4 defense slots. That is one of the things about cobalt plate, offering more defense slots and be sturdier. And this is what JEI info shows about this armor.

Currently, there is no way to way to craft the armor JEI shows. The current recipe just converts the traveler plate to cobalt, changing the armor resistance and armor toughness stats (since they do belong to the item type and are not stored in NBT) but keeps tinker attributes from traveler set. So, instead of 4 defense slots we get a cobalt plate with only 2 defense slots. 

This is misleading and if it is the intended behavior, at least add a note on the JEI tool-tip warning the player that he will NOT get what he sees!

**Comment by Saereth** [comment]
oh yeah no that is a bug, ok reopening

**Comment by Saereth** [comment]
yeah I can even hard set the nbt but tinkers overrides it in the smithing table, not going to be able to fix this sadly but with the access to creative modifiers people have it shouldnt be a major concern. Going to add in 2 more defense modifiers as a quest reward for crafting your first set
