### ISSUE TITLE
[Bug]: spirit fire recipes not working

### ISSUE THREAD

**Issue by therob** [FTBTeam/FTB-Modpack-Issues#1417]
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Log Files

Nothing in log files to find. I searched for "dead" and "fern".

### Describe the bug

The spirit fire recipes to get a dead bush from fern or propelplant cane from sugar cane are not working. They also do not show up in JEI.
![dead_bush_recipe](https://user-images.githubusercontent.com/814171/194957725-2f230b6c-fa84-4bd6-b3b2-926abef2201b.png)
I was looking at the scripts and found the recipe for dead bush defined twice. One in `kubejs/server_scripts/mods/infernalexpansion.js` and one in `kubejs/server_scripts/recipes_misc.js`. The recipe id `inferno:deadfern` is used for both and is also used for `nethersdelight:propelplant_cane` and `structurize:sceptersteel`.

Removing the duplicate recipe and changing the recipe ids to be unique fixes this problem.

### Steps to reproduce

1. install pack
2. start new world
3. look up recipe for dead bush

### Expected behaviour

dead bush and propelplant cane can be created in spirit fire

**Comment by Saereth** [comment]
Fixed in next update, thanks for the report
