### ISSUE TITLE
[Bug]: Sticks are dropping with affixes due to misconfiguration

### ISSUE THREAD

**Issue by Nagapito** [FTBTeam/FTB-Modpack-Issues#1418]
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Describe the bug

As described on Apotheosis changelog for version 5.7 (https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/changelog.md): 

"ATTENTION PACKDEVS! If you do not update your config you will start seeing any sticks dropped by a loot table being given affixes!"

Currently, when we harvest a oak tree, the random sticks it drops have affixes... 
Probably related to this config not being updated

### Steps to reproduce

Harvest an oak tree
Observe dropped sticks

### Expected behaviour

Should drop normal vanilla sticks

**Comment by Saereth** [comment]
This is not a misconfiguration we left it that was intentionally to be used
with the coming aid recycling system. That got delayed due to the hurricane
however do it will be off in the next update along with skillets
