### ISSUE TITLE
[Bug]: FTB Inferno - Duplication via CarryOn and Bonsai Trees 3

### ISSUE THREAD

**Issue by Uimori** [FTBTeam/FTB-Modpack-Issues#1419]
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Describe the bug

Using CarryOn to pick up Bonsai Pots causes the pot to remain in the hand when placed causing a duplication.

### Steps to reproduce

1. Sneak + right click a placed bonsai pot with both hands empty to pick it up
2. Right click to place the pot elsewhere
3. Right click again...and again to duplicate
4. Use "/carryon clear" to empty your hands when done

### Expected behaviour

Bonsai pots should not duplicate or could be black listed from CarryOn

**Comment by Saereth** [comment]
botany pots are not whitelisted in the config for this pack, ONLY chests and drawers. If you can pick them up your server did not import the carryon config from the defaultconfigs folder. There was a note about this in the patch notes for 1.0.2
