### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#1421]
### Modpack

Inferno

### Is your suggestion related to a problem? Please describe.

Some Swords are not added to the forge swords tag meaning they cant be filtered by tag.

**Comment by Saereth** [comment]
Need a list of which ones you think should, it should be tagged by the mod
developer so I'll need to follow up with them

**Comment by tyler489** [comment]
AE
Ars Nouveau
Avaritia
Wither Storm Mod
evilcraft
Immersive Engineering
Minecolonies
SoulShards
Tinkers Construct
WitherBold


Pretty much every mod except vanilla and bloodmagic are untagged.

**Comment by Saereth** [comment]
ugh so much work :P

**Comment by tyler489** [comment]
Just right a script that searches for the word "sword" and assigns them a tag

**Comment by Saereth** [comment]
cant do that sadly as not all swords are JUST swords in the code and applying that tag and allowing socketing without checking each one individuality can result in things breaking on the backend. So I will just check them all as I get time

**Comment by tyler489** [comment]
so forgeswords tag is what controls the socketing of apotheosis?

**Comment by Saereth** [comment]
yep, and armor tag for armors, I fixed MOST of them for 1.0.3
