### ISSUE TITLE
[Bug]: Server making a new world on start up

### ISSUE THREAD

**Issue by Brycen1204** [FTBTeam/FTB-Modpack-Issues#1422]
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Describe the bug

Every time I start the server up it creates a new world and replaces the old world file. 

### Steps to reproduce

1. Download the server files
2. Start up the server 
3. Once server is up and running exit out
4. Start up the server again

### Expected behaviour

The world to not be reset

**Comment by Saereth** [comment]
gonna need to see some logfiles from the server here. Latest.log and debug.log please

**Comment by Brycen1204** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9759870/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9759871/debug.log)

**Comment by Saereth** [comment]
nothing jumps out as wrong here, the only way this should happen is if your server somehow cant write the world data, permission issue perhaps? can you force a /save on the file and verify the /world folder is created and has info before shutting down thes server? post your server.properties as well please

**Comment by Brycen1204** [comment]
I'll put the server up and try that.
[server properties (reformatted for github).txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9759998/server.properties.reformatted.for.github.txt)
I put the level-name to testworld about an hour ago and have restarted it around 5 times since then. The same issue happened when it was set as "world"

**Comment by Saereth** [comment]
testworld is fine, just so check that the folder is actually being created/saved when you launch the server and we'll go from there. Server properties look fine

**Comment by Brycen1204** [comment]
For some reason, /save-all makes it work. Weird that the save from /stop didn't go through, but it works now. Thank you.

**Comment by Saereth** [comment]
ok np, thats so weird
