### ISSUE TITLE
[Suggestion]: Make Blue Nether Bricks give the same Speed Bonus as Red Nether Bricks (FTB Inferno)

### ISSUE THREAD

**Issue by Novasiri** [FTBTeam/FTB-Modpack-Issues#1424]
### Modpack

FTB Inferno

### Is your suggestion related to a problem? Please describe.

I found it a bit weird that the Red Nether Bricks gave a 1.35 speed modifier when their Blue counter parts, made the same way just with Warped Nether Wart, gave 0. Seems really inconsistent since the only difference between the two is color.

![image](https://user-images.githubusercontent.com/78075114/195316984-9048a550-6310-4554-86e6-0af69b59ead3.png)

![image](https://user-images.githubusercontent.com/78075114/195316789-123a6099-98d9-45d6-9501-ce1c9c4691fd.png)

Maybe bring them both in-line with each other so we can keep with the aesthetic of the blue themed colony? (Or let us make a red variation of the colony? Either works.)

**Comment by Saereth** [comment]
ok!
