### ISSUE TITLE
[Bug]: Inferno Crashing on Launch

### ISSUE THREAD

**Issue by proslackergamer** [FTBTeam/FTB-Modpack-Issues#1426]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9769218/latest.log)

### Describe the bug

On launching after updating FTB Inferno, the instance crashes after pressing play.  This has occurred both on an upgraded instance (1.0.2 -> 1.0.3) and on a new installation.

### Steps to reproduce

Download 1.0.3 and attempt to launch the modpack (note: this issue does not seem to occur with all users(?)).

### Expected behaviour

The game to launch normally.

**Comment by Saereth** [comment]
That version has now been marked private until the issue with the backend can be resolved. Closing this as we're aware/working on it and when its sorted should no longer be an issue with the pack specifically.  Ty for the fast report
