### ISSUE TITLE
[Bug]: Bloodmagic Armor is not tagged for Socket Crafting

### ISSUE THREAD

**Issue by Saereth** [FTBTeam/FTB-Modpack-Issues#1430]
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Describe the bug

plz fix

### Steps to reproduce

try to socket bloodmagic armor
be big sad

### Expected behaviour

for it to work

**Comment by bwser20** [comment]
Armor also does not show stats like armor value, health increase, toughness, speed increase ect like other armors, apotheosis stat increases and perks, it only shows what would be directly below item name and if it has a potion effect on hit.
