### ISSUE TITLE
[Bug]: Tooltip does not show extra Apotheosis affixes on Tinker's stuff

### ISSUE THREAD

**Issue by Senne-DC** [FTBTeam/FTB-Modpack-Issues#1437]
### Modpack

Inferno

### Modpack version

1.0.3

### Describe the bug

Tooltips do not show all the Apotheosis related information on Tinkers armor and tools.

### Steps to reproduce

1. Use the Apotheosis Reforging Table to make a Tinkers tool/armor an affix item
2. Check tooltip and compare with item's NBT
3. Notice missing stuff

### Expected behaviour

Show all affixes correctly in the tooltip

### Screenshots

![image](https://user-images.githubusercontent.com/2308797/195897308-24decfa7-a3a8-457d-ba6d-d7b2e26c516c.png)
![image](https://user-images.githubusercontent.com/2308797/195897950-27df90b7-403d-4875-aae4-154163d2ea0f.png)

**Comment by Saereth** [comment]
reported to mod dev
https://github.com/Shadows-of-Fire/Apotheosis/issues/674
