### ISSUE TITLE
[Bug]: Ticking screen crash when connecting to server

### ISSUE THREAD

**Issue by Xplodin** [FTBTeam/FTB-Modpack-Issues#144]
### Modpack

FTB OceanBlock

### Modpack version

1.3.0

### Log Files

[crash-2021-10-16_14.21.00-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7358043/crash-2021-10-16_14.21.00-client.txt)

### Describe the bug

I cant connect to my server thats on linux
Its giving outofbounds and crashes to desktop

### Steps to reproduce

download game on windows
connect to linux server after installing optifine (why not, streamers got it working)
Crash to desktop

### Expected behaviour

Connect to server fully

### Screenshots

N/A

### Additional information

Optifine is installed but thats unrelated

**Comment by Raidobw2** [comment]
As seen in your crash-log, your mod versions are:
`appliedenergistics2-8.4.1.jar` and `minetogether-1.16.5-5.0.1-forge.jar`.
In the changelog for 1.3.0 there is this information:
![image](https://user-images.githubusercontent.com/17010632/137613000-195866cf-b586-4184-a435-dfcf087a8e8e.png)
This indicates that you are still using version 1.2.0 of OceanBlock clientside!

This has already been solved in #67 and I have also replied a solution to you as well in #143.

You need to update your modpack to 1.3.0, if you are unsure about versions, use the FTB App as it is clearly labeled on there.

I will close this as it is duplicate and already solved. Update the modpack and make sure MineTogether is of version `minetogether-1.16.5-5.0.2-forge.jar` in your mods folder, which has been distributed in the new version 1.3.0 of OceanBlock.
