### ISSUE TITLE
[Bug]:  Advanced Hive not functioning.

### ISSUE THREAD

**Issue by ZloIsEvil1** [FTBTeam/FTB-Modpack-Issues#1441]
### Modpack

FTB Inferno

### Modpack version

1.0.2

### Describe the bug

Using vanilla bees in a Warped Advanced Hive with a expansion box, the bees do not function. They will pop out of the box for a split second, enough for the model to load, and then disappear back inside with absolutely no time to seek the flowers. As such, they do not produce honey. 

I have tried using a stick to force them to leave, but they just hover aimlessly until they re-enter the box and the cycle continues. I have used a time-in-a-bottle to speed them up to 128x which achieves nothing but making them pop out faster. 

### Steps to reproduce

Place Warped Advanced Hive on stone bricks, then place an expansion box above it. Place a block of dirt next to the hive, with a poppy/rose bush on top. Release a vanilla bee from a Sturdy Bee Cage and wait for it to enter. After it does, wait for it to come out. If it does for the smallest fraction of a second, you've got the same issue I do.

### Expected behaviour

I expected the bee to leave, eat the flower, and then make honey.

**Comment by Saereth** [comment]
I can't reproduce this
![2022-10-15_04 01 12](https://user-images.githubusercontent.com/9200909/195982943-8bd9379a-d213-4141-9ff0-37e46e5a7453.png)


Can you give me some screenshots or more details of your setup?

**Comment by Saereth** [comment]
can you also test this on 1.0.3, productive bees was update, might have fixed whatever issue you're having

**Comment by ZloIsEvil1** [comment]
Yea, seems like the update fixed it. Thanks for the response.

**Comment by poempelhase** [comment]
I too am experiencing this issue, even after the update. Don't think it's a one time occurence, even though I'm having a hard time reproducing it as other similar hives work just fine.
