### ISSUE TITLE
[Bug]: Minecolonies Concrete mixer not crafting

### ISSUE THREAD

**Issue by iasazo** [FTBTeam/FTB-Modpack-Issues#1442]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

The minecolonies' concrete mixer is not making Concretes from Concrete Powder.  

The Concrete Mixer's Hut shows the correct tasks in its tasks tab.  The hut is delivered the needed ingredients.  The Concrete Mixer repeatedly takes the items from the hut into their inventory then after 5-10 seconds places the same items back in the hut.  This process repeats indefinitely.

This is a tier 1 hut.  I have tried reordering, disabling and re-enabling recipes with no luck.

### Steps to reproduce

1. Request Concrete (In my case request was initiated by other villagers)
2. Observe Concrete Mixer fail to convert Concrete Powder to Concrete.

### Expected behaviour

For Concrete to get made.

**Comment by Saereth** [comment]
seems to be working ok on my end 
![2022-10-15_05 39 20](https://user-images.githubusercontent.com/9200909/195986873-c1d48a72-60b1-4cad-a5ef-e1180e6beaa9.png)

Can we get some screenshots of your setup/mixer/request window?

**Comment by iasazo** [comment]
What level is this concrete mixer hut?  Is it intended that you build your own waterfall structure?  At level 2 the nether stairs in your image are not present and the water just sort of spreads out on the main level.  I'll try manually building the canal structure or upgrading the hut to see if that solves it.
![2022-10-15_12 52 12](https://user-images.githubusercontent.com/8786703/196003429-d5123770-6088-463a-b3ec-073f947cda54.png)

**Comment by iasazo** [comment]
It looks like the issue is that my cement mixer's hut didn't get built correctly.  I just requested to upgrade the building seen in the image and it says it is going from level 3 - level 4.  I'll try repairing but the original issue may be a misdiagnosis.

**Comment by iasazo** [comment]
Requesting a 'Repair' of the concrete mixer's hut did not fix the building.  Did an update change this building's layout?  In my existing building, the hut block is in the 'left' of the 2 buildings.  When I look at the layout with a new hut it shows it in the 'right' of the two buildings.

Rebuilding it from scratch seems to have fixed it.

**Comment by Saereth** [comment]
that is very odd, but glad its working for you now
