### ISSUE TITLE
[Bug]: Crash with buildtool on decorations

### ISSUE THREAD

**Issue by Kithio** [FTBTeam/FTB-Modpack-Issues#1444]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Log Files

https://pste.ch/aranevabuy.rb

### Describe the bug

Hard Crash when cycling decorative buildings [middle bar] in MineColonies UI

### Steps to reproduce

1. Get Build Tool
2. Right click on Ground
3. Cycle Top Middle Bar
4. Crash after reaching a specific one (Don't know which one, it doesn't tell me before it crashes)

### Expected behaviour

No Crashing?

### Screenshots

![image](https://user-images.githubusercontent.com/9414786/196001143-fba5f7d5-0e8b-46a9-8372-c8c4e826d2da.png)

### Additional information

Usually crashes right after that one (right arrow from it) shown in screenshot (Fields/Warped)

**Comment by Saereth** [comment]
This on a server or single player?

**Comment by Kithio** [comment]
Client Crash happens on a Server

**Comment by Saereth** [comment]
if you are the server own or can you ask the server own to see if there is a folder called decorations in:
FTB Inferno\structurize\schematics and also let me know if you have a decorations folder on your client. This folder should have been deleted from both the client and server in 1.0.3 and I suspect it may have been missed somewhere and would trigger this behavior.

**Comment by Kithio** [comment]
Folder is  indeed missing on server

However, the client has been around since 1.0.1 so I assume it's just remnant files in that case that needs to be cleaned out,

probably worthwhile having a notice about stuff like files that are supposed to be deleted when majority of people just hit the Update button on their backs, which never does a full clean

**Comment by Saereth** [comment]
Are you running the pack on the ftbapp or on another launcher? The FTBApp should have deleted that so I'll add a notice but I'll need to look into why the launcher didnt delete it. Or

**Comment by MaximevanderSmissen** [comment]
I seem to be affected by the same issue, but when accessing the 'infrastructure' and 'infrastructure/hutblock' tabs on the build tool.
Crashlog: https://pste.ch/roboqufozo.rb
Only the client of the player holding the tool crashes

After reading through the chat here, I've checked and both the server and client contain the respective folders (FTB Inferno\structurize\schematics\infrastructure and FTB Inferno\structurize\schematics\infrastructure\hutblocks) with files in them
Respectively:
patrolpoint.blueprint 
waypoint.blueprint

And:
scarecrow.blueprint

Hope it might help / get fixed soon.

**Comment by Saereth** [comment]
@MaximevanderSmissen you issue is actually different, you have the template waypoint bug which is fixed in the new mineocolonies release (will be included in the pack update very soon) The missing templates show up as an array index out of bounds crash

**Comment by MaximevanderSmissen** [comment]
@Saereth sorry for replying so late, but thanks for the explanation!
