### ISSUE TITLE
[Bug]: Minecolonies Builder wants bedrock to uprgade

### ISSUE THREAD

**Issue by JordanLewis23** [FTBTeam/FTB-Modpack-Issues#1449]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

I am playing on a server running the Inferno mod pack and ran into an issue: 
My Minecolonies builder are asking for bedrock as part of their upgrading process, however the JEI recipes for bedrock are bloodmagic rituals that have certain effects but do not produce aything let alone bedrock. Bedrock is not listed as required before selecting to upgrade.

### Steps to reproduce

1. have glassblowers hut (also saw on crusher) placed
2. select the option to upgrade building
3. wait for builder to ask for bedrock
4. not be able to get bedrock

![Screenshot 2022-10-16 213959](https://user-images.githubusercontent.com/99272041/196071515-fb7d4230-c527-4a25-b97e-474c09a06cb6.png)

### Expected behaviour

When I selected the upgrade option I expected the builder to request the only prior listed materials and build the upgrade to the building.

### Screenshots

![image](https://user-images.githubusercontent.com/99272041/196071619-7e13d86f-4f77-4cfe-ae9a-4a46fcfdf143.png)

**Comment by JordanLewis23** [comment]
request seems to not matter. after some time the job completed anyway.

**Comment by JordanLewis23** [comment]
request seems to not matter. after some time the job completed anyway.

**Comment by JordanLewis23** [comment]
request seems to not matter. after some time the job completed anyway.

**Comment by Emangi-FCMG** [comment]
I have the same thing happening to me except with crushers hut. The task completed, but the request for bedrock remained in my clipboard.
