### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by PopLamina** [FTBTeam/FTB-Modpack-Issues#1450]
### Modpack

FTB Inferno

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/tool-belt
Very useful for managing tools like the build tool and clipboard and wrenches.

**Comment by Saereth** [comment]
While I like the mod, the license is a bit weird and requires their exact wording be displayed where its redistributed (FTb App in this case) and we dont have anything setup to accommodate that kind of restriction currently. If we get that functionality in the future I'll revist but for now we cant meet their licensing requirements
