### ISSUE TITLE
[Suggestion]: Remove certain buffs from champion mobs

### ISSUE THREAD

**Issue by iAedz** [FTBTeam/FTB-Modpack-Issues#1451]
### Modpack

FTB Inferno

### Is your suggestion related to a problem? Please describe.

The problem is that no matter how much time and effort you put into creating a good set of armor to defeat these bosses that are required to progress, if they spawn with disarmoring, youve already lost the fight and all the armor youve been working towards. I fought the void worm 3 times, each time he spawned with disarmoring or thief or something that takes your weapons/armor. After i spent countless hours collecting mythic material and xp to upgrade and make the perfect armor, doesnt matter, gets ripped off your body and then you get instakilled.

**Comment by Saereth** [comment]
thief is already disabled as is sticky (the one that takes your weapon). I'll disable disarmoring but that should be the only one that was up

**Comment by iAedz** [comment]
Just spawned a wither in 1.0.3, he spawned with sticky and thief, took my satchel n everything i owned lol, idk if you mean its already disabled for the next update, but doesnt seem to be in the current version
