### ISSUE TITLE
[Bug]: Server crash on client connect

### ISSUE THREAD

**Issue by PetervdHemel** [FTBTeam/FTB-Modpack-Issues#1452]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Log Files

https://pste.ch/gelogoqito.rb

### Describe the bug

Server crashes on client connect. Happens in both 1.0.2 and 1.0.3 of **Inferno**.
Suspect maybe some corrupted chunk?

Let me know if you need any further info.

### Steps to reproduce

From client pov, after server is restarted it shows as online and compatible. When connecting the client freezes and after a while I can hear in-game audio for a split second, before the client freezes again and the "Connection Lost" "Timed out" screen is shown. The server is crashed and needs to be restarted before being able to attempt reconnecting.

### Expected behaviour

Being able to connect to server.

### Additional information

For reference, we are at the Immersive Engineering stage of the modpack. The server was running for about 2 days while nobody was online. In this time period of 2 days something caused us to not be able to reconnect to the server without it crashing.

The server was also updated to Inferno 1.0.3 in this time period. The same bug now occurs on both 1.0.2 and 1.0.3.

**Comment by Saereth** [comment]
https://www.curseforge.com/minecraft/mc-mods/entangled-fix
Add this mod to your server and clients, should fix it. This is included in the next update that will be out weds
