### ISSUE TITLE
[Bug]: Armre Recepie Broken

### ISSUE THREAD

**Issue by RickyGeo** [FTBTeam/FTB-Modpack-Issues#1456]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Log Files

[2022-10-18-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9806152/2022-10-18-1.log.gz)

### Describe the bug

The Novice Armor and the Gilded Recepie Broken i cant upgrade it in siting table

### Steps to reproduce

1. add novice Hood and Blaze Fabric in Smiting Table
2. u will get Mge Hood 

1. add add gilded netherite Helet and ignitiumingot in Smiting Table 
2. Produce Ignitium Helmet

### Expected behaviour

it will get the Item with the recepie

### Screenshots

![1](https://user-images.githubusercontent.com/49329363/196327592-15f58ab6-c4b4-42d9-9482-611528e71364.png)

**Comment by Saereth** [comment]
True is a dupplicate issue, it's fixed in the next update that should come out weds
