### ISSUE TITLE
[Bug]: Server Randomly crashing due to Champions or WYML mod?

### ISSUE THREAD

**Issue by legitswitch** [FTBTeam/FTB-Modpack-Issues#1457]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Log Files

https://hastebin.com/ilobayoyok.rb

### Describe the bug

Server will randomly crash. Seems like some kind of mob AI issue, though not sure if it's due to the champions mod or WYML mod.

Pack author recommended updating the collective library, but that did not stop the issue.

### Steps to reproduce

Not sure, but I can provide the world if needed.

### Expected behaviour

Not crashing

**Comment by Saereth** [comment]
This is occurs near beacons, its been fixed by the mod dev but they havent released an updated build yet. You can avoid this by just not putting up beacons until the update.
