### ISSUE TITLE
[Bug]: MV field generator still requires osmium

### ISSUE THREAD

**Issue by Vic3Dexe** [FTBTeam/FTB-Modpack-Issues#1458]
### Modpack

ftb interactions

### Modpack version

2.12.1

### Describe the bug

MV field generator still requires osmium

### Steps to reproduce

1. Install, launch, create new world.
2. Check recipe for MV field generator

### Expected behaviour

Should not require osmium (recipe was changed in 2.12.0)

### Screenshots

![изображение](https://user-images.githubusercontent.com/6287048/196470166-a8a2e1a8-6e10-45c8-9cb0-234d2eba57fe.png)

**Comment by Vic3Dexe** [comment]
[gregtech.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9814679/gregtech.zip)

I didn't touch scripts, all files as downloaded by FTB launcher.
About this line
`print("---------------Gregtech Start------------------"); `
should I see it in some logs? Because I can't find result of this print anywhere.

**Comment by Saereth** [comment]
yeah it should show in the logs, are you seeing any script errors?
I double checked your file and the recipe is correct there
```

recipes.remove(<metaitem:field.generator.mv>);
assembler.recipeBuilder()
		.inputs(<ore:circuitGood>*4, <ore:dustEnderEye>, <ore:wireGtDoubleSignalum>*4)
		.outputs(<metaitem:field.generator.mv>)
		.duration(1800)
		.EUt(120)
		.buildAndRegister()
```

So it would appear something else is breaking your scripts. Will need your latest.log to investigate further

**Comment by Vic3Dexe** [comment]
[latest.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9815001/latest.zip)

I'm not good in log readings, too many mods ))

To clarify: I've actually playing with another install (stock launcher, different forge, some mods deleted etc). But I did clean install with FTB launcher and didn't touch any file. But the issue is the same.

**Comment by Saereth** [comment]
let me get your craftweaker log as well

**Comment by Vic3Dexe** [comment]
[crafttweaker.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9819412/crafttweaker.zip)

**Comment by Vic3Dexe** [comment]
`Enhanced chest recipe now uses config 1 instead of 8 to avoid conflicting with the other recipeS `
This change is actually here
![изображение](https://user-images.githubusercontent.com/6287048/196918269-b1f2ec4e-50e4-459b-9dae-66f52afb0f64.png)
