### ISSUE TITLE
[Bug]: Crash with minecolonies UI

### ISSUE THREAD

**Issue by Silversnake1245** [FTBTeam/FTB-Modpack-Issues#1461]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

When the Minecolonies GUI is opened, the client game crash

### Steps to reproduce

1.Right click with supply camp or building tool
2. The game crash

### Expected behaviour

When the GUI is opened, the game crash

**Comment by Saereth** [comment]
Need a crash log

**Comment by SnightOfTheSnurch** [comment]
Not my post, but I've got the same issue on my Aternos server, same modpack. I can send my server logs and a video of the issue as it happens if you want.

**Comment by Saereth** [comment]
We'll need to see some logs for sure yeah, latest.log from client/server would be useful

**Comment by SnightOfTheSnurch** [comment]
https://mclo.gs/1qriyhE

This is the only error message that is given immediately after the crash

**Comment by Raidobw2** [comment]
Do you have your client logs? If this is a client crash, the error will only be listed clientside, not on the server (current server logs don't show the error).
In `logs` and `crash-reports` on your clients is where you would look for that info.

**Comment by SnightOfTheSnurch** [comment]
[2022-10-19-2.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9838240/2022-10-19-2.log)

**Comment by SnightOfTheSnurch** [comment]
> Do you have your client logs? If this is a client crash, the error will only be listed clientside, not on the server (current server logs don't show the error). In `logs` and `crash-reports` on your clients is where you would look for that info.

I have posted my clientside crash log, apologies for the long delay Ya boi was shleepy lol

**Comment by SnightOfTheSnurch** [comment]
> [2022-10-19-2.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9838240/2022-10-19-2.log)


It seems the FATAL error consistent with the MineColonies/Structurize tool can be found at [19Oct2022 22:01:25.517]. I'm not even remotely fluent in code so I'm not quite too sure what the error message means, but that is when it seems the client log goes a little apeshit.

**Comment by tillvit** [comment]
Had the same issue, did some digging in logs.
Seems like that structures in the structurize/schematics folder aren't being loaded properly. The mod finds 0 structures to load and the dropdown menu for the GUI tries to index an empty array, crashing the client.

```
[21Oct2022 11:02:24.111] [Render thread/WARN] [structurize/]: No file found during schematic discover. Things may break!
[21Oct2022 11:21:47.019] [Render thread/ERROR] [structurize/]: Structures: schematics/fill with md5 null.
[21Oct2022 11:21:47.020] [Render thread/ERROR] [structurize/]: Structures: schematics/dig with md5 null.
[21Oct2022 11:21:47.021] [Render thread/ERROR] [structurize/]: Structures: schematics/supplycamp/infernosupply with md5 null.
[21Oct2022 11:21:47.021] [Render thread/ERROR] [structurize/]: Structures: schematics/fields/warped/basic_farm with md5 null.
```

I can't really debug this right now but hopefully this contributes something

**Comment by Saereth** [comment]
This seems like the client and server have different schematics and the schematics are null (missing or ccupt), looks like a misconfiguration. Please provide a screenshot of client and server schematic files showing file size

**Comment by tillvit** [comment]
Just checked, the aternos files are missing the schematics. Seems like the installation by them doesn't include them. I added them back, but the client doesn't seem to receive them from the server.
Here are the client and server files: 
Client:
<img width="651" alt="Screenshot 2022-10-21 at 5 01 31 PM" src="https://user-images.githubusercontent.com/15373524/197306637-ced3604a-af12-4cf3-a747-a334ffc949bd.png">
Server:
<img width="713" alt="Screenshot 2022-10-21 at 5 01 22 PM" src="https://user-images.githubusercontent.com/15373524/197306633-32bc0623-6e45-4c0b-aa5e-673f1ee84dcf.png">

**Comment by Saereth** [comment]
the client wont receive them from the server, the client should have them on its own from the installer. try doing a fresh install of the pack with the ftbapp and grab the schematics from there and copy them to your server and client schematics folders

**Comment by tillvit** [comment]
I tried that, the screenshot of the server files is from downloading the world from aternos after copying client schematics there. Just to check, I tried reinstalling the client files and it still crashes.

**Comment by Saereth** [comment]
your warped folder is missing a TON of schematics, something is not copying correctly.

**Comment by tillvit** [comment]
Forgot to expand the last folder, sorry
server
<img width="443" alt="Screenshot 2022-10-21 at 5 37 28 PM" src="https://user-images.githubusercontent.com/15373524/197308545-52388a4f-3ca5-4aa5-b896-634b3a210cea.png">
client
<img width="431" alt="Screenshot 2022-10-21 at 5 37 24 PM" src="https://user-images.githubusercontent.com/15373524/197308550-f0b8443e-fbf8-4861-a36e-0e930e25d195.png">

**Comment by Saereth** [comment]
ok with the files in place now can I get a freshcrash log

**Comment by tillvit** [comment]
https://gist.github.com/tillvit/eaf113b36880095ec223c7cd1af466d2

**Comment by Saereth** [comment]
what are the file sizes on those both as well

**Comment by tillvit** [comment]
They are the exact same
Server
<img width="678" alt="Screenshot 2022-10-21 at 6 57 32 PM" src="https://user-images.githubusercontent.com/15373524/197311529-e15a1ca8-76c8-42c0-9937-abc8887bac10.png">
Client
<img width="664" alt="Screenshot 2022-10-21 at 6 57 39 PM" src="https://user-images.githubusercontent.com/15373524/197311533-e422cee3-745b-4809-bd57-5cb10ea1b3a0.png">

**Comment by SnightOfTheSnurch** [comment]
You guys are smart bois! I wanna say thank you for taking the time to help solve this.

**Comment by Saereth** [comment]
Does anyone else crash on your serverr with this issue or only you out of curiosity

**Comment by SnightOfTheSnurch** [comment]
> Does anyone else crash on your serverr with this issue or only you out of curiosity

It happens anytime anyone on the server uses a structurize/MineColonies UI related item (Build tool, Supply Camp. Supply Ship, etc.)

**Comment by tillvit** [comment]
Could be an aternos issue considering the schematic files are missing by default

**Comment by SnightOfTheSnurch** [comment]
I notified them of the bug in the discord, tried to open a ticket with the bot, and am now just kinda sitting in my DMs waiting for the bot to do literally anything

**Comment by SnightOfTheSnurch** [comment]
![image](https://user-images.githubusercontent.com/116124016/197315147-b5043f54-40e7-42e1-81ab-61d862c61c8b.png)

**Comment by SnightOfTheSnurch** [comment]
I guess I will have to wait

**Comment by tillvit** [comment]
Other player also crashes the same way on aternos server

**Comment by Saereth** [comment]
This seems like it might be some kind of permission error.. im not sure, the files do appear to be right but the crash is also reporting a zero length for the schematic file. I did just download and setup a fresh server instance on ubuntu 22 and it's working without issue. This is definitely seemingly like something more host specific I can't help with directly. If there is anything FTB can answer in regards to pack permissions for the server host feel free to put them in contact with me

**Comment by tillvit** [comment]
Ok, did some more digging. It seems like the structures are supposed to be placed in the server directory, not the world/ directory. Aternos only allows you to edit things in the world directory, so there are no structures on the server. Guess I'll have to run the server locally.

**Comment by Saereth** [comment]
ahh ok guess that makes sense, gonna go ahead and close this then

**Comment by SnightOfTheSnurch** [comment]
LETS GOOOOOOOOOO
![image](https://user-images.githubusercontent.com/116124016/197363415-70d23e8e-9618-41bd-9c59-a35ee4147629.png)

**Comment by JulianVennen** [comment]
Hi, Julian from Aternos here:
I was just about to comment my message from the screenshot above here too to clear this up.

In addition to that message: Clicking the download button on https://aternos.org/software/v/modpacks/ftb_inferno now will add the folder to your server.

**Comment by SnightOfTheSnurch** [comment]
Very nice, very kind, much love Julian

**Comment by Saereth** [comment]
> Hi, Julian from Aternos here: I was just about to comment my message from the screenshot above here too to clear this up.
> 
> In addition to that message: Clicking the download button on https://aternos.org/software/v/modpacks/ftb_inferno now will add the folder to your server.

Thanks! great to see
