### ISSUE TITLE
Anaconda not spawning[Bug]: 

### ISSUE THREAD

**Issue by sitnoveter** [FTBTeam/FTB-Modpack-Issues#1462]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

In one of the 7 deadly sins there is a anaconda spawner, 2 problems with it, 1st It does not spawn.
2nd if placed in creative and killed, the soul shard does not colect it, thus onlly able to break spawner in creative.
There is a loot chest under it.

### Steps to reproduce

Go to the 7 deadly sin that has the "pet" in it
and observe no anaconda never spawns.
In creative use a spawn egg and kill it, no soul captured with the shard.

### Expected behaviour

Anaconda to spawn and soul to be captured by the shard.

### Screenshots

![2022-10-18_16 57 07](https://user-images.githubusercontent.com/114706943/196531906-e7d07bd3-1b49-4612-b3ca-69d46e8a601e.png)

### Additional information

My screenshot is of a vry destroyed version of the place (I have looted the blocks)

**Comment by Saereth** [comment]
this is not a bug, it's a thought puzzle for the player, spoiler: You need to convert the spawner with an egg to something else to get at the chest.
