### ISSUE TITLE
[Suggestion]: Problems regarding ore and ingots

### ISSUE THREAD

**Issue by Voiderina** [FTBTeam/FTB-Modpack-Issues#1465]
### Modpack

FTB Inferno 

### Is your suggestion related to a problem? Please describe.

This is a list of problems regarding ores I have come across

[Create]
-Some crushed ores not being smeltable after being crushed by the crushing wheels which are:
(Tin, Lead, Aluminium, Uranium)

-Some ores not having the ability to be washed into nuggets for not having a nugget variant which are:
(Copper, Tin, Lead, Aluminium, Uranium)

-odd outputs per ore crushed for copper ore giving 5 crushed per stone ore and 7 per deepslate ore, and everything else having 1 per stone ore and 2 per deepslate ore (2 per deepslate is not consistent for: anything but gold, iron and zinc)

[AE2]
-Crushed Fluix dust not being obtainable through the IE crusher, the occultisim crusher and FTB interactions macerator, and only being obtained through the mine colonies crusher

-Crushing Certus Quartz ore can only be done in the IE crusher and not in the occultisim and FTB interaction counterparts

[Thermal Series]
-recipe for constantan ingot and block requiring both variants from immersive engineering and thermal series with the IE version being completely unobtainable meaning the block can't be made for bee pollination 

[EvilCraft]
-Dark Gem powder not being created using the macerator like its IE and occultisim counterparts

[Apotheosis]
-Gem dust not being created using the crusher spirit and the macerator like their IE counterpart g the crusher spirit and the macerator like their IE counterpart

**Comment by GoldenIsy** [comment]
Not all Combs can be directly Mixed (Create) into Ingots. The two most important would be Lead and Silver, that way all Singularities could be created with this production Chain.

**Comment by Saereth** [comment]
1) fixed the unsmeltable ores,

2)not all crushed ores are washable by even create standards, copper is vanilla and doesnt have a washing recipe for instance so 
I wont be adding those ores when there is a viable route to ingot already

3) copper output standard, its buffed in this pack via all processing methods so this is fine. the deepslate variants are create internal decisions so I'll leave those as they doint negatively impact the pack

4) fluix can now be crushed in the immersive crusher, macerator or crusher spirit, same with certus

5) Constantan block/ingot conversion to the correct variety should work now

6) dark gems can now be crushed in the IE crusher and ftbic macerator

7)  add it to the macerator and crusher now
