### ISSUE TITLE
[Bug]: Placed Dark Tank does not drop when broken with Miner's Soul trinked equipped

### ISSUE THREAD

**Issue by AngeloAugustoCSW** [FTBTeam/FTB-Modpack-Issues#1466]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Log Files

[Here is the part when the tank is broken with the trinket](https://paste.ee/p/hoKCw)

### Describe the bug

When placed, Dark Tank does not drop when broken while having Miner's Soul equipped, instead it`s still there, tank appears when right clicked with no liquid inside. Right clicking again shows liquid if there is any on tank. Player collides and get "stuck" when trying to walk on where the tank is placed

### Steps to reproduce

1. Place the tank
2. Equip Miner's Soul trinket
3. Break it 

### Expected behaviour

The tank won't drop as an normal block, instead it will be there

### Screenshots

Breaking the tank while following the steps above:
![MinerSoul_trinket_bug](https://user-images.githubusercontent.com/71052653/196770264-8f2dc280-981d-480f-856e-b3ccc1a583a2.gif)

**Comment by Saereth** [comment]
https://github.com/Cozary/Issue-Tracker/issues/41
