### ISSUE TITLE
[Bug]: ghast fireballs destroy blocks in claimed chunks

### ISSUE THREAD

**Issue by therob** [FTBTeam/FTB-Modpack-Issues#1467]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

Fireballs shot from ghasts can destroy blocks in claimed chunks with `"ftbchunks:allow_explosions": 0b`. TNT and creepers don't destroy blocks in claimed chunks.

### Steps to reproduce

1. place a block in a claimed chunk that can be blown up (like a chest, sign or netherrack)
2. get a ghast to shoot at it
3. see the block get destroyed

### Expected behaviour

ghast fireballs follow the same rules as TNT and creepers

**Comment by Saereth** [comment]
this is an issue with ftb chunks and has been reported there, we will update when they do, closing this for now as its a duplicate issue we're already tracking
