### ISSUE TITLE
[Bug]: Tamed foxhound tries to murder your minions

### ISSUE THREAD

**Issue by WolfWhiteFire** [FTBTeam/FTB-Modpack-Issues#1468]
### Modpack

FTB inferno

### Modpack version

1.0.3

### Describe the bug

Tamed Foxhounds, when you have them following you, will try to murder your MineColonies minions when nearby. They will also try to do it while sitting, but can't do much due to being immobile.

They don't seem able to hurt the minions (or at least the fireproof ones), but will try anyways.

### Steps to reproduce

1. Spawn and tame a foxhound
2. Create a MineColonies colony (or maybe just spawn a minion, not sure if that will work).
3. Have the foxhound follow you instead of sitting.

### Expected behaviour

I expected the foxhound to follow me normally.

### Additional information

Admittedly, it was pretty funny watching my enkindling foxhound chase around a poor minion while throwing fireballs at it, but this definitely doesn't seem intentional.

**Comment by Saereth** [comment]
Yeah this is something quark would have to specifically fix and I doubt it
will happen unfortunately

**Comment by tyler489** [comment]
Quark dev said they were "playing" with the minions here https://github.com/VazkiiMods/Quark/issues/3759
Not sure if thats intended behavior or not

**Comment by Saereth** [comment]
its intended behavior, it doesnt know about/care about mobs that are passive to you. Since quark doesnt seem intereted in fixing it/adding a blacklist the only way would probably be by making a mixin mod which is unlikely to happen.
