### ISSUE TITLE
[Bug]: Can't start the game

### ISSUE THREAD

**Issue by Faalcc** [FTBTeam/FTB-Modpack-Issues#147]
### Modpack

FTB University 1.12

### Modpack version

1.2.1

### Log Files

https://paste.ee/p/7diet

### Describe the bug

I cant start the game, it gives me error 1

### Steps to reproduce

Open the launcher and press play

### Expected behaviour

Not starting the game?

**Comment by Jake-E** [comment]
You have corrupt files. Re-download the pack.
