### ISSUE TITLE
[Suggestion]: Chipped blocks should also have the speed modifier bonus

### ISSUE THREAD

**Issue by Nagapito** [FTBTeam/FTB-Modpack-Issues#1470]
### Modpack

FTB Inferno

### Mod suggestion

Chipped mod as a lot of decorative variants that could be used on paths but they do lack the speed bonus.
Would be nice, if possible, to have these bonus on the chipped block variants so we could have more alternative blocks for paths

**Comment by Saereth** [comment]
Probably not gonna add the chipped blocks here, everytime they walk over a path block its looking over all valid block types to see if they are on one. Adding all the chipped blocks would increase that list substantially and with potentially hundreds of colonists on a server running over many blocks this can become quite tps intensive to grow the list too far sadly. 

Shame, I would like to add them as well
