### ISSUE TITLE
[Bug]: Netherite chestplate can still be melt in a smeltery

### ISSUE THREAD

**Issue by Nagapito** [FTBTeam/FTB-Modpack-Issues#1471]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

we can still melt the netherite chestplate in a foundry/smelter and get a netherite ingot and a diamond(foundry). 
This is probably due the fact that the smelting recipe is actually tconstruct:smeltery/melting/metal/netherite/chestplate instead of tconstruct:smeltery/melting/metal/netherite/chest as it is currently in the scripts

### Steps to reproduce

Check usages of netherite chestplate

### Expected behaviour

Should not be possible to smelt it

### Screenshots

![image](https://user-images.githubusercontent.com/4959346/196958198-cc1ad753-7247-48a8-b07a-20fd0f86080a.png)

**Comment by orbidlo** [comment]
Also diamond pixkaxe and axe melts into diamonds.
