### ISSUE TITLE
While Experience Battery equipped, using the Experience Obelisk gives free experience.

### ISSUE THREAD

**Issue by boraberk** [FTBTeam/FTB-Modpack-Issues#1472]
### Modpack

FTB Inferno

### Is your suggestion related to a problem? Please describe.

While Experience Battery equipped, using the Experience Obelisk gives free experience.
Starting exp:
![2022-10-20_22 01 58](https://user-images.githubusercontent.com/24351893/197035633-33353429-7697-43af-bc4c-2be94722140a.png)
After taking experience and resubmitting:

![2022-10-20_22 02 10](https://user-images.githubusercontent.com/24351893/197035824-a4196b0b-5af7-462c-afa4-e867e53cb878.png)

**Comment by Saereth** [comment]
yeah these two seem mutually incompatible so I'll probably just disable the xp battery

**Comment by Saereth** [comment]
actually on second thought, im gonna leave this. Doesn't break the pack and makes actually finding that item way better. We'll leave this as a nice interaction for people to find :)
