### ISSUE TITLE
[Bug]: Holding enchant does not affect COFH satchel's

### ISSUE THREAD

**Issue by Nagapito** [FTBTeam/FTB-Modpack-Issues#1475]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

The holding enchant cannot be applied to satchels and has no effect on them.
If this is an intended feature, then the leatherworker tradeit is misleading since it seems like he is selling a nice satchel with holding X and it turns out just a normal satchel...

### Steps to reproduce

Try to apply holding enchant to satchel

### Expected behaviour

Satchel capacity should increase with holding enchant

### Screenshots

Satchel trade with enchant
![image](https://user-images.githubusercontent.com/4959346/197055120-163f59f7-c275-48ff-a725-144cafdea091.png)
Resulting satchel capacity
![image](https://user-images.githubusercontent.com/4959346/197055182-abf0e382-e230-48b6-9367-34f85d66731f.png)

**Comment by Saereth** [comment]
this is a cofh issue not something we can control, when it's fixed it'll update. It's definitely not a normal satchel though, it has its upgrades installed making it much better than a standard satchel
