### ISSUE TITLE
[Bug]: Entity distance

### ISSUE THREAD

**Issue by Bl4ckstaar** [FTBTeam/FTB-Modpack-Issues#1476]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

Mobs only become visible to me if they are in a 48 (or 47 not realy sure) block radius no matter how high i set the options for entitys visibility

my options for Render Distance and simulation Distance are both at 32

Entity Distance is at 500%

i notice this in FTB inferno i did tests in the latest direwolf20 pack aswell but same issue, in vanilla i had no issue

is that normal and i have to deal with it ?
( I asked the question in the discord, where the assumption was made that there was a problem with an optimization mod but either the problem is with everyone and no one cares or only I have the problem 

### Steps to reproduce

1. open a new world
2. set the options for Entitys visibility higher

### Expected behaviour

If i set the option for Entitys high i expect that the game follow the options i set in the option window

### Screenshots

![Bild_2022-10-21_183012270](https://user-images.githubusercontent.com/116336678/197244527-192f4f07-6ed8-4215-9769-0cba7d555989.png)
![Bild_2022-10-21_183029014](https://user-images.githubusercontent.com/116336678/197244580-00318e29-758e-44df-848b-b804dd6372d9.png)
![Bild_2022-10-21_183043725](https://user-images.githubusercontent.com/116336678/197244627-f477c28d-ea9d-4a82-a60e-d27d1dbaa78d.png)
![Bild_2022-10-21_183106968](https://user-images.githubusercontent.com/116336678/197244700-a0a6434f-ea76-4c4b-8d0d-d1e90bced380.png)

**Comment by Saereth** [comment]
Uncheck enable max entity distance, should sort it for you

**Comment by Bl4ckstaar** [comment]
I appreciate the help but that didn't help

**Comment by Saereth** [comment]
Disable milk of magnesium and see if that does

**Comment by Bl4ckstaar** [comment]
Sadly that didnt help either

**Comment by Saereth** [comment]
Take out oculus and rubidium and see if that helps

**Comment by Bl4ckstaar** [comment]
Unfortunately nothing changes, i still have this issue

**Comment by Saereth** [comment]
Can you provide some screen shots as I don't have this issue personally
it's difficult to pin down

**Comment by Bl4ckstaar** [comment]
sorry I should have done that earlier.
The minimap shows there should be a lama on top of the piller but its not visible i did this screen shot in FTB Inferno with the option above and all mods loaded 
![2022-10-21_21 01 31](https://user-images.githubusercontent.com/116336678/197270455-c64db797-17b4-40c7-b137-87e0761a951d.png)

**Comment by therob** [comment]
I did some digging in the configs and this issue seems to be related to the mod _It Shall Not Tick_. Setting `maxEntityTickDistanceHorizontal` in `config/itshallnottick-common.toml` to a higher value allows entities to render further away. The default value is 48^2. Either _It Shall Not Tick_ causes this or another mod prevents non-ticking entities from rendering.
