### ISSUE TITLE
[Bug]: No way to Craft Crimson Ladder with Minecolonies

### ISSUE THREAD

**Issue by GoldenIsy** [FTBTeam/FTB-Modpack-Issues#1478]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

Miners need Crimson Ladders, due to a Bug they are uncraftable.
Thats fixed with a workaround by KubsJS which implements a dummy item.

But only the dummy Item is craftable by the carpenter from Minecolonies, not the next Step to really craft the ladder.
So the Colonie is not self reliant. Its only fixable in Lategame, but at that point there is no need for the Miner anymore.

### Steps to reproduce

Try to Craft the Crimson Ladder with only Minecolonies.

### Expected behaviour

either fixing the Ladderproblem all together or impmenemting a carpenter recipie for the real ladder.

**Comment by Saereth** [comment]
You can teach builders and miners 2x2 crafting recipes, just yeah them to shape craft true kjs version into the quark version by putting it by itself in the crafting grid

**Comment by GoldenIsy** [comment]
Thanks for the Information! Maybe that Information could be at the Minerquest for new Minecolonieplayers like me.

**Comment by Saereth** [comment]
sounds like a good addition!
