### ISSUE TITLE
muffled / weird sounds[Bug]: 

### ISSUE THREAD

**Issue by bielabomba** [FTBTeam/FTB-Modpack-Issues#1479]
### Modpack

FTB Direwolf20 1.18

### Modpack version

v1.9.1

### Describe the bug

i feel like everything i do is muffled or just allways behind me i tought it was spatial audio but that doesnt seem to be it 

### Steps to reproduce

1. start the modpack
2. create a world
3. play 
4. 

### Expected behaviour

on other modpacks / versions of minecraft the audio sounds normal but here it doesnt

### Screenshots

none

**Comment by Raidobw2** [comment]
Hi, can you check your music & sounds settings in-game, are they tuned?

Also, how much FPS are you playing on?

**Comment by bielabomba** [comment]
music is turned on around 20 - 10 and everything 100 
FPS: 60 - 84

**Comment by Raidobw2** [comment]
Hmm, thanks. I'm not sure what would be causing this, as I've never heard anyone else experience that. I'll write a short list of things you should check:
- Make sure you use a recent Java version for the game (the FTB App does this automatically if you have it, in other launchers you need Java 17)
- Compare the game's audio with YouTube for instance
- Try using earphones/headphones versus speakers and is there any delay as well?
- Plugging your audio device somewhere else in your computer
- Checking if your audio card is near components that get really hot (such as a graphics card). The audio card's location inside your PC is where you connect the cable to say, your headphones. Best testing would be done when the PC is cold at boot
- If your OS is Windows, use the troubleshooter for audio (write "troubleshoot" on the Windows button to get started)
- Reinstall the sound drivers, or obtain new ones from the manufacturer's site (find your motherboard or PC online and check its drivers/support)

The only mods I'm aware of in the modpack that maybe could interfere with sounds are:
- connectivity
- extreme sound muffler
- mute

Up to you if you want to try removing them and seeing what happens.

Also, you could compare the DW20 1.18 pack to either FTB Inferno, FTB Plexiglass Mountain or FTB Chocolate. They all use the same Minecraft version, so I'm thinking maybe one of them doesn't have the issue? Chocolate has the least mods. At the worst hopefully this gives us more info.

Let me know if you find anything while troubleshooting this!

**Comment by bielabomba** [comment]
turns out i had spatial sound turned off in windows ( sorry just build a new one ) and that seems to be this issue

**Comment by Raidobw2** [comment]
Awesome, glad you could figure it out! Thanks for posting your solution as well for others coming across with problem :)

Since that seems resolved, I'll close this issue. Let me know if there's anything else in the future by making a new issue and enjoy playing!
