### ISSUE TITLE
[Bug]: Recipe Conflict: Empty Cell vs. Tin Gear

### ISSUE THREAD

**Issue by Infynis** [FTBTeam/FTB-Modpack-Issues#148]
### Modpack

FTB Cotton

### Modpack version

1.1.0

### Describe the bug

Astromine Tin Gears override the Tech Reborn recipe for Empty Cells, which makes it impossible to progress in Tech Reborn beyond the base level.

### Steps to reproduce

1. Enter a survival world
2. Get 4 Tin
3. Try to craft an Empty Cell

### Expected behaviour

You will receive a Tin Gear

**Comment by manmaed** [comment]
This  issue is now stale
