### ISSUE TITLE
[Suggestion]: Put rowboats back into the mod

### ISSUE THREAD

**Issue by R3Ked** [FTBTeam/FTB-Modpack-Issues#1480]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

For some reason, rowboats don't exist anymore. Why? They were the most convenient early-game way of transport, and you removed them for some reason. Can they be added back in, or at least let vanilla boats work?

### Mod suggestion

n/a

**Comment by Gaz492** [comment]
Thanks for your suggestion, unfortunately we are no longer adding new mods to this modpack, but we will take it into account for any future modpacks we make.
