### ISSUE TITLE
[Bug]: Crashing while rendering minecolony citizen with AMD GPU

### ISSUE THREAD

**Issue by Recio** [FTBTeam/FTB-Modpack-Issues#1481]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Log Files

https://pastebin.com/9vXcTa55

### Describe the bug

Loading the world + looking into a specific direction produces an instant crash trying to render a minecolony citizen according to the logs.

### Steps to reproduce

Log into the server.
Look into the colony direction.
Crash.

### Expected behaviour

No Crash

### Additional information

graphics card is an RX480 8GB.
Seems to be related to AMD GPUs, my friends with NVIDIA don't seem to be affected.

I tested both in windows 10 and latest optional AMD drivers, and Arch with kernel 6.0.2-arch1-1, both reliably produce a crash.

I've had this before and it was a citizen holding a shield with a banner, I also had the crash using one of the crafting terminals when the item would render.

**Comment by Recio** [comment]
To any maintainer I can provide a server for testing with guaranteed reproductibility on my side :)

Would be cool to see if this is for all AMD cards

**Comment by Recio** [comment]
So it seems to be a specific shield, might be in the drop pool for killing skilled+ mobs.

The shield in question is this one with this pattern

![image](https://user-images.githubusercontent.com/3674948/197294791-46e8b089-fb05-474b-90cd-c6abdb622890.png)

**Comment by Saereth** [comment]
Is there reason to believe this is an amd specific issue? This looks like a
mod generating a banner with an invalid resource which should impact anyone
regardless of gpu

**Comment by Recio** [comment]
From a pool of 3 playing I see this as being an issue that only affects me regardless of OS.
My other friends are using a GTX1660 super and an RTX3070.

They managed to remove the shield from the citizen and stored it in a chest, if I open the chest I crash instantly :P

**Comment by Saereth** [comment]
that's so weird that it only effects you, unfortunately looking through the stack trace its basically pure vanilla code crashing you so uhh.. I guess I'll report this one to mojang. Im glad you were able to at least yeet the offending shield off the colonist

**Comment by Raidobw2** [comment]
Try removing Oculus and Rubidium, see if that solves the issue. Oculus has a mixin into the Minecraft Banner Renderer and is being mentioned in the stacktrace `oculus-batched-entity-rendering.mixins.json:MixinBannerRenderer`
https://github.com/Asek3/Oculus/blob/1.18.2/src/main/java/net/coderbot/batchedentityrendering/mixin/MixinBannerRenderer.java

This looks like it coincides with the crash, potentially with function `iris$wrapBufferSource` which is modifying existing code. If removing it solves it, then we'll report it to Oculus

**Comment by Recio** [comment]
here's a fresh crash, seems to be the same issue.

https://pastebin.com/24vHdwFD

Also I can confirm, removing both oculus and rubidium doesn't help :smiling_face_with_tear: 

https://pastebin.com/wsakbGFQ

**Comment by Raidobw2** [comment]
Hmm that's a very peculiar issue. I've dug more with that in mind and found a similar issue at ATM7's repo, https://github.com/ldtteam/minecolonies/issues/7895.

This mentions https://github.com/AlexModGuy/AlexsMobs/issues/780 as the source of the crash for that other issue, so maybe it's a mod's specific banners causing this problem for you.

You can try removing the mod (Alex Mobs) and taking the world into singleplayer as a test!

Also, if your friends are able to hold the item, can they take it in their hands and type `/kubejs hand`? This will print a bunch of info on screen, if it fits inside a screenshot that would help. Otherwise that info will be instantly written to the game log (`latest.log`) as text and they can copy it if they prefer that way.

I'm not aware of much mods in Inferno that adds banner patterns (or even custom ones?) but possibly what I found out rings a bell for @Saereth

**Comment by Recio** [comment]
I have some more info from our play session last night, it was the colony banner on our colony.
Setting the colony banner to a white blank one worked fine and I haven't experienced a crash since then.
I'm not sure if the banner is random (in the sense that the pattern chosen was random on the colony creation)

I'll ask for one of them to do that :) 

Thanks for the follow up!

**Comment by Saereth** [comment]
this was found to be related to the flywheel backend and caused other issues, should now be resolved in the new update
