### ISSUE TITLE
[Bug]: Bees instantly get back into hive after leaving

### ISSUE THREAD

**Issue by SibiChu** [FTBTeam/FTB-Modpack-Issues#1482]
### Modpack

FTB Inferno

### Modpack version

1.0,3

### Describe the bug

Gotten into the mod Production bees and my bees get back into the hive instantly after leaving it and stay there for a solid 2 min at a time. Tried different biomes, room layouts, different flowers, different hives (wood) types and no luck. Can't get honey or honeycombs cuz they can't even get to the flowers.

### Steps to reproduce

Place a beehive anywhere with bees

### Expected behaviour

No combs or honey

**Comment by SibiChu** [comment]
Just a mention, it is on a server

**Comment by Saereth** [comment]
Can you post some screenshots

**Comment by SibiChu** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/116392280/197299014-b9ef6710-925b-4eda-b4a7-8518ba52ae47.png)
![Screenshot_3](https://user-images.githubusercontent.com/116392280/197299018-fe5aaebf-1d07-4610-827b-bbd6d6ab8b76.png)
![Screenshot_4](https://user-images.githubusercontent.com/116392280/197299022-3408a31c-1789-497e-a2f4-11a3f44eda9d.png)

**Comment by SibiChu** [comment]
The quartz are there for the quartz bee, that exits the hive just fine but does not want to "gather" honey at the quartz related blocks

**Comment by Saereth** [comment]
Do you have a glow crystal for lighting anywhere by

**Comment by SibiChu** [comment]
Yes there are shroomlite blocks along the celing.

**Comment by SibiChu** [comment]
I have just tested it in singleplayer, did it all the same, same hive, same biome, same building and it works just fine... I am lost, i didn't edit any files while creating the server, pulled the server from the official site so there "should" not be any issues with that.

**Comment by Saereth** [comment]
no I mean there is specifically a glow crystal block for lighting, it has a very large radius and can sometimes cause this behavior because it makes ghost blocks, can you provide a screenshot that shows your map as well

**Comment by SibiChu** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/116392280/197328938-af39d7fa-5ee7-4011-a61c-bed4afb212ef.png)
![Screenshot_6](https://user-images.githubusercontent.com/116392280/197328941-07ed2275-460f-4d0a-a163-2cad6b7878fb.png)
![Screenshot_7](https://user-images.githubusercontent.com/116392280/197328943-946e81da-3bd6-4bcc-b24b-be53c57a2c0e.png)
I have never made a glow crystal before, unless it can spawn naturally. I keep the bees in a house the capsule mod gives you as a quest reward that is supposed to be for the bees to get you started, i have tryed it out in a normal netherrack box aswell just for trying it out but no fix. I have 4 shroomlights in the houses that give light for the bees, they came with the capsule house spawn

**Comment by SibiChu** [comment]
Ok i swear to f****** god... I have started the server up to show you the screenshots that you requested and it is working fine now... they are making honey like normal, leaving their hives like they are supposed to AND I DID NOTHING BUT close the server, go to sleep and start it back up again...

Well @Saereth tnx alot for wanting to help me out anyway :)

**Comment by SibiChu** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/116392280/197329947-96cfe744-24fe-456d-8bae-317c82a8cf3b.png)
