### ISSUE TITLE
[Bug]: FTB Infinity Evolved crash

### ISSUE THREAD

**Issue by NLORDREBORN** [FTBTeam/FTB-Modpack-Issues#1484]
### Modpack

FTB Infinity Evolved

### Modpack version

1.7

### Log Files

https://pste.ch/biheteyota.sql

### Describe the bug

game crashes when start screen

### Steps to reproduce

click on play button

### Expected behaviour

opening the game

### Additional information

i use m1 mac mini

**Comment by Raidobw2** [comment]
Hi, has it worked before and have you tried reinstalling a second instance of the modpack to see if that did anything?

Also, can you put `-Duser.language=en -Duser.country=US` in the additional java arguments (in the FTB App, in the modpack's settings) and let me know if that helped launching the modpack
