### ISSUE TITLE
[Bug]: Inferno: unable to place capsules

### ISSUE THREAD

**Issue by Boekenkast999** [FTBTeam/FTB-Modpack-Issues#1485]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

When trying to place any capsule it says it is being blocked by some blocks. When i go to the given coordinate its just bedrock. Was able to place capsules just fine yesterday, started happening today.

### Steps to reproduce

Get a capsule
Try placing the capsule
See it getting blocked by bedrock

### Expected behaviour

place the capsule

**Comment by Boekenkast999** [comment]
downgrading my ftb inferno to 1.0.2 seems to have fixed the issue, not sure what was going on there

**Comment by Saereth** [comment]
We cant check on this without screenshots of the issue happening in 1.0.3, please update when you can and get us some screenshots of the issue.
