### ISSUE TITLE
[Bug]: Some items flickering in AE2 storage when in Dimensional Storage with Storage Bus

### ISSUE THREAD

**Issue by Senne-DC** [FTBTeam/FTB-Modpack-Issues#1488]
### Modpack

Inferno

### Modpack version

1.0.3

### Describe the bug

I've noticed some items were flickering in and out of my AE2 storage terminal even though they were not being imported/exported. Noticed the affected items were always stored in the Occultism Dimensional Storage Actuator.

![ae2flickeringstorage1](https://user-images.githubusercontent.com/2308797/197363891-33293b07-b4c4-4531-916a-e81996cf1359.gif)
![ae2flickeringstorage2](https://user-images.githubusercontent.com/2308797/197363893-6970bef5-4aa3-433a-a463-da337f214686.gif)
![ae2flickeringstorage](https://user-images.githubusercontent.com/2308797/197363895-57722d09-9fad-4b6e-9822-678fc28e377a.png)

### Steps to reproduce

Went into a test world to test it in a new small network and managed to reproduce it easily.
1. Create AE2 network with a storage bus on an Occultism Dimensional Storage Actuator
2. Put at least 3 items of the same type but with different enchantments in the dimensional storage. E.g. 3 iron axes with each a different set of enchantments
3. Open ME terminal and observe the items flickering.

![ae2flickeringstorage3](https://user-images.githubusercontent.com/2308797/197364282-4bd5da07-faac-466c-8d49-a9094bf9ec80.gif)
![ae2flickeringstorage2](https://user-images.githubusercontent.com/2308797/197364284-afb682ed-b535-424a-9b03-f36a233e9f05.png)
![ae2flickeringstorage3](https://user-images.githubusercontent.com/2308797/197364286-e5c0de3f-5b31-40db-ae1b-c151b26a2b3f.png)

### Expected behaviour

Items to not flicker

**Comment by Saereth** [comment]
Since this is a non specific pack issue I've forwarded it on to both ae2 and occultism to resolve, will update mods as they get updates avaialble.
