### ISSUE TITLE
[Bug]: Redstone vanished when crafting netherrack with tempered jar

### ISSUE THREAD

**Issue by R3Ked** [FTBTeam/FTB-Modpack-Issues#1489]
### Modpack

FTB Oceanblock

### Modpack version

1.15.1

### Log Files

Couldn't find log file, as FTB app doesn't take me to the file location

### Describe the bug

When crafting the 16 netherrack recipe using tempered jars, the redstone used vanishes and the craft doesn't start.

### Steps to reproduce

1: Insert 16 redstone and one bucket of lava into a tempered jar system via chests, glass jars, and pipes.
2: Start crafting.
3: See the bug.

### Expected behaviour

The redstone is used to start the crafting.

**Comment by Raidobw2** [comment]
Hi, would you be able to include screenshots of your in-game setup for us to reproduce? Thanks!

**Comment by R3Ked** [comment]
Alright, gonna load up the pack now.
Can you also tell me where to find logs so I can give you them?

**Comment by R3Ked** [comment]
![image](https://user-images.githubusercontent.com/20342336/197593309-4676a676-a278-42c9-9e5f-d1652a240832.png)
The redstone is stored in the chest.

**Comment by Raidobw2** [comment]
Sure thing, the log files should be accessible here:
![image](https://user-images.githubusercontent.com/17010632/197655037-743e2b3b-e136-4b0e-adac-57fe9544b95d.png)
The `latest.log` file is commonly known as the game log, usually that's the log that's the most helpful.

I'll go test this up in-game soon, thanks for adding a picture!

**Comment by R3Ked** [comment]
Ok, funny story, turns out my FTBA instance corrupted, and now I think all my OceanBlock progress is gone. No log here. :)

**Comment by Raidobw2** [comment]
Hmm, as long as you have the world or a backup in the `backups` folder, it's recoverable. Let me know

**Comment by R3Ked** [comment]
No, what I think happened is that I installed FTBA from your website, but then everything just disappeared. I installed FTBA again through Overwolf, but that's seperate.

**Comment by Raidobw2** [comment]
They are the same normally. Press Windows + R and put `%localappdata%\.ftba` in the box. If it opens up and you see a folder called "instances" that is not empty, your world files are within there. You can do a file search to locate the world

**Comment by Raidobw2** [comment]
About the bug itself, I'm unable to reproduce it. Looks like the redstone is consumed and the lava bucket from the jar is used instead... Maybe someone else can confirm or deny this. I'm using OB version 1.15.1 (latest as of now)

Note that the lava from the jar is consumed, not the bucket item in the chest

https://user-images.githubusercontent.com/17010632/197657658-0eabbc92-0c5a-4998-a700-abeab8232fad.mp4

**Comment by R3Ked** [comment]
Will take a look tomorrow, as I can't access my computer right now.

**Comment by R3Ked** [comment]
There are some instance folders, but the worlds are gone. The instances are probably from the one Oceanblock instance I made.

**Comment by manmaed** [comment]
This issue is stale and pack is no longer being worked on
