### ISSUE TITLE
[Bug]: Making Double Compressed Cobblestone Crashed The Game?

### ISSUE THREAD

**Issue by Ceru6479** [FTBTeam/FTB-Modpack-Issues#1490]
### Modpack

FTB Revelation

### Modpack version

3.6.0

### Log Files

https://pste.ch/ijonovejez.rb

### Describe the bug

The game crashed. While the client (FTB App) didn't crash, this is frustrating. No data was lost or rolled back and the world wasn't corrupted, The report claims a GUI issue with ExtraUtils2 and Tinkers'Construct at fault.

### Steps to reproduce

I attempted to create "Double Compressed Cobblestone" and something went wrong simultaneously. I believe I was holding the shift key while trying to place Compressed Cobblestone. 
This is most likely a mod conflict with Tinkers'Construct and ExtraUtils2; the Crafting Station (from Tinkers'Construct) attempted forcing an item from ExtraUtils2 into an invalid location (which in this case is Compressed Cobblestone going into the vanilla Furnace's output). This could affect other items from ExtraUtils2, but I'm unsure. Replication is inconsistent but this isn't a one-off.

### Expected behaviour

I wanted Double Compressed Cobblestone, not a 'Crash'.

### Screenshots

![2022-10-24_13 40 28](https://user-images.githubusercontent.com/116467020/197625305-4e14330b-3c06-4cf5-a12e-23ce83760367.png) 

![2022-10-24_13 40 18](https://user-images.githubusercontent.com/116467020/197625355-3fdd00d9-c211-4249-9bcb-a2a58b743f04.png)

### Additional information

This is my first bug report. Let me know if there are any issues with this, or tags I need to apply!
Edit as of 10/26/22: Added extra information from my comment to the main "issue report", along with speculation. Edited again to fix a typo.

**Comment by Raidobw2** [comment]
Hmm, did this happen more than once? The only trace of this problem on the web anywhere is https://github.com/AllTheMods/ATM3-Remix/issues/304.

I've tried reproducing it with Shift/not Shift and a Crafting Station from Tinker's Construct but to no avail, my game won't crash.

The only similarity you have with the other issue I mentioned is that both you were using Tinker's Crafting Station to craft the item. Would you be able to screenshot what is attached/next to the Crafting Station? If you are to disconnect the Crafting Station from nearby blocks or use a normal crafting table from Minecraft, do you still crash?

**Comment by Ceru6479** [comment]
![2022-10-24_13 40 28](https://user-images.githubusercontent.com/116467020/197625305-4e14330b-3c06-4cf5-a12e-23ce83760367.png) 


![2022-10-24_13 40 18](https://user-images.githubusercontent.com/116467020/197625355-3fdd00d9-c211-4249-9bcb-a2a58b743f04.png)


Here's two screenshots. In case they don't load; my Crafting Station is next to a vanilla furnace and a Spruce Chest from Quark. My next guess on why the game crashed is Tinkers'Construct trying to force an item into an invalid location, aka the output area of the furnace. I'm having trouble attempting to replicate this bug.

**Comment by Raidobw2** [comment]
Hmm I see. Thanks for the screenshots, they do work and I see them! I'm not sure exactly how this happened to be honest. If it reoccurs be sure to let me know, and leave this issue opened as well until we update the modpack again. Whoever updates the modpack on our team will have a look at the issue quickly and can ping me about it.
One way I see this being solved is an update in CodeChickenLib/Extra Utilties 2 potentially, but 1.12.2 is not really supported anymore, so this will be hard to fix...

A workaround would be to use a normal crafting table to craft the double compressed cobblestone, or compacting drawers if you want to automate it

**Comment by Ceru6479** [comment]
Thanks for the assistance, I'll make sure to update again when the modpack does,
