### ISSUE TITLE
[Bug]: Eternal Water block gets duped when broken by Ars break spell

### ISSUE THREAD

**Issue by orbidlo** [FTBTeam/FTB-Modpack-Issues#1492]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

When I break the Eternal Water block with Ars spell, I get two instead of one. When I break it with a pickaxe I get normally only one.

### Steps to reproduce

1. Set Eternal Water source somewhere
2. Equip simple Ars Touch+Break spell
3. Shift right click to break the Eternal Water block
4. Get duped block along with original one 

### Expected behaviour

Breaking with Ars spell gives only 1 block

**Comment by Saereth** [comment]
Already previously reported to both devs and we're tracking it, ty, closing this one as its a duplicate
