### ISSUE TITLE
[Bug]: Wilden Stalker kills does not give soul into Soul Shard

### ISSUE THREAD

**Issue by orbidlo** [FTBTeam/FTB-Modpack-Issues#1493]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

When I kill Wilden Stalker it's soul is not fed into my soul shard and thus I am not able to break their spawner.

### Steps to reproduce

1. Have wilden stalker spawner (e.g. in a sin dungeon)
2. Equip a weapon (with or without Soul Steal) and empty soul shard in your hotbar
3. Kill wilden stalker
4. Soul Shard does not gain soul and thus spawner cannot be broken

### Expected behaviour

Soul Shard gains a soul of killed wilden stalker when on hotbar

**Comment by Raidobw2** [comment]
Linked with https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1385#issuecomment-1288083808

**Comment by Nagapito** [comment]
Note that none of Ars Nouveau mobs are configured to work with soul shards so... maybe also add the remaining mobs besides Wilden Stalkers
