### ISSUE TITLE
[Bug]: Dimensional Storage with LaserIO extraction node cause severe TPS issues

### ISSUE THREAD

**Issue by 766b** [FTBTeam/FTB-Modpack-Issues#1496]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

LaserIO and Dimensional Storage interaction cause severe TPS drop, all the way down to 2 TPS.

### Steps to reproduce

1. Place LaserIO node beside Dimensional Storage Actuator
2. Insert Item Card with extraction mode facing Dimensional Storage Actuator
3. /forge tps
4. TPS will go down all the way to 2 TPS.

### Expected behaviour

No TPS drop

**Comment by Raidobw2** [comment]
Hi, could you run a Spark profile, that would indicate the lag sources most likely.

You can run a Spark profile with `/spark profiler`, wait 15 seconds with the lag, then type `/spark profiler --stop` to stop it. It will give you a link that you can post here. Thanks in advance!
![image](https://user-images.githubusercontent.com/17010632/197483433-5be7e443-30b0-4f15-a2fe-596fde64bb58.png)
P.S. You need OP on the server to do that, it can also be done from the server's console

**Comment by Saereth** [comment]
since there's been no response here for a while and I cant reproduce this I'm closing the issue, reopen if you can reproduce or provide more info
