### ISSUE TITLE
[Bug]: My pc crashed and my world got corrupted

### ISSUE THREAD

**Issue by SoySalvaa35** [FTBTeam/FTB-Modpack-Issues#1497]
### Modpack

FTB Academy

### Modpack version

1.12.2

### Describe the bug

So I was playing the ModPack and my pc crashed (blue screen) when it turned on again i entered into the modpack and I was in the school (again) and i touched exit school and lost my items 

### Steps to reproduce

You cant.

### Expected behaviour

I Expected to lose my world but i had a backup

### Additional information

Solved it loading the backup

**Comment by Raidobw2** [comment]
Modpacks crashing have different behaviors depending on how they crash, the worst cases I've seen happen if electricity is cut from the computer or a blue screen happens.

Most of those times there is data corruption as you mentioned and the best and easiest way to recover the data is through a backup.

Do you need help with loading the world, recovering items, etc? It's not clear in your post, and avoiding data loss is not something I can fix if a computer suddenly goes offline, so I can only help you with the aftermath.

If you have a backup, that's great and I recommend that as the solution.

If you need to cheat in items to recover them, you can press Escape and click "Open to LAN" and enable cheats there. This transforms your world into a LAN server with cheats until you exit the world normally, once. When you re-enter the world, it will be Singleplayer again. When you have cheats, you can switch to creative with the buttons in the top left of your inventory.

If you lost quests, when you have cheats ON, you should be able to type `/ftbquests editing_mode` in the chat. Open your quest book and right-click some quests to complete them instantly. This is useful if you lost some quests if you had to use the backup.

Let me know if there's anything else you need help with!

**Comment by manmaed** [comment]
@aaronhowser1 any word on this has this been fixed
this will auto close in 2 weeks if no response

**Comment by aaronhowser1** [comment]
It has not been
