### ISSUE TITLE
[Bug]: Crash when interacting fletcher villager

### ISSUE THREAD

**Issue by boraberk** [FTBTeam/FTB-Modpack-Issues#1498]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Log Files

[crash-2022-10-23_20.38.25-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9847149/crash-2022-10-23_20.38.25-client.txt)

### Describe the bug

Crashes when I try to interact with level 2 fletcher villager.

### Steps to reproduce

1.  Make a fletcher villager
2. Advance fletcher to second tier by trading
3. Interact with villager

### Expected behaviour

It should open trade GUI

**Comment by TheonlyTazz** [comment]
current custom trade for fletcher is:
```js
    {
      "offer": {
        "itemKey": "minecraft:tipped_arrow",
        "amount": 16,
        "advancedNBTData": "{Potion:\"apotheosis:strong_wither\"}",
        "priceModifier": 0
      },
      "request": {
        "itemKey": "evilcraft:dark_gem",
        "amount": 1,
        "priceModifier": 0
      },
      "tradeExp": 6,
      "maxUses": 10,
      "priceMultiplier": 0.1,
      "tradeLevel": 2
    },```
    
the syntax looks right i will follow up on this issue later today
