### ISSUE TITLE
[Bug]: Mahou Tsukai - Durability Exange wont trigger

### ISSUE THREAD

**Issue by creepercrack** [FTBTeam/FTB-Modpack-Issues#1499]
### Modpack

FTB University 1.16

### Modpack version

1.7.0

### Describe the bug

The quest's task "Look at a a Durability Exange blood circle" does not trigger when looking at a working Durability Exange

### Steps to reproduce

1. Unlock the quest
2. Make a Durability exange Blood Circle
3. Look at a Durability exange Blood Circle
4. The quest wont trigger

### Expected behaviour

The quest triggers

### Screenshots

![2022-10-23_20 56 49](https://user-images.githubusercontent.com/47305546/197410470-990df735-831b-41e6-ba80-d2793adc1017.png)
![2022-10-23_20 56 53](https://user-images.githubusercontent.com/47305546/197410472-68225112-1f22-4571-a9df-98b3cf6e2516.png)

**Comment by Raidobw2** [comment]
For now you can switch to creative and type `/ftbquests editing_mode` in the chat. Once you do, open the quest book. Right click the quest and complete it instantly.

To get creative on a singleplayer world you can press Escape and open it to LAN, with cheats enabled.

Thanks for reporting

**Comment by creepercrack** [comment]
After poking a bit I managed to fix the quest
The Observation requirement Observe field should be edited
The value sould be set to "mahoutsukai:mahoujin_durability_exchange" instead of ""
Should look like in the picture:
![Sin título](https://user-images.githubusercontent.com/47305546/198377712-d8908065-531d-4ad0-824a-62ca46b456a4.png)

**Comment by Raidobw2** [comment]
Thank you for posting the fix! 🙂
