### ISSUE TITLE
[Bug]: Unable to craft Reliquary Slime Pearls pre-overworld

### ISSUE THREAD

**Issue by Senne-DC** [FTBTeam/FTB-Modpack-Issues#1502]
### Modpack

Inferno

### Modpack version

1.0.3

### Describe the bug

Unable to craft Reliquary Slime Pearls pre-overworld.

They need Earthslime Cake which needs Tall Slimy Grass
To grow those you need Earthslime Grass though, which can only be found in Overworld. (You get Earthslime Dirt as a quest reward but I haven't been able to get it to grow grass)
![image](https://user-images.githubusercontent.com/2308797/197531370-1eecf505-9d1d-4573-bbbb-9bb60b5f28e0.png)
![image](https://user-images.githubusercontent.com/2308797/197531377-742ea666-68bc-4512-8084-d183ea01bb88.png)

### Steps to reproduce

-

### Expected behaviour

Allow crafting of Reliquary Slime Pearls pre-overworld

**Comment by Raidobw2** [comment]
Linked with https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1410
