### ISSUE TITLE
[Bug]: Reliquary Witch Hat unobtainable

### ISSUE THREAD

**Issue by Senne-DC** [FTBTeam/FTB-Modpack-Issues#1503]
### Modpack

Inferno

### Modpack version

1.0.3

### Describe the bug

The Reliquary Witch Hat is unobtainable because it has no recipes and Reliquary mob drops are disabled.
![image](https://user-images.githubusercontent.com/2308797/197532641-922b84c6-24c1-42fd-b869-631ff84bf8c6.png)

### Steps to reproduce

-

### Expected behaviour

Perhaps a Summoning Altar recipe similar to other Reliquary items?

**Comment by Raidobw2** [comment]
Linked with https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1410
