### ISSUE TITLE
[Bug]: "FE Transformer" Behavior

### ISSUE THREAD

**Issue by iasazo** [FTBTeam/FTB-Modpack-Issues#1506]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

1. Breaking the "FE Transformer" with a pick doesn't drop anything.  The "WAILA"-like tool tip shows a green check. 

2. The "FE Transformer" only accepts 256 RF/t from the "Alternator".  Possibly intended?

### Steps to reproduce

1. Break the FE Transformer
2. No item is dropped

1. Use FE Transformer
2. Observe it only transfers up to 256 RF/t

### Expected behaviour

To drop the item form of "FE Transformer" when broken.

**Comment by Saereth** [comment]
I cant reproduce this, mines up fine for me. The alternator is buffed in next patch.
