### ISSUE TITLE
[Suggestion]: Increase the Capsule Mod's Preview Time

### ISSUE THREAD

**Issue by hanky21** [FTBTeam/FTB-Modpack-Issues#1508]
### Modpack

Inferno

### Is your suggestion related to a problem? Please describe.

For ease of use it might be best to increase the default preview time for the capsule mod so its easier to line up and learn when first using.

**Comment by Saereth** [comment]
I agree with you but this is not currently possible, I will forward the suggestion on to the mod dev however
