### ISSUE TITLE
[Bug]: Lava Grotto Deployable Starter does not deploy to previewed location when rotated

### ISSUE THREAD

**Issue by michaeljory** [FTBTeam/FTB-Modpack-Issues#1509]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

When deploying the capsule quest reward "Lava Grotto Deployable Starter" from the quest "It's all uphill from here", the preview of the deployment is misaligned with where the structure will be deployed if you rotate it.  The actual deployment will be offset by the full width of the structure from where the preview shows, deploying it in a completely different location.

### Steps to reproduce

1. Right click while holding the "Lava Grotto Deployable Starter" capsule
2. Left click to rotate the structure
3. Note the location where the preview shows it will deploy
4. Right click again to deploy the structure
5. Note that the structure did not deploy where the preview displayed

### Expected behaviour

I would expect the structure to deploy to the location outlined by the preview

**Comment by Saereth** [comment]
This can happen when rotating some capsules, nothing we can do to fix it from a pack standpoint, however. The Capsule dev has been made aware and we'll update the pack when the mod updates but they did not have any kind of ETA and the issue seemed low priority on their end so no telling when we'll see a fix.

**Comment by Saereth** [comment]
structurize updated in 1.5.0 may help with this although its till not 100%
