### ISSUE TITLE
[Bug]: Inconsistent Crash when using Vengeance Pickaxe

### ISSUE THREAD

**Issue by sme23** [FTBTeam/FTB-Modpack-Issues#1513]
### Modpack

FTB Inferno

### Modpack version

1.1.1

### Log Files

https://pastebin.com/Dgzcc6vt

### Describe the bug

Upon mining a block of Diamond Ore with a Vengeance Pickaxe, the game immediately crashes, but only sometimes

### Steps to reproduce

This happened initially in the described scenario, but I've not been able to reproduce it. I suspect it has to do with the mob whose spirit is spawned from using the pickaxe? and that's not easy to reproduce; if so, the block mined also shouldn't matter. Still, probably worth reporting regardless. Apologies if this is unhelpful

### Expected behaviour

Game to not crash

**Comment by Raidobw2** [comment]
Hmm, I'm unsure but potentially it could be caused by ItShallNotTick (ISNT). You can try removing it from the mods folder and seeing if the issue happens again after some time.

It's a tick optimizer that prevents mobs from ticking when they are far away

**Comment by Saereth** [comment]
I blacklisted vengeance spirits in 1.2 I think that should solve this as well, re-open if the issue still happens after the update
