### ISSUE TITLE
[Bug]: Death desyncing permissions on colony

### ISSUE THREAD

**Issue by Kangy1103** [FTBTeam/FTB-Modpack-Issues#1514]
### Modpack

FTB Inferno

### Modpack version

1.1.1

### Describe the bug

On my server since updating to 1.1.1 from 1.0.3 the guards in my colony are seeing my friend who has Officer permissions as an enemy and attacking them. After they respawn they also can't interact with any of the Minecolonies stuff. It's like his perms are being reset until he disconnects and reconnects from the server

### Steps to reproduce

1. Be officer of colony
2. Walk around colony
3. Be attacked by guard
4. Try but fail to interact with Minecolonies stuff
5. Log out and back in to be able to interact but still get attacked

### Expected behaviour

Guards shouldn't be attacking officers

**Comment by orbidlo** [comment]
There is bug when you die, your ownership possibly other permissions get bugged until you relog, so could be connected. Have you tried removing his permission and adding him again while he is away from colony (to not briefly anger anyone)?

**Comment by Kangy1103** [comment]
> There is bug when you die, your ownership possibly other permissions get bugged until you relog, so could be connected. Have you tried removing his permission and adding him again while he is away from colony (to not briefly anger anyone)?

We did try this, and changing a permission that allows officers to attack guards and everything seems good so far
