### ISSUE TITLE
[Bug]: Evil Craft's Keybinding options doubled up

### ISSUE THREAD

**Issue by ParrotParrot** [FTBTeam/FTB-Modpack-Issues#1515]
### Modpack

Inferno

### Modpack version

1.1.1

### Describe the bug

Evil Craft's "Open Exalted Crafter" and "Toggle Farting" key binding options are doubled up. They will act as if they were exact copies and will even light up together when changing the key.

### Steps to reproduce

Options -> Controls -> Key Bindings -> Scroll down to Evil Craft's section

### Expected behaviour

A single option for each of them should suffice

### Screenshots

![image](https://user-images.githubusercontent.com/6126426/198420247-9f0496d4-4209-4dba-b03f-e81d916377d0.png)

**Comment by Saereth** [comment]
opened an issue with evilcraft dev
https://github.com/CyclopsMC/EvilCraft/issues/new?assignees=&labels=&template=Bug_report.md
