### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Tintainia** [FTBTeam/FTB-Modpack-Issues#1516]
### Modpack

FTB Inferno

### Modpack version

1.0.3

### Describe the bug

My partner and I both share a minecolony, and we have gotten multiple "Breach is imminent" messages, but after the minute cooldown nothing happens. If we summon the gate via boss battles or the Apotheosis boss gate pearls, but the naturally generating ones have ceased.

### Steps to reproduce

Wait for a "Breach is imminent" message and see if a breach actually appears.

### Expected behaviour

I expected a gate to spawn and a breach to happen

### Screenshots

![bug](https://user-images.githubusercontent.com/116864198/198508230-c22c9006-ace5-4538-88f5-5c952a773a28.PNG)

**Comment by Nagapito** [comment]
Do you have latest version? 
That was a bug in 1.0.3. Update to the 1.1.1

**Comment by Raidobw2** [comment]
Indeed, update to 1.1.1 and if it happens again, you can comment here we'll reopen it
![image](https://user-images.githubusercontent.com/17010632/199427283-e5fc2158-c785-4ce8-a71d-6732d7c3cf9c.png)
