### ISSUE TITLE
[Bug]: Experience Obelisk XP Duping with Experience Battery

### ISSUE THREAD

**Issue by sme23** [FTBTeam/FTB-Modpack-Issues#1524]
### Modpack

FTB Inferno

### Modpack version

1.1.1

### Describe the bug

Repeatedly storing & retrieving experience in an Experience Obelisk will retrieve slightly more experience than you stored. This can be freely repeated to gain infinite experience.

### Steps to reproduce

1. Open Experience Obelisk
2. Store All 
3. Retrieve All
4. Repeat steps 2-3

### Expected behaviour

Consistent amount of xp stored & retrieved

### Screenshots

https://cdn.discordapp.com/attachments/1024733922745122897/1035639022212620528/2022-10-28_15-37-15.mp4

**Comment by Nagapito** [comment]
I cannot reproduce this...
Could you have some item that is causing you to get extra XP...!? And so cause this issue?

**Comment by sme23** [comment]
Oh! I have the Experience Battery from Nameless Trinkets equipped and entirely forgot about it lol. That's probably what makes this happen, since it gives extra xp when you level up
