### ISSUE TITLE
[Bug]: FTB App Fatal Exception when installing packs; with some troubleshooting already provided by Discord

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#1525]
### Modpack

FTB App; FTB Inferno, FTB Plexiglass Mountain

### Modpack version

All stable versions

### Log Files

[Uploading latest.log…]()

### Describe the bug

After some degree of troubleshooting with R3GEN we found that the only files being created by the FTB app are the icon and the instance.json. Every attempt creates a new instance with a new icon, and a new instance.json. Every instance.json has no modloader defined. Manually reinstalling forge* for the modloader, did not fix the issue, nor did manually updating the instance.json with Notepad++ to state what forge the modloader was supposed to load.

*The referenced message in discord for this step is:
https://discord.com/channels/372448486723158016/695329867037933609/1035671267547824129

### Steps to reproduce

Open FTB App.
Attempt to download FTB inferno on any of its stable release versions.
Fatal error.
Completely scrub the FTB app and overwolf from your computer.
Reinstall from scratch
Return to step 1.
Note: every attempt creates a new instance so manual assigning a modloader in the .json does not work. You're truly starting from scratch every time.

### Expected behaviour

Maybe it should download and install without problems

### Screenshots

![FTB error](https://user-images.githubusercontent.com/77522101/198755936-333d7656-d70a-4fd2-a510-04a8d015a46a.png)
![No Mod Loader](https://user-images.githubusercontent.com/77522101/198755959-6f8bc151-36c8-46ca-bab0-0c64a72139bb.png)

**Comment by Avatarded** [comment]
After a herculean effort by R3GEN we discovered that FTB App does not recognize any version of adoptium other than one very specific version: 17.0.2. So, to the FTB App the version 17.0.5 that I was using was completely invisible. It was unclear to both of us at the time that this would be the source of the problem. 

The FTB App should probably be future proofed, in the event the 17.0.2 version is not available in the future, or needs to specify that it will _only_ take that _very specific_ version. I'm not closing this issue on my own, despite it now being resolved, because I want the FTB Team to see what the problem was, and have a reference for it later if need be.

**Comment by Raidobw2** [comment]
Note: This was fixed by reinstalling the correct JRE to the FTB App. (`%localappdata%\.ftba\bin\runtime`)
![image](https://user-images.githubusercontent.com/17010632/199428791-a157e6e9-49d8-4e08-9dd5-5ef184d70097.png)

This folder is normally managed by the app and should only be modified if you know what you are doing. Missing JREs in that folder are not a common occurence, and in this current case, I'm not sure why it was missing.

If others have similar issues, they should get in touch with us through the FTB Discord first.

Since this case was fixed, I'll close this
