### ISSUE TITLE
[Bug]: Flint pickaxe quest does not complete

### ISSUE THREAD

**Issue by lslinnet** [FTBTeam/FTB-Modpack-Issues#1527]
### Modpack

FTB Inferno

### Modpack version

1.1.1

### Log Files

No log file

### Describe the bug

The flint pickaxe quest does not complete when crafting a flint pickaxe.

### Steps to reproduce

1. Start new worl
2. Find some flint
3. complete quests up to the pickaxe point
4. craft a pickaxe

### Expected behaviour

That the quest completes 

### Additional information

I just updated from earlier version to 1.1.1 (I have previously played on 1.0.0 and just about all other 1.0.x versions.

**Comment by lslinnet** [comment]
I did a quick video capture of the issue:
https://user-images.githubusercontent.com/155903/198819148-707c29b1-9658-4f3f-b102-9c81b7f013b9.mp4

**Comment by lslinnet** [comment]
I was able to use `/ftbquest editing_mode` to complete the quest.

**Comment by Saereth** [comment]
Yeah if you can just edit it fixed for now I'll have this fixed up for weds update

**Comment by Blockguy24** [comment]
I am on 1.2.1 and this issue still appears to be present. Is the fix meant to be in this version or is it coming later?

**Comment by orbidlo** [comment]
Apparently relogging fixes the issue but yeah, still there on 1.2.1. Consider making quest completed by submitting flint and giving the flint pick as reward if it gives so much trouble...
