### ISSUE TITLE
[Bug]: Duplication of Any Item 

### ISSUE THREAD

**Issue by AntiNametag** [FTBTeam/FTB-Modpack-Issues#1528]
### Modpack

FTB Inferno

### Modpack version

1.1.1

### Describe the bug

You are Able to duplicate any Item using the Wooden Stand from Nature's Aura and The Ability to Pick up Certain Containers.

You can Just put an Item onto The Wooden Stand, Pick it up, put it down, and get dropped 1 of the Items and can Pickup the one you put on the Wooden Stand.

See Attached Video

### Steps to reproduce

1. Go to a Wooden Stand.
2. Put any Item on the Wooden Stand.
3. Sneak-Rightclick to Pickup said Wooden Stand.
4. Put the Wooden Stand back down using Rightclick
5. Pickup the Dropped (Duplicated) Item
6. Rightclick the Wooden Stand to Pickup the Previously put on Item
7. Two Items.
8. Profit

### Expected behaviour

I expected that either the Item gets Dropped before i pick the Wooden Stand up, or the Item Remains without another Item appearing 

### Screenshots

[2022-10-30 02-18-38.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9894813/2022-10-30.02-18-38.zip)

**Comment by Saereth** [comment]
Your config files are invalid. Please follow the change log directions for 1.1.1 to fix them
