### ISSUE TITLE
[Bug]: Error when joining Inferno server in 1.0.3 or 1.1.1

### ISSUE THREAD

**Issue by Gobroyol** [FTBTeam/FTB-Modpack-Issues#1530]
### Modpack

FTB INFERNO

### Modpack version

1.0.3 and 1.1.1

### Log Files

Client logs:
![Capture d’écran 2022-10-30 124629](https://user-images.githubusercontent.com/117015551/198876747-3bfbcae6-1d2f-4476-9aed-dc008103635b.jpg)

### Describe the bug

![image](https://user-images.githubusercontent.com/117015551/198876820-8c8cc8a0-31a4-48ac-bd38-2471812cf23e.png)
 I get this error (and my friend) when i try to connect to my serv which has the same FTB modpack loaded 
I've tried a lot of things and i dont know what to do about it, ive tried connecting with other modpacks and no modpacks it works well so i think its just this modpack who cause problem. The same problem is in 1.0.3 and 1.1.1. 

### Steps to reproduce

1: Launch Inferno 1.03 or 1.1.1
2 : Set the modpack on the server 1.0.3 or 1.1.1
3 : Try to connect to the server 
4 : Get the error

### Expected behaviour

I expect to conenct on the server normally

### Screenshots

![image](https://user-images.githubusercontent.com/117015551/198877063-7b5b2e32-7221-472d-b408-383f6e811e7e.png)
Ive tried to change all options here obviously nothing change

**Comment by 5ully** [comment]
If you can, please upload the full log files, and not just as images

**Comment by Gobroyol** [comment]
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9895898/console.log)

**Comment by Saereth** [comment]
[30Oct2022 14:09:02.622] [Netty Client IO #2/INFO] [net.minecraftforge.network.NetworkHooks/]: Connected to a vanilla server. Catching up missing behaviour.

Your server is not setup right.

can you provide the server log file

**Comment by Gobroyol** [comment]
I have re setup the server on inferno 1.0.3  here is the new ip : mc197.boxtoplay.com:27188 
If you wanna try on the same type of server Go to BoxToPlay and create a free 12 hours server thats what i am doing

**Comment by Saereth** [comment]
Just grab the latest.log and debug.log from the server, that's what I need. It seems like your server files are not installed right and the logs will confirm if thats the case or not

**Comment by Raidobw2** [comment]
This potentially *could* be linked to https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1448

**Comment by Saereth** [comment]
Ok we'll add it to the pack this update and see if that helps

**Comment by Saereth** [comment]
Let us know if the issue continues after updating to 1.2 (out soon)

**Comment by Gobroyol** [comment]
Okey thanks a lot for your help guys!
