### ISSUE TITLE
[Suggestion]: Nerf or Remove Reality Modifier

### ISSUE THREAD

**Issue by sme23** [FTBTeam/FTB-Modpack-Issues#1533]
### Modpack

FTB Inferno

### Is your suggestion related to a problem? Please describe.

Currently, high tier mobs can have the Reality modifier applied to them. The effect of this modifier is that every time you hit the mob, there is a chance that an enchantment is removed from the weapon you used to hit them. Especially in the earlygame where you're relying mainly on loot drops for weapons and can't easily replace the deleted enchants, this is very bs

**Comment by Saereth** [comment]
duplicate, fixed in dev
