### ISSUE TITLE
[Bug]: Villagers trades on JEI are not the correct ones when connecting to a server

### ISSUE THREAD

**Issue by Nagapito** [FTBTeam/FTB-Modpack-Issues#1536]
### Modpack

FTB Inferno

### Modpack version

1.1.1

### Describe the bug

When playing on a server, JEI does not show correct trades

### Steps to reproduce

Coonect to a server
Check JEI villager trades

### Expected behaviour

See correct trades on JEI

### Screenshots

![image](https://user-images.githubusercontent.com/4959346/198984944-3e0835f7-13a7-4063-b477-bad2d3373f30.png)

**Comment by Saereth** [comment]
Cannot reproduce, looks like the server install may have issue. OR one of the mods updated in 1.2 fixed this. Please re-open if this isnt fixed for you after the 1.2 update soon
