### ISSUE TITLE
[Bug]: Clientside missing mods

### ISSUE THREAD

**Issue by GalaxySynth** [FTBTeam/FTB-Modpack-Issues#1539]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.0

### Describe the bug

Client modpack is missing Structure Compass and Measurements when trying to connect to Stoneblock 3 server

### Steps to reproduce

Install modpack

Try to connect to server

### Expected behaviour

mods not missing

**Comment by Sunekaer** [comment]
Seems like it failled to download them on your client, try and reinstall it

**Comment by newtrogicNexus** [comment]
> Seems like it failled to download them on your client, try and reinstall it

There's a ton of broken and duplicate links on the [modlist page](https://feed-the-beast.com/modpacks/100-ftb-stoneblock-3), perhaps that has something to do with it.

**Comment by Raidobw2** [comment]
It's being worked on
