### ISSUE TITLE
[Bug]: client crash while crafting create millstone

### ISSUE THREAD

**Issue by natebc** [FTBTeam/FTB-Modpack-Issues#1541]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.0

### Log Files

https://gist.github.com/natebc/045f7d4c4fdb58c879edc175dec47dc7

### Describe the bug

While crafting first a cog and then a millstone I experienced a client crash. The latest.log attached to this issue report is from the second crash when crafting a millstone.

### Steps to reproduce

1. place tinkers crafting station next to stone chest
2. craft create cogwheel (crash)
3. craft create millstone (crash)

### Expected behaviour

no crash <3

**Comment by Sunekaer** [comment]
Does it work after a restart?
Ill forward the Crash to Mantle

**Comment by natebc** [comment]
> Does it work after a restart?

It did crash twice doing the millstone quest. After I filed this issue i moved the tinkers workbench away from the stone chest and switched to a vanilla oak chest and it's been fine since.
