### ISSUE TITLE
[Bug]: Entities don't get rendered on first start of a world

### ISSUE THREAD

**Issue by Joshy14-06** [FTBTeam/FTB-Modpack-Issues#1542]
### Modpack

StoneBlock 3

### Modpack version

1.0.0

### Log Files

logs of the first start of the modpack:
[2022-11-01-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9914083/2022-11-01-1.log.gz)
[debug-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9914089/debug-1.log.gz)

logs of the second start:
[2022-11-01-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9914122/2022-11-01-2.log.gz)
[debug-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9914123/debug-2.log.gz)

### Describe the bug

Entities don't seem to get rendered in my installation.
World backup attached:
[2022-11-1_22-0-0.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9914031/2022-11-1_22-0-0.zip)

a restart of the modpack fixed the problem.

### Steps to reproduce

Start a new world with cheats and bonus-chest set to on.
Enter the portal.
Choose the "lushed House" dimension.
Mine something that drops an item.

### Expected behaviour

The entity of the droped item doesn't get rendered.

### Screenshots

before restart:
![Stoneblock3-entity](https://user-images.githubusercontent.com/37276727/199342019-a2dbfc98-5e5a-4810-aefa-0d346b38dd0f.png)
after restart:
![Stoneblock3-entity-fixed](https://user-images.githubusercontent.com/37276727/199346017-777385a3-3bc2-4e91-94e6-a256ed9ba172.png)

### Additional information

the steps to recreate are the steps that i took to get the bug in the first place, but after i had shut down and restarted minecraft i can no longer recreate the bug.

**Comment by Sunekaer** [comment]
It's a weird bug, which we haven't been able to replicate, it just happens randomly, and you have to restart the game to fix it

**Comment by GamingWithJanko** [comment]
Need a log?

I have the same problem. XD

**Comment by Janitor53** [comment]
The same here.

**Comment by Snowman-25** [comment]
Same here. Was wondering why I didn't have hands

**Comment by mnewhart** [comment]
I just had this issue with a double stone chest and my char invisible. I logged out of the game to the MC start screen and upon returning to the game the chest and my char were invisible. The chest was still there and I could access it. Hit F5 to change view and I was invisible also. I then went completely out of the game and reloaded from launcher and I wasn't invisible and the chest that I broke after emptying because I thought I would lose it, was sitting on the ground. I think an exit and reload will make things visible again...

**Comment by TheNickmaster21** [comment]
I also had issues on my first start. First world had no items rendering and I couldn't see that I was breaking blocks. Rejoined the same world with the same issue. Created a new world on a different map and still had the same problem. I then restarted the mod pack and everything was fixed.

**Comment by otDan** [comment]
same here, though the first thing I joined was a server, exact same behaviour and restarting fixed the issue

**Comment by Xiarno** [comment]
I know restarting fixes this but it's still extremely annoying.

**Comment by Sunekaer** [comment]
Should be fixed in 1.1.0 i hope 🙏
