### ISSUE TITLE
[Bug]: Crash while loading mods

### ISSUE THREAD

**Issue by boraberk** [FTBTeam/FTB-Modpack-Issues#1543]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.0

### Log Files

[crash-2022-11-02_01.00.25-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9914239/crash-2022-11-02_01.00.25-fml.txt)

### Describe the bug

Stone chest mod crashes while loading.

### Steps to reproduce

1.Open Stoneblock 3

### Expected behaviour

Does not crash

### Screenshots

![image](https://user-images.githubusercontent.com/24351893/199350462-a27893f2-f8d0-4c1a-a6c6-abaa7ec2bb28.png)

**Comment by sevket** [comment]
Same here.

**Log file**
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9914411/latest.log)

**Comment by boraberk** [comment]
It looks like a language issue. There is a solution in mod's GitHub. (https://github.com/DoctorFTB/StoneChest/issues/9)
Latest log: 
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9914434/latest.log)

**Comment by Raidobw2** [comment]
I've forwarded a message to the FTB App dev team, this could be solved directly in the app itself
