### ISSUE TITLE
[Bug]: Iron Reinforced Hammer doesnt drop items

### ISSUE THREAD

**Issue by Sh1oriko** [FTBTeam/FTB-Modpack-Issues#1544]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.0

### Describe the bug

Iron Reinforced Hammer doesn't drop items after breaking when you FACE UPWARDS.

### Steps to reproduce

Break blocks using Iron reinforced hammer WHEN FACING UPWARDS.

### Expected behaviour

Drop items on break FACING UPWARDS.

**Comment by mellamokb** [comment]
Same issue with the stone hammer.  Also if you are looking at the side of a block from a steep angle downward, it sometimes mines 3x3 in both directions, like a cross shape.  Takes 3x3 plane of the side of block, but also 3x3 deep horizontal slice, if that makes sense.

**Comment by MichaelHillcox** [comment]
Hmm, how interesting. The looking up one I've not seen myself, I'll try it out in a minute. As for the mines in both directions issue... Right now, I recommend you take it as a happy little accident, as it requires me to make pretty substantial changes to my breaking code (:cry:) but this will be fixed.

**Comment by GamingWithJanko** [comment]
Same issue here.

Placed a block to shape the cave with the hammer, no items.

I lost a lot of blocks because of that bug.

**Comment by MichaelHillcox** [comment]
It does... they just drop... upwards... don't ask, it'll be fixed in the next update

**Comment by GamingWithJanko** [comment]
Is there a rough ETA for the "state: Mod Update Available" tag yet?

**Comment by MichaelHillcox** [comment]
It's been released
