### ISSUE TITLE
[Bug]: Smeltery not Oredoubling FTB StoneBlock 3

### ISSUE THREAD

**Issue by Thomas8896** [FTBTeam/FTB-Modpack-Issues#1545]
### Modpack

Stoneblock 3

### Modpack version

1.0.0

### Describe the bug

Smeltery doesn't oredouble as described in Questbook. Easy fix in config to up the nuggets per ingot to 18

### Steps to reproduce

works for me and 2 other friends

### Expected behaviour

should ore double, gives only 12 nuggets per ingot instead of 18

**Comment by Sunekaer** [comment]
Not a big, just how Tinkers works now

**Comment by MaxFirestorm** [comment]
Questbook will need to be changed then since the last line of the Quest literally states that putting ore in the smeltery will double it. 

![2022-11-04 15_12_15-Window](https://user-images.githubusercontent.com/11296552/200010221-651a7727-e576-432b-882e-401e6b244670.jpg)

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/200163934-459228c5-bb1e-4d8c-83c3-f952e41e2e38.png)

REI shows it should be? A bit more than double, even.

Raw ores give 1+1/3 as well
