### ISSUE TITLE
[Bug]: Stoneblock 3 Start.sh/User_jvm_args.txt issues

### ISSUE THREAD

**Issue by Grimlock7** [FTBTeam/FTB-Modpack-Issues#1546]
### Modpack

Stoneblock 3

### Modpack version

1.0.0

### Describe the bug

Upon running the stoneblock 3 installer for linux arm, everything installs correctly and yet when running the start.sh file, this error occurs. I have never seen this issue in any other modpack and I have been installing them for ages. It also says that it ran out of memory...yet both 8GB are assigned in pterodactyl itself and the user_jvm_args.txt has xmx and xms specified at 8G. I have not edited the start.sh at all, so it's all still default.

However what i noticed is, if i remove my arguments from the user_jvm_args.txt the server starts. And the arguments in the file are simply the generic modded ones that work in every other pack ever.

`-Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch 
-XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 
-XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem 
-XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true`

If you cannot put in any custom arguments, how do I define the ram and make sure its using the best performance possible?

Are there any recommended arguments for garbage collection to replace those posted above specifically for stoneblock 3?

### Steps to reproduce

1. Use custom G1GC arguments in user_jvm_args.txt 
2. Start Server
3. It kills itself with a start.sh error
4. Removing all arguments except xms/xmx and it works fine

### Expected behaviour

Standard Java arguments should be working, especially ones for Garbage collection as this is key to performance on both clients and servers

### Screenshots

![image](https://user-images.githubusercontent.com/30302995/199355461-039ea53f-ee13-4be6-a987-f957cb80f0a8.png)

**Comment by Raidobw2** [comment]
Have you tried adding your arguments one after the other? Start with `-Xms8G -Xmx8G -XX:+UseG1GC` only, and add one or two each time. I personally never have used as complex arguments as this, so I don't know if there is an error at first sight.

Anyways, if you kill the process everytime after you confirm it started that'll take you at most a few minutes to pass through that list of arguments. (You have about 20 to do, adding in groups of two that'll be quick)

To note that there can be some differences between Java versions, and StoneBlock 3 uses Java 17. Possibly one of the arguments you're using is no longer valid in Java 17, or got changed.

**Comment by Grimlock7** [comment]
> 

The thing is, the arguments currently listed above that I tried were also the argument's that i use for All the mods 7, which is java 17, on 1.18.2 and vastly more mods as well. That's what's weird about it, why this pack specifically doesn't want to work with them. But works on literally every other pack ever. 

I also tried the arguments individually, it only loads when -XX:+ParallelRefProcEnabled, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch are removed, whilst the majority of the GC arguments work fine. So that's still weird since most packs work fine, but good to know for this pack that there is clearly some issues with how something is setup or a custom mod or something?

**Comment by Raidobw2** [comment]
For Discord there is the SRDP mod that's in the pack, that should work. Concerning the extra jvm argument that caused the issue, do you need it to obtain the best performance, or is the performance already at its best without it?

**Comment by Grimlock7** [comment]
Performance is still fine without it don't worry. Also I have never heard of this SDRP mod, i wasn't aware of it, ill take a look. Thanks

**Comment by Raidobw2** [comment]
Oh you meant for server, I think in beta testing jedi was used https://www.curseforge.com/minecraft/mc-mods/just-enough-discord-integration. Try it out if you want

**Comment by Grimlock7** [comment]
That one worked, thank you so much!!!!!

**Comment by Raidobw2** [comment]
You're welcomed, seeing how the issues seem resolved and I assume your server is up and running fine now, I will be closing this.

If you need more help you can open a new ticket or hit me up on the [FTB Discord](https://go.ftb.team/discord),

Cheers 😎
