### ISSUE TITLE
[Bug]: The One Probe mod doesn't work

### ISSUE THREAD

**Issue by Leycoo** [FTBTeam/FTB-Modpack-Issues#1547]
### Modpack

FTB BEYOND

### Modpack version

1.10.2

### Describe the bug

It's not very important but annoying. The One Probe  is the mode that allows us to identify the blocks and the information on them and it is quite useful. My problem here is that the mod doesn't work, and I tried to fix it by using others like wawla but it didn't work. I would like to know if it's possible to get an answer and if I should download the modpack again. Sorry for bothering you with this unimportant problem, and thank you in advance for your answer.

### Steps to reproduce

There is no step

### Expected behaviour

IDK what this mean but i expected to see the information: like the energy in it... ;of the block and identify him if idk what it is

**Comment by Raidobw2** [comment]
Hi, for me it works fine:
![image](https://user-images.githubusercontent.com/17010632/199439964-39a7f81b-9ac4-4f2a-acb3-0e2b9eaa0e15.png)

I'd recommend that you take a copy of your worlds before reinstalling. Your worlds are accessed here:
![image](https://user-images.githubusercontent.com/17010632/199440062-59832009-8988-4752-a665-6aa4cfbda5a5.png)

After you reinstall the modpack, in-game, take The One Probe paper note in your hand and right-click it. Click on "Extended":
![image](https://user-images.githubusercontent.com/17010632/199440193-8252f9e3-ffd2-4938-b1a4-f4add3d04a6a.png)

With the paper in hand you can shift-right-click to change the position in the HUD:
![image](https://user-images.githubusercontent.com/17010632/199440266-80e4daaa-8072-40dc-a3d8-6759146e03a0.png)

Then you'll be able to see energy and other things. Let me know if you do:
![image](https://user-images.githubusercontent.com/17010632/199440340-442c3d97-4bfe-4627-8475-7c60d26ebb54.png)

**Comment by Leycoo** [comment]
I'm such an idiot, i just forgot to use the paper and config the mod, thank you very much and sorry for wasting you're time for explaining it to me, have a great day

**Comment by Raidobw2** [comment]
No problem, I'm glad you could figure it out! Have fun 🙂
