### ISSUE TITLE
[Bug]: No bulk washing recipe for Gravel in REI

### ISSUE THREAD

**Issue by cakered** [FTBTeam/FTB-Modpack-Issues#1548]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0

### Describe the bug

Bulk washing recipe for Gravel is missing from REI - It's loosely described in the questbook. Recipes exist for Sand and Dust

### Steps to reproduce

Check REI for Bulk Washing recipes. Confirm that there's no entry for Gravel

### Expected behaviour

A bulk washing recipe for gravel exists

**Comment by PianoHallvard** [comment]
Additional for the devs: it's only the recipe in REI that doesn't exist. Actually washing gravel with a water encased fan works as expected
