### ISSUE TITLE
[Bug]: Stoneblock 3 Doesn't work with shaders.

### ISSUE THREAD

**Issue by Ticskter** [FTBTeam/FTB-Modpack-Issues#1549]
### Modpack

Stoneblock 3

### Modpack version

1.0.0

### Describe the bug

I installed Occulus, Rubidium, and rubidium extras mods so that i could play SB3 with shaders. upon doing this the game will load to menu just fine, i select my created world and when the little map finishes loading,  the window closes and the FTB launcher has the option to "re-launch" doing so and trying again it just does the same thing.

I also installed Optifine and repeated the steps, however this time i get a screen that is all red with "Mojang Studios" text that sits at about 99.5% loaded and the launcher log window just has something to do with "optifine texture stitching connected texture False" or something like that and it just gets in an infinite loop.

### Steps to reproduce

1. install shader mods for shader packs
2. Launch and load world

### Expected behaviour

should be able to install and load and play with shaders.

### Additional information

i know the Mod was just released and isnt even 24 hrs old yet. i know there are other "game breaking" issues that need to be fixed first, so this is not a big deal for me, but would love to play with Shaders!!

**Comment by mkaito** [comment]
This is not an issue with the modpack. It's an issue with Optifine and the current version of Forge.

Optifine HD U H9 pre1 only works with Forge 40.1.73. Some mods in the pack require 40.1.76 or newer. There is no single Forge version that would work for everything.

The only likely solution is for Optifine to release an update that works with Forge 40.1.84.

**Comment by MichaelHillcox** [comment]
You need to provide a crashlog, but my assumption is that you're crashing because of the `literal sky block` mod. This mod only adds one block and if I recall correctly, you can safely remove it. As always, do not use optifine. I never had any issues with Rubidium in my testing, but I didn't try it with Occulus... At the point of using shaders, you tend to run into issues.

**Comment by AmyMialee** [comment]
> This is not an issue with the modpack. It's an issue with Optifine and the current version of Forge.
> 
> Optifine HD U H9 pre1 only works with Forge 40.1.73. Some mods in the pack require 40.1.76 or newer. There is no single Forge version that would work for everything.
> 
> The only likely solution is for Optifine to release an update that works with Forge 40.1.84.
> 
> As far as I know, Occulus et al only work with Fabric. This is a Forge pack.

Oculus is the Forge Port of Iris.
Iris is the Fabric only mod.

**Comment by Grimlock7** [comment]
[2022-11-02-2.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9922836/2022-11-02-2.log)
Here is my log of the same issue occurring. Running Ouclus, and loading into a world, then crash.

**Comment by Sunekaer** [comment]
Modifications of the modpacks are not supported.
If you're having issues adding things, please contact the mods you are having issues with.

**Comment by glektarssza** [comment]
If anyone is curious, I found the problematic mod. It's [Literal Sky Block](https://www.curseforge.com/minecraft/mc-mods/literal-sky-block). Disabling that mod solves crashing issue. Unknown what other effects it may have.

**Comment by m0lDaViA** [comment]
> If anyone is curious, I found the problematic mod. It's [Literal Sky Block](https://www.curseforge.com/minecraft/mc-mods/literal-sky-block). Disabling that mod solves the crashing issue. Unknown what other effects it may have.

I tried that by removing the mod but the game still crashes. Even without rubidium/oculus.

**Comment by enbugger** [comment]
Who thought it was a good idea to add a single block mod which alone breaks all the shaders?

Most likely 0.1% of modpack players will ever see this block but they are unable to add custom shaders for the game
