### ISSUE TITLE
[Bug, JEI]: Unable to access JEI config

### ISSUE THREAD

**Issue by JTHm3** [FTBTeam/FTB-Modpack-Issues#155]
### Modpack

FTB Oceanblock

### Modpack version

1.4.0

### Describe the bug

When trying to access the JEI config, a message comes up saying to install FTB Library to access in game config and not allowing me to change any settings. 
If I change the location of the search bar in the mod menu config, it does not update in game
It is already installed and updated to the latest version

### Steps to reproduce

1. open inventory
2. click on JEI Config

### Expected behaviour

JEI config opens

### Screenshots

![image](https://user-images.githubusercontent.com/92832593/138064250-3f14a1e1-eac3-433c-bb4a-06f9a2d26bb1.png)
![image](https://user-images.githubusercontent.com/92832593/138064668-3e8a471d-84df-4bd3-9dac-a98474d3acba.png)

**Comment by Sunekaer** [comment]
https://github.com/mezz/JustEnoughItems/issues/2521

**Comment by sportsziggy** [comment]
> 
> 
> updating JEI to 129 fixed this for me, bar centered again.

Can confirm, this works.
@Raidobw2 this is an option.

**Comment by Raidobw2** [comment]
Thanks for checking that out.
For dev:
![image](https://user-images.githubusercontent.com/17010632/140012568-df91b953-322a-44f4-a0fa-5a64b78f4b59.png)

**Comment by Raidobw2** [comment]
Sunekaer you updated to `jei-1.16.5-7.7.1.129.jar` in 1.6.0, now the bar is centered but it looks like it'll be missing that Configured mod, if you want to add it for the next release 1.7.0:
![image](https://user-images.githubusercontent.com/17010632/140239489-2fa83dc1-b0c2-4244-9ff3-aa51debe306b.png)

**Comment by Sunekaer** [comment]
We already have that mod, this is another jei bug which is why this issue is still open

**Comment by Raidobw2** [comment]
Ah I see, alrighty.
Is this ok for it: mezz/JustEnoughItems#2552 ?

**Comment by Sunekaer** [comment]
I think the version of JEI there was released after the 1.6.0 update is fixing the issue, haven't checked

**Comment by Raidobw2** [comment]
Yup, that is indeed correct. `jei-1.16.5-7.7.1.130.jar` works.

![jei_config](https://user-images.githubusercontent.com/17010632/140472932-99e05976-b407-4e7a-800a-283bb8a32fe6.gif)
