### ISSUE TITLE
[Bug]: Early Random Quest Reward gives Item from a Mod that got removed

### ISSUE THREAD

**Issue by JustinSchweiger** [FTBTeam/FTB-Modpack-Issues#1550]
### Modpack

Stoneblock 3

### Modpack version

1.0.0

### Describe the bug

It seems that the "Measurements" Mod used to be in StoneBlock 3 but got removed. The Early Random Quest Reward still has the Tape Measure Item in the Loot Table.

### Steps to reproduce

1. Go Into Quest Editing Mode and look through the "quest_early" Loot Table.
2. Edit the Tape Measure

### Expected behaviour

Remove the item from the loot table if the mod got removed

### Screenshots

![Image](https://user-images.githubusercontent.com/40092507/199361029-76e3f76a-3176-41f6-9121-4afba7b29831.png)
![Image 2](https://user-images.githubusercontent.com/40092507/199361066-67dff4b0-72ec-42e0-b3b1-6b922913ab9b.png)

**Comment by JustinSchweiger** [comment]
Oh thats fun ... Well yea true lol

I'm using PrismLauncher but it didn't give a popup to download any additional mods so I thought it got all

**Comment by JustinSchweiger** [comment]
So after downloading the server files and comparing the two mod folders I realised that there are even more mods missing ...

- PartyParrots
- RoughlyEnoughProfessions
- Measurements
- StructureCompass

**Comment by Sunekaer** [comment]
Please use the FTB App, there is no support for other mods.
