### ISSUE TITLE
[Bug]: FTB Infinity Evolved Skyblock Server Install

### ISSUE THREAD

**Issue by robert-beckley** [FTBTeam/FTB-Modpack-Issues#1554]
### Modpack

FTB Infinity Evolved Skyblock

### Modpack version

2.0.1

### Log Files

Issue with ResourceLoader - https://mcpaste.io/dd374b59ff8ab2e6 
Issue with CustomMainMenu - https://mcpaste.io/a11664671cd07789
Issue with Lockdown - https://mcpaste.io/ba4995612bdea223

### Describe the bug

The Server install is grabbing the client-side mods as well, causing the server not to launch. 

### Steps to reproduce

Removing the Following Mods from the mods folder will enable the server to launch successfully. 

ResourceLoader-MC1.7.10-1.3.jar
CustomMainMenu-MC1.7.10-1.9.2.jar
Lockdown-1.7.2-2.0.0-universal.jar

### Expected behaviour

After running the server install, the server will launch when running the start file or loading forge manully. 

### Additional information

I used the windows install version, serverinstall_20_102.exe

**Comment by Raidobw2** [comment]
It's due for an update, check in the [FTB Discord's](https://go.ftb.team/discord) `#infinity-evolved` channel, there's a pinned message from me. You'll have a bit more info in there as well

**Comment by Gaz492** [comment]
This issue should be resolved now, there were 3 client only mods being downloaded with the server installer (ResourceLoader, CustomMainMenu and Lockdown)
