### ISSUE TITLE
[Bug]: FTB Presents Cloud 9 Server Install

### ISSUE THREAD

**Issue by robert-beckley** [FTBTeam/FTB-Modpack-Issues#1555]
### Modpack

FTB Presents Cloud 9

### Modpack version

1.3.0

### Log Files

https://mcpaste.io/9e38d15140170ae7

### Describe the bug

The Server install is grabbing the client-side mods as well, causing the server not to launch.

### Steps to reproduce

Removing the Following Mods from the mods folder will enable the server to launch successfully.

ResourceLoader-MC1.7.10-1.2.jar
CustomMainMenu-MC1.7.10-1.9.2.jar

### Expected behaviour

After running the server install, the server will launch when running the start file or loading forge manually.

### Additional information

I used the windows install version, serverinstall_15_108.exe

**Comment by Raidobw2** [comment]
Thanks for reporting!

**Comment by Gaz492** [comment]
This issue should be resolved now
