### ISSUE TITLE
[Suggestion]: Add REI Integration for Botany Pots

### ISSUE THREAD

**Issue by iammael** [FTBTeam/FTB-Modpack-Issues#1556]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Currently, we are unable to see what can be grown in a pot and its required soil. Hovering over dirt in a pot tells us the seed is growing at a 1x rate, but we are unable to know what other soil we could use to improve that.

For example, I knew from experience that Kelp could be grown in pots with a water bucket for soil, but a new player will have a hard time finding that.

**Comment by Sunekaer** [comment]
Hi
This is sadly not something we have control over.
Botany Pots 1.18 and above doesn't have integration for JEI / REI 
Please open a request on Botany Pots issue tracker https://github.com/Darkhax-Minecraft/BotanyPots/issues

**Comment by Raidobw2** [comment]
cc @Sunekaer if Botany Pots is updated now you should have JEI compat (still need to test REI supports it well, I have not checked). Darkhax implemented this very recently on the 1.18.2 branch! 😃 
Click either a soil or berry/sapling/seed with 'u' and you should see that:
![image](https://user-images.githubusercontent.com/17010632/200149571-74c37e6f-9511-49b0-9283-607a2b2f5605.png)
![image](https://user-images.githubusercontent.com/17010632/200149583-ef64a159-f619-4dc2-8c2a-84c68ac6a36b.png)
