### ISSUE TITLE
[Bug]: 3x3 hammer able to break adjacent deepslate blocks when it normally cannot mine them

### ISSUE THREAD

**Issue by whois-trin** [FTBTeam/FTB-Modpack-Issues#1558]
### Modpack

FTB StoneBlock 3

### Modpack version

1.1.0 (i believe)

### Describe the bug

When mining blocks adjacent to deepslate with a hammer (the hammer that mines a 3x3x1 area) that is unable to mine deepslate directly, the deepslate is broken and can be picked up, this does not seem intentional as it allows for the deepslate level of the world to be explored earlier than the progression would normally allow through the means of this bug

### Steps to reproduce

Step 1: Acquire a 3x3x1 hammer underneath the diamond mining level (stone, iron, etc.) 
Step 2: Go to the transition between the andesite layer of the world and the deepslate layer of the world,
Step 3: Mine an andesite block that has deepslate adjacent to it, you will see that the deepslate is broken and dropped 

### Expected behaviour

I expected the andesite to have broken but the deepslate to have stayed unbroken or at least not dropped anything.

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
