### ISSUE TITLE
[dupebug]: ability to copy any item in the game

### ISSUE THREAD

**Issue by captainbrtiain** [FTBTeam/FTB-Modpack-Issues#1559]
### Modpack

ftb inferno 

### Modpack version

1.1.1

### Describe the bug

ability to dupe any item in the game this also includes anything stored in the block as well

### Steps to reproduce

step one make wooden stand 
step two place wooden stand 
step three place item you want to dupe 
step four press shift and pick up wooden stand with item on it
step five place down in same spot or any doesnt matter
step 6 collect item 
step 7 dupe all the things and break world

### Expected behaviour

no second item with exact nbt deta

**Comment by Saereth** [comment]
if you can use carry on on a wooden stand your configs are messed up. Copy the carryon server config from default configs and put it in saves/yoursave/serverconfigs if singleplayer or world/serverconfigs if multiplayer
