### ISSUE TITLE
[Bug, Blood Magic]: Blood magic and Draconic Evolution conflict clears inventory

### ISSUE THREAD

**Issue by JTHm3** [FTBTeam/FTB-Modpack-Issues#156]
### Modpack

FTB Oceanblock

### Modpack version

1.4.0

### Describe the bug

When using the sacrificial knife with the blood alter from Blood Magic while the undying module is installed on an equipped Draconic Evolution chest piece, you die instead of being kept alive by the module, which activates, and your entire inventory is deleted except for your inventory. No gravestone is made

### Steps to reproduce

1. equip draconic evolution chestpiece with an undying module installed
2. use the blood magic sacrificial knife with the blood alter until you die
3. cry

### Expected behaviour

the undying module should prevent you from dying

### Screenshots

Sacrificial knife:
![image](https://user-images.githubusercontent.com/92832593/138066872-f1ae2758-19d3-4eda-a055-8f2f8471d3e2.png)
Chaotic chestpiece:
![image](https://user-images.githubusercontent.com/92832593/138066965-d6f33ca4-a4d6-41b3-9d6a-2f0efa0cf131.png)
Undying module installed:
![image](https://user-images.githubusercontent.com/92832593/138067047-60d648d6-3279-440a-be6f-9ed66b6c7784.png)
Die from using the knife too much - undying module activates late:
![image](https://user-images.githubusercontent.com/92832593/138067171-fa11ca39-e87e-43a0-8c62-c3ee43417ce5.png)
Items and armor are gone, but curios slot items are still equipped:
![image](https://user-images.githubusercontent.com/92832593/138067260-90a154c3-4922-4ebc-b343-52a956be935b.png)
no gravestone:
![image](https://user-images.githubusercontent.com/92832593/138067359-ee6bb9d5-7502-4fc1-a336-2bf97bef9148.png)

**Comment by Sunekaer** [comment]
I was gonna make a issue with BM just havent had time do to work xD

**Comment by Raidobw2** [comment]
I'll make it right now real quick

**Comment by scopiplays** [comment]
I died to the Blood Magic dagger without the Draconic Armor and lost my inventory - no grave, so I'd vote it is totally a Blood Magic issue alone.

**Comment by Raidobw2** [comment]
Blood Magic committed to their repository. Keep an eye open, next BM build will include the fix. It's not on CurseForge yet.
