### ISSUE TITLE
[Bug]: Grave not giving all items from death.

### ISSUE THREAD

**Issue by Xavion3** [FTBTeam/FTB-Modpack-Issues#1560]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.0

### Describe the bug

I had died, ran back to my grave, and started breaking it so I could reclaim my things to better fight the skeleton that had killed me. It was attacking me, and just as I finished breaking my grave and collected my items it killed me. When I respawned and ran back to my new grave, the items I'd gotten from breaking my previous grave were gone and the new grave only gave me the items from before I'd breaking the previous grave.

### Steps to reproduce

Not sure, die the same tick as you collect an item or something?

### Expected behaviour

For graves to contain all your items.

**Comment by last903347** [comment]
When I tried to destroy my tombstone to get my items back, the bit spawner spawns new mobs(those buffed mobs really socks), I was killed while the gravestone was broken at same time. My items appeared in my inventory before I respawn, but after that， I used the back command to go back again my items were not included in the new gravestone

**Comment by Sunekaer** [comment]
we will add this issue to a list of known mod issues
