### ISSUE TITLE
[Bug]: Trying to join stoneblock 3 server and getting an error when joining in 

### ISSUE THREAD

**Issue by BETAIDK** [FTBTeam/FTB-Modpack-Issues#1561]
### Modpack

stoneblock3

### Modpack version

1.0.0

### Describe the bug

Hey I opened a server for me and my friends I tried to join the server and I getting the same error again and again 

### Steps to reproduce

1. Open stoneblock3
2. Enter a stoneblock3 server

### Expected behaviour

I expected when I will join the server I will be enable to play with my friends

### Screenshots

![image](https://user-images.githubusercontent.com/78589468/199494785-07e2ba9f-3cb5-440a-8571-2da761f95947.png)

**Comment by Sunekaer** [comment]
Please provide log file from both client and server

**Comment by BETAIDK** [comment]
> Please provide log file from both client and server

this is from the client [latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9920669/latest.log)
this is from the server [latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9920675/latest.log)

**Comment by gigabit101** [comment]
```[02Nov2022 14:36:46.353] [Netty Client IO #1/INFO] [net.minecraftforge.network.NetworkHooks/]: Connected to a vanilla server. Catching up missing behaviour.```

Your server is running Vanilla Minecraft and not the Modpack, You can also see this by looking at the server log and it not loading any mods

**Comment by BETAIDK** [comment]
> 

what how Im checking right now and its running on forge

**Comment by gigabit101** [comment]
There are no forge/mod lines in that server log file you provided, If it was the Stoneblock Modpack there would be a LOT more messages in the log
