### ISSUE TITLE
[Bug]: KubeJS error on world join

### ISSUE THREAD

**Issue by itsjusttriz** [FTBTeam/FTB-Modpack-Issues#1562]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.0

### Describe the bug

Getting this error from KubeJS on world join.

Unsure if specific to singleplayer, or server play. Currently, personally running on a server.

### Steps to reproduce

1. Login to world.

### Expected behaviour

Most likely a typo or something in the script.

### Screenshots

![image](https://user-images.githubusercontent.com/29345907/199512028-cc55ea01-a73e-45e5-bb60-da68d2a29450.png)

**Comment by Sunekaer** [comment]
What launcher are you using?
Because this mod isn't removed, so the launcher your using didn't download it

**Comment by itsjusttriz** [comment]
Ive installed via the FTB app, but have imported to MultiMC using their `Import from FTB` option

**Comment by Sunekaer** [comment]
Hmm, try and install it again
Seems your missing the mod
