### ISSUE TITLE
[Bug]: duplication

### ISSUE THREAD

**Issue by BibiBaggins** [FTBTeam/FTB-Modpack-Issues#1563]
### Modpack

direwolf

### Modpack version

1.18

### Log Files

i do not have any log files

### Describe the bug

you can dupe copper by putting one "copper block" into stonecutter and trading it for 4 "cut copper blocks" after wich you can trade each of "cut copper blocks" back for 4 "copper blocks" turning your initiall one into sixteen.

### Steps to reproduce

1. place a stonecutter
2. get copper block
3. use stonecutter to turn it into cut copper
4. turn cut copper back to regular copper

### Expected behaviour

i expected that for every copper block i would get one cut copper block and same on converting it back.

**Comment by TheonlyTazz** [comment]
![grafik](https://user-images.githubusercontent.com/3908847/201179351-939e2c34-4751-42f4-9fd1-e67e73b40615.png)
Cannot replicate, also fixed in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/936
