### ISSUE TITLE
[Bug]: Non-Standard Bonemeal Uses Delete Sigil of the Green Grove

### ISSUE THREAD

**Issue by sme23** [FTBTeam/FTB-Modpack-Issues#1564]
### Modpack

FTB Inferno

### Modpack version

1.1.1

### Describe the bug

Right-clicking on a bonemeal-able block with the Sigil of the Green Grove will apply a bonemeal effect at the cost of LP. If this is done to a block that isn't normally bonemeal-able in vanilla but is here, like sugar cane, the growth tick is applied but the Sigil of the Green Grove is deleted.

### Steps to reproduce

1. Place a Sugar Cane
2. Obtain a Sigil of the Green Grove
3. Use the Sigil of the Green Grove on the Sugar Cane
4. See growth tick applied as sigil is deleted

### Expected behaviour

Sigil to apply growth tick at the cost of LP rather than at the cost of the sigil

### Additional information

This is presumably caused by the thing that is allowing bonemealing blocks like sugar cane assuming that the item used is always going to be bone meal, in which case the behavior of "apply growth tick & delete 1 of item" would be correct. I'm unsure if it's even obtainable pre-overworld, but theoretically, Phyto-Gro should have this same issue; normally it only has a % chance of being used up when applying a growth tick, but if this behavior stands it would be a 100% chance when used on something like sugar cane.

**Comment by Saereth** [comment]
duplicate
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1398
