### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by IamSweetie** [FTBTeam/FTB-Modpack-Issues#1567]
### Modpack

FTB stoneblock 3

### Modpack version

1.0.0

### Describe the bug

blocks disappear after placing - I freed a loot bee from approx 10 blocks underground, pillared back up with cobble which then reappeared in my inventory and the hole was back (but I was back on the surface)

### Steps to reproduce

Free a loot bee
pillar out of a hole
pillar up to move the bee
hole reappears
blocks are back in inventory

### Expected behaviour

hole to remain filled when I fill it

**Comment by Raidobw2** [comment]
Hmm I'm not entirely sure how the loot bee script works, but there are some blocks that are manipulated in the script, maybe that's it.

**Comment by Sunekaer** [comment]
Loot bee only manipulate the block where the bee spawned, this must have been something else causing this issue, I just don't know what

**Comment by Sunekaer** [comment]
Im not able to recreate this issue and in the bee code there is no way this can happen.
Closing issue, feel free to reopen if you can recreate it and provide more info.
