### ISSUE TITLE
[Suggestion]: buffer limit for the auto-hammers

### ISSUE THREAD

**Issue by gaminggirl** [FTBTeam/FTB-Modpack-Issues#1568]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

The auto-hammers don't seem to have an upper limit to their buffers. This poses a risk when removing them and makes lots of automation tasks harder. A limit to the buffer or a way to turn them off would be nice.

**Comment by Sunekaer** [comment]
There is a buffer, the buffer limit is the amount of the height outputting recipe

**Comment by gaminggirl** [comment]
And how many thousand items is that?
