### ISSUE TITLE
[Bug]: Freezes, gamemode changes, and cheats on/off weirdness

### ISSUE THREAD

**Issue by grannymc** [FTBTeam/FTB-Modpack-Issues#1571]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.0

### Log Files

no crash logs

### Describe the bug

Can't interact with world, mysterious adventure mode (in player dimenstion, not spawn area)

### Steps to reproduce

These are probably related but might not be. In both cases, I started the world as follows:
1. set gamerules (in the world creation menu) to keepInventory=true, doFireTick=false, doWeatherCycle=false.
2. enabled cheats
3. created a new world, selected the Original start
4. Got to the point where I was growing some oak trees
5. Exited the world for IRL reasons.
6. Game back later and reloaded the world (not the game).

Incident 1: Found out I had mysteriously gotten into Adventure Mode.

Incident 2: Acted like it did in Incident 1 (couldn't interact with anything), but--
(a) couldn't enter commands, so I opened to LAN and turned cheats on
(b) tried /gamemode survival
(c) still couldn't break anything

### Expected behaviour

not this! :)

### Additional information

AMD 3600, 16G, ASRock B550 Pro4, Samsung SSD 970 EVO Plus 500Mb, NVIDIA GdForce GTX 1050 Ti, Razor Ornata Chroma keyboard, Logitech M510 wireless mouse

**Comment by Raidobw2** [comment]
Hmm, I have absolutely no idea what happened... This does sound familiar to https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1542 though and could potentially be linked.
There is one person there that mentioned they joined the same world twice and they couldn't interact or see anything.

Can you confirm between the first time and the second time you entered your world, that you did not close the game (the game stayed on)?

**Comment by grannymc** [comment]
Speaking as a retired programmer this strikes me as something getting overwritten. The symptoms are not consistent, and the one thing every case has in common is that it has happened at or near startup (I am assuming #1542 is related). Restarting the game appears to fix the problem. Which suggests to me that the issue is most likely in the world generation code. That this is very new makes it even more suspect. I would recommend focusing first on the relevant world gen mods unless there is a better starting point. Also my toaster is likely much slower and older than what you guys and most of your testers are using, so this could be a timing issue or race condition. Is the world gen using worker threads? They can be tricky in Java. These are just ideas. I'm heading to bed now but I will do more thorough tests tomorrow if that will help.

**Comment by Raidobw2** [comment]
Thanks for the ideas and feedback! I appreciate it

**Comment by MichaelHillcox** [comment]
Could you confirm if your game mode was actually changed? I'm not sure if from your messages that you checked that the game mode has been changed?

**Comment by grannymc** [comment]
In the first instance, it was adventure. In the second I was unable to run commands to find out, despite opening to lan and turning cheats back on.

**Comment by Sunekaer** [comment]
Can you test version 1.1.0

**Comment by grannymc** [comment]
Yes, I will do so this evening (US eastern time).

**Comment by grannymc** [comment]
I haven't been able to test it yet. IRL got in the way. I'll try to get to it later today.

**Comment by grannymc** [comment]
I've more-or-less reproduced the steps I followed the first two times, although with different seeds and probably a much different detailed order of breaking blocks, etc. So far, no problems.
