### ISSUE TITLE
[Suggestion]: Don't make me install OreExcavation and TwerkSim

### ISSUE THREAD

**Issue by grannymc** [FTBTeam/FTB-Modpack-Issues#1572]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

FTB Ultimine in too restrictive and unconfigurable. (I am NOT asking you to install OE and TS, just make FTB Ultimate more configurable for advanced players).

**Comment by Saereth** [comment]
FTB Ultimine is infact highly configurable with the config + tags as you can see in the nuanced way its setup in SB3. Stone is blacklisted, certain tools work on a range, tools are required to use it. All of that can be configured as well as the size of the tunnels. it's really quite robust. further that, Ultimine sets defining custom tags on both tools and blocks for instance

`event.add("ftbultimine:included_tools", ["mekanism:atomic_disassembler"]);`
Allow the mekanism atomic disassembler to be used with ultimine as a valid tool when it normally wouldnt be

or 
`event.add("ftbultimine:excluded_blocks", ["minecraft:stone"]);`
specifically blacklists blocks you dont want it to work on etc.

I've yet to find a feature of it I can't config so should. If you are requesting certain features though you can always request them at https://github.com/FTBTeam/FTB-Mods-Issues/issues

**Comment by Xiarno** [comment]
How do you make it work on more than 1 stack at a time then? And how do you make it not use food?

**Comment by Raidobw2** [comment]
Open your world in the file explorer and inside the `serverconfig` folder you'll find `ftbultimine-server.snbt`. Edit it with Notepad and change exhaustion to `0.0d` and the max blocks to the number you want:
![image](https://user-images.githubusercontent.com/17010632/200151135-6ca6bad0-a58e-478b-bc89-2696fa07fd66.png)

Also for next time if you need help understanding the mod, feel free to drop by the [FTB Discord](https://go.ftb.team/discord) instead.
We're looking to document more of the mod in the future, which would include information similar to what I've just mentioned for instance, making it easier for players to tweak or understand the mod.

**Comment by Xiarno** [comment]
It's nice but it would be cool to have all that configuration directly in game using the mod list config thing idk what it's called exactly. Makes it more convenient and intuitive.

I would've never guessed that the Ultimine config are in the WORLD folder rather than the expected "config" folder.

**Comment by Xiarno** [comment]
> FTB Ultimine is infact highly configurable with the config + tags as you can see in the nuanced way its setup in SB3. Stone is blacklisted, certain tools work on a range, tools are required to use it. All of that can be configured Further that, Ultimine allows defining custom tags on both tools and blocks for instance
> 
> `event.add("ftbultimine:included_tools", ["mekanism:atomic_disassembler"]);` Allow the mekanism atomic disassembler to be used with ultimine as a valid tool when it normally wouldnt be
> 
> or `event.add("ftbultimine:excluded_blocks", ["minecraft:stone"]);` specifically blacklists blocks you dont want it to work on etc.
> 
> I've yet to find a feature of it I can't config so should. If you are requesting certain features though you can always request them at https://github.com/FTBTeam/FTB-Mods-Issues/issues

Also Saereth mentioned configuration that blacklists stone to prevent them to be Ultimined in Stone Block 3. Where to disable that config? It isn't in either the server config folder you mentioned nor is it in the usual config folder.

**Comment by SephirothWS** [comment]
Not a huge fan of stone being blacklisted in Ultimine unlike the previous iterations of the pack. Please revert this nerf.
