### ISSUE TITLE
[Bug]: Client crash when checking uses in REI on items from EnderStorage

### ISSUE THREAD

**Issue by Partplayer** [FTBTeam/FTB-Modpack-Issues#1574]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.1

### Log Files

[crash-2022-11-02_16.25.32-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9924257/crash-2022-11-02_16.25.32-client.txt)
[crash-2022-11-02_16.32.15-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9924283/crash-2022-11-02_16.32.15-client.txt)
[crash-2022-11-02_16.36.55-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9924298/crash-2022-11-02_16.36.55-client.txt)

### Describe the bug

When checking uses of Ender Chest and Ender Tank client crashes.

### Steps to reproduce

Either obtain or look up Ender Storage items in REI
Press U on item or right click in REI to check uses

### Expected behaviour

See the uses for the Item I.E. ender storage chest should show recipe for ender pouch

**Comment by Sunekaer** [comment]
https://github.com/Creators-of-Create/Create/issues/3981

**Comment by MADMAN1O01** [comment]
[crash-2022-11-08_20.37.27-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9966855/crash-2022-11-08_20.37.27-client.txt)

**Comment by zhukant** [comment]
This is still happening in the 1.4.2 Beta modpack version. I am running a Mac OS Java client in single player. Of note, pressing "R" on these items does not reproducibly crash the game, but does cause a noticeable lag spike in.

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
