### ISSUE TITLE
[Bug]: Hemp Seeds don't grow to the point where they can be harvested by Botany Pots

### ISSUE THREAD

**Issue by MrGREGhimself** [FTBTeam/FTB-Modpack-Issues#1577]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.0

### Describe the bug

Immersive Engineering's Hemp Seeds don't seem to grow past a certain point when in Botany Pot

### Steps to reproduce

1. Craft Hopper Botany Pot
2. Insert Dirt and Hemp Seeds into it
3. Observe it grow
4. Observe it stop growing

### Expected behaviour

It grows to the stage where it gets collected/harvested by the Hopper Botany Pot

### Screenshots

Both bamboo and hemp seeds were planted at the same time (a couple of seconds apart). 
20 minutes later this is the result.

![image](https://user-images.githubusercontent.com/12535527/199614422-4e631992-a497-4fd9-979d-3e4e86ee64a4.png)

### Additional information

There are no messages displayed in the Hopper Botany Pot that there could be some issues (like with wrong materials etc.)

**Comment by Raidobw2** [comment]
Hemp seeds also are unobtainable apparently. This should be checked!

**Comment by MrGREGhimself** [comment]
> Hemp seeds also are unobtainable apparently. This should be checked!

I've had no issues with the release version (on the FTB app) when it comes to getting seeds and/or hemp seeds from using bonemeal on grass blocks.

**Comment by Karma-Fox** [comment]
I'm having a similar but yet different issue. I've planted hemp in hoed dirt and it never grows at all. Everything else around it grows constantly, but I've not seen the hemp move from 0% growth.

**Comment by MrGREGhimself** [comment]
> I'm having a similar but yet different issue. I've planted hemp in hoed dirt and it never grows at all. Everything else around it grows constantly, but I've not seen the hemp move from 0% growth.

I've had no issues there but it does take ages.
![image](https://user-images.githubusercontent.com/12535527/199690060-dd6be4ba-99ec-4e9c-bfd1-5b0e0d4604d7.png)

**Comment by MrGREGhimself** [comment]
The original issue seems to be fixed in 1.0.1.
![image](https://user-images.githubusercontent.com/12535527/199690411-37b246ec-b889-4ae1-ba02-7ac8c36acf18.png)

**Comment by Karma-Fox** [comment]
In my case, it's been running on a server, and chunkloaded, for 8 hours with zero growth. I've never experienced this from industrial hemp in any other mod pack.

**Comment by Raidobw2** [comment]
Make sure the plant has enough light next to it, and that `/gamerule randomTickSpeed` is currently set to 3 (default value).
Else set it with `/gamerule randomTickSpeed 3`.

Taken from vanilla, but I'll guess Immersive Engineering extends crops so it's the same rules that apply:
![image](https://user-images.githubusercontent.com/17010632/199699551-3ca096b6-ad7e-4889-9988-b4a917050ad5.png)

**Comment by Karma-Fox** [comment]
I have wheat and carrots growing around it without issue (a line of carrots, a line of hemp, a line of wheat). The carrots and wheat grow just fine. The hemp does nothing.
