### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TheRandomCrafter83** [FTBTeam/FTB-Modpack-Issues#1578]
### Modpack

Stone Block 3 

### Modpack version

1.0.1

### Log Files

https://mclo.gs/haxw9s7

### Describe the bug

Game crashes when using /. seems to be something going on with MineTogether

### Steps to reproduce

1. start a game
2. go into your personal dimension
3. press the / key

### Expected behaviour

would expect the cheat commands to show up

**Comment by Draylynn** [comment]
MineTogether is aware of crashing with certain buttons, duplicate chat and some other bugs regarding SB3 - The MT dev's are looking into it.

**Comment by Sunekaer** [comment]
Should be fixed in the newest version (1.1.1)
