### ISSUE TITLE
[Bug]: Dust not having uses on REI/JEI for washing/splashing

### ISSUE THREAD

**Issue by Nwitlyck** [FTBTeam/FTB-Modpack-Issues#1579]
### Modpack

Ftb StoneBlock 3

### Modpack version

1.0.1

### Describe the bug

Dust not having uses on REI/JEI even so you can wash it to get redstone and some others stuff

### Steps to reproduce

1. Open REI/JEI
2. Rearch for dust
3. Press the 'U' by deafult
4. And there wont be recipe to be show 
5. You can also use a encased fan with water 
6. You but dust on the way and there is gona be some kind of output

### Expected behaviour

dust showing uses on REI/JEI

**Comment by Raidobw2** [comment]
That is odd, there was a similar issue with Gravel but it was fixed. Do you see the uses to wash Gravel in-game?

**Comment by Nwitlyck** [comment]
Yeah now I can see the gravel one but in the 1.0.0 version no. But now on 1.0.1 as I said in the report I cant see the dust recipes

**Comment by Raidobw2** [comment]
Should be fixed in 1.0.2+
