### ISSUE TITLE
[Bug]: Unable to progress

### ISSUE THREAD

**Issue by April462** [FTBTeam/FTB-Modpack-Issues#1580]
### Modpack

StoneBlock 3

### Modpack version

1.0.1

### Describe the bug

I am unable to get redstone from washing. the recipes doesn't show up in REI and doesn't work.

### Steps to reproduce

throw dust/sand into washer
no items are produced

### Expected behaviour

It should make items

**Comment by Raidobw2** [comment]
I'll keep only https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1579 for tracking for the lead modpack developer, you can subscribe to the other issue to get notifications when this is worked on.
Thanks for reporting in any case!
