### ISSUE TITLE
[Bug]: Crashed when opening to LAN

### ISSUE THREAD

**Issue by relliken** [FTBTeam/FTB-Modpack-Issues#1582]
### Modpack

StoneBlock 3

### Modpack version

1.0.1

### Describe the bug

after loading in to a single player world, after opening to LAN the game crashes

### Steps to reproduce

1 start game
2 load a singleplayer world
3 open to LAN

### Expected behaviour

internal server starts and gives a port number that its open to

### Additional information

[crash-2022-11-02_18.43.13-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9924884/crash-2022-11-02_18.43.13-client.txt)

**Comment by Raidobw2** [comment]
Fixed in-dev by MineTogether, when MT passes version 6.0.7 for Forge (see https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/all?filter-game-version=2020709689%3A9008) this can be fixed in StoneBlock 3 as well

**Comment by Raidobw2** [comment]
MT update fixes this: https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/4065023
