### ISSUE TITLE
[Bug]: hive hopper

### ISSUE THREAD

**Issue by DiggityMan420** [FTBTeam/FTB-Modpack-Issues#1583]
### Modpack

stoneblock 3

### Modpack version

1.0

### Describe the bug

I don't know if its intended  or not but the thermal hive hopper shows up in rei but no recipe is associated with it. if this is intended maybe remove the hive hopper from rei

### Steps to reproduce

1. open rei
2. type hive hopper
3. click hopper
4. nothing shows up

### Expected behavior

recipe for hive hopper

**Comment by Sunekaer** [comment]
Hi
I talked to King Lemming, there is no recipe as Cultivation isn't in the pack, it only shows a recipe if it's present, ill hide the block as it doesn't have any uses in REI anyway.
