### ISSUE TITLE
[Suggestion]: add fast leaf decay

### ISSUE THREAD

**Issue by DiggityMan420** [FTBTeam/FTB-Modpack-Issues#1584]
### Modpack

stoneblock 3

### Is your suggestion related to a problem? Please describe.

its frustrating to have to take every leaf out of a small cave starting in  a larger cave i can see it being not as much a problem but smaller ones well would like to see fast leaf decay mod added

### Mod suggestion

https://github.com/Olafski/FastLeafDecay

**Comment by MichaelHillcox** [comment]
Already planned :)
