### ISSUE TITLE
[Bug]: Gateways spawn rewards after despawning mobs

### ISSUE THREAD

**Issue by hanky21** [FTBTeam/FTB-Modpack-Issues#1585]
### Modpack

Inferno

### Modpack version

1.1.1

### Describe the bug

After a portal opens teleporting away far enough to despawn the mobs will "complete" the wave giving out rewards. The chunk with the portal can be claimed, force loaded or none and it still works.

### Steps to reproduce

1. Spawn portal (If chunks are not force loaded you have to wait until the mobs spawn)
2. Teleport away to despawn mobs
3. Teleport back to spawn next wave, then repeat (if chunks are force loaded just wait until all waves would have spawned)
4. Reward....I mean report bug

### Expected behaviour

The portal should fizzle and give no rewards

### Screenshots

Even weirder it works with infernal commander but juts leaves behind the shulkers and pigs
![image](https://user-images.githubusercontent.com/75486781/199627296-9a8fd357-2803-4dcf-8b80-4a2b4b21a90b.png)

**Comment by Saereth** [comment]
the update in 1.3 seems to fix this, let me know if you can reproduce after the update
