### ISSUE TITLE
[Bug]: String-less Progression

### ISSUE THREAD

**Issue by DuneganS** [FTBTeam/FTB-Modpack-Issues#1588]
### Modpack

Stoneblock 3

### Modpack version

1.0.1

### Describe the bug

There is no way to get string to make an Engineer's Hammer when using "The original" world. You need string to make the Engineer's Hammer but string is only available from Flax or Wool. You cant get either of those early game

### Steps to reproduce

1. Create  a new world
2. Go through the portal
3. Select "The original"
4. Attempt to make an "Engineer's Hammer"

### Expected behaviour

A way to get string or another way to make iron sheets to progress

**Comment by Sunekaer** [comment]
There is multiple ways.
Make a grass area and get a sheep.
Make a mob farm and get spiders.
Break grass with hand and get hemp.
Make a mechanical press and get sheets

**Comment by Karma-Fox** [comment]
Actually, hemp refuses to grow as well. And, while there are many other ways in which to get string, that does not negate the fact that the fact a seed is not obtainable, is indeed a bug. So unless said bug has been fixed, I am wondering why this way closed as completed.

**Comment by Raidobw2** [comment]
Hemp is being tracked at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1577, if you were mentioning a different problem, let me know.

I will add some of the information you stated there as well.

**Comment by Karma-Fox** [comment]
Actually, seeing that, my issue with hemp is different, but I will add it to that #1577
