### ISSUE TITLE
[Bug]: Dust washing recipe not showing for Redstone in REI

### ISSUE THREAD

**Issue by eeakett** [FTBTeam/FTB-Modpack-Issues#1589]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.1

### Describe the bug

The method for creating redstone from dust does not appear under the REI entry for redstone dust.

### Steps to reproduce

Search redstone in REI, open the recipe window, select bulk washing tab.

### Expected behaviour

The Dust washing recipe should show up in the bulk washing tab of REI

**Comment by Raidobw2** [comment]
Hi, thanks for reporting! It appears there is already a report of this at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1579, so I will be closing this one to avoid tracking duplicates. You can subscribe to the other issue to be notified when it is worked on
