### ISSUE TITLE
[Bug]: Does not launch on Prism Launcher 5.0

### ISSUE THREAD

**Issue by Buddhalobes** [FTBTeam/FTB-Modpack-Issues#1590]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.1

### Log Files

https://mclo.gs/Lais66j

### Describe the bug

On launching the game, it loads in normally with splash screen and music until a notification of "Resources failed to reload" message appears on the top right of the window followed by a crash in most cases. If the window stays open, it is the pause menu as if I was loaded into a world and pressed escape. Returning to the Main menu and clicking single or multiplayer causes it to crash

### Steps to reproduce

1. Launch the game.
2. if it stays open, try to make a world.
3. crashes leaving a log like the one linked.

### Expected behaviour

To launch to the main menu and try out the pack.

### Additional information

Prism Launcher released a new version 2 days ago as of this post, 5.1. I am a linux user running NixOS and that updated launcher has not been packaged for NixOs yet. I do not think this is the cause as other 1.18 packs launch and play on the launcher before and after experiencing this crash.

**Comment by MichaelHillcox** [comment]
Try the FTB app, we do not support third party launchers.

**Comment by Buddhalobes** [comment]
> Try the FTB app, we do not support third party launchers.

The FTB launcher is a .sh that I have to set as executable. That is one of those things you are told to never do on linux unless you wrote it, and in that case you are told to absolutely never run it that way. 

I understand that you don't support other launchers, but it seem like the app support for linux is lacking. Even if the launcher is a giant shell script under the hood, there are packaging formats that add sand-boxing by design and would be listed in trusted spaces.

**Comment by MichaelHillcox** [comment]
The installer is just an unpacker and installer. It uses install4j and we'd be considered a safe source.

If you do not feel comfortable using the sh file, I don't really have any good recommendations for you. I think the is an aur package but it just runs our installer.

We are working to improve our Linux support but it doesn't help when Linux uses don't use our app 😢 

I'll be happy to support you in sorting out the pack for Linux if you're using our app.
