### ISSUE TITLE
[Bug]: Drawer Inventory Being Deleted When Crafting

### ISSUE THREAD

**Issue by Martian15** [FTBTeam/FTB-Modpack-Issues#1591]
### Modpack

Stoneblock 3

### Modpack version

1.0.1

### Describe the bug

When crafting with the Modular Storage from RFTools, it used a full drawer of cobble in my inventory to craft a compacting drawer. Deleting the cobble and upgrades. Not sure if this was intentional or not, but still. Best I can tell, this happens anytime you craft using a drawer with items in it.

### Steps to reproduce

Use drawer with items in it to craft something else that requires a drawer.

### Expected behaviour

Either for it to retain an inventory or not work?

### Additional information

If this is intentional, sure, it just felt bad deleting 38k cobble lol

**Comment by Sunekaer** [comment]
https://github.com/Buuz135/FunctionalStorage/issues/112

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
