### ISSUE TITLE
[Bug]: world corruption

### ISSUE THREAD

**Issue by RabzoiGaming** [FTBTeam/FTB-Modpack-Issues#1593]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.1

### Log Files

[crash-2022-11-03_12.01.58-client - Copy.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9927442/crash-2022-11-03_12.01.58-client.-.Copy.txt)

### Describe the bug

everytime i join the world the game crashes 

### Steps to reproduce

no clue

### Expected behaviour

game just crashes

### Additional information

just saying saving world then game crashes

**Comment by Raidobw2** [comment]
Update your MineTogether mod file if you want, that should fix the crashes. Use this one and replace the old one with it: https://www.curseforge.com/minecraft/mc-mods/creeperhost-minetogether/files/4065023
