### ISSUE TITLE
[Bug]: Server files for Stoneblock 3

### ISSUE THREAD

**Issue by calog3no** [FTBTeam/FTB-Modpack-Issues#1596]
### Modpack

Stone Block 3

### Modpack version

1.0.1

### Describe the bug

I downloaded server files and updated Nodecraft server and compressed recipes not showing in pervious save.  Started new world and no custom spawn area and spawned underground in wall.

### Steps to reproduce

Download server files to see if recipes and structures are correct.

### Expected behaviour

Compressed recipes working and new start having pre-generated structurers and starting world types

**Comment by Sunekaer** [comment]
Did you upload all the folders? Sounds like missing the kubejs folder and maybe more

**Comment by calog3no** [comment]
I just deleted and ran the installer again and no kubejs folder was generated. i used serverinstall_100_2276.exe

**Comment by Raidobw2** [comment]
Are you able to copy the kubejs folder from your client into your server?

**Comment by calog3no** [comment]
yes I can I wasn't sure if that needed to be updated with the new server files. I downloaded the 1.0.2 update and that was also missing the kubejs folder just fyi. I will comment back here if updating with kubejs folder does not work. Thanks for the reply!

**Comment by calog3no** [comment]
so I when I uploaded the kubejs folder from my instance the world would not load. Once thes erver started there was a kubejs folder, but it seemed like I was in a minetogether type server. I will just wait for nodecraft to support the pack.  I can play single player for now. Feel free to close this issues thanks for the help
