### ISSUE TITLE
Crash Stoneblock 3

### ISSUE THREAD

**Issue by guruxxt** [FTBTeam/FTB-Modpack-Issues#1597]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.1

### Log Files

[crash-2022-11-03_09.49.22-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9929365/crash-2022-11-03_09.49.22-client.txt)

### Describe the bug

 everytime i start modpack it crashes[Bug]: 

### Steps to reproduce

............

### Expected behaviour

................

**Comment by Raidobw2** [comment]
Update to 1.0.2 and let me know if that is fixed (it should)

**Comment by guruxxt** [comment]
> Update to 1.0.2 and let me know if that is fixed (it should)

I updated the modpack to version 1.0.2, and it still crashes.
[crash-2022-11-04_08.36.08-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9937826/crash-2022-11-04_08.36.08-client.txt)

**Comment by Raidobw2** [comment]
Oh, could you add your latest.log here as well? Thanks in advance!

**Comment by guruxxt** [comment]
> Oh, could you add your latest.log here as well? Thanks in advance!

yes, it's there
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9937903/latest.log)

**Comment by Raidobw2** [comment]
Thanks, I've forwarded it with the error to the MineTogether devs. Can you try using Java 17 instead of Java 18 as well? Let me know if that works

**Comment by guruxxt** [comment]
> Thanks, I've forwarded it with the error to the MineTogether devs. Can you try using Java 17 instead of Java 18 as well? Let me know if that works


I tried with java 17, 18 and 19 it still crashed, I removed MineTogether now it's not crashing, thanks for the help.

**Comment by Sunekaer** [comment]
Can you check if this works on the version released today?
