### ISSUE TITLE
[Suggestion]: Botani Pots uses

### ISSUE THREAD

**Issue by Nwitlyck** [FTBTeam/FTB-Modpack-Issues#1598]
### Modpack

Ftb StoneBlock 3

### Is your suggestion related to a problem? Please describe.

I think there should be like when u press 'U' by deafult in a botanipot being able to see the plats that you can work with on botanipots

**Comment by MichaelHillcox** [comment]
This requires the mod developer of botani pots to add this feature, please suggest the feature to them. :)

**Comment by Raidobw2** [comment]
Already did suggest it to them earlier at https://github.com/Darkhax-Minecraft/BotanyPots/issues/272
