### ISSUE TITLE
[Suggestion]: Refined storage addon mods

### ISSUE THREAD

**Issue by CinnamonShaey** [FTBTeam/FTB-Modpack-Issues#1599]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

All these mods are just QOL for Refined Storage

### Mod suggestion

RSinfinitybooster - adds more range options to wireless grid
Cabletiers - adds multiple tiers of different cables like importers and exporters and so on
Extradisks - bigger storage disks
Extrastorage - higher tier crashers
and maybe Universalgrid - a wireless grid that combines the different wireless grids

**Comment by Sunekaer** [comment]
Hi 
Thanks for the suggestions of the mods, i have looked through them and decided to only add RSinfinitybooster.

**Comment by CinnamonShaey** [comment]
ah great! will help other people too! ill just add the others myself on my private server i play with friends on then, but thank you for your time!
