### ISSUE TITLE
[Bug]: Osmium Helmet gives +1 armor when compared to Netherite Helmet

### ISSUE THREAD

**Issue by Copperearth** [FTBTeam/FTB-Modpack-Issues#1600]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.1

### Describe the bug

The Osmium and Netherite Armors are completely identical except for +1 extra armor on the helmet. I do not think this is intentional, as the two armors are otherwise identical, apart from durability.

### Steps to reproduce

1. Check stats on Osmium armor
2. Compare them to the stats of Netherite armor

### Expected behaviour

Osmium Helmet and Netherite Helmet should have identical armor stats

### Screenshots

![image](https://user-images.githubusercontent.com/22625584/199751797-da22120a-288a-4e87-9a6a-cc564156a9ff.png)
![image](https://user-images.githubusercontent.com/22625584/199752016-ccca98bb-c0c7-4496-acae-df601099f33e.png)

**Comment by Sunekaer** [comment]
I get your point, nothing really i can do about this, i would recommend you opening a suggestion on https://github.com/mekanism/Mekanism/issues about getting this changed.
