### ISSUE TITLE
[Bug]: String is impossible to get in default world

### ISSUE THREAD

**Issue by Joly0** [FTBTeam/FTB-Modpack-Issues#1605]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.1

### Describe the bug

I tried everything, but i cant get strings for the engineering hammer in the default old stoneblock world. I am unable to get hemp seeds or flax and mobs or monsters apparently dont spawn, so i cant even kill spiders or sheep.

### Steps to reproduce

Start a default old stoneblock world and try to get strings.

### Expected behaviour

Some option to get strings

**Comment by Copperearth** [comment]
kill spiders or make a string chicken or get flax

**Comment by Joly0** [comment]
> kill spiders or make a string chicken or get flax

Thx for the reply, though as i said, neither mobs nor monsters spawn and i have no idea how to get flax

**Comment by iDarper** [comment]
I got my string from dungeons. Plenty of spider webs

**Comment by Joly0** [comment]
> I got my string from dungeons. Plenty of spider webs

Hm, ok. Looks like i have to find some. 

Though would be great if hemp or flax would be added to the loot table of dirt, would make it more fair compared to other maps, where its quite easy to get early hemp seeds though tall grass

**Comment by Shuro** [comment]
Personally, i got hemp seeds from immersive, but they won't grow on farmland + just grow sometimes in botany pots and at some point just stop working. Have to remove seed from pot and replant it to get it starting again. It just hangs at 100%, plant not growing.

**Comment by itsrosey** [comment]
> Personally, i got hemp seeds from immersive, but they won't grow on farmland + just grow sometimes in botany pots and at some point just stop working. Have to remove seed from pot and replant it to get it starting again. It just hangs at 100%, plant not growing.

I got industrial hemp from using bone meal on grass and breaking the grass grown. The ONLY way I am able to make it grow is more bone meal. Torches all around it, water saturated farmland... My next step is to try Rich Soil out of a planter then create one with it. But they have not grown for me by natural means. Side note, at full growth, broke the tops off and, of course, they did not grow back. Just had the bottom half. All other crops are growing around it.

As for the first string I received, was from small, dark room (at least 25 blocks away from spawn) yet big enough to spawn spiders.
