### ISSUE TITLE
[Suggestion]: More detail in the chicken catcher quest description

### ISSUE THREAD

**Issue by sage-cook** [FTBTeam/FTB-Modpack-Issues#1606]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

As someone who hasn't played with the chickens mod in a while I forgot that the chicken catcher does not work on vanilla chickens and how to convert chickens into smart chickens. This info might be helpful to have in the chicken catcher quest so as not to confuse new players.

**Comment by BigAl607** [comment]
Or you could just let it work on vanilla chickens

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/201557425-03aca8ba-ed53-48d0-9bfb-71c04d2b7c9a.png)
