### ISSUE TITLE
[Bug]: Players on Server can't interact with the chat and even cause a client crash

### ISSUE THREAD

**Issue by yipiislay** [FTBTeam/FTB-Modpack-Issues#1607]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.1

### Describe the bug

When players on the server open the chat, a message reading "Unable to send messages while client is disconnected" appears in the text bar. They cannot interact with anything inside of the chat (can't type, click on something, etc.) and even crash their clients by clicking on the emoticon button on the bottom right.

Important note: Clicking on "Join [...]" instead of "Don't ask me again" on the MineTogether notification popping up in the bottom left corner when joining seemed to fix the problem.

### Steps to reproduce

1. Paste the given server files from the Feed The Beast website into a server
2. Join the server
3. Open chat
4. Try to invite players to your FTB Team or join an already existing one through commands / Try to send a message

### Expected behaviour

Not being able to type anything into the text box

### Screenshots

![unknown200](https://user-images.githubusercontent.com/117386100/199794703-43485449-8783-44e0-b3bb-cf24af75c0ed.png)

### Additional information

Possible exceptions: The problem isn't affecting a player who already created a singleplayer world

**Comment by TimTacToe** [comment]
I just had the same experience but by disabling Mining Together mod the game works as normal again. Just putting it out there that there is an easy workaround to get your chat and commands back.

**Comment by Raidobw2** [comment]
Update your game to 1.0.2 and let me know if that fixes it, MineTogether pushed out a fix. There is also another update on the way to fix another load issue.

**Comment by Sunekaer** [comment]
Should be fixed in 1.1.0
