### ISSUE TITLE
[Bug]: Editing chat size while being on a server crashes the client

### ISSUE THREAD

**Issue by yipiislay** [FTBTeam/FTB-Modpack-Issues#1608]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.1

### Describe the bug

When trying to change the chat size in the Accessibility Settings, the game instantly crashes when clicking on the slider.

### Steps to reproduce

1. Join a server
2. Click on settings in the pause menu
3. Click on Accessibility Settings
4. Adjust the "Chat Text Size"

### Expected behaviour

Client crashes

### Additional information

Chat size can be adjusted when in the main title screen.

**Comment by Raidobw2** [comment]
Can you update to 1.0.2 and let me know if that's fixed? There was a MineTogether bug with the chat causing crashes but it should have been resolved, thanks

**Comment by Sunekaer** [comment]
Should be fixed in 1.1.0
