### ISSUE TITLE
[Bug]: Spelled "Node Overclocker Singularity" Wrong

### ISSUE THREAD

**Issue by LJLittleman7** [FTBTeam/FTB-Modpack-Issues#1610]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.1

### Describe the bug

The Node Overclocker Singularity is spelled as "Node **Overcolcker** Singularity", the O and L are the wrong way round. Sorry if this is the wrong place to put this since its not really a _bug_, but yeah

### Steps to reproduce

1. In JEI Search up Node Singularity
2. Look at the typo
This shouldnt be a required step, it should be optional

### Expected behaviour

not a typo

**Comment by Raidobw2** [comment]
It's indeed a bug, thanks for reporting here it's perfect!
