### ISSUE TITLE
[Suggestion]: Add AE2 Things

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Modpack-Issues#1613]
### Modpack

Stroneblock 3

### Is your suggestion related to a problem? Please describe.

i feel that ae2 things would help automate ae2 more

### Mod suggestion

AE2 Things: (MIT)
https://www.curseforge.com/minecraft/mc-mods/ae2-things-forge

**Comment by tyler489** [comment]
I believe stoneblock is 1.19 and that mod is only for 1.18 isn't it?

**Comment by Sunekaer** [comment]
SB is 1.18.2

**Comment by tyler489** [comment]
> SB is 1.18.2

my mistake
