### ISSUE TITLE
[Bug]: Dust washing recipe missing from REI

### ISSUE THREAD

**Issue by PianoHallvard** [FTBTeam/FTB-Modpack-Issues#1615]
### Modpack

StoneBlock 3

### Modpack version

1.0.1

### Describe the bug

Dust bulk washing recipe (create encased fan) no longer shows in REI

### Steps to reproduce

1. Get a piece of dust (ftb stoneblock mod)
2. hit U to show uses (or whatever keybind config your client is bound to)
3. Watch as nothing happens

### Expected behaviour

Show dust wash to redstone, certus dust etc

**Comment by Saereth** [comment]
this should be fixed now in 1.0.2
