### ISSUE TITLE
[Bug]: tab completion /ftb-stoneblock prune crashes client

### ISSUE THREAD

**Issue by fraenkelc** [FTBTeam/FTB-Modpack-Issues#1616]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.2

### Log Files

https://pste.ch/oyatuwaguq.cs

### Describe the bug

when using the tab completion after  "/ftb-stoneblock prune " the client crashes. A crash log is *not* written.

### Steps to reproduce

* connect to a server as op
* type `/ftb-stoneblock prune `

### Expected behaviour

I guess a list of pruneable dimensions is listed ? At least the client should not crash.

### Additional information

 The normal log contains a follow-up exception from inside `ApiManager.sendCrashReport`. This might be suppressing the normal crash report.

**Comment by MichaelHillcox** [comment]
Fixed
