### ISSUE TITLE
[Bug]: Chat Issue

### ISSUE THREAD

**Issue by DarkbrineOG** [FTBTeam/FTB-Modpack-Issues#1618]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.2

### Log Files

[crash-2022-11-03_21.15.56-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9934205/crash-2022-11-03_21.15.56-client.txt)
[crash-2022-11-03_21.20.46-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9934206/crash-2022-11-03_21.20.46-client.txt)
[crash-2022-11-03_21.24.40-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9934207/crash-2022-11-03_21.24.40-client.txt)

### Describe the bug

Changing around anything involving the chat settings crashes the game.

### Steps to reproduce

1) Go to Options
2) Click on the Chat Options button
3) Change anything involving the chat

### Expected behaviour

Loads a bit, then crashes.

### Screenshots

![2022-11-03_21 24 21](https://user-images.githubusercontent.com/107524841/199865422-8fc44bd3-80fa-4e3e-837f-fbfdeb0fcf72.png)

**Comment by DarkbrineOG** [comment]
Forgot to note this - it works upon loading back in but you need to have exited beforehand for it to work.

**Comment by Sunekaer** [comment]
Should be fixed in 1.1.0
