### ISSUE TITLE
[Bug]: Game  crashed after placing FTB Power POT MK1 (You cant find it im Creative  Inventory)

### ISSUE THREAD

**Issue by Julcraft14** [FTBTeam/FTB-Modpack-Issues#162]
### Modpack

FTB Oceanblock

### Modpack version

1.4.1

### Describe the bug

I tried the Power in a creative World but then my game crashed

### Steps to reproduce

1. Craft a Power Pot 
2. PLace it on a chest

### Expected behaviour

Should not Crahs

**Comment by MichaelHillcox** [comment]
Crash report please

**Comment by Julcraft14** [comment]
https://pastebin.com/mkpb3Xnf

**Comment by Julcraft14** [comment]
https://pastebin.com/gTEwCGqs
Afeter placing

**Comment by Julcraft14** [comment]
It isnt my real world so its no problem
