### ISSUE TITLE
[Bug]: Pretty pipes crash

### ISSUE THREAD

**Issue by gigabit101** [FTBTeam/FTB-Modpack-Issues#1624]
### Modpack

Stoneblock 3

### Modpack version

1.0.1

### Log Files

https://pste.ch/goverinuge.pl

### Describe the bug

Server crash when placing an entangled block next to a pretty pipe

### Steps to reproduce

1 Place pretty pipe
2 Place entangled block
3 Crash server

### Expected behaviour

no crash

**Comment by Sunekaer** [comment]
https://github.com/Ellpeck/PrettyPipes/issues/162

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
