### ISSUE TITLE
[Bug]: instance crasing

### ISSUE THREAD

**Issue by gus637** [FTBTeam/FTB-Modpack-Issues#1625]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.2

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9937723/latest.log)

### Describe the bug

every time sins I first played the mod it crass, but sometimes it displays the pas gui

### Steps to reproduce

open the FTB app 
go to SB3
click on play
wait a minute
craze

### Expected behaviour

the game lods

**Comment by Raidobw2** [comment]
Remove the MineTogether mod for now, it should fix the crashes. This is the same issue as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1621, so I will close this current issue, but thanks for reporting!
P.S. Another StoneBlock patch should quickly address this problem and resolve it
