### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kotkowski** [FTBTeam/FTB-Modpack-Issues#1626]
### Modpack

Stoneblock 3

### Modpack version

1.0.1

### Describe the bug

Exchanging tool allows to dupe certain blocks (parts of multiblocks)

### Steps to reproduce

1. Use Exchanging Tool
2. try to exchange part of coke oven
3. Exchange without losing coke bricks

### Expected behaviour

Multiblock is broken and blocks exchanged

**Comment by MichaelHillcox** [comment]
Report to building gadgets :+1:
