### ISSUE TITLE
[Bug]: Pretty pipes console spam

### ISSUE THREAD

**Issue by gigabit101** [FTBTeam/FTB-Modpack-Issues#1628]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.1

### Log Files

https://pste.ch/egurexamak.pl

### Describe the bug

Console spam from an exception in pretty pipes

### Steps to reproduce

1. Use pretty pipes with item terminals while linked to drawers 
2. Console spam every time you open the terminal

### Expected behaviour

No exceptions

**Comment by Sunekaer** [comment]
https://github.com/Ellpeck/PrettyPipes/issues/163

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
