### ISSUE TITLE
[Feature Request]: Project Red - FTB Endeavour

### ISSUE THREAD

**Issue by daneleo** [FTBTeam/FTB-Modpack-Issues#163]
### Mod

FTB Endeavour

### Description

Is it possible that we can add Project Red Into the modpack? Its finally been updated to 1.16.5 and works flawlessly with testing it out on the modpack

**Comment by Sunekaer** [comment]
If we do a 2.0.0 update, then we'll add the mod as it require a bit of worldgen changes and some more testing then just a normal pack update
