### ISSUE TITLE
[Bug]:  Chickens in REI drastically drops fps sometimes

### ISSUE THREAD

**Issue by Shikamaji** [FTBTeam/FTB-Modpack-Issues#1630]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.1

### Describe the bug

Searching for "Chickens" mod in the REI will drastically drops fps

### Steps to reproduce

Open REI and search for @chickens.

### Expected behaviour

Being able to do chickens without being forced to 5 fps

**Comment by Sunekaer** [comment]
Hmm weird mine didnt drop, but im also on new versions of those 2 mods, let me know once the new update is out if that helps
