### ISSUE TITLE
[Suggestion]: Adding Refined Storage Addons ?

### ISSUE THREAD

**Issue by Steinzu** [FTBTeam/FTB-Modpack-Issues#1633]
### Modpack

FTB Stoneblock 3

Hello o/

I was wondering if adding any of the refined storage addons was planned ? Would be a little bit more confortable to at least have ExtraStorage for auto-crafting.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/extrastorage

Shouldn't really need a presentation but it adds higher tiers of transportation means, storage disks and crafters.

**Comment by Sunekaer** [comment]
Duplicate of #1599
