### ISSUE TITLE
[Bug]: minecolonies mod causes crash

### ISSUE THREAD

**Issue by Anzulo1984** [FTBTeam/FTB-Modpack-Issues#1634]
### Modpack

FTB Inferno

### Modpack version

1.2.1

### Log Files

https://pastebin.com/gqXSZa2E

https://pastebin.com/WXPEF1aH

### Describe the bug

Game crashes on a dedicated multiplayer server

I am together in a Team with a friend who owns a colony, crash only occours to me, my friend is not affected

I guess it has something to do with assigned permissions

### Steps to reproduce

1. Be on a Team with a friend
2. Friend owns a colony
3. Talk to NPCs (was a guard NPC)
4. Crashes unpredicatbly

### Expected behaviour

not to crash

**Comment by Saereth** [comment]
mc updated and should fix this for 1.3 once it out
