### ISSUE TITLE
[Bug]: Create water wheel output different depending what way they're facing (north/east).

### ISSUE THREAD

**Issue by CubeStick** [FTBTeam/FTB-Modpack-Issues#1635]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.2

### Describe the bug

Depending on what way the water wheels from Create are facing the output is different.

In the first screenshot I'm facing north and it's output is 192su.
In the second screenshot I'm facing east and it's output is 320su.

I'm using the exact same setup for both, they just face a different way.
In the third screenshot you can see the setup I use that's the same on the Create wiki.

### Steps to reproduce

Build 2 exact same setups but let them face different directions.
See that 1 water wheel outputs 192su and the other 320su.

### Expected behaviour

Both should have the same output.

### Screenshots

[https://imgur.com/a/pDhEeb7](url)

**Comment by Bimmr** [comment]
Are you switching which way the water is flowing as well?

**Comment by CubeStick** [comment]
No, it's the same setup.

**Comment by Bimmr** [comment]
That would be the issue then. The water wheel's fins are slanted so it matters which way the water is flowing over the wheel.

**Comment by Bimmr** [comment]
![image](https://user-images.githubusercontent.com/5053870/200084054-f7a2b4fa-82e8-4b47-810f-3d9c0eedc253.png)

**Comment by CubeStick** [comment]
Yep, that was the problem.
Thanks.
