### ISSUE TITLE
[Bug]: Molten Core does not drop from magma cubes 

### ISSUE THREAD

**Issue by Wargoncz** [FTBTeam/FTB-Modpack-Issues#1637]
### Modpack

FTB Inferno

### Modpack version

1.2.1

### Describe the bug

Molten Core does not drop from magma cubes even though JEI says it does.
Also suggestion: add a way to craft it when it is appropriate as I have to now sit and fish when I am already tiers above that. Or not :)

### Steps to reproduce

1. Check JEI to confirm Molten Core drops from Magma Cube.
2. Kill 300 Magma cubes with Looting VIII, Severing IX netherite sword and get 0.
3. Cry and go fishing

### Expected behaviour

Magma cubes drop Molten Core as JEI said.

### Screenshots

![image](https://user-images.githubusercontent.com/116027178/200069435-adf5e4cf-efc8-481a-9891-c0898634f733.png)

**Comment by Saereth** [comment]
Yeah unfortunately reliquary doesnt have a way for me to disable that extra info about mob drop but I'll put some kinda notice on there. I can add a recipe though as well np
