### ISSUE TITLE
[Bug]: Neutronium compressor pops out items

### ISSUE THREAD

**Issue by badf0cus** [FTBTeam/FTB-Modpack-Issues#1640]
### Modpack

Stoneblock 3

### Modpack version

1.0.0

### Describe the bug

When you put items into a neutronium compressor (manually or automatically) it wil pop out items for some reason? So its not actually able to be automated at all because lol

### Steps to reproduce

Neutronium compressor, put items in, they pop out :D 

### Expected behaviour

For the items to go in and not pop out :)

**Comment by Sh1oriko** [comment]
Same issue here, sometimes when you transfer more than a stack at a time, it just spits out items out the block.
