### ISSUE TITLE
[Bug]: Chipped connected textures buggy

### ISSUE THREAD

**Issue by hanky21** [FTBTeam/FTB-Modpack-Issues#1642]
### Modpack

Inferno

### Modpack version

1.2.1

### Describe the bug

Most Chipped connected textures flip between states depending on where you're looking

### Steps to reproduce

1. Make a chipped variant with connected textures Ex. Layered Dirt Pillar
2.  Place two blocks next to each other to connect their textures
3.  Look around slowly to see textures change states

### Expected behaviour

Connected textures should be stable

**Comment by Saereth** [comment]
does this occur with shaders off?

**Comment by hanky21** [comment]
You're right, it does seem to be a shaders conflict. Sorry I forgot to check that first!
