### ISSUE TITLE
[Suggestion]: Add something to allow for auto-smithing

### ISSUE THREAD

**Issue by Copperearth** [FTBTeam/FTB-Modpack-Issues#1644]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

I want to make a bulk amount (1000) of the Netherite Drawer Upgrades so I don't need to worry about them for the rest of my playthrough. Unfortunately, you cannot hook up a Refined Storage Crafter to a Smithing Table.
Please add another way to perform smithing automatically using a crafter.

**Comment by fimmagin** [comment]
It looks like Refined Storage is not encouraged as the end-game storage system, since one AE2 has an Infinity Range wireless terminal. As such, the fact that AE2 supports smithing table, but refined storage does not, might not be an issue.

**Comment by Copperearth** [comment]
Then why give us the illusion of choice?

**Comment by Raidobw2** [comment]
I've just been told that adding https://www.curseforge.com/minecraft/mc-mods/auto-smithing-table could be a solution to this

**Comment by Raidobw2** [comment]
Smithing crafting was recently added by AE2 in a feature update, as well as automatic stonecutting. I don't know any short terms solutions, maybe Create adds in a device that can automatically perform smithing recipes. I'll try and get in touch with the author of Refined Storage for the long term to see if they can add a feature that could allow those special crafting recipes
