### ISSUE TITLE
[Bug]: Unable to craft Red Matter Shears

### ISSUE THREAD

**Issue by Forabor** [FTBTeam/FTB-Modpack-Issues#1645]
### Modpack

FTB Stoneblock 3

### Modpack version

1

### Describe the bug

The recipe for red matter shears shows 2 diagonal mechanical crafters ( create mod ) but i can find no way or documentation on how to actually craft like this? Assume supposed to be 2 vertical.

### Steps to reproduce

Lookup recipe for red matter shears on rei

### Expected behaviour

Be able to craft red matter shears.

### Screenshots

![RedMatterShears](https://user-images.githubusercontent.com/8454481/200096949-0fc80195-b1d8-4698-9bfc-3a22bc9576af.png)

**Comment by fimmagin** [comment]
To craft something diagonal like that, you need three crafters in a . : format, with the bottom right one empty.

**Comment by Sunekaer** [comment]
Answered by fimmagin
