### ISSUE TITLE
[Suggestion]: Barrel Options in Stoneblock 3

### ISSUE THREAD

**Issue by rgdelta1973** [FTBTeam/FTB-Modpack-Issues#1646]
### Modpack

FTB Stoneblock 3

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage

Sophisticated Storage is the only 1.18 mod I know of with Barrel Options like Chests.  You guys have Iron Chests but for me Barrels are better than chests.  I hate using chests since the introduction of Barrels they are 1 slab less to make and you don't have to make room to open.  So, for me Barrels are much better than Chests.

**Comment by Sunekaer** [comment]
Sophisticated Storage / Backpacks was chosen to not be added, as it felt too overpowered.
