### ISSUE TITLE
[Bug]: Gantry Carriages Crash The Server

### ISSUE THREAD

**Issue by OblivionCreator** [FTBTeam/FTB-Modpack-Issues#1648]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.2

### Log Files

https://pastebin.com/ayefXVFW
https://pastebin.com/1BAKDWD3

### Describe the bug

Providing Rotational Force to a gantry carriage crashes the server instantly.

### Steps to reproduce

1. Create gantry shaft
2. Place Gantry Carriage on Gantry Shaft
3. Provide Rotational Speed to Gantry Shaft
4. Server Crashes

Swapping 2&3 has the same result (see attached youtube video in screenshots)

### Expected behaviour

The gantry carriage would move.

### Screenshots

https://youtu.be/97vQ3N4quPw

**Comment by Sunekaer** [comment]
Does this also happen in SP for you?
I just tested in my world and it works fine, but i also have updated mods

**Comment by OblivionCreator** [comment]
Hi - Just tested again and it does work in Singleplayer (on the same world!)

Seems to just be isolated to Multiplayer.

Test in SP and then in MP:
https://youtu.be/K2WDnPmy590

**Comment by OblivionCreator** [comment]
In case it helps, I've attached the world folder from the server to test with. Currently at 100% (4/4) crash rate whenever you either place a carriage down on a powered shaft, or power a shaft with a carriage on.

[world.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9944108/world.zip)

**Comment by Sunekaer** [comment]
Okay thanks ill test on server.
