### ISSUE TITLE
[Bug]: Missing "recipes" for botany pots

### ISSUE THREAD

**Issue by Dr69onS6mur6i** [FTBTeam/FTB-Modpack-Issues#1649]
### Modpack

Stoneblock 3

### Modpack version

1.0.2

### Describe the bug

There are no recipes to tell you what you get from things in botany pots. For example, there is nothing that tells you what you get from dark oak saplings. Or what base you need for Kelp as another example.

### Steps to reproduce

1. Go to any plant item (sappling, kelp, potato, etc.)
2. Hit U, or right click, to pull up the uses
3. Scroll across the different categories
4. See that the botany pots are not listed.

### Expected behaviour

There should be a listing for what can be used in Botany Pots and what you get from them.

**Comment by Sunekaer** [comment]
Yeah sadly nothing i can do about this, botany pots for some reason in and above 1.18 doesnt have integration for JEI/REI
