### ISSUE TITLE
[Bug]: SB3 Crash on launch

### ISSUE THREAD

**Issue by GregTheNeg** [FTBTeam/FTB-Modpack-Issues#1654]
### Modpack

FTB Stoneblock 3

### Modpack version

1.1.0

### Describe the bug

I can't start the game without my whole pc crashing, i don't know what to do and i can't find anywhere how to solve my problem. Can somebody help me? i really wanna play minecraft !

### Steps to reproduce

eeeeeeeuhh
start ftb app
click play on stoneblock3 mod pack
the launcher will open
i click start
my pc crash

### Expected behaviour

my pc crashed completely

### Screenshots

if you want i can record it

**Comment by Saereth** [comment]
Please include a crashlog
