### ISSUE TITLE
[Bug]: Error loading mobs

### ISSUE THREAD

**Issue by Vipris** [FTBTeam/FTB-Modpack-Issues#1655]
### Modpack

Stoneblock 3

### Modpack version

1.18.2

### Describe the bug

When loading up the game, it pops up with two error loading mobs for ftbsbc. Mod ftbsbc requires kubejs 1802.5.5-build.546 or above and below 1900. Mob ftbsbc requires fbtteams 1802.2.6-build.69 or above and below 1900. Currently kubejs and ftbteams are not included in the install.  

### Steps to reproduce

1. Go to https://www.curseforge.com/minecraft/mc-mods/ftb-stoneblock-companion 
2. Click the orange install button
3. Once it opens in curseforge, click create new profile
4. Go to advanced and change the forge from 40.1.0 to 40.1.14 (to resolve another error)
5. Add a name and click create
6. Press play on the pack you just created
7. After it loads up the Minecraft launcher page, click play, I agree to the risks, and play again. 

### Expected behaviour

to open up the modded game menu screen to start a new single player word

### Screenshots

![image](https://user-images.githubusercontent.com/66836430/200124361-fa2033c2-4296-4b2e-a09d-ea9252583dd5.png)

**Comment by Sunekaer** [comment]
Are you trying to play the modpack or just using the mod for your own pack?

**Comment by Vipris** [comment]
> Are you trying to play the modpack or just using the mod for your own pack?

I am trying to play the modpack but I'm not very tech savvy so i could definitely be doing something wrong. Most packs I use are already on curseforge, I just press play.

**Comment by Sunekaer** [comment]
Yeah so SB3 is not on Curseforge, so you just installed 1 mod there is used in the modpack.
You need to use our app to install the modpack [feed-the-beast.com/app](https://www.feed-the-beast.com/ftb-app)
