### ISSUE TITLE
[Bug]: Gene sample not recognized for quest completion

### ISSUE THREAD

**Issue by portega** [FTBTeam/FTB-Modpack-Issues#1656]
### Modpack

FTB Inferno

### Modpack version

1.2.1

### Describe the bug

The Vitamin Bee12 quest can not be completed as it never recognizes the genes. 

### Steps to reproduce

1. Get bee material squashing a bee (tried Iron bee)
2. Centrifuge the gene material
3. Get all the gene samples
4. Combine a treat to reach 100%
5. Quest should be completed but nothing happens

### Expected behaviour

Quest completion after getting any? gene sample

**Comment by Saereth** [comment]
yeah looks like nbt matching, should be an easy fix
