### ISSUE TITLE
[Suggestion]: Faster mining speed of dungeon spawners/ Ability to stop spawns from them with torches

### ISSUE THREAD

**Issue by TheMasterTM69** [FTBTeam/FTB-Modpack-Issues#1657]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Currently about half(maybe less) of the spawners that are in the dungeon do not stop spawning mobs or groups of mobs when lit up which sometimes makes the area "unplayable". Trying to break them takes simply too long in order to pass through.

**Comment by Sunekaer** [comment]
Which spawners are you talking about, because there is 2 vanilla spawner and bits spawner and both do get disabled by light.
Bits spawner do require you put the light on the block itself tho.

**Comment by TheMasterTM69** [comment]
I tried that and it does not work, the bits spawner will always spawn the mobs, and some vanilla spawners like silverfish also do not care if they have a light close by or on them.

**Comment by Sunekaer** [comment]
Hmmm thats weird, works for me: 
![billede](https://user-images.githubusercontent.com/18720460/200132527-e53b2c41-5c1d-4a8c-b220-826134934ed8.png)

**Comment by Raidobw2** [comment]
Note on Silverfish and some other mobs: They still follow normal Minecraft rules. For example, the Silverfish and Blaze can spawn in high light levels or in special conditions:
![image](https://user-images.githubusercontent.com/17010632/200150813-73a7b14d-b06d-4461-9308-8811977ab76c.png)
Please try what Sunekaer has done on the bits spawner and let him know if that worked or not, with a screenshot if possible and thanks.
