### ISSUE TITLE
[Suggestion]: Sophisticated Storage/ Backpacks and Tool Belt mods

### ISSUE THREAD

**Issue by Kangy1103** [FTBTeam/FTB-Modpack-Issues#1658]
### Modpack

Stoneblock 3

### Mod suggestion

I'd like to put forward the suggestion of implementing the Sophisticated Storage mod and the Sophisticated Backpacks mod
https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage
https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks

Also would like to put forward the Tool Belt mod as it's really useful when you have a lot of tools
https://www.curseforge.com/minecraft/mc-mods/tool-belt

**Comment by Sunekaer** [comment]
Duplicate of #1646
