### ISSUE TITLE
[Suggestion]: 1.2.0 FTB Inferno change log availabel on 1.2.1

### ISSUE THREAD

**Issue by Nagapito** [FTBTeam/FTB-Modpack-Issues#1659]
### Modpack

FTB Inferno

### Is your suggestion related to a problem? Please describe.

Could we get the full change log on version 1.2.1?

I am assuming that 1.2.0 has a full change log of issues but since there is a 1.2.1 hotfix and 1.2.0 ended up being removed together with the change log...

**Comment by Saereth** [comment]
yeah I'll add it to curator, but also here you go directly.

## Mod Updates
Apotheosis->5.7.6
AppliedEnergistics->11.5.0
ArsNouveau->2.8.0
Collective->5.13
Engineersdecor->1.1.26
FTBLibrary->1802.3.7
incontrol->6.0.22
kubejs->1802.5.5
Minecolonies->1.0.1086-Alpha
NamelessTrinkets->1.6.8
Placebo->6.6.6
ShetiphianCore->3.10.11
Tips->5.0.10
WarriorRage->1.0.3
FtbChunks->1802.3.7
FtbTeams->1802.2.7
Geckolib->3.0.53
InControl->6.0.23
Rhino->1802.2.1-build.248
serverconfigupdater-2.1
summoningrituals->1.1.6

## Mod Additions
Connectivity 3.2
EnchantmentRequirements 1.1.0

## Changes
- Decreased travel anchor angle targeting range to 10 from 30 to help with anchor precision when multiple anchors are in use
- Disabled beacon protection range in champions to prevent a rare CME crash
- Removed chance for reality affix on mobs to strip enchants
- Invasions no longer occur once you beat the storm
- Command block boss can no longer be a champion mob
- Witherstorm hover range lowered to 64 from 120
- Fixed Blue Nether Brick and treated planks not registering properly as path blocks
- Fixed Nylium variants to work with quarry bee
- Fixed Skystone and clay to no longer work with quarry bee
- Fixed missing Enderium recipe that was causing a progression softlock
- Fixed nbt data on the Flint pickaxe quest so it properly detects
- Blacklisted shader bags from all entities, they are now obtainable via trading and crafting
- Updated socketing quest to use new apoth socket sigisl, added conversion recipe from our old sigils
- Added item collector quest
- Creative world shaper now requires Withered Star
- Added deblockify recipes for Neutronium and Crystal Matrix blocks
- Added FTBIC chunks to colonist's Smeltery ingredient lists
- Blacklisted vengeance spirits from ITSNT to address an edge-case crash
- Fixed Harming Arrow nbt data on Fletcher trade
- Endermen heads can now be used as the flower for Ender Bees
- Added quest for multiplayer teams to explain how to create your island
- Added a new Threetronium bee that produces Neutronium!
- Added new KB Resistance Trinket as a quest reward for Formidbomb
- Added 2 creative defense modifier rewards for the T3 armor quest
- Completely revamped Withstorm phases 8-15, quest book updated with some new instructions.
- Added pack completetion lore flavor text when you defeat the storm
