### ISSUE TITLE
[Suggestion]: Remove Watch of flowing time from Gem leggings recipe

### ISSUE THREAD

**Issue by asmem-a** [FTBTeam/FTB-Modpack-Issues#1662]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Many servers have or will disable the ProjectE Watch of Flowing Time in order to maintain server stability. Gem leggings are a high quality mid game tier item and are used in Avaritia crafts. We need a way to craft the leggings that does not require the Watch of Flowing Time.

**Comment by Sunekaer** [comment]
Hello, if a server is removing/disabling an item, its up to them to make sure any recipes using it, is update to something else.
