### ISSUE TITLE
[Bug]: Server Crash on startup SB3

### ISSUE THREAD

**Issue by RebelBeast** [FTBTeam/FTB-Modpack-Issues#1663]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.2

### Describe the bug

I tried to install the server over an AMP-Panel wich resulted in the panel giving me an error for not having a minecraft_server.jar. Then I tried to install it manually (Linux Server) and there the server first loads and the continues to crash, giving me a huge error starting with the line "Exception caught during firing event: Cannot read field "playerMap" beacuse "s" is null" (Screenshot)

It also doesnt even create a crash-log, but if needed i can copy the full code given until the server crashes.
![Screenshot 2022-11-05 171903](https://user-images.githubusercontent.com/116731158/200137499-737e52e9-d537-4627-8956-cd848c8375b1.png)

### Steps to reproduce

1. Download the Linux-Serverinstall file 
2. Install the server 
3. Try to start it

### Expected behaviour

Server crashes during startup withoput creating any crash-logs

**Comment by Sunekaer** [comment]
Full log please.

**Comment by RebelBeast** [comment]
[Server SB3.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9944610/Server.SB3.txt)
Here you go, thats all i can give you.

**Comment by Sunekaer** [comment]
_The exception was: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use_
Seem you already have a server running on port 25565, either stop that server or change the port for this one

**Comment by RebelBeast** [comment]
I already tried to change the port in the server config. I tried multiple diffrent ports, got the same error every time. Could it be that the AMP-Panel is blocking all Ports for itself ?

**Comment by Sunekaer** [comment]
I dont know how  AMP-Panel works, if they have a discord, i would recommand asking on there

**Comment by RebelBeast** [comment]
OK, thanks for the help.
