### ISSUE TITLE
[Bug]: Ender Comb is unobtainable until the end is accessed.

### ISSUE THREAD

**Issue by tac-owo** [FTBTeam/FTB-Modpack-Issues#1664]
### Modpack

FTB Inferno

### Modpack version

1.2.1

### Describe the bug

The Ender Bee has no flowerable blocks attainable before reaching the end. Enderman Heads were supposed to be a flowerable block, as listed in the patch notes, but they aren't functioning. 

This also has issues with the quest book, where Ender Combs have to be acquired to complete the quest for Ender Bees, and therefore complete the quest for Amethyst/Emerald, Diamond, Silicon, Certus, and Fluix bees.

### Steps to reproduce

1. Open game
2. Put Ender Bee in hive
3. Put Enderman Head near hive
4. Watch as your ender bee floats around looking for something to do
5. Watch as your ender bee doesn't pollinate off anything
6. Watch as you receive no Ender Combs

### Expected behaviour

Ender Bees should be able to flower off of Enderman Heads

**Comment by Saereth** [comment]
they are defined as flowers for the ender bee but not recognized by productive bees so I'll have to take it up with that mod dev

**Comment by bmwalter68** [comment]
It looks like the ender bee has it's flower tags updated in code via kubejs/server_scripts/tags.js instead of via json overrides in kubejs/data/productivebees/tags/blocks/flowers/ender.json like the lumber and quarry bees.  Adding an ender.json file there with the contents:

```
{
    "replace": false,
    "values": [
        "tconstruct:enderman_head"
    ]
}
```
Seems to have fixed it for me.

**Comment by Saereth** [comment]
ty for the script, this is fixed for next update now
