### ISSUE TITLE
[Bug]: Crash when A is pressed in RS system

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#1666]
### Modpack

Stoneblock 3

### Modpack version

1.0.1

### Log Files

Crash report https://gist.github.com/tyler489/e01bb3af8f2d99f6bf92bdeebf47fdd8

### Describe the bug

When searching for "grass" in the RS system with jei sync on, as soon as the A key is pressed the game crashes to desktop.

### Steps to reproduce

See Above

### Expected behaviour

Should be obvious.

### Additional information

Will attach the log in a gist in a second.

**Comment by Sunekaer** [comment]
https://github.com/shedaniel/RoughlyEnoughItems/issues/1196

**Comment by legitswitch** [comment]
Why do you guys use REI instead of JEI?

**Comment by tyler489** [comment]
Weirdly Enough, if I disable the MineTogether mod, the crash does not happen... Might be a cross mod interaction thing?

**Comment by Sunekaer** [comment]
Should be fixed in 1.1.1
