### ISSUE TITLE
[Bug]: Auto-hammers have infinite output capacity

### ISSUE THREAD

**Issue by id-NaN** [FTBTeam/FTB-Modpack-Issues#1668]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.2

### Describe the bug

When an Aut-hammer can't output it will store the overflow in its output buffer. This buffer seems to be way to large/infinite so the output will stack up indefinitely.

### Steps to reproduce

Place an Auto-hammer, a filled input and no or a full output and look at the WAILA readout. the number of stored outputs will increase indefinitely.

### Expected behaviour

The machine should stop working after having too many items in its output buffer

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/48955787/200146183-f818ed35-e840-4d61-ae9d-77299cf4271f.png)

### Additional information

This behaviour makes it impossible to make a simple chain of hammers to get all resources at once

**Comment by Sunekaer** [comment]
Hi it's not infinite, it's 4096
