### ISSUE TITLE
[Bug]: Copper nugget from Chickens and Functional Storage

### ISSUE THREAD

**Issue by dittymargoo** [FTBTeam/FTB-Modpack-Issues#1669]
### Modpack

Stoneblock 3

### Modpack version

1.0.2

### Log Files

This is not a crash so I don't think the log files are necessary.

### Describe the bug

I'm not sure if this is a bug or not.  Copper Chicken lays copper nuggets from Create that will not go into a Functional Storage compacting drawer if there is already an ingot in it (no nuggets) - nor does a nugget appear for a copper ingot.  However, if you take everything out of the drawer and then try again with the nugget first then it will show.  I've attached screenshots.

I'm loving this pack, so thank you all for the hard work.

### Steps to reproduce

1. Compacting drawer empty.
2. Put in a copper ingot - nugget does not display and you can't put nuggets in
3. Take everything out of the drawer and put a nugget in first.
4. Now is will display and further ingots or nugget can be put in.

### Expected behaviour

Either a nugget or ingot should display the same way.

### Screenshots

![2022-11-06_13 42 57](https://user-images.githubusercontent.com/55962902/200148943-35741605-0840-4a26-b2fd-afd66b8b6504.png)
![2022-11-06_13 28 34](https://user-images.githubusercontent.com/55962902/200148944-31d3aff7-ca55-4a33-9097-eaa0c1b752d6.png)

### Additional information

I don't thing my screenshots pasted in about...clearly I don't know what I'm doing wrong.

**Comment by Sunekaer** [comment]
https://github.com/Buuz135/FunctionalStorage/issues/119

**Comment by Sunekaer** [comment]
Should be solved in the newest version of the pack
