### ISSUE TITLE
[Suggestion]: Replace REI with JEI

### ISSUE THREAD

**Issue by InFuRiTy** [FTBTeam/FTB-Modpack-Issues#1671]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

REI is acting weird and/or is buggy

1. Weird and annoying render of the search bar (in whatever position) that makes big item tooltips in hotbar/inventory hard to read.
![2022-11-03_02 31 08](https://user-images.githubusercontent.com/95109357/200149522-15fa473f-41fa-4b8f-a25f-23ea0f0b11ba.png)

2. Custom UI weirdness/interference/obstruction of their functions with REI overlays.
![2022-11-06_03 19 44](https://user-images.githubusercontent.com/95109357/200149588-d8087447-bdca-49b2-9bd7-b773d7018843.png)
![2022-11-06_03 19 24](https://user-images.githubusercontent.com/95109357/200149591-d8673ff9-c536-45f0-938c-08394cb80cfb.png)
 3. Many recipes are broken/don't show up while they are craftable
 4. Many mechanics such as dripper conversion recipes, botany pots accepted crops/soils and their stats, machines like the mekanism crystallizer not showing lithium processing, are not showing up  or have to search specifically for an item that's dependent or created by those.
 5. The utility icons (FTB teams - chunks, quests and trash can) can be deleted just like any other fav entry, that can potentially break the game/progression/gameplay for players.

### Mod suggestion

JEI is more stable in terms of functionality, features and extras (addons + plugins)

**Comment by Sunekaer** [comment]
We will not replace the REI with JEI, tho we can forward the feedback.
1. ill forward it
2. ill forward it
3. report to me which ones isnt, as this could be on my and have nothing to do with REI
4. Dripper works in my world so screens and log file thanks, Botany doesnt work because the mod doesnt have a plugin wouldnt even work with JEI.... Lithium is fixed in dev.. your blaming REI on a lot of things here there isnt them..
5. Dev is aware but there is been more important things to fix.

**Comment by Kangy1103** [comment]
@InFuRiTy I agree with your grumbles about REI but it really ain't a bad replacement for JEI if you take a few minutes to go through it's options. For points 1 and 2 you can go into the options of REI and tweak those as I've done. I moved the search bar to the right and reduced the column sizes so they didn't take up so much space.
<img width="1911" alt="image" src="https://user-images.githubusercontent.com/42292756/200167612-ab4ccf81-1793-4b7f-ac5f-61f8919c3a86.png">
Looks much cleaner after making the said adjustments.

@Sunekaer I have a suggestion for point 5, might it be worth adding a line or 2 into the starting quests just to make people aware of the button to add or remove the utility icons until the REI dev gets round to it?

**Comment by InFuRiTy** [comment]
@Sunekaer
I just offered a suggestion based on many peoples' opinion and my own, from my community we play in.
I'm used to play on default settings since it's less hustle when an update resets everything every time (auto scale UI, search bar in the middle, etc.)
it just feels punishing for not following specific playstyles. (small scales, search bar somewhere else)
everything should work as intended no matter the player's preferences

as for the feedback you guys asked:

hidden/broken recipes are many, but i can't remember all of them rn, in the pack i have found these so far:
a few blocks from thermal series like the hive hopper, Mekanism's basic induction cells which also connect to the lithium issue mentioned before.

The thing i meant with broken REI mechanics is that if i click uses on the dripper it does have a tab with it's uses on the blocks it converts BUT if i click recipes on eg. Clay block it doesn't show up the dripper tab so the only way to check a recipe origin that's dripper dependent is to click uses on the dripper and then cycle through all of its available recipes manually to see if its there.
 it happened on another block as well i just can't remember it rn.

About the botany pots issue, it would help tremendously  if you could add a reward less quest in, like a list with everything available for them, like soil types and their stats etc. i know it's much to ask, im just throwing the idea in there just in case you know a person or 2 who are willing to take the time to do it!!!

about the logs you asked i just compressed the entire log folder and sent it here, the more info you have, the better you can try and solve/understand the issues!!!
[Entire log folder.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9946422/Entire.log.folder.zip)

OH im playing on v1.0.2 btw!!

**Comment by InFuRiTy** [comment]
OK update post.

i reinstalled the pack and the REI mechanics issue i mentioned seems to be fixed, it now shows the dripper uses if i click R on a block that supports it. so im guessing it was another borky install by the looks of it.
i apologize for the trouble on this one.

**Comment by Raidobw2** [comment]
In what you mentioned, I believe Sunekaer is aware of:
- Items that still need hiding in REI, like the Hive Hopper https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1583. Some mods add items or blocks that don't have a use, so we need to hide them manually
- Induction cell https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1623
- Botany Pots was handled at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1556 and the mod got the feature added thanks to its author

Things that could be checked
- That bedrock might be Blood Magic's own recipe look/custom for the pack
- Obstruction of the bookmarks when the furnace UI is out on the left

**Comment by InFuRiTy** [comment]
Good to hear that things getting addressed!!!
I apologize if my responses gave you any "jerk" vibes!!

If you think this post is redundant or not serving a purpose anymore since the majority of things in here are getting patched/fixed you can close it.

Keep up the awesome work, I'm really enjoying  the pack so far!!!

**Comment by phit** [comment]
another thing thats really annoying the U and R hotkeys break quite often when in the AE2 terminal having to reopen the GUI for them to work again happens basically after every time you used the AE2 search
