### ISSUE TITLE
[Bug]: Rendering Overlay bug

### ISSUE THREAD

**Issue by Kitsuzen** [FTBTeam/FTB-Modpack-Issues#1674]
### Modpack

Stoneblock 3

### Modpack version

1.0.2

### Log Files

[crash-2022-11-05_23.33.05-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9945156/crash-2022-11-05_23.33.05-client.txt)

### Describe the bug

Can't load into Stoneblock 3 Mod Pack. Only loaded up once out of 10 times. Crashes after loading into the Mojang screen.

### Steps to reproduce

1. Play on modpack
2. Crash after some loading

### Expected behaviour

Open the launcher and play the game.

**Comment by Raidobw2** [comment]
Try removing the MineTogether mod until the next update, we know of the issue and MineTogether has now released a fix in version 6.0.9+

**Comment by Sunekaer** [comment]
Should be fixed in 1.1.0

**Comment by Kitsuzen** [comment]
I downloaded Stoneblock 3 as a premade modpack. Not sure if I can alter which mods are on there. Is there an eta for 1.1.0 that you know of? Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
