### ISSUE TITLE
[Bug]: REI issues when loading into world/Crashing game

### ISSUE THREAD

**Issue by Ghostsnow15** [FTBTeam/FTB-Modpack-Issues#1675]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.2

### Log Files

[crash-2022-11-06_00.38.22-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9945168/crash-2022-11-06_00.38.22-client.txt)
[crash-2022-11-06_00.24.42-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9945169/crash-2022-11-06_00.24.42-client.txt)

### Describe the bug

Have had multiple issues with REI not loading on startup.
REI loading with broken textures or missing textures.
When attempting to click a recipe from REI into crafting grid game freezes and crashes.
My entire screen UI began to bug out and either not show or load with missing textures.
Every time I have loaded into the game testing this the REI search bar displays a message that REI hasn't finished loading. It seems to finish but takes a minute. After the REI list is loaded there is an issue searching and then this crash seems to reoccur.

### Steps to reproduce

1. Load into world
2. Wait for REI to finish loading
3. Try clicking recipe into crafting grid using REI
4. Game Crashes

### Expected behaviour

Replace REI with JEI or fix issues.

**Comment by Raidobw2** [comment]
Hmm, this looks similar to https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1541. Do you perhaps have a Tinker's Construct Crafting Station next to a Stone Chest? If yes, remove the Crafting Station and replace it with a Crafting Bench to see if all the issues are resolved to allow you to continue playing
