### ISSUE TITLE
[Bug]: Crash au lancement de stoneblock 3

### ISSUE THREAD

**Issue by Kyomashi** [FTBTeam/FTB-Modpack-Issues#1679]
### Modpack

FTB  StoneBlock 3

### Modpack version

1.0.2

### Log Files

[crash-2022-11-06_09.03.11-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9945385/crash-2022-11-06_09.03.11-client.txt)

### Describe the bug

Quand je lance stone block 3 le modpack de lance normalement, puis il crash avec un crash-report
(When I start StoneBlock 3, the modpack launches normally, then it crashes with a crash-report)

### Steps to reproduce

Ouvrir FTB App
Cliquer sur Play FTB StoneBlock3
Ligne de code
Crash

(Open FTB App)
(Click on Play FTB StoneBlock 3)
(Line of code)
(Crash)

### Expected behaviour

Le jeu se lance normalement et ne crash pas
(The game starts normally and does not crash)

**Comment by Kyomashi** [comment]
![Capture d’écran 2022-11-06 094210](https://user-images.githubusercontent.com/88081471/200161815-0448698f-7804-44a2-bea0-2f026b25cb9a.png)

**Comment by Raidobw2** [comment]
Salut, c'est un bogue qu'on a découvert avec l'équipe du mod MineTogether and ça empêche de lancer le jeu correctement. Pour y remédier, tu vas devoir supprimer le fichier de mod de MineTogether du dossier `mods`, qui se situe à l'intérieur des fichiers du jeu et ce jusqu'à la prochaine mise à jour du modpack.

Sur la page du modpack, tu peux cliquer sur les '...' pour accéder aux fichiers du jeu de l'instance (Instance folder) ou bien directement dans le dossier `mods` (Mods folder).

Laisse-moi savoir si ça fonctionne bien après ça!

--------

TLDR: Remove MineTogether from the `mods` folder until next update

**Comment by Kyomashi** [comment]
Merci j'ai supprimer Minetogether et ça fonctionne

**Comment by RaphaelJenni** [comment]
Removing MineTogether didn't fix the problem for me. According to the crash report, it has something to do with the ftbbackups mod. 
Removing this one results in a different crash upon connecting to the server. 
```
Cannot invoke "net.coderbot.iris.pipeline.WorldRenderingPipeline.setPhase(net.coderbot.iris.pipeline.WorldRenderingPhase)" because "this.pipeline" is null
```
