### ISSUE TITLE
[Bug, MineTogether]: CreeperHost Spamvertisement Returns after dismissal upon pack reload

### ISSUE THREAD

**Issue by SephirothWS** [FTBTeam/FTB-Modpack-Issues#168]
### Modpack

FTB OceanBlock

### Modpack version

1.4.1

### Log Files

N/A

### Describe the bug

CreeperHost Spamvertisement in Multiplayer Menu returns after having been dismissed when the pack reloads.

### Steps to reproduce

1. Launch the modpack.
2. Click on Multiplayer.
3. Click the X on the CreeperHost spamvertisement pinned to the top of the multiplayer menu
4. Watch as the spamvertisement disappears.
5. Return to main menu.
6. Click on Multiplayer again
7. Watch as the spamvertisement is still dismissed.
8. Close the pack.
9. Relaunch.
10. Click on Multiplayer.
11. Observe as the spamvertisment has returned.
12. ???
13. Cry as you realize spamvertisements are forced upon users.

### Expected behaviour

Dismissing the spamvertisement is REMEMBERED across separate play sessions and should NOT return after reloading the pack

### Screenshots

![Image](https://i.imgur.com/88f54SV.png)

**Comment by Raidobw2** [comment]
Fixed in `minetogether-1.16.5-5.0.5-forge.jar`, available now
