### ISSUE TITLE
[Bug]: Stoneblock 3 Random crashes

### ISSUE THREAD

**Issue by moosetwin0** [FTBTeam/FTB-Modpack-Issues#1680]
### Modpack

Stoneblock 3

### Modpack version

1.0.2

### Log Files

https://pste.ch/cagonetano.sql

### Describe the bug

Game freezes for a few seconds, and then crashes - time before the crash varies

### Steps to reproduce

Open a world, play for a bit, crash

### Expected behaviour

The game will crash

**Comment by Raidobw2** [comment]
Hmm could be linked to https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1601.
Can you try removing the Emojiful mod?

If the game crashes again, make sure to post your `latest.log` here again, it's useful to us!

**Comment by moosetwin0** [comment]
I will try that!

**Comment by moosetwin0** [comment]
Removing the Emojiful mod seems to have worked.
