### ISSUE TITLE
[Bug]: Crash on Launch

### ISSUE THREAD

**Issue by Zankage** [FTBTeam/FTB-Modpack-Issues#1681]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.2

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9945535/latest.log)

### Describe the bug

Game does not start, same issue every time. Worked fine 11 hours ago, did not change anything.

### Steps to reproduce

Open FTB App
Launch Stoneblock 3

### Expected behaviour

Game starts up normaly

### Screenshots

![image](https://user-images.githubusercontent.com/117568358/200163874-00747aa3-a768-46db-a9c4-8a3055ef7140.png)

**Comment by Raidobw2** [comment]
Looks like the Thermal configuration is damaged, you could try repairing the instance by downgrading and updating it again.

Upon clicking the modpack tile, you'll be able to click versions. From there choose another version, hit Downgrade. Once it finishes, click Update again. Let me know if that worked.

P.S. That should not mess with your world, but you can take a copy of it anyways before doing this if you want. The `saves` folder is what is important

**Comment by Zankage** [comment]
Thank you, that fixed it. And it did indeed not mess with the world.
Sunday is saved ^-^
