### ISSUE TITLE
[Bug]: Can't make mekasuit armor, no recipe for basic induction cells

### ISSUE THREAD

**Issue by Awkweat** [FTBTeam/FTB-Modpack-Issues#1684]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.2

### Describe the bug

You can't make the mekasuit armor because you can't make the basic induction cells. I'm sorry if there is an alternative way of getting the cells, but I can't find any way so far.

### Steps to reproduce

.

### Expected behaviour

.

### Screenshots

.

### Additional information

.

**Comment by Sunekaer** [comment]
fixed in 1.1.0
