### ISSUE TITLE
[Bug]: Startup Crash

### ISSUE THREAD

**Issue by renandestefani** [FTBTeam/FTB-Modpack-Issues#1685]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.2

### Log Files

[crash-2022-11-06_11.40.26-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9946099/crash-2022-11-06_11.40.26-client.txt)

### Describe the bug

Played yesterday normally and today while trying to launch getting crashed with no changes.

### Steps to reproduce

1. Click to play
2. Crashes

### Expected behaviour

Game launching to menu

### Additional information

Only thing I changed was the amount of memory allocated in the app, from 6Gb to 8Gb. Tried changing back but still crashing.

**Comment by renandestefani** [comment]
Fixed by removing minetogether from the mods folder (Problem seems to be the same as in version 1.0.1)

**Comment by Sunekaer** [comment]
Should be fixed in 1.1.0
