### ISSUE TITLE
[Bug]: Loot Bee not despawning (Stoneblock 3)

### ISSUE THREAD

**Issue by ShyNieke** [FTBTeam/FTB-Modpack-Issues#1686]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.2

### Describe the bug

I have an loot bee that has decided to live with my by not de-spawning after I fell to my death and going back to world spawn, my guess is that it should have de-spawned while I was at world spawn but since the chunks where unloaded it didn't and is now my friend forever

### Steps to reproduce

1. have a loot bee spawn
2. Die (maybe unload the chunks as I went back to world spawn)
3. go back to your base
4. infinite glowing bee! yay (doesn't seem to generate more loot)

### Expected behaviour

De-spawning loot bee

**Comment by Raidobw2** [comment]
That might be difficult to fix, I think the bee despawns on a timer. If you miss the timer, you get to keep the bee :) Maybe Sunekaer sees a way to solve this so I'll mark it as enhancement, since it's not game breaking

**Comment by Sunekaer** [comment]
So the bee doesnt naturally have a despawn timer so i cant use that, so i have to run everything on scheduled ticks which means if it gets unloaded like here then i cant do much about it

**Comment by ariosos** [comment]
This also happens if you close and reopen the save when a loot bee is around.

**Comment by osirisgothra** [comment]
There is also an issue when you have beehives that are empty, the loot bee either joines, or just sits in its hole and never despawns, I have had up to 20 bees in random places just because I was using beehives for honey.
