### ISSUE TITLE
[Bug]: Mushrooms can no longer spawn/be planted on Bedrock/Nether Roof

### ISSUE THREAD

**Issue by Novasiri** [FTBTeam/FTB-Modpack-Issues#1689]
### Modpack

FTB Inferno

### Modpack version

1.2.1

### Describe the bug

Just started a new world for a Hardcore playthrough and noticed that there were no mushrooms spawning on the roof reguardless of how far I went out. So Instead I attempted to 'plant' some from quests onto the roof, as I've done before, to get some growing early on.

However, the mushrooms can not be placed on bedrock, Blackstone OR Netherrack, unlike prior. Only on Dirt, Rich Soil, Organic Compost, Warped/Crimson Nylium and Mycelium.

![image](https://user-images.githubusercontent.com/78075114/200184398-23f212a2-13c0-428c-8279-742bb14dbbca.png)

So either it's a bug, or the in-game tooltip needs to be changed to no-longer claim you can get mushrooms by exploring the roof.

![image](https://user-images.githubusercontent.com/78075114/200184446-deb37c53-c3a1-46ad-b836-b1455b4e28fa.png)

### Steps to reproduce

1. Start a new world in 1.2.1
2. Look for mushrooms on the roof.
3. Find none.
4. Try to plant some for early food.
5. Can't plant them unless on special soils.

### Expected behaviour

Being able to place mushrooms on bedrock.

### Additional information

The bedrock in my screenshots is purely visual from vanilla tweaks. I've disabled it and nothing changes. Mushrooms simply can not appear on the roof as of 1.2.1

**Comment by Saereth** [comment]
yeah they dont spawn all over anymore but the structure you start with now contains both varieties to get you started making more, will remove the tip

**Comment by Novasiri** [comment]
Sounds good!
