### ISSUE TITLE
[Bug]: Crashing when Searchin in REI

### ISSUE THREAD

**Issue by fxceptioN** [FTBTeam/FTB-Modpack-Issues#1691]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.2

### Log Files

https://paste.ee/p/10EAy

### Describe the bug

It typically happens when I search for a recipe in REI

### Steps to reproduce

1. Open REI
2. search mod
3. hover over an item. <-- this is typically when it freezes and crashes

### Expected behaviour

not crash.

### Screenshots

![image](https://user-images.githubusercontent.com/16984021/200187723-eef9d1c8-042a-4a16-8317-7160aded60b3.png)

### Additional information

Typically when hovering over an item like I did in screenshot above, it wouldn't show the item name in the pop up, it would just freeze and save world and crash instance.

**Comment by Anzulo1984** [comment]
Maybe related to this?
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40

**Comment by Raidobw2** [comment]
Can you try the workaround at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1601#issuecomment-1305464061?

**Comment by Sunekaer** [comment]
Please test if fixed in 1.1.1

**Comment by fxceptioN** [comment]
I haven't experienced any crashes yet, I've updated to the latest as of today.

**Comment by Raidobw2** [comment]
I'll close this in that case, if it happens again you can comment here and we'll reopen the ticket. For now, with what you said we'll assume it's fixed!
