### ISSUE TITLE
[Bug]: Crash when using /ftbstoneblock prune command

### ISSUE THREAD

**Issue by Plutosion** [FTBTeam/FTB-Modpack-Issues#1692]
### Modpack

FTB StoneBlock 3

### Modpack version

1.0.2

### Describe the bug

When typing in the command /ftbstoneblock prune and then typing a space after, the game will crash

### Steps to reproduce

1. Type /ftbstoneblock prune
2. Press space
3. Crash

### Expected behaviour

No crash

**Comment by Sunekaer** [comment]
Fixed in 1.1.0
