### ISSUE TITLE
[Suggestion]: Some kind of Iron Barrels type mod for Stoneblock 3

### ISSUE THREAD

**Issue by rgdelta1973** [FTBTeam/FTB-Modpack-Issues#1693]
### Modpack

FTB Stoneblock 3

### Mod suggestion

I suggested a mod you guys consider overpowered and that is ok but I hate there is no barrel's version of Iron Chests in this mod.  Since the introduction of barrels, I think they are better than chests and I hate using chests anymore.  Most modpacks have some kind of barrel version of Iron Chests.

**Comment by rgdelta1973** [comment]
Doing a bit of a search Reinforced Barrels https://www.curseforge.com/minecraft/mc-mods/reinforced-barrels

**Comment by Sunekaer** [comment]
Thats a Fabric mod, but i see what you suggesting and ill find something that is for Forge
