### ISSUE TITLE
[Suggestion]: Allow ultimine with open hand for leaves

### ISSUE THREAD

**Issue by OneComputerGuy** [FTBTeam/FTB-Modpack-Issues#1694]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Given that the pack doesn't have fast decay to clear up trees when farming for wood (before entering into the chicken's mod), it would be good if ultimine is enabled to clear leaves without a tool (specially for early game) having to use a tool to break it slows tree farming since durability is consumed faster for stone/early tools.

Crooks are a way to clear them, but the durability of the only one available makes it impossible to clear a tree with a single crook, forcing the player to use more than one clogging the inventory

**Comment by Sunekaer** [comment]
Hi
Thanks for the suggestion, but we will not be changing this.
