### ISSUE TITLE
[Bug]: Cooking Slag has 2 outcomes

### ISSUE THREAD

**Issue by Skokushel** [FTBTeam/FTB-Modpack-Issues#1695]
### Modpack

FTB Plexiglass Mountain

### Modpack version

Beta 1.2

### Describe the bug

Cooking slag in a redstone rurnace from Thermal makes slag glass while cooking in a Minecraft furnace makes rockwool. Recipie book suggest slag in Thermal furnace makes rockwool.

### Steps to reproduce

Put Slag from using gravel in a furnace into a furnace or a Thermal Expansion furnace

### Expected behaviour

didn't think recipie book would decieve me XD

**Comment by Raidobw2** [comment]
Hmm. I'll look into it and improve the way you can craft rockwool or slag glass, thanks for reporting

**Comment by Anzulo1984** [comment]
Same Bug in FTB StoneBlock3

Bulk Burning has rock wool and slag glas as same outcome, there aren't other recipes

**Comment by Raidobw2** [comment]
I've moved the Rockwool recipe to the Induction Smelter instead. This will be fixed in the next version of Plexiglass Mountain, which should be out today.
![image](https://user-images.githubusercontent.com/17010632/200503237-897409aa-3898-4434-b052-225a9bffa672.png)


with KubeJS Thermal:
```
//Rockwool moved to Induction Smelter
    event.remove({ id: 'thermal:rockwool/white_rockwool_from_smelting' })
    event.remove({ id: 'thermal:rockwool/white_rockwool_from_blasting' })
//Rockwool
  event.recipes.thermal.smelter('thermal:white_rockwool', 'thermal:slag')
```

**Comment by Raidobw2** [comment]
Pleave leave this open, we still need to fix this in StoneBlock 3 as well :)
