### ISSUE TITLE
[Bug]: Rich Soil slows down crop growth in Botany pots to 0.1% 

### ISSUE THREAD

**Issue by PeggyPenguin** [FTBTeam/FTB-Modpack-Issues#1700]
### Modpack

FTB StoneBlock 3

### Modpack version

1.1.0 Beta

### Describe the bug

Rich Soil from Farmers Delight make crop growth take forever. 

### Steps to reproduce

1. Make Rich Soil
2. put rich soil in botany pot
3. wait an eternity for your plant to grow

### Expected behaviour

to speed up crop growth

### Screenshots

![image](https://user-images.githubusercontent.com/30187575/200194921-091923ff-3c1b-451d-b55c-5562eac85a6a.png)

**Comment by InFuRiTy** [comment]
I can confirm this happens in 1.0.2 as well because i tried using it for it's supposed sped up growth in a pot.

**Comment by Firedale** [comment]
Just a note to add, and possibly what caused the issue.
Multipliers in Bonzai were time-based.  If something normally took 10 minutes, a multiplier of 0.5 would make it take 5 minutes.
eOn the other hand, multipliers in Botany Pots are speed-based, making it the inverse of time-based.  If something takes 10 minutes, a multiplier of 0.5 would make it take 20 minutes (1/2x speed, 2x time).
