### ISSUE TITLE
[Suggestion]: AE2 things cell's

### ISSUE THREAD

**Issue by tjd46** [FTBTeam/FTB-Modpack-Issues#1702]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Add the AE2 things cell's to count for the Item storage quest.

**Comment by Sunekaer** [comment]
Thanks for the suggestion, but i have decided to not add this mod

**Comment by tjd46** [comment]
The mod is already in the pack I was just suggesting to add the cell types they provide to that quest.
