### ISSUE TITLE
[Suggestion]: Add Simply Jetpacks

### ISSUE THREAD

**Issue by PianoHallvard** [FTBTeam/FTB-Modpack-Issues#1708]
### Modpack

StoneBlock 3

### Is your suggestion related to a problem? Please describe.

I mean, title says it all XD

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/simply-jetpacks-2

**Comment by Sunekaer** [comment]
Hi 
Thanks for the suggestion, but i have decided to not add Simply Jetpacks
