### ISSUE TITLE
[Bug]: Cant launch Stoneblock3 server on linux

### ISSUE THREAD

**Issue by dobbleg1000** [FTBTeam/FTB-Modpack-Issues#1712]
### Modpack

FTB Stoneblock 3 

### Modpack version

1.0.2

### Describe the bug

cant load server

### Steps to reproduce

download server on ubuntu 
try to run

### Expected behaviour

server opens

**Comment by dobbleg1000** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9947436/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9947437/debug.log)

**Comment by Sunekaer** [comment]
Does this also happen on 1.1.0?

**Comment by dobbleg1000** [comment]
For some reason my server wouldn't bind to my nic unless I specified up. Setting that in server.properties fixed jt
