### ISSUE TITLE
Chipped stalactite cause ticking world

### ISSUE THREAD

**Issue by evilspacebunny** [FTBTeam/FTB-Modpack-Issues#1713]
### Modpack

FTB Stone Block 3

### Modpack version

1.0.2

### Log Files

https://pastebin.com/vpQDNVCC

### Describe the bug

One of my members put down some Nether Stalactite from chipped. Every time they would grow they would crash the server. 

### Steps to reproduce

1. Get chipped Stalactite 
2. Put on celling
3. Crash after a few minutes

### Expected behaviour

They had a farm set up with them they would be the same size every time the server rebooted then crash

**Comment by Sunekaer** [comment]
https://github.com/terrarium-earth/Chipped/issues/161

**Comment by Sunekaer** [comment]
Should be solved on the newest version of the pack
