### ISSUE TITLE
[Suggestion]: RS and AE2 addons

### ISSUE THREAD

**Issue by Shikamaji** [FTBTeam/FTB-Modpack-Issues#1715]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

I already saw the post #1599, but since you added "AE2things" for bigger drives Refined Storage users like me still have to use 64k drives, which is a pain, i first higly suggest the "MEGA Cells" mod instead of AE2 things, that does the same thing expect for few items but also add a small drive to store radioactive Mekanism gasses on AE2, also supports Applied Mekanistics too.
For RS bigger disks there is the Extra Storage addon, which i think is very needed so we don't have to fill the entire base of RS crafter which has only 9 slots, and for the more powerful importers, i had to put 6 importers with 1 stack and 3 speed upgrades each to handle the items, those mods will be a big improvement in my opinion, there is also Extra Disks instead, but it adds only the bigger disks for item and fluids

### Mod suggestion

MEGA Cells (AE2)
https://www.curseforge.com/minecraft/mc-mods/mega-cells
Extra Disks (RS)
https://www.curseforge.com/minecraft/mc-mods/extra-disks
Extra Storage (RS)
https://www.curseforge.com/minecraft/mc-mods/extrastorage

**Comment by LWmods** [comment]
id love to see extra storage at least. the crafter by default is so tiny and tedious needing to have a massive wall of them.

**Comment by DAmNRelentless** [comment]
AE2 Things doesn't add bigger drives and it is completely unrelated to MEGA Cells.

AE2 Things adds new item storages called DISKs. They have the same size as the vanilla AE2 cells but have no type limitation. The MEGA cells still have a type limitation but add higher tiers of storage capacity (so they are like the vanilla AE cells).

It's not like you can swap the mods and have the same result. They are very different and can also be used together.

**Comment by Sunekaer** [comment]
Thanks for the suggestion but i have decided these mods wont be added
