### ISSUE TITLE
[Suggestion]: Easier lava egg extraction

### ISSUE THREAD

**Issue by crazymachinefan** [FTBTeam/FTB-Modpack-Issues#1717]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Currently, the only to produce lava en masse (at least early game) is lava eggs from the Chickens mod. However, they're super annoying to use. They can't be cracked directly into tanks (mod issue) and the only way to extract lava automatically is by either dispensing them into the world and pumping it up or with a bucket in a mixer via shapeless crafting. This is an annoying and roundabout way of doing it.
My proposed solution is also in a mixer, but just have a 1 egg->1b lava recipe, as the mixer supports both items and liquids and inputs and outputs. It also kinda makes sense, using the whisk to crack the egg open.
Alternatively, an item drain could work, but I don't know how well as the fluid eggs aren't technically containers as far as I can tell.
These suggestions also apply to the water eggs.

**Comment by hvdklauw** [comment]
Small mineral smelter from engineers decor can create lava

**Comment by Clonephaze** [comment]
You can use a deployer (Create) on top of a small fluid collection funnel (Engineer's Decor). The fluid funnel will automatically collect the lava from above itself, then pump the lava out of the funnel with some kind of pipe into a tank.
