### ISSUE TITLE
[Bug]:  StoneBlock3 - Modpack Crashing on Recipe for AE2 Singularity.

### ISSUE THREAD

**Issue by UrAvgProGamer** [FTBTeam/FTB-Modpack-Issues#1719]
### Modpack

FTB StoneBlock 3

### Modpack version

1.1.0

### Describe the bug

When trying to see the recipe for the AE2 using REI, the modpack kind of crashes (It says saving the game and then closes instead of like completely freezing)

### Steps to reproduce

Just left-click the ae2 singularity in REI or press R to see it.

### Expected behaviour

The Recipe of the singularity should open.

**Comment by RuneZhevitz** [comment]
I ran across the same issue, so I can provide logs instead. I think AE2's REI integration is either cruddy or out of date - 
[crash-2022-11-08_16.17.12-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9962065/crash-2022-11-08_16.17.12-client.txt)

**Comment by Sunekaer** [comment]
[ #1201](https://github.com/shedaniel/RoughlyEnoughItems/issues/1201)

**Comment by Sunekaer** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6765
