### ISSUE TITLE
[Bug]: Eidolon Lead Use

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#172]
### Modpack

Ftb University 

### Modpack version

1.2.0

### Describe the bug

The recipe attached requires Eidolon Lead (theres no way to get this), and it doesn't use normal lead.

### Steps to reproduce

1.) try and craft the mind shielding plate

### Expected behaviour

To craft

### Screenshots

![image](https://user-images.githubusercontent.com/44754456/138446098-78db2628-4b4f-4fd9-a3f2-33faac6ce4d2.png)

**Comment by zoller27osu** [comment]
The recipe for Eidolon Lead seems to be present in modpack version 1.3.
I assume this task is open for the "better fix"?

**Comment by aaronhowser1** [comment]
Honestly I may have just forgotten to close it lol
