### ISSUE TITLE
[Bug]: AutoSmithingTable related server crash on map load

### ISSUE THREAD

**Issue by Copperearth** [FTBTeam/FTB-Modpack-Issues#1723]
### Modpack

FTB Stoneblock 3

### Modpack version

1.1.0

### Log Files

https://pste.ch/utizozerac.pl

### Describe the bug

My sever no longer starts as it crashes nearly instantly upon loading the map. It seems like this crash is related to the autosmithing table. I had hooked it up the night before, but hadn't configured any recipes for it yet. 

### Steps to reproduce

1. Launch Server
2. Place AutoSmithingTable
3. Wait
4. Profit?
5. Realize you can no longer start the server as it will crash instantly upon trying to load the map

### Expected behaviour

For the server not to crash upon attempting to load the map

### Additional information

Java version 17.0.3.1 LTS

**Comment by Copperearth** [comment]
i have more crashlogs if needed. they look practically identical.

**Comment by Copperearth** [comment]
I have managed to find a workaround to be able to continue playing. I have removed the autosmithingtable from the server's mods. Now the map loads once more

**Comment by wrincewind** [comment]
i found i was able to launch by editing forge-server.toml so that 'remove erroring tile-entities' was true. it didn't actually remove the smithing table however, which was a little odd.

**Comment by MisterSoandSo** [comment]
Similar issue in regard the auto smithing table. Apparently, it doesn't like hoppers piping into auto smithing  table
https://pste.ch/uzoxagodez.pl
