### ISSUE TITLE
[Bug]: SB3 - Pipez do not stay connected to entangled blocks after entering the world again

### ISSUE THREAD

**Issue by TheMasterTM69** [FTBTeam/FTB-Modpack-Issues#1724]
### Modpack

Stoneblock 3

### Modpack version

1.1.0 / 1.0.1

### Describe the bug

For some reason when a pipe from Pipez mod is connected to an entangled block it works just fine but when you exit the world and join back in the connection breaks and voids the upgrade on the pipe (if there was any)

### Steps to reproduce

1. Connect pipe to entangled block
2. Exit world
3. Load world
4. Observe pipe connection

### Expected behaviour

Pipe does not disconnect, keeps upgrade (and filters)

### Screenshots

![2022-11-07_12 18 53](https://user-images.githubusercontent.com/75620187/200298796-88230cca-f31d-444b-b25a-0c0d182f6e02.png)
![2022-11-07_12 21 05](https://user-images.githubusercontent.com/75620187/200298816-8c872e58-fe68-4976-8d8b-52ce0e8527c1.png)

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
