### ISSUE TITLE
[Bug]: Crash when searching "Auto" in REI

### ISSUE THREAD

**Issue by louisferdi** [FTBTeam/FTB-Modpack-Issues#1725]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9951118/latest.log)

### Describe the bug

Minecraft crashes when searching inside REI

### Steps to reproduce

1.Go to Inventory
2.Search anything that contains "Auto"
3.Minecraft crashes

### Expected behaviour

no crash

### Additional information

there might be other search tags that can cause a crash but im not sure

**Comment by louisferdi** [comment]
forgot the crash log itself (oops)
sorry
[crash-2022-11-07_18.33.01-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9951249/crash-2022-11-07_18.33.01-client.txt)

**Comment by Sunekaer** [comment]
Duplicate of #1666
