### ISSUE TITLE
[Bug]: Soils and their effects in Botany Pots are strangely configured

### ISSUE THREAD

**Issue by iammael** [FTBTeam/FTB-Modpack-Issues#1727]
### Modpack

FTB Stoneblock 3

### Modpack version

1.1.0

### Describe the bug

Thanks to the recent addition of the Botany Pots' JEI integration, we can now see that it is possible to use different soil in the pots. But they seem to be configured in the opposite way.

Let's take the seed as an example:

1. Soil used : Dirt. 
Grow Time: 1 minute.

![image](https://user-images.githubusercontent.com/7931135/200305134-f9c8c89f-ea60-4962-8b7a-dcd7f25d1cb4.png)

2. Soil used : Farmer's Delight's Rich Soil. 
Grow Time: 10 minutes (x10).

![image](https://user-images.githubusercontent.com/7931135/200305469-3047aaf0-6dce-4ec9-ae00-797b99453a42.png)

For all seeds that I checked (seed, sugar cane, saplings), the best soil is Dirt while all the other soils takes longer to grow.

### Steps to reproduce

Self-explanatory.

### Expected behaviour

Better soils in Pots should result in faster yields.

**Comment by hvdklauw** [comment]
Yeah, I think the logic got swapped, maybe it shoulkd be 10 times as fast?

**Comment by InFuRiTy** [comment]
What's the point in getting them then if dirt is the optimal?
speed modifiers should be sm like this:
Dirt: x1
Grass Block: x1.5/x2
Rich soil: at least a x5
etc.

**Comment by iammael** [comment]
> What's the point in getting them then if dirt is the optimal?

That's the point of this issue. Dirt being the optimal is the current behaviour but it shouldn't.

**Comment by Sunekaer** [comment]
Please make an issue at https://github.com/Darkhax-Minecraft/BotanyPots/issues
