### ISSUE TITLE
[Bug]: kubejs's errors in StoneBlock3

### ISSUE THREAD

**Issue by KuroPeach** [FTBTeam/FTB-Modpack-Issues#1729]
### Modpack

FTB StoneBlock3

### Modpack version

1.1.0

### Log Files

[13:06:18] [ERR  ] Error occurred while handling scheduled event callback: Wrapped java.lang.NullPointerException: Cannot invoke "dev.latvian.mods.rhino.SharedContextData.getExtraProperty(String)" because "cx.sharedContextData" is null (server_scripts:_core/inworldevent/utils.js#36)
[17:17:44] [ERR  ] Error occurred while handling scheduled event callback: Wrapped java.lang.NullPointerException: Cannot invoke "dev.latvian.mods.rhino.SharedContextData.getExtraProperty(String)" because "cx.sharedContextData" is null (server_scripts:_core/inworldevent/utils.js#36)

### Describe the bug

kubejs's errors Appears when the player joins the server again. 
Also, the js that strengthens dungeon monsters does not take effect(kubejs/server_scripts/_core/harderdungeons.js), but when the champions-ranks.toml is modified, it will take effect, but it has to be modified every time the server is started.

### Steps to reproduce

1. joins the server
2. leave the server
3. joins the server again, Sometimes it will appear, but it will be recorded in the diary when the server starts.

### Expected behaviour

_don't be rude please_

**Comment by Sunekaer** [comment]
Hmm something seems to not have started correctly, does this still happen after a server restart?

**Comment by KuroPeach** [comment]
yep, it usually happens when the player login the server again

**Comment by Sunekaer** [comment]
full log?

**Comment by KuroPeach** [comment]
This is the record after I use reload. You can see the error at the end, but there is no error in the game chat bar. 
[server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9953936/server.txt)
latest.log里还没有触发，我在11.02日的记录里找到了，line1629
[2022-11-02-2.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9954089/2022-11-02-2.log)

**Comment by Sunekaer** [comment]
I can see you have modified the pack, please test if this happens with the full default version of the pack.

**Comment by ukmcplyr** [comment]
FWIW I'm also seeing this on an unmodified 1.0.2 server.

**Comment by KuroPeach** [comment]
This can't be done because the server has been running for a long time, and we just replaced rei with jei and added the rei server version, which shouldn't be a problem, And the above UKMCPLYR has not been modified and this problem has also occurred. : )

**Comment by KuroPeach** [comment]
I guess the line 39 40, block should not be abbreviated as b
![image](https://user-images.githubusercontent.com/19620848/200504016-6f4ca949-2b03-4891-95d8-72b58b17bc1c.png)

**Comment by Xplodin** [comment]
just got this error randomly with 1.2.0

**Comment by Saereth** [comment]
> I hollowed out the dungeon, and I can observe the moment when the elite monsters are refreshed and then disappeared. The end of this script may be cancelling the generation of elites, not the original monsters ![image](https://user-images.githubusercontent.com/19620848/200345963-89250ec5-2a85-4ce5-bef3-a0c1333a65fe.png)

this script first rolls la d100, if it rolls higher than the chance for the spawning entity to become a champion, it returns and spawning happens normally. If the makes the check, it makes a champion mob and then cancels the original spawn event

**Comment by KuroPeach** [comment]
> > I hollowed out the dungeon, and I can observe the moment when the elite monsters are refreshed and then disappeared. The end of this script may be cancelling the generation of elites, not the original monsters ![image](https://user-images.githubusercontent.com/19620848/200345963-89250ec5-2a85-4ce5-bef3-a0c1333a65fe.png)
> 
> this script first rolls a d100, if it rolls higher than the chance for the spawning entity to become a champion, it returns and spawning happens normally. If the makes the check, it makes a champion mob and then cancels the original spawn event
> 
> This is not even anywhere remotely where the error is pointing to either (server_scripts:_core/inworldevent/utils.js#36), did you have some other error log pointing to this code? @KuroPeach

These are two questions, unrelated. For some reason, the elite monster disappears after being refreshed, which makes them very rare. According to the script, there should be 15%~25%, but they are basically invisible.
![image](https://user-images.githubusercontent.com/19620848/201239885-26380dd9-8037-453c-81a2-4ad3a719785a.png)
But after I give them a random chance of 1%, the 15%~25% set by the script can take effect.

**Comment by KuroPeach** [comment]
And the slimes and its various variants that need to be blacklisted, they will split large into medium, and then medium has a chance to split into large (elite)，endless ：）@Saereth

**Comment by Raidobw2** [comment]
Sunekaer ^ the way the scripts spawn them via `/summon` makes this a problem for slimes & magma cubes.

KuroPeach I have not been able to reproduce this in a test instance... For me, monsters inside the boundary of the stone dungeon for example, will convert 15% of the time into champions (blue particles). Mobs from spawners also work for this.

Does this happen in singleplayer as well, with a fresh non modified instance from the FTB App?

**Comment by Sunekaer** [comment]
Lat is working on fixing the sharedContextData issue, until thats fixed we cant see if there is a real issue with the boss script which there shouldnt be

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
