### ISSUE TITLE
[Bug]:  Blob of death

### ISSUE THREAD

**Issue by SpankyOnur** [FTBTeam/FTB-Modpack-Issues#173]
### Modpack

FTB Oceanblock

### Modpack version

Every? but at the moment latest beta 1.4.1

### Describe the bug

Giant blob of monsters which dosent despawn only after a restart.
This bug appeared 3 times within the last hours and this really kills this modpack for me ...

### Steps to reproduce

1. Mobfarm with Blessed/Blursed/Cursed earth and a "Mob Masher"
2. Let it farm for a while
3. See a giant blob of immortal mobs inside your mobfarm
4. Go near it
5. "Integrated" Server (Singleplayer) dosent respond and "Save and Quit" takes like 30min - never
6. Wait cause you dont want to lose all of the progress you just did
7. ???
8. Profit

### Expected behaviour

Responding Client/Server

**Comment by Sunekaer** [comment]
Hey,

So i wouldn't really call this a mod issue more a player issue of they need to take care of their farms.
