### ISSUE TITLE
[Bug]: Soul sand on create bulk blasting doesn't work while REI says it should work

### ISSUE THREAD

**Issue by hvdklauw** [FTBTeam/FTB-Modpack-Issues#1730]
### Modpack

Stoneblock 3

### Modpack version

1.1.0

### Describe the bug

Trying to get Vile dust which according to REI can be done with bulk blasting (lava and a fan) from create.

But the blasting doesn't work, and the attribute filter for soul sand also doesn't show it as can be blasted.

### Steps to reproduce

Throw soul sand in front of a blasting fan

### Expected behaviour

The soul sand to turn into vile dust

**Comment by hvdklauw** [comment]
Same with soul soil actually..

**Comment by Clonephaze** [comment]
Soul sand is not reproduced with lava in front of a fan, as you have described in your post. Soul sand is created by blowing a fan in front of a soul fire or soul campfire. A soul fire is made by lighting a piece of soul sand on fire. To get your first piece of soul sand, look at the mixer recipe in REI for soul sand.

**Comment by Sunekaer** [comment]
Hmm it works for me
![billede](https://user-images.githubusercontent.com/18720460/200588195-813bb6db-fff8-4ad2-9a0c-fb1c1920d68d.png)

Whats your setup? how long did you leave it?

**Comment by hvdklauw** [comment]
Maybe the issue is that the brass filter let it though then, let me test again

**Comment by hvdklauw** [comment]
Yeah ok, weird... it's hard to make a filter that does exactly what you want (prevent things that can be smelted, blasted except normal stone) :)
