### ISSUE TITLE
[Bug]: Updating Modular Storage Module causes crash when inserting and locking to see inventory

### ISSUE THREAD

**Issue by sLpFhaWK** [FTBTeam/FTB-Modpack-Issues#1731]
### Modpack

FTB Stoneblock 3

### Modpack version

1.1.0

### Describe the bug

I was updating my Tier 3 storage module to Tier 4, I unlock the storage to remove tier 3, craft tier 4, insert tier 4 game locks and kicks you off the server with an error I didn't get a screen shot of. logged back in, tier 4 card sitting in the world, was able to pick up and insert and lock with my inventory still intact.

### Steps to reproduce

I was updating my Tier 3 storage module to Tier 4, I unlock the storage to remove tier 3, craft tier 4, insert tier 4 game locks and kicks you off the server with an error I didn't get a screen shot of. logged back in, tier 4 card sitting in the world, was able to pick up and insert and lock with my inventory still intact.

### Expected behaviour

Should lock storage and give you access to your inventory

**Comment by Sunekaer** [comment]
crash log?

**Comment by sLpFhaWK** [comment]
I don’t have one

**Comment by Sunekaer** [comment]
Im not able to recreate this issue, so i need your log file from when this happened, else i cant forward it to the mod dev

**Comment by sLpFhaWK** [comment]
it just happened again. 
![error mc sb3](https://user-images.githubusercontent.com/18454563/201109149-1b9f74a3-f364-4a5e-a95c-d81867f95c0e.png)

where do I get the log, server side or client side?

**Comment by Sunekaer** [comment]
Both logs would be help full, latest.log from both

**Comment by sLpFhaWK** [comment]
ive restarted so the recent logs won't work, but here is what ihave.

**Comment by Sunekaer** [comment]
Should be fixed, in 1.3.0
