### ISSUE TITLE
[Suggestion]: Smart-Chicken

### ISSUE THREAD

**Issue by LordDose** [FTBTeam/FTB-Modpack-Issues#1732]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

From The Mod Chickens the Smart-Chicken is not Craftable, i suggest that the chicken is maybe craftable in the next Update. And maybe some more Chickens

### Mod suggestion
Angles Rings maybe

_No response_

**Comment by InFuRiTy** [comment]
You can get the Smart chicken if you use a book on it!

also +1 for the angel rings

**Comment by Sunekaer** [comment]
_You can get the Smart chicken if you use a book on it!_
