### ISSUE TITLE
[Bug/Need Help]: Cannot launch Stoneblock 3 on Linux (Steam Deck)

### ISSUE THREAD

**Issue by Deoxys0** [FTBTeam/FTB-Modpack-Issues#1733]
### Modpack

Stoneblock 3

### Modpack version

1.1.0

### Log Files

Prism launcher's log: https://logpaste.com/3bJfKm5s

### Describe the bug

So I'm trying to setup Stoneblock 3 on my steam deck (linux). Originally I tried to use the official FTB launcher but I could not get it to install on linux and gave up after many failed troubleshooting attempts. I then switched to Prism Launcher (https://prismlauncher.org/) and this installed perfectly and had FTB modpack support. However, trying to launch the modpack will result in a failure to launch with exit status 1. I'm not familiar with debugging minecraft modpacks so I'm hoping I can get some help here. I posted the launch logs in the log files section.

I'm aware that launching via Prism MAYBE why this is failing, however as I am currently unable to install the official FTB launcher, I don't have much of a choice. I will reconsider trying the official launcher again if and only if the issue can be confirmed to be the prism launcher itself.

### Steps to reproduce

1. Launch the modpack...
2. Crash

### Expected behaviour

The modpack should launch

### Additional information

I'm using Java version 19.

**Comment by Sunekaer** [comment]
This crashes extremely early, try with Java 17

**Comment by Deoxys0** [comment]
> This crashes extremely early, try with Java 17

I'll try this (although I can't right this moment but as soon as I do I'll update you), thanks.

**Comment by Deoxys0** [comment]
So switching to java 17 seems to have fixed the problem, but the entire modpack itself is taking about 20 minutes to launch. However, I think this is a steam deck specific issue and not something with the modpack, so I'll move to steam deck support stuff. Thanks for the help though!
