### ISSUE TITLE
Special Lanterns in Stoneblock 3 not craftable [Bug]: 

### ISSUE THREAD

**Issue by GennieLightdust** [FTBTeam/FTB-Modpack-Issues#1736]
### Modpack

FTB Stone Block 3

### Modpack version

1.01

### Describe the bug

There are two types of lanterns that can be crafted in the Chipped Mod. One is based off the vanilla lantern and the other are 4 "special lanterns". JEI is not reflecting recipe for the 4 special lanterns except as a round robin chain within the tinker's bench.

### Steps to reproduce

1. Go to JEI and type in lantern
2. Look at the collapsed menu for "Special Lantern" its the one with 4 large lanterns
3. click on recipe; shows only round robin in the tinker bench.

### Expected behaviour

I expected a recipe for the lanterns

**Comment by Sunekaer** [comment]
https://github.com/terrarium-earth/Chipped/issues/160

**Comment by Sunekaer** [comment]
Should be fixed in newest version of the pack
