### ISSUE TITLE
[Suggestion]: ME Requester

### ISSUE THREAD

**Issue by DAmNRelentless** [FTBTeam/FTB-Modpack-Issues#1739]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

The ME Requester adds an easy way to keep items and fluids in your ME system in stock. While there are methods to keep things in stock in vanilla AE2, the ME Requester is able to request specific batch sizes which causes less stress for the server and also allows for more stocking than just a stack per slot.

There is also a custom terminal in the mod that lets you manage your stocked resources in a central position.

**Alternative:**<br>
The requester was previously (before 1.19) a part of LazierAE2. A mod that was never really up for discussion in FTB packs, as it would make various aspects of AE2 too easy. You can think that just by looking at the name. But LazierAE2 connects to the progression of AE2, not replaces it. This is already reflected in the recipes. It is made for the endgame of AE2 and for huge ME networks to remove some grindyness and make automation more server-friendly.

For 1.19+ the requester has been decoupled from LazierAE2 but for 1.18 you can choose which of the two mods you take. In any case, one of the two mods would be good to have the requester.

### Mod suggestion

Either this to only have the requester with a central terminal:
https://www.curseforge.com/minecraft/mc-mods/merequester

Or this which includes the requester and some other handy stuff for endgame AE2:
https://www.curseforge.com/minecraft/mc-mods/lazierae2

**Comment by Sunekaer** [comment]
Thanks for the suggestion but you can already do this with the buildin tools in AE

**Comment by DAmNRelentless** [comment]
Yes, I mentioned this in the issue. The built-in tools would be level emitters and interfaces. The problem with that is that it doesn't scale very well. You can only stock up to a stack and it's also quite stressful on the server because a level emitter will emit its signal as long as the stock threshold isn't reached and the system will request each craft 1 by 1. The requester can do bulk operations and also allows you to manage the stocking requests from a central position via the terminal.

Refined Storage also has built-in tools to set up stocking but you still added Refined Storage Requestify so what's the reason to not have the same for AE2?

**Comment by DAmNRelentless** [comment]
@Sunekaer if it's your final say, that's alright but please reconsider it. I even talked to one of the AE devs about it who is currently playing your pack 😅

![](https://i.imgur.com/wmLlr79.png)
![](https://i.imgur.com/PoWsa8f.png)
