### ISSUE TITLE
[Bug, CBMultipart]: RFTools Crafter and CBMicroblock Diamond Saw

### ISSUE THREAD

**Issue by Moonhead0811** [FTBTeam/FTB-Modpack-Issues#174]
### Modpack

FTB OceanBlock

### Modpack version

1.4.1

### Describe the bug

Whilst using the RFTools tier 1 crafter to craft Silicon from ProjectRed Core I noticed the diamond saw from CBmicroblock has infinite durability.

The crafter is set up to import diamond saw and silicon boule from Refined Storage with the silicon being extported back in to the storage and the diamond saw staying in the input buffer of the crafter

### Steps to reproduce

import diamond saw and silicon boule to crafter
set the output method to ExtC so the saw stays in input buffer
keep input silicon boule

### Expected behaviour

Diamond saw should be destroyed when durability runs out

### Screenshots

![Crafter](https://user-images.githubusercontent.com/92990020/138457411-82306c25-52ee-4349-a54a-eba98ff2e3ef.png)

**Comment by Raidobw2** [comment]
Fix available with `CB Multipart 1.16.5-3.0.3.122-universal` on CurseForge.
