### ISSUE TITLE
[Bug]:  SB3 1.1.0 Crash to Desktop - Out of Range

### ISSUE THREAD

**Issue by MisterSoandSo** [FTBTeam/FTB-Modpack-Issues#1740]
### Modpack

StoneBlock 3

### Modpack version

1.1.0

### Log Files

https://pastebin.com/3t7TTuiQ

### Describe the bug

The bug that I've encountered seems to occur when REI tries to look an items usage. It doesn't find any usages for the item and crashes directly to desktop. At the moment, it seems like any item/block usage("u") from Enderstorage mod ( ender chest/ ender tank) will crash directly to desktop. The bug was prevalent since V1.0.0. It seems like REI is trying to find any usage for the Enderstorage items/blocks and goes out bounds thus crashing the client. It should do nothing if it can't find anything.

### Steps to reproduce

Go into REI on a server
1. Look up any item from the EnderStorage Mod.
2. Hover the item in REI and press "U"
3. Client will initiate shutdown of game client
4. Crashed onto desktop.

### Expected behaviour

It should  try open a menu of usages for the item but should do nothing because the item shouldn't have any other usages

**Comment by Raidobw2** [comment]
Thanks for reporting! The issue has been initially reported at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1574, so I'll keep only that one opened for us to track. I suggest you subscribe to the other issue, that way you can get information when this is being worked on
