### ISSUE TITLE
[Bug]: Minetogether friend opens world but can't see it on muliplayer

### ISSUE THREAD

**Issue by FTWCougar** [FTBTeam/FTB-Modpack-Issues#1743]
### Modpack

FTB StoneBlock 3

### Modpack version

1.1.0

### Describe the bug

minetogether friend opens world cant see it on muliplayer

### Steps to reproduce

minetogether friend opens world
cant see it on muliplayer

### Expected behaviour

opens world to friend friend joins

**Comment by Raidobw2** [comment]
Thanks for reporting, I've asked the MineTogether team for some help on this. I'll get back to you soon

**Comment by Sunekaer** [comment]
Should be fixed
