### ISSUE TITLE
[Suggestion]: Botany Pot tags

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#1744]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

It would be nice if you could see what soils work for plants inside the botany pot, for instance, Moss says it is a valid soil, but does not work for saplings. It would also be nice if you could see the soils growth modifier like in older versions.

**Comment by Sunekaer** [comment]
You can in version 1.1.0 and above of the pack.
