### ISSUE TITLE
[Bug]: Chicken Hitbox is Full sized 

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#1746]
### Modpack

Stoneblock 3

### Modpack version

1.1.0

### Describe the bug

Chickens' Chickens have a Massive 1.8 tall block hitbox, as opposed to vanilla's chickens 

### Steps to reproduce

Turn on hitboxes

### Expected behaviour

Have an appropriate sized hitbox 

### Screenshots

![2022-11-07_16 24 42](https://user-images.githubusercontent.com/7015040/200428949-b55c7563-251e-4eaa-9eb4-5368fc0117c6.png)

**Comment by Raidobw2** [comment]
Thanks a lot for the report and forwarding this to the mod developers as well!
