### ISSUE TITLE
[Bug]: Extreme Crafting Table Duping

### ISSUE THREAD

**Issue by phit** [FTBTeam/FTB-Modpack-Issues#1747]
### Modpack

Stoneblock 3

### Modpack version

1.0.2

### Describe the bug

The extreme crafting table is being extremely weird when crafting, sometimes duping and creating stacks larger than 64.

### Steps to reproduce

Craft anything with the extreme crafting table. Observe the items in the input.

### Expected behaviour

No duping and weird stack sizes.

### Screenshots

this shows the duping of some end stone in the bottom right its really quick, sorry I didn't record earlier, I originally only had enough stacks in there for 16 endest pearls, I crafted those and the table then looked empty. after clicking in some empty looking slots it gave me items, I kept clicking and moving the items around, somehow I ended up with more neutronium ingots and all the other stuff after the craft than I had before! https://phit.link/s/javaw_2022-11-07_23-14-42.webm

here's a more general video of the weird stack sizes when crafting, haven't been able to reproduce the duping again just yet 
https://phit.link/s/javaw_2022-11-07_23-18-10.webm

and no this is not some client server desync, those items are really there and I could take them out reopen the table etc

**Comment by phit** [comment]
Update: managed to reproduce the dupe again https://phit.link/s/javaw_2022-11-07_23-37-09.webm

**Comment by Avakining** [comment]
This bug seems to be back in version 1.4.3
