### ISSUE TITLE
[Bug]: Game Crash 

### ISSUE THREAD

**Issue by ZakMatheus** [FTBTeam/FTB-Modpack-Issues#1750]
### Modpack

FTB Stoneblock 3

### Modpack version

1.1.0

### Describe the bug

When you click a source gem from ARS NOUVEAU while using wirelles crafting grid the game crashes 

### Steps to reproduce

Open wireless crafting grid
Click on source gem 
Crash

### Expected behaviour

Crash everytime 

### Screenshots

a

**Comment by Raidobw2** [comment]
Likely the same error as https://github.com/shedaniel/RoughlyEnoughItems/issues/1196, can you check if updating to 1.1.1 fixes this?

Otherwise, make sure to add your game log! This helps us a lot in identifying the problem. Thanks!

**Comment by Sunekaer** [comment]
Fixed in 1.1.1, if you still having issues, please report and provide logs
