### ISSUE TITLE
[Bug]: Singularity quest missing

### ISSUE THREAD

**Issue by Dmprisioned** [FTBTeam/FTB-Modpack-Issues#1752]
### Modpack

FTB StoneBlock 3

### Modpack version

1.1.0

### Describe the bug

Just updated server to 1.1.0 on mcprohosting.com and singularity quest are all bugged out

### Steps to reproduce

Go to mcprohosting.com 
Create a server on 1.0.2 update to 1.1.0 
Check quests

### Expected behaviour

Missing quest items

**Comment by Sunekaer** [comment]
Works fine when testing with just our server installer, so sounds like an issue on mcprohosting side, please report to them
