### ISSUE TITLE
[Bug]: Mekanism Basic Induction Cell not craftable

### ISSUE THREAD

**Issue by HappyBigFun** [FTBTeam/FTB-Modpack-Issues#1753]
### Modpack

FTB StoneBlock 3

Latest Beta

### Describe the bug

Basic Induction Cell is not craftable in Stoneblock 3. Advanced+ tiers _are_ craftable and require the basic induction cells.

Possible hint: According to the Mekanism wiki, this cell requires **lithium dust** from a chemical crystallizer, but it does not appear in that machine's list of possible outputs.

### Steps to reproduce

1. Search for Basic Induction Cell in REI
2. Click it

### Expected behaviour

Basic induction cell should be craftable (or entire induction matrix removed)

**Comment by Raidobw2** [comment]
This should have been fixed in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1623. Which "latest beta" are you using? Can you try updating to 1.1.1 and seeing if the recipe appears? Thanks!

**Comment by Sunekaer** [comment]
Fixed in  1.1.0

**Comment by HappyBigFun** [comment]
You are correct. I did update and make sure 1.1 was choosen, but when I deleted the whole Stoneblock 3 instance yesterday and re-downloaded it, it worked as expected. Thank you.
