### ISSUE TITLE
[Bug]: Putting a Tuba into a bundle crashes the game

### ISSUE THREAD

**Issue by PapaZ810** [FTBTeam/FTB-Modpack-Issues#1755]
### Modpack

FTB StoneBlock 3

### Modpack version

1.1.0

### Log Files

https://pastebin.com/DPKu4Djh

### Describe the bug

I tried to put a tuba into a bundle by right clicking the bundle onto the tuba and my game hard crashed.

### Steps to reproduce

1. Get a bundle
2. Right click it onto a tuba(may have to have other items in it before you click on the tuba, mine did)
3. Game crashes

### Expected behaviour

I expected the tuba to either go into the bundle or for it to just stay in the inventory.

**Comment by tyler489** [comment]
Do you have a crash report? That log does not mention a crash at all.

**Comment by PapaZ810** [comment]
I do not unfortunately. I think the launcher was closed or had another window open so it didn't give me a crash report.

**Comment by Sunekaer** [comment]
Ill remove it from quest rewards.
