### ISSUE TITLE
[Bug]:Chat is Crashing Game

### ISSUE THREAD

**Issue by GodPyro** [FTBTeam/FTB-Modpack-Issues#1756]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.1

### Describe the bug

Whenever i am on a server with my friends and i go to open in-game chat or use a command my game freezes then i go to the saving world screen, after that my game crashes 

### Steps to reproduce

im sorry i dont know how to recreate this as i am the only one that i know of that this is happening to

### Expected behaviour

just try figure out how i or your self's can fix this issue as it is really annoying

**Comment by Sunekaer** [comment]
Fixed in 1.1.0
