### ISSUE TITLE
Silverfish voiding weapons

### ISSUE THREAD

**Issue by aAndrew3030** [FTBTeam/FTB-Modpack-Issues#1757]
### Modpack

FTB Stoneblock 3

### Modpack version

1.1.0

### Describe the bug

When fighting the silverfish boss, the little silverfish take your weapons, but upon killing them, the weapons are voided. I am guessing that is a bug and not intended behavior? 

### Steps to reproduce

-

### Expected behaviour

-

**Comment by Raidobw2** [comment]
May I also ask which weapon/tool you were using to fight the silverfish when you lost it?

**Comment by aAndrew3030** [comment]
I was using all vanilla swords and tools to fight it, but I think the issue would happen regardless of what the item is.
Also, this was in SP, and I will try to get a log file (not currently at my gaming pc)

I went back and fought this thing several times to try and figure out what is happening. Killing the silverfish drops the item as expected. The issue seems to only happen when the small silverfish despawn while holding the item. I suspect one of the performance mods is responsible for despawning the silverfish if to many of them spawn? This is especially a problem if you die or the chunks are unloaded for whatever reason. 

Complicating this is that a large number of silverfish are spawning with Champion mod buffs, making it near impossible to kill 100+ of them, with no weapons, in a small area (to keep chunks loaded?), without getting insta killed, while avoiding the negative potion effects, but also not being able to move due to potion effects, but then dying and returning in a few seconds, only to see the mobs have despawned likely because to many of them spawned or the chunk was unloaded?

**Comment by aAndrew3030** [comment]
To add insult to injury, my current fight, the large silverfish boss has burrowed himself into a tunnel (since he can break blocks) and since hundreds of the small buffed silverfish take my weapons upon entering the tunnel, there is no way of killing it without using a kill command. I could make weapons all day long, but all I am doing is feeding it more weapons...

**Comment by Sunekaer** [comment]
https://github.com/baileyholl/mother-silverfish/issues/1
