### ISSUE TITLE
Crash on server restart

### ISSUE THREAD

**Issue by PABessero** [FTBTeam/FTB-Modpack-Issues#1758]
### Modpack

FTB Stoneblock 3

### Modpack version

1.1.0

### Log Files

https://pastebin.com/DQFEAH3p
[crash-2022-11-07_09.17.38-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9958881/crash-2022-11-07_09.17.38-server.txt)
[crash-2022-11-07_09.25.52-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9958882/crash-2022-11-07_09.25.52-server.txt)

### Describe the bug

The target blocks from CC:C Bridge crash the server with a 'Ticking Tile Entity' error.
Removing them via Forge's config then makes the server crash upon interaction with the computer linked to the target block.

Removing the block manually does stop the error

Restart was after updating from 1.0.2 to 1.1.0

### Steps to reproduce

1. Link a target block to a computer
2. Link a train station to the target block
3. Link at least one tunnel to the target block
4. Restart server

### Expected behaviour

No crash on startup

### Additional information

Issue should be fixed in CC:C 1.3.1 (see issue tweaked-programs/cccbridge#11)

**Comment by Raidobw2** [comment]
The mod "CC: C Bridge" could now be updated to v1.3.1 https://www.curseforge.com/minecraft/mc-mods/cccbridge/files/4072918

Thanks a lot for taking care of the report to the author of the mod!
