### ISSUE TITLE
[Bug]:  Ultimine crash on FTB OceanBlock

### ISSUE THREAD

**Issue by demethan** [FTBTeam/FTB-Modpack-Issues#176]
### Modpack

FTB Ocenblock

### Modpack version

1.4.1

### Log Files

https://pste.ch/vayakujibu.rb

### Describe the bug

Get kicked out of the server when trying to use the ultimine binded key.   Mining without the ultimine binded key, ultimines the block type you are mining. . 

### Steps to reproduce

1.login to server
2. hold ultimine binded key
3. get kicked out.

1.login to server
2.mine some block
3.huge chunk of blocks got mined. 

### Expected behaviour

I think you know, its FTB's mod.  :)

**Comment by Sunekaer** [comment]
From reading this, it seems to have been fixed?
If not let me know and ill reopen the issue.
