### ISSUE TITLE
[Bug]: RFTools' Charged Porter UI usability

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#1763]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.2

### Describe the bug

Due to the lengthy dimension name displayed in the Charged Porter's UI, only two characters of the Matter Receiver's name are shown and, once you have a handful or more set up, confusion/hilarity ensues...

GUI scale doesn't make a difference.

### Steps to reproduce

1. Set up Matter Receiver, give it name, link to it etc.
2. Open up the Charged Porter UI

### Expected behaviour

More than two characters of target name shown

### Screenshots

![Screenshot](https://gcdnb.pbrd.co/images/xNCk0dRsvTDE.png?o=1)

**Comment by Sunekaer** [comment]
https://github.com/McJtyMods/RFToolsUtility/issues/159

**Comment by Sunekaer** [comment]
Should be fixed in newest version of the pack
