### ISSUE TITLE
[Bug]: REI Quick Craft puts Fishing Rod in crafting grid instead of Turbine Vent

### ISSUE THREAD

**Issue by LAGZZ25** [FTBTeam/FTB-Modpack-Issues#1767]
### Modpack

Stoneblock 3

### Modpack version

1.1.0

### Describe the bug

basically when i ctrl + clicked turbine vent recipe to crafting grid it gave me a fishing rod recipe instead its repeatable

### Steps to reproduce

1. search Turbine Vent
2. Press CTRL + Click on Turbine Vent to move it towards crafting grid 
3. Displays wrong Recipe 

### Expected behaviour

i expected it to give me the right recipe 

### Screenshots

https://user-images.githubusercontent.com/17010632/201021204-be6ef633-881d-4994-ba26-ffc55be8092d.mp4

**Comment by Sunekaer** [comment]
I have opened an issue with the moddev so they can look at it. 
https://github.com/shedaniel/RoughlyEnoughItems/issues/1210

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
