### ISSUE TITLE
[Bug]: Game crash at launch

### ISSUE THREAD

**Issue by ph1823** [FTBTeam/FTB-Modpack-Issues#1768]
### Modpack

FTB Stone block 3

### Modpack version

1.1.0

### Log Files

Crash report: 
https://hastebin.com/vecelafeli.rb

Console logs:
https://hastebin.com/eqofuduwim.yaml

Debug log:
Too big to upload on hastebin or pastebin
### Describe the bug

Game crash at launch

### Steps to reproduce

1. Update to 1.1.0
2. Game crash

### Expected behaviour

Game launch and no crash

**Comment by xSvenHD** [comment]
Having same issue here on 1.2.0, instance worked fine before. Now it won't start anymore.

**Comment by hugoprudente** [comment]
I got a workaround working, removing the jar for Minetogether solves my issue.

**Comment by Sunekaer** [comment]
https://github.com/CreeperHost/MineTogether/issues/660

**Comment by Sunekaer** [comment]
Should be fixed in 1.3.0
