### ISSUE TITLE
[Bug]: Crash when opening Transmutation table

### ISSUE THREAD

**Issue by F69Y** [FTBTeam/FTB-Modpack-Issues#1772]
### Modpack

StoneBlock 3

### Modpack version

1.2.0

### Describe the bug

me and my friend seems to be having a problem where when i started to make loads of emc my game would just crash when i opened the transmutation table.

### Steps to reproduce

.

### Expected behaviour

Not to crash i guess

### Screenshots

Only screenshot i could provide would be on it not responding

**Comment by Sunekaer** [comment]
Crash log?

**Comment by F69Y** [comment]
it didnt "crash" but it was not respondign for over 5 minutes, so i just alt + f4. By the way this never happens to me

**Comment by Copperearth** [comment]
> it didnt "crash" but it was not respondign for over 5 minutes, so i just alt + f4. By the way this never happens to me
check your instance's files. a crashlog may still have appeared in the "crash-reports" folder

**Comment by Sunekaer** [comment]
Okay then the latest log from the log folder from when the issue happened

**Comment by Raidobw2** [comment]
Linked with https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1710

**Comment by Raidobw2** [comment]
Can you also add how much EMC you have?
