### ISSUE TITLE
[Bug]: Tome of knowledge causes game to freeze

### ISSUE THREAD

**Issue by Sh1oriko** [FTBTeam/FTB-Modpack-Issues#1776]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

Games freezes when putting tome of knowledge in the emc table.

### Steps to reproduce

Put Tome Of Knowledge in an emc table.

### Expected behaviour

Not freeze the game.

**Comment by Sunekaer** [comment]
Can you please send over you latest.log from when this happens?

**Comment by Sh1oriko** [comment]
> Can you please send over you latest.log from when this happens?

Hey, sorry for late reply, here it is.
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9984971/latest.log)

**Comment by Sunekaer** [comment]
This looks to be a fresh log and not from when the issue happened?

**Comment by Sh1oriko** [comment]
How would you want me to provide the log? My game freezes but doesn't crash.

**Comment by Sunekaer** [comment]
Im not able to recreate this issue, but i also i have a very powerful pc.
I would recommend opening an issue on https://github.com/sinkillerj/ProjectE/issues so they can debug it with you
