### ISSUE TITLE
[Bug]: FTB STONEBLOCK 3 - Gravestones /restore command not working.

### ISSUE THREAD

**Issue by PixelParallax** [FTBTeam/FTB-Modpack-Issues#1778]
### Modpack

FTB Stoneblock 3 

### Modpack version

<=1.1.0

### Describe the bug

When you try and use the /restore command from the gravestones mod it never works. My best guess is because there are two other /restore commands and they conflict with eachother.

### Steps to reproduce

1. Player Dies with items.
2. use /restore <player> <death_id> <add|replace>. 
3. Throws "too many arguments" Even though it's correct. 

### Expected behaviour

The items from the grave is supposed to go back into the player's inventory. 

### Screenshots

![image](https://user-images.githubusercontent.com/26911654/200722581-ead6dca4-6179-426c-b9a3-f6aa40ad8ac6.png)
![image](https://user-images.githubusercontent.com/26911654/200722669-6f732bd9-3eeb-4269-88b8-0fad0150af76.png)
![image](https://user-images.githubusercontent.com/26911654/200722693-d84e39b1-ef3e-46a1-88e0-e2aa5dc094b6.png)

### Additional information

Only other solution is by editing nbt.

**Comment by Sunekaer** [comment]
Hmmm worked in my testing.
do you have the log from when this happened? 
So then we can open an issue with the mod dev and they can see if they know whats wrong

**Comment by Sunekaer** [comment]
Can you test if that way works @PixelParallax

**Comment by PixelParallax** [comment]
I'll give it a try tonight.

**Comment by PixelParallax** [comment]
![image](https://user-images.githubusercontent.com/26911654/202616762-73e57975-e9ef-4584-b8c6-e0d76922be8c.png)

Didn't seem to work for me.

**Comment by tyler489** [comment]
I do not believe that @S needs to be there.

**Comment by Dns-q** [comment]
Its not working due worldedit. Its restore from snapshot command overlaps

**Comment by PixelParallax** [comment]
Sounds good. I'll be sure to remove WE then.
