### ISSUE TITLE
[Bug]: Stoneblock 3 crash and don't open anymore on 1.1.1 and 1.2.0

### ISSUE THREAD

**Issue by hugoprudente** [FTBTeam/FTB-Modpack-Issues#1779]
### Modpack

Stoneblock 3

### Modpack version

1.1.1 & 1.2.0 

### Log Files

1.1.1 https://pste.ch/ipacumoyaq.rb
1.2.0 https://pste.ch/onohadolic.rb

Console Log

1.2.0 https://pste.ch/dopewekocu.md

Debug Log.
1.2.0 https://pste.ch/ajawonagiy.md

### Describe the bug

Restarted the game and now it doesn't open anymore

### Steps to reproduce

I just restarted the app. 

### Expected behaviour

Game to open.

**Comment by hugoprudente** [comment]
It looks like is the same error as this https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1768

**Comment by Sunekaer** [comment]
It is the same issue, closing this one as there is no reason to have multiple open
