### ISSUE TITLE
[Bug]: Craftable Chickens, black icons not clickable.

### ISSUE THREAD

**Issue by fxceptioN** [FTBTeam/FTB-Modpack-Issues#1780]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

Cannot see the skin of the chicken itself. I cannot click on it either.

### Steps to reproduce

Step 1. Go to quests
Step 2. Passive Resources
Step 3. Click Craftable Chickens
Step 4. Click the Chicken itself.
Step 5. See missing skins, also cannot click on them.

### Expected behaviour

Actually see the skin of the chicken.

### Screenshots

![image](https://user-images.githubusercontent.com/16984021/200730225-77e8ca27-7dee-4a2a-b286-92b0d875a154.png)

![image](https://user-images.githubusercontent.com/16984021/200730244-82eebaf6-cee3-48b6-8138-427f11dedc38.png)

![image](https://user-images.githubusercontent.com/16984021/200730272-5142bdd6-8e71-4cfa-a20d-9df9843932fb.png)

**Comment by tyler489** [comment]
Those are the spawn eggs for the mob that don't have textures, if you keep scrolling you should see the textures of the chicken.

**Comment by Sunekaer** [comment]
What tyler489 said :)

**Comment by fxceptioN** [comment]
Interesting, Thanks.
