### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Repla7Noobx** [FTBTeam/FTB-Modpack-Issues#1781]
### Modpack

StoneBlock3

### Modpack version

1.1.1

### Describe the bug

Lava eggs destorys blocks. I figured pipez and crafting station i don't know how many blocks are there.

### Steps to reproduce

1. Right click with lava egg to a non full block.
2. Block replaced with lava.

### Expected behaviour

Placin lava on top of non full bock.

**Comment by Copperearth** [comment]
Workaround: use the lava egg + bucket recipe

**Comment by Sunekaer** [comment]
Should be fixed in 1.2.0
