### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jerzean** [FTBTeam/FTB-Modpack-Issues#1782]
### Modpack

stoneblock 3

### Modpack version

1.2.0

### Log Files

[hs_err_pid3071.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9967426/hs_err_pid3071.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9967435/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9967436/latest.log)

### Describe the bug

installing on a centos 7 server

### Steps to reproduce

run installer
start server
wait for the crash almost instantly

### Expected behaviour

well it should start up with out crashing

**Comment by Sunekaer** [comment]
Can you try and delete the libraries and jre folder and run the installer again and see if that fixes the issue?

**Comment by jerzean** [comment]
[screenshot of console](https://i.gyazo.com/3008328e975bf3916c28c372cf85ce27.png)
would giving you access to the box(server) help? this is server i physically own

**Comment by Raidobw2** [comment]
Does this also happen if you use another flavor of JDK 17, such as Adoptium? https://adoptium.net/
Also, if you remove `-XX:+UseG1GC` from the starting arguments (I think in `run.sh`), does the server crash or not?

**Comment by jerzean** [comment]
[hs_err_pid10455.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9993896/hs_err_pid10455.log)


> Does this also happen if you use another flavor of JDK 17, such as Adoptium? https://adoptium.net/ Also, if you remove `-XX:+UseG1GC` from the starting arguments (I think in `run.sh`), does the server crash or not?

also ive tried other versions of java17 with the same outcome

**Comment by jerzean** [comment]
i ran `ulimit -c unlimited` before trying to start the server and it seems to launch fine now, seems core dumps have to be enabled or it fails to launch
