### ISSUE TITLE
[Bug]: Enchantment Factory by IF will not produce Protection enchantments

### ISSUE THREAD

**Issue by adamras** [FTBTeam/FTB-Modpack-Issues#1783]
### Modpack

Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

Enchantment Factory by IF will not produce Protection enchantments.  I am able to acquire them through the vanilla enchanting table.

### Steps to reproduce

Place book or gear in Enchantment factory.  No protection enchants ever get placed.  Attempted 50 times.

### Expected behaviour

Portection would be enchanted on an item

**Comment by Sunekaer** [comment]
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1302
