### ISSUE TITLE
[Bug]: Functional Storage - Pulling Upgrade not working with compacting drawers correctly

### ISSUE THREAD

**Issue by NotPiffany** [FTBTeam/FTB-Modpack-Issues#1784]
### Modpack

Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

When using a framed compacting drawer (not sure about the unframed) next to a roost, the puller upgrade will not work with if the lower right part of the compacting drawer doesn't match what should be pulled from the roost (i.e. coal, redstone, glowstone, etc.).

### Steps to reproduce

1. Make a roost
2. Put a coal chicken in the roost.
3. Put a framed compacting drawn next to the roost.
4. Set the compacting drawer to hold coal: the top will be blocks, the bottom left will be coal, and the bottom right will be empty.
5. Put a pulling upgrade in the compacting drawer, set to pull from the roost.
6. Get frustrated.

### Expected behaviour

I expected coal (for example) to be pulled from the roost into the compacting drawer.

### Additional information

The puller works when the chicken is producing the item in the bottom right of the compacting drawer; with a gold chicken, for example, the nuggets are pulled from the roost into the drawer exactly as I expected. The problem is with drawers where the bottom right section remains empty (like coal) or if the bottom right section differs from the item I want pulled in (redstone).

**Comment by Sunekaer** [comment]
https://github.com/Buuz135/FunctionalStorage/issues/115

**Comment by Sunekaer** [comment]
Should be fixed in the pack already :)
