### ISSUE TITLE
[Suggestion]: Adding the Tool Belt mod to help alleviate the wrench clutter

### ISSUE THREAD

**Issue by tyreforhyred** [FTBTeam/FTB-Modpack-Issues#1786]
### Modpack

Stoneblock 3

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/tool-belt
Tool Belt is a Curios compatible storage solution for various equipment items. It offers a 2 slot radial menu inventory that can be easily accessed with a hotkey, and can be upgraded to hold up to 9 items. With the multitude of hammers, picks, and more importantly a mountain of wrenches the pack offers it can be handy to have all of them readily available in an easy to use swapping feature rather than hunting and pecking around in a backpack when you're working around different parts of your base.

As an aside I suggest using B:releaseToSwap=true in the config to remove a bit of the tedium of actually having to click the item you're mousing over and instead only having to hold and release the swap key when your cursor is over the item you want. I also use B:displayEmptySlots=true so that your radial menu isn't constantly shifting in size when you have the belt upgraded to max slots. But of course this is all personal preference and others may feel differently.

**Comment by Sunekaer** [comment]
Mod has already been suggested and declined, thanks for your suggestion
