### ISSUE TITLE
[Bug]: ProjectE

### ISSUE THREAD

**Issue by wskrzyp78** [FTBTeam/FTB-Modpack-Issues#1790]
### Modpack

stoneblock3

### Modpack version

1.2.0

### Describe the bug

the Body Stone, Soul Stone and Life stone don't works on the necklace slot 

### Steps to reproduce

place on the necklace slot

### Expected behaviour

restores hunger or heart 

### Screenshots

![image](https://user-images.githubusercontent.com/88372188/200816544-80af4a84-cfe2-4d9f-a75f-4cad421b90ac.png)
![image](https://user-images.githubusercontent.com/88372188/200816599-ffacca03-3a8e-4cfa-bfe8-da3682a5d3ca.png)
![image](https://user-images.githubusercontent.com/88372188/200816683-d2ab98a4-53d9-47ed-aeb1-a617ccea5bb5.png)

**Comment by WhitePhant0m** [comment]
You need to activate them first 🤦

**Comment by Sunekaer** [comment]
What [WhitePhant0m](https://github.com/WhitePhant0m) said :)
