### ISSUE TITLE
[Bug]: FPS spikes

### ISSUE THREAD

**Issue by Sirinakis** [FTBTeam/FTB-Modpack-Issues#1791]
### Modpack

Stoneblock 3

### Modpack version

1.1.0

### Describe the bug

frequently fps spikes freezing the screen, gpu usage goes to 100% for miliseconds

### Steps to reproduce

just play the game

### Expected behaviour

get fps spikes

**Comment by Sunekaer** [comment]
How much ram do u have assigned to the pack?
What kinda computer do you have?
And changed settings or mod changes?
