### ISSUE TITLE
[Bug]: block placer will place blocks across latitudes in other dimensions with the same coordinates

### ISSUE THREAD

**Issue by KuroPeach** [FTBTeam/FTB-Modpack-Issues#1792]
### Modpack

FTB StoneBlock3

### Modpack version

1.1.0

### Describe the bug

The block placer will place blocks across latitudes in other dimensions with the same coordinates, Both engineersdecor and IF placers have this problem. The decimation rendering of the IF resin extractor also appears at the same coordinates across latitudes.
![image](https://user-images.githubusercontent.com/19620848/200832975-c67b19e5-12bf-4a23-bb7b-7f509b381b22.png)
![image](https://user-images.githubusercontent.com/19620848/200833116-b2772128-16d4-4bb2-ad54-ecc9740cfb3e.png)
![image](https://user-images.githubusercontent.com/19620848/200833171-5ea11089-88b5-4a04-b59b-7fa70f29c7ae.png)
![image](https://user-images.githubusercontent.com/19620848/200833280-0165ff37-475a-4674-9e13-83a49f1c084e.png)

### Steps to reproduce

None

### Expected behaviour

Help submit to the author to fix

**Comment by Sunekaer** [comment]
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1303

**Comment by Sunekaer** [comment]
so dim type would then just give ftbsbc:stoneblock and no the specific dim

**Comment by KuroPeach** [comment]
Engineersdecor's placer has same bug, Maybe other placers besides these two placers will also. 
And IF's fluid_extractor rendering will appear in all ftbsbc:stoneblock dims.

**Comment by Sunekaer** [comment]
I also opened an issue with Engineers https://github.com/stfwi/engineers-decor/issues/225
