### ISSUE TITLE
[Bug]: [Stoneblock 3] Rich soil slows botany pot 10 times, other soils slow growth instead of speedup as well

### ISSUE THREAD

**Issue by tmdshabigithub** [FTBTeam/FTB-Modpack-Issues#1793]
### Modpack

FTB Stoneblock 3

### Modpack version

1.1.0

### Describe the bug

In botany pot, tree on rich soil has
Speed: 0.1X
Grow Time: 20:00

On common dirt:
Speex: 1.0X
Grom Time: 2:00

Shouldn't it be faster 10x, not slower 10x?

### Steps to reproduce

Put a sapling and soil into botany pot

### Expected behaviour

Expected high level soil speed up growth

**Comment by Sunekaer** [comment]
This is an issue on Farmers delights side, but ill try and fix

**Comment by OldDogy** [comment]
A lot of botany pot soil blocks slow down production instead of speeding it up.
