### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JakeNumber69** [FTBTeam/FTB-Modpack-Issues#1794]
### Modpack

FTB Inferno

### Modpack version

1.2.1

### Log Files

Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 3328cfd8-2b40-4154-98ad-a09d566aa04b
	FML: 40.1
	Forge: net.minecraftforge:40.1.84
	FramedBlocks BlockEntity Warning: Not applicable
[21:06:18] [Render thread/FATAL]: Preparing crash report with UUID 4a90ea39-0051-4538-989d-6e02144d799a
[21:06:79] [Render thread/FATAL]: Preparing crash report with UUID e8766c5d-c5e3-4dd2-8588-651f6c742e58
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Lenovo\AppData\Roaming\.minecraft\versions\Inferno 1.2.1\crash-reports\crash-2022-11-09_21.06.11-client.txt
[21:06:82] [Thread-13/INFO]: Shutdown called, Stopping our threads
java.lang.NullPointerException: Cannot invoke "net.creeperhost.ftbbackups.org.quartz.Scheduler.clear()" because "net.creeperhost.ftbbackups.FTBBackups.scheduler" is null
	at TRANSFORMER/ftbbackups2@1.0.14/net.creeperhost.ftbbackups.FTBBackups.killOutThreads(FTBBackups.java:110)
	at java.base/java.lang.Thread.run(Thread.java:833)
AL lib: (EE) alc_cleanup: 1 device not closed
Here I am!

### Describe the bug

The game crashes when changing textures.

### Steps to reproduce

Go to the resource pack window and change any texture

### Expected behaviour

The game crashes

**Comment by tyler489** [comment]
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Lenovo\AppData\Roaming.minecraft\versions\Inferno 1.2.1\crash-reports\crash-2022-11-09_21.06.11-client.txt

That file would probably be helpful

**Comment by Saereth** [comment]
this is a duplicate, disable hexerei mod and relaunch, change your resource pack then re-enable hexerei. We're awaiting a fix from the mod dev for this and already tracking it

**Comment by JakeNumber69** [comment]
thanks

**Comment by JakeNumber69** [comment]
Doesn't work!!!
