### ISSUE TITLE
[Bug]:  XP Glitch

### ISSUE THREAD

**Issue by anesbit** [FTBTeam/FTB-Modpack-Issues#1796]
### Modpack

Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

When you use a cardboard box to move a furnace that has XP stored inside it when you unpack and re-pack it spits out the XP again. You can do this infinitely to get unlimited XP.

### Steps to reproduce

1. Put items in smelter to smelt.
2. Take Cardboard Box and packge the smelter. (Drops XP)
3. Place Cardboard Box and unpackage.
4. Re-Package Smelter with cardboard box. (Drops XP)
5. Rinse and Repeate Steps 3 and 4

### Expected behaviour

No Extra XP when you repack the smelter.

**Comment by Sunekaer** [comment]
https://github.com/mekanism/Mekanism/issues/7660
