### ISSUE TITLE
[Bug]: Farmer's Delight soils are slower than dirt in Botany Pots

### ISSUE THREAD

**Issue by Copperearth** [FTBTeam/FTB-Modpack-Issues#1798]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

Soils such as Rich Soil from Farmer's Delight give a 0.1X growth multiplier. In previous versions of the modpack, these soils would've actually been preferable to dirt's 1.0X multiplier

### Steps to reproduce

1. press u on a seed (i used industrial hemp seeds)
2. go to botany pots
3. look at the different multipliers for the soils.

### Expected behaviour

rich soil should be better than dirt. not 10x worse

### Screenshots

![image](https://user-images.githubusercontent.com/22625584/200877477-034bb075-1696-4df0-b552-9f3b29f3cbf9.png)

**Comment by tmdshabigithub** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1793 just five issues below ...
