### ISSUE TITLE
[Bug]: Impossible to craft the Creative Wireless Crafting Teminal

### ISSUE THREAD

**Issue by Kymitsu** [FTBTeam/FTB-Modpack-Issues#18]
### Modpack

FTB University 1.12

### Modpack version

1.2.1

### Describe the bug

The crafting recipe of the Creative Wireless Crafting Terminal is not working. Impossible de craft the item. Auto filling the craft with JEI works.
I tried the craft with a fresh new Wireless Crafting Terminal, same result.

Here the info shown using the command /ct hand:
<wct:wct>.withTag({CraftingMatrix: {Size: 9, Items: []}, ViewCells: {Size: 4, Items: []}, TrashSlot: {Size: 1, Items: []}, BoosterSlot: {Size: 1, Items: [{Slot: 0, id: "ae2wtlib:infinity_booster_card", Count: 1 as byte, Damage: 0 as short}]}, ShiftCraft: 1 as byte, IsInRange: 1 as byte, MagnetSlot: {Size: 1, Items: [{Slot: 0, id: "wct:magnet_card", Count: 1 as byte, tag: {MagnetMode: 0}, Damage: 0 as short}]}, name: "", encryptionKey: "16218456934794", internalCurrentPower: 1600000.0})

### Steps to reproduce

Autofill the recipe using JEI
Recipe filled in the basic Crafting Table correctly
Can't craft the Item

### Expected behaviour

There should be The Creative Wireless Crafting Teminal in the crafting result

### Screenshots

![image](https://user-images.githubusercontent.com/8872328/134816241-cf71fa73-2b64-489b-b522-ce556c8c6e0b.png)
![image](https://user-images.githubusercontent.com/8872328/134816256-6304d979-1e80-4230-8c82-90afca4a59e7.png)

**Comment by manmaed** [comment]
@aaronhowser1 any word on this has this been fixed

**Comment by manmaed** [comment]
@aaronhowser1 any word on this has this been fixed

**Comment by aaronhowser1** [comment]
It has not been
