### ISSUE TITLE
[Bug]: REI doesnt show ALL recipes

### ISSUE THREAD

**Issue by redgoblin88** [FTBTeam/FTB-Modpack-Issues#1802]
### Modpack

FTB stoneblock 3

### Modpack version

1.2.0

### Describe the bug

when looking at the use (also occurs for "recipe") of an item, only some of them will be shown.
This can be found by replacing REI (roughly enough items) with JEI (just enough items)

in my case, when i search for uses of "sand", there are 7 "tabs" of reipes, however with JEI installed this is increased considerably to 33 tabs

i found this bug as i was trying to see how to get clay, in which there was no sand "washing" recipe when searching for the "use" of sand, however searching for the "recipe" of clay showed that the sand is used

### Steps to reproduce

different items may vary in results, in my case using the "yellow" sand gave a vast difference in "recipes"

to see that some recipes are "hidden", you can replace REI (roughly enough items) with JEI (just enough items) [note: no extra work is needed, i was able to replace them with no crashing or problems]

### Expected behaviour

REI to show ALL the items uses/recipes, not only some

### Screenshots

![image](https://user-images.githubusercontent.com/13396472/200909881-61bca155-da30-41fc-9976-4b6184ed0d46.png)
![image](https://user-images.githubusercontent.com/13396472/200909957-385a96ff-be50-457c-a60b-014cc730f64c.png)

**Comment by Sunekaer** [comment]
There is more then 7 tabs.
![billede](https://user-images.githubusercontent.com/18720460/200924642-2955bcae-d539-424d-8da0-7bc09cc64db4.png)
These arrows would be grayed out if there wasnt more pages of tabs, you can also use the scroll-wheel over the tabs to change tabs

**Comment by aaronhowser1** [comment]
https://user-images.githubusercontent.com/15698722/200965563-3d38ce81-aff1-4a5c-9f26-49447d70574d.mp4

https://user-images.githubusercontent.com/15698722/200965849-83b0cf8b-a9b9-4bf5-a7f5-bcd65e014443.mp4

The only way you would know this is by moving to another tab though. If I was looking specifically for a tab and didn't see it, I wouldn't click on one of the others. I would just assume the tab didn't exist.
