### ISSUE TITLE
[Bug]: when you press U on moded enderchest game crash

### ISSUE THREAD

**Issue by orekiller** [FTBTeam/FTB-Modpack-Issues#1803]
### Modpack

stoneblock 3

### Modpack version

1.0.2

### Describe the bug

i am still on a older version 1.0.2 for a server when you press U on the moded enderchest your game crash

### Steps to reproduce

go to a made enderchest
press key u
game crash

### Expected behaviour

game crash

**Comment by Sunekaer** [comment]
Duplicate of #1574
