### ISSUE TITLE
[Bug]: Can place water inside a slab

### ISSUE THREAD

**Issue by philip0524** [FTBTeam/FTB-Modpack-Issues#1805]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

When right clicking a slab with a water bucket, the water is being placed inside the slab and is behaving like a normal water source block. The water also flows normally. The slab is still there. I only have tried it with cobblestone slabs.

### Steps to reproduce

1. Place down a cobblestone slab
2. Right click the slab with a water bucket

### Expected behaviour

I expect not to be able to place water inside a solid block

### Screenshots

https://user-images.githubusercontent.com/72703443/200948448-8c0d2d7a-75ea-42e5-bf21-d0ed40c1c0f2.mp4

**Comment by iAedz** [comment]
You know this is a vanilla thing that came out like 5 years ago right..?

**Comment by philip0524** [comment]
I actually didn't. I'll mark this as closed then.
