### ISSUE TITLE
[Bug]: (StoneBlock 3) Minecraft won't launch

### ISSUE THREAD

**Issue by Linkling64** [FTBTeam/FTB-Modpack-Issues#1807]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.0

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9975670/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9975671/latest.log)

### Describe the bug

When I try launching the game, the launcher always gets stuck at some point trying to load.

### Steps to reproduce

1. Try clicking play on the FTB StoneBlock 3 modpack
2. Wait and it will get stuck

### Expected behaviour

Minecraft opens

### Screenshots

<img width="1307" alt="Screenshot 2022-11-09 at 5 44 17 PM" src="https://user-images.githubusercontent.com/117760628/200958272-f399aa7a-0752-4257-a8b8-3afe2ef051b5.png">

### Additional information

This is on MacOS Ventura 13.0
I downloaded the Launcher on Monday to play Stoneblock 3 and I had never used it before this.
I haven't managed to open the game once.
It usually gets stuck on "Processing transition LOAD_REGISTRIES", "Processing work INJECT_CAPABILITIES", or "Processing work UNFREEZE_DATA"
I have tried restarting my computer, redownloading it, etc. and nothing has worked.
There is a Java application shown as open on the dock, but it doesn't open anything when I click on it.
When I right click on the application it says "Application not responding"

**Comment by walksanatora** [comment]
Bump: I also get this but it usually gets stuck at `Processing work: INJECT_CAPABILITIES`

**Comment by Raidobw2** [comment]
That looks more like an app issue than a modpack issue. Has this been reported to https://go.ftb.team/app-feedback?

What happens if you open the instance files, move all the mods from the `mods` folder out of there, and then start the game? (so test if the mods folder is empty)

**Comment by Linkling64** [comment]
I tried opening it without the mods folder and it opened no problem
I have also tried other modpacks and they worked, so I think it is the StoneBlock pack not the app, but idk for sure.

**Comment by Linkling64** [comment]
Still not working on 1.2.1. Didn't expect it to, but still...

**Comment by Raidobw2** [comment]
Sorry for the delay, in that case it looks like a mod is causing the issue. Can you try removing these:
- minetogether-forge-1.18.2-5.2.8
- SimpleDiscordRichPresence-forge-3.0.1-build.21+mc1.18.2
- Any mod with the word `kubejs` in it

These are the only mods I think maybe could interfere right away, but I'm not sure even then... The right thing to do is a mod binary search but it's something we'll have to look into.
Though knowing that the pack opened without the mods would mean we should be able to test this on a Mac (which I currently don't have). I'll probably need to setup a VM for it, if it's possible somehow

**Comment by Linkling64** [comment]
It finally opened when I removed the kubejs mods, but then it gave me an error in the game that some other mods required kubejs to be installed. I tried adding the mod `kubejs-forge-1802.5.5-build.554` but then it got stuck on "Processing work LOAD_REGISTRIES" so I think that the problem is with that mod.

I've attatched the latest.log file from when it _did_ without the kubejs-forge mod.

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9997188/latest.log)

**Comment by Commander-N** [comment]
So, I did a little looking into this, and it seems there is a compatibility issue between FTBQuests and Kubejs, or at least according to some issue reports on Kubejs GitHub. So maybe this helps with figuring out how to fix this issue?
By the way, I also am having the same problems trying to launch the Stoneblock 3 modpack from my mac, but it seems to work on windows.

**Comment by walksanatora** [comment]
Note: I also get these same issues on linux (Arch in my case)

**Comment by Raidobw2** [comment]
Sorry for the delay @Linkling64, interesting findings. Try changing the Flywheel configuration (`/config/flywheel-client.toml`) like so and save the file:
![image](https://user-images.githubusercontent.com/17010632/202651146-dbea54cb-3f14-4bb8-be5d-984eb4a5dd73.png)

This showed up in your crash log the second time and that config option should turn off Flywheel (an optimization mod for Create):
```
Caused by: java.lang.ExceptionInInitializerError
	at com.jozufozu.flywheel.backend.Backend.chooseEngine(Backend.java:96) ~[flywheel-forge-1.18.2-0.6.5.jar%23123!/:0.6.5]
```

Let me know if that works

**Comment by Linkling64** [comment]
I tried changing the config but unfortunately it didn't seem to change anything. It still got stuck on "Processing work INJECT_CAPABILITIES"

**Comment by jabackes** [comment]
I was literally replying to your other post @Linkling64, where there was call for what versions of Mac OS, but you'd closed the report right as I was about to press "comment". I have a FTB log thingy - FTB-DBGELOROFIYUF.

Running Mac OS 12.6 (21G115) and getting stalled at load registries. I'll try the fixes listed here too and report back.

**Comment by jabackes** [comment]
progress report:

I've updated the config file for flywheel. that didnt change anything. I removed all mods and shoved them into a disabled mods directory and the instance loaded. I started populating the mods folder alphabetically, kept getting the instance to load up, but complain about mod dependancies.

decided to skip ahead and replaced ALL mods except the listed, Minetogether, the one about discord, I did put the kubejs mods back into the pack, but it does stall on a new line "processing work UNFREEZE_DATA" going to pull the kubejs mods now.

**Comment by jabackes** [comment]
SimpleDiscordRichPresence-forge-3.0.3-build.26+mc1.18.2.jar
kube-utils-forge-0.1.3+mc1.18.2.jar
kubejs-blood-magic-1802.1.2-build.4.jar
kubejs-create-forge-1802.2.2-build.28.jar
kubejs-forge-1802.5.5-build.556.jar
kubejs-immersive-engineering-1802.2.1-build.35.jar
kubejs-mekanism-1802.1.3-build.8.jar
kubejs-thermal-1802.1.5-build.14.jar
kubejs-tinkers-1802.1.0-build.1.jar
kubejs-ui-forge-1802.1.8-build.17.jar
minetogether-forge-1.18.2-6.0.12.jar

those removed and the pack loaded! however still got an error that kubejs was not installed so it wouldn't play. replaced the kubejs-forge-1802.5.5-build.556.jar and tried again: it crashed. (I think I might have moved the kube-utils mod too, so I am trying one more time with only the kubejs-forge plugin installed)

**Comment by jabackes** [comment]
same crash now as before, unfreeze_data step. went and got the latest kubejs-forge from curse forge... trying that.

**Comment by jabackes** [comment]
nope, crashed outright. noticed I was using a beta kubejs build, trying latest release from curse forge, just-in-case. kubejs-forge-1802.5.5-build.556.jar (I am aware its the same version installed, but just-in-case)

**Comment by jabackes** [comment]
yep, no dice when kubejs is in the mods folder at all. must be the conflict listed above. I'm happy to provide any additional info if needed.

**Comment by jikuja** [comment]
The current findings indicate that the issue is caused by some weird logging interaction between FTB App and game processes:
https://github.com/FTBTeam/FTB-App/issues/713

Therefore a list of working and non-working operating systems would be great.

**Comment by jabackes** [comment]
> The current findings indicate that the issue is caused by some weird logging interaction between FTB App and game processes: [FTBTeam/FTB-App#713](https://github.com/FTBTeam/FTB-App/issues/713)
> 
> Therefore a list of working and non-working operating systems would be great.

Mac OS 12.6 (21G115) does not work without modifying the pack contents.

**Comment by Linkling64** [comment]
Mac OS 13.0.1 (22A400), the latest Mac OS update, does not work either.

**Comment by BetterMobs** [comment]
![image](https://user-images.githubusercontent.com/108685269/203492426-d7d75c8a-352b-4979-878f-ccd46e157022.png)
here it also won't work

**Comment by MstrVLT** [comment]
I use the PolyMC launcher - and it works like a charm with StoneBlock 3. FTB refuses to support owners of Unix systems ((

**Comment by BetterMobs** [comment]
> I use the PolyMC launcher - and it works like a charm with StoneBlock 3. FTB refuses to support owners of Unix systems ((

tysm it worked, you got from me tip in brave browser from me

**Comment by jikuja** [comment]
Did anyone having issue on Linux run Visual VM or some other tool to find out why MC process is hanging

> FTB refuses to support owners of Unix systems ((
Works for me on OS X 10.15.7 and works for multiple Linux users but as long as feedback does not include any details about operating system solving the issue will be really hard.

If anyone knows how to use visual vm (or other tool to generate thread dumps and profiling), please ping me here or in FTB discord for more details.

**Comment by jikuja** [comment]
Getting thread dump from (MC process and) from FTB app's helper process would give some insights.

CPU profiling will probably just fail because AFAIK those processes(threads) are in IO wait state.

**Comment by walksanatora** [comment]
It doesn't crash
It just spikes cpu usage and stops responding (usually long enough for a disconnect to occur)

**Comment by jabackes** [comment]
> I use the PolyMC launcher - and it works like a charm with StoneBlock 3. FTB refuses to support owners of Unix systems ((

attempting to use this right now. I'll let you know if it works. nothing I've done with FTB works at all since their update. pretty sad IMO.
