### ISSUE TITLE
[Suggestion]: [Stoneblock 3] Change lapis chicken to give lapis lazuli

### ISSUE THREAD

**Issue by tmdshabigithub** [FTBTeam/FTB-Modpack-Issues#1808]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Maybe dye output is intended by mod developer, and while it can be processed from gravel, I feel that not getting Lapis Lazuli from chicken like in previous versions break the spirit of Stoneblock. (Gravel provessing line also takes quite a lot space and requires to deal with subproducts most of them already supplied by chickens).

**Comment by tyler489** [comment]
I was thinking about requesting this, Glad someone else thinks it would be helpful.

**Comment by tmdshabigithub** [comment]
Also I wish bonemeal chicken can give bonemeal instead of dye
