### ISSUE TITLE
[Bug]: No Gravity from Giant Chance Cube

### ISSUE THREAD

**Issue by NordicGamerFE** [FTBTeam/FTB-Modpack-Issues#1809]
### Modpack

FTB Stoneblock 3

### Modpack version

2.2.0

### Log Files

N/A

### Describe the bug

I got the potion chance cube effect, I got some effect that didn't run out didn't get removed from milk or relogs. Once I checked my NBT data I got a no gravity effect that was enabled

### Steps to reproduce

open giant chance cubes.

### Expected behaviour

for all effects to get removed with time or milk

**Comment by NordicGamerFE** [comment]
@Raidobw2 sorry but i apperently put down the wrong modpack when I wrote this, I've updated my issue :P

**Comment by Raidobw2** [comment]
Got it, thanks

**Comment by Devilaux** [comment]
Why is this closed? I don't see any solution?
