### ISSUE TITLE
[Bug]: Crash Upon Start

### ISSUE THREAD

**Issue by Ankit17430** [FTBTeam/FTB-Modpack-Issues#1811]
### Modpack

StoneBlock 3

### Modpack version

1.2.0

### Log Files

[crash-2022-11-10_10.15.55-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9976761/crash-2022-11-10_10.15.55-client.txt)

### Describe the bug

Upon Starting the game crashes, I was able to run 1.1.0 with no issues.

### Steps to reproduce

1. Lunch the instance from FTB app
2. It crashes within 2 mins

### Expected behaviour

Lunch the modpack

**Comment by Sunekaer** [comment]
Duplicate of  #1768
