### ISSUE TITLE
[Bug]: `Cannot read property "id" from undefined` crash in FTB University

### ISSUE THREAD

**Issue by TheBlindLama** [FTBTeam/FTB-Modpack-Issues#1812]
### Modpack

FTB University 1.16

### Modpack version

1.7.0

### Log Files

https://crashy.net/Z25adzWvLW0BtqtqMsMP

### Describe the bug

Minecraft crash when I try to launch the modpack. The game start but I see an error saying that there is no mod causing this issue.

### Steps to reproduce

1. Launch the modpack
2. Wait for the end of the loading

### Expected behaviour

Game start normaly

### Additional information

I'll try to update Java and  reinstall the modpack and I'll update this

**Comment by Raidobw2** [comment]
Hi, did you remove some mods? The game is saying that there's something missing in `kubejs/client_scripts/main_menu.js`
Try reinstalling the pack and let me know if it works

**Comment by Raidobw2** [comment]
I've been told this is an actual bug in the modpack -- for now you can downgrade the modpack to the previous version if it works
(To modpack dev reading this: Try using `Platform.mods.minetogether` in your if statement instead)

**Comment by TheBlindLama** [comment]
Hello, just wanted to give a quick update on this. This issue seems tied to playing in offline mod. If you wanna play in offline mod, it is needed to disable MineTogether as it will give you an error otherwise. (Hence why the mod that was missing)

If you disable MineTogether, the game crash with the error stated in the original post.
