### ISSUE TITLE
[Suggestion]: FTB Stoneblock 3 YABBA

### ISSUE THREAD

**Issue by Rexlord** [FTBTeam/FTB-Modpack-Issues#1819]
### Modpack

FTB Stoneblock 3

### Mod suggestion

YABBA
https://www.curseforge.com/minecraft/mc-mods/yabba

I know a lot of people like AE2 but there are those of us who prefer Refined Storage. However, RS is missing a few advanced items that is taken care of by another mod that pairs very nicely with it and puts in on a level playing field with AE2 so those of use who prefer RS over AE2 don't feel like we are forced in to playing the other mod. Enter the mod Extrastorage. It adds in multiple tiered crafters and advanced exporters/importers as well as a few other things. Thanks for your consideration.

**Comment by Sunekaer** [comment]
YABBA doesn't exist for above 1.12.2
