### ISSUE TITLE
[Bug]: REI Recipe using the arrows jumps and icons counts changes

### ISSUE THREAD

**Issue by Eden-817** [FTBTeam/FTB-Modpack-Issues#1821]
### Modpack

FTP StoneBlock 3

### Modpack version

1.1.0

### Describe the bug

When you search for recipes like going through the chickens you click on a chickens on the right and on some the number of items on the right will shift and when you are trying to compare this becomes hard to keep track of where you are at.

Also when using recipes and use the arrows to go through everything that item is made or used in

### Steps to reproduce

When you search for recipes like going through the chickens you click on a chickens on the right and on some the number of items on the right will shift and when you are trying to compare this becomes hard to keep track of where you are at.

### Expected behaviour

The row and the chickens should not change

**Comment by Sunekaer** [comment]
https://github.com/shedaniel/RoughlyEnoughItems/issues/664

**Comment by Sunekaer** [comment]
Solved be fixed
