### ISSUE TITLE
[Bug]: Avaria Mod Pack

### ISSUE THREAD

**Issue by KernaI** [FTBTeam/FTB-Modpack-Issues#1822]
### Modpack

FTB Stoneblock 3

### Modpack version

Version 1.2.0

### Describe the bug

Unable to craft further into mod pack as error

### Steps to reproduce

1. tried clicking on recipe to add items and got error everytime

### Expected behaviour

Trying to craft neutron collector and get error screenshots attached

### Screenshots

![2022-11-11_01 20 26](https://user-images.githubusercontent.com/24534327/201126375-5154fbf5-d108-4484-beb3-86b687847792.png)
![2022-11-11_01 19 52](https://user-images.githubusercontent.com/24534327/201126404-82b45332-d914-4516-9f33-c2cc1f8757ac.png)

**Comment by Sunekaer** [comment]
Ye related to https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1741
