### ISSUE TITLE
[Bug]: Server crash after start

### ISSUE THREAD

**Issue by LukeKing12** [FTBTeam/FTB-Modpack-Issues#1823]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.0

### Log Files

crash-report: https://pste.ch/zifigaraqa.rb
logs: https://pste.ch/afavomupuy.md

### Describe the bug

I'm kinda confuse how this happen but after switching to 1.2.0 the first boot of the server worked fine, but when i switch off the server for the night and power on the next morning the server after 10s or so just crash

### Steps to reproduce

1. Just finished blood magic
2. Added some auto-crafting of food in the me
3. Stop the server for the night
4. Start with error the next morning

### Expected behaviour

Server to run fine

**Comment by Sunekaer** [comment]
Your server is being lagged out by watch of time on Chickens

**Comment by Sunekaer** [comment]
Go to Servers > Manage server > Manage > Settings.
    Go to server.properties.
    Change max-tick-time to -1.
    Save and Reboot server for changes to take effect.
    
    Then when you get on remove some of the watchs to stop lag
