### ISSUE TITLE
[Bug]: Block of Copper does not have an EMC value

### ISSUE THREAD

**Issue by Stephfra** [FTBTeam/FTB-Modpack-Issues#1824]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

Copper ingots have an EMC value
All vanila ore like blocks, have an EMC value (iron/coal/dia/gold/emerald)

### Steps to reproduce

Just start the game

### Expected behaviour

Block of copper should have an EMC value of 1,152

**Comment by Sunekaer** [comment]
Well its a bit more work then just slabbing emc on that block as you have all the different versions and cut version and so on, but its something ill look in to
