### ISSUE TITLE
[Bug]: Pretty Pipes Crafting Terminal doesn't work with REI

### ISSUE THREAD

**Issue by nfinch23** [FTBTeam/FTB-Modpack-Issues#1826]
### Modpack

Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

When you have a Pretty Pipes crafting terminal and you click the + button on a recipe to send it to the crafting window, it should send the whole recipe over like in JEI. But this pack uses REI and for some reason, it only works if the recipe doesn't use any empty spaces, so you can send the recipe for compressed cobble over but not the recipe for a chest. This could be a bug with REI or with Pretty Pipes. It's super frustrating trying to craft with it as your initial storage system before RF power.

### Steps to reproduce

1. Attach a Pretty Pipes crafting terminal to a chest with items in it via a pipe and open the UI.
2. Go to REI and click on any recipe that doesn't use all 9 crafting slots.
3. Click the + button to send the recipe to the crafting terminal.
4. The recipe doesn't get sent over. If you repeat steps 2 and 3 with a recipe that uses all 9 slots, it should work as intended.

### Expected behaviour

The recipe should be sent to the crafting terminal and show the items needed for the recipe.

### Screenshots

![Capture14](https://user-images.githubusercontent.com/80540827/201160030-16b0a367-271a-4705-a815-d6787c186d1c.PNG)

**Comment by gaminggirl** [comment]
I can add on to this problem with the error message from the console when the recipe does not work 

> [13:25:11] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket@e5c5510, suppressing error
> java.lang.NullPointerException: Cannot invoke "de.ellpeck.prettypipes.packets.PacketGhostSlot$Entry.getStacks()" because the return value of "java.util.Map.get(Object)" is null
>         at de.ellpeck.prettypipes.terminal.CraftingTerminalBlockEntity.setGhostItems(CraftingTerminalBlockEntity.java:65) ~[PrettyPipes-1.12.8.jar%23193!/:1.12.8] {re:classloading,pl:epic_rei_lmao:B}
>         at de.ellpeck.prettypipes.packets.PacketGhostSlot.lambda$onMessage$0(PacketGhostSlot.java:64) ~[PrettyPipes-1.12.8.jar%23193!/:1.12.8] {re:classloading,pl:epic_rei_lmao:B}
>         at de.ellpeck.prettypipes.packets.PacketGhostSlot$2.run(PacketGhostSlot.java:82) ~[PrettyPipes-1.12.8.jar%23193!/:1.12.8] {re:classloading,pl:epic_rei_lmao:B}
>         at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:213) ~[forge-1.18.2-40.1.84-universal.jar%23256!/:?] {re:classloading,pl:epic_rei_lmao:B}
>         at de.ellpeck.prettypipes.packets.PacketGhostSlot.onMessage(PacketGhostSlot.java:79) ~[PrettyPipes-1.12.8.jar%23193!/:1.12.8] {re:classloading,pl:epic_rei_lmao:B}
>         at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.1.84-universal.jar%23256!/:?] {re:classloading,pl:epic_rei_lmao:B}
>         at java.util.Optional.ifPresent(Unknown Source) ~[?:?] {re:mixin}
>         at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.1.84-universal.jar%23256!/:?] {re:classloading,pl:epic_rei_lmao:B}
>         at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:153) ~[forge-1.18.2-40.1.84-universal.jar%23256!/:?] {re:classloading,pl:epic_rei_lmao:B}
>         at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:72) ~[forge-1.18.2-40.1.84-universal.jar%23256!/:?] {re:mixin,re:classloading,pl:epic_rei_lmao:B}
>         at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
>         at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
>         at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
>         at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
>         at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.1.84-universal.jar%23256!/:?] {re:classloading,pl:epic_rei_lmao:B}
>         at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[forge-1.18.2-40.1.84-universal.jar%23256!/:?] {re:classloading,pl:epic_rei_lmao:B}
>         at java.util.Optional.map(Unknown Source) ~[?:?] {re:mixin}
>         at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[forge-1.18.2-40.1.84-universal.jar%23256!/:?] {re:classloading,pl:epic_rei_lmao:B}
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1439) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:A}
>         at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:classloading,pl:epic_rei_lmao:B}
>         at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:classloading,pl:epic_rei_lmao:B}
>         at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:classloading,pl:epic_rei_lmao:B}
>         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:classloading,pl:epic_rei_lmao:B,re:mixin}
>         at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:epic_rei_lmao:B,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B}
>         at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:mixin,re:computing_frames,pl:epic_rei_lmao:B,re:classloading,pl:epic_rei_lmao:B}
>         at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
>         at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
>         at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:epic_rei_lmao:B,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B}
>         at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
>         at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
>         at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:epic_rei_lmao:B,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B}
>         at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
>         at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
>         at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23251!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
>         at java.lang.Thread.run(Unknown Source) [?:?] {}
>

**Comment by Sunekaer** [comment]
https://github.com/shedaniel/RoughlyEnoughItems/issues/1216

**Comment by Renari** [comment]
https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/26

Should be fixed.
