### ISSUE TITLE
[Bug]:Industrial centrifuge runs incorrect recipe

### ISSUE THREAD

**Issue by No-steve** [FTBTeam/FTB-Modpack-Issues#1827]
### Modpack

ftb sky odyssey

### Modpack version

v1.4.1

### Describe the bug

Empty cells are put into the industrial centrifuge, but lava cells recipe is excuted

### Steps to reproduce

bug

### Expected behaviour

bug fixes

### Screenshots

![2022-11-11_01 54 02](https://user-images.githubusercontent.com/105639186/201160743-1ff89881-ddd0-4489-96fa-e27ee38f0bcf.png)

**Comment by DinnerBeef** [comment]
Unable to reproduce this, issue.
