### ISSUE TITLE
[Bug]: Server Crash from Chisels and Bits Magnifier

### ISSUE THREAD

**Issue by Kangy1103** [FTBTeam/FTB-Modpack-Issues#1828]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.0

### Log Files

[crash-2022-11-10_18.03.25-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9983566/crash-2022-11-10_18.03.25-server.txt)

### Describe the bug

Unable to start server after crash. 
If i'm right about the log it's complaining about either an ae2 cable or the storage bus attached to it. Honestly not sure how to go about resolving this to recover the world

Any suggestions would be much appreciated :)

### Steps to reproduce

N/A

### Expected behaviour

Server should boot

**Comment by Saereth** [comment]
Chisel and bits client sided issue 
https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/1018

**Comment by togreglove** [comment]
We also had this issue. Was resolved by nbt editing the region file and removing the bus and cable from the offending location.  World booted fine after that with lesson learned about magnifying glasses and AE2

**Comment by Anzulo1984** [comment]
Use a world backup before the crash happened

**Comment by ThirtyTwelveNor** [comment]
#2106

**Comment by Sunekaer** [comment]
Should be fixed already
