### ISSUE TITLE
[Bug]: Alloy smelter not work

### ISSUE THREAD

**Issue by giovmer** [FTBTeam/FTB-Modpack-Issues#1829]
### Modpack

FTB Stoneblock 2

### Modpack version

1.16.1

### Log Files

[crash-2022-11-10_19.37.17-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9983784/crash-2022-11-10_19.37.17-client.txt)

### Describe the bug

I try to use alloy smelter and it don't work

### Steps to reproduce

.

### Expected behaviour

.

### Screenshots

![Screenshot (36)](https://user-images.githubusercontent.com/99511162/201180498-3e9fd093-17ec-4a05-b10a-71fcfb5a8ab9.png)

**Comment by Raidobw2** [comment]
I see, could you try to remove the mod Project Intelligence from the mods folder? I'm not sure but the game seems to be having trouble getting your selected in-game language for some reason...
