### ISSUE TITLE
[Bug]: Botany pots dont show usages in REI

### ISSUE THREAD

**Issue by ArchThunder762** [FTBTeam/FTB-Modpack-Issues#1830]
### Modpack

stoneblock 3

### Modpack version

1.1.0

### Describe the bug

The useage recipes for the Botany pots is not connected to JEI. And hitting the recipee button in the botany pots doesn't pull up any options. The recipees are visible in the jar folder for the mod but currently we are blindly guessing what soil and crop options there are for the mod. 

### Steps to reproduce

1. open botany pot interface. 
2. click recipe book
3. should open recipes, nothing actually happens

Alternatively
1. open jei and click "r" on a crop such as kelp. 
2. should see a botany pot tab and growth option, but none visible

### Expected behaviour

Should see botany pot recipee options for varous crops. But don't 

### Screenshots

![FTB StoneBlock 3 - Minecraft 1 18 2 2022-11-07 8_22_32 PM](https://user-images.githubusercontent.com/111213558/201185557-79299e2d-6f41-405e-98a9-feec83759406.png)
![FTB StoneBlock 3 - Minecraft 1 18 2 2022-11-07 8_22_27 PM](https://user-images.githubusercontent.com/111213558/201185559-60fb4c2d-61b5-473e-9b1d-e40d114673a9.png)

### Additional information

To be clear. the recipe to create botany pots is visible. but not the uses of the pots.

**Comment by Sunekaer** [comment]
Update your pack :)

**Comment by ArchThunder762** [comment]
This is only half completed. I see that the botany pots now show as a possible option when searching from the crop side. But we still can't select the botany pots to see their full list of recipes like we can any other crafting tool. Which also means the recipe button inside the botany pot interface still does nothing.
