### ISSUE TITLE
[Suggestion]: Make ProjectE Darkmatter Pedestals break more easily

### ISSUE THREAD

**Issue by Copperearth** [FTBTeam/FTB-Modpack-Issues#1833]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

I think the darkmatter pedestal should break more easily as it's very easy to make when compared to the tool required to mine it.
You can go days in a playthrough without being able to break the darkmatter pedestals as the morningstar required to mine them, which is comparitively hard to make

**Comment by Bimmr** [comment]
Cardboard boxes are a nice alternative to pickup/move them. I know it really doesn't solve the issue, but it is a work around.
