### ISSUE TITLE
[Bug]: Infinite blocks in Rechiseled

### ISSUE THREAD

**Issue by trephas** [FTBTeam/FTB-Modpack-Issues#1835]
### Modpack

Stoneblock3

### Modpack version

1.2.0

### Describe the bug

If you use the Chisel on any block you can ctrl + click that block and it will give you a full stack of that item. This only works for blocks that can be used in the Rechiseled Chisel

so if you put a stack of stone in the Chisel then Ctrl + Click the stone you will get back the amount that is in the Chisel but that amount stays in the Chisel so you can just keep Ctrl + Clicking 

### Steps to reproduce

1. Make Chisel from Rechiseled
2. Put stack of Stone in Chisel
3. Ctrl + click on stack
4. get free blocks from Rechiseled

### Expected behaviour

not to create matter out of nothing

### Additional information

not game breaking but still a bug

**Comment by Sunekaer** [comment]
this seems to working just fine for me: https://cdn.floatingmonkey.dev/screenshots/2022/11/13/1668357100_javaw.mp4
Are you on server or in SP?

**Comment by trephas** [comment]
yes I am in single player. You have to Ctrl click on the stone

**Comment by Sunekaer** [comment]
I am ctrl clicking it and it isnt duplicating for me

**Comment by trephas** [comment]
hmm it was doing it for me yesterday after the update. well maybe it was a one off bug or something. I do not know

**Comment by Sunekaer** [comment]
Can you replicate the issue now?

**Comment by trephas** [comment]
Yes I just did it again. I tried with Stone, Cobbled Deepslate, and Obsidian. All three of them did the same thing for me. Full stack in the Chisel. Push Ctrl and click on them and it gave me a full stack of the time while keeping 63 of the item inside the Chisel

**Comment by Sunekaer** [comment]
Do you have any changed keybinds?

**Comment by trephas** [comment]
no I do not. in fact I made a new world just to test it there and it does the same thing also.

**Comment by 5ully** [comment]
Im not able to reproduce this on the live sb3 version, from what i can see there is no keybinds actually bound to rechiseled, and it does not have the old change block in world without break/replace that could cause this type of issues

**Comment by Sunekaer** [comment]
I still cant replicate this, are you able to replicate this with an minecraft instance where you only have Rechiseled ?
