### ISSUE TITLE
[Bug]: Thief silverfish are not persitent when they steal gear

### ISSUE THREAD

**Issue by MissPotato** [FTBTeam/FTB-Modpack-Issues#1836]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.0

### Log Files

NA

### Describe the bug

If a thief silverfish steals your gear, then you die, they despawn with the gear on them. Lost my philospoher stone, klein star, and paxel. 

### Steps to reproduce

1) Spawn silverfish mother
2) get hit by thief
3) Get far enough that they de-spawn
4) Permanently lose items

### Expected behaviour

Not losing items

**Comment by Raidobw2** [comment]
Thanks for reporting, although I'll close the issue to avoid tracking the same problem which was originally reported at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1757

**Comment by MissPotato** [comment]
Ah sorry, I searched "thief" and saw nothing, should have searched silverfish as well, sorry again!
