### ISSUE TITLE
Error mods loadings

### ISSUE THREAD

**Issue by KingDs99** [FTBTeam/FTB-Modpack-Issues#1837]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9984693/latest.log)

### Describe the bug

When I try to lunch the pack it loads but at the end of the load a screen appears with the message '' Error loading Mods ''

### Steps to reproduce

1. Lunch the pack
2. Wait the load
3. The error appears

### Expected behaviour

i expected to have the home page of the game

### Screenshots

![Error](https://user-images.githubusercontent.com/113141618/201209372-7ef0b94f-b30c-4217-a721-7b617f274f79.PNG)

**Comment by Anzulo1984** [comment]
Seems like some files are missing/corrupted, i suggest to fully reinstall the pack and try again

**Comment by KingDs99** [comment]
Hey, thanks I will try and ping if it's okay or not

**Comment by Raidobw2** [comment]
Awesome, let me know if that works. You can also install a server locally and copy the relevant folders on your game (`mods`, `config`, `kubejs`, `defaultconfigs`)

https://www.feed-the-beast.com/modpacks/100-ftb-stoneblock-3
![image](https://user-images.githubusercontent.com/17010632/201513715-38d04354-675a-4506-bf65-c2d33267a052.png)

**Comment by KingDs99** [comment]
Hey, so I tried to reinstall the pack and it worked.

Thanks for the help and have a nice day.
