### ISSUE TITLE
[Bug]: Right Clicking Framed Slopes Crashes Clients

### ISSUE THREAD

**Issue by IronicMagnesium** [FTBTeam/FTB-Modpack-Issues#1838]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.0

### Log Files

[crash-2022-11-10_20.56.40-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9984657/crash-2022-11-10_20.56.40-client.txt)

### Describe the bug

Whenever framed slopes are right-clicked on a server it crashes the client.

### Steps to reproduce

1.Place Framed Slope
2.Right Click Framed Slope

### Expected behaviour

The block changes to the texture of the block you are holding.

**Comment by Sunekaer** [comment]
https://github.com/XFactHD/FramedBlocks/issues/208

**Comment by Sunekaer** [comment]
@IronicMagnesium can you recreate the crash and then provide the debug.log & latest.log found in logs folder right after it crash?

**Comment by IronicMagnesium** [comment]
Updating FramedBlocks to 5.9.1 seemed to fix it.
