### ISSUE TITLE
[Suggestion]: Possibly changing the gravestone mod for Corail or Other Curios supported graves?

### ISSUE THREAD

**Issue by Thunder-Nova** [FTBTeam/FTB-Modpack-Issues#1839]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

The issue with the current mod is pointed towards the Curios, where I have a full inventory plus my curios slots. Everything from curios gets spilled out and not return to it's proper slots.

Corail Tombstone is one mod that supports it. Though others might know of other mods.

Though Corail has those Lost Tablets that teleport to structures which can be earn by fishing. Might as well need to disable those.

Some other mods might have proper Curios support, but nothing pops in mind at the moment.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/corail-tombstone/files/4057116

**Comment by Sunekaer** [comment]
Issue with changing grave mod at this point, is thatall graves left in the world will be deleted.
Feel free to do this on your instance.

**Comment by Thunder-Nova** [comment]
So it's not possible to have both mods on, and disable the 1st one from working, but still keep the existing graves?
