### ISSUE TITLE
[Bug]: Server Crash

### ISSUE THREAD

**Issue by Bimmr** [FTBTeam/FTB-Modpack-Issues#1840]
### Modpack

Stoneblock 3

### Modpack version

1.2.0

### Log Files

[https://pste.ch/qezaloceju.pl](https://pste.ch/qezaloceju.pl)

### Describe the bug

Just tried to repeat it and this time there was no crash, but I figure I should still report it just incase.

### Steps to reproduce

Removed Living armour chest from equipment, moved to inventory, and picked up from inventory with the cursor. The only change since the last time I did that was that I applied the "socketed" tome to the armour.
and 

### Expected behaviour

Not to crash?

### Screenshots

Chestplate (If needed):
 ![image](https://user-images.githubusercontent.com/5053870/201239605-a2212311-c863-4db7-9ac0-0fa93d401f02.png)

Flux Network wireless settings (If needed):
![image](https://user-images.githubusercontent.com/5053870/201239669-3a002365-67a5-4fee-abff-48fa0fc14d26.png)

Inventory (If needed): 
![image](https://user-images.githubusercontent.com/5053870/201239979-4df719e2-1d96-401d-a849-d39ce791708f.png)

**Comment by Sunekaer** [comment]
Ill open an issue with flux networks, but idk how much they can do about if you cant replicate it, but we will see.

**Comment by Sunekaer** [comment]
https://github.com/SonarSonic/Flux-Networks/issues/500
