### ISSUE TITLE
[Suggestion]: Cleanup REI

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#1841]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Remove the Inscriber and Advanced Inscriber from JEI, and remove their recipe for the processers as it is confusing people on the discord.

**Comment by Sunekaer** [comment]
Ill hide the Inscriber and Advanced Inscriber, but i wont be removing the recipes for processors in them as it will break peoples setups

**Comment by tyler489** [comment]
Can you hide the processing Recipe in rei as people are confused on how to get the inscriber to make the recipe without tabbing through the create assembly.
