### ISSUE TITLE
[Suggestion]: Adding the mod "Integrated Dynamics" and some of its addons.

### ISSUE THREAD

**Issue by Xiarno** [FTBTeam/FTB-Modpack-Issues#1842]
### Modpack

Stone Block 3

### Mod suggestion

Main mod: https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics

Very useful & important addons that go along with it:
Integrated Crafting: https://www.curseforge.com/minecraft/mc-mods/integrated-crafting
Integrated NBT: https://www.curseforge.com/minecraft/mc-mods/integrated-nbt
Integrated Terminals: https://www.curseforge.com/minecraft/mc-mods/integrated-terminals
Integrated Tunnels: https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels
Integrated Additions: https://www.curseforge.com/minecraft/mc-mods/integrated-additions

**Comment by Xiarno** [comment]
Also, I'm gonna add to the suggestion the addon to the mod too.

I'm not a master at Integrated Dynamics. In fact, I was just starting to learn about it in a previous modpack I was playing. But I'm really starting to realize how powerful and easy it is to be able to do things with it.

These addons to integrated Dynamics make that fact even stronger.

Here are the addons. I'll also edit the main comment to add them.

Integrated Crafting: https://www.curseforge.com/minecraft/mc-mods/integrated-crafting
Integrated NBT: https://www.curseforge.com/minecraft/mc-mods/integrated-nbt
Integrated Terminals: https://www.curseforge.com/minecraft/mc-mods/integrated-terminals
Integrated Tunnels: https://www.curseforge.com/minecraft/mc-mods/integrated-tunnels

**Comment by TSM-EVO** [comment]
I added these mods to my singleplayer playthrough and they fit really well. They didn't seem to break any progression or trivialize any aspect of the core mechanics. You could argue that they provide 'duplication' of available features from other mods in the pack, but I think the additional power they provide to allow advanced automation setups actually fits really nicely with the late-game automation requirements.

**Comment by richie3366** [comment]
To add a layer of iteration-ness, I'd also add Integrated Proxy (https://www.curseforge.com/minecraft/mc-mods/integrated-proxy)

It allows to do everything InteDyn mods does, but to an entire area, block by block.
Currently proposed on 1.18.1, but fully compatible with 1.18.2.

**Comment by Sunekaer** [comment]
Thanks for the suggestion.
Feel free to add them to your own instances, but i have decided to not add them to the pack.
