### ISSUE TITLE
[Bug]: Botania Enchanter Multiblock becomes invalid when "twerking" bonemeal effect applied

### ISSUE THREAD

**Issue by Jacksonrox** [FTBTeam/FTB-Modpack-Issues#1843]
### Modpack

Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

Botania's mana enchanter is a multiblock that contains some mystical flowers. When the player shifts and applies a bonemeal affect to the flowers and the flowers grow into their tall variants, the structure is no longer seen as valid and must be re-made. Flowers with a block over them will not grow so 6/10 flowers are safe from this. The remaining 4 can easily have a block placed above so it is by no means game-breaking.

### Steps to reproduce

1. Form Botania's Mana Enchanter multiblock (including right-clicking with wand of the forest)
2. Press shift (crouch key) a few times
3. Notice multiblock is no longer valid

### Expected behaviour

The multiblock shouldn't fail

### Screenshots

![2022-11-10_21 40 02](https://user-images.githubusercontent.com/117960403/201251178-ff569b71-cb08-4897-9159-aa61bb94ce76.png)
![2022-11-10_21 40 14](https://user-images.githubusercontent.com/117960403/201251179-1975ca13-1e35-47d5-9902-c96340516122.png)

### Additional information

I don't know if this is a bug, per se, but it is 2 mods interacting in a presumably unintended way

**Comment by tyler489** [comment]
This happens with vanilla botania if you bonemeal the flower,

**Comment by Jacksonrox** [comment]
> This happens with vanilla botania if you bonemeal the flower,

Naturally. But this interaction is frequent, accidental, and... bothersome.

**Comment by Thorton101** [comment]
hello also here, 
as a workaround: try flowing botania flowers around the enchanter, they won't grow.

**Comment by Sunekaer** [comment]
Technically not a bug, i can see this is annoying if you accidentally shift around the plants.
Try Thorton101's workaround
