### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Slowbob87** [FTBTeam/FTB-Modpack-Issues#1845]
### Modpack

Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

Was pushing a tunnel out to the nether when a loot bee spawned and dropped a chance cube so figured why not open it while I am not close to my base. Spawned a mimic boss fight with the glass dome was a zombie that wasn't to hard to kill and now that i have killed it i can't leave the arena at all nothing else spawned cleared the area and found nothing...

### Steps to reproduce

open a chance cube and get a boss fight and kill the boss and see if you get stuck in the arena?

### Expected behaviour

figured i share incase it hasn't been reported

**Comment by Raidobw2** [comment]
Did `/ftbstoneblock home`, `/home` or `/spawn` allow you to return to your home or were you completely stuck in that glass dome?

**Comment by Sunekaer** [comment]
You should just be able to break the dome?

**Comment by Slowbob87** [comment]
So i made a mistake and ended up changing the spawn point to inside the dome so the commands didn't work for me. And when i broke the dome i am still stuck inside what would be the arena/aka dome area.

**Comment by NordicGamerFE** [comment]
@Slowbob87 /ftbstoneblock home should still bring you to your cave.
