### ISSUE TITLE
[Suggestion]: SPONGES

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#1847]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Make Sponges Craft able as alot of chance cubes seem to like spawning a large quantity of water.

**Comment by Sunekaer** [comment]
![billede](https://user-images.githubusercontent.com/18720460/201535239-acc28476-bd51-4179-8c56-6cd0d3ff553c.png)
