### ISSUE TITLE
[Suggestion]: liquids eggs from chickens usable directly.

### ISSUE THREAD

**Issue by convict-vx** [FTBTeam/FTB-Modpack-Issues#1848]
### Modpack

FTB stoneblock 3

### Is your suggestion related to a problem? Please describe.

Can we please get water and lava eggs to be used directly without using them first to make a bucket of said liquid? 
For example the dielectric paste uses lava bucket in the recipe but can it be unified so a lava egg would count too?

I guess i mean to ore-dict / forge-tag the lava egg also to minecraft:lava_bucket?

**Comment by Sunekaer** [comment]
Its sadly not as easy as just slabbing a tag on it as the item is using NBT.
I have one solution, but that will make so if you click show uses on lava egg youll also see the uses for water egg tho
