### ISSUE TITLE
[Bug]: Ways to obtain crude oil

### ISSUE THREAD

**Issue by Tha06** [FTBTeam/FTB-Modpack-Issues#1849]
### Modpack

FTB University 1.16

### Modpack version

1.7.0

### Describe the bug

There some problem with the crude oil, it did not generate in the world and there no other way to get some. So it's complicate t move forward with Pneumatiqua

### Steps to reproduce

1, Check the crude oil recipe
2. Try to find some in the overworld (there is not)

### Expected behaviour

I expecte that there is a recipe ad for the curde oil or generation of it in the overworld

**Comment by UnRealDinnerbone** [comment]
Crude Oil can be purchased from the Amadron Tablet
