### ISSUE TITLE
[Bug]: Quivers do not go into armory cabinet

### ISSUE THREAD

**Issue by Jacksonrox** [FTBTeam/FTB-Modpack-Issues#1850]
### Modpack

Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

When automating storage for a mob farm, quivers, despite being non-stackable, are not accepted into the cabinet. (from supplementaries) 

### Steps to reproduce

1. Pipe quiver into armory cabinet
2. Notice it does not go in

### Expected behaviour

Quiver goes into it

### Additional information

Armory cabinet doesnt link to controller but that may be as intended...

**Comment by Sunekaer** [comment]
https://github.com/Buuz135/FunctionalStorage/issues/new

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
