### ISSUE TITLE
[Bug]: Quiver doesn't render when in Functional Storage Drawers

### ISSUE THREAD

**Issue by Jacksonrox** [FTBTeam/FTB-Modpack-Issues#1851]
### Modpack

Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

When placed in a drawer, the quiver does not show a preview. The drawer looks empty except for the one (1) indicating the number.

### Steps to reproduce

1. Place a quiver in a drawer

### Expected behaviour

Should show the quiver's model

### Screenshots

![2022-11-10_23 35 26](https://user-images.githubusercontent.com/117960403/201264922-7d13c9fd-2118-4674-a973-d52ef0e5912d.png)

**Comment by Sunekaer** [comment]
Combining with issue https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1851
