### ISSUE TITLE
[Bug]: Computercraft modem doesn't stay connected when linked to linked entangle block and world closes.

### ISSUE THREAD

**Issue by xikamuix** [FTBTeam/FTB-Modpack-Issues#1853]
### Modpack

Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

When placing Computercraft modems on linked entangled block or entangling the modem itself and running cable to it and server restarts or closes by any other mean or if you close singleplayer world the modem doesnt recognize the entangled block and disconnects modem.

### Steps to reproduce

Entangle a block like drawer with entangled binder and connect it to entangled block.
Put modem next to entangled block.
Make sure you have "network" so you can connect and disconnect modem from it by right clicking.
Turn the modem(-s) on.
Log out of singleplayer / close server.
Red light on modem, showing connection, should now be turned off when logging back in to the world.

### Expected behaviour

Modem stays connected, and codes keep running 

### Screenshots

![image](https://user-images.githubusercontent.com/48416339/201270389-ce1ae84e-bc1f-4672-b069-6d4942220e32.png)

![image](https://user-images.githubusercontent.com/48416339/201274916-b0d2171d-44d9-47ce-ace6-795a3ba990d0.png)

**Comment by Sunekaer** [comment]
Im going to say this is the same issue as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1724 just CC instead of pipes
