### ISSUE TITLE
[Bug]: Rendering Entity Crash Caused by Vanilla Mob

### ISSUE THREAD

**Issue by checkm822** [FTBTeam/FTB-Modpack-Issues#1855]
### Modpack

FTB Academy 1.16

### Modpack version

1.2 because 1.3 caused the same crash

### Log Files

https://pastebin.com/Zdj4cJYY
https://pastebin.com/S8hpZc94

### Describe the bug

When a certain vanilla entity is loaded in, it crashes the game.
First it was when a bat was loaded, then it was when a cod fish was loaded.

### Steps to reproduce

1 Enter within range of a problematic entity to spawn
2 Crash

### Expected behaviour

The entity loads and I continue on my merry way

### Additional information

I downgraded versions of the mod to see if that would help. It did for a while but then I found an ocean (which contains cod) and instantly crashed.

**Comment by checkm822** [comment]
Update: I optimized the world file, deleted some mods, and got back into the game for a whole minute. Then it crashed trying to render a vanilla cow.

**Comment by Raidobw2** [comment]
Are there any added mods, and can you try removing the `Hats-1.16.5-10.3.3.jar` file in the `mods` folder to see if that stops the crashes? Thanks
