### ISSUE TITLE
[Bug]: Discord Rich Presence display as garbled texts in Traditional Chinese

### ISSUE THREAD

**Issue by StarskyXIII** [FTBTeam/FTB-Modpack-Issues#1856]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

Because https://github.com/nanite/Simple-Discord-Rich-Presence/commit/d48be94e8e1bf143d215ad5708a61b4cb2730fb5 
So players which switch game language to Traditional Chinese, will always see the garbled texts in there Discord Rich Presence.

### Steps to reproduce

1. Lauch the modpack
2. See Discord Rich Presence

### Expected behaviour

Display Traditional Chinese texts corrently

### Screenshots

![garbled text](https://user-images.githubusercontent.com/71606873/201294333-96d15255-8e95-479b-be4d-af5091741f17.png)

**Comment by Sunekaer** [comment]
Hmm this works fine in my testing, so im not sure whats causing the issue, still trying to find out how to recreate the issue
![billede](https://user-images.githubusercontent.com/18720460/203778279-785ddca4-6df1-47e1-aac3-ff1790288cbb.png)
![billede](https://user-images.githubusercontent.com/18720460/203780196-dfb1698b-f11e-4719-a1ee-c0c5ab89b0c1.png)
