### ISSUE TITLE
[Bug]: Twerking at Botania Flowers

### ISSUE THREAD

**Issue by DerMikele** [FTBTeam/FTB-Modpack-Issues#1857]
### Modpack

Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

Twerking at or running around a botania flower makes it grow into a large botania flower disrupting the mana enchantment all the time

### Steps to reproduce

1. place botania flower
2. twerk at it

### Expected behaviour

Not growing into a large botania flower

**Comment by Thorton101** [comment]
Hello,
reading this. I suggest a workaround: 
use around the enchanter flowing botania flowers?
They should not grow.
