### ISSUE TITLE
[Bug]: Server crashing on breeding some particular chicken

### ISSUE THREAD

**Issue by SuperMake** [FTBTeam/FTB-Modpack-Issues#1859]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.1

### Log Files

https://pastebin.com/3Ep9nkTJ

### Describe the bug

After removing the chicken mod because my client crashed every time I tried to log in, I have the problem that there are 11 chickens that dont have an icon anymore and every time I try to breed one of them the whole server crashes over and over. 

### Steps to reproduce

Join server
Get one of the 11 chickens without an icon
Try to breed
Crash

### Expected behaviour

The server shouldn't crash when breeding one of them.

### Screenshots

![k7lhkA7](https://user-images.githubusercontent.com/14853454/201340540-947db99e-cb67-497a-b9ec-d6a4b0e26fa6.png)

### Additional information

No problems in single player. No missing icons and neither a problem to breed the chickens. The missing chickens are ore chickens like osmium, tin, copper, zinc, netherite etc.

**Comment by tyler489** [comment]
I wonder if those are added by data pack or something, You readded the chicken mod right?

**Comment by SuperMake** [comment]
Yes, I also reinstalled the whole server and just added the backup of the world.

**Comment by Anzulo1984** [comment]
You need the backup of world before you removed the chicken mod, the breeder is causing the crash, i guess your world and backup is corrupted

Try downgrade to 1.2.0 (both server and client), with at least 2 previous backups and check if that works

**Comment by Sunekaer** [comment]
Seems like you were missing the config file or something like that for the mod
All chickens are done via config/chickens/chickens.json

**Comment by SuperMake** [comment]
> Seems like you were missing the config file or something like that for the mod All chickens are done via config/chickens/chickens.json

I replaced the config file and it works perfectly now. Thank you!

**Comment by Sunekaer** [comment]
Your welcome :)
