### ISSUE TITLE
[Bug]:  Mk 4 power pots nuke FPS 

### ISSUE THREAD

**Issue by Spyder1369** [FTBTeam/FTB-Modpack-Issues#186]
### Modpack

Oceanblock

### Modpack version

1.5.0

### Describe the bug

After a few different set ups the power pots seem to tank my FPS to single digits im using around 20 of them in the current set up I have player sims using phyto-gro on them. as soon as they run out of power FPS pops back up, I will do a little testing to see if fewer pots cause issues and if the player sims are the real culprit. Oh and the FPS drop seemed global it was affecting me away from the chunks with the pots and about 50 or so blocks above. 

### Steps to reproduce

Place multiple power pots and player sims up and the FPS should go down. 

### Expected behaviour

Using the Mk4 power pot should not tank global FPS.

**Comment by Sunekaer** [comment]
Function of bonemeal use on power pots has been disabled in update.
