### ISSUE TITLE
[Bug]:Cannot use infinity water upgrade on quantum tank

### ISSUE THREAD

**Issue by No-steve** [FTBTeam/FTB-Modpack-Issues#1862]
### Modpack

ftb sky odyssey

### Modpack version

v1.4.1

### Describe the bug

As the title says 

### Steps to reproduce

bug

### Expected behaviour

bug fixes

### Additional information

Quantum storage mod

**Comment by manmaed** [comment]
Please provide the log files and some simple steps to reproduce the issue you are having and update to 1.4.2 to see if this issue has been fixed
