### ISSUE TITLE
[Bug]:Distillation tower not craftable

### ISSUE THREAD

**Issue by No-steve** [FTBTeam/FTB-Modpack-Issues#1864]
### Modpack

ftb ultimate 1.4.7

### Modpack version

v1.1.2

### Describe the bug

recipe bug

### Steps to reproduce

bug

### Expected behaviour

Bug fixes

### Screenshots

Expected behaviour
![2022-11-12_00 09 32](https://user-images.githubusercontent.com/105639186/201370256-cad53083-9a45-40dc-ab76-49da99416a28.png)
actual behaviour
![2022-11-12_00 09 23](https://user-images.githubusercontent.com/105639186/201370448-b90a6b82-aa24-43eb-98b6-f643f3515cd0.png)

### Additional information

The industrial centrifuge displayed in NEI is non-existent block

**Comment by moody69420** [comment]
y did u type "end" in search?

**Comment by No-steve** [comment]
It doesn’t matter

**Comment by manmaed** [comment]
This i an old mod pack and is unlikely to get updated added @Raidobw2 if he gets time (1.4.7)
