### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by Bloodshadow14** [FTBTeam/FTB-Modpack-Issues#1867]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Some of the mod, that i suggested are very in need in my opinion fo automation some mods or encrase speed of work automation  
And some i want to see in modpack, becuase there isn't much interesting content

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks -mostly cool mod for backpacks, yeah it has some dupes but there is 
https://www.curseforge.com/minecraft/mc-mods/extra-pockets
or
https://www.curseforge.com/minecraft/mc-mods/useful-backpacks 
(even though all of them  are better than simply)
refined storage
https://www.curseforge.com/minecraft/mc-mods/extrastorage - more faster auto crafters  and some other staff
https://www.curseforge.com/minecraft/mc-mods/creative-crafter - INFINITY fast crafter - it's what we need for 10000000000000 EMC
https://www.curseforge.com/minecraft/mc-mods/creative-disk - and infinity storage for all items of course
https://www.curseforge.com/minecraft/mc-mods/creative-wireless-transmitter - and very fast acces for system 
https://www.curseforge.com/minecraft/mc-mods/rs-requestify - it's verey in need thing for global crafts
https://www.curseforge.com/minecraft/mc-mods/extra-disks - only 64k Disks? Really? more comfortable to craft infinity and forgot about storage overflow
https://www.curseforge.com/minecraft/mc-mods/cable-tiers - faster delivery and collection of items from storage
others
https://www.curseforge.com/minecraft/mc-mods/angel-ring - creative fly is very inneed in endgame 

Botania

**Comment by Sunekaer** [comment]
Please search the issues before suggesting 90% has already been decided

**Comment by 5ully** [comment]
more like 99% 👀

**Comment by Bloodshadow14** [comment]
> Please search the issues before suggesting 96% has already been decided

I searched mostly  all bugs amd suggesttions taged stoneblock 3 or with   with it's mention 
so what the problem? i missed the post than you said that most of this mods will be NOT added? if yes, sorry
