### ISSUE TITLE
[Bug]: Can't accept FTB Teams invite

### ISSUE THREAD

**Issue by stalmocan** [FTBTeam/FTB-Modpack-Issues#1868]
### Modpack

FTB StoneBlock3

### Modpack version

1.2.1

### Describe the bug

I invited my friend to join my FTB team but when he tries to accept the invitation he just gets an error message.

He then tried to use the command "/ftbteams party join [PartyName]" directly but it's as though the command doesn't exist anymore.
![image](https://user-images.githubusercontent.com/22631511/201392602-abff759c-5efe-4c9c-890c-e2af1d962114.png)

### Steps to reproduce

1. Player A invites Player B to their FTB team
2. Player B tries to use the UI to accept the invitation
OR
2. Player B tries to type in the command "/ftbteams party join <PlayerAPartyName>"

### Expected behaviour

Player B manages to join Player A's FTB party

### Screenshots

![image](https://user-images.githubusercontent.com/22631511/201392505-153356a3-a1b2-4514-802f-891d22ed3b8a.png)
![image](https://user-images.githubusercontent.com/22631511/201392602-abff759c-5efe-4c9c-890c-e2af1d962114.png)

**Comment by Anzulo1984** [comment]
I got the same bug when i invited someone wh had a party already, he needs to leave his own party and then you can send him a reinvite

**Comment by MichaelHillcox** [comment]
You need to leave your current team
