### ISSUE TITLE
[Bug]: Can't start modpack

### ISSUE THREAD

**Issue by Devilaux** [FTBTeam/FTB-Modpack-Issues#1869]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Log Files

https://paste.atlauncher.com/view/0ea0a5bc-76b1-4a6f-a1ba-8079b5a73653

### Describe the bug

Can't open the modpack suddenly. Won't start, ATLauncher minimizes (as usual), then pops back up again after 10 seconds, with the log above.....

### Steps to reproduce

click "play" on the modpack, in ATLauncher.

### Expected behaviour

Start modpack

**Comment by Raidobw2** [comment]
Please try with the FTB App and let me know if it works or not, thanks

**Comment by Devilaux** [comment]
> thanks

I'm using ATLauncher, not Ftb app. So thanks, but no thanks. I fixed it myselp by removing MiningTohether mod and fml config.
