### ISSUE TITLE
[Suggestion]: Give bred 1/1/1 chickens EMC 

### ISSUE THREAD

**Issue by baueko** [FTBTeam/FTB-Modpack-Issues#1870]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Bred 1/1/1 chickens do not stack with crafted ones because the crafted ones have an EMC value and the bred ones don't (e.g. breeding red with sand to get redstone but you get red/sand 1/1/1).

I suggest that the resulting 1/1/1 chickens are the same ones you get from crafting.

**Comment by richie3366** [comment]
I am 100% sure it is not the reason. The reason is that crafted ones have only 1 NBT tag (their chicken-type), but the bred ones have three other NBT values (their 3 stats set to 1/1/1)

But **there is clearly a stacking issue** that could be solved by specifying their basic stats in the crafting output NBT.

I've already done it here to ease the dev's work:
```javascript

  const chickens = [
    {
      input: "minecraft:flint",
      output: Item.of(
        "chickens:chicken_item",
        '{ChickenType:{id:"chickens:flint_chicken"},gain:1,growth:1,strength:1}'
      ),
    },
    {
      input: "minecraft:sand",
      output: Item.of(
        "chickens:chicken_item",
        '{ChickenType:{id:"chickens:sand_chicken"},gain:1,growth:1,strength:1}'
      ),
    },
    {
      input: "#minecraft:logs",
      output: Item.of(
        "chickens:chicken_item",
        '{ChickenType:{id:"chickens:log_chicken"},gain:1,growth:1,strength:1}'
      ),
    },
    {
      input: "minecraft:soul_sand",
      output: Item.of(
        "chickens:chicken_item",
        '{ChickenType:{id:"chickens:soulsand_chicken"},gain:1,growth:1,strength:1}'
      ),
    },
    {
      input: "minecraft:quartz",
      output: Item.of(
        "chickens:chicken_item",
        '{ChickenType:{id:"chickens:quartz_chicken"},gain:1,growth:1,strength:1}'
      ),
    },

    {
      input: "#forge:dyes/green",
      output: Item.of(
        "chickens:chicken_item",
        '{ChickenType:{id:"chickens:green_chicken"},gain:1,growth:1,strength:1}'
      ),
    },
    {
      input: "#forge:dyes/blue",
      output: Item.of(
        "chickens:chicken_item",
        '{ChickenType:{id:"chickens:blue_chicken"},gain:1,growth:1,strength:1}'
      ),
    },
    {
      input: "#forge:dyes/red",
      output: Item.of(
        "chickens:chicken_item",
        '{ChickenType:{id:"chickens:red_chicken"},gain:1,growth:1,strength:1}'
      ),
    },
    {
      input: "#forge:dyes/black",
      output: Item.of(
        "chickens:chicken_item",
        '{ChickenType:{id:"chickens:black_chicken"},gain:1,growth:1,strength:1}'
      ),
    },
    {
      input: "#forge:dyes/yellow",
      output: Item.of(
        "chickens:chicken_item",
        '{ChickenType:{id:"chickens:yellow_chicken"},gain:1,growth:1,strength:1}'
      ),
    },
    {
      input: "#forge:dyes/white",
      output: Item.of(
        "chickens:chicken_item",
        '{ChickenType:{id:"chickens:white_chicken"},gain:1,growth:1,strength:1}'
      ),
    },
  ];
```

I tested it successfuly in 1.2.1

**Comment by moody69420** [comment]
u should also be able to place them and pick em back up to get the rest of the nbt tags

**Comment by richie3366** [comment]
@moody69420  (if I understand your comment correctly) Unfortunately, the NBT tags that are set on pickup are ticktimes related to their next egg &/or breed cooldown. There is a very small probability that you can catch two chickens having identical NBT. There is nothing we can do to allow them to stack after placing them.

**Comment by baueko** [comment]
But do you need the next egg and breed cool down when you pick up a chicken? Couldn't you just reset it on picking it up (so when it gets placed down it just starts from the default/max value again)?
