### ISSUE TITLE
[Suggestion]: Um....  some automatization speed and automatize mods problems and small quantity of content

### ISSUE THREAD

**Issue by Bloodshadow14** [FTBTeam/FTB-Modpack-Issues#1871]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

i have a list of mods (i checked  again and they haven't been suggested to stoneblock 3 ) 
Because there isn't much contnet and useful block as it can be 
But mostly RS is very slow without addons  and i can't automatize botania without botanical machinery , as it will cause only more lags and will be not so effective

### Mod suggestion

(i would copy mods there if i have answer why i neede to check all the issues - sorry i only play modpack and don't check all the  forum to before do a suggestion)

**Comment by tyler489** [comment]
The extra storage addon for faster and larger crafter have been rejected a few times
#1599 $1633 #1715 #1788 #1810

However I haven't seen the botanical addons request.
https://www.curseforge.com/minecraft/mc-mods/botanical-machinery

**Comment by Bloodshadow14** [comment]
> The extra storage addon for faster and larger crafter have been rejected a few times #1599 #1633 #1715 #1788 #1810
> 
> However I haven't seen the botanical addons request. https://www.curseforge.com/minecraft/mc-mods/botanical-machinery

it's very interesring but i need to craft much thing and what should i use ? EMC ? mostly haven't  the driwer speed is VERY slow  big schemes  using them can be compacted with  a couple of mods not hundred  we have new cells in ae but there isn't any at RS 
i remember stoneblock  (mostly 2 ) as an idea to complect A LOT OF mods at one roof in limited conditions
now i see very boring modpack  with fast gettting much resources very lazy end and NOTHING new
stoneblock at his time give much experience for people with new mods and crafts  but this is only parasite on the idea 
you farm some resources build auto hammers and other things for first breed chickens and wow you have much resources just build big block of autocrafters and wait for hours then your ifinity ingot would craft
oh of course  avaritia - ONLY AVARITIA CRAFTS  - you are serious ?  nothing creative only another cosmic set with another craft  and NOTHING chanded... oh sorry new sigularities -  WOW how interesting
and yeah if it released earlier with more mods it would be interesting but this.... i am  upset after Beutiful oceanblock and inferno
..... no insults only my imho

**Comment by Bloodshadow14** [comment]
So without any explanation why they couldn't be added  we need to add them by ourselves  without any chance that conflicts with them could be fixed - I don
"I looked through them all and decided to add only  Rs infinity booster " Okay you checked the mods but they were added to ocean block and inferno - so what is problem to add them to modpack? 
You didn't say any reason why this  mods couldn't be added and after it you add AE2things - it's looking like a digital storage system racism ( don't be so serious it's only figure of speech) 
Add yeah modpack is very fast to go through and after ocean block stoneblock 2 it looks like laziness to make modpack more interesting as only change some craft components in avaritia and don't add any crafts for creative items
