### ISSUE TITLE
[Bug]: searching for ender tank uses crashes game

### ISSUE THREAD

**Issue by gman4161** [FTBTeam/FTB-Modpack-Issues#1872]
### Modpack

Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

searching for ender tank uses, pressing u in REI, etc. crashes the game. 

### Steps to reproduce

open a world
press u on ender tank
crash

### Expected behaviour

game shouldn't crash

**Comment by tyler489** [comment]
Crash report?

**Comment by Raidobw2** [comment]
This seems like a duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1574, so I'll close it to avoid tracking the same issue twice
