### ISSUE TITLE
[Suggestion]: Alternitive Recipe for temporal pouch

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#1875]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Gadgets against Grind Temporal pouch is designed to accumulate time passively and consume that time to speed up other blocks, In this pack it takes a nautilus shell which requires full progression through mekanism's antimatter to get. Consider making the recipe earlier for beginning players.

**Comment by Xiarno** [comment]
Wandering trader can sell it.

**Comment by EeveeTC** [comment]
You can fish up nautilus shell, aka use marine fisher.
Alternatively, the drowned spawner in the stone dungeon have a chance to spawn with nautilus shell in their hand, which drop guaranteed.

**Comment by Sunekaer** [comment]
As they peeps above said, there is multiple other ways to get the shell
