### ISSUE TITLE
[Bug]: Dark Matter Pedestal

### ISSUE THREAD

**Issue by masDO1337** [FTBTeam/FTB-Modpack-Issues#1876]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.0

### Describe the bug

It is impossible to break the dark matter pedestal

### Steps to reproduce

1. Place the dark matter pedestal
2. try to break it

### Expected behaviour

like a bedrock

**Comment by IThundxr** [comment]
not a bug u can break it with a dark matter pick or use a cardboard box

**Comment by Nibble-Byte** [comment]
@masDO1337 you should close this one yourself to save the devs the hassle :)
Also, if you dont have a dark matter/red matter pick, you can move the pedestals with a cardboard box from mekanism.

**Comment by masDO1337** [comment]
Thanks! 😀👍🏻
