### ISSUE TITLE
[Suggestion]: Give lava egg more uses and make it basically a lava bucket

### ISSUE THREAD

**Issue by IThundxr** [FTBTeam/FTB-Modpack-Issues#1877]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Basically lava egg being a lava bucket would be very nice since we wont need to make lava bucket

### Mod suggestion

Basically make the lava egg a valid furnace fuel item and change recipes using lava buckets to use a tag which has both lava bucket and lava egg

**Comment by Sunekaer** [comment]
Duplicate of #1848
