### ISSUE TITLE
[Bug]: sneaking for fast growing yellow dock Bush from Hexerei crashes the game

### ISSUE THREAD

**Issue by CalvoMamao** [FTBTeam/FTB-Modpack-Issues#1878]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

I mutated and oak log with mutandis and became yellow dock Bush, but when i sneak to fast grow It the Game just crashes.

### Steps to reproduce

1. Plant a yellow dock Bush in a dirt block
2. Sneak to accelerate growth

### Expected behaviour

Expected the Bush to fast grow normally

**Comment by rmedzihradsky** [comment]
This happens with all Hexerei plants and was reported in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1372

**Comment by Raidobw2** [comment]
Thanks for reporting, but I'll be closing this to avoid the modpack developers to track two of the same issue
