### ISSUE TITLE
[Bug]: SoulShard recipe display missing

### ISSUE THREAD

**Issue by Kangy1103** [FTBTeam/FTB-Modpack-Issues#1881]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

The recipe for SoulShards is missing some graphics

### Steps to reproduce

1. Press R on Soul Shard from Soul Shards
2. See recipe missing graphics key to crafting item

### Expected behaviour

Graphic appears correctly

### Screenshots

<img width="535" alt="image" src="https://user-images.githubusercontent.com/42292756/201447523-f6cdd739-c0e1-4c5f-8f66-024d1a4d6f4a.png">

**Comment by Sunekaer** [comment]
https://github.com/shedaniel/RoughlyEnoughItems/issues/1221

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
