### ISSUE TITLE
[Bug]: kubejs/champions mode causing lag

### ISSUE THREAD

**Issue by i9xgit** [FTBTeam/FTB-Modpack-Issues#1882]
### Modpack

ftb stoneblock 2

### Modpack version

1.2.1

### Log Files

https://spark.lucko.me/apRP2AWOjS

### Describe the bug

kubejs/champions mode is completely destroying servers. its crashing/lagging people out constantly

### Steps to reproduce

idk man

### Expected behaviour

not crash

**Comment by Raidobw2** [comment]
Do you have a bit more information about the issue? Lag problems are hard to figure out...
- Logs please
- Ctrl + U in-game to bring up the crash utilities menu and check the amount of loaded entities
- Setting the game to peaceful to compare performance
- Removing the `kubejs/server_scripts/_core/harderdungeons.js` script and typing `/reload` in the server console

If you think anything else would be useful for us to debug this case, feel free to add it here as well. Thanks!

**Comment by i9xgit** [comment]
ill give the 4th option a try ill let you know if anything changes, i dont have the logs anymore due to this being 2 days ago but spark specificlaly mentioend champions/kubejs and something else
