### ISSUE TITLE
[Bug]: Refined Storage Fluid Storage Parts have EMC

### ISSUE THREAD

**Issue by Nibble-Byte** [FTBTeam/FTB-Modpack-Issues#1884]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

It seems unintended to me, as everyother AE2 and RS storage component does not have EMC.
But the 64k Fluid parts from RS do.

### Steps to reproduce

1. Open the pack.
2. Search REI for `@refined 64k fluid`
3. See that all 3 items have emc values.

### Expected behaviour

I would expect that these parts do not have emc.

### Screenshots

![image](https://user-images.githubusercontent.com/38148177/201451576-31012d31-43be-4f18-a778-1fc7aad11332.png)

![image](https://user-images.githubusercontent.com/38148177/201451581-3a22f7e0-bb60-4dd9-b227-d09bd2c24f7c.png)

![image](https://user-images.githubusercontent.com/38148177/201451642-0241e0ba-ec27-4601-8562-fc612aa1ea00.png)

### Additional information

This isnt exactly game breaking, but just strange that out of all the storage parts from these two mods, this was the only one with EMC.

**Comment by richie3366** [comment]
The reason is simple: all of their ingredients have EMC, just like 1k storage part (RS), which has EMC too.

**Comment by richie3366** [comment]
I hope my explanation resolved the "issue" you experienced.

If I may quote yourself in another issue
> you should close this one yourself to save the devs the hassle :)
