### ISSUE TITLE
[Bug]: Inventory trash slot missing

### ISSUE THREAD

**Issue by ebingamer** [FTBTeam/FTB-Modpack-Issues#1885]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.1

### Describe the bug

Whenever I use E to open my inventory, I can't see the trash slot in the bottom right. However, I can see the slot when I open the crafting menu (either by crafting stick or crafting table) and when I open a chest. There may be other places it appears that I'm not aware of. I remember the trash slot showing properly in 1.1.0 or 1.1.1, I'm not sure. I know I could use the trash icon in the top left, but the one in the inventory screen is more convienient.

### Steps to reproduce

1. Open inventory/machine
2. Try to throw away junk
3. Realise the inventory trash slot is missing
4. Cry

### Expected behaviour

I expect to have a trash slot in the bottom right of the inventory menu whenever the inventory is displayed

### Screenshots

The Enrichment Chamber isn't the only machine that doesn't show the slot, every machine that I have doesn't show it.
![image](https://user-images.githubusercontent.com/43820104/201451942-692cd983-fa5a-4550-933b-d466a74c4d62.png)

Inventory screen:
![image](https://user-images.githubusercontent.com/43820104/201451955-b1d390dc-4609-4d9e-a775-0fde41607553.png)

Minecraft chests (shown) and barrels work, but drawers don't work
![image](https://user-images.githubusercontent.com/43820104/201451970-12ce5762-3b15-496a-a3ef-158df24fc8d5.png)

This is with the stone crafting table, but the crafting stick works as well
![image](https://user-images.githubusercontent.com/43820104/201451974-829420cd-06a8-4655-b3f8-34dfc33436fa.png)

The trashcan in the top left shows it, but its floating (?)
![image](https://user-images.githubusercontent.com/43820104/201452240-f48bfadb-eca1-40f6-a5cd-a3c3b9bbe88c.png)

**Comment by Xiarno** [comment]
Press `T` by default to show/hide it.

**Comment by ebingamer** [comment]
> Press `T` by default to show/hide it.

Cheers. Seems weird it would still show in other places though.

**Comment by Xiarno** [comment]
> > Press `T` by default to show/hide it.
> 
> Cheers. Seems weird it would still show in other places though.

Tbh I have no idea why sometimes it shows by default and others not. What I do know is that generally, it remembers if you disable it & enable it.
