### ISSUE TITLE
[Bug]: Flint Pickaxe quest not recognizing crafted pickaxe.

### ISSUE THREAD

**Issue by LynchMatias** [FTBTeam/FTB-Modpack-Issues#1886]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

I started two separate worlds and in both cases when I crafted the flint pickaxe the quest never recognized it. I had to use commands to set it as completed.

### Steps to reproduce

Start world
Complete first info quests
Craft flint pickaxe
Check questbook

### Expected behaviour

The quest counts as completed.

**Comment by orbidlo** [comment]
This quest is legit cursed.

**Comment by Shinino** [comment]
Workaround:  Create Tinker's Construct crafter/part maker and make it in that.
