### ISSUE TITLE
[Bug]: Rainbow Furnace, fully linked & fueled doesn't generate 10k rf/t

### ISSUE THREAD

**Issue by Nekosity12** [FTBTeam/FTB-Modpack-Issues#1888]
### Modpack

FTB Stoneblock 3

### Modpack version

1.20

### Describe the bug

The Rainbow Furnace says it can generate 10k rf/t when it is fueled & every other furnace is fueled and linked to the rainbow furnace. Well I did this and when I went to put in an infinity range upgrade for my refined storage system (consumes 4k rf/t) it was definitely not producing anywhere near 10k rf/t and I quickly ran out of power.

I'm confident it was fully linked and my friend even re-linked them to double check.

### Steps to reproduce

1. Create a rainbow furnace
2. Create all 9 furnaces (silver, iron, copper, gold, emerald, netherite, obsidian, crystal, diamond)
3. Fill them all with generator upgrades
4. Use a rainbow linker to link the furnaces to the rainbow generator
5. Fill them all up with coal
6. Hook up the rainbow furnace to something that takes a lot of power but less than 10k (i.e. an RS system with infinite range attached to the wireless torch)
7. Notice it does not produce the power required
P.S. I'm aware I'm not on latest but I didn't see anything in changelogs that would change the behavior and I can't test on latest due to aternos not updating to beta releases & having to wait on a friend to update our VPS to be able to do 1.18 servers

### Expected behaviour

For the rainbow generator to produce 10krf/t

**Comment by tapegreen** [comment]
having the same issue, but on the latest version(1.21). rainbow furnace only produces 1000k rf\t.

**Comment by Xavion3** [comment]
1000k RF/t is the base rate the rainbow furnace produces while not getting the rainbow boost, so that's normal. It just means either you don't have them all linked or they're not all currently running. That or a bug, but the rainbow furnaces work fine when set up correctly for me in single player, so if it's a bug it might be a specific interaction as they're not universally bugged.

**Comment by Nekosity12** [comment]
I mean 1000k is 1M rf/t >~> That or a non existent number. But in any case I've seen multiple people talk about it in the discord not working & I saw no issue posted on github so I posted it. They're 100% linked, as I explained I'm confident they were linked and that my friend even re-linked them to double check

**Comment by Xavion3** [comment]
1000 RF/, copied the typo without thinking.

And yeah, linked and running should be the only requirements. Remember if any of the furnaces fill up they're no longer running, I've seen that mistake before. They need to be actually doing something. Any info is useful though, on a server or single player? How are you ensuring they all stay running? Could it be an issue with the pipes? There's a bunch of options.

Checking if you have enough linked is pretty easy, as the linker tells you how many you still need to link.

**Comment by Nekosity12** [comment]
https://youtu.be/4gco_nGCxmk

Hopefully this video doesn't turn out too choppy. But with all furnaces on AND linked, they (including the rainbow furnace) only produce about 1000/t. You'll see in the video it says 20,000 at one point but that's just because it's going through all of the reserved energy. Once all of it is gone it's about 1000. I also showed myself using the linker on the rainbow furnace and it said "Remaining: 0".

I've tested it with and without blast furnace upgrades and another way to tell I'm not making 10k rf/t is that I had to switch on my clocks just to access my RS system to grab the rainbow linker which my RS system only uses a bit over 4k rf/t. 

I'm on a server, we were originally using aternos but just switched to Sticky Piston & are now updated to 1.21

**Comment by Raidobw2** [comment]
That might be normal, by default it seems to generate 1k per tick:
![image](https://user-images.githubusercontent.com/17010632/202646230-9068e500-6e07-4694-a069-4ea5ed6ca505.png)

I'll mark as enhancement assuming you'd like it to generate more

**Comment by Nekosity12** [comment]
I'd def love to see it generate more! I reported it as a bug because the rainbow furnace states in it's description "Generates 10k rf/t when all furnaces are linked" (I think you have to hold shift or smtg over it? I don't recall exactly) Never thought about checking the config files 😅

**Comment by Nekosity12** [comment]
I thought about commenting that but the config is really confusing. Right below that, it suggests the rainbow generator doesn't generate power unless linked:
"How many furnaces need to be linked in order for the rainbow furnace to generate power"
But then why have a separate setting of 10k power. The only thing I could think of is the rainbow furnace generates 1krf/t but each item lasts for 10k power. So a single coal gets used in 10 ticks to generate 10k power

**Comment by Xavion3** [comment]
The 10k RF/t value is the value when linked and unique to the rainbow furnace, the 1k RF/t value is the value when not linked, and every generator has one. So you can configure both the normal power generation and the power generation while linked.  All furnaces can generate power with a generator upgrade, although the config could be clearer yes. As said, the linking can work and does cause the increased generation, I've gotten it working myself.

Figuring out why it wasn't working for you is still a conundrum though, but you seem to be throttled somewhere on how much power you accept I guess? It's odd, but the nine normal furnaces together should be producing more than 1k RF/t alone, and even an unlinked rainbow should push that total to over 2k RF/t so there's more going on in your setup than just the rainbow furnace not linking properly.

**Comment by Nekosity12** [comment]
Honestly everything should be a-okay, all of the pipes are hooked up with ultimate upgrades and it says it pulls way more rf/t than the furnaces should produce. The weirdest thing is all the furnaces are empty of power, still producing more. So if for some reason the pipes are only sending 1k rf/t to the flux plug where is the excess going? The only thing I can think of is possibly the RS system since I don't believe I disconnected it during the testing (woops) and that drains 4krf/t (but since it wasn't powered it clearly wasn't receiving that much so :shrug:) Unfortunately we're struggling to get the server cooperate (we finally are able to switch back to our personal server instead of using stickypiston or aternos) & my friend who operates the server is really busy irl so I can't access our world to try to do some testing disconnected from my rs system or trying only flux plugs etc

**Comment by Gotsp** [comment]
For me the rainbow furnace says it produces 200K RF/t with all the other ones connected, whilst it only produces 12k for me.
