### ISSUE TITLE
[Bug]: Creative chemical tank not craftable on Oceanblock

### ISSUE THREAD

**Issue by avicuz1142** [FTBTeam/FTB-Modpack-Issues#189]
### Modpack

FTb Oceanblcok

### Modpack version

1.4.1

### Describe the bug

The creative chemical tank is not craftable due to the nbt issues in the recipe, they have 2 nbt tag instead of 1.

### Steps to reproduce

1. Open up ultimate crafting table
2. Attemping to craft creative chemical tank
3. Nbt tag isn't match
4. Unable to craft the item

### Expected behaviour

Creative chemical tank at output slot

### Screenshots

![2021-10-25_20 01 27](https://user-images.githubusercontent.com/89138898/138675916-b0411a21-55b6-4ef7-a9c9-b6ead6ebf666.png)
![2021-10-25_20 01 22](https://user-images.githubusercontent.com/89138898/138675932-a226ecbf-08dc-4d3a-aa6d-906b200e90b6.png)

![2021-10-25_19 51 57](https://user-images.githubusercontent.com/89138898/138676061-8d06aa7c-5309-47d6-83ff-fd552ef98344.png)

**Comment by JackUdeschini** [comment]
Creative storage upgrade also has issues with crafting due to nbt data

**Comment by Raidobw2** [comment]
Sunekaer ^ creative vending upgrade
![image](https://user-images.githubusercontent.com/17010632/140013103-2447de26-b7a1-4344-97f9-92a3498ae131.png)
Might want to use `nbt_ingredient_predicate:nbt_includes` for that nbt
