### ISSUE TITLE
[Bug]: AE2 Too many channels.

### ISSUE THREAD

**Issue by JosephHelland** [FTBTeam/FTB-Modpack-Issues#1891]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

When connecting AE2 Network if I add more than 8 channels to a Dense cable it overloads and says "Too many channels"

### Steps to reproduce

put more than 8 channels on a Dense cable.

### Expected behaviour

32 channels should be carried

### Screenshots

![2022-11-12_02 58 07_2](https://user-images.githubusercontent.com/15934919/201470923-133a8cc2-109a-4d09-a271-4fb7722f8134.png)
![2022-11-12_02 58 29](https://user-images.githubusercontent.com/15934919/201470925-86f756b7-dad8-49ea-b758-01aaa345163b.png)

**Comment by Kangy1103** [comment]
That's a smart cable in your screenshot, not a dense cable. Smart cables can only carry 8 channels

**Comment by JosephHelland** [comment]
yes its attached to a dense cable as you can see just to the right of the smart cable same as a smart cable going up. when that second one is connected it goes from 8/32 on the dense cable to Too many channels, instead of carrying the new 8 channels.

**Comment by JosephHelland** [comment]
Also, apparently the dense cable can carry devices past 8 but not p2p? Ive never seen this behavior and cant find anything related to it on any AE2 wiki or site so I suspect its an issue in the pack.

**Comment by JosephHelland** [comment]
![2022-11-12_04 53 52](https://user-images.githubusercontent.com/15934919/201474914-fce3d56b-0bae-4436-ad92-10be62ec9aee.png)
![2022-11-12_04 54 00](https://user-images.githubusercontent.com/15934919/201474917-ac037419-abbf-4a53-b0a4-6a4002db93b6.png)

**Comment by Kangy1103** [comment]
No that's right as the P2P tunnels have to connect to a normal answer cable making you can only have 8 connected to each branch coming from the dense cable. Once you hit 8 P2P tunnels you'll need to make a separate branch not connected to the original. I'll be home shortly so will fire up a creative works to visualise this for you as I'm not the best at explaining hahaSent from my Galaxy
-------- Original message --------From: JosephHelland ***@***.***> Date: 12/11/2022  12:52  (GMT+00:00) To: FTBTeam/FTB-Modpack-Issues ***@***.***> Cc: Kangy ***@***.***>, Comment ***@***.***> Subject: Re: [FTBTeam/FTB-Modpack-Issues] [Bug]: AE2 Too many channels. (Issue #1891) 
Also, apparently the dense cable can carry devices past 8 but not p2p? Ive never seen this behavior and cant find anything related to it on any AE2 wiki or site so I suspect its an issue in the pack.

**Comment by Kangy1103** [comment]
Scratch my last reply. Mobile didn't show me your additional screenshots Sent from my Galaxy
-------- Original message --------From: JosephHelland ***@***.***> Date: 12/11/2022  12:54  (GMT+00:00) To: FTBTeam/FTB-Modpack-Issues ***@***.***> Cc: Kangy ***@***.***>, Comment ***@***.***> Subject: Re: [FTBTeam/FTB-Modpack-Issues] [Bug]: AE2 Too many channels. (Issue #1891)

**Comment by JosephHelland** [comment]
:) np :D like I said Ive never seen this behavior before its odd. been playing with AE2 for a decade and this is bizzare behaviour.

**Comment by Kangy1103** [comment]
It's almost like it's treating the end of the dense cable like a smart cable. Just out of interest, what happens if you extend the smart cable by 1?

**Comment by Kangy1103** [comment]
Okay, so part way through replicating I noticed something. At this point in the build I had 4 channels coming from the right side of the controller but you have 8. Is there something not seen in the screenshots attached to the dense cable?

<img width="919" alt="image" src="https://user-images.githubusercontent.com/42292756/201475791-6ec11470-8275-478c-a49d-be2e5116710a.png">

**Comment by Kangy1103** [comment]
@JosephHelland Important question as it completely slipped my mind. Do you have a 2nd controller on your P2P network?

**Comment by JosephHelland** [comment]
no, jsut the one core. and yea its p2p on both ends.

**Comment by JosephHelland** [comment]
![2022-11-12_14 12 03](https://user-images.githubusercontent.com/15934919/201496547-bdfc76a6-5428-4ca1-8301-f5abab8f3490.png)

At the opposite end, regular machines take the expected 1 channel. Im baffled why the p2p is erroring.

**Comment by Kangy1103** [comment]
> no, jsut the one core. and yea its p2p on both ends.

You need a 2nd controller on your P2P network to provide the 32 channels to your P2P network. Otherwise you only get the 8 as you would with a basic AE2 setup. I knew we were missing something obvious haha

**Comment by JosephHelland** [comment]
omg shows you what I forget in 8 months lol.
