### ISSUE TITLE
[Bug]: No crafting for Inscriber

### ISSUE THREAD

**Issue by xXZatXx** [FTBTeam/FTB-Modpack-Issues#1892]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.1

### Describe the bug

When I want to look up the crafting of Inscirber using RoughlyEnoughItems, nothing shows up.

### Steps to reproduce

1. Look up Inscriber in RoughlyEnoughItems mod in the inventory.
2. Hover over the Inscriber icon.
3. Press "u" on your keyboard.

### Expected behaviour

Crafting showing up

### Additional information

Every other crafting works so it isn't a problem with key bindings.

**Comment by convict-vx** [comment]
i believe inscribers are disabled, need to make the AE2 circuits with create deployers.

**Comment by tyler489** [comment]
Correct, Inscriber was disabled.

**Comment by NordicGamerFE** [comment]
The Advanced Inscriber still has a recipe it either should be removed to stop confusion or changed, I would still like to see the Advanced Inscriber in the game maybe made with create and some other bits to fit the theme

**Comment by tyler489** [comment]
> The Advanced Inscriber still has a recipe it either should be removed to stop confusion or changed, I would still like to see the Advanced Inscriber in the game maybe made with create and some other bits to fit the theme

#1841
