### ISSUE TITLE
[Bug]: FTB StoneBlock 3 Thermal Evaporation

### ISSUE THREAD

**Issue by OrangeJr** [FTBTeam/FTB-Modpack-Issues#1893]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

there doesn't seem to be a way to use thermal evaporation to get lithium ( mekanism ) 

### Steps to reproduce

1. build thermal evaporation chamber 
2. realize there are no advanced solar generators to complete the multiblock structure

### Expected behaviour

build thermal evaporation chamber insert water, it turns into brine based on the heat generated then take brine into a second thermal evaporation chamber and turn the brine into liquid lithium then put it in a rotary condensentrator and decondensentrate it into lithium(gas) then put it in chemical crystallizer and get lithium dust

### Screenshots

![(step1)thermal evaporation process ](https://user-images.githubusercontent.com/118052411/201471481-b303ddfe-e2e3-45bd-80ff-0862427ada35.png)
![(step2)thermal evaporation process](https://user-images.githubusercontent.com/118052411/201471483-912ff412-afdf-4d25-bc67-c36efc754f40.png)
![(step3)lithium decondenstrating](https://user-images.githubusercontent.com/118052411/201471486-fb516c14-111f-4b15-8287-51a2088566f5.png)
![(step4)lithium dust](https://user-images.githubusercontent.com/118052411/201471488-c1ad738a-c93a-4000-8cc2-fb9ddd3dc005.png)

**Comment by ukmcplyr** [comment]
You need to use a Resistive Heater from Mekanism and give that power. See https://www.youtube.com/watch?v=Be2TimlkL-g for a recent walkthrough from direwolf20.

**Comment by OrangeJr** [comment]
thanks
