### ISSUE TITLE
[Bug]: Emtpy bowls spitting out of farmer's delight cooking pot

### ISSUE THREAD

**Issue by convict-vx** [FTBTeam/FTB-Modpack-Issues#1894]
### Modpack

FTB stoneblock 3

### Modpack version

1.2.1

### Describe the bug

All Farmer's Delight food items that have tomato sauce as an ingredient spits out an emtpy bowl. Not sure if it matters but automated with Refined storage.

pasta with mutton chop
fish stew
Pasta with meatballs

these 3 are confirmed now, maybe other recipes do the same.

### Steps to reproduce

1. setup stove and cooking pot
2. automate fish stew, pasta with meatballs or pasta with mutton chop that require tomato sauce in it.
3. craft either of those
4. wait till finish 
5. see the bowl spit out

### Expected behaviour

not getting an empty bowl out of the pot

**Comment by Sunekaer** [comment]
Can you show me your automation setup? 
So i can replicate it for testing
