### ISSUE TITLE
[Bug]: FTB App Stoneblock 3 won't start

### ISSUE THREAD

**Issue by DayDreamiiing** [FTBTeam/FTB-Modpack-Issues#1896]
### Modpack

Stoneblock 3

### Modpack version

1.2.1

### Log Files

[crash-2022-11-12_14.01.40-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9995029/crash-2022-11-12_14.01.40-client.txt)

### Describe the bug

I played Stoneblock 3 on v1.1.0 before. After updating the Instance it will not start. FTB app says "Instance failure: The instance has crashed or has been externally closed."

### Steps to reproduce

1. Update Stoneblock 3 instance in FTB App to 1.2.1

### Expected behaviour

It should start the instance normally

### Screenshots

![2022-11-12 14_12_35-NVIDIA GeForce Overlay DT](https://user-images.githubusercontent.com/49448869/201475621-63696ccc-6f86-402c-9fd2-ec275ac666d6.png)

**Comment by Raidobw2** [comment]
Remove the MineTogether mod, we're tracking this problem at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1768
