### ISSUE TITLE
[Bug]: Chunk Loading Issues

### ISSUE THREAD

**Issue by expert9480** [FTBTeam/FTB-Modpack-Issues#1897]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

I have been trying to chunk load the Mother Silverfish dungeon and my main base so that stuff that are a both locations can work and send stuff back. I have tried using FTB Chunks for chunk loading and I tried using the Create Chunk loaders but they don't work.

I have noticed that going back to the chunks and manually loading them with my player and then going back keeps the chunks loaded for a bit, then it just stops.

Since I am using a drygmy farm, it is a possibility that it is just entities not being loaded. (There was a chunk loading issue in ATM7 with mob farms, but I think that was resolved.)

### Steps to reproduce

1. Join World
2. Chunk load with FTB Chunks and/or Create Chunk Loader at Location 1
3. Move to Mother Silverfish Dungeon
4. Chunk load with both options
5. Go back to location 1
6. Watch it work for like a few minutes
7. Then the flow of items stops

(This can work the other way, where if you stay at the Dungeon, location 1 will not import items from my enderchest)

### Expected behaviour

The expected behavior is that both sides are chunk loaded without the player being there and the machines and cables are working.

**Comment by Raidobw2** [comment]
Is this to farm the Mother Silverfish using Drygmys? (See https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1771#issuecomment-1309027136)

**Comment by Sunekaer** [comment]
Do you have any mods added to the pack?
What is your setup your using, just so i can test with the same stuff :)
