### ISSUE TITLE
[Bug]: Datapack of FTB stoneblock 3 is preventing the wolrd from creating

### ISSUE THREAD

**Issue by fisherNPC** [FTBTeam/FTB-Modpack-Issues#1898]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10026947/latest.log)

### Describe the bug

I just download the mod pack and started the new world but The screen shows that data pack is preventing the world from creating.

### Steps to reproduce

1. Open the game
2. single player
3. Create the world
4. Screen show datapack prevent the world from creating

### Expected behaviour

I hope that some one can help me out this case because I really want to try this modpack

**Comment by ukmcplyr** [comment]
@fisherNPC your latest.log didn't upload correctly.

**Comment by Raidobw2** [comment]
Can you add your log here again, as ukmcplyr mentioned it's not attached for some reason. Thanks in advance

**Comment by fisherNPC** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10002803/latest.log)

**Comment by fisherNPC** [comment]
Thanks for let me know about my mistake also post my logs in again.

**Comment by Sunekaer** [comment]
Did you add mods to the pack?

**Comment by NordicGamerFE** [comment]
Based on the logs ecologics was added
