### ISSUE TITLE
[Bug]: Steam Engine - Tank shows empty

### ISSUE THREAD

**Issue by realswamo** [FTBTeam/FTB-Modpack-Issues#1899]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

When adding a steam engine to the fluid tank, the tanks show that there is no fluid in them. When I remove the steam engine, it then shows you the amount of water in the tank.

### Steps to reproduce

1. Add tanks
2. Fill with water (shows amounts)
3. Add steam engine
4. The tanks no longer shows the amount and the steam engine doesn't start.

### Expected behaviour

When you fill the tank with water, you can see how much water is in the tank and steam engine starts working.

### Screenshots

![2022-11-12_10 34 26](https://user-images.githubusercontent.com/33209961/201481741-c787e7f7-efe4-4c5e-b4a9-cfb8b8f8b6e4.png)
![2022-11-12_10 34 39](https://user-images.githubusercontent.com/33209961/201481742-2a5f374e-d2f2-4a80-94da-ab6995987791.png)

**Comment by Sunekaer** [comment]
https://github.com/Snownee/Jade/issues/176
