### ISSUE TITLE
FTB Oceanblock - Garden Cloche missing recipes?

### ISSUE THREAD

**Issue by SpankyOnur** [FTBTeam/FTB-Modpack-Issues#19]
Hey.

Was playing the new Modpack "Oceanblock" and after some time i got some Garden Cloches from a reward and so i did try it out with some seeds.

I dont know if it is intended but i can only use some vanilla seeds, some seeds from the mod "Farmer's delight" and the Industrial Hemp seed from the same mod as the Garden cloche.

The "Phytogenic Insolator" can be used with ALL seeds and saplings as far as i see ... so i dont think that this is a kind of nerf.

**Comment by Sunekaer** [comment]
Hi SpankyOnur,

This isnt a nerf, but just how the block comes by default from the mod.
We will look at adding more recipes to the cloche
