### ISSUE TITLE
[Bug]: DarkModeEverywhere affects AE2 only partially making it unreadable

### ISSUE THREAD

**Issue by SaphireLattice** [FTBTeam/FTB-Modpack-Issues#1901]
### Modpack

FTB StoneBlock3

### Modpack version

1.2.1

### Describe the bug

If using dark mode inventory and then opening any AE2 UI, the font will be white, but the background of the AE2 interface is not affected, making it rather difficult to read and use at all

### Steps to reproduce

1. Open any Applied Energistics 2 UI
2. Made sure you have changed dark mode to be on, any setting
3. Observe the unreadable mess

### Expected behaviour

Dark AE2 UI, or font color not being affected

**Comment by Sunekaer** [comment]
https://github.com/Buuz135/DarkModeEverywhere/issues/7

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
