### ISSUE TITLE
[Bug]: Duplication (with Avaritia)

### ISSUE THREAD

**Issue by Hollowlab01** [FTBTeam/FTB-Modpack-Issues#1903]
### Modpack

Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

Duplication bug that allows players to craft and duplicate end game item from the extreme crafting table

### Steps to reproduce

1. Go to the extreme crafting table
2. Fill in the crafting materials for any extreme crafting (eg. Infinity Catalyst) either by manually filling or shift-left-click the "+" button
3. Once the craft item shows, Spacebar-left-click the item and immediately Shift-left-click the craft item

### Expected behaviour

The crafting material will double their stack size on the first spacebar-left-click, and the doubled stack size will double again once shift-left-click, producing exactly 127 items (if the initial craft was meant for 64 items or 1 stack)

**Comment by Raidobw2** [comment]
Hmm, might be linked to https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1747, thanks for reporting

**Comment by Hollowlab01** [comment]
Looks somewhat the same as #1747. Alright no problem

**Comment by phit** [comment]
Yeah I can still reproduce this as well on 1.2.1, #1747 was not fixed.

**Comment by Draradech** [comment]
Can reproduce in 1.3.0.

A simple repro is to fill the table with full stacks, then click the output once. It'll craft one, then duplicate the input stacks.
![2022-11-25_19 11 30](https://user-images.githubusercontent.com/223321/204038876-cff67f87-0068-4c89-94b7-af7765d21d69.png)
![2022-11-25_19 11 32](https://user-images.githubusercontent.com/223321/204038882-bf0a7a4f-10cb-43af-8ff1-bcf71c7a58fe.png)

It also happened to me with non-full stacks when shift-clicking the output, but this one is sporadic :/

**Comment by Draradech** [comment]
https://github.com/Morpheus1101/Avaritia/issues/209

**Comment by brandon3055** [comment]
This build should fix this issue. I would appreciate it if someone who is able to reproduce this dupe could test it.
[Avaritia-1.18.2-4.0.0.1-universal.jar](https://ss.brandon3055.com/ecd1a)

**Comment by Sunekaer** [comment]
Seems to work fine in my instance with newest version of Avaritia
