### ISSUE TITLE
[Suggestion]: Crafting Recipes & Quarry Bees for Create's stone blocks

### ISSUE THREAD

**Issue by tac-owo** [FTBTeam/FTB-Modpack-Issues#1906]
### Modpack

FTB Inferno

### Is your suggestion related to a problem? Please describe.

I'd like to be able to build with Create's different stones. Especially Limestone, but all of them would be nice. Came up with a couple ideas for crafting recipes, they're all similar to the ones for Granite / Diorite / Andesite.

Asurine: 2x Lapis or Blue Dye, 2x Stone = 2x Asurine
Crimsite: 2x Nether Wart Block, 2x Stone = 2x Crimsite
Limestone: 2x Stone, 2x Light Gray Dye = 2x Limestone
Veridium: 3x Stone, 1x Oxidized Copper = 4x Veridium
Scorchia and Scoria are both already attainable.

All of these stones being produceable by the quarry bees would also be nice.

**Comment by Saereth** [comment]
This is a good idea, I'll get this in
