### ISSUE TITLE
[Suggestion]: add emc to skystone/skystone dust

### ISSUE THREAD

**Issue by i9xgit** [FTBTeam/FTB-Modpack-Issues#1907]
### Modpack

ftb stoneblock 3

### Is your suggestion related to a problem? Please describe.

i think there should be an emc value for skystone/skystone dust or at the very least a better way to gain it as washing dust is painfully slow for the little skystone dust you gain

**Comment by Sunekaer** [comment]
Which better way would you suggest?

**Comment by 5ully** [comment]
Mix black dye, redstone and water in heated create mixer
