### ISSUE TITLE
[Suggestion]: Add Eccentric/Akashic Tome to SB3

### ISSUE THREAD

**Issue by obipoketbobo** [FTBTeam/FTB-Modpack-Issues#1909]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

there's a lot of book juggling and every chapter giving a separate book is a headache when i can't combine them

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/eccentric-tome
https://www.curseforge.com/minecraft/mc-mods/akashic-tome
reason listed above

**Comment by Sunekaer** [comment]
Duplicate of #1801
