### ISSUE TITLE
[Bug]: FTB StoneBlock 3 - Travel Anchors teleports to incorrect destination

### ISSUE THREAD

**Issue by hairlessOrphan** [FTBTeam/FTB-Modpack-Issues#1911]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.1

### Describe the bug

Travel Anchors teleportation doesn't teleport to the targeted anchor, but rather to (I think) the furthest anchor it can find within range in the same direction. Both the Teleport Staff and teleportation via standing on an existing anchor exhibit this behavior.

### Steps to reproduce

1. Place a travel anchor at X=0 (call it Anchor A)
2. Place a travel anchor at X=30 (Anchor B)
3. Place a travel anchor at X=60 (Anchor C)
  NB: it is important than both Anchor B and Anchor C are within teleport range of Anchor A, less than 64 blocks away
  EDIT: Actually, it's not as important as I thought (or the range is 128 blocks?). I tried moving Anchors to be 60 blocks away from each other, and even with the distance from Anchor A to Anchor C at 120 blocks, the same thing still happens)
4. Stand on Anchor A and look at Anchor B. Notice that Anchor B is highlighted as your target destination
5. Teleport! (right-click)
6. Find yourself at Anchor C

### Expected behaviour

You find yourself at your highlighted target destination (Anchor B)

**Comment by Sunekaer** [comment]
Works in my instance, im guessing mod updates fixed it, let me know if its not fixed for you in 1.7.0 when its released
