### ISSUE TITLE
[Bug]: Energy dupe bug

### ISSUE THREAD

**Issue by NordicGamerFE** [FTBTeam/FTB-Modpack-Issues#1913]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Log Files

n/a

### Describe the bug

Place a battery from powah in your inventory and fill your inventory with Mekanism energy cubes and it will charge all the energy cubes = with the amount of power in your powah battery

### Steps to reproduce

Exactly like i discovered it:
1 charge a 100 mil battery.
2 Placed said battery in the head slot of my curio slot.
3 placed 10 ultimate energy cubes in my inventory and noticed they all got charged to 100 mil.

### Expected behaviour

to only charge for a total of 100 mil

### Screenshots

n/a

### Additional information

Lovely modpack

**Comment by richie3366** [comment]
Could it be a wireless charging by a Flux Network, or anything else like that?

**Comment by NordicGamerFE** [comment]
No i tested on a blank world and its caused by the battery charging all the items at once

**Comment by NordicGamerFE** [comment]
![image](https://user-images.githubusercontent.com/18188155/201512390-a1a3d844-5caa-4d89-93f5-c67460516a03.png)
battery was charged to around 50 mil

**Comment by Sunekaer** [comment]
https://github.com/Technici4n/Powah/issues/48
