### ISSUE TITLE
[Bug]: Jumbo tank dupe

### ISSUE THREAD

**Issue by NordicGamerFE** [FTBTeam/FTB-Modpack-Issues#1914]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Log Files

n/a

### Describe the bug

Breaking a jumbo tank with a paxel will drop 2 tanks

### Steps to reproduce

Break a jumbo tank from mob grinding utils with a paxel from mekanism

### Expected behaviour

to only drop 1 tank

### Screenshots

n/a

### Additional information

Lovely modpack

**Comment by richie3366** [comment]
Which Paxel did you use exactly? I can't reproduce in 1.2.1

**Comment by NordicGamerFE** [comment]
I did some more research and this was caused by the server I am playing on using Magma
