### ISSUE TITLE
[Bug]: Crash mining gadgets block

### ISSUE THREAD

**Issue by NesChrome** [FTBTeam/FTB-Modpack-Issues#1916]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.0

### Log Files

https://pastebin.com/3XwbWVJw

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9996506/latest.log)

(same link)

### Describe the bug

When setblock a block the game crash instantly

### Steps to reproduce

1. Be able to write commands (open to lan or create a world with commands)
2. /setblock ~ ~ ~ mininggadgets:renderblock (or something called like that)
3. See the game crash

### Expected behaviour

A block that disappear or nothing

**Comment by NesChrome** [comment]
And now , i can't launch my world ..

**Comment by NesChrome** [comment]
I've thinked about a way to fix it maybe , edit the render block (every files with subjet editing render block) to make it be a "real" block .
So , the people with this problem could take the mod to break the block (render block)
And then continue to play with the "normal" mod

**Comment by NesChrome** [comment]
Additional lastest.log when trying to load the world

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9997106/latest.log)

**Comment by MichaelHillcox** [comment]
None of these have been crashlogs and why would you set the block of mininggadgets:renderblock?! xD

**Comment by NesChrome** [comment]
i were testing ...

**Comment by NesChrome** [comment]
I could find a backup for my world !
