### ISSUE TITLE
[Bug]: Evertide Amulet Rotary in Condensentrator Craashes the Game

### ISSUE THREAD

**Issue by Repla7Noobx** [FTBTeam/FTB-Modpack-Issues#1920]
### Modpack

StoneBlock3

### Modpack version

1.2.1

### Log Files

https://pste.ch/tirakinizo.pl

### Describe the bug

Evertide amulet in 

### Steps to reproduce

1. Put Evertide Amulet in to the rotary condensentrator
2. Move the rotary condensentrator
3.  Right cilck the rotary condensentrator
4.  World repeatedly

### Expected behaviour

Rotary condensentrator opens normally.

**Comment by Sunekaer** [comment]
Question, why would you even put that in there?

**Comment by Sunekaer** [comment]
Im guessing to use a water source? just double checking :)

**Comment by Sunekaer** [comment]
I have opened an issue with Mekanism, https://github.com/mekanism/Mekanism/issues/7664
I dont think they will fix it as they only dev on latest version of MC, but to recover your world if you havent already go to saves/<worldname>/serverconfig/forge-server.toml and enable removeErroringBlockEntities, now load the world and the block should be gone

**Comment by Repla7Noobx** [comment]
Thank you. I just loaded the world from backups
