### ISSUE TITLE
[Bug]: Tier 5 Dyer Hut has no Furnace

### ISSUE THREAD

**Issue by Kwiechowski** [FTBTeam/FTB-Modpack-Issues#1922]
### Modpack

FTB Inferno

### Modpack version

1.2.1

### Describe the bug

The hut no longer was able to produce green dye from smelting cactus due to lack of furnace when upgraded

Looked around the hut and could not find the furnace. Tier 4 must have had a furnace because the dyer still had green dye in their inventory but would not continue making the stack.

### Steps to reproduce

FTB Inferno. Upgrade Dyer to tier 5. There is no furnace. 

### Expected behaviour

Upgrade Dyer to tier 5. There is no furnace.

**Comment by SirDragonKnight** [comment]
Hello, I've run across the bug today and it is still an issue. The dyer won't do any of its recipes because of that furnace missing.
