### ISSUE TITLE
[Bug]: we have translated the ftbquests file from stoneblock3 (CN)

### ISSUE THREAD

**Issue by yiqv** [FTBTeam/FTB-Modpack-Issues#1923]
### Modpack

FTB StoneBlock 3

### Modpack version

The latest

### Log Files

https://pste.me/@/NdtV6el6_GE

### Describe the bug

VM Chinese Translation Group
You should put the files here: kubejs\assets\ftbstoneblock\lang
It's the lang of ftbquests
1.Is there an admin who can accept translator @ in discord channel
2.Can you prepare a project to upload files for translators
3.If you have any questions please email us at 3379605778@qq.com

### Steps to reproduce

1.@ An administrator
2.Ask how to upload a file
3.No one answer
4.Finally someone came
5.Don't ping admin =)

### Expected behaviour

Come on

### Additional information

=)

**Comment by yiqv** [comment]
@Sunekaer Just email me if you have any questions(Including quests updates)

**Comment by Sunekaer** [comment]
Thanks a lot for the translation

**Comment by Wulian233** [comment]
@Sunekaer I made a Chinese translation for FTB Auxilium.Can you add the it into FTB Auxilium?
↓zh_cn.json
https://github.com/FTBTeam/FTB-Mods-Issues/issues/547

**Comment by yiqv** [comment]
@Sunekaer ，@Wulian233 is one of our group members

**Comment by Sunekaer** [comment]
@Wulian233 @yiqv just leave https://github.com/FTBTeam/FTB-Mods-Issues/issues/547 open and our mod dev will take care of it
