### ISSUE TITLE
[Bug]: ftbteams party join invalid argument (can't join party)

### ISSUE THREAD

**Issue by Skolman360** [FTBTeam/FTB-Modpack-Issues#1928]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.1

### Log Files

nothing shows in the console

### Describe the bug

FTB Teams (party) the command to join a party after being invited `/ftbteams party join (party name)` does not work, making it impossible to join a party. It shows "Incorrect argument for command" and shows "join ..." as being the incorrect argument.

![image](https://user-images.githubusercontent.com/51415372/201536418-37c8be34-66dc-4163-89da-c984c3de9ece.png)

### Steps to reproduce

1. Create party
2. Invite other player to a party `/ftbteams party invite (username)`
3. Other player tries to join using the command to join `/ftbteams party join (party name)`

### Expected behaviour

I would expect for the argument to actually be recognized and make the player join the party

### Screenshots

![image](https://user-images.githubusercontent.com/51415372/201536427-e932f065-3a80-475d-b3ed-fe2f4a821ba9.png)

**Comment by desht** [comment]
Could you please look in the `ftbteams/` folder inside your world save folder for .snbt file starting with "bb499735" and attach a copy of it to this issue?  (you should remove anything in the "message_history" section)

I suspect the issue here might be some character in your team's displayable name that the mod doesn't like, but I need the team file to know exactly what's there.

**Comment by Skolman360** [comment]
[bb499735-4b6e-41b7-81fc-d004c677417f.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10001099/bb499735-4b6e-41b7-81fc-d004c677417f.zip)

**Comment by desht** [comment]
The party name looks OK, so it's not that. The only thing I can think of is that the player you invited is already in a party (or at least the game thinks they are).  Are you certain they're not?

You can also check this by looking for that player's UUID in any other .snbt files in `ftbteams/party/` - if you need to look up a player's UUID, you can use a tool like https://mcuuid.net/ - if their UUID appears in the `ranks { }` field of any file there, then they're already in a party.

**Comment by Skolman360** [comment]
they currently are in a party but they have tried leaving their own party to join mine but the same problem persisted

**Comment by desht** [comment]
Have they run `/ftbteams party leave`? And was there any error from doing that?

**Comment by Skolman360** [comment]
I don't know if there were any errors with it or not, soonest I can check that is in 8-9h

**Comment by Skolman360** [comment]
so I tried making the issue happen again except I installed the latest version which came out very recently (1.3.0) server and client and the issue does not happen anymore, it works properly now. So I guess it's been fixed? either way I can't really test further as it's not happening anymore.
