### ISSUE TITLE
[Bug, RFToolsUtility]: Duplication Bug - Duplicate every Block with RFTools Builder

### ISSUE THREAD

**Issue by N2Blue** [FTBTeam/FTB-Modpack-Issues#193]
### Modpack

FTB OceanBlock

### Modpack version

1.5

### Describe the bug

Hi,
you can duplicate every block with RFTools Builder + Copy Mode + Preview.
I could not find anything about this duplication bug on the web, so I am not sure if it is Modpack or Mod related.

### Steps to reproduce

1. Setup a Space Chamber from RFTools Builder and put your Blocks to duplicate into it
![grafik](https://user-images.githubusercontent.com/5692853/138779371-90276607-73ca-4305-ad33-c48071e69ed9.png)

2. Setup your Builder. Use Copy-Mode and **enable Preview all the time**.
![grafik](https://user-images.githubusercontent.com/5692853/138780527-44c200a1-444d-4954-bc9d-b07244435a5b.png)

3. Put the correct amount of blocks you want to duplicate into a chest above builder
![grafik](https://user-images.githubusercontent.com/5692853/138779559-93ad56db-03ef-451c-b234-27da47141f4e.png)

4. Before you start, your setup should somehow look like this (with Preview enabled)
![grafik](https://user-images.githubusercontent.com/5692853/138779638-e8a1a4f5-8b34-4ddd-81b1-4496acffab45.png)

5. Final result: Preview and blocks above preview will be placed. You can break them like usual blocks and have duplicated them now
![grafik](https://user-images.githubusercontent.com/5692853/138779758-bd6282e2-8ed0-46d9-9672-1b3a749dbdfc.png)

### Expected behaviour

Only place blocks in shown preview. Don't duplicate.

### Additional information

Obviously this should be not a guide how to duplicate, I play on a singeplayer solo word, so there is no reason for me to cheat myself.
Use wisely.

**Comment by Raidobw2** [comment]
@Sunekaer Does this issue still need a report to the mod author, or it's been reported already and we're waiting for a mod  update to be release on CurseForge?

**Comment by Sunekaer** [comment]
@Raidobw2 still need to be report

**Comment by Sunekaer** [comment]
reported:: https://github.com/McJtyMods/RFToolsBuilder/issues/74
