### ISSUE TITLE
[Bug]: Sky block transparent issue

### ISSUE THREAD

**Issue by NordicGamerFE** [FTBTeam/FTB-Modpack-Issues#1931]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Log Files

n/a

### Describe the bug

If you vein mine a couple of blocks directly under the sky block it will cause the sky block to become transparent.

### Steps to reproduce

Place skyblocks then place atleast 2 blocks in a row under the skyblocks and veinmine them.

### Expected behaviour

for the blocks to be mined without turning the sky blocks transparent

### Screenshots

![image](https://user-images.githubusercontent.com/18188155/201550115-edf73f48-e2c3-4e32-881f-ae57885db220.png)

### Additional information

Lovely Modpack :D

**Comment by NordicGamerFE** [comment]
Just tested and its a issue with the void blocks also

**Comment by Sunekaer** [comment]
https://github.com/nanite/Literal-Sky-Block/issues/4

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
