### ISSUE TITLE
[Bug]: Game crashes if you open your inventory before REI finishes initializing.

### ISSUE THREAD

**Issue by TheD0ct0r101** [FTBTeam/FTB-Modpack-Issues#1933]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Log Files

No crash log is created

### Describe the bug

Upon joining the world, if you open your inventory before REI has gone through all of it's initialization steps, the game will freeze. You can try waiting for it to finish loading, but upon investigating the game in task manager, it is revealed that CPU and Disk processing has 100% halted, indicating the game has silently crashed.

It is to be noted that I am also using REI's caching option to increase it's performance, however its quite possible this issue also happens with the setting turned off.

### Steps to reproduce

1. Enable REI's caching mode (or dont?)
2. Join your world, and as soon as you load in, open your inventory
3. You should get a red-box message at the bottom of the screen, saying REI is only a few steps into intializing
4. Game promptly freezes and silently halts, forcing the user to kill the instance (no useful crash log as a result).

### Expected behaviour

A short amount of time to load REI to completion, and a lag spike to load the cache (if using cache mode), and then the game would resume and run smoothly

**Comment by Sunekaer** [comment]
Can your please provide the crash log from when this happened?

**Comment by yoshijulas** [comment]
I enable REI's caching by error, in the inventory menu, and the game crashed, after opening and loading the game, it tries to generate the cache and crashes again

I "fixed it" by disabling it on config file 
"cachingFastEntryRendering" and when I open the game, leave it without doing anything until everything loads, and I can play again without issues

**Comment by ScarredPast** [comment]
I suspect this is related to a crash I keep encountering involving the Null egg from the _Chickens_ mod. Without REI's caching enabled, there's no freeze or crash on startup. REI initializes just fine. With it enabled, if you open your inventory (and therefore view the REI lib) before it has finished initializing, it causes freezing and eventually a crash. Similarly, if you type in a search that brings up the Null Egg from _Chickens_, it produces a similar, if not identical crash state. What's got me suspicious that the two are related is the fact that if we enable REI's caching mode, load into the world, wait a few minutes to allow REI to fully initialize and cache, we then do not encounter any crash related to viewing the Null Egg from _Chickens_. My apologies on reviving a closed ticket, but I feel as though this insight as to possible relation between the Null Egg and the REI caching crash may be useful. I have replicated both crash states and attached REI and REI-Issues logs for both. The logs related to opening the inventory too soon are labeled StartupCrash and the ones related to viewing Null Egg without REI caching on are labeled NullEgg. All of these crashes are encountered on a multiplayer server.

[StartupCrash-rei-issues.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14128275/StartupCrash-rei-issues.log)
[StartupCrash-rei.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14128278/StartupCrash-rei.log)

[NullEgg-rei-issues.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14128379/NullEgg-rei-issues.log)
[NullEgg-rei.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14128385/NullEgg-rei.log)
