### ISSUE TITLE
[Suggestion]: Stoneblock 3 Industrial Foregoing and Immersive Engineering

### ISSUE THREAD

**Issue by ame824** [FTBTeam/FTB-Modpack-Issues#1937]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

The Plant Gatherer cant farm the Industrial Hemp from Immersive Engineering. 

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/integration-foregoing

**Comment by Bloodshadow14** [comment]
Hey buddy this addon is only for 1.12.2 so thr authors couldn't add it i think
