### ISSUE TITLE
[Bug]: Ars Nouveau Sribe's Table Dupe Glitch

### ISSUE THREAD

**Issue by Bereim** [FTBTeam/FTB-Modpack-Issues#1938]
### Modpack

FTB StoneBlock 3

### Modpack version

1.2.1

### Describe the bug

Using the Tinkers Crafting Station you can place a Stack of Items into the Scribe Table. However when removing the stack, it is duplicated and the stack remaining in the Scribe Table has 1 Item Subtracted from it.

### Steps to reproduce

1. Place down an Ars Nouveau Scribe's Table.
2. Place a Tinkers Crafting Station adjacent to it.
3. Put a Stack of Items into the Scribe's Table using the Crafting Station.
4. Remove the Stack of Items using the Crafting Station without Shift-Clicking.
5. Repeat Step 4 until the Stack in the Scribe's Table is Depleted.

### Expected behaviour

No Duping

**Comment by Sunekaer** [comment]
https://github.com/baileyholl/Ars-Nouveau/issues/695

**Comment by TheonlyTazz** [comment]
also:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1938

**Comment by Sunekaer** [comment]
Should be solved already

**Comment by AnAwesomGuy** [comment]
seems like this is still happening
