### ISSUE TITLE
cant attack  [Bug]: 

### ISSUE THREAD

**Issue by Dankwiz2017** [FTBTeam/FTB-Modpack-Issues#1939]
### Modpack

stoneblock 3

### Modpack version

1.2.1

### Describe the bug

cant attack, not mobs or even air, i can mine do everything else but attack. 

### Steps to reproduce

press left click

### Expected behaviour

attack doesnt happen

**Comment by Dankwiz2017** [comment]
when i change my controls to right click it works as advertised but when i switch it back i can only attack blocks

**Comment by Sunekaer** [comment]
Works in my instance, im guessing mod updates fixed it, let me know if its not fixed for you in 1.7.0 when its released
