### ISSUE TITLE
[Bug]:  Lighting glitch with torches in OceanBlock

### ISSUE THREAD

**Issue by FizzyPop521** [FTBTeam/FTB-Modpack-Issues#194]
### Modpack

FTB Oceanblock

### Modpack version

1.1.0 Beta

### Describe the bug

Occasionally when I leave my island my torches stop working. They are still where I placed them, but not lighting up the area. When F7 is pressed it shows red or yellow x's even on top of the torches. Removing and replacing torches does work until the next time it starts to act up.

### Steps to reproduce

1. Place torches
2. Leave island whether by boat or painting
3. Return and torches are not lighting the island or preventing mob spawn. Does not happen every time.

### Expected behaviour

Torches to provide light.

### Screenshots
![2021-10-25_21 39 41](https://user-images.githubusercontent.com/91456938/138799870-e4ad9315-39c2-42ac-9d26-f446b7454279.png)

_No response_

### Additional information

This does not occur every time I leave the island. Seems to be random as far as I can tell.

**Comment by Sunekaer** [comment]
Im not able to recreate this issue.
Since Fizzy hasnt replied to Raidobw2 for 11 days closing issue
