### ISSUE TITLE
[Bug]: Going through the nether portal grants the Escape quest

### ISSUE THREAD

**Issue by Inky-developer** [FTBTeam/FTB-Modpack-Issues#1944]
### Modpack

FTB Inferno

### Modpack version

1.2.1

### Describe the bug

Going through a nether portal, even in early game, grants the quest but causes a teleport back into the nether

### Steps to reproduce

1. Start a new world
2. Get some Obsidian
3. Build a nether portal and light it
4. Enter and get quest

### Expected behaviour

Nothing happens

**Comment by Saereth** [comment]
This is not a bug and does not allow progression skipping, people are welcome to go through and complete that quest at any time, they will find the no escape message and be yeeted back into the nether
