### ISSUE TITLE
[Bug]: Game crashes when breaking a small cog wheel 

### ISSUE THREAD

**Issue by huffalexw** [FTBTeam/FTB-Modpack-Issues#1945]
### Modpack

FTB Stone Block 3

### Modpack version

1.2.1

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10004261/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10004264/latest.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10004266/console.log)

### Describe the bug

Placed a cog wheel improperly (i.e. shaft of cog wheel was horizontal when it should have been vertical.). When going to break the cog wheel the game freezes and will not respond.  When forcing the close the system states that the instance is not responding. 

### Steps to reproduce

1. Place a Create mill
2. Place a Create cog wheel perpendicular to the appropriate direction.
3. Attempt to break cog wheel
4. Game freezes

### Expected behaviour

Expected to be able to break cogwheel

**Comment by Raidobw2** [comment]
This might have been fixed after your report 🙂 thanks for reporting!
![image](https://user-images.githubusercontent.com/17010632/214771537-93815337-b5f7-447e-9a97-a6c7eea69acf.png)
![image](https://user-images.githubusercontent.com/17010632/214771575-308f1cd6-ec08-40ea-8da9-c3abc652aa6b.png)
