### ISSUE TITLE
[Bug]: Connected Glass Issue

### ISSUE THREAD

**Issue by Worgeen** [FTBTeam/FTB-Modpack-Issues#1948]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.0

### Log Files

https://github.com/SuperMartijn642/ConnectedGlass/issues/29

### Describe the bug

https://github.com/SuperMartijn642/ConnectedGlass/issues/29

### Steps to reproduce

https://github.com/SuperMartijn642/ConnectedGlass/issues/29

### Expected behaviour

https://github.com/SuperMartijn642/ConnectedGlass/issues/29

### Screenshots

https://github.com/SuperMartijn642/ConnectedGlass/issues/29

### Additional information

https://github.com/SuperMartijn642/ConnectedGlass/issues/29

**Comment by Worgeen** [comment]
Only put this issue here so you guys can update the mod if the creator fix it! :)

**Comment by Worgeen** [comment]
New to github, so sorry if i did anything wrong O.o

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
