### ISSUE TITLE
[Bug]: Mods are wrongly set to client only (DW20 1.7.10)

### ISSUE THREAD

**Issue by Einhornyordle** [FTBTeam/FTB-Modpack-Issues#1951]
### Modpack

FTB Presents Direwolf20

### Modpack version

1.10.0

### Describe the bug

Some mods are set to client only which are needed on the server too. I've noticed this on Direwolf 20 1.12.2 too so maybe even more packs are afffected.

### Steps to reproduce

1. Take a close look at the [manifest](https://api.modpacks.ch/public/modpack/14/104), especially at which mods are set to client only
2. Notice that multiple Mods which are needed on the server are set to client only for some reason

### Expected behaviour

Mods that are supposed to be on the server aren't set to client only

### Screenshots

![image](https://user-images.githubusercontent.com/47315090/201739394-736fca4a-bdf0-4d02-8a4c-322864f858e5.png)

**Comment by Raidobw2** [comment]
Thanks, we'll look into it

**Comment by Einhornyordle** [comment]
Since it's been almost three months, any update on this?

**Comment by Gaz492** [comment]
This should be resolved now.

**Comment by SirEndii** [comment]
🐌
