### ISSUE TITLE
[Bug]: Inventory Sorter sorts both hotbar+inventory when Iron Furnace interface is open

### ISSUE THREAD

**Issue by bmwalter68** [FTBTeam/FTB-Modpack-Issues#1952]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

When the Iron Furnace interface is open sorting with inventory sorter sorts the hotbar as well as inventory contents.

### Steps to reproduce

1. Right click on Iron Furnace to open interface
2. Click middle button to sort inventory
3. Hotbar+Inventory are all sorted together

### Expected behaviour

Only the inventory should be sorted, not the hotbar

### Additional information

I believe adding iron furnaces to the Inventory Sorter blacklist would be a valid interim solution.  I will also attempt to post this to the Iron Furnace bug tracker.

**Comment by stillie** [comment]
This bug has caught me out one too many times! Hope this one gets fixed :)
