### ISSUE TITLE
[Bug]: Lava Egg show uses shows Water Egg recipes

### ISSUE THREAD

**Issue by baueko** [FTBTeam/FTB-Modpack-Issues#1956]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

Show Uses for Lava Egg in REI also shows recipes for the Water Egg (probably related to #1848).

### Steps to reproduce

1. Press "Show Uses" on Lava Egg

### Expected behaviour

Only Lava Egg recipes are shown

**Comment by Sunekaer** [comment]
Hi

Yea, its that or them not being useable sadly
