### ISSUE TITLE
[Bug]: cant look around. only in one direction

### ISSUE THREAD

**Issue by KaspianU** [FTBTeam/FTB-Modpack-Issues#1959]
### Modpack

Stoneblock 3 

### Modpack version

1.3.0 (others too)

### Describe the bug

I have a Problem,  i can only look in one direction and can turn around with the mouse an somebody help please?

### Steps to reproduce

1. i download the mod
2. logged in 
3. cant look right or left / not turn abound only look in one direction

### Expected behaviour

turn around and not only in one direction

### Screenshots

hard to make a screenshot about this Problem

### Additional information
 
happens in single player / multiplayer and with other versions/ alredy uninstall and install again. not in Vanilla minecraft only . Not work in Inferno modpack and Vanilla started with the FTB App

**Comment by 5ully** [comment]
Does the game not capture your mouse input?

**Comment by KaspianU** [comment]
In the Inv an the menu my mouse work, i can break an place blocks too

**Comment by KaspianU** [comment]
no not breaking the game,just cant look around. Can you maybe msg me in Discord (KaspianU#4962) that i can show you a video about it ? i realy not not understand it... never had somethink like this before...

**Comment by jikuja** [comment]
Did you post all the extra information we went through in Discord this ticket? Your current `Additional information` is really hard to understand.

E.g. which MC versions are working and which are not.

**Comment by Raidobw2** [comment]
@KaspianU You can add videos here. Drag any mp4 file to upload it (max 10MB for Github). If a video is too big, lower your bitrate on the recording software, or put the video on your Google Drive and share it with a link here.
Can you try pressing F11 in-game and seeing if your mouse works again? F11 will allow you to go fullscreen
Thanks
