### ISSUE TITLE
[Bug]: Game unloads world after looking at a creative drawer with Creative Capacitor Banks from Ender IO in it

### ISSUE THREAD

**Issue by CleanCutBloons** [FTBTeam/FTB-Modpack-Issues#196]
### Modpack

Sky Odyssey

### Modpack version

1.1.0

### Log Files

https://pastebin.com/1MEndJyq

### Describe the bug

After I put a Creative Capacitor Bank in a Storage Drawer, I put a Creative Vending Upgrade in the drawer. The game then sent me to the title screen. This happened again after I looked at the drawer, but the game froze instead.

### Steps to reproduce

1. Place a drawer down
2. Put a Creative Capacitor Bank from Ender IO inside the drawer
3. Place a Creative Vending Upgrade inside the drawer

### Expected behaviour

The game should allow Creative Vending Upgrades on drawers with Creative Capacitor Upgrades and should not unload the world.

### Screenshots

None

### Additional information

I think that it is caused by the code that renders the icon of the Creative Capacitor Bank.

**Comment by Raidobw2** [comment]
If SkyOdyssey gets maintained at some point, we'll switch the mod.
Otherwise, this may be closed at any point in time if the project is judged discontinued, since the focus is currently for 1.16.
This will stay in the records in that case, and contains the fix.
