### ISSUE TITLE
[Suggestion]: Add Morph-o-tool mod

### ISSUE THREAD

**Issue by Xiarno** [FTBTeam/FTB-Modpack-Issues#1960]
### Modpack

Stone Block 3

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/morph-o-tool

Similar to #1801 for books, adding Morph-o-tool would solve the many-wrench problem.

**Comment by Sunekaer** [comment]
Which wrench problem would it solve?
This mod was more used in like 1.12, as most mod are following the same standard now.

**Comment by Xiarno** [comment]
> Which wrench problem would it solve? This mod was more used in like 1.12, as most mod are following the same standard now.

No "problem" per say, but you added the Eccentric tome mod for books so why not the same sort of thing but for wrenches? So combining the wrench in a singular one.

**Comment by Sunekaer** [comment]
Because all the books doesnt do the same thing.
Where 95% of the wrenches has the same function and therefore you might only need 2 through the game play, which is why im asking you which issues it is your having..

**Comment by SoxMax** [comment]
I agree, having modpack specific wrenches is often useful. For example the wrench from Mekanism, the Configurator, shows what input/output state the sides of a block are in which other wrenches do not do.
