### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shadeisthebest** [FTBTeam/FTB-Modpack-Issues#1961]
### Modpack

Stoneblock 3

### Modpack version

1.2.0

### Describe the bug

I have been trying to play stoneblock 3, and I can launch the game as well as create a new world just fine. Upon attempting to save the world, the game freezes completely, and will not respond until I kill the instance.

### Steps to reproduce

1. Create new world
2. Attempt a save and exit

### Expected behaviour

World would save just fine, and would allow me to launch again when I desire

**Comment by Sunekaer** [comment]
Does this happen on 1.3.0?
