### ISSUE TITLE
[Bug]: no blocks

### ISSUE THREAD

**Issue by demoniclords** [FTBTeam/FTB-Modpack-Issues#1963]
### Modpack

FTB stoneblock 3

### Modpack version

1.3.0

### Describe the bug

when mining with the red morning star you dont get any block drops

### Steps to reproduce

get a red morning star 
try to mine something

### Expected behaviour

i get the block

**Comment by Sunekaer** [comment]
What blocks you mining?

**Comment by 5ully** [comment]
Doesnt the morning star drop "orbs" of blocks when mined?

**Comment by demoniclords** [comment]
I was mining stone and my cobble gen and I would get nothing from them
