### ISSUE TITLE
[Bug]: No Singularitys

### ISSUE THREAD

**Issue by Shatikka** [FTBTeam/FTB-Modpack-Issues#1964]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

Infinity Catalyst don't have a crafting recipe, all the Singularities are gone and uncraftable now.

### Steps to reproduce

1. Open quest book
2. Go to 'Densitas Infinita' tab
3. All Singularitys are now question marks

### Expected behaviour

To be able to craft Singularitys

### Screenshots

![image](https://user-images.githubusercontent.com/49534746/201795484-0dc83007-8c52-4849-b965-fdf9f1ef6e35.png)

**Comment by NordicGamerFE** [comment]
I dont have this issue, Also 1.3.0
