### ISSUE TITLE
[Bug]: Cannot apply Range Addon to Stasis Chamber

### ISSUE THREAD

**Issue by ShadofuTRT** [FTBTeam/FTB-Modpack-Issues#1966]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

As mentioned in the quest book, the Range Addon can be applied to the Stasis Chamber to increase the range of it, but when I tried to apply one it doesn't work, furthermore I can't even see the working area of the machine as well.

### Steps to reproduce

1. Place Stasis Chamber down
2. Open UI
3. Add any Range Addon to the machine

### Expected behaviour

Being able to add Range Addon as mentioned in the quest book

**Comment by Kangy1103** [comment]
This is also happening to me

**Comment by portalgungamer2** [comment]
I Have The Same Problem I'm on version 1.4.1
![2022-11-24_22 46 51](https://user-images.githubusercontent.com/62117476/203903260-88b1d518-771a-40d8-84c6-62129d34138e.png)
