### ISSUE TITLE
[Bug]: Casting Iron Gears gives Lapis Gears instead

### ISSUE THREAD

**Issue by Apocrophon** [FTBTeam/FTB-Modpack-Issues#1967]
### Modpack

FTB Stoneblock 3

### Modpack version

1.0.2

### Describe the bug

Attempting to cast Molten Iron from a TiCon Smeltery into a Gear Cast gives Lapis Gear instead of the intended Iron Gear.

### Steps to reproduce

cast iron into gear gold cast

### Expected behaviour

want iron gear

**Comment by Sunekaer** [comment]
Update your game, its fixed long time ago
