### ISSUE TITLE
[Bug]: MineTogether crashes

### ISSUE THREAD

**Issue by frinkifail** [FTBTeam/FTB-Modpack-Issues#1968]
### Modpack

FTB Academy

### Modpack version

1.3.0

### Log Files

https://pastebin.com/XZradsdf

### Describe the bug

MineTogether crashes on load, during `sided_setup` event

### Steps to reproduce

1. Launch the game
2. Wait
3. Error screen

### Expected behaviour

Load Normally??

### Screenshots

<img width="855" alt="Screen Shot 2565-11-15 at 16 04 39" src="https://user-images.githubusercontent.com/76682714/201876897-934237c0-cf4f-4a3a-bb02-925fef76af37.png">

### Additional information

dang it i just wanna play

**Comment by Raidobw2** [comment]
Try logging again in the MineTogether in the FTB App, or remove the MineTogether mod from the mods folder. If the former doesn't work, you'll have to remove the mod to play as it looks like an error in the mod code

**Comment by Raidobw2** [comment]
Also, it looks like you're using MultiMC or a similar launcher, so does the FTB App work?

**Comment by frinkifail** [comment]
no, ftb app doesn't work, if i remove it, rhino crashes the game and complains about `cannot read property 'id' from undefined`

**Comment by Raidobw2** [comment]
That's odd, in that case remove the main menu script completely and potentially that'll allow you to play like normal. Open the game files and delete the file at `kubejs\client_scripts\main_menu.js`, then start the game and see if that works for now

**Comment by frinkifail** [comment]
i forgot to close this issue
