### ISSUE TITLE
[Suggestion]: ExtraStorage

### ISSUE THREAD

**Issue by justinpierson** [FTBTeam/FTB-Modpack-Issues#1970]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

I have always liked having more crafters!

### Mod suggestion

Extrastorage:
https://www.curseforge.com/minecraft/mc-mods/extrastorage

**Comment by Sunekaer** [comment]
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1599
