### ISSUE TITLE
[Bug]: Powah Energy Cable causes lag & crash

### ISSUE THREAD

**Issue by duruer** [FTBTeam/FTB-Modpack-Issues#1971]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0

### Describe the bug

Hi, when we were playing in our dedicated server, we realized more than 50 to 60 any energy cables of Powah causes lag and after more than 60 cables, server starts to not respond and due to this, it gets crashed.

Also, due to this bug, when someone enters to those chunks which include those cables, server logs in console a huge not understandable text.

### Steps to reproduce

1. Try to put 50 to 60 of Powah energy cables. (this should lag server)
2. Put more cables (if you go to lobby or exit from game and come back to world, it loads chunks again and cause huge error log and not respond)

### Expected behaviour

Not crashing

**Comment by 5ully** [comment]
Please provide server logs

**Comment by duruer** [comment]
Here it is since it's huge:
https://drive.google.com/file/d/1ZgN2i7BLsbBnEV0WNcQH0snmqn9kee0u/view?usp=sharing

Well, logs are not helpful for this modpack I think but they might be useful for powah.

**Comment by Raidobw2** [comment]
Could be the same issue as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/195, try removing all Powah cables and see if that solves the lag/crashes.
Powah cables might need to be disabled or have a notice on them to warn about their use

**Comment by duruer** [comment]
Yes, it does solve the issue already.

**Comment by Sunekaer** [comment]
https://github.com/Technici4n/Powah/issues/54

**Comment by Technici4n** [comment]
Hi, I'm the current maintainer of Powah. I partially rewrote cables because the previous implementation was flawed. I'm open to performance improvements, but I'd need some more scientific measurements. If you are experiencing cable-induced lag, please post a spark profile so I can see where it's coming from.

**Comment by Gaz492** [comment]
Looks like cables get into a recursive loop and lag out everything https://spark.lucko.me/wnmWwyhrXo 
This can be reproduced by creating a snake of cables, the longer the snake the more lag.
@Technici4n

**Comment by Sunekaer** [comment]
Should be solved.
