### ISSUE TITLE
[Suggestion]: Chicken colors

### ISSUE THREAD

**Issue by Reithsaw** [FTBTeam/FTB-Modpack-Issues#1974]
### Modpack

FTB Stoneblock 3 V1.3.0

### Is your suggestion related to a problem? Please describe.

Hi,

Can you change the color for the " Ink Black Chicken " ? Actually is like the Gray chicken

Best regards

**Comment by Sunekaer** [comment]
Free feel to open this request at https://github.com/CreeperHost/Chickens we dont control the textures
