### ISSUE TITLE
[Suggestion]: Make create something much more useful

### ISSUE THREAD

**Issue by JustKama** [FTBTeam/FTB-Modpack-Issues#1975]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

So i was wandering around my world doing stuff when i thought it might be pretty annoying having to craft all the stuff from Refined storage and Create later in the game "This is ofc only an example" If it had emc it'd be much easier to work with and.. In my opinion Make create something much more useful, Basically getting all the recources.. I don't mean other stuff like the Precision Mechanism since that would just Make it too easy, But like casings and the sheets and such.. That'd make the whole thing alot more do-able especially having to wait for all the Refined storage things

**Comment by Sunekaer** [comment]
But that takes out all the fun of making automations.
Im okay with adding EMC to more base resources because to me seems to much
