### ISSUE TITLE
[Bug]: Unable to complete flint pickaxe quest

### ISSUE THREAD

**Issue by TobiDoes** [FTBTeam/FTB-Modpack-Issues#1976]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

Unable to Complete Flint Pick Quest 

### Steps to reproduce

try to Complete Flint Pick Quest 

### Expected behaviour

after the crafting of a flint pick it completes

**Comment by orbidlo** [comment]
Duplicate of #1886

**Comment by Shinino** [comment]
Workaround for now:  Create Tinker's Construct version (with parts et al), and it'll finish.
