### ISSUE TITLE
[Bug]: Trash can overlap in chest view

### ISSUE THREAD

**Issue by bmowes** [FTBTeam/FTB-Modpack-Issues#1977]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

The trash slot in players inventory moves and overlaps with the player inventory when viewing contents of chest. Happens with both stone chest and vanilla chests, both single and double. Does not happen when just viewing player inventory. Still functions, strictly aesthetic

### Steps to reproduce

Open chest in survival

### Expected behaviour

Should remain in position

**Comment by Sunekaer** [comment]
Works fine in my instance, it should remember if you move the slot
