### ISSUE TITLE
[Bug]: ProjectE / Dupe bug

### ISSUE THREAD

**Issue by Hellox8** [FTBTeam/FTB-Modpack-Issues#1979]
### Modpack

FTB Stone Block 3

### Modpack version

1.3.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10014662/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10014663/debug.log)

### Describe the bug

I don't know how but i manage to drop/clear an item in same time inside my EMC Link and have 112 items stacks on grounds that generate infinite item when i walk to take the items. 
I just take a flint and steel and burn the 112 items stack who remove it. 

### Steps to reproduce

I dont really know?
1. put item inside the compressed EMC Link
2. clear/took a stack in same time ?
3. having 112 items stack on ground

### Expected behaviour

fixe the dupe

### Screenshots

![2022-11-15_17 54 08](https://user-images.githubusercontent.com/118120827/201980724-ef125a85-4715-4422-9556-dfecc7651cd2.png)
![2022-11-15_17 54 16](https://user-images.githubusercontent.com/118120827/201980744-efca60c4-92d6-4f77-92af-e3d08d1802fc.png)
![2022-11-15_17 54 25](https://user-images.githubusercontent.com/118120827/201980752-01d7b576-6f21-4783-890a-bc5bf55dc35d.png)
![2022-11-15_17 54 35](https://user-images.githubusercontent.com/118120827/201980761-3dd885a1-db21-42f6-8b86-4ba08a5aaf8b.png)
![2022-11-15_17 54 38](https://user-images.githubusercontent.com/118120827/201980771-b471eb86-4c76-48db-ba13-e91417e5102a.png)

**Comment by Sunekaer** [comment]
Should be solved in the newest update of the pack
