### ISSUE TITLE
[Suggestion]: Autosmithing table should be added to the misc tab

### ISSUE THREAD

**Issue by Gurkysword12** [FTBTeam/FTB-Modpack-Issues#1981]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

I find that the autosmithing table should be added to the misc tab for users to find easier

**Comment by Sunekaer** [comment]
Misc tab in Creative menu or you talking about in Quest?

**Comment by Gurkysword12** [comment]
Im talking about in the quests

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/205216324-fa8954c9-fbb1-4422-87b3-657a9c4a1630.png)
