### ISSUE TITLE
[Bug]: Silverfish not affected by mob crusher

### ISSUE THREAD

**Issue by Azemari** [FTBTeam/FTB-Modpack-Issues#1984]
### Modpack

Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

Silverfish are not affected by the Mob Crusher

### Steps to reproduce

Place and Power Mob Crusher
Upgrade Range to affect desired area 
Watch Silverfish not die

### Expected behaviour

Silverfish die

### Screenshots

![image](https://user-images.githubusercontent.com/55991839/202040419-49a2b831-2aa7-4b5c-b9c0-43e0b641521b.png)

### Additional information

The dead loot objects are from me killing them

**Comment by Sunekaer** [comment]
Not a bug
