### ISSUE TITLE
[Bug]: Floral fertilizer pops out of dispenser instead of functioning like vanilla bonemeal

### ISSUE THREAD

**Issue by ihaveaskimask** [FTBTeam/FTB-Modpack-Issues#1987]
### Modpack

FTB stoneblock 3

### Modpack version

1.3.0

### Describe the bug

Floral fertilizer pops out of dispenser instead of functioning like vanilla bonemeal.

### Steps to reproduce

1. set up dispenser pointing at grass blocks
2. put floral fertilizer in 
3. power dispenser

### Expected behaviour

flowers grow

**Comment by Raidobw2** [comment]
Just a note that this might be intended by Botania...
Normally you are supposed to use the Jaded Amaranthus to automate Mystical Flowers, and a Drum of the Wild that receives a mana burst to break the flowers
