### ISSUE TITLE
[Bug]: Negative EMC values

### ISSUE THREAD

**Issue by CanINotUseTruth** [FTBTeam/FTB-Modpack-Issues#1988]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

I think this is a long-term bug in Project E and doesn't really have an in-game quick fix. When a player's personal EMC value hits about 9.2 Quintillion it goes negative and then obviously any system sections requiring EMC become unavailable and stop. You can't see or pull out items from EMC links through any digital storage system.

### Steps to reproduce

Have a personal EMC value over 9.2 Quintillion.
Use EMC links with RS or AE2.

### Expected behaviour

EMC systems to continuously work without maxing out and failing.

### Additional information

Suggestion: 

Introduce an EMC Cap so it can't reach the negatives or an OP command to edit/remove personal player EMC levels so it can be quickly rectified. The only way I could find to reset my EMC levels was to delete my player files. Some searching online says that eventually the EMC levels will cycle back to 0 but obviously that is inconvenient too. I understand this may be something that needs to be just passed onto the ProjectE author as well so understandable if you are unable to implement these changes.

**Comment by Sunekaer** [comment]
Fixed in 1.3.0
