### ISSUE TITLE
[Bug]: "getting started" questline disappeared after update from 1.2.1 to 1.3.0

### ISSUE THREAD

**Issue by Gamewalker** [FTBTeam/FTB-Modpack-Issues#1989]
### Modpack

Stoneblock3

### Modpack version

1.2.1 to 1.3.0

### Describe the bug

After updating from 1.2.1 to 1.3.0 the "getting started" questline disappeared.
I started new singleplayer game and the questline was there.
Changing to edit mode doesnt show the questline, so I guess it got deleted.

### Steps to reproduce

1. Server with 1.2.1
2. Play
3. Updsate to 1.3.0
4. "Getting started" isnt there anymore

### Expected behaviour

Getting started shouldnt be deleted

**Comment by Sunekaer** [comment]
Sound like a file got messed up in your update, i cant recreate this issue
