### ISSUE TITLE
[Bug, PortableStonecutter]: Crash when opening refined storage grid. JEI and PortableStonecutter references.

### ISSUE THREAD

**Issue by AlexandrXamlo** [FTBTeam/FTB-Modpack-Issues#199]
### Modpack

FTB OceanBlock

### Modpack version

1.5.0

### Log Files

https://pste.ch/verodaguno.md

### Describe the bug

Game crashed after opening craft grid (refined storage) and type in search: "6"...

### Steps to reproduce

1. Open craft grid (refined storage)
2. type in search "6"

### Expected behaviour

not crashed...

**Comment by Raidobw2** [comment]
The mod author mentioned their fix:

> I think it has to do with AnvilFlatteningRecipeCategory and IAnvilFlatteningRecipe having the same UID, so I differentiated them to be sure. As I wasn't able to reproduce the issue I cannot be sure that it fixed it so if someone who had the issue can confirm for me I'd be grateful 👍

And it looks like it worked for the user, so we will then wait for the mod to update to include the fix in the next development cycle.

**Comment by Raidobw2** [comment]
Portable Stonecutter-1.16.5-1.3.5 recently available with the fix.
https://www.curseforge.com/minecraft/mc-mods/portable-stonecutter/files
