### ISSUE TITLE
[Bug]: Crash after craft

### ISSUE THREAD

**Issue by Reithsaw** [FTBTeam/FTB-Modpack-Issues#1990]
### Modpack

FTB Stoneblock 3

### Modpack version

V1.3.0

### Describe the bug

If you open the quest book and click on an item, after that it the +, and craft it with a tablet from RFtoolsStorage the game crashed, i don't know if it's a mod problem, or other things.

### Steps to reproduce

1. Have a RFtoolsStorage Tablet
2. Open the quest book
3. Click on a quest
4. Click on the item requested
5. Click on the " + "
6. The craft showed is not correct BUT
7. If you press the number (1 for this exemple) the game create it and then crash

### Expected behaviour

Refresh the craft showed and don't crash ?

**Comment by Raidobw2** [comment]
Hi, could you add your game logs please? The `latest.log` in the `logs` folder would be good, as well as the most recent file in the `crash-reports` folder. Add them here after you encounter the error if possible please and thanks!

**Comment by Reithsaw** [comment]
[crash-2022-11-18_14.24.45-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10041603/crash-2022-11-18_14.24.45-client.txt)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10041604/latest.log)

Here is the log and the crash-report

**Comment by Raidobw2** [comment]
Sorry for the delay, thanks for posting your logs. It looks like the crash report should contain the relevant info; I've forwarded it to the mod author just now

**Comment by Raidobw2** [comment]
Reported to REI instead ^

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
