### ISSUE TITLE
[Bug]: Thermal Wrench and Create Belt

### ISSUE THREAD

**Issue by Djahmo** [FTBTeam/FTB-Modpack-Issues#1991]
### Modpack

StoneBlock 3

### Modpack version

1.3.0

### Describe the bug

when you breack the belt with the wrench that break just one part of the belt and you can generate infinite belt

### Steps to reproduce

1. Take in hand the thermal wrench
2. Right click with them on Create Belt 

### Expected behaviour

generate infinite create belt

### Screenshots

https://www.youtube.com/watch?v=gIpeaQJSOAc

**Comment by Sunekaer** [comment]
Same as #1958
