### ISSUE TITLE
[Suggestion]: Couple of mod suggestions

### ISSUE THREAD

**Issue by NordicGamerFE** [FTBTeam/FTB-Modpack-Issues#1992]
### Modpack

FTB Stoneblock 3

## I've got two mods to suggest plus a small other thing.

1: [Animal Crops](https://www.curseforge.com/minecraft/mc-mods/animal-crops) could be nice to have since some of the animals can be hard to get they could be good with custom recipes and dungeon loot to acquire mob drops, I know you can find mob eggs but I think this is more elegant and a better solution.

2: [Easy Mob Farms](https://www.curseforge.com/minecraft/mc-mods/easy-mob-farm) nice to have since it will reduce performance hit for large farms a plus is also its configurability.

3: [The Useful List](https://github.com/TheUsefulLists/UsefulMods) is a list with a bunch of bugfixing and performance mods some less known then others, Its worth a look you often find small gems, I got nothing specific to suggest on it but you might find a mod that fixes a thing that you didn't know you wanted fixed.

**Comment by NordicGamerFE** [comment]
Do note if Easy Mob Farms were to be added I don't think Animal Crops would have a place in the pack.

**Comment by Sunekaer** [comment]
1. crop farming is overused imo, which is also why there is no Mystical Arg. in the pack.
2. Tooooooo easy.
3. We try to not use to many of those mods as the often breaks other things, so nothing something we can just add without heavy testing in out beta enviroment
