### ISSUE TITLE
[Bug]: New ftbquest translation of CN

### ISSUE THREAD

**Issue by yiqv** [FTBTeam/FTB-Modpack-Issues#1993]
### Modpack

ex.stoneblock3

### Modpack version

The latest

### Log Files

"sb3.exploration.silverfish_farm.title":"养殖蠹虫之母",
"sb3.exploration.silverfish_farm.desc1":"在几个模组的联合辅助之下，你可以从蠹虫之母身上轻松地&6获取无穷无尽的蠹虫之心&r。",
"sb3.exploration.silverfish_farm.desc2":"&b德格米护符&r可以消耗魔源，从而&6再不杀死生物的情况下获取它们的掉落物&r。",
"sb3.exploration.silverfish_farm.desc3":"使用&6火山魔源通道&r可以轻松制作魔源宝石，用&6更多鸡&r（或是其它的来源）中获取的煤炭可以为它供能。",
"sb3.exploration.silverfish_farm.desc4":"要固定住蠹虫之母的位置，不让她乱跑，你可以&6直接在召唤祭坛下面&r放置一个&b生物静滞室&r，最好再加装上一块&6范围升级插件&r。",
"sb3.exploration.silverfish_farm.desc5":"之前获得的煤炭还可以用来为发电机提供燃料，生产FE。记得用栅栏来&6防止德格米进入生物静滞室的工作范围！",
"sb3.exploration.silverfish_farm.desc6":"最后，一个&b超级火把&r可以防止蠹虫之母产下她的子嗣。",

### Describe the bug

@Suneekaer I took care of it

### Steps to reproduce

1.@
2,@
3,wait for Sunekaer

### Expected behaviour

Come on

**Comment by yiqv** [comment]
@Sunekaer

**Comment by Raidobw2** [comment]
Sunekaer will be able to look into this in time, thanks for adding the translations here!
