### ISSUE TITLE
[Bug]: STONEBLOCK 3 CANT MINE STONE

### ISSUE THREAD

**Issue by awolanin6611** [FTBTeam/FTB-Modpack-Issues#1999]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

Currently having an issue where I cant break stone with any tool. It doesnt give item

### Steps to reproduce

1: start up modpack
2: load world
3:try and break block with any tool

### Expected behaviour

I expect to get the block I break,

**Comment by awolanin6611** [comment]
Yes locally the game runs as expected but when I go to my hosted server I cant break stone

**Comment by awolanin6611** [comment]
Currently using APEX HOSTING.

**Comment by Sunekaer** [comment]
It does sound like there is missing files on download of the server install, im not able to recreate this issue in my testing.
Please reinstall the server and if it still happens provide the installation log for the server
