### ISSUE TITLE
[Bug]: Enderium Ingot

### ISSUE THREAD

**Issue by Furious85** [FTBTeam/FTB-Modpack-Issues#20]
### Modpack

FTB OceanBlock

### Modpack version

1.1.0

### Describe the bug

Enderium Ingot is only craftable with mini utilities ender dust which is not easily obtainable and its should also be able to use ender pearl dust

### Steps to reproduce

check the enderium ingot and blend recipe in jei

### Expected behaviour

Add ender pearl dust to enderium recipe

**Comment by neonbladez2** [comment]
Someone has made an issue already regarding that if i remember correctly, but its nice to know that its an issue for other people as well :)

**Comment by Sunekaer** [comment]
duplicate of #2
