### ISSUE TITLE
[Bug]:  compacting drawer not intaking items

### ISSUE THREAD

**Issue by TELOC** [FTBTeam/FTB-Modpack-Issues#200]
### Modpack

FTB University 

### Modpack version

1.2.0

### Describe the bug

Compacting drawer refuses to intake items (at the end of the video I again clicked on it and no items were stored) only occurs from my knowledge after placing the compacting drawer on top of a cobblefordays generator also may result in the item not loading in a sprite when picked up after breaking it for a short period of time. Blocks placed into the drawer will become invisible however still maintain a slot in the inventory. May cause the world to save and send you back to the menu if you can store in it.

### Steps to reproduce

Place cobblefordays generator down .
Place compacting drawer on top.
Wait for the drawer to display the 2x compressed cobblestone. 
Now it will not store any item if it does it gets worse as it may cause "Illegaljavaargument" (Only item in my world that wasn't loaded with generation)

### Expected behaviour

The cobblestone input from the generator would enter the smallest slot then the compressed versions would be shown with correct values proportional to the cobblestone that is inside the compacting drawer.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/142746708-de0d516f-0d47-4691-86b8-2b5a5146189c.png)
It's working fine for me?

**Comment by Raidobw2** [comment]
Sounds fixed, haven't heard from user in 25 days, close at wish Aaron
