### ISSUE TITLE
[Bug]: Magmator only generates 10,000 FE/t

### ISSUE THREAD

**Issue by stinyc** [FTBTeam/FTB-Modpack-Issues#2001]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0

### Describe the bug

The nitro tier Magmator from Powah says that it produces 40,000 FE/t, however when pumping them full of lava they only generate 10,000 FE/t.

### Steps to reproduce

1. Place nitro Magmator
2. Fill with lava
3. Pump into flux network and see it only produce 10,000 FE/t

### Expected behaviour

Should either produce 40,000 FE/t, or should have its tooltip updated.

**Comment by Sunekaer** [comment]
From my testing it is going up by 40k, but for very 10k FE it is using 1 bucket of lava.
which is correct, to my knowledge, as better version of the machine just allows you to burn the lava faster

**Comment by stinyc** [comment]
I'm using ultimate tier Mekanism pipes with a surplus of lava (the amount of lava in the pipes is increasing while the machines are running) and it's only generating 10k FE/t.

**Comment by Sunekaer** [comment]
Please open an issue at https://github.com/Technici4n/Powah/issues as i can't recreate this issue, maybe they can see where it goes wrong

**Comment by stinyc** [comment]
![2022-11-17_20 45 22](https://user-images.githubusercontent.com/20892446/202597751-667262cb-da6f-4085-913b-e478cbb3140c.png)
![2022-11-17_20 45 27](https://user-images.githubusercontent.com/20892446/202597753-6d672229-367c-40ff-a6c5-19da07fb8006.png)
Here are screenshots of it in a creative test world. A creative lava tank pumping into the highest tier Magmator only produces 10k FE/t. I have also posted an issue on the Powah project here: https://github.com/Technici4n/Powah/issues/50
