### ISSUE TITLE
[Bug]: Wooden Plank Ingredient is Broken

### ISSUE THREAD

**Issue by zziobro7** [FTBTeam/FTB-Modpack-Issues#2004]
### Modpack

Direwolf20 1.18

### Modpack version

1.10.0

### Describe the bug

All recipes that use wooden planks are broken. JEI shows only "bamboo bundles" as craftable in place of certain wood plank recipes.

### Steps to reproduce

log into server
get log
make into planks
attempt to make crafting bench
check JEI for crafting bench recipe 

### Expected behaviour

wood planks make a crafting bench

**Comment by TheonlyTazz** [comment]
yea, small messup on our side, this can be resolved by disabling
unify.js line #793
`replaceIO("#forge:storage_blocks/bamboo", "bambooeverything:bamboo_bundle");`
by just adding // at the start of the line

this can be done directly on the server and after restart it shall be fixed, a hotfix will be shipped soon
