### ISSUE TITLE
[Bug]: Agronomic Sourcelinks don't work in main dimensions

### ISSUE THREAD

**Issue by melbellrocks** [FTBTeam/FTB-Modpack-Issues#2005]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

I am unable to generate any Ars Nouveau source with agronomic sourcelinks in my normal Stoneblock dimension.  I can use them inside Compact Machines, and I can use other sourcelinks in my Stoneblock dimension (I tried volcanic ones, for example, and they work as expected).  I also tried with various different crops, including cactus on both sand and snad, industrial hemp, and magebloom.  I also tried the main dimensions of other players on the server, still with no result.

I believe it was working previously, but I'm not sure when it stopped, perhaps with the 1.3.0 update?  Not sure if any logs are useful in a case like this, or where to even start troubleshooting.

### Steps to reproduce

1. Place Agronomic Sourcelink and a source jar in my main Stoneblock dimension.
2. Plant something.
3. Wait.

### Expected behaviour

Agronomic sourcelink should generate source and place it into the source jar when the plant grows.

**Comment by melbellrocks** [comment]
It gets weirder.  After a server restart I can now successfully use the agronomic sourcelink in one player's dimension, but still not mine or another person's.

**Comment by ukmcplyr** [comment]
I'm seeing the same, ish. Agronomic Sourcelinks didn't work the first time I tested them situated next to a Create tree farm. One random restart later they work, add and another restart and the source entities stop spawning.

**Comment by melbellrocks** [comment]
Last night I was able to use my sourcelinks as expected.  Randomly breaking and working again will make this very hard to track down. :(

**Comment by ukmcplyr** [comment]
I can't reproduce either. A dozen or so clean 1.3.0 worlds split between both single-player and server and every time the sourcelink works ex expected first time.

**Comment by melbellrocks** [comment]
Furthermore, last night after I logged in and found a working agronomic sourcelink, I had another one, same setup, in the same dimension (my main Stoneblock dimension) that was NOT working...at the same time.  And I'm watching the jars to determine if it's working or not, I don't assume that I will always see particles.

**Comment by Raidobw2** [comment]
Could be the same problem that we found in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1792 especially after hearing this:

> It gets weirder. After a server restart I can now successfully use the agronomic sourcelink in one player's dimension, but still not mine or another person's.
