### ISSUE TITLE
[Bug]: Direwolf20 1.18.2 crafting recipes

### ISSUE THREAD

**Issue by cursher212** [FTBTeam/FTB-Modpack-Issues#2006]
### Modpack

Direwolf20 1.18.2

### Modpack version

1.10.0

### Describe the bug

in 1.9.1 the crafting recipes were normal now in 1.10.0 everything requires bamboo blocks and you can use wood

### Steps to reproduce

install 1.10.0

### Expected behaviour

fix crafting recipes

### Screenshots

![image](https://user-images.githubusercontent.com/118467485/202507400-aa73c182-5f6d-4a33-b15f-204bee938ec5.png)

**Comment by Sunekaer** [comment]
Should be fixed, in 1.10.2
