### ISSUE TITLE
[Bug]: Create train stuttering

### ISSUE THREAD

**Issue by rozbrajaczpoziomow** [FTBTeam/FTB-Modpack-Issues#2009]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0

### Describe the bug

Train that self-places tracks has issues (especially when going at high speeds)
https://www.youtube.com/watch?v=mXF3sP8QLcc

### Steps to reproduce

1. Make a create train with a deployer that places tracks ahead of the bogey
2. Drive it, see stuttering and issues when going at high speeds

### Expected behaviour

No stuttering and no game being kinda stuck

**Comment by MichaelHillcox** [comment]
Closed due to racial slur in youtube video
