### ISSUE TITLE
[Bug]: Total client crash, unplayable. 

### ISSUE THREAD

**Issue by 0debriszebra** [FTBTeam/FTB-Modpack-Issues#2010]
### Modpack

FTB Plexiglass mountain

### Modpack version

1.2.2-1.2.3

### Log Files

[crash-2022-11-17_12.24.21-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10034554/crash-2022-11-17_12.24.21-server.txt)
[MCAZIP.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10041889/MCAZIP.zip)

### Describe the bug

Crashes when the world is loaded from menu. Usually loads for a few seconds and then crashes completely. I'm no serious programmer but judging from the crash report it has something to do with dadobug's bedrock ores under my base? (soulstone). I have an automated set up mining a few ores and a little logistics train running around picking it up and dropping it off. Nothing is directly interacting with soulstone bedrock ores, but there are plenty around the area. This started happening on the 15th in 1.2.2, I rolled it back to the most recent save, no luck, same thing. Updated to 1.2.3 today and same thing. Crash report is from today ver 1.2.3. Not familiar with github or bug reporting, if you need more info or logs let me know. :)

### Steps to reproduce

Unknown. 

### Expected behaviour

The world to boot and the game to play normally, as it has been.

**Comment by Raidobw2** [comment]
I see, would you be able to add the file at `world/region/r.5.-3.mca` here? This would contain the ores that are causing the issue so I can try reproducing it. I'll also report it to the author of the mod now. Thanks

**Comment by Raidobw2** [comment]
Also, does reverting to 1.2.1 fix the issue? And does removing the block at 2897,-64,-1321 and nearby bedrock ores (using Creative mode for example) fix this when updating?

In singleplayer you can switch to creative by opening to LAN with cheats ON

**Comment by 0debriszebra** [comment]
Requested MCA file uploaded. Rolling back to 1.2.1. unsuccessful, acts the same as 1.2.2 and 1.2.3, so unable to attempt creative mode fix.

**Comment by 0debriszebra** [comment]
Works like a charm as far as I can tell! Big thanks to you and Dadobug for the quick fix. Glad to have my world back with minimal loss. Yall are fantastic. Keep up the good work. <3

**Comment by 0debriszebra** [comment]
So I had a look at the trouble block! Seems like the chest above it just disappeared, which was what the little logistics train was dumping its collected ores in. I have creates rope pully pulling this chest up into my create factory area, but instead, since the chest was gone, it was pulling on the dadobugs soulstone bedrock ore below it, which probably created the error, just in case you or the mod creator wanted to know. :)
