### ISSUE TITLE
[Bug]: Mother Silver fish can still spawn silverfish with mega torch nearby

### ISSUE THREAD

**Issue by Kangy1103** [FTBTeam/FTB-Modpack-Issues#2011]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

Motherfish still able to spawn silverfish when using a mega torch which conflicts with the quest stating a mega torch will block silverfish spawning

### Steps to reproduce

1. Follow quest for farming Mother Silverfish
2. Spawn Mother Silverfish with stasis chamber and mega torch
3. Watch silverfish spawn

### Expected behaviour

Mother Silverfish shouldn't be able to spawn silverfish

### Screenshots

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/42292756/202543921-a08288b8-96ec-4904-84d2-bb0f9c24b87e.png">

**Comment by Sunekaer** [comment]
Not a bug

**Comment by Kangy1103** [comment]
Maybe not a bug but it's definitely a conflict of information with the quest book

**Comment by ChimeraGaming** [comment]
There are summons not natural spawn. Not a bug.

**Comment by Zenith-One** [comment]
While I agree that this isn't a bug, in that the behavior is correct, it is also true that the quest book tells you that a mega torch will prevent those spawns. The fact that the quest text is wrong is the error here, not the spawning behavior.
