### ISSUE TITLE
[Bug]: No recipe for Torch Bow

### ISSUE THREAD

**Issue by Kangy1103** [FTBTeam/FTB-Modpack-Issues#2012]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

The torchbow doesn't have a recipe so is unable to be crafted

### Steps to reproduce

1. Search "Torchbow" in REI
2. Left click or press R on Torchbow
3. Nothing happens

### Expected behaviour

Torchbow recipe should show to enable it to be crafted

**Comment by Sunekaer** [comment]
That is intented, you can get the bow from quest reward.
