### ISSUE TITLE
[Suggestion]: Consider adding Tool Belt mod

### ISSUE THREAD

**Issue by Kangy1103** [FTBTeam/FTB-Modpack-Issues#2013]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Not a problem exactly, more QoL of having so many tools for different things

### Mod suggestion

Tool Belt: https://www.curseforge.com/minecraft/mc-mods/tool-belt

**Comment by Sunekaer** [comment]
Mod has already been suggested and declined, thanks for your suggestion
