### ISSUE TITLE
[Suggestion]: fix server files for linux

### ISSUE THREAD

**Issue by Xplodin** [FTBTeam/FTB-Modpack-Issues#2014]
### Modpack

ALL

### Is your suggestion related to a problem? Please describe.

server files fail to include kubejs scripts on ubuntu 20.04

some of them get excluded and are missed

### Mod suggestion

just do things right for once and actually use correct server file formats.

Itd be a lot easier for everyone

**Comment by Raidobw2** [comment]
Does reinstalling the server with the server installer correctly downloads the missing kubejs folder?

**Comment by Xplodin** [comment]
Ill try to capture the output. But ill usually go through 2 installs before resorting to client to pickup the missing kubejs scripts

**Comment by Xplodin** [comment]
May I ask how I can get a capture for the install into a text file? When I SSH it goes so fast that I cant get the beginning of the text

**Comment by ukmcplyr** [comment]
@Xplodin you can use something like

```
../serverinstall_100_2288 2>&1 |tee serverinstall.log
```

**Comment by Raidobw2** [comment]
That would be great yup. If you manage to get a capture of the log the way ukmcplyr suggested (where some files fail to be downloaded), let me know as it will be useful

**Comment by Xplodin** [comment]
https://gist.github.com/Xplodin/4ffadb098c00d73f6d0ee180ddac6ba6

just updated the server, havent tested running it yet but here is the log for the 1.4.1 update
