### ISSUE TITLE
[Bug]: Crash on adding some custom casing on compact drawer frame

### ISSUE THREAD

**Issue by JetFlightGit** [FTBTeam/FTB-Modpack-Issues#2016]
### Modpack

FTB ST3

### Modpack version

1.2.1

### Describe the bug

Crash when trying to change look of framed compacting drawer.
For example adding oak drawer as the look

### Steps to reproduce

1.  Add oak drawer as look into crafting table with framed compacting drawer.
2. Client will crash

### Expected behaviour

Saving world screen then crash

**Comment by Raidobw2** [comment]
Hi, thanks for reporting, could you add your crash log? Thanks a lot!
