### ISSUE TITLE
[Bug]: game crash 

### ISSUE THREAD

**Issue by Jdollery23** [FTBTeam/FTB-Modpack-Issues#2018]
### Modpack

FTB stone block 3

### Modpack version

1.3.0

### Describe the bug

After giving the project e transmutation table the alchemical book and trying to use the table your game crashes every time 

### Steps to reproduce

1. Get transmution table 
2. Give it the alchemical book 
3. Game not repond 
4. Game crash 

### Expected behaviour

Game not to crash when one table

**Comment by Raidobw2** [comment]
Hi, thanks for reporting, if the game crashes could you add your crash log? That would be useful to us, thanks. It's in the `crash-reports` folder

**Comment by NordicGamerFE** [comment]
I have this also, The game just hard freeze with nothing in the logs. tho based on #2054 its the 4096 power flowers causing the issue.

**Comment by NordicGamerFE** [comment]
Ok i did some testing, but i went into the server where I have this issue, and I found out if I leave the game long enough it will start working again. in debug there is a lot of the same line 
![image](https://user-images.githubusercontent.com/18188155/202868546-8de3000c-e03b-4f44-81c3-a6bace7e369b.png)

**Comment by Sunekaer** [comment]
Should be solved in the newest update of the pack
