### ISSUE TITLE
[Bug]: Can't crush silver ingots in Mekanism Crusher

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#202]
### Modpack

Ftb University 

### Modpack version

1.2.0

### Describe the bug

Can't crush silver ingots (TE) into silver dust using mek machines, can only do it in the IE crusher

### Steps to reproduce

Theres no recipe for it.

### Expected behaviour

Silver ingots > Dust in a  Mek Crusher

**Comment by aaronhowser1** [comment]
Fixed
