### ISSUE TITLE
[Bug]: NullPointerException KubeJS

### ISSUE THREAD

**Issue by 4w3Official** [FTBTeam/FTB-Modpack-Issues#2020]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0

### Describe the bug

`[16:05:57] [ERR  ] Error occurred while handling scheduled event callback: Wrapped java.lang.NullPointerException: Cannot invoke "dev.latvian.mods.rhino.SharedContextData.getExtraProperty(String)" because "cx.sharedContextData" is null (server_scripts:_core/inworldevent/utils.js#36)`

### Steps to reproduce

-/-

### Expected behaviour

-/-

**Comment by Sunekaer** [comment]
Duplicate of #1729
