### ISSUE TITLE
[Bug]: Various seeds etc become unplantable on farmland

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#2021]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.0, 1.3.0

### Describe the bug

Attempting to plant any of: carrots, potatoes, beetroot seeds, wheat seeds and magebloom seeds on farmland (hydrated and not) no longer works on one of the servers I'm on.

Strangely, planting melon/pumpkin and hemp seeds from Immersive *does* work as expected.

Everything above except beetroot has worked previously in early-game. Upgrading to 1.3.0 makes no difference. Notably though, a clean 1.3.0 single-player world works as expected.

Nothing at all printed to logs. Suspect this server instance is hosed after previous crashes but posting in case it's a bona fide bug.

### Steps to reproduce

N/A

### Expected behaviour

Eg wheat seeds plant on farmland as expected

### Screenshots

![Screenshot](https://gcdnb.pbrd.co/images/5AcyC5KeaWNT.png?o=1)

### Additional information

ETA:

Seems at least one other has experienced similar:

https://discord.com/channels/372448486723158016/1037082109891842048/1041593158242406423

After a bit of trial and error, I can get wheat seeds to plant as in the screenshot above. Random locations around my spawn at Y 0 refuse to plant whereas Y 2 works.

**Comment by ukmcplyr** [comment]
Turns out I can repro in a clean 1.3.0 single-player test world:

![Screenshot 1](https://gcdnb.pbrd.co/images/3xdOm7eJ9kIG.png?o=1)
![Screenshot 2](https://gcdnb.pbrd.co/images/YZsaNj0WM0NO.png?o=1)

The farmland blocks without planted seeds won't accept them.

I didn't test every seed/veg but minimally hemp seeds work fine whereas mage bloom, wheat and beetroot do not.

**Comment by TheonlyTazz** [comment]
check your light level
> A [light](https://minecraft.fandom.com/wiki/Light) level of 9 or higher at the plant. This doesn't have to be sunlight, so [torches](https://minecraft.fandom.com/wiki/Torch) let crops grow at [night](https://minecraft.fandom.com/wiki/Night) or underground.

**Comment by ukmcplyr** [comment]
Gah. That's embarrassing... It was the light level. Sorry for the noise!
