### ISSUE TITLE
[Suggestion]: Make Tinker's Blood compatible with Biomes a plenty for crafting Flesh Blocks

### ISSUE THREAD

**Issue by bvers6** [FTBTeam/FTB-Modpack-Issues#2022]
### Modpack

FTB Inferno

### Is your suggestion related to a problem? Please describe.

When trying to create flesh block's Tinker's bucket'o Blood is incompatible as a method of using blood to create flesh blocks. Apparently this process requires Biomes a plenty blood to create fleshblocks via lava generator. Seems like an oversight and wonder if we could get it added to use Tinker's construct blood as an easy way to acquire Flesh Blocks.

**Comment by tyler489** [comment]
Not an oversight, as the biomes o plenty blood naturally makes flesh blocks, in order to have tinkers work it would require another mod for that interaction.

**Comment by Saereth** [comment]
this is not an oversight as tyler said, this is working as intended
