### ISSUE TITLE
[Bug]: Worldgen Problems

### ISSUE THREAD

**Issue by zziobro7** [FTBTeam/FTB-Modpack-Issues#2023]
### Modpack

Direwolf20 1.18

### Modpack version

1.10.1

### Describe the bug

Really odd worldgen with things like burnt cable etc taking the place of other blocks. 

### Steps to reproduce

Started a fresh world in 1.10.1
Walk around until you see somthing strange. 

### Expected behaviour

Nomral worldgen

### Screenshots

See this imgur album: https://imgur.com/a/l60U6pg

**Comment by TheonlyTazz** [comment]
as we have discussed in discord and per DMs, we both couldnt replicate this with the official server files provided by FTB Server Installer, please contact your host.

if this is replicatable in singleplayer or through our official server installer, feel free to create a new ticket please
