### ISSUE TITLE
[Bug]: Worldgen often freeze at 100% since 1.10

### ISSUE THREAD

**Issue by piedrrum** [FTBTeam/FTB-Modpack-Issues#2024]
### Modpack

Direwolf20 1.18

### Modpack version

1.10.1

### Log Files

When not loading:
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10036944/debug.log)
When loading and let some empty chunks:
[debug-1.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10036976/debug-1.log)

### Describe the bug

When generating a world in 1.10.0 or 1.10.1, the loading screen often freeze at 100% and remains stuck (for ever ?). Sometimes it's before 100%.
Sometimes it does not freeze and works ~1/3 time.
When loading works, going fast forward into the new world lead to some empty chunks that are never loaded.
It was not happening in 1.9 versions. Going fast forward in a world was finishing by loading chunks in 1.9 versions.

### Steps to reproduce

Generate a normal map in 1.10.0 or 1.10.1

### Expected behaviour

Joining world and begin to play, then go fast and chunks generate.

### Screenshots

![image](https://user-images.githubusercontent.com/60243235/202591695-53847f63-4163-4e7f-bb00-4e0374dba7bf.png)

### Additional information

We are at least two (saw same error on the FTB discord) to have this issue.

**Comment by Gaz492** [comment]
MineTogether received an update in the latest version of the pack, which may have resolved the issue.
If the issue is still there do let us know
