### ISSUE TITLE
[Bug]: Crash due to corrupt serverconfig file/s 

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#2031]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.0 minimally

### Log Files

[crash log](https://pste.ch/aqemabezad.pl)

### Describe the bug

Note: This bug has come up on Discord half a dozen times in the past week, maybe more. Not directly affected myself but I've spent some time on RCA.

The common theme is that a user will exit single player one day and then next one or more files under `saves/Blah/serverconfig/` will contain only NULs, leading to a crash:

```
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file constructionwand-server.toml of type SERVER for modid constructionwand
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:47) ~[fmlcore-1.18.2-40.1.84.jar%23255!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60) ~[fmlcore-1.18.2-40.1.84.jar%23255!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.18.2-40.1.84.jar%23255!/:?] {}
[...]
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.4.jar%237!/:?] {}
```

The first few times I saw it reported, `serverconfig/ironfurnaces-server.toml` was the only file that got filled with NUL bytes but in the case below, 30/30 files got eaten and I've seen, from memory, at least one more case where multiple files were nerfed.

The last person I helped with this bug shared their save and logs with me with permission to post them up here:

[nulconfbug.zip](https://drive.google.com/file/d/1hWTPkxPB_ltqUNrsM8vXMCgGmAt1ursq/view?usp=sharing)
 - /nulconfbug/02/logs
 - /nulconfbug/02/save (contains working serverconfig that was regenerated)
 - /nulconfbug/02/serverconfig (contains corrupt serverconfig files pre-regen)

I came across MinecraftForge/MinecraftForge#9122 after a decent amount of searching but it's not exactly a 100% match. Every user I've helped beyond "re-gen and try again" has been running Windows.

Attempts to repro on Linux with many, forced kills (SIG{KILL,TERM,HUP}) yielded no corruption.

Likely missed a vital detail along the way here so please feel free to ding me on Discord for more.

### Steps to reproduce

On Windows:
1. Open, play, close SB3 1.2.0
2. Open again some time later and see if serverconfig files get corrupted.

### Expected behaviour

No crash, no corruption

### Additional information

I'll ping the person who provided the referenced save etc and ask them to make themselves known.

**Comment by Sunekaer** [comment]
Sadly something there happens a lot with Forge config system, there is no way we can fix this sorry.
All we can hope is that Forge fixes this, but this has been an issue since the changed to using toml files

**Comment by chorbintime** [comment]
> Sadly something there happens a lot with Forge config system, there is no way we can fix this sorry. All we can hope is that Forge fixes this, but this has been an issue since the changed to using toml files

Fuzs created a mod which fixes this: https://www.curseforge.com/minecraft/mc-mods/night-config-fixes
