### ISSUE TITLE
[Suggestion]: Storage quest

### ISSUE THREAD

**Issue by Reithsaw** [FTBTeam/FTB-Modpack-Issues#2032]
### Modpack

FTB Stoneblock 3 V1.3.0

### Is your suggestion related to a problem? Please describe.

Can you change/add the requested items for the disks of AE2 for AE2 AND AE2Things ?

Kind regards,

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/205217154-3fcdd0e3-f131-42fc-978d-997b1662cf3a.png)
