### ISSUE TITLE
[Bug]: chicken catcher

### ISSUE THREAD

**Issue by WanweiInMod** [FTBTeam/FTB-Modpack-Issues#2034]
### Modpack

FTB Stoneblock3

### Modpack version

1.3.0

### Describe the bug

failed to use "chicken catcher" items

### Steps to reproduce

1.right click chicken mob with holding item "chicken catcher"
2.see error

### Expected behaviour

chicken mob turn into "chicken" item

**Comment by NordicGamerFE** [comment]
Are you trying to catch a vanilla chicken, In that case that is not possible. You can right click a vanilla chicken with a book to make a smart chicken, that will produce eggs in a roost
