### ISSUE TITLE
[Suggestion]: Thermal Evaporation Plant

### ISSUE THREAD

**Issue by NordicGamerFE** [FTBTeam/FTB-Modpack-Issues#2035]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Reduce the heat requirements for the Thermal Evaporation Plant because you cant make the advanced version nor can you really make the heat go up

**Comment by NordicGamerFE** [comment]
After some research i found out that you can hook resistive heaters to the Thermal Evaporation Plant, I am used to using the solar panels to get heat, I think many other people are to and a quest to explain this could probably be benefical

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/205219041-e9e82509-c25f-49be-9896-1f6a2a87e127.png)

**Comment by NordicGamerFE** [comment]
That is some hot stuff right there
