### ISSUE TITLE
[Bug]: Radiation still present after loading a backup

### ISSUE THREAD

**Issue by chrisg89822** [FTBTeam/FTB-Modpack-Issues#2036]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

A Mekanism Fission Reactor exploded irradiating the area. After reloading a backup before the reactors activation, the radiation still existed.

### Steps to reproduce

1. Build a Mekanism Fission Reactor
2. Make a world backup
3. Make the reactor explode
4. Load the Backup

### Expected behaviour

I expected the game state to return to how it was at the time of the backup creation.

**Comment by TheonlyTazz** [comment]
radiation is probably stored outside the stuff that is being backed up, 
you can however use cheats to clear the radiation:
`/mek radiation removeAll`

or.. handle radiation with care
