### ISSUE TITLE
[Suggestion]: Add Botania's Buried Petals to SquatGrow's Blacklist

### ISSUE THREAD

**Issue by WindFreaker** [FTBTeam/FTB-Modpack-Issues#2037]
### Modpack

StoneBlock 3

### Is your suggestion related to a problem? Please describe.

The mod in Stoneblock 3 that allows you to spam crouch and grow trees and other crops also causes Botania's buried mystical petals to grow. While these buried petals are technically functional, they also serve a decorative purpose for their particle effects. Without the buried petals blacklisted they are basically impossible to build with, as any accidental crouch will cause them to sprout up into double tall flowers.

This is a general suggestion and not specific to Stoneblock 3, that just happens to be the modpack I'm playing at the moment.

**Comment by VorpalLemur** [comment]
There's another issue with the botania flowers..... squatting can grow a normal botania flower into its tall variant.   Some botania multiblocks (thinking of the mana enchanter in particular here) use botania flowers as structural components.  If you squat near your mana enchanter, you'll grow the flowers, breaking the enchanter instantly.    Quite annoying.

**Comment by tyler489** [comment]
Try putting a piece of string over the flowers, personally i liked being able to squat and grow these flowers.

**Comment by WindFreaker** [comment]
To me that doesn't feel like a proper solution. The string is faint but noticeably visible.
