### ISSUE TITLE
[Bug]: Server crashes after placing compacting drawer

### ISSUE THREAD

**Issue by Omega172** [FTBTeam/FTB-Modpack-Issues#2038]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0 upgraded from 1.2.0

### Log Files

https://pastebin.com/Ne1p1GGc

### Describe the bug

After placing a compacting drawer under a hopper to collect chicken resources the server crashed, every time after starting the server and someone logs on the server crashes.

### Steps to reproduce

Start a server, have a roost with a chicken (I used a gold chicken) in it placed atop a hopper connecting into a compacting drawer and the server should crash, place the compacting drawer last

### Expected behaviour

The expected behavior is that the hopper should be able to feed the roost resources into the compacting drawer without crashing

### Additional information

After testing it works just fine in single player not on server though

**Comment by Sunekaer** [comment]
Seems like the JAVA install got messed up, can you try and fresh install of JAVA and the pack

**Comment by Omega172** [comment]
Attempted fresh install of the pack, same outcome

Switching to OpenJDK 1.8.0 fixed it
