### ISSUE TITLE
[Bug]: Infinite energy from Powah Ender Cells 

### ISSUE THREAD

**Issue by active666** [FTBTeam/FTB-Modpack-Issues#2039]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

The ender cells from Powah will charge the batteries from Powah without using any power

### Steps to reproduce

1.Charge any tier Powah battery
2.Place it in any tier Ender Cell
3.Battery is consumed
4.Place an empty battery of any tier into the ender cell and it will be charged without consuming any energy. This allows you to completely fill nitro tier batteries with a single starter battery for example.

### Expected behaviour

energy should be consumed when charging batteries 

### Screenshots

![image](https://user-images.githubusercontent.com/9612124/202771517-3111194c-d40d-4ce5-a5d3-ca1f3ae012ec.png)
![image](https://user-images.githubusercontent.com/9612124/202771562-ce9b5157-f448-4bb5-8366-fc4e6f053c5a.png)
![image](https://user-images.githubusercontent.com/9612124/202771809-6bc4387f-7365-424f-af12-2dd58b727d3a.png)

**Comment by Sunekaer** [comment]
https://github.com/Technici4n/Powah/issues/53

**Comment by Sunekaer** [comment]
Should be solved already
