### ISSUE TITLE
[Bug]: /event toggle

### ISSUE THREAD

**Issue by perennialpersephone** [FTBTeam/FTB-Modpack-Issues#2040]
### Modpack

Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

/toggle events is only disabling certain events and not others. Wandering Traders aren't spawning when enabled (Haven't placed a "No Soliciting" sign), Bees and Sticks still spawn even with toggled off. Server "Going for tea" is disabled and working correctly.

### Steps to reproduce

1.) /toggle events (pick your choice)
2.) Chat displays the event has been toggled OFF
3.) Loot Bee & Stick events are still spawning when toggled OFF. Wandering Trader isn't spawning when toggled ON.

### Expected behaviour

When toggled off an event should not be happening, when toggled on it should.

### Additional information

This problem is happening on a server (haven't tested in single player) Both OP'd and Non OP'd players have tried disabling events and they are still spawning/not spawning like they're supposed to.

**Comment by tyler489** [comment]
Events are per player, I havent noticed any issues with disabling myself personally, although traders are EXTREAMLY rare, like once every 2 or 3 hours.

**Comment by Renari** [comment]
I haven't encountered this issue while playing on a server, do you have other players near you that have events on that you do not?

**Comment by perennialpersephone** [comment]
I live with someone, though even when they're offline I have these events spawn, at the time of typing this I'm staring at a loot bee inside my wall. I'm not the only player on my server having this issue but I've had a server up since day 1 of this pack releasing and have yet to see a single wandering trader, we've had maybe 3 spawn for any of the 7 players on our server... No idea why I keep seeing events spawning unless it's because my offline partner having them enabled is the issue?

**Comment by Sunekaer** [comment]
Events has no relation to if someone else is no, its fully based on per player.
The less events the system has to pick from the less chance there is of you getting an event, special if the events you have enabled are very low chance ones.

**Comment by Sunekaer** [comment]
Im not able to replicate this issue.
If you do /ftblibrary nbtedit player <PlayerName>
Then open KubeJSPersistentData -> disabledEvents, what is it showning here for you?

**Comment by perennialpersephone** [comment]
0: ftbstoneblock:loot_bee
1: ftbstoneblock:wanderingtrader
2:ftbstoneblock:stick
3:ftbstoneblock:tea

LootBeeCount: 390.0
Timer: 7306601.0

**Comment by Sunekaer** [comment]
Okay so you have all events disabled?

**Comment by perennialpersephone** [comment]
Yes, I have ALL events disabled for me personally.

**Comment by Sunekaer** [comment]
yes?
