### ISSUE TITLE
[Bug]: 2 bugs one post. Missing Animation on compacting machines. Quest category complete did not turn green.

### ISSUE THREAD

**Issue by SGZ-Creations** [FTBTeam/FTB-Modpack-Issues#2045]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0 

### Describe the bug

* Issues 1
The animation for compact machines are gone or disabled can be on mod side or packs side witch i don't know. Ether way it seem to take items rather than giving anything when the process is on going.
![image](https://user-images.githubusercontent.com/59801736/202849789-7ed751dc-55e9-49e5-8a7b-db670ef22ea0.png)
![image](https://user-images.githubusercontent.com/59801736/202849694-b1f9384b-731c-411d-88b7-d51c0e74f337.png)

* Issues 2
I've completed all quest in Exploration witch some how is not completing the category. Since it haven't switched to the green look. I even went trough all tabs to see if one where missing (Told to do by ukmcplyr (Discord)). Witch wasn't the case.
![image](https://user-images.githubusercontent.com/59801736/202850089-300043e7-e610-4fd1-928f-ca4a290cf862.png)
![image](https://user-images.githubusercontent.com/59801736/202850669-afad37c9-0a62-4872-9e82-1c670b7b47ac.png)

### Steps to reproduce

* Issue 1:
1 Build the compact machines setup.
2 Make the "compact machines wall".
3 see the animation missing when the pearl is dropped.

* Issue 2:
1 Work on quest under Exploration.
2 Complete the Exploration category.
3 See it won't go green.

### Expected behaviour

Issues 1: Showing animation to see where items went. Issues 2. Turn green when all quest completed.

**Comment by Sunekaer** [comment]
1. from what i remember it sometimes just stops working.
2. you havent come far enough in Create to see the next quest.
