### ISSUE TITLE
[Bug]: Create Mechanical Crafter overstresses Electric Motor

### ISSUE THREAD

**Issue by RudiHansen** [FTBTeam/FTB-Modpack-Issues#2048]
### Modpack

StoneBlock 3

### Modpack version

1.18.2

### Describe the bug

I have setup a wall of 21 Mechanical Crafters connected directly to one Elictric Motor, but it does not run since it's overstressed.

So I tried to remove some of the Mechanical Crafters so there is only 18 in the wall, and then it runs with no problem.

It does not matter at what speed i set the Elictric Motor, with 18 Crafters it will run anything from 256 RPM to 1 RPM.
But when I place the 19'th Crafter, it stopps.

### Steps to reproduce

Place 18 Mechanical Crafters to an Electric Motor to see it run, add one more and it stops.

### Expected behaviour

That the Electric Motor should handle 21 crafters and more even.

**Comment by Sunekaer** [comment]
Hi 
Yes youll have to make a strong boiler setup :)

**Comment by RudiHansen** [comment]
I do not understand your comment.

I replaced the Electric Motor with 4 x Water Wheels, and that can run the 21 Crafters without any problems.
So it this not an error with the Electric Motor?

I can see you closed the case, so I do not understand are you fixing or dismissing this issue?
