### ISSUE TITLE
[Suggestion]: Add some visible tips to the loading screen. (or the Tips mod)

### ISSUE THREAD

**Issue by ariosos** [FTBTeam/FTB-Modpack-Issues#2049]
### Modpack

StoneBlock 3

### Is your suggestion related to a problem? Please describe.

In MineTogether's chat, 90% of the questions I see, users don't seem to know about the questbook, or the hotkey for the questbook, or ask the same series of (very, VERY basic) questions. So, a few off the top of my head.

1 - The Loot Bee is your friend. Don't kill him, but collect the loot before it despawns!
2 - Click "U" when hovering over an item to see its' uses.
3 - Veinmining is in the pack, but veinmining stone is disabled. 
4 - You must dig 1,000 blocks to reach the nether, and further for the End.
5 - Veinmine andesite to make long tunnels.
6 - Use cardboard boxes to pick up spawners!
7 - Crops require a light level of 8 to grow.
8 - Stand within 16 blocks of a spawner to activate it.
9 - Hold your up key when hovering over a Create item to ponder it.
10 - "READ THE QUEST BOOK!!!" (~ key) It explains 90% of your questions.
11 - Chance Cubes. are evil. Open them FAR away from your base, if you dare...
12 - Passive mobs require grass, high light level, no existing nearby passive mobs, and the player must be 24 blocks away.
13 - Hammers break cobble into gravel, dirt, sand and dust.
14 - Using a crook on any type of dirt, sand and leaves will give you items.
15 - Bonemeal grass blocks for hemp seeds.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/tips

Add tips for Frequently Asked Questions.

**Comment by Sunekaer** [comment]
Thanks ariosos!

**Comment by credomane** [comment]
> 7 - Crops require a light level of 8 to grow.

Just a heads up Industrial Hemp is the exception to that rule. It requires a light level of 12! This catches my buddy every time when he makes an indoor farm for the hemp. What's bad it he knows modded minecraft infinitely better than me and I have to come fix his indoor hemp farm when they don't work. All light sources besides the sun (which isn't "in" this pack) output 14. So you need a light source within 2 blocks of the Industrial Hemp for it grow. It can be a real PITA sometimes.
