### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#2054]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Replace expanded exchange with this mod https://www.curseforge.com/minecraft/mc-mods/project-expansion/files/4077697

it has a few more features, and a few more bug fixes. for instance the 4096 power flowers that is currently crashing my game every time I open the transmutation tablet because expanded exchange sends each update individually per flower.

**Comment by NordicGamerFE** [comment]
@Sunekaer Has project expansion been allowed to use assets from extendedexchange?

**Comment by NordicGamerFE** [comment]
also @tyler489 if you didnt notice expandedexchange is owned by ftb so its highly unlikely that it will be replaced

**Comment by tyler489** [comment]
I noticed, but I can still hope, as its impossible to continue playing if I cant open my transmutation tablet because its getting packet spammed.

**Comment by NordicGamerFE** [comment]
They will fix the issue just be patient there is always some bugs in the start.

**Comment by Sunekaer** [comment]
We wont be replacing the mod, we are working on fixing the issues
