### ISSUE TITLE
[Bug]: RFToolsStorage:Can't pull items from storage scanner or tablet(scanner)

### ISSUE THREAD

**Issue by mutley7675** [FTBTeam/FTB-Modpack-Issues#2055]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

When I try and pull any item out of storage scanner, it will not allow me to pull them into my inventory nor will the tablet.  I can craft items from storage scanner and tablet.  At one point it seem to fix itself for about an hour or so but then went back to not letting me grab items.

### Steps to reproduce

Unsure.

### Expected behaviour

restart might have cleared it up but did not.

### Screenshots

none

### Additional information

none

**Comment by mutley7675** [comment]
- Figured this out.  In lower left of this picture you see the blue and orange boxes.. when my inventory was full ui was placing items in the orange box preventing me from pulling items out of my inventory.![image](https://user-images.githubusercontent.com/60831266/204833925-bd3d93c6-a026-40b5-b5df-fa4785b88ff1.jpeg)

**Comment by Raidobw2** [comment]
I see, thanks for the feedback, in that case I can assume this is sorted out. RFTools transfers stacks directly in your inventory (and not on your cursor for example).
I'll be closing this then, since it seems to be working as normal
