### ISSUE TITLE
[Bug]: [Stoneblock 3] Raw Zinc, Bauxite, Silver and Nickel missing Mekanism processing

### ISSUE THREAD

**Issue by LuciusV** [FTBTeam/FTB-Modpack-Issues#2056]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0

### Describe the bug

Materials mentioned above don't have Clumps/Shards/Slurries, breaking Mekanism processing lines design

### Steps to reproduce

1. Try to put Raw Ore or block of Raw Ore in Purification Chamber/Chemical Injection Chamber/Chemical Dissolution Chamber
2. Machine does not accept item

### Expected behaviour

Ore processing unification for all raw ores

**Comment by Sunekaer** [comment]
#1965
