### ISSUE TITLE
[Bug]: Yellow ME Glass cable don't use the right tag.

### ISSUE THREAD

**Issue by MLDEG** [FTBTeam/FTB-Modpack-Issues#2057]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

I don't think it's a bug, but it's still a problem.
I wanted to make yellow AE2 cables, and the craft only requires Sulfur.

### Steps to reproduce

Use 8 Fluix ME Glass Cable and a Yellow dye.

### Expected behaviour

It would be #forge:dyes/yellow not #forge:dusts/sulfur

### Screenshots

![Capture](https://user-images.githubusercontent.com/90324978/202876035-7e2c7392-2441-4ac8-ba06-43433c61a8c1.PNG)

**Comment by perennialpersephone** [comment]
Someone else noticed! #2033 lmao
