### ISSUE TITLE
[Bug]: Computer Craft Duping Computers

### ISSUE THREAD

**Issue by trevorgolden** [FTBTeam/FTB-Modpack-Issues#2058]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

When Computer Craft computers and advanced computers are broken in survival, or creative, the block drops 2 entities 

### Steps to reproduce

1. Place down Computer/Advanced Computer
2. Break said Computer/Advanced Computer
3. Profit. 

### Expected behaviour

Place 1 Break 1 Drop 1

### Screenshots

 7 Second video of the issue https://gyazo.com/1fe9b6b1ea342ef9ae8b9c996900d78d

**Comment by Sunekaer** [comment]
Hmm im not able to recreate this in my test world, have you done any changes to the pack?

**Comment by trevorgolden** [comment]
I haven’t done any changes to the pack no, I don’t even think I’ve got
Mohist/Magma installed on the server yet, let me check with a clean install
after work today

**Comment by Sunekaer** [comment]
Thanks

**Comment by Raidobw2** [comment]
Interesting issue, if you mine the computer with your hand (hold no item) does it still duplicate it?
I've looked a bit at https://github.com/cc-tweaked/CC-Tweaked/blob/0db32bd0fe7603c8a83e62edf74130df6637df99/src/main/java/dan200/computercraft/shared/computer/blocks/BlockComputerBase.java#L150-L166 and I think that could have to do with it

**Comment by trevorgolden** [comment]
My apologies I am just now getting back to this, the issue is fixed I made a patch for it.
