### ISSUE TITLE
[Bug]: Numerous KubeJS Errors on login

### ISSUE THREAD

**Issue by NetherResonant** [FTBTeam/FTB-Modpack-Issues#2059]
### Modpack

FTB Inferno

### Modpack version

1.2.1

### Describe the bug

Loading into a multiplayer world has shown a warning nearly every time about KubeJS errors, sometimes up in the thousands, and it floods the server console as well with error messages whenever they appear. They're all the same error, and it seems to only appear when I right click with anything that doesn't directly interact with the world. As in pushing a button, opening a door, placing a block. But if I right click a block with (or even the air) with my pickaxe (or just by eating a piece of food), nothing happens and the error ticks up one. This also applies to click machines, which I was using to automatically harvest demon will crystals, and have poured thousands of errors in now that I've dug them up. They all show the same message of:

Error occurred while handling event 'item.right_click': ReferenceError: "item1" is not defined. (server_scripts:playerhandler.js#633)

### Steps to reproduce

1. Equip anything in your hands that isn't place-able.
2. Right click either block or air.
3. Run /kubejs errors to see it's tacked on another error.

### Expected behaviour

No errors to happen

### Screenshots

![kubejs errors](https://user-images.githubusercontent.com/118647125/202884700-2c535319-33a7-4cdc-a749-f060bd7d5d52.PNG)

**Comment by TheonlyTazz** [comment]
Latest version of FTB Inferno is V 1.3.0
looking at the current line of playerhandler.js

`    if ((item == 'avaritia:infinity_bow' || item2 == 'avaritia:infinity_bow') && event.player.level.dimension == 'witherstormmod:bowels'){`

Please update your modpack and make a new issue if the issue still arises
