### ISSUE TITLE
[Bug, SeedDrop]: Shears and Kama breaking grass instead of shearing it

### ISSUE THREAD

**Issue by Darkehart** [FTBTeam/FTB-Modpack-Issues#206]
### Modpack

FTB Oceanblock

### Modpack version

1.5

### Describe the bug

Only the vanilla iron shears drop the expected grass item when used to break tall grass. This item is needed by Mystical Agriculture and Botania for Earth Agglomeratio/Earth Seeds and a variety of functional flowers, respectively.

### Steps to reproduce

Left-click a tall grass while holding any shear or kama except for the vanilla shears made of iron ingots. The block will break and generate seed drops.

### Expected behaviour

The tall grass should drop itself if broken by shears or a kama.

### Additional information

I tested it and found that the problem is Seed Drops 2. I've filed a report over there, as well, but I figured if somebody else noticed and came here, there should be a record.

[https://github.com/EwyBoy/SeedDrop/issues/8](url)

**Comment by Raidobw2** [comment]
Fixed in "Seed Drop-1.16.5-2.1.2.jar", now available on CurseForge
