### ISSUE TITLE
[Bug]: ABLE TO GET ANY 3X3 CRAFTABLE ITEM

### ISSUE THREAD

**Issue by CarelessSpore** [FTBTeam/FTB-Modpack-Issues#2060]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

Able to Craft any 3X3 Item from an RF Tools Crafter with out needing the necessary items before hand. You are able to give the crafter a recipe you want it to craft. Put a Tinkers Crafting Station next to the Crafter and then shift click in from the recipe menu the items inside of the crafter and grab the item you want.

### Steps to reproduce

1. Get RF Tools Crafter (Any Tier)
2. Get Tinkers Crafting Station
3. Place Crafter next to Crafting Station
4. Get recipe into the RF Tools Crafter
5. Go back to the Crafting Station
5. Look up recipe in REI and shift click items into the Crafting Station.

### Expected behaviour

Not getting the item I have set in the RF Tools Crafter

### Screenshots

![image](https://user-images.githubusercontent.com/46659963/202888875-d39ef7ca-4fee-4c08-b91a-8514a1e18c92.png)
![image](https://user-images.githubusercontent.com/46659963/202888886-25e36e75-d4ab-4746-b5fa-e6e46ac72864.png)
![image](https://user-images.githubusercontent.com/46659963/202888894-de4e070d-a7ce-4b99-9766-21c4be603988.png)
![image](https://user-images.githubusercontent.com/46659963/202888897-16d2626f-41a7-45d4-a9fc-a031f372fd95.png)

### Additional information

Last Photo is to Show I never did the questline at all and I can still create the Rubber for Plastic.

**Comment by tyler489** [comment]
Another one for the tinkers table blacklist

**Comment by CarelessSpore** [comment]
> 

i honestly think this is a issue with REI i have tried to go to other packs that have JEI and every single one that has both RFTools and tinkers there is no issue.

**Comment by Sunekaer** [comment]
https://github.com/McJtyMods/RFToolsUtility/issues/154

**Comment by CarelessSpore** [comment]
> 

No i can still craft everything just as fine this is an interaction bug between the RF Crafter and Tinkers Crafting Station

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
