### ISSUE TITLE
[Suggestion]: Add extended crafting to automate 9×9 crafting

### ISSUE THREAD

**Issue by dj-ccd** [FTBTeam/FTB-Modpack-Issues#2061]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

I am in end game and have set up 9×9 create mechanical crafters for auto crafting infinity ingots and other non standard recipes. It takes around 4 min per ingot (including all other dependent non standard recipies) with everything maxed out. 

Create is slow and manual crafting is difficult and time consuming. 

It would be very helpful if you add extended crafting to the mod pack. Maybe add infinity ingot as part of crafting recipe so people have to set 9×9 crafter to finally automate it.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/extended-crafting

**Comment by NordicGamerFE** [comment]
Hey, I auto craft with the mechanical crafter myself. I use pretty pipes taking from a chest, each mechanical crafter i have a filter in the pipe. then for speed i use 2 motors at max speed. the crafting process is pretty quick and i would say create is not limiting me when it comes to time.

**Comment by dj-ccd** [comment]
I have 2 max speed 9×9 crafter (256rpm 8 motors). I just timed the operation. The animation itself after you insert all items and provide signal takes around 9-10 sec. You have 34 extended crafts to make a single ingot. That is 34*9 which is around 5 minutes. And if you add time to load and unload inventories it reaches 8-9 minutes. 

Please look into it as more and more people will reach endgame soon.

**Comment by Sunekaer** [comment]
extended-crafting, create is not limiting factor at all, in our testing we used LaserIO for the inserting of items and it was instant inserting and pulling.
