### ISSUE TITLE
[Bug]: Stoneblock - REI + Avaritia move items button

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [FTBTeam/FTB-Modpack-Issues#2064]
### Mod

REI + Avaritia

### Mod version

Avaritia-1.18.2-4.0.0.4-universal

### Forge / Fabric version

1.18.2 40.1.84

### Modpack & version

Stoneblock 3 - 1.2.1

### What issue are you having?

Mods + versions
-----------------------
* RoughlyEnoughItems-8.3.567
* RoughlyEnoughItems-forge-8.0.27
* Avaritia-1.18.2-4.0.0.4-universal

Can't move the items to the Avaritia crafting table with the "move items" button.

### Crashlogs

https://paste.feed-the-beast.com/view/53958f65

### Steps to reproduce

1. Move the items to the Avaritia crafting table with the "move items" button.

**Comment by Tander** [comment]
The same issue on 1.3.0

**Comment by Tander** [comment]
Here is where this error message comes from

https://github.com/shedaniel/RoughlyEnoughItems/blob/52e4a517f9809ae74d60446338460b210ef0664a/runtime/src/main/java/me/shedaniel/rei/impl/common/transfer/InputSlotCrafter.java#L68

**Comment by Tander** [comment]
error from the server log
https://pastebin.com/GwwRFSrX
