### ISSUE TITLE
[Suggestion]: Replace surface bedrock in FTB Inferno

### ISSUE THREAD

**Issue by jjjet42** [FTBTeam/FTB-Modpack-Issues#2066]
### Modpack

FTB Inferno

### Is your suggestion related to a problem? Please describe.

The bedrock roof is causing me all sorts of headaches in this pack, especially with minecolonies.
First problem is that removing bedrock is painful. Outside of capsules, you have to use the wand and dig it all out by hand.
Second Problem is that colonists simply do not like bedrock. If I want to pretty up my colony with roads or replace sections with nylium, the colonists are 0 help. They can't do anything about it. 
The miner in particular didn't want to work until I removed the bedrock in his hut's build area. He kept requesting netherrack then immediately requesting pickup in an unending loop.

My proposed solution: replace the top bedrock in new worlds with some other equivalent that plays nice with automation. (Faux Bedrock or some other block)

You could end up with 50 different workarounds and solutions for mods not playing nice with bedrock, but it would be much less of a headache to not have it at all.

**Comment by Saereth** [comment]
no, just use the build tool to remove whatever bedrock you want
