### ISSUE TITLE
[Bug]: CRASH ISSUE

### ISSUE THREAD

**Issue by NesChrome** [FTBTeam/FTB-Modpack-Issues#2068]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10049756/latest.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10049757/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10049758/debug.log)

### Describe the bug

The game crash when i try to put the item in a container

### Steps to reproduce

1 . Place a modular storage (RfToolsStorage) .
2 . Put a Remote Modular storage in the container .
3 . The game crash .

### Expected behaviour

like with the other modular storage tier

**Comment by NesChrome** [comment]
![image](https://user-images.githubusercontent.com/105519787/202913284-05770cfa-eb80-4dc6-bbf5-cb2eae40c4a5.png)
( item image )

![image](https://user-images.githubusercontent.com/105519787/202913329-417fc3e8-d314-4403-9a97-c1f9071dc5be.png)
( block image )

**Comment by NesChrome** [comment]
Get the same issue when putting normal tier
(of the same mod)

**Comment by NesChrome** [comment]
( An other problem i consulted in the modpack , when i write command my game freeze )

**Comment by NesChrome** [comment]
i think it's something else ...

**Comment by Sunekaer** [comment]
Well, after chatting to the mod author, I'm being told this item you are using (Remote Storage Module) is implemented yet.
Item also doesnt have a crafting recipe which means you cheated it in.
