### ISSUE TITLE
[Bug]: [Stoneblock 3] Chickens from Chickens mod should be prepared by campfire Encased Fan, not by lava one

### ISSUE THREAD

**Issue by LuciusV** [FTBTeam/FTB-Modpack-Issues#2069]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0

### Describe the bug

Chickens have their cooking recipe as smelting - lava fan cooks them, while it should be campfire smoking.

### Steps to reproduce

Look recipe and test encasing fan

### Expected behaviour

Expected smoking chickens, not melting

**Comment by Sunekaer** [comment]
1.3.0 is a very old version of the pack, the recipe is correct in my current instance.
