### ISSUE TITLE
[Suggestion]: Remove /back

### ISSUE THREAD

**Issue by NordicGamerFE** [FTBTeam/FTB-Modpack-Issues#2070]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

This might be controversial but i think /back dont belong in stoneblock, /back can be used to cheese all the dungeons giving you easily early on enough loot to start projecte by first making a gem of eternal density to obtain loads of (iron/gold/diamond/dark matter and red matter). not only does this boost you into projecte but also a lot of other mods. while I think dungeon loot, or the gem of eternal density could be nerfed, I think /back is not needed in a world where graves exists and where you never are really far from your base.

**Comment by Sunekaer** [comment]
Command wont be removed, but thanks for the suggestion.
