### ISSUE TITLE
[Bug]: Errors in currently selected datapacks prevented the world from loading.

### ISSUE THREAD

**Issue by YuhGnad** [FTBTeam/FTB-Modpack-Issues#2071]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10049884/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10049908/debug.log)

### Describe the bug

After finished some multiblock, I had to save the world and then I log back in, this happened. I had to try reinstall the mobpack and paste my file world in new instance, it's still happen.

### Steps to reproduce

1. Just log back in, this happened

### Expected behaviour

I can't log into my world. In my opinionIt seem like the problem comes  from level.dat or level.dat_old file

### Screenshots

![Screenshot 2022-11-20 211821](https://user-images.githubusercontent.com/117620860/202907290-351a01be-14a9-4f65-ac3f-1edf89a53930.png)

**Comment by NordicGamerFE** [comment]
Issue caused by user added mod Mahou Tsukai

**Comment by NordicGamerFE** [comment]
@YuhGnad Even if you delete a mod it can still cause issues, I am not myself familier with 1.18 issues so you will have to wait until someone from the ftb team helps you out.
