### ISSUE TITLE
[Bug]: Crystal chest doubling cpu usage

### ISSUE THREAD

**Issue by Malte5768** [FTBTeam/FTB-Modpack-Issues#2072]
### Modpack

Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

So whenever i open a crystal chest(form the iron chest mod) in my world i can see my cpu going from 20 percent to 40 percent. It does not matter if the chest if full or not, just opening it ramps up the cpu to double. This does not happen with any other chest there is from the iron chest mod.

### Steps to reproduce

Get a Crystal chest.
Open it.

### Expected behaviour

My cpu percentage not doubling

### Additional information

I do not know if this is stoneblock 3 related or if it is an iron chest mod thing... just wanted to get it out so it may be improved because it cutting down on server/world performance.

This does not happen when opening any other chests of the iron chest mod

**Comment by Malte5768** [comment]
> Is this still an issue for you on the latest version of the modpack?

Hello there, i updated the modpack and the issue is still there. Cpu usage ramps up from 20 to 30 percent continuisly while i have a crystal chest open. Does not matter if it is empty or not. This issue does still not occur with any other chests from the iron chest mod.

**Comment by UnRealDinnerbone** [comment]
Crystal Chest has always been known to cause fps and such. I would recommend just using a diamond chest instead
