### ISSUE TITLE
[Suggestion]: StoneBlock 3: Add Tool Belt mod!

### ISSUE THREAD

**Issue by hairlessOrphan** [FTBTeam/FTB-Modpack-Issues#2073]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

I find myself going to the same tools and mods over and over for one really awful reason: inventory management. I have my backpack kitted out, and I've got all the tools and toys stored in it! But I never use them, because when I'm trying to accomplish something in the moment, it's just too many clicks to quickly bring lesser-used tools in to my normal gameplay loop. So it's always the paxel, scaffold, and oak.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/tool-belt

It's a fun quality of life mod that I use in other modpacks to quickly bring in tools from a lot of the other mods. Early game, it helps manage the initial set of basic tools. Once you get to paxels, you can also manage building or mining gadgets, teleportation wands, personal shrinking devices, wrenches, etc... while also freeing up the hotbar for building blocks.

I believe Tinker's has a similar thing, but I'll never use it, because the opportunity cost for other upgrades and abilities is too high. This may have a similar issue with the Repair Talisman for the belt slot, but I never get this drop until I'm way past caring about it anyway, so this sounds like someone else's problem.

**Comment by Sunekaer** [comment]
Mod has already been suggested and declined, thanks for your suggestion

**Comment by ShadoKitten** [comment]
I've been playing Stoneblock 3 for a few days now and I find myself going back and forth between mining and dumping my inventory. Is there any way to add Ender Storage? Please and thank you.
