### ISSUE TITLE
[Suggestion]: StoneBlock 3: Let us harvest pebbles with pebbles

### ISSUE THREAD

**Issue by hairlessOrphan** [FTBTeam/FTB-Modpack-Issues#2074]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Every player ever:
1. Punch stone for pebble.
2. Pick up pebble.
3. Punch stone for pebble.
4. Get super confused that you didn't get a pebble.
5. Oh. Right. Ugh.

Everyone here knows what I'm talking about.

**Comment by Sunekaer** [comment]
Since it's been like this since SB1, I won't change this behaviour
