### ISSUE TITLE
[Bug]: StoneBlock 3: Passive Mobs and Wandering Trader not spawning

### ISSUE THREAD

**Issue by hairlessOrphan** [FTBTeam/FTB-Modpack-Issues#2075]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0

### Describe the bug

I'm not sure why, but in my current playthrough, I didn't get any passive mobs or wandering traders spawning for hours. I think there might be some internal toggle that isn't being set correctly?

This isn't going to be super helpful or easy to reproduce, so this might not be actionable, but I'll leave some notes here anyway.

1. I toggled off Loot Bees and Sticks events right after spawning into the portal hub. I did NOT toggle off Wandering Trader (I double-checked, see below).
2. I also increased my Loaded Chunks limit to 100 right away. Can't imagine this affects anything, but including just in case.
3. After spawning in, I dug up to Y=65 before building out my base and Giant Passive Mob Grass Field (in previous playthroughs, I built at Y=0, and I had no issues with passive mobs or wandering traders. Not sure if this affects spawning logic).
4. I didn't get any passive mobs for hours, despite having a 24x24, chunk-loaded, well-lit, fully-grassed field (at Y=65).
5. However, as soon as I got a Delightful Dirt drop from a dungeon, I plopped one down and got passive mobs from it (hooray)... what makes me suspect this is a bug is that after I removed the Delightful Dirt and killed off all the passive mobs, I started getting passive mobs right away as per vanilla Minecraft spawning rules, as expected.
6. ...but I still haven't seen a single Wandering Trader.
7. I don't have a No Soliciting sign up (I haven't even crafted one).
8. I also toggled the Wandering Trader event off and on (the classic troubleshooting step) to see if maybe there was a toggle to reset (similar to the Delightful Dirt experience, above). Hours later, still no Wandering Trader.

### Steps to reproduce

I have no idea if this will reproduce the issue. But here's everything I did that was different from my first game (when I got plenty of passive mobs and wandering traders):

1. Create new world
2. In the portal hub, immediately toggle off Loot Bees and Sticks (but don't touch Wandering Trader event!)
3. Immediately set `/ftbchunks admin extra_force_load_chunks` to 100
4. Step into the portal and select The Original spawn point
5. Dig up to Y=65
6. Make a 24x24 (x7 tall) grass field
7. Put torches out to light the entire field (checked this by ensuring the entire field gets covered in grass)
8. Chunk-load the entire field (2x2 chunk area)
9. Work on base ~20-60+ blocks away for hours. Observe no passive mobs ever. Observe no wandering trader ever.

### Expected behaviour

Too many wandering traders. Some number of passive mobs.

**Comment by Sunekaer** [comment]
Wandering Trader isn't using the vanilla spawn system and has a low chance of spawning, turning off other events doesn't make it have a higher chance of spawning.
There is also multiple factors to if it spawns or not.

Passive mobs spawning just fine in my test world:
![billede](https://user-images.githubusercontent.com/18720460/203308338-e3b150f3-297a-4df6-a0b8-1ee4c243106c.png)
![billede](https://user-images.githubusercontent.com/18720460/203308428-65addb52-d049-4000-8093-9ad7b357df2a.png)
![billede](https://user-images.githubusercontent.com/18720460/203308484-841fba15-cd35-4fd3-ba5f-2d3788dddb7d.png)

**Comment by Strange05** [comment]
I have the same problem in my world using version 1.3.0. I Disable the stick event and never had any passive mob spawning nor wandering trader. I tried activating the stick event to see if change something and it did, i saw some bunnys and Ars Nouveau  mob spawning inside the starter cave(lush house) but i tried moving the grass to other place and mobs didn't spawn. The stick event is doing some weird stuff, it was the only event i changed. The loot bees do spawn, but since they have some special spawning that's probably why they still spawn.

**Comment by Sunekaer** [comment]
Wandering traders is spawned the same way as loot bees.
The stick event, nor any of the events are related to natural spawns in any way
