### ISSUE TITLE
[Bug]: FTB Ultimine Doesn't Unlock

### ISSUE THREAD

**Issue by HaloGT1** [FTBTeam/FTB-Modpack-Issues#2076]
### Modpack

OceanBlock

### Modpack version

1.15.1

### Log Files

[2022-11-12-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10050723/2022-11-12-2.log.gz)
[2022-11-13-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10050724/2022-11-13-1.log.gz)
[2022-11-13-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10050725/2022-11-13-2.log.gz)
[2022-11-14-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10050726/2022-11-14-2.log.gz)
[2022-11-19-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10050727/2022-11-19-2.log.gz)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10050728/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10050729/debug.log)
[debug-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10050730/debug-1.log.gz)
[debug-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10050731/debug-2.log.gz)
[debug-3.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10050732/debug-3.log.gz)
[debug-4.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10050733/debug-4.log.gz)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10050734/latest.log)

### Describe the bug

When you begin the modpack, Ultimine is locked until specific quests are completed, which will give the trinket to unlock the use of the mod. I completed the quests, right-clicked and used the trinket, and it didn't unlock the mod.

### Steps to reproduce

1. Start the modpack
2. Complete the quests that unlock the Ultimine Trinket
3. Place the trinket in the hot bar
4. Right-click the trinket in hand

### Expected behaviour

Ultimine to be unlocked for use with the "`" key

### Screenshots

![Screenshot_20221120_023130](https://user-images.githubusercontent.com/118693033/202927294-1cb0ea31-b02d-49bb-b6a6-97e1d22f6204.png)

**Comment by mpetrole** [comment]
Did you open the trinkets UI and slot in the ultimine trinket?

**Comment by HaloGT1** [comment]
No because the menu does not open when I press 'r'. I rebound it to ']' and
it still doesn't work.

**Comment by Raidobw2** [comment]
Try binding the Lost Trinkets menu to a letter (such as 'k' or 'l') and make sure there are no keybind conflicts for that letter. Then open the Lost Trinkets menu with said key and add the Ultimine trinket to it (click on the "+"), then try to use it with the "`" key. Let me know if that works!

**Comment by DinnerBeef** [comment]
Were you able to get Ultimine to work, or are you still having issues with it?
