### ISSUE TITLE
[Suggestion]: StoneBlock 3: Ladder tweaks for QoL

### ISSUE THREAD

**Issue by hairlessOrphan** [FTBTeam/FTB-Modpack-Issues#2077]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

I wanted to try a more vertical base to take advantage of how there are no air blocks (so building up should be almost as easy as building down, unlike in normal worlds). But I found that it was too painful early game to get up and down ladders, and by the time I had vertical options (i.e. ender pearls for elevators or travel anchors), too much of my base was already built out at the same Y-level.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/climb-ladders-fast

...and...

https://www.curseforge.com/minecraft/mc-mods/scaffolding-behavior

Or any related mods. There are three changes these mods will make to ladders to make them usable early-game:
1. Easier ladder placement when you're climbing higher than 5 blocks
2. Faster ladder movement
3. Going up and down ladders by looking, without holding movement keys

The only thing I can think of that this might negatively affect is it makes it easier to get in and out of the ladder rooms in dungeons. But I don't think it would make a significant difference - even at the current climbing speed, it's never been a problem getting in and out quickly enough to avoid dying.

Note that for Climb Ladders Fast, it's helpful to disable this behavior for scaffolds in the config, so scaffolds can serve a slightly different purpose (for building). Maybe disable it for vines, too; that could be a mess in the dungeons.

**Comment by Sunekaer** [comment]
FYI, i was gonna add climbladdersfast but it breaks scaffolding so you can stand on it like normal and such

**Comment by Sunekaer** [comment]
Nevermind found a solution.
