### ISSUE TITLE
[Bug]: [Stoneblock3] minetogether  api.creeper.host instability causes game to crash

### ISSUE THREAD

**Issue by hugoprudente** [FTBTeam/FTB-Modpack-Issues#2078]
### Modpack

Stoneblock

### Modpack version

1.3.0

### Log Files

https://pste.ch/osiqorejug.sql

### Describe the bug

While playing the game crashed with the message "Close externally" 

Checking the logs I notice that was a timeout from the minetogether mod again

### Steps to reproduce

On linux.

1. Open your game
2. ensure that you receive messages from minetogether.
3. check the api.creeeper.host 
```
➜ dig +short api.creeper.host
185.57.191.115
```
4. Drop it on iptables
```
iptables -A OUTPUT -s 185.57.191.115-j DROP
```
5. Wait and the game will crash.

### Expected behaviour

Game do not crash case the API stop responding.

**Comment by vengefulgod** [comment]
I have to remove the mod and reload the pack cause it crashes before the game even has the chance to load and on top of that i try installing the mod myself still crashes so my advice is to take it out all together not even worry about it

**Comment by Sunekaer** [comment]
Closing issue as mod hasn't been updated to fix this, we will add this issue to a list of known mod issues
