### ISSUE TITLE
[Bug]: AE2 Autocrafting - Doesn't close interface

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#208]
### Modpack

Ftb University 

### Modpack version

1.3.0

### Describe the bug

When requesting a recipe the screen doesn't close, meaning you can click again to request it again.

### Steps to reproduce

1.) request a recipe
2.) click button again to request again
3.) Theres no acknowledgement of either being accepted

### Expected behaviour

Should close interface after requesting

**Comment by aaronhowser1** [comment]
Confirmed, forwarded to mod dev

**Comment by Raidobw2** [comment]
FYI subscribed to the other issue to bring this current one back into your workspace once mod is fixed.

**Comment by aaronhowser1** [comment]
Apparently it's from the Wireless Terminals addon, not the main mod

Tfarcenim/AE2WirelessTerminalLibrary/issues/27

**Comment by Raidobw2** [comment]
The PR was merged for that issue. We'll have to wait for a release on CF.
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals-forge
