### ISSUE TITLE
[Suggestion]: Add Creative Wireless Transmitter Mod to the Pack for Refined Storage Infinity wireless Range!

### ISSUE THREAD

**Issue by Timu420** [FTBTeam/FTB-Modpack-Issues#2081]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

I dont like the max 48 Blocks Range of the normal Wireless Transmitter, that is why i would like to get infinity Range and Cross Dimensional Range. THX
and no i will not switch to AE2, because i dont like the way they Store items based on Itemtype and the way the Cables work there.

sry for bad English.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/creative-wireless-transmitter

Infinity range for Refined Storage Wireless Transmitter and Cross Dimension Acess.

**Comment by Sunekaer** [comment]
Hi 
We are not looking to add any "creative items" to this pack.
Thanks for the suggestion.
