### ISSUE TITLE
[Bug]: Mega torch do not prevent silverfish minions from spawning

### ISSUE THREAD

**Issue by Fuckthissignup** [FTBTeam/FTB-Modpack-Issues#2082]
### Modpack

Stoneblock 3

### Modpack version

1.3

### Describe the bug

Following the tooltip for automating the mother does work. (ish)
But if you at any point deactivate the field to adjust something. she spawn minions and will never stop. even innside the
field of a megatorch or any other item that prevents spawning.

### Steps to reproduce

Set up a force field under the altar, give it power and place a mega torch somewhere near. Then deactivate the forcefield and she will start spawning minions.

### Expected behaviour

Mega torches blocks spawning even after she is released from stasis.

**Comment by Sunekaer** [comment]
mega torch wont stop the small sliverfishes, i have removed this info from the quest text in the next update
