### ISSUE TITLE
[Suggestion]: Add Apotheosis to FTB Stoneblock 3

### ISSUE THREAD

**Issue by ItsAzaria** [FTBTeam/FTB-Modpack-Issues#2083]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Seems like a good fit for the modpack. Hopefully not a duplicate suggestion! (I did check first)

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/apotheosis

**Comment by Sunekaer** [comment]
Hi 

Thanks for the suggestion, but i don't feel this fits the pack.
