### ISSUE TITLE
[Bug]: SB3 Dims on server not unloading. 200+ active at all times

### ISSUE THREAD

**Issue by accio-nox** [FTBTeam/FTB-Modpack-Issues#2084]
### Modpack

SB2

### Modpack version

1.3.0

### Describe the bug

Running a server with 200+ active dims that won't unload when players are offline. As you can imagine this is becoming an issue with TPS. How do we force unload these when players arent active? 

### Steps to reproduce

self explanatory

### Expected behaviour

Dims should unload by default after 24/36/72 hrs of inactivity

**Comment by perennialpersephone** [comment]
Are these dimensions being chunk loaded through FTB Chunks? I assume that'd be the reason they aren't being unloaded.

**Comment by accio-nox** [comment]
We’ve managed to find a way to disable it that it’s a but out of the way but thanks for giving me time to reply to the issue before closing it …..On 22 Nov 2022, at 10:31 am, Sunekaer ***@***.***> wrote:﻿
Some machines chunk loads themselves, there is nothing we can do about that.
If its loaded by FTB Chunks you can disable offline chunk loading

**Comment by Shybella** [comment]
https://github.com/FTBTeam/FTB-StoneBlock-Companion/issues/2
