### ISSUE TITLE
[Bug]: Loot doesnt drop from mobs spawned from soul shards spawner when killed indirectly

### ISSUE THREAD

**Issue by FLAMiNGPHYtON1** [FTBTeam/FTB-Modpack-Issues#2085]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

Special Mobs from Apotheosis spawned from Soul Shard spawner not dropping extra loot when killed by any other means beside the player (Ars Nouveau Spell turrets). I used magma cubes for my spawner. This was working as intended a few days ago in my mob spawner, but has since stopped working.

### Steps to reproduce

1. Add a soul shard of any mob to a soul shard spawner
2. Spawn mobs
3. Kill mobs indirectly

### Expected behaviour

Extra loot should be dropping when killed using turrets or damage blocks

**Comment by Saereth** [comment]
this is not a bug and is working as intended
