### ISSUE TITLE
[Bug]: Quest Rewards notifier showing wrong info

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#209]
### Modpack

Ftb University 

### Modpack version

1.3.0

### Describe the bug

When completing a quest and claiming the reward, the notification of a waiting quest reward doesn't go away. Its still visible in the top right and clicking it sometimes gives duplicate rewards.

### Steps to reproduce

Not sure as I have all the quests I can do done, but Im guessing just do a quest and claim the reward.

### Expected behaviour

Once claimed it shouldn't pop up as claimable in the top right

### Screenshots

![image](https://user-images.githubusercontent.com/44754456/139234916-f376816b-a817-4ee4-a7ae-4adf679997a1.png)

**Comment by aaronhowser1** [comment]
Very late, but you probably have a reward in an invisible chapter somewhere. Going into editing mode will show where. I'll forward to FTB Quests dev to not show that when the reward isn't visible.

**Comment by aaronhowser1** [comment]
Actually wait no, that can't be right. If you still have this, can you enter editing mode and find the reward?
