### ISSUE TITLE
[Suggestion]: Craftable Infinity Upgrade

### ISSUE THREAD

**Issue by Pienapples** [FTBTeam/FTB-Modpack-Issues#2091]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Since most people generally are making a Max Size reactor from Mekanism to be able to produce a lot of Polonium for singularities in a short amount of time, the problem arises from not being able to input enough water into a Reactor without creating a turbine touching it. 

I suggest adding some sort of expensive Avaritia Extreme Craft for the Infinity Upgrades for the Pipez mod, something that we can obtain in the late-game with a bit of grinding but something that at least requires you to get to the end-game to achieve it.

Maybe something along the lines of using Silverfish Hearts, Neutronium, and maybe even Infinity Catalysts, just to be able to play off some of the end-game quests.

**Comment by Sunekaer** [comment]
We are not looking to add items like creative items to this pack, singularities will be tweaked in next update
