### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cc2k** [FTBTeam/FTB-Modpack-Issues#2092]
### Modpack

Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

I was not able to get the orange field from the projecters(compact machines mod) in 1 place, but  i did get it in the same way on a diffrent location.
i believe this might have been due to the light added from the mining gadget.

### Steps to reproduce

made the projector field with a inside cube of 11 x 11 on a location where i dug out with the mining gadget(with the option to add light)

### Expected behaviour

Working projector field

**Comment by Sunekaer** [comment]
Nothing i can do about this, youll just have to break the light there was placed

**Comment by cc2k** [comment]
thats the thing breaking the lights made this error(not sure if it also happends if its not broken)
