### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LordyGames** [FTBTeam/FTB-Modpack-Issues#2094]
### Modpack

Stoneblock3

### Modpack version

1.3.0

### Log Files

I'm not able to do the brine

### Describe the bug

Estou tentando fazer a bateria do mekanisme porem não estou conseguindo fazer o brinde 

### Steps to reproduce

Construo o thermal evaporation porém não funciona 

### Expected behaviour

Esperava conseguir fazer o brine que e um item para crafiting a bateria do mekanisme

**Comment by Sunekaer** [comment]
Please convert your report to English.

**Comment by NordicGamerFE** [comment]
Related to #2035
