### ISSUE TITLE
[Bug]: Factory Hopper Void Bug

### ISSUE THREAD

**Issue by lurch9229** [FTBTeam/FTB-Modpack-Issues#2097]
### Modpack

FTB Stoneblock 3

### Modpack version

1.2.1

### Describe the bug

Engineer's Decor Factory Hoppers void items when broken

### Steps to reproduce

1. Place factory hopper
2. Place item in hopper
3. Break hopper

### Expected behaviour

Items spill into world like breaking a regular inventory tile

**Comment by Sunekaer** [comment]
https://github.com/stfwi/engineers-decor/issues/226

**Comment by Sunekaer** [comment]
Should be solved
