### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LordyGames** [FTBTeam/FTB-Modpack-Issues#2098]
### Modpack

Stoneblock3

### Modpack version

1.3.0

### Describe the bug

I'm not able to make brine to create the mekanisme battery

### Steps to reproduce

I build the thermal evaporation plant mechanism to turn water into brine but I can't make it work

### Expected behaviour

I was hoping to make the toast which is an item for crafting the mekanisme battery

**Comment by louis2607** [comment]
You need a Resistive Heater in between both evaporation chambers connected to Thermal Evaporation Valves

**Comment by Sunekaer** [comment]
Duplicate of #2035
