### ISSUE TITLE
[Bug]: Creative Upgrade (Tinkers) counts as a creative ability (Tinkers), same with normal and creative mana tablet

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#210]
### Modpack

Ftb University 

### Modpack version

1.3.0

### Describe the bug

I made the creative upgrade and both quests got ticked off, this happened with mana tablet and creative mana tablet too.

### Steps to reproduce

1.) make a creative upgrade / mana tablet
2.) get 2 quests for the price of 1

### Expected behaviour

Not to tick off the 2nd quest

**Comment by aaronhowser1** [comment]
Fixed, they're the same item with different NBT. Set the quests to require NBT as well.
