### ISSUE TITLE
[Bug]: small lagspike during join server causes disconnect (sb3)

### ISSUE THREAD

**Issue by walksanatora** [FTBTeam/FTB-Modpack-Issues#2100]
### Modpack

StoneBlock 3

### Modpack version

1.3.0

### Describe the bug

When joining a peer on LAN or a server there is a small lag spike right after the game says `Encrypting` while joining
This usually freezes the client and causes a disconnected or timed out

### Steps to reproduce

1. Join a server
2. Cpu spikes from ~20% to 90% and stops responding
3. Unable to connect

### Expected behaviour

Able to join servers without a NotResponding issue

### Additional information

I have 7 GB ram allocated
The server is responding to pings within 50-100ms

**Comment by Raidobw2** [comment]
I see, @walksanatora could you try adding the Connectivity mod or the Longer Login Times mod to your client?

You can try one or the other at a time, but I wouldn't try both at the same time:
https://www.curseforge.com/minecraft/mc-mods/connectivity/files/3833738
https://www.curseforge.com/minecraft/mc-mods/longer-login-times/files/3601460

You simply add the mod to your mods folder, load the game and try to connect to the server.
I'm not sure if this is required server side exactly to work, it might not.

In the case it doesn't look to be working, try adding it to the server/LAN host if you can as well (either, but not both. Add the same you added to your client).

Also, how much RAM does your total computer have? 8GB, 16GB, 32GB, etc?
How much RAM is free when you are connecting to the server? (Task Manager > Performance tab > % usage)
Thanks
