### ISSUE TITLE
[Bug]: [SB3] Industrial Foregoing Item Transporter cannot extract items from Roosts

### ISSUE THREAD

**Issue by remco082000** [FTBTeam/FTB-Modpack-Issues#2103]
### Modpack

Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

When attempting to extract items from a Roost or Chicken Breeder using Industrial Foregoings' Item Transporter, no items are being extracted. Attempting to extract from the bottom of the Roost does not work either. 

Inserting items into these blocks using the Item Transporter does work. 

### Steps to reproduce

1. Place a Roost and put chickens inside; 
2. Place a chest one block away; 
3. Place the Item Transporters; 
4. Set the Item Transporter on the chest to be receiving items; 
5. No items will be extracted from the Roost. 

### Expected behaviour

Item Transporters should be able to extract items from a Roost.

### Screenshots

https://user-images.githubusercontent.com/22686088/203577057-bb387e30-6233-4e3b-9315-a7043072b332.mp4

**Comment by MisterSoandSo** [comment]
I know for a fact that laserio works properly

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
