### ISSUE TITLE
[Bug]: Crashing when trying to craft certain items in transmutation table

### ISSUE THREAD

**Issue by Megatonberry** [FTBTeam/FTB-Modpack-Issues#2105]
### Modpack

Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

The game lags then crashes to desktop when trying to craft certain items from the transmutation table, happens with personal EMC link and refined EMC link.

### Steps to reproduce

Go to transmutation table
Try to craft personal EMC link

### Expected behaviour

FPS lags for a few seconds then crashes to desktop

**Comment by Sunekaer** [comment]
Duplicate issue

**Comment by Morgen-stern** [comment]
Same thing happens to me as well. Whenever i open the transmutation table, game freezes and i have to alt f4. Still no answer how i could solve it
