### ISSUE TITLE
[Bug]: Update Chisel and bits mod, because critical server breaking bug.

### ISSUE THREAD

**Issue by ThirtyTwelveNor** [FTBTeam/FTB-Modpack-Issues#2106]
### Modpack

Stoneblock 3

### Modpack version

1.3.0

### Log Files

[crash-2022-11-23_22.09.53-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10079588/crash-2022-11-23_22.09.53-server.txt)

### Describe the bug

On loading a ae2 network that is trying to import magnifying glass(chisel&bits)(hereby defined as item name)
will result in ae2 trying to access client-side only code when it Querys item name
resulting in an instant server crash
by instant, it goes so fast neither worldedit or crashutilites have the chance to remove it before crash...
also resulting in soft-locking(they released a patch) someones bases. 

### Steps to reproduce

1. make ae2 network with storage
2. spawn in magnifying glass or get it from loot
3. connect a import bus with chest to ae2 network
4. put magnifying glass in chest
5. =unrecoverable base untill update

### Expected behaviour

magnifying glass gets imported without problems

**Comment by NordicGamerFE** [comment]
They are already aware of this, You can probably expect this to be fixed in the next update as chisel and bits has released a update fixing this.

**Comment by Sunekaer** [comment]
Updated in 1.4.0

**Comment by NordicGamerFE** [comment]
> Updated in 1.4.0

Nice to see it was updated, But it was not put in the changelog.

**Comment by ThirtyTwelveNor** [comment]
[crash-2022-11-25_18.22.57-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10094469/crash-2022-11-25_18.22.57-server.txt)
is this a coincidence, the same guy that had the magnifying glass. now get a new crash on base load. after modpack update...

**Comment by NordicGamerFE** [comment]
this is not related open a new issue.
