### ISSUE TITLE
NEI not Working even after insalling VanillaNeiFix

### ISSUE THREAD

**Issue by iCubeex** [FTBTeam/FTB-Modpack-Issues#2107]
### Modpack

FTB Lite

### Modpack version

1.2.3

### Describe the bug

FTB Lite installed. 
NEI not Working
Installed the fix Mod 
Still not Working

### Steps to reproduce

Install FTB 
Open FTB Lite 
Join World 
Open inventory 

See Nothing

### Expected behaviour

Help me to fix my Problem

**Comment by manmaed** [comment]
This is an Old Version which is no longer supported

**Comment by Raidobw2** [comment]
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/553
