### ISSUE TITLE
[Bug]: Ender dust seldom falls on belt under crushing wheel

### ISSUE THREAD

**Issue by Roland-swe** [FTBTeam/FTB-Modpack-Issues#2108]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

When crushing ender pearls whith Create crushing wheel the eneder dust does not fall on the Create belt below, but to the side of it. Out of about ten stacks of ender dust forty peices ended up on the belt. I have not encountered this with any other material yet.

### Steps to reproduce

1. Set up a Create crushing wheel with a belt underneath
2. Put some ender peqarls in the crushing wheel
3. Look when the ender dust does not hit the belt, but is thrown to the side (not all of it though.

### Expected behaviour

I eaxpected the enderdust to fall vertically to the belt below the crushing wheel

**Comment by Raidobw2** [comment]
Does your setup work properly if you put a "chute" (search REI, it's a block) from Create below the crushing wheels? Or with a hopper, same result?

Also, could you add a picture showing where the Ender Dust ends up falling, and where the crushing wheels are? That would be very helpful to us in the case we need to make a report to the mod author! Thanks

**Comment by Roland-swe** [comment]
Hi. Thanx for the response.

Apparently I had destroyed my setup in my regular world, but I made a new one and could replicate the results there.

As seen in the first four pics, when cruching ender pearls to dust and letting them fall onto the belt directly; 16 ended up in the chest and 96 on the ground (as seen in my inventory). It seems they all fell on the ground up to three blocks away on the north side of the cruching wheels when the setup is in a east-west direction (if that matters).

![2022-12-03_14 33 32](https://user-images.githubusercontent.com/413335/205443741-708e319f-82dc-4504-a366-98968378be8e.png)
![2022-12-03_14 33 40](https://user-images.githubusercontent.com/413335/205443751-09c40732-6a2c-4f45-8f21-91b5fb7a6259.png)
![2022-12-03_14 34 06](https://user-images.githubusercontent.com/413335/205443755-eeecf168-2a83-4ee0-88d5-a082afd848dc.png)
![2022-12-03_14 34 49](https://user-images.githubusercontent.com/413335/205443760-cf518cdf-5e43-4cae-a6c1-6c25618b8f7a.png)

When putting a chute below the cruching wheels ALL the dust ended up in the chest of a few stacks processed:


![2022-12-03_14 36 29](https://user-images.githubusercontent.com/413335/205444075-b3be0a5c-6d78-42dc-ad3d-dcb6d814aa50.png)

When using a hopper all the dust goes into the hopper, but the hopper does not let any out on the belt. Maybe that is how it is supposed to work?

![2022-12-03_14 37 08](https://user-images.githubusercontent.com/413335/205444155-f91568e9-8cfe-4254-b090-7768a29672b8.png)

So basicly; using a chute solved the problem.

If you need anything else don't hesitate to ask.

Best regards
Herringpants

**Comment by Sunekaer** [comment]
chute is the solution, nothing we can do here sorry
