### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by itsjusttriz** [FTBTeam/FTB-Modpack-Issues#2110]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Log Files

https://srcb.in/19agwDA80S

### Describe the bug

Architectury has caused 2 server crashes now. Idk what its doing, to be able to "Describe it" but yea...

### Steps to reproduce

Read log.

### Expected behaviour

Not to crash server

### Additional information

Doesnt happen immediately. Happens overtime.

**Comment by Sunekaer** [comment]
Architectury, but FTB Backups crash, duplicate issue, will be fixed in next update

**Comment by itsjusttriz** [comment]
I thought it was Architectury as my server host kept flagging the mod, each time the server went down.
