### ISSUE TITLE
[Bug]: REI move items is broken for AE2

### ISSUE THREAD

**Issue by cooljacob204** [FTBTeam/FTB-Modpack-Issues#2113]
### Modpack

Stoneblock 3

### Modpack version

1.4.0

### Describe the bug

REI move items is broken for AE2. Get the warning "Move Items is not supported with this recipe and this container"

### Steps to reproduce

1. Open an ae2 crafting or pattern terminal
2. Open an item in REI
3. Try to move items to crafting grid

### Expected behaviour

Items should move to the grid

### Screenshots

![image](https://user-images.githubusercontent.com/1229589/203854524-cfd64f4a-2bcd-45cd-bcfc-b40d8b2075ff.png)

**Comment by PerretB** [comment]
Same problem with refined storage, problem appeared with the update to 1.4.0

**Comment by Sunekaer** [comment]
Can you please test if this fixed in 1.4.1

**Comment by brokenscrub** [comment]
> Can you please test if this fixed in 1.4.1

It is working for me after update 1.4.1

**Comment by NordicGamerFE** [comment]
Can also confirm working in 1.4.1
