### ISSUE TITLE
[Bug]: Industrial Foregoing removed from REI

### ISSUE THREAD

**Issue by PdSiK** [FTBTeam/FTB-Modpack-Issues#2114]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.0

### Describe the bug

Two issues,
1. while using Industrial Foregoing, hovering over items will show their "item info" far away from the item itself (Better shown on screenshot attached)
2. There aren't any recipes for Machine Frames, or items created using Industrial Foregoing

### Steps to reproduce

Issue 1:
1. Open a block with interface from "Industrial Foregoing"
2. Hover over any item

Issue 2:
1. Find an item that has industrial foregoing as a recipe (For example Supreme Machine Frame),
2. Try to check its recipe using REI

### Expected behaviour

Issue 1: Item info will display next to item,
Issue 2: Showing the recipes of items

### Screenshots
Issue 1:
![image](https://user-images.githubusercontent.com/91431682/203856381-cebbf1ae-5f8a-4ce0-b17c-1018a5567358.png)

Issue 2:
![javaw_MMOQGQy25K](https://user-images.githubusercontent.com/91431682/203856500-5f1bc3f8-7383-422e-abe7-8cb3c2f31113.gif)

**Comment by Sunekaer** [comment]
Can you please test if this fixed in 1.4.1

**Comment by NordicGamerFE** [comment]
Tested and can confirm working in 1.4.1
