### ISSUE TITLE
[Bug]: Stoneblock 3 crash when looking up recipe via quest book

### ISSUE THREAD

**Issue by ziron999o365** [FTBTeam/FTB-Modpack-Issues#2115]
### Modpack

Stoneblock 3

### Modpack version

1.4.0

### Log Files

https://justpaste.it/ak9ku

### Describe the bug

It is just a simple crash upon looking up any recipes via the quest book.

### Steps to reproduce

Version 1.4.0
Started a new game, click on recipe via quest book tasks only.

### Expected behaviour

Should be able to see recipes via quest book tasks

**Comment by georgebutler** [comment]
Same thing happening to my client since the latest update.

**Comment by GalaxyOfZero** [comment]
Same thing happening to my client since the latest update.

**Comment by Sunekaer** [comment]
Can you please test if this fixed in 1.4.1

**Comment by NordicGamerFE** [comment]
Tested and can confirm working in 1.4.1

**Comment by NordicGamerFE** [comment]
@Sunekaer i am going to update my server, was the only change REIPluginCompatibilities?

**Comment by Sunekaer** [comment]
yes
