### ISSUE TITLE
[Bug]: Crashing whenever u want to see any recipe through the question

### ISSUE THREAD

**Issue by Joao-Pedro-Bautista** [FTBTeam/FTB-Modpack-Issues#2117]
### Modpack

stoneblock 3

### Modpack version

1.4.0

### Log Files

https://dontpad.com/crashissue

### Describe the bug

Whenever a question requires you to see any crafting recipe, the game crashes

### Steps to reproduce

Just click on the item the quest tells you to do

### Expected behaviour

The recite pops up on REI

**Comment by theodorSchei** [comment]
I have the same problem :) Clicking a an item to show the recipe from the quest book crashes the game

**Comment by NordicGamerFE** [comment]
@Joao-Pedro-Bautista try to update.
@theodorSchei crashlog? or latest.log?

**Comment by Joao-Pedro-Bautista** [comment]
@NordicGamerFE people are saying 1.4.1 is still crashing

**Comment by Joao-Pedro-Bautista** [comment]
@NordicGamerFE people are saying the game is still crashing

**Comment by Sunekaer** [comment]
Are you in SP or MP?

**Comment by Joao-Pedro-Bautista** [comment]
SP

**Comment by Raidobw2** [comment]
Should be fixed now in 1.5.0+
