### ISSUE TITLE
[Bug]: Cannot change ftbstoneblock textures with resource pack

### ISSUE THREAD

**Issue by leo-pe** [FTBTeam/FTB-Modpack-Issues#2118]
### Modpack

FTB Stoneblock

### Modpack version

1.4.0

### Describe the bug

I wanted to add the textures from the Crafting Table and Compressed blocks in FTB Stoneblock to the Sphax patch. Unfortunately the textures can only be changed in the kubejs/assets/ folder and the textures in the resources package are ignored.

### Steps to reproduce

1. Create a Texture Pack with assets/ftbstoneblock/textures/item/1x_compressed_stone.png
2. Start the game and see that the textures not changing
3. move the crafting_table.png to [instance folder]/kubejs/assets/ftbstoneblock
4. Start the game accept the Warning in FTB App and textures are changed

### Expected behaviour

Assets of kubejs changeable with a resource pack

**Comment by Sunekaer** [comment]
Thats because the textures for ftbstoneblock is already loaded via a texture pack and not a mod

**Comment by leo-pe** [comment]
> Thats because the textures for ftbstoneblock is already loaded via a texture pack and not a mod

Are you sure? I had my texture pack at the top in Resource Pack Folder and there are no other Resource Packs where the original texture can came from.

**Comment by Sunekaer** [comment]
This texture pack is always loaded last
