### ISSUE TITLE
[Bug]: Not receiving blocks back when using the Exchanging Gadget on Ethereal Glass

### ISSUE THREAD

**Issue by justinsSoJaded** [FTBTeam/FTB-Modpack-Issues#212]
### Modpack

FTB Academy 1.16

### Modpack version

1.2.0

### Describe the bug

When using the _Exchanging Gadget_ from **Building Gadgets**, user is not receiving blocks back when attempting to exchange **Glassential's** _Ethereal Glass_ for any other block. Bug discovered when attempting to exchange _Ethereal Glass_ for _Luminous Glass_.

### Steps to reproduce

1. Place _Ethereal Glass_.
2. Attempt to use the _Exchanging Gadget_ to swap any other block with the _Ethereal Glass_.
3. Note that you will not receive the _Ethereal Glass_ back.

### Expected behaviour

When using the Exchanging Gadget, the expected behavior would be to receive the block the user is swapping out back into their inventory.

**Comment by Raidobw2** [comment]
Whoops, looks like that issue fell in the dark for a bit. I've corrected that now, thanks for the report.

**Comment by aaronhowser1** [comment]
Ethereal Glass doesn't drop itself when mined, so I assume it's intended.
