### ISSUE TITLE
[Bug]: Mass item duplication involving Functional Storage

### ISSUE THREAD

**Issue by andrewtea** [FTBTeam/FTB-Modpack-Issues#2121]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

We are using pipes from Pretty Pipes to collect chicken drops from a bunch of Roosts and funneling the drops into a Storage Controller block from Functional Storage. Sometimes, the system gets clogged somehow and we break the controller to reset the flow of items. This works, but then fills all available storage drawers to the max with one type of item. It's resulted in multiple drawers filled with billions of emeralds, which became very annoying very quickly.

### Steps to reproduce

1. Get a Roost with a chicken in it.
2. Connect a pipe from Pretty Pipes to the bottom with a High Extraction Module extracting from the block above (the Roost).
3. Connect the pipe to a Storage Controller from Functional Storage.
4. Link the Storage Controller to as many Functional Storage drawers as needed.
5. Wait for the system to get clogged (Not sure exactly why this happens, just happens on occasion, don't know how to reproduce this).
6. Upon clogging, break the Storage Controller, replace it, and relink it to the drawers.
7. Any empty drawer slots will be filled to maximum capacity with the drop from whatever chicken is in the Roost (For us, it was emeralds specifically even though we had many different chickens all funneling into the Storage Controller. Not sure how it is decided what item gets duplicated).

### Expected behaviour

All empty drawers slots from drawers linked to the Storage Controller will get filled to maximum capacity with one type of item.

### Screenshots

Multiple drawers filled to the brim with emeralds.
![image](https://user-images.githubusercontent.com/57932797/203869384-c3829325-de69-4204-99cc-ac8d0b135dcb.png)
The chicken setup (the empty roost contained the emerald chicken, which we removed in fear of it happening again)
![unknown](https://user-images.githubusercontent.com/57932797/203869400-a13badd9-dec8-427e-9fba-11f23cac78d7.png)

**Comment by Gaz492** [comment]
Can you confirm if this is still an issue for you in the latest version of the pack?
