### ISSUE TITLE
[Bug]: Crashes when entering world

### ISSUE THREAD

**Issue by pybe** [FTBTeam/FTB-Modpack-Issues#2122]
### Modpack

FTB Stone Block 3

### Modpack version

1.4.1

### Log Files

[crash-2022-11-24_22.13.37-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10087561/crash-2022-11-24_22.13.37-client.txt)
[crash-2022-11-24_22.21.19-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10087562/crash-2022-11-24_22.21.19-client.txt)

### Describe the bug

Launched the pack and got into the world, it lagged and then crashed. Closed and reopened launcher and it asked to update to 1.4.1 which I did and tried again, with the same result.

### Steps to reproduce

Launch pack
Load world
crash

### Expected behaviour

World to load and be playable

**Comment by Raidobw2** [comment]
There will be the upcoming 1.6.0 version of Stoneblock 3 next week, try with this one! I'm including many crash fixes in that update.
I also believe this current issue might have been fixed in between 1.4.1 and 1.5.0
