### ISSUE TITLE
[Suggestion]: Add more use for spawn eggs

### ISSUE THREAD

**Issue by LCoolJT** [FTBTeam/FTB-Modpack-Issues#2124]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

No Problem
But something todo with the spawn eggs you get from the mod Mob Grinding Utils.
Maybe a singularity?

**Comment by Sunekaer** [comment]
We wont be adding more singularities, but if you have other ideas, we are open to hear them
