### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by soultstice** [FTBTeam/FTB-Modpack-Issues#2125]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.1

### Describe the bug

When wearig the Engineer Goggles and looking at a working block(Crushing Wheel, Mechanical Crafter, Deployer), opening an inventory keeps the Goggles' display up, blocking part of the inventory.

### Steps to reproduce

1. Equip Engineer's Goggles from Create
2. Look at a working block from Create that shows the Kinetic Stress Impact
3. Open an inventory (Player Inventory, Wirless Grid, Backpack)
4. Observe.

### Expected behaviour

When I open an inventory while looking at any block, my inventory should be as clear as any other time.

### Screenshots

![Screenshot (24)](https://user-images.githubusercontent.com/95586692/203879959-ff225a0b-61fc-4679-aca8-0466f2cc7254.png)
![Screenshot (23)](https://user-images.githubusercontent.com/95586692/203879961-06b23592-10ba-48ea-b5f7-50708aaf259d.png)
![Screenshot (22)](https://user-images.githubusercontent.com/95586692/203879963-9d211e7d-bbf1-4a48-a0c2-67d7a9a51b48.png)

### Additional information

I don't recall this happening before this update(1.4.1), though I may have just never managed to be looking at one of these blocks while opening an inventory.

**Comment by Darlat** [comment]
This also happens with the temporal pouch
 tooltip.

Also, the tooltips for the refined storage side buttons are offset for some reason.

![shifted tooltips](https://user-images.githubusercontent.com/15280788/204033238-5f1f92a7-ae2b-43d3-8aad-9e8756467917.png)
