### ISSUE TITLE
[Bug]: Pressing E crashed the game

### ISSUE THREAD

**Issue by Cloudhunter** [FTBTeam/FTB-Modpack-Issues#2126]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.1

### Log Files

https://pste.ch/etecopeqov.md

### Describe the bug

Upon opening inventory I crashed to desktop

### Steps to reproduce

1. Press E

### Expected behaviour

The game not to crash

### Additional information

I was connected to a remote server.

Could be related to https://github.com/Towdium/JustEnoughCalculation/issues/125 - error message looks similar, but didn't cause a crash

**Comment by omegaparticl** [comment]
Same thing here
https://pste.ch/usikasehoj.md
