### ISSUE TITLE
[Suggestion]: FTB Oceanblock: Menril planks recipe for Mekanism

### ISSUE THREAD

**Issue by LuciusV** [FTBTeam/FTB-Modpack-Issues#213]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

Hello!
There is Thermal expansion Sawmill recipe 1 Menril log =>  1 Stripped Menril Log => 6 Menril planks + 25% chance sawdust
Can you  please consider adding similar Mekanism recipe for Precision Sawmill? Like another Mekanism recipes 1 Log => 6 planks + 25% chance sawdust

**Comment by Raidobw2** [comment]
Linked to #226. 226 asks for all logs, this, 213, asks for menril only. Up to you Sunekaer, ping me if you want me to judge and close semi-dupes like that in the future.

**Comment by Sunekaer** [comment]
Yeah just close it as it will be fixed by 226
