### ISSUE TITLE
[Bug]: FTB backups 1.0.16 Crash bug fix

### ISSUE THREAD

**Issue by CaptainSilver** [FTBTeam/FTB-Modpack-Issues#2130]
### Modpack

Direwolf20 1.18

### Modpack version

1.10.2

### Log Files

Didn't save while troubleshooting
sorry
Only line I have save is from my google search
Job DEFAULT.ftbbackups2 threw an unhandled Exception: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 512

### Describe the bug

Received the same unhandled exception as this bug report multiple times https://github.com/CreeperHost/FTB-Backups-2/issues/38

Fix was to update FTB backups 2 to version 1.0.17 worked on my instance.

### Steps to reproduce

Have large world
wait for backup
kinda crash except the backup wants to finish even though that's what crashed resulting in watchdog never crashing the server.

### Expected behaviour

Backup as usual

### Additional information

FTB backups 2 Page
https://www.curseforge.com/minecraft/mc-mods/ftb-backups-2
Direwolf20 1.18 pack
https://www.feed-the-beast.com/modpacks/95-ftb-presents-direwolf20-118

**Comment by macks2008** [comment]
Thanks for posting this, I'm also having this issue (server crashes —kind of— at backup time with an unhandled ArrayOutOfBoundsException) and your solution seems promising. I'll try it next time I restart my server (which could be the next time it crashes at this rate).

**Comment by JasonBow42** [comment]
From issue https://github.com/CreeperHost/FTB-Backups-2/issues/38 this has been fixed in FTBBackup v1.0.17. After updating, I haven't experienced this crash in the past 16 hours.
