### ISSUE TITLE
[Bug]: Fluid values for chiller are incorrect, it should be 90 mb -> 1 ingot, not 144 mb -> 1 ingot

### ISSUE THREAD

**Issue by Renari** [FTBTeam/FTB-Modpack-Issues#2131]
### Modpack

Stoneblock 3

### Modpack version

1.4.0

### Describe the bug

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2042

This appears to have been broken with this update, 1000mB of fluid is not equal to one ingot, according to Tinkers it's 90mB to one ingot.

### Steps to reproduce

1. Melt ingots into fluid using smeltery
2. Pump molten metal to chiller ingot back.
3. Get back less ingots than put in.

### Expected behavior

Get back the same number of ingots as those that were melted.

### Screenshots

![image](https://user-images.githubusercontent.com/1839179/203896676-4dba2f5f-56cd-4d8a-93a5-34b1b5e41ec4.png)
![image](https://user-images.githubusercontent.com/1839179/203896697-a99c883a-792a-46d1-9950-312b493d5f26.png)

**Comment by Renari** [comment]
Looking at the config, it appears these are being set to 144, not 1000, I have no clue where the 1000 is coming from in REI. Either way 144 is also incorrect since Tinkers uses 90 now.

**Comment by Sunekaer** [comment]
144 is the default value thermal uses, which is why i use that.
Why its showing wrong in REI, is a different issue we have to look at

**Comment by Sunekaer** [comment]
Ill change it to 90 to match, the REI issue, will have to wait a little
