### ISSUE TITLE
[Bug]: Hostile mobs no longer spawning

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#2136]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.1

### Log Files

[latest.log](https://pste.ch/ahobasekos.md)
[debug.log](https://pste.ch/havipiqipa.md)

### Describe the bug

Hostile mobs are no longer spawning since upgrading from 1.3.0, including from spawners.

At least two others on Discord are seeing the same.

This is all on a server, single-player not tested. So far I've only checked in the main inner stone ring.

Can't see anything in the logs but attached nonetheless.

### Steps to reproduce

1. Go to a dungeon and sit next to a spawner
2. Wait a while and be surprised at the lack of death

### Expected behaviour

Hostile mobs spawn

### Screenshots

Spawner:

![Non-working spawner screenshot](https://gcdnb.pbrd.co/images/MIoigLc7ieZV.png?o=1)

Crude mob farm:

![Crude mob farm screenshot](https://gcdnb.pbrd.co/images/VjofDpDKyxUK.png?o=1)

**Comment by Soulja975** [comment]
A friend and I are having the exact same issue. We can't get Withers to spawn at all for some reason

**Comment by NordicGamerFE** [comment]
Same issue here also

**Comment by FluffyKyuki** [comment]
Same here. Me and my friend were playing LAN on a singleplayer world and it worked fine before, and when i updated and opened the world in 1.4.1 no hostile mobs spawned in our darkroom and the spawners didnt work either.
