### ISSUE TITLE
[Bug]: Stack of chickens disappear from furnace (the stack transforms into another odd item)

### ISSUE THREAD

**Issue by AshenPheonix** [FTBTeam/FTB-Modpack-Issues#2137]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.1

### Describe the bug

Has been happening since 1.0 at least.

When a stack of chickens with more than 1 chicken from the chickens mod enters an Iron Furnace furnace with the "factory" upgrade and auto split on, any "split" chickens will become an "any chicken" and the item model will disappear. The "Item" can be removed.

### Steps to reproduce

1. Get an iron furnace (or greater)
2. Insert a Factory Upgrade
3. Power said furnace.
4. Get more than 1 chicken from the "chickens" mod
5. Shift click the chicken into the furnace (more chickens will make it easier to see/spot)
6. (optional) remove the now invisible "any chicken"

### Expected behaviour

Chicken doesn't spontaneously morph into a tag

### Additional information

The chicken does properly turn into a cooked chicken, however it's unclear if this has any other detrimental effects.

**Comment by Sunekaer** [comment]
Seems to be fixed in newer versions of the pack or mod as it works in my dev instance :)
