### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ShadowBeastSW** [FTBTeam/FTB-Modpack-Issues#2139]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.1

### Describe the bug

Every machine that uses stress unit from create the tooltip overlay  covers my inventory when i open it while looking at the machine with engineers goggles on me.e

### Steps to reproduce

Put on the engineers goggles.Put down a waterwheel make it spin. Attach a for ex...: Mechanical press to the wheel.Look at the press.Open your inventory.U will see that u wont see a part of the inventory and the REI cause the kinetic stats covers it

### Expected behaviour

I suppose to see the inventory

### Screenshots

![Képernyőkép_20221125_152126](https://user-images.githubusercontent.com/118735071/204004860-5797eb32-b2bf-4d6c-a882-cb09f083c5da.png)
![Képernyőkép_20221125_152140](https://user-images.githubusercontent.com/118735071/204004873-26f9019e-8190-4c53-ae5e-d7f06fc26058.png)

### Additional information

I should see my inventory in its entirety

**Comment by 5ully** [comment]
Im gonne guess this might be a duplication of #2138, since the issue looks to be fairly similar. Might be interesting to keep the info from both until we can confirm that it is the same issue.

**Comment by Sunekaer** [comment]
duplication of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2138
