### ISSUE TITLE
[Bug]: Ars Nuovo Explosion Spell Drops Pebbles Instead of Cobblestone

### ISSUE THREAD

**Issue by BenLarge1** [FTBTeam/FTB-Modpack-Issues#2140]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.1

### Describe the bug

Ars Nuovo explosion spells do not drop cobblestone, but instead drop pebbles. I believe this is unintentional because TNT drops cobblestone and the explosion spell is meant to replicate TNT

### Steps to reproduce

1. Make an Ars Nuovo spell that uses the Explosion Glyph 
2. Use the spell on stone

### Expected behaviour

Spell should drop cobblestone

**Comment by Sunekaer** [comment]
Fixed in newer version of the pack
