### ISSUE TITLE
[Bug]: Instantly Crashed, now crashing instantly when I join the server

### ISSUE THREAD

**Issue by G59SUICIDE** [FTBTeam/FTB-Modpack-Issues#2141]
### Modpack

Stone Block 3

### Modpack version

1.3.0

### Describe the bug

I went from my base to the lobby/spawn area. I then tried to go back to my base, instead of going through the nether portal I tried to use the command /home home. Doing this instantly crashed my game and now every time I try to log into the server my game instantly crashes.

### Steps to reproduce

1. Go to spawn/lobby area
2. Don't go through nether portal
3. use /home command to travel to location outside of spawn

### Expected behaviour

Your game will crash

**Comment by NordicGamerFE** [comment]
upload latest.log

**Comment by G59SUICIDE** [comment]
> upload latest.log

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10094897/latest.log)

**Comment by Raidobw2** [comment]
Have you tried reinstalling the game and did it fix it? Note that you might want to keep those files/folders before reinstalling:
- `options.txt` => keybinds
- `local` => minimap data
- `saves` => if you have any singleplayer worlds

Also, is it the same result (a crash) with `/ftbstoneblock home`?

**Comment by AMRRIDER** [comment]
now i have the same prob i cant even join the server that i love playing on

**Comment by Raidobw2** [comment]
AMRRIDER there's an upcoming fix in the current in-dev version of Stoneblock 3, 1.6.0. That should fix a lot of crashes, including one when joining worlds like you are describing.

I will assume this issue fixed, since I've not received more information
