### ISSUE TITLE
[Bug]: Chance cubes mod allows you to spawn rewards with no op

### ISSUE THREAD

**Issue by Nyaannn** [FTBTeam/FTB-Modpack-Issues#2146]
### Modpack

FTB Stoneblock 3

### Modpack version

Latest

### Describe the bug

alows spawning chance cubes rewards 

### Steps to reproduce

1.open game
2.open chat 
3. /chancecubes spawnReward <rewardid> <username>
4. pick what you want from the id list https://theturkey.dev/chancecubes/rewardstatus (i did enchant)
5. run
6. enjoy

### Expected behaviour

it to require operator status

### Screenshots

https://www.youtube.com/watch?v=rFGQTbetnoA&ab_channel=Nyaann

**Comment by NordicGamerFE** [comment]
Works on a new server without op also

**Comment by Sunekaer** [comment]
https://github.com/TheTurkeyDev/ChanceCubes/issues/277

**Comment by manmaed** [comment]
https://www.curseforge.com/minecraft/mc-mods/chance-cubes/files/4122830

**Comment by Sunekaer** [comment]
Solved
