### ISSUE TITLE
[Bug]: Some vanilla mob spawners no longer working

### ISSUE THREAD

**Issue by hairlessOrphan** [FTBTeam/FTB-Modpack-Issues#2147]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.1

### Describe the bug

Skeleton, Cave Spider, and Zombie spawners aren't spawning mobs anymore, regardless of light level.

Bits spawner will still spawn mobs, but now can be stopped with a torch (in previous versions, light level would not stop Bits spawner).

Silverfish spawner will still spawn mobs regardless of light level (like in previous versions).

Not sure about other spawners, these are the ones I've tested in a dungeon.

### Steps to reproduce

1. Go to a dungeon.
2. Find a zombie, skeleton, or cave spider spawner (regular spider spawners, endermen spawners, etc... might also work? No idea).
3. Remove all light sources.
4. Observe no mobs spawning.

### Expected behaviour

Vanilla spawners will spawn mobs in low light levels. I actually have no idea what the expected behavior of Bits spawners or Silverfish spawners should be. For what it's worth, I personally love that Bits spawners can be stopped with a torch now, previously it was just a horrible (tedious, not dangerous) experience to clear those. I'd also love for Silverfish spawners to respect light levels, but at least those can be cardboard boxed.

**Comment by NordicGamerFE** [comment]
Duplicate of #2136

**Comment by hairlessOrphan** [comment]
Closing as duplicate.

**Comment by NordicGamerFE** [comment]
Just checked and this was apparently fixed in 1.4.2 also that was released not to long ago
