### ISSUE TITLE
[Bug]: Megatorch not stopping mother silverfish from spawning silverfish

### ISSUE THREAD

**Issue by DugganB** [FTBTeam/FTB-Modpack-Issues#2150]
### Modpack

Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

Have a megatorch set up with the mother silverfish frozen with a statis chamber. The megatorch is about 4 blocks from the mother silverfish. The mother silverfish is continuously spawning silverfish despite the megatorch being set up.

### Steps to reproduce

1. set up stasis chamber and spawn mother silverfish
2. place megatorch down near boss
3. observe silverfish continue to spawn

### Expected behaviour

Megatorch should stop the silverfish spawning

**Comment by NordicGamerFE** [comment]
duplicate of #2082

**Comment by Sunekaer** [comment]
Because they are not natural spawns.
