### ISSUE TITLE
[Bug]: Major duplication glitch involving Crafting Station and Scribe's Table

### ISSUE THREAD

**Issue by BaguetteJet** [FTBTeam/FTB-Modpack-Issues#2152]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

If you place a Crafting Station from _Tinker's Construct_ directly beside the Scribe's Table from _Ars Nouveau_ it opens a new inventory storage slot on the left. If you put in more than one of ANY stackable item into said slot, you are then able to click and pick up the said amount of stackable items leaving the stacked amount minus one in the slot. This leave you with items left in both the slot and for you to remove, therefore duping the items. You can continue doing this indefinitely. 

### Steps to reproduce

1. Place Crafting Station from _Tinker's Construct_ directly beside the Scribe's Table from _Ars Nouveau_. (either side)
2. Open inventory menu of the **Crafting Station**.
3. A storage slot to the **left** should appear.
4. Place more than one of any stackable item into slot.
5. Either right or left click to remove duplicated items. 
(the stack -1 item stays in the slot and you can take the rest out)

### Expected behaviour

No clue, it just had a slot for some odd reason???

### Screenshots

![23490329032i4u3294i](https://user-images.githubusercontent.com/117129969/204067553-ac886a4e-244c-456b-9bef-0fa3ac03b885.png)
![rweuijjwsgengnrenigerniugewr](https://user-images.githubusercontent.com/117129969/204067555-a8e03c7b-61ec-44bc-9c47-9f3204d578f6.png)
![tr3ju9grefimgfem9i0gfe9dk09gfk](https://user-images.githubusercontent.com/117129969/204067558-4c9b42c0-32e1-4609-95ac-7e2be15fc204.png)

### Additional information

Discovered when playing with friends.

**Comment by Sunekaer** [comment]
Duplicate issue
