### ISSUE TITLE
[Bug]: Meka-tool doesnt give cobblestone

### ISSUE THREAD

**Issue by tapegreen** [FTBTeam/FTB-Modpack-Issues#2153]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

When mining stone with meka-tool, cobblestone is not dropped, nor is it recognized as a tool for ultimine(not sure if intentional since meka-tool has vein mining upgrade). All other mined blocks drop as intended.

### Steps to reproduce

1.use-mekatool on stone
2.nothing is dropped.

### Expected behaviour

cobblestone

**Comment by Timu420** [comment]
the Red Morningstar does also Drop Nothing once mining Stone
