### ISSUE TITLE
[Bug]: Loot bee does not despawn sometimes

### ISSUE THREAD

**Issue by SaphireLattice** [FTBTeam/FTB-Modpack-Issues#2156]
### Modpack

FTB StoneBlock3

### Modpack version

1.4.1

### Describe the bug

Loot bee will not despawn if the game (and I guess server) is shut down and then reloaded, leaving a forever highlit bee floating around.

Same happens if the loot bee sneaks into a beehive/bee nest.

### Steps to reproduce

1. Wait for a loot bee to spawn
2. Save and quit to menu
3. Start the same world again
4. Wait for the bee to despawn
5. It does not, nor does the highlight ever disappear

For bee nest:
1. Wait for a loot bee to spawn close to a bee nest
2. Observe it hovering over the flowers
3. Realize it might not despawn, try and fail to shoo it away from the nest
4. It goes into the nest
5. Eventually it comes out
6. It does not despawn

### Expected behaviour

The bee despawns or the highlight times out

**Comment by Sunekaer** [comment]
Correct, due to bee not having a natural despawn timer, if they get unloaded they wont despawn
