### ISSUE TITLE
[Bug]: Uber-Invisible Vengeance Spirits

### ISSUE THREAD

**Issue by nyx-2525** [FTBTeam/FTB-Modpack-Issues#2159]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

Blackstone Dwarves spawn bugged Vengeance Spirits when they fall to death.

They're invisible even with Vengeance Ring in my inventory.
If I switch to creative mode, I can see them.

When I'm attacked by those spirits with a Burning Gemstone in my inventory, I take both damage AND hunger.
A gemstone Torch will prevent those bugged Vengeance Spirits from spawning, but when I slay Blackstone Dwarves in radius of Gemstone Torch, normal Vengeance Spirits still spawn.

### Steps to reproduce

1. Spawn Blackstone Dwarves via Soul Cage
2. Make them fall 43+ blocks to die from falling
3. Uber-Invisible Vengeance Spirits attacks you.

4. When I have a Burning Gemstone in my inventory, I take both damage AND hunger from those bugged-spirits.
5. Gemstone Torches will prevent bugged-spirits from spawning, but not normal ones slain by me.

### Expected behaviour

Vengeance Spirits don't spawn from falling to death

**Comment by HumdrumPanic** [comment]
I can add that I also cannot see the spirits even with the ring enabled and equipped in my curios/baubles ring slot. also on version 1.30. I have a NVIDIA GeForce RTX 3090. I dunno if there is a setting I could change maybe?

**Comment by Saereth** [comment]
should be fixed in the new evilcraft version coming in 1.6
