### ISSUE TITLE
[Bug]: Hostile mobs arent spawning neither in spawner dungeons nor in dark rooms

### ISSUE THREAD

**Issue by GordonFreeman64** [FTBTeam/FTB-Modpack-Issues#2160]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

upgraded from 1.3.0 to 1.4.2, noticed that hostile mobs stopped spawning in the dark room I made, and also werent spawning in the spawner dungeons. It is back to normal when i downgraded the modpack back to 1.3.0

### Steps to reproduce

1. Upgrade the modpack to 1.4.2 trough the FTB app
2. Make a dark room or go to a spawner dungeon
3. Wait and see that mob aren't spawning...

### Expected behaviour

I expect that mobs should be spawning, like in the 1.3.0 version

**Comment by DMJaxun** [comment]
Same issue on 1.4.1

**Comment by danaYatsuta** [comment]
1.4.2, can confirm

**Comment by MisterSoandSo** [comment]
Boss isn't spawning at all

**Comment by kiiriitsugu** [comment]
had the same experience updating to 1.4.2. even the mobs from dredfull dirt and from mob spawner machine stopped spawning, i only seen slimes spawn after updating.

**Comment by Sunekaer** [comment]
Im not able to replicate this issue.
Please provide log files and if your playing multiplayer or single player and more information about the setup

**Comment by tekkitan** [comment]
Not sure if the same issue or not, but I started a brand new server (1.4.1) a few days ago on Easy difficulty, mobs are not spawning at all unless I get a chance cube that spawns them or I get a spawn egg. Tried upping it to Normal difficulty but same thing no mobs are spawning even hundreds of blocks away in mining tunnels I have created.

**Comment by tekkitan** [comment]
[debug.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10106559/debug.log.gz)

My latest debug log file if it helps.

**Comment by ukmcplyr** [comment]
@tekkitan If you're still on 1.4.1, give 1.4.2 a go. There was a bug relating to hostile mob spawns that got fixed in .2.

**Comment by tekkitan** [comment]
> @tekkitan If you're still on 1.4.1, give 1.4.2 a go. There was a bug relating to hostile mob spawns that got fixed in .2.

Does it? OP seems to be on 1.4.2 and has the same problem. I'll update to 1.4.2 to give it a shot though. Thanks.

**Comment by ukmcplyr** [comment]
@tekkitan Agreed about the OP. If no hostile mobs aren't spawning on **1.4.2**, comment 4 from Sunekaer above applies. But for 1.4.1 only, there was FTBTeam/FTB-Modpack-Issues#2136; upgrading from 1.4.1 to 1.4.2 fixed hostile mob spawning, for me at least.
