### ISSUE TITLE
[Bug]: Rotten Egg recipe not showing

### ISSUE THREAD

**Issue by Joao-Pedro-Bautista** [FTBTeam/FTB-Modpack-Issues#2162]
### Modpack

StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

REI not showing the recipe for the rotten egg on the mob grinding utilities mod

### Steps to reproduce

Press R or LMB on the Rotten Egg item on REI

### Expected behaviour

The recite pops up on REI

**Comment by Sunekaer** [comment]
That is because MGU doesnt have a recipe tab for it.
But you can follow the quest to learn how to get it
