### ISSUE TITLE
[Bug]: Redstone components don't update and stay 'triggered'

### ISSUE THREAD

**Issue by Skyknight46** [FTBTeam/FTB-Modpack-Issues#2164]
### Modpack

Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

I'm trying to create a dispenser on a timer to place water and pick it back up. Whenever the dispenser get's triggered once it stays triggered meaning it becomes completely unresponsive to redstone. Had sort of the same issue with redstone lamps aswel where they would stay lit after toggling them once.

### Steps to reproduce

Difficult to reproduce since it only is in certain spots in the world.
1. Place a dispenser.
2. Trigger said dispenser using a sequencer from RFTools.
3. Look at the dispenser with 'F3' debug window open.

### Expected behaviour

State of dispenser stays triggered even though no redstone is triggering it.

### Screenshots

![image](https://user-images.githubusercontent.com/43069708/204105400-d62256fd-9340-46d5-91e4-0f773e53458f.png)

**Comment by UnRealDinnerbone** [comment]
The lever on the wall closest to you is powering it
