### ISSUE TITLE
[Suggestion]: Add Cable Tiers and ExtraStorage to StoneBlock 3

### ISSUE THREAD

**Issue by dylanrenwick** [FTBTeam/FTB-Modpack-Issues#2165]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Refined Storage is my preferred storage mod, but it has one major drawback; slots. RS Crafters have only 9 slots for patterns, and RS Importers/Exporters/etc. have only 9 slots for white/blacklists.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/cable-tiers

Cable Tiers introduces higher-tier Importers, Exporters, Constructors, Destructors, Disk Manipulators, and Requesters from RS: Requestify (already present in SB 3)
These have more slots for filtering, are faster, and at the highest tier feature a built-in stack upgrade.
All default recipes are displayed in the CurseForge page.

https://www.curseforge.com/minecraft/mc-mods/extrastorage

ExtraStorage introduces higher-tier Crafters. Iron, Gold, Diamond, Netherite. Each is faster and can hold more patterns.
It also adds larger disk options, and storage block versions of all disks.
ExtraStorage also has its own Advanced Importer and Exporter that have 18 slots, but I would recommend disabling these if also using Cable Tiers.

Notably, ExtraStorage adds its own higher-tier processor - the Quantum Processor - used for Gold-tier and above crafters. The default recipe for this processor is quite different to the vanilla RS processors, but it may want to be revised to match the Create sequenced assembly based approach of other processors.

**Comment by Sunekaer** [comment]
Already been suggested and said no to :)
