### ISSUE TITLE
[Bug]: Refined storage don't see energy cable from powah in fast crafting

### ISSUE THREAD

**Issue by MrRavain** [FTBTeam/FTB-Modpack-Issues#2168]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.1

### Describe the bug

Even if u have some energy cables in your inventory or on disk drive from refined storage mod u have to manually put cables in crafting beacuse they're pointing red. 

### Steps to reproduce

Open crafting grid 
Find recipe in Jei
Hover at "+" button 
see highlight red cables 
done

### Expected behaviour

Cables don't want to cooperate xD

### Screenshots

![bug1](https://user-images.githubusercontent.com/118583745/204114862-6119fa85-a3d3-4942-b5dd-c76ecb6a0e3a.png)
![bug2](https://user-images.githubusercontent.com/118583745/204114864-ed5a6503-0922-4ad1-8bac-d276f324799d.png)

**Comment by Sunekaer** [comment]
Works in my instance so either fixed in newer version of the pack or in a mod there is updated in my instance :D
