### ISSUE TITLE
[Bug]: Energy cables from Powah are not stacking automatically in inventory

### ISSUE THREAD

**Issue by MrRavain** [FTBTeam/FTB-Modpack-Issues#2169]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.1

### Describe the bug

Separate cable in inventory after picking it up  from ground

### Steps to reproduce

Have at least 3 same cable from powah
place one
mine it 
cable don't stack to those 2 but take another slot in inventory
done

### Expected behaviour

Not stacking

### Screenshots

![bug1](https://user-images.githubusercontent.com/118583745/204115179-b5f5525d-5254-4d5a-9ee6-b9b37fc9c94b.png)
![bug2](https://user-images.githubusercontent.com/118583745/204115181-82ab7818-98ce-4466-a06e-b8afac1648f0.png)

**Comment by Sunekaer** [comment]
Because they have NBT data stored on them, from when you had them placed, i cant do anything about that
