### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CommunistFishy** [FTBTeam/FTB-Modpack-Issues#2170]
### Modpack

Stoneblock 3

### Modpack version

1.3.0

### Log Files

[Latest.log](https://pste.ch/gavegodexo.md)
[console.log](https://mclo.gs/5v9orZf)
[debug.log](https://drive.google.com/file/d/1wk9mNxuzmfaUpA8v8LCz2rP0vlo-AwQ7/view?usp=share_link)
google drive was used for the debug.log as it was too large to upload anywhere else.

### Describe the bug

while searching for an item in the transmutation table, i first experienced stuttering, and then a complete freeze of my game, where it then whitescreened and i had no option other than to force close it.

### Steps to reproduce

1. open a transmutation table
2. get energy up to ~800 quintillion
3. add several pages worth of items
4. search for anything
a crash should occur, [here is a video](https://youtu.be/NqitJLeyufA) of me reproducing the bug.

### Expected behaviour

I expected the transmutation table to search for the item i was looking for, and display it to me without freezing or crashing.

### Screenshots

https://youtu.be/NqitJLeyufA this is not a screenshot, but a video of the items used in the table.

### Additional information

i have several pages of items in the transmutation table, and somewhere in the range of 800 quadrillion EMC-1 Quintillion

**Comment by Sunekaer** [comment]
Your on an outdated version of the pack, please update
