### ISSUE TITLE
[Bug]: Possible dungeon location bug?

### ISSUE THREAD

**Issue by hairlessOrphan** [FTBTeam/FTB-Modpack-Issues#2171]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

I suspect dungeons are always supposed to generate on or near a straight line in any of the four cardinal directions (i.e. X=0 or Z=0)? From my first three playthroughs, this always happened, and from the map screenshot in the guidebook (though that appears to be a random world and not meant as guidance or anything) this seems to also be true. In my current playthrough, I don't have an End Dungeon in the region due North from 0,0,0.

![Screenshot 2022-11-26 234301](https://user-images.githubusercontent.com/3323307/204119644-885cd52c-9ce3-4c87-8d46-2d44ca8fbbf1.png)

### Steps to reproduce

1. Start game with seed: -6243098729474182730
2. Dig north forever

### Expected behaviour

Dungeons appear in all four cardinal directions?

**Comment by Sunekaer** [comment]
Placement of dungeons are random, so this is fine.
