### ISSUE TITLE
[Suggestion]: StoneBlock 3: revert the spawn rules in Forest biome

### ISSUE THREAD

**Issue by hairlessOrphan** [FTBTeam/FTB-Modpack-Issues#2172]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

I know this was originally a bug that mobs wouldn't spawn naturally in the Mother Silverfish dungeon, but that made the dungeon feel eerie and beautiful. It was a place to enjoy the build and then have a boss fight. Now it's just another creeper-blown, torch-covered, garbage-loot strewn speedbump that isn't worth looking at. The "no mobs" version was worth experiencing for itself, and trying to make this another poor man's Vault Hunter run kind of ruined that.

To explain what I mean: I have no idea what the rooms in the other three dungeons look like. I'm sure someone put a lot of time into making them look nice, but I don't see it before it's torn apart, and honestly I'm too busy killing and looting to care. This dungeon, though, I got a really good look at, stole some ideas for my own base, and really looked forward to coming back to.

I think y'all should lean into this build and not just revert the light-level spawn rule change, but remove the spawners (and of course move the loot to another dungeon), and just make this a peaceful place with a giant boss in the center, where the real challenge is killing the boss without letting it destroy the center summoning room.

**Comment by Sunekaer** [comment]
This change wont be reverted.
Thanks for the suggestion tho :)
