### ISSUE TITLE
[Suggestion]: Unable to clear items config using crafting table

### ISSUE THREAD

**Issue by rtm516** [FTBTeam/FTB-Modpack-Issues#2174]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

It would be good if you could reset configurable items when placed into a crafting grid so they can stack nicely in a storage system.
A few I have found so far are:

- Filter (Create)
- Energy Cable (Powah)
- Ender Gate (Powah)
- Redstone Transmitter (RFToolsUtility)
- Redstone Reciever (RFToolsUtility)

**Comment by Sunekaer** [comment]
Powah seems to not save this data anymore from my testing.
But ill add for the others
