### ISSUE TITLE
[Bug]: Zombie Villager can't be cured to get vanilla Villager

### ISSUE THREAD

**Issue by Jan102** [FTBTeam/FTB-Modpack-Issues#2175]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

You need vanilla Villagers to complete the questline "Welcome Back, Friend...".
Using the vanilla mechanic or Ars Nouveau transforms them only into MineColonies mobs instead of vanilla villagers.

### Steps to reproduce

1. Spawn Zombie Villager with Summoning Altar
2. Cure either with vanilla mechanic or Ars Nouveaus Tablet or Restoration
3. MineColonies villagers

### Expected behaviour

Curing Zombie villagers should make vanilla villagers

**Comment by orbidlo** [comment]
This is not bug but feature :) Read the quest warning you to cure them outside of colony influence (that is borders, you can display when holding building wand). Within boundary -> citizens, outside boundary -> villagers.

**Comment by tyler489** [comment]
Alternatively remove your tavern block, as that is what causes the conversion.
