### ISSUE TITLE
[Suggestion]: Can we please address the curios problem going forward in future modpacks?

### ISSUE THREAD

**Issue by JustJinxed** [FTBTeam/FTB-Modpack-Issues#2177]
### Modpack

Future Modpacks

### Is your suggestion related to a problem? Please describe.

re:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1247
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1839

### Mod suggestion

I realize this issue has already come up in SB3, as it did in Direwolf20 and Oceanblock - and that it can't be changed now. 
Just would like to know why FTB didn't switch grave mods between these releases? Is Enigmatic graves lacking in some department? Is there a lack of some other good alternative? We're all still losing items here and there from inventory spillover.

**Comment by Sunekaer** [comment]
We will keep this in mind for the future
