### ISSUE TITLE
[Bug]: Void Ore Miner Magic Ore Doesn't give source gem ore

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#218]
### Modpack

Ftb University 

### Modpack version

1.3.0

### Describe the bug

The magic ore setting only mines vinteum, should also do source gem ore as its magical.

### Steps to reproduce

1.) run the miner

### Expected behaviour

Also give source gem ore

**Comment by Raidobw2** [comment]
Hello, which miner exactly are you referring to so our modpack dev can have the information more easily available to him?

**Comment by JunaidA197** [comment]
Its the envirotech void ore miner

**Comment by aaronhowser1** [comment]
Forwarded to mod dev. The tag for the ore changed, so I assume that's what's at fault.

**Comment by Raidobw2** [comment]
Awaiting ET update: https://www.curseforge.com/minecraft/mc-mods/environmental-tech/files/all?filter-game-version=2020709689%3A8203

Left it in your workspace Aaron since that thing is harder to monitor for me.
