### ISSUE TITLE
[Suggestion]: Add Quarry Mod

### ISSUE THREAD

**Issue by UnhappyCodings** [FTBTeam/FTB-Modpack-Issues#2180]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

No. It isnt

### Mod suggestion

The mod simply adds a simple quarry which doesnt need any FE/RF and has a lot of features in one block

Thanks!

https://www.curseforge.com/minecraft/mc-mods/quarry

**Comment by tyler489** [comment]
The rftools builder can act like a quarry if you craft a quarry card if you didnt know

**Comment by Sunekaer** [comment]
rftools builder works as a quarry
