### ISSUE TITLE
[Bug]: Mother Silverfish keeps spawning Thief/Leech/... silverfish while being effected by the Stasis Chamber

### ISSUE THREAD

**Issue by PhamKun** [FTBTeam/FTB-Modpack-Issues#2184]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

Im not sure if its a bug or not. But when the Mother Silver fish got froze, she still spawning the little silverfish, but they were also got froze by  the stasis chamber. It would be fine if shes not trying to spawn more, but she does. The the farm become a source of lag on my server, there are about 300 of the small silverfishes.

### Steps to reproduce

1. Summon the Mother Silverfish
2. Using Stasis chamber to freeze her
3. Leaving her there, and eventually the Silverfish will spawn.

### Expected behaviour

I kinda expecting the silverfish mother stop spawning when the number of the small silverfish reach to a certain number

**Comment by Sunekaer** [comment]
This is correct as the little silverfish isnt natural spawns but an attack she does

**Comment by PhamKun** [comment]
But I didn't attack her. There is only the drymy trying to get items from her.

**Comment by BasteFw** [comment]
@PhamKun , you find a solution ?

**Comment by PhamKun** [comment]
> @PhamKun , you find a solution ?
Yes. I think the statis chamber keep the state of the Silverfish mother when she spawns. So when you start the ritual. Hide somewhere that she cannot see you, e.i hide behind the column. Doing that the statis chamber will save the state when the mother didnt see you.

**Comment by BasteFw** [comment]
@PhamKun , Thank you for your solution
