### ISSUE TITLE
[Bug]: Gaia Guardian becomes unkillable if the player dies during the fight

### ISSUE THREAD

**Issue by meow121325** [FTBTeam/FTB-Modpack-Issues#2185]
### Modpack

FTB stoneblock 3

### Modpack version

1.4.2

### Describe the bug

during the gaia guardian fight if the player dies the boss, music, and barrier will still be there without any AI rendering the entity unkillable 

### Steps to reproduce

1. activate the ritual of gaia from botania
2. die to the gaia guardian
3. respawn

### Expected behaviour

gaia guardian remains in place when player died with no AI

**Comment by UnRealDinnerbone** [comment]
I'm unable to reproduce this issue. If this still happens in the latest version, please reopen this issue
