### ISSUE TITLE
[Suggestion] [Bug]: Chance Cube Events

### ISSUE THREAD

**Issue by burg5204** [FTBTeam/FTB-Modpack-Issues#2186]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Can we add the overworld spawn location to NoChanceCubeHere.js for KubeJS?

During lag spikes player could place on portal and spawn giant chance cube in spawn location. I was not able to replicate the issue, but it has happened with griefer accounts, server owners beware of players "AugVP" and "_JarFile_"

### Mod suggestion

KubeJS Location - [kubejs]
/
[server_scripts]
/
[_core]
/
nochancecubehere.js

**Comment by Sunekaer** [comment]
So when the player is in the lobby they are in Adventure mode, so they are not able to place things, so they real questions is how the person wasnt in that.
If they used cheats to do then i cant do anything about it.
Without a way of recreating the issue there is nothng i can do to stop it, but we will keep an eye on this

**Comment by burg5204** [comment]
> So when the player is in the lobby they are in Adventure mode, so they are not able to place things, so they real questions is how the person wasnt in that. If they used cheats to do then i cant do anything about it. Without a way of recreating the issue there is nothng i can do to stop it, but we will keep an eye on this

Found Issue-
Players can spawn them.
https://github.com/TheTurkeyDev/ChanceCubes/issues/274
