### ISSUE TITLE
[Bug]: feral lantern breaking fission reactor  and thermal electric boiler

### ISSUE THREAD

**Issue by slckbutter** [FTBTeam/FTB-Modpack-Issues#2187]
### Modpack

stoneblock 3

### Modpack version

1.4.2

### Describe the bug

placed down a feral lantern and the light sources broke the two machines and then i broke lantern it erased all resources in the machines and then continued to fill and run then explode

### Steps to reproduce

build fission reactor and thermal electric boiler
then add resources 
then let run for a few 
then place a feral lantern down to watch it break every thing related to said machines
restart machines to start working again 
and wait for them to explode

### Expected behaviour

the feral lantern was to place light sorces not in machines and provide better lighting in my enviroment

**Comment by Sunekaer** [comment]
Well feral lantern places light sources in air, there is no way it can detect if it's inside a multiblock.
youll just have to use normal ligthing around those
