### ISSUE TITLE
[Bug]: stoneblock 3 world not opening

### ISSUE THREAD

**Issue by bithhub** [FTBTeam/FTB-Modpack-Issues#2188]
### Modpack

FTB stoneblock 3

### Modpack version

1.4.1

### Describe the bug

I can open the game but when i open my world, it gets stuck on a blank screen and never loads my world

### Steps to reproduce

Launch stoneblock from FTB app
open single player world
world doesn't load

### Expected behaviour

World opens like normal

**Comment by Sunekaer** [comment]
Please use 1.4.2 and provide your log file so we can see what happens

**Comment by bithhub** [comment]
> Please use 1.4.2 and provide your log file so we can see what happens
![Screenshot (25)](https://user-images.githubusercontent.com/117700333/204496808-65e9bdb8-0128-4c92-9a75-21182f74cc47.png)

**Comment by Raidobw2** [comment]
At that picture you posted, there's a button in the FTB App right above, in green, called "Open Folder"/"Instance Folder". Click it, and inside the `logs` folder you'll find the `latest.log` file which you can drag and drop here.

Also, in the `saves` folder this time, there will be your world. You can right click > Send To > Archive/Zip.
Then you can put that zip on Google Drive for example and share the world here.

We'd still need at least the log to help you solve this, as the current log window you posted does not have enough information for us to conclude anything at the moment... If you add your world as well and it's broken, I can also fix it.

Thanks in advance for checking that!

**Comment by bithhub** [comment]
https://drive.google.com/file/d/173S9cy6aiOoG5spN7L0enEhc3XkXYnCN/view?usp=sharing
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10147830/latest.log)

**Comment by bithhub** [comment]
I tried something like that. I restored my latest back up and I was able to open my world. But the next time I opened it, i couldn't open my world anymore.
