### ISSUE TITLE
[Bug]: Stone wand can infinitely copy cobblestone

### ISSUE THREAD

**Issue by Loberd** [FTBTeam/FTB-Modpack-Issues#2191]
### Modpack

FTB Stoneblock3

### Modpack version

1.4.2

### Describe the bug

stone wand can infinitely copy cobblestone. other blocks get placed from inv like they should.

### Steps to reproduce

Launch SB3 in Singleplayer Survival.
Craft a Stone Wand
You are now able to infinitely copy cobblestone around you, it doesn't use the cobble in your inventory.
It uses other blocks as intended.

### Expected behaviour

When I play in Survival, the wand should just be able to paint with blocks in my inventory. even cobble I remember I used to use a wand item in sb2 as well. Though I am almost sure it was from a different plugin.

**Comment by Sunekaer** [comment]
Im not able to recreate this issue, what other things do you have in your inventory / world?
Does this also happen on a fresh world?

**Comment by Loberd** [comment]
Earlier, I reproduced it successfully three times before posting the report, each time restarting minecraft in between.
However, I can not reproduce it anymore, no matter what I do. It works completely as intended in all worlds and scenarios I can come up with.
