### ISSUE TITLE
[Bug]: Crash When Looking at Nether Gold Ore in World

### ISSUE THREAD

**Issue by Darkfiend009** [FTBTeam/FTB-Modpack-Issues#2192]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Log Files

https://pastebin.com/9kVvkjMV

### Describe the bug

I was floating around in a newly generated single player world to see how the modpack was setup worldgen wise in creative. I stopped and looked a Nether Gold Ore and crashed to desktop.

### Steps to reproduce

I am not sure how reproducible it will be, to be honest.

### Expected behaviour

Not to crash

**Comment by orbidlo** [comment]
Including the logs is essential, without them we don't really know true reason for crash.

**Comment by Darkfiend009** [comment]
My apologies!

latest.log: https://gist.github.com/Darkfiend009/9e2f0f5dad6b92e7bcfbbdc6b8999cd6

debug.log: https://gist.github.com/Darkfiend009/c07f97eddbc6b5791f9618a8f110bddf

**Comment by Saereth** [comment]
I don't see a crash in these logs, do you have anything in your crash-reports folder?
