### ISSUE TITLE
[Bug]: illegal packet received after starting several clocks

### ISSUE THREAD

**Issue by gabriel13336** [FTBTeam/FTB-Modpack-Issues#2193]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

If I play with someone in the world via LAN and start after 16 watch of flowing time, the person playing with me in the world receives an error (illegal packet received)

### Steps to reproduce

1. Start at least 16 watch of flowing time
2. Continue to start one by one in continuation of the 16
3. Wait about 4-5 minutes between the clocks started later
4. Then the person connected via LAN receives the error

### Expected behaviour

I expected it to work normally with several clocks, because if I play alone in the world, only the people who enter my world take me out

**Comment by Raidobw2** [comment]
Hi, thanks for reporting, do you think you could add more information such as game logs / error messages you mentioned? That would help us compare with our games when we reproduce / test for this. Thanks in advance
