### ISSUE TITLE
[Bug]: Map not showing Nether Dungeons

### ISSUE THREAD

**Issue by SudzBud** [FTBTeam/FTB-Modpack-Issues#2194]
### Modpack

Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

Looking at map could not find any dungeons in Nether ring. Checked my map settings and didn't find any options that may help.

After returning to home area, my map started showing really off colors, pink, green, purple.

Went to compact machine world and came out, now map has no features at all, just mob icons.

At this point, I'd be happy to just completely reset my map, if that is a thing.

### Steps to reproduce

go to nether ring
open map settings
return to base
open map settings
go to compact machine
open map settings

### Expected behaviour

expected to find nether dungeon areas and map not to corrupt

**Comment by Raidobw2** [comment]
Hello, would you be able to add a screenshot of your map/minimap so we can see what the issue looks like? This will be helpful if this ends up being a mod issues, thanks!

**Comment by SudzBud** [comment]
![Snag_43857209](https://user-images.githubusercontent.com/8115888/205449663-c9fe21c7-87a2-4121-ab26-6ca9fd058fd4.png)
![Snag_4385cf6b](https://user-images.githubusercontent.com/8115888/205449676-abb35da9-9aef-4bc8-b2be-1986942e5997.png)

**Comment by SudzBud** [comment]
The latest update seems to have fixed the map content, 

Now I have a question about world gen. See map below. Should there be dungeons within these regions of Nether ring and Ender Ring or is my RNG just horrible?

![2022-12-10_13-10-04](https://user-images.githubusercontent.com/8115888/206869529-10a4a6c0-e01e-4a8f-a9cf-a3298158345e.png)
