### ISSUE TITLE
[Suggestion]: Add Dave's Building Extended (Decoration mod)

### ISSUE THREAD

**Issue by TheAmazingJeh** [FTBTeam/FTB-Modpack-Issues#2195]
### Modpack

FTB Stoneblock Three

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/daves-building-extended/

This mod adds lots of cool blocks, and makes creating Create trains more fun as it has blocks specifically designed for trains like boilers and buffers.

**Comment by Sunekaer** [comment]
We are not looking to add more mods to this pack. thanks for suggestion
