### ISSUE TITLE
[Bug]: Chancecube Follow-Up

### ISSUE THREAD

**Issue by burg5204** [FTBTeam/FTB-Modpack-Issues#2196]
### Modpack

Stoneblock 3

### Modpack version

1.4.2

### Log Files

Follow up #2186 --SEE BELOW IN DESCRIBE--

Can we add the overworld spawn location to NoChanceCubeHere.js for KubeJS?

During lag spikes player could place on portal and spawn giant chance cube in spawn location. I was not able to replicate the issue, but it has happened with griefer accounts, server owners beware of players "AugVP" and "JarFile"

### Describe the bug

Found Issue-
Players can spawn them, chancecubes can be spawned by /chancecubes <command>

Tried setting command to false in FTB Ranks did work.

https://github.com/TheTurkeyDev/ChanceCubes/issues/274

### Steps to reproduce

1. Start Game
2. Log to Server
3. Play Legit

### Expected behaviour

disabled commands for players

**Comment by manmaed** [comment]
looks like its been fixed with this: https://github.com/TheTurkeyDev/ChanceCubes/issues/277

**Comment by manmaed** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2146
