### ISSUE TITLE
[Bug]: Crafting Framed Drawers using Chipped Blocks crashes the game

### ISSUE THREAD

**Issue by D4T4N0TF0UND** [FTBTeam/FTB-Modpack-Issues#2197]
### Modpack

FTB Stoneblock 3

### Modpack version

1.3.0

### Log Files

https://paste.feed-the-beast.com/view/b12a7276
[crash.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10145920/crash.txt)

### Describe the bug

crafting framed drawers using chipped blocks (tested with tiny brick bordered dark prismarine) crashes the game as soon as the output is attempted to be rendered

### Steps to reproduce

open stoneblock 3
craft chipped block in first 2 crafting table slots and framed drawer in third
client crashes

### Expected behaviour

client does not crash and correct framed drawer is output

**Comment by Raidobw2** [comment]
I'll track this issue https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2452, so I will close this one. Thanks for the report
