### ISSUE TITLE
[Bug]: Can't access high value EMC items

### ISSUE THREAD

**Issue by EfficiencyVI** [FTBTeam/FTB-Modpack-Issues#2198]
### Modpack

Stoneblock 3

### Modpack version

1.4.x

### Describe the bug

Something is wrong with extended exchange. Since 1.4.x I can't take any high value EMC item out of the EMC link. It's just doing nothing like I lack EMC. AE2 doesn't see the items either.

Downgrading to the version before (from 1.3) fixes the problem. 

### Steps to reproduce

Generate enough EMC
Try to take out yellow matter out of the EMC link (no matter what block exactly).

### Expected behaviour

You should be able to access all items you have enough EMC

### Additional information

Other people in chat confirmed the issue.

**Comment by leofred** [comment]
i'm having the exactly same issue...

**Comment by Intoned** [comment]
Came here to say this.
