### ISSUE TITLE
[Bug]: Mekatool not functioning on use against stone blocks.

### ISSUE THREAD

**Issue by Listalli** [FTBTeam/FTB-Modpack-Issues#2199]
### Modpack

Stoneblock 3

### Modpack version

1.21

### Describe the bug

Mekanism Mekatool will not drop stone blocks when mined, efficiency module functions as intended, but alongside stone not dropping, the blasting module does not work on stone. Once you attempt to mine anything other than stone blocks, all modules function as intended. Equipping the vein miner module had no discernable effect.

### Steps to reproduce

Im unsure of how this can be reproduced, as it only just started happening after my brother got his own tool and used it.

### Expected behaviour

Mekatool modules function as intended with mining stone, as well as dropping blocks.

**Comment by Raidobw2** [comment]
This was reported at #2153, which I believe was fixed in a development version (might not have been released to the public yet). I'll be closing this issue since we'll be tracking the problem in the other issue (you can subscribe to that other issue if you want notifications)
