### ISSUE TITLE
Supremium furnace does not process all clusters from Rid mod[Bug]: 

### ISSUE THREAD

**Issue by NunbearTWITCH** [FTBTeam/FTB-Modpack-Issues#22]
### Modpack

FTB Oceanblock

### Modpack version

1.1.0

### Describe the bug

i have set up a crafter to make the clusters from the sluiced pieces and when putting them into a supremium furnace only 2 of the types of chunks would smelt to bars.

The only cluster that work are aluminium and osmium.

### Steps to reproduce

put clusters into supremium furnace
add coal
bar should be produced.

### Expected behaviour

bar should be made from clusters in furnace

**Comment by Kevin-Marsh** [comment]
I think their intentions were that all clusters were supposed to be processed through the jar mod or tinkers. I pump all the clusters through a Mekanism enriching factory to double them into dusts and then into the furnace. A tip as well, the Krate mod can auto craft the pieces as well as being a storage to receive and store them.

**Comment by neonbladez2** [comment]
Yep, you can't smelt the clusters in a furnace, have to be jars. As long as you have a automated setup then you are good to go. Like what Kevin said the next step would be to use mekanism. If not then jars is your option.

**Comment by NunbearTWITCH** [comment]
Ah so the issue should be that aluminium and osmium could be smelted.

**Comment by MichaelHillcox** [comment]
Yeah, you have to use jars for clusters :)
