### ISSUE TITLE
[Bug, DimensionalPaintings]: Breaking Block behind Dimensional Painting makes it disappear

### ISSUE THREAD

**Issue by LemmingYellow** [FTBTeam/FTB-Modpack-Issues#220]
### Modpack

FTB OceanBlock

### Modpack version

1.5.0

### Describe the bug

We were trying to figure out how to use dimensional paintings, and trying different ways to make it work. I picked up and put down the painting, and my partner said "I wonder if we have to walk through it?"

He was behind the wall and broke the block behind it, which would cause a typical painting to pop off the wall. Instead, it totally disappeared! It's not the end of the world because we aren't hurting for resources, just a pain.

We built a 1 deep, 6 across, 4 tall wall of Cobble that had been chiseled to Tiles, and built stone brick stairs up to the level of the painting. 

I placed it in the middle and breaking the block one in from the corner broke the painting.

```
WWWWWW
WPPPPW
WPPXPW
WWWWWW
```
(this is the wall, the X is where we broke)

He also broke the block above that first and it didn't affect the painting. 

We both logged out and reloaded the world, to no avail.

### Steps to reproduce

((We have not tried it more than once))
1. Create wall with chiseled cobble
2. Place painting on wall
3. Break block painting was placed against

### Expected behaviour

Painting pops off and is NOT destroyed

**Comment by LemmingYellow** [comment]
UPDATE: So I made another one and went through the portal (after watching videos on how to) and my other nether portal painting was there, on the other side.

**Comment by Mrbysco** [comment]
This has been fixed in version 1.2 of Dimensional Paintings
