### ISSUE TITLE
[Bug]: FTB Stoneblock 3 crash, mere seconds after launching

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#2200]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.2

### Log Files

https://pste.ch/xameyepumu.log

### Describe the bug

launched the game and before I had a chance to do more than open my inventory and see if I left any unfinished business, and close it again, suddenly all froze and shortly after the window closed itself

### Steps to reproduce

1. frankly not sure, don't really know what happened or why

### Expected behaviour

no crash? no crashes is good.

### Additional information

Wish I had more to give you to go on besides the crash report. will follow up further if it happens again

**Comment by Raidobw2** [comment]
Might be something to do with REI. Has this happened again?

**Comment by WebDragon** [comment]
not yet, fortunately. If it does, you'll be the next to know about it.

**Comment by Raidobw2** [comment]
Updated REI again in-dev 1.6.0, hopefully this is resolved 👍 REI has had a bunch of fixes between SB3 v1.4.2 and now. I'll mark this as fixed in-dev for now.

If this happens again let me know and thanks for reporting 🙂
