### ISSUE TITLE
[Bug]: When adding an invalid item to a framed storage drawer craft it crashes to desktop

### ISSUE THREAD

**Issue by NunbearTWITCH** [FTBTeam/FTB-Modpack-Issues#2202]
### Modpack

Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

When you create a framed storage drawer and want to set what it looks like if you accidentally add an invalid item it crashes me to desktop

### Steps to reproduce

put the framed drawer in crafting bench/grid
Add first block e.g wood
Add second item e.g. glow berry
Game crashes to desktop

### Expected behaviour

should just be an invalid craft

**Comment by Raidobw2** [comment]
This looks similar as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2197. Can you confirm if that is the same thing, or your report is for something different? Thanks

Also, please add your crash log or game logs, they will help us forward the issue to mod developers

**Comment by Raidobw2** [comment]
I'll be tracking this issue at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2452
