### ISSUE TITLE
[Bug]: My world doesn't load.

### ISSUE THREAD

**Issue by IchLarss** [FTBTeam/FTB-Modpack-Issues#2203]
### Modpack

Stoneblock 3 v1.4.2

### Modpack version

v1.4.2

### Describe the bug

When I start Stoneblock everything is normal but when i want to join my world (or create a new one) i get stuck in a grey screen with just the little tip in the corner.

### Steps to reproduce

1. Open the modpack
2. try to join a world
3. Get stuck in the loading screen

### Expected behaviour

I think it happend last night wwhen my pc crashed while i was closing the world.

**Comment by Raidobw2** [comment]
Hi, try following these instructions:
1. Make an immediate copy of your world that's inside the `saves` folder. In the FTB App, you open the files to the instance folder with the "`...`" dots next to "Play".
2. For instructions \# 3 and more, only work on that copy.
3. Enter the copy of the world and inside your `world`'s folder you will find a `serverconfig` folder. Delete every file inside that `serverconfig` folder.
4. Return to the "root" of the modpack where there is the `saves` folder. Locate the `defaultconfigs` folder next to it.
5. Copy all files inside the `defaultconfigs` folder and paste them inside the `world` copy, in the `serverconfig` folder from earlier.
6. Start your game and try to join your world.
7. Let me know if it works
