### ISSUE TITLE
[Bug]: FTB Stoneblock 3 Map causing crash

### ISSUE THREAD

**Issue by NeonDactyl** [FTBTeam/FTB-Modpack-Issues#2205]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Log Files

[debug-1.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10119494/debug-1.log)

### Describe the bug

Screen is null within the ftbchunks client; attempting to open the map causes full client crash.

### Steps to reproduce

Attempt to open FTB Chunks map within Stoneblock 3, modpack version 1.4.2

### Expected behaviour

I expect the pack to not crash

### Additional information

 Updated pack to version 1.4.2 from 1.0.2, and the issue began upon the pack update. Occurs for both myself and my wife, launching from the FTB App through overwolf

**Comment by Raidobw2** [comment]
Oh I'm super late... I'm sorry.

I think our mod dev Des fixed this for all versions after a lot of digging. Pressing 'M' should no longer crash the game.

Stoneblock 3 version 1.6.0 should be out next week with some fixes regarding crashes
