### ISSUE TITLE
[Bug]: NPEs from Chickens mod leads to unresponsive FTB App

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#2207]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.2

### Log Files

N/A

### Describe the bug

I'm seeing a metric tonne of stacktraces like in the screenshot below that seems to be coming from the Chickens mod. Unfortunately none of these are making their way to logs.

Though likely a seperate issue, scrolling through to try and gather some context, the app hangs, later spins on a single core 100% for five minutes give or take and the app is left in a completely unresponsive state UI-wise.

This is all on a server. Removing the sole Roost containing a Soul Sand Chicken and restarting stops the app's console getting flooded but adding it back starts the same waterfall of NPE messages on the console.

### Steps to reproduce

1. Place down a Roost with a Soul Sand Chicken (10/10/10 here) inside
2. Wait for stacktraces to flood in on the app console

### Expected behaviour

No/fewer NPEs

### Screenshots

![Screenshot](https://gcdnb.pbrd.co/images/o9j4hARL5F71.png?o=1)

**Comment by Raidobw2** [comment]
If you manage to get full logs for this, it would help a lot since I'm unsure if that's chickens or REI that should be looked into.
Do you know if this happens when looking into the Roost's GUI or regardless if the player is looking into it? (but the chicken is inside at all times)

**Comment by ukmcplyr** [comment]
This is really annoying. I made sure I could reproduce this through two clean boots of both the client and server the other day and now I can't. I have upgraded my stalwart 17.0.3 JDK to 1.0.5 only last night, though. I'll try downgrading JDK sometime this weekend and see if that's the missing piece.

**Comment by ukmcplyr** [comment]
Either I got the reproduction steps wrong or I've found another way to trigger it.

Searching for `@chicken` in REI is enough.

And this time I've managed to get more than `java.lang.NullPointerException` printed to logs over and over.

[console.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10146980/console.log.gz)

**Comment by Sunekaer** [comment]
Works in my instance so either fixed in newer version of the pack or in a mod there is updated in my instance :D
