### ISSUE TITLE
[Bug]: Crash after requesting item

### ISSUE THREAD

**Issue by Reithsaw** [FTBTeam/FTB-Modpack-Issues#2208]
### Modpack

FTB Stoneblock 3

### Modpack version

V1.4.2

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10124968/latest.log)
[crash-2022-11-30_17.07.49-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10124970/crash-2022-11-30_17.07.49-client.txt)

### Describe the bug

If you open the quest book and click on an item, after that it the +, and craft it with a wireless universal terminal the game crashed, i don't know if it's a mod problem, or other things.

### Steps to reproduce

1. Have a wireless universal terminal (here the KJS if you want the exact same one `Item.of('ae2wtlib:wireless_universal_terminal', '{crafting:1b,currentTerminal:"crafting",filter_type:"ALL",gridKey:16690419015438L,internalCurrentPower:4800000.0d,internalMaxPower:4800000.0d,pattern_access:1b,pattern_encoding:1b,show_pattern_providers:"VISIBLE",sort_by:"AMOUNT",sort_direction:"DESCENDING",upgrades:[{Count:1b,Slot:0,id:"ae2wtlib:infinity_booster_card"}],view_mode:"ALL"}')` )
2. Open the quest book
3. Click on a quest
4 .Click on the item requested
5. Click on the " + "
6. probably the game crashed
7. if not, redeem the item crafted and then crashed

### Expected behaviour

don't crash lol

**Comment by Raidobw2** [comment]
I've followed your instructions and it seems to be working fine in 1.6.0, in-dev version. I've used the terminal to craft a stone chest from the quest book, no issues.
Looks like this was fixed in earlier versions, perhaps in 1.5.0!
