### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hardytm426** [FTBTeam/FTB-Modpack-Issues#2209]
### Modpack

Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

No recipes for any of the Refined Storage processors.

### Steps to reproduce

Click on raw processor in REI and no recipe is shown.
Also tried crafting processors via previous Create crafting process and it doesn't work.

### Expected behaviour

Ability to see how to craft raw processors

**Comment by hardytm426** [comment]
I did forget to add that I'm playing this on a Linux server from a Windows client.  I fired up a new test world on my Windows PC and the recipes are there for all the raw processors.  I then tried using create to build them and it works, so the issue is with the Linux server.  If I knew which config files may cause this, I'd copy them over from my Windows device to the Linux server to see if that solves the issue.

**Comment by hardytm426** [comment]
As a test, I shut down my server and copied the server_scripts & startup_scripts folders from the kubejs folder to the server, after deleting the ones there, fired the server back up and connected.  I now have raw processor recipes.  I then tested it with my Create setup I had for them and it works!  So itr looks like the Linux server files are just not correct.

**Comment by NordicGamerFE** [comment]
Guess this is related to #2014
