### ISSUE TITLE
[Bug]: Wither Spawner

### ISSUE THREAD

**Issue by EinradStevo** [FTBTeam/FTB-Modpack-Issues#2211]
### Modpack

Stoneblock 3

### Modpack version

1.18.2

### Describe the bug

The wither skeleton spawner in the nether dungeon ring aren´t spawning any wither skeletons.
idk if that has to do something with my settings but eitherway i let them on default.

im on a server hosted by pebblehost

### Steps to reproduce

open a world and go in the nether fortress.
search for a wither skeleton spawner

### Expected behaviour

well the spawner should properly spawn whats inside

**Comment by Sunekaer** [comment]
They spawn naturally in the dungeons.
