### ISSUE TITLE
[Bug]: Trying to open the Create Mechanical Crafter recipe through the quest book crashes the entire game

### ISSUE THREAD

**Issue by Blacksmith-Sarec** [FTBTeam/FTB-Modpack-Issues#2212]
### Modpack

Stoneblock 3

### Modpack version

1.4.2

### Log Files

[crash-2022-12-01_12.00.12-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10127977/crash-2022-12-01_12.00.12-client.txt)

### Describe the bug

Trying to open the Create Mechanical Crafter recipe through the quest book crashes the entire game

### Steps to reproduce

1. Open World
2. Open Quest Book
3. Go to Create Questline
4. Click on Mechanical Crafter quest
5. Click on Mechanical Crafter item

### Expected behaviour

Game crashes entirely

**Comment by Raidobw2** [comment]
Seems to work now, in-dev 1.6.0
![image](https://user-images.githubusercontent.com/17010632/214766969-2ea2fbe7-5060-4c7b-8ba6-ae5ce4876d3b.png)
