### ISSUE TITLE
[Bug]: Rich Soil Farmland is unobtainable

### ISSUE THREAD

**Issue by Lordfirespeed** [FTBTeam/FTB-Modpack-Issues#2213]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

Rich soil farmland has the best growth speed modifier for botany pots, however it is unobtainable.

### Steps to reproduce

- place rich soil; till; silk touch -> does not drop farmland
- place rich soil into botany pot; till -> rich soil is not tilled in the pot

### Expected behaviour

Rich soil farmland is obtainable, for example through a shapeless recipe consisting of a hoe + rich soil.

**Comment by Sunekaer** [comment]
#2161
