### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Bloody-Tofu** [FTBTeam/FTB-Modpack-Issues#2215]
### Modpack

Stoneblock 3

### Modpack version

1.3.0

### Describe the bug

Framed compacting drawers not pulling correctly with a puller upgrade from Roosts. Frames 1x1 drawers work fine but the compacting, even with items that compact, won't pull from the roost with the upgrade.

 I am using Cut Asuring Bricks for the outside and black wool for the inside in case that matters.

### Steps to reproduce

Place a framed compacting drawer
Place a roost behind it
Insert production chicken of choice
Set Puller upgrade into framed compacting draw and right click for proper direction pull

### Expected behaviour

Items chickens produce being pulled into Compacting drawers

### Additional information

If you pipe from the roost to the framed compacting drawer it works fine but trying to keep this compact. So far it's worked fine with all the ingot types but not coal, glowstone, and others

**Comment by Sunekaer** [comment]
Did you put one item in the drawer? the drawer needs to have its item set before it auto pulls
