### ISSUE TITLE
[Bug]: All mobspawners does not spawn mobs

### ISSUE THREAD

**Issue by Frededb** [FTBTeam/FTB-Modpack-Issues#2216]
### Modpack

Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

All mobspawners (the normal Vanilla dungeon mob spawners), does not spawn mobs.

### Steps to reproduce

Find a mob spawner
Look

### Expected behaviour

They need to spawn mobs

### Screenshots

![2022-12-01_19 13 19](https://user-images.githubusercontent.com/47889596/205129112-9642c8a1-0629-46a9-848b-bdbaa61c1a97.png)

### Additional information

No im not in peacefull.
No i do not have a mega toutch around.
Yes i have tried other spawners, non work.

**Comment by Raidobw2** [comment]
Using `spawn_overrides` this will be fixed in the next version of SB3, for all spawners (not only drowned)
![image](https://user-images.githubusercontent.com/17010632/235522159-b7aecc72-c16c-486b-ae0b-aba031227a27.png)
