### ISSUE TITLE
[Bug]: VERY MINOR "w" to ponder is hard coded in a tip

### ISSUE THREAD

**Issue by AWDoBaun** [FTBTeam/FTB-Modpack-Issues#2217]
### Modpack

FTB Stoneblock 3

### Modpack version

1.4.2

### Describe the bug

A small edge case. the text in a tip is hard coded to a value that is not hard coded.

.../en_us.json: line 16:  "sb3.tips.5": "Hold your 'W' key when hovering over a Create item to open Ponder, 

The keybind for ponder is not hardcoded to 'w' it is directly tied to whatever key you have bound to the vanilla action of move forward.
![image](https://user-images.githubusercontent.com/12954977/205168921-feee6b3c-5ba2-4916-9165-8579ee404c45.png)

![image](https://user-images.githubusercontent.com/12954977/205169031-6a7b21fe-46c6-409d-b4c2-01e80cc8c537.png)

### Steps to reproduce

- [ESC]
- [Options...]
- [Controls...]
- [Keybinds...]
- Change value for "Walk Forwards"
- [Done][ESC][ESC]
- open REI, search for @Create, observe ponder has changed.

### Expected behaviour

Tips should not lie.

**Comment by Sunekaer** [comment]
We cant make the tips adjust to your keybinds.
Tips are made based on default settings

**Comment by AWDoBaun** [comment]
I added this due to watching a broadcaster who did not use standard keybinds struggle.
A replacement might be "Hold 'walk forward' key, default is [w], when hovering over a Create item to open Ponder".
