### ISSUE TITLE
[Suggestion]: Day/night cycle for literal-skyblock

### ISSUE THREAD

**Issue by jamuspsi** [FTBTeam/FTB-Modpack-Issues#2218]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Given that we have literal-skyblock, is there a reason that time is frozen at day, or is it just a holdover from another pack like odyssey?  I tried gamerules, I grepped for "time" and "day" everywhere I could find, but couldn't find any way to re-enable the day/night cycle or weather.

It would be awesome if we could get this enabled for building our artificial "fresh air" rooms.  Or even just a setting we could edit ourselves!

**Comment by TilBlechschmidt** [comment]
I second this, already dug through the KubeJS scripts trying to see if there is anything to easily fix this but did not find much (except for the fact that beds will blow up on you, which might become relevant if the day-night cycle is re-established — depending on how Phantoms work underground).

**Comment by Sunekaer** [comment]
Suggestion for https://github.com/nanite/Literal-Sky-Block
Also i dont think it would work in SB3 dims if it was a thing due to how our dims are made
