### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Thehotpepp** [FTBTeam/FTB-Modpack-Issues#2219]
### Modpack

Gtb stoneblock 3

### Modpack version

1.4.2

### Describe the bug

When putting down enchanting apparatus doesn’t locate pedistals although I am placing them in the right spot

### Steps to reproduce

Error made after placing pedestals and right clicking enchanting apparatus 

### Expected behaviour

Enchanting apparatus located pedistals to craft in ars mod

**Comment by Thehotpepp** [comment]
![Uploading 4A686A52-3366-4A65-8D50-3D9EB350FCC1.jpeg…]()

**Comment by Sunekaer** [comment]
Please reupload the picture, it seems to not have been completed
