### ISSUE TITLE
[Suggestion]: Add Quest for Create Charger

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Modpack-Issues#2221]
### Modpack

Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Matt wants a Quest to explain how to use the tesla coil as REI dosnt say to use a depo
https://clips.twitch.tv/SlickAlluringChowderBibleThump-n26SmhnT8h6fjrn4

**Comment by Sunekaer** [comment]
We not looking to add more quests
