### ISSUE TITLE
[Suggestion]: Quest Suggestions

### ISSUE THREAD

**Issue by NordicGamerFE** [FTBTeam/FTB-Modpack-Issues#2224]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Honestly i just wanted to say happy birthday to aaron but I don't want to clutter the github with useless issues, so I will also attach a suggestion 
![image](https://user-images.githubusercontent.com/18188155/205384506-ea5da367-b2f1-40ba-b546-bed33a8664d3.png)

Quests:
1: Ender Chest/Tank
2: Both pretty pipes and pipez are listed but not laserio, And xnet I think xnet should get some quests, I was new to xnet for this modpack and while its not that hard when you played this game for some time I could see new players struggling with it, And that would be a shame as xnet is really nice when it comes to speed and configurability
3: A lot could be said about how mekanism and rftools lacks in the quests department currently I would love to see a new quest line in the mekanism chapter for HDPE, and antimatter. Also quests about the different mekanism multiblocks wouldn't hurt like the fission reactor and sps. Rftools got many cool machines that can be made for instance blazing generator, and endergenic generator these are two power generating setups that in itself is not hard to make but the creation of one can be tricky as the the complex nature of how they operate more so the endergenic generator then the blazing generator. Also a quest about machine infusion wouldn't hurt.
4: Botania while I bunch could be added I don't think its needed botania in itself is simple where you can place down a endoflame and forget about it and reach endgame, But I think touching on sparks a bit more with it augments could be nice as it can change the game quite a bit.
5:  Blood Magic I suggest a placement change of the blood magic quests to reduce some of the line clutter 
![image](https://user-images.githubusercontent.com/18188155/205386935-c263072a-a8c7-4625-9d42-79a4efcb8a2a.png)

**Comment by Sunekaer** [comment]
We not looking to add more quests
