### ISSUE TITLE
REI

### ISSUE THREAD

**Issue by yjl0810** [FTBTeam/FTB-Modpack-Issues#2227]
### Modpack

FTB StoneBlock 3

### Modpack version

Release-1.1.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10146454/latest.log)

### Describe the bug

I always fail to enter the world that I created at last time.
Each time as soon as I press "E",just to open the bag,the game will stop,and stuck for a long time,then it crash.
When I am reading the logs,it mentions "REI" in "error" sentence many times.

### Steps to reproduce

I'm sorry that I can't describe it exactly.

### Expected behaviour

Just to play the game normally

### Launcher
The launcher I use is called "HMCL" (stands for"Hello Minecraft! Launcher") by Huanghongxun,and you can find this project on the Github.
### RAM
The total RAM of my computer is 8GB,and half of them is used by minecraft.
### Java
The Java version is JDK-17.0.3.1.

**Comment by Raidobw2** [comment]
I think REI fixed this way back, we forgot to close the issue. 
Ref: https://github.com/shedaniel/RoughlyEnoughItems/issues/1199
I've also updated REI in upcoming SB3 version 1.6.0, though that fix was most likely within the pack in 1.5.0 already.
