### ISSUE TITLE
Playing with friends, connection failed.

### ISSUE THREAD

**Issue by EnterFor** [FTBTeam/FTB-Modpack-Issues#2230]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Log Files

debug     https://pste.ch/itikeyidoh.md

### Describe the bug

I play with my friends, and when I enter his world, I disconnect.
My friend is all right.
We played for a week, and it kept coming up today.

### Steps to reproduce

1. Get into the game
2. Connect to my friend
3. Do things normally
4. The connection fails

### Expected behaviour

Play normally

### Screenshots

![image](https://user-images.githubusercontent.com/10114685/205456088-7976f23f-c8bf-488e-9972-372b73240eda.png)

**Comment by EnterFor** [comment]
The problem is getting serious...
I can't get into my friends' games at all.
But single-player games are perfectly fine.
I used a friend's save and got into the single player game with no problem.

**Comment by DinnerBeef** [comment]
Unable to reproduce this is my dev version. When the next version comes out, can you please test this to see if this is still happening.
