### ISSUE TITLE
You can eat sourceberries when your hunger is full

### ISSUE THREAD

**Issue by BreadBod** [FTBTeam/FTB-Modpack-Issues#2234]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

eating sourceberries when my hunger bar is full would just keep adding on more and more saturation until it maxes out

### Steps to reproduce

1.get a lot of source berries 
2.Eat a stack of sourceberries you don't even need to wait for hunger to go down

### Expected behaviour

Your saturation would keep going up

### Screenshots

![2022-12-03_20 15 59](https://user-images.githubusercontent.com/85652077/205469331-d42d0bad-259a-41e5-ae83-d31b872ce04f.png)

**Comment by tyler489** [comment]
That is an intended mod mechanic because they give mana regen.
