### ISSUE TITLE
Wither not dropping nether star on a 100% rate

### ISSUE THREAD

**Issue by Joao-Pedro-Bautista** [FTBTeam/FTB-Modpack-Issues#2235]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

When a Wither in spawned by a wither builder from industrial foregoing and killed by a mob crusher, the rate of the nether star dropping isnt 100%

### Steps to reproduce

spawn a wither with wither builder
let it be killed by mob crusher

### Expected behaviour

100% drop rate 

### Screenshots

https://youtu.be/kMHBNeKpDZk

**Comment by DinnerBeef** [comment]
It appears that your YouTube video is private, can you make that at least unlisted so that I can see if you are doing something different than I am. I am unable to reproduce this bug myself in my current dev version.
