### ISSUE TITLE
Red Matter Shears Impossible Recipe 

### ISSUE THREAD

**Issue by zigonick** [FTBTeam/FTB-Modpack-Issues#2236]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

Unable to create the red matter shears as it has dark matter shears lower left and red matter upper right and create will not route them. 

### Steps to reproduce

1. Place 3 Mechanical Crafters together. 
2. place dark matter shears lower left, 
3. Place red matter upper right
4. Power on
5. Attempt to rotate path way every direction
6. Nothing happens

### Expected behaviour

The ability to craft Red Matter shears

**Comment by Smurphicus** [comment]
I'm unable to reproduce this bug on version 1.4.2
The crafting recipe works fine for me.
[Video of it working.](https://imgur.com/uXQmKFy)
