### ISSUE TITLE
Can't load into the modpack

### ISSUE THREAD

**Issue by ProtocolLoaf** [FTBTeam/FTB-Modpack-Issues#2237]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

When I press play to go into the StoneBlock 3 modpack, it starts initialization then after some time it says that "looks like the instance has crashed during setup or while loading..." and then just doesn't work at all. Even if I switch the version I get the same message

### Steps to reproduce

1. Go to StoneBlock 3
2.  Press "play"
3.  Wait

### Expected behaviour

Game should start and load into the modpack

### Screenshots

![image](https://user-images.githubusercontent.com/119776986/205477131-6e0a8f52-48e8-430b-978e-98a15ff87b8c.png)

**Comment by Raidobw2** [comment]
There will be an update for Stoneblock 3 next week, version 1.6.0. Try installing this version instead if you want to try again, and if that doesn't work, reach me on the [FTB Discord](https://go.ftb.team/discord) instead (`@R3GEN`)
