### ISSUE TITLE
Can't enter the world 

### ISSUE THREAD

**Issue by StarskyXIII** [FTBTeam/FTB-Modpack-Issues#2238]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Log Files

https://mclo.gs/KKwfTX2

### Describe the bug

When I entering my world, it will get stuck in the infinite loading screen.
I already tried to remove `framedblocks-server.toml`.
When last time playing, I use the Framed Slope from FramedBlock.

### Steps to reproduce

1. Enter the Singleplayer world 
2. get stuck in the infinite loading screen

### Expected behaviour

I can join my world, and break some stones.

**Comment by Sunekaer** [comment]
log from after removing framedblocks-server.toml please :)
