### ISSUE TITLE
[Bug, MineTogether]: Disabling MineTogether breaks chat

### ISSUE THREAD

**Issue by NovaAstral** [FTBTeam/FTB-Modpack-Issues#224]
### Modpack

FTB OceanBlock

### Modpack version

1.5.0

### Describe the bug

If you disable minetogether (Either using the config button, or pressing "Don't ask me again" when the chat first comes up) You can no longer send messages into the server chat, or use commands.

(Minetogether chat also still shows up even if its disabled)

### Steps to reproduce

1: Go to singleplayer
2: Disable the Minetogether chat
3: Try to say something in chat or use a command
4: It doesn't work. You can't do anything chat related anymore.

### Expected behaviour

Chat shouldn't break like this, You should be able to use commands and say stuff even if you disable minetogether

**Comment by Sunekaer** [comment]
https://github.com/CreeperHost/MineTogether/issues/567

**Comment by Raidobw2** [comment]
Fixed in `minetogether-1.16.5-5.0.5-forge.jar`, available now
