### ISSUE TITLE
Kicked as soon as joining server

### ISSUE THREAD

**Issue by 4j0x** [FTBTeam/FTB-Modpack-Issues#2241]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Log Files

https://mcpaste.io/cea1f91e487f8e1b

### Describe the bug

When joining the server it would start to load me into the world but then would stop and give me a "timed out" message the server would then crash however changing max tick time to -1 fixed the crashing but still does not let me join the server

### Steps to reproduce

1. Try to join the server
2. timed out
3. server crashes

### Expected behaviour

able to load into world without being timed out

**Comment by Nightcaste** [comment]
I am also having this same problem.  Just commenting to follow what happens.

**Comment by manmaed** [comment]
are you able to get a spark report? with -1 on?

**Comment by 4j0x** [comment]
This issue can be fixed by killing all dropped items
(at least in my case)
