### ISSUE TITLE
Certain ores don't have further processing recipes.

### ISSUE THREAD

**Issue by crazyjerz** [FTBTeam/FTB-Modpack-Issues#2243]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

I have been building a Mekanism ore processing setup based on the Crushing Wheel output and there are some weird differences in how the raw materials can be processed.
Only 4 out of 6 materials (raw iron, tin, lead and osmium) can be processed in a Purification Chamber and further machines.
One (raw bauxite) can be processed in an Enrichment Chamber, and one (raw zinc) can only be smelted.
These differences are there without any obvious reasoning as to why they are implemented that way.
I made a datapack to enable basic (Enrichment Chamber) processing of zinc, but further changes require custom items and I don't have the skills to code them into the game, so I decided to report it here. I hope it can be resolved.

### Steps to reproduce

1. Place raw zinc or raw bauxite in a working Purification Chamber

### Expected behaviour

All six raw materials can be processed using Mekanism

**Comment by Sunekaer** [comment]
#1965
