### ISSUE TITLE
Crashing when craft from Quest book in AE

### ISSUE THREAD

**Issue by hapnesss** [FTBTeam/FTB-Modpack-Issues#2246]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Log Files

https://pastebin.com/JMQG3PVm

### Describe the bug
(edit because I investigate a little on the problem)
I can enter in the world, but I got some problems when I try to craft something (from quest book by clicking the little "+" only) with AE, items doesn't fill  the slots of the crafting table and when I click one of these slots, the game crash 

Moreover, all the craft I do (from quest book or no) disappear from my storage system
### Steps to reproduce

1. Enter the world
2. Trying to craft something from quest book in AE
3. Items doesn't fill the slots
4. Clicking one of these
5. Crash

### Expected behaviour

I expected I could craft my item

### Additional information

- I saw some peoples on the forum talking about framed slope, I used them last time I played (definitely not slope, I removed them and the problem is still here)
- I'm laggy, more than usually
- I can craft normally with REI with the "+" in AE, but they disappear from AE storage

**Comment by Raidobw2** [comment]
Appears to be fixed in 1.6.0 in-dev. I can craft from the FTB Quest book directly into the Applied Energistics Crafting Terminal with the "+" function.
There's also no more ghost slots/items, and no crashes from my tests. I'll assume this is fixed then!
