### ISSUE TITLE
Refine auto crafting got bug ingredients with avaritia mod. This happen only on Avaritia with RS

### ISSUE THREAD

**Issue by YuhGnad** [FTBTeam/FTB-Modpack-Issues#2247]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10162912/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10162913/latest.log)

### Describe the bug

I make RS pattern to craft endest pearl. The pattern I set up just 4 neutronium ingot and only 4 neutronium ingot to craft 1 endest pearl. When it all set, I gonna auto craft, RS add more ingredients on it.

### Steps to reproduce

I was setting up endest pearl which was crafted by create crafting (with item have EMC), then I make RS pattern with 4 neutronium ingot to craft 1 endest pearl and RS just add more ingredients on it. I have this issue before when I craft Neutron Collector (modpack ver 1.3.0)

### Expected behaviour

Didn't add more ingredients with avaritia mod

### Screenshots

![Screenshot 2022-12-06 125537](https://user-images.githubusercontent.com/117620860/205830221-3958d5bb-de06-42fd-a645-3a0c814cc986.png)
![Screenshot 2022-12-06 121455](https://user-images.githubusercontent.com/117620860/205830235-c9d605a9-8140-4c82-88c7-5affb00101c3.png)
![Screenshot 2022-12-06 121254](https://user-images.githubusercontent.com/117620860/205830244-f8e11bf3-7e33-482a-be47-aaaedbaffbd2.png)

**Comment by DinnerBeef** [comment]
Unable to reproduce this bug. Are you sure that you have everything on the back of the Mechanical crafters configured correctly so that 4 slots accept the Neutronium Ingots?
