### ISSUE TITLE
Jade should be set to show contents with normalShowAmount = 54 instead of 0

### ISSUE THREAD

**Issue by Xetaxheb** [FTBTeam/FTB-Modpack-Issues#2250]
### Modpack

FTB Stoneblock 3

### Is your suggestion related to a problem? Please describe.

Jade has a Lite mode instead of Toggle to hide details without shift. For some reason it's set to normalShowAmount = 0 but it should be set to normalShowAmount = 54 so the contents of chests and more importantly millstones and the like are shown in Toggle mode.

**Comment by Sunekaer** [comment]
This was done on propures and wont be changed, your welcome to change it on your instance :)
