### ISSUE TITLE
FTB One Pipez not working with Tesseract

### ISSUE THREAD

**Issue by davegilpin** [FTBTeam/FTB-Modpack-Issues#2253]
### Modpack

FTB One

### Modpack version

1.3.0

### Describe the bug

Connecting an Item Pipe (Pipez) through Tesseracts doesn't transport items.  My setup is a chest (tried both Gold and vanilla) in the Overworld, with one Item Pipe connected to the tesseract with one channel setup and activated.  In the Mining Dimension I have another vanilla chest connected to another tesseract on the same one active channel.  Nothing happens.  To verify the Overworld pipe was working, I connected another vanilla chest to the same pipe and it transferred items fine.  I also tried setting the Overworld Tesseract to Send Only and the Mining Dimension Tesseract to Receive Only.

### Steps to reproduce

1. In the Overworld, connect one end of an Item Pipe to a vanilla chest and the other to a Tesseract with one activated channel.
2. WIth the Pipe Wrench, change the end connected to the vanilla chest to output.
3. In the Mining Dimension, connect one end of an Item Pipe to a vanilla chest and the other to a Tesseract with the same one activated channel.

### Expected behaviour

Items should transfer to the chest in the Mining Dimension

### Screenshots

![Overworld1](https://user-images.githubusercontent.com/41874752/206051536-c8157a73-40eb-48de-accd-d39879ae6c71.png)
![Overworld2](https://user-images.githubusercontent.com/41874752/206051561-35706abc-647b-4a05-8e80-3cc7b24293f4.png)
![MiningDimension1](https://user-images.githubusercontent.com/41874752/206051755-17384569-907d-418c-8a38-92cb121ecfef.png)
![MiningDimension2](https://user-images.githubusercontent.com/41874752/206051766-b02771fb-5dd3-422f-8820-65d36c1ce1b7.png)

**Comment by Saereth** [comment]
yeah these just dont work, it's an issue on pipez's side and has been reported but nothing we can do about it from a pack dev standpoint. There are other pipes in the pack that will work however so I suggest you use those and we'll update pipez if and when it gets fixed
