### ISSUE TITLE
REI search bar doesn't work

### ISSUE THREAD

**Issue by LuciusV** [FTBTeam/FTB-Modpack-Issues#2254]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

No matter whatever item I search in REI search bar, it does not filter anything, showing all items at right panel.

### Steps to reproduce

1. Open inventory
2. Type any item name e.g. "hammer" in search box
3. REI panel doesn't filter items

### Expected behaviour

Expected filtering items

**Comment by Sunekaer** [comment]
Can you provide logs from this happening?
im not able to recreate this issue
