### ISSUE TITLE
Shift-Clicking a mystical agriculture augment destroys it in tkinkering table

### ISSUE THREAD

**Issue by LyfeOnEdge** [FTBTeam/FTB-Modpack-Issues#2257]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.18.2

### Describe the bug

Item destruction glitch

### Steps to reproduce

1. Open a Mystical agriculture tinkering table
2. Shift-Click an augment in (I was using wither resist)
3. Attempt to Shift-Click another augment in (I was using absorbtion)
4. The second augment disappears and never reappears even after reloading game.

### Expected behaviour

The augment shouldn't be destroyed

### Additional information

Video put in FTB discord under username Lyfe 12/7/2022
https://cdn.discordapp.com/attachments/983080030248796230/1050078434291875880/2022-12-07_07-56-23.mp4

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
