### ISSUE TITLE
Add a recipe for hellforged parts

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#2259]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Hellforged parts are used to upgrade blood runes to double their effect, however they are INCREADIBLY rare, even with luck potions, on average you can get around 8 for every 32 rooms. I feel that a custom recipe using create would allow for people to upgrade their alters.

**Comment by tyler489** [comment]
Maybe something like this for 8 gears https://gyazo.com/f1af95e8119f50aa741c8272c19b050b

This would mean
1. They have to explore the mines to get 4 gears originally
2. Use demon will to make the node router,
3. Adds a use for demonite, as you can get it in the mines
4. gives a use for lower tier slates, as tier 2 slates are needed for the node router.

**Comment by tyler489** [comment]
Apparently the bot can create labels if its not an exact match... Sorry.

**Comment by DinnerBeef** [comment]
Thank you for the suggestion. But we fell like the current way is fine
