### ISSUE TITLE
Functional Drawers buggy texture rendering

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#2260]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.0

### Log Files

N/A

### Describe the bug

Just a heads up that texture rendering for non-block items on Functional Storage's drawers is broken.

Reported upstream by others as Buuz135/FunctionalStorage#130 and Buuz135/FunctionalStorage#122.

### Steps to reproduce

N/A

### Expected behaviour

Textures render as expected

**Comment by koukimonster91** [comment]
i would like to add that there is "fix" for this by downgrading forge to 43.1.55
