### ISSUE TITLE
Mob "Hidebehind" has no AI

### ISSUE THREAD

**Issue by defen999** [FTBTeam/FTB-Modpack-Issues#2262]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.0

### Describe the bug

Mob "Hidebehind" has no AI. it will hit back if you hit it and your close enough but it will not walk or chase you or attack you. im fairly sure this wasnt intentional. also other people have suggest other mobs like the little ones have AI issues as well on FTB discord.

### Steps to reproduce

spawn a "Hidebehind" in a cave system and attack it in survival. you will see no AI.

### Expected behaviour

i expected the mob to attack and chase me like most other mobs. that or run away like passive mobs.

**Comment by Saereth** [comment]
This is a unique mob from the mod but working as intended, see this issue on their tracker
https://github.com/itsmeow/whisperwoods/issues/46
