### ISSUE TITLE
direwolf20 1.0.0 crashes on startup

### ISSUE THREAD

**Issue by rreilly-edr** [FTBTeam/FTB-Modpack-Issues#2264]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.0

### Log Files

Crash Log: [https://paste.c-net.org/RainesComet](https://paste.c-net.org/RainesComet)

Last Log [https://paste.c-net.org/BroadsCrews](https://paste.c-net.org/BroadsCrews)

### Describe the bug

Crashes on start

### Steps to reproduce

Start Modpack
it crashes on start

### Expected behaviour

mod pack should start

### Screenshots

None

### Additional information

None

**Comment by rreilly-edr** [comment]
Strange, I noticed is had just under 8G assigned, I adjusted that to 8192MB and the pack starts.

**Comment by DizzyDJW** [comment]
Same issue. The game refuses to start on less than 8192GB. It will crash and blame a different mod each time, with a "Ticking entity" error

**Comment by Saereth** [comment]
This isnt a ram issue, but I could understand why it would have seemed as such when you increased it. This appears to be a bug in thermal itself that only happens occasionally, regardless of the ram assigned. I've opened  a bug report with them regarding it

**Comment by DizzyDJW** [comment]
I've crashed on startup 3 times now. Can this please be resolved soon?!?!

**Comment by manmaed** [comment]
Is this still happing on 1.0.4?

**Comment by manmaed** [comment]
you could try this: https://cdn.discordapp.com/attachments/434101214548852746/1050833062277160990/cofh_core-1.19.2-10.0.2.1.jar
