### ISSUE TITLE
Scale of Title Screen Not Responsive

### ISSUE THREAD

**Issue by savosdarkran** [FTBTeam/FTB-Modpack-Issues#2265]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.0

### Describe the bug

Not a huge deal as far as bugs go.

If I modify the GUI scale under Options -> Video Settings and use a scale higher than 4 the images for single player, etc overlap each other and do not scale.

### Steps to reproduce

1. Launch Pack
2. Click Options
3. Click Video Settings
4. Click Gui Scale to change from 4 to 5
5. Done
6. Done
7. View the title screen

### Expected behaviour

Images scale with gui scale and/or do not overlap.

### Screenshots

Scale 4

<img width="1914" alt="Screenshot_Scale_4" src="https://user-images.githubusercontent.com/26523998/206563989-a9af8df2-b451-46e0-a64d-ed4cf2a22649.png">

Scale 5

<img width="1914" alt="Screenshot_Scale_5" src="https://user-images.githubusercontent.com/26523998/206564010-d3498b32-aeba-4b48-ab69-624a053169bd.png">

**Comment by manmaed** [comment]
Fixed in 1.1.0
