### ISSUE TITLE
Sudden Crash On Start Up

### ISSUE THREAD

**Issue by DeepFriedAndDead** [FTBTeam/FTB-Modpack-Issues#2266]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0 and 1.4.2

### Log Files

[crash-2022-12-09_09.01.43-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10189803/crash-2022-12-09_09.01.43-client.txt)

### Describe the bug

Click "Play" through FTB app
Instance begins to load and opens
"Mojang" screen appears with loading bar
As soon as loading bar completes instance crashes
Was loading and playing fine less then 12 hours ago

### Steps to reproduce

1.Launch game
2.Waiting for data loading
3.Crashes

### Expected behaviour

1.Launch game 
2.Main menu loads
3.Open world

**Comment by Carlncameron** [comment]
I am having the same problem, I've tried re-installing the modpack and trying different versions and all of them just crash as soon as the mojang bar is full.
![image](https://user-images.githubusercontent.com/79234934/206581299-ddd07931-091e-4720-baea-a5143bc22715.png)
[crash-2022-12-09_11.30.25-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10190256/crash-2022-12-09_11.30.25-client.txt)

**Comment by AesirSolace** [comment]
I've got a few friends with the exact same issue

**Comment by KieranP** [comment]
Same issue here. Was loading fine just 14 hours ago

**Comment by Carlncameron** [comment]
> Same issue here. Was loading fine just 14 hours ago

Yeah it was working for me 9 hours ago then our server crashed and the 3 of our people all crashed and are having the problem

**Comment by Carlncameron** [comment]
The cause of the crash is Better Than Llamas, Deleting the modpack seems to fix it and i'm able to play.

**Comment by andrewjbennett** [comment]
As Carlncameron said, this bug is from "BetterThanLlamas", which has an "Easter Egg Day" on the 1st of April and 9th of December (with a bug that prevents the game from loading). You can work around it by changing your computer's date, waiting until tomorrow to play, or just removing the mod entirely. 

https://github.com/iChun/BetterThanLlamas/issues/3

**Comment by manmaed** [comment]
#2263

**Comment by manmaed** [comment]
#2269
