### ISSUE TITLE
MEGA Cells (1.19)

### ISSUE THREAD

**Issue by 62832** [FTBTeam/FTB-Modpack-Issues#2267]
### Modpack

FTB Presents Direwolf20 1.19

### Is your suggestion related to a problem? Please describe.

*Disclaimer: I am the developer of the mod/add-on in question.*

As requested by Saereth over on the FTB Discord, I am resubmitting an issue previously made for the 1.18 DW20 pack for reconsideration over on 1.19.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/mega-cells

MEGA Cells is an Applied Energistics 2 add-on that I have been maintaining for a few months now since 1.18 which adds higher-tiered storage cells and crafting storage, alongside some specialised bits of equipment such as the Bulk Item Storage Cell offering infinite storage for a single item type and the Greater Energy Card for increased energy capacity over AE2's own energy card. It also adds integration with Applied Mekanistics for higher-tier chemical cells, including another specialised cell for radioactive chemicals excluding spent nuclear waste.

I would hope by now that these make for some decent accompaniments to AE Additions and generally provide greater choice for players depending on aesthetic preference and playstyle for AE2.

**Comment by Saereth** [comment]
I've reviewed the mod, and it looks like a good addition. There is some overlap with Ae Additions and ae additions provides additional features we wouldn't want to lose, so I've instead left AE additions but deferred to MEGA for all cells over 1024 in size so they both work well now within the AE ecosystem and of course with mekanistics within the pack. Expect it in update 1.0.2
