### ISSUE TITLE
[Suggestion]: Mod Suggestion: Easy Villagers to OceanBlock 

### ISSUE THREAD

**Issue by sarim** [FTBTeam/FTB-Modpack-Issues#227]
### Modpack

FTB OceanBlock

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/easy-villagers

This basically has some single block machines for all villager related tasks. Trading, Breeding, Growing, Zombie conversion etc... 
It has ability to just convert villagers to item, then insert villager item to those machines to correcting tasks. Eliminates the hassle of handling and storing villagers. Easier to automate, eliminates lag as there are no living entities with AI roaming around.

**Comment by Sunekaer** [comment]
Thanks for the suggestion, but we wont be adding this mod in this pack, but will keep it in mind for the future
