### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by RedSpec28** [FTBTeam/FTB-Modpack-Issues#2271]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0

### Log Files

[crash-2022-12-09_02.27.37-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10192739/crash-2022-12-09_02.27.37-client.txt)

### Describe the bug

Crashes on startup

### Steps to reproduce

click play on the pak then crashes after a few

### Expected behaviour

load the pack

**Comment by NordicGamerFE** [comment]
Duplicate of #2269
