### ISSUE TITLE
Stoneblock 3 Crashing on start

### ISSUE THREAD

**Issue by rebirthflame1** [FTBTeam/FTB-Modpack-Issues#2277]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Log Files

[crash-2022-12-09_10.21.50-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10193934/crash-2022-12-09_10.21.50-client.txt)
[crash-2022-12-09_10.14.20-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10193935/crash-2022-12-09_10.14.20-client.txt)
[crash-2022-12-09_10.08.59-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10193936/crash-2022-12-09_10.08.59-client.txt)

### Describe the bug

Would press play, load up to the Mojang screen, but the mod will crash due to BetterThanLlamas. Attached three crash reports

### Steps to reproduce

Press play, Issue seems to happen nearer the end of loading

### Expected behaviour

To load the game

**Comment by TimLiz** [comment]
You should change ur computer date for launch

**Comment by rebirthflame1** [comment]
Hi there, TimLiz, I apologize but I don't understand what it is you mean.

**Comment by NordicGamerFE** [comment]
Hey there @rebirthflame1 try removing Better Than Llamas from your mods folder and boot the game.

**Comment by rebirthflame1** [comment]
Thank you for the help there @NordicGamerFE. Shall do, I really appreciate the help!

**Comment by NordicGamerFE** [comment]
Duplicate of #2269

**Comment by rebirthflame1** [comment]
100% deleting BetterThan was the answer, Thank you @NordicGamerFE

**Comment by NordicGamerFE** [comment]
> 100% deleting BetterThan was the answer, Thank you @NordicGamerFE

No problem, Enjoy your time playing.
