### ISSUE TITLE
The world doesn't open

### ISSUE THREAD

**Issue by giovmer** [FTBTeam/FTB-Modpack-Issues#2279]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.16.1

### Log Files

[crash-2022-12-09_17.00.03-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10196280/crash-2022-12-09_17.00.03-server.txt)

### Describe the bug

it doesn't let me open the world

### Steps to reproduce

.

### Expected behaviour

.

### Screenshots

![Screenshot (38)](https://user-images.githubusercontent.com/99511162/206743431-53215182-53b3-40a7-bd2b-85e0cbdfc5df.png)

**Comment by tyler489** [comment]
Going to need that crash file,upload it to a gist and post the link here.

**Comment by Gaz492** [comment]
A little late replying to this, but if you or anyone else runs into this issue, either restoring a world backup or going to the config folder and setting `removeErroringTileEntities` to `true` should fix the issue.
The latter option may require you to load the world up multiple times to completely resolve the issue.
