### ISSUE TITLE
[Bug]: Steel making recipe missing for Thermal and Tinkers

### ISSUE THREAD

**Issue by sarim** [FTBTeam/FTB-Modpack-Issues#228]
### Modpack

FTB OceanBlock

### Modpack version

1.5.0

### Describe the bug

There are various ways to make other allows like bronze, invar etc.. Ex: Thermal Induction Smelter and Tinkers Alloying (molten). But no recipe for steel. There should be iron + coal = steel recipe for Thermal Induction Smelter and Tinkers Alloying (molten).

### Steps to reproduce

1. Open JEI.
2. Look up recipe for Steel ingot and Molten Steel

### Expected behaviour

Iron + Coal = Steel recipe for Thermal Induction Smelter nd Tinkers Alloying (molten).

**Comment by Raidobw2** [comment]
To dev: You'll have to check if that's your intended steel progression. Currently there's only 2 ways "early" game to get steel. IE Blast furnace by blasting iron directly into steel, or Mekanism Metallurgic Infuser (osmium available from the get-go). The infuser cycles iron twice with carbon (coal) until it's steel grit. After that you have to smelt the grit to get the ingot.
There's steel seeds + arc furnace after that.
Optimally you could add this as unification, up to you.

**Comment by Sunekaer** [comment]
Theres no molten coal from what i could see so no tinkers recipe, but ill add Smelter recipe
