### ISSUE TITLE
Any Chicken item bug

### ISSUE THREAD

**Issue by DeltaMage777** [FTBTeam/FTB-Modpack-Issues#2280]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

I believe I've found a bug with the Chickens mod. I accidentally shift clicked 2 silver chickens and 1 blaze chicken into an obsidian furnace and when I went to get them out, one of my silver chickens had become an "any chicken" item.

### Steps to reproduce

1 Shift click a stack of chickens into a furnace from Iron Furnace that has auto sort on
2 Before the chickens are smelted shift click them back out

### Expected behaviour

I expected to get the same chickens back

### Additional information

I haven't been able to reproduce it, my best guess is that the furnace's auto sort had something to do with it

**Comment by UnRealDinnerbone** [comment]
This issue has been reported to the mod author. If the mod gets updated to fix the issue, it will get updated
