### ISSUE TITLE
audio problems

### ISSUE THREAD

**Issue by CinnamonShaey** [FTBTeam/FTB-Modpack-Issues#2281]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.0

### Describe the bug

some sounds do not play at all, i have nothing muffeled and all sounds are up in the sound options, and yet only some sounds are playing mainly the mekanism machines

### Steps to reproduce

well for me its just whenever i start the pack

### Expected behaviour

make sounhd

**Comment by Saereth** [comment]
make sure you're on the latest version of the pack and see if it still occurs, if so please send your debug log and any other info we might be able to use to duplicate the issue on our end

**Comment by CinnamonShaey** [comment]
still dont know why it occured, but a simple reinstall of the pack did fix it, dont know if it will come back, guess we will see

**Comment by Tirak-Graeyson** [comment]
you could always try toggling directional sound when it bugs as a temporary fix, and back again once it bugs. its a work around but not fun long term.

https://gyazo.com/11f21eccbe2bb704725346daedcd3888  how to turn it on/off
