### ISSUE TITLE
Direwolf 1.18.2 1.10.2 Wont Start

### ISSUE THREAD

**Issue by DocCodeSharp** [FTBTeam/FTB-Modpack-Issues#2282]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.10.2

### Log Files

https://pastebin.com/8iY4JQqc

### Describe the bug

When trying to start the server with the Linux download file for Direwolf 1.18.2 1.10.2 it does not work. The install put all the files in the location wanted, but the moment that start.sh is ran it fails to start Minecraft due to 3 mods that will not load.

### Steps to reproduce

Install the server install file from the website download.
run the start.sh script to start the server.

### Expected behaviour

The server would start with no issues.

**Comment by Saereth** [comment]
Fixed in 1.0.3, should be available for download soon

**Comment by DocCodeSharp** [comment]
Now i am getting a new issue the install fails

Downloading minecraft server failed, invalid checksum.
Try again, or manually place server jar to skip download.
There was an error during installation
2022/12/09 23:05:24 Running forge installer failed with exit status 1. You may wish to install forge 40.1.84 for Minecraft 1.18.2 manually

**Comment by DocCodeSharp** [comment]
I have discovered my issue the following was not installed on the box

apt-get -y install libxrender1 libxtst6 libxi6
