### ISSUE TITLE
Iron dust recipe issues

### ISSUE THREAD

**Issue by c44448** [FTBTeam/FTB-Modpack-Issues#2286]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.1

### Describe the bug

Iron dust from Mekanism and Iron dust from Thermal series aren't the same in recipes you can't use the thermal series once for Invar blend.

### Steps to reproduce

try to craft invar blend you can only use the iron dust from Mekanism. But you get the Thermal series dust from using the pulverizer.

### Expected behaviour

Both iron dusts should work

**Comment by Saereth** [comment]
This should be fixed in 1.0.3, if you see any more issues like that, especially related to thermal unifications please reopen or open a new issue I'll get them sorted asap

**Comment by SteseDav** [comment]
This issue still appears in Vers. 1.0.4.
