### ISSUE TITLE
World creation problem/ problem opening 1.0.1 worlds in the new version

### ISSUE THREAD

**Issue by c44448** [FTBTeam/FTB-Modpack-Issues#2287]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.2

### Describe the bug

If you try to create a new world the error: "Data pack validation failed" shows up. You can create a new world if you click on Reset to Default. (first screenshot)
If you try to open a 1.0.1 world you get an error (screenshot 2) Save mode doesn't work
Last screenshot is from the recource Pack option.

### Steps to reproduce

try to open a world
or generate a new one

### Expected behaviour

if possible it would be nice if the old worlds would still work/ no error when generating a new world

### Screenshots

![image](https://user-images.githubusercontent.com/113215353/206811865-ad9ed8cd-9e65-4f58-ad89-7f17c8da56e3.png)
![image](https://user-images.githubusercontent.com/113215353/206812215-f87c75c3-84a0-4fc0-ba40-678a0195e927.png)
![image](https://user-images.githubusercontent.com/113215353/206812363-237b7251-371a-4bb6-a0e7-a67e5f85c6bb.png)

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2282
