### ISSUE TITLE
thermal unifications issue

### ISSUE THREAD

**Issue by c44448** [FTBTeam/FTB-Modpack-Issues#2288]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.01

### Describe the bug

If you try to make electrum in the induction smelter you can only use mekanism gold not the thermal one.
If you make electrum blend(thermal series) it has no recipe, you can use the Immersive Electrum grid but it also only uses the mekanism gold.

### Steps to reproduce

see above

### Expected behaviour

should work

**Comment by c44448** [comment]
Im not shure if this helps because i can only use 1.0.1 instead of 1.0.2. If its helpfull i can search for more problems and just reopen this one if i find more.

**Comment by manmaed** [comment]
can you confirm if this is still an issue in 1.0.4?

**Comment by SineW4V3** [comment]
Unsure if this still does not work in 1.0.4, however making invar in 1.0.4 is not possible with the iron dust from thermal, so I'd assume the same is true for 1.0.2

**Comment by ukmcplyr** [comment]
Yep, copper, iron, gold and diamond dust from the Thermal pulveriser (minimally) all default to `therml:blah_dust`.

**Comment by c44448** [comment]
its still a problem in 1.0.4

**Comment by c44448** [comment]
Short answer all the 8 blends require Mekanism dusts and wont work with Thermal dusts

**Comment by c44448** [comment]
same is true for the two Grits from immersive

**Comment by robertm1771** [comment]
> can you confirm if this is still an issue in 1.0.4?

Minecraft gold and Occultism silver make IE electrium in Thermals Induction smelter from ingots atm in 1.0.4

**Comment by c44448** [comment]
> 

hat is right but we where talking about the dusts in various other recipes.

**Comment by Saereth** [comment]
These should all be fixed for next update. I plan on releasing 1.0.5 Monday.
