### ISSUE TITLE
Enderdragon is completely bugged! and unplayable

### ISSUE THREAD

**Issue by CinnamonShaey** [FTBTeam/FTB-Modpack-Issues#2289]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.0

### Describe the bug

the dragon does not render in, even with max render and sim distance and entity distance i have to fly up in spectator about 2 chucks away from it then it "loads" in, i can always hear the wing flaps, but as soon as it goes slightly out of those 2 chunks it just pauses and disappears from view until you get close enough again then it resumes on its path it is on a server, but the server has sim distance and render distance up to 16 too as our clients have so dont think thats it either

### Steps to reproduce

1. server on 1.0.0
2. go to the end
3. see dragon is bugged
4. be sad

### Expected behaviour

dragon should be "normal" or not bugged, atleast should fly around like normal 

### Additional information

First time i have encountered this, after countless modpacks where i have been server host

**Comment by manmaed** [comment]
is this still an issue in 1.0.4?

**Comment by CinnamonShaey** [comment]
if you need any  other information i will try my best to give it

**Comment by CinnamonShaey** [comment]
have found out its not only the enderdragon but it seems it happens to my friend too if i gets too far away from him he dissapears, same thing that happens with like chests and stuff when you get away from them, but its most noticeable on the enderdragon cause of the bigger arena so might not be strictly the enderdragon, but entities as a whole??

**Comment by CinnamonShaey** [comment]
![image](https://user-images.githubusercontent.com/80605917/206876857-45e9b0d6-ea88-4cf9-b443-80f2831286dc.png)
![image](https://user-images.githubusercontent.com/80605917/206876867-e97df914-24df-4745-a48f-937a50fb664b.png)
you can see on these 2 pictures only a few blocks difference, and many things disappear from view like my friend, the reactor and some other small stuff, thats exactly the same that happens with the enderdragon, about the same distance away

**Comment by Saereth** [comment]
ok thanks for the info, I have an idea what it might be now at least, will do some testing

**Comment by Saereth** [comment]
Appears to be a conflict with far sight and rubidium, should have a fix for it today

**Comment by HPeti** [comment]
When are you planning to release this patch approximately? I've tried removing the farsight mod or modifying its config, but it did not fixed the issue for me. Also tried removing rubidium but it's the same. (tested on 1.0.4)

Can you describe the steps you did to fix this issue or should i wait for the release?
