### ISSUE TITLE
[Suggestion]: Tag recycle-able item for easier filtering when using Item Recycler

### ISSUE THREAD

**Issue by sarim** [FTBTeam/FTB-Modpack-Issues#229]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

https://www.curseforge.com/minecraft/mc-mods/item-recycler
> This mod does not have any default recipes, it's up to modpack author to add them! Please do not report missing recipes as an issue

I'm putting this here bcz of that ^ and as recipes are added by oceanblock via kubejs script. In gameplay It would be easy to automatically filter by tag so that only recyclable items go to Item Recycler. So maybe add a forge tag like **recyclable** to all items added in the script?

**Comment by Sunekaer** [comment]
Sure we can add a tag "ftbob:recyclable"
