### ISSUE TITLE
DW20 1.19 1.0.3 Errors in currently selected datapacks prevented the world from loading.

### ISSUE THREAD

**Issue by matthew-nichols** [FTBTeam/FTB-Modpack-Issues#2290]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.3

### Log Files

https://paste.atlauncher.com/view/8a9a16da-a9a5-43fa-bc54-aecfc85547b7

### Describe the bug

![image](https://user-images.githubusercontent.com/4212148/206819682-5df63072-aa5c-4745-a2fe-85cc816ef15a.png)

World loads in 1.0.1, refuses to load in 1.0.3. (Can revert to 1.0.1 and world loads.)

No extra mods added.

### Steps to reproduce

Play in 1.0.0 and/or 1.0.1.

Upgrade to 1.0.3.

### Expected behaviour

World loads

**Comment by tyler489** [comment]
Try updating to 1.0.4 as it states fixes an issue with features, This usually happens if a dimention mod is removed.

**Comment by matthew-nichols** [comment]
1.0.4 fixes the issue.
