### ISSUE TITLE
Ore processing steps missing for Thermal and Mekanism

### ISSUE THREAD

**Issue by SineW4V3** [FTBTeam/FTB-Modpack-Issues#2291]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

- Raw bauxite, raw zinc, all uranium, all osmium including nether, all silent gear ores, and all ad astra ores cannot be processed by a pulverizer
- All clumps/shards/crystals/dirty dusts/slurries provided by JAOPCA do not have any recipes attatched to them, making ore processing impossible for the following through mekanism:
1. Zinc + Nether Zinc
2. Silver
3. Aluminum
4. Nickel
5. All Silent Gear ores
6. All Ad Astra ores

- Yellorium has no items included by JAOPCA, and thus cannot be processed through mekanism

### Steps to reproduce

1. Try to put the ores mentioned through ore processing
8. Machines do not accept item(s)

### Expected behaviour

Ore processing for all ores mentioned

**Comment by MCDemon117** [comment]
It's not just the Raw Ores or something but also some dusts, I noticed it with Nickel Dust from Thermal Series, can not be smelt, it came out as a bonus from the Pulverizer.
