### ISSUE TITLE
Gobber Ores don't Work with Silent gear

### ISSUE THREAD

**Issue by Mini-kun** [FTBTeam/FTB-Modpack-Issues#2293]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Log Files

None

### Describe the bug

Gobber 2 Mod nether Ores can not be mine with Silent Gear

### Steps to reproduce

1. get to the nether and find the ore
2. mine it
3. Nothing drop
4.

### Expected behaviour

to drop the loot Table from the block

### Screenshots

https://snipboard.io/vELgwm.jpg <- Tool
https://snipboard.io/1RXVmk.jpg <- Block

**Comment by tyler489** [comment]
It appears your pick is not a high enough level to mine that, what is it made out of.

**Comment by Saereth** [comment]
tyler is correct here, I tested it as well and a higher tier pick was able to mine them
