### ISSUE TITLE
MineColonies capsules can't be placed 

### ISSUE THREAD

**Issue by mschsmith** [FTBTeam/FTB-Modpack-Issues#2296]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

When trying to place the town hall capsule a message pops up saying that there are blocks in the way. This happens both when trying to place the blocks at the level of the first layer of bedrock, or when trying to place a block above the first layer in order to place the capsule one layer above it. I've considered also digging out a 23x23x1 area in the ground and trying to place it there, but when I tried a similar solution placing a 23x23x1 platform one block above the bedrock layer and trying to place  it on top of that I got the same error, and I don't really want to do that whole process just for it to not work. 

### Steps to reproduce

1. Start a new world
2. Try to place the town hall capsule 

### Expected behaviour

The townhall capsule will be properly placed in the expected location

### Additional information

I placed down the mine colonies block using the build tool before doing this and then broke it, just because I wanted to get a sense of where I should place the capsule, (I have more experience with the mine colonies build tool than the capsules, and thought that I would be less likely to mess up the positioning using that first), so maybe that might have played a part in it?

**Comment by orbidlo** [comment]
The capsule can usually replace any netherrack, blackstone or bedrock. But not any cobbled blackstone or deepslate, faux bedrock etc. If it says certain block is preventing putting it down, find the block and remove it. Only use netherrack if you need to place the capsule at certain y-level.
Also in my experience sometimes the dead bushes were in the way and I have to veinmine them away before placing capsule. 
Hope it helps you.

**Comment by mschsmith** [comment]
So I tried both taking out any cobbled blackstone, and then creating a 23x23x1 layer of netherrack and trying to place the capsule on top of it and neither of those worked. I might try doing the netherrack thing later and just doing it inside the bedrock layer, but I think I'll wait a bit before doing that. Thank you so much for your help, I suspect that the netherrack trick will be the way I end up getting it to work!

**Comment by orbidlo** [comment]
Just FYI, the netherrack needs to be only in the middle of capsule where you click to throw it, not everywhere. If it didn't work, just make sure to go to chat and find any blocks mentioned there as preventing placement. Some buildings also have "underground" part of sorts and needs more than one layer checked.

**Comment by Saereth** [comment]
this is not really a pack issue so much as jsut a general usability issue with capsules, it takes some getting used to but if you can think of some way to improve it please head on over to the capsule github and make some suggestions so he can improve the mod. Not much I can do to improve it from a pack standpoint. 

https://github.com/Lythom/capsule/issues
