### ISSUE TITLE
1.0.4 Data Pack Validation Failed // Errors in currently selected datapacks prevented the world from loading. (Different from bug #2290)

### ISSUE THREAD

**Issue by Flabort** [FTBTeam/FTB-Modpack-Issues#2301]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Log Files

https://pastebin.com/ucW966f4

### Describe the bug

When you try to create a world, the pack says that the data packs validation failed, and gives you the option to try and fix it or reset to default data packs. The pack refuses to create worlds unless you select to reset to default data packs. If you do get the world created, you can play on it for a while, but if you save and quit, then try to reload, it gives you the error that errors in the selected data packs prevent the world from loading. It gives the option to load in a safe mode, but it doesn't work. The game with freeze up for a moment, and then do nothing when it unfreezes.

When creating the world, the reason it says data pack validation failed is that most of the data packs were created for an older version of minecraft.

### Steps to reproduce

A1. On GDLauncher, add new instance from FTB library
A2. Select FTB Presents Direwolf20 1.19, and select Explore/Versions
A3. Select version 1.0.4 (Labeled as [Beta])
A4. Click Download
A5. When GDLauncher finishes downloading, including its workaround for the mods that opt out of outside launchers, run the pack.
A6. Create a world.
A7. Click "Reset to default data packs"

B1. Close game after making a world.
B2. Reopen the game.
B3. Try  loading your world.

### Expected behaviour

I expect the game to load  my save file.

### Screenshots

https://imgur.com/a/KcE9Kcc

**Comment by EgFriedRice** [comment]
Hey, I have the same problem, but it's for the mod pack that I made on Curse Forge and I was wondering how to fix it.
