### ISSUE TITLE
Mother Silverfish continue to spawn silverfish with the stasis chamber - Crash server

### ISSUE THREAD

**Issue by BasteFw** [FTBTeam/FTB-Modpack-Issues#2302]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Describe the bug

Hello,

I set up the farm at mother silverfish.
I start the ritual, she freezes with the Stasis Chamber
I specify that I do not attack it.
She spawns littles silverfishs all the time.
It makes my server lag and crash after a few hours.

### Steps to reproduce

1- Summon the Mother Silverfish
2 -  Using Stasis chamber to freeze her
3 -  The mother Silverfish spawn all the time little silverfish ( around 400 after 1 hours).

### Expected behaviour

the silverfish mother stop spawning when it freeze.

**Comment by Sunekaer** [comment]
This is correct as they are not spawned naturally, we are adding a way to kill them next update
