### ISSUE TITLE
:-[Suggestion]-: Add AntiBlocksReChiseled

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Modpack-Issues#2304]
### Modpack

FTB Presents Direwolf20 1.19
FTB Stoneblock 3 - Denied 

### Is your suggestion related to a problem? Please describe.

Who doesn't want sexy glowy full bright blocks?

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/antiblocksrechiseled

**Comment by tyler489** [comment]
Did you suggest your own mod 🤣 I knew that name sounded familiar.. Seriously though can we also get this in stoneblock 3?

**Comment by manmaed** [comment]
Sune Said no for stoneblock 3

**Comment by manmaed** [comment]
added in 1.1.0
