### ISSUE TITLE
Apotheosis tables not craftable and random sticks

### ISSUE THREAD

**Issue by DillePickle** [FTBTeam/FTB-Modpack-Issues#2305]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

Apotheosis's tables for salvaging and reforging as well as every material above uncommon are unsearachable and uncraftable in jei and only show as missing textures when searching @apotheosis. Random sticks also drop that have apotheosis modifiers.

### Steps to reproduce

1: Type in any of the items mentioned
2: Nothing in jei shows these items
3: Type in @apotheosis
4: The items show up as missing textures at the bottom
5: Vein mine a tree's leaves to receive apotheosis sticks.

### Expected behaviour

These items should have textures and be craftable, as the apotheosis drops are useless otherwise, and the sticks should all be normal sticks

### Screenshots

<img width="1440" alt="Screenshot 2022-12-11 at 8 42 51 AM" src="https://user-images.githubusercontent.com/100093268/206910381-0ea4dc90-6573-4e34-9b44-47fba6765254.png">
<img width="1440" alt="Screenshot 2022-12-11 at 8 43 08 AM" src="https://user-images.githubusercontent.com/100093268/206910396-c6525343-c8f8-45f7-8078-01b71c682f8d.png">

**Comment by orbidlo** [comment]
wow sticks with affixes were removed LONG time ago. Does this happen on a fresh install (if singleplayer)?  Seems like borked  installation with overwritten defaultconfigs. If singleplayer, do fresh install and world and if everything works well, you can load your old world. 
If on server - First consider restarting server first. Then back up your server folder, installing fresh (1.2.1 is way better than the bugged 1.3.0 btw) and from the backup, copy only folders that are NOT already present (world, etc). You definitely do not want to overwritte e.g. new defaultconfigs folder by any old content.

**Comment by DillePickle** [comment]
Yeah I updated my game from an older version to 1.3 and that seemed to not update the configs, so I made a fresh install and ported the world which fixed all the issues, thanks!
