### ISSUE TITLE
Stuck in the end

### ISSUE THREAD

**Issue by Charismara** [FTBTeam/FTB-Modpack-Issues#2306]
### Modpack

FTB Inferno

### Modpack version

1.2.1

### Describe the bug

Jumping into the end portal (in the end) results into getting stuck between both dimentions.

### Steps to reproduce

1. Go to the end
2. kill the ender dragon
3. jump into the end portal
4. get teleported into the overworld
5. get instandly teleported back into the end
6. get teleported into the overworld due to the end portal you're in
7. well... now you're stuck like me

### Expected behaviour

Well... getting back to the nether?

### Additional information

I'm playing on a Server.

Teleporting using the `execute` or `tp` command doesn't work

**Comment by Saereth** [comment]
Im having some issue reproducing this, when I do it, it sends me back to the nether from overworld, not back to the end, could you zip and share your save with me if possible to get it from the server owner?

**Comment by Charismara** [comment]
Sadly i can't. I've deleted the world after a playthrough

I could "hack" me free using the NBTExplorer
