### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by legalizerke** [FTBTeam/FTB-Modpack-Issues#2307]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.19.2

### Describe the bug

@powah = no cables are available to craft 
@mekanism = not possible to autostock the metalurgic infusers with coal, redstone or diamonds (tried with laserio and refined storage)

### Steps to reproduce

dont have any experience with this not a it guy

### Expected behaviour

a fix would be nice

**Comment by Saereth** [comment]
powah cables are disabled becuase they are buggy, when they are fixed they'll be back in. I cant reproduce your issue with mekanism, works fine for me. Make sure you set the input sides correctly in the gui
