### ISSUE TITLE
Snad doesn't work

### ISSUE THREAD

**Issue by c44448** [FTBTeam/FTB-Modpack-Issues#2308]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

The snad block doesnt grow sugar cane or cactus faster

### Steps to reproduce

The block doesn't work

### Expected behaviour

Snad should accelerate growth

**Comment by manmaed** [comment]
Repoted to mods issue tracker [](https://github.com/lazyMods/snad/issues/14)](https://github.com/lazyMods/snad/issues/14)

**Comment by Saereth** [comment]
no response at all from the dev, just removing the mod for now
