### ISSUE TITLE
Occultism Crusher Spirits Refuse Ores

### ISSUE THREAD

**Issue by TheFroggyNinja** [FTBTeam/FTB-Modpack-Issues#2309]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

The Crusher Spirits from Occultism will not pick up ores (or other crushables) and immediately eject them if manually entered into their inventory.

### Steps to reproduce

1. Summon an Ore Crusher Foliot
2. Drop raw ores on the ground in front of it.
3. Shift right click to directly interact with its inventory and place ores in the slot.

### Expected behaviour

Ore Crushers should rush towards anything with a valid crushing recipe and then try to crush them.

### Additional information

They _will_ crush end stone, which is notable because end stone dust is the only dust that doesn't have an equivalent in Mekanism or another mod. I suspect that the issue is that, after the removal of the Occultism dusts to prevent clutter from duplicate item types, the recipe wasn't actually updated to produce Mekanism (or other mod) dust, so the Ore Crusher doesn't actually accept ores as a valid ingredient because its output has been removed with no replacement.

**Comment by jlindsey** [comment]
>  I suspect that the issue is that, after the removal of the Occultism dusts to prevent clutter from duplicate item types, the recipe wasn't actually updated to produce Mekanism (or other mod) dust

Almost certainly the case. If you edit `kubejs/startup_scripts/global.js` and remove the `occultism:*` entries from the `global["unUnified"]` array, the crushers will properly accept those ores again (producing the occultism flavored dusts).

**Comment by Amunsul** [comment]
> > I suspect that the issue is that, after the removal of the Occultism dusts to prevent clutter from duplicate item types, the recipe wasn't actually updated to produce Mekanism (or other mod) dust
> 
> Almost certainly the case. If you edit `kubejs/startup_scripts/global.js` and remove the `occultism:*` entries from the `global["unUnified"]` array, the crushers will properly accept those ores again (producing the occultism flavored dusts).

So this fix allows for the 3 vanilla raw ores to be crushed, but not modded ores unfortunately.  but as im just starting this DW20 1.19 pack thats still useful so i appreciate the info. Just sharing for anyone else who is curious.
