### ISSUE TITLE
[Bug, FTBChunks]: Force loaded chunks not unloading, even when offline chunkloading=false

### ISSUE THREAD

**Issue by legitswitch** [FTBTeam/FTB-Modpack-Issues#231]
### Modpack

FTB OceanBlock

### Modpack version

1.5

### Describe the bug

This happens on FTB Uni 1.16 as well.

Chunks marked as force loaded by players will not unload. This has been a consistent issue since the packs were released and I've had to unload players' chunks manually every so often. I think the issue is they fail to unload for some reason.

This is very bad as lag will pile up on a server as more and more people join and forceload chunks.

### Steps to reproduce

1. Go on a server that has players with force loaded chunks.
2. Use Crash Utilities mod
3. Press CTRL+U to bring up the menu.
4. Click the second tab for a list.
5. Click the "ENTITIES" button and switch to "TICKETS".
6. See list of forced tickets by clicking on the text.

### Expected behaviour

Chunks should unload

### Additional information

FTBChunks files contain "chunk_load_offline: false" already.

**Comment by legitswitch** [comment]
I found this issue was reported to have been fixed 4 weeks ago (check bottom of the linked page)
https://githubmemory.com/repo/FTBTeam/FTB-Chunks/activity?page=3

Both packs use ftbchunks build 71, which is older than when it was reported to have been fixed.

**Comment by Raidobw2** [comment]
LatvianModder last issue ^ is opened on your side for your records

**Comment by legitswitch** [comment]
Any update on this? I have issues where "/ftbchunks admin unload_everything" doesn't work either. I have to teleport to the claim and manually shift click then shift right click.

**Comment by Gaz492** [comment]
As this is a rather old issue and the pack has had several updates since this issue was reported its possible that this issue has been resolved.
It's also a possibility that another mod is keeping those chunks loaded
