### ISSUE TITLE
Direwolf20 1.19 cant connect to lan game

### ISSUE THREAD

**Issue by Punkenhead** [FTBTeam/FTB-Modpack-Issues#2312]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.04

### Describe the bug

the wife cant connect to my lan game

### Steps to reproduce

try to host a lan game

### Expected behaviour

want it just to work

### Screenshots

![Screenshot (130)](https://user-images.githubusercontent.com/120287879/206940946-87e08e73-2a67-47b3-8da1-61a129268bb6.png)

**Comment by Trelsonowsky** [comment]
Same as #2283

**Comment by Trelsonowsky** [comment]
Can you post both of yours latest.log and debug.log? Ill try comparing them to mine with the same issue

**Comment by jasondewitt** [comment]
Im having the same problem, tested with the release version and the new beta that shows up in my FTB client.

Heres the logs from both sides

[latest-client.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10225114/latest-client.log)
[latest-host.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10225115/latest-host.log)
[debug-client.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10225116/debug-client.log)
[debug-host.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10225117/debug-host.log)

**Comment by Trelsonowsky** [comment]
Yeah it's 1:1 identical with mine. Now we gotta wait for ftb to actually do something

**Comment by Saereth** [comment]
consolidated issue here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2283
