### ISSUE TITLE
unusual high server ping

### ISSUE THREAD

**Issue by Eidelmaim** [FTBTeam/FTB-Modpack-Issues#2313]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

we are unsure why this is happening... it is not indicated in the logs. we have noticed that when more than 3 players join a server using FTB Inferno 1.3.0 server, all players on the server receive a ping which is too high to play the game.. some palyers are seeing a ping of up to 42,000. We have tried running the server on different host machines at different locations across the united states and the issue remains. as soon as we have downgraded the server to 1.2.1 this issue resolved its self. only server side mod we added is auto-restart. even with this mod disabled and the server running as packaged it is still producing the problem.

### Steps to reproduce

create a server using 1.3.0.
have more than 3 players log in.
wait for rediculous pings to arrise !

### Expected behaviour

be able to play a multiplayer server with out unplayable high ping

### Screenshots

![image](https://user-images.githubusercontent.com/13890144/206946820-8f968c6a-38a6-4680-a62c-367d6253d875.png)
![image](https://user-images.githubusercontent.com/13890144/206946841-cac25ab5-2f18-4542-bcaf-8feeb763f8c6.png)

**Comment by orbidlo** [comment]
I recommend staying on version 1.2.1, the 1.3.0 is hot mess with just few end fight fixes.
I already reported similiar issue in #1904 but definitely thanks for further info.

**Comment by Eidelmaim** [comment]
we have updated our server to 1.5.0, we are testing to see if this issue persists. will report back soon.

**Comment by Saereth** [comment]
closing for now since most people have reported it clearded up in 1.5.
