### ISSUE TITLE
Direwolf20 1.19

### ISSUE THREAD

**Issue by elijahward** [FTBTeam/FTB-Modpack-Issues#2314]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.1

### Describe the bug

Storage Drawers not showing items. Sapplings, apples, and some logs

### Steps to reproduce

Create a storage drawer, put in above items

### Expected behaviour

I would like to see the items in the drawers

**Comment by ukmcplyr** [comment]
Likely dupe of FTBTeam/FTB-Modpack-Issues#2260
