### ISSUE TITLE
Bugged light sources from the feral flare lantern

### ISSUE THREAD

**Issue by xhos** [FTBTeam/FTB-Modpack-Issues#2315]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

Light sources from the feral flare lantern won't disappear when you brake the lantern with RFTools Builder

### Steps to reproduce

1. Place a feral flare lantern
2. Break it using RFTools Builder
3. Light sources stay

### Expected behaviour

Light sources to disappear

### Screenshots

![image](https://user-images.githubusercontent.com/60789741/207061884-89d4e689-41e3-4e16-bda5-11fdf44048e5.png)

Light sources without a lantern

**Comment by Sunekaer** [comment]
https://github.com/Xalcon/TorchMaster/issues/207

**Comment by UnRealDinnerbone** [comment]
This bug has been fixed
