### ISSUE TITLE
Furnace quest

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [FTBTeam/FTB-Modpack-Issues#2316]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

Quest Limbo > Dark Forest > Furnace requires wrong furnace. It instructs you to use blackstone to create a furnace. Which creates a blackstone furnace. However it requires a vanilla furnace.

### Steps to reproduce

1. Get to the stage the quest is active.
2. Craft furnace with blackstone.
3. Quest fails to complete.
4. JEI cheat in a vanilla furnace.
5. Quest completes incorrectly.

### Expected behaviour

Quest should complete with a blackstone furnace

**Comment by Saereth** [comment]
you just shapecraft a blackstone furnace into a vanilla furnace as shown in jei, ironically this quest is making sure you know how to craft it correctly :p
