### ISSUE TITLE
Rendering overlay

### ISSUE THREAD

**Issue by logios690** [FTBTeam/FTB-Modpack-Issues#2317]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Log Files

https://pste.ch/ugujaxehak.pl

### Describe the bug

It starts normally then it opens minecraft but it just crashes going back to the ftb app 

### Steps to reproduce

Open FTB app
Select Stoneblock 3
Press Play
Wait for it to crash

### Expected behaviour

launch the game normaly 

### Additional information

i also deleted forge-client.toml and it didn't fix it

**Comment by Raidobw2** [comment]
Hi, sorry for the delay. Try downgrading/updating first, then add `-Duser.language=en -Duser.country=US` in the additional java arguments for the modpack (in the modpack settings).

To downgrade you access the "Versions" tab on the FTB App, on the modpack's page.

SB3 1.5.0 also has a startup issue, you can do this workaround https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2404#issuecomment-1364625915 or wait when 1.6.0 comes out next week

Let me know if that worked or not
