### ISSUE TITLE
Forcecraft upgrade core not craftable

### ISSUE THREAD

**Issue by ImJeremyWade** [FTBTeam/FTB-Modpack-Issues#2318]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

The crafting recipe for an upgrade core from forcecraft is one force rod and an experience tomb with at least 100xp on it. Even with both of those items in a crafting table it does not create an upgrade core.
![image](https://user-images.githubusercontent.com/60204187/207145082-2fd61fb6-5a19-4681-8b5f-4a45a56cfcd5.png)

### Steps to reproduce

get experience tome with more than 100 exp on it
put in crafting table with force rod
expected output is upgrade core
no output for crafting recipe

### Expected behaviour

expected output is upgrade core but no output for that recipe

**Comment by koshorama** [comment]
Can confirm. Can't craft the core no matter how many levels I've got in the tome

**Comment by Saereth** [comment]
https://github.com/Mrbysco/ForceCraft/issues/68

**Comment by welch3694** [comment]
Here is perhaps a clue -- I was affected by this issue myself, and after trying every possible combo of force rod + experience tome, I accidentally left the tome and rod in the crafting grid, and then exited Minecraft entirely.

When I restarted my game, I opened the grid and I see that the upgrade core was actually craftable. I pulled one upgrade core out, and then swapped in a different book with much more experience (7900 xp), and I once again am unable to craft the cores.

I then left my 7900 xp tome in the crafting grid with the rod, and tried Save and Quit to Title, Upon re-entering the world I have 64 available cores. I crafted all 64 of them, and then was unable to craft any more after that.

**Comment by koshorama** [comment]
Tried it yesterday. Doesn't work on my instance of DireWolf20 1.19 1.0.4

**Comment by MCDemon117** [comment]
> Can confirm. Can't craft the core no matter how many levels I've got in the tome

I can confirm this too, it happens to me but it's on 1.0.4.

**Comment by EndlessDex** [comment]
@Saereth I am on 1.3.2 and still see this issue. Is that expected?

**Comment by MrRavain** [comment]
DireWolf20 1.19 version 1.3.2 still issue
