### ISSUE TITLE
Add mod for ethereal glass

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#2319]
### Modpack

FTB Presents Direwolf20 1.19

### Is your suggestion related to a problem? Please describe.

Ethereal (not solid to player) glass comes in handy not least for mob farms. I think Glassential is the mod that's provided it in previous direwolf20 packs from 1.16 upwards.

I seem to remember the pack's namesake being a big fan. Ahem :sunglasses: 

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/glassential

**Comment by frquadrat** [comment]
There are the "Dark Phantom Glass Viewer" and the "Phantom Glass Viewer" both in the XyCraft:World mod
