### ISSUE TITLE
Ftb Inferno: minion birth crashes game 

### ISSUE THREAD

**Issue by keithc463** [FTBTeam/FTB-Modpack-Issues#2321]
### Modpack

FTB Inferno

### Modpack version

1.30.0

### Log Files

https://gist.github.com/janai884/cf3a542cea137873617a190bc2261b06

### Describe the bug

Anytime a villager is birthed after around 118 it is crashing the game. 

### Steps to reproduce

Have a colony with 118 minions and space for more 

### Expected behaviour

Not crashing! 

### Additional information

Can't play at all. Is there any quick fixes I could do? Can't seem to find the list inferno uses for minion names

**Comment by orbidlo** [comment]
You could change this file to add more name options "$game_folder\kubejs\data\minecolonies\citizennames\default.json"
