### ISSUE TITLE
Character stuck in flight- Glitch associated with Gem and Red matter armor/gear set

### ISSUE THREAD

**Issue by DrBurnsey** [FTBTeam/FTB-Modpack-Issues#2322]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0

### Describe the bug

A couple of days ago, I opened a Compressed Chance Cube, and it spawned the Squid Aquarium on the torso block of my character. I crouched, and went prone in the available blocks underneath the aquarium, similar to how your character turns horizontal when you swim to fit through 1-block holes. I crawled out, hovering above the ground as a function of the Gem Hurricane Boots, part of the ProjectE Mod Pack. With the Gem Armor on, I am able to ascend and descend, but will not walk on the ground, and double tapping space does not allow me to stop flying. When I take the armor off, I also do not stop flying. Rather, I hover above the ground, unable to change my vertical position. If I am hovering more than a block above the ground, I am kicked from the server for flying. When I reload into the server, the problem persists.

NOTE- Every now and then (about once every 10 times I reload into the game) I randomly spawn in normally, able to walk on the ground, and able to use the Gem Armor as intended. However, when this happens, the Red Matter Pickaxe (also part of the ProjectE Modpack) becomes glitched, and any blocks I break replace themselves, comparable to breaking blocks while lagging- attempting to pass through the blocks results in being rubber-banding, etc. This I can accept, as I can just use other pickaxes from other mods, but getting this instance of the glitch requires me to reload the game several times just for the chance for this to happen.

I believe that this is simply a problem with the ProjectE modpack, but no amount of uninstalling and reinstalling has helped so far.

### Steps to reproduce

Initiate the Flying function of your Gem Armor (I had the full set on at the time).

Somehow, generate blocks on the torso level of your character, by method of commands or chance cube.

Crouch, activating the "prone" stance, and navigate to an open area where your character automatically stands back up.

### Expected behaviour

N/A

### Additional information

I am going to place my items in a chest and reset player data, hopefully resetting the glitch. I will update the forum whether or not this works.

**Comment by DrBurnsey** [comment]
Update: Deleting player data did, in fact, fix the problem. However, this deletes all of the items placed in alchemical bags, which I was not aware of. It's nice to be able to play again, but it's a shame that that happened as a result. If there's a better fix to this problem that I should have done, please let me know here.

**Comment by Sunekaer** [comment]
#1809
