### ISSUE TITLE
Minetogether Error

### ISSUE THREAD

**Issue by ValantheIR** [FTBTeam/FTB-Modpack-Issues#2325]
### Modpack

FTB OceanBlock

### Modpack version

1.12.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10213117/latest.log)

### Describe the bug

Error loading mods
1 error has occurred during loading

MineTogether (minetogether) has failed to load correctly
java.lang.NullPointerException: null

### Steps to reproduce

1. Open FTB App
2. Open FTB Oceanblock 1.12.0
3. When launch the client error appears

### Expected behaviour

Expected modpack to work

**Comment by DinnerBeef** [comment]
Do you know if this is still happening on the newest version of the pack?
