### ISSUE TITLE
SB3 Extreme Crafting Table

### ISSUE THREAD

**Issue by trevorgolden** [FTBTeam/FTB-Modpack-Issues#2326]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

Creating anything in the extreme crafting table can be duped, there is a delay in the update on the extreme crafting table that allows 2 people to grab it at once. 

### Steps to reproduce

Fill extreme crafting table with recipe
2 people looking in extreme crafting table
both players remove item unison
PROFIT

### Expected behaviour

Work right?

**Comment by Sunekaer** [comment]
#1903
