### ISSUE TITLE
Unable to craft Powah Ender Gates 

### ISSUE THREAD

**Issue by Tanerax** [FTBTeam/FTB-Modpack-Issues#2327]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

Unable to craft Powah Ender Gates because the Powah energy cables are removed.

### Steps to reproduce

1. Try and Make Ender Gates

### Expected behaviour

The ability to craft ender gates, since they are visibly in JEI

### Additional information

The cables are being removed (on purpose or accidentally) in the KubeJS Startup Script

**Comment by TheVekter** [comment]
The cables are just outright not in the pack at all. You can't even find them in JEI; they only show up in the crafting recipe for Ender Gates.
