### ISSUE TITLE
JEI intercepting clicks to Laser IO's Card Holder UI 

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#2329]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Log Files

N/A

### Describe the bug

When clicking on a card in Laser IO's Card Holder UI, sometimes JEI intercepts the click and brings up recipes from bookmarked items directly below where the card sites said UI.

[Blockshot video](https://blockshot.ch/YpNV)

### Steps to reproduce

1. Set enough bookmarks like in the video/gif above.
2. Access the Card Holder UI via a node and try to click/drag the card

### Expected behaviour

JEI does not intercept clicks

**Comment by Saereth** [comment]
I can no longer reproduce this in the latest update, reopen if you experience this again
