### ISSUE TITLE
[Bug]: JEI Config broken in game

### ISSUE THREAD

**Issue by sportsziggy** [FTBTeam/FTB-Modpack-Issues#233]
### Modpack

FTB OceanBlock

### Modpack version

1.5.0

### Describe the bug

JEI Config fails to open in game saying to "Install FTB Library to access ingame config".
FTB Library is installed.

### Steps to reproduce

Download game
Open game
Open inventory
Click JEI config button
???
Don't profit

### Expected behaviour

JEI Config is supposed to open up so we can edit it

### Screenshots

![image](https://user-images.githubusercontent.com/1366131/139905265-a8237eec-7543-482a-8f06-bbaad0444949.png)

**Comment by Sunekaer** [comment]
Duplicate issue report.

**Comment by sportsziggy** [comment]
@Sunekaer this works
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/155#issuecomment-957951116
