### ISSUE TITLE
Nickel Ore Direwolf 1.19

### ISSUE THREAD

**Issue by DiggityMan420** [FTBTeam/FTB-Modpack-Issues#2331]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

as with dire 1.18 pack again nickel is insanely hard to find this was like it as the start of 1.18 i have been mining at lvl of nickel and and have found more diamond and emerald then nickel. don't want to cheat it in  please fix

### Steps to reproduce

1. got to nickel lvl 
2. find nickel ( if you can)
3. good luck

### Expected behaviour

find nickel

**Comment by koshorama** [comment]
It's probably just very poorly textured. It looks almost exactly the same as deepslate. When you get ore scanner, you'll see how much nickel there is.

**Comment by Hazmatik** [comment]
It's because it is using Immersive Engineering's badly textured nickel ore that looks basically the same as deepslate. I wish modpacks with both Immersive and Thermal would default to the Thermal nickel ore it's much easier to spot when looking for it.

**Comment by Saereth** [comment]
We would have but thermal came out like 2 days before the pack released and oregen was already finalized, switching it now would be a breaking change to preexisting worlds
