### ISSUE TITLE
Waypoints not working properly

### ISSUE THREAD

**Issue by vantzs** [FTBTeam/FTB-Modpack-Issues#2332]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

Beta 1.0.4

### Describe the bug

Open map, right click on map, create waypoint. No matter how high in the air or deep underground the waypoint is always at surface level.

### Steps to reproduce

1) Open map
2) Right click on map
3) Create waypoint
4) TP to waypoint

### Expected behaviour

Should teleport you to the depth/height you are at

**Comment by HeavyDeception** [comment]
@vantzs I believe this is intended behavior but not 100%.  You can set a keybind for ftb chunks for placing waypoints   and they will be placed at your level.

**Comment by Saereth** [comment]
Yeah this is working as intended, setting a hotkey will do it at your current position otherwise it has no way to know exactly what height you'd want it at
