### ISSUE TITLE
Texture Bug

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Modpack-Issues#2333]
### Modpack

FTB Infinity Evolved 1.7

### Modpack version

Last version

### Describe the bug

Texture Bug

### Steps to reproduce

I downloaded the game, loaded a new World and than it happend. I would cut a tree down and i have a Texture Bug.

### Expected behaviour

That i can play Infinity Evolved withput this bug.

### Screenshots

![2696E019-F476-4DA8-9A35-6149DEE3F539](https://user-images.githubusercontent.com/111293025/207671642-bc899319-03eb-4cd1-bd8a-1461a9fa8eb0.png)

**Comment by Gaz492** [comment]
I believe that this issue is caused by old graphics drivers, making sure that your graphics drivers are up to date may fix your issue, but there are some known issues with older intel graphics that can cause these issues.
