### ISSUE TITLE
crash on opening refined storage system soon after loading

### ISSUE THREAD

**Issue by quantumchaos19** [FTBTeam/FTB-Modpack-Issues#2334]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.1

### Describe the bug

after loading into my world I press 3 ,which is my hotkey to open the refined storage wireless crafting grid, the one added by an addon mod, and the game freezes and then crashes 

### Steps to reproduce

1. load up modpack, I'm using ftb app,
2. load into your world
3. soon after entering world press the hotkey for the refined storage wireless crafting grid, this item is added by an addon mod,
4. the screen freezes and soon after the game instance crashes 

### Expected behaviour

game cragses

**Comment by Raidobw2** [comment]
Seems to be working fine in version 1.5.0+, so I'll assume this was fixed before.

When I press "Ctrl + G" to open the wireless crafting terminal, it works without any issues.

If you still experience this, please attach a crash log! Thanks
