### ISSUE TITLE
rubber and latex between TE and IF do not have compatibility. 

### ISSUE THREAD

**Issue by zziobro7** [FTBTeam/FTB-Modpack-Issues#2336]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Log Files

N/A

### Describe the bug

TE latex and IF latex don't have compatibility, nor do the two mod's rubbers. But JEI indicates that you may be able to convert latex via the bottling machine. This doesn't seem like intended behavior. 

### Steps to reproduce

Check various JEI recipes for rubber and latex. 
Liquid, Bucketed forms, and rubber itself is not cross compatible. 

### Expected behaviour

Latex and rubbers should be cross compatible, there doesn't seem to be any kind of serious difference in level of effort to acquire each.

**Comment by Saereth** [comment]
These fluids do not use a fluid tag or shared oredicting style, as such I have to assume the mod devs did not intend for their to be parity with the fluid of other mods. As Dw has requested we keep mods as close to their authors intent as possible this change wont be made on a pack level. You can contact Thermal or IF Devs and see if they would like to add a fluid tag to create compatibility between them but that will be up to the mod devs in this case.
