### ISSUE TITLE
Invar Blend missing ore dictionary

### ISSUE THREAD

**Issue by SteseDav** [FTBTeam/FTB-Modpack-Issues#2337]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

You cannot create Invar blend with ThermalSeries Iron & Nickel dusts, so you can't use the Thermal Series pulveriser to create Thermal Series Invar. 

Reported to have been fix in v 1.0.3... https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2286

### Steps to reproduce

Attempt to create Invar Blend with ThermalSeries Iron & Nickel Dust

### Expected behaviour

2x ThermalSeries Iron Dust + 1x ThermalSeries Nickel Dust should = 3x ThermalSeries Invar Blend.

### Screenshots

![image](https://user-images.githubusercontent.com/8818293/207921315-ab1ae5d7-325d-4a7c-9766-c1d1da66ad1b.png)

![image](https://user-images.githubusercontent.com/8818293/207921860-4fdbc5e0-9f7c-4c7a-90b3-154627ece822.png)

**Comment by TheVekter** [comment]
FYI this can be bypassed by using the Induction Smelter with Iron and Nickel ingots, but is clearly not intended behavior given how the pack is normally supposed to progress.

**Comment by SteseDav** [comment]
@TheVekter Good to know, thank you.

**Comment by HeavyDeception** [comment]
@TheVekter I can't get the Induction smelter because it requires Invar does anyone have another workaround? or do I have to get into mek just to get their dust?
