### ISSUE TITLE
Unable to collect vines with shears

### ISSUE THREAD

**Issue by SteseDav** [FTBTeam/FTB-Modpack-Issues#2338]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0..4

### Describe the bug

Using shares on vines does not give you vines. Vines are required for making Rubber in ThermalSeries.

### Steps to reproduce

Find vine, 'use' shears on Vines

### Expected behaviour

Get Vines

### Screenshots

https://user-images.githubusercontent.com/8818293/207924934-99036c54-0e5c-499a-a40b-99de046ae618.mp4

### Additional information

Using Shears on Vines is a Vanilla Mechanic

**Comment by frquadrat** [comment]
Using shears by left-clicking on the vines cuts / harvests them.
Using right-click halfs them without harvesting them and stops them from growing.

Same behaviour as in vanilla, isn't it?

**Comment by SteseDav** [comment]
Weird, didn't work when in testing the other day, and in the video... but working ok now.... so I'll close this.
