### ISSUE TITLE
Neat's HP bar mis-sized

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#2339]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Log Files

N/A

### Describe the bug

Some HP bars from Neat (screenshot below) are much longer horizontally than they should be.

### Steps to reproduce

Simplest repro (though not 100%):
1. Wait for a wandering trader
2. Get lucky and see a llama with an overly long HP bar

### Expected behaviour

Normal sized HP bars

### Screenshots

![Screenshot](https://gcdnb.pbrd.co/images/Hix7voVgQZmr.png?o=1)

**Comment by Saereth** [comment]
not just any trader too, specifically the white one
![image](https://user-images.githubusercontent.com/9200909/208715254-c3ca7f8e-5b13-45fd-85f0-06566ac4eee1.png)

**Comment by Saereth** [comment]
https://github.com/VazkiiMods/Neat/issues/121
