### ISSUE TITLE
Luggage, when trashed glitches back into inventory

### ISSUE THREAD

**Issue by DeadpoolDoc** [FTBTeam/FTB-Modpack-Issues#2340]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Describe the bug

When i try to trash the Luggage item, in the bottom right of my inventory, then click another item, the luggage appears in the spot where i clicked an item. The one in the trash can is fake and will disappear if you try to put it in your inventory, thus not duping, but making it impossible to trash in inventory.

Only work if luggage is empty when trashed.

### Steps to reproduce

1. Have luggage item, Empty
2. Have another item in inventory
3. Drag Luggage to trash in bottom left of inventory
4. click other item , the luggage should appear where the item was

### Expected behaviour

the Luggage should move itself to where you grabbed the item from,leaving a fake copy in the trash

### Screenshots

![image](https://user-images.githubusercontent.com/100952046/207986348-d72cd638-f8e5-400e-88ec-4070103fc1ac.png)
![image](https://user-images.githubusercontent.com/100952046/207986419-7d04b537-27ac-432e-a8a6-559aff5fb034.png)
![image](https://user-images.githubusercontent.com/100952046/207986468-841b52c7-6cbb-481e-9d30-12ebc4c62a99.png)

### Additional information

doesnt seem to work if there is something in the luggage

**Comment by UnRealDinnerbone** [comment]
Unable to reproduce if still able to reproduce on latest update, please reopen
