### ISSUE TITLE
Gobber 2 Medallion Not working along with water Breathing.

### ISSUE THREAD

**Issue by HeavyDeception** [FTBTeam/FTB-Modpack-Issues#2342]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.1

### Describe the bug

After building the Medallion of water breathing I could still drown.

### Steps to reproduce

1. Make a Gobber 2 Medallion of water breathing
2. stand underwater.

### Expected behaviour

I can breath underwater.

**Comment by Saereth** [comment]
https://github.com/kwpugh/gobber_forge/issues/29

**Comment by Almandor** [comment]
I have the same issue. And the medallion of water breathing is not working at all. Not just when another water breathing is active.

![image](https://user-images.githubusercontent.com/19967786/209689770-9df3670c-5148-4cda-8738-07836c107a5b.png)

**Comment by DGMexe** [comment]
Not working for me too

**Comment by choekstr** [comment]
Not working in ATM 8 pack.

Gobber version: 2.7.28
Forge version: 43.2.3
MC version: 1.19.2
