### ISSUE TITLE
Possible chunk loading issues with create

### ISSUE THREAD

**Issue by c44448** [FTBTeam/FTB-Modpack-Issues#2345]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

2 Bugs and im not sure if they are all realted to chunkloading.
1: If you restart your world the hose pulley block from create looses the hose but its only a visual bug its still working normaly?
2: my contraption shown below is working fine untill i start the world again. I have to visit it once in the nether. Everithing is in one chunk and loaded with FTB chunks. Not sure how to describe it other than its not filling the ender tank untill i go there once. (sometimes twice for some reason) Unfortualy i cant say what block has the problem.

### Steps to reproduce

1. reload world after beeing in the main menu.
2. Both issues are there.

### Expected behaviour

chunkloading should work for create

### Screenshots

<img width="1156" alt="BUG1" src="https://user-images.githubusercontent.com/113215353/208218089-5aa63f4e-7d07-4701-8de9-87e5e8613aae.png">

### Additional information

The visual bug isn't that bad but the need to go there after every restart of the world is a bit annoying.
If you need the world files let me know.

**Comment by Saereth** [comment]
1.0.5 will have updated create, this should be fixed in there now
