### ISSUE TITLE
FTBTeams "join" argment seems to be missing. Impossible to join other teams.

### ISSUE THREAD

**Issue by CailanVR** [FTBTeam/FTB-Modpack-Issues#2346]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Log Files

[2022-12-16-1.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10251025/2022-12-16-1.log)

### Describe the bug

Neither myself nor my friend are able to join each others' team using FTBTeams

### Steps to reproduce

1. Invite friend to FTBTeams team
2. Friend clicks "accept"
3. Command returns with invalid argument of "join"

### Expected behaviour

Allow joining of the team when invite is accepted.

**Comment by UnRealDinnerbone** [comment]
Was the person joining your team already at a party. To join a party, the person must not be on a team
