### ISSUE TITLE
jei-client.toml missing, unable to configure JEI

### ISSUE THREAD

**Issue by alucard87pl** [FTBTeam/FTB-Modpack-Issues#2348]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Log Files

Not sure which one would contain any info on that, please let me know, I'll upload then.

### Describe the bug

There is no `jei-client.toml`

### Steps to reproduce

Fresh pack download, fresh world, click JEI wrench:

### Expected behaviour

jei-client.toml file present, clinet config possible

### Screenshots

![image](https://user-images.githubusercontent.com/7818225/208240531-45f9b35d-aa38-4e18-a007-57c98a75bb10.png)

### Additional information

Copying from a different 1.19 pack does not help.

**Comment by Saereth** [comment]
JEI doesnt have a client toml in 1.19.2, instead they moved to an ini based config system which you will find in the new 1.0.5 update of this pack (releasing soon) which now has the updated JEI
