### ISSUE TITLE
[Suggestion]: Feedback on Endgame Singularities

### ISSUE THREAD

**Issue by dizzystem** [FTBTeam/FTB-Modpack-Issues#235]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

This is a thread for people to post suggestions on regarding the endgame singularities, since the strawpoll at https://strawpoll.com/kkpyzkjyc doesn't have a comment field for more detailed feedback.

**Comment by lachian** [comment]
I believe the Magical Egg Singularity is too dependant on getting "lucky" on getting a Compressed Experience Pearl and knowing NOT to eat it. Otherwise, it leads to players trying to implement very laggy mob farms trying to farm the Experience pearls via Draconic Grinder with an item that can take the Experience Harvest Enchant.

**Comment by dizzystem** [comment]
The magical egg singularity is highly RNG-dependent, since if you get an 8x experience pearl from a quest you can skip it - and importantly, farming experience pearls in such high quantities requires many spawners and many mob grinders, which causes huge amounts of lag.

To contextualize this, I've built a spawner farm with 16 spawners (upgraded with Draconic Evolution draconic cores) and 9 Draconic Evolution mob grinders, each with an Experience Harvester V enchantment. It's dropped my entire base to an unplayable 5 fps and is estimated to take 30 hours to finish getting all 324,000 experience pearls required for the singularity.

I believe the nerf to remove 8x experience pearl drops from crate and barrel loot was aimed at this, but it actually makes the problem worse - if you don't get an experience pearl by the time you've finished all your quests, you have to farm for it.

My suggestion is to either increase the pearl drop rate or reduce the amount of pearls needed somehow - probably both. Another possibility is to add some other way of crafting experience pearls or magical eggs, like converting essence / fluid xp / liquid mob souls from Industrial Foregoing / Mob Grinding Utils / KubeJS into experience pearls with jars or something.

**Comment by dizzystem** [comment]
I also think that the supremium coal singularity might be a bit too grindy - half of my hydroponics and later on my power pots have been dedicated solely to inferium seeds. That's the same amount of growing space as all the other singularities put together. On the other hand, reducing that cost would also make each of the other resource-heavy singularities (wyvern energy controller, dimensional shard, raw neural processor, tesseract) easier by freeing up growing space, so it might not strictly be a plus. Other opinions are welcome.

**Comment by dizzystem** [comment]
On the other end, some singularities that might be too easy are the terrasteel, pig iron, refined obsidian, clay, oak, and phyto-gro singularities.

Terrasteel can be grown using Mystical Agriculture, and since the singularity uses nuggets it's really easy to produce a lot of it. There's a bit of initial difficulty in obtaining the ingots to craft the seed, but that's all.
Refined obsidian and pig iron are the same, just without the x9 nugget multiplier. The solution is just to grow it.
Phyto-gro is crafted 8 at a time from a sand block, two apatite, and a niter, which are plentiful from sluicing or crushing cobblestone. By the time you get to endgame, you'd already have more than enough as a byproduct from sluicing for ores. This is even easier than the previous three - all you have to do is to run an auto crafter for an hour or two.
Clay is craftable with auto jars - you get 16 per second with one jar (32 with a crying obsidian block), and the costs are basically free.
Finally, oak is also growable with either saplings or MA wood seeds, and is incredibly fast to grow with the latter because 3 wood essence crafts into 16 oak logs. It's also slightly redundant with the basic krate singularity, since basic krates cost 20 logs each.

My suggestion here is to keep just one of the directly growable singularities, since they're functionally the same. Terrasteel is probably the most interesting one, since the starting ingots are complex to get, but it should use ingots instead of nuggets. If nothing else, the oak singularity is the best one to switch out for something more interesting. I'd like to see more Farmer's Delight singularities, since there's hardly anything from that mod.
Alternatively, there could be some additional cost to crafting refined obsidian, terrasteel, or pig iron from the MA essences - kind of like how the nitro crystal essences have to be combined with a nether star to make nitro crystals. That would be good for differentiating them.
The clay singularity could use clay blocks instead of clay balls, since they're absolutely plentiful.
As for the phyto-gro singularity, it could use phyto-gronades, phyto-soil or PNT - those cost multiple phyto-gro to craft, to somewhat offset the x8 crafting ratio.

**Comment by dizzystem** [comment]
A comment about the crystal shard seeds added in 1.6.0 - I think that they remove variety from the endgame by making crystal shards another growable singularity, like the ones mentioned above. Previously, there was the choice between quarrying for shards in the End or sluicing for shards using a gold mesh and crushed end stone, and while sluicing was far easier it was still an interesting choice.

**Comment by Sunekaer** [comment]
The reason, why crystal shards were made growable, was because of complaints that getting that singularity took too long compared to others...
It's hard to balance the singularities right and make everyone happy

**Comment by dizzystem** [comment]
In my experience, the crystal shard singularity was much much faster than singularity singularities, supremium coal, or magical eggs. One sluice with max upgrades was enough.

**Comment by dizzystem** [comment]
Let me see if I can get some numbers.

**Comment by dizzystem** [comment]
So a piece of crushed endstone has a base 7% chance of making a crystal shard. With 18 fortune upgrades, that's a 61% chance. It has a base processing time of 100 ticks, which is multiplied by 0.4 for a netherite sluice and then 0.1 for max speed upgrades, thus processing in 4 ticks. This means that with _one_ upgraded netherite sluice you get 5 rolls of 61% per second, averaging out to 3 crystal shards per second.

In comparison, my singularity singularity build with 104 chisel bit tanks takes up an entire half of a compact machine and produces less than 1 singularity per second. That's probably less than 1% of a singularity per second per chisel bit tank. To get the same rate as the above, I'd need over 300 chisel bit tanks or so.
A MK4 power pot has a 75% chance to produce 64 inferium every 24 seconds, which works out to 2 inferium per second - or 1/256 of a piece of supremium coal per second. To get the same rate as the above, I'd have to build 256 * 3 = 768 MK4 power pots, consuming 267 million FE/t of energy - compared to the 651 thousand FE per operation of the single sluice, which at 4 ticks per operation works out to a mere 162 thousand FE/t. In practice, with my Mekanism fusion reactor, I could produce 60 million FE/t, which runs 171 power pots that I dedicated half to inferium and half to other resources. 85 power pots is a ninth of the above 3 supremium per second setup, which means I was producing a third of a supremium coal per second.
Finally, as previously mentioned, my magical egg megaspawner farm takes 30 hours with 16 spawners to produce 108 singularities. This works out to exactly 1.5 magical eggs per second - and don't forget the lag.

I hope that helps.

**Comment by dizzystem** [comment]
Ferretmaster on the discord says they just used vein mining and fortune to manually collect 60 singularities of crystal shards from the End in 10-15 minutes. I didn't think of that, but that may make crystal shards actually the fastest endgame singularity.

**Comment by NaminBeforeGamin** [comment]
Why don't you just make a recipe for experience pearls(or even 1x experience pearls ) in the blast chiller or even with tinkers? then cut the amount of the eggs needed in half since it is unequivalent iron/diamond wise(because of the unstable ingot) in comparison to the other singularities. I mean singularities arent really even a logistic challenge if its just lag city.

And for singularity singularity, it'd be nice to have some sort of infinite water source for it to be bareable(like a sink). I know that ruins some challenge but I think it makes it more fun. Who cares about that type of balance? this is a simple little skyblock pack and you shouldn't have to die for resources like that yk? At that point it's just not fun.

**Comment by demethan** [comment]
I do find the magical egg singularity disproportionately long to craft. My mob farm is already affecting the gameplay on the server.  I have plenty of liquid XP or mob essence.  It would be nice to convert some of that to XP orbs. It's now a waiting game. When it gets like that, I move on to some other pack or game. Most of our players do the same.
