### ISSUE TITLE
Direwolf20 1.19 Mine Colonies Keep taking items(tools) from my inventory - Silent Gear Only

### ISSUE THREAD

**Issue by zeziba** [FTBTeam/FTB-Modpack-Issues#2350]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

The builder keeps yonking a copper excavator from my primary inventory if it is in there. I put it in my backpack and it doesn't disappear.

Don't know if distance matters but the colony is chunk loaded completely, hut is first level not upgraded.

Has happened when I am over 100 blocks away and over 50 in y as well.

### Steps to reproduce

1. Have a mine colony with a builder.
2. (Accidentally)Give a builder a silent tools excavator.
3. Take the tool back with a in-place replacement tool that is vanilla minecraft shovel
4. Wait till the bugger takes your tool - needs a job active that requires digging and the current wooden tool needs to break
4.a. Seems to happen when builder is looking for a replacement tool.

### Expected behaviour

The builder to not teleport the tool to themselves

**Comment by Saereth** [comment]
This should be fixed in the new update of MC, let me know if this still occurs in 1.0.5 once its out
