### ISSUE TITLE
SB3 | Replace the WOFT with Torcherine

### ISSUE THREAD

**Issue by Exymat** [FTBTeam/FTB-Modpack-Issues#2351]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

There's no denying it, mid late game in SB3 has to be done with the use of the Watch of Flowing Time from Project E. But as it stands, the lack of configuration of the woft is causing more harm than good. 
Having 10 and more WOFT on a server can and will destroys TPS, and that's even when you add server performance improvements mods that can work with SB3 (which is not even how the pack is shipped by default), and that's why WOFT is banned on public community servers hosting SB3.
TPS management is a big issue server side in modpacks, and the WOFT isn't helping, making a 10 by 10 by 10 cube of uncontrolable size, sometimes more than needed tick rate increase.

### Mod suggestion

Torcherino (https://www.curseforge.com/minecraft/mc-mods/torcherino). Torcherino has around 2.8M download on Curse, and can be seen as a more perfectionned and configurable WOFT. It offers : 
- a 3 dimentionnal control of the area in which ticks are increased (configurable), 
- a slider to control the speed (configurable), 
- a better redstone control than the WOFT. 
And all of the Torcherino options can be modified using config files, which adds more power to the dev team to balance the item if needed, and the slider accessed in game with shift right clicking the torch. 
As a result, control more precisely the affected area (instead of the default 10 by 10 by 10 of the WOFT, that sometimes is just more than needed) and adapt the speed rate to suit better what you want accelerated.

**Comment by Sunekaer** [comment]
We wont be replacing any mods, we looked at Torcherino in testing but choose not to go with it.
