### ISSUE TITLE
server crashing on boot 

### ISSUE THREAD

**Issue by GamerBrit** [FTBTeam/FTB-Modpack-Issues#2356]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Log Files

[crash-2022-12-18_21.11.15-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10254656/crash-2022-12-18_21.11.15-server.txt)

### Describe the bug

i honestly dont know, the server crashes when i boot it

### Steps to reproduce

all that i do i boot the server and it crashes 

### Expected behaviour

not crash

**Comment by NotTheNobleSavage** [comment]
Looks like your server is lagging bad, might need to free up some resources. For the mean time a workaround is changing max-tick-time=-1 in your server.properties.

**Comment by GamerBrit** [comment]
[crash-2022-12-19_03.01.32-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10255592/crash-2022-12-19_03.01.32-server.txt)
is it the same issue?

**Comment by GamerBrit** [comment]
[crash-2022-12-19_03.12.00-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10255628/crash-2022-12-19_03.12.00-server.txt)
another one just incase

**Comment by GamerBrit** [comment]
https://mcpaste.io/ea2e527276ae5736 latest crash

**Comment by GamerBrit** [comment]
https://mcpaste.io/97dd3d4420fb9449 crash after ai reinstalled the pack

**Comment by Saereth** [comment]
duplicate, ftb chunks issue, fixed in next update
