### ISSUE TITLE
Server Crash When Opening Lootr Chest Underwater

### ISSUE THREAD

**Issue by KalenNighteyes** [FTBTeam/FTB-Modpack-Issues#2357]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.1

### Describe the bug

It seems that when going to loot Lootr chests that are in ship wrecks/under water it just crashes the server. Both myself and my friend have tried opening them. The chests still work when not underwater so the issue seems to be isolated to Lootr chests that are underwater. Uncertain if this is an issue in singleplayer.

### Steps to reproduce

Go to any shipwreck under water and try to open the Lootr loot chests that are in them. I am uncertain if this happens in singleplayer to crash the game.

### Expected behaviour

I expected to be able to open the chest and obtain its contents.

**Comment by SteseDav** [comment]
have you tried this in version 1.0.4?

**Comment by FullMetalMaster** [comment]
having this issue in 1.19.2

**Comment by AgentAvis** [comment]
Also seeing this in 1.19.2, v0.4.27.67 fabric

Server stops responding (seemingly overloaded) every one times out and a minute later the server calls it quits and crashes
