### ISSUE TITLE
Klein Star Duping. Refined Storage

### ISSUE THREAD

**Issue by gmfjrii** [FTBTeam/FTB-Modpack-Issues#2360]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Describe the bug

When auto-crafting a Colossal Klein Star Omega using Refined Storage no resources appear to be consumed. Coal, Alchemical Coal, Mobius Fuel or Diamonds.

### Steps to reproduce

Setup auto-crafting for Colossal Star Omega using Refined Storage.
I recreated this in creative with no resources in a creative Disk Dive.

### Expected behaviour

I haven't done the math but it should cost hundreds of thousands of Coal and Diamond.

### Screenshots

![image](https://user-images.githubusercontent.com/120997563/208336624-269f812d-a66a-4a07-832e-7adc1e49ff90.png)
![image](https://user-images.githubusercontent.com/120997563/208336642-4209db4e-b48d-434e-9bed-c71cbf18ab82.png)

**Comment by DinnerBeef** [comment]
Reported Issue https://github.com/refinedmods/refinedstorage/issues/3500

**Comment by UnRealDinnerbone** [comment]
Closing this issue as it does not seem the mod is going to update
