### ISSUE TITLE
Blood Magic Reinforced Runes Cannot Be Picked Up Once Placed

### ISSUE THREAD

**Issue by MaxAstro** [FTBTeam/FTB-Modpack-Issues#2362]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

Blood Magic's Reinforced Runes have no tool assigned to them, and don't drop themselves unless broken with the "correct" tool, effectively making them impossible to pick up once placed. Even a silk touch pick doesn't work.

This is especially unfortunate because they are marked as "safe for decoration"...

### Steps to reproduce

1. Place any Reinforced Rune from Blood Magic.
2. Try to break it.
3. Notice that One Probe indicates "No Tool" as the correct tool.

### Expected behaviour

Reinforced Runes should be able to be picked up like normal Runes.

**Comment by Saereth** [comment]
this should be fixed on bloodmagic's side so I reported to them, fixed the tags for the pack in the meantime
