### ISSUE TITLE
Mekanism Radiation Linger Time

### ISSUE THREAD

**Issue by MetagamerDotJpg** [FTBTeam/FTB-Modpack-Issues#2363]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

I think the time for radiation to clear up from a fission reactor is entirely ludicrous. I've been waiting several hours now and it's down maybe 60% in radius because I broke a pipe with a tiny amount of nuclear waste in it.

In the real world, I suppose this would take way longer to dissipate but this isn't real life.

A default nerf to the time it takes to disappear (and maybe a mention/warning in the quest section with a quest for a hazmat suit) would be very nice. I know I can edit the config for this myself, but I imagine everyone will want this.

I do not know how much faster it should disappear, so if considered I will leave that to you. Personally, I don't think it should exceed an hour or two.

**Comment by Dan-Mizu** [comment]
Didnt take long for me. I think it depends on the size of your reactor, and I had the minimum size- also had it in a compact machine because I knew it would probably happen. Possibly try a watch of flowing time in the area that is affected? idk. probably wont work.

**Comment by tyler489** [comment]
The more sources of radiation, the faster it will decay according to the mekanism devs, I broke 25 of the prcs with the red matter multitool and it took a full 24 hrs for it to decay, but thats the price you pay, as for the watch of time, I dont believe that works.

**Comment by DinnerBeef** [comment]
This is the default mod behavior, however if you don't like it, you can always just run the command "/mek radiation removeAll". On a side note, the biggest compact machine is designed to be able to build the reactor in.
