### ISSUE TITLE
Refined Storage

### ISSUE THREAD

**Issue by Basketpro03** [FTBTeam/FTB-Modpack-Issues#2365]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Describe the bug

when i use the crafting grid of refined storage the game crashes and and takes me out of the game 

### Steps to reproduce

click on the crafting grid

### Expected behaviour

The Crafting grind opens

### Screenshots

![Captura de pantalla (338)](https://user-images.githubusercontent.com/121059635/208510841-7b3fbaa5-e5e0-46ab-9c98-9ec4ac135dbe.png)

### Additional information

I have 7gb of ram in instance memory

**Comment by Raidobw2** [comment]
I've placed some Framed Drawers inside the Refined Storage system and it seems to work fine. The Framed Drawers appeared to have been the issue causing the crashes. I've updated Functional Storage quite a few versions, so this should be fixed?... I think.

If you still experience this in the upcoming 1.6.0 of SB3 next week, let me know here and I'll take a look at the issue again.
If possible also, open your `saves` folder and open your world folder. Inside you'll find a `data` folder, open it.
There will be a file called `refinedstorage_disks.dat`. Rename the file to `refinedstorage_disks.dat.txt` and try to drag it here.

If it's too big, try sharing it here with Google Drive or find me on the FTB Discord (`@R3GEN`) and send that file to me in DMs. I believe this file contains the Refined Storage items in the disks, and it would be helpful for me to try and reproduce your framed drawers with the same materials. Thanks in advance 🙂
