### ISSUE TITLE
[bug] ender dragon not attackable

### ISSUE THREAD

**Issue by plainkinkajou60** [FTBTeam/FTB-Modpack-Issues#2366]
### Modpack

FTB OceanBlock

### Modpack version

1.15.1

### Describe the bug

whenever i enter the end i am unable to damage the ender dragon through any direct method (swords bows etc etc) yet when i have a friend enter the end and try to damage the dragon it takes damage like expected?

### Steps to reproduce

unsure how i can reproduce the issue as it seems to only be happening to me 

### Expected behaviour

the ender dragon takes damage

### Additional information

![dragon](https://user-images.githubusercontent.com/61305058/208557130-d865eedc-78cd-4cde-bb2e-bcda1bca68ef.gif)

**Comment by DinnerBeef** [comment]
Unable to reproduce this bug. Please let us know if you still have this issue in the next version of the pack.
