### ISSUE TITLE
SB3 Crashs after reentering any world

### ISSUE THREAD

**Issue by WBatten** [FTBTeam/FTB-Modpack-Issues#2367]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Log Files

[Logs.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10264271/Logs.zip)

### Describe the bug

Crash shortly after loading into any world (Single or Multi).
Loads fine with new world creation.
Using FTB App.

### Steps to reproduce

Load Game
Load World or connect to server
a few seconds after the world loads the game crashes

### Expected behaviour

Not crash

**Comment by ManInDark** [comment]
Likely the same as #2391 and #2404

**Comment by WBatten** [comment]
After updating to v 1.5.0 of this pack, the issue seems to be resolved.

**Comment by Raidobw2** [comment]
Alrighty, I'll go ahead and close this then. There is a fix in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2404#issuecomment-1364625915 for those still having an issue joining worlds

**Comment by Talidorn** [comment]
If you are running on AMD...

Open configs -> flywheel-client.toml

change:

backend = "INSTANCING"
to
backend = "OFF"
