### ISSUE TITLE
Shift+[1-9] is intercepted when typing in JEI

### ISSUE THREAD

**Issue by terickson001** [FTBTeam/FTB-Modpack-Issues#2368]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

When trying to type `@` or `#` in the JEI search bar, the search bar is instead unfocused, and the corresponding hotbar slot is selected as if the number key was pressed.

### Steps to reproduce

1. Load into game
2. Open Inventory
3. Focus JEI Search bar
4. Type `@`

### Expected behaviour

`@` would be entered in the search bar

### Screenshots

Typing `@` (Shift+2) in the search bar
https://blockshot.ch/z8qs

**Comment by Saereth** [comment]
This is fixed in the JEI update for next pack release
