### ISSUE TITLE
[Suggestion]: Make Waystones Free

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Modpack-Issues#2369]
### Modpack

FTB Presents Direwolf20 1.19

### Is your suggestion related to a problem? Please describe.

Is there a reason that waystones cost xp? No! Make them free for all

**Comment by Saereth** [comment]
The reason I didn't change them is that Dire has stated he prefers to leave most mod configs like this default as the developers intended them for showcasing in his lets play so in other packs I'd agree with you but for fidelity within dire's series we'll be leaving it.
