### ISSUE TITLE
Game Crash when i enter the "Game Menu"

### ISSUE THREAD

**Issue by AtomicDonuts** [FTBTeam/FTB-Modpack-Issues#2372]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10272653/debug.log)

### Describe the bug

When i open the game, i can select the world, it will open and i can play normaly (and smoothly) until i hit the ESC key and enter the Game Menu. When it happen the game will freeze and never recover. 

### Steps to reproduce

1. Open the game and start a world
2. Push the ESC botton on the keyboard

### Expected behaviour

The game to play without freezing and crashing

**Comment by AtomicDonuts** [comment]
After futher investigation i discovered that the problem was not the Game Menu but the saving process of the map

**Comment by LawnMower9999** [comment]
I'm having the same problem but I still haven't found a way to fix it, can you tell me how you fixed it?
