### ISSUE TITLE
Tinkers Issue

### ISSUE THREAD

**Issue by TheLoneDude** [FTBTeam/FTB-Modpack-Issues#2373]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Describe the bug

When using a lever to pour seared stone into an ingot cast, it bugs visually as seen in the screenshot. When trying to collect, it instead grabs the cast first.

### Steps to reproduce

1. Make a Tinker's Smeltery
2. Smelt something into seared stone, and try to pour into Ingot Cast using a lever.

### Expected behaviour

The seared brick should be obtainable without needing to remove the cast.

### Screenshots

![Screenshot (138)](https://user-images.githubusercontent.com/86646904/208784017-842bc038-86fe-421e-9d9e-4a6c02a8ade1.png)

**Comment by UnRealDinnerbone** [comment]
I'm unable to reproduce this issue if this still happens in the latest version, please reopen the issue
