### ISSUE TITLE
Game crashes upon attempting to open

### ISSUE THREAD

**Issue by OpInternet** [FTBTeam/FTB-Modpack-Issues#2375]
### Modpack

FTB OceanBlock

### Modpack version

1.15.1

### Log Files

https://paste.feed-the-beast.com/view/31c5da81

### Describe the bug

Upon trying to launch the game, the game crashes during the setup stage, I've restarted my game and ftb and my laptop and the issue still persists. I 

### Steps to reproduce

1. Try to launch game
2. Watch as game tries to open and crashes 

### Expected behaviour

The game crashes

### Additional information

I think the issue might have something to do with the fact that I'm on an M1 Mac but I really have no idea

**Comment by DinnerBeef** [comment]
Are you able to re-upload the crash log, It seems to no longer exist?
