### ISSUE TITLE
Gobber 2 - Dragon Armor - No Creative Flight & No Water Breathing

### ISSUE THREAD

**Issue by SirDeKay** [FTBTeam/FTB-Modpack-Issues#2377]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.1

### Describe the bug

No creative flight and no water breathing while wearing the full dragon armor

### Steps to reproduce

Creative flight:
Wearing the armor
Double press the jump-key which should normaly activate the flight mode

Water breathing:
Jump into the water

### Expected behaviour

Creative flight and water breathing while wearing the full armor set

**Comment by QuillDev** [comment]
Appears there's an issue on the gobber 2 wiki that relates to flight not working in non-vanilla dimensions, there is a config option to fix this

https://github.com/kwpugh/gobber_forge/issues/6

**Comment by SirDeKay** [comment]
Problem solved, many thanks

**Comment by PurplePillowParadox** [comment]
> Problem solved, many thanks

The flight solution was helpful, but I would still like to see if anyone has a solution for the water breathing issue.

**Comment by PurplePillowParadox** [comment]
Other Gobber 2 issues can apparently be fixed in the same file. Thanks. Also, for me, the flying only stopped working in the other dimension if I spawned there or got there through a way other than entering the portal.
