### ISSUE TITLE
[Bug, FTBSluice]: Sluice proccesing when fluid is actually too low.

### ISSUE THREAD

**Issue by andr9528** [FTBTeam/FTB-Modpack-Issues#238]
### Modpack

FTB OceanBlock

### Modpack version

1.5.0

### Describe the bug

In the Sluices that use less than 1000mB per craft it only checks to ensure the correct fluid is there, not that there is sufficient fluid.

I.e a Iron sluice with 1000mB can proccess two pieces, when it should only proccess one, and then be missing 200mB to do the next one.

### Steps to reproduce

1. Place down Iron Sluice with any Mesh.
2. Add Hopper to the side of Sluice.
3. Add 1000mB of water.
4. Place two pieces of gravel in hopper.
5. See both pieces be sluiced.
6. Profit and look at the error. 

### Expected behaviour

I'd Expect the first pieve to go throught just fine, but the next be waiting on another 200mB of water.

**Comment by Raidobw2** [comment]
Michael see linked issue above ^ on Mod Issues for your records

**Comment by MichaelHillcox** [comment]
I've fixed this in dev, it'll need a new pack version for the fix to take effect :+1:

**Comment by Raidobw2** [comment]
Fixed in `ftb-sluice-forge-1.0.9-build.34.jar`, available now
