### ISSUE TITLE
Demon's Dream Seeds (Occultism) - Growable in Phytogenic Insolator (Thermal Expansion)

### ISSUE THREAD

**Issue by SirDeKay** [FTBTeam/FTB-Modpack-Issues#2380]
### Modpack

FTB Presents Direwolf20 1.19

### Is your suggestion related to a problem? Please describe.

The Demon's Dream Seed is in my opinion a seed like every other plant seed in this game.
For this reason I was very suprised that it is not possible to grow it inside the Phytogenic Insolator.

### Mod suggestion

Mod 1:
Occultism

Item:
Demon's Dream Seed
----------
Mod 2:
Thermal Expansion

Item:
Phytogenic Insolator

**Comment by Saereth** [comment]
yeah thermal doesnt support all modded seeds so I'll get this one added and check if there are some others that need adding soon

**Comment by garyccurtin** [comment]
Is it possible to add Forestry trees so they work with the sapling augment? Some mod sapling work like Industrial Craft rubber tree or Integrated Dynamics menril saplings, but not others.
