### ISSUE TITLE
Oak Sapling (Occultism) - Unnatural behavior

### ISSUE THREAD

**Issue by SirDeKay** [FTBTeam/FTB-Modpack-Issues#2381]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.1

### Describe the bug

My goal is to automaticaly convert vanilla minecraft Oak Saplings into the counterpart from Occultism.
I tried this process manualy and found a differeent symbol between the JEI end product and the oak saplings in my inventory.
Screenshot 1: JEI
Screenshot 2: Occultism Oak Saplings in Inventory

After this I wanted to automaticaly produce this Occultism Oak Sapling.
The Formation Plane (Applied Energistics 2) dropped the "normal" Oak Sapling onto the Spitfire from Occultism.
The sound indicates that the process was successfully completed.
I have set a whitelist filter inside the Advanced Item Collector (Item Collectors), as a symbol the one inside my personal inventory was shown.
After the completed transformation the Item Collctor put the Occultism Sapling inside a chest.
But inside the Chest the symbol out of the JEI was shown.
If this item is now importet into the Applied Energistics Network the task cannot be fullfilled because this is expected.
Screenshot 3: Occultism Oak Saplings automatic pickup

I can put this item from the chest or the AE2 System into my inventory and it changed in an instant into the other symbol (Screenshot 2).

### Steps to reproduce

1. View Symbol from end product (Convert Oak Sapling into Occultism Oak Sapling)
2. Do this proces by hand and check this item (This should be another symbol then in Step 1.)
3. Pick up the end product automatically and check this item (This should be the same symbol mentioned in Step 1.)

### Expected behaviour

These two Occultism Oak Saplings should have the same symbol and the same behaviour (For the purpose of automation)

### Screenshots

JEI:
![JEI](https://user-images.githubusercontent.com/121033670/209051462-e249b64c-cc14-4a36-91d4-bf2acb14b17a.png)

Occultism Oak Saplings in Inventory:
![Occultism_Oak_Saplings_in_Inventory](https://user-images.githubusercontent.com/121033670/209051483-06c5ee20-2e9e-45ce-b157-a828dac0abcf.png)

Occultism Oak Saplings automatic pickup:
![Occultism_Oak_Saplings_automatic_pickup](https://user-images.githubusercontent.com/121033670/209051496-10fd92cb-d5d3-429f-8832-da76441e6592.png)

Experimental Setup:
![Experimental_Setup](https://user-images.githubusercontent.com/121033670/209053254-b9a8852d-1060-4c17-b63a-9c684c494747.png)

### Additional information

The fourth screenshot serves as a guide for my experimental setup

**Comment by Saereth** [comment]
Occultism just received a major update, please update your pack and let me know if this issue persists for you, I'll leave this issue open for now
