### ISSUE TITLE
Bedrock required in schematics

### ISSUE THREAD

**Issue by DillePickle** [FTBTeam/FTB-Modpack-Issues#2383]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

Tier 5 Houses require bedrock which is always required even if you keep telling the builder to skip it, making it impossible to build the house. Courier huts have a similar issue at every tier, but telling the builders to skip it will get them to skip it, though every time they go back to their hut you have to skip again,.

### Steps to reproduce

1: Tell a builder to upgrade a house to tier 5
2: Wait until the last steps where they ask for bedrock
3: Skip the step
4: Fail to continue the building

1: Build or upgrade the courier's hut 
2: A notification for bedrock comes up in the construction menu
3: Skip it

### Expected behaviour

Both buildings should not require bedrock as far as I know it is unobtainable, though blood magic does have some non-working recipes for it

### Additional information

The build menu before you can tell the builder to start the building does not ask for bedrock for either building.

**Comment by drkanbs** [comment]
I found a recipe that lets you make bedrock. You should look for it, gotta dig.

**Comment by Zbulu** [comment]
can you tell how to make bedrock it is annoying that my builders cannot finish buildings

**Comment by drkanbs** [comment]
There are a number of Alchemy array options available for creating bedrock.  I was trying to prove it but I am having crash issues with another mod in the pack that affects everything.  no one on here has helped yet.  But I was able to load it just long enough to use JEI and see the recipe for bedrock, and the alchemy array came up.  It's a recipe from the Blood (something) mod.

**Comment by Zbulu** [comment]
oh these alchemy recipes for bedrock do not work I've tried every single one of them they either have different effects like rune of harming or jumping or no effect at all I guess until this get fixed won't be able to finish my village upgrade to full level 5 :(

**Comment by drkanbs** [comment]
Straight from the inferno Dev on the FTB Discord. 

"If your builder asks for bedrock just tell them this will have to do for now/cancel and they will complete the structure without it."

**Comment by Zbulu** [comment]
it worked few times now however for example for glass blower lvl 5 it doesn't matter how many times I try to cancel it builder still asks for bedrock and does not finish the building
