### ISSUE TITLE
[BUG] Game Breaking on Death 

### ISSUE THREAD

**Issue by Powknee** [FTBTeam/FTB-Modpack-Issues#2389]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

The game plays fine until dying and breaking the tombstone on the obituary mod. Although before this sometimes once dying the game also breaks without breaking the tombstone. Specifically, once it breaks, the game is still playable, but breaking blocks and moving too far in one direction makes blocks invisible. Which makes it so I can see into the void, so too far and nothing becomes viewable. Plus breaking and interacting with anything works, but is in no way functional. Its like I'm in a world that's just lagged out but I'm still moving around in it. 

### Steps to reproduce

1. Download Stone block 3     
3. Load into classic stoneblock cave 
3. Kill self  
4. Do or don't break tombstone
5. Game Breaks

### Expected behaviour

Game breaks on death and to fix only restarting game works. Plus deleting files and redownloading files doesn't fix the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/121290810/209321772-bc090a8d-2862-4cb1-93c3-041c50ba48dd.png)

**Comment by DinnerBeef** [comment]
Do you have any logs file from when this issue happened? We are unable to reproduce this.
