### ISSUE TITLE
Some Mod added Fluids not properly registered

### ISSUE THREAD

**Issue by DrSyndicate** [FTBTeam/FTB-Modpack-Issues#2390]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

At present Menril Resin and Chorus Resin for Integrated Dynamics are showing as "Fluid_Type.Unregistered_Sadface" In JEI. The same is occurring with the fluids from Force and Murky fluid MahouTsukai. The issue also persists when the fluids are placed in the world from a bucket.

I've tested this in both a solo DW20 1.19.2 - 1.0.4 instance and a server instance and the issue is present.

If I install only Integrated Dynamics, Forge and JEI in a single player world the issue does not persist.

I've attached three screenshots showing the issues with the fluids.

### Steps to reproduce

1. Open Jei
2. Search for "Menril Resin"
3. Menril Resins liquid does not appear.
4. Enter Creative mode
5. place a bucket of Menril Resin in the world
6. Name of the liquid still doesn't resolve.

### Expected behaviour

The liquids to be searchable and properly indexed.

### Screenshots

![2022-12-23_05 41 25](https://user-images.githubusercontent.com/29594386/209330453-23e8e9fc-4507-4f06-b8be-6d67eb638597.png)
![2022-12-23_05 41 29](https://user-images.githubusercontent.com/29594386/209330457-43502fa0-c5f4-4a33-83f6-3f3ac2349c7a.png)
![2022-12-23_05 41 39](https://user-images.githubusercontent.com/29594386/209330463-11c2953b-cf45-42c3-bbbf-04f5eee8e395.png)

**Comment by Saereth** [comment]
already reported to the mod authors,, the mods will get updated with fixes when released
