### ISSUE TITLE
Stoneblock 3 Client crashes on world join (Single and Mulitplayer)

### ISSUE THREAD

**Issue by Braastos** [FTBTeam/FTB-Modpack-Issues#2391]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

Latest Client Log: https://pste.ch/oqaxedemit.md
Latest Server Log: https://pste.ch/loyiqezezi.md

### Describe the bug

On Server or Local World Join the Client just crashes

### Steps to reproduce

1. Start Game
2. Join Server or Start Local World
3. Crash

### Expected behaviour

I expected to be able to play the game

### Additional information

Game was installed using PrismLauncher, because of Problems with the new FTB App in the past and i want to have all different Modpacks i play in one place

**Comment by tsjoe2** [comment]
I too am having this problem. Something in my main home is causing it to crash. If I load the game after updating, when I am somewhere else, ie; end city, it loads fine, but once I go back to my base it crashes. Hopefully this log is useful.  I am loading from the FTB App.
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10297727/debug.log)

**Comment by frankfraynk** [comment]
+1 this issue, at least 2 other people in discord are having this issue, here are my crash logs: https://hastebin.com/afojomuqeh.yaml

**Comment by HenriqueCaux** [comment]
Having the exact same problem too...

**Comment by ManInDark** [comment]
It is probably the same issue as #2404

**Comment by Raidobw2** [comment]
I'll close this in favor of keeping https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2404 as our way to track this issue.
There has been a proposed temporary fix at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2404#issuecomment-1364625915 by a user which I'd recommend to apply for those having AMD graphics cards such as RX 5700 XT

**Comment by Talidorn** [comment]
If you are running on AMD...

Open configs -> flywheel-client.toml

change:

backend = "INSTANCING"
to
backend = "OFF"
