### ISSUE TITLE
[With Fix] Failed to synchronize with server - Server version and my version of mod has the same version number

### ISSUE THREAD

**Issue by SirDeKay** [FTBTeam/FTB-Modpack-Issues#2392]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10295861/latest.log)

### Describe the bug

After 10 days of playing on this server I spontaniously get the following error:
Failed to synchronoze registry data from server, closing connection

Furter Details:
Mod versions do not match

Mod name:
Thermal Series

Server Version:
10.0.0.1

My Version
10.0.0.1

-> Server Reboot did not fix this
-> Personal Instance Reboot fix this problem (With the fourth try after the server reboot)

### Steps to reproduce

I did not changed anything
Server version and my modpack version is still on version 1.0.1

### Expected behaviour

Mod versions are the same, so there should be no problem

**Comment by Menolito** [comment]
I have this problem now, any way to solve this issue?

**Comment by SirDeKay** [comment]
I have rebootet the server and reopened my FTB instance a few times, after this the error was gone

**Comment by Saereth** [comment]
the new version of the pack uses an updated thermal version now so this should be resolved
