### ISSUE TITLE
Can’t put cows in jars

### ISSUE THREAD

**Issue by KippyTheSavage** [FTBTeam/FTB-Modpack-Issues#2393]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

Bedrock

### Describe the bug

I follow the instructions and YouTube videos to put the cows in the jars, the cow just ends up disappearing and the glass remains the same

### Steps to reproduce

Fix it

### Expected behaviour

Fix it so cows go in jars

**Comment by Gaz492** [comment]
I believe this issue has been fixed, if its still an issue for you do let us know by opening a new issue on our bedrock issue tracker https://github.com/FTBTeam/FTB-Bedrock-Issues
