### ISSUE TITLE
Chest partially invisible after updating to 1.5.0 and bee not dropping / going away

### ISSUE THREAD

**Issue by Nemelis** [FTBTeam/FTB-Modpack-Issues#2394]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

Today I updated to FTB Stoneblock 3 1.5.0.
When I started it I noticed 3 things:
1) The wooden chests are partially invisible (see attached screenshot). I can only see the top and when walking around the backside. It does not matter if it is a single chest or a double chest.
2) ~~Whenever I was cutting a tree at the start there sounded a whistle (did not retry yet since the tree did not regrow yet).~~ 
Solved. See comment @StarskyXIII 
3) ~~A Bee was there and I thought while investigating that I would be too slow so it would disappear, but it stayed put. So I dug up to it and it did not drop anything. The only way to get rid of it was to kill it.~~
Solved. See comment @KindarConrath 

### Steps to reproduce

Update from the previous stable version to 1.5.0 and open an existing game.

### Expected behaviour

1) For the chests I would expect to see the whole chest;
2) ~~I would not expect that annoying whistle to happen when I cut a tree~~
3) ~~For the bee I would expect that it disappears after a while / drops things and than disappears;~~ 

### Screenshots

![FTB_stone_block3_1 5 0 chest_bug](https://user-images.githubusercontent.com/35840579/209407210-a071bdcf-de1b-405d-b777-97d05f1b623b.png)

**Comment by Nemelis** [comment]
About the whistle: it is definitely linked to the growing of the tree, since whenever I bone meal it and want to do things with it the annoying whistle starts for a while whenever I do an action.

**Comment by KindarConrath** [comment]
The bee happens sometimes if the server shuts down while a bee is spawned. It looses its internal timer and won't despawn/drop items. Only option is to kill it.

**Comment by StarskyXIII** [comment]
Did you use FTB Ultimine to break the trees?
If you do, you need to tweak your key binding.
Whistle sound is from the luggage mod.
Because luggage mod also use grave key to call for luggage.

**Comment by MrMagicPenguin** [comment]
I can confirm the chest model does this on a fresh 1.5.0 install, not only when updating the pack from a previous version.

**Comment by Nemelis** [comment]
I had hoped that switching back from the standard minecraft X-mas box decoration would solve the issue with the partially visible chests, but it has not. So it seems pack related.

**Comment by StarskyXIII** [comment]
> I had hoped that switching back from the standard minecraft X-mas box decoration would solve the issue with the partially visible chests, but it has not. So it seems pack related.

Try to update your Flywheel to latest version.

**Comment by Nemelis** [comment]
> Flywheel?
Is that a mod? (Sorry not so saffy with mods)

**Comment by StarskyXIII** [comment]
> > Flywheel?
> > Is that a mod? (Sorry not so saffy with mods)

![Flywheel](https://user-images.githubusercontent.com/71606873/215913781-0de01cba-cabf-4f54-a768-ee8b2ca35098.png)

**Comment by Nemelis** [comment]
solved in 1.6.1
