### ISSUE TITLE
FTB Inferno crash

### ISSUE THREAD

**Issue by drkanbs** [FTBTeam/FTB-Modpack-Issues#2396]
### Modpack

FTB Inferno

### Modpack version

1.3.0 Beta

### Log Files

[crash-2022-12-23_19.51.09-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10297832/crash-2022-12-23_19.51.09-server.txt)

### Describe the bug

Just trying to, twerk with some sage that I just planted and it's crashed twice in a row now. 

Addendum from the below reproduction.
the other sage plant I planted next to it grew.  

### Steps to reproduce

Create a farm of sorts, use the rich dirt and plant sage.  

Attempt to mutandis (sp) the plant(s), I suggest multiple

If any simply vanish, try to plant the sage again and start to twerk. 

### Expected behaviour

The plant will grow, or mutandis works to a different plant

### Screenshots

can't I crashes to quickly for a screen.

**Comment by drkanbs** [comment]
[crash-2022-12-23_20.23.59-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10297869/crash-2022-12-23_20.23.59-server.txt)

It just crashed again, I wasn't trying to twerk this time.  

This time the mutandis, made the plant I was trying to mutate disappeared again.  Maybe that's the problem?  I can't play...it's like those many hours are just gone..

**Comment by orbidlo** [comment]
hexerei plats have this issue when twerking around them, its bee reported ages ago but no apparent fix has been found. workaroud is takig the plant out and maually replant it, which should set it's state properly and not crash when twerked
