### ISSUE TITLE
Smeltry Fluids not visible

### ISSUE THREAD

**Issue by dcvinyou2day** [FTBTeam/FTB-Modpack-Issues#2398]
### Modpack

FTB Inferno

### Modpack version

1.3.0

### Describe the bug

I just built a tinker's smeltry for the first time. 3x3x2. I put gold in there to make molds. I couldnt see the smelted gold in the smeltry or when it was being poured. I got my molds though. I tried again with a full tank of Iron Round Plates and noticed the same thing. I couldnt see the melted product and figured I would try pouring blocks instead. I could not see the pour but I did get the iron blocks. 

### Steps to reproduce

Build Smeltry
Place iron,copper,gold, etc in smelter.
No melted product visible.

### Expected behaviour

Ability to see fluids in the smeltry after the have been melted down

**Comment by drkanbs** [comment]
That is caused by the complimentary shader pack.  I turned them off and I could see the fluids coming out, as soon as I turned it back on the fluids disappeared.  I left it as the shaders look nice.  It's a bug in the shader, or something with the way it's rendering fluid.

**Comment by Saereth** [comment]
Set a hotkey to toggle shaders and just toggle them off when using the smeltery, seems to be the easist solution
