### ISSUE TITLE
Just Enough Resources

### ISSUE THREAD

**Issue by ToastedPlayz** [FTBTeam/FTB-Modpack-Issues#2399]
### Modpack

FTB Presents Direwolf20 1.19

### Is your suggestion related to a problem? Please describe.

A problem I'm having throughout my gameplay is the lack of knowledge of what levels ores spawn. With the new version of Minecraft, I haven't gotten a chance to learn just the vanilla ore spawn levels, but also the modded ore spawn levels. Finding Osmium within my world was painful. This issue does affect only the early progression of the pack before you get access to the Scanner from Scannable.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer

This is Just Enough Resources. It builds off of information from JEI and vanilla game mechanics to create new tabs for items. For example, to get prismarine shards it now shows mob drops, to get iron ore it shows a graph with how populated each Y-Level was with the ore. 

I've added the mod to my pack, and It's helped a ton, unfortunately, it only gives the ore spawn levels for vanilla ores (This is not a problem with most nether ores because the ore has the Y-Level in the Item's Lore). I'm not sure if custom ore generation is being used in the pack, but if it is, you can set the graphs to match the spawning levels for the ores. 

Unfortunately, the biggest problem with the mod is its built-in "profiling" feature gathers ore information across dimensions (Usage: /JRE_Profile [Count] [DimID,All]) isn't supported past 1.15. The mod author states in a [GitHub Issue](https://github.com/way2muchnoise/JustEnoughResources/issues/356) "I do want to re-implement, but I can't really invest the time needed at the moment to learn all the new world gen stuff. Trying to get around to it but just can't find the time :/". This does make the initial setup/config with the mod somewhat difficult.

The biggest pro of this mod is it helps with finding what all mobs can drop as well as vanilla ore spawn locations. The ore spawn locations are still really useful for early-game progression! The mob drops are good at all times, say you run across an item that doesn't seem to have a recipe and you cant figure out how to get it, it will tell you if it's a mob drop, if you can find it in any dungeon chest (including modded dungeons), or if it can be found naturally in the world.

**Comment by Saereth** [comment]
This mod is currently in a semi broken state, the profiling doesn't work and mob drops stop showing when you connect to a server. When the bugs get sorted I'll probably add it but until then we're just waiting
