### ISSUE TITLE
[Bug]: AmbientSounds audio quality for certain effects sounds terrible

### ISSUE THREAD

**Issue by benten2000** [FTBTeam/FTB-Modpack-Issues#240]
### Modpack

FTB OceanBlock

### Modpack version

1.5.0

### Describe the bug

Certain sound effects (weather ones it seems) from the included pack mod AmbientSounds from as soon as I load a map sound terrible, like it's even more compressed, tinny, slight robot effect to it.

### Steps to reproduce

1. Fresh modpack install from the FTB Launcher
2. Any map and play
3. Soon as you spawn it happens

### Expected behaviour

Normal sounding ambient effects

### Additional information

With the mod AmbientSounds disabled the problem goes away.
I have checked inside the AmbientSounds_v3.1.10_mc1.16.5.jar file to test the audio ogg files outside of Minecraft and they sound normal.
Most seen to playback fine ingame (tried some swimming) but the one I think that is causing the problem for me at least is assets/ambientsounds/sounds/wind/wind.ogg.

I managed to record a sample of the actual problem.
[FTB OceanBlock - Wind audio problem.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7470638/FTB.OceanBlock.-.Wind.audio.problem.zip)

**Comment by Sunekaer** [comment]
Is 1.6 of the pack better?

**Comment by benten2000** [comment]
Ah didn't check if a new version is out, shall try a fresh install and test now, thank you.

**Comment by benten2000** [comment]
Just tested with a clean 1.6.0 pack and sadly still the same with this weird and specific problem.

**Comment by Sunekaer** [comment]
Thanks for checking.
Could i get you to make an issue here? https://github.com/CreativeMD/AmbientSounds/issues
Just you have a much better understanding of the issue and knows how to recreate the issue

**Comment by benten2000** [comment]
Will do, thanks.
Tried a vanilla 1.16.5 with same forge version and only Ambient mod and seems to works fine there.
Shall do some more testing tomorrow as well to see if able to narrow it down.

**Comment by benten2000** [comment]
Reported this problem to the mod maker of Ambient and confirmed a bug on its end and has just been fixed for AmbientSounds_v3.1.11_mc1.16.5.jar

**Comment by Raidobw2** [comment]
> Fixed playing desert and ocean sounds at the same time (causing weird wind sound)
