### ISSUE TITLE
[Suggestion]: Add Showcase Item mod

### ISSUE THREAD

**Issue by StarskyXIII** [FTBTeam/FTB-Modpack-Issues#2400]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

This mod allows players to share their items in the chat, such like Quark does.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/showcase-item

**Comment by Sunekaer** [comment]
We are not looking to add anymore mods to this pack, thanks fo the suggestion tho :)
