### ISSUE TITLE
radiation mekanism

### ISSUE THREAD

**Issue by sqarezar** [FTBTeam/FTB-Modpack-Issues#2402]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

i made a mistake by breaking a radioactive waste barrel filled with spent nuclear waste. My whole wolrd is irradiated. I tried with the command /mek radiation RemoveAll but it didnt work. I crafted the hazmaz suit but i keep taking damage. i would like to delete the radiation without using backup.

thank you for that perfect modpack i love it !

### Steps to reproduce

1. fill a barrel with spent nuclear waste
2. break it

### Expected behaviour

i tough if i break a nuclear waste barrel it wont irradiate my wolrd

**Comment by tyler489** [comment]
/mek radiation removeAll
Try remove being lowecase
