### ISSUE TITLE
AE2 Wireless Craft Terminal becomes useless after trying and failing to create Mob Slaughter Factory block.

### ISSUE THREAD

**Issue by AochiToxx** [FTBTeam/FTB-Modpack-Issues#2403]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

https://drive.google.com/drive/folders/1AsFSyHqbpFRZNNT_-GiU0i-o41mfHtxA?usp=share_link

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10299012/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10299014/debug.log)

### Describe the bug

Was trying to make a "Mob Slaughter Factory" (MSF) via a AE2 "Wireless Crafting Terminal" (WCT) from REI recipe.

Once all the items for MSF are in the crafting 3x3 and normal left click to pick up the resulting MSF the item disappears from the mouse and the crafting window is closed automatically. Now right clicking the air with the WCT does nothing. I added my debug and console logs via google drive with open access and direct upload. Since pastebin couldn't contain everything.

I tried to find any errors when the original event happened, But I'm struggling to find anything identifying to that instance..

### Steps to reproduce

1. Have AE2 storage with items required for Mob Slaughter Factory.
2. have AE2 Wireless Crafting Terminal (fully charged).
3. lookup and select recipe for Mob Slaughter Factory via wireless crafting terminal.
4. click to pick up Mob Slaughter Factory, have wireless crafting terminal become useless and loose the Mob Slaughter Factory block.

### Expected behaviour

I would expect the AE2 Wireless Crafting Terminal to still be useable after successfully creating the Mob Slaughter Factory block.

**Comment by tyler489** [comment]
It didn't run out of power by chance did it?

**Comment by AochiToxx** [comment]
> It didn't run out of power by chance did it?

I wish that were the case. I've recorded a video on the broken terminal to show both that it has power and that it just does not want to work as expected.

https://youtu.be/FV2zHtNzB58

**Comment by AlexandrXamlo** [comment]
same issue

**Comment by DinnerBeef** [comment]
I am unable to reproduce this bug in my current dev version. Can you let me know if this is still happening for you on the current version?
