### ISSUE TITLE
Stoneblock 3 crashing after update from 1.4.3 to 1.5.0, cannot enter any world, instant crash

### ISSUE THREAD

**Issue by HenriqueCaux** [FTBTeam/FTB-Modpack-Issues#2404]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

https://gnomebot.dev/paste/1056220951773188167

### Describe the bug

The game opens, the world loads but 2 seconds after loading if crashes

### Steps to reproduce

1. Open FTB Launcher
2. Open StoneBlock 3 ( version 1.5.0 )
3. Open singleplayer
4. Enter world
5. Wait 
6. Crashes

### Expected behaviour

Being normally playable just like older version

### Additional information

My 1.4.3 world crashes when i enter it on 1.5.0, even a new world crashes when i open it, keeps popping up the error and if i downgrade the modpack, it works fine, but the newest version does not.

**Comment by ManInDark** [comment]
I have the same problem but I can add that there aren't any helpful information on the server side, as I wanted to play on a self-hosted server.

Log on server from time joined to disconnected: https://pastebin.com/EAUbwd59

Between points 4~6 I can see the world briefly before the client crashes.

**Comment by TreyR9** [comment]
I had a similar issue, hard crash with no crash file after a few seconds in the world. Resolved it by going to the flywheel-client config file and setting BACKEND to "OFF." Seemed to resolve the crash for me, I've heard on the web that it may have something to with AMD hardware.

**Comment by ASJoker** [comment]
> I had a similar issue, hard crash with no crash file after a few seconds in the world. Resolved it by going to the flywheel-client config file and setting BACKEND to "OFF." Seemed to resolve the crash for me, I've heard on the web that it may have something to with AMD hardware. Let me know if that helps!

Thanks mate :) friend of mine has this issue and he has an AMD. This config solved the issue for him <3

**Comment by Raidobw2** [comment]
https://github.com/Jozufozu/Flywheel/issues/166

**Comment by ChillyOnMC** [comment]
Same thing here, hoping a fix will come out soon. My friend was able to play with no problems but he's running a NVIDIA GPU.
I originally had a GTX 1060 but it died on me the other day, and I put in my spare AMD RX 570 and had no luck getting this modpack to load in. Crashes in Singleplayer & Multiplayer.

**Comment by SakYSakY** [comment]
does anyone know how to fix this crash ?
