### ISSUE TITLE
Villager trades and ore dict

### ISSUE THREAD

**Issue by red360** [FTBTeam/FTB-Modpack-Issues#2405]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

Villagers wont lose professions and immersive engineering villagers are offering air blocks as trades.
Thermal gold and silver nuggets that are generated by create washing but are not ore dict with occoltism or mekanism nuggets.

### Steps to reproduce

use create washing and try compacting gold and silver nuggets.
Trade with villagers.

### Expected behaviour

Villagers to cycle trades and not offer air blocks

**Comment by sharlin073** [comment]
having similar issue; happens for machinist, electrician, engineer- still can't figure out why
