### ISSUE TITLE
Durability Tooltip

### ISSUE THREAD

**Issue by HeavyDeception** [FTBTeam/FTB-Modpack-Issues#2406]
### Modpack

FTB Presents Direwolf20 1.19

### Is your suggestion related to a problem? Please describe.

This mod allows for Durability info without using the F3 menu and allows ppl to see how much a tool or time has left.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/durability-tooltip/files

**Comment by Saereth** [comment]
Good additions, added
