### ISSUE TITLE
Missing gregtech JEI recipes

### ISSUE THREAD

**Issue by tankirules** [FTBTeam/FTB-Modpack-Issues#2408]
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Describe the bug

I've noticed many items do not show up in JEI, such as the flint sword, knife, and for example, an emerald sword. You can see the crafting for the emerald sword head but not the actual sword itself. 

### Steps to reproduce

Search "Flint Sword"
There will be no results, but crafting a sword with two flint and a stick like a normal sword, will give you this pretty powerful fire aspect flint sword

### Expected behaviour

These recipes should show up in JEI when searched for

### Screenshots

![2022-12-25_23 47 28](https://user-images.githubusercontent.com/35437320/209468477-bf383fdf-691e-4b43-8f49-350985c69d82.png)
Here, the crafting is shown but it does not show up in JEI

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

We may have something up our sleeves, some may call it a remaster, keep an eye out on our social media platforms for more information.
