### ISSUE TITLE
MineColonies - Builder stuck at building Builders Hut

### ISSUE THREAD

**Issue by SirDeKay** [FTBTeam/FTB-Modpack-Issues#2409]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.1

### Describe the bug

Minecolonies (Theme: Warped Netherlands)

Two builder are trying to build the two distinct Builder Huts.
Both stuck at the same state.
They are standing at the positin shown in the first screen shot, or directly under the central building (hovering in the air in the moment)
If they are standing below this "block" the get teleportet out of the hole after ~1 minute.

There are no open requests for materials on both builders and both of them have a paxel and enough food.
------------------------
This could probably be a problem with the theme, because in the second minecolony on the server (Dark Oak Theme) there was no Problem with this

### Steps to reproduce

1. Use the wasted netherlands theme in minecolonies
2. Builder build the Builders Hut
3. Builder should stuck at some point after digging a hole

### Expected behaviour

Builder should not stuck by building the first / most important building

### Screenshots

Dug a hole and now stuck:
![Builder-Building State](https://user-images.githubusercontent.com/121033670/209479518-9862399b-e554-4ab7-81e7-86be4f22badb.jpg)

Command - mc citizen info
![Builder-MC_Citizen_Info](https://user-images.githubusercontent.com/121033670/209479528-10b0b8c9-9920-4902-a41d-19dc57eb3a88.png)

**Comment by Saereth** [comment]
new update has a update for minecolonies, see if its still occurring now. If so please reopen and provide your debug log and right click on the builder to show all open requests, thanks.
