### ISSUE TITLE
[Bug]: Immersive Engineering Improved Blast Furnace produces slag from Thermal Series

### ISSUE THREAD

**Issue by blenderisland** [FTBTeam/FTB-Modpack-Issues#241]
### Modpack

University

### Modpack version

1.16

### Describe the bug

Slag; Immersive Engineering Improved Blast Furnace produces slag from Thermal Series, and the slag is not interchangeable in the recipes for Slag Brick Block @Engineer's Decor. Can I fix this, so the Blast Furnace Produces Slag it originally does in Immersive Engineering?

### Steps to reproduce

Produce slag with Improved Blast Furnace. Use slag to create Slag Brick Block.

### Expected behaviour

Slag should be compatible or have different names.

**Comment by aaronhowser1** [comment]
```js
    recipe.replaceInput('immersiveengineering:slag','#forge:slag')
```
Fixed
