### ISSUE TITLE
Render issue in FTB University 1.16

### ISSUE THREAD

**Issue by SysToad64** [FTBTeam/FTB-Modpack-Issues#2411]
### Modpack

Other...

### Modpack version

1.7.0

### Log Files

[crash-2022-12-26_00.32.06-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10301782/crash-2022-12-26_00.32.06-client.txt)
[crash-2022-12-26_00.33.45-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10301783/crash-2022-12-26_00.33.45-client.txt)
[crash-2022-12-26_00.35.19-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10301784/crash-2022-12-26_00.35.19-client.txt)
[crash-2022-12-26_00.41.33-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10301785/crash-2022-12-26_00.41.33-client.txt)

### Describe the bug

Crash One: a ton of random textures replacing the player's skin,
a Couple seconds later, the world crashes.
Crash Two: Player Skin disappears, a Couple seconds later, the world crashes.

### Steps to reproduce

1. Do Nothing

### Expected behaviour

Render Messes up, Then the world crashes

### Screenshots

Second Crash: ![2022-12-26_00 40 56](https://user-images.githubusercontent.com/116862894/209508661-5d12eff8-4939-4530-9ca2-eec0d109dcc1.png) in 3rd person.

**Comment by NijaKing8** [comment]
Did you ever figure out the issue?

**Comment by Gaz492** [comment]
Does this issue still happen on the latest version of the modpack?
