### ISSUE TITLE
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by anik1ng** [FTBTeam/FTB-Modpack-Issues#2412]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Log Files

srv latest.log — [latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10304025/latest.log)
srv debug.log [debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10304026/debug.log)

client latest.log [latest.log.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10304034/latest.log.zip)
client debug.log [debug.log.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10304036/debug.log.zip)

### Describe the bug

I create new world and click "Open to Lan". Next step i try to connect with local network from one computer to second computer. Player connect to game, and momentally disconnect with error "Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException".

I try to connect with local network or minecraft together, and can't. Every try i got error.

### Steps to reproduce

1. Create new world.
2. Click "Open to Lan" or "Open to minecraft together"
3. From another PC try to connect to created world.
4. Got error "Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException".

### Expected behaviour

Play together over LAN with my son :)

### Screenshots

![Direwolf20 1 19 2022-12-26 22 41 07](https://user-images.githubusercontent.com/505388/209565351-fa643672-3381-4b47-accc-ec1f53a5dfb9.png)

**Comment by Saereth** [comment]
This should be resolved now in 1.4.0, I tested it on lan locally in my houshold with 2 other pcs, if you encounter the issue again please open a new issue with your updated version.
