### ISSUE TITLE
Server TPS gets really low then all players time out

### ISSUE THREAD

**Issue by bubbafett5611** [FTBTeam/FTB-Modpack-Issues#2413]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Log Files

https://pste.ch/wijinogoba.md - Server Latest.log

### Describe the bug

While playing on a server with a couple of other people the TPS will drop very low, the log gets spammed with the warning in the lastest.log then everyone times out. After the timeout, the TPS normalizes then everyone can connect again.

### Steps to reproduce

Happens at random.

### Expected behaviour

Players to be able to stay connected

**Comment by Saereth** [comment]
we'll need to see some profiling to try and diagnose this. Spark is included in the pack, please do some profiling and share the results when you recreate this

**Comment by bubbafett5611** [comment]
I unfortunately don't have the pack running on the server right now, but can swap it back and try to reproduce the issue.

**Comment by Saereth** [comment]
Thanks, that would be helpful, let me know what you find

**Comment by Al7778** [comment]
Having the same problem with TPS dropping real low, and the server either crashes or everyone gets kicked.
[2023-01-22-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10476226/2023-01-22-2.log.gz)
[crash-2023-01-22_11.19.38-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10476227/crash-2023-01-22_11.19.38-server.txt)
[crash-2023-01-22_11.25.09-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10476228/crash-2023-01-22_11.25.09-server.txt)

Not sure what else i need to add to this, and have no clue how to use spark mod.   Thanks

**Comment by FagSoft** [comment]
That's Hexerei causing a crash, [Al7778](https://github.com/Al7778). I recommend disabling the mod, as it's known to cause crashes with other mods as well. (Better Desert Temples and Twilight Forest in particular.)

Also, when the server lags like that. Did anyone open a chest that contained a treasure map?

**Comment by Al7778** [comment]
Sorry it took so long to reply, Real life got in the way.  To date i have Lowered render distance on the server, and updated the modpack to the latest version.  That has fixed the crashes.  Still getting a lot of timeout errors and everyone on the server gets kicked at the same time, but the server stays running.

**Comment by Al7778** [comment]
Also how do you disable a single mod in a modpack without screwing anything else up?

**Comment by Saereth** [comment]
hexerei doesnt have any specific compat requirements so you can just name the jar file .disabled. Yeah I've got an open issue with hexerei not much else I can do to fix this from a pack side. Will update as soon as Hex publishes an update
