### ISSUE TITLE
Mekanism infusion

### ISSUE THREAD

**Issue by ShadowBeastSW** [FTBTeam/FTB-Modpack-Issues#2414]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

I tried to automate the mekanism alloys but the metallurgic infuser (even the higher tier ones) does not accept the enriched items carbon/redstone/diamond.... when i tried to pipe into the machine (all the pipes/refined storage extractor/create chute/industrial foregoind item transporter).It Only allows me to put in manually the items.

### Steps to reproduce

put an item pipe between a chest and a metallurgic infuser
put iron ingots and enriched/regular redstone into the chest a stack of each
set the infuser side configs where the pipe connected to it to accept the items
cunfigurate the pipe with a wrench to pull the items out of the chest
if u look into the metallurgic infuser u will see the pipe only puts the iron into it

### Expected behaviour

Expecting to work properly

**Comment by tyler489** [comment]
The enrichment items have their own side color to be accepted, I believe it is purple? its the color of the box in the gui.
