### ISSUE TITLE
Simple Magnets Mod more control over what you pick up.

### ISSUE THREAD

**Issue by HeavyDeception** [FTBTeam/FTB-Modpack-Issues#2415]
### Modpack

FTB Presents Direwolf20 1.19

### Is your suggestion related to a problem? Please describe.

This is to fix a few things as it is there is no real way to filter or stop what you pick up with the other magnet choices this adds a way. This mod is one that as its name says really simple but does so much to make things easy and fast.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/simple-magnets

**Comment by Saereth** [comment]
good suggestion, approved
