### ISSUE TITLE
The error of compact machine preview

### ISSUE THREAD

**Issue by shivalli0623** [FTBTeam/FTB-Modpack-Issues#2416]
### Modpack

FTB StoneBlock 3

### Modpack version

1.3.0

### Log Files

[crash-2022-12-27_16.25.43-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10307224/crash-2022-12-27_16.25.43-client.txt)

### Describe the bug

Pipe of Pretty Pipes mod can't render on preview of compact machine.

### Steps to reproduce

Placing pipe of Pretty Pipes mod inner compact machine, back to overworld and opening the preview of compact machine.

### Expected behaviour

client crash

**Comment by jc2xs** [comment]
I can verify this bug also exists on the version 1.5.0 of the Stoneblock 3 mod pack.  I've opened a github issue with the authors for Compact Machines.

https://github.com/CompactMods/CompactMachines/issues/554

Here is the crash report: https://pastebin.com/y6J2CXYd

Versions:

- Forge: 1.18.2-40.1.92
- Compact Machines: 4.5.0
- Pretty Pipe: 1.12.8
- Java 17

**Comment by Saereth** [comment]
adding this here so I get notified when there is a fix
https://github.com/CompactMods/CompactMachines/issues/554
