### ISSUE TITLE
Not working Modpack

### ISSUE THREAD

**Issue by Balint20103** [FTBTeam/FTB-Modpack-Issues#2417]
### Modpack

FTB Sky Odyssey

### Modpack version

1.4.1

### Describe the bug

Since the new version (1.4.2) I can't start the game and sometimes it crashes my computer, I've tried redownloading and multiple things it doesn't seem to work 

### Steps to reproduce

1. Downgrade to 1.4.1
2. Start the game (press the play button)

### Expected behaviour

The game most likely going to stop at some mods, like: Just enough resources. And the game won't start even after waiting for one and a half hour.

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can take a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
