### ISSUE TITLE
Server crashes after FTB Backups runs

### ISSUE THREAD

**Issue by zziobro7** [FTBTeam/FTB-Modpack-Issues#2418]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Log Files

https://pste.ch/iwaqowewez.cs

### Describe the bug

Upon successful run of FTB backups the server crashes. Our current backup save size is 0.7 GB/

### Steps to reproduce

Auto FTB backup runs
According the server console it successfully saves the backup archive
The server then crashes with the above log

### Expected behaviour

FTB Backups does not crash the server

### Screenshots

Computer information: https://imgur.com/a/cp56omV

**Comment by FagSoft** [comment]
You can circumvent this issue by increasing the max-tick-time in the server.properties.

The slower your hardware (CPU + disk), the higher the value needs to be. I would recommend setting it to 10 minutes (add an extra 0 to the value), then see how long the backup runs for. Then add a minute to that time, and you should be fairly future proof.
