### ISSUE TITLE
Items of the same are not stacking

### ISSUE THREAD

**Issue by Lloydsanity** [FTBTeam/FTB-Modpack-Issues#2419]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

when mining gold ore with a pickaxe it will go into my inventory fine. if i mine thew same thing with a laser, it will create a new stack and will noit merge.

### Steps to reproduce

1. mine gold ore with pickaxe
2. mine gold ore with laser
3. 2 different stacks will be created

### Expected behaviour

fix??

### Screenshots

![Untitled](https://user-images.githubusercontent.com/121529320/209747315-43994b95-19a7-41e7-a3d5-0e740cfebeba.png)
![Untitled1](https://user-images.githubusercontent.com/121529320/209747324-02b6c00c-2910-4e26-846b-d181f572f716.png)

**Comment by TheVekter** [comment]
Does your Mining Laser have the Magnet Upgrade on it?

**Comment by Lloydsanity** [comment]
Yes it does

**Comment by TheVekter** [comment]
I didn't notice this same behavior with mine, but I was mining zinc ore, not gold.

**Comment by Lloydsanity** [comment]
I haven’t checked it since I have transitioned into the ME system from AE2

**Comment by Saereth** [comment]
I'm unable to reproduce this now after the update to 1.1.0, please update and open a new issue if you can reproduce this afterwards
![image](https://user-images.githubusercontent.com/9200909/212445697-745f48e2-3686-41fb-8114-d8f68ca5eedf.png)
