### ISSUE TITLE
[Bug]: Game Crashing when trying to load World

### ISSUE THREAD

**Issue by CerealHydra137** [FTBTeam/FTB-Modpack-Issues#242]
### Modpack

FTB Sky Odyssey

### Modpack version

1.12.2

### Describe the bug

Whenever I try to load my world it crashes. This wasn't happening yesterday or even a few hours ago. It starts loading the terrain and then crashes and goes back to the minecraft launcher.

### Steps to reproduce

I honestly don't even know.

### Expected behaviour

I expected it to let me play my world but it just keeps kicking me over and over.

**Comment by Raidobw2** [comment]
Try and restore a backup from your `backups` folder. You'll lose a bit of time played but your world will be playable again.

Also add your crash log here if you can. This way I can look at it and tell you what caused it, or if there are things to avoid or update.

This modpack is not currently updated, so this "bug" if it is one might stay, so it might be valuable info to you to know what caused it.

You can access the modpack's folder in the FTB App if you are using it, in Settings of the modpack.
Backups are in `backups`, you extract a zip it gives you a world.
Crash logs are in `crash-reports`, they are text files.

Thanks in advance

**Comment by moosetwin0** [comment]
Still a problem, been having this with Stoneblock 2 as well, making a new world/loading backup doesn't work either.

**Comment by TheonlyTazz** [comment]
Closing issue. Reporter has failed to supply Crash-logs.
