### ISSUE TITLE
Whistle luggage to stay crashes game

### ISSUE THREAD

**Issue by Nemelis** [FTBTeam/FTB-Modpack-Issues#2421]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

[crash-2022-12-28_22.25.44-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10316563/crash-2022-12-28_22.25.44-client.txt)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10316564/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10316565/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10316566/latest.log)
[rei.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10316567/rei.log)
[rei-issues.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10316568/rei-issues.log)

### Describe the bug

When "telling" Luggage to stay put the game crashes

### Steps to reproduce

1. Have Luggage follow you
2. Whistle that it should stay
--> game crashes.

### Expected behaviour

Luggage stays and you can continue playing

**Comment by Archangel784** [comment]
Getting the same behaviour. 
Issue occurs in single player and in LAN worlds.

Changed keybind to an unbound key, I dunno, was taking a shot in the dark and hadn't scanned the crash logs for an idea what was happening. Here's my crashlog although it looks very similar to Nemelis' one.
[crash-2023-01-07_11.21.38-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10365105/crash-2023-01-07_11.21.38-client.txt)
