### ISSUE TITLE
Crashing on World Creation

### ISSUE THREAD

**Issue by MeridiasBeacon** [FTBTeam/FTB-Modpack-Issues#2422]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

[Minecraft log.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10317227/Minecraft.log.txt)

### Describe the bug

After pressing the "Create New World" button, the game states that a new world is being created, then the game freezes, then crashes.

### Steps to reproduce

1. Click "Play" button
2. click SINGLEPLAYER
3. Click Create New World

### Expected behaviour

Game creates new world and I can play the modpack.

### Additional information

One of the first warnings in the log states that my Minecraft 1.18.2-40.1.92 file is missing the mods.toml file in case that may be the issue.

**Comment by Talidorn** [comment]
If you are running on AMD...

Open configs -> flywheel-client.toml

change:

backend = "INSTANCING"
to
backend = "OFF"

**Comment by MeridiasBeacon** [comment]
> 
Thank you for the reply, I am not using AMD and have tried this and it didn't change the outcome.

**Comment by erne8644** [comment]
Thanks alot. After BIOS update, Changed procesor from Ryzen 5 1400 To Ryzen 7 5800X and new windows instal had same problem.
