### ISSUE TITLE
Disable Carryon working on chipped doors

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#2423]
### Modpack

FTB Inferno

### Modpack version

Any

### Describe the bug

https://discord.com/channels/372448486723158016/1024733922745122897/1057880170356277259

Chipped doors need to be blacklisted from carryon as they cannot be placed once picked up.

### Steps to reproduce

Try to carry door

### Expected behaviour

Blacklist doors so they don't get picked up.

**Comment by Saereth** [comment]
This is a misconfiguration of the client/server files, carryon works on a whitelist only setting and those doors are not white listed. Grab the carryon config from /defaultconfigs and replace the one in your saves/savename/serconfigs if singleplayer or world/serverconfigs/ if multiplayer and it should have the proper whitelist again.

New installations of the pack shouldnt have this issue anymore bu tthere was an update where this manual intervention was required and there were instructions on the patch notes.
