### ISSUE TITLE
Breeder not displaying "!" from Chickens Mod

### ISSUE THREAD

**Issue by GodzArchAngel** [FTBTeam/FTB-Modpack-Issues#2424]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

Whenever a chicken gets done breeding (2 chickens in the input and 1 chicken in the output) and there is no seeds the "!" doesn't appear on the breeder. Whenever I go into it and move it so there is 2 chickens in the input and 0 chickens in the output and 0 seeds in the breeder the "!" will appear.

### Steps to reproduce

1. Place Breeder
2. Insert 2 chickens into input (the "!" appears)
3. Add seed into breeder
4. Breeding finishes
5. No "!" is displayed
6. Remove chickens in output (the "!" will appear)

### Expected behaviour

When breeder finishes the breeding process the "!" appears when no seeds are in seed input

**Comment by DinnerBeef** [comment]
Reported Issue: https://github.com/CreeperHost/Chickens/issues/56

**Comment by UnRealDinnerbone** [comment]
This issue has been fixed
