### ISSUE TITLE
FTB Stoneblock 3 1.5.1 suggested release with single change to fix AMD users crashing issues.

### ISSUE THREAD

**Issue by Talidorn** [FTBTeam/FTB-Modpack-Issues#2425]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

AMD users having crashes due to flywheel setting.

### Steps to reproduce

Load 1.5.0 on an AMD system.
Start any world (saved or new) in SSP.
Crashes.

### Expected behaviour

Game starts

### Additional information

Upgrade pack to 1.5.1 with a single change:

Open configs -> flywheel-client.toml

change:

backend = "INSTANCING"
to
backend = "OFF"

**Comment by Raidobw2** [comment]
Hi, thanks for reporting, we're currently tracking this at https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2404. I'll doublecheck with my colleagues if this has been handled in-dev for 1.5.1 already or if it still needs to be applied.
I will close this issue to avoid duplicates, so please feel free to subscribe to the mentioned issue above to get notifications when this is fully sorted out
