### ISSUE TITLE
Ingredients of Longbow of the Heavens can't be moved to Extreme Crafting Table by REI

### ISSUE THREAD

**Issue by StarskyXIII** [FTBTeam/FTB-Modpack-Issues#2428]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

https://mclo.gs/9Zoo1T7

### Describe the bug

When I try to make a Longbow of the Heavens, I open the Extreme Crafting Table,
favorite the recipe in REI, click the [+] button at the bottom right, and get the following error:
``[CHAT] Internal Error: Cannot invoke "blusunrize.immersiveengineering.common.register.IEItems$ItemRegObject.m_5456_()" because the return value of "java.util.Map.get(Object)" is null``

### Steps to reproduce

1. Open the Extreme Crafting Table
2. Click the [+] button at the bottom right recipe
3. Get error messege at the chat

### Expected behaviour

I can move items from my inventory to the Crafting Grids of Extreme Crafting Table.

### Screenshots

![image](https://user-images.githubusercontent.com/71606873/210058477-84c5cd31-819c-4bdb-b98e-a908452e7414.png)

![image](https://user-images.githubusercontent.com/71606873/210057702-282015b7-7581-4a16-9c5a-0349634556de.png)

### Additional information

Already report to IE , see https://github.com/BluSunrize/ImmersiveEngineering/issues/5516

**Comment by Sunekaer** [comment]
Should be fixed in the newest version of the pack
