### ISSUE TITLE
Crash related to the item display of a refined storage pattern. 

### ISSUE THREAD

**Issue by Dooblin** [FTBTeam/FTB-Modpack-Issues#2429]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

When attempting to show the item display of a refined storage pattern, I am met with a game crash. This ONLY happens with items related to CC:Tweaked. The item that the pattern is crafting is displayed when crouching or placing the pattern into a crafter. A crash happens the instant a CC:Tweaked item is displayed on any pattern in the UI.

### Steps to reproduce

1. Apply a CC:Tweaked recipe to a Refined Storage Pattern.
2. Display the image of that pattern in any way. (Either by pressing the crouch button or putting the pattern in a crafter.)

### Expected behaviour

The game crashes when recreating this bug. 

### Additional information

I only tried this with two recipes from the mod, but I imagine there are more that will crash the game. The game crashed with the following recipes: Felling Turtle and Turtle. Both of these items involved the Turtle from CC:Tweaked, so I imagine it is that item which is causing problems.

**Comment by Saereth** [comment]
This should be resolved now, if you experience it in 1.4.0 update please open a new issue and provide a crash log
