### ISSUE TITLE
Cannot create bedrock with arcane ashes.

### ISSUE THREAD

**Issue by JuanNicholas** [FTBTeam/FTB-Modpack-Issues#2437]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Describe the bug

There are several recipes in REI that indicate you can make bedrock using arcane ashes.  I tried each of them at least twice to one of two results: 1) ashes activate and the animation completes with no results or 2) ashes activate and animation continues for greater that 10 minutes.

### Steps to reproduce

1. Acquire arcane ashes & (2) coal.
2. Activate arcane ashes with coal twice.
3. Watch for a result of nothing.

### Expected behaviour

One bedrock to appear at the end of the animation.

### Screenshots

Empty Ashes) ![2022-12-31_10 04 47](https://user-images.githubusercontent.com/121730152/210152163-70493579-573d-4c77-8a74-1eb72b18eedf.png)
Ashes with 1 coal) ![2022-12-31_10 05 34](https://user-images.githubusercontent.com/121730152/210152203-71e15f85-8f47-4cf7-8427-ec8c6d6a484e.png)
Results) ![2022-12-31_10 06 00](https://user-images.githubusercontent.com/121730152/210152227-9f1d5d59-cfc2-49c0-91ad-2d18194d7999.png)
REI w/ recipe) ![2022-12-31_10 10 19](https://user-images.githubusercontent.com/121730152/210152239-a79acf5e-61df-4595-9791-f53768dc9d8c.png)

**Comment by DinnerBeef** [comment]
See Issue: https://github.com/WayofTime/BloodMagic/issues/1938

**Comment by LandofHeros2234** [comment]
These are all effect recipes, they don't actually give bedrock, but instead do different things when touching the array. If you hover over the [!] button it will tell you the recipe id which describes the effect.

**Comment by UnRealDinnerbone** [comment]
Closing this issue as the mod issue has been open since April, without any update
