### ISSUE TITLE
Brass Chicken Is Uncraftable.

### ISSUE THREAD

**Issue by magerooster** [FTBTeam/FTB-Modpack-Issues#2438]
### Modpack

FTB Sky Odyssey

### Modpack version

1.4.2

### Describe the bug

The recipe for the brass chicken is using the wrong kind of brass. The rest of the pack seems to be using Alchemical Brass from Thaumcraft for recipes, but the chicken recipe is expecting TechReborn brass (which is otherwise disabled).

### Steps to reproduce

Attempt to craft a brass chicken by any method in single player or multiplayer.

### Expected behaviour

Getting a  brass chicken

**Comment by ngschaider** [comment]
Can confirm this. One solution would probably be to change the brass chicken recipe to use Ore Dictionary names (ingotBrass)
