### ISSUE TITLE
ATM 7 to the sky chest crash

### ISSUE THREAD

**Issue by QuartzDr4gon** [FTBTeam/FTB-Modpack-Issues#2439]
### Modpack

Other...

### Modpack version

1.18.2

### Describe the bug

The game crashes when any 'vanilla' chest comes into render. Reproduceable every time. Top part of chest is rendered correctly, bottom part is invisible. This is game breaking 100% and stops any progression without cheating. Cannot go into the Twilight Forest, crash. Cannot go into the end, crash.

### Steps to reproduce

Place chest into the world.

### Expected behaviour

Chest render properly and game not crash

### Screenshots

![chestbug](https://user-images.githubusercontent.com/121739615/210159501-c2478382-1af6-4262-9ddb-9d7c9ed223e1.png)

### Additional information

 I believe this issue has to do with the holiday themed Mojang chest skin.

**Comment by simon1342** [comment]
got the same problem

**Comment by manmaed** [comment]
this is not a FTB Pack
