### ISSUE TITLE
direwolf2- 1.19.2 1.04beta constant crashing.

### ISSUE THREAD

**Issue by gzcwnk** [FTBTeam/FTB-Modpack-Issues#2440]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4beta

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10328279/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10328280/debug.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10328283/console.log)

### Describe the bug

Crashes every few minutes

### Steps to reproduce

no idea

### Expected behaviour

doesnt crash

### Additional information

Tried increasing to 9gb of ram

**Comment by gzcwnk** [comment]
[crash-2022-12-31_21.13.10-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10328287/crash-2022-12-31_21.13.10-server.txt)
[crash-2022-12-31_21.26.31-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10328288/crash-2022-12-31_21.26.31-server.txt)
[crash-2023-01-01_08.31.46-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10328289/crash-2023-01-01_08.31.46-server.txt)
[crash-2023-01-01_09.30.23-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10328290/crash-2023-01-01_09.30.23-server.txt)
[crash-2023-01-01_12.55.58-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10328291/crash-2023-01-01_12.55.58-server.txt)
[crash-2023-01-01_13.02.03-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10328292/crash-2023-01-01_13.02.03-server.txt)
[crash-2023-01-01_17.22.28-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10328293/crash-2023-01-01_17.22.28-server.txt)

**Comment by VenxSavior** [comment]
Im having the same issues, any fix yet?
[crash-2023-01-03_00.06.53-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10333847/crash-2023-01-03_00.06.53-server.txt)

**Comment by gzcwnk** [comment]
Sadly no, no ideas.  I have tried googling the errors and got no reply  I will go look at upgrading java in a minute. Also annoyed the FTB client upgraded me to a beta without warning me so also.

**Comment by gzcwnk** [comment]
On java 8 351 which is the latest  :(

**Comment by gzcwnk** [comment]
You are using,  "Java Version: 17.0.1, Eclipse Adoptium"  I am on,

"Java Version: 17.0.2, Eclipse Adoptium"  it seems so I have upgraded to 17.0.5, testing

**Comment by gzcwnk** [comment]
"17.0.5, testing" crashed inside 1min.  :(

**Comment by gzcwnk** [comment]
1.8.0_351, testing.  nope wont load at all  :(

**Comment by gzcwnk** [comment]
temurin 1.8.0_312, testing nope wont load at all :(

**Comment by VenxSavior** [comment]
issues was fixed by disabling fast leaf decay and ftbchunks, starting the server, logging in, closing the server, re-enabling ftbchunks and that fixed it

**Comment by gzcwnk** [comment]
"issues was fixed by disabling fast leaf decay and ftbchunks"

how is this done?
