### ISSUE TITLE
Bits Spawner - Causing unplayable lag.

### ISSUE THREAD

**Issue by 89gsc** [FTBTeam/FTB-Modpack-Issues#2442]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0 (Older also) 

### Log Files

https://spark.lucko.me/0Sxv9sH1a8

### Describe the bug

When myself or other players go to Nether dungeons (this is where we see these most often) and we get near "Bits Spawners" these appear to be spawning champions which create a huge amount of lag so much that it actually becomes very difficult to tackle these areas. 

### Steps to reproduce

Go near a bits spawner, log the time its taking ticks to happen etc and see the impact the champions spawning has. 

### Expected behaviour

Not lag to the point you end up dying without being able to do anything

### Screenshots

![image](https://user-images.githubusercontent.com/1032459/210177506-ea6f76e3-43e8-4cb7-b97e-fea3d5b058b0.png)

**Comment by UnRealDinnerbone** [comment]
We are unable reproduce this on our end, if you this still happening on the latest version please reopen the issue with a new spark report
