### ISSUE TITLE
Stoneblock 3 won't load

### ISSUE THREAD

**Issue by Ov3rk1ll76** [FTBTeam/FTB-Modpack-Issues#2443]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

[crash-2023-01-01_18.52.38-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10329890/crash-2023-01-01_18.52.38-client.txt)

### Describe the bug

When I start loading the modpack, it goes through the initialization and then says "Instance Failure" in red box on lower right side of screen. 

### Steps to reproduce

1. Open FTB App
2. Go to FTB StoneBlock 3 1.5.0
3. Start App

### Expected behaviour

Expected to load up

### Screenshots

![image](https://user-images.githubusercontent.com/121778747/210192232-0bb8b184-d0a3-4602-a93d-4b16ad77cb43.png)

**Comment by DanielSeldura** [comment]
There's a fix in the comments for #2404 , might be able to help you if you are running AMD

**Comment by Raidobw2** [comment]
I'll update MineTogether, this might fix the issue. The patch notes for MineTogether are as follows:

> Fix Crashes on the public server listing screen.
> Fix issues with the new user gate not working, having missing buttons, or buttons under the grey-out.
> Fix issues with Connect failing to get the closest server.

Side note: the flywheel issue will be fixed as well
