### ISSUE TITLE
World getting stuck at 100% load

### ISSUE THREAD

**Issue by LilMxPlagueRat** [FTBTeam/FTB-Modpack-Issues#2446]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

https://pastebin.com/erP8GcrA

### Describe the bug

I can load the instance just fine, and I can create new worlds perfectly fine and play in them, however if I try to load my previous save from before the update once the World Loader screen reaches 100% it will seem to try to load the World twice more before stopping responding. I receive no error messages nor am I told that Java has stopped responding. I do however get a message saying "Can't keep up! Is the server overloaded?" in the log starting the moment it stops responding, despite having more than adequate RAM available (having set Instance Memory to 9.06 GB).

### Steps to reproduce

1) Click Play on Instance.
2) Wait for Instance to Load
3) Click Singleplayer
4) Select World
5) Wait for World to Load
6) Stops Responding before World can Load

### Expected behaviour

World should load once load percentage reaches 100

### Screenshots

![image](https://user-images.githubusercontent.com/23294423/210328812-024a14ac-6aa7-47a5-b751-8ac987173a8b.png)

### Additional information

Things I have tried:
Optimising the world in the edit section
The fix suggested in #2404 of going into the flywheel-client config file and setting BACKEND to "OFF"
Updating Java
Updating Drivers
Loading putting the world save into a new instance
Upping and lowering the Instance Memory
Waiting 8 hours to see if it eventually loaded

I have also noticed that the frame rate on my other worlds is very low

**Comment by UnRealDinnerbone** [comment]
Please also upload your debug log. And since this seems to be tied to a world, it also helps if you upload your world, so we can try and track down the issue
