### ISSUE TITLE
Stone block crashing evertime

### ISSUE THREAD

**Issue by th3uszin** [FTBTeam/FTB-Modpack-Issues#2448]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

stone block suddenly crahs same i reinstalled the app and restar the PC

### Steps to reproduce

1. open the FTB app
2. click to open stone block 3
3. whait show the stone block 3 icon in taskbar
4. error end close the game

### Expected behaviour

oppen the game for me continue playing normaly

### Screenshots

![Captura de tela 2023-01-03 162637](https://user-images.githubusercontent.com/121897603/210427368-a40b9b33-c4f2-43d2-92e1-5319257fc5b9.png)

### Additional information

before the update never it happened this error

**Comment by UnRealDinnerbone** [comment]
Please upload crashlog
