### ISSUE TITLE
"World Breaker" can't break Dark Matter Pedestals

### ISSUE THREAD

**Issue by neldridge** [FTBTeam/FTB-Modpack-Issues#2450]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

I cannot break a Dark Matter pedestal with the World Breaker but I can with a Red Matter Pickaxe

### Steps to reproduce

1. Place a Dark Matter pedestal
2. Attempt to break with World Breaker

### Expected behaviour

World Breaker should break Dark Matter pedestals, since it's made with a red matter pickaxe-- and it can.

**Comment by UnRealDinnerbone** [comment]
World breaker is not meant to break those blocks

**Comment by neldridge** [comment]
Uh huh
