### ISSUE TITLE
Crash When loading up a world

### ISSUE THREAD

**Issue by ItsChase7** [FTBTeam/FTB-Modpack-Issues#2451]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

Everytime i try to load my world it crashes.

### Steps to reproduce

1. Load modpack
2. click on world
3. game crashes

### Expected behaviour

it to load up world

**Comment by QuartzDr4gon** [comment]
Same thing happened to me on stream just now. Sad day man, was looking forward to playing this pack.

**Comment by APotocar** [comment]
I also experienced the same issue, happened after updating from v1.4.3 to v1.50.

Seems to be a certain block/interaction in the world causing a crash. World starts up normally if you downgrade back to 1.4.3 

Attaching my crash report too: 
[hs_err_pid11232.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10385271/hs_err_pid11232.log)
