### ISSUE TITLE
Crash while making framed drawers (with Chipped blocks)

### ISSUE THREAD

**Issue by castel-int** [FTBTeam/FTB-Modpack-Issues#2452]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

[crash report.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10342168/crash.report.txt)

### Describe the bug

i am not sure how the bug comes to be since i dont have the knowledge to make mods.

### Steps to reproduce

create framed drawer.
take two blocks and try giving the framed drawers textures

### Expected behaviour

it should crash as soon as you place the framed drawer in the recipe of giving it  a texture

**Comment by UnRealDinnerbone** [comment]
An Update has been released since this issue was made. Can you please confirm this issue, it's still happening?
