### ISSUE TITLE
Client crash when placing comparator on altar with bloodstone block

### ISSUE THREAD

**Issue by neldridge** [FTBTeam/FTB-Modpack-Issues#2454]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

https://pste.ch/masinasuve.md

### Describe the bug

Created a second blood altar to use bloodstone block to get redstone for LP. After placing comparator, game crashes.

After reloading the comparator appears to be working (power is displayed accurately) but if I interact with the comparator the game will crash again.

Breaking the comparator does not cause a crash.

### Steps to reproduce

1. Place bloodstone block
2. Place altar
3. Place archmage orb into altar
4. Place redstone comparator facing away from altar

### Expected behaviour

Game doesn't crash.

### Screenshots

![image](https://user-images.githubusercontent.com/720437/210565054-63a87781-446a-4d6c-97b4-e6be5ec77130.png)

I broke the comparator to use laser io here but it was placed in the same area.

### Additional information

I suspect the issue is related to the NPE in the attached logs.h
My server continues to run fine during this, it's only aa client side issue.

**Comment by Raidobw2** [comment]
Thanks for reporting

**Comment by UnRealDinnerbone** [comment]
Close this issue as the mod issue has been open since January, without any update
