### ISSUE TITLE
Cyclic item cable into AE2 inscriber dupes stacks

### ISSUE THREAD

**Issue by 2called-chaos** [FTBTeam/FTB-Modpack-Issues#2455]
### Modpack

FTB Endeavour

### Modpack version

1.9.0

### Describe the bug

The item cable manages to put a stack-1 into the inscriber whilst retaining stack-1 in the inventory resulting in easy and immensely broken item duplication (as it accepts any item). This behaviour does not occur with the AE2 Charger which also only accepts single items.

### Steps to reproduce

inventory -> cyclic item cable (pulling out of inventory) -> AE2 Inscriber

Demo: https://www.youtube.com/watch?v=dPbqqYb8uTU&t=48s

### Expected behaviour

no duplication

**Comment by manmaed** [comment]
This issue is stale
