### ISSUE TITLE
Mining laser volume not retained

### ISSUE THREAD

**Issue by Tyranical** [FTBTeam/FTB-Modpack-Issues#2456]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

The mining laser custom volume slider setting is not saved. Lowering the volume below 100 does not change the volume at all unless the tool is set to have 0 volume, then it is silent.

### Steps to reproduce

Create a mining laser
Shift + right click
Lower volume to 1
Exit menu
Mine (should be loud)
Re-open the menu
See volume is reset to 100

### Expected behaviour

Volume level is retained

**Comment by TheVekter** [comment]
Replicated here as well.

**Comment by Saereth** [comment]
https://github.com/Direwolf20-MC/MiningGadgets/issues/203

**Comment by schmintendo** [comment]
This also happens in AllTheMods 8
