### ISSUE TITLE
Instance crashed

### ISSUE THREAD

**Issue by Emadomenica** [FTBTeam/FTB-Modpack-Issues#2457]
### Modpack

Direwolf20 1.4.7

### Modpack version

5.3.2

### Describe the bug

First of all, sorry for my english, it's not my mother tongue. I just found this old modpack, and wanted to play it. After downloading it, as I tried to run it, the instance crashed. I retried a couple of times, also the offline option, but had the same result. I don't know anything about the codes that appear on the screen, therefore I have no clue about what to do. Thanks in advance. 

### Steps to reproduce

Open FTB App
Go to the section "Browse"
Type "Direwolf20 1.4.7"
Click on "Install", then again "Install"
Click on "Play"

### Expected behaviour

I expect an explaination of what I have to do in order to play this modpack

### Screenshots

![screen_ftb_1 4 7](https://user-images.githubusercontent.com/121980031/210650864-833ef7d9-debf-4f60-a8df-a99a44d0614f.png)

### Additional information

I don't know if this will be useful, but I have Windows 8.1, 8 GB of RAM, and have also another modpack launcher, called "Technic Launcher". I actually don't know if these are problematic.

**Comment by manmaed** [comment]
noting that this is an old modpack so it may not be fixed can you please supply the latest and debug logs as well as the hs_err log
