### ISSUE TITLE
Occultism Crusher Demon not working

### ISSUE THREAD

**Issue by tantalum8516** [FTBTeam/FTB-Modpack-Issues#2458]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4

### Describe the bug

When I summon the Foliot of crushing from Occultism it will not pick up ores to crush them when they are dropped near by. If I give the foliot the ore by shift right clicking it will just throw the ore onto the ground. It does this with both ore "block" form and in the "raw" chunk form.

### Steps to reproduce

Summon Foliot for crushing give it ore

### Expected behaviour

Should crush the ore into dust

**Comment by TheVekter** [comment]
Replicated for me as well. It'll chew on Occultism Silver but not on any of the Mekanism ores at the very least. It'll also eat End Stone into Crushed End Stone, which is good considering that there's literally no other way to get it in this pack.

So it looks like the default Occultism recipes work fine, but it won't actually process any other ores.

**Comment by Saereth** [comment]
I'm not having any luck reproducing this after the update
![image](https://user-images.githubusercontent.com/9200909/212444735-00ba6e55-aba8-4a90-a9e3-09cc4e90eed3.png)
