### ISSUE TITLE
Crimson Ladder Automation

### ISSUE THREAD

**Issue by ZerosLab** [FTBTeam/FTB-Modpack-Issues#2459]
### Modpack

FTB Inferno

### Is your suggestion related to a problem? Please describe.

Carpenter currently cannot learn recipe to convert KubeJS crimson ladders to Quark crimson ladders. This makes nether miners quite inconvenient. Adding such a recipe would make life that much easier.

**Comment by Saereth** [comment]
any of the 2x2 crafters (builders and such) can learn the conversion recipe, teach it to one of them.
