### ISSUE TITLE
[Bug]: Crystal Shard Essence: Missing Recipe for Botany- / FTB Power Pots

### ISSUE THREAD

**Issue by Bountyx0** [FTBTeam/FTB-Modpack-Issues#246]
### Modpack

FTB Oceanblock

### Modpack version

1.6.0

### Describe the bug

You can't produce crystal shard essence through Power Pots/Botany Pots because of a missing recipe.

### Steps to reproduce

1. Try to put crystal shard seed on a Botany/Power Pot

### Expected behaviour

Seed reproduce essence through pots

**Comment by Raidobw2** [comment]
For dev: The essence, notice one recipe tab to make it:
![image](https://user-images.githubusercontent.com/17010632/140441019-c70de271-ca3a-43fc-8960-8f317f47d7fb.png)
![image](https://user-images.githubusercontent.com/17010632/140441218-04028d5b-8d4d-4322-866f-f70657cec348.png)
`'64x mysticalagriculture:crystal_shards_essence'`
The seed for that essence:
![image](https://user-images.githubusercontent.com/17010632/140441043-26a23a8e-86a4-4289-a54e-c125d6f42356.png)
`'64x mysticalagriculture:crystal_shards_seeds'`
`'#mysticalagriculture:seeds'`
You can still plant them like normal seeds and you do get essence, but that's a bit broken, the texture is not there?
![image](https://user-images.githubusercontent.com/17010632/140441482-3f56ad1b-3e77-411b-bb73-3bd578c089ff.png)
![image](https://user-images.githubusercontent.com/17010632/140441576-c9c3370c-7164-4210-8b65-9b05ec0e00b0.png)
`mysticalagriculture:crystal_shards_crop`
`#mysticalagriculture:crops`
</br>
An example with a good essence, iron essence:
![image](https://user-images.githubusercontent.com/17010632/140441166-406e5af6-e344-46b7-97d0-d812f98bc774.png)
