### ISSUE TITLE
Client Crash (presumably due to laser.io rendering)

### ISSUE THREAD

**Issue by Nandez22** [FTBTeam/FTB-Modpack-Issues#2460]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

[crash-2023-01-05_00.33.14-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10349916/crash-2023-01-05_00.33.14-client.txt)
[crash-2023-01-05_00.04.53-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10349917/crash-2023-01-05_00.04.53-client.txt)
[crash-2023-01-04_23.59.28-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10349918/crash-2023-01-04_23.59.28-client.txt)

### Describe the bug

While working on a farm another person on the server copied and pasted a farm tile that included laser.io elements. Upon setting a pipe to extract from a source (to the laser node) his client immediately crashed. After just a handful of seconds (which I presume was the time it took for the game to hand off the chunk rendering to my client) Mine crashed as well.

If it's worth mentioning, I was running a ME export bus into a drawer running into an advanced connector (into an RFTools network connected to mechanical crafters) when my client crashed.

### Steps to reproduce

Build a laser.io node connected to a pipe
Copy said laser node with copy paste tool from building gadgets
Paste in another area with pipes
Disconnect pipe running to laser node from other pipes

### Expected behaviour

Expected the farm segment to function as normal with items to be able to transfer as the would "normally"

**Comment by Raidobw2** [comment]
https://github.com/Direwolf20-MC/BuildingGadgets/issues/724
