### ISSUE TITLE
AE2 and autocraft netherite upgrade (function drawer) bug

### ISSUE THREAD

**Issue by ph1823** [FTBTeam/FTB-Modpack-Issues#2461]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

https://pste.ch/patozozefo.pl

### Describe the bug

When the task of craft of the netherite upgrade (function drawer) is finished, the AE2 network does not notice it and thinks that it is not finished.

### Steps to reproduce

1. Make a AE2 system
2. Start craft of netherite upgrade (function drawer)

### Expected behaviour

after the end of the craft, it must disappear from the tasks.

### Screenshots

[Screenshot 1](https://ibb.co/0B6hVMY)

### Additional information

if you want video i can make this

**Comment by DinnerBeef** [comment]
The item has a damage value when crafting in the smiting table. In order to fix this, you can use the output that you get from the crafting of them as the result instead of the item form REI
