### ISSUE TITLE
AE2 facade and block not connect with CTM

### ISSUE THREAD

**Issue by ph1823** [FTBTeam/FTB-Modpack-Issues#2462]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

https://pste.ch/gasomiyucu.md

### Describe the bug

The textures are well connected with the "normal" blocks but when you put facades this is not connected

### Steps to reproduce

1. Craft grill concrete (any color but in my screen its orange)
2. craft grill concrete facade
3. Place concrete
4. Place facade

### Expected behaviour

texture conncted

### Screenshots

[Screen 1](https://ibb.co/0B6hVMY)

**Comment by DinnerBeef** [comment]
Do to limitations in how mods work, unfortunately, that is not possible at this time.
