### ISSUE TITLE
Luggage and Mob Imprisonment Tool Glitch

### ISSUE THREAD

**Issue by ryan11js** [FTBTeam/FTB-Modpack-Issues#2463]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

The luggage entity will drop items on pickup, and the mob imprisonment tool will store the luggage containing the item, resulting in the duplication of that item

### Steps to reproduce

1. Place item in luggage
2. Use mob imprisonment tool on luggage
3. Place luggage back down
4. Items become duplicated

### Expected behaviour

Not game breaking, but just to be cautious of it

**Comment by UnRealDinnerbone** [comment]
Same as #2441
