### ISSUE TITLE
Record Fragments crash my game

### ISSUE THREAD

**Issue by Garoot1111** [FTBTeam/FTB-Modpack-Issues#2464]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

[crash-2023-01-05_12.07.19-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10354569/crash-2023-01-05_12.07.19-server.txt)

### Describe the bug

All i know is that when i grab record Fragments, it crashes my game

### Steps to reproduce

1. place Record fragments into crafting station
2. grab Fragments
3. Anti-Profit

### Expected behaviour

i thought it would just pick up the items

**Comment by Raidobw2** [comment]
Sorry for the delay!
Instructions clear, it worked, I've fixed it ;)
Upcoming 1.6.0 SB3 will fix this.
Thanks for reporting
