### ISSUE TITLE
Stoneblock 3 unify.js script is inefficient

### ISSUE THREAD

**Issue by embeddedt** [FTBTeam/FTB-Modpack-Issues#2465]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

KubeJS scripts take nearly 5 minutes to run on my machine. Upon profiling, the majority of this time is spent in `RegexIDFilter.test`.

I believe this is caused by `unify.js` calling `event.replaceInput`/`event.replaceOutput` many times. As I understand it, each one of these calls is a separate iteration over the recipe registry (which contains nearly 17,000 recipes). This is not very scalable to a modpack of Stoneblock 3's size, as it means that over 17,000 regex matches are performed in each call. 

I don't think there is a need to keep refiltering the set of recipes every time. Ideally one iteration should be performed over the recipe registry first to filter out any recipes in `dontReplaceMe`. Then the replacement calls should only be done on this limited set of recipes. I am not sure if KubeJS allows this.

### Steps to reproduce

1. Open StoneBlock 3 and load into an existing or new world.

### Expected behaviour

KubeJS scripts should not take up the majority of world load time.

### Additional information

As a second minor issue, I identified two potential logic problems with the regexes themselves.

* The Botania regexes should probably be prepended by `^` and `$` to ensure they perform a complete rather than partial match of the ID.
* `/.*yellow*./` "matches any number of any character, followed by `yello`, optionally followed by any number of `w`s, followed by exactly 1 character". [Here](https://regexr.com/75mtt) is a demonstration of how this behaves. Ideally this should be changed to `/.*yellow.*/` so that it matches any string before and after (which is likely what was intended). 

Kudos to @Nolij for his assistance with the regexes.

**Comment by MaxNeedsSnacks** [comment]
A small note on replaceIO and its performance: The way replaceIO is used in modpacks nowadays is.. _excessive at least_, and warrants rethinking how that code is handled. You're right that it currently iterates over the *entire* recipe registry (and this is unfortunately unlikely to change in 1.18 to maintain backwards compatibility with existing scripts) every time it's called, and it would be much much more efficient to have some sort of data structure storing pairs of filters and operations executed on recipes matching that filter, such that only one loop ends up being executed and all modifications are done in sequence for each recipe

**Comment by Sunekaer** [comment]
Yes but its the best we can do right now :)
