### ISSUE TITLE
Cannot load the world at all

### ISSUE THREAD

**Issue by MrCurseBreaker** [FTBTeam/FTB-Modpack-Issues#2466]
### Modpack

FTB StoneBlock 3

### Modpack version

buschebus@gmail.com

### Log Files

https://pste.ch/ogadoneqew.md

### Describe the bug

When I try to create the world, it stuck on loading screen forever.

### Steps to reproduce

1.Play StoneBlock 3 (1.5.0)
1.Single Player
2.Create New World

### Expected behaviour

Load in the world.

### Screenshots

![Uploading 1.png…]()

### Additional information

I tried first and latest version of pack already but nothing work.
I tried on default and custom game path too (Just testing).

Nothing work, I'm just stucking with this screen over 10 minutes.

**Comment by UnRealDinnerbone** [comment]
Looks like there was an issue loading a config file. You can fix this by deleting the config file cofh_core-server.toml (this file is located in the world folder so that full path would be world/cofh_core-server.toml) doing this should fix the issue
