### ISSUE TITLE
Kubejs startup scripts failing to run.

### ISSUE THREAD

**Issue by HamishWHC** [FTBTeam/FTB-Modpack-Issues#2468]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0 (have also tested 1.4.3, same issue)

### Log Files

[crash-reports/crash-2023-01-07_17.58.57-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10365667/crash-2023-01-07_17.58.57-fml.txt)
[logs/kubejs/startup.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10365669/startup.txt)

### Describe the bug

When launching, the Mojang loading screen finishes and I get an "Error loading mods" page (see screenshot). Looking through the crash report, it seems to be an issue with the kubejs scripts that I've linked below.

### Steps to reproduce

Not certain exactly what is causing the issue, but it's very likely my platform (M1 Mac) is the main issue. I'm using [JDK 17.0.5 for Mac OS Arm 64](https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html) and Prism Launcher 6.1. From there, I'm creating a new instance, selecting Stoneblock 3 1.5.0 from the FTB section, then launching the instance once it's ready. After a minute or so, I get the page below.

### Expected behaviour

Loading successfully to main menu.

### Screenshots

<img width="861" alt="image" src="https://user-images.githubusercontent.com/20359560/211135497-cf32236a-7272-40a7-98b1-c1216fccf662.png">

### Additional information

The failing scripts according to `logs/kubejs/startup.txt`:
* [forgevent.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10365660/forgevent.txt)
* [sbd.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10365661/sbd.txt)

Fingers crossed this is a simple enough issue to fix, I don't have a Windows PC with me right now and would love to play this modpack. Thanks for your help (and work on the pack).

**Comment by HamishWHC** [comment]
Well I feel very stupid right now! Prism Launcher asks me to download extra mods that it can't autodownload for whatever reason. I didn't notice this list had a scroll bar, so I downloaded 1 extra mod, and missed (after going through this prompt multiple times) that there were actually ~5 mods to download (including the Stoneblock companion mod!), so of course it wasn't working. Having now downloaded the missing mods, I get to the main menu! Sorry to post an issue unnecessarily, and thanks again for the work you put into your mods!

**Comment by BrobyM** [comment]
is there a chance you could help me with this having the same problem rn and i dont understand it

**Comment by keetsta** [comment]
Hey! I can't download stoneblock 3 on macos in prism launcher rn, can you do it? Or modpack just get deleted?
