### ISSUE TITLE
Issue Completing Flint Pickaxe Quest

### ISSUE THREAD

**Issue by jfkinslow** [FTBTeam/FTB-Modpack-Issues#2470]
### Modpack

FTB Inferno

### Modpack version

1.2.1

### Describe the bug

I had an issue with the completion of the quest "Flint and Stones to Grind The Bones" where when I did the only listed task it failed to complete. I took the time to look into and it looks as though the way the quest is setup it is using an AND Filter that is expecting you to have a flint pickaxe. However when I update the quest to only require the flint pickaxe to complete it works successfully.

### Steps to reproduce

1. Start a new game
2. complete quests leading up to flint and stones to grind the bones
3. Craft a flint pickaxe
4. Watch as the quest never completes

### Expected behaviour

I expected when i crafted a flint pickaxe as shown by JEI for the quest to be completed

**Comment by orbidlo** [comment]
It's been already reported, it's been issue for several versions now. Workaround is: switch the created pickaxe between main and off hand, try logging out and back in, create any tinker pickaxe (on tinker station) and if everything else fails, you can manually mark the quest completed using the command `/ftbquests editing_mode` and right-click the quest, and click Force Complete. Use command again to toggle off editing mode.
