### ISSUE TITLE
Change Akashic Tome for Eccentric Tome

### ISSUE THREAD

**Issue by nddragoon** [FTBTeam/FTB-Modpack-Issues#2477]
### Modpack

FTB Plexiglass Mountain

### Is your suggestion related to a problem? Please describe.

The 1.18 release of Akashic Tome has long been broken, particularly causing this bug that hides the first few books in it. Eccentric Tome is a rewrite that fixes issues with Akashic while also having a more permissive license.
![image](https://user-images.githubusercontent.com/54559451/211437775-8fd26b9c-74e9-4565-a11e-0525b856a612.png)

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/eccentric-tome

**Comment by Gaz492** [comment]
Closing this issue as there is more detail in #2499 on a workaround for the issue.
This pack is unlikely to get any further mod updates so its unlikely that we will swap the mod around with the one mentioned.
