### ISSUE TITLE
Day and night time not changing

### ISSUE THREAD

**Issue by Losos77** [FTBTeam/FTB-Modpack-Issues#2481]
### Modpack

FTB Sky Odyssey

### Modpack version

1.12.2

### Log Files

Dont needed.

### Describe the bug

Day and night time not changing:
Time on server and on single not changing naturally and can't be changed by commands

### Steps to reproduce

Not changing time

### Expected behaviour

Fix the bug

**Comment by Gaz492** [comment]
If you want to enable the day night cycle, go to the main menu on the pack, click on Mods, then search for FTB Utilities and click on it.
Now click on Config > FTB Utilities Common > World and set `Forced Spawn Dimension` Time to `-1`
