### ISSUE TITLE
Full game crash after world load

### ISSUE THREAD

**Issue by CaptRenault** [FTBTeam/FTB-Modpack-Issues#2482]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Log Files

https://drive.google.com/file/d/1-qTepVbW6iRZG5bTjPaX6UhR6Hg3ypki/view?usp=share_link

### Describe the bug

Loaded up updated Direwolf20 pack with no changes made by me.  I can load into a world but in less than a minute the game will crash.  I have restarted the computer and tried loading multiple new worlds with the same results.  Played the Direwolf20 1.0.4 version for hours with no complications.

### Steps to reproduce

Run any world for a couple minutes.

### Expected behaviour

For the game not to crash

**Comment by MoonStalk** [comment]
as a possible work around, try this: find flywheel-client.toml in configs directory:

changing backend = "INSTANCED" to backend = "OFF"

**Comment by markiem32** [comment]
@MoonStalk thank you. Changing that flywheel-client.toml to "off" worked for me.

**Comment by Saereth** [comment]
duplicate
