### ISSUE TITLE
Server Crash on Industrial Foregoing Machine Creation

### ISSUE THREAD

**Issue by ConstructionZombie** [FTBTeam/FTB-Modpack-Issues#2483]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Log Files

[crash-2023-01-11_02.31.48-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10388483/crash-2023-01-11_02.31.48-server.txt)

### Describe the bug

We are just starting out in this modpack, we needed something to deal with the animals and I chose Industrial Foregoing. Crafting the Fluid Extractor is the last event to happen before the server crashes. Consistent on two attempts, one being first discovery and second being immediately on restart. No client crashes.

### Steps to reproduce

1. Boot server
2. Craft Fluid Extractor from Industrial Foregoing

### Expected behaviour

Server retains functionality

**Comment by fewhnhouse** [comment]
I also encountered this issue. Happened on Creating Plant Sower, Plant Harvester, Dissolution Chamber.

**Comment by Saereth** [comment]
Visual workbench related crash here, appears to be fixed with an update to the mod which I've added to the next pack update

**Comment by ConstructionZombie** [comment]
Having seen this being a Visual Workbench issue, I tried crafting the same item in a crafting table upgraded Sophisticated Backpack. The item was made but the bag will no longer open from either previously-used keybind, right clicking in-hand, or placing on the floor and right clicking. Being a relatively similar situation, is this a relatively similar problem?

**Comment by Saereth** [comment]
That is a very weird interaction, thanks for letting me know I'll take a look

**Comment by ConstructionZombie** [comment]
I can add a further addendum to this in that it is only the backpack used to craft it that is inaccessible; a friend can't access it but can access their own, along with my ability to access their backpack freely.

**Comment by AnthonyFuller** [comment]
This also occurs when placing a pity machine frame in the crafting menu. It's related to BluSunrize/ImmersiveEngineering#5508 which has been fixed and will be in next mod update, verified that updating to the pre-release version fixes it.
