### ISSUE TITLE
Remove ProjectE

### ISSUE THREAD

**Issue by sinkillerj** [FTBTeam/FTB-Modpack-Issues#2486]
### Modpack

FTB StoneBlock 3

### Modpack version

All

### Describe the bug

I have written to the official Twitter, but did not receive a response. Please take notice that due to ongoing behavior from the FTB team, as well as non compliance with our publicly available modpack policies, we are no longer allowing ProjectE to be included in FTB modpacks.

Please remove this mod from Stoneblock 3, and any other FTB pack. This revocation of usage rights is permanent, and appeal requests will not be accepted at this time. We apologize for any inconvenience caused, however plenty of opportunities to make amends were given.

### Steps to reproduce

N/A

### Expected behaviour

N/A

**Comment by ThePaul-T** [comment]
Not commenting as part of any team here, just someone who is confused...

https://github.com/sinkillerj/ProjectE/blob/mc1.18.x/LICENSE

> Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do s
