### ISSUE TITLE
entiti rendering bug

### ISSUE THREAD

**Issue by Ropgo** [FTBTeam/FTB-Modpack-Issues#2487]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

the bug is that at some point of playing the rendering of entities(chests and minecarts only) just broke without me installing any new mods or externally edit the pack . I hope there would be sort of "repair " button as there is with curse forge or other launchers.
![2023-01-11_16 04 01](https://user-images.githubusercontent.com/122468591/211854580-5b6f5b7a-fc71-4255-a777-2e7aca8b2fec.png)

### Steps to reproduce

so I have no idea how this happed, at some point it happened while casually playing and progressing through the modpack

### Expected behaviour

I expected it to be like the vids online thru out the entire play time

### Screenshots

![2023-01-11_17 06 22](https://user-images.githubusercontent.com/122468591/211856229-395adea7-cbe4-4ab9-96f0-a357027c3fa5.png)
it only affects minecarts and chests, these are the ones i noticed

**Comment by DinnerBeef** [comment]
Do you have any logs file from when this happened, so we can see if there are any errors happening?
Did you recent update any drivers that might have caused this issue?
