### ISSUE TITLE
help me for crash game versions 1.5.0

### ISSUE THREAD

**Issue by pepe515** [FTBTeam/FTB-Modpack-Issues#2488]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

![FTB App 11  1  2023 17_47_38](https://user-images.githubusercontent.com/121722205/211868087-2e33ba4a-4c4a-4231-8f15-ca0202a3aa5f.png)

### Mod suggestion

the game still crashes when I start it in single player  
pleas help

**Comment by Raidobw2** [comment]
We're fixing this for Stoneblock 3 version 1.6.0, it will be out next week.

Try this in the meantime:

> There has been some players crashing after updating from 1.4.3 to 1.5.0. The crash happens as soon as you join a world in singleplayer or a server.
> It looks like this is an issue when the FlyWheel mod configuration is set to "instancing".
> 
> To resolve this, in the FTB App, you can click the "..." button next to the "Play" button and select "Open" > "Config Folder".
> You will need to open the file `flywheel-client.toml` with a text editor such as Notepad and change the value in quotes to "`OFF`".
> Make sure to save the file. Afterwards, start your game and you should be able to join worlds.
> 
> Reference: <https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2404#issuecomment-1364625915>
> ![image](https://user-images.githubusercontent.com/17010632/214731422-bd787f80-cdc8-4afe-9ced-6bbea1532203.png)
