### ISSUE TITLE
Add fluid xp to the fluid that the hose pulley (from create) can consider infinite

### ISSUE THREAD

**Issue by Enryco** [FTBTeam/FTB-Modpack-Issues#2489]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Hose pulley from create has default config so only water and lava can be consider infinite. All other liquid can not be consider infinite. I suggest to add the liquid xp, required for the Jelly Baby Singularities, to the fluid that the hose pulley can consider infinite

**Comment by DinnerBeef** [comment]
Thank you for your suggestion, however, we fell like there are plenty of other ways to get XP need for Jelly Baby Singularities.
