### ISSUE TITLE
[Suggestion]: Make seeds give the dust instead of the ingot

### ISSUE THREAD

**Issue by set92** [FTBTeam/FTB-Modpack-Issues#249]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

It has happened with two seeds, netherite and titanium, that what I want is the ancient debris/netherite scrap to create Advanced Machine Frame, and titanium dust to create flux dust. But since the seeds give me netherite ingots and titanium ingots, and I can't destroy them to scrap or dust I only have 1 method to get them.

So my suggestion is to enable to transform the ingots into the previous steps, in the case of the titanium I think is normal that if you break an ingot you should get dust no? And in the case of the netherite maybe the seed could drop the ancient debris, and that way anyone could use it later for whatever they want?

Also since we are talking about the flux dust, could be possible to add some other way to do it? For late game when I'm not using tempered glass jar or I want to automate all with Refined Storage would be helpful if I could create flux dust with some other machine.

**Comment by quietust** [comment]
As of pack version 1.6.0, Netherite ingots can be converted into Dust in a Crusher (Mekanism), and a Combiner (also Mekanism) can convert 2 dust and 1 Basalt into Ancient Debris (which you can subsequently refine into Netherite Scrap).

Titanium ingots can also be converted into dust using the Crusher (Immersive Engineering), Enrichment Chamber (Mekanism), or Pulverizer (Thermal).

**Comment by set92** [comment]
About the netherite true, didn't remember that recipe with basalt, but the titanium's recipe I can't find it, seems there is something faulty with my version?

https://i.imgur.com/Jj3lE5I.png Seems I don't have any use for the titanium ingot in the crusher or any other machine. I also tried to put it in the crusher, but it doesn't allow me to put it inside.

**Comment by Raidobw2** [comment]
In 1.6.0, the info by quietust is correct and those recipes are available:
![image](https://user-images.githubusercontent.com/17010632/140471089-813dc532-9216-4002-ad64-2b0757608d49.png)
![image](https://user-images.githubusercontent.com/17010632/140471103-896cd366-1136-401e-b410-bde365ffcbb8.png)

I would suggest to back up your worlds and reinstall the modpack in case you don't see those.

As for creating flux automatically, you can already do that, but my personal opinion would just be to batch craft them for the rest of your playthrough. Here's a quick automated setup:
![auto_jar_craft](https://user-images.githubusercontent.com/17010632/140471235-13217004-127f-4ad0-828f-ea8f22be15b3.gif)

I'll leave your suggestion open so the dev can think if changes could be needed, or if the current system is sufficient.
For obtaining Titanium Dust, obtaining Netherite Scraps and automating Flux production.

**Comment by Sunekaer** [comment]
I wont be changing the outputs, ill add recipe for thermal and IE to crush netherite ingot to dust
