### ISSUE TITLE
Game crashes upon joining server

### ISSUE THREAD

**Issue by CyrilwerKaldra** [FTBTeam/FTB-Modpack-Issues#2490]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.10

### Log Files

[hs_err_pid14868.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10394861/hs_err_pid14868.log)

### Describe the bug

Client crashes upon trying to join a server, always spits out the exact same log
So far i have tried reinstalling the pack, reinstalling minecraft completely, updating Java, reinstalling java from scratch.
All drivers are up to date, same as the pc itsel

### Steps to reproduce

Launch the pack
Join a server
Client crashes

### Expected behaviour

For the game to not crash upon joining a server

**Comment by MoonStalk** [comment]
as a possible work around, try this: find flywheel-client.toml in configs directory:

changing backend = "INSTANCED" to backend = "OFF"

**Comment by CyrilwerKaldra** [comment]
> as a possible work around, try this: find flywheel-client.toml in configs directory:
> 
> changing backend = "INSTANCED" to backend = "OFF"

I'm gonna be carefully optimistic and say that doing this seems to have fixed the issue on my end so far

**Comment by Saereth** [comment]
https://github.com/Jozufozu/Flywheel/issues/168
Hopefully flywheel gets a fix out for this, that work around should help but without flywheel create can get very laggy

**Comment by MoonStalk** [comment]
flywheel fix is out (0.6.8.a) and new create version using it has been released (0.5.0.g)
Limited testing on my AMD GPU system with backend = "INSTANCING" seems to be working properly
