### ISSUE TITLE
Compact Machines and Digital Storage within StoneBlock 3

### ISSUE THREAD

**Issue by Raidobw2** [FTBTeam/FTB-Modpack-Issues#2491]
### Discussed in https://github.com/FTBTeam/FTB-Modpack-Issues/discussions/2484

<div type='discussions-op-text'>

<sup>Originally posted by **CyberTaniwha** January 10, 2023</sup>
As of writing, there is only one way to bring your digital network into a complex machine when using AE2 and that is using a quantum bridge.

RS has built in compatibility that allows it to send into a compact machine thus making it the only digital storage to natively work with a Compact Machines environment.

Could you look at something like <https://www.curseforge.com/minecraft/mc-mods/capability-adapter> that would help close the gap between these two digital storage solutions so that they are on par with each other in regards to compact machine functionality.

This is a quality of life fix only, so at your discretion and potential work load increase by adding another mod to maintain. </div>

**Comment by manmaed** [comment]
that mod is only for 1.12.2 pack is 1.18.2

**Comment by manmaed** [comment]
@CyberTaniwha
