### ISSUE TITLE
SB 3 - The rebirth point has been removed.

### ISSUE THREAD

**Issue by Cheezofff** [FTBTeam/FTB-Modpack-Issues#2497]
### Modpack

FTB Stone Block 3

### Modpack version

1.5.0

### Log Files

https://dropmefiles.com/pGEB2

### Describe the bug

I really enjoy playing this build, but for some reason I died in the hell ring from Mob Blaze. Then I went to the lobby with the portal, and in the chat it was written: The Rebirth point has been removed. I went into the portal and the game started all over again from the beginning. There should be no technical errors, the computer is new and has not changed anything in the build files. I'm upset(( all my stuff has been deleted(((

### Steps to reproduce

I do not know how I made this bug

### Expected behaviour

I hoped to appear at home as usual after death

**Comment by DinnerBeef** [comment]
Seems like your logs have expired. You can upload a new copy of the logs so that we can see if we can fix this issue?
