### ISSUE TITLE
Akashic Tome book model blocks icons

### ISSUE THREAD

**Issue by RyanDamerell** [FTBTeam/FTB-Modpack-Issues#2499]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.2.4

### Describe the bug

The book model blocks the top row of icons in the spawn Akashic Tome.

### Steps to reproduce

1. Open Plexiglass Mountain
2. Right click with the Akashic tome you spawn with

Independent of any UI scale

### Expected behaviour

The book should be above the icons, or failing that at least render behind them.

### Screenshots

![2023-01-12_13 13 55](https://user-images.githubusercontent.com/23424092/212182741-80283f67-e6c1-4efd-a200-a7434afc8498.png)

**Comment by iTzCrutchie** [comment]
As a temporary solution at least for me was to navigate to the config for akashic tome and turn the rendering off. Its located under configs and called akashictome-common.toml. Can edit with vs code or any text editor then change line 6 "Hide book render" from false to true. This will hide the book render when you right click the tome.

**Comment by MikesNameIsMike** [comment]
Same issue for me (4k monitor with UI scale at highest, if it matters).  The pack should probably just set that cofig to true by default for an easy fix.

**Comment by yeeticus777** [comment]
has this been fixed at all? im having the exact same issue but now the solution defined in this isnt capable as the file is empty starting at line 6 and there isnt any other options besides blacklist and whitelist
