### ISSUE TITLE
OceanBlock - Industrial Hemp Seed[Bug]: 

### ISSUE THREAD

**Issue by ZHerbold** [FTBTeam/FTB-Modpack-Issues#25]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

There is no way to get industrial hemp seeds in any way

**Comment by dahoskins75** [comment]
just loaded in with 1.2 still cant get hemp seeds from grass tried server and single plr

**Comment by hammackj** [comment]
2 stacks of bone meal and did not get a single hemp seed. This probably needs to be reopened.

**Comment by dahoskins75** [comment]
I'm glad I'm not the only one still having issue
