### ISSUE TITLE
[Bug]: FTB Jar Mod, Void Issue

### ISSUE THREAD

**Issue by Elvarion** [FTBTeam/FTB-Modpack-Issues#250]
### Modpack

OceanBlock

### Modpack version

1.5.0

### Describe the bug

When using the Jar Auto-Processing Block and crafting a Recipe with ingredients from your Inventory and there is no room for the output to go the crafted item is voided.
Tested on a Server and on Singleplayer

### Steps to reproduce

Place down 1 **Tempered Glass Jar**
Place down 1 **Jar Auto-Processing Block** Above the **Tempered Glass Jar**
Place down 1 **Cast Iron Tube** on Either side of the **Jar Auto-Processing Block**
Place down 1 **Chest** underneath the **Cast Iron Tube**
Fill the **Chest** so that all slots are occupied with any item besides what you are trying to craft
Example: Fill it with Dirt and then Craft **Prosperity Seed Base** with the Prosperity shards and Seeds in YOUR inventory.
Press the Green button to start the craft, The crafted item gets voided.

### Expected behaviour

Either fail the craft, or have the crafted item pop out on the ground (Later will be bad for server performance if items just spill out though)

**Comment by Raidobw2** [comment]
Hello, is it possible that you can test this on 1.6.0? I've just tried replicating it with the steps you wrote, and it seems to work on my side. I'm not really sure how that would be fixed on 1.6.0 as the mod did not update, but please try it and let me know how it went.

As usual, backups your worlds before updating.

I've attached a gif with the steps I've done below. I tried surrounding the jar contraption with blocks to prevent it from dropping the item as well after that test, but it still drops it even then.
I'm using `ftb-jar-mod-1605.1.0-build.31.jar`, which is in OceanBlock 1.6.0.

![jar_craft](https://user-images.githubusercontent.com/17010632/140468385-41a9eb8e-8d6b-4c81-89fc-2814336fce4d.gif)

**Comment by Elvarion** [comment]
Ok, some findings here
Today I cant replicate the issue on SP 1.5.0
But I can replicate the issue with my current Jar setup on the server, **but** If I make the small "Step by step" setup It works like intended.
https://i.gyazo.com/c1132d2edd9822b609c30701f65a243f.png
The seeds are not able to go into any machine as it either dont accept the item or its already full.
Blocks in the Picture connected via the pipe network; (Can you disable connections??)
Cooking Pot(Bowl slot is full(Farmers Delight))
Heat Generator(Mekanism), Enrich~ Chamber(Mekanism)
Metallurgic Infuser(Both Slots are full(Mekanism))
Cobble gen Tier2(Cobble for Days)
Chest(Full of Cobble(Vanilla))
Glass Jar(FTB Jar Mod).

There are also blocks behind the whole setup. The only block side open for the Auto Jar is infront. Possibly it spits out the seeds somewhere and it gets tossed at mach10 somewhere else? (I have been standing here with a magnet ring and that has not picked up any seed)

Seed in inventory is from when I broke the setup and made the "Step by step" version, that actually worked.

Not able to do more testing at the moment due to work.

**Comment by Elvarion** [comment]
Managed to sneak in one last test.
Needs more confirmation, but it SEEMS like the Cobble for Days Cobble Gen Tier2 eats the item straight up.
Test 1 - Removed the Cobble Gen > Seeds popped out
Test 2 - Put back the Cobble Gen > No seeds to the found

**Comment by Sunekaer** [comment]
Fixed in 1.6.0 please update your client

**Comment by Raidobw2** [comment]
Yup, #167 had Cobble gens eating items. It's been fixed in 1.6.0 as our developer says! :D
