### ISSUE TITLE
Pressing V causes the game to crash on home screen

### ISSUE THREAD

**Issue by DashPallvax** [FTBTeam/FTB-Modpack-Issues#2500]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Log Files

[crash-2023-01-12_16.30.27-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10406862/crash-2023-01-12_16.30.27-client.txt)
[crash-2023-01-12_16.22.43-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10406863/crash-2023-01-12_16.22.43-client.txt)

### Describe the bug

pressing V on any of the screens that you can access from the start screen without entering a world will crash the game.

You could be typing text or just tap the key and it will crash.

### Steps to reproduce

Open the game

press v on any of the home screen pages, single, multi, and their sub-screens

game crashes

### Expected behaviour

Pressing v would not crash the game.

**Comment by specCon18** [comment]
changing the supplementaries quiver binding from v solves this have verified with @JustANormalHooman

**Comment by specCon18** [comment]
this is a deeper issue with [Supplementaries](https://github.com/MehVahdJukaar/Supplementaries) any key associated with the binding even with modifiers not being pressed causes crash will be reporting on their repo referencing this.

**Comment by specCon18** [comment]
updating moonlight lib to 1.19.2-2.1.25 and supplementaries 1.19.2-2.2.35t solves this issue commit [here](https://github.com/MehVahdJukaar/Supplementaries/commit/eb56d85d870940fc07627e8566e1f580076b1ad4?diff=unified)

**Comment by DashPallvax** [comment]
Well, it's still a problem and the pack devs should be made aware that updating these mods is needed to stop this from occurring.
