### ISSUE TITLE
ServerHangWatchdog crashes on storage entities

### ISSUE THREAD

**Issue by Adam-OGithub** [FTBTeam/FTB-Modpack-Issues#2501]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

Crash 1: https://pste.ch/epifaqesup.pl
Crash 2: https://pste.ch/zexekojujo.pl
Crash 3: https://pste.ch/urubotohay.rb
Debug 1: https://pste.ch/uxakekuguq.md
Debug 2: https://pste.ch/upotilohin.md
latest 1: https://pste.ch/edetihewat.md
latest 2: https://pste.ch/zakupepojo.sql

### Describe the bug

Error:  **ServerHang Watchdog detected that a single server tick took longer than X seconds.**

### Steps to reproduce

With default "max-tick-time" or higher
1. Start the server
2. Player joins the server
3. Server crashes

or with modified  "max-tick-time" to -1 
1. start the server
2. Player joins 
3. Players gets timed out
4. Server console logs can't keep up

### Expected behaviour

Server to not have a higher tick than expected and allow player to join.

### Screenshots

n/a

### Additional information

Potential cause: 
It appears there is an entity that is the cause ,but I am unable to find exactly which entity is the cause and how to remove it. 

Troubleshooting
- I have tried to modify the "max-tick-time" in server.properties to -1 to disable watchdog which results in players timing out from the server when trying to connect and having the server say "Can't keep up! ..." in the console. 

- I have also tried increasing the "max-tick-time" to 120 seconds and while it allows players in temporarily it eventually crashes the server.

Possible solution:
- I have restored the world and disconnected the chickens from storing items in the connected black hole units and  compacting draws. Not sure if this will actually resolve anything permanently.

**Comment by Adam-OGithub** [comment]
Seems after I have stopped the chickens from importing items into our storage the server has stayed stable so far.

**Comment by michele-grifa** [comment]
The same issue happened on my server a couple of times in an hour. In our case we had connected around 40 chickens inside a compact machine and 2 RF Tools Tier 3 Crafter, and we imports all the items in the AE2, outside of the compact machine. When i try to enter the compact machine, i fall down in the void until the "timed out" message pops up.

I couldn't find a fix, other than disconnect the cable that output the items.

**Comment by Adam-OGithub** [comment]
I am now having the same issue again, however I believe the problem is with refined storage itself  and how it is handling large numbers of items going into the external storage. We still have most of the chickens disconnected form the system but have added other items that generate a large quantity at a time with EMC links.
Crash log:  https://pste.ch/izojepekip.pl

**Comment by Raidobw2** [comment]
For crash-1 of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2501#issue-1531631140, looks like that's caused by 3188 item stacks on the ground in dimension `ftbsbc:team/rorqual-movers-iconic`.

For https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2501#issuecomment-1386150818, I have no idea... If you have more of those crashes that look different or other server logs, feel free to add them and thank you.

For https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2501#issuecomment-1399645909, Refined Storage seems to have tried importing an item with NBT and it took too long, but the item is not specified. Could that have been a nested item like a backpack?

**Comment by michele-grifa** [comment]
Right now the problem seems to be gone after taking out chickens outside of the compact machines in my case.

**Comment by Raidobw2** [comment]
Thanks for letting me know! I've just did a quick test as well by setting chickens in a compact machine, but so far it's doing fine. If you are able to upload an older world of yours with the chickens inside the compact machines and put it here (like Google Drive), I may be able to test this further.
Thanks in advance if you do!

**Comment by michele-grifa** [comment]
I will check if I saved the pre-crash backup.

**Comment by michele-grifa** [comment]
Here it is, a pre-crash backup.

[Backup File](https://drive.google.com/file/d/1fP3wSZ7rIr1BA7eRF9g0Hejo9JKtdXNe/view?usp=drivesdk)

After server startup all is normal and I you can enter the compact, after a while, you fall in the void entering

**Comment by Raidobw2** [comment]
I appreciate this, I should be able to have a look this weekend. Thank you🙂

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
