### ISSUE TITLE
Instantly dying, all armour instantly destroyed

### ISSUE THREAD

**Issue by flarefluffsune** [FTBTeam/FTB-Modpack-Issues#2504]
### Modpack

FTB Inferno

### Modpack version

1.18.2

### Log Files

https://paste.ee/p/sPzU1

### Describe the bug

Instantly dying randomly and its also destroying my amour instantly.

This has not only completely and utterly destroyed a week of progression with a lot of rare items from epic/mythic apotheotic bosses but ruined the pack for me.

### Steps to reproduce

I don't know, it just happens.

### Expected behaviour

Not instantly dying and losing all of my hard worked on productivity.

### Additional information

There should never, in any instance, be a situation where you have zero control over being able to defend yourself or instantly losing all your hard earned equipment. I can accept every single vex being a legendary champion, mobs attacking through block walls because of wacky hitboxes and 50 different mobs that all have half second attacks who can attack further than your own attack range, but this is _completely and utterly **Unacceptable**._

**Comment by Saereth** [comment]
You were killed by a deathknight and your grave was created at (14, 128, 5272), your stuff should be there, if you can't find it for whatever reason there is also a backup created when you die as well you can recreate the tomb with the command: 

```
/simpletomb restore yourUserName 0 
```

this will recreate the latest tomb with all your things in it. As for it destroying your armor, there is nothing like that in the pack that directly destroys armor. You pack is also out of date as of the day you posted this and is now further out of date with the latest update today.

**Comment by flarefluffsune** [comment]
You really think I would take the time to come here and fill this in if it was as simple at retrieving them from the grave? Why are you treating me like some brainlet?

I retrieved my grave. None of my armour was in it. Helmet, chestplate, leggings, boots and shield all gone and on death I heard the break sounds and saw particles so clearly there is something because I doubt a mythic grade shield that ignores like 50% durability damage and had unbreaking 5 with almost full durability still is just going to break because it feels like it.

**Comment by blb2529** [comment]
This is real, just happened to me, "Death Knight" instantly killed me. Unbreaking 10 + mending on all pieces with experience backpack, broke my Traveler's Boots first, then after retrieving it broke all but my reforged % durability reduction helmet. Playing on 1.10.1 as of 2/22/2025.

Necroing, but I agree, this CAN'T be intentional and definitely happens. I couldn't imagine someone mistaking their armor breaking for their grave not showing up correctly. Mine was elite/legendary or whatever, so it may have something to do with affixes from the Champions mod?
