### ISSUE TITLE
Instant Crash on World Loading

### ISSUE THREAD

**Issue by Anghamarad** [FTBTeam/FTB-Modpack-Issues#2505]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Log Files

[hs_err_pid2280.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10415198/hs_err_pid2280.log)

### Describe the bug

No longer able to open a world I have been playing on without crashing FTB. Several retries have yielded several different reasons including Insufficient Memory, Exceptional Access Error and others, but most often not even creating a crash log at all. Crash usually occurs right after Terrain Generation.

### Steps to reproduce

1. Crashes instantly upon loading single player world

I don't remember what I was doing before the first crash. 

### Expected behaviour

To open world without crashing

### Additional information

I have attempted to allocate more memory and have run Windows Memory Diagnostic without solving the problem. First crash occured several days ago, I have since also attempted updating the modpack to 1.1,0. Other single player worlds created since then do not crash instantly like the main world but tend to crash shortly after joining. Not tested significantly.

**Comment by Saereth** [comment]
This is a computer issue/Java itself crashing 
```
siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0xffffffffffffffff
```
Unfortunately due to liability issues I cant even begin to help you troubleshoot your PC but this is not a pack specific bug I can fix for you sadly. Best of luck

**Comment by kernelstubbs** [comment]
We're having a crash with the new update for AMD GPUs only.  There is a similar issue here: https://github.com/adoptium/adoptium-support/issues/674 but that mod isn't in the pack...could it be a rendering issue with one of the new mods/updates?

**Comment by Anghamarad** [comment]
Yeah, I have an AMD GPU. Reinstalled the pack with old patch, no more crashing.
