### ISSUE TITLE
Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@5e5807c7, suppressing error

### ISSUE THREAD

**Issue by JakeMoe** [FTBTeam/FTB-Modpack-Issues#2508]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Log Files

This is what appeared in red in the server console:
[crash-console.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10416246/crash-console.txt)

This is the crash file it mentioned:
[crash-2023-01-14_00.40.15-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10416247/crash-2023-01-14_00.40.15-server.txt)

After logging back in, right clicking the crafting grid gives this:
[crash-after.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10416270/crash-after.txt)

Fourth crash log:
[crash-2023-01-14_01.04.45-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10416279/crash-2023-01-14_01.04.45-server.txt)

Single-player crash log:
[crash-2023-01-14_11.41.25-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10416317/crash-2023-01-14_11.41.25-server.txt)

### Describe the bug

Trying to craft an Industrial Foregoing Laser Ore Base leads to the first two crash logs attached.  I can put the items into the crafting table, and it renders the 3x3 grid of ingredients and the item above it correctly, but when I click the item to craft it, the server crashes.

When I start the server again and log back in, the crafting grid is only showing some of the ingredients in the table, and the missing ones aren't in my inventory.  Right-clicking the crafting grid gives the third crash text on screen.  I have to break the crafting grid and re-place it to be able to use it again.

The server seems to be fine, but after a short while, I get kicked out and the fourth crash log happens on the server.

Created a new single player world, gave myself the crafting table and ingredients, and tried to craft the Laser Ore Base there, which resulted in the same crash (crash log #5)

### Steps to reproduce

1. Put ingredients for Laser Ore Base into crafting table
2. Try to pick up item from slot to put into inventory
3. Server crashes

### Expected behaviour

Item crafts and is able to be put into my inventory.

### Additional information

Not sure if this matters, but this pack instance and server world have been upgraded several times from the original 1.0.0.

**Comment by JakeMoe** [comment]
Oh, I forgot to mention that I can get around this for now by cheating in the Laser Ore Base, so it doesn't appear to be the item itself, but the act of crafting it, that causes the crash.

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2483

**Comment by JakeMoe** [comment]
Cheers for the info; I had thought it was Laser Ore Base specific and searched for that, but having the same trouble with the Laser Drill now.  Will keep an eye on the other ticket.  Thanks again for the prompt answer.
