### ISSUE TITLE
[Bug]: cannot download file

### ISSUE THREAD

**Issue by blueaxolotl07** [FTBTeam/FTB-Modpack-Issues#251]
### Modpack

FTB Academy 1.12

### Modpack version

1.4.0

### Log Files

i dont know

### Describe the bug

it saids that the file from C:\Users\ADM\AppData\Local\.ftba\bin\assets\objects\14 is 14ae57a6bce3d4254daa8be2b098c2d99743cc3f cannot be downloaded by minecraft launcher

### Steps to reproduce

go to the FTB app
download FTB Academy 1.12
make sure u have minecraft

### Expected behaviour

i want that file to be downloadable so i can play the academy

### Screenshots

![image](https://user-images.githubusercontent.com/93713278/140443363-962633f7-fb6d-4f84-98b1-ed953cba675c.png)

### Additional information

don't have any add info

**Comment by Raidobw2** [comment]
Do this:

Open the launcher directly from `%localappdata%\.ftba\bin`, it's called `launcher.exe`.
Edit the installations to play on a new profile on 1.12.2 and play that profile once.
Reach the vanilla main menu.
Then close the vanilla game and close the FTB App for 15 seconds.
Open the FTB App again, and click play on your modpack.
If that doesn't work, verify your internet connection as it's saying it's too slow.

Once you've done that, there is not much else I can do, you have to check your internet with the ones you are living with.

Is this ok with you? Once you've done that please write me a message here and close this issue. Come see me in the FTB Discord if the issue persists (R3GEN), I can make you try other fixes, but if you don't have a good internet connection I cannot guarantee it will work.

**Comment by Raidobw2** [comment]
Come see me in the FTB Discord if you still need help. Closing this as it's a support request, which we handle on the Discord.
