### ISSUE TITLE
Server crash on startup, Oculus (oculus) has failed to load correctly

### ISSUE THREAD

**Issue by zediious** [FTBTeam/FTB-Modpack-Issues#2510]
### Modpack

FTB Inferno

### Modpack version

1.4.0

### Log Files

Latest.log: https://gist.github.com/zediious/4ee315f6648a34f26f070e734c6ab07b
Crash report: https://gist.github.com/zediious/b5f764aa70259422a2d0ddf174812119

### Describe the bug

When starting the server, the server crashes early on in startup. The cause seems to be the Oculus mod, given the following lines from the crash report/log

`Failure message: Oculus (oculus) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER`

This crash occurs after launching the server immediately after install, no changes are made.

### Steps to reproduce

1: Download fresh FTB Inferno 1.4.0 server (Tested on Windows and Linux)
2: Launch server after install, see crash

### Expected behaviour

The server to not crash

### Additional information

This issue was not occurring in 1.3.0. It seems an update to Oculus is incorrectly calling client code on the server?

**Comment by ztk4** [comment]
+1 I have the exact same failure when starting the 1.4.0 server build (only tested in Windows 10).

AFAICT it's trying to run client code to grab a screen from a console application and failing. I haven't tried running without `nogui`, but I don't that would WAI anyhow.

Impact: I'm staying back on 1.3.0 until this is fixed ;)

**Comment by markhc** [comment]
Same issue on a clean install on Debian Linux

Crash reports:  [crash-reports.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10419756/crash-reports.zip)

![image](https://user-images.githubusercontent.com/11592227/212531094-828c1ea2-f12d-44ca-ace3-620d2f5316fc.png)
exi

**Comment by zediious** [comment]
Created issue on Oculus issue tracker https://github.com/Asek3/Oculus/issues/279

Confirmed the crash occurs with the mod alone on a server.
