### ISSUE TITLE
Powah Solar Panels and Mining Dimension

### ISSUE THREAD

**Issue by vl0fast** [FTBTeam/FTB-Modpack-Issues#2513]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Describe the bug

I found that no Powah Solar panels seems to work on the mining dimension. But all the others, from other mods, seem to work fine

### Steps to reproduce

1. Make a Powah solar panel
2. Enter mining dimension
3. Place solar panel
4. Panel doesnt work

### Expected behaviour

I expected for the solar panel to be producing energy

**Comment by Saereth** [comment]
I submitted a PR to powah to resolve this, will update the mod when it's implemented
https://github.com/Technici4n/Powah/compare/1.19...Saereth:Powah:patch-1

**Comment by martijnenco** [comment]
Can this issue be merged? It says waiting for mod update, but there where multiple since january.. ..right?
