### ISSUE TITLE
Dont have any tool tipp

### ISSUE THREAD

**Issue by Aleron1707** [FTBTeam/FTB-Modpack-Issues#2514]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

Hi,

suddenly i dont have any Tool tip when i am locking at stuff. how could i fix this? :-/

### Steps to reproduce

a

### Expected behaviour

a

**Comment by UnRealDinnerbone** [comment]
Looks like you are talking about the tool tip that shows the block that you are looking at, there is a keybind to toggle it default keybind is 1 on the keypad (It called "Show Overlay" under the Jade category
