### ISSUE TITLE
Client crash with AMD GPU

### ISSUE THREAD

**Issue by kernelstubbs** [FTBTeam/FTB-Modpack-Issues#2515]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Describe the bug

The MC client crashes during initial chunk generation when logging into a SSP or SMP world - issue began after update to 1.1.0 and is similar to:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2505
https://forums.minecraftforge.net/topic/119518-exit-code-1073740940/#comment-524102

### Steps to reproduce

1. Have AMD GPU RX5700XT v. 22.11.6
2. Generate Chunks
3. Play Despacito

### Expected behaviour

Fun times with friends

**Comment by Saereth** [comment]
This is a flywheel issue we're waiting for a fix from the mod devs on, duplicate issue has already been created, temporary fix for you:


Open ...\Instances\[installation]\config\flywheel-client.toml

change:

backend = "INSTANCING"
to

backend = "OFF"
