### ISSUE TITLE
Volumetric Flask is not compatible with AE2 Unofficial Extended Life

### ISSUE THREAD

**Issue by SilveryStar** [FTBTeam/FTB-Modpack-Issues#2517]
### Modpack

FTB Interactions

### Is your suggestion related to a problem? Please describe.

There are too many recipes containing fluids that require the use of Assembly machine and Assembly Line. But Volumetric Flask's **Volumetric Interface** does not support the use of the **Pattern Expansion Card** in AE2 Unofficial Extended Life, and it cannot be displayed in the interface terminal.
I noticed that Volumetric Flask has not been updated for too long, is there any way to fix this

### Mod suggestion

I recommend using [AE2 Fluid Crafting Rework](https://www.curseforge.com/minecraft/mc-mods/ae2-fluid-crafting-rework). After testing, this mod can better support the PAE2 Pattern Expansion Card and can be displayed in the Interface Terminal.

**Comment by SilveryStar** [comment]
Surprisingly, it supports fluids as a crafting table that returns results, and at the same time, the recipes containing fluids in JEI can also be directly filled into the template terminal.

Really looking forward to seeing this mod in future updates, I think I'll be writing some zs scripts myself for now to avoid continuing to use the Volumetric Interface, it's just unsatisfying

**Comment by Kyyken** [comment]
I ran into this issue as well and felt challenged. Anyway, by adding

`ItemStack x = new ItemStack(Items.ITEM_PART_O_INTERFACE);
Upgrades.PATTERN_EXPANSION.registerItem(x, 3);
Upgrades.CRAFTING.registerItem(x, 1);
ItemStack y = new ItemStack(Items.ITEM_BLOCK_O_INTERFACE);
Upgrades.PATTERN_EXPANSION.registerItem(y, 3);
Upgrades.CRAFTING.registerItem(y, 1);`

to the end of the init method of Volumetric Flask, I was able to fix the issue (the Volumetric Interface is just made of subclasses of the ME interface, so I just had to register it as supporting the cards). This code can and should just be put into its own mod, but I didn't wanna deal with forge mod dependencies when I threw this together. Here's my reddit post with a download link to the modified Volumetric Flask mod.

https://www.reddit.com/r/feedthebeast/comments/11j7ryv/fix_for_pattern_extension_cards_in_ae2_extended/

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

We may have something up our sleeves, some may call it a remaster, keep an eye out on our social media platforms for more information.
