### ISSUE TITLE
Loom + Banner Not Working

### ISSUE THREAD

**Issue by Barnnotbarn** [FTBTeam/FTB-Modpack-Issues#2520]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Describe the bug

The pattern selection in the loom no longer works after updating to 1.1.0.  After placing a blank banner and dye, no options appear.

### Steps to reproduce

1. Place blank banner in loom
2. Place any dye in the loom

### Expected behaviour

No banner pattern options appear.

**Comment by Saereth** [comment]
working in 1.1.1 and 1.2
![image](https://user-images.githubusercontent.com/9200909/215552727-d68d10bd-a14c-4597-99cd-58853d02e114.png)
