### ISSUE TITLE
Can't update, new version mistakenly labeled as minecraft 17.0.2

### ISSUE THREAD

**Issue by Flabort** [FTBTeam/FTB-Modpack-Issues#2521]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.4 to 1.1.0

### Describe the bug

In the GDLauncher, when looking at versions, the modpack has an update available but it changes the version of minecraft and refuses to install.

Specifically, previous versions of the modpack run on minecraft 1.19.2, but version 1.1.0 of the modpack is listed as minecraft version 17.0.2+8

### Steps to reproduce

In GD Launcher, right click your Direwolf20 1.19 instance, and click manage.
Click on Modpack
Click on the dropdown bar for versions

### Expected behaviour

Direwolf20 1.19 should be on minecraft 1.19

### Screenshots

https://i.imgur.com/16oFTqR.jpeg

**Comment by Flabort** [comment]
> This seems to be an issue with GDLauncher not the modpack...

I would agree if the other versions of the modpack weren't on the correct minecraft version. I refer you to the screenshot, where you can clearly see the launcher is working fine, except for there being a non-existent minecraft version on the latest version of the pack.

**Comment by Saereth** [comment]
that's the version number listing not the mod pack version number
```
  "packAuthor": "FTB Team",
  "packVersion": "1.1.0",
  "packName": "FTB Inferno",
  "minecraftVersion": "1.18.2",
  "modLoader": "forge",
  "modLoaderVersion": "40.1.80",
  "javaVersion": "17.0.2+8",
  "minimumRam": 4096,
  "recommendedRam": 6144,
  "changelog": "metadata/changelog.md",
  "logo": "metadata/logo.png",
  "splash": "metadata/splash.png",
  "type": "beta",
  ```

This is a gdlauncher misreading whatever it's trying to identify as the version number from the pack. Since this isnt a pack specific issue and not something I can fix Im going to close this

**Comment by Flabort** [comment]
OK, I can accept that. I see it's the java version it's reading now, for some reason. Do you know if GDlauncher has a github or error reporting tool I can go to?
