### ISSUE TITLE
Direwolf 1.19 1.1.0 crashes without notifications

### ISSUE THREAD

**Issue by DigitalSketch** [FTBTeam/FTB-Modpack-Issues#2522]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.10

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10429957/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10429958/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10429959/latest.log)

### Describe the bug

My instance keeps randomly crashing and I can't see any errors causing it. I've tried:

- Reinstalling the Direwolf 1.19 1.1.0 modpack
- Increasing and reducing the RAM
- Trying in single and multiplayer, happens in both. 
- Starting a new world

### Steps to reproduce

Just opening the game, opening a world and waiting anywhere from 0 to 30 seconds then it crashes

### Expected behaviour

Game doesn't crash

**Comment by Saereth** [comment]
This looks related to the amd crashes from flywheel, should be resolved in the 1.1.1 update coming out soon, let me know if you experience this after updating please, thanks

**Comment by DigitalSketch** [comment]
This fixed the issue. Thank you
