### ISSUE TITLE
Occultism Pentacle Visualization Not Working

### ISSUE THREAD

**Issue by CarbyDood** [FTBTeam/FTB-Modpack-Issues#2523]
### Modpack

FTB Inferno

### Modpack version

1.4.0

### Describe the bug

When trying to use the multiblock preview for pentacles in the Dictionary of Spirits, no blocks from the preview are visible, and right clicking to anchor the preview will simply cause the game to say that the structure is "complete". 

### Steps to reproduce

1.) Open Dictionary of Spirits
2.) Select any pentacle under the pentacle tab
3.) click on the eye button that says "Show Multiblock Preview" when you hover over it.
4.) Right Click to Anchor the preview

### Expected behaviour

The needed blocks for the structure are supposed to be visible, and when you anchor the preview, it is not supposed to be marked as complete until all the blocks needed for it are put down by the player.

### Screenshots

![image](https://user-images.githubusercontent.com/25436746/212792986-84341aef-c05a-4b6d-9d61-444120d27f01.png)
![image](https://user-images.githubusercontent.com/25436746/212793011-4ce54bd1-4422-4789-8d56-2db532d582eb.png)
Pentacle selected was "Fatma's Incentivized Attraction"

### Additional information

This may be applicable to other mods that have a multiblock preview for thier books.

**Comment by Saereth** [comment]
this is a new incompatibility with occultism and rubidium, despite it previously working with Rubidium occultism as decided to place the blame squarely with rubidium. Unfortunate but we'll just have to do without the preview for now until either of them get a fix for us. I'll update if/when we get a solution from the devs
