### ISSUE TITLE
Kubejs errors on login to server.

### ISSUE THREAD

**Issue by willrun4fun** [FTBTeam/FTB-Modpack-Issues#2524]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

[server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10436808/server.txt)

### Describe the bug

Had been playing fine and now when I login I get a Kubejs warnings in my chat.
The kubejs server.txt it pointed me to is attached.

### Steps to reproduce

Login

### Expected behaviour

to not have an error

### Screenshots

![javaw_kmFGNe6qhT](https://user-images.githubusercontent.com/5352339/212946604-b6bba8a7-0f4c-412b-aeb2-edfecf4e9ff5.png)

**Comment by Lorien31** [comment]
I do have the exact same issue when launching Stoneblock 3 with Prism

**Comment by willrun4fun** [comment]
I fixed the issue.  Copied over a new copy of the kubejs folder on the server.

**Comment by Sunekaer** [comment]
#1729
