### ISSUE TITLE
Ticking entity (skeleton) crashes game

### ISSUE THREAD

**Issue by Thorton101** [FTBTeam/FTB-Modpack-Issues#2525]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Log Files

[crash-2023-01-17_16.09.53-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10436888/crash-2023-01-17_16.09.53-server.txt)
[crash-2023-01-17_13.52.41-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10436890/crash-2023-01-17_13.52.41-server.txt)

### Describe the bug

Game crash cause of a ticking entity (melee-skeleton). Started fighting a melee-skeleton.
After kill, game freezes and crash. 

### Steps to reproduce

Join a world, wait for night and start fighting melee - skeletons.

### Expected behaviour

no crash

### Screenshots

n/a

### Additional information

n/a

**Comment by Saereth** [comment]
Can you please include your debug and latest.log files. I cannot reproduce this myself so any additional information you can give to help me sort it would be useful, thanks.

**Comment by Thorton101** [comment]
Hi Saereth,

I posted two crash-logs, because it happened 2 times with 2 hours in between, after those crashes I restarted
the game and kept on playing. So the information you want from me should be in older logs.
I try my best to post those.

debug.logs (first two should be the same time as the crashes happened, third one is unpacked one,
I found in my game-folder)
[debug-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10439741/debug-2.log.gz)
[debug-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10439746/debug-1.log.gz)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10439749/debug.log)

latest.logs (same here, packed ones with the timestamp the crashes happened, third on unpacked one,
I found in my game-folder)

[2023-01-17-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10439759/2023-01-17-2.log.gz)
[2023-01-17-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10439763/2023-01-17-1.log.gz)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10439766/latest.log)

If you need further information or an unpacked version of the logs, 
please let me know.
Thanks for your effort.

Best regards
Thorton101

**Comment by Saereth** [comment]
appears to be caused by a supplementaries mod mixin for the skeleton AI, I've updated supplementaries for the 1.1.1 update which should fix the issue.
