### ISSUE TITLE
Mixing any potion with redstone resulting on Haste II potion

### ISSUE THREAD

**Issue by bruno-borges-2001** [FTBTeam/FTB-Modpack-Issues#2526]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Describe the bug

I was trying to automate the crafting of potions with create and when I mixed night vision (3:00) with a redstone, the result was haste II, then I tried with a mundane potion and it also returned the same thing.

### Steps to reproduce

1. Create any potion in a create Mixer + Basin (I tested with Night Vision (3:00) and Mundane Potion
2. Add a redstone
3. The recipe will consume any amount of redstone and 250mb of the potion and result on 250mb of Haste II potion (from Cyclic)

### Expected behaviour

Result on the extended time version of the potion

### Screenshots

![2023-01-17_17 38 18](https://user-images.githubusercontent.com/40278304/213007645-d9a2f161-59f4-4386-a801-eb25782cd085.png)
![2023-01-17_17 38 48_2](https://user-images.githubusercontent.com/40278304/213007647-e876d01e-898b-48fe-bdf6-77f21308c8a1.png)
![2023-01-17_17 38 53](https://user-images.githubusercontent.com/40278304/213007649-576aff55-6192-4f4a-9ba6-42c140b09e4c.png)

**Comment by JustANormalHooman** [comment]
I was able to confirm this. I tested every potion that could be put in a Create Drain and every single one of them would react with redstone in a mixer + basin + blaze burner setup to create Haste 2 from Cyclic, as described above. What's curious is this includes Haste 2 itself. The self-reaction explains how it is possible to consume any amount of redstone with this reaction.
