### ISSUE TITLE
[Bug] stacked Soups are consumed together

### ISSUE THREAD

**Issue by TheonlyTazz** [FTBTeam/FTB-Modpack-Issues#2527]
### Modpack

Other...

### Modpack version

1.0.0

### Describe the bug

Stacked Soups are consumed all at once upon eating (Thank you KatHioo for pointing that out to me)

### Steps to reproduce

1. make multiple soups
2. stack them
3. eat
4. ???
5. all consumed, only 1 bowl left
6. cry

### Expected behaviour

only eat 1 soup, or unstack

**Comment by Saereth** [comment]
No Soup for you, come back, One yeaaaar! :(
