### ISSUE TITLE
[Bug]: Compacting Ruby/Sapphire

### ISSUE THREAD

**Issue by andr9528** [FTBTeam/FTB-Modpack-Issues#253]
### Modpack

FTB OceanBlock

### Modpack version

1.6.0

### Describe the bug

Ruby and Sapphire both require Multiservo Press to be compacted into block form, as the block form doesn't have a recipe outside of the Multiservo Press one.

### Steps to reproduce

1. Collect alot of Rubies and/or Sapphires.
2. Attempt to compact Rubies/Sapphires like any other gem (i.e with a crafting table).
3. Be sad and look at this error.

### Expected behaviour

I'd expect the block form of Rubies/Sapphires to be craftable in a ordinary crafting table.

### Additional information

Would also be cool if the block forms could be used inside the Lapidary Dynamo, which is the only real use of Rubies/Sapphires.

**Comment by LuciusV** [comment]
Let me add closely related suggestion to make them convertable in compacting drawer

**Comment by andr9528** [comment]
@LuciusV That would be fixed by them adding a vanilla crafting recipe for the blocks.
