### ISSUE TITLE
Duplication with Drawer + Recycler

### ISSUE THREAD

**Issue by DoneTCT** [FTBTeam/FTB-Modpack-Issues#2530]
### Modpack

FTB Cotton

### Modpack version

1.1.0

### Describe the bug

you can duplicate items with a recycler from tech reborn and a drawer of the "simple drawers" mod by putting a backpack , from "simple backpacks" mod, with items in the drawer next to the recycler which will pull the backpacks in, quadrupling them, the backpacks will contain all the items that the original one had.
this works with all items . if i put one item in the drawer it gives me 4, if i put 6 , it gives me 8, if i put 5 i gives 8. and so on. looks like it goes by multiple of 4.

### Steps to reproduce

1 place a recycler (mine had auto-output to the top with a chest on top, auto-input to the right with the drawer next to it)
2 place the oak drawer from "simple drawers" (mine was on the right since auto-input was on right of the recycler + my drawer had a full gold upgrade)
3 give power the recycler
4 put a backpack from "simple backpacks" with items in it into the drawer, it should pull the backpack in, quadrupling it,
5 pull out the backpack from the recycler before it gets recycled.

### Expected behaviour

put 1 item in the drawer, the same item should be pulled into the recycler without dupe

### Screenshots

![image](https://user-images.githubusercontent.com/48444041/213193830-501e010c-5cf1-46e4-a331-b6a93fa52211.png)
![image](https://user-images.githubusercontent.com/48444041/213194031-36611b08-614d-4b33-a0f4-e296bb0011c0.png)

### Additional information

i'm sorry for not providing any log file, but it is pretty easy to replicate.
sorry for my not-so-great english.
I haven't tested with others machines from tech reborn, also the recycler doesn't need power. the backpack specification is because it was an accident when it first happened, i rightclicked my BP on the drawer and accidentally duped it, but it works with other items.
I said to give power to the recycler Because it is how it first happened to me, just to be clear.

**Comment by manmaed** [comment]
This  issue is now stale
