### ISSUE TITLE
Frequent Crashes: Timed out waiting for World Statistics

### ISSUE THREAD

**Issue by CaptainMojojojo** [FTBTeam/FTB-Modpack-Issues#2531]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10456852/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10456853/latest.log)
[crash-2023-01-18_15.43.05-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10456856/crash-2023-01-18_15.43.05-server.txt)
[crash-2023-01-17_22.32.19-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10456857/crash-2023-01-17_22.32.19-server.txt)

### Describe the bug

Frequently but intermittently server crashes with [spark-asyncsampler-worker-thread/WARN] [spark/]: Timed out waiting for world statistics error code. Can occur when logging in to server or frequently occurs when teleporting into home location. Area is chunkloaded and contains multiple mod integrations.

Issue usually temporarily resolved with server restart.

### Steps to reproduce

Teleport to specific area using RFTools Transmitter/Receiver

Or

Login to server while last location was in specific area.

### Expected behaviour

Server not crashing and requiring restart

**Comment by Fey142** [comment]
Same issue on 1.1.1 - Console spammed with Timed out waiting for world statistics. - at some point it does a huge lag spike and the ticks continue like nothing happened, other times the server completely stalls and keeps spamming that message every minute (you dc and if you try to reconnect it says timed out).

**Comment by jewiden** [comment]
Still seeing this error after having upgraded to 1.3.2. Exact same behavior as on 1.1.1.

**Comment by hezamu** [comment]
Possibly related, at least the symptoms are identical: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/299

Note that upgrading FTB Chunks did not fix the problem for me.

**Comment by zEpiixz** [comment]
Anyone here got a solution to this or at least located the problem because ftb chunks wasnt it.

**Comment by modderchris** [comment]
exact same issue, no pillagers in sight and never crafted a shield, happens when opening a chest, or sometimes literally just standing still so your link is not the root cause buddy, maybe FTB chucnks but wtf does "world statistics" have to do with critical world functions? I mean statistical data is good but it shouldn't be a higher priority than normal functions, like how many block spaces are tile entities would help with tracing lag but it shouldn't be using so much time of the server ticks to calculate debugging log data
or am I entirely misunderstanding what that thread does?

**Comment by xXsansoloXx** [comment]
I'm losing my mind trying to fix this for my modpack

**Comment by elslimecicle** [comment]
Also losing my mind. Desperately trying to find a fix lol. Don't have FTB Chunks installed on the server whatsoever, have yet to encounter a pillager or hold a shield.

**Comment by Saereth** [comment]
This issue shown in the logs has been resolved so Im going to need some fresh log files from any of you having the issue and i'll be glad to dig in
