### ISSUE TITLE
Unable to Craft Traveler's bedroll in Traveler's backpack Crafting grid

### ISSUE THREAD

**Issue by Podgeman10** [FTBTeam/FTB-Modpack-Issues#2532]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0.0

### Log Files

N/A

### Describe the bug

From Rammer Darksun#7687 on Discord:
"i don't know if you guys are able to do anything about it but the travelers backpack crafting grid is incapable of building "traveler's bedroll". it makes bedsheet (same recipe item) and there is no way to change it. meaning if you want to make more backpacks you got to bring a workbench with you
it's barely an inconvenience if you have more than one backpack but kind of odd that it doesn't give priority to its own recipe like in the work bench"

### Steps to reproduce

Attempt to Craft Traveler's bedroll in a Traveler's Backpack Crafting Grid
Defaults to bedsheet (same recipe)
Cannot craft more Traveler's Backpacks without  having to carry a default Crafting Table

### Expected behaviour

be able to swap between both recipes or have it default to the mod's recipe

### Additional information

Grabbed and ported from lote discord chat

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/213768574-d27df64a-1399-44be-8d8c-87cd13596f2c.png)
![image](https://user-images.githubusercontent.com/3908847/213768654-a77d0e30-366c-4625-9416-f1f505e24d1e.png)
while this is correct for the white ones.. it is only the white ones... you can make bedrolls from any color. ill add a recipe to turn 1 white bedroll into 8 white sheets and 8 whitesheets into 1 bedroll if that would make u happy

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/213771063-dd69b4ab-fb34-46c7-847c-bf84a092e26b.png)
![image](https://user-images.githubusercontent.com/3908847/213771081-006b9983-c85e-4f19-a102-411fb55ae03e.png)

Fixed in Dev
