### ISSUE TITLE
[Bug]: This line is printed by an example mod mixin!

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Modpack-Issues#2535]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0.0

### Log Files

N/A

### Describe the bug

We found the mod that places  This line is printed by an example mod mixin! and its trashcans 0.0.1-19.X

### Steps to reproduce

on title screen resize mc window

### Expected behaviour

Not to do that

**Comment by manmaed** [comment]
https://github.com/farrucho/trashCan/issues/1

**Comment by farrucho** [comment]
You are absolutely right I will fix that as soon as I can, thanks

**Comment by manmaed** [comment]
Fixed?
