### ISSUE TITLE
[Bug] False spam

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Modpack-Issues#2536]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0.0

### Log Files

false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false

### Describe the bug

false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false

### Steps to reproduce

?

### Expected behaviour

no false spam

### Additional information

up date Effective https://github.com/Ladysnake/Effective/issues/129

**Comment by manmaed** [comment]
Unable to Update mod as its a Quilt Only Mod

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/213766320-04fad3ac-bd8f-4b43-a84e-18d9f554a728.png)
ill be downgrading the mod to v1.3 seeing how 1.5+ are quilt only

only things we'll be musing is>
Effective 1.4 - 1.19.2

    Hypnotizing glow squids
        Glow squids can now hypnotize you, displaying a hypnotizing shader that gradually gets stronger the longer you look at them
        Glow squids will attract your cursor if they appear on your screen, this attraction getting stronger with the shader
        Both cursor attraction and hypnotizing can be disabled with two new configuration options
    Glow squids named "jeb_" now glow rainbow and have a rainbow hypnotizing pattern
    Splashes and ripples (from rain or splashes) in warm oceans at night will now glow from glowing plankton
        Glowing plankton can be disabled with a new configuration option

**Comment by manmaed** [comment]
we have a fix in the works

**Comment by Rushmead** [comment]
There is a mod that will allow you to use version 1.4 without any spam, it is currently waiting to be approved on curseforge.

**Comment by TheonlyTazz** [comment]
Okay, once that's available, we can use that theb

**Comment by manmaed** [comment]
Looks like this has been added!
