### ISSUE TITLE
[Suggestion]: Add Woot

### ISSUE THREAD

**Issue by andr9528** [FTBTeam/FTB-Modpack-Issues#254]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

Having many mobs in the world has a negativ impact on a worlds TPS. With the inclusion of Woot players can make mob farms that is more TPS friendly.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/woot
Adds multiblocks structures which farm mobs.

**Comment by Sunekaer** [comment]
Thanks for the suggestion but we are not looking to add more mods to the pack unless highly necessary
