### ISSUE TITLE
Mobs dont despawn in the nether

### ISSUE THREAD

**Issue by BiffaPlayz** [FTBTeam/FTB-Modpack-Issues#2540]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0

### Describe the bug

Mobs aren't despawning in the nether when more than 128 away. They seem despawn correctly in the overworld

### Steps to reproduce

Go to the nether
Spawn a mob
move more than 128 blocks away

### Expected behaviour

Instant despawn when more than 128 blocks away

### Screenshots

![mobs](https://user-images.githubusercontent.com/118503749/213599774-8626243a-ac80-4d21-b6ce-2e8206fbbf95.jpg)

### Additional information

I was designing an Ender Warthog farm in a test world and it wasn't spawning anything because all the mobs were staying under the bedrock. I tried with other mobs too and none of them despawned at y500. Moving away in x/z and coming back didn't work either.

**Comment by TheonlyTazz** [comment]
I have tested this a bit and it seems this only affects the Enderwarthogs. I will need to figure out what is causing this issue and will try to come up with a fix asap

**Comment by tyler489** [comment]
It might be worth a look to see if they are classified as passive mobs in the code, I noticed this as well.

**Comment by TheonlyTazz** [comment]
[Adventurez Source](https://github.com/Globox1997/AdventureZ/blob/135e51f84cf92e2589b98bb1e48f48df8591d45a/src/main/java/net/adventurez/entity/EnderwarthogEntity.java#L34)

actually they are classified as net.minecraft.entity.mob.HostileEntity;
