### ISSUE TITLE
Unable to craft Powah Ender Cells

### ISSUE THREAD

**Issue by TheVekter** [FTBTeam/FTB-Modpack-Issues#2541]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.1

### Describe the bug

Remember how you couldn't craft Ender Gates because the cables are disabled? You folks changed the recipe to be identical to the Ender Cell one.

This wouldn't be an issue, but I can't find anything in the pack that lets me choose between valid recipes. Maybe switch the Ender core in the Ender Cell recipe with an Ender Eye Block from Cyclic?

### Steps to reproduce

1) Try to craft an Ender Cell.

### Expected behaviour

Game crafts an Ender Cell.

### Screenshots

![image](https://user-images.githubusercontent.com/7019927/213622838-213b177f-b7e1-4f77-afe2-938c2397260c.png)
Ender Cell

![image](https://user-images.githubusercontent.com/7019927/213622856-ec7d9296-bd59-4713-9f31-4a5091f51efc.png)
Ender Gate

**Comment by TheVekter** [comment]
Those screenshots are from JEI, btw. If you try to add the ingredients to the crafting table either through JEI or manually, you always get Ender Gates.

**Comment by Saereth** [comment]
These recipes should have been changed for the cells to use black glass panes this update, looks like the recipe change didnt make it into this update, I'll check on it and make sure its in for the next one tuesday

**Comment by kolhed** [comment]
After some searching I noticed that the crafter from rftools make the ender cell, not the gates, unlike all other crafters :)
