### ISSUE TITLE
Stoneblock 3 NEEDS a better ending quest 

### ISSUE THREAD

**Issue by LashaAreshidze** [FTBTeam/FTB-Modpack-Issues#2544]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

The current end of stoneblock 3 is to grind all singularities and create the infinity armor & weapons. And when you do, you have nothing to use it on. You've already mined all the blocks and beat all the bosses. So you're essentially questing for a useless set of armor. (red matter gem armor and Mekanism armor can get you through the entire pack with no problem)

I suggest adding a final quest. There should be one final boss in the pack. Maybe a Warden-style boss that is overpowered, and you NEED the infinity armor & weapons to get to it and defeat it. He could reside perhaps in the far-out layers, maybe 15,000 or 20,000 blocks away from spawn, encased in blocks only broken by the infinity pickaxe. The fight should be challenging but beatable. That way, the armor has a purpose, and you have something to use it on. 

That's just my personal idea, and it would be great to see, **But either way, it's important that the Infinity armor has a purpose and isn't crafted just for the sake of crafting it. Add an ending to the pack!!!**

Thanks :)

**Comment by Sunekaer** [comment]
The ending of the pack is to have infinity armor and be the most powerful you can be
