### ISSUE TITLE
Leaves not decaying

### ISSUE THREAD

**Issue by WTFGaming10** [FTBTeam/FTB-Modpack-Issues#2545]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0.0

### Describe the bug

Any non-vanilla generated trees' leaves are not decaying. I've sat at one for 30 minutes and no leave decay

### Steps to reproduce

Destroy any non-vanilla generation-style tree and the leaves just stay floating

### Expected behaviour

Leaf decay

**Comment by Morasiu** [comment]
Same

**Comment by TheonlyTazz** [comment]
changed the Custom Trees to not have persistent leaves
