### ISSUE TITLE
Cold Eye trade dissappears from cured zombie villager

### ISSUE THREAD

**Issue by FishOutOfH20** [FTBTeam/FTB-Modpack-Issues#2547]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0.0

### Describe the bug

I cured the villager and the trade for the cold eye was available.  I left to get the candy and upon returning, the trade was no longer available.  It had "cycled".  I could not get it to reappear by cycling the trade.  This means having to locate another igloo and cure another villager.

### Steps to reproduce

Cure the zombie.  Leave. Return.  See if trade is still available.

### Expected behaviour

The trade should not disappear when I leave and come back.

**Comment by TheonlyTazz** [comment]
I think i have fixed this, but would need more testing.
I also have added some info in the Questbook to prepare the food in advance
