### ISSUE TITLE
IndRev's smelter cannot process raw ore

### ISSUE THREAD

**Issue by FishOutOfH20** [FTBTeam/FTB-Modpack-Issues#2548]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0.0

### Describe the bug

Following their mod's book, I was looking to triple my ores.  I built the smelter, condenser, and pulverizer.  The raw ores cannot be put into the smelter like their book says.  It's an 8 month old bug that they haven't fixed.  Perhaps you can fix it within the pack.

Also, zinc ore cannot be used in their machines.  Stuck with a 1-1 conversion using a furnace or Create.  I would think if a pack offers ore tripling, it should apply to all ores.

### Steps to reproduce

Build the smelter and try to put raw ore into it.  It doesn't accept it.  Apparently it will only accept the sulfuric acid processed stuff, but I'm not interested in all that mess.  Just like nobody really uses the full Mekanism setup in 1.19.  It's not worth all the additional hassle to produce the extra gas.  Most stop with ore doubling through oxygen.  That was the plan.  Stop with ore tripling.

### Expected behaviour

If a mod's book says it processes raw ore, it should.

**Comment by TheonlyTazz** [comment]
![grafik](https://user-images.githubusercontent.com/3908847/213911586-6c115b84-3e1b-42d3-bb31-169bbe258dbf.png)
The book doesnt specificly tells it processes RAW ore, it only tells you that it can process Ore.

Reason this cannot be done with Raw ore is very simple.

1 Ore Block can give you 3 ingots through processing it with Indrev Smelter.

If i would enable Raw Ores being processed the same way, you could in theory just use Fortune on your Oreblock, get 1-4 Raw ores per Ore Block (Results may vary depending on your fortune Level)
and then process the 1-4 raw Ores, which would then, if trippled result into 3-12 ingots.

I understand that its frustrating that raw ores cannot be trippled in that way. But as it stands now, i am not going to change this.

I will keep this Issue open for now and am open for a discussion why and how we should implement raw ores smelting
