### ISSUE TITLE
Direwolf

### ISSUE THREAD

**Issue by jefrbunn** [FTBTeam/FTB-Modpack-Issues#2549]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Describe the bug

Crafting the livingwood twig form botania is not possible due to a recipe conflict. I believe the livingwood log crafting sticks overrides the ability to craft the twigs

### Steps to reproduce

1. Craft living wood.
2. try and craft a living wood twig
3. tried via a vanilla table 

### Expected behaviour

using two living wood logs should craft a 

### Screenshots

![image](https://user-images.githubusercontent.com/3003516/213844815-1152eec2-7373-429e-b586-c1653e93ce05.png)

**Comment by Saereth** [comment]
fixed in next update
![image](https://user-images.githubusercontent.com/9200909/215282409-8dbe58e4-59a7-4560-b47c-2b5c24810a99.png)
