### ISSUE TITLE
[Bug]: Can't make ultimate singularity

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#255]
### Modpack

Ftb University 

### Modpack version

1.3.0

### Describe the bug

I have all the singularities, the ultimate pops up on the right, I just cant take it out (it gets put back in)

### Steps to reproduce

1.) Put all the singularities into a tier 4 crafter (Ultimate)
2.) Try and take the ultimate from the output

### Expected behaviour

To give me an ultimate singularity

**Comment by Raidobw2** [comment]
Check with the server owner as well, typically when the item goes back in it can be a mismatch between the client and server.

To confirm it's the case for them, you can hop in a Singleplayer world and try to make the craft. If the craft works, the server changed the recipe or it's not on the server for some reason.

**Comment by JunaidA197** [comment]
Yeah thanks it works in SP must be a MP issue.

**Comment by JunaidA197** [comment]
Was weird, the recipe used to not show invar singularity, but it now does.
