### ISSUE TITLE
Duplicated Items in @Avaritia Extreme Crafting Table

### ISSUE THREAD

**Issue by G2-Grizzlyy** [FTBTeam/FTB-Modpack-Issues#2551]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.2

### Describe the bug

When crafting items in the extreme crafting table in quantities, crafting then exiting the table without using all of the ingredients will almost double the remaining quantities when re-opening the crafting table. 

The results seem to vary. Sometimes it'll not use up any ingredients, but still allow you to take the crafted item, even without closing the crafting interface. The majority of the time, it duplicates the ingredients within the interface itself. If it doesn't duplicate whilst inside the interface, closing and opening it again will produce my original findings. 

### Steps to reproduce

1. Input at least 2x of each ingredient into the crafting interface
2. Remove 1 of the crafted items
3. Close the interface and re-open it
4. Ingredients should have duplicated

### Expected behaviour

Input ingredients, output crafted item using up all of the given ingredients.

### Screenshots

https://user-images.githubusercontent.com/123249473/213870644-e573938a-e3ae-4499-a9a4-fbcd01ec3e59.mp4

### Additional information

Creative mode OFF
JEI Cheats OFF
Works on singleplayer
Works on multiplayer

**Comment by Sunekaer** [comment]
#1903
