### ISSUE TITLE
Crashing On Launch "No Signature"

### ISSUE THREAD

**Issue by CH4MBRS** [FTBTeam/FTB-Modpack-Issues#2555]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3&1.5.0

### Log Files

[crash-2023-01-21_20.03.51-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10473527/crash-2023-01-21_20.03.51-fml.txt)
[crash-2023-01-21_20.08.19-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10473528/crash-2023-01-21_20.08.19-client.txt)
[crash-2023-01-21_20.10.10-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10473529/crash-2023-01-21_20.10.10-client.txt)
[crash-2023-01-21_20.12.11-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10473530/crash-2023-01-21_20.12.11-client.txt)
[crash-2023-01-21_20.16.49-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10473531/crash-2023-01-21_20.16.49-client.txt)
[crash-2023-01-21_20.21.45-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10473532/crash-2023-01-21_20.21.45-client.txt)
[crash-2023-01-21_20.25.02-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10473533/crash-2023-01-21_20.25.02-client.txt)

### Describe the bug

The modpack is launching past the starting running but once it hits the Mojang loading screen it crashes before the bar gets full. The first crash I had said only two mods had an issue but then the whole pack stopped working.

### Steps to reproduce

1. FTB app
2. Launch instance
3. Crash

### Expected behaviour

Proper functioning of pack and ability to enter servers/worlds.

### Screenshots

![image](https://user-images.githubusercontent.com/123280060/213896941-3c77e8e3-a79c-43a3-ae5d-3bf537e1e864.png)

**Comment by Raidobw2** [comment]
Whoops, labeled this by error.

Some mods appeared to cause issues, try opening the mods folder and remove the "reauth" mod jar file (delete).

Also, if you want you can try to install the Stoneblock 3 server on the side in a new folder and copy all of the files it install into your client instance.

In the Versions tab you can get the portable executable and install the server with it. You'll need to place the exe inside a new folder then double click it. Press enter when it asks for questions
![image](https://user-images.githubusercontent.com/17010632/214730418-8b501819-768e-4e89-bc17-d73079b6754e.png)
https://www.feed-the-beast.com/modpacks/100-ftb-stoneblock-3

Normally I'd say you can downgrade/update the instance to repair it, but this might be a network issue, hence why I'm trying to make you pass by the installer to see if it can download correct mod files, which you can then use in your modpack files.
The server and the client basically are more or less the same, so sometimes it has some useful uses like that

E.g. Copy the `mods` folder from the server to your modpack files in the FTB App, they're the same folder. Same for all other files on the server, and overwrite when prompted.

Let me know if that worked

P.S. There's a crash with Flywheel in 1.5.0 as well. If you want to wait, next week we're releasing another version of StoneBlock 3, version 1.6.0. This will fix many crashes including the Flywheel bug, so it could be worth the wait. The workaround for now is in the [FTB Discord](https://go.ftb.team/discord) in the `#stoneblock-3` channel, in the pinned messages.
