### ISSUE TITLE
Client can't join a LAN server

### ISSUE THREAD

**Issue by NeosGhost** [FTBTeam/FTB-Modpack-Issues#2556]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.1

### Describe the bug

[Client can't join a LAN server](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2283#issue-1487501571)

My friend can't join LAN server. She gets error "Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException"

Reopening

### Steps to reproduce

One kit hosts a LAN server from pause menu.
Second kit joins the server
Observe the issue

### Expected behaviour

Second kit is able to join server

### Additional information

was closed in reference to missing version 1.4.0.

**Comment by Saereth** [comment]
can you both try removing or disabling the connectivty mod and see if the issue happens with it disabled?

**Comment by NeosGhost** [comment]
updating moonlight lib mod version fixed the issue. recommend version 2.2.0.
