### ISSUE TITLE
wireless universal terminal bug

### ISSUE THREAD

**Issue by Thorton101** [FTBTeam/FTB-Modpack-Issues#2557]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.1

### Log Files

[WirelessCraftingGrid_latest_0122.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10474119/WirelessCraftingGrid_latest_0122.log)
[WirelessCraftingGrid_debug_0122.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10474121/WirelessCraftingGrid_debug_0122.log)
[WirelessCraftingGrid_debug_0122.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10474122/WirelessCraftingGrid_debug_0122.log)

### Describe the bug

Hello,

trying to open the Wireless Universal Terminal doesn't work anymore. After trying to use it via hotkey or manual
in the inventory nothing happened. I noticed a 'null-pointer-exception' - error in the FTB App log.
Normal AE2 terminals work fine.
Wondering what caused this issue. I was able to use the wireless universal terminal 2 days ago and also
yesterday, but something happened yesterday and I am not able to use it anymore.
Thought a fresh start of my pc should fix that problem, but I logged in today and have the same issue.

best regards
& thanks for your effort

Thorton

### Steps to reproduce

No plan on how to reproduce that error

### Expected behaviour

hitting the keybind should bring up terminal interface

**Comment by dalgrim** [comment]
I have this issue as well. 
Link to Java error as the wireless crafting terminal is being used: https://pastebin.com/f54XdAk2
IT appears to be a recipe error with another mod. Using a non-crafting wireless terminal works fine.

**Comment by Thorton101** [comment]
Hi @dalgrim,

a okay good to know, same at my world, happened after a few days working. Had an other issue, that was fixed by
reloading the world, that the ae2 - terminals were blank with no items showing up.
I think of switching to refined storage, if there is no quick workaround or fix showing up.
Sorry to mod-author for the effort they put it setting up the mods.

**Comment by dalgrim** [comment]
I don't think a switch is necessary, I'm betting this is a mod interaction issue. A simple mod version upgrade/downgrade of the effected mod should fix it. Give the FTB team a couple days and they'll get it figured out. In the mean time you should be able to just use a standard wireless terminal. You can still access all your autocraft recipes even from the plain wireless terminal. In the short term go to one of the terminals that does work, click on the configure terminal icon on left and check clear terminal on close. This should prevent any further terminal loss due to recipe conflicts.

**Comment by Fey142** [comment]
Can confirm happened to me a few times - a hotfix is just to delete the terminal and cheat in a new one (until it happens again).

**Comment by AnthonyFuller** [comment]
This is related to #2483 which I have a fix for in the comments. Manually update to a pre-release version of Immersive Engineering.

**Comment by Thorton101** [comment]
Hello,

one small question, where do I get the pre-release version?
I looked at curseforge and the github-page from immersive engineering
and found nothing.

**Comment by Fey142** [comment]
I guess you'd probably have to compile it youself from the github files or wait for a release.

**Comment by AnthonyFuller** [comment]
You can find it on their Jenkins here:
https://ci.blamejared.com/job/Immersive%20Engineering/job/1.19.2/28/
`ImmersiveEngineering-1.19.2-9.1.1-pre.11.jar` is the exact file you need.

**Comment by Thorton101** [comment]
Thanks for the link.

**Comment by Thorton101** [comment]
@AnthonyFuller Thanks again. Worked fine for me, during the visit I noticed, I visited Jenkins in the past very often.
But I forgot, that this page exists.
