### ISSUE TITLE
[Lunchbox] Attempting to put the lunchbox inside the lunchbox causes it to despawn from inventory

### ISSUE THREAD

**Issue by 2ndRecon** [FTBTeam/FTB-Modpack-Issues#2559]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0.0

### Log Files

N/A

### Describe the bug

With the lunchbox open, place various food items inside.

If you accidently. (or purposely) shift-click on the lunchbox from your toolbar, it attempts to put the 'lunchbox in the lunchbox' and causes it to instantly despawn from your inventory with ALL the food you just placed inside.

### Steps to reproduce

Craft or otherwise get lunchbox.
put it in your toolbar, and right click on it.
put something inside it like bread, foods, etc.
shift click on the lunch box itself.
watch your hard earned food and sustenance disappear into the vapor 

### Expected behaviour

dawg, you shouldn't be able to put a lunchbox in a lunchbox dawg.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
