### ISSUE TITLE
Modlist Crashing Issue

### ISSUE THREAD

**Issue by GitHub-Alexander-P** [FTBTeam/FTB-Modpack-Issues#2563]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

Clicking on the "Climb Ladders Fast" option in the mod list tab in the main menu immediately and efficiently crashes the game.

### Steps to reproduce

1) Open The Game
2) Click Mod List
3) Click "Climb Ladders Fast" (2nd from top option)
4) Crash

### Expected behaviour

I expected to see a menu showing the author, short description, and effect of the mod.

**Comment by Raidobw2** [comment]
https://github.com/spoorn/ClimbLaddersFast/issues/5

Thanks for reporting, though looks like we'll need to wait for this one, it's got some opened PRs already.

Visit the mod's page on CurseForge for info about this mod in the meantime https://www.curseforge.com/minecraft/mc-mods/climb-ladders-fast
