### ISSUE TITLE
Game Crashes on uses f

### ISSUE THREAD

**Issue by chrabri2** [FTBTeam/FTB-Modpack-Issues#2565]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

https://pste.ch/ikoxebefaz.pl

### Describe the bug

Game crashes upon examining the uses of an Enderchest, from the mod Enderchests. Works for other items in the mod too.

### Steps to reproduce

1. Open up a world
2. Open inventory to REI
3. Find an @Enderchest item
4. Use the keybind to "examine uses"

### Expected behaviour

A UI of the uses of the enderchest, or nothing if there are none.

**Comment by Raidobw2** [comment]
https://github.com/Creators-of-Create/Create/issues/4122

I'll see if I can find a workaround, thanks for reporting
