### ISSUE TITLE
every time i use ftb mine it Whistle

### ISSUE THREAD

**Issue by yoyode06** [FTBTeam/FTB-Modpack-Issues#2566]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

every time i use ftb mine it Whistle and i have to restart the launcher

### Steps to reproduce

1.press the ftb mine button
2.use it on anything
3.here is it.

### Expected behaviour

can you fix it so I don't have to change my key

**Comment by LilMxPlagueRat** [comment]
I'm nothing to to with FTB but this is because the key for "Call for Luggage" is assigned to the same key by default, just get rid of or remap "Call foir Luggage" key instead of "FTB Ultimine"

**Comment by yoyode06** [comment]
ok thanks but this is really annoying
