### ISSUE TITLE
Pharaoh bugs

### ISSUE THREAD

**Issue by fulstock** [FTBTeam/FTB-Modpack-Issues#2567]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0

### Describe the bug

Playing in the coop (with a friend via LAN). 

Killing the Pharaoh vanishes the Curse only from the player who killed him. Curse is kept within the other one, with no luck to cure. 
Same issue for the advancement itself. 

### Steps to reproduce

Obvious I guess? Stated earlier. 

### Expected behaviour

Probably better to grant this (and other quests like this) to all players / nearby ones at least.

**Comment by fulstock** [comment]
Tried to grant advancement "Eternal Slumber" to a cursed player, but this did not help either.

**Comment by TheonlyTazz** [comment]
It's added via  kubeJS data

I'll make sure to work on this next update, this totally slipped my mind.

In the meantime, you could resummon him and rekill him

Or if the player dies a couple of times (depends on the game difficulty) the pharaoh will have pity on them
