### ISSUE TITLE
Crimson Ladder not recognized by courier/builder

### ISSUE THREAD

**Issue by rewenx** [FTBTeam/FTB-Modpack-Issues#2568]
### Modpack

FTB Inferno

### Modpack version

1.5.0

### Describe the bug

When builder request Crimson Ladder, they never seem to see it inside the warehouse, or it takes a very long time to register. I have not noticed this happening with any other building material. Even manually going to the builder and placing Crimson Ladder in their inventory does not clear the request.

### Steps to reproduce

upgrade mechanists hut or fisher building

### Expected behaviour

Clipboard request should disappear as soon as the item is in stock

**Comment by rewenx** [comment]
Edit: You can resolve it by placing the ladders in the crafting grid to make the same item with a different namespace. Apparently this is known. Sorry to have wasted any time.

**Comment by Saereth** [comment]
no worries yeah, we're still hoping one day to see a proper fix from quark but for now thats the work around
