### ISSUE TITLE
Periodic Lag Spikes, libpthread-2.27.so.__pthread_cond_timedwait()

### ISSUE THREAD

**Issue by Mikeatron-User** [FTBTeam/FTB-Modpack-Issues#2569]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

https://spark.lucko.me/OSnnBrVzhH

### Describe the bug

Will be playing and there is periodic server lag that often causes us to time out. The lag seems to be random and the time between intervals is also random. Its like the server stops responding.

### Steps to reproduce

1. Create server
2. Play on server

### Expected behaviour

A smooth experience

**Comment by UnRealDinnerbone** [comment]
Looks like the spark linked expired if you are still having lag issues, please reopen the issue with a new spark profile

**Comment by soudasuwa** [comment]
Same thing, libc.so.6.pthread_cond_timedwait() is using 89.00%. Is that normal?
https://spark.lucko.me/c4q5aQMsCp
