### ISSUE TITLE
[Bug]: Entering water in End no longer triggers special effects, script error

### ISSUE THREAD

**Issue by quietust** [FTBTeam/FTB-Modpack-Issues#257]
### Modpack

FTB OceanBlock

### Modpack version

1.6.0

### Log Files

`[05Nov2021 07:59:33.654] [Server thread/ERROR] [KubeJS Server/]: Error occurred while handling event 'player.tick': ReferenceError: "h" is not defined. (server_scripts:player/end.js#17)`
(repeated hundreds of times)

### Describe the bug

In this pack, touching water in the End while not wearing appropriate swim gear poisons you, creates a floating platform, then teleports you onto it.

In version 1.6.0, this logic was extended to also support the MekaSuit. The scripts were also optimized to make use of some temporary variables, but those variables are only initialized in the Overworld code - the End code is missing them, so the script is aborting with a syntax error before applying any negative effects.

### Steps to reproduce

1. Go to the End, ensure you're in Survival mode
2. Remove all equipment
3. Jump into the water
4. Observe that you didn't get teleported

### Expected behaviour

You should get teleported onto a floating platform and poisoned.

### Additional information

Patch enclosed:
```
diff -ur oceanblock_160/minecraft/kubejs/server_scripts/player/end.js oceanblock_fixed/minecraft/kubejs/server_scripts/player/end.js
--- oceanblock_160/minecraft/kubejs/server_scripts/player/end.js      2021-11-03 16:40:55.142487800 -0600
+++ oceanblock_fixed/minecraft/kubejs/server_scripts/player/end.js    2021-11-05 08:00:36.993518700 -0600
@@ -13,6 +13,11 @@
         //Check if player gamemode, so we only do this on players in survival.
         if (e.player.creativeMode || e.player.spectator) return;

+        const h = e.player.headArmorItem;
+        const c = e.player.chestArmorItem;
+        const l = e.player.legsArmorItem;
+        const f = e.player.feetArmorItem;
+
         //If player is wearing full diving gear dont do effects
         const head =
             h == "better_diving:diving_mask" ||
```

**Comment by 2perry2** [comment]
Hello, I see that this appears to be marked as fixed in dev but a quick fix you can apply right now is to edit your end.js file found in **\kubejs\server_scripts\player** and adding the if statement containing the definitions for h,c,l and f from the swimming.js file in the same directory. Hope this helps until an official patch comes out. 
### Statement in question
if (e.player.underWater) {
		            const h = e.player.headArmorItem;
		            const c = e.player.chestArmorItem;
		            const l = e.player.legsArmorItem;
		            const f = e.player.feetArmorItem;
		}



![FTB end fix](https://user-images.githubusercontent.com/38171634/140668996-fbed732c-4bbb-4886-81cb-acc3f3df7314.png)

**Comment by quietust** [comment]
> 
> 
> Hello, I see that this appears to be marked as fixed in dev but a quick fix you can apply right now is to edit your end.js file found in **\kubejs\server_scripts\player** and adding the if statement containing the definitions for h,c,l and f from the swimming.js file in the same directory. Hope this helps until an official patch comes out.
> 
> Quick edit: I am blind didnt read the bit where you included the patch my bad
> ### Statement in question
> 
> if (e.player.underWater) { const h = e.player.headArmorItem; const c = e.player.chestArmorItem; const l = e.player.legsArmorItem; const f = e.player.feetArmorItem; }
> 
> ![FTB end fix](https://user-images.githubusercontent.com/38171634/140668996-fbed732c-4bbb-4886-81cb-acc3f3df7314.png)

You don't want to add that `if` statement, *only* the 4 lines inside it - if you code it to only set those variables when the player is underwater, it will still generate errors because it's meant to trigger the instant you *touch* water, not when you're fully submerged.
