### ISSUE TITLE
direwolf20 1.18 will not generate superflat

### ISSUE THREAD

**Issue by Satellite-SLickers** [FTBTeam/FTB-Modpack-Issues#2570]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.10.3

### Describe the bug

selecting superflat world at world generation does not create a superflat world, instead resulting in normal terrain generation

### Steps to reproduce

1) start at title screen
2) click on single player
3) click new world
4) go to more world options
5) set world type to superflat
6) press create new world
7) you will spawn in a regular minecraft world instead of a superflat one

### Expected behaviour

you should generate a superflat world

**Comment by Sunekaer** [comment]
Known issue issue with Terralith, nothing we can do about it, as they wont fix it.
You can remove the mod if you like
