### ISSUE TITLE
Archwood Leaves in Botany Pots not producing

### ISSUE THREAD

**Issue by ZieTerminator** [FTBTeam/FTB-Modpack-Issues#2571]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

Hopping Botany Pots are described in JEI as producing all 4 colors of Archwood leaves from Ars Nouveau, but only the purple and red saplings will produce leaves. My pots with purple and red saplings have produced over 500 leaves each. The green and blue have produced no leaves yet.

### Steps to reproduce

Create 4 hopping botany pots.
Put dirt in each and an Archwood sapling of each color, one color per pot.
Wait.

### Expected behaviour

I would expect some blue and green archwood leaves to be generated.

**Comment by UnRealDinnerbone** [comment]
I'm unable to reproduce this issue on the latest version, if you are still having issues on the latest version please re-open this issue
