### ISSUE TITLE
Quest not completing

### ISSUE THREAD

**Issue by Furious85** [FTBTeam/FTB-Modpack-Issues#2572]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.1.0

### Describe the bug

In the final quest to kill the void shadow it doesnt complete.

Atleast it didnt complete for me.

### Steps to reproduce

1. Go to void
2. Kill void shadow

### Expected behaviour

I expected the quest to auto complete when i killed the void shadow.

### Additional information

Maybe make it so it completes when the player gets the source stone from the loot chest after it gets killed.

**Comment by TheonlyTazz** [comment]
Good Suggestion!

I will change this in the next update!
