### ISSUE TITLE
Cabinet from Industrial Revolution deletes its content when picked up

### ISSUE THREAD

**Issue by Epicycle23** [FTBTeam/FTB-Modpack-Issues#2574]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.1.0

### Describe the bug

The content of Industrial Revolution's Cabinet gets deleted when picked up.

### Steps to reproduce

1. Place a cabinet in the world
2. Add some contents e.g. a stack of cobblestone
3. Break/pick up the cabinet
4. Place it down again

### Expected behaviour

The cabinet should either maintain or drop its content

**Comment by TheonlyTazz** [comment]
https://github.com/GabrielOlvH/Industrial-Revolution/issues/513

**Comment by Gaz492** [comment]
Unfortunately, it looks like the mod author has not resolved this issue. As a result, we will be closing this issue.
If the mod receives an update in the future, we will reconsider this.
