### ISSUE TITLE
REI "View All Categories" makes huge lag spike within AE Terminal or Wireless Terminal

### ISSUE THREAD

**Issue by realTIMematrix** [FTBTeam/FTB-Modpack-Issues#2576]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

[rei.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10493643/rei.log)

### Describe the bug

As soon as I use REI within AE2 I have a huge lag-spike. I checked the REI Log and it shows that if you want to see "Vie all categories" within AE2 Terminal it takes up to 30 seconds until everything is loaded. The same without AE2 only using REI it does takes some miliseconds to show all categories. 

Using only REI:
[21:09:53] [Render thread/TRACE] [REI] Built Recipe View in 117.2 ms for 229 categories, 0 recipes for, 0 usages for and 5 live recipe generators.

Using REI within AE2 Terminal:
21:08:05] [Render thread/TRACE] [REI] Built Recipe View in 25.43 s for 229 categories, 0 recipes for, 0 usages for and 5 live recipe generators.

### Steps to reproduce

1. Open normal inventory, using REI to show some recipe and then select "View All Categories" 
2. Do the same steps as Step 1, but within AE2 Termin

### Expected behaviour

I expect the same REI performance, no matter if I'm in an AE2 Terminal or not.

**Comment by DinnerBeef** [comment]
Unable to reproduce this bug in my current dev version. Can you let us know if this still happens when the next version comes out?
