### ISSUE TITLE
Compact machines are not chunk loaded

### ISSUE THREAD

**Issue by dklilley** [FTBTeam/FTB-Modpack-Issues#2578]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

The contents of a compact machine do not stay chunk loaded when you are not within the machine, breaking piping of items out of the machine.

This can be worked around by force chunk loading with the FTB Chunks map, however compact machine's contents are supposed to be chunk loaded when the overworld chunk the machine is within is loaded.

### Steps to reproduce

1. Create/place a compact machine
2. Add some sort of resource generation inside compact machine (e.g. resource chicken)
3. Use Pretty Pipe or Pipez to transport resources out of compact machine
4. Observe that resources do not continue to be piped, except for a limited number of stacks, unless you move in/out of the compact machine (due to the tunnel's buffer)
5. Force-load the chunk within the compact machine, as well as the chunk the machine is located in the main stoneblock dimension via the "Claimed Chunks" section of the map.
6. After being force chunk loaded, the piping works as expected.

### Expected behaviour

Compact machine contents should be chunk loaded when the corresponding overworld chunk is loaded.

**Comment by UnRealDinnerbone** [comment]
While there is normally an upgrade to enable this feature, it is disabled in this pack. So you have to use FTB Chunks as mentioned
