### ISSUE TITLE
Smithing Table (Auto) generates negative integer when connected to power, causing spam in local console

### ISSUE THREAD

**Issue by Lynch-MC** [FTBTeam/FTB-Modpack-Issues#2579]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.1

### Describe the bug

When connecting Smithing Table (Auto) from _Auto Smithing Table_ Mod, the RF internal meter shows negative integer for power level, spaming error in FTB app console:

[20:42:14] [Render thread/WARN] [io.gi.hw.au.cl.AutoSmithingTableScreen/]: toMap (-31072) is too big or too small 100000

Suggest to remove Mod immediately due to spamming.

### Steps to reproduce

1. Attach power to "Smithing Table (Auto)"
2. Right click to open GUI, hover mouse over RF power meter.  Meter shows negative integer.
3. View FTB app console for spamming error.

### Expected behaviour

Power level should be a positive integer and function properly to prevent error.

### Screenshots

![82860d0ddee0868ac0bf4c5fe84f2006](https://user-images.githubusercontent.com/123524302/214465632-8f470e85-499e-4caf-95be-c8b06f781db3.png)

**Comment by Saereth** [comment]
https://github.com/HW9636/AutoSmithingTableMod/issues/11

**Comment by HW9636** [comment]
Should be fix in [Version 1.2.4](https://www.curseforge.com/minecraft/mc-mods/auto-smithing-table/files/4366410)

**Comment by Lynch-MC** [comment]
Unfortunately, looks like still exists after I updated today to 1.2.1 (1.2.4 for AutoSmithingMod).  Although, it is purely cosmetic at this time, no longer spamming console with errors.
![84ee6a7a2769de70176814e9e7637599](https://user-images.githubusercontent.com/123524302/215913132-4d63e091-1168-4935-9aaa-3005d4173e47.png)

**Comment by HW9636** [comment]
Is it possible for you provide log files / system info or Java version? I was not able to reproduce the problem with the new version.
