### ISSUE TITLE
[Suggestion]: Add MythicBotany

### ISSUE THREAD

**Issue by e30Birdy** [FTBTeam/FTB-Modpack-Issues#258]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

I think MythicBotany would work really nice in this pack as it just makes Botania even more fun and adds some neat features to Botania.

The mana infuser: An upgrade to the terrestrial agglommeration plate that requires gold an shimmerrock underneath and besides Terrasteel allows to create Alfsteel.
Alfsteel: Made like Terrastell but with alfheim resources. Can be used to create a better armor, pylons and other things.
Dreamwood Wands: You can now make wands of the forest from dreamwood

Some new flowers:
Wither Aconite: Creates Mana from nether stars
Exoblaze: Fills the fuel of brewing stands with mana
Hellebore: Stops piglins and hoglins from zombifying in the overworld
Aquapanthus: Fills petal apothecaries and cauldrons nearby.
Raindeletia: Creates mana when it's raining. Must have a clear view to the sky. Place it on vivid grass or enchanted soil to make it produce more mana.
It also adds an alfheim dimension and some content from the norse mythology

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/mythicbotany

**Comment by quietust** [comment]
I would only approve of this if its change to the Gaia Pylon recipe was reverted, since this mod changes the recipe such that you need to fill 5 mana pools in order to do the first Gaia Guardian fight (rather than just one pool to make the two Terrasteel ingots), making an otherwise already-grindy modpack even _more_ grindy.

**Comment by e30Birdy** [comment]
> I would only approve of this if its change to the Gaia Pylon recipe was reverted, since this mod changes the recipe such that you need to fill 5 mana pools in order to do the first Gaia Guardian fight (rather than just one pool to make the two Terrasteel ingots), making an otherwise already-grindy modpack even _more_ grindy.

But how hard is it really to fill up some pools, I mean I fill up mine AFK and make mana batteries. I had this mod in a different pack and things like mana collectors and the netherstar flower make filling up pools quite easy. Plus i think FTB could make custom changes to any mod to change recipes.

**Comment by Sunekaer** [comment]
Thanks for the suggestion but we are not looking to add more mods to the pack unless highly necessary
