### ISSUE TITLE
Spawner Collecting

### ISSUE THREAD

**Issue by JodianGaming** [FTBTeam/FTB-Modpack-Issues#2581]
### Modpack

FTB Legend of the Eyes

### Is your suggestion related to a problem? Please describe.

Considering the number of spawners in the world, due to dungeons, it would be nice if we could collect some and bring them home for "farming" purposes.  There are several mods for Fabric that will allow a player to do this.  I've listed them in the mod suggestions area.

### Mod suggestion

Mekanism - https://github.com/Mekanism-Fabric/Mekanism

Enhanced Mob Spawners - https://www.curseforge.com/minecraft/mc-mods/enhanced-mob-spawners

Botania - https://www.curseforge.com/minecraft/mc-mods/botania-fabric

**Comment by TheonlyTazz** [comment]
U can make spawners with spirit
