### ISSUE TITLE
Item get wiped when put into the chest

### ISSUE THREAD

**Issue by SinonLol** [FTBTeam/FTB-Modpack-Issues#2585]
### Modpack

FTB Legend of the Eyes

### Modpack version

ex. 1.1.0

### Describe the bug

Some item put into the chest get wiped over time

### Steps to reproduce

1. Set two iron chest into double iron chest
2. Shift left click oak log into the chest
3. Oak log get wiped but it is inconsistent. This bug happen with random items but seem only vanilla minecraft item

### Expected behaviour

Fixed or updated mod

### Screenshots

![Screenshot (1813)](https://user-images.githubusercontent.com/123566325/214591670-e9c63711-8d19-4fe4-b098-0495495fc130.png)
![Screenshot (1814)](https://user-images.githubusercontent.com/123566325/214591703-c74b955b-52bc-42c0-b16b-81f9097e1b34.png)

### Additional information

This bug is so inconsistent and with random item.

**Comment by TheonlyTazz** [comment]
Do u happen to have an Indrev Machine (Generator or some sort) next to it?
maybe that is set to autopull

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/214609459-1ed571f2-46a1-4061-9529-56cde8ab581d.png)
