### ISSUE TITLE
Planter and Rich soil planter not working

### ISSUE THREAD

**Issue by SinonLol** [FTBTeam/FTB-Modpack-Issues#2586]
### Modpack

FTB Legend of the Eyes

### Modpack version

ex. 1.1.0

### Describe the bug

Planter and RIch soil planter not work

### Steps to reproduce

1. RIght click any seed to Planter or RIch soil planter 

### Expected behaviour

FIxed or use botany pot

**Comment by TheonlyTazz** [comment]
Updated the Mod, still cant plant seeds

Automating wood is definetly doable with other mods available (Create or Indrev)
