### ISSUE TITLE
[Bug]: Stone Block 3 fatal exception whil installing modpack

### ISSUE THREAD

**Issue by ninexdd1** [FTBTeam/FTB-Modpack-Issues#2588]
### Mod

Stone Block 3

### Mod version

1.5.0

### Forge / Fabric version

1.19.2

### Modpack & version

Stone Block 3

### What issue are you having?

Stone Block 3 cant dowload in ftb app 
fatal exception whilist installing modpack
![image](https://user-images.githubusercontent.com/123078067/213731165-96398158-5ac6-4a18-9b86-14a572980b7c.png)

### Crashlogs

- 
![image](https://user-images.githubusercontent.com/123078067/213731346-2a83d51a-3138-4b67-a4e4-0000ca0bd172.png)
fatal exception whilist installing modpack

### Steps to reproduce

open the FTB App
Click on Browse
Press Green install button next to Stoneblock 
3.1.5.0
Click Install
Fatal Exception whilst installing modpack

### Anything else to note?

I cant dowload any modpack

**Comment by UnRealDinnerbone** [comment]
This looks like an issue with the FTB App and not Stoneblock 3 if this issue is still happens, please reopen the issue on the app issue tracker https://github.com/FTBTeam/FTB-App/issues
