### ISSUE TITLE
[Bug]: Creative chemical tank still not craftable (1.6.0), recipe seems to have lost the required tank contents

### ISSUE THREAD

**Issue by dizzystem** [FTBTeam/FTB-Modpack-Issues#259]
### Modpack

FTB Oceanblock

### Modpack version

1.6.0

### Describe the bug

In 1.6.0, the recipe for the creative chemical tank seems to have changed to require empty ultimate chemical tanks instead of two each of ethylene, uranium hexafluoride, nutritional paste, and D-T fuel. I'm not sure if this is intentional, but it doesn't seem to have fixed the crafting recipe.

![javaw_ryfax3Kpmj](https://user-images.githubusercontent.com/25002736/140527560-9151a2cd-7ea0-4d1d-8e8a-1ad28027b803.png)

I had the old recipe in my ultimate crafting table using the filled chemical tanks, which did not work. I then changed them to empty chemical tanks, which still did not work.

![javaw_0pPMyuat13](https://user-images.githubusercontent.com/25002736/140527740-6d24a38a-fe0a-4704-ac12-1b36eeab9dce.png)

I noticed that there was an NBT tag on the empty chemical tanks in the recipe, while there wasn't on the empty chemical tanks I was trying to craft with. This might be why the recipe isn't working.

![javaw_fZHLKd4clE](https://user-images.githubusercontent.com/25002736/140527983-5c07f3ec-832a-417d-828e-d2a0af8d12ef.png)

### Steps to reproduce

1. Fill the ultimate crafting table with the creative chemical tank recipe.
2. It doesn't display anything in the output slot.

### Expected behaviour

The output slot should have a creative chemical tank in it.

**Comment by dizzystem** [comment]
Lachian from the discord told me how to check the NBT tags - the recipe wants
`'{BlockEntityTag:{GasTanks:[{stored:{amount:512000L,gasName:"mekanism:nutritional_paste"},Tank:0b}],id:"mekanism:ultimate_chemical_tank"}}'`
and the filled tank has
`'{mekData:{GasTanks:[{Tank:0b,stored:{gasName:"mekanism:nutritional_paste",amount:512000L}}]}}'`

**Comment by dizzystem** [comment]
I tried editing the recipe in my copy and managed to create a fixed version of it. In \kubejs\server_scripts\mods\recipes.extendedcrafting.js, change the creative gas tank recipe to:

```    //Creative Gas Tank -
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            "ABABABABA",
            "BABABABAB",
            "ABDBABEBA",
            "BABCECBAB",
            "ABADFGABA",
            "BABCHCBAB",
            "ABHBABGBA",
            "BABABABAB",
            "ABABABABA",
        ],
        key: {
            A: {
                item: "mekanism:alloy_atomic",
            },
            B: {
                item: "mekanism:ingot_osmium",
            },
            C: {
                item: "mysticalagradditions:creative_essence",
            },
            D: {
                type: "nbt_ingredient_predicate:nbt_includes",
                item: "mekanism:ultimate_chemical_tank",
                count: 1,
                nbt: '{mekData:{GasTanks:[{Tank:0b,stored:{gasName:"mekanism:ethene",amount:512000L}}]}}',
            },
            E: {
                type: "nbt_ingredient_predicate:nbt_includes",
                item: "mekanism:ultimate_chemical_tank",
                count: 1,
                nbt: '{mekData:{GasTanks:[{Tank:0b,stored:{gasName:"mekanismgenerators:fusion_fuel",amount:512000L}}]}}',
            },
            F: {
                item: "mekanism:creative_fluid_tank",
            },
            G: {
                type: "nbt_ingredient_predicate:nbt_includes",
                item: "mekanism:ultimate_chemical_tank",
                count: 1,
                nbt: '{mekData:{GasTanks:[{Tank:0b,stored:{gasName:"mekanism:nutritional_paste",amount:512000L}}]}}',
            },
            H: {
                type: "nbt_ingredient_predicate:nbt_includes",
                item: "mekanism:ultimate_chemical_tank",
                count: 1,
                nbt: '{mekData:{GasTanks:[{Tank:0b,stored:{gasName:"mekanism:uranium_hexafluoride",amount:512000L}}]}}',
            },
        },
        result: {
            item: "mekanism:creative_chemical_tank",
        },
    });
```

**Comment by Sunekaer** [comment]
Interesting worked in my dev, ill have a look at it again
