### ISSUE TITLE
Requester recipe 

### ISSUE THREAD

**Issue by David45123** [FTBTeam/FTB-Modpack-Issues#2590]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.1.0

### Log Files

https://pste.ch/uzazekusih.http

### Describe the bug

Opening the requester recipe in any ae terminal causes a crash

### Steps to reproduce

open ae terminal
left click requester for recipe & just putting my mouse over the the item in REI causes a crash while having ae terminal open

### Expected behaviour

open requester recipe

**Comment by TheonlyTazz** [comment]
I have updated the mods already on my Dev-Instance and couldnt replicate this issue, ill put this on the backburner for now and we will see if it still happens on the next update

**Comment by TheonlyTazz** [comment]
Assuming that this issue got resolved, as we updated the mods and i cannot reproduce it,
if it does happen again, feel free to reopen/create a new issue
