### ISSUE TITLE
Thermal Nickel Nuggets cannot make ingots

### ISSUE THREAD

**Issue by mattengelken** [FTBTeam/FTB-Modpack-Issues#2592]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.1

### Describe the bug

Nickel nuggets from thermal cannot be made into ingots. the nickel ingot recipe shows forge:nuggets/nickel for the outer 8 nuggets but requires an immersive engineering nickel nugget for the center 

### Steps to reproduce

1. Induction smelt raw iron
2. try to craft resulting nickel nuggets into nickel ingot

### Expected behaviour

entire nickel ingot recipe should accept forge:nuggets/nickel

### Screenshots

![2023-01-25_21 20 40](https://user-images.githubusercontent.com/36420373/214752985-333d5efc-c638-4d3f-a651-3dab3498bdab.png)

**Comment by Saereth** [comment]
These should no longer be obtainable after the next update, all nugget outputs should output the IE variants now
