### ISSUE TITLE
Crafting Tweaks not working with Tinkers Construct Crafting Station

### ISSUE THREAD

**Issue by Xaverix** [FTBTeam/FTB-Modpack-Issues#2594]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

Crafting Tweaks are not working for Crafting Station from Tinkers Construct. Mod description claims to work with modded crafting tables and it is working with other modpacks.

### Steps to reproduce

1. Craft Crafting Station
2. Bind any free keybind to Crafting Tweaks "Toggle Buttons" setting
3. Open Crafting Station and press the set keybing
4. Nothing happens

### Expected behaviour

Buttons should appear after pressing keybind

**Comment by DinnerBeef** [comment]
Mod Issue See: https://github.com/TwelveIterationMods/CraftingTweaks/issues/151

**Comment by UnRealDinnerbone** [comment]
Close this issue as the mod issue has been open since April, without any update
