### ISSUE TITLE
Enable capabiltiy to store experience

### ISSUE THREAD

**Issue by orbidlo** [FTBTeam/FTB-Modpack-Issues#2595]
### Modpack

FTB Legend of the Eyes

### Is your suggestion related to a problem? Please describe.

One thing that frustrates me is not being able to store my exp in some way. I often die in exploring and loose my exp and hate being forced to create exp mob farm to be able to enchant. I read on [supplementaries wiki](https://github.com/MehVahdJukaar/Supplementaries/wiki/Tweaks#xp-bottling) that it should enable bottling of exp, but it didn't work for me. Maybe this is one of the things available in forge version but not in fabric? Consider adding some way to store experience please.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/bottle-your-xp

**Comment by TheonlyTazz** [comment]
```
    "bottle_xp": {
      "enabled": false,
      "cost": 2
    },
```

Bottle XP was turned off by default, ill be turning it on and give it a test
