### ISSUE TITLE
Unbreakable sluice

### ISSUE THREAD

**Issue by ShadowStriker102** [FTBTeam/FTB-Modpack-Issues#2597]
### Modpack

FTB OceanBlock

### Modpack version

1.12.0

### Describe the bug

I accidently used the thermal series wrench on the iron sluice and broke it. but because the sluuice was facing the wrong direction the wheel part didn't break and became an immortal block that couldnt break even in creative mode. It does "break" but when you place a blcok there, it becomes the second part of the sluice.

### Steps to reproduce

1. place iron sluice
2. use thermal series wrench on sluice to change direction
3. break the core sluice
4. try to break the wheel part of slucie
5. if it breaks try to walk over or place block there

### Expected behaviour

i expected it to break and not become an immortal block

### Screenshots

![image](https://user-images.githubusercontent.com/123655406/214884313-34e0e9fb-af4e-4339-9008-2c57a630f245.png)

**Comment by rreilly-edr** [comment]
This also the case with huts that have the sluice in the from world gen.
