### ISSUE TITLE
Crash when pressing Middle mouse button

### ISSUE THREAD

**Issue by AlexanderI32** [FTBTeam/FTB-Modpack-Issues#2598]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10511307/latest.log)

### Describe the bug

Whenever I click middle mouse button to sort my own inventory it crashes the game. Didn't happen until I crafted diamond netherite pickaxe and sword.

### Steps to reproduce

1. Click middle mouse button to sory own inventory
2. Crashes the game

### Expected behaviour

Sorting inventory

**Comment by TheonlyTazz** [comment]
https://github.com/terrarium-earth/Spirit/pull/59
waiting for Spirit to fix this
this is likely caused bcause of the bound Soul Shard in your inventory, not the pickaxe or sword

**Comment by AlexanderI32** [comment]
> [terrarium-earth/Spirit#59](https://github.com/terrarium-earth/Spirit/pull/59) waiting for Spirit to fix this this is likely caused bcause of the bound Soul Shard in your inventory, not the pickaxe or sword

Indeed I have found out the Soul Shard was the issue, I was just about to come here to update

**Comment by Epicycle23** [comment]
Can confirm I had that issue too but couldn't figure out what was causing it, but I also had a soul shard in my inventory when it happened.
