### ISSUE TITLE
[Bug]: Recipe for Cobble Gen Tier 4 Doesn't work

### ISSUE THREAD

**Issue by Kevin-Marsh** [FTBTeam/FTB-Modpack-Issues#26]
### Modpack

FTB OceanBlock

### Modpack version

1.1.0

### Describe the bug

I am trying to produce the tier 4 cobble gen using molten rose gold, a tier 3 cobble gen and 2 slime blocks. The sub zero jar recipe isn't showing up. The molten rose gold is in a tank connected to the jar with cast iron tube. And the slime and tier 3 have been tested in my inventory and in a chest connected with tube as well. The water to ice recipe has worked with this setup but not the cobble gen.

### Steps to reproduce

1. Place jar over ice, packed ice, blue ice or dry ice.
2. Connect molten rose gold tank to jar with cast iron tube
3. Try to produce the cobble gen tier 4 recipe

### Expected behaviour

Produce the tier 4 cobble gen

**Comment by Sunekaer** [comment]
Could you double-check?
The recipe shows for me and works for me
![image](https://s1.sunekaer.com/i/27-09-2021_18-39-13_javaw.png)

**Comment by Kevin-Marsh** [comment]
I tried every combination but I never realized that there are two different kinds of Tinker's slime blocks. 1 made with 4 slimes and 1 made with 9 slimes. The recipe works, I am just an idiot. Thanks for your help with everything.

**Comment by hammackj** [comment]
Worked for me with normal slime blocks.
