### ISSUE TITLE
[Bug]: Some Mystical Agriculture Botany Pot recipes require wrong soil tiers

### ISSUE THREAD

**Issue by quietust** [FTBTeam/FTB-Modpack-Issues#260]
### Modpack

FTB OceanBlock

### Modpack version

1.6.0

### Describe the bug

Nearly all of the Botany Pot recipes for Mystical Agriculture require that the seed require the same tier or higher of soil - Inferium for tier 1, Prudentium for tier 2, Tertium for tier 3, Imperium for tier 4, Supremium for tier 5, and Insanium for tier 6.

However, the following recipes are requiring the wrong tier:
* Sky Stone (tier 3) requires Imperium (tier 4)
* Certus Quartz (tier 3) requires Imperium (tier 4)
* Fluorite (tier 4) accepts Prudentium (tier 2)
* Netherite (tier 5) accepts Imperium (tier 4)
* Nether Star (tier 6) accepts Supremium (tier 5)
* Dragon Egg (tier 6) accepts Supremium (tier 5)

Additionally, some recipes are even allowing _ordinary_ soil types:
* Energized Steel (tier 4)
* Blazing Crystal (tier 4)
* Niotic Crystal (tier 5)
* Spirited Crystal (tier 5)
* Uraninite (tier 5)
* Blizz (tier 3)
* Blitz (tier 3)
* Basalz (tier 3)
* Signalum (tier 4)
* Lumium (tier 4)
* Enderium (tier 5)

Oddly, a few of the mixed up seeds are also ones that aren't even craftable in the first place:
* Iridium (tier 5) accepts Prudentium (tier 2)
* Platinum (tier 5) accepts Prudentium (tier 2)

### Steps to reproduce

1. Place a Botany Pot
2. Place Tertium Farmland in it
3. Attempt to plant a Sky Stone seed or a Certus Quartz seed in it, observe that it doesn't accept it
4. Replace the Tertium Farmland with Imperium Farmland
5. Try again and observe that they both work now

### Expected behaviour

Botany Pots should require the same tier of soil as the base seed

### Additional information

I also noticed that all of the Garden Cloche recipes seem to accept one tier of soil _below_ the seed (except for the tier 6 seeds which aren't growable there at all), though that might be intentional because Garden Cloches require power and water in order to run,

**Comment by Sunekaer** [comment]
Mod issue, a reminder to self create an issue on Botany Pot

**Comment by Sunekaer** [comment]
https://github.com/Darkhax-Minecraft/BotanyPots/issues/199

**Comment by Raidobw2** [comment]
`BotanyPots-1.16.5-7.1.38.jar` is now available to fix this: https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/3793411
