### ISSUE TITLE
FTB Direwolf20 1.19 - server crashing on stop

### ISSUE THREAD

**Issue by bancey** [FTBTeam/FTB-Modpack-Issues#2600]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.1

### Log Files

https://pste.ch/enelafipiq

### Describe the bug

Shortly after issuing a `/stop` command, the server crashes with the error `[net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/AbstractClientPlayer for invalid dist DEDICATED_SERVER`

The full stack trace can be found in the log file above ☝️ 

I've been able to reproduce this across two server instances on different machines (both running Ubuntu 22.04.5) using both the bundled version of Java and version `openjdk 17.0.5 2022-10-18` installed via apt.

### Steps to reproduce

1. Install a Direwolf20 1.19 server using the serverinstall file (version 1.1.1)
2. Start the server, wait for it to finish loading for the first time
3. Play on the server (or just skip this step)
4. Issue a `stop` command, either in game or from the server console
5. The server crashes shortly after executing the stop command, not saving the world correctly (this can be worked around by issuing a `save-all flush` command prior to stopping)

### Expected behaviour

The server should stop cleanly, saving the world as it does so.

**Comment by Saereth** [comment]
Bug caused my moonlight lib, marked as fixed for next update
