### ISSUE TITLE
Suggest Openblocks Elevator Mod Fabric Port

### ISSUE THREAD

**Issue by farrucho** [FTBTeam/FTB-Modpack-Issues#2602]
### Modpack

FTB Legend of the Eyes

### Is your suggestion related to a problem? Please describe.

I am tired of wasting my time going to my underground base on stairs. In your old modpacks the mod OpenBlocks used to be there with the elevator block. There is a port of this mod to Fabric. I was hoping you could use it in your modpacks. Thanks and great work :)

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator-fabric
This mods adds the 1.12.2 elevator from forge to fabric. Really coold mod

**Comment by Morasiu** [comment]
I would also love that!
