### ISSUE TITLE
Crash server and need a backup

### ISSUE THREAD

**Issue by HunterCat05** [FTBTeam/FTB-Modpack-Issues#2603]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

[crash-2023-01-23_22.41.59-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10521281/crash-2023-01-23_22.41.59-server.txt)

### Describe the bug

When you click on "Comparator" at the Netherite Furnace the server shutdown and while crash forever.

### Steps to reproduce

1. Place a netherite furnace on a server
2. Open the menu and open the config
3. select "comparator"
4. Enjoy

### Expected behaviour

Work ..?

### Screenshots

![image](https://user-images.githubusercontent.com/123761723/215170048-fb6a8d7d-7f99-483c-a2fc-f0983080440f.png)

**Comment by UnRealDinnerbone** [comment]
same as #3166
