### ISSUE TITLE
Crash when adding Counting Filter and Basic Filter to a Requestor

### ISSUE THREAD

**Issue by Addar** [FTBTeam/FTB-Modpack-Issues#2605]
### Modpack

FTB StoneBlock 3

### Modpack version

1.11.0

### Log Files

[crash-2023-01-27_13.39.49-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10522615/crash-2023-01-27_13.39.49-server.txt)

### Describe the bug

I have a bank of requestors and I have been adding items that I want to keep on hand. I added a Basic Filter and a Counting Filter from LaserIO to a requestor set to 64. Within a few seconds or closing the UI and walking away my game crashed. Upon reloading the game I immediately removed the items from the requestor.  I then checked and some of the items needed to make those 2 filters were not setup in a requestor set. I added then added a logic chip and glass pane to the requestor. A few minutes later I walked back over and added a Basic Filter and a Counting Filter back to the requestor. Within a few seconds of closing the UI my game crashed again. 

### Steps to reproduce

1. Open requestor
2. add a Basic Filter and a Counting Filter to a requestor
3. close the UI of the requestor
4. within a second or two your game will crash

### Expected behaviour

To not have the game crash and be able to add the 2 filters to a requestor

### Screenshots

https://i.imgur.com/rctrSfO.png

**Comment by DinnerBeef** [comment]
Seems to be a mod issue.
See: https://github.com/refinedmods/refinedstorage/issues/3485

**Comment by UnRealDinnerbone** [comment]
Close this issue as the mod issue has been open since May, without any update
