### ISSUE TITLE
Waypoint beacons break shader between 1.3.0 and 1.4.0

### ISSUE THREAD

**Issue by Jethora** [FTBTeam/FTB-Modpack-Issues#2606]
### Modpack

FTB Inferno

### Modpack version

1.4.0

### Describe the bug

Updated Inferno from 1.2.1 to 1.5 and got a visual glitch with waypoints. I tried updating the shader, but that didn't fix it.
Ended up downgrading my instance to see if it was the forge update in 1.5. but 1.4 still had the problem. 
Downgraded again to 1.3 and the glitch is fixed.

### Steps to reproduce

1. Update to 1.4.0
2. Place a waypoint.
3. Turn on shader.

### Expected behaviour

Waypoint to properly beacon

### Screenshots

1.5.0 and 1.4.0
![2023-01-26_23 08 21](https://user-images.githubusercontent.com/123700736/215185294-8aa3d6ae-7c36-4dee-b437-506d9369c1ef.png)
![2023-01-26_23 08 31](https://user-images.githubusercontent.com/123700736/215185314-80d8ee64-ce4c-4fa3-8118-2bb958e4fa55.png)

1.3.0
![2023-01-27_12 44 40](https://user-images.githubusercontent.com/123700736/215185334-281dfdc6-b1a6-42a0-83af-5e81a1a78345.png)
![2023-01-27_12 44 53](https://user-images.githubusercontent.com/123700736/215185344-abfefd47-2e69-4f3d-9e05-9570ac184262.png)

**Comment by Saereth** [comment]
Reported to dev but unlikely to get fixed, unfortunately the update fixes some critical crash errors with rubidium so better to have the weirdness than the crashes.
