### ISSUE TITLE
direwold20  1.19

### ISSUE THREAD

**Issue by gzcwnk** [FTBTeam/FTB-Modpack-Issues#2607]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10523375/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10523378/debug.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10523380/console.log)
[debug-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10523382/debug-1.log.gz)
[crash-2023-01-28_08.21.30-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10523402/crash-2023-01-28_08.21.30-server.txt)

### Describe the bug

game crashes

### Steps to reproduce

start game

### Expected behaviour

game doesnt crash

### Screenshots

na

### Additional information

This kept happening in 2.0.4beta?

**Comment by Saereth** [comment]
I've forwarded this on to the FTB Chunks dev for resolution

**Comment by MercAngel** [comment]
i had the same error until it is fix if you have placed a digital miner in your world you will have to remove it.

**Comment by Saereth** [comment]
We have a fix coming for this soon for FTB Chunks, should be out today or tomorrow I believe
