### ISSUE TITLE
Wall Latern model appears to be bugged/missing

### ISSUE THREAD

**Issue by toolongtospell** [FTBTeam/FTB-Modpack-Issues#2609]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.1.1

### Describe the bug

I found one of the POI (points of interest) that points you to the closest town. On that structure, there is a 'Wall Lantern' that has a bugged or missing texture/model; the block as a purple and black checkered box.
![image](https://user-images.githubusercontent.com/8914789/215242132-61ddb9d9-9e43-4d53-a85e-d0c230176fff.png)

### Steps to reproduce

N/A

### Expected behaviour

Working model

### Screenshots

![image](https://user-images.githubusercontent.com/8914789/215242146-0ed9d419-8820-4263-b7eb-da3e7faedc01.png)

**Comment by TheonlyTazz** [comment]
Do u happen to have CTM Refrabricated enabled?

That mod causes it and its a known issue, thus thats why the mod is disabled, and actually shouldnt be in the pack anymore

**Comment by toolongtospell** [comment]
I installed the pack directly from a launcher and didn't make any modifications to the game files.
