### ISSUE TITLE
Mod Suggestion: EnderIO Rewrite

### ISSUE THREAD

**Issue by bumv** [FTBTeam/FTB-Modpack-Issues#2610]
### Modpack

FTB Presents Direwolf20 1.19

### Mod suggestion

https://github.com/SleepyTrousers/EnderIO-Rewrite

EnderIO Spawners provide a more Tech oriented kind of mob farm, rather than apotheosis (which is a bit more explorey and magical). EnderIO also allows for similar IOing to LaserIO without the lasers and just conduits.

I'm not sure if it the rewrite is complete, but if it is it would be cool, thanks for considering this.

**Comment by Saereth** [comment]
This is and has been on our radar for a while, sadly the rewrite is still very alpha and not yet ready for large scale inclusion in packs. We'll continue to monitor though, we are excited for it as well!

**Comment by bumv** [comment]
Awesome thanks.
