### ISSUE TITLE
Withers are invulnerable long after their summons have been killed

### ISSUE THREAD

**Issue by RyanTurner105** [FTBTeam/FTB-Modpack-Issues#2611]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.1.1

### Describe the bug

In a test world, I summoned the wither. I was testing out how strong it was. I ended up summoning and killing the wither about 20 times. 

In each of those attempts, the wither became invulnerable immediately after summoning his skeletons. I was able to 1-shot each of the skeletons, and normally after about 1-3 seconds, all the summons would be dead. However, the wither would always be invulnerable for much longer, normally ~30 seconds, but once was invulnerable to sword and bow for over 3 minutes. I learned later in the discord that this was a bug.

### Steps to reproduce

1. Summon wither with soul sand and wither skulls
2. Damage it until summons happen. Check that you cannot damage the wither by attempting to hurt it while the darkness effect is active.
3. Kill summons as quick as you can.
4. Attempt to hit the wither, over and over, with either sword (I tested with diamond sword) or bow (crystal bow). 
5. Time how long it takes until wither can again be hurt by you.

### Expected behaviour

I expected the wither's invulnerability to drop when the summons had been killed, which was confirmed by Tazz on discord.

**Comment by TheonlyTazz** [comment]
Just double checked;

The wither is invulnerable for 30 Secs, not longer.
However, the Summons didnt actually make it vulnerable again, this has been fixed indev, will come out in update v1.2
