### ISSUE TITLE
IndRev plates missing plates tag

### ISSUE THREAD

**Issue by orbidlo** [FTBTeam/FTB-Modpack-Issues#2612]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.1.0

### Describe the bug

IndRev plates lack the `#plates` tag and make it cumbersome to filter them in create attribute filter.

### Steps to reproduce

1. create attribute filter
2. add as reference any IndRev plate
3. no `#plates` tag :(

### Expected behaviour

All IndRev plates have proper plates tag to allow filtering

### Additional information

![image](https://user-images.githubusercontent.com/9553279/215258165-9ac3e36e-fd9a-4c17-92b5-f4c28104f597.png)

**Comment by TheonlyTazz** [comment]
thanks! added them for v1.2
