### ISSUE TITLE
A curropted save I need to fix

### ISSUE THREAD

**Issue by MrZERO00001** [FTBTeam/FTB-Modpack-Issues#2613]
### Modpack

FTB Ultimate

### Modpack version

1.1.2

### Log Files

[debug-4.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10527447/debug-4.log.gz)
[debug-5.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10527448/debug-5.log.gz)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10527449/latest.log)

### Describe the bug

My local world save suddenly curropted. The world just froze and I cannot do anything. When I break blocks, they do not drop. When I re-enter the save, the blocks I broke are no longer broken. The mobs are just frozen and I cannot interract with them. Even if I try to walk, when I re-enter my world I find myself in the same exact location. Additionally, I cannot quit the save without the intire instance crashing.

### Steps to reproduce

1. Open FTB app 
2. Launch the FTB ultimate modpack
3. Load the save
4. Notice the curropted world.

### Expected behaviour

To help me fix the curropted save.

### Additional information

-I do not know if this might help, but I had this same exact isuue with my save in mindcrack pack.
-The issue might be because of a spawner I made using _**soul shards 1**_  mod, but I am not sure. (I also used soul shards 1 to make a spawner in my mindcrack save)

thank you.
_little note: English is my second languge, so I am sorry if my descreption is not clear (:_

**Comment by manmaed** [comment]
1.4.7

**Comment by manmaed** [comment]
This i an old mod pack and is unlikely to get updated added @Raidobw2 if he gets time

**Comment by Gaz492** [comment]
A bit late getting back to you, but if you still have the world would you be able to upload it so I can take a look?
I may be able to fix it for you, but if you can restore a backup of the world I would suggest that, otherwise theres not much we can do as this is a very old modpack and they are very prone to breaking.
