### ISSUE TITLE
Data Card encoder broken

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#2615]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.1.0

### Describe the bug

For some reason the data card encoder refuses to count down after adding the ores, and clicking write. it consumes the ores but stays at 10s.

### Steps to reproduce

put in a stack of iron and coal ore
click write.

put in a stack of iron ore
put in a stack of stone
put in a half stack of enriched nicolite 
click write

### Expected behaviour

To write a usable ore card.

**Comment by tyler489** [comment]
Reported 
https://github.com/GabrielOlvH/Industrial-Revolution/issues/511
&
https://github.com/GabrielOlvH/Industrial-Revolution/issues/516

**Comment by Morasiu** [comment]
I've had the sam problem. But when I connected Data card by energy cables (from Industrial Revolution) it worked.

**Comment by tyler489** [comment]
Mine only worked when it was directly touching, the cables wouldn't output.

**Comment by TheonlyTazz** [comment]
added some quest information about this in the next update

**Comment by orbidlo** [comment]
I had data encoder touching lapis battery mk3, fully charged and configured to output on the side. I put in full stack of deepslate diamond ore, 3 stack of stone and hit write and it got stuck at 21%, the energy in battery never run out. I tired again with deepslate lead ore + 3 stacks of stone and exatly the same thing happened. I'm really stumped in what to do to make it work and dismayed I lost the ore.
