### ISSUE TITLE
Crushed Tin from Create does not process into Tin Nuggets

### ISSUE THREAD

**Issue by Firepoppy5** [FTBTeam/FTB-Modpack-Issues#2616]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0.0

### Describe the bug

I put Raw Tin through the Create Crushing Wheels, and got back Crushed Tin. I went to put it in my Bulk Washing setup in order to refine it into nuggets, but after a longer than usual time, it wouldn't convert into nuggets. I went into JEI, and hit "u" on the crushed tin, and it wouldn't show it's uses. I double checked by hitting "r" on it to make sure that JEI wasn't bugging out, and the recipe for Crushed Tin showed just fine. A second attempt of hitting "u" confirmed that there isn't a recipe to convert Crushed Tin to Tin Nuggets. I haven't checked what other metals are missing "Crushed" to "Nuggets" recipes, but I will be doing that before going forward with my crafting. Thank you for your time!

### Steps to reproduce

1. Put Raw Tin through the Create Crushing Wheels
2. Get back Crushed Tin
3. Put Crushed Tin in front of a Create Fan blowing through Water
4. Don't Profit

### Expected behaviour

I expected to get Tin Nuggets back from the Crushed Tin

### Screenshots

![2023-01-29_08 24 32](https://user-images.githubusercontent.com/55170950/215332986-f9c793b5-2540-418d-9c3c-948518c9f1b9.png)

### Additional information

This is less of a bug and more of a missed recipe, I wasn't sure if this should go under bugs or suggestions. It definitely affects the gameplay somewhat negatively

**Comment by TheonlyTazz** [comment]
Update the pack
