### ISSUE TITLE
KubeJS crashes modpack when running on adoptium

### ISSUE THREAD

**Issue by aaronliu0130** [FTBTeam/FTB-Modpack-Issues#2619]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0 only

### Log Files

See adoptium/adoptium-support#666

### Describe the bug

See adoptium/adoptium-support#666 . Modpack crashes soon after loading the sky of the world.

### Steps to reproduce

1. Install eclipse adoptium jdk version that is compatible with 1.19
2. Use jdk for modpack
3. Launch and join world
4. wait

### Expected behaviour

Doesn't crash when loading world

**Comment by Sunekaer** [comment]
Open configs -> flywheel-client.toml

change:

backend = "INSTANCING" to backend = "OFF"
