### ISSUE TITLE
Cooking for blockheads oven cannot be charged by any available means

### ISSUE THREAD

**Issue by orbidlo** [FTBTeam/FTB-Modpack-Issues#2620]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.1.1

### Describe the bug

I tried using powah solar + cables and IndRev battery + cables and nothing charges the blockhead oven with electricity upgrade.

### Steps to reproduce

1. Get Cookign for blockheads oven
2. Install Heating unit to use electricity
3. connect powah solar + cable or indrev battery + cable at the bottom of the oven with available electricity
4. oven is not charged
5. despair :(

### Expected behaviour

Oven gets charged using either indrev or powah cables

**Comment by TheonlyTazz** [comment]
Disabled the recipe for now to avoid the issue,
already reported

https://github.com/TwelveIterationMods/CookingForBlockheads/issues/598

**Comment by DinnerBeef** [comment]
The issue has been resolved for a newer version of the mod. However, it was not fixed for this version of minecraft. As a result, this issue will now be closed.
