### ISSUE TITLE
Endeavour: Crash when killed

### ISSUE THREAD

**Issue by JonathSpirit** [FTBTeam/FTB-Modpack-Issues#2621]
### Modpack

FTB Endeavour

### Modpack version

1.9

### Log Files

https://pastebin.com/72LBmga7

### Describe the bug

I have installed a 1.9 FTB Endeavour server and, when killed by anything (example here with a centipede from alexsmobs), the server crash and destroy the player inventory without a way to get it anymore

### Steps to reproduce

1. Create a server
2. Go to a hostile mob
3. Get killed by it
4. Crash

### Expected behaviour

The server should not crash and should corretly let the player respawn

**Comment by JonathSpirit** [comment]
note, bumping :
collective to collective-1.16.5-5.49
justplayerheads to justplayerheads_1.16.5-2.0
justmobheads to justmobheads_1.16.5-6.2

fix the crash

**Comment by lorddane** [comment]
I am having the same issue. The server crashes and reboots if I am killed.

**Comment by manmaed** [comment]
This issue is stale
