### ISSUE TITLE
[Possibly an Upstream Bug] Crash with Mechanical Belts and Smart Chutes

### ISSUE THREAD

**Issue by JustANormalHooman** [FTBTeam/FTB-Modpack-Issues#2622]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.1

### Log Files

https://mclo.gs/yR8JdZh

### Describe the bug

When placing a mechanical belt above Create Smart Chutes that are connected to Crushing Wheels, the client will crash.

### Steps to reproduce

1. Set down a set of Crushing Wheels
2. Set a Smart Chute on top of the Crushing Wheels
3. Attempt to set a mechanical belt running over the Smart Chute
4. Crash.

### Expected behaviour

The game should not crash when placing belts above smart chutes, as it is expected that the smart chute will pull matching objects from the belt.

### Additional information

This is possibly an upstream bug with the Create mod. I am reporting it here just in case it isn't an upstream bug and it's something that needs to be fixed on the pack side instead of the mod itself.

**Comment by Saereth** [comment]
cant reproduce now after the create update, marking fixed but please reopen if you can reproduce in the 1.4.0 DW update once its out
