### ISSUE TITLE
(1.2.0)Client crash loading tooltip of raw Zinc

### ISSUE THREAD

**Issue by NEURALDELVERM** [FTBTeam/FTB-Modpack-Issues#2625]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.2.0

### Describe the bug

I crash when I hover over a Create item, Zinc.

### Steps to reproduce

Launch a 1.2.0 server, self hosted.
Have another client on the same network join you using your IPv4 address.
Mine some Zinc Ore in-game.
Open your inventory, and hover hover the item you collected.

### Expected behaviour

The game shows the tooltip

**Comment by NEURALDELVERM** [comment]
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10543810/debug.log)

Not sure if this is the log from when I crashed. Would the .gz files work for you?

**Comment by FagSoft** [comment]
Seeing as you're on 1.2.0 this is most likely the Create Display bug that was fixed in 1.2.1. I recommend updating to (at least) that version, and see if the issue persists.

**Comment by NEURALDELVERM** [comment]
We are actually playing 1.3.2 now- this specific issue is no longer, but unfortunately we have discovered a new but similar bug. 
In short, searching for something like "Bone meal" in creative(all categories) and accidentally hovering over tooltips for included enchanted books can cause a client crash with many overflow errors shown in server console.
I will mark this issue as fixed, should I create a new report for this other bug once I can collect some sort of log?

**Comment by FagSoft** [comment]
I would advice to make a new bug report, yes.
