### ISSUE TITLE
Modular mining drill can be upgraded bypassing need for netherite

### ISSUE THREAD

**Issue by orbidlo** [FTBTeam/FTB-Modpack-Issues#2626]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.1.1

### Describe the bug

There are two way to get modular drill. One crafting directly using netherite drill, second using diamond drill and mk4 upgrade which bypasses need for netherite. It felt kinda cheaty, is this intended? 

### Steps to reproduce

1. Craft mk4 upgrade
2. Craft diamond drill
3. Combine to modular drill and bypass netherite requirement.

### Expected behaviour

Both approaches need netherite to be balanced.

**Comment by TheonlyTazz** [comment]
yes this is intended, as u require the increased costs of the upgrades.
I added the recipes bcause people were complaining that you couldnt upgrade the drills at all.
I can add the drill item to the recipe as an addition, that would make a good perhaps
