### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Eoicq** [FTBTeam/FTB-Modpack-Issues#2627]
### Modpack

FTB StoneBlock 3

### Modpack version

1.4.3

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10545488/latest.log)

### Describe the bug

When i joining to the world i cant interact with some blocks, and when i try to place a block he is returningto my inventory and does not apply.

### Steps to reproduce

1. Join the world
2. Interact with blocks.

### Expected behaviour

I want to interact with blocks

**Comment by MichaelHillcox** [comment]
To confirm, this is when you go into your own dimension via the portal?

**Comment by Eoicq** [comment]
to confirm that happens randomly when i try to play again later. Like I played sb3 yesterday and when I join to my world today i can't interact with mods block

**Comment by MichaelHillcox** [comment]
I will note, you've reported that you're playing on version 1.4.3, this version is now quite out of date. Have you tried updating the pack to the latest version?

**Comment by Eoicq** [comment]
i have updated pack to 1.5.0 vers and still have this problem. But in newest version it happens rarely that before
