### ISSUE TITLE
[Bug]: Compacting Drawer with Sand compacts not to 1x Compressed Sand but Sandstone

### ISSUE THREAD

**Issue by bulldog98** [FTBTeam/FTB-Modpack-Issues#263]
### Modpack

FTB Oceanblock

### Modpack version

1.6.0

### Describe the bug

Sand in the Compacting drawer produces Sandstone

### Steps to reproduce

1. Place a compacting drawer
2. Put Sand in it
3. Take Sandstone out

### Expected behaviour

Take Compressed Sand out

**Comment by andr9528** [comment]
Technically not a bug as vanilla takes precedence over modded content, afaik.
You can make a build that craft 1x compressed sand when you have X amount of sandstone. I did that so that i keep a 50% full compact drawer with sandstone, rest of the sand is compacted to 3x compressed sand. My build uses alot of Math with Integrated Dynamic.

**Comment by Cursedradiance** [comment]
i fixed the problem with this entry in the "storagedrawers-common.toml"

```
[General]
	#List of rules in format "domain:item1, domain:item2, n".
	#Causes a compacting drawer convert n of item1 into 1 of item2.
	**compactingRules = ["minecraft:clay, minecraft:clay_ball, 4", "rid:1x_compressed_sand, minecraft:sand, 9"]**
	enableUI = true
	debugTrace = false
	enableItemConversion = true
	enableSidedInput = true
	#The number of item stacks held in a basic unit of storage.
	#1x1 drawers hold 8 units, 1x2 drawers hold 4 units, 2x2 drawers hold 2 units.
	#Half-depth drawers hold half those amounts.
	baseStackStorage = 4
	enableExtraCompactingRules = true
	#Range: 1 ~ 50
	controllerRange = 12
	enableSidedOutput = true

[StorageUpgrades]
	level2Mult = 4
	#Storage upgrades multiply storage capacity by the given amount.
	#When multiple storage upgrades are used together, their multipliers are added before being applied.
	level1Mult = 2
	level3Mult = 8
	level5Mult = 32
	level4Mult = 16

[Integration]
	wailaStackRemainder = true
```

**Comment by andr9528** [comment]
Do note that the above overwrites the current sand to sandstone compacting that compact drawers do.

**Comment by Sunekaer** [comment]
Technically not a bug and not something there will be changed

**Comment by KennethHoff** [comment]
I'm not gonna say you're wrong (You're not; It's technically not a bug that our current mod list doesn't do this), but Storage Drawers  itself [did this exact change a long time ago](https://www.curseforge.com/minecraft/mc-mods/storage-drawers/files/2252383) if you've got Extra Utilities installed (And effectively we do, essentially just with a different name - Mini Utilities)

>If Extra Utilities is present, compressed sand will be preferred over sandstone in compacting drawers.

Based on that change, I'd argue that it *is* a bug that it _doesn't_ compact sand into compressed sand with "Extra utilities" installed.
