### ISSUE TITLE
Raw Iron can't be inserted into Thermal Pulverizer

### ISSUE THREAD

**Issue by yohkev** [FTBTeam/FTB-Modpack-Issues#2631]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.2.1

### Describe the bug

With the update, last night to 1.2.1 Thermal Pulverizer is unable to take Vanilla Iron to pulverize.

### Steps to reproduce

1. Set down a Thermal Pulverizer
2. Attempt to add Iron to be pulverized.

### Expected behaviour

Iron was able to be pulverized before(so it should pulverize now)

### Additional information

Not sure yet, but it seems as though NEI no longer show Iron Dust option, I have also not tested if its all 'dust' creation for Iron.  I was able to smelt the existing dust I had.

**Comment by yohkev** [comment]
As an additional note, it also looks like Mekanism Enrichment chamber also has the same challenge.  It will 'take' the Iron but it will just sit there doing nothing with it.

**Comment by Stefondle** [comment]
All other dust appears to be present.

**Comment by fassina2** [comment]
same I talked about it on discord yesterday, didn't know this place existed. I'll downgrade to 1.11 for now

**Comment by MoonStalk** [comment]
enrichment chamber seems to work fine for raw iron, but definitely can't place raw iron in the pulverizer.  Iron Ore on the other hand, works fine.

**Comment by i-am-the-soup** [comment]
Dunno if it's been figured out yet, but I believe I've found the culprit -  a conversion from TE's nickel dust to IE's nickel grit in kubejs's unification.js server script is missing, causing any recipes outputting TE nickel dust, such as Raw Iron in the Pulverizer, to be removed by the recipe_removals.js script. Adding the proper conversion fixes the recipe.

**Comment by Sirfilior** [comment]
In my opinion the best fix is to change `thermal:iron_dust` in  `pulverizer_raw_iron.json results[]`  to `immersiveengineering:dust_nickel`. As it is already the case for gold for example. And most importantly for iron ore. This will fix the recipe quite well.
