### ISSUE TITLE
Only in revelations Driver Timeout 

### ISSUE THREAD

**Issue by CouchPotato617** [FTBTeam/FTB-Modpack-Issues#2633]
### Modpack

FTB Revelation

### Modpack version

3.6.0

### Describe the bug

Every time I begin to start the modpack either during or at the end of starting it I get a driver time out. In any other game this does not happen.

### Steps to reproduce

1. Open FTB
2. Start Revelations
3. Wait

### Expected behaviour

The game to start

**Comment by MichaelHillcox** [comment]
I'm unsure of what you mean by driver timeout?
