### ISSUE TITLE
kubejs errors

### ISSUE THREAD

**Issue by DiggityMan420** [FTBTeam/FTB-Modpack-Issues#2634]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.2.0

### Describe the bug

Kubejs errors screen shot attached of errors

### Steps to reproduce

login single player
chat says errors
type /kubejs errors

### Expected behaviour

no error???

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/45196448/215916511-71de4613-9450-4d14-96b2-13e32b7f12f8.jpg)

**Comment by TheonlyTazz** [comment]
Check ur modlist

It seems, from the look of your error, that u are missing the summoningaltars mod

Please redownload the pack and check if u are still having issues

**Comment by DiggityMan420** [comment]
i redeownloade the mod but get the same errotr i checked the mod is installed
![Screenshot_2](https://user-images.githubusercontent.com/45196448/216061882-71813917-4e33-4cee-aef9-63ac156defcb.jpg)

**Comment by DiggityMan420** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/45196448/216062313-cb5c5bb5-ca0c-4d67-9776-477e6eafe518.jpg)

**Comment by DiggityMan420** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/45196448/216062480-c3e1f0c9-f741-4790-9a55-e150b36e0572.jpg)

**Comment by TheonlyTazz** [comment]
can u post your KubeJS and Fabric API version?
