### ISSUE TITLE
Immediate crash to desktop upon trying to join a world.

### ISSUE THREAD

**Issue by uGuardian** [FTBTeam/FTB-Modpack-Issues#2637]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.2.1

### Log Files

https://pste.ch/gozuqijisa.pl
https://pste.ch/azibeduxin.md

### Describe the bug

Server was 1.2.0, could connect to it even though I was on 1.2.1, crashed once with the same error in the crash log that it's doing now.
Server updated to 1.2.1, immediate CTD on connect now.
Attempted to clear out the ExtremeSoundMuffler config file, didn't work.

The reported error in the crash log is always EXACTLY `java.lang.NullPointerException: Cannot read field "f_108590_" because "this.f_109059_.f_91074_" is null`

### Steps to reproduce

1. Start game.
2. Attempt to connect to server.
3. Crash

### Expected behaviour

Immediate crash.

**Comment by uGuardian** [comment]
Just as an update, I had the server owner clear my server-side data, that didn't work, then I tried completely reinstalling that pack and that actually did.

If this is considered too much of an edge-case to look into, feel free to close it.

**Comment by Saereth** [comment]
I think I found the cause of this, should be sorted in 1.3 now
