### ISSUE TITLE
Broken text in FTB App description

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#2638]
### Modpack

FTB Inferno

### Modpack version

1.5

### Describe the bug

The bold text for Occultism is not displaying as bold, but as the text indicating it should be bold.

### Steps to reproduce

Open the app 
go to inferno's description
look at text that makes pack look unpolished.

### Expected behaviour

be bold

### Screenshots

![Broken text](https://user-images.githubusercontent.com/77522101/216194480-fab9243f-41a6-450c-808d-1df38884d350.png)

**Comment by MichaelHillcox** [comment]
Fixed a while back, thanks for reporting it
