### ISSUE TITLE
[Bug]: Netherite Autohammer uses Diamond hammer in Recipe

### ISSUE THREAD

**Issue by andr9528** [FTBTeam/FTB-Modpack-Issues#264]
### Modpack

FTB OceanBlock

### Modpack version

1.6.0

### Describe the bug

Simply the title; Netherite Autohammer uses Diamond Hammer in Recipe.

As it is the Netherite Autohammer id expect to need a Netherite Hammer for it.

### Steps to reproduce

1. Go to craft Netherite Autohammer
2. Expect to need a Netherite Hammer for it.
3. Be pleasantly surprised that it only needs a Diamond Hammer.
4. Look at this error report

### Expected behaviour

I'd expect to need a Netherite Hammer to craft it, to match that crafting layout of the previous tiers.

**Comment by andr9528** [comment]
Mikey, this one has not been fixed in version ftb-sluice-forge-1.0.9-build.34 that you gave me on discord while testing if the dupe bug had been fixed.

**Comment by Raidobw2** [comment]
Reminder for Sunekaer: Most likely requires another update on top of the current fixes for FTB Sluice, version 37 is available on CurseForge (instead of version 34, used previously in many fixes for the current Milestone).
