### ISSUE TITLE
Experience OreDict / Obelisk

### ISSUE THREAD

**Issue by moneyblind** [FTBTeam/FTB-Modpack-Issues#2641]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.2.1

### Describe the bug

Unable to pump fluid in and out of the obelisk

### Steps to reproduce

Place obelisk, deposit exp
Place Tank
Put @pipez fluid pipe between blocks.

Moving Exp out of the obelisk results in the tank being filled with "fluid_type.unregistered_sadface" fluid in the tank.

Moving liquid experience (cyclic) to the obelisk does not work.

I believe that the storage type of the obelisk is not ore-dictionary to a exp fluid.

I believe stoneblock had this same issue.

### Expected behaviour

Ore dictionary to Experience liquids

**Comment by TheVekter** [comment]
Able to replicate.

Alternative is to use Cyclic's Experience Pylon. You input experience to it by standing on top of the pylon. Can't remember if you need to crouch or not.

Appropriate fix would be to ore dictionary all experience fluids with one another and have the Obelisk either use its included fluid or one of the ones already in the mod.
