### ISSUE TITLE
Crushing Cobble Conversion

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Modpack-Issues#2644]
### Modpack

FTB Legend of the Eyes

### Is your suggestion related to a problem? Please describe.

Allow for modded types of cobble from consistency to be crushed in create crushing wheels to make Minecraft gravel or add a recipe to convert consistency plus cobble to vanilla cobble.

**Comment by TheonlyTazz** [comment]
All cobbled variants can be cooked into their proper versions, which almost all have their own crushing recipe.

I dont see a need to add additional cobbled variant recipes.
