### ISSUE TITLE
Crash at launching

### ISSUE THREAD

**Issue by PolluxetCastor** [FTBTeam/FTB-Modpack-Issues#2646]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

[crash-2023-02-02_21.47.40-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10573498/crash-2023-02-02_21.47.40-server.txt)
[crash-2023-02-02_21.57.08-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10573501/crash-2023-02-02_21.57.08-server.txt)

### Describe the bug

My game crashes when i launch it. 
Everything seems to run, it says the world is loaded at 100%, when another square appeares with a green face on it (see screenshot).
According to the first crash report, i moved the "EnderStorage" folder in another location.
When I try to restart the game, the same thing happens, and I get the second crash report, talking about the "Transporters" i'm using, but i don't know what i'm supposed to do there.

### Steps to reproduce

1. Start the FTB client and clic on "Play" Stoneblock 3
2. Clic on Single Player
3. Clic on New World

### Expected behaviour

Joining my world

### Screenshots

![wlLuBtOiAD](https://user-images.githubusercontent.com/124310418/216452814-7d9a22eb-d0ac-4c38-a547-22e009fb396a.png)

**Comment by MichaelHillcox** [comment]
You're quite out of data on that version. Does this issue continue to happen on Stoneblock 1.6.1?
