### ISSUE TITLE
Stoneblock 3 Not Joining world

### ISSUE THREAD

**Issue by ShawnGunnels** [FTBTeam/FTB-Modpack-Issues#2647]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10573586/latest.log)

### Describe the bug

Will load terrain and show me one frame in the world before crashing back to the FTB app. tried reinstalling and making multiple new worlds and nothing will work.

### Steps to reproduce

Hit play in the app 
go to single player
either create a new world or try to load a created new world
crash

### Expected behaviour

loading into the world

**Comment by Fury-Caramels** [comment]
I have the same issue.
[hs_err_pid12792.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10580872/hs_err_pid12792.log)

**Comment by trosandich96** [comment]
Having the same issue. I tried different spawn caves and they all crashed.

**Comment by Crasben** [comment]
Same issue here

**Comment by WABUHA** [comment]
same

**Comment by MichaelHillcox** [comment]
Does this continue to happen with Stoneblock 1.6.1?
