### ISSUE TITLE
[Bug]: Crushing Nickel Ingots give Silver Dust

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#265]
### Modpack

Ftb University 

### Modpack version

1.3.0

### Describe the bug

Crushing nickel ingots in Mek factories gives Silver dust

### Steps to reproduce

1.) Put in the ingot into a crusher
2.) check output

### Expected behaviour

Should give nickel dust

### Screenshots

![image](https://user-images.githubusercontent.com/44754456/140622781-d733f457-14a2-4377-958e-6cab5f5f946c.png)

**Comment by andr9528** [comment]
When reporting issues try to check if a newer version is out, which might have fixed it. You are a few versions behind.

Current version (1.6.0) has the following shown in JEI
![image](https://user-images.githubusercontent.com/21788044/140622514-8de080f4-74c5-49b1-a27b-f10c8793535d.png)

**Comment by JunaidA197** [comment]
> When reporting issues try to check if a newer version is out, which might have fixed it. You are a few versions behind.
> 
> Current version (1.6.0) has the following shown in JEI ![image](https://user-images.githubusercontent.com/21788044/140622514-8de080f4-74c5-49b1-a27b-f10c8793535d.png)

Im sorry but you seem to be mistaken, or from the future, University is only on version 1.3.

**Comment by andr9528** [comment]
My mistake - thought i read Oceanblock - i am EXSTREMLY sorry

**Comment by JunaidA197** [comment]
> My mistake - thought i read Oceanblock - i am EXSTREMLY sorry

Haha no problem had a feeling that was the case was just messing with you :p

**Comment by aaronhowser1** [comment]
Fixed, made a mistake when copy/pasting
