### ISSUE TITLE
Crash when going through spawn portal

### ISSUE THREAD

**Issue by Karatemango** [FTBTeam/FTB-Modpack-Issues#2651]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.0

### Log Files
latest.log
https://pste.ch/xosarufohi.md
crashreport
https://pste.ch/xazujocoso.pl

### Describe the bug

Game Crashes when going though the Obsidian Portal in the beginning and Select "Original". Not sure if other Spawncaves also cause the crash.
My friend tried the same and also crashed.

### Steps to reproduce

New world in 1.6.0
Go into Portal
Select anything
Wait
-> Crash!

### Expected behaviour

No Crash!

### Additional information

I have no idea how such a gamebreaking bug can go though to a stable version...

**Comment by BernierVincent** [comment]
Having the same issue on my end. 

[crash-2023-02-03_14.18.53-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10582087/crash-2023-02-03_14.18.53-server.txt)

Linking my crash report in hopes of helping.

**Comment by whiterasbk** [comment]
the same problems
[crash-2023-02-04_04.08.51-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10582450/crash-2023-02-04_04.08.51-server.txt)
