### ISSUE TITLE
Items Moving Around in My Inventory Randomly

### ISSUE THREAD

**Issue by ZekerDEATH** [FTBTeam/FTB-Modpack-Issues#2652]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

Randomly, without any input, the item that I am holding out will move to the first available slot in my hotbar. I've had it move items  from my inventory as well, but haven't clipped that yet.
Example attached. My hands are COMEPLETLY off of my keyboard and mouse when I stand still in the second half.
https://user-images.githubusercontent.com/78389771/216719310-7aba0d7a-cf62-457f-8b99-1386b84be3a1.mp4

### Steps to reproduce

I cannot tell what causes this issue. My friend is having the same issue so it's highly unlikely to be hardware.

### Expected behaviour

Nothing should happen on its own spontaneously in the way it does, I should simply keep the item in my hand without it moving on its own.

### Additional information

On server, TPS is 20.00.

**Comment by MichaelHillcox** [comment]
Looks like desync between the client and server. Are you on a server?

**Comment by trevorgolden** [comment]
Having the same issue. Should not be closed.

**Comment by MichaelHillcox** [comment]
@Sunekaer

**Comment by trevorgolden** [comment]
Issue is still active, believe it is something to do with Inv Tweaks

**Comment by Andy608** [comment]
I'm having this issue too, but I don't have inventory tweaks installed
