### ISSUE TITLE
ReAuth present in Stoneblock 3 Server Files

### ISSUE THREAD

**Issue by Lordfirespeed** [FTBTeam/FTB-Modpack-Issues#2653]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

When using the Windows exe Server files installer, ReAuth is downloaded to the server mods folder.

### Steps to reproduce

- Download the [Windows server installer](https://api.modpacks.ch/public/modpack/100/2328/server/windows)
- Run it 
- Check the `mods` folder of the resulting installation for `ReAuth`

### Expected behaviour

ReAuth should be excluded from the dedicated server modlist

**Comment by MichaelHillcox** [comment]
These kinda things aren't huge issues, but it's worth noting. Thanks for the report. I've flagged this mod as client only. This should be resolved in the next few hours.
