### ISSUE TITLE
Direwolf20 1.19 world not opening up

### ISSUE THREAD

**Issue by plumbologist** [FTBTeam/FTB-Modpack-Issues#2654]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.2.1

### Log Files

[crash-2023-02-03_21.12.19-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10607749/crash-2023-02-03_21.12.19-server.txt)

### Describe the bug

I can open up the Direwolf20 modpack fine but when I go to select a world that I have created before it does not load, it gets past "reading world data..." but then the window freezes and no amount of waiting will cause it to go onto the next step (usually there is a square in the middle of the screen that will load to 100% before the world opens and this doesn't appear while this isn't working) 

### Steps to reproduce

1. Open up Direwolf 20 1.19 modpack
2. Try and open up a singleplayer world
3. It doesn't load so try and restart. 

### Expected behaviour

The world should open when you click on it

### Additional information

This has only started happening the past two days, I tried to update it to the newest version but still had the issue. I don't have any other mods installed besides what's in the modpack.

**Comment by MichaelHillcox** [comment]
Please delete `toomanyglyphs/glyph_filter_block.toml` this file.

If this works for you. Please close the issue :+1:

**Comment by plumbologist** [comment]
I deleted that file but the issue still persists.

**Comment by MichaelHillcox** [comment]
Can you upload the latest log?

**Comment by plumbologist** [comment]
Here is the latest log: 
[crash-2023-02-04_15.31.14-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10609878/crash-2023-02-04_15.31.14-server.txt)
I can open up other minecraft modpacks (enigmatica 6 expert) so I don't quite know whats up

**Comment by MichaelHillcox** [comment]
Now it's this file, `ars_nouveau/glyph_rotate.toml`, can you delete that one too. If it doesn't work, attach the changelog again.

**Comment by plumbologist** [comment]
I am still having the issue, here is the crash report: [crash-2023-02-05_09.27.41-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10611690/crash-2023-02-05_09.27.41-server.txt)

**Comment by Saereth** [comment]
this are ars autogen configs, we dont even distribute them so its something odd for sure.. I'd suggest a clean reinstall to start
