### ISSUE TITLE
Server can't keep up without a reason

### ISSUE THREAD

**Issue by Henkiwan** [FTBTeam/FTB-Modpack-Issues#2655]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0/1.6.0

### Describe the bug

Me and my friend were on our SB3 server, which runs on a separate machine with 8GB RAM, without having any issues. We left and now suddenly when trying to get back in it just says "Connection Timed Out".

All the server log says is "Server can't keep up. Running XXXXms behind (XXX ticks). Is the server overloaded?". After trying to get in the server a few times it crashes. The crash report only says "1 tick running 60000ms behind."

We already restored a backup and were able to get in, didn't change anything on the world and left just to try if it was solved. It times out again.

### Steps to reproduce

1. Click to join the server.
2. Timeout before getting in..

### Expected behaviour

Get in the server? Get in the server would be nice :)

**Comment by MichaelHillcox** [comment]
Sounds like you have too many entities in the world. If you have the spark mod installed, run /spark profiler start then after a minute or so, run /spark profiler stop and provide the link it gives you here so we can better debug why your server is running so behind
