### ISSUE TITLE
dont load resourcepack and shaders

### ISSUE THREAD

**Issue by NezoreXn** [FTBTeam/FTB-Modpack-Issues#2656]
### Modpack

FTB Academy 1.16

### Modpack version

1.16

### Describe the bug

when i add an resourcepack, this doesnt load and still having the default resources.
and for the shaderpacks the folder shaderpack dont exist and if i create them dont appear the option in the settings menu

### Steps to reproduce

open seetings
open resourcepacks option
add the resourpack
loading
dont load

### Expected behaviour

optifine trouble

### Screenshots

![image](https://user-images.githubusercontent.com/96381119/216780842-48c1da7b-780e-41d4-9755-423782fb21ed.png)
![image](https://user-images.githubusercontent.com/96381119/216780849-cb8b262b-9c2f-40d5-8b2d-75a57e091185.png)

**Comment by MichaelHillcox** [comment]
We don't support using optifine on our modpacks. I'm also not sure what you're trying to say here. Resource packs aren't shaders...
