### ISSUE TITLE
DireWolf20 1.19 Mod Suggestion: Tetra

### ISSUE THREAD

**Issue by ToxinZangoose** [FTBTeam/FTB-Modpack-Issues#2659]
### Modpack

FTB Presents Direwolf20 1.19

### Is your suggestion related to a problem? Please describe.

Hello,

Big fan of the DW20 FTB series, I would like to suggest that Tetra and its dependency, mUtil could be added to the modpack.

It is listed as in alpha stage, but it runs flawlessly from my own experience.

### Mod suggestion

https://beta.curseforge.com/minecraft/mc-mods/tetra

This was in previous the 1.16 version of DireWolf20 and has since been updated and revised to add the ruins back and many bug fixes.

It also adds a helpful way to find ancient debris and the ruins by using the holosphere and an eye of ender.

**Comment by Saereth** [comment]
The problem with tetra is it requires considerable worldgen that would now be missing from existing worlds. I'd have loved to gotten tetra in if it were ready before pack release, but it's a bit awkward to use now. I probably would have gone with it over silent gear. Tetra is however already planned to be in some of our upcoming packs, and you should be able to add it to your own instance without issue.
