### ISSUE TITLE
[Bug]: Can;t make creative chemical tank

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#266]
### Modpack

Ftb University 

### Modpack version

1.3.0

### Describe the bug

The item won't craft.

JEI Recipe shows centre bottom as empty chem tank, Kube files show it as clean uranium slurry, which I assume it to be, but ive tried both and neither works

### Steps to reproduce

Try and craft it.

### Expected behaviour

Give a creative chemical tank

### Screenshots

![image](https://user-images.githubusercontent.com/44754456/140627126-7f166d7e-4492-4299-991c-6cabe78bb3c1.png)

**Comment by zoller27osu** [comment]
Found the problem lol
In the kubejs, the bottom tank is listed as:
`      K:Item.of('mekanism:ultimate_chemical_tank', {mekData:{GasTanks:[{Tank:0,stored:{slurryName:"mekanism:clean_uranium",amount:512000}}]}}),`
but the "GasTanks" should actually be "SlurryTanks".

The recipe may need to be refactored now that the tanks hold so much more maximum (unless all gases were just 16x'd?)
