### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by nickperry23** [FTBTeam/FTB-Modpack-Issues#2660]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.2.1

### Log Files

[crash-2023-02-04_16.45.06-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10609582/crash-2023-02-04_16.45.06-client.txt)

### Describe the bug

crashes every time i try to load it up

### Steps to reproduce

not sure 

### Expected behaviour

to be able to play

**Comment by Saereth** [comment]
disable Ribidium if you want to use optifine, you cant use both
