### ISSUE TITLE
Infinite Dropped Item Glitch with Create

### ISSUE THREAD

**Issue by Mikeatron-User** [FTBTeam/FTB-Modpack-Issues#2662]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

In essence, Items that are dropped from crusher wheels will not deposit onto belts in loaded chunks when there is no player nearby. This leads to items indefinitely dropping; causing immense server lag over time.

### Steps to reproduce

1. Place two Create crusher wheels.
2. Power them
3. Place a moving Create belt under the crusher wheel. There needs to be 1 block of space between the of the center of crusher wheels and the belt.
4. Feed the crusher wheels with something that produces infinite items like a cobble generator.
5. Load chunk using FTB chunks or have the system be in spawn chunks.
6. Set game rule `spectatorsGenerateChunks` to `false` and go into spectator mode. (This allows the player to observe the glitch without actually disconnecting or having to relocate by simulating an absent player.)
7. Items should drop onto belt, but not be deposited into the belt.

### Expected behaviour

Items should deposit onto the belt regardless if a player is present.

### Screenshots

![image](https://user-images.githubusercontent.com/70152741/216792972-655f3b2b-8f71-4c58-b58a-9b1503105642.png)

**Comment by MichaelHillcox** [comment]
Could you run spark on your server whilst this is happening so we can ensure this is causing server lag and not just a visual issue.
