### ISSUE TITLE
Auto-Hammer does not output the correct ammount of items for 3x compressed item

### ISSUE THREAD

**Issue by zaadDev** [FTBTeam/FTB-Modpack-Issues#2665]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5

### Describe the bug

The **Auto-Hammer** from _FTB StoneBlock Companion_ mod **doesn't** output the correct ammount of items when processing _3x compressed item_.
It _only_ outputs a total of **512** instead of **729**.

### Steps to reproduce

1. Put the autohammer between to chest
2. Insert one 3x compressed item in the input chest
3. wait until the auto-hammer process the item
4. in the output chest there are only 8 Stacks of items

### Expected behaviour

A total of 729 items as shown in the REI

### Screenshots

https://user-images.githubusercontent.com/96781967/216828221-0921ebcb-c478-46a7-974d-29f0dd3e1336.mp4

**Comment by MichaelHillcox** [comment]
Hmm, interesting... Does this happen on the latest version of the modpack?

**Comment by hiddenvaad** [comment]
Sorry for the late response, I thought this repo wasn't active. \
Anyway, I just checked and it still happens with the latest version

**Comment by TheDebbyCase** [comment]
Experiencing this bug now also

**Comment by hiddenvaad** [comment]
Hello,
I can confirm this is still not fixed in version 1.7.1
