### ISSUE TITLE
OreDict / Copper Nuggets - Cyclic

### ISSUE THREAD

**Issue by Holy-Bananas** [FTBTeam/FTB-Modpack-Issues#2667]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.2.1

### Describe the bug

Cyclic Crushing Macerator will produce Cyclic Copper Nuggets when processing Copper Ore, but they cannot be used in crafting.

### Steps to reproduce

1. Get Crushing Macerator set up.
2. Process Copper Ore blocks.
3. Enjoy copper nuggets that can't be used in crafting table.

### Expected behaviour

Produce copper nuggets that don't work as copper nuggets.

**Comment by Saereth** [comment]
weird, I did a datapack override for this in 1.2.1, shouldn't be happening. I guess it must be hard coded somewhere, I'll bring it up with the mod dev

**Comment by Silent-Hunter** [comment]
This seems to be happening again in 1.13.1, my roommate can't use Cyclic's copper nuggets in any recipe. Should I make a new bug report for this?
