### ISSUE TITLE
Certus Quartz Dust Recipe added to the Pulverizer from INDEV 

### ISSUE THREAD

**Issue by daodragon** [FTBTeam/FTB-Modpack-Issues#2668]
### Modpack

FTB Legend of the Eyes

### Is your suggestion related to a problem? Please describe.

Hi Tazz.
Right now the only way to make Certus dust is to either mine the not fully grown crystal buds or to use a relatively slow millstone/crushing stone method. Adding the dust recipe to the pulverizer from INDEV makes it more useful machine to have and much faster to make the dust.

Cheers,
Rammer DarkSun

**Comment by TheonlyTazz** [comment]
![image](https://i.imgur.com/xgmiFnU.gif)

Added in the latest version of LotE! Thanks alot
