### ISSUE TITLE
Direwolf20 1.19 Game Crash in YUNG's Better Desert Temples

### ISSUE THREAD

**Issue by JordanBlake** [FTBTeam/FTB-Modpack-Issues#2669]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.2.1

### Log Files

Log Error: "FramedBlocks BlockEntity Warning: Not Applicable"

[crash-2023-02-05_15.19.14-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10613976/crash-2023-02-05_15.19.14-server.txt)
[crash-2023-02-05_15.24.38-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10613977/crash-2023-02-05_15.24.38-server.txt)
[crash-2023-02-05_15.32.41-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10613978/crash-2023-02-05_15.32.41-server.txt)

### Describe the bug

I came across an (obviously mod-added) desert temple with some puzzles. I completed the first puzzle (turn all lights off) and my game immediately crashed. I loaded back in fine, but when I completed the second puzzle (item frames), the game crashed again. I loaded in again, and when I completed the third puzzle (target + scrolling lights), the game crashed again. After those three puzzle-related crashes, I was able to traverse the rest of the temple without any issues.

This doesn't appear to have affected my world in any way, and does not break the temple, however; it's obviously annoying to have to load back in every time I complete a puzzle.

### Steps to reproduce

1. Enter YUNG's Better Desert Temple
2. Complete Puzzle 1
3. Crash
4. Complete Puzzle 2
5. Crash
6. Complete Puzzle 3
7. Crash
8. Go on with life

### Expected behaviour

No crash after puzzle completion.

**Comment by JordanBlake** [comment]
Sorry, I thought I selected Direwolf20 1.19, but I must have misclicked. It's pack version 1.2.1.

**Comment by Saereth** [comment]
Yeah its a bug with Hexerei I literally submitted a PR to fix it over a month ago and not a word from the dev. We could remove yungs better desert dungeons but it isnt really that mod's fault the fault is with Hexerei's mixin on the campfires which spawn as part of worldgen in his temples. We will likely have to remove yungs better desert temples until it can get resolved for now

**Comment by FagSoft** [comment]
While this issue has been marked as closed, I would possibly recommend looking into removing Hexerei instead. I've seen a couple of reports of it crashing with mods like Twilight Forest as well, and it has some other issues that's quit annoying; Don't leave your broom too far away from yourself in an SMP server, for instance. It'll become invisible.
