### ISSUE TITLE
[Bug]: Mobs Spawning In Overworld Starting Area

### ISSUE THREAD

**Issue by SKGuru00** [FTBTeam/FTB-Modpack-Issues#267]
### Modpack

FTB OceanBlock

### Modpack version

1.6.0

### Describe the bug

It appears hostile mobs are spawning in my save when gamerule doInsomnia is set to "false," although not sure if this is a bug or working as intended.  Steps to reproduce have been outlined below.

### Steps to reproduce

1.) Create new world in "The island" map.
2.) In the Game Rules section, set Spawn phantoms to off.
3.) After starting the game, set time to midnight and wander around.
4.) Hostile mobs should now be spawning in the starting area.

### Expected behaviour

My assumption is that hostile mobs should not be spawning unless in the Deep Warm Ocean part of the Overworld.

**Comment by Sunekaer** [comment]
Hi, doInsomnia=false only stop Phantoms from spawning, if you want to stop all hostile mob spawn you should play in peaceful 
Not sure if that answers your question?

**Comment by SKGuru00** [comment]
Hello, when I set doInsomnia=false, it appears **all** hostile mobs are able to spawn in the starting area.

**Comment by Raidobw2** [comment]
Do you still see phantoms?

**Comment by SKGuru00** [comment]
My mistake, the game rule doInsomnia command was a red herring.  I wasn't paying attention and just noticed my starting are **is indeed** in the Deep Warm Ocean, so that makes sense why hostile mobs are spawning at my island.  Thanks for your time, cheers.
