### ISSUE TITLE
[Feature Request]: Compact Machines/Crafting

### ISSUE THREAD

**Issue by UpstartMyst** [FTBTeam/FTB-Modpack-Issues#2670]
### Mod

Stoneblock 3

### Description

I am currently near the endgame of stoneblock 3, creating singularities, and reached the wall singularity where it wants me to have-(I think)-compact crafting set up. I have zero experience with with this set of mods, but that isn't the problem, I can learn them. But there is no section within the quest book to teach them to you so I'll have to go elsewhere for it, again, not a big deal, but could be better which I'm sure is a thing that everyone likes seeing.

### Describe the solution you'd like

I think it would be good to add at least a small section to the quest book introducing and explaining at least the basics of how to interact with the mods, so that you don't have leave the game to learn it if you don't already know any of it.

### Describe alternatives you've considered

Maybe if that isn't feasible add a link or something to somewhere explaining the basics? It would take you out of the game, but it's still something that could help.

**Comment by DinnerBeef** [comment]
For learning how to use mods, we suggest you play one of these packs, [FTB Academy](https://www.feed-the-beast.com/modpacks/88-ftb-academy-116) and or [FTB University](https://www.feed-the-beast.com/modpacks/90-ftb-university-116). This pack is not designed to teach you how every mod works.
