### ISSUE TITLE
Stoneblock 3 | Compct Machines & Mekanism | no power transfer

### ISSUE THREAD

**Issue by lordsofking** [FTBTeam/FTB-Modpack-Issues#2671]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

If i have my power generation in a compact machine(forceloadet the compact machine) i can not transfer the power with a Mekanism cabel to the overworld with the use of a tunnel. With energy pipe from Pipez it works but i want higher capacity. is this a Bug?

### Steps to reproduce

1. Get a compact Machine Block and place it in the world
2. go in the Block dimension an buid a power generation
3. set up a tunnel to the overworld
4. in the overworld use the selectet tunnel site do attach a cable or other block that can store or transfer power

### Expected behaviour

transfer power

**Comment by UnRealDinnerbone** [comment]
This has been an issue for over a year on Compact Machines, closing this issue https://github.com/CompactMods/CompactMachines/issues/568
