### ISSUE TITLE
Ars Nouveau in Stoneblock 3 No Sound.

### ISSUE THREAD

**Issue by Furious1964** [FTBTeam/FTB-Modpack-Issues#2674]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

Placed and used the Enchanting Apparatus and there's no sound when item is crafted.

### Steps to reproduce

1. Make Apparatus
2. Craft Item
3. Apparatus makes no sound when crafting.

### Expected behaviour

Expected to hear a sound.

**Comment by MichaelHillcox** [comment]
Please attach game logs

**Comment by Furious1964** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11132294/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11132296/debug.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11132299/console.log)

**Comment by Furious1964** [comment]
Also, there's no sound from the Arcane Portal and I've already tried a fresh install of the pack....still no sound.

**Comment by Furious1964** [comment]
Any luck trying to track this down? For some strange reason, one portal started to give the teleport sound....put only when enter the room I built. I don't know what is causing this to happen.

**Comment by DinnerBeef** [comment]
Looks like most sounds were added after this version of minecraft. So this version of the mod, won't have many sounds.
