### ISSUE TITLE
Only 1 chunk is not loading in Stoneblock 3 (I tried reloading the chunk & relogging & redownloading)

### ISSUE THREAD

**Issue by Oh-Im** [FTBTeam/FTB-Modpack-Issues#2676]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

Since the newest update (1.6.1) one of my chunks just refused to load. I can still fly through it, but I can't walk through it. I can also not see any of my machines including immersive engineering and others. I still run into the blocks as if they were there but I can see them or access them.

### Steps to reproduce

This just randomly happened after the 1.6.1 update. I don't know how to replicate it.

### Expected behaviour

After getting the new update I thought is would just fix some other bugs.

### Screenshots

![Screenshot (58)](https://user-images.githubusercontent.com/111196270/217159734-0ff800cd-1055-489b-bcb6-9ea611610c62.png)

### Additional information

This is the only modpack I have had this problem with. Could it be something on my end or is it just a bug? I also tried reloading the chunk, closing the application and reopening it, and redownloading the mod.

Thank you!

**Comment by MichaelHillcox** [comment]
Can you attach your logs please
