### ISSUE TITLE
Player becomes ticking entity and crashes server as weird interaction of lunchbox and helmet auto-eat module

### ISSUE THREAD

**Issue by orbidlo** [FTBTeam/FTB-Modpack-Issues#2677]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.2.0

### Log Files

[crash-2023-02-07_09.04.30-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10672874/crash-2023-02-07_09.04.30-server.txt)
[crash-2023-02-07_09.05.51-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10672875/crash-2023-02-07_09.05.51-server.txt)

### Describe the bug

I crafted the modular helmet and upgraded it with auto-eat module but soon after I needed to log off. Next time I log in, it instantly crashes the server as I'm ticking entity, two times in succession (logs included) and because it involves the lunch box I can only assume it is weird interaction between it and the helmet module.

### Steps to reproduce

1. Craft and equip modular helmet with auto eat module turned on
2. Equip lunchbox in hotbar and have some food in it 
3. Log off
4. Try to log back in 
5. Enjoy becoming ticking entity

### Expected behaviour

Auto eat module correctly eats out of lunchbox or at least ignores it and it doesnt crash anything

**Comment by TheonlyTazz** [comment]
This is caused bcause the auto eat module thinks the lunchbox is actually something to eat, which causes a weird interaction.
only fix i can think of isto disable the recipe of the auto eat module, as i have no high hopes the Indrev developer is still active
