### ISSUE TITLE
Minecraft Crash while breaking/placing blocks [FTB University 1.16]

### ISSUE THREAD

**Issue by JulikGame** [FTBTeam/FTB-Modpack-Issues#2678]
### Modpack

FTB University 1.16

### Modpack version

1.8.0

### Log Files

https://bytebin.lucko.me/DSirx7ydWL

### Describe the bug

when i'm breaking/placing blocks in higher Y cords or it just biome mountains and i'm getting crash

### Steps to reproduce

1. go on any mountain or biome which has so much mountain
2. place/break any block
3. it will crash not fully

### Expected behaviour

i don't know, it's probably rubidium issues or it's probably my server problem

**Comment by aaronhowser1** [comment]
Try downgrading to the previous version and seeing if that works

**Comment by JulikGame** [comment]
tried to remove rubidium and didn't crashed
trying magnesium..... def doesn't crash but i've got bug texture in ae2 ME Drive

**Comment by MichaelHillcox** [comment]
Please post your crashlog again as it's no longer under the URL posted
