### ISSUE TITLE
Problem with launching StoneBlock 3

### ISSUE THREAD

**Issue by Majevek** [FTBTeam/FTB-Modpack-Issues#2679]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

Failed to prepare instance 'FTB StoneBlock 3(693dibdg-1815-4434-9a5b-cdafbscoezbe). because. java.joIOException: Failed to execute asset update task.

![obraz](https://user-images.githubusercontent.com/124740046/217378652-6cdadb2b-5a3b-430e-9dfb-658ff60d5c3f.png)

![obraz](https://user-images.githubusercontent.com/124740046/217378757-7fccf23c-006f-4a33-abd1-fe340f53f6fd.png)

### Steps to reproduce

1. Open launcher
2. Click FTB StoneBlock 3
3. click play

### Expected behaviour

I want the launcher to properly open the modpack

### Additional information

I tried to reinstall modoapck but it did not help, I do not know what's going on

**Comment by MichaelHillcox** [comment]
This issue should have been fixed. Can you confirm if it is still happing?

**Comment by Majevek** [comment]
Everything works fine now, thanks Wiadomość napisana przez Michael Hillcox ***@***.***> w dniu 02.04.2023, o godz. 13:56:﻿
This issue should have been fixed. Can you confirm if it is still happing?
