### ISSUE TITLE
Unable to launch Stoneblock 3

### ISSUE THREAD

**Issue by Spacemoney21** [FTBTeam/FTB-Modpack-Issues#2681]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

Unable lo launch the game at al because of said issue I've tried using earlier versions along with uninstalling yet nothing has worked

### Steps to reproduce

Go to StoneBlock 3 instance.
launch game.
Crashes.

### Expected behaviour

Game to Launch 

### Screenshots

![Screenshot 2023-02-07 200042](https://user-images.githubusercontent.com/124747609/217402088-a9a3ab25-9f22-4fa4-b3ef-e73b0749b9df.png)

**Comment by RebelRK99** [comment]
I'm also having this issue

**Comment by MichaelHillcox** [comment]
Duplicate of #2679 please comment there if this is still an issue for you.
