### ISSUE TITLE
Infinite duplication bug with extreme crafting

### ISSUE THREAD

**Issue by MegaIng** [FTBTeam/FTB-Modpack-Issues#2682]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

When having a valid recipe in the extreme crafting table and taking the result out with the scroll wheel, it sometimes duplicates the stack sizes of all input stacks, even far beyond normal caps (up to and including signed 32bit overflow, resulting in stacks vanishing). This is corrected quickly, however if another crafting action is completed very quickly and/or the interface is closed (I didn't find a 100% reliable method), this is permanent and the stacks can even be extracted. This allows for duplication of all items that are used in any crafting recipe. I did this a few times accidentally before figuring out what was happening.

I have not tested out if this bug exists with just Avaritia.

### Steps to reproduce

1. Have a valid reciepe in a Extreme Crafting Recipe (does not have to be a 9x9 one)
2. Use the scroll down action to get the result item into your inventory.
3. the Item count of all items will doubled (or more correctly, 2n-1 where n is the count beforehand)
4. very quickly, before the item count corrects, close the inventory
5. Wait a bit (a second) and then reopen the crafting table
6. The stacks will now stay at the increased value, even far beyond 64 items

### Expected behaviour

No infinite duplication glitch. Either the count doesn't actually jump up, or it at least reliabley get's down again.

### Screenshots

![image](https://user-images.githubusercontent.com/26136419/217419870-ddbcc0f5-c2ca-4a28-862a-1c1f685838ed.png)

![image](https://user-images.githubusercontent.com/26136419/217420043-07283988-fdd9-4fb0-8188-d68c33c29184.png)

**Comment by Sunekaer** [comment]
#1903
