### ISSUE TITLE
Stoneblock 3 Transmutations Table Cant Open

### ISSUE THREAD

**Issue by Grampixi** [FTBTeam/FTB-Modpack-Issues#2684]
### Modpack

FTB StoneBlock 3

### Modpack version

1.18.2

### Log Files

https://pste.me/@/b9KP_QDFAkI

### Describe the bug

This comes when my friend trys to Open his Table

### Steps to reproduce

He just right clicks but it worked at the begin of the server

### Expected behaviour

Find the error

**Comment by MichaelHillcox** [comment]
Please post a full crashlog and a copy of your debug.log
