### ISSUE TITLE
Mekanism and thermal iron dusts are not ore dictionaried

### ISSUE THREAD

**Issue by StromanLiam** [FTBTeam/FTB-Modpack-Issues#2688]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.1

### Describe the bug

You cannot craft Thermal Series Invar blend with Iron Dust from Thermal Series, it requires that it be Mekanism Iron Dust. 

Weird that a thermal recipe requires mekanism items...

The two dusts are not ore dictionaried. 

I also notice that Iron Dust from thermal doesn't appear in JEI, but I get the item from using the thermal series pulverizer to process iron.   

So there are two iron dusts that are not equivalent. 

Perhaps this was an oversight? 

### Steps to reproduce

1. place a vanilla iron ingot or raw iron in a thermal series pulverizer 
2. it will produce thermal series iron dust
3. try to use that dust to craft thermal series invar blend

### Expected behaviour

the two dusts should be ore dictionaried, or the recipe should at least allow dust from thermal since its a thermal recipe.

**Comment by Saereth** [comment]
Thermal dust shouldnt be oredicted any longer and shouldnt be created any more. Mekanism dust should be produced everywhere now as of v1.4.0 when it comes out
