### ISSUE TITLE
Add obsidian dust to the Occultism Crusher

### ISSUE THREAD

**Issue by lucasturetta** [FTBTeam/FTB-Modpack-Issues#2690]
### Modpack

FTB Presents Direwolf20 1.19

### Is your suggestion related to a problem? Please describe.

I think an obsidian dust recipe should be avaliable as an oppition to the occultism crusher ritual. As it stands right now, Occultism is gated by other mods. As i'm tying to progress using only occultism i got stuck trying to get the purple chalk.
Do you think this is possible? Am I missing something?

**Comment by Saereth** [comment]
the crusher foliot can crush obsidian to dust and it doesnt require purple chalk to summon it, this process is outlined in the occultism book
