### ISSUE TITLE
Minecolonies colonists stop functioning at a certain range, but only when multiple players are online

### ISSUE THREAD

**Issue by dkowis** [FTBTeam/FTB-Modpack-Issues#2691]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.3.2

### Log Files

I haven't been able to find anything in the logs indicating anything. I don't see any errors, or info messages that pertain to it.

### Describe the bug

For some reason, when more than one person is on line (granted there's only two of us, but it only happens when we are both connected,) the colonists will stop working just out of some range of a player. Instead of continuously moving around the map doing their thing, they'll get to a range from a player and then stop. Days could pass in minecraft, and they'll get upset about not having slept for the last few days. If either one of us disconnects, they will suddenly start up again, as if they've been untethered. 

We haven't been able to figure out any configuration things.

### Steps to reproduce

1. Create a server on this modpack Direwolf20 1.19
2. Create a colony
3. Have multiple players
4. grow the colony so that it takes up a decent amount of space
5. observe that when both players are online, eventually there will be a "ring" of white dots on the map where the colonists exit the odd functional range around a player.
6. If one or the other player logs off, all the colonists start moving again.

### Expected behaviour

The colonists should always go about their jobs.

### Screenshots

I'll try to capture a screenshot of the villagers getting stuck and update this.

### Additional information

I'm in the server with @MaffooClock, tagging him so we can get information on the issue together.

**Comment by brandobas** [comment]
I have experienced the same issue with multiple players (2), here is some additional detail.

 - increasing the view distance allows you to see the colonists stop moving at approximately 32 blocks distance.  Every step you move towards a stopped colonist will see them move away and stop again in 1 block.
 - the colonist also stops moving if the vertical distance is 32 blocks, i.e. a colonist going down a mineshaft ladder will stop descending, even if you are in the same chunk.
 - barbarian raids are also affected.  The barbarians will not approach your colony when they have spawned unless you go out to meet them.
- operating 2 separate colonies has the same issue. ( so this is not an ownership problem )

As @dkowis notes, logging players out until only 1 remains, resolves all of these issues and all colonists and barbarians will start to move again.

**Comment by MaffooClock** [comment]
Just in case anyone asks, we have the following in the server config:
```
[gameplay]
    forceloadcolony = true
    colonyloadstrictness = 1
```
...although this should not be a factor given that the problem being reported only occurs when more than one person is connected.

FWIW, the behavior @dkowis describes as "the colonists will stop working just out of some range of a player" is very similar to what the "simulation distance" and "render distance" settings control in video settings.

**Comment by kkrabfir** [comment]
We are also experiencing this in 1.1.0. Colonists are fine when only one player is online. Colonists stop moving beyond a certain range from the player as soon as a second player logs on.

**Comment by adam-miller** [comment]
I would try editing the ItShallNotTick config to add an exclusion for minecolonies.

Via the Minecolonies Discord:

Your colony only runs when it is chunk-loaded. There are several reasons why parts of your colony may not be loaded, though.

1. If you are far away from your colony, it unloads. This can be solved by certain chunk loaders, but that is not recommended.
2. If your colony is bigger than your render distance, some parts of your colony may not be chunk-loaded. You can change the config to force the colony to load. The option for that is forceloadcolony.
3. If you are in your colony, and colonists that are loaded (within the render distance) are not doing anything, then there is a mod interfering. A few mods that can cause this are:
  - Optifine ("smooth world" should be turned off)
  - "It will not tick" (add "minecolonies:*" to the ignore list in the config)

**Comment by dkowis** [comment]
I think that's the secret!

looking at the configuration for `itwillnottick` I see that it's not enabled until at least 2 players show up.

I have modified it to include in the ignore list `minecolonies:*`

Will test and report back.

**Comment by dkowis** [comment]
Adding a `minecolonies:*` to the it will not tick configuration solved the problem! It'd be awesome if that were added to the modpack in general!

**Comment by Requios** [comment]
Fyi: in Better MC modpack, the 'Does Potato Tick' mod does the same. If citizens are more than 64 blocks away from you, they stop. You can add 'minecolonies' to the whitelisted mods. 

Note for dedicated server: changing the config using the ingame menu only changes your local config. Make sure to change the config on the server as well.

**Comment by Jessifero** [comment]
You, my friend, are my hero. I've been trying to fix this for weeks and that just changed everything.

**Comment by hydrocrry** [comment]
dont forget about noseenotick it does it aswell
