### ISSUE TITLE
Miner destroying itself - 

### ISSUE THREAD

**Issue by McMiller81** [FTBTeam/FTB-Modpack-Issues#2692]
### Modpack version

Direwolf 20 1.19.2 (Version 1.3.2)

### Describe the bug

When placing a "Cyclic" miner.
Limiting the mining area to 0/0
Giving it powers and a basic iron pick axe
activating with redstone signal or always active
If there is no block to mine "nothing"
When trying to mine the area it destroys itself 

### Steps to reproduce

place miner
Give power 
Give signal or setting mine
watch the miner self implode

### Expected behaviour

mining the block \ breaking the machine but can pickup the machine

**Comment by Saereth** [comment]
can you show a preview of the mining area, also are you mining in a claimed chunk? Are fake players set to allied for you?

**Comment by McMiller81** [comment]
Hello,

I am mining in a Claimed Chunk.
Personal game no other players.

It dose not seem to matter if I am trying to mine a stone block or empty air.
I am running the server on default settings.
I can get any wanted extra information needed if you can provide a list tonight when I have access to the PC.
I can also record a video of testing the feature.
If you can provide a list of what to show/test.


Mika Vakkilainen
System Administrator
Advania Finland
Direct +358 9 8861 1526
Mobile +358 50 4657661
***@***.***

***@***.***%0b%0b>Itsehallintokuja 6, 02600 Espoo, Finland
www.advania.fi<http://www.advania.fi/>

**Comment by McMiller81** [comment]
Hello,

Here are screenshots of settings and link to test.

https://youtu.be/s4B5rsuWy5E
![2023-02-26 10_56_33-Direwolf20 1 19](https://user-images.githubusercontent.com/100205606/221401452-bad11e48-d87c-44ce-bc3f-fa18271ca603.png)
![2023-02-26 10_47_56-FTB App](https://user-images.githubusercontent.com/100205606/221401454-f518522f-3e85-4066-93d8-4a54c03e3ec8.png)
![2023-02-26 10_51_54-Direwolf20 1 19](https://user-images.githubusercontent.com/100205606/221401456-8d9bea9e-56f8-49aa-90ef-c2260c1a327c.png)
![2023-02-26 10_55_29-ElevenClock](https://user-images.githubusercontent.com/100205606/221401457-5fd022bf-5dd1-4bcc-a2a6-631ec615a310.png)
![2023-02-26 10_56_13-Direwolf20 1 19](https://user-images.githubusercontent.com/100205606/221401458-901ee160-e9d4-4976-b3cc-4731ab3e8e02.png)
![2023-02-26 10_56_20-Direwolf20 1 19](https://user-images.githubusercontent.com/100205606/221401459-c1cab5fb-2c12-456b-9860-6baeb13916f4.png)

**Comment by Arithia** [comment]
I am on a server running the latest beta build 1.4.0 and am also having the same problem.
Here is a video

https://user-images.githubusercontent.com/126522275/221695865-40330ce7-2554-4954-a466-42b1f6cacd68.MOV

**Comment by McMiller81** [comment]
Same result.
And it seems it is not the END pickaxe as I have tried with a vanilla iron pick axe as well.

Good to know it has been replicated and is not just my setup

Mika Vakkilainen
System Administrator
Advania Finland
Direct +358 9 8861 1526
Mobile +358 50 4657661
***@***.***

***@***.***%0b%0b>Itsehallintokuja 6, 02600 Espoo, Finland
www.advania.fi<http://www.advania.fi/>

**Comment by Arithia** [comment]
I just re read the earlier question in the email above about fake players and that was the problem. I went into team settings and made fake players true and it no longer breaks the blocks.

**Comment by McMiller81** [comment]
No help for me unfortunately.
Still breaking as soon as I put any pickaxe in and the tick starts the mining

Mika Vakkilainen
System Administrator
Advania Finland
Direct +358 9 8861 1526
Mobile +358 50 4657661
***@***.***

***@***.***%0b%0b>Itsehallintokuja 6, 02600 Espoo, Finland
www.advania.fi<http://www.advania.fi/>
