### ISSUE TITLE
Cardboard box Unuseable

### ISSUE THREAD

**Issue by Xenorhaste** [FTBTeam/FTB-Modpack-Issues#2696]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.0

### Log Files

https://pastebin.com/0t22ppR1

### Describe the bug

If i try to use the Cardboard Box from Mekanism the game instantly crashes, no matter if the world is new

### Steps to reproduce

1. Get the Cardboard Box
2. Right click a Block

### Expected behaviour

Cardboard Box is used for boxing up other blocks to move them, preserving the inventory while being moved. By right clicking it on any block, tank, chest or machine, you wrap it in this protective box that you can break while still preserving everything about that block, tank, chest or machine. This includes its inventory, orientation, installed upgrades, and more, and should work with any block from any mod. You can later place it safely into the world. Sneak right-click to unwrap a box, causing the Cardboard Box to drop as an item.

**Comment by Xenorhaste** [comment]
I had it on ever Block i tried it. stone, spawner, chest (all types of
chests), machine Blocks from mekanism and all other sorts of blocks u would
want to Pick up like that

UnRealDinnerbone ***@***.***> schrieb am Do., 27. Apr. 2023,
16:32:

**Comment by UnRealDinnerbone** [comment]
Unable to reproduce this issue, if you're able to make this happen again please reopen the issue and attach logs file, so we can try and track issue
