### ISSUE TITLE
Keep falling through the void on server join

### ISSUE THREAD

**Issue by Colonelbacon22** [FTBTeam/FTB-Modpack-Issues#2697]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.1 and 1.3.2

### Log Files

https://imgur.com/a/cUBwEFs

### Describe the bug

Hello,

I'm hosting a Direwolf 1.9.2 1.3.2 Server for me and some friends, and after about 2 weeks of playing, one of my friends suddenly can't join. Every time he joins he just falls into the void for about 2 minutes and then crashes.

### Steps to reproduce

Cannot replicate the issue on other clients, only happens to one user's client for unknown reasons.

### Expected behaviour

Expected to be able to log onto the server but am unable.

### Screenshots

Have a screen recording of him attempting to join the server cannot upload it here and cannot post to Imgur as its over 60 seconds. Will update this when able to add it here.

### Additional information

Things we've tried:

Complete reinstall of FTB on his PC

Turned down render distance and installed Fastchunk and sodium on client and server

Has 16gb of ram allocated

System specs:
Ryzen 9 5900x
3070 ti
32gb ram
FTB on m.2 SSD
Network Speed of friend: ~500mbps down ~200mbps up

Can play single player and other Direwolf servers

Complete clean install of the server (Hosting on Apexminecrafthosting)

Friend completely uninstalled both the modpack and launcher multiple times with no success   

What's odd is 3 other people including me are able to play on the server just fine, but his client randomly stopped being able to connect properly. The server and mod pack version we were originally playing on was 1.1.1 until we ran into this issue and tried updating everything to 1.3.2.

Any ideas? I searched everywhere trying to find an answer before posting but couldn't find anything. Also let me know if there is a better forum to post this on.

Thanks

**Comment by Saereth** [comment]
Seems to be some kind of connectivity issue between your systems really difficult to diagnose without digging into network internals though which we cant do.  You can try removing the connectivity mod and see if it helps but beyond that I dont have much to suggest
