### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by FizzyPop521** [FTBTeam/FTB-Modpack-Issues#27]
### Modpack

FTB Oceanblock

### Modpack version

1.1.0 Beta

### Describe the bug

Petal Apothecary from Botania is not accepting any items, no petals, no seeds. I can put water into it, but will not accept anything else

### Steps to reproduce

1. Place petal apothecary
2. Fill with water bucket
3. Right click with petals or seeds
4. Nothing happens

### Expected behaviour

Petals to place into apothecary when right clicked

**Comment by Raidobw2** [comment]
Normally you throw the petals and the seeds, not right click them. The only right click interaction is actually shift right to take items out. I'd be surprised Vazkii let this through, especially how Botania was almost the first mod updated every Minecraft version!

**Comment by Sunekaer** [comment]
"To craft a flower in the petal apothecary, various petals and other ingredients must be thrown into it when it has water. Once all the petals are in, a seed must be thrown in to complete the recipe. Shift-right clicking on the apothecary will remove the last item put in."

**Comment by Sunekaer** [comment]
Does it work with throwing in items?

**Comment by FizzyPop521** [comment]
oh gods, im an idiot. thank you so much for pointing out the obvious for me lol

**Comment by FizzyPop521** [comment]
yes it worked
