### ISSUE TITLE
Dying in void during the final fight bugs the elytra flight

### ISSUE THREAD

**Issue by orbidlo** [FTBTeam/FTB-Modpack-Issues#2700]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.2.0

### Describe the bug

Playing on the server. Was knocked off the platform during Void Shadow fight and died due to void damage. My grave spawned way below the platform and in it full modular gear, several backpacks etc. Respawned on spawn due to broken bed, grabbed new elytra, rockets etc and wanted to return, retrieve gear and continue the fight. But once I returned, I couldn't fly again with the message that my rocket failed to ignite. So I couldn't retrieve my stuff and died again. Once in overwworld I crafted new elytra (crafted from two crude elytras) and rockets and still couldn't fly with same message, so this must be some bug. Once server op restored my gear from grave (my death there was due to irl emergency) I could fly again! When I switched from modular chestplate to normal elytra (the one that didn't work just moments ago) I was still able to fly but it gave me the "could not ignite" message.

### Steps to reproduce

1. have fully upgraded modular armor with flight and all eyes and chapters done, unlock void portal
2. enter void dimension, get knocked off platform when afk and die due to void damage
3. grave spawned at y:0 way below platform
4. respawn 
5. flight is bugged and get the message "rocket failed to ignite" both in the void dimension and in overworld when tried with new elytra and rockets
6. can't retrieve grave and die again due to boss
7. sad
8. my grave content is restored to me by server op
9. somehow my ability to fly is restored with it (using modular armor)
10.  switching to elytra gives me the fail message "cannot ignore" but still able to fly

### Expected behaviour

Flight is possible after death in void.

**Comment by TheonlyTazz** [comment]
the message always showed bcause of the message not being enclosed in the eyecounter check,this is fixed in the next update, same as graves now being spawned at lastblockpos
