### ISSUE TITLE
Stoneblock 3 crashing after accessing Refined Storage

### ISSUE THREAD

**Issue by Purpledennyson** [FTBTeam/FTB-Modpack-Issues#2702]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

[crash-2023-02-10_17.10.29-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10711942/crash-2023-02-10_17.10.29-client.txt)
[crash-2023-02-10_16.51.46-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10711943/crash-2023-02-10_16.51.46-client.txt)
[2023-02-10-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10711944/2023-02-10-2.log.gz)

### Describe the bug

When I am initially accessing the singleplayer world and attempt to access refined storage, the game will freeze and completely crash.

### Steps to reproduce

No idea what steps to take to get the issue to reproduce since it just crashes and I do not do anything prior but load up the world.

### Expected behaviour

Access refined storage network

**Comment by electricsteve** [comment]
I have the same issue, I have done some tests. And what i can conclude from my tests is: The game crashes when you open an rs grid if REI is not yet fully initialized, when REI is fully initialized it doesn't crash.

**Comment by DinnerBeef** [comment]
Unable to reproduce this is my dev version. When the next version comes out, can you please test this to see if this is still happening.

**Comment by Purpledennyson** [comment]
I figured out the issue, for some reason if you left items in the crafting
grid then logged out and then logged back in it would crash when attempting
to access any part of refined storage. Don't know why it would do that but
braking the crafting grid that had the items still in the grid and
replacing it fixed the issue.
