### ISSUE TITLE
[Bug]: Grey Vertical Line on screen

### ISSUE THREAD

**Issue by GrapePancakes** [FTBTeam/FTB-Modpack-Issues#2703]
### Mod

FTB OceanBlock

### Mod version

1.15.1

### Forge / Fabric version

36.2.39

### What issue are you having?

A big Vertical Chat box looking line on the side of the screen

### Steps to reproduce

Anytime i load in to the world its self, it appears and stays there

### Anything else to note?

![2023-02-10_20 52 13](https://user-images.githubusercontent.com/125104958/218235603-5b298908-66fc-415f-a48f-474365c44dd2.jpeg)
Ive tried resetting my pc, ftb, the line goes behind the map in game, so its not my monitor.

**Comment by DinnerBeef** [comment]
Looks like you must have accidentally pinned a quest. When you are in your quest book, you should see an icon on quests that you have pinned. You can unpin by opening the quest and clicking the pin next to the "X" button.
