### ISSUE TITLE
Botania craft crash world and game or craft botania potion

### ISSUE THREAD

**Issue by ph1823** [FTBTeam/FTB-Modpack-Issues#2704]
### Modpack

FTB University 1.16

### Modpack version

1.8.0

### Log Files

Botania craft: https://bytebin.lucko.me/1H1S36lYd0
Botania potion: https://bytebin.lucko.me/eWOOKefsXL

### Describe the bug

When i craft a botania brewing stand, my game has crash

Edit: i try to make botania potion and when i get a potion my game has crash

### Steps to reproduce

1. Create single player world
2. Make botania setup
3. Try to craft a botania brewing stand
4. The game crash

1. Place botania brewing stans
2. Try to make potion
3. That crasg

### Expected behaviour

game not crash

**Comment by Gaz492** [comment]
Unfortunately, the paste links are no longer valid, would you be able to upload the logs again so we can take a look?

**Comment by ph1823** [comment]
Why you close ?
I post m'y log this weekend, sorry dont have time to reply 😭

**Comment by Gaz492** [comment]
> Why you close ? I post m'y log this weekend, sorry dont have time to reply 😭

This issue should be fixed now in the update that was released today. :D

**Comment by ph1823** [comment]
> > Why you close ? I post m'y log this weekend, sorry dont have time to reply 😭
> 
> This issue should be fixed now in the update that was released today. :D

Oh ok nice ! No need my log :D
