### ISSUE TITLE
Travel Anchors

### ISSUE THREAD

**Issue by Vo1d88** [FTBTeam/FTB-Modpack-Issues#2705]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.3.2

### Describe the bug

Travel Anchors doesn't render when you try to teleport to them.

### Steps to reproduce

Place a Travel Anchor
Name it
Try to teleport to it with a Travel Staff or with another Travel Anchor
It doesn't render

### Expected behaviour

I should render

### Screenshots

![2023-02-11_16 48 53](https://user-images.githubusercontent.com/123479379/218267598-d19bd6b1-2eab-4d22-97bb-fccf38bee59c.png)
![2023-02-11_16 48 57](https://user-images.githubusercontent.com/123479379/218267603-a544c637-d206-487c-8edf-a6860066f5d2.png)
![2023-02-11_16 49 05](https://user-images.githubusercontent.com/123479379/218267604-b879b913-913b-4a5a-bb45-5717d27cebd5.png)
![2023-02-11_16 49 09](https://user-images.githubusercontent.com/123479379/218267605-6a5ee292-34fd-4926-b3a7-f2c3a882cdb3.png)

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/220515925-a9cecc97-a58e-468e-82a8-fb6ad3a45042.png)
