### ISSUE TITLE
Industrial Foregoing Fluid Laser Base with Black Lenses does not produce Crude Oil

### ISSUE THREAD

**Issue by shank3001** [FTBTeam/FTB-Modpack-Issues#2707]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.3.2

### Describe the bug

Industrial Foregoing Fluid Laser Base with Black Lenses does not produce Crude Oil. 

### Steps to reproduce

1. Set Fluid Laser Base in whitelisted biome (Ocean or desert).
2. Add required black lens to fluid laser base .
3. Set depth between 20 & 60.
4. Add 4 or more Laser Drills surrounding Fluid Laser Base.
5. Ensure Laser Drills are properly targeting the Fluid Laser Base.
6. Add power to Laser Drills.
7. Add optional "tier 2" upgrades to both the Drills and Base 

### Expected behaviour

Should produce 50MB Crude Oil per processes. Nothing is being produced.

### Screenshots

![2023-02-11_23 38 46](https://user-images.githubusercontent.com/10300791/218299077-befef231-29d6-4d4d-8e57-c6ebd468349d.png)
![2023-02-11_23 38 57](https://user-images.githubusercontent.com/10300791/218299086-951323b7-8447-4fbe-b71f-31713c343f46.png)
![2023-02-11_23 39 06](https://user-images.githubusercontent.com/10300791/218299090-887208d6-a23f-4d59-aac7-51384fd28732.png)
![2023-02-11_23 40 12](https://user-images.githubusercontent.com/10300791/218299092-184a75e5-47f4-4040-b2ce-4f0a0388b544.png)

**Comment by Saereth** [comment]
This has to be fixed on IF's end, it's been reported
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1334
We will update once a fix is out

**Comment by LilLexort1** [comment]
Any update on this. Not working still in ATM 9

**Comment by daRealADONYS** [comment]
> Any update on this. Not working still in ATM 9

Actually it works, my problem was the y level. It needs to be under 60
