### ISSUE TITLE
No Quest completion when creating a Soul Crystal Shard

### ISSUE THREAD

**Issue by SirDragonKnight** [FTBTeam/FTB-Modpack-Issues#2708]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.4.0

### Describe the bug

Quest did  not complete when I made a Soul Crystal Shard.

### Steps to reproduce

Not sure if its reproducable or not.
1. I created the item as instructed
2. Picked the item up off the ground.

### Expected behaviour

For the quest to be completed

### Additional information

Quest did not complete until I put the item inside a chest and then pulled it out of a chest.

**Comment by SirDragonKnight** [comment]
Looks like this problem exists for all the quests in this chain. I havent' tried the Soul Cage or pedestal yet. Will update when I do.

**Comment by SirDragonKnight** [comment]
My bad, didn't mean to close this

**Comment by TheonlyTazz** [comment]
redone all the quests, worked on my testing enviroment
