### ISSUE TITLE
Server uses all memory and fails to start (memory leak)

### ISSUE THREAD

**Issue by SplenectomY** [FTBTeam/FTB-Modpack-Issues#2709]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.3.2

### Log Files

crash log (probably not much here) - https://pste.ch/uyawiqasuc.sql
debug log - https://pste.ch/amuxusinol.md
entire server - https://drive.google.com/file/d/1ngQ-nbi6lUplkrkV-pz7AtjtnwYRFzUp/view?usp=share_link

### Describe the bug

On server start, server eats up entirety of available memory and never fully loads. Tested on both linux and Windows environments with up to 16 gb of memory set in the start.bat.

My best guess is something to do with MineColonies, but also possibly Ad Astra. These were the mods our server was using most extensively prior to the problems.

### Steps to reproduce

1. Start the server

### Expected behaviour

Server starts and allows login

### Additional information

Due to the possible complexity of this problem, I have attached the entire server as a google drive link.

The debug.log link probably has the most clues, but there's not too much to go on.

I'm going to try slowly wiping things in Minecolonies first, then ad astra, to see if things work.

**Comment by SplenectomY** [comment]
Server has this to say right as it dies:

https://paste.pics/7736665fa3df5bbedc9a20d9deada5a5

**Comment by Zonk1987** [comment]
I had the same problem and added this following mods only to the Server:
Saturn -> https://www.curseforge.com/minecraft/mc-mods/saturn
Pluto -> https://www.curseforge.com/minecraft/mc-mods/pluto
Canary -> https://www.curseforge.com/minecraft/mc-mods/canary
Smooth Boot (Reloaded) -> https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded

After this the server runs very smooth.

I hope this can help you.

**Comment by SplenectomY** [comment]
anyone know if there's a way to profile memory usage during startup? Does Spark even have that kind of functionality? Much appreciated

**Comment by SplenectomY** [comment]
![image](https://user-images.githubusercontent.com/4369778/218857353-dc52f8b2-78a4-448f-b662-a163c2a252b8.png)

Latest update: I turned off the tick watchdog to see if it would eventually load and it comes to this after an hour and a half. This is both before and after attempting to use the mods @Zonk1987 suggested.

**Comment by FagSoft** [comment]
If you're using top (or similar) to monitor the memory usage, this won't give you an accurate depiction: Java will allocate all of the memory you give it, while Minecraft itself will only allocate what it needs from that. I've seen it recommended not to assign more than 10 GB to MC, due to inefficiencies in Java's garbage collection causing lag above this amount.

That said, I do wonder how big your world is in GB, and what kind of hardware you're running this on? The CPU and HDD setup most important parts.

**Comment by Saereth** [comment]
a ton of mods updated, let me know once 1.4.0 comes out if you still have this issue as I've not run into it else where so I'm hoping one of the mod updates resolved it.

**Comment by SplenectomY** [comment]
@Saereth Just got the server up and running, looks good so far. Started up relatively quickly, ram usage is nominal and performance is good so far. Will watch it for a couple days and update here.
