### ISSUE TITLE
[Bug]: Tape measure from Chisel and Beats given to the player doesn't work right

### ISSUE THREAD

**Issue by GriSphera** [FTBTeam/FTB-Modpack-Issues#271]
### Modpack

FTB University 1.16

### Modpack version

1.3.0

### Describe the bug

I was playing FTB University 1.16, and I got to the chisel and bits quest. The tape measure that was given to the player by completing it had a missing texture, a name that was likely it's ID and a decription that says "Missing Item". Still, the Tape Measure is craftable and has totally different properties. I think the mod might have been updated between versions of the modpack and the developer changed the IDs of the tape or something. Some screenshots below.
![2021-11-07_11 59 27](https://user-images.githubusercontent.com/88846902/140654675-a47605db-6823-4605-8d4b-ce542a33e583.png)
The quest in question.
![2021-11-07_11 59 35](https://user-images.githubusercontent.com/88846902/140654687-b33e049a-3b4a-4228-97a3-cb0a7cc469ca.png)
The Tape Measure that appears in game.
![2021-11-07_12 07 39](https://user-images.githubusercontent.com/88846902/140654704-bf0e24fa-3cd0-46b3-ad07-cadca88f015c.png)
The Tape Meausre you get from completing the quest.

### Steps to reproduce

1. Have that quest completely clear.
2. Craft a chisel from any of the basic vanilla materials.
3. Go to the quest in the misc section and claim it, along with the Tape Measure.

### Expected behaviour

I'm not sure. It just looked interesting so I claimed it regardless. But  if at all, get the working Tape Measure.

**Comment by Raidobw2** [comment]
To dev: name probably changed from tape_measure to measuring_tape from the mod update. A little switcheroo!

**Comment by aaronhowser1** [comment]
> To dev: name probably changed from tape_measure to measuring_tape from the mod update. A little switcheroo!

Correct, fixed
