### ISSUE TITLE
Pipe and Smelter interaction

### ISSUE THREAD

**Issue by RoboticWrapper** [FTBTeam/FTB-Modpack-Issues#2712]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

Pipe from the Pipez mod losses upgrades when smelter is broken

### Steps to reproduce

1. Have any Item or liquid pipe extract from the Tinkers construct multi block through a duct
2. have any upgrade in the pipe i.e. (speed, filter)
3. break the Smelter controller

### Expected behaviour

Pipe stays in configuration but useless

**Comment by UnRealDinnerbone** [comment]
This is intended as when the smelter controller is broken the whole blocks no longer become "tanks" so pipez no longer seems them as valid blocks to connect to
