### ISSUE TITLE
FTB: Legend of the Eyes version not available for download

### ISSUE THREAD

**Issue by SterlingVesper** [FTBTeam/FTB-Modpack-Issues#2714]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.3

### Describe the bug

1.3 doens't exist, yet in server files you can download version 1.3 to run your server on. Since my server provider only has version 1.3 it makes it impossible to play on my server due to the incompatibility. Why isn't the FTB app showing version 1.3 as an available version.
![1Capture](https://user-images.githubusercontent.com/125304382/218546322-559bce15-e72f-4ff5-aead-67d78a1b9924.PNG)

### Steps to reproduce

1. Go to FTB app Legend of the eyes modpack.
2. See latest version 1.2
3. click on server files 
4. see version 1.3 available to download server on
5. notice that 1.2 is the latest version available to run your client on, but 1.3 is the last version to run your server on.

### Expected behaviour

I expected the version to be listed in the FTB app to download

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/219084974-a4051c8a-36b7-4acd-beec-ce9697daa82a.png)
refresh ur cache

click the gear, go to App Info, and click the Refresh Cache button
![image](https://user-images.githubusercontent.com/3908847/219085157-eee739c6-f74b-42f6-bdd3-a602c887a3d6.png)
