### ISSUE TITLE
Avaritia Extreme Crafting Table "eats"/deletes ingredients on Server

### ISSUE THREAD

**Issue by CarbyDood** [FTBTeam/FTB-Modpack-Issues#2715]
### Modpack

FTB Inferno

### Modpack version

1.5.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10727087/latest.log)
Skip to line 17325 for the error

### Describe the bug

When trying to craft anything with the infinity ingot on the extreme crafting table on a SMP server, the game will randomly wig out and then delete the item i was dragging. Relogging and sorting my inventory does not bring the item back and it seems to have been permanently lost. Video of the behavoir will be attached. Whenever this happens, the server log spits out an error (specified in the log file). This also happens when using the "Move Items" Button with JEI; It will delete all the items that were supposed to be used in the recipe except for a single infinity ingot.

### Steps to reproduce

1.)Set up Inferno Server with 22G of allocated ram
2.) Try to craft the Sword of the Cosmos
3.) when putting down the infinity ingots, they will start to randomly disappear from the table
4.) with the needed ingredients in your inventory, try to use JEI to Move all Items onto the extreme crafting table
5.) observe that the items will be deleted, save for 1 infinity ingot.

### Expected behaviour

Normal crafting of a item with no ingredients disappearing

### Additional information

Video of the behavoir:
https://youtu.be/3BUVWYUfnwY

**Comment by zediious** [comment]
I can confirm the occurrence of this bug from a player on my server. I'll update this comment with relevant logs, wanted to chime in and say this is definitely a thing.
