### ISSUE TITLE
Minecolonies doesn't recognise MC clocks.

### ISSUE THREAD

**Issue by FagSoft** [FTBTeam/FTB-Modpack-Issues#2718]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.2.1

### Log Files

N/A

### Describe the bug

When trying to have the builder make the Cavern's "Main Gate Courtyard" 
large decoration, it will stall on requesting a regular MC clock. However, no matter how you provide this clock to the builder, it will not recognise it. Causing the builder to be stuck.

Double checked to see if there were any other recipes for clocks, which there weren't.

### Steps to reproduce

1. Start a Caverns Minecolony.
2. Request a Large Decoration -> Main gate (land).
3. Wait until the builder requests a clock.
4. Try to give it to him.

### Expected behaviour

The builder to accept being given a clock, either by the couriers or player.

### Screenshots

![image](https://user-images.githubusercontent.com/3675554/218698119-8e7e874f-d8c7-4dc1-a861-7764c2e03447.png)
![image](https://user-images.githubusercontent.com/3675554/218698315-bacd4556-8753-4af2-b994-39b24dec9cc3.png)
![image](https://user-images.githubusercontent.com/3675554/218698400-9289c301-541d-4010-94f4-cc4827e6ecfe.png)

**Comment by adam-miller** [comment]
One workaround is to go into creative mode, and then you can click to fulfill anything in the list. I have encountered builds that depended on specific user heads that could only be resolved that way.

**Comment by FagSoft** [comment]
> One workaround is to go into creative mode, and then you can click to fulfill anything in the list.

You can also enable Cheat Mode on JEI, and spawn the item from there. Just make sure to put it directly into the inventory of the builder/builder hut, and not into your own. Apparently some NBT tags change once you put it into player inventory, which causes it to be not recognised.

Same goes for Compasses.

**Comment by Saereth** [comment]
quark was adding the nbt to both, fixed for next udpate but you'll need to recraft your clocks and compasses

**Comment by FagSoft** [comment]
Thanks for the updates, @Saereth, to all of the issues I've reported.
Recrafting won't be an issue, but thanks for the heads up as well.
