### ISSUE TITLE
Certus Quartz does not even exist.

### ISSUE THREAD

**Issue by Sangha0** [FTBTeam/FTB-Modpack-Issues#2719]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.0.1 (stabil version) / 3.2.1 Latest version (beta)

### Log Files

I have realised now that I completely forgot about Certus Quartz, now I have come to the point where I want to build a ME system with applied energetics AE2.
But Certus quartz is the main “ore” for ME systems, when will there be an update??

### Describe the bug

I have realised now that I completely forgot about Certus Quartz, now I have come to the point where I want to build a ME system with applied energetics AE2.
But Certus quartz is the main “ore” for ME systems, when will there be an update??

### Steps to reproduce

Don’t know how to fix it need help..

### Expected behaviour

AE2 won’t work properly!

**Comment by EndlessDex** [comment]
@Sangha0 AE2 does not use ore anymore. They moved to a system like vanilla amethyst. You find the Budding Certus in the meteorites. This is what produces the crystals.

PS Crystal Growth Accelerator is OPOP

**Comment by Saereth** [comment]
Endless is correct
