### ISSUE TITLE
[Suggestion]: Applied Energistics 2 Wireless Terminals

### ISSUE THREAD

**Issue by xSvenHD** [FTBTeam/FTB-Modpack-Issues#272]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

Refined Storage has a wireless crafting terminal but Applied Energistics 2 doesn't have one. 
There is luckily an addon mod that adds that. Would be a very nice addition for people that use/prefer AE2 like me.

The default wireless terminal doesn't have a crafting grid. 

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals-forge
Adds wireless **crafting** terminal and a couple more.

**Comment by Sunekaer** [comment]
Thanks for the suggestion but we not looking to add more mods, will keep this mod in mind the future packs.
