### ISSUE TITLE
Occultism Spirit Campfire causes ticking entity resulting in server lag/crash

### ISSUE THREAD

**Issue by AK-Zephyr** [FTBTeam/FTB-Modpack-Issues#2725]
### Modpack

FTB Inferno

### Modpack version

1.5.0

### Log Files

Server Generated Error Log:

https://pastebin.com/FpxhR8SW

Server Error Message Indicating ticking block:

```
Server thread/WARN
Block entity minecraft:campfire @ BlockPos{x=241, y=128, z=246} state Block{occultism:spirit_campfire} facing=south,lit=true,signal_fire=false,waterlogged=false] invalid for ticking: 
```

### Describe the bug

The block "Spirit Campfire" causes a Ticking Entity resulting in the Server Watchdog restarting the server after a single tick took more that 60.00 seconds. 

Our monitoring software showed that the server was running at 4TPS after restart without anyone connecting (Expected 20TPS). Attempting to connect to the server in game would result in the Server Watchdog restarting the server instance.

We were able to work around the issue by:
Changing `max-tick-time` to `-1` in `server.properties` - prevented the watchdog from killing the instance.
Logging into the server in game (Extremely slow and laggy)
Used F3 menu to navigating to the ticking entity block and destroying it - coordinates for this block were displayed in the server console.  (Depending on situation one may need to use commands to teleport player to the entity)

After the block was destroyed the server immediately caught up and ran stable again. Destroying the block gave back the Spirit Campfire and four brown mushrooms. The incompatible cooking of mushrooms likely compounded the issue.

Further testing revealed that even just placing down the campfire by itself, no attempt to cook, resulted in ticking entity errors in the server console.

### Steps to reproduce

1. Place the Occultism Spirit Campfire in a persist chunk (FTB Teams)
2. Watch as the server throws errors and potentially restarts 

### Expected behaviour

Spirit Campfire doesn't cause ticking or is entirely remove/disabled from pack.

### Screenshots

Initial server console error after 'disabling' the Server Watchdog:

![image](https://user-images.githubusercontent.com/29581915/219827879-2617a40a-c6d2-444e-97c0-41bdf33ec126.png)

Resulted server console error after placing down the some fire slightly elsewhere

![image](https://user-images.githubusercontent.com/29581915/219827909-2033e382-f134-44ce-818d-e43477549b9a.png)

### Additional information

The test of placing the campfire down a second time did not cause nearly as much lag. This may indicate that the attempted cooking of mushrooms severely compounded the ticking loop.

Reviewing the JEI for this block - it does not appear there is any practical, non cosmetic, use for it. All necessary "spirit" conversion are handed by the standard non-campfire spirit fire you create via starting a fire on the demon dream item.

**Comment by Saereth** [comment]
updated occultism for next update should fix this
