### ISSUE TITLE
Cpu usage 100%

### ISSUE THREAD

**Issue by sysyss** [FTBTeam/FTB-Modpack-Issues#2727]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

none

### Describe the bug

my computers cpu is intel i5 6500 and setting ram usage of minecraft is 18Gb

when is start lauch, minecraft is cpu usage is over 100% and computer is little stop.
when open map file  game is stop agin (also i just few day of playing, so my map is not 30MB yet )
after star map, shift control is lock and didn't respond. 

can't not sneak, can't not wrench create, even can't see chickens data.

What should i do?

even strange thing is just shift input was problem. input upacase latter(in chat or other.) has no prablem

### Steps to reproduce

1. try to play minecraft.
2. shift is lock

### Expected behaviour

normal shift key working.

**Comment by 5ully** [comment]
You should not allocate 18 gb of ram to java, 6-8 should be enough, even if you have 32gb of total ram. java will also use more ram than you allocate it.
