### ISSUE TITLE
stoneblock 3 broken spawn issue

### ISSUE THREAD

**Issue by matt14509** [FTBTeam/FTB-Modpack-Issues#2729]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10776615/latest.log)

### Describe the bug

Spawn on my server was broken.

### Steps to reproduce

1. Lunch stoneblock
2.play on your server for a while.

### Expected behaviour

Idk

### Screenshots

![image](https://user-images.githubusercontent.com/88714707/219942459-a51a4f4c-409f-4449-b23f-ac0f8aaae339.png)

**Comment by matt14509** [comment]
- Place down a structure block in the bottom right of the spawn area (outside of the spawn area, not inside).
- Go to load mode in the GUI of the structure block
- Enter the name as "ftbstoneblock:lobby"
- Select the correct load button
- Close the GUI and look at the outline it's placed in the world. If it looks close enough 
- Open the GUI again and click load once more. This will rebuild your spawn area

**Comment by matt14509** [comment]
I turned off the server at the boot stage, but there was no one on the spawn.

**Comment by matt14509** [comment]
.

**Comment by UnRealDinnerbone** [comment]
That would be the reason as you stopped the server will the chunks were loaded. Spawn chunks are always loaded
