### ISSUE TITLE
FTB quest translation for stoneblock3

### ISSUE THREAD

**Issue by yiqv** [FTBTeam/FTB-Modpack-Issues#2731]
### Modpack

FTB StoneBlock 3

### Modpack version

FTB quest translation for stoneblock3  

### Log Files

https://pste.ch/aforosalom.json
👆Chinese
@Sunekaer Long time no see!
UPDATE!

### Describe the bug

1

### Steps to reproduce

1

### Expected behaviour

Come on

**Comment by yiqv** [comment]
@Sunekaer

**Comment by yiqv** [comment]
@Sunekaer

**Comment by 5ully** [comment]
Poor Sune getting mega pinged
