### ISSUE TITLE
Ars Nouveau Spell Turrets Not Functioning

### ISSUE THREAD

**Issue by Anghamarad** [FTBTeam/FTB-Modpack-Issues#2732]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.3.2

### Describe the bug

Can't get any spell turrets to function. Even simple spells like projectile-break. Source is there and is getting pulled but the spell won't go through. 

### Steps to reproduce

1. Place Spell Turret
2.  Set spell with spell parchment
3. Provide redstone signal

### Expected behaviour

Spell turret should apply the set spell

**Comment by Anghamarad** [comment]
Having similar issues with Industrial Foregoing's Block Placers. I thought it might be an FTB Chunks issue, so I set the config to allow all fake players. Both in game and in config files. Still no luck.

**Comment by Anghamarad** [comment]
> Having similar issues with Industrial Foregoing's Block Placers. I thought it might be an FTB Chunks issue, so I set the config to allow all fake players. Both in game and in config files. Still no luck. Also, doesnt seem to be working outside of the claimed chunks either.

Figured it out. Minecolonies chunks

**Comment by Bumbelberra** [comment]
Hi! Can you please help a noob. I think I have the same problem. But  I have no idea how to fix it

**Comment by Bumbelberra** [comment]
Did figured it out :)
/mc colony delete 1 false keep buildings
