### ISSUE TITLE
Several tags are empty

### ISSUE THREAD

**Issue by wrincewind** [FTBTeam/FTB-Modpack-Issues#2734]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.1.0

### Describe the bug

i've noticed a few recipes have empty tags, most notably refinedstorage:silicon (preventing the crafting or usage of Raw Super Advanced Processors - i think the recipe needs to be changed to use forge:silicon), but also the following:

minecraft:carpet (used for crushing into string)

minecraft:boats (used for making the Minecolonies starter boat, among other things) 
Oddly, for this one, i can see that  line 3173 of kubejs\exported\tags\minecraft\item.txt explicitly lists the minecraft:boats tag and its contents. I can see that minecraft:chest_boats (listed in the same sheet) has a valid tag, but boats themselves have no tag at all.  and in kubejs\server_scripts\tags.js, we have event.get('minecraft:boats').add('minecraft:oak_boat'). 
other stuff in there is working just fine; i can see forge:ores/iron being applied to the Ad Astra iron ores.

c:purple_sand (the various Biomes You'll go coloured sand types, used to make coloured sandstone), 

BYG:Brown Dye (no idea what this recipe was for, but the recipe is hanging around still even though the tag is empty... )

There's also a few useless broken recipes, like forge:storage_blocks/raw_silver in a crusher makes 12 silver dust, despite Raw Silver not having a storage block. 

Were these issues fixed in a more recent version? I'm playing on a server, so i cannot easily check myself.

### Steps to reproduce

1. look up Raw Super Advanced Processor in JEI
2. Check the recipe
3. See a barrier block showing up instead of silicon
4. right click the barrier block for 'show uses' to see all other broken recipes / missing tags (there's more than what I listed here; silent's gems is a mess, for example, but I don't know enough about Silent's to speak about that authoratively)

### Expected behaviour

Super Advanced Processors to be craftable as usual

**Comment by Saereth** [comment]
the circuit was fixed in the new versions
the boat issue persists, waitng on a mod update but we're aware so this is technically a duplicate,
carpets dont crush to string but wool does, the carpet tag is fixed
the minecolonies ship recipe needs fixed meanwhile but otherwise these should all be sorted in the next update (and some have already in the current update)
