### ISSUE TITLE
LoTE: Massive console spam on servers

### ISSUE THREAD

**Issue by tac-owo** [FTBTeam/FTB-Modpack-Issues#2736]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.3.0

### Describe the bug

LoTE's server constantly spams the console with random information, making it near-impossible to run server-side commands. Also causes huge log files, so huge that I cannot upload them since I cannot open them. I attached a screenshot of the server running for like, 16 hours.

### Steps to reproduce

1. Run server
2. Have people play on it
3. Look in the server console, and see a bunch of server_scripts:entityhandler.js.8

### Expected behaviour

The server to make log files that aren't a thousand times larger than the entire raw data of an Apollo mission

### Screenshots

GIF of Console - https://gyazo.com/f19644fafc552aa6b9ac5c8388479f27

Imgur link to the properties of the log file, I can't open it - https://imgur.com/a/j7toe7I

GIF of Console while my friend is mining - https://gyazo.com/4126fc1c926411ffc43976eb42d6851a

I think it's running like, 8 checks on every entity every time an entity is created.

**Comment by TheonlyTazz** [comment]
Hotfix is on its way!

In the meantime, I'd anyone experiences this issue
.go check
/KubeJS/server_scripts/entityhandler.js

And delete line8
`for(let i in entity) console.log(i)`
