### ISSUE TITLE
Duping Items with Rod of Lyssa and Mimicube

### ISSUE THREAD

**Issue by Karatemango** [FTBTeam/FTB-Modpack-Issues#2738]
### Modpack

FTB Inferno

### Modpack version

1.5.0

### Describe the bug

Alexmobs's Mimicube copies the attackers Items in the Main- and Offhand and uses them. I dont think they drop them though.
Rod of Lyssa of Reliquary can be bought at the Fisher Villager which has a chance to pick-pocket items off mobs.
This includes the equipment copied by mimicube.
One may say it can be hardly abused as mimicubes cant respawn, however you can put mimicubes in soulshards.

### Steps to reproduce

1. Get Mimicube at a Gluttony Dungeon(?) (you may want to use a soulshard, as they don't seem to respawn. A Tier 1 Shard requires litterly 1 soul)
2. Hit a Mimicube with the Item equipped. (It will copy Main- and Offhand)
3. Fish it alot with Rod of Lyssa. I recommend making a hole or such, so you can just keep holding rightclick. Don't expect it to work right off the start, as i needed to fish it ALOT. I don't know the chances of it happening but it seemed around 1% or lower.
4. You'll hear a breaking sound when it happens. The Mimicube should now have dropped the items in the Main- and Offhand.
5. Profit!

### Expected behaviour

Duping is never the expected behaviour.

**Comment by Saereth** [comment]
This is a mod interaction that we're aware of and found it not to be a breaking issue for the pack so basically it's fine and its a unique interaction between mods that people are free to use without breaking the balance of the pack overall. Thank you for reporting the issue though as always
