### ISSUE TITLE
Thorns effects can cause a crash due to a ticking entity

### ISSUE THREAD

**Issue by Chirimorin** [FTBTeam/FTB-Modpack-Issues#2745]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.3.2

### Log Files

https://pastebin.com/VLZQ8Urr
https://pastebin.com/F0DyD7yn

### Describe the bug

When an entity dies to any thorns effects, the game (or server) can crash with a ticking entity error. 
The source does not seem to matter. I've managed to crash the game with both modded and vanilla sources of the effect. 

### Steps to reproduce

1. Enchant some armor with the (vanilla) Thorns enchantment or get a thorns-like effect from any other source in the modpack. 
2. Spawn some mobs (I used Wither Skeletons) and let them hit you until they die
3. At some point, the game/server will crash. 

### Expected behaviour

The game shouldn't crash because of entities dying to thorns.

**Comment by DarkQuiet** [comment]
I have exactly the same problem modpack FTB ONE
