### ISSUE TITLE
Statue mod crashes launcher with upgrade Mob Killer enchant II+

### ISSUE THREAD

**Issue by MrRavain** [FTBTeam/FTB-Modpack-Issues#2749]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.4.0

### Log Files

[2023-02-24-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10828199/2023-02-24-1.log.gz)

### Describe the bug

Placing statue with Mob killer upgrade causes crash launcher.
I tried with creeper and zombie statue with mob killer II and III, crashes in both.

Mob killer I doesn't crash launcher.
Any other statue upgrade doesn't crash launcher.

### Steps to reproduce

Place s.t.a.t.u.e, pick one of mob statues
Upgrade it in "s.t.a.t.u.e" table to  mob killer I with diamond sword, 
then upgrade it to Mob Killer II with Lapis block and enchant book.
Spawn mob according to statue u picked.
Be happy with crash when statue deal damage.

### Expected behaviour

Crash

**Comment by KPear87** [comment]
This issue is still present in version 1.6.1. I've had to start over twice already before I found the issue._
