### ISSUE TITLE
OceanBlock Single Player World Not Opening To Friends

### ISSUE THREAD

**Issue by Lonedeath420** [FTBTeam/FTB-Modpack-Issues#2752]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.15.1

### Describe the bug

Hi, I was playing oceanblock on a single-player world and invited friends to join, we were playing all night, and now all of a sudden they can't join. They instantly get kicked when trying to join. 

### Steps to reproduce

1. Open Single Player world to friends
2. Friends join the world
3. friends instantly get kicked

### Expected behaviour

Said above

### Screenshots

![image](https://user-images.githubusercontent.com/126301564/221328652-8883672a-0a53-4247-8645-91b037f3ba1a.png)

**Comment by manmaed** [comment]
This issue is stale and pack is no longer being worked on
