### ISSUE TITLE
OceanBlock 1.15.1 Friends no longer able to play together on world

### ISSUE THREAD

**Issue by b2dull** [FTBTeam/FTB-Modpack-Issues#2754]
### Modpack

FTB OceanBlock

### Modpack version

1.15.1

### Describe the bug

My friends and I have made a total of two worlds. we have discovered that after playing the mod pack ocean-block for an extended period of time it just randomly decides to not allow any of my friends to join the world. we have invested a lot of time playing together for it to all amount to nothing. my friends have even tried downloading the world and trying it on a different host but that didn't change it. it is something corrupted in the world files or the profiles of my friends on my world. I'm not sure what to do and i really really don't want to lose all of our progress for the second time now. I've found a lot of enjoyment in this modpack and will be waiting for a response. please someone help me.

### Steps to reproduce

go to single player world 
load in
select the open world to friends button
it opens to friends
friends attempt to join 
error code wont let them join

### Expected behaviour

said above

### Screenshots

Lonedeath has a screenshot not too much to show

**Comment by manmaed** [comment]
This issue is stale and pack is no longer being worked on
