### ISSUE TITLE
Direwolf20 1.19 pack memory leak causing whole PC to lag

### ISSUE THREAD

**Issue by ninja85a** [FTBTeam/FTB-Modpack-Issues#2755]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.3.2

### Log Files

https://pste.ch/ovoyiliwen.md

### Describe the bug

after a few hours of playing on a FTB direwolf20 1.19 server I start nearly maxxing out my systems ram, only I am affected I'm on linux, running the prism launcher via flatpak while my friends are on windows and are fine and not having any issues while playing for the same amount of time

### Steps to reproduce

1. launch direwolf20 1.19
2. join server
3. play on it for a few hours, going to end, nether the moon
4. watch ram usage go over 10GB that was allocated up and going up to 15GB is highest I've noticed
5. system starts to lag with cpu usage maxing out as well

### Expected behaviour

to not go super high ram usage

### Additional information

I have installed journeymap, easier sleeping and entityculling, I did install entityculling after it started leaking memory so I dont think that is the reason

**Comment by Saereth** [comment]
Going to need some profiling data or something. What JVM args are you using, can you use some profling tools like spark over time to share the profiling data with us. Without being able to reproduce it myself and it happening under fairly specific circumstances for you It will be difficult to troubleshoot this.

**Comment by ninja85a** [comment]
I'm not using any JVM args in prism launcher and how would I use spark to get the profile data to share with you?

------- Original Message -------

**Comment by Saereth** [comment]
Here are the instructions for Spark, https://spark.lucko.me/docs/Command-Usage you'll want to probably run it when you mem usage is particular high so we can see whats using it and once you stop it'll give you a link to share with us

**Comment by ninja85a** [comment]
https://spark.lucko.me/8GPo6WliZS is the record when my whole PC froze for maybe 20 seconds, I'm starting to wonder if its something else and MC is just using alot of ram to cause it

------- Original Message -------
