### ISSUE TITLE
Sever crash everytime i join. It started when i was crafting infinity sword

### ISSUE THREAD

**Issue by 7Overlord7** [FTBTeam/FTB-Modpack-Issues#2757]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Log Files

25.02.2023 time 22:29:18.842
[debug-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10833663/debug-2.log.gz)
[2023-02-25-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10833667/2023-02-25-2.log.gz)

### Describe the bug

I can't join to the server.

### Steps to reproduce

I was on the server trying to make infinity sword by mechanical crafter. I made 9x9 mechanical crafter and then place every item in there. Then I clicked on the button and start making infi sword. When the sword was almost crafted, server crashed and now every time i join the server, it crash again. 

### Expected behaviour

I expected, that it will craft me infinity sword? 

### Screenshots

![image](https://user-images.githubusercontent.com/124199463/221409776-86371e17-9fba-49df-8306-4220d540fd25.png)

**Comment by 5ully** [comment]
Do you have a server crash log?

**Comment by 7Overlord7** [comment]
Server just crashed, there was nothing in the server crash log. But i can ask for them.

**Comment by DinnerBeef** [comment]
Were you able to get a crash log?
