### ISSUE TITLE
Leafs dont decay

### ISSUE THREAD

**Issue by lavouuzu** [FTBTeam/FTB-Modpack-Issues#2758]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.3.1

### Describe the bug

if you break a special tree (the normal generated on) the leaves dont decay and remain there forever.
The vanilla trees you're planting with seeds are working

### Steps to reproduce

destroy a tree
watch

### Expected behaviour

leaves decay

**Comment by TheonlyTazz** [comment]
we had this set to decayable leaves, but that was a Server Killer
thats why i disabled decaying again.
