### ISSUE TITLE
Automatic Shift-Clicking

### ISSUE THREAD

**Issue by joshonalog** [FTBTeam/FTB-Modpack-Issues#2759]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.19

### Describe the bug

Occasionally, whenever I click on any item in my inventory, it will automatically shift click. I have confirmed that it is not my keyboard thinking that I am pressing shift. Furthermore, when I type into chat the letters are not in all caps, it is solely when I click on an item that the game believes I am shift clicking it.

### Steps to reproduce

Unsure, this occurs randomly after anywhere from several minutes to one hour of play. 

### Expected behaviour

Expected to select an item as normal.

**Comment by Saereth** [comment]
think I sorted this in next update let me know if it happens again
