### ISSUE TITLE
Blood Magic start is out of order in the questbook

### ISSUE THREAD

**Issue by Jorvalt** [FTBTeam/FTB-Modpack-Issues#2760]
### Modpack

FTB Inferno

### Modpack version

1.5.0

### Describe the bug

For whatever reason, the quest book has you make the alchemy table and arcane ashes before the weak blood orb, even though you can't make anything with an alchemy table with no orb. The quest text for the alchemy table even references an "orb network" which you don't have yet.

### Steps to reproduce

Look at the "Sanguine Sting" section under Mephistopheles' Anger, and you will see that the ordering of the quests goes alchemy table -> arcane ashes -> weak blood orb.

### Expected behaviour

I expected the weak blood orb quest to be first in that order, considering it's required for the alchemy table to function.

### Screenshots

![2023-02-26_17 24 50](https://user-images.githubusercontent.com/5514973/221443782-b613404e-6cef-43c6-8e12-d7772798d029.png)

**Comment by Saereth** [comment]
it's actually not a requirement, its just the way the questbook is layed out a bit that the line looks like it is. Honestly its a bit difficult getting everything layed out well with so many interconnected pieces. you can see what I mean better here with it moved out a bit
![image](https://user-images.githubusercontent.com/9200909/222942750-6abc7e9a-6723-4dc0-a802-81885a76582b.png)
