### ISSUE TITLE
Game crash after launch

### ISSUE THREAD

**Issue by aniquelost** [FTBTeam/FTB-Modpack-Issues#2762]
### Modpack

FTB University 1.16

### Modpack version

1.16

### Log Files

https://bytebin.lucko.me/uKIZY325pA

### Describe the bug

Game crash after launch

### Steps to reproduce

Not a clue

### Expected behaviour

Launch game

**Comment by Gaz492** [comment]
Unfortunately, it looks like the paste link in no longer valid, if you are still having this issue, would you be able to post a new crash report for us?
