### ISSUE TITLE
FTB Inferno - crash after using mutandis

### ISSUE THREAD

**Issue by csuarezmtz** [FTBTeam/FTB-Modpack-Issues#2763]
### Modpack

FTB Inferno

### Modpack version

1.5.0

### Log Files

[crash-2023-02-27_10.57.53-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10842091/crash-2023-02-27_10.57.53-server.txt)
[crash-2023-02-27_10.52.23-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10842092/crash-2023-02-27_10.52.23-server.txt)

### Describe the bug

After using mutandis on sage (fully grown, planted on rich soil), the third one bugged (transmuted into nothing - the plant dissappeared). Now the game crashes when loading (I load right in front of the plant). 

### Steps to reproduce

*Cannot tell if it will reproduce consistently, happened on the third plant 

1. Use mutandis on sage planted over rich soil
2. the plan will dissappear instead of mutating
3. game will conitnue to crash when looking/being near the bugged plant

### Expected behaviour

Mutandis should work and game should not crash

**Comment by Saereth** [comment]
duplicate issue, waiting on a fix from hexerei which may not come but the work around is dig up the plant and replant it before growing it after you convert it
