### ISSUE TITLE
Interactions crashing

### ISSUE THREAD

**Issue by Shyskyemarie** [FTBTeam/FTB-Modpack-Issues#2766]
[crash-2023-02-27_22.39.35-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10846340/crash-2023-02-27_22.39.35-client.txt)
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Log Files

<img width="915" alt="Screenshot 2023-02-27 222219ftb" src="https://user-images.githubusercontent.com/126539208/221745765-7b1bf6d2-1380-464b-a0ca-1e925a8c6669.png">

### Describe the bug

the start up will run then a "the instance crashed or was closed" pops up

### Steps to reproduce

Go to the instance and click "play" wait and the crash pops up

### Expected behaviour

the game to launch

### Screenshots

<img width="915" alt="Screenshot 2023-02-27 222219ftb" src="https://user-images.githubusercontent.com/126539208/221746099-46fc2213-d38f-48ae-9ac2-7b8944fcc421.png">

**Comment by Shyskyemarie** [comment]
i have tried uninstalling and reinstalling the mod pack and clicked "retry" many times. i have also tried to restart my pc. i hvae run this many times before and this is my first time having a problem.

**Comment by Saereth** [comment]
This is some kind of hardware/driver issue, not something I'll be able to help with unfortunately
