### ISSUE TITLE
net.minecraftforge.fml.ModLoadingException: Mod §exnetgases§r requires §6xnet§r §o1.18-4 or above§r §7Currently, §6xnet§r§7 is §o§nnot installed

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [FTBTeam/FTB-Modpack-Issues#2767]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.5.0

### Log Files

This snippet should be enough:

net.minecraftforge.fml.ModLoadingException: Mod §exnetgases§r requires §6xnet§r §o1.18-4 or above§r
§7Currently, §6xnet§r§7 is §o§nnot installed

### Describe the bug

Trying to upgrade from 1.3.2 to 1.4.0, getting below error.

net.minecraftforge.fml.ModLoadingException: Mod §exnetgases§r requires §6xnet§r §o1.18-4 or above§r
§7Currently, §6xnet§r§7 is §o§nnot installed

### Steps to reproduce

1. Install anything lower than 1.3.2 on SERVER
2. Upgrade to 1.5.0 on SERVER

### Expected behaviour

Server upgrades should work. This is the third time an upgrade is breaking my server. :(

**Comment by misterzirillo** [comment]
I was able to get around this by running the install script a second time. After that, the server starts but my client is unable to connect #2768 so ymmv

**Comment by Saereth** [comment]
yeah mods just didnt download/install right looks like, reinstall was the right course of action
