### ISSUE TITLE
[Bug]: Game freezes when trying to make near infinite capacitor

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#277]
### Modpack

Ftb University 

### Modpack version

1.3.0

### Log Files

Latest Log: https://pastebin.com/KVn80fZG

Debug Log: Attached
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7497199/debug.log)

### Describe the bug

Game freezes forever during the crafting of near infinite capacitor (it happens as I add the ingredients, it happens throughout the process so doesn't happen with a single ingredient, its random)

### Steps to reproduce

1.) Try and make an infinite capacitor in an ultimate crafting table
2.) Freeze

### Expected behaviour

Don't freeze

**Comment by Raidobw2** [comment]
I can confirm, however I'm not sure if that's a mod issue or due to something in the recipe script.
![almost_infinite_cap](https://user-images.githubusercontent.com/17010632/140874254-5f445f15-2dac-4960-85e7-c6d7513a80b3.gif)

**Comment by JunaidA197** [comment]
This also happens when making the creative generator (think it may an issue with the ultimate table/ultimate table recipes?)

**Comment by zoller27osu** [comment]
does this still happen if you craft it with the Ultimate Package Crafter through AE2?

**Comment by zoller27osu** [comment]
Have discovered that this issue exists only client-side - had my friend try to manually craft it, and only they froze/crashed.

Unfortunately the Package Recipe Encoder doesn't seem to be working for the Creative Generator, so no workaround for that yet.

**Comment by zoller27osu** [comment]
> 

the Package Recipe Encoder seems to no longer have a problem with the Creative Generator recipe, at least not in singleplayer! It requires a Creative Chemical Tank though, so it still won't be craftable...
