### ISSUE TITLE
Server crash on login

### ISSUE THREAD

**Issue by cooleymt** [FTBTeam/FTB-Modpack-Issues#2770]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

https://pastebin.com/TBkXq2pM

### Describe the bug

On login server crashes and client stops responding

### Steps to reproduce

1. join server
2. server crashes

### Expected behaviour

Log into server and load world

### Additional information

The last thing that I did on the server was create a projectE and extendedExchange EMC farm which I chunkloaded using the FTB chunk claim/load mod.

**Comment by UnRealDinnerbone** [comment]
Same as #2501
