### ISSUE TITLE
Ability to set resolution

### ISSUE THREAD

**Issue by ThomasLilley** [FTBTeam/FTB-Modpack-Issues#2771]
### Modpack

FTB One

### Is your suggestion related to a problem? Please describe.

In the previous version of the modpack (1.3.0) I was able to set a screen resolution. Now with the new video settings options this has disappeared. This is frustrating as I play on a 5k screen but need a lower resolution to play this modpack at a reasonable framerate. The only workaround I have currently is to change the OS resolution.

**Comment by PentoreXannaci** [comment]
cant you set the resolution in the launcher before starting ftb?

**Comment by ThomasLilley** [comment]
I launch through the ftb app so the launcher is bypassed, unfortunately the only options I have in the ftb app are for window size, not resolution

**Comment by Saereth** [comment]
While you're in the advanced video settings press shift+p to bring up the vanilla settings and you can set your resolution to whatever you need in there, hope that helps!
