### ISSUE TITLE
Waystones Broken in 1.5

### ISSUE THREAD

**Issue by rgdelta1973** [FTBTeam/FTB-Modpack-Issues#2773]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.5

### Describe the bug

Unable to use warpstone to warp to waystone I use the item in my hand and nothing happens.  Tried in a existing world and new world.  Also Waystones no longer require xp to teleport.  Checked config file and it looks the same as 1.4 and nothing set to disable the xp I can see.

### Steps to reproduce

Make Warp Stone and Waystone
Place Waystone Name it
move away hold to use Warp stone does nothing no menu comes up nothing.

Make Waystones
Place Waystone
Go many blocks away
place another waystone
use waystone to go to first waystone (does not matter dimension or how many blocks away no xp requirement shows up.

### Expected behaviour

Warpstone on right click after charge time waystone menu is suppose to come up.  Waystones should show an xp cost for distance waystones and waystones in other dimentions

**Comment by ehertlein** [comment]
Just confirming that I am seeing the same behavior. Came here to put this issue in.

**Comment by Saereth** [comment]
this was a mod issue
https://github.com/TwelveIterationMods/Waystones/issues/672
we've update balm for the next pack update so should be sorted then
