### ISSUE TITLE
1.6.0 Crash on rendering Immersive Engineering Workbench with Blueprint

### ISSUE THREAD

**Issue by Sparklingtips** [FTBTeam/FTB-Modpack-Issues#2774]
### Modpack

FTB Inferno

### Modpack version

1.6.0

### Log Files

https://mcpaste.io/0be20be351e27a8a

### Describe the bug

When logging into a server after the 1.6.0 update if you are in an area where an immersive engineering workbench with a blueprint inside will render the client will crash producing the linked crash report. If you log in outside of the render range of a workbench the client will load normally however as soon as you move into an area where the workbench will render the client crashes.

### Steps to reproduce

1. Create a FTB Inferno server on a version before 1.6.0
2. Place an immersive engineering workbench with a blueprint
3. Disconnect from server within render range of the workbench
4. Update server and client to 1.6.0
5. Connect to server
6. Client crashes

### Expected behaviour

Client does not crash

### Additional information

Hosting provider: Pebblehost

There seems to be other users (Thetacapa1111#4054, Karatemango#4709) reporting this issue in the FTB discord Inferno channel so I don't believe this is limited in scope to just our server.

**Comment by Alaric323** [comment]
I can confirm this is an issue in a singleplayer world as well.

**Comment by Alaric323** [comment]
Unfortunately it doesn't seem to be fixed, still the same issue on 1.6.1.  Exact same crash report as SparklingTips again.

**Comment by Alaric323** [comment]
I did a full reinstall of the modpack as a new instance and that seems to have worked; it appears that an override may not be functioning correctly for this update.
