### ISSUE TITLE
Pondering “Mechanical Pump” crashes 

### ISSUE THREAD

**Issue by Maynase3** [FTBTeam/FTB-Modpack-Issues#2775]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.4.0

### Describe the bug

Pondering the “Mechanical Pump” from Create crashes the game. This was in Multiplayer survival. Minecraft version 1.19.2, Pack version 1.4.0, Create version 0.5.0.i-961

### Steps to reproduce

-Open JEI
-Search @create Mechanical Pump
-Hold W to ponder
-Game will crash before finishing step 2 of the pondering animation

### Expected behaviour

Pondering an item from Create does not normally crash the game.

**Comment by TheonlyTazz** [comment]
Seems to be fine working on my end?

https://user-images.githubusercontent.com/3908847/223050823-82f90b76-0478-4da9-828c-9ae70497722b.mp4
