### ISSUE TITLE
Server Crashes On Login

### ISSUE THREAD

**Issue by techsupport-noah** [FTBTeam/FTB-Modpack-Issues#2776]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.3.2

### Log Files

[nohup.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10880042/nohup.txt)
[crash-2023-03-02_18.29.50-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10880049/crash-2023-03-02_18.29.50-server.txt)

### Describe the bug

Server crashes on Null Pointer Exception

### Steps to reproduce

Fighting an end boss seems to be the reason, as it crashed the first time while fighting it and then continued to crash on login.

### Expected behaviour

Not crash.

**Comment by Saereth** [comment]
This should be fixed  in the next update now
