### ISSUE TITLE
[Server] - Windows Server Installer - start.bat doesn't take into account entered installation directory

### ISSUE THREAD

**Issue by Swirl9** [FTBTeam/FTB-Modpack-Issues#2777]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.4.0

### Describe the bug

Server doesn't start after accepting the EULA.
Nothing happens after launching the .bat file again. 

### Steps to reproduce

1. Download latest windows server installer
2. Run it
3. Enter an installation location (named mine server_location)
4. go to install location
5. launch start.bat
6. accept EULA
7. launch again

### Expected behaviour

Server should start

### Screenshots

![image](https://user-images.githubusercontent.com/111529305/222748202-2aaf7e9c-2009-4d34-a4c8-82050c49796b.png)
![image](https://user-images.githubusercontent.com/111529305/222749175-b4a55f81-4084-4cfa-991d-826c93037a37.png)

### Additional information

It seems that the installer nests the jar file inside a folder named from the install location prompt, but the .bat file doesn't take it into account

the -jar argument should specify that folder, or the installer should nest the jar file at the server root.

**Comment by TheonlyTazz** [comment]
Known issue, thanks for reporting tho
