### ISSUE TITLE
Industrial Foregoing - Wither Builder not working.

### ISSUE THREAD

**Issue by Kelambrad** [FTBTeam/FTB-Modpack-Issues#2780]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.3.2

### Log Files

N/A Not displayed in logs.

### Describe the bug

Wither Builder is supposed to place Soul Sand and Wither Skeleton Skulls. 
Wither Builder worked once as intended then stopped functioning.
Playing on a server with Normal Difficulty.
Items can be placed inside the Wither Builder, but then do not place.

### Steps to reproduce

1. Place Wither Builder
2. Attach power
3. Place required items inside the builder gui
4. Wither is not created
5. Nothing happens. Wait approx 10 minutes.

### Expected behaviour

Wither Builder recieves items and places the wither.

### Screenshots

![Animation](https://user-images.githubusercontent.com/13155773/222907263-6587dbb1-ad61-4133-8e9c-6c9e2538b8ff.gif)
![2023-03-04_14 08 18](https://user-images.githubusercontent.com/13155773/222907309-ddc34ba2-4231-4c1a-b529-0c5f37da4333.png)
![2023-03-04_14 08 26](https://user-images.githubusercontent.com/13155773/222907312-2b1e923c-ac01-472b-a93f-fab3fdc2f106.png)

**Comment by Saereth** [comment]
You're using it inside a claimed chunk, you need to set Ally [IF] in your allys list, this will allow other players to use IF machines to 'grief' your claims though. (block placer, block breaker ect). Or just move the builder outside of your claim.

**Comment by MaffooClock** [comment]
I'm having exactly the same problem on Direwolf20 1.19 v1.6.1 -- Wither Builder has power, Wither Skulls and Soul Sand are piped in, but it never places the blocks in the chamber above.  However, I do not have claimed chunks.

![Wither Builder GUI showing skulls and soul sand in place](https://user-images.githubusercontent.com/540782/224126241-a0b28cfa-5432-4685-8a8e-34aab648a697.png)

![Screenshot of Chamber showing valid working area](https://user-images.githubusercontent.com/540782/224126201-69bdc1e4-195c-4774-a969-172f5da23352.png)

**Comment by Kelambrad** [comment]
Hi [MaffooClock],
That's certainly strange with the original solution suggesting to use the builder outside claimed chunks.
My solution worked similarly to the suggested option.
As I am playing within a private server that I own I just allowed any block interaction to be public and that worked for me.
However I do not suggest doing so if you are playing on a server that is in the public domain.

**Comment by MaffooClock** [comment]
Hmm... I went into the mining dimension and built an identical setup (except using creative power source blocks), and it worked fine.

![wither builder in mining dimension](https://user-images.githubusercontent.com/540782/224360225-e8d38e1d-3865-4672-9f08-db899c6a38a8.png)

The only other difference I can think of is that our base is located within a MineColonies colony... maybe the [Colony Protection System](https://wiki.minecolonies.ldtteam.com/source/systems/protection) is interfering?  I can spawn a Wither manually, but the Wither Builder won't do it for me.

**Comment by MaffooClock** [comment]
Yep.  MineColonies' Colony Protection System was preventing the Wither Builder from working.

Setting `enablecolonyprotection = false` in the `[permissions]` section of `world/serverconfig/minecolonies-server.toml` allowed the Wither Builder to work.
