### ISSUE TITLE
Cant join any server in feed the beast modpack

### ISSUE THREAD

**Issue by iiShnouda** [FTBTeam/FTB-Modpack-Issues#2781]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.4.0

### Describe the bug

i have created a minecraft server for (legend of the eyes) modepack , i used the server installer but when , so when i join this massage appears what to do ?!!

### Steps to reproduce

![Minecraft Screenshot 2023 03 04 - 17 17 57 76](https://user-images.githubusercontent.com/126971489/222914804-394d7065-bd16-4946-bf32-46a1e26c913a.png)

### Expected behaviour

I cant Join any servers

### Screenshots

![Minecraft Screenshot 2023 03 04 - 17 17 57 76](https://user-images.githubusercontent.com/126971489/222914780-510e1918-0a1a-4fb8-8f47-8fb2e8a796d8.png)

**Comment by cheezwizard0403** [comment]
having this same issue unfortunately

**Comment by TheonlyTazz** [comment]
This issue should have been resolved in v1.5.0, please try again and if needed, please reopen the issue (or make a new one)
