### ISSUE TITLE
i lost the world

### ISSUE THREAD

**Issue by Chr18x** [FTBTeam/FTB-Modpack-Issues#2782]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

this morning i felt like playing a little stoneblock 3 but as soon as i opened the FTB app i noticed that my world is gone but i don't know why

### Steps to reproduce

1. open ftb app
2. launch stoneblock 3 
3. enter in singleplayer
4. there are no more worlds

### Expected behaviour

i expected to find my world  as always

**Comment by 5ully** [comment]
There can be a few reasons for saves vanishing, and the FTB app have had some issue loading packs sometimes, so i have a few questions?
- When you launched the ftb App, did it show you having no instances? And if so, how did you start Stoneblock?
- When You launch your stoneblock 3 instance, does the save folder have the save in it? (As in, does the folder exist and minecraft is unable to see it/read it)

Please add any information you can about those, though both might not apply. You can find the safe folder by clicking the worlds folder found here:
![image](https://user-images.githubusercontent.com/9050688/234969380-d54772b4-25d7-42b1-870d-28969705ba63.png)
