### ISSUE TITLE
Raw Tin/Lead/Aluminum ore + Bronze blend dust smelts as FTB Industrial Contraptions ingots, but recipies only accept forge:ingots

### ISSUE THREAD

**Issue by MechBFP** [FTBTeam/FTB-Modpack-Issues#2784]
### Modpack

FTB One

### Modpack version

2.0.0

### Describe the bug

As the title says, when you smelt "raw tin" (Mekanism) ore in a furnace (regular cobblestone furnace) they come out as "FTB Industrial Contraptions" tin ingots that don't have the forge:ingot tag, but then in FTBIC recipes only Mekanism tin ingots (and perhaps other forge:ingots/tin) are accepted.

According the Kubejs config files the mekanism:tin_ingot is the preferred item, so not sure why a regular cobblestone furnace that has nothing to do with FTBIC is producing an item specific to FTBIC.

### Steps to reproduce

1) Put "Raw Tin (Mekanism)" in a furnace.
2) Confirm you receive "Tin Ingot (FTB Industrial Contraptions)"
3) Try to make an "LV Battery" in the workbench.
4) See that it won't accept the "Tin Ingot (FTB Industrial Contraptions)"

### Expected behaviour

The recipies should accept any version of tin ingots.

**Comment by MechBFP** [comment]
I went through the various tag files in the ftbic jar and the Kubjs files and I can't find any reason why the "ftbic:tin_ingot" is not being tagged with the forge:ingot/tin tag. All the configuration looks correct, and other ftbic ingots don't have that issue.

**Comment by MechBFP** [comment]
This is also a problem with lead, aluminum, and bronze.

**Comment by RoshTMG** [comment]
I dug around in the files too, and I can't see anything out of place at first glance; everything looks business as usual. I had a look around online for relevant threads, and found only one that had to do with kubejs and unified tagging. Barely relevant. I checked the FTBIC jar for any plugins anyways, though, and found one; I had a peek inside the dev/ftb/mods/ftbic/kubejs folder and found two files that seem to have something to do with recipes and ingredients? It's worth noting that the other mods relevant to this problem (mainly extreme reactors and mekanism) do not have these files or plugin. I'm not really a minecraft modder, though; I'm just able to see discrepancies. I could be totally off-course; the files in question are too arcane for somebody as technologically illiterate as I to decipher.

Mods affected are anything that uses:
Tin
Lead
Uranium
Iridium
Enderium
Aluminum
Bronze
