### ISSUE TITLE
Tempad Portal not closing.

### ISSUE THREAD

**Issue by TheLoneDude** [FTBTeam/FTB-Modpack-Issues#2787]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

The Tempad portal will not close and has been open for at least an hour in real time.

### Steps to reproduce

1. Use Tempad item to travel to a location.
2. Returning back to portal location, found it still there.

### Expected behaviour

Portal should close shortly after use.

### Screenshots

![Screenshot (171)](https://user-images.githubusercontent.com/86646904/222940749-6cc4f0c9-5421-4003-b2f8-e7be098b110e.png)

### Additional information

World was open to friends on MineTogether Connect, unsure if that's what caused the issue.

**Comment by DinnerBeef** [comment]
Unable to reproduce this in my current dev version. Can you let us know when the next version comes out if this is still an issue?
