### ISSUE TITLE
[Bug]: Compacting Drawer with Rubies/Sapphires

### ISSUE THREAD

**Issue by andr9528** [FTBTeam/FTB-Modpack-Issues#279]
### Modpack

FTB OceanBlock

### Modpack version

1.7.0

### Describe the bug

Compacting Drawer not compacting Rubies/Sapphires

### Steps to reproduce

1. Get a Compacting drawer.
2. Add Rubies/Sapphires.
3. Be sad and look at this error.

### Expected behaviour

I'd expect the Rubies/Sapphire to be compacted in the drawer.

### Screenshots

![2021-11-08_22 09 46](https://user-images.githubusercontent.com/21788044/140818846-95b03b54-767f-46e9-b25d-396bcda7f3b7.png)
![2021-11-08_22 09 50](https://user-images.githubusercontent.com/21788044/140818852-6476e638-09c7-474d-b5e3-039411676c4d.png)

### Additional information

Seems to be missing the unpacking recipe. Adding the unpacking recipe should fix them for Compacting Drawers.

**Comment by KennethHoff** [comment]
Slightly unrelated, but could you also change the rule for sand to use compressed sand instead of sandstone? Placing sand gives sandstone, and placing 1x compress sand gives 1x,2x, and 3x compressed sand respectively

**Comment by Raidobw2** [comment]
See #263, this has already been answered
