### ISSUE TITLE
Issue with the mod Spiceoff

### ISSUE THREAD

**Issue by JeanHubertDLC** [FTBTeam/FTB-Modpack-Issues#2791]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.4.0

### Log Files

Client logs
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10892813/latest.log)
Server logs
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10892814/latest.log)

### Describe the bug

![image](https://user-images.githubusercontent.com/33748974/222982705-4e76f958-fe81-449f-b013-5c35092f5c22.png)
Here is the error I get when trying to reach my server. 
I checked all the updates and they are good, and the mods (spiceof) are in both client and server folders 
It seems that the client do not find the mods the server is asking from him

### Steps to reproduce

Download the FTB Modpack Legend of the Eyes Server builder.
Build the server. 
Get to the mods folder in server files, and copy and paste in the mods folder in client side.
Turn the server on and try to connect to it with your client

### Expected behaviour

Successful connection to the server with mods on

**Comment by TheonlyTazz** [comment]
spice of life adds items if enabled in their config, be sure to copy that over aswell.
