### ISSUE TITLE
Some blocks loses their content when reloading and/or stop working

### ISSUE THREAD

**Issue by siconnellym** [FTBTeam/FTB-Modpack-Issues#2794]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.4.0

### Describe the bug

Some exemples I have found. The biomass reactor doesn't keep it's content when reloading a save, the Powah Cells lose their charge after loading a save and they also don't seem to charge if you don't uplug and replug them.

### Steps to reproduce

1. Plug and charge a powah cell or put some biomass in the biomass generator
2. Save an quit
3. Reload the game
4. Look at the powah cell or biomass generator

### Expected behaviour

The content of these block should be saved on quitting and reloading

**Comment by TheonlyTazz** [comment]
could not replicate




https://user-images.githubusercontent.com/3908847/223050420-ecbc91a3-5dca-4d94-b88b-4a8a5360454b.mp4

**Comment by siconnellym** [comment]
So, after retesting multiple times, the biomass generator doesn't seem to have any problem for me either, so it must have been a coincidence that my generator was empty. 

But the powah cells are definitely not working after a reload and they are losing charge.

https://user-images.githubusercontent.com/39924130/223272527-dbb3a8e6-7e70-4c9a-9310-7c91d4a4a246.mp4
