### ISSUE TITLE
Modular Force Field Systems

### ISSUE THREAD

**Issue by bumv** [FTBTeam/FTB-Modpack-Issues#2797]
### Modpack

FTB Presents Direwolf20 1.19

### Mod suggestion

https://www.reddit.com/r/feedthebeast/comments/11i4nim/modular_force_field_systems_are_making_a_return/
Allows for interesting pvp experience! 
Also a good utility for defense.

**Comment by Saereth** [comment]
Mod is still pretty new, we've requested perms to add it in the future but will give it week or two to look for any major bugs before slapping it in
