### ISSUE TITLE
JAOPCA: Zinc Crystals not being produced

### ISSUE THREAD

**Issue by MCDemon117** [FTBTeam/FTB-Modpack-Issues#2799]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

Version 1.5.0

### Describe the bug

There are Dirty and Clean Zinc Slurreys from the mod JAOPCA, and that mod as far as I know is like an addon towards the mod Mekanism for Ore Processing, but there are no Zinc Crystals, you'll see in the screenshot below, there might be others need to check.

Same said for Silver apparently.

### Steps to reproduce

Just type the word "Zinc" in the search bar in the game and it should show the problem

### Expected behaviour

I inspected the Clean Zinc Slurry to go into the Chemical Crystallizer and make Zinc Crystals, then Chemical Injection to make Shards, then to Purification to make Clumps, then to Crusher to make Dirty Dust, then to Enrichment Chamber to make the Dust and then to the Smelter so it can make ingots.

### Screenshots

![2023-03-06_10 49 30](https://user-images.githubusercontent.com/111976874/223090178-ae23b479-2902-48ac-b116-e9ec2b056631.png)

**Comment by 5ully** [comment]
This sounds like a JAOPCA issue, if they add extra ore slurries ++, they should also add the crystals. Have you reported it to Jaopca too?

**Comment by MCDemon117** [comment]
No, the pack has been known to have a few bugs ever since the release.
