### ISSUE TITLE
[Bug, ReAuth]: Reauthenticator not working, not accepting account/password

### ISSUE THREAD

**Issue by Evalynndewinters** [FTBTeam/FTB-Modpack-Issues#28]
### Modpack

Ftb oceanblock

### Modpack version

1.1.0

### Describe the bug

Reauthenticator not working, not accepting account/password. Can't join multiplayer games anymore. Please fix/remove this.

### Steps to reproduce

go to the reauthenticator.

### Expected behaviour

Removal of reauthenticator or fix.

### Screenshots

![image](https://user-images.githubusercontent.com/60989596/134920138-90beb51f-322f-41f9-b6ba-12e3342ed4b8.png)

**Comment by Sunekaer** [comment]
Hi 

Could you provide any errors?
Mojang or Microsoft account?
If you start the client and don't click the reauth button can you then join a server or what error you get?

**Comment by Raidobw2** [comment]
Very likely that this is a Microsoft account, i had one other user complain about it, but ReAuth states that on their CurseForge page: `It is not yet possible to use Microsoft accounts with ReAuth - If you want to continue using ReAuth please refrain from migrating for now`

You can only use ReAuth with Mojang accounts in its current state.

Does not sound like a bug, but rather a limitation imposed by the new Microsoft accounts. My guess is the mod gets updated with time to support the new login -- if it's possible anyhow.
Hopefully @Evalynndewinters can confirm this for us, that they are using a Microsoft account, or not, then we can close this ticket.

Thank you.

**Comment by falizure** [comment]
this is only going to be a growing issue as more people are forced to convert over, i suggest to switching to oauth, it is up to date and supports microsoft accounts.

**Comment by MichaelHillcox** [comment]
Please note this is not our mod and if this is a mod issue then it'll be down to the mod author to fix, I'll leave this open until @Sunekaer has a second to make a decision on whos issue this is

**Comment by Raidobw2** [comment]
We could report to the author for them to implement it, but otherwise as falizure said we can switch to OAuth if we end up having the choice (https://www.curseforge.com/minecraft/mc-mods/oauth).
Up to Sunekaer to decide on that, but that could "fix" it most likely.

**Comment by Sunekaer** [comment]
Talked to TechnicianLP he is working on implement it.

**Comment by TheonlyTazz** [comment]
This Issue has been fixed
