### ISSUE TITLE
[Suggestion]: Can we have a dragon's breath custom recipe?

### ISSUE THREAD

**Issue by MisterZam** [FTBTeam/FTB-Modpack-Issues#280]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

All of the mycelial generator can be automated except for this halitosis one. It uses dragon's breath and there are no means on automating it. It is a selfish request but i believe most of the people will be happy with the addition

**Comment by Sunekaer** [comment]
Its easy to get a lot of dragon breath and also cant think of a recipe that would make sense.
