### ISSUE TITLE
local multiplayer crashes aswell as startup crashing

### ISSUE THREAD

**Issue by Jaykkemp** [FTBTeam/FTB-Modpack-Issues#2806]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

experiencing multiple crashes whenever i try boot up the modpack. im running with 6 to 7 GB of ram when attempting to load. everything seems to go well then just as the window opens and the mojang loading bar almost fills it crashes. if this doesnt happen then the mod crashes upon attempting to create a single player world or join a multiplayer session.

aswell when attempting to do local multiplayer with a friend after somehow getting the mod to work. opening JEI for crafting recipes causes the host of the world to immediately crash every time. 

### Steps to reproduce

load mod.
play for atleast 10 minutes after joining through minetogether or LAN.
attempt to open a JEI crafting recipe
normally crashes the host

### Expected behaviour

causes the window to not respond then crashes the instance

**Comment by UnRealDinnerbone** [comment]
Please upload a crash log, so we can investigate this issue this is located in crashreports folder in the minecraft instance directory
