### ISSUE TITLE
Direwolf 20 1.19 Version 1.6.0 will not start.

### ISSUE THREAD

**Issue by Jwh1o1** [FTBTeam/FTB-Modpack-Issues#2807]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.6

### Log Files

https://pastebin.com/NKfJTvy8

### Describe the bug

Starting up the game when it finishes loading it shows an error Oh The Biomes You'll GO errors.

### Steps to reproduce

start Direwolf 20 1.19 through the FTB App

### Expected behaviour

It should start the game and load to the minecraft start screen.

### Screenshots

https://prnt.sc/WvLfNY3WGy3Q

**Comment by Likasil** [comment]
Having exact same issue with new update.

**Comment by gvillwrstlr** [comment]
Also happening to me

**Comment by Thorton101** [comment]
Hello,

just wanna say, same error occurs on my singleplayer - instance, after updating and starting the modpack via 
FTB app.
Best regards.

**Comment by MCDemon117** [comment]
I think the EXACT same issue happened with me.

**Comment by Likasil** [comment]
Update seems to have fixed it. :)

**Comment by Jwh1o1** [comment]
I did test out 1.6.1 and it is working just a warning though if you are upgrading from a previous version server it might take a couple of starts to clean up all the old stuff.
