### ISSUE TITLE
FTB One 2.1.0 - Server Not Starting

### ISSUE THREAD

**Issue by J-powers4877** [FTBTeam/FTB-Modpack-Issues#2808]
### Modpack

FTB One

### Modpack version

2.1.0

### Log Files

https://pastebin.com/szerk4gd

### Describe the bug

When attempting to start the server, it would load through for about 30 seconds before hanging.
Upon hanging, the error log above shows "Modular Force Field System (mffs) has failed to load correctly"

### Steps to reproduce

1. Download FTB One 2.1.0 Server File for Windows
2. Run Installer
3. Once installer is complete, run the "start.bat"

### Expected behaviour

Server Runs Properly

**Comment by PentoreXannaci** [comment]
#https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2768#issuecomment-1456882565

they should really change the way they test their modpacks.

**Comment by TehGOOSE** [comment]
> #[#2768 (comment)](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2768#issuecomment-1456882565)
> 
> they should really change the way they test their modpacks.

We volunteer as tribute

**Comment by IceWarden** [comment]
idk if this helps but from the debug log:

`[07Mar2023 12:42:52.410] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: mffs, class dev.su5ed.mffs.MFFSMod`
