### ISSUE TITLE
Failed to start the minecraft server

### ISSUE THREAD

**Issue by PentoreXannaci** [FTBTeam/FTB-Modpack-Issues#2809]
### Modpack

FTB One

### Modpack version

2.10

### Log Files

https://pastebin.com/sypVPf76

### Describe the bug

i updated my server and cant run it anymore.
even crashes on a new server.
see the logs.

### Steps to reproduce

Start the Server.

### Expected behaviour

Server should not crash.

EDIT: 
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2808

he was faster :c

**Comment by Crussade** [comment]
Same here
