### ISSUE TITLE
[Bug]: BlockCarpentry Slabs in Worldgen use Old TileEntity data

### ISSUE THREAD

**Issue by Jkosio23** [FTBTeam/FTB-Modpack-Issues#281]
### Modpack

FTB OceanBlock

### Modpack version

1.5.0

### Describe the bug

The basalt structures with the gold trim in the overworld feature BlockCarpentry slabs, which have been changed from 0.3.6 to 0.4.0 in order to handle doubleslabs. This means the structure generation presumably uses the old tile entities and don't behave as intended.

### Steps to reproduce

1. Launch instance of 1.5.0
2. Turn off Liquid view for the one probe.
3. Find a basalt octahedron
4. Look for invisible blocks.

### Expected behaviour

The slabs should work properly.

**Comment by Raidobw2** [comment]
This happens on a fresh new 1.7.0 game:
![slab](https://user-images.githubusercontent.com/17010632/140877727-b9997a1f-f5f3-42c7-a123-c0b547fa0496.gif)
