### ISSUE TITLE
Stoneblock 3 keeps making it so I cant load my world

### ISSUE THREAD

**Issue by Turtlelover0404** [FTBTeam/FTB-Modpack-Issues#2812]
### Modpack

FTB Stone Block 3

### Modpack version

1.16.1

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10914024/debug.log)
[debug-5.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10914026/debug-5.log.gz)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10914029/console.log)
[2023-03-07-8.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/10914031/2023-03-07-8.log.gz)

### Describe the bug

Whenever I try to load up my world for stoneblock 3 it just stops on loading the world and then crashes after a while. Every time the console says "at java.lang.Thread.run(Unknown Source) [?:?]" as its last command. This has been an issue more than once and I have not been able to find any other posts solving it. 

### Steps to reproduce

1. Go to FTB Launcher and press play on the Stoneblock 3 launcher
2. Once it loads in go to singleplayer and select the world
3. After this it loads for a while and then sits on not responding

### Expected behaviour

I expect that when I click on the world it will load, Im fine with slow loading times, not loading at all is not okay

### Screenshots

![image](https://user-images.githubusercontent.com/47216823/223554793-6394ef87-64a0-44e0-846d-dcab87930fc9.png)
![image](https://user-images.githubusercontent.com/47216823/223554889-3129d538-10c1-4ab8-9b4e-3091987d88cf.png)
![image](https://user-images.githubusercontent.com/47216823/223554923-4ff9c4b7-cf17-40c0-89e1-f2c7a6b3f386.png)

### Additional information

I have had this happen about three times now. The only solution I have found is to delete the world and start again. I have spent too many hours on this world to do that again. Please fix this. I don't know if its a launcher or modpack problem but please

**Comment by DaAnubis** [comment]
did u find a solution?

**Comment by Turtlelover0404** [comment]
idk if its a permanent solution but I went into my config and deleted a file named thermal-server-1.toml.bak because it was not an actual toml file and there was another file that was just thermal-server.toml so I figured it might do something. I figured it was something with the config but I still don't know if it fixed it for sure

**Comment by Korabnick** [comment]
I have the same issue, i can't play the game at all, i even can't create a new world. I tried to delete thermal-server-1.toml.bak, I tried to log in by creating a new instance, but nothing helped, everything stopped during the download. Based on the logs, you can see that the server goes down after finding an error, exactly the same error occurs with me:
"[07Mar2023 16:17:26.817] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot read field "playerMap" because "s" is null"

**Comment by UnRealDinnerbone** [comment]
Looks like there was an issue loading a config file. You can fix this by deleting the config file Mekanism/generators.toml (this file is located in the world folder so that full path would be world/serverconfig/Mekanism/generators.toml) doing this should fix the issue
