### ISSUE TITLE
Creative chemical tank not crafting if cheats are off

### ISSUE THREAD

**Issue by LayraAlixis** [FTBTeam/FTB-Modpack-Issues#2814]
### Modpack

FTB University 1.16

### Modpack version

1.8.0

### Describe the bug

When trying to craft a creative chemical tank it doesn't work
If I try again in a world where cheats are on, it work perfectly

### Steps to reproduce

1. Go to a world with cheats **not** enabled
2. Try to craft a creative chemical tank
3. See that it doesn't work
4. Open to LAN and allow cheats
5. Place the items (Rearange them to have the same as the receip, the add button does not place them right)
6. See that now it work

### Expected behaviour

Craft the creative chemical tank

### Screenshots

Try when cheats are off:
![CheatsOff](https://user-images.githubusercontent.com/43513829/223803558-22f31c95-b178-4eda-b1a7-d9ef3f2a2115.png)

Try when cheats are on:
![CheatsOn](https://user-images.githubusercontent.com/43513829/223803553-6a831635-392d-47a5-8a5d-2b7742c35de6.png)

**Comment by eliphatfs** [comment]
Similar issue here. On a dedicated server and cannot craft creative chemical tank.
![image](https://user-images.githubusercontent.com/23738781/230012745-76e2e98a-731f-4c6c-9e38-29981b3d7858.png)

**Comment by eliphatfs** [comment]
I can say it is an NBT matching issue. By changing the script from these tanks to empty tanks the craft will succeed.

**Comment by UnRealDinnerbone** [comment]
With this packing being old as it. This would require big changes. Going to mark this is not planned
