### ISSUE TITLE
cant interact with block in crazy craft updated

### ISSUE THREAD

**Issue by redgoonraccoon1** [FTBTeam/FTB-Modpack-Issues#2817]
### Modpack

Other...

### Modpack version

0.9.2

### Describe the bug

when loading in to any world in crazy craft updated i cant interact with any block 
cant place any blocks
cant break any block 
cant open any ui's
i dont know what to do to solve this issue

### Steps to reproduce

i dont know how to reproduce this

### Expected behaviour

to be able it interact with blocks

### Additional information

can message me at coppertop#8698 on discord

**Comment by redgoonraccoon1** [comment]
so i found that the issue is the ftb cunks mod 
it no longer recognizes me as the chunk owner

**Comment by Sunekaer** [comment]
Please open an issue with the author of the pack, if its an issue in a FTB Mod please make an issue on [@FTBTeam](https://github.com/FTBTeam/FTB-Mods-Issues)
