### ISSUE TITLE
RFTools Storage Tablet crafting don't consume ingredients

### ISSUE THREAD

**Issue by Snobux** [FTBTeam/FTB-Modpack-Issues#2818]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.22.0

### Describe the bug

When crafting, RFTools Storage Tablet does not consume ingredients.
Lets say, I have 6 gravel in Storage Tablet inventory and I craft 1 flint, it use 3 gravel, but when I close and reopen Storage Tablet, in it's inventory still 6 gravel.
When crafting consume all ingredients in its inventory, then it will consume them. Lets say, I have 3 gravel in inventory, and craft 1 flint, then it uses 3 gravel , and close and reopen Stone Tablet show that the gravel is gone.
Sorry for my english.

### Steps to reproduce

1. Open Storage Tablet
2. Put in 6 gravel in the Storage Tablet inventory (there must be no gravel in the player inventory)
3. Craft 1 flint, using Storage Tablet crafting
4. 3 gravel will remain in the Storage Tablet inventory
5. Close Storage Tablet
6. Open Storage Tablet
7. In the Storage Tablet inventory 6 gravel

### Expected behaviour

consumed 3 gravel

**Comment by UnRealDinnerbone** [comment]
I can confirm this is a mod issue. However, with the pack being as old as it and the mod being on 1.12.2. This won't get fixed
