### ISSUE TITLE
[Bug]: FTB Oceanblock crashes when you click the "Planner" button in a Tinker Station.

### ISSUE THREAD

**Issue by RPMYT** [FTBTeam/FTB-Modpack-Issues#282]
### Modpack

FTB Oceanblock

### Modpack version

1.7.0

### Log Files

https://paste.ee/p/oEx1X

### Describe the bug

When clicking the "Planner" button in a Tinker Station, the game will crash with a `ClassNotFoundException`. I suspect this is a Tinker's bug rather than a pack bug, but I was told to report it here.

### Steps to reproduce

1) Open a Tinker Station
2) Click the "Planner" button
3) Game crashes.

NOTE: I had a Pickaxe recipe in the table at the time - might only happen when there's a valid recipe? Not sure.

### Expected behaviour

No clue what's *supposed* to happen when you click the button, but it's probably not a game crash.

### Additional information

This happened on the Modded Minecraft discord server's Oceanblock server.

**Comment by RPMYT** [comment]
Oh, FWIW, the Pickaxe recipe was entirely wooden.

**Comment by Raidobw2** [comment]
Thanks for the report, we'll manage from here.
Currently active ticket at tiffit/tconplanner#1. First! :p
Awaiting feedback there or mod update.

**Comment by Raidobw2** [comment]
`tconplanner-1.16.5-1.1.1` is now released on CurseForge and available, will currently work with TConstruct `3.2.0.290`
