### ISSUE TITLE
Processing Ores creates dead ingots

### ISSUE THREAD

**Issue by GrandpaAhab** [FTBTeam/FTB-Modpack-Issues#2821]
### Modpack

FTB One

### Modpack version

2.1.1

### Describe the bug

FTB Industrial Contraptions has ingots in it that are incompatible with other mods. The problem is that the modpack force creates the FTB Industrial Contraptions versions of several ingots when smelting. The Tin Ingot and Lead Ingot are the first ones I experienced this with, but there could be many more as I was not able to advance much further without working materials.

### Steps to reproduce

1. Obtain Tin Ore
2. Create Macerator
3. Macerate Tin
4. Smelt Tin Dust
5. See produced ingot

### Expected behaviour

All ingots should be compatible with all mods as their type, or only one ingot type should exist and work with all mods.

**Comment by dsf3449** [comment]
I've run into this issue too, but with nickel.

It works fine when you just smelt raw nickel, but as soon as you start to process it (for example, via a pulverizer) you end up with nickel dust (thermal), _not_ nickel grit (immersive). When you smelt the dust you end up with a dead nickel ingot from thermal. The nickel dust and nickel ingots provided don't even show up in any JEI search.

**Comment by MechBFP** [comment]
This should already be fixed in the current version (2.1.1). If you created these before the update, then you will still have the old ones.

**Comment by dsf3449** [comment]
Actually, just checked on 2.1.1 and the issue I reported with nickel is indeed fixed. Thanks for the info!
