### ISSUE TITLE
Stoneblock 3 Server Crash 

### ISSUE THREAD

**Issue by Dameworth** [FTBTeam/FTB-Modpack-Issues#2822]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

https://pastebin.com/gWj3P9gK
https://pastebin.com/jt7P1sjd

### Describe the bug

The server crashes whenever a certain user logs in, they just started ProjectE.

### Steps to reproduce

N/A

### Expected behaviour

Server immediately crashes when user attempts to login

**Comment by UnRealDinnerbone** [comment]
Same as #2501
