### ISSUE TITLE
Problem with activating Guardian Eye

### ISSUE THREAD

**Issue by SlotherX** [FTBTeam/FTB-Modpack-Issues#2826]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.5.0

### Describe the bug

When throwing inactive guardian eye into a lit structure the soul fire just burns the inactive eye, it doesn't consume the blocks or do anything beside destroying the inactive eye.

### Steps to reproduce

1. Take inactive eye
2. throw into lit structure
3. Watch it getting burned and nothing heppening.

### Expected behaviour

I expected to activite the Guardian eye.

**Comment by TheonlyTazz** [comment]
did u use compressed soul sand?

**Comment by SlotherX** [comment]
You are right, that was the problem thank you!
