### ISSUE TITLE
Lava Chicken Producing No Eggs

### ISSUE THREAD

**Issue by TehGOOSE** [FTBTeam/FTB-Modpack-Issues#2827]
### Modpack

FTB One

### Modpack version

2.1.1

### Describe the bug

Placing a Lava chicken in a roost produces no Lava Eggs

### Steps to reproduce

1. Place Roost
2. Put Lava Chicken in
3. Wait
4. Wait More
5. Get sad
6. Make a bucket and go to nether  :(

### Expected behaviour

Get Lava Egg

### Screenshots

![No Lava Egg](https://user-images.githubusercontent.com/62586077/224459565-7b36f7b7-045e-48bf-b628-26e1b0e73ff8.png)

https://user-images.githubusercontent.com/62586077/224459574-72196e9d-d95d-4749-b610-3400ba5a9854.mp4

2nd "Image" is a short video
### Additional information

In Discord Saereth said this may be a reversion of a previous bug the mod devs previously fixed and would be reporting it to them

Id add the link but I dont see the post yet.

**Comment by Saereth** [comment]
currently a bug with mod yeah, issue is open on their tracker presently
https://github.com/CreeperHost/Chickens/issues/48
