### ISSUE TITLE
Got CrypticEye without DullEye

### ISSUE THREAD

**Issue by taktod** [FTBTeam/FTB-Modpack-Issues#2828]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.5.0

### Describe the bug

Got the cryptic eye cryptically.

### Steps to reproduce

1. make the cage.
2. capture frog.
3. enchant any item.
4. suddenly got the cryptic eye.

### Expected behaviour

enchant dull eye to make cryptic eye.

### Screenshots

![image](https://user-images.githubusercontent.com/614160/224466563-53ee2064-2900-4521-9fb2-3c8d77399d43.png)

**Comment by TheonlyTazz** [comment]
there is a very small chance to get the enchant on any item, turning it into a dull eye... im afraid i cannot change this behaviour however
