### ISSUE TITLE
Converted villagers instantly despawn

### ISSUE THREAD

**Issue by zedstas** [FTBTeam/FTB-Modpack-Issues#2832]
### Modpack

FTB Inferno

### Modpack version

1.5.0; 1.6.1

### Describe the bug

In a room built on the nether roof, just outside the Colony border: (on version 1.5.0)
Summoned 12-15 villagers, converted them (using Ars Rite of Restoration), setup their jobs, did initial trades. 
Log off, back on, all villagers had despawned. 
Now any z.villagers I summon using the table instantly despawn once they convert to a villager. 

### Steps to reproduce

1. while outside colony border (as indicated with the builder's wand) use the summoning table to summon 3 z.villagers.
2. Use Ars Rite of Restoration to convert them to regular villagers. 
3. Watch them instantly despawn. 

### Expected behaviour

Villagers should not despawn.

### Additional information

I upgraded to 1.6.1, same result. 
I've tried to move the room further away from the colony (5 chunks outside the boundary). Same result.
I've removed my tavern, same result.
Note: I'm pre-bellringer in progress, but at colonist cap (25 colonists). 

I did notice one test I got a villager to remain (briefly, until I logged out), and in the log for that play there was a line indicating one of my Colonists had been DISCARDED. 
[11Mar2023 05:30:00.460] [Render thread/WARN] [net.minecraft.world.level.entity.TransientEntitySectionManager/]: Entity EntityCitizen['Minion Kyth'/78, l='ClientLevel', x=196.50, y=128.00, z=5418.80, removed=DISCARDED] wasn't found in section SectionPos{x=12, y=8, z=338} (destroying due to DISCARDED)
(He is my Teacher; he reappeared after logging back in, but the villager was gone). 

Is there any other reason (unrelated to the colony) that would cause villagers to instantly despawn? 
Is the colony cap also a limit on villagers in general? 
What should I do next to try and debug this issue?

**Comment by Saereth** [comment]
I am on 1.6.2 (development build) and I'm unable to reproduce this issue now so hopefully the updated minecolonies resolves this for you, if not please reopen the ticket and provide a latest.log 
![image](https://user-images.githubusercontent.com/9200909/231622360-9d554e82-6696-41d2-b0f7-f64bfa3cc8e5.png)
New update will be out soon

**Comment by zedstas** [comment]
Just tried doing the exact same thing on 1.9.1, with the same results. I've attached the latest.log file and the appropriate "debug" file. 
Here is a screenshot of my map, showing where I'm trying to spawn the villagers in relation to my Minecolony
![2023-05-26_22 07 35](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/115383600/b7c8ab11-1f5a-4329-913d-0f551e3dc420)


Considering how immediately the villagers disappear, I'm curious if there is something like a max count somewhere that isn't being reset. Since it isn't generally reproducible, it is something I've done, but I'm not sure how to reset just that, without losing other progress.
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11580738/latest.log)

[debug-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11580744/debug-2.log.gz)
