### ISSUE TITLE
Graphic bug in some instance

### ISSUE THREAD

**Issue by Nadrik** [FTBTeam/FTB-Modpack-Issues#2834]
### Modpack

FTB Tech World 2

### Modpack version

1.1.6

### Describe the bug

Hi,

Sorry for my english.

I just started to play Tech World 2 and i saw some graphic bugs in the game.
Somes blocs become purple then turn to the right texture when i touch them.
I don't see the breaking animation when hitting a tree, some things like this.

Here is my computer :

-Intel Core i9-11800H
- Windows 11
- Nvidia RTX 3070 

Can you tell me what can I do to stop this bug ?

Thank you.

Nadrik.

### Steps to reproduce

1. Start the instance and see the graphics bugs

### Expected behaviour

I just want to know what to do to clear this problem.

### Screenshots

![bug](https://user-images.githubusercontent.com/127679228/224556509-9b28c600-262a-42c1-98b7-1c19fd2d0a47.png)
![bug 2](https://user-images.githubusercontent.com/127679228/224556511-ffad315e-8cbe-41d6-b69f-52cbf5c03f8b.png)

**Comment by manmaed** [comment]
This i an old mod pack and is unlikely to get updated added @Raidobw2 if he gets time

**Comment by Gaz492** [comment]
Could you try updating your graphics drivers to the very latest version available, this looks similar to a known bug caused by outdated graphics drivers.
