### ISSUE TITLE
Bugreport Stoneblock 3 | "Hellforge Sand" production

### ISSUE THREAD

**Issue by lordsofking** [FTBTeam/FTB-Modpack-Issues#2835]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

if i want to create "Hellforged Sand"(Blood Magic) in the "Fluid Sieving Machine"(Industrial Foregoing) withe the 100mb of "Fermented Ore Meat(Hellforged Sand)(Hellforged Sand)"(Industrial Foregoing) and 1 "Sand"(Vanilla Minecraft) then i get "Iron Grit"(Immersive Engineering).

### Steps to reproduce

1. get a "Fluid Sieving Machine"(Industrial Foregoing)
2. add 100mb of "Fermented Ore Meat(Hellforged Sand)(Hellforged Sand)"(Industrial Foregoing) 
3. add 1 "Sand"(Vanilla Minecraft) 
4. give the machine power
5.  now you get on "Iron Grit"(Immersive Engineering)

### Expected behaviour

get the item in the recipe

### Screenshots

![2023-03-12_17 58 06](https://user-images.githubusercontent.com/15952743/224560071-d30058eb-ae1b-4356-aeb2-394b0fe322de.png)
![2023-03-12_18 00 16](https://user-images.githubusercontent.com/15952743/224560125-5886aada-9d5c-44e7-8ebe-de06f53f7213.png)

**Comment by DinnerBeef** [comment]
Unable to reproduce this is my dev version. When the next version comes out, can you please test this to see if this is still happening.
