### ISSUE TITLE
Certain things arent appearing

### ISSUE THREAD

**Issue by NijaKing8** [FTBTeam/FTB-Modpack-Issues#2837]
### Modpack

FTB University 1.16

### Modpack version

1.8.0

### Describe the bug

Okay so my hands arent showing up, i cant see overlay on blocks like the lines when you look at them, beds are invisible, mobs are invisible, and im invisible if i press f5. oh and i cant break anything

### Steps to reproduce

I dont know how it happened, i joined the world and it was like this

### Expected behaviour

i expected to join like normal

### Screenshots

![2023-03-12_18 39 07](https://user-images.githubusercontent.com/127700380/224581067-9dfd5452-a907-4869-93b9-8b7d031bc134.png)

**Comment by Gaz492** [comment]
Closing the game and starting it up again often fixes this issue; however, it's a rather annoying bug to track down what's causing it so its possible that this bug wont ever be fixed.
