### ISSUE TITLE
Non-Interchangable "Bronze Ingots"

### ISSUE THREAD

**Issue by TehGOOSE** [FTBTeam/FTB-Modpack-Issues#2839]
### Modpack

FTB One

### Modpack version

2.1.1

### Describe the bug

Discovered when trying to craft Mekanism "Armored Jet Pack"
Once again I didnt learn my lesson and tried Crafting Bronze via Thermals Machines:
![Thermal Bronze](https://user-images.githubusercontent.com/62586077/224593036-6263c8f7-5ffb-4ab4-b9e7-abc8b9168393.png)
Which didnt work :(
![No Armored Jet Pack](https://user-images.githubusercontent.com/62586077/224593062-a0dd13fd-6035-4945-aab7-897cb0223006.png)

However when I made the Mekanism Bronze via the Immersive Alloy Smelter:
![Mekanism Bronze](https://user-images.githubusercontent.com/62586077/224593136-dfc8a0de-75ac-4580-90c0-f276b8822d8f.png)
SUCCESS!
![Armored Jet Pack BRONZE](https://user-images.githubusercontent.com/62586077/224593157-499e6836-7cd6-4b14-9d5e-81db0bc1375c.png)

### Steps to reproduce

See Images

### Expected behaviour

Both versions of the ingot to be innerchangable like other materials. 

### Additional information

TRALALA

**Comment by Saereth** [comment]
So these are now fixed that even thermal machines no longer produce those ingots, the solution is to unify them in a compacting drawer or just manually shapecraft to nuggets and back and it'll give you the right kind of ingots. From now on your thermal machines should produce the correct variants as of ftb one 2.2.0
![image](https://user-images.githubusercontent.com/9200909/225130915-9c34d1f5-b1f1-46ba-9c82-c2a849d50736.png)
