### ISSUE TITLE
Curio slot missing texture and localized name

### ISSUE THREAD

**Issue by hatfielddr** [FTBTeam/FTB-Modpack-Issues#2842]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.6.1

### Describe the bug

Curio slot (glasses presumably) is missing a texture and localized name

### Steps to reproduce

Open curios bar and scroll about halfway down to glasses slot

### Expected behaviour

Expected texture and localized name like the other slots

### Screenshots

![2023-03-13_15 58 47](https://user-images.githubusercontent.com/28369760/224827688-bcb93967-91bc-412d-8d5b-cf3f9e6377a1.png)

**Comment by Saereth** [comment]
well I can fix the localization but not the texture. Some mod is misregistering that but its not throwing any errors in the log so im not sure what mod it even is to fix it presently. If anoyne gets more info on this let us know!

**Comment by Saereth** [comment]
https://github.com/SirEndii/AdvancedPeripherals/issues/432

**Comment by SirEndii** [comment]
Since the goggles are disabled in 1.19.x, the curio slot shouldn't even exist...

**Comment by SirEndii** [comment]
Fixed in 1.19.2-0.7.26r
