### ISSUE TITLE
Chickens don't spawn in the nether

### ISSUE THREAD

**Issue by Chelass** [FTBTeam/FTB-Modpack-Issues#2843]
### Modpack

FTB One

### Modpack version

2.1.1

### Describe the bug

Chickens spawn normally in overworld but dont in the Nether both in Servers and Singleplayer.
Chickens mod config file seems to be setup normally

### Steps to reproduce

1. Go to the nether
2. Find no chickens
3. not even if you load the world and then tp them to yourself
4. Cry because no chickens 

### Expected behaviour

to be chickens in the nether

### Additional information

The only difference on the config file from the overwolrd chickens to the Nether chickens is the location of spawning that being Normal for overworld and Hell for the nether, maybe there is conflict between mods?

**Comment by Saereth** [comment]
seems to be a bug with the chickens mod, reporting to them. I was able to reproduce this with vanilla and chicken mods only
