### ISSUE TITLE
FTB Inferno shuts down immediately as singleplayer pressed

### ISSUE THREAD

**Issue by Dziumongs** [FTBTeam/FTB-Modpack-Issues#2847]
### Modpack

FTB Inferno

### Modpack version

1.6.1

### Log Files

https://pastebin.com/WpR5MmXV

### Describe the bug

Have been playing FTB inferno for a while but few days ago cant start game. It loads and turns on, but as i press single player button it shuts down

### Steps to reproduce

Turn on FTB App
Select FTB inferno
Start instance
Press Singleplayer
Game shuts off

### Expected behaviour

Find a way if its modpacks bug or something wrong with my system

**Comment by Saereth** [comment]
This should be fixed in the next update, fancy main menu bug
