### ISSUE TITLE
Wither Storm fight has no end

### ISSUE THREAD

**Issue by rourke750** [FTBTeam/FTB-Modpack-Issues#2848]
### Modpack

FTB Inferno

### Modpack version

1.6.1

### Log Files

https://pste.ch/yupuyodeja.pl

### Describe the bug

Started the Wither storm fight on version 1.5.0.  No portals ever spawned just had to wait for 30 minutes for it to upgrade to a tier 5.  Then a Wither Symbiont spawned and managed to kill it and get the creative book for the fbomb.  Used to fbomb to kill the wither storm first round.  It then resurrected as it was expected but another symbiot never spawned and there was never an opportunity to teleport with an ender pearl into the wither storm.

Additionally it looks like there are 1 wither storm and 2 wither segments but they arent connected, unsure if they are supposed to be or not.

Also tried upgrade from 1.5.0 to 1.6.1 and this did not fix it.  I have afked for hours waiting, no new behavior is occuring.

### Steps to reproduce

Unsure if reproducible.

### Expected behaviour

Be able to beat the wither storm

**Comment by Saereth** [comment]
please edit kubejs/server_scripts/entityhandler.js and at the top there is a line that says
const debug = false;
switch that to
const debug = true;

then load into the fight and let it run for a while and send me your latest.log after that if you can. That should give us the insight we need as to what's broke so I can help get you a fix.

**Comment by rourke750** [comment]
This is from the console (debug and latest.log were missing this stack) https://pste.ch/gadoyubetu.sql

and my latest.log https://pste.ch/pasaqehoyi.sql

**Comment by Saereth** [comment]
Ok this is weird, the portal command is silent failing without any reason just returning 0. Can you manually run the portal command and see what happens? 

the command it's running in the script is 

`/execute in minecraft:overworld run open_gateway 1789 185 1929 gateways:witherstorm_final_gate`

**Comment by rourke750** [comment]
I've tried running:
/open_gateway ~ ~ ~ gateways:witherstorm_final_gate and the witherstorm gate isnt there as an option.

**Comment by Saereth** [comment]
alright this gives me a place to focus my testing, I'll be working on this tomorrow and will get an update to fix it out asap, thanks for sharing your logs

**Comment by csuarezmtz** [comment]
Don't know if useful, but I was able to open the portal by using /witherstormmod consumedEntities set @e[type=witherstormmod:wither_storm,limit=1] 3000000

However I was not able to naturally get to Phase 7 and had to push for it using a command as well ( /witherstormmod phase set @e[type=witherstormmod:wither_storm,limit=1] 7  )

There's a similar command for Phase 5.5 (meaining there's also a ConsumedEntity threshold.
Hope this helps.

**Comment by Saereth** [comment]
I put in a fail safe to prevent this in the next update

**Comment by thegwangster** [comment]
I'm still experiencing this issue today - the wither storm is stuck in the post-formidibomb stage.
I've never seen a witherstorm gateway, which I thought was strange at the time. Looking into it, it seems the witherstorm gateways are not recognized by the command. The gateway config files themselves don't seem to have any issue, so I'm not sure how to proceed other than manually forcing the witherstorm stages by command.
