### ISSUE TITLE
[Suggestion]: Add Mod Simple Sponges

### ISSUE THREAD

**Issue by NecoAngelus** [FTBTeam/FTB-Modpack-Issues#285]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

I love building under Water, Domes and Spheres. But getting rid of the Water in this Pack is a challenge. 
How about the mod Simple Sponges to simplify that

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/simple-sponge

**Comment by Sunekaer** [comment]
Thanks for the suggestion but the mod hasnt been updated for a while, and from reading through it has some bugs and therefore wont be added
