### ISSUE TITLE
Golden furnace crash the server

### ISSUE THREAD

**Issue by Geardung** [FTBTeam/FTB-Modpack-Issues#2851]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

https://pastebin.com/TMVcwbnM

### Describe the bug

My friend open the golden furnace and clicked on redstone options.
The server crashed. When you try to start the server, it starts.
If someone enters on to the server, it crashes

### Steps to reproduce

1. Open the gold furnace
2. Click on the redstone options

### Expected behaviour

Don't crash

**Comment by UnRealDinnerbone** [comment]
Same as #3166
