### ISSUE TITLE
Return from Resource Pack screen crashes game

### ISSUE THREAD

**Issue by Seth0067** [FTBTeam/FTB-Modpack-Issues#2853]
### Modpack

FTB Inferno

### Modpack version

1.5.0

### Log Files

https://pastebin.com/MjiPrR48

### Describe the bug

Returning from resource packs screen to main menu crashes game, once you have attempted to load a pack once.

The packs I have tried this with include Sphax BDCraft for 1.18, which I have loaded successfully in previous version of the game. I have also tried adjusting RAM allocation in case that helps, but this seems to have no impact.

### Steps to reproduce

On a fresh install of both the FTB App and FTB Inferno:

Start the game
On the main menu select "Options..." button
On the Options screen, select "Resource Packs..." button
On the "Select Resource Packs" screen , select a pack and try to load
Select "Done" or ESC to return to Options screen
Result: game will crash at the Mojang load screen
Note: On restart, any time you go to the resource pack select screen, when you ESC or hit "Done" the game will hit the Mojang load screen and then crash, even if you have not loaded anything.

### Expected behaviour

Users should be able to navigate to resource packs screen and return, or load resource packs and return without crashing the game.

**Comment by Saereth** [comment]
Known issue, this is a duplicate issue, problem exists because of hexerei and may never get fixed. You can work around it by disabling hexerei, setting your resource packs then re-enabling it.

**Comment by Seth0067** [comment]
Appreciate the reply. - you might consider posting this in your release notes under "known issues". 

FWIW - tried disabling Hexerei and the game is still crashing in the same manner - super-frustrating as I have been playing the game for months without issue with these same packs before going in and trying a new one and getting crash for first time.

**Comment by Seth0067** [comment]
But...

What does work is to modify the options.txt file directly so the packs load at client start - you may want to let people know?
