### ISSUE TITLE
Cant log into FTB One server

### ISSUE THREAD

**Issue by CptWedge** [FTBTeam/FTB-Modpack-Issues#2854]
### Modpack

FTB One

### Modpack version

2.0.0

### Describe the bug

When trying to log into my FTB One server, I get an error  Internal Exception: java.lang.UnsupportedOperationException: Failed to get registry access. This is a bug.   I can load into a  single player world but not a server.

### Steps to reproduce

By trying to load into a mp server?

### Expected behaviour

I expected to load into a world to play the game

**Comment by Saereth** [comment]
There is an update out for FTB One that resolves this. You'll need to update
