### ISSUE TITLE
Stoneblock 3 Open to friends Crash/Close

### ISSUE THREAD

**Issue by n8sgr8** [FTBTeam/FTB-Modpack-Issues#2855]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11006287/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11006290/latest.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11006291/console.log)

### Describe the bug

Game crashes upon attempting to open singleplayer world to friends

### Steps to reproduce

1. Open world
2. Pause menu
3. Click open to friends
4. Game stops responding, then crashes

### Expected behaviour

Menu opens to the "Open to friends" screen and allows me to open to my minetogether friends

### Additional information

This has only started relatively recently.

**Comment by ChaosPrometheus** [comment]
Yes, I've had these crashes too.

**Comment by RendalTumar** [comment]
Same here been looking for a fix for a while. It seems to happen on most of the modpacks right now.

**Comment by Gerdathlete** [comment]
Same issue here. Its in the same spot as options, so I keep pressing the button when I go to change settings. Either fix the issue or just outright remove the mod.

**Comment by UnRealDinnerbone** [comment]
Minetogther has been updated since, please make a new issue if this is still happening
