### ISSUE TITLE
Server dont start

### ISSUE THREAD

**Issue by officialVoice** [FTBTeam/FTB-Modpack-Issues#2856]
### Modpack

FTB Infinity Evolved Skyblock

### Modpack version

2.0.1

### Log Files

[crash-2023-03-18_15.15.28-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11008881/crash-2023-03-18_15.15.28-server.txt)

### Describe the bug

After starting the server shutsdown, the log file is uploaded :)

### Steps to reproduce

1. Start Server
2. Server Stops with crashreport

### Expected behaviour

Server Shutsdown

**Comment by mariusvn** [comment]
same here with the same errors

**Comment by officialVoice** [comment]
So here is the fix now, the Serverinstaller downloads all the mods even the clientside mods for your game client ( mainmenu design e.g) you need to remove these mods.
Here is an Post which mods are clientsided and need to be removed.
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1554
