### ISSUE TITLE
The initial sky island is always generated in save

### ISSUE THREAD

**Issue by SilveryStar** [FTBTeam/FTB-Modpack-Issues#2857]
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Describe the bug

The initial sky island is always generated in my save

### Steps to reproduce

Start the game normally and enter the save. When the world is loaded, the initial empty island will be generated, and the replaced trophies and items in the container will become drops.

Even if I change my dimension to 144 through the backup save, and then return to the sky island world through psd, the above situation will still happen

### Expected behaviour

The save should load normally

### Screenshots

![G`_ ZI D)IQW4IN~KE2HR{N](https://user-images.githubusercontent.com/42149290/226165554-ba0cdc3b-774a-4a52-98b6-369dc5209c48.png)

**Comment by Gaz492** [comment]
Ive not been able to reproduce this myself, can you confirm this is still an issue for you (if you are still playing the pack)

**Comment by SilveryStar** [comment]
No need, I have already completed this modpack
