### ISSUE TITLE
Can't unbind an Entangled Block

### ISSUE THREAD

**Issue by Lordmau5** [FTBTeam/FTB-Modpack-Issues#2859]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

https://pste.ch/takutogiva.pl

### Describe the bug

Shift-rightclicking an Entangled Block from the Entangled mod should unbind it and additionally display a client message that the block was unbound, as seen here: https://github.com/SuperMartijn642/Entangled/blob/1.18/src/main/java/com/supermartijn642/entangled/EntangledBlock.java#L55

This is however not the case and instead it's throwing an error as can be seen in the pste I've attached

### Steps to reproduce

1. Place down an Entangled Block
2. Shift-Right-click on another block with the Entangled Binder
3. Right-click the Entangled Block
4. Shift-Right-click with an empty hand on the Entangled Block (to unbind it)

### Expected behaviour

The Entangled Block should get unbound

### Additional information

I've replied to the issue in the Entangled repository with a bit more information on where the error seems to occur.
Not entirely sure which mod is causing this though...

**Comment by UnRealDinnerbone** [comment]
Close this issue as the mod issue has been open since March, without any update
