### ISSUE TITLE
[Bug]: Sluice produces chorus plant instead of chorus flower

### ISSUE THREAD

**Issue by RobertBouillon** [FTBTeam/FTB-Modpack-Issues#286]
### Modpack

FTB Ocean Block

### Modpack version

1.5

### Describe the bug

Loot table for crushed endstone in a sluice produces a chorus plant, which has no use in any recuipes. I presume this is meant to be a chorus  flower?

### Steps to reproduce

NA: Loot Table

### Expected behaviour

NA: Loot Table

**Comment by Raidobw2** [comment]
Hmm. Our modpack dev will see if this is fit, maybe it's intended for progression.
![image](https://user-images.githubusercontent.com/17010632/141093416-5cfa691d-abdd-4fc8-84da-4cd658802807.png)
You can however place the plant onto end stone and break it to obtain some chorus fruit.
As long as there is a machine that can place it like the Mechanical Placer or break with Mechnical Miner, it's technically automatable.
![chorus_plant](https://user-images.githubusercontent.com/17010632/141093431-c7fa10f3-63e5-4dc7-870b-770142651403.gif)
