### ISSUE TITLE
Sky Block single color - no actual sky block

### ISSUE THREAD

**Issue by Natervater** [FTBTeam/FTB-Modpack-Issues#2860]
### Modpack

FTB StoneBlock 3

### Modpack version

1.5.0

### Describe the bug

WHen using the Literal Sky block, Sky Block, there is no sky texture, its a flat gray blueish color. See screenshot: https://www.screencast.com/t/vfQqrF8dvJfj

### Steps to reproduce

1. Craft Sky Block
2. Create ceiling from Sky Block
3. See its a flat grey color
4. say ugh
5. troubleshoot graphic settings
6. hope to God the smarter people on Github know whats wrong and can enlighten me

### Expected behaviour

Sky block creates a sky as the name suggests

### Screenshots

https://www.screencast.com/t/vfQqrF8dvJfj

**Comment by Sunekaer** [comment]
This is actually how the sky looks in this dim.. :)
