### ISSUE TITLE
SSN inventory crash (new update)

### ISSUE THREAD

**Issue by Magnus8377** [FTBTeam/FTB-Modpack-Issues#2862]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.11.0

### Log Files

[crash-2023-03-19_21.03.58-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11012285/crash-2023-03-19_21.03.58-client.txt)

### Describe the bug

When opening SSN inventory the game crash

### Steps to reproduce

Open SSN inventory 

### Expected behaviour

That the inventory would open I could get my items

### Screenshots

Sorry 

### Additional information

yeah, the items are offset then i SSN inventory

**Comment by Gaz492** [comment]
Just wanted to check, did you add any mods to the pack or did you mark this as the wrong modpack?
