### ISSUE TITLE
upgrade for chests and barrels

### ISSUE THREAD

**Issue by ChristianZeolla** [FTBTeam/FTB-Modpack-Issues#2864]
### Modpack

FTB Legend of the Eyes

### Mod suggestion

onto the reinforced-chest-2.2.0+1.19 
there is a lack of upgrade for tier up chest and barrell without brake them, like for the iron-chest mod.
from my point of view is a huge improvment for the quality life of the actual gameplay.
thanks for the beautiful job that you are doind on this modpack

**Comment by TheonlyTazz** [comment]
unfortunatly the developer never added these functions to the Reinforced Chests. If you would like this to be added, its best to suggest this at the Mod's [Github](https://github.com/Aton-Kish/reinforced-chests)
