### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ShadowBado** [FTBTeam/FTB-Modpack-Issues#2865]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Hi I need help When I go into the modpack there is always a voice that tells me what I'm doing right now and it's very annoying and I don't know how to do it Help

**Comment by Lela810** [comment]
Go into Options -> Accessibility Settings -> Disable Narrator (Top Left)
The Narrator reads you every option on screen, as the name implies.

**Comment by ShadowBado** [comment]
Thank you for your help
