### ISSUE TITLE
Netherite chicken can be smelted in a furnace, even though netherite is supposed to be fireproof.

### ISSUE THREAD

**Issue by Thexus** [FTBTeam/FTB-Modpack-Issues#2866]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

Netherite is supposed is be fireproof. Even jet fuel can't melt netherite. From the wiki: "Netherite is a material resistant to fire and lava". Being able to smelt netherite chickens is a huge plothole. Pls fix. Ty.

### Steps to reproduce

1, Get a netherite chicken
2, Put it in a furnace
3, Cover your ears so that you can't hear its scream.
4, Now you have a delicious cooked chicken

### Expected behaviour

This shouldn't happen.

### Screenshots

https://cdn.discordapp.com/attachments/160402646115549184/1087802299960787004/image.png

**Comment by UnRealDinnerbone** [comment]
Not an issue as you're supposed to be able to smelt any Chicken into cooked chicken (including lava)
