### ISSUE TITLE
Oceanblock Crashing 

### ISSUE THREAD

**Issue by aololstopper** [FTBTeam/FTB-Modpack-Issues#2867]
### Modpack

FTB OceanBlock

### Modpack version

1.15.1

### Log Files

[hs_err_pid18676.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11035287/hs_err_pid18676.log)

### Describe the bug

It crashed when I type U in the RS storage system
### Steps to reproduce

Open RS system or RFtool Storage module
Type U
Crashes

### Expected behaviour

The client crashed and boot my back to the FTB launcher

**Comment by MichaelHillcox** [comment]
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40
