### ISSUE TITLE
Instance crash upon connecting to server

### ISSUE THREAD

**Issue by aleeexe** [FTBTeam/FTB-Modpack-Issues#2869]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

https://pastebin.com/sAuUbBRV

### Describe the bug

Playing on friends server, suddenly my instance crashed and I can no longer login on the server. Upon connecting to the server it crashes. 

### Steps to reproduce

cant reproduce 

### Expected behaviour

Able to connect to server 

### Additional information

This has happened once before, we fixed it by deleting my profile from the server. But I want to see if there are any other fixes before doing it again since I will lose all my items and progress.

**Comment by Gaz492** [comment]
It looks like this was caused by a rendering error, possibly from Mekanism, is this still an issue with the latest version of the pack?
