### ISSUE TITLE
[Suggestion]: Flame Lily Botany Pot?

### ISSUE THREAD

**Issue by Jkosio23** [FTBTeam/FTB-Modpack-Issues#287]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

Basically the same thing as #44  but for Flame Lily the https://github.com/OneLemonyBoi/MiniUtilities/blob/main/src/main/java/onelemonyboi/miniutilities/blocks/FlameLily.java Flame Lily

**Comment by lslinnet** [comment]
@Sunekaer the Netherrack soil for the Flame Lily is set to 1.0 growth factor while it should likely have been 0.0
The 1.0 Growth factor prevents it from growing.

**Comment by Sly-Phox** [comment]
Not sure if this was fixed. Repeatedly had the same issue, see screenshot


![2021-11-26_16 16 04](https://user-images.githubusercontent.com/95108149/143660633-68846283-2fdd-4be9-b08d-d2129e0dd913.png)

**Comment by Sly-Phox** [comment]
Pretty sure this wasn't implemented properly. Using the latest version, I repeatedly ran into this issue (see screenshot)

![2021-11-26_16 17 20](https://user-images.githubusercontent.com/95108149/143660681-31e4c17a-b784-4c8d-88f2-f99e3304dc16.png)
