### ISSUE TITLE
The Wither in the shields tutorial destroys the room because it's projectiles can't be contained

### ISSUE THREAD

**Issue by ninjachicken1** [FTBTeam/FTB-Modpack-Issues#2871]
### Modpack

FTB University 1.16

### Modpack version

1.8.0

### Describe the bug

See the title. Attempting this tutorial can result in:

1. Player death
2. The floor getting destroyed, meaning you can't reach the exit button
3. The exit button getting destroyed
4. SCP CONTAINMENT BREACH (The Shield Projector getting destroyed so you're stuck fighting the Wither without weapons or armour. This is what normally happens)
5. A combination of 3 & 4, but instead of killing you the wither just leaves through the hole where the button was. With no means of escape, you're left to wonder if maybe you were the real monster all along as you wait for the end of your days.

If you claim the chunks in the room, this avoids all issues except the first, except now you've used up some of the chunks you could claim, and if you forget before you leave you can't easily unclaim them. Everything outside of this paragraph leaves the chunks unclaimed.

It's notable that by using creative mode to stand on the roof directly above the wither before it could take damage and waiting there the entire time (with creative mode disabled), then as long as it doesn't blow up the projector it can't hit the ceiling directly above it. This makes the ceiling the only safe place I can tell to put the projector.

Most of the destruction could be avoided by using Wither-Proof blocks. Options in this pack include Rebar Concrete Blocks, Kryonite and Compact Machine Walls (the unbreakable kind).

Everything else in the tutorial can be kept safe by putting it above the chamber apart from the hoppers and item pipes. You could safely collect the star from above using a Krate with a Collector Upgrade.

By applying this you should be able to make this school safe to use with the chunks unclaimed.

### Steps to reproduce

1. Type /school enter ftbuniversity:rftools/shields
2. Make sure the chunks are unclaimed
3. Pull the lever
4. ???
5. PROFIT

### Expected behaviour

I bring new (un)life into this world purely to watch it suffer and die while I sit back in complete safety

### Screenshots

A typical summoning attempt:
![2023-03-15_08 59 31](https://user-images.githubusercontent.com/3670136/227028954-39f73ae5-573d-40ed-a753-19797c8ed28f.png)

 The aftermath of Scenario 5
![2023-03-15_09 00 06](https://user-images.githubusercontent.com/3670136/227029228-e6afbb0e-4697-4b15-9427-1e752c3af8b1.png)

My copy of what you made, except on a ceiling in a compact machine. No Krate, because I couldn't be bothered to strip logs, but I was able to unclaim the chunk and run it safely. If I wasn't in early game I'd swap out the dirt for wither-proof blocks, just in case.
![2023-03-22_20 27 28](https://user-images.githubusercontent.com/3670136/227032377-fdd5f3ea-c2a2-494b-8090-df04f02291f4.png)

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
