### ISSUE TITLE
Travel Anchors vanish when trying to teleport

### ISSUE THREAD

**Issue by Lela810** [FTBTeam/FTB-Modpack-Issues#2873]
### Modpack

FTB One

### Modpack version

2.3.0

### Log Files

Log Files do not Write any Entry when trying to teleport

### Describe the bug

When trying to Teleport either using the Staff or the Travel Anchors, every travel anchor becomes invisible.
Teleporting still works, but without any sort of interface or GUI

### Steps to reproduce

1. Place 2 Travel Anchors an name them Something
2. Try teleporting with either
-> Teleporting Works, UI doesn't

### Expected behaviour

Be able to see the names of the Travel Anchors when trying to teleport

### Screenshots

![2023-03-24_15 43 27](https://user-images.githubusercontent.com/71135175/227557290-3dd144bc-cf81-435b-9042-49046e364c0e.png)
![2023-03-24_15 43 33](https://user-images.githubusercontent.com/71135175/227557331-2ab6c069-2e5f-4521-8a8a-a3e6ec89a939.png)
![2023-03-24_15 43 40](https://user-images.githubusercontent.com/71135175/227557356-6731cb26-9fcb-442a-8110-37c8da279e28.png)

**Comment by Saereth** [comment]
this is an issue with the renders from temp pad that also breaking the glowing effect, waiting for an update from them to fix it
