### ISSUE TITLE
SB3 - Create's "Nugget of Experience" needs automation

### ISSUE THREAD

**Issue by SaphireLattice** [FTBTeam/FTB-Modpack-Issues#2875]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Create helpfully provides a lot of Experience Nuggets that can be used by the player to redeem XP equivalent-ish to smelting things yourself. The issue is that there's a LOT of these produced, yet there's no good way to actually use them other than manually.

This really begs for some (or multiple?) ways to convert such a nugget into liquid XP from other mods, as otherwise it just sits there without use.

I know that voiding it is an option, but it's a bit silly to do with such an amount of resources.

Not sure what is the average (if it's not completely fixed) of experience you get from a nugget though, might need to check Create's code for that.

**Comment by UnRealDinnerbone** [comment]
You can use the Deployer from create to turn the Experience Nuggets into xp entities
