### ISSUE TITLE
WHY does the crafting of ME Glass cables require Fluix Dust?!?!?!?!

### ISSUE THREAD

**Issue by Furious1964** [FTBTeam/FTB-Modpack-Issues#2877]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

Trying to craft Fluix ME Glass Cables and the recipes are correct but every time I start to craft them, Refined Storage won't because it's missing Fluix Dust?!?! I've tried several methods to solve this and it won't. Can you guys PLEASE fix this!!!

### Steps to reproduce

1. Make recipes of items
2. Craft items
3. Get Nothing.

### Expected behaviour

I expected it to work.

### Screenshots

![2023-03-26_11 38 36](https://user-images.githubusercontent.com/2803725/227787136-e7fca15a-7798-404c-b6dc-00d038961fd3.png)
![2023-03-26_11 38 39](https://user-images.githubusercontent.com/2803725/227787140-5ca33bd6-8496-448e-bd95-6fbb3a209f62.png)
![2023-03-26_11 38 59](https://user-images.githubusercontent.com/2803725/227787146-b0983a17-6d37-46a5-9092-d6ec85fde3f9.png)

### Additional information

I'll have to cheat them in if I can't solve this or it doesn't get fixed. I'm doing nothing wrong with the recipes and everything should be working fine. Also, I'm making the Fluix Crystals in an Enrichment Chamber. Also also, added Extra Storage because I found that a room full of Crafters Daisy-chained together is just insane.

**Comment by electricsteve** [comment]
because its trying to craft the fluix crystal

**Comment by Furious1964** [comment]
D'OH!!!! Didn't see that....another Homer Moment.
