### ISSUE TITLE
constant overloading of the ram

### ISSUE THREAD

**Issue by daimajin1708** [FTBTeam/FTB-Modpack-Issues#2878]
### Modpack

FTB Infinity Evolved 1.7

### Modpack version

3.1.0

### Log Files

I don't know where to upload the launching log

### Describe the bug

After loading into the world, my RAM (I am currently at 11 GB RAM, started with 7 GB) minecraft constantly loads up to 77/78 percent then freezes for a second and begins filling the ram from 0 back to 77/78 percent again. This happens constantly and how much RAM i allocate does not matter (haven't tried allocating more than 11 GB, because I always was playing with 8GB RAM allocated).

### Steps to reproduce

1. Download the modpack
2. start it up
3. (install Sphax x64 resource pack for vanilla and ftb infinity)
4. open a new biomes o' plenty world

### Expected behaviour

this game constantly freezes every 1.5 seconds

**Comment by Elcar0** [comment]
Having the same issue. Sometimes everything is okay, but then the game crashes out of nowhere and after relaunching FPS is significantly reduced and my RAM does the same thing as Daimajin1708 reported above. I've tried switching to Red Hat Java and launching without Optifine. Neither has solved it.

Other people on the same server don't seem to experience this issue. Increasing or decreasing RAM seems to only slightly increase or decrease the time between lag spikes, but given that they happen every 1-3 seconds anyways it doesn't really make a difference.

The crash report says the reason for crashing is java.lang.IllegalStateException: Already tesselating!

If any logs or reports are required I'm willing to send them.
