### ISSUE TITLE
[Bug]: conflicting Black glass recipes

### ISSUE THREAD

**Issue by gamesineed** [FTBTeam/FTB-Modpack-Issues#288]
### Modpack

FTB Oceanblock

### Modpack version

1.7.0

### Describe the bug

Mini Utilities "Dark Glass" and Macaw`s Windows "Black Mosaic Glass" have the same recipes.

Look at the pictures

![2021-11-09_22 37 03](https://user-images.githubusercontent.com/94018844/141010800-85e74c45-958c-4cde-a47f-5e17b50f58b9.png)

![2021-11-09_22 37 11](https://user-images.githubusercontent.com/94018844/141010812-746a49c1-3dfd-4771-ac0e-0658f7e50211.png)

### Steps to reproduce

First try to craft "Dark Glass" from Mini Utilities and you get Black Mosaic Glass from Macaw`s Windows.

### Expected behaviour

Be able to craft Dark Glass from Mini Utilities

### Screenshots

![2021-11-09_22 37 03](https://user-images.githubusercontent.com/94018844/141010800-85e74c45-958c-4cde-a47f-5e17b50f58b9.png)

![2021-11-09_22 37 11](https://user-images.githubusercontent.com/94018844/141010812-746a49c1-3dfd-4771-ac0e-0658f7e50211.png)

**Comment by Sunekaer** [comment]
What the heck, worked in my instance... guess we'll change it again.
