### ISSUE TITLE
server can't keep up on start and crashes

### ISSUE THREAD

**Issue by adam110902** [FTBTeam/FTB-Modpack-Issues#2887]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

[crash-2023-03-30_18.56.09-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11114075/crash-2023-03-30_18.56.09-server.txt)
[crash-2023-03-30_18.43.21-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11114076/crash-2023-03-30_18.43.21-server.txt)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11114088/latest.log)

### Describe the bug

when loading at some point it starts reporting "server can't kep up" with incresing delay until it crashes, it run without any problems before

### Steps to reproduce

1 start server
2 wait
3 see "server can't keep up"
4 the server crashes after a bit more time passes

### Expected behaviour

no crash

**Comment by UnRealDinnerbone** [comment]
Same as #2501
