### ISSUE TITLE
It Shall Not Tick Deprecated

### ISSUE THREAD

**Issue by Provello** [FTBTeam/FTB-Modpack-Issues#2888]
### Modpack

FTB Presents Direwolf20 1.19

### Is your suggestion related to a problem? Please describe.

https://www.curseforge.com/minecraft/mc-mods/it-shall-not-tick

Suggested removal

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/it-shall-not-tick

**Comment by Saereth** [comment]
yeah this is true, will get it out for next update
