### ISSUE TITLE
JEI crashes the pack

### ISSUE THREAD

**Issue by Allelyfie** [FTBTeam/FTB-Modpack-Issues#2889]
### Modpack

FTB Interactions

### Modpack version

2.12.1 

### Describe the bug

I used JEI to search up recipes, and after a few searches, it froze and crashed my game. I tried to reopen the world, and it worked fine until I opened my inventory again.

### Steps to reproduce

1. Go into the JEI menu
2. Search for "Me" (last thing i saw while it was frozen)
3. Crash

### Expected behaviour

I expected it to not crash

**Comment by Gaz492** [comment]
Would you be able to upload a crash report so we can take a look at this?
https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

We may have something up our sleeves, some may call it a remaster, keep an eye out on our social media platforms for more information.
