### ISSUE TITLE
[Bug]: O crash Landing carrega normal no launcher mas assim que vai mudar a tela para o jogo ele fecha sozinho e volta para o FTB!!!

### ISSUE THREAD

**Issue by veroncarlos** [FTBTeam/FTB-Modpack-Issues#289]
### Modpack

CRASH LANDING

### Modpack version

1.1.3

### Describe the bug

ele fecha sozinho assim que carrega o launcher!

### Steps to reproduce

baixem o crash landing, apertem jogar, ai ele abrira o launcher do minecraft normal mas assim que carregar para entra para tela do jogo ele fechara sozinho.

### Expected behaviour

Eu esperava que ele entrasse no jogo normal!

**Comment by Raidobw2** [comment]
Hello. Adicione este mod em sua pasta de mods, ele permitirá que você use o Java 8 e inicie o modpack: https://dist.creeper.host/sheep/mods/legacyjavafixer-1.0.jar. Se você ainda tiver problemas, use o aplicativo CurseForge para jogar este modpack.

Tenha um bom dia!
