### ISSUE TITLE
Mod Pack Crashes upon World load with Oculus mod installed.

### ISSUE THREAD

**Issue by Ticskter** [FTBTeam/FTB-Modpack-Issues#2893]
### Modpack

FTB One

### Modpack version

FTB One 2.3.0

### Log Files

[crash-2023-04-02_11.49.31-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11132675/crash-2023-04-02_11.49.31-client.txt)

### Describe the bug

 Ive added a few mods that prefer i to use over ones that already exist such as Journey map, and a mod that works with the Rubidium mods called Oculus to use shaders.

However, when i have the oculus-mc1.19.2-1.2.8.jar installed, Minecraft loads fine, i select a world to load and the llittle world loading square completes and says 100% and then goes to a "joining world" text screen and sits there for a minute and then crashes.

this only happens when the oculus-mc1.19.2-1.2.8.jar is installed.

### Steps to reproduce

1. Install oculus-mc1.19.2-1.2.8
2. attempt to load world

### Expected behaviour

world loads and the abulity to use shaders

**Comment by MechBFP** [comment]
I am using Oculus and Rubidium no problem with this modpack. Did you install the mods though the FTB launcher?

**Comment by Ticskter** [comment]
no i did not install from the FTB launcher.

**Comment by MechBFP** [comment]
Give that a try, it works just fine when using the versions the launcher provides.

**Comment by Saereth** [comment]
I can't reproduce this seems to be working fine with oculus via the ftbapp
