### ISSUE TITLE
Client Crashes when trying to upgrade apotheotic equipment

### ISSUE THREAD

**Issue by GrandpaAhab** [FTBTeam/FTB-Modpack-Issues#2895]
### Modpack

FTB One

### Modpack version

2.3.0

### Describe the bug

When I placed my apotheotic iron sword from Apotheosis into the Forge Table, it crashed once I added the diamond as the new resource. It specifically crashed once I put the diamond stack down after putting one diamond in.

### Steps to reproduce

1. Get Apotheotic Boss Iron Sword
2. Place Iron Sword in Forge Table
3. Place Diamond in Second slot of Forge Table
4. Put down stack of remaining diamonds elsewhere
5. Witness Crash

### Expected behaviour

Upgrade the iron sword to a diamond sword

**Comment by MechBFP** [comment]
I have a similar problem if I try to use a Smiting Table with an enchanted book on those swords the game crashes. Using an Anvil however works just fine.

**Comment by Saereth** [comment]
new placebo and apoth update should fix this in 2.4.0 out soon
