### ISSUE TITLE
[Bug]: Tasks not showing

### ISSUE THREAD

**Issue by nusretagayani** [FTBTeam/FTB-Modpack-Issues#2896]
### Mod

FTB Academy 1.16

### Mod version

FTB Academy 1.16

### Forge / Fabric version

1.16.5

### Modpack & version

FTB Academy 1.16

### What issue are you having?

I set up the FTB Academy 1.16 server to play with my friend. Everything works fine, but when I open the task book, none of the tasks appear, why is this happening?

photo:

https://www.hizliresim.com/2ho9bn4

### Crashlogs

its not crash

### Steps to reproduce

no

### Anything else to note?

no

**Comment by manmaed** [comment]
Please update to 1.4.0 and see if this issue has been fixed
