### ISSUE TITLE
[Crash Report]: Not compatible and cannot use earlier version

### ISSUE THREAD

**Issue by Zeusto** [FTBTeam/FTB-Modpack-Issues#2897]
### Mod

Applied energistics

### Mod version

Appliedenergistics2-rv3-beta-6.jar

### Forge / Fabric version

1.7.10

### Modpack & version

FTB Skyfactory 2.5.8

### What issue are you having?

The game crashes when trying to load Appliedenergistics2-rv3-beta-6.jar because it is not compatible with Ender IO. It says to try Appliedenergistics2-rv2 instead. But when I try this, the game says "Appliedenergistics2 is missing" or "You need Appliedenergistics2 version rv3 or above.

### Crashlogs

[crash-2023-04-03_14.49.19-client.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/11138560/crash-2023-04-03_14.49.19-client.txt)

### Steps to reproduce

Well it is a crash not a bug.

### Anything else to note?

It happened randomly without me touching any game files.

**Comment by manmaed** [comment]
This is an old mod pack and is unlikely to receive an update
