### ISSUE TITLE
Stone block 3 not working/ FTB

### ISSUE THREAD

**Issue by Christianpugia** [FTBTeam/FTB-Modpack-Issues#2898]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.6.1

### Log Files

ac289526-a362-4bfb-b831-27872dc8caec

### Describe the bug

Hey i started playing stoneblock 3 and now when i try to load my world it instantly crashes. I have tried allocating different amounts of ram and nothing works so its not a memory issue.

### Steps to reproduce

no damn clue help thats why i made this. Why does ftb have no support for their users. trash company.

### Expected behaviour

crash game

### Additional information

Make a way for customers to contact you guys and get help. Its insane you have no support at all.

**Comment by Sunekaer** [comment]
Stone block 3 or FTB Legend of the Eyes? 
You selected FTB Legend of the Eyes by say SB3.
Please attach a crash log
