### ISSUE TITLE
[Bug]: FTB University 1.16 Quests

### ISSUE THREAD

**Issue by zoller27osu** [FTBTeam/FTB-Modpack-Issues#290]
### Modpack

FTB University 1.16

### Modpack version

1.3.0

### Describe the bug

1. [Optional] quests must still be completed for the chapter to be counted as completed and for the chapter trophy to be obtained
2. The "unique" bow enchantments in university.uniqueruneenchants.task3 (Multishot and all levels of Quick Charge) are vanilla Crossbow enchantments and the mod does not allow you to apply them to Bows, so these enchants do not belong in this quest.
3. The other runes (on the Unique Rune Enchants and Aura quests) sometimes don't complete, based on other NBT data that may be on the runes (specifically, they can sometimes come with a grey name, NBT of that shown below). Optimally the quests would ignore all NBT fields not specified in the quest metadata? (As a workaround, deleting the extra NBT tags with NBTEdit makes the quests work fine.)
4. The Wireless Universal Terminal cannot actually be crafted with the current version of https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals-forge, so the quest should be marked Optional at the very least. (If you give yourself one with Creative and add the "crafting: true" and "pattern: true" NBT tags, everything does seem to work - so maybe when you complete the other Wireless Terminal quests, it could just give you one as a reward?)
5. Please make the quest to get Morgan in Mahou Tsukai optional lol, not everyone is ok with killing their own tamed dog.

### Steps to reproduce

1. Go to Woot chapter
2. Complete all quests except the Exotics one (which, btw, there is no proof that https://github.com/Ipsis/Woot/issues/530 is actually fixed [i.e. Exotics are probably not practically obtainable])
3. Note that the trophy quest does not complete

### Expected behaviour

The trophy quest should be complete when all non-Optional quests are completed

### Screenshots
1:
![2021-11-10_20 18 54](https://user-images.githubusercontent.com/12834978/141236272-3181aea1-9472-4d56-8882-2ba93770d9b0.png)
3:
![RuneName](https://user-images.githubusercontent.com/12834978/141235742-59e9a2c7-f348-4303-9a58-6bb9d52c1186.PNG)

**Comment by Raidobw2** [comment]
P.S. I think you're reporting this for University, not Academy.

**Comment by zoller27osu** [comment]
oops, embarassing. yes, University.

**Comment by aaronhowser1** [comment]
For woot: FTBTeam/FTB-Mods-Issues/issues/123

For bow enchants: whoops! Removed from next version

For the NBT thing: I could not replicate this, a freshly crafted Bouncy rune only had the enchantment in the NBT, and completed the task

Removed the Universal Terminal quest, and made Morgan optional

**Comment by zoller27osu** [comment]
@aaronhowser1 it seems random whether the special colored name happens or not. thing is, if it does happen, the ONLY way to make the quest accept the items is to edit their NBT. Renaming them in the Anvil gives equally wrong NBT, while there seems to be no way to restore the item's default name.

**Comment by aaronhowser1** [comment]
The quest version of the item has the NBT `{Enchantments:[{lvl:1s,id:"mana-and-artifice:bouncing"}]}`. A freshly crafted rune has that NBT. I don't know where you got the colored NBT stuff.
