### ISSUE TITLE
FTB Skies Video Settings Menu

### ISSUE THREAD

**Issue by DMJaxun** [FTBTeam/FTB-Modpack-Issues#2902]
### Modpack

FTB Skies

### Modpack version

1.00

### Describe the bug

Video settings menu buttons overlap on the top right

### Steps to reproduce

Go to video settings in FTB Skies.

### Expected behaviour

Buttons should be spaced and not overlap

### Screenshots

![image](https://user-images.githubusercontent.com/66274985/229901015-6875df17-1fe3-446a-9235-66bfc08152a6.png)

**Comment by MichaelHillcox** [comment]
Looks like there is no way for us to prevent this. We're going to reach out to the mod author and see what they can do about it. For now, if you just press the little x to the right of the text. This should be resolved.

**Comment by TexBlock** [comment]
TRO [mc1.19.x-1.0.5](https://www.curseforge.com/minecraft/mc-mods/textrues-rubidium-options/files/4507672) fixed this issues.

**Comment by MichaelHillcox** [comment]
@Saereth
