### ISSUE TITLE
skies lobby

### ISSUE THREAD

**Issue by DiggityMan420** [FTBTeam/FTB-Modpack-Issues#2904]
### Modpack

FTB Skies

### Modpack version

1.0 beta

### Describe the bug

not putting me in lobby and can't /ftb-dim lobby says there isnt one

### Steps to reproduce

new world 
enter
falling over and over from 0,0,0

### Expected behaviour

enter to lobby

**Comment by DiggityMan420** [comment]
this i sthe firts time it started me in water after about 10 new worlds SS below [https://ibb.co/XVr3JHK](SS)

**Comment by KaizenNeko** [comment]
Similar issue. But I did get a lobby, but it spawned in partially underwater in an ocean. Seed was 2212471310477345437
![2023-04-04_19 34 44](https://user-images.githubusercontent.com/1039807/229945505-ad8e7b93-5f65-4a68-a362-3a90c17f737c.png)
![2023-04-04_19 39 25](https://user-images.githubusercontent.com/1039807/229945704-31874faa-e6b3-4ab2-8ace-3ef62d7e173b.png)

**Comment by DiggityMan420** [comment]
fixed
