### ISSUE TITLE
Skies Lobby in Ocean Biome

### ISSUE THREAD

**Issue by jnthnjns** [FTBTeam/FTB-Modpack-Issues#2908]
### Modpack

FTB Skies

### Modpack version

1.0

### Describe the bug

Lobby boat is under water in Deep Ocean Biome. Seed: 

### Steps to reproduce

1. Create new world with seed 6409716233231461529

### Expected behaviour

No water above, on, or in lobby boat

### Screenshots

![2023-04-04_20 53 59](https://user-images.githubusercontent.com/339960/229954205-849a53df-06b8-45a5-b486-a34cf83c32e9.png)

![2023-04-04_20 54 15](https://user-images.githubusercontent.com/339960/229954218-1481c4a2-9363-4524-9d24-579bc35ac450.png)

**Comment by dittymargoo** [comment]
Same thing happened to me on my first try, I got the ability bottle etc, but could not get the portal to work even after choosing a world type.  So I created another game, everything seemed fine, portal worked, but no ability bottle this time.

**Comment by dittymargoo** [comment]
Here's my pic too
![2023-04-05_15 46 13](https://user-images.githubusercontent.com/55962902/229996877-35afbe87-5137-49fd-a48b-6990a559ef7d.png)

**Comment by MichaelHillcox** [comment]
Hi all, thank you for the reports, we know of this issue and are working on finding a good solution to resolve it. We should have an update today / tomorrow. For now, if you want to fix this, create a new world :+1:

**Comment by Saereth** [comment]
For now if don't cycle through the world types before you create it seems to prevent this. Recreating your world without doing that is the workaround until we get in an official fix.

**Comment by Saereth** [comment]
The new update should prevent any more worlds from bring created like this
