### ISSUE TITLE
[Suggestion]: Replace the abandoned BetterEnd Forge with BetterEnd Reforked in FTB OceanBlock to resolve major rendering issues with Magnesium

### ISSUE THREAD

**Issue by JeffBittle** [FTBTeam/FTB-Modpack-Issues#291]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

When adding the Magnesium renderer replacement mod to greatly improve Minecraft performance, there are massive rendering issues that make the game unplayable.  Looking into the issue, it was found that these issues are a result of a conflict with the BetterEnd Forge mod, which the mod author apparently had to walk away from.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked

BetterEnd Reforked is a forked continuation of the BetterEnd Forge mod, which is up to date and has already fixed the incompatibility with the Magnesium renderer mod.

**Comment by banece** [comment]
+1 on this, Reforked version works much better, as I tried in my own instance of the game. Forge version gave me transparent world. [Screenshot](https://i.imgur.com/mkpZZbz.png) 
Quoting developer of reforked version of the mod: `Beethoven, The lead Developer of BetterEnd (Forge) is no longer in contact with the original team. This means that, Vemerion is left to work on it alone with little time.`

**Comment by Sunekaer** [comment]
This wont happen in the next update, as we´ll have to do a bunch of testing and such before just swapping mods out.

**Comment by JeffBittle** [comment]
Fair enough, although it's worth noting that Better End Reforked didn't even change the file name, the file name of the mod is still betterendforge-1.16.5, just with a much newer version number.  I'm not sure if there are any recipes or quest triggers or anything that specifically reference things in the Better End mod, but I'm kind of curious if just swapping the Reforked version in right now works or not.

**Comment by sarim** [comment]
> betterendforge-1.16.5, just with a much newer version number

On the top of my head  (So I might be totally wrong) AFAIR betterend forge is probably better end fabric's 0.5 version's port. Reforked is 0.9 version's fork. Something like that, the version jump is pretty significant with new blocks added.

**Comment by jvgoch** [comment]
I've been running it for a little while on my OceanBlock 1.15.1 server and so far I haven't experienced any issues. And the extra performance from Ribidium (which is why I switched to BetterEnd Reforked) are very nice!
