### ISSUE TITLE
Laggy when in inventory 

### ISSUE THREAD

**Issue by YTPinkCherry** [FTBTeam/FTB-Modpack-Issues#2911]
### Modpack

FTB Skies

### Modpack version

1.0

### Describe the bug

Usally i get like 100-120 fps but it drops to like 20 or below when either in inventory or quest book and takes a long time to get the frames back

### Steps to reproduce

load into world 
open inventory 
then boom, lag

### Expected behaviour

To not be laggy since i have a decent pc

**Comment by MichaelHillcox** [comment]
Could you attach a screenshot?

**Comment by Saereth** [comment]
knowing which video settings you're using and your hardware specs would be useful as well. Some users have reported turning mipmaps to 0 helped alleviate this, thanks for letting us know
