### ISSUE TITLE
Build Tool Crash

### ISSUE THREAD

**Issue by TobiDoes** [FTBTeam/FTB-Modpack-Issues#2912]
### Modpack

FTB Inferno

### Modpack version

1.6.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11157587/latest.log)

### Describe the bug

Anytime I try to open the infrastructure Blueprints in the Build Tool in the game it crashes (so far only on Servers)

### Steps to reproduce

Open the Build Tool and change to infrastructure and the game will crash (so far only on Servers)

### Expected behaviour

be able to place Roads (or see if their available)

**Comment by Saereth** [comment]
This should be resolved with the new updated (1.6.2) if this happens again please provide a crash log and i'll follow up with the minecolonies devs. Thanks!
