### ISSUE TITLE
Launcher does not start

### ISSUE THREAD

**Issue by xx1982xx38** [FTBTeam/FTB-Modpack-Issues#2913]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Describe the bug

If I want to start the launcher or the modpack, it tries to validate data but then breaks off and outputs an error message. You can see the error message in the picture I attached.

### Steps to reproduce

Modpack uninstalled and reinstalled. error persists

### Expected behaviour

Request for suggestions on how to fix the error

### Screenshots

![Screenshot 2023-04-05 135430](https://user-images.githubusercontent.com/106419701/230074243-012b5f04-78cd-4043-90e4-79962d41e23c.png)

**Comment by Saereth** [comment]
As this isn't a pack specific issue, please followup with the issue regarding this on our FTB App bug tracker. You can find the issue here, sounds like what you're experiencing.
https://github.com/FTBTeam/FTB-App/issues/832
