### ISSUE TITLE
[Bug]: Mysterious RF-loss With Energy Battery

### ISSUE THREAD

**Issue by Ceru6479** [FTBTeam/FTB-Modpack-Issues#2915]
### Mod

IntegratedDynamics

### Mod version

IntegratedDynamics-1.19.2-1.16.2

### Forge / Fabric version

43.2.6 (Forge)

### Modpack & version

FTB Skies - 1.0.0

### What issue are you having?

The Energy Battery drains RF for no reason. Initially I thought this was an overflow error related to Iron Jetpacks when equipped in a Curios slot, but after testing with RF-items from 3 different mods (Redstone Arsenal, Industrial Foregoing Tools, & Iron Jetpacks) and getting no conclusive results, I'm not sure what's causing this issue.

https://user-images.githubusercontent.com/116467020/230026805-a5b9700b-efe3-47f6-88da-205227b115d9.mp4

### Steps to reproduce

Hold SHIFT and right-click with the Energy Battery from IntegratedDynamics. Might be related to holding an energy-dependent item that's full or inaccessible to the Energy Battery.

### Anything else to note?

1.0.0 is a beta-version so errors like this are expected, mod conflicts too.
I did this twice due to Github disallowing files above a certain size, but results are consistent.
This might be an IronJetpacks-sided issue too.
Edited to clarify version

**Comment by manmaed** [comment]
can you update to version 1.2.1 and see if this issue has been fixed?
