### ISSUE TITLE
[FTB Skies] Pedestals and FTB Hammers dont work together

### ISSUE THREAD

**Issue by DasBrain** [FTBTeam/FTB-Modpack-Issues#2916]
### Modpack

FTB Skies

### Modpack version

Beta 1.0.0

### Log Files

_Not applicable_

### Describe the bug

1. A Pedestal with Material Generator Upgrade breaks the generated block with the tool provided.
2. Sand, when broken with a FTB Skyblock Additions Hammer yields Dust.
3. A Hammer inserted into a Pedestal generating Sand produces... Sand.

### Steps to reproduce

1. Place a Pedestal on Chiseled Sandstone
2. Put a Material Generator Upgrade into the Pedestal
3. Put a FTB Skyblock Additions Hammer into the Pedestal
4. Observe that the Pedestal produces Sand

### Expected behaviour

Pedestal produces Dust

### Screenshots

![2023-04-05_16 30 34](https://user-images.githubusercontent.com/652983/230115040-6c7315b6-b1ed-4e1e-8ce4-e14ab62340ef.png)

**Comment by Saereth** [comment]
This is not a bug, the pedestal only accepts certain types of tools and the hammer is a unique tool. We can ask the mod dev to add special handling for the hammer but beyond that this isnt a pack specific issue. I'll contact the dev and see what he says though, thanks for the report!
