### ISSUE TITLE
Quest Reward

### ISSUE THREAD

**Issue by gonjat** [FTBTeam/FTB-Modpack-Issues#2917]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Describe the bug

I created a lapidary dynamo, went to the thermal section of FTB quests, clicked on the 32 coal reward only to be given a choice reward list that is empty. Red "!" to indicate a reward wont go away since reward cant be claimed.

### Steps to reproduce

1. Create Lapidary Dynamo and place in inventory.
2. Go to Thermal quest tab
3. click the Dynamo button
4. Click the 23 coal reward icon
5. Be shown a choice reward list that is empty resulting in not being able to claim the reward.
Even the button to claim all rewards shows an empty rewards list.

### Expected behaviour

Click the 32 coal to get the reward or a proper choice reward list.

**Comment by Saereth** [comment]
update your pack
