### ISSUE TITLE
Light Rendering Glitch

### ISSUE THREAD

**Issue by MildManeredMan** [FTBTeam/FTB-Modpack-Issues#2918]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.7.0

### Describe the bug

When mining a stone block a shadow is left on the right side of the block of the remaining block. There seems to be an update issue with the rendering engine. I have included a couple of screenshots to explain it better. Placing a light source on or near the block does not trigger an update. 

### Steps to reproduce

Open a new world and mine a 1x3 tunnel down through stone and the bottom block on the left side will be shadowed, no matter the light source on or near the block. 

### Expected behaviour

When mining through stone the shadowed surfaces should be removed once a light source is place near or on the block. 

### Screenshots

![2023-04-05_16 13 00](https://user-images.githubusercontent.com/129975495/230133263-245bf15d-a0a9-43ac-ab03-8c36927900e3.png)
![2023-04-05_16 13 22](https://user-images.githubusercontent.com/129975495/230133271-11f6bd3f-0d9b-4dea-84ab-6d93a2f03d2a.png)
![2023-04-05_16 13 25](https://user-images.githubusercontent.com/129975495/230133279-6466394b-f343-4770-a1b5-2c205f35b7de.png)

### Additional information

Graphic settings within the game are:
Graphics: Fancy
Chunk Builder: Threaded
Smooth Lighting: Maximum
VSync: On
Mipmap Levels: 1
Render Distance: 12 Chunks
Simulation Distance: 12 Chunks

**Comment by MildManeredMan** [comment]
Does anyone have a suggestion to resolve this? It's not game-breaking, but quite irksome. I've tried rubidium 0.6.2a as I know Optifine is not recommended but this causes the instance to crash before loading.

**Comment by Saereth** [comment]
this is actually forge vanilla lightning behavior for 1.19, confirmed in a test instance 
![2023-04-13_08 31 43](https://user-images.githubusercontent.com/9200909/231810236-214195dc-f2bd-448e-b6fe-38f6656fda43.png)

You might change config/forge-client.toml 
```
	experimentalForgeLightPipelineEnabled = false
```
to true and see if you like that behavior better but we wont ship that on by default for this pack as it can cause other rendering issues
