### ISSUE TITLE
Majority of in-game sounds not playing

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#2919]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Describe the bug

After leaving a client idling on a server over night, the majority of in-game sounds (player/mob damage, block breaking, climbing ladders, opening chests/barrels etc.) as well as the background music either no longer plays or plays at a barely audible volume level.

The client's running Linux so it may be an OS-specific bug.

Relaunching gets sound back to normal for a time.

Logs show a lot of sound engine errors:

```
($) francis@beef.core.destinatech:~/.ftba/instances/d50b5b99-155d-4162-a66d-943bc694eda8/logs
>>> (for z in *.gz; do zcat $z; done; cat console.log) |grep -i 'sound.*error' |tail -n5
[17:02:33] [Sound engine/ERROR] [mojang/OpenAlUtil]: Stop: Invalid parameter parameter value.
[17:02:33] [Sound engine/ERROR] [mojang/OpenAlUtil]: Stop: Invalid parameter parameter value.
[17:03:24] [Sound engine/ERROR] [mojang/OpenAlUtil]: Allocate new source: Invalid parameter parameter value.
[17:03:24] [Sound engine/ERROR] [mojang/OpenAlUtil]: Stop: Invalid parameter parameter value.
[17:03:24] [Sound engine/ERROR] [mojang/OpenAlUtil]: Stop: Invalid parameter parameter value.

($) francis@beef.core.destinatech:~/.ftba/instances/d50b5b99-155d-4162-a66d-943bc694eda8/logs
>>> (for z in *.gz; do zcat $z; done; cat console.log) |grep -ci 'sound.*error'
630698
```

Full [latest.log](https://pste.ch/uqayuqajuf.md) and [debug.log](https://pste.ch/eyizudesif.md) in case they're useful.

### Steps to reproduce

1. Idle for a period
2. Interact with blocks/entities
3. Rinse and repeat until most sounds gone/inaudible

### Expected behaviour

Stable sound

**Comment by Saereth** [comment]
can you try disabling the mod extreme sound mufflers and see if the issue persists?

**Comment by ukmcplyr** [comment]
Bingo :smile:

I'll leave this client idling for a bit longer just in case, but there're no tell-tale sound errors on join with ESM removed.

**Comment by HitaloM** [comment]
I'm also having this same problem and am using Windows 11, so it's really not a Linux-specific problem.

**Comment by Saereth** [comment]
> I'm also having this same problem and am using Windows 11, so it's really not a Linux-specific problem.

can you also try disabling the extreme sound muffler mod?

**Comment by HitaloM** [comment]
> > I'm also having this same problem and am using Windows 11, so it's really not a Linux-specific problem.
> 
> can you also try disabling the extreme sound muffler mod?

I will try this when I get back to the game, my logs are really full of OpenAL errors and this must be what is making my FPS very unstable.

**Comment by FishOutOfH20** [comment]
I disabled the muffler mod (a shame).  It solved the sound issues for me.  Hopefully you can find a solution which will allow us to use the muffler

**Comment by HitaloM** [comment]
> I disabled the muffler mod (a shame).  It solved the sound issues for me.  Hopefully you can find a solution which will allow us to use the muffler
> 

The same here, I also disabled and had no more OpenAL errors.
