### ISSUE TITLE
[Bug]: OceanBlock fails to load 2 mods

### ISSUE THREAD

**Issue by iGamerTrip** [FTBTeam/FTB-Modpack-Issues#292]
### Modpack

FTB OceanBlock

### Modpack version

1.7.0

### Log Files

https://paste.feed-the-beast.com/view/d5f35f68

### Describe the bug

the Modpack says it fails to load 2 mods upon launch, but doesnt tell me _what_ they are

### Steps to reproduce

1. Launch the game
2. 2 mods fail to load

### Expected behaviour

uh, run?

### Screenshots

![unknown](https://user-images.githubusercontent.com/42869384/141073464-b743a839-1c00-4348-9c64-bf9c2035e801.png)

### Additional information

im using MultiMC and Java 16.0.2 with ~6.5GB of RAM allocated to it, Windows 10 21H1, everything _should_ be up to date afaik

**Comment by JeffBittle** [comment]
This is actually a known issue with Minecraft versions below 1.17 and Java versions above 15, which have disabled Reflection by default.  I believe the only real fix is to add a line to Java's Command Line Arguments that reads: `--add-opens java.base/java.lang=ALL-UNNAMED`  This should basically enable the Reflection that Minecraft expects for that instance of Java and allow Minecraft to load normally.

**Comment by iGamerTrip** [comment]
> 
> 
> This is actually a known issue with Minecraft versions below 1.17 and Java versions above 15, which have disabled Reflection by default. I believe the only real fix is to add a line to Java's Command Line Arguments that reads:
> 
> `--add-opens java.base/java.lang=ALL-UNNAMED`
> 
> This should basically enable the Reflection that Minecraft expects for that instance of Java and allow Minecraft to load normally.

that fixes it, thanks
