### ISSUE TITLE
FTB App not starting any Modpack

### ISSUE THREAD

**Issue by Wallbreaker93** [FTBTeam/FTB-Modpack-Issues#2920]
### Modpack

All

### Modpack version

n

### Log Files

No Logs

### Describe the bug

Modpacks dont start at all, no Debug code given, nor log

### Steps to reproduce

1. Starting modpack
2. Launching Error Occurs
3. Modpack doesnt start

### Expected behaviour

1. Starting modpack
2. Modpack launches/gives exit or debug code
### Screenshots

![image](https://user-images.githubusercontent.com/129981249/230144064-cdd11b19-d7d0-443e-96e5-7ec4ab264747.png)

### Additional information

A few weeks ago this error didnt occur, I changed to a custom built pc

**Comment by manmaed** [comment]
Hello this sounds like and app issue please run the below tool and report that and this to https://github.com/FTBTeam/FTB-App/issues
Please use the link below to download and run the FTB Debug tool. This tool will provide you a code that you can give to the support team which they can use to support your issue more specifically. The code will look like FTB-DBGAOIDOSDII. If you are unsure on how to use this tool, please [follow this guide](https://go.ftb.team/ftbdbg-support).

Download Me
Windows
[ftb-debug.exe](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe)
MacOS
[ftb-debug-macos](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos)
Linux
[ftb-debug-linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux)
Windows (Arm)
[ftb-debug-arm64.exe](https://dist.creeper.host/tools/ftb-debug/ftb-debug-arm64.exe)
MacOS (Arm)
[ftb-debug-macos-arm64](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos-arm64)
Linux (Arm)
[ftb-debug-linux-arm](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux-arm)
