### ISSUE TITLE
Spawn boat filled with water

### ISSUE THREAD

**Issue by PeytonNagle** [FTBTeam/FTB-Modpack-Issues#2921]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Describe the bug

Spawn island filled with water in river biome.

### Steps to reproduce

Create new world where spawn island is in river biome. May be the same for something like an ocean biome.

### Expected behaviour

Spawn in water, inside of boat filled/covered with water

**Comment by Saereth** [comment]
duplicate https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2908
