### ISSUE TITLE
An error whilst launching

### ISSUE THREAD

**Issue by AUTColdMilk** [FTBTeam/FTB-Modpack-Issues#2922]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Describe the bug

I only get at start the following Error message:
[https://i.imgur.com/HoLseJh.png](url)

### Steps to reproduce

1. Start FTB
2. Install FTB Skies
3. Start FTB Skies

### Expected behaviour

I expected that the game starts.

### Screenshots

https://i.imgur.com/HoLseJh.png

**Comment by Saereth** [comment]
Please followup on your issue by providing more information on this ticket please
https://github.com/FTBTeam/FTB-App/issues/832
