### ISSUE TITLE
FTB Skies Server

### ISSUE THREAD

**Issue by elokaynu** [FTBTeam/FTB-Modpack-Issues#2923]
### Modpack

FTB Skies

### Modpack version

1.0

### Describe the bug

Server installed fine, loaded, but when I went through the portal it crashes and gives the reason as Reset, now I can't log back in.

### Steps to reproduce

Log in
Go to Portal
Go through portal
Crash

### Expected behaviour

Spawn into new Sky Block

**Comment by Saereth** [comment]
Need some crash logs and/or latest.log and debug.log files please

**Comment by elokaynu** [comment]
Weird Issue has resolved it self. Did a server restart and a world purge and that seems to have fixed it.
