### ISSUE TITLE
Connection lost on using Cyclic's sleeping mat

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#2924]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Describe the bug

Attempting to sleep at night using Cyclic's sleeping bag consistently kicks the client from the server. Not tested single player.

### Steps to reproduce

On a server:
1. At night, attempt to sleep with sleeping bag

### Expected behaviour

No disconnection, successful kip

### Screenshots

![Screenshot](https://gcdnb.pbrd.co/images/GfeTvK3S1Wh5.png?o=1)

**Comment by Saereth** [comment]
can you please provide your latest.log so I can get with the cyclic dev on this?  Thanks

**Comment by ukmcplyr** [comment]
Oops. Half asleep, apologies.

[Client latest.log](https://pste.ch/nibanemati.md)
[Server latest.log](https://pste.ch/ebagupapib.sql)

**Comment by manmaed** [comment]
i feel this is fixed if not open new issue
