### ISSUE TITLE
Other players items in my backpack from Sophisticated Backpacks

### ISSUE THREAD

**Issue by orwashams** [FTBTeam/FTB-Modpack-Issues#2925]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Describe the bug

While playing on a server, I got surprised that my backpack had this much loot in it, turns out its another player's loot.
The issue in recurring every time I login to the server.
I tested it twice as you can see in the pictures below.
I'm also playing on the Chosen island if that helps

### Steps to reproduce

1. Get a friend on a server
2. Fill one player's backpack (from Sophisticated Backpacks) with random stuff, and the other leave empty.
3. Open the second player's backpack and the items you put in the first player's backpack might be there.

### Expected behaviour

To open my backpack and not find other's items in it.

### Screenshots

![2](https://user-images.githubusercontent.com/124343754/230172606-828f1e91-6af7-4b92-8a87-d3c613fd3ffe.png)
![1](https://user-images.githubusercontent.com/124343754/230172615-29628a85-50cc-4230-8254-dad757ed70fc.png)

**Comment by orwashams** [comment]
Update: Thanks to a player on the server we might have cracked the issue, since there's backpack on the Chosen island, it might be have the same ID across every Chosen island, which explains the item sharing between them.

**Comment by JustAnotherGhostName** [comment]
Can confirm this outlines the issue. If two players create an island using chosen architects design, the two backpacks spawn with the same UUID.

**Comment by Saereth** [comment]
Where is this backpack? I thought he replaced it with a shulker box

**Comment by ShadowMagnus000** [comment]
its inside the shulker box

**Comment by Saereth** [comment]
> its inside the shulker box

lol ok I'll switch that for something else, thanks for the report

**Comment by JustAnotherGhostName** [comment]
I would recommend if a backpack is still desired, to just add the materials to craft the backpack. That way players can still get one early on.

**Comment by Saereth** [comment]
fixed in dev
