### ISSUE TITLE
FTB presents crackpack file corrupt

### ISSUE THREAD

**Issue by Jordondaarkz** [FTBTeam/FTB-Modpack-Issues#2926]
### Modpack

FTB Presents Crackpack

### Modpack version

1.1.0

### Describe the bug

i was starting my own server with some friends and found that the FTBinstall.bat doesn't install the file right.
for ex. the minectaft_server.1.7.10.jar that it installs is corrupt

### Steps to reproduce

install the server file
Run FTBinstall.bat

### Expected behaviour

 that the file is not corrupt

**Comment by Gaz492** [comment]
This issue should be resolved now
