### ISSUE TITLE
Adding some form of Aircrafts 

### ISSUE THREAD

**Issue by Traverse-Joe** [FTBTeam/FTB-Modpack-Issues#2927]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

With the vast amount of exploration with the sky islands and villages I would love other methods to explore and with the sky style I feel airships makes a lot of sense.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/viescraft-airships

This mod has airship that can be configured to run on fuel or power(FE) (if that feature was implemented)

**Comment by Saereth** [comment]
I had this originally but based on player feed back it was basically never used in favor of the other flight options in the pack like magic brooms/jetpacks unfortunately. As the pack is already quite large we had to make some calls on which mods to add or not. Personally I enjoy that mod quite a bit.
