### ISSUE TITLE
quest progress reset

### ISSUE THREAD

**Issue by ainz9989** [FTBTeam/FTB-Modpack-Issues#2928]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

played the modpack 2 days ago and when I entered the game to play again today all my quest progress was reset (singleplayer)

### Steps to reproduce

1. complete some quests
2. save and quit
3. start game again and check quests

### Expected behaviour

quest progress not being reset

**Comment by UnRealDinnerbone** [comment]
Unable to reproduce this if you have the logs from that time or are able to reproduce the issue, please reopen the issue with the logs files
