### ISSUE TITLE
[Bug] Uppers do not insert more than 64 items into a drawer, unless you manually add more than 64.

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#2929]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Log Files

No specific logs associated.

### Describe the bug

When you place an Upper below a drawer (In our case, we tested with a default oak drawer from functional storage), and you have items in the upper, it will not insert items into the drawer once it reaches 64 of that item. Once you add more than 64 of that item manually, it will continue filling. 

This does not occur with a vanilla hopper, just the uppers. 

### Steps to reproduce

1. Place a drawer
2. Place an upper below the drawer
3. Place 64 of an item the drawer, and 1 or more of the same item in the upper
4. Observe that the item count in the drawer does not increase

### Expected behaviour

uppers should fill drawers past 64 items

### Screenshots

![2023-04-05_15 22 43](https://user-images.githubusercontent.com/122759195/230183668-9ad71519-a9d2-42c0-ae26-63b717571944.png)
![2023-04-05_15 23 00](https://user-images.githubusercontent.com/122759195/230183710-98a90a9c-85ab-4296-86f4-1aeaaac595dd.png)

**Comment by Saereth** [comment]
reported to mod dev
https://github.com/vadis365/Uppers/issues/15

**Comment by manmaed** [comment]
Still Issue 1.3.1

**Comment by Saereth** [comment]
this has been reported to the dev and its been quite a while so im gonna close this, if they update the mod we'll update the pack with it but nothing else we can do on our end
