### ISSUE TITLE
[Bug] Create Sifters break audio when they are actively sifting

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#2930]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Log Files

No logs associated.

### Describe the bug

When you have multiple sifters from "Create Sifter" sifting blocks, the in game audio breaks and becomes stuttery. As you move away, the audio gets fixed. This issue affects other in game sounds

### Steps to reproduce

1. Setup multiple create sifters
2. Feed them with items
3. Turn on audio
4. Listen to stutters in the audio
5. Observe that other sounds no longer work properly

### Expected behaviour

The audio to not be broken and not break other sounds nearby.

**Comment by Saereth** [comment]
can you see if this occurs for you with extreme sound muffler mod disabled

**Comment by KillSavage** [comment]
I had the cutting in and out out audio bug, I didn't know what caused it but disabling extreme muffler seems to be working for me . thank you

**Comment by JustAnotherGhostName** [comment]
Thank you for testing it, I haven't had the time to get to this issue due
to investigating other more critical issues reported.

**Comment by KillSavage** [comment]
https://youtu.be/w2IFz4vPkrc  The issue i had is in this video. The bug doesn't occur when you start playing, it come as i continue playing. For me it's like 3 hours later. Anyway the solution worked for me. ty
