### ISSUE TITLE
[Mod Suggestions] Observable & NoChatReports

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#2931]
### Modpack

FTB Skies

### Mod suggestion

Observable: 
Allows you to get a visualization of how much lag a tile entity is causing, and allows for better isolation to diagnose the issue. So far this pack seems very optimized, but its still a useful thing to have.
https://www.curseforge.com/minecraft/mc-mods/observable

No Chat Reports:
Prevents plays from being able to report each other in chat to get their Minecraft account banned. If you are hosting a private server, this should be up to the server administration, and it prevents false reports. 
https://www.curseforge.com/minecraft/mc-mods/no-chat-reports

**Comment by Saereth** [comment]
Observable was giving too many false positives so we pulled it. If you'd like it you can add it yourself with no issue of course. We do include both spark and crush utilities to help diagnose issues currently. 

As for the no chat report thing... I personally am all for using it but it's something we really have made a decision on internally at ftb so we'll have to discuss it soon. Of course server owners are free to add it for now.

**Comment by JustAnotherGhostName** [comment]
Fair points. Might I ask what kind of false positives were observed? I would like to make sure I dont fall for those pit falls if they occur.

**Comment by Saereth** [comment]
Mostly just red herrings where people would think they identified lag sources because they see a pipe ticking higher than anything else when the actual underlying tps issue was something completely else.
