### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Hazflem** [FTBTeam/FTB-Modpack-Issues#2937]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Log Files

[crash-2023-04-06_12.34.42-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11165809/crash-2023-04-06_12.34.42-client.txt)

### Describe the bug

Launching client on FTB app and crashed i attached the report

### Steps to reproduce

I just launched FTB app FTB skies

### Expected behaviour

Launch

**Comment by Saereth** [comment]
Forge is unable to write the new config because its open else where/the file is locked
```
Caused by: java.nio.file.FileSystemException: C:\Users\harry\AppData\Local\.ftba\instances\8903f226-2983-4fb4-8e50-bd44389c1166\config\chiselsandbits-client.toml: The process cannot access the file because it is being used by another process
```

This is not a pack issue, but an os/file locking issue. You can resolve this with a restart/reinstall. Feel free to reopen if that doens't resolve your issue (it should)
