### ISSUE TITLE
Nuclear Grenade exploding an advanced turtle causing a server and single player game crash

### ISSUE THREAD

**Issue by TheMostPurifiedOfWaters** [FTBTeam/FTB-Modpack-Issues#2941]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

[crash-2023-04-06_04.14.18-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11166698/crash-2023-04-06_04.14.18-server.txt)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11166699/latest.log)

### Describe the bug

When Throwing a Nuclear Grenade from Thermal Series (https://ftb.fandom.com/wiki/Thermal_Series) at an advanced turtle the game crashes. Video of the bug-(https://www.youtube.com/watch?v=EiUM6o9o3EI&ab_channel=MikeR) 

### Steps to reproduce

1. Pull a Nuclear Grenade Out of Rei.
2. Throw the Nuclear Grenade near (I don't know if it 100% works if it hits directly) an Advanced Turtle by [ComputerCraft](https://ftbwiki.org/ComputerCraft).
3. Game Should crash.

### Expected behaviour

Turtle Blows up with no game crash? idk

**Comment by UnRealDinnerbone** [comment]
This mod issue has been fixed
