### ISSUE TITLE
Pedestals not planting

### ISSUE THREAD

**Issue by vl0fast** [FTBTeam/FTB-Modpack-Issues#2944]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Describe the bug

Making a setup to farm some crops using the pedestals, the fertilizer and the harvester both work, but the planter isnt working properly. I have one planter doing fine with flax seeds, but trying to make another with potatos/carrots/cabbages isnt planting anything, I used a word area card not sure that the issue

### Steps to reproduce

1. Have a crop field
2. give the planter pedestal the work area (Tried both 1 block above the tilled dirt and on the same lvl as the dirt too)
3. give it seeds
4. Nothing happens

### Expected behaviour

I expect it to start planting the seeds I gave to it

**Comment by Saereth** [comment]
please take a screenshot showing your work area
