### ISSUE TITLE
Add Modular Routers

### ISSUE THREAD

**Issue by Brndnrphl** [FTBTeam/FTB-Modpack-Issues#2945]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

So from what i currently see when playing the pack, it seems like that there isn't any form of wireless item transfer, so i think modular routers would work great. Though some of it modules might overlap with cyclic's blocks but i think modular routers does it better and more compact.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/modular-routers

**Comment by Saereth** [comment]
There are plenty of wireless transfer options in the pack. Cyclic item node, ender chests, pedestals, create ender transmission, mekanism entangleporters, ars portals etc. That being said modular routers is lightweight and a good mod so I added for the next update
