### ISSUE TITLE
[Crash] FTB Skies - Ad Astra Mod loading error has occurred

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#2946]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Log Files

https://gist.github.com/JustAnotherGhostName/881c43ef02b7e4d9f60c4ef843cf18e1

### Describe the bug

Crash at startup, mod loading error. 

### Steps to reproduce

1. Start server
2. Crash (Doesn't happen every time. Just this one off)

### Expected behaviour

Server dosnt crash

**Comment by Saereth** [comment]
report to ad astra devs
https://github.com/terrarium-earth/Ad-Astra/issues/266
