### ISSUE TITLE
Add A Flawless Budding Certus Quartz Recipe

### ISSUE THREAD

**Issue by Brndnrphl** [FTBTeam/FTB-Modpack-Issues#2947]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

So i've been playing this pack for a bit and wanted to get into ae2. I Checked out the quests and i saw it recommended me to make a budding certus quartz but i saw that the flawless version doesn't have a recipe, this wouldn't be a problem if it wasn't a skyblock. So im assuming that meteors don't generate here and that means there's no way of obtaining the flawless version of the budding certus quartz, so if players want a renewable source of certus quartz, they'd have to sieve for it or go through the trouble of automating the process of making a flawed budding certus. So by making the flawless version obtainable it would improve QOL a bit i think.

**Comment by shikyo13** [comment]
The existing recipe returns a chiseled quartz block for me instead of the flawless budding certus.
