### ISSUE TITLE
Add Bigger Reactors or other forms of high power generation

### ISSUE THREAD

**Issue by Brndnrphl** [FTBTeam/FTB-Modpack-Issues#2948]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

So from what i see in the quest book, the only source of late-endgame power generation seems to be mek's fusion reactor. I think it kinda sucks there's only one option so i figured that bigger reactors would be a good addition.

**Comment by Saereth** [comment]
You can also use the mycellial generator top tier which is competitive with mek fission
