### ISSUE TITLE
Refined Storage Addons

### ISSUE THREAD

**Issue by StormCountTwo** [FTBTeam/FTB-Modpack-Issues#2949]
### Modpack

FTB Skies

### Mod suggestion

Would like this mod to be added as it adds the Wireless Crafting Grid for Refined Storage, which doesn't exist in default RS

https://www.curseforge.com/minecraft/mc-mods/refined-storage-addons

**Comment by Saereth** [comment]
There is a universal wireless grid for it, check jei for recipe
