### ISSUE TITLE
[Bug]: Cannot craft Enderium Ingot from Ender Pearl Dust

### ISSUE THREAD

**Issue by ogmacwinux** [FTBTeam/FTB-Modpack-Issues#295]
### Modpack

FTB OceanBlock

### Modpack version

1.7.0

### Describe the bug

Related to #2 which has been fixed but somehow it has returned?

One of the recipe components of Enderium Ingot is Mini Utilities' Ender Dust which as per JEI can only be obtained through the IF Fluid Sieving mechanic from BetterEnd Forge's Ender Ore.
Grinding Ender Pearls using Mekanism's Crusher or Thermal's Pulverizer results into Ender Pearl Dust which cannot be used in Enderium Ingot crafting.

Issue as per #2 is due to tags; looking at their tags in-game we have the ff.:

- **Ender Dust** -  `forge:dusts/ender`
- **Ender Pearl Dust** - `forge:dusts/ender_pearl`

Current content of `kubejs/server_scripts/resources/unify.js`:

```
    event.replaceInput("appliedenergistics2:ender_dust", "#forge:dusts/ender");
    event.replaceInput("miniutilities:ender_dust", "#forge:dusts/ender");
    event.replaceInput("thermal:ender_pearl_dust", "#forge:dusts/ender");
    event.replaceOutput("miniutilities:ender_dust", "thermal:ender_pearl_dust");
    event.replaceOutput("appliedenergistics2:ender_dust", "thermal:ender_pearl_dust");
```

### Steps to reproduce

1. Make a Creative test world.
2. Grind Ender Pearls using a Pulverizer.
3. Try to craft Enderium Ingot using an Induction Smelter.

### Expected behaviour

Be able to use Ender Pearl Dusts in Enderium Ingot crafting

### Screenshots

![2021-11-09_12 34 41-cropped](https://user-images.githubusercontent.com/61723329/141104429-c149f334-0a56-40b0-bff8-5850735562ae.png)
![2021-11-09_12 34 53-cropped](https://user-images.githubusercontent.com/61723329/141104441-98cf9968-c883-4f19-a2ef-f8d40d519b96.png)
![2021-11-10_19 20 39-cropped](https://user-images.githubusercontent.com/61723329/141104455-6c28ff9b-188d-4e5e-adde-cafe91f311eb.png)

**Comment by Sunekaer** [comment]
Your smelter recipe is different from mine, could you try this on a fresh install of the pack?

**Comment by ogmacwinux** [comment]
I re-checked and this looks like a GDlauncher issue (https://github.com/gorilla-devs/GDLauncher/issues/1144) wherein the launcher "updates" the pack without actually downloading and updating the latest mods/configs/etc. so I have an outdated version.

I then used the FTB App, downloaded OceanBlock 1.9.0, moved the save, and the issue is fixed. 

Thanks for taking your time to look into this, we can close this now.
