### ISSUE TITLE
Add more ways to get ink sacks

### ISSUE THREAD

**Issue by Brndnrphl** [FTBTeam/FTB-Modpack-Issues#2951]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

So i was playing the pack and i was trying to get into occultism and i got to the point where i was trying to craft the foliot book of binding. And to make it i needed a book and quill which in turn needed an ink sack. Now i had a hard time getting any squids to spawn so this stopped me from progressing on occultism for a bit. So the current options that i found is that either wait for squids to spawn or fish and hope you get an ink sack. So i think there should be a way to be able to get ink sacks easier, maybe a squid model from hostile neural networks, if i remember correctly i think they were a thing or maybe some other way. As it is now i think it's a bit of a pain to get ink sacks but maybe that's just me and there's actually a way easier way that i haven't thought of.

**Comment by Saereth** [comment]
setup a vanilla squid farm at low y level, makes tons
