### ISSUE TITLE
Link to "FTB SkyBlock Addons" mod is wrong for latest Beta update 1.0.1. 

### ISSUE THREAD

**Issue by Hedenvang** [FTBTeam/FTB-Modpack-Issues#2952]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Describe the bug

When downloading new Beta update 1.0.1 .   Launcher asking to download "FTB SkyBlock Addons" mod manually but the link to curseforge is wrong. 

I am using ATLauncher.

![NVIDIA_Share_2023-04-06_19-26-03](https://user-images.githubusercontent.com/25149454/230452277-a56e86fd-cacb-4aa7-bc8b-b43a7494e51c.png)

![msedge_2023-04-06_19-26-32](https://user-images.githubusercontent.com/25149454/230452272-04ab7065-fcb8-4fd1-9968-8259c9f4ee62.png)

### Steps to reproduce

1. Update existing modpack using ATLauncher.
2. Manually open the "FTB Skyblock Addons" using the "Open" button on ATLauncher.
3. CurseForge not finding the correct link. 

### Expected behaviour

Curseforge finds correct download link and the mod gets downloaded. --> Game playable for Beta 1.0.1

**Comment by MasterBladeX** [comment]
Also having same issue

**Comment by Hedenvang** [comment]
I just tested again, it now works.
