### ISSUE TITLE
Small mod suggestion

### ISSUE THREAD

**Issue by Chtholly-dev** [FTBTeam/FTB-Modpack-Issues#2953]
### Modpack

FTB Skies

### Mod suggestion

Could we get Aiot Botania and Integrated NBT added to the pack? Aiot Botania work since it only adds more tool variants and are a nice straight upgrade from the vanilla versions. Integrated NBT helps the players who use Integrated Dynamics heavily to automate things easier.

**Comment by Saereth** [comment]
added aiot botania but we've chosen to leave out the direct integrated nbt as some feel it just makes an already powerful system even more powerful/accessible
