### ISSUE TITLE
Basalt Delta Town Gen

### ISSUE THREAD

**Issue by CasualCannibal** [FTBTeam/FTB-Modpack-Issues#2954]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Describe the bug

when a nether structure generates in a basalt delta biome, the structure is covered with and in some cases filled in with basalt.

### Steps to reproduce

I dont know how to reproduce this other than going to a basalt delta and spawning in a town or maybe searching for one in a new seed?

### Expected behaviour

a town spawning that could be traversed without clearing out multiple inventories worth of basalt

**Comment by loneztar** [comment]
Can confirm this is present on 1.0.1 as well
![basaltdelta](https://user-images.githubusercontent.com/42538990/230472473-7aea8e6a-df27-43b1-b4d9-4de7cb8fd5d0.png)

**Comment by Saereth** [comment]
This is a vanilla jigsaw bug, existed in inferno as well, sadly nothing we can do about it, this one is on Mojang
