### ISSUE TITLE
Hexerei and Create bug

### ISSUE THREAD

**Issue by Chtholly-dev** [FTBTeam/FTB-Modpack-Issues#2956]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Describe the bug

For Hexerei when you clear the bark from a Witch Hazel log it turns into a whillow one and you can't use Hexerei logs to make copper cassings from Create while you can with the other wood types.

### Steps to reproduce

Video bellow shows how to reproduce them.

### Expected behaviour

I expected those bugs not to happen as shown in the video bellow.

### Screenshots

Video is to big so I posted it on imgur to send it here: https://imgur.com/a/NyuUFUc

**Comment by Saereth** [comment]
previously reported, fix from hexerei is coming soon
