### ISSUE TITLE
CLient crash trying to use ae2 terminals search bar

### ISSUE THREAD

**Issue by Nidaelie** [FTBTeam/FTB-Modpack-Issues#2959]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Log Files

[crash-2023-04-05_22.17.41-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11173989/crash-2023-04-05_22.17.41-client.txt)

### Describe the bug

after update everytime i try to use the search bar in the ae2 terminals the client crash, before update had no issues

### Steps to reproduce

open ae2 terminal, try to use the serach bar... crash

### Expected behaviour

client not crash

**Comment by Nidaelie** [comment]
looks like some rftools dimlets crash the client... ae2 terminals.... chests....

**Comment by EvilZeR01** [comment]
Was going to make a new issue but this same issue is also happening to me just having the dimlet in my inventory causes the game to crash just when i open inventory.

**Comment by TehBest2020** [comment]
Yeah I had the same problem with AE2. There was a few things it could have been for me, thanks for making the post, helped me out. I think the problem is specifically in rftoolsdim version 9.1.4, it is still a beta. I went back to on my client and it doesnt crash anymore.

**Comment by JustAnotherGhostName** [comment]
This happens aswell in barrels.
