### ISSUE TITLE
Waterlogged Sifter

### ISSUE THREAD

**Issue by NicoDaKit** [FTBTeam/FTB-Modpack-Issues#2960]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Describe the bug

Grabbing water from a waterlogged sifter convertes the whole stock of buckets to one water bucket.

### Steps to reproduce

1. Take a stack of buckets (more than one)
2. Rightlick a waterlogged sifter
3. Have a single water bucket in hand, missing all the other normal buckets

### Expected behaviour

get one water bucket and the rest of the normal buckets

**Comment by Saereth** [comment]
@TheonlyTazz  :P

**Comment by TheonlyTazz** [comment]
Oh yeah! I'll fix that today
