### ISSUE TITLE
Liberians are still broken in FTB skies

### ISSUE THREAD

**Issue by PersonthatexistsYAY** [FTBTeam/FTB-Modpack-Issues#2961]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Log Files

https://mclo.gs/dEescoV

### Describe the bug

Villager trades are still broken albiet less then before (yet now new issues have popped up)
#1 Liberians are still giving looting 3 for 1 emerald and 1 book while not always it is still messing with trades
#2 Other trades are messed up as I have seen a trade "1 paper for 1 emerald" Which it should be "24 paper for 1 emerald" along with "1 emerald for 1 bookshelves" which it should be "9 emeralds for 1 bookshelves"
#3 Apotheosis expanded book levels (sharpness 9) are not in trading (I do not know if that is intentional just reporting what I am seeing)  

### Steps to reproduce

Spawn in a villager.
Lock up the villager in a box.
Put Lectern block near the villager.
Cycle trades until an enchanted book pops up.
Look what trades are shown.
Verify that these trades can spawn in the loot pool:
"1 book and 1 emerald for looting 3 book"
"1 paper for 1 emerald"
"1 emerald for 1 bookshelves"
Once those has been verified  through cycles that they are in the pool cycle again to see if other trades spawn.
No higher leveled books beyond vanilla should spawn (sharp 6+).
Note the findings.
Done.

### Expected behaviour

Different trades and apotheosis books should be appearing

### Screenshots

![2023-04-06_15 33 12](https://user-images.githubusercontent.com/122125749/230479243-c2f9a669-4a02-4b3b-a45a-e00b7bc948f0.png)

![2023-04-06_15 33 17](https://user-images.githubusercontent.com/122125749/230479272-9e61df23-4476-4abe-90e8-00f765e82044.png)

![2023-04-06_15 33 21](https://user-images.githubusercontent.com/122125749/230479291-90932df9-8615-4436-9e97-45cc7863c77b.png)

### Additional information

Has been tested on a new creative world and these issues are still there

**Comment by Saereth** [comment]
This is working as intended now, apoth trades will be back in the next update
