### ISSUE TITLE
[Bug] FTB Teams Dimensions unload

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#2962]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Log Files

https://gist.github.com/JustAnotherGhostName/5e8d7e0f6fbabdd3aa0a71f2eac780c6

### Describe the bug

Our server has had this happen twice which has required a roll back each time. Once yesterday, and once just now. A report was not made yesterday due to lack of log data found, however, although I still have not found relevant log data (although I posted the initial startup log from yesterday), I am making the report to bring attention to it.

Upon a server restart, it was discovered that all FTB Teams Dimensions data gets unloaded. That is to say, the dimension is not registering as existing, even though the data files are still there and can be located. The dimensions are not listed with `/forge tps`, `/ftbteamsdimensions visit`, nor through trying to tp to your island with `/home` or `/ftbteamsdimensions home`. 

The error listed in console is "(bad level key)" when someone try's to visit.

This appears to be more of a critical issue, so I wanted to confirm it was not a 1 off occurrence or something specific to my server before posting it.

### Steps to reproduce

Unknown, issue is noticed after a restart, however, it does not seem to be triggered by a restart. 

### Expected behaviour

You could visit your islands, and they still exist

**Comment by JustAnotherGhostName** [comment]
Update, I have had this happen for a third time now.

**Comment by JustAnotherGhostName** [comment]
Was able to hodge podge a temp rollback fix with minimized data loss, through that I confirmed that no data in the `/world/dimensions/`, `/world/ftbteams/`, `/world/playerdata/` folders and the `/world/data/ftbteamdimensions_dimension_store.dat` file did not have any issues.

**Comment by JustAnotherGhostName** [comment]
Extra info, working on a development server with the bad data. While the server is loaded, `/ftbteamdimensions list-dimensions` still lists the dimensions as existing. Yet the visit command shows there are none. 
![image](https://user-images.githubusercontent.com/122759195/230539013-eeef83fa-cf45-47cd-98f4-91a5ebddd4df.png)

**Comment by Seegras** [comment]
I think this happend to me too, now. After a crash, it spawned me in the main overworld. I even had 4 backups that were already corrupted. 

/ftbteamdimensions list-dimension listed the dimension,but  /ftpdim home and /home and even the charged porter couldn't get me home.

**Comment by Seegras** [comment]
happened again. I was playing around with rftools dimensions, but my last good save was still after I visited my first (random) rftools dimension. After that, I created several dimensions, dismantling and re-creating the dimension tabs. Still, might this be connected?

**Comment by Saereth** [comment]
Any ideas on this one @desht?

**Comment by desht** [comment]
@Saereth This sounds like dimension data isn't being written to disk after the dimension has been created, but presumably we didn't encounter this problem on the beta server?

@JustAnotherGhostName can I check a couple of things:
1. Your server is definitely being restarted cleanly, i.e. via the `/stop` command, and not due to a crash either of the minecraft server, or unscheduled reboot of the host.
2. When a new team dimension is created, can you verify that the dimension files are being created?  They will appear in `world/dimensions/ftbteamdimensions/team/<team-id>` where `team-id` is the UUID of the team just created.
3. If the dimension files are not appearing, do they appear if you do `/save-all` on the server?

**Comment by JustAnotherGhostName** [comment]
Not at my main system due to the holidays, but i can confirm the server
gets shut down with first the save-all fommand, followed by the stop
command after a few seconds.

I can take a look later today regarding if the team is added to the dim
folder.

I also want to add that I believe rf tools dims didnt load now that i think
of it. If i recall correctly, only base dims like vanilla, ad astra, ae2,
ect get registered. Though there was a reboot that only registered the
vanilla dims.

**Comment by JustAnotherGhostName** [comment]
Also I forgot to mention it in the last message, but they are not a result
of a crash or unclean shut down.

**Comment by desht** [comment]
> I also want to add that I believe rf tools dims didnt load now that i think of it

Interesting, since both mods (RFTools Dims & FTB Team Dimensions) use a similar system of dynamic dimension creation. I will take a look into this, but I haven't been able to reproduce the problem in my dev instance so far (dimensions always seem to reload fine), so this could be tricky to track down...

**Comment by JustAnotherGhostName** [comment]
If it could help, sunday night i could privide a modified copy of a server
backup with the bad data.

**Comment by JustAnotherGhostName** [comment]
I think it is worth mentioning that this may also be a result of creating
dims with RF Tools Dimensions. According to the one player on my server who
has created dimensions, the 3 times we had to roll back due to this bug,
their rf tools dimension was no longer there after a safe rollback.

**Comment by desht** [comment]
One other thing - what OS is your server running?

**Comment by JustAnotherGhostName** [comment]
Linux based os, but the modpack server is in a docker image.

**Comment by desht** [comment]
So it looks like there is some kind of unwanted interaction between RFTools Dimensions and FTB Team Dimensions going on, which causes team dimensions to get unregistered if an RFTools dimension is created.  We're trying to track down what's going on right now (both mods work fine individually, but not together, it appears).

Until we have a fix, can you advise your players not to create or use any custom RFTools Dimensions?

**Comment by Seegras** [comment]
I think it's happening when you create a custom dimension in the Dimension Builder. Because for the random one, it worked. But when I was trying to get myself a custom dimension, and made a backup before entering, the save was still corrupted.

**Comment by desht** [comment]
RFTools Dimensions has been removed from the latest release of the pack (1.0.4) so hopefully the issues will subside.  I do plan to continue trying to track down the interaction that leads to this problem, and with luck we'll be able to include RFTools Dimensions again at a later date.  Keeping this issue open for now.

**Comment by JustAnotherGhostName** [comment]
I believe there is a manual fix with modifying the level.dat. Unfortunately they never mentioned anywhere that I see on what part of the file needs to be modified, but to quote the FTB Discord, "If this issue has happened to you, please email me at mikey@feed-the-beast.com with your level.dat and their ftbteamdimensions-dimensions-store.dat and I’ll fix it and send it back to you." from Mikey, one of the admins.

**Comment by FrederikRasmussen** [comment]
> I believe there is a manual fix with modifying the level.dat. Unfortunately they never mentioned anywhere that I see on what part of the file needs to be modified, but to quote the FTB Discord, "If this issue has happened to you, please email me at [mikey@feed-the-beast.com](mailto:mikey@feed-the-beast.com) with your level.dat and their ftbteamdimensions-dimensions-store.dat and I’ll fix it and send it back to you." from Mikey, one of the admins.

Thank you very much for this information. I see that even rolling back to 1.0.3 we are unable to load the dimensions. I'll try contacting Mikey.
