### ISSUE TITLE
Dupe

### ISSUE THREAD

**Issue by NatieUwU** [FTBTeam/FTB-Modpack-Issues#2963]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Describe the bug

I can dupe with pickaxe that can place torches, i place torch on block and i take this torch whit this pickaxe it duplicate (the pickaxe)

### Steps to reproduce

1. Take pickaxe that can place torches
2. Right click on for example a block of Dirt
3. Second right click on that same block
4. Open inventory and you see your pickaxe has 2 on the bottom
5. Drop one pickaxe, and this dropped pickaxe dosent disappear

### Expected behaviour

Duped pickaxe just disappear or something 

### Screenshots

![image](https://user-images.githubusercontent.com/130102909/230494705-ea18675f-4164-40e0-8129-4046ffedeeb2.png)
![image](https://user-images.githubusercontent.com/130102909/230494768-37d107f7-51eb-4f66-aa47-693ec5bf862b.png)

**Comment by CrimsonXMC** [comment]
Can confirm i was able to reproduce this bug in my test world,
