### ISSUE TITLE
Missing Item - Dragon Glass - Obsidian Quest

### ISSUE THREAD

**Issue by RoneVierAcht** [FTBTeam/FTB-Modpack-Issues#2964]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Describe the bug

Missing Items as Quest Reward

### Steps to reproduce

Claim Dragon Glass Quest

### Expected behaviour

get the Obsidian Arrows :)

### Screenshots

![2023-04-06_23 04 57](https://user-images.githubusercontent.com/130104409/230494966-43735f19-95eb-488a-8f82-212f2682c9c3.png)
![2023-04-06_23 04 36](https://user-images.githubusercontent.com/130104409/230494970-c4277de8-c728-4663-8db4-9ce59070a3e3.png)

**Comment by Ironpyre** [comment]
I have the same issue. Did you ever find the sollution?
