### ISSUE TITLE
Sons of Sins Gluttony breaks Graves

### ISSUE THREAD

**Issue by Snailic** [FTBTeam/FTB-Modpack-Issues#2965]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Describe the bug

Gluttony mob from this mod can break graves.

### Steps to reproduce

1. Die with items to have a grave spawn
2. Spawn a Gluttony near grave.
3. Get attacked by a Gluttony near the grave.
4. Grave broken.

### Expected behaviour

Grave not broken by anything.

**Comment by recals** [comment]
i feel this is a pointless mod to have in the pack the mobs are crazy OP and there drops have almost zero use

**Comment by Saereth** [comment]
mod removed in next update
