### ISSUE TITLE
FPS drop while looking at Jetpack recipe

### ISSUE THREAD

**Issue by MrSataana** [FTBTeam/FTB-Modpack-Issues#2966]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Describe the bug

While looking at the jetpack recipes (iron jet packs mod) there is a significant drop in FPS.

### Steps to reproduce

Press E
Search for Jetpack
Click on any Iron Jetpacks Jetpack to view the recipe
Experience 3 FPS

### Expected behaviour

For it to not drop to 3 FPS

**Comment by MrSataana** [comment]
Update, seems to only be while looking at the wooden recipe.

**Comment by Stefanuk12** [comment]
This is happening to me too.

**Comment by Saereth** [comment]
I suspect there may be more to this like something system specific not sure. I tried to reproduce this again with no luck on my end, can one of you run spark on your client and then look at recipes and send me the log, may shed some insight

**Comment by Stefanuk12** [comment]
The log is a bit old, hopefully that's fine. Let me know if it's not, I was using it to diagnose some fps issues a while ago.

https://spark.lucko.me/JSGm3ZOuAf

**Comment by Saereth** [comment]
ok this is due to the crafting station trying to render it and some combination of hardware/modded items. I've requested the crafting station dev allow us to blacklist renders, we'll see if they get us an update but otherwise I cant do anything about it currently from the packdev side of things.

**Comment by manmaed** [comment]
Hello i have just tried this in version 1.3.1, and I'm not dropping any FPS can you update to this version and see if it still happens?
