### ISSUE TITLE
Curios menu not opening

### ISSUE THREAD

**Issue by WarJedi2109** [FTBTeam/FTB-Modpack-Issues#2967]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Describe the bug

unable to open the curios inventory at all. Either by hotkey or the inventory button. No clue when the issue began

### Steps to reproduce

open inventory
click curios inventory icon by character model
thus action provides no response

press keybind for open curios menu
thus action provides no response

### Expected behaviour

the menu to open to give access to curio accessory slots

**Comment by Saereth** [comment]
Cannot reproduce...anyone else?
