### ISSUE TITLE
Inventory bug

### ISSUE THREAD

**Issue by WarJedi2109** [FTBTeam/FTB-Modpack-Issues#2968]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Describe the bug

Upon loading into the world, certain inventory blocks to not open their menus, only activating the animation for opening the inventory of the block.

These blocks include:
*Double Chests
*Shulker Boxes
*occasionally barrels
*occasionally single chests 

### Steps to reproduce

after creating a world (in this instance the Chosen Island), place the mentioned inventory blocks
leave the world
re-load into the world
interact with the inventory blocks

### Expected behaviour

Inventory menu should open when right clicking an appropriate block

**Comment by Saereth** [comment]
I can't seem to reproduce this. Is this still happening for you on 1.0.2?

**Comment by Eidelmaim** [comment]
i have reproduced this issue in version 1.0.4 on a fresh server installation. this seems to only affect double chests for me.
[https://prnt.sc/SNDeU-j5DTU6](url)

**Comment by Eidelmaim** [comment]
i was using the AT launcher... i changed to the FTB launcher and this issue is no longer happening. appears to either be a launcher issue or a bad installation issue.
