### ISSUE TITLE
TB Skies wont open

### ISSUE THREAD

**Issue by i0inator** [FTBTeam/FTB-Modpack-Issues#2972]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Describe the bug

When starting the launcher it white screens and stops responding last line of code that shows up says 'minetogether could not connect: unknown'

### Steps to reproduce

press play on FTB Skies

### Expected behaviour

Launcher opens

### Additional information

even when I delete mine together it doesn't work

**Comment by MystifiedSky** [comment]
This is unrelated to minetogether.  This is because you have a higher then 1080p monitor but you still have it set to launch at 1080p.  You need to go into the launcher settings for the pack and set the resolution higher.
