### ISSUE TITLE
Add more AE and RS addons

### ISSUE THREAD

**Issue by Brndnrphl** [FTBTeam/FTB-Modpack-Issues#2976]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

Ae has a few addons added but RS barely has any making the rs much more limited compared to ae. So i think at least Extra Storage, Extra Disks should be added, cable tiers would also be nice. Ae additions would also be great because it adds a more compact wireless option other than the quantum ring for ae2 (it only works in a single dimension so it wouldnt make the quantum ring obsolete). The ME Requester and RS requestify mod would also be a good addition.

### Mod suggestion

ExtraStorage: https://www.curseforge.com/minecraft/mc-mods/extrastorage
ExtraDisks: https://www.curseforge.com/minecraft/mc-mods/extra-disks
AEadditions: https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork/files/4379316
ME Requester: https://www.curseforge.com/minecraft/mc-mods/merequester
RS Requestify: https://www.curseforge.com/minecraft/mc-mods/rs-requestify
Cable Tiers: https://www.curseforge.com/minecraft/mc-mods/cable-tiers

**Comment by Saereth** [comment]
Me requester is already in. 
AE2 Megacells is in so Ae Additions isnt needed, too much functionality overlap
We're not looking to add any additional features for RS beyond what is in the pack. Ae has more functionality and more addons but is harder to use as the trade off.
