### ISSUE TITLE
Chipped blocks with connected textures appear dark

### ISSUE THREAD

**Issue by Blockguy24** [FTBTeam/FTB-Modpack-Issues#2977]
### Modpack

FTB Skies

### Modpack version

1.0.2

### Describe the bug

Blocks from the Chipped mod that have connected textures appear dark. Blocks without connected textures work fine. In the inventory, both types look normal.

### Steps to reproduce

1. Place down some blocks from Chipped that have connected textures (such as Bordered Cobblestone)
2. Observe that it is dark
3. Place down blocks that do not have connected textures (such as Cobblestone Bricks)
4. Observe that it looks normal.

### Expected behaviour

The blocks look like their non-connected-texture variants.

### Screenshots

![2023-04-07_20 46 37](https://user-images.githubusercontent.com/21016331/230598993-3f18f2e3-125a-4a85-bbcd-1c63c3362bff.png)

### Additional information

Shaders are disabled.

**Comment by Saereth** [comment]
you can edit forge.cfg in your config and change the setting for the experimental pipeline. it will fix this but then any mekanism multiblocks will be dark, up to you which you prefer until the mods can address it themselves.
