### ISSUE TITLE
force wrench

### ISSUE THREAD

**Issue by recals** [FTBTeam/FTB-Modpack-Issues#2978]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Describe the bug

made the force wrench from forcecraft used it to pickup a ironchest full of items as intended on placement all items in the chest were gone

### Steps to reproduce

1.made force wrench added force into it 
2.used force wrench to pick up iron chest (full of items)
3.used force wrench to place iron chest  (all items gone)

### Expected behaviour

as intended from the mod you are ment to transport a block with 250 force including items within

### Screenshots

pre pickup ![image](https://user-images.githubusercontent.com/24914553/230599740-bf9288ab-42a5-4094-ba63-330f10d656fe.png)
post pickup 
![image](https://user-images.githubusercontent.com/24914553/230599877-8a9c9468-41eb-4d3e-a9d2-e39b1df6dad1.png)

**Comment by Saereth** [comment]
https://github.com/Mrbysco/ForceCraft/issues/78
