### ISSUE TITLE
Cant use middle click to change quantity on ae2 terminal

### ISSUE THREAD

**Issue by pedruhb** [FTBTeam/FTB-Modpack-Issues#2979]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Describe the bug

I cant use the mid click to change amount on patterns or craft, i cant find any option with middle click in key bindings.

### Steps to reproduce

Try use middle-click for modify amount in recipe or craft anything in ae2 terminal

![Screenshot_101](https://user-images.githubusercontent.com/34753501/230602604-91cb36a3-d070-4430-8fb8-2c19f5124b18.png)

### Expected behaviour

.

**Comment by abesto** [comment]
Just hit the same. FTR, this is the same issue as https://github.com/DarkPacks/SkyFactory-4/issues/939: Inventory Sorter takes over the middle click. I guess real solution would be the same as noted there (blocklist AE2 terminals from Inventory Sorter config in the pack).

Note, the workaround mentioned in that issue (shift-middleclick) doesn't seem to work here.

Workaround: re-bind the "Sort Inventory" action to something else.

**Comment by Saereth** [comment]
yeah rebinding the sort key is the annswer here but since we dont ship pre-set keys I cant ship it like that by default
