### ISSUE TITLE
[Bug]: metal press unformed after logging of from server, now powerconnection on top not functioning.

### ISSUE THREAD

**Issue by convict-vx** [FTBTeam/FTB-Modpack-Issues#298]
### Modpack

Oceanblock

### Modpack version

1.6.0

### Log Files

no logs available

### Describe the bug

Did build the metal press from IE, after logging off the server for the night and logging in now the power connection of the press does not work anymore from the top. when i logged in there was a graphical error with the press all looking like the bottom blocks. but the press rendered back normally after a block update next to the press (placed torch)

### Steps to reproduce

1. build metal press
2. tes it and it works
3. log off server 
4. log back in
5. notice press isnt formed and looks weird

can say i cannot reproduce this but this is what i did.

### Expected behaviour

keeping the press formed

### Screenshots

![oceanblock](https://user-images.githubusercontent.com/6298792/141250161-c6672e6f-7015-430a-8340-0fb269ebdd7f.jpg)

**Comment by Raidobw2** [comment]
To dev: Might be support, might be mod issue. Depends.

@convict-vx Is the metal press sitting in between chunk boundaries? Press F3 + G to toggle those boundaries on screen.

**Comment by convict-vx** [comment]
![oceanblock 2](https://user-images.githubusercontent.com/6298792/141281785-3afde6ed-26fb-4675-ae10-02f591465b39.jpg)

As u can see they are both in diff chunks but both are standing in 1 chunk.

**Comment by convict-vx** [comment]
also forgot to mention that the automated engineering table has the same issue. 

ss with boundaries on, this is build in corner of chunk.

![oceanblock 3](https://user-images.githubusercontent.com/6298792/141282304-cfbf2b26-6c1e-4d6f-b6f3-1a031cee439a.jpg)

**Comment by Raidobw2** [comment]
Hmm I see. Thanks for confirming. We'll need to conduct tests to determine if that's a mod issue or an effect of something else. We'll be testing on 1.7.0, even though the Immersive Engineering version didn't change from 1.6.0.
