### ISSUE TITLE
grayscales

### ISSUE THREAD

**Issue by Ahubbart** [FTBTeam/FTB-Modpack-Issues#2980]
### Modpack

FTB Skies

### Modpack version

1.0.2

### Describe the bug

not sure if I'm being silly or not but my screen has gone grey and I can't figure out why. I've looked at all the key binds but still am unable to find anything

### Steps to reproduce

i don't know how this happened so I don't know how to reproduce 

### Expected behaviour

a change so colour to the screen

### Screenshots

![image](https://user-images.githubusercontent.com/130110969/230610903-dcf98d13-3938-4845-8986-e46b82b357be.png)

**Comment by Ahubbart** [comment]
if anyone else has this issue, press F4, although It doesn't appear in the key, binds this has done the trick for me

**Comment by Fishpit** [comment]
This normally happens whenever I wear a skull or mob head.
