### ISSUE TITLE
Oredict Industrial Foregoing Essence to XP so that Experience Obelisk can use it

### ISSUE THREAD

**Issue by TSM-EVO** [FTBTeam/FTB-Modpack-Issues#2981]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

It would be beneficial to oredict all of the liquid experience to work with the Experience Obelisk mod. As it stands , Industrial Foregoing's Essence doesn't seem to work. In other packs, it seems to be a common interaction that the essence that comes from the Foregoin mob crusher is importable into whatever xp obelisk is available to players.

**Comment by Galaxy2Alex** [comment]
Same as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2641, doesn't appear to have been noticed for the new pack

**Comment by Saereth** [comment]
duplicate issue, we've already asked the mod dev to add compat, nothing else we can do for now
