### ISSUE TITLE
Enderman loot crashed my party, and game.

### ISSUE THREAD

**Issue by FenixFire00** [FTBTeam/FTB-Modpack-Issues#2982]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Log Files

[crash-2023-04-07_07.50.39-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11179672/crash-2023-04-07_07.50.39-client.txt)

### Describe the bug

While in the nether, killing Endermen, received loot.  When I moused over it to see what it was, game crash.  Based on the icon, I was able to determine that it is a 'Biome Dimlet'.  This is now stuck in my inventory.  Any help would be appreciated.

### Steps to reproduce

Unsure how this could be reliably reproduced.

### Expected behaviour

Should be able to not crash when viewing tooltip.

**Comment by Xobias** [comment]
[crash-2023-04-07_18.10.23-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11180353/crash-2023-04-07_18.10.23-client.txt)

Adding my crash log to this issue, I have just experienced the same problem twice, the second time I was trying to see which dimlet was causing the crash however I was unable to even get the tooltip before crashing to desktop.

**Comment by Joprebond** [comment]
I've gotten this same crash 3-4 times already when hovering over a dimlet.

**Comment by Saereth** [comment]
Opened an Issue with Mcjty to hopefully get this resolved
https://github.com/McJtyMods/RFToolsDimensions/issues/445

**Comment by stripeyhorse** [comment]
i get the same issue with any dimlet both in ender chests and refined storage as well.
