### ISSUE TITLE
Can't use bone meal on grass

### ISSUE THREAD

**Issue by Reaper9802** [FTBTeam/FTB-Modpack-Issues#2983]
### Modpack

FTB Skies

### Modpack version

Beta

### Describe the bug

Unable to use bone meal on vivid grass or dry grass. This prevents me from starting the Occultism quest line. Tried to create regular grass using a pedestal on top of a moss block, with the material generator upgrade. JEI says that it will produce grass, but it only creates dirt. Tried to create grass with a bucket of water in a 3x3, but all the dirt turned to vivid grass.

### Steps to reproduce

1. Grab bone meal
2. Right-click bone meal on vivid grass
3. Right-click bone meal on dry grass
4. Grab moss block and place it in the ground
5. Place pedestal on top
6. Place material generator upgrade into the pedestal

### Expected behaviour

Be able to spawn tall grass/generate grass blocks

**Comment by Saereth** [comment]
You need to make normal grass, bone meal doesnt work on those. You get pasture seeds from sifting, put those on dirt and it'll make normal grass.

**Comment by Spongman** [comment]
you need to mention this in the 1st Occultism task that reads "By using Bone Meal and breaking the Tall Grass". Using Bone Meal on what?
