### ISSUE TITLE
Dupe With Hexerei drying rack

### ISSUE THREAD

**Issue by Mizuga** [FTBTeam/FTB-Modpack-Issues#2985]
### Modpack

FTB Skies

### Modpack version

1.0.0

### Describe the bug

You can dupe any item with one of the following blocks from the Hexerei mod :
a Mahogany drying rack,
a Willow drying rack,
a Witch hazel drying rack

### Steps to reproduce

1) Place the rack 
2) Place the item you want to dupe in the rack (right click)
3) break the rack

you get 2 items back instead of 1.
It also works with unstackable items like armors and tools 

### Expected behaviour

the rack should only give the exact amount of item it is holding

**Comment by CrimsonXMC** [comment]
Can confirm this is reproducible in my world and on my server.

**Comment by KodaKat666** [comment]
Can confirm it is still a problem in 1.1.0 ftb skies
