### ISSUE TITLE
backpack

### ISSUE THREAD

**Issue by ITapan** [FTBTeam/FTB-Modpack-Issues#2987]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Describe the bug

When filled backpack with items from mob farm that have run about 30ish min it disconnect client

### Steps to reproduce

1. make a mob farm
2. make a backpack and put 2 stack upgrades in
3. let it run while magnatizing item
4. crashes when i open backpack

### Expected behaviour

Open backpack so can take out items

**Comment by ITapan** [comment]
might be a drop since exported stuff to a chest to add to drawer and still crash

**Comment by recals** [comment]
could it be a dimlet? as we are having crashes with dimlets?
