### ISSUE TITLE
Compact Sky Nested Machine crash

### ISSUE THREAD

**Issue by jdiveley** [FTBTeam/FTB-Modpack-Issues#2988]
### Modpack

FTB Skies

### Modpack version

1.0.2

### Describe the bug

I am in Compact Sky world and have a nested Large machine within my starter machine.  Often when I attempt to go from machine to machine I will crash.

### Steps to reproduce

1.  Place Large machine within starter machine.
2.  Attempt to travel between machines.

[crash-2023-04-07_16.39.32-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11181696/crash-2023-04-07_16.39.32-client.txt)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11181697/debug.log)

### Expected behaviour

Zone between worlds without issue

**Comment by Saereth** [comment]
edge case bug with plonk looks like, I've notified the dev and BlueAgent is looking into it

**Comment by BlueAgent** [comment]
Just released a fix for this: [plonk-1.19.2-10.0.4](https://www.curseforge.com/minecraft/mc-mods/plonk/files/4480791).
Let me know if it's still crashing.

**Comment by jdiveley** [comment]
That appears to of resolved the problem.  Thanks for the quick patch.
