### ISSUE TITLE
[Suggestion]: (FTB Academy 1.16) Save My Stronghold mod

### ISSUE THREAD

**Issue by Waoweens** [FTBTeam/FTB-Modpack-Issues#299]
### Modpack

FTB Academy 1.16

### Is your suggestion related to a problem? Please describe.

I was looking for a stronghold and when I found one I saw it got cut by a massive cave:

![image](https://user-images.githubusercontent.com/30313089/141285704-ddd757d7-0b8c-4435-a99d-c5b3abed062e.png)

![image](https://user-images.githubusercontent.com/30313089/141286107-8fe682e1-e1b8-4ba9-a64e-0eae32dcd492.png)

The portals did not get cut, but it was still really annoying.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/save-my-stronghold

Save My Stronghold! (Forge)

> _A lightweight mod to prevent strongholds from being torn up by underground caves, ravines - anything._
> _Enjoying that sick new cave mod you just got?_
> _Ever been fully immersed while navigating the deepest depths, searching for the End, only to come across an utterly destroyed stronghold?_
> _Say goodbye to sliced up strongholds. **Save My Stronghold!**_

**Comment by aaronhowser1** [comment]
I swear this used to be in. I'll add it, thanks!
