### ISSUE TITLE
Witch Hazel Stripped Log Bug

### ISSUE THREAD

**Issue by ZephyrousCodes** [FTBTeam/FTB-Modpack-Issues#2992]
### Modpack

FTB Skies

### Modpack version

Beta 1.0.2

### Describe the bug

When stripping a witch hazel log, its turns in a stripped willow log.

### Steps to reproduce

1. Place down a witch hazel log
2. Strip with an axe
3. Turns into a stripped willow log

### Expected behaviour

get a stripped witch hazel log

### Screenshots

https://user-images.githubusercontent.com/121004775/230696397-cfbecbcf-0058-4309-b413-e5bff919702e.mp4

**Comment by Saereth** [comment]
Hexerei is aware  of this and will have an update in a bit, we'll update once its out
