### ISSUE TITLE
Tetra weapons being categorized as pickaxes for apotheosis affixes.

### ISSUE THREAD

**Issue by WhitePhant0m** [FTBTeam/FTB-Modpack-Issues#2994]
### Modpack

FTB Skies

### Modpack version

1.0.1

### Describe the bug

Any tetra equipment that has "Good Quality 1/2" will be categorized as a pickaxe for apotheosis affixes.

Ex. Made a katana with tetra and gave it Good Quality 2 using the forge hammer with 2 Planar Stabilizers and tried to reforge it with apotheosis, but only got tool affixes.

### Steps to reproduce

1. Make any tetra weapon.
2. run `/apoth loot_category` and see it's categorized as sword/heavy_weapon
3. Give it Good Quality by using forge hammer with 1~2 Planar Stabilizers.
4. run `/apoth loot_category` and see it's categorized as pickaxe.

### Expected behaviour

Tetra weapons with Good Quality counting as weapons for apoth affixes.

### Screenshots

![image](https://user-images.githubusercontent.com/33400200/230699297-e297828d-5b0b-4cf4-873f-3388a1df0383.png)

**Comment by Saereth** [comment]
brought this up to the devs and they dont seem interested in fixing it unfortunately, just going to have the chalk this one up to an incompatibility
