### ISSUE TITLE
[Suggestion]: change how dirt is initially aquired

### ISSUE THREAD

**Issue by redgoblin88** [FTBTeam/FTB-Modpack-Issues#3]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

(huh the example read my mind)
well yeah it does annoy me when modpack developers decide to put dirt into the hammering chain of stone, because going from cobblestone to gravel, to DIRT to sand doesn't make much sense and only makes it a step more tedious.

below i have suggested two alternative ways on how you can get dirt, is a "unique" method AND is more... logical... rather than turning a stone into a soil, then back again *magically*

### Mod suggestion

I have got 2 suggestions.
now looking at the preset maps one thing they all have in common is... trees! so you already have something organic already.

My first suggestion is to utilise what you have already got, As botania is already in, we have the "pestile and mortar" which is used to turn petals into floral dye, but you could make it so crafting anything organic (for example, 8 seeds, 6 saplings, 4 wheat or 7 flowers) yields a piece of "organic mulch", as if you took the plants and ground them down.
With this mulch you then craft it again into the dirt itself

My second suggestion is utilising KubeJS, by creating a custom tool in which when you use it to break leaves, it drops "dead leaves", which you would, as i said before, craft that into dirt
(below is a json example of this which yields 1 "dead leaf" when you break any oredict leaf block [note: sorry but i was unable to locate ho to filter by tool type used])
`event.addBlock(
		'#minecraft:leaves',
		table => {
		table.addPool(pool => {
			pool.rolls = [1, 3]
			pool.addItem('kubejs:dead_leaves', 1)
		})
	})`

later on the user can use machines to automate this, possibly for more output

**Comment by Sunekaer** [comment]
Thank you for the suggestion.
This won't be changed in this pack, but ill keep your suggestion in mind for other packs we are making in the future.
