### ISSUE TITLE
[Bug]: Creating new world

### ISSUE THREAD

**Issue by TheRandomCrafter83** [FTBTeam/FTB-Modpack-Issues#30]
### Modpack

FTB OceanBlock

### Modpack version

1.1.0

### Describe the bug

When I start a new world using the ftb standard island, once the world is created, there is no island.

### Steps to reproduce

1. launch game
2. single player
3. create new world
4. select the ftb standard island without the cottage
5. start the world.
6. No island...at least for me anyway

### Expected behaviour

I believe there should be an island.

### Screenshots

![image](https://user-images.githubusercontent.com/42680657/134996917-dbf630d1-8833-4e88-a875-85b7d0105e1a.png)
![image](https://user-images.githubusercontent.com/42680657/134996931-73355160-9e56-4d9a-8e73-ed1a4bee67c6.png)

**Comment by Raidobw2** [comment]
Is this happening on the FTB App or another launcher?

**Comment by TheRandomCrafter83** [comment]
i was using MultiMC, surely thats not the issue. also, i downloaded just 2 days ago. so u dont think its an update issue unless you guys uploaded an update yesterday

**Comment by Sunekaer** [comment]
Issue is with multimc and not the pack.
https://github.com/MultiMC/MultiMC5/issues/4114

**Comment by TheRandomCrafter83** [comment]
then why do the other maps work and not the default one?

**Comment by Sunekaer** [comment]
As you can see from the issue I linked it fails to download the fail
