### ISSUE TITLE
[Bug]: Crashes sometimes when i open the quest book

### ISSUE THREAD

**Issue by ianjohnson778** [FTBTeam/FTB-Modpack-Issues#300]
### Modpack

FTB OceanBlock

### Modpack version

1.6.0

### Describe the bug

Sometimes when i open the quest book the game crashes and gives exit code 0 in the launcher and "Process crashed with exit code -1073740791" in the game output

### Steps to reproduce

Not sure seems random

### Expected behaviour

Random Crash

**Comment by MichaelHillcox** [comment]
Before anything else, please update to the latest version of the pack and see if this issue is solved

**Comment by ianjohnson778** [comment]
I have tried all the versions and it still does it after about 5 - 10 mins of play when i open the quest book

**Comment by ianjohnson778** [comment]
> Before anything else, please update to the latest version of the pack and see if this issue is solved

I have tried all the versions and it still does it after about 5 - 10 mins of play when i open the quest book

**Comment by Raidobw2** [comment]
Do you have a crash-log or even a log that gets generated after your playing session? Without information I'm in the dark and can't do much about the problem, I would need more info.
If it's on a server, the server log could help as well.

You can use https://paste.feed-the-beast.com/ to upload them here.
