### ISSUE TITLE
Crash + update to 1.0.2 = entire overworld wipe

### ISSUE THREAD

**Issue by socrlax24** [FTBTeam/FTB-Modpack-Issues#3001]
### Modpack

FTB Skies

### Modpack version

1.0.2

### Describe the bug

My game crashed due to memory overload from the QIO Mekanism stuff, and while I was online the modpack updated from 1.0.1 to 1.0.2 and when I logged in, my entire overworld had been overwritten. My teleporter still has my frequencies saved, but I can only teleport to the nether, and not to my overworld base. When I teleport to the nether and go into the nether portal, it never teleports me. I tried restoring to a backup from about 30 minutes before the crash, and it did not work. Also, when it loads me in now, it puts be back on the air ship, but when I go through the portal to "start my adventure", nothing happens. My character still has the items that were on it when the game crashed, but my QIO portable dashboard can't connect to my storage frequence, either. 

### Steps to reproduce

idk

### Expected behaviour

Uh, that my entire overworld wouldn't be overwritten?

**Comment by Saereth** [comment]
You can zip your world save and send a dropbox/google drive link, i'll take a look at it

**Comment by socrlax24** [comment]
https://drive.google.com/file/d/1l_GkNtWtNCsJ4ENlxYE7xyWvanfKpZTS/view?usp=share_link

**Comment by MichaelHillcox** [comment]
Please email me at mikey@feed-the-beast.com with your level.dat and their ftbteamdimensions-dimensions-store.dat and I’ll fix it and send it back to you. We're looking into why it's happening but we can fix it.

Both can be found in your world folder or saves for the level.dat and in the world or saves folder inside a folder called data for the latter.

**Comment by superhealing** [comment]
Would be nice to post general workaround for people already corrupted bases. Mostly people already did update to 1.0.2...

**Comment by MichaelHillcox** [comment]
When we have one, we'll be sure to make everyone aware of it. Right now I've worked out a way that fixes it 50% of the time but it's internal tooling that I can't release. I'm more than happy to put your data through it and send it back. Im still refining it and looking into how MC loads dimensions to get a better understanding of how to resolve ir 100% of the time

**Comment by socrlax24** [comment]
@MichaelHillcox I really appreciate you looking into it. I'm fine though, I started a new world and am avoiding RF Dimensions (since removed) and QIO this time around. Testing alternative storage options and having fun with it.

**Comment by Frostystyle** [comment]
@MichaelHillcox Just wanted to let you know I sent an email with requested files
