### ISSUE TITLE
Kicked for 'flying'

### ISSUE THREAD

**Issue by jon-s-london** [FTBTeam/FTB-Modpack-Issues#3002]
### Modpack

FTB Skies

### Modpack version

1.02

### Describe the bug

Fall off the island edge, get kicked because flight isn't allowed on the server. 

### Steps to reproduce

Start a server
Connect to server with client
Fall off edge of island
Get kicked

### Expected behaviour

To land back on island with a thud

**Comment by Saereth** [comment]
edit your server properties, set allow flying to true
