### ISSUE TITLE
AE2 & RS should be similarly gated

### ISSUE THREAD

**Issue by Galaxy2Alex** [FTBTeam/FTB-Modpack-Issues#3003]
### Modpack

FTB Skies

At the moment, AE2 requires Amethyst progression due to the requirement of sky stone in the Controller recipe, while RS doesn't - they appear equal in the quest lines, so they probably also should be equally achievable. Easiest solution is probably to add 4 Sky Stone as a reward to the AE2 cable quest.

**Comment by Saereth** [comment]
You don't need a controller to get into ae2, the quest also accepts an energy acceptor which Will allow you to establish an 8 channel network to get started. That being said, I'm fine adding 4 skystone as a quest reward.

**Comment by Galaxy2Alex** [comment]
Thanks - wasn't actually aware of the energy acceptor path, good thing to know.
