### ISSUE TITLE
Servercrash with selfmade modpack while entering the Nether 

### ISSUE THREAD

**Issue by DomDomderweise** [FTBTeam/FTB-Modpack-Issues#3004]
### Modpack

Other...

### Modpack version

1.19.2

### Log Files

[crash-2023-04-08_13.33.33-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11183417/crash-2023-04-08_13.33.33-server.txt)

### Describe the bug

Sever Crashes while entering the nether 

### Steps to reproduce

Start modpack on a server and go in the Nether= Servercrash
[Modpack_test.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11183439/Modpack_test.zip)

### Expected behaviour

Entering the nether with no Problems

### Additional information

Its a selfmade modpack made in Curseforge if needed i can post all mods we have in the modpack.
Its Working in Singleplayer but the Chunks are not Loading properly

**Comment by Jake-E** [comment]
This issue tracker is for FTB Modpacks, not custom made modpacks.
