### ISSUE TITLE
The stoneblock 3 world doesnt load

### ISSUE THREAD

**Issue by TUKMUK** [FTBTeam/FTB-Modpack-Issues#3007]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11183613/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11183614/debug.log)

### Describe the bug

when i try to play my world in stoneblock 3 it doesnt respond when world is loading. i see only dirt screen. i try to load world 2 hours and it doesnt load. Everytime in console is error with playerMap. Please hepl me

### Steps to reproduce

1. I click on play button in ftb app
2. it loads a main screen and i click on singleplayer
3. i click on my world
4. it writing reading world data
5. then i see only dirt screen

### Expected behaviour

when the text "reading world data" disappear i see the loading squere and then i be in my world

### Additional information

i try to put ram from 6GB to 12GB and it doesnt works

**Comment by TUKMUK** [comment]
maybe cna help this
[crash-2023-04-08_18.45.53-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11183710/crash-2023-04-08_18.45.53-server.txt)

**Comment by UnRealDinnerbone** [comment]
Looks like there was an issue loading a config file. You can fix this by deleting the config file Mekanism/generator-storage.toml (this file is located in the world folder so that full path would be world/serverconfig/Mekanism/generator-storage.toml) doing this should fix the issue
