### ISSUE TITLE
Give 5 dripstone for reward to LIQUID FIRE quest

### ISSUE THREAD

**Issue by CrypticEnigma00** [FTBTeam/FTB-Modpack-Issues#3009]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

in quest LIQUID FIRE in section getting started you give 4 dripstone which is nice but does not allow for growing dripstone as you need 5  4 to create block and one under the block to allow them to grow. the suggestion is to give 5 dripstone rather than 4 on the quest

**Comment by Saereth** [comment]
This is intended so people go trade for more to expand beyond the given 4. The tier 3 mason sells drips stones
