### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by Vylnaros** [FTBTeam/FTB-Modpack-Issues#3012]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Describe the bug

If you put any item or block into the Witch Hazel Drying Rack and break it with left click it will dupe the items that were in the rack

### Steps to reproduce

1.- Place a itch Hazel Drying Rack anywhere
2.- Fill it with the items/blocks you wanna dupe
3.- Break it with left click
4.- Items are duped

### Expected behaviour

Just dropping 1 items instead of getting it duped. 

### Screenshots

![Dupe 1](https://user-images.githubusercontent.com/130250682/230741020-0268b952-6763-4628-9609-39bb7a49142b.jpeg)
![Dupe 2](https://user-images.githubusercontent.com/130250682/230741026-40ec9696-c742-4552-b2c8-050bcbdc2f12.jpeg)

**Comment by KodaKat666** [comment]
Can confirm this glitch still is active in version 1.1.0! Just looked to see if anyone had already posted about it, just came across it myself.
