### ISSUE TITLE
Client crash on opening storage with RFTools Dimlet inside

### ISSUE THREAD

**Issue by shadowcryptic** [FTBTeam/FTB-Modpack-Issues#3014]
### Modpack

FTB Skies

### Modpack version

1.0.2

### Log Files

[crash-2023-04-08_16.47.33-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11184393/crash-2023-04-08_16.47.33-client.txt)

### Describe the bug

Mob farm is producing RFTools dimlets, the chest that I have the items being pumped into crashes my client when I open it.
I've been able to open it with dimlets in there previously but there seems to be one or more causing this crash.

### Steps to reproduce

Open storage with a specific RFTools dimlet inside.

### Expected behaviour

Opening the chest doesn't cause a crash.

**Comment by Jake-E** [comment]
This was fixed in FTB Skies 1.0.3:
https://feed-the-beast.com/modpacks/103/changelog/6448
