### ISSUE TITLE
Add Balanced Enchanting

### ISSUE THREAD

**Issue by ogmon1243** [FTBTeam/FTB-Modpack-Issues#3017]
### Modpack

FTB Skies

### Mod suggestion

With apotheosis, enchanting can take up to 100 levels and without balanced enchanting, it takes 100 levels from you. This issue is that the enchants are not always good and it becomes a big waste of xp unless you have a big and laggy mob farm supplying you with xp.

https://www.curseforge.com/minecraft/mc-mods/balanced-enchanting

**Comment by Saereth** [comment]
This currently has some issue with 1.19.2 will revisit later once the dev resolves them
