### ISSUE TITLE
[Bug]: Breaking Creative Generator doesn't drop it

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#302]
### Modpack

Ftb University 

### Modpack version

1.3.0

### Describe the bug

Breaking Creative Generator doesn't drop it (think its the same with creative source jar too)

### Steps to reproduce

1.) Place it
2.) Break it

### Expected behaviour

It should drop as an item

**Comment by aaronhowser1** [comment]
Fixed both
