### ISSUE TITLE
Create deployers not planting saplings

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#3023]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Describe the bug

Deployers from Create are seemingly unable to plant saplings. The sapling-planting sound is made but no sapling actually gets planted in the ground.

I've tested the design (screenshots below) in a forge-4.3.6 instance with create-0.5.0.i only and deployers work as expected.

Not seeing anything relevant to Create in latest.log or debug.log but I can attach them if needed.

### Steps to reproduce

1. Place deployer with rotational power as in the third screenshot
2. Drop a sapling into the hopper

### Expected behaviour

Sapling planted by deployer

### Screenshots

FTB Skies: non-working
![Screenshot](https://gcdnb.pbrd.co/images/toVld7fqedkr.png?o=1)

Test instance: working
![Screenshot](https://gcdnb.pbrd.co/images/fuQRMm65QImv.png?o=1)
![Screenshot](https://gcdnb.pbrd.co/images/QAlHYaUlN4eJ.png?o=1)

**Comment by ukmcplyr** [comment]
Seems this is only an issue in claimed chunks.

Deployers work as expected in unclaimed chunks. Hoping this is a bug :thinking:

**Comment by Epicycle23** [comment]
Did you try to set "Allow All Fake Players" option to true in the team properties?

**Comment by Saereth** [comment]
This is not a bug you need to go into your team settings and allow fake players to interact with your claims. This is off by default because otherwise someone could make a create contraption to just go mine up your entire base/griefing issues etc
