### ISSUE TITLE
Add the Mod XNet

### ISSUE THREAD

**Issue by MasterBladeX** [FTBTeam/FTB-Modpack-Issues#3024]
### Modpack

FTB Skies

### Mod suggestion

Xnet has similar performance to laserIO but has better GUI and easier to manage. It would be a great addition to the pack
Link: curseforge.com/minecraft/mc-mods/xnet

**Comment by Saereth** [comment]
We considered it but the pack is already quite large and it's functionality is all mostly covered already. I do like the mod though, is great!
