### ISSUE TITLE
Chipped bordered tuff block places as if no light is there.

### ISSUE THREAD

**Issue by Mogrin27** [FTBTeam/FTB-Modpack-Issues#3025]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Describe the bug

When placing the chipped  bordered tuff block, it places as if no light.

### Steps to reproduce

Place the chipped bordered tuff block into the world.

### Expected behaviour

The block should have displayed exactly like all other blocks placed in a well lit area.

### Screenshots

![2023-04-09_08 26 54](https://user-images.githubusercontent.com/76449585/230772452-832935a1-bb7a-4eff-bd0c-8b6ad857aef6.png)
![2023-04-09_08 27 03](https://user-images.githubusercontent.com/76449585/230772454-5f600706-0d41-4d9b-a490-dd4bd98ce0c8.png)

**Comment by Saereth** [comment]
This is a rendering issue you can fix it by changing the experimental pipeline config option in your forge config but then mekanism multiblocks will all have this render shading instead. Kinda have to chose between the two until the mods can correct it themselves
