### ISSUE TITLE
Levitation Stone

### ISSUE THREAD

**Issue by NordicGamerFE** [FTBTeam/FTB-Modpack-Issues#3026]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Log Files

N/A

### Describe the bug

The Levitation Stone from castle in the sky dont work

### Steps to reproduce

go to 8000 cords and use the stone

### Expected behaviour

for the stone to make a cloud that you can follow

**Comment by Saereth** [comment]
already reported to mod dev, closing as this is a duplicate
