### ISSUE TITLE
Visual Bug Mega Pattern Provider - set direction

### ISSUE THREAD

**Issue by Jona898** [FTBTeam/FTB-Modpack-Issues#3027]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Describe the bug

If you change the direction of the MEGA Pattern Provider the visuals show always towards North.
If you inspect the block with "/ftblibary nbtedit block __ __ __" the direction is set correctly, only the visuals point in the wrong direction.

### Steps to reproduce

1. Build the MEGA Pattern Provieder
2. Right click it with the AE2 Quartz Wrench
3. Inspect the block with "/ftblibary nbtedit block ..."

### Expected behaviour

The Visuals point in the right direction

**Comment by Saereth** [comment]
reported to mod dev
https://github.com/62832/MEGACells/issues/51

**Comment by Jona898** [comment]
Thanks for forwarding this.
I didn't think it was a general mod issue and it was only here.

**Comment by 62832** [comment]
Mod dev here; as per the issue linked, I've fixed this in dev and I should be able to include it in the next release build.
