### ISSUE TITLE
Melon not growing

### ISSUE THREAD

**Issue by Mizuga** [FTBTeam/FTB-Modpack-Issues#3028]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Describe the bug

Melon seeds can be grown fine they never actually create a melon block on an adjacent block. (I waited a few minutes with randomTickSpeed set to 100)

### Steps to reproduce

1) Plant a melon seed
2) Wait ?

### Expected behaviour

Melon should grown

### Additional information

This is fine because we can get melons using the Phytogenic Insolator from Thermal but the natural way should be an option too

**Comment by Saereth** [comment]
I can't reproduce this behavior and we arent doing anything in the pack to alter vanilla melons
![2023-04-09_10 11 06](https://user-images.githubusercontent.com/9200909/230786589-32ddcbfa-4975-4375-8e33-0d5aece5c475.png)

I'd say make sure they have plenty of room to grow around them and adequate light/water
