### ISSUE TITLE
Progression gated behind cogwheel, only obtainable through quest reward

### ISSUE THREAD

**Issue by EduardoTost** [FTBTeam/FTB-Modpack-Issues#3029]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Describe the bug

Quest book mentions quests are optional, but the only way to progress through the pack requires a cogwheel for the sifter, and to make the cogwheel you require materials obtained through sifting (iron nugget + andesite).

Currently the only way to obtain the cogwheel on a new world is through a quest reward, which makes the quests required to progress through the pack.

### Steps to reproduce

1. Create new world
2. Attempt to sift
3. No way to craft first cogwheel to start sifting
4. Rely on quest reward to progress through modpack

### Expected behaviour

Should not rely on quest rewards to progress through modpack

**Comment by Jake-E** [comment]
You can directly hand crank the sifter, thus the cogwheel isn't needed to do this?

**Comment by EduardoTost** [comment]
> You can directly hand crank the sifter, thus the cogwheel isn't needed to do this?

I don't think this is true, even the quest book mentions the hand crank must be on a cogwheel.

From the quest book:

_Make sure the cogwheel that is part of the sifter aligns with the cogwheel your handcrank is on._

**Comment by Fishpit** [comment]
You can also use the sieve in one hand and gravel in the other btw. You want to attach the crank to the underside of the sifter. Have done both.

**Comment by EduardoTost** [comment]
Can confirm the above works, thanks for the help!
