### ISSUE TITLE
[Bug]: Protection Ancient Tome potentially impossible to get

### ISSUE THREAD

**Issue by JunaidA197** [FTBTeam/FTB-Modpack-Issues#303]
### Modpack

Ftb University 

### Modpack version

1.3.0

### Describe the bug

I've had over 150 books, and I keep getting the same few, protection book is needed for the multi armour.

### Steps to reproduce

1.) Im using a loonium to generate chest loot
2.) I've gotten well over 150 books and non are protection

### Expected behaviour

All tomes should be possible to receive

**Comment by Raidobw2** [comment]
I'll mark this as mod issue but unsure, might require some looking around the code

**Comment by JunaidA197** [comment]
> I'll mark this as mod issue but unsure, might require some looking around the code

I checked the configs, theres only 20 books you can get and protection isn't one of them.

**Comment by aaronhowser1** [comment]
Fixed
