### ISSUE TITLE
refined storage not allowing item removal from disks or drawers

### ISSUE THREAD

**Issue by STaT-Evolution** [FTBTeam/FTB-Modpack-Issues#3031]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

so i set up refined storage in a simple set up with power to disk drives and a drawer controller with an external storage set to priority ten, the system works and allows the crafting grid to craft from jei, the issue im having is the system does not allow me to take items out of the system unless it is in the crafting grid of the crafting grid block. i have tried both crafting grid block and the regular grid block, neither allowed me to remove items, ik there is ae2 in the pack but i just prefer to use refined storage due to the channel restrictions and ae2 interfaces not being ideal for me.

### Steps to reproduce

1. set up system
2. set up drawer controller with a bunch of drawers and auto input materials from a bunch of things being sifted from create sifters into the drawers
3. try to remove items

### Expected behaviour

i expect to always be able to take out my items if the system has power and items to take

**Comment by Saereth** [comment]
Refined storage bug, reported, will update the pack when they resolve. There is always ae2 in the meantime like you said.

**Comment by anagram3k** [comment]
The mod developers are aware of the problem?

I couldn't find an issue created on either refined storage or functional storage on GitHub

**Comment by Flekrad** [comment]
Here is a workaround (works in 1.0.6 , unsure if it will for 1.0.4)
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3124

**Comment by manmaed** [comment]
See https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3124
