### ISSUE TITLE
ftb skies

### ISSUE THREAD

**Issue by Emmci** [FTBTeam/FTB-Modpack-Issues#3032]
### Modpack

FTB Skies

### Modpack version

ex.1.0.4

### Describe the bug

while traveling through the sky villages captured chickens in jars can spawn in some of the chests alongside the feed needed to create a golden egg however when I try to open the jars I get a message in the chat logs that there is no such animal or entity found.

### Steps to reproduce

1. go to sky village, if there are chickens in jars that spawn in the chests found around it
2. try to open the jar and release the chicken
3. a message shows up saying there is no entity found

### Expected behaviour

a message pops up in the chat

**Comment by Saereth** [comment]
already reported, will be fixed in a future update
