### ISSUE TITLE
frame rate drops when opening any ui.

### ISSUE THREAD

**Issue by LilEndy** [FTBTeam/FTB-Modpack-Issues#3033]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Describe the bug

If I were to open a chest, crafting table, etc.  my frames will drop 90% (which for me is about 30 frames) and has at one point crashed while I tried to pull up a recipe.   

### Steps to reproduce

open something with a gui.

### Expected behaviour

to run as the game does normally.

### Additional information

I do not have a powerful computer, however I have never seen this before and checking some of my other modpacks I experienced no such drop.

I also experience a lot of frame drop near the main island that dies down if i leave, though I am unable to find what causes it.

Finally I experimented with chests to see if it was the amount of items in it that caused the drop, with little to no difference.

**Comment by LilEndy** [comment]
In 1.0.4 it seems to be significantly better but I still have a low frame rate; 10 fps in ui and 20 outside.

**Comment by LilEndy** [comment]
It works a little better in 1.0.4 but I am still getting 10 frames in ui and 20 frames outside.

**Comment by LilEndy** [comment]
[https://spark.lucko.me/1adz43Nz9g](url)
Here is the link
Interesting idea with the JEI as this is prevalent between all UI and not a specific one,  I did clear out my favourites, despite only having four, and found no significant change.  I cannot find a way to limit or disable JEI in order to test this, unfortunately.

**Comment by MissPotato** [comment]
> https://spark.lucko.me/1adz43Nz9g

It seems like it is the Crafting Station mod that is tanking your FPS. The best I can suggest is to stop using it asap.

**Comment by Saereth** [comment]
yeah this seems to be crafting station mod from what I can tell, forwarded onto the dev but nothing else I can do about it on our end
