### ISSUE TITLE
Bad rendering of soul sand chiken

### ISSUE THREAD

**Issue by Nwitlyck** [FTBTeam/FTB-Modpack-Issues#3034]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

The soul sand chicken doesnt have pick or the red think under it or legs

### Steps to reproduce

1. Get a soul sand chicken
2. See there is no legs or mouth

### Expected behaviour

Not legs or mouth of the soul sand chicken

### Screenshots

![2023-04-09_20 44 45](https://user-images.githubusercontent.com/100742058/230815468-dd70740a-a0e4-4f39-a9b2-d99f0424de5b.png)

**Comment by UnRealDinnerbone** [comment]
Reported to mod author https://github.com/CreeperHost/Chickens/issues/55

**Comment by UnRealDinnerbone** [comment]
The issue has been fixed
