### ISSUE TITLE
Crashing when trying to open the world to friends.

### ISSUE THREAD

**Issue by FussionDelight** [FTBTeam/FTB-Modpack-Issues#3035]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Describe the bug

I've been trying to play with some friends but everytime I hit "Open to Friends", it freezes for a bit, then says saving world like if I quit to title, then crashes. My friends also tried it and it seems the many people, or maybe even all are having the same issue.

### Steps to reproduce

1. Make a single world
2. Esc
3. Open to friends (top right)

### Expected behaviour

Open my world, available to my friends

**Comment by Saereth** [comment]
Need crash logs

**Comment by FussionDelight** [comment]
[crash-2023-04-12_16.28.37-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11216828/crash-2023-04-12_16.28.37-client.txt)

oops sorry about that. Here it is
