### ISSUE TITLE
Updating from 1.0.2 to 1.0.4 broke sifters, now nothing will sift.

### ISSUE THREAD

**Issue by DMCK96** [FTBTeam/FTB-Modpack-Issues#3036]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Log Files

server log: https://pastebin.com/Adw0PpKA

### Describe the bug

Updated from 1.0.2 to 1.0.4.

Everything seems fine, no noticable issues but now I can't sift anything. 

Tried gravel and dust, both with an amethyst mesh, and had tried breaking and rebuilding with no luck. Any items just get stuck in hoppers above the sifter/mesh.

### Steps to reproduce

1. Create a server on 1.0.2
2. Build automated sifter
3. Update to 1.0.4
4. Observe bug

### Expected behaviour

Should be able to sift no problem

**Comment by Saereth** [comment]
gonna need log files, looks like you're missing kube scripts at a guess, logs will confirm
