### ISSUE TITLE
FTB SKIES v1.0.3 and v1.0.4

### ISSUE THREAD

**Issue by 2ndRecon** [FTBTeam/FTB-Modpack-Issues#3037]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Log Files

No Logs Needed

### Describe the bug

When using the flower pouch from Botania, and when it contains Flowers; opening the pouch from your inventory bar with right-click and then 'Middle Mouse' clicking anywhere in the Pouches UI will cause ALL ITEMS TO VOID.

This is a similar behavior to something I described with IF machines in FTB Eyes.
[url="https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1301"]Middle Mouse Click Void Issues IF [/url]

Someone mentioned this could be related to Inventory Sort / Mouse Tweaks behaviours. IF Author says it isn't an IF issue and I am going to presume that Botania author will say the same. 

I'm just reporting it on this pack because the bug / issue is still present and causes players to lose items. In the case of Botania, it is progression breaking to lose for instance, white flowers which are needed for Pure White Daisy and other things. 

### Steps to reproduce

Get the Botania Flower Pouch.
Equip the flower pouch to your characters hot-bar / belt.
Harvest / Drop some magical flowers from Botania
Flowers should be auto-magically placed into the Flower Pouch
Select and Right-Click the flower pouch to open it's inventory
Middle-Mouse Button Click anywhere in the Botania Pouch UI
'Voila' you have now voided  / deleted all these rare drops.

Thank you.

### Expected behaviour

Middle Mouse Clicking in a non-sortable inventory such as a machine output or a flower pouch / ender pouch, etc. should have no effect or be nulled.

**Comment by hadesanc1** [comment]
Facing a similar issue here using the middle click with the dank/dock from #dank storage.
