### ISSUE TITLE
Trades not rerolling

### ISSUE THREAD

**Issue by MrCeanBeard** [FTBTeam/FTB-Modpack-Issues#3038]
### Modpack

FTB Skies

### Modpack version

newest

### Describe the bug

i assume it has something to do with the custom dimensions our island is set on but trades for villagers have not rerolled for me at all.

### Steps to reproduce

bleed them dry of a trade item

wait.

### Expected behaviour

i wait a day and they should reroll twice

**Comment by Saereth** [comment]
Put them in the ez trader blocks and give them their appropriate workstation (righ click it into the block) They will start resetting normally then
