### ISSUE TITLE
rftoolsstorage won't add recipes to crafting grid while across dimensions

### ISSUE THREAD

**Issue by MrCeanBeard** [FTBTeam/FTB-Modpack-Issues#3039]
### Modpack

FTB Skies

### Modpack version

newest

### Describe the bug

i have my storage room in a compact machine. when i am in the overworld i can access all of my storage by using a tablet, however if i try to craft something from jei it just doesnt apply the recipe to the crafting grid. 

when i am in the machine my storage is in it works fine and oddly enough it works fine when i'm inside of a different machine. just not in the overworld.

### Steps to reproduce

build rftoolssorage room in a compact machine
try to craft from jei in the overworld

### Expected behaviour

i should be able to craft anywhere with a tablet connected to my storage scanner

### Additional information

i have power to the storage scanner
and i have the chunks force loaded

**Comment by Saereth** [comment]
I cant reproduce this, seems to be working fine for me, can you give me some screenshots of your setup?
![image](https://user-images.githubusercontent.com/9200909/231600614-1b410c05-9173-4a57-9350-c64c056f0d08.png)
