### ISSUE TITLE
[Suggestion]: Replace BetterEndForge with BetterEndReforked

### ISSUE THREAD

**Issue by GoatRammaHamma70** [FTBTeam/FTB-Modpack-Issues#304]
### Modpack

FTB university 1.16

### Is your suggestion related to a problem? Please describe.

a suggestion i have is to replace betterendforge in the pack with betterend reforked. betterendforge is abandoned and will therefore have no more updates. reforked will continure to get updated, and it also works with magnesium, which improves preformance.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked

**Comment by sarim** [comment]
This should be nice improvement in FTB Oceanblock too.

**Comment by quietust** [comment]
> 
> 
> This should be nice improvement in FTB Oceanblock too.

Already planned (or possibly done already) - see #291.

**Comment by zoller27osu** [comment]
Hopefully this would also have fixed the issue of Sulfur Springs biomes being present in my Overworld lol

**Comment by aaronhowser1** [comment]
Done
