### ISSUE TITLE
Productive Bees can force stack any item allowing for dupes

### ISSUE THREAD

**Issue by MissPotato** [FTBTeam/FTB-Modpack-Issues#3040]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Log Files

Not useful

### Describe the bug

Productive Bees can be used to force any item to stack. This lets you not only bypass Minecraft's 64 stack limit, but stack unstacakables.  With very little effort. This opens up a whole list of dupes. Which I wont explain for obvious reasons.

### Steps to reproduce

1) Shift click any identical item into the advanced hive block.
2) Pick up both items with your mouse, they are now stacked.
3) Drop the item on the ground
4) Pick it up to maintain stack.

### Expected behaviour

Only take out a maxStack of item

### Screenshots

https://i.imgur.com/MR7ujby.png
https://i.imgur.com/20Ze2Xo.png
https://i.imgur.com/uQi7y0D.png

**Comment by Saereth** [comment]
https://github.com/JDKDigital/productive-bees/issues/370
