### ISSUE TITLE
Item disappears in a dock #dank storage when using middle click to sort inventory from #inventory sorter

### ISSUE THREAD

**Issue by hadesanc1** [FTBTeam/FTB-Modpack-Issues#3041]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

Item disappears in a dock #dank storage when using middle click to sort inventory from #inventory sorter

### Steps to reproduce

Middle click a dock with stacked items inside, the item stacks will expand in a form of 64 per stack. The overflow items would disappear.

### Expected behaviour

Nothing should happens or sorts in a correct way rather than expanding the items and causing them to disappear.

**Comment by MechBFP** [comment]
Sounds like a similar issue/cause to this problem https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3037

**Comment by hadesanc1** [comment]
![image](https://user-images.githubusercontent.com/122217363/232038990-ef05a6cd-6747-4372-b452-f3d53f948632.png)

**Comment by hadesanc1** [comment]
Its not fixed in 1.0.5 :C

**Comment by hadesanc1** [comment]
![image](https://user-images.githubusercontent.com/122217363/232039454-4fbe772e-5476-46bf-9790-42b13a64089c.png)

**Comment by TheMeq** [comment]
Just had this happen to me, luckily it was just full of farmable stuff like dirt, stone, sand and dust. Looks like i'm sticking the dank back in to storage so it doesn't happen again.

**Comment by EthicalBen** [comment]
The issue persists in 1.2.1
