### ISSUE TITLE
Apple of Lofty stature bug

### ISSUE THREAD

**Issue by lars2505** [FTBTeam/FTB-Modpack-Issues#3042]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

When I started my world I ate an apple of lofty stature from cyclic to get more hearts. I know that this item enables step height so you no longer have to jump up a block. If you want to disable it you eat another one. So I ate another apple to turn the step height off. 
Now every time I join my world the step height is enabled by default. So I need to eat two apples to disable it.

### Steps to reproduce

Don't have a clear idea of what happend
1. Ate an apple of lofty 
2. noticed that I could jump up blocks without hitting spacebar
3. Ate a second apple to remove this
4. When I reopen my world the step height is back
5. Eat two apples every time I join my world.

### Expected behaviour

That after I ate the second apple to disable the step height, I don't need too eat two apples to get rid off it every time I join my world

**Comment by Saereth** [comment]
duplicate issue, bug has already been reported to cyclic, we'll update when they get a fix for it
