### ISSUE TITLE
FTB Skies 1.0.4 - Force Craft - unable to craft Upgrade Core - Recipe produces no result

### ISSUE THREAD

**Issue by 2ndRecon** [FTBTeam/FTB-Modpack-Issues#3043]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

When attempting to craft the 'Upgrade Core', JEI recognizes you have the ingredients, but produces no result either in the crafting table nor in the player's 2x2.

Even with a freshly crafted 'full durability' Force Rod, you cannot produce the desired result of 'Upgrade Core'.

### Steps to reproduce

Get a Force Rod and an Experience Tome
Place them in either your 2x2 or in a Crafting Table
Notice it doesn't produce the desired result

### Expected behaviour

Using a fully durable (75/75) Force Rod WITH an Experience Tome should produce a Upgrade Core

### Screenshots

![MC-Skies-Problem1](https://user-images.githubusercontent.com/39180607/230980465-0d413d77-2c1e-4e83-a200-d151ad940285.png)
![MC-Skies-Problem2](https://user-images.githubusercontent.com/39180607/230980467-51eba0db-5559-42e0-99ab-50c2a4c0e180.png)

**Comment by Saereth** [comment]
How much experience is in your tome?
