### ISSUE TITLE
FTB skies 1.0.4-Quests

### ISSUE THREAD

**Issue by W1TH3REX** [FTBTeam/FTB-Modpack-Issues#3044]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

Hello FTB team
I am writing to an issue regarding the quests
Basically sometimes  when I leave the game and restart the modpack and join back on my world the quests reset. Idk if it is just an issue for me but I hope u can resolve the issue. I know it is still in beta and it is gonna have some issues but i think its good to forward this to you.
Best regards

### Steps to reproduce

1. Launch FTB skies modpack
2. Create a world
3. Complete most of the starting quests
4. Leave the game
5. Quit modpack
6.Relaunch modpack and join world

It does not work everytime but some quests that have been already claimed are reset

### Expected behaviour

I hope the issue is resolved in the next update. If it is not it is alright.

**Comment by Saereth** [comment]
I can't reproduce your issue. Can you send me a copy of your world save in dropbox/googledrive something like that

**Comment by MuneebM-GAMING** [comment]
The same thing is happening to me. Here is my world save:

https://www.mediafire.com/file/772dx2eqigs70ty/FTB_Skies_-_1_19_2_Skyblock.zip/file

**Comment by W1TH3REX** [comment]
I fixed the issue thank u for ur help tho i really appreciate it <3

Best regards

V čet., 20. apr. 2023, 05:55 je oseba MuneebM-GAMING <
***@***.***> napisala:
