### ISSUE TITLE
Doubling Weapons on Right Click?

### ISSUE THREAD

**Issue by brandonramon** [FTBTeam/FTB-Modpack-Issues#3046]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11195540/latest.log)

### Describe the bug

When right clicking with my netherite paxzel and my Power of Friendship sword, I'm able to duplicate the item after a few right clicks. So far I have 6 copies of my paxzel at varying durabilities (can place a torch at the price of durability). With that as well, my paxzel fails to place visible torches, however the light level does increase. I'm in a hexerei village so I don't know if that's a factor but I didn't notice this issue on my home island. Also, witch hazel drying racks also doubled my sword so I have three copies.

### Steps to reproduce

see note above

### Expected behaviour

duplication of item

**Comment by Saereth** [comment]
this is a known issue with the torch placing modifier, it's been reported and this is a duplicate issue. Once Apotheosis has a fix for it we'll update to include it. Ty for the report
