### ISSUE TITLE
1.0.4 Functional Storage not allowing more items to be imported 

### ISSUE THREAD

**Issue by Riezing** [FTBTeam/FTB-Modpack-Issues#3048]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

I am using functional storage to store cobble and dirt both have a copper upgrade but cobble wont go past 6.7 and dirt will not go past 7.6 i've tried to manually place a stack and ive let pedestals try and both have not worked 

### Steps to reproduce

1.Have storage drawer have a certain amount of an item
2.Try to place more of the same item inside but will not fit 

### Expected behaviour

To be able to place the displayed amount of items in storage 

### Screenshots

![Screenshot_3](https://user-images.githubusercontent.com/39835635/231061081-0b3b78c3-eddc-46aa-b489-d761f38e8fda.png)
![Screenshot_4](https://user-images.githubusercontent.com/39835635/231061087-e15f730c-4892-47f3-962a-93f0b897f5cb.png)

**Comment by Saereth** [comment]
that could be, probably removing and readding the upgrade will adjust it. In a fresh 1.0.5 (dev build) world this works fine now. so break/replace should sort it. 

![image](https://user-images.githubusercontent.com/9200909/231595024-dd151ea2-dbae-4c56-a580-a266a190e5ca.png)
