### ISSUE TITLE
FTB Skies: Pedestals Planter Not Planting Saplings Since 1.0.4 Upgrade

### ISSUE THREAD

**Issue by ratkinsonuk** [FTBTeam/FTB-Modpack-Issues#3050]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Log Files

N/A

### Describe the bug

It looks like this mornings 1.0.4 release may have broken the Pedestal Planter. I had a tree farm running without any problems before the update, but now it's not planting the saplings. It does make the planting sound however, so it's trying to do something.

### Steps to reproduce

Place a pedestal down with a Planter upgrade and Oak Saplings. Add a Work Area Card configured for a 2x2 area.

### Expected behaviour

Planter should plant saplings on the grass area

### Screenshots

![image](https://user-images.githubusercontent.com/25905667/231133867-00cec51b-dcc0-42f8-8477-bb07b549a882.png)

**Comment by DLCIncluded** [comment]
I had this issue, my area was claimed using the FTB Chunks. Unclaiming it allowed the planter to start working, and claiming after the pedestal started placing saplings, it continued to work. This appears to be a fake player permissions issue

**Comment by Saereth** [comment]
yeah this is a setting issue in your chunks not a bug but rather working as expected in claimed chunks

**Comment by ratkinson-prh** [comment]
Apologies Saereth. I got a reply on Discord to the same effect, and meant to come back to close this call.
