### ISSUE TITLE
Going into orbit breaks dimensions

### ISSUE THREAD

**Issue by socrlax24** [FTBTeam/FTB-Modpack-Issues#3051]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

I went to the moon, and coming back, I thought I'd try going into orbit around earth. My rocket started freefalling above the starting airship and did this on a loop until it randomly despawned and it was just me freefalling, so I used my teleporter and luckily it sent me back to my base's dimension. I'm not sure if this is actually a bug, but definitely doesn't seem like it's working correctly. 

### Steps to reproduce

1. Go to moon
2. When leaving moon, go into earth orbit
3. Get sent to wrong dimension

### Expected behaviour

Not sure

**Comment by socrlax24** [comment]
Also, my rocket disappeared.

**Comment by Saereth** [comment]
This is something that'll need some reworking later

**Comment by manmaed** [comment]
still issue 1.3.1

**Comment by Saereth** [comment]
This is not something ad astra is going to build in compat for in 1.19.2 unfortunately, so I've added a note to the space quests that you should not attempt to fly back to your base and instead use a teleportation method.
