### ISSUE TITLE
Dark textures for mekanism multiblocks

### ISSUE THREAD

**Issue by vprouza** [FTBTeam/FTB-Modpack-Issues#3053]
### Modpack

FTB Skies

### Modpack version

1.0.4,1.0.2

### Describe the bug

Multiblock structures from Mekanism mod are really dark when build in the world.
Tested on 1.0.2 and 1.0.4

### Steps to reproduce

Build any Mekanism multiblock structure

### Expected behaviour

Mekanism multiblock are rendered correctly

### Screenshots

![2023-04-11_17 17 07](https://user-images.githubusercontent.com/51821713/231210145-67d3c771-0c0f-4c77-8c56-b0992dac8967.png)

### Additional information

I tried installing just mekanism to clean forge installation and it works correctly there.

**Comment by vprouza** [comment]
After trying that on other computers, It seems like this is problem just on AMD GPUs

**Comment by Saereth** [comment]
you can edit the forge.cfg in your configs and change the lighting to experimental, this will break the lighting on functional drawers though so the choice is yours until both mods can resolve
