### ISSUE TITLE
Furnace and Barrel not responding to clicks

### ISSUE THREAD

**Issue by Envy7500** [FTBTeam/FTB-Modpack-Issues#3054]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

So, when i spawned in on my island (The standard FTB island) i tried opening the barrels, but nothing happened, figured i'd just break them to get the items in them which worked. Kept on playing a few minutes was going to make a sifter, but for that i needed stone. So, i made a furnace, but when trying to open it nothing happened. I tried reloading the world, and even creafting a new island, but the issues still occur

### Steps to reproduce

1. Find a barrel or furnace
2. try left-clicking them

### Expected behaviour

To be able to open their menus

**Comment by Saereth** [comment]
Does not occur for me on a fresh 1.0.4 install. Please provide your latest.log and possible a zip of your world save if able.

**Comment by Envy7500** [comment]
I ended up deleting the world and creating a new one, and that seems to have fixed it. Might be a random bug that appears during world generation or something im guessing. 

Here's the log for that world
[2023-04-11-2.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11216393/2023-04-11-2.log)

**Comment by Saereth** [comment]
yeah looks like an apoth config corrupted on that save which was invadating the block tags. Since it was fixed with a new world it's likey forge regerated the broken config (it does this normally) and you should be ok now. If you run into this again feel free to reopen the issue. Thanks for the log!
