### ISSUE TITLE
Going into nether crashes server

### ISSUE THREAD

**Issue by SharkToothDK** [FTBTeam/FTB-Modpack-Issues#3055]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Log Files

[2023-04-11-1.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11203355/2023-04-11-1.log)

### Describe the bug

whenever somebody goes into the nether, the server crashes. for both someone with or without the portal necklace.
after reloading it either crashes when they log in or its fine but someone else cant go into the nether without it crashing.

### Steps to reproduce

1. login
2. if person is in the nether .
3. if person is in overworld and then goes into nether. it crashes.

### Expected behaviour

the whole server crashes and restarts

### Additional information

anyone in the overworld is fine and can play normally. 
no crash log folder is made so this is the only log i can find.

**Comment by Saereth** [comment]
need an actual crash log, your latest.log doesnt have anything about a crash in here
