### ISSUE TITLE
[Bug] Rituals to change the time of day do not work

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#3056]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Log Files

No relevant logs

### Describe the bug

When a player wants to do a ritual to change the time of day, IE, moon fall or sunrise rituals from Ars Nouvea or the occultism equivalent, the time of day is not changed. I am uncertain to the underlying cause of it, my only guess is FTB Team Dimensions since there is some sort of syncing between dimensions, but I can not say for certain as this is just a hypothetical guess. 

### Steps to reproduce

1. Place down a ritual brazier with a creative source jar nearby
2. Right click it with the tablet of moonfall or sunrise
3. Right click with an empty hand
4. Observe the ritual being activated
5. Observe once the ritual finishes, that the time did not change

### Expected behaviour

The time of day changes

### Additional information

This was reported by 2-3 players on my server and I confirmed it with Ars Nouveau.

**Comment by Saereth** [comment]
They only work in the lobby, this is a design limitation of ftb dims
