### ISSUE TITLE
Functional Storage Fluid Drawer Infinite liquid dupe when having shield in offhand.

### ISSUE THREAD

**Issue by LucemDivinus** [FTBTeam/FTB-Modpack-Issues#3057]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

When having a shield equipped in the offhand slot and attempting to fill a Functional Storage fluid drawer with a lava bucket (Only tried with lava don't know if it'll work with other liquids.), The shield gets deleted and replaced with an empty bucket, but you also keep the original filled bucket. Once this happens, you enter a state where you can infinitely fill the fluid drawer with the bugged bucket.

### Steps to reproduce

1. Shield in offhand slot, filled bucket in mainhand slot.
2. Block with shield
3. Fill fluid drawer
4. Shield gets deleted and you now have a bugged bucket than can infinitely fill the fluid drawer

### Expected behaviour

Filling the fluid drawer once, emptying the filled bucket in mainhand, not deleting the shield in offhand slot.

### Additional information

A side issue is you can remove the "new" empty bucket from the offhand slot and if you attempt to fill the fluid drawer again you dupe an empty bucket.
A relog fixes this, but interestingly if you use a freshly crafted shield that hasn't been blocked with the bug won't trigger.

**Comment by Saereth** [comment]
https://github.com/Buuz135/FunctionalStorage/issues/165
