### ISSUE TITLE
[Bug] Gamerule playersSleepingPercentage does not work 

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#3058]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Log Files

No specific log.

### Describe the bug

gamerule playersSleepingPercentage does not work properly with multiple players. If configured to 100%, meaning all players online needs to sleep, it reports that 1/1 player sleeps and the night is skipped, even if there are multiple players. Any other percentage also does not work.

It appears overall that regardless of configuration, it only needs 1 player to sleep the night, which is an issue when some parts of the game requires night time. 

### Steps to reproduce

1. Configure the playersSleepingPercentage to any value that would require more than 1 person to sleep normally.
2. Have multiple players on a server
3. Set it to night time
4. Have 1 person sleep, and regardless of the gamerule config, only 1 player is needed to sleep the night

### Expected behaviour

The gamerule works normally

**Comment by FallenRecruit** [comment]
Same problem is happening with FTB Presents F.A.M
