### ISSUE TITLE
[Bug]: Tweak Quests for CobbleForDays # ticks per cobble.

### ISSUE THREAD

**Issue by mellamokb** [FTBTeam/FTB-Modpack-Issues#306]
### Modpack

FTB OceanBlock

### Modpack version

1.7.0

### Describe the bug

The quests for CobbleForDays generators say they make cobble every x amount of ticks.  For example, the Cobble Generator Tier 5 is supposed to be making a cobble every tick.  However, in testing it appears to only make 10 cobble stone every second, so it is really every 2 ticks.  Looking at the source code, it appears that it is better worded it delays by 1 tick every cobble, so that it is in effect every 2 ticks.  Same with Tier 4 is every 6 ticks, Tier 3 is every 11 ticks, etc. because it is the tick *delay* between generating cobble.

I'm not sure if this behavior was intended by the author of CobbleForDays or not, so I wasn't sure if the issue belonged here in the modpack, or with the CobbleForDays repo.  Either the mod needs to be tweaked so it correctly makes cobblestone / tick at the expected rate, or the quest needs to be updated to more accurately describe the behavior, for anyone else who is trying to do the calculations like me :)

Thanks!

### Steps to reproduce

1. Create a Tier 5 CobbleForDays Generator
2. Run the generator directly into a drawer
3. Observe the # of cobble being generated
4. It is only making 10 cobble every second

### Expected behaviour

It should be making 20 cobble every second.

**Comment by Sunekaer** [comment]
Config is set to 1 per tick for tier 5
![image](https://user-images.githubusercontent.com/18720460/141679716-fa7a641a-3d68-4b7b-b8ec-cc2ad02924d7.png)

**Comment by mellamokb** [comment]
Yes, I agree.  But if you look at the wording, "The number of ticks *between* every generation update".  Whereas here's what it says in the Quest Book: "Makes 1 Cobblestone every 1 ticks."

According to what it says in the Quest book, you would expect 20 cobblestone / second.  But if there is 1 tick *between* every generation update, then it would be generating a cobble every other tick, which is 10 cobblestone / second.  If you actually load up a world, plop down a Tier 5 Cobble Gen and watch it output into a drawer, you will see the rate is 10 cobblestone / second.

Don't you agree that is still a little bit misleading?  Hope that makes sense.

**Comment by Sunekaer** [comment]
Yes but reading the code of the mod its meant to be every tick, we are looking at doing a PR to the mod to fix it

**Comment by Sunekaer** [comment]
https://github.com/LexManos/CobbleForDays/pull/18

**Comment by Raidobw2** [comment]
Now available in CobbleForDays-1.3.7.jar
![image](https://user-images.githubusercontent.com/17010632/142169983-1fd3972a-9c7c-4375-85c9-009e308053e5.png)
