### ISSUE TITLE
Personal Shrinking Device not "shrinking"

### ISSUE THREAD

**Issue by MajorGhosty** [FTBTeam/FTB-Modpack-Issues#3062]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

When using the PSD the player visibly shrinks and the hit box changes as well but is unable to walk under blocks.

### Steps to reproduce

1. Open PSD GUI select height.
2. Press "G" to shrink.
3. Walk under blocks.

### Expected behaviour

When shrunk under 0.5 you should be able to walk under blocks or in tight spaces.

**Comment by Saereth** [comment]
I can't reproduce this, its working fine for me. Got a screenshot or something we can go off of?

**Comment by MajorGhosty** [comment]
https://user-images.githubusercontent.com/110222875/231618450-85f2461a-ef6d-4518-b0fe-7040292eefc3.mp4

**Comment by MajorGhosty** [comment]
> 

In the video I shrunk to 0.2 and tried to walk under. This also happens in survival mode.

**Comment by WhitePhant0m** [comment]
are you using the keybind? that has caused that for me, but fixed by just sneaking once after shrinking

**Comment by MajorGhosty** [comment]
Thank you for you're help. Didn't realize it was that simple of a fix. Still weird that you have to crouch after shrinking, never had to do that before.
