### ISSUE TITLE
Task Screen energy acceptance rate

### ISSUE THREAD

**Issue by ogmon1243** [FTBTeam/FTB-Modpack-Issues#3063]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

The "task screen" from ftbquests is the only way to complete the energy quests for the endgame. One of them requires 100B FE to complete but the issue is that these task screens have an energy input limit of 1kFE/t. Getting 100B FE would take literally hours of just sitting around even if you had all that power already. I'm asking to remove the input limit or at least raise it way, way higher.

**Comment by MechBFP** [comment]
Increasing it is already planned for the next update.

**Comment by ogmon1243** [comment]
Ah I made a 7x7 task screen and am inputting power from every side so that’s why my time was shorter.
