### ISSUE TITLE
Add recipe for Red Print (Dank Storage Mod)

### ISSUE THREAD

**Issue by WyFryMU** [FTBTeam/FTB-Modpack-Issues#3064]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

Hello, I want to be able to have 2 Docks on the same frequency and normally you do that with the Red Print item. However, there is no crafting recipe for it in this pack. Could you please add one? Thanks :D
![image](https://user-images.githubusercontent.com/47251130/231348023-a3a6e6d1-e5d3-4665-b2c4-186331d40e67.png)

**Comment by WhitePhant0m** [comment]
Actually the normally you do it by typing the frequency in this
![image](https://user-images.githubusercontent.com/33400200/231447826-a80aa5c3-ab68-4132-82ff-355ce5e83392.png)
and then save it, you do need to unlock the frequency first tho.
