### ISSUE TITLE
FTB Skies crashing on startup

### ISSUE THREAD

**Issue by NGminecraft** [FTBTeam/FTB-Modpack-Issues#3066]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Log Files

[hs_err_pid4580.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11215149/hs_err_pid4580.log)
[hs_err_pid14996.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11215151/hs_err_pid14996.log)

### Describe the bug

My FTB Skies has started crashing whenever I attempt to open it. Every time I attempt to launch it it starts loading as normal but crashes with a memory allocation error. My computer isn't very good, so I might have just ran into it's limits. I tried setting the memory allocation as high as it will go, but it didn't change anywhere, crashed at the exact same spot. I attached to crash report files.

### Steps to reproduce

Press play and wait. Instance memory was at 11.81 GB, and the world size is about 7.5 GB.

### Expected behaviour

It was expected to open up just fine

### Screenshots

![Screenshot 2023-04-12 132544](https://user-images.githubusercontent.com/99756151/231563920-82481e84-d264-4e58-bf0b-9127790beebf.png)

**Comment by Saereth** [comment]
You system has 12121M of ram system wide, you should allocate no more than 8 and preferably 7 or less to java. The pack itself only ever commited 4gb to ram. The bigger issue is your pagefile is nearly full with only 833Mb available out of a 48gb page file. So clear that and it should start working for you. You may have another issue for the pagefile to be so inflated but that is beyond the scope of our support
