### ISSUE TITLE
Levitation stone causes server to crash

### ISSUE THREAD

**Issue by GamingGuyRob** [FTBTeam/FTB-Modpack-Issues#3068]
### Modpack

FTB Skies

### Modpack version

1.0.3

### Log Files

https://pastebin.com/BXXC91DU

### Describe the bug

Using the levitation stone crashes the server

### Steps to reproduce

Go 8K blocks from spawn
Use levitation stone
Crash server

### Expected behaviour

Not crash server

### Additional information

If anyone needs to be whitelisted on my server for testing purposes, I am fine with that. Message me on Discord and I will make it happen

**Comment by Saereth** [comment]
Not a true crash exactly more of a time out and watchdog kills it for taking too long. I've reported this issue to the dev so waiting for them to get a fix in, we may disable the levitation stone until then tbh.

**Comment by Saereth** [comment]
this item is now removed in the new update
