### ISSUE TITLE
Rain Won't Stop, Teru Teru Bozu Won't Fix It

### ISSUE THREAD

**Issue by Morabert** [FTBTeam/FTB-Modpack-Issues#3069]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

It's raining Constantly. Neither Teru Teru Bozu nor Console Commands fixes the problem. This is annoying enough to make me quit the pack.

### Steps to reproduce

1. Be in-game
2. Have it be raining
3. nothing stops it from raining

### Expected behaviour

It to stop training

**Comment by Saereth** [comment]
use the teru teru or console commands in the lobby, not the island dimensions. This is a limitation of ftb dimensions. Sleeping works, as well as does the rain shield (you can craft them or one is given in the questbook once you make a bed)

**Comment by Morabert** [comment]
Neither sleeping nor the teru teru stopped the rain

**Comment by Morabert** [comment]
I started a new world and used the console commands in the lobby, that seems to have done it, we'll see

**Comment by Hazmatik** [comment]
it annoyed me so much that I did /gamerule doWeatherCycle false

I couldn't see any reason to have rain other than a few mana creating flowers and the rain shield only disabled the particles, my bees still knew it was raining
