### ISSUE TITLE
[Bug]: Charged certus quartz crystal duplication bug

### ISSUE THREAD

**Issue by KamiShinku** [FTBTeam/FTB-Modpack-Issues#307]
### Modpack

FTB Oceanblock

### Modpack version

1.5.0

### Describe the bug

When using cardboard boxes on inventories containing charged certus quartz crystals they duplicate and drop on the ground.

### Steps to reproduce

1.place charged certus quartz crystals into an inventory block.
2.place cardboard box on inventory

### Expected behaviour

the certus quartz should not duplicate and drop on the ground

### Additional information

tested with vanilla chests, krates, tinkers crafting station and RFtools modular storage. the modular storage is the only one that did not replicate the bug.

**Comment by Raidobw2** [comment]
Duplicate of #33
