### ISSUE TITLE
Mod function duplication

### ISSUE THREAD

**Issue by UraraChiya** [FTBTeam/FTB-Modpack-Issues#3070]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

I noticed that there are two mods with the same function. moreoverlays ＆ light-overlay. They can both Show Light Overlay.

### Steps to reproduce

- Press F7
- There are two overlays on the ground

### Expected behaviour

Only one overlay

### Additional information

Remove mod light-overlay will fix this issue

**Comment by MechBFP** [comment]
That explains the large performance hit as well when using F7.
