### ISSUE TITLE
Levitation Stone - Only works in Overworld - Not in Dimensions of players

### ISSUE THREAD

**Issue by KoolKat69** [FTBTeam/FTB-Modpack-Issues#3071]
### Modpack

FTB Skies

### Modpack version

1.0.5

### Describe the bug

Get Levitation Stone and use within your dimension 8k+ blocks away. No effects happen. Go to spawn and white smoke/cloud effects work and point to the Castle in the sky,

### Steps to reproduce

Get Levitation Stone
Use in your personal Dimension
No effects happen point to the Castle in the sky
Go to spawn and you see effects happening
First member to go to the castle gets all the loot in overworld leaving other players sad

### Expected behaviour

Should work in their dimension

**Comment by Saereth** [comment]
duplicate issue, known and already reported to the dev

**Comment by KoolKat69** [comment]
> duplicate issue, known and already reported to the dev

Thank you for letting me know. I tried searching for the issue prior to posting this. Is there a thread I can follow within github to track this issue?
Thank you for your time.
-Kool Kat

**Comment by alden-richter** [comment]
@KoolKat69 Found it in the [castle in the sky repo](https://github.com/CarrotOfRivia/castle_in_the_sky/issues/23)
