### ISSUE TITLE
non breaking pedestals

### ISSUE THREAD

**Issue by pokemonkiller90** [FTBTeam/FTB-Modpack-Issues#3072]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

in my worlds i cannot break the pedestals i can make them i can put on the upgrades but it wont let me break them to move them and ive even tried doing it in creative with no luck it wont remove them but im not getting any type of error either

### Steps to reproduce

i dont know how you would reproduce it i dont know if its my file or just a bug but i cant break the pedestals

### Expected behaviour

i should be able to break the pedestals to move them

**Comment by Saereth** [comment]
Do it outside of creative, you cant break them in creative
