### ISSUE TITLE
FTB Skies: Extend Spice of Life Thread

### ISSUE THREAD

**Issue by ratkinson-prh** [FTBTeam/FTB-Modpack-Issues#3074]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

The current settings for Spice of Life allows you to get to 10 hearts pretty quickly. Once there, all of the different food types in the pack become pretty pointless.

Would it be possible to change the settings so that you can get to 20 lives, but the second set of 10 are spread evenly across the last 200 or so foods. That would encourage players to continue building farms, and producing items from the rest of the food-related mods.

### Mod suggestion

Already capable in the current mods, just needs a small tweak to the configs.

**Comment by Saereth** [comment]
good suggestion, added
