### ISSUE TITLE
Industrial Foregoing Fermentation Station voiding products

### ISSUE THREAD

**Issue by Fawkes76** [FTBTeam/FTB-Modpack-Issues#3075]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.7.0

### Describe the bug

When the Industrial Foregoing Fermentation Station has liquid in it's output, it will proceed with processing a new batch of non-like liquid (ie a different ore), and will void it on completion if there is still some other liquid in the output.

### Steps to reproduce

1. use washing factory to process a batch of ore
2. eject to fermentation station and allow to run
3. process a different batch of ore
4. eject to fermentation station, it will run and void product on completion

### Expected behaviour

Fermentation shouldn't commence (or complete) until the output is empty of liquids are not similar.

**Comment by Saereth** [comment]
I've added that machine to the inventory sorting blacklist now in 1.11
