### ISSUE TITLE
Issue when teleporting to  generated "island"

### ISSUE THREAD

**Issue by cylian914** [FTBTeam/FTB-Modpack-Issues#3076]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

i was stuck on some block after rejoining my "island" (see  screenshot)

### Steps to reproduce

1. go in the portal and generate your "island"
2. do /spawn
3. go to the portal

### Expected behaviour

Teleporting the player at the ceneter of the "island"

### Screenshots

![2023-04-12_22 45 01](https://user-images.githubusercontent.com/73445993/231581629-8dccf60e-33a2-46e7-9d3b-9f989c13d740.png)

**Comment by UnRealDinnerbone** [comment]
I'm unable to reproduce this issue, please upload your log files debug and latest. And also did you do anything else with creating more island or anything else before the issue happened
