### ISSUE TITLE
Quest book description not accurate for Laser amplifier

### ISSUE THREAD

**Issue by Mizuga** [FTBTeam/FTB-Modpack-Issues#3077]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

Last paragraph of the quest book entry for the quest Laser amplifier under the mekanism quest tree has an inacuracy : 

"You can extract this with a Universal Cable configured to pull."

this suggest using a Universal Cable from Mekanism but in reality you have to use a Universal Pipe from Pipez

### Steps to reproduce

1) open quest book entry for laser amplifier under the Mekanism quest tree
2) read last paragraph

### Expected behaviour

Either change cable to pipe in the quest description or make the correct cable work

### Screenshots

![image](https://user-images.githubusercontent.com/114857102/231792250-cad199af-1fef-4e61-80ee-f3a607b18ab3.png)
![image](https://user-images.githubusercontent.com/114857102/231792451-ac9d279c-c9b7-428f-838e-8e8553b0780c.png)
![image](https://user-images.githubusercontent.com/114857102/231792841-ea17e86b-7e43-436f-9ee6-db7a86138a0d.png)

### Additional information

in screen n°3 only the universal pipe is actually pulling energy from the laser amplifier

**Comment by Saereth** [comment]
Your universal cables are not configured to extract mode.
