### ISSUE TITLE
wand of the forest quest dependent on unrelated quest

### ISSUE THREAD

**Issue by dragoonwiza** [FTBTeam/FTB-Modpack-Issues#3078]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

the completion of the wand of the forest quest is dependent on the completion of the chop chop quest

there is no indication or clear reason on why these two quests are linked 

### Steps to reproduce

complete quest up to wand of the forest
make wand
quest doesnt complete
complete quest chop chop
both wand and chop chop quests will complete

### Expected behaviour

remove the dependence for the chop chop quest or make it clear that you need to do it in order to complete wand of the forest quest

**Comment by Nerdtality** [comment]
Was this fixed, still happens in FTB Skies 1.3.2
