### ISSUE TITLE
New 1.8.0 version still crashes Game, Instance and FTB App when opening a world

### ISSUE THREAD

**Issue by IsaacTheII** [FTBTeam/FTB-Modpack-Issues#3079]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.8.0

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11225531/debug.log)

### Describe the bug

On opening a world the game proceeds as normal with reading world data etc. etc. until it displays the "joining world" text where it now will freeze and the window title will display "(Not Responding)". After 30sec-1min the instance will crash and after further few seconds the FTB App will then also crash.

same issue as before
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3067#issue-1665438694

### Steps to reproduce

1. Open FTB DW20 1.19 instance
2. Open world
3. wait for few seconds for the crash

### Expected behaviour

launch world

### Additional information

As mentioned by @Saereth it looked like the bug was similar to the bug with FTB Skies and should be resolved but after updating to 1.8.0 it still crashes. Maybe there is some other additional issue as well. I attached a new debug.log file from the updated version.

**Comment by Saereth** [comment]
Try disabling line together?

**Comment by IsaacTheII** [comment]
Still crashes, even after disabling minetogether.
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11225715/debug.log)
here is the new log

**Comment by Saereth** [comment]
Sorry can you also disable the polylib mod it depends on

**Comment by IsaacTheII** [comment]
No sry, it still crashes. I also had to disable blockshot and ftbbackups2 since both depend on the polylib mod.
here the corresponding log. 
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11225853/debug.log)

**Comment by IsaacTheII** [comment]
I was able to fix my issue. At least for now it works. Seems like something corrupted the game files. Since i didn't find any thing else that that helped with this kind of issue, I'll leave my solution here.
disclaimer: I'm not a modder nor am I particularly familiar with the minecraft code. So my approach is most likely completely backwards. 😀
Also this approach only works if selected Worlds are kaput and not if the entire instance is bugged. 

1. Re-Create the broken World. 
2. Open the new world and save it.
3. Then navigate to your instance folder ($USER/AppData/Local/.ftba/instances/$your-instance) and then to the broken World in the saves Folder.
4. Now, bisection replace half of the folders in your newly re-created save world with the corresponding folders from the broken world.
5. Open the new world. If it crashes then you found the broken section and revert it back and sub divide further by repeating from step 4 on that broken section. If it didn't crash, you're good and all of these folders you replaced should work properly. now you can replace the second half of the folders. and repeat this step. (if both sections seem to work, you/file-explorer/nbt-data-explorer probably didn't save the changes or you mixed up the sections. no worry just go back an iterations and keep replacing till something breaks)
6. If you keep doing step 4 and 5 you will eventually narrow it down to one folder. Then you do the same for all the files in that folder and then for all of the content/lines of that file. 
7. Try to patch the broken files/lines in the original World file as best you can. For me the affected file was the level.dat and further more most likely something with the wandering trader tags. So i used and NBT explorer to replace and change the nbt data.) 
8. If it still breaks might have multiple broken files/lines. Restart from step 4. and focus on the sections that are not yet replaced.
9. Done. Hopefully you're all set and good to play.

@dev's feel free to close this issue if this is a one-off issue and does not seem to affect other players. Also thank you for your amazing work and dedication to this game. ❤ Me and my kids are really enjoying playing together in our LAN world.👍

**Comment by Saereth** [comment]
glad this is working for you now, I havent gotten any other reports like this and cant reproduce it so I guess I'll close for now, will reopen if we see other reports like it
