### ISSUE TITLE
[Bug]: Cannot create Sulfur Dust inside a Mekanism Crusher, but Pulverizer works

### ISSUE THREAD

**Issue by Insequearaux** [FTBTeam/FTB-Modpack-Issues#308]
### Modpack

FTB OceanBlock

### Modpack version

1.7.0

### Describe the bug

You are not able to create sulfur dust in a mekanism crusher, and I am assuming this is a bug because it works in the Thermal Series pulverizer

### Steps to reproduce

1. check JEI
2. its not there
3. try to put sulfur in the crusher
4. it doesnt work
5. put sulfur in pulverizer
6. it works

### Expected behaviour

you should be able to get sulfer dust with the crusher

**Comment by quietust** [comment]
The main consequence of this is that it makes the production of sulfuric acid (whether for ore quintupling or for fissile fuel production) much more resource-intensive, since pulverizers are rather slow (and the only speedy alternative is to craft very large quantities of earth charges).
