### ISSUE TITLE
Quest Book Reset

### ISSUE THREAD

**Issue by SirNiklas15** [FTBTeam/FTB-Modpack-Issues#3080]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

Questbook was set back to the start after i launched the game again the next day.

### Steps to reproduce

Play, clear a few quests, save, quit, launch again, all gone

### Expected behaviour

For it not to reset

**Comment by MikesNameIsMike** [comment]
This happened to me also.  I paused the game for about an hour.  Came back, unpaused, and it wasn't responding so I just shut it down.  Reopened the game and my quest book was completely reset.

**Comment by Saereth** [comment]
looks like removing the smoothchunks mod in a recent update fixes this
