### ISSUE TITLE
Lag Issues

### ISSUE THREAD

**Issue by WoahItzJackson** [FTBTeam/FTB-Modpack-Issues#3081]
### Modpack

FTB Skies

### Modpack version

1.1.4

### Describe the bug

Hi, I have a gaming laptop that's normally good with modpacks but this one not so much. i have a nitro 5 laptop. when it first came out I had no lag but these recent last two updates really gave a lot of lag, I've done loads of techniques to stop this but it didn't work. Is there anything that can fix this issue or any help that I can get? Thank you.

### Steps to reproduce

Im not sure how you can fix this issue, maybe comments in the comment section can help?

### Expected behaviour

Not much lag

**Comment by Saereth** [comment]
let me know if its better now in 1.7.0 if not we'll need you to run spark and provide some profiling data
