### ISSUE TITLE
No Map When spawning into a new world and making an island

### ISSUE THREAD

**Issue by Smallchild83** [FTBTeam/FTB-Modpack-Issues#3083]
### Modpack

FTB Skies

### Modpack version

1.0.5

### Describe the bug

When me and a friend booted the pack and went into a world it looked good, but when we made a island no island spawned and we where in the void

tested with with several island types to be sure i'm not crazy 

### Steps to reproduce

create a world
make a island
get teleported and no island appears 

### Expected behaviour

i expected to spawn in and be on an island

**Comment by glektarssza** [comment]
I've seen this behavior too in 1.0.4 and 1.0.5. Rebooting the game solved it but that suggests, to me, that it's an initialization bug or race condition that doesn't occur every time the game starts up.
