### ISSUE TITLE
Server installation (FTBInstall.sh) fails. Error 403 jar file cant be downloaded

### ISSUE THREAD

**Issue by Alex000ch** [FTBTeam/FTB-Modpack-Issues#3084]
### Modpack

FTB Infinity Evolved 1.7

### Modpack version

latest 3.1.0

### Describe the bug

When installing the Server version of the Modpack i run the FTBInstall.bat (.sh) script and im getting an 403 Error that the server cannot be accessed.

It seems that the AWS where the .jar File is located is messed and cannot be accessed.

Following Error is shown in Commandline:

--2023-04-13 21:42:11--  https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/minecraft_server.1.7.10.jar
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.198.72, 52.216.210.208, 52.217.90.22, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.198.72|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-04-13 21:42:12 ERROR 403: Forbidden.

And when i try to access the URL of this Server im getting an XML with "Access Denied"-

### Steps to reproduce

1. Installing Server Version of the Modpack by launching FTBInstall.bat (or .sh) in Console.
2. Getting Error with 403

### Expected behaviour

File should be downloaded

**Comment by FaultyPine** [comment]
having the same error

**Comment by claick-oliveira** [comment]
+1

**Comment by Gaz492** [comment]
This issue should be resolved now.
