### ISSUE TITLE
FTB Skies crash on loading world - 1.0.5

### ISSUE THREAD

**Issue by GlobalGamer2015** [FTBTeam/FTB-Modpack-Issues#3088]
### Modpack

FTB Skies

### Modpack version

1.0.5

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11227157/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11227158/latest.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11227159/console.log)

### Describe the bug

After clicking to load world, Minecraft entirely crashes.

![image](https://user-images.githubusercontent.com/19220996/231902050-2c4d34aa-44a8-4923-9158-611682f7b3ff.png)

### Steps to reproduce

1. Update to 1.0.5
2. Load pre-existing world from 1.0.4
3. Wait for crash.

### Expected behaviour

Load world and not crash.

**Comment by 5ully** [comment]
Can you upload the crash log too?

**Comment by GlobalGamer2015** [comment]
The log from the FTP App?

**Comment by GlobalGamer2015** [comment]
From the "latest.log".

I'm seeing issues relating to LootTables, Apotheosis enchantment, and Everlasting Abilities.

**Comment by TheDirepack** [comment]
I have the same problem
here's my log files
[crash-2023-04-14_01.27.52-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11229077/crash-2023-04-14_01.27.52-server.txt)
I did add
cabletiers-1.19.2-0.5471, EdivadLib-1.19.2-1.2.0, ExtraStorage-1.19.2-3.0.1, rebornstorage-1.19.2-5.0.3, refinedstorageaddons-0.9.0, RSInfinityBooster-1.19.2-3.0+27, rsrequestify-2.3.0
didn't brake 1.0.4 
here's it without those mods
[crash-2023-04-14_01.37.10-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11229108/crash-2023-04-14_01.37.10-server.txt)

**Comment by Snowydraco** [comment]
Im having the issue too here is my crash nothing added
[crash-2023-04-14_06.28.39-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11231791/crash-2023-04-14_06.28.39-server.txt)

**Comment by GlobalGamer2015** [comment]
Looks like "EverlastingAbilities-1.19.2-2.0.0.jar" is causing the main issue for us.

I managed to load into my world with no further issues.

**Comment by Saereth** [comment]
addressed in hotfix 1.0.6
