### ISSUE TITLE
[Skies 1.0.5] Items dropped by Botania Open Crate do not trigger pressure plates

### ISSUE THREAD

**Issue by glektarssza** [FTBTeam/FTB-Modpack-Issues#3089]
### Modpack

FTB Skies

### Modpack version

1.0.5

### Describe the bug

When constructing a basic Endoflame setup I tend to use a hopper feeding an Open Crate from Botania with a pressure plate underneath. Redstone links the hopper to the pressure plate to turn the hopper off when something is waiting to be consumed by the Endoflames. As of v1.0.5 it seems items dropped from an Open Crate won't trigger pressure plates but items tossed from a player's hand will. I also tried with a Chute from Quark and that also does not trigger any pressure plates.

### Steps to reproduce

1. Set up a simple Redstone contraption as pictured:

![2023-04-13_18 31 18](https://user-images.githubusercontent.com/94402525/231911460-641bc224-682f-4520-aee6-15f8760710ac.png)

2. Place items in the hopper.
3. Observe pressure plate behavior as items are dropped onto it.
4. Throw items onto the pressure plate manually.
5. Observe pressure plate behavior.

### Expected behaviour

Pressure plate is triggered, producing a Redstone signal.

### Screenshots

Items dropped from Quark Chute, no Redstone signal.

![2023-04-13_18 28 51](https://user-images.githubusercontent.com/94402525/231911250-3470022b-53bc-48bf-8cd4-7866abbfb5a9.png)

Items dropped by hand, Redstone signal.

![2023-04-13_18 29 34](https://user-images.githubusercontent.com/94402525/231911319-3d1446ed-557e-4a13-850e-5aca254f6534.png)

**Comment by glektarssza** [comment]
Turns out this "bug" was being caused by my Open Parties and Claims config preventing pressure plates from being interacted with by non-player owned entities. Closing as not actually a bug.

**Comment by Maple-Kade** [comment]
how did you fix it?

**Comment by glektarssza** [comment]
> how did you fix it?

I disabled chunk protection on claimed chunks.

**Comment by adkinss** [comment]
I saw the same issue and came here to find that Open Parties and Claims was the culprit.  If you run into this issue, it can be fixed pretty easily without affecting your other claim and chunk settings by going to "My Player Config" (hit single quote to open the config menu) and turning off "Prot. Plates from Other".

**Comment by kallezz** [comment]
I turned every single plate protection option off from every config I could find and pressure plates are still not working. Any ideas?

**Comment by adkinss** [comment]
What if you unclaim the chunk, does it start working then?

**Comment by kallezz** [comment]
> What if you unclaim the chunk, does it start working then?

I fixed the issue after some headache.. apparently the server config files don't matter at all, you have to change the protectplates config with ingame commands and then it worked.

**Comment by Dragon2558** [comment]
> > What if you unclaim the chunk, does it start working then?
> 
> I fixed the issue after some headache.. apparently the server config files don't matter at all, you have to change the protectplates config with ingame commands and then it worked.

What are the command(s)?
