### ISSUE TITLE
[Suggestion]: [OceanBlock] add Convenient curios container

### ISSUE THREAD

**Issue by TupacTheLazy** [FTBTeam/FTB-Modpack-Issues#309]
### Modpack

OceanBlock

### Is your suggestion related to a problem? Please describe.

There's a bunch of mods that adds their own trinkets and management can be annoying.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/convenient-curios-container

it gives an easy way to swap trinkets and manage them.

**Comment by Sunekaer** [comment]
Hi
Thanks for the suggestion but we are not looking to add more to the pack
