### ISSUE TITLE
crafting table dupe

### ISSUE THREAD

**Issue by huskyvenom** [FTBTeam/FTB-Modpack-Issues#3090]
### Modpack

FTB Skies

### Modpack version

1.0.5

### Describe the bug

I keep putting enough resources to make one of something and when I click the made item it stacks to 64.

### Steps to reproduce

1. put the resources into a vanilla crafting table to make one and then get a stack of 64

### Expected behaviour

I didnt expect to get a 64 stack

**Comment by koalalord9999** [comment]
Testing myself, this is game breaking if it works... LOL

**Comment by CrimsonXMC** [comment]
> Testing myself, this is game breaking if it works... LOL It doesn't work in 1.0.4 - so something that got updated messed it up. And it does work in 1.0.5

it also works in the regular inventory crafting LOL

**Comment by Mowmaster** [comment]
Can confirm, this bug only exists in v1.0.5
