### ISSUE TITLE
Massive Lag Spike when entering Sky Villages

### ISSUE THREAD

**Issue by BigBadShay** [FTBTeam/FTB-Modpack-Issues#3093]
### Modpack

FTB Skies

### Modpack version

1.0.5 - 1.0.6

### Describe the bug

Ever-increasing lag when entering a sky village. I've just entered a village for the first time and it instantly began to lag. Exiting and re-opening the instance rectifies the issue for a couple minutes but as villagers mill about it goes from slideshow to completely froze. I have no shaders enabled, I've tried minimizing rendering and graphical setting but it only delays the issue. The moment I'm far enough away for the villagers to de-render the issue resolves. Issue persists into 1.0.6. Appeared resolved at first, then returned at nightfall.

Update: Issue also appears in nether villages. Attempted "/kill @e[type=!player]" to confirm if issue was entity related. No change. Lag continued to increase until near complete freeze (Upwards of 10 second between pressing Escape and menu opening but lag abates after a few minutes in-menu). When attempting previous fix to exit and reload, instance will lock up, console giving multiple UncaughtExceptionHandler errors while trying to load the world. The only way to reload is to completely kill the instance and restart.

### Steps to reproduce

Get within render distance of a villager.

### Expected behaviour

smooth operation

**Comment by Saereth** [comment]
i'm unable to reproduce this currently, if anyone else has more info please let me know

**Comment by Makekith** [comment]
I cannot confirm whether it is to do with a Sky village or not but my spawn intersected with one and over time the game lag builds to unplayable levels (e.g. 10s to eat an apple).

**Comment by Saereth** [comment]
with version 1.1.0+ of the pack login and run
/modernfix upgradeStructures
should sort it now
