### ISSUE TITLE
Keeps Crashing since v1.0.2 - 1.0.5

### ISSUE THREAD

**Issue by JoshuaBalles** [FTBTeam/FTB-Modpack-Issues#3096]
### Modpack

FTB Skies

### Modpack version

1.0.5

### Log Files

I do not know which log file to send so here's the whole logs folder in a [zip](https://1drv.ms/u/s!ArTE_M3hEMX_hPoAIyh3HmZNhQcmYw?e=p73l25) file.

### Describe the bug

I have been getting numerous crashings since v1.0.2 up until the current version 1.0.5 and I could not figure out why. I have my memory set to 8GB and I have also attatched a screenshot of my pc's specs if it is of any help.

### Steps to reproduce

Unsure how to reproduce it because it happens at random intervals.

### Expected behaviour

Minecraft instance crashes

### Screenshots

![system](https://user-images.githubusercontent.com/79013822/232001126-0e56ec04-a147-4ceb-90f7-3d8a9ba45649.jpg)

**Comment by heolo1** [comment]
Have also been experiencing this. RAM usage is normal for a while (6-7 GB), then randomly shoots up. I allocate 10 GB of RAM to FTB Skies, and then it sometimes randomly eats up everything left on my computer. I think it went up to 19 GB used at once once. This large memory usage is usually accompanied by a couple of frameskips corresponding to allocating large amounts of RAM. Most likely a memory leak. Playing on v1.0.4.

**Comment by heolo1** [comment]
![Screenshot_2023-04-14_23-12-38](https://user-images.githubusercontent.com/95734779/232189939-b5c51b1c-0f5c-4269-aa91-013305766c68.png)
Image related, this is now on v1.0.6

**Comment by heolo1** [comment]
![Screenshot_2023-04-14_23-15-50](https://user-images.githubusercontent.com/95734779/232190043-8e3d8d07-5719-4e66-876f-f2f2af637c27.png)
This is immediately before pressing the quit button in the main menu on an instance where the OutOfMemoryError has occurred

**Comment by heolo1** [comment]
![Screenshot_2023-04-14_23-16-12](https://user-images.githubusercontent.com/95734779/232190122-a740716c-6cfb-4c4f-991c-558f7271d608.png)
This is immediately after

**Comment by heolo1** [comment]
![Screenshot_2023-04-14_23-17-52](https://user-images.githubusercontent.com/95734779/232190143-3869a437-05ec-4fe8-8c84-2dd43b4aae72.png)
This is immediately after

**Comment by heolo1** [comment]
![Screenshot_2023-04-14_23-18-42](https://user-images.githubusercontent.com/95734779/232190178-750038ae-5857-4cdd-9a4d-4ae91ee57409.png)
This is immediately after without closing any other processes
