### ISSUE TITLE
Going to the Nether Deletes Overworld

### ISSUE THREAD

**Issue by AlchemicPhoenix** [FTBTeam/FTB-Modpack-Issues#3102]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

I found that when I go to the Nether through the portal my island gets deleted. If I go back through the portal I spawn a new portal in the overworld with the ship about thousands of blocks away, like x25,000 z36,000. If I go to the nether and try to use /ftbdim home, it says I have to go to the overworld and use the portal to make my home. I think I started the pack in version .2 or version .3, not sure. I've used backups to restore my island to continue playing and just avoided going to the nether. I tried going after a while and had the same results and discovered that the backup from before I even built the portal did not delete the nether or the ship overworld spawned nether portal. So I have a fully looted nether structure but no items from it.

### Steps to reproduce

1. Build portal
2. Go through portal
3. No more island world

### Expected behaviour

Island dimension deleted

### Screenshots

![2023-04-14_11 26 22](https://user-images.githubusercontent.com/50083962/232102788-7861ef20-9028-42d2-9a29-c74c42b8fb93.png)
![2023-04-14_11 26 53](https://user-images.githubusercontent.com/50083962/232102896-4f4635a2-1456-4e58-92ea-94612618fa9c.png)
![2023-04-14_11 28 07](https://user-images.githubusercontent.com/50083962/232102933-5361a706-0f15-496c-90c0-3820abb17a8f.png)

**Comment by Saereth** [comment]
this was a bug that is now resolved but you will need to have your world repaired, please email Mikey at mikey@feed-the-beast.com with your level.dat and ftbteamdimensions-dimensions-store.dat files from your save folder and he'll send you back the repaired file.

**Comment by AlchemicPhoenix** [comment]
@Saereth I emailed Mikey the files and he replied saying "Hi, please follow up with Saereth, I have reviewed your files but unfortunately (or fortunately depending on how you look at it) they are healthy and should be fine. You’ve liked found a new issue with the mudpack." 
Is there something else that can be done to resolve this issue?
