### ISSUE TITLE
FTB SKIES Sifter not sifting anything 

### ISSUE THREAD

**Issue by JackWayne3** [FTBTeam/FTB-Modpack-Issues#3103]
### Modpack

FTB Skies

### Modpack version

1.05

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11235250/latest.log)

### Describe the bug

Before I updated to 1.0.4, the sifter was working. Ever since I updated to 1.04 and even now at 1.05 the sifter still does not work. It does the animation but the blocks don't produce results through the meshes. 

### Steps to reproduce

1. Download version 1.02
2. Update to version 1.04 
3. Run FTB SKIES
4. Try to use the sifter

### Expected behaviour

Expected the input to produce an output in the sifter

### Additional information

I suspected that a lack of scripts may be the issue, however I do not know where to find those.

**Comment by Saereth** [comment]
sounds like your upgrade had issues, I'd do a fresh install and just bring your world over. The scripts are in your installation folder in the kubejs folder
