### ISSUE TITLE
ftb skies不支持 modern ui？

### ISSUE THREAD

**Issue by denke123** [FTBTeam/FTB-Modpack-Issues#3105]
### Modpack

FTB Skies

### Modpack version

1.0.5.1

### Log Files

[crash-2023-04-15_00.03.18-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11235401/crash-2023-04-15_00.03.18-client.txt)

### Describe the bug

Does FTB Skies not support modern UI? I joined the modern ui and it couldn't start

### Steps to reproduce

Does FTB Skies not support modern UI? I joined the modern ui and it couldn't start

### Expected behaviour

Does FTB Skies not support modern UI? I joined the modern ui and it couldn't start

**Comment by Saereth** [comment]
yeah it doesnt, skies uses fancy main menu which isnt going to be compatible
