### ISSUE TITLE
duplication bug

### ISSUE THREAD

**Issue by alienfisheater** [FTBTeam/FTB-Modpack-Issues#3106]
### Modpack

FTB Skies

### Modpack version

1.0.5

### Describe the bug

While using a crafting table, right clicking the crafted item out of the grid will produce a stack of this item

### Steps to reproduce

Insert one flax into crafting grid
right click 64 string out.

### Expected behaviour

I expected a one for one transaction. I recieved a better deal.

**Comment by ttechr** [comment]
Already been reported. #3090
