### ISSUE TITLE
[Suggestion]: Mod Addition (LazierAE2)

### ISSUE THREAD

**Issue by Ghost-Asood** [FTBTeam/FTB-Modpack-Issues#311]
### Modpack

FTB OceanBlock

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/lazierae2

**Comment by Sunekaer** [comment]
Thanks for the suggestion but won't be added.

**Comment by Ghost-Asood** [comment]
is there a reason for that?

**Comment by Raidobw2** [comment]
The modpack has reached a size that's considerable, we don't want this to turn any heavier. Almost all mod suggestions get turned down at this point, it's normal. You might want to use Refined Storage if you want a "lazier" way to get your storage working, it has bigger crafters iirc.

If you need tips concerning AE2, pass by the FTB Discord and ping me (R3GEN) with screenshots of the problems you think could be improved. I'll hit you up with solutions for automating it, I'm a pro at the mod ;D

**Comment by Ghost-Asood** [comment]
I also am a pro at AE2, my point from adding it was to make the automation easier and takes less space.
Also grinding for that mod items is fun ...
