### ISSUE TITLE
Easy Villagers Visual glitch

### ISSUE THREAD

**Issue by HoboClownsShoe** [FTBTeam/FTB-Modpack-Issues#3113]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

All the Easy Villager blocks no longer display correctly in JEi or when placed on the ground. 
The Breeder, Converter & Iron farm do show partially, the breeder show the bed for example but the framing, glass and floor are missing  

### Steps to reproduce

Search for  "@easy" in JEI

### Expected behaviour

each block should look similar to the Barterer block from the East Piglins mod

### Screenshots

![image](https://user-images.githubusercontent.com/130802972/232167239-0c389466-145d-445b-b5c9-bcece59fcbdf.png)

![image](https://user-images.githubusercontent.com/130802972/232167333-4a12a18e-2fcd-4a16-b4c1-91a826a36a9b.png)

**Comment by EvilEpicPanda** [comment]
Was fixed by mod, just needs to be updated in the pack.

https://github.com/henkelmax/easy-villagers/issues/155
