### ISSUE TITLE
Add Iron Furnaces to FTB Skies

### ISSUE THREAD

**Issue by tsGod** [FTBTeam/FTB-Modpack-Issues#3114]
### Modpack

FTB Skies

### Mod Suggested

IronFurnaces

### Additional Information

FTB Skies has Iron Barrels and IronChests, it would be great if it had IronFurnaces as well. Having IronFurnaces adds greater early game variety and would help to bridge the progression gap between the vanilla furnace and the rf powered furnace options such as those from Thermal or Mekanism.

If this is not the right place for this suggestion please let me know where this type of suggestion should be made.

### Mod suggestion

https://github.com/Qelifern/IronFurnaces

**Comment by CrimsonXMC** [comment]
I agree with this suggestion, vanilla furnaces are painfully slow.

**Comment by melbellrocks** [comment]
I am into Mekanism now so it's too late for me (lol), but I agree with this suggestion for earlier game.  More furnace options would have been great!

**Comment by Saereth** [comment]
Already suggested but there are already fast smelting methods in the pack, create, forcecraft, mekanism etc are all available early
