### ISSUE TITLE
Duplication in Hexerei sky village.

### ISSUE THREAD

**Issue by WizoAtonz** [FTBTeam/FTB-Modpack-Issues#3115]
### Modpack

FTB Skies

### Modpack version

1.0.4 &1.0.6

### Describe the bug

I right clicked on a Witch Hazel Drying Rack with my Elusive Immolation Blade of Distant Battles. I then broke the drying rack with left click and suddenly I had an exact copy of my sword. I did this in both 1.0.4 and 1.0.6 versions of the pack. 

### Steps to reproduce

1 go to a Hexerei sky village.
2 Enter a witch house with a drying rack in the back corner or the house.
3 Right click on the drying rack with you Immolation blade in your main hand.
4 Punch the drying rack to break it. 

### Expected behaviour

I expected the drying rack to drop my sword and the leather that was in it. I got two swords and the leather.

**Comment by CrimsonXMC** [comment]
This is already reported under https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2985

**Comment by WizoAtonz** [comment]
Sorry for the duplicate issue, I did a search but didn't find anything. I
must have not used the right search terms.
