### ISSUE TITLE
Request to become maintainer.

### ISSUE THREAD

**Issue by bookerthegeek** [FTBTeam/FTB-Modpack-Issues#3116]
### Modpack

FTB Revelation

### Is your suggestion related to a problem? Please describe.

FTB Revelation seems to be missing a maintainer. I would like to volunteer to become the maintainer for this pack. 

### Mod suggestion

Update the mods in the pack (There are more mods needing updates in the pack then not needing one)

Replace Mods:
AE2 with [AE2 Unofficial Extended Life](https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life)
Baubles with [Baubles-LTS](https://www.curseforge.com/minecraft/mc-mods/baubles-lts)

Add in the mods:
[Integrated Dynamics](https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics)
[Integrated NBT](https://www.curseforge.com/minecraft/mc-mods/integrated-nbt)

**Comment by MichaelHillcox** [comment]
Sorry, we are currently not looking for anyone to take over our packs. If you have a request for specific mods to be added, replaced, etc for a specific reason, please create a new issue stating your reasoning and if they're compatible with the pack and our team will take a look into it
