### ISSUE TITLE
Dreadful and delightful dirt no longer spawn mobs

### ISSUE THREAD

**Issue by smemasmem** [FTBTeam/FTB-Modpack-Issues#3119]
### Modpack

FTB Skies

### Modpack version

1.0.5, 1.0.6

### Describe the bug

I set up 3 mob farms, 1 delightful dirt farm, 2 dreadful dirt. one in my team dimension and one in the nether. These were created when i was on modpack version 1.0.4. I used them to collect hundreds of blaze rods and wither skeletons, raw food, feathers, etc. 

As of updating to 1.0.5 and now to 1.0.6 not a single mob spawns in the exact same farms I used to use. I did not touch the farms after updating in any way or modify them at all. But they no longer work. 

### Steps to reproduce

1. Download 1.0.4 version of modpack
2. build a mob farm using delightful or dreadful dirt
3. collect resources
4. update to 1.0.5 or 1.0.6 
5. notice that your mob farm no longer spawns mobs.

### Expected behaviour

Both delightful and dreadful dirt would continue to spawn mobs as they had prior to updating to 1.0.5+

**Comment by MechBFP** [comment]
They still spawn mobs it is just much slower/normal than before.

**Comment by melbellrocks** [comment]
We thought we were having an issue too and I noticed that they started spawning again when I removed my Mega Torch.  It used to ignore a mega torch and now it seems to honor it.  If you have one nearby try removing it and see if it works.

**Comment by MidwinterMakes** [comment]
Been having an issue with Delightful Dirt, it seems to only be spawning Drygmys and Starbuncles, anyone know why?

**Comment by Zoidey** [comment]
Yeah I've been having issues also, at first it works really well then it slows down and only spawns Drygmys, Starbuncles and the other flying one on mass then after a while it stops spawning even then, I sat here and watched for like 10 to 15 minutes and not a single thing spawn, was like watching paint dry or grass grow.

If you dig up the dirt and use another golden egg on it to spawn it starts working again but then slows down until it stops spawning anything.

**Comment by MechBFP** [comment]
> Yeah I've been having issues also, at first it works really well then it slows down and only spawns Drygmys, Starbuncles and the other flying one on mass then after a while it stops spawning even then, I sat here and watched for like 10 to 15 minutes and not a single thing spawn, was like watching paint dry or grass grow.
> 
> If you dig up the dirt and use another golden egg on it to spawn it starts working again but then slows down until it stops spawning anything.

Are you getting rid of the grass that grows on it? The grass stops spawns.

**Comment by Zoidey** [comment]
Ah, I never thought that the grass would have stopped it but kinda makes sense asdigging it all up and reapplying the golden egg to make it work again makes sense if it's the grass that's stopping it from working.
