### ISSUE TITLE
[Bug]: oceanblock keeps crashing 

### ISSUE THREAD

**Issue by Dakmon85** [FTBTeam/FTB-Modpack-Issues#312]
### Modpack

oceanblock

### Modpack version

1.16

### Log Files

there is no log files

### Describe the bug

when im typeing in refine storage it will crash it did give a code 0 and now it dont do that 

### Steps to reproduce

when im typeing in refine storage it will crash it did give a code 0 and now it dont do that 

### Expected behaviour

when im typeing in refine storage it will crash it did give a code 0 and now it dont do that

**Comment by Raidobw2** [comment]
Refer to #40 I've written the solution on the last comment. We'll see if we can improve that for new users by disabling it.
