### ISSUE TITLE
Crashing on world load-in

### ISSUE THREAD

**Issue by Redstoner875** [FTBTeam/FTB-Modpack-Issues#3120]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11238424/latest.log)

### Describe the bug

When loading into a world on version 1.0.6, my UI and hotbar renders while the world does not. After a few seconds the game crashes. I give the modpack 12 gigs and have a total of 32 gigs of ram total. I've experienced no issues from 1.0.0 to 1.0.4, once updating to 1.0.6 the crashes started occurring. This happens both when loading into a server and a single-player world.

### Steps to reproduce

N/A

### Expected behaviour

Being able to load in

**Comment by Saereth** [comment]
need your crash logs, there is no crash report in that log file you submitted
