### ISSUE TITLE
Must double click island choice on world start, otherwise an island does not spawn for you.

### ISSUE THREAD

**Issue by Kandarth** [FTBTeam/FTB-Modpack-Issues#3121]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

Just starting this pack, and I go to create a world, put in my settings, and it seems all good. Then I go through the portal to select an island type, and I selected "FTB Sky Island" and hit the create button.

This started an endless loop of falling from the very top of the world to the very bottom of the world, over and over again. No island was created. I successfully recreated this 7 different times on 7 different worlds. 

What finally allowed me to start playing?

DOUBLE CLICKING THE F***ING WORLD TYPE I WANTED.

### Steps to reproduce

1. Load FTB Skies
2. Start new world
3. Go to island creation portal
4. Single click the island you would like to use
5. Click the "create" button at the bottom of the selection screen
6. Enjoy falling forever as your island is never created.

### Expected behaviour

You fall forever. Your island never appears.

**Comment by Saereth** [comment]
this should be resolved now
