### ISSUE TITLE
Dissappearing Items

### ISSUE THREAD

**Issue by Elgato8725** [FTBTeam/FTB-Modpack-Issues#3125]
### Modpack

FTB Skies

### Modpack version

1.0.4-1.0.6

### Describe the bug

Items are disappearing from my inventory, primarily from the force pack given at start. Examples of items that have gone missing from said force pack are my personal shrinking device, my buckets, and more. Not sure the cause or how to stop it from happening.

### Steps to reproduce

Unclear

### Expected behaviour

Items stay in inventory

### Additional information

Please help

**Comment by Saereth** [comment]
I've tried to recreate this a couple times now to no avail :-/ If you can find any more information that might help us reproduce the issue please reopen this issue and we'll look into it further.
