### ISSUE TITLE
Dupe bug with supplementaries jar and create honey bucket

### ISSUE THREAD

**Issue by dittymargoo** [FTBTeam/FTB-Modpack-Issues#3133]
### Modpack

FTB Skies

### Modpack version

1.0.5

### Log Files

sorry but I don't think this is a log file issue

### Describe the bug

I (perhaps foolishly) tried to take honey out of a Supplementaries jar with a bucket and put it in a Functional Storage fluid drawer.  The honey would be added to the drawer.  I could see the three empty buckets in my hot bar, but the moment I opened my inventory they would magically refill and duplicate in the top right slots in my inventory.  The honey filled bucket is noted as a Create honey bucket.  At the time I had also taken my Mekanism refined obsidian shield out of my offhand and put it in the first slot (top right) in my inventory - this was deleted/overwritten by the duping honey buckets.

### Steps to reproduce

1.  Fill a Supplementaries jar with honey and take some out with a bucket.
2.  Try to empty the bucket into a Functional Storage fluid drawer.
3.  Watch the bucket magically refill again when you open your inventory.

### Expected behaviour

I'm not sure...a bucket that stays empty, doesn't refill, doesn't duplicate or delete items.

### Additional information

I checked to see if the latest version/update involved any of these mods.  But I have not updated yet as I'm worried about the effect on my current Ability bottle.  However, was I supposed to use a minecraft bottle rather than a bucket?...as I haven't found a pipe yet that will connect to the Supplementaries jar to extract the honey.

**Comment by dittymargoo** [comment]
My apologies, I have found another issue that probably is the same as this one: #3057.  The only difference beings that I didn't have a shield in my offhand and the modpack versions are different.

**Comment by Saereth** [comment]
yeah this is a duplicate interaction of that same bug so I'll close this, we're waiting for buz to fix it
