### ISSUE TITLE
FTB Skies - Easy Villagers mod item icons are invisible

### ISSUE THREAD

**Issue by GlobalGamer2015** [FTBTeam/FTB-Modpack-Issues#3134]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

Most of the items icons from Easy Villagers mod are invisible

### Steps to reproduce

Search in JEI for any of the items from the screenshots below.

### Expected behaviour

Have icons.

### Screenshots

![image](https://user-images.githubusercontent.com/19220996/232261849-8e0f4dc3-b3f3-430f-9e3f-2b0abbfaf9f3.png)
![image](https://user-images.githubusercontent.com/19220996/232261853-92ec5a10-949c-4edd-8ba9-e506a4a62606.png)
![image](https://user-images.githubusercontent.com/19220996/232261858-3d504a00-42ca-476f-bd78-c395fb5b3f2f.png)
![image](https://user-images.githubusercontent.com/19220996/232261860-c7a6167a-d2e6-4e68-8915-21b52a1a895e.png)
![image](https://user-images.githubusercontent.com/19220996/232261863-b72d719f-c4e5-417a-90a6-43bbe7ca6e59.png)

**Comment by gamingoninsulin** [comment]
But when placed the trader block its just visable.
And the incubator form what ive been testing is not visable at all it still works tho

**Comment by Cujoplays** [comment]
im having a simular issue but when a trader is placed into the world it becomea visible and a villager and workstation can be added to it but the GUI is not accessible
