### ISSUE TITLE
Tetra Nihilo - New Mod Suggestion

### ISSUE THREAD

**Issue by PersiflageTheNinth** [FTBTeam/FTB-Modpack-Issues#3135]
### Modpack

FTB Skies

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/tetra-nihilo

A mod I wrote to allow Tetra Hammers to be used for in world hammer crushing. Simple addition allowing for earlier use of Tetra

**Comment by Saereth** [comment]
nice mod, adding!
