### ISSUE TITLE
Game crash when using magma crucible with pipez for RF

### ISSUE THREAD

**Issue by DarkNews11** [FTBTeam/FTB-Modpack-Issues#3136]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

I was going to use the magma crucible to produce lava, and when i place it on the energy pipes form pipez, the WAILA flash a long red bar (bigger than WAILA itself) where its show the energy of the machine, and the game freezees and crashes.
i tried twice, and the same thing happends, and the magma crucible disaper out of existence.

### Steps to reproduce

1. flux point and chose your network
2. connect ennergy pipes form pipez to the flux point
3. place the magma crucible close to the pipe to be connected
4. the game crashes

### Expected behaviour

Know if i'm doing something worng or the correction of the bug

**Comment by MechBFP** [comment]
I have the exact same setup and have an item pipe, fluid pipe, and energy pipe, all from pipez connected to the magma crucible and I don’t have any issues. I also have the energy coming from a flux point through the energy pipez as well.

**Comment by DarkNews11** [comment]
Well, i tried again today, and still had crashs (2 more times). Then i tried to place the point directly and was fine. Idk tbh

**Comment by MechBFP** [comment]
> Well, i tried again today, and still had crashs (2 more times). Then i tried to place the point directly and was fine. Idk tbh

What do you mean by "placed the point directly"?

**Comment by DarkNews11** [comment]
Insted of giving energy to the crucible by energy pipes, i placed the flux point directly and it didnt crash
