### ISSUE TITLE
Mekanism Quests

### ISSUE THREAD

**Issue by ninjachicken1** [FTBTeam/FTB-Modpack-Issues#3137]
### Modpack

FTB University 1.16

### Is your suggestion related to a problem? Please describe.

Here's some quests that could be in the Mekanism chapter, because hey, the Combiner's completely useless in this pack and that's a quest:

- Roads - Slide like ice to move fast
- Gauge Dropper - Remove and insert chemicals from machines. Handy if something has the wrong chemical in it, or if one ore of Slurry get's spread between multiple Crystallizers somehow.
- Balloons - Seriously, what do they do?
- Obsidian TNT - Bigger booms
- Pigment Extractor/Pigment Mixer/Painting Machine - Colour Balloons and Plastics colours beyond the standard 16
- Network Reader - Debug Mekanism Networks
- Dictionary/Oredictionificator - Convert wrong ores. Maybe give a stack of wrong ore as a reward?
- Industrial Alarm - Make annoying noise
- Security Desk - Something to do with stopping other players from accessing your stuff. I don't play multiplayer
- Configuration Card - Copy/paste machine settings
- Personal Chest - Portable storage. Likely made while crafting something else.
- Fluidic Plenisher - A lake maker
- Resistive/Fuelwood heater - Generate heat from FE/fuel.
- Bio generator - FE from Biofuel.

I'm going to mention the Walkie Talkie separately, because I'm not sure if it's implemented properly, and in versions of Mekanism predating Discord the VOIP server was on by default and slowed the game down. Still, it's funny to note that Mekanism comes with a VOIP server.

There's also some stuff that I was led astray on at various points, based on out-of-date information online. Maybe some clarification in the questbook would be nice.

- I was led to believe that the Thermal Evaporation Plant works better in the desert, then that it doesn't, then that it does, but if you put Advanced Solar Generators on it replaces the desert bonus with a better bonus. Quite frankly I don't know anymore, all I know is you put Advanced Solar Generators on the corners. There's no mention of that trick in the questbook, and also no mention of other ways of heating it up, like the Resistive Heater. Another cool thing about the TEP not mentioned is that the walls can be made of Structural Glass.
- Solar Generators and the Solar Neutron Activator don't work in the End anymore. Apparently they used to work 24/7 there once, which led to me attempting to set up Nuclear in the End, but nope.
- This might have been addressed already with the Heaters and the TEP, but not much is mentioned about the heat mechanics, and why you might want to use Thermodynamic Conductors.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
