### ISSUE TITLE
Farmer bees dont actually farm

### ISSUE THREAD

**Issue by ChewedPencil** [FTBTeam/FTB-Modpack-Issues#3138]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

So i have a bee farmer setup with two farmers and two collector bees. the farmer bees will act as if they were pollinating a fully mature crop like a flower, and i assume they are supposed to right click the crop to harvest it, but instead they just float around the same crop all day until night, where they return to the hive, not actually breaking anything.

### Steps to reproduce

Set up a farm

Set up teh bees in the hive(I have two range upgrades only)

watch them fly around like lil idiots.

harvest the crops manually every time instead

### Expected behaviour

I would EXPECT the Farmer bees to actually harvest the crops

**Comment by JaisDK** [comment]
Hi,

Can you open the `world/serverconfig/productivebees-server.toml` config file and set `forceEnableFarmerBeeRightClickHarvest` to `true` and see if that helps?

**Comment by Saereth** [comment]
yep that seems to work, added to pack
