### ISSUE TITLE
[Suggestion]: FTB Oceanblock - Chaos Guardian/ Chaos Shards

### ISSUE THREAD

**Issue by Keiko403** [FTBTeam/FTB-Modpack-Issues#314]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

sorry, I know this suggestion isn’t inline with your requirements but I’m really enjoying FTB Oceanblock but have just started to wonder if it’s worth me putting anymore time into it as looking ahead to endgame requires a chaos guardian fight win (ain’t gonna happen!! I’m just not up for it and would never win which to me makes this pack unbeatable and therefore removes the fun element for me.

I don’t like the chaos guardian fight, never have and to me having progression locked behind that fight puts me off playing.

### Mod suggestion

Not sure if Avaritia is available for 1.16.5 but something OP like Sword of the Cosmos would be great.
Alternatively a different recipe for an initial Chaos Shard or a chance of Chaos Shard reward for quest completion.
Happy to add a recipe myself but I always feel this is cheating? Maybe a Dragon egg Singularity, Nether Star Singularity, Netherite Singularity, Ender Pearl Singularity, End Stone Singularity, Awakened Draconium Singularity and a Power Pot MK4 in a Draconic Fusion Crafter with copious amounts of power?
Or a large extended crafting recipe?

**Comment by Sunekaer** [comment]
Feel free to change it yourself, this wont be changed in the pack :)
