### ISSUE TITLE
Endgame Stuff

### ISSUE THREAD

**Issue by ninjachicken1** [FTBTeam/FTB-Modpack-Issues#3141]
### Modpack

FTB University 1.16

### Is your suggestion related to a problem? Please describe.

I'm nowhere near the Endgame yet, but there's some stuff I noticed that needs some clarification.

First off, the Singularity Singularity. I had to look up how to make that, and I'd never have guessed if I didn't. I recommend a quest explaining the fluid bits trick.

Second, 9x Compressed Iron Blocks. Multi Armor wants 4 of them. That's 13,947,137,604 Ingots just for those blocks, just short of 14 billion. I don't see how you expect players to craft this without the Creative Vending Upgrade, and the quest for that suggests you expect that to be made after the Armor.

**Comment by temhelk** [comment]
@ninjachicken1 What is that trick that you are referring to?

I'm trying to find a way to get Singularity Singularity quickly, and I'm using fluid bits to generate a lot of items. The bottleneck in my case is transport speed, the fastest way I found is using integrated dynamics, that way I can transfer 1 stack per tick. Based on my calculations, to get 1 Singularity Singularity, we either need to wait for 5 straight days with 1 chiseled bit storage or to get 1 Singularity Singularity in one hour, we need to place 556 chiseled bit storages with that transfer speed. Am I missing something?

**Comment by ninjachicken1** [comment]
@temhelk The fact that you know how long it will take shows that you know more about this that I do. I haven't actually got to that stage in the pack, I just watched someone else do it in a different modpack - Oceanblock, specifically.

**Comment by temhelk** [comment]
@ninjachicken1 Thanks for the response. I think I know the video that you are referring to. I watched a part of it (maybe I missed something), and in that video, I think, for transportation author uses a mod named "Industrial Foregoing" that is not included in FTB University and probably some other things. I tried finding other mentions of Singularity Singularity and didn't find a lot. But I missed the fact that you can pump fluids into the matter condenser, so I need to experiment a little bit more with that.
