### ISSUE TITLE
Refined Storage Bigger Disks

### ISSUE THREAD

**Issue by RatherChaotic** [FTBTeam/FTB-Modpack-Issues#3146]
### Modpack

FTB Skies

### Mod suggestion

I recommend adding https://modrinth.com/mod/extra-disks since there is the MEGA disks mod I feel there should be more disks for refined storage.

**Comment by Saereth** [comment]
Ae2 has more addons and bigger disks and is geared towards power users in this pack. Refined storage has less addons for power users and is for players wanting a simpler storage solution.
