### ISSUE TITLE
ExtremeSoundMuffler causes a memory error in the sound Engine

### ISSUE THREAD

**Issue by N0thyn** [FTBTeam/FTB-Modpack-Issues#3147]
### Modpack

FTB Skies

### Modpack version

1.0.4-1.0.6

### Describe the bug

After playing for a bit the sounds get fewer and fewer until the game is practicly silent. 
After looking in the concole the error shown in the screenshot gets spammed multiple times per second.
![Memory Error](https://user-images.githubusercontent.com/130873483/232322312-e7a2a5b0-467d-4893-b07b-a07fd97e070e.PNG)
I started playing in version 1.0.4 so i do not know if the bug exists in earlier versions. Changing the allocated ram to minecraft itself does not solve the problem. The bug still appears with 8GB, 12GB, 16GB, etc. 
There are two known ways to fix the bug.
1. Restart minecraft completly (just exit to main menu and reload the world does not work) TEMPORARY FIX!
2. Remove ExtremeSoundMuffler from the pack

### Steps to reproduce

1. Start the game
2. Play or idle for some time
3. Sounds start to reduce
4. Game goes nearly silent

### Expected behaviour

ExtremeSoundMuffler should not "crash" the sound engine and just muffle selected sounds

### Additional information

A fix or alternative would be very appreciated because some sounds from machines or other blocks/mobs are very annoying over time.

**Comment by MechBFP** [comment]
ExtremeSoundMuffler was removed in 1.0.3. So your post makes no sense given the version you listed.

**Comment by N0thyn** [comment]
That kind of makes sense now but i seems like the update did not remove the mod from the pack in my case. I will close this now an try to reinstall the pack with my world as backup in case some other update changes failed to update.
