### ISSUE TITLE
Crash while Launching

### ISSUE THREAD

**Issue by Smok3dDevil** [FTBTeam/FTB-Modpack-Issues#3153]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11245693/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11245694/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11245696/latest.log)

### Describe the bug

After launching the instance the minecraft windows appears, about half way through it crashes back to the FTB App

### Steps to reproduce

1. Open FTB App
2. Launch FTB Skies
3. Crash
4. Retrying the launch also repeatedly fails

### Expected behaviour

Game loads correctly

**Comment by Saereth** [comment]
your config files are locked so it cant regenerate an damaged one, I'd suggest you reboot then reinstall the pack, should clear it up
