### ISSUE TITLE
Inventory sorter mod blacklist issues

### ISSUE THREAD

**Issue by hadesanc1** [FTBTeam/FTB-Modpack-Issues#3155]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

The bug in this thread still exists.
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3041
I have tried using the command '/invsorter bladd' to add the danks and botania flower pouch into the blacklist but nothing changed. The blacklist simply did not work.

### Steps to reproduce

1. Use command /invsorter bladd dankstorage:dank1 
2. Use command /invsorter list to confirm the targeted storage container is blacklisted.
3. Open the container and press the middle button of the mouse.
4. Hurray! Items voided.

### Expected behaviour

Storage containers can be successfully added into the blacklist.

### Screenshots

![image](https://user-images.githubusercontent.com/122217363/232467751-56319f81-79f9-4692-95d9-13a3f627ada2.png)
![image](https://user-images.githubusercontent.com/122217363/232467786-ddf050d3-dfcb-4e5b-91d2-9b51b7d43fea.png)

**Comment by Saereth** [comment]
needs to be added to the server configs (defaultconfigs) and then put back into your save unless its done in an automated way via serverconfigupdater mod. I've added the flower pouch to the blacklist and set the configs to update for 1.7.0

**Comment by EthicalBen** [comment]
The issue persists in 1.2.1
