### ISSUE TITLE
Lag/Crashes while holding Wrenches

### ISSUE THREAD

**Issue by Juicemoose89** [FTBTeam/FTB-Modpack-Issues#3159]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

When anyone on my server has a Pipez Wrench or Mekanism Configurator tool in hand the server begins to lag aggressively and will sometimes crash and restart, has anyone seen this issue and of a solution?

### Steps to reproduce

Place wrench or configurator in hand
watch the game world lag and the server stutter

### Expected behaviour

Lag and server crash

**Comment by maca134** [comment]
Ok this is also happening with create wrench.
It looks like a weird interaction with integrated dynamics looking at the profiler
https://spark.lucko.me/KDsShrcFOr

**Comment by maca134** [comment]
Issues reported to ID guys
https://github.com/CyclopsMC/IntegratedDynamics/issues/1266
