### ISSUE TITLE
Going to the Nether Deleted Island Overworld

### ISSUE THREAD

**Issue by AlchemicPhoenix** [FTBTeam/FTB-Modpack-Issues#3160]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

I found that when I go to the Nether through the portal my island gets deleted. If I go back through the portal I spawn a new portal in the overworld with the ship about thousands of blocks away, like x25,000 z36,000. If I go to the nether and try to use /ftbdim home, it says I have to go to the overworld and use the portal to make my home. I think I started the pack in version .2 or version .3, not sure. I've used backups to restore my island to continue playing and just avoided going to the nether. I tried going after a while and had the same results and discovered that the backup from before I even built the portal did not delete the nether or the ship overworld spawned nether portal. So I have a fully looted nether structure but no items from it.
I remade this issue because I emailed Mikey the level.dat and ftbteamdimensions_dimensions_store.dat files and he said that they were fine and that this may be a new issue. 

### Steps to reproduce

Build portal
Go through portal
No more island world
Go back through portal
Returns you to ship overworld

### Expected behaviour

Should return you to Island world

### Screenshots

![2023-04-14_11 26 22](https://user-images.githubusercontent.com/50083962/232594423-22d509e8-4331-4ede-afaf-b1e9f6a5e039.png)
![2023-04-14_11 26 53](https://user-images.githubusercontent.com/50083962/232594438-58b4fdaa-1b26-49b0-a295-1153976128f8.png)
![2023-04-14_11 28 07](https://user-images.githubusercontent.com/50083962/232594452-6cf16c3c-8b16-49c0-a2b5-9bfef1ec05d7.png)

**Comment by MikesNameIsMike** [comment]
Same Issue here I think.  No idea if my base is 'deleted' though, I think I'm just nowhere near it.  
I created a nether portal, went through, and when I came back to the overworld it brought me to a location 80,000 x 160,000 blocks away from the origin 0,0 where my island is.  I have no way to get back to my base now.

**Comment by lelmattin** [comment]
> Same Issue here I think. No idea if my base is 'deleted' though, I think I'm just nowhere near it. I created a nether portal, went through, and when I came back to the overworld it brought me to a location 80,000 x 160,000 blocks away from the origin 0,0 where my island is. I have no way to get back to my base now.

I had the same issue myself. I had to run the command "Execute in ftbteamdimensions:team829823094bjfg984382 run tp myusername 0 0 0" just to get back to my island again. 

ftbdimension would be different for your own world etc etc.

**Comment by Frogimus** [comment]
This same thing just happened to me. On the current release.
