### ISSUE TITLE
Sophisticated Backpacks Item Loss/Removal (Stack Upgrade)

### ISSUE THREAD

**Issue by iosrouter** [FTBTeam/FTB-Modpack-Issues#3161]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

-N/A-

### Describe the bug

Issue is when using the Backpack (Any Tier) from Sophisticated Backpacks mod with the "Stack Upgrade".
When the backpack is near full or full, pressing CTRL + MIDDLE CLICK causes the backpack inventory to restack to 64 items per slot. This causes any items that dont normally fit to disappear. 

### Steps to reproduce

1. Get Backpack from Sophisticated Backpacks
2. Insert any tier of "Stack Upgrade" into the upgrades section on the left
3. Fill backpack more than half full (
4. CTRL + Middle Click in the middle of the GUI to resort the backpack
5. Observe the items as they unstack into 64 stacks instead of respective size.

### Expected behaviour

The backpack should be resorted into the proper order when using CTRL + MIDDLE CLICK.

**Comment by iosrouter** [comment]
> this is the same behaviour as trying to sort the danks... so id imagine the inventory sorting mod is to blame... instead of using a keybind sort, use the backpacks own sorting button at the top... and another mod to add to the inventory sorter blacklist.

Yeah and the weird part is it doesn't happen when using the default sort (middle mouse). Only when doing ctrl or shift. Also I didn't know this was an issue for Danks too. Yeah any inventory that has >64 stacks it doesn't enjoy. Instead of just blacklisting that can just be an extra check. It's hard because everyone does inventories a little different.

**Comment by Morelyn** [comment]
blacklisting doesnt work with the sorting mod... went all through blacklisting danks and still lost another full inventory of stuff to the silly mod.
