### ISSUE TITLE
Cant interact with crafting table

### ISSUE THREAD

**Issue by thederpykrafter** [FTBTeam/FTB-Modpack-Issues#3162]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

After updating to latest version when I try to open the vanilla crafting table charachter arm swings but nothing happens.

Issue doesn't seem to exist in new worlds

### Steps to reproduce

1. Update to version 1.0.6
2. Load existing world
3. Attempt to open crafting table
4. Swing arm in frustration (in game and irl)

### Expected behaviour

Expected crafting gui to open

### Additional information

Not sure what other information may be needed as no crash log or anything happened.

**Comment by thederpykrafter** [comment]
So now I'm even more confused than I was. After closing minecraft and launching again it works fine, which is probably why it worked in the new world as well.

**Comment by Saereth** [comment]
yeah I can't reproduce this now either so i'm assuming just some edge case fluke, reopen if you can provide any reproducible steps please
