### ISSUE TITLE
[Bug] Large memory leaks v1.0.4+

### ISSUE THREAD

**Issue by heolo1** [FTBTeam/FTB-Modpack-Issues#3164]
### Modpack

FTB Skies

### Modpack version

v1.0.4 - v1.0.6

### Log Files

[debug-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11258257/debug-1.log.gz)
[2023-04-17-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11258259/2023-04-17-1.log.gz)

### Describe the bug

Game sometimes crashes out of nowhere when memory on F3 is fine with the error message on a `Connection Lost` screen (on a server) of `Internal Exception: java.lang.OutOfMemoryError: Cannot reserve 4194304 bytes of a direct buffer memory (allocated: <some number close to 12884901888>, limit: 12884901888)`, computer has no more RAM (seen on `/mem/procinfo`). Requires game closing and restarting to free memory.

When I had allocated 12 GB of RAM to Minecraft, sometimes uses up to 26 GB of RAM before erroring and kicking me back to the `Connection Lost` screen.

### Steps to reproduce

Launch game
Play game as expected
Wait for a couple hours (~4-6?)
Get OutOfMemoryError

### Expected behaviour

For Garbage Collector to deallocate RAM properly

### Screenshots

Image of error message:  
![Screenshot_2023-04-14_23-12-38](https://user-images.githubusercontent.com/95734779/232683225-5d0be5b3-1dd7-4456-b73d-6cfa2e54095e.png)
Image of memory usage immediately after crash with game still open: 
![Screenshot_2023-04-14_23-15-50](https://user-images.githubusercontent.com/95734779/232683329-18427182-204c-45b7-ac99-84c50f0cd6f9.png)
Image of memory usage immediately after closing game: 
![Screenshot_2023-04-14_23-18-42](https://user-images.githubusercontent.com/95734779/232683388-7e4bdad1-df4c-42d1-981f-1c148d220402.png)

### Additional information

I know that it has been happening to several other people on a public server that I am playing on. The server in question is the Craft Down Under FTB Skies NA (don't know if this is advertising and if advertising is allowed).

**Comment by Saereth** [comment]
Let me know if this issue persists for you in 1.7.0 update once it comes out
