### ISSUE TITLE
Diamond block is a filter for pedestals attacker, until it's a budding amethyst.

### ISSUE THREAD

**Issue by MarkSzita** [FTBTeam/FTB-Modpack-Issues#3168]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

pretty simple issue, the diamond block is used as a filter for pedestals to attack hostiles. could do with being changed to another block to avoid the amethyst conversion causing unwanted deadsies.

### Steps to reproduce

1. setup pedestal attack with diamond block filter.
2. wait for the fairy to bring you doom.

### Expected behaviour

to not be murdered.

**Comment by Emmanuel-true** [comment]
i guess you can close event (budding amethyst)
/events toggle (budding amethyst)

**Comment by Dan-Mizu** [comment]
Toggling events doesn't make sense on multiplayer servers, though. For now I have to settle for detecting amethyst and then replacing it with diamond automatically but that feels like a workaround.
