### ISSUE TITLE
Excessive data transmission on FTB skies server

### ISSUE THREAD

**Issue by jaynotgay** [FTBTeam/FTB-Modpack-Issues#3169]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

Could someone please provide an explanation as to why our FTB skies server is sending more than 10 Mbps of data to each client? We had 25 players online and it was transmitting over 200 Mbps of data to all connected players.

https://gyazo.com/46b75261bd35357e28ca95f79e446869

### Describe the bug

Could someone please provide an explanation as to why our FTB skies server is sending more than 10 Mbps of data to each client? We had 25 players online and it was transmitting over 200 Mbps of data to all connected players.

https://gyazo.com/46b75261bd35357e28ca95f79e446869

### Steps to reproduce

Run an FTB skies server

### Expected behaviour

High  bandwidth

**Comment by metalim** [comment]
Have same issue. Except I get traffic up to 100 Mbps for single player, which is NUTS. Probably limited by player network connection, and would flood it even more if it could

**Comment by JustAnotherGhostName** [comment]
Can confirm this is a thing on my network. Don't have time to investigate yet, but the outbound traffic is several magnitudes higher than say ATM8. I mentioned it on the discord before, but after 4 hours of measurement, with 2gb of inbound traffic, there was 65 gb of outbound. This isn't a one off thing either, I've noticed this since 1.0.0, just didn't think much of it at first.

**Comment by sauramel** [comment]
We are also experiencing this on our network, seems to cause certain players to time out very frequently.
We also experience this issue with FTB Inferno.

**Comment by Saereth** [comment]
This should be better in the new version of ftbquests that came out today (will be in the 1.7.0 update) let me know if you still ssee issues with this at that point so we can dig more into it as maybe its something else

**Comment by JustAnotherGhostName** [comment]
> 

Sounds good. After 1.7.0 comes out and my network has time to update (If its out today I would prob do it Thursday or Friday, busy week), then report back here if there is still an abnormally high usage.

**Comment by sauramel** [comment]
Our network has updated FTB Skies to 1.0.7 as directed and have not seen any improvement

**Comment by metalim** [comment]
> This should be better in the new version of ftbquests that came out today (will be in the 1.7.0 update) let me know if you still ssee issues with this at that point so we can dig more into it as maybe its something else

Nope, didn't fix a sh*t. Getting 50+ Mbps, and timeout in 10 seconds

**Comment by jaynotgay** [comment]
I think the update made it worse

**Comment by metalim** [comment]
Is there indication someone is working on this? Is it known what packet types are sent? Is there some logging proxy to debug this?

**Comment by Micaxs** [comment]
> This should be better in the new version of ftbquests that came out today (will be in the 1.7.0 update) let me know if you still ssee issues with this at that point so we can dig more into it as maybe its something else

It remains an issue even after 1.0.8 update.

**Comment by sauramel** [comment]
> and

Can confirm this is also still an issue for us

**Comment by Micaxs** [comment]
Still an issue in version 1.1.0

**Comment by sauramel** [comment]
> Still an issue in version 1.1.0

Same for us

**Comment by metalim** [comment]
1.1.0 -- still no change
<img width="609" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/230431/6435e186-ed52-43af-a849-b5dbe5a43d91">

**Comment by jaynotgay** [comment]
Can confirm still an issue in 1.1.0

**Comment by jaynotgay** [comment]
We are transmitting arround 1TB a day at the moment

**Comment by ukmcplyr** [comment]
> We are transmitting arround 1TB a day at the moment

Yikes. I knew this bug was a thing but had no idea about the scale. Makes me question whether two other bugs I've been monitoring have been purely down to utterly saturating the old gigabit ethernet card on my test server.

Has anyone tried/started a binary search on 1.1.0's mods, config and kubejs scripts to see where the culprit(s) may be? Would be interested to hear if anyone has or is before I venture down that long ol' road myself...

**Comment by metalim** [comment]
> a binary search

Actually good idea, to locate the issue fast, if you have access to the server. Do it.
For me issue appears on public server, and does not -- on my private server, so I'm going the way of MC traffic sniffers on the client side. It sure is a `ClientbountCustomPayloadPacket`, but it's just any modded packet, so I need to get content of it. Sniffcraft crashes with segfault on FTB Skies, so I'm trying other tools

**Comment by paradust7** [comment]
I was able to decode the identifiers on the ClientboundCustomPayloadPackets and record the total bytes received.

In about 20 seconds of being connected to the server, this is how many bytes were received of each kind:

```
6535057 sons_of_sins:sons_of_sins
4245576 forge:split
3336821 architectury:network
612498 tetra:main
145271 modonomicon:main
67397 productivebees:buzzinga
58101 placebo:placebo
47421 supplementaries:network
38220 dpanvil:main
17638 moonlight:channel
15050 unusualend:unusualend
10742 rainshield:main
8069 modernfix:main
7365 mekanism:mekanism
5260 fluxnetworks:network
5075 rechiseled:main
4503 curios:main
3187 minecraft:register
3025 computercraft:network
1747 ironjetpacks:main
1692 supermartijn642configlib:sync_configs
1010 ad_astra:main
774 create:main
486 forge:tier_sorting
338 occultism:main
309 libx:netchannel
290 hammerlib:main
244 ars_nouveau:network
210 shrink:main_channel
135 hexcasting:main
73 hexal:main
38 solcarrot:main
35 sophisticatedcore:channel
29 everlastingabilities:channel_main
22 blueprint:net
20 travelanchors:netchannel
18 creativecore:main
17 mcjtylib:mcjtylib
10 appleskin:sync
6 minecraft:brand
5 titanium:network
5 integrateddynamics:channel_main
4 jade:networking
3 configured:play
2 rftoolsutility:rftoolsutility
2 craftingtweaks:network
2 chiselsandbits:chiselsandbits
1 spectrelib:main
1 inventoryessentials:network
```

**Comment by paradust7** [comment]
The sons of sins packets are all the same (52 bytes, in hex):

00000000000a000006001077697374697665726a61776c696d69744084d0000000000001000c736f6e736772696566696e670100

This has two identifiable strings: "wistiverjawlimit" and "sonsgriefing" which appear to be config parameters for the mod. I can't find the source for the mod, so can't say for sure.

Forge:split are split packets which can be decoded, and architectury:network is an abstraction layer that other mods can use. I will try to inspect deeper into these.

**Comment by ukmcplyr** [comment]
Awesome work :beer:

**Comment by JustAnotherGhostName** [comment]
Great work so far, I would have ended up using something like wireshark if I got to it, but that definitely would have had a lot more work isolating what mod is causing it than whatever tool you are using. Was not aware of MC-specific tools, cool to know they exist. 

Wonder if its worth creating a test server and a couple of clients just with the sons of sins mod later on? Would be able to see a bit more if its the mod itself, or something pack specific.

**Comment by ukmcplyr** [comment]
Just finished testing a few things and removing only Sons of Sins greatly reduces server egress from an average of ~650 kB/s to ~100 kB/s.

Not a solution but at least it's progress. Kudos to those who did the hard work!

**Comment by Saereth** [comment]
ok that mod has been removed from next update which in itself is a massive improvement. If you guys find more problem areas I'll be glad to address them. Going to leave this up for the next few updates just to keep tracking. We've been testing and trying to find things internally as well so this isnt being ignored, just not a simple problem to tackle.

**Comment by paradust7** [comment]
To wrap up, I was able to record much more than the first 20 seconds and verify that only sons_of_sins is spamming. The other big transmissions are one-time. The forge:split packet is a single 4MB "ClientboundUpdateRecipesPacket" that is only sent once. The architectury:network packets were generated by the ftbquests mod, and also only sent once. (sub types: sync_team_data, sync_quests, sync_known_server_registries, sync_teams, send_all_chunks, sync_archived_dimensions, ..etc).

unusualend:unusualend is spamming a little bit, sending the following 86 bytes over and over:

000a000006000b506c617965724d75736963bff000000000000001000d697354656c65706f7274696e670006000374705a00000000000000000600037470590000000000000000060003747058000000000000000000

(identifiable strings: PlayerMusic and isTeleporting)

But about 100x slower than the s_o_s spam. Other than that, it is very quiet after 20 seconds. (only looking at the custom payload packets)

**Comment by metalim** [comment]
Hey guys, any confirmation 1.2.1 fixes traffic issues, where FTB Skies was unplayable ?

**Comment by metalim** [comment]
Upd: confirming myself. Traffic is normal. 50-100 KB/s instead of 20 MB/s

<img width="404" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/230431/96c9ec33-6c8d-46fa-9165-789ff148a98c">
