### ISSUE TITLE
[Bug]: FTB Academy 1.16.5: AstralSorcery error

### ISSUE THREAD

**Issue by SirGouki** [FTBTeam/FTB-Modpack-Issues#317]
### Modpack

FTB Academy 1.16

### Modpack version

1.2.0

### Log Files

https://pste.ch/upekepeyim.md

### Describe the bug

This is from a fresh install through the FTB launcher, the only thing that I've done was change where the instances folder is to where it was in my curse forge launcher, and changed the java from the default to the one I keep updated on my computer (which works for mod packs installed from the curse forge launcher).

When running FTB Academy, it does all the file checks and ends with a window that states "File astralsorcery-1.16-1.16.5-1.13.12.jar is not a jar file"

This causes none of astral sorcery to load, and even causes the entire area for it in the school to be loaded as a void with water.

I have actually been experiencing this error for a while now on the previous version, and was hoping it was fixed since you guys went so far as to even roll your own laucher (minecraft doesn't have enough launchers already?), but it appears to be present here as well.
My internet connection was not interrupted during the download, and the FTB launcher gives no errors itself.  Also, clicking "Load in game" button does nothing.

### Steps to reproduce

1. Download and install FTB Academy 1.16
2. Launch that mod pack.
3. After the launcher launches minecraft, then loads all the mods through the launcher, and returns to minecraft, you are presented with the error message "File astralsorcery-1.16-1.16.5-1.13.12.jar is not a jar file"

### Expected behaviour

Mods in a mod pack should be configured to work without any user intervention or configuration required.

### Screenshots

![image](https://user-images.githubusercontent.com/11664236/141880974-3054d1b0-b0cd-4398-a579-b929007f0965.png)

### Additional information

I will edit in the log file (or provide it in a comment), if it is not present when I hit submit.

**Comment by SirGouki** [comment]
Note, this exact same error is present in FTB University 1.16.

**Comment by Raidobw2** [comment]
Glad you got it fixed. I'll be taking note of the issue and the log since I'm currently building up a bug list for our App devs.

This happens commonly amongst other users. Sometimes the fix is even to download the server from the FTB website and to replace a lot of files on the client (mods, config, kubejs).

I'll be closing this as it's a support issue and has been self-resolved thanks to your ingenuity, if you encounter other bugs visit us in the FTB Discord, we have support channels to help you with that.
