### ISSUE TITLE
Statues Looting Broken

### ISSUE THREAD

**Issue by Squeegee44** [FTBTeam/FTB-Modpack-Issues#3170]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.8.0

### Describe the bug

Prior to version 1.8.0 the Statues Mod allowed a semi-automated method to gather Loot from a Statue.  Using Cycle Item User and Item Collector you could Right Click a Looting 1 Statue and it would drop some Loot every few seconds.  This ability was broken with the updates in the 1.8.0 version.  Now a Looting 1 Statue will only drop one time of Loot after you place it down somewhere.  It will not drop anymore after that initial time.  You can break the Statue and set it down again and it will drop Loot once (so, it is possible to use a breaker and placer to possible work around this issue).

### Steps to reproduce

1. Get a Statue and a Statue Core from a Statue Bat
2. Use the S.T.A.T.U.E. upgrade tool to upgrade the Statue with the Statue Core (initial Upgrade to get levels)
3. Kill at least 10 of the Statue entity to get to Level 1 on the Statue
4. Upgrade the Statue in the S.T.A.T.U.E. upgrade tool with the Looting 1 Upgrade
5. Place the Statue in the world somewhere and right click it a few times over a few seconds.  It should give you some Loot specific to the Statue you are using.
6. Keep right clicking the Statue for a few minutes - nothing else drops but should drop something every few seconds
7. Break the Statue and replace it again somewhere and right click it for a few seconds and it will drop loot.

### Expected behaviour

The Status should drop Loot every few seconds if you right click it and it has at least Looting 1 Upgrade.

**Comment by Saereth** [comment]
should be fixed in new update
