### ISSUE TITLE
FTB Skies World Crash

### ISSUE THREAD

**Issue by alio314** [FTBTeam/FTB-Modpack-Issues#3171]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

https://pastebin.com/dMfDqzzQ

### Describe the bug

FTB Skies modpack opens but my world hangs up and crashes. I've tried backups from earlier saves and no go. My other test world opens up fine.

### Steps to reproduce

Go to FTB Launcher
Open FTB Skies
Click Singleplayer
Open World
FTB Skies crashes: message: 

### Expected behaviour

I expected that my World would open up.

**Comment by Saereth** [comment]
config files are damaged, reinstall
