### ISSUE TITLE
Quest Chapter 'Getting Started' not showing complete (green)

### ISSUE THREAD

**Issue by The-OD** [FTBTeam/FTB-Modpack-Issues#3172]
### Modpack

FTB Skies

### Modpack version

beta 1.0.6

### Describe the bug

I have completed all of the tasks in the 'Getting Started' chapter but the Chapter is not being marked as complete and does not appear green

### Steps to reproduce

Complete all tasks
check the quest book
chapter is not complete

### Expected behaviour

Chapter should be marked green and chapter complete

### Screenshots

The screenshot shows all tasks in the chapter marked as complete but the chapter is not green like other complete chapters
<img width="1920" alt="Screenshot 2023-04-19 054451" src="https://user-images.githubusercontent.com/106688777/232969294-20eed40d-d246-459b-a67d-826fabbcd63b.png">

### Additional information

previous chapter has gone green successfuly

**Comment by demoniclords** [comment]
you need to make a personal shrinking device and a large compact machine for it to pop up
