### ISSUE TITLE
Island Doesn't Spawn

### ISSUE THREAD

**Issue by 77wisher77** [FTBTeam/FTB-Modpack-Issues#3173]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

https://pastebin.com/HgBn3KAK

### Describe the bug

Linux Multiplayer Server, Islands do not spawn for players when they try and create one

We tried both FTB Skies and Chosen island types

Every player could not spawn in an island, we tried restarting the server a few times and pruning old islands to try again

### Steps to reproduce

1. Connect to a server
2. Walk through portal and choose island
3. No island spawns

### Expected behaviour

Island spawns

**Comment by Kage-Yami** [comment]
(One of the players trying to generate islands on the OP's server)

Looks like the Minimalist and Compact Machine islands were generating without issues (tried a few times by going through the portal and leaving the team). Didn't have any issues in Singleplayer...

**Comment by mystardious** [comment]
Having the same issue for myself on the latest version. Had to go into single player and generate a world and the migrate it to my server.
