### ISSUE TITLE
Mekanism Turbine ponder is incorrect/missing details

### ISSUE THREAD

**Issue by Ignoranus** [FTBTeam/FTB-Modpack-Issues#3174]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

The Ponder for the Mekanism Turbine that appears in FTB: Skies is missing some important elements.

Mod documentation: https://wiki.aidancbrady.com/wiki/Industrial_Turbine
https://wiki.aidancbrady.com/wiki/Fission_Reactor

(also, I can provide a save with a functional turbine if that would help)

The Ponder shows the entire upper area of the turbine - above the layer with the pressure dispersers - being filled with Electromagnetic Coils. This is very wasteful of resources, as according to mod documentation, one coil block will support 4 blades on the turbine; because of the limited max size of the multiblock, this means you will never need more than 7 coils. 

Beyond that, the turbine depicted in the Ponder has no Saturating Condenser blocks - which would go where the extra Electromagnetic Coil blocks are - and so would not be able to return any steam as water and would, instead, lose the excess water. In other words, the turbine as presented is not suitable for a closed-loop reactor system.

**Comment by Saereth** [comment]
the one presented is more for a system with an infinite water source, and the point of the ponder is basic construction not a comprehensive guide
