### ISSUE TITLE
Infinite block duplication glitch with rechisled.

### ISSUE THREAD

**Issue by CoMeTXero56** [FTBTeam/FTB-Modpack-Issues#3177]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

Using the Rechiseled "Chisel" you are able to duplicate any chiselable block without end, and without consuming anything.

### Steps to reproduce

1.) Obtain a Chisel from Rechiseled mod.
2.) Place AT LEAST 2 of a block into the chisel slot.
3.) Use the mouse scroll wheel to "move" block back into inventory
4.) Notice that you have an infinite amount of blocks coming back into your inventory with no consuming of anything.

### Expected behaviour

Using the scroll wheel, it should only move the selected block back to the inventory ONLY to the amount up to 64 blocks.

### Additional information

Can provide screenshots, but not recording of the issue.

**Comment by Saereth** [comment]
reported to mod dev
https://github.com/SuperMartijn642/Rechiseled/issues/27

**Comment by Saereth** [comment]
a PR was submitted, waiting for item sorter to merge it in

**Comment by manmaed** [comment]
Hello I have just tried this in version 1.3.1, and it seems I can not reproduce this issue can update to 1.3.1 and confirm if this has been fixed?
