### ISSUE TITLE
Missing recipe for Cyclic fluid cables

### ISSUE THREAD

**Issue by MushuPlatypus** [FTBTeam/FTB-Modpack-Issues#3179]
### Modpack

FTB Skies

### Modpack version

1.0.5

### Describe the bug

There is no recipe for the Cyclic fluid cables.  You get 8 from a quest, but I cannot see how to craft more.

### Steps to reproduce

Search JEI for @cyclic fluid cable

### Expected behaviour

See recipe for Cyclic fluid cable

**Comment by Saereth** [comment]
they are disabled intentionally due to crippling tps when used en masse, that is why you only get 8 from the quest
