### ISSUE TITLE
Quests Resetting after game crashing

### ISSUE THREAD

**Issue by MuneebM-GAMING** [FTBTeam/FTB-Modpack-Issues#3181]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

So yesterday, I was playing in my world, and I noticed it was getting very laggy, with huge lag spikes, so I exited and re-entered the world, and then it crashed before the blocks loaded. I loaded back in and everything was fine, except that my quests had been reset. What I have noticed is that there are 2 files in my ftbquests folder in my world folder. One is something like 00000000-000-0000-000000 and another was 218d9cc9-a536-400a-ab46-39ec08b55942. I checked the ones with zero and it was almost empty, whereas on the other file, there were alot of completed quests. I knew that the game was for some reason using the file with zeros and not the original one.

### Steps to reproduce

My game crashed randomly, but before that I was in the nether and I had shaders on, to be specific, Sildur's Vibrant. I set the render distance to 32 Chunks and my game was very laggy, around 0.1 FPS. Normally with shaders in the nether, since there was nothing to render, I got a solid 20 FPS, but I was getting 0.1 FPS, so I knew something was wrong. I then turned off my shaders (it did not really improve FPS) and then left the world and re-entered it. I was looking down in the world, and I saw my inventory, GUI and the block outline, but nothing was rendering. I could not move or look around, as the game was frozen, and as a result, my game crashed. 

### Expected behaviour

I expected the game to load just fine but it crashed

**Comment by Saereth** [comment]
Sounds like something didnt get written due to out of mem/timeouts etc, you should be able to restore from a backup to resolve this
