### ISSUE TITLE
Block of Obsidian from JAOPCA Should be Obsidian?? as it is uncraftable

### ISSUE THREAD

**Issue by robertm1771** [FTBTeam/FTB-Modpack-Issues#3182]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

Trying to get into flux networks it seem the game is looking for me to turn Obsidian into Obsidian dust from Mek. But the reciepe is Block of Obsidian from JAOPCA into 9 obsidian dust. But 9 obsidian dust turns into one block of Minecraft obsidian.

### Steps to reproduce

Search for Block of Obsidian in JEI, Will find it will turn into 9 obsidian dust from mek but there is no way to make a "Block of Obsidian" 

### Expected behaviour

Craft obsidian into 9 obsidina dust per JEI

**Comment by Saereth** [comment]
You put obsidian into an enrichment chamber to get 4 obsidian dust
