### ISSUE TITLE
Freeze/Lag when crafting certain items in terminal

### ISSUE THREAD

**Issue by MoritzT** [FTBTeam/FTB-Modpack-Issues#3183]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

When using Integrated Terminals to craft some items (e.g. Pistons or Drawers) the game freezes up for a few seconds and starts to lag. I only noticed it with those two items thus far.

### Steps to reproduce

1. Create storage system with chests and integrated tunnels + integrated dynamics cables and an integrated terminal
2.  Sync NEI
3. search drawer to craft
4. lag

### Expected behaviour

smooth lag free crafting

**Comment by Kracton** [comment]
I also just had this with Grid from Refined Storage, though after closing and reopening the game to see if it persisted, it resolved the issue.

I'll record the issue next time if that would help but as of right now I can't find anything else that has this issue in my current session.

**Comment by Saereth** [comment]
see if the update fixes this when it drops tomorrow and let me know please
