### ISSUE TITLE
Hexerei Dismount Keybind

### ISSUE THREAD

**Issue by SpeakinEkan** [FTBTeam/FTB-Modpack-Issues#3184]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

Not sure it's really a bug per se but: There doesn't seem to be a way to rebind the "Dismount" of the Hexerei brooms. With the default being "left shift" (most mod's key bind for descend) my muscle memory is always leaving me falling into the void.

### Steps to reproduce

1. Go to options>controls>key binds
3. search "left shift" (make sure "key" is checked)

Hexerei's "Dismount" should be there, right?

a search for "dismount" also yields no results

### Expected behaviour

search keys binds menu and find Hexerei's dismount function

**Comment by Saereth** [comment]
the keybind you're looking for is decend under the hexerei category, its actually a dismount and mislabeled

**Comment by SpeakinEkan** [comment]
> 

Not so in my version. 
I rebound Descend when I couldn't rebind dismount. 
The Descend function is working as expected.
Please note: 
I'm not looking for my problem to be fixed, 
I submitted this report in hopes of aiding the development of the pack.

Many thanks
