### ISSUE TITLE
Server install freezes after download Forge

### ISSUE THREAD

**Issue by mouro001** [FTBTeam/FTB-Modpack-Issues#3185]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

C:\Users\user\MC\skies>serverinstall_103_6454.exe
Server installer version 22.1213.2347-windows-amd64 commit fba9792cf71889ce973a6a0846a194e3113e1678
Where would you like to install the server? [current directory]
skies6454
Continuing will install FTB Skies version 1.0.5. Do you wish to continue? (y/n) [y]

2023/04/20 16:36:13 Performing installation...
2023/04/20 16:36:13 Getting downloads for Forge Install
^C
C:\Users\user\MC\skies>serverinstall_103_6458.exe
Server installer version 22.1213.2347-windows-amd64 commit fba9792cf71889ce973a6a0846a194e3113e1678
Where would you like to install the server? [current directory]
skies6458
Continuing will install FTB Skies version 1.0.6. Do you wish to continue? (y/n) [y]
y
2023/04/20 16:39:03 Performing installation...
2023/04/20 16:39:03 Getting downloads for Forge Install

### Describe the bug

Upon trying to install the server (using the .exe, or Linux), the installer downloads Forge and then freezes. Enabling verbose mode doesn't print any more information

### Steps to reproduce

1. Download server installer for FTB Skies 1.0.6 or 1.0.5
2. Run the installer

### Expected behaviour

It should install the server

**Comment by asdf3601a** [comment]
The Forge server is down. Maybe wait for it to recover.

**Comment by mouro001** [comment]
Weird that it downloads the `forge-1.19.2-43.2.6-installer.jar`, which you can then run to install the forge server

**Comment by mouro001** [comment]
Forge seems up, and the server installer seems to work now.
