### ISSUE TITLE
The NVIDIA OpenGL Driver has encountered an out of memory error.

### ISSUE THREAD

**Issue by ItzReyez** [FTBTeam/FTB-Modpack-Issues#3186]
### Modpack

FTB Cotton

### Modpack version

1.1.0

### Log Files

![image](https://user-images.githubusercontent.com/131385814/233419188-d07f8399-b1c3-4f29-8d83-72d3829ef1c1.png)

### Describe the bug

At random times, I will crash and get this error.
The NVIDIA OpenGL Driver has encountered an out of memory error.
 It only really happens in the nether, not sure how to fix it.

When looking at my settings when pressing F3 (Shows FPS, PC Specs, Etc.) It shows my Chunk renderer and VRAM Pool which is capped to 817mb and it's using 90% capacity which seems very low considering I have a 3090 with 24gb vram.

### Steps to reproduce

Not sure who to reproduce it, just happens at random times

### Expected behaviour

?

**Comment by MechBFP** [comment]
I know this sounds counter intuitive but decrease the amount of ram you have allocated in the FTB launcher to only about 6 to 8GB.

**Comment by ItzReyez** [comment]
2nd issue, I'm trying to get the missus to join my server on the same wifi
but she can't seem to join whereas other people can from home - any ideas?

**Comment by manmaed** [comment]
This  issue is now stale
