### ISSUE TITLE
Rocket mycelial generator does not accept fuel.

### ISSUE THREAD

**Issue by RxDoc** [FTBTeam/FTB-Modpack-Issues#3188]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

Rocket mycelial generator does not have a use entry in JEI, and it does not accept rockets as fuel.  I only tried the one second rockets.

### Steps to reproduce

Open jei,
Right click rocket mycelial generator.
Nothing happens.
Try to put rockets inside generator
Nothing happens.

### Expected behaviour

Jei should include usage like the other mycelial generators do.  Generator should accept rockets.

**Comment by Azhen89** [comment]
It accepts only rockets that says Flight I on them , i tested it and it works fine , got even a Mycelial reactor running. Sometimes when you craft rockets they show as normal one thats the bug.

**Comment by RxDoc** [comment]
Thank you. It is still missing a JEI entry though.

**Comment by anasselmi** [comment]
The problem is (correct me if I am wrong) the rockets that have Flight 1 on them are only manually craftable. So this bug makes any kind of automation impossible.

**Comment by RxDoc** [comment]
Not really what I am getting at. The other mycelial generators have a JEI
entry to tell you what fuel they need to function, while this one seems
obvious, it should also have an entry. I did notice that 2 and 3 second
flight time rockets work, just not seemingly the 1 second rockets.
