### ISSUE TITLE
Client Crash due to EverlastingAbilities

### ISSUE THREAD

**Issue by dave36464736** [FTBTeam/FTB-Modpack-Issues#3189]
### Modpack

FTB Skies

### Modpack version

1.0.5

### Log Files

[crash-2023-04-20_16.33.38-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11290307/crash-2023-04-20_16.33.38-server.txt)

### Describe the bug

I was playing normally and had added two saturations from everlastingabilities into my character. I then logged out. When I went to resume gameplay, I now experience crashes everytime I try to enter my world.

### Steps to reproduce

Add Saturation from Everlasting Abilities.

### Expected behaviour

I expected the game to continue normally and to gain saturation bonuses.

**Comment by MechBFP** [comment]
Update to 1.0.6

**Comment by dave36464736** [comment]
Yep. I was ignorant and did not update. Thank you :) Have a super day.
