### ISSUE TITLE
Duplication using hexerei drying rack

### ISSUE THREAD

**Issue by charlesgael** [FTBTeam/FTB-Modpack-Issues#3190]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

We are able to duplicate items using hexerei drying rack

### Steps to reproduce

1. Place drying rack on any surface
2. Place items you want duplicated in rack
3. Break rack
4. Items are duplicated
5. Rince and repeat ?

### Expected behaviour

We get back same number of items as put in drying rack

**Comment by koalalord9999** [comment]
can confirm

**Comment by koalalord9999** [comment]
works in 1.0.6 as well

**Comment by CrimsonXMC** [comment]
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2985

**Comment by Saereth** [comment]
duplicate issue
