### ISSUE TITLE
Duplication with the Witch hazel drying rack

### ISSUE THREAD

**Issue by 21XxNoahxX12** [FTBTeam/FTB-Modpack-Issues#3193]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.8.0

### Describe the bug

if you put an item in the witch hazel drying rack and then dismantle the witch hazel drying rack, the item will duplicated

### Steps to reproduce

1. Place the witch hazel drying rack
2. Put the item in there
3. Destroy the witch hazel drying rack with the Items
4. after step 3. you duplicated the item

### Expected behaviour

Duplication from items

**Comment by Saereth** [comment]
Duplicate issue, reported to hexerei already waiting for them to fix it
