### ISSUE TITLE
Server timeout issue of unknown cause

### ISSUE THREAD

**Issue by Emmanuel-true** [FTBTeam/FTB-Modpack-Issues#3194]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

[crash-2023-04-18_00.31.01-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11292069/crash-2023-04-18_00.31.01-server.txt)

### Describe the bug

1.19.2-20230411a    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 2c3c9fb5-ed0b-455e-aa21-d4ae4206d86e
	FML: 43.2
	Forge: net.minecraftforge:43.2.6
	FramedBlocks BlockEntity Warning: Not applicable

### Steps to reproduce

1. open the server
2. connect to the server
3. play 
4. random server crash
5. server close

### Expected behaviour

server  running normal

**Comment by Saereth** [comment]
This is the server doing something too long and timing out, try running spark profiler or some other profiler, there is nothing in this logfile to indicate a crash with framed blocks

**Comment by Emmanuel-true** [comment]
but there are5 crash logs 
[crash-2023-04-16_23.29.49-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11338446/crash-2023-04-16_23.29.49-server.txt)
[crash-2023-04-17_03.22.06-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11338447/crash-2023-04-17_03.22.06-server.txt)
[crash-2023-04-17_18.01.01-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11338448/crash-2023-04-17_18.01.01-server.txt)
[crash-2023-04-17_21.31.01-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11338449/crash-2023-04-17_21.31.01-server.txt)
[crash-2023-04-18_00.31.01-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11338450/crash-2023-04-18_00.31.01-server.txt)
when I have this mod something want wrong, and it crashes when I delete that mod it seems fine, the server will run normally. Should I reinstall that mod and test it, also I liked to know how to get debug.log

**Comment by Emmanuel-true** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11379126/latest.log)
[crash-2023-05-02_20.29.59-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11379127/crash-2023-05-02_20.29.59-server.txt)
I update the pack to 1.0.7 it was crash again

**Comment by Emmanuel-true** [comment]
I start a new world, I haven't done anything just start up the world then the server crashed 
[latest (1).log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11382569/latest.1.log)
[debug (1).log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11382571/debug.1.log)
[crash-2023-05-03_05.31.01-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11382575/crash-2023-05-03_05.31.01-server.txt)

**Comment by Saereth** [comment]
update to 1.2 and then run 
/modernfix upgradeStructures
should sort the issue
