### ISSUE TITLE
Using Applied Energistics Wireless Crafting Terminal  sends Bows into the AE system on use

### ISSUE THREAD

**Issue by BmxDmx** [FTBTeam/FTB-Modpack-Issues#3195]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

When I have the Wireless Crafting Terminal from Applied Energestics 2 in the inventory or equipped as curio and I try to use a bow , vanilla bow or flux-infused bow, the bow is being moved  from the inventory into the AE system. 

### Steps to reproduce

1. Equip AE Wireless Crafting Terminal
2. Use Bow

### Expected behaviour

Bow teleport from inventory into AE2 system

**Comment by Saereth** [comment]
awt update in new version seems to have fixed this
