### ISSUE TITLE
Refined Storage Addons

### ISSUE THREAD

**Issue by malezjaa** [FTBTeam/FTB-Modpack-Issues#3196]
### Modpack

FTB Skies

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/rs-requestify
https://www.curseforge.com/minecraft/mc-mods/refined-cooking
https://www.curseforge.com/minecraft/mc-mods/rslargepatterns
https://www.curseforge.com/minecraft/mc-mods/more-refined-storage

Please add these mods, there is far too little refined storage in this modpack. If not all of them then at least RS cooking and More Refined Storage

**Comment by RatherChaotic** [comment]
I quite agree, AE2 definitely gets aton more attention which leaves RS in the dust

**Comment by Micaxs** [comment]
Just want to mention when you want to suggest such mods, make sure there are 1.19.2 versions as that's the version of minecraft that ftb skies is running on. (2 "more-refined-storage" and "rslargepatterns" of your suggested mods didn't update for quite a long time and will simply not work).

You can always add these mods yourself as well (the one's that do have a 1.19.2 version off course).

**Comment by Saereth** [comment]
we've considered all this, we've added all the ones we're going to add. The ones we didnt add were for performance or ae2 vs rs easy of use balancing. They should mostly work fine if you want to add them to your own instance. 

RS is easier, has no channels and is cheaper to get into. Ae2 has more options for power users as a trade off in this pack
