### ISSUE TITLE
Combining damaged crude elytras gives a regular elytra

### ISSUE THREAD

**Issue by DWiz24** [FTBTeam/FTB-Modpack-Issues#3198]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.6.0

### Describe the bug

Title, see screenshot

### Steps to reproduce

Make 2 crude elytra.
Damage at least one.
Put them in the crafting grid, hit the other recipes button

### Expected behaviour

Only able to combine them to make another crude elytra

### Screenshots

![2023-04-21_16 14 18](https://user-images.githubusercontent.com/12277340/233727281-d79911a3-173b-4273-bfd5-b0f907aa4862.png)

**Comment by TheonlyTazz** [comment]
disabled Polymorph in the next version
