### ISSUE TITLE
Raw tungsten can't be pulverized for 1.5x dust

### ISSUE THREAD

**Issue by DWiz24** [FTBTeam/FTB-Modpack-Issues#3199]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.6.0

### Describe the bug

There is a 1.5x pulverizing recipe for every other raw ore, but not tungsten. 

### Steps to reproduce

Look at recipes using raw tungsten, then look at raw lead, tin, etc.

### Expected behaviour

Pulverize 2 raw tungsten-> 3 tungsten dust

### Screenshots

![2023-04-21_16 23 28](https://user-images.githubusercontent.com/12277340/233728166-df9cbaa8-3807-443e-8faf-0ac77c61ed80.png)

**Comment by TheonlyTazz** [comment]
![grafik](https://user-images.githubusercontent.com/3908847/236121329-ce0f3096-f7e2-4b82-b24a-4c692dea4425.png)
for consistency sake, ill just be adding it to the next update
