### ISSUE TITLE
Easy Villager/Piglin Invisible

### ISSUE THREAD

**Issue by neonbladez2** [FTBTeam/FTB-Modpack-Issues#3201]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

Have seen a few issues made already, basically when placing easy villager blocks in the overworld, JEI and inventory, they show up invisible. Can see some blocks such as the villager itself in the block and the bed for breeding.

### Steps to reproduce

Type @.easy into JEI and it should be visible, not just the bed/zombie floating.
When in inventory it is invisible as well.
Placing a trader or any of the blocks will be invisible as well.

### Expected behaviour

Should have icons that are easily distinguishable, and overworld placing should be fine.

### Screenshots

<img width="252" alt="image" src="https://user-images.githubusercontent.com/91413148/233746339-616bb4eb-06cf-4d68-8fc5-41ca56c8704d.png">
<img width="266" alt="image" src="https://user-images.githubusercontent.com/91413148/233746403-3017c2df-dac7-4792-a994-a657805674c5.png">
<img width="576" alt="image" src="https://user-images.githubusercontent.com/91413148/233746463-f143a63b-8555-4bb7-a6c9-3607627da878.png">

**Comment by Cujoplays** [comment]
im having a simular issue but when I place them into the world the block showed up and will take a villager and workstation but you can't right click into the blocks GUI.
