### ISSUE TITLE
One Guide loading error

### ISSUE THREAD

**Issue by MertsSavelii** [FTBTeam/FTB-Modpack-Issues#3202]
### Modpack

FTB One

### Modpack version

2.30

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11301248/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11301249/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11301250/latest.log)

### Describe the bug

I can't use one guide book. There is no data about iron tank controller.

### Steps to reproduce

open one guide book

### Expected behaviour

book categories

### Screenshots

![image](https://user-images.githubusercontent.com/77778323/233783160-23555e81-66b9-4f58-a6d5-5241c871ee92.png)

### Additional information

if you delete a folder .ftba\instances\c05d2cdb-2ab0-4bdb-9c44-bcf9946af2f3\patchouli_books\ftb_one_guide\en_us\entries\mod_content\storage\ fluids then the book starts working. However, there are no pictures in one place

**Comment by MertsSavelii** [comment]
![image](https://user-images.githubusercontent.com/77778323/233784123-fc334a8e-c648-4e72-b390-be0c9898dea1.png)
![image](https://user-images.githubusercontent.com/77778323/233784134-bf2ba9e9-e420-44b9-8c92-ade9acbbd151.png)
![image](https://user-images.githubusercontent.com/77778323/233784155-6a063f9d-dd9b-43d0-a42e-8ed3fbcc5031.png)
![image](https://user-images.githubusercontent.com/77778323/233784171-f91b98e2-5e62-4a27-ab0e-3e7fdbb30336.png)

**Comment by Saereth** [comment]
guide is removed now, its mostly redundant and was unfinished so removed it in favor of some custom ponders
