### ISSUE TITLE
Spawn gets deleted when restarting server (1.0.4)

### ISSUE THREAD

**Issue by Stinkysunstep** [FTBTeam/FTB-Modpack-Issues#3203]
### Modpack

FTB Skies

### Modpack version

1.0.4

### Describe the bug

when restarting ftb skies server it deletes the spawn island which means players fall infinitely in the void this also happens even when you create an island, /spawn sends you to the void and you fall infinitely as well.

### Steps to reproduce

1. Download 1.0.4 server files and install all files
2. Start server
3. Joining the world will have the spawn island all there
4. Restart server
5. Join world
6. Spawn gone

### Expected behaviour

the spawn island after restarting a ftb skies server (1.0.4) deletes the spawn island, sending players into falling into the void

**Comment by Saereth** [comment]
I cannot reproduce this, please provide latest.log and debug.log files
