### ISSUE TITLE
Game Crashed and idk why [FTB LOTE]

### ISSUE THREAD

**Issue by CookieGD** [FTBTeam/FTB-Modpack-Issues#3208]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.5.0

### Log Files

https://pastebin.com/QFXNnFb5

### Describe the bug

I wanted to search for Stone Lamps in REI because I needed the recipe and in the middle of typing the name in the search bar my game crashed.

### Steps to reproduce

1. select the REI search bar
2. try to enter Stone Lamp into the search bar

### Expected behaviour

Expected to see the item in REI

### Additional information

I added a few mods to my server (mainly a few combat mods, 2 QoL mods and a structure mod) but I don't think they cause this issue because it worked perfectly fine yesterday. The server did not crash, only my client.

**Comment by TheonlyTazz** [comment]
has this issue happened ever since?
i cannot seem to replicate it, so it could be a 1 off time
