### ISSUE TITLE
[Suggestion]: Add Quark and Quark Oddities

### ISSUE THREAD

**Issue by NaminBeforeGamin** [FTBTeam/FTB-Modpack-Issues#321]
### Modpack

FTB Oceanblock

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/quark
https://www.curseforge.com/minecraft/mc-mods/quark-oddities
Quark fits into this pack because it gives many QOL features and really gorgeous building blocks. Just disable its deep slate and its world gen features and you should be fine. It would be wonderful for its backpack(prolly would want to change the recipe), its shift t flex feature, its emotes in person, and the search feature in early game.

**Comment by Sunekaer** [comment]
Hi 
Quark is a huge mod and is not something you just can add to a pack.
For a mod like quark to be added to a pack will require a major pack version update.
Therefor the mod won't be added, you can add it to your own SP world, but everything might not work as intended

**Comment by Kuktar** [comment]
I added quark mainly for the chest dump feature and some of the redstone automation. Luckily the quark wiki explains all 144 features of quark. it took me almost an entire day to go through the quark config and disable many of the features. of the 144 features there are many that break this pack letting you bypass progression and even allowing swimming in the ocean infinitely. i ended up keeping 23 features.

let me know if you want to collaborate on the configs I'm more than happy to share my opinions and knowledge.
