### ISSUE TITLE
Black screen inventory bug

### ISSUE THREAD

**Issue by CommanderWori** [FTBTeam/FTB-Modpack-Issues#3210]
### Modpack

FTB Infinity Evolved Skyblock

### Modpack version

2.0.1

### Describe the bug

The modpack loads and starts perfectly fine, but when in a world all chests or other inventory blocks appear invisible. Looking directly will render the entire window (both window and fullscreen) black as long as you are facing them. Right clicking will open the inventory screen visible like normal. The screen will also turn black while browsing the pages of the "NotEnoughItems" mod, specifically pages 2 to (depending on your screen size) the end of "Applied Energistics". 

### Steps to reproduce

1. start the modpack
2. create a new world
3. try looking for the chest

### Expected behaviour

The screen should behave normal

### Additional information

The bug appeares threw both CurseForge and then FTB app. I also tested it on other PCs with the same outcome.

**Comment by Gaz492** [comment]
This may be a graphics driver issue, could you try making sure that your graphics drivers are up-to-date and let us know if the issue continues to occur.
