### ISSUE TITLE
My world loads then closes itself

### ISSUE THREAD

**Issue by FireyTwo2** [FTBTeam/FTB-Modpack-Issues#3211]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

Everything is fine until I open my world as soon as it finishes loading it closes then gives me an error saying disconnected then the game shuts.

### Steps to reproduce

Go on the Modpack,
Open the world
and hope this happens.

### Expected behaviour

I expected for it to load and i could play on my world.

### Additional information

i have none :(

**Comment by Saereth** [comment]
need your latest.log/debug.log files
