### ISSUE TITLE
Stoneblock 3 - Nether bits spawner to many mobs

### ISSUE THREAD

**Issue by M0nkey4365** [FTBTeam/FTB-Modpack-Issues#3213]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

Whenever I go to the nether dungeons, the spawners spawn too many mobs and "champion" mobs to the point where it lags the game pretty badly.

### Steps to reproduce

Go to the nether dungeons and wait around 5 minutes and notice the entity count jump up.

### Expected behaviour

Have the spawns on a timer so that they don't infinitely spawn.

### Screenshots

<img width="456" alt="javaw_sr1N0c2QYJ" src="https://user-images.githubusercontent.com/131619624/233866711-6ba9c33f-6a51-4d88-98f6-88b3c901eaae.png">
<img width="182" alt="javaw_bK8UxuPhug" src="https://user-images.githubusercontent.com/131619624/233866717-f5f68bb1-3ead-4822-96a7-eaec5ae3a07e.png">
<img width="351" alt="javaw_kdRZDGIAv0" src="https://user-images.githubusercontent.com/131619624/233866740-0ae763ef-a5c7-4057-88bb-52df2b038463.png">

### Additional information

the issue makes it difficult to go to the nether dungeons, with lag spikes and overall sluggishness. also, the overall main mobs that are spawning so much are the "brutes" and the "hoglins"

**Comment by UnRealDinnerbone** [comment]
Same as #2442
