### ISSUE TITLE
[Bug] Mekanism multi blocks have a lighting glitch and are very dark

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#3214]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

No relevant log

### Describe the bug

When you place a block that belongs to a mekanism multiblock, or fully assemble a mekanism machine thats a multiblock, the blocks them self's are a much darker shade than they should be. If you hold say a thermal evaporation chamber block, its a mellow coppery orange. If you place it, it is a extremely dark orange / black. 

Its a very minor issue, as it does not cause a lighting glitch in the chunk even and the machines work properly, but its an issue none the less. 

### Steps to reproduce

1. Join a world
2. Go to creative mode
3. Place down any mekanism multiblock block, such as a Thermal Evaporation Block
4. Observe the change in shade. 

### Expected behaviour

The multiblock blocks should be the same shade as the texture

### Screenshots

![2023-04-23_18 24 24](https://user-images.githubusercontent.com/122759195/233869480-eb9a5dc2-66de-4757-afbc-dcfc8d496cad.png)
Image contains a thermal evaporation chamber, and a fission reactor. Both are much darker than they should be, but the chunk itself has normal lighting.

**Comment by MechBFP** [comment]
I don’t have this issue at all. Perhaps a video card issue with the shader the pack yes.

**Comment by JustAnotherGhostName** [comment]
> I don’t have this issue at all. Perhaps a video card issue with the shader the pack uses.

I  can check that, though the issue does not occur on ATM8, so this is pack specific.

**Comment by johnll56** [comment]
Happens to me as well on the latest beta of FTB skies

**Comment by Saereth** [comment]
![2023-04-26_12 00 28](https://user-images.githubusercontent.com/9200909/234676412-5f9df042-70b5-4a04-a4b8-756bba324d8d.png)
fixed in next update
