### ISSUE TITLE
FTB-Direwolf20 1.8.0 Beta serverinstall linux failed to download 4 packages

### ISSUE THREAD

**Issue by phil2sat** [FTBTeam/FTB-Modpack-Issues#3217]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.8.0

### Log Files

[log.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11307384/log.txt)

### Describe the bug

When running the installer i get:
Downloaded 1050 successful, 4 failed, 0 incomplete.
Now i tried both win and linux

Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/commons-io/commons-io/2.4/commons-io-2.4.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/commons-logging/commons-logging/1.2/commons-logging-1.2.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar: server returned 404 Not Found

Its a double https:// in there, so the installer cant download the files, manually fixing the doubled https:// downloaded the files just fine.

### Steps to reproduce

Download installer file serverinstall_101_6456 linux or win exe
run it ant wait for:
Downloaded 1050 successful, 4 failed, 0 incomplete.

### Expected behaviour

Downloaded 1054 successful, 0 failed, 0 incomplete.

**Comment by Saereth** [comment]
I've forwarded this on to Gaz to have a look, was able to reproduce it myself

**Comment by Pyrogear** [comment]
exact same issue when trying to update with the serverinstall_101_6464

**Comment by freakyfreaky** [comment]
It seams that the item users of cyclic aren’t working anymore. Could this be an issue with the update

**Comment by manmaed** [comment]
See: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3256
