### ISSUE TITLE
Create Electric Motor crash

### ISSUE THREAD

**Issue by iiJonno** [FTBTeam/FTB-Modpack-Issues#3219]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

when clicking the + icon in crafting window for the create electric motor it crashes the game

### Steps to reproduce

click + on electric motor in crafting window

### Expected behaviour

not crashing

**Comment by Saereth** [comment]
need a crash log

**Comment by iiJonno** [comment]
https://mclo.gs/7dU660i
