### ISSUE TITLE
[Bug:] Botania dispenser planting not working on mystical petals

### ISSUE THREAD

**Issue by VorpalLemur** [FTBTeam/FTB-Modpack-Issues#322]
### Modpack

FTB OceanBlock

### Modpack version

1.8.0

### Describe the bug

Mystical petals in a dispenser don't plant (onto dirt or grass) and instead are thrown out the front.    This is contrary to how I know it's intended to work (from other packs).   Interestingly, I was able to plant a wheat seed onto farmland via dispenser just fine, but, again, can't do the same with petals.   

Am suspecting another mod has overridden Botania's dispenser tweak.

### Steps to reproduce

1. Place a dispenser on the ground, facing an air block over either a dirt or grass block
2. insert mystical petals of your choice
3. trigger dispenser.   Note petal is thrown out the front and not planted.
4. 

### Expected behaviour

Petal should be planted in the ground.

### Screenshots

![2021-11-16_11 02 19](https://user-images.githubusercontent.com/16469763/142049200-0ecec9d3-f1f6-4705-b540-d1b24861491c.png)

**Comment by Raidobw2** [comment]
Hello. Unfortunately, I don't think this is a bug after validation, and from experience as well. You might be referring to the Mechanical User from Extra Utilities. I think there is a similar block in OceanBlock, maybe you'll want to check it out. Search "user" or "mech" in JEI and you'll find it.

I've done a test using a new custom CurseForge instance with the Botania mod and here are the results:
![petal_seed_dispenser](https://user-images.githubusercontent.com/17010632/142140789-eb56e73b-77e4-4e0c-8a4c-14e78a2b2cd4.gif)

As you see, all but the wheat seeds on farmland are shot out of the block as an item. This is indicated by the dispenser behavior classes in the Botania code, accessible at: https://github.com/VazkiiMods/Botania/tree/master/src/main/java/vazkii/botania/common/block/dispenser
![image](https://user-images.githubusercontent.com/17010632/142140985-90aca2ec-1d4f-41af-bdd0-36c4f6ad4761.png)

If you want to see the code for the petal when they are planted, it's available at: https://github.com/VazkiiMods/Botania/blob/master/src/main/java/vazkii/botania/common/block/decor/BlockBuriedPetals.java
It's indeed growable but it won't be dispensed by a dispenser. Only machines capable of simulating player actions (right-click) will be able to plant those.

**Comment by VorpalLemur** [comment]
Ok, well your evidence of creating a fresh install with just botania in it and testing it is pretty compelling, and, I'll be honest here, I wouldn't trust my own memory as far as I can throw it.... but I am *pretty* sure this is supposed to work? Or at least I'm certain I've had recent experience of it working.   In fact I doublechecked my Enigmatica 6 world and,  yup, works fine with 2 dispensers 
![2021-11-19_23 21 58](https://user-images.githubusercontent.com/16469763/142718442-ea87f509-f65c-436c-b4bb-a2ee080ec7dc.png)

so I'm relieved i'm not senile.. at least not today :)

also I'll the Lexica Botania, chapter called Dispenser Planting:
![Screen Shot 2021-11-19 at 11 07 34 PM](https://user-images.githubusercontent.com/16469763/142717951-b64ae5d3-9d80-4726-9546-da96d0ed4769.png)

which seems to imply that it was intended to work?   Dunno.   Anyways, just because it works in a different modpack doesn't make it this packs problem and I appreciate the attention you've given this.  Cheers

**Comment by Raidobw2** [comment]
That's because in E6 Quark is installed and in OB it's not. Quark can enable placing blocks with dispensers.
`"Dispensers Place Blocks" = true`.
