### ISSUE TITLE
Download errors during server setup

### ISSUE THREAD

**Issue by KekkusMaximus** [FTBTeam/FTB-Modpack-Issues#3220]
### Modpack

FTB Ultimate Reloaded

### Modpack version

1.11.0

### Log Files

Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/lzma/lzma/0.0.1/lzma-0.0.1.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/java3d/vecmath/1.5.2/vecmath-1.5.2.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar: server returned 404 Not Found

### Describe the bug

Pretty much self explanatory

Download links are broken thus leading to broken installation. Can't fix it because I don't know the correct file paths to manually install them.

### Steps to reproduce

1. Launch the installer
2. Use default settings
3. it breaks by itself

### Expected behaviour

It should install the files correctly leading to a working server

### Additional information

As far as I know this behaviour is appearing both in the windows version and the arm-linux version

**Comment by manmaed** [comment]
See: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3256
