### ISSUE TITLE
Refined Storage Auto-crafting with Mekanism Ore Doubling

### ISSUE THREAD

**Issue by AdventureLady** [FTBTeam/FTB-Modpack-Issues#3221]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

While trying to auto-craft iron and gold ingots through Mekanism using the ore doubling setup (Purification chamber > Crushing Factory > Enriching Factory > Smelting Factory (Basic tier machines)) the refined storage crafting monitor indicates that the crushing factory will not accept iron clumps or gold clumps.

The way I am setup is with R.S. crafters placed behind the mekanism machines (but facing into them) and the respective crafting patterns in each crafter.

If you need anymore information that I haven't provide, please let me know. 

### Steps to reproduce

1. Create a crafting pattern for each part of the process (raw ore > ore clump; ore clump to dirty ore dust; dirty ore dust > ore dust; ore dust to ore ingot). - _I have only tried it with iron and gold so far; however, I am confident the other ores will do the same._
2. Insert patterns into respective crafters facing a purification chamber and basic crushing factory.
3. Request ore ingots from the R.S. system.

### Expected behaviour

I expected to start with raw iron & gold ore and end up with iron and gold ingots

### Screenshots

![2023-04-24_12 27 11](https://user-images.githubusercontent.com/29524786/234060273-1a7d2795-7ceb-4459-aae4-31fefa8617f1.png)
![2023-04-24_12 27 25](https://user-images.githubusercontent.com/29524786/234060281-98c467a7-5495-4a18-83e9-45f8f2fcb248.png)
![Crafter Manager](https://user-images.githubusercontent.com/29524786/234060285-ce84fe79-6d16-40f6-81fc-eeb6b8e5df17.png)
![Crafter Manager2](https://user-images.githubusercontent.com/29524786/234061180-32d0d6ac-98d1-451a-8e55-810dddd14f1b.png)
![Image-GoldProcess1](https://user-images.githubusercontent.com/29524786/234060288-23c0b10f-f487-4224-b59b-af5fea35a1c1.png)
![Image-GoldProcess2](https://user-images.githubusercontent.com/29524786/234060291-5611ec78-9d24-4e71-808a-954684d09f39.png)
![Image-IronProcess](https://user-images.githubusercontent.com/29524786/234060293-5f8c088d-cbbf-47a1-958e-b7a8d51117b1.png)

**Comment by AdventureLady** [comment]
I wonder if my world might be corrupted..? I am not sure how that may have happed, as everything else seems fine. However, I created a fresh world in creative mod and setup the ore doubling up to the crusher stage and everything worked fine.

**Comment by Saereth** [comment]
I tested this as well and was unable to reproduce this issue. You can send me your world save if you want me to investigate it further.

**Comment by AdventureLady** [comment]
I may do that. I started a new survival world and want to see if that makes a difference. I am nearly ready to setup R.S. with Meka.

**Comment by AdventureLady** [comment]
[HighintheSky_2.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11337758/HighintheSky_2.zip)

**Comment by AdventureLady** [comment]
So, in the new survival world I created, I am still running into the same issue.. It says machine does not accept item for the silicone with the AE inscriber, but it continues to work (R.S. is probably wanting to put in a full stack bu it accepts just one silicone at a time). However, with the crushing factory, it just doesn't do anything.

**Comment by AdventureLady** [comment]
It does, however, work with the crusher, as opposed to the basic crushing factory which does not work for some reason.
