### ISSUE TITLE
FTB Inferno won't exit worlds.

### ISSUE THREAD

**Issue by Winterssystem** [FTBTeam/FTB-Modpack-Issues#3222]
### Modpack

FTB Inferno

### Modpack version

1.7.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11315100/latest.log)

### Describe the bug

When I click "Save & Quit to Title" the game saves, but then gets stuck on the "Saving World" screen. The only way to exit from there is to manually kill the instance.

### Steps to reproduce

1. Load into a world
2. Click "Save and exit"
3. The game gets stuck on "Saving World" and the log acts as if it was never told to shutdown the server

### Expected behaviour

The game should exit when you click exit

### Screenshots

![Screenshot 2023-04-24 153720](https://user-images.githubusercontent.com/90431178/234131287-642afdd7-4cf4-4788-ab60-cc579b5c8bf8.png)

**Comment by Saereth** [comment]
this should be fixed in the new update

**Comment by Winterssystem** [comment]
alright! thanks!
