### ISSUE TITLE
Remove "Inventory Bomb" from the random chance cubes

### ISSUE THREAD

**Issue by socrlax24** [FTBTeam/FTB-Modpack-Issues#3226]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

I spent _hours upon hours upon hours_ crafting and upgrading my equipment, only to open a chance cube and have all of my items get instantly and permanently deleted. Sure, I can load a backup, but why is this even a thing?

**Comment by Saereth** [comment]
chance cubes are clearly marked use at your own risk for reasons like this
