### ISSUE TITLE
Reborn Storage for Refined Storage

### ISSUE THREAD

**Issue by d00mbr1nger** [FTBTeam/FTB-Modpack-Issues#3228]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

Instead of having multiple walls of crafters, would be nice to just have the crafter multiblock.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/rebornstorage

Adds multiblock crafter and larger drives.

**Comment by Saereth** [comment]
Previously considered and decided not to use due to tps impact on larger servers
