### ISSUE TITLE
[Bug]: Basalt Essence incorrect recipe

### ISSUE THREAD

**Issue by CariTheKitty** [FTBTeam/FTB-Modpack-Issues#323]
### Modpack

FTB Ocean Block

### Modpack version

1.8.0

### Describe the bug

Basalt essence from Basalt Seeds making Basalt (raw) block from chisel, not Basalt Vanilla block.

### Steps to reproduce

Take 8 Basalt Essence, make a donut shape in a crafting grid, yields 16 Basalt (Raw)

### Expected behaviour

Should make Basalt (vanilla block)

### Screenshots

[basalt](https://user-images.githubusercontent.com/30705207/142063650-4f0333d4-2ccd-485f-b979-2bd7ebdcbe63.png)

**Comment by quietust** [comment]
How did you get basalt seeds in the first place? Last I checked they could only be crafted using Chisel basalt, and that doesn't seem to spawn naturally anywhere I've seen.

**Comment by CariTheKitty** [comment]
I used regular basalt in the recipe, using the jar mod to make the basalt

**Comment by quietust** [comment]
> I used regular basalt in the recipe, using the jar mod to make the basalt

My mistake - I was thinking of the Limestone seed recipe.

**Comment by Raidobw2** [comment]
Just to make sure, can it be chiseled to be the vanilla Basalt or not?

**Comment by CariTheKitty** [comment]
it can be chiseled into the correct basalt, but just seems to be a punishing extra step

**Comment by Raidobw2** [comment]
I see, thanks, we'll take a look at it.

**Comment by Sunekaer** [comment]
This isnt really a bug.
I allowed the chisel between Vanilla and Chisel basalt.
By default, MA gives chiselled basalt and uses chiselled basalt tag.
