### ISSUE TITLE
KubeJS error with right click operation causing block and entity disappearances + GUI won't pop up in Minecolonies.

### ISSUE THREAD

**Issue by LoessCode** [FTBTeam/FTB-Modpack-Issues#3231]
### Modpack

FTB Inferno

### Modpack version

1.2.1 [Stable]

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11329641/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11329642/latest.log)

### Describe the bug

When we join the world, a red error pops up which says a bunch of kubeJS errors were found. 

When performing operations like using mutandis, right clicking on minecolonies blocks / entities, mutating bees, the error pops up in server logs and the plant dissapears / Minecolonies GUI won't open / Bee will disappear.

Stopped us from progressing completely and a fix would be greatly appreciated. 
 

### Steps to reproduce

Just playing the game. 

### Expected behaviour

The trees were supposed to mutate to other plants, the minecolonies GUI should open and the bee should not disappear.

**Comment by Saereth** [comment]
fixed in 1.7.0+
