### ISSUE TITLE
mod: Campanion not able to be used at all

### ISSUE THREAD

**Issue by drewsuhferr** [FTBTeam/FTB-Modpack-Issues#3232]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.6

### Describe the bug

All items stemming from mod Campanion are inaccessible. You cannot craft anything from that modpack.

### Steps to reproduce

start a default server -> attempt to view the recipes in your inventory -> clicking the recipes from the inventory fails to produce an instance that shows you the recipe. -> knowing the recipe and attempting to place it in the crafting spot does not produce the expected Campanion items. instead it is not recognized and does not produce anything.

### Expected behaviour

Should expect all items from Campanion to be craftable

**Comment by TheonlyTazz** [comment]
I had added Campanion in v1.4.0, but it caused alot of crashes, thus i decided to disable all the recipes (basicly disabling the mod) in v1.5.0.

## 1.5.0 changelog:
Disable Campanion Mod Recipes, Mod will be removed in a later update


I just forgot to remove it in the v1.6.0 update, will be removed in v1.7.0

**Comment by drewsuhferr** [comment]
Ah apologies just started using the pack so I didnt know that update was in place. Thank you for taking time to respond!
