### ISSUE TITLE
FTB Skies 1.06 server install failed file download

### ISSUE THREAD

**Issue by Warzer1** [FTBTeam/FTB-Modpack-Issues#3235]
### Modpack

FTB Skies

### Modpack version

1.06

### Describe the bug

During install of serverinstall_103_6458.exe for SKIES 1.06 4 files were unable to download and you can see why is the cmd line. 1 url is fed into another url.

Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/commons-io/commons-io/2.4/commons-io-2.4.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/commons-logging/commons-logging/1.2/commons-logging-1.2.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar: server returned 404 Not Found

manual d/l works if you remove the first https portion, but no idea where these files go.

### Steps to reproduce

1. Download serverinstall_103_6458.exe for windows
2. run serverinstall_103_6458.exe
3. default options
4. reports failed to download 4 files continue?
5. continuing seems to extract files then proceeds without the missing files.

### Expected behaviour

not have missing files during install

### Additional information

was installer for windows

**Comment by Warzer1** [comment]
1.07 has the same issue
[install107.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11346388/install107.log)

**Comment by manmaed** [comment]
Moving to https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3256
