### ISSUE TITLE
Direwolf20 1.19 crashes on launch

### ISSUE THREAD

**Issue by vladmw5** [FTBTeam/FTB-Modpack-Issues#3238]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.9.0

### Log Files

[hs_err_pid7072.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11342219/hs_err_pid7072.log)

### Describe the bug

When I try to start the instance, it crahses with the error shown on the screenshot below

Reinstalling the instance and switching to other versions did not help to fix the issue

### Steps to reproduce

1. Launch the instance
2. See its crashing

### Expected behaviour

I expect the game to launch so I can play 

### Screenshots

![image](https://user-images.githubusercontent.com/75910284/234829557-9b745dde-5836-4e6e-a1dd-62a50bb1babe.png)

**Comment by MechBFP** [comment]
Its a Radeon driver issues. Search for atio6axx.dll online and you will see reports back to Oct 2022 of people having this issue. Update your driver to the latest version. If that doesn't work, then roll back your driver to a version some time before Oct 2022.

**Comment by vladmw5** [comment]
> Its a Radeon driver issues. Search for atio6axx.dll online and you will see reports back to Oct 2022 of people having this issue. Update your driver to the latest version. If that doesn't work, then roll back your driver to a version some time before Oct 2022.

I am not sure what drivers I should update since my GPU is Nvidia

**Comment by 69Werewolf69** [comment]
Same problem. When starting the Play Offline, everything works, but my colony is not available for management. Same error when running online.

**Comment by 69Werewolf69** [comment]
Disabling auto-update of Windows drivers and reinstalling the video driver from the manufacturer helped. Apparently UWP drivers are in conflict.

**Comment by Saereth** [comment]
yeah this is not a pack issue it's an amd driver issue, best of luck getting your systems sorted, I know its annoying but nothing we can do from the pack side of things
