### ISSUE TITLE
[Bug]: Mekanism Creative Bin causing game to freeze

### ISSUE THREAD

**Issue by JTHm3** [FTBTeam/FTB-Modpack-Issues#324]
### Modpack

FTB Oceanblock

### Modpack version

1.8.0

### Describe the bug

When taking items out of a filled creative bin in the player crafting inventory, the game freezes if you shift click the items.

### Steps to reproduce

1. put an item in a mekanism creative bin
2. open inventory
3. place creative bin in player crafting slot
4. shift click item from bin into inventory 
5. game freezes

### Expected behaviour

items from the bin will be put in the inventory (maybe one stack at a time will solve the problem)

**Comment by Sunekaer** [comment]
Im not able to recreate this issue.
Please reopen if you still have this issue in the newest version of the pack
