### ISSUE TITLE
my modpack keep crashing 

### ISSUE THREAD

**Issue by MRlonely3244** [FTBTeam/FTB-Modpack-Issues#3241]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

[crash-2023-04-25_23.51.13-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11346197/crash-2023-04-25_23.51.13-client.txt)

### Describe the bug

my modpack keep crahsing pls help

### Steps to reproduce

s

### Expected behaviour

s

### Screenshots

s

### Additional information

s

**Comment by UnRealDinnerbone** [comment]
Looks like there was an issue loading a config file. You can fix this by deleting the MineTogther config, doing this should fix the issue

Same as #3007

**Comment by MRlonely3244** [comment]
where is that?

**Comment by MRlonely3244** [comment]
> Looks like there was an issue loading a config file. You can fix this by deleting the MineTogther config, doing this should fix the issue
> 
> Same as #3007



where is that

**Comment by UnRealDinnerbone** [comment]
Sorry, gave the wrong response, thought it was another issue. For now, this is a bug in MineTogher and you can fix this by disabling MineTogher
