### ISSUE TITLE
Move Items Button in Refined Storage Crash

### ISSUE THREAD

**Issue by ChosenArchitect** [FTBTeam/FTB-Modpack-Issues#3245]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

Trying to craft something that has more then 9 items required to craft into the grid will crash

### Steps to reproduce

1. open refined storage crafting grid
2. search for Spectrolus (this is just one of many)
3. hit R over it
4. Shift-click the + (move items button)

### Expected behaviour

pull items into the grid

**Comment by Saereth** [comment]
reported to RS but no updates from RS for a while so far unfortunately...

**Comment by manmaed** [comment]
@Saereth can you please provide a link to the issue :) stil 1.3.1
