### ISSUE TITLE
Flux Networks Textures are Broken

### ISSUE THREAD

**Issue by ChosenArchitect** [FTBTeam/FTB-Modpack-Issues#3246]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

Visual Bug with Flux Networks

### Steps to reproduce

Just look up flux networks

### Expected behaviour

no texture issues

### Screenshots

![2023-04-27_17 30 47](https://user-images.githubusercontent.com/35053440/235004868-a1bb8b54-c864-4837-9204-cf4598535bf1.png)

**Comment by MechBFP** [comment]
Can confirm.
