### ISSUE TITLE
Quest not working well

### ISSUE THREAD

**Issue by daniloqz** [FTBTeam/FTB-Modpack-Issues#3248]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

After the update (1.0.6 to 1.0.7), quests are not completing even with the item done. I noticed that, sometimes, it is completed when I do some craft whatsoever. I tried to restart my game twice, same problem.

### Steps to reproduce

1. make some quest item
2. quest is not completed, even if I play, click with the item in the air or put it on the ground and break
3. craft a stick, for example, quest is finished, or not.

### Expected behaviour

quest completed

### Screenshots

![Captura de tela 2023-04-28 001227](https://user-images.githubusercontent.com/36247183/235052477-030fea7f-495a-4519-a5fd-5c32aab0cdb6.png)
I made the pedestal, but even crafting something random like a stick, it wasn't completed

**Comment by MechBFP** [comment]
Yup quest book is quite broken now. I have to enable cheat mode and force complete almost all of them now as a result of the issue you described. I think it has to do with whatever that unified system is with the rainbow ingot icon that appears in the recipes list.

**Comment by Scripter84** [comment]
This is also happening in my instance on FTB Skies. Example quests: 

Cobbled Together
This is not a Drill

Some other quests have completed fine, if I was to take a guess I would think it may have to do with FTB skies custom mods?

**Comment by Wilvyn1** [comment]
Having the same issue, hope they get it looked at soon, was only since i updated the pack that it started with the issue

**Comment by Wilvyn1** [comment]
> Having the same issue, hope they get it looked at soon, was only since i updated the pack that it started with the issue

I downgraded to 1.0.6 and the issue seems to not be there. will be waiting to upgrade for a bit longer I think

**Comment by Michael-McKinley** [comment]
Also happening in a completely new game based on the 1.0.7 game build. 
I installed this mod pack today and went straight to the new 1.0.7 version (the savefile was not migrated from a 1.0.6 game). 

1. Teleported to the FTB Island (with the lake)
2. Cleared all the "Intro" quests that could be done immediately.
3. Started working on a few quests in the "Getting Started" section.   Each updated when I completed the next quest or new crafting recipe. 

For example:

1. Right-clicked on the ground until I had a stack of stone pebbles and soil. The cobblestone quest did not update.
2. Harvested the flax, receiving eight strings. The cobblestone quest completed, but the flax quest did not. 
3. Punched few logs (not enough to trigger the log quest) and built a chest.  As soon as the chest was built, the flax quest updated.

**Comment by daniloqz** [comment]
> > Having the same issue, hope they get it looked at soon, was only since i updated the pack that it started with the issue
> 
> I downgraded to 1.0.6 and the issue seems to not be there. will be waiting to upgrade for a bit longer I think

I did it too, solved my problem.

**Comment by alecium** [comment]
I discovered a solution to this issue which you can do until such time that they issue an update or hotfix.

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3281

**Comment by daniloqz** [comment]
> I discovered a solution to this issue which you can do until such time that they issue an update or hotfix.
> 
> #3281

tell to us here, please

**Comment by daniloqz** [comment]
> I discovered a solution to this issue which you can do until such time that they issue an update or hotfix.
> 
> #3281

thank you! I'm playing in 1.0.6, i will test it
