### ISSUE TITLE
Creative Source Jar

### ISSUE THREAD

**Issue by Badasseddy** [FTBTeam/FTB-Modpack-Issues#3251]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

When breaking the Creative Source Jar after having placed it in the world, despite using tool that has the green tick box in WAILA, it disappears rather than going back to your inventory (I used a Netherite Paxel)

### Steps to reproduce

Place Creative Source Jar in world
Break with adequate tool

### Expected behaviour

Get the item back in inventory

**Comment by Saereth** [comment]
use a cardboard box to move them, they're typically only meant for creative plaeyrs so it doesnt drop a block when broken by design
