### ISSUE TITLE
Buried treasure not generating when maps are found

### ISSUE THREAD

**Issue by Lime-Tophat** [FTBTeam/FTB-Modpack-Issues#3253]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.7.0

### Describe the bug

Buried treasure chests not generating on my server

### Steps to reproduce

1. Find Buried treasure map
2. Go to X on map
3. Not able to find chest

### Expected behaviour

Buried treasure chest not generating

**Comment by Saereth** [comment]
this should be fixed in the new update which has the fixed quark
