### ISSUE TITLE
Decorative Mods

### ISSUE THREAD

**Issue by Kismet-Scarlet** [FTBTeam/FTB-Modpack-Issues#3254]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

This suggestion isn't related to any problem. This is more like a feature request.

I'm suggesting some mods that will enhance the building and general experience in this modpack by pitching in some cosmetic mods that's available in 1.19.2. 

These cosmetic mods including the ones that includes decorative blocks and items to add more style and immersion in builds. 😊

### Mod suggestion

Macaw's Bridges: https://www.curseforge.com/minecraft/mc-mods/macaws-bridges
I mean, most people would build floating islands, bridges definitely add such wonderful aesthetic connecting each place together.

Macaw's Doors: https://www.curseforge.com/minecraft/mc-mods/macaws-doors
If you're getting Macaw's bridges, this one's a good additional too. This opens more door of opportunities to add good touches in your build.

Macaw's Fences and Walls: https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls
Macaw's Trapdoors: https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors
Macaw's Windows: https://www.curseforge.com/minecraft/mc-mods/macaws-windows
Macaw's Roofs: https://www.curseforge.com/minecraft/mc-mods/macaws-roofs
Macaw's Lights and Lamps: https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps
To complete the collection that is. I'm sure a lot of builders are very fond of Macaw's mods.

MrCrayfish's Furniture Mod: https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod
Additional furnitures that will add immersion especially with multiplayer worlds. Who doesn't want a tea party with actual chairs and tables with friends?

Cosmetic Armor Reworked: https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked
You wanna show your cute minecraft skin and still wearing your armor? Yes, why not have cosmetic armor? You can either hide your armor or repurpose your botania aesthetic stuff.

Corail Tombstone: https://www.curseforge.com/minecraft/mc-mods/corail-tombstone
Dying with style? This totally got you. Or maybe you want to make a decorative cemetery. It also comes with some interesting systems like disenchanting and voodoo poppets.

Botany Pots: https://www.curseforge.com/minecraft/mc-mods/botany-pots
Ofcourse, this is given if other players would like another means to farm plants. To be fair, we don't even have mystical agriculture so it shouldn't affect the way we farm at the moment. It's good decorative and encourages players not to grow their sugar canes and bamboos too long. 😄

Anyway, here are the stuff I can list that supports this certain MC version. I'm sure there will be others who can come up with more suggestions.

**Comment by Saereth** [comment]
Weve added a few more cosmetic mods with the recent updates, I love mcaws's stuff but the pack is just large right now. You can add them to your own instance and it wont break anything but adding them for us is pushing the pack beyond the memory average requirements for our average users.
