### ISSUE TITLE
"Missing Files/Downloads" x 4 - Server Install

### ISSUE THREAD

**Issue by DaddyItsSticky** [FTBTeam/FTB-Modpack-Issues#3256]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

Updated the client and my local server to 1.0.7, and when installing fresh the server, the console warned of 4 missing file downloads, and asked if I wished to continue, which I said yes to.

I launched the client and I am able to connect to my world on the new server files, however I haven't investigated further to find the deficiencies. 

Also got hella fps lag compared to last version. Good drop of about 20-30%

### Steps to reproduce

1. Download 1.0.7 Windows Server Installer
2. Run Installer
3. Follow prompts
4. See the download fail message
5. continue or cancel y/n (yes)

### Expected behaviour

I expected the installer to run through the downloading and then automatically close itself like the older version installers.

**Comment by manmaed** [comment]
reported to server downloader tracker: https://github.com/CreeperHost/modpacksch-serverdownloader/issues/18

**Comment by itay347** [comment]
Exact same problem happened right now when I tried to install StoneBlock 3 version 1.6.1

log - https://pste.me/@/b5KzAC0XbmU

**Comment by Rothop** [comment]
specifically, it looks like the url is wrong on 4 files. 

Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/commons-io/commons-io/2.4/commons-io-2.4.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/commons-logging/commons-logging/1.2/commons-logging-1.2.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar: server returned 404 Not Found

when i type in the url with the duplicate "https://libraries.minecraft.net/" I can download the files locally, I'm not sure where to put them for the install

**Comment by KillerRat89** [comment]
any updates on fixing this?

**Comment by manmaed** [comment]
we are waiting for a fix to be released

**Comment by ztk4** [comment]
For anyone else running into this (while waiting for this release or in the future), I was able to work around it as follows:

 1. When the installer prints the prompt like "Failed to download some files, continue [y/n]", scroll up and find all of the "Error downloading..." messages.
 2. Fix each broken link (in this case, remove the redundant https://libraries.minecraft.net/), and download the .jar file at that link.
 3. Place it into the mods/ folder in your server directory (just like the old days of modding lol)
 4. After all of the errored downloads are added to the mods/ directory, type y and hit enter on the install prompt
 5. It will finish installing the server successfully now that you've manually added the jars that failed to be auto-downloaded.

**Comment by KillerRat89** [comment]
how do you see witch ones are not downloading

**Comment by JHthe4** [comment]
@ztk4 Thanks for the tip! Are you sure that placing the jars manually in the mods/ directory is enough? From the context of the other files being downloaded around the broken links, it seems that they probably belong somewhere deep in the libraries/ directory instead. Thanks!

**Comment by JHthe4** [comment]
Also, for lazy people, here are the wget commands to download the missing files: 

`wget https://libraries.minecraft.net/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar`
`wget https://libraries.minecraft.net/commons-logging/commons-logging/1.2/commons-logging-1.2.jar`
`wget https://libraries.minecraft.net/commons-io/commons-io/2.4/commons-io-2.4.jar`
`wget https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar`

**Comment by ztk4** [comment]
@JHthe4 AFAIK pretty much all .jar files go into the mods/ folder (I think the main exceptions are the server .jar and forge loader .jar in the root dir).

There are other resources that get downloaded during install (e.g. kubejs scripts, models and resources, etc.), so if download fails on those it may be trickier to track down where to place those files. 

Thankfully much of the working state on disk is generated by the mods themselves when the server is first started (e.g. default config files), so there's really only a select few places you should expect downloads to be for.
