### ISSUE TITLE
Game *sorta* crashing on every single backup

### ISSUE THREAD

**Issue by cembohan** [FTBTeam/FTB-Modpack-Issues#3257]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11354563/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11354564/latest.log)

### Describe the bug

no issues while the game is running, i have tested mspt with several runs of spark, my average tps is 20. however,
as soon as the chat says started a backup, i soft disconnect from the game. i am in the game, can move but can't interact with anything. i can press exit to main menu but that doesn't even go through, i have to kill instance every time. At first it started happening at 1.0.7 version, then i downgraded to 1.0.6 with a fresh instance, just copying my backup, and the same issue kept happening.

### Steps to reproduce

1.

### Expected behaviour

-

### Additional information

backup files are currectly at 116Mb in zip form. Never had any issues similar to this before,
let me know if i can supply any additional info

**Comment by Saereth** [comment]
this was a duplicate issue and should now be resolved in the new 1.2 update
