### ISSUE TITLE
Building Gadgets failed to paste.

### ISSUE THREAD

**Issue by squillis** [FTBTeam/FTB-Modpack-Issues#3258]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

N/A.

### Describe the bug

I'm trying to use the copy paste gadget from Building Gadgets, and if I try to paste something from one world to another it says  "Paste Failed, MC Version (1.12.2.x) is not supported. Please use only templates that were build for (1.19.2) -> ()"
It works when I paste in the same world but not when I do it from world to world. This is all copy and pasted from FTB Skies pack, same versions. Any idea how to fix this?

### Steps to reproduce

1. Use copy/paste gadget to copy the build.
2. Change worlds.
3. Try to use template manager to paste build.
4. Get error message listed above and in screenshot.

### Expected behaviour

Paste in the build.

### Screenshots

![2023-04-28_12 07 05](https://user-images.githubusercontent.com/14357840/235200093-f1e7a69d-4182-4938-851a-31ed155ffbb1.png)

**Comment by Saereth** [comment]
This is not someting I can do anything to help with from a packdev standpoint, you might want to head over to the building gadets github to get support
https://github.com/Direwolf20-MC/BuildingGadgets
