### ISSUE TITLE
[Bug]: lossing item of the interaction of blood magic and trinkets mods

### ISSUE THREAD

**Issue by smig00** [FTBTeam/FTB-Modpack-Issues#326]
### Modpack

Ftb Oceanblock

### Modpack version

1.8.0

### Describe the bug

when dying from a blood sacrifice and you have a broken totem trinket activated when you die you lose all the items in your inventory with no gravestone or gravestone log

### Steps to reproduce

broken totem trinket
dying by sacrifice with blood magic

### Expected behaviour

losing items withouth a gravestone ore gravestone log

**Comment by Raidobw2** [comment]
Could be linked to WayofTime/BloodMagic#1861 and #156.

To be investigated.

**Comment by Sunekaer** [comment]
Yeah sounds like duplicate of 156.
