### ISSUE TITLE
Unifying Honey on FTB skies

### ISSUE THREAD

**Issue by 5ully** [FTBTeam/FTB-Modpack-Issues#3260]
### Modpack

FTB Skies

### Modpack version

Latest

### Log Files

n/a

### Describe the bug

There is 4 types of honey and only one work, please unify the honey types or allow for any of them to be submittet.
Even if one way is intended, this is a bad concept that punishes players for "taking the wrong route". 😠 

### Steps to reproduce

n/a

### Expected behaviour

Any honey type to work

### Additional information

We can discuss it on discord if that is more fitting.

**Comment by Saereth** [comment]
unification is not entirely possible, they all use forge:honey tag but not all the machines accept tagged fluid and most of the producers only produce their specific time and arent changeable. best I can really do is put a note on the quest that it must be productive bees honey as thats the route they're intended to use anyway

**Comment by 5ully** [comment]
I guess accepting any doesnt work for fluids in quests?
