### ISSUE TITLE
Refined Storage receivers inside compact machines get disconnected on server restart.

### ISSUE THREAD

**Issue by anuzsubedi** [FTBTeam/FTB-Modpack-Issues#3261]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

So I have two refined storage receivers inside two compact machines and whenever the server restarts I have to manually get the cards from the transmitters, right click on the receivers and put the cards back in the transmitters. It has happened about 3 times. 

### Steps to reproduce

1. Program a receiver inside a compact machine. 
2. Restart the server. 
3. The receiver will lose connection.

### Expected behaviour

I expect the reciever to retain the connection.

**Comment by Saereth** [comment]
have you verified they are chunkloaded with ftb chunks?

**Comment by wyvernstar** [comment]
i'm having the same issue, my compact machine already chunk loaded with ftb chunks, but every time got disconnected

**Comment by anuzsubedi** [comment]
I think it was a server specific issue. Idk how it is solved but it solved itself without even updating the server version from 1.0.6. The only thing that changed was I just used to take the network card and re-connect it but the last time it happened I just took the cards out of the transmitter and put back. Idk if I should close the issue.
