### ISSUE TITLE
Inventory deleted when the initial teleport from the Starter ship to a new island

### ISSUE THREAD

**Issue by Michael-McKinley** [FTBTeam/FTB-Modpack-Issues#3262]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

Teleporting from the starter ship to a newly-created, single-player island deleted all quest reward items collected before the teleport.

When the teleportation completes, your inventory is empty, and the spawn equipment (saplings, bonemeal, apple, Akashic Tome, Questbook) is automatically regenerated.  None of the quest rewards previously collected remain.

### Steps to reproduce

1. Start a new 1.0.7 game
2. Open the questbook, complete all possible quests, and claim the rewards.
3. Use the gateway to teleport to your island (I used the FTB Island with the lake)
4. Check your inventory. 

### Expected behaviour

Either all items in your inventory should remain once the teleport is complete, or the quests should not be completable until after teleporting to your starter island.

### Additional information

This is a fresh install of the 1.0.7 build, meaning it is not an upgraded install from another version.

**Comment by Saereth** [comment]
you can no longer claim quest until you get to your starter island, should sort this
