### ISSUE TITLE
add a mod that resolves the took too long to log in message

### ISSUE THREAD

**Issue by GhestPlays** [FTBTeam/FTB-Modpack-Issues#3263]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

I suggest adding a mod where it is possible to increase the time available for login, such as random patches.

some weaker computers like mine take longer than normal to log in to the server.

**Comment by Saereth** [comment]
No  mod needed, you accomplish this with a jvm argument addition
-Dfml.readTimeout=120
