### ISSUE TITLE
Several quests that don't work as intended

### ISSUE THREAD

**Issue by fluffyfool** [FTBTeam/FTB-Modpack-Issues#3264]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

The chalk quest doesn't work i have made the chalk but it doesn't activate the quest not only until i grab something from a furnace did the quest get completed. The same issue occured with the waterlogged sand --> manasteel mesh quest i did the quest it didn't complete until i grabbed something from a furnace

### Steps to reproduce

1. make chalk
2. not complete the quest because it's broken
3. complete the quest when you grab something out a furnace

### Expected behaviour

i expected the quest to complete normally but instead i have to grab random items from furnaces

**Comment by daniloqz** [comment]
I made a post a couple of days ago about this same problem, several people are having it too. It seems to be something related to the update itself, the solution at the moment is to downgrade to 1.0.6 and the problem will be solved

**Comment by alecium** [comment]
I discovered a solution to this issue which you can do until such time that they issue an update or hotfix.

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3281
