### ISSUE TITLE
Game crashes every single time I launch it

### ISSUE THREAD

**Issue by peter9030** [FTBTeam/FTB-Modpack-Issues#3265]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

Every single time I launch my world it crashes. When I look in the crash rapport I see that a config file couldn’t be loaded. Then I fix this config file and on the next launch of my world an other config file gets corrupted. After several tries it finally loads.
So now everytime the game doesn’t launch I go inside the config folder and I delete every corrupted .toml file and hope the world launches.
I tried backing up my world, deleting the complete pack and reinstall it. Then it’s ok for a while, but afther some days the problem starts over.
I don’t know what is causing this, but I’m getting a little frustrated on it. I play other FTB packs without any problem.

### Steps to reproduce

Launch the pack
Launch my world, sometimes it loads and sometimes it stops loading

### Expected behaviour

The world should launch everytime without me having to search for corrupted .toml files

**Comment by Saereth** [comment]
this is a forge bug, yes its super annoying, we've got an issue open with forge about it
