### ISSUE TITLE
Mod Suggestion - Cat Jammies [Fabric]

### ISSUE THREAD

**Issue by farrucho** [FTBTeam/FTB-Modpack-Issues#3266]
### Modpack

FTB Legend of the Eyes

### Is your suggestion related to a problem? Please describe.

There was a mod called Cat Jammies, made for forge that people loved. The developer unfortunately didn't keep the mod updated so the community was kinda frustrated.

### Mod suggestion

 I think this mod would add a little bit of fun, without destroying any environment. It would be a fun thing to boost the player mood. https://legacy.curseforge.com/minecraft/mc-mods/cat-jammies-fabric

**Comment by TheonlyTazz** [comment]
I am sorry, but this Mod doesn't add any real additional value to the pack and currently see no use in adding it into the pack.
