### ISSUE TITLE
No more hearts from Spice of Life when upgrading to 1.0.7

### ISSUE THREAD

**Issue by DasBrain** [FTBTeam/FTB-Modpack-Issues#3267]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

After upgrading, I expect getting additional hearts for eating more food.

The Food Book tells me that I gained 10/10 hearts (as before the update), but the change log states that I can get up to 22 extra hearts.

I currently have only 111 hearts, I expected to be able to go to 123 hearts with the upgrade.

### Steps to reproduce

1. Create a world in 1.0.6
2. Max out your hearts (Optional?)
3. Upgrade to 1.0.7
4. Try to increase your hearts further

### Expected behaviour

I get more hearts

### Screenshots

![2023-04-29_22 00 21](https://user-images.githubusercontent.com/652983/235322272-54ad4df6-f8cf-45a3-a390-5bca5843061e.png)

**Comment by Janitor53** [comment]
Deleting file saves\your_save_name\serverconfig\solcarrot-server.toml will fix the issue. Usually, deleting whole serverconfig subfolder from the save after upgrading the pack will help with such things.

**Comment by Saereth** [comment]
server config updater has been set to overrite these files for 1.0.8 so should sort that
