### ISSUE TITLE
[Bug/Issue] Compact Machines no lighting - FTB Skies

### ISSUE THREAD

**Issue by RoutYMO** [FTBTeam/FTB-Modpack-Issues#3268]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

Some Compact Machines give off no light after creation.
Seemingly random which ones do and don't.
When they're first set up, they are fine, but then after a while they go dark.

Placing/removing blocks will return light to that block and just that one block.
Glowstone was placed in one to help light up the machine but even they aren't giving off light (see image).
Pedestal Mod's glowstone upgrade emits light as expected, but only a small amount.

### Steps to reproduce

Don't really have a step-by-step as it happens to some and not others.

### Expected behaviour

The walls of the machine should emit light, but they're not.

### Screenshots

![2023-04-29_23 37 54](https://user-images.githubusercontent.com/132172885/235326942-7b877190-a90f-452f-8c54-d98f2a068448.png)
![2023-04-29_23 39 54](https://user-images.githubusercontent.com/132172885/235326969-c7beb4d0-4e83-49da-bfeb-0b6b5993d1b5.png)
![2023-04-29_23 40 11](https://user-images.githubusercontent.com/132172885/235326975-e05034e8-dc6b-4d23-ae8f-1c017b1bda85.png)
![2023-04-29_23 40 26](https://user-images.githubusercontent.com/132172885/235326984-7d2b31b5-9079-41b3-9549-19b96bba80ad.png)

**Comment by Saereth** [comment]
should be fixed in 1.0.8 update, may not be retroactive for already existing cms though
