### ISSUE TITLE
[Suggestion]: Sand on Storage Drawers does not compress like gravel or cobble

### ISSUE THREAD

**Issue by davisjw** [FTBTeam/FTB-Modpack-Issues#327]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

Not really a problem if the modpack author wants this to be this way.  To keep with the design of the pack when putting sand in a compacting storage drawer it would be good if it presented sand and compressed variants vs sandstone.  easily accomplished using compactingRules in storagedrawers-common.toml 
just add something like "rid:1x_compressed_sand, minecraft:sand, 9"

### Mod suggestion

see description above.

**Comment by Raidobw2** [comment]
Thanks for the suggestion. However, this has been answered in #263 and our modpack dev has stated this:

> Technically not a bug and not something there will be changed

The behavior will remain as is, so I will be closing this issue.
