### ISSUE TITLE
ftb skies 1.0.7 crash

### ISSUE THREAD

**Issue by teddyboj** [FTBTeam/FTB-Modpack-Issues#3271]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11360845/latest.log)
[debug-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11360846/debug-1.log.gz)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11360847/console.log)

### Describe the bug

i just downloaded ftb skies and wanted to start playing but both 1.0.7 and older versions crash even before it launches. 

### Steps to reproduce

1. start to launch in the ftb launcher
2. wait for it to launch
3. crashes before it launches

### Expected behaviour

it crashes for me

### Screenshots

![image](https://user-images.githubusercontent.com/132192746/235342834-90d07a56-a396-4fee-a499-349a56fa1dad.png)

### Additional information

ive tried 1.0.7 and 1.0.6 and they crash at the same part. could it be somthing to do with my system even tho the requirements are met.

**Comment by Saereth** [comment]
this is an amd driver issue crash with java not a pack specific issue, I cant help you fix this but I can say it usually involves removing the adrenaline software and updating amd drivers
