### ISSUE TITLE
Thermal rubber recipe in mechanical crafters

### ISSUE THREAD

**Issue by warplord** [FTBTeam/FTB-Modpack-Issues#3272]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

I found out the recipe to make 3 rubber from 1 latex bucket (from TE) was impossible to craft in a mechanical crafter. Would be very nice if it was.

**Comment by Saereth** [comment]
general shapecrafting is disabled for the mechanical crafters in this pack so it wont be possible
