### ISSUE TITLE
Takes multiple attempts to join server

### ISSUE THREAD

**Issue by immeraufdemhund** [FTBTeam/FTB-Modpack-Issues#3273]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.6.0

### Log Files

[logs.zip](https://drive.google.com/file/d/1kdngmtFyKHGL-RPTKP8I2VWWWrvl-ZRA/view?usp=share_link) on my google drive
zip file with
- logs\latest.log
- logs\rei.log
- logs\rei-issues.log
- logs\console.log
- logs\JadeErrorOutput.txt

### Describe the bug

I host a server using the ftb server install on my mac book pro with intel core i7. I have whitelist turned on. I have had up to 3 people on the server at one time all on windows pc. 2 of the 3 people are in my household the other is a friend of mine connecting from his house. I connect the most often of the 3 of us so I probably see the error the most but when I try to connect I'll get 1 of 3 errors.

![Missing profile public key. This server requires secure profiles](https://cdn.discordapp.com/attachments/1064938393752064092/1102253222602735779/image.png)
![Authentication servers are down. Please try again later, sorry!](https://cdn.discordapp.com/attachments/1064938393752064092/1102254794422358066/image.png)
![Failed to log in: The authentication servers are currently not reachable. Please try again.](https://cdn.discordapp.com/attachments/1064938393752064092/1102255314293764136/image.png)

sometimes I can just keep trying to connect and it will connect. Sometimes just to be thorough I'll restart the server and client (even have tried restarting the pc). this issue happened to my wife and I told her to just try again and it worked second time for her. I've tried sometimes up to 10 times and it wont connect.

### Steps to reproduce

I can only share my setup so i'm not sure if it affects others (I can white list you on my server if it would help)

Mac book pro with core i7 pc running the server from terminal
Windows machine running the client from ftb app.

try to connect to the server on the mac using ip address. sometimes it works first try; for me more often than not I have to try a few times to make it work.

### Expected behaviour

I can log in first try

### Screenshots

![Missing profile public key. This server requires secure profiles](https://cdn.discordapp.com/attachments/1064938393752064092/1102253222602735779/image.png)
![Authentication servers are down. Please try again later, sorry!](https://cdn.discordapp.com/attachments/1064938393752064092/1102254794422358066/image.png)
![Failed to log in: The authentication servers are currently not reachable. Please try again.](https://cdn.discordapp.com/attachments/1064938393752064092/1102255314293764136/image.png)

**Comment by manmaed** [comment]
Looks like mojang servers were down, nothing we can do about that. Make sure not to install any mods that would disable the chat reporting stuff

**Comment by immeraufdemhund** [comment]
I promise you this was not the case. There were times I was logged in for 1 minute tops when my wife tried to join. she would try once or twice then it would work. other times it was me, but then I would try logging into mine Skies and it would work. This should not be closed @manmaed .

**Comment by immeraufdemhund** [comment]
thank you. now if it would help i can reinstall 1.6 on my mac and white list you. for me it happens most of hte time but not all of the time.

**Comment by TheonlyTazz** [comment]
@immeraufdemhund - 
I have been looking into this issue and it seems to be related to the secure chat protocols that Mojang implemented. I am unsure on how to fix this, multiple people have also reported this on the vanilla [Minecraft Bugtracker](https://bugs.mojang.com/browse/MC-252942)

One fix i got told, was to change your `enforce-secure-profile` to `false`  inside your `server.properties`

please try that and see if that resolved the issue (note, this will disable the chat report function, but reading your post, i assume this is a private server between friends/family anyway)

**Comment by immeraufdemhund** [comment]
made a copy of my world and installed 1.6.0 again. i'm also hopefully installing a second instance of legend of the eyes through the ftb app.. (it acts like it is installing a second version.. here's to hoping it does). will test it out and get back with your @TheonlyTazz
