### ISSUE TITLE
Quests not completing unless logging in and out of world

### ISSUE THREAD

**Issue by Stroopwafel3** [FTBTeam/FTB-Modpack-Issues#3274]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

As described in title, I noticed it with the ex nihilo sieving quest "Soul Sand -> Andesite Mesh" but it seems to be everywhere as I afterwards ran into the same issue with the Hexerai quest "Mixing Cauldron" as well as "Witchy Trees"

It seems to only update when logging into the game and complete if it is in the inventroy at that moment. If not in the inventory at the moment of logging in it also doesn't complete.

I am however not sure how this started happening but in the discord I saw someone that had the same issue.

### Steps to reproduce

1. obtain items required to complete quest
2. log out with items needed for completing quest in inventory
3. log back in
4. quest is now completed

### Expected behaviour

My quest to be completed the second I had met the requirements

### Screenshots

![Bug FTB skies](https://user-images.githubusercontent.com/127240775/235364689-da50f287-a4e5-464e-ad4c-556d9d8ea646.png)

**Comment by alecium** [comment]
I discovered a solution to this issue which you can do until such time that they issue an update or hotfix.

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3281
