### ISSUE TITLE
Dupe items using the cyclic user and a pedestal from pedestals

### ISSUE THREAD

**Issue by GhestPlays** [FTBTeam/FTB-Modpack-Issues#3277]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

using a cyclic user item to click very fast on a pedestal or any block that looks like the item that was on the pedestal is duplicated

### Steps to reproduce

1 - place a cyclic user item in front of a pedestals pedestal 2 - insert energy and an item inside the user item 3 - set user item to click as fast as possible, set to use left or right button 4 - place the item to be duplicated on the pedestal 5 - turn on the user item

### Expected behaviour

several items equal to those on the pedestal will be dropped

**Comment by ttechr** [comment]
I can not duplicate this issue. Can you post a video by chance?
