### ISSUE TITLE
[Bug] Crash when placing a importer on a Integrated Dynamics storage system

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#3279]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

Forgot to download crash report before rolling back. It corrupted some data and was easier to just roll back a few minutes to just before the corruption / crash.

### Describe the bug

When a user was trying to import items from a integrated dynamics storage system to a refined storage system, the server crashes and player data corrupts due to a ticking entity crash. 

Unfortunately, I forgot to download the crash report which was overwritten when rolling back, so I do not have the report. 

### Steps to reproduce

1. Setup a RS system with storage
2. Setup a Integrated Dynamics system filled with various items (see images)
3. Connect a RS importer on a Integrated Dynamics interface (see images)
4. Observe a server crash

### Expected behaviour

No crash, no corruption, items either transfer or dont. 

### Screenshots

Where an importer was placed:
![2023-05-01_00 28 51](https://user-images.githubusercontent.com/122759195/235406850-78c50b7a-e164-4c3b-ab48-05e446edeb09.png)

The storage system (Note that it is now partially disassembled. The players were trying to import from their integrated dynamics storage to RS):
![2023-05-01_00 29 03](https://user-images.githubusercontent.com/122759195/235406913-1af60f72-7d5e-46bf-8985-fb3285d091b4.png)

**Comment by Saereth** [comment]
Please reopen if you can get me a crash log
