### ISSUE TITLE
Connection Lost - Payload Too Large (now causing KubeJS errors)

### ISSUE THREAD

**Issue by DaddyItsSticky** [FTBTeam/FTB-Modpack-Issues#3280]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Log Files

[server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11363818/server.txt)

### Describe the bug

When in the JEI recipe for the cover from "refined storage", I clicked the + icon to add the recipe into my crafting grid, and it booted me from my local server I play on. "Connection Lost: Payload may not be larger than 32767 bytes".

- I have added a screenshot of the lost connection screen.

Now when I re-join my server, I get KubeJS errors x 2, and KubeJS warnings x 22.
The errors are something about the wandering trader entitiy, and the warnings are a whole list of recipes unable to be parsed.

- I have added the server.txt log from KubeJS with the details

I am reverting back to an old world backup in the meantime, cause of nervousness etc blah blah

### Steps to reproduce

1. Craft cover from refined storage in crafting grid
2. disconnect
3. see results
4. reconnect to see KubeJS problems

### Expected behaviour

I expected to be able to create a cover and no change to have happened

### Screenshots

![Crash When Creating Cover](https://user-images.githubusercontent.com/130208520/235414976-101fdf7d-d6f7-4abc-8d03-071f7ae280a2.png)

**Comment by Saereth** [comment]
that kubejs error can be safely ignored. The bigger problem is you've got too much nbt data on your character now either via recursive storage or something you picked up that has a ton of nbt data. you'll need to restore your player file from a backup
