### ISSUE TITLE
[FTB Skies] Possible Issue with Autocrafting Sender Module Mk2/Distributor Modules via Refined Storage

### ISSUE THREAD

**Issue by Tybold** [FTBTeam/FTB-Modpack-Issues#3284]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

When trying to autocraft Distributor Modules from Modular Routers in Refined Storage, it didn't recognize any Sender Module Mk2s in storage and acted as if I didn't have the pattern to autocraft them in the terminal. The issue seems to have fixed itself upon relogging, but I'll attach a few screenshots I took before then. I didn't know at the time that the Distributor Module and/or the Sender Module was the issue, so I don't have any more specific screenshots. I was trying to craft an Energy Distributor Module at the time, and ruled out the other components aside from the Distributor Module.

### Steps to reproduce

Unknown

### Expected behaviour

Expected to be able to autocraft Distributor Modules.

### Screenshots

![2023-05-01_08 00 23](https://user-images.githubusercontent.com/8304590/235464580-1ebd36b1-0ed2-4e57-aabf-d3ddd9c36cb3.png)
![2023-05-01_08 00 44](https://user-images.githubusercontent.com/8304590/235464583-01357f1e-4588-4835-a884-e8a315cdd972.png)
![2023-05-01_08 00 56](https://user-images.githubusercontent.com/8304590/235464588-996faa75-15ec-45a6-b8b2-8516a66c0bba.png)
![2023-05-01_08 02 05](https://user-images.githubusercontent.com/8304590/235464591-f7ee25be-2af6-4cfe-aab4-d7ec6176704d.png)
![2023-05-01_08 02 44](https://user-images.githubusercontent.com/8304590/235464594-c317f114-ade3-4d8d-a463-9d74b54f2f54.png)

### Additional information

I've been having (inconsistent) bugs related to my Refined Storage network since updating to 1.0.7 involving crafters and wireless networks, though I attempted to autocraft the modules after manually crafting the components and storing them via the main crafting grid.

**Comment by Saereth** [comment]
Im unable to reproduce this, I suspect maybe something to do with wireless networks/chunkloading or pathfinding logic of cables at play here for rs

**Comment by Tybold** [comment]
> Im unable to reproduce this, I suspect maybe something to do with wireless networks/chunkloading or pathfinding logic of cables at play here for rs

The issue occurred again. I manually crafted the sender modules on the wired grid, then tried both autocrafting the distributor module and crafting it via JEI, and both times it was acting as though there were none in the system, nor could they themselves be autocrafted. All completely wired, and all in the same chunk as the storage network (including the crafter).

**Comment by Tybold** [comment]
> > Im unable to reproduce this, I suspect maybe something to do with wireless networks/chunkloading or pathfinding logic of cables at play here for rs
> 
> The issue occurred again. I manually crafted the sender modules on the wired grid and placed them into the system (on a disk), then tried both autocrafting the distributor module and crafting it via JEI (edit: I may be misremembering about trying to craft through JEI. Will double-check if the issue pops up again.) and both times it was acting as though there were no sender modules in the system, nor could they themselves be autocrafted. All completely wired, and all in the same chunk as the storage network (including the crafter). Crafting the distributor module by manually placing the ingredients worked without issue.

Here it shows that autocrafting doesn't see the Sender Module Mk1s (first screenshot) despite having the required 3 in storage (second screenshot)
![2023-05-04_15 31 45](https://user-images.githubusercontent.com/8304590/236311979-e0d6db8c-aba2-4994-a227-ebcfa58f85ce.png)
![2023-05-04_15 31 53](https://user-images.githubusercontent.com/8304590/236312013-5d67ba40-18f8-4329-b055-6e44ccc43155.png)

**Comment by ren-** [comment]
had the same problem but worked when I disabled "Exact" in the patterns for it.

**Comment by Tybold** [comment]
> had the same problem but worked when I disabled "Exact" in the patterns for it.

Didn't work when I tried it.

**Comment by Tybold** [comment]
> > had the same problem but worked when I disabled "Exact" in the patterns for it.
> 
> Didn't work when I tried it.

Changed literally every step of the crafting process to Exact, and it seems to be working for now.

**Comment by Saereth** [comment]
that explains it yeah, I have exact disabled so thats why I couldnt reproduce it, glad its working for you now!
