### ISSUE TITLE
Crashing When Dieing and Entering StoneBlock 3 Lobby

### ISSUE THREAD

**Issue by ThunderCraz** [FTBTeam/FTB-Modpack-Issues#3286]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Log Files

[crash-2023-05-01_07.17.36-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11369250/crash-2023-05-01_07.17.36-client.txt)

### Describe the bug

When I die in my stoneblock 3 world, I enter the spawn lobby which sometimes I crash. I realized that the spawn chunks are not loaded sometimes and then crash or if I go afk at the spawn lobby, I would crash.

Please anyone help me find the issue so, I could try to solve it.

### Steps to reproduce

Happening on my end maybe.

### Expected behaviour

Help Me

**Comment by UnRealDinnerbone** [comment]
It looks like you added mods that are not default to this pack. Please remove the mods such as Rubidium and try again if the issue still happens please let us know with a new crashreport
