### ISSUE TITLE
World reset after redownloading modpack

### ISSUE THREAD

**Issue by wumbology102** [FTBTeam/FTB-Modpack-Issues#3287]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

My stoneblock 3 world would freeze every time I tried to load a world from the main menu. I created a new world in the modpack to see if that would fix it but that would freeze too. I then downloaded a save to my desktop and redownloaded the modpack. I created another world in the newly installed modpack and it opened no problem. i then moved my previous world into the newly installed modpack, and when i loaded in my inventory and position was the same but the world had reset to default.

### Steps to reproduce

install new modpack
port old save over
open a different world
open the ported save world 

### Expected behaviour

my old world to be just as i had left it

**Comment by UnRealDinnerbone** [comment]
Please make sure you copied all the files from the old world. and please also upload log file when loading into the world
