### ISSUE TITLE
Industrial Foregoing Mob Crusher Inventory Deleted

### ISSUE THREAD

**Issue by gmwarlord** [FTBTeam/FTB-Modpack-Issues#3288]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.9.0

### Describe the bug

JEI sorting [Middle click] in Industrial Foregoing Mob Crusher Deletes Block Inventory

### Steps to reproduce

1. Open Industrial Foregoing Mob Crusher
2. JEI sort the Industrial Foregoing Mob Crusher
3. Industrial Foregoing Mob Crusher Block Inventory Is deleted output and addons

### Expected behaviour

a: nothing or b: items sorted

### Additional information

Industrial Foregoing Mob Crusher Block Inventory Is deleted output and addons

**Comment by Saereth** [comment]
added if blocks to inventory sorting blacklist for next update
