### ISSUE TITLE
[Bug]: pressing media button open mod list

### ISSUE THREAD

**Issue by eroom05** [FTBTeam/FTB-Modpack-Issues#329]
### Modpack

FTB OceanBlock

### Modpack version

1.8.0

### Describe the bug

a list of the mods appears when pressing any media button (mute/volume down/volume up/previous/play-pause/next).

### Steps to reproduce

1. go to singleplayer world
2. presse a media button

### Expected behaviour

the menu does not appres

### Additional information

btw sorry if any of this is wrong it's my first time on this website.

**Comment by Raidobw2** [comment]
Hello, try setting that keybind to something you don't use, like a numpad key for example:
![image](https://user-images.githubusercontent.com/17010632/142345063-636b3041-931f-46d6-9626-7c0cec714996.png)

@Sunekaer 2nd time seeing this, it's not a lot of people but if you have some kind of default options in the pack you could set it as another default keybind. The key was blank in 1.8.0 though, as on the picture. I don't have media buttons to test.
Close this if there's no such mod in the pack or checking keybinds like I recommended is the thing to do.

**Comment by eroom05** [comment]
setting a keybind did fix it

**Comment by Raidobw2** [comment]
Thanks for getting back to us. We'll take it from here and see if we can add a default keybind for it or not.
Have fun playing! :)

**Comment by Sunekaer** [comment]
https://github.com/MrCrayfish/Configured/issues/27

**Comment by Sunekaer** [comment]
Ill add a default keybind as a temp fix

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Configured/commit/7d6c6c0c67b1600bbf6e48e1112bb81d8aad0cfb

**Comment by Sunekaer** [comment]
Thanks @MrCrayfish !

**Comment by Raidobw2** [comment]
Awesome :) mod now available on CurseForge for update `Configured 1.3.1`
