### ISSUE TITLE
Crush during startup

### ISSUE THREAD

**Issue by michalhomie** [FTBTeam/FTB-Modpack-Issues#3292]
### Modpack

FTB Skies

### Modpack version

1.0.7/1.0.6

### Log Files

[crash-2023-05-03_10.57.47-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11380975/crash-2023-05-03_10.57.47-client.txt)

### Describe the bug

Dont know what this type of Bug ist, im not geek guy

### Steps to reproduce

1. Starting FTB App
2. Open instance 
3. Crush

### Expected behaviour

Will be nice when someone can help me fix it .)

**Comment by Saereth** [comment]
minetogether is obfuscating the actual crash here, please disable minetogether and post a new crashlog

**Comment by michalhomie** [comment]
seams works fine, sorry that i answear soo late. thank you very much!
