### ISSUE TITLE
Unstable Bow is not functional

### ISSUE THREAD

**Issue by Copperearth** [FTBTeam/FTB-Modpack-Issues#3293]
### Modpack

FTB Skies

### Modpack version

1.0.7 & 1.0.6

### Describe the bug

Unstable Bow doesn't function

### Steps to reproduce

1. Equip Unstable Bow
2. Draw bow
3. Release

### Expected behaviour

Arrow should fly forwards instead of instantly dropping to the ground.

**Comment by Saereth** [comment]
reported to mod dev and removed for next update since yeah its completely useless currently
