### ISSUE TITLE
Server script - Wrong mods urls (Linux)

### ISSUE THREAD

**Issue by Arimav2nd** [FTBTeam/FTB-Modpack-Issues#3294]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Log Files

Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/commons-logging/commons-logging/1.2/commons-logging-1.2.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/commons-io/commons-io/2.4/commons-io-2.4.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar: server returned 404 Not Found

### Describe the bug

Some files URL in script installer have an issue.

They begin with "https://libraries.minecraft.net/https://libraries.minecraft.net/" instead of "https://libraries.minecraft.net/"

### Steps to reproduce

Simply execute linux server install script.

### Expected behaviour

Link should be starting with "https://libraries.minecraft.net/https://libraries.minecraft.net/" instead of "https://libraries.minecraft.net/"

**Comment by Saereth** [comment]
This is the creeper host installer, there is an open issue with them, you'll want to followup here, I believe they have a fix in the works now:
https://github.com/CreeperHost/modpacksch-serverdownloader/issues/18

**Comment by manmaed** [comment]
See: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3256
