### ISSUE TITLE
Sifter voids ores if output types are full

### ISSUE THREAD

**Issue by UnRealDinnerbone** [FTBTeam/FTB-Modpack-Issues#3297]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

Sifter voids ores if output types are full. For example, if you sift gravel with manasteal mesh and have no output for sifter, you won't see any diamonds 

### Steps to reproduce

1. Put mana mesh in sifter
2. Throw gravel on
3. Wait for sifting
4. Get no diamonds or other low chance 
5. Be sad because you have no diamonds 

### Expected behaviour

Diamonds / other drops

**Comment by Saereth** [comment]
This is not a bug, it's by design

**Comment by UnRealDinnerbone** [comment]
I fell like this should be mentioned somewhere in the questbook / tooltip on the block so people will take notice of this. I never setup automation as I was enjoying not manual labor

**Comment by Saereth** [comment]
added to the sifter quest
