### ISSUE TITLE
Auto hammer does not work with cobbled deepslate - Solved

### ISSUE THREAD

**Issue by Rithenar** [FTBTeam/FTB-Modpack-Issues#3298]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1

### Describe the bug

Using the same setup I have for cobble, gravel, etc., the auto hammer does not process cobbled deepslate. REI shows cobbled deepslate as possible to process with the hammer or autohammer. In the autohammers that work as expected (screenshot with cobble) the tooltip shows green with cobble on input. The auto hammer for deepslate shows a red processing line and no input.

### Steps to reproduce

1. Have a source of cobbled deepslate
2. set up auto hammer facing input to the cobbled deepslate
3. have a container in the output side to stored the crushed deepslate

### Expected behaviour

for auto hammer to process the deepslate as it shows in REI

### Screenshots

![image](https://user-images.githubusercontent.com/9939332/236085085-fe014b99-9cd0-4fc2-b844-8bfef2dc1a86.png)
![image](https://user-images.githubusercontent.com/9939332/236085112-86e69d63-ba97-4f63-b1ba-b0b074000e37.png)
![image](https://user-images.githubusercontent.com/9939332/236085247-75bfc9de-f79c-4121-ad6f-e0e8b3af6129.png)

**Comment by Rithenar** [comment]
Apparently, you need a Diamond auto-hammer for deepslate. Could you please update the REI recipe so it shows that instead of all hammers?

**Comment by well291** [comment]
thanks this helped a lot. as of now it is still not updated.
