### ISSUE TITLE
[Bug]: Ars Nouveau's Warding Stones don't work that way.

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#330]
### Modpack

FTB University 1.16.5

### Is your suggestion related to a problem? Please describe.

The warding stone quest text describes functionality the warding stone does not have.

![Warding Stones](https://user-images.githubusercontent.com/77522101/142290670-1d851e2e-41a9-48e2-bad4-cb30099f9749.png)

**Comment by Raidobw2** [comment]
Hello. I see the quest for that block defines it like this: `Monsters will refuse to walk over Warding Stone.`

From my understanding of the reply of Dashkal, this appears to be true. Mobs will not pathfind over the stone, thus will never walk over it.

I've done a test to make sure that works as intended, and it looks like it does. They don't walk on the stone, and try to "get out of it" with haste, even Nether mobs:
![warding_stone_pathfinding](https://user-images.githubusercontent.com/17010632/142341791-4d49ba06-f1c5-4480-9562-4656cb86f858.gif)

I hope I understood right, but to your opinion, what should the text of the quest say instead?

**Comment by zoller27osu** [comment]
"Monsters will try not to walk over Warding Stone."

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/142748477-faa4d494-b133-450e-a307-9777bb55f960.png)
The creeper isn't leaving it
