### ISSUE TITLE
Solar Neutron Activator stops working after server restart.

### ISSUE THREAD

**Issue by anuzsubedi** [FTBTeam/FTB-Modpack-Issues#3301]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Describe the bug

Whenever the server restarts any solar neutron activators currently running stop working. Also, any new activators in the same chunk will also not work. 

### Steps to reproduce

1. Setup a solar neutron activator 
2. Restart the server.
3. It will stop working. 
4. Move it to a new chunk
5. It will start working. 

### Expected behaviour

It should not break after server restart.

### Screenshots

![image](https://user-images.githubusercontent.com/78558895/236310430-83331bcd-a097-4e03-b7f5-6f27c2b0eb67.png)
![image](https://user-images.githubusercontent.com/78558895/236310524-c271a04d-48a6-47b5-9f99-90ac57a53ca2.png)

**Comment by Saereth** [comment]
new update should sort this
