### ISSUE TITLE
Error downloading Server files

### ISSUE THREAD

**Issue by CodyTheRed** [FTBTeam/FTB-Modpack-Issues#3302]
### Modpack

FTB Skies

### Modpack version

1.0.8

### Describe the bug

When trying to install server files for the 1.0.8 version of the pack, 4 of the libraries have "https://libraries.minecraft.net/" twice at the download link, causing them to fail.

1. https://libraries.minecraft.net/https://libraries.minecraft.net/commons-io/commons-io/2.4/commons-io-2.4.jar
2. https://libraries.minecraft.net/https://libraries.minecraft.net/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
3. https://libraries.minecraft.net/https://libraries.minecraft.net/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
4. https://libraries.minecraft.net/https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar

### Steps to reproduce

1. Download the server install program
2. Start installing server files
3. Get the message "Downloaded 1129 successful, 4 failed, 0 incomplete. Some downloads failed. Would you like to continue anyway? (y/n) [y]"

### Expected behaviour

To download al files without any failing

**Comment by KingTamotsu** [comment]
Yeah I am having the same issue :(
Wanted to play with a friend but couldn't download those files.

**Comment by d1ggah** [comment]
This is still an issue with 1.0.9 server files (serverinstall_103_6473).

**Comment by manmaed** [comment]
See: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3256
