### ISSUE TITLE
Entity? Issue with Create Trains interacting with Mekanism Teleporters

### ISSUE THREAD

**Issue by Smok3dDevil** [FTBTeam/FTB-Modpack-Issues#3303]
### Modpack

FTB Skies

### Modpack version

1.0.7

### Describe the bug

I have built a create train and setup multiple stations, I also later added some Mekanism Teleports for player transport however anytime a train from Create pulls up and waits at a station and there is a Teleporter that is atleast 3-6 blocks away from the train they seem to.. collide? the mekanism teleporter starts shooting out purple particles as if the train is constantly teleporting back and forth through it, any players that are seated within the train get teleported repeatedly between the train and the teleporter it's connected to.

### Steps to reproduce

1.Setup a looped Create train track with atleast 2 stops
2. Create atleast a 4x3x4 train 
3. Setup a Mekanism teleporter 3-6 blocks away from the track where the train stops
4. Setup a second Mekanism teleporter to establish a link
5. Drive or Setup a conductor to drive the train to that stop
6. and you get Spam teleports

### Expected behaviour

Expected train to stop and not repeatedly attempt to teleport through the mekanism teleporter.

### Additional information

 I'm guessing this has something to do with the trains hitbox being larger than it should be so it's interacting with the teleporter

**Comment by Saereth** [comment]
yeah that's whats happening, This is somehting that would be on create and mekanism to resolve, nothing we can do to address it from a pack standpoint
