### ISSUE TITLE
new update broke the game completely for me and my friends.

### ISSUE THREAD

**Issue by outcastdiamond** [FTBTeam/FTB-Modpack-Issues#3305]
### Modpack

FTB Skies

### Modpack version

1.0.8

### Describe the bug

when I try to fly out and find a village it stops loading and wont let me do anything other then move. when i try to save a quit after the world stops responding it gets stuck on saving. when i try to make a new world it will let me in to the lobby of that world it stops working too. it happens to two of my friends too and we cant even play at all. love the pack though the update just did something since it worked before updating the pack.

### Steps to reproduce

tried to make new worlds same thing.

### Expected behaviour

for it not to break when loading anything.

**Comment by Huntingwillow** [comment]
I am having the same issue, I get about 900 blocks away and then everything stops loading in. i even tried going slower to see if that would help. but nope.

**Comment by Blockguy24** [comment]
I am having this issue too. I'm not sure what's going on with this version.

**Comment by Sirttas** [comment]
This I my fault: https://github.com/Sirttas/ElementalCraft/issues/142 uupdate lementalcraft to 5.8.1

**Comment by ren-** [comment]
@Saereth 🙏
