### ISSUE TITLE
Inferno - Invalid Player Data

### ISSUE THREAD

**Issue by Riathel** [FTBTeam/FTB-Modpack-Issues#3307]
### Modpack

FTB Inferno

### Modpack version

1.9.0

### Describe the bug

Looks like bug 3107 is back in 1.9.0:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3107

### Steps to reproduce

Complete fresh install of Inferno
Launch singleplayer
Create World
... get kicked

### Expected behaviour

Player joins new world

**Comment by MiniNinja1810** [comment]
same here, just tried to play 1.9.0 and got that issue :(

**Comment by Zarepheth** [comment]
Same here.

Perhaps I should try downgrading from 1.9.0 to 1.8.0 to create a new world.

**Comment by Riathel** [comment]
Downgrading to 1.8.0 is a valid workaround. So long as you enter the new world at least once before going back to 1.9.0.
