### ISSUE TITLE
[bug] Server crash at startup (Fastsuite and compacting drawer)

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#3308]
### Modpack

FTB Skies

### Modpack version

1.0.6

### Log Files

https://gist.github.com/JustAnotherGhostName/1db5d29ca5c3f52c4018bd6d9f4e5fa4

### Describe the bug

Second time I had this bug occur this week. Server boots up to a instant crash before a player joins (likely due to chunk being chunk loaded). 

At first I thought the drawer just got corrupted somehow so I rolled back to a backup from just before the crash, however, nothing about the drawers setup seemed odd. It wasn't actively having items added to that drawer as part of the network, it didnt have any upgrades, nor was it remotely full. There was not even some sort of lag from sophisticated storage popping up on spark reports. 

Uncertain how to reproduce, but I have noticed some spike issues this week with the "fast" mods (fast craftingtables and fastsuite so far) on the modpacks in my network this week. 

### Steps to reproduce

1. Start server
2. Observe a CHANCE for a crash

### Expected behaviour

Server dosnt crash

**Comment by Saereth** [comment]
this should be fixed with the sophisticated core update coming in 1.0.3
