### ISSUE TITLE
[Bug]: Plant gatherer collects things outside the shown work area

### ISSUE THREAD

**Issue by Kamasu-Tra** [FTBTeam/FTB-Modpack-Issues#331]
### Modpack

FTB Academy

### Modpack version

1.16

### Describe the bug

Am having a weird issue with the Industrial Foregoing Plant Gatherer; I've got it all setup, but it keeps harvesting trees that are not there. I've cleared the area of all trees, but it keeps pulling in branches and sapplings, even for trees that are no where near me. 

![tree2](https://user-images.githubusercontent.com/64828205/142291664-cf3b5dbc-83a3-4f91-a5e2-b6701f98c509.png)
![tree3](https://user-images.githubusercontent.com/64828205/142291710-1fc8546c-fb99-4fe3-a696-2ae2c9004b2e.png)
![plants](https://user-images.githubusercontent.com/64828205/142291603-5a4219d0-34dd-4a31-96d0-8828ab473696.png)

### Steps to reproduce

Put down a Plant Gatherer with a wide area range upgrade, and it will pull things from outside the expected/shown range.

### Expected behaviour

To only interact with blocks within it's working range.

**Comment by Raidobw2** [comment]
Awaiting reply from mod author
