### ISSUE TITLE
Can't bonemeal grass blocks

### ISSUE THREAD

**Issue by nikoflame** [FTBTeam/FTB-Modpack-Issues#3311]
### Modpack

FTB Skies

### Modpack version

1.0.9

### Describe the bug

When I use bonemeal on the grass blocks in the game (Vivid grass and Dry grass, there doesn't seem to be normal grass) I do not get anything, and the bonemeal is not used. It's as if I cannot use bonemeal on grass. This blocks me from breaking tall grass to get demon fruit seeds in order to progress the game any further.

### Steps to reproduce

1. go into the game
2. get bonemeal
3. use it on grass (vivid grass or dry grass)
4. doesn't work

### Expected behaviour

i expect it to give me tall grass and small grass and some flowers when using the bonemeal on grass, just like in vanilla.

**Comment by natebc** [comment]
@nikoflame The way I got vanilla grass was via the Create recipe for a Grass Block. The Botania grass blocks don't seem to work like regular grass. Not sure if that's intentional or not.

Not sure if this is a bug or can be configured in a modpack but hopefully Create can at least get you some Grass in the meantime.

**Comment by nikoflame** [comment]
> @nikoflame The way I got vanilla grass was via the Create recipe for a Grass Block. The Botania grass blocks don't seem to work like regular grass. Not sure if that's intentional or not.
> 
> Not sure if this is a bug or can be configured in a modpack but hopefully Create can at least get you some Grass in the meantime.

Thank you, I can progress now, however the bug or whatever it is should still be fixed. Either that or the quest for the fruit should be updated to tell you the long drawn out process of getting a grass block.

**Comment by Spongman** [comment]
Yeah, the first Occultism quest specifically says to use bone meal. on what exactly? the botania grass blocks don't yield tall grass like it says. broken.

**Comment by turt2live** [comment]
per https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2983#issuecomment-1500864888 you can use pasture seeds on dirt blocks. If you create a large enough area, it'll spread out a bit too

**Comment by Saereth** [comment]
This is not a bug, the quest book guides you towards pastrue seeds for making vanilla grass.

**Comment by Spongman** [comment]
it's highly misleading for new players unfamiliar with botania and looking at the occultism quest. it says to use bonemeal, and that usually works on vanilla grass, but the occultism quest doesn't mention anything about it not working on botania grass.
i would either put a clue in there, or gate it on a pasture seed quest.
