### ISSUE TITLE
Quiver causes arrow duplication

### ISSUE THREAD

**Issue by drewsuhferr** [FTBTeam/FTB-Modpack-Issues#3313]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.6.0

### Describe the bug

Usage of the Quiver from the Supplementaries mod causes all arrow types to duplicate. When using arrows directly from the inventory they decrease as expected but when placed in the quiver the quantity does not decrease upon firing. The arrows also becoming an interactable entity so they can be picked up and thus duplicated.

### Steps to reproduce

1. Get a quiver from the supplementaries mod 
2. Shoot an arrow with a bow or crossbow
3. Arrow shot does not decrease count in the quiver
4. When you pick up the arrow it enters your quiver and you've now gained one arrow

### Expected behaviour

When firing arrows using a quiver the arrow quantity should decrease like normal

### Screenshots

![2023-05-05_22 52 57](https://user-images.githubusercontent.com/116617543/236598565-42f321a6-bfbf-42cd-912d-24030d9b7342.png)
![2023-05-05_22 52 35](https://user-images.githubusercontent.com/116617543/236598568-6e0f77c5-e4aa-431d-87b9-616ef005089b.png)
![2023-05-05_22 52 08](https://user-images.githubusercontent.com/116617543/236598572-5c17f7b1-d022-440c-85c4-5b51aa17e239.png)

**Comment by drewsuhferr** [comment]
screenshots were loaded in reverse order. you can see in the last one I have six arrows but after firing and picking up the arrow we now have seven. As a note the bow does not have infinity enchantment. It can also be noted that I tested this using a standard bow from minecraft base and the duplication still occurs. I also tested with standard minecraft bow enchanted (any) and the duplication still occurs so I think it has to do with the Supplementaries Quiver.

**Comment by TheonlyTazz** [comment]
This is a known issue and is related to supplementaries Quivers as u have already mentioned. sadly, this issue never got fixed
