### ISSUE TITLE
All materials gone with new update.

### ISSUE THREAD

**Issue by Jreil1981** [FTBTeam/FTB-Modpack-Issues#3314]
### Modpack

FTB Skies

### Modpack version

1.0.9

### Describe the bug

The new update has caused all materials to disappear from my refined storage system. When I try to add something to it, it won't take it.  Not sure how to fix this, I was going to just run it off the previous version, but it locks up when I go and visit a sky village. Any help with this would be greatful.

### Steps to reproduce

Update to new version.
Access Refined storage system.
All items gone. Storage acts as though my disks don't exist, or are full (which is not the case).

### Expected behaviour

Can't add anything to my storage system, can't find/withdraw anything I already had in there.

### Additional information

I've have added a couple of mods, such as project e, and project extended, neither of which should have caused an issue with this.

**Comment by MechBFP** [comment]
Make sure it has power still.

**Comment by Jreil1981** [comment]
> Make sure it has power still.

That was the first thing I check, and it would have gone dark if power was lost. It was still lit up.

**Comment by ukmcplyr** [comment]
@Jreil1981 Have you got any Functional Storage controllers hooked up to your RS system? If yes, does breaking the external storage cables linking the fix it?

**Comment by Saereth** [comment]
This does seem the like fucntional storage+external storage bug, let us know how yours is setup
