### ISSUE TITLE
Error paths in windows installer

### ISSUE THREAD

**Issue by msamsel** [FTBTeam/FTB-Modpack-Issues#3315]
### Modpack

FTB Skies

### Modpack version

1.0.9, 1.07

### Log Files

```
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/commons-io/commons-io/2.4/commons-io-2.4.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/commons-logging/commons-logging/1.2/commons-logging-1.2.jar: server returned 404 Not Found
Error downloading https://libraries.minecraft.net/https://libraries.minecraft.net/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar: server returned 404 Not Found
```

### Describe the bug

During pack installation paths to 4 files are wrongly constructed, which causes a failed warning during the installation.

### Steps to reproduce

1. Download Windows installer for FTB Skies (server)
2. Run the installer
3. Wait for a moment when mods are downloaded from Internet 

### Expected behaviour

No failed downloads during installation on Windows

### Screenshots

![Screenshot_11](https://user-images.githubusercontent.com/9017322/236613306-80167b51-1e47-408c-a473-520ac769f70b.png)

**Comment by VoxelVixen** [comment]
Same here , 4 files failed.
But when you check the path of the files, they are present in the libaries folder.
I updated the server and so far its working fine.

**Comment by Kage-Yami** [comment]
Just wanted to confirm that this is not exclusive to the Windows installer - the same thing happens on the Linux installer.

Good job spotting that they're simply malformed URLs - I had missed that. Glad there's nothing stopping me from upgrading now. :)

**Comment by manmaed** [comment]
See: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3256
