### ISSUE TITLE
CLIENT CRASH ON OPEN INVENTORY

### ISSUE THREAD

**Issue by Xfitloco2** [FTBTeam/FTB-Modpack-Issues#3317]
### Modpack

FTB OceanBlock

### Modpack version

1.15.1

### Log Files

[hs_err_pid1188.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11412962/hs_err_pid1188.log)

### Describe the bug

trying to open the inventory crash the game and show the EXCEPTION_ACCESS_VIOLATION

### Steps to reproduce

start the game 
press the E to open the inventory 
the game crash

### Expected behaviour

Crash

**Comment by manmaed** [comment]
Are you also able to attach the latest and debug log files

**Comment by Xfitloco2** [comment]
> Are you also able to attach the latest and debug log files

[logs.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11416177/logs.zip)

**Comment by manmaed** [comment]
try this: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40#issuecomment-966039154
