### ISSUE TITLE
Client crash/shutdown

### ISSUE THREAD

**Issue by Lae95** [FTBTeam/FTB-Modpack-Issues#3318]
### Modpack

FTB Skies

### Modpack version

1.0.9

### Log Files

[crash-2023-05-06_21.38.16-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11413257/crash-2023-05-06_21.38.16-client.txt)

### Describe the bug

When holding "W" to ponder Rolling Mill while inside storage terminal the game shuts down/crashes.
Game does not crash when holding "W" from inventory.

### Steps to reproduce

Open IE Storage terminal with Create Rolling Mill in inventory/storage.
Hold "W" to ponder the Rolling Mill

### Expected behaviour

Should open "ponder" interface and show how to use the item

### Screenshots

![2023-05-06_21 43 47](https://user-images.githubusercontent.com/132782815/236643739-4cbcedd0-b230-4850-973e-03ee0b5f98de.png)

### Additional information

EDIT:
Upon further "failing" it seems to happen to other Create items too.

_No response_

**Comment by Saereth** [comment]
mod issue, we'll have to wait for them to fix, meanwhile dont ponder inside of other UIs as a work around
