### ISSUE TITLE
Cobblestone Glitch

### ISSUE THREAD

**Issue by Henri-ohl** [FTBTeam/FTB-Modpack-Issues#3319]
### Modpack

FTB Skies

### Modpack version

1.0.9

### Describe the bug

When you put an Item User, directed on an Pedestal with an Material Generator Upgrade, it gives you way more Ressources than it should.

### Steps to reproduce

1. Place an Item User
2. Place an Pedestal next to it with an Material Generator Upgrade and a Block like Stone under it
3. Make sure the Item User "clicks" with left click on the Pedestal
4. Change the Item User to Always Active and wait until block pop out of the Item User 

### Expected behaviour

Block like cobblestone everywhere

**Comment by Mowmaster** [comment]
From my testing, this is more then likely a cyclic issue.
Create Deployer does not have this issue.

Cyclic, seems to over fill its internal inventory up to 320 items before it starts to spew out everywhere, once it does, you can break the pedestal and put ANY other block in its place and the cyclic item user will continue to spill out items all over the place.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10681506/470e0eea-57a4-409f-8830-d98000d65e62)

On my end I could just flat out prevent fake players from interacting with pedestals, which would prevent this interaction all together, but it doesnt appear to be a bug in pedestals itsself, from my testing.
