### ISSUE TITLE
[Bug]: projectred/cbmultipart wire with immersive machines requires break and place

### ISSUE THREAD

**Issue by dhdzeke** [FTBTeam/FTB-Modpack-Issues#332]
### Modpack

ftb ocean block

### Modpack version

1.8.0

### Describe the bug

i am using project red /cbmultipart framed insulated wires and bundled cable to make a network that i can turn on and off my machines with immersive machines it requires a break and replace of the insulated wire to use the machine again after turning off the redstone signal

### Steps to reproduce

1. craft any immersive multiblock machine
2. put a red alloy wire on the redstone port
3. put a framed insulated wire on the red alloy wire 
4. run some bundled cable off of that
5. place another insulated wire at the end and a lever 
6. make sure the machine has the required inputs for production
7. flip the lever on to shut off the machine then back off to turn it on 
8. you will notice that with the lever off and not supplying a redstone signal the machine doesnt run
9. break and place the insulated wire on the machine 
10. the machine will now start working

### Expected behaviour

able to turn on and off the machines with insulated wire and bundled cable

**Comment by Raidobw2** [comment]
Thanks for the report. Could you share a quick picture of your setup with the cables and your machines?

**Comment by dhdzeke** [comment]
https://i.imgur.com/TD935k0.png

**Comment by dhdzeke** [comment]
and then the bundled cable runs through the floor and wall to the second flour of my building where i have my levers for shutting my machines off

**Comment by Raidobw2** [comment]
Thank you

**Comment by Sunekaer** [comment]
Works fine in my testing, might have been fixed in modupdates.
If you can still recreate the issue please let us know
