### ISSUE TITLE
[Bug]: FTB Skies: cant take items out of my RS system.

### ISSUE THREAD

**Issue by NickiBossow** [FTBTeam/FTB-Modpack-Issues#3320]
### Mod

FTB Skies

### Mod version

ftb-teams-forge-1902.2.13-build.100

### Forge / Fabric version

forge 43.2.8

### Modpack & version

FTB Skies 1.0.9

### What issue are you having?

I cant take items out of my RS system when it is connected to Functional storage via external storage.

### Steps to reproduce

placing external storage on storage controller from functional storage

**Comment by NickiBossow** [comment]
found the problem.. 

dont put a compact machine in the system that is chunkloaded!!!!

**Comment by NickiBossow** [comment]
well it work for a short time.. now its back.. dont know what it can be then!!

**Comment by ramalott** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3124

Using a controller extension as described in issue 3124 fixed this for me.

**Comment by NickiBossow** [comment]
Ramalott. 
IT WORKED!!
Thank you for your reply, that made my day THANK YOU...

**Comment by manmaed** [comment]
See https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3124
