### ISSUE TITLE
Ich kann keine Resonated Thruster Herstellen obwohl ich alle materialen dazu habe

### ISSUE THREAD

**Issue by Edersoon** [FTBTeam/FTB-Modpack-Issues#3321]
### Modpack

FTB Skies

### Modpack version

1.7.10

### Describe the bug

Hallo also ich wollte mir gerade ein Resonated Jetpack bauen was bis jetzt auch alles funktioniert hat aber wenn ich den Thruster dafür bauen will kommt es rechts nicht was kann ich da machen oder was muss ich machen damit ich das machen kann?

### Steps to reproduce

Alles für den Thruster Herstellen
Dann in die Normale? ich glaube sonst das das das problem ist geben
und dann kommt rechts nicht der Thruster

### Expected behaviour

Das ich den Thruster herstellen kann ;) 

### Screenshots

![Screenshot 2023-05-07 134124](https://user-images.githubusercontent.com/132821684/236675477-67301416-cab3-47be-b0b6-f4a9be44bcc3.jpg)
![Screenshot 2023-05-07 134135](https://user-images.githubusercontent.com/132821684/236675479-f89bc99d-b896-4f90-9cfd-9b1a9f425367.jpg)
![Screenshot 2023-05-07 134147](https://user-images.githubusercontent.com/132821684/236675480-ba6c3639-51a5-4b85-8dd1-ef79ff51adb1.jpg)
![Screenshot 2023-05-07 134159](https://user-images.githubusercontent.com/132821684/236675483-d7828a7b-ecb3-4d78-a18d-daa1e54ee41c.jpg)
![Screenshot 2023-05-07 134208](https://user-images.githubusercontent.com/132821684/236675485-f2b72737-4758-4853-b706-5ed92a2bacdd.jpg)

**Comment by Saereth** [comment]
Which modpack is this? This is definitely not ftb skies and those arent 1.19 thermal textures

**Comment by Edersoon** [comment]
Thx for commenting it’s Infinity Evolved then I think it’s 1.7.10
