### ISSUE TITLE
Repeated crash when traveling large distance from starting island

### ISSUE THREAD

**Issue by atealein** [FTBTeam/FTB-Modpack-Issues#3322]
### Modpack

FTB Skies

### Modpack version

1.0.9

### Log Files

https://pastebin.com/zKyVqk8L

### Describe the bug

I am flying in overworld (teams dimension) and trying to find castle in the sky. I have approximate coordinates that are ~15k blocks away from spawn. I traveled over 10k of them without any issues. Then in less than one hour I've had three complete crashes (logs produced, see one example above) - and i got about 10-15 minutes between relaunches. First time the crash was while flying (everlasting abilities Flight), second time was when i was stationary (flying) and trying to break a block (one of the ElementalCraft shrines) and the most recent one I was exploring a Hexerei village and neither flying nor moving quickly. 

I complained in Discord and few people mentioned they have experienced similar things trying to travel far away, so thought to post it here too. 

### Steps to reproduce

So far it seems just being at high distance from spawn is the only common denominator. 

### Expected behaviour

Not crash?

**Comment by AichiChikuwa** [comment]
We had the same issue, but in our case the player who is most far from their base is only x=3024.85, y=150.20, z=1660.98. Here's the crash report. https://mclo.gs/pAVWXYF

**Comment by Micaxs** [comment]
Having the same issue, seems to occur with elementalcraft source nodes when a plaer comes into the vicinity of these.

**Comment by AichiChikuwa** [comment]
> Having the same issue, seems to occur with elementalcraft source nodes when a player comes into the vicinity of these.
> 
> It occurs when running into these (happens in the nether and the end dimensions as well as every ftbdimensions they are generated in): ![image](https://user-images.githubusercontent.com/14205312/237109390-26217db7-8dc5-4773-bda8-0c0772fd0410.png)
> 
> Might be fixed in an updated version of elementalcraft since they are onto 5.8.4 now.

can confirm the bug is from the mod itself and is fixed in the latest version.
