### ISSUE TITLE
Crash with Gaia Agglomeration plate & comparator

### ISSUE THREAD

**Issue by charred1** [FTBTeam/FTB-Modpack-Issues#3323]
### Modpack

FTB Skies

### Modpack version

1.0.9

### Describe the bug

placing a comparator to read out of the gaia plate crashes the game instantly, and on reload.
loaded a backup and reproduced. comparator worked fine out of the terrestrial plate.

### Steps to reproduce

build a gaia agglomeration plate & multiblock. place comparator next to plate to read out of the plate. immediate crash

### Expected behaviour

no crash

**Comment by Saereth** [comment]
This has been reported to the mod dev, we're waiting for an update to fix it
