### ISSUE TITLE
Direwolf20 1.19 1.10.0 crashes with SIGBUS

### ISSUE THREAD

**Issue by sethtaplin** [FTBTeam/FTB-Modpack-Issues#3325]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.10.0

### Log Files

[hs_err_pid736.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11415840/hs_err_pid736.log)

### Describe the bug

JDK SIGBUS upon launching the server, following an upgrade from 1.9.0 to 1.10.0

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0x0000000112f8d4e4, pid=736, tid=51719
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# v  ~StubRoutines::SafeFetch32
```

### Steps to reproduce

1. Update working 1.9.0 to 1.10.0
1. Run start.sh on a M1 Mac Mini

### Expected behaviour

Minecraft server launches successfully

**Comment by unilock** [comment]
It's a JVM bug in Java 17.0.7, *specifically* on aarch64 macOS. Downgrading to Java 17.0.6 should fix the issue, for the time being.  
https://bugs.openjdk.org/browse/JDK-8307549

**Comment by Saereth** [comment]
This is the answers, ty unilock, yeah not something I can fix unfortunately from the pack side of things

**Comment by sethtaplin** [comment]
I confirmed that downgrading to 17.0.6 did resolve the issue.
