### ISSUE TITLE
Steel Ingots for Ad Astra missing entirely, can't make Steel ingots for Mekanism

### ISSUE THREAD

**Issue by Tikayle** [FTBTeam/FTB-Modpack-Issues#3326]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.10

### Describe the bug

When placing iron ingots in a furnace or blast furnace, nothing happens. Steel ingots from the Ad Astra modpack are missing entirely and there is no way to craft Mekanism or Immersive Engineering ingots.

### Steps to reproduce

1. Open furnace
2. Place iron ingots in top slot
3. Place coal in bottom slot
4. Nothing happens

### Expected behaviour

I expect to make steel ingots when iron and coal are placed in (blast) furnace

### Screenshots

![image](https://user-images.githubusercontent.com/132857127/236707886-e9a281a8-4942-4c42-a0bc-31bea4f63d71.png)
![image](https://user-images.githubusercontent.com/132857127/236707901-8b3b45cb-7112-4aa0-9ed1-d5f96c528f65.png)

**Comment by MechBFP** [comment]
Steel isn't made that way.

**Comment by Tikayle** [comment]
For Ad Astra it is? But the steel ingot for Ad Astra is missing entirely. I know steel is made differently for Mekanism but the enriched iron that's a midway step is missing for me too

**Comment by Saereth** [comment]
<img width="605" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/935f56e0-32d2-4ef5-9b06-041b8d4a3bfd">
<img width="649" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/7918d253-e416-4469-9272-8e8dbc327dbe">
<img width="506" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/6b12ad1d-91ae-4406-8438-c380d9e2e2be">

Seems to be working fine for me?
