### ISSUE TITLE
FTB Skies crashes server when going through Nether Portal

### ISSUE THREAD

**Issue by Somberous** [FTBTeam/FTB-Modpack-Issues#3329]
### Modpack

FTB Skies

### Modpack version

1.0.9

### Log Files

[crashdump.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11425758/crashdump.txt)

### Describe the bug

Whenever going through the nether portal, the teleporting player gets to the "nether" the maps states "plains" then the player will fall infinitely (nether never loads). This then leads to a crash of the server.

### Steps to reproduce

1. Build Nether Portal
2. Go through Nether portal
3. Wait for teleport to "complete"
4. Once teleport is done processing wait for the crash

### Expected behaviour

For the Nether to load and allow exploration

### Additional information

The Nether never even loads like stated in the issue https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3082

**Comment by BetaTraps** [comment]
From looking at your logs this is what i saw `java.lang.ErrorServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)`. This error tells me that when generating the nether its exceeding your tick rate that was set in your server.properties file. I would recommend changing `max-tick-time=60000` to `max-tick-time=-1` in your servier.properties file ,-1 turns off this max tick and it will run and maybe after the server loads and settles down the tick rate will go back to normal. Tick rate is a common issue i have experienced with multiple mod packs on my servers.

**Comment by Somberous** [comment]
> From looking at your logs this is what i saw `java.lang.ErrorServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)`. This error tells me that when generating the nether its exceeding your tick rate that was set in your server.properties file. I would recommend changing `max-tick-time=60000` to `max-tick-time=-1` in your servier.properties file ,-1 turns off this max tick and it will run and maybe after the server loads and settles down the tick rate will go back to normal. Tick rate is a common issue i have experienced with multiple mod packs on my servers.

This worked, thanks!
