### ISSUE TITLE
[Bug]: PackagedExCrafting's Combination Crafter can't be crafted

### ISSUE THREAD

**Issue by zoller27osu** [FTBTeam/FTB-Modpack-Issues#333]
### Modpack

FTB University 1.16

### Modpack version

1.3.0

### Describe the bug

PackagedExCrafting's Combination Crafter, which automates the Extended Crafting's Crafting Core, cannot be crafted due to the removal of recipes (in kubejs/server_scripts/recipes/removals.js) for the ender_crafter and certain ender items that make up the Combination Crafter (https://github.com/TheLMiffy1111/PackagedExCrafting/blob/1.16/src/main/resources/data/packagedexcrafting/recipes/combination_crafter_ae.json)

Granted, the version of the Combination Crafter currently in the pack is bugged and will crash your game, but I completely fixed it in https://www.curseforge.com/minecraft/mc-mods/packagedexcrafting/files/3535198! (be sure to include https://www.curseforge.com/minecraft/mc-mods/packagedauto/files/3531871 for QoL as well!)

Please make sure it can be crafted in the next pack release, either by re-enabling those ender items, or providing a substitute recipe for the Combination Crafter. Thanks!

### Steps to reproduce

1. Search for "Combination" in JEI
2. Press R or left click on the Combination Crafter - nothing comes up

### Expected behaviour

The Combination Crafter should be craftable

**Comment by zoller27osu** [comment]
Unrelated: please also update Botania to version 420 (https://www.curseforge.com/minecraft/mc-mods/botania/files/3523132) to fix an issue that crashed my world 5 times

**Comment by aaronhowser1** [comment]
If the machine doesn't have a recipe, it likely isn't implemented yet. The combination crafter has a recipe in the latest version, but the basic package crafter doesn't, so I made an issue here TheLMiffy1111/PackagedExCrafting/issues/9

I don't like Ender Crafting, and have no recipes that use it, so there's no point in keeping the machines.

I (almost) always update mods to the latest version

Yes.

**Comment by zoller27osu** [comment]
A Basic Package Crafter would be pointless as the entire point of Package Crafting is the ability to fit more than 9 items into a recipe.
But the Combination Crafter is very useful for fully automating Combination recipes like the Creative Source Jar, Creative Ability, Creative Upgrade, etc.
