### ISSUE TITLE
i cant install the modpack correctly

### ISSUE THREAD

**Issue by francueto00** [FTBTeam/FTB-Modpack-Issues#3331]
### Modpack

FTB Skies

### Modpack version

1.0.9

### Describe the bug

i try to install the modpack but when i try to start it the instance crush and i cant play it.
I need help thanks u

### Steps to reproduce

1. install the modpack
2. run the modpack
3. crush the instance

### Expected behaviour

when i run the modpack i want to play

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/133018307/02d86a6f-8558-4bfa-8386-5d6272a0cb88)

**Comment by MichaelHillcox** [comment]
Please attach crash reports

**Comment by francueto00** [comment]
How can i do it?

**Comment by francueto00** [comment]
I actualizated the Java and drivers and i cant install the modpack Well yet, what can i do now?

**Comment by Saereth** [comment]
we cannot offer you OS/Java system support due to liability issues, that support is beyond the scope of this issue track so you'll need to get help with your OS/Java/Drivers elsewhere.
