### ISSUE TITLE
Broken Recipe?

### ISSUE THREAD

**Issue by Dukasho** [FTBTeam/FTB-Modpack-Issues#3332]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.19.0

### Describe the bug

mod -Ars Elemental 
recipe - Mark of Mastery

Doesn't seem to work, say's no valid recipes found when attempting to start up the imbument chamber

### Steps to reproduce

Imbument chamber, 8 arcane pedestals 1 block away, 1 full source jar 2 blocks away (tried with up to 4), activate imbument chamber with wilden trophy

### Expected behaviour

create 5 marks of magic

**Comment by Saereth** [comment]
working on 1.11 update,ars elemental updated and seems to be working now
