### ISSUE TITLE
game overload

### ISSUE THREAD

**Issue by Emmanuel-true** [FTBTeam/FTB-Modpack-Issues#3334]
### Modpack

FTB Skies

### Modpack version

1.0.8

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11432761/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11432762/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11432763/latest.log)

### Describe the bug

The server crashed so I play on my machine, it was so slow I don't know what was wrong with it. I was given 10G memory.

### Steps to reproduce

1. open ftb
2. open ftb skies modpack
3. lag

### Expected behaviour

not that slow

### Screenshots

![Overwolf_Gi0hBVI1bf](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26563556/8ab496ed-4825-4ea4-ab08-52db7ac2732f)

**Comment by MichaelHillcox** [comment]
Please run a spark log

**Comment by daniloqz** [comment]
Any solution? i have the same problem here

**Comment by Emmanuel-true** [comment]
It was 4G+ how can I upload

**Comment by Emmanuel-true** [comment]
Most of them was young gen

**Comment by Emmanuel-true** [comment]
![javaw_ciIOhSeGa9](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26563556/37fedb9a-717c-42e4-a4e3-357d838ca397)
![javaw_jhw7wlkDU6](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26563556/67c89f14-a7d9-47d4-94ac-fa92a834e15c)
![javaw_Uf7WwR9MG2](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26563556/4125f445-628b-4194-ad5e-15541b140f07)
[DLHxNBH8tk.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11447250/DLHxNBH8tk.zip)
okay i figure it out

**Comment by Emmanuel-true** [comment]
> Any solution? i have the same problem here
i don't know i want help too

**Comment by Pecako2001** [comment]
i have the same problem disconnecting the AE2 storage systems seems to clear at the lagg in i can play normally

**Comment by Saereth** [comment]
your issue seems related to Bees, this next update has a fix from productive bees that will hopefully fix that

**Comment by Emmanuel-true** [comment]
i restart a new world this is my log and spark
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11459219/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11459220/latest.log)
[DLHxN).zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11459223/DLHxN.zip)
the tps is bad

**Comment by Emmanuel-true** [comment]
# ![Notepad_GxtXupDd4T](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26563556/ab42a0e7-0003-47d3-b754-3a75b48af9b2)
i restart a new world this is my server log and sparkprofile forreference
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11459219/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11459220/latest.log)
[DLHxN).zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11459223/DLHxN.zip)
the tps is bad

**Comment by Mack3sh** [comment]
[EkjcAh1MQ8.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11465407/EkjcAh1MQ8.zip)
