### ISSUE TITLE
minetogether crashes when I try to use

### ISSUE THREAD

**Issue by TheEggCake** [FTBTeam/FTB-Modpack-Issues#3337]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.6.0

### Log Files

[crash-2023-05-10_00.39.00-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11439143/crash-2023-05-10_00.39.00-client.txt)

### Describe the bug

game crashes when I try to use minetogether mod 

### Steps to reproduce

1. Join world
2. open option
3. click 'open to friends'
4. crashes

### Expected behaviour

It should normally just open the single player world to my friends

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/41491144/ba643f91-0aa6-4aa1-bfdf-5bef882df0d7)
 it crashes when I click it

### Additional information

I've used this mod with my friend in stoneblocks3 before and it worked perfectly, but it just crashes when I try to use it in the legend of the eyes modpack. It also crashes when my friend tries to use the mod.

**Comment by Gaz492** [comment]
Is this still an issue in the latest version of the pack for you?
