### ISSUE TITLE
Cow In a Jar Recipe Broken

### ISSUE THREAD

**Issue by gman4161** [FTBTeam/FTB-Modpack-Issues#3338]
### Modpack

FTB Skies

### Modpack version

1.0.9

### Describe the bug

The cow in a jar recipe says to drop a jar or an anvil on a cow in a jar with a cow to get cow in a jar. Oddly enough, the cow in a jar recipe is also considered a USE of the cow in a jar and has no recipe to GET cow in a jar. Very weird.

Also, the dropping anvil on cow over a jar still works as intended, but doesn't create the cow in a jar. It consumes the cow and makes the noise, but the jar remains empty.

### Steps to reproduce

JEI recipe check cow in a jar

### Expected behaviour

anvil on cow over jar should work

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/28549680/53acb06d-dc79-47f3-8d6b-8c983eb8efb4)

**Comment by gman4161** [comment]
I swear I was doing it right, I've done it 100 times before without issue. The only thing I can think of is if I dropped the anvil from too high or low, but it looked like it worked, but the milk jar didn't turn into a cow in a jar.

**Comment by Movcog** [comment]
Not sure if it's okay to bump a couple month old issue, but I am having the same problem. No matter what I do, dropping an anvil onto a cow that is stood ontop of a milk jar, just makes the pop noise and then remains a milk jar and the cow still disappears.
