### ISSUE TITLE
Flame Lily not growing

### ISSUE THREAD

**Issue by Heregerifa** [FTBTeam/FTB-Modpack-Issues#334]
### Modpack

FTB Oceanblock

### Modpack version

1.8.0

### Describe the bug

JEI indicates that flame lily seeds can grow in botany pots using netherrack.

Tried planting one in both botany pot and hopping botany pot using netherack - interface then shows percentage progress as [maxint] number and time to grow counting negatively. Occurs in both overworld and nether.

### Steps to reproduce

Obtain flame lily seed 
place botany pot and insert netherack
plant seed
hover cursor over pot to access interface

### Expected behaviour

Progress should start at zero and time to grow should be 3 minutes

### Screenshots

![2021-11-18_18 08 08](https://user-images.githubusercontent.com/38160792/142473808-4d43b862-41f8-456b-9a04-39810a7bb917.png)

**Comment by quietust** [comment]
The problem looks to be that Netherrack was defined with a growthModifier of `1.0` which means **-100%** (i.e. instant) when it should've been `0.0` (to mean "no growth speedup").

**Comment by Heregerifa** [comment]
Thanks. Noted that blaze mesh works as expected
