### ISSUE TITLE
Server running behind / lagging on normal use

### ISSUE THREAD

**Issue by Semorphim** [FTBTeam/FTB-Modpack-Issues#3340]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.10.0

### Log Files

https://spark.lucko.me/zsI4fMelXE

### Describe the bug

After setting up the server with pterodactyl (forge egg version 1.19.2-43.2.8) with 12GB of RAM.
Starting the Server and joining with 3 to 4 players I get console spammed with "can't keep up is the server overloaded”
After running spark I thought maybe it is ticking entities but I'm not sure.

### Steps to reproduce

1. Install server
2. give enough RAM to it
3. start Server and join
4. lag

### Expected behaviour

No Lag? 

### Additional information

I've also installed the Mod inControl and reduced hostile Mob Spawns to 25 per Player in hopes of reducing entities. To no avail so far.

**Comment by Semorphim** [comment]
I forgot to add that I use an Intel(R) Xeon(R) CPU E5-2643 v2 @ 3.50GHz and allocated 6 Cores to this server.

**Comment by Saereth** [comment]
version 1.11 coming out soon has some performance tweaks in it that should help
