### ISSUE TITLE
Missing recipe for Farmer's Delight Onions in JEI

### ISSUE THREAD

**Issue by BrewingCoder** [FTBTeam/FTB-Modpack-Issues#3341]
### Modpack

FTB Skies

### Modpack version

1.0.9

### Log Files

N/A

### Describe the bug

JEI Missing recipe for wild onion; which apparently is only available from the market block.  

### Steps to reproduce

Enter game, use JEI, look for recipe for wild onion.

### Expected behaviour

JEI should show the only means to get the wild onion is via the Market block

**Comment by MisterWuff** [comment]
Did you check the recipe for wild onions at all?
At least in 1.0.6 they clearly show you that you can purchase it from the Market by Farmer's delight. So as far as this not having changed this issue is invalid.

**Comment by BrewingCoder** [comment]
JEI doesn't show a recipe for wild onion in 1.09; I haven't checked the market. Thanks for this.

**Comment by BrewingCoder** [comment]
Negative; the onion is not available in the Market in 1.09

**Comment by convict-vx** [comment]
> EDIT: Market does sell wild onion; JEI just doesn't show the recipe.

if im not mistakej use the wild onions on a cuttingboard with a knife and u would have 2 onions, plant and harvest.

**Comment by Saereth** [comment]
yeah this is the process for all of farmer delight's plants pretty much
