### ISSUE TITLE
Create Motor recipe bug in RS

### ISSUE THREAD

**Issue by Worgeen** [FTBTeam/FTB-Modpack-Issues#3346]
### Modpack

FTB Skies

### Modpack version

1.0.9

### Describe the bug

When u try to click on JEI "+" to bring the recipe of the "Electric Motor" to the pattern grid, you get a crash.

### Steps to reproduce

1. Open a "Pattern Grid";
2. Look for "Electric Motor" recipe;
3. Click on "+" to add the recipe to the terminal;
4. Get a crash.

### Expected behaviour

Getting the correct recipe on the terminal, and no crashes at all

### Additional information

Since i was in Multiplayer, i got a disconnect message. Can't remember now what was written on it, but is something about craft length, that was bigger than 9.

**Comment by MechBFP** [comment]
You don't make motors in the crafting grid. You can make them using Creates mechanical crafter instead.

**Comment by Saereth** [comment]
this is a duplicate issue, its been reported, Rs will have to fix it, and yeah you craft it in the mechanical crafter

**Comment by Worgeen** [comment]
> You don't make motors in the crafting grid. You can make them using Creates mechanical crafter instead.

@MechBFP I bet u didn't read it with 2% of your full brain potential. "Pattern Grid" isn't a "Crafting Grid".
