### ISSUE TITLE
Cyclic Forester not... foresting?

### ISSUE THREAD

**Issue by ProgrammerPanda** [FTBTeam/FTB-Modpack-Issues#3348]
### Modpack

FTB Skies

### Modpack version

1.0.9 + 1.0.10

### Describe the bug

I set up a forester from cyclic to attempt and automate wood gathering, but for some reason the forester won't plant or run wven when fully powered and redstone is supplied (i tried both redstone and always on).

The forester works in 1.0.7, but not in later versions?

### Steps to reproduce

1. place forester by a dirt field of any size up to max 21x21
2. add a power source (FE) to the forester
3. supply saplings
4. wait to see if forester plants the saplings.

### Expected behaviour

The forester (if working) should plant saplings and wait for them to grow, then chop the blocks.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/24791891/83ee9f8f-8672-4a49-adf4-f24531190b5d)
![2023-05-12_08 49 16](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/24791891/d14c1760-cb1a-49e1-a1c7-315c737565cf)

**Comment by STK-Close** [comment]
Can confirm. We have the same issue. It is a problem with areas that are chunk loaded. Spawn protection isn't an issue.

**Comment by Saereth** [comment]
You need to go into your ftb chunk settings and allow fake users access to your claimed areas

**Comment by iCloudly** [comment]
still not working

**Comment by WhiteFire-Sondergaard** [comment]
Going into my team settings and turning on the "Allow All Fake Players" setting fixed it for me.
