### ISSUE TITLE
[Bug]: Elevator + Caving Torch Charm = Torch Spam

### ISSUE THREAD

**Issue by PotatoKnight** [FTBTeam/FTB-Modpack-Issues#335]
### Modpack

FTB Academy 1.16

### Modpack version

1.2.0

### Log Files

N/A

### Describe the bug

While equipped with an enabled Caving Torch Charm and using an Elevator from the Elevator Mod, the Torch Charm goes nuts and spams torches in every available space around you.

### Steps to reproduce

1. Place down an Elevator (I used White).
2. Step onto it with an Enabled Caving Torch Charm.
3. BEHOLD, GLORIOUS ILLUMINATION.

**EDIT**:
The bug spontaneously stopped occurring for me so there is definitely some X-Factor going on. I'll update this if/when I figure out what that is. Some experimentation may be necessary - I'm very early game, nothing fancy in terms of other interactions or gadgets going on.

**EDIT 2**:
I now have it where it only happens to the bottom of my 3 elevators. The upper two are fine.

### Expected behaviour

For the caving charm not to go absolutely nuts.

### Screenshots

![2021-11-19_00 52 56](https://user-images.githubusercontent.com/4663736/142520243-c18a2861-7b4b-4cb3-9b5a-daf1810a81b7.png)

**Comment by Raidobw2** [comment]
It's been reported 9 days ago apparently on Lothrazar/Cyclic#1969

**Comment by PotatoKnight** [comment]
> It's been reported 9 days ago apparently on [Lothrazar/Cyclic#1969](https://github.com/Lothrazar/Cyclic/issues/1969)

So it has, my mistake! I hope the additional information offered (IE it isn't consistent) helps with bug cracking though :)

**Comment by Raidobw2** [comment]
The mod author closed the issue on their end. Looks like that was fixed in an "older" version, since that issue was idle for a good while.
Basically, the mod update should fix it.

**Comment by sarim** [comment]
@Raidobw2 Academy 1.16 is also affected. Might also want to add tag for that.

**Comment by Raidobw2** [comment]
Oops that must have been a misclick on my end, it was meant to be academy 1.16. Thanks
