### ISSUE TITLE
Roots Acceleration spell doesn't apply properly to Crystal staff

### ISSUE THREAD

**Issue by atealein** [FTBTeam/FTB-Modpack-Issues#3350]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Describe the bug

The crystal staff should have the acceleration spell (potency 3) added to it when using specific ingredients, the ritual activates properly but end result doesn't show the spell (but shows the staff as containing -something-?).

### Steps to reproduce

1. set up roots altar with 4 brazers around it; mortar and pestle
2. use the ingredients in the mortar for acceleration with potency 3 ( in this order - oxi daisy, end stone, gold ingot, sugar, dragon eye, 3 glowstone dusts), mix with the pestle
3. place a newly spawned crystal staff and verdant roots on the altar
4. place the mixture from the mortar into one of the brazers and light it up
5. sneak right click on the altar to activate the imbuement process - the animation activates
6. check the resulting crystal staff

### Expected behaviour

To have the spell in the staff

### Screenshots

This is how the resulting crystal staff looks like: ![Screenshot 2023-05-12 at 09 45 21](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25322782/4eab6338-9d37-4e74-b455-7f03f75aa090)

This is how it looks with a different spell: 
![Screenshot 2023-05-12 at 09 34 48](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25322782/bbabb19a-5388-44a7-aa12-b360e7fa9f64)

**Comment by Saereth** [comment]
https://github.com/Lothrazar/RootsClassic/issues/93
