### ISSUE TITLE
Task Screen doesn't accept honey at all. (100 B Quest- Just getting started)

### ISSUE THREAD

**Issue by Yamijro** [FTBTeam/FTB-Modpack-Issues#3351]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Describe the bug

After using the Centrifugal seperator to get the honey liquid out of combs and bottles i could not get it to be piped into the task screen.
I double checked the settings of the screen and the settings of the mekanism pipes i used. I tried many different ways of pumping it in even exporting it out of RS and many different tanks. Nothing seems to work. 

### Steps to reproduce

1. Set task screen to the above mentioned quest.
2. Connect any fluid storage filled with honey to it via appropriate piping.
3. Watch it or rather watch the honey not going in the task screen like its supposed to be.

### Expected behaviour

I expected the honey to be piped into the task screen.

### Screenshots

![2023-05-12_11 35 27](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/132203466/8caa443c-fdbe-4cb8-a1dc-b1276980b5d7)
![2023-05-12_11 35 31](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/132203466/2136a67f-7657-4b63-b623-f5750d0c6cfb)

### Additional information

Right before i wanted to turn in the honey i turned in the 100k FE quest via the task screen and it worked fine. I also tried crafting new ones but the dont seem to work either.

**Comment by MechBFP** [comment]
Honey isn't unified for some reason. It only accepts Productive Bees honey.

**Comment by Saereth** [comment]
this quest specifically requires productive bee honey to ensure people are getting into/using that mod for this quest objective. I added a note to the quest to clarify this.
