### ISSUE TITLE
XP Obelisk Crash When Teleporting Away

### ISSUE THREAD

**Issue by jokerr77** [FTBTeam/FTB-Modpack-Issues#3354]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.0

### Log Files
[crash-2023-05-13_00.13.55-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11468865/crash-2023-05-13_00.13.55-client.txt)

### Describe the bug

Teleporting away from my base with an XP obelisk placed down causes the game to crash and generate the above error.

Teleporting home (towards the XP obelisk) doesn't cause the game to crash,

### Steps to reproduce

1. Have XP Obelisk placed down near you
2. Teleport a few chunks away (I used the tempad, but using /warp or other methods seem to cause it too)
3. Game crashes

### Expected behaviour

Game shouldn't crash

### Additional information

Haven't tested downgrading the XP Obelisk mod back to what is used in Stoneblock 3 1.6.1 (experienceobelisk-v1.3.6-1.18.2), but that might fix it

**Comment by UnRealDinnerbone** [comment]
Update Released
