### ISSUE TITLE
Create press and basin not working.

### ISSUE THREAD

**Issue by turd13** [FTBTeam/FTB-Modpack-Issues#3355]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.0

### Describe the bug

When using the Create press and basin for compacting any of the Fluorite buds, the press activates once upon the first place of the basin, but immediately stops functioning. Re-placing the basin allows the press to activate once more, but only doing that.

### Steps to reproduce

Use a metal press and basin with Create. I'm using Fluorite buds in the packing method, though it seems to happen with the press in general.

### Expected behaviour

Funciton stops after one activation.

**Comment by UnRealDinnerbone** [comment]
I'm unable to reproduce this issue on my end. I put a stack of small fluorite buds, and after it pressed down about 20 times I got a fluorite cluster out of it. Do you have a filter or something on it that stopping it?
