### ISSUE TITLE
Part of the world bugged after a server restart. 

### ISSUE THREAD

**Issue by KavisKryptic** [FTBTeam/FTB-Modpack-Issues#3357]
### Modpack

FTB University 1.16

### Modpack version

1.8.0

### Log Files

https://bytebin.lucko.me/5kpa6zgXnI

### Describe the bug

Top of our house's blocks are bugged, most textures are invisible even though it's still there. Any interaction causes a crash, log provided

### Steps to reproduce

Unsure. We started crashing after a bit, so I restarted the server. But then we came back to this. 

### Expected behaviour

For it not to be bugged?

### Screenshots

![Uploading 2023-05-12_22.22.01.png…]()
![2023-05-12_22 26 29](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/51237952/dfef5d68-dd28-4f6c-9f0f-0d4287026c57)

### Additional information

This is kind of unfortunate, since this is the entrance to our base, any time we interact with the door or block, we crash.

**Comment by KavisKryptic** [comment]
Sorry, wrong label, this is FTB University 1.16

**Comment by Gaz492** [comment]
Unfortunately, the log you linked in no longer valid, so I'm not exactly sure what's happened here.
I would suggest restoring a world backup in this case.
