### ISSUE TITLE
Elementalcraft Fire Pylon Dupe Bug

### ISSUE THREAD

**Issue by DarGo68** [FTBTeam/FTB-Modpack-Issues#3358]
### Modpack

FTB Skies

### Modpack version

1.0.9

### Describe the bug

I made a fire pylon from elemental craft and miss placed it down. Broke it and got 2 back. tried many pickaxes and all did the same.

### Steps to reproduce

make fire pylon
place down
break
get 2 back

### Expected behaviour

Only expected to get 1 back

**Comment by Saereth** [comment]
https://github.com/Sirttas/ElementalCraft/issues/145
