### ISSUE TITLE
Difficult to acquire 'Niter'

### ISSUE THREAD

**Issue by andr9528** [FTBTeam/FTB-Modpack-Issues#3359]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

Playing on 1.0.9, wanting to setup Phytogenic Insolators using Phyto-gro, i found that the only source of Niter, when you have none, is from Industrial Foregoings Laser Drills.
As soon as you have gotten a blocks worth you can also use bees, which not all players like, including me.

I'd highly suggest Niter being added as a drop from Sifting Dust, just like its counterpart, Apatite, is gained from.

**Comment by BrewingCoder** [comment]
you can add the following line to your sifting.js file , located in the kubejs/server_scripts folder:

[dust,'thermal:niter_dust',0.3,3,false],

That will add a 30% chance of getting a niter dust when using an amethyst mesh.  If you want it to be a lower tier mesh reduce the 3rd value.

It's easy to tweak the recipes.  On our server we bumped the diamond/coal % when using the amethyst and reduced the iron/copper to more balance for needs middle to end game.

**Comment by Saereth** [comment]
Thermal already provides a way to make unlimited niter by pulverizing sandstone which is itself renewable.
