### ISSUE TITLE
[Suggestion]: Have the netherite and empowered sluices keep their stored power when broken.

### ISSUE THREAD

**Issue by BennyOfEarth** [FTBTeam/FTB-Modpack-Issues#336]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

Not sure how hard this would be to implement, but other mods have similar things, but it is a bit of a nuisance to lose up to 71,000,000 rf when you upgrade a sluice or want to drain the liquid from the sluice to switch between lava and water.

**Comment by Raidobw2** [comment]
@MichaelHillcox ^
