### ISSUE TITLE
Swap Metal Barrels & Iron Chests with Sophisticated Storage

### ISSUE THREAD

**Issue by andr9528** [FTBTeam/FTB-Modpack-Issues#3360]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

I am currently playing on version 1.0.9, which along with prior version includes _Metal Barrels_ and _Iron Chests_, both of which could be replaced by a single mod, _Sophisticated Storage_. From looking at the Changelog for 1.1.0, this doesn't seem to have changed.

The Pack already includes _Sophisticated Backpacks_, so including its brother mod would make some sense.
_Sophisticated Storage_ brings many of the upgrades that _Sophisticated Backpacks_ has to a full block form, along with a wide selection of barrels that can functions similar to drawers from _Functional Storage_, but with the benefit of being able to apply a wide varity of upgrades to the Barrels.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage

**Comment by Saereth** [comment]
sophisticated storage was crashing during dev every time we tried to include it, sadly we cant swap them now as it would cause everyone's stuff to get deleted that is currently using them so we'll have to pass on this suggestion
