### ISSUE TITLE
Sophisticated Backpacks reset when upgrading. Mass item loss!

### ISSUE THREAD

**Issue by NJM1564** [FTBTeam/FTB-Modpack-Issues#3361]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Describe the bug

When upgrading Sophisticated Backpacks to the netherite tier everything gets reset. Items lost, colors of backpack get lost, upgrades get lost. Tested against auto smiting table and normal one.

sophisticatedbackpacks-1.19.2-3.18.45.819
sophisticatedcore-1.19.2-0.5.54.261

### Steps to reproduce

Take a diamond backpack upgrade it to netherite.
All items inside color settings and upgrades inserted are lost.

### Expected behaviour

All the other tier upgrades from base to diamond keep there settings and items.

**Comment by Saereth** [comment]
I can't reproduce this now in 1.2 so I'm assuming its fixed, let me know if you can reproduce this after the upgrade
