### ISSUE TITLE
Crash on try startup

### ISSUE THREAD

**Issue by IDKIDONTKNOWANAME** [FTBTeam/FTB-Modpack-Issues#3363]
### Modpack

FTB Skies

### Modpack version

1.0.9-1.0.8

### Describe the bug

so everytime i start it up it crashed after around 2-4 min of trying to launch
and idk what the error is but i think its smth with java def not with my memory

### Steps to reproduce

idk how its just when i start it up

### Expected behaviour

i just expected to start it and play the game but it wont

### Screenshots

<img width="548" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/133523092/31d698a3-bcf9-4649-8f84-7188a5bfd29c">

### Additional information

i think its java

**Comment by NateyWinkle** [comment]
I had this same issue and seems like the issue was the atio6axx.dll file, updating my graphics drivers fixed the issue with AMD card

**Comment by IDKIDONTKNOWANAME** [comment]
Yo nathan how do i update it

Op wo 17 mei 2023 03:31 schreef Nathan Pound ***@***.***>:

**Comment by Saereth** [comment]
this is a system os/driver not a pack issue, update your java and update your video card drivers. We can not offer support for you on doing that as its outside the scope of what we do here.
