### ISSUE TITLE
Wither Bone from Baubly Heart Canisters does not drop in latest version

### ISSUE THREAD

**Issue by FishOutOfH20** [FTBTeam/FTB-Modpack-Issues#3367]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Describe the bug

The wither bone does not drop from player kills or machine kills.

This makes the mod useless.

If your intention is to nerf it, then remove the mod as it serves no purpose.  You can't upgrade the sword or your hearts.

### Steps to reproduce

1. Kill wither skeletons.
2. Observe drops.
3. Notice no wither bones among them.

### Expected behaviour

Wither bones should drop

### Additional information

This only started happening in 1.10, so perhaps it's a problem with the originating mod.

**Comment by Saereth** [comment]
Wow such hostility, ok mod removed, just for you!

**Comment by FishOutOfH20** [comment]
Ok Saereth, but what exactly was hostile?  Maybe it was saying "perhaps it's a problem with the originating mod".
