### ISSUE TITLE
Teleporting far away from an Experience Obelisk block crashes the client

### ISSUE THREAD

**Issue by Wyvernity** [FTBTeam/FTB-Modpack-Issues#3368]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Log Files

[crash-2023-05-14_06.58.47-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11471093/crash-2023-05-14_06.58.47-client.txt)

### Describe the bug

Using any type of teleportation (tested with /back command and Portable Teleporter from Mekanism) away from an Experience Obelisk crashes the game. Breaking the block and teleporting does not crash.

### Steps to reproduce

1. Place down an Experience Obelisk (Mine had about 55 levels of experience stored).
2. Try to teleport to far location.
3. Game crashes.

### Expected behaviour

No crashes should happen and successfully teleport

### Additional information

I have used this experience obelisk in other mod packs and this never have happened before. It might be an issue with the newer version of the mod or some kind of strange interaction with another mod could be causing it.

**Comment by LWmods** [comment]
i ran into this on my 1.1.0 server yesterday can confirm its a client side crash
