### ISSUE TITLE
Creates Planter

### ISSUE THREAD

**Issue by XnetsracX** [FTBTeam/FTB-Modpack-Issues#3370]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Describe the bug

My Craete-planter cant plant Sapling, The Saw working fine

### Steps to reproduce

Always

### Expected behaviour

None

**Comment by ukmcplyr** [comment]
Do your deployers work if you change `Allow Fake Players` from `check` to `allow` in FTB CHunks' server settings windows (key `m` by default, then `Ctrl+S`)?

**Comment by XnetsracX** [comment]
ok, right, that was my mistake
