### ISSUE TITLE
Mod pack crashes shortly after skies tab opens

### ISSUE THREAD

**Issue by Snowbailes** [FTBTeam/FTB-Modpack-Issues#3371]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Log Files

[crash-2023-05-14_20.03.26-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11471638/crash-2023-05-14_20.03.26-client.txt)

### Describe the bug

instance crashes shortly after startup was working fine yesterday no issues 

### Steps to reproduce

open version 1.1.0

wait for startup skeis page to open

wait for crash..

### Expected behaviour

skies to open to main page to get into game

**Comment by Saereth** [comment]
you have a corrupt config file, delete config/reauth.toml
