### ISSUE TITLE
Cap spawns of forcecraft:angry_enderman

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#3373]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

Something seems to have changed between 1.0.4 and 1.1.0 with regards to ForceCraft's angry enderman.

Idling over night after building a relatively large mob farm (19x19 internal) on a server resulted in 80 angry enderman milling around, filling the bulk of the mobcap.

As In Control is already in the pack, I'll try limiting their spawning locally but maybe a config tweak would benefit others we well.  I can post what I come up with but I've never used the mod myself so it's highly likely you guys could come up with a better rule quicker :grin:

**Comment by ukmcplyr** [comment]
Seems like 80 was just the tip of the iceberg. From a server left idle for a day:

![Screenshot](https://gcdnb.pbrd.co/images/qEf6lnjuFdSm.png?o=1)

Ignore the 33 Blitz's, those are my fault due to missing fans on the roof of the mob farm.

**Comment by Saereth** [comment]
oh boy lmao sure if you've got setting tweaks I'll slap them in

**Comment by ukmcplyr** [comment]
It gets better, merked 267 yesterday :grin: 

Lightly tested but adding this rule to `config/incontrol/spawn.json` seems to be working fine:

```
        {
                "mob": "forcecraft:angry_enderman",
                "mincount": 5,
                "result": "deny"
        }
```

Capping at 5 is probably too conservative for a MP server but you'll have a better idea on what the upper limit should be.

Diff [here](https://pste.ch/asakubimaj.diff) in case it's helpful.
