### ISSUE TITLE
Second player Pharaoh bug

### ISSUE THREAD

**Issue by a1base** [FTBTeam/FTB-Modpack-Issues#3375]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.6.0

### Describe the bug

If both players in co-op pick up the Cursed Eye they both get the quest to kill the pharaoh to remove the cycling curse, but killing the Pharaoh vanishes the Curse only from the player who killed him. 

Curse is kept within the other one, with no luck to cure.

It looks like this bug was previously reported but the fix hasn't worked, I guess.

### Steps to reproduce

Described above.

### Expected behaviour

Curse needs to be removed from both players

### Additional information

A description of how to resummon him for the second player would be helpful

**Comment by TheonlyTazz** [comment]
i tried this again with 2 players together in a team and both got the stage pharaoh_beaten and then their curse got lifted
`    if(player.stages.has('pharaoh_beaten') && pData.cursed <2) pData.cursed = 2`

nevertheless, ill add more information on how to resummon the Pharaoh
