### ISSUE TITLE
Dreadful Dirt plus Mega Torch broken with mob_grinding_utils >= 0.4.48

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#3376]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Log Files

N/A

### Describe the bug

With the update of mob_grinding_utils to version 0.4.48/49, dreadful dirt within range of a mega torch stops functioning as it should (no mobs spawn).

vadis365/Mob-Grinding-Utils#249 contains a little more.

Verified this is fixed by downgrading to 0.4.47.

### Steps to reproduce

On a server:
1. Place dreadful dirt in range of mega torch
2. Hostile mobs will not spawn

### Expected behaviour

Hostile mobs spawn when dreadful dirt used in conjunction with the mega torch

**Comment by Saereth** [comment]
Downgrading causes mob overflow issues with blaze mek so we'll just wait for a fix from flanks, meanwhile just dont use megatorches near your dreadful dirt.
