### ISSUE TITLE
Unable to craft crimed mycelial generator industrial foregoing

### ISSUE THREAD

**Issue by Shadowstriker0s** [FTBTeam/FTB-Modpack-Issues#3377]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Describe the bug

Unable to craft crimed mycelial generator industrial foregoing. Nether Wart block not craftable and no direction from quest book explaining how to obtain item.

### Steps to reproduce

searching for block in JEI results in no way to craft needed block needed.

### Expected behaviour

Alterntive crafting recipes or chapter in the quest book for the method of obtaining required items.

**Comment by Saereth** [comment]
you grow crimson fungus on crimson nylium, their leaves are nether wart blocks. They also spawn naturally in crimson forests in the nether.
