### ISSUE TITLE
Sky Castle quest causes server to crash

### ISSUE THREAD

**Issue by Shadowstriker0s** [FTBTeam/FTB-Modpack-Issues#3378]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Log Files

[crash-2023-05-15_01.01.53-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11473404/crash-2023-05-15_01.01.53-server.txt)

### Describe the bug

Using Eye of sky legend results in the below error in the console and the server will crash

Can't keep up! Is the server overloaded? Running 2014ms or 40 ticks behind
20:00:51
Mod castle_in_the_sky is shipping outdated structure files, which can cause worldgen lag; please report this to them.

### Steps to reproduce

Craft Eye of the sky legend
add item to hotbar
attempt to use item
world gen lag then crash

### Expected behaviour

Assuming its behavior is like the other "eyes of legend" and lead player to structure

**Comment by Saereth** [comment]
run /modernfix upgradeStructures 
on your server as outlined here:
https://github.com/embeddedt/ModernFix/wiki/Outdated-Structures

Should fix it

**Comment by Stefanuk12** [comment]
Experiencing the same issue on version 1.2.1. Server also crashes when `/modernfix upgradeStructures` is ran.
[2023-05-31-1.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11617731/2023-05-31-1.log)
[crash-2023-05-31_20.21.17-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11617735/crash-2023-05-31_20.21.17-server.txt)

**Comment by Ninetailed** [comment]
If it crashes for you while `upgradeStructures` is running, you can re-run it after the server restarts and it will get a little bit further. I had to run it three times, but it did the job.

**Comment by Strengthless** [comment]
Why is this issue closed when it is not fixed, but only provided with a potential workaround (that is not even working for some people)...?
