### ISSUE TITLE
After 1.1.0 Update Refined Storage Does not detect External Storage on log in

### ISSUE THREAD

**Issue by Juravieal** [FTBTeam/FTB-Modpack-Issues#3379]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Describe the bug

On log in RS loses external storage connected to Functional Storage controller. This is the only external storage I have, so I am unsure if it happens for other external storages. The only way to get it to detect again is to break the RS Controller and re-place. 

### Steps to reproduce

1. Have RS system
2. Connect external storage to Functional Storage Controller
3. Log out
4. Log in
5. Functional Storage will be missing until breaking the RS Controller. 

### Expected behaviour

Not to be missing Functional Storage

**Comment by l3vines** [comment]
Using it on controller extension will probly help you out. I had the issue that when i connected the RS network to the FS controller that it wouldnt allow me to remove anything from the RS system so after googling abit i found a work around with the extension.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/16386078/48f71d27-4468-4a38-885b-fedf2363c809)

**Comment by Saereth** [comment]
currently known issue with RS/storage drawer, using it on extension is the work around until there is a proper mod fix

**Comment by Saereth** [comment]
waiting mod update, duplicate issue so closing for now
