### ISSUE TITLE
[Bug]: Redundant copper ore generation

### ISSUE THREAD

**Issue by LuciusV** [FTBTeam/FTB-Modpack-Issues#338]
### Modpack

FTB Endeavour

### Modpack version

1.6.0

### Describe the bug

Both Immersive Engineering and Thermal expansion ores generate in world

### Steps to reproduce

Just create a world

### Expected behaviour

Expect only one kind of every ore type generated

**Comment by LuciusV** [comment]
Sorry I forgot to mention it was copper

**Comment by Raidobw2** [comment]
Appears to have been fixed in an earlier version of the modpack -- I can't reproduce in newly generated chunks.
