### ISSUE TITLE
Auto inject on Infusing Factory don't work

### ISSUE THREAD

**Issue by Maelthh** [FTBTeam/FTB-Modpack-Issues#3382]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Describe the bug

Impossible to auto input with cable and/or with auto craft (with AE2) (the other machien from Meka fonction well)

### Steps to reproduce

...

### Expected behaviour

AUto craft with AE2 like the other meka machine

**Comment by Saereth** [comment]
confirmed, not sure if its on ae2 or mekanism's side though
