### ISSUE TITLE
Game crash when using Compact machine

### ISSUE THREAD

**Issue by Maelthh** [FTBTeam/FTB-Modpack-Issues#3383]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Log Files

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/133704254/4f4b85b6-24e0-4677-b8b1-e912ffaac82b)

### Describe the bug

Game crash when using compact machine (going in and out)

### Steps to reproduce

Go in and ou of some compact machine

### Expected behaviour

Do not crash and be playable

**Comment by Saereth** [comment]
Please provide an actual crash log from your crash-reports folder, this truncated snippet doesnt contain the information we need to diagnose the issue

**Comment by Maelthh** [comment]
The new update (1.2.1) fixe the crash :)
