### ISSUE TITLE
FTB StoneBlock 2

### ISSUE THREAD

**Issue by Cole-Pearce** [FTBTeam/FTB-Modpack-Issues#3385]
### Modpack

Other...

### Modpack version

latest

### Describe the bug

When i click on certain recipes the game crashes in a way where it takes me to the title screen however, i can't see anything but a small square

### Steps to reproduce

Open inventory
Search: Drop of evil
Left click on item

### Expected behaviour

Show how to get

**Comment by manmaed** [comment]
can you please provide the latest log and debug log files
