### ISSUE TITLE
A weird behavior of plant gatherer from industrial foregoing

### ISSUE THREAD

**Issue by vandr0s** [FTBTeam/FTB-Modpack-Issues#3386]
### Modpack

FTB Skies

### Modpack version

1.0.9-1.1.0

### Describe the bug

I have a weird behavior of plant gatherer from industrial foregoing. It dont harvest pumpkins, also when pumpkins appear on it's way it stops harvesting other random number of plants.

### Steps to reproduce

1. make a farm with plant gatherer
2. plant seeds on rich soil from farmers delight
3. provide gatherer with energy and ether gas
4. look hes working well until pumpkins grew up

### Expected behaviour

afaik plant gatherer must harvest pumpkins

### Screenshots

https://discord.com/channels/372448486723158016/1092887307830435921/1108388362341064774

### Additional information

i post a video example in discord ftb-skies channel:
https://discord.com/channels/372448486723158016/1092887307830435921/1108388362341064774

**Comment by Saereth** [comment]
This seems to be reproducible with incorrect fake player user settings in ftb chunks. Set fake players to allow so it can actually break the pumpkin.

**Comment by vandr0s** [comment]
I have tried to set fake players to allow in ftb chunks, or to unclaim all chunks. Doesn't help.
Also plant gatherer successfully harvesting cactus, sugarcane and melons. Only pumpkins making it stuck.
