### ISSUE TITLE
[Bug] Crash when connecting a comparator to a Fluix Mana Pool

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#3387]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Log Files

https://gist.github.com/JustAnotherGhostName/88c0113fed0c16d4451411eb7a3185e5

### Describe the bug

When a user placed a comparator next to a fluix mana pool from applied botanics, the server had a crash. I am uncertain why that would have caused it, seems like an odd thing to crash, but regardless it was confirmed by a player and the crash report that this is what happened. 

### Steps to reproduce

1. Setup a fluix manapool setup, potentially with mana already in it
2. Place a comparator next to it in order to get a redstone read of the mana level in the pool
3. Observe a server crash 

### Expected behaviour

No crash, receive readout of mana levels

### Screenshots

![2023-05-17_10 06 05](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/122759195/6cdf9c87-fada-452b-bc04-9101151098fd)

**Comment by Saereth** [comment]
https://github.com/ramidzkh/Applied-Botanics/issues/43
