### ISSUE TITLE
Experience Obelisk causes NullPointerException upon "FTB" teleport

### ISSUE THREAD

**Issue by Kzorith** [FTBTeam/FTB-Modpack-Issues#3390]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Log Files

[crash-2023-05-17_23.07.43-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11504608/crash-2023-05-17_23.07.43-client.txt)

### Describe the bug

If an Experience Obelisk has been placed in the world, using the FTB commands "warp" or "back" causes a crash when arriving at the destination away from where the experience obelisk is located.  Using home does not.

Removing the experience obelisk from the world prevents the crash.

### Steps to reproduce

1. Place down an experience obelisk on the starting island
2. Travel to a sky village and set a waypoint in the map and use the /setwarp command
3. Use the /home command to return to your starting island
4. Execute a teleport, either using /back, /warp, or waypoint submenu teleport
The game will crash upon your arrival at the destination.  Starting the game again, you will find yourself where you teleported to.

### Expected behaviour

The game doesn't crash.

**Comment by LWmods** [comment]
seems to be any form of teleportation. i just had the same crash using an Ars Nouveau portal. removing the obelisk fixes it.
