### ISSUE TITLE
Inventory font size adjustment

### ISSUE THREAD

**Issue by DRWho1027** [FTBTeam/FTB-Modpack-Issues#3391]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

I do not know how to adjust the font size for the text and the inventory/crafting huds. They are barely visible when I open up my options and inventory.

**Comment by Saereth** [comment]
that's all tied to ui scaling, in your graphics option set your UI scale higher to make them larger

**Comment by DRWho1027** [comment]
Thanks, I had to get real close to the screen to even read it, I know I need new glasses but not that bad.
    On Thursday, May 18, 2023 at 04:59:30 PM EDT, Saereth ***@***.***> wrote:  
 
 


Closed #3391 as completed.
