### ISSUE TITLE
Middle-click sorting a dank spreads out and may void items

### ISSUE THREAD

**Issue by asteranx** [FTBTeam/FTB-Modpack-Issues#3393]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Describe the bug

I had a Dank 7 with a boatload of materials, and I wanted to reorder the slots. Recalling the behavior of the old dank/null, I tried middle clicking to select a slot to swap, but the result was that every slot became filled with a 64 stack of dirt and the prior contents of those slots were deleted.

### Steps to reproduce

1. Spawn a Dank 7 and put it in bag mode
2. Add a large quantity of one item to it (cobbler + gold hopper + open crate will get you plenty of cobble)
3. (Optional) Add smaller quantities of one or more other items
4. Middle-click inside the bag UI

Observe that the single stack of cobble has spread out to fill all the slots of the dank, and excess cobble (as well as any other items) have been voided.

### Expected behaviour

Unsure, but not this

### Screenshots

![2023-05-18_19 15 01](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/18324808/91885fe9-78f3-47b2-887a-c3b3880d7f67)
![2023-05-18_19 15 57](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/18324808/7eb64349-1b31-4811-a639-43fe3c969284)

### Additional information

I saw in the latest patch notes that middle click sorting was disabled for advanced beehives to prevent a similar issue. I hope something similar can be done here. If danks don't allow you to reorganize their contents, that's fine. I'll just be happy knowing that I won't accidentially delete all my building materials again.

**Comment by ukmcplyr** [comment]
I might be misremembering (not got the game in front of me) but doesn't mousing over the `SORT` button in a dank say not to try and sort externally (e.g. via middle-click with an inventorysorter-like mod) for this very reason?

**Comment by asteranx** [comment]
> I might be misremembering (not got the game in front of me) but doesn't mousing over the `SORT` button in a dank say not to try and sort externally (e.g. via middle-click with an inventorysorter-like mod) for this very reason?

It's possible. But at the same time if it's possible to straight up block the action on a specific UI I think that'd save a lot of headaches. Clearly if there is a warning there it isn't obvious enough to get the message to everyone - in addition to myself there's at least one other person on the server I play on that's hit the same issue - so there's probably some value in looking into more comprehensive action.

**Comment by ukmcplyr** [comment]
> > I might be misremembering (not got the game in front of me) but doesn't mousing over the `SORT` button in a dank say not to try and sort externally (e.g. via middle-click with an inventorysorter-like mod) for this very reason?
> 
> It's possible. But at the same time if it's possible to straight up block the action on a specific UI I think that'd save a lot of headaches. Clearly if there is a warning there it isn't obvious enough to get the message to everyone - in addition to myself there's at least one other person on the server I play on that's hit the same issue - so there's probably some value in looking into more comprehensive action.

Yep. And now I do have the game in front of me, I see the warning's gone :thinking:

So I take back everything I said :grin:

**Comment by checkerddd** [comment]
Sophisticated Backpacks have their own sorting that is used when middle clicking, however when you hold shift and then middle click, It'll use the Inventory Sorter's sorting and spread everything out into stacks of 64 and void everything the same way. This backpack was full prior to accidentally doing that. I think that's what happened for you, Inventory Sorter took charge.
![2023-05-19_21 31 26](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/79051838/abe5fc3d-2ef6-4ede-818b-00ea03ddadc4)
![2023-05-19_21 31 28](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/79051838/a7b3c8be-c629-4ac2-92d1-98198ee9813f)

**Comment by asteranx** [comment]
> I think that's what happened for you, Inventory Sorter took charge.

I was aware of this much. I posted the issue to hopefully get the behavior blocked going forward to prevent others from having it. But that's a good point about the backpacks having the same problem. The stacking upgrades aren't something I usually use with backpacks so I hadn't considered that.

If there's a way to block it for the Danks then I hope it's possible to do the same for the backpacks.

**Comment by crysyn** [comment]
For what it is worth, it looks Iike industrial foregoing also suffers the voiding from being sorted. I have not tried this with many objects but the mob crusher, when sorting its inventory, voided everything, including the upgrades in it.

**Comment by Saereth** [comment]
blacklisted the sorting from danks for now unless the invsorter dev can fix it on their end and then we'll re-eneable it
