### ISSUE TITLE
Ship default server.properties enabling flight

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#3394]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

Unsure if it's that big of a deal, but since there're many flight options in the pack, adding a 'template' server.properties containing just `allow-flight=true` might be helpful to less esperienced players so that they don't get kicked from the server when moving too quickly in an inconvenient location, etc.

**Comment by JonBirdd** [comment]
It also sometimes kicks players when they fall off the map, or if you're falling through a void (if the area didn't load for example, and you're falling, waiting for it to load)
