### ISSUE TITLE
[FTB Skies] 2FPS Lag | Log Spam

### ISSUE THREAD

**Issue by DizzyDJW** [FTBTeam/FTB-Modpack-Issues#3395]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Log Files

https://mclo.gs/GjXoIwq

### Describe the bug

Every so often after a while of playing my frames drop to 2FPS. Logs are spammed with TONS of errors, main one being Integrated Terminals but I only used that mod in the very early game and there are no more integrated anything blocks anywhere in the world, aside from the Squeezer and Drying Basin, which aren't throwing errors.

The FPS drop lasts for 20-30mins until I change the Render Distance back and forth enough times for it to go away.

### Steps to reproduce

1. Load World??
2. Place Integrated Terminal??
3. Remove all Integrated Terminal Blocks from world???
4. See issue?????

### Expected behaviour

Not that

**Comment by Saereth** [comment]
r eadjusted the render distance in the new update, hopefully that fixes it
