### ISSUE TITLE
Pig spawns hogging mobcap

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#3397]
### Modpack

FTB Skies

### Modpack version

1.2.0

### Log Files

N/A

### Describe the bug

Seems like there might be a bug with pigs spawning in player dimensions.

The screenshot linked below shows a roughly 5x5 chunk area.  On switching vivid grass to stock grass blocks, pigs seem to spawn in every few minutes and after around an hour idling, 142 had spawned hogging the mobcap.  Ahem.

A couple of players on Discord [here](https://discord.com/channels/372448486723158016/1092887307830435921/1109209692644839474) and [here](https://discord.com/channels/372448486723158016/695329867037933609/1108974190490550332) have reported more extreme examples.

Seems like the angry enderman cap might have been part of a wider issue maybe?

I'll leave the server running and continue monitoring in case I do get the hundred(s) seen on Discord.

### Steps to reproduce

Unsure if this affects singleplayer as well but on a server at least:
1. Create a large area made entirely of grass blocks similar to the screenshot below
2. Idle and wait for pigs to spawn

### Expected behaviour

Pigs spawn less excessively

### Screenshots

![Player dim](https://gcdnb.pbrd.co/images/15AjzPdAd2U1.png?o=1)
![Entities](https://gcdnb.pbrd.co/images/8IRDw1CRcQfJ.png?o=1)

**Comment by ukmcplyr** [comment]
Seems like the numbers finally settled:

```
> execute in ftbteamdimensions:team/93643a02-06af-437d-8a88-75f037a32796 run forge entity list
[06:37:46] [Server thread/INFO] [minecraft/MinecraftServer]: Total: 486
[06:37:46] [Server thread/INFO] [minecraft/MinecraftServer]:   380: minecraft:pig
[06:37:46] [Server thread/INFO] [minecraft/MinecraftServer]:   68: forcecraft:angry_enderman
[...]
```

Not sure I can explain the large number of forcecraft:angry_enderman occupying two chunks, I never saw more than 5 in my testing of the incontrol rule capping them but maybe I didn't test it for long enough... :disappointed:

**Comment by ixanza** [comment]
Temporary solution you can do is put a dread lamp nearby. it prevents passive mob spawning

**Comment by ukmcplyr** [comment]
Yep.

Minor update since the last. The angry enderman incontrol `spawn.json` rule has been working flawlessly here, so long the number of other mobs/pigs doesn't enter the ridiculous realms. So not all bad.
