### ISSUE TITLE
Update 1.2.0 has duplicate mods

### ISSUE THREAD

**Issue by IamStig** [FTBTeam/FTB-Modpack-Issues#3398]
### Modpack

FTB Skies

### Modpack version

1.2.0

### Describe the bug

Ad-Astra-Giselle-Addon-forge-1.19.2-1.14.jar &
Ad-Astra-Giselle-Addon-forge-1.19.2-1.15.jar for example.
I have not looked further, manually removing now

### Steps to reproduce

update pack

### Expected behaviour

old versions removed

**Comment by lordgames27** [comment]
Here's a lil' list of the duplicate mods for people wondering : 
Ad-Astra-Giselle-Addon
Botania
BotanicAdditions
EverlastingAbilities
Flowerpatch
forcecraft
integratedDynamics
moonlight
pedestals

If you remove all the older variants, it seems to be opening fine, unsure if it's really the move
Also that's the entire mod updates list -2 or 3 mods from this new version. Have a nice one!

**Comment by Saereth** [comment]
this was an artifact of us migrating to git lfs luckily forge is smart enough to default to the most recent versions so you're fine to remove those, will get that cleared up in our next release
