### ISSUE TITLE
Unable to launch.

### ISSUE THREAD

**Issue by jakeljns** [FTBTeam/FTB-Modpack-Issues#3399]
### Modpack

FTB Skies

### Modpack version

1.2.0

### Log Files

[crash-2023-05-19_19.35.01-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11521433/crash-2023-05-19_19.35.01-client.txt)

### Describe the bug

When you enable the beta releases and launch 1.2.0, the modpack won't launch and instead crashes. 

### Steps to reproduce

1. Install 1.2.0
2. Launch modpack
3. Popup shows "Potentially Invalid Instance"
4. Click Launch
5. 

### Expected behaviour

Modpack was supposed to launch.

### Screenshots

![Screenshot 2023-05-19 195812](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/58644061/16f4a935-5148-43d0-ac98-beec367aa4fc)

**Comment by Saereth** [comment]
if you just hit launch it should work

**Comment by Saereth** [comment]
this is a duplicate related to their being duplicate mods

**Comment by manmaed** [comment]
Please install to a new instance and try again! Current is 1.3.1
