### ISSUE TITLE
[Bug]: Some Chapters in FTB Quests Not Showing as Completed

### ISSUE THREAD

**Issue by justinsSoJaded** [FTBTeam/FTB-Modpack-Issues#340]
### Modpack

FTB Academy 1.16

### Modpack version

1.2.0

### Describe the bug

Even after completing all quests, some chapters in the quest book are not detecting/showing as having been fully completed. The following chapters were not marked as "complete" for me:

- Getting Started
- Technology - Beginner
- Botania
- Astral Sorcery

### Steps to reproduce

1. Finish all quests in aforementioned chapters.
2. Observe as the chapter will not be changed to show it has been fully completed.

### Expected behaviour

Upon completion of all quests in a given chapter, the player should receive a toast letting them know they've completed it, and the text in the sidebar for that chapter should change from blue to a green.

### Screenshots

![2021-11-19_07 46 50](https://user-images.githubusercontent.com/93367156/142629684-b4a2f3a9-343a-4558-af57-6a4f26d3b17b.png)

![2021-11-19_07 47 24](https://user-images.githubusercontent.com/93367156/142629725-0e0b39e4-a42c-44f1-acc6-0cf7576697dd.png)

![2021-11-19_07 47 42](https://user-images.githubusercontent.com/93367156/142629739-6a6ac74c-ed35-43f8-8dc0-891ad7f87fce.png)

![2021-11-19_07 48 03](https://user-images.githubusercontent.com/93367156/142629752-33fea4af-f31b-44e3-acb2-e8d91aa38fe1.png)

**Comment by Raidobw2** [comment]
One last report as you finish the pack, you're legendary.

I hope you enjoyed the modpack and managed to learn a lot of things, and most importantly, had fun!
I saw some of your pictures on the FTB Discord every now and then -- you looked like you knew how to build pretty stuff and make it functional at the same time. That screenshot inside your base with the lights on the floor, and machine on the walls definitely got my attention.

Thanks for playing the modpack, and thank you for this last report.  Other adventures await you for sure!

**Comment by aaronhowser1** [comment]
FTBTeam/FTB-Mods-Issues/issues/123

**Comment by Raidobw2** [comment]
Linked, but not duplicate ^
