### ISSUE TITLE
multiplayer world crash

### ISSUE THREAD

**Issue by BlazeOfGameS** [FTBTeam/FTB-Modpack-Issues#3405]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Log Files

[crash-2023-05-20_21.56.03-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11523462/crash-2023-05-20_21.56.03-client.txt)
[crash-2023-05-20_21.48.28-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11523463/crash-2023-05-20_21.48.28-client.txt)

### Describe the bug

when entering the world the game goes to a black screen and then it crashes

### Steps to reproduce

we just entered each other's world

### Expected behaviour

enter the world normally

**Comment by Saereth** [comment]
disable the toast control mod, I've fixed this for the next update
