### ISSUE TITLE
Item bug

### ISSUE THREAD

**Issue by Myzoul** [FTBTeam/FTB-Modpack-Issues#3407]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Describe the bug

While taking some items from a beehive or quest book, small stacks will turn into only one. I had 4 honeycombs in my hive and only had one in my hand when I took them out. 

### Steps to reproduce

1. produce items in Beehibe or finish a quest in the quest book that gives multiples of an item (dragon glass)
2.  move the item or accept the item
3. it will sometimes only have one instead of whatever number it was supposed to be

### Expected behaviour

to give me my complete stack or reward

**Comment by Saereth** [comment]
productive bees put a fix for this, it will, be in the next update
