### ISSUE TITLE
SkyOdyssey Remove EMC from Time in a Bottle

### ISSUE THREAD

**Issue by gagekehoe** [FTBTeam/FTB-Modpack-Issues#3409]
### Modpack

FTB Sky Odyssey

### Is your suggestion related to a problem? Please describe.

I'm always frustrated when I accidently dump my Time in a Bottle into my transmutation tablet. It would be great to remove the EMC from the Time In a Bottle. All the ingredients to make it are EMC-able so I can get a new one anytime without Time In a Bottle needing EMC. I have lost multiple days of time to this.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
