### ISSUE TITLE
[Bug]: Botania's Fruit of Grisaia Not Replenishing Hunger Despite Full Mana

### ISSUE THREAD

**Issue by justinsSoJaded** [FTBTeam/FTB-Modpack-Issues#341]
### Modpack

FTB Academy 1.16

### Modpack version

1.2.0

### Describe the bug

The **Fruit of Grisaia** from Botania appears to be non-functional as it will not replenish hunger even if player has full mana.

### Steps to reproduce

1. Obtain the Fruit of Grisaia from a Dice of Fate after defeating the Gaia Guarding (level 2).
2. Attempt to eat fruit will full or otherwise ample mana.
3. Apple will be continuously "chomped", but the player's hunger will not replenish.

### Expected behaviour

When used, the item is supposed to make use of mana to fill the player's hunger bar.

### Screenshots

GIF showing the issue can be found here: https://imgur.com/YekTaz8

**Comment by aaronhowser1** [comment]
Do you have a source of Mana in your inventory? It didn't work for me until I spawned one in.

**Comment by Raidobw2** [comment]
Looks like it, on the GIF there's a mana bar atop the xp bar

**Comment by justinsSoJaded** [comment]
Yeah, I had the terrasteel versions of both the mana band and the aura one as well.

**Comment by aaronhowser1** [comment]
Does this still happen if you update to the latest Botania?
