### ISSUE TITLE
Cyclic Sleeping Mat Causes Crash

### ISSUE THREAD

**Issue by WendyJaja** [FTBTeam/FTB-Modpack-Issues#3411]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Every time me or my partner try to use the sleeping mat the game crashes

### Steps to reproduce

Just try to put down the sleeping mat

### Expected behaviour

I hope it can be fixed

### Screenshots

![Sleeping mat crash message](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/134278732/93e045de-4e5e-485a-a127-919dacabf973)

**Comment by ukmcplyr** [comment]
There's an issue open for this over at #2924

**Comment by Saereth** [comment]
removed in new version
