### ISSUE TITLE
[Lote] Add Applied Energistics 2 Wireless Terminals mod

### ISSUE THREAD

**Issue by Nightw4re** [FTBTeam/FTB-Modpack-Issues#3412]
### Modpack

FTB Legend of the Eyes

### Is your suggestion related to a problem? Please describe.

Amazing mod pack! I just miss the extra AE2 WT ... is any chance to add it or was it incompatible? It looks the AE2 is better for usa and mainly for store items, but it has distance and dimension limitations, which this missing mod removed.

### Mod suggestion

https://modrinth.com/mod/applied-energistics-2-wireless-terminals

**Comment by DinnerBeef** [comment]
Thank you for your suggestion, but at this time will not be adding this mod to the Modpack
