### ISSUE TITLE
Crash with IronFurnaces and "Redstone Comparator" mode

### ISSUE THREAD

**Issue by dkowis** [FTBTeam/FTB-Modpack-Issues#3413]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.0

### Log Files

[crash-2023-05-22_20.17.54-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11536918/crash-2023-05-22_20.17.54-server.txt)

### Describe the bug

Class Not Found Exception when hitting on the "redstone comparator" option in an @IronFurnace furnace.

### Steps to reproduce

1. Create an Iron Furnace (mine was Netherite)
2. Put it somewhere
3. Open it's display
4. Push the redstone comparator button (I don't even know what it does other than crash the server!)

### Expected behaviour

No crashes

**Comment by UnRealDinnerbone** [comment]
Same as #3166
