### ISSUE TITLE
World Crashing with Ticking Block Entity

### ISSUE THREAD

**Issue by ixanza** [FTBTeam/FTB-Modpack-Issues#3418]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Log Files

https://pastebin.com/WAGE32DV

### Describe the bug

After setting up my crop area with pedestals I was messing with my sifters and when I shift scrolled through the infinity wand I got this crash. Strangely enough the crash just mentions pedestals. Reloading the world produces a crash again and again

### Steps to reproduce

I don't think this is reproduceable on a fresh world

### Expected behaviour

Game no crash?

**Comment by Mowmaster** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10681506/77b9b1a4-8936-4f90-9781-696504e8cdb6)

**Comment by Mowmaster** [comment]
needed more info for debugging this^

**Comment by Bauws** [comment]
Until its fixed you need to find a way to get rid of this block.

Details:
	Name: pedestals:block_entity_pedestal // com.mowmaster.pedestals.Blocks.Pedestal.BasePedestalBlockEntity
	Block: Block{pedestals:block_pedestal}[color_blue=2,color_green=2,color_red=2,facing=up,filter_status=0,lit=false,waterlogged=false]

Either some sort of blockzap or if it is still a thing MCEdit or NBT Explorer. 

Otherwise you gotta wait for a fix sadly #:/

**Comment by ixanza** [comment]
> Until its fixed you need to find a way to get rid of this block.
> 
> Details: Name: pedestals:block_entity_pedestal // com.mowmaster.pedestals.Blocks.Pedestal.BasePedestalBlockEntity Block: Block{pedestals:block_pedestal}[color_blue=2,color_green=2,color_red=2,facing=up,filter_status=0,lit=false,waterlogged=false]
> 
> Either some sort of blockzap or if it is still a thing MCEdit or NBT Explorer.
> 
> Otherwise you gotta wait for a fix sadly #:/

I reverted to a backup which was 15 mins prior then removed the crop farm for now.

**Comment by Mowmaster** [comment]
Fixed version of pedestals is out,
also fixes the bug where blocks like bamboo/cane/cactus/kelp were not being harvested
https://github.com/Mowmaster/Pedestals/commit/766ff43f14befa2ea88d52cddc11d6801f091827
https://legacy.curseforge.com/minecraft/mc-mods/pedestals/files/4550637
