### ISSUE TITLE
[Bug,QuantumStorage]: Quantum Storage Crates Dupe bug

### ISSUE THREAD

**Issue by Ghost-Asood** [FTBTeam/FTB-Modpack-Issues#342]
### Modpack

DireWolf20 1.16

### Modpack version

1.11.0

### Describe the bug

(on server)
place a Iron / Gold / Diamond Storage crate from Quantum Storage mod, put some items in it, get a friend to help you, now you open the crate and keep it opened and tell your friend to break it while you are using the inventory, he'll break the crate and pick it up while you are still in the inventory, which'll let you get the items from the inventory without the actual crate losing its items, can be repeated infinitely.  

### Steps to reproduce

1 - Place Iron / Gold / Diamond Storage crate from QuantumStorage
2 - Put some items in the crate and keep the inventory opened
3 - tell your friend to break the crate
4 - Pickup the items before you close the inventory
6 - you now have twice as you had in that crate now, replace the crate and do the same to get more items!!

### Expected behaviour

I expected the inventory to close as he breaks the crate.

### Screenshots

here's a video (stolen from my teammate xD):
https://medal.tv/games/minecraft/clips/71333759/d1337IsMNTNl?invite=cr-MSxvMUssNTMxNzU4Myw

**Comment by Raidobw2** [comment]
This is reported at gigabit101/QuantumStorage#239, we'll be waiting on and update from the mod
