### ISSUE TITLE
[Bug] Stuck in Lobby Dimension. Teleporting to Island Crashes Game.

### ISSUE THREAD

**Issue by ThtGuyMichael** [FTBTeam/FTB-Modpack-Issues#3423]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Log Files

[crash-2023-05-23_19.36.17-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11549906/crash-2023-05-23_19.36.17-client.txt)

### Describe the bug

When I open the game, I keep appearing in the lobby dimension. The portal doesn't work to teleport me to my island. When I try various methods of teleportation (Ender Book, Waypoints, Commands, etc.) my game crashes.

### Steps to reproduce

1. Open game
2. Try to use the teleport portal
3. If unsuccessful, try other methods of teleportation

### Expected behaviour

Teleport to island

**Comment by Bauws** [comment]
Hey @ThtGuyMichael,

can you provide a crash log please? You can find it in ur minecraft folder. We can't help you without it.

**Comment by ThtGuyMichael** [comment]
I believe I already attached the .txt file. Is that what you’re looking for?

**Comment by ThtGuyMichael** [comment]
ISSUE RESOLVED: The solution here was to rebuild the FTB Team Dimension entry in my level.dat file. I created a new world and copied the structure of the dimension entry from that level.dat file. Make sure to copy the dimension id from the ftbteamdimensions_dimension_store.dat file.
