### ISSUE TITLE
Void Speed Run Challenge had been defeated

### ISSUE THREAD

**Issue by imotori481** [FTBTeam/FTB-Modpack-Issues#3424]
### Modpack

FTB Interactions

### Is your suggestion related to a problem? Please describe.

The record for Void Speedrun has been updated from 27m59s to 27m47s, please change the quest link to the following video.

Player: imotori481
https://youtu.be/v8BPGsv7jHg

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

We may have something up our sleeves, some may call it a remaster, keep an eye out on our social media platforms for more information.
