### ISSUE TITLE
Invisible Mobs and dropped items etc.

### ISSUE THREAD

**Issue by Kularhi** [FTBTeam/FTB-Modpack-Issues#3425]
### Modpack

FTB Academy 1.16

### Modpack version

1.4

### Describe the bug

Mobs, held items and dropped items are invisible. Can still interact with them.

### Steps to reproduce

1. load game
2. play

### Expected behaviour

To see things, makes playing difficult

**Comment by JaydeStarr** [comment]
I'm having this issue too.

**Comment by Gaz492** [comment]
If you are still experiencing this issue, would you be able to upload your logs so we can have a look at them?
https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
