### ISSUE TITLE
Cannot complete Mob Farming quest line

### ISSUE THREAD

**Issue by Mejval5** [FTBTeam/FTB-Modpack-Issues#3426]
### Modpack

FTB Skies

### Modpack version

1.1.0

### Describe the bug

I finished all quest everywhere, but this one chapter is still not completed :/

### Steps to reproduce

1. Complete "Mob Masher" quest before "Iron Spikes" quest
2. Complete "Iron Spikes" quest
3. Complete rest of the quests

### Expected behaviour

The quest line should complete

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/771c817f-e68e-478d-93a1-5e114901980d)

**Comment by Mejval5** [comment]
Actually it looks like the Mob Masher Upgrade is stuck. I can't fix it even when removing and adding the item into my inventory. Closing the inventory with the item. Etc...
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/f1cd0dc0-60a0-49c7-8643-a052f0d71055)

**Comment by Mejval5** [comment]
Okay so there is one secret quest (The only in the whole pack). I had to look into the quest config file to find it.
I had to make Saw Upgrade Looting
Is this really intentended?
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48858230/e8adf986-c29c-4c8f-a79a-b48838b1a9d7)

**Comment by Saereth** [comment]
no its not, marked it not hidden for next update, ty for the report
