### ISSUE TITLE
KubeJS Crash

### ISSUE THREAD

**Issue by UnRealDinnerbone** [FTBTeam/FTB-Modpack-Issues#3427]
Hello! I have the same issue, have a look:

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/81705259/bb301a0f-a126-4410-80fd-5413b7e6731d)

[startup.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11564629/startup.txt)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11564630/latest.log)
[crash-2023-05-25_15.02.53-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11564638/crash-2023-05-25_15.02.53-fml.txt)

_Originally posted by @Tyrthurey in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3415#issuecomment-1562803746_

**Comment by UnRealDinnerbone** [comment]
Both KubeJS issues but for different packs and different errors

**Comment by Saereth** [comment]
your installation is all messed up, wrong mod versions, wrong scripts. Definitely reinstall fresh
