### ISSUE TITLE
Add a questline for getting ice 

### ISSUE THREAD

**Issue by ixanza** [FTBTeam/FTB-Modpack-Issues#3428]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

Getting ice in a regular non cold biome is quite a task.
I spawned in an ocean biome and had to use weird tricks involving the AE entropy manipulator to chill water into ice, pure daisy for ice into packed ice to make a blast chiller.

The other method is water to snow with pure daisies, snow to ice in the alchemical catalyst then ice to packed ice with pure daisies.

Once you have the blast chiller it's pretty easy. 

Maybe a questline in getting started, botania or thermal could mention ice generation outside of cold biomes

**Comment by Saereth** [comment]
You can also just goto a cold biome and let water freeze :p There are 3-4 different methods. I'll tag this as an enhancement to add later
