### ISSUE TITLE
Firework Star Recipe is missing

### ISSUE THREAD

**Issue by ccbmeyer** [FTBTeam/FTB-Modpack-Issues#3429]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.11.0

### Describe the bug

Trying to create the Ars Nouveau AOE Glyph and need the Firework star.  The Firework star display in the JEI, but no corresponding recipe. and putting the items in the crafting table also does not create the Firework star

### Steps to reproduce

1. Go to Crafting table
2. Type Firework Star in the JEI
3. Click on it
4. Nothing is display in the crafting recipe.
(PS: I am using Refined Storage to keep and build, and have just a RS Crafting Grid.

### Expected behaviour

The Recipe to be shown and the materials taken from Refined storage

**Comment by ukmcplyr** [comment]
Recipes for firework stars not being visible in the usual way is a long-standing JEI issue, iirc. mezz/JustEnoughItems#91 and some of the referenced issues therein has a bit more on the topic.

More helpfully, they should still be craftable using the recipes [here](https://minecraft.fandom.com/wiki/Firework_Star) and Ars should accept any of the variants.
