### ISSUE TITLE
Cant join my server

### ISSUE THREAD

**Issue by TheGamerDK2009** [FTBTeam/FTB-Modpack-Issues#3430]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.12.2

### Describe the bug

Cant join my server when i am logged in but it says that im offline

### Steps to reproduce

1. go to multiplayer
2. in the top right corner there is a Oauth Login button
3. press on the button and chose microsoft account
![Skærmbillede 2023-05-26 144834](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/134708007/afb5a7a6-21fd-4fe9-bfb6-09151ad62e25)

### Expected behaviour

i wanted to join my server

**Comment by Gaz492** [comment]
Try removing/disabling the oauth mod on your client and checking if the issue still happens.
