### ISSUE TITLE
Broken link to external Boiler Fuel Chart

### ISSUE THREAD

**Issue by TheMingo888** [FTBTeam/FTB-Modpack-Issues#3431]
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Describe the bug

The quest "Boiler Fuel Chart for FTB Interactions" links to a [Google Docs spreadsheet](https://docs.google.com/spreadsheets/d/1GMIWZtxvebEXCOZilsOwPJbh1aHzD9Ia6FUU7pQz1FM/edit) that has since been deleted.

### Steps to reproduce

1. Open the quest book and go to "How do we power this party ?" > "Boiler Fuel Chart for FTB Interactions"
2. Visit the linked website

### Expected behaviour

The file should not be deleted

### Additional information

Even if it is not practicable to patch the modpack at this point, I am very interested in seeing a copy of this spreadsheet if someone can provide it here. I haven't been able to find any relevant and concrete information on boiler fuel consumption and production.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

We may have something up our sleeves, some may call it a remaster, keep an eye out on our social media platforms for more information.
