### ISSUE TITLE
automating casting seared stone fails

### ISSUE THREAD

**Issue by Skulgren** [FTBTeam/FTB-Modpack-Issues#3432]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.0

### Describe the bug

Attempting to cast seared stone via molten clay in a Tinker's smeltery over stone fails when using some form of automation. It appears that priority is given to the drain over any means of inputting the stone into the basin, resulting in terracotta being produced instead of seared stone. This has been tested with hoppers and with item pipes from Pipez mod (both with and without speed upgrades).

### Steps to reproduce

basic test setup:
1. have a Tinkers smeltery with molten clay, with seared drain & faucet for output into a casting basin, with hopper under casting basin for item output.
2. adjacent to casting basin set up storage for stone with input (hopper or pipe usage leads to same result) into casting basin from the side.
3. use lever to power the faucet to begin casting
4. after first seared stone produced (created by stone already going into basin) future casts will fail to produce stone as molten clay is input before stone

### Expected behaviour

priority given to item input to casting basins over liquid ingredient

**Comment by UnRealDinnerbone** [comment]
This is more of an automation issue than a pack issue. In order for automation, you need to make sure the stone goes in before the liquid starts (redstone should be able to do something)
