### ISSUE TITLE
Refined Storage Covers

### ISSUE THREAD

**Issue by Dukasho** [FTBTeam/FTB-Modpack-Issues#3435]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.11

### Describe the bug

The covers for Refined Storage, the texture is a different level of zoom/resolution than original block.

### Steps to reproduce

Place cable, place cover, place matching block next to cover

### Expected behaviour

Cover should look like original block

### Screenshots

![2023-05-27_09 14 33](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/133019443/5f5ee408-20b6-4ba1-8141-7d952ee90176)

**Comment by UnRealDinnerbone** [comment]
It looks like you have a texture pack on, does this happen if you turn the texture pack off?

**Comment by Saereth** [comment]
![2023-06-12_19 32 16](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/bcb80f3e-1d28-4225-a691-a2dcaf39c0d9)
As Unreal suggested, I cannot reproduce this with a standard texture pack. This does seem to be an issue with your texture pack and outside the scope of our support. You'll need to report it to the resource pack author to fix.
