### ISSUE TITLE
Crash when attempting to join a server (both a dedicated one and a shared world)

### ISSUE THREAD

**Issue by Lyrapuff** [FTBTeam/FTB-Modpack-Issues#3436]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Log Files

[crash-2023-05-27_19.06.53-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11582518/crash-2023-05-27_19.06.53-client.txt)

### Describe the bug

The game starts fine, creating a local world and playing alone works fine, but when I attempt joining a dedicated server or a shared world the game crashes.

### Steps to reproduce

1. Start the game
2. Start a dedicated server
3. Try joining it

### Expected behaviour

It works

**Comment by Lyrapuff** [comment]
Update: Disabling `ToastControl` on the server solved the issue.

**Comment by matefoldes** [comment]
I'm having the same issues. There is no "ToastControl" mod in my server folder. I tried to delete it from my client mods but the issue still persists.

**Comment by Lyrapuff** [comment]
@matefoldes sharing your crash report would be helpful too!

**Comment by Saereth** [comment]
added toastcontrol to client only mods

**Comment by matefoldes** [comment]
I had a mod for capes that caused the issue. After removing that and ToastControl mod it works flawlessly.
