### ISSUE TITLE
Trying to craft a Rocket in a 3x3-Grid crashes when copying recipe via JEI

### ISSUE THREAD

**Issue by Mithi83** [FTBTeam/FTB-Modpack-Issues#3438]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

I'm trying to craft the Tier 1 Rocket from Ad Astra. As I was distracted and not paying attention I tried to craft that recipe not in a NASA Workbench but rather via a 3x3 grid using my Ultimate Wireless Grid (Refined Storage). When trying to move the recipe from JEI the game crashes.

I'm not sure which mod is at fault here. Could be JEI that does not check if the recipe is suitable for the 3x3-Grid of a Wireless Universal Grid. The problem is probably that a NASA Workbench has more slots than the usual 3x3-Grid, thus accessing an array index out of bounds. Using the proper NASA Workbench the recipe is copied without any problem.

### Steps to reproduce

1. Prepare all materials for a Tier 1 Rocket from Ad Astra
2. Open Wireless Universal Grid (in crafting grid mode)
3. Search "Tier 1 Rocket" recipe in JEI
4. Ignore the fact that it says Nasa Workbench ;)
5. Click on the small plus button on the bottom right
6. Crashes with "Internal Exception: java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9"

### Expected behaviour

No crash and rather a comment that it requires a specific workstation rather than a typical

**Comment by MechBFP** [comment]
Similar to this. A problem with RS that they would need to fix. https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3346

**Comment by Saereth** [comment]
known issue with RS, have to wait for them to update, just dont use the + to move from JEI into RS crafting terminal for now
