### ISSUE TITLE
Dreadful Dirt/Delightful Dirt not spawning Mobs in latest version (1.7.0)

### ISSUE THREAD

**Issue by Furious1964** [FTBTeam/FTB-Modpack-Issues#3439]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.0

### Log Files

https://pastebin.com/DmhR12L0
https://pastebin.com/y3DVarw9
https://pastebin.com/KZEN20FV
https://pastebin.com/itAhe86s

### Describe the bug

When back to the game after play some FTB Slies and found that my Mob Farms, which use Dreadful/Delightful Dirt, no longer are spawning anything Waited 10 minutes and nothing spawned in TOTAL darkness.

### Steps to reproduce

1. Started Game.
2. Went to Mob Farms.
3. Nothing was spawning on the Dreadful or Delightful Dirt.
4. Downgraded Mod Pack to Version 1.6.1
5. Started Game and farms were working properly.

### Expected behaviour

I expected it to work properly.

### Screenshots

How it's supposed to work:
![2023-05-28_12 18 39](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2803725/4f8f7a3a-a9b9-4a12-921e-2bae65020240)

How it's working now:
![2023-05-28_12 32 42](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2803725/387f55f4-15e2-4ee7-80f7-c6a863635176)
![2023-05-28_12 33 15](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2803725/68ab4bee-4228-4dd6-a27e-a17a079bcaf3)

### Additional information

Downgrading the Mod Pack back to 1.6.1 fixes the issue.

**Comment by UnRealDinnerbone** [comment]
This is currently an issue with the way Torchmaster and MobGridingUtils interact, for now you have to remove your megatorch in order for them to spawn

**Comment by Addar** [comment]
Is there a way to locate the megatorchs easily? I thought I removed all of them but I'm still not getting spawns so I'm assuming I still have one behind a wall somewhere...

**Comment by UnRealDinnerbone** [comment]
This issue should be fixed
