### ISSUE TITLE
Can't do anything in my world after logging in

### ISSUE THREAD

**Issue by Trojminks** [FTBTeam/FTB-Modpack-Issues#3440]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

I was playing the modpack, then after closing the game I reopened it (because it didn't finish loading in the FTB Launcher and I killed the instance, I didn't fix it after restarting though, but the game was still playable) and after logging into my world I encountered several issues: I couldn't break blocks (they would break and a tick later they'd appeared)or place any blocks (they would appear and a tick later they'd disappeared), all my quests were reset (I still can complete them, however, the welcome quest can't be completed as it doesn't register me being in the overworld dimension, but I'm on my island), I couldn't open any chests and place or pick up water. However, mobs would spawn and function regularly and I could still take damage, die and respawn normally

### Steps to reproduce

No idea, other worlds work just fine

### Expected behaviour

Be able to open chests, break blocks, and continue questing line where I left off

**Comment by krusynth** [comment]
I'm having this same issue since upgrading to 1.2.1. Can't interact with chests, crafting tables, machines, etc. - when I look at them, they don't even show as a block in JEI.  Mobs appear for me but are stuck, not moving, in an animated state (chickens' wings flapping, etc.)

**Comment by krusynth** [comment]
I spent a few hours this morning poking at this further, and it's weirder than I thought.  I've tried reinstalling the pack clean, and then using my saved world, and that did not fix it. I tried reinstalling clean with an older version and using my saved world, and that also did not fix it.

What *did* work was starting an entirely new world. So I'm guessing my world file got corrupted while upgrading, and now it's unplayable. (Super-annoying given that I'm recording a Let's Play series, so I'll have to start over.)

@Trojminks try creating a new world and seeing if that works?

**Comment by Saereth** [comment]
please provide any logs you may have from the broken world so we can investigate, and if you're able to reproduce this the steps to do so.

**Comment by krusynth** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11929316/latest.log)
[kubejs client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11929318/client.txt)
[kubejs server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11929319/server.txt)
[kubejs startup.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11929320/startup.txt)
