### ISSUE TITLE
Game crashes on pause.

### ISSUE THREAD

**Issue by ewc33** [FTBTeam/FTB-Modpack-Issues#3441]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Log Files

https://pastebin.com/1sQkdzDp
https://pastebin.com/xDMcuGJt

### Describe the bug

I can load into my world just fine, but as soon as I try to tab out of the game or pause in any way the game stops responding. It doesn't even produce a crash log. I've experienced this in two different worlds as I restarted after encountering it the first time. I have reinstalled the modpack and tried different versions.

### Steps to reproduce

I don't know how you could reproduce this, but I had just gotten to the blaze burner tier of Create progression in both worlds if that helps.

### Expected behaviour

Not to crash.

**Comment by Saereth** [comment]
we need the crash log from crash-reports folder
