### ISSUE TITLE
StoneBlock 3 crahes on teleport (single, offline) but /home

### ISSUE THREAD

**Issue by MrsMormota** [FTBTeam/FTB-Modpack-Issues#3442]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.0

### Log Files

![ftbsb3crash23052902](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/134918316/cfe0d6d0-8524-4d75-a2b7-c85b29399d0a)

### Describe the bug

Dear Friends!
My man refreshed the Stoneblock 3 (SB3) 16 days ago. Since then whenever i would like to teleport from Overworld to Nether or to other places via waypoints or "/back" command the game crashes messaging "Saving world" and closes the modpack and the FTB App too. The only teleport command working well is "/home". I can travel from A to B and versus by walking but i cannot teleport. Restarting the App messages the list i linked here above. Waiting a pair of minutes and restarting the App i can restart the modpack, it loads well and i can reload the map, my character has teleported to the B.
I load the game connecting the Internet then i shut down the internet and load in the map offline.
This worked well before the last refresh. It generates the bug since the last refresh. There is a "Beta" label on the up left corner of the modpack's icon in the FTB App.
Is there any way to teleport from A to B without crashes and reloads, please? I would like to play offline.

### Steps to reproduce

1. Refresh the Stoneblock 3 to 1.7.0 (Beta?!?)
2. Load the SB3 connected to Internet
3. Load in the map offline
4. Get the journey map and choose any waypoint on the list then right click it and Teleport
5. facepalm as you see the "Saving world" message and closing modpack and App
6. In real go to have some coffee (or wait a quarter hour or so - having coffee is much better i think)
7. reload the App
8. reload the SB3 online
9. reload the map offline
10. see your character teleported to the chosen place!
11. See working the "/home" command but dont try the "/back" since it drives crashing the world.

### Expected behaviour

I would like to teleport from A to B without crashing, as it was before the refresing.

### Additional information

The Minecraft window size is preset by 1920*1080
"Java version" field contents "Recommended" text, "Arguments" contains "-Xmx1G"
Instance memory is 9.44 GB
Here at the top of App is a light blue label writed "Running beta version" - i dont remember seeing the "Beta" label when my man refreshed the modpack. He usually doesnt refresh my games to Beta nor Alpha but Release. He is an excellent Beta-tester but i am a bit histerical seeing a game crashes.

**Comment by shank3001** [comment]
I am getting the same issue and I am on a server.

**Comment by Dragonslayer9841** [comment]
Same issue

**Comment by UnRealDinnerbone** [comment]
Is someone able to upload a crash report for this issue?

**Comment by MrsMormota** [comment]
> Is someone able to upload a crash report for this issue?
There are not any failure messages but the words "Saving world" asif i'd have cliked the "Saving world and exit" button in the Pause menu but i didnt.
i cant copy from the FTB App's window anything since cannot mark the text there before crashing. And when the the game crashes then the App crashes too so i cannot see anything about the crash.
I found only some debug_n.log.gz files. I send the fourth of them saved as debug-4_230529_091400.log where the 230529 is the day of the crash (2023. május 29.) and the 091400 is the cca. timestamp of the debug file. There are 3 debug files on 29th of May.
[debug-4_230529_091400.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11616404/debug-4_230529_091400.log)

**Comment by eccles714** [comment]
[crash-2023-06-05_23.41.39-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11659981/crash-2023-06-05_23.41.39-client.txt)

**Comment by eccles714** [comment]
Above is my most recent crash report from trying to teleport from my base at the center to my death marker waypoint. I don't think the waypoint matters. It also crashes the same way if I try to teleport via commands by entering coordinates. When I reload the game, I have successfully teleported and I can instantly teleport with /home like it's nothing. But if I try to teleport back via waypoint or command, even seconds later, it always crashes

**Comment by UnRealDinnerbone** [comment]
This issue should be fixed in the next stoneblock 3 update

**Comment by UnRealDinnerbone** [comment]
Update Released

**Comment by MrsMormota** [comment]
Thank you very much, unRealDinnerbone, it works well!
