### ISSUE TITLE
FTB University 1.16 - Prefab Bulldozer can't be powered

### ISSUE THREAD

**Issue by MoonliteDelight** [FTBTeam/FTB-Modpack-Issues#3447]
### Modpack

FTB University 1.16

### Modpack version

1.8.0

### Describe the bug

The Prefab Bulldozer item does not work on its own -- it needs to be combined with Triple Compressed Stone in an anvil to actually do something. This is not the bug, this is just part of the mod. The hover text of the item even explains this. 

But FTB University 1.16 has the Prefab triple compressed stone disabled and the Compressium 3x and 2x stone versions don't work to activate the bulldozer. This makes the Prefab useless. 

### Steps to reproduce

1. Get a bulldozer prefab.
2. Put it in an anvil with triple compressed stone (Compressium)
3. Tada, it does nothing

### Expected behaviour

The Bulldozer is supposed to get an enchantment glow and the item's text is supposed to change to let the player know it's activated. 

### Additional information

The best solution is probably to either change the recipe to output an activated bulldozer, make the Compressium stone activate it, make the recipe output a creative bulldozer, or disable it by default in the config.

**Comment by Garueri** [comment]
what is even this bulldozer and what is does

**Comment by Grocel** [comment]
This is also relevant for FTB University 1.19. This is a recipe conflict with Compressium.

@Garueri https://github.com/Brian-Wuest/MC-Prefab/wiki/Bulldozer

It's a multi use prefab that clears a large area to make up space for builds.
