### ISSUE TITLE
SB3, weird KubeJS Behavior.

### ISSUE THREAD

**Issue by FooterMan15** [FTBTeam/FTB-Modpack-Issues#3448]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.0

### Log Files

No relevant information in the logs 🤷

### Describe the bug

Kinda just wondering what makes SB3 weird when working with KubeJS.
This is kind-of a pack modification question, so bear with me:

I've been trying to make a ClearLag script for a server hosting community with the pack, which is based around chat events. Problem is, the messages are never caught. The Timer I implemented works perfectly though.
I've tried this same script, and several different iterations of it on other packs, such as ATM7, ATM7S, and BetterMC, along with a small testing pack, and they all worked as expected. I checked for variable conflicts, and there were none. I checked for scripts or mods that might block chat events, nothing. So I have no idea what's going on here.

### Steps to reproduce

Install the pack.
Add the provided script to the server_scripts folder.
Load the game / Run /reload
The Timer should work, but the chat events don't work.

### Expected behaviour

Chat Events to be caught.

### Additional information

https://gist.github.com/FooterMan15/8227a238a333b9947196e6fd4d2dfd1c
ClearLag script ^

**Comment by UnRealDinnerbone** [comment]
Sorry, we do no provide support for modifications of packs
