### ISSUE TITLE
Duplication bug with many crafting recepies

### ISSUE THREAD

**Issue by EggRollForce** [FTBTeam/FTB-Modpack-Issues#3449]
### Modpack

FTB One

### Modpack version

2.7.0

### Describe the bug

When crafting pretty much anything in a crafting bench the output can be right clicked to get a full stack if only one of each input is used. Works in a standard craft bench and inventory crafting, does not happen in the "Craftbench on a Stick"

### Steps to reproduce

1. Fill a craft bench with redstone dust (one per slot grid for 9x total redstone)
2. Right click on output
3. Receive a stack of redstone blocks

### Expected behaviour

You should only get one block from this recepie with provided ingredients

**Comment by luckyaide** [comment]
Hi,
i can commit this in version 2.7.0. it's like cheating so no real survival playing possible..

**Comment by luckyaide** [comment]
Hello everyone, I don't want to be rude but does anyone care about this duplication bug? It pops up with normal normal mouse clicks as described above and is constantly triggered unintentionally. That's really no fun, please take a look and thank you in advance! -Lucky

**Comment by piedrrum** [comment]
I tested and it appeared from 2.3.0 to 2.4.0

**Comment by BlayTheNinth** [comment]
> I tested and it appeared from 2.3.0 to 2.4.0. It might be due to the add of "crafting tweaks". Its not really a fix but you can disabe this by turning to "false", the feature "rightClickCraftsStack" inside "craftingtweaks-common.toml" in config file folder. I hope this will be fixed in future versions of crafting tweaks also for 1.19...

I cannot reproduce this issue when running Crafting Tweaks by itself. Did you verify that disabling `rightClickCraftsStack` does indeed solve the issue?

**Comment by piedrrum** [comment]
I confirm that this is solving the issue. Thats also obviously remove the base feature of right click for this.
I tested to manually add crafting tweak 1.19.2-15.1.7 on 2.3.0 with rightClickCraftsStack true and there is no issue.
This means that the issue is due to some change from 2.3.0 to 2.4.0.

**Comment by piedrrum** [comment]
I ran dichotomy update 2.3.0 to 2.4.0 with adding crafting tweak everytime and I found that the issue is coming from fastworkbench update. So FastWorkbench-1.19.2-7.1.0  is causing issue with crafting tweak whereas FastWorkbench-1.19.2-7.0.1 was not.

**Comment by piedrrum** [comment]
I reproduced out of the modpack:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/60243235/a85509aa-37ea-48b9-bc50-e752f746e9f0)

**Comment by piedrrum** [comment]
I tested again with a Fastworkbench update ==> FastWorkbench-1.19.2-7.1.4 and the bug disapeared.
