### ISSUE TITLE
[Bug]: Game crash when attempting to enchant a The One Probe helmet in an Industrial Foregoing Enchantment Applicator

### ISSUE THREAD

**Issue by Morotstomten** [FTBTeam/FTB-Modpack-Issues#345]
### Modpack

FTB Oceanblock

### Modpack version

1.8.0

### Log Files

[crash-2021-11-19_20.00.25-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7572129/crash-2021-11-19_20.00.25-server.txt)

### Describe the bug

Attempting to enchant a "Diamond Helmet with Probe" from "The One Probe" mod in the "Enchantment Applicator" from "Industrial Foregoing" mod causes the server/host to crash, reproducing the issue in a singpleplayer world ruined it, from a brief look at the 2 recent crash logs i assume the process that causes the crash is being resumed when the world is loaded and causes instant crash. The issue appears to concern any enchantment with said item, vanilla armor pieces work just fine so its likely a mod compatibility issue.

### Steps to reproduce

1. Set up an Enchantment Applicator from the mod Industrial Foregoing with Energy and Essence
2. Aquire both an Enchantment book of any type or at the very least Protection III, IV or Projectile Protection III and a Diamond Helmet with Probe
3. Insert said items into their appropriate slots in the machine

### Expected behaviour

Enchantment applied to mentioned item

### Additional information

i attempted this the first two times on a friends server using Protection IV enchantment and im fairly certain i crashed his server(hes been offline all day so i cant get confirmation on that at this moment), while reporting this issue i reproduced it in singleplayer, i used the enchantments protection III, IV and projectile protection III with Diamond Helmet with Probe and caused crash and broke the world, the enchantments can be aquired on said item through random enchanting using the Enchantment Factory machine from the same modpack, its only while trying to apply them using the Enchantment Applicator that causes the crash

**Comment by Sunekaer** [comment]
Duplicated of #109
