### ISSUE TITLE
Pedestals are unbreakable in creative mode

### ISSUE THREAD

**Issue by CurtisT15** [FTBTeam/FTB-Modpack-Issues#3450]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Was doing some testing with the pedestals mod in creative mode, and found it was impossible to break by punching it. Even when using items/tools in hand, the only ways to remove pedestals after placing are to either use the fill console command or to change my game mode to survival and break with a pickaxe. 

### Steps to reproduce

Start world in creative/ Change game mode to creative.
Place pedestal from pedestals mod. 
It is unremovable without the use of commands.

### Expected behaviour

Expected pedestal to be removable via punching.

**Comment by Saereth** [comment]
not a bug, this is by the mod creator's design.
