### ISSUE TITLE
Occultism crusher spirits outputting barrier blocks on server

### ISSUE THREAD

**Issue by bracken453** [FTBTeam/FTB-Modpack-Issues#3451]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.11.0

### Describe the bug

On a default direwolf20 1.19 server crusher spirits will drop barrier blocks when crushing specific ores
The affected ores seems to be 
- Iron (Raw/Ingot)
- Copper (Raw/Ingot)
- Iesnium (Ore Block)
I have been able to confirm this on both Foliot and Djinni crushers but I imagine it also happens on Afrit and Marid as well
It seems to work as expected in single player worlds but not in servers
The server that I encountered this on is using the server provided on the FTB website
If the crusher spirit runs out of the original ore it will pick up the barrier blocks and crush them into either quartz or diamond dust

### Steps to reproduce

1. Summon Foliot or Djinni Crushers on a Server
2. Give them one of the affected ores
3. Wait for them to process the ore

### Expected behaviour

The Appropriate dust is dropped rather than a barrier block

**Comment by Saereth** [comment]
This should be resolved now in the 1.12 update, occultism update resolved it.

**Comment by Dns-q** [comment]
This is still happening in 1.12.0
