### ISSUE TITLE
My quest and questlines disappeared

### ISSUE THREAD

**Issue by MrBlackSks** [FTBTeam/FTB-Modpack-Issues#3453]
### Modpack

FTB StoneBlock 3

### Modpack version

1.18.2

### Describe the bug

My quest and questlines disappeared and i cant completed them try adding them by cheats but no answers.

### Steps to reproduce

1. Launch Modpack
2.  Start world
3. all quest gone

### Expected behaviour

I thought i could fix it

### Screenshots

![Snímka obrazovky 2023-06-01 092755](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/135208211/79fb004b-dd5b-4154-bc7e-758064716c3d)

**Comment by UnRealDinnerbone** [comment]
Looks like you are in the lobby world, did you create and island before you started playing the pack?

**Comment by MonkeyTonk** [comment]
Hey there! I have the same problem. Not sure, if claiming chunks had something to do with it.
What do you mean by "lobby world"? I am playing alone on a single player world.
