### ISSUE TITLE
Brass Essence has no crafts

### ISSUE THREAD

**Issue by Pixpo** [FTBTeam/FTB-Modpack-Issues#3454]
### Modpack

FTB OceanBlock

### Modpack version

1.15.1

### Describe the bug

Brass Essence from Mystical Agriculture has no crafts added, you got the essence for nothing to craft

### Steps to reproduce

1. Get Brass Essence
2. Try to craft something or press "u" to view crafts

### Expected behaviour

Add brass to the modpack

**Comment by DinnerBeef** [comment]
Thanks for reporting. However, there is no use for brass in this modpack. So Brass Essence / Seeds will be hidden in the next update.

**Comment by manmaed** [comment]
This issue is stale and pack is no longer being worked on
