### ISSUE TITLE
Compact Machines 4 - Item Tunnel uncraftable

### ISSUE THREAD

**Issue by DroggeIbecher** [FTBTeam/FTB-Modpack-Issues#3455]
### Modpack

FTB OceanBlock

### Modpack version

1.15.1

### Describe the bug

I am unable to use the mod Compact Machines 4 due to the inability to craft the item tunnels ( compactmachines:tunnel )

### Steps to reproduce

1. open Inventory
2. Search "Item Tunnel"
3. Hover over and press "R" ( show recipe ) OR click on it
4. *does nothing*

### Expected behaviour

Shows me a recipe

**Comment by DinnerBeef** [comment]
Tunnel don't exist in Compact Machines 4. Will have to use another way to get stuff you want in an out. "Ender Chests, Ender Tanks, Tesseracts" are all good items to use.
