### ISSUE TITLE
Crash during backup

### ISSUE THREAD

**Issue by uhthomas** [FTBTeam/FTB-Modpack-Issues#3456]
### Modpack

FTB Skies

### Modpack version

6477

### Log Files

https://gist.github.com/uhthomas/2c0d8eb24d14d83178e85601c9b8d89b

### Describe the bug

This is a brand new server, so it shouldn't be due to the world size or anything. It seems that every half an hour or so the server will crash when during a backup.

### Steps to reproduce

Run the Docker image `itzg/minecraft-server:2023.3.0` with these environment variables:

```cue
env: [{
  name:  "EULA"
  value: "TRUE"
}, {
  name: "TYPE"
  value: "FTBA"
}, {
  name: "FTB_MODPACK_ID"
  value: "102"
}, {
  name: "FTB_MODPACK_VERSION_ID"
  value: "6477"
}, {
  name: "MEMORY"
  value: ""
}, {
  name: "JVM_XX_OPTS"
  value: "-XX:MaxRAMPercentage=75"
}]
```

### Expected behaviour

It shouldn't crash

### Additional information

https://github.com/uhthomas/automata/blob/edeeed0323f64ab9fa630a81beb50ec67aef13f2/k8s/unwind/minecraft/ftb_102/stateful_set_list.cue#L27-L55

**Comment by Saereth** [comment]
backups update in 1.3.0 coming out should address this
