### ISSUE TITLE
MineColonies Miner request loops

### ISSUE THREAD

**Issue by DamondSword2247** [FTBTeam/FTB-Modpack-Issues#3459]
### Modpack

FTB Inferno

### Modpack version

1.9.1

### Log Files

Not sure if these will be of any use but they are there if needed.

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11634940/console.log)

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11634941/debug.log)

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11634942/latest.log)

[crafttweaker.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11634943/crafttweaker.log)

### Describe the bug

The miner gets stuck in a requesting loop when requesting netherrack preventing the miner from doing their job.

### Steps to reproduce

Step 1: Build a courier.
Step 2: Build a mine.
Step 3: Wait for miner to dig down.
Step 4: Miner requests netherrack.
Step 5: Courier delivers netherrack.
Step 6: Miner gets stuck on netherrack and it gets sent back to the warehouse.
Step 7: Miner requests netherrack.
Step 8: Courier delivers netherrack.
Step 9: Miner gets stuck on netherrack and it gets sent back to the warehouse.
Step 10: Miner requests netherrack.
Step 11: Courier delivers netherrack.
Step 12: Repeats steps 4-11 till the heat death of the universe.

### Expected behaviour

The miner does its damn job and stops trading netherrack with the courier like it's a never ending game of hot potato.

### Additional information

Creating a custom mod pack with just Mine Colonies and its dependencies did not have this looping issue.

I had even tried updating mine colonies to minecolonies-1.18.2-1.0.1434-ALPHA to see if that would fix the issue but reverted back to minecolonies-1.18.2-1.0.1396-ALPHA after updating to the aforementioned version didn't fix the problem.

**Comment by Darksilver78** [comment]
Easy fix for this, set a minimum quantity on the miner hut, making sure it's minecraft netherrack, not occultism

**Comment by denbykov** [comment]
I faced the same issue, and it looks like I found a workaround to solve it. Try to disable pickup for this miner and fill all the inventories(racks, inventory of the building and miner's inventory) with netherrack. I hope it can help somebody.

**Comment by denbykov** [comment]
Well, I faced the same issue again, and it turns out that Occultism has its version of the netherrack, that is displayed first in the search, and I configured miner to use it as a filling material. It looks like choosing the netherrack from Minecraft is a fix.
