### ISSUE TITLE
No more woodland mansions?

### ISSUE THREAD

**Issue by zedstas** [FTBTeam/FTB-Modpack-Issues#3460]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.7.0

### Describe the bug

It seems Woodland Mansions don't exist in this version? 
According to the quest book, the Rogue Eye is to be found in a Woodland Mansion.
I converted 3 villagers to Cartographers, and all three sold Adventure and Lost Castle maps, but neither of the Explorer maps. 
I went to the Deep Dark for shards to create the recovery compass to trade for the explorer's compass. Searched in three areas for "Mansions" and it was not found in 10000 blocks. 

Is the Rogue Eye no longer possible in this Modpack? 

### Steps to reproduce

Read Quest book regarding the Rogue Eye. 
Craft a cartography table and level up a Cartographer; 
attempt to buy an explorer's map. Note it does not sell Explorer maps.
Craft Explorer's Compass. 
Attempt to find Mansions, states Not Found. 

### Expected behaviour

I expected there to be a way to find a Woodland Mansion. 

### Screenshots

It seems Woodland Mansions don't exist in this version? 
According to the quest book, the Rogue Eye is to be found in a Woodland Mansion.
![2023-06-02_18 23 34](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/115383600/c94665c0-3e00-4fa2-9b73-1a7556dc2fc5)
I converted 3 villagers to Cartographers, and all three sold Adventure and Lost Castle maps, but neither of the Explorer maps. 
![2023-06-02_18 23 08](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/115383600/d41bf240-daea-4e1a-82c8-08f200b4944b)
I went to the Deep Dark for shards to create the recovery compass to trade for the explorer's compass. Searched in three areas for "Mansions" and it was not found in 10000 blocks. 
![2023-06-02_18 22 33](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/115383600/bf8a7d1b-47fd-46d9-8941-2f56d12f71c7)

Is the Rogue Eye no longer possible in this Modpack?

**Comment by TheonlyTazz** [comment]
probably a very very unlucky situation in that regard of worldgen
i tested multiple worlds and all seemed to have a woodland mansion map
![grafik](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/3908847/e87977e2-a174-47a9-897c-be86481bf491)
