### ISSUE TITLE
Experience Obelisk Crash

### ISSUE THREAD

**Issue by nweilbrenner** [FTBTeam/FTB-Modpack-Issues#3461]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.0

### Log Files

[crash-2023-05-19_20.35.17-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11639979/crash-2023-05-19_20.35.17-client.txt)

### Describe the bug

While tping long distances. the experience obelisk causes me to crash. Has to do with chunk loading and XP being added or removed to the obelisk. I do have the chunks force loaded I assume that's the problem, but it shouldn't act like that.

### Steps to reproduce

1. Place an experience obelisk next to a force chunk loaded mob farm, leave the farm on and running.
2. Tp using RF Tools Matter transmitter/reciever for example to one of the dungeons from your base.
3 Game should crash. 

### Expected behaviour

A teleport with no crashes

**Comment by UnRealDinnerbone** [comment]
Same as #3354
