### ISSUE TITLE
Villager trades not refreshing in Easy Villagers' Trader block.

### ISSUE THREAD

**Issue by TheLoneDude** [FTBTeam/FTB-Modpack-Issues#3462]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Placing a villager into an Easy Villagers' trader block causes their trades not to refresh.

### Steps to reproduce

1. Gather a villager with a profession into a Easy Villagers' trader block.
2. Exhaust one of their trades.
3. Wait a day or more in-game, and return to the Trader. 
4. Check the previously exhausted trade.

### Expected behaviour

Villager trades should refresh after some time.

### Screenshots

![Screenshot (188)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/86646904/6d9bd38f-9a6d-452f-99c1-4b076ea6689e)

**Comment by TheLoneDude** [comment]
Never mind! I forgot you have to add their workstation block to the Trader. My bad!

**Comment by Saereth** [comment]
yep, you got it!
