### ISSUE TITLE
Gilded Pearl Recipe Conflict

### ISSUE THREAD

**Issue by Furious1964** [FTBTeam/FTB-Modpack-Issues#3463]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Can't craft the Gilded Pearls from Unusual End as the recipe is locked to crafting Ender Modems!

### Steps to reproduce

1. Place Eye of Ender surrounded by Gold Ingots in a Crafting Table.
2. Recipe shows Ender Modem when it SHOULD be Gilded Pearls.

### Expected behaviour

I expected it to work properly.

### Screenshots

![2023-06-03_11 24 48](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2803725/21edf75a-2135-4062-aa63-223cea9d6f90)
![2023-06-03_11 25 39](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2803725/4ffacd6c-5d36-473e-a775-c2cbd46c1e0f)

**Comment by manmaed** [comment]
Fixed in 1.3.0
