### ISSUE TITLE
Game started crashing after few seconds in the game

### ISSUE THREAD

**Issue by Nycard** [FTBTeam/FTB-Modpack-Issues#3464]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Log Files

[crash-2023-06-03_23.42.18-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11645078/crash-2023-06-03_23.42.18-server.txt)
[crash-2023-06-04_08.54.26-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11645079/crash-2023-06-04_08.54.26-server.txt)
[crash-2023-06-04_08.58.21-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11645080/crash-2023-06-04_08.58.21-server.txt)
[crash-2023-06-04_09.01.37-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11645081/crash-2023-06-04_09.01.37-server.txt)

### Describe the bug

Every time I start the world it will crash. First happend after I made crops farm using create mod, give or take half an hour after it was finished. That was last farm that I created.

### Steps to reproduce

1. Open game
2. Wait few sec
3. Try again

### Expected behaviour

playing the game

**Comment by Saereth** [comment]
shut down your server and edit your world/serverfconfigs/forge-server.toml and change the lines

	removeErroringBlockEntities = false
	removeErroringEntities = false

to both = true
restart and it should clear the erroring tile which seems to be a bug with hexerei plants specifically in your farm, I'd avoid farming those with create for now.
