### ISSUE TITLE
Didn't get the achievement

### ISSUE THREAD

**Issue by Kanominano** [FTBTeam/FTB-Modpack-Issues#3466]
### Modpack

FTB Infinity Evolved Skyblock

### Is your suggestion related to a problem? Please describe.

I didn't get the achievement for the Bound Blade.

### Mod suggestion

I wanted to ask what the command for the achievement is, it's important to mention that I play in single player and can use commands there.

/achivement give...

**Comment by nilskossmann** [comment]
Same Problem Pickel the sword up but did Not get the achievement or the trophy

on singleplayer i got both

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
