### ISSUE TITLE
Dimensions are kept loaded even if there are no players online

### ISSUE THREAD

**Issue by MohamdSaan** [FTBTeam/FTB-Modpack-Issues#3468]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Hello,

Dimensions of players and ad astra are kept loaded even if there are no players online. The dimensions do not have force loaded chunks and they do not have items that force load chunks. 

### Steps to reproduce

Play on skies server that has multiple people each with their own dims.
Ask one player to leave.
Profile using spark or observable.
Result will show that dimensions are actually loaded and ticking

### Expected behaviour

once a player leaves the server, the dimension should be unloaded

**Comment by Saereth** [comment]
dimensions just work this way now with forge, that is why there is a prune command to archive unused dimensions. The chunks in them should not remain loaded however unless you have that enabled for chunks in your server
