### ISSUE TITLE
Our Lobby Startship disappeared

### ISSUE THREAD

**Issue by PenguAUT** [FTBTeam/FTB-Modpack-Issues#3469]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Me and my 2 friends started yesterday, today another friend wanted to join but the ship in the lobby dimension wasnt there anymore. Just a completely empty dimension. I tried to restore the lobby dimension which didnt change anything. Is there a way to build a new portal?

### Steps to reproduce

since i dont even know how it happened i sadly cannot tell how to reproduce this

### Expected behaviour

-

**Comment by GalaxyBobissimo** [comment]
Just happened to me as well. Well second time maybe cuz it was sooner, a little bit of the boat remained but portal is gone

**Comment by Saereth** [comment]
try to figure out the step by step process to reproduce this is you can, would help us figure out where there may be an issue
