### ISSUE TITLE
Task Screen not accepting energy

### ISSUE THREAD

**Issue by LloydAZ** [FTBTeam/FTB-Modpack-Issues#3470]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

I am using the pitiful generator with a flux duct to try to pipe the energy into the task screen.  I've tried both right-clicking and shift-right-clicking the block and it just takes me to the true/false setup area.  I'm not seeing any of the quests that I need to select in order to turn in the 10K energy.

I also do not have anything in my off-hand.

### Steps to reproduce

1. place a pitiful generator
2. add coal to fill the generator
3. place the task screen two blocks in front of the generator
4. attach a flux duct between the two
5. right-click on the task screen or shift-right-click on the task screen

### Expected behaviour

Should open the selection menu to allow me to select the 10K energy task

**Comment by TheBread113** [comment]
That "True/False" screen is also the task selection screen. 

At the top of the list is a label that says "Task." It will highlight when hovered over. 

Click that then select the task. It should work then.

**Comment by LloydAZ** [comment]
That did it!  Thanks for helping.  This ticket can be closed now.
