### ISSUE TITLE
Industrial Foregoing Dry Rubber dupe

### ISSUE THREAD

**Issue by iTuroQQ** [FTBTeam/FTB-Modpack-Issues#3472]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

cyclic 3x3 crafter needs only 3 tiny dry rubber initially and then creates infinite dry rubber ( the combined one) 

### Steps to reproduce

1. Required Items: 3x Tiny Dry Rubber, Cyclic Crafting Machine, 
2. Put 3x Tiny Dry Rubber into the input side of the 3x3 Crafter
3. Set the correct 3x3 crafting recipe
4. set redstone to always on and supply with RF
5. 3x Tiny Dry Rubber gets increased to 12, crafting works
6. outputs Dry Rubber, input is reset to 3x tiny dry rubber
7. repeats
8. infinte rubber / plastic

### Expected behaviour

input gets used up

### Screenshots

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/135659377/bb33534e-ee24-4c91-90a8-937b837c316f

**Comment by Saereth** [comment]
crafter is removed in next update due to several dupes like this
