### ISSUE TITLE
Dreadful Dirt doesn´t work

### ISSUE THREAD

**Issue by dynamicgitter** [FTBTeam/FTB-Modpack-Issues#3474]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.1

### Describe the bug

Before the 1.7.1 Update, the Dreadful Dirt spawned a lot of mobs very fast, but now after the update nothing spawns anymore.

### Steps to reproduce

Place Dreadful Dirt and see if there spawn any mobs

### Expected behaviour

Mobs spawning on the dreadful dirt

**Comment by Code7737** [comment]
do you have any mega torches nearby? just upgraded the modpack and everything works fine.

**Comment by manmaed** [comment]
as Code said do you have any mega torches near by?

**Comment by swear01** [comment]
I encountered this problem and it works well after I break my mega torch.
However it works in previous version even when mega torch nearby.
I think this somewhat like a bug

**Comment by DinnerBeef** [comment]
Same issues as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3439
