### ISSUE TITLE
quark crashes pack launch

### ISSUE THREAD

**Issue by 420Mora** [FTBTeam/FTB-Modpack-Issues#3475]
### Modpack

FTB Skies

### Modpack version

1.1.0 - 1.2.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11678523/latest.log)

### Describe the bug

when ever a certain part of quark gets loaded the game stops launching, the instance itself is already there but not responding.
[Worker-ResourceReload-0/INFO] [quark/]: Dispatching Module Step TEXTURE_STITCH
[Worker-ResourceReload-0/INFO] [quark/]: Dispatching Module Step TEXTURE_STITCH
[Worker-ResourceReload-0/INFO] [quark/]: Dispatching Module Step TEXTURE_STITCH
this is the part where it stops, always the same 3 lines no matter how long i wait. had this problem before but solved itself after a few days. got and older laptop might be the reason. cant think of a certain block or so from quark that i used before this issue popped up

### Steps to reproduce

launch the game with a old/bad pc ig

### Expected behaviour

game launching, worked before, cant think of any triggers or so

### Screenshots

![Screenshot 2023-06-07 161314](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/122045817/e2e0b748-2a52-4ac3-aa07-bc899e3baa23)

**Comment by Saereth** [comment]
should be fixed in the update with new quark verison
