### ISSUE TITLE
Empty Mechanism Creative Energy Cell

### ISSUE THREAD

**Issue by IamStig** [FTBTeam/FTB-Modpack-Issues#3478]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

The Creative Energy Cube made available to players is useless..... it is empty with no way of putting power into it. JEI shows 2 creative Mekanism cubes ....1 that has energy in it and another that shows 0FE/Infinite .....the 0FE being the problem.

### Steps to reproduce

1 Get to the Creative Storage reward
2 Put the Creative Storage in the Refined Drive
3 Type Creative or @Mek Creative and locate the available Cube
4 Despair at the lack of any use for  this Creative item.

Note Creative FE is possible using the Create expansion Creative Generator. 

### Expected behaviour

A usable Creative energy cube

**Comment by Saereth** [comment]
this is not really something I can help, its just the way the creative item is implemented, there are several otherways to get creative power once you have that disk so this is not something we'll likely have a fix for

**Comment by IamStig** [comment]
Really? If I go into creative mod I am pretty sure I have the option of
choosing on empty creative cell or a full one.... I would have though the
same 2 options would be available for rewards.
