### ISSUE TITLE
[Bug]: Mystical Aggradations crux crops not automatable

### ISSUE THREAD

**Issue by thisismynombre** [FTBTeam/FTB-Modpack-Issues#348]
### Modpack

FTB Oceanblock

### Modpack version

1.8.0

### Describe the bug

Any Mystical Aggradations crop that requires a crux (e.g. nether star) lacks a way to automate.  The plant sower only seems to work if it is the block below the farmland, and the same is true for the crux.  The Phytogenic Insolator and Bottany Pots/Power Pots don't seem to be available for these either.

So, a user has to sit there and click the plant, because the Plant Gatherer will destroy the plant, and the sower can't be in place to replant the seed.  There aren't any mechanical users, so I don't believe there are any automation options.  You end up having to stand there to right click 27 times to make one nether star, which seems unintended.

### Steps to reproduce

1. Put down insanium farmland
3. Put nether crux below farmland
3. Plant Nether Star seed
4. Try to automate planting/sowing/gathering of essence from nether star plant

I tried multiple setups to automate this.  Sower/Plant Gather didn't work, the miner is left clicking, and there doesn't appear to be any blocks that simulate a player's right click.

### Expected behaviour

I would expect there to be a way to automate Mystical Aggregations plants, even if they require a crux.

### Screenshots

![image](https://user-images.githubusercontent.com/20806428/142705856-48b47936-819c-4e83-a678-e3f7cb085456.png)

**Comment by quietust** [comment]
These crops definitely worked in Botany Pots and Power Pots (where they do **not** require a Crux, just Insanium farmland) as of pack version 1.7.0 - maybe something changed in the last release?

**Comment by Raidobw2** [comment]
On OceanBlock 1.9.0 I don't seem to have that problem. You might want to backup your saves and reinstall the modpack.
Before reinstalling, you can clear the app cache in your instances folder by deleting the `.localCache` file if you're using the FTB App.
All those botany pots work fine.
![image](https://user-images.githubusercontent.com/17010632/142719432-a2377e46-b5ff-42bf-a9cd-59ce106f666f.png)

A tip for you, you can put upgrades in a plant sower to increase its range. This would automate it in your current setup.
![image](https://user-images.githubusercontent.com/17010632/142718790-8eac22f4-df32-4e6b-8edd-fc625065eb7d.png)

And there should definitely be the Mechanical Placer and Miner. With a little bit of ingeniosity you can even automate it in your current setup. Using a Sensor from RFTools to sense Growth for "Number: 100" for example and a little bit of wiring from Pipez. If you don't see those machines, I really recommend backing up saves and reinstalling.
![example_setup](https://user-images.githubusercontent.com/17010632/142719467-b8346f35-d68e-48e6-b599-4698f1695372.gif)
![image](https://user-images.githubusercontent.com/17010632/142719529-1caaf0f6-a385-4dca-86ee-ea0a1b19a605.png)
![image](https://user-images.githubusercontent.com/17010632/142719541-24e28771-be24-430e-8024-4ade9a031dcf.png)
I will be closing this as there does not seem to be an issue with botany pots (for the mentioned crops) in version 1.9.0 of the modpack. Reinstall after backup or use my suggestions above to automate it.
