### ISSUE TITLE
/back not working correctly 

### ISSUE THREAD

**Issue by Yousek** [FTBTeam/FTB-Modpack-Issues#3480]
### Modpack

FTB StoneBlock 3

### Modpack version

1,7,0

### Describe the bug

Yesterday i found out bug with /back command and i don't know do both ways cause it. If u type too fast /back after die (before loading screen tp to the spawn) it will crash the game. Same story if u blown by creeper (and probably the blocks around are destroyed). For sure at least one of those can crash the game :/ 

### Steps to reproduce

1.Die by creeper and/or type /back before death loading screen appear.
2. Loading screen should appear for a bit 
3. Congratulations! You should now send back to desktop

### Expected behaviour

Game should normaly tp to the spawn with locking death or loading screen

**Comment by manmaed** [comment]
Hay, thanks for the issue! Unfortunately it looks like you've not provided any `Log Files`... We require this as it helps us debug your issue as quickly as possible.

please provide the full latest.log, debug.log and the crash repot file
