### ISSUE TITLE
ME Storage Bus from Stoneblock 3 not craftable on Multiplayer Server

### ISSUE THREAD

**Issue by xxyifan96xx** [FTBTeam/FTB-Modpack-Issues#3482]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.1

### Describe the bug

Item "ME Storage Bus" from Modpack Applied Energistics is uncrafable. Apperently its only appearing on the Multiplayer server.

### Steps to reproduce

- Go to any Crafting Station
- Put the required items into the Crafting Grid
- No craftable item is shown / item is displayed but cannot be taken out from the crafting slot

### Expected behaviour

Item should be craftable in Multiplayer too.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/136028531/003f48f4-dc8d-4b52-b903-716af4707bad)

**Comment by SaphireLattice** [comment]
Any chance it's just the server forbidding this item (For... some reason. Probably either dupe or "concerns about lag")

Leaving an IP in there feels a bit like an ad though
