### ISSUE TITLE
Absorption Hopper stopped working in the nether

### ISSUE THREAD

**Issue by Dralex85** [FTBTeam/FTB-Modpack-Issues#3484]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

The absorption Hopper stopped working after being cloged.

### Steps to reproduce

I created a mob farm in the nether.
Mob's falls on mob mahser from Mob Grinding Utils, looting item and XP.
The absorption hopper is in front of the zone with 4 Radius Upgrade.
When I placed it filled up but I there was no Output connected so it clog.
After I connected XP and item storage, the hopper outputed everything where it belonged but don't do anything since then.

### Expected behaviour

Collect item and XP from the area.

### Additional information

I tried breaking it and replacing it in the same place, elsewhere in the nether and it didn't work either.
I put it in the overworld and recreate the same pattern and it worked perfectly

**Comment by Saereth** [comment]
I've tried to reproduce this but have been unable, after clogging and then breaking/replacing it starts working for me again.

**Comment by minepro3600** [comment]
Its weird I have the same issue but in another dimension
