### ISSUE TITLE
[Bug]: Refined Storage importer not pulling items from an adjacent chunk.

### ISSUE THREAD

**Issue by RedCitadel** [FTBTeam/FTB-Modpack-Issues#3486]
### Mod

Refined Storage / Refined Storage Addons

### Mod version

refinedstorage-1.11.6 / refinedstorageaddons-0.9.0

### Forge / Fabric version

ToolKit-forge-2.3.8-build.18+mc1.19.2.jar

### Modpack & version

Direwolf20 1.19 1.11.1

### What issue are you having?

I have a local host 1.19 Direwolf20 server setup for me and my girlfriend. Direwolf20 Version 1.11.1

I use a refined storage system in my main base in the overworld. I set up a network transmitter in my base and a network receiver in the End. While it is giving me full access to the storage system from the end, I cannot use an importer to move anything into the system if it comes from a chunk outside of the chunk the network receiver is placed in, I have made sure to chunk load all of the chunks with refined storage system components including all cables on both sides of this connection, following the warnings posted on the RS forum. This has not solved the issue. I chunk loaded using ftbchunks as well as using FluxNetworks to see if it was just an ftbchunks issue. 

As a side note: The network appears to lose this network connection upon reloading the server and has to be setup again to allow access to the storage system.
![db11dcc8b00326679399fcecbd59c8ea](https://github.com/FTBTeam/FTB-Mods-Issues/assets/136137761/5d1e4bb6-7d15-4fdd-85e9-8642c761c59e)

### Steps to reproduce

Setup a Refined storage system. Connect a network transmitter to the system and link it to a receiver in the end with chunkloaded chunks. Place an importer in a different chunk in the end, connect it to the receiver and attempt to have it pull an item from that importer to the receiver, it does nothing.

**Comment by Saereth** [comment]
This was related to ITNT which is being removed in update 1.12.0
