### ISSUE TITLE
Cyclic Sleeping Mat not working,

### ISSUE THREAD

**Issue by Furious1964** [FTBTeam/FTB-Modpack-Issues#3487]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Trying to use the Sleeping Mat from Cyclic and it's not working, can't sleep.

### Steps to reproduce

Just use the Mat.

### Expected behaviour

I expected it to work properly.

**Comment by ukmcplyr** [comment]
There's an issue open for this already at #2924
