### ISSUE TITLE
Wrong recipe for cobblestone with Pedestals

### ISSUE THREAD

**Issue by ZirMc** [FTBTeam/FTB-Modpack-Issues#3488]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Log Files

NA

### Describe the bug

The JEI recipe for a pedestal with stone under shows stone as the output, rather than cobblestone. 

### Steps to reproduce

1. Open inventory / crafting menu
2. Search for "@Pedestals Material"
3. Hover over Material Generator and hit U
4. Browse pages under material generator until you find stone (for me it is page 14, not sure if it is consistent across devices)

### Expected behaviour

Should show cobble as output

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/79288970/2a80984d-dbd6-47bd-b0e9-d9b9940a5dcd)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/79288970/2eb74666-2b3b-4ea6-8bb9-5493b06f3ac9)

**Comment by Saereth** [comment]
you need to give it silk touch if you want stone, the quests explain this

**Comment by ZirMc** [comment]
I am sorry, you seem to have misunderstood. The recipe in JEI shows stone under pedestal produces stone, not cobblestone. This caused me some frustration as I misread the quest and couldnt figure out how to get the pedestal to produce cobble, not stone. It should show that stone under the pedestal produces cobble.
