### ISSUE TITLE
JEI Interface performance issues

### ISSUE THREAD

**Issue by Avemado** [FTBTeam/FTB-Modpack-Issues#3490]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Having a crafting interface open and pressing "U" on a melon block in your inventory (looking up possible recipes to craft with a melon block) uses up a lot of performance.

Edit:  Same thing happens with netherite blocks, only page 1 affected

Just by having this setup, while looking at the crafting recipes on page 1 (page 2 works fine, probably cause the bookshelfs aren't cycling), it's already lagging quite bad (UI feedback is slowed and background animations are laggy/choppy).
It gets even worse, down to 1 fps, when I place down my 12 wind generators hooked up to my mekanism blocks.

![2023-06-12_03 24 48](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/58288858/84e48965-8274-415d-81ed-368ed82babc0)

### Steps to reproduce

1. Have a bunch of machines running (wind generators, pipes transporting items, pedestals farming/transporting items) to just cause a bunch of load
2. Not so much load that it's already lagging, but gets close to it
3. Place down crafting table or station
4. Open crafting interface from table or station
5. Look up craftable recipes with the melon block
6. Experience lag on recipe page 1

### Expected behaviour

Not lag the game down to a crawl

### Screenshots

![2023-06-12_03 24 48](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/58288858/84e48965-8274-415d-81ed-368ed82babc0)

### Additional information

Edit: Shaders did not affect performance at all
Edit 2: Same thing happens with netherite blocks, only page 1 affected

AMD Ryzen 7 2700X Eight-Core Processor 3.70 GHz
16.0 GB of RAM
AMD Radeon RX 6700 XT

**Comment by Saereth** [comment]
this is related to those crafting stations, duplicate issue, we've requested the mod dev to look into it in the other issue threads already. ty for the report though!

**Comment by Avemado** [comment]
What crafting stations?
This also happens with normal workbenches
