### ISSUE TITLE
[StoneBlock 3] Massive Frame Drops Due To Mouse Polling Rate

### ISSUE THREAD

**Issue by Kieran99235** [FTBTeam/FTB-Modpack-Issues#3491]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.1

### Describe the bug

Started to get random frame drops when moving the mouse. Did some troubleshooting, reseaching and figured out it was caused by the polling rate on my mouse. Changed the poll rate to 500 instead of 1000 and frame drops vanished. 

A really werid bug as It just randomly happend, I've never changed the poll rate on my mouse before.

Mouse: Logitech G703 

> 

### Steps to reproduce

I'm unsure why or how it started happening.

### Expected behaviour

No frame drops.

### Screenshots

Video to better explain.
https://youtu.be/rn8-Rqb3ei4

**Comment by DinnerBeef** [comment]
This has been an on and off minecraft issue for a while. Just have to keep the polling rate lower.
