### ISSUE TITLE
This is a TEST Issue!

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Modpack-Issues#3493]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

This is a TEST Issue!

### Log Files

This is a TEST Issue!

### Describe the bug

This is a TEST Issue!

### Steps to reproduce

This is a TEST Issue!

### Expected behaviour

This is a TEST Issue!

### Screenshots

This is a TEST Issue!

### Additional information

This is a TEST Issue!

**Comment by Raidobw2** [comment]
Works
