### ISSUE TITLE
[IBPDX]  Mod name tooltip mod useless because it makes duplicates.

### ISSUE THREAD

**Issue by Leclowndu93150** [FTBTeam/FTB-Modpack-Issues#3494]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.0

### Describe the bug

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/73310949/5a65521c-7a08-4642-9292-1699984d229a)

basically thats it

### Steps to reproduce

play the pack

### Expected behaviour

a  working pack after it being tested in beta

### Additional information

**Comment by Leclowndu93150** [comment]
dont mind the untranslated items

**Comment by manmaed** [comment]
Just installed the pack and found the block in the image isn't a translation string ![](https://ss.manmaed.net/1686654274.png)

**Comment by Leclowndu93150** [comment]
> Just installed the pack and found the block in the image isn't a translation string ![](https://camo.githubusercontent.com/5aa5aee788fad3e508e089152d4113a0a84caf5d2bd833b3bd06b3a3fb4973e9/68747470733a2f2f73732e6d616e6d6165642e6e65742f313638363635343237342e706e67)

I said dont mind the untranslated items

**Comment by pikminman13** [comment]
without the modnametooltip it all shows as being from "minecraft" for the custom items

**Comment by Leclowndu93150** [comment]
Then is it possible to disable JEI mod thing

Le mar. 13 juin 2023, 17:12, pikminman13 ***@***.***> a
écrit :

**Comment by pikminman13** [comment]
jade has been removed for 1.0.1
