### ISSUE TITLE
floating ores

### ISSUE THREAD

**Issue by demoniclords** [FTBTeam/FTB-Modpack-Issues#3495]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.0.0

### Describe the bug

the asteroid from the space boss tools mod makes floating ores around 

### Steps to reproduce

find a asteroid from space boss tools

### Expected behavior

everything on the ground

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/114711675/f006a985-8f81-47fb-b367-d28bb2e0476e)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/114711675/52f08400-f44c-4a96-9398-b17f8c95b997)

**Comment by pikminman13** [comment]
intended functionality
