### ISSUE TITLE
double names

### ISSUE THREAD

**Issue by demoniclords** [FTBTeam/FTB-Modpack-Issues#3496]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.0.0

### Describe the bug

all items show the mod name two times

### Steps to reproduce

look in jei and hover over something

### Expected behaviour

it has the mod name on time

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/114711675/d1b34ed1-4228-4e6e-ae9f-5583697f09b2)

**Comment by pikminman13** [comment]
fixed for 1.0.1
