### ISSUE TITLE
Stoneblock 3 Not Responding on World Load

### ISSUE THREAD

**Issue by pythour** [FTBTeam/FTB-Modpack-Issues#3499]
### Modpack

FTB StoneBlock 3

### Modpack version

1.6.1, 1.7.0, 1.7.1

### Log Files

https://pastebin.com/J8D1GrVk
https://pastebin.com/jFRC6LKs

### Describe the bug

When I open my world (or any other world) in stoneblock 3, it goes through the "reading world data" stage and then proceeds to stop responding until I have to force close it. I used to be able to play, but one day, not even after an update or anything, I started experiencing this bug.

### Steps to reproduce

1. load game
2. open world
3. reads world data
4. game stops responding

### Expected behaviour

I expect the world to open

**Comment by UnRealDinnerbone** [comment]
Looks like a config got corrupted, try remvoing compactmachines-server.toml in the config folder and trying again

**Comment by pythour** [comment]
> Looks like a config got corrupted, try remvoing compactmachines-server.toml in the config folder and trying again

in my config folder, there is no compactmachines-server.toml. there's a compactmachines-common.toml, but not the one you mentioned
![Capture](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/103907330/5f5219b2-f056-452c-aa44-6fedd6b0cf97)

**Comment by UnRealDinnerbone** [comment]
oh sorry it's a server config, so it will be in your world folder / config

**Comment by UnRealDinnerbone** [comment]
Well it looks like it champions-server.toml causing the issue now

**Comment by pythour** [comment]
> Well it looks like it champions-server.toml causing the issue now

i deleted all of them and it worked. tysm **<3**
