### ISSUE TITLE
[Bug]: Joining or creating an FTB team deleted all items in inventory

### ISSUE THREAD

**Issue by BennyOfEarth** [FTBTeam/FTB-Modpack-Issues#350]
### Modpack

FTB Oceanblock

### Modpack version

1.8.0

### Describe the bug

Joining or creating an FTB team deleted all items in inventory

### Steps to reproduce

Use the ingame commands to create a team or join a team someone invites you

### Expected behaviour

items deleted from inventory (other than curios)

### Additional information

Contact me via discord at Benjamin268#4364 (I'm in the discord server)if there are any logs or anything that could help y'all.

**Comment by Raidobw2** [comment]
Hi, this is intended behavior. You can read our developer's answer on FTBTeam/FTB-Mods-Issues#83 for that matter.

You can change the config to prevent that behavior if you want, which is also explained in that linked issue. Cheers.

**Comment by BennyOfEarth** [comment]
Alright, thanks for the response. I don't entirely get your reasoning for this being a thing but okay.
