### ISSUE TITLE
FullScreen Crash

### ISSUE THREAD

**Issue by Namurtss** [FTBTeam/FTB-Modpack-Issues#3500]
### Modpack

FTB Magic World 2

### Modpack version

1.1.2

### Log Files

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 6/13/23 11:21 PM
Description: Unexpected error

java.lang.IllegalStateException: Cannot determine close requested state of uncreated window
	at org.lwjgl.opengl.Display.isCloseRequested(Display.java:549)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:889)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_312, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 669632704 bytes (638 MB) / 1073741824 bytes (1024 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 7 total; -Xmx4096M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 71 mods loaded, 71 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{6.4.49.965} [Forge Mod Loader] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{9.11.1.965} [Minecraft Forge] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Evoc{1.0.0} [Evoc] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	InfiniBows{1.2.0 build 14} [Infinity Bow Fix] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MobiusCore{1.1.0} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.6.1.9} [Not Enough Items] (NotEnoughItems 1.6.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	switches|pistontweak{1.3.0 build 25} [Switches|PistonTweak] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DamageIndicatorsMod{2.9.2.3} [Damage Indicators] (1.6.4 DamageIndicatorsv2.9.2.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DC1{2.4.0.12} [DukeCore] ([1.6.4] DukeCore v2.4.0.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AS1{2.4.5.21} [Arcane Scrolls] ([1.6.4] ArcaneScrolls v2.4.5.21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	bspkrsCore{v5.2(1.6.4)} [bspkrsCore] ([1.6.4]bspkrsCorev5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ArmorStatusHUD{v1.15(1.6.4)} [ArmorStatusHUD] ([1.6.4]ArmorStatusHUDv1.15.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	StatusEffectHUD{v1.19(1.6.4)} [StatusEffectHUD] ([1.6.4]StatusEffectHUDv1.19.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	arsmagica2{1.1.2b} [Ars Magica 2] (AM2_1.1.2b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Thaumcraft{4.1.0g} [Thaumcraft] (Thaumcraft4.1.0g.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	betterstorage{0.8.0.43} [BetterStorage] (BetterStorage-1.6.4-0.8.0.43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioCraft{1.5.5} [BiblioCraft] (BiblioCraft[v1.5.5].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Natura{2.1.14} [Natura] (Natura_mc1.6.X_2.1.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiomesOPlenty{1.2.1} [Biomes O' Plenty] (BiomesOPlenty-universal-1.6.4-1.2.1.416.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioWoodsBoP{1.3} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.3].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioWoodsNatura{1.1} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AWWayofTime{v1.0.0b} [Blood Magic: Alchemical Wizardry] (Blood Magic v1.0.0b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ChickenChunks{1.3.3.4} [ChickenChunks] (ChickenChunks 1.3.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHCore{2.0.0.2} [CoFH Core] (CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHLoot{2.0.0.2} [CoFH Loot] (CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHMasquerade{2.0.0.2} [CoFH Masquerade] (CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHSocial{2.0.0.2} [CoFH Social] (CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHWorld{2.0.0.2} [CoFH World] (CoFHCore-2.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CraftHeraldry{1.0.3} [CraftHeraldry] (CraftHeraldry 1.0.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Waila{1.5.2} [Waila] (Waila_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DragonAPI{release} [DragonAPI] (DragonAPI 1.6 V19b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DyeTrees{beta} [Dye Trees] (DyeTrees 1.6 V19.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	eplus{1.16.5b} [Enchanting Plus] (EnchantingPlus-1.16.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	EnderForest{beta} [Ender Forest] (EnderForest 1.6 V19b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	EnderStorage{1.4.3.6} [EnderStorage] (EnderStorage 1.4.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	farlanders{1.1} [The Farlanders] (Farlanders_v1.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	flatsigns{1.4.0} [Flat Signs] (flatsigns-1.6.2-universal-1.4.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThaumicTinkerer{2.3-130} [Thaumic Tinkerer] (ThaumicTinkerer-2.3-130.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForbiddenMagic{0.32} [Forbidden Magic] (ForbiddenMagic pr0.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GeoStrata{Gamma} [GeoStrata] (GeoStrata 1.6 V19b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	HopperDuctMod{1.2.2} [Hopper Ducts] (HopperDuctsMod1.2.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	inventorytweaks{1.56} [Inventory Tweaks] (InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	JABBA{1.1.2b} [JABBA] (JABBA_1.1.2c.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	magicalcrops{3.2.1} [Magical Crops] (magical_crops_1.6.4_3.2.0_BETA_15a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	standardcrops{1.1.0} [Magical Crops - Crops & Food] (magical_crops_1.6.4_3.2.0_BETA_15a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mimicry{1.3.8.2} [Mimicry] (Mimicry_1.3.8.2_forge 965_mc 1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mystcraft{0.10.12.01} [Mystcraft] (mystcraft-uni-1.6.4-0.10.12.01.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons{1.10.4.64} [NEI Addons] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|AE{1.10.4.64} [NEI Addons: Applied Energistics] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|MiscPeripherals{1.10.4.64} [NEI Addons: Misc Peripherals] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|ExtraBees{1.10.4.64} [NEI Addons: Extra Bees] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Forestry{1.10.4.64} [NEI Addons: Forestry] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|CraftingTables{1.10.4.64} [NEI Addons: Crafting Tables] (neiaddons-mc164-1.10.4.64.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIPlugins{1.1.0.6} [NEI Plugins] (NEIPlugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	notenoughkeys{0.0.4} [Not Enough Keys] (NotEnoughKeys-1.6.4-0.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ObsidiPlates{2.0.0} [Obsidian Pressure Plates] (obsidiplates-1.6.2-universal-2.0.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	PlayerBeacons{1.2.2} [Player Beacons] (PlayerBeacons-1.6.4-1.2.2-28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	RandomThings{1.9} [Random Things] (Random_Things_v._1.9__MC_1.6.4_.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	xreliquary{1.1.2} [Xeno's Reliquary] (Reliquary-1.1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Revamp{1.2.2} [Rivvest's Enhancements to Villager and Mob Performance] (revamp-1.2.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	switches{1.3.0} [Switches] (switches-1.6.4-universal-coremod-1.3.0.25.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TorchLevers{1.3.2} [Torch Levers] (TorchLeversV1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	totemic{0.3.0a} [Totemic] (Totemic-0.3.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TwilightForest{1.20.5} [The Twilight Forest] (twilightforest-1.6.4-1.20.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	UtilityMobs{2.1} [Utility Mobs] (UtilityMobs 2.1 for MC 1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	witchery{0.16.3} [Witchery] (Witchery_0-16-3_164.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMultipart{1.0.0.244} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	McMultipart{1.0.0.244} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMicroblock{1.0.0.244} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.0.244.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.6.4-Forge9.11.1.965
	LWJGL: 2.9.0
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Pack: Default
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

### Describe the bug

I just switched my in-game settings to full-screen from window mode and the game crashed instantly. When I try to start it again, it gets through most of the startup process, then crashes again. The Launcher registers the crash. 

### Steps to reproduce

Open a new world in the modpack, and change display settings to fullscreen mode

### Expected behaviour

I was expecting the game to go into full screen mode

### Additional information

My current theory is that the full-screen requirements don't meet with what my OS and computer can offer, but I am not a coder, or really a knowledgeable computer person, so I don't know. I did change the window sizes in the launcher settings, but that didn't help. I have put a TON of effort into this world and it would suck to lose months of work on my favorite modpack. Any help is appreciated. Thank you!!!!!

**Comment by manmaed** [comment]
This is a very old pack and don't think it will ever be updated

**Comment by manmaed** [comment]
@Raidobw2 if you want to try and fix this :P
