### ISSUE TITLE
auto starlight infuser

### ISSUE THREAD

**Issue by kotsuki017** [FTBTeam/FTB-Modpack-Issues#3503]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.0.2

### Describe the bug

i think the aquamarine should be only one recipe at input slot in the multiblock auto starlight infuser
but the infused wood infused occupied another output 

### Steps to reproduce

just in auto starlight infuser recipes 

### Expected behaviour

aquamarine to infused aquamarine

**Comment by pikminman13** [comment]
can you reword the question i dont understand what youre asking

**Comment by liuseniubi** [comment]
> can you reword the question i dont understand what youre asking

TL;DR: Input Aquamarine, output Vibrant Infused Wood, seem like there's a wrong in `multiblockrecipes.js L5503`.

**Comment by pikminman13** [comment]
fixed
