### ISSUE TITLE
FTB Skies DUPE

### ISSUE THREAD

**Issue by Gablers** [FTBTeam/FTB-Modpack-Issues#3506]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Witch Hazel Drying Rack Dupe.
Anything inside it is duped on break

### Steps to reproduce

1. place
2. put item inside
3. break 
4. 2x of input dropped

### Expected behaviour

Breaking should give back the same items inputted

### Screenshots

https://i.giphy.com/media/OL1nI4xxOt8PvaDPE0/giphy.mp4

I've attached a vid, it's very simple to replicate.

**Comment by JustAnotherGhostName** [comment]
Looks like its a duplicate of #3452 , #3421, and half a dozen others which are already closed.
