### ISSUE TITLE
Resonating gem recipe VIA auto infusion altar seems incorrect

### ISSUE THREAD

**Issue by ShGGy64** [FTBTeam/FTB-Modpack-Issues#3508]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.0.2

### Describe the bug

The recipe for "resonating gems" and "vibrant infused wood" is the same in the Auto infusion altar and this seems wrong

### Steps to reproduce

1. Build the auto Infuser multiblock structure
2. Input liquid starlight as the fluid and Aquamarines as the item input
3. See error- Vibrant infused wood is produced 

### Expected behaviour

I expected inputting aquamarines to return Resonating gems

### Screenshots

![2023-06-16_18 11 24](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/136859944/c329fbec-cb4b-437a-a2fc-d0b214d902e5)
![2023-06-16_18 11 22](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/136859944/e5bae4aa-af89-431c-8697-c51744c82048)

**Comment by pikminman13** [comment]
ok fixed
