### ISSUE TITLE
[Bug / Error] FTB IBP disconnect error

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#3509]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.0.0

### Log Files

https://gist.github.com/JustAnotherGhostName/cc9057482801e4e07280d33b6fdc907e

### Describe the bug

Every once and awhile a player disconnects from the server followed by a netty error. From my understanding, the player did not intentionally disconnect. I dont know the cause, or how to replicate it. 

### Steps to reproduce

1. Start up a server
2. Have several people join and play
3. User may randomly disconnect
4. Error shows up in console after the disconnect message

### Expected behaviour

User does not randomly disconnect.

### Additional information

Some players also experience a higher ping than normal for the pack, inconsistently. Of course this could be something specific to their connection, however, they have not reported it as an issue on other servers on our network, which share the same physical uplink and box. This may be unrelated, but I figured it was worth mentioning as it is a connection related issue, and there could be a relation.

**Comment by manmaed** [comment]
Can you confirm this still happens as of 1.0.2?

**Comment by JustAnotherGhostName** [comment]
Yes, I updated my server last night, and the issue still occasionally occurs when I looked at the logs this morning. See attached gist.
https://gist.github.com/JustAnotherGhostName/abaf4b56f72d97340c283fe8e719ce51 

Looking at it a bit further though, it seems like it sometimes generates the message even if you just leave normally sometimes. 

I need to spin up a testing server today to add a discord bot to our server, so when I do that ill double check if its any of the server performance mods I put in the pack that I normally add.

For reference, the 3 things I added that affects mechanics for performance are radon, saturn, and dynview.

**Comment by JustAnotherGhostName** [comment]
Apologies, waiting on something to finish on my pc which I cant close before I can boot a test server. 

I will say though that the pack seems to have a similar connectivity issue that FTB Skies originally had. This pack doesn't have Sons of Sins, so I cant say its the same mod causing it, but per player traffic is like 5x that of other packs on my network. This could be the cause of the disconnects and bad connection for some, as it was reported to be the cause in Skies before it was fixed. 

For reference, on FTB Integration by Parts, with 4 players on, spark health report reports ` 2.2 MB/s / 12,601 pps` as the outbound traffic. Comparing it to ATM8 with 2 players, it reports `120.2 KB/s / 923 pps` as the outbound traffic. Of course they are different versions of mc, different mods, ect, ect, but that is a much higher jump.

**Comment by JustAnotherGhostName** [comment]
Update with the disconnect message, interestingly enough on a fresh test world (locally on my machine, so not at my host), same addon mods I have on my main server, im not getting the disconnect error when I disconnect. 

Might be because there isn't any actual network activity being done? Spark I guess knows its a local server, so it doesn't post the network connectivity.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
