### ISSUE TITLE
[Suggestion]: Update Quests and Tutorial Area to reference that non-hostile mobs are not a good source of food in Industrial Foregoing's Mob Slaughter Factory.

### ISSUE THREAD

**Issue by PotatoKnight** [FTBTeam/FTB-Modpack-Issues#351]
### Modpack

FTB Academy 1.16

### Modpack version

1.2.0

### Describe the bug

Following a conversation in FTB's discord, I can only conclude that the amounts of Liquid Meat and Pink Slime being given by the Slaughter Factory are way off. Far too much Pink Slime, and pathetic amounts of Liquid Meat. It's possible that the amount of Pink Slime is elevated because this is a tutorial pack, but there's no reason that I can think of for there to be so little liquid meat. I've looked up the standard amounts given by the mod and as far as I can tell the amount of Pink Slime given out is perhaps as much as 20x too much, and less than half of the amount of Liquid Meat than is usual.

Here is my setup, just incase it is my error, but no one in the Discord has been able to tell me as much at least.
![image](https://user-images.githubusercontent.com/4663736/142739502-a67d3d76-3893-4710-950e-4cf2866165e4.png)

### Steps to reproduce

1. Place a cow in front of a Slaughter Factory from Industrial Foregoing.
2. See that the Slaughter Factory gives way too much Pink Slime and far too little Liquid Meat.

### Expected behaviour

According to https://ftb.fandom.com/wiki/Mob_Slaughter_Factory, "Mobs killed will produce 5 mb of Liquid meat per HP and 1 mb of Pink Slime per HP (50 mb of Liquid Meat and 10 mb of Pink Slime for Cows and Pigs)."

### Screenshots

![image](https://user-images.githubusercontent.com/4663736/142739587-f074a117-c053-4fd2-975b-275e78e197b9.png)
The above is after a few ingame days of operation.

**Comment by PotatoKnight** [comment]
If I could change the title I would, "Industrial Foregoing's Mob Slaughter Factory is providing improper amounts of Liquid Meat and Pink Slime". Woops.

**Comment by quietust** [comment]
For the record, that wiki page is incorrect - the Mob Slaughter Factory gives different ratios of Meat/Slime depending on the mob type:
* Animals (i.e. peaceful mobs) give 1mB Liquid Meat and 20mB Pink Slime per HP
* Non-animals (i.e. hostile mobs) give 20mB Liquid Meat and 1mB Pink Slime per HP

**Comment by PotatoKnight** [comment]
> For the record, that wiki page is incorrect - it was created back in 2018 and its content was never updated since.
> 
> In the current version, the Mob Slaughter Factory gives different ratios of Meat/Slime depending on the mob type:
> 
>     * Animals (i.e. peaceful mobs) give 1mB Liquid Meat and 20mB Pink Slime per HP
> 
>     * Non-animals (i.e. hostile mobs) give 20mB Liquid Meat and 1mB Pink Slime per HP
> 
> 
> Ref: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/1.16/src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/SlaughterFactoryTile.java#L85

It may be then that this report is inaccurate! I will do some further testing with hostile mobs. Thanks for the comment!

**Comment by PotatoKnight** [comment]
So I've done some testing!

Here are the results, using spawn eggs in creative mode.

![image](https://user-images.githubusercontent.com/4663736/142777532-945c22dc-1e92-47a0-a085-2ed7b2c24527.png)

Given these numbers are about what one would expect re: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/1.16/src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/SlaughterFactoryTile.java#L85 , I'm going to close this comment. I will say, personally, however, I think it's very silly that the mobs you otherwise breed for food _aren't a good source of food in aslaughtering farm_, and think the situation should be reversed, but it seems regardless this is working as intended.

Maybe the Quest (and the tutorial area) should be changed to reflect that non-hostile mobs are NOT a good source of food, as both imply otherwise. I will keep this open for now, as more of a suggestion than a bug report.

**Comment by aaronhowser1** [comment]
Submitted to mod dev InnovativeOnlineIndustries/Industrial-Foregoing/issues/1224

If they confirm it's intended (somewhow), I'll mention it in the quest.

**Comment by quietust** [comment]
I thought I made it clear in my earlier post that this was 100% intentional:
```
                    meat.fillForced(new FluidStack(ModuleCore.MEAT.getSourceFluid(), entity instanceof AnimalEntity ? (int) (currentHealth) : (int) currentHealth * 20), IFluidHandler.FluidAction.EXECUTE);
                    pinkSlime.fillForced(new FluidStack(ModuleCore.PINK_SLIME.getSourceFluid(), entity instanceof AnimalEntity ? (int) (currentHealth * 20) : (int) currentHealth), IFluidHandler.FluidAction.EXECUTE);
```

**Comment by aaronhowser1** [comment]
I don't understand the thought process behind it, but they've confirmed it's intentional. I thought maybe they forgot a `!` somewhere or something. I've added a line to the quest mentioning it.
