### ISSUE TITLE
JEI search crash

### ISSUE THREAD

**Issue by TheTryharder** [FTBTeam/FTB-Modpack-Issues#3511]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.16.5

### Log Files

Local\.ftba\instances\842c5bf3-4ebc-beec-3743b92f14aa\hs_err_pid23152.log

### Describe the bug

Game crashes when keyword mod is entered followed by u. Crash recreated 5 times to isolate crash.

### Steps to reproduce

Open inventory
click on search bar in JEI
enter "mod"
follow that string with a "u"
game crashes on site

### Expected behaviour

JEI searched "modu"

**Comment by manmaed** [comment]
Can you confirm this still happens as of 1.0.2?

**Comment by pikminman13** [comment]
i thought we fixed this. let me ask sae

**Comment by TheTryharder** [comment]
> Can you confirm this still happens as of 1.0.2?

The version I was using was 1.0.2

**Comment by Saereth** [comment]
can you please actually link that file to us for review, you can upload it to google drive or something like that, thanks.

**Comment by TheTryharder** [comment]
yeah, it'll take a a couple hours i'm not home

**Comment by Rasip** [comment]
Typing "dra" into JEI looking to see if drawers is in the pack also crashed it. immediately relaunched and tried again and it crashed the moment i hit the a.
[hs_err_pid14772.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11780044/hs_err_pid14772.log)

**Comment by TheTryharder** [comment]
> can you please actually link that file to us for review, you can upload it to google drive or something like that, thanks.

https://drive.google.com/file/d/1oFIdZUSnE6Wr--aFw5n8JNOXBkHL6X7E/view?usp=sharing
