### ISSUE TITLE
Why doesn't Budding Selenite bud?

### ISSUE THREAD

**Issue by Furious1964** [FTBTeam/FTB-Modpack-Issues#3513]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Is there a problem in getting Budding Selenite to grow? Been trying for days and nothing is happening.

### Steps to reproduce

1. Place block
2. Nothing happens for days.

### Expected behaviour

This is just a question to find out if Budding Selenite doesn't work.

**Comment by Saereth** [comment]
unsure, looked at the code and it seems fine, just basically extends vanilla rules for amethysts, will have to do some testing
