### ISSUE TITLE
Backpacks losing their inventory when upgraded with custom recipes

### ISSUE THREAD

**Issue by caner-191** [FTBTeam/FTB-Modpack-Issues#3514]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.0.2

### Describe the bug

When sophisticated backpacks' backpacks upgraded by custom recipe they lose their inventory. So yes, no problem on netherite upgrade.

### Steps to reproduce

1. Store items in a sophisticated backpack.
2. Upgrade the backpack with a custom recipe.
3. Stored items gone!

### Expected behaviour

Backpacks shouldn't lose their inventory on custom recipe upgrade.

**Comment by pikminman13** [comment]
i fixed this yesterday. itll be in the next update
