### ISSUE TITLE
Opening the "DE" chapter crashes the game. 

### ISSUE THREAD

**Issue by Wolfsokim** [FTBTeam/FTB-Modpack-Issues#3516]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.0.2

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11780552/latest.log)

### Describe the bug

Opening the "DE" chapter in the quest book crashes the game. It seems to not matter how long I have been in my world.

### Steps to reproduce

Open a world.
Open questbook.
Go to "DE" chapter.
Game Crash

### Expected behaviour

Being able to explore the "DE" chapter.

**Comment by Wolfsokim** [comment]
Did some digging, anything related to Draconic crashes the game. (I am on an AMD GPU as that seems to be relevant according to the internet.

I HAVE FIXED THE ISSUE by going into the Draconic Evolution config file, and setting the shader settings all to false.
![Shaders = False](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/21130986/67e61214-36d3-49f5-8334-c1930eb77bb2)

**Comment by manmaed** [comment]
https://github.com/Draconic-Inc/Draconic-Evolution/issues/1539

**Comment by manmaed** [comment]
Detailed fix for users:
If your game crashes it is a "java crash", therefore the crash is located directly inside the modpack folder this time. It will look like `hs_err_pid13156.log`.
Fix: go in `config/brandon3055/DraconicEvolution.cfg` and disable all those shaders (they are set to `true` right now, set them all to `false`):

```
# Set this to false to disable tool shaders.
B:"toolShaders"=true

# Set this to false to disable crystal shaders.
B:"crystalShaders"=true

# Set this to false to disable reactor shaders.
B:"reactorShaders"=true

# Set this to false to disable all other shaders.
B:"otherShaders"=true
```

Late game you might need to disable this, up to you if you want to do it now as well, but you might also be fine:
This one is set to `true` right now, late game if you crash you might need to set it to `false`.
```
# Set this to false to disable chaos guardian shaders.
(May visually break some stuff but could be useful if you are experiencing gl crashes.)
B:"guardianShaders"=true
```

Then start your game again and type stuff like "draconic" in the JEI search box, if it doesn't crash, you've solved it. 🎉

_Originally posted by @Raidobw2 in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40#issuecomment-966039154_
