### ISSUE TITLE
Aluminum ore doubling

### ISSUE THREAD

**Issue by Don77b** [FTBTeam/FTB-Modpack-Issues#3517]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.0.2

### Describe the bug

Putting Aluminum Dirty Dust into the compressor is supposed to give two Aluminum clumps per dust, but it is giving only 1

### Steps to reproduce

1. Bauxite ore into botania mana pool
2. Aluminum Dirty Dust into FTB Compressor
3. Realize that was a wasted step as its 1 to 1 and not 1 to 2

### Expected behaviour

1 Aluminum Dirty Dust into FTB Compressor = 2 Aluminum Clumps

**Comment by pikminman13** [comment]
quest text was wrong. it gives you one clump which makes two ingots. this was corrected.
