### ISSUE TITLE
High traffic for no reason

### ISSUE THREAD

**Issue by metalim** [FTBTeam/FTB-Modpack-Issues#3518]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.0.2

### Describe the bug

Similar to https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3169, this pack on server has excessive traffic per client for no reason

10 Mbps is transferred constantly to 1 client, on idle base, and with not much activity around. As it's within my channel capabilities, effect is not as fatal as in FTB Skies, however excessive traffic causes client lags, when there are no TPS issues

### Steps to reproduce

Play the pack on server, lol

### Expected behaviour

Traffic should stay at 1 Mbps (100 KB/s)

### Screenshots

<img width="627" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/230431/2447b54a-36c2-46d3-b11a-aa3730562a14">

**Comment by JustAnotherGhostName** [comment]
Just mentioned this in my issue #3509 , I think its related ish. I occasionally get people that just get massive spikes in their ping specifically on this pack in the network (the other servers on my network are the same box and outbound link, so it shouldn't be that different).

**Comment by JustAnotherGhostName** [comment]
Network usage is particularly bad for my server right now, issue is still there. Have had 2 people on since the last restart, 3 hours of  play time. Right now spark reports the following:

    34.7 KB/s / 566 pps (eth0 rx)
    1.1 MB/s / 5,497 pps (eth0 tx)
    
Which aint the best, but looking at the panels recording for total data send and received, its at 222 MiB inbound and 6.56 GiB outbound, which is much higher than its normal issues.

**Comment by JustAnotherGhostName** [comment]
Had a random spike that basically had all players online get it by it at once, no clue the cause. 
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/122759195/7b45b3c9-3a28-4103-b531-b26663bc19bc)

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?

**Comment by metalim** [comment]
> Could you please confirm if you are still experiencing this issue with the latest pack version? If you are, would you be able to upload new log files for us so we can take a further look?

The server has been shut down for a long time due to inactivity, as is my modpack installation. I'll leave it to others, who still play the pack
