### ISSUE TITLE
Stoneblock 3 Server crashes on startup

### ISSUE THREAD

**Issue by SenoTech** [FTBTeam/FTB-Modpack-Issues#3519]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.6.1 & 1.7.1

### Log Files

[crash-2023-06-18_14.31.57-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11782102/crash-2023-06-18_14.31.57-server.txt)

### Describe the bug

Server completly crashes on startup.

What we did to solve this issue:
1. Tried the world in singleplayer: started up fine
2. tried upgrading from 1.6.1 to 1.7.1: didnt help
3. tried a new installation of the stoneblock server: didnt help

### Steps to reproduce

1. Start server
2. Server crashes
3. Dead server :sad

### Expected behaviour

Server startup without errors

**Comment by manmaed** [comment]
is this stoneblock 3 or Intergration By Parts DX?

**Comment by SenoTech** [comment]
@manmaed it is about Stoneblock3. I found this git repo in the Version Tab. Hopefully it was right to post it here.

**Comment by SenoTech** [comment]
Hey sorry for the late reply. Was waiting for the data from a M8 cause i am not the owner of the server. Here is the lates.log and debug.log

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11805599/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11805600/latest.log)

**Comment by SenoTech** [comment]
Well it seems like the installation of the server is f...ed.

Just did a clean install on my laptop so i can verify its not the world data. Just hopeing I can sort it on the server as well

**Comment by manmaed** [comment]
The Crash Log Provided was caused by watchdog which means A single server tick took 60.00 seconds (should be max 0.05)

**Comment by SenoTech** [comment]
@manmaed i think that a serverfile is just currped and that the server is dead because of it. There was also a error in the logs which statet that a user tried to connect and that caused the overload. This error is traceable to modfiles which are incorrect or faulty.

I could start my localy hostet server on my laptop which ran fine without any problems. (World data form Server, new server installation).

I will investigate the issue further to see what is wrong and will keep you postet

**Comment by SenoTech** [comment]
I just figured it out. It was a currupted file of the server. After reinstating the file the server did start up fine
