### ISSUE TITLE
[Bug]:  Mini Utilities Solar Panels

### ISSUE THREAD

**Issue by Zen-Headshot** [FTBTeam/FTB-Modpack-Issues#352]
### Modpack

FTB Oceanblock

### Modpack version

1.9

### Describe the bug

Placing multiple Mini Utilities controllers connected to Mini Utilities solar panels will exponentially increase the power produced.

Last photo in the screenshots is an array that does not tax server resources as hard. if i put solar panels between that array set to combine them all, the usage per block will be ~600μs/t per controller. In the array i have set its only 16μs/t per controller.

### Steps to reproduce

Place down an array of solar controllers from Mini Utilities, they cannot touch and cannot be in a direct checkerboard pattern.
Next place the solar panels down from Mini Utilities. (Placing the solar panels first will not work)
Afterward connect all of the controllers outputs (at the top) to a combined input to a battery or energy sink using a flux plug to get an accurate energy reading.

### Expected behaviour

Each controller should recognize and update what solar panels its using so other controllers cant take advantage. The controllers only notice if you place the panels first.

### Screenshots

![Screenshot_88](https://user-images.githubusercontent.com/12034923/142742723-a2d7e637-3e15-45d7-a968-d99277100f87.png)
![Screenshot_89](https://user-images.githubusercontent.com/12034923/142742730-edad7191-8ed1-45c8-8315-cf2ac0c34859.png)
![Screenshot_90](https://user-images.githubusercontent.com/12034923/142742732-368ab286-f3cd-4179-9814-79485e1386a8.png)
![Screenshot_91](https://user-images.githubusercontent.com/12034923/142742733-d650b3eb-e401-4814-8b4b-23316a3d94db.png)
![Screenshot_92](https://user-images.githubusercontent.com/12034923/142742752-7fba4dcb-cb32-4fe9-a209-ba1d4028b799.png)
![Screenshot_93](https://user-images.githubusercontent.com/12034923/142742761-3a333e8a-bccf-4915-a73f-71a0a2545764.png)
![Screenshot_97](https://user-images.githubusercontent.com/12034923/142742816-d562d078-93c3-49fb-b179-c3e1f57025f0.png)
![Screenshot_96](https://user-images.githubusercontent.com/12034923/142742822-b40a2b0a-e910-49bd-b34e-f87461a279e0.png)

### Additional information

If people are unaware about the μs/t of the controllers and connect a massive array it can cause a compounding influx of resource usage.

Any other information needed, feel free to contact me on the FTB discord @𝒵𝑒𝓃

**Comment by Sunekaer** [comment]
https://github.com/OneLemonyBoi/MiniUtilities/issues/110

**Comment by Raidobw2** [comment]
Fixed in-dev on the mod author's repo OneLemonyBoi/MiniUtilities@6644a26. Now we just wait for the mod to update at https://www.curseforge.com/minecraft/mc-mods/miniutilities/files
