### ISSUE TITLE
Broken item "Eye of Sky Legend"

### ISSUE THREAD

**Issue by SoulK1ller** [FTBTeam/FTB-Modpack-Issues#3520]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Log Files

[crash-2023-06-18_18.00.43-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11782283/crash-2023-06-18_18.00.43-server.txt)

### Describe the bug

Server crash on attempt to use item "Eye of Sky Legend"

### Steps to reproduce

Create "eye of sky legend" item
Right click to use item
Watch as nothing happens and time stops

### Expected behaviour

I don't know, something awesome I guess

**Comment by Saereth** [comment]
I made some changes to its behavior for next update, if you have any issues then get a fresh log and open a new issue please, should be sorted now though
