### ISSUE TITLE
softlock lockout bugs

### ISSUE THREAD

**Issue by CoryNB** [FTBTeam/FTB-Modpack-Issues#3521]
### Modpack

Other...

### Modpack version

any or all versions

### Describe the bug

I discovered a code bg under jei cheat mode in multi player mode for keybinds locking user out of their pause menu. can be serious threat for ransomware or malware attack. 

### Steps to reproduce

jei cheat mode key binds section

### Expected behaviour

behavior should work without clicking conflict between op warn/chat warn.

### Screenshots

only possible in minecraft to be seen.

### Additional information

softlock accidentally discovered today while trying to find certian option.

**Comment by manmaed** [comment]
Please provide a modpack this happens in with the version numbers

**Comment by Raidobw2** [comment]
Hi, which FTB modpack have you experienced this in? I'll be awaiting your reply, thanks for the report
