### ISSUE TITLE
Crash at Launch -  Immersive Engineering, Immersive Industry - "failed to load correctly"

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#3522]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.0.3

### Log Files

https://pste.ch/apucemoziz.log

### Describe the bug

launch fails due to mod failing to load correctly

### Steps to reproduce

launch game
mods crash, see logfile
lather rinse repeat

### Expected behaviour

normal launch

### Additional information

I had launched already once or twice after updating and was not expecting this to suddenly fail . I've downgraded to previous in the meantime

**Comment by pikminman13** [comment]
afaik reloading fixes it

**Comment by WebDragon** [comment]
I reloaded twice - the successive reloads had both modules cause crashes - the initial crash was only immersive engineering. at that point I punted and downgraded and will just wait for the next update

**Comment by WebDragon** [comment]
1.1.0 seems to be fine. will re-open if there is a repeat performance
