### ISSUE TITLE
Game saves being deleted :( 

### ISSUE THREAD

**Issue by GalaxyAlissy** [FTBTeam/FTB-Modpack-Issues#3525]
### Modpack

FTB StoneBlock 3

### Modpack version

1.18.2

### Describe the bug

After saving and loading up the game a few times, my 12 hours of hard work was fine. After a few days I returned, loading up through the FTB launcher and it was gone, with Stoneblock being deleted from my libary all together. Last night, I redownloaded and started again, this time making a backup save of my world, and when I logged on this morning, the save was gone again! Luckily due to the backup, my world is safe, but this is an ongoing issue. 

### Steps to reproduce

1. Shut down PC after gaming.
2. When you log back on, saves are deleted. 

### Expected behaviour

World saves deleted

**Comment by Raidobw2** [comment]
Hi, I feel it might be an issue with the FTB App. Perhaps we can check the way you close the FTB App and your PC, and then I'll be able to relay information to the app team for them to fix this.

If you wish to fix some of your worlds, you can DM or ping me anywhere on the [FTB Discord](https://go.ftb.team/discord), my username there is the same as here `@R3GEN`. I'll be able to provide more live support there than on here.

I'll be awaiting your contact!

**Comment by Gaz492** [comment]
I believe that this issue with the app has been resolved now, if the issue continues to occur to you, please open a new issue on our app issue tracker https://github.com/FTBTeam/FTB-App
