### ISSUE TITLE
empowered gold | softlocked progression

### ISSUE THREAD

**Issue by minecrafterseppe** [FTBTeam/FTB-Modpack-Issues#3529]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.0.3

### Describe the bug

metal empowerer needs 80k rf  for empowered gold ingot               but only stores  20k in input buffer

machine will not start craft even when provided with the needed stuff

### Steps to reproduce

assemble empowered

put in recipy items/fluids for empowered gold 

does not start the craft

### Expected behaviour

it should start making empowered gold

**Comment by pikminman13** [comment]
i fixed it
