### ISSUE TITLE
[Suggestion]: Add Creative Compressed Iron recipe

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#353]
### Modpack

FTB University

### Is your suggestion related to a problem? Please describe.

Creative Compressed Iron does not have a recipe. The recipe should not cost much since it has limited (but well defined) usefulness, and we already have the ability to maintain near infinite temperatures with Tinker's Firestarters. 

The difficulty comes in trying to maintain a temperature in a range which requires heating/cooling blocks using Integrated Dynamics to regulate the temperature, or building a network in the nether where the ambient temperature is in the correct range.

Adding a recipe for the Creative Compressed Block would fix these considerable inconveniences.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/145760741-863f7119-48c1-47ac-ab66-b58deb5a2697.png)
![image](https://user-images.githubusercontent.com/15698722/145760754-02a4c863-c545-42fb-bb2e-589f1c762dc8.png)
![image](https://user-images.githubusercontent.com/15698722/145760767-341778ad-6bbb-47eb-bf8a-bb12ded00206.png)
