### ISSUE TITLE
can't make empowered lead ingot & can't build Fluxial Converter 

### ISSUE THREAD

**Issue by Fellal1** [FTBTeam/FTB-Modpack-Issues#3537]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.1.0

### Describe the bug

cant make empowered lead ingot 

and dont have recipe fluxial converter

### Steps to reproduce

1. make metal empowerer 
2. put in input port to 1 lead ingot and 4 infused emeraldium crystal

### Expected behaviour

cant make item

### Screenshots

![2023-06-21_02 04 19](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/5456ea89-507e-4c9f-8af2-6c26b6a45684)
![2023-06-21_02 04 47](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/d4f504a1-a01c-4905-b0b3-0540878f7777)
![2023-06-21_02 07 19](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/813b82f5-f51e-42da-b2e8-d69c6817127c)

**Comment by pikminman13** [comment]
did you replace the port like the chat message on login said to do?

**Comment by Fellal1** [comment]
oh i fix that

**Comment by Fellal1** [comment]
yep same issue

**Comment by minecrafterseppe** [comment]
the recipy for empowered lead is different as it "outputs" power for somereason
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/13523046/8f80595f-1dce-40af-a4d7- 180c03a641c3)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/13523046/6e445b97-fd96-4a65-9085-c8b78af647bb)

**Comment by minecrafterseppe** [comment]
(there is no output port on the multiblock)

**Comment by pikminman13** [comment]
oh whoops i better fix that

**Comment by pikminman13** [comment]
ok its fixed on my client

**Comment by pikminman13** [comment]
ok finally got around to the other half of this issue, ports are now craftable
