### ISSUE TITLE
Quest Problem

### ISSUE THREAD

**Issue by slaarek** [FTBTeam/FTB-Modpack-Issues#3538]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.16.1

### Describe the bug

Hello 
I've got an issue in stoneblock v2 on my multiplayer server. Everytime I complete some quest, I can normally claim the reward. Afterwards when I reconnect, all the quest that I've completed and claimed rewards already, become highlighted with red ! and showing that I can claim the reward again, but they are not claimable after I claimed them once. 

Hopefully you understand me, English is not my mother language, so I'm not sure with that 😅 

Thank you for your response.

### Steps to reproduce

1. join multiplayer
2. complete some quest
3. claim reward
4. reconnect

### Expected behaviour

some way to fix it

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
