### ISSUE TITLE
Stoneblock3 crash with STATUS_ACCESS_VIOLATION 

### ISSUE THREAD

**Issue by NovelPhacelia** [FTBTeam/FTB-Modpack-Issues#3541]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.1

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11816034/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11816035/latest.log)
[Console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11816040/Console.log)
[EventViewerLog.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11816065/EventViewerLog.txt)

### Describe the bug

Sometimes crashing at launch with error `STATUS_ACCESS_VIOLATION` and faulting module path of lwjgl.dll in event viewer, tracked it down to the bookshelf mod though I'm not sure if its a issue of the mod or modpack.

### Steps to reproduce

1. Start Stoneblock 3
2. Close Stoneblock 3
3. Repeat till crashes

### Expected behaviour

Stoneblock 3 to start without issue

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83443727/21102355-1c10-43fa-8181-e37c4f01884a)

### Additional information

Removing bookshelf, starting the game, adding bookshelf, then starting it again seems to sometimes fix it, if not then repeating previous steps till it works.
It usually occurs on the second attempt for me, though sometimes third

**Comment by UnRealDinnerbone** [comment]
Thanks for the report. The pack has been updated since this report, If this issue is still present, reopen this issue.
