### ISSUE TITLE
Some blocks lose excess power when connected to Masterful Machinery's Energy Input

### ISSUE THREAD

**Issue by Attacker0922** [FTBTeam/FTB-Modpack-Issues#3543]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.1.0

### Describe the bug

(I used a translator)

When IE's wire and Powah's Energy Cell directly connect to the MM's Energy Input, it transmits power even though the Energy Input is full of power.  This excess transmitted power is discarded.  I tested with LV wire and Basic Cell.

It is recommended that players put another block in between to prevent this.  Powah's cables (at least the Starter cable) don't void power. An example is this.

Power Source-Energy Cell-Cable-Energy Input

### Steps to reproduce

1. Fully power any Energy Input from MM (at least the Metal Empowerer did).
2. Connect IE's wire or Powah's Energy Cell (at least LV and Basic Cell did).
3. Transfer power to Energy Input.
4. An example is this.
Power Source-Energy Cell-Energy Input

### Expected behaviour

Energy Input is full, but power drains out.  The drained power completely disappears.

**Comment by pikminman13** [comment]
i dont think i can really do anything about this

**Comment by mexmer** [comment]
can we expect fix? version 1.8.0, and it's still broken.

**Comment by pikminman13** [comment]
unlikely. not really anything i can do about it. you can mitigate the issue by putting a powah pipe between an IE connector and the energy port.

**Comment by pikminman13** [comment]
also, universal cables and flux points do not seem to have this issue either.

**Comment by mexmer** [comment]
ok, thanks for answer, it doesn't look nice with powa cable between wire connector and machine, but it works, so there is workaround. other solution will be just cabling everything with powah, instead of IE, just IE wire can connect at longer distance and not block by block (and yes i'm aware of power loss on IE wires)

**Comment by mexmer** [comment]
Just note to this,
I encountered today same issue, but with MM and Xnet.
When you connect Energy input of MM to Xnet power network, it simply shorts it. there will be 0 RF in whole network as a result your inventory scanner, storages and even controller will loose all power. Workaround is same as for IE, put powa cable between Xnet connector and MM Energy Input.
Should i create this as separate issue?
