### ISSUE TITLE
U can't get Infused emeraldium it's just a endles loop of what u need

### ISSUE THREAD

**Issue by DizzyDrwaf** [FTBTeam/FTB-Modpack-Issues#3546]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.1.0

### Describe the bug

U can't get Infused Emeraldium u need a elven portal to get the elven quartz but to get the elven portal u need a astral tier 3 altar but to get that u need to get to the moon but to get to the moon u need Infused Emeraldium and it's just a endless loop 

### Steps to reproduce

follow the resepi for infused Emeraldium

### Expected behaviour

Add a new resepi to get stardust

### Screenshots

![Screenshot 2023-06-21 192944](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/ca7f8091-55bc-4eb1-96e8-690a3cb6e6e7)
![Screenshot 2023-06-21 193017](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/a52b796d-61d9-4610-bb85-00dba9f1381c)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/a3e55181-989f-46f8-b028-638356800285)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/d6142cef-3b2b-4588-a60c-20062facefcb)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/babcc4a9-2c86-4851-b162-e36cb2497b84)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/83c1a7d6-2cfa-4f97-88b1-aa2f8711d7d3)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/0066d1f0-9ae0-4ee6-99cb-f57474390d7e)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/e19a73f1-8745-4c59-bfb2-2416f1b20e91)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/3a60c15b-df12-4607-85e3-3f7c9932f57f)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/3df1aa91-1092-44ed-95c5-62e5d4bed5a2)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/306706e9-839c-48d0-a9ed-c211160db44e)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/d8f5e900-81cd-476f-8460-007051645052)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137322658/9a17d80d-dc68-4eae-b8ca-945e95521990)

### Additional information

it's a crafting and quast endless loop

**Comment by pikminman13** [comment]
theres another way to get stardust if you read the quests
