### ISSUE TITLE
Ftb crash on moving in game

### ISSUE THREAD

**Issue by Sfiend118** [FTBTeam/FTB-Modpack-Issues#3549]
### What Operating System

Windows 10

### Debug Code

 FTB-DBGCIHAVASURI

### Describe the bug

FTB crashes when I move

### Steps to reproduce

Move apparently

### Expected behaviour

FTB crashes

**Comment by MichaelHillcox** [comment]
Transferred as this is not an app issue

**Comment by Saereth** [comment]
What pack is this happening with?
