### ISSUE TITLE
[Bug]: Jar Auto Processing Obsidian

### ISSUE THREAD

**Issue by amill288** [FTBTeam/FTB-Modpack-Issues#355]
### Modpack

OceanBlock

### Modpack version

1.8.0

### Describe the bug

The Auto processing only works for Obsidian when the contents of the Jars are empty. 
 The setup is: 
Glass jar left side with water, tempered glass in middle with auto processor on top, glass jar right side with lava, cast iron tubes connecting them. 

Manual works when jars are not empty but as soon as the jars empty, the auto processing starts working.  The coding is backwards.

### Steps to reproduce

1. Glass jar left side with water 
2. Tempered glass in middle with auto processor on top
3.  Glass jar right side with lava
4. Cast iron tubes connecting them
5.  Auto processing works if empty left and right jars
6. Manual processing works if not empty left and right jars

### Expected behaviour

With left and right jars full, auto processing of obsidian to occur.

**Comment by Sunekaer** [comment]
Okay so this isnt a bug.
So if the jar is autocrafting and it drops a block on the groud (Doesnt have a inventory to put the item/fluid in) then it will stop the auto processing. 
What you seeing when the jar is empty is the processor trying to restart the recipe.
If you connect a chest to the pipe then youll see the chest getting filled.
