### ISSUE TITLE
FTB Skies not installing

### ISSUE THREAD

**Issue by awildsnorlax1** [FTBTeam/FTB-Modpack-Issues#3552]
### Modpack

FTB Skies

### Modpack version

All

### Describe the bug

FTB Skies giving Fatal exception while trying to install.

### Steps to reproduce

_No Response_

### Expected behaviour

Pack was meant to install

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/75688042/09e427f0-3c67-4d2f-b175-a6054f5f207f)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/75688042/d97ef90d-84c5-4a25-af4f-84918eb3b36c)

### Additional information

PC specs:

CPU: Ryzen 5 2600
GPU: MSI Gaming GeForce GTX 1660 Super
RAM: 16GB DDR4 Corsair Vengeance
1.7TB free space

**Comment by Saereth** [comment]
please head over to
https://github.com/FTBTeam/FTB-App/issues
for support with the app, this tracker is for issues with the pack itself
