### ISSUE TITLE
Advaced connectors from xnet lags/freezes the game.

### ISSUE THREAD

**Issue by ForteFornix** [FTBTeam/FTB-Modpack-Issues#3553]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.12.0

### Describe the bug

Game freezes when trying to manually craft or make a pattern in refined storage of the advanced connector from Xnet. Game  lags and freezes and  I have to force it to close and when trying to load the world again the world does not load.

### Steps to reproduce

Craft the connectors from xnet and then try to craft the advanced version.

### Expected behaviour

As soon as the recipe is placed in the crafting table the game lags and I'm not able to interact with anything or close the game without forcing it.

### Screenshots

I cannot get a screenshot of anything since the game lags and not able to interact or even close the game without forcing it to close.

**Comment by DinnerBeef** [comment]
Looks like It's an issue with https://github.com/mezz/JustEnoughItems/issues/3184

**Comment by BlueHero233** [comment]
Any follow up from this? having the exact same issue as OP described, game freezes while waila says "Waiting for server" and anyone connected times out
