### ISSUE TITLE
Crashing when grabbing item from creative inventory

### ISSUE THREAD

**Issue by yasterday** [FTBTeam/FTB-Modpack-Issues#3554]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.12.0

### Log Files

[crash-2023-06-23_11.16.36-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11849884/crash-2023-06-23_11.16.36-client.txt)

### Describe the bug

Game crashes upon opening creative inventory search tab, searching for an item, and attempting to drag it from creative inventory to hotbar.

### Steps to reproduce

-start world
-open creative inventory
-click on search tab
-search for an item
-drag item from creative inventory to hotbar
-game will freeze for a second before crashing back to FTB launcher

### Expected behaviour

expected to successfully drag item from creative inventory to hotbar

### Additional information

World was originally created in vanilla 1.19.2 and moved to FTB instance saves folder, clearWeatherTime changed to 5681 in level.dat

**Comment by DinnerBeef** [comment]
Unable to reproduce this issue. Please try reinstalling the pack and letting me know if this still happens.

**Comment by yasterday** [comment]
Will do, thanks!

**Comment by yasterday** [comment]
Reinstalling seems to have fixed it
