### ISSUE TITLE
nickel and invar chicken types

### ISSUE THREAD

**Issue by devessi** [FTBTeam/FTB-Modpack-Issues#3555]
### Modpack

FTB One

### Is your suggestion related to a problem? Please describe.

Compared to other materials, nickel is frustrating to acquire. The Chickens mod helps with hard to acquire materials through patience/time/breeding, but nickel (and invar) chickens are not breeding options in One.

### Mod suggestion

In some versions of the chickens mod included in other FTB packs, nickel and invar chickens are part of the varieties available. Please consider making them part of the FTB One chicken varieties.

**Comment by Saereth** [comment]
I sent the suggestion onto the mod devs ages ago, guess they're not looking to add it to the core mod for this version
