### ISSUE TITLE
unstable REI W on ae2 inscriber deadlocks

### ISSUE THREAD

**Issue by beepbopbeepboop** [FTBTeam/FTB-Modpack-Issues#3558]
### Modpack

FTB Unstable 1.20: Fabric

### Modpack version

1.0.0

### Describe the bug

In REI (e), when I search @ae2 inscriber and hit shift over it and then hit W, the game locks up (deadlock).  This also happens with at least one other ae2 block.

### Steps to reproduce

Hit e, hit shift, hit W.

### Expected behaviour

When I hit W with create in other packs, it does something useful

### Additional information

on a mac

**Comment by UnRealDinnerbone** [comment]
Fixed in 1.2.0
