### ISSUE TITLE
unstable techreborn resin basin doesn't work

### ISSUE THREAD

**Issue by beepbopbeepboop** [FTBTeam/FTB-Modpack-Issues#3559]
### Modpack

FTB Unstable 1.20: Fabric

### Modpack version

1.0.0

### Describe the bug

The resin basin can collect exactly once, and then never again. This mirrors manual tree tap and electric tree tap. The tree doesn't ever renew the resin.

The work around is a tree farm and an extractor to make rubber.

### Steps to reproduce

Collect resin, wait for hours and hours.

### Expected behaviour

In IC2, the resin comes back

### Additional information

on a mac

**Comment by UnRealDinnerbone** [comment]
Fixed in 1.1.0

**Comment by beepbopbeepboop** [comment]
Confirmed.
