### ISSUE TITLE
[Suggestion]: Add the radiant Modifier as a valid modifier for the Enviromental Tech Lightning Rod tasks (and make sure it works correctly)

### ISSUE THREAD

**Issue by GriSphera** [FTBTeam/FTB-Modpack-Issues#356]
### Modpack

FTB University 1.16

### Is your suggestion related to a problem? Please describe.

I found it odd that the only modifiers (for the Enviromental Tech/Energy mods) that you could craft early and use in the Lightning Rod were the null ones, since the other machines have at least one that you can craft and use along. So I looked in JEI, and surprisingly I found another modifier that wasn´t listed in the tasks: the Radiant Modifier. It has a crafting recipe and a description that says "Allows Lighting Rods to passively generate RF in sunny weather".

So in first place my suggestion is to add them as a valid item to complete the tasks in the corresponding quests in FTB Quests.

When you use the modifier the machine works at least seemingly at normal, but that's what heads to my second suggestion.

In second instance, it would be good to know if it is actually working (you might want to report this to mods's dev, actually). For example, the solar generator has in it's GUI the amount of RF that it generates per tick. While it's understandable that in the rod's case it doesn't shows the value, as the generation of energy is somewhat random, it should appear if the modifer is generating the passive energy. The other generator, the solar generator has a modifer that allows it to generate energy passively during the rain, and it shows the value. So it might be good, that if the rod is under sunlight and has the modifier installed, it shows how many energy it is generating per tick.

**Comment by zoller27osu** [comment]
Nit: the Lightning Rod quests should also be asking for an FE Output block of the current tier or higher :)

**Comment by aaronhowser1** [comment]
I'll add the radiant modifier

> So it might be good, that if the rod is under sunlight and has the modifier installed, it shows how many energy it is generating per tick.

This is beyond what a modpack can do, you would have to suggest that to the mod dev instead.
