### ISSUE TITLE
Getting very stuck in Validation

### ISSUE THREAD

**Issue by ArtsyRedhead4** [FTBTeam/FTB-Modpack-Issues#3561]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

I try to open and it gets stuck in validating assets. It will not get further in this process. It either results in a complete freeze of the FTB app or an error message. I have the same issue with FTB OceanBlock. It gets stuck in the exact same place. I use FTB StoneBlock 3 and don't have any issues. I'm unsure of what is causing the problem. I have tried restarting my computer and deleting and redownloading everything from the modpacks, the FTB app, and Minecraft Java. Nothing is resolving the issue. I've also tried downgrading to previous versions and they won't run either. 

### Steps to reproduce

1. Open FTB app
2. Click on FTB Skies
3. Click Play
4. Gets stuck on Validating Assets

### Expected behaviour

I want to be able to play the modpack. It looks so fun!

### Screenshots

![Screenshot (2)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137584930/d79404f2-af80-459e-99ce-0b7f1d38f08f)

**Comment by Saereth** [comment]
This is not a pack issue so there is nothing I can do to help you out here, you'll have to check over on the app support tracker. 
https://github.com/FTBTeam/FTB-App/issues
