### ISSUE TITLE
Quantum Quarry doesn't generate all overworld ores.

### ISSUE THREAD

**Issue by HAJ523** [FTBTeam/FTB-Modpack-Issues#3562]
### Modpack

FTB OceanBlock

### Modpack version

1.15.1

### Log Files

quantumquarryores.json as it exists today:

[
    {
        "name": "minecraft:coal_ore",
        "weight": 4,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "minecraft:iron_ore",
        "weight": 3,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "minecraft:gold_ore",
        "weight": 1,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "minecraft:diamond_ore",
        "weight": 1,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "minecraft:lapis_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "minecraft:redstone_ore",
        "weight": 4,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "minecraft:emerald_ore",
        "weight": 1,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "mysticalagriculture:soulium_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "mysticalagriculture:inferium_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "mysticalagriculture:prosperity_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "powah:uraninite_ore_dense",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "powah:uraninite_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "powah:uraninite_ore_poor",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "appliedenergistics2:charged_quartz_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "appliedenergistics2:quartz_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "thermal:copper_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "immersiveengineering:ore_aluminum",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "mekanism:fluorite_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "mekanism:osmium_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "mekanism:uranium_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    }
]

### Describe the bug

The quantum quarry is missing generation for many thermal ores. This does not appear to be on purpose as other ore generation methods return all ore types.

### Steps to reproduce

Start a quantum quarry and see that the ores for lead, apatite, cinnabar, niter, sulfur, tin, silver, nickel, sapphire, ruby are not generated.

### Expected behaviour

The missing ores would be generated as they are overworld ores.

### Screenshots

The following are my corrections to the config to make it work for my instances:

[
    {
        "name": "minecraft:coal_ore",
        "weight": 4,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "minecraft:iron_ore",
        "weight": 3,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "minecraft:gold_ore",
        "weight": 1,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "minecraft:diamond_ore",
        "weight": 1,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "minecraft:lapis_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "minecraft:redstone_ore",
        "weight": 4,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "minecraft:emerald_ore",
        "weight": 1,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "mysticalagriculture:soulium_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "mysticalagriculture:inferium_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "mysticalagriculture:prosperity_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "powah:uraninite_ore_dense",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "powah:uraninite_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "powah:uraninite_ore_poor",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "appliedenergistics2:charged_quartz_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "appliedenergistics2:quartz_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "thermal:copper_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "immersiveengineering:ore_aluminum",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "mekanism:fluorite_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "mekanism:osmium_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "mekanism:uranium_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "thermal:lead_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "thermal:apatite_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "thermal:cinnabar_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "thermal:niter_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "thermal:sulfur_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "thermal:tin_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "thermal:silver_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "thermal:nickel_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "thermal:sapphire_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    },
    {
        "name": "thermal:ruby_ore",
        "weight": 2,
        "dimensions": ["minecraft:overworld"],
        "biomes": []
    }
]

**Comment by manmaed** [comment]
This issue is stale and pack is no longer being worked on
