### ISSUE TITLE
FTB StoneBlock 3 Version 1.7.1 : Crash on joining a public or local server but not on a solo/offline world

### ISSUE THREAD

**Issue by AppoGit-Hub** [FTBTeam/FTB-Modpack-Issues#3563]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11856691/latest.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11856692/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11856693/debug.log)
[crash-2023-06-24_13.33.54-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11856694/crash-2023-06-24_13.33.54-client.txt)

### Describe the bug

crash happens only when joinning a local or public server but not in a solo/offline world

### Steps to reproduce

1. Launch FTB Stoneblock 3
2. Join a public or local server
3. <Crash on joining the server>

### Expected behaviour

Joining the server without a crash

### Screenshots

cool video of the crash : https://www.youtube.com/watch?v=ohxtbD10Lvo

### Additional information

i love the modpack

**Comment by UnRealDinnerbone** [comment]
Remove rubidium this is not a supported mod in the pack
