### ISSUE TITLE
mana input crafting bug

### ISSUE THREAD

**Issue by Fellal1** [FTBTeam/FTB-Modpack-Issues#3564]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.1.1

### Describe the bug

mana input crafting bug

### Steps to reproduce

1. find crafting table
2. crafting mana input port to output port

### Expected behaviour

cant make

### Screenshots

![2023-06-25_00 38 06](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/7c296c1c-96d3-4939-83ab-09952b2e0a4f)
![2023-06-25_00 38 08](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/ea671571-fd96-43f2-a27a-197d0c589103)

**Comment by Kojesma** [comment]
I have the same issue, it block progression, waiting for the fix ! :)

**Comment by pikminman13** [comment]
fixed in dev

**Comment by Zleub** [comment]
This is still a issue in 1.7.0
