### ISSUE TITLE
unstable iron probabilities

### ISSUE THREAD

**Issue by beepbopbeepboop** [FTBTeam/FTB-Modpack-Issues#3565]
### Modpack

FTB Unstable 1.20: Fabric

### Modpack version

1.0.0

### Describe the bug

Iron seems to be rare in worldgen.  22 iron, 676 copper.  Mainly techreborn progression. Just starting ae2.  Used turtle branch mining (40*30 area), and collected everything of value. Use turtle excavate 15 for some chunk clearing down to bedrock.  Building retechreborn machines as I go.  Thinking of iron farm to counter the lack of iron.

Not necessarily a bug.  Just an experience.

### Steps to reproduce

Play 1.0.0 for a day or two.

### Expected behaviour

I'm used to having slightly more iron in ic2 and/or ftb ultimate when it was new.

**Comment by UnRealDinnerbone** [comment]
Ores Spawn at different levels https://pbs.twimg.com/media/FFdKHA7X0AQCkVv?format=jpg&name=4096x4096

**Comment by beepbopbeepboop** [comment]
Vanilla iron farm solves the problem.
