### ISSUE TITLE
 fractioning still not working and the  forge hammer not working

### ISSUE THREAD

**Issue by MRminer69** [FTBTeam/FTB-Modpack-Issues#3566]
### Modpack

FTB Revelation

### Modpack version

3.6.0

### Describe the bug

i used this mod pack a whale ago and i just got back into it and i noticed that the forge hammer and wire cutters used to make tin plates and wiring would not craft the auto recipe in your inventory it shows tin and hammer but when you put it into the crafting table it will not craft along with the wire cutters used to make the bat box to store power also the fractioning still used to make tree oil will not accept sap no matter what pipe or slot i use i tried using a bucket as well but no luck 

### Steps to reproduce

not really sure what to put here but its telling me to put something here 

### Expected behaviour

for the  recipe to work

### Screenshots

![Screenshot 2023-06-24 165806](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137658942/305f81a8-c482-4820-a2a7-3f346feed533)

### Additional information

![Screenshot 2023-06-24 170117](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137658942/7f8d75cc-ac52-4041-ad09-2a43b5674e39)

**Comment by lucasbdv** [comment]
I have the same problem the solution was a downgrade to 3.5

**Comment by LevyWilson** [comment]
The reason this doesn't work is because there is a line in 01_unification.zs that disables all shapeless plate recipes. If you delete or comment that out, you fix the recipes without the need to downgrade Unidict.

`mods.unidict.removalByKind.get("Crafting").remove("plate");`
