### ISSUE TITLE
unstable immersive airplanes, biplane description typo

### ISSUE THREAD

**Issue by beepbopbeepboop** [FTBTeam/FTB-Modpack-Issues#3567]
### Modpack

FTB Unstable 1.20: Fabric

### Modpack version

1.1.0

### Describe the bug

"Fast and rather reliably." isn't English, "Fast and rather reliable." is better.

### Steps to reproduce

Hit e, search biplane. Read subtext.

### Expected behaviour

"Fast and rather reliable."

**Comment by manmaed** [comment]
reported to mod @ https://github.com/Luke100000/ImmersiveAircraft/issues/69

**Comment by manmaed** [comment]
pack still has 5.1 installed  it was fixed as of 5.2 and  latest version is now  1.0.1

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
