### ISSUE TITLE
Wither Skull

### ISSUE THREAD

**Issue by QXT45** [FTBTeam/FTB-Modpack-Issues#3568]
### Modpack

FTB Horizons III

### Modpack version

1.10,0

### Describe the bug

I successfully defeated a wither using my sword, and as a result, it dropped its skull, which had the Nazi emblem on each side.

### Steps to reproduce

1. Get Beheading On A Sword
2. Kill a Wither
3. Have The Chance of Dropping Its Skull
4. The Skull Was Named Something Along The Lines of MHF_WitherSkull Head

### Expected behaviour

I wasn't planning on getting a Wither Skull I just wanted a Nether Star.

### Screenshots

I did not screenshot this but I did place it around a few times before it turned into a Steve skull just called "Head"

### Additional information

I'm not sure where else to put this as it is not a bug but I feature in the mod I assume.

**Comment by Gaz492** [comment]
Im not sure what would cause the head to specifically drop a head with that name, but the skin issue appears to have been fixed by mojang.
