### ISSUE TITLE
[Bug] Cardboard box on Compact Machine Block dosnt keep machine data

### ISSUE THREAD

**Issue by JustAnotherGhostName** [FTBTeam/FTB-Modpack-Issues#3571]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Log Files

None

### Describe the bug

A user reported after trying to move a compact machine with a mekanism cardboard box, that it clears the data for the compact machine (Ie, if you place it again and try to go in, it creates a new area in the compact machines dimension). Ideally the cardboard box doesn't work on the compact machine, or carries the data (though id assume the former to the ladder would be the solution used since its easier).

### Steps to reproduce

1. Create a compact machine and place it
2. Go inside the compact machine to init the area in the dim
3. Place something to make sure its a unique machine (or note the coords)
4. Leave the machine
5. Use cardboard box on the machine
6. Remove the cardboard box
7. Go inside the compact machine and observe that it is now a different location in the compact machine world

### Expected behaviour

Either disable interaction with cardboard boxes, or add support so you can transport them.

### Additional information

Shouldn't be skies specific, but I haven't tested on other packs.

**Comment by Saereth** [comment]
You can just pickaxe them to transport them...

**Comment by JustAnotherGhostName** [comment]
Correct, but the issue is thst it wipes the data. Need to double check with
the player if they did it on accident, but it shouldent be usable if it
wipes the data.
