### ISSUE TITLE
Direwolf20 1.19 - Intermittent lags and crashes due to ServerHangWatchdog

### ISSUE THREAD

**Issue by JHthe4** [FTBTeam/FTB-Modpack-Issues#3572]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.12.0

### Log Files

[crash-2023-06-24_15.32.46-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11860006/crash-2023-06-24_15.32.46-server.txt)
[crash-2023-06-24_15.37.04-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11860007/crash-2023-06-24_15.37.04-server.txt)
[crash-2023-06-25_14.16.57-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11860008/crash-2023-06-25_14.16.57-server.txt)
[crash-2023-06-25_14.22.58-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11860009/crash-2023-06-25_14.22.58-server.txt)
[crash-2023-06-24_14.31.09-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11860010/crash-2023-06-24_14.31.09-server.txt)
[crash-2023-06-24_15.25.08-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11860011/crash-2023-06-24_15.25.08-server.txt)

### Describe the bug

We're experiencing intermittent lag spikes and server crashes thanks to the ServerHangWatchdog on the newest version of the  Direwolf20 1.19 pack. The lag spikes happen concurrently for all players on the server, so we're sure that they're being caused by the server itself. Players report that the crashes seem to happen primarily when configurating Mekanism logistical transporters, but we're not sure as to the exact cause. We suspect that there must be a memory leak or a race condition somewhere that we haven't been able to locate. 

### Steps to reproduce

1. Start the server (we can provide world file if necessary)
2. Work with items in the mining dimension/configurate Mekanism transporters
3. Lag spikes intermittently
4. Wait for server to crash

### Expected behaviour

Server should ideally not crash, tick delay should not continue to increase

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9847839/808eb4f8-8994-4614-af35-1dd665cf0bb1)

### Additional information

The server is hosted on the Oracle Cloud Free Tier in the shape VM.Standard.A1.Flex with 4 OCPUs and 24GB RAM. Looking at the screenshot above, it seems like there's plenty of resources available. We can provide a lot more crash logs on request! Thanks!

**Comment by ukmcplyr** [comment]
Those crash logs aren't very informative unfortunately. You could try and increase `max-tick-time` in server.properties and that might be enough to stop the watchdog kills.

My 2p, feel free to disregard. OCI free is just not good enough for modded Minecraft. I have 8 of those 4/24 Ampere VMs that I was gifted and the numbers look awesome, but at the end of the day, they're shared systems (i.e. one host to *many* child VMs) and heavily overcommitted with limited network egress not suited to sending out ~100k per player per second.

**Comment by Saereth** [comment]
added some more debug tools for next update, please open a new issue with full debug.log if the issue persists. We've included fullstack watchdog mod now which should provide a lot more info if this happens again.
