### ISSUE TITLE
netherite dupe

### ISSUE THREAD

**Issue by debtlesspig7** [FTBTeam/FTB-Modpack-Issues#3575]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.1.0

### Log Files

NA

### Describe the bug

FTB Industrial Contraption: Roller, produces 2 netherite plates from 1 ingot, which can then be turned into 2 ingots with a smeltery or arc furnace

### Steps to reproduce

Roller, produces 2 netherite plates from 1 ingot, which can then be turned into 2 ingots with a smeltery or arc furnace

### Expected behaviour

to smelt to one ingot

### Screenshots

**Roller**
https://cdn.discordapp.com/attachments/1120472046858666075/1122873550181769347/2023-06-26_22.57.44.png
**Arc furnace**
https://cdn.discordapp.com/attachments/1120472046858666075/1122873579411877958/2023-06-26_22.58.19.png

**Comment by pikminman13** [comment]
fixed in dev
