### ISSUE TITLE
Metal empowerer quest locked

### ISSUE THREAD

**Issue by Peroloooo** [FTBTeam/FTB-Modpack-Issues#3576]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.1.1

### Describe the bug

I crafter the metal empowerer controller, but the quest for i didn't unlock so i can't submit the pieces.

The quest under the Overview tab completed correctly, the one under Reach For The Stars didn't

### Steps to reproduce

craft metal empowerer controller
collect reward from Overview quest
quest under Reach For The Stars doesn't unlock

### Expected behaviour

quest under Reach For The Stars unlocks

### Screenshots

![Overview](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137057017/284adfb4-db0d-409b-8f23-12f50591cf04)
![ReachForTheStars](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137057017/6ce85ac2-cb61-4b0e-a9ed-330ca17ce2b3)

**Comment by pikminman13** [comment]
this is not a bug. press the arrow on the quest for the metal empowerer to see that it requires another quest in "The Next Generation"
