### ISSUE TITLE
FTB Skies 1.2.1 - Apotheosis, Integrated Dynamics and Functional Storage

### ISSUE THREAD

**Issue by LustfulWanderer** [FTBTeam/FTB-Modpack-Issues#3578]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Built storage system using Integrated Dynamics, Integrated Tunnels, and Functional Storage Amory cabinet. Placed Apotheosis gems within and unable to take any of them back out. No other items are seem to be affected. Able to select them, but not remove them from storage to place into inventory. Any method of attempting to remove the gems with this storage set up will not work, creative, setting up an exporter from Integrated Tunnels etc. Attempting to place a singular gem into the inventory with right click will result in the number displaying a negative value.

### Steps to reproduce

using a logic cable, item interface, storage terminal, and armory cabinet. Link them all together and then place an Apotheosis Gem in the storage network created, then attempt to remove the gem. 

### Expected behaviour

To remove the gem and place it into my inventory

### Screenshots

![2023-06-26_20 44 41](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137854863/06c6505b-63c9-4db8-acb6-35f93d13542d)
![2023-06-26_20 50 00](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137854863/ac0ff23b-3153-4cbb-a783-32491ea53004)

**Comment by Saereth** [comment]
this is working as intended, armory crate isnt meant for automation
