### ISSUE TITLE
fluxial converter work in overworld

### ISSUE THREAD

**Issue by Fellal1** [FTBTeam/FTB-Modpack-Issues#3579]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.2.0

### Describe the bug

![화면 캡처 2023-06-27 140744](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/142fc79a-9a33-4bbd-a127-f49db8b000a1)

### Steps to reproduce

1. clear quest
2. throw capsule in overworld
3. use 

### Expected behaviour

bug

### Screenshots

![2023-06-27_13 53 36](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/a245312b-4ec9-4259-85f8-045f0315a4bb)

**Comment by pikminman13** [comment]
unfortunately i cannot enforce this from the looks of it
