### ISSUE TITLE
[Bug]: modlist for FTB University 1.16 displays incorrect version of ae2wtlib

### ISSUE THREAD

**Issue by Mari023** [FTBTeam/FTB-Modpack-Issues#358]
### Modpack

FTB University 1.16

### Modpack version

1.3.0

### Describe the bug

the [modlist](https://www.feed-the-beast.com/modpack/ftb_university_1_16) incorrectly shows the wrong version / modpage of ae2wtlib.
it shows [this 1.12 version](https://www.curseforge.com/minecraft/mc-mods/ae2wtlib), despite the pack being 1.16, and probably using [this version](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals-forge) which *is* 1.16, but made by another author.

### Steps to reproduce

Go to the modlist, and look for ae2wtlib, and see it indexing the wrong mod

### Expected behaviour

point to [this mod](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals-forge) instead

**Comment by aaronhowser1** [comment]
I'm not on the curator side, so I can't help with this bit

**Comment by Raidobw2** [comment]
Got you in to subscribe you for info, I think this would either be Jake or Sunekaer
