### ISSUE TITLE
solar panel can be placed overworld

### ISSUE THREAD

**Issue by Fellal1** [FTBTeam/FTB-Modpack-Issues#3580]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.2.0

### Describe the bug

![화면 캡처 2023-06-27 142111](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/1c39ef3f-455c-4641-8c71-57ddb404f197)

### Steps to reproduce

1. place cyclic mod placer
2. put on solar panel
3. change redstone mode always on

### Expected behaviour

bug

### Screenshots

![Honeycam 2023-06-27 14-19-30](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/4e50fdf8-07db-48f5-a727-d05f15674731)

**Comment by pikminman13** [comment]
i cant do anything about this unless i disable the placer
