### ISSUE TITLE
can't install upgrade on industrial foregoing machine

### ISSUE THREAD

**Issue by Fellal1** [FTBTeam/FTB-Modpack-Issues#3581]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.2.0

### Describe the bug

![화면 캡처 2023-06-27 142604](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/0c267498-fe27-4847-a072-85d4c90cbcc2)

### Steps to reproduce

1. make range tier or speed, processing, efficiency with carpenter
2. install to industrial foregoing machine
3. can't install

### Expected behaviour

bug

### Screenshots

![Honeycam 2023-06-27 14-20-03](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/b0524e4b-eb0d-4b8e-91d9-da0a8a096219)

**Comment by pikminman13** [comment]
i forgot to remove those carpenter recipes. removed for next update.
