### ISSUE TITLE
1.3.0 update

### ISSUE THREAD

**Issue by RaiTaki** [FTBTeam/FTB-Modpack-Issues#3584]
### Modpack

FTB Skies

### Modpack version

1.3.0

### Log Files

https://pste.ch/morewacabo.sql

### Describe the bug

It doesn't start

### Steps to reproduce

Just install the new version and start

### Expected behaviour

Starting normally

**Comment by RaiTaki** [comment]
Updating the Experience Obelisk mod fixed it.

https://www.curseforge.com/minecraft/mc-mods/experience-obelisk/files/4611584

**Comment by BrewingCoder** [comment]
Experiencing Same thing on Dedicated server.  Experience Obelisk 1.4.4 is broken for Dedicated Servers.  Need update to 1.4.5.

**Comment by BrewingCoder** [comment]
FYI the fact that this wasn't tested in dedicated server mode is disappointing

**Comment by Saereth** [comment]
> FYI the fact that this wasn't tested in dedicated server mode is disappointing

It was, .4.5 was set to ship with the pack but the mod didnt get pushed with the update, hotfix going out for it today
