### ISSUE TITLE
Masterful Machinery Mana Death Generator doesn't generate

### ISSUE THREAD

**Issue by Peroloooo** [FTBTeam/FTB-Modpack-Issues#3585]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.2.0

### Describe the bug

Input Blood + Milk + Molten Ender into the input ports, machine stays Idle.
I tried putting a mana pool / a mana spreader / nothing on the mana output port but it stays empty in all the cases.
what do?

### Steps to reproduce

1. build machine with capsule
2. insert blood
3. insert milk
4. insert molten ender (no  "Liquid Ender" in JEI)
5. no mana

### Expected behaviour

generate mana

**Comment by pikminman13** [comment]
is it the right milk?
