### ISSUE TITLE
can't make alchemy reactor core controller

### ISSUE THREAD

**Issue by Fellal1** [FTBTeam/FTB-Modpack-Issues#3587]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.2.0

### Describe the bug

no recipes

### Steps to reproduce

1. find alchemy reactor core controller
2. click r key

### Expected behaviour

no recipes

### Screenshots

![2023-06-27_19 49 16](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/2bebe932-9706-4570-aa3b-cac1df641bcf)

**Comment by pikminman13** [comment]
fixed in dev
