### ISSUE TITLE
[Bug]: Searching in Refined Storage wireless crafting grid randomly ends up with crash

### ISSUE THREAD

**Issue by ppozniak** [FTBTeam/FTB-Modpack-Issues#359]
### Modpack

FTB Ocean Block

### Modpack version

1.8 (but also previous versions)

### Log Files

[Error log file](https://pste.ch/sihubenaho.makefile)

### Describe the bug

Crash occurs **randomly** when using Refined Storage wireless crafting grid search.

### Steps to reproduce

1. Open wireless crafting for Refined Storage
2. Focus search 
3. Start typing

### Expected behaviour

No crash should occur

### Additional information

Not consistent so may be due to some external sources.

I was rolled back a few minutes back so I did the same exact step and a few times it crashed in the same exact moment.

**Comment by quietust** [comment]
This looks like it might be the exact same issue as #40 - Java itself is crashing inside `atio6axx.dll` (AMD OpenGL driver), and on the Java side it was trying to compile the Shader used by Draconic Evolution's modular chestpiece.,

**Comment by Raidobw2** [comment]
Yes the fix is contained inside what quietust linked. Closing as duplicate, issue 40 is pinned and will be fixed later on as Draconic Evolution updates, for now the workaround will fix it for AMD users.

Thank you for the report anyways, it's appreciated to get feedback from players.
