### ISSUE TITLE
not work neutron collector

### ISSUE THREAD

**Issue by Fellal1** [FTBTeam/FTB-Modpack-Issues#3591]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.2.0

### Describe the bug

not work neutron collector

### Steps to reproduce

1. make neutron collector
2. place
3. and just wait

### Expected behaviour

bug

### Screenshots

![화면 캡처 2023-06-28 044146](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83914598/3affb6a1-3d50-4ca5-9589-8cdade624891)

**Comment by pikminman13** [comment]
removed it and added a different recipe
