### ISSUE TITLE
ship from the beginning

### ISSUE THREAD

**Issue by Renank8** [FTBTeam/FTB-Modpack-Issues#3592]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

I had a world full of things and buildings I left the game and when I came back I was spawning only on the ship at the beginning and there was no way to enter the portal to go back to my world and I tried to collect backups and it always spawned on the ship

### Steps to reproduce

open the save and enter the world

### Expected behaviour

start in the world that I already build things

### Screenshots

![2023-06-27_15 46 10](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137942050/156508dd-b3f7-4735-8794-75edb065b7e3)
![2023-06-27_15 46 15](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137942050/e07202a5-a2b9-4803-8119-7b4cb3445a7b)
![2023-06-27_15 46 47](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137942050/058855d8-cd05-49ad-a302-7e8ee34d29c7)

**Comment by mlogan2k2** [comment]
I've seen this happen once myself.  The specific condition I made note of at the time was that I created and played the world in 'online' mode, and the error happened when I tried to play in 'offline' mode.
