### ISSUE TITLE
Unable to insert range addons into Industrial Foregoing Plant Gatherer

### ISSUE THREAD

**Issue by DontStarve72** [FTBTeam/FTB-Modpack-Issues#3595]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.2.0

### Describe the bug

I am unable to add range addons to the Plant Gatherer from Industrial Foregoring

### Steps to reproduce

1. Play a server for a few days with your friends
2. Place a Plant Gatherer
3. Attempt to insert "Addon: Range X" into the purple slots on the right
4. Observer that you're unable insert the item

### Expected behaviour

I'm able to add rango addons to the plant gatherer

### Additional information

I've verified that this doesn't happen when I'm on singleplayer, but I don't know if having cheats on, having creative mode, or for some reason the world being a flat land influences anything. We've tried disabling the FTBUtils claim on the chunk. Speed addons work fine.

**Comment by DontStarve72** [comment]
Using the carpenter recipe does not provide an insertable addon either

**Comment by AtlaasMs** [comment]
Try crafting the addon in a vanilla crafting table. I think that is what solved the problem for me.
