### ISSUE TITLE
FTB Skies Instance Crash

### ISSUE THREAD

**Issue by Realistiz** [FTBTeam/FTB-Modpack-Issues#3596]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Log Files

[debug-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11895790/debug-1.log.gz)
[2023-06-28-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11895793/2023-06-28-1.log.gz)

### Describe the bug

After downloading FTB Skies and click play, the instance crash

### Steps to reproduce

1. Download FTB Skies Modpack
2. Click Play
3. Loading
4. Instance Crash

### Expected behaviour

Instance Crash 100% of the time, even after using recommended Java Runtime and giving 8GB of RAM

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/138025401/6e9e895d-ce5d-4bf6-b092-a259aacce008)

**Comment by gabriel-meirax** [comment]
I'm having this problem too.

**Comment by Realistiz** [comment]
It hasn't been fixed in development. Please help I want to play this pack

**Comment by Realistiz** [comment]
Yo this ain't fixed dude. Why did you close it????
