### ISSUE TITLE
Can't craft lapis with lapis essense

### ISSUE THREAD

**Issue by bigdatajar** [FTBTeam/FTB-Modpack-Issues#3598]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.2.0

### Describe the bug

Lapis recipie using lapis essense doesn't exist

### Steps to reproduce

1.get lapis essense
2.try crafting lapis like other essense
3. Does not craft

### Expected behaviour

Lapis should be craftes

**Comment by pikminman13** [comment]
fixed in dev
