### ISSUE TITLE
[Suggestion]: Add Astral Sorcery ores to Industrial Foregoing laser output

### ISSUE THREAD

**Issue by JakeMoe** [FTBTeam/FTB-Modpack-Issues#360]
### Modpack

Direwolf20-1.16

### Mod suggestion

Was disappointed to find Astral Sorcery ores not listed in the Industrial Foregoing laser output (at least, not in JEI).  Looking into it, I found this thread on the Industrial Foregoing discussions page that seems to indicate that's for modpacks to add if desired.  I'd like to see the added if possible.  :-)  I'd suggest aquamarine would be whitelisted to ocean or river biomes, and rock crystal ore to be very rare (probably more so than diamonds & emeralds).

[Add astral sorcery crystals to laser drill output #1031](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/discussions/1031)

**Comment by Raidobw2** [comment]
In 1.13 you can now obtain aquamarine from all water biomes, including frozen ones (e.g. frozen river). You'll obtain them at an increased rate between y levels 60 and 70 with the laser drill. I've also added this change to the Environmental Tech Magical Ore Miner for parity. Have fun!
