### ISSUE TITLE
About update,will Re-download jre & JEI version

### ISSUE THREAD

**Issue by CreamCati** [FTBTeam/FTB-Modpack-Issues#3600]
### Modpack

FTB Presents Integration by Parts DX

### Is your suggestion related to a problem? Please describe.

When updating the package, the old jre directory will be deleted and downloaded again. But because it is downloaded from github, the use in mainland China is not successful every time. Can you change the update strategy, when jre exists, keep the original jre file
------Translated by Google

### Mod suggestion

The jei version is reduced to jei-1.16.5-7.7.1.153.jar, which will be convenient for some players in mainland China. This version can use the JEI pinyin search (jecharacters) function, and the latest version of jei cannot use pinyin search
------Translated by Google

**Comment by liuseniubi** [comment]
我也试了 jei-1.16.5-7.7.1.153 jecharacters-1.16.4-4.3.9，依旧不能拼音搜索（
