### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jebustino** [FTBTeam/FTB-Modpack-Issues#3605]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.3.0

### Describe the bug

So a couple days ago I had made mixed metal blend via tin, bronze and iron. Now I need more mixed metal blend but the recipe to make bronze that I used is gone. I'm just wondering if it is supposed to be gone. If it is then what is the easiest way to make bronze blend. Thanks

### Steps to reproduce

not sure I just play the game for fun

### Expected behaviour

A recipe that makes bronze blend from other dusts

**Comment by pikminman13** [comment]
alloys were never meant to be made before the super alloyer, that was a bug

you can crush bronze ingots back into dust im pretty sure
