### ISSUE TITLE
Apotheosis and Tetra not getting along

### ISSUE THREAD

**Issue by mlogan2k2** [FTBTeam/FTB-Modpack-Issues#3606]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

Any attempt to modify a bow via Tetra completely breaks compatibility with Apotheosis.  Apo treats the new weapon as a light weapon instead of a ranged weapon.  In a similar vein, upgrading parts using the Metal Expertise scroll or the forge hammer with Planar Stabilizer upgrades causes any weapon so modified to be treated as a pickaxe.

The bow upgrades break pre-existing Apotheosis upgrades, while weapon upgrades seem only to affect gems, keeping the affixes and related stats.  I've tested this in multiple playthroughs, starting from scratch each time, with cheats both enabled and disabled.  The particular material I'm using is forged steel, if that helps, but I've tried it with other materials (calorite, for one) with similar results.

Also, certain Tetra materials make items completely incapable of being modded with Apotheosis.  Nickel bow staves, for example.

### Steps to reproduce

Bows:
1: Make a standard bow (three sticks, three string.)
2: Modify the bow in a Tetra workstation.
3: Attempt to modify the bow with the Apotheosis reforging table and pay attention to the options

Weapons:
1: Make a sword.
2: Place the metal expertise scroll or use planar stabilizers on the forge hammer.  (Yes, I've tried using both at the same time.)  This is important - the process works as expected if you don't do this.
3: Modify the sword however you want.  My go-to is forged steel saber blade, end rod handle, dreamwood counterweight, pristine diamond socket, and either dragon sinew or end fiber wrap with no fuller reinforcement.
4: Attempt to modify the sword with the Apotheosis reforging table and pay attention to the options.

### Expected behaviour

Hoped for the ability to use both mods at the same time without issues.

### Screenshots

![bow1](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/138180852/ae978409-17f2-4b73-a155-2ee1f1b72d50)
![bow2](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/138180852/0da71a8c-6c0a-4922-8bc2-80b388a2c84d)
![bow3](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/138180852/e50f11d7-52ab-4651-8a19-82b31cc91b39)
![bow4](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/138180852/f5a6c3bc-5485-4caf-be10-cc6d3cdc5291)
![sword](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/138180852/caedc2d8-7654-481a-a81a-ddfd7110090c)

**Comment by Saereth** [comment]
this is some compat the two mod devs would have to address, I've mentioned it to shadows of fire but he didnt seem to keen to fix it on his end so not much we can do from the pack side of things
