### ISSUE TITLE
Nether Broken

### ISSUE THREAD

**Issue by Luckyludog** [FTBTeam/FTB-Modpack-Issues#3609]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Log Files

[2023-07-01-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11925229/2023-07-01-1.log.gz)

### Describe the bug

Nether portals don't return to island or even dimension island is in. TP to island coordinates returns to starting ship. Unable to access nether without losing home world. Reproduces when loading a backup instead. /ftbdim home doesn't work.

### Steps to reproduce

1. Enter nether portal into nether
2. Leave portal to return to overworld
3. Spawn in separate dimension at seemingly random coordinates.

### Expected behaviour

Return to dimension where my home island/base exists

### Additional information

Happened when I first started the pack. Loaded a backup and kept playing in overworld only. Decided after about a month of real time to check if it had been patched and it was exactly the same. Seems other reports match. Thanks

**Comment by Alistair1231** [comment]
Is the fix already in 1.1.0? Because I still encounter this.
