### ISSUE TITLE
[Bug]: Compacting drawers create sandstone instead of compressed sand

### ISSUE THREAD

**Issue by ecatherman** [FTBTeam/FTB-Modpack-Issues#361]
### Modpack

FTB Ocean Block

### Modpack version

1.9.0

### Describe the bug

compacting drawers from storage drawers do not allow sand and compressed sand. the drawers force either compact sand 1-2-3 or sand and sandstone.

to fix: add "rid:1x_compressed_sand, minecraft:sand, 9" to the compactingRules setting array in storagedrawers-common.toml

as explained here:
https://www.reddit.com/r/feedthebeast/comments/qc4v09/comment/hkjjkme/?utm_source=share&utm_medium=web2x&context=3

### Steps to reproduce

1. make a compacting drawer
2. attempt to put in sand -> get sand to sandstone
3. attempt to put in compressed sand -> get compressed sand 1-2-3

### Expected behaviour

put sand in the compacting drawer and get sand compressed - 1 and 2

**Comment by Raidobw2** [comment]
Hello. For now this is intended, refer to #263. I'll talk with the modpack dev next meeting about it.

Thanks for the suggestion and fix!
