### ISSUE TITLE
Ponder Errors

### ISSUE THREAD

**Issue by LandofHeros2234** [FTBTeam/FTB-Modpack-Issues#3610]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11925308/debug.log)

### Describe the bug

Mekanism Turbine and AE2 Controller ponders crash game in Ponder Index, and show message "Tooltip error see logs" when attempting to ponder from JEI whilst inventory is open.
Debug log provided

### Steps to reproduce

Try pondering the Mekanism Turbine or AE2 Controller

### Expected behaviour

Ponder scene opening

**Comment by Automatiax** [comment]
https://i.gyazo.com/9c3881d89b468cbbd6e4f7f0be42a935.mp4
