### ISSUE TITLE
JEI crash upon typing "pic"

### ISSUE THREAD

**Issue by CaptainTheta** [FTBTeam/FTB-Modpack-Issues#3611]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.3.0

### Log Files

https://pastebin.com/1nsJRNMi

### Describe the bug

Game seems to crash every time "pic" is typed into JEI. I was just trying to search for a pickaxe, but the crash is repeatable.

### Steps to reproduce

1. Open game
2. Wait for JEI to load
3. Type "pi" into JEI, business as usual
4. Type "c" into JEI
5. Game Crashes

### Expected behaviour

No crash

### Screenshots

![Screenshot 2023-07-01 151112](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/78312699/bdd6aed0-2aa9-416c-b849-65f01afd8ff2)

**Comment by pikminman13** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40
