### ISSUE TITLE
Village Temple Chest not handled by Lootr

### ISSUE THREAD

**Issue by SoraHjort** [FTBTeam/FTB-Modpack-Issues#3615]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Describe the bug

The chest that are under the podium in the Village Temples(?), have normal chests. These chests are also empty. 

This also affects the piglin village as well.

### Steps to reproduce

1. Find village that contains the tile for the village temple
2. look at the opening behind the podium to see the chest under it
3. chest is a normal chest and not a lootr chest. also contains nothing.

### Expected behaviour

Chest to be Lootr Chest and to Contain Loot

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/18604504/4b5b9fea-7e0b-4868-b399-dee3d4cf8101)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/18604504/cc7af969-df65-4841-beef-a6f5a883b046)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/18604504/947f17f2-213b-4957-874b-2ee2f26bce2e)

### Additional information

If this is supposed to be the chest linked to the Village Temple according to JEI, then considering this chest spawns things like Echo Shards and gem dust, it's somewhat annoying to not have them generate.

**Comment by Saereth** [comment]
that particular chest is not defined as a loot chest in the village so it spawns like that intentionally
