### ISSUE TITLE
stoneblock 3 world not responding while entering the world 

### ISSUE THREAD

**Issue by rabbites616** [FTBTeam/FTB-Modpack-Issues#3616]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11929232/latest.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11929233/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/11929235/debug.log)

### Describe the bug

I successfully played this world for 3-4 days but today I am not able to enter the world. when I open my world, I am able to finish the world loading process but stucks immediately as I join the world. After that, the game freezes and stops responding until I need to force shut it.

### Steps to reproduce

1.load game
2.open world
3. Finish loading and enters the world
4. Screen freeze
5.game stops responding

### Expected behaviour

I expect the world to open

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/86862802/0d6f4b89-aea0-4b8a-80c1-5389ebe4de62)

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
