### ISSUE TITLE
[Suggestion]: University 1.16 does not have a mekanism recipe for bone meal.

### ISSUE THREAD

**Issue by Atherum** [FTBTeam/FTB-Modpack-Issues#362]
### Modpack

FTB University 1.16

### Is your suggestion related to a problem? Please describe.

Wanted to automate bone mean production and discovered that Immersive Engineering is the only "high tech" mod that allows for production of bone meal. Mekanism does not have bone meal crushing as a recipe. While IE isn't too much of a hassle to set up, especially with mid-late game resources, it seems strange that such a basic recipe is excluded.

![image](https://user-images.githubusercontent.com/36828886/142797633-3b9abe46-19b9-4097-a9eb-19704fff8289.png)

**Comment by aaronhowser1** [comment]
Added
