### ISSUE TITLE
unstable quantum suit creative flight doesn't work

### ISSUE THREAD

**Issue by beepbopbeepboop** [FTBTeam/FTB-Modpack-Issues#3621]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.2.0

### Describe the bug

Tech Reborn quantum suit doesn't feature creative flight. Double tap is the same as a single tap, a boost up, but then gravity will crash you to the ground if space isn't repressed or held down.

### Steps to reproduce

double tap space

### Expected behaviour

creative flight

**Comment by beepbopbeepboop** [comment]
Sorry, fabric.

**Comment by UnRealDinnerbone** [comment]
Report to Author https://github.com/TechReborn/TechReborn/issues/3159

**Comment by jacktorrealba** [comment]
creative flight doesn't work for me either

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
