### ISSUE TITLE
Nether Mobs Spawn Issue

### ISSUE THREAD

**Issue by StraatLigMot** [FTBTeam/FTB-Modpack-Issues#3622]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Describe the bug

Building a mob farm using Dreadful Dirt does not spawn Nether Mobs such as Blazed, Wither Skeletons, etc.

Biome specific mobs do spawn Such as Piglins in the Nether Waste Biome. Bazalz in the Basalt Deltas. Etc

### Steps to reproduce

Build a Mob Farm using Dreadful dirt

### Expected behaviour

Blazes, Wither Skeletons to spawn

### Resolution 

Downgrading to Mob Grinding Utils 1.19.2-0.4.49 from 1.19.2-.0.4.50 fixes the issue.
Credits Seeroh for finding solution!

**Comment by 4shari** [comment]
Just want to add, i have the same problem. Despite the Questbook telling us it will work anywhere, it wont spawn any Witherskellies or Blazes with dreadful dirt in any Biome

**Comment by Seeroh** [comment]
After updating to 1.3.1 from 1.2.1 I am encountering this same issue. My Dreadful Dirt farm next to my nether portal used to spawn Nether Skeletons and Blazes, but now only spawns Piglins, Zombified Piglins, Endermen, Magma Cubes, and Ghasts.

**Comment by Seeroh** [comment]
Did some testing: downgrading to Mob Grinding Utils 1.19.2-0.4.49 from 1.19.2-.0.4.50 fixes the issue. Blazes and Wither Skeletons are spawning again.
