### ISSUE TITLE
unstable raw tin --grinder--> tin dust is missing

### ISSUE THREAD

**Issue by beepbopbeepboop** [FTBTeam/FTB-Modpack-Issues#3623]
### Modpack

FTB Unstable 1.20: Fabric

### Modpack version

1.2.0

### Describe the bug

The tech reborn wiki says there is a 2x raw tin into tin dust. I'm just coming up on 16 fusion coils, and an missing 2168 tin.  In ic2, they have a spin lava into copper and tin, which would be a way to get it, but tech reborn is missing that mechanic (they only do copper).

This isn't necessarily a bug, but if not, the tech reborn wiki needs updating.

### Steps to reproduce

Play, notice a very short tin supply.  I've been researching, and turtles and uumatter seem the only way  to get it, I could be wrong.

### Expected behaviour

more tin?

**Comment by beepbopbeepboop** [comment]
Ah, 4 turtles working overnight in 150x150 world spawn chunk in the mining dimension solved the underlying problem.

**Comment by UnRealDinnerbone** [comment]
Configs are default TechReborn make of a wiki issue
