### ISSUE TITLE
Blossom planks etc. missing.

### ISSUE THREAD

**Issue by NoOneCZ** [FTBTeam/FTB-Modpack-Issues#3625]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Describe the bug

While Blossom Saplings are available from the Market, their logs are not craftable into planks. Anything related to Blossom trees from Quark is not findable in JEI.trees

### Steps to reproduce

1. Build market
2. Buy any Blossom saplings
3. Plant and grow
4. Harvest 
5. Try to make planks

Or

1. Open inventory
2. Type Blossom or @quark into JEI
3. 

### Expected behaviour

Possability to craft planks from trees, Appearence of Blossom tree related items in JEI

### Screenshots

![FTB Skies 03 07 2023 19_37_36](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/39586891/dca21d33-b874-4942-aef2-7e2d2a696f19)

**Comment by Adtrl** [comment]
I'm having this problem too.

Same with Otherworld logs>Planks.
