### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jebustino** [FTBTeam/FTB-Modpack-Issues#3628]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.3.0

### Describe the bug

Why don't energy cables from Powah work with the machines from ftb industrial contraptions. Is this a bug.

### Steps to reproduce

.

### Expected behaviour

I expect the Powah cables to be able to feed energy to the industrial contraptions macines like the roller and the macerator for example.

**Comment by pikminman13** [comment]
FTBIC machines do not accept RF/FE power. this is not a bug.

**Comment by Jebustino** [comment]
What does that mean

**Comment by Jebustino** [comment]
Is there a way to convert FE/RF to energy used by FTBIC?
