### ISSUE TITLE
[Suggestion]: Please add a recipe for compact machine tunnels. 

### ISSUE THREAD

**Issue by Electrofried** [FTBTeam/FTB-Modpack-Issues#363]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

Right now they are uncreatable but functional. I understand the dev is working on adding some features to the tunnels and they will regain more functions if/when the mod updates, but for now they are working even though the recipe is disabled so I can not see a reason why a recipe could not be added to them for this pack.

**Comment by Sunekaer** [comment]
Hi 
We didn't remove the recipes, the mod dev has not added the recipe as the tunnels aren't ready yet.
We wont be adding recipes as the tunnels arent ready.

**Comment by Electrofried** [comment]
Perhaps you did not take the time to read my issue completely but I did not say you removed the recipes. I specifically stated that the tunnels are working, if you want you can go and look at the devs github for confirmation and the tunnels API is already in place and tunnel item transfer is working. 
The dev simply has not added a recipe because **all** features (fluids, energy, nested connection etc.) are not implemented. I have added a recipe on my server for this pack and made use of tunnels extensively without any issues, however I understand if you make the decision not to make this available to all players of the pack for your own reasons.
