### ISSUE TITLE
Neromantic Prime will not spawn oil.

### ISSUE THREAD

**Issue by memester420** [FTBTeam/FTB-Modpack-Issues#3630]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.2.0

### Describe the bug

You misspelled petroleum on line 672 of the astral sorcery server config file so there's no oil veins in the world.

### Steps to reproduce

1. Go to ~/defaultconfigs/astralsorcery.toml
2. Go to line 672
3. See it says "immersivepetrolium:oil;2500000;125000;500".

or

1. Go ingame.
2. Pull out the Ichosic Resonator.
3. See there's no oil.

### Expected behaviour

It should say "immersivepetroleum:oil;2500000;125000;500"

### Additional information

I don't know if I'm supposed to report here or mention you on discord.

**Comment by pikminman13** [comment]
alright, fixed in dev
