### ISSUE TITLE
Sodium and Iris Support

### ISSUE THREAD

**Issue by SniketTheLlama** [FTBTeam/FTB-Modpack-Issues#3633]
### Modpack

FTB Unstable 1.20: Fabric

### Is your suggestion related to a problem? Please describe.

I tried to add Sodium and Iris myself to the modpack and it crashed. I had originally added only Iris. It got to the main menu and said that Iris didn't load because I didn't have Sodium. I downloaded and added it, now it won't load at all. I disabled both and it loads find.

### Mod suggestion

Iris and Sodium so players can use shader packs.

**Comment by UnRealDinnerbone** [comment]
Sorry, we don't provide supported for adding mods to our packs

**Comment by honbee** [comment]
made an account to tell you that this is, respectfully, lame as hell

regardless, i am able to add some mods to the packs with no problems. it was specifically iris and sodium that were not functional
