### ISSUE TITLE
Vanilla+ pack will not run

### ISSUE THREAD

**Issue by logicbug** [FTBTeam/FTB-Modpack-Issues#3635]
### Modpack

FTB Vanilla+

### Modpack version

1.1.0

### Describe the bug

Modpack does not start, seems like a problem with dependencies of codechicken?

### Steps to reproduce

Install vanilla+ pack
Go to instance
Start
- fails

### Expected behaviour

Normal start

### Additional information

I have no idea what to expect as in what this pack offers, never tried it before.

**Comment by Gaz492** [comment]
This looks to be the same issue as #756 we may release a fix for this providing nothing else breaks by updating the mod mentioned in that issue.

**Comment by Gaz492** [comment]
Duplicate of #3635

See https://github.com/FTBTeam/FTB-Modpack-Issues/issues/756#issuecomment-1120337810 for possible fix
