### ISSUE TITLE
Cannot Load Direwolf 20 1.19 saved games or start new save

### ISSUE THREAD

**Issue by jeddell** [FTBTeam/FTB-Modpack-Issues#3637]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.12.0

### Log Files

https://pastebin.com/TyT51pgX

### Describe the bug

After loading the FTB Launcher and then starting the Direwolf20 Modpack. The game stops loading any saved game. I tried all of my backups and tried starting a new game. All with the same result.

### Steps to reproduce

1. Launch  the FTB Launcher.
2. Click play on the Direwolf20 1.19 modpack loaded to my PC
3. When  the spash screen opens, click on single player
4. click on my saved game
5. Game crashes with errors in the console

Alternatively 
Repeat steps 1 and 2
3. Create a new game
4. Game crashes with et he same errors in  the console.

### Expected behaviour

My saved game to load

**Comment by manmaed** [comment]
try removing the Mekanism/generator-storage.toml file and see  if that makes it work

**Comment by jeddell** [comment]
I went a little more drastic than that. I backed up my world, uninstalled the modpack and re-installed it. Figured it had something to do with the modpack when i could even start a new world. Must have had a corrupted file somewhere, possibly the Toml file.

Lost a little progress, but I'm back up and running now. (as he sighs a sigh of relief)
