### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by Jebustino** [FTBTeam/FTB-Modpack-Issues#3639]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.3.0

### Describe the bug

I am trying to make an infused block of redstonium on the pedestal from better end forge. I have everything setup right and it isn't working. I have waited the entire 400 ticks or seconds and have tried removing and re-adding all the required blocks in different orders and rotating them around the centre-piece too. Is this a bug or am I missing something? I know my pedestal works because it worked with the seeds I infused.

### Steps to reproduce

Not sure

### Expected behaviour

I expect the recipe to function as is seen in the J.E.I

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/138139614/8f9b13d4-95de-4e64-bbe1-34541f679bf5)
![Bug](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/138139614/ed767300-59e1-41ca-a35c-39b048a14615)

**Comment by pikminman13** [comment]
it looks like youre facing the recipe south, based on the way your minimap and the biomes are oriented. it needs to face north, hence the compass on the recipe

**Comment by Jebustino** [comment]
Ok thank you very much
