### ISSUE TITLE
[Bug]: Crash when loading world. Failed loading config file integratedterminals-server.toml

### ISSUE THREAD

**Issue by dominiccarrington** [FTBTeam/FTB-Modpack-Issues#364]
### Modpack

FTB Oceanblock

### Modpack version

1.9.0

### Log Files

Full Log: https://pastebin.com/J8FzWE4A
Debug [After world starts to load otherwise it's 20000 lines]: https://pastebin.com/FPgDKjiB
Crash Log: https://pastebin.com/ZvPtbNJ5

### Describe the bug

When trying to load an existing world, `net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file integratedterminals-server.toml of type SERVER for modid integratedterminals` is raised and Minecraft crashes having to be closed via Task Manager. 
This file exists in the world/serverconfig folder and I created it in the config folder to double check. 

### Steps to reproduce

Unknown. 
Updated to version 1.9.0 yesterday and was able to play on my world. Tried loading the world a couple of hours later and Minecraft was freezing on load.

### Expected behaviour

The world to load correctly.

**Comment by Raidobw2** [comment]
Hmm. I've seen the bug once or twice, but unsure what causes it, be it an update or a crash.

1. Backup your world by copy-pasting it elsewhere.
2. Wipe the contents of the `saves/world/serverconfig` folder.
3. Take the contents of `defaultconfigs` and copy them into `saves/world/serverconfig`.
4. If your keyboard is special compared to the English language, put this in your JVM arguments: `-Duser.country=US -Duser.language=en`. Please let us know if that's the case, example: a Turkish keyboard.
5. Load up the modpack and try to start your world. If everything works fine, awesome.

Although I'd be still unsure what would cause that, so if you have any other information or how that config file looked (empty or weird chars), then feel free to add it here.

Thanks in advance, and I hope this works out!

**Comment by dominiccarrington** [comment]
Thanks for your response, I'll try regenerating the serverconfigs this evening.

I am using a standard English UK keyboard.

The config file just has a single character in it (0x0000). The same is true for a few other serverconfig files (e.g. simplyjetpacks, integratedtunnels, integrateddynamics, SeedDrop).

**Comment by dominiccarrington** [comment]
Regenerating the serverconfigs has worked.

The normal integratedterminals-server.toml file, by the way, is just a blank file with a new line in it (Contents: 0x0D0A)

Thank you for your help @Raidobw2

**Comment by Sunekaer** [comment]
We dont ship that server config file, so if its blank its because something went wrong when the files was generated.
