### ISSUE TITLE
FTB Skies loading crash

### ISSUE THREAD

**Issue by SaltyBoi15913** [FTBTeam/FTB-Modpack-Issues#3640]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Log Files

https://pastebin.com/PmbAJdDa

### Describe the bug

Crashes when trying to load into my world.

### Steps to reproduce

1. Load up FTB Skies
2. Load into a world

### Expected behaviour

To load in to the world normally.

### Additional information

This has been an issue on FTB Skies and Stoneblock 3. The modpack works just fine the first time its loaded up. After that any attempt to load into my world results in a crash. Ive tried deleting the instance and reinstalling it.

**Comment by Saereth** [comment]
you have corrupt configs, reinstall the packs/scan your harddrive for errors
