### ISSUE TITLE
SkyOdyssey Bonsai EMC flowers not producing promised amount

### ISSUE THREAD

**Issue by StephJ2Fan** [FTBTeam/FTB-Modpack-Issues#3641]
### Modpack

FTB Sky Odyssey

### Modpack version

1.42

### Describe the bug

The ProjectEx Bonsai Power Flowers do not give the amount described. I currently have a MK3 Bonsai Power flower which is supposed to be producing 1024 emc/ per second. It's only producing 204 emc/s. And it doesn't matter how many i have placed down. Whether 1 or 24. it's still only producing 204 emc / second.

### Steps to reproduce

Place down power flower
Check what's producced compared to what is said to being produced per item.

### Expected behaviour

producing 1024 emc/s

**Comment by Gaz492** [comment]
It looks like it's generating the correct amount of emc, it's just the +204/s that's incorrect.
Due to the age of the pack and mod, this display bug will not be fixed.
