### ISSUE TITLE
Update Create to v5.1

### ISSUE THREAD

**Issue by NotTheNobleSavage** [FTBTeam/FTB-Modpack-Issues#3644]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

Create has recived a major update to version 5.1, this adds a bunch of new features to the game as well as changing some current features. This would be a good update and would add some crazy more machines with better textures

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/create/files?version=1.18.2

**Comment by UnRealDinnerbone** [comment]
same as #3736
