### ISSUE TITLE
IE Squeezer Capsule not correctly formatted

### ISSUE THREAD

**Issue by stumpertwo** [FTBTeam/FTB-Modpack-Issues#3647]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.4.0

### Describe the bug

The Capsule for the Immersive Engineering Squeezer, claimed from the Capsule Corp. Squeezer quest, does not create the correct multiblock. One of the barrels is misplaced. The barrel is supposed to go in the middle of the 2nd layer and is inbetween the redstone engineering block and light engineering block. 

### Steps to reproduce

1. Claim Squeezer Capsule Reward
2. Fill with correct contents
3. Deploy or visualize - the improper schematic will still show

### Expected behaviour

fix the capsule schematic

### Screenshots

the highlighted barrel should be in the middle under the piston
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/139035633/654445a9-d4f5-4881-9d11-fcb85dd60437)

**Comment by pikminman13** [comment]
fixed on dev
