### ISSUE TITLE
[Suggestion]: Add Dragon's Breath Recipe

### ISSUE THREAD

**Issue by MisterZam** [FTBTeam/FTB-Modpack-Issues#365]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

Can we have a mystical agriculture custom recipe for dragon's breath? Its for automating the halitosis generator. Hope this gets approved

**Comment by quietust** [comment]
Maybe a combination of Dragon essence (which otherwise only makes Dragon eggs) and Air essence (which otherwise has no uses at all)?

**Comment by Raidobw2** [comment]
Linked/Reopen of #280. We'll look into it again, thanks for the suggestions.
