### ISSUE TITLE
cannot craft Level:0 syringes

### ISSUE THREAD

**Issue by Redon4200** [FTBTeam/FTB-Modpack-Issues#3650]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.3.0

### Describe the bug

Im trying to make a spawner and i can't make a Level:0 syringe. I can only make a Level:100 syringe and i have tried to use it but it doesnt work.

### Steps to reproduce

i dont know

### Expected behaviour

I expect that the spawner works

**Comment by PinkieIcePie** [comment]
Just tested this:
> Created empty syringe (Red colored icon)
> Hit (not right-click) an entity (I used pig)
> Syringe turns grey and level drops to 10 (from 100).
> Add syringe to spawner (it needs power too)

Something happens but server crashed before I could see.

**Comment by DinnerBeef** [comment]
Mod Issues See: https://github.com/McJtyMods/RFToolsUtility/issues/185

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
