### ISSUE TITLE
Team managing

### ISSUE THREAD

**Issue by matevzbirk** [FTBTeam/FTB-Modpack-Issues#3651]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

ftb unstable 1.20 /1.2

### Log Files

When trying to invite a friend to a group and them clicking accept we get an error:
An unexpected error accured trying to execute that command.

### Describe the bug

An unexpected error accured trying to execute that command.

### Steps to reproduce

team manager
create a party
invite a friend
have them click accept

### Expected behaviour

get into a team.

### Additional information

not server owner but can provide further data of report if needed

**Comment by PinkieIcePie** [comment]
I found a workaround with this is to invite them to the team, then open the team config file on the server (InstDir\world\ftbteams\party\partyGUID.snbt) 
Notepad works fine :)

Scroll down and find the ranks: section. 
The GUIDs used here should match the player GUIDs in the ftbteams\player folder.

Where you have 'Invited' change to member or officer, save the file and reload the server (stop/start etc)

When you next open the FTBTeams gui, your friends should now be listed correctly :)

**Comment by manmaed** [comment]
can you update to 1.3.0 to confirm if this has been fixed
