### ISSUE TITLE
Crushed silver ore doesn't smelt into silver ingot

### ISSUE THREAD

**Issue by lifeinaglasshouse** [FTBTeam/FTB-Modpack-Issues#3655]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.12.0

### Log Files

https://pste.ch/filiqaxeca.coffeescript

### Describe the bug

Create crushed silver ore doesn't have any recipe. You can't smelt it and have no use.

### Steps to reproduce

1. Get crushed silver ore
2. Smelt it in furnace
3. nothing happen

### Expected behaviour

crushed silver ore smelted to silver ingot

### Additional information

Based on the error log, other item probably have the same problem as this

**Comment by lifeinaglasshouse** [comment]
I cannot confirm if this issue still present since I already stop playing the modpack.

**Comment by Gaz492** [comment]
Ok no problem, this looks to have been fixed in the latest version from a quick test.
