### ISSUE TITLE
Server Crash on Enderman taking a block

### ISSUE THREAD

**Issue by PinkieIcePie** [FTBTeam/FTB-Modpack-Issues#3656]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.3.0

### Log Files

https://pastebin.com/fCFBbAKR

### Describe the bug

Server crash caused by enderman trying to take block from a protected region (Using FTBTeams and FTBChunks)

### Steps to reproduce

1. Protect a chunk (with FTBTeams)
2. Allow Enderman to attempt the theft of your protected block (while "ftbchunks:allow_mob_griefing": 0b for protected regions)
3.  Server Crashes with: Exception caught during firing event: Attempted to call Event#setCanceled() on a non-cancelable event of type: net.minecraftforge.event.entity.EntityMobGriefingEvent

### Expected behaviour

Enderman cannot take block and goes away from protected regions.

### Additional information

Did not occur on previous version (1.2.0).

Can be temporarily worked around by changing difficulty to Peaceful and therefore preventing any mob spawns.
Can also be worked around by enabling mobGriefing in the protected region.

**Comment by WeepingAngel256** [comment]
This was a huge help, thanks!

**Comment by manmaed** [comment]
Fixed in 1.4.0

**Comment by bigclap** [comment]
reproduced on 1.19.9 
[crash-2024-06-24_18.39.57-server.txt](https://github.com/user-attachments/files/15960049/crash-2024-06-24_18.39.57-server.txt)
