### ISSUE TITLE
Unstable Mod Request

### ISSUE THREAD

**Issue by PinkieIcePie** [FTBTeam/FTB-Modpack-Issues#3657]
### Modpack

FTB Unstable 1.20: Forge

### Mod suggestion

Add the following mods:

Patchouli - Adding this mod will allow some other mods to show their in-game documentation a lot easier.
https://www.curseforge.com/minecraft/mc-mods/patchouli

CraftTweaker - Allows server owners to tweak recipes to fit the game better, for example, the Ultimate Car Mod adds canola cake, which can only be composted according to REI. This could be adjusted wioth CT for players to be able to use it in another way, for example, Canola Cake could be cooked in a furnace to become charcoal or something similar. It would also allow the modpack to hide doors from the Dramatic Doors mod that are un-craftable with the current mod setup. 
https://www.curseforge.com/minecraft/mc-mods/crafttweaker

Thank you :)

**Comment by MisterZam** [comment]
Polymorph - allows you to craft the other item with the same crafting recipe like crafting table on a stick. It allows you to pick either from cyclic or the crafting on a stick item. 

https://www.curseforge.com/minecraft/mc-mods/polymorph

**Comment by DinnerBeef** [comment]
Thanks for the suggestions. All of these will be added in the next update, beside CraftTweeker. However, If there are any issues with an item not being craftable that you think should, please open another issue so that issue can be report to the mod dev if need be.

**Comment by manmaed** [comment]
Fixed in 1.4.0
