### ISSUE TITLE
Direwolf20 - Apotheosis - Crash upon hovering the cursor over the Nature's Blessing enchanted books

### ISSUE THREAD

**Issue by Tudor-Sandru** [FTBTeam/FTB-Modpack-Issues#3659]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.12.0

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12005063/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12005064/latest.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12005065/console.log)

### Describe the bug

After activating creative game mode in a newly created world and attempting to hover the mouse cursor over the Apotheosis - Nature's blessing Enchanted Books in the creative inventory, a crash is occurring.

### Steps to reproduce

1. Create a new world (on survival mode with allowed cheats)
2. Enter that newly created world
3. Activate creative game mode
4. Open the creative inventory
5. Search for the Nature's Blessing Enchanted Books from the Apotheosis mod
6. Attempt to move the mouse cursor to any of the displayed enchanted books 

### Expected behaviour

A description of the hovered item should be displayed

### Screenshots

![crash](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/61461335/8d9da0e2-0ba2-4f11-86d9-eee02a35f83e)

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
