### ISSUE TITLE
[Bug]: NoSuchFieldError

### ISSUE THREAD

**Issue by happymoep** [FTBTeam/FTB-Modpack-Issues#366]
### Modpack

FTB Sky Odyssey

### Modpack version

1.3.0

### Log Files

https://www.toptal.com/developers/hastebin/adokefeyac.md

### Describe the bug

Placing down a "Plate Bending Machine" from "Tech Reborn" crashes the game

### Steps to reproduce

Open any world
Place down "Plate Bending Machine" from "Tech Reborn" 

### Expected behaviour

-

### Additional information

Removing the Block via MCEdit Unified appears to undo the damage.

**Comment by Raidobw2** [comment]
Thanks for the report, we'll look at this when development resumes for that modpack! For now, avoid using the machine or feel free to update the mod and try to place the machine in a new singleplayer world

**Comment by TheonlyTazz** [comment]
Cannot replicate in latest in-dev, please try again once new update gets released
