### ISSUE TITLE
machines from thermal series do not show fluid amount in gui

### ISSUE THREAD

**Issue by helkin-jurgles** [FTBTeam/FTB-Modpack-Issues#3667]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.4.0

### Describe the bug

thermal machines like the fluid tank and arboreal extractor do not show the fluid amount while hovering over the liquid. this makes getting to know the amount of fluid in a fluid tank difficult as waila too doesn't show the amount.the only way to see the amount in a fluid tank in this case is too pick it up which can be difficult to do in certain places

### Steps to reproduce

place down a fluid tank from thermal series. 
fill it up with a liquid 
hover over the liquid and it dosnt show the liquid in my case

### Expected behaviour

it show show the amount of liquid when hovering with the mouse

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/133527819/d8141f36-96bf-487c-814c-514b2d97fb24)

**Comment by helkin-jurgles** [comment]
not 100% sure but could be part of the bug where pop up gui elemnts are shifted to top right corner for some machines

**Comment by pikminman13** [comment]
finally fixed. downgraded a mod.
