### ISSUE TITLE
Adding Additional Bosses

### ISSUE THREAD

**Issue by PraseodymiumSpike** [FTBTeam/FTB-Modpack-Issues#3668]
### Modpack

FTB Unstable 1.20: Forge

### Is your suggestion related to a problem? Please describe.

While many Mods give the Player more power or make things easier for the Player, this is rarely counterbalanced by new and interesting challenges such as new Boss Mobs. I think this modpack may suffer from this problem due to tiers higher than vanilla Netherite being available, and it would be helpful to add a Mod to counterbalance this with Boss Mobs.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm

This Mod adds well-made Boss Mobs and has plans to add more in the future.

**Comment by PraseodymiumSpike** [comment]
The Twilight Forest is updated, too, but most of its Bosses don't provide a major challenge against a Player with endgame gear. It may be possible to change this through configuration files, though.

**Comment by DinnerBeef** [comment]
Thanks for the suggestions. Both of these will be added in the next update.
