### ISSUE TITLE
Crash When Removing Items From Refined Storage Crafting Grid

### ISSUE THREAD

**Issue by davegilpin** [FTBTeam/FTB-Modpack-Issues#3669]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.3.0

### Log Files

[crash-2023-07-12_22.36.52-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12034845/crash-2023-07-12_22.36.52-client.txt)

### Describe the bug

When removing items from the Refined Storage Crafting Grid, the game crashes.

### Steps to reproduce

1. Click on items in Refined Storage Crafting Grid.

### Expected behaviour

The items should be removed from Refined Storage.

**Comment by PinkieIcePie** [comment]
Looks to be a bug with REI and Refined Storage. 

Workaround is possible by swapping out REI for JEI 
Already reported here #3660

**Comment by davegilpin** [comment]
Thanks
