### ISSUE TITLE
[Bug]: Pack crashes every couple hours, or when too many people are on.

### ISSUE THREAD

**Issue by Paladinine** [FTBTeam/FTB-Modpack-Issues#367]
### Modpack

FTB Oceanblock

### Modpack version

1.8

### Log Files

[crash-2021-11-22_21.33.13-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7584623/crash-2021-11-22_21.33.13-server.txt
[crash-2021-11-22_16.47.42-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7584624/crash-2021-11-22_16.47.42-server.txt)
)

### Describe the bug

Server is crashing, not sure what is causing the crash. I've attached the last two crash logs, both from today.

### Steps to reproduce

I can't really tell, that's part of my issue.

### Expected behaviour

Server not crashing.

**Comment by Raidobw2** [comment]
Hello, please see #211.
Basically:
- Are you using an online host?
- Did setting `max-tick-time=-1` in `server.properties` solve the issues?
- Did you speak with your host to know if the CPU had been experiencing stress when crashes occur?

I've concluded that the source of that error might be lag, since other people who experienced the issue were using online hosts which sometimes can have huge lag spikes.
Please let me know any information regarding my above questions,
Thank you

**Comment by Paladinine** [comment]
I am using an online host, PebbleHost.

I tried setting the max-tick to -1, and from what I can see all that change did is make the server just hang instead of crashing.

I have also attached an image of the resource usage from when the latest crash.

![resourceusage](https://user-images.githubusercontent.com/15878126/143089613-20f91178-288e-4b31-9148-9015b0ba963e.png)

**Comment by Raidobw2** [comment]
If the crash/lag happened at the start of that graph, I would believe it to be normal behaviour. Looks like that was a ~20second huge lag spike, then the server continued doing its work like usual.

If this was a continuous source of lag, this would be problematic and on our side.

But in that case we can't replicate the issue, and from the info you gave me it just sounds like the CPU of the node got stressed. I've myself been using hosts, and had the same issue at times, their CPU isn't 100% reliable at all times and that's to be expected.

If you keep getting lag spikes, I'd recommend you contact them and ask them to move your server to a new fresh node, sometimes they get saturated from too many users, especially if you're running a budget plan which normally shares CPU resources with other customers (not dedicated).

It's not something we can fix in the modpack, so I'll be closing this as a result.
