### ISSUE TITLE
Using Auto Smithing Table to Upgrade Backpack to Netherite Tier causes item loss

### ISSUE THREAD

**Issue by techno156** [FTBTeam/FTB-Modpack-Issues#3670]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Describe the bug

Using the Auto Smithing Table to upgrade a "Sophisticated Backpacks" backpack to Netherite tier results in a blank netherite-tier backpack, causing the total loss of all items inside.

### Steps to reproduce

1. Place and Power Auto Smithing Table
2. Insert Diamond-tier Sophisticated Backpack (with items inside), and one netherite ingot
3. Backpack is replaced with netherite-tier backpack, causing items to disappear

### Expected behaviour

Items and upgrades should be preserved when upgrading a backpack.

### Additional information

A similar issue has occurred before in #3361, where upgrading a backpack to netherite also resulted in the items being deleted. It is possible that these issues may be related.

Another possible related issue is #3514, where the backpack was also reset, causing item loss, but due to a custom recipe. As this is a modded machine, and not vanilla, there may be a similar issue at play.

**Comment by Saereth** [comment]
reported to dev and added a warning on the tooltip for now
