### ISSUE TITLE
Cyclic Beheading enchantment does not work on Baby Wither Skeletons

### ISSUE THREAD

**Issue by lord-ne** [FTBTeam/FTB-Modpack-Issues#3672]
### Modpack

FTB Presents Integration by Parts DX

### Is your suggestion related to a problem? Please describe.

The Beheading enchantment from Cyclic does not work on Baby Wither Skeletons from Mekanism. (In contrast, the Severing modifier from Tinker's Construct does work properly, dropping Wither Skeleton skulls).

This can probably be fixed by adding Baby Wither Skeletons to the beheading list in the Cyclic config file (although I'm not sure what kubejs wizardry is being done to automatically convert the MHF heads into regular mob heads).

**Comment by pikminman13** [comment]
tried what i could, couldnt get them to drop anything let alone wither skulls
