### ISSUE TITLE
Mining Gadgets (or maybe not?) InvocationTargetException Weirdness

### ISSUE THREAD

**Issue by cyanidearsenic** [FTBTeam/FTB-Modpack-Issues#3674]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.1

### Log Files

Original crash: https://pastebin.com/mkyJaL8h
When I tried removing Mining Gadgets just to see: https://pastebin.com/UJwdaVDQ
When I tried just throwing all the mods back in to see if it was just that dependency I was missing: https://pastebin.com/uFjKL24m
When I tried throwing all the mods back in, except Mining Gadgets: https://pastebin.com/s6spLdjW

### Describe the bug

So, I wanted to add some decoration focused mods for some things I was building in Stoneblock 3, but I got over-excited by the options and put a bunch of mods in at once. Predictably, the game would not launch, but I realized I'd missed a dependency.
So I added the dependency and tried to launch it, but no such luck.
So I took them all back out and tried launching what, I think, should have been the original modpack mod list (minus the chat emoji one and minetogether which I'd taken out when I first got the pack and had played without already, so it should work without them). But it gave me the Mining Gadgets error in the first screenshot.
So I tried disabling Mining Gadgets, and got a CoFH_Core error (see the second screenshot). 
So I tried throwing all the mods in and launching it with all the mods I added and not Mining Gadgets (because I was getting frustrated) and got the same CoFH_Core error as before.
I tried looking up the Mining Gadget one (first screenshot, first pastebin) but none of the solutions I saw worked (they called for deleting a server.toml for a mod I don't have and wasn't the issue in mine; they called for changing the Java arguments but my permgen and minimum memory were already there, my max memory was higher, and I couldn't tell it to use the server.jar thing because I'm not running a server? It's just singleplayer?; use Forge version 41.I-don't-remember-the-rest or lower, I am already using a lower version than the point they said, tried the version they said anyway, no luck, etc.)
Oh, pastes are just the latest log files because it hasn't been generating crash reports since it hasn't been crashing really.

### Steps to reproduce

1. Get Stoneblock 3, remove MineTogether and whatever the emoji mod thing is called, play for a while
2. Add Quark because you super miss the chest sorting buttons. Play for a while more.
3. Decide to try adding some decoration mods for my build. Get over-excited by all the interesting options and add, like, 15 mods in one go. Remember that is a dumb thing to do after it crashes.
4. Remove the added mods and try launching. Mining Gadgets error screen.
5. Remove Mining Gadgets to see if it's suddenly broken. CoFH_Core error screen.

### Expected behaviour

Launch the game as normal when I'd taken all the mods I'd added back out.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/12106286/aefeb0a9-155c-481c-a473-a7c1f213ed5e)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/12106286/51d3f3ad-6a37-4bd5-ada1-c315409cfb52)

**Comment by cyanidearsenic** [comment]
Oh dang, I just realised it was creating crash logs (hence the crash log button, it just wasn't showing up at the top of the list of crash logs in my launcher.
Here are the two logs mentioned in the screenshots:
Mining Gadgets screenshot: https://pastebin.com/VQ0UMMKV
CoFH_Core screenshot: https://pastebin.com/ZDa11dgy

**Comment by cyanidearsenic** [comment]
I tried reinstalling the pack separately again, and it won't launch either, but the error I'm getting is


    CoFH Core (cofh_core) encountered an error during the common_setup event phase
    com.electronwill.nightconfig.core.io.ParsingException: Not enough data available


This should be the pack exactly as I played it the first time (the normal pack minus minetogether and emojiful) and, again, it worked for the first use and then won't open on subsequent launches. I looked up the error and tried what was suggested up to and including deleting the entire config file and making it regenerate it, but it didn't work still.

Crash Log: https://pastebin.com/yRRWhuj1
Latest.log: https://pastebin.com/6MUMAppF

**Comment by UnRealDinnerbone** [comment]
We do not support modifying pack, that issues have to with configs remove all Cofh Configs
