### ISSUE TITLE
Villager breeding doesnt work

### ISSUE THREAD

**Issue by imadethistomakeaquestion** [FTBTeam/FTB-Modpack-Issues#3675]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.5,0

### Describe the bug

I made a server in the 1.4.0 version of the mod, not even there villager breeding worked, they just stare at the food and dont pick it up
i tested in in creative with a newly spawned villager and nothing

### Steps to reproduce

1.Give food to villager
2.Villager doesnt pick up food
3.Villager doesnt breed

### Expected behaviour

Villager should pick up the food

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?

**Comment by pikminman13** [comment]
This sounds like an issue relating to mob griefing. If mob griefing is off, villagers cannot breed.
