### ISSUE TITLE
FTB Interactions by Parts DX; Server stops handling login events

### ISSUE THREAD

**Issue by BrewingCoder** [FTBTeam/FTB-Modpack-Issues#3677]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.5.0

### Log Files

Log with initial "bad" connection attempt:

[https://gist.github.com/BrewingCoder/d6b0c31f30b794a72aa221d29f5248d8](https://gist.github.com/BrewingCoder/d6b0c31f30b794a72aa221d29f5248d8)

### Describe the bug

Server running 1.5.0 fine for 24 hours with multiple players connecting.

A player attempts a connection; possibly with a v1.4.0 client, and an exception is thrown.  The client is disconnected due to an "internal server error"  (See line 124 of attached log)

Any subsequent attempt at connection by myself or other known players with clients that are known to connect properly are disconnected in the same fashion. 

Subsequent connection attempts:  [https://gist.github.com/BrewingCoder/e8885737456ded5ce4bd17f43f017aa5](https://gist.github.com/BrewingCoder/e8885737456ded5ce4bd17f43f017aa5)

This behavior has happened twice in the last few hours.  I wouldn't have reported the first and chalked it up to a modded MC thing; but it happened again two hours later.

### Steps to reproduce

I swear I'm not sure.  Was it the 1.4 client connection attempt?  Did the server just have a hiccup?

### Expected behaviour

Stable handling of login events

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
