### ISSUE TITLE
Crash when loading the world.

### ISSUE THREAD

**Issue by Murchiz** [FTBTeam/FTB-Modpack-Issues#3678]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12052827/latest.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12052828/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12052829/debug.log)

### Describe the bug

My game crashed and I can no longer enter that world after starting the game. It enters other worlds without any problems.

### Steps to reproduce

1. Load game.
2. Open world.
3. Crash.

### Expected behaviour

Launched world.

**Comment by UnRealDinnerbone** [comment]
Does this still happen on the lastest version of the pack?
