### ISSUE TITLE
Multiple Recipes

### ISSUE THREAD

**Issue by epicdad843** [FTBTeam/FTB-Modpack-Issues#3683]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.3

### Log Files

nm

### Describe the bug

Iron Furnace from Iron Furnaces mod has the same recipe as the Blast Furnace from Ultimate Car mod.

Maybe add Polymorph mod

### Steps to reproduce

nm

### Expected behaviour

nm

### Screenshots

nm

### Additional information

nm

**Comment by manmaed** [comment]
Fixed in 1.4.0
