### ISSUE TITLE
Server Crash once player joins.

### ISSUE THREAD

**Issue by spkesDE** [FTBTeam/FTB-Modpack-Issues#3684]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Log Files

https://nc.spkes.de/index.php/s/no88nXWewxjfTSL/download/crash-2023-07-15_17.36.56-server.txt

### Describe the bug

Once a player joins the server, the server crashes. Looks like the world is corrupt? 

### Steps to reproduce

Join Server

### Expected behaviour

That the server do not crash

**Comment by ukmcplyr** [comment]
Suspect it's less corruption and more to do with this:

```
ResourceKey[minecraft:dimension / ftbteamdimensions:team/7b333f07-bedc-4d25-a138-1c73fe4a910d]: players: 1, entities: 56685,56685,9,80,80,1,0 [minecraft:item:56649, ...]
```

The above is showing that your player dim has 56,649 minecraft:item entities (things like mob drops, xp orbs, etc). A backed up mob farm is the most likely cause if I had to guess.

Are you on FB's Discord? Fixing this should be easy enough but more of a pain to explain here on GitHub.

**Comment by spkesDE** [comment]
Nah, I'm not the FTB Discord Server, but you can hit me up on discord 
https://discord.com/channels/@me/157193075326844930 or search for 'spkes'

**Comment by ukmcplyr** [comment]
Doh. I wrongly assumed you couldn't get to the point where `/kill @e` would work, but glad you're thinking quicker than me :grin:

Stopping it from happening again should be simple enough.  Using a mob farm as an example, you just have to ensure that mob drops and xp orbs are are sucked up and put into bulk storage/fluid tanks as quickly as they're generated, or voided.

Pipez or LaserIO and trash can from the Trash Cans mod should be all you need to do it.  Gimme a shout if you need more specific pointers on how to ties it all together :+1:

**Comment by spkesDE** [comment]
Thank you for your help :)
