### ISSUE TITLE
Modded persistent creatures despawning on server restart

### ISSUE THREAD

**Issue by EveOfTheRoses** [FTBTeam/FTB-Modpack-Issues#3685]
### Modpack

FTB University 1.16

### Modpack version

1.8.0

### Describe the bug

Entities that are not meant to despawn from Ars Nouveau and Mana & Artifice seem to despawn upon restart of the server. Namely we have encountered a missing Starbuncle, a Drygmy, a Vortex Broom, and an Iron Construct. This of course makes automation entirely impossible

edit: This seems to only happen in claimed chunks, in testing they only dissappeared when in a forceloaded chunk but our base is not currently forceloaded, the only forceloading on the server was about 300 blocks away. Furthermore they are not despawning, they are being deleted as they instantly disappear even if you just placed them and immediately restart. Name tags do not help either.

### Steps to reproduce

1. Place an Ars Nouveau summon, or Mana & Artifice artifice/construct entity down (edit: in a forceloaded/claimed area)
2. Restart server or game
3. ~~Suffer~~ _Note that they are missing_

### Expected behaviour

These are meant to be persistent and not dissapear

**Comment by UnRealDinnerbone** [comment]
Starbuncle does not exist in 1.16. What version of is it supposed to be?

**Comment by EveOfTheRoses** [comment]
Starbuncles did exist in 1.16, that was just pre renaming of them so they were called Carbuncles at the time (I think they stole the name from Final Fantasy or something of the like and had to change it for later versions).

**Comment by UnRealDinnerbone** [comment]
Ok, I see I'm able to reproduce this issue now. However, from looking at Ars Nouveau GitHub they said that 1.16 is no longer supported. So I'm going to have closed this issue as not planed
