### ISSUE TITLE
Super alloy invalid structure

### ISSUE THREAD

**Issue by Swright-ROBO** [FTBTeam/FTB-Modpack-Issues#3688]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.3.0

### Describe the bug

Completed task for super alloy smelter, Through the item to spawn in on a flat surface, check computer part and get error message of "Invalid structure" and "structure unknown"

### Steps to reproduce

1. complete task for Super alloy smelter spawned
2. clear a flat area of dirt
3. use spawner
4. check the computer part

### Expected behaviour

the compter part should say "Super alloy" and should be able to make modular ingots

**Comment by DinnerBeef** [comment]
I am going to assume this pack you are playing is FTB Presents Integration by Parts DX not FTB Unstable 1.20: Forge. Please let me know if I am wrong.

**Comment by Swright-ROBO** [comment]
Yep your right i thought I selected the integration. Sorry!

**Comment by pikminman13** [comment]
i am unable to replicate this on my dev instance or on 1.5

**Comment by pikminman13** [comment]
actually, you probably have a block placed above the controller

**Comment by Swright-ROBO** [comment]
Yes I just re tested it and you are correct, if there is a block above the fence it breaks.
