### ISSUE TITLE
thermo generator has too low extract rate

### ISSUE THREAD

**Issue by helkin-jurgles** [FTBTeam/FTB-Modpack-Issues#3690]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.5.0

### Describe the bug

the thermo generator from powah has low extraction rate lower than it can produce so would consider buffing that so that i could use it

### Steps to reproduce

place thermo generator (hardened in this case) and put in liquid star light and lava underneath it produces more than it could output meaning it wastes energy

### Expected behaviour

it should have a extration rate much higher than its generation

**Comment by pikminman13** [comment]
tables have been modified
