### ISSUE TITLE
Crash in a nether mob farm using furnace mycelial generator

### ISSUE THREAD

**Issue by supramaxis** [FTBTeam/FTB-Modpack-Issues#3692]
### Modpack

FTB Skies

### Modpack version

1.2.1

### Log Files

https://mclo.gs/owKqHGX

### Describe the bug

Okay so i built a nether mob farm using mechanical dirt a mycelial generator, an ender tank to feed the mechanical dirt with liquid meat, laserIO nodes and a mob crusher as shown in ChosenArchitect's video of the modpack

what happens next is that when i went back to the nether after doing some things on the overworld I opened the mycelial 
generator to see if it has something inside to generate power, and it has.

When the mechanical dirt gets full of power, the mob crusher is the next in getting power, but that does not happen

so for example, the mechanical dirt is close to have 10kFE and when the dirt had 10kFE it crashes

something i found in the logs is that it mentions: MycelialDataManager and modern fix mod

### Steps to reproduce

the steps are the same as the above

1. Build a mob farm
2. Stay next to the farm
3. Wait until the mechanical dirt have 10kFE
4. Expect the crash

### Expected behaviour

to not crash

### Screenshots

![imagen](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/88255405/772a4607-7c40-4e09-80cf-529b083278a7)

![imagen](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/88255405/274a0a17-8f8f-4e88-bc4a-a53879b7fdc3)

### Additional information

this is a linux server i manage to build myself, for me to not have the modpack opened in my pc all day

**Comment by Saereth** [comment]
this should be fixed with the new IF update
