### ISSUE TITLE
Refined Storage in Unstable Mod 1.20

### ISSUE THREAD

**Issue by MasonSwordXD** [FTBTeam/FTB-Modpack-Issues#3693]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.20

### Describe the bug

I setup a refined storage and put all my items into the system and when I try to take something out of it, it crashes my game

### Steps to reproduce

1. Load up modpack
2. Join my world
3. Open refined storage grid
4. Click on an item to take out
5. Crash

### Expected behaviour

I expected to take out items from my system but I've had to make a new world.

**Comment by PinkieIcePie** [comment]
It's a mod issue with Roughly Enough Items (see #3660 ) Only way I have found is to use JEI in place of REI for now until REI gets an update.

**Comment by Gaz492** [comment]
Is this still an issue in the latest version of the modpack for you?
