### ISSUE TITLE
Create Deployer crashes world with modpack update 1.4.0

### ISSUE THREAD

**Issue by Tactikitty** [FTBTeam/FTB-Modpack-Issues#3696]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.4.0

### Describe the bug

As soon as we load a world with a Deployer (from the mod Create) the game crashes (both on a server as well as in single player)

We tried removing the Deployer via map editing software, but as it is rotating on a "subgrid" and not an actual block there is no way we can remove it that way.

It might be a Problem with the Java Version in combination with the Create mod but we werent able to figure out anything else.

### Steps to reproduce

1. load up a world in FTB Unstable 1.20: Forge Version 1.4.0
2. place a Deployer from the mod Create

### Expected behaviour

Game doesnt crash

**Comment by OWNEDGAMING** [comment]
Having a similar problem, but doesn't just crash the game, but crashes the entirety of Overwolf including the FTB app.
Crash doesn't give me a log

**Comment by PraseodymiumSpike** [comment]
@OWNEDGAMING I've had the FTB App crash when loading in Worlds too, but the World itself doesn't crash until a little bit after I've joined. I thought it was something to do with the Skeleton Druid I was fighting, but maybe, it's the same issue.

**Comment by PraseodymiumSpike** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3707 This could be the same thing, too.

**Comment by DinnerBeef** [comment]
Please let me know if this issue is still happening in the next update.
