### ISSUE TITLE
SpaceBoss gem ores cannot be processed using Carbonic Acid

### ISSUE THREAD

**Issue by lord-ne** [FTBTeam/FTB-Modpack-Issues#3698]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.5.0

### Describe the bug

There is no fluid-to-item recipe to convert SpaceBossTools versions of certain ores into Clumps using Carbonic Acid. For example, there is no recipe to convert Venus Diamond Ore into Diamond Clumps using Carbonic Acid, but there is such a recipe for regular vanilla Diamond Ore

### Steps to reproduce

n/a

### Expected behaviour

n/a

**Comment by pikminman13** [comment]
fixed
