### ISSUE TITLE
JEI certain words crash

### ISSUE THREAD

**Issue by Prank3322** [FTBTeam/FTB-Modpack-Issues#3699]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.5.0.

### Log Files

[hs_err_pid13940.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12100160/hs_err_pid13940.log)

### Describe the bug

Game crashes when for example energ is typed into JEI search.

### Steps to reproduce

For me:
1. Open save
2. Open inventory
3. Type ener in JEI
4. type g and the game crashes

### Expected behaviour

The game shouldn't crash

### Additional information

I posted about this in the ftb discord but then i reinstalled java and it worked for a second but when i restarted the game it started happening again. Might be an issue for me only but i am not smart enough to know if it is.

**Comment by pikminman13** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40
