### ISSUE TITLE
[Bug]: Gem cast's are not obtainable 

### ISSUE THREAD

**Issue by evanFroelich** [FTBTeam/FTB-Modpack-Issues#37]
### Modpack

FTB University 1_16 

### Modpack version

1.2.0 

### Describe the bug

on the server stock ftb university we cannot make a gem cast. neither of the sand or the gold version. cant see a recipe or make it how its "supposed" to be made.

### Steps to reproduce

put gem like diamond in cast table, try to pour gold over it. nothing happens. and no recipe.

### Expected behaviour

put a compatible gem in the smeltery forge table and pour gold over it to make a gem cast

**Comment by Raidobw2** [comment]
This works as intended on version 1.1.0 of University 1.16, with Tinker's Contruct `TConstruct-1.16.5-3.1.1.252.jar`
![gem_cast_1 1 0](https://user-images.githubusercontent.com/17010632/135366721-18b9f0ee-abef-4a16-b94e-a7e0599da6c3.gif)
<br/>

However i can confirm it not working on version 1.2.0 of University 1.16, with Tinker's Construct `TConstruct-1.16.5-3.1.2.265.jar`
![gem_cast_1 2 0](https://user-images.githubusercontent.com/17010632/135366740-651f0189-000e-43db-9c98-09ddcd931944.gif)

**Comment by Raidobw2** [comment]
Probably at the recipe level something is messing it up, somehow, or config?

Server exports with `/kubejs export` (Thanks Lat)
Minimalist instance grafted from University 1.2.0 (Tinker's, KubeJS/integrations and other stuff)
```"tconstruct:smeltery/casts/gold_casts/gems":{"recipe":{"type":"tconstruct:casting_table","cast":{"tag":"forge:gems"},"cast_consumed":true,"switch_slots":true,"fluid":{"tag":"tconstruct:molten_gold","amount":144},"result":"tconstruct:gem_cast","cooling_time":57},"inputs":[{"tag":"forge:gems"}],"outputs":[{"item":"tconstruct:gem_cast","count":1}]}```

Full University 1.2.0 clean instance server export:
```"tconstruct:smeltery/casts/gold_casts/gems":{"recipe":{"type":"tconstruct:casting_table","cast":{"tag":"forge:gems"},"cast_consumed":true,"switch_slots":true,"fluid":{"tag":"tconstruct:molten_gold","amount":144},"result":"tconstruct:gem_cast","cooling_time":57},"inputs":[{"tag":"forge:gems"}],"outputs":[{"item":"tconstruct:gem_cast","count":1}],"removed":true}```

Notice the presence of **"removed":true** at the end of the second export.
I checked other recipes and they don't have that removed thing at the end of them. Still don't know what adds that after the update to 1.2.0, might dig again later to help you out Aaron.

**Comment by aaronhowser1** [comment]
Likely because I removed all recipes that use NYI thermal items, like rubies. I'll re-add.
