### ISSUE TITLE
[Bug/FTB Oceanblock]: Flame Lily Growth modifier for Netherrack causes underflow

### ISSUE THREAD

**Issue by Simon-Bitdiddle** [FTBTeam/FTB-Modpack-Issues#370]
### Modpack

FTB Oceanblock

### Modpack version

1.9.0

### Describe the bug

Planting the fire lily on netherrack in pots causes instant growth. Planting fire lily on netherrack in the world does not let the plant grow.

### Steps to reproduce

Attempt to plant fire lily as expected (on netherrack)

### Expected behaviour

Plant to grow in stages and steps.

### Screenshots

![2021-11-23_11 16 37](https://user-images.githubusercontent.com/9999849/143074173-ea1ddb2b-ff3a-409a-be1e-ae4adf805dc4.png)
![2021-11-23_11 17 05](https://user-images.githubusercontent.com/9999849/143074176-1a8160f3-be20-4798-ad2f-f4a1170ca946.png)
![2021-11-23_11 17 08](https://user-images.githubusercontent.com/9999849/143074178-ec02d0fb-db55-421b-9d07-08b640baf500.png)

**Comment by quietust** [comment]
Looks like you've spotted the root cause of #334 - netherrack was defined with a growthModifier of `1.0` when it should've been `0.0`.
