### ISSUE TITLE
Add RS Requestify

### ISSUE THREAD

**Issue by lord-ne** [FTBTeam/FTB-Modpack-Issues#3700]
### Modpack

FTB Presents Integration by Parts DX

### Mod suggestion

Refined Storage: Requestify is a mod that adds a block used to easily keep items in stock in a Refined Storage system. There are ways to achevie this with just Refined Storage (I think you can do an external storage onto an interface or something), but this is cleaner and more compact

**Comment by pikminman13** [comment]
i dont remember if i added this in an update or not but its already there
