### ISSUE TITLE
Copper plates can't be created with Ad Astra Iron Hammer

### ISSUE THREAD

**Issue by trevorjd** [FTBTeam/FTB-Modpack-Issues#3701]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.3.0

### Describe the bug

Ad Astra and Energized Power both add an iron hammer with the same recipe and the Ad Astra one takes precedence.  Copper plates can't be crafted with the Ad Astra Iron Hammer.

Since Energized Power adds a range of hammers, this can be worked around but it would create a more consistent environment if the EP recipe took precedence and the Ad Astra plates were tweaked onto the EP hammer set.

### Steps to reproduce

I think the description covers it.

### Expected behaviour

Recipe tweaks as covered in description.

**Comment by PinkieIcePie** [comment]
I believe the Polymorph mod is already installed, it may be disabled (rename the .jar file in your mods folder). That will give you a switch button to change the output recipe when there is a conflict :)
