### ISSUE TITLE
I Can't Log onto my Friend's Server and actually CRASH it.

### ISSUE THREAD

**Issue by E-Hunter19** [FTBTeam/FTB-Modpack-Issues#3707]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.4.0

### Describe the bug

My friends are able to log onto the server perfectly fine, nothing excepting logging on happens, but everytime I specifically try logging in, it not only prevents me from logging in but also kicks everybody else off and leaves us with two options, either wait around 10-15 minutes for the server to reboot or shutting it down and bringing it back up it manually. You would assume it's something with my PC but I was on the server for about 2 hours before the issues started happening. The last thing I did before not being able to log on again was be at the bottom of water and then opened my map, as I did, it kicked me off, I even thought that maybe I pressed a button that kicked me off as I think I fat-fingered some buttons around my Map Button (M) but I don't understand how that would be, we've tried to solve this problem ever since it happened about 10 hours ago and we can't seem to figure out how, if anyone else has this problem or knows a solution then that would be wildly appreciated.

### Steps to reproduce

1. Well I don't know if you can 'reproduce' it exactly but I'll rewrite what I was doing
2. Walk into a tall water pillar with walls (w1 x d1 x h30) from the block 1 above the bottom (e.g. if the bottom of the water pillar is y = 30, then enter the pillar from y = 29)
3. As you hit the bottom of the water, open your map and that'll kick you and you wont be able to log into the server again.

### Expected behaviour

I was expecting to be able to open my map so that I could set a waypoint in the water pillar.

**Comment by DinnerBeef** [comment]
Please send a crash log or the logs file of the server.
