### ISSUE TITLE
Crash when pressing "u" in JEI search bar

### ISSUE THREAD

**Issue by pandouss** [FTBTeam/FTB-Modpack-Issues#3708]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.6.0

### Describe the bug

When I type "u" in any sentence in JEI, such as "modular alloy", it just crashes. Also, when I click the modular alloy recipe it crashes.

### Steps to reproduce

Type "u" in JEI

### Expected behaviour

JEI working normally

**Comment by pikminman13** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40
