### ISSUE TITLE
Immersive Engineering Bottling Machine

### ISSUE THREAD

**Issue by MrLayton** [FTBTeam/FTB-Modpack-Issues#3710]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.4.0

### Describe the bug

When you break the bottling machine to relocate it, you lose 1 of the fluid pumps. You only get 1 pump back when the machine costs 2 to build.

### Steps to reproduce

Place the bottling machine with a capsule.
Break bottling machine.
Count number of fluid pumps.

### Expected behaviour

When you break the machine you get 2 fluid pumps back along with the other blocks required to construct the machine

**Comment by pikminman13** [comment]
thats an issue with the capsule. it treats it as 2 fluid pumps despite only being 1 and theres not much i can do about that. if you rebuild it manually you dont lose the pump. i might just remove the pump from the capsule.
