### ISSUE TITLE
To add jec

### ISSUE THREAD

**Issue by GrishaCrysta** [FTBTeam/FTB-Modpack-Issues#3711]
### Modpack

FTB Skies

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation
With this mod u can easily calculate resources for big crafts (in pre-autocraft)

**Comment by Saereth** [comment]
its purely client side, you're welcome to add it to your own instance, too many mixed opinions about it based on tester feedback to include it as default
