### ISSUE TITLE
Crash on getNewEyeHeight()

### ISSUE THREAD

**Issue by trevorjd** [FTBTeam/FTB-Modpack-Issues#3714]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.4.0

### Log Files

https://pastebin.com/dt23EuC0

### Describe the bug

Trying to figure out why my mining gadget wasn't using it's newly-added 3x3 module, I intended to hit G to open the UI.  I have had a few drinks so I might have hit something else.  Either way, the game froze and crashed with the with a deliciously novel error:  

Description: Exception in server tick loop
java.lang.NoSuchMethodError: 'float net.minecraftforge.event.entity.EntityEvent$Size.getNewEyeHeight()'

Crashlog suggests it's the Shrink mod however I have not crafted a personal shrinking device.  However, disabling the mod allowed me back into the game.

### Steps to reproduce

Have a Mining Gadget in hand with a 3x3 module in it.
Drunkenly try to hit the G key.
Sigh as an Unstable pack lives up to its name again :)

### Expected behaviour

The game to not crash in response to random keypresses

**Comment by ManiakNL** [comment]
I have the same issue :(

https://pastebin.com/witgXzhe

Is there anything i can change in the .dat file of my player to "fix" it?

**Comment by NilsRamstoeck** [comment]
Here is how I got things working again on a multiplayer server

1. Install [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases) 
2. Download your players .dat file from your server (not needed if you play single player)
3. Opened it using NBTExplorer
4. Expanded "ForgeCaps"
5. Expanded "shrink:shrunk"
6. set "isshrinking" and "isshrunk" to 0
7. Upload your fixed players .dat file to your server (again, not needed if you play single player
8. Immediatly unbind the key for shrinking ._.

**Comment by ManiakNL** [comment]
@NilsRamstoeck 
Interesting, that item is missing from my ForceCaps folder, perhaps it's because i joined my server once without the mod installed?

Seemingly it cleaned my attributes
