### ISSUE TITLE
(MACHINE) Mana Input to Generic Mana Input conversion not working

### ISSUE THREAD

**Issue by CaptAlex1092** [FTBTeam/FTB-Modpack-Issues#3716]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.6.0

### Describe the bug

The Recipe for (MACHINE) Mana Input to Generic Mana Input does not work.

### Steps to reproduce

Press R on the Generic Mana Input

Look at the recipe

### Expected behaviour

Get a Generic Mana Input when you place a (MACHINE) Mana Input

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/71784597/fdf4e538-7ecd-45ff-b717-2d0bacf74b65)

**Comment by pikminman13** [comment]
fixed in dev
