### ISSUE TITLE
Failing Backup causes the game to hang

### ISSUE THREAD

**Issue by techno156** [FTBTeam/FTB-Modpack-Issues#3717]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Log Files

https://mclo.gs/YgSSP9D

https://mclo.gs/XmB6jUk (longer log showing the errors more clearly, using a manually-triggered backup)

### Describe the bug

If the backup process fails, the game ends up being soft-locked. The player cannot do anything, and attempting to exit the game normally results in it being stuck on the "saving world" screen. The tips change, but nothing happens. From the Task Manager, the game is constantly writing 5MB/s to disk during this time. From the logs, it seems that it is constantly trying to write a thread dump/the timeout errors to disk, and blocking the rest of the processing which is causing the issue.

This is at odds to "normal" saving times, which are near-instant.

### Steps to reproduce

1. Make a Backup using FTB Backup
2. If FTB Backup Fails, the Game will be Softlocked, and it will not be possible to play the game, or save the world.

### Expected behaviour

The game should not be rendered unplayable by an unsuccessful backup

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2368911/3c473430-c188-4ccc-a68e-24de1687648c)

### Additional information

I run the modpack inside of a portable installation of PolyMC v5.1, which is itself inside of a Resilio Sync folder.

The Resilio Sync folder is located in an external drive, so the path directory is as follows: D:\<Sync Folder>\Shared\PolyMC\instances\FTBSkies, and as such, should not be long enough to run into problems with file name length limits.

In either case, the backup should fail, and only notify the user (preferably with an error message attached), rather than causing the game to hang.

**Comment by Automatiax** [comment]
I am also experiencing this issue, and this is the console output when the hang happened.


21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Attempting to create an automatic backup
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Found world folder at /home/minecraft/mc-instances/mc-64bf8d8aceba3/./world/.
21:30:00  [Error] [ne.cr.ft.FTBBackups/]: Last backup size: 0B Current world size: 916.4MB Current Available space: 60.7GB ExpectedSize 107.1MB
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world minecraft:overworld save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world compactmachines:compact_world save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:moon_orbit save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world minecraft:the_nether save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:earth_orbit save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:mars_orbit save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:mars save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ftbteamdimensions:team/bd687016-cfe5-4f1e-8acf-a5aa32b40eeb save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:glacio_orbit save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:moon save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:mercury save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:mercury_orbit save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:glacio save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:venus_orbit save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:venus save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world minecraft:the_end save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Setting world ae2:spatial_storage save state to true
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Writing to file /home/minecraft/mc-instances/mc-64bf8d8aceba3/backups/backups.json
21:30:00  [Info] [ne.cr.ft.FTBBackups/]: Waiting for world save to complete.
21:30:20  [Warn] [spark/]: Timed out waiting for world statistics
21:30:30  [Error] [ne.cr.ft.FTBBackups/]: Failed to create backup
java.util.concurrent.TimeoutException: null
at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960) ~[?:?] {re:mixin}
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095) ~[?:?] {re:mixin}
at net.creeperhost.ftbbackups.BackupHandler.lambda$createBackup$4(BackupHandler.java:206) ~[ftbbackups2-forge-1.19.2-1.0.19.jar%23523!/:?] {re:classloading}
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?] {}
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?] {}
at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world minecraft:overworld save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world compactmachines:compact_world save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:moon_orbit save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world minecraft:the_nether save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:earth_orbit save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:mars_orbit save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:mars save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ftbteamdimensions:team/bd687016-cfe5-4f1e-8acf-a5aa32b40eeb save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:glacio_orbit save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:moon save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:mercury save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:mercury_orbit save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:glacio save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:venus_orbit save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ad_astra:venus save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world minecraft:the_end save state to false
21:30:30  [Info] [ne.cr.ft.FTBBackups/]: Setting world ae2:spatial_storage save state to false
21:30:50  [Info] [ne.cr.ft.FTBBackups/]: More backups than 5 found, Removing oldest backup
21:30:50  [Info] [ne.cr.ft.FTBBackups/]: Removed old backup 2023-7-30_10-0-0.zip
21:30:50  [Info] [ne.cr.ft.FTBBackups/]: File missing, removing from backups /home/minecraft/mc-instances/mc-64bf8d8aceba3/backups/2023-7-30_10-0-0.zip
21:30:50  [Info] [ne.cr.ft.FTBBackups/]: File missing, removing from backups /home/minecraft/mc-instances/mc-64bf8d8aceba3/backups/2023-7-30_13-30-0.zip
21:30:50  [Info] [ne.cr.ft.FTBBackups/]: Writing to file /home/minecraft/mc-instances/mc-64bf8d8aceba3/backups/backups.json
21:31:20  [Warn] [spark/]: Timed out waiting for world statistics
21:32:20  [Warn] [spark/]: Timed out waiting for world statistics
21:33:20  [Warn] [spark/]: Timed out waiting for world statistics
21:34:20  [Warn] [spark/]: Timed out waiting for world statistics
21:35:20  [Warn] [spark/]: Timed out waiting for world statistics
21:36:20  [Warn] [spark/]: Timed out waiting for world statistics
21:37:20  [Warn] [spark/]: Timed out waiting for world statistics
21:38:20  [Warn] [spark/]: Timed out waiting for world statistics

**Comment by gdharron** [comment]
Still an issue in 1.20. Direwolf20 1.20 hangs for 30-90 secs while starting a backup using ftbbackups2 on my servers. Just wondering if there has been any progress on this?
