### ISSUE TITLE
sky factory crashes after 30 minutes

### ISSUE THREAD

**Issue by heyimlucky1** [FTBTeam/FTB-Modpack-Issues#3720]
### Modpack

FTB Presents Skyfactory 3

### Modpack version

3.0.21

### Describe the bug

when I load the game online or offline, after 30 or so minutes the forge will crash and I will be sent back to my desktop my ram is 16 GB and I have 10 allocated to Sky Factory and the latest version of Java. so I don't know what the issue is my computer has been brand new out of the box for a week 

### Steps to reproduce

-load into sky factory
-play for a few minutes 
-crash

### Expected behaviour

help

**Comment by Gaz492** [comment]
Unless you are running a texture pack I would suggest not giving the modpack more than 6GB of memory as it can start to misbehave.
If you still have a crash log for this, feel free to post it and I'm happy to have a look at it.
