### ISSUE TITLE
JEI Crash

### ISSUE THREAD

**Issue by BeardedGamer0** [FTBTeam/FTB-Modpack-Issues#3722]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.3.0

### Log Files

https://pastebin.com/JiV9SLJY

### Describe the bug

trying to type "item" into JEI search bar... hard crash when i hit the M key

### Steps to reproduce

launch game
open JEI
type Item

CRASH

### Expected behaviour

i expect to type item and see object like item pipes or anything tied to the word item

### Additional information

recreated this 3 times same crash all 3 times

**Comment by BeardedGamer0** [comment]
the letter Q also crashes....

**Comment by pikminman13** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40
