### ISSUE TITLE
Crash when rotating object

### ISSUE THREAD

**Issue by MiiWii0312** [FTBTeam/FTB-Modpack-Issues#3723]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.4.0

### Describe the bug

Layered Asurine can not be rotated with a PNC:R Wrench and crashes the server when it is tried.

### Steps to reproduce

1. Place Layered Asurine
2. Try to rotate with a PNC:R Wrench
3. Crash. 

### Expected behaviour

Don't crash and rotate block successfully

**Comment by DinnerBeef** [comment]
https://github.com/TeamPneumatic/pnc-repressurized/issues/1187
