### ISSUE TITLE
Timed out waiting for world statistics

### ISSUE THREAD

**Issue by ZooksPrime** [FTBTeam/FTB-Modpack-Issues#3724]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.1

### Log Files

https://pste.ch/iyehoqunay.md

### Describe the bug

Game freezes after leaving spawn and moving outwards towards the nether. Possibly crashing due to too many hostile mobs? No freezing near spawn, but as I move closer to the lush caves biome or the nether, the game crashes. Tried walking and also teleporting, still crashes.

### Steps to reproduce

Start from spawn
Head outwards to another biome

### Expected behaviour

No crashing while entering a new biome

**Comment by baboonery1** [comment]
im also having this issue, i time out and crash whenever im using a create mechanism near a dungeon or new biome
