### ISSUE TITLE
lobby destroyed

### ISSUE THREAD

**Issue by Falcon314** [FTBTeam/FTB-Modpack-Issues#3726]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.1

### Describe the bug

a few chunks in the lobby are just gone, + the portal is gone, i still can use " /ftb stoneblock home " but i would want the whole lobby back

### Steps to reproduce

there are no steps, i dont know how that happend

### Expected behaviour

i want my lobby back

### Screenshots

![2023-07-24_17 39 57](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/140426549/5b63f480-00e4-495a-991a-ff0234ca6ec3)

**Comment by UnRealDinnerbone** [comment]
Please upload logs files
