### ISSUE TITLE
[Bug]: Multiple recipe osmium essence

### ISSUE THREAD

**Issue by crzyblue** [FTBTeam/FTB-Modpack-Issues#3727]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.6

### Describe the bug

Looking up osmium in JEI, shows that you can craft 4 and 8 osmium from 8 essence with the same pattern.

1 of these is wrong :)

### Steps to reproduce

1. Open JEI
2. search Osmium Ingot
3. Click it
4. Notice crafting recipe for Essence

### Expected behaviour

Only have 1 essence recipe

### Screenshots

![2023-07-24_06 51 49](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/82949784/dea4f894-3e4e-4b76-830d-88b204670c94)

**Comment by pikminman13** [comment]
fixed in dev
