### ISSUE TITLE
[Bug]: Extra storage disk do not require Lunar Satellite dish to make the disk itself.

### ISSUE THREAD

**Issue by crzyblue** [FTBTeam/FTB-Modpack-Issues#3728]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.6

### Describe the bug

Extra storage disk do not require Lunar Satellite dish to make the disk itself.
![2023-07-24_22 18 16](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/82949784/9e8fd710-f473-4747-83fa-8fc5b2f5266e)

### Steps to reproduce

Lookup any drive 256k or larger.

### Expected behaviour

Require Lunar Satellite dish to make the disk.

**Comment by pikminman13** [comment]
for whatever reason it just spits errors at me if i put anything from extra storage into the recipe. despite being spelled correctly. if youre gonna resource spam to get the higher level drives its not like you didnt spend at least 3x more on parts so eh.
