### ISSUE TITLE
Deep Learner Right click in off hand crashes game

### ISSUE THREAD

**Issue by bowzer1991** [FTBTeam/FTB-Modpack-Issues#3729]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.3.1

### Describe the bug

When right clicking with the Deep Learner from Hostile Neural Networks in off hand the game crashes

### Steps to reproduce

 Put Deep Learner from Hostile Neural Networks in off hand, 
 right click,
observe game crash

### Expected behaviour

Game not to crash but open Deep Learner UI

**Comment by DinnerBeef** [comment]
Can you please double-check the pack? Hostile Neural Networks is not in FTB Unstable 1.20: Forge
