### ISSUE TITLE
Items dissapear when using keep inventory

### ISSUE THREAD

**Issue by NilsRamstoeck** [FTBTeam/FTB-Modpack-Issues#3730]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.4.0

### Describe the bug

When dying, you dont keep all items, some just dissappear. They dont get dropped or anything, they are just gone. Also Armor gets unequipped and items change slots in the inventory

### Steps to reproduce

1. Fill inventory
2. set keepInventory true
3. die

### Expected behaviour

Keep armor equiped, keep all items in the same slots

**Comment by Exanadu** [comment]
Same issue

**Comment by DinnerBeef** [comment]
Unable to reproduce. Can you please tell me what is in your inventory when you die please
