### ISSUE TITLE
Placing certain blocks with Buidling gadgets causes game to crash on interacting with the block

### ISSUE THREAD

**Issue by Thorfgin** [FTBTeam/FTB-Modpack-Issues#3731]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.12

### Log Files

https://paste.ee/p/PE7wh

### Describe the bug

When creating certain objects through the Architecture cutter the blocks are placed/replaced with a Building Gadget as a oak version instead.
When the oak object placed this way is cut, the game crashes.

### Steps to reproduce

1. Grab some Moss blocks
2. Create Moss stairs through the Architecture Cutter
3. Place the Stairs with a Building Gadget (builder/replacer)
4. Attempt to remove the block with an Axe.
5. Game crashes.

### Expected behaviour

1. Moss block becomes Moss stairs
2. Moss stairs when placed are rendered as Moss stairs
3. Moss stairs can be removed without crashing

### Additional information

Game save actually became corrupted after a few attempts to remove the blocks.
Had to restore a backup.

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can take a look at them? The link in your post looks to have expired.
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
