### ISSUE TITLE
Crash from Shrink Mod

### ISSUE THREAD

**Issue by d00mbr1nger** [FTBTeam/FTB-Modpack-Issues#3732]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.4.0

### Log Files

Crash Report of initial interaction: https://mclo.gs/ZoONU8B

Crash Report of attempting to rejoin: https://mclo.gs/myiEJcz

### Describe the bug

EDIT: Upon further testing, I have found that purely hitting the Toggle Shrink Hotkey (Default: G) causes the server/world to crash. Steps to reproduce added.

### Steps to reproduce

EDIT:

1. Join world/server
2. Press the Toggle Shrink Hotkey (Default: G)
3. Crash

### Expected behaviour

Unknown of what expected behaviour would be, not crashing I guess.

**Comment by Diamondman121314** [comment]
It seems to be a result of the changes to EntityEvent.Size in Forge. This was fixed with Forge version >= 47.1.40, which FTB Unstable will have to update to at least that version.

**Comment by DinnerBeef** [comment]
Mod has been downgraded. Tested it and it's not crashing more me.
