### ISSUE TITLE
List of Bugs and Issue I've Encountered

### ISSUE THREAD

**Issue by NotKanjuro** [FTBTeam/FTB-Modpack-Issues#3733]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.4.0

### Describe the bug

The following is a list of Bugs and Issues me and my friends have encountered whilst playing together. Some of these have been talked about in other Bug reports I'm just bringing up everything I've personally encountered.

- Advanced Peripherals, any of the blocks from advanced peripherals cause a game and server crash when clicked or interacted with a CC Tweaked Computer. I've tried this on both Single player and multiplayer and the same thing happens. The only fix I've been able to figure out for this is to load a world backup.

- Create, The Create deployer causes a game and server crash in both single and multiplayer, upon placing the block down is when the issue occurs, and you'll have to load a world backup. Since it can't be used most of the mods items cant be accessed with how important the deployer is in multiple create crafting recipes.

- Refined Storage, you can place anything you want into a refined storage system but upon taking it back out you can't. Doing so instantly crashes whatever server you're on and crashes your game, and you need to load a world backup.

- Beams, This one seems to be hit or miss with some people, whenever a beam from the Beams mod is turned on, specific people on a multiplayer server have their games crash, as long as the beam is on they keep crashing.

- Shrink, Upon trying to shrink or grow with the personal shrinking device in a single-player world your game crashes, and in multiplayer the server crashes making me have to load a world backup.

- Ars Nouveau, when attempting to make source gems or source gem blocks and there is a source jar nearby it seems like a 50/50 chance that your game crashes, and each time you load back you keep crashing till the source gem/block is complete or someone stops the process.

- Occultism, When attempting to summon Foliot the ritual will play out like normal up until the very end where it will say the ritual is successful and your game or server will crash, upon opening your world back up the ritual will be where it was just before starting, you don't need to load a world backup. It seems to rewind just before the ritual automatically.

- Rftool, I've noticed that some recipes in rftools don't show up in REI, things like the crafter and storage module, their tier one forms appear but the higher tiers don't. You can still craft them if you know the recipe otherwise if you don't you'll have to google them.

- EverlastingAbilities, The flight Ability just doesn't work, upon activation, you get slow falling and if you tap the space bar rapidly you can maintain your current height in the air but it doesn't give you creative flight.

- PlantTech2, The nether wart seeds don't work in any temperature, they need a warmer temperature, and when planted in the correct biomes, and aren't compatible with the temperature when they should be.

There are still a lot of mods I haven't fooled around with yet so there are probably more bugs to find, but for the moment this is my list of Bugs I've currently encountered.

### Steps to reproduce

Any steps are in the description with the corresponding bug

### Expected behaviour

These issues don't happen

**Comment by DinnerBeef** [comment]
Please reopen any of these issues you find in the next update as separate issues. Please double-check that the issues are not already open before making the issues, though.
