### ISSUE TITLE
FTB Infinity Evolved Skyblock: Bound Blade created but no achievement or trophy dropped 

### ISSUE THREAD

**Issue by syrilie** [FTBTeam/FTB-Modpack-Issues#3734]
### Modpack

FTB Infinity Evolved Skyblock

### Modpack version

2.0.1

### Describe the bug

I have build up the binding ritual stone stucture and placed the Sword of the Zephyr on top of the block in the middle and activated the binding ritual wih a weak activation crystal. Then some animation and sound and the bound sword got dropped. when i pick it up no achievement and no trophy appears. I am playing on a Server host. all the other achievements did appear Thaumcraft Wand Trophy, Crescent Hammer Trophy, etc. but this does not appear. Why? And more Importand how do i get it solved? 

### Steps to reproduce

1. preconditions done!
2. place the sword on the binding ritual block in the middle
3. activate the binding ritual with a weak activation crystal
4. pick up the bound sword

Expected results: bound sword and trophy in inventory. Achievement "you should leave this activated" reached.

### Expected behaviour

bound sword dropped, when picked up achievement and Trophy should drop

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
