### ISSUE TITLE
IC2 and Thaumic Tinkers bug in IE2.

### ISSUE THREAD

**Issue by tamagotchii2003** [FTBTeam/FTB-Modpack-Issues#3735]
### Modpack

FTB Infinity Evolved 1.7

### Modpack version

3.1.0

### Log Files

no errors in log

### Describe the bug

When Thaumic tinkerers and IndustrialCraft2 are in the same pack
The radiation effect of uranium 238 does not kill the player. 

### Steps to reproduce

1. Download current 3.1.0 Infinity Evolved pack.
2. Issue console command give player 4122 1
3. Observe potion effect does apply but does not tick.

### Expected behaviour

The player should be damaged by the radiation effect while holding uranium 238 while not wearing hazmat suit

### Additional information

Seems to work correctly if Thaumic Tinkers is not installed.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
