### ISSUE TITLE
Steam Engine displays an empty fuel tank

### ISSUE THREAD

**Issue by YungFR3AKDaddy** [FTBTeam/FTB-Modpack-Issues#3738]
### Modpack

FTB StoneBlock 3

### Modpack version

1.7.1

### Describe the bug

Seems to be the same bug as [this](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1899), water tank displays empty when a steam engine is applied and immediately displays full once its removed.

### Steps to reproduce

1. Add tanks
2. Fill with water (shows amounts)
3. Add steam engine
4. The tanks no longer shows the amount and the steam engine doesn't start.

### Expected behaviour

When you fill the tank with water, you can see how much water is in the tank and steam engine starts working.

### Screenshots

![2023-07-27_17 47 44](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/44386220/6cdb8693-b84d-4b27-bf5b-ad5b772108cb)
![2023-07-27_17 51 50](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/44386220/3dfb73d8-b1b1-4052-9ce0-3fb195773c07)

**Comment by UnRealDinnerbone** [comment]
Does this still happen in the latest version?
