### ISSUE TITLE
Immersive Engineering metals missing ore dictionary

### ISSUE THREAD

**Issue by youixentoo** [FTBTeam/FTB-Modpack-Issues#3740]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.7.0

### Describe the bug

Wooden storage crates generated in IE villager houses can contain a variety of metals. However, some these cannot be used in any recipe or interchanged to the Thermal variant. See screenshots for examples.

Compared to how Space-BossTools steel is also not used in any recipes or has ore dictionary tags, but can be crafted into IE steel.

Affected IE items (based on running the command below for some time):
- Copper ingot
- Lead nugget
- Silver nugget
- Nickel nugget

### Steps to reproduce

1. Place a chest
2. Run /loot insert <xyz of chest> loot immersiveengineering:chests/engineers_house
2.alt: Find a engineers house in a village

### Expected behaviour

Being able to use them

### Screenshots

![2023-07-28_19 25 09](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26249689/98621d37-15d3-460a-ac66-7b562b1f2dde)
![2023-07-28_19 25 11](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26249689/8c004504-37f5-463d-9b1b-ee34d42385c8)
![2023-07-28_19 29 23](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26249689/1d73a12b-f434-49b3-8f83-e935f64eabc9)
![2023-07-28_19 29 25](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26249689/01f69ac4-b5d0-4c68-9b8b-9b63d48918ee)

**Comment by pikminman13** [comment]
conversion recipes have been added
for whatever reason they refuse to accept the right tags
