### ISSUE TITLE
JEI search crash

### ISSUE THREAD

**Issue by Kameloe** [FTBTeam/FTB-Modpack-Issues#3744]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.7.0

### Log Files

https://pastebin.com/4KpsJ3A0

### Describe the bug

Client closes during JEI search

### Steps to reproduce

1. Open inventory with hotkey "e" (default hotkey)
2. Type "ope" in JEI search
3. Crashes, client closes

### Expected behaviour

No crash

### Additional information

-Typing "eeee" in JEI search does not crash the client
-Typing "pe" in JEI search does not crash the client

**Comment by pikminman13** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40
