### ISSUE TITLE
Crash when Searching "pic" in JEI

### ISSUE THREAD

**Issue by einekratzekatze** [FTBTeam/FTB-Modpack-Issues#3745]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.7.0

### Describe the bug

Searching "Pic" in JEI crashes the game. Specifically, the moment I press "c", while having "Pi" in the search bar before it. 

### Steps to reproduce

open jei. type "pic"

### Expected behaviour

no crash

**Comment by pikminman13** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40
