### ISSUE TITLE
Entering server crashes game, but others can join

### ISSUE THREAD

**Issue by oofking109** [FTBTeam/FTB-Modpack-Issues#3749]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.4.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12222452/latest.log)

### Describe the bug

I host a server on my computer, and all day yesterday I was able to play and everything was fine with everyone. Today, I tried starting it back up and joining, but it won't let me. It encrypts data and starts loading terrain, then says "saving world" and closes the game. My friend was able to join and even see me as I tried joining, but I wasn't able to fully enter the world.

### Steps to reproduce

I don't know how to properly do it, but I changed nothing between it working and not working.
Load game up after loading server.
Connect (direct, make server, go through local, any of it) to server.
Game does usual process, encrypting data then loading world then loading terrain.
Says saving world, then closes game.
Back to the FTB app which is crashed as well.

### Expected behaviour

I expected to join the server like normal.

### Additional information

It might be enderio, since when I load the game and look into the log from FTB app, it says "Invalid path textures/enderio:block/overlay: Invalid segment 'enderio:block' in path 'textures/enderio:block/overlay'" over and over again. I have no idea what else it would be, I have 6G of ram going to both my side and the server while I have 16, and a friend with a laptop was able to join and play since the server is up and running. It's most likely an issue with my side of the game, but I tried reinstalling, restarting my computer, the server, my router, and even checking my firewall.

**Comment by Godson777** [comment]
I looked through the logs, and it seems like you triggered the shrink mod (the default hotkey is G, so it's easy to accidentally trigger it). It's not a problem in 1.5.0, try updating the pack and loading it up to see if it's still crashing.

**Comment by MoBeMo** [comment]
Seems like its not fixed in the newest Version
Same issue. One server, some can join, some are crashed after entering.
Is there any quick workaround?
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/14964633/7aff08e4-d55f-4055-9828-9160b6230611)

**Comment by MoBeMo** [comment]
this is on the 1.5 version

**Comment by mgorf2005** [comment]
I get that too. FTB loader is frozen and the Minecraft launcher is running the title screen with music. I click on Singleplayer, which takes me to the Select World screen. I choose my world and click Play Selected World, the FTB loader screen goes black and the Minecraft loader starts creating the world. Once it gets to 100%, the window closes and FTB app shows it trying to reconnect to apps agent.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
