### ISSUE TITLE
FTB Builders Paradise gets stuck while launching

### ISSUE THREAD

**Issue by InsaneJaffaman** [FTBTeam/FTB-Modpack-Issues#3753]
### Modpack

FTB Builders Paradise

### Modpack version

1.9.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12235531/latest.log)

### Describe the bug

Modpack gets stuck while loading it on the FTB launcher

### Steps to reproduce

1. Launch the Builders Paradise modpack
2. Leave it to load
3. Gets stuck on Initializing mods Phase 3 // Thermal Cultivation

### Expected behaviour

Boot up to main menu of the modpack

### Screenshots

![Screenshot_12](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/141198876/6c0c2801-37f0-463b-afb8-2fc4ba520e0b)

### Additional information

Occasionally it will get stuck on other parts but always in Phase 3, I have tried reinstalling the instance but the issue has persisted

**Comment by manmaed** [comment]
This issue is stale and pack is no longer being worked on
