### ISSUE TITLE
Linux server files - Compromised ?

### ISSUE THREAD

**Issue by Arimav2nd** [FTBTeam/FTB-Modpack-Issues#3754]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Describe the bug

I can no longer download Linux server files, it's blocked by Windows Defender / Chrome.

When is use VirusTotal to scan it, there is 18 results : https://www.virustotal.com/gui/file/4691552b6929465bf006962e01d9c94125366083993350abc8dbc3781a260af4/detection

According to sandbox scans, file seems to execute curious things : 

```
sh -c /usr/lib/rsyslog/rsyslog-rotate logrotate_script /var/log/mail.info/var/log/mail.warn/var/log/mail.err/var/log/mail.log/var/log/daemon.log/var/log/kern.log/var/log/auth.log/var/log/user.log/var/log/lpr.log/var/log/cron.log/var/log/debug/var/log/messages
sh -c /usr/lib/rsyslog/rsyslog-rotate logrotate_script /var/log/syslog
systemctl kill -s HUP rsyslog.service
```

### Steps to reproduce

Simply download the file from Chrome.

### Expected behaviour

Should be able to download the file

### Additional information

Issue seems to be the same with all other Linux Servers scripts.

**Comment by Gaz492** [comment]
I'm not sure what would cause the server installer to be classed as a trojan, these are false positives and the source code for the installer can be found at https://github.com/CreeperHost/modpacksch-serverdownloader/
