### ISSUE TITLE
I am unable to switch hotbar slot

### ISSUE THREAD

**Issue by incomingnerd** [FTBTeam/FTB-Modpack-Issues#3756]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Describe the bug

I am unable to switch hotbar slot. Neither scrollwheel, nor number key has any effect.

This is happened to me a total of three times so far. It seems to happen when trying to scroll to a new hotbar slot after just having exited the interface of a machine or storage. There are no log messages, no crashes, nor other indications of a problem. All other parts of the game continue to function - I can still interact with the world, other keys (including switch hands) still work fine. I just lose all ability to switch to a different hotbar slot.

I have tried many things to fix this, including:

- Opening and closing my inventory 
- Removing all equipped baubles and armor
- Switching dimensions
- Exiting to the main menu and re-opening the save

Nothing has any effect. Once triggered the bug will persist. The only way I have found to fix it is to quit the game entirely and re-launch.

I am perplexed. I have never seen a bug like this before in any modpack. Any ideas?

### Steps to reproduce

I have no idea how to reproduce this bug. As stated, it has happened three times now, seemingly with little to no shared factors.

Here's the current state of the game with the bug active:

- I am playing single player
- I have had the game open for several hours
- The bug triggered with empty hands on hotbar slot 5
- I had just closed out of an Industrial Foregoing Fluid Extractor when I noticed the bug

### Expected behaviour

That the hotbar continues to function.

**Comment by ewhaze** [comment]
I'm having the same problem.. And disconnecting from the current game and coming back doesn't fix it, i had to re-open the launcher, happened to me twice, not very commom but quite annoying

**Comment by Wexalian** [comment]
I have encountered the same issue. It seems like, when everything works normally, holding 'V' blocks you from scrolling, but should let you scroll again when you release it. Apparently there seems to be an issue there. 

I've tried rebinding all keybinds using 'V', but it still scroll locks when holding 'V'. Pressing 'V' again also doesn't seem to release the button again.

Does anybody know which mod adds this feature, and why isn't it a proper keybind?

**Comment by CoryNB** [comment]
here is another thing to try, vr mode. vr mods are around for use in modpacks

**Comment by incomingnerd** [comment]
> I have encountered the same issue. It seems like, when everything works normally, holding 'V' blocks you from scrolling, but should let you scroll again when you release it. Apparently there seems to be an issue there.

Good find! Yes, it appears that hitting 'V' did just fix it (it happened again). I'm pretty sure I didn't hit 'V' to trigger the bug in the first place, but whatever mod it is that's causing the issue does at least seem to respond to that.

I've not changed my keybindings for 'V' from the defaults. I've got: Building Gadgets (Range / Overlay), CoFH (Cycle Mode Up), Mekanism (Head Mode Switch) and Supplementaries (Quiver) bound to it. I'm only using the Cycle Mode feature though.

**Comment by KubaLubiMaslo** [comment]
Its Quiver from Supplementaris you need to go in there and set it to not bound just click esc while on it. It fixed everything.
