### ISSUE TITLE
Questbook and Island not working on server

### ISSUE THREAD

**Issue by inasarr** [FTBTeam/FTB-Modpack-Issues#3757]
### Modpack

FTB Skies

### Modpack version

1.19.2

### Describe the bug

Hello,
I've encountered a problem with the quests and the world. I downloaded the modpack and uploaded the files to the server, also changing the Forge version. However, when I entered the server, the world was not the same as in singleplayer. So, I took the save from singleplayer and put it on the server. The islands on the server were not showing up, so I created them in singleplayer and everything seemed fine until I noticed that the quests were not appearing on the server. The quest book was not given, and it appeared empty, which didn't happen in singleplayer. I tried deleting the quest file, but it didn't work. I also tried replacing it with the one from singleplayer, but that didn't work either. I even tried removing everything and leaving only the mods, but it didn't work.

Please, help me. I've been trying since this morning.

Thank you very much for your attention!

### Steps to reproduce

1. open ftb skies
2. join the server
3. questbook is empty

### Expected behaviour

questbook and island working

**Comment by Saereth** [comment]
your installation was corrupt
