### ISSUE TITLE
Mod Suggestion: Storage Drawers

### ISSUE THREAD

**Issue by d00mbr1nger** [FTBTeam/FTB-Modpack-Issues#3758]
### Modpack

FTB Unstable 1.20: Forge

### Is your suggestion related to a problem? Please describe.

Sophisticated storage has drawer like blocks, but they're frustrating to use because they don't have a centralized access / control point like storage drawers.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/storage-drawers

This mod adds single, double, or quad item mass storage blocks that can all be accessed via a centralized controller with refined or ae2. Provides bulk storage to eliminate the need for many storage disks/drives in those digital systems.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
