### ISSUE TITLE
FTB skies shape builder corrupts chunk

### ISSUE THREAD

**Issue by Sirpickle4** [FTBTeam/FTB-Modpack-Issues#3759]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Log Files

[crash-2023-08-01_18.14.08-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12262389/crash-2023-08-01_18.14.08-client.txt)

### Describe the bug

If you shift right click any blocks from the "Chipped" mod into the shape builder from cyclic, the game crashes. if you try to rejoin while rendering that chunk the game will crash again. basically corrupting the chunk.

### Steps to reproduce

1. place down the shape builder from cyclic
2. shift click any blocks from the chipped mod into the shape builder inventory.
3. you crash.

### Expected behaviour

The items to go in and the builder to start building.

**Comment by Z1Meme** [comment]
Also dealing with this issue on the same version of ftb skies, seems like it's caused by either shift-clicking a stack of items (specifically Mekanism Structural Glass), or the shape builder trying having a block in it's path already.

**Comment by Saereth** [comment]
this was reported fixed the cyclic dev and we've updated the mod so should sort it
