### ISSUE TITLE
cant craft raw neural processor in s2 processor cutter

### ISSUE THREAD

**Issue by TheNewDingo** [FTBTeam/FTB-Modpack-Issues#3761]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.7.0

### Describe the bug

I attempted to craft raw neural processor in the processor cutter with with a singular torsion speed gearbox in the multiblock making it a s2.
I can craft the base raw processors but not the raw neural processor unless I remove the singular torsion speed gearbox to make it a base process cutter. 
I have not tested any other version of the machine just theses two 

### Steps to reproduce

upgrade processor cutter to s2
put in ingredients for raw neural processor 
nothing happens

### Expected behaviour

it crafts a raw neural processor 

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/141454699/4cb63e62-7233-4999-a2e0-a14c5b5fda14)

**Comment by pikminman13** [comment]
ok fixed in dev
