### ISSUE TITLE
vr mode support for all of fabric 6

### ISSUE THREAD

**Issue by CoryNB** [FTBTeam/FTB-Modpack-Issues#3765]
### Modpack

Other...

### Is your suggestion related to a problem? Please describe.

Recently had to find the mod and its dependency on VR mode for fabric, I just ran the test and it took a full 5 to 15+ mins to boot up a VR-capable launcher. 
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/94322419/9cf9b19c-0b6e-4e91-8e5c-f961b0162d53)
mcxr core + mcxr play must be used to allow VR mode to work with the headset. sodium mod helps with performance in the game.
found it for youtube and gave it a random try for it to successfully work. feels like the complexity of iskaki and sao combined in Minecraft being introduced 

### Mod suggestion

mod 1, sodium: https://modrinth.com/mod/sodium/version/mc1.19.4-0.4.10
mod 2 and 3, mcxr core and mcxr play: https://github.com/mcxr-org/MCXR/releases/tag/c0.2.2-p0.2.24
both mods are fabric only. so no java forge edition vr has yet been found. recommend having a ddr4 that runs 3000 mhz or higher with low latency, 20 gb minimum to 64 maximum amount of ram memory. storage minimum is 64 gb to 1 tb max. storage transfer rate minimum is an sata ssd and maximum is nvme ssd gen 3. minimum performance cpu specs must be 4 cores, 8 threads, and the maximum is 10 core, 20 threads. 4 efficiency cores are the minimum for OS, Recording, and interface commands.

**Comment by UnRealDinnerbone** [comment]
This is not a FTB Pack
