### ISSUE TITLE
Screenshot trouble

### ISSUE THREAD

**Issue by GrishaCrysta** [FTBTeam/FTB-Modpack-Issues#3767]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12267444/latest.log)

### Describe the bug

When i want to make a screenshot, showing screenshot for some seconds later, or just all screen gray or black

### Steps to reproduce

Just click printscreen

### Expected behaviour

normal screenshot g

### Screenshots

![Снимок экрана 2023-08-03 185502 — копия](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/111286512/e6c9f4f2-29e7-4f30-a136-0b9140a9f4ee)
![Снимок экрана 2023-08-03 185502](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/111286512/467441df-55aa-4209-a203-0dd94b8ed26e)
![Снимок экрана 2023-08-03 163122 — копия](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/111286512/bd9e7648-28ea-4cbd-8d6c-197fee2f26e1)
![Снимок экрана 2023-08-03 163122](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/111286512/e16610ed-6e0c-4f1e-a689-5efeff0f607c)
![Снимок экрана 2023-08-03 163106](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/111286512/e68fa623-c20f-4ca6-aec1-a365390ed7f2)
![Снимок экрана 2023-08-03 163052](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/111286512/3626df32-57af-4431-a007-b989f01012b0)
![Снимок экрана 2023-08-03 162931](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/111286512/ac099c0a-ba57-4568-a4a6-62600c4f05d7)

### Additional information

i'm on win 11, problem appeared something like a week ago

**Comment by CoryNB** [comment]
have you tried vr mode? there may be alternative modes for gameplay.

**Comment by GrishaCrysta** [comment]
what is vr mode? with vr headsets? i haven't it before & it's very expensive

**Comment by Saereth** [comment]
I cant reproduce this
