### ISSUE TITLE
Integration by Parts DX - Stuffed Pumpkin not edible 

### ISSUE THREAD

**Issue by dragon-masterk** [FTBTeam/FTB-Modpack-Issues#3769]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.8.0

### Describe the bug

The Thermal Cultivation Stuffed Pumpkin food item is not edible. It also does not have any diet values. 

### Steps to reproduce

1. Crate Stuffed Pumpkin.
2. You cannot eat it. 

### Expected behaviour

You should be able able to eat the food item and it should have values to add to your diet.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83424830/a34d343e-1d6e-4e41-9c43-c9cd2d18e2ce)

**Comment by pikminman13** [comment]
this is not a bug. you place it down and eat it like a cake.
