### ISSUE TITLE
Impossible to craft generic mana output

### ISSUE THREAD

**Issue by Zleub** [FTBTeam/FTB-Modpack-Issues#3770]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.7.0

### Describe the bug

You cannot craft a generic mana output from the generic mana input 

### Steps to reproduce

1 open crafting table
2 put generic mana input in it

### Expected behaviour

We should be able to craft or cycle recipes for the generic mana output

**Comment by pikminman13** [comment]
fixed in dev
