### ISSUE TITLE
Space villagers lack custom trades

### ISSUE THREAD

**Issue by Axolotl009** [FTBTeam/FTB-Modpack-Issues#3771]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.8.0

### Describe the bug

Although the quest book and KubeJS file show custom trades for the alien shepherd (for Magical Egg and Alien Zombie Charm Fragment) they do not appear to spawn in the shepherd’s trade pool in any of those I’ve trained. Instead vanilla shepherd trades (which should be removed) override them. 

### Steps to reproduce

Summon an alien from Space Boss Tools with the shepherd profession. Train alien to the max level. Only vanilla trades (emeralds for vanilla items) appear, except at level 1.

### Expected behaviour

Custom trades (for enderium coins) appear.

### Additional information

It feels as though vanilla trades with aliens were intended to be disabled entirely, but I’m not 100% sure. Indeed librarians and tool smiths (disabled in overworld) retain all trades.

**Comment by pikminman13** [comment]
by the time you reach space the stuff that makes those villagers "broken" isnt nearly as much of an issue. i dont think i can remove villager trades either. the later trades are only a chance to appear, though the eggs have two chances.

**Comment by Axolotl009** [comment]
Thankfully I have been able to find one shepherd in my world who sells the egg fragment. I’ve still yet to see the magical egg even in creative testing, which is a shame since this item is pretty important for automating mob fluids! It seems the shepherd has so many other trades at levels 2-4 they’re very likely to get overridden. 
I’d suggest you consider adding the charm fragment and egg to a different villager, or adding an alternative method to get them, since villager RNG can be pretty annoying.

(Also great job with the pack I’m really enjoying it!)

**Comment by pikminman13** [comment]
i added a recipe using coins, gaia spirits, and an egg. then theres still a way to get it but the coin recipe is easier if you have it.
