### ISSUE TITLE
Moon Sand lacks a recipe

### ISSUE THREAD

**Issue by Axolotl009** [FTBTeam/FTB-Modpack-Issues#3772]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.8.0

### Describe the bug

The item Moon Sand, required for the Nital path to infused crystals, is not automatable by any means.

### Steps to reproduce

Check JEI and custom KubeJS scripts, this item has no recipe.

### Expected behaviour

Moon Sand has a recipe.

### Additional information

This may be intentional but the item seems essential enough that it may be an accident.

**Comment by pikminman13** [comment]
fixed in dev
