### ISSUE TITLE
Dimension locking doesn’t work

### ISSUE THREAD

**Issue by Axolotl009** [FTBTeam/FTB-Modpack-Issues#3773]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.8.0

### Describe the bug

Blocks such as the Orechid and Solar Panel that are supposed to be restricted to a given dimension can be placed by Cyclic’s Block Placers or teleported by Blood Magic’s Teleposers, and will still work. 

### Steps to reproduce

For the block placer: Place a floating Orechid inside the block placer, then enable it. For the teleposer: Place and link a pair of teleposers, one on the Moon and one in the Overworld, place an EV solar panel on the Moon teleposer, then activate the teleposers.

### Expected behaviour

The blocks should cease to function while in the wrong dimension.

**Comment by pikminman13** [comment]
this is impossible to enforce and was already reported. i would have to remove the responsible features, but theyre too useful to not.

**Comment by Axolotl009** [comment]
There is a mod called Restriction that was used in E6E for the same effect. I can see why it’s not possible to fix with Kube alone.
