### ISSUE TITLE
Copper Blocks

### ISSUE THREAD

**Issue by NotKanjuro** [FTBTeam/FTB-Modpack-Issues#3777]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Describe the bug

Copper Blocks Cannot be turned back into Copper Ingots

### Steps to reproduce

Make Copper Block
Put Block back into the crafting table

### Expected behaviour

I get 9 Copper Ingots

**Comment by raalpe** [comment]
from my testing it is "pneumaticcraft-repressurized-6.0.0+mc1.20.1" that is causing the issue, as soon i remove it the recipe works.

**Comment by raalpe** [comment]
solved in PneumaticCraft: Repressurized, so would assume it is fixed in next release.
https://github.com/TeamPneumatic/pnc-repressurized/issues/1213#issuecomment-1712751827
