### ISSUE TITLE
Refined Storage System

### ISSUE THREAD

**Issue by NotKanjuro** [FTBTeam/FTB-Modpack-Issues#3778]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Describe the bug

The refined storage system doesn't allow you to take items out of it, once you try to take items out of the system the game immediately crashes, or if you're on a server it crashes the server.

### Steps to reproduce

-Create a Refined Storage storage system
-Put any item into the system
-Try to take the item back out

### Expected behaviour

I can put items in and take them back out with out with crashing

**Comment by anything420** [comment]
Having the same problem. All I've been able to find is a bug in REI and there seems to be no way to fix it.

**Comment by CowboyJet** [comment]
Same, attached crash report

[crash-2023-08-18_16.20.18-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12380339/crash-2023-08-18_16.20.18-client.txt)

**Comment by Terraform89** [comment]
If you replace the mod REI with JEI it will work correctly.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
