### ISSUE TITLE
Beams Mod

### ISSUE THREAD

**Issue by NotKanjuro** [FTBTeam/FTB-Modpack-Issues#3779]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Describe the bug

Upon turning on a projector on a server as long as it's being powered most people on the server have their games crash. I'm still trying to figure out why only some people have their games crash, but it doesn't seem clear.

### Steps to reproduce

-Place down a projector
-Power it with Redstone(I used a lever)

### Expected behaviour

The beam shoots out of the Projector and no one crashes

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can take a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
