### ISSUE TITLE
Rftoolsbuilder Mover

### ISSUE THREAD

**Issue by NotKanjuro** [FTBTeam/FTB-Modpack-Issues#3780]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Describe the bug

Using RftoolsBuilder's Mover block when you place your vehicle card inside the block you get a weird visual glitch where you see two copies of your vehicle floating around your screen that doesn't go away till you take the card out.

### Steps to reproduce

-Create a Vehicle Card with a build stored on it
-Place down Two mover blocks and a Mover Controller with a power source
-Place Vehicle Card into mover block

### Expected behaviour

There is not Visual Glitch

### Screenshots

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/140635951/858e51b6-27db-41cd-8502-994fc93ad1ef

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
