### ISSUE TITLE
MineTogether is BS

### ISSUE THREAD

**Issue by mydii** [FTBTeam/FTB-Modpack-Issues#3781]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.9.0

### Describe the bug

i cant open a world to friends, it keeps me stuck in attempting and never goes anywhere else. We were playing just fine for like a week and now we cant even play. Idk what to do as weve done just about everything to try and fix it.

### Steps to reproduce

fix it :)

### Expected behaviour

I expected to open my world to friends like ive been for the past week and have them be able to join without constant errors.

**Comment by Gaz492** [comment]
If you happen to still have a log file from when this was an issue for you, would you be able to upload it so we can take a look at it and possibly forward it to the developers of MineTogether?
