### ISSUE TITLE
Antimatter changes have no effect

### ISSUE THREAD

**Issue by Axolotl009** [FTBTeam/FTB-Modpack-Issues#3783]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.8.0

### Describe the bug

In the changelog for 1.7.0 it states the polonium cost for antimatter was halved from default and the energy cost was quartered. However in my 1.8.0 world it still costs 400MRF and 1000mB of polonium to produce 1 man antimatter.

### Steps to reproduce

Set up an SPS, fill it with polonium and attach a battery, wait for 1 mB antimatter and observe the consumed polonium and energy. 

### Expected behaviour

As discussed in the patch notes only 100MRF and 500mB polonium should be consumed.

**Comment by pikminman13** [comment]
after about 400 brain shortages trying to figure out the number i needed i fixed it. now its 500 mb per and 100MRF per anti (its cut in half per process and then the amount you need is also half)
