### ISSUE TITLE
Remix Generator is energy net-negative

### ISSUE THREAD

**Issue by Axolotl009** [FTBTeam/FTB-Modpack-Issues#3784]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.8.0

### Describe the bug

I really want to set up the Remix Generator in my world to run the SPS, but as it stands the generator produces 50M RF per set of items. However, making 2 Circuit Shells require an Ultimate Control Circuit, requiring 1 mB antimatter whether produced directly or from crying obsidian. 
Even with the energy changes mentioned in the 1.7.0 changelog (which aren’t currently working) this consumes 100MRF to produce 100MRF, plus the other energy costs involved in operating the Nucleosynthesizer and making every other item.
This could be fixed if the Remix Generator produced energy every tick (for the 5 ticks it runs).

### Steps to reproduce

Measure the energy consumed in creating an Ultimate Circuit and compare to the output from the Remix Generator.

### Expected behaviour

One possible resolution is to add the line ‘perTick’: true to the remix generator recipe. Alternately the Ultimate circuit could be replaced with an Elite one.

### Additional information

Also about the Remix Generator: I don’t think it’s worth opening a separate issue, but another problem is the Lunar Satellite Dish takes 20 minutes to produce one Coordinate Module. Running the generator once per second would take 1200 Lunar Satellite Dishes, which is not feasible.

**Comment by pikminman13** [comment]
i fixed the satellite dish already.

more importantly: excuse me? there's a per tick option?

**Comment by Axolotl009** [comment]
Yep and there’s a few examples here: 
https://github.com/TicTicBoooom-Mods/MasterfulMachinery/wiki/Step-3:-Machine-Recipes

**Comment by pikminman13** [comment]
welp, after wanting to take a spacewalk and remove my helmet, and doing some fiddling, i changed some stuff.

so first of all, the generation rate is ACTUALLY 50M/t now. second, it makes that over 5 seconds, so the item consumption rate is much slower. hopefully this addresses the balance changes. as a result, it is now 250M/item set i believe, so that addresses the power issue.
