### ISSUE TITLE
Witches gain fire resistance in smeltery

### ISSUE THREAD

**Issue by Axolotl009** [FTBTeam/FTB-Modpack-Issues#3785]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.8.0

### Describe the bug

I tried melting a witch in a smeltery to produce Magical Mixture, but after making two buckets she drinks a 3 min fire resistance potion and becomes immune. 
It’s possible there’s a workaround I don’t know about, but this seems to make them unmeltable.

### Steps to reproduce

Make a smeltery, and spawn a witch inside. Watch the effects she gains.

### Expected behaviour

The witch should not be able to drink these potions, or there should be a way to spawn a witch with NoAI enabled. 

### Additional information

Alternately if there is a workaround for removing potion effects I haven’t noticed this could be mentioned in the quest book!

**Comment by pikminman13** [comment]
this is not a bug
