### ISSUE TITLE
Jade mod missing in serverinstall_100_6647 (1.8.0)

### ISSUE THREAD

**Issue by morpheus8379** [FTBTeam/FTB-Modpack-Issues#3791]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.0

### Describe the bug

Hi,

It seems that the mod Jade 5.3.0 is missing in the mods directory when using the server_install (linux version) script to update from 1.7.1.

### Steps to reproduce

1. DL serverinstall_100_6647 from FTB site
2. Launch serverinstall_100_6647 to update existing 1.7.1 instance
3. Try to launch server
4. Server exit with dependency failure (Jadeaddons need Jade)

### Expected behaviour

Server start without adding Jade mod by hand

### Additional information
Just tried fresh install with serverinstall_100_6647 and Jade mod missing too

_No response_

**Comment by JulianVennen** [comment]
Here's an example log file showing this problem: https://mclo.gs/t0zc9V9#L80

**Comment by Jake-E** [comment]
This has been fixed, it may take a few minutes due to caching.
