### ISSUE TITLE
How do I fix the guide book being "invalid" in survival?

### ISSUE THREAD

**Issue by carsiebek** [FTBTeam/FTB-Modpack-Issues#3792]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.20.1

### Describe the bug

I just downloaded this modpack for the first time and created a survival world first thing. When everything loaded, I first tried to open up the guide book and it didn't work so i opened up my inventory, hovered my cursor over it and it showed "Invalid book : advancedperipherals:manual" underneath the name of the item. I've tried creating new worlds after that and it does the exact same thing each time. I've even attempted to go to the main menu to see if i could change the settings in either the Advanced Peripherals mod or the Patchouli mod (thats the mod tagged under the guide book issue) but I wasnt able to. Please let me know how i can fix this!!!! 

### Steps to reproduce

1. create new world:)
2. guide book not work:(
3. idk what other steps i could possibly put

### Expected behaviour

I expected to create a new world and for the guide book to work 

### Screenshots

![2023-08-10_17 52 53](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/141968659/4a0c4d77-072f-45e9-8ca4-397721ce8135)

**Comment by anything420** [comment]
yea, I ignored that hoping it would get a fix.. Still yet to happen. I kept playing without it and made a refined storage system just to find out that when you insert items into the storage system you then cant take anything out without the pack crashing.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
