### ISSUE TITLE
Multi buffer cannot be used for some carpenter recipes

### ISSUE THREAD

**Issue by Inky-developer** [FTBTeam/FTB-Modpack-Issues#3794]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.8.0

### Describe the bug

Some carpenter recipes (Like the simple circuit assembly) require more than 3 item ingredients. However, the multi buffer can only accept 3 + 1 fluid. As far as I am aware, there is no other block in the modpack that can be used with a refined storage crafter that accepts items and fluids. 
So to automate the carpenter, one would have to remove the fluid from the refined storage pattern and e.g. build multiple carpenters or somehow make sure that the carpenter gets the correct fluid for the input items, which is not ideal.

### Steps to reproduce

1. Set up refined storage
2. Create a pattern for a recipe with a fluid and more than 3 input items (e.g. circuit assembly)
3. Notice that there is no way for a crafter to craft that recipe, since the multi buffer won't accept that many items

### Expected behaviour

Either the multi buffer should accept more input items, or there should be alternative blocks that can accept items and fluids

**Comment by pikminman13** [comment]
unchangeable, there is no config, and im not allowed to edit mod jars. there are no other mods that add something like that. export fluids separately to just keep the machine filled.

**Comment by Axolotl009** [comment]
Hey, just wanted to say I’ve gotten around this by using a Sophisticated backpack with a tank upgrade. In fact it makes the multi-buffer pretty redundant.
