### ISSUE TITLE
Any Refined Storage grid not showing missing items or auto-craftable items

### ISSUE THREAD

**Issue by Faldal** [FTBTeam/FTB-Modpack-Issues#3795]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.0

### Describe the bug

Since update 1.8.0 the Refined Storage grid does not show which items are missing for crafting.
For example, if I use a normal crafting table the items that are missing have a red background (like here https://i.imgur.com/4XUj2a8.png) but that does not happen anymore on any refined storage grid.

Same for the refined storage pattern grid. It used to show which items are auto-craftable with a blue background but that doesn't show anymore either.

### Steps to reproduce

1. Open refined storage crafting grid
2. Select item you do not have the materials to build
3. Hover with mouse over "Move Items" Button

### Expected behaviour

When performing step 3. you should be able to see which exact items are missing when you hover over the "Move Items" button in a refined storage crafting grid.

### Screenshots

normal crafting table:
https://i.imgur.com/4XUj2a8.png

refined storage crafting table:
https://i.imgur.com/bTbWzBE.png

### Additional information
It was fine on the previous version, the issue began with version 1.8.0.

**Comment by UnRealDinnerbone** [comment]
Same as #3839

**Comment by WoodsBandit** [comment]
Here is the other Article UnRealDinnerbone has marked as "Completed" with no resolution. Please Advise am I missing something? Some link to fix the problem or are we still (From Nov 16th, 2023) awaiting resolution....
