### ISSUE TITLE
Silver Crystal doesnt have a further recipe to finish processing the ore.

### ISSUE THREAD

**Issue by 01guil** [FTBTeam/FTB-Modpack-Issues#3796]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.8.0

### Describe the bug

The silver clump to shard recipe only has the water option and it asks for it to go through the same machine twice  for the slurry but doesnt even result in an ingot at the end.

### Steps to reproduce

Check the processing line for iron copper tin gold and lead and compare it to the silver one.

### Expected behaviour

Expected the silver crystal to be processed into dust than smelted

**Comment by pikminman13** [comment]
this is already fixed in 1.9

**Comment by 01guil** [comment]
Oh i see sorry i dont see an option to update in the ftb app :/

**Comment by 01guil** [comment]
When is the 1.9 version getting released?
