### ISSUE TITLE
tpshud:tps error reporting

### ISSUE THREAD

**Issue by logicbug** [FTBTeam/FTB-Modpack-Issues#3799]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.9.0

### Describe the bug

While playing in single user FTBApp screen is constantly logging error:

[19:43:37] [Render thread/WARN]: Unknown custom packed identifier: tpshud:tps

Not sure if this is affecting my game-play, though it's not a good look.

### Steps to reproduce

Playing Legend of the Eyes
Single player mode
In-game
Click on desktop app in desktop panel

### Expected behaviour

I don't expect an error like this to constantly be reported.

### Screenshots

![eyeslog](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/5179818/9e487772-8f0e-4a04-8ff4-fe620cc030cc)

### Additional information

I am  using FTBApp on Linux Mint 21.2

System:
  Kernel: 5.15.0-78-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: Gigabyte model: B550 AORUS ELITE AX V2 serial: <superuser required>
    UEFI: American Megatrends v: F12 date: 01/18/2021
CPU:
  Info: 6-core model: AMD Ryzen 5 2600 bits: 64 type: MT MCP arch: Zen+ rev: 2 cache: L1: 576 KiB
    L2: 3 MiB L3: 16 MiB
  Speed (MHz): avg: 2045 high: 3890 min/max: 1550/3400 boost: enabled cores: 1: 1384 2: 1375
    3: 1375 4: 1556 5: 2887 6: 3890 7: 1375 8: 1375 9: 1375 10: 1552 11: 2637 12: 3769
    bogomips: 81438
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Oland XT [Radeon HD 8670 / R5 340X OEM R7 250/350/350X OEM] vendor: Dell
    driver: amdgpu v: 5.18.13 pcie: speed: 8 GT/s lanes: 8 ports: active: DP-1,DVI-I-1 empty: none
    bus-ID: 0a:00.0 chip-ID: 1002:6610
  Device-2: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 3-4:3
    chip-ID: 046d:0825
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: DisplayPort-0 res: 1920x1080 dpi: 120 diag: 466mm (18.4")
  OpenGL: renderer: AMD Radeon R7 350 (oland LLVM 15.0.3 DRM 3.48 5.15.0-78-generic)
    v: 4.6 Mesa 22.3.0-devel direct render: Yes
Audio:
  Device-1: AMD Oland/Hainan/Cape Verde/Pitcairn HDMI Audio [Radeon HD 7000 Series] vendor: Dell
    driver: snd_hda_intel v: kernel pcie: speed: 8 GT/s lanes: 8 bus-ID: 0a:00.1 chip-ID: 1002:aab0
  Device-2: AMD Family 17h HD Audio vendor: Gigabyte driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 16 bus-ID: 0c:00.3 chip-ID: 1022:1457
  Device-3: Medeli USB 5A type: USB driver: hid-generic,snd-usb-audio,usbhid bus-ID: 1-3:2
    chip-ID: 0a67:8a00
  Device-4: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo bus-ID: 3-4:3
    chip-ID: 046d:0825
  Sound Server-1: ALSA v: k5.15.0-78-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8125 2.5GbE vendor: Gigabyte driver: r8169 v: kernel pcie: speed: 5 GT/s
    lanes: 1 port: f000 bus-ID: 08:00.0 chip-ID: 10ec:8125
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel pcie: speed: 5 GT/s lanes: 1
    bus-ID: 09:00.0 chip-ID: 8086:2723
  IF: wlp9s0 state: up mac: <filter>
Bluetooth:
  Device-1: Intel AX200 Bluetooth type: USB driver: btusb v: 0.8 bus-ID: 1-5:3 chip-ID: 8087:0029
  Report: hciconfig ID: hci0 rfk-id: 0 state: down bt-service: enabled,running rfk-block:
    hardware: no software: yes address: <filter>
Drives:
  Local Storage: total: 1.6 TiB used: 89.62 GiB (5.5%)
  ID-1: /dev/nvme0n1 vendor: Toshiba model: KBG40ZNV256G KIOXIA size: 238.47 GiB
    speed: 31.6 Gb/s lanes: 4 serial: <filter> temp: 33.9 C
  ID-2: /dev/nvme1n1 vendor: SK Hynix model: BC501 HFM256GDJTNG-8310A size: 238.47 GiB
    speed: 15.8 Gb/s lanes: 2 serial: <filter> temp: 39.9 C
  ID-3: /dev/sda vendor: Seagate model: ST3500418AS size: 465.76 GiB speed: 3.0 Gb/s
    serial: <filter>
  ID-4: /dev/sdb vendor: Western Digital model: WD5000AAJS-22A8B0 size: 465.76 GiB
    speed: 3.0 Gb/s serial: <filter>
  ID-5: /dev/sdc vendor: Western Digital model: WD2500AAKX-753CA1 size: 232.89 GiB
    speed: 6.0 Gb/s serial: <filter>
Partition:
  ID-1: / size: 233.18 GiB used: 89.62 GiB (38.4%) fs: ext4 dev: /dev/nvme0n1p3
  ID-2: /boot/efi size: 512 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/nvme0n1p2
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile
Sensors:
  System Temperatures: cpu: 33.0 C mobo: 28.0 C gpu: amdgpu temp: 35.0 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: 3111 note: see --pkg apt: 3087 flatpak: 24
  No active apt repos in: /etc/apt/sources.list
  No active apt repos in: /etc/apt/sources.list.d/amdgpu-proprietary.list
  Active apt repos in: /etc/apt/sources.list.d/amdgpu.list
    1: deb https: //repo.radeon.com/amdgpu/5.4.5/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //ucmirror.canterbury.ac.nz/linux/mint/packages victoria main upstream import backport
    2: deb http: //mirror.fsmg.org.nz/ubuntu jammy main restricted universe multiverse
    3: deb http: //mirror.fsmg.org.nz/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //mirror.fsmg.org.nz/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/opera-stable.list
    1: deb https: //deb.opera.com/opera-stable/ stable non-free
  Active apt repos in: /etc/apt/sources.list.d/rocm.list
    1: deb [arch=amd64] https: //repo.radeon.com/rocm/apt/5.4.5 jammy main
  Active apt repos in: /etc/apt/sources.list.d/spotify.list
    1: deb http: //repository.spotify.com stable non-free
Info:
  Processes: 355 Uptime: 1d 6h 20m Memory: 39.11 GiB used: 3.23 GiB (8.3%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Cinnamon v: 5.8.4 inxi: 3.3.13

**Comment by Gaz492** [comment]
Im not able to reproduce this issue on a fresh install of the modpack.
Have you added any extra mods by any chance?
