### ISSUE TITLE
[Bug, Entangled]: Crash when rendering entangled integrated cable

### ISSUE THREAD

**Issue by weszhuang** [FTBTeam/FTB-Modpack-Issues#380]
### Modpack

FTB OceanBlock

### Modpack version

1.8

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7611202/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7611203/debug.log)
Crash message:
`The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Rendering Block Entity
Exit Code: -1`

### Describe the bug

Crash when rendering/loading Entangled Block entangled to a Integrated Dynamics cable instance with or without things attatched to the cable.

### Steps to reproduce

1. Place any integrated Dynamics cable or attached components(e.g. interfaces, exporters, importers) 
2. place entangled block
3. set entangled target to the cable/components
4. assign entangled block to cable/components

### Expected behaviour

Not crashing when rendering the entangled block

### Additional information

On a server we have running the targeted location of an entangled block inside a compact machine was rebuilt and happened to contain an integrated dynamics cable. Inside the compact machine and outside of the overworld area with the entangled block the players were fine. Upon exiting and rendering or loading (unsure which) the entangled block the players client would crash but the server continues to run fine.

Entangled targets which crash:
1. plain cable
2. individual components(e.g. interfaces, exporters, importers) 
3. components on cable

**Comment by weszhuang** [comment]
There are two related threads in the Entangled github:
[This rendering issue](https://github.com/SuperMartijn642/Entangled/issues/34)'s problem has been identified by the Entangled author as an issue in Integrated Dynamics. He has opened a pull request already within integrated dynamics to fix it: [CyclopsMC/IntegratedDynamics#1114](https://github.com/CyclopsMC/IntegratedDynamics/pull/1114#issue-1065499751)

Also the issue for other future issues with block rendering in entangled blocks has a planned solution in the form of a rendering blacklist for entangled mod as listed in: [this feature request](https://github.com/SuperMartijn642/Entangled/issues/34)

**Comment by Raidobw2** [comment]
Wow thanks a bunch for reporting that to the author as well!

**Comment by weszhuang** [comment]
[Resolution](https://github.com/SuperMartijn642/Entangled/issues/34#issuecomment-982769366)
The pull request submitted to integrated has been merged just need to wait for a new release of Integrated Dynamics now
