### ISSUE TITLE
Chunks not rendering properly

### ISSUE THREAD

**Issue by xWires** [FTBTeam/FTB-Modpack-Issues#3800]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.0

### Describe the bug

Most blocks are not loading in chunks, and they appear invisible instead.

### Steps to reproduce

1. Join a StoneBlock 3 world
2. Reload chunks with F3 + A

### Expected behaviour

Chunks should load properly

### Screenshots

![2023-08-14_10 38 17](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/68852080/54541d1f-c893-4fa0-9918-703076cdfa66)
![2023-08-14_10 37 37](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/68852080/a5026587-7085-4951-a7e0-9766a7f52034)

**Comment by TangledWiresYT** [comment]
Also, forgot to add this, but blocks textures do not update until chunks are reloaded

Examples:

I place a block, I can see the outline but the block itself is invisible until I reload the chunk with F3 + A
I break a block, the block's texture is still there, but I can walk through it.

**Comment by m0lDaViA** [comment]
installed 1.8 today and got the same issues.
https://cdn.discordapp.com/attachments/1139944746794618880/1140751599942258718/image.png

If i try to interact in any way the game crashes.

**Comment by LaplaceNeko** [comment]
Still happening as of today. Any ETA on a fix?

**Comment by UnRealDinnerbone** [comment]
Does this still happen on 1.18.1? And if so can you upload log files please

**Comment by TangledWiresYT** [comment]
> Does this still happen on 1.18.1? And if so can you upload log files please

I assume you mean 1.8.1, as StoneBlock 3 runs on MC 1.18.2, in which case, yes, it is still happening.

Client Log: https://mclo.gs/YSsntEM

**Comment by TangledWiresYT** [comment]
Do not close

**Comment by Gaz492** [comment]
Does this still happen on 1.9.0 for you?
If it does would you be able to share your world so we can take a further look at what the issue may be?

**Comment by xWires** [comment]
I'm unable to test this at the moment as I do not play the mod pack anymore. Sorry!
