### ISSUE TITLE
Various magic quest suggestions (BM remix, orechid, and fluxial generator)

### ISSUE THREAD

**Issue by InfernalGrumbler** [FTBTeam/FTB-Modpack-Issues#3802]
### Modpack

FTB Presents Integration by Parts DX

### Is your suggestion related to a problem? Please describe.

**Problems: fluxial gen/orechid unviable to use despite being heavily gated and bm remix reward (creative activation crystal is pretty useless.**

**Buff orechid/fluxial generator** - Orechid is not viable for most players as it requires 17,500 mana per block and it only activates every 5 seconds. this means it needs 3500 mana/second which is smth like 8 kekimurus just to run(my math may be off but it's still quite a lot of mana to run). It's even worse for the alfheim exclusive fluxial generator which produces barely more than like 2 or 3 endoflames. Basically, it's just super slow and super power hungry.

To improve, make the fluxial generator generate more and the orechid cost less mana per operation. However, make the fluxial generator way more energy hungry, (like 500-1000rf/tick so it's like the lens of the miner it's replacing). It'd be decently balanced since it'd require wireless router bare minimum for energy across dimensions. Would provide more types of ores than mineralis but would be slower and more power hungry as balance. 

Maybe like 900 mana per second costing 1krf/tick with the orechid costing 3500 mana per operation? Just some random numbers I thought up that are better than kekis. Or maybe make it so the fluxial generator can be upgraded with the gears to make it this level, because botania tech mod. 

**Make the creative activation crystal from BM remix useful** - as it stands, it gives a creative activation crystal with a mark of the falling tower. The intention is to give manual, but infinite ore gen I'm assuming. However, the creative activation crystal only works in creative and just acts like a weak activation crystal in survival. Basically, your reward for the remix is a slightly more expensive mark of the falling tower ritual.

First off, if there's an easy way to get something functionally the same as the creative activation crystal, then go with that. If not, Here are some spitball idea:

-masterful machinery late game multiblock for mark of the falling tower that works like the nomifactory microminers with the crystal as a recipe to unlock it. More efficieint LE wise and would give a reasont to automate LE mekanism way plus would work as an alternative to mystical agri.

-Change the reward to something different but equally as good as the creative activation crystal. Maybe like a different way to produce LE that works only in the blood magic dungeon dimension?

**Comment by pikminman13** [comment]
ok, so now that ive gotten a chance to look at this:

like everything in botania, the orechid has no mana number configuration. therefore, i can only change the converter's generation rate.

to remedy, this i have made the converter 5x faster (now producing 5000 mana per second, at the cost of 2k rf/tick). hopefully this addresses that, as it now outproduces the orechid's consumption rate.

as for the blood magic reward, i'm making a multiblock that will handle a lot of the rituals inside of it. of note, you will be able to automate will crystals with it, among the other stuff like lava, trees, ores etc, for a cost of LP.
