### ISSUE TITLE
Mekanism machines can be manually crafted into Factories for much cheaper than the Tier Installer Recipe

### ISSUE THREAD

**Issue by lord-ne** [FTBTeam/FTB-Modpack-Issues#3804]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.8.0

### Describe the bug

You can manually craft e.g. an Enrichment Chamber into a Basic Enriching factory for just a few control circuits and redstone, much cheaper than the recipe for the Basic Tier installer which needs things like Saturated Tau and Stainless Steel. You can do this for all machines and for all tiers.

![2023-08-14 (001)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/34069872/72f57401-4b55-4f32-89ed-85fc24e11f8b)

![2023-08-14 (002)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/34069872/490ebf2b-2ce2-4204-bff0-4a8c2f192167)

### Steps to reproduce

Craft a Mekanism machine such as an Enrichment Chamber into a factory using a few control circuits and alloys; this is much cheaper than the custom recipes for the tier installers.

### Expected behaviour

Upgrading a machine to a factory costs the same or similar amounnt of resources to crafting and using the Tier Installer

**Comment by pikminman13** [comment]
fixed in dev

**Comment by lord-ne** [comment]
It just occured to me that one of the Mekanism machines requires a factory to craft (I think like the Purification Chamber uses a Basic Enriching Factory as an ingredients, or maybe it was something else that uses a Basic Purifying Factory?), so that may be an issue if you entirely remove the upgrade recipes
