### ISSUE TITLE
Crash on Ponder

### ISSUE THREAD

**Issue by Schmidtie-UNFS** [FTBTeam/FTB-Modpack-Issues#3805]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Log Files

[crash-2023-08-15_10.31.02-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12346044/crash-2023-08-15_10.31.02-client.txt)

### Describe the bug

Game crashes when attempting to ponder the industrial turbine for Mekanism. Crashes from both JEI ponder and from quest log.

### Steps to reproduce

1. Search JEI for Turbine parts OR click from quest screen
2. Hold "w" to ponder

### Expected behaviour

Game crash and stacktrace dump to log folder

**Comment by warpath1985** [comment]
exact same issue
