### ISSUE TITLE
Entangled and Refined Storage don't work with each other

### ISSUE THREAD

**Issue by RevolvingMadness** [FTBTeam/FTB-Modpack-Issues#3806]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Describe the bug

The Entangled Mod and Refined Storage Mod don't work with each other.

### Steps to reproduce

1. Entangled the RS Controller onto the wrench
2. Place down a entangled block and right click it with the wrench
3. Try to import items into the RS system with a importer
4. Observe that the items don't go in

### Expected behaviour

Able to import items into your RS system.

### Screenshots

![2023-08-15_20 58 46](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83436020/1219b06e-42c4-433b-a664-2e87fb6132a4)
![2023-08-15_20 58 34](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83436020/8c80b573-c412-46e9-b68c-980b0d7a79cc)

### Additional information

If you try it with a crafter it doesn't light up.

**Comment by RevolvingMadness** [comment]
I just realized there are built-in things for RS but is there any way I could use entangled if I wanted

**Comment by D1veer** [comment]
Same not working in FTB Stoneblock 3

**Comment by Saereth** [comment]
not the engangler cant supply the capabilites for RS, not a bug its just functionality that doesnt exist, you'd need to ask the mod devs to add compat for each other
