### ISSUE TITLE
FTB Stoneblock 3 1.18.0 crashes while launching

### ISSUE THREAD

**Issue by jboschelli0501** [FTBTeam/FTB-Modpack-Issues#3807]
### Modpack

FTB StoneBlock 3

### Modpack version

1.18.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12362714/latest.log)

### Describe the bug

When I go to launch the instance it crashes 

### Steps to reproduce

1. Launch FTB app
2. Open up Stoneblock 3
3. Launch Stoneblock 3
4. Wait a minute 

### Expected behaviour

Fully running application

**Comment by UnRealDinnerbone** [comment]
Are you still unable to load the pack on 1.18.1?
