### ISSUE TITLE
Inconsistent reward for the fridge quest

### ISSUE THREAD

**Issue by Vavorit** [FTBTeam/FTB-Modpack-Issues#3824]
### Modpack

FTB Presents Integration by Parts DX

### Is your suggestion related to a problem? Please describe.

The quest "a good chef always follows the recipe" asks for an oven, and the reward is a heating element for it.
While the quest "Refrigerator-Refrigerador-Freezerator", which asks for a fridge, also gives a heating element for the oven as a reward.
Shouldn't this be a Ice unit for the fridge?

**Comment by pikminman13** [comment]
fixed in dev
