### ISSUE TITLE
Crashes at launch from various mod error 

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#3828]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.9.0

### Log Files

https://pste.ch/obinuboqet.log

### Describe the bug

Crashed at launch from mod loading error with Capsule
relaunching hung at "Waiting for scan to complete" for more than 10 minutes. killed the instance and retried a third time

third time was the charm and resulted in successful launch

### Steps to reproduce

unable to reproduce. 

### Expected behaviour

no crash

### Additional information

I've already launched 1.9.0 in the past so I have no idea what caused it

**Comment by WebDragon** [comment]
Additional Crash log today out of the blue after no additional changes

`CoFH Core (cofh_core) encountered an error during the sided_setup event phase java.util.ConcurrentModificationException: null`

[crash-2023-09-17_14.14.23-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12643429/crash-2023-09-17_14.14.23-fml.txt)

**Comment by WebDragon** [comment]
Additional crash 
`Nature's Compass (naturescompass) encountered an error during the sided_setup event phase` 

[crash-2023-09-21_18.18.56-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12693927/crash-2023-09-21_18.18.56-fml.txt)

**Comment by Gaz492** [comment]
A little late getting back to you on this, as the crashes are different each time I would suggest installing a fresh copy of the modpack and checking if the issue still happens.

**Comment by WebDragon** [comment]
At this point I'm pretty much done with the pack, sadly, as well as it was on my previous computer :) I doubt I would be able to reproduce it at this point, so I'm going to close the bug
