### ISSUE TITLE
solid color screen

### ISSUE THREAD

**Issue by betaomega47** [FTBTeam/FTB-Modpack-Issues#3830]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

feed the beast 

### Describe the bug

ive downloaded 3 different mods and i have the same problem with all of them ive gone in and changed the setting and to try and get the video to play but as soon as it loads and i get into the game i can see for about 3 secs then it goes to a solid color screen and if i move around the colors will change but i cant see anything. ive uninstalled the app and reinstalled several times.

### Steps to reproduce

for me all i did was open the game and as soon as i open the and get into the game its solid color and cant see anything on the screen 

### Expected behaviour

i just want to play the game 

### Screenshots

![Screenshot (1)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/142691269/7c23f788-6cdf-400c-99eb-11a98c668aa2)
![Screenshot (2)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/142691269/d9644da3-d5cd-4774-a46c-136ed032d9a5)
![Screenshot (4)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/142691269/a4e9233d-7868-40a7-856b-842dc3569740)
![Screenshot (5)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/142691269/4386b900-fe4c-41f5-888b-eb757ba07403)

### Additional information

doesn't matter what game i try to play they are all the same

**Comment by Gaz492** [comment]
This looks like it may be a graphics driver issue, I would suggest making sure your computers graphics drivers are up to date.
There is/was a bug with some intel graphics which caused this issue, and updating to the very latest driver supposedly fixed this.
