### ISSUE TITLE
Switch to AutomationBuffers fork to fix issue with inventory size

### ISSUE THREAD

**Issue by lord-ne** [FTBTeam/FTB-Modpack-Issues#3832]
### Modpack

FTB Presents Integration by Parts DX

### Is your suggestion related to a problem? Please describe.

The Multi Buffer cannot be used for some carpenter recipes due to having not enough inventory space. Someone reported this in #3794, and it was closed as unfixable since the mod cannot be configured.

I forked Automation Buffers to fix this issue, and released the fork on CurseForge. As such, I believe you should switch the pack to use this forked version, to fix the above issue.

It uses the same mod id, so no issues with existing worlds. I've been using the fork for a few weeks, and haven't encountered any bugs.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/automation-buffers-fork

Changes from base:
* Increases item capacity to 9 slots
* Increases tank capacity to 20,000mB
* Add comparator support
* Remove unused GUI elements
* Fix some minor bugs and visual issues

**Comment by pikminman13** [comment]
thanks for the reminder, its in now in dev
