### ISSUE TITLE
Fatal exception when trying to update Stoneblock 3 to 1.8

### ISSUE THREAD

**Issue by LasagnaFairy** [FTBTeam/FTB-Modpack-Issues#3834]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8

### Log Files

FTB-DBGIBOZOGUYUG
SUCCESS  Uploaded settings.json: https://pste.ch/oqofirucaw
 SUCCESS  Uploaded version_manifest.json: https://pste.ch/amoyayikib
 SUCCESS  Uploaded console.log: https://pste.ch/cumahawoku
 SUCCESS  Uploaded fml-client-latest.log: https://pste.ch/anenemuyel
 SUCCESS  Uploaded fml-junk-earlystartup.log: https://pste.ch/faguheleqo
 SUCCESS  Uploaded latest.log: https://pste.ch/ozarayupuw
 SUCCESS  Uploaded console.log: https://pste.ch/eyufejecew
 SUCCESS  Uploaded debug.log: https://pste.ch/fikisodira
 SUCCESS  Uploaded latest.log: https://pste.ch/haqegabugo
 SUCCESS  Uploaded rei-issues.log: https://pste.ch/ufulucirep
 SUCCESS  Uploaded rei.log: https://pste.ch/loyovocaxo
 SUCCESS  Uploaded latest.log: https://pste.ch/dejeyaheli
 SUCCESS  Uploaded debug.log: https://pste.ch/sosarerizo
 SUCCESS  Overwolf Logs: file/directory exists
 SUCCESS  Uploaded index.html.log: https://pste.ch/ehasenegip
 SUCCESS  Uploaded background.html.log: https://pste.ch/ukaxevupeb

### Describe the bug

Whenever I try to download the Stoneblock 3 1.8 update, when it is on the Installing Modloader step, it never progresses and I get the error "Fatal exception whilst installing modpack."

### Steps to reproduce

1. Go to the Stoneblock 3 page on the FTB app
2. Click on the update available button to download the update
3. The download screen pops up, stalls on the Installing Modloader step, and returns the "Fatal exception whilst installing modpack."

### Expected behaviour

The modpack updates with no issue

### Screenshots

![Screenshot 2023-08-21 005525](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/142778168/917225d1-5e5e-4298-acb0-b3578d204364)

### Additional information

I have tried totally uninstalling/reinstalling the modpack, FTB, and Overwolf. I cleared the instance folder after uninstalling FTB. I even did a clean install of Java, but nothing has helped this error. This is the second day it's been happening. None of my friends are having the same issue. I'm able to download 1.7.1 Stoneblock 3 just fine, and I'm able to download other modpacks.

**Comment by EnercakQ** [comment]
it does the same thing to me and I don't know how to do it either

**Comment by EnercakQ** [comment]
mayby off antivirus
