### ISSUE TITLE
FTB University 1.19: Mekanism's ore doubling is actually 3 ores into 4 ingots

### ISSUE THREAD

**Issue by Himmla** [FTBTeam/FTB-Modpack-Issues#3835]
### Modpack

FTB University 1.19

### Modpack version

1.0.0

### Describe the bug

Despite of what the quests might make you think, ore doubling is 4 ingots for 3 ores, and ore tripling is true ore doubling (I don't know if it progresses in this way further as I haven't yet built machines for ore "quadrupling")

### Steps to reproduce

The problem is reproducible by smelting ores using Enrichment Chamber and Energized Smelter.

### Expected behaviour

Doubled ingots

**Comment by aaronhowser1** [comment]
I feel a bit silly for missing this 😅 ty for the catch
