### ISSUE TITLE
Game crashes when trying to withdraw items from RF storage

### ISSUE THREAD

**Issue by pandouss** [FTBTeam/FTB-Modpack-Issues#3836]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Describe the bug

When I try to take items from RF storage the game crashes.

### Steps to reproduce

Simply trying to take out items from the grid.

### Expected behaviour

Accessing my items

### Additional information

 I have allowed over 10GB of RAM in the instance.
The grid is connected through a cable 5 blocks above the controller.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
