### ISSUE TITLE
Fatal error and app crashing

### ISSUE THREAD

**Issue by IamStig** [FTBTeam/FTB-Modpack-Issues#3838]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Log Files

https://pastebin.com/WHR501eL

### Describe the bug

The app (and this ONLY happens when loading Unstable) stops loading at about 80% of the bar, the last line  message is "Cleaning up last 500 messages". The launcher screen comes up as if all is OK. The app then crashes to an "Oh ... this doesn't look right" screen. 
Until today a world could be loaded even after the app crashes. Now after selecting and attempting to load the world it is a grayed out screen with "joining world..." that never fully loads.  

### Steps to reproduce

Load the game in the normal way

### Expected behaviour

that it works

### Screenshots

![App crash](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20489424/21141537-0dfd-4dbf-a37b-4ecb92999fc6)
![Untitled](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20489424/7cf222fb-7a82-4877-93f5-49178a567a52)

### Additional information

Additional info is that between Yesterday when I could access the world and Today when I can't is a Windows Update.
The screenshot shows a clock in the top left corner, simple world timer, I have removed the mod to see if that was the problem, it wasn't.
The crashlog seems to be pointing to ElevatorID but I have neither crafted or placed an elevator...... I have bookmarked one.

**Comment by Gaz492** [comment]
A little late getting back to you, updating the mod to the latest 1.20.1 version may also help as the change log mentions a null player fix which is what you are running into.
If that doesnt work you could also try disabling the mod as this will remove any trace of it from your world.
I would recommend making a backup of the world before attempting either of these.
