### ISSUE TITLE
Missing items not showing in REI (Crafting Grid)

### ISSUE THREAD

**Issue by andr3eee1** [FTBTeam/FTB-Modpack-Issues#3839]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.0

### Log Files

https://mclo.gs/gjVQqAO

### Describe the bug

When you open the crafting grid from refined storage and then click a recipe from the right it won't show what items you don't have, but show only "Missing Items" with red.

### Steps to reproduce

1. Open the Crafting Grid from the refined storage mod.
2. Click a recipe from the REI that you can't make.
3. Hover over the plus bottom in the right corner of the recipe.

### Expected behaviour

Normally de plus should have a red background and when hovering over an item it should have a red background too.

### Screenshots

Bug:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/81253375/ff827fd1-516f-4499-96f4-3dbdb082f5fc)
Expected:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/81253375/3f4f166b-bd0a-4fc9-a450-e54028548aa5)

### Additional information

Sorry for my bad English.

**Comment by AnonymousTM** [comment]
Same problem!

**Comment by WoodsBandit** [comment]
I see two closed Articles about this Problem. I am playing in the UniversIO pack and am having the same issue. It is incredibly frustrating. Both of these Articles are "closed" yet I see not resolution. Is this a simple config issue we can address OR are we will awaiting a BUG fix? Please Advise...

**Comment by JanSchuermannPH** [comment]
Having the same problem. Simply labeling it as a mod issue and closing the issue isn't a solution.

**Comment by UnRealDinnerbone** [comment]
The pack has been updated since this issue was created and REI version has changed. Does this issue still happen in the latest version of pack?

**Comment by andr3eee1** [comment]
> The pack has been updated since this issue was created and REI version has changed. Does this issue still happen in the latest version of pack?

Yes it does!  Sorry for late reply, I had a medical issue!

**Comment by dave36464736** [comment]
Can confirm having same issue. Would you like me to open a new one?

**Comment by andr3eee1** [comment]
Yep, you could!

**Comment by dave36464736** [comment]
has been done. Glad to know Im not the only person. Thought I was going crazy.

**Comment by seacucu** [comment]
I'm having the same issue. Any update on this?

**Comment by lev-corrupted** [comment]
This is really ruining the game... hahaha the tinker station has no problem with this while having a storage nearby by but when u use refined storage, which is the most important and late game crafting system, with this bugggg, it's frustrating af

**Comment by petrvavra420** [comment]
> This is really ruining the game... hahaha the tinker station has no problem with this while having a storage nearby by but when u use refined storage, which is the most important and late game crafting system, with this bugggg, it's frustrating af

Hello, i was facing this bug myself. I found the easiest way is to replace REI with JEI.
