### ISSUE TITLE
FTB University 1.19: Running empty command (/) triggers kick [Connectivity bug]

### ISSUE THREAD

**Issue by RPMYT** [FTBTeam/FTB-Modpack-Issues#3840]
### Modpack

FTB University 1.19

### Modpack version

1.1.0

### Log Files

https://mclo.gs/3ZTPiSN

### Describe the bug

Title.

I've provided my [playerdata](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12435558/f00ca274-754f-428a-b6bf-1769bff86c65.gz) here, if it's of any use.

### Steps to reproduce

Log onto a server
Run `/`
???
Profit!

### Expected behaviour

...to *NOT* get kicked for running an empty command to test lag???

### Screenshots

![Error SS](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45874270/5ed4e680-d376-4167-9fc0-4a8522f2f713)

**Comment by aaronhowser1** [comment]
Doesn't happen now, assumed a mod update fixed it and I forgot to check
