### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by RedKnite5** [FTBTeam/FTB-Modpack-Issues#3843]
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Log Files

[crash-2023-08-23_09.56.25-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12441845/crash-2023-08-23_09.56.25-server.txt)

### Describe the bug

Minecraft crashed. When I restart it, it works fine for a few hours before crashing again, so I'm not sure its always the same thing.

### Steps to reproduce

I'm not sure. It happens in a wide variety of situations. I had been working on my AE2 network, but at the moment I was just looking through jei.

### Expected behaviour

It to not crash

**Comment by Gaz492** [comment]
It looks like integrated dynamics is trying to read a non-existent inventory and causing the game to crash.
We may look at releasing an update to this pack that fixes this issue and a few others. 

!skip

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

We may have something up our sleeves, some may call it a remaster, keep an eye out on our social media platforms for more information.
