### ISSUE TITLE
Pulverizer to generous

### ISSUE THREAD

**Issue by impatus** [FTBTeam/FTB-Modpack-Issues#3846]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.10.0

### Describe the bug

Pulverizer from Thermal outputs 36 Aquamarine from 1 Aquamarine Shale.
Its supose to give 6

Either JEI shows wrong or the output is wrong.

that was with no catalyst in the bottom. don't know if that would have given even more.

### Steps to reproduce

Put Aquamarine Shale in pulverizer

### Expected behaviour

expected to get 6 aquamarine

**Comment by pikminman13** [comment]
i get 6 aquamarine with no catalyst and more with catalyst

**Comment by impatus** [comment]
yeh seems like it just bugge out for me. tried again today and now im getting normal amounts.
no idea why this happened.

**Comment by pikminman13** [comment]
maybe you had "residual" catalyst in the slot. i think it does that sometimes. closing it now if it works for you.
