### ISSUE TITLE
Cyclic Obsidian Shears not dropping modded leaves.

### ISSUE THREAD

**Issue by OdisAxe** [FTBTeam/FTB-Modpack-Issues#3848]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.10

### Describe the bug

Cyclic obsidian shears don't drop "treemendous" walnut leaves. They work as intended on vanilla MC blocks.

### Steps to reproduce

Use Cyclic Obsidian Shears on Treemendous Walnut leave block and nothing drops.

### Expected behaviour

Drops walnut leave block

**Comment by pikminman13** [comment]
i just removed and hid them. obviously if you have them you can still use them, but there are plenty of other shears that do work.
