### ISSUE TITLE
Crash on specific JEI page

### ISSUE THREAD

**Issue by doomclownn** [FTBTeam/FTB-Modpack-Issues#3849]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.10.0

### Describe the bug

When looking thru the JEI pages, it suddenly crashed, and when i rechecked it crashes around the 50-60 page, not sure which tho.
EDIT: just now  checked and it also corrupts save files/inventory

### Steps to reproduce

1. Open inventory
2. Scroll on JEI until 50-60
3. Crash

### Expected behaviour

To not crash

**Comment by pikminman13** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40
