### ISSUE TITLE
[Bug]: Crash on render Refined Storage Pattern for Project Red blocks

### ISSUE THREAD

**Issue by weszhuang** [FTBTeam/FTB-Modpack-Issues#385]
### Modpack

FTB OceanBlock

### Modpack version

1.8 + 1.9

### Log Files

[crash-2021-11-27_21.57.19-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7612881/crash-2021-11-27_21.57.19-client.txt)

### Describe the bug

Crash upon previewing(pressing shift with pattern in inventory) a Refined Storage pattern set to craft placeable component from ProjectRed(e.g. toggle latch, or gate...) or upon viewing the Recipe from within the crafter manager.

It appears to crash for all of the placeable redstone circuit blocks from ProjectRed. The crafting items used to make them do not cause a crash in the same fashion.

### Steps to reproduce

1. Make a Refined storage pattern for crafting the ProjectRed Component
2. Preview the component by shift in inventory or within crafter manager or crafter

### Expected behaviour

no crash

**Comment by weszhuang** [comment]
will retest in latest version to see if its fixed already

**Comment by Raidobw2** [comment]
Thanks for the report. Were just waiting on the mod update for #151, I don't think it came out yet from checking their changelogs. ProjectRedIntegration made a patch for it to prevent the crash but I think it's still in-dev only. You can follow the other issue if you want to know when we'll resolve it.
