### ISSUE TITLE
Rare castle kit blueprint shows wrong recipe

### ISSUE THREAD

**Issue by Vavorit** [FTBTeam/FTB-Modpack-Issues#3852]
### Modpack

FTB Presents Integration by Parts DX

### Is your suggestion related to a problem? Please describe.

When deploying the Rare Castle Kit blueprint, it places a lectern with a book.  In the book are instructions how to change the One Use capsules to blueprints, with the materials in the chests (placed with the deploy)
The recipe in the book tells to place lapis lazuli besides the capsule, but it has to be blue dye for the recipe to work.

**Comment by pikminman13** [comment]
this is a default capsule that came with the mod and im not changing it
