### ISSUE TITLE
Moving Spawners with a Moving Wand disables spawning

### ISSUE THREAD

**Issue by danilluzin** [FTBTeam/FTB-Modpack-Issues#3853]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.10.0

### Describe the bug

Moving Spawners with a Moving Wand stops them from spawning. 
After picking up a mob spawner (tested on both Blaze spawner that was moved into the overworld and a Zombie spawner) and moving it or just placing it back down turns it off completely.

### Steps to reproduce

1. get a Moving Wand from [Not Enough Wands](https://www.curseforge.com/minecraft/mc-mods/not-enough-wands)
2. pick up any spawner
3. place it down somewhere
4. spawning stops.

### Expected behaviour

spawner shouldn't be neutered after moving

**Comment by pikminman13** [comment]
i think a block update might fix it. i cant do anything about it otherwise.

**Comment by danilluzin** [comment]
One solution I have found is logging out and logging back again. This seems to fix it!
