### ISSUE TITLE
core AE2 quest is dependent on prior optional quest

### ISSUE THREAD

**Issue by revelae** [FTBTeam/FTB-Modpack-Issues#3854]
### Modpack

FTB University 1.19

### Modpack version

1.1.0

### Describe the bug

ME glass cables quest "you basic" is locked by previous optional ME energy acceptor quest "me and mine"

### Steps to reproduce

1. normal progress through ae2 questline
2. skip optional quest
3. discover it is not optional

### Expected behaviour

not to get stuck on cables quest

**Comment by aaronhowser1** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/15698722/678eb64d-74af-4380-8992-ef61c3779d14)
Cannot replicate
