### ISSUE TITLE
Free Creative Reclamation Chambers

### ISSUE THREAD

**Issue by Ivan2OO5** [FTBTeam/FTB-Modpack-Issues#3855]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.10.0

### Describe the bug

You can get infinite amount of Creative Reclamation Chambers from The Mix Mart without paying 200 Bio-Napalm Cells

### Steps to reproduce

1) Finish Thermal Remix
2) Get 200 Bio-Napalm Cells
3) You will see *Quest Completed* message
4) Receive Creative Reclamation Chamber and reset quest
5) Move at least 1 Bio-Napalm Cell to another slot of your inventory and you will see *Quest Completed* message again and will be able to receive the reward again
6) Repeat from step 4

**Comment by pikminman13** [comment]
i already fixed this in dev
