### ISSUE TITLE
Botania tall flower duplication

### ISSUE THREAD

**Issue by youixentoo** [FTBTeam/FTB-Modpack-Issues#3856]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.1.0

### Describe the bug

Using a cyclic item user on a botania mystical tall flower, with 'use left hand' turned on, drops a copy of the flower. 

### Steps to reproduce

1. Place item user, select 'use left hand'
2. Place mystical tall flower in front

### Expected behaviour

I don't know, it's not a block breaker

### Screenshots

https://youtu.be/_Xo9EazQh8Y

**Comment by pikminman13** [comment]
its this or you dont get backported shearless flower breaking

**Comment by youixentoo** [comment]
I wouldn't mind, tried using shears before this after block breakers and pistons didn't work.

**Comment by pikminman13** [comment]
alright i redid the script and added to it and now it should just break it
