### ISSUE TITLE
Cant reset *The Mix Mart* quest

### ISSUE THREAD

**Issue by Ivan2OO5** [FTBTeam/FTB-Modpack-Issues#3857]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.11.0

### Describe the bug

I took the reward and left this quest without clicking command button, when I returned to this quest, command button disappeared

### Steps to reproduce

1) Give items to quest
2) Take reward (dont click on reset quest button)
3) Leave quest menu
4) Go back to quest menu and look at the quest

### Expected behaviour

Tell me ID of this quest, so I reset it with command

### Screenshots

![2023-08-31_18 06 12](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/143195765/01392ea8-227b-4f38-8e51-b1fc9803c6f8)

**Comment by pikminman13** [comment]
you are not intended to reset this quest
