### ISSUE TITLE
grave bug 

### ISSUE THREAD

**Issue by yulik05** [FTBTeam/FTB-Modpack-Issues#3858]
### Modpack

FTB University 1.19

### Modpack version

1.1.1

### Describe the bug

Honestly i was afk, when some mobs killed me and i've respawned and the grave is gone

### Steps to reproduce

1. Stay at glass pane
2. Use /kill to test
3. That's grave is gone.

### Expected behaviour

stay out glass pane

**Comment by aaronhowser1** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/15698722/8230d151-b7d0-422c-86f1-afe9b04d7586)
Are you sure it didnt just put the grave way up to the top of your house?

**Comment by yulik05** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/66960588/d78ccbd7-28a1-4454-91e9-00cec1e180c2)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/66960588/1edb389f-fa93-468e-9bb6-8f168d09041e)

it didnt
