### ISSUE TITLE
[Bug]: Ritual of the Martyr causes a ticking server crash

### ISSUE THREAD

**Issue by zoller27osu** [FTBTeam/FTB-Modpack-Issues#386]
### Modpack

FTB University 1.16

### Modpack version

1.3.0

### Describe the bug

https://github.com/Ipsis/Woot/issues/550

### Steps to reproduce

1. Using the Ritual Diviner [Dusk], build the Ritual of the Martyr above a Woot factory with a Flayer perk.
2. Activate the Master Ritual Stone with a Weak Activation Crystal
3. Congratulations, your world is essentially corrupted! It will instantly crash on every start-up unless the Master Ritual Stone is deleted using external tools, or an unofficial Woot version is installed.

### Expected behaviour

The Flayer perk and/or the Ritual of the Martyr should be dis-allowed until this is fixed

**Comment by aaronhowser1** [comment]
Gotta love months-old issues with an existing fix that hasn't been implemented by the dev. Disabling those Upgrade Keys.

**Comment by zoller27osu** [comment]
The un-accepted fix does work perfectly btw!

**Comment by aaronhowser1** [comment]
Problem is that you would have to import and build the mod yourself

**Comment by Raidobw2** [comment]
@aaronhowser1 If you still want to have that ritual in the pack https://www.curseforge.com/minecraft/mc-mods/woot/files/3587754
![image](https://user-images.githubusercontent.com/17010632/147851385-848eb4cd-a9fe-475c-9eb3-7f78e2aa603e.png)
https://github.com/Ipsis/Woot/issues/550
