### ISSUE TITLE
Crash after entering to school SCS on colab

### ISSUE THREAD

**Issue by MehanikTMYT** [FTBTeam/FTB-Modpack-Issues#3860]
### Modpack

FTB University 1.19

### Modpack version

1.1.1

### Log Files

https://pastebin.com/vH05yWiW

### Describe the bug

I enter to SCH school and after some seconds waiting and crash, server started on Google Colab, in single this bug isn't worked (maybe)

### Steps to reproduce

Go to quests, click enter to school (SCH)

### Expected behaviour

no crash

**Comment by aaronhowser1** [comment]
This crash was due to lag. I assume this is because the server was on a free host (Google Colab), which aren't known for their quality. I'll try to make the file size of the school structure smaller.
