### ISSUE TITLE
Opencomputers causes server to crash and unable to restart

### ISSUE THREAD

**Issue by JNash1232** [FTBTeam/FTB-Modpack-Issues#3861]
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Log Files

[crash-2023-09-03_00.40.18-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12504982/crash-2023-09-03_00.40.18-server.txt)
[crash-2023-09-03_00.37.47-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12504983/crash-2023-09-03_00.37.47-server.txt)
[crash-2023-09-03_00.51.17-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12504984/crash-2023-09-03_00.51.17-server.txt)

### Describe the bug

Server crashes and will not start if you connect an opencomputer block to any power

using spectral coils seem to be the only way to power opencomputers without killing the server.

### Steps to reproduce

Place open computer on any power cable and watch the server close

### Expected behaviour

server to not crash and opencomputer to consume power

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

We may have something up our sleeves, some may call it a remaster, keep an eye out on our social media platforms for more information.
