### ISSUE TITLE
Using over 13gb ram with Sky Factory 3

### ISSUE THREAD

**Issue by vqnv** [FTBTeam/FTB-Modpack-Issues#3864]
### Modpack

FTB Presents Skyfactory 3

### Modpack version

1.10.2

### Describe the bug

While playing, I frequently start at around 4 - 5gb ram usage. After a few minutes, ends up at 13gb and crashes. I've tried redownloading the modpack, driver updates, different launch arguments and testing with capping at different maximums with memory. Also tried launching with different versions of java and tried both curseforge and the FTB launcher.

Nothing has really worked, anyone lmk if you have an issue related to this, or a possible fix  (or information you might need). It really does suck not being able to play this modpack.

### Steps to reproduce

1. Start game
2. Load into world

### Expected behaviour

Normal usage around 4 - 6Gb. Eventually rises to about 13gb until game crashes.

**Comment by KaranKapur123** [comment]
Hi, were you able to find a solution?

**Comment by vqnv** [comment]
Nah

**Comment by Gaz492** [comment]
May I ask how much memory you have assigned to the pack?
I would only recommend giving it around 6GB of memory, as anything higher can cause issues and make memory leaks more apparent.
Unfortunately, due to the age of the modpack it's unlikely that the pack will get any further updates, so this issue is likely to stay.

**Comment by PapyrusOfficial** [comment]
I too have this issue. I allocated 4GB of memory and SF3 would take up 26GB of ram within a matter of 5-10 minutes. I have also done everything listed above and am still experiencing this issue.

**Comment by poketen** [comment]
I had the same Issue, I reinstalled the Profile with a older Version of Skyfactory 3, to be exact ( FTB-Presents-SkyFactory-3_3.0.20.zip ) i allocated 3.1 GB and it works perfectly fine. wont go over 4.700 MB in the Task manager.
