### ISSUE TITLE
wooden crank AE2

### ISSUE THREAD

**Issue by Alex09035** [FTBTeam/FTB-Modpack-Issues#3866]
### Modpack

FTB University 1.19

### Modpack version

1.1.1

### Describe the bug

I can't put the wooden crank in the charger because if I try it it breaks and I have it back in the inventory the wooden crank and there are no chunks claimed in AE2

### Steps to reproduce

1 go to charger
2 I try to put the wooden crank in hte charger
3 broke the item 

### Expected behaviour

i think that i can put 

### Screenshots

![2023-09-04_18 31 52](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/92629821/c9c067c7-e1ed-43a0-a797-38872d20cca3)

**Comment by aaronhowser1** [comment]
You need to sneak right-click the top of the Charger, not the wall behind it. I'll mention this in the quest.
