### ISSUE TITLE
Server Installer unable to download JRE

### ISSUE THREAD

**Issue by TheCheatCode** [FTBTeam/FTB-Modpack-Issues#3869]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.12

### Log Files

https://pastebin.com/7pwTQqRk

### Describe the bug

When running serverinstall_101_6503.exe it downloads 1068 files and fails to download one:

Error downloading https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.2%2B8/OpenJDK17U-jre_x64_windows_hotspot_17.0.2_8.zip: server returned 403 Forbidden

### Steps to reproduce

1. download the server files from FTB for Direwolf20 1.19
2. run serverinstall_101_6503.exe
3. after 1049 mods successfully download, you will get an error message
4. It will ask if you want to continue anyway, selecting Yes will immediately close the window with a split second to read that it failed to extract jre/jre.zip

### Expected behaviour

The server to install successfully

**Comment by denizkoekden** [comment]
Hello,
I have the same error with Stoneblock 3

**Comment by GenuineJakob** [comment]
I was able to manually download the file, does anyone know where to place it and under which name so the installer will continue?

**Comment by ThePaul-T** [comment]
A fix for this has been deployed.

**Comment by jvgoch** [comment]
I'm having the same issue but on a itzg/minecraft-server docker image.
`Error downloading https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.2%2B8/OpenJDK17U-jre_x64_linux_hotspot_17.0.2_8.tar.gz: server returned 403 Forbidden`
Was it also fixed for the linux version of the pack?
