### ISSUE TITLE
fails to download parts on latest update

### ISSUE THREAD

**Issue by timbob1980** [FTBTeam/FTB-Modpack-Issues#3871]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.12.0

### Describe the bug

when running the installer the files start to download and then a meaage appears saying some files failed to download and then another message about it couldnt find something or link to something and then installer closes 

### Steps to reproduce

try to install the updated files with a fresh install into a new folder 

### Expected behaviour

says it fails to gather all files

**Comment by pikminman13** [comment]
does 1.11 still work?
