### ISSUE TITLE
EMI's crafting recipe fill in is broken on RFTools Storage Scanner

### ISSUE THREAD

**Issue by virtualgurel** [FTBTeam/FTB-Modpack-Issues#3872]
### Modpack

FTB University 1.19

### Modpack version

1.2.0

### Describe the bug

When I pressed the fill in button(+ button) from EMI to fill it in the RFTools Storage Scanner it placed items in the wrong slots.

### Steps to reproduce

1. Open RFTools Storage Scanner.
2. Open a recipe from EMI. (Not recipe specific)
3. Press the + button on the bottom right corner of the recipe.
4. It fills in the wrong slots.

### Expected behaviour

EMI filling in the correct recipe.

### Screenshots

![Ekran görüntüsü 2023-09-09 001156](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/113795958/e38de5b4-1110-4291-8d31-fb3b2138d920)

**Comment by Norcim133** [comment]
Same experience

**Comment by Norcim133** [comment]
Same thing with Integrated Dynamics. Fills in the wrong recipe.

Also doesn't highlight in red the missing ingredients when you hover over the plus button.

<img width="981" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/19489960/1421b063-e98e-4206-9e7c-b8231ec2ccd8">

**Comment by Norcim133** [comment]
I tried upgrading to EMI 1.0.21 and it solved the problem with the RF Storage Scanner.
