### ISSUE TITLE
Accessing refined storage system causing game to crash

### ISSUE THREAD

**Issue by DinkaFox** [FTBTeam/FTB-Modpack-Issues#3873]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Log Files

[crash-2023-09-08_21.11.23-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12564360/crash-2023-09-08_21.11.23-client.txt)

### Describe the bug

When trying to grab items from a refined storage system, the game crashes.
I have tested in single player and multiplayer. It does not seem specific to any item when testing in creative. Others on a multiplayer server have experienced this issue as well.
The world is generated on V1.5.0.

### Steps to reproduce

1. Create a new world(Use creative for simplicity but this occurs in survival as well)
2. Grab a refined storage controller, coloring does not matter
3. Grab a refined storage disk drive
4. Grab a refined storage disk(Any size)
5. Grab a refined storage grid(Any grid is fine)
6. Place the disk drive, controller and storage grid in any area where all 3 blocks are touching each other
7. Right click on the disk drive and place the disk into it
8. Grab blocks from some power source(Powah reactor or solar panels will work. Make sure to grab appropriate cables to transfer power and connect it to the controller)
9. Once the controller is powered, grab any item to use with the storage system
10. Right click on the grid
11. Place the item into the storage inventory
12. Try to take the item out
13. See game crash

### Expected behaviour

The item gets taken out of storage and into the player inventory and the game doesn't crash

**Comment by DinkaFox** [comment]
Issue is in REIPluginCompatibilities jar file. 
Looked up an updated jar version and used that, 12.0.88(Modpack is on 12.0.55).
When updating the version, Roughly enough items needed to be updated as well. Used version 12.0.652(Modpack is on 12.0.634)

Created a duplicate of my server with these two jar files replaced and the storage system is now working. Able to successfully take out items and place items in.
Unsure of other effects this version upgrade may have with the modpack but wanted to provide additional information.

**Comment by DinkaFox** [comment]
Issue has been reported in #3836 and #3778 so I'm closing this ticket to remove duplicate issues.

**Comment by vhhawk** [comment]
Thank you so much for posting this. Saved me a bacon load of problem.
