### ISSUE TITLE
Infinite Crafting Dupe

### ISSUE THREAD

**Issue by yhwachlol** [FTBTeam/FTB-Modpack-Issues#3874]
### Modpack

FTB One

### Modpack version

2.7.0

### Describe the bug

Whenever crafting stackable items, shift + right click will give you a full stack of said item while only consuming a single recipe's worth of resources.

### Steps to reproduce

1. Open any crafting GUI (Vanilla, have not tested for non-vanilla crafting GUIs}
2. Input recipe for any stackable item
3. Shift + Right Click on the output

### Expected behaviour

The expected behaviour is a singular item being crafted, rather than a full stack.

**Comment by Thorton101** [comment]
Hi there,

even that the post is 3 weeks old, the bug still exists.
I started the pack several days ago and noticed the dupe bug in inventory crafting grid (made some torches) and
also in the tinkers-like crafting table.
