### ISSUE TITLE
crash from kubejs when invalid tetra scroll in inventory

### ISSUE THREAD

**Issue by adrianmgg** [FTBTeam/FTB-Modpack-Issues#3875]
### Modpack

FTB University 1.19

### Modpack version

1.2.0

### Log Files

https://gist.github.com/adrianmgg/31687019f4d87fd73e7b56a2837a0b40

### Describe the bug

A tetra scroll with missing nbt data being in the player's inventory will crash the game (which wouldn't be as much of an issue if the only way to get one was to manually spawn it in, but creative mode 'pick block'ing a placed scroll(s) will put an nbt-less one in your inventory).

### Steps to reproduce

steps:
1. either
   1. give yourself any valid tetra scroll
   1. place the valid scroll down in the world
   1. in creative mode, 'pick block' the placed scroll

   or just
   1. do `/give @s tetra:scroll_rolled`
1. the game should crash to desktop very soon after the nbt-less scroll enters your inventory

optionally also try:
1. start the game up again
1. try to open that world
1. the world should fail to load and kick you to an "invalid player data" error screen

### Expected behaviour

not crashing

### Additional information

the crash happens in the `checkScrollType` function in `server_scripts/quests/custom_filters/schematics.js`
```javascript
let checkScrollType = (itemstack, searched) => {
  const item = itemstack.getIdLocation()

  if (item != 'tetra:scroll_rolled') return false

  const nbt = itemstack?.nbt
  const scrollType = nbt?.BlockEntityTag?.data[0]?.key

  return scrollType.includes(searched)
}
```

there's no [optional chaining `?.`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) on the `[0]` in `nbt?.BlockEntityTag?.data[0]?.key`, so when any of the preceding accesses in the chain are null/undefined it will error out when it hits the `[0]` with a `rhino.EcmaError: TypeError: Cannot read property "0" from undefined`

making this change to the script[^rhino_opt_chain_support] and trying again prevents the crash, and the relevant quests still seem to work fine
```diff
diff --git a/schematics.js.original b/schematics.js
index 0d853cc..57d381c 100644
--- a/schematics.js.original
+++ b/schematics.js
@@ -20,7 +20,9 @@ let checkScrollType = (itemstack, searched) => {
   if (item != 'tetra:scroll_rolled') return false
 
   const nbt = itemstack?.nbt
-  const scrollType = nbt?.BlockEntityTag?.data[0]?.key
+  const data = nbt?.BlockEntityTag?.data
+  if (data == null) return false
+  const scrollType = data[0]?.key
 
   return scrollType.includes(searched)
 }
```
[^rhino_opt_chain_support]: using the `?.[expr]` style optional chaining would be cleaner here but rhino doesn't seem to support that

**Comment by Norcim133** [comment]
I'm getting an "Invalid player data" message when I try to connect to my server with tetra scrolls in my inventory. One of the error messages references schematics.js

**Comment by aaronhowser1** [comment]
Fixed! Ty

**Comment by aaronhowser1** [comment]
@Norcim133 I don't suppose you still have that crash report? Long shot ik
