### ISSUE TITLE
Server will not start

### ISSUE THREAD

**Issue by Al7778** [FTBTeam/FTB-Modpack-Issues#3877]
### Modpack

FTB University 1.19

### Modpack version

1.2.0

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12568157/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12568158/latest.log)

### Describe the bug

Server will not start,

### Steps to reproduce

1 Downloaded new server files.
2 installed server files
3 started server
4 server will not launch
5 repeated steps 1 thru 4 on different computer with same results

### Expected behaviour

Server to run

### Additional information

Had a previous issue with 1.2.0 on the same day with error - downloading https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.7%2B7/OpenJDK17U-jre_x64_windows_hotspot_17.0.7_7.zip: server returned 403 Forbidden. Went to discord, they fixed that, then this problem cropped up. Posted new problem in discord with no replies or answers, so posted here.

**Comment by aaronhowser1** [comment]
Crash is due to a clientside mod being loaded serverside. That mod isn't in the pack though so 🎉
