### ISSUE TITLE
owo handshake failure

### ISSUE THREAD

**Issue by Nessuno6** [FTBTeam/FTB-Modpack-Issues#3878]
### Modpack

FTB Unstable 1.20: Fabric

### Modpack version

1.20.0

### Log Files

https://pastebin.com/fYgWQ57b

### Describe the bug

when I try to enter in a server that I created with gamehosting; the owo mod gives me that problem

### Steps to reproduce

go on multiplayer, connect to a server and wait

### Expected behaviour

I expected to enter the server but it doesn't happen

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/77236974/17ac5748-83f1-45cd-9e32-a86d6d09c60d)

### Additional information

I sadly can't remove the owo mod

**Comment by Louiess** [comment]
I had this problem and trying to figure this out for 2 hours now, seems like uninstalling the mod is the only solution :(

**Comment by 302XXX** [comment]
> У меня возникла эта проблема, и я пытаюсь разобраться в ней уже 2 часа, похоже, что удаление мода - единственное решение:(

ты нашёл решение?
