### ISSUE TITLE
Stoneblock 3 crash cause of tunnel

### ISSUE THREAD

**Issue by MacaronFR** [FTBTeam/FTB-Modpack-Issues#3879]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.0

### Log Files

https://pastebin.com/h2p1zXJq

### Describe the bug

Instance randomly crashes at first view because of create brass tunnel

### Steps to reproduce

1. New world
2. Use many tunnel at relatively high speed
3. Wait
4. Crash happen

### Expected behaviour

No crash

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
