### ISSUE TITLE
[Bug]: Breaking Environmental Tech Ore Miner duplicates items

### ISSUE THREAD

**Issue by RobertBouillon** [FTBTeam/FTB-Modpack-Issues#388]
### Modpack

Direwolf20 1.16

### Modpack version

1.11

### Describe the bug

Breaking Environmental Tech Ore Miner duplicates items

### Steps to reproduce

1. Place a void ore miner block into the world
2. Place any item into the flash memory slot
3. Break the void ore miner block

The ore miner block breaks and ejects the items into the world. Replacing the block allows you to remove the items you placed, effectively duplicating the items.

### Expected behaviour

The ore miner will either retain or eject the items in flash memory slot, not both.

**Comment by Raidobw2** [comment]
Thanks for the report! Linked to #318.
