### ISSUE TITLE
Tombstone don't disappear in Dimensional Dungeons

### ISSUE THREAD

**Issue by philippewarren** [FTBTeam/FTB-Modpack-Issues#3880]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.8.0

### Describe the bug

If you die in a Dimensional Dungeon, you can come back and get your stuff back by using the key on your tomb, same as you can do in any other dimension.

In Dimensional Dungeons though, the tomb won't disappear, and you can't break it either.
In some cases, it can block paths in the dungeon.

The Dimensional Dungeons has an entry telling server admins to add the tombstone block to a whitelist of breakable blocks in these dungeons:

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/55722645/0c96559b-d077-4412-8b95-7d85b5a6421d)

This configuration could be set in the default configuration of the pack so that if works by default.

The ID of the block is `simpletomb:tombstone`. 

### Steps to reproduce

1. Teleport in a Dimensional Dungeon using the portal and a key.
2. Die.
3. Come back and pick-up yout tomb using the key.
4. The tomb won't disappear.

### Expected behaviour

The tomb disappears, as it does in any other dimension.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/55722645/7219aa4f-15c2-475d-a385-f002e131a329)

**Comment by pikminman13** [comment]
this did not fix anything. the ID is correct, though.

**Comment by pikminman13** [comment]
ok, so apparently it does work with a pickaxe. right click does not make it disappear but does reclaim the inventory.
