### ISSUE TITLE
[Bug]: My Mod freezes when i try to boot it up

### ISSUE THREAD

**Issue by CJW1004** [FTBTeam/FTB-Modpack-Issues#3881]
### Mod

Abe pack

### Mod version

1.0.1

### Forge / Fabric version

202308162122-46a8a2536d

### Modpack & version

Abe pack 1.0.1

### What issue are you having?

when i press play and mod begins to load it freezes on the same step every time.

![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/144640159/48ed2c60-bf3d-4b54-b587-ad6b9f5bec6f)

### Steps to reproduce

I downloaded the pack and hit play

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
