### ISSUE TITLE
I installed a couple of mods and now the game doesnt want to start

### ISSUE THREAD

**Issue by Sajns** [FTBTeam/FTB-Modpack-Issues#3882]
### Modpack

FTB Direwolf 20 1.19

### Modpack version

1.12.0

### Log Files

[crash-2023-09-12_01.17.52-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12581043/crash-2023-09-12_01.17.52-client.txt)

### Describe the bug

I installed a couple of mods to the game and now it doesnt want to start, what shall I do so I can play again?

### Steps to reproduce

c

### Expected behaviour

I want help so I can play again.

**Comment by DelusionalWizard** [comment]
Delete the self installed mods and see if it works again

**Comment by Sajns** [comment]
It's working now but the games is too laggy to play so I'm playing an other modpack now.
