### ISSUE TITLE
Custom tree leaves have persistent: true tag

### ISSUE THREAD

**Issue by KazzaKING** [FTBTeam/FTB-Modpack-Issues#3883]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.9.0

### Describe the bug

Leaves generated have persistent: true tag

### Steps to reproduce

Generate the world and F3 on the leaves

### Expected behaviour

For leaves to be able to delay via the fastdecay mod

**Comment by DinnerBeef** [comment]
Sadly, this won't be able to be fixed due to how the world gen mod works.
