### ISSUE TITLE
Created harvesting glyph, now game closes seconds after starting

### ISSUE THREAD

**Issue by Bluesingingsea** [FTBTeam/FTB-Modpack-Issues#3884]
### Modpack

FTB Presents AbePack

### Modpack version

1.0.3

### Describe the bug

The game was running smoothly up until I decided to create a harvesting glyph from the ars nouveau mod pack. I placed the hoe and earth sigil thing to create, and as the harvesting glyph is being created, the game closes. Every time I try to hop back in, the glyph is in the process of being made, and then when it's "complete" it closes. Probably takes ~4ish seconds for the whole process to take place. 

### Steps to reproduce

Go to scribe table. Use spell book on scribe table. Select harvest glyph. Place iron hoe and earth glyph on table. Wait for the harvesting glyph to be completed.

### Expected behaviour

I expected the glyph to be completed, for me to pick it up, and use the glyph so that I could use a harvesting spell on my novice spell book.

**Comment by Bluesingingsea** [comment]
I just tried to create the magelight glyph and it crashed again. so the issue seems to be ars nouveau

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
