### ISSUE TITLE
Infinity Pipe Upgrade Recipe

### ISSUE THREAD

**Issue by Atschinger12** [FTBTeam/FTB-Modpack-Issues#3887]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

I`m in the Process of Building a max Size fission reactor from Mekanism and realized that all pipes are relatively slow in transfering liquid so you would have to use multiple pipes to transfer liquids/geasses.
The mod "Pipez" has an infinity pipe upgrade to allow nearly limitless transferring/extracting of liquids,gasses,items etc...
I would like to have a  Late-Game crafting recipe for these - like using 4 Neutronium Ingots from Avaritia, 4 Redstone blocks and an Ultimate pipe upgarde. This fits the crafting pattern of the previous Upgrades and it would be a good price for how Overpowered this Item is.

**Comment by UnRealDinnerbone** [comment]
As there are no other "creative" items in Stoneblock 3 I do not fell like this fits with the pre-existing recipes / end game items in the game
