### ISSUE TITLE
vinery recipes for aging barrel not showing up on JEI

### ISSUE THREAD

**Issue by Derppotatoe5** [FTBTeam/FTB-Modpack-Issues#3888]
### Modpack

FTB Presents AbePack

### Modpack version

1.0.4

### Describe the bug

JEI does not show the recipes for the aging barrel, tried using R or right click and nothing pops up.

### Steps to reproduce

go in inventory
look up the wines in vinery mod 
no recipes

### Expected behaviour

there should be recipes

**Comment by Hanoverfist** [comment]
Tested this on our servers. Fresh 1.04 install of client and server. Everything is working as intended. Recipe shows needing a barrel and 2 sticks. 

Isuspect you have a bad install. Try a fresh, clean install maybe with a different launcher.

**Comment by Derppotatoe5** [comment]
> Tested this on our servers. Fresh 1.04 install of client and server. Everything is working as intended. Recipe shows needing a barrel and 2 sticks.
> 
> I suspect you have a bad install. Try a fresh, clean install.

sorry I wrote this post poorly; I was talking about the actual recipes for the wines itself. that use the aging barrel to craft them.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
