### ISSUE TITLE
Cannot claim Apotheosis Quest Reward in FTB University 1.2.0

### ISSUE THREAD

**Issue by Reaper9802** [FTBTeam/FTB-Modpack-Issues#3889]
### Modpack

Other...

### Modpack version

1.2.0

### Describe the bug

Having a problem completing the first quest in the Apotheosis quest chain, called "Affix Items". There's a green checkmark on the bottle of enchanting icon and a red exclamation point over the reward, but it won't let me claim the reward. It switches to green checkmark and then quickly back to the red exclamation mark whenever I click on it. Also when I hover the cursor over the bottle of enchanting, "Get an affix item. Click to view recipe(s)", but clicking on it bring up an error: No Valid Items

### Steps to reproduce

1. Open questbook
2. Open Apotheosis quest chapter
3. Go to first Apotheosis quest
4. Try to claim the reward

### Expected behaviour

To claim the reward

**Comment by aaronhowser1** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/15698722/cc4c8f55-6945-419e-92ac-387a5b375700)
Fixed (kinda)
