### ISSUE TITLE
Tunnels for Compact Machines Mod do not have recipes

### ISSUE THREAD

**Issue by Dr3mmy** [FTBTeam/FTB-Modpack-Issues#389]
### Modpack

FTB OceanBlock

### Modpack version

1.9.0

### Describe the bug

Everything except the Tunnels have recipes and are able to be made except for the tunnels and cannot send items out of the compact machine.

### Steps to reproduce

Click on Compact Machine Tunnels on JEI to see recipes are not available.

### Expected behaviour

add recipes for Compact Machines tunnels

**Comment by Raidobw2** [comment]
Hello, please see #363, this has been answered the other day. Thanks for the report anyways.
Basically, the mod author will add a recipe once they are fully working, currently, they don't have their full functionalities implemented which is why they are in this state.
