### ISSUE TITLE
Masterful Machines + Immersive Engineering connector = constant power drain

### ISSUE THREAD

**Issue by danilluzin** [FTBTeam/FTB-Modpack-Issues#3890]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.12.0

### Describe the bug

Multiblock **Masterful Machines** connected with **Immersive Engineering** wires and connectors are constantly draining power when machine is doing nothing.
 

**Current workaround :**
Use **Powah cable** as a single inbetween block between the connector and the machine

### Steps to reproduce

1. Connect any **Masterfull Mashine** (tested on both Alloyer and Carpenter) with **Immersive Engineering** connector (tested with LV) to a power source (used Powah cell)
2. Check the cell to see **energy drain** constantly while the machine is idling.

### Expected behaviour

Power is only used when machine is doing something

### Screenshots

![2023-09-14_22 22 31](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26139644/ae725d34-d9e7-42fb-81e5-551e8c5f3983)
![2023-09-14_22 22 59](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26139644/9542527c-b75b-42d4-8fe2-b2916a2cdbbd)

**Comment by pikminman13** [comment]
duplicate issue of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3543
