### ISSUE TITLE
World Crash on Startup - RS & Masterful Machinery

### ISSUE THREAD

**Issue by elder-sign** [FTBTeam/FTB-Modpack-Issues#3891]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.12.0

### Log Files

https://pste.ch/anofidoson.rb

### Describe the bug

World crashes on load on server-side, seems to be related to Masterful Machinery, possible cause is connecting a RS external storage to a MM fluid input block.

### Steps to reproduce

1. Connect RS ext storage to fluid input block
2. Connect RS exporter to separate fluid block
3. Re-log
4. Experience crash

### Expected behaviour

World loads normally

**Comment by pikminman13** [comment]
external storages are a bad idea for fluid ports on most inventories. you have to be really careful. they don't like mekanism tanks or immersive engineering tanks either.

**Comment by elder-sign** [comment]
I found out the hard way with the IE tanks already, was hoping the MM ports worked better, at least the IE interaction doesn't render your world inoperable. RS in 1.16 was a crapshoot, and fluid external storages seem to be constant snake eyes

**Comment by elder-sign** [comment]
World Download Link:
https://drive.google.com/file/d/1fn-F94ODjdSRlTqFyK3T03wpJjBmgmPr/view?usp=drive_link

**Comment by pikminman13** [comment]
specifically which port was it? im trying to replicate the crash but its not corrupting the world or anything on my test world

also you need to give me access to the file

**Comment by pikminman13** [comment]
ok, in the event im not around when you get back to me, make a copy of your world and remove MM and see what happens. if the world can be reloaded, at worst all you should have to do then is reload the world with the mod after and replace anything that was lost. im going to try to make a script that prevents placing external storages against mm fluid ports.

**Comment by elder-sign** [comment]
It was on a pair of Mana Death Generator fluid inputs, and the file should be accessible now, my bad, I thought I turned permissions on

**Comment by elder-sign** [comment]
Removing MM solved the issue, time to rebuild the machines now

**Comment by pikminman13** [comment]
ok, next update will have a script preventing placement like that as to avoid future crashes
