### ISSUE TITLE
The game is constantly crashing with graphics error

### ISSUE THREAD

**Issue by BegpoCMA** [FTBTeam/FTB-Modpack-Issues#3893]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.16.5

### Log Files

(mistake №1, log №1):
[hs_err_pid11396.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12642626/hs_err_pid11396.log)
(mistake №2, log №2):
[hs_err_pid13716.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12642647/hs_err_pid13716.log)

### Describe the bug
The error occurs on any Java versions: Java 8, Java 11, Java 19, Java 20
!I'm playing the Russian version.
(mistake №1, log №1)..When you start searching for some items by JEI, the game crashes due to graphics. Reinstalling the video driver or Java does not help.
(mistake №2, log №2). When you go to the draconic evolution tab in quests, the game immediately crashes.

### Steps to reproduce

(mistake №1, log №1):
1. Opening the inventory
2. You write in the search JEI "Кирка". And the error occurs with many searches.
3. The game is crashing.

(mistake №2, log №2):
1. You open the quest book
2. Go to the "Draconic..." tab
3. The game is crashing.

### Expected behaviour

How to get rid of crashes

**Comment by pikminman13** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40

**Comment by BegpoCMA** [comment]
Thank you.I played a little, the crashes stopped
