### ISSUE TITLE
Game crash when I started to do create mod

### ISSUE THREAD

**Issue by Ulyande** [FTBTeam/FTB-Modpack-Issues#3896]
### Modpack

FTB Presents AbePack

### Modpack version

1.0.5

### Log Files

[crash-2023-09-18_22.16.23-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12648850/crash-2023-09-18_22.16.23-client.txt)

### Describe the bug

Game closed/crashed after few min of playing. Not really sure what is the main cause it but heres when it happen:

1: Multiple time inside Sop backpack
2: During changing stripped log into the create block

the crashes happened rarely before i started create but now it happen within min. Not really sure if create is the cause or Sop backpack but thats what happened. 

thankyou for your time

### Steps to reproduce

Random within min

mostly during and after openning Sop backpack GUI

### Expected behaviour

Random crashes

**Comment by UnRealDinnerbone** [comment]
Does this still happen in the lastest version?
