### ISSUE TITLE
Server crash upon login

### ISSUE THREAD

**Issue by AlexMagic01** [FTBTeam/FTB-Modpack-Issues#3897]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.22.0

### Log Files

[crash-2023-09-19_12.40.52-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12660448/crash-2023-09-19_12.40.52-server.txt)

### Describe the bug

I'm playing Stoneblock 2 with a friend on a cloud server hosted by Oracle. We have never encountered any problems even when we modified the world generation a bit. This is like almost 2 weeks in with no hiccups whatsoever. No server files have been changed since, absolutely nothing was removed or added. I logged out last night after having upgraded some magmatic dynamos. 
I proceed to log back in this morning, and the chunks just won't load. I can see the character hand but the chunks just aren't there. After a few seconds the minecraft window doesn't respond anymore. I quickly go to the server console and these error messages get prompted:

_[12:40:52] [Server Watchdog/FATAL] [minecraft/ServerHangWatchdog]: A single server tick took 60.00 seconds (should be max 0.05)
[12:40:52] [Server Watchdog/FATAL] [minecraft/ServerHangWatchdog]: Considering it to be crashed, server will forcibly shutdown.
[12:40:52] [Server Watchdog/ERROR] [minecraft/ServerHangWatchdog]: This crash report has been saved to: /home/opc/./crash-reports/crash-2023-09-19_12.40.52-server.txt_

and the minecraft window works again and gives me the server was closed screen (the crash file is the same one I attached).
I restart the server, and this time i don't even get to see the character hand, just after the "Loading terrain..." screen it's just dirt blocks with no text, the minecraft window not responding anymore and the server shutting down again.
So as a last resort I go and reboot the entire VM. I try to start it up one more time but with the same result. I just don't understand what the problem could be.

### Steps to reproduce

- Try to join the server | The rest has been explained in the bug description

### Expected behaviour

The chunks should load like normal and the server shouldn't crash

**Comment by Gaz492** [comment]
It sounds like there are hundrads if not thousands of entities or dropped items on the floor around where you are logging in.
These can be a little difficult to fix and the easiest method to fix this is to restore a world backup.

If you are quick, when you log into the server you can try running the command /kill @e[type=item] for items and /kill @e[type=!player] to kill everything thats not a player, but this would kill any entity such as cows, sheep and mobs.
