### ISSUE TITLE
Water wheel is invisibile

### ISSUE THREAD

**Issue by Bluesingingsea** [FTBTeam/FTB-Modpack-Issues#3899]
### Modpack

FTB Presents AbePack

### Modpack version

1.0.6

### Describe the bug

When placing down a water wheel, the water wheel won't be seen, despite it taking up blocks. In the screen shot, there are three next to each other.

### Steps to reproduce

Create water wheel, place it down in an adequate space, see that it's invisible.

### Expected behaviour

To see the water wheel.

### Screenshots

![Water wheel](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/144850391/579e7516-dd13-4e28-97f0-c82097d3fcc6)

**Comment by UnRealDinnerbone** [comment]
Please try turning shaders off, to see if it still happens
