### ISSUE TITLE
Moon Iron Ore missing from IE crusher recipe line

### ISSUE THREAD

**Issue by SSM121** [FTBTeam/FTB-Modpack-Issues#3900]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.11.0

### Describe the bug

The moon iron ore has a recipe for the FTB contraptions macerator and the thermal series pulverizer and should fit into the standard ore proccessing line like regular iron but the IE crusher recipe is not there.

### Steps to reproduce

Issue is seen in version 1.11.0 of the pack.

### Expected behaviour

Expected moon iron to fit into one of the 3 ore processing chains.

### Additional information

after the crusher/macerator/pulverizer step it produces the same output as regular iron ore so only this one part of the chain is broken.

**Comment by pikminman13** [comment]
fixed in dev
