### ISSUE TITLE
Minecraft ores not spawning in world

### ISSUE THREAD

**Issue by atomroflman** [FTBTeam/FTB-Modpack-Issues#3902]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.2.1

### Describe the bug

There are close to no minecraft ores to be found in the world.

Found 8 Iron while mining for 3 hours already.
Mined at different levels from 2 to 60. Even found a lava pit without any MC ores.

Applies to Redstone, Diamonds and Gold as well. 

Anyways there were dozens of ores from diffent mods, like Mekanism.

### Steps to reproduce

1. Start a new game
2. Mine for a while
3. Give up...

### Expected behaviour

Iron should be findable close to everywhere and redstone and gold at the low levels.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10799353/3a27b206-3585-45df-9667-bc96ed0230b4)

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
