### ISSUE TITLE
Crash FTB Skies

### ISSUE THREAD

**Issue by LojzanGT** [FTBTeam/FTB-Modpack-Issues#3903]
### Modpack

FTB Presents AbePack

### Modpack version

1.3.1

### Log Files

https://pste.ch/olehoyoyiw.makefile

### Describe the bug

Hi, the modpack loads for a while and then an error pops up.
The game won't even start

### Steps to reproduce

see error log

### Expected behaviour

Modpack by se měla načíst

**Comment by DelusionalWizard** [comment]
Delete instance then reinstall the first time will most likely client crash the second time it will run and trying too increase the ram once you've loaded it once

**Comment by LojzanGT** [comment]
Hi, The problem is still the same. I have also tried reinstalling FTB launcher. It still doesn't work

**Comment by Gaz492** [comment]
Is this still an issue in the latest version of the modpack?
If it is would you be able to upload a new log for us as the one in your original post no longer exists
