### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by TH3GOD88** [FTBTeam/FTB-Modpack-Issues#3904]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.13.1

### Describe the bug

A lot of textures are not showing. 

### Steps to reproduce

Run the server
Join the server
Look at recipes 

### Expected behaviour

To see what I am making

### Screenshots

![Screenshot 2023-09-22 172515](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2775629/00185d0e-4f39-4df5-9e78-86796abd099a)

**Comment by pikminman13** [comment]
f3+t

**Comment by TH3GOD88** [comment]
You're quick to close stuff that hasn't been resolved.
This is after it reloaded assets. Seems to not have worked. 
![Screenshot 2023-09-22 183020](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2775629/4730b7ed-0519-49f7-973e-6e5de3c4356e)

**Comment by TH3GOD88** [comment]
This is only happening with Ibpdx mod.

**Comment by pikminman13** [comment]
there is nothing i can do to fix it. sometimes the textures break.

**Comment by TH3GOD88** [comment]
I figured it out, I ended up having to delete and reinstall the pack. Sorry if what I wrote seemed rude. I wasn't trying to be. I know you were trying to help, and I am grateful for it.

**Comment by pikminman13** [comment]
oh believe me, i hate this issue. the reload _usually_ works, but obviously i wish it didn't happen at all. i simply have rarely encountered a time (after an entire playthrough) where one reload did not fix it on the instances it did, and it never had an issue after two reloads. i asked people about it and they couldn't figure it out either.
