### ISSUE TITLE
fix mini map

### ISSUE THREAD

**Issue by betwithbeth** [FTBTeam/FTB-Modpack-Issues#3905]
### Modpack

FTB Presents AbePack

### Modpack version

1.0.6

### Describe the bug

cant seem to see friends on mini map, how to fix please

### Steps to reproduce

idk

### Expected behaviour

see mini map

**Comment by UnRealDinnerbone** [comment]
This is not a bug, to see other players you either need to join a team with them or change the map server setting (Purple gear on the map if you are oped) to show all players to everyone
