### ISSUE TITLE
Atomic Dissassembler

### ISSUE THREAD

**Issue by awong2761** [FTBTeam/FTB-Modpack-Issues#3906]
### Modpack

FTB Presents AbePack

### Modpack version

1.0.6

### Describe the bug

Can't create the atomic disassembler, the refined obsidian ingot requires the one from mekanism and won't allow me to create the mekanism version, only the emendatus version.  This isn't allowed in the crafting recipe of the atomic disassembler.

### Steps to reproduce

Try to craft refined obsidian ingot in osmium compressor > get emendatus refined obsidian ingot.  
Try to craft atomic disassembler > doesn't work because you don't have the mekanism version of refined obsidian ingot.

### Expected behaviour

Able to craft AD

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/65233651/9cf24462-8d7e-419d-95e2-becc39028314)

**Comment by awong2761** [comment]
Mekanism ingot doesn't have a dictionary either, so oredictionificator doesn't work

**Comment by DinnerBeef** [comment]
Will be fixed in the next update. Recipe was changed back to normal now that you need to kill the leviathan first.
