### ISSUE TITLE
No quartz seeds for AE2

### ISSUE THREAD

**Issue by mtashchuk** [FTBTeam/FTB-Modpack-Issues#3907]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.12.0

### Describe the bug

I have no recipe for them in jei, nor can i craft any seeds from AE2

### Steps to reproduce

1 go to jei
2 no recipe
3 try to craft
4 nothing
5 sad(

### Expected behaviour

Less ways to multiply quarz

**Comment by Saereth** [comment]
this is normal, the process was changed in 1.19.2 to use budding certus now
