### ISSUE TITLE
FTB Skies Crashed

### ISSUE THREAD

**Issue by selfobsession** [FTBTeam/FTB-Modpack-Issues#3908]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Log Files

https://drive.google.com/file/d/1VbTQ39hEfoKFf2CVbhIDRretCMeppFgd/view?usp=drive_link

### Describe the bug

I made an attempt to startup the game and the message popped up  "Looks like the instance has crashed during startup or whilst running..."

### Steps to reproduce

1: Download FTB Skies 1.3.1
2: Launch the Game 
3: Wait for the instance to crash

### Expected behaviour

I expected the game to load as normal. Instead the game never loaded at all.

### Screenshots

I currently run windows 11.

### Additional information

I play the game with 10.06gb of ram

**Comment by DelusionalWizard** [comment]
Delete instance and reinstall

**Comment by DelusionalWizard** [comment]
Delete  instance and reinstall run it atleast twice since the first time will client crash

**Comment by selfobsession** [comment]
I deleted the instance and ran it twice both times crashed before I increased the ram from the default 6gb to 10.06gb and still crashed.  No luck of the game evening opening.

**Comment by Saereth** [comment]
need a log file here.
