### ISSUE TITLE
i can't craft a cardboard box

### ISSUE THREAD

**Issue by PvpBud** [FTBTeam/FTB-Modpack-Issues#3909]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.0

### Log Files

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/145945870/95ed44e4-9da6-48a2-80ee-af694d79b9c2)

### Describe the bug

i can't make a cardboard box with sawdust and i'm not so sure about the recipe 

### Steps to reproduce

I'm not really sure if i'm doing anything wrong 
1. get sawdust
2. craft cardboard box
3. i can't craft it

### Expected behaviour

to get a cardboard box from using sawdust 

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/145945870/06232efb-f166-410e-8cee-4085d822b7c0)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/145945870/ba98274e-8bc9-44c4-b403-a95c7b349352)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/145945870/163d4db8-8e88-42c1-ba4a-dd3d4f955fad)

### Additional information

I would like to know how to make them 
and whats wrong

**Comment by PvpBud** [comment]
I'm playing on a server by the way

**Comment by UnRealDinnerbone** [comment]
Does this still happen? I can't seem to repurpose the issue
