### ISSUE TITLE
Cannot complete Clay  Kiln quest

### ISSUE THREAD

**Issue by benloz10** [FTBTeam/FTB-Modpack-Issues#3910]
### Modpack

FTB Interactions

### Modpack version

1.9.1

### Log Files

N/A

### Describe the bug

The Clay Kiln quest on the void world quest line cannot be completed. Crafting Whittled Fire Sticks does not complete the quest. I presume it's because the quest requires a stack of 2, while the items are non-stackable.

### Steps to reproduce

1. Open the quest book
2. Complete quests leading up to the "Clay Kiln" quest
3. Craft more than two "Whittled Fire Sticks"
4. That portion of the quest will not be completed.

### Expected behaviour

Crafting 2 fire sticks should complete the associated section for the quest

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/16801611/be7105ab-dbe1-428f-b9cb-faad8bbebd47)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/16801611/948f1f18-5da9-450e-b0fc-4d5e21bc0914)

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

We may have something up our sleeves, some may call it a remaster, keep an eye out on our social media platforms for more information.
