### ISSUE TITLE
MineColonies Bug in All The Mods 9 Scanning tool

### ISSUE THREAD

**Issue by ArmedBOB** [FTBTeam/FTB-Modpack-Issues#3914]
### Modpack

Other...

### Modpack version

9-0.1.3

### Log Files

[crash-2023-09-27_15.10.29-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12742480/crash-2023-09-27_15.10.29-client.txt)

### Describe the bug

I am scanning a building with the scanning tool to make a new blueprint for Minecolonies. I am able to make the blueprint but when I am trying to place it the game freezes up and then crashes.

If I select the " Show resources" when I am making the blueprint it will also freeze.

The building is made up of the shingles from domum_ornamentum, Vanilla blocks such as Bricks, Polished Granite, Stone Brick and Oak wood.
It has various machines, belts, steam tank redstone transmitters in the build. 

I have stopped all the machines and removed all the belts from Create to try to troubleshoot.

Other than removing each block type one by one, I am unsure how else to troubleshoot this.

### Steps to reproduce

1. Scan building with Scanning tool for Minecolonies
2. Attempt to review recourses for that blueprint or place the blueprint in my colony.

### Expected behaviour

I expected the building to be placed for construction within my colony for Minecolony

**Comment by SolarBAM404** [comment]
You properly want to report that to either Minecolonies developers themselves or report it to [All The Mods](https://github.com/AllTheMods/ATM-9/issues) on their issue board since its for them. Since its not actually an FTB pack :)

**Comment by DinnerBeef** [comment]
This is not and FTB Pack.
