### ISSUE TITLE
Connection Lost: Internal Exception with Ars Noveau

### ISSUE THREAD

**Issue by Panczinello** [FTBTeam/FTB-Modpack-Issues#3915]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Log Files

Connection Lost

Internal Exception: io.netty.handler.codec.DecoderException: unknown serializer type 91

### Describe the bug

The problem is involving Ars Noveau:
Whenever an item goes in the imbuement chamber, be it Lapis or Amethyst, this error appears.
The problem only comes when source is used in the crafting process.
It also does not matter if I put it in there, another plyayer, or even a hopper.
Other player I tested it with, did not get the exception.

### Steps to reproduce

1. setup source network
2. place down full source jar and imbuement chamber
3. put lapis lazuli or amethyst in the chamber

### Expected behaviour

faster source gem crafting process/ almost instant usually

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
