### ISSUE TITLE
Bamboo Recipe Conflict

### ISSUE THREAD

**Issue by Vincalota** [FTBTeam/FTB-Modpack-Issues#3916]
### Modpack

FTB Endeavour

### Modpack version

1.9.0

### Describe the bug

Items from "Bamboo Everything" aren't craftable because of a recipe conflict with Thermal Series.

### Steps to reproduce

1. Try to craft "bamboo bundle" by putting 1 bamboo in every crafting grid slot
2. "Block of bamboo" from thermal series is crafted

### Expected behaviour

I expected to receive a bamboo bundle, or to see an option to cycle through recipes in the crafting grid

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/146437365/5c8c3c8c-472c-4d43-b455-c15c53bd2eae)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/146437365/8447ba90-f4c4-4874-8066-39e4603ef44f)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/146437365/e94bcbed-2620-4eb7-9e3e-b06bd908429e)

### Additional information

There's also a bamboo bundle from Quark with the same recipe.

**Comment by manmaed** [comment]
This issue is stale
