### ISSUE TITLE
amethyst recipe

### ISSUE THREAD

**Issue by Jebustino** [FTBTeam/FTB-Modpack-Issues#3919]
### Modpack

FTB Presents AbePack

### Modpack version

1.1.1

### Describe the bug

Just wondering if you can still grow amethyst from budding amethyst in the garden cloche, I noticed the recipe for it is missing and I'm wondering if I should go through the efforts of building a garden cloche so I can easily grow amethyst or if it is intentional.

### Steps to reproduce

.

### Expected behaviour

a JEI recipe for amethyst in the garden cloche

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
