### ISSUE TITLE
Multiple bugs, issues and suggestions

### ISSUE THREAD

**Issue by Meteoblastdragon** [FTBTeam/FTB-Modpack-Issues#3920]
### Modpack

FTB Presents AbePack

### Modpack version

We used 1.0.6 but having read the patch notes I don't think these things have changed

### Log Files

https://spark.lucko.me/yMFOUlF9iC

### Describe the bug

Hey there! So far I'm loving the pack and our community is as well, however, we found some bugs/issues during our server beta test (v1.0.6). We are currently using the Apex Hosting 10GB server pack and the lag-related issues start at 10+ people and crashes at 15+ players.

- Something we're noticing is that every time there is voice chat authentication or secrets sent, that seems to happen just before a tick warning (we're having TPS issues and all our complete server crashes were due to server tick falling too far behind). We were under the impression that the voice mod was a lite mod?
- Speaking of TPS issues, Mikey on the FTB Discord said to also include our Spark report to see if there's anything we can do to run our server more smoothly. https://spark.lucko.me/yMFOUlF9iC. Currently, by advice from our server host, we're looking into https://www.curseforge.com/minecraft/mc-mods/in-control to see if we can fix some lag by controlling entities.
- As well as something different that we might have noticed that trains could possibly be very lag-inducing? If that's the case maybe some kind of limiter would be interesting.
- The electrolytic separator is available to craft but doesn't show up in JEI
- When a player that is not in a team, does /msg_team, the whole server gets kicked. The server doesn't stop but everyone gets a chat validation error message. Can we prevent this or would we have to remove the command for everyone whether or not they are in a team?

Thanks in advance for the hard work and I'm looking forward to the updates! I will also be filling out a suggestions form though I feel like some suggestions fall in between a suggestion and a bug so wasn't sure if I should post them here but will do so over there.

### Steps to reproduce

I feel like with the way I described the issues/bugs, there's not really a need for steps to reproduce. It all speaks for itself.
First three are just server load and lag issues which the spark report can probably tell you the most that you would need to know
4th you type in electrolytic separator in JEI and you won't find it...
5th have a player not be in a team and have them type in chat /msg_team. Within a minute the whole server gets kicked.

### Expected behaviour

1-3 No to less lag. 4 find the electrolytic separator in JEI. 5 Not have everyone get kicked

### Additional information

I'm new to GitHub so I hope I did everything right. If not you can contact me on Discord @bluefirefox for more info (or I'll do my best to respond here if that's possible)

**Comment by DinnerBeef** [comment]
In Control has been added to the modpack since the version of the pack. Please let me know if you are still having issues with the newest version of the modpack.

**Comment by Meteoblastdragon** [comment]
We're no longer running this server so we can't really test if there are any more issues.

**Comment by DinnerBeef** [comment]
That's fine. If someone else experiences this issue, they can open a new one up.
