### ISSUE TITLE
Some current configuration suggestions and multiple add-on mods suggestions

### ISSUE THREAD

**Issue by Meteoblastdragon** [FTBTeam/FTB-Modpack-Issues#3921]
### Modpack

FTB Presents AbePack

### Is your suggestion related to a problem? Please describe.

Hey, it's me again. Here I have 2 suggestions that might be interesting to consider or take a look at:
- Since v1.0.5 you added GameStages and RecipeStages and put some things behind bosses which I absolutely love, but I believe right now it's so that the boss needs to be killed by the server to be unlocked? Would it be interesting and possible to have it locked per FTB team?
- The Akashic Tome is a great feature that new players spawn with so they have some sense of direction as to what mods they can try to explore. However, there are some books/guides that are not yet included in the tome which might be nice to have. Like Mahou Tsukai Knowledge Compendium and "Guide" from AE2. Sadly I don't remember all the exact ones as of right now but I could look those up.

### Mod suggestion

Here are some mod suggestions I would like to suggest. All these mods are add-ons to already current mods you have in the pack.

The biggest thing I would like to see is Mekanism Chemicals integration with AE2 which can be done with this mod: https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics

Because I was looking if it was possible to store chemicals in AE2, I found some other addons for AE2 as well and since there's integration with Ars I was checking for Ars addons so I fell into a rabbit hole haha. These are all mods I just found that could potentially be fun to add, but everything's up to you of course if you like these things and if that's the way you want to take this modpack.

https://www.curseforge.com/minecraft/mc-mods/ars-energistique (AE2 + Ars Nouveau)
https://www.curseforge.com/minecraft/mc-mods/applied-cooking (AE2 + Cooking for Blockheads)
https://www.curseforge.com/minecraft/mc-mods/applied-botanics-addon (AE2 + Botania)
https://www.curseforge.com/minecraft/mc-mods/aeinfinitybooster (AE2 wireless terminal add-on)
https://www.curseforge.com/minecraft/mc-mods/ae2-qol-recipes (AE2 QoL changes)
https://www.curseforge.com/minecraft/mc-mods/ars-ocultas (Ars Nouveau + Occultism)
https://www.curseforge.com/minecraft/mc-mods/ars-armiger (Ars Nouveau + Tetra)
https://www.curseforge.com/minecraft/mc-mods/ars-elemental (Ars Nouveau extras)
https://www.curseforge.com/minecraft/mc-mods/too-many-glyphs (Ars Nouveau extras)
https://www.curseforge.com/minecraft/mc-mods/ars-instrumentum (Ars Nouveau utility)
https://www.curseforge.com/minecraft/mc-mods/ars-omega (Ars Nouveau extras) 
https://www.curseforge.com/minecraft/mc-mods/ars-industria (Ars Nouveau + Immersive Engineering + Botania) 
https://www.curseforge.com/minecraft/mc-mods/starbunclemania (Ars Nouveau extras) 
https://www.curseforge.com/minecraft/mc-mods/tetraonic-mahounic (currently not yet for 1.19.2, but perhaps interesting for the future)
https://www.curseforge.com/minecraft/mc-mods/tetranomicon (Tetra + Create + Quark + Twilight Forest. Note: it says that BYG might sometimes cause issues so I'm not sure if this will work)
https://www.curseforge.com/minecraft/mc-mods/tetras-delight (Tetra + Farmer's Delight + Nether's Delight)
https://www.curseforge.com/minecraft/mc-mods/tetra-booster-pack (Tetra extras)

I feel like none of these mods are a necessity to add, however, I do think with so many cross-compatible mods, it will entice players to discover and work with more mods and most would overall be a good addition to the pack.

Thanks a lot for all the hard work and effort you guys have done in this pack! As I said in the bug report, we're having a blast with our community and we have run a beta test with v1.0.6 and are planning to open the server to our whole community on the latest version (whichever that may be at that time) this Tuesday :)

**Comment by 3vilN355** [comment]
I'd like to chime in and say I agree almost all of the above suggested mods feel like a great addition (especially applied mekanistics), though I would like to point out that the AE infinity booster would be unnecessary as we have the terminals from AE2WTLib, which provide infinite range and cross dimensional support with its card and terminals.
I would like to add that there's another great addition for AE2 which makes it much more approachable for most people. In my experience people tend towards RS when there are drawers in the pack, because of the type restriction for AE. 
https://www.curseforge.com/minecraft/mc-mods/ae2-things-forge
The AE2 Things mod offers not only RS-like drives for AE2 but also features the Advanced Inscriber, which is not only faster but also much more user friendly in 1.19 than the AE2 Inscribers.

**Comment by Meteoblastdragon** [comment]
> I'd like to chime in and say I agree almost all of the above suggested mods feel like a great addition (especially applied mekanistics), though I would like to point out that the AE infinity booster would be unnecessary as we have the terminals from AE2WTLib, which provide infinite range and cross dimensional support with its card and terminals.

I did not realize that that was how that worked. That makes so much sense now with the quantum card. Does only work for one person per quantum ring though, but def makes it possible

**Comment by DinnerBeef** [comment]
Thank you for your suggestion, but at this time will not be adding these mods to the Mod Pack.
