### ISSUE TITLE
Electrolyric Separator has no recipe

### ISSUE THREAD

**Issue by notZestly** [FTBTeam/FTB-Modpack-Issues#3922]
### Modpack

FTB Presents AbePack

### Modpack version

1.1.1

### Describe the bug

electrolytic separator from mekanism isnt in the jei recipe list, along with what it can make for example chlorine which can be made inside it has no recipe 

### Steps to reproduce

1. Search Electrolyric Separator in JEI
2. Nothing shows up

### Expected behaviour

it is suppose to show in jei

### Screenshots

![Screenshot 2023-09-30 102448](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/86637149/db23cfb7-6549-4c82-a721-2e4c48aad55b)

**Comment by Fma965** [comment]
Definitely a bug but you can work around it, click the core, then press U on the core in the crafting view then it shows the recipe :)

**Comment by UnRealDinnerbone** [comment]
Fixed in 1.20
