### ISSUE TITLE
Optifine Crashes instance

### ISSUE THREAD

**Issue by Sufficingwing** [FTBTeam/FTB-Modpack-Issues#3923]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Describe the bug

Simply cannot add optifine or any mod for that sake, without the instance either not launching or crashing upon launch. and there's no way to add Optifine through the launcher which may be the problem

### Steps to reproduce

1. Download modpack
2. Add correct optifine version
3. launch and wait for crash

### Expected behaviour

I'd just like to launch game w optifine

**Comment by UnRealDinnerbone** [comment]
Optifine is not supported

**Comment by enzofrnt** [comment]
> Optifine is not supported

Maybe you can add support for it ?
