### ISSUE TITLE
Botania Assets Invisible

### ISSUE THREAD

**Issue by MercifulCrouton** [FTBTeam/FTB-Modpack-Issues#3924]
### Modpack

FTB Presents AbePack

### Modpack version

1.1.1

### Describe the bug

A few of the the Botania items have invisible parts. All of the pylons for example. I can see the outside bit of it but the inner crystal part is invisible. Most Notably the Gaia Guardian is also invisible and I don't believe it's supposed to be. It's nothing game breaking especially when it was just the pylons but the Gaia Guardian was needlessly difficult due to me not being able to see it. 

After going into creative and double checking if stuff was invisible I also realized that mana pools do not visibly display how much mana is in them. You have to use the wand to see how much is in it. Otherwise it appears empty. 

### Steps to reproduce

1. Place a Mana Pylon, a Natura Pylon, a Gaia Pylon, a Gaia Guardian head, and a full mana pool

### Expected behaviour

The inside crystals of the pylons will be invisble. The Guardian head will be entirely invisible and the mana pool will appear empty.

### Screenshots

![2023-09-30_10 19 21](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/146568573/661139eb-0ed8-45bc-94d9-a5caa7263fd8)

**Comment by UnRealDinnerbone** [comment]
Please try turning shaders off, to see if it still happens

**Comment by MercifulCrouton** [comment]
Yes, turning off shaders makes the inner pylons and such visible again.

**Comment by DinnerBeef** [comment]
Sadly, due to the nature of how mods work with shaders, we will be unable to have this issue fixed. You will just have to turn off the shaders if you need to see the pylons while playing with Botina.
