### ISSUE TITLE
blocks placing wrong way

### ISSUE THREAD

**Issue by ironaddie** [FTBTeam/FTB-Modpack-Issues#3925]
### Modpack

FTB Presents AbePack

### Modpack version

1.0.1, 1.0.6

### Describe the bug

certain blocks that can be placed in different ways (e.g. stairs used as roof, slabs, logs, etc) will automatically place in a fixed direction and will not flip like in vanilla Minecraft. 

### Steps to reproduce

unsure ?

### Expected behaviour

i expect the blocks to place depending on where your crosshair is?

**Comment by UnRealDinnerbone** [comment]
Looks like some mod is changing to where you click on the block instead you're facing
