### ISSUE TITLE
Tier 1 Spell Glyph - Leap - Ars Neaveau

### ISSUE THREAD

**Issue by Necronomis** [FTBTeam/FTB-Modpack-Issues#3927]
### Modpack

FTB Presents AbePack

### Modpack version

1.1.1

### Describe the bug

The Leap glyph is listed in the book as a tier 1 glyph, but upon learning, can only be used in a tier 3 book and the tooltip indicates it's a tier 3 glyph. Bug report submitted to Ars Neaveau team, response below:
"This is a limitation of patchouli, as items cannot be moved categories at will. Your pack adjusted it to tier 3, but it unfortunately cannot be moved without a pack modifying the pages manually."

### Steps to reproduce

Craft Leap glyph
Learn glyph
Attempt to create a spell using the glyph

### Expected behaviour

Glyph should be of the level the book indicates.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
