### ISSUE TITLE
Not downloading files

### ISSUE THREAD

**Issue by Jpotpotski** [FTBTeam/FTB-Modpack-Issues#3929]
### Modpack

FTB Presents AbePack

### Modpack version

1.1.1

### Describe the bug

I installed the modpack through FTB launcher but when the instance doing its thing, there is an issue opening it. And it shows that I the files downloaded were incomplete.

### Steps to reproduce

A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffabfa76280, pid=9668, tid=13348
JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
No core dump will be written. Minidumps are not enabled by default on client versions of Windows

### Expected behaviour

Expect to download everything and works

**Comment by roflburger2010** [comment]
I too had this problem! I posted an issue under the FTB-App [page](https://github.com/FTBTeam/FTB-App/issues/982).

Everything validates fine, the mods start to load and then the EXCEPTION_ACCESS_VIOLATION occurs.
Initial Install: [hs_err_pid21896.log](https://github.com/FTBTeam/FTB-App/files/13032847/hs_err_pid21896.log)
Second run: [hs_err_pid11704.log](https://github.com/FTBTeam/FTB-App/files/13032855/hs_err_pid11704.log)

**Comment by Gaz492** [comment]
Could you confrim that you are still having this issue on the latest version of the modpack?
I have not been able to reproduce this issue unfortunately.
