### ISSUE TITLE
[Bug]: Refined Storage Disk quest rewards are broken

### ISSUE THREAD

**Issue by quietust** [FTBTeam/FTB-Modpack-Issues#393]
### Modpack

FTB OceanBlock

### Modpack version

1.9.0

### Describe the bug

Two of the rewards you can potentially collect from completing quests are the 64k Storage Disk and the 4096k Fluid Storage Disk, both from Refined Storage.

However, all of these disks have the same predefined UUID on them (`4a2009aa-dd27-4603-8ec6-51d8f63a6885` and `111aac0e-377c-4b74-a52a-044b6de72fa1`, respectively) which prevents them from actually being usable - if you place them in a Disk Drive the slots on the block will still appear blank, and if you try to shift+right-click them to take them apart it won't let you.

There are two possible solutions to this:
1. Create the items *without* a UUID so that Refined Storage can automatically generate a new UUID for them. This will _probably_ work (because when you craft them yourself, they don't seem to gain a UUID until you drop them in your inventory), but in case it doesn't:
2. Change the quest rewards to give you the storage part and an empty housing so you can combine them yourself.

### Steps to reproduce

1. Collect quest rewards from category "leg-a" (5D24D61536E3A0FB.snbt) until you get one of the two storage disks
2. Try to insert the disk into a Disk Drive and observe that it doesn't actually work
3. Try to shift+right-click it to disassemble it and observe that you can't

### Expected behaviour

Quest rewards should actually be usable.

**Comment by weszhuang** [comment]
It appears the storage blocks from the quest rewards do not cause the same issue when you pop the disks out of them if the bug is hard to sort out this can work as a bandaid to the rewards.

**Comment by Sunekaer** [comment]
Changing to give Part instead of Disk, as i dont see a way to fix the uuid part
