### ISSUE TITLE
Forged Hammer

### ISSUE THREAD

**Issue by Aemehaf12** [FTBTeam/FTB-Modpack-Issues#3931]
### Modpack

FTB Presents AbePack

### Modpack version

1.2.0

### Describe the bug

I am having issues with the forged hammer and the hololens. I can't seem to get the higher tier hammers, (tier 5 and 6). I also can't craft the toolbelt. Any suggestions are welcome.  

### Steps to reproduce

N/A

### Expected behaviour

to craft tier 5 and 6 hammers

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?

**Comment by Aemehaf12** [comment]
Apologies for not responding. I am unable to see if the update has fixed
the issue. My family has gone through a house fire since I reported it. So
unfortunately at this time I can not provide any further information.
