### ISSUE TITLE
Growthcraft book won't load

### ISSUE THREAD

**Issue by petros1815** [FTBTeam/FTB-Modpack-Issues#3935]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.0

### Describe the bug

When opening the Growthcraft book, it won't load.

### Steps to reproduce

Open Growthcraft book.

### Expected behaviour

Show the contents of the book.

### Screenshots

![growthcraftbookbug](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/76600439/ed959eb2-3aa0-488e-8149-10e330888702)

**Comment by DinnerBeef** [comment]
Mod Bug: https://github.com/GrowthcraftCE/Growthcraft-1.20/issues/36

**Comment by DinnerBeef** [comment]
This issue has now been fixed! Please reopen this issue if you are still having problems.
