### ISSUE TITLE
Mining glowstone with Just Hammers tools doesnt drop dust

### ISSUE THREAD

**Issue by NobleBarrel1** [FTBTeam/FTB-Modpack-Issues#3936]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.0

### Describe the bug

when mining glowstone blocks with Just Hammers hammers (any tier) no glowstone dust will drop

### Steps to reproduce

mine a glowstone block with any tier of  Just Hammers hammer. 

### Expected behaviour

Glowstone dust should drop

**Comment by FishOutOfH20** [comment]
The Just Hammers mod is indeed very broken and has been reported previously on its own issues page.

It voids all blocks not normally mined with a pickaxe.  Sand, gravel and dirt all get voided.

**Comment by DinnerBeef** [comment]
Thanks for reporting and issue, However this is working as indeed and will not be fixed.
