### ISSUE TITLE
Minecraft comparator has no recipe 

### ISSUE THREAD

**Issue by NobleBarrel1** [FTBTeam/FTB-Modpack-Issues#3937]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.0

### Describe the bug

Cannot craft the minecraft comparator

### Steps to reproduce

try and craft a comparator
try and view the recipe for a comparator

### Expected behaviour

be able to craft comparator

**Comment by redgoblin88** [comment]
the same for the daylight sensor

in the script "recipe-removals" like 163 and 165
