### ISSUE TITLE
Add Applied Mekanistics mod

### ISSUE THREAD

**Issue by fred21O4** [FTBTeam/FTB-Modpack-Issues#3938]
### Modpack

FTB Presents Direwolf20 1.20

### Mod suggestion

[Applied Mekanistics](https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics) 
The official Mekanism support add-on for AE2 since this pack has Mekanism and AE2 already I feel that having support for storing and using Mekanism gas/chemicals with AE2 is a no brainer.

**Comment by DinnerBeef** [comment]
Added is version 1.0.1
