### ISSUE TITLE
Aetherslate Cave

### ISSUE THREAD

**Issue by MTigerFang** [FTBTeam/FTB-Modpack-Issues#3939]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.0

### Describe the bug

there is a biome named "Aetherslate Cave" everywhere is diamond at that biome idk why but i think that is not to be like that maybe you want to look at that

### Steps to reproduce

1. go to mining
2. find a Aetherslate Cave biome
3. mine 3 stacks or more diamond in a session

### Expected behaviour

i did not think find that much diamond in a session

**Comment by danebra** [comment]
Experienced this as well. It's kinda insane...I had fortune 3 too. I got 488 diamonds in less than 40 minutes of exploring the cave. And at higher levels (y=0) there is coal everywhere. 

Aethersteel is the mod adding the biome. Possibly not implementing the reduced air exposure of the diamond generation? Or this is intended of a rare(?) biome. 

@Ross2750 is this a bug or an intended feature?

Here are so pictures for reference. These are at y=-19
![2023-10-05_02 22 00](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147029326/546fcb81-04a3-44ba-85bd-fc4755b2f4a9)
![2023-10-05_02 22 48](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147029326/77be7fb7-6fda-4ac9-93b1-8223e29fcd92)

**Comment by Ross2750** [comment]
I'm just using a modding software called MCreator, and MCreator does not have that feature to add caves so I made it a cave biome instead.

**Comment by Ross2750** [comment]
Hello! I'm the developer of Aethersteel, and I will tell you that the Diamond and Coal generates frequently is not a bug and that was a feature
