### ISSUE TITLE
Crash on key search in control settings

### ISSUE THREAD

**Issue by lucasmccauslin** [FTBTeam/FTB-Modpack-Issues#3940]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0

### Log Files

https://pastebin.com/BJkEW71P

### Describe the bug

In trying to figure out what the whistling when pressing ` (grave) was I searched for it in the controls settings.  I accidentally pressed the ` key multiple times and it crashed.

### Steps to reproduce

1. Go to the Controls menu
2.  select key or type key:
3. search for ```(three graves)
4. crash

### Expected behaviour

not crashing

**Comment by DinnerBeef** [comment]
Mod Bug: https://github.com/jaredlll08/searchables/issues/3
