### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by cardmarius** [FTBTeam/FTB-Modpack-Issues#3941]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.0

### Log Files

Please work better on optimizing the pack, there are packs that have more modes than this one and work better. I have an I5 processor with 16GB DDR4 ram and an ATI video card with 4g ram 256bit and this pack runs at 2FPS while others that have the same number of modes even more run without problems and this is not the first pack from FTB that I have encountered this problem.

### Describe the bug

Low FPS

### Steps to reproduce

Play on normal PC

### Expected behaviour

Do the same thing "All the mods" do and other modpacks that work do

**Comment by Xymorm** [comment]
adding mods like optifine or sodium could help

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
Please note, adding additional mods, especially performance makes getting supported very limited.
