### ISSUE TITLE
Diamond generation & hammer 

### ISSUE THREAD

**Issue by Aba-sama** [FTBTeam/FTB-Modpack-Issues#3942]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.0

### Describe the bug

IDK if it's intended, but mining i found aethersteel biome. And it propably has to high diamond generation setting (more then 64 in less then 5 min? everything on cave walls)
And then i found st that IS 100% bug - I doubt that stone hammer should mine diamonds. OFC it works on aether debris too, but im not sure its mining lvl 

### Steps to reproduce

Go find aethersteel cave
Mine using hammer
Dont break D ore, just block next to it

### Expected behaviour

destroy ore/prevent from mining

**Comment by danebra** [comment]
duplicate of #3939
