### ISSUE TITLE
no accurate recipe for coal dust

### ISSUE THREAD

**Issue by MrGeorge547** [FTBTeam/FTB-Modpack-Issues#3943]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Describe the bug

Without a crusher and trying to get energy early game it's impossible as dark steel ingot from enderio  is required to make a Stirling generator. when using flint and cobbled deepslate you end up with grains of infinity 

### Steps to reproduce

1. search coal dust in jei 
2. press r on coal dust 
3.  3rd icon {mod: just enough items} 

### Expected behaviour

a recipe for coal dust

### Screenshots

https://gyazo.com/77ff6b5f43bb341c93e827feef2cc2d7

**Comment by DinnerBeef** [comment]
Sorry about that, looks like I put the wrong message there. It should read this instead. "Hold some flint in your offhand and 3 or more coal in your main hand, then shift right-click a block of obsidian, crying obsidian or a grindstone to produce early powdered coal."

**Comment by TronWoWGamer** [comment]
So, there's still no way to get powdered coal? because I'm still getting grains of infinity.

**Comment by DinnerBeef** [comment]
Did you do what I said in the message above, because that's working for me?
