### ISSUE TITLE
Redstone comparator is uncraftable and missing a recipe in JEI.

### ISSUE THREAD

**Issue by sauerkrau5** [FTBTeam/FTB-Modpack-Issues#3945]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.0

### Describe the bug

The basic vanilla redstone comparator is uncraftable and does not have a recipe in JEI.

### Steps to reproduce

Open JEI.
Search for redstone comparator.
Click on it.
Notice no recipe shows up.
Try to craft it manually with the recipe you memorised.
Notice that it doesn't craft.

### Expected behaviour

I expected the item to be craftable.

**Comment by DinnerBeef** [comment]
Fixed is version 1.0.1. Please update
