### ISSUE TITLE
Random Freezes

### ISSUE THREAD

**Issue by SpawnInsane** [FTBTeam/FTB-Modpack-Issues#3947]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1 and 1.0.0

### Log Files

[2023-10-04-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812384/2023-10-04-2.log.gz)
[2023-10-04-3.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812385/2023-10-04-3.log.gz)
[2023-10-04-4.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812386/2023-10-04-4.log.gz)
[2023-10-04-5.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812387/2023-10-04-5.log.gz)
[2023-10-04-6.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812388/2023-10-04-6.log.gz)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812389/console.log)
[crafttweaker.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812390/crafttweaker.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812391/debug.log)
[debug-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812392/debug-1.log.gz)
[debug-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812393/debug-2.log.gz)
[debug-3.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812394/debug-3.log.gz)
[debug-4.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812395/debug-4.log.gz)
[debug-5.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812396/debug-5.log.gz)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12812397/latest.log)

### Describe the bug

Game will randomly freeze while playing, happened with initial release and with 1.0.1 patch. 

### Steps to reproduce

1. Open game and start playing.
2. Game will randomly freeze.
3. Requires using "end task" in task manager in order to restart.

### Expected behaviour

Game does not freeze

**Comment by SpawnInsane** [comment]
Re-installed the mod pack and so far no crashes, will keep updating.

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
