### ISSUE TITLE
No villager models in JEI

### ISSUE THREAD

**Issue by Maximus3670** [FTBTeam/FTB-Modpack-Issues#3948]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.01

### Describe the bug

No villager render in JEI

### Steps to reproduce

Open JEI
Search any tradeable item
Open the JEI Resources section

### Expected behaviour

A model of the villager profession

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/93289843/a5fc1196-5527-4dcb-80e7-2e636c53266d)

**Comment by DinnerBeef** [comment]
The issue has been reported to the mod dev. The mod will be updated if the issue is resolved.
