### ISSUE TITLE
remove Swing Through Grass

### ISSUE THREAD

**Issue by redgoblin88** [FTBTeam/FTB-Modpack-Issues#3949]
### Modpack

FTB Presents Direwolf20 1.20

### Is your suggestion related to a problem? Please describe.

with swing through grass added, it causes several problems

lets say you are clearing a large area of grass, well if there are any livestock there (cows, sheep, chickens, pigs) you will accidently start punching them when instead you may want to gather them and keep them

if there are wolves nearby as you are punching the grass, you will accidently punch the wolf causing all of the wolves to attack you due to vanilla mechanics

if you are on horseback exploring and wanting to gather resources, for example sugarcane, you will punch your horse instead of punching the sugarcane, as you can see in the attached screenshot (which is made worse if you happen to be holding your weapon)
![2023-10-05_09 54 37](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/13396472/6796062a-92b7-47a0-8ce6-f1f10ce5c53c)

**Comment by DinnerBeef** [comment]
I am unable to reproduce this issue. I hit mobs when I want, and I destroy plants when I want.
