### ISSUE TITLE
[Bug]: Xnet/Draconic Voiding items

### ISSUE THREAD

**Issue by Elvarion** [FTBTeam/FTB-Modpack-Issues#395]
### Modpack

Oceanblock

### Modpack version

1.9.0

### Describe the bug

Xnet or Draconic Evolution Voiding Items(In this case Chaos Fragments)
Setup was working the day before. Server was restarted during downtime, possibly something happened on reboot.

Restarting the server did solv the issue without doing anything to the setup.
Thought id still report it incase there is something code wise that could be looked at to prevent this from possibly happen again.

### Steps to reproduce

Has happened once, So no real steps on how to reproduce it other then Build a setup like this and see if it occurs again.

### Expected behaviour

Crafting completing without voiding

### Screenshots

https://youtu.be/k8Y_5MdY6-g
Showing the Injectors are in Single Mode
Showing that there is no ghost items, that there is actually 5 fragments
Placing the key in the chest has no significance other then showing that there is nothing left in that slot.

**Comment by Elvarion** [comment]
Ive had this happen another two times since reporting this.
If you want a world save let me know if that can assist in any testing.

**Comment by Raidobw2** [comment]
Thanks for the report. We're running on lower personel for that modpack this week, when things get back to normal we'll check it out.
The video you provided should be more than enough for us to find the issue, thank you very much!

**Comment by Elvarion** [comment]
Sorry if my reply came across as trying to rush things, That was not my intention!
Just wanted to mention it so that my first report was not an isolated experience :)

**Comment by Raidobw2** [comment]
Don't worry, we appreciate your report. I was simply being informative since some modpack devs are/were unavailable in the past days and still are currently, and it's also the end of Uni sessions for students like me :p
Have a nice day!

**Comment by e30Birdy** [comment]
I thought i was the only one with this. Chaos shards were also voided on my setup. 2 were placed in injectors and rest were just gone.

**Comment by Sunekaer** [comment]
Could you test if this is an issue on version 1.10.1 of the pack?

**Comment by Elvarion** [comment]
Tested on 1.10.1;
Issue still persists on the Server
Loaded the server world into Singleplayer and the issue is still there.

I cant replicate this issue in Singleplayer in version 1.10.1 in a new world.
Also tried it in Singleplayer in 1.9.0, Not able to replicate it there either.

_Cursed world?_

**Comment by Sunekaer** [comment]
Hmm cursed world yes.
And you the same setup in your test world?

**Comment by Elvarion** [comment]
Same setup, however its not an exact replica.
But using Refined to send the items to a Chest
Xnet to pull the items from the chest and put into the Injectors.

Other recipes works just fine in that world. Its just that recipe with Chaos Fragments. It places 1-3 of them, the rest of the supposed 5 Fragmets gets voided.

**Comment by ThorsHammer666369** [comment]
i'v had it happen to me also found it was xnet. fixed by setting destination to 1, if left blank or 0 it would void item
