### ISSUE TITLE
Crash on Startup Due to The Aether and Flywheel

### ISSUE THREAD

**Issue by ARMAGEDDEON92** [FTBTeam/FTB-Modpack-Issues#3951]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Log Files

https://pastebin.com/CJJXfsy1

### Describe the bug

I start the modpack and it makes it to mod loading phase and then crashes listing "The Aether" And "Flywheel" as the cause

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/28818841/0736656c-a071-4651-bd10-88b3f49e21f8)

### Steps to reproduce

1.download Modpack Via FTB Launcher with overwolf
2.Start Modpack
3.Launch?

### Expected behaviour

Modpack to start

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/28818841/26353abf-2481-464c-a4a2-859277d92a64)

### Additional information

I have tried downgrading the modpack to the previous version and still get the same errors

**Comment by ARMAGEDDEON92** [comment]
Still getting the same problem no fixes have worked. tried different versions of java, tried redownloading just the mods in question nothing works





[crash-2023-10-07_10.00.16-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12837982/crash-2023-10-07_10.00.16-fml.txt)

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
