### ISSUE TITLE
Rats Ore Doubling Upgrade breaking AI

### ISSUE THREAD

**Issue by Alexwolfus** [FTBTeam/FTB-Modpack-Issues#3952]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Describe the bug

The Ore Doubling upgrade currently doesn't work correctly.
When setting the rat to "Transport Items" or "Gather Items" raw Ores and Blocks of raw Ore don't get doubled and get just straight deposited into the Chest. Ore Blocks cause the Rat to just stop working and stand there with an Ore block in there Inventory.

### Steps to reproduce

1. Get a Rat
2. Equip a Ore Doubling Upgrade
3. Rat just deposits Raw Ores and Blocks of Raw Ores, Ore Blocks break them completely

### Expected behaviour

Rat eating Raw Ores or Ore Blocks and dropping associated "nuggets"

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by TheViralDivinity** [comment]
This is definitely still happening, and definitely a problem with the new way MC handles ore.
