### ISSUE TITLE
Fix ARC quest reward 

### ISSUE THREAD

**Issue by orbidlo** [FTBTeam/FTB-Modpack-Issues#3953]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.13.1

### Describe the bug

In ARC quest, one of rewards is Crystalline Resonator which currently serves no purpose (it can convert iron/gold/ancient fragment into gravel, but the gravels have no further uses that I can see in JEI).
But the quest mentions blood shard so maybe it was meant to be Sanguine Reverter that is used to craft Blood Shard? Or maybe there were other plans for it that were cut from the release and it would be better to remove it from rewards at least.

### Steps to reproduce

1. craft ARC
2. click to get reward
3. puzzle over it endlessly and seek it's purpose

### Expected behaviour

Quest rewards with purpose

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9553279/a09dbdc4-27eb-4e8e-aa2f-e90e6ddd7986)

**Comment by pikminman13** [comment]
fixed in dev
