### ISSUE TITLE
Server Wont Start

### ISSUE THREAD

**Issue by TobiDoes** [FTBTeam/FTB-Modpack-Issues#3955]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12824880/latest.log)

### Describe the bug

The server won't start saying there are missing mods
` Mod ID: 'computercraft', Requested by: 'peripheralworks', Expected range: '[1.108.1,)', Actual version: '[MISSING]'
Mod ID: 'forge', Requested by: 'l2damagetracker', Expected range: '[47.1.0,)', Actual version: '46.0.14'
Mod ID: 'minecraft', Requested by: 'antsportation', Expected range: '[1.20.1,1.21)', Actual version: '1.20'
Mod ID: 'mekanism', Requested by: 'appmek', Expected range: '[10.4.0,11.0.0)', Actual version: '[MISSING]'
Mod ID: 'useitemonblockevent', Requested by: 'morered', Expected range: '[1.0.0.2,1.1.0.0)', Actual version: '[MISSING]'
Mod ID: 'minecraft', Requested by: 'searchables', Expected range: '[1.20.1,)', Actual version: '1.20'
Mod ID: 'patchouli', Requested by: 'ars_ocultas', Expected range: '[1.20.1-81,)', Actual version: '[MISSING]'
Mod ID: 'bookshelf', Requested by: 'runelic', Expected range: '[20,)', Actual version: '[MISSING]'
Mod ID: 'forge', Requested by: 'peripheralworks', Expected range: '[47.1.0,48)', Actual version: '46.0.14'
Mod ID: 'minecraft', Requested by: 'flib', Expected range: '[1.20.1,)', Actual version: '1.20'
Mod ID: 'refinedstorage', Requested by: 'rebornstorage', Expected range: '[1.12.0,)', Actual version: '[MISSING]'
Mod ID: 'minecraft', Requested by: 'apotheosis', Expected range: '[1.20.1,)', Actual version: '1.20'
Mod ID: 'minecraft', Requested by: 'advgenerators', Expected range: '[1.20.1,)', Actual version: '1.20'
Mod ID: 'forge', Requested by: 'morered', Expected range: '[47.1.0,)', Actual version: '46.0.14'
Mod ID: 'forge', Requested by: 'flib', Expected range: '[47.1,)', Actual version: '46.0.14'
Mod ID: 'patchouli', Requested by: 'ars_creo', Expected range: '[1.19.2-77,)', Actual version: '[MISSING]'
Mod ID: 'minecraft', Requested by: 'createchunkloading', Expected range: '[1.20.1,)', Actual version: '1.20'
Mod ID: 'minecraft', Requested by: 'chiselsandbits', Expected range: '[1.20.1,1.20.1]', Actual version: '1.20'
Mod ID: 'forge', Requested by: 'growthcraft', Expected range: '[47,)', Actual version: '46.0.14'
Mod ID: 'forge', Requested by: 'appmek', Expected range: '[47.0.0,48.0.0)', Actual version: '46.0.14'
Mod ID: 'minecraft', Requested by: 'javd', Expected range: '[1.20.1,1.20.1]', Actual version: '1.20'
Mod ID: 'create', Requested by: 'ars_creo', Expected range: '[0.5.1,)', Actual version: '[MISSING]'
Mod ID: 'citadel', Requested by: 'rats', Expected range: '[2.2,)', Actual version: '[MISSING]'
Mod ID: 'forge', Requested by: 'supplementaries', Expected range: '[47.0.19,)', Actual version: '46.0.14'
Mod ID: 'forge', Requested by: 'lemonlib', Expected range: '[47,)', Actual version: '46.0.14'
Mod ID: 'minecraft', Requested by: 'ad_astra_giselle_addon', Expected range: '[1.20.1,)', Actual version: '1.20'
Mod ID: 'jumbofurnace', Requested by: 'morered', Expected range: '[4.0.0.0,4.1.0.0)', Actual version: '[MISSING]'
Mod ID: 'minecraft', Requested by: 'ftbxmodcompat', Expected range: '[1.20.1,)', Actual version: '1.20'
Mod ID: 'forge', Requested by: 'ars_nouveau', Expected range: '[47.1.0,)', Actual version: '46.0.14'
Mod ID: 'forge', Requested by: 'farmersdelight', Expected range: '[47.1.0,)', Actual version: '46.0.14'
Mod ID: 'forge', Requested by: 'ars_ocultas', Expected range: '[47.0,)', Actual version: '46.0.14'
Mod ID: 'forge', Requested by: 'industrialforegoing', Expected range: '[47.0.19,)', Actual version: '46.0.14'
Mod ID: 'ftblibrary', Requested by: 'ftbxmodcompat', Expected range: '[2001.1.3,)', Actual version: '[MISSING]'
Mod ID: 'forge', Requested by: 'chiselsandbits', Expected range: '[47.1.3,)', Actual version: '46.0.14'
Mod ID: 'minecraft', Requested by: 'morered', Expected range: '[1.20.1,1.21)', Actual version: '1.20'
Mod ID: 'forge', Requested by: 'bdlib', Expected range: '[47.1,)', Actual version: '46.0.14'
Mod ID: 'forge', Requested by: 'createchunkloading', Expected range: '[47.1.0,)', Actual version: '46.0.14'
Mod ID: 'minecraft', Requested by: 'ae2things', Expected range: '[1.20.1,)', Actual version: '1.20'
Mod ID: 'forge', Requested by: 'advgenerators', Expected range: '[47.1,)', Actual version: '46.0.14'
Mod ID: 'minecraft', Requested by: 'trenzalore', Expected range: '[1.20.1,1.20.1]', Actual version: '1.20' `

### Steps to reproduce

not sure how to explain this i downloaded the pack through AMP by CodeBreakers

### Expected behaviour

server starts

### Additional information

i even took out the Client side mods from my own files to replace the ones on the server and it wont start

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
