### ISSUE TITLE
Mekanism Refined Obsidian Infuser recipes missing

### ISSUE THREAD

**Issue by DT357** [FTBTeam/FTB-Modpack-Issues#3956]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Describe the bug

The recipes that allow refined obsidian / enriched obsidian to be put into the infusing yellow slot of the mekanism infusing factories are missing; this prevents Atomic Alloy from being created, which prevents progression to the late-game Mekanism modpack.

### Steps to reproduce

1. Make an infusing factory
2. Infuse powdered obsidian in an infusing factory with diamonds
3. try to put the refined obsidian dust into a new infusing factory - it will not go into the yellow infusing material slot.

### Expected behaviour

Infusing factory should accept enriched obsidian / refined obsidian dust to allow for the creation of atomic alloys.

**Comment by DinnerBeef** [comment]
Unable to reproduce. Please make sure you are trying to put the right items in the correct machine.
