### ISSUE TITLE
Server crash when killing Plague Doctor

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#3957]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Log Files

- [latest.log](https://pste.ch/eqikivecir.md)
- [crash report](https://pste.ch/inunugukuk.pl)

### Describe the bug

On killing a Plague Doctor from the Rats mod, the server I'm testing the pack on crashed.

### Steps to reproduce

1. Kill a Plague Doctor

Not sure how reproduceable the crash is. I've killed min. two prior to the crash without issue.

### Expected behaviour

No crash

**Comment by DinnerBeef** [comment]
I tried many times. But I am unable to reproduce this can. Can you please reopen this issue if you see it happen again in the newest version of the pack.
