### ISSUE TITLE
Copper nuggets not recognised by compacting drawer

### ISSUE THREAD

**Issue by Meteoblastdragon** [FTBTeam/FTB-Modpack-Issues#3959]
### Modpack

FTB Presents AbePack

### Modpack version

1.2.0

### Describe the bug

For all overworld ingots (only ones I have been able to test atm) the compacting drawers work as intended but not with copper. It just shows copper ingots and blocks but no nuggets.

### Steps to reproduce

Place compacting drawer. Click with copper ingot on the drawer. Watch it only show blocks and ingots but no nuggets

### Expected behaviour

The compacting drawer to show the nuggets as third option

**Comment by UnRealDinnerbone** [comment]
Try putting the copper nuggets in first

**Comment by Meteoblastdragon** [comment]
That seems to work indeed. Not exactly ideal but it works definitely as a temp solution. Weird that it's only an issue for copper though
