### ISSUE TITLE
[Bug]: Pneumatic Craft liquid compressor does not explode

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#396]
### Modpack

FTB University 1.16

### Modpack version

1.3.0

### Describe the bug

The standard pressure (5 bar) liquid compressor does not explode when run at dangerous pressure no matter how much time passes.

### Steps to reproduce

run the PNC liquid compressor at dangerous levels

### Expected behaviour

make boom-boom

**Comment by aaronhowser1** [comment]
Unable to reproduce, both types exploded when I maxed them out. I just put them down, put no pipes, and let them fill to burst.

**Comment by aaronhowser1** [comment]
Could be due to mod updates since the last pack version, though i can't remember if any released.
