### ISSUE TITLE
Add Configured mod for JEI

### ISSUE THREAD

**Issue by SpawnInsane** [FTBTeam/FTB-Modpack-Issues#3960]
### Modpack

FTB Presents Direwolf20 1.20

### Is your suggestion related to a problem? Please describe.

Can't config JEI in game.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/configured

Allows in game configuration of JEI.

![2023-10-06_04 17 37](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/36284692/1dfff1ff-6593-4f63-aeee-ee80858327a1)

**Comment by DinnerBeef** [comment]
Sorry, cant add that mod right now as it is not updated to 1.20. But it will be added if it gets updated to 1.20
