### ISSUE TITLE
Caliburn cap won't go up from initial 27 even when using nether stars witht he upgrade

### ISSUE THREAD

**Issue by thecas90** [FTBTeam/FTB-Modpack-Issues#3964]
### Modpack

FTB Presents AbePack

### Modpack version

1.2.0

### Describe the bug

In the mahou tsukai mod pack, I tried upgrading my enchanted with smite 5 caliburn's cap twice, each time throwing a netherstar before the sword in the fog pond. and both times the cap stayed at 27. is this a bug? it ate both my nether stars

### Steps to reproduce

You would need to make an enchanted diamond sword, throw in pond you made in mahou tsukai mod, then enchant caliburn with smite 5, and throw into pond with nether star first, and see if cap goes up from 27. 

### Expected behaviour

The cap should of went up to at least 35-50

### Additional information

Please help

**Comment by GHOSTLYxKNIGHT** [comment]
dont use a spawned sword is what ive noticed. If you make it normally with a diamond sword V Smite the base cap is 30, then it goes up from there.

**Comment by thecas90** [comment]
I just tried making two caliburn's from crafted diamond swords and the initial cap is still 27.

**Comment by thecas90** [comment]
I think this modpack set a 27 cap cause it's OP but didn't say in the notes. oh well
