### ISSUE TITLE
Advancement screen is small and doesn't scale with GUI

### ISSUE THREAD

**Issue by atealein** [FTBTeam/FTB-Modpack-Issues#3965]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Describe the bug

Advancement screen is quite small - is able to only show few advancements without scrolling and exploring some of the more extensive advancement trees because really a challenge of patience. Changing GUI scale did not affect the screen.

### Steps to reproduce

1. Install the pack, check the advancement screen.

### Expected behaviour

Previous versions had a much larger visibility?

### Screenshots

View in 1.20
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25322782/81a00a5a-bff8-41bd-8407-5bcf48f1f7e2)
Previous view in 1.19
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25322782/e2994c14-b4f5-478d-9805-707a15bf24b6)

### Additional information

I realize now this might be due to a missing mod (Better Advancements?) and not a bug but intentional design?

**Comment by DinnerBeef** [comment]
Thanks for reporting and issue, However this is working as indeed and will not be fixed.
