### ISSUE TITLE
Growthcraft Cheese Curds

### ISSUE THREAD

**Issue by BaconaBiscuit** [FTBTeam/FTB-Modpack-Issues#3971]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Describe the bug

Most of the cheese curd recipes are not working in the modpack. Was able to craft all curds when loading the mod with just JEI installed.

### Steps to reproduce

Missing recipes in JEI for cheese curds
Recipe in Mixing Vat for cheese curds not working

### Expected behaviour

Ability to craft all the cheese curds in mixing vat

**Comment by DinnerBeef** [comment]
This issue has now been fixed! Please reopen this issue if you are still having problems.
