### ISSUE TITLE
Items that require unlocking Gamestage cant be crafted on modded crafting menus

### ISSUE THREAD

**Issue by notZestly** [FTBTeam/FTB-Modpack-Issues#3972]
### Modpack

FTB Presents AbePack

### Modpack version

1.3.0

### Describe the bug

Gamestage specific items cant be crafted inside refined storage or sophiscated backpack's crafting menu, they have to be crafted on a vanilla crafting table. An example is the mekasuit.

### Steps to reproduce

1. Grab required items for Mekasuit
2. Try to craft it inside Refined Storage's crafting grid
3. Nothing comes up

### Expected behaviour

item should be crafted anywhere

**Comment by DinnerBeef** [comment]
Have you tired, relogging and see what happens? Can you also try this on the latest version of the ModPack and let me know what happens..
