### ISSUE TITLE
Game crashed when I type "Chest" in search bar.

### ISSUE THREAD

**Issue by DarkBladeNemo** [FTBTeam/FTB-Modpack-Issues#3974]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.13.1

### Log Files

https://pste.ch/gihufuriti.rb

### Describe the bug

The game crashes whenever I search "Chestplate" seems to crash around the "chest" part.

### Steps to reproduce

1. Search "chest" in JEI
2. crash?

### Expected behaviour

The game crashes

**Comment by pikminman13** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40
