### ISSUE TITLE
Error launching a modpack after an update

### ISSUE THREAD

**Issue by indommy** [FTBTeam/FTB-Modpack-Issues#3975]
### Modpack

FTB Presents AbePack

### Modpack version

1.3.0

### Log Files

[FTB APP][INFO] Validate Java Runtime
[FTB APP][INFO] Pre-Start Tasks

### Describe the bug

Can't launch modpack after updating it to 1.3.0.

### Steps to reproduce

1. Press Play

### Expected behaviour

Minecraft is expected launch

### Screenshots

<img width="448" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147277507/c5a98010-914b-4d0a-85e3-3e121bd47e60">

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack and app version?
If you are, would you be able to upload new log files for us so we can take a further look?
