### ISSUE TITLE
Cannot Lauch modpack

### ISSUE THREAD

**Issue by Invasla** [FTBTeam/FTB-Modpack-Issues#3977]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Log Files

[hs_err_pid54168.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12839393/hs_err_pid54168.log)
[hs_err_pid54948.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12839394/hs_err_pid54948.log)
[hs_err_pid55512.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12839395/hs_err_pid55512.log)
[hs_err_pid7916.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12839396/hs_err_pid7916.log)
[hs_err_pid49312.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12839397/hs_err_pid49312.log)

### Describe the bug

Cannot lauch the pack using the FTB launcher

### Steps to reproduce

1. Open launcher
2. Select modpack
3. Press play

### Expected behaviour

The modpack lauching and opening the instance window

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147283956/0aafcb0d-17e2-4224-9dba-a15d1717dd77)

**Comment by Strongward** [comment]
having same issue. any fix?

**Comment by DinnerBeef** [comment]
Can you please let me know if this is happening in the newest version of the pack? Current Version: 1.10.0

**Comment by Invasla** [comment]
> Can you please let me know if this is happening in the newest version of the pack? Current Version: 1.10.0
The issue is ongoing. It still doesnt even open a new window.
