### ISSUE TITLE
[Bug]: Molten Invar missing in JEI

### ISSUE THREAD

**Issue by nwageler** [FTBTeam/FTB-Modpack-Issues#398]
### Modpack

FTB OceanBlock

### Modpack version

1.9.0

### Describe the bug

Two different friends mentioned they could not see Molten Invar in JEI (as well as a few other Molten items) while we were playing in my server.  I could see them just fine.

I was able to reproduce by joining the server using a different MC account.  The missing items appear normally after joining a single player world, and appears to fix the issue as after rejoining the server the items were no longer missing.  This may explain why my main account had no issues as I had previously played a single player world before playing multiplayer.

### Steps to reproduce

1. Join a multiplayer game using a fresh install (i.e. do not launch a single player game beforehand)
2. Search JEI for "Molten Invar" and notice it is missing.
3. Quit and launch a single player world.
4. Search JEI for "Molten Invar" and notice it is visible.
5. Rejoin the server world.
6. Search JEI for "Molten Invar" and notice it is visible.

### Expected behaviour

Molten Invar should appear in JEI

### Screenshots

Player cannot see Molten Invar:
![2021-11-29_22 11 33](https://user-images.githubusercontent.com/91289520/144165282-79e85d29-8542-4ecb-bbbd-cdb6d3dd51ea.png)

I can see it fine:
![unknown](https://user-images.githubusercontent.com/91289520/144165296-ad314da9-681a-42d2-804b-a95601ebd05e.png)

**Comment by nwageler** [comment]
After some further testing, it appears that loading into a single player world only temporarily fixes the missing recipes.  The issue returns next time you load the MC client.

**Comment by Sunekaer** [comment]
Could you test if this is an issue on version 1.10.1 of the pack?

**Comment by nwageler** [comment]
Yes the issue is still present in a fresh 1.10.1 install.

**Comment by Jwguy** [comment]
Can confirm this is still occurring in 1.16.5 with TConstruct 3.3.4.335. Both Bronze and Invar are missing from JEI as of their most latest version for 1.16.5, v7.7.1.152.

I'm running a very, very bare bones pack for friends, not a major pack, either.
