### ISSUE TITLE
No recipe for Redstone Comparator & can't craft manually

### ISSUE THREAD

**Issue by BubbaVB** [FTBTeam/FTB-Modpack-Issues#3981]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.0

### Describe the bug

Recipe for the Redstone Comparator doesn't exist in the pack.  The Redstone Comparator shows up in JER but it's not it doesn't show the recipe nor are you able to manually craft if if you know the recipe.

### Steps to reproduce

Go to JER & search for Redstone Comparator.
Try to see recipe.

Alternative:
Click on crafting table
Try to manually craft Redstone Comparator.

### Expected behaviour

Craft Redstone Comparator

**Comment by drunkripper** [comment]
This is fixed in version 1.0.1. Please update to fix the issue!

**Comment by DinnerBeef** [comment]
Like @drunkripper said please update your pack.
