### ISSUE TITLE
No recipe Ritual Containment Sphere controller and port

### ISSUE THREAD

**Issue by ninjyang** [FTBTeam/FTB-Modpack-Issues#3982]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.13.1

### Describe the bug

I cant crafting Ritual Containment Sphere controller and port

### Steps to reproduce

Recipe does not appear when pressed r

### Expected behaviour

1. make Ritual Containment Sphere controller and port recipe 2. add quest and capsule to Ritual Containment Sphere

### Screenshots

![2023-10-08_19 58 16](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147314542/2c3a528c-6200-46a2-8344-21f3a91384ed)
![2023-10-08_19 58 33](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147314542/a176d287-781b-4bd6-8775-1de051d37b4a)

**Comment by pikminman13** [comment]
not supposed to have one. it's a quest reward.
