### ISSUE TITLE
Game Crash when open 'DE' quest chapter

### ISSUE THREAD

**Issue by Shaithiss** [FTBTeam/FTB-Modpack-Issues#3983]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.13.1

### Log Files

[hs_err_pid4340.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12840574/hs_err_pid4340.log)

### Describe the bug

The game crashes when i open the 'DE' chapter in the questbook

### Steps to reproduce

Open Questbook
Click 'DE' chapter
crash.

### Expected behaviour

no crash

**Comment by DinnerBeef** [comment]
Please update your pack name. You seem to have put the wrong pack name down.
