### ISSUE TITLE
FTB AbePack [Industrial Foregoing] "Addon: Range Tier 12" item has no recipes for Infinity Tools in JEI

### ISSUE THREAD

**Issue by mb9023** [FTBTeam/FTB-Modpack-Issues#3986]
### Modpack

FTB Presents AbePack

### Modpack version

1.3.0

### Describe the bug

The "Addon: Range Tier 12" item is used in all the Infinity Tool recipes (Infinity Drill/Hammer/etc), but does not show properly in JEI. Searching for the Addon and rightclicking it does not show recipes. Searching for Infinity Tool recipes and left clicking the Addon in the recipe does not show the recipe for making the Addon.

Attempting to use Refined Storage Crafters to autocraft these tools does not work, even when having the Addon item in storage. Crafting the Infinity Tools manually does still work.

### Steps to reproduce

1. Open JEI item search and type in "addon tier 12"
2. Left click item to view its recipe
3. Right click item and see that nothing happens
4. Search for Infinity Drill
5. Left click Drill and see recipe contains "addon tier 12"
6. Left click on the addon item and see that nothing happens.
7. Right click the addon and see it is used in multiple recipes

### Expected behaviour

The recipes need to be linked. In step 3, right clicking the item should show Infinity Tool recipes that you see in Step 7. Step 6 should display the recipe you see in Step 2.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
