### ISSUE TITLE
Crash on Ponder

### ISSUE THREAD

**Issue by SteseDav** [FTBTeam/FTB-Modpack-Issues#3987]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12841489/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12841492/latest.log)

[crash-2023-10-08_19.53.39-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12841510/crash-2023-10-08_19.53.39-client.txt)

### Describe the bug

using 'Ponder' on the Portable Storage Interface seems to cause a crash, once the instructions have completed. 

### Steps to reproduce

1. Hold 'W' to Ponder on the Portable Storage Interface
2. Watch instructions
3. Crash!

### Expected behaviour

Not to Crash

### Additional information

PC - Windows 10 22H2 48Gb Ram, Ryzen 3700x, nVidia RTX2060.

Launched Modpack via FTB App, allocated 8GB Ram to instance.

**Comment by DinnerBeef** [comment]
Mod Bug see Issue: https://github.com/Soaryn/XyCraftTracker/issues/25
