### ISSUE TITLE
Copper nuggets don't work with Compacting Drawers.

### ISSUE THREAD

**Issue by lpacphantom** [FTBTeam/FTB-Modpack-Issues#3988]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.0

### Describe the bug

I like to keep metals in compacting drawers to make ingots, blocks and nuggets available in AE2 without the need for autocrafting them. Most of the ingots are fine, but copper doesn't make nuggets available. I looked for myself how to add that as a custom recipe, but most of what I found was for Storage Drawers, not the new Functional Storage mod.

### Steps to reproduce

Make Compacting Drawer.
Add Copper Ingots.
Note lack of nuggets.

### Expected behaviour

Copper nuggets in compacting drawer.

**Comment by DinnerBeef** [comment]
It seems to be working fine for me. Only thing I can think of that you can try is putting in the copper nuggets first.
