### ISSUE TITLE
[Suggestion]: Unlock Infinity Pipe Upgrade

### ISSUE THREAD

**Issue by e30Birdy** [FTBTeam/FTB-Modpack-Issues#399]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

I kind of see it as an issue and some may agree but there is no wire in this pack capable of transferring enough power to even power one mk3 Power Pot. I feel the infinity Pipe upgrade could solve that for the pack or some pipe to adjust the power as one does not want to have 50 points from flux networks around their base each to power 1 pot, when I get to Mk4 pots I need 350k per tick and the only real way I can think of doing that is a tesseract for each pot or a point. Would be nice to just not have my base spammed with points.

**Comment by quietust** [comment]
Have you tried using Ultimate Universal Cables from Mekanism? I've been using them to power *dozens* of Mk4 Power Pots through a single flux point, and I haven't had any problems with them.

**Comment by e30Birdy** [comment]
> Have you tried using Ultimate Universal Cables from Mekanism? I've been using them to power _dozens_ of Mk4 Power Pots through a single flux point, and I haven't had any problems with them.

The ultimate cables only make 128k rf/t so how are you powering them fully? mk3 uses 185k rf/t and mk4 uses 350k rf/t.

**Comment by quietust** [comment]
> The ultimate cables only make 128k rf/t so how are you powering them fully? mk3 uses 185k rf/t and mk4 uses 350k rf/t.

Where did you get that number? A single Ultimate Universal Cable can hold 3.27 *million* RF, and if you connect it to a Flux Point then it will be able to transfer that much energy _per tick_ into whatever's connected to the cable. Furthermore, if your cable is more than one block long, then the total transfer rate will be multiplied by the number of blocks (e.g. a 10-tile cable will be able to transfer a combined total of 32.7 million RF/t).

**Comment by e30Birdy** [comment]
> > The ultimate cables only make 128k rf/t so how are you powering them fully? mk3 uses 185k rf/t and mk4 uses 350k rf/t.
> 
> Where did you get that number? A single Ultimate Universal Cable can hold 3.27 _million_ RF, and if you connect it to a Flux Point then it will be able to transfer that much energy _per tick_ into whatever's connected to the cable. Furthermore, if your cable is more than one block long, then the total transfer rate will be multiplied by the number of blocks (e.g. a 10-tile cable will be able to transfer a combined total of 32.7 million RF/t).

Wiki but I guess I was wrong. But still would be nice to be have for water transfer to reactors. =)

**Comment by Sunekaer** [comment]
Hi, infinity upgrade wont be "unlocked", thanks for the suggestion tho
