### ISSUE TITLE
Step Height Enchant 

### ISSUE THREAD

**Issue by volrathstormborn** [FTBTeam/FTB-Modpack-Issues#3992]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Describe the bug

Enchant any leg armor with Step Height and you still have to jump single block heights. 

I believe the Apotheosis step increase items work (no longer have the helm), but the Cyclic enchant is not. 

### Steps to reproduce

Apply Cyclic “Step Height” enchant to any leg armor. 

Equip and walk into single level block increase. You will stop rather than step up automatically. 

### Expected behaviour

Should walk right up without jumping.

**Comment by SpawnInsane** [comment]
Can back this up, I have ran into the same problem.

**Comment by itworksdontaskquestions** [comment]
also having this issue

**Comment by DinnerBeef** [comment]
Sadly, due to how the mods add the step height enchantments, this will not be able to be fixed for this pack.
