### ISSUE TITLE
xp boost and experience boost enchants not working

### ISSUE THREAD

**Issue by bookert01** [FTBTeam/FTB-Modpack-Issues#3993]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Describe the bug

the xp boost enchant is not working and the experience boost enchant is not word will killing mobs or mining. I tried them both on their own.

### Steps to reproduce

Apply EnderCore “XP Boost” enchant to a sword or pick-axe.

Go mining with the pick-axe or kill mobs with the sword.

Apply Cyclic “Experience Boost” enchant to a sword or pick-axe.

Go mining with the pick-axe or kill mobs with the sword.

### Expected behaviour

bonus XP

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
