### ISSUE TITLE
game crash 

### ISSUE THREAD

**Issue by befamouz** [FTBTeam/FTB-Modpack-Issues#3996]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Describe the bug

the game crashes if i use refined storage me system

### Steps to reproduce

build me system
put storage disk in disk drive 
open crafting grid
try to take item out of me system
game crashes

### Expected behaviour

that an update is available without the issue of th game crashing

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can take a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
