### ISSUE TITLE
[Bug]: Game Courrupted with Industrial Foregoing Enchantment Applicator + Pipez + Ender Tank

### ISSUE THREAD

**Issue by sugarnsalt** [FTBTeam/FTB-Modpack-Issues#4]
### Modpack

FTB OceanBlock

### Modpack version

1.0.1 and 1.1.0

### Describe the bug

The games corrupts and constantly crashes when the steps enchantment applicator + fluid pipe and endertank is being used. I tested it for both versions of the pack and the same issue occurs. The exception below was raised in the log file. 

Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity

### Steps to reproduce

1.Set up a powered (power source doesn't matter) enchantment applicator, a fluid pipe (from pipez mod) and an ender tank and connect them together in any way you like. 

2. Set the fluid pipe to extract from ender tank. 

3. World is corrupted.

### Expected behaviour

Not to crash

**Comment by Sunekaer** [comment]
Could you please attach your full crash log?  ( https://paste.feed-the-beast.com )

**Comment by sugarnsalt** [comment]
https://paste.feed-the-beast.com/view/a0c40f8e

**Comment by Sunekaer** [comment]
https://github.com/henkelmax/pipez/issues/74

**Comment by Boolyman** [comment]
This still happens.

**Comment by Raidobw2** [comment]
Please open a new issue
