### ISSUE TITLE
[Bug]: Didn't get my items back after I broke the grave.

### ISSUE THREAD

**Issue by Quidney** [FTBTeam/FTB-Modpack-Issues#400]
### Modpack

FTB Oceanblock

### Modpack version

1.9.0

### Log Files

https://gist.github.com/Quidney/d3dc14df61959e6e386527a000c45fa5

### Describe the bug

Oceanblock Gravestone Mod items disappearing.

I was in the nether when I got ambushed by a piglin, skeleton and a ghast. Cuz I didn't have any good armor and sword, I died but the death message was lagged out and gave me this message;

Quidney was fireballed by Piglin.

I thought it glitched because the piglin and the ghast hit me at the same tick or something so I didn't think about it much. Went back to nether just to break my grave and get 2 arrows and a bone.

I had a diamond paxel when I died and it was gone.

Even though diamond isn't something that rare in Oceanblock, It could happen again and I don't even know what causes it!

I now have full supremium armor, a supremium sword and a S-Paxel. I grinded for 2 days to get enough essence and it took me at least 2 hours to craft the essences, the essence ingots etc to make the tools. Don't even get me started on crafting the tools from the lowest tier and upgrading 1 by 1.

If I lose these items I probaby wouldn't continue playing the modpack and I don't wan't that to happen.

### Steps to reproduce

Hell if I know!

### Expected behaviour

Break my grave, get my items back.

### Screenshots

![](https://user-images.githubusercontent.com/62697261/144216482-9582d1a2-5a92-414f-821d-1090f96cc6c9.png)

**Comment by Raidobw2** [comment]
Quick tip: Make backups with `/ftbbackups start`. They'll be in the `backups` folder. They're also made automatically every 2 hours (normally).

We'll investigate this, but having those backups at hand will be very helpful to you.

**Comment by Quidney** [comment]
Ight will sure do! I don't have much storage though and each backup takes like 800mb - 1gb

**Comment by Raidobw2** [comment]
Well in that case, refer to this to get your items back and use command suggestions in-game to help you type the info:
![image](https://user-images.githubusercontent.com/17010632/144339991-1911fa83-decc-4dd3-94e2-b15a0bacd8ff.png)
`/restore <player> <death_id> <replace|add>`
The last parameter defines if you want to get the players inventory REPLACE (Overwritten) or ADD (Just adds the items to the players existing inventory).
Cheers.

**Comment by Quidney** [comment]
Thank you for the help!
Have a great one.
