### ISSUE TITLE
Dimlet workbench eat dimlets 

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Modpack-Issues#4001]
### Modpack

FTB University 1.19

### Modpack version

all

### Describe the bug

In the rftools dimlet workbench, if you have a dimlet in the output - a new dimlet you create will vanish (consumed the resources but does not give you the dimlet)

### Steps to reproduce

    place a dimlet workbench
    create a dimlet (for example a Flat terrain dimlet)
    do NOT take out the dimlet from the output
    create a new same dimlet
    the creation will consume the resources but the output will still remain 1

### Expected behaviour

output should contain 2 dimlets

**Comment by aaronhowser1** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/15698722/2efc7678-4df7-4078-9beb-fea7de2bd14c)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/15698722/43766473-4815-4ffc-b32d-aeaef323b659)

aparently i've entirely forgotten how this works, so ill save this for after i've figured it out again

**Comment by aaronhowser1** [comment]
Got it McJtyMods/RFToolsDimensions/issues/479

**Comment by UnRealDinnerbone** [comment]
This issue has been open since February without any update on the issue closing
