### ISSUE TITLE
Hot Cooking Plate only useable in the overworld

### ISSUE THREAD

**Issue by Dunbock** [FTBTeam/FTB-Modpack-Issues#4004]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.13.1

### Describe the bug

The _Hot Cooking Plate_ seems to only work in the overworld. Other dimensions tried: nether, end, compact machines 4 dimension, alfenheim. If applicable, the item will get used / vanish like _Fresh Water_ for _Hot Water_, but the liquid will not generate nor will _Hot Cooking Plate_ transform into a _Cool Cooking Plate_.

Note in regards to nether: In case the liquids generate obsidian or extinguish the player on fire, then they would need to be made not placeable in the nether and therefore the _Hot Cooking Plate_ then should not work in the nether. _Hot Water_ does atleast not generate obsidian, so there should technically be not problem with the _Hot Cooking Plate_ working in the nether. Other generated liquids untested in regards to obsidian generation. 

### Steps to reproduce

1. Go to dimension other than overworld (end, alfenheim, compact machines 4 block).
2. Place _Hot Cooking Plate_.
3. Right click _Hot Cooking Plate_ with _Fresh Water_.
4. Note that _Fresh Water_ is used up, but no _Hot Water_ is generated on top of _Hot Cooking Plate_ and _Hot Cooking Plate_ does not get transformed into _Cool Cooking Plate_.

### Expected behaviour

_Hot Cooking Plate_ works in dimensions other than the overworld, i.e. generate for example _Hot Water_ when right clicked with _Fresh Water_..

**Comment by pikminman13** [comment]
fixed in dev
