### ISSUE TITLE
JAOPCA error loading Direwolf20 

### ISSUE THREAD

**Issue by vetchris** [FTBTeam/FTB-Modpack-Issues#4006]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Log Files

[crash-2023-10-10_08.20.43-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12857180/crash-2023-10-10_08.20.43-fml.txt)

### Describe the bug

JAOPCA encountered an error during the construct event phase

### Steps to reproduce

reinstalled pack and tried reinstalling the version 4.4.4.5 of Jaopca mod

### Expected behaviour

help on why this fails

### Screenshots

![Screenshot 2023-10-10 082406](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/50930642/40a567e0-9327-4aea-9662-9cd1ed478d18)

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by vetchris** [comment]
I have to disable my virus scanner in Aura and it let's me launch the pack
even though I add the whole pack folder as an exception
