### ISSUE TITLE
Dupe bug with SAG Mill and ingots

### ISSUE THREAD

**Issue by FishOutOfH20** [FTBTeam/FTB-Modpack-Issues#4007]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Describe the bug

Processing ingots in the SAG Mill will net you extra dusts based on grinding ball's properties.

### Steps to reproduce

1. Put in 8 iron or gold ingots.
2. Get back about 12 dusts.
3. Rinse and repeat for infinite resources.

### Expected behaviour

Grinding ingots should not produce extra dusts.

**Comment by swestrup** [comment]
You can also do this with diamonds.

**Comment by DinnerBeef** [comment]
It looks like the mod dev has resolved this issue now. https://github.com/Team-EnderIO/EnderIO/pull/616. This should be fixed in the latest version of the modpack.
