### ISSUE TITLE
Warp Scroll (ars nouveau) not craftable from Sophisticated Backpacks crafting upgrade

### ISSUE THREAD

**Issue by w0ntoan** [FTBTeam/FTB-Modpack-Issues#4009]
### Modpack

FTB Presents AbePack

### Modpack version

1.3.0

### Describe the bug

The Warp Scroll (ars nouveau) recipe is available after killing the Ur-Ghast, but it is only craftable from a crafting table, and not craftable from the crafting table from the crafting upgrade in a backpack from Sophisticated Backpacks.

### Steps to reproduce

Kill Ur-Ghast, Craft warp scroll in crafting table, make a backpack with crafting upgrade, open backpack's crafting table, try to craft warp scroll but no output is available.

### Expected behaviour

Warp Scroll should be available in backpack crafting table

### Screenshots

![warpscrollfail](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/5566366/a1c18fcf-0943-4a5b-b012-0bab8ec8d678)

**Comment by UnRealDinnerbone** [comment]
Same as #3972
