### ISSUE TITLE
Squeezer makes wrong raw zinc

### ISSUE THREAD

**Issue by Lohoydo** [FTBTeam/FTB-Modpack-Issues#4010]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.0.1

### Describe the bug

The Squeezer and Mechanical Squeezer recipes for turning zinc ore to raw zinc creates Railcraft Reborn raw zinc instead of the create version

### Steps to reproduce

1. Put zinc ore in Squeezer or Mechanical Squeezer
2. Get Railcraft Reborn Raw Zinc
3. Process raw zinc further (limited recipes, not all machines can handle this version)

### Expected behaviour

Create raw zinc from Create

**Comment by DinnerBeef** [comment]
This issue has now been fixed! Please reopen this issue if you are still having problems.
