### ISSUE TITLE
AE2 pattern providers are using channels but are not usable for crafting in assember pattern provider set up

### ISSUE THREAD

**Issue by robertm1771** [FTBTeam/FTB-Modpack-Issues#4015]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1

### Describe the bug

After update patterns in pattern providers are lost or distroyed if moved using patter terminal. Seems not all patterns are showen in pattern terminal. After update.

### Steps to reproduce

Not 100% sure but 
Open pattern terminal and see if your normal pattern for layout
move patterns to missing locations 
now patterns are still listed for crafting but no londer in pattern providers. 
Causes crafting to hang and patterns for items are missing from providers.

### Expected behaviour

Patterns to not be removed or replaced when moved in pattern terminal 

### Screenshots

<img width="605" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/6488750/4e7f7578-8408-46ac-9c91-ce086a75fab4">
<img width="607" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/6488750/d4f4c601-92be-4d96-a7d2-d274baee3bbb">
<img width="435" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/6488750/8918192d-3950-41a7-9a3d-09a291fa7dac">

### Additional information

I hope the images shows little more information. As you can see ae2 system can see a pattern for copper upgrage for functional storage but the patten is no longer listed in my pattern terminal. All autocrafting issues started after I moved patterns in my pattern terminal to "blank" pattern locations.

**Comment by robertm1771** [comment]
<img width="397" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/6488750/4ec023a1-b8a8-4367-93db-784b855be8d6">
Update image for patterns show in pattern terminal

**Comment by robertm1771** [comment]
Missing patterns are in providers but autocrafting cant see them. Unsure where the problem lies I think its tied to the pattern terminal though

**Comment by robertm1771** [comment]
Sorry but seems to be an issue with how AE2 is seeing pattern providers in my assember provider setup. I have used the same setup in the past without issue. Pattern providers are using channles but the patterns are not usable by system for crafting. Sorry having issues discribing

**Comment by robertm1771** [comment]
Seems to be an issue with channel passing thought assembers it limited to 8 unknow if new feature or bug

**Comment by DinnerBeef** [comment]
Thanks for reporting and issue, However this is working as indeed and will not be fixed.
