### ISSUE TITLE
More Mod/Feature suggestions, this time from other people from Blau's community server

### ISSUE THREAD

**Issue by Meteoblastdragon** [FTBTeam/FTB-Modpack-Issues#4016]
### Modpack

FTB Presents AbePack

### Is your suggestion related to a problem? Please describe.

"Ore generation is still in default Minecraft levels meaning ores compete for spawn locations and end up becoming incredibly rare. The mining dimension still generates ores at default Minecraft rates. We've built a quarry and looking down it you see like 1000 blocks of stone, 4 coal, 5 emeralds, and 3 copper ore. With every other ore spawn being modded ones. This means if 1 chunk had 100 iron ore inside it in vanilla, it now contains something like 10 iron ore or less"

Please check out other suggestions/bug reports from me if you haven't already

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics
Create a more advanced network with AE2 and Meknism with chemical support.

https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails 
Adds larger and smaller tracks as well as monorails and coverable tracks to allow for street cars, cable cars, and more allowing for small base transport similar to the car mod they added with 1.4

https://www.curseforge.com/minecraft/mc-mods/create-confectionery
Is something Blau would love as well as anyone making food stores as it adds a huge variety of foods you need a factory floor for

https://www.curseforge.com/minecraft/mc-mods/create-deco
Create deco from a purely decorative perspective but we've got alternatives so it's fine if not

https://www.curseforge.com/minecraft/mc-mods/evilcraft
It's got blood magic and flying Brooms. Good for Blau's evil villain arc.

https://www.curseforge.com/minecraft/mc-mods/trash-cans
To get rid of unnecessary clutter.

https://www.curseforge.com/minecraft/mc-mods/controllable
Allows players to play Java MC with a controller like when playing Bedrock MC

**Comment by DinnerBeef** [comment]
Thank you for your suggestion, but at this time will not be adding these mod to the Mod Pack.
