### ISSUE TITLE
FTBSkies Eye of Sky Legen Server Crash

### ISSUE THREAD

**Issue by mdinnocenzo** [FTBTeam/FTB-Modpack-Issues#4017]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Log Files

[debug-1.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12874827/debug-1.log)

### Describe the bug

Eye of Sky Legend has an outdated structure file and crashes the server when trying to use.  The item is creatable but upon use the system will halt about a DFU and stop the server.

### Steps to reproduce

Craft the Eye of Sky Legend
Right Click to use the item

### Expected behaviour

effect of the item to show the location of the castle

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10065027/ce5996d8-11a4-4d39-93c9-63443da1d392)

**Comment by Saereth** [comment]
in the next update we've configured structures essentials to fail if it takes long enough to trigger a watchdog crash instead.
