### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by aragonnetje6** [FTBTeam/FTB-Modpack-Issues#4024]
### Modpack

FTB University 1.19

### Modpack version

1.3.1

### Log Files

[log.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12886139/log.txt)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12886141/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12886142/debug.log)

### Describe the bug

Seamless is still causing an issue in servers on linux. this is causing the server to fail on launch

### Steps to reproduce

1. install FTB University 1.19 server version 1.3.1
2. run start.sh and agree to eula
3. wait for server to stop loading

running with --safeMode as the logs suggest does not work

### Expected behaviour

The server should start

**Comment by Raidobw2** [comment]
Try removing the "seamless" mod from the server for now. We will need to fix this in the pack, I'll let the dev know now.

This should at least get your server working for now as the mod seems to be clientside only. Let me know and thanks for the report

**Comment by aragonnetje6** [comment]
Works like a charm, thank you!

**Comment by aaronhowser1** [comment]
Hm, this should have been fixed in 1.3.1. I'll see what's up with that.

**Comment by aaronhowser1** [comment]
Fixed
