### ISSUE TITLE
Loot Table Error (Bandit Tower Chests Empty)

### ISSUE THREAD

**Issue by MoMochi77** [FTBTeam/FTB-Modpack-Issues#4025]
### Modpack

FTB Presents AbePack

### Modpack version

1.4.0

### Describe the bug

None of the chest produce any loot at Bandit Towers. It seems as though when the chest is open the 'expected modpack' causes an error to the loot table.

### Steps to reproduce

1. Go to Bandit Towers
2. Open the shared loot chests

### Expected behaviour

The chests not being empty and have some loot to gather

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147756187/8549f0b9-55f3-4174-9a51-b7105ea347e1)

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
