### ISSUE TITLE
OutOfBounds Exception while trying to join my locally hosted server for AbePack

### ISSUE THREAD

**Issue by boyshinboiv** [FTBTeam/FTB-Modpack-Issues#4029]
### Modpack

FTB Presents AbePack

### Modpack version

1.4.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12888233/latest.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12888235/latest.log)

### Describe the bug

I get a specific error every time I try to join my locally hosted server (both when I set the server address to 0 and my ip address). 

### Steps to reproduce

1. Install server files for 1.4.0 of AbePack
2. Launch the server
3. Connect to the server using an instance of AbePack 1.4.0 client.

### Expected behaviour

Get an OutOfBounds  Exception error and be disconnected from the server.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147779461/0a9c2731-b05c-4564-84b5-8aa8f66c4d82)

### Additional information

The Mod folders in my modded client and the actual server are identical.

**Comment by Gaz492** [comment]
Your log looks to be showing that your server is running as pure vanilla (no mods/modloader installed)
May I ask how you created your server?
