### ISSUE TITLE
[Suggestion]: Add the Lens Grinder from Environmental as a Quest/Optional Quest

### ISSUE THREAD

**Issue by GriSphera** [FTBTeam/FTB-Modpack-Issues#403]
### Modpack

FTB University 1.16

### Is your suggestion related to a problem? Please describe.

Recently, messing around with Enviromental Tech, I discovered this machine: the Lens Grinder. It offers a similar funcionality as that of the Laser lens in the previous versions of the mod, that being manipulating the drops of the void miner.
The machine in question.

![2021-12-01_15 06 29](https://user-images.githubusercontent.com/88846902/144317120-85f8dd05-6088-4d1e-b154-1ab18d477e6f.png)
Its crafting recipe.

![2021-12-01_15 06 44](https://user-images.githubusercontent.com/88846902/144317234-de140963-da02-4909-82f5-be083e17bf29.png)
This thing works in colaboration with the void miner, by placing the crafted lens in the lens holder present in the former.
Lens holder (second tier void miner).

![2021-12-01_15 35 46](https://user-images.githubusercontent.com/88846902/144317455-7dcef0bc-19d0-46a1-b929-715f594a0314.png)
The first one works only with the crystal flash memory (which is obtained as the pictures below show. Having pictures of this may be a good thing, as many people struggle finding it).

![2021-12-01_16 36 36](https://user-images.githubusercontent.com/88846902/144318020-16cc1311-5ae1-4ca4-9ea4-845ce7758ef4.png)
![2021-12-01_16 36 40](https://user-images.githubusercontent.com/88846902/144318053-7e1a51f5-ba29-45a6-b2f4-77aacf02da61.png)
![2021-12-01_16 36 48](https://user-images.githubusercontent.com/88846902/144318058-7b0917ca-77ff-4c62-85dd-140547b61fac.png)
The other multi miners.

![2021-12-01_16 36 55](https://user-images.githubusercontent.com/88846902/144318066-baa2329a-da6f-47a2-8923-906dbe091b16.png)
So, it works by placing the block of the crystal you want and selecting the one that corresponds.
Here is how it looks.

![2021-12-01_15 08 13](https://user-images.githubusercontent.com/88846902/144318733-7c129b1e-d600-4d16-b9b2-48a698da577c.png)
Here is the litherite one (Idk what the bugged one does, probably nothing, as it doesn't accept londstanite crystal either).

![2021-12-01_15 08 21](https://user-images.githubusercontent.com/88846902/144318767-d1daf8dc-e824-4d6e-984e-3efd3abcfe5a.png)
After finding it, I place the block of the crystal to the top right slot and click the lens.

![2021-12-01_15 08 25](https://user-images.githubusercontent.com/88846902/144318988-9f76b325-acab-4c44-a992-5fbc473a3319.png)
![2021-12-01_15 08 27](https://user-images.githubusercontent.com/88846902/144319043-1bc0d9ad-1624-4e0a-8af8-1cdf805ef9ab.png)
And it's done. Now we place it on the lens holder and look the results.
Void miner and it's regular crystal drops.

![2021-12-01_15 08 50](https://user-images.githubusercontent.com/88846902/144319282-adc5ac3d-6fa6-45d8-8e09-8f227023fb52.png)
![2021-11-25_11 44 45](https://user-images.githubusercontent.com/88846902/144319325-0d11de19-9a32-404a-8a70-33a2e82a0c68.png)
![2021-11-25_11 44 50](https://user-images.githubusercontent.com/88846902/144319350-e5d90a95-3120-43c5-a5cf-eca103b335cd.png)
![2021-12-01_15 08 43](https://user-images.githubusercontent.com/88846902/144319540-3f589217-a737-4869-9f44-b6499931c6a8.png)
Placing the lens and seeing it's effects. It now has more than twice the chance of dropping the litherite crystals.

![2021-12-01_15 08 55](https://user-images.githubusercontent.com/88846902/144319596-401274ab-b82d-41e7-b002-431f623e6d20.png)
![2021-12-01_15 08 57](https://user-images.githubusercontent.com/88846902/144319602-a7a52217-ebca-4375-82fd-d20f0619cc67.png)
![2021-12-01_15 09 01](https://user-images.githubusercontent.com/88846902/144319608-cd9f51f9-535a-48d5-a6c5-f6f664792600.png)
The other lens type is applied to all the other flash memory types.
Here is the lens recipe. They don't do anything yet.

![2021-12-01_15 08 04](https://user-images.githubusercontent.com/88846902/144319790-a427126b-114c-4111-a106-f6afc7a24d5c.png)
Here is their GUI in the lens grinder. All 16 vanilla colors are used. You select the one you want, place the lens and then they get colored. You can take an already colored lens and overwrite it as well, like the flash cards with the memory programmer. It works in relation to the color of your choosing. So, if you choose cyan, drops that have cyan as their main color have their chances increased. This isn't exactly intuitive, so maybe another suggestion would be adding a mod that shows the main color of a block. But I'm not sure if that exists.

![2021-12-01_15 12 32](https://user-images.githubusercontent.com/88846902/144319954-bcdb2a78-4da8-4cad-97a4-94b4f572d2e9.png)
Four different lens.

![2021-12-01_15 14 24_2](https://user-images.githubusercontent.com/88846902/144320356-af891159-b8ba-41c1-9dd9-6b777aee467a.png)
Here I use a metallic ore flash card. Gold has a low percentage. After I place the yellow lens, it now drops gold almost six times more than the usual.

![2021-12-01_15 15 00](https://user-images.githubusercontent.com/88846902/144320630-9c4e8a7f-ac83-4625-b8d9-24a397be6864.png)
![2021-12-01_15 14 34](https://user-images.githubusercontent.com/88846902/144320703-72dc7662-de4a-42ad-91a8-7e93b8976c77.png)
![2021-12-01_15 15 06](https://user-images.githubusercontent.com/88846902/144320718-12987833-2c2a-4962-bf2c-58c66c5eacfa.png)
Same with Uranium, a modded ore. So that means that modded materials work as well (it uses cactus green lens, didn't had the capture).

![2021-12-01_15 17 29](https://user-images.githubusercontent.com/88846902/144321073-0fb46bb1-4ee0-453c-a674-ee84cea3a3cb.png)
![2021-12-01_15 17 51](https://user-images.githubusercontent.com/88846902/144321078-9794193e-ec9e-445b-8c9a-5dd2a58a6578.png)
So my suggestion consists on adding a quest that explain how does the machine work, it being either a required quest for completion, or an optional one.

I'm sorry if this was quite long, but as there is barely any documentation for this mod, I wanted to document it myself, hoping it is of help.

**Comment by Raidobw2** [comment]
Thanks for the suggestion.

To dev: TL;DR: Read title

**Comment by aaronhowser1** [comment]
Wow that's a very comprehensive issue! Tyvm lol.

The machine didn't exist when I was making the quests, and I didn't notice it was added. Thank you!

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/144752512-77acc202-b9bb-4014-a50e-d3990a778400.png)
![image](https://user-images.githubusercontent.com/15698722/144752521-5c13eda9-a879-4cdc-8534-52c59667f086.png)

**Comment by GriSphera** [comment]
Just two lil things. Mention that the crystal lenses are made of the block of the crystal that you wanna influence (or add it as a tip on JEI, whatever you feel is better). And you had a small typo: you wrote similarly  as simialrly. That's all.

**Comment by aaronhowser1** [comment]
For the first, I think "They make it more likely for the Miner to drop the Crystal of the Lens' type." should already be sufficient. For the second, fixed ty
