### ISSUE TITLE
GrowthCraft Rice should be Ore dictionaried with Rice not GrowthCraft Rice Stalk

### ISSUE THREAD

**Issue by EarthwormO** [FTBTeam/FTB-Modpack-Issues#4033]
### Modpack

FTB Presents Direwolf20 1.20

### Is your suggestion related to a problem? Please describe.

Currently for GrowthCraft Rice you have to use the Stalk in recipes, where it really should be the processed stalk which turns into Rice that should be used in the recipes. Currently the only use for GrowthCraft Rice itself is to make Sake.  All other recipes use the unprocessed stalk.

**Comment by DinnerBeef** [comment]
This issue has now been fixed! Please reopen this issue if you are still having problems.
