### ISSUE TITLE
BuildingGadgets2

### ISSUE THREAD

**Issue by BoraFiuDoBiuu** [FTBTeam/FTB-Modpack-Issues#4035]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Describe the bug

When i try to choose the block with the command shift + right click, its says invalid block. The same happens with the cut-past tool, but instead of saying invalid block the command shift + right click does nothing.

### Steps to reproduce

Go to Building gadget 
Shift Right click a block of choice 
Expect the bug " invalid block"

### Expected behaviour

i hope u can give me a solution to resolve this problem

**Comment by DinnerBeef** [comment]
What block are you trying to copy? Some blocks are blacklisted.

**Comment by BoraFiuDoBiuu** [comment]
Hi for some reason i figured it out... when i got into AE2 and linked my building gadgets to my network they start to work. But thanks anyway

Enviado de Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
