### ISSUE TITLE
Angel ring randomly stops flying when wearing armour

### ISSUE THREAD

**Issue by StefinitelyLethal** [FTBTeam/FTB-Modpack-Issues#4037]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Describe the bug

When you are wearing armour from Ars Nouveau you randomly stop flying, When you are wearing armour in general, and take damage, you stop flying. If you CHANGE your armour, I.E. take it off, or put it on, you also stop flying.

### Steps to reproduce

Equip angel ring
Wear Armour
Take damage

### Expected behaviour

Creative flight

### Additional information

You can see me extensively test this, while losing my mind.... here: https://www.twitch.tv/videos/1950485404

**Comment by StefinitelyLethal** [comment]
Update! I have discovered that any NBT change to armour you are wearing causes the angel ring to stop working

**Comment by robertm1771** [comment]
Mod author didnt see an issue so must be another mod causing issues shame its not been looked into
