### ISSUE TITLE
/spark commands don't display number data

### ISSUE THREAD

**Issue by lil0programmer** [FTBTeam/FTB-Modpack-Issues#4038]
### Modpack

FTB University 1.19

### Modpack version

1.3.1

### Log Files

https://mclo.gs/APMtDSD client

https://mclo.gs/6i3lyVz server

### Describe the bug

spark quick commands like /tps, /gc or /health are answered by the server but come blank on client

### Steps to reproduce

on client, give yourself /op to use spark cmds
proceed to run /spark tps, /spark health, /spark gc
contemplate the lack of data

### Expected behaviour

it shoud be showing numbers

### Screenshots

![2023-10-14_11 13 50](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/78182381/c6773fa0-ceba-4e89-a1bb-fb37f8d83e7b)

**Comment by aaronhowser1** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/15698722/39fcaef5-4002-4249-9d76-097646d056a2)
Potentially fixed in a mod update as this issue is rather old
