### ISSUE TITLE
Cannot Bulk Blast Terracotta using create - consistency+ conflicting reciep

### ISSUE THREAD

**Issue by Kwiechowski** [FTBTeam/FTB-Modpack-Issues#4039]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.9.0

### Describe the bug

Conistency+ smooth clay takes the spot of terracotta as the result of bulk blasting clay and you cannot bulk blast smooth clay into terracotta
This removes the ability for great to produce terracotta (which is used in production of gold)

### Steps to reproduce

1. Set up Depot in Create with blocks of clay
2. bulk blast the depot until blocks of clay turn into smooth clay
3. -cannot do anything to turn either the clay or smooth clay into terracotta

### Expected behaviour

Either clay bulk blasts into terracotta or smooth clay bulk blasts into terracotta

**Comment by Gaz492** [comment]
Just a note for our devs to clarify the issue.
When bulk blasting:
- Clay > Smooth Clay
- Smooth Clay > Smooth terracotta

It's not possible to get regular terracotta through bulk blasting.

**Comment by DinnerBeef** [comment]
Unfortunately, this is a side effect of how the Create mod works. You will have to use a blast furnace if you want to get terracotta.
