### ISSUE TITLE
Bug]: Kitten Bee uses the wrong model

### ISSUE THREAD

**Issue by Vaerys-Dawn** [FTBTeam/FTB-Modpack-Issues#404]
### Modpack

FTB Ultimate Anniversary Edition

### Modpack version

1.0.2

### Log Files

N/a

### Describe the bug

Kitten Bee model is wrong

### Steps to reproduce

Observe Kitten Bee

### Expected behaviour

Kitten Bee Should have "BaseModelType" : "KITTEN" in the main section of the JSON

### Additional information

See correct JSON below
```Json
{
    "flower": "tag:minecraft:beds",
    "baseLayerTexture": "/kitten/bee",
    "maxTimeInHive": 600,
    "sizeModifier": 0.75,
    "creator": "Dawn Felstar",
    "lore": "Cute little baby kitty bee.",
    "loreColor": "rainbow",
    "traits": ["kitten"],
    "hasHoneycomb": true,
    "customCombDrop": "resourcefulbees:catnip_honeycomb",
    "customCombBlockDrop": "resourcefulbees:catnip_honeycomb_block",
    "baseModelType": "KITTEN",
    "ColorData": {
        "primaryColor": "#EAA939",
        "secondaryColor": "#4C483B",
        "isBeeColored": false
    },
    "CombatData": {
        "isPassive": false,
        "removeStingerOnAttack": false,
        "attackDamage": 0
    },
    "MutationData": {
        "hasMutation": false
    },
    "SpawnData": {
        "canSpawnInWorld": true,
        "spawnWeight": 2,
        "biomeWhitelist": "tag:rare",
        "biomeBlacklist": "",
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "lightLevel": "DAY"
    },
    "BreedData": {
        "isBreedable": true,
        "breedWeight": 3,
        "breedChance": 0.6,
        "parent1": "tropical",
        "parent2": "curious",
        "feedItem": "tag:forge:raw_fishes",
        "feedAmount": 4
    },
    "TraitData": {
        "hasTraits": true
    }
}
```

**Comment by Vaerys-Dawn** [comment]
Btw as one of the devs for resourceful bees I am more than happy to provide assistance and support for the bees in this pack, if a developer would like to contact me they can do so on discord by adding @Dawn Felstar#1234 as a friend

I have a large supply of bee textures and would be more than happy to help by supplying custom textures for more of the bees

**Comment by Raidobw2** [comment]
Thanks a lot for the fix! And for your availability. I personally have not developed the modpack, but I'll relay your generous offer to our other devs that have. :)

**Comment by MaxNeedsSnacks** [comment]
@Raidobw2 For referernce, feel free assign me to any future Bee issues in FTBU:AE if you can, since Bees were basically my job in this pack :p

**Comment by Raidobw2** [comment]
Ok Max, thanks a lot, will do ^-^
