### ISSUE TITLE
Electrolytic separator not affected by energy upgrades

### ISSUE THREAD

**Issue by BeakerLSC** [FTBTeam/FTB-Modpack-Issues#4040]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Describe the bug

Mekanism machine, electrolytic separator accepts the energy upgrades but they have no affect.  With 8 upgrades installed the machine still shows that it needs 160 FE/T.

### Steps to reproduce

1.  Craft electrolytic separator and energy upgrades.
2. Put the upgrades in the machine.
3. See that the FE/T usage does not decrease.

### Expected behaviour

I expected the energy upgrades to reduce the energy cost of the machine.

### Screenshots

![2023-10-14_13 15 27](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147940245/42b0f078-11b7-45e0-8abe-4867a421855a)
![2023-10-14_13 15 35](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147940245/d48088aa-29aa-4a1c-82f0-eb19cebf5f80)

**Comment by eppi98** [comment]
Bumping this bug, can concur it exists 

![DW20_ES_EnergyBug](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/126548168/b72d1f6d-705d-42fc-8b81-c6b75b48fa7e)

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
