### ISSUE TITLE
Neutral mobs are not spawning

### ISSUE THREAD

**Issue by saenoa** [FTBTeam/FTB-Modpack-Issues#4041]
### Modpack

FTB Presents AbePack

### Modpack version

1.4.0

### Describe the bug

Bats and Squids are not spawning, but they are not disabled

### Steps to reproduce

no regular squids/bats spawns

### Expected behaviour

theyre supposed to spawn

**Comment by VoodooBeard** [comment]
I've been looking for squid for days. There's recipes that require ink sacs that have no other crafting recipes.
The whole of Occultism requires a constant supply of "Book and Quill", for example

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
