### ISSUE TITLE
Ironjetpacks cause crashes when equiped into the curio body slot

### ISSUE THREAD

**Issue by peisach** [FTBTeam/FTB-Modpack-Issues#4043]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Describe the bug

I play Direwolf20 1.20 on a private server.  The jetpack works fine when you equip it in the normal chest slot.  Whenever I put an ironjetpacks jetpack into a curio slot, however, my game client crashes.  Furthermore, when I try to log back in, the client keeps crashing until I restore my world to a prior backup.  

### Steps to reproduce

1. Create an ironjetpack jetpack (I made a diamond one)
2. Put the jetpack into a curio slot

### Expected behaviour

The game not to crash

**Comment by Medivha** [comment]
i have a the Gold Jetpack in the Curio Slot and it works fine for me no crashes(singleplayer).
Maybe check another Tier if it is specific to the Diamond. maybe server related. crash report/logs?!

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you? If so, can you please upload your crash report?
