### ISSUE TITLE
won't work

### ISSUE THREAD

**Issue by empyrealtech** [FTBTeam/FTB-Modpack-Issues#4044]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.20

### Log Files

https://pste.ch/ixiyuquwah.css

### Describe the bug

when i try and launch the mod pack, it will crash, and not give me a clear answer to what the problem is. 

### Steps to reproduce

download modpack 
click play

### Expected behaviour

the game would open

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you? Please re-upload your crash log if need be, as the link does not seem to be working any longer.
