### ISSUE TITLE
Instance crashes during startup after trying to add new mod to modpack

### ISSUE THREAD

**Issue by paleorchids** [FTBTeam/FTB-Modpack-Issues#4045]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Describe the bug

I tried to add a mod to the Unstable modpack, but the instance crashed during startup. I removed the mod from the modpack, but it just keeps crashing anytime I try to launch.

### Steps to reproduce

1. Go to FTB launcher
2. Add Forgematica mod to FTB Unstable modpack
3. Click play
4. Instance starts up and soon crashes

### Expected behaviour

Instance launches the game instead of crashing

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
