### ISSUE TITLE
game crashing

### ISSUE THREAD

**Issue by XiXnecromancer** [FTBTeam/FTB-Modpack-Issues#4047]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Log Files

[crash-2023-10-15_13.24.25-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12909270/crash-2023-10-15_13.24.25-server.txt)

### Describe the bug

when i enter my single player world after 2 - 5 minutes of playing the game start crashing. It started doing it recently after the i updated the modpack. 

### Steps to reproduce

1. start the game
2. go to single player
3. start the world
4. whait for the game to crash

### Expected behaviour

to be able to play normally without crashing

### Screenshots

no response 

### Additional information

no response

**Comment by TheBlackEntity** [comment]
Additional information:
This crash happen when any Tropicraft fruit tree grows

I had the same issue.
I just set randomTickSpeed to 0 so I can remove all saplings and set it back to 3 after that

**Comment by XiXnecromancer** [comment]
> Additional information: This crash happen when any Tropicraft fruit tree grows
> 
> I had the same issue. I just set randomTickSpeed to 0 so I can remove all saplings and set it back to 3 after that

Thanks  a lot that saved my gameplay :D <3
