### ISSUE TITLE
Crash when Laser IO node + Item Card + Basic Filter is next to a Fabricator

### ISSUE THREAD

**Issue by thecrypticace** [FTBTeam/FTB-Modpack-Issues#4048]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Log Files

https://pste.ch/wijuhidilu.pl

### Describe the bug

The server crashes when a Fabricator is next to a Laser IO node and that node has two Item Cards on the side of the Fabricator and a basic filter is placed into one of them. The server will crash in such a way that it gets stuck shutting down and generally must be force-killed.

### Steps to reproduce

Items needed: 1 Xycraft Fabricator, 1 Laser IO Node, 2 Item Cards, 1 Basic Filter
1. Place down the Fabricator (crafting grid is face up)
2. Fill in the processor binding recipe from JEI
3. Place Laser IO Node in front of it
4. Place 2 Item Cards in the Laser IO Node face toward the Fabricator (the tab that has it's icon)
5. Place a basic filter in the first item card

Boom server crashes and you can't login without the server crashing again. You have to restore the world from backup where those blocks are not next to each other.

### Expected behaviour

Server doesn't crash, world doesn't become unplayable

### Screenshots

Even better, I have a video:

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/614993/3b8684e7-e0e4-41a7-a7e1-c7c7bfaf07ec

**Comment by DinnerBeef** [comment]
This issue has now been fixed! Please reopen this issue if you are still having problems.
