### ISSUE TITLE
[Bug]: Custom Honeys give way more saturation than they probably should

### ISSUE THREAD

**Issue by Vaerys-Dawn** [FTBTeam/FTB-Modpack-Issues#405]
### Modpack

FTB Ultimate Anniversary Edition

### Modpack version

1.0.2

### Log Files

N/a

### Describe the bug

Custom Honeys give way more saturation than they probably should

### Steps to reproduce

go to the beepedia
open the honey tab
look at the given saturation levels

### Expected behaviour

Custom honeys should not almost always give max saturation

### Screenshots

![image](https://user-images.githubusercontent.com/5305116/144325612-c524a42f-41fc-435f-83a1-7a6f1ba48f0d.png)
![image](https://user-images.githubusercontent.com/5305116/144325628-94d2561c-de86-462a-a731-905c72526233.png)
![image](https://user-images.githubusercontent.com/5305116/144325637-a4e2b5b9-c276-462b-87c0-f0c05920e545.png)

**Comment by MaxNeedsSnacks** [comment]
Oh dear this... doesn't seem right.

The saturation multiplier is supposed to be 1 on these, meaning they should give 3 full hocks of saturation (I think?)

For reference, here's the JSON for aluminium honey:

```json
{
    "hunger": 3,
    "honeyColor": "0xdfedf2",
    "saturation": 1,
    "isRainbow": false,
    "honeyBlockRecipe": true,
    "generateHoneyBlock": true,
    "effects": []
}
```

Could it be that the display in the Beepedia is broken maybe?

**Comment by MaxNeedsSnacks** [comment]
Got the following feedback from one of our testers:

![image](https://user-images.githubusercontent.com/12750501/144342666-22c1d224-2ef8-4cfc-85e8-4c77e1c4a687.png)

It seems the Beepedia just... doesn't display saturation correctly for some honeys for whatever reason(?) because all of these values match the ones I expected based on the JSON files

**Comment by Vaerys-Dawn** [comment]
testing with apple skin installed shows that it's probably the beepedia that's wrong, I'll close this and see about fixing it on our end

**Comment by Vaerys-Dawn** [comment]
actually, it seems that the way we handle adding saturation for the beepedia is different to how saturation with foods are normally calculated

**Comment by Vaerys-Dawn** [comment]
this is going to need some testing and thought put to it

**Comment by Vaerys-Dawn** [comment]
okay, so saturation is a modifier

```Java
int foodLevel = 20
int nutrition;
float saturationLevel = 5.0F
float saturationModifier;

this.saturationLevel = Math.min(this.saturationLevel + (float) nutrition * saturationModifier * 2.0F, (float)this.foodLevel);
```
say we use steak as an example
`COOKED_BEEF = (new Food.Builder()).nutrition(8).saturationMod(0.8F).meat().build();`
5 + 8 * 0.8 * 2 =17.8
![image](https://user-images.githubusercontent.com/5305116/144543927-9e6d6266-b5aa-403b-8a8a-586fb7eb076b.png)

a golden apple for example
`GOLDEN_APPLE = (new Food.Builder()).nutrition(4).saturationMod(1.2F)`
5 + 4 * 1.2 * 2 = 14.6
![image](https://user-images.githubusercontent.com/5305116/144543920-f75b9284-b4c5-4f67-b32e-59a8ef29d8b8.png)

golden carrots which have a really high saturation looks like this
`GOLDEN_CARROT = (new Food.Builder()).nutrition(6).saturationMod(1.2F).build();`
5 + 6 * 1.2 * 2 = 19.4
![image](https://user-images.githubusercontent.com/5305116/144544090-d69109c1-8b52-435f-92b7-2cf13aee5648.png)

so using the example aluminum honey we get
5 + 3 * 1 * 2 = 11
![image](https://user-images.githubusercontent.com/5305116/144544181-fd7605a4-6685-46df-bc85-50fcea0fb515.png)

but looking at catnip honey we get
5 + 8 * 0.9 * 2 = 19.4
![image](https://user-images.githubusercontent.com/5305116/144544357-e0210380-fd20-42c1-ad09-28c131eb35c9.png)

The same as golden carrots

The problem is that the beepedia actually shows this properly (to some degree)
![image](https://user-images.githubusercontent.com/5305116/144544389-24a2be44-9e6e-4d67-baf5-5fdb09860150.png)

**Comment by Vaerys-Dawn** [comment]
wait... i think i know what's actually gone wrong here

it's showing the modifier as an amount out of 1

but it should be showing the calculated saturation...

**Comment by Vaerys-Dawn** [comment]
should be able to fix this in the next patch

😩

**Comment by Vaerys-Dawn** [comment]
and finally figured it out, so hopefully the amount of saturation displayed will now be accurate...

**Comment by Raidobw2** [comment]
Thank you very much!😄
