### ISSUE TITLE
Gateways To Eternity

### ISSUE THREAD

**Issue by Kopassium** [FTBTeam/FTB-Modpack-Issues#4051]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Describe the bug

None of the medium pearls have a crafting recipe and trying to use the crafting recipe found online, for example 8 blaze rods surrounding an eye of ender, creates an Errored Gate Pearl.

### Steps to reproduce

1. Open crafting panel.
2. Try to create a medium sized pearl i.e. 8 rotten flesh surrounding 1 eye of ender.
3. Get Errored Gate Pearl.

### Expected behaviour

Get regular Gate Pearl.

**Comment by DinnerBeef** [comment]
https://github.com/Shadows-of-Fire/GatewaysToEternity/issues/33. Mod dev is redoing how those work. I will hide them from JEI in the meantime.
