### ISSUE TITLE
Exception when trying enter in lan

### ISSUE THREAD

**Issue by Gemsanches** [FTBTeam/FTB-Modpack-Issues#4053]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Describe the bug

This exception `Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: ItemStackIngrediens cannot be created using the empty ingredient` is occurring when trying to join lan. The message "player joined the game" appears but the connection is lost shortly after. There are two newly installed instances, without modifications. New world, newly created.

Did not find reference to the specific exception in any log. The problem occurs try connecting from computer A to B and B to A.

In a quick test, notice it also happens in version 1.0.1 of modpack. Haven't try 1.0.0.

### Steps to reproduce

1. Create a instance with the modpack in two computers
2. Create a new world (standard configurations)
3. Open the world to lan
4. In the other computer, try to enter the world via lan multiplayer

### Expected behaviour

The exception will occur before the world loads

### Screenshots

![Screenshot_3](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/70922080/7565ed5b-4f8c-418d-803f-e1e556fc2322)

**Comment by basserex** [comment]
I just had the same problem with my brother, he had optifine installed, when he removed that i could join just fine.

**Comment by Gemsanches** [comment]
> I just had the same problem with my brother, he had optifine installed, when he removed that i could join just fine.

Unfortunately this is not my case. Both computers have a pure modpack installation, without optifine or any other mod outside the standard list.

But thank you for presenting what solved it for you.

**Comment by Gemsanches** [comment]
I made an update in one of the computers and had to format it. The connection is working now.

Unfortunately I not be able to specify what was the problem, since I no longer can simulate it.

I'll close the issue.
