### ISSUE TITLE
Refined Storage Controller Issues

### ISSUE THREAD

**Issue by Kopassium** [FTBTeam/FTB-Modpack-Issues#4054]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Describe the bug

I'm not sure about this one, so I'm not playing on a multiplayer server I just open the pack through the FTB program. In my main save whenever I close out of MC and I open it again the Refined Storage Controller disconnects from several devices that it's connected to through Refined Storage Cables. This includes the cables themselves, as the cable count goes down when you right click the controller, exporters, importers, etc. I think it's everything outside the chunk that the controller itself resides in but I'm not sure. It's happened more the once the first time I broke all the cables and wired everything back up, everything started working again. The second time I broke the controller itself and placed it back and it worked just fine it recognized everything. I'm not sure how to described recreating the issue, I went onto a superflat world and tried doing it, closing out MC and coming back on with cables going to devices outside the main chunk and everything still worked. So I don't know.

### Steps to reproduce

1. I'm not sure.
2. Read bug description.

### Expected behavior

I'm unsure of what this box is asking. If it's asking expectant bug behavior, I expect the refined storage controller to disconnect from anything outside the chunk that it resides in. If this box is asking expectant normal behavior, then I expect the refined storage controller to stay connected to whatever refined storage devices I connect it to through refined storage cables whether they go through chunk boundaries or not.

**Comment by DinnerBeef** [comment]
Are you chunk loading anything? That could be an issue if your base is very big and everything is not loaded in yet

**Comment by Kopassium** [comment]
Yes I do have chunk loading enabled but the storage system is contained within 2 chunks. I'll try disabling the chunk loading and see what that does didn't think that would be the issue. I'll update when I can try this.

**Comment by Kopassium** [comment]
I didn't intend to close the issue.
