### ISSUE TITLE
Backpack Disappears

### ISSUE THREAD

**Issue by Lockhart3195GC** [FTBTeam/FTB-Modpack-Issues#4056]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Describe the bug

When I shift-click my backpack into the curios slot and then hit middle mouse on the backpack in the slot it disappears. It is not on the ground. it is not in my inventory, it is not in a chest, it is gone from the game. I've been able to recreate this 3 times now with other backpacks. I tested to see if it may have been another keybind but even after unbinding all keys other than sort inventory it disappears still

### Steps to reproduce

1. open inventory
2. shift click a sophisticated backpack into the back slot of curios
3. middle mouse click the backpack while in the slot
4. backpack disappears from game

### Expected behaviour

backpack is gone from game with everything inside it

**Comment by DinnerBeef** [comment]
I am unable to reproduce. Could you send a video, so I can try to reproduce it the same way you are doing it?
