### ISSUE TITLE
Unify Honey

### ISSUE THREAD

**Issue by gman4161** [FTBTeam/FTB-Modpack-Issues#4057]
### Modpack

FTB Presents Direwolf20 1.20

### Is your suggestion related to a problem? Please describe.

Create honey comb mixer recipe creates prod. bees honey, but emptying honey bottles in a create drain gives create honey. this makes it impossible (annoying at the very least) to empty honey bottles and process combs into the same storage.

**Comment by DinnerBeef** [comment]
Thanks for suggestion. However, at this time we will need to be unifying honey, as everything can still be crafted even though you might to do something a different way.
