### ISSUE TITLE
Direwolf20 1.20.1.1.0 crash on startup

### ISSUE THREAD

**Issue by reformedpuma** [FTBTeam/FTB-Modpack-Issues#4059]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Describe the bug

game will try to start and load up and keep getting the same thing of Java.io.IOexception for my crash 

### Steps to reproduce

1. Go To Direwolf20 1.20.1.1.0 pack
2. Click Play
3. Crash report pops up

### Expected behaviour

want to be able to load and play the game

### Screenshots

![IMG_3654](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/148089855/c9cc060f-3853-455f-8394-5779cd2c409b)

**Comment by handoo123** [comment]
I am having the same issue with Direwolf 20 1.20 but I am on Mac. Any suggestions?

**Comment by reformedpuma** [comment]
Im on windows. But there was a file that didnt download so i had to take the url from the debug and download it and add it to where it needed to go myself and now it works

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
