### ISSUE TITLE
Cannot Craft Dark Steel Using EnderIO's Powdered Coal

### ISSUE THREAD

**Issue by JustANormalHooman** [FTBTeam/FTB-Modpack-Issues#4062]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Describe the bug

If you create EnderIO's Powdered Coal using the method involving coal in mainhand and flint in offhand shift-clicked on obsidian you get EnderIO's Powdered Coal, you are not able to use the Powdered Coal in the Dark Steel recipe, as that calls for Mekanism's Coal Dust.

### Steps to reproduce

1. Create EnderIO Powdered Coal using the recipe that is explained in JEI that involves shift-clicking obsidian with coal and flint
2. Be unable to use said Powdered Coal in Dark Steel.

### Expected behaviour

Powdered Coal should be able to make Dark Steel.

**Comment by DinnerBeef** [comment]
Unable to reproduce it. Even though the recipe in JEI says it only uses coal dust.
