### ISSUE TITLE
keep getting a error saying" error installing modpack"

### ISSUE THREAD

**Issue by killerrose213** [FTBTeam/FTB-Modpack-Issues#4064]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Log Files

[installer.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/12953683/installer.log)

### Describe the bug

it won't let me back into the game. it would saying reinstall but then the error pops up. 

### Steps to reproduce

I went to the app like regular then it told me to just reinstall it but then this error just keeps popping up. I already uninstalled it and then reinstalled it but it's not working. 

### Expected behaviour

thought i would be able to get into the game again.

### Screenshots

![error on abe pack](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/148282396/6e7161aa-fe09-43ad-ba78-e946486063ac)

### Additional information

the first time I tried it.it was fine but then the second time is when it said to reinstalled it then the error.

**Comment by DMIL421** [comment]
Double Check that you are installing the right modpack. Your screenshot shows a different FTB pack.

**Comment by killerrose213** [comment]
I downloaded it from this website 

https://www.feed-the-beast.com/ftb-app

It worked the first time but then second time it gives me a error.

**Comment by DinnerBeef** [comment]
This looks like an app issue and not and Pack issue. Please open and issue here https://github.com/FTBTeam/FTB-App/issues if you still have issues.
