### ISSUE TITLE
Mining Gadget loses 3x3 upgrade after update

### ISSUE THREAD

**Issue by bob-anthony** [FTBTeam/FTB-Modpack-Issues#4065]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

Mining Gadget loses the 3x3 upgrade, but retains other upgrades after updating to 1.2.0. 

### Steps to reproduce

Mining Gadget MK3 in player inventory with the following upgrades installed
- Fortune, Tier 3
- Efficiency, Tier 5
- Range, Tier 2
- Battery, Tier 3
- Light Placer
- 3x3

Update the modpack from v1.1.0 to v1.2.0

### Expected behaviour

All upgrades are retained

**Comment by robertm1771** [comment]
Confirm device still has 3x3 area in effect but I cant change to 1x1 until I added a 3x3 upgrade back to laser

**Comment by DinnerBeef** [comment]
Sadly, this is a know mod bug. You will have to cheat it in or craft a new one. Things changed when the mod added 5 by 5, and 7 by 7 Upgrades
