### ISSUE TITLE
Iron Jetpack (Platinum recipe missing)

### ISSUE THREAD

**Issue by pwaksman973** [FTBTeam/FTB-Modpack-Issues#4067]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

All recipes related to platinum are missing on JEI
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/78715804/591c3518-5f59-44c1-88c4-05fc88bc1a4c)

### Steps to reproduce

1. Open JEI
2. Search for @Iron
3. look for the Platinum recipe for iron jetpack, one before last

### Expected behaviour

Should have a valid recipe

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/78715804/4763ce38-2992-4bdb-9ef2-61d2f92bbc1b)

**Comment by DinnerBeef** [comment]
This issue has now been fixed! Please reopen this issue if you are still having problems.

**Comment by pwaksman973** [comment]
Ah, should it be working at the current version?

I still see the same recipe with the "forbidden" symbol.

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/78715804/680e3422-4f6c-47c1-b7f3-590cfddea828)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/78715804/cacd33e5-ab4d-4edf-85f7-e93d55ff3343)
