### ISSUE TITLE
GrowthCraft Cheese Press Crashes client on teleport

### ISSUE THREAD

**Issue by WellGramarye** [FTBTeam/FTB-Modpack-Issues#4069]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2

### Log Files

https://pastebin.com/xD42GRu2

### Describe the bug

When teleporting away from an area with a Cheese Press in the world, whether with TPA/Back, or Waystones, to the same dimension, the Client Crashes.

### Steps to reproduce

1. Have cheese press in world
2. Try to teleport away from area
3. Crash

### Expected behaviour

No crashing

### Additional information

Cheese Press might need to be active with Cheese curds in it.

**Comment by LamMods** [comment]
Still an issue in DW20 1.20 1.6.0 and can confirm that removing cheese from the cheese press stops the crashing - crashing seems to be based on the cheese ticking.

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
