### ISSUE TITLE
Mahou Tsukai Mod - Power Consolidation spell won't spawn/create lake

### ISSUE THREAD

**Issue by janraeflores** [FTBTeam/FTB-Modpack-Issues#4071]
### Modpack

FTB Presents AbePack

### Modpack version

1.4.0

### Log Files

[Launch logfile.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13034882/Launch.logfile.txt)
[Ingame logfile.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13034883/Ingame.logfile.txt)

### Describe the bug

I am currently playing around with the Mahou Tsukai mod, specifically trying to use the spell "Power Consolidation" to create/spawn in the lake. After following the correct procedure to make/use the spell and having a good amount of Mahou mana, the spell is placed on the ground, drains a bit of mana, but the lake is never created and the spell on the ground disappears. 

### Steps to reproduce

1. Check I have enough mana (I have ~1900)
2. Stab my self with Mahou Tsukai dagger
3. Place down magic circle using hotkey
4. Create Power Consolidation spell by placing two diamond powder in magic circle
5. Then 1 emerald powder in magic circle
6. Magic circle is complete and spins (looks activated) and mana drains (~300)
7. After ~6 seconds or so, magic circle disappears and no lake is created/spawned in

### Expected behaviour

Complete Power Consolidation spell on ground, mana gets taken while lake is being created. Big black lake now created.

### Screenshots

Mahou dagger used and magic circle placed on floor:
![MagicCircle](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/80787341/2ff294dc-1910-4648-b6c7-7cdbb826e150)

Power Consolidation Spell created and active:
![PowerConsolidationSpell](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/80787341/eadb7c79-c89e-4256-9298-9d9a5308100f)

No lake being created or spawning:
![NoLake](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/80787341/594e60c5-54fc-48a5-8cfa-806b49440b2e)

Spell disappears with no lake created:
![SpellDisappear](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/80787341/0e15cba0-7dea-479d-82fa-ac46c8f7a8d1)

### Additional information

This lake should be spawned in after the spell is complete:
![PowerConsolidationLake](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/80787341/f6c57214-0b90-497b-82a1-ae59ff3cad40)

**Comment by Gaz492** [comment]
This looks to have been fixed in the latest version of the pack, if its still an issue do let us know!
