### ISSUE TITLE
tropicraft causes server to crash

### ISSUE THREAD

**Issue by Erabior** [FTBTeam/FTB-Modpack-Issues#4072]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.20

### Describe the bug

Apparently, there is a crash upon tree growth with tropicraft trees that causes a null exception

### Steps to reproduce

have a server running the modpack.
grow the tree from tropicraft
should produce the crash

### Expected behaviour

The game would ideally not crash

### Additional information

This is a known issue on the tropicraft github but I'm not sure what to do with my server in the meantime as I tried removing the mod and that stops the server from loading. I also tried deleting the tropicraft dimension but I am still unable to load the server.

**Comment by DinnerBeef** [comment]
This looks like the same issue as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4086
