### ISSUE TITLE
Zombies give 1 NBT tag to items they pick up

### ISSUE THREAD

**Issue by Wertyus23** [FTBTeam/FTB-Modpack-Issues#4073]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

When zombies (maybe other mobs) pick up items, they give the item some nbt data. Therefore, said item (ie:Rotten Flesh) cannot be stacked with other of the same type.

### Steps to reproduce

1. Use the command /summon minecraft:zombie ~ ~ ~ {CanPickUpLoot: 1b} to summon a zombie that can pick items.
    or
    Find a zombie that picks items in the wild
2. Give the zombie any stackable item.
3. Kill the zombie to get the item back.
4. The drop item will now have 1 NBT tag

### Expected behaviour

When zombies drop items they picked up, they should NOT have additional NBT data.

### Screenshots

![Step_1_Summoning zombie](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/148408775/d39220eb-5c48-4abf-8dd3-892bb0a2a16a)
![Step_2_Giving stackable item](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/148408775/88ce08c7-10b0-4ba2-b8f6-b46b40bb8ee8)
![Step_3_Zombie holding item](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/148408775/154c9dc5-b48f-4a5c-b901-e4ed292a6514)
![Step_4_The dropped item now has an NBT tag](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/148408775/c1cff802-b55f-48b5-90b6-b63c28236179)

**Comment by DinnerBeef** [comment]
Thanks for reporting and issue, However this is working as indeed and will not be fixed. This is to do a mod in the pack that respawns baby zombies holding items
