### ISSUE TITLE
Multiple Enchanting reapie conflicts

### ISSUE THREAD

**Issue by NJM1564** [FTBTeam/FTB-Modpack-Issues#4074]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

When trying to use ender io's enchanter multiple aspires all use the same materials. 
Riptied, Impaling, Piercing, and sweeping edge all use the same materials.
Note: The same materials for different tiers is expected behavior. They are differentiated by the amount of materials used. IE. Riptied 2 used more iron than riptied 1.
And I suspect that the problem occurred because there are new enchantments since the last version EIO was released.
A quick look through the enchanter's recipes indicates that this looks like it's the only error there.

Might I suggest using:
Copper for impaling
Arrows for piercing
And Different tiers of swords as the ingredient for sweeping edge? Wood, stone, gold

### Steps to reproduce

Goto enchanter Look at resapie lists that use Iron see that there are several entries for it.

### Expected behaviour

Sepert reapies for the  diferant types of enchanted books.

**Comment by inuyashagodofall** [comment]
Found the same issue in my session today.

**Comment by DinnerBeef** [comment]
https://github.com/Team-EnderIO/EnderIO/issues/358
The issue has been reported to the mod dev. The mod will be updated if the issue is resolved.
