### ISSUE TITLE
EnderIO powered spawner's progress jumps to -300%

### ISSUE THREAD

**Issue by saladass419** [FTBTeam/FTB-Modpack-Issues#4077]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.20

### Describe the bug

The first few mob spawns are okay, then suddenly after a spawn, it doesn't reset to 0, instead it goes to -300% and starts from there, which takes a lot of time. Using an octadic capacitor, there is plenty of power supplied to it.

### Steps to reproduce

1. Craft powered spawner with Iron Golems.
2. Place it, give it power and a capacitor
3. wait for a few spawns to happen
4. -300%

### Expected behaviour

For it to reset back to zero.

### Screenshots

![Screenshot (49)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83832648/91b609a7-0df6-4a81-93b6-16cd8de5b7bc)

### Additional information

Sometimes it works fine after a while, then it goes to -300 again

**Comment by DGHades** [comment]
This exact Bug seems to exist in ATM 9  Version 0.2.21 too, i just ran into it.

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by saladass419** [comment]
Well, I switched to apotheosis spawners after a while so I don't know if it's still an issue.
