### ISSUE TITLE
Industrial Foregoing missing gear recipes

### ISSUE THREAD

**Issue by RoyalReject** [FTBTeam/FTB-Modpack-Issues#4078]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

Industrial Foregoing is missing its Iron and Gold gear recipe.

### Steps to reproduce

Search @industrial gear in jei, only diamond gear shows up.

### Expected behaviour

Have gold and Iron gear recipes

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/32550284/af081d10-5202-4ab7-9815-4ebcd18f32ae)

**Comment by destinatech** [comment]
The IG iron/gold gears being hidden is likely expected because Almost Unified is in the pack.

Are you seeing recipes from IG where the higher-precedence iron/gold gears from Railcraft aren't working?

**Comment by Industrial** [comment]
> Search @Industrial gear in jei, only diamond gear shows up.

Industrial found you :P

**Comment by RoyalReject** [comment]
I see the gears from railcraft but don't see why I would have to get into brass or bronze when base industrial foregoing has gears that don't need any extra materials/steps

**Comment by DinnerBeef** [comment]
It was based on what mod has more gears in it. Anyway you don't need to go down create to craft brass in this pack. Its just 3 copper and 1 tin.
