### ISSUE TITLE
Blocks can remove graves when right clicked.

### ISSUE THREAD

**Issue by AhKeelU** [FTBTeam/FTB-Modpack-Issues#4079]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2

### Describe the bug

Some blocks have the ability to be placed over a grave removing the grave without it dropping items. I am not sure which only that I died while fighting an end guardian, had a random block, right clicked the grave and received no items then died again and gave up trying.

### Steps to reproduce

1. Die
2. Return to grave with blocks
3. Right click grave with offending block.

### Expected behaviour

Items from the grave to be returned to my inventory.

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
