### ISSUE TITLE
[Bug]: Unable to make brass for the Create mod (FTB Ultimate Anniversary 1.0.2)

### ISSUE THREAD

**Issue by Electrofried** [FTBTeam/FTB-Modpack-Issues#408]
### Modpack

FTB Ultimate Anniversary Edition

### Modpack version

1.0.2

### Describe the bug

Brass is uncraftable.

### Steps to reproduce

Go to JEI
Look at Brass
There is no recipe for the ingot, dust, etc.
Brass plates are required for the create mod.

### Expected behaviour

To be able to make brass somehow. Preferably in all the different style alloy furnaces, though even just the create mixer being able to craft would be good.

**Comment by LatvianModder** [comment]
Fixed in 1.0.3
