### ISSUE TITLE
Some productive bees not producing

### ISSUE THREAD

**Issue by omgz92** [FTBTeam/FTB-Modpack-Issues#4080]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

With seemingly random bees in the Productive Bees mod, they just do not produce combs sometimes. I had a Ghostly bee set up in an advanced hive surrounded by soul sand and it did not produce any combs. I added a second Ghostly bee to the hive and that one worked as intended. I have a farm of metal bees and most seem to work, however I have an advanced beehive with 3 Aluminum bees with an Aluminum Storage block in front of it, and they do not pollinate or produce combs. Also, I have an Invar bee in an advanced beehive with an invar block in front of it, and it also does not pollinate or produce combs. Not sure if it's a random issue or these specific bees. All of the other metal bees with this setup produce combs as intended. I ensured all blocks required to pollinate are correct.

### Steps to reproduce

1. Add ghostly/aluminum/invar bee to advanced beehive.
2. Place appropriate pollinating block around the beehive.
3. Bees will not pollinate or produce combs.

### Expected behaviour

Bees should produce combs when they have access to the appropriate pollinating block.

**Comment by NoFriendsMate** [comment]
I am also having trouble with osmium (eventually got one to work), nickel, and the bees listed above. Maybe its because we aren't on the most recent update?

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by scootmando** [comment]
I am having same problem with Grave's bee as well. Have grave at footing of advanced hove like normal and adult grave's bees in hive with simulator been 2 days afking and nothing. They use to work in an earlier patch

**Comment by RedDamer** [comment]
Hey I know bot said this is closed, but, I am having the same issues. Specifically the Aluminum bee, and the Nickel bee, as the Nickel block from Thermal actually has no crafting recipe, as Railcraft Reborn takes over, and the Nickel bee does not view the RR nickel block as a valid pollinator. Not sure why the Aluminum bee doesn't produce comb though.

**Comment by gbeans44** [comment]
I am also having this issue with the Starry Bees. I have star blocks infront of them and removed the simulation upgrade but they still don't produce.

**Comment by SavageSki13** [comment]
3 years later now and still the same issue with no fix???
