### ISSUE TITLE
KubeJS (kubejs) encountered an error during the complete event phase java.lang.RuntimeException: There were KubeJS startup script syntax errors

### ISSUE THREAD

**Issue by jonharn** [FTBTeam/FTB-Modpack-Issues#4081]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Log Files

Server Boot log: https://mcpaste.io/42741b1d06a51bc4
MC Paste for KubeJS: https://mcpaste.io/178acfb59c0b721d

### Describe the bug

When i updated the modpack to the latest version, it crashed and gave me an error of 
`Failure message: KubeJS (kubejs) encountered an error during the complete event phase
java.lang.RuntimeException: There were KubeJS startup script syntax errors! See logs/kubejs/startup.log for more info`

### Steps to reproduce

1. Boot server 
2. Wait for it to crash
3. Observe crash 

### Expected behaviour

I expect the server to boot fine 

### Additional information

I downgraded my server to the previous version and it worked fine, so its something with the new version.

**Comment by DinnerBeef** [comment]
Try deleting the KubeJS folder and reupdating the pack

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
