### ISSUE TITLE
Cyclic Crafting Machine: Infinite honey!

### ISSUE THREAD

**Issue by Horcrux94** [FTBTeam/FTB-Modpack-Issues#4084]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

When configuring the Cyclic Crafting Machine to create a Honey Block using 4 bottles of honey, having only 2 stacked honey bottles in the input allows the recipe to complete and doesn't consume the ingredients.

### Steps to reproduce

1. Place Cyclic's Crafting Machine and give it power
2. Make sure the Crafting Machine is in "Always On" redstone mode
3. Configure recipe as follows: 
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/123459113/c2880cd4-2a1d-4837-85d5-966579882b54)
4. Add 2 Honey Bottles (stacked) to the left hand side of the UI
5. ???
6. Profit

### Expected behaviour

Craft should not be allowed to complete

### Screenshots

Initial configuration:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/123459113/fba95679-002b-47a3-82d7-ccc86994b751)

After adding 2 stacked bottles of honey...
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/123459113/4e145f29-a751-43b8-9180-a77813b7fadc)

**Comment by DinnerBeef** [comment]
This item has since been disabled from the pack, as such, I will be closing this issue.
