### ISSUE TITLE
DW20 1.1.0 Dimension Builder Crashes game on Completion in Void World

### ISSUE THREAD

**Issue by Binomialgeoduck** [FTBTeam/FTB-Modpack-Issues#4085]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.0

### Log Files

[crash-2023-10-22_08.56.16-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13062782/crash-2023-10-22_08.56.16-server.txt)

### Describe the bug

When fully realizing a dimension tab in the dimension builder, gets to 99%, then crashes game/server on 100% completion. When boot up, dimension tab is invalid. Retried with 9 attempts, 9 fails.

### Steps to reproduce

Go to Void World
Place dimension tab into dimension builder.
Wait till it hits 99%
Game crashes
Rinse, and repeat

### Expected behaviour

I expect to dimension builder to not crash on completion.

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
