### ISSUE TITLE
Can't export Refined Storage Fluids

### ISSUE THREAD

**Issue by SnappyFrog** [FTBTeam/FTB-Modpack-Issues#4087]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

Refined Storage exporter doesn't recognize fluids.  Fluids are not selectable and the refined storage exporter doesn't turn green.  Items work just fine.

### Steps to reproduce

Save fluids to refined storage fluid disk via endertank and importer set to fluid.
Fluids visible on Fluid Monitor
create exporter and connect to valid machine/tank
Set to fluid and try to pull over any fluid to exporter.

### Expected behaviour

When mousing over a fluid in JEI when exporter is set to fluid, the exporter will go green and allow you to pull over the selected fluid into one of the exported boxes.

**Comment by DinnerBeef** [comment]
Wait so is the issue that you can't just pull from JEI for fluids or is the issue that it won't export fluids at all
