### ISSUE TITLE
Fatal exception has occurred when downloading on ftb app

### ISSUE THREAD

**Issue by lbraswe1** [FTBTeam/FTB-Modpack-Issues#4089]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.13.1

### Describe the bug

Pack will not install

### Steps to reproduce

go to download the pack
hit install
Will prepare the instance and instantly give the error when preparing the instance

### Expected behaviour

Pack is intalled

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/148716592/344b1b7f-8574-4db6-a048-4c4f7ce8b3af)

**Comment by Gaz492** [comment]
Does this still happen with the lastest version of the FTB App and latest version of the modpack?
