### ISSUE TITLE
Modpack is crashing

### ISSUE THREAD

**Issue by Cazzykat** [FTBTeam/FTB-Modpack-Issues#4090]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.22.0 (and the last three versions after that)

### Log Files

[hs_err_pid16124.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13064869/hs_err_pid16124.log)

### Describe the bug

I can run the modpack just fine it loads on the FTB app and it'll open Minecraft but anytime I try and actually start a world it crashes before I load in. I've tried to download an older version of it and it doesn't fix the issue. I can run other modpacks just fine so it only seems to be FTB StoneBlock two. I can play it just fine on the curse forge app so i know it shouldn't be an issue with my computer. I made sure it had the latest version of Java also so that isn't the issue.

### Steps to reproduce

Start the modpack, enter Minecraft, make new world. 

### Expected behaviour

I expected to be able to start a world and play it.

**Comment by Gaz492** [comment]
Im not able to replicate this issue, can you confirm this is still an issue for you with a clean install of the modpack?
