### ISSUE TITLE
Mining gadget unable to change number of blocks to mine

### ISSUE THREAD

**Issue by Enreva** [FTBTeam/FTB-Modpack-Issues#4092]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

After upgrading the modpack to 1.2.0 I was unable to change the mining size from 1x1 to 3x3, or from 3x3 to 1x1 depending which size you were using when upgraded. The option is grayed out and the 3x3 upgrade is not in the gadget. Changed the version of Mining gadgets mod to the previous release (1.15.3) and worked as used to. Returned to the pack mod version (1.15.4) keeping the 3x3 upgrade in my own inventory and it "dissapeared". In the newer version of the mod (1.15.5) the upgrade is there, but does not allow to change the size between 1x1 and 3x3 although it is usable to craft the 5x5 upgrade and then everything works as expected

### Steps to reproduce

Install a pack version previous to 1.2.0
Craft the 3x3 size upgrade of the mining gadget
upgrade to pack version 1.2.0
The upgrade is not there

### Expected behaviour

To keep the upgrade and its functionality when upgrading, or converting if that is what is needed

**Comment by DinnerBeef** [comment]
Know mod bug. Will have to craft a new one. They changed the item ID when they added the other upgrades.
