### ISSUE TITLE
minign gadgets 5x5 and 7x7 upgrades

### ISSUE THREAD

**Issue by Enreva** [FTBTeam/FTB-Modpack-Issues#4093]
### Modpack

FTB Presents Direwolf20 1.20

### Is your suggestion related to a problem? Please describe.

Mining gadgets

### Mod suggestion

Can the 5x5 and 7x7 can not be centered on the square they are mining but in the second block (from ground to ceiling) so you can mine in a straight line? (in the 5x5 would be 1 block below the one you are  pointing to, the block you are pointing to and 3 above that one). Or that this could be an option (an offset value)?

**Comment by Kadah** [comment]
Likely should be a feature request on Mining Gadgets instead of the pack.

https://github.com/Direwolf20-MC/MiningGadgets/issues

**Comment by Enreva** [comment]
Sorry, you are totally right.

**Comment by DinnerBeef** [comment]
Yea, there is a setting in the mining gadget you can change. It should be the button below the size option.
