### ISSUE TITLE
AE2 terminals(universal also) lose half their power on use on a server

### ISSUE THREAD

**Issue by gman4161** [FTBTeam/FTB-Modpack-Issues#4096]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

The Universal Wireless terminal (with crafting T, pattern encoding T, and pattern access T) from AE2WTLib stores 4.8 million AE(intended), but upon opening said terminal, it halves the AE stored(to 2.4M AE). 
[update] it just didn't do it for a bit after. still broken

~~(5 minutes of config checking later) I fixed it. The issue seemed to come from the client.json config files. My client and server were not the same. However, the only difference was the "terminalStyle" config. The server's was "full" and my client's was "tall". How THIS config caused the terminals to lose half their power still confuses me, but I thought I'd report this to ensure server files and client files are updated together or so other people could find the fix.~~

### Steps to reproduce

1. I have 0 clue
~~1. launch server and client~~
~~2. change the server's ae2 config client.json "terminalStyle" setting to "full"~~
~~3. change the same file and setting for the client's config but set it to "tall"~~
~~4. your terminals should now lose half their power for no reason~~

### Expected behaviour

terminal shouldn't lose 1/2 its power
~~or one config should overwrite the other without issues~~

### Additional information

~~I suppose this would be a bug for AE2 authors. It did this for both universal terminals and ae2 terminals and was always exactly 1/2 of the power capacity.~~

**Comment by gman4161** [comment]
Never mind, it's still doing it. Just didn't happen for a bit after I changed configs. this is still broken

**Comment by Dracos99** [comment]
I have seen this same interaction with the Wireless Crafting Terminal directly from AE2.
The steps to reproduce:
1. Charge Wireless Crafting Terminal
2. Connect it to the AE2 Network
3. Open terminal and place a Quantum Bridge card into the slot (this does not trigger the problem)
4. Place a Quantum Entangled Singularity into the slot for it
5. Place the other matched Singularity into the Quantum Bridge on the network
6. every time you open the terminal after this is done, the power goes from 1.6M ae to 800k and then continues to drop like normal...if you recharge past 800k, it will drop back down immediately on next open

This is especially painful if you have wireless charging...you get an up to 800k penalty each time you use your terminal

**Comment by 9bananas** [comment]
Since i didn't see anything in the release notes, or in the issues, i reported the bug over at AE2:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7473#issue-1995662152

hope this gets fixed, it's a very annoying bug....

**Comment by Dracos99** [comment]
Thanks for the quick solution. Intended but not expected behavior...I would expect it to short out or not open with a message. Someone should also clue Dire in on this as i believe he has been struggling with power his whole playthrough and this could be a major contributor.

**Comment by 9bananas** [comment]
yeah, this behavior is pretty much impossible to guess at and completely unexpected from a user perspective.

nothing about the mod or the descriptions provided indicates that the charge level of the terminal is in any way related to the AE stored in the ae2 network...and like you said, there's no message about it either.

instead, the terminal is described and presented as a standalone unit of the network, and should therefore have indepenent power.

i should probably open an issue over at ae2wtlib, since i havven't seen it mentioned when i searched for a solution to this behavior...

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by 9bananas** [comment]
in a quick test on version 1.10.0, the issue seems resolved:

created a simple ME network with a quantum ring without any AE storage attached, connected a universal terminal via wireless access point, and the wireless terminal didn't immediately drain charge.

seems good!
