### ISSUE TITLE
FTB Skies : Hexerei Witch armor crash

### ISSUE THREAD

**Issue by Calaheim** [FTBTeam/FTB-Modpack-Issues#4097]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Log Files

https://mclo.gs/IMUr4dX latest Log.
https://mclo.gs/2zcGh8O 

### Describe the bug

Game crashes to desktop when near Witches

### Steps to reproduce

1. Load game
2. Enter hostile mob farm
3. Crash because of witch.
4. Enjoy your desktop background.

### Expected behaviour

Game just working. 

### Additional information

Entity witch is responsible? perhaps because im wearing witch armor. 
Crash solved when not wearing witch armor. 

Solution update hexerei to latest version

**Comment by Saereth** [comment]
this should be fixed in the update but if you ever run into this with any mod in the future go into your world save /serverconfigs/forge-server.toml and change remove erroring enttites to true
