### ISSUE TITLE
Industrial Foregoing Dissolution Chamber cannot accept inventory when inputs locked (fixed upstream)

### ISSUE THREAD

**Issue by Kadah** [FTBTeam/FTB-Modpack-Issues#4098]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

Bug reported on Industrial Foregoing and fixed upstream.

https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1366

### Steps to reproduce

1. Set Dissolution Chamber inputs and lock
2. Try to insert items >1 at a time, ie not with a vanilla hoppers methods

### Expected behaviour

Items can be inserted

### Additional information

Update Titanium to fix Industrial-Foregoing bug #1366

**Comment by Kadah** [comment]
Unfortunately there appears to be no change for this bug by the fix to Titanium. Will keep tracking upstream issue.

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by Kadah** [comment]
AFAIK, the bug has not been fixed upstream yet.
