### ISSUE TITLE
RFToolsUtility Modules Unable to Craft

### ISSUE THREAD

**Issue by DanielOlker** [FTBTeam/FTB-Modpack-Issues#4099]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

Following the JEI recipes (and confirming against recipes listed in the relevant wiki and the in game "Information Guide" book) it is impossible to craft and of the positive modules or moduleplus for the environmental controller. 

To test this bug further the recipes were placed into the RFTools crafter and it was unable to recognize the setups as a valid recipe. 

### Steps to reproduce

1. Place the items in a crafting bench or workbench of any variety in the pattern to craft a module.
2. No output will be detected as available to be selected and grabbed. 

### Expected behaviour

The modules and moduleplus variants should be craft-able using their specified recipes. 

### Screenshots

Selecting the feather falling module recipe in JEI
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/40639362/ea2b8a91-8371-4db9-b111-cc41e0b6a876)
Attempting to craft the module in the AE2 wireless crafting module
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/40639362/083f0ccd-cb91-47a0-96ad-8c813498aa1f)
Selecting the saturation module recipe in JEI
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/40639362/250a3d89-3f04-4cd4-ae40-db548c16f33a)
Attempting to craft the module in the AE2 wireless crafting module
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/40639362/4e8a4c16-ddce-484d-925c-d82986216c4c)
Attempting to craft the saturation module in a standard crafting table
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/40639362/2d0a5c36-8a3c-42c4-a2de-434f6b9cd402)

**Comment by DinnerBeef** [comment]
Everything seems to be working fine for me. Are you getting the mob you need in syringe? Each recipe need a different type of mob. All you need to do is hit the mob with the syringe.

**Comment by DanielOlker** [comment]
I understand now where I was making my mistake. However is there any way to prevent the JEI "Move Items" button from grabbing the improper syringes or not showing the items as being available if that specific mob syringe isn't in the inventory?
