### ISSUE TITLE
[Bug] when typing chaos or @draconic in jei game crashes

### ISSUE THREAD

**Issue by vanharen07** [FTBTeam/FTB-Modpack-Issues#41]
### **Modpack**
FTB Oceanblock

### **Modpack version**
1.0.1 and beta 1.1.0

### **Log file**
[2021-09-29-1.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7253298/2021-09-29-1.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7253309/debug.log)

### **Describe the bug**
when typing "chaos" or "@draconic" in JEI game crashes

### **Steps to reproduce**
1. open JEI
2. type "chaos" or "@draconic"
3. game crashes

### **expected behavior**
game shows what I search for in JEI and doesnt crash

**Comment by Sunekaer** [comment]
I'm assuming you have an AMD GPU? if so go the Draconic config and disable shaders.

**Comment by vanharen07** [comment]
I indeed have an AMD GPU. changing the config worked and game no longer crashes. thank you.
