### ISSUE TITLE
[Bug]: Glassential recipe conflict with Prefab

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#410]
### Modpack

FTB University 1.16.5

### Modpack version

1.3.0

### Describe the bug

Glassential's ghostly glass conflicts with, and overrules Prefab's boundary block recipe, making boundary blocks uncraftable.

### Steps to reproduce

![crafting conflicit](https://user-images.githubusercontent.com/77522101/144501642-bcc6b263-e2c0-4e51-87da-6887bc5719ab.png)

### Expected behaviour

recipes to not conflict

**Comment by aaronhowser1** [comment]
Removed the Boundary since it was weird anyway
