### ISSUE TITLE
Rainbow Linker Missing from Iron Furnaces

### ISSUE THREAD

**Issue by WellGramarye** [FTBTeam/FTB-Modpack-Issues#4100]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2

### Describe the bug

Rainbow Linker item used to link all the Iron Furnaces together to power the Rainbow Furnace is missing from the pack. 

### Steps to reproduce

1. Open JEI
2. Type in @Iron Furnaces
3. No Rainbow Linker

### Expected behaviour

Rainbow Linker expected to be able to actually use the modlet.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/58095709/acab1875-a92b-41a2-92d1-afd1b804d46b)

### Additional information

If this was an intentional removal, its a bit of a silly one.

**Comment by volrathstormborn** [comment]
Glad to see it was reported.  Built them all and had the automation setup.  Then realized there is nothing to link with.  Had it in ATM 8, have not played another 1.20.1 pack that has the mod so I cannot say if it is a 1.20.1 issue of the mod or the modpack itself.  Ran through the scripts and kubejs but did not see anything regarding the linker or its recipe.

**Comment by DinnerBeef** [comment]
It seems like the mod changes how it works. There is no rainbow linker in the mod anymore.
