### ISSUE TITLE
RefinedStorage and RebornStorage, on start up, not syncing.

### ISSUE THREAD

**Issue by jadedrock** [FTBTeam/FTB-Modpack-Issues#4101]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

Direwolf20 1.20 1.2.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13110249/latest.log)

### Describe the bug

RefinedStorage and RebornStorage are not syning when I connect to the world. I have a RebornStorage crafting multiblock with 2 computer cores and 2 crafting storage blocks.  When I log into the world, the refinedStorage network does not know anything about the RebornStorage multiblock, any crafting recipe, or or any other RefinedStorage devices connected indirectly through the RebornStorage multiblock.  When I break a RefinedStorage cable connecting to it, it will connect to the network.  Placing a lever, or a block next to the multiblock does not trigger it to connect.

### Steps to reproduce

1. build a RefinedStorage network.
2. Build a RebornStorage multiblock, mine was 3x4
3. Place something like a diskdrive from the RefinedStorage with drives at it at the bottom of the multiblock.  
4. Connect the rest of the RefinedStorage network to the top of the multiblock but not to the Diskdrive.
5. Log out.
6. Log in, and the Diskdrive should be dark, not active, and the RefinedStorage network should not see the craft patterns in the Multiblock.
7. Break a cable to the multiblock.  
8. place a cable back.

### Expected behaviour

The multblock should connect to t the RefinedStorage Network

### Screenshots

![Broken](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20877765/93baceae-7df9-4cc6-a0fb-527761bd3354)
![WorkingAfterCablePlaced](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20877765/07ac2d27-6231-4122-9347-cc69f1178057)

**Comment by DinnerBeef** [comment]
In theory this should be fixed in the next update. Let me know if it still happens
