### ISSUE TITLE
Enchantment Library with Recall enchant crashes when Item Filter is used

### ISSUE THREAD

**Issue by wpetrowski** [FTBTeam/FTB-Modpack-Issues#4102]
### Modpack

FTB Inferno

### Modpack version

1.9.1

### Log Files

https://mclo.gs/4OMM1Vo

### Describe the bug

When an Enchantment Library (from Apotheosis) contains the Recall enchant (from Capsule), then the Item Filter slot in the Enchantment Library becomes unusable.  Placing any item into the Item Filter slot causes the client to crash.

Removing the Recall enchant from the Enchantment Library fixes the issue, and allows the Item Filter slot to work normally again.

### Steps to reproduce

In a creative world:

* Grab an Enchantment Library and an Iron Sword from JEI or wherever.
* The Recall enchant doesn't show up in JEI, so: `/give @p enchanted_book{StoredEnchantments:[{id:"capsule:recall",lvl:1}]}`

Place the Enchantment Library and put the Recall book into the library.  Place the Iron Sword into the Item Filter slot.

### Expected behaviour

No client crash, and the list of enchants in the library filtered to the ones applicable to the item, as usual.

**Comment by Saereth** [comment]
unfortunately it has no blacklist but what I did is add a tooltip to the libraries warning people not to insert that enchant. This is due to it not having a valid item type it can apply to.
