### ISSUE TITLE
better ocean monument crashing server

### ISSUE THREAD

**Issue by Ryinsanity** [FTBTeam/FTB-Modpack-Issues#4103]
### Modpack

FTB Presents AbePack

### Modpack version

1.4.0

### Log Files

https://mclo.gs/TZ27i0Y
https://mclo.gs/AKk4c2S
https://mclo.gs/oekc586

### Describe the bug

Server crashing

### Steps to reproduce

Could be something in ocean monuments crashing the server

### Expected behaviour

NO CRASHES!

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you in the latest version of the pack?
