### ISSUE TITLE
Server crashes on rejoin

### ISSUE THREAD

**Issue by Drakkim** [FTBTeam/FTB-Modpack-Issues#4104]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Log Files

[crash-2023-10-24_19.10.53-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13126350/crash-2023-10-24_19.10.53-server.txt)

### Describe the bug

Whenever I rejoin the server, the client tells me "Server Closed" and the server itself crashes. I can then log in again, but only once.

### Steps to reproduce

1. Disconnect from the server.
2. Reconnect to server.
3. Crash.

### Expected behaviour

Server should survive multiple log ins

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by Drakkim** [comment]
It looks like it was fixed along with [#4367](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4367). Thanks for checking back with me!
