### ISSUE TITLE
FTB Presents Abepack Server version 1.4.0 doesn't match client from install

### ISSUE THREAD

**Issue by BackZlasH** [FTBTeam/FTB-Modpack-Issues#4105]
### Modpack

FTB Presents AbePack

### Modpack version

1.4.0

### Describe the bug

It seems like the modpack for the server installations is not up to date 
After installing a new server and updating my client to 1.4.0 the mods doesn't match up
![image_2023-10-25_125252498](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/94891313/5f2bd11e-36de-4655-ab64-9feb399f8b71)

### Steps to reproduce

install client and server and try it out

### Expected behaviour

i expected them to match from the get go

### Screenshots

![image_2023-10-25_125451145](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/94891313/63d49931-3e6d-4108-914c-1fadd65f26b0)

### Additional information

Im new to reporting things here so hope i did it right

**Comment by UnRealDinnerbone** [comment]
Does this happen on a fresh server / client install?

**Comment by BackZlasH** [comment]
Its a fresh install of the server but not the client i will test it.

**Comment by BackZlasH** [comment]
Upgrading to the new 15 version that just got released worked
