### ISSUE TITLE
Apotheosis is missing

### ISSUE THREAD

**Issue by Nexey** [FTBTeam/FTB-Modpack-Issues#4106]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.0

### Describe the bug

It seems that the mod doesn't load properly on servers.

### Steps to reproduce

1. Launch a server with the 1.2.0 version of the pack and acquire some Apotheosis Gems
2. Update it with v1.3.0 and the Gems will be gone

### Expected behaviour

Apotheosis should be loaded when updating the server

**Comment by Alpvax** [comment]
This also causes a crash for me if I look at certain affix items (IndexOutOfBounds 0 of 0).
All my apotheosis items in my chest have disappeared (gems/materials), as well as all blocks in the world (salvaging table).
However, the mod still seems to have loaded partially, as my mob spawner tooltip is still working correctly.

**Comment by DinnerBeef** [comment]
This issue has now been fixed! Please reopen this issue if you are still having problems.
