### ISSUE TITLE
FTB Presents Direwolf20 1.20 1.3.0 has crashed

### ISSUE THREAD

**Issue by Bolukan** [FTBTeam/FTB-Modpack-Issues#4109]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.0

### Log Files

https://paste.feed-the-beast.com/view/f0feee2f

### Describe the bug

Core reason: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

maybe related to (see log file): dev.shadowsoffire.apotheosis.adventure.loot.RarityRegistry.getMinRarity(RarityRegistry.java:69) ~[Apotheosis-1.20.1-7.0.5.jar%23458!/:7.0.5] {re:classloading}

I got into a little cave, I had a bat flying around or/and a plagued rat
And I saw those purple crystals and maybe touched them for the first time walking there.

### Steps to reproduce

Reload of the saved game, crashes directly.

### Expected behaviour

no crash

### Screenshots

not possible

**Comment by kong009** [comment]
Team,

I am experiencing the same crash on 1.3.0. On both occasions I was simply trying to open my inventory. See attached crash reports.
[crash-2023-10-25_14.03.33-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13169791/crash-2023-10-25_14.03.33-client.txt)
[crash-2023-10-25_14.10.34-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13169792/crash-2023-10-25_14.10.34-client.txt)

**Comment by LandonCalling** [comment]
I am also getting what appears to be the same crash.  Updated to 1.3.0 right before it started happening.  I was searching in my AE2 system when the crash happened.

https://paste.feed-the-beast.com/view/2ac2004e

**Comment by DinnerBeef** [comment]
There should be a fix coming out soon

**Comment by DinnerBeef** [comment]
https://feed-the-beast.com/modpacks/119/changelog/6960
