### ISSUE TITLE
FTB Direwolf20 1.3.0 Crashes

### ISSUE THREAD

**Issue by ThebestSammy** [FTBTeam/FTB-Modpack-Issues#4110]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.0

### Log Files

[crash-2023-10-25_20.18.43-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13169382/crash-2023-10-25_20.18.43-server.txt)
[crash-2023-10-25_20.22.18-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13169383/crash-2023-10-25_20.22.18-server.txt)

### Describe the bug

If you shoot an arrow its bounces back to you or hits the ground the game will instantly crash
if you restart the game and choose the same map it will crash while loading the map

### Steps to reproduce

get a bow 
shoot in it at a mob (i used a Zombie and a Pig)
arrow bounces back
hits the ground or the Player
Game Crashes

### Expected behaviour

Zombie would die /get hurt

### Additional information

I tried using a other bow but it still crashed (both bows where enchanted 1st Bow with: Flame;Power 4;Unbreaking 3
2nd Bow with:Flame;Multibow;Quickshoot
3rd Bow no enchants

**Comment by DinnerBeef** [comment]
Same as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4109
