### ISSUE TITLE
Game crash when using AE2 Crafting panel

### ISSUE THREAD

**Issue by MicrodenNL** [FTBTeam/FTB-Modpack-Issues#4111]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3

### Log Files

[crash-2023-10-25_21.18.01-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13169795/crash-2023-10-25_21.18.01-client.txt)

### Describe the bug

when opening the AE crafting panel search bar the game crash

### Steps to reproduce

opening the AE 2 crafting panel
trying the search bar
game crash

### Expected behaviour

Applied Energistics 2

**Comment by llflory** [comment]
I'm having the same issue, with the same trigger:
1. open AE2 terminal (fixed or wireless)
2. type in anything in the search-bar (was trying netherrack)

From looking into the crash logs, I saw that it was related to the apotheosis mod (seems to be the same issue as #4113, #4112, #4110, #4109.
[crash-2023-10-25_22.48.02-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13170057/crash-2023-10-25_22.48.02-client.txt)
[crash-2023-10-25_22.51.07-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13170058/crash-2023-10-25_22.51.07-client.txt)

**Comment by gman4161** [comment]
+1. also experiencing this

**Comment by DinnerBeef** [comment]
Same as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4109
