### ISSUE TITLE
Direwolf20 1.20 v1.30 Apotheosis Crash

### ISSUE THREAD

**Issue by DizzyDJW** [FTBTeam/FTB-Modpack-Issues#4112]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.30

### Log Files

https://pste.ch/teluxukuru.rb

### Describe the bug

When hovering over ANY Apotheosis-augmented weapon or equipment, the game freezes and crashes.

The weapons and equipment tested with this were all in a Sophisticated Backpack and existed prior to the 1.30 update

### Steps to reproduce

1. Hover the mouse of ANY Apotheosis-augmented weapon or equipment
2. Watch game crash

### Expected behaviour

I EXPECT the game not to crash

**Comment by gman4161** [comment]
It appears it doesn't need to be hovered over if it's in an AE terminal of some sort. That makes it VERY hard to play. LMK if anyone has a fix for this besides rolling back the update.

**Comment by DinnerBeef** [comment]
Same as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4109
