### ISSUE TITLE
FTB Presents Direwolf20 1.20 1.3.0 Apotheosis Inventory Crashes

### ISSUE THREAD

**Issue by mokzwell** [FTBTeam/FTB-Modpack-Issues#4113]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.0

### Log Files

[crash-2023-10-25_15.15.13-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13169837/crash-2023-10-25_15.15.13-client.txt)

### Describe the bug

Apotheosis reforges seem to have been broken with the most recent update. The names are still there (with their relevant rarity) but all stat bonuses from armor and weapons are gone.

When mousing over one of these broken items in my inventory, the game crashes. This seems to be exclusive to tools/items in the primary inventory, as my equipped armor can be hovered with no issues (which is how I realized stats from reforging were broken).

### Steps to reproduce

1. Open inventory
2. Hover over an Apotheosis-reforged item created in a previous version
3. Tooltip for the item will not display and the game should crash

### Expected behaviour

Tooltip for the item should show and item should be able to function normally in the player inventory. No crash expected.

### Additional information

Enchantments on the item seem irrelevant as it was tested on both enchanted and mundane items. All other items in inventory can be hovered normally. As stated above, equipped reforged armor can be hovered with no issues, but the reforge/prefix provides no stat bonuses.

**Comment by mokzwell** [comment]
As an addendum after some further investigation, all apotheosis blocks/items have disappeared from anywhere except the player inventory, including placed blocks.

**Comment by DinnerBeef** [comment]
Same as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4109
