### ISSUE TITLE
Wither Bone from Baubly Heart Canisters doesn't drop

### ISSUE THREAD

**Issue by antisocialian** [FTBTeam/FTB-Modpack-Issues#4114]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.20

### Describe the bug

killing the wither skeleton should have a drop chance of the wither bone. there is no mention of it on jei to get it/craft it.

### Steps to reproduce

find wither skeleton, kill it, notice lack of drops :cry:

### Expected behaviour

BHC config shows it should have a 15% drop rate.

### Screenshots

some screenshots of the jei screen showing what drops from the wither skeleton. 
https://imgur.com/a/14JJ7d7

### Additional information

could also be a drop from the wither boss too, usually don't need many of them to make all the heart containers tho i think.

**Comment by Medivha** [comment]
i have 14 of these so it was dropping for me in 1.2.0. I'm now in 1.3.1 and still can confirm it drops from wither skeletons tested with spawner and looting 8 and scavenger 3
![](https://i.imgur.com/zJO002P.png)
I’m almost sure the egg/MobDrops window doesn't show all drops.

**Comment by antisocialian** [comment]
setup a spawner with max settings killed at least 50 with a test sword with 255 looting and 255 scavenger(chance to roll loot twice) and got 19. 

that's probly enough for one player, just seems a bit lower than i remember.
