### ISSUE TITLE
Hunting mobs causing unexpected crashes

### ISSUE THREAD

**Issue by hitwolf1985** [FTBTeam/FTB-Modpack-Issues#4116]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.0

### Log Files

[crash-2023-10-25_15.20.59-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13170309/crash-2023-10-25_15.20.59-server.txt)

### Describe the bug

Crashed after I was attacking an Enderman.

### Steps to reproduce

I have been able reproduce by attacking another mob

### Expected behaviour

the ability to hunt mobs

**Comment by DinnerBeef** [comment]
Same as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4109
