### ISSUE TITLE
Direwolf 1.20 - 1.3.0 Mod Mismatch

### ISSUE THREAD

**Issue by Shadowstriker0s** [FTBTeam/FTB-Modpack-Issues#4117]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.0

### Log Files

[MClog.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13170586/MClog.txt)

### Describe the bug

Upon joining server get mod mismatch error.

### Steps to reproduce

start server
start client
attempt to connect from multiplayer server broswer

### Expected behaviour

Connect with no error

### Screenshots

![Screenshot 2023-10-25 155935](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/44280285/348c3dd1-5d30-4a13-8d97-55f45db17d6e)

**Comment by DinnerBeef** [comment]
Sane as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4109
