### ISSUE TITLE
Xycraft Extractor Dragon Egg issue

### ISSUE THREAD

**Issue by shank3001** [FTBTeam/FTB-Modpack-Issues#4119]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.20

### Describe the bug

Xycraft Extractor above Dragon Egg or any orientation fails to produce dragon eggs

### Steps to reproduce

1. CraftXycraft Extractor 
2. Place above Dragon Egg or any orientation fails to produce dragon eggs

### Expected behaviour

produce dragon eggs

**Comment by shank3001** [comment]
I figured out the cause of bug. You cannot wrench the extractor to rotate it into position. Wrenching the extractor renders it inert. This is repeatable. . .

**Comment by Kadah** [comment]
Can confirm the behavior that wrench (tested using the YETA one) rotating an extractor in to orientation does not trigger activation for a valid recipe.

**Comment by Aba-sama** [comment]
its working, you must get xycraft extractor under dragon egg

**Comment by shank3001** [comment]
> its working, you must get xycraft extractor under dragon egg

It is working just cannot rotate the extractor in position with a wrench.

**Comment by DinnerBeef** [comment]
Thanks for reporting and issue, However this is working as indeed and will not be fixed.

**Comment by HalJordan** [comment]
I'm glad I found this. The recipe is showing wrong in JEI for the pack I'm in, it has the extractor on top of the egg, with no mention of it having a specific orientation other than what's on screen.

**Comment by becky15675** [comment]
Okay, I got this working. You have to make the dragon egg fall onto the extractor, so from top to bottom - a dragon egg, then the extractor pointing down into a chest/container

**Comment by HalJordan** [comment]
I didn't have to make it fall, I just had to place.. up the extractor on a different block, break the temp block, and plunk the egg on top.

**Comment by abiliomg** [comment]
I'm still having this problem, have tried all the combinations and still didn't work. Can someone show me a pic on this working?

**Comment by becky15675** [comment]
okay, steps:
1: Place down chest
![2024-07-31_07 41 23](https://github.com/user-attachments/assets/0a046f8d-f63a-43ac-921c-90ddc89c4bef)

2: Place a block above the chest with a space between it and the chest.
![2024-07-31_07 41 35](https://github.com/user-attachments/assets/01df8ba9-dcf3-470e-a4c8-c262a056df94)

3: Place the extractor on the underside of the top block so the narrow end points to the chest.
![2024-07-31_07 41 51](https://github.com/user-attachments/assets/dd5a1d08-da0a-449a-b108-036daf173f9d)

4: Break the dirt block above the extractor.
![2024-07-31_07 42 02](https://github.com/user-attachments/assets/e90a5930-428b-4dea-8246-3bd6cba9a9a2)

5: Place dragon egg atop the extractor. If done right, you will see the extractor pulse.
![2024-07-31_07 42 16](https://github.com/user-attachments/assets/9f48e0e6-c35f-4b0f-9a80-075794dc1c0b)

6: After a few seconds, eggs will appear in the chest. Make sure you don't have any redstone signals near the extractor as this will stop it working.
![2024-07-31_07 42 26](https://github.com/user-attachments/assets/af3ecfc6-42ea-4d77-b155-e5da55628210)

![2024-07-31_07 48 53](https://github.com/user-attachments/assets/b7f0d76c-929e-4f3f-99f7-a736f0653c52)

**Comment by HalJordan** [comment]
I pointed this out in december, and it's STILL an issue. The JEI recipe is dead WRONG.

Either change the recipe, or fix how it's showing up.

**Comment by xKOBAYASHIMARUx** [comment]
This is not a closed issue, this is still very much open. The problem is the JEI recipe. It shows the extractor on top of the egg when it needs to be below.

**Comment by HalJordan** [comment]
A year later and not a fucking thing done to fix it.

**Comment by DinnerBeef** [comment]
Please see this for more information https://github.com/Soaryn/XyCraftTracker/issues/35
