### ISSUE TITLE
[Suggestion]: Recipe for Creative Blaze Cake?

### ISSUE THREAD

**Issue by zoller27osu** [FTBTeam/FTB-Modpack-Issues#412]
### Modpack

FTB University 1.16

### Is your suggestion related to a problem? Please describe.

Recipe for Creative Blaze Cake? Preferably not made of any singularities that require Blaze Cakes.

**Comment by aaronhowser1** [comment]
Yeah there's a bunch of creative items that didn't exist when I was making recipes. #353 as well.

**Comment by zoller27osu** [comment]
A recipe for Woot's "Creative Conatus (Dev)" would be cool as well (preferably much cheaper than the Infinite Fluid Tank).

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/145760607-5a66e974-db2a-4e8b-85e1-ad2e1d9b5599.png)
Shadow Steel, Refined Radiance, Blazing Blood singularities, and Magma Cake, Blaze Quartz, and Blazing Archwood Log
