### ISSUE TITLE
Apotheosis gear is missing after upgrading to 1.3.1

### ISSUE THREAD

**Issue by robertm1771** [FTBTeam/FTB-Modpack-Issues#4120]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.1

### Describe the bug

All my armor from Ars with enchants and gems installed was missing

### Steps to reproduce

upgrade from 1.2.0 to 1.3.1 and lost gear I was wearing sword and tools where ok

### Expected behaviour

To have geat I had on in 1.2.0

**Comment by DinnerBeef** [comment]
Did you update to 1.3.0 first?

**Comment by robertm1771** [comment]
Nope like I said upgraded from 1.2 to 1.3.1

**Comment by robertm1771** [comment]
Was Ars gear incase this makes a differance

**Comment by DinnerBeef** [comment]
This issue has now been fixed! Please reopen this issue if you are still having problems.
