### ISSUE TITLE
Ad Astra Hammer is uncraftable

### ISSUE THREAD

**Issue by welch3694** [FTBTeam/FTB-Modpack-Issues#4122]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.1

### Describe the bug

Ad Astra hammer used to be craftable in 1.2.0, but now in version 1.3.1 the recipe is overwritten by the "Handcrafted" hammer, which does not produce iron sheets/plates.

### Steps to reproduce

1. Try to craft the ad astra hammer
2. You will receive the Handcrafted Hammer instead
3. Try to craft Iron Sheets with it
4. You will not be able to.

### Expected behaviour

Ad Astra Hammer recipe does not conflict with Handcrafted Hammer

### Screenshots

Ad Astra hammer recipe:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1097586/199561b0-a6b5-4487-87e3-fac806aeaece)

Handcrafted Hammer actually output:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1097586/c44ae7e4-0e79-419d-9960-279521b9a7d6)

**Comment by Medivha** [comment]
You can craft it in the normal Crafting table by pressing the arrows.

![](https://i.imgur.com/6GZoSBz.png)

The mod that make same recipe patterns craftable made it only for the crafting table. Most other crafting windows don't have it.(and/or chooses a random one)

**Comment by SaronGrave** [comment]
I have the same problem. Also persists in modpack version 1.4.0.

@Medivha I do not have the arrows button in the original crafting table and/or other crafting tables. Do you have something extra installed for this?

**Comment by Medivha** [comment]
it should be in the pack if it comes from a specific mod. the button only shows when it used on a recipe with multiple outcomes.
![javaw_2023-11-04_14-01-22](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/16429350/634aa53f-6833-4181-a5ef-fd26529e4668)

I think Direwolf20 mentioned somewhere in his Youtube series the mod/name but could not find on the quick.

If there is another problem with it, i have no clue how to fix it ;)

**Comment by Medivha** [comment]
Bump. would be nice to also change that recipe (same as drawer/cupboard) hammer gets confused a lot. and only the ad astra one cane make the iron sheets

**Comment by Drakkim** [comment]
Also, the fact that they look the same makes it super easy to craft the wrong one. Could you possibly add the Handcrafted one to an ore dictionary or the sheet recipes?

**Comment by DinnerBeef** [comment]
Looks like Ad Astra has since removed the hammer for their mod. As such, this issue will now be closed.
