### ISSUE TITLE
Update TorchMaster to 20.1.5 to fix #4019

### ISSUE THREAD

**Issue by Kadah** [FTBTeam/FTB-Modpack-Issues#4123]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.1

### Describe the bug

Bug https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4019 is fixed by https://github.com/Xalcon/TorchMaster/issues/223

### Steps to reproduce

See https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4019

### Expected behaviour

Mega Torches should block all hostile mob spawns, or at least the death loving leaping fishies

### Additional information

Can confirm fixed. Only server needs the updated mod, so anybody currently experiencing this issue can update just TorchMaster to resolve till the next pack version ships.

The previous unsuccessful fix attempt can be undone as it is does nothing.

`megaTorchEntityBlockListOverrides = ["+cataclysm:lionfish"]` > `megaTorchEntityBlockListOverrides = []`

**Comment by Skilles** [comment]
Torchmaster was updated in version 1.4.0
