### ISSUE TITLE
Game crashes when loading something(dont know what)

### ISSUE THREAD

**Issue by Risingtoglory** [FTBTeam/FTB-Modpack-Issues#4127]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.1

### Log Files

[2023-10-28-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13193776/2023-10-28-2.log.gz)
[2023-10-28-3.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13193777/2023-10-28-3.log.gz)
[2023-10-28-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13193778/2023-10-28-1.log.gz)

### Describe the bug

my game suddenly just crashed, when loading up the world then walk a little and some chunk would load with something that ceases my game to just crash

### Steps to reproduce

1.load world that im in
2.Move exact position im in
3.wait till all chunkz (12) load
4.Crash happens form something that loads

### Expected behaviour

Crash

### Additional information

I have a shaders mod but i tried it without shaders and it still had the issue, i even uninstalled the mod

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by DinnerBeef** [comment]
Sorry about that. Looking at this a bit more, looks like you installed a fork of Sodium for forge. Please remove that mod and try again.
