### ISSUE TITLE
INFECTED According to my Anti-virus software

### ISSUE THREAD

**Issue by JoelHud** [FTBTeam/FTB-Modpack-Issues#4128]
### Modpack

Other...

### Modpack version

Latest

### Describe the bug

Trojan:Win32/Znyonm Detected and Quarentined

### Steps to reproduce

Scan files

### Expected behaviour

IF you have an anti-virus it SHOULD auto detect the Trojan:Win32/Znyonm virus

**Comment by JoelHud** [comment]
This is from the STONEBLOCK 3 pack (Sry I couldn't get that into the original report.

**Comment by TheFlyron** [comment]
Same error for version Stoneblock 3 1.8.0 for me. Same trojan name. I can install version 1.7.1 but then can't upgrade. The current version is unplayable via FTB App.

**Comment by UnRealDinnerbone** [comment]
Same as #4131
