### ISSUE TITLE
Malware detected when installing Stoneblock 3

### ISSUE THREAD

**Issue by Camq543** [FTBTeam/FTB-Modpack-Issues#4129]
### Modpack

FTB StoneBlock 3

### Modpack version

Stoneblock 3

### Describe the bug

Windows defender flags Trojan:Java/Vigorf.A as malware when you try to install the Stoneblock 3 modpack

### Steps to reproduce

Download FTB launcher
Install Stoneblock 3

### Expected behaviour

Install will fail when windows defender flags Java/Vigorf.A as trojan malware

**Comment by SandaJohn13** [comment]
I have the same issue, flags mine as Java:XWorm!MTB

**Comment by TheFlyron** [comment]
Also getting flagged for me with some other name. Is something happening here?!

**Comment by UnRealDinnerbone** [comment]
Same as #4131
