### ISSUE TITLE
[Bug]: (Oceanblock) RS Wireless system claims "Network Not Found" upon entering and attempting to enable one in two different Compact Machines

### ISSUE THREAD

**Issue by butterlol143** [FTBTeam/FTB-Modpack-Issues#413]
### Modpack

FTB Oceanblock

### Modpack version

1.9.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7647508/latest.log)

### Describe the bug

While setting up a second wireless Refined Storage in another compact dimension, the wireless transmitter will claim "Network Not Found" on any and all wireless networks inside of the compact machines dimension.

### Steps to reproduce

1. Set up base Refined Storage system in over world with two **Network Transmitters**
2. Chunk load this area
2. Create two compact machine blocks and place one **Network Receiver** and **Wireless Transmitter** in each 
3. Connect them to the **Network Transmitters** with **Network Cards**
4. Attempt to connect to one with a **Wireless Grid**

### Expected behaviour

The system will claim "Network not Found" in both dimensions.

### Screenshots

Compact machine #1
![image](https://user-images.githubusercontent.com/95466939/144563116-9d76f069-5aef-462e-960e-4f0d0e94903e.png)
Compact machine #2
![image](https://user-images.githubusercontent.com/95466939/144563171-06ffdefb-22ef-43ff-9cc4-246036410e08.png)
Overworld
![image](https://user-images.githubusercontent.com/95466939/144563183-1ac8ee87-f224-4b39-8fe6-04495a296a72.png)

**Comment by Sunekaer** [comment]
Hi, 
So i just created this setup in my world and i dont have this issue.
I can recreate the issue if i right click on the receiver with the wireless grid but thats the only way i can recreate this issue.
Could you try and link you grid again and go to the world and dont look at the RS system when right clicking to open the grid
