### ISSUE TITLE
Trojen:XWorm!MTB

### ISSUE THREAD

**Issue by SandaJohn13** [FTBTeam/FTB-Modpack-Issues#4131]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.0

### Log Files

(https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137634365/5d9105ea-7a5d-4e21-a8d8-8ce76b62b37d)

### Describe the bug

When installing from the FTB App a fatal exception is encountered due to Windows Security flagging a file as a Severe Trojan threat. The affected item file path makes sense (AppData\Local\.ftba\bin\libraries\net\minecraftforge\forge...) but it's still scary that windows is calling it "Trojan:Java/XWorm!MTB" which seems to be a well known virus. Is this a false positive? Thank you 

### Steps to reproduce

try to install FTB StoneBLock 3 from the FTB App

### Expected behaviour

Windows Security flags an install file as a severe XWorm threat and prevents the install

### Screenshots

![Trojan](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/137634365/cf403edc-a7b7-400e-9608-fce84a7fc1b2)

**Comment by RyanC-1229** [comment]
got the same thing.
also know of 2 others with the issue

**Comment by shkabo** [comment]
related to https://github.com/MinecraftForge/MinecraftForge/issues/9765
partial solution, downgrade to forge 1.18.2-40.2.9

**Comment by SparkdotIe** [comment]
I have gotten the same thing twice now. It either reads it as Trojan:Java/XWorm!MTB or Trojan:Win32/Znyonm while downloading forge 1.18.2-40.2.10

**Comment by TheFlyron** [comment]
It's not installable via the FTB App. The download just fails. I can install 1.7.1 as this doesn't get flagged as a virus, but then can't upgrade. It's impossible to play the current version and I'm not going to deactivate my windows defender.
