### ISSUE TITLE
Fatal issues when installing mod pack

### ISSUE THREAD

**Issue by Trooper4life** [FTBTeam/FTB-Modpack-Issues#4132]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.1

### Log Files

FTB-DBGUWOCUHOTEY
error code on ftb debug

### Describe the bug

Install failed due to Fatal exception whilst installing modpack.

### Steps to reproduce

1. Download direwolf20 1.20 mod pack
2. When installing the mods get fatal error

### Expected behaviour

I expect to download the mods and begin playing the pack

### Screenshots

![Screenshot (2)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/149276824/7561fe42-467d-4895-8b97-03a3b38b4f6a)

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
