### ISSUE TITLE
NoMoWanderer makes trader more annoying

### ISSUE THREAD

**Issue by duragizer** [FTBTeam/FTB-Modpack-Issues#4133]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.1

### Describe the bug

When sign or talisman is used trader still spawns with llamas they are just always invisible and annoy you like never before.
You hear them walking around and if you blindly attack or shoot with seeker bow they are killed and drop items.

### Steps to reproduce

Use NoMoWanderer talisman or sign

### Expected behaviour

Trader should not spawn at all

**Comment by Medivha** [comment]
i use the talisman and sometimes they spawn but instant despawn. but most of the time they don't spawn at all.

**Comment by nuke3d** [comment]
I am experiencing this as well. Same modpack.

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you? Can you please ensure that they are not spawning outside the range of the sign?

**Comment by duragizer** [comment]
Still happens in pack version 1.10.0 and it spawns in the same chunk or one chunk over as sign or player with talisman.
It is definitely within the 6 chunks it should not spawn.

**Comment by HalJordan** [comment]
Still happening. Turning them back off via command.

**Comment by WebDeveloperMax** [comment]
My friends and I on a server are also experiencing this issue. The Trader Rug does not seem to make them spawn at that location either. They spawn within our houses and bases.
