### ISSUE TITLE
Lost souls spawn on delightful dirt

### ISSUE THREAD

**Issue by SYNE-RU** [FTBTeam/FTB-Modpack-Issues#4136]
### Modpack

FTB Presents Direwolf20 1.20

### Is your suggestion related to a problem? Please describe.

Related to this issue: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4052
Changelog for version 1.2.0 says this was fixed but they keep spawn on delightful dirt in version 1.3.1.

Also they can fly through Fission reactor from Mekanism and it seems that they took a huge amount of radiation which is causing them to taking damage. But they can't die so they keep flying but now producing taking-damage-sound every second. This is extremely annoying! Please get rid of them finally

**Comment by SYNE-RU** [comment]
`Lost souls spawn on delightful dirt [#4136]`
Nope.
https://www.youtube.com/watch?v=Wb-sqGccDXQ
Skip loading to 4:05

**Comment by Skilles** [comment]
Can confirm this is happening in version 1.4.0

**Comment by jlp1528** [comment]
This issue still exists in 1.5.0, That, or the Mob Masher from Mob Grinding Utils is producing them when it kills things. Either way, they are EVERYWHERE.

**Comment by jlp1528** [comment]
![2023-11-15_17 48 25](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1498260/9138f8f4-56f9-47f1-ac69-971747dca0a8)
bruh

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by jlp1528** [comment]
I'm still getting lost souls, yes.

**Comment by Kirizan** [comment]
I am also getting this issue still. It's breaking my delightful dirt mob farms.

**Comment by incomingnerd** [comment]
The existing script uses the wrong tag registry and tag name. In `kubejs/server_scripts/tags.js`, change lines 199-201 from
```
ServerEvents.tags('entity', event => {
    event.add('mob_grinding_utils:no_spawn' ,'forbidden_arcanus:lost_soul')
})
```
to
```
ServerEvents.tags('entity_type', event => {
	event.add('mob_grinding_utils:no_dirt_spawn' ,'forbidden_arcanus:lost_soul')
})
```
(the `mob_grinding_utils:no_spawn` tag is registered, but isn't actually used, AFAICS)

Enjoy!

**Comment by Gaz492** [comment]
Closing in favour of #5368
