### ISSUE TITLE
Productive bees - nest not accepting treats

### ISSUE THREAD

**Issue by mzery** [FTBTeam/FTB-Modpack-Issues#4137]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.1

### Describe the bug

Can not put a honey treat into a quartz nest. 
Also could not give a crystalline bee spawn egg, it was not listed in the commands

### Steps to reproduce

1. place quartz bee nest
2. try to place treat in nest
3. nest does not accept treat

### Expected behaviour

nest to accept treat

**Comment by Medivha** [comment]
you need to give it Quartz. also mentioned with U on the nest in JEI or R on the Bee

![javaw_2023-10-31_10-17-53](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/16429350/fdd870df-710c-42ec-b70d-327796967812)

**Comment by DinnerBeef** [comment]
Please let me know if you were able to get this issue fixed.

**Comment by mzery** [comment]
It did work, thank you.

I was reading the bee instruction book and it said treats.
