### ISSUE TITLE
Create train glitching, other issues coincided that likely were caused by the train.

### ISSUE THREAD

**Issue by Craw-d** [FTBTeam/FTB-Modpack-Issues#4139]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.0

### Describe the bug

-Basically, I'm stuck in a room with a broken train
-Can't pick up drops, occasionally a few do come through
-Can't eat
-Can't mine
-Can't use my tempad to teleport out of there
-Can't move Create train that I have moved from track to track in past
-Upon reloading my single player world the train glitched:
     -Bogies are rotated 90 degrees, not in intended direction
     -One entire train car has disappeared
     -Tunnel bore has moved into the middle of the train and now faces the wrong direction
     -A train station can't be used to modify train
     -Train car with controls is the one that disappeared making driving the train impossible

<img width="1728" alt="Screenshot 2023-10-30 at 1 21 18 PM" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/149417761/792ff5b2-7d11-4879-9f14-d753d1af67d7">

<img width="1728" alt="Screenshot 2023-10-30 at 1 20 49 PM" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/149417761/8915ebfe-bf7b-4cba-b1bc-59bba38f1b94">

### Steps to reproduce

Computer:
2021 16in MacBook Pro
64 gigs ram (30 gigs allocated to FTB, uses about 13 gigs)
SSD
M1 Max chip

1. Make a 3 car train-tunnel bore that also utilizes a lot of deployers
2. Restart FTB & Stone Block 3
3. Open game and inspect train
4. If possible, move train to a new track
5. If possible drive the train
6. If not possible, restart game. My problem still exists after restarting game

### Expected behaviour

#1 Click bogie with create's wrench
#2 Click on desired track with wrench facing the right direction
#3 Whole train moves to desired location and direction, appearing the way I made the train
#4 Glued sections stay glued appropriately

**Comment by Craw-d** [comment]
After about 20x of waiting the 3 minute tempad cooldown I did get through the portal. I had just played for 4 a few hours and didn't want to lose my progress with a previous save. 

Also had an issue while in a nether fort. Mined a ladder and the space left behind translucent ghost blocks is what I'll call them anyways. Maybe there is as greater problem.

**Comment by Gaz492** [comment]
Does this still happen to you on the latest version of the modpack?
If it does, would you be able to upload your world so we can take a look?
