### ISSUE TITLE
Can't download stoneblock3

### ISSUE THREAD

**Issue by XTrooper815** [FTBTeam/FTB-Modpack-Issues#4142]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.0

### Log Files

Trojan:Java/XWorm!MTB
![Screenshot 2023-10-30 165519](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/128264884/b8df4baf-dbc7-4534-9031-88e65ccbd839) 

### Describe the bug

It keep saying that theres a trojan virus when i try to download stoneblock3, but its fine for anyother modpacks

### Steps to reproduce

1. Download the FTB app
2. download stoneblock3
3. select version 1.8.0
4. click install

### Expected behaviour

you should get a virus alart

### Additional information

Im useing a window 11
Any other version of stoneblock 3 works only 1.8.0 doesent work

Edit: I fixed it

**Comment by linkion** [comment]
Also getting this

**Comment by XTrooper815** [comment]
> Also getting this
