### ISSUE TITLE
Bug Crafting Middle Tier Gateway Pearls

### ISSUE THREAD

**Issue by jfrisnedi** [FTBTeam/FTB-Modpack-Issues#4143]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.1

### Describe the bug

The middle tier of gate pearls from the Gateways To Eternity mod are bugged and the crafting recipe gives a generic "Gate Pearl."

### Steps to reproduce

1. surround an eye of ender with any mob drop like blaze rod, spider eye, rotten flesh, bones, etc. in a crafting table/
2. see the results of the bugged recipe

### Expected behaviour

for the middle tier gate to be crafted

### Screenshots

![bug](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/149436759/9373ca86-7905-4fee-a67f-0bfc38f80de7)

**Comment by DinnerBeef** [comment]
https://github.com/Shadows-of-Fire/GatewaysToEternity/issues/33 Mod Dev disabled to pending overhaul
