### ISSUE TITLE
Ars Break Spell Not Working

### ISSUE THREAD

**Issue by TheMrLocalhost** [FTBTeam/FTB-Modpack-Issues#4144]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.1

### Log Files

https://pastes.io/3v0gqtmlop

### Describe the bug

Using the spell projectile break in ars nouveau does not break any blocks (yes, not even dirt).
Tried in/out of claimed zone
Tried amplify
Tried to make sure spawn protection wouldn't be the culprit
Tried re-learning the break spell
Tried the /ars-reset @s command

It should also be noted that touch-break doesn't work either.

### Steps to reproduce

Open spellbook
select projectile
select break
name spell "Break"
click "create"
ensure "Break" spell is selected
Right click
projectile fires
block does not break

### Expected behaviour

projectile break should break at least dirt

**Comment by DinnerBeef** [comment]
The only thing I can think of is make sure you have enough mana Because the spell is working just fine for me.
