### ISSUE TITLE
Mekanism Digital Miner 

### ISSUE THREAD

**Issue by Olann92** [FTBTeam/FTB-Modpack-Issues#4146]
### Modpack

FTB Presents AbePack

### Is your suggestion related to a problem? Please describe.

it's not really a proposition but i just want to know how to reactivate the digital miner on my server 
if someone have any idea how, i would be very grateful

**Comment by DinnerBeef** [comment]
You can remove the "mekanism:digital_miner" from both the hide.js and minecraft.js files in KubeJS scripts.
