### ISSUE TITLE
FTB Inferno Freeze on Save + Exit

### ISSUE THREAD

**Issue by nroe1337** [FTBTeam/FTB-Modpack-Issues#4147]
### Modpack

FTB Inferno

### Modpack version

1.9.1

### Describe the bug

Whenever I leave the world, FTB inferno seems to get stuck on saving and exiting. The only way I can close the game is to kill the instance through the FTB Launcher. I'm worried that this will impact my ability to play the pack because my world may not save properly. 

### Steps to reproduce

1. Download FTB Inferno
2. Create World
3. Leave World
4. Game is stuck

### Expected behaviour

When pressing Save and Exit, the game gets stuck and does not fully exit the world.

**Comment by nroe1337** [comment]
I've tried reinstalling the pack and changing java versions, as well as reinstalling the FTB launcher completely, I'm at a loss of what to do and would really like to play this pack. Can anyone help me?

**Comment by Saereth** [comment]
updating forge and ftbbackups seems to have resolved this, update will be out today
