### ISSUE TITLE
Curios deleting items when clicking sorting inventory buttom while hovering over curios slots

### ISSUE THREAD

**Issue by madbranx** [FTBTeam/FTB-Modpack-Issues#4148]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.3.1

### Log Files

no log available. items dissappeard without any note in the server console

### Describe the bug

All items in Curios slot (except advanced magnet) got deleted by clicking the inventory sorting button (middle mouse button) while hovering over the curios slots in the inventory,

### Steps to reproduce

1. put item in curios slot (e.g. a backpacl from sophisticated backpacks)
2. klick middle mouse buttom while hovering over any curios slot
3. item is deleted

### Expected behaviour

expected nothing to happen: esp. not deleting the items

**Comment by Medivha** [comment]
are you talking about the curio tab on the top or the curio slots on the left

If you're talking about the one on the top, the tab then you can do the command "/invsorter bladd l2tabs:curios"  (without the "") and it adds it to the blacklist, and it should not sort any more.

If you're talking about the left side, then I didn't find a way to block with that command.

for the ftb team notes: if you add it to default on a future update it will not fix existing worlds only new created. same as the productive bee one

**Comment by Medivha** [comment]
nvm the command is only available with cheats or creative. so it needs to be in the config

**Comment by madbranx** [comment]
Hello,
thank you for your answer!
Yes, I was talking about the curio tab on the top.
The stated command did fix the bug.
thanks!

**Comment by Medivha** [comment]
even it is fixed for you with the command it is not fixed for everyone else especially without cheats/creative so the issue should stay open

**Comment by DinnerBeef** [comment]
This issue has now been fixed! Please reopen this issue if you are still having problems.
