### ISSUE TITLE
Monster Drops don't stack in certain Circumstances and a way to reproduce the Bug

### ISSUE THREAD

**Issue by Medivha** [FTBTeam/FTB-Modpack-Issues#4149]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Log Files

Video with the Bug https://youtu.be/uNe8-_LVZok

### Describe the bug

Sometimes you have Items from Monster drops (at least only Monster drops so far we know) that don't stack.

### Steps to reproduce

You can see that i create in the Video (link in log area) a conflicting extract with LaserIO, so the drop doesn't know where to go.
I added a second Extract with a NBT filter and some not functioning nbt tag.
Then you can see that some of the items generated by the Drygmy don't get sorted into the drawer system.
Now i pick from the Drawers the same Items and after that i pick it out of the chest. And you can see they don't stack.

I do it in this order because as you can see in the Video if you pick out the Items first from the chest and then from the drawer it acts like as a new dropped Item and fixes itself. 
The same goes if you just let the items sit in the chest revert the nbt filter to normal, and it fixes itself as soon the same item drops again goes on top of the "broken/corrupted" Item
You also can see that the "broken" item cant be put manually into the drawers.

### Expected behaviour

Items Stack correct

### Additional information

Just do be clear again, this is not only a LaserIO thing. I just had it a lot with it because you create these conflicting scenarios with it easier. People in Discord said they just had it also from Normal Monster drops just by killing them.
I assume that when Stuff drops/want to get pick up if there is some conflicting scenario it creates these Items that don't stack. Like the conflicting filter on LaserIO or maybe on normal Drops Magnets that fight each other.

Idk what creates this behaviour, but at least you have something now to further investigate it.

If you need my world, let me know where I can upload it. Feel free to Ask for more details.

**Comment by DinnerBeef** [comment]
Thanks for reporting and issue, However this is working as indeed and will not be fixed. This is to do a mod making it so baby zombies despawn after 5 mins even if they pick up and item.
