### ISSUE TITLE
[Bug]: Zombies in mob farm standing still (unkillable)

### ISSUE THREAD

**Issue by iammael** [FTBTeam/FTB-Modpack-Issues#415]
### Modpack

FTB OceanBlock

### Modpack version

1.9.0

### Describe the bug

When a world run for a certain time, mob farms end up with multiple mini zombies and mini zombie villagers standing still. They have no AI and are unkillable (see screenshot below).

The server's log printed hundreds of message like this during the night (might or might not be related):

`[18:42:44] [Server thread/WARN] [minecraft/TrackedEntity]: Fetching packet for removed entity ZombieVillagerEntity['Zombie Villager'/11004, l='ServerLevel[Main World]', x=258.50, y=120.00, z=4861.50]`

### Steps to reproduce

1. Build a mob farm with the mob spawning utilities of your choice (Mechanical Dirt or Cursed Earth)
2. Let the world/server run for a while

### Expected behaviour

All mobs are killed and no left-overs

### Screenshots

![2021-12-03_17 46 35](https://user-images.githubusercontent.com/7931135/144648860-45a3051b-a458-4b13-9285-9b4fffd49bcd.png)

### Additional information

This is certainly not a bug related to Mini Utilities' Cursed Earth as I had the same issue with Mechanical Dirt on another pack (Sky Bees).

_This is a bug I've had in multiple packs, and multiple people in the Discord confirmed they experienced the same thing so I decided to open an issue. As this is not an FTB issue, I don't know if this is the right place to post this but maybe someone will want to investigate it._

**Comment by Raidobw2** [comment]
> As this is not an FTB issue, I don't know if this is the right place to post this but maybe someone will want to investigate it.

Any issue related to our modpacks is a FTB issue. We'll take care of redirecting the info to the right people if needed, after investigation.
Thanks for the report and with the picture too!

**Comment by Sunekaer** [comment]
Which mods have you added to the pack?
Could you test if you can recreate this issue without adding any mods to the pack?

**Comment by iammael** [comment]
I added:
- Enigmatic Graves (replacing Gravestone)
- Framed Compact Drawers
- More Overlays (replacing LightOverlay)
- JourneyMap
- Optifine & Shaders
- RSInfinityBooster
- Sophisticated Backpacks

I should have mentionned those in my report, sorry about that.

I'll recreate a test world tomorrow and let the server run for a day, I'll get back to you with the results.

**Comment by Sunekaer** [comment]
Thanks, im testing in my SP world also.
After how long does it happen normally?

**Comment by iammael** [comment]
I'd say one or two hours for the first ones to appear. For as many as in the screenshot it was a whole night of letting the server run.

**Comment by Sunekaer** [comment]
Okay thanks

**Comment by iammael** [comment]
I was already able to recreate the issue on a fresh installation of version 1.9.0 of the modpack (no modifications at all).

It is also a completely new world.

I don't know it could have any influence but do note that it is on a local server.

![2021-12-09_16 06 41](https://user-images.githubusercontent.com/7931135/145421683-96af1ab4-c236-4f4c-af90-69a390f5276e.png)

**Comment by Sunekaer** [comment]
Could you upgrade to 1.10.1 and test, i have had my world open for nearly 2 hours and no issue.
IS your test on MP or SP

**Comment by iammael** [comment]
It is running on a local server (same computer) so it is MP.

I unfortunately have to leave but I'll try on the latest version tomorrow if you still need it.

**Comment by Sunekaer** [comment]
Okay, my SP world has been running for 5 hours now without issues.
Ill do some MP test over the weekend

**Comment by iammael** [comment]
I was still able to recreate the issue on version 1.10.1 of the pack.

![2021-12-10_03 51 27](https://user-images.githubusercontent.com/7931135/145509167-6358e3a6-6f6c-474e-9b4b-032a8c89c1c4.png)

**Comment by Sunekaer** [comment]
Im still not able to create this, i had the server running for 5 hours with my client looking that the mob spawner

**Comment by iammael** [comment]
Then I wonder if it only happens when the player is not connected. Because when I tested that, I stayed in the world for a little while and couldn't reproduce the bug. But then I disconnected, went back half an hour later and I had a few of these AI-less guys.

**Comment by Sunekaer** [comment]
So the chunk is loaded by FTB Chunks or how?

**Comment by iammael** [comment]
Yes I chunkloaded via FTB Chunks

**Comment by ThorsHammer666369** [comment]
i have had the same issue latest pack mp server i think it is the mob crusher from mob utilities.  first time i had to use op commands to kill them, after i got my Drac staff of power or drac bow with vary high damage i can kill them one hit. if you dont 1 hit them you have to use commands to remove

**Comment by crouton111** [comment]
Same issue here. I'm using cursed earth (now turned to dirt from lamps), with fans and mob grinder from mob utilities.
![Little_guys01](https://user-images.githubusercontent.com/39347503/147992079-16b0af10-214b-4ace-88ee-3fa6c8f25a88.png)
I haven't added any mods, but I did remove the Hats mod.

**Comment by BigPlatypus** [comment]
I just discovered this bug on an Oceanblock server running the 1.12.0 version of the modpack, with no modifications, on a remote hosted server. Some experimentation on the frozen baby zombies shows them immune to water flow, lava, and the mob imprisonment tool. It's as if they aren't there—unless you one-hit them with a strong enough weapon. Despite this, they count towards the hostile mob cap, which can ruin mob farm rates. Every day or so I have to turn off my modest cursed earth mob farm and clear them out manually, as even with a small spawning area (10x10 blocks) they build up quickly.

The frozen baby zombies only seem to appear when leaving the mob farm running while offline and keeping the area loaded with FTB Chunks. Since FTB Chunks doesn't play nice with other mods including Refined Storage, my initial hypothesis is that there's something about these loaded chunks that is breaking the spawning system for baby zombies. I'll do further testing to see if it a) happens when a player is online, and/or b) occurs with natural mob spawns rather than spawns "forced" by cursed earth or similar spawning blocks.
