### ISSUE TITLE
Mekanism Infused Alloy lost it's crafting recipe and is uncraftable

### ISSUE THREAD

**Issue by UNK1LL4BL3** [FTBTeam/FTB-Modpack-Issues#4150]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13229507/latest.log)

### Describe the bug

Infused Alloy has lost its JEI recipe and is uncraftable. From what I remember from the other day, you use a metalurgic infuser and put redstone and iron in which should create the Infused Alloy. After updating to 1.4.0, you can no longer put iron into the infuser with redstone.

### Steps to reproduce

1. Go to JEI
2. Search Infused Alloy
3. Try to see Recipe.
4. Put redstone into metalurgic Infuser (Mekanism)
5. Try to place Iron ingots into the Infuser as well.
6. Iron is unplaceable.

### Expected behaviour

Once redstone is placed into Infuser, you should be able to place iron in as well, thus creating Infused Alloy with the help of power.

**Comment by Medivha** [comment]
I'm on 1.4.0 and still have it in JEI and can craft it. Can you restart your game and check again. And maybe also check in a new world in creative if it is only happening in your save.
