### ISSUE TITLE
AE2 not working correctly

### ISSUE THREAD

**Issue by minimee1864** [FTBTeam/FTB-Modpack-Issues#4153]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.20.1

### Describe the bug

 i login into my single player world and my AE2 system is missing patterns that i know i put in my ME pattern access terminal before i got got off then login in its not there 

### Steps to reproduce

ae2 is set up 
log out log in 
pattern are not there 
in the screen it shows u ca craft it but nothing happens

### Expected behaviour

it should not delete my patterns after i log out

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
