### ISSUE TITLE
Create Display Link cannot be placed on Elevator Contact

### ISSUE THREAD

**Issue by desaianand1** [FTBTeam/FTB-Modpack-Issues#4155]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Describe the bug

Unable to place a Display Link on an elevator contact block. When attempting to place, it momentarily places, then disappears and returns to inventory. This issue only occurs while on a server. On a single player world, It works as expected and I cannot replicate this issue.

### Steps to reproduce

1. Setup "Create" elevator contraption with Redstone Contacts placed appropriately in a column.
2. Place and power an Elevator Pulley block and connect it to the contraption. Note that the stationary Redstone Contacts turn into Elevator Contacts
3. Target a display source with a Display Link
4. Attempt to place Display Link on an Elevator Contact block.

### Expected behaviour

Display Link should place on an Elevator Contact and allow reading it as a Display Source

**Comment by desaianand1** [comment]
Any update? Does this require more information?

**Comment by TrashTwT** [comment]
i have the same issue, any news?

**Comment by desaianand1** [comment]
@TrashTwT I resolved this issue by placing a dummy, solid block, placing the display link adjacent to it and then breaking the initial dummy block. This works for those odd placements where it initially disappeared.

**Comment by TrashTwT** [comment]
we could say it worked. I instead of using a dummy block placed a display link on redstone contact, because for some reason it doesnt have a problem with it, and then rotated it with a wrench. Thanks for the tip!

**Comment by UnRealDinnerbone** [comment]
An Update has been released since this issue was made. Can you please confirm this issue, it's still happening?

**Comment by desaianand1** [comment]
> An Update has been released since this issue was made. Can you please confirm this issue, it's still happening?

Was unable to replicate this issue again on a single player world on the latest version. Unfortunately, I do not have access to a multi-player world/server with the latest version to demonstrate if the bug was fixed in that scenario
