### ISSUE TITLE
Client-Only Mod's Triggering Error on Server Startup

### ISSUE THREAD

**Issue by lazycooken** [FTBTeam/FTB-Modpack-Issues#4156]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4

### Log Files

[13:17:27] [modloading-worker-0/ERROR] [me.ic.mo.be.co.BetterThanLlamas/]: You are loading Better Than Llamas on a server. Better Than Llamas is a client only mod!

[13:18:08] [modloading-worker-0/ERROR] [me.ic.mo.be.co.BetterThanBunnies/]: You are loading Better Than Bunnies on a server. Better Than Bunnies is a client only mod!

### Describe the bug

In a modded Minecraft server, the 'Better Than Llamas' and 'Better Than Bunnies' client-only mods trigger error messages during server startup. These mods are already present in the server's mod list, and they are not intended for server-side use.

### Steps to reproduce

Start a Minecraft server,

### Expected behaviour

The expected behavior is that the server starts without any errors. Client-only mods like 'Better Than Llamas' and 'Better Than Bunnies' should not be on the server side of the modpack, and their presence on the server should not cause any issues during startup.

### Screenshots

![Screenshot 2023-11-02 063738](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/46348858/461fdaa8-ea60-4b16-9ef5-fe80e6f29072)

**Comment by lazycooken** [comment]
> Did you use the server installer to install the server?

Yes, I did install it through the installer.

**Comment by DinnerBeef** [comment]
It should be fixed. Thanks for reporting the issue.
