### ISSUE TITLE
Bug Report : Instance fold bug

### ISSUE THREAD

**Issue by MisterBros** [FTBTeam/FTB-Modpack-Issues#4158]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.2.4

### Describe the bug

I installed the mod, launched it from the FTB App, and then this text appeared in the log:

[FTB APP][INFO] Validating assets
[FTB APP][INFO] Validating Java Runtime
[FTB APP][INFO] Pre-Start Tasks

A pop-up window appeared with the following text:

An Error Occurred While Launching
Failed to prepare instance 'FTB Plexiglas Mountain' (2c8b507c-7a8-4ad5-b956-984396e7a41f) because... java.io.IOException: Failed to execute asset update task.

It's clear that something is missing on my PC, but I really don't know what it is.
I tried to launch FTB Skies on the side, and it worked.

### Steps to reproduce

I just install FTB Plexiglas from FTB App

### Expected behaviour

I hope we can fix this problem, maybe someone has encountered the same bug.

### Screenshots

![Capture](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/114913279/bc9e2eb9-e457-40cc-af39-7cbb40b8231e)

**Comment by Gaz492** [comment]
If this is still an issue for you, please open a new issue at https://github.com/FTBTeam/FTB-App
