### ISSUE TITLE
[Bug]: Redundant Signalum recipe

### ISSUE THREAD

**Issue by loneztar** [FTBTeam/FTB-Modpack-Issues#416]
Signalum Recipe Bug

FTB Ultimate: Anniversary Edition

### Modpack version

1.0.4

### Describe the bug

2 recipes for Signalum via crafting table. One recipe takes 3 copper, 1 silver, 2 redstone (all dust) resulting in 4 Signalum (dust)

Second recipe takes 3 copper, 1 silver, 4 redstone (all dust) resulting in 4 Signalum (dust)

Seems to be no reason to use the dearer recipe

### Steps to reproduce

Take materials
place in crafting table in pattern for desired recipe
check output for intended quantity of signalum

Repeat for second recipe

### Expected behaviour

Either 1 recipe or 2 recipes with differing output amounts

**Comment by Raidobw2** [comment]
Fixed in dev 1.0.5 by LatvianModder
