### ISSUE TITLE
Modular routers break and placer does nothing

### ISSUE THREAD

**Issue by pwaksman973** [FTBTeam/FTB-Modpack-Issues#4160]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Describe the bug

I can't get modular routers to place or break any item, even just dirt.

### Steps to reproduce

1. Place the modular router
2. Config a placer to place item in front, empty black list
3. Add the placer to the modular router
4. Add dirt or any block on the router buffer
5. Nothing will happen

Same for breaker module
White listing doesn't help either.
Direction also doesn't metter

### Expected behaviour

block should be placed or broken

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/78715804/96d1a914-7de6-4e2b-8175-3d689a61e702)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/78715804/e59c9ea2-874b-4187-9534-a5974d2e6236)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/78715804/b0269155-f046-45f1-9b09-d0c5ca86ebf9)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/78715804/8b9b52f7-e6e9-494b-a414-8d16ab9f900e)

**Comment by Medivha** [comment]
hm works for me. the only thing i can think of is Allow Fake player is False

Check the My teams when you have inventory open top left -> on the right the little cogwheel -> and here Set Allow All Fake Players to True

You should do that in single-player. on a Server idk if you can do that or should do that

let me know if that works

**Comment by pwaksman973** [comment]
Gosh, I should buy new glasses. It is clearly stated in manual
Thanks @Medivha
