### ISSUE TITLE
Stoneblock2 Erasing inventory

### ISSUE THREAD

**Issue by grumpyfan777us** [FTBTeam/FTB-Modpack-Issues#4161]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.22.0

### Describe the bug

When I am done playing I save and exit the game and wait to get back to the main menu before leaving the game. When I reenter my world all of my inventory that I had on my person is gone and all my armor/baubles are gone. It reverts to amor that I was wearing a long time ago BUT stuff that I put in chests are still in the chests. I can't find the backup save files on my comp to try and go back to a previous save.
I lost full dragon armor and the OP skull fire sword from quest drops. I can cheat the armor back in but not the sword.

### Steps to reproduce

1. Play a world for a few hours
2. Exit to the main menu
3. don't leave the game but Reenter the world after a few hours
4. all items gone.

### Expected behaviour

I expect the game to save my inventory and armor/baubles when I exit the game.

### Screenshots

![2023-11-02_22 59 36](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/18691551/16bf7a10-97a1-4aa7-bb96-eb8931d56e7a)

**Comment by grumpyfan777us** [comment]
I was able to find the save file and my inventory but its still aggravating to have to look for it.
![2023-11-02_23 18 30](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/18691551/b5420070-3016-42bc-ba7d-d509539a78c4)

**Comment by grumpyfan777us** [comment]
The disappearing inventory issue has spread to my transmutation table. I just loaded the game and everything I put into my transmutation table has disappeared.

**Comment by grumpyfan777us** [comment]
Ok I think you people don't care anymore. The issue has spread to ALL of my backups. I have restored every single backup i have going back a long time and every single one loads in at the same position. I have deleted the save file and pasted in the backup save file and its all the same. I made sure their different file by naming them different things but nothing. I have dragon armor and all of my fully upgraded draconic armor as well as everything i have fed into my transmutation tablet IS GONE. I'm uninstalling this fucking game and never coming back!!!!!!!!!!!!!!!!!!

**Comment by Gaz492** [comment]
Apologies for the lack of a response, if you still happen to have modpack installed, would you be able to reproduce the issue then upload the logs for us so we can take a look?
https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

If you can would you also be able to upload the world?
