### ISSUE TITLE
EnderIO Powered Spawner reset after copied and pasted with copy-paste gadget

### ISSUE THREAD

**Issue by ubaldialessio** [FTBTeam/FTB-Modpack-Issues#4162]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Describe the bug

I tried to copy and paste an EnderIO powered spawner. On pasting, the powered spawner on my inventory (that was a zombie spawner) was successfully placed but the zombie binding was removed.

### Steps to reproduce

1 Copy a binded EnderIO powered spawner with the copy paste gadget.
2 Have a binded powered spawner in inventory.
3 Paste.

### Expected behaviour

I expected that the past process keeps the mob (zombie) binding in the spawner.

**Comment by DinnerBeef** [comment]
It seems like the mod is working how it should. The copy and paste gadget should only keep the base machine and not any NBT data stored inside it.
