### ISSUE TITLE
Server disconnects players immediately after they connect: "Timed out waiting for world statistics"

### ISSUE THREAD

**Issue by Bcampsie** [FTBTeam/FTB-Modpack-Issues#4164]
### Modpack

FTB Presents AbePack

### Modpack version

1.5.0

### Log Files

https://pste.ch/idisaxohob.md

### Describe the bug

This issues started occurring this afternoon, as players had no issue playing the night before. Upon joining the server, players are disconnected almost instantly and presented with the error: Timed Out. On the console it says "Timed out waiting for world statistics." I was not able to find any way to fix it but I believe it to be related to the world itself as when I made a fresh server it ran fine but as soon as I brought the old world over it gave the same issue. Using any of the backups gave the same issue. I believe something one of the players did may be causing lag but I am unable to actually get in and navigate in order to find it. 

### Steps to reproduce

1. Ensure the AbePack 1.5.0 server has the Ars Elemental mod included.
2. Use the same world
3. You may have to be at the location where the majority of players live, there is an Ars Portal at spawn to there.
4. Get disconnected (If you didn't already before trying to go to the main lived in area)

### Expected behaviour

Upon joining immediately experience lag, when looking at anything with WAILA it will say "Waiting for server...", then disconnected.

### Additional information

I should note that this is the standard version of AbePack 1.5.0 and we added Ars Elemental to the mods and have been playing with that. The version of Ars Elemental we used can be found [here](https://www.curseforge.com/minecraft/mc-mods/ars-elemental/files/4768477). In order to replicate this you will probably need the world also so I included that [here](https://www.mediafire.com/file/mndu4zrfs9kwpc4/world.rar/file) as well.

**Comment by hailfire15** [comment]
I am now running into this in the direwolf20 1.20 pack. It seems to be happening whenever I run into a Supplementaries sign and the server is trying to spawn a block and it fails then just hangs. Is there any update on this?

**Comment by DinnerBeef** [comment]
Can you re-upload the logs, it seems to have been removed?
