### ISSUE TITLE
Aetherslate caves not generating

### ISSUE THREAD

**Issue by NixieTrick** [FTBTeam/FTB-Modpack-Issues#4165]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.2.0

### Describe the bug

Aetherslate cave biome is not generating. Nature's Compass cannot locate the Aetherslate cave in the Overworld. The dimension is blank in the Aetherslate cave biome entry for the compass. I also went into spectator mode and looked all over.  There are no Aetherslate caves. Thus aethersteel cannot be attained.

### Steps to reproduce

1. Try to find Aetherslate cave in the overworld.
2. Fail to locate.

### Expected behaviour

I expect Nature's Compass to locate an Aetherslate cave biome.

**Comment by DinnerBeef** [comment]
The worldgen of the mod was disabled to it being over complex. The mod was left to not break people's existing worlds
