### ISSUE TITLE
FTB Resurrection Server Installer for Linux Fails

### ISSUE THREAD

**Issue by gretaSamsa** [FTBTeam/FTB-Modpack-Issues#4167]
### Modpack

FTB Resurrection

### Modpack version

1.0.1

### Log Files

[install.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13255840/install.log)

### Describe the bug

The "serverinstall_12_119" binary does not download all files necessary for the server to operate. It says 4 files failed to download, all due to the error `unsupported protocol scheme ""`.
In the log file I stop when it shows that files were missed, I tried continuing the installation anyway but obviously the server then doesn't start.

### Steps to reproduce

1. Download the "serverinstall_12_119" binary (x86) from https://www.feed-the-beast.com/modpacks/server-files and set permissions such that it can be executed (I did it by using the commands provided).
2. Run the server installer binary. Four of the files fail to download.

### Expected behaviour

The server installer binary should download all needed files.

**Comment by Gaz492** [comment]
These errors should be fine to ignore, from a quick test the server still starts up and everything looks to be correct with the modpack.
