### ISSUE TITLE
Fatal Exception Whilst Installing Modpack

### ISSUE THREAD

**Issue by TzarChasmJr** [FTBTeam/FTB-Modpack-Issues#4169]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Log Files

https://pastebin.com/50gJSVQ7

### Describe the bug

Direwolf20 1.4.0 brings up a fatal exception every time install is attempted.

### Steps to reproduce

1. open FTB App
2. click on Direwolf20 1.4.0
3. click install
4. failure

### Expected behaviour

Expected modpack to install.

### Screenshots

![Screenshot (1)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/149891248/17119d34-57be-4563-852b-97d20c6a344e)

### Additional information

debug code: FTB-DBGSATEKUGUQU

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
