### ISSUE TITLE
[Bug]: Infinite loading terrain screen

### ISSUE THREAD

**Issue by DaKiller3k** [FTBTeam/FTB-Modpack-Issues#417]
### Modpack

FTB OceanBlock

### Modpack version

1.9.0

### Describe the bug

Infinite loading terrain screen upon falling out of Blood Magic's Edge of the Hidden Realm dungeon while having "Warm Void" trinket activated (Lost Trinkets mod).

### Steps to reproduce

1. Find a "Warm Void" trinket.
2. Learn the trinket.
3. Use the trinket.
2. Perform Blood Magic's Edge of the Hidden Realm ritual.
3. Enter the dungeon realm.
4. Break a block on the dungeon floor.
5. Fall into the void.

### Expected behaviour

To be teleported to overworld(or however the heck this trinket works).

### Additional information

Fix please. I can't even join my world now because of the infinite "Loading Terrain" screen.

**Comment by Raidobw2** [comment]
For the moment you can restore a backup from the `backups` folder and avoid using the Trinket again for the time being.

**Comment by Sunekaer** [comment]
Could you test if this is an issue on version 1.10.1 of the pack?
