### ISSUE TITLE
Game crashes sometimes on Teleport from far away 

### ISSUE THREAD

**Issue by VacShot** [FTBTeam/FTB-Modpack-Issues#4170]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Log Files

[crash-2023-11-04_22.52.21-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13257810/crash-2023-11-04_22.52.21-server.txt)

### Describe the bug

After Teleporting home (no matter which method I use) the game crashes.   

### Steps to reproduce

1. Travel a long distance (chunk of home not loaded in anymore)
2. Teleport Home (via Teleporter or waystone)
3. Game crashes after freezing

### Expected behaviour

Teleport me home without crashing

### Additional information

Changing the grafic setting doesn't change anything. Turning shaders on or off is also irrelevant.

**Comment by DinnerBeef** [comment]
Mod Issue: https://github.com/Team-EnderIO/EnderIO/issues/530 Looks like enderIO ME conduits are causing the issue, you can try and removing them and see what happens.
