### ISSUE TITLE
Productive Bees: Breeding Chamber Does not produce Radioactive Bees

### ISSUE THREAD

**Issue by MarkLKW** [FTBTeam/FTB-Modpack-Issues#4171]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Describe the bug

Putting an Iron Bee and a Cree-Bee into the Breeding Chamber shows the preview of a Radioactive Bee, but does not start progressing towards creating one, even with cages, flowers and energy provided.

### Steps to reproduce

1. Put an Iron Bee and a Cree-Bee into a Breeding Chamber
2. Provide power, flowers and a bee cage

### Expected behaviour

GUI should start displaying progress of the process once the conditions are met

**Comment by Medivha** [comment]
I did this just yesterday and did another right now to confirm again, and I don't have any problems breeding it.

Are your bees Adult's? Do the flowers get consumed?!(try tulips?!)

**Comment by MarkLKW** [comment]
Ah... I see my mistake... I went straight from making an Iron bee to a Radioactive one forgetting about the "child" phase.

**Comment by MarkLKW** [comment]
Ah I see the mistake, I went straight from making an Iron Bee to a Radioactive one, the Iron bee was a Child
