### ISSUE TITLE
Pedestals Chopper Upgrade don't break Nest from Productive Bees

### ISSUE THREAD

**Issue by Zonk1987** [FTBTeam/FTB-Modpack-Issues#4172]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Describe the bug

Pedestals Chopper Upgrade don't break Nest from Productive Bees of any Woodtype

### Steps to reproduce

1. Build a Woodfarm with Pedestals
2. Chopper Upgrade 40/40 Speed
3. Netherite Axe in the Pedestal
4. Define workarea

### Expected behaviour

Nests should be voided or somthing like that

### Screenshots

![Screenshot 2023-11-05 132343](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25836879/60da3720-5b9a-4f25-bb98-b48512f983cf)
![Screenshot 2023-11-05 132015](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25836879/c6ccc87c-6e5c-4aa9-84d1-a64728357e79)

**Comment by Skilles** [comment]
Since the nests are block entities I don't believe the pedestal will ever break them. Same thing with mining gadget

**Comment by Zonk1987** [comment]
I build a workaround for this with the Cyclic Miner and a Block Data Card in it. The Miner break the block what ever is in it.

**Comment by DinnerBeef** [comment]
It seems like it's working as intended. As hives are Block entities, you will have to break them some other way.
