### ISSUE TITLE
crush. a fatal error has occurred this connection is terminated

### ISSUE THREAD

**Issue by xImSkilzzz** [FTBTeam/FTB-Modpack-Issues#4174]
### Modpack

FTB Infinity Evolved 1.7

### Modpack version

1.17.10

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13259896/latest.log)

### Describe the bug

when I death or change dimension I have crush to menu.
1.shutting down internal server
2. a fatal error has occurred this connection is terminated

### Steps to reproduce

go to nether
crash to menu
enter in world and Im in nether
go out from nether
crash to menu
enter to world
im in overworld

### Expected behaviour

helping

### Screenshots

![Зображення 05 11 23 о 16 45](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/149951729/243d5e5e-6962-42e5-9609-2afc9f815ae2)

**Comment by Gaz492** [comment]
It looks like the witchery mod is running into errors, if you have any items from witchery in your I would suggest putting them in a chest then checking if the issue still happens for you.
If it does, you could try disabling the mod, however this would remove everything that it adds from your world so I would recommend creating a backup of your world if you do this.

Unfortunately, as this is a rather old modpack it's unlikely to receive any bug fixes.
