### ISSUE TITLE
Applied Mekanistics Autocrafting not working

### ISSUE THREAD

**Issue by crippie** [FTBTeam/FTB-Modpack-Issues#4176]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Describe the bug

Unable to use mekanism chemicals (gasses, pigments, slurries) in AE2 patterns for autocrafting. The mod page for Applied Mekanistics shows that you should be able to do this. But it doesn't seem to work. I tried to do any and all chemicals in a pattern, they wont click in, I cant drag them in, they just don't show up.

I can store all of these chemical types within an AE2 Chemical Storage Cell, but that seems to be all cant even get the chemicals out because I cant put them into the export bus interface.

### Steps to reproduce

1.) Set up a basic Applied Energistic system.
2.) Use a Pattern Encoding Terminal to make a pattern.
3.) Attempt to do one that has mekanism chemicals in its recipe. (Polonium pellet, Painting machine with pigment, etc.)
4.) Notice that the chemicals do not go into the pattern, any items, or fluids will, but not chemicals
5.) Try to drag the chemical from JEI into the pattern, notice it does not work
6.) Can repeat with other AE2 devices such as export and import busses

### Expected behaviour

Have the ability to use Mekanism Chemicals within AE2 patters and devices, as if they were a fluid. Such as the Applied Energistcis mod page shows.

### Screenshots

Mod page description showing chemical support, and stating support:

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97772673/d96bc190-7ce6-430f-a067-179bf36bce35)

Polonium pelet recipe tried to click in, only has item, and fluid, no chemical, also tried with pigment:

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97772673/1a040863-f2d2-4c84-9576-989f5e7e0941)

Chemical stored in AE2 system:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97772673/1590f60c-f5c8-43ca-8aed-9463e5120c47)

### Additional information

The applied mekanistics page does state, 1.18.2 in the description, but also shows its for game version 1.20.1 and is in the pack.

**Comment by lord-ne** [comment]
My guess is that this is a problem with *encoding* patterns, possibly a JEI issue. I'll see if I can find any workaround

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by Tiagssz** [comment]
so i was having a problem and i think its the same, this is the stupidest solution ever be ready.

press the **scroll whell** in the chemical craft request you want to do, it worked for me
