### ISSUE TITLE
Server Crash - Possibly related to Hyperbox and LaserIO

### ISSUE THREAD

**Issue by Frezo20** [FTBTeam/FTB-Modpack-Issues#4177]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Log Files

https://pastebin.com/99iZ18nV

### Describe the bug

I have one of the Hyperboxes set up for bees, and in it I have used one of the advanced connectors from LaserIO to take the items out. When I break the Hyperbox to move it from an old base to my new base, it crashes the server and makes it so that the server auto-crashes on my reentry, not just startup. I believe that it is an interaction between the Advanced connecter node being tied to specific dimension/coordinates and how the Hyperbox handles being moved. 

### Steps to reproduce

Create a LaserIO network in a Hyperbox.
Link it to another LaserIO network outside of the Hyperbox using the Advanced Node from LaserIO
Break the Hyperbox. 

If the item lands into the world, the server can not restart.
If the item lands in a player inventory than the server crashes on that player's entry.

### Expected behaviour

Pickup and move the Hyperbox to a new location.

### Additional information

There were about 20 Advanced Bee Houses and Bee Box extensions from Productive Bees, a Feral Flare lantern, and 4-5 Feed slabs from Productive Bees also in the box.

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by Frezo20** [comment]
Yes, I can confirm that this is still happening in the 1.9.1 version of the DireWolf20 1.20 pack, I have not yet updated to the 1.10.0 version of the pack to test it.

I have also found that it does not happen if the advanced connector from LaserIO is removed from the box. Doing so allows me to move the box with no crash, as well as if the advanced connector is present but not linked to another advanced connector outside of the hyperbox. The crash has only happened for me when an advanced connector is linked to another advanced connector that is outside of the box and then trying to move said box with the two linked.
