### ISSUE TITLE
Clay won't drop when mining with just hammers

### ISSUE THREAD

**Issue by Minspace32** [FTBTeam/FTB-Modpack-Issues#4179]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4

### Describe the bug

When mining clay at level -16 using a diamond just hammer Clay will not drop.  

### Steps to reproduce

mine clay with a Dimond hammer from just hammers

### Expected behaviour

Clay drops when mined

**Comment by DinnerBeef** [comment]
Thanks for reporting and issue, However this is working as indeed and will not be fixed.
