### ISSUE TITLE
Machines in Growthcraft not working

### ISSUE THREAD

**Issue by Wickedsrain** [FTBTeam/FTB-Modpack-Issues#4182]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Log Files

None created

### Describe the bug

None of the GrowthCraft machines will open an interface when right-clicked on. Specifically tested Fruit Press, Brewing Barrel. Tried Right clicking, just normal clicking. Nothing. 

### Steps to reproduce

1. Create the object. In this case for example the fruit press.
2. Shift click it to open UI. NOTHING HAPPENS
3. Click it normal to open UI nothing happens
4. Destroy it 
5. Recreate it
nothing happens

### Expected behaviour

When you click it, the UI should open to allow you to work with machine

### Additional information

Ive tried to get this to work almost every other day for a week. Something is clearly not working correctly.

**Comment by DinnerBeef** [comment]
Everything seems to be working fine for me. You can try shift clicking with an empty hand and letting me know what happens.

**Comment by Wickedsrain** [comment]
I tried that.. :( Several times. But for some reason it just doesnt work.
Ive tried it on different flooring: Wood, dirt, brick. right click left
click. :/ my partner tried too and nothing.

**Comment by natebc** [comment]
For the Fruit Presses, make sure you're not sending it a redstone signal {i.e. turn it off). I haven't checked the current pack version but this is how they worked for me a couple of weeks ago.

It's kinda like you can't stick your fingers in an operating Fruit Press? Feels janky but it might actually be on purpose.

**Comment by Wickedsrain** [comment]
Thanks for all the help. I do appreciate it. I wish that the site was up
to date on the recipes and how to make things, and how things work.

**Comment by DinnerBeef** [comment]
Seems like everything is fine now. Please reopen this issue if you are still experiencing this issue.
