### ISSUE TITLE
quick compress craft (default hotkey K) does not work with Cyclic crafting stick

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4184]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Describe the bug

I'm not sure which mod adds quick compress craft, but it doesn't work with Cyclic's crafting stick. I'm also not sure which mod is to blame, Cyclic or K crafting? I have noticed and reported various other issues with Cyclic, but without understanding the code, assuming I could, I'm not sure which mod is to blame for this incompatibility. A minor issue, to be sure, but it would be nice if this feature worked with the crafting stick, as it is an easy and excellent early game portable crafting tool.

### Steps to reproduce

1. Open Cyclic crafting stick
2. Press K on a stack of metal ingots.
3. Nothing happens.

### Expected behaviour

In the example of metal ingots, they should compress into blocks when K is pressed and ANY crafting table is open.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
