### ISSUE TITLE
Unable to place certain nuggets/bars into Cyclic Packager

### ISSUE THREAD

**Issue by QueenMelancholic** [FTBTeam/FTB-Modpack-Issues#4185]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Describe the bug

When attempting to place certain ore nuggets into a Cyclic Mod Packager several were unable to be placed into the input slot. When shift clicking them, they would default to the output slot. Pressing U on the Packager in TMI show that they should be valid and accepted items, even allowing me to click the "+" symbol to insert the nuggets (which also does not work).

The following ore nuggets i have noticed issues with:
- Copper
- Tin
- Zinc
- Osmium
- Silver
- Lead
- Calorite
- Ostrum
- Steel

_(not tested all nuggets, just those i had access to in-game)_
Further testing also revealed that Uranium, Lead, Tin, Silver and Zinc Bars also fail to be input, and again shift-click into the output slot.

### Steps to reproduce

1. Place a Cyclic mod Packager and ensure it is powered.
2. Attempt to insert any of the aforementioned ore nuggets as an input.
3. The Packager wont let it be placed in the input slot.
4. Attempt to shift click the item into the input slot
5. The item is input into the Packager Output slot instead.

### Expected behaviour

The Packager should accept all nuggets

**Comment by QueenMelancholic** [comment]
As a quick-fix solution if anyone else is having this or similar problems, Sophisticated Storage has an upgrade component that can perform a similar function with the Compacting Upgrade.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
