### ISSUE TITLE
FTB Genesis Server crash

### ISSUE THREAD

**Issue by Daenara** [FTBTeam/FTB-Modpack-Issues#4187]
### Modpack

Other...

### Modpack version

1.0.0

### Log Files

[crash-2023-11-08_23.25.34-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13301968/crash-2023-11-08_23.25.34-server.txt)

### Describe the bug

I was trying to get dirt, it didn't work with the water on the surface so I took the quest literally and dug down next to the pond. A few blocks in this crash happened, not sure if me digging was an issue, or something else.

### Steps to reproduce

I dug down, but I doubt that that caused the crash

### Expected behaviour

No crash

**Comment by TemporalWolf** [comment]
[crash-2023-11-08_15.47.17-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13302940/crash-2023-11-08_15.47.17-server.txt)
[crash-2023-11-08_17.53.11-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13302937/crash-2023-11-08_17.53.11-server.txt)
Similar crashes just walking around: first time almost immediately after loading my vault for the first time, walking towards the storage.
Second time walking out of simulation room.

**Comment by Saereth** [comment]
this may be fixed in the next update, we'll have to see if it works, will leave the issue open until we're sure
