### ISSUE TITLE
[Bug]: Inconsistent Plate and Gear Recipes

### ISSUE THREAD

**Issue by rmccarthy1504** [FTBTeam/FTB-Modpack-Issues#419]
### Modpack

FTB Ultimate Anniversary

### Modpack version

1.0.4

### Log Files

None

### Describe the bug

Some plates have 5 methods of crafting.
Most have less.
Brass has 1.

1. Ingot + Enigmatic Hammer in a crafting table
2. Ingot in a Roller machine (FTB IC)
3. Ingot in a metal press (IE)
4. Ingot in a multiservo Press (Thermal Series)
5. Ingot in a mechanical press (Create)

Iron, Gold and Copper, have all 5 methods
Diamond, Emerald, Aluminium, Silver, Lead, Nickel, Tin, Bronze, Constantan, Electrum, Steel, Invar, Signalum and Lumium have methods 1-4
Zinc has methods 1-3
Iridium, Sapphire, Ruby, Peridot has methods 1 and 2
Brass has method 2 only.

All plates should have all 5 methods available, to have a wider range of mods we can use for plate processing. Currently the only way to process all plates is to use the Roller machine from FTB IC.

### Steps to reproduce

Go to JEI
Check recipes for the different plates.

### Expected behaviour

All plates should have 5 methods to be produced.

### Screenshots
Iron has all 5 methods
![Iron has all 5 methods available](https://user-images.githubusercontent.com/68466998/144729454-53daf893-a934-44d9-9598-f1b301480888.png)
Brass only has 1
![Brass only has 1 method](https://user-images.githubusercontent.com/68466998/144729455-4432307c-23ee-4ac5-9692-3356778875a4.png)

**Comment by rmccarthy1504** [comment]
Going to add to this, as it's more recipes missing.

Gears can be made in 4 ways.
1. Manually crafted
2. In a Rolling machine (FTB IC)
3. On a metal press (IE)
4. In a Multiservo press (with gearworking die) (Thermal Series)

Zinc gears are missing recipes with multiservo press.
Brass gears are missing recipes 1,3 and 4

**Comment by Raidobw2** [comment]
Thank you
