### ISSUE TITLE
Aether Boss and Graves

### ISSUE THREAD

**Issue by Nites-Path** [FTBTeam/FTB-Modpack-Issues#4191]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.4.0

### Describe the bug

Death by Valkyrie Queen deletes graves and all items in it.

### Steps to reproduce

Death by Valkyrie Queen. When going back to death-site to look for grave it's gone; deleted by the Queens final blow.

### Expected behaviour

Grave to still be there upon death

**Comment by Nites-Path** [comment]
I'm not OP, but I can get the owner of the server to help with that. Is the command different when OP does it, or would I HAVE to be OP?

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you in the latest version of the modpack?
