### ISSUE TITLE
FTB Genesis | An error occurred while reading `cucumber-tags.json`

### ISSUE THREAD

**Issue by alppp** [FTBTeam/FTB-Modpack-Issues#4193]
### Modpack

FTB Genesis

### Modpack version

1.0.0

### Log Files

https://pste.ch/zobikagama.pl

### Describe the bug

I think title is self-explanatory

### Steps to reproduce

1. Install FTB Genesis from FTB Launcher
2. Launch the pack
3. Wait until is done 
4. Read the logs.

### Expected behaviour

No error reading the log.

### Additional information

I think there is a duplicate entry .
To fix it, just remove the `}e:ingots/brass": "null"` at end of the line at `cucumber-tags.json`

**Comment by Raidobw2** [comment]
Thanks for the report
