### ISSUE TITLE
FTB Genesis Rightclick interaction with seeds/ic2 crop seeds

### ISSUE THREAD

**Issue by Daenara** [FTBTeam/FTB-Modpack-Issues#4194]
### Modpack

Other...

### Modpack version

1.0.0

### Describe the bug

Early on I noticed I could not open the barrels when I had crop seeds or seeds in hand. As soon as I took them out, everything worked fine again. This is no game breaking bug, but it can lead to confusion, at least it did for me.

I tested:
Vanilla Minecraft:
- Wheat Seeds (white and green name)
- Beetroot Seeds (yellow and red name)
- Pumpkin Seeds
- Melon Seeds
- Birch Sapling

Supplementaries:
-  Flax Seed

Flower Seeds:
- Cyan Rose Seeds
- Orange Tulip Seeds
- Winter Succulent Seeds
- Oxeye Daisy Seeds

Farmers Delight:
- Rice
- Tomato Seeds

IC2 Classic:
- Hemp Seeds
- Crop Seeds (various)

Botania:
- Mutated Pasture Seeds
- Vivid Pasture Seeds
- Overgrowth Seed

Biomes 'O Plenty
- Rainbow Birch Sapling

Of all those things tested, only anything named a sapling and everything from botania let me open the barrel/chest. 

I am pretty sure that the pack somehow hooks into the right click event for those seeds to prevent them from being placed wherever we want, but it would be nice if it would let us still open inventories/guis still.

### Steps to reproduce

1. Take one of the affected seed items into your hand (wheat seeds for example)
2. Stand in front of an inventory (I used a barrel, chests are broken, too)
3. Try to open said inventory

### Expected behaviour

The inventory opens up

**Comment by Raidobw2** [comment]
Thanks for the report and the hint, we'll have a look at it
