### ISSUE TITLE
FTB Genesis some textures missing from Flower Seeds plants

### ISSUE THREAD

**Issue by bartu26** [FTBTeam/FTB-Modpack-Issues#4196]
### Modpack

Other...

### Modpack version

Genesis 1.0

### Describe the bug

Missing Texture of some flowers from the "Flower Seeds" Mod, during growth completly missing and when fully grown shown text "not installed".
![grafik](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/49201294/62511c31-0bed-4958-ae32-42e25ed01c1d)

- Cyan Tulip Seeds
- Silver Vase Flower Seeds
- Begonia Seeds
- Crocus Seeds
- Winter Succulent Seeds
- Yellow Daffodil Seeds

### Steps to reproduce

Plant the seeds found in the barrels from "Flower Seeds".

### Expected behaviour

Textures

**Comment by Saereth** [comment]
those seeds are for mods that arent in the pack, they will be removed in future versions of the vault but for existing vaults just throw them away

**Comment by Paxination** [comment]
What mods would that be?  maybe we could install them manually.
