### ISSUE TITLE
FTB Genesis - Steel Rod recipe is an uncraftable loop

### ISSUE THREAD

**Issue by Hanoverfist** [FTBTeam/FTB-Modpack-Issues#4197]
### Modpack

FTB Genesis

### Modpack version

1.0.0

### Describe the bug

It is currently impossible to make a Steel Rod as near as I can tell.

Steel Rod requires Lathe.
Lathe requires Aluminum Plate.
Aluminum Plate requires Metal Press.
Press requires Steel Rod.

So its not possible to make steel rods or the metal press or any related recipes.

Temp fix on my server was to make a recipe similar to other plates: IE hammer + Aluminum ingot = Aluminum Plate.

### Steps to reproduce

See above.

### Expected behaviour

Craft a Steel Rod.

**Comment by Saereth** [comment]
this is fixed in dev, the lathe should require aluminum ingots
