### ISSUE TITLE
FTB Genesis 1.0.0 - Quest reward

### ISSUE THREAD

**Issue by dcvinyou2day** [FTBTeam/FTB-Modpack-Issues#4198]
### Modpack

FTB Genesis

### Is your suggestion related to a problem? Please describe.

The quest RNGesus Take The Wheel. The quest reward contains 25/25/25 stickreed seeds. This seems a little OP and harder to keep going for something so early on. The rest of the quests in this area give 5/5/5 seeds. Even if they were 15/15/15 that would be better but the original reward makes  things more complicated than they should be this early on.

**Comment by Saereth** [comment]
I use that reward, and the very explicity warning that comes with them to help people understand the difficulty in keeping high tier plants alive. This is very much intended
