### ISSUE TITLE
Aetherslate Caves not generating

### ISSUE THREAD

**Issue by Asvand42** [FTBTeam/FTB-Modpack-Issues#4199]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.5.0

### Describe the bug

I’ve traveled over 100,000 blocks by now and have still yet to find an aetherslate cave in my server. I’ve used the /locatebiome command and it just says “can’t find within reasonable distance” and I’ve used the natures compass and it says “status, not found” every time I try both of them. 

### Steps to reproduce

Generate a world on direwolf20 1.20 version 1.5.0
Traveled over 100,000 blocks
Used /locate biome command and natures compass 
Still unable to find Aetherslate caves

### Expected behaviour

With the amount of distance I traveled I figured I would have found an aetherslate cave by now

**Comment by natebc** [comment]
This is intentional, 

See: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4165#issuecomment-1799400463
