### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by FrozenBenny** [FTBTeam/FTB-Modpack-Issues#42]
### Modpack

FTB Academy

### Modpack version

1.4.0

### Log Files

https://pastebin.com/GF4MtrBX

### Describe the bug

hello there, i am new to mods and modpacks in general and iv always wanted to try out feed the beast, i found this mod pack that basically teaches you how to use the mods, i wanted to try it out however it wound launch and it gives me an error of missing mods, when downloading the mod i had no errors of missing mods but when i launched the game it gives me the the errors (logs are on the pastebin link)

### Steps to reproduce

idk if there is a way to reproduce the bug, maybe its only on my side but what all i did was:

1. download the modpack
2. launched the mod 
3. then it just wont work 

### Expected behaviour

i was expecting for it to work so i could enjoy playing it

### Screenshots

https://gyazo.com/bf8eb78f224f21e6a3aad5df7280a7ad

https://gyazo.com/5babaeda459f2de820c3cd08a444be24

two screanshots of what i get when i try to launch the game

### Additional information

hope to get some help so i can start playing

**Comment by Raidobw2** [comment]
There's a bunch of missing and failed files from the download, e.g.:
```
[Client thread/ERROR] [FML]: Unable to read a class file correctly

MineTogether-1.12.2-2.3.9.jar - probably a corrupt zip
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

[FML]: Zip file MineTogether-1.12.2-2.3.9.jar failed to read properly, it will be ignored
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException
```

Can you do this in order and let me know after if it is resolved:

1. Uninstall FTB Academy 1.12
2. Close the FTB App for 10 seconds
3. Open the FTB App
4. Go straight to installing FTB Academy 1.12
5. Hit Play and reply here if it worked

**Comment by FrozenBenny** [comment]
Hey, the modpack is working now, thanks for the help
