### ISSUE TITLE
Bees Dying 

### ISSUE THREAD

**Issue by DiggityMan420** [FTBTeam/FTB-Modpack-Issues#4200]
### Modpack

FTB Genesis

### Modpack version

1.1.1

### Describe the bug

my bee farm all died on update i found a nest from a tree that I grew so i started a bee farm in a small room i made. breed up some bees. Then on the latest update(1.1.1) and now any new/old bee inworld ,spawned in bee or any bee in the overworld (in the vault area an out) are dying to wither. i didnt see anythin in the change log about it. if its intented ok  i see we get a bee place later on i was tryin to get a head start.

### Steps to reproduce

overworld vault
spawn bee or find nest
any bee in overwold dies 

### Expected behaviour

alive bees

### Screenshots

![Screenshot_8](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/3554cb01-06b7-4294-8d95-f0e2aa6a224b)

### Additional information

this maybe intented i just didnt see any in the updated change log and it killed my whole hive off i would of saved them in bee hives it i knew

**Comment by atealein** [comment]
I think the devs have mentioned it is intended. You can have the bees roaming around only within the simulation matrix. Outside of the matrix (even in the vault where you don't have radiation) they will wither away and die UNLESS you have them in the beehives with simulation upgrade, so they don't go out of the hive at all.

**Comment by DiggityMan420** [comment]
thx :)
