### ISSUE TITLE
unable to plant IC2 crops on Mystical Agriculture Farmland

### ISSUE THREAD

**Issue by yarma92** [FTBTeam/FTB-Modpack-Issues#4201]
### Modpack

FTB Genesis

### Modpack version

1.1.1

### Describe the bug

The inferium farmland quest says that the enhanced farmland (inferium farmland) should allow us to freely plant anywhere. Trying to plant IC2 cropsticks on this does not work, neither does trying to plant the seed regularly. Non-IC2 seeds/plants work without issue.

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2682099/680781a4-dd8a-490a-9e76-84bc019842b6)

### Steps to reproduce

1. Place down inferium farmland
2. Optionally hydrate next to water
3. Try to place IC2 cropsticks on, they will not plant. 
4. Try IC2 crops on the inferium farmland, they will not plant.
5. Try any other seed/plant, e.g. vanilla wheat seeds, they will plant. 

### Expected behaviour

Expected to be able to plant IC2 cropsticks and Crops on inferium farmland.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2682099/74d6b279-a45a-49d2-82ee-419a12f910b9)

**Comment by Saereth** [comment]
edited the quest to specify they dont work with cropsticks
