### ISSUE TITLE
Reactor Fuel Rod (reinforced) missing

### ISSUE THREAD

**Issue by markbogdan** [FTBTeam/FTB-Modpack-Issues#4203]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.5.0

### Describe the bug

Extreme Reactors's **Reactor Fuel Rod (reinforced)** is broken and no longer has a JEI recipe or for that matter presence in world or in storage systems. For now i've downgraded back to 1.4.0 and everything was reverted to normal without issues. Some of the other reinforced elements from extreme reactors seem to be fine (at least the ones i've checked : Casing, Glass, Controll Rod

### Steps to reproduce

1. Try to craft or view item in world or in refined storage.

### Expected behaviour

Being able to craft and have the block present in world.

**Comment by Nahkranoth0** [comment]
I've added a recipe in the recipes.zs in scripts folder:

`
craftingTable.addShaped("reinforced_reactorfuelrod", <item:bigreactors:reinforced_reactorfuelrod>, [
    [<tag:items:forge:ingots/steel>, <tag:items:forge:ingots/graphite>, <tag:items:forge:ingots/steel>],
    [<tag:items:forge:glass>, <tag:items:forge:ingots/uranium>, <tag:items:forge:glass>],
    [<tag:items:forge:ingots/steel>, <tag:items:forge:ingots/graphite>, <tag:items:forge:ingots/steel>]
]);`

**Comment by localzuk** [comment]
Can confirm this is an issue on my server as well. Can build all the other reinforced items but not the fuel rods.
