### ISSUE TITLE
Earth Source was not at the provided coordinates

### ISSUE THREAD

**Issue by Ratlanta** [FTBTeam/FTB-Modpack-Issues#4207]
### Modpack

FTB Genesis

### Modpack version

1.1.1

### Describe the bug

The Earth source was not at the provided coordinates and the quest also did not complete when arriving. 

### Steps to reproduce

Go to x:4 y:72 z:-447

### Expected behaviour

Earth Source should have been there or the quest should have marked as completed based on coordinates.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/59396659/8b34530d-57b4-4895-9458-cfc7467daec8)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/59396659/6c8c657c-80e0-421a-9f9e-f198450a79ff)

**Comment by Brettflan** [comment]
I had the exact same problem, that specific node (same coordinates) was not there and the quest therefore couldn't be completed. I ended up toggling editor mode on the quest and flagging it as complete to get past it.

However, despite AFAIK the world seed for this pack being the same for all players, my map looks different than yours there. The part to the south matches, but the northern part does not. Here's my map there (it wasn't bare stone in that spot originally, I dug down in case the node was somehow underground when I was looking for it):
![missing-node](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/592130/44e052b7-4ff6-4dcd-9216-65fcb3aa83d6)

**Comment by hawkeye0926** [comment]
I have the exact same problem, that specific node
