### ISSUE TITLE
[Bug]: Greenhouse Glass from Actually Additions doesn't work

### ISSUE THREAD

**Issue by Orichlol** [FTBTeam/FTB-Modpack-Issues#421]
### Modpack

Stoneblock 2

### Modpack version

1.16.1

### Describe the bug

Greenhouse Glass from Actually Additions can't work in this modpack.

No daytime.  No sky.

### Steps to reproduce

1. Make greenhouse glass
2. Try to use it

### Expected behaviour

I'd expect that it works.

**Comment by Raidobw2** [comment]
Hello. I've looked in ways to make that block work but there is no config and I doubt the mod author still updates the mod. It requires line of sight to the sky, and with a roof of bedrock it's not possible. I have removed Greenhouse Glass from JEI to avoid future confusion.
I encourage players to use other options to speed up crop growth as there as a ton. This will be closed once we release 1.22.
