### ISSUE TITLE
mass item dupe

### ISSUE THREAD

**Issue by demoniclords** [FTBTeam/FTB-Modpack-Issues#4210]
### Modpack

FTB Genesis

### Modpack version

1.1.1

### Describe the bug

using world save and explosions to dupe a large amount of items

### Steps to reproduce

get a chest and the creeper sense item from nameless trinkets
fill the chest with things to dupe
leave the world to save it then rejoin
blow up the chests 
kill the instance
re-launch your game
you will have all the chests and the items will have dropped

### Expected behaviour

items drop to the floor

### Screenshots

https://youtu.be/A1jqUF5s-r4

**Comment by Saereth** [comment]
I mean this sorta thing isnt something fixable from a pack point of view, you can accomplish the same thing a ton of ways with just pure vanilla. Your player data is written and you're killing the instance before it has a chance to save the chunks with the destroyed blocks. If people are willing to force a crash to dupe we cant really stop that.
