### ISSUE TITLE
Direwolf201.20 Mac V1.5.0.0 no launch

### ISSUE THREAD

**Issue by CorvidQueen** [FTBTeam/FTB-Modpack-Issues#4214]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.5.0.0

### Log Files

none available

### Describe the bug

I click to launch the instance and it validates everything up to client. crash on validating client, no log for console, latest, or crash.

### Steps to reproduce

1. Open modpack
2. click play
3. crash

### Expected behaviour

click play and load modpack

### Additional information

have tried deleting added mods, fresh instance, and manual java version selection.

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
