### ISSUE TITLE
extremely underwhelming heat exchangers

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4215]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.5.0

### Describe the bug

The heat exchanger in Advanced Generators is extremely slow, even with the max of 50 installed on one controller. Could this be adjusted in the configs? Also, the blocks are slow to break because they have "no tool" according to TOP and no wrench support.

### Steps to reproduce

1. Build a heat exchanger from Advanced Generators.
2. Feed it lava.
3. Observe very slow production of obsidian.

### Expected behaviour

This machine should produce obsidian MUCH faster.

**Comment by DinnerBeef** [comment]
Thanks for reporting and issue, However this is working as indeed and will not be fixed.
