### ISSUE TITLE
Advanced Peripherals descriptions cannot be viewed in JEI

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4218]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.5.0

### Describe the bug

I have tried adjusting the keybind to show description on these items as well, but nothing seems to work. I'm not sure if this is a bug with the mod itself or the control schema. Please look into it regardless.

### Steps to reproduce

1. Search "@advanced" in JEI to bring up these items.
2. Press indicated keybind in tooltip.
3. No response.

### Expected behaviour

The keybind to view these descriptions should work.

**Comment by eqagunn** [comment]
Any known workarounds?

**Comment by DinnerBeef** [comment]
Thanks for bringing this issue to our attention. However, this seems like a bug in the mod and due to some issues with mod loaders in this pack, we cannot update this mod at this time.
