### ISSUE TITLE
Factory Block Placer not placing logs when placed upside down

### ISSUE THREAD

**Issue by UltraGameCoder** [FTBTeam/FTB-Modpack-Issues#4219]
### Modpack

FTB Genesis

### Modpack version

1.1.1

### Describe the bug

The `Factory Block Placer` from the `Engineer's Decor` mod clears blocks it tries to place when the placer is facing downwards

### Steps to reproduce

1. Get a `Factory Block Placer` from the `Engineer's Decor` mod.
2. Fill it with 1x `birch log`
3. `Factory Block Placer`  removes the 1x `birch log` without placing it.

### Expected behaviour

A birch log to be placed

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25270207/157ae5d3-430a-4c82-bae3-aad7bb9c911a)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25270207/73e14201-a5ae-4c25-bcf9-01c6dc21c7b6)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25270207/6b7a6bec-5ca7-4f2c-8cf0-18313978179f)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25270207/9dfd0441-588a-43f5-8e5c-0a12cfe51faf)

**Comment by Saereth** [comment]
this is a mod issue that wont get fixed, the dev has archived the repo and isnt supporting it., I'd suggest just using a differnt block placer if you need that specific application.
