### ISSUE TITLE
[Bug]: FTB Teams Invite on FTB Ultimate Anniversary, appears as if the invitee invited themselves

### ISSUE THREAD

**Issue by rmccarthy1504** [FTBTeam/FTB-Modpack-Issues#422]
### Modpack

FTB Ultimate Anniversary

### Modpack version

1.0.4

### Log Files

None

### Describe the bug

I invite WindsOfChaos to my party, and when receiving the invite, the text reads as if they invited themselves to my party.

### Steps to reproduce

Invite user to party.
Received invite does not say it's from you, but from themselves instead.
Screenshot attached shows this.

### Expected behaviour

Invite would state who it was from correctly.

### Screenshots

From WindsOfChaos's perspective (receiving an invite from me)
![FTB Teams Issue](https://user-images.githubusercontent.com/68466998/144751347-b1e33342-f544-4cff-8f8c-740fefc2bda0.png)

From my perspective (sending the invite)
![FTB Teams Issue2](https://user-images.githubusercontent.com/68466998/144751320-ac17f8b0-e9a1-4043-b5bd-eeb3f9dd381c.png)

**Comment by Raidobw2** [comment]
Issue created for the mod at FTBTeam/FTB-Mods-Issues#136

**Comment by Raidobw2** [comment]
Fixed in-dev at FTBTeam/FTB-Teams@2de1b6c by LatvianModder, thank you!
