### ISSUE TITLE
Genesis Quest reset sets world to permanent Adventure Mode

### ISSUE THREAD

**Issue by QahnaarinOrigin** [FTBTeam/FTB-Modpack-Issues#4220]
### Modpack

FTB Genesis

### Modpack version

1.5.15

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13328986/debug.log)

[debug-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13328987/debug-1.log.gz)

### Describe the bug

Similar to ticket #3282 where interacting was not possible and ALL quests were reset. I even tried the force complete command to push past the first 2 quests and nothing happened for progression. Still couldn't interact with objects or mobs, but can be attacked by them. I had the same quest reset issue with Stoneblock 3, but that resolved itself and I got all the rewards again to the point where I left off. This time, the quests won't resolve itself.

After closing the game, the FTB app showed there was an error while the game was loading/running.

I don't know where to find the link for my log file, but the two files I've uploaded are about all I can provide.

Photos attached show progress, show quest reset and all attempts to interact with objects.

I even tried starting a new world and the first quest does not register completion after triggering the console explosion when interacting with it.

Seems like the game is set to a permanent Adventure Mode no matter which mode is selected for play. Quests cannot progress as expected when first quest does not trigger.

I even re-downloaded the game (after dropping the logs above) in case the force complete command carried over to the new world and the issue persists. First quest refuses to trigger...

### Steps to reproduce

1. Play game (I stopped after setting down the Waypoint)
2. Log off
3. Enter game next day
4. Starting quest table reset

There really isn't much to the steps. Hopefully the log will shine some light...

5. Uninstall and re-install modpack
6. Start new game
7. Initial quest does not trigger
8. Cannot delete modpack 2nd time; waiting for response from agent

### Expected behaviour

Log in and pick up where my quests were left off

### Screenshots

![20231112_112536](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150618167/b3a4a022-deef-473d-9281-224872e79863)
![20231112_112448](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150618167/ced7afa0-e407-4074-bb8d-65dac02df7c3)
![20231112_112422](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150618167/9351629f-8218-4840-8140-78300d1d4304)
![20231112_112304](https://github.com/FTBTeam/
![20231112_112253](https://github.com/FT
![20231112_112218](https://github.com/FTBT
![20231112_112145](https://github.com
![20231112_112017](https://github.co
![20231112_112002](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150618167/65f0bbb8-2685-4bd4-87f1-4522b8203cf5)
m/FTBTe
![20231112_112008](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150618167/0234773d-ad6d-4797-a3f8-e7d5ebaea9a0)
am/FTB-Modpack-Issues/assets/150618167/e6e5acb6-af1d-447e-96d4-03128d46b05a)

![20231112_112036](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150618167/6df03775-8303-4dbd-92af-f3d4a23f05b6)
/FTBTeam/FTB-Modpack-Issues/assets/150618167/38f28841-5b43-4ab5-8e0c-73b80219bd79)
![20231112_112110](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150618167/5ceca7eb-1495-48a5-ac80-114f025c1727)

![20231112_112123](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150618167/018a1d0b-ca9d-47f6-9bb2-0590f6dcb94e)

eam/FTB-Modpack-Issues/assets/150618167/14cfef5e-8786-4594-8f06-cc503152c83a)
BT
![20231112_112209](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150618167/3a8c44d9-0c6a-4c24-b719-2fe5c81dc721)

![20231112_112213](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150618167/ad51ab17-2014-4fd9-b9e7-b03a8897c4b9)

![20231112_112229](https://github.com/FTB
![20231112_111901](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150618167/8f52c6fb-a988-40c8-a2dd-7d507db3b588)
Team/FTB-Modpack-Issues/assets/150618167/13b5ec79-c876-4680-af15-44aa6404c2b0)
eam/FTB-Modpack-Issues/assets/150618167/ca929f4a-2765-422b-aee8-bd903a87f169)
FTB-Modpack-Issues/assets/150618167/1eeab27f-a65f-4b8d-aa25-e5228b42cc59)

**Comment by Saereth** [comment]
you have a couple different issues at play here causing you issue, the quest not completing is a bug which is fuxed next update and I believe the forge update coming with it will fix the other issue. If you have problems after the update follow up with us here please
