### ISSUE TITLE
FTB Genesis - IC2 Aluminum dust 

### ISSUE THREAD

**Issue by cpeake9** [FTBTeam/FTB-Modpack-Issues#4222]
### Modpack

FTB Genesis

### Modpack version

1.0.0

### Describe the bug

Nether aluminum ore drops Raw Aluminum, though this is not viewable in JEI it is smelted normally or processed further, though it cannot be macerated with electrodynamics like other ores.
Alum plants from IC2 drop IC2 Aluminium Dust which requires an alloy smelter and cannot be smelted normally.

Not sure which is meant to be the intended way of things, just figure it should be unified.

### Steps to reproduce

Harvest an alum plant and attempt to smelt it into aluminium.
vs 
Mine an aluminum ore and smelt it directly into aluminium.

### Expected behaviour

IC2 Aluminium dust smeltable without alloy smelter.

**Comment by pgmtags** [comment]
Sorry, if it is fixed, can you explain how to melt aluminium?

From the presented solutions nothing works
