### ISSUE TITLE
fail to load ftb stoneblock 3 world

### ISSUE THREAD

**Issue by tking26** [FTBTeam/FTB-Modpack-Issues#4224]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Log Files

[16:14:05] [spark-java-sampler-0-5/WARN] [spark/]: Timed out waiting for world statistics

### Describe the bug

it takes over 5 min to load my world and the server never updates or is updating but i cant use my refined storage and after 10 minutes i cant do anything and the program is crashing and i have to force close the program

### Steps to reproduce

1. go to the ftb stoneblock 3 mod
2. load my map in stoneblock 3 and this bug will accure 
3. the bug will accure every minute 

### Expected behaviour

there should not be this bug comin up and the world normaly updates all the time 

### Additional information

its only in the world i played very much in

**Comment by UnRealDinnerbone** [comment]
Please upload the full log file
