### ISSUE TITLE
Ars ritual Summon Wilden Chimera inside hyperbox deletes bedrock

### ISSUE THREAD

**Issue by Dracos99** [FTBTeam/FTB-Modpack-Issues#4225]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.5.0

### Describe the bug

When using the Ars Ritual Brazier to perform the summon wilden with the added components for the Wilden Chimera, the blast from the summoning deletes the bedrock walls of the hyperbox

### Steps to reproduce

1. create/enter hyperbox
2. place a ritual brazier offset near one of the corners
3. place ritual tablet on it
4. chuck in the 3 wilden parts
5. click the brazier to start the ritual
6. boom!

### Expected behaviour

Bedrock should not be breakable by the ritual

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/46051093/21555cc0-24ab-41dc-8998-166a73666444)

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you in the latest version of the modpack?
