### ISSUE TITLE
FTB Genesis Pressure Chamber Mixed Metal recipe

### ISSUE THREAD

**Issue by cpeake9** [FTBTeam/FTB-Modpack-Issues#4226]
### Modpack

FTB Genesis

### Modpack version

1.1.1

### Describe the bug

Mixed Metal Ingot recipie in pressure chamber only accepts mekanism bronze.

### Steps to reproduce

Attempt to insert IC2 bronze into pressure chamber for mixed metal ingot recipe, IC2 bronze will not be accepted.

### Expected behaviour

Accepts any type of bronze.

**Comment by Saereth** [comment]
all bronze should unify now in the new update to mekanism bronze, if you have any remaining ic2 bronze you'll be able to grind it down to dust and resmelt for mekanism ingots
