### ISSUE TITLE
[Bug]: see though blocks with nether coal ore

### ISSUE THREAD

**Issue by Steftast1c** [FTBTeam/FTB-Modpack-Issues#423]
### Modpack

ftb ultimate anniversary

### Modpack version

1.04

### Describe the bug

when in the nether you can see though the coal ore block and see other ores

### Steps to reproduce

go to the nether
find coal ore
look at it, 
you can likely see other ores around it

### Expected behaviour

shouldnt be able to see other items though it

### Screenshots

[https://imgur.com/yhGfyQb](url)

**Comment by rmccarthy1504** [comment]
I'm afraid I don't get the same.

![image](https://user-images.githubusercontent.com/68466998/144752754-50aa13e2-0d6f-475d-b10d-35a00be6be30.png)

**Comment by Steftast1c** [comment]
figured out the issue, its the fabulous graphics setting using a rtx 3080ti should of thought about any settings changes before posting

**Comment by Sunekaer** [comment]
For modded don't use over Fancy
