### ISSUE TITLE
Baubley Heart Canisters are unusable

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4230]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.6.0

### Describe the bug

Baubley Heart Canisters cannot be inserted into any curio slots and are thus unusable except in the Vitality Blade.

### Steps to reproduce

1. Craft a heart canister.
2. Go to curios.
3. Item does not fit in any slots.

### Expected behaviour

Baubley Heart Canisters should be usable.

**Comment by ItsAvyy** [comment]
Afaik you have to place the canisters into the Heart Amulet, which does have a Curio slot.

**Comment by jlp1528** [comment]
Thank you for the information. That wasn't immediately clear.
