### ISSUE TITLE
Attempting to restock Sophisticated Backpack from claimed Lootr chest causes crash

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#4232]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.13.1

### Log Files

https://pste.ch/alasonukol

### Describe the bug

while in DimDungeons, I attempted to flip on the Restock upgrade in my Sophisticated backpack after noting a Lootr chest I had opened was full of glass blocks/panes, and right clicked the previously-opened chest with the backpack and instantly crashed 

### Steps to reproduce

1. have sophisticated backpack with advanced restock upgrade with ~~no filters set~~ 
2. find a Lootr chest and open it
3. check backpack to make sure restock upgrade is active
4. shift right click the chest to attempt to fill the backpack with the contents of the chest

### Expected behaviour

backpack grabs all contents of chest into itself

### Screenshots

![2023-11-13_23 25 17](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1612570/87bdecc3-f006-400b-8faf-f1d6f99c3ef9)
![2023-11-13_23 25 12](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1612570/3d1847f1-8a74-4d32-9c43-c625765834d7)
![2023-11-13_23 25 02](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1612570/8f8eef86-8303-4bfd-ae8d-773d07333e71)

### Additional information

.. correction, it DID have a filter, and it was set to `forge:ores`, so technically it shouldn't have been able to extract anything from the chest anyway

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?

**Comment by WebDragon** [comment]
I need to restore a backup from an old laptop to test this in the world I had been experiencing it with, after I update to current release once the backup worldsave has been moved to the new laptop.  Please bear with.
