### ISSUE TITLE
(Pedestals Mod) Planter Pedestal with Work Area card gets stuck on any block

### ISSUE THREAD

**Issue by Drocks135** [FTBTeam/FTB-Modpack-Issues#4234]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.6.0

### Describe the bug

Every time a pedestal with the planter upgrade hits a block that it can not place operations completely halt until the block becomes available to place on. I tested this with both wheat seeds and saplings and got the same result. This seems to include any block, sapling seed etc... that blocks the planting from happening.

### Steps to reproduce

1. Start with a pedestal and a planter upgrade from the pedestals mod, a WorkCard (Area) from the MowLib mod, and a stack of saplings.

2. Place the pedestal down, and imagine a line 5 long centered in front of it. (Image attached in screen shot to show the set up)
   
3. Place saplings at positions 1, 3 and 5.

4. Sneak right click with the work card on sapling one and then on sapling 5.

5. Off hand the work card and right click the pedestal, Off hand the planter upgrade and right click the pedestal

6. Main hand the saplings and right click the pedestal to place them on top

At this point no operation will start because the work card starts at slot 1 and there is a sapling blocking the way

7. Break sapling at position 1

At this point the planter will place saplings at Positions 1 and 2

8. Break sapling at position 3

At this point the planter will place saplings at position 3 and 4

At this point the planter is looking at position 5, breaking any sapling except for the one on position 5 will result in nothing happening. The planter will only continue operation once it can plant at position 5 and which it resets to position 1 and has the same issue.

### Expected behaviour

Upon not being able to complete a plant operation, the pedestal should skip the position and carry on. This is how the harvest upgrade works.

### Screenshots

Initial Setup for visualization

![InitialSetup](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25653377/6557b644-70e1-4699-8be7-2a1f88c68e81)

Work Area

![WorkArea](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25653377/1ddcf5cf-6fce-45ff-8bf3-e074bfce4528)

**Comment by Mowmaster** [comment]
Fixed in 1.19, a fix for 1.20+ is coming

**Comment by DinnerBeef** [comment]
The mod dev has said this issue has been resolved. The latest updates should include this fix, please reopen this issue if it's still happening for you.
