### ISSUE TITLE
Mekansim GUI Broken (Hotfix?!)

### ISSUE THREAD

**Issue by Medivha** [FTBTeam/FTB-Modpack-Issues#4236]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.6.0

### Describe the bug

UI Broken in Mekansim

![javaw_2023-11-14_19-26-38](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/16429350/f86e69e6-1ee7-4cd8-9c0b-25e6d2a1f58c)

depending on what gui scale it gets worse ;)

### Steps to reproduce

install 1.6.0
open any Mekanism Maschine UI

### Expected behaviour

Ui elements on the correct place

### Additional information

there is already a fix for it according to https://github.com/mekanism/Mekanism/issues/7924

maybe bring out a hotfix for the pack

**Comment by jlp1528** [comment]
Can confirm this bug.

**Comment by ligerzero459** [comment]
Also confirming

**Comment by Medivha** [comment]
fixed in 1.7.0
