### ISSUE TITLE
Can't find Aetherslate cave anywhere

### ISSUE THREAD

**Issue by Kopassium** [FTBTeam/FTB-Modpack-Issues#4238]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.6.0

### Describe the bug

I'm aware that Aethersteel was fixed due to the massive world gen issue it had, I deleted my release world because the overabundance of diamonds was not fun for me. But I'm at a point now where I'd like to try out Aethersteel and I can't find a cave anywhere, I got Nature's Compass no luck, doesn't detect one. I tried making a test world and teleported tens of thousands of blocks using the locate biome command and no luck.

### Steps to reproduce

1.Create new world and us locate biome command to find Aetherslate cave.
2. No cave.
3. Or I'm unrealistically unlucky.

### Expected behaviour

Existing cave.

**Comment by Medivha** [comment]
#4165
