### ISSUE TITLE
[Bug]: Missing sulfur gem to dust recipes on Uni 1.16

### ISSUE THREAD

**Issue by douyabian** [FTBTeam/FTB-Modpack-Issues#424]
### Modpack

FTB University 1.16

### Modpack version

1.3.0

### Describe the bug

You get sulfur gems from processing sulfur ore, but there seems to be a lack of processing recipes to convert sulfur gems to sulfur dust other than with the blast charge

### Steps to reproduce

Smelt/crush sulfur ore to get sulfur gem
No other ways of further processing it with machines into dust

### Expected behaviour

Being able to use crusher from mekanism/IE/create to crush sulfur gems into dust 

### Additional information

Might be due to the lack of pulverizers which would be the inituitive way of getting sulfur dust

**Comment by aaronhowser1** [comment]
Fixed for next update
