### ISSUE TITLE
Crash when trying to add server by IP

### ISSUE THREAD

**Issue by mexmer** [FTBTeam/FTB-Modpack-Issues#4240]
### Modpack

FTB Genesis

### Modpack version

1.1.1

### Log Files

[crash-2023-11-14_20.47.40-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13355446/crash-2023-11-14_20.47.40-client.txt)

### Describe the bug

game crashes when entering server ip with numpad

### Steps to reproduce

start game
go to multiplayer
click add server or direct connection
start typing server IP on numeric pad
game crashes after entering first or second number

### Expected behaviour

game should not crash

### Additional information

entering numbers on normal keyboard (eg. top row) doesn't crash game.
using numpad to enter numbers ingame (for example in chat, or entering ammounts) doesn't crash game.

**Comment by Saereth** [comment]
this is a bug in placebo, shadows is aware of it but hasnt published a fix yet, as a work around just unbind the patreon trails effect hotkeys, 8 and 9 are bound by default which are used often in IP addresses :p
