### ISSUE TITLE
light levels reset in simulation matrix

### ISSUE THREAD

**Issue by vizzair** [FTBTeam/FTB-Modpack-Issues#4242]
### Modpack

FTB Genesis

### Modpack version

1.1.1

### Describe the bug

if you create a dark room in the farm simulation, ie completely dark, when you unload and reload the simulation the light levels in the dark area are reset to full brightness.
light levels on crop sticks change from 5 or 6 to 12 or more, causing problems breeding redwheat.

### Steps to reproduce

activate the light level display (f7)
build a simple hollow cube in the farm simulation
enter the cube and close all openings, you will see the red crosses show 0 light levels
exit the cube
unload and reload the simulation
go back to the cube , enter and close all openings
now there are no crosses display and it is in full brightness instead of full darkness.

### Expected behaviour

expect the dark areas to remain in the dark

**Comment by Saereth** [comment]
there is a button on the spatial io that force a lighting update, sometimes you have to use it a couple times but it will eventually do it. this is unfortuantely an artifact with the spatial IO system and is something AE2 would have to fix more thoroughly so this is all we can offer as a pack work around.
