### ISSUE TITLE
Redstone Comparator Missing Recipe on V1.6.0

### ISSUE THREAD

**Issue by Spencer0014** [FTBTeam/FTB-Modpack-Issues#4246]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.6.0

### Describe the bug

Redstone Comparator recipe is missing in JEI. Unable to craft using JEI or through manual methods

### Steps to reproduce

Attempt to craft a redstone comparator

### Expected behaviour

see recipe and craft item

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150972669/046573f8-320c-4a96-98f0-e8f322dfb9ee)

**Comment by Medivha** [comment]
Can you restart (complete restart server/game) your game and confirm again? I can craft it with all 3. Nether Quartz, Certus Quartz Crystal and Charged Certus Quartz Crystal and different stone types.

Sometimes some recipes goes missing and restart helps (nobody have a clue yet what it causes)

![javaw_2023-11-16_02-11-51](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/16429350/4b63e7f3-8478-45fc-8558-7c8570cd6a18)

**Comment by Spencer0014** [comment]
I just completed a full restart as requested and still experiencing the same issue as reported. 

As a side note, I have added three mods to the pack :
Ars Elemental - v1.20.1-0.6.2.2
Immersive Engineering - v1.20.1-10.0.0-169
Tree Harvester - v1.20.1-8.2

However, I had these 3 mods installed on previous versions of the Direwolf20 1.20 pack without issue and do not see any of these affecting the recipe for a comparator in the 1.6.0 version of the pack. I did not update the 3 mods when updating the modpack from what was used on the previous versions, nor have I tested if updating these 3 mods changes the issue. Just including this note for full transparency. 

I also attempted creating a new test world to see if the issue was repeatable in it. Same issue in new world.

If no one else is experiencing this issue though then I suppose I can assume it is a bug in my specific instance and chalk it up to the general wonkiness of modded Minecraft!

**Comment by Medivha** [comment]
For sure, this is a weird one. It's a vanilla recipe, so how does it get broken? I guess you tested a new world in the same instance. So you could test a new instance. And if it works, to back up your world and copy it to the new instance. Maybe on the update to 1.6.0 something got broken. I don't think it is because of your added mods. 
Maybe someone else has another idea.

**Comment by DinnerBeef** [comment]
Did you change scripts? The recipe in the pack was changed to only use AE2 which makes the recipe use tags. However, that was removed from the mod, so I added it back.

**Comment by runichardt** [comment]
I have been looking for hours for another post to avoid commenting here but can not find any other posts or information about this other than this thread and one other closed thread that says it was fixed in dev. However, this is still an issue in version 1.11.0 of the pack; even with a brand new instance downloaded.

**Comment by Spencer0014** [comment]
The issue I listed above was never fixed. I had just cheated in some comparators and moved on as aside from that one missing recipe the issue did not affect gameplay and I didn’t want to waste time trying to figure it out if only I was having the issue.

**Comment by runichardt** [comment]
> The issue I listed above was never fixed. I had just cheated in some comparators and moved on as aside from that one missing recipe the issue did not affect gameplay and I didn’t want to waste time trying to figure it out if only I was having the issue.



> I have been looking for hours for another post to avoid commenting here but can not find any other posts or information about this other than this thread and one other closed thread that says it was fixed in dev. However, this is still an issue in version 1.11.0 of the pack; even with a brand new instance downloaded.

For anyone interested I was able to fix it for myself and here's how:

Go to [your dw20 instance location]\kubejs\server_scripts\

make a new script fixmissing.js using a text editor (you can name it something else if you'd like).

Copy and post the following code:
`// priority: 1000

ServerEvents.recipes(event => 
{
	
	// Change recipes here
	event.shaped(
		Item.of('minecraft:comparator',1),
		[
			' A ',
			'ABA',
			'CCC'
		],
		{
			A: 'minecraft:redstone_torch',
			B: 'minecraft:quartz',
			C: 'minecraft:stone'
	
		}
	)	
	event.shaped(
		Item.of('minecraft:daylight_detector',1),
		[
			'GGG',
			'QQQ',
			'SSS'
		],
		{
			G: 'minecraft:glass',
			Q: 'minecraft:quartz',
			S: 'minecraft:oak_slab'
	
		}
	
	)
})
`

Then you can either relaunch the entire instance or use the following commands while in game: /kubejs reload server_scripts 
then /reload.

**Comment by Muir6401** [comment]
I have found a fix within kubejs/server_scripts/recipie_removals.js - Both minecraft:comparator and minecraft:daylight_detector were in there along with a few others in which I had to remove to make some items craftable again. I have attached my fixed file (in a zip as github doesnt support .js files)  if you dont want to edit it yourself just move and replace my one in. (this is not a definitive fix for everyone as it still has mods with recipies removed but I havent had a use for those yet so cannot comment if any issues)
[recipe_removals.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14719380/recipe_removals.zip)
