### ISSUE TITLE
Sweeping Edge and Riptide books are the same recipe in the EnderIO Enchanter

### ISSUE THREAD

**Issue by ligerzero459** [FTBTeam/FTB-Modpack-Issues#4248]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.6.0

### Describe the bug

The recipes for the Sweeping Edge book and the Riptide book are the exact same recipe in Enchanter: iron ingots and lapis. It defaults to Riptide because of this with no way to craft the Sweeping Edge book

### Steps to reproduce

1. Check the recipes for Sweeping Edge and Riptide, see they're the same
2. Try to craft Sweeping Edge in Enchanter, should default to Riptide with no way to change

### Expected behaviour

Recipes should be different so both can be crafted

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1093351/639b79b2-7d09-4272-9a8c-7e5470bc2967)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1093351/27371471-e409-45c8-b8fb-c0e32b801c43)

**Comment by DinnerBeef** [comment]
https://github.com/Team-EnderIO/EnderIO/issues/358
The issue has been reported to the mod dev. The mod will be updated if the issue is resolved.
