### ISSUE TITLE
Draconic bees are not producing products

### ISSUE THREAD

**Issue by RikHov** [FTBTeam/FTB-Modpack-Issues#4255]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.6.0

### Log Files

No logs

### Describe the bug

The draconic bees will not produce any products. I have tried with an advanced hive in the overworld and a dragonegg nest in the end. Dragoneggs have been tried: next to the hive, 2 block from the hive, next to the hive but one block lower, 2 blocks from the hive but one block lower and an entire floor of dragoneggs. 

### Steps to reproduce

1. Place advanced hive in the overworld or dragon egg hive in the end
2. Place expansion box on top of advanced hive
3. Place dragonegg near the hive
4. Place draconic bees in the hive
5. Wait

### Expected behaviour

The draconic bees will start producing combs

### Screenshots

![Dragonegg_floor](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/112859731/f578192f-42ee-4923-a778-5ba697071b39)
![Overworld](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/112859731/5064a528-92c5-41e4-b60f-9fd4988e1937)
![Overworld2](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/112859731/f3abf4e5-e5c6-44fb-87d5-50e14e758e1a)
![The_End](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/112859731/8b43ac7a-5d42-42cd-b3f7-1d0815889d69)
![The_End_more_eggs](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/112859731/1758abb1-59cc-4007-8b45-6e9afad66091)

### Additional information

In the discord other people have it working like mine is setup. All the other bees work fine.

**Comment by Linux123123** [comment]
How did you solve your issue?
