### ISSUE TITLE
Mekanism gas and fluid buffers not visible on The One Probe panel

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4256]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.6.0

### Describe the bug

I'm not sure whether this is Mekanism's or TOP's fault, but gas and fluid buffers in pressurized tubes and mechanical pipes, respectively, do not show up.

### Steps to reproduce

1. Fill a pressurized tube with gas or mechanical pipe with fluid.
2. Look at the tube/pipe.
3. Buffer not visible in TOP panel

### Expected behaviour

Gas and fluid buffers should be visible.

### Screenshots

![2023-11-16_16 07 05](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1498260/908e2a85-d697-4f78-87f5-aab697f8970a)
oxygen
![2023-11-16_16 08 31](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1498260/cf71bf0a-0e89-4ebd-8524-36ceb1ceb944)
water

### Additional information

Energy buffers are working fine.
![2023-11-16_16 10 35](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1498260/c567073b-54ab-4bdb-acda-d0a7bfada0cd)

**Comment by g45635g** [comment]
Pretty certain TOP is set to require a Probe to see this information by default in this pack, so if you haven't already, you would need to either craft one or type /top need, and set to Not Needed

**Comment by jlp1528** [comment]
I have already investigated this and it did not resolve the issue.

**Comment by g45635g** [comment]
> I have already investigated this and it did not resolve the issue.

Beats me then, I've been playing the pack for the past 2 days and fixed this same issue that way. Hopefully you find your answer soon

**Comment by Medivha** [comment]
Contents are set in the config to extended, so you have to sneak to see it(or build "the one probe" and point at it). instance->config->theoneprobe-client.toml

Maybe [g45635g](https://github.com/g45635g) operates on admin level and could change it in game, and therefore it overrides it. But a lot don't play with these rights, so it doesn't change it?! I don't know.

**Comment by jlp1528** [comment]
The actual item works so I guess I'll close this
