### ISSUE TITLE
Using "sort inventory" feature while in Curios menu deletes items

### ISSUE THREAD

**Issue by Famish3d** [FTBTeam/FTB-Modpack-Issues#4258]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.6.0

### Describe the bug

I hovered my cursor over an inventory slot in the curios menu whilst pressing my "middle mouse button" activated the sorting inventory feature. The aftermath are the items are arranged but deleted and/or becoming unreachable.

Note: I do hear the sound activating maybe from "sophisticated backpacks" as if an item is being picked up. (No items are in any backpacks)
Note 2: I have the advanced pickup upgrade on multiple backpacks in my inventory including one in my "back" curios slot 
Note 3: Items are still deleted/arranged even with removal of "sophisticated backpacks" from inventory

### Steps to reproduce

1. Click Curios Sub-Menu
2. Hover Cursor over any inventory slot
3. Press middle mouse button "inventory sorting feature"

### Expected behaviour

I expected it to move the items to the closest counterpartner, or remove all the items and put them in my inventory.or take the items from my inventory and fill the corresponding slots.

**Comment by Medivha** [comment]
same as #4148 

you can do with the command(stated in the reference) or have to add it to the config to the blacklist(preferable from the pack author per update)

this is what i have in my config (instance->saves->World Name->serverconfig-> inventorysorter-server.toml)

No guarantee that this works or cause some harm, ;) use it on your own risk (maybe backup) or just wait for an update on it and don't use the sorting in the curio tab ;)

```
#Inventory sorter blacklists
[blacklists]
	#Container blacklist
	containerBlacklist = ["l2tabs:curios", "curios:curios_container", "productivebees:advanced_beehive"]
	#Slot type blacklist
	slotBlacklist = ["com.enderio.machines.common.menu.MachineSlot", "net.p3pp3rf1y.sophisticatedcore.upgrades.FilterLogicContainer$FilterLogicSlot", "net.p3pp3rf1y.sophisticatedcore.common.gui.SlotSuppliedHandler", "net.p3pp3rf1y.sophisticatedcore.common.gui.FilterSlotItemHandler", "com.enderio.machines.common.menu.EnchanterMenu$EnchanterOutputMachineSlot", "com.enderio.machines.common.menu.GhostMachineSlot", "net.p3pp3rf1y.sophisticatedcore.common.gui.StorageInventorySlot", "com.enderio.machines.common.menu.PreviewMachineSlot", "net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase$StorageUpgradeSlot"]

```

**Comment by Quest79** [comment]
*tumbleweed*
