### ISSUE TITLE
[Bug]: Auto-hammers internal buffer is too big

### ISSUE THREAD

**Issue by iammael** [FTBTeam/FTB-Modpack-Issues#426]
### Modpack

FTB OceanBlock

### Modpack version

1.9.0

### Describe the bug

The FTB Sluice's Auto-Hammers have a huge internal output buffer (+100k blocks and growing after a few days for me).

This is very bad for plenty of reasons and especially on servers since when you break them they will spill all the items on the ground and potentially cause lag/FPS drops.

### Steps to reproduce

1. Use auto-hammers for a little while
2. Observe with TOP that they have a huge internal buffer

### Expected behaviour

The auto-hammers should have no internal buffer or a small one

### Screenshots

![2021-12-06_03 33 49](https://user-images.githubusercontent.com/7931135/144778961-41979806-8d7b-4e04-9bf8-c486999ef49b.png)

**Comment by Sunekaer** [comment]
should be better in 1.10.0
