### ISSUE TITLE
Duplicating Tin with 30K Coolant Cells

### ISSUE THREAD

**Issue by Jhuang79** [FTBTeam/FTB-Modpack-Issues#4260]
### Modpack

FTB Genesis

### Modpack version

1.1.1

### Describe the bug

Crafting 30k coolant cells with modular storage duplicates tin.

### Steps to reproduce

1. Have some tin and water cells
2. Open modular storage
3. Use JEI to pull up 30k coolant cell recipe - the one with water cells, not the 1k coolant cells
4. Click to craft
5. Profit

### Expected behaviour

Crafting 1, you get over 5 stacks of tin

**Comment by Saereth** [comment]
issue reported to mcjty and speiger both for a fix
https://github.com/McJtyMods/RFToolsStorage/issues/84
