### ISSUE TITLE
World crash Botania 

### ISSUE THREAD

**Issue by jotaprojects** [FTBTeam/FTB-Modpack-Issues#4262]
### Modpack

FTB Genesis

### Modpack version

1.1.1

### Log Files

[crash-2023-11-17_16.01.32-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13393476/crash-2023-11-17_16.01.32-client.txt)

### Describe the bug

I am not sure if this a pack issue or mod issue with Botania.

Playing on single player.

I just unlocked the floating white flower and wanted to use pure daisy with it. No problem there. But I wanted to test the overgrowth seed on it and tried to apply it when the floating pure daisy is on the ground and right clicking with the overgrowth seed just crashed the world. 

Right now as soon I join the world it crashes so I can't really tell if I have any more that can relate to the issue. 

### Steps to reproduce

1. Combine Pure daisy with floating white flower
2. Put down the flower and apply Overgrowth Seed on the floating flower. 
3. The world saves and instance crash.

### Expected behaviour

No world crash

### Additional information

From what I can see on Botanias changelog I could only find a fix in the version https://botaniamod.net/changelog.html#r1-8-309-fake
I can't find any related issues on Botanias github. 

Using Java 17

**Comment by Saereth** [comment]
hrm yeah looks like botania but might also be related to embedium/oculus shaders, try disabling those mods and see if it still crashes. you can also edit your save/serverconfig/forge.cfg and turn on remove erroring entities to get back up and running.

**Comment by jotaprojects** [comment]
Thanks for getting back. I tried to disabled embedium and oculus but it did not change. The world still crash. Do I have to remove the jar files or is it enough to just rename with .disabled? 

I also tried to update saves\New Beginnings\serverconfig\forge-server.toml to remove erroring entities but sadly it does not help. Same crash. The crash log is reporting the same error. Just a question here, I have claimed chunks for the base, does that effect how things can be removed? 
When I am logging in and I see the world for a second, some of the claimed chunks seems to be removed. I can see if I can get a screenshot of it, if you need.

I have loaded up a backup of the save to continue as I am not sure how I will get the faulty one to run again.

Feel free to close the issue if it is a mod issue.

**Comment by Saereth** [comment]
its just enough to rename them, basically in this scenario the only way to get rid of it is to remove the block which you would have to do with something like mcedit, restoring from the backup is probably the best bet. With no embedium in the stack trace this does seem to be a botania issue so I'll go open an issue report there and see what they say
