### ISSUE TITLE
IC2 diamond dust compression disabled

### ISSUE THREAD

**Issue by Brettflan** [FTBTeam/FTB-Modpack-Issues#4266]
### Modpack

FTB Genesis

### Modpack version

1.2.0

### Describe the bug

In 1.1.1 and back, the IC2 diamond dust (generated by IC2 adamantum plants) could be compressed 4:1 into diamonds in the IC2 compressor. In 1.2.0 that recipe is currently removed, and the only usage showing for IC2 diamond dust is the recycler.

### Steps to reproduce

1. Check recipes for IC2 diamond dust.
2. See that they now have no recipes other than to chuck them in the recycler.

### Expected behaviour

For the 4:1 compression recipe or similar to be added back so my adamantum plants aren't useless.

**Comment by yarma92** [comment]
Confirmed this is not just a JEI integration issue. Unable to insert diamond dust in to any form of a compressor.

**Comment by Knoxxar** [comment]
We have the same problem ...

**Comment by Kenshij** [comment]
go to folder kubejs\data\ic2\ic2_recipes\compressor copy the diamond_compression.json, name it as you want, change in there mekanism:dust_diamond to ic2:dust_diamond

this solved it until hotfix
