### ISSUE TITLE
1.2.0 Wont boot up

### ISSUE THREAD

**Issue by munugget** [FTBTeam/FTB-Modpack-Issues#4267]
### Modpack

FTB Genesis

### Modpack version

1.2.0

### Log Files

https://pste.ch/obigadumoq.md

### Describe the bug

Can't update my 1.1.1 server. I tried redownloading the whole pack, but can't get the server to boot up.
I tried 3 times to start a fresh server setup, and every time I get the same error.

### Steps to reproduce

Downloaded the 1.2.0 serverpack
Install on an empty folder
Start the server

### Expected behaviour

The server should start

**Comment by ingel81** [comment]
same for me...reason might be that one file during update can't be downloaded...
also here #4271

**Comment by munugget** [comment]
I manually downloaded the missing file (although in my case it did download, just re-downloaded it), but still get the same error

**Comment by ingel81** [comment]
re-download also does not work here..tried about 6 times...file is offline (--> 404)

**Comment by drtrdr23** [comment]
mine wont boot too

**Comment by ingel81** [comment]
deleted this file from the server mods folder and it started again... "jeargh-1.19.2-1.0.2.jar"
i think it isn't needed on server side or should not even be there but better make a world backup before trying.

**Comment by munugget** [comment]
mod description says: All this mod does is creating a world-gen.json file in your config folder for JER to attach.
I dont know...might be needed

**Comment by ingel81** [comment]
> mod description says: All this mod does is creating a world-gen.json file in your config folder for JER to attach. I dont know...might be needed

Description also says that it is for Single Player worlds and provides only a comand for scanning for something ore related and write results to a file. Probably something that was done during creation of the shipped world but not needed when playing. But i also might be totally wrong here :)

Played a few hours with it removed and didn't notice any problems.

**Comment by Saereth** [comment]
delete jeargh mod, its marked clientside only but was installing in servers erroneously, this has been fixed now for the server installer
