### ISSUE TITLE
[Bug]: Auto-hammers can accept compressed blocks

### ISSUE THREAD

**Issue by iammael** [FTBTeam/FTB-Modpack-Issues#427]
### Modpack

FTB OceanBlock

### Modpack version

1.9.0

### Describe the bug

The FTB Sluice's Auto-Hammers can accept compressed version of blocks and treat them as fast as they do with the normal version of the block.

This render the upgraded version of Auto-Hammers useless as the Iron version can give you a stack of block in a matter of second if using a 2x compressed version of any block (which is very easily obtainable with a Compacting Drawer).

### Steps to reproduce

1. Place a chest with 2x Compressed Cobblestone on the input side of the Auto-Hammer.
2. Observe that in a second you have more than a stack of Gravel on the output side.

### Expected behaviour

Auto-Hammers should not accept compressed blocks or the processing time should increase depending on how compressed the blocks are.

**Comment by quietust** [comment]
Alternatively, only the higher tiers of auto-hammerers should accept compressed blocks, the same as with the hammers themselves.

**Comment by Sunekaer** [comment]
In 1.10.0 hammers respects block hardness now
