### ISSUE TITLE
Quest Bug: Access The System Internals (1st Getting Started Quest)

### ISSUE THREAD

**Issue by beironjohn** [FTBTeam/FTB-Modpack-Issues#4270]
### Modpack

FTB Genesis

### Modpack version

1.2.0

### Describe the bug

Encountered during MP, tested on multiple SP worlds

When starting the pack, in the main instance, the quest Access The System Internals becomes incompletable when anything other than the bottom crafting screen is selected, and the ae2 machines are destroyed.

This prevents advancement of the questline, meaning the player cannot do anything.

This was found on a MP server (TwinPeaks Gaming), so we are investigating how we can restart without a full server wipe

### Steps to reproduce

1. in front of the ae2 blocks, right click any device not the lower screen
2. notice all devices 'explode' (dissapear)
3. notice quest has not progressed
4. notice quest can no longer be completed

### Expected behaviour

Quest becomes progressable

### Screenshots

![image_2023-11-18_110105580](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/16866321/1554fde9-6bff-4630-bee0-2d9be146707b)

**Comment by Saereth** [comment]
ok I changed this to work off a gamestage now, ae2drives, which is granted when the actual explosion happens. This should fix itself automatically next update but in the mean time you can go into editing mode (pencil in the lower right corner) and right click the quest and complete instantly. Fix in 1.2.1 update coming today
