### ISSUE TITLE
FTB Genesis 1.2.0 Windows server fails installation

### ISSUE THREAD

**Issue by Agoutii** [FTBTeam/FTB-Modpack-Issues#4271]
### Modpack

FTB Genesis

### Modpack version

1.2.0

### Log Files

Error downloading https://dist.modpacks.ch/modpacks/0/FTB%20Academy-1.0.0/config/brandon3055/ResourceCache/Cache: server returned 404 Not Found

### Describe the bug

1.2.0 Windows server install fails with missing file. If the installation is continued with missing file, server will not launch.

### Steps to reproduce

1. Install from serverinstall_120_11334.exe
2. Observe failed download

### Expected behaviour

Install finishes without error

### Screenshots

N/A

### Additional information

N/A

**Comment by ingel81** [comment]
Same for me....in my case when updating to 1.20 on linux (Intel / AMD) server.

**Comment by ingel81** [comment]
deleted this file from the server mods folder and it started again... "jeargh-1.19.2-1.0.2.jar"
i think it isn't needed on server side or should not even be there but better make a world backup before trying.

**Comment by Saereth** [comment]
duplicate issue, this is now resolved in the server installer

**Comment by MvanRietschoten** [comment]
Trying this modpack out and I still have this in 1.2.2. Exact same 404 not found download error of that mod.
