### ISSUE TITLE
[Bug]: Genesis: 1.2.0 kubejs error in sdrp.js

### ISSUE THREAD

**Issue by crzyblue** [FTBTeam/FTB-Modpack-Issues#4272]
### Modpack

FTB Genesis

### Modpack version

1.2.0

### Describe the bug

[Render thread/ERROR] [KubeJS Client/]: sdrp.js#3: Error occurred while handling event 'sdrp.dimension_change': TypeError: Cannot read property "dimension" from undefined

issue with sdrp.js script line 3.

### Steps to reproduce

Joined server
Got error for dimension

### Expected behaviour

kubejs not to give error

**Comment by Saereth** [comment]
this can be ignored, usually happens doing a creation transition event or something, I put a null check in there just to prevent the error message in future updates
