### ISSUE TITLE
FTB Genesis: My team/dimension/vault is disconnected/not accessible/gone after update to 1.2.0 

### ISSUE THREAD

**Issue by atealein** [FTBTeam/FTB-Modpack-Issues#4273]
### Modpack

FTB Genesis

### Modpack version

1.2.0

### Describe the bug

I logged off in my simulation matrix in the vault. After the update, I log in - I am in stone suffocating. Switched to spectator, and after a bit of looking around I realize I am in fact in the overworld with the huge starting structure over where my vault should be. I tried to go through the portal ("Welcome, Administrator") but it doesn't work for me. I believe the team and dimension is actually gone ( I tried /home and I also ran a command to teleport to the lostcity dimension directly Edit:just realized that the ftbteamdimension is a different one so I will try to teleport to it as well ).

I have a bunch of backups from before the update, so I will downgrade and use them to restore, but I don't see anyone else has reported this issue and I'd like to upgrade to 1.2.0.

### Steps to reproduce

1. Just updated to 1.2.0 and ran as usual

### Expected behaviour

Ideally either be back in my vault or be loaded at the overworld spawn point in front of the portal and be allowed to go back through it to my dimension.

### Screenshots

![2023-11-18_14 33 13](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25322782/a374a873-e4ff-4cb6-9417-23559cbd33ef)
![2023-11-18_14 33 34](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25322782/f785cf69-eddc-4023-b479-505de820807c)
![2023-11-18_14 35 58](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25322782/d380ceee-c528-4033-ac97-11b9083b10bd)

**Comment by atealein** [comment]
So some additional things I have tried:
1. The /ftbteamdimensions home 
doesn't work tells me i need to use overworld lobby portal - which doesn't work
2. /ftbdim list-dimensions lists my dimension 
3. /ftbteam list shows that i am still part of my team
![Screenshot 2023-11-18 at 15 52 44](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25322782/35f6336c-2179-4417-8e0a-faf8e1f060b2)

5. trying to use /ftbdim visit to visit my own team tells me I don't have a team dimension.

So i am both shown to have a dimension and team and be in it (my questbook progression is preserved).

**Comment by atealein** [comment]
So, I tried to downgrade to older version and restored a backup and it still actually happened on login. So I installed an entirely new instance to 1.1.1 and then upgraded to 1.2.0 and on the new instance it ran without issue. I am not sure what the problem was still, but at least i have a workaround.

**Comment by Saereth** [comment]
your latest.log and debug.log here would help shed some light, im afraid without the logs we dont have much to go on
