### ISSUE TITLE
Update Stoneblock 3's forge version again

### ISSUE THREAD

**Issue by aaronliu0130** [FTBTeam/FTB-Modpack-Issues#4275]
### Modpack

FTB StoneBlock 3

### Is your suggestion related to a problem? Please describe.

1.8.1 only downgraded the forge version. According to https://github.com/MinecraftForge/MinecraftForge/issues/9765#issuecomment-1790134726 , the original issue with the forge version has been fixed.

### Mod suggestion

Update forge

**Comment by UnRealDinnerbone** [comment]
Same as #4131
