### ISSUE TITLE
Genesis - Nether aluminum and osmium does not drop anything without silktouch

### ISSUE THREAD

**Issue by anqingchen** [FTBTeam/FTB-Modpack-Issues#4277]
### Modpack

FTB Genesis

### Modpack version

1.2.1

### Describe the bug

Mining nether aluminum and osmium ores drop nothing. Looks like kubejs loot table specifies we need silk touch, is this intended?

### Steps to reproduce

1. Mine a nether aluminum ore
2. Nothing drops

### Expected behaviour

I should get a nether aluminum ore

**Comment by Brettflan** [comment]
Confirmed.

**Comment by RayChimera** [comment]
Same, went here to report that (was thinking it's because of my drill update)

Also, that started only after 1.2.1, before Aluminum was mineable
