### ISSUE TITLE
IC2Classic energyNet crash fix push update

### ISSUE THREAD

**Issue by Savior10K** [FTBTeam/FTB-Modpack-Issues#4281]
### Modpack

FTB Genesis

### Modpack version

1.2.1

### Log Files

https://github.com/TinyModularThings/IC2Classic/issues/913

### Describe the bug

this issue was fixed by the IC2 Classic dev today. Making this bug report so you can push out a hotfix or something for this crash

### Steps to reproduce

all in the link

### Expected behaviour

breaking IC2 cables can lead to constant crashing

**Comment by Speiger** [comment]
@Savior10K Genesis 1.2.2 is already out fixing that issue.
