### ISSUE TITLE
Entities disappear behind name tags

### ISSUE THREAD

**Issue by aleksandrose** [FTBTeam/FTB-Modpack-Issues#4283]
### Modpack

FTB Presents Direwolf 20 1.2.0

### Modpack version

1.6.0

### Describe the bug

Other entities disappear completely behind the floating name/entity tags. It seems to happen globally and with all spawns.

### Steps to reproduce

Just have any creature walk behind the name tag of another creature.

### Expected behaviour

Should be able to see them behind the name tag

### Screenshots

![error](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/82713594/1847f636-ff10-4415-81c7-b61751f865c7)

As you can see, this chicken is halfway cut off behind the wolf's title/name tag

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
