### ISSUE TITLE
Faltal exception 

### ISSUE THREAD

**Issue by Peterosisk** [FTBTeam/FTB-Modpack-Issues#4285]
### Modpack

FTB Genesis

### Modpack version

1.2.1

### Log Files

I try to install the latest version of the modpack but it won't let me and I get a fatal exception while installing modpack and the only version that works is from 1.1.1 onwards, it won't let me update either, please help

### Describe the bug

It won't let me update or install the latest version and I restarted, deleted the instance as the launcher and nothing

### Steps to reproduce

Vaya, haga clic e imágenes 

### Expected behaviour

Quiero poder descargar el modpack y que me lo expliquen claro y preciso

### Screenshots

![eb0e898e-15b7-4b1f-95cf-2a3607178da6](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/151469633/7579c98d-860a-4a3e-9390-5b8826d39ece)

### Additional information

Please help

**Comment by Micaxs** [comment]
Retry the isntall, should work right after.

**Comment by orbidlo** [comment]
I have the same issue, created issue there: https://github.com/FTBTeam/FTB-App/issues/1005
I have tried restarting FTB app several times and downloading both 1.2.1 or 1.2.2, both fail with same error

**Comment by Saereth** [comment]
this is not a pack specific issue so the issue has been migrated to app support. We have a major update to the app soon that will hopefully help solve this
