### ISSUE TITLE
Unable to use Builder's Hut

### ISSUE THREAD

**Issue by CilliePaint** [FTBTeam/FTB-Modpack-Issues#4288]
### Modpack

Other...

### Modpack version

Valhelsia 6 6.1.0-pre1

### Describe the bug

Upon attempting to place and use a Builder's Hut, it states that 'This block is missing its respective building, try restarting or loading a backup!'

I have checked all common causes of this issue, including waiting several minutes, restarting the Server (Apex Hosting), re placing the Block, re placing the Colony, and now I am here.

### Steps to reproduce

1. Open Valhelsia 6
2. Start Colony
3. Place Builder's Hut

### Expected behaviour

The UI for the Builder's Hut should open.

### Additional information

If additional information is needed, I can provide it.

**Comment by manmaed** [comment]
This is not a FTB Controlled Pack, try reporting this [here](https://discord.com/invite/rdfQuaM)
