### ISSUE TITLE
Enhanced farming sim

### ISSUE THREAD

**Issue by DiggityMan420** [FTBTeam/FTB-Modpack-Issues#4290]
### Modpack

FTB Genesis

### Modpack version

1.2.2

### Log Files

no log

### Describe the bug

along the wall your dark room the light level is still 14-15

### Steps to reproduce

complete the beetroot quest
open the Enhanced Farm Sim
head to dark room
place sticks one both side wall and window
See Pics

### Expected behaviour

light level of redstone torch (6-7)

### Screenshots

![Screenshot_19](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/3376aadf-865b-4584-9521-cb7b50e15835)
![Screenshot_20](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/a1483b6c-ab7a-462e-8b89-03172b052dfa)

**Comment by Saereth** [comment]
this is now fixed in for new simulaitons but it wont be retroactive unfortunately

**Comment by jmrobichaud0569** [comment]
Is there a way to adjust the simulation to set correct light levels? Or at least a way to re-generate the sim so it will come out with correct light?
