### ISSUE TITLE
all functional storage unlinked upon pack update

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4294]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

As the title says, when I updated the pack, all of my controllers lost all of their linked drawers, which immediately caused my client to drop to <1 FPS from mob drops no longer getting sucked into my drawers. 

### Steps to reproduce

1. Link a Functional Storage Controller to some drawers in a version prior to 1.7.0.
2. Update pack.
3. Load world.
4. Drawers no longer linked.

### Expected behaviour

Drawers should not lose links. As I said, bad things could happen!

**Comment by DMIL421** [comment]
Can confirm this issue.

**Comment by kernelstubbs** [comment]
We're also having trouble adding some drawers back - the range is displayed in world but drawers within 4 blocks of the edge are not adding back to the controllers.  Tried breaking them.

**Comment by perlguy** [comment]
Ran into this same issue. Looks like the server pack updated to limit linking range to 8, while the normal pack (for single player) is still set to 12.  The mod should probably be pulling the client side value from the server to show linking rangem which would make it less confusing.  I just bumped the server config back to 12 since I only have 2 players on a private server.

**Comment by volrathstormborn** [comment]
This was a new function added to Functional Storage which was in the newest version that the pack updated to.  Sneak right-click on the Storage Controller and you'll see four upgrade slots.  You can now add the standard Copper-Netherite upgrades to increase the range of the controller.

I would certainly agree that it should not be unlinking the drawers that are still within the base range, and it is certainly odd that the server config would be different than the client config.

I can confirm the unlinking, but was a fan of the ability to add upgrades to the Storage Controller as I just hit the default range limit and was about to add a second controller.
