### ISSUE TITLE
very low FPS when looking up uses for things in JEI

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4295]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

It is very common for your FPS to take a massive hit when looking up uses for items in JEI. I thought it was maybe due to JEI cycling through many oredicted items (glass, glass panes) but this does not seem to be the case consistently. In fact, I have not managed to track down any consistent cause of this issue except that some items will produce the behavior and some will not. My graphics settings are left at default except for a slight bump to render distance.

### Steps to reproduce

1. Right click or press U (default key to look up uses) on an item. I most recently noticed this with silver ingots.
2. Observe very low FPS to the point of sluggish mouse movement.

### Expected behaviour

FPS should not drop when looking up recipes.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
