### ISSUE TITLE
PvP off does not block Apotheosis cold damage

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4296]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

I accidentally 1shot my friend so I checked whether PvP is off and it is but it said he was "frozen to death" which could have only been caused by the Apotheosis lunar gem on my weapon dealing extra cold damage. I would assume the solar gems (fire damage) and other effects would also bypass PvP off in FTB Teams. Another case of idk who to blame!

### Steps to reproduce

1. Turn off PvP in FTB Teams.
2. Add a lunar gem to a weapon.
3. Hit a friendly player.
4. Player takes damage and can die despite PvP off.

### Expected behaviour

PvP off = PvP off

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
