### ISSUE TITLE
crash when killing mobs in a vault

### ISSUE THREAD

**Issue by simpson1987** [FTBTeam/FTB-Modpack-Issues#4297]
### Modpack

FTB Genesis

### Modpack version

1.2.2

### Log Files

[crash-2023-11-21_05.07.19-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13421668/crash-2023-11-21_05.07.19-server.txt)

### Describe the bug

i went to the first vault around -900 -600 and when i kill some mobs i get a nullpointer exeption from apotheosis.

### Steps to reproduce

go vault,
kill some mobs,
and crash

### Expected behaviour

not crashing

**Comment by BeastyCloak** [comment]
Same, specifically when the boss is about 1/4th health for me

**Comment by Nylathim** [comment]
Exact same issue, my crash logs also mention something with gateways to Eternity.
[crash-2023-11-21_20.01.14-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13432402/crash-2023-11-21_20.01.14-server.txt)
