### ISSUE TITLE
Add Powah! (Rearchitected)?

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4298]
### Modpack

FTB Presents Direwolf20 1.20

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/powah-rearchitected
I remember Dire using and enjoying this mod so I think it would be a good fit if this rewrite is stable enough.

**Comment by DinnerBeef** [comment]
Dire did not want it added to this version.
