### ISSUE TITLE
[Bug]: steves carts 2 time in minuses

### ISSUE THREAD

**Issue by Steftast1c** [FTBTeam/FTB-Modpack-Issues#430]
### Modpack

ftb ultimate anniversary

### Modpack version

1.04

### Describe the bug

making a full galgadorian cart (is how i experienced it)

modules 
solar + coal engine
galgador planter
not sure on attachments
side chests
chunk loader

time to craft it has -xx% 

### Steps to reproduce

make a Steve cart
set it to build
should be acting like described and in the image

### Expected behaviour

time and progress should be normal and not -xx%

### Screenshots

https://media.discordapp.net/attachments/915596600854872124/917415062577217616/unknown.png

**Comment by Steftast1c** [comment]
addition https://media.discordapp.net/attachments/915596600854872124/917418164114030622/unknown.png i dont think im getting my cart am i?

**Comment by Steftast1c** [comment]
add on to this

so the steves carts dont know how to deal with long grass 
wont accept carrots or potato's for planting
solar panel doesn't seem to want to power it properly (had to use the coal engine in it for it to work)

**Comment by Sunekaer** [comment]
Hi, please attach your log file

**Comment by Steftast1c** [comment]
which one i have a lot? this one is my latest one (just closed the game so it might be big
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7662372/latest.log)

**Comment by Sunekaer** [comment]
just one where the issue happened :)

**Comment by Steftast1c** [comment]
that should be the one

**Comment by Sunekaer** [comment]
Talked to the dev, the cart will still craft, just the tooltip there is broken, they will look in to it

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?

**Comment by Steftast1c** [comment]
this was an issue i encountered over 3 years ago, i dont even think the pack is available anymore
