### ISSUE TITLE
PneumaticCraft Netherite Drill Bit Assembly Crash

### ISSUE THREAD

**Issue by tabernacle8** [FTBTeam/FTB-Modpack-Issues#4303]
### Modpack

FTB Genesis

### Modpack version

1.2.2

### Log Files

[crash-2023-11-21_20.23.09-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13432517/crash-2023-11-21_20.23.09-server.txt)

### Describe the bug

Trying to create the Netherite Drill Bit with PneumaticCraft's assembly platform crashes the game.

### Steps to reproduce

1. Take the Unassembled Netherite Drill Bit and put it into the input chest
2. Wait for the robot arm to put it onto the assembly platform
3. Server Crash

### Expected behaviour

Not crashing when assembling

**Comment by Saereth** [comment]
opened an issue with PNC git
https://github.com/TeamPneumatic/pnc-repressurized/issues/1259
