### ISSUE TITLE
Opened the FTB app and all modpacks were deleted along with the worlds

### ISSUE THREAD

**Issue by xRodies** [FTBTeam/FTB-Modpack-Issues#4304]
### Modpack

FTB Cotton

### Modpack version

1.1.0

### Log Files

The files are gone

### Describe the bug

Been playing FTB cotton for a about a week now and i came on my computer and opened the ftb app to launch it and everything was gone. All of the modpacks i had installed. Redownloaded Cotton and my world was gone aswell.

### Steps to reproduce

Open FTB app
See no modpacks lol

### Expected behaviour

open and play my FTB cotton world

**Comment by manmaed** [comment]
This  issue is now stale
