### ISSUE TITLE
FTB Genesis: Zero drops from Adamantum using IC2 Harvester

### ISSUE THREAD

**Issue by ratkinsonuk** [FTBTeam/FTB-Modpack-Issues#4305]
### Modpack

FTB Genesis

### Modpack version

1.2.2

### Log Files

N/A

### Describe the bug

I have 25/25/20 Adamantum growing on crop sticks with hydration and fertilizer. If I manually right-click, I get around 4 drops. The IC2 Harvester is updating the block, but not collecting any drops.

### Steps to reproduce

Set up IC2 crops as above.

### Expected behaviour

Expecting 2-4 drops per cycle.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25905667/b62205da-5844-43aa-a0f3-04cea67d53ea)

**Comment by Saereth** [comment]
I talked with speiger about this, its not a bug. The harvester gives much lower drop chance on crops so basically you need more diamond plants to consistently get drops over time. I may implement a better farming method eventually but thats just how it works for now

**Comment by krazzykid2006** [comment]
> I talked with speiger about this, its not a bug. The harvester gives much lower drop chance on crops so basically you need more diamond plants to consistently get drops over time.

I'm not getting drops even when harvesting by hand over half the time with the Adamantum crop specifically.
When the crop harvester handles it I get less than a 20% chance at drops.

Like I said though, it doesn't drop anything even by hand around half the time.
Surely THAT can't be intended.....
