### ISSUE TITLE
Pneumaticraft tanks placed inside Electrodynamics Machines provide infinite fluid

### ISSUE THREAD

**Issue by mjory80** [FTBTeam/FTB-Modpack-Issues#4306]
### Modpack

FTB Genesis

### Modpack version

1.2.1

### Describe the bug

When you place a Pneumaticraft tank inside the fluid slot of an Electrodynamics machine, such as lubricant for a motor or fuel for the combustion generator, the fluid bar is filled and does not remove any fluid from the tank.  The tank will continue to keep the fluid bar filled and never consume any of the fluid from the tank.

### Steps to reproduce

1. Place down a combustion generator from Electrodynamics mod
2. Put 1 bucket of LPG fuel into a Pneumaticraft tank
3. Put the tank into the fluid slot of the combustion generator
4. Note that the generator will run and stay filled without removing any fluid from the tank

### Expected behaviour

I expect the fluid to be consumed from the tank to fill the fluid buffer of the machine.

### Screenshots

![2023-11-21_19 30 29](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26591/2ef6b01c-c542-4c6f-a4b9-3d7704a04fe2)
![2023-11-21_19 30 36](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26591/1565922b-e826-4ec9-9a4c-32d462d3ed8e)
![2023-11-21_19 30 38](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26591/ceceac64-4f63-4338-8187-9ebb8d0f96a7)

**Comment by Saereth** [comment]
reported to mod dev for followup, 
https://github.com/aurilisdev/Electrodynamics/issues/235

**Comment by DiggityMan420** [comment]
happens with crude oil too

**Comment by Saereth** [comment]
ED devs have located the issue and are working on a update
