### ISSUE TITLE
Dual-Head Distant Signal (Railcraft Reborn) not function properly

### ISSUE THREAD

**Issue by Tavren** [FTBTeam/FTB-Modpack-Issues#4307]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

Dual-Head Distant Signal bottom lamp blinks yellow after getting bound to second Signal Controller Box instead of show signal aspect from that controller, both controllers controls only top lamp.

### Steps to reproduce

Place Dual-Head Distant Signal
Place two Signal Controller Box (or Analog Signal Controller Box)
Place a lever or button for each Controller Box for change the signal aspect they provide with redstone
Using Signal Tuner right click on one Controller Box, then on Dual-Head Distant Signal to link them
Using Signal Tuner right click on second Controller Box, then on Dual-Head Distant Signal to link them
(If using Analog Controller then right click on it and set for example green aspect to be send when redstone level is 15)
Using Levers or Buttons byt the controllers we can control the lamp that will show that signal aspect from controllers, but only top lamp is working and from the both, lower one just blink yellow

### Expected behaviour

Dual-Head Distant Signal should bound to two Signal Controllers and show the signal aspect they provide on separate lamps

### Screenshots

![изображение](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/6377052/b3fd0cbd-dc8d-4205-981f-0234cdaef8a5)

**Comment by Tavren** [comment]
After restarting the world bottom lamp just show solid green but yet not controlled by the controller, both of them still weirdly controls the top lamp only

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
