### ISSUE TITLE
Quest constantly completing

### ISSUE THREAD

**Issue by Riezing** [FTBTeam/FTB-Modpack-Issues#4309]
### Modpack

FTB Genesis

### Modpack version

1.2.2

### Describe the bug

When i open my world after updating from 1.2.1 to 1.2.2 my quest will constantly complete over and over again it stops once i go back to 1.2.1

### Steps to reproduce

1.Log in
2.Quest just constantly complete

### Expected behaviour

For them to already have been completed

**Comment by Saereth** [comment]
pre-requisites changed so they're all reupdating, they will stop or you can relog to make it stop faster, not a bug though
