### ISSUE TITLE
[Bug]: "The Island" setting won't spawn an island

### ISSUE THREAD

**Issue by P1neapplecak3** [FTBTeam/FTB-Modpack-Issues#431]
### Modpack

FTB OceanBlock

### Modpack version

1.9.0

### Log Files

https://paste.ee/p/OVsIe

### Describe the bug

Choosing the island type "The Island" spawns me a few blocks above the ocean, with nothing but the ocean under me.
There is no island spawned, I'm in the open ocean. This problem happens on every "The island" world generated.
"The Cottage" island type works fine, I haven't tested other island types.
(This bug exists since version 1.1.0)

### Steps to reproduce

Create a new world
Choose "The island" world
Spawn in the open ocean with no island anywhere
Drown

### Expected behaviour

Create a new world and have an island under me

**Comment by quietust** [comment]
Did you download and install the modpack using MultiMC or another 3rd-party tool?

**Comment by Raidobw2** [comment]
Hello, this is a known issue with MultiMC and some island templates don't seem to be downloaded for some reason.

Use the FTB App or the dev branch of MultiMC to correct the issue.
Cheers.
