### ISSUE TITLE
village raids getting stuck

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4310]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

Raids will get stuck with 1 or 2 raiders left. I hunted all over the place, but aside from digging up a ton of terrain underneath I'm not sure what to do. Setting difficulty to peaceful and back does resolve the issue, but also kills the wither in my stasis chamber and could kill other "kept" hostile mobs.

### Steps to reproduce

1. Initiate village raid.
2. Eliminate all raiders in sight.
3. It doesn't happen every time, but sometimes the raid gets stuck with at least one enemy remaining.

### Expected behaviour

Raiders should spawn above ground. If this is not possible, they should despawn eventually. Configurable in LetMeDespawn?

**Comment by DinnerBeef** [comment]
Unable to reproduce this, issue. Please reopen if you are still having issues with this.
