### ISSUE TITLE
Download error when running serverinstall

### ISSUE THREAD

**Issue by Asgarus** [FTBTeam/FTB-Modpack-Issues#4311]
### Modpack

FTB Genesis

### Modpack version

1.2.1; 1.2.2

### Log Files

Error downloading https://dist.modpacks.ch/modpacks/0/FTB%20Academy-1.0.0/config/brandon3055/ResourceCache/Cache: server returned 404 Not Found

### Describe the bug

When running the serverinstall on our linux server (to either install or update), one of the download paths apparently spits out a 404.
The pack still runs fine, but I don't think this is intentional^^

### Steps to reproduce

1. Run serverinstall 
2. See notifcication that one download failed

### Expected behaviour

No download failing

**Comment by Saereth** [comment]
its just a 0 byte file that will get created on first launch, you can ignore it, we'll get it resolved at some point
