### ISSUE TITLE
plains and snowy village dimlets unobtainable

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4313]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

Plains villages share the "recipe" in the dimlet workbench with desert villages, and snowy share their recipe with savannah. Despite requiring a structure absorber with the correct structure, only the first dimlet with the same recipe is obtainable.

### Steps to reproduce

1. Attempt to create plains or snowy villages dimlets.
2. You will get desert or savannah village dimlets, respectively.

### Expected behaviour

These dimlets should be obtainable. Tweak recipes?

**Comment by jlp1528** [comment]
After further testing, it appears this issue only occurs when searching "village" and trying to create all of them as I did. Searching for the specific villages seems to allow creation of the correct dimlets. The recipes should still be tweaked to prevent this issue entirely though IMO.

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you in the latest version of the pack?
