### ISSUE TITLE
WORLD CORRUPTING CRASH - DO NOT BREAK SPAWNERS WITH PEDESTALS

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4314]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Log Files

[crash-2023-11-22_12.10.30-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13444027/crash-2023-11-22_12.10.30-server.txt)
[crash-2023-11-22_14.11.26-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13444028/crash-2023-11-22_14.11.26-server.txt)

### Describe the bug

Breaking a spawner with a pedestal breaker upgrade causes the game to crash. Attempting to reload the world causes an immediate crash. THANK YOU FOR INCLUDING AUTOMATIC BACKUPS!!!!!

### Steps to reproduce

1. Place a spawner.
2. Right click the spawner with the pedestal location work card.
3. Apply work card and breaker upgrade to pedestal.
4. CRASH

### Expected behaviour

It should just drop a broken spawner or apotheosis spawner according to the tool on the pedestal, not crash and corrupt my game.

**Comment by jlp1528** [comment]
This appears to only affect Pedestals. I have so far tested both AE2 and RS block breaker planes, as well as Cyclic and Industrial Foregoing block breakers. All of these worked completely and as intended, except for the double broken spawner drop, which I believe is a known issue.

**Comment by Mowmaster** [comment]
Spawners should be block entities, normally a pedestal shouldn't be able to break these types of blocks unless it's configured in the config file to allow it...

**Comment by jlp1528** [comment]
> Spawners should be block entities, normally a pedestal shouldn't be able to break these types of blocks unless it's configured in the config file to allow it...

I see no such config option. Where would that be? Also, pedestals-client.toml looks very weird in Notepad++.

**Comment by DinnerBeef** [comment]
This should be fixed now, I hope. I blacklisted broken spawners.
