### ISSUE TITLE
Mold (Bottle) Use recipes missing

### ISSUE THREAD

**Issue by norm1000100** [FTBTeam/FTB-Modpack-Issues#4315]
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Describe the bug

Bottle mold is given for quest "Are you Gellin?" most likely for use in making glass bottles after basic fluid solidifier is made but does not have recipes to actually use the mold in any machines

### Steps to reproduce

get mold.
Check use recipes in JEI (Nothing)
Try to use in Fluid Solidifier
doesnt work

### Expected behaviour

Should be able to make glass bottles with glass and mold

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/3014634/1f37db2e-f0a5-4583-ad46-7a3e003fc27a)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/3014634/16eb2ea7-3317-4b6c-a77a-c79de1ff218d)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/3014634/c137d21e-4b08-4e95-a3c0-1445cd242987)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/3014634/be8b9e3d-763a-42b3-a937-ab13386885c1)

### Additional information

Seems like an oversight when adjusting recipes

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

We may have something up our sleeves, some may call it a remaster, keep an eye out on our social media platforms for more information.
