### ISSUE TITLE
cyclic miner problems

### ISSUE THREAD

**Issue by thisKid619** [FTBTeam/FTB-Modpack-Issues#4316]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

the miner from cyclic keeps mining itself when in the mining dimension and the miner itself is dissapearing

### Steps to reproduce

1. place miner in mining dimension
2. set miner up with power and reduce rnage down to a 1 by 1 block
3. give it a pick and make it run without redstone

### Expected behaviour

i expected the miner to mine the ore being placed in front of it

**Comment by jlp1528** [comment]
If you're just trying to mine ore in a 1-block space, I recommend using pedestals with a fortune enchanted pickaxe. I've never used the miner so I'm not sure what it's supposed to do, but there is also a block breaker, as well as the industrial foregoing block breakers and AE2 annihilation planes and RS destructors.
