### ISSUE TITLE
visual tearing

### ISSUE THREAD

**Issue by DiggityMan420** [FTBTeam/FTB-Modpack-Issues#4318]
### Modpack

FTB Genesis

### Modpack version

1.2.2

### Log Files

no log

### Describe the bug

Looking at the pressure gauge from certain angles makes a visual glitch bug see screenshoots
PneumaticCraft has a report too

### Steps to reproduce

install pressure gauge i added a mod expansion card to it but it happen with or with out the card
walk around
see visual pics

### Expected behaviour

no tearing

### Screenshots

![Screenshot_2](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/0ac34f3b-15d5-43f0-bf56-d1d528310c8e)
![Screenshot_6](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/db2134e9-d704-4199-9968-3675352360cf)
![Screenshot_3](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/d1809f62-449b-4ee3-807f-e083fb3a15da)
![Screenshot_4](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/e5ce21f9-7811-4478-8433-35674e4f2390)
![Screenshot_5](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/da238577-3acd-420c-a40b-de549fcafe0b)

**Comment by Saereth** [comment]
yeah this will be an embedium/pneumaticraft issue to sort, I'll leave this issue open and see how it goes with them
