### ISSUE TITLE
Radiation in vault

### ISSUE THREAD

**Issue by WarpedLeopard** [FTBTeam/FTB-Modpack-Issues#4319]
### Modpack

FTB Genesis

### Modpack version

1.3.0

### Describe the bug

I just updated the world from the previous release to 1.3.0 and I noticed that I am in an irradiated zone in the simulation chamber, the data access area, and the connectivity nexus. I've attached screenshots to help show where. 

### Steps to reproduce

1. Updated world to 1.3.0
2. Entered the Simulation chamber or other space
3. Used a Dosimeter to measure the rads, also can see particles if active.

### Expected behaviour

You will encounter radiation in the related vault locations

### Screenshots

![2023-11-22_20 48 40](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/151803464/49322c39-965a-4b68-b8ed-efc8644e42a4)
![2023-11-22_20 49 32](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/151803464/614cfc44-ea04-431b-b417-7f534101e3f2)
![2023-11-22_20 49 54](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/151803464/8bc96bdf-d470-4708-891c-d47d43f28db2)

### Additional information

Hope this is an easy fix. Thank you for a wonderful mod pack regardless, I've really enjoyed this! -Warped

**Comment by WarpedLeopard** [comment]
Also forgot to mention but I'm also wearing the pneumatic armor set with these screenshots and testing. Radiation suit didn't help either.

**Comment by Wigalot** [comment]
Are you taking damage from it? If not, it is background radiation at normal levels. I also noticed from your screen shots it says Time to Decay: Xm. Did any radiation effect go away after that time?

**Comment by Saereth** [comment]
This can happy if you die near your base. It will go away on its own (10mins time there you can see on your dosimeter) this is just a product of how mek radiation works, its strong near the starting point and diminishes over many chunks from the source. If you want it gone sooner you can use a cheat command /mek radiation removeAll

The radiation suits/pneumatic armor dont actually prevent radiation poisoning once you have it they only prevent new radiation from occuring.
