### ISSUE TITLE
Terra wart doesn't spawn correctly with snow block underneath

### ISSUE THREAD

**Issue by RobertBouillon** [FTBTeam/FTB-Modpack-Issues#4320]
### Modpack

FTB Genesis

### Modpack version

1.2.2

### Describe the bug

Quest to create terra wart specifies that you can place a snow block under a nether wart plot and a terra wart will grow in its place. This doesn't work. I had to get terra wart via breeding, instead.

### Steps to reproduce

1. Enter farm simulation
2. Place a snow block under a farming plot
3. Place crop sticks on farming plot
4. Plant nether wart

### Expected behaviour

Terra wart appears when nether wart is fully grown

**Comment by DiggityMan420** [comment]
this isnt a 100% chance its like 50/50 and terra starts out red till its grown hope this clears it up

**Comment by RobertBouillon** [comment]
I grew 15~20 to full-size over a snow block on MP. If it's really 50%, something's broken.

**Comment by Saereth** [comment]
I talked to speiger its actually a chance to transform every 12 ticks, even if its full grown so basically just plant it and leave it and it will eventually change
