### ISSUE TITLE
Enhanced farm simulation doesn't produce energy from LV converters

### ISSUE THREAD

**Issue by RobertBouillon** [FTBTeam/FTB-Modpack-Issues#4321]
### Modpack

FTB Genesis

### Modpack version

1.2.2

### Describe the bug

The enhanced farm that's awarded to you from the selective breeding quest comes equipped with immersive engineering thermoelectric generators which don't work. These appear to be disabled by config.

### Steps to reproduce

1. Complete the "Enhanced Farming" quest in the "Selective Breeding" Questline
2. Activate the "Enhanced Farm"
3. Open the floor underneath the LV converters
4. The generators are not producing any power

### Expected behaviour

The generators produce power

**Comment by DiggityMan420** [comment]
allready reported see [4322](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4322)
but i said too thermal dont produce power unless it has some where to put it connact a bat box or lv ic2 machine mine works

**Comment by RobertBouillon** [comment]
> already reported see [4322](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4322)

That was created 3 hours after I created mine. Peep the issue IDs.

Did you guys reproduce my issue, log your own, and call mine a duplicate? :joy:

**Comment by Fidixx** [comment]
sorry when i start making the Report there was nothing about the Problem :)

**Comment by Saereth** [comment]
duplicat, just replace the cables basically
