### ISSUE TITLE
Thermoelectric Generator from IE doesn´t work in adv. Farm

### ISSUE THREAD

**Issue by Fidixx** [FTBTeam/FTB-Modpack-Issues#4322]
### Modpack

FTB Genesis

### Modpack version

1.2.2 and now 1.3

### Describe the bug

In the adv. Farm under the Converters the 3 Thermoelectric Generators doesn´t produce Power.

### Steps to reproduce

goto Adv. Farming Simulation
get some Power from the Converter
no new Power from the Generators

### Expected behaviour

produce Power

### Screenshots

![2023-11-23_08 38 44](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/143183322/6a3fbc91-c2b1-427e-bfeb-139926dfc3a2)

**Comment by Fidixx** [comment]
![2023-11-23_08 40 04](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/143183322/0140fd46-948e-47ce-aa4a-ba5a8ade9257)

**Comment by DiggityMan420** [comment]
they need batbox to work but if you connect a lv bat box before your ic2 machine it wil have power the thermo does show until it has some where to go

**Comment by DiggityMan420** [comment]
no NEW power confirmed

**Comment by Wigalot** [comment]
Switching the cables out for mekanism basic universal cables makes it work, however doing so causes another issue I am about to report. (cables are always present even if you unload the new farm world)

**Comment by Saereth** [comment]
just switch cables, the new version of it comes with them but it isnt retroactive

**Comment by MysticAura** [comment]
So your solution was to suggest switching to the cables which don't unload properly (another issue you closed which is not fixed yet)? Just to clarify.  It would be more accurate to simply tag these issues as 'waiting for mod update', not close them as you're still going to keep getting reports on these still existing issues.
