### ISSUE TITLE
Block placer doesn't work

### ISSUE THREAD

**Issue by RazvanBd** [FTBTeam/FTB-Modpack-Issues#4323]
### Modpack

FTB Genesis

### Modpack version

1.3.0

### Describe the bug

Block placer from Industrial Foregoing dose not place blocks.

### Steps to reproduce

1. use Block placer from Industrial Foregoing

### Expected behaviour

place block

### Additional information

fix: https://www.reddit.com/r/feedthebeast/comments/kqp069/industrial_foregoing_block_placer_not_placing/

/ftbteams party create

/ftbteams party settings_for YOURNAMEHERE ftbchunks:allow_fake_players true

**Comment by jlp1528** [comment]
This is not a bug. Fake player blocking works as intended and is default on for a reason. In singleplayer or with trusted friends, it's not a problem to turn it off, but players must be aware they do so at their own risk.

**Comment by Saereth** [comment]
yeah this is working as intended
