### ISSUE TITLE
Apotheosis Vault Crash

### ISSUE THREAD

**Issue by Knoxxar** [FTBTeam/FTB-Modpack-Issues#4324]
### Modpack

FTB Genesis

### Modpack version

1.3.0

### Log Files

https://pste.ch/jasoqipiqe.pl

### Describe the bug

Every time we attack an opponent, the server crashes. But this is only in a vault.

### Steps to reproduce

1. Go to a vault
2. hit an enemy
3. take a break

### Expected behaviour

hit a mob and take a break

**Comment by DiggityMan420** [comment]
this is happening to me too in desert vault soon as i hit a mob i crash out uploaded crashg and latest logs
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13452298/latest.log)
[crash-2023-11-23_11.38.05-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13452299/crash-2023-11-23_11.38.05-server.txt)

**Comment by BeastyCloak** [comment]
Another log, but functionally the same as before this most recent update.

https://pastebin.com/tBgw9RBV

**Comment by Saereth** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/issues/1084 
waiting to hear back from shadows on this

**Comment by TheLastCreation** [comment]
we don't encounter the error until a boss is about to die. but each time we load after that the server crashes.
https://gist.github.com/TheLastCreation/1f0f37676efcbda66cc61bec44f7bc77
