### ISSUE TITLE
Fatal Crash when right clicking Overgrowth Seed to Floating white flower

### ISSUE THREAD

**Issue by Afrowookie1996** [FTBTeam/FTB-Modpack-Issues#4326]
### Modpack

FTB Genesis

### Modpack version

1.3.0

### Log Files

[crash-2023-11-23_13.45.26-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13450653/crash-2023-11-23_13.45.26-client.txt)

### Describe the bug

Right Clicked it and now cannot load in

### Steps to reproduce

1. Complete Quest for 8 Living Wood and 8 Living Stone
2. Collect Rewards
3. Put down floating white flower
4. Right Click overgrowth Seed on it 

### Expected behaviour

Not Sure

**Comment by DiggityMan420** [comment]
this has been mentioned and told to botania

**Comment by Saereth** [comment]
I've disabled the ability to use these on the plant, it goes on the grass anyway now
