### ISSUE TITLE
[Bug]: OceanBlock 1.10 crash when opening krate

### ISSUE THREAD

**Issue by cfelstead** [FTBTeam/FTB-Modpack-Issues#433]
### Modpack

OceanBlock

### Modpack version

1.10

### Log Files

https://pastebin.com/bmw1C0qz

### Describe the bug

Crashes when opening a krate. I only have one to test with. I believe it is related to something inside.
Same crash occurs if krate is broken.

### Steps to reproduce

I think it is related to an item in the krate and not the krate itself.

However, just open it or break it.

### Expected behaviour

No crash

**Comment by cfelstead** [comment]
Just tried downgrading to 1.9. The issue is still occurring.
However, the world worked prior to upgrading to 1.10. Including opening this krate.

**Comment by Sunekaer** [comment]
Could you try and put this mod in your mods folder and delete old version of it
https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/files/3553742

**Comment by cfelstead** [comment]
> Could you try and put this mod in your mods folder and delete old version of it https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/files/3553742

Do you want me to upgrade back to 1.10 first?

**Comment by Sunekaer** [comment]
Yes please

**Comment by cfelstead** [comment]
Works. Thanks.
