### ISSUE TITLE
Holes in World Gen, open Bedrock to Void.

### ISSUE THREAD

**Issue by HardInk** [FTBTeam/FTB-Modpack-Issues#4332]
### Modpack

FTB Genesis

### Modpack version

1.3.0

### Describe the bug

There are holes in the world everywhere, very eay to stumble into them and fall through into the void.

### Steps to reproduce

Explore world, find hole in bedrock, die in void.

### Expected behaviour

Not find holes in bedrock, and die in the void.

### Screenshots

![Genesis_Exibit_A](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/11012411/18db4ad4-163b-40a7-a082-25959d4577aa)
![Genesis_Exibit_B](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/11012411/d132753f-2cab-44df-b866-faee60b6f3e0)
![Genesis_Exibit_C](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/11012411/0099dbb4-7e2f-4c3c-be85-7df6bf8c3ce2)

**Comment by krazzykid2006** [comment]
Can confirm this has been happening ever since the pack was first released.

It's as if they set the canyons and other structures too deep and they deleted the bedrock everywhere they generate. It's just missing everywhere.

**Comment by Saereth** [comment]
this is not a bug, I designed the worldgen this way, watch your step :p

**Comment by HardInk** [comment]
Is it mentioned in the quest book that bedrock is broken in the overworld? Perhaps it could be clearer if so, as I couldn't see any mention of it in my playthroughs. Stumbling into the void unawares on hardcore makes for a very unsatisfying experience.
