### ISSUE TITLE
Enerigized alloyer doesn’t work from electrodynamics 

### ISSUE THREAD

**Issue by FluffyLlama2** [FTBTeam/FTB-Modpack-Issues#4333]
### Modpack

FTB Genesis

### Modpack version

1.3.0

### Describe the bug

The alloyer doesn’t work I have provided it with sufficient power and trying to set it up with auto rafting from my me system but it’s not working even if I manually place the items into the alloyer

### Steps to reproduce

1 power alloyer
2 try and use it

### Expected behaviour

To produce the items from the recipe

**Comment by Saereth** [comment]
I cant reproduce this, works fine in testing, we'll need some screenshots of your setup to help trouble shoot,

**Comment by FluffyLlama2** [comment]
Did you change any config settings or anything? I can’t remember off the top of my head if there is any config required to do so, if so please let me know
