### ISSUE TITLE
Instance Crash

### ISSUE THREAD

**Issue by HanRiverSong** [FTBTeam/FTB-Modpack-Issues#4334]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Log Files

[2023-11-24-3.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13463826/2023-11-24-3.log)

### Describe the bug

I updated the pack in the launcher and whenever I try to load it, the instance crashes

### Steps to reproduce

1. Open FTB app
2. Open Stoneblock app 3
3. Load instance

### Expected behaviour

For the game to load

**Comment by jlp1528** [comment]
A screenshot of a crash is not helpful. The team needs the actual logs to investigate. You should also try backing up your worlds and reinstalling the mod pack.

**Comment by HanRiverSong** [comment]
> A screenshot of a crash is not helpful. The team needs the actual logs to investigate. You should also try backing up your worlds and reinstalling the mod pack.

Thank you for the help. Hopefully, this is the right file. It's my first time doing this so I wasn't sure.

[2023-11-24-3.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13463797/2023-11-24-3.log)

**Comment by jlp1528** [comment]
That might help, but the _crash_ log referenced in the screenshot you initially posted would be ideal. It was at the bottom and has a characteristic name identifying it as a crash, and it's located in a crash logs folder.

**Comment by jlp1528** [comment]
It looks like your forge is not up to date to support at least one of the mods. Again, please try reinstalling the mod pack.

**Comment by jlp1528** [comment]
My freshly installed instance of Stoneblock 3 1.8.1 worked flawlessly. Have you installed additional mods?
