### ISSUE TITLE
Occultism Master Miner Marid produces Barrier's

### ISSUE THREAD

**Issue by Spaex** [FTBTeam/FTB-Modpack-Issues#4335]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

When using the Master Miner Marid from Occultism inside a Dimensional Mineshaft, it will produce Barrier Blocks.

### Steps to reproduce

1. Place a Dimension Mineshaft (Occultism)
2. Put inside a Master Miner Marid Lamp
3. Wait some time and Barrier Blocks will get produced

### Expected behaviour

According to JEI only Ores should get generated, seems like there are some invalid ores?

### Screenshots

![grafik](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/46825907/ac71dca2-f9f1-433a-a1aa-140723fb7e71)

**Comment by jlp1528** [comment]
I don't think these are barriers. The same icon is used for invalid tags. WEIRD nonetheless!

**Comment by DinnerBeef** [comment]
If you hover over the "barrier" does it say something. In theory, it should say a tag.

**Comment by Spaex** [comment]
> If you hover over the "barrier" does it say something. In theory, it should say a tag.

![grafik](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/46825907/afab23b2-3100-4da8-b213-4ed760fa305c)

**Comment by jlp1528** [comment]
So they are _**actual barriers**_. Interesting. How does that even happen?!

**Comment by Spaex** [comment]
Is solved
