### ISSUE TITLE
CC: Tweaked Monitors are too dim

### ISSUE THREAD

**Issue by Galbi3000** [FTBTeam/FTB-Modpack-Issues#4336]
### Modpack

FTB Genesis

### Modpack version

1.3.0

### Describe the bug

As the title says, the monitor is dim, so dim you can barely see what's being displayed!

### Steps to reproduce

Build a computer. Build a screen. Show something on the screen!

### Expected behaviour

Expected to be able to see the screen content clearly

### Screenshots

![2023-11-24_19 07 45](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/4162256/159c9882-af16-4750-a7ae-8d426a7fa925)

**Comment by Saereth** [comment]
this is just shaders doing shader things, you'll have to tweak your shader settings till you find something that looks good or just toggle them off

**Comment by Galbi3000** [comment]
Not so fast, the screenshot shows I am not using the shader!
