### ISSUE TITLE
[Bug]: Charred bee is unobtainable

### ISSUE THREAD

**Issue by loneztar** [FTBTeam/FTB-Modpack-Issues#434]
### Modpack

FTB Ultimate: Anniversary Edition

### Modpack version

1.0.4

### Describe the bug

Trying to get a Lead Bee which requires at some stage of the breeding process a Charred Bee which is not available in the world and does not have a crafting recipe in the current version (I believe it used to breed from a Brimstone Bee + Skeletal Bee but Brimstone Bees don't seem to exist in the pack)

### Steps to reproduce

Look in JEI for Lead Bee and go to breeding
JEI panel shows recipe for Industrious Bee + Charred Bee
Go to charred Bee recipes
JEI panel shows only Charred Bee + Charred Bee recipe (and info panel lists them as not spawning in the world)

### Expected behaviour

For a recipe to obtain a Charred Bee to exist (or a Brimstone Bee)

**Comment by Raidobw2** [comment]
@MaxNeedsSnacks can't assign to you for some reason (i think until you comment) so a ping will have to do, thanks in advance

**Comment by MaxNeedsSnacks** [comment]
Augh, right, I'm set to busy because of uni stuff... This is probably another one of those were I renamed the bee midway through development and forgot to rename the breeding chains -_- Should be fixed in the next update if that's the case!
