### ISSUE TITLE
Digital miner destroyed when broken with pick that has excavate enchant

### ISSUE THREAD

**Issue by localzuk** [FTBTeam/FTB-Modpack-Issues#4341]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

When you break a Mekanism Digital Miner with a pickaxe that has the Excavate enchantment on it, the game plays the sound like it is breaking a bunch of ore, and the digital miner disappears, gone for good.

### Steps to reproduce

1. Have a pick with the Excavate enchant on it
2. Break a digital miner
3. Miner disappears entirely

### Expected behaviour

Miner breaks and drops

### Screenshots

The pick I used:

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/998988/ec432f4b-d177-42fc-abb1-02b24a0746ce)

**Comment by DinnerBeef** [comment]
https://github.com/Lothrazar/Cyclic/issues/2193

**Comment by DinnerBeef** [comment]
This issue has been reported to the mod dev. Sadly, it looks like the mod dev has not resolved the issue, so will we be closing this issue.
