### ISSUE TITLE
FTB Genesis - Initializing game crash

### ISSUE THREAD

**Issue by kennethvasquez93** [FTBTeam/FTB-Modpack-Issues#4344]
### Modpack

FTB Genesis

### Modpack version

1.3.1

### Log Files

https://pste.ch/idilapuxix.pl

### Describe the bug

Just installed the modpack today after watching Chosen Architect play it. Tried to start the modpack, but it crashes before the minecraft window opens (the one that shows forge loading screen). I have tried to increase the RAM with no luck. Even uninstalled the modpack in installed it again to see if maybe it somehow got corruped, but still get the same crash at the same time.

### Steps to reproduce

1. Install modpack.
2. Change to Java 17 (default settings is Java 8).
3. Launch the modpack.
4. Get the crash

### Expected behaviour

I expected the modpack to fully launch wihtout any crashes

**Comment by kennethvasquez93** [comment]
![FTB_Genesis_1 3 1](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20266731/d3f2622a-4502-416a-be69-75b1dfc46f37)
I saw in the crash log something about MineTogheter mod. So i just tried to dissable that mod and launch the modpack, and now it fully launches (excpet i'm apparently missing Fancymenu 2.6.4 or above and Fancymenu 2.14.4 or above. Not sure why i'm missing those mods, but will add it and see if the modpack will launch correctly.

**Comment by Saereth** [comment]
yeah this looks like your download just failed to get some key files, reinstall would probably be best just in case it is missing any more crucial files like scripts or world region files

**Comment by shinji257** [comment]
I hit into this using Prism Launcher to grab the pack.  For whatever reason fancymenu got installed as disabled.  However I went over and used FTB App and couldn't reproduce it there.  There are two possibilities that are there...

1) The manifest for this pack as fancymenu marked as disabled in error but FTB App ignores that.
2) There is some screw up with non official apps that caused this mod to get disabled in error

These are just the ones I could think of.  I can't see the manifest for FTB packs so I can't check it myself.

**Comment by LazyPsychopomp** [comment]
Yeah, for anybody not in the know, you can go into the mods folder and just remove the disable affix by renaming it and it will run fine. My assumption is it is some kind of anti third party thing or just a simple mistake.
