### ISSUE TITLE
Taking more damage while wearing Composite armour compared to the Hazmat suit

### ISSUE THREAD

**Issue by OhmegaWolf** [FTBTeam/FTB-Modpack-Issues#4345]
### Modpack

FTB Genesis

### Modpack version

1.3.1

### Describe the bug

When wearing composite armour it seems to fail to negate damage. The Hazmat suit is a lower tier armour yet negates way more damage

### Steps to reproduce

Try wearing both types of armour and let a mob hit you, the damage difference should be clear

### Expected behaviour

Composite armour should be alot better

**Comment by Saereth** [comment]
ok this one Im sending over to speiger, statsitically the composite is better in every way, very odd behavior
