### ISSUE TITLE
[Bug]: Enderstorage crashes the Game

### ISSUE THREAD

**Issue by PLEisenherz** [FTBTeam/FTB-Modpack-Issues#435]
### Modpack

FTB OceanBlock

### Modpack version

1.10.0

### Log Files

https://github.com/PLEisenherz/Logs/blob/main/Log%20FTB%20OB

### Describe the bug

When MC tries to render Enderstorage Tank it crasches back to Desktop. Same goes for rendering it in in JEI.
Tried Ender Storage 1.16.5-2.8.0.168 ,-166  and -161. Same Problem. Game Crasches Back to Desktop.
I dont know if it is a compatility Problem or the Enderstorage itslelf.

### Steps to reproduce

None

### Expected behaviour

No Crash.

**Comment by Sunekaer** [comment]
Could you try and put this mod in your mods folder and delete old version of it
https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/files/3553742

**Comment by Sunekaer** [comment]
#433
