### ISSUE TITLE
Attempting to change Pneumaticcraft values crashes the game

### ISSUE THREAD

**Issue by Runisco** [FTBTeam/FTB-Modpack-Issues#4350]
### Modpack

FTB Genesis

### Modpack version

1.3.1

### Log Files

https://pste.ch/pivoniqiqe.rb

### Describe the bug

Game crashes when I try to edit the values for Pneumaticcraft

### Steps to reproduce

1: Open up mods
2: find Pneumaticcraft
3: click on client settings, then armor
4: crash

### Expected behaviour

I should've been able to change values

**Comment by DiggityMan420** [comment]
confirmed i had to do it off line
