### ISSUE TITLE
some Ars Nouveau glyphs not consuming all items to craft

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4352]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

Some of the Ars Nouveau glyphs properly require all listed items, others do not. In particular, "Exchange", which should require an emerald block, two ender pearls, and a manipulation essence only took the essence!

### Steps to reproduce

1. Attempt to craft Ars Nouveau "Exchange" glyph.
2. Only manipulation essence consumed for Scribe's Table to craft it.

### Expected behaviour

Items listed should be required.

**Comment by DinnerBeef** [comment]
Unable to reproduce it
