### ISSUE TITLE
Reactivate the Arid Nexus Continous crash

### ISSUE THREAD

**Issue by mccaan** [FTBTeam/FTB-Modpack-Issues#4354]
### Modpack

FTB Genesis

### Modpack version

1.3.1

### Log Files

[crash-2023-11-26_19.44.58-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13467777/crash-2023-11-26_19.44.58-server.txt)

### Describe the bug

When I arrive the second vault the server crash always with the same error:

java.lang.NullPointerException: Cannot invoke "shadows.apotheosis.adventure.loot.AffixLootEntry.getStack()" because the return value of "shadows.apotheosis.adventure.loot.AffixLootManager.getRandomItem(net.minecraft.util.RandomSource, float, java.util.function.Predicate[])" is null

### Steps to reproduce

Start the reactivate the arid nexus and arrive the second vault

once you go deep  into the vauld the game crashes after a minute

### Expected behaviour

Get into the vault, fight the enemies and continue with the quests

**Comment by mccaan** [comment]
Changed from Oracle Java 17 to OpenJDK 21 and the issue is the same

**Comment by Sirat18** [comment]
I have the same issue. Probably something with the rewards from clearing the gates. Quick fix was to change the rewards section in kubejs/data/gateways/gateways/desert_gate.json to no rewards:

```
  "rewards": [
  ],
```

Probably the same for the next gate configs.
