### ISSUE TITLE
solar neutron activators think they can't see the sun on world reload

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4355]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

See issue also posted by me on Mekanism GitHub:
https://github.com/mekanism/Mekanism/issues/7940

It's been suggested to me by those in the Mekanism Discord that this could be an issue with other mods affecting sky visibility. Please investigate.

### Steps to reproduce

see link

### Expected behaviour

SNAs should just work if they can see the sun.

**Comment by DinnerBeef** [comment]
Hmm. Everything seems to be working fine for me. Just to make sure. Is everything chunk loaded? That would be the only thought  I would have on why it's not working right.

**Comment by jlp1528** [comment]
The area is all chunk loaded. I could share the relevant part of the world on google drive or something.

**Comment by DinnerBeef** [comment]
I don't have this issue. Please let me know what happens in the next update.

**Comment by jlp1528** [comment]
This appears resolved now.
