### ISSUE TITLE
instance crashing on load - "A[n AE2] node is being used after it has been destroyed."

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4357]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Log Files

[crash-2023-11-26_16.46.24-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13468358/crash-2023-11-26_16.46.24-server.txt)

### Describe the bug

world not loading

### Steps to reproduce

I don't know what I did, but someone on the Discord suggested it might be a bad interaction between Applied Energistics 2 crafters and Entangled blocks.

### Expected behaviour

my world should load

**Comment by DinnerBeef** [comment]
To test to see if this is entangled causing the issue.

1. Make a backup of your world
2. Disable entangled mod
3. Start the game
4. Join and world and see what happens.
5. Let me know what happens

**Comment by jlp1528** [comment]
I should have done this just for debugging purposes, but unfortunately I have managed to restore from a backup and played too long since. If it happens again, I will try this, but you may close the issue for now.
