### ISSUE TITLE
[Bug]: Rendering crash due to endertank since 1.10.0

### ISSUE THREAD

**Issue by Atreyon** [FTBTeam/FTB-Modpack-Issues#436]
### Modpack

FTB Oceanblock

### Modpack version

1.10.0

### Log Files

https://paste.feed-the-beast.com/view/61a4a362

### Describe the bug

Game crashes when trying to load my world in the new 1.10.0. Probably an issue with endertanks if i read my logs correctly.

### Steps to reproduce

1. Create a world in 1.9 and use endertanks in some way
2. Update to 1.10
3. try to load your world
4. Crash the game

### Expected behaviour

No crashes

**Comment by Sunekaer** [comment]
#435
