### ISSUE TITLE
apotheotic bosses not spawning in end, config WAI but is this config itself intended?

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4360]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

Currently, apotheotic bosses are only set to spawn in the nether, which they are doing correctly, but only ever epics, not mythics. As far as I know, mythic bosses only spawn in the end, and while it is possible to get mythic items from regular mobs, the chance is EXTREMELY rare and requires player kills. Is this intended, or should mythic apotheotic  bosses be spawning in the end? Also, time required between natural boss spawns is currently set to 10 hours. Again, intended???

### Steps to reproduce

1. look at configs
2. also observe no apotheotic bosses in the end

### Expected behaviour

mythic bosses in end, shorter min spawn delay?

**Comment by DinnerBeef** [comment]
Thanks for reporting and issue, However this is working as intended and will not be fixed.
