### ISSUE TITLE
luzzz

### ISSUE THREAD

**Issue by BoomZA3** [FTBTeam/FTB-Modpack-Issues#4361]
### Modpack

FTB Skies

### Modpack version

1.2

### Describe the bug

I can't adjust the speed of the electric motor.

### Steps to reproduce

1. I want to increase the speed of the Electric Motor, but I can't. 2. So I don't look for other people's methods. 3. When I try it, nothing happens.

### Expected behaviour

ฉันต้องการวิธีแก้ไข

**Comment by jlp1528** [comment]
If you're talking about the electric motor from the Create addon, just hold Rclick on the back and drag.
