### ISSUE TITLE
Can’t craft crop harvester from IC2

### ISSUE THREAD

**Issue by pavelbeard** [FTBTeam/FTB-Modpack-Issues#4362]
### Modpack

FTB Genesis

### Modpack version

1.3.1

### Describe the bug

The recipe doesn’t work, nowhere and no one of crafting tables/grids 

### Steps to reproduce

Try to craft this item

### Expected behaviour

No

**Comment by pavelbeard** [comment]
Thanks, that is work only with manual craft

**Comment by Saereth** [comment]
stacked crafting requires tables that support it so standard crafting table or the ic2 specific industrial workbench table, there is a quest to make one in both the ic2 chapter and the seed chapter
