### ISSUE TITLE
Uranium dust not processed in Netherite Furnace

### ISSUE THREAD

**Issue by localzuk** [FTBTeam/FTB-Modpack-Issues#4363]
### Modpack

FTB Direwolf20 1.20

### Modpack version

1.7.0

### Describe the bug

I've got a Netherite furnace, upgraded wireless heat receiver, and uranium dust will not process. If I switch out to coal, it works.

### Steps to reproduce

1. Have netherite furnace
2. Set up a wireless heat receiver so it gets energy to the furnace
3. Test it processes stuff (throw some iron ore in there or something)
4. Now try the same with uranium dust from mekanism

### Expected behaviour

Uranium dust should become uranium ingots.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/998988/77db5c84-c8f4-4559-8741-a077333078cf)

**Comment by localzuk** [comment]
Sorry, chose wrong pack - should be FTB Direwolf20 1.20

**Comment by DinnerBeef** [comment]
Unable to reproduce. Can you please let me know if this is stilling happening in version 1.8.0.

**Comment by localzuk** [comment]
Yes, this is still an issue in 1.8.0. Exact same setup - Netherite furnace with a wireless heat receiver in it.

Note, it works fine if you swap out the wireless heat receiver for coal.

**Comment by localzuk** [comment]
Just updated to 1.9.1 and the issue persists.

**Comment by DinnerBeef** [comment]
I am unable to reproduce this bug. Have you tired of replacing the iron furnace to see what happens?

**Comment by localzuk** [comment]
Ah, turns out, its when it has a speed augment in it. Just built an entire new setup, missing that augment and the uranium cooks fine. Add the speed augment and it stops working.
