### ISSUE TITLE
Bug or Intended 64x Upgrade

### ISSUE THREAD

**Issue by DiggityMan420** [FTBTeam/FTB-Modpack-Issues#4364]
### Modpack

FTB Genesis

### Modpack version

1.3.1

### Log Files

no log

### Describe the bug

just tried speed upgrades so far but is it mek ftb or me upto 64 x speed upgrades i swore it was 8 max if this is intented. Cool :) my machines will be quick and im sorry i didnt know mek changed it.

### Steps to reproduce

make a mekanism machine
make speed upgrades

### Expected behaviour

8 max

### Screenshots

![Screenshot_6](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/864de22c-50a1-4deb-80d1-0ba37daa2035)

**Comment by DiggityMan420** [comment]
![Screenshot_7](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45196448/8ee6393a-181d-44a6-bd4e-8595e2b6500a)
so you see it goes over 8 like i said maybe mek changed it and i didnt realize its new

**Comment by jlp1528** [comment]
I believe these are configurable, but 64 seems like a bit much. You never know though!

**Comment by Saereth** [comment]
this is intended, if you can actually power it, have fun :p
