### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by ShadowBeastSW** [FTBTeam/FTB-Modpack-Issues#4366]
### Modpack

FTB OceanBlock

### Modpack version

1.16.0

### Describe the bug

electrotice generator freezes the game when im trying to put in/take out anything by Shift+Clicking in the machine Mod:ProjectRedCore.

### Steps to reproduce

1

### Expected behaviour

2

**Comment by manmaed** [comment]
This issue is stale and pack is no longer being worked on
