### ISSUE TITLE
Server crashes on client connection after update to 1.8.0 

### ISSUE THREAD

**Issue by Bluebottle39** [FTBTeam/FTB-Modpack-Issues#4367]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.8.0

### Log Files

[crash-2023-11-29_19.58.53-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13504553/crash-2023-11-29_19.58.53-server.txt)

### Describe the bug

After update to latest version of the pack (1.8.0) the server crashes when client tries to connect.

### Steps to reproduce

Start server
try to connect with client
server crashes

### Expected behaviour

server not crashing and successful connection 

### Additional information

Downgrading to previous version of enderio (EnderIO-1.20.1-6.0.21-alpha) fixes it.

Obserservation, I have added a couple mods to the pack in case it's relevant but the error seems to be related to enderio which shouldn't be affect by them:

apotheotic additions
scannable
JustEnoughMekanismMultiblocks
ftb-ultimine
Polymorphic Energistics
Refined Polymorphism

**Comment by TheWolfNations** [comment]
+1 on this, Server crashes every 20-30mins with the exact same error. Looks like EnderIO, as going to previous version as you stated works fine but isn't a solution for a full server, so rolled back to 1.7.0 until fixed.

**Comment by Bluebottle39** [comment]
Looks like this was fixed in dev by enderIO. Have to wait for next version.
Team-EnderIO/EnderIO#574
