### ISSUE TITLE
Hostile Neural Networks 'Predictions' get corrupted when placed in a Industrial Foregoing 'Black Hole Unit'

### ISSUE THREAD

**Issue by TheTrueDV** [FTBTeam/FTB-Modpack-Issues#4368]
### Modpack

FTB Genesis

### Modpack version

1.3.1

### Describe the bug

It seems when you pump predictions into a Black Hole Unit controller they get converted into a corrupted form. I'm guessing it's todo with NBT being wiped?

This only happens when you pump it into the controller, not into the Black Hole Units by themselves.

### Steps to reproduce

1. Get a Hostile Neural Network's prediction. Seems to impact them all.
2. Put them in a barrel or any other storage medium.
3. Place down a Black Hole Unit Controller
4. Put a Black Hole Unit (I used a Common tier one) inside the controller
5. Connect the barrel and the controller with a Mekanism logistical pipe (Unsure if it happens with other connections)
6. Wait for the prediction to be fed into the controller and then remove the Black Hole Unit from the controller.
7. You should now see that the prediction is a grey colour and removing the item from the Black Hole Unit should reveal a now corrupted prediction.
![image_2023-11-29_191808655](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/83378046/2db3b004-ccf7-4206-b625-a90ffb7954e8)

### Expected behaviour

Items should be stored normally and NBT should be maintained.

**Comment by Saereth** [comment]
There are several issues reported on IF's github looks like with storing nbt data items in a black hole can be problematic, we'll hope for an update to fix but if one doesnt come in a bit we may have to look into disabling those blackhole storages. I'd avoid anything with extra item data on them for now.
