### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by Bluebottle39** [FTBTeam/FTB-Modpack-Issues#4369]
### Modpack

FTB Presents Direwolf20 1.20

### Mod suggestion

Apotheotic Additions:
https://www.curseforge.com/minecraft/mc-mods/apotheotic-additions
Adds gems and affixes that integrate with other mods

Refined Polymorphism:
https://www.curseforge.com/minecraft/mc-mods/refined-polymorphism
Adds polymorphism support to Refined storage terminals

Polymorphic Energistics:
https://www.curseforge.com/minecraft/mc-mods/polymorphic-energistics
Adds polymorphism support to Applied Energistics 2 terminals

FTB Ultimine:
https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge
Adds vein mining for qol

**Comment by jlp1528** [comment]
I definitely second the polymorph mods just to avoid any recipe conflicts in automation. However, vein mining is added by certain enchantments, tools, etc. in this pack. As for Apotheotic Additions, it looks interesting, but mods need to fit with the idea of the pack and be approved by FTB and in this case direwolf20 himself. So I'm not sure on that one.

**Comment by DinnerBeef** [comment]
I am going to say no to all of these. If there are any recipes conflicts, please let me know. There should not be any in this pack.
