### ISSUE TITLE
[Bug]: 1.10.1 seems to not allow one to make processing recipes in Refined Storage

### ISSUE THREAD

**Issue by e30Birdy** [FTBTeam/FTB-Modpack-Issues#437]
### Modpack

FTB OceanBlock

### Modpack version

1.10.1

### Describe the bug

I made a bunch of autocrafting patterns and now trying to make one for Grout to Seared Bricks and I cannot shift click in the recipes. Nor can you drag and drop from the right. Made a video to show.

If mode is not processing it does let one drag from the right. Just seems processing mode is broken.

### Steps to reproduce

I show all the steps in video link I attached.

### Expected behaviour

Click the plus and create processing recipe or ability to drag and drop parts into recipe from JEI

### Screenshots

https://youtu.be/hfr6rIG2Crc

**Comment by Sunekaer** [comment]
This works fine for me in testing, due you have any errors in log?

**Comment by e30Birdy** [comment]
> This works fine for me in testing, due you have any errors in log?

[07:51:41] [ERR  ] server_scripts:tags.js:177: + items:ftbob:recyclable // tconstruct:earth_slime_boots [Not found!]
[07:51:42] [ERR  ] server_scripts:mods/recipes.recycler.js:16: Failed to create recipe for type 'recycler:recycler': tconstruct:earth_slime_boots is not a valid ingredient!

**Comment by Sunekaer** [comment]
Any error when trying to create your pattern?

**Comment by e30Birdy** [comment]
> Any error when trying to create your pattern?

Nope, just like you see in the video it just does nothing. It is weird because in 1.9 which was using the same version of RS this worked perfect.

**Comment by Sunekaer** [comment]
hmm yea, and it works in my world.
Could you try an new world? maybe an new instance of the pack?
Are you in SP or MP?

**Comment by e30Birdy** [comment]
I am playing on a local hosted server on the same PC I play one, each with 8gb dedicated. I tried the same world is SP and it didn't work there either. I made a new SP world and it works

**Comment by Sunekaer** [comment]
Hmm then i would recommend reporting to Refined Storage, so they can look at whats wrong in your current world

**Comment by e30Birdy** [comment]
I put in a ticket with them to see if they can figure this out.

**Comment by Sunekaer** [comment]
Awesome, feel free to open an new ticket here if we need to do anything.
Thanks

**Comment by e30Birdy** [comment]
> Awesome, feel free to open an new ticket here if we need to do anything. Thanks

My pattern terminal was in fluid mode, no clue why as I didn't change it so I wouldn't have even thought of that. Someone posted a screenshot and now I feel like a moron as no one else has caught that either. I never use fluid mode as I store it all in black holes.
