### ISSUE TITLE
Ars nouveau book showing error

### ISSUE THREAD

**Issue by Klawn** [FTBTeam/FTB-Modpack-Issues#4370]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.8.0

### Log Files

[2023-11-29-4.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13505453/2023-11-29-4.log)

### Describe the bug

When i try to open the book for ars nouveau, it shows : Loading error (hover for info)
the tooltip shows : Error building entry ars_nouveau:familiars/summoning_familiars of book ars_nouveau:worn_notebook
Error while building entry ars_nouveau:familiars/summoning_familiars page 3 of book ars_nouveau:worn_notebook
Could not find entry ars_nouveau:rituals/binding
Check your log for more

### Steps to reproduce

Run a save
open ars nouveau book

### Expected behaviour

Book displaying the information for the mod ars nouveau

### Screenshots

![2023-11-29_19 11 53](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/152443162/037d3d12-8726-4fd9-9687-57704c161b06)

### Additional information

The only way i've been successfull to make it work was to rollback the version of Patchouli to Patchouli-1.20.1-81-FORGE and disabling Botania and Applied botanic

**Comment by Klawn** [comment]
The label is wrong, the modpack is FTB Presents Direwolf20 1.20, i don't know how to edit it

**Comment by dalgrim** [comment]
I can confirm this issue on Direwolf20 1.20, pack version 1.8.0

**Comment by Medivha** [comment]
it is a error with patchouli and reverting to Patchouli-1.20.1-81-FORGE should fix it for now
[
source](https://github.com/baileyholl/Ars-Nouveau/issues/1168)

**Comment by Medivha** [comment]
Oh, sorry, I totally oversaw that information. My bad.
