### ISSUE TITLE
Refined Storage MOD - Missing Extra Mods

### ISSUE THREAD

**Issue by DanielColunas** [FTBTeam/FTB-Modpack-Issues#4375]
Hello, Extra Disks and Extra Storage are already on this version, would you be so kind to add them to the modpack please?
Thank you!

Links to Mods:
> https://www.curseforge.com/minecraft/mc-mods/extra-disks
> https://www.curseforge.com/minecraft/mc-mods/extrastorage

I believe this mod is needed too:
> https://www.curseforge.com/minecraft/mc-mods/edivadlib

Cheers

**Comment by DinnerBeef** [comment]
A lot of this can be found in the Reborn Storage mod.
