### ISSUE TITLE
When leaves decay, holding the veinminer key makes your tool take full durability damage as if you had broken all of them yourself

### ISSUE THREAD

**Issue by SmolFloofyRedhead** [FTBTeam/FTB-Modpack-Issues#4376]
### Modpack

FTB University 1.19

### Modpack version

1.3.1

### Describe the bug

I noticed that whatever kind of fast leaf decay mod this pack has breaks the leaves instead of just triggering their decay rapidly. It interacts strangely with Ultimine. If I'm holding the key at all when the leaves "decay", it acts as if I broke all of them, nuking my axe's durability. The result is I have to release the key and wait a few seconds for the mod to trigger after every single tree.

### Steps to reproduce

Veinmine any tree.
Continue to hold the key, as if you're moving on to the next tree. Side mouse button bind makes this far easier.
Axe durability goes poof.

### Expected behaviour

The leaves should simply decay (or break with this mod) without it being "done by the player" under the hood.

### Additional information

Probably the easiest fix would be to switch to a mod that actually decays the leaves instead of mimicking a player breaking them all.

**Comment by aaronhowser1** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/assets/15698722/f0f3c9ae-8b17-4dd2-a9db-26c27d62398e

Unable to reproduce

**Comment by mellamokb** [comment]
I am seeing this behavior in FTB StoneBlock 3 as well on the latest version, when using a Tinker's tool.  If I keep the Ultimine key held when the instant leaf decay kicks in, it triggers all the leaves as durability on the tool.

https://github.com/user-attachments/assets/e2b9993f-ceee-406c-aacb-0524967b9c55

**Comment by SmolFloofyRedhead** [comment]
This is still a problem? Jeez. I did try to record it ages ago, but the size was too big and I gave up. That clip might not show enough though. I'm surprised more testing wasn't done and that I'm the only one that mentioned anything for so long when it's in 2 packs.
