### ISSUE TITLE
Creative Flight runs out after a few seconds.

### ISSUE THREAD

**Issue by TheTrueDV** [FTBTeam/FTB-Modpack-Issues#4377]
### Modpack

FTB Genesis

### Modpack version

1.3.2

### Log Files

https://pste.ch/evunotupaj.pl

### Describe the bug

Any form of creative flight runs out after a few seconds.
This doesn't impact Jetpack or elytra flight. Only creative flight while in survival mode.

### Steps to reproduce

1. Choose a form of creative flight such as Supremium armor (with Flight Augment) from MysticalAgriculture, Ethereal Wings from Nameless Trinkets, Flugel Tiara from Botania or the /fly command
2. Rise up into the air, just a 4-5 blocks so you're not on the ground anymore.
3. Do nothing and wait.
4. After a short period of time, you'll just drop to the floor again.

I have tested this in a isolated environment with just Mystical Agriculture and the Supremium armor works as expected. This seems to be an issue with mod compatibility.

### Expected behaviour

At least with the Supremium armor, creative flight should be infinite and you should never fall.

**Comment by krazzykid2006** [comment]
This has been an ongoing issue in every version of the pack.

I sure do hope the communication doesn't stay private here, because many of us would like the answer as well.

**Comment by krazzykid2006** [comment]
I also want to point out that this isn't just happening near the main base, meaning it doesn't only happen when you are in proximity to the environmental controller. 

I've had it happen still when in the nether for example, although sometimes when I am in the nether it happens and other times it doesn't and stays working.

If I am in the overworld or in the spatial dimension then it happens constantly and with 100% consistency.

**Comment by TheTrueDV** [comment]
> This has been an ongoing issue in every version of the pack. I sure do hope the communication doesn't stay private here, because many of us would like the answer as well.
> 
> It is definitely a repeating cycle that happens every few seconds. Flight shuts off every time the cycle happens.
> 
> It affects every single form of flight that isn't gliding (elytra and gliders aren't affected as they are gliding). The only form that isn't affected is if you are in actual creative mode. All other forms of creative flight outside creative mode shut off.
> 
> It is quite the letdown for sure. I spent WAY too much time grinding to get to this point only for it to be broken. Was definitely enough to make me rage quit for now.

@krazzykid2006 
I unlocked several forms of flight in order to trial this- Mystical, Botania, Trinkets for creative flight. As mentioned those all failed.
Jetpacks and Jetpacks in Nano/Quantum armor however had no issue, other than having to recharge them every so often.
PneumaticCraft's elytra upgrade also works just fine with fireworks or jump boost enchantments.

If you're having issues staying in the air even using a jetpack's advance hover mode I suspect you're facing a separate issue.

**Comment by fusionnrg** [comment]
i find that setting the ECU to "mobs"  made it no longer affect me but still keep things peaceful, If that can be set as the  default in the ECU  at least you can fix it going forward.

**Comment by TheTrueDV** [comment]
Heya
Sorry for the delay. I completed this pack last year and hadn't checked Github in a while.

I've created some new saves to test this. (Not sure where my original save is stored at this point)
I tried on two saves: One created in 1.3.1 (Since 1.3.2's world creation was busted) and one created in 1.7.0.

The save created in 1.3.1 was moved over to 1.7.0 in order to test if it was an issue with the world generation (I.e, the environmental controller having bad settings) or if it was an issue with the mod versions. 

It seems both the 1.3.1 world and the 1.7.0 world still have the issue. 
The fix mentioned above (setting the environmental controller to use 'Mobs' instead of 'Blacklist') still seems to resolve the issue.

Let me know if you need anything.
