### ISSUE TITLE
[Bug]: Ultimate AE Compressor doesn't compress Cinnabar fragments

### ISSUE THREAD

**Issue by mtbrenner** [FTBTeam/FTB-Modpack-Issues#438]
### Modpack

FTB Ultimate Anniversary Edition

### Modpack version

1.0.4

### Describe the bug

The Compressor doesn't compress cinnabar fragments.

### Steps to reproduce

Put 7 cinnabar fragments into the Compressor, should compress this to 1 chunk, but nothing is happening (no progress bar).

### Expected behaviour

Compress to 1 cinnabar chunk

### Additional information

 The recipe works in Multiservo Press (Thermal) and I have compressed other things in the Compressor.

**Comment by LatvianModder** [comment]
Seems like the timer was off. So its actually compressing but ridiculously slow
