### ISSUE TITLE
Growthcraft: Cannot plant rice.

### ISSUE THREAD

**Issue by swestrup** [FTBTeam/FTB-Modpack-Issues#4381]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.20.1

### Describe the bug

Tilled some farmland and turned it into cultivated land with the cultivator. Waterlogged it with a bucket, and tried to plant rice, as the manual suggests. Rice will not plant. It cannot be planted under any light levels, on any sort of soil I've tried.

### Steps to reproduce

Create Cultivated land.
Waterlog it.
Try to plant growthcraft rice.
rice refuses to plant.

### Expected behaviour

rice should be planted.

**Comment by DinnerBeef** [comment]
Working fine for me. What are you trying to plant? You need to plant Rice item?

**Comment by swestrup** [comment]
Your question about what I was trying to plant puzzled me, as the only thing I had ever found was a rice stalk, which doesn't plant. It never occurred to me that you would plant the ready-to-cook rice that comes from the stalk.

**Comment by DinnerBeef** [comment]
Did this fix your issue then?

**Comment by swestrup** [comment]
Yes. Sorry I wasn't clear. Planting the cookable rice totally works, its planting the stalks that didn't work.
