### ISSUE TITLE
Ender Inventory key opens inventory from previous world when it hasn't been unlocked yet

### ISSUE THREAD

**Issue by ttufts** [FTBTeam/FTB-Modpack-Issues#4382]
### Modpack

FTB Skies

### Modpack version

1.3.1

### Describe the bug

Started a new FTB Skies world and in early game I accidentally hit the keybind to open my Ender Inventory extra space. It opened the inventory from my previous world, along with the items that were in that inventory. 

### Steps to reproduce

1. Create a world
2. Get Ender Inventory Cake
3. Eat it
4. Add items to inventory
5. Create a second world
6. Open Ender Inventory in second world

I haven't attempted to cleanly reproduce this bug, but this is roughly what happened to me. 

### Expected behaviour

I assume the inventory keybind shouldn't work at all until the inventory cake has been eaten.

**Comment by ttufts** [comment]
Update: when eating the ender inventory cake in my second world, initially the cake didn't work at all. I gave myself a second cake and it worked and allowed me to open the inventory, but it is still the same inventory from my previous game.

**Comment by ttufts** [comment]
Switched over to the first world, moved items out of the ender inventory and then back to the second world, the items were still in the ender inventory. Seems to have copied the first world's inventory on world creation perhaps.

**Comment by Saereth** [comment]
very odd, I cant seem to reproduce this in dev but cyclic was updated so perhaps its fixed now
