### ISSUE TITLE
Single player freezes and crashes when creating world

### ISSUE THREAD

**Issue by piedrrum** [FTBTeam/FTB-Modpack-Issues#4383]
### Modpack

FTB Genesis

### Modpack version

1.3.2

### Log Files

[crash-2023-12-02_00.29.25-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13532994/crash-2023-12-02_00.29.25-server.txt)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13532995/latest.log)

### Describe the bug

When creating a new world in single player, it freezes during generation and instance must be killed.

### Steps to reproduce

Single player
Generate any world in 1.3.2

### Expected behaviour

See world loading screen then get player view.

**Comment by jlp1528** [comment]
Is the world created at all? The server has this problem, but it resolves with a reload. If the world is created, try loading it again.

**Comment by Saereth** [comment]
delete serverconfigupdater.toml in /config/ folder, it should allow it to start, I'll get a proper fix out for this tomorrow

**Comment by piedrrum** [comment]
@Saereth  Deleting this make it works, @jlp1528 I fear to begin my journey on a corrupted world but it looks like this is not related.
Thank you all for working on this cool modpacks !
