### ISSUE TITLE
Mythical Agriculture Tin Seed Petal Apothecary recipe is incompletable.

### ISSUE THREAD

**Issue by Bulleft** [FTBTeam/FTB-Modpack-Issues#4384]
### Modpack

FTB Genesis

### Modpack version

1.3.2

### Describe the bug

When crafting a tin seed on the Petal Apothecary the recipe calls for 4 "Mekanism" tin ingots but all smelted ingots are IC2 ingots. The Petal Apothecary is not allowing a substitution to complete the craft.

### Steps to reproduce

1. Gather ingredients for Tin Seed Petal Apothecary craft.
2. Attempt craft.

### Expected behaviour

A Tin Seed should have been created.

### Screenshots

![Screenshot (1)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/152677679/f2b682ba-cccc-4899-942c-3236ce028f30)
![Screenshot (2)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/152677679/7e76f697-2240-43fb-92bb-139cc8a70978)
![Screenshot (3)](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/152677679/97232f55-a837-43e4-a6fe-699717ab6952)

**Comment by TheTrueDV** [comment]
You need the mekanism ingot. Oredicting this might be good, but just craft those ingots into a nugget and then back to ingots. Should get mekanism ones!

**Comment by Bulleft** [comment]
> You need the mekanism ingot. Oredicting this might be good, but just craft those ingots into a nugget and then back to ingots. Should get mekanism ones!

This was the answer. It's weird as none of the recipes for the tin ingots state it will create an IC2 ingot so I had assumed nuggets to bar would have done the same as well. It was the only thing left I could have done and I just gave up I guess.
