### ISSUE TITLE
Cardboard box on Flawless certus crash game

### ISSUE THREAD

**Issue by Pyrocrisis** [FTBTeam/FTB-Modpack-Issues#4388]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.8.0

### Describe the bug

Trying to use a cardboard box from mekanism on naturally spawned in meteor flawless budding certus block crashes client.

### Steps to reproduce

Find AE2 meteor with flawless budding certus
Right click on certus block with cardboard box.
Game crash

### Expected behaviour

Pick up the block I guess not even sure how cardboard box works yet to be honest

**Comment by DinnerBeef** [comment]
Please send the crashlog

**Comment by Pyrocrisis** [comment]
[crash-2023-12-02_12.58.42-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13550315/crash-2023-12-02_12.58.42-client.txt)
