### ISSUE TITLE
[Suggestion]: Grout recipe for Mystical Agriculture

### ISSUE THREAD

**Issue by Tokoshoran** [FTBTeam/FTB-Modpack-Issues#439]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

Thought it was a bit silly that you can craft so much sand, gravel, and clay through mystical agriculture, but couldn't just combine their recipes into a grout recipe. Although a direct conversion would require twelve crafting slots, even at a halved rate gravel and sand still produce 8 blocks, so I was thinking something like this:
![image](https://user-images.githubusercontent.com/5721448/145123071-9a7d2fb1-9792-4e81-9404-ea8dd8f7b573.png)
This would result in a net loss of one block of clay on the halved-recipe halved-result idea, but to skip three other recipes I think it'd be worth the slight loss.

**Comment by Sunekaer** [comment]
Yeah i like this recipe, ill add it
