### ISSUE TITLE
Trinkets/backpacks dissapearing

### ISSUE THREAD

**Issue by Kaiclye** [FTBTeam/FTB-Modpack-Issues#4393]
### Modpack

FTB Inferno

### Modpack version

newest

### Describe the bug

Basically my trinkets and backpacks will randomly vanish from my inventory. It's causing me to really struggle to play.

### Steps to reproduce

collect a bunch of items at once after killing many mobs is usually when i notice its happened

### Expected behaviour

I personally lost, my backpack, the magnet coin item, exalted crafter, and my light mushroom

**Comment by Saereth** [comment]
can you post your world/serverconfigs/champion* files here?
