### ISSUE TITLE
LaserIO Card Holder box doesn't show for Energy Cards

### ISSUE THREAD

**Issue by BubbaVB** [FTBTeam/FTB-Modpack-Issues#4394]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.8.0

### Describe the bug

When you right click on any LaserIO card within a node it normally displays the card holder screen on the left.  This is not happening with Energy Cards.  The 2 attached screenshots show what you see when right clicking on a card other cards vs the energy card.

### Steps to reproduce

1 - Add an Energy Card to a LaserIO Node.
2 - Right click on the Energy Card

### Expected behaviour

See the Card Holder box when right clicking on an Energy Card

### Screenshots

![LaserIO-1](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20612106/cd039dc8-ae30-421f-acba-8d135be10d2b)
![LaserIO-2](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20612106/bd99bc5a-edb3-4f8d-860c-c3e017706c9c)

**Comment by jlp1528** [comment]
Known issue:
https://github.com/Direwolf20-MC/LaserIO/issues/206
Could be fixed by pull request soon:
https://github.com/Direwolf20-MC/LaserIO/pull/221

**Comment by DinnerBeef** [comment]
This issue has been resolved in a newer version mod for a different version of minecraft. However, it looks like it will not be fixed for this version of minecraft. As such, we will now be closing this issue.
