### ISSUE TITLE
Pack crashing to Desktop

### ISSUE THREAD

**Issue by TheTrueDV** [FTBTeam/FTB-Modpack-Issues#4398]
### Modpack

FTB Arcanum Institute

### Modpack version

1.1.0

### Log Files

https://pste.ch/uyocumivas.pl

### Describe the bug

Entered Ars Dungeon for my third attempt.
Automatically teleported to dungeon after generation.
I see some dragon bone head and cobwebs before the game completely crashes.

Crashlog seems to indicate `Entity Type: supplementaries:falling_urn (net.mehvahdjukaar.supplementaries.common.entities.FallingUrnEntity)` as the offending entity.

Unfortunately the normal advise of setting 'removeErroringEntities' to true has not worked.
Eventually found a solution in removing all but the 'data' folder in `~\saves\Arcanum Institute\dimensions\ftbdungeons\dungeon_dim`. Unsure of any other issues this may cause, but all the folders seem to have regenerated normally.

I do have a backup in case this significantly impacts the dimension.

### Steps to reproduce

Go to the Ars quest page.
Attempt to challenge a dungeon.
Crash.
This is unlikely to be reproduceable.

### Expected behaviour

No crash.

**Comment by yarma92** [comment]
I'm also getting this issue with any dungeons at present. Same
[crash-2023-12-04_19.57.02-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13550820/crash-2023-12-04_19.57.02-server.txt)
 entity. Logs attached

**Comment by TheTrueDV** [comment]
> I'm also getting this issue with any dungeons at present. Same [crash-2023-12-04_19.57.02-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13550820/crash-2023-12-04_19.57.02-server.txt) entity. Logs attached

It will nuke the existing dungeon, but the newly generated one should be fine.
You can do this:
Backup the save.
Go to instance\save\dimensions\ftbdungeons\dungeon_dim\delete the folders except 'data'
You might just have to delete the 'entities' folder since it's a entity issue... but I accidentally deleted of them and it worked, so... that's a fix. 

Keep the backup in the pack devs need it. I forgot to do so, so I can't send a world file anymore.

**Comment by yarma92** [comment]
Yeah saw that in your original report after attaching my logs too. Worked like a charm. Looks like it's a supplimentaries urn being a pain.

**Comment by yarma92** [comment]
[Backup Dungeons.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13591518/Backup.Dungeons.zip)

Backed up deleted files from ...\save\dimensions\ftbdungeons\dungeon_dim\
