### ISSUE TITLE
when I open chat it keeps crashing my game [Bug]: 

### ISSUE THREAD

**Issue by IdkwhatToNameThis1** [FTBTeam/FTB-Modpack-Issues#4399]
### Mod

FTB genesis

### Mod version

FTB-team

### Forge / Fabric version

1.3.2

### What issue are you having?

game crashing

### Steps to reproduce

i opened chat and the thing said cancel or something else that was covered so i only can press cancel and now it keeps crashing when i open chat

**Comment by Saereth** [comment]
update to 1.4.0, its fixed there
