### ISSUE TITLE
Can't use Ars Magelight to light up dungeons

### ISSUE THREAD

**Issue by melbellrocks** [FTBTeam/FTB-Modpack-Issues#4401]
### Modpack

FTB Arcanum Institute

### Modpack version

1.1.0

### Describe the bug

I think we should be able to use Magelight in dungeons.  I can shoot it but it doesn't leave the light.

### Steps to reproduce

1. Go to dungeon
2. Try to light it up with Magelight
3. Be sad
4. Chicken out and leave the dungeon :)

### Expected behaviour

To be able to place magelight in dungeons

**Comment by jeridan** [comment]
This isn't fixed in 1.2.0
