### ISSUE TITLE
Eternal Hellforged Explosive Cells break after 1 usage in ARC instead of lasting forever

### ISSUE THREAD

**Issue by TopPercentageRattata** [FTBTeam/FTB-Modpack-Issues#4404]
### Modpack

FTB Arcanum Institute

### Modpack version

1.1

### Describe the bug

Applying an eternal stella to a hellforged explosive cell, hellforged resonator, advanced cutting fluid, sanguine reverter, and presumably all similar items such as primitive hydration cells causes them to be repaired to full, but they instantly break after 1 usage in Alchemical Reaction Chamber

### Steps to reproduce

1. Apply an Eternal Stella to a Hellforged Explosive Cell in a smithing table.
2. Put Eternal Hellforged Explosive Cell into an Alchemical Reaction Chamber along with any ore.
3. Cry

### Expected behaviour

For the items to not break at all, much less instantly

**Comment by Saereth** [comment]
this is hardcoded in bloodmagic if the nbts dont match is assumes its done and deletes it, there is no blacklist for forbidden arcanus either so we cant prevent this. I added a tooltip warning people not to apply it to bloodmagic consumable items as a compromise.
