### ISSUE TITLE
Massive lag

### ISSUE THREAD

**Issue by normsomers** [FTBTeam/FTB-Modpack-Issues#4405]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

Newist

### Log Files

I am experiencing massive lag. I am not experiencing it with normal Minecraft. I have allocated extra memory and am running a newer computer, so I do not understand what is causing the problem. I have also searched the internet and tried many suggestions to improve the frame rate but without success.

### Describe the bug

I am experiencing massive lag. I am not experiencing it with normal Minecraft. I have allocated extra memory and am running a newer computer, so I do not understand what is causing the problem. I have also searched the internet and tried many suggestions to improve the frame rate but without success.

### Steps to reproduce

Do you own a computer?

### Expected behaviour

no response

### Screenshots

none

**Comment by Klawn** [comment]
Dude, how do you expect to be helped with so few informations ? It's litterally like going to car repair and saying "my car is brand new and it maikes noise, fix it please"
At least, provide a log or a video showing your problem. I doubt you will get your issue solved with just the informations you gave.

**Comment by DinnerBeef** [comment]
Please fix your issue report. First, "Newist" is not a version. Please put a version number. Second, please explain what you are doing in the world. You can send screenshots and what not if you want as well. Does this happen everywhere in the world, or does it only happen in certain spots of the world? If you could as well send a screenshot of when F3 is open that could end up being helpful as well.
