### ISSUE TITLE
Hotkey 'B' opens a teleport menu and cant be rebound

### ISSUE THREAD

**Issue by NilsRamstoeck** [FTBTeam/FTB-Modpack-Issues#4406]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.1.9

### Describe the bug

I want to bind the hotkey 'B' to only open my backpack, but I cant unbind it from opening the teleport menu.

### Steps to reproduce

1. Equip Backpack
2. press 'B'

### Expected behaviour

Backpack opens

### Additional information

I play on a server with ops

**Comment by WouterButers** [comment]
I got the same problem. I reverted back to an older version (1.8.0) and the problem is gone, So I guise the problem is in version 1.9.0. for me it looks like it open some kind of waystone menu.

**Comment by davisjw** [comment]
+1 same issue; revert corrects

**Comment by DinnerBeef** [comment]
Fixed in version 1.9.1.
