### ISSUE TITLE
Daylight cycle in Student Dorms messes with villagers

### ISSUE THREAD

**Issue by TopPercentageRattata** [FTBTeam/FTB-Modpack-Issues#4407]
### Modpack

FTB Arcanum Institute

### Modpack version

1.1

### Describe the bug

Villagers just sleep 24/7 if there are beds, and never take jobs. Apparently some may take jobs if no beds but never restock.

### Steps to reproduce

Place some beds and spawn some villagers in Student Dorms dimension

### Expected behaviour

Villagers work properly

**Comment by Saereth** [comment]
is this on a server or single player?

**Comment by mccaan** [comment]
I'm working in single player and in my case is never night, so villagers do not sleep and never restock

**Comment by jeridan** [comment]
I can also confirm daylight cycle is stopped in my SSP world and the villagers trade never cycle.
