### ISSUE TITLE
Many uncraftable items

### ISSUE THREAD

**Issue by TopPercentageRattata** [FTBTeam/FTB-Modpack-Issues#4408]
### Modpack

FTB Arcanum Institute

### Modpack version

1.1

### Describe the bug

Netherite pickaxe needed for Advanced Amplify glyph and source steel pickaxe.
Netherite axe needed for source steel axe
Gold or iron or diamond or netherite axe required for Foliat lumberjack ritual. Mentioned in another issue though.
Diamond pickaxes required for diamond mining arrows and destruction wand core. This and next 2 lines can be fixed by fixing daylight cycle for villagers though. https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4407
Iron sword possibly needed for a roots ritual, not sure.
Iron armor needed for roots wildwood armor.(Can be obtainable once daylight issues
Golden pickaxe requied for Ring of the Mantle.
Flashing archwood required for Tablet of Zapping
1 starter gorgon gem(structure loot) required to make more gorgon gems and what I believe is a guidebook for ars omega or some way to unlock pages for things in regular ars guide.
Wooden axe needed for chipped Carpenter's Workbench
Wooden sword/axe/shovel/pickaxe/hoe needed for Roots Living tools
Possibly stone sword needed for a roots ritual, not sure.

### Steps to reproduce

1. Try to craft some items
2. Fail due to unobtainable vanilla ingredients

### Expected behaviour

Things should be craftable

**Comment by theivycoder** [comment]
also the glassblowers table from chipped :)
