### ISSUE TITLE
Terra Genesis quests not giving rewards

### ISSUE THREAD

**Issue by b4rtong** [FTBTeam/FTB-Modpack-Issues#4410]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Describe the bug

Restore the Arid Nexus, Restore the Verdant Labyrinth, and Restore the Emerald Bastion all auto-accepts reward once the quest is complete but don't give you the reward.

### Steps to reproduce

If the other materials are in your possession, once you click the task check box, the reward should auto-accept. It is identical for each quest. I went to a non Terra Genesis task to confirm the reward selection occurs normally, and it does. I suspect it's just related to the Terra Genesis rewards.

### Expected behaviour

rewards are delivered to inventory

**Comment by Nidaelie** [comment]
happenning same, last update.... quest autocompletes but no reward
