### ISSUE TITLE
Cow in Jar uncraftable

### ISSUE THREAD

**Issue by Winfrex** [FTBTeam/FTB-Modpack-Issues#4414]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.9

### Describe the bug

Hello, I have attempted to craft the cow in a jar multiple times and every time the animation happens but it is still a milk jar in the end

### Steps to reproduce

place a milk jar a block below a cow and an anvil above the cow, knock the block holding the anvil and watch the animation happen but the milk jar never changes into the cow in a jar

### Expected behaviour

after dropping an anvil over the cow standing on top of the milk jar, the cow gets stuck in the jar

**Comment by DinnerBeef** [comment]
Can you send a video of you trying this? I just tried it in my game and everything is working like expected?

**Comment by Winfrex** [comment]
I tried it again and it worked this time, if there is a height requirement then I wasn't meeting it the first two times

Thanks for the reply, have a good one!
