### ISSUE TITLE
Singleplayer crash after using Cut Paste Gadget on enderIO energy conduit

### ISSUE THREAD

**Issue by zaz187** [FTBTeam/FTB-Modpack-Issues#4415]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.9.0

### Log Files

[crash-2023-12-06_20.51.59-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13591069/crash-2023-12-06_20.51.59-server.txt)
[crash-2023-12-06_20.56.14-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13591070/crash-2023-12-06_20.56.14-server.txt)
[crash-2023-12-06_21.16.32-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13591180/crash-2023-12-06_21.16.32-server.txt)

### Describe the bug

Using the building Cut Paste Gadget to move Ender IO machines and Energy conduit. When pasted instead of energy conduit a block called "Render block (DO NOT USE)" is placed. Shortly after game crashed and crashes when trying to open world. Last crash report was from recreating in creative

### Steps to reproduce

Use 'Cut' function on Cut Paste Gadget on enderIO energy conduit connected to a machine
Use 'Paste' function on Cut Paste Gadget somewhere

### Expected behaviour

Expected to have the cut machines and conduit placed connected in new location

### Screenshots

![Bug pt 1](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/153129356/e0423ac3-332d-4dd7-92ae-ad0b9b041408)
![Bug pt 2](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/153129356/09051d23-6fe6-4cdd-ab86-7dcbd8c8afdb)

### Additional information

Canary and Starlight has been added to the modfolder
Unable to enter world after crash

**Comment by DinnerBeef** [comment]
Just to double-check, this does happen on version. 1.9.0 and not version 1.8.0 correct?

**Comment by zaz187** [comment]
This was in 1.9.0. I'm not sure if it happened in version 1.8.0 aswell

**Comment by DinnerBeef** [comment]
Do to a bug in EnderIO I am unable to resolve this issue. The issue will be resolved, the bug is fixed.

**Comment by DinnerBeef** [comment]
Turns out I made a semi derp. This issue will now be resolved in the next version of the pack.
