### ISSUE TITLE
Waystones GUI has no keybind that I can find

### ISSUE THREAD

**Issue by Pyrocrisis** [FTBTeam/FTB-Modpack-Issues#4416]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.9.0

### Describe the bug

I have a Sophisticated backpack in a curio slot which I have assigned the B key to open in the key binds menu and it has been working great. However today after I updated the modpack and I went to open my backpack, having changed no settings myself, I got a GUI which at first I was like huh? So I went to check my keybinds I thought maybe a modd update or mod addition added a new key but there were no conflicts that I could see. I then realised it seems to be some sort of waystones GUI as I recognised some names listed. So I went back to keybind menu and cannot find anything related at all.
I have also looked at mods menu and unfortunately the config button for waystones mod is greyed out so no options there :(

### Steps to reproduce

Press B key

### Expected behaviour

A configurable keybind

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/35179535/cce96135-0eea-4d77-9811-9f984dc6f214)

**Comment by zaz187** [comment]
Reply in earlier thread

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4406#issuecomment-1842523169

**Comment by DinnerBeef** [comment]
Fixed in version 1.9.1.
