### ISSUE TITLE
Botania visuals do not work with the shaders in this pack. 

### ISSUE THREAD

**Issue by yarma92** [FTBTeam/FTB-Modpack-Issues#4417]
### Modpack

FTB Arcanum Institute

### Modpack version

1.1.0

### Log Files

N/A

### Describe the bug

Botania effects do not work with shader packs. Mana does not render, luminzer entities to interact with are not visible. 

These DO work with shaders in Genesis 1.4

### Steps to reproduce

Enable shaders and then look at any mana pool with mana or try to find a luminize to interact with

### Expected behaviour

Botania visuals work with shaders

### Additional information

This isn't an issue in genesis in current versions but was at release. Maybe it's possible to find the solution there? I noticed a difference in the shader versions but after copying the genesis shaders to arcanum the issue persisted.

**Comment by Saereth** [comment]
This is a known issue and botania sadly does not have the option to turn off their interal shaders in 1.18.2. We've requested it but its unlikely to work. To work around we made it so you can right click on mana pools to see a numerical value of their contents. There is also a quick keybind to toggle shaders on/off quickly if needed but thats about all we can do for it presently.
