### ISSUE TITLE
Setting within Furnaces of "IronFurnaces" Mod causing "Ticking block entity" Crash AND Not stacking in inventory after placed. 

### ISSUE THREAD

**Issue by TehGOOSE** [FTBTeam/FTB-Modpack-Issues#4423]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Log Files

https://pastebin.com/ibtKTihv

### Describe the bug

When placing a Copper Furnace (IronFurnaces Mod) I clicked the cogwheel and clicked settings and slicked one of the settings (im not sure which - first time using the mod - and I do not want to risk corrupting the world to test it)

Something else that happens is once you create multiple versions (any kind not just the copper tier) they stack - but if you place one and pick it up it no longer stacks with the others - not sure if this is related but seems odd - and stood out to me`

### Steps to reproduce

1. Place Copper Furnace
2. Edit settings *Sadly I dont know which I selected - it was one of the lower toggles*
3. Server crashes

### Expected behaviour

Edit Furnace settings without crashing - And furnaces all stack - even after placed and picked up. 

### Additional information

Saereth is a swell feller.

**Comment by UnRealDinnerbone** [comment]
Looks like the issue has been fixed in the mod. Does this issue still exist?
