### ISSUE TITLE
Spawners only work when i'm at an another dimension

### ISSUE THREAD

**Issue by Lacko1994** [FTBTeam/FTB-Modpack-Issues#4426]
### Modpack

Direwolf20 1.2.0

### Modpack version

1.9.1

### Describe the bug

My spawners only work when i'm present in the area or i'm in an another dimension, the spawner upgraded with a nether star and i also tried the spawner agitator the area where the spawners are is chunk loaded. Thanks for any ideas!

### Steps to reproduce

sorry i don't know how to reproduce

### Expected behaviour

I expected the spawner works when im not present

**Comment by DinnerBeef** [comment]
Seems like you missed labeled the pack name. I am going to guess you are playing Direwolf20 1.20 and not Direwolf20 1.4.7

**Comment by Lacko1994** [comment]
> Seems like you missed labeled the pack name. I am going to guess you are playing Direwolf20 1.20 and not Direwolf20 1.4.7

yes thank you. But now it fixed i needed to reinstall the client.
