### ISSUE TITLE
[Suggestion]: please add a way to get infinite night vision 

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [FTBTeam/FTB-Modpack-Issues#443]
### Modpack

FTB Oceanblock 

### Is your suggestion related to a problem? Please describe.

I and many others I watch complain about it being to dark at times. And there are no items that give night vision  for a unlimited duration. Please make a item that can give unlimited night vision, preferably one that can be toggled. Even at the cost of energy or exp.

**Comment by quietust** [comment]
Botania has the Tainted Blood Pendant which can be made to provide Night Vision at the cost of Mana, and it can even be equipped in a Curio slot so it won't clutter your inventory.

**Comment by Sunekaer** [comment]
Hi,
Thanks for the suggestion, this wont be added as there already is ways to upgrade armor til give the effect
