### ISSUE TITLE
can't make IC2C steam turbine & steam tunnel , because missing water mill recipe

### ISSUE THREAD

**Issue by s87145132000** [FTBTeam/FTB-Modpack-Issues#4430]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Describe the bug

missing IC2C water mill recipe , result can't make IC2C steam turbine even steam tunnel

### Steps to reproduce

1. find IC2C steam turbine recipe
2. recipe show need use water mill to craft.
3. press R to find IC2C water mill recipe.
4. no recipe find , can't craft it 

### Expected behaviour

craft a water mill , then craft steam turbine or steam tunnel to generate EU power

**Comment by billmillz** [comment]
Having the same issue - any fixes?
