### ISSUE TITLE
Refined Storage devices disconnecting after server restart

### ISSUE THREAD

**Issue by Fearzu** [FTBTeam/FTB-Modpack-Issues#4431]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

Latest

### Log Files

No applicable log data found. 

### Describe the bug

Running an apex server, 16 GB, with the 1.20 pack, latest version. Multiple players have reported that refined storage devices such as crafters and external storage disconnect from the controller until it is broken and replaced. I do not see anything in the logs concerning this. 

No changes have been made to the default config file for RS. 

### Steps to reproduce

Setup refined storage system with crafters or external storage. Reboot server. 

### Expected behaviour

For the controller not to disconnect from devices on reboot.

**Comment by DinnerBeef** [comment]
Latest is not a version. Please put the version number in the issue report.
