### ISSUE TITLE
XNET Logic function 

### ISSUE THREAD

**Issue by ZanXacato** [FTBTeam/FTB-Modpack-Issues#4434]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Describe the bug

On servers, the xnet logic function doesn't have the item count functionality. I checked singleplayer mode and it worked. Unsure if that's intentional or not.

### Steps to reproduce

Create a server and use XNET logic functions.

### Expected behaviour

Have item functionality similar to singleplayer worlds.

**Comment by UnRealDinnerbone** [comment]
An Update has been released since this issue was made. Can you please confirm this issue, it's still happening?

**Comment by ZanXacato** [comment]
Unfortunately, I no longer run that server so I cannot say.
