### ISSUE TITLE
Ad Astra Oxygen Cans (both) dump oxygen 'into armor' but armor doesn't receive it

### ISSUE THREAD

**Issue by ttufts** [FTBTeam/FTB-Modpack-Issues#4436]
### Modpack

FTB Skies

### Modpack version

1.4

### Describe the bug

When "Enabled: All Armor" is selected with the Oxygen Can, the can dumps it's contents but the enabled Ad Astra armor doesn't increase oxygen content

### Steps to reproduce

1. Equip Ad Astra suit with partially filled oxygen tanks (74.5% in my case)
2. Fill an Ad Astra oxygen can from an Oxygen Loader
3. Right click with oxygen can in main hand until Enabled: All Armor is displayed
4. Oxygen can will empty, but oxygen tanks will not increase
5. Oxygen seems to be lost

### Expected behaviour

Oxygen should go into armor tanks

**Comment by Pola06** [comment]
I am having the same issue now for a server did you find a solution

**Comment by Saereth** [comment]
This is an issue with ad Astra, not something specific we've done. Its been reported and we'll update when/if they get a fix
