### ISSUE TITLE
Ad Astra suit displays overlap/obscure minimap (upper right) and Deep Learning display (upper left)

### ISSUE THREAD

**Issue by ttufts** [FTBTeam/FTB-Modpack-Issues#4437]
### Modpack

FTB Skies

### Modpack version

1.4

### Describe the bug

Ad Astra suite displays overlap and block the minimap and the deep learning display. 

### Steps to reproduce

1. Equip Ad Astra jet suit
2. Put some models in a deep learner and put it in it's curio slot

### Expected behaviour

Displays should be movable or configured in code to not conflict

### Screenshots

![2023-12-08_23 59 38](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2926882/956584bd-475c-41c1-b677-ea2235434e32)

**Comment by Saereth** [comment]
you can edit the ad_astra.toml in your config folder and set the offset to wherever you'd like it. We dont publish this because it would overwite people's customizations every update.
