### ISSUE TITLE
Crying Obsidian is unobtainable

### ISSUE THREAD

**Issue by shadowcryptic** [FTBTeam/FTB-Modpack-Issues#4438]
### Modpack

FTB Arcanum Institute

### Is your suggestion related to a problem? Please describe.

Could be added through Malum Spirit Infusion like so:

    event.custom({
        "type": "malum:spirit_infusion",
        "input": {"item": "minecraft:obsidian","count": 1},
        "output": {"item": "minecraft:crying_obsidian"},
        "extra_items": [{"item": "ars_nouveau:water_essence",  "count": 2}],
        "spirits": [{  "type": "aqueous",  "count": 4},{  "type": "arcane",  "count": 2}]
    })
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/68837404/279a208b-3827-403a-8bd0-1351a444130e)

**Comment by TheonlyTazz** [comment]
added!
