### ISSUE TITLE
[Bug]: AN creative items require M&A instead of AN.

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#444]
### Modpack

FTB University 1.16.5

### Modpack version

1.3

### Describe the bug

Ars Nouveau creative spellbook requires Mana & Artifice vellum instead of Ars Nouveau spell parchment.

### Steps to reproduce

Go to JEI. Click the Item to see its recipe.

### Expected behaviour

AN creative items should require AN materials.

### Screenshots

![Ars requires M A](https://user-images.githubusercontent.com/77522101/145245357-e2cdd5be-fa7b-4f59-912e-b64603836d98.png)

**Comment by aaronhowser1** [comment]
Fixed
