### ISSUE TITLE
Game shutdown on entering dimensions or teleporting with EnderIO

### ISSUE THREAD

**Issue by markusschwarz99** [FTBTeam/FTB-Modpack-Issues#4440]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.8.0

### Log Files

[crash-2023-12-03_11.32.21-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13624104/crash-2023-12-03_11.32.21-server.txt)
[crash-2023-12-03_12.23.01-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13624105/crash-2023-12-03_12.23.01-server.txt)
[crash-2023-12-03_14.24.15-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13624106/crash-2023-12-03_14.24.15-server.txt)
[crash-2023-12-03_19.54.26-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13624107/crash-2023-12-03_19.54.26-server.txt)
[crash-2023-12-03_20.11.14-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13624108/crash-2023-12-03_20.11.14-server.txt)
[crash-2023-12-03_21.15.42-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13624109/crash-2023-12-03_21.15.42-server.txt)

### Describe the bug

Game shutdown on entering dimensions or teleporting with EnderIO

### Steps to reproduce

Go to mining dim, then go back to normal world dim.
Go like 1000 blocks away from base, use teleporter from enderio

### Expected behaviour

game crash

**Comment by DinnerBeef** [comment]
Please update your pack. This should have been fixed in version 1.9.0.
