### ISSUE TITLE
Nitpick: Shift while looking in Sophisticated backpack isn't captured, and makes you fly down if you're flying

### ISSUE THREAD

**Issue by ttufts** [FTBTeam/FTB-Modpack-Issues#4442]
### Modpack

FTB Skies

### Modpack version

1.4

### Describe the bug

While looking in a Sophisticated backpack, hitting or holding SHIFT will cause you to fly down, which is not the same behavior as with other inventory systems. 

Seems like the normal player inventory behaves the same, but the Cyclic Ender Inventory, regular boxes/crates/inventories, and the Refined Storage wireless grids all capture SHIFT so that you can SHIFT+Click on items to move them around. When flying over the void you have to be very careful interacting with your inventory if you don't have something you can see to notice that you're descending into the void.

### Steps to reproduce

1. Fly
2. Open backpack
3. Hit shift 
4. Descend

### Expected behaviour

Capture SHIFT so that it's only used for interacting with inventory

**Comment by Saereth** [comment]
this would be a suggestion for the mod dev as its not something we control at a pack level
