### ISSUE TITLE
Crash when using IC2 Advanced Jetpack and trying to access Pneumaticraft machines

### ISSUE THREAD

**Issue by OhmegaWolf** [FTBTeam/FTB-Modpack-Issues#4444]
### Modpack

FTB Genesis

### Modpack version

1.4.4

### Describe the bug

Whenever im using my Advanced jetpack in Advanced hover mode and i try to interact with PNCR machines my game will crash to the Desktop every single time

### Steps to reproduce

Wear an advance jetpack and be hovering using advanced hover, right click into a PNCR machine (ive tested with Flux compressors, Pressure chamber and Thermopneumatic plants. Once you try to access the GUI the game will crash to desktop instantly

### Expected behaviour

It shouldn't crash

**Comment by ArtpokeBr** [comment]
This doesn't seem to be happening anymore, please, if the issue still persists after the next update, reopen this issue or open a new one! =)
