### ISSUE TITLE
My wither builder doesn't work what can i do?

### ISSUE THREAD

**Issue by YUR1N4R** [FTBTeam/FTB-Modpack-Issues#4445]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Describe the bug

my wither builder don't spawn wither and e try replace him in other places and he didn't work

### Steps to reproduce

put a wither builder in world
make an automation with: refined storage - exporter
using @xnet to finnish the recovery of loting from mob mob crusher

### Expected behaviour

solve the problem

**Comment by UnRealDinnerbone** [comment]
Can't seem to reproduce this issue. Are the items blocks going into the builder? And are the blocks not getting placed?

**Comment by YUR1N4R** [comment]
exacly
all items go inside manualy and automatic the wither builder, he have energy and i tried with addons and without addons and the wither boss never spawns!!!!

**Comment by YUR1N4R** [comment]
> Can't seem to reproduce this issue. Are the items blocks going into the builder? And are the blocks not getting placed?

nop they not get placed

**Comment by YUR1N4R** [comment]
@UnRealDinnerbone can you see whats appening?
