### ISSUE TITLE
FTB Direwolf20 modpack

### ISSUE THREAD

**Issue by FMM0** [FTBTeam/FTB-Modpack-Issues#4446]
### Modpack

FTB Presents Direwolf20

### Modpack version

1.9.1

### Describe the bug

same as a previous issue that was reported in regards to FTB Genesis (Oredict issues with Flint Block #4411), the flint block from cyclic which is required to craft many cyclic items, is uncraftable, the flint block from supplementaries is interfering with the recipe, i've tried using a crafter from cyclic but the default recipe is the supplementaries one

### Steps to reproduce

1- Place 9 Flint in a crafting window and take the Supplementaries Block of Flint
2- Attempt to use that block in a Cyclic recipe

### Expected behaviour

Oredict should allow for use of either mod's flint block in recipes, or at least conversion of one mod's block to the other's.

**Comment by Kojesma** [comment]
Still existing....

**Comment by Gaz492** [comment]
This looks to be fixed in the latest version of the pack.
