### ISSUE TITLE
Advanced Inscriber popping

### ISSUE THREAD

**Issue by Beckydog** [FTBTeam/FTB-Modpack-Issues#4451]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Describe the bug

POSSIBLY me being ultra stupid, But the advanced inscriber autopops when placed anywhere near pattern/provider crafters from AE2, (MEGA version too) not quite sure what logfile I should supply to show this. It may be working as intended! 

### Steps to reproduce

Have pattern crafter. Try to put Advanced inscriber on/near 

POP! 

### Expected behaviour

No popping, more shiny autocrafting, akin to the Chosen architect 'playthough'

**Comment by ArtpokeBr** [comment]
This doesn't seem to be happening anymore, if still occurs, please reopen this issue =)
