### ISSUE TITLE
Mechanical Squeezer recipe

### ISSUE THREAD

**Issue by FMM0** [FTBTeam/FTB-Modpack-Issues#4452]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.9.1

### Describe the bug

There is no way of making the mechanical squeezer (@IntegratedDynamics) without diving into bees, as the mechanical squeezer which is primarily used to create the crystallized menril, takes crystallized menril to make, and the normal squeezer doesnt provide a sufficient solution, a change to the mechanical squeezer recipe or allowing the normal squeezer to make crystallized menril is required.

### Steps to reproduce

1- try to create mechanical squeezer
2- realize you cant without progression in bees

### Expected behaviour

 a change to the mechanical squeezer recipe or allowing the normal squeezer to make crystallized menril is required

**Comment by DinnerBeef** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8346986/2b1ab539-b857-4ef0-b0d2-3747ea1c0cf8)
You need to craft the Squeezer and use a Drying basin
