### ISSUE TITLE
[mekanism] Turbine Vent not outputting water

### ISSUE THREAD

**Issue by imle** [FTBTeam/FTB-Modpack-Issues#4453]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.9.1

### Describe the bug

The turbine vent block (part of the turbine multiblock) is not outputting water when it is being used with a steam/water based reactor.

### Steps to reproduce

Build reactor of any size and turbine of any size.
Run the reactor.
Observe no return flow from turbine vent blocks.

### Expected behaviour

Water should be coming back from the vent blocks

### Screenshots

![Turbine Setup](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/4809109/f63a77bf-02dc-49b5-a3f1-9fb366b3dc00)
![Power Output](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/4809109/d07bfcb0-d4a4-4628-aa81-f9b4e91a8e59)
![Turbine UI](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/4809109/cf315c5f-b79d-4ba6-9e9b-cd2a722a7274)
![Reactor UI](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/4809109/949f02e3-7b77-458a-ae1a-5445da47589b)
![Water Flow Observation](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/4809109/69ba083c-ba9d-40f8-bf07-0954567f6fb1)
![Turbine Info Screen](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/4809109/d1cacbaa-136e-4087-a6b7-5a6661ea7fcd)

**Comment by YUR1N4R** [comment]
i add the same problem on stoneblock 3

**Comment by YUR1N4R** [comment]
@UnRealDinnerbone can you see whats appening?

**Comment by YUR1N4R** [comment]
> ### Modpack
> FTB Presents Direwolf20 1.20
> 
> ### Modpack version
> 1.9.1
> 
> ### Log Files
> _No response_
> 
> ### Describe the bug
> The turbine vent block (part of the turbine multiblock) is not outputting water when it is being used with a steam/water based reactor.
> 
> ### Steps to reproduce
> Build reactor of any size and turbine of any size. Run the reactor. Observe no return flow from turbine vent blocks.
> 
> ### Expected behaviour
> Water should be coming back from the vent blocks
> 
> ### Screenshots
> ![Turbine Setup](https://private-user-images.githubusercontent.com/4809109/289413277-f63a77bf-02dc-49b5-a3f1-9fb366b3dc00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjE1OTQsIm5iZiI6MTcwNDkyMTI5NCwicGF0aCI6Ii80ODA5MTA5LzI4OTQxMzI3Ny1mNjNhNzdiZi0wMmRjLTQ5YjUtYTNmMS05ZmIzNjZiM2RjMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMjExNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGI4ZDE5NDg4YjY1NTcwMWVhZmZjZTIyNDAxNWUxNTFlNzE3MDRkMTdiOTFmMjg0NzQ5ODc2NWI1ZmZjMDU1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LgJvQ8f9rSTXUo4inC3P1LO3qBTzPB2WVlJuTSsqQ8g) ![Power Output](https://private-user-images.githubusercontent.com/4809109/289413279-d07bfcb0-d4a4-4628-aa81-f9b4e91a8e59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjE1OTQsIm5iZiI6MTcwNDkyMTI5NCwicGF0aCI6Ii80ODA5MTA5LzI4OTQxMzI3OS1kMDdiZmNiMC1kNGE0LTQ2MjgtYWE4MS1mOWI0ZTkxYThlNTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMjExNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzE4YTFhNDE5YTZiYjE2NGE0MzA5ZTY3YTk0MDE5Njg3YjJlMTAyZTRlOTJhOGVlMGU4ZDE3ZWI1OTMxZTZkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o-yaL48IzgLZX13gnSFDjIdOo4otxbGWBWy6Gwk6VK4) ![Turbine UI](https://private-user-images.githubusercontent.com/4809109/289413280-cf315c5f-b79d-4ba6-9e9b-cd2a722a7274.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjE1OTQsIm5iZiI6MTcwNDkyMTI5NCwicGF0aCI6Ii80ODA5MTA5LzI4OTQxMzI4MC1jZjMxNWM1Zi1iNzlkLTRiYTYtOWU5Yi1jZDJhNzIyYTcyNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMjExNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ0YjEzODk1YjU5NTdlNzdhZjQyNWNlOGZmOWZmOGI2YWM0Nzc0Yjg4NzdiY2U2NGY2NzM0ZDE2MDdlMDNlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XWMbpPttx5h7oRsbHRLubMHtpNclYbXCpSrTq0gpoZk) ![Reactor UI](https://private-user-images.githubusercontent.com/4809109/289413283-949f02e3-7b77-458a-ae1a-5445da47589b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjE1OTQsIm5iZiI6MTcwNDkyMTI5NCwicGF0aCI6Ii80ODA5MTA5LzI4OTQxMzI4My05NDlmMDJlMy03Yjc3LTQ1OGEtYWUxYS01NDQ1ZGE0NzU4OWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMjExNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJmNGMzOGIyZTEzMTllNDU0OTA2MGVhZGJkZjk2YTBhN2JhMmUzOTkwM2NkNzAyZTIwMDY5MTVhY2U5YzQxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iMENE1M9BR76JVn_Jzsk57HhAPYxtyaFwJbKh1D6sIE) ![Water Flow Observation](https://private-user-images.githubusercontent.com/4809109/289413285-69ba083c-ba9d-40f8-bf07-0954567f6fb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjE1OTQsIm5iZiI6MTcwNDkyMTI5NCwicGF0aCI6Ii80ODA5MTA5LzI4OTQxMzI4NS02OWJhMDgzYy1iYTlkLTQwZjgtYmYwNy0wOTU0NTY3ZjZmYjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMjExNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdjNTA3OGM2ZTYxMTRiMzk5OTIyOTVkNjgxYThlMzRlZTE2ZjBmNjQ1NTE0MzFkZmU4MWRkYTA4ZjMxM2FlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IwC9ewNLRRxvmQUHNBM-sBHo8Q__pKOoZGC6YrRpTtg) ![Turbine Info Screen](https://private-user-images.githubusercontent.com/4809109/289413536-d1cacbaa-136e-4087-a6b7-5a6661ea7fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjE1OTQsIm5iZiI6MTcwNDkyMTI5NCwicGF0aCI6Ii80ODA5MTA5LzI4OTQxMzUzNi1kMWNhY2JhYS0xMzZlLTQwODctYTZiNy01YTY2NjFlYTdmY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMjExNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjYzOWM5Mzc1MGI3YTNkYTE2ODllYjgyNzdkNzA5MDZjY2VkYjI1MTdkMjkzMGM2MTBiNjA3MjgyNzE4ZGFjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QC8158pIskxSxHJ85x5wj6x4UILT1mLbD2oMQMgR2OM)
> 
> ### Additional information
> _No response_

check if you are using clock's from ProjectE on same chunk of reactor

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
