### ISSUE TITLE
Missing Chunks

### ISSUE THREAD

**Issue by FarFar2132** [FTBTeam/FTB-Modpack-Issues#4454]
### Modpack

FTB Arcanum Institute

### Modpack version

1.1.0

### Describe the bug

There seems to be an ongoing issue on LAN worlds where playing with the mod pack and with your friends on LAN results in missing chunks for anyone besides the primary LAN world creater. Theses chunks are usually on the bridge leading towards the classes, (The bridge with the magical beams that you glide with, the one that goes up and one that goes down). There are other areas of course as well that are missing chunks. 

### Steps to reproduce

1. create a LAN world
2. invite a friend to play
3. play and then maybe disconnect / have a second session or so (may even occur on the first session)
4. missing chunks that don't show up visually. The chunks are there as you can walk on them, but they are invisible. Pressing F3+b / F3+H or other F3 commands don't seem to fix or change anything. 

### Expected behaviour

I expected the chunks to be there so both me and my friend could walk around the campus as normal, but instead the chunks are invisible and only one of us can see campus and the other has to teleport around. 

### Screenshots

![asd 1](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/153476145/5f424f26-258d-44c5-a394-94fe3c1a8f8f)
![asd 2](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/153476145/7a140ddb-f5bb-45b8-b78f-477d98482ce6)

### Additional information

Once again this occurs in more spots than just this, and is a consistent issue. So far nothing we have done has fixed this and I have noticed others on the discord seem to be having the same issue and are also playing on LAN.

**Comment by TheonlyTazz** [comment]
This is an Issue caused by the Signpost on the map it seems. relogging should fix this issue. If you are the server owner, you can remove those signs in creative mode for now.

**Comment by Ninetailed** [comment]
I've also experienced this. Issue went away when we switch to a dedicated server, so it only seems to occur with LAN worlds.
