### ISSUE TITLE
Unable to make Infused Alloy

### ISSUE THREAD

**Issue by Admiralmatt** [FTBTeam/FTB-Modpack-Issues#4456]
### Modpack

FTB One

### Modpack version

2.8.3

### Describe the bug

after the update i am unable to use the Metallurgic Infuser to craft Infused Alloy.

### Steps to reproduce

1 place redstone into an Metallurgic Infuser
2 try to place iron into the Metallurgic Infuser
3 the iron will snap back into your inventory instead of crafting into Infused Alloy

### Expected behaviour

the infuser will craft Infused Alloy

### Additional information

this issue happens with both the Metallurgic Infuser and factories. the iron snaps back to inventory when placed into the machine.
when automation is used to place items in the iron enters the machine and goes to the correct slot but it does not craft.

i am able to craft Reinforced Alloy as normal but did not test Atomic Alloy

**Comment by UnRealDinnerbone** [comment]
I'm unable to reproduce this issue. Does this happen in a fresh instance of pack?
