### ISSUE TITLE
[FTB One] Server crash caused by Embeddium

### ISSUE THREAD

**Issue by JulianVennen** [FTBTeam/FTB-Modpack-Issues#4458]
### Modpack

FTB One

### Modpack version

2.8.3

### Log Files

https://mclo.gs/FkY7OX9

### Describe the bug

The server install script for this modpack installs the mod embeddium, which is a client only mod and causes the server to crash.

### Steps to reproduce

1. Download the server install script
2. Run it
3. Try to start the server

### Expected behaviour

The server should start

**Comment by JulianVennen** [comment]
Yes, I also did that. I just want this to be fixed for other users and future versions.

**Comment by natefabian18** [comment]
Can confirm issue still exists in install script. Just ran into it today when setting up a server.

**Comment by timephy** [comment]
> Can confirm issue still exists in install script. Just ran into it today when setting up a server.

Same

**Comment by eqagunn** [comment]
Still present.

**Comment by Gaz492** [comment]
This should be resolved now
