### ISSUE TITLE
Please add the mod Quickstacks to Current / Future Modpacks

### ISSUE THREAD

**Issue by Kuktar** [FTBTeam/FTB-Modpack-Issues#446]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

No

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/quickstack

Ever since 1.12.2 your modpacks no longer have the Quark mod. Quark has some really cool and useful features. One Feature i think is really useful and adds a lot to modpacks is the ability to dump your inventory to nearby chests. 

Thanks.

**Comment by Jake-E** [comment]
FTB Endeavour, Academy 1.16 and University 1.16 have Quark included - all 1.16 modpacks.

The mod list for each pack differs depending on what we decide for that particular pack, we aren't excluding the mod for any reason in particular, it just didn't fit OceanBlock.

I'll leave the quick stack mod suggestion for Sunekaer to comment on.
