### ISSUE TITLE
Mobs killed with an IF Mob Crusher do not drop Mob Souls

### ISSUE THREAD

**Issue by tsjb89** [FTBTeam/FTB-Modpack-Issues#4460]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Describe the bug

Sorry if this is intended, but most other automatic ways of killing mobs seems to drop Mob Souls. 

### Steps to reproduce

Kill a mob with a Mob Crusher

### Expected behaviour

Mob Souls drop when a Mob Crusher kills them

**Comment by UnRealDinnerbone** [comment]
This has to do with the way the Crusher kills the mobs. The mob souls need a 'player' in order for the drop to happen, the other mods must use a fake player
