### ISSUE TITLE
unfixed issue - mining gadgets deleting waterlogged tile entities with freeze upgrade

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4462]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.10.0

### Describe the bug

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4233
This issue is fixed in mininggadgets-1.15.7 and noted as such in the change log. However, the pack still has not been updated from mininggadgets-1.15.6.

### Steps to reproduce

see linked issue

### Expected behaviour

Waterlogged tile entities should be ignored, not turned into packed ice.

**Comment by jlp1528** [comment]
Still present in modpack version 1.11

**Comment by DinnerBeef** [comment]
The issue has been reported to the mod dev. The mod will be updated if the issue is resolved.
