### ISSUE TITLE
Can't join single-player or multiplayer

### ISSUE THREAD

**Issue by camz7017** [FTBTeam/FTB-Modpack-Issues#4463]
### Modpack

FTB Skies

### Modpack version

1.4.0

### Describe the bug

My girlfriend is trying to play FTB Skies and it loads into the main screen and they can create a world and all that but when they try and load into the world either single-player or joining my LAN world, it disconnects them after loading for like 3 minutes. It crashes their whole game. While I’m in the world on my screen chat says they’ve joined but then after a minute it says they’ve left before they’ve even loaded in

### Steps to reproduce

1. Make a single-player world
2. Click the create world button
3. Wait for it to load

### Expected behaviour

Disconnects from world before loading and crashes game.

**Comment by poeticwatcher** [comment]
Also currently trying to play with my partner. Both of us can successfully create worlds, and open our games to LAN... but when either of us tries to join the other via LAN, Minecraft spends forever trying to connect before displaying the error...
"Connection Lost
Internal Exception: java.lang.IllegalArgumentException: ItemStackIngredioents cannot be created using the empty ingredient."
...to the person trying to join.

Whereas the partner with their game running and open to LAN sees:
[player name] joined server.
[player name] left server.

Please help?
