### ISSUE TITLE
Cant make purpur block to go futher in quest

### ISSUE THREAD

**Issue by Pontus231** [FTBTeam/FTB-Modpack-Issues#4466]
### Modpack

FTB Arcanum Institute

### Modpack version

Think 1.2.0

### Describe the bug

Cant make purpure block in nature altar cant put the end stone in the altar same whit rabit stew to make lucky foot and some other items in the picture know that the altar is unpowerd but have tryed whit one who have power to and can still put in iron so sohuld be able to put in end stone to

### Steps to reproduce

Build nature altar
Put the end stone in it

### Expected behaviour

to be put in the altar

### Screenshots

![Skärmbild 2023-12-13 214828](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/153770570/53546a9e-032b-4066-b5aa-7c85f492e74c)
![Skärmbild 2023-12-13 214846](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/153770570/2b216b25-a159-4e48-985e-c8e289039bd7)
![Skärmbild 2023-12-13 215234](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/153770570/658c6a3b-af49-42a7-a3c9-1214234a583b)

**Comment by TheonlyTazz** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/3908847/d1ea7909-b045-47a7-b568-7211d2a5a945)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/3908847/116dd1e1-c230-46c5-85ff-3fd84cc2d4b3)


Reading the Book, it will tell you to place the transmutation catalyst on one of the lower golden stone bricks;
I will state this more clear in the questbook
