### ISSUE TITLE
DW20 1.20 Client crashes when clicking through JEI Pages. 

### ISSUE THREAD

**Issue by raysilverstone** [FTBTeam/FTB-Modpack-Issues#4468]
### Modpack

FTB Direwolf20 1.20

### Modpack version

1.10.0

### Log Files

[crash-2023-12-13_19.28.45-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13667274/crash-2023-12-13_19.28.45-client.txt)

### Describe the bug

When looking through JEI the client crashes after getting to page 26 or page 76 when going in reverse page order. It happens on my server and in a single-player world. 

### Steps to reproduce

Open JEI
Click next page

### Expected behaviour

The next page of items in JEI to come up.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?

**Comment by raysilverstone** [comment]
In the current version this is no longer an issue.
