### ISSUE TITLE
Direwolf20 - Multiple mods not functioning

### ISSUE THREAD

**Issue by AlexanderStroer** [FTBTeam/FTB-Modpack-Issues#4474]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.10.0

### Describe the bug

This is on an Ubuntu Linux machine.

Rats can not be tamed. They are able to eat the cheese player's drop and use the cheese eating animation (until the animation stops working; presumably at the same time I should be taming them the animation breaks), make eye contact with the player feeding them, but won't be tamed (no heart animation appears at all)

Warp portals do not teleport the player. When two portals are configured for teleportation they fail to teleport the player (who stands on it for 20+ seconds)

### Steps to reproduce

Rat issue;
Feed cheese; nothing happens

Warp portal;
Configure portals; stand on a portal; never get teleported

### Expected behaviour

Ability to tame

### Additional information

I loaded a fresh install for a test and the rats still did not work; I'll assume the same for warp portals for now.

**Comment by DinnerBeef** [comment]
Invalid Issue. Please open one issue report for each issue you are facing and not one issue for both issues.
