### ISSUE TITLE
Forcecraft Healing Infusion is broken after FTB Skies 1.4

### ISSUE THREAD

**Issue by ttufts** [FTBTeam/FTB-Modpack-Issues#4477]
### Modpack

FTB Skies

### Modpack version

1.4.1

### Describe the bug

This worked in my previous play through on 1.3.1 but doesn't work anymore in my 1.4.1 play through. 

Advance through the Forcecraft tome up to the Healing infusion, add a newly created Force Rod and a ghast tear to the Forcecraft Force Infuser with the Tier 5 Tome. 

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2926882/82ce29b6-4158-4c43-a490-aedaf9bc2883)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2926882/21a433f9-052e-4dc9-8106-cd9697af5859)

This prevents advancement up to Tier 6 of the Force Tome and prevents advancement past the Time Torch quest

### Steps to reproduce

1. Advance through the Forcecraft tome up to the Healing infusion
2. Add tome and force gems to the Infuser
3. Add a newly created Force Rod and a ghast tear
4. Infusion will not activate the arrow to start the infusion

### Expected behaviour

Shgould be 

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2926882/d6e14158-ae0e-4dde-8e07-ee1db9c030e5)

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2926882/ef68aed3-0372-4544-9844-b63e10df4674)

**Comment by chunkynutella** [comment]
Can confirm having the same issue. have tried upgrading the force rod a bit but still no result just keeps saying no recipe found

**Comment by chunkynutella** [comment]
> Can confirm having the same issue. have tried upgrading the force rod a bit but still no result just keeps saying no recipe found

to add to this it looks liek ALL the rod's infusion recipe's don't work (ender pearl, obsidian block, glowstone, ghast tear)

**Comment by fellerrm** [comment]
Another way around it is to craft 2 force rods together.  I was playing on a multiplayer server so modifying files wouldn't work.
