### ISSUE TITLE
Please remove Inventory sorter. 

### ISSUE THREAD

**Issue by Shybella** [FTBTeam/FTB-Modpack-Issues#4479]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.10.1

### Log Files

https://github.com/cpw/inventorysorter/issues

### Describe the bug

https://github.com/cpw/inventorysorter/issues

Go to issues and look at the insane amount of dupes and item deleting. The mod is not great and causes many dupes while also voiding items. 

### Steps to reproduce

Just use the mod or better yet, don't.

### Expected behaviour

Not dupe and delete items.

### Additional information

Please remove abandoned mods.

**Comment by DinnerBeef** [comment]
If you are having issues with the mod and a certain inventory. Please tell me so that I can blacklist them.

**Comment by Shybella** [comment]
> If you are having issues with the mod and a certain inventory. Please tell me so that I can blacklist them.

The blacklist feature does not work with the mod.

**Comment by Shybella** [comment]
Haha, completely ignored. 

You hate to see it
