### ISSUE TITLE
FTB LITE opens without mods

### ISSUE THREAD

**Issue by NxtYuo** [FTBTeam/FTB-Modpack-Issues#4480]
### Modpack

FTB Lite

### Modpack version

all

### Log Files

No Logs needed/exist

### Describe the bug

FTB Lite is not playable in any version.

### Steps to reproduce

1. Install the Modpack on a PC which had never FTB Lite 1 installed
2. Start it
3. Minecraft opens, but it is Vanilla or something and not the modpack

### Expected behaviour

Hope to fix it, that de Modpack works again

### Screenshots

In the two Screenshots, you can see the startet MC and then an Singleplayer world with gamemode creative Inventory.
There you can see, that the items are not there.
![MC_FTB_LITE_ERROR_1](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/62716472/daf38c0b-e134-41ec-a583-3b71359be126)
![MC_FTB_LITE_ERROR_2](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/62716472/1ea150f2-c388-4b31-8d4d-67c0f68cd2eb)

### Additional information

Testet it on 5 Systems, 2 of me an 3 of my friends

I tried it in the MuliMC Launcher and there it worked to 20%. It got many issues while getting the FTB Files from the Internet and then it crashed. Maybe that Information can help a little bit.

**Comment by Gaz492** [comment]
Could you test if this is still an issue with the latest version of the FTB App?
I was not able to reproduce the issue you are having with the pack.
