### ISSUE TITLE
ME Toggle Bus quest text is inverted

### ISSUE THREAD

**Issue by avandesa** [FTBTeam/FTB-Modpack-Issues#4483]
### Modpack

FTB University 1.19

### Modpack version

1.3.1

### Describe the bug

The text in the quest `Disconeeeeeeeeeeeect` in the AE2 chapter, which requires crafting an ME Toggle Bus, incorrectly describes the toggle bus's functionality. It reads:

> The ME Toggle Bus, when given a redstone signal, will not allow channels or energy to pass through it.
> The Inverted ME Toggle Bus does the opposite, disabling when not given a signal.

This is the opposite of how these devices work. The regular toggle bus is _allows_ channels and energy through when given a signal, and the inverted toggle bus is _disabled_ when given a signal.

### Steps to reproduce

In the first screenshot, a toggle bus (right) and inverted toggle bus are receiving a redstone signal. the molecular assembler attached to the regular toggle bus is activated, while the one attached to the inverted bus is not. In the second screenshot, the busses are not receiving a signal, but the inverted bus is allowing ME through.
![2023-12-17_17 31 53](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/11090778/6b877f47-97e8-4156-9d04-f27fc085bb5b)
![2023-12-17_17 31 56](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/11090778/05afb010-1599-43b0-8ff1-b322c3206979)

### Expected behaviour

The text should correctly describe how the devices function.

**Comment by aaronhowser1** [comment]
Fixed, ty
