### ISSUE TITLE
leaf decay

### ISSUE THREAD

**Issue by calbertso** [FTBTeam/FTB-Modpack-Issues#4484]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.9.0

### Describe the bug

When mining all the logs in a tree, the leaves won't decay.

### Steps to reproduce

1. Create a world
2. mine a tree

### Expected behaviour

I expected the leaves to decay

**Comment by TheonlyTazz** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2880
