### ISSUE TITLE
[Bug] Nature's compass not listing biomes

### ISSUE THREAD

**Issue by Darksonic407** [FTBTeam/FTB-Modpack-Issues#4487]
### Modpack

FTB Skies

### Modpack version

1.4.1

### Describe the bug

After creating the "Nature's compass" item, right clicking with the item in hand opens the UI but does not provide a list of biomes to search for.

### Steps to reproduce

1. Grab a "Nature's compass"
2. Right click while in primary hand

### Expected behaviour

It should provide a list of biomes to select and search for before pointing in the direction of the nearest biome of the selected type.

### Screenshots

![Nature's Compass Bug](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/19627171/c0c11fb6-740a-4c79-afe8-6adbafbbc8f6)

### Additional information

Using the search function does not fix the issue.

**Comment by frog9394** [comment]
I have the same issue. It used to work in the previous version.

**Comment by Snoddas76** [comment]
Same issue for me too.

**Comment by BuddhaBuddy1** [comment]
Can someone add "[Bug]" to the beginning of the description, and maybe the "Mod Issue" tag? Maybe that will get it some attention.

There are lots of things that need to be done in specific biomes, which can be pretty hard to find without terrain or Nature's Compass.

**Comment by ArtpokeBr** [comment]
yeah, this is pretty much an issue with Nature's Compass, if they fix this, maybe we could bring the mod back.

It will be removed next update.
