### ISSUE TITLE
Dupe with uncrafting table

### ISSUE THREAD

**Issue by Moonyol** [FTBTeam/FTB-Modpack-Issues#4488]
### Modpack

FTB Academy 1.12

### Modpack version

1.4.0

### Describe the bug

putting 3 of an item in the place where it is used to create another item and putting that other item in the uncrafting slot shift clicking the output will dupe the 1st item

### Steps to reproduce

0. get 2 items, item 1 which you want to dupe, item 2 which can be made with item 1
1. open the uncrafting table
2. put 3 or more of item 1 in the slot where it is used to make item 2
3. put item 2 in the uncrafting slot
4. shift right/left click the output on the right this will dupe item 1 and now you can throw it out or shift click it

### Expected behaviour

for it to not dupe

### Screenshots

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/92951072/f1b13ed0-7ed0-4885-a1ec-28e45616ec2d

**Comment by manmaed** [comment]
@aaronhowser1 any word on this has this been fixed
this will auto close in 2 weeks if no response

**Comment by aaronhowser1** [comment]
It has not been
