### ISSUE TITLE
[Bug]: Lack of Potions registered as Fluids/buckets in JEI prevents autocrafting patterns in Refined Storage/AE2

### ISSUE THREAD

**Issue by Mystikite** [FTBTeam/FTB-Modpack-Issues#449]
### Modpack

FTB Ocean Block

### Modpack version

1.10.1

### Describe the bug

When creating Fluid recipes, RS/AE2 requires you to dragndrop _fluids_ from JEI (not buckets of fluid), or  a _bucket_ of the fluid from player inventory into the pattern grid.  Only a generic 'potion' fluid is defined currently, and only awkward potion is defined as a bucket (and it is bugged).

This prevents automated potion crafting via patterns.

### Steps to reproduce

type 'potion' in JEI
See that there is only a generic 'potion' fluid, and only a single bucket of 'awkward potion' available.
(ignore expected potion bottles and splash potions, etc, they are outside the scope of this issue)

### Expected behaviour

expect JEI to show available potions as fluids, and buckets.

**Comment by Raidobw2** [comment]
I've seen a recent post of a similar problem, try setting your terminal into fluid mode and vice-versa I think? When you open the terminal it's one of the buttons on the left. Let us know if that worked or not

**Comment by Mystikite** [comment]
That button toggles fluid/item mode, and is used when creating a hybrid pattern (nether wart + water(fluid) = awkward potion(fluid)).  That is not the issue.  As stated, the lack of JEI registered potion fluids and potion buckets break functionality w/rt RS/AE2 patterns/crafting, and breaks several potion recipes w/rt the alchemical brewer(thermal series mod).

**Comment by Sunekaer** [comment]
We are not hiding any liquids, is this an issue in MP or SP?

**Comment by Mystikite** [comment]
This is SP.

**Comment by Sunekaer** [comment]
Thanks, i dont know if i can do anything about this.
But ill look into it

**Comment by Mystikite** [comment]
yeah, Since the base potions are vanilla, maybe this should be a Forge issue?

**Comment by Mystikite** [comment]
Possibly a COFH/ImmersiveEngineering thing as well, since, their machines are the ones that claim to be able to process potion fluids/buckets.
As a User, I don't know who adds the 'Bucket of Awkward Potion', or the generic 'Potion' fluid to JEI. maybe they are where this needs to be addressed.

**Comment by Sunekaer** [comment]
Well since vanilla doesnt add them it would more be an RS/AE issue
