### ISSUE TITLE
add Create: Power Loader

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4492]
### Modpack

FTB Presents Direwolf20 1.20

### Is your suggestion related to a problem? Please describe.

Yes, I know we already have **many** chunk loading options including another Create-based chunk loader. However, this feels much more immersive and thematic. It is also more configurable and in active development (beyond just porting like the other Create chunk loader). I suppose it's up to Dire as to whether or not this mod should be added, and of course I could add it myself, but I thought I would suggest it anyway.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/create-power-loader

**Comment by DinnerBeef** [comment]
Thank you for your suggestion, but at this time will not be adding this mod to the Mod Pack
