### ISSUE TITLE
FTB One upgrade to 2.8.3 from 2.7.0 breaks Step Height enchant

### ISSUE THREAD

**Issue by jfmoots** [FTBTeam/FTB-Modpack-Issues#4497]
### Modpack

FTB One

### Modpack version

2.8.3

### Describe the bug

I upgraded from a 2.7.0 world to 2.8.3 and the Step Height enchant from Cyclic is no longer working. 

### Steps to reproduce

1. upgrade 2.7.0 instance to 2.8.3
2. load server
3. be sure to equip armor enchanted with Step Height enchant
4. try to walk up a single block

### Expected behaviour

You should walk up the block without the need to jump.

**Comment by UnRealDinnerbone** [comment]
This is a mod issue with Apotheosis and Cycle
