### ISSUE TITLE
Beds not advancing time

### ISSUE THREAD

**Issue by Ninetailed** [FTBTeam/FTB-Modpack-Issues#4498]
### Modpack

FTB Arcanum Institute

### Modpack version

1.3.0

### Describe the bug

Update 1.3.0 enabled the day/night cycle in the dorm dimension, but it does not seem to be possible to sleep to advance the cycle. Lying down works as normal, and the "sleeping through this night" text does appear, but when the sequence completes, it is still night.

This was observed on a dedicated server with two online players. The playersSleepingPercentage gamerule is set to 1 to allow a single person to cycle. Both players experience the issue.

### Steps to reproduce

1. Place bed in the dorm dimension
2. Wait for night
3. Sleep in bed

### Expected behaviour

Time advances to morning

**Comment by TheonlyTazz** [comment]
fixed in Dev
