### ISSUE TITLE
[Bug]: Client Randomly Crashing When Entering Compact Machine

### ISSUE THREAD

**Issue by TangentDelta** [FTBTeam/FTB-Modpack-Issues#450]
### Modpack

FTB Oceanblock

### Modpack version

1.10.1

### Log Files

[crash-2021-12-09_18.30.55-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7689097/crash-2021-12-09_18.30.55-client.txt)

### Describe the bug

When I enter a compact machine and my player is teleported to the compact machine dimension my client crashes. If I restart the game and log back into the server, I will log in inside of the compact machine I was trying to enter. This crash is relatively infrequent, and only seems to happen if I try to enter a compact machine immediately after logging in. My server is not producing any errors or extra messages when this crash occurs on my client. It appears that this has something to do with the FTBChunks mini-map, according to the crash. 

### Steps to reproduce

Enter a compact machine using the Personal Shrinking Device immediately after logging into the server.

### Expected behaviour

The client doesn't crash when entering the compact machine

**Comment by Raidobw2** [comment]
Hmm, we'll look into. For now I can think of something to prevent the crash, it might not look pretty on the minimap but if you're able to play at least that's fine as a workaround for now:
> I found a solution, in the overworld I used "map type: topography" and "Biome Blend:15x15" on the minimap, when I made the biome blend none, and the map type none, I went into the end normally, nothing happened

In-game open up the Map then click the settings:
![image](https://user-images.githubusercontent.com/17010632/145507319-0e9b9a07-f47f-4db9-8940-a5762bbff170.png)
Have it be liked this:
![image](https://user-images.githubusercontent.com/17010632/145507395-e365a234-3755-4a1f-aa06-64c4aa218b17.png)
No clue if this will work, but if it does that's better than nothing until we can fix this properly.

**Comment by TheonlyTazz** [comment]
could not reproduce this on my letsplay server with the latest in-dev instance. Tested around 5Minutes going in and out of a full Compact Machine and various relogging.
If this issue does still occur, feel free to reopen or make a new Issue
