### ISSUE TITLE
Ars Omega Demonic Essence unobtainable?

### ISSUE THREAD

**Issue by afolk2** [FTBTeam/FTB-Modpack-Issues#4501]
### Modpack

FTB Arcanum Institute

### Modpack version

1.3.0

### Describe the bug

The Demonic Essence from Ars Omega requires the Demonic Crystal from the boss? of Ars Omega. To encounter this boss you should travel to the demon dimension and find a staff in a structure to summon it. However, after flying around the demon dimension, I could find no structures.

### Steps to reproduce

Use a Ritual of Banishment with 3 full source jars and travel to the Demon Dimension.
Try to locate a structure for the demon staff

### Expected behaviour

There should be some structures in the Ars Omega dimension

### Additional information

Are structures spawning turned off for the dimension?

**Comment by Xylan** [comment]
Can confirm this issue still exists

**Comment by Hypermoron** [comment]
For whatever reason, my Demon Realm stop generating at y64
![](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/59400119/05c204e5-aa99-4f7c-83f4-1fa1409dc4c7)

**Comment by TheonlyTazz** [comment]
the issue is, that Ars Omega never was finished in 1.18; 
i added the staff as a reward inside the Ars Codex Questline to be able to fight the demon king
