### ISSUE TITLE
Returning from the Ars Omega dimension spawns you in the overworld

### ISSUE THREAD

**Issue by afolk2** [FTBTeam/FTB-Modpack-Issues#4502]
### Modpack

FTB Arcanum Institute

### Modpack version

1.3.0

### Describe the bug

After traveling to the demon dimension using a Ritual of Banishment and 3 full source jars you need to find a demonic rift and step on it to be teleported back home. However, it teleports the player to an empty overworld instead of the campus or dorm.

### Steps to reproduce

Travel to the Ars Omega Demon dimension
Find a demonic rift, they are easy to spot in the side of the islands
step on the top of the block
Get teleported to a void overworld

### Expected behaviour

The rift should teleport the player to either their dorm, or the campus spawn

### Additional information

Having the player teleported to the campus spawn could prompt them with a "Hey, we found you lost and wandering" type of message.

**Comment by Xylan** [comment]
Can confirm this issue still exists
