### ISSUE TITLE
Unable to open FTB Genisis

### ISSUE THREAD

**Issue by TrousleInTheDesert** [FTBTeam/FTB-Modpack-Issues#4503]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Log Files

https://pste.ch/mirayerusi.md

### Describe the bug

The icon for the modpack would flicker briefly on the taskbar, not even generating the image of the pack, before closing out.

### Steps to reproduce

Launch the app.

### Expected behaviour

The modpack to load.

**Comment by ArtpokeBr** [comment]
It seems that your installed wasn't done properly, missing mods to be exact.

Please, if this still persists in the next update, reopen this issue or open a new one =)
