### ISSUE TITLE
Infinite Crude Oil in Combustion Chamber

### ISSUE THREAD

**Issue by Th3SpaceCod3x** [FTBTeam/FTB-Modpack-Issues#4504]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Describe the bug

If you place a Small Fluid Tank with Crude Oil in the Combustion Chamber, it dosen´t consume Crude Oil from the Small Fluid Tank

### Steps to reproduce

![Screenshot_13](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/50593498/88ca5ec3-cc69-4b6c-b4b1-fa83a851d5b3)
Place down a Combustion Chamber
Put a Small Fluid Tank filled with Crude Oil in the Combustion Chamber

### Expected behaviour

It will consume the Crude Oil from the Small Fluid Tank

**Comment by ArtpokeBr** [comment]
It is consuming now, probably fixed in a recent mod update =)
