### ISSUE TITLE
Game crashing chunk generation

### ISSUE THREAD

**Issue by Dragonvi1** [FTBTeam/FTB-Modpack-Issues#4505]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.10.0

### Log Files

No useful log files are ever generated. It just throws a generic `java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)` when the cap set to the default. Or will be stuck for at least an hour if `max-tick-time` is set to 0.

### Describe the bug

When a user tries to generate chunks in a specific 3x3 area. It probably get's stuck in an infinite loop generating something. Problem occured on a dedicated linux version running the latest docker image of `itzg/minecraft-server` on my own device in single player mode using the same world file. And on a device of my friend who generated a fresh world using the seed.

### Steps to reproduce

1. Create new world
2. enter seed `-3119173828365203853`
3. travel to 40, -640

### Expected behaviour

From the moment that the 3x3 chunks entered render distance your server should have stopped saving any progress/do any tick updates

### Screenshots

Close image of the area that couldn't be loaded
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/154750370/f02893ed-7278-4eba-9609-0419e35bee3d)

Image of 1. the area where I had to paste chunks to prevent server questions and 2. world spawn
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/154750370/96e1280b-9e7c-4342-b026-1fc81c0506a4)

**Comment by Dragonvi1** [comment]
O yes, for people experiencing similar issues. What I ended up doing was to zip the world and move it to my personal pc. Extracted once as a single player world and enclosed on the troublesome area from all cardinal directions hitting escape each time I entered a new chunk to force a quick save and destroy a block of dirt to see or the item would spawn. As soon as the dirt thing stopped working force shut the game and go for the next direction.

After you've mapped all 4 directions, I used a tool called MCA Selector. and opened the world in it (I opted to use the zipped world instead of the one modified using singleplayer). Then I copied a chunk grid into the troublesome area. Deleting the chunks won't work since the issue is related to world gen.

**Comment by pantheis** [comment]
Came here looking to see if someone else had reported this, as I'm getting this on my server with my friends. The exact same issue. I'm unsure where the problem chunk that's having issues is though.

Unsure if it's useful, but I attached my crash log.

[crash-2023-12-25_22.32.07-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13769267/crash-2023-12-25_22.32.07-server.txt)

**Comment by OsirisKalev** [comment]
Had the same issue. Crash log didn't show anything obvious, except a tic took 60 seconds. We were able to consistently crash the server when exploring a certain part of our world too. Avoiding that area from generating kept our server going fine. I can only assume that we are having the similar issue of a bad chunk/structure generation occuring.

[crash-2023-12-25_23.25.46-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13770163/crash-2023-12-25_23.25.46-server.txt)

**Comment by pantheis** [comment]
Update: On a hunch, I tried updating the NoMoWanderer mod to the latest version, as it's the only mod jar listed in the crash logs, and it's in both of them. That didn't fix it, but after removing the mod completely, the server didn't crash again when I went to the area that had been triggering it.

Instead, I got these in the server console:
```
[17:58:14] [Server thread/ERROR] [minecraft/PoiSection]: POI data mismatch: never registered at BlockPos{x=-1103, y=-16, z=-115}
[17:58:14] [Server thread/ERROR] [minecraft/PoiSection]: POI data mismatch: never registered at BlockPos{x=-1102, y=-15, z=-115}
[17:58:14] [Server thread/ERROR] [minecraft/PoiSection]: POI data mismatch: never registered at BlockPos{x=-1102, y=-16, z=-114}
[17:58:21] [Worker-Main1/INFO] [ModernFix/]: Instantiating Mojang DFU
```

When going to the coords listed in spectator, it's the air blocks right above a trio of loot barrels from Lootr.
I hope this information helps someone track down what's happening, but at least for me, in the place that I could reliably crash the server every time, it's now not crashing after removing the NoMoWanderer mod.

![2023-12-26_18 07 04](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1609871/472cdfa6-e54b-4164-ba8f-79d95dad302a)

**Comment by brddleader** [comment]
# @pantheis 

Thank you for pointing this out. I can confirm that after removing the NoMoWanderer mod the crashing issue stopped. I was able to render the area without issue. The mod had to be removed from the server and the client.

**Comment by Romariin** [comment]
Hi, I'm also using `itzg/minecraft-server:latest` and I'm experiencing the same crashes as you as soon as a player loads a specific chunk, the server crashes. I tried to remove `nomowanderer` among the mods, but it didn't change anything as soon as reconnecting, the problem persists.

I have no further information in my crash log, which I've linked below. Do you have any idea? 🫠
Thank you!

[crash-2024-01-01_14.31.57-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13804899/crash-2024-01-01_14.31.57-server.txt)

**Comment by MMonteMiner** [comment]
I've also encountered this crash; using DW20's "DW20LP20V120" seed in 1.10, there's some haunted chunk(s) somewhere to the east of the spawn that will trigger it (I haven't identified precisely where).

Removing/disabling nomowanderer-1.20.1_1.6.2 from the modpack prevents the crash.

[crash-2024-01-05_15.59.17-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13847739/crash-2024-01-05_15.59.17-server.txt)

**Comment by Suni-Shinobi** [comment]
disabling nomowanderer fixed my lets play world
