### ISSUE TITLE
FTB StoneBlock 3 world don't working

### ISSUE THREAD

**Issue by kanapka11** [FTBTeam/FTB-Modpack-Issues#4506]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Describe the bug

I open Stoneblock 3 and everything is okay, but if i wan't to join to the world it's loading forever. Last time I playing 15 hours ago and then is everything okay, but now it's don't working.

### Steps to reproduce

1.Open FTB App
2.Open FTB StoneBlock 3
3.Join to the world and don't working

### Expected behaviour

Opened my world

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/154755692/425e4f42-714a-4e4f-b59c-72cb73572385)

**Comment by UnRealDinnerbone** [comment]
Please attach the log file
