### ISSUE TITLE
Immersive Engineering Alloy Brick

### ISSUE THREAD

**Issue by Exhale180** [FTBTeam/FTB-Modpack-Issues#4508]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Describe the bug

Unable to craft Alloy Bricks (or Kiln Bricks)  for Alloy Smelter/Alloy Kiln.  recipe file indicates 
{"type":"minecraft:crafting_shaped","key":{"b":{"tag":"forge:ingots/brick"},"s":{"tag":"forge:sandstone"}},"pattern":["sb","bs"],"result":{"count":2,"item":"immersiveengineering:alloybrick"}}

But does not show up in JEI and does not work when manual crafting.

### Steps to reproduce

input recipe in crafting grid.  Nothing shows up.

### Expected behaviour

Should craft 2 Alloy Bricks

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/154767404/f96548ec-24eb-4f34-bcb9-cea14eb331ab)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/154767404/e421d2b7-5669-499f-a9b9-0ffa1522c69b)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/154767404/bb83265c-c32e-4cf5-b1dd-d71f59e48d68)

### Additional information

Have also tried with all variations of sandstone (including red)

**Comment by ArtpokeBr** [comment]
The Alloy Kiln shouldn't be accessible, you should use other alloying options instead. =)
