### ISSUE TITLE
Apotheosis Spawner causing other zombie spawns

### ISSUE THREAD

**Issue by afolk2** [FTBTeam/FTB-Modpack-Issues#4509]
### Modpack

FTB Arcanum Institute

### Modpack version

1.3.0 

### Describe the bug

When I have the pictured spawner down and active with a lever I get zombies spawning around 30 blocks away that have AI. I have a similar spawner for wither skeletons for my blood magic, but no extra wither skeletons spawn outside of the range with AI

### Steps to reproduce

Grab a zombie spawner from the Endless Realm
Use apotheosis modifiers to make the pictured spawner
Activate the spawner with a lever
At night time zombies spawn outside of the spawners range with AI

### Expected behaviour

No extra zombie spawns should happen

### Screenshots

![2023-12-24_18 21 32](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/24921099/9e6bfb3c-3d53-41ec-a199-adf31bd0eda3)

![2023-12-24_18 46 48](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/24921099/d29eebbb-bec5-4a65-afc4-879e97f495d4)

### Additional information

The second screenshot is where I have the spawner placed while harvesting blood. It is enclosed with the 3 high placement for a zombie on each side

**Comment by TheonlyTazz** [comment]
This is because zombies spawn reinforcement mobs, this is vanilla behavior.
https://minecraft.wiki/w/Zombie
Check here under behavior.



Closed as it's not an issue
