### ISSUE TITLE
[Bug]: RFToolsUtility Crafters Not Displaying Recipes When Reloaded

### ISSUE THREAD

**Issue by TangentDelta** [FTBTeam/FTB-Modpack-Issues#451]
### Modpack

FTB Oceanblock

### Modpack version

1.10.1

### Describe the bug

Programming recipes into the RFTools crafter works as expected, and the programmed recipes can be re-viewed even after closing and re-opening the GUI of the block. Upon reloading the dimension that the crafter is in (via traveling to a different dimension and back again, loading a saved game, leaving and joining a server, etc.) you will be unable to view the recipes held in the crafter. The crafter will continue to craft using these recipes without any problems.

I have this issue in both single-player and connected to my server. I did not experience this issue in 1.9.0.

### Steps to reproduce

1. Program some recipes into an RFToolsUtility crafter
2. Save and quit to the main menu
3. Load the world
4. Open the crafter and observe the lack of recipes

### Expected behaviour

Being able to review and edit the recipes in the crafter

### Screenshots

![image](https://user-images.githubusercontent.com/3003211/145494261-11848108-a64e-4566-9979-c36ada2e1455.png)

**Comment by rafern** [comment]
I manually updated RFToolsUtility to v3.1.6 and the problem went away. I also updated RFToolsBase, RFToolsBuilder, RFToolsPower, RFToolsStorage and McJtyLib but I'm not sure if you have to update all of these.
