### ISSUE TITLE
Lumberjack Foliot doesnt work.

### ISSUE THREAD

**Issue by SkyDev125** [FTBTeam/FTB-Modpack-Issues#4510]
### Modpack

FTB Arcanum Institute

### Modpack version

1.3.0

### Describe the bug

The foliot Doesnt go and break trees as expected, neither does he place any items in the chest if further than 2 blocks away from the place where he's supposed to deposit things.

He simply doesn't walk, just stands still and does nothing.

### Steps to reproduce

1 - Spawn a lumberjack foliot
2 - Set his work area and deposit inventory
3 - watch him do nothing

### Expected behaviour

Lumberjack foliot should break trees, replant them, and pick the items, and put them in the chest

### Screenshots

<img width="656" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/41944315/8d84ef35-dc8d-4d8b-8557-2b45e1533646">

### Additional information

I've noticed that supposedly this issue was previously reported here for a different modpack:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3634

I'd assume the same issue could be solved by doing the same resolution?

**Comment by JohannDumoulin** [comment]
Same Problem
The issue is reported on the occultism github : https://github.com/klikli-dev/occultism/issues/891
The problem seems to be a mod that prevent the lumberjack AI from working in a matter of performance
It seems to be fix in 1.19.2, I don't know if it can be fix in Arcanum

**Comment by TheonlyTazz** [comment]
sadly there is no occultism updates coming out for 1.18.2 anymore, so i'm afraid this is not something we can fix; i will make a note in the pack about this!
