### ISSUE TITLE
Loading specific chunks crashes server and breaks singleplayer

### ISSUE THREAD

**Issue by Bug-Bites** [FTBTeam/FTB-Modpack-Issues#4513]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.10.0

### Log Files

No useful log files generated

### Describe the bug

From the instant specific chunks are generated the server immediately stops responding. In singleplayer, once you've loaded these chunks you are unable to save your world.

### Steps to reproduce

Create a world with the seed 2238317527795937136
Go to roughly X:85 Z:-580

For more time for the chunks around the issue to load, try a -50sh X coordinate, this will more clearly demonstrate the specific set of chunks that cause the game to stop working.

### Expected behaviour

The game should immediately stop being able to load new chunks, or stop responding altogether if it's a server.

**Comment by RevLaw** [comment]
We got the same issue at seed "2380711957785352345" roughly at -500 / 50

error log: [Pastebin](https://pastebin.com/nRh2jnUM)

**Comment by Cwmwd24** [comment]
Might be the same issue as #4465 ?

**Comment by Suni-Shinobi** [comment]
i have the same issue in my lets play world by a meteor

**Comment by Suni-Shinobi** [comment]
similar issue reported removing or disabling nomowanderer mod fixes this in most cases. can confirm in my lets play world

**Comment by DinnerBeef** [comment]
Same issue as https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4569. This issue will be resolved in the next update!
