### ISSUE TITLE
Overlays and Non-tile entities are Invisible.

### ISSUE THREAD

**Issue by Zarepheth** [FTBTeam/FTB-Modpack-Issues#4516]
### Modpack

FTB University 1.19

### Modpack version

1.3.1

### Describe the bug

Immediately upon starting my first world with this modpack, I was unable to view creatures in the forest where I spawned. I could hear them, but could not see them. I am used to targeted blocks having an outline, but that was not visible, though I could interact with the blocks. Breaking tree trunks and grass sometimes had logs or seeds appear in my inventory, but I could not see them on the ground, nor any entities moving from the ground to myself.

I tried to preview an initial quest's reward for a starter house, but I could not see any preview. However, going on blind faith I placed it down and after a few moments, the prefabricated house suddenly appeared. I've been playing for 1.5-2 hours, with no visible entities in the world and no overlays. It is very disconcerting. Upon breaking any blocks, crops, stone, trees, etc... the drops are invisible, which makes it hard to know if I've picked out all the available drops.

### Steps to reproduce

Before creating the world, I adjusted the main Minecraft options to my preferences:
View angle: 90 degrees.
Fullscreen: on.
Head bobbing: off.
Auto-step: off.
Adjust a few keybinds.

Scrolled through the list of mods to see if I wanted to adjust any settings. For the Light-Overlay mod, I set the view to Numbers and turned on the underwater and in mushroom biomes options. I think I adjusted something else, but nothing I would expect to impact entity visuals.

Before creating the world, give it a name and turn on the bonus chest.

Create the world - see no animals (though hear their sounds).
Break a tree trunk, but see no dropped logs.
Break grass, but see no dropped seeds.
Walk in the area where grass was broken and perhaps acquire some seeds...

### Expected behaviour

Animals visible. Drops visible. Tools hung an Tetra racks visible. Breaking progress overlays visible.

### Additional information

I've seen quite a few open reports for invisible entities. About half are from earlier editions of the FTB University modpack (prior to Minecraft 1.19). None of the open issues have any solutions.

I've not yet checked for closed issues...

**Comment by Zarepheth** [comment]
I closed and restarted Minecraft. Entities are now visible.
No settings changes, so I haven't a clue why entities started invisible or why they stopped being invisible. Anyway, it is much better when I can actually see them!

**Comment by aaronhowser1** [comment]
I have no idea how to even begin tracking this bug down. It's wildly inconsistent. I don't know what triggers it, nothing in the log mentions it, it's just very confusing and upsetting.

**Comment by Zarepheth** [comment]
I’ve continued playing the mod pack, almost daily, even through last evening.  The problem has not recurred since I posted about it. 

I have to agree, I’ve got no idea how anyone could reproduce it in a manner to troubleshoot.

**Comment by UnRealDinnerbone** [comment]
Seems like this issue fixed itself. If the issue comes back, please let use know
