### ISSUE TITLE
when I start the world I fall into the void

### ISSUE THREAD

**Issue by KenviX16** [FTBTeam/FTB-Modpack-Issues#4517]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Describe the bug

The commands don't work and the game mode cannot be changed, what should I do?

### Steps to reproduce

I don’t know how to reproduce this bug, I can assume that this is due to the fact that I installed 104 water wheels
![Base Profile Screenshot 2023 12 29 - 19 47 48 33](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147339626/3513323d-3f1d-42e8-8e6e-1675a3c5910a)

### Expected behaviour

Any error correction will do

### Screenshots

![Base Profile Screenshot 2023 12 29 - 19 47 48 33](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147339626/88ce4965-63fc-4abe-a843-b78315931466)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/147339626/8ab4a9a8-df15-4ec1-8e74-b8ac92db9741)

**Comment by UnRealDinnerbone** [comment]
Please upload your latest.log and debug.log
