### ISSUE TITLE
FTB Genesis crashing while loading

### ISSUE THREAD

**Issue by FielCrenteDaTerrabola** [FTBTeam/FTB-Modpack-Issues#4518]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Log Files

https://pste.ch/raw/layiqagute

### Describe the bug

Just installed the modpack, but the instance is crashing during boot.

Already tried to delete and download the files again, as well as restarting my computer, but the same bug keep happening.

I'm playing arcane institute without any problems.

### Steps to reproduce

Boot instance

### Expected behaviour

The game should open

**Comment by ArtpokeBr** [comment]
This seems to be related to your Java/Mem Allocation, try reinstalling Java or Updating it to a compatible version.

Also.... 🇧🇷
