### ISSUE TITLE
[Bug]: The crafting recipe for the Certificate of Magical Competency does not unlock after meeting requirements

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#452]
### Modpack

FTB University 1.16.5

### Modpack version

1.3

### Describe the bug

After completing the Ars Nouveau chapter, the crafting recipe for the Certificate of Magical Competency, required for the creation of AN creative items, does not unlock like it is supposed to.

### Steps to reproduce

Complete AN's chapter.
Collect all rewards.
Click certificate in JEI.
Get told to complete AN's chapter.

### Expected behaviour

Recipe unlocks so it can be crafted.

**Comment by zoller27osu** [comment]
(You can work around this by doing `/kubejs stages add @p ars_completed`)

**Comment by aaronhowser1** [comment]
It uses game stages, not kubejs stages

**Comment by aaronhowser1** [comment]
Tested it myself, after completing the chapter I *do* get the stage, but the recipe doesn't show as unlocked.
![image](https://user-images.githubusercontent.com/15698722/147386631-c8bf9ef6-1437-408b-ba64-684fad004bef.png)
![image](https://user-images.githubusercontent.com/15698722/147386632-4798aa3e-deee-42a0-bda2-122e766dcc5b.png)

However, after a `/reload`, it *does* work
![image](https://user-images.githubusercontent.com/15698722/147386641-7babf601-7aff-4d54-84e7-7e8dbc50607e.png)

I'll tell the mod dev.

**Comment by aaronhowser1** [comment]
Got around to it eventually :P
