### ISSUE TITLE
Cardboard Boxes not working

### ISSUE THREAD

**Issue by TanCY1** [FTBTeam/FTB-Modpack-Issues#4522]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.9.0

### Describe the bug

The cardboard boxes from Coxinha Utilities do not work

### Steps to reproduce

1. Click on any block with a Cardboard Box

### Expected behaviour

The cardboard box replaces the original block

**Comment by Gaz492** [comment]
I believe you need to shift right-click on the blocks to have the cardboard box replace the original block.
I also believe that this doesn't work on all blocks and only ones with an inventory or those that are classed as a tile entity.

I tested the cardboard box on a chest, mob spawner and a few other blocks such as a creative motor from create, and it looks to be behaving as expected.
