### ISSUE TITLE
Stoneblock 3

### ISSUE THREAD

**Issue by slxckxn** [FTBTeam/FTB-Modpack-Issues#4525]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Describe the bug

When i start to load into my world the screen freezes and crashes the app

### Steps to reproduce

1.Start world 2.Game freezes 3. Game Crashes

### Expected behaviour

i expect the game to crash

**Comment by MichaelHillcox** [comment]
Please attach a crashlog
