### ISSUE TITLE
particle effects causing FPS lag with "void junk" enabled on mining gadgets

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4529]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Describe the bug

massive FPS lag when using 7x7 with void junk enabled and high efficiency

### Steps to reproduce

1. mine stuff as I described
2. FPS cries

### Expected behaviour

no FPS lag

**Comment by Gaz492** [comment]
If you remove the void junk upgrade, does the issue continue to occur for you?
I noticed an FPS drop while using the gadget with efficiency 5 added, but no extra drops with the void junk upgrade added.
