### ISSUE TITLE
Map settings unavailable after using map settings menu

### ISSUE THREAD

**Issue by axiom2000** [FTBTeam/FTB-Modpack-Issues#4531]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Describe the bug

Repeatable error.  Opened map settings and changed a value in FTB chunks menu.  The settings cog wheel icon no longer works.  The only way to open the map settings menu is to use the "S" hot key.  

### Steps to reproduce

1. Press M to open map settings.
2. Click the cog wheel to open the settings menu.
3. Make a change to the mini map (for example).
4. Accept the changes.
5. Try to repeat step 2 but the cog wheel is no longer responsive.  Only the hot key S works to get back to map settings.

### Expected behaviour

Expect the cog wheel icon to open the map settings.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
