### ISSUE TITLE
Mekanism Fusion Reactor - showing wrong values for MFE/t and heat generation using D-T fuel

### ISSUE THREAD

**Issue by axiom2000** [FTBTeam/FTB-Modpack-Issues#4532]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Describe the bug

Piping Deuterium and Tritium into a Fusion reactor produces 4MFE/t (2 inject rate) and behaves normally.   A second fusion reactor with D-T fuel pumped directly into fusion reactor produces 102.40 MFE/t (2 inject rate).  102.4 MFE/t must be a incorrect value and should be producing 4MFE/t.  If both reactors are set for inject 2, then they should be producing the same MFE/t.

### Steps to reproduce

Have one fusion reactor using Deuterium and Tritium - it produces D-T fuel inside the reactor. (inject 2)
Have second fusion reactor fuel receiving D-T fuel directly. (inject 2)
Both reactors will have a different value for MFE/t production.

### Expected behaviour

if both reactors are set for inject 2, they should both produce the same MFE/t.

**Comment by RundownRhino** [comment]
I don't believe the injection setting applies to directly piping DT fuel. For example, [on the wiki](https://wiki.aidancbrady.com/wiki/Fusion_Reactor) there's a tip about it:
> To keep the reactor running at a constant rate, it is best to pipe in Deuterium and Tritium separately at a rate greater than half of the specified injection rate in the fuel tab for each type of fuel. Piping in D-T fuel will result in the reactor using it all up to an 1000mB/t rate, or a 500mB/t rate of both Deuterium and Tritium

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
