### ISSUE TITLE
Unable to start pack... please see the instance logs...

### ISSUE THREAD

**Issue by RealBurmi** [FTBTeam/FTB-Modpack-Issues#4535]
### Modpack

FTB Skies

### Modpack version

1.4.1

### Log Files

![Bild_2024-01-05_221548193](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/155778096/095beb83-811b-4471-984b-4ba380b0cc85)

### Describe the bug

When i want to start FTB Skies, it wont start and i get this error code "Failed to prepare instance "FTB Skies" ... . because ... java.io.IOExeption: Failed to execute asset update task. I deleted it completly and reinstalled it but it dont work.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/155778096/7c6ad903-9b2f-4fe9-acd2-4c6b20349639)

### Steps to reproduce

1. Install FTB APP 
2. Install FTB Skies 1.4.1
3. Start FTB Skies 
4. Get an Error Code

### Expected behaviour

I want to start the game

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/155778096/450bebce-7a81-401c-bb2c-58a85920f507)

**Comment by ProdOrDev** [comment]
I had this same issue for FTB Skies Expert. The game, more specifically creeperlauncher, was trying to download an asset which it supposedly failed to do.

If you look in `C:\Users\xxxxx\AppData\Local\.ftba\logs\latest.log` at the very bottom it shows that the download failed after 3 attempts.

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/148014775/c4bb8fbc-ba1a-4840-819d-589231fd3c75)

After "crashing", e.g. failing to load the modpack, there existed a file called `_tmp_85c860ea8c55984bf6cabb75354c78f3a603f98d` in the correct object folder `assets/objects/85/`. To make the game load I simply removed the `_tmp_` prefix.

If there is no temporary file in the folder you can simply download it from `https://resources.download.minecraft.net/85/85c860ea8c55984bf6cabb75354c78f3a603f98d` and place it into `assets/objects/85/` named as `85c860ea8c55984bf6cabb75354c78f3a603f98d`.

Hopefully this helps you.

**Comment by Gaz492** [comment]
If you are still running into this issue would you be able to open a new issue on our app tracker: https://github.com/FTBTeam/FTB-App/issues
