### ISSUE TITLE
FTB OceanBlock - No safe structure generated in nether on firs enter.

### ISSUE THREAD

**Issue by botondszilniczky** [FTBTeam/FTB-Modpack-Issues#4536]
### Modpack

FTB OceanBlock

### Modpack version

1.16.0

### Describe the bug

No safe structure is generated when entering nether!

### Steps to reproduce

1. Create a new word.
2. Enter nether with painting.
3. Swim in lava :(

### Expected behaviour

Safe structure is generated like in previous versions.

**Comment by manmaed** [comment]
This issue is stale and pack is no longer being worked on
