### ISSUE TITLE
Stoneblock 3 can't join my world

### ISSUE THREAD

**Issue by fartgat** [FTBTeam/FTB-Modpack-Issues#4537]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13850898/debug.log)
[crash-2024-01-06_21.54.36-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13850902/crash-2024-01-06_21.54.36-server.txt)

### Describe the bug

Yesterday my game was okay. But today i start the game , click on my world after checking the log , i saw server is crashing with no reason, i found some help guids for my problem, they not help me

### Steps to reproduce

1. Click play in FTB launcher
2.Click singleplayer in main menu of minecraft
3.Join my world
4.Server is not responding and crash

### Expected behaviour

I just wanna play minecraft

### Additional information

I trying it so many times and no one advice can help me

**Comment by fartgat** [comment]
idk what is problem,but i run my previous backup and its work

**Comment by UnRealDinnerbone** [comment]
This was casued by an issue with forge config system
