### ISSUE TITLE
[Bug]: Server remove refined storage patterns when restart

### ISSUE THREAD

**Issue by Felixchong882003** [FTBTeam/FTB-Modpack-Issues#454]
### Modpack

FTB Oceanblock

### Modpack version

1.9.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7692829/latest.log)

### Describe the bug

When I restart the server, I found that one of the refined storage crafter (not connected to machine/inventory) have all the recipe patterns and speed upgrades disappear. It happened 3 times, first time is a gold crafter full of pattern, second and third time are netherite crafter. Not sure is it related to number of crafter/ number of patterns

### Steps to reproduce

1. have plenty of crafter connected in a refined storage network
2. restart server
3. check crafters is any pattern missing

### Expected behaviour

All the patterns inside one of the crafter disappear

### Screenshots

![Inked2021-12-10_20 51 58_LI](https://user-images.githubusercontent.com/22407689/145577005-93bf43f2-f652-4a46-8f4e-bfdf7aa215c0.jpg)
In the third time happen, is the crafter in the circle have its content disappear. I was guessing it is related to too many crafter placed next to each other so i placed this one another place. But this didn't fix the problem

**Comment by Felixchong882003** [comment]
I just found that there is error in the log file near the end related to extrastorage

**Comment by Raidobw2** [comment]
Thanks for the report and the link to the opened issue on ExtraStorage!
