### ISSUE TITLE
FTB Direwolf 20 pack Multibow enchantment doeas not work since the last update

### ISSUE THREAD

**Issue by DasCxbweb** [FTBTeam/FTB-Modpack-Issues#4541]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Log Files

.

### Describe the bug

FTB Direwolf 20 pack Multibow enchantment doeas not work since the last update

### Steps to reproduce

no steps needed --> FTB Direwolf 20 pack Multibow enchantment doeas not work since the last update 
my bow just shoots one arroe instead of 3 

### Expected behaviour

it should shoot 3 arrows at once 

### Screenshots

.

### Additional information

.

**Comment by DinnerBeef** [comment]
There is no enchantment name called "Multibow". Are you talking about multishot from Minecraft?
