### ISSUE TITLE
DW20 1.20 slots missing from curio with 1.11.0

### ISSUE THREAD

**Issue by hopkinssm** [FTBTeam/FTB-Modpack-Issues#4542]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Describe the bug

With the 1.11.0 upgrade, curio slots for items like gloves, capes, and shields are no longer available.

### Steps to reproduce

Open inventory, and select the curios tab.

### Expected behaviour

The slots were previously available, and loot is being generated that fits in these slots.

**Comment by Jakalth** [comment]
Press I on your keyboard.  It opens a seperate window that has the "missing" curio slots.

**Comment by Bluebottle39** [comment]
The slots seem to be missing from all the curio interfaces
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/56110672/769c0f23-d709-441c-87fb-80dcd669354f)

For me it seems to be the 3 slots added by The Aether mod that are missing which are the ones mentioned by op (gloves, capes, and shields)

**Comment by JakeMoe** [comment]
Wierd, the slots are missing from my inventory screen, but I can see them in the other GUI that comes up when I press "I".

**Comment by hopkinssm** [comment]
> Wierd, the slots are missing from my inventory screen, but I can see them in the other GUI that comes up when I press "I".

Agree.   I was unaware of 'I', but they were previously on the 'normal' curios tab. I'm not sure what the expected behavior is at this point.

**Comment by Bluebottle39** [comment]
From what i have seen in the configs it looks like the aether is now defaulting to use its own implimentation (the accessory system) instead of curios one. That would explain the missing curio slots.
