### ISSUE TITLE
Direwofl20 1.20 - Nickel Dust only smelts in Thermal Induction Smelter, no other furnace

### ISSUE THREAD

**Issue by JakeMoe** [FTBTeam/FTB-Modpack-Issues#4543]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Describe the bug

Not sure if this is by design and intended now that Thermal has been added, but my Raw Nickel processing has broken; it still changes to Nickel Dust in the Enrichment Chamber, but the resulting dust can no longer be processed by my Mekanism Smelting Factory.  The only way to process Nickel Dust now is in a Thermal Induction Smelter.  Can the recipes for Nickel Dust in various Smelters be re-added, or was that change intended, and I need to re-work my ore processing?

### Steps to reproduce

Put Raw Nickel in Enrichment Chamber and get Nickel Dust.  The resulting Nickel Dust can only be processed in Thermal Induction Smelter, no other smelter (including vanilla furnace) will accept it.

### Expected behaviour

Nickel Dust behaves like other dust and can be smelted.

### Additional information

If this is intended and by design, feel free to close as such, and I'll work around it.  It just feels like an oversight / bug, so figured I'd report it.  :-)

**Comment by Suni-Shinobi** [comment]
compacting drawer still makes nickel blocks and nickel can be used with other dust to make alloy which can then be smelted
