### ISSUE TITLE
(Pedestals Mod) Planter Pedestal gets stuck/halts on crops in the way of its pathing

### ISSUE THREAD

**Issue by mrgattz** [FTBTeam/FTB-Modpack-Issues#4544]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Describe the bug

Planter pedestal will stop planting completely if there is another plant in the way of its planting path (including its own crops that it's planted) which prevents it from continuing to plant anything until that crop has been harvested or removed.

### Steps to reproduce

1. get a planter pedestal set up
2. set up a work area
3. put another plantable object in the way of its planting path
4. watch it not continue to plant until you remove said object

### Expected behaviour

exxpected to skip over the obstruction and continue to plant in work area

### Screenshots

![wheat seeds in the way](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/81583750/df0de50a-ca23-4415-820e-26fee8569222)
i have manually planted wheat seeds in the way of its pathing of planting potatoes to halt the planter but this can be achieved by also just waiting a long time for crops to grow and be harvested as it will not replant in the open spots until the crop in its pathing has been harvested, to which it will get stuck at the next occupied block.
![work area](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/81583750/671ebfc1-5f1e-4318-a607-b07cc37d7b96)
in the back you can also see that its own pedestal gets in the way of planting as well.

**Comment by Mowmaster** [comment]
Fixed in 1.19, a fix for 1.20+ is coming

**Comment by DinnerBeef** [comment]
Issues have been resolved in the latest version of the modpack.
