### ISSUE TITLE
Arcanum Institute Crash using occultism storage terminal

### ISSUE THREAD

**Issue by MuriloObr** [FTBTeam/FTB-Modpack-Issues#4545]
### Modpack

FTB Arcanum Institute

### Modpack version

1.3.0

### Log Files

[crash-2024-01-09_01.02.11-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13876032/crash-2024-01-09_01.02.11-client.txt)

### Describe the bug

I started crafting an item a few minutes after the world opened and when I put the items into the crafting slots, the game crashed...
For you know, I clicked on the item and dragged it to spread it

### Steps to reproduce

1. Start the world
2. Open occultism storage terminal
3. drag items to spread in the crafting

### Expected behaviour

I was expecting to not crash the game

**Comment by TheonlyTazz** [comment]
Seeing how this is a rare crash that has happened and Occultism isn't activly being developed anymore for 1.18.2 i'm going to close this.
