### ISSUE TITLE
Lag spikes when opening AE2 system 

### ISSUE THREAD

**Issue by ydnar2000** [FTBTeam/FTB-Modpack-Issues#4552]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Log Files

https://spark.lucko.me/NMyOEBpBtU

### Describe the bug

Lately I've been having annoying lag spikes while I'm trying to open my AE2 system and certain other modded inventories. They're not absolutely huge lag spikes but big enough to make it unplayable. Trying to open recipes with JEI whilst in my AE2 system also gives lag spikes. I can't seem to figure it out myself and I don't really know how to fix it myself. I hope someone else could take a look at my spark files and give some advice. 

### Steps to reproduce

1 Open certain inventories from mods (mainly AE2 and JEI together) and receive a lag spike 

### Expected behaviour

No lag whilst doing this

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
