### ISSUE TITLE
[Bug]: Pipez java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by SirKratosAurion** [FTBTeam/FTB-Modpack-Issues#4553]
### Mod

Pipez

### Mod version

1.20.1-1.1.3

### Forge / Fabric version

47.1.3

### Modpack & version

FTB Unstable 1.20

### What issue are you having?

Server Crash

### Crashlogs

[crash-2024-01-12_02.38.52-server.txt](https://github.com/FTBTeam/FTB-Mods-Issues/files/13911062/crash-2024-01-12_02.38.52-server.txt)

### Steps to reproduce

connected item pipe to top of vanilla single chest, connected other end to bottom of vanilla single chest, wrenched the top of the pipe on the lower chest and the server crashed.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
