### ISSUE TITLE
IC2 Classic Crop Harvester and Metal Crops

### ISSUE THREAD

**Issue by raymondbweaver** [FTBTeam/FTB-Modpack-Issues#4554]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Describe the bug

IC2 Classic crop harvester is only harvesting one dust per metal plant, but right click harvest is giving a handful.

### Steps to reproduce

1. Grow metal plant with high output
2. Place crop harvester in range
3. Watch as harvester only harvests one dust

### Expected behaviour

Harvester collects same amount of dust as right click

**Comment by raymondbweaver** [comment]
Update - gold plant is harvesting correctly, but iron and copper are not

**Comment by ArtpokeBr** [comment]
please, if this issue still persists in the most recent update, reopen this issue or open a new one =)
