### ISSUE TITLE
Unable to craft Super Cable due to missing Polished Gold recipe

### ISSUE THREAD

**Issue by Ortintzki** [FTBTeam/FTB-Modpack-Issues#4556]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Describe the bug

The recipe for Polished Gold Ingots from IC2 does not exist in JEI even though Polished Gold Ingots are searchable in the JEI interface.  It's unclear if it can be created at all.  This locks us out of Uncompressed Super Cables and subsequently Super Cables.  Super Cables exist in the modpack as a quest reward so it's not clear if this is an oversight or not.  These recipes seem to be based in the IC2 mod but it's not clear whether Polished Gold Ingots exist in any version of the modpack.

### Steps to reproduce

1. Open your inventory/access the JEI menu
2. Search for "Polished Gold Ingot"
3. Try to backsearch its creation using right click.
4. No entry should exist describing how to create Polished Gold Ingots

### Expected behaviour

Polished Gold Ingots should have a recipe for its creation in JEI that can be used in the world.  OR the recipe for Uncompressed Super Cables no longer requires Polished Gold Ingots

### Additional information

I think this is a mod configuration issue, but I'm not able to figure out where the recipe for super cables are in the mod files.  Super cables are referenced in the IC2 manual (Using Patchitouli?  I don't know what mod is responsible for the Akashic Book) but no description about how to create them exists.

**Comment by Repellium** [comment]
Has there been a fix to this yet? It seems the brewing system might be disabled for this pack? From what I've read, the polished gold requires alcohol to create, but there's no recipe for alcohol so I assume brewing is disabled.
