### ISSUE TITLE
Mekanism Enriched Alloy Recipe Broken

### ISSUE THREAD

**Issue by SitHOBO** [FTBTeam/FTB-Modpack-Issues#4557]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Describe the bug

No recipe appears for Mekanism Enriched Alloy appears in JEI any longer. Other uses within machine infuser seem (after a cursory look through) to be functioning as expected (i.e. previous version 1.10.0 of pack).

### Steps to reproduce

Checking recipe in jei yields no entries for alloy
checking uses for infuser yeilds all other recipes.

### Expected behaviour

Expected to see enriched alloy via iron ingots in infuser with redstone 'extra'

**Comment by DinnerBeef** [comment]
Are you talking about Enriched Iron from "Refined Storage"? Mekanism does not add anything called "Enriched Alloy"

**Comment by vetchris** [comment]
when 5 times a ore it goes to crusher makes clumps but the dirty dust has no where to go should be going into enriching factory
