### ISSUE TITLE
Terra Glass - no tool to break and not recognized by building gadget mod

### ISSUE THREAD

**Issue by axiom2000** [FTBTeam/FTB-Modpack-Issues#4559]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Describe the bug

Terra glass by Cyclic has no tool to break it.  The mod Building gadgets can not break it either.

### Steps to reproduce

Place Terra Glass in world
No tool available to break, so it takes a very long time to break.

### Expected behaviour

Should have a tool associated to break it

**Comment by DinnerBeef** [comment]
Seems to be working fine for me; However, it does seem like "Tatta Glass" is a Block Entity, so you would need to turn on the setting in the destruction gadget for that.
