### ISSUE TITLE
[Bug]: Projectred pattern crashes client

### ISSUE THREAD

**Issue by Petapaka** [FTBTeam/FTB-Modpack-Issues#456]
### Modpack

FTB Oceanblock

### Modpack version

1.7.0

### Log Files

[crash-2021-12-10_08.48.11-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7693960/crash-2021-12-10_08.48.11-client.txt)

### Describe the bug

When accessing a Refined Storage crafter containing a pattern for ProjectRed, the client crashes.

### Steps to reproduce

1. Use Refined Storage to create patterns for ProjectRed items
2. Put the pattern into a crafter from refined storage (Netherite crafter used in this case)
3. Attempt to review the patterns in the crafter
4. The client crashes

### Expected behaviour

The player can view the patterns in the crafter

**Comment by Petapaka** [comment]
Updated to 1.9.0 and the error still occurs.

**Comment by Raidobw2** [comment]
Update to 1.10.1 as shown in #151, this will correct the issue.
Have a good day!

**Comment by Petapaka** [comment]
Thank you!
