### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Knugent25** [FTBTeam/FTB-Modpack-Issues#4560]
### Modpack

FTB Skies

### Modpack version

1.20.51

### Describe the bug

Can’t pick up the sifter to move it to a new location after use 

### Steps to reproduce

1. Place sifter, and mesh on it 
2. Run sifter with items in it 
3. Try to brake it
4. Won’t brake so I can move it 

### Expected behaviour

I was hoping I could pick it up and move it

**Comment by ArtpokeBr** [comment]
Seems to be fixed in the most recent version of the pack.
