### ISSUE TITLE
Keep getting FTB-AUTH-000012

### ISSUE THREAD

**Issue by LuckyBoyAlex** [FTBTeam/FTB-Modpack-Issues#4561]
### Modpack

FTB Genesis

### Modpack version

ex 1.18

### Log Files

FTB-AUTH-000012

### Describe the bug

why does it say (The account used does not have an XBox Live account, this likely means you haven't yet migrated your account...) wheni already have migrated my account and i can play multiplayer on all clients. I was late with migration but I luckily got to get minecaft for free but didnt keep all my worlds. So I missed first step of migration.

### Steps to reproduce

help me show what to do

### Expected behaviour

i should get logged in

### Screenshots

![Screenshot 2024-01-14 160235](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/156593939/80012139-84ae-485c-b53f-2c9249724732)

### Additional information

The account used does not have an XBox Live account, this likely means you haven't yet migrated your account...

**Comment by Gaz492** [comment]
If this is still an issue for you please open a new issue on our App issue tracker https://github.com/FTBTeam/FTB-App
