### ISSUE TITLE
Electrodynamics circuit breaker not working (Mod update required)

### ISSUE THREAD

**Issue by piedrrum** [FTBTeam/FTB-Modpack-Issues#4562]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Describe the bug

Electrodynamics circuit breaker is not working. I looked into sources and it is supposed to protect circuit depending on voltage and turn off / on power with redstone (by doing iron trapdoor noise) but nothing happening. It has been fixed in recent electordynamics mod update. (Tested with a quick forge setup)

### Steps to reproduce

Open a world in creative
Put a Creative power source with 999V and 9999MW output.
Put a circuit breaker with a redstone lever on (no noise here but noise expected).
Place a 120V furnace at red side (output) ==> it explodes, circuit breaker is not preventing current to pass.
This can be also seen with a multi meter.

### Expected behaviour

Restone must control circuit breaker, circuit breaker must protect lower voltage output against overvoltage.

### Additional information
After some local tests with recent release, I think electrodynamics needs to be updated.

On another modpack, a guy is experiencing the same issue with the mod:
around 2:33:30
https://www.youtube.com/watch?v=CfRYZHWRe5g

Also class file off the mode (cant say if it has been fixed on recent version):
https://github.com/aurilisdev/Electrodynamics/blob/1.19.2/src/main/java/electrodynamics/common/tile/electricitygrid/TileCircuitBreaker.java

**Comment by piedrrum** [comment]
I dont know if its the right way to proceed (quoting someone like this) but maybe @skiprocks999 already worked on that

**Comment by skiprocks999** [comment]
We just released a bug patch for 1.19.2 on Jan 10th (v0.8.1-0). The Circuit Breaker actually did not work prior to this update. The code you are referencing is part of that patch. I know Saereth is working on an update for the pack to include the latest release. Please respond to this thread if the issue still persists.

**Comment by ArtpokeBr** [comment]
updating the mod now! =)
