### ISSUE TITLE
While on LAN, chunks won't load no matter what I do.

### ISSUE THREAD

**Issue by ClockworkSnowman** [FTBTeam/FTB-Modpack-Issues#4565]
### Modpack

FTB Arcanum Institute

### Modpack version

1.3.0

### Describe the bug

While playing as a guest on a LAN world hosted by a family member I live with, I would say roughly a quarter of all the chunks (on the school grounds, the sky island where we can interact with things doesn't have this issue) won't load, F3+A doesn't fix it, relogging doesn't help, even things like uninstalling/reinstalling doesn't fix it. I have done some research and this is an issue not exclusive to myself, and after nearly 24 hours of waiting, a "help me" reddit post did not have a single comment from staff nor other members. 

### Steps to reproduce

1. start a new world
2. turn on LAN
3. have another device/account join that LAN world
4. walk around the premises of the school, these holes are absolutely everywhere

### Expected behaviour

I expect this problem to get solved and the chunks to start loading, this is extremely dampening my ability to, and experience of playing the game.

### Screenshots

![Screenshot 2024-01-13 161354](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/156607323/9c3b19c1-e845-4b16-9e3d-e119a85b3b14)

### Additional information

the chunks load just fine for the LAN host, but as soon as any of the npcs go in or they do, they disappear instantly. I saw someone else with this issue and they were told something about sodium not playing nice with something else, IDK if there's any merit to this, but maybe there is.

**Comment by camcam95** [comment]
I too am having this issue

**Comment by brianHeroic** [comment]
I am also having this issue...

**Comment by TheonlyTazz** [comment]
This is an issue with the Signposts mod; sadly this issue never got found during testing and because of the nature of Arcanum Institute, with the premade world, there is no real way for us to remove them from your current playthrough
