### ISSUE TITLE
crashing when attempting to use auto crafting

### ISSUE THREAD

**Issue by ViscoseMC** [FTBTeam/FTB-Modpack-Issues#4566]
### Modpack

FTB OceanBlock

### Modpack version

1.16

### Log Files

https://pste.ch/agewacebin.md

### Describe the bug

When using the (Refined Storage) wireless crafting terminal all is fine until I click on a recipe I have saved, then my game crashes.

### Steps to reproduce

1. Open wireless crafting terminal
2. Search for saved recipe
3. Click on any recipe

### Expected behaviour

Expected to select the amount I want to craft

**Comment by manmaed** [comment]
This issue is stale and pack is no longer being worked on
