### ISSUE TITLE
server keeps crashing on same spot

### ISSUE THREAD

**Issue by Steelduck1** [FTBTeam/FTB-Modpack-Issues#4569]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Log Files

Crash report:
https://pastebin.com/TU4gGRDU

Console log:
https://pastebin.com/JqDmAXYW

### Describe the bug

server keeps crashing on same spot. I ran in a waystone onces removed the mod but it still happend

### Steps to reproduce

just walked around in ftb direwolf

### Expected behaviour

not crashing

**Comment by Suni-Shinobi** [comment]
i believe this is from the meteors

**Comment by Suni-Shinobi** [comment]
similar issue has reported removing nomowanderer mod fixes. i can confirm for my letsplay world. fixed loading in specific chunk with loot barrels and chests

**Comment by Steelduck1** [comment]
Okay thanks, gonna try both out

**Comment by Shybella** [comment]
How is this still not fixed? The pack is literally crashing out of the box? What's the point?

**Comment by DeliciousJaffa** [comment]
Still have this issue on 1.12.1
> 1.12.0
Fixed
NoMoWanderer causing chunk load locking [#4569](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4569)

**Comment by Shybella** [comment]
Why is everyone abandoning everything? What the hell is going on

Direwolf20 1.19 is also crashing out of the box because an image name has a capital D in it..

**Comment by Steelduck1** [comment]
Uninstalled nomowanderer and it fixed it for me.

**Comment by mcdodge34** [comment]
Update NoMoWanderer to .64 version this will fix the issue for the ones that look for this problem.
