### ISSUE TITLE
[Bug]: Ultimate Singularity recipe does not work

### ISSUE THREAD

**Issue by alexandrusendroni** [FTBTeam/FTB-Modpack-Issues#457]
### Modpack

FTB OceanBlock

### Modpack version

1.10.1

### Describe the bug

When trying to craft the Ultimate Singularity, the Fusion Crafting Core implies No Valid Recipe

### Steps to reproduce

1. Have a Fusion Crafting core with 30 Draconic Fusion Crafting Injectors
2. Place all 30 singularities from the recipe from JEI
3. Place a Quantum Entangled Singularity in the Fusion Crafting Core
4. The message: No Valid Recipe appears

### Expected behaviour

The Craft button should appear and, when pressed, the crafting should begin.

### Screenshots

![2021-12-10_18 16 46](https://user-images.githubusercontent.com/74202515/145607743-ec462bec-aad7-4692-9629-db06a4529d6c.png)
![2021-12-10_18 38 09](https://user-images.githubusercontent.com/74202515/145609124-9c354079-0ae5-452c-a26d-1c42e8330621.png)

**Comment by quietust** [comment]
One of your injectors is being blocked by something, because the Fusion Crafting Core only shows **29** different singularites available.

**Comment by alexandrusendroni** [comment]
Yes, you are correct. I tried the recipe in a creative world and it works. I now see that the Ender Chest is blocking one of the injectors. The bug can now be closed as not a Bug!
