### ISSUE TITLE
FTB App failing to download any modpack

### ISSUE THREAD

**Issue by Crasyee** [FTBTeam/FTB-Modpack-Issues#4570]
### Modpack

FTB Sky Odyssey

### Modpack version

1.4.2

### Describe the bug

Anytime I try to download any modpack, I have tested with both FTB and Curseforge packs. It says requisted to download [] it then starts and I can see it go to my instances. Then as soon as I see a percentage it says "Failed to install [] due to unexpected error]"

Also sorry for no better description I am not very knowlagable on computers 

### Steps to reproduce

1. Click install on any modpack. 

### Expected behaviour

Help me fix this please

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/153146278/1041fcc8-da38-41d8-90d6-dd2cc97a585d)

**Comment by Crasyee** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/153146278/d42a66e0-65c4-4ee2-acab-d8251e3585fe)

**Comment by Gaz492** [comment]
If this is still an issue for you with the app would you be able to open a new issue on our App tracker: https://github.com/FTBTeam/FTB-App/issues
