### ISSUE TITLE
Rabbits

### ISSUE THREAD

**Issue by Suni-Shinobi** [FTBTeam/FTB-Modpack-Issues#4572]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Describe the bug

Rabbits not spawning

### Steps to reproduce

Go to any plains or forest and search for rabbit.

### Expected behaviour

find rabbits

### Additional information

this breaks a lot of enchants in the game and lots of magic mods

**Comment by DinnerBeef** [comment]
Rabbits do now spawn in Plains or Forest Biomes. You can go here to see where they do spawn. https://minecraft.wiki/w/Rabbit
