### ISSUE TITLE
Minecraft Expedition by Welsknight modpack

### ISSUE THREAD

**Issue by Mogley182** [FTBTeam/FTB-Modpack-Issues#4573]
### Modpack

Other...

### Modpack version

1.1.3

### Describe the bug

no JEI appears when pressing "E" to access inventory.  Therefore, no crafting is available.  

### Steps to reproduce

just create a new world and open your inventory 

### Expected behaviour

No JEI or crafting menu appears

**Comment by Gaz492** [comment]
This issue tracker is only for FTB modpacks, you will need to report the issue to the author of that specific modpack.
