### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by zenzen33** [FTBTeam/FTB-Modpack-Issues#4575]
### Modpack

FTB StoneBlock 3

### Modpack version

1.18.2

### Log Files

[2024-01-19-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13979170/2024-01-19-1.log.gz)

### Describe the bug

My server crashes when I open a Modular Storage with a Storage Module Tablet

### Steps to reproduce

1. Place a Modular Storage
2. Add the Storage Module Tablet
3. then boom server crashes

### Expected behaviour

Well I expected everything to work just fine since ive been playing on my server for 4 days and nothing has happened until I insterted that module, I cant remove it now since i have to open the Modular Storage to remove it.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/157041974/d03c1c61-1e58-4e6c-a42b-de513ef23a30)

**Comment by UnRealDinnerbone** [comment]
This issue has been open since Feb without and update closing this issue
