### ISSUE TITLE
EnderIO Clear Glass seems to be uncraftable

### ISSUE THREAD

**Issue by 0GroundZero0** [FTBTeam/FTB-Modpack-Issues#4576]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.0

### Describe the bug

EnderIO's clear glass seems to be uncraftable as it shares a recipe with at least one other mod's clear glass. The clear glass produced from the recipe (in my case it was Cyclic's smooth glass) is not usable as a substitute in recipes requiring EnderIO's clear glass. I attempted with several different smelting blocks and types of glass and none worked.

### Steps to reproduce

1. Reference JEI for EnderIO clear glass recipe
2. As per JEI smelt vanilla glass
3. Output of the recipe is Cyclic smooth glass

### Expected behaviour

I expected there to be a method of producing the glass from EnderIO.

**Comment by DinnerBeef** [comment]
Try putting the alloy smelter on alloys only mode. Please let me know if that resolved the issue for you.
