### ISSUE TITLE
Netherite ingot, Block, and nugget no longer work in compacting drawer (functional storage mod)

### ISSUE THREAD

**Issue by dalgrim** [FTBTeam/FTB-Modpack-Issues#4577]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.0

### Log Files

n/a

### Describe the bug

After completing the upgrade from DW20 1.10.0 to 1.12.0 My functional storage compacting drawer that had my netherite stored in it changed from the correct nugget,bar, and block to only nuggets. Attempting to add netherite nuggets to a new compacting drawer places them in the top center slot where blocks should be. Adding Netherite blocks or ingots to a new compacting drawer adds those two correctly to the drawer but omits nuggets. Other ore types are correctly converted and stored. This only seems to be affecting netherite. images attached of issue.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/12730893/67287414-3eef-4714-974e-513a20cc7558)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/12730893/df2cb2c5-d911-4d29-b91a-f6cab0fb0e0a)

### Steps to reproduce

place netherite ingots, blocks, or nuggets into a compacting drawer.

### Expected behaviour

All three types to be correctly converted in correct ratio in a single drawer

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/12730893/67287414-3eef-4714-974e-513a20cc7558)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/12730893/df2cb2c5-d911-4d29-b91a-f6cab0fb0e0a)

**Comment by DinnerBeef** [comment]
Unable to reproduce this, issue. Please reopen if you are still having issues with this. Try reinstalling the modpack to see if that fixes it.
