### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Suni-Shinobi** [FTBTeam/FTB-Modpack-Issues#4578]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.0

### Describe the bug

not really a bug but since the last update went from 60 fps to 10-20 fps. makes the pack almost unplayable and definitely not fun.

### Steps to reproduce

update client and start world 
check performance

### Expected behaviour

same consistent fps as last build

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can take a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

May I also ask what the output of the command `/spark tps` is?
