### ISSUE TITLE
[Suggestion]: Easier Cobblestone/Cobblestone Singularity?

### ISSUE THREAD

**Issue by zoller27osu** [FTBTeam/FTB-Modpack-Issues#458]
### Modpack

FTB University 1.16

### Is your suggestion related to a problem? Please describe.

We've managed to get every singularity except for the Cobblestone one. 10k 4x compressed cobblestone is actually a lot. (Like, 65 million.)

- I don't particularly want to build a metric ton of Cobble Gen Tier5's, since each requires an inventory _above_ them or automated extraction via pipes, etc. Each only makes 1 Cobble per tick anyways. So a single one would take 14 years to generate enough and 900 of them would still take a week.
- Void Mining for it isn't really viable, since anywhere you can mine for Cobblestone, you can also get Stone, and they share the Gray lens, but Stone's focused weight is 2000 compared to Cobblestone's 1200, and Cobblestone is mined as `forge:cobblestone` which means when you roll it you randomly get one of many different variants of Cobblestone, and only the vanilla Cobblestone can be compressed. So no matter what modifiers you use, you don't get very much Cobblestone even at max speed. You can get a lotttt of Stone though.
  - It would be nice if I could crush (using Mekanism's Crusher) Compressed Stone into Compressed Cobblestone the same way that you can smelt any tier of Compressed Cobble into the same tier of Compressed Stone? That would be the only way I can think of to really process the stone into cobblestone fast enough to be worth it though.
- Quarrying/Digital Mining for that much real cobblestone can't be good for the frame rate (all that water and lava updating) since I wouldn't have enough of any material to replace it all with.
  - Actually, the Digital Miner doesn't go fast enough, but even if it did, it refuses to replace Stone with Stone, even if Silk Touch is off so you would actually get Cobblestone.
  
Am I missing something? How am I meant to get all that Cobblestone?

**Comment by Raidobw2** [comment]
Thanks for the suggestion

**Comment by aaronhowser1** [comment]
Lowered it from 10,000 to 2,000, and added a new recipe:

![image](https://user-images.githubusercontent.com/15698722/147387042-6cd2906a-579d-43dd-a0d8-3da05fdc0c94.png)

So you can use the first to make more for free
