### ISSUE TITLE
Mekanism ore processing 

### ISSUE THREAD

**Issue by vetchris** [FTBTeam/FTB-Modpack-Issues#4582]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Describe the bug

when processing ores with mekanism goring from purification chamber that makes clumps, to the crushing factory makes dirty dust now has no where to go. when pressing R on the dirty dust there is no recipe. in version 1.10.0 it went into the enriching factory  then smelter.

### Steps to reproduce

clumps to dirty dust

### Expected behaviour

no recipe for mekanism dirty dust

**Comment by LarsBorris** [comment]
I can confirm this is still an issue on 1.12.1 - I am also having this problem - All ore processing is halted because of this.

**Comment by Lord-Seth** [comment]
I saw another bug report concerning this being closed... apparently the Bug then got reintroduced in a later version?
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4036

**Comment by Lord-Seth** [comment]
One can also just manually delete the following parts from the "recipe_removals.js" in kubejs\server_scripts

        `mekanism:processing/iron/dust/from_dirty_dust`,
        `mekanism:processing/gold/dust/from_dirty_dust`,
        `mekanism:processing/osmium/dust/from_dirty_dust`,
        `mekanism:processing/copper/dust/from_dirty_dust`,
        `mekanism:processing/tin/dust/from_dirty_dust`,
        `mekanism:processing/lead/dust/from_dirty_dust`,
        `mekanism:processing/uranium/dust/from_dirty_dust`,
        
        that turns the recipe back on

**Comment by DinnerBeef** [comment]
Unable to reproduce this, issue. Please reopen if you are still having issues with this. Try reinstalling the modpack to see if that fixes it.
