### ISSUE TITLE
Incorrect file name when updated ftb direwolf20 1.19 from version 1.12 to 1.13.0

### ISSUE THREAD

**Issue by cdcecho** [FTBTeam/FTB-Modpack-Issues#4583]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.13.0

### Describe the bug

Updated to 1.13.0 then wasnt able to launch because the file names beginning in DWL in this address ".ftba\instances\e9ac6a44-0fd5-42eb-8bc2-baba32246fd6\kubejs\assets\direwolf20\textures\ui\button" were all uppercase but needed to be undercase. Simple fix for the user but im sure theres people who arent very tech savy.

### Steps to reproduce

1. update from 1.12.0
2. try to launch
3. error

### Expected behaviour

launch

**Comment by kn4s96** [comment]
I solved it this way: Open the startup log so you get the notes file with the error. Go into the file directory for your instance and find the kubejs folder. Then, follow the directory in the startup log until you find the images in question that is causing error. Lastly: simply rename them to the same thing but in lowercase.

I tried it and my instance started up without issue afterwards.

**Comment by jasoncollege24** [comment]
Installed this fresh (not an update), and exported it to another launcher. Had exactly the same problem with exactly the same files. Based on the circumstance, this would've happened if launched directly within the FTB app too.

Renaming the files to be lowercase resolved the issue right away.

**Comment by Gaz492** [comment]
This issue should be fixed in the latest version of the pack
