### ISSUE TITLE
No recipe for block of Ruby and Sapphire

### ISSUE THREAD

**Issue by Yusunoha** [FTBTeam/FTB-Modpack-Issues#4585]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.0

### Describe the bug

It's not a huge problem, but in the DW1.20 pack there's no recipe for a block of ruby and sapphire.
Because of this you're not able to craft a ruby or sapphire bee, because those require blocks of ruby and sapphire to bed fed to a diamond bee.

### Steps to reproduce

Look up the recipe for a block of ruby and sapphire. You can see the items in JEI, but there's no a recipe for it.

### Expected behaviour

When you craft ruby or sapphire in a 3x3 grid you'd be able to craft the items into block form.

### Additional information

This problem was there since the moment the ruby and sapphire items were added with the thermal mods. Perhaps this may be a thermal recipe problem?

**Comment by Suni-Shinobi** [comment]
compressing drawers?
