### ISSUE TITLE
JAOPCA version mismatch error

### ISSUE THREAD

**Issue by NatalieZorah** [FTBTeam/FTB-Modpack-Issues#4589]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/13998826/latest.log)

### Describe the bug

I upgraded to version 1.12.0 of the pack and copied the updates over to my server. When I got everything transferred, including updating the scripts and KubeJS folders, and then attempted to log into the server, it tells me that there is a version mismatch with JAOPCA (see screenshot). I backed up and deleted the server side configs folder and copied my client side configs over, that didn't work. I deleted the mod from the server and copied it over from my client, and then vice versa, neither of which worked. I copied over my entire mods folder, deleted all the duplicates and old versions, and then tried again, same result.

All of this remains true even with a fresh install of the pack on the client, so it feels like a config issue somewhere, but I don't know which config is doing it. I provided the log of the client-side messaging when it occurred. The only think I see is something to do with Nickel dust, which was one of the listed fixes in the update, though I am unsure if this is the issue or how to fix it.

### Steps to reproduce

1. Update from 1.11.0 to 1.12.0 on client and server.
2. Attempt to log in.

### Expected behaviour

Successful Login

### Screenshots

The error.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/93982667/af2d2eb0-0fb2-4ad4-87f3-b0bc03902b08)

Server and Client mods folders.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/93982667/e6aa4735-441c-4493-8be4-53de81f248dd)

### Additional information

I spent several hours trying to find a solution that doesn't just involve a complete loss of the server, or a lengthy roll back process.

**Comment by DinnerBeef** [comment]
Can you try and reinstall the server by deleting both the kubejs folder and the config folder first and seeing what happens?

**Comment by NatalieZorah** [comment]
I got the same error after deleting both the config and kubejs folders.

**Comment by DinnerBeef** [comment]
Can you try and replacing "config/jaopca/main.toml" with this https://pste.me/@ia9RAXgBAtE/raw

**Comment by NatalieZorah** [comment]
On both client and server?

**Comment by DinnerBeef** [comment]
Yea, try both client and server

**Comment by NatalieZorah** [comment]
That solved it! I don't know what toml-fu you did, but thank you much!

**Comment by DinnerBeef** [comment]
Thank you! There will be a fix out soon to resolve this issue for everyone else. :)

**Comment by LivingManiac** [comment]
Hi, I am getting this issue but the pste.me link in this thread dosnt work, any chance of a fresh link?

**Comment by pucgenie** [comment]
affects server updated to Direwolf20 1.20 1.16.0 too/again (client installed on fresh system)
4.4.10.17
