### ISSUE TITLE
Angel Block voided by RfTools Builder

### ISSUE THREAD

**Issue by becky15675** [FTBTeam/FTB-Modpack-Issues#4590]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.0

### Describe the bug

Angel block from Angel Block Renewed mod gets voided when mined by the RfTools builder with a clearing silk quarry installed

### Steps to reproduce

set up the builder and set up a quarry shape card with clearing silk (solid box).
All void options are off within the shape card.
have angel blocks within the selected area
turn on the builder and angel blocks will not appear in the chest

### Expected behaviour

Angel blocks to be mined like a normal block, not voided

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by becky15675** [comment]
Updated to 1.13.1
yes it still voids the angel block

**Comment by Gaz492** [comment]
In the last couple of weeks we released another update to the modpack, is this still an issue?
