### ISSUE TITLE
Task screen issue

### ISSUE THREAD

**Issue by wickedj81** [FTBTeam/FTB-Modpack-Issues#4592]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Describe the bug

I'm not sure quite how to describe this issue but attempting to complete the "Defragmentation" quest I've created the Lesser Entangled Matter and checked off that part of the quest. As far as the 2M FE I've got to 1.99M using the combustion generator from Electrodynamics and it won't go any further no matter what I do. 
I;ve broken the task screen and moved it, used different cables, all to no avail. Am I doing something wrong or did the task screen just freak out and decide I'm not allowed to complete this task
![2024-01-21_16 50 30](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/117311253/3456bbf7-46a7-4213-ad87-b163d63ea0e9)

### Steps to reproduce

Go to Quests > Defragmentation> Defragmentation quest
Supply 2 million FE and create a Lesser Entangled Matter and the quest should complete 

### Expected behaviour

Alas, I have no ideas unless the task screen bugged out

### Screenshots

![2024-01-21_16 43 17](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/117311253/c278b6d5-a77b-40b6-bd33-28631e65c253)

**Comment by CarterJWallace** [comment]
This usually occurs when not using the IE wires as described in the first quest in which you power the task screen. It has a picture with the setup and how you should keep it wired as other wires and cables will cause issues like this where it becomes ~99.99% full and the next packet is more than ~0.01% and so it won't accept it.

**Comment by wickedj81** [comment]
I used the IE cables both LV and HV, I used various power sources with the IE cables and no change.

Is there a config file I can edit to complete this damn task or reset the task so I can try the IE cables from the start? I'm at a bit of a stand still

**Comment by CarterJWallace** [comment]
If you have OP you can reset or complete any quest in the quest log. There's a button on the bottom right to turn on editing mode.

For what it's worth, I never changed my setup from the original setup given in the quest screenshot and never encountered the issue. Electrodynamics energy network connected to ED wire and then an IE connector to IE wire to and IE connector on the task screen.

**Comment by wickedj81** [comment]
Reset my tasks and after painfully re-doing them all I did use the IE wires and that worked.

Thanks for the heads up on the wires and the task reset, appreciate it!
