### ISSUE TITLE
unobtainable platinum jetpack and components have returned

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4595]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

Platinum jetpack is visible as possible crafting component for emerald jetpack, but made with empty tag for platinum. Ditto for components.

### Steps to reproduce

Look up the recipe for emerald jetpack, then platinum jetpack. Observe empty tags.

### Expected behaviour

these recipes should not be visible if platinum doesn't exist

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1498260/85201049-d4a5-4f6c-bf84-3f429a5b5e49)

**Comment by Gaz492** [comment]
Closing in favour of #5249
