### ISSUE TITLE
aether gloves not equippable

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#4596]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

Curio slots are present again but unusable.

### Steps to reproduce

Attempt to equip aether gloves into curios tab. Nope.

### Expected behaviour

gloves should equip

**Comment by Famish3d** [comment]
Hey!

The only way I've found to equip the "aether gloves" is putting them in your hot bar and right click it in hand. They dont show up in the curious slot so only way to "unequip" would be to alt+f4 yourself and gather items via gravestone.

Hope this helps!
Famished

**Comment by itsmemattk** [comment]
I was stumped by this for a long time as well, but just happened on the fix today. There's a little cloud looking icon on the bottom right of the player picture in the inventory screen that has a slot for the gloves, among other things.

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you in the latest version of the pack?
