### ISSUE TITLE
JAOPCA version mismatch error

### ISSUE THREAD

**Issue by SinnFullOne** [FTBTeam/FTB-Modpack-Issues#4597]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

updated server to 1.12.1 from 1.11.0 and got the version mismatch with JAOPCA. that was to be fixed in that update. it seems that it did not work and now the issue has continued on to the " fixed " version.

### Steps to reproduce

1: updated server
2: tried to log in

### Expected behaviour

log into game no issue

**Comment by mirmaed** [comment]
I am having the same issue after updating to 1.12.1

**Comment by Gaz492** [comment]
Would you be able to try running the server installer/updater again?
On a fresh install of both the modpack and server I have not been able to reproduce this issue.
