### ISSUE TITLE
No crafting recipe for Cyclic's Sack of Holding 

### ISSUE THREAD

**Issue by Bifasaurus** [FTBTeam/FTB-Modpack-Issues#4598]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.

### Describe the bug

The cyclic mod's sack of holding does not have a recipe and you can not get an empty one from creative.

### Steps to reproduce

1) Launch DW20 1.20 pack. 
2) Open a world
3) try to craft a sack of holding from the Cyclic mod.
4)  See that there is no recipe 

### Expected behaviour

I expect to be able to make one, I only need one to move things. 

### Screenshots

![2024-01-24_16 34 30](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/142745359/cf596d1b-8820-48f7-8ca1-9fd42961ce55)

**Comment by Bifasaurus** [comment]
Note:  I am playing this mod pack on a private server.  I'm not sure if this means there are different configs set.

**Comment by mcdodge34** [comment]
The FTB team probably disabled this item because its way too easy to create early game and can sometimes be used to dupe items, but you can use mekanism cardboard box instead, it does the same job, put some wood logs in a pulverizer and you'll get the sawdust needed for them.

**Comment by Bifasaurus** [comment]
Thank you for your reply!  I found out .... or just realized really that the the FTB launcher was updating my client but the server never updated.  I had to do that manually.  Now everything works!  👍
