### ISSUE TITLE
No crafting recipe for Comfort Mod's sleeping bag

### ISSUE THREAD

**Issue by Bifasaurus** [FTBTeam/FTB-Modpack-Issues#4599]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.11.0

### Describe the bug

Can't craft a sleeping bag from the comfort mod.  Jei does not show a recipe just the items.  Putting in the known recipe into a crafting grid does not produce a sleeping bag. 

### Steps to reproduce

1) Launch a world in Direwolf20 1.20 mod pack
2) Search JEI for sleeping bag and see that there are no crafting recipes.
3) try to use known recipe and it does not work.

### Expected behaviour

I expect to be able to make a sleeping bag so I can sleep w/o resetting my spawn

### Screenshots

![2024-01-24_16 40 06](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/142745359/a55ee744-5106-484b-b67b-e603a6279674)
![2024-01-24_16 40 22](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/142745359/18f7831b-1384-440b-b098-ce63d46c922a)

**Comment by Bifasaurus** [comment]
Note:  I am playing this mod pack on a server.  I'm not sure if this means there are different configs set.

**Comment by jlp1528** [comment]
I would talk to the server owner/operator if possible to first of all update the server to pack version 1.12.1. Also, I'm not sure why, but the sleeping bag recipe is not like beds; the wool MUST be placed in the top row of the crafting grid.

**Comment by DinnerBeef** [comment]
Yea due to more than one mod adding a recipe that uses 3 wool across the recipe was changed to only work on the top row.
