### ISSUE TITLE
Lag and or crash when looking up chickens in JEI

### ISSUE THREAD

**Issue by LordeThapi** [FTBTeam/FTB-Modpack-Issues#4604]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Describe the bug

Sometimes when we go to search @chickens or look up chickens recepies we get a lot of lag or even crashes.

### Steps to reproduce

1. Open Inventory
2. Search @chickens
3. check a recepie

### Expected behaviour

Lag free chicken recepie

**Comment by CesarDenis** [comment]
I have the same issue here

**Comment by MichaelHillcox** [comment]
Please attach a crash log

**Comment by edledwith** [comment]
As I have the same issue, how would I get what you need. 

When I search @chickens my Minecraft (stoneblock 3, launched through FTB app) instantly begins to stop responding (the Windows Insert program here has stopped responding and gets the slightly white screens), and for about 1 out of every 10 seconds my game un-freezes. If I close my inventory or clear my search bar the game will continue running completely fine.

If this matters this is a multiplayer server that I am hosting, my friend also playing on server has his game crash if searches @chickens as well. I have plenty of RAM to both the server and Stoneblock 3.

**Comment by H3RO993** [comment]
I have done a little bit of testing myself. Not 100% confident but it seems as though it is being caused by the null egg within REI. I have looked through everything else from the mod individually and that is the only thing that, for me, is causing lag every time.

**Comment by Liam-Selleslagh** [comment]
I can't even hover over anything, the moment I type it in it freezes already the question is how can I stop it from doing it

**Comment by Liam-Selleslagh** [comment]
@UnRealDinnerbone a friend of mine managed to get a Debug log on this issue hopefully it helps
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14379122/debug.log)

**Comment by TheTrueLM** [comment]
Anyone figure this out yet? Im stumped. We run a dedicated server for the pack and everyone who has anything from the Chickens mod show up in the JEI will experience client freezes. If theyre lucky they can sometimes empty the search bar or change the JEI page to fix the issue. Most of the time they have to end the process and restart the client.

**Comment by TheTrueLM** [comment]
I get "java.lang.NullPointerException" spam in client console when anything from Chickens mod shows up in JEI

**Comment by Liam-Selleslagh** [comment]
I somehow got it to not freeze or crash but when I'm looking at chickens or eggs my pc starts reving up like a madman I did also find the Null egg

**Comment by TheTrueLM** [comment]
The Null Egg seems to be the issue. I tried to duplicate the freeze issue in singleplayer in both 1.9.0 and 1.8.1 with it not happening. It only seems to affect servers due to the Null Egg only existing on servers, the egg doesnt show in SP.

Is there a way to remove that item from the files?

**Comment by Liam-Selleslagh** [comment]
not sure I've been scanning through them and I seen no mentions of this type of egg anywhere

**Comment by Declan-F** [comment]
Here's the log (console.log) file for the console when I replicated the issue on a recently created server. I also zipped all other log files that might be relevant along with it. I have not skimmed through the console log yet. 
[Download 2024-02-23T01 12 36.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14380770/Download.2024-02-23T01.12.36.zip)

**Comment by Liam-Selleslagh** [comment]
so far in ur console log I've seen the same "java.lang.nullpointerexception" spam I also have
in the others I haven't found much only 1 other spam but that about workerpool something

**Comment by edledwith** [comment]
I actually seem to have found a fix, at least for me. 

If you hover the settings, Display settings --> Enable "Caching Entry Rendering" I can open @chickens (and search the null egg) and not crash
![image_2024-02-22_203501979](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/58717193/d1b4152b-bf02-4246-9bbb-6b17d1818d71)

**Comment by TheTrueLM** [comment]
> I actually seem to have found a fix, at least for me.
> 
> If you hover the settings, Display settings --> Enable "Caching Entry Rendering" I can open @Chickens (and search the null egg) and not crash ![image_2024-02-22_203501979](https://private-user-images.githubusercontent.com/58717193/307201881-d1b4152b-bf02-4246-9bbb-6b17d1818d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTI0NzksIm5iZiI6MTcwODY1MjE3OSwicGF0aCI6Ii81ODcxNzE5My8zMDcyMDE4ODEtZDFiNDE1MmItYmYwMi00MjQ2LTliYmItNmIxN2QxODE4ZDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAxMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YjRkMWM0OWMwNTRmZjZkZmIxYzA2YTdiZDg3NDkwMjQ2MmQ1YWYzNzlkZDI5OGZmODg5ZTVlOGNiY2FhMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-hapTPDEGLnucjovzJO9ztXEnJDImq9e4j_95wv9pQY)

This is the fix right here bro. Thanks for the find. Just tried it on my end and its works without issues.

**Comment by UnknownDev37** [comment]
Still an issue. The Caching Entry Rendering fixes it.

**Comment by APOCAMANDER** [comment]
Still broken. Turning Caching on still is the fix.
