### ISSUE TITLE
Ad astra manual doesnt open and ad astra items cannot be searched on rei

### ISSUE THREAD

**Issue by OrhunTokdemir** [FTBTeam/FTB-Modpack-Issues#4605]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Describe the bug

ad astra mod manual astrodux cannot be opened and when I search ad astra mods items on rei like "@ad astra" only astrodux comes up. because of this I'm having trouble using the ad astra mod.

### Steps to reproduce

right click with astrodux in your hand. it doesn't open.

### Expected behaviour

ı expected astrodux to open and let me see ad astra mods manual

**Comment by Helcostr** [comment]
To answer your 2nd issue, adding a space will mess with the `@` search. try doing `@ad_astra` (as there is an underscore in the mod identifier: everything before the colon `:`). See the images attached.

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/15018549/6fc8a59d-071c-4c57-9326-a8eb45c84a7b)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/15018549/57a65d72-f3ae-46a3-a28f-a5b9799875ad)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/15018549/8ebfc2bb-d691-4558-a449-eee7cdd0de50)

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

Keep an eye on our social media as we may have something unstable coming out soon.
