### ISSUE TITLE
error ocuring during launch

### ISSUE THREAD

**Issue by kizuru22** [FTBTeam/FTB-Modpack-Issues#4606]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.9.0

### Describe the bug

every time i try to launch the modpack it shows:

error: a JNI error has occured, please check your installation and try again

i tried that and still the same please help

### Steps to reproduce

launch the modpack

### Expected behaviour

to be able to play the modpack

**Comment by MichaelHillcox** [comment]
Please attach a log

**Comment by kizuru22** [comment]
how can i add a log after i made the issue?

**Comment by kizuru22** [comment]
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14075501/console.log)

**Comment by kizuru22** [comment]
> Please attach a log

i added the log now

**Comment by Gaz492** [comment]
Is this still an issue with the latest version of the app for you? If it is, would you be able to try a fresh install of the modpack and upload the logs again?

**Comment by kizuru22** [comment]
it works now

Den man. 10. jun. 2024 kl. 09.54 skrev Gareth Williams <
***@***.***>:
