### ISSUE TITLE
sb3 wont open

### ISSUE THREAD

**Issue by iiuliiaan** [FTBTeam/FTB-Modpack-Issues#4607]
### Modpack

FTB StoneBlock 3

### Modpack version

1.8.1

### Describe the bug

when i try to launch the modpack, its loading a bit then it crashes, yesterday I added optifine to it and it worked but now it doesn't 
:(

### Steps to reproduce

just try opening the modpack from the ftb app

### Expected behaviour

i expected the modpack to open

### Screenshots

[crash-2024-01-28_13.53.13-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14075909/crash-2024-01-28_13.53.13-client.txt)

**Comment by iiuliiaan** [comment]
and i did try to reinstall the modpack

**Comment by jlp1528** [comment]
DO NOT ADD OPTIFINE TO FORGE PACKS EVER. It literally deletes or overrides CRITICAL FORGE COMPONENTS. FTB packs already include other, better, less hacky performance enhancing mods. If you're still having performance issues, turn down your graphics.

**Comment by MichaelHillcox** [comment]
Don't use optifine
