### ISSUE TITLE
Loading (Modded?) Pillager Outpost Crashes Game/Server, Update NoMoWanderer From 1.6.3 to 1.6.4 Fixes This

### ISSUE THREAD

**Issue by guesstv** [FTBTeam/FTB-Modpack-Issues#4608]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Log Files

https://mclo.gs/fMCDNhM

### Describe the bug

When exploring on my server the server randomly crashed. I deduced the problem was consistently stemming from an unloaded pillager outpost. I'm unsure if this outpost is a modded structure. Either way, the crash log mentioned NoMoWanderer so I updated it from 1.6.3 to 1.6.4 and that has fixed the issue. I don't believe this occurred in previous versions of DW1.20 since my world has previously loaded pillager outposts before updating the pack. Or- this problematic structure contains something that I'm incapable of specifying. Attached screenshot shows structure in question AFTER the fix. Previously this would stay an unloaded 3x3 area of chunks. I was only able to determine this structure was the problem because I was able to load a portion of the fence.

### Steps to reproduce

1. Locate unloaded pillager outpost
2. Load
3. Crash 

### Expected behaviour

Structure should load normally.

### Screenshots

![Screenshot 2024-01-28 174047](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/156400797/d424338b-4cf0-4eae-b3c1-e16fde84f685)

**Comment by francWhite** [comment]
As @guesstv already obseverd the bug was fixed in NoMoWanderer 1.6.4 by @esvarc with issue [#21](https://github.com/J-Dill/NoMoWanderer/issues/21). An soon update of the modpack would be appreciated as the hard server crashes often lead to the loss of items.

**Comment by JustinMcCune** [comment]
Experiencing this issue as well in Direwolf20 mod pack for 1.20. Please add update to mod pack <3

**Comment by Jacoby6000** [comment]
Updating to NoMoWanderer 1.6.4 on the server fixes this issue. I did not need to update clients.
