### ISSUE TITLE
Custom tree leaves persistent true

### ISSUE THREAD

**Issue by KazzaKING** [FTBTeam/FTB-Modpack-Issues#4610]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.9.0

### Describe the bug

Leaves don't decay as they generate with the persistent true tag

### Steps to reproduce

Self explanatory (grown trees are fine)

### Expected behaviour

Leaves generate with persistent true

**Comment by DinnerBeef** [comment]
Sadly, this won't be able to be fixed due to how the world gen mod works.
