### ISSUE TITLE
Immersive Engineer's Workbench Game Crash

### ISSUE THREAD

**Issue by LalondeBrenton** [FTBTeam/FTB-Modpack-Issues#4616]
### Modpack

FTB Inferno

### Modpack version

1.10.0

### Log Files

[crash-2024-01-30_15.51.43-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14105560/crash-2024-01-30_15.51.43-client.txt)

### Describe the bug

Placing a blue print on the Engineer's Workbench cases the game to crash and makes the world unloadable

### Steps to reproduce

1 place workbech
2 add blueprint
3 CRASH

### Expected behaviour

craft parts

**Comment by LalondeBrenton** [comment]
Sorry this is for Inferno Not Genesis

**Comment by Gaz492** [comment]
Duplicate of #4514
