### ISSUE TITLE
Modpack Crashes Upon Initialization

### ISSUE THREAD

**Issue by wizney** [FTBTeam/FTB-Modpack-Issues#4617]
### Modpack

FTB University 1.19

### Modpack version

1.3.1

### Log Files

Removed log link

### Describe the bug

Crash when trying to load game, Unsure if modpack fully downloads.

### Steps to reproduce

Download latest version, hit play

### Expected behaviour

Game successfully loads

### Additional information

Im genuinely unsure if the download even fully completed. I've tried to reinstall the modpack multiple times, restarting my computer as well as trying to redownload the correct forge version to no avail.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff900150590, pid=9044, tid=6040
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [atio6axx.dll+0x190590]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by aaronhowser1** [comment]
This is a very strange issue. Can you see if copying the contents of the modpack folder to another launcher still crashes?

**Comment by Gaz492** [comment]
It looks like your graphics drivers may be out of date, the crash you are running into is commonly seen when your graphics drivers are out of date or if you are on a laptop with an integrated graphics and a dedicated graphics card, the modpack may be using the wrong graphics card.

To begin with, we recommend making sure that your graphics drivers are up-to-date by downloading the latest drivers from the manufacture's website.
