### ISSUE TITLE
Nickname/user account in your packs

### ISSUE THREAD

**Issue by 5ully** [FTBTeam/FTB-Modpack-Issues#4619]
### Modpack

FTB Skies

### Is your suggestion related to a problem? Please describe.

Im requesting that FTB removes my username from FTB Skies, FTB Skies Expert and FTB Stoneblock for any upcoming versions. In FTB skies and the expert version this would be my player skull on the anti block island. As for FTB Stoneblock this is the birthday in the code.

### Mod suggestion

n/a

**Comment by Saereth** [comment]
They removed your birthday stuff from sb3, not sure where your name is anywhere in skies or skies expert, pretty sure just your head on manmaed's island. Im afraid I cant do much about the head though, it was part of his artistic creative passion and far be it from me to infringe on an artists right of expression. I will however add 2 more of your heads to the new sakura grove next to a crying obsidian shrine. In recognition of your service!

**Comment by 5ully** [comment]
Well, response as excepted from the "amazing" dev.

**Comment by Saereth** [comment]
We'll take it under advisement! (Joking aside, we'll remove them, no eta as we have more pressing things to focus on but as we roll out updates for packs that have the birthday stuff we're just going to generally remove them all for everyone, probably best. As for the head, you've been replaced with manmaed in Expert mod, will mirror the change to normal version whenever I get around to the next update for it.

**Comment by 5ully** [comment]
Cool, thanks. Im not bothered enough to require it immediately. Just sneak it into the next version available :P
