### ISSUE TITLE
[Bug]: *URGENT* Minecraft Vulnerability

### ISSUE THREAD

**Issue by Tntdruid** [FTBTeam/FTB-Modpack-Issues#462]
### Modpack

FTB OceanBlock

### Modpack version

1.10.1

### Describe the bug

Forge is open to a new vulnerability https://twitter.com/Direwolf20/status/1469356597185028106

Why did FTB not update forge yet?

### Steps to reproduce

Start MC

### Expected behaviour

new vulnerability

**Comment by MichaelHillcox** [comment]
Thanks for the concern. We have already handled this and will slowly migrate our packs to the latest forge versions when we have time.

Please see the following for more details.
https://www.creeperhost.net/blog/mitigating-cve/

**Comment by Tntdruid** [comment]
Good :)
