### ISSUE TITLE
Intergration by Parts DX Linux Server fails to start up

### ISSUE THREAD

**Issue by Alex-tiygahealth** [FTBTeam/FTB-Modpack-Issues#4620]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.13.3

### Describe the bug

When installing the Integration by Parts server on a Linux Server machine an error prevents the server from launching correctly.

The first time I tried to run the server it was before the 1.13.3 update and it launched sucessfuly, however now neither 1.13.3 or 1.13.2 servers are working.

### Steps to reproduce

1. Install Ubuntu Server 
2. Access server via ssh 
3. Download and install server intaller for linux and grant execute permisions. 
4. Run installer 
5. Run start.sh

### Expected behaviour

Expected server to launch correctly

### Screenshots

<img width="1049" alt="Screenshot 2024-02-01 202616" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/135236021/8fe1ed32-5213-4eb2-8a9e-f5b27f7f50b0">

### Additional information

System is a Dell E10S - Intel Xeon E3-1231 v3 @ 3.40GHz with 8GB DDR3 RAM

**Comment by Gaz492** [comment]
Im not able to reproduce this issue, the error in the screenshot suggests an issue with java itself, could you try deleting the jre folder to see if that resolves the issue?
