### ISSUE TITLE
everytime when i am playing the game crashes

### ISSUE THREAD

**Issue by 7ossxD** [FTBTeam/FTB-Modpack-Issues#4622]
### Modpack

FTB Infinity Evolved 1.7

### Modpack version

3.1.0

### Log Files

[crash-2024-02-02_15.34.28-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14140921/crash-2024-02-02_15.34.28-client.txt)

### Describe the bug

when i am at my base the game suddenly stop and crashes

### Steps to reproduce

1.start the game 
2. playing 
3. stop suddenly and crashes

### Expected behaviour

tell me how to stop the game being crashed

**Comment by Gaz492** [comment]
It looks like the ender chest from ender storage is running into a rendering issue, I would suggest restoring a world backup if you can as this pack is unlikely to receive any bug fixes due to its age.
