### ISSUE TITLE
Game Crash when try to run

### ISSUE THREAD

**Issue by Banane52** [FTBTeam/FTB-Modpack-Issues#4623]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Log Files

https://gist.githubusercontent.com/FTBAuto/8353db24c352ee38a8b744e6ef25148b/raw/ed280429889acbd9b3ce43129985015e0afab023/instance.json

### Describe the bug

When i start any modpack it just says Error

### Steps to reproduce

I click play 
wait a couple sec like 30 or so 
then it says Error

### Expected behaviour

Start of the game

**Comment by SeaSmuS** [comment]
currently having the same issue

**Comment by Gaz492** [comment]
Would you be able to upload the latest.log and debug.log from the logs folder for us and if you have one a crash report from the crash-reports folder.
