### ISSUE TITLE
MAJOR BUG

### ISSUE THREAD

**Issue by immigrantGaming** [FTBTeam/FTB-Modpack-Issues#4626]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

FTB PRESENTS DIREWOLF20 1.20 RELEASE (1.12.1)

### Describe the bug

This appears to be an issue with the mod pack. 
I believe something in a village at these coordinates is causing the server to lock up -10555 119 -7635
I was able to reproduce this issue in single-player by creating a world with the same seed as your server.

We would recommend reporting this issue to FTB.
The steps to reproduce this issue are as follows, 
Create a world with this seed: 1957493381065788475

Teleport to the following coordinates: -10555 119 -7635
After teleporting, the server will immediately become unresponsive.

### Steps to reproduce

This appears to be an issue with the mod pack. 
I believe something in a village at these coordinates is causing the server to lock up -10555 119 -7635
I was able to reproduce this issue in single-player by creating a world with the same seed as your server.

We would recommend reporting this issue to FTB.
The steps to reproduce this issue are as follows, 
Create a world with this seed: 1957493381065788475

Teleport to the following coordinates: -10555 119 -7635
After teleporting, the server will immediately become unresponsive.

### Expected behaviour

server times out and doesnt work

**Comment by Tokrates** [comment]
Can confirm this issue, could be something with Forbidden and Arcanus? It stops half way generating one of the forts with evokers and stuff in my save (wild guess). Tested with multiple saves (same seed) coming up from different directions

Seed: -2237363556603177864
-> Fly for about 10-20sec to the east-east-south after spawning and the lockup happens.

**Comment by residentsummer** [comment]
I had the similar issue with this pack (version 1.11). Try removing "NoMoWanderer" mod. There was a consistent worldgen lockup on my save, after combing through the log I noticed something about this mod, removed it and issue had disappeared. After that I flew again in the same direction - there was an evoker fort with the wandering trader locked up in a cage.
