### ISSUE TITLE
Stoneblock 3 v1.9.0 missing Jade mod

### ISSUE THREAD

**Issue by Xayma** [FTBTeam/FTB-Modpack-Issues#4629]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Log Files

[2024-02-03-1.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14152398/2024-02-03-1.log)

![From Tristy @disc](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/32491966/01c87b44-a98b-4d2d-bc07-c6185a595dc9)

### Describe the bug

Stoneblock 3 v1.9.0
Server on local machine

JadeAddons complaning about missing dependency Jade 5.2.3
Can see in changelog" Update Jade-1.18.2-forge-5.3.0 to Jade-1.18.2-forge-5.3.1"
However when installing the server the Jade is not present making the server crash and not start up.
Meaning the server "installer" is not adding the Jade version required by JadeAddons even when stated in changelog have been updated.

Verified with Tirsty in discord that this is not only happening to me (see img attached)

_Manual fix is to add missing dependency (Jade-1.18.2-forge-5.3.1) to mod folder._

### Steps to reproduce

1. DL Stoneblock 3 v1.9.0
2. Install Stoneblock 3 v1.9.0
3. Start Stoneblock 3 v1.9.0
4. Get error in console or read in log file.

### Expected behaviour

Server should start normally without crashing and complaining about missing dependency

**Comment by Gaz492** [comment]
This issue should be resolved now.
