### ISSUE TITLE
can't light the spirit fire with "fire stick" 

### ISSUE THREAD

**Issue by GZxZxHX000** [FTBTeam/FTB-Modpack-Issues#4632]
### Modpack

FTB Arcanum Institute

### Modpack version

1.3.0

### Describe the bug

“fire stick”不能点燃灵火，而任务书只给了“fire stick”

### Steps to reproduce

i'm a chinese ,so i will write in chinese 
任务里叫我用 “fire stick”点起一堆灵火，但是“fire stick”并不能点燃灵火，而在我用创造模式试过后，发现能用打火石点燃，我认为这应该算是一个bug
mod：occultism

### Expected behaviour

它应当能点燃，这样任务才能继续

**Comment by Wulian233** [comment]
FTB team are english, so they will solve only engliah

**Comment by KajeTheCat** [comment]
This does not seem to be the case in my save, the targeting system to ensure lighting the "spirit fire" may be very specific, have you tried using F3+B so that you can target the demon fruit's hitbox to light it with the sticks?

在我的保存中似乎并非如此，确保点燃“灵火”的瞄准系统可能非常具体，您是否尝试过使用F3+B，以便您可以瞄准恶魔果实的命中框以用棍子点燃它？

**Comment by TheonlyTazz** [comment]
this is due to the fire sticks not actually being able to make spirit fire; i adjusted the AABB while checking for demon fruit to have a bit more leahway
