### ISSUE TITLE
Dublicating the mekanism tanks 

### ISSUE THREAD

**Issue by S1lvally** [FTBTeam/FTB-Modpack-Issues#4634]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

When right-clicking with Ultimate Fluid Tank from "Mekanism" on fluid drawer from "Functional Storage", Fluid tanks will be dublicated with everything included in them

### Steps to reproduce

 Open the game world. Take the tank and drawer. Fill the tank with any liquid. Update your drawer with upgrades. Place the drawer in the world and right click on the drawer  with the tank in main-hand. 

### Expected behaviour

Tanks should't be duplicated

**Comment by S1lvally** [comment]
and i'm sorry. I don't speak English. I wish, you understand all

**Comment by S1lvally** [comment]
upd: it works not only with tanks from mekanism. All items with liqud buffer will be dublicated!

**Comment by S1lvally** [comment]
buckets, tanks etc.

**Comment by UnRealDinnerbone** [comment]
Can't reproduce this issue. If this is still happening, please reopen this issue
