### ISSUE TITLE
blank screen when holding items

### ISSUE THREAD

**Issue by Thebigdravens** [FTBTeam/FTB-Modpack-Issues#4638]
### Modpack

FTB Infinity Evolved 1.7

### Modpack version

3.1.0

### Log Files

[fml-client-latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14200222/fml-client-latest.log)

### Describe the bug

any time an item goes into my current hotbar slot it makes the screen go blank, when i try to open inventory, it does the same.

### Steps to reproduce

all i did was download the modpack and open it up. this has been going on since downloading.

### Expected behaviour

screen goes dark and unable to see entities when not holding items either.

**Comment by Gaz492** [comment]
I would suggest making sure your graphics drivers are up-to-date as this sounds like a common issue that occurs with older graphics drivers.
If its still an issue after updating your graphics drivers, would you be able to take a screenshot of the issue?

Note:
This is an old modpack which we are no longer releasing updates for.
