### ISSUE TITLE
Searching 'pic' in JEI causes crash

### ISSUE THREAD

**Issue by light8593** [FTBTeam/FTB-Modpack-Issues#4641]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.13.3

### Describe the bug

Searching 'pick' in JEI causes the game to crash

### Steps to reproduce

1. Open JEI
2. Type 'pic' in search bar

### Expected behaviour

The results for pic to display

**Comment by light8593** [comment]
It also happens when attempting to search 'energy'

**Comment by pikminman13** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40

sorry for the late reply
