### ISSUE TITLE
Crashing when trying to open the modpack

### ISSUE THREAD

**Issue by UzumakiNoKurama** [FTBTeam/FTB-Modpack-Issues#4642]
### Modpack

FTB Inferno

### Modpack version

1.10.0

### Describe the bug

I keep trying to open the modpack but it crashes when it opens to the main menu area. [crash-2024-02-09_06.00.26-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14221549/crash-2024-02-09_06.00.26-client.txt)

### Steps to reproduce

click play on Inferno through FTB app.
Let it load

### Expected behaviour

Menu shows before crashing.

**Comment by Gaz492** [comment]
Have you made any modifications to the pack, it looks to be crashing while loading sounds?
Im not able to reproduce this issue, if you try installing the modpack again, does it allow you to start the pack up?
