### ISSUE TITLE
smeltery controller no showing 

### ISSUE THREAD

**Issue by 420blaze4231** [FTBTeam/FTB-Modpack-Issues#4643]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

smelter controller from tinkers construct missing recipe for crafting, the 1.8.1 update was working fine updated to 1.9 and the recipe stopped working 

### Steps to reproduce

download fresh install of 1.9 jei search  smeltery controller and try to access recipe  

### Expected behaviour

for the recipe to show up but no recipe is detected

**Comment by DJDrWright** [comment]
This issue still persists. Cannot craft smeltery controller. Thank you

**Comment by Gaz492** [comment]
It looks like the recipe still works (casting copper onto a seared stone block in a casting basin), just doesn't show the recipe.
I will pass this on to our devs.
