### ISSUE TITLE
Lag caused by sound? 

### ISSUE THREAD

**Issue by lihaiww** [FTBTeam/FTB-Modpack-Issues#4644]
### Modpack

FTB Sky Odyssey

### Modpack version

1.4.2

### Describe the bug

The game will freeze for a few seconds, then runs smoothly. 
Analysis on the bottom right says sound suddenly use a lot of resources for no reason.
![PixPin_2024-02-13_16-47-58](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/122516140/56767e66-0e85-4800-8f20-e59beeb398dc)
no lag
![PixPin_2024-02-13_16-48-53](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/122516140/e3ba0a9a-d8a6-48a6-bb4d-48f4b544d857)
FREEZING
FPS is not limited. Total mem is 6.5g.
Same issue when the sound set to 0.

### Steps to reproduce

A new save and a few minutes of playing.

### Expected behaviour

A freeze like game stopped running, and back to normal.

**Comment by Gaz492** [comment]
Does this happen as soon as you start playing the modpack or only after playing for a while?

**Comment by lihaiww** [comment]
As soon as I start playing

**Comment by lihaiww** [comment]
Optifine is added only because I want to know the reason for that lag, so no it wont get any better.

**Comment by Gaz492** [comment]
Ok, if you go to options > BetterFPS options, could you try changing the algorithm option in there to `Vanilla Algorithm`?

May I also ask what launcher you are using to start the modpack with? I noticed that the Java version shown in your screenshot doesn't match the one that we ship with the modpack (Java 8 update 302, at the bottom of the last page here https://adoptium.net/temurin/archive/?version=8), so I'm wondering if that's possibly causing an issue.
