### ISSUE TITLE
Ftb server

### ISSUE THREAD

**Issue by Regentorius** [FTBTeam/FTB-Modpack-Issues#4646]
### Modpack

FTB One

### Modpack version

2.8.3

### Describe the bug

In console i started server and nothing happend

### Steps to reproduce

In console i started server and nothing happend

### Expected behaviour

Start server

### Additional information

Hi, I'm having trouble turning on the server on the FTB One modpack. I don't have a problem with another modpack. It starts to load and then it freezes and nothing. Is there anything I can do to fix it? Thank you.

**Comment by Gaz492** [comment]
Would you be able to upload the latest.log and debug.log from the server so we can take a look?
