### ISSUE TITLE
FTB Genesis crash caused by IC2 crops

### ISSUE THREAD

**Issue by IntrACate** [FTBTeam/FTB-Modpack-Issues#4647]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Log Files

https://pastebin.com/HHhSHc5N

### Describe the bug

My game crashes seemingly at random when I am doing various tasks throughout the Seed Vault base. Since the crash report seems to indicate some issues with IC2 crops, I can elaborate on my crop setup.

I am working in the Enhanced Farm simulation. The crashes seemed to start when I was attempting to grow Terra Wart, breeding some Nether Wart. I am breeding Nether Wart in both the dark room and one of the farm plots. I have some snow under some of the plots but not all.

The crash does not seem to be connected to placing blocks or interacting with objects.

### Steps to reproduce

1. Go to the Enhanced Farm Simulation.
2. Breed Nether Wart in the dark room and in another crop plot.
3. Put snow blocks under some of the crops.

### Expected behaviour

No crash

**Comment by IntrACate** [comment]
Update:
I managed to grow some crops of Terrawart. I let them fully grow and left them like that for quite some time to see if the game was stable. I had no crashes. As soon as I harvested the Terrawart, the game crashed. I have snow blocks directly under the farmland and then 3 Soul Sand underneath.

**Comment by TobyD** [comment]
Same problem. Running genesis 1.4.0. Planted two netherwarts on crop stick with double crop stick in the middle. Terrawart mutates in the middle slot and grows, but shorty after harvesting it, the game crashes.

**Comment by ArtpokeBr** [comment]
Please, if this issue still persists in the next update, reopen this issue or open a new one.
