### ISSUE TITLE
[Bug]: Crafted Capacitatoes are not accepted by the Singularity Compressor after rejoining the world

### ISSUE THREAD

**Issue by DasBrain** [FTBTeam/FTB-Modpack-Issues#465]
### Modpack

FTB Oceanblock

### Modpack version

1.9.0

### Describe the bug

When setting up autocrafting for the capacitato it stops working after you leave and join the single-player world.

### Steps to reproduce

* Setup Capacito auto-crafting using an RFTools crafter.
* Export the Capacitatoes into a Singularity Compressor
* Restart the game
* New Capacitatoes are no longer accepted

### Expected behaviour

No capacitato singularity needed?

### Screenshots

![2021-12-11_20 59 19](https://user-images.githubusercontent.com/652983/145690191-a91eecf2-5127-4289-b808-355d8d419cc0.png)

### Additional information

The used device is a RFTools crafter.

After some investigation, it appears that the RFTools crafter will not create the Capacitato with an empty tag.

**Comment by Pkrakmo** [comment]
This also happens when using Mekanisms Formulaic Assemblicator, it worked fine yesterday, but when I started up my singleplayer world the Quantum compressor will not accept Capacitatoes

**Comment by Sunekaer** [comment]
https://github.com/BlakeBr0/ExtendedCrafting/issues/145
