### ISSUE TITLE
FTB Skies Expert - Island not spawning

### ISSUE THREAD

**Issue by Lamilams** [FTBTeam/FTB-Modpack-Issues#4650]
### Modpack

Other...

### Modpack version

1.0.0

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14312944/console.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14312945/latest.log)

### Describe the bug

The island doesn't spawn when entering the world
I waited several minutes in creative mode hovering a few blocks above the teleport point with /ftbdim home

Tested seeds:
(Seed is 1172256153830652454) - Island failed to spawn (Tested this seed 3 times)
(Seed is -1819656986958195476) - Island spawns (Tested this seed twice)

### Steps to reproduce

Create a world with default settings with the seed "1172256153830652454" (Remove quotes)
After entering the portal I selected the topmost island, FTB Sky Island.
I then get teleported to the island location but the island isn't there.
Use /ftbdim home to confirm you are in the right place.

### Expected behaviour

The island should spawn.

**Comment by Lamilams** [comment]
That would explain it if it was consistent, but then please explain why it worked on one seed but not on another with no client restart. I tested the working seed, then created a new world with the bad seed immediately after without restarting the client, and the island once again failed to generate.

**Comment by Saereth** [comment]
We are looking into this more I was able to replicate your issue with that seed. A different/random seed should let you at least get going until we get a fix out for it, ty for the info!

**Comment by Lamilams** [comment]
Happy to help :)

**Comment by Saereth** [comment]
We have a solution for this that will go into todays update
