### ISSUE TITLE
no dirt

### ISSUE THREAD

**Issue by emilrasmussen1302** [FTBTeam/FTB-Modpack-Issues#4652]
### Modpack

Other...

### Is your suggestion related to a problem? Please describe.

ftb skies expert

no dirt on compact sky island
![Skærmbillede 2024-02-16 171202](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/126979173/ef28cd93-5da7-4fea-90da-6a0f64c52b2c)

**Comment by Soldierdarkops** [comment]
Same issue. I thought maybe it was in the quest book but have yet to find anything.
