### ISSUE TITLE
Crafting Station Crash

### ISSUE THREAD

**Issue by gobzil** [FTBTeam/FTB-Modpack-Issues#4657]
### Modpack

FTB Skies Expert

### Modpack version

1.0.1

### Log Files

[crash-2024-02-16_17.55.37-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14317030/crash-2024-02-16_17.55.37-client.txt)

### Describe the bug

when opening the crafting station with Hexerei Alter next to it games crashes

### Steps to reproduce

place alter next to crafting station w/ chest next to it, click to open crafting station, games crashes

### Expected behaviour

game closes

**Comment by Saereth** [comment]
These are blacklisted on our end but the mod seems to be ignore its own blacklist so I've opened an issue with the dev, thanks for the report, we'll get a fix in once we hear back from the dev

**Comment by Saereth** [comment]
https://github.com/Tfarcenim/crafting-station/issues/96
