### ISSUE TITLE
Spirit deployer not working 

### ISSUE THREAD

**Issue by ydnar2000** [FTBTeam/FTB-Modpack-Issues#4659]
### Modpack

FTB Skies Expert

### Modpack version

1.0.0

### Describe the bug

after getting the quest reward the spirit deployer to expand the alter from spirit. The item doesn't work and nothing is showing up, after right clicking, left clicking and both shift clicking. Even though the item description tells you to do so. 

### Steps to reproduce

1 complete the quest "soul engulfing concentrator" 
2 claim reward "spirit deployer"
3 structure not placing and item not working

### Expected behaviour

that the item works, places the multiblock

**Comment by Saereth** [comment]
we removed this spirit deployer and switched it to schematic cannon in v1.0.2, you'll need to update
