### ISSUE TITLE
cannot disable goat event

### ISSUE THREAD

**Issue by LWmods** [FTBTeam/FTB-Modpack-Issues#4669]
### Modpack

FTB Skies Expert

### Modpack version

1.0.2

### Describe the bug

as the title says i cannot disable the goat event. i have looked at one, killed one and been hit by one none of which have unlocked the ability to disable the event.

### Steps to reproduce

wait for a goat to spawn look/kill/be hit by it then try to disable the event

### Expected behaviour

be able to disable it after encountering one 

### Screenshots

![goat](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/46599167/586d4be2-ec69-4257-8396-11dfa7fe937f)
![goatevent](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/46599167/3ca3a2ca-b908-4b24-ae18-790ab196d225)

**Comment by Saereth** [comment]
this should be fixed now
