### ISSUE TITLE
[Bug]: Thermal Series sapphire dust no recipe

### ISSUE THREAD

**Issue by set92** [FTBTeam/FTB-Modpack-Issues#467]
### Modpack

FTB Oceanblock

### Modpack version

1.10.1

### Describe the bug

I can get the sapphire ore from laser drilling, I turned it into sapphire dust with the washing machine, but I can't do anything with sapphire dust. I also saw that happens with ruby.

### Steps to reproduce

Put sapphire ore into washing machine, then fermentation station and fluid sieving machine to finish.

### Expected behaviour

Be able to use the sapphire dust to create gems or something,

**Comment by Sunekaer** [comment]
Thermal adds ruby and sapphire dust but there is no use for them.
Ill add a furnace recipe for turning them back in to gems
