### ISSUE TITLE
it is possible the airship can catch fire when struck with lightning. minor

### ISSUE THREAD

**Issue by AWDoBaun** [FTBTeam/FTB-Modpack-Issues#4670]
### Modpack

FTB Skies Expert

### Modpack version

1.0.2

### Describe the bug

I was exploring the airship in creative to fly around and get a good look at it. A thunder storm broke out, lightning struck one of the wooden sections on the top of the "balloon". The fire spread and many ash piles from supplementaries were formed.

### Steps to reproduce

command /weather thunder
and or /summon lightning

### Expected behaviour

The airship should be completely immutable.

### Screenshots

![2024-02-17_16 43 38](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/12954977/08c337b7-b27b-4bbc-a4a5-34bad8d2cfa6)

**Comment by Saereth** [comment]
uhhh... lol ok I'll have to see what we can do about that
