### ISSUE TITLE
Issues with One Large Tick Delay (5-10 Minutes) Every 15 Minutes

### ISSUE THREAD

**Issue by Whyareuhere** [FTBTeam/FTB-Modpack-Issues#4671]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14320555/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14320557/debug.log)

### Describe the bug

In single player world, some sort of error in a tick happens ever 5-10 minutes. You can see that it is stuck saying "Waiting for server..." while processing this error, which stops all other ticks from processing. You can still move around, but cannot access anything (inventory or otherwise). The shaders during this time somehow make everything seem darker during this period. After 15 minutes the error is resolved and gameplay can continue as normal. Please note that any shader issues here are resolved when the game properly starts up again.

This was only starting today, of which I have done a few things:

- Made unbreakable flight charm, and unbreakable other charms
- started up Ender simulation in simulation chamber

More specifically, this new simulation chamber is where these issues start, And I can save my game afterwards with no problem.

### Steps to reproduce

Suspected way of triggering issue:

- Get team reward for Ender simulation
- Have charms (ex: flight) with the unbreakable infusion enchantment

### Expected behaviour

Lack of issues with ticks in world

### Additional information

If you want, I can upload the world to the FTB Discord server for people to analyze. Willing to cooperate with other things to help resolve this!

**Comment by Whyareuhere** [comment]
Ok, I think I found out that it is the unbreakable flight charm. Turned it off, haven't gotten any of the issues described above!

**Comment by Whyareuhere** [comment]
Unfortunately it seems that I found more to this issue: I had a mob farm which was spawning a lot of mobs, culling them seems to have helped with delaying the "waiting for server" issue. However, that doesn't seem to fully resolve the issue; it now shows up every 10-15 minutes, and this error of waiting does seem to resolve itself quicker.

**Comment by ArtpokeBr** [comment]
Please, if this issue still persists in the next pack update, reopen this issue or open a new one.
