### ISSUE TITLE
Missing recipes in Stoneblock 3

### ISSUE THREAD

**Issue by DJDrWright** [FTBTeam/FTB-Modpack-Issues#4674]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

smeltery controller from tinkers construct missing recipe for crafting, cobblegen tier 2 missing recipe for crafting

### Steps to reproduce

download fresh install of 1.9 jei search smeltery controller or cobblegen tier 2 and try to access recipe

### Expected behaviour

for the recipe to show up but no recipe is detected

**Comment by PyaniGnom** [comment]
I have the same problem. I just replaced the REI Plugin Compatibility and Roughly Enough Items (REI) from version 1.8.1 of StoneBlock and the problem was solved

**Comment by DJDrWright** [comment]
> I have the same problem. I just replaced the REI Plugin Compatibility and Roughly Enough Items (REI) from version 1.8.1 of StoneBlock and the problem was solved

Thank you! This worked a treat.

**Comment by OZoneGuy** [comment]
For anyone else finding this, these are the relevant changelogs:
> Update REIPluginCompatibilities-forge-8.0.65 to REIPluginCompatibilities-forge-8.0.89
Update RoughlyEnoughItems-8.3.642 to RoughlyEnoughItems-8.3.681-forge

I tried downgrading to the older versions, but my game keeps crashing when I try to open my inventory, or any action that opens REI.

What versions did you guys use?

**Comment by UnRealDinnerbone** [comment]
Same as #4804
