### ISSUE TITLE
FTB Skies: Expert - Unintended Easy Planks - Tropicraft Mahogany

### ISSUE THREAD

**Issue by 2ndRecon** [FTBTeam/FTB-Modpack-Issues#4676]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Describe the bug

While most logs-->Stripped log--->Plank recipes require the saw or axe; the Tropicraft Mahogany can be crafted down from Logs
to [4] Planks in the 2x2 grid.

I don't believe this in intentional. (but it's a welcome oversight ha ha)

### Steps to reproduce

Get a Mahogany Sapling from the Market
Grow it
Chop it down
Slap those logs in your 2x2 and break them down into 4 planks.
Profit

### Expected behaviour

I'm guessing you probably want these to require the same steps as all other logs.

**Comment by stearnsbq** [comment]
I mean archwood also gives you log -> 4 planks

**Comment by 2ndRecon** [comment]
> I mean archwood also gives you log -> 4 planks

Understood; i was just calling out one example. Seems like if they were going to make planks tedious to get in an expert pack, they wouldn't leave other mods Logs so easily crafted. It's probably an item tagging issue.

**Comment by Saereth** [comment]
archwood we did intend to leave as is since it requires quite a bit of progression to get to, the tropicraft woods do need fixing

**Comment by Saereth** [comment]
After reviewing this we're gonna leave the magic wood variants the ones you get via trading like mahogony as more direct crafting routes you can migrate too as you progress a bit, ultimately you'll get better yield on all of them by processing at that point anway. 

Also helping the decision, there is no stripped variants of those so we'd need to add for each and the pay off isnt really there for this
