### ISSUE TITLE
FTB Skies: Expert | Tetra Tool Variants / Tetra Modified Tools unable to be used in crafting recipes. Tetra Stone hammer does not act like hammer on stone / cobble / gravel blocks

### ISSUE THREAD

**Issue by 2ndRecon** [FTBTeam/FTB-Modpack-Issues#4677]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Describe the bug

When converting vanilla tools such as stone pick, axe or hammer into the Tetra variant
via the Tetra workbench, the tool is no longer able to be used in crafting recipes; such as using an 
axe to craft stripped logs into planks.

Also, when upgrading the Stone hammer in the Tetra workbench; Once 'Tetra'ized' it can no longer mine Cobble into Gravel etc.

In fact, the Tetra'ized Stone Hammer cannot mine the block at all.

### Steps to reproduce

Make a vanilla stone axe
Strip some logs manually
Harvest those logs with the axe.
Attempt to craft logs + axe in the 2x2
-note the stripped logs craft into planks, with the axe.

Now, place the Axe in the tetra table. 
Upgrade it in some way such as the handle, or the axe head.
Now remove the upgraded Tetra Axe
Attempt to craft some stripped logs into planks.
Note that it no longer works once the tool is 'tetra'.

Same with the Stone Hammer.
Make a Stone Hammer (the FTBSKYBLOCKADDONS variant)
Bust a cobblestone
Note it turns into gravel
Now: Place the stone hammer into the tetra table
upgrade it in some way
remove it
Attempt to bust a cobble
Note you can no longer bust anything with this hammer.

### Expected behaviour

I strongly feel since you put Tetra in the game we should be able to upgrade and repair our hammers with Tetra. However, doing anything to a tool turns it into a 'tetra' tool, which breaks it's use for Mining or in crafting recipes. 

### Screenshots

![Tetra-Axe-No-Worky](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/39180607/906e79ba-f5ef-44e5-a617-d7dc5f3e26e1)
![Vanilla_Axe_Works_Fine](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/39180607/e0235afe-e9e9-468f-9020-277ccf021c72)
![Tetra-Hammer-No-Worky](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/39180607/40bdb408-a5b7-4515-adeb-f20c20929642)

### Additional information

I appreciate that you may not want players to be able to mod / upgrade the Hammers outside of the Tetra playloop but having two discrete Hammer types is kind of a pain. 
In this case, I can use hammers from Tetra for anything 'except' mining down blocks into different materials.

As for the Axe situation, I think you should consider looking at the tags and making sure the Tetra*.*Axe is Alias'd / Tagged as any old Axe. It's very helpful for leveling Tetra to be able to use Tools in many ways such as player held, in crafting grid, as a weapon, etc.

Thank you,

**Comment by mickelus** [comment]
I think I have an ingredient somewhere that you could use to allow the tetra items to be used, not sure who works on this pack but send me a dm and I can help out!

**Comment by Saereth** [comment]
@mickelus sure that sounds great, you can dm me on discord username saereth

**Comment by Saereth** [comment]
didnt hear back on this and doing it for all recipes is a bit more work than I'm willing to invest for this functionality unfortunately
