### ISSUE TITLE
FTB launcher crasht wenn ich das Mod pack öffne.

### ISSUE THREAD

**Issue by Shiroxkurox** [FTBTeam/FTB-Modpack-Issues#4681]
### Modpack

FTB Unstable 1.20: Forge

### Modpack version

1.5.0

### Describe the bug

Wenn ich den FTB launcher öffne und unstable. 1.20 forge öffne, kommt nicht wie gewohnt die Menu leiste zu meiner Welt sondern er crasht und zeigt ein Menü an in dem steht das das spiel nicht geöffnet werden kann und es sechs mod Fehler gibt. folgende mods können nicht geladen werden: universal grid, supplementaries, iron Furnaces, cyclic, roots classic und mining gagets. Darauf hin kann nich mir zur den fehlerbericht anschauen. mehrfaches neustarten den launchers und Pc´s habe ich probiert, brachte aber nichts. Folgendes Problem entstand heute 18.02.2024 zum ersten mal.

### Steps to reproduce

1. FTB launcher öfnnen.
2. unstable 1.2. forge öffnen.
3. Bildschirm lädt
4. unstable crashed
5. menü mit fehlermeldung öffnet sich.

### Expected behaviour

ich erhoffe mir hilfe bei der Problemlösung um meine Welt Öffnen zu können ohne Fehlermeldung

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can take a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
