### ISSUE TITLE
upgrading sophisticated backpacks voids items

### ISSUE THREAD

**Issue by pikminman13** [FTBTeam/FTB-Modpack-Issues#4683]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Describe the bug

title

fix likely by making sure the right crafting method is used

### Steps to reproduce

craft backpack with inventory and upgrade it to iron tier

### Expected behaviour

no voiding

**Comment by 2ndRecon** [comment]
Just posting here to affirm / confirm this behavior..

While I generally empty the pack as a precaution; this time I did not out of hubris and I found it voided all items.
