### ISSUE TITLE
12 errors when starting modpack

### ISSUE THREAD

**Issue by Slimequicksilver** [FTBTeam/FTB-Modpack-Issues#4686]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.13.0

### Describe the bug

It shows that there is a problem in all textures with the uppercase letter `D`

### Steps to reproduce

I simply just downloaded the modpack for the first time and started

### Expected behaviour

I hope they can fix it

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/103580792/6430242a-20d4-4209-9062-d14ac2344f7c)

**Comment by Gaz492** [comment]
This issue should be fixed in the latest version of the pack
