### ISSUE TITLE
[Suggestion]: Add CC: Tweaked

### ISSUE THREAD

**Issue by privateryann1** [FTBTeam/FTB-Modpack-Issues#469]
### Modpack

FTB OceanBlock

### Mod suggestion

Link to mod: https://www.curseforge.com/minecraft/mc-mods/cc-tweaked

Adding this mod with further benefit the tech side of this pack. The possibilities are endless here. My particular reasoning for wanting this added is so I can pull data from my Mekanism power generation and display it on screens with fancy graphs and charts.

**Comment by Raidobw2** [comment]
Hello, thanks for the suggestion, however this has already been suggested in #205 and won't be added to the modpack.
