### ISSUE TITLE
Soul Crystal burning up

### ISSUE THREAD

**Issue by LilMxPlagueRat** [FTBTeam/FTB-Modpack-Issues#4690]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Log Files

N/A

### Describe the bug

When attempting to create the Soul Crystal the Crude Soul Crystal burns up before the Soul Crystal can be created. I have tried both letting the process through without picking up the Soul Crystal up at any stage and also with picking it up and tossing the product back into the soul fire.

### Steps to reproduce

1. Throw Apatite into the soul fire with multiblock shown in the Soul Engulfing Concentrator quest.
2. Receive a Soul Crystal Shard.
3. Throw Soul Crystal Shard into the soul fire with multiblock shown in the Soul Engulfing Concentrator quest.
4. Receive a Crude Soul Crystal
5. Throw Crude Soul Crystal into the soul fire with multiblock shown in the Soul Engulfing Concentrator quest.
6. The expected particle effects appear momentarily before the Crude Soul Crystal is destroyed.

### Expected behaviour

The Crude Soul Crystal to transform into a Soul Crystal

### Screenshots

![2024-02-18_19 56 43](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/23294423/c2c52b9a-7f85-4c94-9529-c3cd3e8e99cf)

**Comment by 2ndRecon** [comment]
Same, observed this many times. Frustrating, resorted to giving the item to players.

However, when getting past this to the 'spawn blaze' portion, the blaze doesn't spawn even with all the correct items on pedestals and the chicken soul in the center. Right Clicking with open hand has no effect at all.

**Comment by bradminky** [comment]
Completed tier 3 shrine in SP and MP. SP was able to obtain the Soul Crystal. MP the Soul Crystal just burns up and vanishes. This is really game breaking.

**Comment by Saereth** [comment]
Just tested this in SP and MP and both worked, you have to be very careful that the structure is right or the items are consumed. The mutliblock in the image for example, the pillars are too far apart. Recommend using the schematic cannon to build it. 
![2024-02-19_21 06 32](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/7c36c480-1f0d-4426-b221-ae2e4bd82005)

**Comment by LilMxPlagueRat** [comment]
> Just tested this in SP and MP and both worked, you have to be very careful that the structure is right or the items are consumed. The mutliblock in the image for example, the pillars are too far apart. Recommend using the schematic cannon to build it. ![2024-02-19_21 06 32](https://private-user-images.githubusercontent.com/9200909/306140610-7c36c480-1f0d-4426-b221-ae2e4bd82005.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDU5MjQsIm5iZiI6MTcwODQwNTYyNCwicGF0aCI6Ii85MjAwOTA5LzMwNjE0MDYxMC03YzM2YzQ4MC0xZjBkLTQ0MjYtYjIyMS1hZTJlNGJkODIwMDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMDUwNzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODJiNmE4MTliMTZkNzFmN2VlNjlhN2UxODJhNmU0NTE5YjQ5OTk2Yjk3OGQxMjdhOWRiNzgyNjg5NzlmMzMwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bjrdCL-id6ZEz4i6U7KrQIJMx_XKJLhlGQLogbF8f1Y)

I rebuilt it using the schematic cannon and it still doesn't work
