### ISSUE TITLE
[FTB Skies Expert] Super Cooler 9000 Broken - Consumes all stored power, produces no result

### ISSUE THREAD

**Issue by 2ndRecon** [FTBTeam/FTB-Modpack-Issues#4691]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Describe the bug

When attempting to craft for instance 'Experience Confection' in the Super Cooler, it consumes ALL stored power
and doesn't produce an output. 

It will not continue to progress the recipe; it just fails the recipe craft and restarts (now with no power).

Continuing to supply incremental power will not advance the recipe / craft.

Additionally it doesn't appear the Cyclic Claystone Batteries can supply power to this block even when fully charged by the peat generator. Fortunately, placing the block against the peat generator seems to work.

### Steps to reproduce

You need the following. 
- RF/FE power source w/ appropriate fuel for generating at least 100k FE/RF
- Super Cooler 
-  [3] sugar
- [1] Bucket of Cognitium.

===steps to reproduce===
1.) Place the power source down and place the "Super Cooler" against the power source 
     and allow it to fill it's reserves to max (100k FE)
2.) Right click the "Super Cooler' with the bucket of Cognitium, to load it into internal fluid tank.
3.) Place 1-Sugar into each of the (3) crafting slots.
4.) Observe as the stored FE rapidly depletes toward zero without completing the craft.
--Note in the JEI the recipe dictates it requires 2k FE to complete this recipe. 
5.) Further observe as the power attempts to replenish from the adjacent power supply block; but the craft
does not increment nor complete.

====
Additionally
====
Placing a Cyclic 'Claystone Battery' adjacent to the "Super Cooler' has no effect. e.g. it doesn't supply any supplemental RF/FE power. In fact, the Claystone Batteries in general appear to be 'input only' with no way to configure them for output.

![Skies_Exp_Confection_Issue](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/39180607/b7dc52be-6be5-4da2-9d29-c5eeb47e1af0)
![skies_sc9k_issue](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/39180607/af0eb3a6-7d62-4755-942c-85c122fa9b46)

### Expected behaviour

The craft should complete after consuming 2k FE/RF 'or' the craft should continue to increment to completion as additional power is provided to the block / machine.

### Screenshots

![Skies_Exp_Confection_Issue](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/39180607/ca6b0d5d-bcac-4702-8eeb-d8286d6e432a)
![skies_sc9k_issue](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/39180607/aff73a28-1f3c-405f-b493-7ca16f811562)

**Comment by Saereth** [comment]
This is not a bug, the recipe says 2000Fe/t, it requires 160k power total. The internal buffer only holds 100k so unless you can actively supply the 2k rf/t the recipe will not progress. If you have enough power though it does work. I am gonna recommend Mikey and desh increase the internal buff to 1M rf instead of 100k, should help with this

**Comment by Saereth** [comment]
<img width="461" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/d4000542-e3e3-4ca8-b244-7cacb7b28fb6">

**Comment by 2ndRecon** [comment]
Thanks , I guess I'm not an expert :) any word on what's up with the cyclic batteries you receive from the power generation Task reward ? They don't seem to output.
