### ISSUE TITLE
Loot Bee Issues

### ISSUE THREAD

**Issue by Aipoc76** [FTBTeam/FTB-Modpack-Issues#4694]
### Modpack

FTB Skies Expert

### Modpack version

1.0.2

### Describe the bug

Loot bee drops loot and it flies off the island instantly making it unable to collect.  The loot goes off, not the bee.  Like it repelled by reverse magnetism ...

### Steps to reproduce

let loot bee spawn and watch

### Expected behaviour

loot to hit ground and not move.

**Comment by Saereth** [comment]
This is not a bug its intended. the bee gives you a debuff called stinky that lasts for  a few seconds and makes all of your items run away from you. You can get around this by not looking at the items and backing into them... or several other methods but we leave that up to you.
