### ISSUE TITLE
Server crashes caused by sound error from Queen Bee / Botania

### ISSUE THREAD

**Issue by Alistair1231** [FTBTeam/FTB-Modpack-Issues#4695]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Log Files

https://pste.ch/elosozufen.pl
https://pste.ch/axoyakuxer.pl
https://pste.ch/uwelohixuz.pl
https://pste.ch/cequpacuva.pl
https://pste.ch/oqiduseriq.pl
https://pste.ch/qozumoloho.pl

### Describe the bug

While playing, the game randomly closes. The log seems to indicate this is related to Queen Bee and/or Botania

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-02-19 18:58:45
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.sounds.SoundInstance.m_7778_()" because "this.tmpSound" is null
	at net.minecraft.client.sounds.SoundEngine.modify$bdo000$bergamuateAttenuate(SoundEngine.java:1126) 
```

```
-- Head --
Thread: Server thread
Suspected Mods: 
	Botania (botania), Version: 1.19.2-440-FORGE
		Issue tracker URL: https://github.com/Vazkii/Botania/issues
		Mixin class: vazkii.botania.mixin.client.SoundEngineMixin
		Target: net.minecraft.client.sounds.SoundEngine
		at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.sounds.SoundEngine.modify$bdo000$bergamuateAttenuate(SoundEngine.java:1126)

	Queen Bee (queen_bee), Version: 3.0.3-1.19.2
		Issue tracker URL: https://github.com/CerbonXD/QueenBeeMod/issues
		at TRANSFORMER/queen_bee@3.0.3-1.19.2/com.cerbon.queen_bee.entity.custom.QueenBeeEntity.m_7515_(QueenBeeEntity.java:244)
Stacktrace:
	at net.minecraft.client.sounds.SoundEngine.modify$bdo000$bergamuateAttenuate(SoundEngine.java:1126)
```

### Steps to reproduce

1. Play game

### Expected behaviour

No crashes

**Comment by Saereth** [comment]
try removing super sound muffler and see if you can get this to happen again

**Comment by Alistair1231** [comment]
> try removing super sound muffler and see if you can get this to happen again

I only see `extremesoundmuffler-3.39-forge-1.19.2.jar` I assume you mean that? I will try it know and will report back. 
I played in the same wolrd on a local server yesterday without any issues btw. I don't know if I was simply lucky or if that is somehow related.
I will try playing locally without `extremesoundmuffler-3.39-forge-1.19.2.jar` now

**Comment by Alistair1231** [comment]
That seems to have fixed it. In the last few hours I didn't crash. 👍

**Comment by Alistair1231** [comment]
I crashed again. Though I had a good run. It took 3+ hours this time
https://pste.ch/leriniyipu.pl

**Comment by Alistair1231** [comment]
The crash intervals seem very random today it crashes more than recently, since disabling the sound muffler mod
https://pste.ch/uwaginitus.pl
https://pste.ch/werawabogo.pl

**Comment by Saereth** [comment]
ok since this all seem to indicate the queen be issue we've disable it from generating in worldgen and will implement an alternate event for spawning her
