### ISSUE TITLE
Quest items uncraftable/not available

### ISSUE THREAD

**Issue by itsmetheonlyben** [FTBTeam/FTB-Modpack-Issues#4696]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Describe the bug

Certain quests require items that are currently removed or not craftable in the expert mode of this modpack. E.g. The "Motor" quest in the Create questline, and the "Gas-Burning Generator" quest in the Mekanism questline.

### Steps to reproduce

1. Open Questbook
2. Go to Mekanism quest page
3. Click the "Gas-burning Generator" quest
4. Press "r" on the Gas-burning generator or search the item in JEI

### Expected behaviour

These quests should either not require these items if they are intentionally not included, or these items should have an appropriate expert mode recipe

**Comment by Saereth** [comment]
both of those are fixed in the next update

**Comment by Rukiuss** [comment]
Hey, I dont know if you got all, but the same goes for the Elemental Displacment Quest in Elementalcraft.
