### ISSUE TITLE
[FTB Skies Expert] Menril Resin Slowmelter recipie

### ISSUE THREAD

**Issue by Samtino** [FTBTeam/FTB-Modpack-Issues#4698]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Describe the bug

Menril resin from Crystalized Menril recipe appears to be incorrect in the SlowMelter 9000. 

### Steps to reproduce

1. Put 1 crystalized menril in slowmelter
2. Get 200mb of menril resin
3. Put 2 side by side crystalized menril 
4. Get 200mb of menril resin (at double the cost of resin and RF)

### Expected behaviour

2 menril chunks should equal 400mb

### Screenshots

![image_2024-02-19_165328686](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/35015007/f4a4fdc1-5c11-43a4-adfe-5f0d7923c712)
![image_2024-02-19_165339654](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/35015007/e3029038-8008-421d-a1cf-f7a48ee72de5)

**Comment by Saereth** [comment]
@MichaelHillcox Mikkkkeeeey
