### ISSUE TITLE
Compact Machines Spawn Point

### ISSUE THREAD

**Issue by drrk** [FTBTeam/FTB-Modpack-Issues#4699]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Describe the bug

When you die you are spawned outside the compact machine, without any items, so you need to use the emergency items to get back into the machine.  You are given a soulbound enchanted book, but cannot create an anvil until you have access to iron ingots, which is a little way down the quest line.  You cannot set your spawn point with a bed as it explodes inside the compact machine.

### Steps to reproduce

Use compact machine world, die.

### Expected behaviour

You should respawn inside the compact machine on death.

**Comment by Saereth** [comment]
You wanna use /sethome to set your home inside the compact machine, there is a quest in the first chapter that explains using sethome

**Comment by drrk** [comment]
Thanks for the information.  I should note though, there is not a quest that tells you about using sethome, only about using ftbdim home, which takes you to the same place as respawning after death.
