### ISSUE TITLE
[Bug]: Lava crystal in a Heat Generator crash's server/client

### ISSUE THREAD

**Issue by reficulagi** [FTBTeam/FTB-Modpack-Issues#470]
### Modpack

FTB University 1.16

### Modpack version

1.3.0

### Log Files

https://pastebin.com/TMGAsP3d

### Describe the bug

Game crashes when placing a lava crystal into a Heat Generator from mekanism

### Steps to reproduce

Bind a Lava crystal
Place lava crystal into mekanism heat genarator

### Expected behaviour

Heat generator would produce RF

**Comment by aaronhowser1** [comment]
mekanism/Mekanism/issues/7000
