### ISSUE TITLE
Rose Quartz Crafting Recipe is Missing

### ISSUE THREAD

**Issue by shank3001** [FTBTeam/FTB-Modpack-Issues#4702]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Describe the bug

No rose quartz crafting recipe is avaible other through Mekanism Enrichment chamber which you need steel, but you need rose quartz in order to make Coke or Blast Bricks to make steel. This is a progression blocker.

### Steps to reproduce

1. No JEI recipe.

### Expected behaviour

Should have one nether quartz and 8 redstone dust recipe.

**Comment by Samtino** [comment]
Not a bug, you make Electron Tubes with Redstone Glass from an alloy kiln until you can get Rose Quartz
