### ISSUE TITLE
Compacted Dirt/ Cobblestone/ Gravel reverting to normal versions

### ISSUE THREAD

**Issue by kn1g0** [FTBTeam/FTB-Modpack-Issues#4703]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Describe the bug

Basically Title;
The Compacted Dirt/ Cobblestone/ Gravel just turned into the normal versions after seemingly random times (all being placed simultaneously).

### Steps to reproduce

1. Create Compacted Dirt, Gravel or Cobblestone
2. Place in world
3. Wait some time

### Expected behaviour

Blocks stay as is

### Additional information

Blocks were placed over void
I assume that this is a bug and not an intended feature, as it doesn't say so in the quest or tooltip of the items.
Also, they reverted while I was not actively digging at them.

**Comment by ArtpokeBr** [comment]
Its actually intentional, they should decay after 10 mins :)
