### ISSUE TITLE
Miniaturization Crafting in JEI - Hovering over some items doesn't always show the block

### ISSUE THREAD

**Issue by TheKoci** [FTBTeam/FTB-Modpack-Issues#4704]
### Modpack

FTB Skies Expert

### Modpack version

1.0.3

### Log Files

Not needed

### Describe the bug

When hovering over Miniaturization Crafting recipes in JEI, on some of the recipes the first block is not visible/clickable (as in the picture). 
From what I checked, the recipes currently affected (unclickable item in parentheses) are: 
Desh Tank (Third item - Hardened Glass)
Rocket Nose Cone (First item)
Runic Altar (Second item)
Rocket Fin (First item)
Calorite tank (Third item - Hardened Glass)
Calorite engine (First item)
Desh engine (First item)
Terrestrial Agglomeration Plate (First item)
Steel tank (Third item - Hardened Glass)
Steel engine (First item)
Ostrum engine (First item)
Ostrum tank (Third item - Hardened Glass)

### Steps to reproduce

1. Open Miniaturization Crafting recipes in JEI
2. Hover over the recipes.
3. In some of the recipes, the first item is not visible/clickable

### Expected behaviour

Hovering over the first item should provide the name and when clicked, its recipe

### Screenshots

![obrazek](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/18722279/5136b5e8-0758-400a-ae6d-5342e3e468da)

**Comment by TheKoci** [comment]
Just a note, this is using Faithful resourcepack, but friend I am playing with has default settings and has the same issue.

**Comment by Saereth** [comment]
this has been reported to the mod dev, not much else we can do about it from a pack standpoint. We've included notes for what blocks are needed in the quest and a schematic to build it though
