### ISSUE TITLE
Crash before world generation

### ISSUE THREAD

**Issue by aomtte** [FTBTeam/FTB-Modpack-Issues#4706]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Log Files

https://gist.githubusercontent.com/FTBAuto/377c6e7642c0265f757cd8008f99609c/raw/dfa98279f3863f22bd6bebe69fc0645375acbf24/hs_err_pid26720.log
https://gist.githubusercontent.com/FTBAuto/da70bec226b7db8bcea0da68f153f7fc/raw/db36b123f69d318457591837ab81d450d88d3944/latest.log

### Describe the bug

When trying to start a new world, the game load a few seconds with the labels "Preparing for world creation" then "Validating selected data packs" and in just few seconds the game close with the log file linked.

### Steps to reproduce

1. Start game
2. Press "Single Player"

### Expected behaviour

Game window close with above logs

### Additional information

I can start other modpacks like ftb-skies.
I can join public server of the modpack ftb skies Expert with no issues.
I tried using a blank world from ftb-skies, then pressing Single player didn't crash as it wasn't creating a world but showing me my save, but the save couldn't be started neither a new world created from this screen.
Regarding my hardware and devices, my keyboard layout is azerty (french layout), my monitor has a wide resolution (21:9) and my CPU don't have iGpu (KF series) if any of those can help.
After this log, I tried again with minor java update (from 17.0.8 to 17.0.10+11), still same error.

**Comment by Thrydwolf** [comment]
This is also happening to me, all versions of FTB Skies Expert.  It gets to Validating selected data packs... then crashes. Attaching my log.

[hs_err_pid9460.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14360059/hs_err_pid9460.log)

**Comment by aomtte** [comment]
So, I disabled every mod 5 by 5 until it stopped to crash, then I narrowed it down to Elementalcraft.
Disabling it won't either let me play, but show me this screen :
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/5513753/c448693f-3943-4724-a989-d9cf73e3dbdb)
Checking all mods won't do anything, also checked some randomly and did the same.
Then I tried removing every occurence and disabling the mod of elementalcraft in kubejs but then it crashed again on pressing single player.
If you could also try disabling this mod to check if you have the same issue as me, and if someone have idea to test to narrow down more the issue I'm open to every idea :)

**Comment by Thrydwolf** [comment]
Disabled Elementalcraft and received the same screen. I downloaded the
server files and tried to start a server and it rebooted my pc. I setup the
server on another pc I have and it boots up and I can connect to it and
play. Something specific on the pc's is causing this, just needing to find
out what.

**Comment by aomtte** [comment]
So I did few other tests.
I used docker to setup a server on the computer, and I ended up with the same error.
I used an eclipse-temurin (based on ubuntu) image, and also tried with 5 other modpack from FTP that caused no issues.
As far as my knowledge goes, it the issue was about something else than the hardware, the docker should have worked.
If you see any common parts to mine in the following list, it may help us to narrow the issue :

- I9-13900KF
- RTX3090FE
- 2x16GB DDR5(CMK32GX5M2B5200C40) 4800Mhz
- GIGABYTE Z790 AORUS ELITE AX

From now on, I'll setup a server on a local raspberry and see how it goes.

Docker command used : `docker run -it eclipse-temurin:17.0.10_7-jre-jammy /bin/sh -c "cd /home && curl -JLO "https://api.modpacks.ch/public/modpack/117/11701/server/linux" && chmod +x serverinstall_117_11701 && ./serverinstall_117_11701 --latest --auto && echo "eula=true" > eula.txt&& chmod +x start.sh && ./start.sh"`
[hs_err_pid173.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14390441/hs_err_pid173.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14390442/latest.log)

**Comment by Thrydwolf** [comment]
I9-14900K
Tried both - RTX 4080 and Radeon RX 7900 XTX
4x16GB DDR5 G.Skill Trident Z 7200 running at 4200 MHz (XMP not enabled)
ROG STRIX Z790-E Gaming WiFi
Java Build 1.8.0_401-b10 - have tried other versions but all resulted in
the same issue.

PC Server is running on is an AMD Ryzen 7 7700X with 64GB Ram

Both PCs are running Windows 11 Pro.

**Comment by KillerBoy777** [comment]
I'm receiving the same error every time I click Singeplayer and then hit "Validating selected data packs..."

I've also tried downgrading versions, allocating more/less ram, updating java and graphics drivers. Nothing has worked so far, but all other modpacks work fine.

**Comment by KillerBoy777** [comment]
I've found a way to at least be able to play the game. 

I had to downgrade the version to 1.0.1 in order to create a world. After it was created, I went through versions from most recent to last and the most recent version that is playable so far was 1.0.2. I don't know how much is missing, but this has at least let me get into a world.

I have yet to play with it much, but it seems like what we are experiencing is something from one of these updates.

**Comment by soutou233** [comment]
same here
I9-13900k
2x16GB DDR5 7200Hz
RTX 2080
ROG Maximus Hero Z790
Windows 11, JDK17

**Comment by aomtte** [comment]
So according to the hardware everyone liste, we are all on the same kind of cpu, either 13900k or 14900k.
With those informations I came across this post on Intel about memory access violation when CPU has boost enabled and reach 5.5 Ghz : https://community.intel.com/t5/Processors/Question-about-i9-13900k-experiencing-memory-access-violations/td-p/1520012

I am not able to test until monday but that seems close to what we encounter.

**Comment by Thrydwolf** [comment]
Confirmed that was the issue. Guess Microsoft didn't fix the issue from
22H2 to 23H2. Able to create a world now. Set my maximum processor
frequency at 5000 MHz in Power Options. If it doesn't show up in power
options then need to change registry key:

followed this article to enable maximum processor frequency
https://www.reddit.com/r/GamingLaptops/comments/vphxz0/guide_how_to_properly_limit_cpu_boost_clock_to/

*HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\75b0ae3f-bce0-45a7-8c89-c9611c25e100*

Change attribute from 1 to 2 to unhide the maximum processor frequency
setting in power options.

**Comment by aomtte** [comment]
As it does the same issue on linux, I doubt a windows update could fix it.

Fixed the issue for me too, even if changing the CPU frequency depending on which game I want to run is tedious.

Closing as the issue isn't related to the modpack itself.
