### ISSUE TITLE
StoneBlock 3 Freeze when opening the world

### ISSUE THREAD

**Issue by WithOneTee** [FTBTeam/FTB-Modpack-Issues#4707]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

When I open the world I previously played in singleplayer, it freezes. Yesterday I could open it easily. Also, yesterday I was playing with my brother with open to LAN

### Steps to reproduce

1. Go to Singleplayer Option
2. Enter a world
3. It then freezes for years

### Expected behaviour

Enter my world & play

### Screenshots

Can't really screenshot since it's frozen

**Comment by Gaz492** [comment]
Would you be able to upload the logs from your client when this happens and also upload your world so we can take a look at it?
https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
