### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by FlavioF6799** [FTBTeam/FTB-Modpack-Issues#471]
### Modpack

FTB: Oceanblock

### Modpack version

1.9.0

### Log Files

https://pastebin.com/nPLp0eP3

### Describe the bug

it's like when i gonna make RS latch and OR gate, then this game crashed, cause by render by 3D between 2D

### Steps to reproduce

1. going to Refined Storage Pattern Grid
2. make pattern of LS Lanch (for example)
3. put pattern LS Lanch in inventory
4. open inventory and press shift then this happened

### Expected behaviour

error by rendering thread

**Comment by Sunekaer** [comment]
Fixed in newer version of the pack
