### ISSUE TITLE
Resolve confusion around "feature" #4703

### ISSUE THREAD

**Issue by no-name-provided** [FTBTeam/FTB-Modpack-Issues#4710]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

It's unnecessarily confusing. 

1. "Feature" #4703 isn't documented in-game. There's no reference to this behavior in the quest that tells you to make them, there's no tooltip, no info page in JEI, no countdown in WAILA/One Probe, etc. When they decay, they revert to the base block (something you're likely to have laying around randomly) - they could decay to special "depleted" variants that drop the base block when broken.

**Comment by Saereth** [comment]
The quest that has you make it and tells you about it explains the decay mechanic as well.

**Comment by no-name-provided** [comment]
Following a series of unfortunate interactions with Saereth, and pursuant to his request to "fuck right off", I am unsubscribing from this issue.
