### ISSUE TITLE
Pedestals Issue

### ISSUE THREAD

**Issue by NixMiner1** [FTBTeam/FTB-Modpack-Issues#4711]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

When breaking a pedestal with fluid in it will crash a server when temp fluid item would disappear. on previous version acted normally.

### Steps to reproduce

put fluid in pedestal
break pedestal
have temp fluid item in inventory when its timer runs out

### Expected behaviour

Crash

**Comment by Saereth** [comment]
can you please provide a crahs log?

**Comment by Mowmaster** [comment]
As the mod dev I've dug into this a fair bit, both using the packager upgrade and by breaking pedestals to get the packaged fluid item from them, Ive used a number of modded fluids like cyclic xp, cognitium, energized glowstone(which cant be placed in world), primitive slurry. 
In single player I cannot reproduce this bug, I would request at the minimum a full crashlog, and if possible, exact details on fluid used, amount in package, etc. That way the issue can be reproduced by someone else.
