### ISSUE TITLE
Adjustable and interdimensional SU won't output power on any side

### ISSUE THREAD

**Issue by selwo** [FTBTeam/FTB-Modpack-Issues#4716]
### Modpack

FTB Ultimate Reloaded

### Modpack version

1.10.0

### Describe the bug

ASU and IDSU wonr output power on any side but store power normaly and Charles items in it.

### Steps to reproduce

Try.

### Expected behaviour

Output power like any mfe or mfsu

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
