### ISSUE TITLE
[Bug]: Melter not accepting fuel from Heater (Server ONLY)

### ISSUE THREAD

**Issue by Shinino** [FTBTeam/FTB-Modpack-Issues#472]
### Modpack

FTB Oceanblock

### Modpack version

1.9.0

### Describe the bug

After playing this on singleplayer, I created a server (using 1.9 due to other bugs).  In Singleplayer, I was able to create a basic Melter/Heater setup, and it worked fine with charcoal as fuel.  On my server, I did the same thing -- but the melter would keep saying 'no fuel' and not accept trees or charcoal.  

Running a test by giving myself a fluid tank and a bucket of lava resulted in the combo of a Melter and Fluid Tank working as expected.

### Steps to reproduce

1. Create Heater
1a. Place Heater
2. Create Melter
2a. Place Melter on top of Heater
3. Put charcoal in Heater.
4. Click on Heater, see 'no fuel' under the stack of charcoal

### Expected behaviour

Melter/Heater combo should work in multiplayer similar to singleplayer

### Screenshots

https://imgur.com/DQ8dyPu
https://imgur.com/9gWelMG
https://imgur.com/GoTdIrs

**Comment by Raidobw2** [comment]
Does updating to 1.10.1 fixes the problem? There might have been changes to the modpack already to correct this

**Comment by Shinino** [comment]
Haven't tried due to the bug with dropping items in 1.10.1 to be honest.

**Comment by Raidobw2** [comment]
The bug with items is fixed in 1.11.0, you should try updating please!

**Comment by Shinino** [comment]
Resolved in 1.11.0!
