### ISSUE TITLE
Server Crash when certain terrain is generated.

### ISSUE THREAD

**Issue by BobHassok** [FTBTeam/FTB-Modpack-Issues#4722]
### Modpack

FTB Presents Direwolf20 1.12

### Modpack version

1.12.1

### Log Files

https://hastebin.com/share/ipugowuhod.perl

### Describe the bug

Internal & Dedicated server will crash when generating specific locations.

### Steps to reproduce

Going near a couple areas will cause the issue. I have found 2 locations so far. World file(s) will be provided upon request.

### Expected behaviour

Terrain generates as normal.

### Additional information

I have tried a few things. I tried loading the area multiple times in single player and had the issue happen every time. Next I tried removing AdoptOpenJava and updating to the newest version(s). Next tried removing AdoptOpenJava and installed Oracle's Java 8 Update 401 (32bit & 64bit). Next I tried opening the game to multiplayer and loading the area. Finally I tried downloading the dedicated server files and importing my World. The issue persists through all these attempts.

**Comment by ParsaPilehvari** [comment]
I am also having the issue and have done similar steps, I have attempted to remove the region folders to regenerate however error persists and stalls server/single-player worlds. I suspect it may be an issue with structure generation, but hard to tell with the stalls.

**Comment by ParsaPilehvari** [comment]
Sorry to piggyback on your ticket, but it seems we have the exact same issue. I have tried generating a new world and still face the same issue, so it does not directly appear to be a corruption of the previous world. I have noticed that in some of the stalling regions, I get errors about POI mismatches and hanging entities before a stall, however it does not seem exclusive to it as the stalls can happen without the error. Additionally, when a stall occurs, the maximum ram allocated to the instance is used, which could indicate a leak?

My theory is that there is a structure being generated in those regions/chunks causing a stall, but it is difficult to tell without a crash report generating. I am open to anyone's assistance

**Comment by BobHassok** [comment]
> I am also having the issue and have done similar steps, I have attempted to remove the region folders to regenerate however error persists and stalls server/single-player worlds. I suspect it may be an issue with structure generation, but hard to tell with the stalls.
> 
> [Edit] To add on, attempting to pregen the world causes a crash when certain regions are loaded too, even if no players are online.



> Sorry to piggyback on your ticket, but it seems we have the exact same issue on version 1.12.1. I have tried generating a new world and still face the same issue, so it does not directly appear to be a corruption of the previous world. I have noticed that in some of the stalling regions, I get errors about POI mismatches and hanging entities before a stall, however it does not seem exclusive to it as the stalls can happen without the error. Additionally, when a stall occurs, the maximum ram allocated to the instance is used, which could indicate a leak?
> 
> My theory is that there is a structure being generated in those regions/chunks causing a stall, but it is difficult to tell without a crash report generating. I am open to anyone's assistance


I read the log more and saw that the "NoMoWanders" mod was showing up a lot. So I disabled the mod and the issue disappeared for me. I suggest you 2 try to disable the "NoMoWanders" mod and see if that helps.

**Comment by ParsaPilehvari** [comment]
@BobHassok You're a lifesaver, thank you so much! Disabling the mod allowed me to generate the bad regions with no more issues. Thank you again.

**Comment by BobHassok** [comment]
@ParsaPilehvari No problem! Once I disabled the mod and went to those areas I think I saw what was causing the crash. Found Iron's Archevoker compounds with imprisoned Wandering Traders in them.

![2024-02-23_17 29 50](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8952360/f1b28270-959c-4fbd-85a1-b38426cde07a)
![2024-02-23_17 28 27](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8952360/cb9c23be-ddac-40c6-9480-f78b0191f142)

**Comment by ParsaPilehvari** [comment]
I've done the same and those are the exact same structures that caused me to crash.
