### ISSUE TITLE
Infinite su with diesel generator

### ISSUE THREAD

**Issue by Zichen0804** [FTBTeam/FTB-Modpack-Issues#4724]
### Modpack

FTB Skies Expert

### Modpack version

1,10

### Describe the bug

Diesel generator normally generates 2112su (lowest tier), but when relogging, it adds to itself another 2112su, and it is stackable.
So relog 2 times gives 4224su, 3 times gives 6336su....making it infinite.

### Steps to reproduce

Although is inconsistent in a test world, sometimes it work like in the creative world screenshot, in my survival world it is consistent.
1, place down diesel generator and connect some machines, let it run
2, relog a couple of times
3, infinite su

### Expected behaviour

Infinite su with diesel generator

### Screenshots

![2024-02-22_08 39 38](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/134135107/5b89e6a5-3435-4cf5-b927-2da05d6199fc)
![2024-02-22_08 41 27](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/134135107/f1aa80f1-aed7-4266-9964-59f08e0ebfda)

**Comment by phit** [comment]
this is still happening for us consistently after the update, basically every server restart will create ghost SU

**Comment by TheBlckbird** [comment]
same issue here
