### ISSUE TITLE
Honey bottles to SlowMelter9000 - Disable this recipe or change outcome to Productive bees Liquid honey

### ISSUE THREAD

**Issue by Kyks20** [FTBTeam/FTB-Modpack-Issues#4725]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

If you put honey bottles to Slowmelter9000 it will make Cyclic liquid honey. Maybe disable this recipe or change outcome to productive bees honey. caus "supper"cooling can make productive bees honey to bottled honey

**Comment by ArtpokeBr** [comment]
Are you in the most recent version? cause it seems that this was already fixed. =)

**Comment by Kyks20** [comment]
Yea i just updated and found it out. Thanks! Love this pack!
