### ISSUE TITLE
Ruined Portal Loot Chests sometimes fail to generate

### ISSUE THREAD

**Issue by Bluehanz** [FTBTeam/FTB-Modpack-Issues#4726]
### Modpack

FTB One

### Modpack version

2.8.3

### Describe the bug

Sometimes when generating ruined portals in newly generated chunks, the loot chest is not there (it just fails to generate). This also always happens with ruined portals that generate underwater.

### Steps to reproduce

1. Create new world in Creative Mode
2. Locate Ruined Portal
3. Travel to that Portal (do not teleport)
4. Teleport to a random remote location and repeat the process until a portal is found without a chest nearby

### Expected behaviour

A chest should be present close to the Portal

### Additional information

My guess is that it could be an issue with the compatibility of the mods Quark and Lootr, since the loot chests that generate are of a random wood type instead of the standard ones

**Comment by Frinzky** [comment]
I found one too while playing hardcore in the latest version, apparently this bug hasn't been fixed.
seed: 2706985192657261156
coordinates: 358 70 222
