### ISSUE TITLE
[Suggestion]: FTB Uni 1.16 Blood Magic Quest

### ISSUE THREAD

**Issue by douyabian** [FTBTeam/FTB-Modpack-Issues#473]
### Modpack

FTB University 1.16

### Is your suggestion related to a problem? Please describe.

![BM](https://user-images.githubusercontent.com/30873473/145944310-39946aeb-0b1a-42ef-908b-e768cfeb0035.png)

Gathering of Forsaken Souls isn't available yet in the current version of blood magic, also for clarity, the ritual would damage mobs but it needs to kill a mob for it to grow crystals

Also, would be nice if there was a quest related to saturated tau just to make it easier for players to decipher what to do, with the most recent version (3.1.6) making the tau scanning range 3x1x3 and easier to grow

**Comment by aaronhowser1** [comment]
Removed the last paragraph.

As for the Tau, I'm going to wait until the dungeons are a bit less... awful. They're incredibly unfinished.
