### ISSUE TITLE
PneumaticCraft Pressure Tube multiplication

### ISSUE THREAD

**Issue by Lancelu-Horse** [FTBTeam/FTB-Modpack-Issues#4730]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

Using Building Gadget on Pressure tubes places it, but not consume from inventory. Thus, infinity tubes multiplication

### Steps to reproduce

1. Shift right click with building gadget on pressure tube
2. Set building gadget on any mode to place it

### Expected behaviour

Should consume the tubes from iventory

**Comment by Saereth** [comment]
ok blacklisted these now
