### ISSUE TITLE
Unable to travel to the End

### ISSUE THREAD

**Issue by CactusDuper** [FTBTeam/FTB-Modpack-Issues#4731]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

In FTB Skies, `\kubejs\data\ftbskies\planet_data\planets` contains `skies_end.json` which allows travel to the end with Ad Astra. FTB Skies Expert does not have this file meaning you cannot travel to the end with Ad Astra. In the quests book, the `Ad Astra` questline has a quest called `Visit the End` which states: `With a Tier 1 Rocket, you can fly to the End!`. Under the `progression` questline, the quest `Visit the End` states: `The next step is to breach the End! There are two methods to do this: Craft End Portal Frames, which is gated behind the Gaia Guardian. Fly there using Ad Astra. See its chapter here (links to the above Ad Astra quest) for more information.`

The recipe for minecraft:end_portal_frame exists in FTB Skies but not FTB Skies Expert.

### Steps to reproduce

1. Launch a rocket
2. Observe that the option to travel to the end does not exist
3. Look for the recipe for minecraft:end_portal_frame
4. Observe that the recipe does not exist

### Expected behaviour

According to the quest book, there should be two methods to enter the end. Both methods do not exist in FTB Skies Expert.

**Comment by TheKoci** [comment]
This is most likely not a bug, just a not updated quest, as from what Saereth wrote in discord, recipe for the frames unlocks after you visit Glacio
![obrazek](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/18722279/ea8f9dbb-cc75-410e-93b4-823bcf4722b8)

**Comment by CactusDuper** [comment]
I see, thank you for letting me know! I'll leave this issue open since the quests still need to be updated. Thank you so much!
