### ISSUE TITLE
There is no way to generete brine

### ISSUE THREAD

**Issue by vencordplus-a** [FTBTeam/FTB-Modpack-Issues#4732]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

since solar generators can only be placed on orbit, Thermal Evaportion Controller needs to get set up in orbit.
the problem with that is since you cant place any water in orbit (it turns into ice) you cant use aqueous accumilator or its alternatives.
I tried to use compact machines but for some reason fluid tunnels dont work. mekanism or thermal fluid pipes both dont connect, or doesnt pull with servo.
as a result there is no way to generate brine in pack (at least from what stuff I tried)

edit: I can just fill a tank in overworld and take move it there but obv that will be fully manual all the time so.

### Steps to reproduce

1: Go to orbit
2: set up thermal evaporation plant
3: try to generate water
4: fail

### Expected behaviour

generate brine

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/151923520/eb2d63e9-5dc5-4ba1-a08c-8b2698eec129)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/151923520/ee4874e7-bb2e-43a6-bce9-c17c11f25ff7)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/151923520/abd17c5c-04db-4e06-b7b7-a7838fe27b84)

**Comment by ArtpokeBr** [comment]
technically you can always make brine using Salt directly, But I understood your issue, gonna take a look.

**Comment by ArtpokeBr** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/44851727/9bbe00d0-9da3-4adb-b409-861c90d3c45a)
Hey so you don't actually need to place in orbit, you can use PneumaticCraft to generate the required Heat for it. =)

**Comment by ArtpokeBr** [comment]
after some more quick testing, you can actually have Water in your Space Station, just make sure that the room has oxygen.

**Comment by Radiumss** [comment]
use ender tank

**Comment by KuroPeach** [comment]
Use blocks containing water

**Comment by vencordplus-a** [comment]
> Use blocks containing water
oh does that work lmao

also I managed to get compact machine working, for some reason they are hella bugged in this version. whenever I break it I need to break and reput all tunnels and the pipes in outside.
