### ISSUE TITLE
Game Hangs Then Crashes

### ISSUE THREAD

**Issue by Crazyzora** [FTBTeam/FTB-Modpack-Issues#4733]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

When using Create's trains after getting off the seat the game will run for a few seconds and then hang, audio will repeat but it will be un-responsive. This happens when traveling large distances (happened at 400 blocks traveled and 900 blocks traveled).

Update: re-loaded old save and manually dug to 400 blocks, then started traveling back. Game hanged then crashed without the use of trains. Upon reload of save of me running back from the 400 blocks; game loaded in everything and I was able to return to base without game hanging again.

### Steps to reproduce

1. Create a train that has drills, places rails, and places torches.
2. Get on train on seat and use train controller to move the train.
3. Travel a long distance, at least 400 blocks.
4. Get off the seat and travel back down the tunnel.

### Expected behaviour

The game will freeze with audio playing and will not recover.

### Additional information

There didn't seem to be a problem when using the train for short distances.
I only got off the seat when I found the stone dungeon and stone caves, there may be a link but untested.
Did creative world with same train, traveled 800 blocks without crashing.
I did not have my base chunk loaded. I'm wondering if this is part of something else that needs to be chunk loaded at my base.

**Comment by Crazyzora** [comment]
Update: Made a creative world to remake same train, did not freeze after 800 blocks.

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can take a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
