### ISSUE TITLE
Quantum Assembler preview doesn't show Vibrant Glass

### ISSUE THREAD

**Issue by TheKoci** [FTBTeam/FTB-Modpack-Issues#4734]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Log Files

Not needed

### Describe the bug

When viewing the structure for Quantm Assembler via the button in the controller gui (recipes->under the energy, that button with "required structure"), it doesn't show the Vibrant Glass required (screenshot). It might be a bug with the mod itself, but I wasn't 100% sure, because when viewing the sctructure in Schematic from Create, structure looked fine and it worked after that too, so just seems like an issue with rendering (probably) glass-ish blocks.

### Steps to reproduce

1. Build only Quantum Assembler
2. Open GUI -> Recipes -> Click on the required structure button
3. Observe that Vibrant Glass in the back is not visible

### Expected behaviour

Vibrant Glass should be rendered when clicking the GUI button

### Screenshots

![obrazek](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/18722279/edb0ad86-7135-4965-867e-aa3b4d6ce018)

**Comment by Saereth** [comment]
nothing we can relaly do about this render, its been reported, we included a schematic cannon builder to build it for you though which will list the glass as a work around
