### ISSUE TITLE
Lan servers don't show up in server list nor does direct connect work.

### ISSUE THREAD

**Issue by DamondSword2247** [FTBTeam/FTB-Modpack-Issues#4735]
### Modpack

FTB Skies

### Modpack version

1.4.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14382243/latest.log)

### Describe the bug

Can't join Lan servers. Weather you use the port or Ip address.

### Steps to reproduce

1. Be on the same network
2. Create a Lan server
3. Get another computer on the same network and go to multiplayer menu
4. Find no Lan server in the multiplayer menu
5. Try direct connection find either there is nothing to connect to or get timed out

### Expected behaviour

Being able to join Lan servers while on the same network.

### Additional information

Both firewall settings are set to allow on both systems. Also effects the expert version of the modpack.

**Comment by Gaz492** [comment]
It looks like the LAN servers not being visible may be caused by Minetogether, but I've not been able to reproduce the issue of not connecting to another LAN server.
