### ISSUE TITLE
Pneumatic Craft ethanol craft giving incorrect amount

### ISSUE THREAD

**Issue by BoundenDeer** [FTBTeam/FTB-Modpack-Issues#4736]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

the thermopneumatic processing plant is giving only 100mb of ethanol for a craft costing 100mb of yeast culture, but its supposed to give 200mb according to the JEI crafting recipe

### Steps to reproduce

1. put 100mb or more yeast culture in thermopneumatic processing plant
2. add 1 or more sugar
3. ensure it has proper heating and pressure to craft ethanol

### Expected behaviour

supposed to give 200mb of ethanol per craft

**Comment by DinnerBeef** [comment]
Thanks for reporting and issue, However this is working as intended and will not be fixed. Sugar only gives you 100. While Mendosten gives you 200
