### ISSUE TITLE
There is no way to get Apotheosis material (Mysterious scrap metal etc.)

### ISSUE THREAD

**Issue by brave-nico** [FTBTeam/FTB-Modpack-Issues#4737]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

Apotheosis materials are usually obtained by salvaging items containing Affix.
However, weapons, tools, and armor containing Affix cannot be put into the salvage table.
In addition, it was not possible to transport the items even if pipes or hoppers were used.
Therefore, various materials (for example, Mysterious scrap metal) cannot be obtained.

### Steps to reproduce

Step 1: Prepare the item containing the Affixes in your inventory.
Step 2: Create a salvaging table for Apotheosis MOD and place it anywhere.
Step 3: When you try to put an item containing an Affixes into the salvaging table, it doesn't work!

### Expected behaviour

you can put an item containing an Affixes into the salvaging table and get  material.

**Comment by mthp1999** [comment]
Looks like the only way to get the materials is through boss killing and sky villages

**Comment by Saereth** [comment]
this is intended yep
