### ISSUE TITLE
I suddenly couldnt play on my single player server after several hours played

### ISSUE THREAD

**Issue by Bassillen** [FTBTeam/FTB-Modpack-Issues#4739]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

So after 9 hours of on my singleplayer server, i just out of no where couldn't get in. And i making a new server works, but i want to still play on my server and not a new one. I goes as such, i click on the server on my singleplayer tab, and then i go to the loading screen. I says "Reading datea " for like 30 seconds, and then it disapears. then i sit there looking at the blue brick background, with the tip box in the left corner. I left this loading screen on for 30 minutes, nothing happend. I have no idea what has happend and what to do. 

### Steps to reproduce

...

### Expected behaviour

I simply expected to get in to my server and play the modpack

### Screenshots

( I wasnt able to take a screen shoot of the problem, but i think you get the idea of my description

### Additional information

I just wish i could play tbh , this was one of the most fun i had in a long time while playing a modpack.
( Note after writing this: After i was bored of trying to get in, i played a litle FTB stoneblock 3 , and the same exact same thing happend )

**Comment by Saereth** [comment]
we'll need a crashlog or latest.log/debug.log to investigate further for you
