### ISSUE TITLE
Unable to craft Ostrum Space Plating/create a tier 3 rocket

### ISSUE THREAD

**Issue by CactusDuper** [FTBTeam/FTB-Modpack-Issues#4741]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

Ostrum Space Plating cannot be crafted.

Ostrum Space Plating requires Polytetrafluoroethylene.
Polytetrafluoroethylene requires PTFE Sheet.
PTFE Sheet requires Hydrofluoric Acid.
Hydrofluoric Acid requires Chemical Dissolution Chamber.
Chemical Dissolution Chamber requires Ultimate Control Circuit.
Ultimate Control Circuit requires Cryo Infused Gas.
Cryo Infused Gas requires Cryo Fuel.
Cryo Fuel requires Cryo Freezer.
Cryo Freezer requires Ostrum Tank.
Ostrum Tank requires Ostrum Space Plating Block.
Ostrum Space Plating Block requires Ostrum Space Plating.

Because Ostrum Space Plating needs Ostrum Space Plating, it cannot be crafted.

I have not been able to find any of the above requirements on Mars or anywhere else. Because of this, it appears that it is currently impossible to progress beyond Mars.

### Steps to reproduce

1. Look at the recipes for Ostrum Space Plating
2. Observe the above loop

### Expected behaviour

There should be a way to craft/obtain Ostrum Space Plating or one of the dependencies.

**Comment by CactusDuper** [comment]
Addition:

```
// Deny Cryo Fuel placement when not on Glacio
BlockEvents.placed("ad_astra:cryo_freezer", (event) => {
  const { level, player, block } = event;
  if (level.getDimension() !== "ad_astra:glacio") {
    if (!player.isCreative()) {
      error(event, "This can only be placed on Glacio")
      block.set("minecraft:air");
      returnBlock(event, "ad_astra:cryo_freezer")
    }
  }
});
```

This would have to be changed as well unless another method to obtain Cryo Infused Gas/Cryo Fuel is added.

**Comment by Radiumss** [comment]
raw ostrum obtained by laser drill in planetary orbit

**Comment by Radiumss** [comment]
> raw ostrum obtained by laser drill in planetary orbit

sorry i dont see the ostrum tank
