### ISSUE TITLE
Prefab's bulldozer is not working

### ISSUE THREAD

**Issue by Sei-moto** [FTBTeam/FTB-Modpack-Issues#4743]
### Modpack

FTB University 1.19

### Modpack version

1.19.2

### Describe the bug

bulldozer in prefab mods are not working
use Triple Compreesd stone to work bulldozer but nothing happen
and prefab's T-C-S recipe is didn't work

### Steps to reproduce

1. make bulldozer
2. use anvil to make bulldozer+Triple compressed stone
3. :(

### Expected behaviour

work

### Screenshots

![bull2](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/113434111/282952c6-3b62-43b3-9bd8-84d8e9ea1435)
![bull1](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/113434111/d34f7562-4b88-42f0-ab8f-4f8b97aa88db)

**Comment by aaronhowser1** [comment]
Related to #3447
