### ISSUE TITLE
World crashing on load

### ISSUE THREAD

**Issue by Pixelbushbebe** [FTBTeam/FTB-Modpack-Issues#4744]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Log Files

[crash-2024-02-23_18.13.59-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14388777/crash-2024-02-23_18.13.59-server.txt)
[My bro he loves to fidget.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14388786/My.bro.he.loves.to.fidget.zip)
[Redoing I guess.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14388790/Redoing.I.guess.zip)

### Describe the bug

Game launches fine but when I load certain save files the game loads in and instantly says "Error, Server Closed" and then crashes.

### Steps to reproduce

Both of my world saves are in the log files, load them into the game and your game should also crash on loading them.

### Expected behaviour

Game will load fine, but upon fully loading into either save will instantly crash

**Comment by Gaz492** [comment]
I had luck in resolving the issue your world is running into by following the guide below and enabling both the options mentioned in the guide.
https://docs.feed-the-beast.com/docs/support/Troubleshooting/ticking-entities/#packs-running-forge-114-and-newer
