### ISSUE TITLE
Electric motor quantum assembler recipe

### ISSUE THREAD

**Issue by vencordplus-a** [FTBTeam/FTB-Modpack-Issues#4748]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/151923520/0e4c9b3e-ab7f-4fce-90a8-b1699e1ca89e)
this recipe is already hella annoying and only way to make it is through mechanical crafter
idk if that was intentional or forgotten but it would be very nice if we could craft it in quantum assembler

**Comment by TheKoci** [comment]
Why though? It is being used to craft only into like 3 things in total? There is like no reason to put it into Quantum Assembler at all.

**Comment by vencordplus-a** [comment]
technically yeah but for setting up stuff that use su in different places you need electric motors, its possible to mass craft at once but I think if other mechanical crafter stuff are on quantum assembler this would make sense too
