### ISSUE TITLE
KubeJS has failed to load correctly

### ISSUE THREAD

**Issue by Henda1zyzz** [FTBTeam/FTB-Modpack-Issues#4750]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Log Files

https://drive.google.com/file/d/1TnrfYI-vbSACBlr9bBHje5oOysCmGnQ3/view?usp=drive_link
https://drive.google.com/file/d/15P27cfT4yRWmTwjrzUCJb9tQkGCYr-Wn/view?usp=drive_link
[crash-2024-02-24_14.41.14-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14392649/crash-2024-02-24_14.41.14-fml.txt)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14392650/latest.log)

### Describe the bug

When I launching the game, appears an error "KubeJS (kubejs) has failed to load correctly". Before today, game started with no problem

### Steps to reproduce

1. Launch the game
2. Loading
3. Error

### Expected behaviour

I expected to see the menu of stoneblock

### Screenshots

![Screenshot_12](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/161121334/8242c82a-dac3-4db4-a0c1-7870a6554bd9)

**Comment by Shybella** [comment]
Every pack is basically crashing out of the box, no one seems to care much

**Comment by Gaz492** [comment]
Would you be able to upload the KubeJS startup.txt log for us?
This log can be found in the logs folder then kubejs > startup.txt
