### ISSUE TITLE
Functional Storage controllers have a bad interaction with any form of item transfer on world relog.

### ISSUE THREAD

**Issue by MrSelenix** [FTBTeam/FTB-Modpack-Issues#4752]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Log Files

n/a

### Describe the bug

If you are in a world with functional storage draws being fed items via a basic item collector (item collectors mod) into the storage controller, such as from a mob farm, the item collector will place items into empty drawer slots instead of pre-filled slots. This behaviour only shows itself whenever joining a world

### Steps to reproduce

1. Make a setup with drawers, connected and linked to a controller
2. Attach a basic item collector to the controller
3. Add some random items (e.g. rotten flesh, bones etc) to some of the drawers, leaving some slots empty.
4. Quit to main menu
5. Relog into the SP world
6. Take an item out (or spawn a new item) and toss it toward the collector
7. _**Sometimes**_ that item will go to an empty slot instead of the existing slot.
8. Try step 4 onward again if it didn't happen the first time.

The behaviour seems frequent but unpredictable. Rebinding the drawers to the controller does resolve the issue for that session, but one would have to repeat this every time they join the world again.

### Expected behaviour

One would expect all items to enter the appropriate slots on the drawers after quitting and re-logging.

### Screenshots

![Screenshot 2024-02-24 190434](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/37115839/2d136eab-1c28-4be5-b0fe-d4a6c662ee48)

Item collector is behind the piston bottom right, feeding the controller. Ordinarily items go to the occupied places. but when re-logging, items will often enter the open unlocked slots top left. The behaviour happens regardless of if a drawer is locked or not.

### Additional information

Right clicking items on the controller to insert still places the items in the correct drawer, so is most likely a bad interaction between the basic item collector and the controller.

EDIT: It would appear its not linked exclusively to the item collectors but any form of item transfer, including pedestals and even vanilla hoppers. Anything that can insert items into the controller. So either a buggy version of functional storage, or a different mod is affecting how item transfer works between the controller and something else

**Comment by isochronous** [comment]
I've definitely noticed some weird issues with functional storage - for example, cobblestone I took out of one drawer was unable to be stored in a different cobblestone drawer... until I placed and broke the "weird" cobblestone, and then I could put the result into the second drawer.

**Comment by MrSelenix** [comment]
Ive even downgraded the version of functional storage to the previous stable release and still had the same issue with them being awkward regarding inserting items into random slots, so leads me to believe theres a mod conflict somewhere down the line. But as to which i have no idea.

**Comment by Saereth** [comment]
I have observed this and it appears the items actually have different nbt data, something is giving them that data although im not sure what yet so I'll be looking into it further later

**Comment by Saereth** [comment]
appears to have been balm which has been updated now and should fix this in 1.8
