### ISSUE TITLE
space station not generating for me

### ISSUE THREAD

**Issue by chrisnox10** [FTBTeam/FTB-Modpack-Issues#4754]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

i orbited to around earth but it did not generate a space station for me. It landed me back on my island instead. 

### Steps to reproduce

1. launch rocket
2. select orbit around earth
3. landed back on island not the space station

### Expected behaviour

expected behavior was to land on the space station

**Comment by Saereth** [comment]
Ill need log files and/or debug logs, did anyone else in your team already goto space/orbit by chance?

**Comment by Saereth** [comment]
we added some more sanity checking and edgecase handling for this, should be resolved hopefully
