### ISSUE TITLE
StoneBlock 3 "Mechanical Crafter" not working.

### ISSUE THREAD

**Issue by carztle** [FTBTeam/FTB-Modpack-Issues#4757]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

Built a Mechanical Crafter and tried to craft items with it but every time as it's about to finish crafting all the recipe items just fly out and drop to the floor.

### Steps to reproduce

1. Build Mechanical Crafter.
2.  Put in any recipe
3.  Start crafting

### Expected behaviour

fix naxui

### Screenshots

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/161207827/48969224-f9fd-48b2-bb40-fc858a76ee48

**Comment by UnRealDinnerbone** [comment]
Can't tell from the video, are you sure you have the correct crafting recipe? Items pop out if the crafting recipe is invalid
