### ISSUE TITLE
Crash when scrolling

### ISSUE THREAD

**Issue by GrishaCrysta** [FTBTeam/FTB-Modpack-Issues#4759]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Log Files

https://drive.google.com/file/d/1fR2o7u9wA7iW4zV5jvEHCVrdTCLGjXUU/view?usp=sharing

### Describe the bug

I scrolled with mmb & it crashed, log is 44 mb so i download it on google disc

### Steps to reproduce

1. Go into world
2. Scroll hotbar

### Expected behaviour

selecting other slot

**Comment by Saereth** [comment]
looks like some mod broke your renders and spammed your log till it eventually crashed with a massive log, not really helpful from the log though pinning it down, any chance you know what items you had on your hotbar?

**Comment by GrishaCrysta** [comment]
Akashic tome (spice of life), something from chest in standart world (1 tree & small island) & some tree loot

**Comment by GrishaCrysta** [comment]
@Saereth ?

**Comment by Saereth** [comment]
I believe this should now be fixed with the emeddium update for 1.6.0 coming out today
