### ISSUE TITLE
[Suggestion]: Accept Soul Snad in Bonsai Pots

### ISSUE THREAD

**Issue by DasBrain** [FTBTeam/FTB-Modpack-Issues#476]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

Currently only Soul Sand and Soul Soil are accepted in the Bonsai Pots.

Modifier TBD.  
If it should be twice as fast as soul sand, it needs a modifier of +0.35

**Comment by quietust** [comment]
Is Soul Snad an actual item from the "Snad" mod, or are you suggesting adding a brand new item?

**Comment by quietust** [comment]
To clarify, Soul Snad *is* a block provided by the "Snad" mod in this pack for the purpose of growing Nether Wart more quickly, but it isn't usable in Botany Pots. This might be worth reporting as a bug in the Botany Pots mod itself.
