### ISSUE TITLE
Sleeping in Comforts Hammock makes the time morning

### ISSUE THREAD

**Issue by alkinguler** [FTBTeam/FTB-Modpack-Issues#4761]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

As stated in the title, sleeping in a hammock from comforts mod makes the time morning instead of night.

### Steps to reproduce

1. Be in Direwolf20 1.20 pack (version 1.12.1)
2. Craft/Place a comforts hammock.
3. Sleep in hammock
4. Can be seen time is now morning

### Expected behaviour

It should turn the time to night

**Comment by DinnerBeef** [comment]
Thanks for reporting and issue, However this is working as intended and will not be fixed.

**Comment by JheregJAB** [comment]
@DinnerBeef This is not working as intended, its a bug in the mod and has to do with interactions with Ad Astra. See the ticket filed for the comforts mod itself (but while using dw20 1.20).

https://github.com/illusivesoulworks/comforts/issues/138

**Comment by ExoBiTe** [comment]
This is indeed not working as intended. Please reconsider fixing this issue.
Ad Astra has fixed that Bug on their Side from Version 1.15.17 on (https://github.com/terrarium-earth/Ad-Astra/issues/470), 
but the Pack includes only Version 1.15.10.

**Comment by JheregJAB** [comment]
@ExoBiTe The pack is dead. No updates at all since my comment in March, and this issue is only one of many. You should set your expectations that there will be no more updates to this pack.
