### ISSUE TITLE
Can not craft Integrated Tunnels Energy Interface due to components being uncraftable.

### ISSUE THREAD

**Issue by MrSelenix** [FTBTeam/FTB-Modpack-Issues#4762]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Log Files

n/a

### Describe the bug

The Energy Interface from Integrated Tunnels requires an Energy Battery to craft, but the Energy Battery recipe has been removed and hidden from JEI.

### Steps to reproduce

n/a

### Expected behaviour

If it is intended to not use integrated tunnels energy interface/importers etc, perhaps hiding those from JEI too, otherwise the battery in the recipe may need to be changed for something that can be crafted.

**Comment by pikminman13** [comment]
fixed in dev
