### ISSUE TITLE
Old unpacking recipes for Multiservo Press not working due to removed unpacking die

### ISSUE THREAD

**Issue by Therrous** [FTBTeam/FTB-Modpack-Issues#4768]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

The recipes for the Multiservo Press that would 'unpack' one item into multiple no longer work. JEI claims that no mold/die is needed, but the items simply will not fit into the machine. My assumption is that the recipe is still trying to get the removed original die, and its functions were not moved onto using the equivalent Immersive Engineering mold. 

### Steps to reproduce

1. Attempt to put a block of lapis in the Press to unpack it 'automatically'
2. Realize the futility of your actions

### Expected behaviour

Unpacking recipes shown in JEI work

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/109634384/c86f32e1-25c8-4217-9e83-a2421574b77e)

**Comment by pikminman13** [comment]
alright a bunch were added and it doesnt corrupt player data (found out what was causing it)
