### ISSUE TITLE
game loading issues

### ISSUE THREAD

**Issue by MYTH1xWolf** [FTBTeam/FTB-Modpack-Issues#4769]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.13.0

### Describe the bug

im having an issue when loading the modpack using ftb launcher where it is saying that loads of kubejs files didnt load properly and this keeps happening even when i deleted instance and reloaded it.

### Steps to reproduce

1. load direwold20 1.19 2. wait

### Expected behaviour

i dont know

### Screenshots

![Screenshot 2024-02-26 153917](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/161343660/58947240-65c4-456c-8859-83c1998721d5)

**Comment by tlannigan** [comment]
Rename all those files, change the uppercase "DWL" in them to a lowercase "dwl".

**Comment by Gaz492** [comment]
Confirmed this to still be an issue and attached the kubejs log
[startup.log](https://github.com/user-attachments/files/15547118/startup.log)

**Comment by Gaz492** [comment]
This issue should be resolved now
