### ISSUE TITLE
[Bug]: Oceanblock TEst Category 

### ISSUE THREAD

**Issue by Officialy** [FTBTeam/FTB-Modpack-Issues#477]
### Modpack

FTB Oceanblock

### Modpack version

1.10.1

### Describe the bug

Players have access to the "TEst" category, which can give them an OP item as a quest reward. The player doesn't need to be opped either

### Steps to reproduce

Open a new instance of oceanblock 1.10.1, view the quests and see the TEst catagory.

### Expected behaviour

This category not to exist

### Screenshots

https://i.imgur.com/2gRl60E.png
https://i.imgur.com/LWALHHp.png
https://i.imgur.com/WDNubzx.png

**Comment by Sunekaer** [comment]
duplicated
