### ISSUE TITLE
Reaper Generator recipe

### ISSUE THREAD

**Issue by Naschen** [FTBTeam/FTB-Modpack-Issues#4777]
### Modpack

FTB Skies Expert

### Modpack version

1,1,0

### Describe the bug

The recipe in JEI doesn't work and results in materials burning and disappearing in the soul fire.

### Steps to reproduce

1. have soul engulfing setup
2. throw soul steel block into the soul fire
3. Watch as soul steel block burns and disappears.

### Expected behaviour

soul steel generator should turn into Reaper Generator

**Comment by MrSelenix** [comment]
I got caught out with that myself. Double check the recipe, it calls for **Compressed Soul Powder Blocks** not the normal soul powder used in the larger engulfing setup

**Comment by Naschen** [comment]
ah, I see it now.
It's called Soul engulfing and appears on the surface to be the same as all the other soul engulfing recipes, but isn't and uses a different structure.
I'd personally question why it should be that way as it seems like poor design to me, unless the intention is to troll people. Even then.
