### ISSUE TITLE
[Bug]: Epic/Ultimate Backpack crashes the game on first open. Game log says something like "Backpack migrated" then crash.

### ISSUE THREAD

**Issue by psperneac** [FTBTeam/FTB-Modpack-Issues#478]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Log Files

https://pastebin.com/Uxwsx7H3

### Describe the bug

Had an Epic backpack, full around 2/3 (out of 99). Upgraded game, opened backpack game crashed. Restarted game, upgraded backpack to Ultimate, opened, same thing

### Steps to reproduce

1. Make Epic or ultimate backpack in 1.0.9
2. Fill with things
3. Upgrade game to 1.11.0
4. Open backpack

### Expected behaviour

To not crash game

**Comment by psperneac** [comment]
You might be right, I think I upgraded the backpack and never opened it then went offline.

**Comment by Flanks255** [comment]
was this in single player or multiplayer? if single, the items "should" be safe... i think... im pushing a fix to github to build right now...

**Comment by psperneac** [comment]
single player. items not important but once it's out I'll tell you if they survived,

**Comment by Flanks255** [comment]
i fixed "new" occurrences of it from happening, then remembered i need to fix ones already bugged, so its building again...

**Comment by Flanks255** [comment]
try this: https://www.curseforge.com/minecraft/mc-mods/simply-backpacks/files/3566909

**Comment by psperneac** [comment]
Worked! Items were retained. Much appreciated.

**Comment by Raidobw2** [comment]
Wow thanks a lot Flanks, that was quicker work than I could dispatch it :^) lightning fast!!!
