### ISSUE TITLE
Liquid Crystallizer Consumes Infinite Mana

### ISSUE THREAD

**Issue by whatamike** [FTBTeam/FTB-Modpack-Issues#4780]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

When a mana spreader is pointed at a liquid crystallizer, all mana from the adjacent mana pool(s) will be consumed and sent to the liquid crystallizer whether or not it is processing anything or even has rotational force applied to it.

### Steps to reproduce

1. Place a Liquid Crystallizer in the world
2. Place a mana pool with mana nearby
3. Place a mana spreader adjacent to the mana pool
4. Using the wand of the forest, bind the mana spreader to the liquid crystallizer

### Expected behaviour

The mana consumption of the liquid crystallizer is similar to a runic altar, only consuming mana during processing.

**Comment by Saereth** [comment]
This is not the case, I've verified it does not consume mana when recipes are not running. It has a very large internal buffer however, an entire mana pool so it will keep storing mana as long as its not full and you have a lense pointed at it.

We're going to reduce the internal buffer in the future which should help

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/d1cb7317-5d85-49ca-aa30-02839dc3df15
