### ISSUE TITLE
Server crashing when players approach certain village types

### ISSUE THREAD

**Issue by Hanoverfist** [FTBTeam/FTB-Modpack-Issues#4782]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

When flying to villages =some cause the server to hard lock. Process must be killed and server restarted. This does NOT occur in singleplayer. I suspect NBT issues with a schematic?? Ofc one of our server mods could be responsible too.

### Steps to reproduce

1) Use /locate structure skyvillages:skyvillage
2) Fly to village coords

### Expected behaviour

Server wont crash

### Screenshots

Coords of village and level seed:
https://imgur.com/3V3uDp6

**Comment by Saereth** [comment]
I cant reproduce this on my server with current coordinates and seed, can you please provide a crash log

**Comment by Hanoverfist** [comment]
Ok, sorry to waste your time on this. I traced this back to the Canary mod. Currently sorting through which mixin  is causing it.

**Comment by Saereth** [comment]
ok cool thanks
