### ISSUE TITLE
Super Cooler automation not possible

### ISSUE THREAD

**Issue by Hazmatik** [FTBTeam/FTB-Modpack-Issues#4783]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

Trying to automate the super cooler block to produce raw silver, but once the first slot fills with mana powder from a hopper then the next slot starts to fill with it as well and then the machine doesn't produce the final result. The progress bar fills up but then stops at the end until you remove all the items in any slots other than the 1st one. It would be nice if there was a recipe selection or if it would still produce the item that uses a single item if all 3 slots have that item in it.

### Steps to reproduce

Hopper in mana powder to the super cooler until it starts filling the 2nd slot
Watch machine stop producing output.

### Expected behaviour

Only slot 1 fills up or the machine just continues to craft

**Comment by ArtpokeBr** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/44851727/fd9227f7-a0a8-448a-aab3-9efed66db736)
Kinda Interesting as the recipe only stops when the second slot is filled with mana powder... By using any other block/item as a filler the recipe works normally. 🤔

**Comment by Saereth** [comment]
we can pretty much address this by adding recipes that produce more but require 2/3 item slots filled. Alternatively you can pretty easily automate it still with an item translocator set to regulate

**Comment by Saereth** [comment]
you can actually just automate this with an item transporter set to regulate mode so im closing this
