### ISSUE TITLE
(Pedestals Mod) Planter Pedestal stops when reaching a block in its workflow that prevents placing a new crop/sapling.

### ISSUE THREAD

**Issue by kmadstarh** [FTBTeam/FTB-Modpack-Issues#4786]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0

### Describe the bug

If the Planter Pedestal encounters a a block coordinate in its given work area where it is unable to place a crop/sapling, it simply stops working until that coordinate is eligible for planting again.

### Steps to reproduce

1. Set up a planter pedestal with work area
2. Supply planter with saplings/crops
3. Place another sapling or crop (or other block entirely) in the path of the planter's workflow
4. Planter stops working until the space is cleared.

### Expected behaviour

Planter skips over blocks in its work area that prevent it from planting.

### Additional information

This particular issue has been fixed in the most recent version of Pedestals, released on [21 Feb 2024](https://www.curseforge.com/minecraft/mc-mods/pedestals/files/5126589).

**Comment by Saereth** [comment]
v1.2 already has this update
