### ISSUE TITLE
Desh Space Plating recipe not working

### ISSUE THREAD

**Issue by Bamfut** [FTBTeam/FTB-Modpack-Issues#4787]
### Modpack

FTB Skies Expert

### Modpack version

1.2.1

### Describe the bug

The Desh Space Plating recipe in the Quantum Assembler doesn't work.

### Steps to reproduce

1. Make a Quantum Assembler
2. Input the correct items for Desh Space Plating

### Expected behaviour

The Quantum Assembler should produce Desh Space Platings

### Screenshots

![JEI](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/90445342/ebf9dd67-89e3-435a-a240-c78f34c975e6)
![Screenshot 2024-02-28 164257](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/90445342/3385a66b-fc7d-440e-aae8-f1562ed4ffd3)

### Additional information

The Quantum Assembler multiblock works, I tested it with other recipes.
People on the official discord told me that the recipe needs molten cheese, but that cant be inserted into the Quantum Assembler. Might have todo something with this pachnote from 1.2.0? "Quantum assembler no longer requires fluids in specific slots and will now type lock several specific fluids to specific slots to aid in automation"

**Comment by vencordplus-a** [comment]
it seems like they forgot to add molten_cheese into quantum assembler fluid slots, if you dont want to wait you can go into 
ModpackFolder/kubejs/data/ftbskies/machines/quantum_assembler.json, open the json file and edit the part 

```
    {
      "type": "custommachinery:fluid",
      "id": "inputtank6",
      "capacity": 4000,
      "maxInput": 1000,
      "maxOutput": 1000,
      "mode": "input",
      "whitelist": true,
      "filter": ["minecraft:water",
      "minecraft:lava"]
    },
```

into

```

    {
      "type": "custommachinery:fluid",
      "id": "inputtank6",
      "capacity": 4000,
      "maxInput": 1000,
      "maxOutput": 1000,
      "mode": "input",
      "whitelist": true,
      "filter": ["minecraft:water",
      "minecraft:lava","ftbskies:molten_cheese"]
    },
```

(basically assigning tank number 6 into liquid cheese)

**Comment by vencordplus-a** [comment]
imo 6th tank would be better since fluix crystals are made on the 5th one, from what I seen theres nothing that uses 6th tank atm
