### ISSUE TITLE
Can't progress after update (Ars Nouveau)

### ISSUE THREAD

**Issue by ssDko** [FTBTeam/FTB-Modpack-Issues#4789]
### Modpack

FTB Skies Expert

### Modpack version

1.2.1

### Describe the bug

I just updated my instance of the pack to 1.2.1.  The changes did give me some new quests to complete, but some of the quests I had already completed are now locked behind other quests that either wont unlock them selves or will not complete.  Despite the quest dependencies being completed.
The quests in question are;
 -Sourcestone: I have completed Source Gem, and I have crafted Sourcestone. Removing it and readding to my inventory does nothing.
-Sourcelinks: I have a Vitalic Sourcelink but even with it in my inventory I can't submit the quest for completion.  The same dependency is completed
-Source Jar: This quest doesn't even unlock to allow completion even though I have completed Archwood Saplings.

### Steps to reproduce

Update to 1.2.1 while in the middle of these quests.

### Expected behaviour

I should be able to complete these quests

### Screenshots

![QuestIssue1](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10103014/2adce6df-9a90-424f-a651-e63cb10e5c36)

**Comment by Saereth** [comment]
there are other pre-requisites now you'll have to go back and complete

**Comment by ssDko** [comment]
> there are other pre-requisites now you'll have to go back and complete

Are some of the pre-reqs not listed on the quests them selves? Because as far as what they specifically tell me I need, I have them all.

**Comment by Saereth** [comment]
> > there are other pre-requisites now you'll have to go back and complete
> 
> Are some of the pre-reqs not listed on the quests them selves? Because as far as what they specifically tell me I need, I have them all.

They can be deep pre-requistes and not all nescesarily related either, had someone else on discord having this issue and they needed to go complete the task on the reaper gen, thats basically it though just going to be some new updated task that needs to be addressed

**Comment by Saereth** [comment]
> > there are other pre-requisites now you'll have to go back and complete
> 
> Are some of the pre-reqs not listed on the quests them selves? Because as far as what they specifically tell me I need, I have them all.

yeah exactly and thats the issue people ran into, some of them are unrelated but going back to complete them fixes it. For someone in discord today it was the reaper gen quest. I believe this was caused by some redundant quests being removed and shuffling the quest ids
