### ISSUE TITLE
The recipe for orechid is incorrect

### ISSUE THREAD

**Issue by AT080702** [FTBTeam/FTB-Modpack-Issues#4797]
### Modpack

FTB Arcanum Institute

### Modpack version

1.18.2

### Describe the bug

I’m following the recipe given in the Lexica Botania for Orechid but for some reason it doesn’t work.

### Steps to reproduce

Go to petal apothecary, drop in 1x rune of mana, 2x mystical red petals, 2x gray petals, 2x green, 2x yellow. Which doesn’t come up as a valid recipe, when you drop in seeds

### Expected behaviour

I expected it to craft an orechid as the recipe given to me stated

**Comment by KajeTheCat** [comment]
Just tested this in my world and it seems to work correctly, are you sure you put in 2 of each petal? the proper rune? did you try throwing seeds in to see if it would finish the recipe regardless?

**Comment by TheonlyTazz** [comment]
cannot replicate
