### ISSUE TITLE
Can't craft rose quartz 

### ISSUE THREAD

**Issue by lekleekleeek** [FTBTeam/FTB-Modpack-Issues#4799]
### Modpack

FTB Skies Expert

### Modpack version

1.2.2

### Describe the bug

I'm trying to progress through the mod, but to accomplish this I would need to craft a Create’s Deployer, using a Polished Rose Quartz. In order to achieve the polished, it is needed a regular Rose Quartz, which is only available using a Mekanism’s Metallurgic Infuser, but in order to do the Metallurgic Infuser, it is needed the Polished Rose Quartz. Usually, there is a craft recipe for the Rose Quartz, which seems to be missing in the modpack. 

### Steps to reproduce

1. Go to the Create’s deployer recipe;
2. Go to the Rose Quartz recipe; 

### Expected behaviour

I expected to be able to craft the regular Rose Quartz, which seems not possible for now.

### Screenshots

![2024-02-29_16 01 40](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/161760596/7ea6752b-3faa-4da3-a078-0aab93c007e1)
![2024-02-29_16 01 44](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/161760596/34fc4629-8af6-4ce7-8a62-0a6a8a18a15e)
![2024-02-29_15 59 29](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/161760596/4c6872d5-5002-4652-b261-0748fc80ce05)

**Comment by Saereth** [comment]
you dont need rose quartz for a deployer

**Comment by Dacktar13** [comment]
> you dont need rose quartz for a deployer

Looking a the deployer recipe, it is requiring rose quarts.

This needs re-opening

**Comment by Dacktar13** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/3123519/5b97a1b9-0c9a-45d0-bcaf-e94795b5c5e7)
