### ISSUE TITLE
Raw Ostrum Ore recipe was moved from Pink lens to Purple lens.

### ISSUE THREAD

**Issue by UltraGameCoder** [FTBTeam/FTB-Modpack-Issues#4800]
### Modpack

FTB Skies Expert

### Modpack version

v1.2.2

### Describe the bug

Before the v1.2.2 update, Raw Ostrum Ore was obtained by the laser drill using a Pink lens (which requires to obtain your first Raw Ostrum Ore) but in this v1.2.2 version, its drop was moved to the Purple Lens that already obtains Ether Gas.
Is this intentional or a mistake?
The Pink Lens serves no purpose now in v1.2.2.

### Steps to reproduce

1. Check Pink Lens usage in v1.2.1
2. Check Purple Lens usage in v1.2.2

### Expected behaviour

Raw Ostrum Ore should come from Pink Lens

**Comment by Saereth** [comment]
no we just put it back to mod defaults so this is how it ships with compat from ad astral gisel addon, inlcuding the planetary biomes to mine it
