### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by HrisStehtAufThighs** [FTBTeam/FTB-Modpack-Issues#4801]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

Always when a Industrial Foregoing machine gets placed the Server crashes 

### Steps to reproduce

1. just place for example the tree fluid extractor (on Server)

### Expected behaviour

No server crash, but it crashed

**Comment by Gaz492** [comment]
Would you be able to upload a crash report for us to take a look at?
