### ISSUE TITLE
soul engulfing fire ponder shows wrong t4 structure

### ISSUE THREAD

**Issue by pikminman13** [FTBTeam/FTB-Modpack-Issues#4802]
### Modpack

FTB Skies Expert

### Modpack version

1.2.2

### Describe the bug

the ponder for the t4 spirit structure shows the outer towers being one block too far from the center than they should be

### Steps to reproduce

view its ponder and compare to schematic/functional setup

### Expected behaviour

correct setup

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/30882377/c50dfaf4-4a39-4c90-b9c8-aee104f899ae)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/30882377/13c23128-7d36-4743-ad3a-5661c79dad8a)

**Comment by gman4161** [comment]
Can confirm. The pillars at the edge are supposed to be 1 block closer. So 2 blocks between the pillars and the main structure, not 3 for anyone else looking to solve this problem
