### ISSUE TITLE
Missing recipe for @CobbleForDays

### ISSUE THREAD

**Issue by AzurePenguinWithIcyWings** [FTBTeam/FTB-Modpack-Issues#4804]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

none recipe was appeared when search for cobble gen tier 2-5

### Steps to reproduce

1. open REI or quest book
2. click on cobble gen tier 2-5
3. and none was appeared(sorry for my grammar)

### Expected behaviour

Expected a recipe for tier 2-5

**Comment by AzurePenguinWithIcyWings** [comment]
onEvent("recipes", (event) => {
  event
    .shaped("cobblefordays:tier_1", ["RRR", "WGL", "RRR"], {
      W: "minecraft:water_bucket",
      L: "minecraft:lava_bucket",
      G: "minecraft:glass",
      R: "ftbstoneblock:1x_compressed_stone",
    })
    .id("cobblefordays:tier_1");

  event.recipes.tconstruct
    .casting_basin({
      cast: Item.of("cobblefordays:tier_1").toJson(),
      cast_consumed: true,
      fluid: {
        name: "tconstruct:seared_stone",
        amount: 4000,
      },
      result: "cobblefordays:tier_2",
      cooling_time: 100,
    })
    .id("cobblefordays:tier_2");

  event.recipes.tconstruct
    .casting_basin({
      cast: Item.of("cobblefordays:tier_2").toJson(),
      cast_consumed: true,
      fluid: {
        name: "tconstruct:molten_iron",
        amount: 3240,
      },
      result: "cobblefordays:tier_3",
      cooling_time: 100,
    })
    .id("cobblefordays:tier_3");

  event.recipes.tconstruct
    .casting_basin({
      cast: Item.of("cobblefordays:tier_3").toJson(),
      cast_consumed: true,
      fluid: {
        name: "tconstruct:molten_gold",
        amount: 3240,
      },
      result: "cobblefordays:tier_4",
      cooling_time: 100,
    })
    .id("cobblefordays:tier_4");

  event.recipes.tconstruct
    .casting_basin({
      cast: Item.of("cobblefordays:tier_4").toJson(),
      cast_consumed: true,
      fluid: {
        name: "tconstruct:molten_diamond",
        amount: 3600,
      },
      result: "cobblefordays:tier_5",
      cooling_time: 100,
    })
    .id("cobblefordays:tier_5");
});

even though there is a code, it didn't show up on REI

**Comment by AYtsukue** [comment]
I have the same problem, and find out that the recipe will show up when you finish the tic3 items in quests (like smeltery)

**Comment by opplaypro** [comment]
there is a simple solution:
open REI settings (at the bottom, next to search bar)  --> go to advanced  --> press "Reload Plugins" button
