### ISSUE TITLE
FTB Skies Expert will not complete Soul Steel Ingot

### ISSUE THREAD

**Issue by SgtKrazy** [FTBTeam/FTB-Modpack-Issues#4805]
### Modpack

FTB Skies Expert

### Modpack version

1.2.2

### Describe the bug

Can not complete Soul Steel Ingot. Per the dependency to complete this quest in Occultism the otherstone is needed to be completed only. With that quest completed and displaying a green check mark. Soul Steel Ingot displays as a grey check mark and will not complete. Attached image showing the issue.

### Steps to reproduce

1. Go to Mastering the Occult
2. Complete Quests down to Otherstone
3. Then complete Soul Steel Ingot once that is completed this quest stays as a grey check mark.

### Expected behaviour

With only the Otherstone quest being the only requirement Soul Steel Ingot should complete with green check mark

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/21181138/38453cc3-2bb3-4045-b99d-4881860732fd)

**Comment by Saereth** [comment]
you are missing task dependencies in other questlines, you'll have to go searching to see which you havent completed yet

**Comment by Ton841152** [comment]
Hey, I got the same problem as you, I wonder what quest that needed to be completed in order to complete soul steel quest.
