### ISSUE TITLE
Protection of the Castle in the Sky

### ISSUE THREAD

**Issue by KuroPeach** [FTBTeam/FTB-Modpack-Issues#4806]
### Modpack

FTB Skies Expert

### Modpack version

v1.2.1

### Describe the bug

This will cause frequent screen refreshes in the server background and unlimited scripts. It is recommended that when the player is in this structure, the player is given the native buff of this structure, which has the ability to prevent destruction.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/19620848/0ca3a2fc-2ff9-4b5d-804b-732c69851fc7)

### Steps to reproduce

When fake players destroy blocks, and when abnormal tools destroy blocks

### Expected behaviour

fix it

**Comment by Saereth** [comment]
no this doesnt work sadly because for whatever reason the mod dev hard coded the dimension check to the buff to be minecraft:overworld. I asked them to expand it but they havent.
