### ISSUE TITLE
FTB Genesis Applied energistic 2 auto craft bug when multiple item

### ISSUE THREAD

**Issue by ph1823** [FTBTeam/FTB-Modpack-Issues#4807]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Log Files

https://pste.ch/fetoqijivi.md

### Describe the bug

When we try to craft a item with more one stack, applied energistic refused this.
But in modular storage that work.

You can check the video if you want

### Steps to reproduce

1. Try to craft MV transfomer with copper cable in applied
2. Try to make a pattern of MV Transformer with copper cable
3. Try to craft this in Modular Storage: that work

### Expected behaviour

Craft work

### Screenshots

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8150089/0a03c8d9-f209-4ee6-b25c-7c51b384427f

**Comment by ArtpokeBr** [comment]
Probably another Limitation with AE2 unfortunatly =/
