### ISSUE TITLE
Duplication copper cable when craft mv transformer

### ISSUE THREAD

**Issue by ph1823** [FTBTeam/FTB-Modpack-Issues#4808]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Log Files

https://pste.ch/elebucumup.md

### Describe the bug

When i try craft MV Transformer from modular storage, my inventory has full (just 3 empty slot) and i craft 16 MV Trasnformer, my copper cable has duplicate on my the ground.
In my storage i have 90 copper cable and after pick up item on the ground i get more 400 (i have delete a lot of copper cable)

### Steps to reproduce

1. try craft mv transformer
2. craft with inventory full
3. craft 16 mv transformer with full invetory

### Expected behaviour

no duplicate

### Screenshots

![2024-03-01_10 49 51](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8150089/c5a7b93d-ee72-42a0-8bc5-380e558861c0)

Video of reproduction

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8150089/d04631f9-efc4-4b77-a92a-b9860488b889

**Comment by ArtpokeBr** [comment]
Yeah... I'll have to remove all Stacked Recipes.
