### ISSUE TITLE
[Suggestion]: Change internal inventory size of Auto Hammers / Breaking Compressed 3x into Compressed 3x

### ISSUE THREAD

**Issue by odog221** [FTBTeam/FTB-Modpack-Issues#481]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

It is related to a "potential problem".  The Auto Hammers have an huge internal inventory.  In our server, I broke one with 20k+ blocks, and visual glitches instantly occurred.  This is not a current problem, but could potentially lead to an issue later one.  I have to potentially solutions to this, as this huge internal inventory also makes linear flow systems almost impractical.

Reduce Internal inventory of Auto Hammers to some multiple of 192, preferably maybe 8x this number.

Make it so Compressed Cobble hammers into Compressed Gravel etc etc and reduce Auto Hammer inventory size to 64.

### Mod suggestion

Reduce Internal Inventory : This is probably the quickest and easiest change to be made and would be low effort.  I understand the reasoning behind the extremely high inventory size is due to the fact that 3x Compressed blocks break into 192, and this large inventory size makes sense in that context.  However, I believe this is unnecessary, as ideally blocks would be flowing into and out of the Auto Hammer, and it would not need to be constantly ran and accumulate such a high number of blocks.  The argument against this is creating inefficient set ups, but in reality, the flow rate of these machines would not change.

Change Compress Block Hammering : By changing the way hammering compressed blocks works, so it is hammered into the equivalent next step compressed block (3x Cobble into 3x Gravel etc), we reduce the need for the large inventory size inside the Auto Hammers, and additionally make the machines more efficient, reducing the number of ticking blocks.  This occurs because it would reduce the need for multiple assemblers/crafters needed to recompact the blocks. This way, only one step is needed to uncompact them when preparing to auto sieve, and compact at the beginning to insert into the linear Auto Hammer line. The argument against this is that it would create more ticking blocks in these assembly lines, but however, it will become equivalent, or more likely, reduce the number of ticking entities.  Currently, when wanting to bulk store or quickly hammer a lot of material, a crafter/assembler is needed at every step of the process, but with this change, a crafter/assembler would only be needed at the first stage, and at the last stage.

Thank you, 
𝓓𝓸𝓬𝓢𝓬𝓸𝓽𝓽 𝟙𝟠#2076 (Discord Handle)

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
