### ISSUE TITLE
Circuit Craftings are a bit frasturating

### ISSUE THREAD

**Issue by vencordplus-a** [FTBTeam/FTB-Modpack-Issues#4811]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

Next level circuit craftings like advanced,ultimate and enderium recipes are ridicilous

I understand that we need to automate or actually passive this stuff but needing 2 stacks of basic circuits just to make 1 ultimate circuit or 
8 basic just to craft one elite is a bit extreme in my opinion

just leaving it as suggestion

**Comment by Saereth** [comment]
We are looking at feedback from other people around this stage as well to make adjustments where needed. We're definitely going to lower the craft time of elites and probably a few other changes. This is definitely something we have our eye on so I appreciate the feedback
