### ISSUE TITLE
Reaper Generator has small maximum buffer

### ISSUE THREAD

**Issue by Timmy3921** [FTBTeam/FTB-Modpack-Issues#4814]
### Modpack

FTB Skies Expert

### Modpack version

1.2.2

### Describe the bug

The Reaper Generator has a maximum buffer of 4.8k FE, instead of the 1M FE shown in its UI.

### Steps to reproduce

1. Activate a Reaper Generator and have it accumulate at least 4.8k FE.

### Expected behaviour

The Reaper Generator should have a maximum buffer of 1M FE.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/112140369/c606c19e-4cc0-4ef1-84dd-12140fbf1073)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/112140369/03e619ef-e84d-452a-b937-46950b479e34)

**Comment by Saereth** [comment]
the 4800 buffer is correct, the 1M is a display bug I've reported

**Comment by jhymni** [comment]
Is the reficiat rune useless, then? Seeing as it increases generation to 9600lightnings/heart

**Comment by Saereth** [comment]
for now yes, it should increase the buffer with the rune, I've reported it to the dev to resolve

**Comment by Timmy3921** [comment]
Do you know what the expanded buffer should be?

**Comment by khaskelbergTAU** [comment]
Looking at the configs - the buffer of the generator should be 50000, not 4800. Tested with Reaper mod alone, when config is changed to the same parameters everything works fine. Unless im testing something very wrong, this seems to be an issue with this modpack, not with the mod.

**Comment by khaskelbergTAU** [comment]
After checking - this is an issue with how the reaper mod read its configs. I have fixed it and created a pull request in the mod's repository, hopefully this gets patched.
