### ISSUE TITLE
Villager trades still broken in FTB Skies

### ISSUE THREAD

**Issue by thomasaronford** [FTBTeam/FTB-Modpack-Issues#4816]
### Modpack

FTB Skies

### Modpack version

1.4.1

### Describe the bug

There are still broken trades for (new) villagers, such as 1 paper -> 1 emerald, or the fact that looting 3 is vastly overrepresented in the trade pools (around 1/3 refreshes gives looting, to a more ridiculous around 1/200 gives me an efficiency book)

### Steps to reproduce

1. Get a new villager into an easyvillagers trader w/ lectern
2. Cycle through trades

### Expected behaviour

Lower levels of looting should be available in trade pool and looting should not be so common. Paper trades should not be 1-1

**Comment by Saereth** [comment]
fixed the paper trade to be 1 to 16 but the looting enchant is just a product of how trades work with mc, cant set a rarity on it
