### ISSUE TITLE
all flowers have duplication tooltip

### ISSUE THREAD

**Issue by pikminman13** [FTBTeam/FTB-Modpack-Issues#4817]
### Modpack

FTB Skies Expert

### Modpack version

1.2.2

### Describe the bug

all botania flowers show that they can be duplicated in their tooltip, but only mystical flowers should

### Steps to reproduce

jei, hover over flower, hold shift

### Expected behaviour

no tooltip for flowers it does not work on

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/30882377/c4dbb5c9-965d-41fc-9a10-a0e4f0304cd6)

**Comment by Saereth** [comment]
bug with the mod, it's been reported but I cant remove those tooltips hard coded by the mod
