### ISSUE TITLE
Cataclysm structures

### ISSUE THREAD

**Issue by CactusDuper** [FTBTeam/FTB-Modpack-Issues#4823]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

Cataclysm structures should be added back to the end dimension (Ruined Citadel). They should also be added to the tropical dimension (Sunken City, Ancient Factory).

**Comment by Saereth** [comment]
doing something else for the cata custom content so we wont add them back in as standard versions
