### ISSUE TITLE
Can't start the launcher

### ISSUE THREAD

**Issue by JoachimBody** [FTBTeam/FTB-Modpack-Issues#4824]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Log Files

[2024-03-02-4[1].log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14470356/2024-03-02-4.1.log)

### Describe the bug

Just downloaded the pack and it simply dont want to boot. I tried earlier versions and also tried installing java on my own. But still it doesnt boot.

### Steps to reproduce

1. Download the pack
2.  Start it
3. You got error

### Expected behaviour

Booting minecraft as normal

### Screenshots

![obraz_2024-03-02_191038069](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/123320984/ff2d2882-ebcc-4c31-aa39-d501b4ba854f)

**Comment by Gaz492** [comment]
It looks like your graphics drivers may be out of date, the crash you are running into is commonly seen when your graphics drivers are out of date or if you are on a laptop with an integrated graphics and a dedicated graphics card, the modpack may be using the wrong graphics card.

To begin with, we recommend making sure that your graphics drivers are up-to-date by downloading the latest drivers from the manufacture's website.
