### ISSUE TITLE
The hammer(@FTB Skyblock Addons)won't crush cobble/gravel or something

### ISSUE THREAD

**Issue by Vanthoven** [FTBTeam/FTB-Modpack-Issues#4830]
### Modpack

FTB Skies Expert

### Modpack version

ex. 1.2.2

### Describe the bug

![656ca25165467d72a55fa914d1c9f867](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/162000776/641f182a-7c96-4169-aae7-440ed9ce6090)

Anyone got the problem like me?

### Steps to reproduce

1.Create a stone hammer
2.try to crush some cobble and,just don't work

### Expected behaviour

cobble should be crushed into gravel

### Screenshots

![656ca25165467d72a55fa914d1c9f867](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/162000776/896740e8-b125-4f16-b10e-d2a954fec8df)

### Additional information

    cant crush anything so my quests cant go on...

**Comment by Saereth** [comment]
there is something wrong with your installation, you need to reinstall. When lookint at cobble and holding the hammer if things are working you'll see an icon showing what it will crush into like this
<img width="985" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/8c0d6cc5-fa03-4919-8ff4-37cd0e5935d1">
Verified working. If you reinstall and still have an issue open a new issue and provide your latest.log please

**Comment by Vanthoven** [comment]
> 你的安装有问题，需要重新安装。当查看鹅卵石并握住锤子（如果一切正常）时，您会看到一个图标，显示它将压碎成什么，就像这样 已验证的工作。如果您重新安装后仍然存在问题，请打开一个新问题并提供您的最新日志 <img alt="图像" width="985" src="https://private-user-images.githubusercontent.com/9200909/309529519-8c0d6cc5-fa03-4919-8ff4-37cd0e5935d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTM2MzQsIm5iZiI6MTcwOTQ1MzMzNCwicGF0aCI6Ii85MjAwOTA5LzMwOTUyOTUxOS04YzBkNmNjNS1mYTAzLTQ5MTktOGZmNC0zN2NkMGU1OTM1ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDNUMDgwODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmIxY2VlMTZmOTFkOGZkN2E5ZTgxODQ3MmUxN2YwMjZhZWZkZTQ1MmI2YWQ3MDcyMTMzZGUzODQ4MDFkNTliMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N-3qspz4RYEL2R_nNknFqIvdUMMzi2ixLT3T5cAkdsk">

thanks,this problem has been solved after i reinstall the game.

**Comment by Vanthoven** [comment]
> there is something wrong with your installation, you need to reinstall. When lookint at cobble and holding the hammer if things are working you'll see an icon showing what it will crush into like this <img alt="image" width="985" src="https://private-user-images.githubusercontent.com/9200909/309529519-8c0d6cc5-fa03-4919-8ff4-37cd0e5935d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTM3MjUsIm5iZiI6MTcwOTQ1MzQyNSwicGF0aCI6Ii85MjAwOTA5LzMwOTUyOTUxOS04YzBkNmNjNS1mYTAzLTQ5MTktOGZmNC0zN2NkMGU1OTM1ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDNUMDgxMDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDkxYzFkMjlkMTFhOGE4ZTYxNmIwNjcxN2UzM2VhZmNhYTY3MTMyNGM2N2IzZjY2YjgxN2U0MDU3ZDA1YmNjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sgun209p4muhjWp3VCjskG71StVvy6VeiVcvVw8waw8"> Verified working. If you reinstall and still have an issue open a new issue and provide your latest.log please

thanks, this problem has been solved after i reinstalled my game.
