### ISSUE TITLE
We need faster thermal machines, they're too slow

### ISSUE THREAD

**Issue by KuroPeach** [FTBTeam/FTB-Modpack-Issues#4831]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

We need faster thermal machines, they're too slow

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/thermal-endergy

**Comment by Saereth** [comment]
we could add this yeah, will have to be next update though as the augments will need recipe tweakss
