### ISSUE TITLE
no mods loaded

### ISSUE THREAD

**Issue by firestrike772** [FTBTeam/FTB-Modpack-Issues#4832]
### Modpack

FTB Skies

### Modpack version

1.4.1

### Describe the bug

There are no mods loading when i launch ftb skies 

### Steps to reproduce

1.start ftb skies
2.no mods load

### Expected behaviour

i want the mods to launch

### Additional information

no additional information

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the instance so we can take a look at them?
https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
