### ISSUE TITLE
FTB Skies 1.4.1 Server dowload for x64 linux

### ISSUE THREAD

**Issue by wildkurt** [FTBTeam/FTB-Modpack-Issues#4836]
### Modpack

FTB Skies

### Modpack version

1.4.1

### Log Files

From my Bitdefender antivirus:
_The file \\192.168.107.102\SANDISK\FTBSkies\Unconfirmed 124060.crdownload is infected with Trojan.Linux.Agent.XRK. Bitdefender blocked this item, your device is safe._

### Describe the bug

Every time I try and download this file it is stopped by my anti-virus program. I am on a Windows 11 machine using it to download the server files into a shared directory on my Linux Mint computer. 

### Steps to reproduce

Either through the Overwolf FTB App or the FTB web site:
1. Select the Linux x64 download
2. Select download folder
3. Okay
4. Then Anti-virus quarantines the file saying there is a virus

### Expected behaviour

I expected the shell script to download virus free

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/35972430/f321ca31-2fd1-42aa-aea2-73f8e070131f)

**Comment by Gaz492** [comment]
This is a false positive, you can view the source code for the server installer at https://github.com/CreeperHost/modpacksch-serverdownloader/
