### ISSUE TITLE
[Bug] Crash: Tessellating CCL block in world (Plus in-game log errors)

### ISSUE THREAD

**Issue by InQuognito** [FTBTeam/FTB-Modpack-Issues#484]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Log Files

[Log w/ Crash](https://paste.ee/p/2Yyoo)

### Describe the bug

Game just crashed when I loaded in the game after turning the config setting 'B:"catchBlockRenderExceptions"=false' in the CCL config menu to get rid of the annoying config messages. Then I loaded in and the game just crashed once joining the world. Before turning this message off, I was recieving consistent in-game messages stating an exception was thrown and CCL was not rendering a block.

### Steps to reproduce

1. Launch the game? Happened without any modifications unless you include resource packs, but those aren't server-side.

### Expected behaviour

Not crashing or not rendering blocks, I suppose?

**Comment by TheonlyTazz** [comment]
Issue has gone stale, if this issue is still relevant, feel free to reopen (or create a new issue)
