### ISSUE TITLE
mod suggestion

### ISSUE THREAD

**Issue by Haruto19** [FTBTeam/FTB-Modpack-Issues#4840]
### Modpack

FTB Arcanum Institute

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai

this a magic mod that adds it's own mana system and quite a good amount of fun spells and weapons to use, and it can be rebalanced easily with the use of configs. i want this mod in simply because i like it quite a lot and don't see it used as much as i would like in modpacks like these.

**Comment by TheonlyTazz** [comment]
Sadly Arcanum Institute is not going to get more Content Mods added.

Maybe we will include it in a future Project
