### ISSUE TITLE
No way to disable enderman spawn event.

### ISSUE THREAD

**Issue by Penumbra97** [FTBTeam/FTB-Modpack-Issues#4841]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

I just started a world and enderman are spawning like crazy. It says "a strange creature seems to be observing you". It happens like once every minute and there does not appear to be a way to disable that event.

**Comment by Saereth** [comment]
kill them, once you get your first pearl they will stop bothering you

**Comment by Penumbra97** [comment]
Ah, got it. I just figured that out. Thanks!
