### ISSUE TITLE
Visual screen chop

### ISSUE THREAD

**Issue by andrewgabbert** [FTBTeam/FTB-Modpack-Issues#4842]
### Modpack

FTB Presents F.A.M

### Modpack version

1.0.0

### Log Files

[logs FTB.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14474605/logs.FTB.zip)

### Describe the bug

![Client VView](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/80989326/4529eb3d-a21c-4ae8-8a45-bd6878f65ce1)
Game looks like this when opening, can't figure out why. Persists through all opening screens. I've tried moving the instances between drives, uninstalling/reinstalling, reinstalling Java, restarting computer, etc. Problem is persistent in FTB Genesis and University as well. I was thinking maybe a problem with OpenGL integration? I got the Microsoft app for it. 

### Steps to reproduce

Unknown. probably something with my computer?

### Expected behaviour

To be able to see the screen

### Screenshots

![Client VView](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/80989326/29a4c8fa-64c6-4242-a138-061e38ec34f0)

### Additional information

Modpacks worked when I played a few months ago (back with FTB Presents Abepack).

**Comment by andrewgabbert** [comment]
Direwolf20 starts working fine, but then glitches out after the xycraft:core rule appears in the bottom left of the screen.

**Comment by andrewgabbert** [comment]
![Screenshot 2024-03-03 152856](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/80989326/45f3014a-70bf-4e2b-9485-905d1cfba4d6)
Screenshot of Direwolf loading screen

**Comment by andrewgabbert** [comment]
Directly after the above loading screen, it chops off similar to the first screenshot

**Comment by manmaed** [comment]
Looks like a graphics card issue try resetting it? see if that solves  the issue

**Comment by andrewgabbert** [comment]
I've tried that and even tried resetting my PC, wiping files. I use NVIdia Geforce graphics drivers. I'm running it on a gaming laptop connected to separate monitors. When I open it on the laptop alone, the game instantly crashes. When I open it on the other monitors with my laptop closed, the game opens but with the screen chop. AMD Ryzen 5 4000 series with NVidia graphics. I dunno, I'm beat.

**Comment by andrewgabbert** [comment]
This issue still persists.

**Comment by Gaz492** [comment]
Im not really sure what would be causing this other than the previously mentioned graphics card/driver issues.
Do you have any issues with other games you run on your laptop?
