### ISSUE TITLE
Tier 4 Soul Engulfing preview not showing outer pillars

### ISSUE THREAD

**Issue by noelmage** [FTBTeam/FTB-Modpack-Issues#4844]
### Modpack

FTB Skies Expert

### Modpack version

1.3.1

### Describe the bug

JEI preview of the Tier 4 soul engulfing setup does not show the entire multiblock.

### Steps to reproduce

1.Open JEI
2. Search for Soul Crystal
3. Select the Soul Crystal

### Expected behaviour

JEI preview shows outer pillars of tier 4 soul engulfing setup

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25268975/6bbbe79c-0def-45bd-a7a6-fddfb0f29780)

**Comment by Saereth** [comment]
This is a limitation of the jei render, its been reported to the mod dev, as a work around we've included an image in the quest book and a ponder to show the full structure
