### ISSUE TITLE
FTB Interactions Not start

### ISSUE THREAD

**Issue by DaTouJun** [FTBTeam/FTB-Modpack-Issues#4845]
### Modpack

FTB Interactions

### Modpack version

1.9.1

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14475432/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14475433/latest.log)

### Describe the bug

juet crash

dragonwell java and openjdk all tested

### Steps to reproduce

Download from curseforge
start

### Expected behaviour

Start

**Comment by Saereth** [comment]
You are on a very old version from curseforge that is no longer supported, you can get the 2.x versions from the FTB App with the more updated verison
