### ISSUE TITLE
Implosion Compressor Issue

### ISSUE THREAD

**Issue by shank3001** [FTBTeam/FTB-Modpack-Issues#4848]
### Modpack

FTB Skies Expert

### Modpack version

1.3.2

### Describe the bug

The implosion compressor fails to operate on latest version. Was working on prior version.

### Steps to reproduce

1. On earth space station as the machine requires to be in orbit.
2. Formed implosion compressor
3. Load with TNT or it's variant and ingot
4. Fails to operate.

### Expected behaviour

Processing bar should move towards completion

### Screenshots

![Screenshot 2024-03-04 013024](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10300791/408bf040-f051-4c02-8ad0-185386723265)
![2024-03-04_01 31 29](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10300791/46577b81-18f7-457a-b9cd-01bee2495ab4)

**Comment by shank3001** [comment]
Broke and reformed using schematic cannon. Implosion machine has a grey front and still did not work. Broke machine and replaced with new one and it is working.

**Comment by manmaed** [comment]
Is this  for Skies Expert or F.A.M?

**Comment by Saereth** [comment]
This is due to the implosion compressor's structure being updated in this version, as you've discovered break and replace is the fix for it.

**Comment by shank3001** [comment]
Saereth,

Thanks for the quick response! Enjoying the pack! On to Venus!
