### ISSUE TITLE
"Super" coller fluids not adding or removing correctly

### ISSUE THREAD

**Issue by robobeaver6** [FTBTeam/FTB-Modpack-Issues#4849]
### Modpack

FTB Skies Expert

### Modpack version

1.2.2

### Describe the bug

Adding a bucket of liquid biomass works, but then I I remove it again, it leaves 250mb in the maching.  It needs to be broken and re-placed to clear the tank, as there is no purge.
I can not add a bucket of primitive slurry,  if I click on the machine with the bucket, it just opens the machine UI.

### Steps to reproduce

1. Right click with a full bucket of Liquid Biomass
2. Right click with an empty bucket.

### Expected behaviour

Same amount in as out for biomass.  recepie for gold shards requires a liquid that can't be added

**Comment by Saereth** [comment]
You should be piping into and out of these machines with the fluid transporters or jsut directly clicking with a mekanism basic tank. This is a limitation of buckets only holding exactly 1000mb and not a mod bug

**Comment by robobeaver6** [comment]
There is certainly some sort of bug, as 1000mb and then 1000mb out should not leave 250mb behind.  Also the reflected contents when in the UI compared to inspecting the machine did not agree.  One said empty, the other 250mb.  While your solution of using the fractional bucket containers effectively works around the bug, there definitely is one.
