### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ed0g14** [FTBTeam/FTB-Modpack-Issues#4851]
### Mod

FTB SkyFactory 2.5

### Mod version

FTB-Presents_SkyFactory_2.5-2.5.9.zip

### Forge / Fabric version

1.7.10

### Modpack & version

FTB Presents SkyFactory 2.5 1.7.10

### What issue are you having?

when i load the game it is normal until i open a world, then the screen turns one color, and when i mine the object below me it goes to normal, but when i stop doing this it goes back to being one color. the same thing happens for the menu. and i am using curse forge if that is the problem, but on my old laptop this was running just fine using curse forge.
![Screenshot 2024-02-19 230439](https://github.com/FTBTeam/FTB-Mods-Issues/assets/160577395/16360f37-c9d3-4c67-9cbf-72ea54fe4db9)
![Screenshot 2024-02-19 230532](https://github.com/FTBTeam/FTB-Mods-Issues/assets/160577395/02d903c3-fe12-4dd8-a061-ce01817e1159)

### Steps to reproduce

open a world

**Comment by Gaz492** [comment]
This might be a graphics issue caused by an outdated graphics driver, have your tried to update your graphics card drivers to see if it improves anything?
