### ISSUE TITLE
Advanced MIxer won't accept heat.

### ISSUE THREAD

**Issue by nlobdell** [FTBTeam/FTB-Modpack-Issues#4852]
### Modpack

FTB Presents F.A.M

### Modpack version

1.3.0

### Describe the bug

Unable to provide the Advanced Mixer with heat. Ambient temperature gets it to 300 Kelvin but then it stops. Mekanism pipes connect but wont transfer any heat, PneumaticCraft heat pipes don't connect at all. Blaze burner does nothing as well.

### Steps to reproduce

1. Place down advanced mixer.
2. Attach desired heat supply.
3. No heat is transferred.

### Expected behaviour

Heat can be provided to the mixer via at least 1 mod.

### Screenshots

![2024-03-04_04 27 10](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/70344419/74b0863d-dae4-477f-9869-22dfba411c1d)
![2024-03-04_04 29 17](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/70344419/6983fb1a-f245-4044-82b6-6cb97f5180f6)
![2024-03-04_04 32 15](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/70344419/67c94849-216f-4db5-9cb4-1e8525391616)
![2024-03-04_04 32 19](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/70344419/e0552d4c-596f-443c-bc94-1c59495215fd)

**Comment by nlobdell** [comment]
Wrong modpack label, mod please close this.

**Comment by Saereth** [comment]
You need to provide mekanism heat, not pneumaticraft heat, you need to use the RTG generator or fission to produce heat. Mekanism CAN provide heat to pneumaticraft, but it doesnt work the other way around.

**Comment by nlobdell** [comment]
close my other one my b https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4853
