### ISSUE TITLE
Advanced MIxer won't accept heat.

### ISSUE THREAD

**Issue by nlobdell** [FTBTeam/FTB-Modpack-Issues#4853]
### Modpack

FTB Skies Expert

### Modpack version

1.3.0

### Describe the bug

Unable to provide the Advanced Mixer with heat. Ambient temperature gets it to 300 Kelvin but then it stops. Mekanism pipes connect but wont transfer any heat, PneumaticCraft heat pipes don't connect at all. Blaze burner does nothing as well.

### Steps to reproduce

1. Place down advanced mixer.
2. Attach desired heat supply.
3. No heat is transferred.

### Expected behaviour

Heat can be provided to the mixer via at least 1 mod.

### Screenshots

![2024-03-04_04 27 10](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/70344419/487d3732-a1df-4d23-a56c-4090b1762068)
![2024-03-04_04 29 17](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/70344419/f6fc8657-fe99-4a47-afeb-af1158f213b4)
![2024-03-04_04 32 15](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/70344419/30ef4716-3087-4c02-b91e-ff20002a584b)
![2024-03-04_04 32 19](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/70344419/9392a3b0-4d45-4f7d-a38e-167a20c7abb1)

**Comment by Saereth** [comment]
fixed the label and responded in your other post
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4852
