### ISSUE TITLE
Biofuel earlygame

### ISSUE THREAD

**Issue by MaxHD22** [FTBTeam/FTB-Modpack-Issues#4855]
### Modpack

FTB Skies Expert

### Modpack version

1.3.2

### Describe the bug

In the quest for Biofuel stands that you can creat Biofuel via Creat at the begining but there is no recipe anymore

### Steps to reproduce

Click in to the recipe of Biofuel and look at the tabs

### Expected behaviour

There should be a Mixin recipe be for creat

**Comment by krisavi** [comment]
Fixed in 1.3.3

**Comment by MaxHD22** [comment]
Okay thanks
