### ISSUE TITLE
Create Windmill

### ISSUE THREAD

**Issue by Blugypsy** [FTBTeam/FTB-Modpack-Issues#4856]
### Modpack

FTB Skies Expert

### Modpack version

1.3.2

### Describe the bug

Windmill doesn't increase the base stress units after increasing the size

### Steps to reproduce

add 8 sails right click bearing then add 8 more and right click bearing stress units don't change

### Expected behaviour

Increase Stress Units as size increases

### Screenshots

![image_2024-03-04_141731359](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/162188191/a6284572-5c1d-4952-9d97-5642190c3929)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/162188191/05102f29-5931-4dce-bbf9-ed8adc1ea2d1)

**Comment by Saereth** [comment]
This is working as intended for this pack, the quest that tells you about the endless water and windmills tells you that they are vastly reduced SU capacity to facility aesthetic designs and small farms only
