### ISSUE TITLE
Immersive Engineering Cables not being saved in the Simulation Chamber

### ISSUE THREAD

**Issue by KristjanT32** [FTBTeam/FTB-Modpack-Issues#4857]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Describe the bug

For some reason, when saving a simulated environment in the Simulation Chamber, Immersive Engineering wires are not saved, and instead disintegrated. Upon loading the chamber back, the connectors are intact, but all of the connections have been wiped and the wires nowhere to be found.

### Steps to reproduce

1. Load up any Simulation (e.g Farms)
2. Connect two machines with a wire from Immersive Engineering
3. Unload simulation
4. Reload simulation
5. All of the wires are gone.

### Expected behaviour

The wires should also be saved onto the Spatial Storage Cell

**Comment by ph1823** [comment]
you can add spark, if you add spark, that dont save and depop this, i have lost many spark
and if you have too many mekanism item, dont save too

I hope a update soon fix this

**Comment by ArtpokeBr** [comment]
yeah, this is unfortunatly a limitation of AE..... we can't fix this on our side =/
