### ISSUE TITLE
Informational quests

### ISSUE THREAD

**Issue by KajeTheCat** [FTBTeam/FTB-Modpack-Issues#4859]
### Modpack

FTB Arcanum Institute

### Is your suggestion related to a problem? Please describe.

I just recently learned how to acquire rotten eggs so that I can get bees, but without any mod knowledge I never would have found out if I hadn't asked someone in the discord. Adding a quest to beasts and familiars that explains that you need to convert the egg through a mana pool + alchemy catalyst could help players in the future.

**Comment by TheonlyTazz** [comment]
it seems that i actually missed adding bees spawneggs to Jake's trades.
