### ISSUE TITLE
Crash while loading mods

### ISSUE THREAD

**Issue by LezarisCW** [FTBTeam/FTB-Modpack-Issues#486]
### Modpack

FTB stoneblock 2

### Modpack version

1.12.1

### Log Files

[crash-2021-12-19_14.51.16-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7740992/crash-2021-12-19_14.51.16-client.txt)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7741008/latest.log)

### Describe the bug

When the modpack finishes loading all the mods, it crashes withe the message "Game crash: an unexpected error occured. Exit 
code: 0"

### Steps to reproduce

I dont know, i just opened it and it crashed

### Expected behaviour

I expected the game to open normally as usually, sending me to the game's main menu (where i can choose singleplayer/multiplayer etc)

**Comment by Raidobw2** [comment]
Can you try a few things:
-Update your graphics cards driver to its latest version. Or update graphics drivers from the manufacturer's site if you don't have a graphics card from Nvidia or AMD.
-Open the modpack folder. In the FTB App, click Stoneblock 2 in your library. Click settings, then Open Folder. In the File Explorer, find and open `options.txt`. Find the line where it says `fullscreen:` and set it to false like this `fullscreen:false`. Save the file.
Try to play the game after that, and let me know.

Another option could be to update HammerCore, although I'm not sure that will work.
(By getting the file at https://www.curseforge.com/minecraft/mc-mods/hammer-lib/files/3493538 and replacing `HammerLib-1.12.2-2.0.6.17.jar` in your `mods` folder by it).

Wait till it's loaded to put it fullscreen with F11.

**Comment by Raidobw2** [comment]
Closing this as I haven't gotten a reply in many days, I assume it was solved.
