### ISSUE TITLE
Constant disconnects from all FTB Skies Expert Servers

### ISSUE THREAD

**Issue by mc-birdie** [FTBTeam/FTB-Modpack-Issues#4861]
### Modpack

FTB Skies Expert

### Modpack version

1.3.2

### Log Files

This is my most recent latest.log copied after experiencing a disconnect.

https://pste.ch/osukezodah.md

### Describe the bug

I am experiencing what appears to be in-client connection degradation leading to eventual timeouts from all public FTB skies servers that I have tried joining. I believe the problem is specific to FTB skies expert and my network. I will explain how I have arrived at this conclusion.

A. I have experienced this issue on servers hosted by a particular group. I joined their FTB Genesis server and was able to play without issue. FTB Genesis is also running on Minecraft version 1.19.2, which leads to me to believe it is not an issue specific to any pack running with the 1.19.2 protocol.

B. I have joined several public servers with ~10 people playing just fine on them. I experience the same issue on all of these servers. This leads me to believe it is not specific to the server(s) because A) other people are playing just fine on them and B) it is unlikely I would hit the same issue on multiple different servers on different hosts in different parts of the world.

C. I monitored my connection to these servers with WinNTR, which essentially gives you a long-running tracert, and saw no issue at all with my connection to those servers in those logs. No significant packet loss, totally normal latency depending on location, no issues. I also monitored the traffic between these servers with Wireshark and the TCP traffic data looks basically normal to me up to the point where I am very suddenly hit with a TCP RST. These tests were all run while connected to the servers in client. This is what makes me think the issue is somehow specific to something happening in the pack, rather than just my network.

The pattern is basically that I join these servers and Minecraft shows me at full wifi signal strength. I don't know what this thing actually measures, but it very slowly loses bars until it gets to 1/2 bars and then I get booted from the servers.

Connecting also takes quite a while, with most of the time spent on the encrypting step.

I'm more than happy to hop on a call with someone or provide whatever logs/additional debugging info if anyone wants to take a deep-dive with me.

The error message is most often the java.net.SocketException: Connection reset error, which makes sense if that is the generic error for TCP RST. But I've also had chat message validation failure and one other - maybe a more generic timed out error? I can't quite remember.

### Steps to reproduce

1. Be me
2. Launch FTB skies expert and connect to any public server
3. Get timed out after a few seconds/minutes

### Expected behaviour

I expect to be able to play on servers in FTB skies expert without being disconnected constantly

### Additional information

I have tagged this 1.3.2, but I've been experiencing the error on every version I've played on for the past week or so.

Anecdotal, but I have also heard from a few other players that they are experiencing the same issue, so I don't think it is isolated to just me.

I should probably add that I've reset both my router and my modem and have tried both wifi and hardwire connections.

**Comment by mc-birdie** [comment]
Updating with what limited information I've been able to gather.

We installed the connectivity mod on the server and discovered two things:

The first thing is that the server is somehow deciding that I am logged in from another location. As far as I can tell this is not true. 

The Microsoft account linked to my Minecraft account is passwordless w/ 2FA on and I have no notifications. I also checked the log-in attempt log and I'm the only person successfully connecting with the account. Further, it doesn't make sense to me that someone would only be logging into my account when I'm on FTB Skies Expert servers. I can be disconnecting nonstop on FTB Skies Expert and then switch over to a different 1.19.2 FTB pack on the same server infrastructure and experience hours of uninterrupted gameplay.

So, in this case, I think that error is not quite true but may still help point to the actual problem.

The second is that we got a packet dump for the server that looks a little unusual. It may be connected, it may not be connected, not sure. https://mclo.gs/XufcGeK

These logs are for a server with 9 players connected. Something is sending a ton of SavedDataSyncMessage packets, but I'm not sure what. The consensus from talking w/ the dev of connectivity is that the first two numbers are "quite suspicious" and that the rate of 4k packets/player/second is abnormally high for Minecraft. I can't speak to that personally, but figured I would pass it on in case it is an unexpected measurement for you all.

**Comment by mc-birdie** [comment]
I wonder if this is a similar issue to: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3169

**Comment by Saereth** [comment]
> I wonder if this is a similar issue to: #3169

no that mod was remvoed from skies and is still removed in skies expert

**Comment by Saereth** [comment]
> ### Modpack
> FTB Skies Expert
> 
> ### Modpack version
> 1.3.2
> 
> ### Log Files
> This is my most recent latest.log copied after experiencing a disconnect.
> 
> https://pste.ch/osukezodah.md
> 
> ### Describe the bug
> I am experiencing what appears to be in-client connection degradation leading to eventual timeouts from all public FTB skies servers that I have tried joining. I believe the problem is specific to FTB skies expert and my network. I will explain how I have arrived at this conclusion.
> 
> A. I have experienced this issue on servers hosted by a particular group. I joined their FTB Genesis server and was able to play without issue. FTB Genesis is also running on Minecraft version 1.19.2, which leads to me to believe it is not an issue specific to any pack running with the 1.19.2 protocol.
> 
> B. I have joined several public servers with ~10 people playing just fine on them. I experience the same issue on all of these servers. This leads me to believe it is not specific to the server(s) because A) other people are playing just fine on them and B) it is unlikely I would hit the same issue on multiple different servers on different hosts in different parts of the world.
> 
> C. I monitored my connection to these servers with WinNTR, which essentially gives you a long-running tracert, and saw no issue at all with my connection to those servers in those logs. No significant packet loss, totally normal latency depending on location, no issues. I also monitored the traffic between these servers with Wireshark and the TCP traffic data looks basically normal to me up to the point where I am very suddenly hit with a TCP RST. These tests were all run while connected to the servers in client. This is what makes me think the issue is somehow specific to something happening in the pack, rather than just my network.
> 
> The pattern is basically that I join these servers and Minecraft shows me at full wifi signal strength. I don't know what this thing actually measures, but it very slowly loses bars until it gets to 1/2 bars and then I get booted from the servers.
> 
> Connecting also takes quite a while, with most of the time spent on the encrypting step.
> 
> I'm more than happy to hop on a call with someone or provide whatever logs/additional debugging info if anyone wants to take a deep-dive with me.
> 
> The error message is most often the java.net.SocketException: Connection reset error, which makes sense if that is the generic error for TCP RST. But I've also had chat message validation failure and one other - maybe a more generic timed out error? I can't quite remember.
> 
> ### Steps to reproduce
> 1. Be me
> 2. Launch FTB skies expert and connect to any public server
> 3. Get timed out after a few seconds/minutes
> 
> ### Expected behaviour
> I expect to be able to play on servers in FTB skies expert without being disconnected constantly
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> I have tagged this 1.3.2, but I've been experiencing the error on every version I've played on for the past week or so.
> 
> Anecdotal, but I have also heard from a few other players that they are experiencing the same issue, so I don't think it is isolated to just me.
> 
> I should probably add that I've reset both my router and my modem and have tried both wifi and hardwire connections.

Try running the server with secure profile enforcement off and see if that helps

**Comment by mc-birdie** [comment]
> > I wonder if this is a similar issue to: #3169
> 
> no that mod was remvoed from skies and is still removed in skies expert

I know - I don't mean that specific mod. I mean some other mod, which _is_ in this pack, is causing extremely high network traffic per the log I posted above. Not speculative, it is happening.

**Comment by mc-birdie** [comment]
OK, disabling secure profile enforcement did not work.
