### ISSUE TITLE
Unable to launch modpack

### ISSUE THREAD

**Issue by chavonne-kek** [FTBTeam/FTB-Modpack-Issues#4862]
### Modpack

FTB Presents AbePack

### Modpack version

1.5.0

### Log Files

[FTBlog.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14490165/FTBlog.txt)

### Describe the bug

Im not sure what the error is that is preventing the modpack to launch. It crashes as it is loading the modpack in the FTB app

### Steps to reproduce

1. download the modpack
2. hit the "play" button of the mod

### Expected behaviour

Launch the minecraft launcher after loading the modpack in the FTB

### Screenshots

<img width="803" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/131730486/75d648d4-8f0f-498f-a7d5-69c50a029078">

**Comment by Gaz492** [comment]
It looks like your graphics drivers may be outdated, could you try updating your graphics drivers to see if that resolves the issues you are having?
