### ISSUE TITLE
thermal endergy is too far back

### ISSUE THREAD

**Issue by KuroPeach** [FTBTeam/FTB-Modpack-Issues#4863]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

By the time we can use it, it's almost game over.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/19620848/29880e53-5759-4f71-80a8-034fe3bccc75)

**Comment by Saereth** [comment]
changed to require protochorus now, should help!
