### ISSUE TITLE
Ars Nouveau - Ritual of Challange in FTB Dims

### ISSUE THREAD

**Issue by Niitek** [FTBTeam/FTB-Modpack-Issues#4865]
### Modpack

FTB Skies Expert

### Modpack version

1.3.3

### Describe the bug

Reminder for Tazz to check on the ars ritual of challenge not working. Works on the boat, minecraft:overworld, but not any of the dimensions from FTB.

### Steps to reproduce

start ritual with villager and POI

### Expected behaviour

Raids should begin shortly after activation.

**Comment by Saereth** [comment]
this is not a bug, raids are disabled in ftbteam dims intentionally
