### ISSUE TITLE
Wither particle effects wont disappear

### ISSUE THREAD

**Issue by Nanaki2345** [FTBTeam/FTB-Modpack-Issues#4866]
### Modpack

FTB Skies Expert

### Modpack version

1.3.3

### Describe the bug

I have a mob farm in the nether, while killing mobs I had a apothic boss bear spawn. after killing all the mobs the left behind a wither effect, like a splash potion going off. but the issue is it wont disappear. i have died, re-logged, left the nether and came back. But nothing seems to fix the issue. also if you walk into the particles or mobs walk into it the wither effect hits the entity inside the "cloud"

### Steps to reproduce

Mob farm in nether

### Expected behaviour

particles to disappear after a little time

### Screenshots

![2024-03-05_14 21 51](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/162335009/65518e1d-2625-4b4e-b13a-7ee8f4da13ad)

**Comment by Saereth** [comment]
anyone else been able to reproduce this? I havewnt been able to

**Comment by IonNight** [comment]
I have and hitboxes was enabled when it spawned. It spawned like a mob and got transported to the killing chamber by the vector plates
![2024-03-25_19 08 53](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/27898087/57a6994f-dddf-40d8-bd61-8667999a4def)

**Comment by IonNight** [comment]
@Saereth did you see my reply?
