### ISSUE TITLE
Super cooler bugged

### ISSUE THREAD

**Issue by StonebanksYT** [FTBTeam/FTB-Modpack-Issues#4868]
### Modpack

FTB Skies Expert

### Modpack version

1.2.2

### Describe the bug

Super Cooler fluid input is bugged. When I emptied the liquid biomass it still shows 500mb liquid biomass and I cannot remove it or add another fluid in it.

### Steps to reproduce

1. Add liquid biomass or any liquid in Super Cooler for eg 2500mb liquid biomass
2. Make the enriched peat or any item
3. Empty the remaining biomass 
4. Does not empty entirely
5. GUI remains bugged

### Expected behaviour

The super cooler should empty completely and the gui should update

### Screenshots

![Screenshot 2024-03-05 222347](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/76697156/3861db50-1b0a-426a-a7d9-05c64d6a20c5)

**Comment by Saereth** [comment]
yeh this isnt a bug, you cant bucket less than a bucket, you need to use a tank on bucket mode or pipe it
