### ISSUE TITLE
Biomass mixing recipe not working

### ISSUE THREAD

**Issue by CubeStick** [FTBTeam/FTB-Modpack-Issues#4871]
### Modpack

FTB Skies Expert

### Modpack version

1.3.3

### Describe the bug

Can't craft the Biomass in the mixer, recipe says 4 bone meal and 1 coal dust.
I put it in the Basin but nothing happens.
It's an alternative recipe since I also can't make it with flowers (tried MC flowers).
There's 2 of the same recipe btw, 1 that gives 16 Biomass and the other 8 Biomass with the same ingredients.

### Steps to reproduce

Put 1 coal dust and 4 bone meal (or 8 flowers and 1 coal dust) in Basin
(it's powered by water wheels, the ones with durability, they're at 90% so not broken)
See that it doesn't do anything

### Expected behaviour

Expect it to craft Biomass

### Screenshots

![2024-03-05_21 59 55](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/56218378/b6a97b09-2a37-4dc6-ab78-cab50b536865)

**Comment by Miime** [comment]
same probleme there !
