### ISSUE TITLE
FTB Skies Expert Spirit Multiblock Incorrect Ponder Structure

### ISSUE THREAD

**Issue by Nozsho** [FTBTeam/FTB-Modpack-Issues#4875]
### Modpack

FTB Skies Expert

### Modpack version

1.2.2

### Describe the bug

Within the description of the quest Soul Engulfing Concentrator, the ponder structure and the screenshot structure are not the same; the **ponder structure showcases an 11x11 area from the pillar corners**, whereas the **image structure showcases a 9x9 area**. Because the ponder structure is on the first page of the quest description, this can cause unnecessary headache, especially when making the Soul Crystals.

### Steps to reproduce

1. Go to Quests --> Mastering the Occult --> Soul Engulfing Concentrator
2. Look at Ponder Structure
3. Go to second page of quest description, compare Ponder Structure with Image

### Expected behaviour

The structures should be the same

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/80147822/a9b49a90-da9f-4554-9e62-67d7e23fd433)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/80147822/2a081359-ed5a-4552-9df7-2afd1a36367b)

### Additional information

The 9x9 structure (non-ponder) is the correct structure. Also, since the Schematic Cannon is already included and preloaded with certain structures, it'd be nice to have this structure as well, at the very least to allow users to learn how to use it early in the pack.

**Comment by TheonlyTazz** [comment]
update to 1.3.x; this has been updated. 

When making Issues, please ensure you are running the latest version of the pack.
