### ISSUE TITLE
Ad Astra fuel/oil/cryo fuel does not exist/crude oil will not pipe into refinery

### ISSUE THREAD

**Issue by Zeaxe** [FTBTeam/FTB-Modpack-Issues#4876]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1&1.12.0

### Describe the bug

ad astra oil, fuel, and cryo fuel icons are invisible in JEI
ad astra fuel refinery will not accept crude oil
tried to replicate on 2 different computers/installs

### Steps to reproduce

1. open inventory with JEI
2. type in "@adastra fuel"/"@adastra oil"
3. shit ain't there

### Expected behaviour

I expected to go to the moon

### Screenshots

[![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/121538272/445a756e-b849-4f8f-8137-09076107384a)
](https://imgur.com/a/Ba2dT71)

**Comment by ZeroOrigin** [comment]
I'm not sure what you're doing, but if you are doing what I was doing, trying to use the crude oil from a pool on the ground, it doesn't work. You have to go into the ocean with buckets or mekanism tanks in bucket mode and grab them manually. Hope this helps.

**Comment by DinnerBeef** [comment]
The buckets show up in JEI the fluids are still there show are invisible. You can also hit `U` on the Fuel Loaders to see all types of fuels are that supported.
