### ISSUE TITLE
Provide alternate ways of obtaining electrum and higher tier coins

### ISSUE THREAD

**Issue by Timmy3921** [FTBTeam/FTB-Modpack-Issues#4878]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

It would be nice if you could obtain higher tier coins from regular villagers to allow for auto-trading higher tier items, because waiting for wandering trader to spawn or sacrificing a villager to summon one just to get 30 coins is a bit tedious. Obviously this could allow players to obtain the coins before they can get the corresponding resource, so as a solution, the items that earn you coins are locked behind progression. For example, maybe the librarian could exchange a sculkshelf for enderium coins, since to get the sculkshelfs, you need a warden tendril, and to get a warden you need a martian raptor. That way enderium and its coin equivalent both require you to go to mars.

Alternatively, you could just have a mid-late game machine turn the alloys into coins, or have a coin mold that's difficult to obtain.

**Comment by Saereth** [comment]
This wont match our design intent for trading, which is time limited resources via manual coin trading. Any automated method of producing coins would break this design goal.
