### ISSUE TITLE
Crash when holding Shadow Book from Hexerei

### ISSUE THREAD

**Issue by PandaionicZone** [FTBTeam/FTB-Modpack-Issues#4880]
### Modpack

FTB Arcanum Institute

### Modpack version

1.3.0

### Log Files

https://[pste.ch/raw/soyomeqeca](https://pste.ch/raw/soyomeqeca)

### Describe the bug

I was in the process of crafting the book from Hexerei, and when i finally crafted it and went to open it, as soon as i had it in my hand the client crashed. Afterwards i ran the client again, and as soon as i get into the server the client crashes.

### Steps to reproduce

1. craft book of shadows from hexerei
2. select it in hotbar
3. crash

### Expected behaviour

i expected the book to be selectable and openable

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
