### ISSUE TITLE
Pneumatic Cylinder villager trade

### ISSUE THREAD

**Issue by Lydia-Defountain** [FTBTeam/FTB-Modpack-Issues#4884]
### Modpack

FTB Skies expert

### Is your suggestion related to a problem? Please describe.

The Pneumatic Cylinder villager trade in the Pneumaticract:mechanic is a bigh high cost being Sig. Please reduce to electrum.

**Comment by Saereth** [comment]
lowered cost of pnc cylinder trade to electrum coins from signalum
