### ISSUE TITLE
Can't craft Redstone Comparator or daylight sensor in FTB Direwolf20 1.20 pack version 1.12.1

### ISSUE THREAD

**Issue by mcdodge34** [FTBTeam/FTB-Modpack-Issues#4885]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

Can't craft redstone comparators or daylight sensors

### Steps to reproduce

1. Search for redstone comparator in JEI
2. See there's no recipes for it
3. Be sorry because we need redstone comparator
4. Repeat for daylight sensor

### Expected behaviour

Be able to craft redstone comparator and daylight sensor

**Comment by DinnerBeef** [comment]
Unable to reproduce this issue. Please reopen if you are still having issues with this. Try reinstalling the modpack to see if that fixes it.
