### ISSUE TITLE
[Suggestion]: Piglin bartering list for JEI

### ISSUE THREAD

**Issue by Therrous** [FTBTeam/FTB-Modpack-Issues#4887]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

For a lot of resources there seems to be tooltips to various items to let people know you can get them via bartering. Why not have some way to just contain a list somewhere of the custom barters so items you can get that way show up properly?

**Comment by Saereth** [comment]
Yeah we can add a quest that shows this
