### ISSUE TITLE
Castle in the sky

### ISSUE THREAD

**Issue by Virusinfector** [FTBTeam/FTB-Modpack-Issues#4888]
### Modpack

FTB Skies Expert

### Modpack version

1.3.3

### Describe the bug

While in the Castle dungeon i can still place blocks and when at the end and flip the lever i still can't break blocks so I'm trapped in there 

### Steps to reproduce

place a block?
flip the lever at the end and try to break a block

### Expected behaviour

i wanted a new home

**Comment by Saereth** [comment]
I cant really do much to address this unfortunately, I've asked the mod dev to enable suport for its functionality outside of overworld but for now its hard coded.

**Comment by Virusinfector** [comment]
> I cant really do much to address this unfortunately, I've asked the mod dev to enable suport for its functionality outside of overworld but for now its hard coded.

ah that sucks because you could get trapped in there if you dont know the code to blow up the castle
