### ISSUE TITLE
[Suggestion]: Quest chapter dedicated to pointing out heavily used materials

### ISSUE THREAD

**Issue by Therrous** [FTBTeam/FTB-Modpack-Issues#4889]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

I've noticed a lot of certain materials being used/relied on for recipe gating and general tiering up. The large unguided web of current chapter two lists a lot of singular materials, but a chapter dedicated to pointing out the blocks/materials you'll want to automate in bulk or always have constantly produced would be very helpful in guiding players on what to focus their time/effort in. Pointers for production paths/methods are optional :P

Bonus points taking a page from Create Above and Beyond: an extra checkmark quest completion alongside a singular item check for the resources in question so that players can self-mark off something as both accessible and automated. No need for quest rewards there, automation is its own reward.

**Comment by Saereth** [comment]
I couldnt really see a good way to implement this so it looks nice, going to keep it in mind for future packs tho
