### ISSUE TITLE
[Suggestion]: Dense Tungsten Ore doesn't smelt down properly

### ISSUE THREAD

**Issue by Maru467** [FTBTeam/FTB-Modpack-Issues#489]
### Modpack

FTB Interactions

### Is your suggestion related to a problem? Please describe.

Dense tungsten ore doesn't smelt to the correct ore cluster. It smelts to tungstate ore clusters, which do nothing, while the blood shard smelts to tungsten ore clusters, which process correctly.

**Comment by Saereth** [comment]
This is not a bug this intended, otherwise you'd get ALOT more tungsten production from that, you still need to process the tungstate ore as you normally would
