### ISSUE TITLE
Mana spreader recipe

### ISSUE THREAD

**Issue by SkyExpertTester** [FTBTeam/FTB-Modpack-Issues#4896]
### Modpack

FTB Skies Expert

### Modpack version

1.3.3

### Describe the bug

The Mana spreader recipe through the Enchanting Apparatus (Ars Nouveau) requires 1 Manipulation Essence, 7 Living Logs or equivalent and shows a source relay for the conversion material. When right clicked on the apparatus with or without the source relay it says "No recipe found". Tried switching to different living log equivalents and same result. Cannot craft the Mana spreader this way however is the only way to make the basic version of it. 

### Steps to reproduce

Craft a mana spreader in the Enchanting Apparatus with mentioned recipe above. 

### Expected behaviour

The Mana spreader to get crafted in the Enchanting Apparatus for collection

**Comment by AStickyWicket** [comment]
Are you sure you don't have any other pedestals with items around? This recipe works in my 1.3.3 game

**Comment by SkyExpertTester** [comment]
For sure, it is the only setup in that area. I triple checked because every recipe so far has worked with no issues and made me think I was going crazy haha
