### ISSUE TITLE
industrial foregoing Animal rancher harvests black dye from squids instead of ink sacs

### ISSUE THREAD

**Issue by Troll-Rex** [FTBTeam/FTB-Modpack-Issues#4898]
### Modpack

FTB Skies

### Modpack version

1.4.1

### Describe the bug

The Animal Rancher is supposed to farm ink sacs from squids when they are in the work area.
However, it is instead harvesting black dye which is not usable in place of ink sacs for most recipes

### Steps to reproduce

1) Set up industrial foregoing animal rancher
2) Put squid into work area
3) Check output of animal rancher

### Expected behaviour

The Machine should be harvesting ink sacs from squids

### Additional information

I checked all of the documentation I could find to see if this was intentional and could not find anything discussing it.
Given than ink sacs are not reliably farmable/automatable in any other manner, it did not seem like a change that would have been made intentionally.

**Comment by Saereth** [comment]
this is the way the mod works not the pack, you can setup a vanilla squid farm though otherwise
