### ISSUE TITLE
[Suggestion]: Redstone signal locking Jar Auto-Processing

### ISSUE THREAD

**Issue by LuciusV** [FTBTeam/FTB-Modpack-Issues#490]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

Please add possibility to pause jar autocrafting on redstone signal

**Comment by LuciusV** [comment]
Any decision please?

**Comment by Raidobw2** [comment]
Hi, that was not originally planned in the release of the mod so it might not be added. We currently don't have many modders at the task -- in fact our lead software developer is currently our only modder. He is focused mainly on game breaking bugs at the moment which affects more modpacks, for instance in FTB Chunks, Ranks, etc.

FTB Jar Mod is only used within OceanBlock and a few other modpacks probably -- it's niche therefore it's not currently a priority for the development team.

If I could suggest something for now is to use other ways to limit item transfer into the auto-processing jar. Most item cables from other mods have redstone control which you could use to your advantage.
