### ISSUE TITLE
Crafting for Steel and Iron Mechanical components

### ISSUE THREAD

**Issue by Lancelu-Horse** [FTBTeam/FTB-Modpack-Issues#4900]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

Automated Engineer's Workbench is a slow and big machine and can only craft one type of item, so I suggest that the Iron and Steel Mechanical Components cheaper recipes (that uses only 2 plates) be added to Fabrication Matrix.

**Comment by Saereth** [comment]
nah people can automate those workbenches/bulk craft if they want the cheaper recipe either way they can pay the higher cost for convenience. Later play its a non issue as those resources are effectively infinite so you just encode a shapecraft pattern and call it a day.
