### ISSUE TITLE
Lexica Botania not displaying crafting some recipies

### ISSUE THREAD

**Issue by robobeaver6** [FTBTeam/FTB-Modpack-Issues#4902]
### Modpack

FTB Skies Expert

### Modpack version

1.3.3

### Describe the bug

Lexica Botania not showing some recipy patterns.  Dor example Runic Altar page only contains the words "Crafting the Runic Altar" and no recipy.  The runes for Earth and Fire are also not showing in the book, but it does show in NEI.  

The runic altar pattern does not show in NEI either, and it is a nonstandard patturn, so I have no idea how to build it.

### Steps to reproduce

1. Open the Lexica Botania book.  
2. Click Basics and Mechanics
3. Click Runic Altar.
4. Scroll to crafting instructions

### Expected behaviour

Show recipies.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20403563/b8182e62-9fa0-4616-9f24-c5293b1bdcc8)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20403563/baa7b1e5-3770-4538-89ad-88deac57f58b)
NEI only shows a minituraisation crafting pattern
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20403563/e8d60b60-2805-413b-90b6-84f207b380b9)

### Additional information

No additional mods installed.

**Comment by Saereth** [comment]
This wont be changed, its a limitation of the lexica botania to render actual crafting recipes, since there isnt one for the runic altar it cant render it.

**Comment by robobeaver6** [comment]
Thanks for the response.  Can you tell me how you are supposed to make The Runic Altar?
Also the Rune of earth and Rune of fire do appear to have recipies in NEI, but they are not rendering either in the book.
