### ISSUE TITLE
Direwolf 1.20 Rats Mounts crashing Multiplayer server forever

### ISSUE THREAD

**Issue by agrahamlincoln** [FTBTeam/FTB-Modpack-Issues#4903]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Log Files

I ran a backup IMMEDIATELY before the crash

latest.log
[minecraft-logs.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14544605/minecraft-logs.log)

debug logs:
[minecraft-logs.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14544616/minecraft-logs.log)

### Describe the bug

It seems like anytime I equip a rat from ratlantis with any of the mount upgrades the whole server crashes and kicks me off. After some time the server will exit because there hasn't been a tick in over a minute. All players are immediately logged out of the server and can't reconnect. After the server starts backup, users cannot reconnect.

Only way I've been able to resolve the issue is by restoring a world backup.

### Steps to reproduce

1. Setup a Multiplayer server (I haven't tried creative or anything, only from my active game)
2. Tame a rat from ratlantis
3. Equip the rat with a golem or a chicken mount upgrade
4. game crashes

### Expected behaviour

Game shouldn't crash, and the rats should have a mount

**Comment by agrahamlincoln** [comment]
FWIW we had a similar world-breaking crash when we broke a ratlantis Air Raid Siren in ratlantis that had blocks above it. The stack trace looked similar but I didn't look closely enough to see if it was exactly the same exception and trace.

**Comment by mbaumaister13** [comment]
> FWIW we had a similar world-breaking crash when we broke a ratlantis Air Raid Siren in ratlantis that had blocks above it. The stack trace looked similar but I didn't look closely enough to see if it was exactly the same exception and trace.

Just had the same issue. Were you able to restore server functionality?

**Comment by IanLunt** [comment]
This issue is relating to citadel and running it on a dedicated server. If you run into this issue and don't have a backup, load the world in a single player world and unequip the rat mount and then you should be able to load the world again on a server.

**Comment by Gaz492** [comment]
Another solution to this may be to disable the Canary mod. It looks to be a known issue.
https://github.com/AlexModGuy/Rats/issues/862
https://github.com/AbdElAziz333/Canary/issues/222

**Comment by mbaumaister13** [comment]
> Another solution to this may be to disable the Canary mod. It looks to be a known issue. [AlexModGuy/Rats#862](https://github.com/AlexModGuy/Rats/issues/862) [AbdElAziz333/Canary#222](https://github.com/AbdElAziz333/Canary/issues/222)

I was the one who submitted the issue on the Canary mod repo. Disabling the Canary mod on both client & server side fixed our issue. Still waiting on a fix on the Canary side.
