### ISSUE TITLE
Material Generator not working 

### ISSUE THREAD

**Issue by StonebanksYT** [FTBTeam/FTB-Modpack-Issues#4908]
### Modpack

FTB Skies Expert

### Modpack version

1.3.3

### Describe the bug

The material generator is not generating any material and a text is hovering that says "Needs Tool". Can you please help or tell what I'm doing wrong?

### Steps to reproduce

place the required block
place the pedestal on top of it
put the material generator upgrade in offhand and click on the pedestal
material does not generate and it shows Needs Tool

### Expected behaviour

The material generator should start generating blocks

### Screenshots

![Screenshot 2024-03-10 001006](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/76697156/0e292694-7957-456f-b344-ad3220e07a8c)

**Comment by Saereth** [comment]
you need to git it a tool, place a tool for it to use in your off hand and then right click on it. It wont consume the tool but it will use it to mine the block so if you have it mine stone for example it will give cobblestone unless the pick axe silktouch or autosmelt etc etc
