### ISSUE TITLE
Can not join Partner in playing FTB Skies Expert, while in same house seated next to on another, on the same LAN

### ISSUE THREAD

**Issue by poeticwatcher** [FTBTeam/FTB-Modpack-Issues#4909]
### Modpack

FTB Skies Expert

### Modpack version

1.3.3

### Log Files

![FTB_Skies_Expert_Join_Error](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63106144/d73739f2-3960-475d-9b2c-12101f5dd634)

### Describe the bug

Error for [Joining Partner] when trying to join as visibly seen LAN game, as hosted by [Hosting Partner]

### Steps to reproduce

1. You and your partner, sitting side by side in the same house on the same LAN (and internet, et al) connection... open FTB Skies Expert modded minecraft
2. Either of you, as [Hosting Partner], start a new Singleplayer world in said game... advance in the game as far as you like, even advancing nothing at all and just being on the starting airship...
3. At some point, [Hosting Partner] hits 'ESC' to bring up the main menu in minecraft and click on the 'Open to LAN' button...
4. Second partner, as [Joining Partner], open the Multiplayer Games button in modded minecraft... Visually see that your partner's game is listed as open Via LAN for you to connect to... Click connect (or log in, or whatever to try to join)
5. [Hosting Partner] watches minecraft announce in the chat log that "[Joining Partner] joined server," followed immediately by an announcement that "[Joining Partner] left server"...
6. [Joining Partner] after a loading screen encounters the error pictured above.

Please assist! The method described here of joining a partner via LAN has worked for many older versions of Modded and unmodded Minecraft.

### Expected behaviour

For joining a partner's game of modded or unmodded minecraft to work without error as it has for multiple years and various modpacks in the past.

### Screenshots

![FTB_Skies_Expert_Join_Error](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63106144/c218afbf-f5d2-4a48-88e6-24a80a8153a3)

**Comment by poeticwatcher** [comment]
My partner joined the FTB Discord server, I think, and did a searched within the server for the Internal Exception that both of us had encountered as the [Joining Partner] in the steps described above. He found commentary from someone-else on the Discord, suggesting that removing the individual mod, 'fullstackwatchdog-1.0.1+1.19.2-forge' from both of our FTB Skies Expert modpack install would allow us to join each other via LAN. This did work!!! And after some poking around with FTB Teams mod (all done completely in game), we were able to be on the same island!!! Currently hosted by myself.

I am not 100% sure what the 'fullstackwatchdog-1.0.1+1.19.2-forge' mod does, from it's name I would guess it prevents cheating? I honestly don't know. Either which way, I wanted to come back and report that when BOTH of us removed this mod from the install, we were able to successfully connect.  I am leaving this report up as doing a blanket install of FTB Skies Expert and attempting to join a partner via LAN would (I am assuming) still result in an error. My partner commented to me that there was a new release of FTB Skies Expert while we were playing... but I don't know if this bug has been fixed.

**Comment by Saereth** [comment]
If some process takes too long (more than 60 seconds) the game will close with a watchdog exception, this mod gives more insight into what caused that issue. It can safely be removed but its something we'll need to get over to the mod dev to fix properly
