### ISSUE TITLE
Crude oil not being produce by black lens

### ISSUE THREAD

**Issue by LucasWarner** [FTBTeam/FTB-Modpack-Issues#4910]
### Modpack

FTB Skies Expert

### Modpack version

1.4.0

### Describe the bug

Attempting to create crude oil but no luck the fluid base says it producing something but yields nothing

### Steps to reproduce

1. setup laser drill
2. setup fluid base
3. insert black lens
4. power up the laser drill(s)
5. recipe yields zero crude oil

### Expected behaviour

production of 50mb of crude oil

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/38757711/7a1ba63e-6067-467b-a410-7475022d4ed5)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/38757711/f1bfd642-3b05-482f-9b5f-378cab087bbd)

### Additional information

depth is set between 20-60

**Comment by magisch** [comment]
This recipe only works in Orbit, either Earth or Moon Orbit works.

**Comment by Saereth** [comment]
Yeah as Magisch pointed out, if you check on the recipe in JEI it will show the whitelisted biomes for it
