### ISSUE TITLE
Server fatal crash on Lootr loot box opening

### ISSUE THREAD

**Issue by Eacaw** [FTBTeam/FTB-Modpack-Issues#4912]
### Modpack

FTB Presents F.A.M

### Modpack version

1.0.0

### Log Files

https://drive.google.com/file/d/1EqVGBb3e2_jlDkZQWW8Di2u5AczKBIxL/view?usp=sharing

### Describe the bug

Disclaimer: I wasn't online when this occurred but I have experienced something similar without a full crash. Console output rate limiter swallowed up any output immediately before the crash so nothing useful could be found there. Screenshots of this attached below. 

The server, with 16 GB memory playing on the 1.0.0 version has experienced several crashes. Most recently this occurred when players were trying to open a Lootr loot box on a sunken ship. Initially showing the 'Loot has not yet generated' message, before causing the server to crash. I have attached a link to a drive zip file with two crash reports around 20 minutes apart. In my case when I experienced this, I found a sunken ship and attempted to open a loot chest, initially nothing happened, then around 10-15 seconds later, I got rubber banded back to the first chest. 

From what I can ascertain from the crash report it looks like when the server fell over when trying to generate the loot inside these chests. 

On a similar note, we have also encountered other chests around the world that have been displaying as 'Loot not generated' in structures such as dungeons and their above-ground buildings. 

Repro steps are unconfirmed, will conduct some testing later this evening and report back. 

### Steps to reproduce

1. Start up a server on 1.0.0
2. In survival, head out to an ocean area and locate a sunken ship with Lootr chests inside.
3. Look at the chests -> see 'loot not generated'
4. Attempt to open the chest -> either:
    a.  Game becomes unresponsive, nothing happens and a few seconds later you get rubber banded to the now open chest
    b. Server crashes almost immediately requiring manual restart. 

### Expected behaviour

Loot available in chests and no server crashes. 

### Screenshots

![Screenshot_20240309-234615](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/24251551/5184e35e-8f8d-42da-9f97-4f362921467e)
![Screenshot_20240309-234549](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/24251551/32a6e782-7416-46e7-8b84-11ff64b64712)

**Comment by dbbrazin** [comment]
Same here. Twice now server has crashed when friend opened up a chest on one of those pirate ships.

**Comment by Eacaw** [comment]
This has just happened again, crash log suggests to me that it fell over while doing some chunk generation and trying to unpack a loot table for the Lootr mod again. Crash log attached. 

[crash-2024-03-16_16.24.55-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14624546/crash-2024-03-16_16.24.55-server.txt)

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version? I have not been able to reproduce this issue thus far.
If you are, would you be able to upload new log files for us so we can take a further look?

To prevent the server from crashing, you could try setting the max-tick-time option in the server.properties file to -1, this will disable the server watchdog and may allow the server to catch up instead of crashing.

**Comment by Eacaw** [comment]
That server is long gone, but I can confirm that we had regular crashes for many reasons throughout our playthrough. Some unknown, several due to Lootr boxes though. I can't provide any more logs, unfortunately.
