### ISSUE TITLE
Implosion Compressor's Structure Crafting to Hard

### ISSUE THREAD

**Issue by Odesyus** [FTBTeam/FTB-Modpack-Issues#4913]
### Modpack

FTB Skies Expert

### Modpack version

1.4.0

### Describe the bug

After 1.4.0 update Structural Glass recipe has changed and made it much harder. It isn't the big issue mostly but Implosion Compressor's structure needs Structural Glass and becuse of this change to make Implosion Compressor structure is become so hard to make

### Steps to reproduce

1. For structure you need the make Structural Glass
2. For Stuctural Glass you need the Weak Radiation Plate.
3. For Weak Radiation Plate you need to make Liquid Concrete
4. For Liquid Concrete you need to make Advanced Mixer.
5. For Advanced Mixer you need to make Ostrum Proc.
6. For Ostrum Proc. you need to able to go to Mars

### Expected behaviour

For the Implosion Compressor structure, another glass (for example Hardened Glass) should be used instead of Structural Glass.

### Screenshots

![Screenshot 2024-03-10 144229](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10671922/d8d8fb3d-3be2-4dfe-9d41-954ae6410cd0)
![Screenshot 2024-03-10 144315](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10671922/6cfeccb4-12c2-47c2-9d90-2b24559ad7a6)
![Screenshot 2024-03-10 144333](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10671922/375adeb0-11c5-467f-af98-9580343c668b)
![Screenshot 2024-03-10 144351](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10671922/502cc1ce-2923-4ea9-99d4-a847262aaa87)
![Screenshot 2024-03-10 144419](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10671922/99e18b8b-3c2e-4869-87af-f526443e4869)

**Comment by Saereth** [comment]
This has now been changed to use limium glass instead, good catch
