### ISSUE TITLE
Crash on typing Ches into JEI

### ISSUE THREAD

**Issue by RLightning** [FTBTeam/FTB-Modpack-Issues#4915]
### Modpack

FTB Presents Integration by Parts DX

### Modpack version

1.13.3

### Log Files

Removed log

### Describe the bug

Typing the word "chest" into JEI crashed game, C H E are good, once I hit S it instantly crashes.

### Steps to reproduce

new world
open inventory
type Chest
crash on putting the letter s

### Expected behaviour

no crash

**Comment by Gaz492** [comment]
Could you try making sure your graphics drivers are up-to-date as the log file you posted seems to indicate towards a known issue with outdated graphics drivers being the cause.

**Comment by pikminman13** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40
