### ISSUE TITLE
Applying Rat Upgrade: Beast Mount crashes and bricks FTB Direwolf20 1.20 server

### ISSUE THREAD

**Issue by nicolaihornung** [FTBTeam/FTB-Modpack-Issues#4917]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Log Files

[crash_log.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14550678/crash_log.txt)
[crash-2024-03-10_15.45.52-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14550680/crash-2024-03-10_15.45.52-server.txt)

### Describe the bug

Applying Rat Upgrade: Beast Mount (Rat Upgrade: Natural Remedy is already equipped but I don't know if this is required for reproduction) leads to my server crashing and bricking the save. I cannot get the server to start without instantly crashing once a user connects.

### Steps to reproduce

1. Start a fresh server
2. Summon a Rat
3. Apply Rat Upgrade: Natural Remedy
4. Apply Rat Upgrade: Beast Mount

### Expected behaviour

Server not crashing

### Additional information

I self host the server on on docker using using https://github.com/itzg/docker-minecraft-server.

Sadly something about my backups seems to have been broken as there was only one from today and that one is also crashing upon loading into the server so if there's a way to fix the world after this happens that would also be marvelous.

I also submitted this issue with the mod in question: https://github.com/AlexModGuy/Rats/issues/862

**Comment by Gaz492** [comment]
Did the suggestion of disabling Canary fix the issue for you?
https://github.com/AlexModGuy/Rats/issues/862#issuecomment-2002106957

**Comment by Gaz492** [comment]
Closing this as it's a duplicate, of #4903
Feel free to reply to either this issue or the one mentioned.
