### ISSUE TITLE
FTB Presents FAM server Trojan

### ISSUE THREAD

**Issue by Trish59au** [FTBTeam/FTB-Modpack-Issues#4918]
### Modpack

FTB Presents F.A.M

### Modpack version

1.1.0

### Describe the bug

Trying to download the Linix server pack for this modpack and my antivirus flagged as a Trojan
Copy of email : Online Threat Prevention
We blocked this dangerous page for your protection: https://api.modpacks.ch/public/modpack/121/11751/server/linux Threat name: Trojan.Linux.Agent.XRK Dangerous pages attempt to install software that can harm the device, gather personal information or operate without your consent.

### Steps to reproduce

Download Linix server

### Expected behaviour

Bitdefender Antivirus flags file as having a virus

**Comment by Gaz492** [comment]
This is a false positive, the server installer is visible source and can be found at https://github.com/CreeperHost/modpacksch-serverdownloader/
