### ISSUE TITLE
Amethyest Isles - ice spikes and snow too close

### ISSUE THREAD

**Issue by Lydia-Defountain** [FTBTeam/FTB-Modpack-Issues#4919]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

Is it possible to have a Amethyst island not have default biomes of ice spike and snowny plains included. Loaded it up many times and it always has those biomes close so they seem default with the plains. Can this be changed to a more neutral biome before seed biomes take over

**Comment by Saereth** [comment]
We could probably do this in a future update yeah but it wont be retroactive sadly

**Comment by Lydia-Defountain** [comment]
I'd be willing to restart to not have to deal with the ice spikes and snow on every expansion I try to make

**Comment by Saereth** [comment]
For an interm solution I would suggest installing worldedit and you can just select the region you want with //pos1 and //pos2 commands and the set the biome to plains, so you dont need to wait for us to get out a fix :)
