### ISSUE TITLE
Apoth spawners in sky village loot maybe get no ai as well?

### ISSUE THREAD

**Issue by Lydia-Defountain** [FTBTeam/FTB-Modpack-Issues#4920]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

The sky village loot spawners come with playerless and redstone by default, any way to get them to have no ai as well, or have protochorus for the no ai upgrade?

**Comment by Saereth** [comment]
No I'm not really looking to make noai easier for the pack. While nice for a mob farm its pretty terrible for actual dungeons as you can quite easily run in, slap a protochorus on spawners, leave and let stuff despawn then come back to a challengless dungeon. That is something best reserved for where it presently is, which is end gated.
