### ISSUE TITLE
make end portal quest depend on SPS quest

### ISSUE THREAD

**Issue by vencordplus-a** [FTBTeam/FTB-Modpack-Issues#4923]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

crafting end portal requires purpur block which is not obtainable without antimatter

**Comment by Saereth** [comment]
you can get purpur blocks from the lord of darkness bee

**Comment by vencordplus-a** [comment]
lord of darkness be requires purpur block too tho
