### ISSUE TITLE
Spawner does not spawn gold chu chu

### ISSUE THREAD

**Issue by Schlauchiboy** [FTBTeam/FTB-Modpack-Issues#4925]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

A spawner with a gold chu chu spawnegg inside does not spawn any gold chu chus. Other mobs can be spawned and with a spawnegg gold chu chus can also be spawned.

### Steps to reproduce

1. Place Spawner
2. Use gold chu chu spawnegg
3. Nothing is happening no matter what upgrades are used

### Expected behaviour

It should spawn gold chu chus

**Comment by Saereth** [comment]
This is some mod conflicting issue with the chu spawns conditions and apoth spawners, cant fix it on our end but I've reported it to the mod dev
