### ISSUE TITLE
IE Metal Press not accepting input

### ISSUE THREAD

**Issue by CrispyPigeon131** [FTBTeam/FTB-Modpack-Issues#4927]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

I have not been able to get any items to insert into Metal Press. I have used Hoppers, Mekanism cables and item transporter.

### Steps to reproduce

Attempt to insert item to metal press with pipes/transporter

### Expected behaviour

It should insert items automatically

**Comment by CrispyPigeon131** [comment]
![2024-03-10_18 18 42](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63083209/386ff94e-7f77-418f-85da-f6ce4b11a459)
![2024-03-10_18 18 51](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63083209/af06a69b-f3bc-4f97-b824-346eeab87fca)

**Comment by TheonlyTazz** [comment]
this seems more like an user error
https://github.com/FTBTeam/FTB-Modpack-Issues/assets/3908847/1dd46bac-3725-4107-97a5-94ac6644f4d5

Working as intended on the latest version, be sure you are inserting into the belt block and the mold is inside the press.
additionally, if u use something other than hoppers, u might need to regulate the amount of items inserted


Edit:
I even tested it again with a chest and item transporter (no further settings, except setting directions) and working as intended
https://github.com/FTBTeam/FTB-Modpack-Issues/assets/3908847/72750ae0-84b7-470a-8aa2-ba6488e72b35

**Comment by CrispyPigeon131** [comment]
I believe this is only an issue with gears. I have tested wires, rods, and sheets (as shown in your videos) and they will all insert as intended. However when I add the gear mold it wont accept anything into the metal press.  Ive recorded it in action but video is too large to post here.

**Comment by TheonlyTazz** [comment]
Yes this is correct; bcause the recipe of gears need 4 items; you need to be able to insert atleast an itemstack with 4 items (a hopper does only 1 per operation for example)
a few ways to automate gears could be:

- Omnidirectional Hoppers (Pneumaticcraft) with atleast 5 Speed Upgrades
- Integrated Dynamics (where u set the export to atleast 4items
- Modular Routers with stack upgrades
- Mekanism Advanced Logistical Transporters
