### ISSUE TITLE
Visual glitch- Archmage spellbook channeling inner butterfly

### ISSUE THREAD

**Issue by Lydia-Defountain** [FTBTeam/FTB-Modpack-Issues#4928]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

When held the archmage spellbook rather then just opening is opening and closing and flapping about weirdly.
Mine has soulbound not sure if that is a factor

### Steps to reproduce

Hold the spellbook

### Expected behaviour

Book opens but stays open

### Screenshots

![2024-03-10_20 16 38](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/12691263/6dd71a8c-2375-45c3-b855-406a8448a597)

**Comment by Saereth** [comment]
I cant reproduce this, can you try with a standard resource pack? may be related

**Comment by Lydia-Defountain** [comment]
I don't think it was the res pack but reloading into that world it has suddenly stopped. Not even sure what it was. Will close issue Sorry for the trouble.
