### ISSUE TITLE
Crash when using Cyclic Shape Builder

### ISSUE THREAD

**Issue by CraMagicka** [FTBTeam/FTB-Modpack-Issues#4929]
### Modpack

FTB Skies Expert

### Modpack version

1.4.0

### Log Files

[crash-2024-03-11_03.12.08-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14553184/crash-2024-03-11_03.12.08-client.txt)
[crash-2024-03-11_03.18.58-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14553185/crash-2024-03-11_03.18.58-client.txt)
[crash-2024-03-11_03.26.33-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14553186/crash-2024-03-11_03.26.33-client.txt)

### Describe the bug

I shift-clicked large diamond oak bordered glass from the Chipped mod while I had the Shape Builder interface open, with the intention of moving the stack in. Now I cannot join my world without it immediately crashing. I will restore from a backup.

### Steps to reproduce

1. Open Cyclic Shape Builder
2. Shift-Click Chipped large diamond oak glass
3. Crash?

### Expected behaviour

The stack of glass to move into the Shape Builder

**Comment by CraMagicka** [comment]
Update: I also had preview as being shown, it doesnt seem to crash when i make the preview hidden.

**Comment by Saereth** [comment]
because of course cyclic -_- we've disabled it for next update since this has been an issue on cyclics git for MONTHS. We'll re-enable it if they ever manage to fix it

**Comment by Belique** [comment]
The issue is still ongoing; the render still causes a significant crash when a barrier is placed in the "shape builder. Causin the loss of the world
