### ISSUE TITLE
Sequential fabricators all produce stone

### ISSUE THREAD

**Issue by Asukichi** [FTBTeam/FTB-Modpack-Issues#4931]
### Modpack

FTB Skies Expert

### Modpack version

1.4.0

### Describe the bug

If you put Productive bees chips into the Thermal Expansion's sequential fabricator, they will all turn into stones.

### Steps to reproduce

Occurs only in sequential fabricator

### Expected behaviour

This should give you the correct crafting result.

**Comment by Saereth** [comment]
sadly the sequential fabricator does not properly support nbt, this isnt something that can be changed. I'd suggest using pedestal or rftools crafter instead for your chips
