### ISSUE TITLE
Material Generator recipe changed

### ISSUE THREAD

**Issue by Lomakot** [FTBTeam/FTB-Modpack-Issues#4933]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

It seems Material Generator recipe changed to be using a Constantan Plate which is not available at that tech level.

### Steps to reproduce

1. Go to JEI
2. Material Generator recipe

### Expected behaviour

From what i saw in 1.3.3 it was without the Constantan Plate

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/12444634/cd649628-f2e3-418a-8551-e05104ed9987)

### Additional information

Maybe its intentional and i just dont get it, please confirm 😄

**Comment by ArtpokeBr** [comment]
Gonna add a piece of description to help out, but technically it is achievable in chapter 1!

- But you would require to trade with a Wandering Trade to get your first piece of nickel.

**Comment by ArtpokeBr** [comment]
But after some pondering, this recipe should require brass plates now. =)

**Comment by InfinitiesLoop** [comment]
I'm on the latest 1.9 of this pack and the recipe still requires a constantan plate, but this issue says it should be brass? Also I don't understand the Wandering Trader way of getting nickel, nothing he sells seems to be helpful for that at all.
