### ISSUE TITLE
Swapping grave manager for armor/curios slots

### ISSUE THREAD

**Issue by CoolLord22** [FTBTeam/FTB-Modpack-Issues#4934]
### Modpack

FTB Presents F.A.M

### Is your suggestion related to a problem? Please describe.

The current graves mod doesn’t support item restoring for items that go into armor and curios slots. If you have a full inventory + armor and baubles, then those items drop on the ground which can be frustrating if you’re over lava or something. 

There is another graves mod (EnigmaticGraves) that does have built in support for returning armor, baubles and even cosmetic armor that could be beneficial here. 

I did also make a support ticket for SimplyGraves to see if these slots could be returned but we’ll have to wait and see if that feature can be coded in!

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/enigmatic-graves

**Comment by UnRealDinnerbone** [comment]
Being this late into the pack it too late to change it, as we would have to have both mods in the pack, as not to remove people items currently in graves. However, for future pack we can take this into consideration
