### ISSUE TITLE
Unclear how to get Purpur blocks

### ISSUE THREAD

**Issue by GedasFX** [FTBTeam/FTB-Modpack-Issues#4936]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

Unclear how to get Purpur blocks

There are some early(ish) completable mods such as Elementcraft that get stuck on quests like Pure rock as it requires Purpur.

Looking at recipes we have:
1. Find in world gen? -> Unclear where to find that.
2. Popped Chorus Fruit [Chorus Fruit] -> Kill Cosmaw (requires end?)
3. Grow from Chorus flower:
  a. find (where from?)
  b. Use Antimatter... (..really?)
4. Bees? -> Requires purpur to pollinate

The quests make it seem like we should have access to purpur/chorus fruit, but realistically how I see its its gated behind Antimatter (as End Portal Frames require purpur blocks too).

I suggest adding a quest explaining how to get purpur (maybe even add it as a quest reward so it shows up in JEI too)

**Comment by GedasFX** [comment]
Could you add description or some flavor text to early quests that they are locked behind The End? Solution is visible, but the vibe received here is that there MUST be something that I missed, no way its antimatter to finish up Elementcraft questline.

**Comment by GedasFX** [comment]
Regardless, I think locking Chorus/Purpur so arbitrarily late in the game is a bit of a miss. Like maybe it would be cool to be able to trade from Moon villagers, would fit thematically a bit. Then you can convert to flower with Botania. 

I do think antimatter should be involved in making the end portal frames, but current gating doesn't feel fair.

**Comment by Saereth** [comment]
Lord of Darkness bee for purpur is the easiest way, it should show as a product in JEI already but yeah I can add a tool tip

**Comment by GedasFX** [comment]
Lord of darkness bees require purpur blocks as flowers to pollinate, so it's a bit of a catch-22 here 😄

**Comment by Saereth** [comment]
This was an oversight it should require a block of botania petals, will fix that
