### ISSUE TITLE
Liquid Chorus to Block of Crystallized Chorus recipe bug

### ISSUE THREAD

**Issue by mjory80** [FTBTeam/FTB-Modpack-Issues#4938]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

The recipe to craft a Block of Crystallized Chorus from Liquid Chorus in a mechanical basin is bugged, requiring 1125/1000mb to craft, which is impossible since the basin can only hold 1000mb.

### Steps to reproduce

Place Popped Chorus Fruit/Proto Chorus in a Mechanical Squeezer next to a Drying Basin or Mechanical Drying Basin and pump in the Liquid Chorus.  Note that a Block Crystallized Chorus will never craft.

### Expected behaviour

To be able to craft the Block Crystallized Chorus

### Screenshots

![chorus_recipe](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26591/e1188461-f0e4-40cd-81a2-b5ce4beae92c)

**Comment by ArtpokeBr** [comment]
Kinda intended, thx for the issue as now i've worked on a better implementation of this little gate :p

**Comment by mjory80** [comment]
> Kinda intended, thx for the issue as now i've worked on a better implementation of this little gate :p

What was intended by it?  The blocks can still be formed from the chunks you get from the squeezer.  You just can't do anything with the liquid.
