### ISSUE TITLE
KamikazBee invisible or disabled?

### ISSUE THREAD

**Issue by Humorist** [FTBTeam/FTB-Modpack-Issues#4939]
### Modpack

FTB Skies Expert

### Modpack version

1.4.0

### Describe the bug

KamikazBee seems to be either invisible or disabled in some way that they can still be seen but not caught. I've asked in the discord and noticed that Saereth said that they were not disabled but for some reason I cannot see them at all or catch them. I even tried waiting until the bees entered an advanced bee hive with a simulator upgrade installed and I heard them enter and I could not pull the out of the hive or see them. I've started from 1.0.2 and have upgraded the server from that version along the way until the version I am now on 1.4.0. I have not installed any different shaders or resource packs that are not initially already installed. No idea what could be causing this. I can see them on the map and hear them but I can not catch or see them.

### Steps to reproduce

1. Equip bees nest helmet
2. Go into an area that the bees cannot leave, I used ethereal glass
3. Bring a hostile mob with a mob imprisonment tool
4. Get hit by hostile mob until you here bees leaving the helmet
5. profit?

### Expected behaviour

Bee able to catch KamikazBee

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/35659064/c9c64a56-be0a-4c5c-ad08-da439e84623b)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/35659064/d002b715-96da-4b76-90e3-c42708d9590e)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/35659064/3c7fde6b-a570-4e9d-92cf-9296bf83528e)

**Comment by calebh514** [comment]
Can confirm that the KamikazBee exists in some strange limbo. On 1.4.1. The bees spawn when getting hit, can be heard, show up on the map as an entity. But do not exist. and I even devised a bottler box to trap them and see if they can be squished but they cannot. What's even stranger is that sometimes I can see them poof and die because presumably they spawn clipped into the blocks of my floor.

**Comment by Saereth** [comment]
I think this should be fixed in the next update now, did some testing and its working again after my fix
