### ISSUE TITLE
Apotheosis gems still dropping as normal

### ISSUE THREAD

**Issue by melbellrocks** [FTBTeam/FTB-Modpack-Issues#4940]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

Per the 1.4.0 change notes normal Apotheosis gems should not be dropping, but rather we should be getting malleable gems that we must then process into gems.  As of 1.4.1 I am still getting the normal Apotheosis gems.  I didn't check on version 1.4.0 because I skipped over that version.

### Steps to reproduce

1. Kill a mob
2. Get the wrong gem :)

### Expected behaviour

Should receive malleable gems instead of the ones that already have stats.

**Comment by Lydia-Defountain** [comment]
Are you manually killing is manual kills to get gems. I have only killed witches/enderman/goat/silverfish/slime/energetic sheep and minimics this world and 3 apoth gems. I think Witches where where I got at least 2/3 of those

**Comment by no-name-provided** [comment]
Same. Occurs with 
- natural mob spawns
- killed by hand 
- with an Immolation Blade

**Comment by ArtpokeBr** [comment]
Alright, tested here, indeed is dropping via player kills... gonna take a look at fixing this!
