### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by tombaku** [FTBTeam/FTB-Modpack-Issues#4941]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Log Files

https://mclo.gs/66PyOn5
https://mclo.gs/VHtrCQu
https://mclo.gs/sYALuLw

### Describe the bug

This has happened over the last 2 days and i'm not sure what the issue is or even how to solve it as I am not familiar enough with how the event stack works in Forge.

From what I can understand mods are adding an event to an Array without first expanding the array. however from what I know that shouldn't be possible

### Steps to reproduce

1. Go to FTB App - FTB Skies Expert 1.4.1
2. Click Play
3. Crash happens and log made before the main menu loads but after a full loading bar under Mojang Logo

### Expected behaviour

To see a Main Menu and Launch a save

### Additional information

It seems this issue is intermittent as i've attempted to launch again with the same configuration again and it worked for whatever reason

**Comment by Saereth** [comment]
I would do a fresh reinstall something is definitely not right with your installation/some corruption most likely
