### ISSUE TITLE
Eye of Mech not working

### ISSUE THREAD

**Issue by Frogiggi** [FTBTeam/FTB-Modpack-Issues#4945]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

When using eye of mech it does the animation in the hand but doesn't "shoot" the eye

### Steps to reproduce

1. put eye of mech in the hotbar
2. right click with it in hand

### Expected behaviour

Eye of mech should "shoot"

**Comment by Saereth** [comment]
the structures are disabled right now pending a future rework, I've disabled the eye as well for next update to avoid confusion
