### ISSUE TITLE
Otherworld Logs only drop from 'break' glyph

### ISSUE THREAD

**Issue by spoonypanda** [FTBTeam/FTB-Modpack-Issues#4946]
### Modpack

FTB Arcanum Institute

### Modpack version

1.3.0

### Describe the bug

Can only get otherworld logs with "break" glyph

### Steps to reproduce

1. Plant otherworld sapling
2. Eat Demon Fruit for third eye debuff
3. cut down tree with 'fell' glyph or an axe (I used the diamond one you get from a quest)
4. you get regular oak

### Expected behaviour

regardless of method, I should get otherworld log when i cut down the tree with the demon dream fruit buff

### Additional information

Either mention this in the quest book that only break glyph works, or make sure that you get the appropriate item with other cutting methods too.

**Comment by TheonlyTazz** [comment]
Sadly this is something i cannot fix, but i added it as a note in the Questbook
