### ISSUE TITLE
Crash on on "Validating selected Data Packs"

### ISSUE THREAD

**Issue by TridTech** [FTBTeam/FTB-Modpack-Issues#4949]
### Modpack

FTB Skies Expert

### Modpack version

1.1.0, 1.4.0 and 1.4.1

### Log Files

Logs from the FTB App: https://pastebin.com/RZsWTs7N
Note:  FTB app did not allow scrolling in the logs (even after disabling autoscroll), so best attempt at getting the log from the app.

Extended error report file
https://pste.ch/abugeqicoy.makefile

### Describe the bug

Crash almost immediately on selecting single player.  After launching the app and clicking single player, it crashes within a few seconds.

I've tried going down to an older version, as well as reinstalling from scratch, and nothing makes a difference.

### Steps to reproduce

1. Install FTB Skies Expert from the FTB App
2. Launch, and select "Single Player"
3. Crash

### Expected behaviour

Proceed to worldgen and be able to play the game.

**Comment by Saereth** [comment]
This is an actual jvm access violation which is something non pack specific. Could be driver realted or permissions but not something I can help troubleshoot further due to liabilites

**Comment by TridTech** [comment]
Well, after that wildly helpful comment, and trying a few other packs with no problems, I'm going to say the issue is the pack, but I can't provide any additional information due to liabilities.  Maybe the next one...
