### ISSUE TITLE
Techreborn block causes game crash

### ISSUE THREAD

**Issue by imkyro02** [FTBTeam/FTB-Modpack-Issues#4950]
### Modpack

FTB Sky Odyssey

### Modpack version

1.3.0

### Log Files

 https://paste.feed-the-beast.com/view/6f5ba0fa

### Describe the bug

Game crashes upon placing "techreborn:plate_bending_machine", and after loading the world with said block placed.

### Steps to reproduce

Load new world (Optional creative)
Get block techreborn:plate_bending_machine
Place it
Crash the game

### Expected behaviour

he game freezes and crashes

**Comment by Gaz492** [comment]
This looks to have been fixed in 1.4.0
