### ISSUE TITLE
Fusion Reactor Will Not Stay Operational

### ISSUE THREAD

**Issue by shank3001** [FTBTeam/FTB-Modpack-Issues#4951]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

I have built at least 50 of them over my Minecraft play throughs and not sure if I am missing something; however, I cannot keep the reactor running. I have over 3M  MB each of Deuterium and Tritium, my Hohlraum filled and in place, shooting it with at least 1 GFE through the laser focus via the laser amplifier. I get the animation as the reactor is properly fire up but the casing temperature goes down instead of up and the reactor extinguishes itself after a minute. I have even tried feeding it direct with D-T Fuel and the same thing occurs.

### Steps to reproduce

1. I have over 3M  MB each of Deuterium and Tritium
2. Hohlraum filled with D-T Fuel and in place in the reactor
3. Shoot it with at least 1 GFE through the laser focus via the laser amplifier. 
4.  You get the animation as the reactor is properly fire up but the casing temperature goes down instead of up and the reactor extinguishes itself after a minute.

### Expected behaviour

Reactor case temperature should increase along with the power output. Stated minimum injection rate is 8 for air cooled; however, the actual value required is 15 for the fusion reactor to stay operational.

### Screenshots

![2024-03-12_13 14 18](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10300791/3b47e8b8-8ec8-438f-a4ce-012601954c6a)
![2024-03-12_13 14 23](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10300791/0d2a5899-67d3-4c19-aa24-b65cd38098e7)
![2024-03-12_13 15 26](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10300791/7cfeb2bf-e0f7-4979-8824-0ded51473fd8)

**Comment by shank3001** [comment]
The settings within the mekanism generators config is bugged. Stated miimum injection rate is 8 for air cooled; however, the actual value required is 15. Furthermore, even at an injection rate of 60, I am only getting 160K RF/tick. This is not praticial even though this is an expert pack. Will not be able to generate enough power to feed a power hungry SPS at 15MB per tick Fissle Fuel Fission Reactor injection rate. Something is way out of balance.

**Comment by Saereth** [comment]
You should be using the heat produced by the fusion to power turbines, the raw rf production is turned WAY down on the fusion reactors but the thermal conductivity is actually buffed. You'll get millions of rf/tick using turbines

**Comment by shank3001** [comment]
Ahhhhh - very smart!
