### ISSUE TITLE
Warden despawns right after summoning.

### ISSUE THREAD

**Issue by grav0r** [FTBTeam/FTB-Modpack-Issues#4953]
### Modpack

FTB Skies Expert

### Modpack version

1.3.3

### Describe the bug

I spent the whole afternoon troubleshooting this, and i don´t make tickets or issues easily, but i couldn´t get it to work.
Under whatever circumstances i summon wardens, they always burrow into the ground right after summoning, no intention to fight. (Its not peaceful.) i can soul gem them and bring them to another place, but upon releasing, they instantly start to burrow in the ground and despawn. I tried it day and night, with light and without, with sculk and darkroom around them, with making alot of noise on sculk, with having other mobs nearby, they don´t seem to care and just start despawning right upon summoning. I tried inside and outside of my claim, and also vanilla-name-tagging him, which apparently should keep him around, but even nametagged he gets away in 2 seconds. pls try to reproduce/check.. ty alot!

### Steps to reproduce

1. Summon a warden with soul transmutation Martian Raptor
 2. Try to kill him before he gets away...

### Expected behaviour

I expect him to fight and able to get killed after summoning him.

**Comment by grav0r** [comment]
Additional info, both on 1.3.3 and on 1.4.1 and both single player and multiplayer this bug exists.

**Comment by Saereth** [comment]
This is a vanilla mechanic "After not detecting any vibrations or sniffing any nearby mobs, a warden burrows back into the ground and despawns, unless it has been named." So slap a name tag on it should prevent that.

**Comment by grav0r** [comment]
Hello, pls test it yourself. I nametagged him and he still despawned. If u spawn egg him, he has a total different behavior, might be summoning state of the pedestal maybe?

**Comment by mackfoggia** [comment]
@Saereth why was this closed? name tag doesn't work
