### ISSUE TITLE
Game Crash  on opening world to friends

### ISSUE THREAD

**Issue by bastisir** [FTBTeam/FTB-Modpack-Issues#4957]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

Game crashes on launch when trying to play minetogether (multiplayer).

### Steps to reproduce

1. Launch game, 2. Join world, 3. Open the world to friends, 4. Let friends join 5. Crash after a minute or two

### Expected behaviour

Game crash without a log.

**Comment by Schlauchiboy** [comment]
i am playing since version 1.0.0 with friends on a lan world and on every version a had zero game crashes

**Comment by bastisir** [comment]
So you are not using mine together? Only Lan?

**Comment by bastisir** [comment]
Gotcha, imma test it out and if it works thank you thank you

**Comment by Saereth** [comment]
You need to update, fullstack watchdog causes this and was removed in 1.4.1, you can also just remove the mod yourselves if you dont want to update for some reason
