### ISSUE TITLE
FTB Skies Expert - No Space Alternative

### ISSUE THREAD

**Issue by Arochio** [FTBTeam/FTB-Modpack-Issues#4960]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

i can't go moon :(

### Mod suggestion

I'm doing a no moon run in my world to challenge myself, and there are a few resources that can't be obtained, including: desh, ostrum, calorite, cheese, ice shards, and the stones/sands from each planet. this would Include adding the ability to summon corrupted lunarians/star  crawlers through the spirit mod's pedestal, and adding 4 laser lenses for the ore laser that are more expensive but give you the 3 ores and ice shards without the biome requirement. i also think the recipe for these things should be significantly more expensive than it would take if you could go to space.

**Comment by Arochio** [comment]
one of the first implementations of this should probably be a toggle to complete the moon quest so you can progress past that point in the quest book, and maybe adding desh blocks for pedestal material gens to generate moon stone, and maybe a way to get desh in orbit through the ore laser with an extremely low weight

**Comment by Saereth** [comment]
There hasnt been enough general interest in investing in this idea so closing this for now, sorry!
