### ISSUE TITLE
ME Disk Drive doesn't give all components back when disassembling

### ISSUE THREAD

**Issue by lpacphantom** [FTBTeam/FTB-Modpack-Issues#4961]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

I used sneak right click on an ME Disk Drive, received only ME Disk Housing and 16k storage component. To craft the Disk Drive requires an ME Item Cell Housing from AE2BetterHousings. I feel like all components should be refunded when trying to recycle components into higher amounts.

### Steps to reproduce

1. Sneak Right Click an ME Disk Drive.
2. Receive only 2 of 3 parts for crafting.
3. Be unable to recraft...

### Expected behaviour

All crafting components are refunded

**Comment by Saereth** [comment]
this is hard coded into ae and cant be changed
