### ISSUE TITLE
Inventory visual glitch with Create Item Vault and Crafting Station

### ISSUE THREAD

**Issue by jnashtv** [FTBTeam/FTB-Modpack-Issues#4962]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

whenever interacting with a crafting station next to a item vault all your inventory and hotbar seem to just disappear and you have you right click a hotbar slot just to get your items to reappear.   

### Steps to reproduce

1.) place down an item vault, 2.) place a crafting station next to it. 3.) put any block in your inventory. 4) open up the crafting station

### Expected behaviour

to be able to use items from the vault for crafting purposes

**Comment by Saereth** [comment]
this is a bug in the mod, I'd suggest just not using it with an item vault. It should be blacklisted but the craftstation isnt currently respecting the black list, we're waiting for an update from the mod dev to fix this
