### ISSUE TITLE
Fluid Sourcelink doesn't work with Flux-Infused Diesel

### ISSUE THREAD

**Issue by LemoNude** [FTBTeam/FTB-Modpack-Issues#4966]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

Fluid Sourcelinks from Starbunclemania has a recipe for 1B Flux-Infused Diesel -> 25600 Source. Other recipes work with no issue. With said fluid, it does nothing. 

### Steps to reproduce

1. Place Fluid Sourcelink
2. Insert Flux-Infused Diesel via piping OR buckets
3. Wait indefinitely for it to start processing 

### Expected behaviour

With every other fluids, it fills its internal buffer with source created from the fluid and distributes it among the source jars within range.

### Additional information

As the Flux-Infused Diesel being the only fluid that is coverted to more than 10000 Source, the bug is probably caused by the internal buffer of 100000 being smaller than the amount to create.

**Comment by Saereth** [comment]
looks like it cant support ratios high enough to convert those fluids so we had to limit it to the lower tier fuels :(
