### ISSUE TITLE
Thermal Series machines limited power input

### ISSUE THREAD

**Issue by BoundenDeer** [FTBTeam/FTB-Modpack-Issues#4967]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

All the machines from the Thermal Series mod seem have a limited input of 600 FE/t on each face. Tried IE wires, Mekanism cables, Flux Network's flux point, and nothing seems to be able to feed power to it over 600 FE/t. Currently its impossible to make use of any speed upgrades past the gold upgrade component with 3 flux linkage amplifier upgrades as the power is drained faster than it can be inputed

### Steps to reproduce

1. place down and Thermal Series machine
2. connect to power
3. use more that 600 FE/t and watch the power drain even after allowing more power to be available

### Expected behaviour

Machines should be able to draw more than 600 FE/t.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/161007044/ce2cb815-19b5-4cf3-ab02-a2124fdecd14)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/161007044/b1f6af9d-6386-4f03-832b-e02ce43e6264)

**Comment by Saereth** [comment]
huh this appears to be a limitation with thermal and no config option to change it.. will have to bring it up on their issue tracker
