### ISSUE TITLE
Thermalpedia can't be crafted

### ISSUE THREAD

**Issue by RedneckNoob** [FTBTeam/FTB-Modpack-Issues#4968]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12

### Describe the bug

ThermalPedia doesn't show up in JEI, it's not included in Eccentric Tome. Try to craft the Crescent Hammer to craft it, and the Crescent Hammer is auto converted to Wrench from HammerLib. Wrench from HammerLib can't be used to craft it.

### Steps to reproduce

1. Open Game. 2. Craft Crescent Hammer. 3. Try to combine with book.

### Expected behaviour

You should get thermal pedia

**Comment by Gaz492** [comment]
You should be able to select the crescent hammer by clicking on the refresh button above the output slot of the crafting table, from there you should then be able to combine it with a book to get the Thermalpedia
![hammer](https://s3.wuffs.dev/screenshots/2024/06/Parsec_2hwXmcju.png)

As for it not showing up in JEI we will need to look at what would be causing this.
