### ISSUE TITLE
[Bug]: FTB Oceanblock RFTOOLS Charger Porter crashes the game

### ISSUE THREAD

**Issue by gomesgr** [FTBTeam/FTB-Modpack-Issues#497]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Log Files

https://pastebin.com/b8vKc4ET

### Describe the bug

I'm playing the FTB Oceanblock 1.11.0 on a server i'm hosting and i encountered this problem:
Everytime i _sneak + right click_ on a **Matter Receiver** with the **Charger Porter** (basic and advanced) the game crashes.
Funny thing is, only my client game is crashing, the server still continues to run normally and when i come back to the server,
the charger porter is configured correctly.

### Steps to reproduce

1. Have a energized Matter Receiver placed
2. Sneak + Right Click on it with the charger porter to configure it
3. Crash!

### Expected behaviour

No Crash after sneaking + right clicking

**Comment by jackodsteel** [comment]
I'ved filed McJtyMods/RFToolsUtility#109 for this bug, and sent McJtyMods/RFToolsUtility#110 as a fix. Hopefully McJty reviews and merges soon :)

**Comment by Raidobw2** [comment]
Wow, much thanks jackodsteel! :)
