### ISSUE TITLE
Hexerei's Mixing Cauldron Tallow + Residue Recipe not working

### ISSUE THREAD

**Issue by ParrotParrot** [FTBTeam/FTB-Modpack-Issues#4973]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

The recipe for Tallow Residue using animal fat in the mixing cauldron from hexerei isn't currently working. The recipe will show up in JEI allowing any `hexerei:tallow_meltable` but won't be able to be automatically set up with the JEI button while using Animal Fat, despite the item directly appearing in both standalone recipe and linking it as a use for Animal Fat.

### Steps to reproduce

1. Set the mixing cauldron up over an heated block
2. Put 8 Animal Fat in
3. Recipe doesn't proceed

### Expected behaviour

Recipe should proceed and create 2 buckets of tallow and 1 tallow residue

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/6126426/7398f04e-7054-4e3d-a4f1-c42393cfc58f)

**Comment by TheyCallMeSibs** [comment]
Does it work with other meltables, such as honeycombs?

**Comment by ParrotParrot** [comment]
The recipe itself seems to be working, but requires input fluids (works with water) and will convert that liquid into tallow.
This stems from the JEI recipe being very vague about the required input fluid, as shown.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/6126426/3ac0d60c-c3be-42b0-a409-f837c3968393)
I have been unable to make any tallow impurities while using animal fat, however.

**Comment by Saereth** [comment]
this is working fine for me,
<img width="487" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/43c0ee45-3636-4383-bace-5125cbc5b1ea">

Yeah you need input fluid to make it work, specifically 2 buckets of water, you wont get impure tallow with only 1 bucket. Yeah its wierd jei doesnt show that well but the book of shadows does explain it. It's been reported to the mod dev so maybe they can make the jei render more clear in the future.

**Comment by krisavi** [comment]
I tried it with honey comb, animal fat, even tried with vanilla candles. 2 buckets of water, 1 bucket of water, still no tallow impuritiy... I now have 32 buckets of tallow which I never wanted. Just wanted impurity to eat for hearts progress.
