### ISSUE TITLE
Salvaging table not accepting affixed weapons/tools/armor

### ISSUE THREAD

**Issue by tiniestfeet** [FTBTeam/FTB-Modpack-Issues#4974]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

Try to put affixed item into salvaging table, will not accept.

### Steps to reproduce

Find affixed loot in villages.

Craft salvaging table.

Try to input affixed loot into salvaging table.

### Expected behaviour

Input affixed item, get reforging materials.

**Comment by Saereth** [comment]
This is not a bug, salavaging reforing components is disabled, you need to loot the actual forging components
