### ISSUE TITLE
Dreamwood unable to be crafted in Mechanical Daisy

### ISSUE THREAD

**Issue by ItsNora** [FTBTeam/FTB-Modpack-Issues#4978]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

When attempting to craft Dream wood block (not Log) in the Mechanical Daisy, the daisy auto converts to living wood.

From what is presumed, Dream wood is being input back into the blocks input before being output, this seems to be due to the Dream wood block(s) being apart of the tag list for available items to make Living Wood

### Steps to reproduce

1. Input Elven wood into Mechanical Daisy from Botanical Machinery
2. Wait for conversion
3. Output will quickly show the expected block of Dream Wood, then covert to Living Wood

### Expected behaviour

Elven wood should only be converting to Dream Wood block

### Additional information

From testing, it seems like the Dream wood is apart of the tag list for available items / blocks to convert into Living Wood. If this can be removed / separated, this should resolve the issue.

**Comment by Saereth** [comment]
dreamwood is part of the general minecraft:logs tag, you could remove it from that tag (which is what pure daisies use) but then they become unusable in any recipe that uses logs which is less than ideal. Seems like the mod blocks inserting living wood which has the same tag but there is no config or anything to blacklist blocks that can be inserted so I cant forge dreamwood to have the same limitaiton. This is something that will need to be sorted by the mod dev but I'll open an issue with them.

**Comment by Saereth** [comment]
https://github.com/TheDrOfDoctoring/mechanicalbotania/issues/1

**Comment by Saereth** [comment]
https://github.com/MelanX/botanical-machinery/issues/64
