### ISSUE TITLE
Source jars quest not completing

### ISSUE THREAD

**Issue by krisavi** [FTBTeam/FTB-Modpack-Issues#4983]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

I have crafted quite source jars since version 1.1.0 I think. Tried to craft new one on 1.4.1 to trigger quest completion, but quest seems still with grey checkmark like some dependency is missing. Only dependency that it has, albeit not shown in spellbook is archwood saplings and it is done as well. I cannot seem to complete quests that depend on source jar either. Quests like Basic Spell Turret and Warp Scroll.

### Steps to reproduce

Craft Source Jar...

### Expected behaviour

Quest to mark as completed and progress available on dependent quests

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1912568/698d4228-6822-4b42-9e27-f727a3332b97)

### Additional information

Might be due to version updates and changes in quest book. Unfortunately I cannot edit quest book to fix the quest progress.

**Comment by krisavi** [comment]
Seems to be same as #4789
Any details on what quest needs to be complete in order to progress? I have crafted reaper gen mentioned in there?

**Comment by Saereth** [comment]
yeah this is a duplicate, just gotta figure out which task isnt completed that was updated, super annoying and I hope desht can fix it in ftbquests at some point but yeah the dependencies are all correct

**Comment by Nagapito** [comment]
> yeah this is a duplicate, just gotta figure out which task isnt completed that was updated, super annoying and I hope desht can fix it in ftbquests at some point but yeah the dependencies are all correct

I was looking into this and noticed that the dependency is to a "Archwood Sapplings" but the quest is called Archwood Sappling".
It is depending on the task, not the quest, that is why it does not enable!
