### ISSUE TITLE
Second quest in Pneumaticraft chain requires wrong number of pressure chamber walls because of typo

### ISSUE THREAD

**Issue by Meta-Didact** [FTBTeam/FTB-Modpack-Issues#4984]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

The second quest in the pneumaticraft chain asks the player to acquire 91 pressure chamber walls.

This is a typo as 19 walls + the other items the quest asks for would create the 3x3x3 pressure chamber the quest recommends.

### Steps to reproduce

Open the quest labeled 91x Pressure Chamber Wall in the Air Bending And You! or II - Getting on Up sections of the quest book.

### Expected behaviour

The required number of pressure chamber walls should be 19

**Comment by Saereth** [comment]
will get this fixed for the next update (not 1.5.0 as thats already done)
