### ISSUE TITLE
FTB Skies Expert - Cannot join partner hosting on LAN

### ISSUE THREAD

**Issue by arcanine537** [FTBTeam/FTB-Modpack-Issues#4987]
### Modpack

FTB Skies Expert

### Modpack version

1.5.0

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14625980/debug.log)

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14625981/latest.log)

### Describe the bug

Trying to join my partner who is on the same network as I am, I get an error screen when joining that says "Connection Lost Internal Exception: java.lang.IllegalArgumentException: ItenStackIngredients cannot be created using the empty ingredient." and it gives me the option to go back to server list at that point. 

Searching for the text "IllegalArgumentException" in the debug.log file returns that Mekanism seems to have a recipe (or three) that may be having an issue that is causing LAN join to fail. Have attached log files.

### Steps to reproduce

Partner is playing on Linux machine, I am playing on a windows machine. 
When joining partner opens to LAN, I try to join, it loads in, before I ever see the world on my machine, the game crashes (the hosting player sees me apparently log in, and immediately back out). 

### Expected behaviour

Please help get the game so I can join a multiplayer instance.

### Screenshots

![error](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/59538674/5d0d3a93-6b37-4194-be01-0be96a16dfba)

**Comment by arcanine537** [comment]
Note: Reverting the pack on both machines to 1.4.1 removes this issue for us.

**Comment by arcanine537** [comment]
Sorry, hit the wrong button. 
Note: Reverting the pack to 1.4.1 on both machines removes this issue for us.

**Comment by krisavi** [comment]
Both were on same version? Or your partner was still on 1.4.1 and you downloaded pack and it came with newest version?

**Comment by arcanine537** [comment]
Yes, we were both on 1.5.0 when the error occurred.

**Comment by Schlauchiboy** [comment]
works for me on every version

**Comment by TinkerWorX** [comment]
This error is present in 1.8.1 as of today.

**Comment by pimvandenbroek** [comment]
Issue is still present in 1.9.0. 'Fixed' it by removing supplementaries, but am missing a bunch of rewards now.
