### ISSUE TITLE
unbreakable oak logs

### ISSUE THREAD

**Issue by Warlords999** [FTBTeam/FTB-Modpack-Issues#4988]
### Modpack

FTB Skies Expert

### Modpack version

1.5.0

### Describe the bug

can not break any oak logs i just says unbreakable in the tool bar of what i am looking at and will not let me break them

### Steps to reproduce

just play the game and not letting break the block

### Expected behaviour

says unbreakble

**Comment by Warlords999** [comment]
![2024-03-17_01 33 01](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/82765179/ab69b9f5-67af-4989-b80b-bb3a4b489d68)
![2024-03-17_01 32 49](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/82765179/3559e451-cc39-4de8-995e-60323ea42f0b)

**Comment by MrSelenix** [comment]
You have to use correct tools in order to mine many block types. Following the quest line should lead to getting a basic axe.
