### ISSUE TITLE
[Bug]: Game crash on empty soundEvent

### ISSUE THREAD

**Issue by tmjnsn** [FTBTeam/FTB-Modpack-Issues#499]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Describe the bug

16:10:39.703
[16:10:39] [main/WARN] [minecraft/SoundEngine]: Unable to play empty soundEvent: minecraft:entity.tropical_fish.ambient
16:11:03.253

16:11:03.253
A fatal error has been detected by the Java Runtime Environment:
16:11:03.253

16:11:03.253
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff826e8ce60, pid=6560, tid=952
16:11:03.253

16:11:03.253
JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
16:11:03.253
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode windows-amd64 compressed oops)

### Steps to reproduce

Unknown. Possibly encounter a tropical fish.

### Expected behaviour

Game not crashing

**Comment by Raidobw2** [comment]
1. Try to update your sound drivers from the manufacturer's site.
2. Make the FTB App use your latest installed Java 8 64 bits, add the argument `-version:1.8+` to that instance. You can do that in the instance settings, inside the FTB App.

If that didn't fix it, I suspect a corrupted OpenAL lib or something else interfering with it. If so I'll need to investigate more, if you can get me that Java crash under your modpack instance that'd be great. It'll look like `hs_err_pid`. Thanks.

**Comment by Raidobw2** [comment]
Have not received a response from user, this will be closed. If this persists, visit us in the FTB Discord support channels.
