### ISSUE TITLE
Minecraft Wandering traders not visible

### ISSUE THREAD

**Issue by Abraxos12** [FTBTeam/FTB-Modpack-Issues#4995]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

Bug does not cause crash located this on a server however. The wondering traders spawn but remain invisible always even when not at night time. Ive tested this multiple times trying to use commands to summon the wandering trader and they spawn invisible i cant interact with them or anything but i hear they are in the area.

### Steps to reproduce

1: Summon wandering trader
2: look around in confusion
3: click around in area where wandering trader should be or can be heard from

### Expected behaviour

Summon the trader he is invisible but you can hear him you cant interact with him

**Comment by HeProtecButAtac** [comment]
Did you find a solution? I'm also experiencing this issue.

**Comment by Gaz492** [comment]
I'm not able to replicate this issue at the moment, do you have a no soliciting sign around your base or anything else from the nomowanderer mod?
