### ISSUE TITLE
Gamestages do not progress in FTB F.A.M

### ISSUE THREAD

**Issue by Crazysua** [FTBTeam/FTB-Modpack-Issues#4999]
### Modpack

FTB Presents F.A.M

### Modpack version

1.0.0

### Describe the bug

Gamestages do not complete when defeating the respective bosses. For example, in our server we have defeated the Leviathan boss, however the mekasuit and meka-tool still show as locked behind the leviathan stage and are also not craftable. When using the ingame command for the gamestages, it shows the leviathan stage to be completed as well. This was also reproduced in singleplayer.

### Steps to reproduce

1. Go to Sunken City
2. Kill the Leviathan Boss
3. Try to craft the Mekanism MekaSuit
4. The recipes are not unlocked and can not be crafted

### Expected behaviour

The crafting recipes of the MekaSuit and Meka-Tool should unlock

**Comment by Squall0182** [comment]
Same issue as above, but Ur-Ghast proc for the warp scroll didnt work.

**Comment by UnRealDinnerbone** [comment]
I'm unable to reproduce this issue. And for the Ur-Ghast issue, FAM doesn't lock warp scrolls behind that it in the vending machine
