### ISSUE TITLE
CC:Tweaked recipes are incorrect in MP with updated server

### ISSUE THREAD

**Issue by RobertBouillon** [FTBTeam/FTB-Modpack-Issues#5001]
### Modpack

FTB Skies Expert

### Modpack version

1.5.0

### Describe the bug

CC:Tweaked recipes are not correctly updated in MP after updates from 1.4.0 and 1.4.1.

### Steps to reproduce

1. Install 1.4.0 MP Server
2. Play game
3. Update to 1.4.1
4. Update to 1.5.0
5. Recipes for Computers only require redstone

### Expected behaviour

Recipes for computers are progression-locked

## Multi-Player 1.5.0
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/612152/3224e009-ca0f-4033-8ad2-0933c2818261)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/612152/e1bd5cfe-7db2-4d98-8fd1-93017f7cca98)

## Single-Player 1.5.0
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/612152/2fdf0584-6846-4c2e-964a-434aac009937)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/612152/56caac4e-8d1a-49e7-a9a7-f6d945380a68)

**Comment by RobertBouillon** [comment]
WORKAROUND: I copied the `kubejs/server_scripts` folder from my client to the server and restarted the server.

This seems to have resolved the issue, however I'm not sure if the underlying cause has had other negative effects.

**Comment by Saereth** [comment]
yeah no thats fine, just sounds like the server didnt update properly

**Comment by RobertBouillon** [comment]
Would this warrant a fix in the updater, then? I had no indication that something failed.

How can I install 1.5.0 fresh and restore my world to the fresh instance?
