### ISSUE TITLE
Tetra soulsteel tools have broken keys and stats

### ISSUE THREAD

**Issue by CyberFoxar** [FTBTeam/FTB-Modpack-Issues#5003]
### Modpack

FTB Skies Expert

### Modpack version

1.5.0 (ID 11766)

### Describe the bug

When modifying a tool using the tetra workbench, it is possible to use soul steel as a tool/blade head and part.

When doing so, the tooltip have missing translation keys, and the stats seem to default to be on-par with wood and/or stone tools, which seems odd given that the _actual_ soulsteel tool are inbetween diamond and iron.

A soulsteel pickaxe head also does not have the required level to mineobsidian.

### Steps to reproduce

1. Make tetra workbench
2. Acquire level 2 tetra hammer
3. Acquire around 4 soul steel ingots and a stone pickaxe
4. In tetra workbench, change both sides of the stone pickaxe to soulsteel pickaxe
5. Behold broken language keys and weird stats and modifiers, as well as a mining level no better than iron (4) and a visual that does not match with the one from Spirits

### Expected behaviour

Either fix the strings and stats, or remove the ability to use soulsteel as a tetra material

### Screenshots

![javaw_b16ZLtAb3b](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1347036/8ec84858-bd12-4cd6-8a83-3991a54f7d32)
![javaw_fALtSaTnby](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1347036/441040c4-90f3-4114-80d7-c03feeb7ee37)
![javaw_3VJMKq6WMP](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1347036/c86e93a9-52bd-47cc-aee9-ae80ce42ae1c)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1347036/908fca07-2ae5-4039-bb97-0724136d47e4)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1347036/911a7576-7a3d-4457-9973-090f7b846a21)

### Additional information

I am available on discord at cyberfoxar

**Comment by Saereth** [comment]
the localization there is a bug I cant fix due to a bug in when the langfiles are injected, as for it being iron level, thats intended as to not circumvent tetras standard progression dynamics. It's basically just not a great material but people can use it pre iron ingots to progress tetra beyond iron before they get to iron if they want to push that.
