### ISSUE TITLE
Mobs not Spawning on dreadful dirt in Nether - same as (re:3622)

### ISSUE THREAD

**Issue by Rithenar** [FTBTeam/FTB-Modpack-Issues#5004]
### Modpack

FTB Skies

### Modpack version

1.4.1

### Describe the bug

Dreadful dirt in the nether does not spawn blazes or wither skeletons

### Steps to reproduce

1- make a spawning area with low light level
2- place dreadful dirt (rotten egg)
3- lots of endermen, piglins and magma cubes spawn

### Expected behaviour

blazes and wither skeletons to spawn as well

### Additional information

Same as issue #3622 which shows closed and completed on 12/6/23. I have 1.19.2-0.4.50, downgraded to 1.19.2-0.4.49 and they are spawning now

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
