### ISSUE TITLE
Obsidian dust is not craftable in Multiservo press

### ISSUE THREAD

**Issue by RobertBouillon** [FTBTeam/FTB-Modpack-Issues#5006]
### Modpack

FTB Skies Expert

### Modpack version

1.5.0

### Describe the bug

Crafting recipe for Obsidian -> Obsidian Dust in Multiservo press is unusable because the source Obsidian is the Block of Obsidian from Jaopca, which is uncraftable.

### Steps to reproduce

1. Craft a multiservo press
2. Try to use the press to compress the obsidian

### Expected behaviour

Multiservo press converts obsidian to dust

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/612152/87f1220d-cf7f-46c7-b28f-2820cc5e0b32)

**Comment by kmadstarh** [comment]
This seems like an "unpacking" recipe for a storage block for obsidian dust, rather than an obsidian to obsidian dust recipe. I think the most likely solution here is complete removal of the "Block of Obsidian" from JEI/recipes.
