### ISSUE TITLE
Small Apothic Gate pearl doesn´t drop any rarity materials

### ISSUE THREAD

**Issue by grav0r** [FTBTeam/FTB-Modpack-Issues#5010]
### Modpack

FTB Skies Expert

### Modpack version

1.5.0

### Describe the bug

The apothic gate pearl is not sustainable. It costs 2 godforged pearls and 6 arcane sands to craft besides dropping nothing but affix items. Regarding the scarcity of the godforged pearls and all rarity materials in general many players think this might be the only reliable way of obtaining rarity materials but they don´t drop. 

### Steps to reproduce

1. Craft a "small apothic gate pearl"
2. Beat all three waves
3. Get nothing.

### Expected behaviour

At least break even if u master the challenge, maybe have a small surplus of materials.

**Comment by kmadstarh** [comment]
Agreed. If all I want is to fight apothic bosses for their loot I'm better off waiting for loot bees to drop the boss tokens, and save the rarity materials for later use.
