### ISSUE TITLE
Windmills/Waterwheels producing too much SU.

### ISSUE THREAD

**Issue by nlobdell** [FTBTeam/FTB-Modpack-Issues#5011]
### Modpack

FTB Skies Expert

### Modpack version

1.5.0

### Describe the bug

Hello I am having an issue with the waterwheels and windmills on my multiplayer server.
They should be capped at 64 but instead are showing 8,192 max and 512x RPM.
My create config shows the correct values so it is being overwritten somewhere.
I have tried reinstalling the pack after deleting config and kubejs folder.

### Steps to reproduce

1. Log onto server.
2. Open inventory.
3. Search "windmill" or "waterwheel".
4. See incorrect SU values.

### Expected behaviour

Waterwheels and Windmills should be capped at very low SU production.

### Screenshots

![image 1](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/70344419/058a9fad-984a-4b3a-840d-6b2007a0c5ab)
![image 1](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/70344419/8ac2e77d-1f05-4a79-b91e-ea3ae52612dc)

**Comment by kmadstarh** [comment]
That's an odd bug you've got there. I'm not experiencing the same on my server. Does this also happen in SP?

**Comment by nlobdell** [comment]
No it does not happen in SP. And changing the create-server.toml in the server config folder within the world folder and restarting the server results in the toml file being reverted to the wrong values.

**Comment by Saereth** [comment]
I cant reproduce this but you should be able to shut down the server then copy the default config files into your world/serverconfig files to correct it, allowing it to overwrite. Its important this is done with the server offline.
