### ISSUE TITLE
Please add a russifier

### ISSUE THREAD

**Issue by Crazymaks3** [FTBTeam/FTB-Modpack-Issues#5014]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

Add a function so that the quests can be translated into different languages, because it is very difficult for many to perceive what is written in the quests. I would like this feature to be available for all your builds.

**Comment by tr0llfeedi4** [comment]
Yes, I've encountered a problem in the build "FTB Inferno", all lines are contained in SNTB files, which makes the translation process very difficult, as an example of an ideal implementation to simplify the life of translators build "FTB University 1.19" all lines in 1 file `./kubejs/assets/<ftb_modpack_name>/lang/en_us.json`, very convenient!

**Comment by tr0llfeedi4** [comment]
I found a solution to the FTB Inferno translation problem, but it will only work for 1.18.2 - FTB Quests: Localisation keys generates a ftb-conv folder which contains modified *.SNTB files (all strings are replaced by variables) as well as a modified localisation file considering the new *.SNTB

I hope this information will be useful to someon

source code: https://github.com/Horeak/ftb-quest-lang-generator

**Comment by Saereth** [comment]
We've actually ported a mod to conver to lang files so we can support multiple languages, we'll be converting to lang files for the quests and setting up a repo for people to crowdsource translate. This will not be for the 1.8 update but likely for the 1.9 update
