### ISSUE TITLE
Add Simple Shops Mod

### ISSUE THREAD

**Issue by twofrind1** [FTBTeam/FTB-Modpack-Issues#5016]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

This is a mod that allows server shops to be setup/would be ideal for an multiplayer economy because this mod is server-side and client-side  plus could be used to make player-shops in larger servers too

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/simple-shops

**Comment by Saereth** [comment]
since this mod is ARR I need perms from the dev to include it, I've reached out to them, we'll see
