### ISSUE TITLE
Bulk Haunting Recipe for Soul Powder

### ISSUE THREAD

**Issue by Timmy3921** [FTBTeam/FTB-Modpack-Issues#5019]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

As the title says, it would be nice to have the option to bulk haunt glowstone for soul powder for people looking to set up a reaper gen farm. I can automate dropping glowstone into a soul fire, so a bulk haunting recipe isn't necessary, but it would nice for people using create set-ups.

**Comment by isochronous** [comment]
You can do this purely with create as well pretty easily: drop onto soul sand with a chute, blow it towards a brass funnel with a filter on it. That said, I too wouldn't mind a bulk haunting recipe, just wanted to point out it's already possible with "create set-ups".

**Comment by Timmy3921** [comment]
I know, that's why I said it isn't necessary. Just a nice addition.
