### ISSUE TITLE
[Bug]: RFToolutility Environmental Controller isn't working

### ISSUE THREAD

**Issue by meson11** [FTBTeam/FTB-Modpack-Issues#502]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Describe the bug

RFToolutility Environmental Controller isn't working. OneProbe shows: Inactive (#322013)

### Steps to reproduce

Build Environmental Controller. Put some Modul in it.

### Expected behaviour

Working

**Comment by Raidobw2** [comment]
Just to check, did you...
- Power it with redstone or configure the GUI to not require a signal.
- Give it some energy, like Redstone Flux (RF)
- Set the range correctly
Thanks for letting us know that info!

**Comment by meson11** [comment]
Yes, did all of this.

**Comment by Raidobw2** [comment]
Thanks, I've relayed it to the mod author, we'll wait for an update. You can adjust the range slighty or set the first range to 0 and it'll start working. Then adjust the range to your liking and it should be fine from there. See linked ^ issue for a visual representation of that in action.

**Comment by Raidobw2** [comment]
Fixed in 3.17 and now released. I'm astonished by the speed of that fix!
![image](https://user-images.githubusercontent.com/17010632/147545435-1ba0d38e-5d5c-4295-b596-2cdcdbf6df4f.png)
