### ISSUE TITLE
FTB Skies Expert - 1.4.1 - Recipe bug 

### ISSUE THREAD

**Issue by Grimjahk** [FTBTeam/FTB-Modpack-Issues#5020]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

Issue: Recipe for Basic Control Circuit in the Fabrication Matrix is the same as the fluid Encapsulator Recipe for the Advanced Control Circuit.  Requiring a Signalum processor (2x basic Control Circuit) to make one Basic Control Circuit.  I think the intended recipe is for the Advanced Control Circuit instead.

### Steps to reproduce

Recipes shown in JEI

### Expected behaviour

Fabrication Matrix recipe for Advance control Circuit does not exist, instead rewards 1 Basic Control Circuit at the cost of 2 Basic Control Circuits

**Comment by krisavi** [comment]
Duplicate of #5017 ?

**Comment by Grimjahk** [comment]
Duplicate of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5017.
