### ISSUE TITLE
powered centrifuge recepies

### ISSUE THREAD

**Issue by fishecod000** [FTBTeam/FTB-Modpack-Issues#5021]
### Modpack

FTB Skies Expert

### Modpack version

1.5

### Describe the bug

the powered centrifuge recipes to process comb were removed.

### Steps to reproduce

n/a

### Expected behaviour

either add the recipes back or remove the recipe and quest for the centrifuge

**Comment by Timmy3921** [comment]
The powered centrifuge is now just used for handling squashed bee material. It's intended to be that way.
