### ISSUE TITLE
Creative Source Tank didnt drop itself when mined.

### ISSUE THREAD

**Issue by grav0r** [FTBTeam/FTB-Modpack-Issues#5024]
### Modpack

FTB Skies Expert

### Modpack version

1.5.0

### Describe the bug

Creative Source Tank didnt drop himself when mined. I used a Refined Obsidian Paxel but after that went to my test world and tested all other Paxels as well as Pickaxes. It did not drop itself with any tool. Pls fix.

### Steps to reproduce

Mine the creative source tank, watch it disapear :)

### Expected behaviour

Drop like normal source jars after mining so it can be placed again.

**Comment by Saereth** [comment]
this is hard coded to break when broken, I cant even datapack override the loot table so uhh just use a cardboard box to move them I guess
