### ISSUE TITLE
Crash on start up.

### ISSUE THREAD

**Issue by JayVBG** [FTBTeam/FTB-Modpack-Issues#5026]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Log Files

	NeoForge: net.neoforged:47.1.84
[15:55:25] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 22c23a24-8da5-4021-b1c3-05d07d1d494b
[15:55:26] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID b0f933c7-2912-4cc0-a7f3-f9337a69ccc3
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\jayva\AppData\Local\.ftba\instances\f3891787-a955-426b-8762-d9b3df0d6f67\crash-reports\crash-2024-03-21_15.55.25-client.txt

### Describe the bug

game gets to loading screen then crashes and states "instance has crashed during startup or whilst running"

### Steps to reproduce

launch game from FTB app.  It begins to load and crashes.

### Expected behaviour

Game loads

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/164410911/533e5790-033a-44e1-87bc-b4b9d1b05979)

**Comment by Gaz492** [comment]
Would you be able to upload the full crash report for us so we can take a look?
https://docs.feed-the-beast.com/docs/app/Instances/instance-logs#locating-crashlogs
