### ISSUE TITLE
Blazeburner consuming thermal reservoir (and adding incorrect amount of fluid)

### ISSUE THREAD

**Issue by klobass** [FTBTeam/FTB-Modpack-Issues#5027]
### Modpack

FTB Skies Expert

### Modpack version

1.5

### Describe the bug

"feeding" blaze burner (with straw) force infused diesel using thermal reservoir - consumes reservoir and feeds only 700mb (while consuming 32.000mb)

### Steps to reproduce

1. prepare thermal reservoir full (32b) of force infused diesel
2. prepare blazeburner with straw
3. 
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/31200493/5809a7ad-da19-42d6-a9e4-cee2c070563d)
4. feed blazeburner force infused diesel using thermal reservoir set to empty mode
5. .....
6. ????? 
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/31200493/f7061748-2064-4928-80d0-a19dfab5bd73)

expected result - leaving reservoir in hand consuming 4b of force infused diesel and blazeburner having full tank of force infused diesel
current result - blazeburner consumed whole reservoir of force infused diesel (32b) and is having only 700mb of force infused diesel in tank

### Expected behaviour

expected result - leaving reservoir in hand consuming 4b of force infused diesel and blazeburner having full tank of force infused diesel

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/31200493/5809a7ad-da19-42d6-a9e4-cee2c070563d)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/31200493/f7061748-2064-4928-80d0-a19dfab5bd73)

**Comment by Saereth** [comment]
Yeah this is a limitation of the mod since they seem to hardcode container interactions. You should pipe into/out of them instead to prevent this
