### ISSUE TITLE
Cyclic Ender Book Crash

### ISSUE THREAD

**Issue by CamdenSegal** [FTBTeam/FTB-Modpack-Issues#5028]
### Modpack

FTB Skies Expert

### Modpack version

1.5

### Log Files

[debug-1.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14725282/debug-1.log)

### Describe the bug

It's unclear if the Cyclic ender book is intended to allow cross dimensional teleportation but currently when it is attempted it causes long pause followed by a crash to desktop.

Upon reopening the save the teleport resolves allowing for cross dimensional teleportation, as long as you are ok with the CTD.

### Steps to reproduce

1. Get Ender Book with cross dimensional location bound.
2. Sneak right click to start teleport.
3. Wait for teleport to initialize.

### Expected behaviour

Either a message that cross dimensional TP isn't allowed, or no CTD.

**Comment by Saereth** [comment]
report to cyclic but seeing as its cyclic.. wouldn't expect a fix anytime soon
