### ISSUE TITLE
[Bug]: Tesseract does not transfer items TO a Pipez item pipe

### ISSUE THREAD

**Issue by rmccarthy1504** [FTBTeam/FTB-Modpack-Issues#503]
### Modpack

FTB Ultimate Anniversary

### Modpack version

1.1.0

### Describe the bug

Chest with items in > Pipez mode 'item pipe' connected to chest, extracting from chest.
Tesseract has items channel setup.

On the other side.

Tesseract > Pipez mod 'item pipe' connected to an output chest, set to extract from tesseract.

![image](https://user-images.githubusercontent.com/68466998/147425835-dfde4bd6-9957-4bf7-9056-0cc662b6e993.png)

### Steps to reproduce

Set up as shown in picture.
Items to not transfer.

Place tesseract directly on chest, on the outputting side, and items do transfer.

### Expected behaviour

Items should transfer through item pipes

**Comment by Raidobw2** [comment]
Hmm, not sure if we can qualify that as a bug, but we'll look into. Pipez pipes don't expose an inventory like some other pipes do sometimes. Doing this will work for example:
![image](https://user-images.githubusercontent.com/17010632/147437621-af9270b8-c718-4b22-8c1a-c4ebbf390905.png)
And yes, those chests have different textures. Idk, I just skipped midnight at my place. Kind of a cool "bug" with the textures really!

**Comment by LatvianModder** [comment]
Yeah I dont think this is a bug really just maybe something user might not expect. You could re-open it on Tesseract issue tracker maybe to support Pipez or the other way around, but I'm gonna close it here
