### ISSUE TITLE
Cyclic Builder error with Mason Workbench modified block.

### ISSUE THREAD

**Issue by TheLoneDude** [FTBTeam/FTB-Modpack-Issues#5031]
### Modpack

FTB Skies

### Modpack version

1.4.1

### Log Files

 
[crash-2024-03-22_16.47.00-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14727581/crash-2024-03-22_16.47.00-client.txt)

### Describe the bug

When attempting to place Brick blocks, modified at a Mason's Workbench, into a Cyclic Builder, my game crashed, and I have not been able to get back into my world without it crashing again.

### Steps to reproduce

1. Get some blocks you can change on a Workbench. (I used Bricks on a Mason's Workbench, though this might cause an issue with any modified block [Untested])
2. Manually insert the blocks into the Builder's internal inventory. 

### Expected behaviour

Blocks should go into Builder's internal inventory without issue.

### Additional information

This has caused the world to crash immediately after loading with any attempt to return to it.

**Comment by ArtpokeBr** [comment]
Tested and it seems to not be happening here? maybe the recent Cyclic Updated fixed this.

After the Next update, if this still persists, please let me know.
