### ISSUE TITLE
Quantum Bridge Card Does Not Appear To Be Working

### ISSUE THREAD

**Issue by shank3001** [FTBTeam/FTB-Modpack-Issues#5038]
### Modpack

FTB Skies Expert

### Modpack version

1.60

### Describe the bug

Quantum Bridge Card Does Not Work Cross-Dimensionally or works beyong the range of the installed wireless booster cards.

### Steps to reproduce

1. Craft Quatum Bridge Card
2. Install in AE2 Teminal
3. Go into another Dimension
4. Try to open Crafting Terminal 
5. Indicates wireless Out Of Range

### Expected behaviour

Wireless Terminal should open in any dimension

### Screenshots

![2024-03-23_22 45 32](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10300791/04d4c9d8-dca0-4404-8f07-d4047faeaccb)
![2024-03-23_22 46 00](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10300791/aea417ad-879d-43d0-b5bb-beae5a05fd9a)

**Comment by shank3001** [comment]
Process apparently changed dramitiaclly since 1.19.2, so I am going to post the instructions to get this woking (I might suggest to add the instructions to a possible questline). Instructions are as follows:

1. Create Singularity using Matter Condensor.
2. Create Quantum Entangled Singluarity Pair (exploding TNT with Singularity and Ender Pearl or Ender Dust). This creates an entangled pair.
3. Craft Quantum Bridge Card.
4. Craft 8 Quantum Rings and 1 Quantum Link Chamber.
5. Build Quantum Bridge (Surround Quantum Link Chamber by the 8 Quantum Rings).
6. Link Quantum Bridge to AE netowrk via cable (can only link to top, bottom, or sides, not on the corners of Quantum Ring).
7. Craft Wireless Access Point and attach to Quantum Bridge (again, can only attach to top, bottom, or sides, not on the corners of Quantum Ring).
8. Craft Security Terminal and attach to Quantum Ring.
9. Craft Wireless Crafting Terminal (one of many options).
10. Insert one of the Quantum Entangled Singluarity Pairs in the Link Chamber.
11. Insert other Quantum Entangled Singluarity in the Wireless Crafting Terminal along with the Quatum Bridge Card. They are slot specific and on the right hand side.
12. Insert Wireless Crafting Terminal into the right-hand slot of the Security Terminal to link it to the Quantum Bridge.
13. You now have infinite cross-dimensional wireless AE access.

**Comment by shank3001** [comment]
Please change to suggested.

**Comment by Saereth** [comment]
This functionality is well documented with AE now so I dont consider it a pack issue anymore
