### ISSUE TITLE
Coconut Takes Too Long To Cut With Sword to Create Coconut Chunks

### ISSUE THREAD

**Issue by shank3001** [FTBTeam/FTB-Modpack-Issues#5039]
### Modpack

FTB Skies Expert

### Modpack version

1.60

### Describe the bug

Coconut Takes Nealy 15 seconds To Cut With Sword. This does not allow for automation and you need 4,000 cocunut chunks to clear final Pina Colada task. Because of this delayed interaction you cannot automate via Cyclic User, Create Deployer, Pedestals, Modular Routers, or Integrated Dynamics. 

### Steps to reproduce

1. Plant Palm Tree
2. Once grown try to left click on coconut with sword.

### Expected behaviour

Should only take one hit with sword to create coconut chuck

### Screenshots

![2024-03-24_00 20 50](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10300791/5ce3851d-c5f2-4317-b685-c3b466ce0e9a)

**Comment by ArtpokeBr** [comment]
You can still use a Deployer tho.

**Comment by shank3001** [comment]
Thanks for the impending fix. I did try using a deployer with a sword on 256 speed, would not work.

**Comment by shank3001** [comment]
My not so elegant, brute force method netting about 100 coconut chunks per hour based on the current mechanics. Only need to AFK 40 hours and I am golden :) 
![2024-03-26_21 00 36](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10300791/d5a03ce8-e32b-44a0-9d05-3303eb40d12a)
![2024-03-26_21 03 09](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/10300791/7fd6a708-d3e0-4d86-b62e-7482f1a9007a)
