### ISSUE TITLE
Pressurized reaction chamber internal energy storage

### ISSUE THREAD

**Issue by MrSelenix** [FTBTeam/FTB-Modpack-Issues#5043]
### Modpack

FTB Skies Expert

### Modpack version

1.6.0

### Describe the bug

Is it intentional to have the Mekanism Pressurized Reaction Chamber's internal energy buffer be only 800 FE, when many other machines have energy buffers of 8 kFE -> 64 kFE. It means that probably most recipes, in my current instance, silicon -> Printed Silicon, gives the error "Not enough energy to operate" without the use of energy upgrades

### Steps to reproduce

n/a

### Expected behaviour

Unless this was intentionally changed, having an internal capacity of 8 kFE like many other Mekanism machines.

### Screenshots

![Screenshot 2024-03-24 145917](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/37115839/c500be90-89b5-4c8a-8ac9-12109e096f21)

**Comment by Saereth** [comment]
This is intentional, you must use energy upgrades in it and it limits the effectivness of those ugprades
