### ISSUE TITLE
Direwolf 1.20 Generating certain specific areas of the map creates endless lag

### ISSUE THREAD

**Issue by dylithian** [FTBTeam/FTB-Modpack-Issues#5046]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1 11614

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14737597/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14737598/debug.log)

### Describe the bug

Generating chunks in specific areas creates endless lag. This was initially discovered by players simply exploring, but it even happens when nobody is on the server and the /forge generate command is used.

On this seed, marauders3, some of the chunks around -890 66 165 get generated (no idea which chunks are causing the problem) and then the server lags. Players see "waiting for server" until the server crashes due to the watchdog.

This also happens on the same seed in singleplayer.

This also happens on a different seed, marauders2, near -2333 63 3291.

### Steps to reproduce

1. Generate a world with seed marauders3
2. Teleport to -890 66 165
3. Move around.
4. Notice that the server starts to lag and never stops.

### Expected behaviour

The server should, you know, continue to work?

**Comment by dylithian** [comment]
Additional information:

Removing irons_spellbooks-1.20.1-2.2.1.jar from the mods list resolves the issues.

**Comment by Shybella** [comment]
https://github.com/iron431/irons-spells-n-spellbooks/issues/367

**Comment by hw4n** [comment]
tested ``marauders3`` without and with nomowanderer 1.6.3 and 1.6.4.

1.6.3 instantly produces waiting for server deadlock, without it or with 1.6.4 works no problem.

I had this problem on my server and did not know how to solve, so I had to hard reset my server. However the hang persisted, searched out that nomowanderer 1.6.3 is the problem.

I think FTB team should update the nomowanderer version to 1.6.4, not 1.6.3. in changelog it's mentioned like the following:
NoMoWanderer causing chunk load locking [#4569](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4569)
``nomowanderer-1.20.1_1.6.2`` to ``nomowanderer-1.20.1_1.6.3``
