### ISSUE TITLE
Savage Ender Dragon x Cupboard mod

### ISSUE THREAD

**Issue by ImmortalKindr3d** [FTBTeam/FTB-Modpack-Issues#5047]
### Modpack

FTB Presents F.A.M

### Modpack version

1.1.0

### Describe the bug

Ender dragon fight. Player shoots arrow to destroy egg. Lightning strikes and server crashes.
Creeperhost stated it is a known bug with Savage Ender dragon and cupboard mod.  https://github.com/someaddons/SavageEnderDragon/issues/48  
There is a fix, F.A.M. just needs to be updated.

### Steps to reproduce

Activate ender dragon fight, destroy egg.

### Expected behaviour

Server has unexpected error and crashes.

**Comment by whitjae** [comment]
same thing happening to me. would love an update quick so we're not stuck in the ender dragon fight and can actually play!

**Comment by ImmortalKindr3d** [comment]
> same thing happening to me. would love an update quick so we're not stuck in the ender dragon fight and can actually play!

We ended up just disabling the savage ender dragon mod and restarting the server. We were able to progress from there.

**Comment by whitjae** [comment]
> > same thing happening to me. would love an update quick so we're not stuck in the ender dragon fight and can actually play!
> 
> We ended up just disabling the savage ender dragon mod and restarting the server. We were able to progress from there.

Did you do that server side and app side? I can find the mod on my FTB app but not in my server files.

**Comment by ImmortalKindr3d** [comment]
> > > same thing happening to me. would love an update quick so we're not stuck in the ender dragon fight and can actually play!
> > 
> > 
> > We ended up just disabling the savage ender dragon mod and restarting the server. We were able to progress from there.
> 
> Did you do that server side and app side? I can find the mod on my FTB app but not in my server files.

Just did it server side. I'm hosting the server through creeperhost, and they made it easy to disable individual mods.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
