### ISSUE TITLE
cant launch ftb skies expert

### ISSUE THREAD

**Issue by symba666** [FTBTeam/FTB-Modpack-Issues#5051]
### Modpack

FTB Skies Expert

### Modpack version

1.4.0-1.5.0-1.6.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14748025/latest.log)

### Describe the bug

fails to download something every time i try to launch

### Steps to reproduce

try to launch the mod pack 

### Expected behaviour

it wont launch

**Comment by Saereth** [comment]
this was a server issue with cf, should be resolved now, reinstall if it hasnt already worked for you
