### ISSUE TITLE
Middle Click (Sort) in Curios Tab Deletes Items

### ISSUE THREAD

**Issue by Mad-Hatz** [FTBTeam/FTB-Modpack-Issues#5052]
### Modpack

FTB Skies Expert

### Modpack version

1.5.0

### Describe the bug

Sorting your curios (middle click my default) in the curios tab causes items to be deleted. Including but not limited to backpacks.

### Steps to reproduce

1. Goto curios tab.
2. Middle click or whatever you have "sort" configured to...
3. Try to find your curios.

### Expected behaviour

Sorting should be disabled or items should sort into available slots, but not deleted.

**Comment by Easelm** [comment]
Just happened to me.

**Comment by Saereth** [comment]
this would mean your inventory sorter config is wrong on your server/world save, grab inventorysorter-server.toml from default-configs and copy into your world or save folder under the server-configs folder and restart, should prevent it.

**Comment by Mad-Hatz** [comment]
So I checked this out, and [diffed](https://www.diffchecker.com/XibX4BsG/) the files. There was no difference between the default inventorysorter-server.toml and the world save inventorysorter-server.toml.

- I copied the default config into the world save anyways.
- restarted the server 
- _issue persisted_

This is the relevant curios section of the inventorysorter-server.toml file which falls under the containerBlacklist array:
`"l2tabs:curios", "curios:curios_container"` are these the correct names for these containers? I'm not sure how to determine if these are accurate at this time.

**Comment by bo-jensen** [comment]
Had the same happen to me on my single-player world. The mentioned .toml files are identical.

**Comment by agustincriado** [comment]
Hey there, same thing happened to me.

Aswell copied inventorysorter-server.toml from default-config into the world folder under serverconfig, but nothing happened.
Both files are identical as previously mentioned and the issue persist
