### ISSUE TITLE
Productive Bees centrifuge recipes broken despite recommendation

### ISSUE THREAD

**Issue by DannyDan4** [FTBTeam/FTB-Modpack-Issues#5053]
### Modpack

FTB Skies Expert

### Modpack version

1.6.0

### Describe the bug

It appears all of the recipes were removed from the Productive bees centrifuge, but the recipe of the centrifuge was changed, and a quest indicates it's a "good option for processing your combs".

### Steps to reproduce

1. check quest for productive bees
2. see the centrifuge is recommended to use
3. find out it doesn't work with any combs, whatsoever.

### Expected behaviour

The Centrifuge should be able to process most, if not every, comb.

**Comment by ArtpokeBr** [comment]
Fixed the Quest about the Centrigue, as now you should be using a Fabrication Matrix for Comb Processing.
