### ISSUE TITLE
Add pedestals "remove durability cost" modifier recipe

### ISSUE THREAD

**Issue by fwaaade** [FTBTeam/FTB-Modpack-Issues#5055]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

Pedestals mod breaker upgrades don't work with undamageable tools (https://github.com/Mowmaster/Pedestals/issues/259)

### Mod suggestion

Add a `pedestals:upgrademodification_global` recipe (https://github.com/Mowmaster/Pedestals/wiki/Infusions119) to not damage any tool. Suggested recipes: unbreaking 9 book + (1 'stable' unstable ingot OR 1 unstable block).

**Comment by Saereth** [comment]
this is something for mowmaster to fix, he's got an issue open for it so when he updates we'll update the pack, nice research into the underlying issue!
