### ISSUE TITLE
Bamboo Stick recipes conflict

### ISSUE THREAD

**Issue by calebh514** [FTBTeam/FTB-Modpack-Issues#5057]
### Modpack

FTB Skies Expert

### Modpack version

1.6.0

### Describe the bug

Bamboo have two "block" style crafts, and considering this is an endgame quest one would not think to look inside a vanilla crafting bench to swap between both and pick the one that works to craft the pina colada mug.

### Steps to reproduce

1. Go to make bamboo mug
2. turn bamboo into block in non vanilla crafting table
3. receive tropicraft block instead of quark block in anything that isn't a vanilla crafting table. 

### Expected behaviour

I would expect both types of bamboo block to work in the Tropicraft Bamboo Stick craft.

**Comment by ArtpokeBr** [comment]
You know may convert easily (using a Stonecutter) all the types of Bamboo Blocks.
