### ISSUE TITLE
FTB opens minecraft no issue, once i open the world game crashes

### ISSUE THREAD

**Issue by MILLWRIGHT2309** [FTBTeam/FTB-Modpack-Issues#5059]
### Modpack

~~FTB Presents F.A.M~~ Direwolf20 1.20

### Modpack version

1.12.1

### Log Files

[crash-2024-03-27_10.44.02-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14775126/crash-2024-03-27_10.44.02-server.txt)

### Describe the bug

modpack opens fine, once attempting to join world my game crashes. before this happened i did some ars nouveau progress, force loaded heat generator in nether, created a enderman farm in a hyperbox and set up pedestals material generators for (cobble,sand etc) obsidian from the heat generator.

### Steps to reproduce

open modpack, join my world, game crashes

### Expected behaviour

my world to open

**Comment by MILLWRIGHT2309** [comment]
Modpack is direwolf20 1.20

**Comment by Gaz492** [comment]
Could you try going to where you have the modpack installed then opening the saves > your world > serverconfig folder then deleting the jumbofurnace-server.toml config and let me know if the issue still happens to you?
