### ISSUE TITLE
Mekanism steel armor doesn't have forge armor tag

### ISSUE THREAD

**Issue by MrReps** [FTBTeam/FTB-Modpack-Issues#5060]
### Modpack

FTB Skies Expert

### Modpack version

1.6.0

### Describe the bug

hi !
Simple bug but annoying for mob farm :(
Mekanism steel armor doesn't have forge tag (chestplate, helmet ...)

Thanks

### Steps to reproduce

Read metadata

### Expected behaviour

Should have the correct tag

**Comment by MrReps** [comment]
Hello !

After a double check, I've saw that I set incrorrectly the pack ! It's not FAM but ftb skies expert... I do not know how i miss that ! my bad i'll close the ticket sorry for the time loose. 

Sincerely

**Comment by UnRealDinnerbone** [comment]
It's ok, I can convert it FTB Skies issue

**Comment by MrReps** [comment]
Hey, can you put as FTB skies Expert (not normal ftb skies) ?

Plus i'll had some more content, because i've checked on version 1.8.1 this problem. Mekanism armor are not craftable, but looks like they are still dropable by mob killing, and it looks like there is still no tag on them, but because they are not craftable this can be why.

thanks

**Comment by MrReps** [comment]
So it is a problem. Being dropped by mob in farm could lead to fill chest
(okay not quickly) even when a sorter take out to trash all armor tag.
