### ISSUE TITLE
Productive bees not producing comb

### ISSUE THREAD

**Issue by RedDamer** [FTBTeam/FTB-Modpack-Issues#5061]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

I am creating a new thread but, productive bees, specifically for me the Nickel and Aluminum bees, do NOT produce any comb. The Aluminum bee has the "required" (per JEI recipe on pollination) aluminum block, but nothing happens. The Nickel bee does not have it's required block, as the recipe for a nickel block from thermal is not available, and instead becomes a Railcraft Reborn nickel block, which the bee does not view as a valid pollinator option.

### Steps to reproduce

1. Place a Nickel and Aluminum bee inside an Advanced Beehive.
2. Place down blocks of aluminum and nickel around said beehive. 
3. Bees do not pollinate on blocks, therefore they do not produce any comb.

### Expected behaviour

Bees should create comb.

### Screenshots

![2024-03-27_22 25 00](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165237224/a22eed55-f4ab-445a-ba73-f5d9b01dd4cf)
![2024-03-27_22 25 17](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165237224/354d0dae-9aef-4a64-9dbc-8d01bce6551d)
![2024-03-27_22 25 18](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165237224/37893f27-5f6f-45e7-95ff-f3d7fe9e2cf5)
![2024-03-27_22 25 28](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165237224/dd9af723-ca3b-44b8-a0a3-1ee5e1f42388)

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you? I am tested this on my client, and it’s working as intended.
