### ISSUE TITLE
[Bug] Big lag which creates a crash log

### ISSUE THREAD

**Issue by sphinxnine9** [FTBTeam/FTB-Modpack-Issues#5062]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.22.0

### Log Files

[crash-2024-03-28_14.11.54-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14790225/crash-2024-03-28_14.11.54-client.txt)

### Describe the bug

Hi, idk why but when I play sometime when I play I have a very big lag (like I go from 80 fps to 0-1 fps) and my game didn't crash, but I receive a crash log. Also, I receive in game a message who says that I have problem of unknown origin

### Steps to reproduce

idk

### Expected behaviour

idk

**Comment by Gaz492** [comment]
Unfortunately the crash report is rather vague on what the issue could be, would you be able to upload the debug.log from when this issue happens so we can take a look?
