### ISSUE TITLE
Raccoon bypasses villager's coin progress

### ISSUE THREAD

**Issue by DArkHekRoMaNT** [FTBTeam/FTB-Modpack-Issues#5063]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

You can bypass villager coin progression via Raccoon from Alex's Mobs

### Steps to reproduce

1. Tame Raccoon
2. Steal any level villager item, i.e. coins
3. Profit

### Expected behaviour

Should you limit raccoons somehow?

**Comment by ArtpokeBr** [comment]
Raccoons shouldn't be able to Spawn Anymore.
