### ISSUE TITLE
Steel Plates Uncraftable via Create

### ISSUE THREAD

**Issue by mikeperez05522** [FTBTeam/FTB-Modpack-Issues#5066]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

The Create "Pressing" crafting method for steel plates has a broken recipe. The ingredient is ad_astra_platform:steel_ingots which does not appear to exist in the pack:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/60409335/59bc4f5a-c7a7-433a-8d06-86252fbab7e3)
It is uncraftable via Create currently.

### Steps to reproduce

1. Go into JEI and search "steel plate"
2. Left click the thermal "steel plate" to view the crafting recipes
3. Observe the broken recipe

### Expected behaviour

A steel ingot is able to be crafted into a steel plate via the Pressing crafting method.

### Additional information

I checked version 1.9.1 of the pack and the mekanism steel ingot was the ingredient back then, not sure what the desired one is now.

**Comment by DinnerBeef** [comment]
Unable to reproduce this, issue. Please reopen if you are still having issues with this. Try reinstalling the modpack to see if that fixes it.
