### ISSUE TITLE
Crashed while fighting End Dragon - had to restore a backup to get server running again and then lost a bunch of data/stuff

### ISSUE THREAD

**Issue by kchowchow** [FTBTeam/FTB-Modpack-Issues#5067]
### Modpack

FTB Presents F.A.M

### Modpack version

1.1.0

### Log Files

mc-instances/mc-65e2ba386c3a1/crash-reports/crash-2024-03-29_04.18.33-server.txt

### Describe the bug

We crashed while fighting the end dragon and our server would not start due to the crash so we loaded a backup file, but when the backup was loaded, anything stored in a storage system (portable storage, mekanism computer storage, etc.) was missing, our maps were wiped, and our claimed chunks were cleared. We tried loading different backups to retrieve the missing data/items/information, but nothing would load the missing information/entities. Now were missing a bunch of stuff stored in our storages and a lot of map progress made.

### Steps to reproduce

Not sure what you want me to tell you - your modpack crashed while fighting the End Dragon and then we had to restore a backup because it crashed our server and now we're missing shit.

### Expected behaviour

well for one, not for the server to crash when fighting the end dragon, but two for us NOT to lose our storages when we load a backup

### Additional information

I'm not sure what you can do to help - your modpack is super buggy and there is barely any support with the pack so its really just annoying.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?
