### ISSUE TITLE
Visual bug in FTB inf ev Skyblock

### ISSUE THREAD

**Issue by schwitaler** [FTBTeam/FTB-Modpack-Issues#5068]
### Modpack

FTB Infinity Evolved Skyblock

### Modpack version

2.0.1 

### Describe the bug

When I create a new world, the chest is invisible at first. As soon as I turn to the chest, the game zooms in by about 1000 per cent. The more I interact with the crate or the world, the more often the bug happens and also the menu disappears. Repeatedly deleting all files of the FTB or curse app and the modpack does not change anything, the bug keeps coming back after reinstalling :(

### Steps to reproduce

I dont know if the bug only appears on my Pc. But to reproduce the bug i only need to restart the game and join a new survival map 

### Expected behaviour

dont know what too write here 

### Screenshots

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165397454/6c4d0143-7606-479e-aeef-56f106dbd4dd

**Comment by 5ully** [comment]
This is an issue with intel graphics cards and older versions of Minecraft
