### ISSUE TITLE
Villager JEI trades are incorrect

### ISSUE THREAD

**Issue by bsylve1996** [FTBTeam/FTB-Modpack-Issues#5069]
### Modpack

FTB Skies Expert

### Modpack version

1.6.0

### Describe the bug

In JEI, it shows vanilla villager trades not the changes to villager trades. 

### Steps to reproduce

1. Go to JEI
2. search any item that the villager would have in vanilla

### Expected behaviour

Coin Trades show up in the JEI trades

**Comment by Saereth** [comment]
mod issue, its been reported like a month ago but no fix yet, we're watching for it
