### ISSUE TITLE
FTB One server wont start fully

### ISSUE THREAD

**Issue by sophienix** [FTBTeam/FTB-Modpack-Issues#5072]
### Modpack

FTB One

### Modpack version

2.8.3

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14808678/debug.log)

### Describe the bug

when i start up the server it stops processing but stays open in the console i have even waited over 5 minutes and nothing happened just showed a java error but did not crash

### Steps to reproduce

1.intall a fresh version 2.8.3 
2.start it

### Expected behaviour

suppose to finish starting but it did not

### Screenshots

![ftb one part 2](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/74495871/fa036ee3-e2fd-4fbe-ab43-b538673f396f)
![ftb one](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/74495871/9e02e687-e977-4b2a-8534-8fa8f1657a50)

### Additional information

i have never had any problems with starting any ftb servers on my server hosting device

**Comment by Lycerd** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/96354240/b78a5862-1769-4fed-ae02-d48cb25ef07f)
