### ISSUE TITLE
FTB Skies Expert Nether Bug

### ISSUE THREAD

**Issue by plausible912** [FTBTeam/FTB-Modpack-Issues#5073]
### Modpack

FTB Skies Expert

### Modpack version

1.6.0

### Describe the bug

I'm experiencing the same bug referenced here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3586.

When I travel to the Nether, I am unable to return to my island.

### Steps to reproduce

1 Build nether portal
2 walk through
3 return back

### Expected behaviour

the nether portal should link to the nether portal I build in my dimension

**Comment by kmadstarh** [comment]
Are you unable to return from the nether whatsoever, or are you leaving the nether and coming back somewhere not in your dimension, or not at your island in your dimension?

**Comment by plausible912** [comment]
Hi,

Thanks for the quick response!

Hopefully the screenshots below help show the progression of entering and attempting to return. I end up in the desert and things appear bugged at that point (e.g. I can't place cobblestone, items drops through blocks). If I return back to the Nether and try again, I always return back to the desert location.

Before Entering:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165497814/bf498a89-69dc-4339-b7f5-8ddcef7bce2d)

After Entering:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165497814/9cf6c9cd-433d-4a33-907f-d18a4919195f)

Returning to Island:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165497814/51cf7294-8e3a-4eea-ad03-726d1b72941b)

**Comment by kmadstarh** [comment]
It looks like you're being returned to an equivalent point in the overworld dimension, rather than being returned to your own personal dimension... Until this is fixed you'll probably have to stick with the "/ftbdim home" command to return to your island from the nether.

**Comment by Saereth** [comment]
the new version of teamdims coming should help to address this
