### ISSUE TITLE
BioDiesal Recipe

### ISSUE THREAD

**Issue by Squishychew** [FTBTeam/FTB-Modpack-Issues#5074]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

I noticed in update log that Bio-Diesal recipe output was increased in the Advanced Mixer.
I am assuming this was to make it more attractive an option compared to the PNC process
While checking the new ratios I did notice that the PNC fluid mixer ratios have also been changed
25mb Vegetable Oil + 25mb Ethanol = 100mb Bio Diesal and 1 Glyceran
I am not sure if this is intended and could not see anything mentioned here already

### Steps to reproduce

Check BioDiesal Fluid Recipe in JEI

### Expected behaviour

I expected the PNC recipe to be unchanged

**Comment by Saereth** [comment]
This is intended it was just forgotten on the patch notes
