### ISSUE TITLE
Windmills not producing Stress correctly

### ISSUE THREAD

**Issue by bsylve1996** [FTBTeam/FTB-Modpack-Issues#5076]
### Modpack

FTB Skies Expert

### Modpack version

1.6.0

### Describe the bug

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/35739125/f07c9ce8-cfc2-44c7-8d73-c7b41920e675)
Either update the tooltip to say max of 4 SU or add it to the produces low amounts of stress that the 64 su is incorrect.

### Steps to reproduce

Go to JEI 
hover over Windmill Bearing in JEI

### Expected behaviour

Either Windmill produces up to 64 SU or tooltip says it caps at 4SU

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/35739125/609c7234-deda-4b36-ba72-0ddf29b63d2b)

**Comment by Saereth** [comment]
this is server/config file desync, copy defaultconfigs/create* files to your worldsave/serverconfigs to update the stats
