### ISSUE TITLE
Implosion Compressor slot filter

### ISSUE THREAD

**Issue by GalaxyOfZero** [FTBTeam/FTB-Modpack-Issues#5077]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

Added to the implosion compressor components imput slot the "filter" value to black list other items from going in to this slot,

https://frinn.gitbook.io/custom-machinery-1.19/creating-custom-machines/machine-components/item-component

**Comment by Saereth** [comment]
prefer to leave the logistics on this to the player
