### ISSUE TITLE
Ender dragon crystals crashes server

### ISSUE THREAD

**Issue by Kyo0x** [FTBTeam/FTB-Modpack-Issues#5079]
### Modpack

FTB Presents F.A.M

### Modpack version

1.1.0

### Log Files

https://pastebin.com/p6365yv6

### Describe the bug

When you shoot the crystal with an arrow the server crashes

### Steps to reproduce

1. Go to end
2. Shoot the end crystal
3. Server crash

### Expected behaviour

Go to end, shoot crystal, kill ender dragon

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version?
If you are, would you be able to upload new log files for us so we can take a further look?

**Comment by Kyo0x** [comment]
Hi,
Sorry but I've not played it in a while now, but if you believe it has been
fixed, i'll trust that!
