### ISSUE TITLE
[Bug]: Mod §6xnet§r§7 missing with release 1.4.0

### ISSUE THREAD

**Issue by Rduppe** [FTBTeam/FTB-Modpack-Issues#508]
### Modpack

FTB University

### Modpack version

1.4.0

### Describe the bug

Release update 1.4.0 done succesfully and when i start the server i get the error that the mod §6xnet§r§7 is missing.
Please fix for Linux version release, i don't know if other versions are impacted.

[crash-2021-12-27_10.56.45-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7779950/crash-2021-12-27_10.56.45-fml.txt)

### Steps to reproduce

select folder on server
run ./start.sh after install 1.4.0 release
get error Mod §6xnet§r§7 missing
server won't start after install 1.4.0 release

### Expected behaviour

Minecraft server should start without problems

**Comment by Raidobw2** [comment]
I got that forwarded to our team asap, thank you. For now you can get the mod from https://www.curseforge.com/minecraft/mc-mods/xnet/files/3557001 and place it inside the mods folder, this will resolve the crash and allow you to play like normally on the server.

**Comment by Raidobw2** [comment]
The installer on my side works fine for either Windows or Linux. Are you sure it's not a download error? This would be specified at the end of the download, inside your terminal saying that some files failed or all succeeded.
Please try a reinstall and close this issue if this was a download problem, thanks!

**Comment by Rduppe** [comment]
> The installer on my side works fine for either Windows or Linux. Are you sure it's not a download error? This would be specified at the end of the download, inside your terminal saying that some files failed or all succeeded. Please try a reinstall and close this issue if this was a download problem, thanks!

Thanks for the quick reply and information, will try this as fast as possible and let you guys know the result.

**Comment by Rduppe** [comment]
I just did the reinstall of 1.4.0 release and indeed there was a failed download. for some reason the Xnet mod wouldn't download.
This issue is resolved thanks to the link you gave me earlier.
