### ISSUE TITLE
Missing recipes for waterlogged dirt for other mesh types

### ISSUE THREAD

**Issue by iTitus** [FTBTeam/FTB-Modpack-Issues#5081]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

The sifter has a recipe for waterlogged dirt -> corals, but it only exists for the string mesh and not other meshes.
This contradicts the text for the _Mesh Progression_ quest which states that there is no reason to keep old ones around.

### Steps to reproduce

Look at the usages of dirt for the Create sifter.

### Expected behaviour

I expect this recipe to work with all mesh tiers.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/5154317/f48660b6-5c73-4c41-9b0a-e269fba32523)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/5154317/7db67a86-5823-46c7-8c3f-65641dad0e40)

**Comment by Saereth** [comment]
this is done to save on recipe lookup performance, I'll edit the quest text to mention the string waterlogged

**Comment by iTitus** [comment]
SO it is intended to keep the string mesh around for that one recipe?
