### ISSUE TITLE
Bee Genetics not Accessible

### ISSUE THREAD

**Issue by BPLP123** [FTBTeam/FTB-Modpack-Issues#5082]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

You cannot process the 'Squished Bee Material' in any machine, particularly the Fabrication Matrix where you process combs.

### Steps to reproduce

1. Go to a Fabrication Matrix
2. Try to insert Squished Bee Material
3. Look at Squished Bee Material recipes and uses
4. Find none

### Expected behaviour

Some method of centrifuging Squished Bee Material into gene samples

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/89955214/900d329b-c259-49b9-b053-6a596b349209)

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/89955214/2eb4d63c-5b91-41bc-811f-29cd9ef72d3b)

**Comment by Timmy3921** [comment]
Squashed bee material is processed in the powered centrifuge, that's the machine's only purpose now.

**Comment by mstew20** [comment]
I'm having the same issue. The powered centrifuge doesn't exist in 1.7.0. Even tried the pokey upgrades and those aren't producing anything either.

**Comment by Ardrial** [comment]
Confirming 1.7.0 removed the ability to craft powered centrifuge.
