### ISSUE TITLE
Shady Wizard not offering Bastion fruits from Ars Nouveau

### ISSUE THREAD

**Issue by SillyBits** [FTBTeam/FTB-Modpack-Issues#5085]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

The Shady wizard is missing a trade for bastion fruits, as with the other fruits from Ars Nouveau
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/2514661/f14463f9-d112-446f-9195-0a783f0cffa0)

### Steps to reproduce

1. Open "shady_wizard.json" from the kubejs folder
2. Inspect trades
3. No ars_nouveau:bastion_pod trade found

### Expected behaviour

To offer bastion fruits as well

**Comment by Saereth** [comment]
yep it was moved to loot and allowed to be reproduced in phytogens and cloches now
