### ISSUE TITLE
Refined Storage   No longer works properly. Help.

### ISSUE THREAD

**Issue by desrapter** [FTBTeam/FTB-Modpack-Issues#5088]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Log Files

nop

### Describe the bug

Today I switched from Applied Logistics, i.e. from the ME system, to the Refined Storage System. I have moved my items over. Now I can't get anything out. By mouse click or by shift. I can still craft manually without any problems. But I can't access my items. Does anyone have any idea what's going on? I have also set up a security panel. Doesn't help either. 

### Steps to reproduce

Unfortunately, I don't know how this situation came about. I'm sorry. 

### Expected behaviour

 Well, I can take my stuff out of the storage system like in the ME. Doesn't work now somehow. It's probably a bug or something.

**Comment by Gaz492** [comment]
Would you be able to upload a copy of your world so we can look into this?
