### ISSUE TITLE
PNC Jackhammer and IE Mining Drill missing tags or attributes to identify them as able to mine pickaxe materials

### ISSUE THREAD

**Issue by pjfranke** [FTBTeam/FTB-Modpack-Issues#5089]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

Both the PNC Jackhammer and the IE Mining Drill don't appear to be identified as "pickaxes", or have item tags that would allow them to mine pickaxe required materials.  Perhaps the missing item tags are a symptom, not the cause.

This seems to be an interaction issue with the mod Natural Progression where the tools aren't seen as a valid Pickaxe, as in a test world only after that mod was added does the problem occur.  Tested with just these mods loaded:

Jade-1.19.1-forge-8.9.2.jar
jei-1.19.2-forge-11.6.0.1019.jar
NaturalProgression-1.19.2-2.3.6.jar
pneumaticcraft-repressurized-1.19.2-4.3.15-20240123.082827-1.jar
--fml.forgeVersion 43.3.8 
--fml.mcVersion 1.19.2

### Steps to reproduce

Try to mine anything stone or higher hardness with them, the blocks are shown as Unbreakable and are unable to be mined/broken.

### Expected behaviour

Jackhammer and Mining Drill would be able to mine stone, cobble, or crushed category blocks, as well as any harder material up to the mining level of their bit (Iron, Diamond, or Netherite Drill Bit, or Iron or Steel Drill Head).

### Screenshots

Tags for Pneumatic Jackhammer as seen with Create filter (none):
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8549006/e4cef0aa-7a55-4a2b-8f40-cedf7a775f6e)
Tags from LaserIO (also none):
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8549006/82864966-1e89-409a-9edc-db9aeb0ccd90)
Tags for Immersive Engineering seen by Create:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8549006/afd4076a-1146-4408-821f-22f1fdfe4b79)
Tags from LaserIO:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8549006/6b2746d7-c6f0-4555-8c72-a075d47b7545)

In contrast, the tags for the Thermal Innovation Fluxbore seen by Create:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8549006/7eaa6849-516e-49ee-b5ff-d90b5cffbb1f)
Tags from LaserIO:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8549006/e4d2b263-2b25-4e0e-abcb-185f6d68d527)

Finally, a vanilla Netherite pickaxe:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8549006/d19a8f9b-86a6-4095-b256-170fc260e7b3)
Tags from LaserIO:
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8549006/9af077ed-421a-45d0-987b-06a7e6d4738f)

**Comment by pjfranke** [comment]
In-game error seen.  The middle message is disabled in the pack default config, this is from the test pack.  The Jade prompt is identical though.

![2024-04-02_21 30 02](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/8549006/1a56adc4-7ac5-4615-a67b-0a795cc0654b)

**Comment by ArtpokeBr** [comment]
Yup, it was just a matter of adding the correct tags to the drills =)

**Comment by pjfranke** [comment]
That's great to hear!  Mind mentioning what tags it needed?  I could post an issue over on https://github.com/TeamPneumatic/pnc-repressurized letting them know it should be updated in code to fix it by default, rather than all pack authors needing to rely on adding them with KubeJS.

**Comment by ArtpokeBr** [comment]
the tags were `natprog:considered_as_axe` and `natprog:considered_as_pickaxe` =)
