### ISSUE TITLE
[Bug]: Awakened Draconium seed does not work with Hydroponic Bed from IF

### ISSUE THREAD

**Issue by LuciusV** [FTBTeam/FTB-Modpack-Issues#509]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Describe the bug

Awakened Draconium seed does not work when planted on Hydroponic Bed. Common Draconium works normally.

### Steps to reproduce

1. Supply Hydroponic Bed with Water, Ether Gas and energy
2. Nothing happens

### Expected behaviour

Expected it to grow like other plants

**Comment by quietust** [comment]
All Tier 6 seeds require a matching **Crux** beneath the farmland in order for them to grow, and Hydroponic Beds behave as farmland.

Note that this does not apply to Botany Pots or Power Pots, and it probably doesn't apply to Garden Cloches either.

**Comment by LuciusV** [comment]
> All Tier 6 seeds require a matching **Crux** beneath the farmland in order for them to grow, and Hydroponic Beds behave as farmland.
> 
> Note that this does not apply to Botany Pots or Power Pots, and it probably doesn't apply to Garden Cloches either.

Thank you, it works with crux under hydroponic bed
