### ISSUE TITLE
More morph-o-tool compat

### ISSUE THREAD

**Issue by rlnt** [FTBTeam/FTB-Modpack-Issues#5091]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

I'd like to see more tools being able to be added to the Morph-o-Tool. Right now, the tools from Pedestals and Ars cannot be added. There are probably more but that's the current stage of the pack I am playing.

**Comment by ArtpokeBr** [comment]
while definetly possible, with some tests, apparently due to the nature of how morph-o-tool works, you would be able to add only 1 tool from the pedestals mod.

**Comment by rlnt** [comment]
Hmm, I see. I didn't test multiple tools from the same namespace. Inserting the linking tool into it would already be pretty helpful though. The issue submission was meant to point in a general direction. Since I am still in the early game of the modpack and don't want to spoil myself, I am not able to test all relevant tools and whether they can be inserted into the morph tool. There might be more tools that are not compatible yet.

**Comment by Saereth** [comment]
if people want to make a list of tools here to add compat I'll add them
