### ISSUE TITLE
Pearl Gate that spawns Apothic Bosses leaves boss's health bar on screen

### ISSUE THREAD

**Issue by Hennic** [FTBTeam/FTB-Modpack-Issues#5092]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

I was farming Apothic bosses for some of the enchanted gear that can't be crafted. Using the Pearl Gates that summons Apothic bosses, I got a blaze boss which also display a boss health bar on the top of the screen, this boss has an insane knockback attack and a larger health pool compared to the usual bosses I would get from the Pearl Gate, after the timer of the portal runs out or the bosses walked off and fell into the void, the health bar would still remain on the middle top of the screen and doesn't go away, I don't know what to do about it, even going into a different dimension doesn't make it disappear.

### Steps to reproduce

1. Use the Gate Pearl that spawns Apothic bosses (Small Apothic Boss Gate Pearl)
2. Kill the bosses and use the Gate Pearl again until you get a boss which has a health bar.

### Expected behaviour

The Apothic Boss (which has health bars) would walk off the edge, kills you or the timer of the gate would run out before you kill it or in some casses disappears immediately upon spawning and leaving a health bar in the middle of the screen.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165844440/fabd3c47-cedf-4e38-ba7a-999a3699c724)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165844440/a9179739-2d3d-4e82-8a0e-38cd9d063f6a)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165844440/d783d74c-373d-420e-890c-08dedfcfbe10)

**Comment by Saereth** [comment]
These particular bosses should no longer spawn from apoth gates
