### ISSUE TITLE
Server freezes then game crashes after end towers explode while fighting ender dragon

### ISSUE THREAD

**Issue by Hezakaiah** [FTBTeam/FTB-Modpack-Issues#5094]
### Modpack

FTB Presents F.A.M

### Modpack version

1.1.0

### Describe the bug

Playing on a LAN server, got to the ender dragon and when you try to explode the end crystal/tower (whatever it is) so the dragon doesnt heal, the game freezes and then crashes as soon as you hear thunder. Loaded up the game over a dozen times trying to fight the dragon. Finally gave up on it when i realized it was not worth doing. Quit the game since.

### Steps to reproduce

Go to the end.
shoot a crystal on top of the tower
watch your game crash

### Expected behaviour

I expected to just beat the dragon like normal with no crashes?

**Comment by Gaz492** [comment]
Would you be able to upload the crash report for us so we can take a look at it for you?
https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by Hezakaiah** [comment]
Close it mate. Stopped playing the game after I had to do console commands
to get the achievement for the ender dragon. Killed the fun instantly. Have
a good one brother.
