### ISSUE TITLE
ID Variable Card craft does not trigger advancement

### ISSUE THREAD

**Issue by rlnt** [FTBTeam/FTB-Modpack-Issues#5095]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

Since ID Variable Cards use a sequenced assembly recipe, you are not able to complete the advancement for it. This means you can't progress through the ID book to unlock new chapters and rewards.

### Steps to reproduce

1. Craft a Variable Card
2. See that you don't complete the advancement

### Expected behaviour

The advancement should be completable

### Screenshots

![](https://i.imgur.com/AlRnGXt.png)

### Additional information

You could add a quest line for ID and when crafting variable cards, you could have a command as quest reward which grants you the advancement.

I completed the advancement via:
```
/advancement grant SoRelentless only integrateddynamics:network_foundations/variables
```

**Comment by ArtpokeBr** [comment]
Alright, upon obtaining a Variable Card you should get the advancement now.

**Comment by isochronous** [comment]
To work around this for now you can "clear" a programmed variable card in the crafting grid to get the achievement
