### ISSUE TITLE
Just Enough Immersive Multiblocks removed?

### ISSUE THREAD

**Issue by krisavi** [FTBTeam/FTB-Modpack-Issues#5096]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

I remember seeing Immersive multiblocks in JEI, but in 1.7.0 it seems to be removed. Did not see anything related to it in changelog.

### Steps to reproduce

Open inventory and check usages for IE hammer in JEI

### Expected behaviour

To see multiblocks ingredient list and which block to hit to form them.

### Additional information

Remember seeing it in 1.6.0 or maybe in 1.5.x

**Comment by ArtpokeBr** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/44851727/c660cdb4-ac3a-4c0b-903a-6b2df688adaa)
Idk what you mean, I'am seeing the JEI Tab here O.o

**Comment by krisavi** [comment]
in 1.7.0 it doesn't seem to work for me any more. Will try reinstalling latest update on server, maybe something got messed up with update process. 
I have tried 2 different machines as client and no "multiblock with hammer" tab.

**Comment by Saereth** [comment]
working fine here as well
