### ISSUE TITLE
Crashing on server join

### ISSUE THREAD

**Issue by Jacobothy** [FTBTeam/FTB-Modpack-Issues#5097]
### Modpack

Other...

### Modpack version

Direwolf20 1.19 Version 1.12

### Log Files

[crash-2024-04-03_14.59.40-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14858565/crash-2024-04-03_14.59.40-client.txt)

### Describe the bug

When I join the server my game loads for a little bit, then says saving world and crashes. Friend can join server without issue. Java is up to date.

### Steps to reproduce

1. launch game
2. join server
3. crash on loading screen

### Expected behaviour

join server

**Comment by Gaz492** [comment]
Are you and your friend at the same location in the world?
The crash report is pointing towards an issue with the mod domum ornamentum and playing sounds.

Is this also an issue on the latest version of the modpack (1.13.0)
