### ISSUE TITLE
Tetra Material; Quartz

### ISSUE THREAD

**Issue by jacobeman5872** [FTBTeam/FTB-Modpack-Issues#5099]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

You're able to make AE2 quartz tools, but you're unable to improve them with the Tetra mod.

### Mod suggestion

https://github.com/jacobeman5872/Tetra-Material
I have written a KubeJS script that adds quartz as a material.
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48856913/05ad9e1d-85c8-4abf-972a-129ca19a2e36)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48856913/93fed725-7c50-4eb5-95a6-73803ff471ca)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48856913/05ec193b-778f-40dd-9197-a8daebc6ffa6)

**Comment by Saereth** [comment]
nice addition, we'll get it in
