### ISSUE TITLE
There is a trapdoor missing on the crane on the FTB Sky Island

### ISSUE THREAD

**Issue by Jamiscus** [FTBTeam/FTB-Modpack-Issues#5100]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

There is supposed to be a trapdoor here
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/107725325/b9a84685-abb4-4df3-9f2d-ad8492f40c1c)

### Steps to reproduce

1. Create World
2. Select FTB Sky Island
3. Look at the crane and see the missing trapdoor

### Expected behaviour

There is supposed to be a trapdoor where the red markings are on on the screenshot

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/107725325/5c06d42c-156e-423c-b22b-7818c888550f)

**Comment by Saereth** [comment]
this is not worth regenerating all the region files and redoing the nbt structure for a single trap door :P
