### ISSUE TITLE
Source Jar quest can't be completed

### ISSUE THREAD

**Issue by rlnt** [FTBTeam/FTB-Modpack-Issues#5101]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

The Source Jar quest within the Ars Nouveau quest chapter can't be completed. It's grayed out even if you complete the dependency quest to obtain an Archwood sapling.

### Steps to reproduce

1. Complete the quest for the Archwood sapling
2. See that the Source Jar quest is still grayed out

### Expected behaviour

Quest should be completable

### Screenshots

![](https://i.imgur.com/ZK8ryGt.png)
![](https://i.imgur.com/qvIFp3N.png)

### Additional information

The Source Jar quest correctly shows the Archwood sapling quest as a dependency but the Archwood quest does not show the Source Jar quest as a dependant.
![](https://i.imgur.com/GQVGdZj.png)

**Comment by krisavi** [comment]
Duplicate of
#4983 and #4789

**Comment by rlnt** [comment]
Interesting, I searched for duplicates but not in the resolved status. Thanks for pointing this out.
