### ISSUE TITLE
Unable to complete Space Plating Block

### ISSUE THREAD

**Issue by acmpedro** [FTBTeam/FTB-Modpack-Issues#5103]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

I've put the needed materials in the machines to sequence produce the Space Plating Block. It went through the first cycle, changing from Steel Plate Block to Incomplete Space Plating Block, with step 2/12,  but when it cycles back to do the next step, it just goes straight through the system, it doesn't stop to Deployer/Spout/Press. 

### Steps to reproduce

Steel Plate Block on a create sequence:
Deployer with Space Plating
Spout with polyethylene
Mechanical Press

Goes through to become Incomplete Space Plating Block, and the process need to repeat 3 more times, but the new part goes straight through the deployer, without stopping.

### Expected behaviour

It should do the step 3 more times and then become Space Plating Block

**Comment by krisavi** [comment]
Make sure the press has rotational power.

Spout doesn't need it and doesn't pass through rotational power, so if you have them in a row, then it can be a reason for that.

**Comment by Tyler99999999922** [comment]
if it says steps 2/16 then your press isn't working

**Comment by Saereth** [comment]
can't reproduce this
