### ISSUE TITLE
Breeding two chickens will complete the quest 'Bee Friends'

### ISSUE THREAD

**Issue by Vellox** [FTBTeam/FTB-Modpack-Issues#5104]
### Modpack

FTB Skies Expert

### Modpack version

1.6

### Describe the bug

Breeding two chickens (possibly any two animals) will complete the quest 'Bee Friends'. I haven't upgraded my server to 1.7 yet but I am not seeing this as fixed. This is possibly down to it being tied to the advancement 'The parrots and the Bats. I'm not sure if it is linked to that advancement intentionally and so this is by design but presuming not.

### Steps to reproduce

Breed two chickens with grass seeds. Guessing colour does not matter but they were black and brown.

### Expected behaviour

A baby chicken! Which happens anyway.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/38526460/bd7879da-01b8-4dd3-b13c-a169b5e5e744)

**Comment by Saereth** [comment]
yeah this is advancement bound there really is no way to know what you bread, the basic quest idea is just making sure people understand how to breed animals that poppy's are used for bees so in that it achieves what its meant to do
