### ISSUE TITLE
[Bug]: Tropicraft crashes during save

### ISSUE THREAD

**Issue by GitMrMeeseeks** [FTBTeam/FTB-Modpack-Issues#5105]
### Mod

Tropicraft

### Mod version

Tropicraft (tropicraft), Version: 9.5.1

### Forge / Fabric version

Forge: net.minecraftforge:43.3.8

### Modpack & version

FTB Skies Expert 1.7.0

### What issue are you having?

We had Tropicraft trees and when the server was saving it would crash until we removed the trees.

### Crashlogs

https://paste.feed-the-beast.com/view/6fba6996

### Steps to reproduce

We had Tropicraft trees and when the server was saving it would crash until we removed the trees.

**Comment by Gaz492** [comment]
Unfortunately, it looks like the paste link is no longer valid, would you be able to upload the log again for us?
