### ISSUE TITLE
Game Instance Crashing

### ISSUE THREAD

**Issue by Dedoctah** [FTBTeam/FTB-Modpack-Issues#5106]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Log Files

[crash-2024-04-06_19.22.31-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14894611/crash-2024-04-06_19.22.31-server.txt)

### Describe the bug

The game instance crashes upon interacting with object inventories. Unknown what exactly as it has happened while interacting with 3 different objects. if it helps this has only started happening since I planted the Lime fruit tree after purchasing it from the Marketplace and the error log does mention 'fruitleaves'

### Steps to reproduce

Click and interact with object inventories

### Expected behaviour

N/A error log details something that does not involve the object I'm interacting with

### Screenshots

N/A

### Additional information

N/A

**Comment by Dedoctah** [comment]
It appears the crashes are being caused by a rendering issue with the tropicraft trees, Lime sapling in this instance. The sapling growing was causing the crashes, I've not had a single crash since I removed the sapling.

**Comment by Saereth** [comment]
yep you're right, grapefruit can cause this as well. We've removed them from the market until tropicraft can fix
