### ISSUE TITLE
Mekanism Radiation Not Working

### ISSUE THREAD

**Issue by Tyler99999999922** [FTBTeam/FTB-Modpack-Issues#5107]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

RTG generators arent creating radiation on servers, tried in orbit at first but doesnt work in the overworld either. Also was unable to create radiation by breaking pressurized pipe with spent waste while in orbit.

### Steps to reproduce

Create RTG Generator
Use Yellow Cake Uranium in any dimension

### Expected behaviour

Creates radiation from mekanism

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/166253779/8f82da49-5555-4591-bb28-f547410082f0)

### Additional information

originally wanted radiation for the microfusion extrapolator but realized it wasnt functioning correctly in any dimension.

**Comment by Saereth** [comment]
this is definitely working for me 
<img width="1515" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/ba85cfdd-4b57-46bd-8a5c-1ce90c3099f2">
check that your server host doesnt have radiation disabled for some reason.
