### ISSUE TITLE
Official ImmediatelyFast

### ISSUE THREAD

**Issue by YozoraGD** [FTBTeam/FTB-Modpack-Issues#5108]
### Modpack

FTB University 1.19

### Is your suggestion related to a problem? Please describe.

This is a mod replacing suggestion since ImmediatelyFast avaliable for Forge.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/immediatelyfast

**Comment by UnRealDinnerbone** [comment]
With this being a performance, we would want to make sure we test before adding it to the pack. However, since this is not the case I don't fell comfortable adding it to the pack
