### ISSUE TITLE
Jade

### ISSUE THREAD

**Issue by YozoraGD** [FTBTeam/FTB-Modpack-Issues#5113]
### Modpack

FTB University 1.19

### Is your suggestion related to a problem? Please describe.

This is just an idea to add Jade and Jade Addons to modpack and have it disabled by default to give players more choice for what to use...

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/jade
https://www.curseforge.com/minecraft/mc-mods/jade-addons

**Comment by UnRealDinnerbone** [comment]
With The One Probe already in the pack. And disabled mods not really supported this is not possible
