### ISSUE TITLE
Crash when mining turtle mines stellarite

### ISSUE THREAD

**Issue by Jacoby6000** [FTBTeam/FTB-Modpack-Issues#5115]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Log Files

[crash-2024-04-08_19.00.28-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14910685/crash-2024-04-08_19.00.28-server.txt)

### Describe the bug

Whenever a mining turtle mines a `stella_arcanum` block, the server crashes

### Steps to reproduce

1. Place a stella arcanum block with creative mode
2. place a mining turtle in front of it
3. Dig up the block with the turtle

### Expected behaviour

The block explodes like normal, destroying the turtle and the surrounding area

**Comment by Gaz492** [comment]
I've not been able to replicate this issue, does it happen every time when you tell the turtle to dig the stella arcanum block?
If it does, would you be able to try disabling the no mo wanderer mod, I want to rule out a potential issue caused by a known issue with that mod in the pack right now.

**Comment by Jacoby6000** [comment]
This issue came up after having already resolved the No Mo Wanderer stuff. Also I worked around the issue by just telling my turtles to avoid those blocks. Its specifically the ones that explode when mined that were triggering a crash


________________________________

**Comment by Jacoby6000** [comment]
@Gaz492 what was the fix for this? Just to make sure I'm being clear: this was not related to NoMoWanderers

**Comment by DinnerBeef** [comment]
O sorry about that. I missed read the issue and that thought the issue was about No More Wander. Can you please let me know if this still happening in the latest version of the pack?
