### ISSUE TITLE
Alternate methods of obtaining certain resources

### ISSUE THREAD

**Issue by Timmy3921** [FTBTeam/FTB-Modpack-Issues#5116]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

There are so many resources that are costly at first but later on have cheaper alternatives. However, some resources don't have this luxury, making it really tedious to get them.
Here's some resources that I have problems with obtaining and some suggestion on late game alternatives to make them easier.

Manasteel - currently requires making magically inclined steel; they can be dropped by guardian of gaia, but since the guardian can't be farmed, why not add manasteel (as well as mana diamonds and mana pearls) as an option for guardian of gaia predictions. Since the fight is gated behind mars, you don't need these resources as much at this point, and since fighting the guardian can already get you a lot of these resources, it wouldn't be overpowered or anything

Osmium - I do not like how the only method of obtaining osmium is through putting platinum in a centrifugal separator. It is far too slow with three auxiliary sieve upgrades (which btw, don't even increase the chances that much), even with a melodic upgrade. So please, give us a way to obtain osmium bees. It could be an osmium-infused ostrum plate given to idk an ostrum bee, since at that point of the pack you need a lot of osmium. The osmium comb recipes still exist in jei and it feels like a waste to not be able to use them.

Space ores - I'll be honest, I hate the arc furnace. Processing space ores with the arc furnace is so slow and power hungry. Even if you can get enough power for it, smelting 12 at once for 30 seconds is still way too slow, especially because you can't speed up the furnace via time torches or temporal pouches (and no, I am not willing to build multiple arc furnaces, I don't have that much space). Now, if you want smelting these ores to be costly, here me out: what if you introduced some kind of "space slag" or whatever, making it a slightly expensive item with similar progression to tnt, where when put in an induction smelter with a large amount of a specific space ore dust (amount of ore per "space slag" decreases with each tier), it can smelt them into ingots. Just think of the process like making space ingots into plates but replace the tnt with some other item that requires several steps to make and the implosion compressor with just the standard thermal induction smelter (but please don't make it require a ton of power and therefore negate the entire premise of faster space ore production)

Diesel generators - Just have the quantum assembler give double, you need a ton of them and I don't think I really need to explain myself.

Whether or not you actually want to implement any of these is up to you; I just want to vent my frustrations about some tedious aspects of this pack, providing my suggestions with balance in mind. Oh, and sorry for writing so much.

**Comment by Saereth** [comment]
This feedback is good and we will definitely keep these points in mind for future packs but at this point we probably wont implement them in the current iteration of skies expert. Ty for the well thoughtout post though, it really helps us in planning future packs and progression paths
