### ISSUE TITLE
Integrated Scripting

### ISSUE THREAD

**Issue by YozoraGD** [FTBTeam/FTB-Modpack-Issues#5117]
### Modpack

FTB University 1.19

### Is your suggestion related to a problem? Please describe.

Another addon for Integrated Dynamics, why not?

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/integrated-scripting

**Comment by UnRealDinnerbone** [comment]
With this mod having a such a low download count, I would want to make sure the most tested before being added
