### ISSUE TITLE
Create: Power Loader

### ISSUE THREAD

**Issue by YozoraGD** [FTBTeam/FTB-Modpack-Issues#5118]
### Modpack

FTB University 1.19

### Is your suggestion related to a problem? Please describe.

A way to load the chunks in-world, although we have Create chunkloading, but it only chunkload while being a part of contraption. We can add mods anyway because they function differently (in contraption, Create Chunkloading will load every chunk the contraption is in, while Create: Power Loader only chunkload with fixed range).
Currently FTB Chunks is currently limited to 25 forceloaded chunks only, and the only way of conditioning forceload is to manually set an expire time. After forceload the chunks I must remember where I forceloaded the chunk to turn off (by gui).
Mekanism anchor upgrade and Flux Network are 2 options, but place something just for chunkload is typically odd and unmanageable.
AE2 spatial anchor is a good one, but for some cases where cables don't reach the chunk and therefore not chunkloaded (or some location which didn't involve the use of AE2).

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/create-power-loader

**Comment by Grocel** [comment]
The FTB Chunks limit can be changed in configs. Even in-game if you are admin/singleplayer.

**Comment by UnRealDinnerbone** [comment]
With this being a chunk loading mod, I would want to make sure it tested and working. So this will not be added this time
