### ISSUE TITLE
texture pack

### ISSUE THREAD

**Issue by DevilShark20** [FTBTeam/FTB-Modpack-Issues#5125]
### Modpack

FTB Presents Direwolf20 1.19

### Modpack version

1.13.0

### Log Files

[startup.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/14950748/startup.log)

### Describe the bug

When creating texture packs, large letters are prohibited DWL, replaced with dwl

### Steps to reproduce

1. Logged into the game

### Expected behaviour

Fix

### Screenshots

![fix 2](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/146369306/1b65b6b8-ff67-4e1b-8f5d-424f0d784f22)
I have corrected:
![fix](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/146369306/c578d7f1-d272-45eb-a6f8-4e18ebd70b7f)

**Comment by Gaz492** [comment]
This issue should be fixed in the latest version of the pack
