### ISSUE TITLE
Pedestal smelter bug: Air essence -> Everburning air

### ISSUE THREAD

**Issue by Zarko7** [FTBTeam/FTB-Modpack-Issues#5127]
### Modpack

FTB Skies Expert

### Modpack version

1.7

### Describe the bug

When smelting Air essence with the Pedestal smelter the recipe yields only 1 everburning air instead of 16 like other furnaces do.
And if done so on a server the recipe bugs out for all furnace types and yields only 1 until Server is restarted

### Steps to reproduce

1. Setup pedestal smelter
2. Smelt Air essence with pedestal smelter

### Expected behaviour

Pedestal smelter should behave like normal furnace and yield 16 everburning air; aswell as it shouldn´t bug out the recipe for all furnaces on a server

**Comment by Saereth** [comment]
Pedestal update fixed this
