### ISSUE TITLE
[Bug]: Crushing Wheel recipes still broken / infinite ore duplication

### ISSUE THREAD

**Issue by elevated-zeto** [FTBTeam/FTB-Modpack-Issues#513]
### Modpack

FTB Ultimate Anniversary Edition

### Modpack version

1.1.0

### Describe the bug

Despite the 1.1.0 Patchnotes stating that Create Crushing Wheel recipes have been fixed, they are still somewhat broken and allow for infinite ore duplication. 
Instead of crushing Ore Chunks into Crushed Ore, they are getting crushed into Dust.

Ore Chunks should be crushed into crushed ore, which is then washable into nuggets. Dust shouldn't be washable.

### Steps to reproduce

1) Crush an Ore Chunk in a crushing wheel
2) Wash the resulting dust 
3) Compact the nuggets to an Ingot
4) Crush the Ingot to dust
5) rinse and repeat

### Expected behaviour

Crushing an Ore chunk should produce a washable crushed ore. Ore Dust shouldn't be washable.

**Comment by LatvianModder** [comment]
I see the issue now. I thought crushed ore was synonymous with ore dust

**Comment by LatvianModder** [comment]
My solution for this is to use one of unused EE items, Cluster. Wheel will make clusters, and clusters can be washed for nuggets

**Comment by elevated-zeto** [comment]
Awesome, sounds good :)
