### ISSUE TITLE
Plough not making farmland from dirt (Create mod)

### ISSUE THREAD

**Issue by lexiconvict** [FTBTeam/FTB-Modpack-Issues#5130]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

Perhaps this is just user error but I can't seem to get a plough contraption to work. As per the screenshot, I set up the contraption pretty much just as the ponder displays a plough setup. It makes a sound effect as if it was doing something, but when it's pulled back, there is no change to the dirt (see the screenshot provided). I'm not the most familiar with Create, however I don't see what I could be doing wrong here. I tried bringing this up in the discord channel on the FTB server but didn't get any feedback from the other players. It will destroy torches but, again, no farmland is created. Apologies if this is just user error, but I believe it has to be some issue with the mod or pack. Cheers!
### Steps to reproduce

1. Make a "working" plough contraption from Create
2. Run the contraption over dirt
*issue occurs - no farmland is created*

### Expected behaviour

I expected the dirt to be tilled into farmland

### Screenshots

![2024-04-12_06 46 38](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/75248404/2f701bfb-f4d9-4838-b487-46e84a7e634f)

**Comment by Saereth** [comment]
you need to make sure you have fake players allowed to interact with your claim in the chunks settings

**Comment by dannyr-git** [comment]
is there a specific fake user id we can use to give create/ploughs access without ALL fake users?
