### ISSUE TITLE
[Suggestion] XNet

### ISSUE THREAD

**Issue by mrvalhar** [FTBTeam/FTB-Modpack-Issues#5133]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

Could we add XNet into this pack, with the complexities and depth of the pack it would be great to have. It provides lag free ways of networking.
Make it a tough recipe or whatnot, but would be an amazing feature.

### Mod suggestion

[https://www.curseforge.com/minecraft/mc-mods/xnet](url)

**Comment by Saereth** [comment]
been suggested but it has too many balancing issues right now so it'd have to be late game and by then not very useful. We try to avoid to many overlapping logistics mods as well as they all compound the performance hits on the pack.
