### ISSUE TITLE
Games Crashing on title screen

### ISSUE THREAD

**Issue by FurOnyx98** [FTBTeam/FTB-Modpack-Issues#5136]
### Modpack

FTB Presents F.A.M

### Modpack version

1.1.0

### Log Files

REMOVED SEGFAULT

### Describe the bug

the game crashes with a fatal error when on title screen

### Steps to reproduce

go to ftb launcher 
open mod pack 
crashes on title screen after loading in 

### Expected behaviour

game crash

**Comment by Gaz492** [comment]
This looks to be a system issue and not a modpack issue, I would suggest making sure that all of your drivers are up-to-date.
