### ISSUE TITLE
Magma anvil has no recipe but is recommended by Powerful Anvils quest

### ISSUE THREAD

**Issue by saulrh** [FTBTeam/FTB-Modpack-Issues#5137]
### Modpack

FTB Skies Expert

### Modpack version

1.6.0

### Describe the bug

The Powerful Anvils quest describes and recommends the Cyclic magma anvil, though it misnames it the "magmatic anvil". However, the magma anvil cannot be crafted and is not in the completion task's detection set.

### Steps to reproduce

1. Install FTB Skies Expert.
1. Open the quest manual
1. Go to the Gadgets and Gizmos section and look at the Powerful Anvils quest
1. Note the text recommending the "magmatic anvil"
1. Note the task does not have the magma anvil as a valid item to complete the task
1. Open JEI and search for the magma anvil
1. Note that the magma anvil has no recipe

### Expected behaviour

Magma anvil shouldn't be in the docs if it's been removed from the pack

**Comment by Saereth** [comment]
yeah this needs to just be removed from the quest
