### ISSUE TITLE
Tinker's Smeltery Controller Recipe Missing

### ISSUE THREAD

**Issue by Bentcheesee** [FTBTeam/FTB-Modpack-Issues#5139]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

The recipe for making the Smeltery Controller is missing.

### Steps to reproduce

1. Download and run Stoneblock 3
2. Search for the Smeltery Controller in REI
3. Click angrily and incredibly fast as everyone knows the more you click the more likely something will load (This line is joking btw) 

### Expected behaviour

The recipe to be present

**Comment by BitWiseBots** [comment]
This issue appears to be affecting multiple Smeltery block recipes. The Tier 2 Cobblegen is also missing.

**Comment by IcemanDs** [comment]
Same issue.

**Comment by UnRealDinnerbone** [comment]
Same as #4804
