### ISSUE TITLE
[Bug]: Server falied not start 

### ISSUE THREAD

**Issue by alije123** [FTBTeam/FTB-Modpack-Issues#514]
### Modpack

FTB Cotton

### Modpack version

 1.1.0 (server)

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7785962/latest.log)

### Describe the bug

I tried linux and windows scripts but it not working properly
I using jdk-17.0.1

### Steps to reproduce

1. Install and start server first
2. Stop server
3. Start server

### Expected behaviour

Server start

**Comment by Shadowner83** [comment]
I think this is your issue:

 Mod 'Mouse Wheelie' (mousewheelie) conflicts with any version of mod 'Applied Energistics 2' (appliedenergistics2), but a matching version is present: 8.3.0-alpha.2!
	 - While this won't prevent you from starting the game, the developer(s) of 'Mouse Wheelie' (mousewheelie) have found that version 8.3.0-alpha.2 of 'Applied Energistics 2' (appliedenergistics2) conflicts with their mod.
	 - It is heavily recommended to remove one of the mods.
	 - Mod 'Applied Energistics 2' (appliedenergistics2) v8.3.0-alpha.2 is being loaded from the user's mod directory.
	 
Try removing the mod Applied Energistics 2 and start your server again. See if that fixes it.

**Comment by alije123** [comment]
@Shadowner83, I deleted mousewheelie mod and server is working well, thanks
