### ISSUE TITLE
Recipe conflict: Create Mixer - Pumpkin Soup conflicts with Cabbage to 2x Cabbage Leaf

### ISSUE THREAD

**Issue by MacAttack-UK** [FTBTeam/FTB-Modpack-Issues#5141]
### Modpack

FTB Skies Expert

### Modpack version

1.7

### Describe the bug

I've tried numerous ways of adding the ingredients for the Pumpkin Soup recipe but as soon as the cabbage is added it crafts the cabbage into 2x cabbage leaf.

### Steps to reproduce

Add the ingredients to the basin
As soon as the Cabbage is added it crafts 2x Cabbage Leaf

### Expected behaviour

Pumpkin Soup

### Additional information

The alternative Pumpkin Soup recipe in the 'Farmers Delight' cooking pot works as it should.

**Comment by rlnt** [comment]
You can filter the recipe on a basin. You can do this with a simple filter and then adding the output item to it via drag and drop from JEI.

**Comment by MacAttack-UK** [comment]
I tried the filter thing in amongst many others in my testings, it still made the 2x Cabbage leaf. I actually set the filter with the one I made in the other mods cooking pot. On a few occasions I even manged to dupe Milk Buckets whilst trying to remove items before it messed up but wasn't sure of the steps so didn't mention it in this report.

**Comment by Saereth** [comment]
I was able to filter and craft this so not sure whats happening on your end
