### ISSUE TITLE
Refine Storage do not recognize "Honey" from productive bees as a fluid in crafting.

### ISSUE THREAD

**Issue by lyzio** [FTBTeam/FTB-Modpack-Issues#5142]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

When trying to do a crafting process with the solidification chamber, when having honey in the system the system wont recognize honey as a ingredient that is available even if there is plenty. Have tried both in a multiplayer and seperate singelplayer world. The system though recognize is as a fluid in the fluid terminal, but not as a crafting ingredient.

### Steps to reproduce

1. Have honey and other ingredients in the system (for me i have tried with the Crystalized Amber)
2. Request in refine storage to craft it.
3. Get error that honey is needed even though its in the system.

### Expected behaviour

The system recognize honey fluid as a crafting ingredient.

### Screenshots

![2024-04-17_15 54 44](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/3907428/7732915a-a069-491b-8c6e-6c7c89928fb4)

![2024-04-17_15 55 15](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/3907428/0b36483e-ec01-45e5-ae5d-c1b36ecf2d58)

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?
