### ISSUE TITLE
[Bug]: crash report

### ISSUE THREAD

**Issue by shooteram** [FTBTeam/FTB-Modpack-Issues#5144]
### Mod

-

### Mod version

-

### Forge / Fabric version

1.19.2 43.3.9

### Modpack & version

FTB Skies Expert - 1.7.0

### What issue are you having?

The game crash when I log back in-game after a while (like an hour or so). 

### Crashlogs

https://pste.ch/wukicepolo.pl

### Steps to reproduce

/

### Anything else to note?

On a teammate's map on a server.

**Comment by Saereth** [comment]
looks like too many entities, probably overlfowing mobfarm or something, gonna have to turn the server watchdog to -1 so it doesnt time out and remove the entities
