### ISSUE TITLE
FTB Sky Adventures server startup error 

### ISSUE THREAD

**Issue by PancakeCatsss** [FTBTeam/FTB-Modpack-Issues#5145]
### Modpack

FTB Sky Adventures

### Modpack version

1.4.0

### Log Files

https://www.pastelog.us/paste/KAHFIECBJDG

### Describe the bug

Missing class org.apache.logging.log4j.Level

### Steps to reproduce

1) Download FTBSkyAdventuresServer_1.4.0 server pack
2) Extract it and try run the server

### Expected behaviour

The server to load

### Additional information

I've tried using Java 8 and Java 17

**Comment by Gaz492** [comment]
Unfortunately it looks like the paste link is no longer valid, would you be able to upload the log again?
