### ISSUE TITLE
Crash when joining the world

### ISSUE THREAD

**Issue by Murchiz** [FTBTeam/FTB-Modpack-Issues#5146]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15028244/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15028246/latest.log)
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15028247/console.log)
[crash-2024-04-18_20.09.43-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15028250/crash-2024-04-18_20.09.43-client.txt)
[New world.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15028386/New.world.zip)

### Describe the bug

Crash when joining the world. I have attached my world which I have a problem with.

### Steps to reproduce

1. Launch game
2. Click singleplayer
3. Join world
4. Crash

### Expected behaviour

Game will load fine, but when loading the world game will crash

**Comment by Gaz492** [comment]
It looks like Mekanism is running into a rendering issue causing your client to crash, You may be able to enter the world again by either restoring a backup of the world or you could try deleting your playerdata and just restoring your playerdata from a backup.

**Comment by Murchiz** [comment]
Thanks a lot, replacing playerdata in the damaged world with playerdata from the undamaged world helped solve my problem.
