### ISSUE TITLE
Client crash on shift clicking the JEI recipe plus button in a crafting table

### ISSUE THREAD

**Issue by dmvgbs** [FTBTeam/FTB-Modpack-Issues#5148]
### Modpack

FTB Skies

### Modpack version

1.5.0

### Log Files

https://pastebin.com/hZtcPF6w

### Describe the bug

After todays update from the recent to the latest version of FTB Skies, the client crashes whenever I shift click a recipe from JEI to  crafting table. Doesn't even matter if you have the materials for the recipe or not.

### Steps to reproduce

Create a new world, Creative or Survival, doesn't matter.
Place a crafting table. Shift click a JEI recipe plus button within the crafting table as you would to craft multiple items of the same recipe. The client will crash then.

Edit:
Even shift clicking something like cooked stone in a furnace to get it out all at once will crash it.

Somehow it tries to access index 1 of a list that only has a length of 1, which is results in an index out of bounds.

### Expected behaviour

Should not crash when shift clicking a JEI recipe plus button in a crafting table.

**Comment by hellboym5** [comment]
i can confirm this also when use in refine storage

**Comment by Liinx** [comment]
Can confirm as well happens to me too when shift clicking on bunch of ae2/mekanism machines and upgrade slots.
Removing the flowerdoubling mod like @dmvgbs suggested really did solve the issue for me too.
