### ISSUE TITLE
FTB Skies 1.5 - New Map no boat, impossible to create island

### ISSUE THREAD

**Issue by Jason-Linux** [FTBTeam/FTB-Modpack-Issues#5149]
### Modpack

FTB Skies

### Modpack version

1.50

### Describe the bug

I download the last version 1.5 and when i create new game save, i fall for ever and ther is no boat like earlier.
I have the cheat rules activated to test /home /ftbdim  home, nothing work

### Steps to reproduce

1. Download FTB Skies 1.5
2. Create new save
3. Spawn
4. Fall until reach word limit and "tp" to the top of ther word (loop)

### Expected behaviour

Normally we spawn on the boat with portal to create our island

### Additional information

I try to download few more times and repair didn't work

**Comment by Slashinoo** [comment]
I instal the previous version (1.4.1) of the modpack, create a word, create a island, close the game, and after update the modpack at the last version (1.5.0)
Its not perfect, but it works for me

**Comment by Jason-Linux** [comment]
> I instal the previous version (1.4.1) of the modpack, create a word, create a island, close the game, and after update the modpack at the last version (1.5.0) Its not perfect, but it works for me

I would like to test the new island skin
