### ISSUE TITLE
Skies keeps crashing after installing 1.5.0

### ISSUE THREAD

**Issue by BerlinerLuft1** [FTBTeam/FTB-Modpack-Issues#5152]
### Modpack

FTB Skies

### Modpack version

1.5.0

### Log Files

[crash-2024-04-20_16.34.59-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15048624/crash-2024-04-20_16.34.59-client.txt)

### Describe the bug

Game keeps crashing randomly after short amount of time. Mostly crashes when wanting to craft something.

### Steps to reproduce

1. Start Game
2. Go into random world (mine is an world out of Version 1.3.1, in Version 1.5.0 i cant create a World)
3. Go into Crafting Table
4. Crash

### Expected behaviour

No Crash, crafting the choosen Crafting Recipe

**Comment by legoj15** [comment]
Same thing happening to me. Happens very consistently when installing/uninstalling upgrade cards in Mekanism machines and searching in the Applied Energistics Crafting ME Interface
Here's a log from when trying to interact with a Mekanism machine's UI
[2024-04-20-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15048716/2024-04-20-1.log.gz)
[crash-2024-04-20_11.09.29-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15048726/crash-2024-04-20_11.09.29-client.txt)

**Comment by duartelourenco** [comment]
Same here.
[crash-2024-04-20_16.53.39-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15049106/crash-2024-04-20_16.53.39-client.txt)
[crash-2024-04-20_16.42.39-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15049107/crash-2024-04-20_16.42.39-client.txt)
