### ISSUE TITLE
Crash when using @ to look up inventory in occultism

### ISSUE THREAD

**Issue by calog3no** [FTBTeam/FTB-Modpack-Issues#5153]
### Modpack

FTB Skies

### Modpack version

1.5.0

### Log Files

[crash-2024-04-20_14.18.05-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15049372/crash-2024-04-20_14.18.05-client.txt)

### Describe the bug

Game crashes when I attempt to use @  or shift click stack of  items out in the occultism dimensional storage actuator or remote.  JEI is synced and I can still look up items in JEI with @ and game does not crash

### Steps to reproduce

1. Start world
2. Open interface for occultism in dimensional storage actuator
3. type @ in search or shift click items out 

### Expected behavior

Search storage by mods using @ or shift click stack of items out

### Screenshots

![2024-04-20_14 32 24](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/25380281/401c34ab-e671-40b3-843c-f1773f5ef6c6)

**Comment by Saereth** [comment]
do you have shaders on or off?

**Comment by calog3no** [comment]
shaders are off

**Comment by Saereth** [comment]
This looks like an oculus crash but I cant reproduce it myself. My dev build is on 1.5.1 though which will release soon. After you update try and see if you can produce it on 1.5.1 because I'm not having any luck. Update will be out shortly

**Comment by calog3no** [comment]
ok awesome thanks for the update. I'll reply here after I update if it's out before I head to work, or first thin tomorrow am (est-US)

**Comment by calog3no** [comment]
updated to 1.5.1 and no more crashes!!! Thanks again! I will close the issues.
