### ISSUE TITLE
Infinite stress units

### ISSUE THREAD

**Issue by CrimsonBlaze513** [FTBTeam/FTB-Modpack-Issues#5154]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

My power generator keeps having unreal amount of SU. I had my two Turbo Diesel Generators running and I come back and they are making according to my stressometer 4,354,560su. Then I could turn of my generators and it's still making 2,806,272su without anything create the SU.

### Steps to reproduce

I have no idea. I leave the ganerators on and then the stressometer reads a crap ton of su after a bit.

### Expected behaviour

I should have no SU when generators are off and 1,548,288su from my two Turbo Diesel Generators when on.

### Screenshots

![Screenshot 2024-04-20 154450](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/108965134/82f5bcda-7891-4cec-b08b-623f98901c33)
![Screenshot 2024-04-20 154545](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/108965134/18444ee5-cf6c-4744-b8d1-91d979cb4e17)

**Comment by Saereth** [comment]
should be fixed with next update as custom machinery added some code to fix this
