### ISSUE TITLE
Quest gives reward that is a missing item

### ISSUE THREAD

**Issue by Fuzzbling** [FTBTeam/FTB-Modpack-Issues#5155]
### Modpack

FTB Skies

### Modpack version

1.5.1

### Describe the bug

Quest gives reward that is a missing item - incubation:fried_egg

### Steps to reproduce

Open Quests -> Getting Started -> Sifter go Brrr

### Expected behaviour

Quest reward is Fried Egg from Farmer Delight

### Screenshots

<img width="1920" alt="Screenshot 2024-04-20 161700" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/5251587/8c78f8df-755f-4648-bf21-7bdd05cab0bf">

**Comment by KarlSchmitte** [comment]
I also have this issue. Gives me the question block with incubation:fried_egg. Also seems to be missing nature compass because that also appears to be a question block when you right click the incubation:fried_egg in JEI.

**Comment by Ledeanna** [comment]
Same here

**Comment by Firepoppy5** [comment]
here as well

**Comment by Ledeanna** [comment]
also a few other quests have missing items like the xp holder
