### ISSUE TITLE
Saerth's grave is included with the Amethyst Island

### ISSUE THREAD

**Issue by tyreforhyred** [FTBTeam/FTB-Modpack-Issues#5157]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

Amethyst Island always loads in with Saerth's grave at coordinates 111, 1, 122

### Steps to reproduce

start up a new world, choose Amethyst Island, go to coordinates 111, 1, 122 and observe Saerth's grave

### Expected behaviour

probably not what is occuring as you cannot remove the grave outside of creative mode

### Screenshots

![sg](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/76914208/f0df28f0-f79e-496c-8fef-a6ed5bd2d1d6)

**Comment by Saereth** [comment]
This is an easter egg we decided to leave in, there is actually a way to mine it for the stuff but you need to progress quite a bit to be able to do it :P
