### ISSUE TITLE
Nether coordinates completely broken

### ISSUE THREAD

**Issue by Kiito10** [FTBTeam/FTB-Modpack-Issues#5162]
### Modpack

FTB Skies

### Modpack version

1.5.1

### Describe the bug

First things first, I am playing on a world from 1.4.1. When I try to enter the nether it sends me tens of thousands of blocks away, and when I try to go back to my island it doesn't even put me in the same world as I found out when I tried to teleport back to zero zero. I included the screenshots of me before going into the portal on my island, screenshots of my location in the nether, where I go back after I go through the portal again, where I go when I teleport to 0 64 0 using commands, and what happens when I die.

### Steps to reproduce

I have no idea, the only things I can tell you is that I made the world on version 1.4.1 of the modpack and now on version 1.5.1 the portal is broken, I have no idea what would have happened if I went into the nether without updating as I did not have a portal when I was still on version 1.4.1

### Expected behaviour

I expected to go to appropriate coordinates in the nether and come back to my island when I went back.

### Screenshots

![2024-04-22_10 59 57](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/32998071/42a758ff-c234-4023-9426-faed550a330f)
![2024-04-22_10 59 58](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/32998071/9f390605-ac76-470a-8967-6662ee7416d9)
![2024-04-22_11 00 09](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/32998071/d3dc7f11-786b-4704-a896-f036c0d49a33)
![2024-04-22_11 00 10](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/32998071/a8c8f193-80d2-4b22-adcc-91b423dac20e)
![2024-04-22_11 00 19](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/32998071/a5383630-0eb8-4058-8088-3613675b1c51)
![2024-04-22_11 00 20](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/32998071/02df7513-3378-4e00-9ff0-dadf1d4c1228)
![2024-04-22_11 00 39](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/32998071/17197d17-7017-46f1-871a-3c8ed42b0b10)
![2024-04-22_11 00 40](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/32998071/76ff90a5-fe11-45a5-86d2-f9060b36a97a)
![2024-04-22_11 00 54](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/32998071/e51e5152-40db-4c74-8fb1-1292d760aec4)
![2024-04-22_11 00 55](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/32998071/3cacdcd4-182c-472e-a8ae-0d190d6554ed)

**Comment by Kiito10** [comment]
I am currently building on a new save because I am making my first bigger build and I want to first build it in creative and though to quickly check the nether, and while it does put me tens of thousand of blocks away from zero zero(which I don't like because mild OCD) it does bring me back to the correct portal, so it seems like the problem is indeed because of the save being from an earlier version, but I would like to actually keep playing on my save so I would be happy if it was fixed :).

**Comment by Kiito10** [comment]
ignore the thing being completed and reopened, first time I am posting about an issue on github and had no idea what that button did.

**Comment by Saereth** [comment]
we have a similar issue already open in skies expert, referenced this one over there and im closing this one to keep it all in one place https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5303

**Comment by desht** [comment]
The random coordinates that a team is sent to depends solely upon the team UUID, and is not related to the world seed in any way. I don't know why updating to a newer version of the pack would change those coordinates, unless the team ID has somehow changed as well...?  Was the team disbanded and recreated?
