### ISSUE TITLE
Log chips from Productive Bees and Sequential Fabriactor from Thermal not crafting correct logs

### ISSUE THREAD

**Issue by lurch9229** [FTBTeam/FTB-Modpack-Issues#5165]
### Modpack

FTB Skies Expert

### Modpack version

1.7.0

### Describe the bug

I was trying to find a way to auto-craft log chips into logs, and decided to use a sequential fabricator. However the outputted log from this craft is an oak log, not the force logs I was trying to make. 

### Steps to reproduce

place and power sequential fabricator
input recipe for logs using log chips
note that the output preview shows the correct logs
place logs chips in the fabricator
get oak logs out

### Expected behaviour

expected to get the correct logs from log chips

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/38219473/1357fc46-ed7e-44f5-a476-b03c2153e309)

**Comment by isochronous** [comment]
Yeah, I wound up having to use a friggin' turtle of all things to craft these correctly. For now, just craft a block upgrade as soon as you can - they're not too hard to make.

**Comment by lurch9229** [comment]
I actually ended up using the crafter from RFTools. Originally tried using a compacting drawer but that didn't craft the logs either

**Comment by isochronous** [comment]
I found that the rftools crafter got confused by multiple types of chips

**Comment by Saereth** [comment]
yeah this is unfortunately just an oredicting limitation, no real great work around but yeah basically incentive is to just rush the full block upgrade, its why we made them relatively cheap compared to other upgrades
