### ISSUE TITLE
Please help with crash on FTB Infinity Evolved

### ISSUE THREAD

**Issue by Jaimarl** [FTBTeam/FTB-Modpack-Issues#5168]
### Modpack

FTB Infinity Evolved 1.7

### Modpack version

3.1.0

### Log Files

Log: https://gist.github.com/Jaimarl/0f1291bafb3515007731d3dc56713613
Crash report: https://gist.github.com/Jaimarl/7857cb05ba9b2430eb9bfbff42dc2bbb

### Describe the bug

My friend and I decided to pass FTB Infinity Evolved, replaced some mods and the modpack worked stably until it started crashing. We tried to find out the reason but nothing was found. Crashes for no reason at random times after entering the world.

### Steps to reproduce

idk

### Expected behaviour

Work stable

**Comment by Gaz492** [comment]
The crash looks to be caused by a rendering error on a dropped item.
I can see you have optifine installed, which may be the source of the issue as it did not play well with mods back in 1.7.10, I would recommend disabling/removing that mod to see if it changes anything for you.

**Comment by Jaimarl** [comment]
Thank you, it worked.
