### ISSUE TITLE
Builders Paradise 2 UI Shift

### ISSUE THREAD

**Issue by CurtisT15** [FTBTeam/FTB-Modpack-Issues#5169]
### Modpack

FTB Builders Paradise

### Modpack version

1.0.0

### Describe the bug

When equipping an elytra in survival mode, it causes an inventory UI, pause menu, and the exp bar shift to the right. This only happens in survival mode and not in creative mode. 

### Steps to reproduce

1. Create new world.
2. Find/Give player elytra.
3. Equip elytra while in survival mode. 

### Expected behaviour

The UI to not shift to the right. 

### Screenshots

![ExpBar_Issue](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/90854196/7575f866-6ad5-4846-b3ae-4fc7a069deab)
![Inventory_Issue](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/90854196/731ad9a4-7913-4ad6-b272-336d49c0e651)
![Inventory_Normal](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/90854196/fc61c475-ea5d-4570-bb98-a27a1cd6bf5d)
![PauseMenu_Issue](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/90854196/4d837e11-e356-45d5-b014-c75fd87a1740)
![PauseMenu_Normal](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/90854196/33c50d96-792c-4941-975f-f39a71a0a64d)

### Additional information

I have the initial default settings from when installing the modpack, and I have not found any relevant messages in the logs that could help in discovering the cause of the issue.

**Comment by Saereth** [comment]
ok looks like this was one of the quark experimental settings, should be fixed in v1.1.0
