### ISSUE TITLE
[Bug]: Height Detector not showing levels

### ISSUE THREAD

**Issue by Shadowner83** [FTBTeam/FTB-Modpack-Issues#517]
### Modpack

Creeperhost SteveCarts in FTB Ultimate Anniversary Edition

### Modpack version
Creeperhost SteveCarts stevescarts-alpha1.0.22.jar
FTB Ultimate Anniversary Edition 1.1.0

### Describe the bug

I built a train for mining but the Height sensor is not showing the height level.
This makes the train just go mining downwards instead of moving forward and then going down a level.

For reference I used the same setup as Chosen Architects setup here: https://www.youtube.com/watch?v=_zqn4uqJK98&list=PL_ipI8CnaNIYn9sS5qOHkFHEfh83N09EA&index=7&t=707s

### Steps to reproduce

1) Built train with standard hull, coal engine, side chests, fluid detector, block placer and height detector
2) Place the train and open the GUI
3) Scroll a bit down and you are able to set the level but its not showing with level it is.

### Expected behaviour

Y level should be visible and the train should move forward and then move 1 level every block ahead.

**Comment by Shadowner83** [comment]
Added specific mod and version in the Modpack for reference.

**Comment by Raidobw2** [comment]
Thanks for the thorough reports. CreeperHost/StevesCarts2#2
