### ISSUE TITLE
Rats Mob Filter Resetting bug

### ISSUE THREAD

**Issue by RedDamer** [FTBTeam/FTB-Modpack-Issues#5173]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

While trying to filter my rat to hunt only cows from my cow farm, I noticed it resets itself and clears any selected settings when you go to give the rat the filter upgrade.

### Steps to reproduce

1. Have a rat tamed.
2. Have a Rat Upgrade: Mob Filter.
3. Right click to open filter upgrade, toggle on the left to be whitelist, and then search/select Cow
4. close out of gui.
5. Now, without clicking on the tamed rat, if you open your inventory and hover over the filter, it will show your selected settings, however, when you right click on the rat in order to give the upgrade, when you now hover over the filter, it has cleared itself.

### Expected behaviour

Filter retains selected options.

### Screenshots

![2024-04-27_16 28 07](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165237224/50076dc1-2f36-4213-93dd-6bcbfd40f621)
![2024-04-27_16 28 29](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165237224/44b88dab-a39c-42f5-857a-2891ee384e11)
![2024-04-27_16 28 46](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165237224/efb54e8d-19f6-483a-927f-7499918aa1e7)
![2024-04-27_16 28 51](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165237224/44853a2e-d9b8-43e1-973a-6676580cca93)
![2024-04-27_16 29 02](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/165237224/be06c6ee-a57d-4f8a-97bc-1156b0881539)

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by Robertdebrus** [comment]
This is still an issue on rats 1.20.1 - 8.1.2
