### ISSUE TITLE
Accessing crafting table ui in places where you shouldnt be able to completely locks the world

### ISSUE THREAD

**Issue by Pikaahhh** [FTBTeam/FTB-Modpack-Issues#5174]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

Sometimes attempting to craft an item from the quest menu doesn't block the button to put items into the crafting table. If you press that button it does open up the crafting ui, however it does also completely lock the world from being loaded once you leave, and doing anything before you leave it. This has happened twice already and now I cant play either worlds I've started.

### Steps to reproduce

1. Open Quest Menu
2. Look at a recipe via quest.
3. Check if the crafting button is blocked or not.
4. If it isn't, press the button.
5. Watch as your world can no longer be played on.

### Expected behaviour

The world freezes.

### Additional information

This might be because I have my world open to LAN?

**Comment by UnRealDinnerbone** [comment]
An Update has been released since this issue was made. Can you please confirm this issue, it's still happening?
