### ISSUE TITLE
[Bug]: FTB Revelation Iron Plates

### ISSUE THREAD

**Issue by panettone98** [FTBTeam/FTB-Modpack-Issues#5175]
### Mod

Unidict 

### Mod version

unidict 3.0.10

### Forge / Fabric version

14.23.5.2858

### Modpack & version

FTB Revelation 3.6.0

### What issue are you having?

IC2 Iron and Tin plates can't be forged. 
Unidict 3.0.10 seems to be the issue. Reverting mod to 3.0.8 works.

### Steps to reproduce

Placing Forge Hammer into crafting table along Iron or Tin ingot should produce a plate,but doesn't. 
Workaround is to use Tinker's  smeltery to forge a single plate.

**Comment by Gaz492** [comment]
duplicate of #3566
