### ISSUE TITLE
Server crash after death

### ISSUE THREAD

**Issue by RubenB98** [FTBTeam/FTB-Modpack-Issues#5176]
### Modpack

Other...

### Modpack version

1.9.0

### Describe the bug

Running my own server for FTB Endeavour which works fine until i die after an unknown amount of time, in which case the server crashes and i lose my items.

I haven't been able to test this with other players yet

### Steps to reproduce

1. Start the server
2. join
3. die after x amount of time (i only died after 30mins or so)
4. server crashes

### Expected behaviour

be able to keep playing

**Comment by Gaz492** [comment]
Would you be able to upload the crash report so I can have a look at it.
