### ISSUE TITLE
regrowth crash on startup

### ISSUE THREAD

**Issue by Mufi432** [FTBTeam/FTB-Modpack-Issues#5177]
### Modpack

Other...

### Modpack version

1.0.2

### Log Files

[minecraft-exported-crash-info-2024-05-02T10-14-06.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15185647/minecraft-exported-crash-info-2024-05-02T10-14-06.zip)

### Describe the bug

its a graphics driver problem

### Steps to reproduce

1.have the wrong driver
2. launch the game

### Expected behaviour

i expectedit to start

**Comment by WyFryMU** [comment]
Are your graphic drivers up to date?

**Comment by Mufi432** [comment]
Yes

**Comment by 5ully** [comment]
Not a FTB Modpack, but try using Java 8 on build 101 or 144

**Comment by Mufi432** [comment]
Thanks i'll try
