### ISSUE TITLE
Sifter Quest not completing on building required items

### ISSUE THREAD

**Issue by DildHussette** [FTBTeam/FTB-Modpack-Issues#5178]
### Modpack

FTB Skies Expert

### Modpack version

1.19.2

### Describe the bug

After crafting the sifter and hand crank it still says I have not completed the quest and cant progress.

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/168799079/eea64b58-4b92-4400-b1e7-29296644fe69)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/168799079/8208117f-20d9-447b-bf0b-ea6fa18bd97b)

### Steps to reproduce

1. Craft Sifter and Hand Crank
2. Try to turn in quest
3. Quest not complete

### Expected behaviour

Quest to be completed

**Comment by SamuUndici** [comment]
The same happens to me
