### ISSUE TITLE
[Bug]: Flux Points Sever Connection to Integrated Dynamics Energy Interface on World Load

### ISSUE THREAD

**Issue by DizzyDJW** [FTBTeam/FTB-Modpack-Issues#518]
### Modpack

Oceanblock

### Modpack version

1.11.0

### Describe the bug

Flux Points stop being connected to Integrated Dynamics Energy Interfaces on world load. 

### Steps to reproduce

1. Place Flux Point
2. Attach Energy Interface
3. Reload World
4. See Issue

### Expected behaviour

Flux Points should remain attached to whatever block they begin attached to.

### Additional information

Integrated Dynamics is used since it has the ability to move Int FE/t. It is a basic setup, with Energy Interfaces attacked to Chaos Fusion Injectors and one more attached to a Flux Point. Very easy to replicate thus far, and has happened 100% of the time, every single world load.

**Comment by TheonlyTazz** [comment]
This should have been fixed with the latest version of Fluxnetworks that got shipped with v1.12.0
