### ISSUE TITLE
Recipes for Sugar Cane block randomly chosen in Cyclic workbench

### ISSUE THREAD

**Issue by Mipsters** [FTBTeam/FTB-Modpack-Issues#5186]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

When attempting to create a sugar cane block with 9 sugar canes in Cyclic's workbench, there are two blocks that can be created
they seem to be chosen randomly
in the vanilla workbench there's a button to choose between the two, but it doesn't exist in Cyclic's workbench

### Steps to reproduce

1. get 9 sugar canes
2. use a crafting table
3. try to craft a sugar cane block
4. you will see a result from either tropicraft:thatch_bundle or thermal:sugar_cane_block

### Expected behaviour

only one result per recipe

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/4920832/7f99ea2b-074c-48f9-9cf6-dd878ff89a5f)

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/4920832/48a5a7c1-457f-4ab9-9cb4-7fe23dfd7ae1)

**Comment by Gaz492** [comment]
It looks like Cyclic support has not yet been added/ported to polymorph
https://github.com/illusivesoulworks/polymorph/issues/186
