### ISSUE TITLE
Server installer failed | Error downloading 404 Not Found 

### ISSUE THREAD

**Issue by Nawrux** [FTBTeam/FTB-Modpack-Issues#5188]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Log Files

https://pastebin.com/5Sq9N24L

### Describe the bug

Server installer can't download mcp_config 404 not found :
"Error downloading https://maven.neoforged.net/releases/de/oceanlabs/mcp/mcp_config/1.20.1-20230612.114412/mcp_config-1.20.1-20230612.114412.zip: server returned 404 Not Found"

### Steps to reproduce

1. Download server installer for 1.10,1.11, 1.12, 1.12.1 (tried these versions, all not working) 
2. start exe in terminal
3. wait for error server not found (always the same)
4. A problem installing was detected, install cannot continue
    2024/05/05 00:06:28  NeoForge installer failed with exit code 1, retrying...
    2024/05/05 00:06:28 NeoForge failed to install multiple times exiting...
5. cry

### Expected behaviour

That the server would install

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/126285502/f2448816-46de-4b97-ae76-b3e83e6e491b)

### Additional information

Running on Windows 11 with java 17 installed

**Comment by Gaz492** [comment]
Can you confirm if this is still an issue for you?
I have not been able to reproduce this in my testing.
