### ISSUE TITLE
Server is unable to start after upgrading from 1.7.0 to 1.8.1

### ISSUE THREAD

**Issue by Citrus0299** [FTBTeam/FTB-Modpack-Issues#5189]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Log Files

latest.log: https://pste.ch/rekiwonafa.md
crash-2024-05-05_11.55.33-fml.txt :https://pste.ch/unizekawin.php

### Describe the bug

After renaming and using the linux serverinstall script to update the modpack from version 1.7.0 to 1.8.1 the server will no longer start. All of the choices made during the upgrade were done by using the default [y]

### Steps to reproduce

1. Upgrade the Modpack FTB Skies Expert from version 1.7.0. to 1.8.1 using the installers upgrade feature
2. start the server

### Expected behaviour

The server should start after the upgrade

### Screenshots

nA

### Additional information

nA

**Comment by Zonk1987** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5180#issue-2277343518

**Comment by Citrus0299** [comment]
How did I overlook that, thanks
