### ISSUE TITLE
[Feature Request]: FTB Ultimate AE Immersive petroleum

### ISSUE THREAD

**Issue by opticGT** [FTBTeam/FTB-Modpack-Issues#519]
### Mod

immersive petroleum 

### Description

Immersive Petroleum is a lightweight content add-on for Immersive Engineering that introduces oil, oil extraction, and oil processing to the mod's tech progression. It includes an expansive set of configuration options to ensure that it will be a welcome addition to any modpack that includes Immersive Engineering.
![HB4Q0Lg](https://user-images.githubusercontent.com/19476801/144968544-1aede9f4-2272-4137-9e2d-651b053139f9.png)

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
