### ISSUE TITLE
stoneblock 3 isn't launching

### ISSUE THREAD

**Issue by AgataKatsu** [FTBTeam/FTB-Modpack-Issues#5190]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Log Files

[2024-05-05-3.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15212975/2024-05-05-3.log.gz)

### Describe the bug

crushed before starting

### Steps to reproduce

1. launch on MacBook m1pro fab stoneblock 3
2. wait

### Expected behaviour

launching the Minecraft

**Comment by Gaz492** [comment]
If you are still having the issue, could you try deleting the options.txt in the folder where the modpack is installed?
