### ISSUE TITLE
Phytogenic insolator overfilling

### ISSUE THREAD

**Issue by gnadelstein** [FTBTeam/FTB-Modpack-Issues#5191]
### Modpack

FTB Skies Expert

### Modpack version

1.5.0

### Describe the bug

when a force sapling is in the phytogenic insolator with cyclical processing augment, it grows force logs with stacks of 108 in each slot

### Steps to reproduce

1. power up phytogenic insolator and fill with water
2. add cyclic processing augment from thermal expansion (i also have a reinforced integral components to speed it up)
3. add bonemeal (or other fertilizer?)
4. wait for the slots to overfill 

### Expected behaviour

output stacks to fill with 64 force logs

**Comment by Saereth** [comment]
This is just a byproduct of the heavy multiplier force logs get in there, should be fine/trivial.
