### ISSUE TITLE
Alfheim Gateway normal reversed

### ISSUE THREAD

**Issue by JJSax** [FTBTeam/FTB-Modpack-Issues#5196]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Describe the bug

Small potential bug, likely a botania bug.

The portal to the alfheim has two renderings of the portal animation, and I assume just for performance, only one is drawn unless you're inside the portal.  You can see both when you step into the portal.

I believe the normals are pointed in the wrong direction which causes visual inconsistencies depending on which side of the portal you're on.

### Steps to reproduce

Make a botania alfheim portal,
go through it paying attention to where the renderings are

### Expected behaviour

I expected the green parts to always show on the closer edge to you

### Screenshots

![2024-05-06_17 27 35](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/5084938/5a853825-49fb-4dbc-9a45-1ef4cfe4e714)

**Comment by Saereth** [comment]
This is a botania specific issue, you'll need to take it up with the maintainers of that mod to request a change in how they render it, nothing we can do about it from the pack side of things
