### ISSUE TITLE
Blackscreen/Loading Errors FTB 

### ISSUE THREAD

**Issue by shnewitchnx9** [FTBTeam/FTB-Modpack-Issues#5197]
### Modpack

FTB Infinity Evolved Skyblock

### Modpack version

2.0.1

### Describe the bug

I started a new Server with a Friend, first it startet normaly only thing i had no Sounds but thats okay, after 10 minutes i got some Texture Failures, some blocks went White and i had blackscreen, after restart/newinstall with Start as Admin i cant log in, when im logging in get instant blackscreen , in Console it shows me some Errors while Loading Item Textures 

### Steps to reproduce

Dont think it can be reproduced

### Expected behaviour

If anyone knows please help me

**Comment by Gaz492** [comment]
Would you be able to upload a log from the modpack so we can take a look at it?
May I also ask what your computer specifications are (CPU, GPU) as it sounds like it may be a graphics driver issue.

We no longer provide bug fix updates to this pack due to its age so there may not be much we can do.
