### ISSUE TITLE
Integrated Dynamics crash freeze

### ISSUE THREAD

**Issue by sebasti1987** [FTBTeam/FTB-Modpack-Issues#520]
### Mod

ftb oceanblock, Integrated Dynamics

### Mod version

for ftb ocean block 1.9 or 1.10.1 or Integrated Dynamics version 1.16.5 : 1.10.5 or Integrated Dynamics 1.16.5 : 1.10.6

### Forge / Fabric version

version, 1.16.5-forge-36.2.9

### Modpack & version

FTB oceanblock version 1.9 or 1.10.1

### What issue are you having?

Hello, first of all I want to apologize for my English, I'm French
Here is when we launch an auto craft with integrated the games this freezes in freeze and it remains freeze no warn appears in the console and the bug and on our server and in solo, each time this freeze exept from time to time it does not not freeze but its very rare most of the time the games this block to infinity and impossible to unlock even after hours nothing changes a screenshot will not be used on the other hand if I am the first to report this bug I will share a video with you, to show what happens (I attach a ytb link to show you what happens during the freeze)

link bug::  https://youtu.be/s4K5ZOwFa6I

### Crashlogs

No crash log was created during the problem, I am not a developer and I only have small databases so I cannot provide you with a crashlog because it does not create this

### Steps to reproduce

to reproduce the bug you just have to launch an auto craft with integrated dynamic (I attached a video, a ytb link found above or it shows the problem)

link bug :::   https://youtu.be/s4K5ZOwFa6I

### Anything else to note?

I hope that the problem can be solved, thank you in advance, once again excuse me for my English I use google translate thank you for your understanding and your work

**Comment by Raidobw2** [comment]
EN
Sunekaer leave this one open until mod bug is confirmed. I'll close this current one to only keep the other when that happens.
FR
Sunekaer laisse celui-ci ouvert jusqu'à ce que le bug soit confirmé. Je vais fermer ce billet-ci pour garder l'autre quand cela va arriver.

**Comment by Raidobw2** [comment]
EN
Will be fixed next update. To manually fix it, head to the file `config/integratedterminals-common.toml` and change `craftingPlannerEnableMultithreading` to "false".
FR
Ça va être résolu la prochaine mise à jour. Pour corriger l'erreur manuellement, aller au fichier `config/integratedterminals-common.toml`  et changer `craftingPlannerEnableMultithreading` à "false".
![image](https://user-images.githubusercontent.com/17010632/153594378-c60455c1-ae4e-465b-8f6d-a8797c676fbb.png)
