### ISSUE TITLE
Quantum Flud not Quantum Fluid

### ISSUE THREAD

**Issue by tombaku** [FTBTeam/FTB-Modpack-Issues#5200]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Describe the bug

Localisation of createteleporters:quantum_fluid is currently the words 'Quantum Flud'. As this was not this way in previous version i am unsure if this is a intended feature however i didn't see it in changelogs.

### Steps to reproduce

Search for the Fluid in JEI

### Expected behaviour

Change of the name to 'Quantum Fluid'

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/7895377/fc37d7ef-2493-44e3-89fa-8bdc71e6c08a)

**Comment by pikminman13** [comment]
this is a problem with the base mod and not really FTB's department
