### ISSUE TITLE
ShapeBuilder crash game

### ISSUE THREAD

**Issue by Belique** [FTBTeam/FTB-Modpack-Issues#5201]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Log Files

[crash-2024-05-08_13.09.07-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15252508/crash-2024-05-08_13.09.07-client.txt)
[crash-2024-05-08_15.07.45-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15252509/crash-2024-05-08_15.07.45-client.txt)
[crash-2024-05-08_19.12.51-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15252510/crash-2024-05-08_19.12.51-client.txt)

### Describe the bug

Game crashes with no way to recover. The game will now instantly crash after loading the world, causing the loss of the world or making it impossible to log back into a server where the bug occurs.

### Steps to reproduce

Step 1: Place a Shape Builder from Cyclic.
Step 2: Fill the Shape Builder with a fence Occurs with any fence, regardless of whether it's from a mod or vanilla.)
Step 3: Activate the Preview Rendered.
(The order of steps 2 and 3 doesn't matter.)

### Expected behaviour

Render the shape nothing more x:

**Comment by 9mahall** [comment]
Also getting this issue, not sure how to disable the block in the configs or how to recover from the bug/prevent in the future.

**Comment by chase-robbins** [comment]
+1 on this issue. Here is my crash log: https://pastebin.com/jXv383R0

Experiencing this on Direwolf20 1.20 1.12.1

**Comment by Saereth** [comment]
Since cyclic hasnt fixed this in months im disabling it in the pack
