### ISSUE TITLE
Diesel generators stop working once world is loaded

### ISSUE THREAD

**Issue by DustEyezz** [FTBTeam/FTB-Modpack-Issues#5205]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Log Files

https://pste.ch/ericosayer.md //latest.log
https://pste.ch/hafulejeva.md //debug.log

### Describe the bug

Upon loading in half of my diesel generators, normal and advanced alike, don't spin the cogs attached to them, but they are running.

### Steps to reproduce

1. Load world
2. half the generators aren't working
3. destroy and place generator or cog on it to fix

### Expected behaviour

my diesel generators should keep running

**Comment by Saereth** [comment]
some screenshots of your setup would be useful here, make sure you're not on chunk borders and stuff or have backlinking stressors. etc etc

**Comment by DustEyezz** [comment]
![2024-05-10_11 24 43](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/75487794/5d587208-1b85-48bc-af02-f0d210d880c9)
![2024-05-10_11 24 49](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/75487794/421100e5-c3f3-452f-820e-27905fdb66f3)
![2024-05-10_11 27 13](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/75487794/19c81c53-fd30-446a-9bd1-6eebe1ba01c7)
1 of them crosses chunk borders, but the other is directly linked to 4 liquid crystallizers in the same chunk and also doesn't work
