### ISSUE TITLE
Bootstrapped Tech Questline: Molecular Transformer and Stabilized Machine Block Recipe Missing

### ISSUE THREAD

**Issue by Jakads** [FTBTeam/FTB-Modpack-Issues#5206]
### Modpack

FTB Genesis

### Modpack version

1.5.0

### Describe the bug

Molecular Transformer and Stabilized Machine Block, which are quintissential to further game progress, are impossible to craft in FTB Genesis 1.5.0. While the recipe existed until 1.4.0, it seems to have disappeared in the latest update.

### Steps to reproduce

You can check that there is no recipe in JEI.

### Expected behaviour

You must be able to craft them.

**Comment by ArtpokeBr** [comment]
closing as this issue have been reported already, no worries tho, already fixed the recipe issues in dev :p
