### ISSUE TITLE
[Bug]: Can't craft Creative Chemical Tank on 1.11.0

### ISSUE THREAD

**Issue by Venomia** [FTBTeam/FTB-Modpack-Issues#521]
### Mod

Extended Crafting / JEI?

### Mod version

ExtendedCrafting-1.16.5-3.1.10 and jei-1.16.5-7.7.1.137+8

### Forge / Fabric version

Forge: 36.2.20

### Modpack & version

FTB OceanBlock 1.11.0

### What issue are you having?

Inputting the recipe for creative chemical tank from JEI places the tanks wrong but even after fixing them manually, the recipe doesn't work.

https://imgur.com/a/NOBL1Nv

### Steps to reproduce

1. press the "+" icon on JEI to input all the things
2. fix the order of the tanks
3. No output

**Comment by Raidobw2** [comment]
Hmm that's strange. Normally I think that was fixed in 1.10.1. I'm on a clean 1.11.0 instance. Maybe you can backup all your data (`saves`, `local` and options.txt for keybinds) and try to reinstall to a clean state?
![image](https://user-images.githubusercontent.com/17010632/147752995-23786b13-fb00-4b1c-866e-5b8ba157343f.png)

**Comment by Raidobw2** [comment]
p.s.: The JEI quirk that misplaces the tank I'm not sure if we can do anything about it, it's NBT acting weird

**Comment by Venomia** [comment]
> Hmm that's strange. Normally I think that was fixed in 1.10.1. I'm on a clean 1.11.0 instance. Maybe you can backup all your data (`saves`, `local` and options.txt for keybinds) and try to reinstall to a clean state? ![image](https://user-images.githubusercontent.com/17010632/147752995-23786b13-fb00-4b1c-866e-5b8ba157343f.png)

I'm almost done with the pack, I don't want to have to redo all the settings and configs (I have some custom ones that have nothing to do with this) I'm just going to cheat it in, posted it more in case it's an issue with anyone else too! :) Thanks a lot though!

**Comment by Raidobw2** [comment]
Alrighty, thanks for playing!

**Comment by Venomia** [comment]
It seems it's only an issue when the tanks have an Owner a.k.a have been placed. So if anyone is researching this, fill up the tanks without placing them! :) Same happens with this recipe:

https://imgur.com/a/ao8OTDG
