### ISSUE TITLE
Compressium not working with Prefab Bulldozer

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#5211]
### Modpack

FTB University 1.19

### Modpack version

Latest

### Describe the bug

Compressium replacement for Prefabs compressed stone does not work to activate the bulldozer.

### Steps to reproduce

Compress stone.
Anvil Bulldozer with Compressed Stone.

### Expected behaviour

The bulldozer needs to be anviled with Prefab's compressed stone

### Screenshots

![Stone no stone](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/77522101/820d0388-6977-4946-ad8c-de8bc2884977)

**Comment by UnRealDinnerbone** [comment]
Same as #4743
