### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by ihcookiedan** [FTBTeam/FTB-Modpack-Issues#5212]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Describe the bug

as soon as the instance tries to load, the game crashes. The Log reports Mekanism tanks and something from Thermal? Im not sure on that one. 

### Steps to reproduce

Just load instance. as soon as game tries to load, when it reaches 100%, it crashes.

### Expected behaviour

The game to load and open

**Comment by WyFryMU** [comment]
Maybe try a fresh install? Otherwise provide a log file.
