### ISSUE TITLE
EnderIO SAG Mill

### ISSUE THREAD

**Issue by Purex100k** [FTBTeam/FTB-Modpack-Issues#5213]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

I can't make the SAG Mill take any raw materials. It only takes ingots?

### Steps to reproduce

I dont know

### Expected behaviour

So that  the SAG Mill can take raw material

### Additional information

Thats it :)

**Comment by Purex100k** [comment]
Im not playing before we can use EnderIO :(

**Comment by Gaz492** [comment]
I have not been able to reproduce this issue so far, may I ask exactly what raw materials you are giving the SAG mill and if possible a screenshot(s) of your setup?
