### ISSUE TITLE
Compact Machine Island unable to play

### ISSUE THREAD

**Issue by Ledeanna** [FTBTeam/FTB-Modpack-Issues#5214]
### Modpack

FTB Skies

### Modpack version

1.5.1

### Describe the bug

You Start the Compact Machine Island Start you get the basic items like you do on the ship and in the world is a angel block with a pedestal on top with the compact machine.  That is it No Shrinking Device No Dirt No Water etc.  Those are given in quests in Expert but you can't get them without cheating in regular skies.

### Steps to reproduce

Create Compact Machine Island in 1.5.1

### Expected behaviour

You should get items like shrinking device etc.

**Comment by LouisOuellet** [comment]
Yup had the same issue when the last update released. I had to start from a different island instead.

**Comment by LouisOuellet** [comment]
This issue still persists in version 1.6.0. We still do not spawn with the tool required to enter the compact machine.
