### ISSUE TITLE
Internal Exception: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0 Error

### ISSUE THREAD

**Issue by iiDevWaffle1** [FTBTeam/FTB-Modpack-Issues#5215]
### Modpack

FTB OceanBlock

### Modpack version

1.16.0

### Log Files

[2024-05-13-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15290215/2024-05-13-1.log.gz)

### Describe the bug

When trying to join a friends server through minetogether, it gives me the error stated in the title and in the command box it also says, [Netty Client IO #1/ERROR] [minecraft/WorldSettingsImport]: Error adding element: Unknown registry element com.brandon3055.draconicevolution.world.DEWorldGen$1@768b768a

### Steps to reproduce

1. Load up modpack.
2. Have a friend open a server
3. Join server

### Expected behaviour

Allow you to join the server

**Comment by UnRealDinnerbone** [comment]
Is your friend on the same version as you? If so, can you also upload their logs, please.
