### ISSUE TITLE
[Bug]: Mageboom crop not dropping seeds

### ISSUE THREAD

**Issue by Fatom20** [FTBTeam/FTB-Modpack-Issues#5216]
### Mod

Ars Nouveau

### Mod version

2.23.0

### Forge / Fabric version

43.3.8

### Modpack & version

FTB Skies Expert 1.8.1

### What issue are you having?

Mageboom crop not dropping seeds, only the Magebloom flower when planted on vanilla farmland.
Only way to duplicate is Garden cloche and phytogenic insolator (or default recipe from ars)

### Steps to reproduce

Plant Magebloom seed on farmland, harvest when fully grown

**Comment by botanySupremist** [comment]
Having Fortune on a hoe allowed me to get seeds from harvesting Magebloom. I believe them not dropping seeds by default is normal for Ars Nouveau.
