### ISSUE TITLE
Eye of the Sky freezes game

### ISSUE THREAD

**Issue by duartelourenco** [FTBTeam/FTB-Modpack-Issues#5217]
### Modpack

FTB Skies

### Modpack version

1.5.1

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15299796/debug.log)

### Describe the bug

When I try to use the Eye of the Sky to find the Castle in the Sky, the game freezes.

### Steps to reproduce

Use the Eyes of the Sky

### Expected behaviour

The game not to freeze and the route to the castle to be shown.

**Comment by Saereth** [comment]
This can happen as it has to search a very large radius to find it. You just have to wait
