### ISSUE TITLE
FTB Builders Paradise 2 Little Tiles Crashes Game

### ISSUE THREAD

**Issue by SikeTeam** [FTBTeam/FTB-Modpack-Issues#5220]
### Modpack

FTB Builders Paradise

### Modpack version

1.1.0

### Describe the bug

I When To Place A Little Structure From Little Tiles Mod, I Crash.

### Steps to reproduce

Place Down Structure Builder,
Break Structure Builder, 
CRASH.

### Expected behaviour

Not Crash?

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can take a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
