### ISSUE TITLE
Molecular Transformer has no recipe.

### ISSUE THREAD

**Issue by SgtKrazy** [FTBTeam/FTB-Modpack-Issues#5221]
### Modpack

FTB Genesis

### Modpack version

1.5.0

### Describe the bug

As the title states. Molecular Transformer has no recipe. Cannot add screenshot as there is nothing that displays upon clicking on Molecular Transformer.

### Steps to reproduce

1. Search for Molecular Transformer
2. Click on Molecular Transformer in JEI (Even quest Book under Bootstarpped Tech)
3. No Recipe displayed.

### Expected behaviour

Display recipe for Molecular Tranformer

**Comment by Icysnowman** [comment]
I have the same issue, Found a video of someone playing the same pack and copied the recipy they used (2 Advanced circuits, 4 Advanced Machine Block, 2 Energy Crystal and a Mt Core) This also does not work (on a multiplayer server)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48984022/b1fe2d33-36d6-4a37-931c-2cec44dc3938)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/48984022/2b0c4e05-a165-416d-aeb2-e65928e7f3fb)

**Comment by ArtpokeBr** [comment]
Weird, this might be an issue with the most recent mod updates. I'll be adding the recipe back manually then
