### ISSUE TITLE
Iron spellbooks

### ISSUE THREAD

**Issue by BiggSlimm** [FTBTeam/FTB-Modpack-Issues#5224]
### Modpack

FTB Presents F.A.M

### Modpack version

1.1.1

### Describe the bug

The scroll forge and arance anvil do not work nor exist even they are required to progress

### Steps to reproduce

look up the arcane anvil in the jei menu

### Expected behaviour

I wanted the recipe for the scroll forge and arcane anvil

**Comment by Gaz492** [comment]
It's intentional that the items you mentioned are uncraftable as all the spells in Iron Spellbooks were changed to be loot that spawn as loot
