### ISSUE TITLE
How i can change the text in ftb schools

### ISSUE THREAD

**Issue by MVillabon** [FTBTeam/FTB-Modpack-Issues#5225]
### Modpack

FTB Academy 1.16

### Is your suggestion related to a problem? Please describe.

When editing texts and certain blocks on the map in FTB Academy 1.16, changes are made and translated into Spanish. However, upon exiting and re-entering the school, the changes are not saved, and everything reverts back to its original state from the beginning

**Comment by MichaelHillcox** [comment]
Looks like all our translations for the schools are contained here 

`kubejs/assets/ftbacademy/lang/en_us.json`

meaning you can likely add a new file for your locale and translate the rooms yourself
