### ISSUE TITLE
Task Screen not charging properly.

### ISSUE THREAD

**Issue by dcvinyou2day** [FTBTeam/FTB-Modpack-Issues#5227]
### Modpack

FTB Genesis

### Modpack version

1.5

### Describe the bug

On the Initiate reboot the prescribed method of charging the task screen no longer functions properly. You have to connect the wires as shown below to get them to charge.

Removing either set of connectors from the Task Screen will stop the charging.

### Steps to reproduce

See Screen Shots and follow the instructions in the quest to charge the task screen for the "Initial Reboot" quest.

### Expected behaviour

By following the image in the quest it should charge the task screen.

### Screenshots

This image shows the expected method not charging the block:
![2024-05-17_18 01 30](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/121339705/43d0aac8-30ea-4e2b-b4ea-c48c6ea7266c)
The second shows the only way I could get the task screen to charge. Any changes to the configuration stopped the charging.
![2024-05-17_18 06 39](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/121339705/cc443e4d-2bb1-4c5d-a36b-a62c284962d3)

**Comment by SgtKrazy** [comment]
If I remember right. The task screen only takes power on the back.  Remove the insulated wire from the back of the screen and then connect the immersive connector to the back.

**Comment by dcvinyou2day** [comment]
If you look in the initial screen shot there was no insulated wire on the back. It was not working. I had to put the insulated wire on the back to get it to work. If I remove the insulated wire it stops working. If I remove the copper wire it stops working. I now have to have both for it to work. It used to be the way you said but after the 1.5 update it now requires both.

**Comment by Br3ezey** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/170462667/67ac62e8-42fb-499e-8629-662e4b28eb69)
This is what is needed to be done. I managed to get it working

**Comment by ArtpokeBr** [comment]
This is basically the same thing reported here[https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5202](url) At the moment Electrodynamics has an Issue where Wires don't convert energy, only block faces do. So a Workaround is doing something like this.
![ed_converting_bug](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/44851727/d8e553f0-1941-448a-9115-de5547b2433e)

**Comment by ArtpokeBr** [comment]
I will close this issue tho as there's already one to be kept opened until I get a response from the ED devs :)
