### ISSUE TITLE
Shift+T boots you from the server in some cases

### ISSUE THREAD

**Issue by botanySupremist** [FTBTeam/FTB-Modpack-Issues#5229]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Describe the bug

Attempting to display items in chat by pressing Shift-T on those items, like those over 3000 stack count in a Dank Null or held Piglins from Easy Piglins with armor equipped, boots me from the server. It does not crash the game outright, and EDIT: it does not actually send your message, but boots you from the server on attempting to, so it only boots the player who attempts this. 

### Steps to reproduce

1. Press Shift+T to display an item with an unusually high stack count or a Piglin with armor equipped in your inventory.
2. Behold as the game shits itself.

### Expected behaviour

It should have displayed the aforementioned items in the chat without issue.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/160211017/f06ae104-8719-4b56-af96-69e837560188)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/160211017/4fd5f60f-05f9-43e9-ba75-633633bfabd9)

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack after the issue has happened so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
