### ISSUE TITLE
Wormhole vs remote storage actuator

### ISSUE THREAD

**Issue by Fatom20** [FTBTeam/FTB-Modpack-Issues#5230]
### Modpack

FTB Skies Expert

### Is your suggestion related to a problem? Please describe.

Why is the remote storage accessor locked behind a lot of machinery but the wormhole can be done before the moon? I feel like it does the same thing but when I want remote storage early game I have to place the wormhole down and break it.

### Mod suggestion

Equalize the difficulty of getting both items

**Comment by AlexDev-9000** [comment]
Just came here to check this out, why is the accessor much further behind than applied energistics, and so much further away than the wormhole ?

**Comment by Saereth** [comment]
For the same reason you're complaining about having to place down the wormhole, pure convenience.
