### ISSUE TITLE
No visible cube at the shape card in the Mod RFTools (Quarry)

### ISSUE THREAD

**Issue by Buggy1987** [FTBTeam/FTB-Modpack-Issues#5231]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

Hello, i have no visual effects at the shape card in the MOD RFTools Builder.
I can set DIM and Offset and so on but i dont see the visual effects at the right corner of the ui.

### Steps to reproduce

Simple right click in the sky and see the ui of the shape card

### Expected behaviour

I want to see the 3d cube

**Comment by Buggy1987** [comment]
I have already tested to update all the mods inclusive the McJtyLib to the newest version. No fix

**Comment by Gaz492** [comment]
It looks like the preview feature of the shape card has not been ported yet according to https://github.com/McJtyMods/RFTools/issues/2170

If you put the card into the builder and enable the Support/preview mod it should show the preview in the world for you.

**Comment by DinnerBeef** [comment]
This issue has been reported to the mod dev. The mod dev has said that this feature has not been ported to this version of minecraft yet. As such, this issue will now be closed.
