### ISSUE TITLE
Pedestal Recycler upgrade is almost entirely nonfunctional

### ISSUE THREAD

**Issue by botanySupremist** [FTBTeam/FTB-Modpack-Issues#5233]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Describe the bug

This is not necessarily a bug, but is still an issue.
The almost total lack of smelting recipes for armor/tools to nuggets in the pack, which the Recycler upgrade draws from to function, means it cannot do things like process gold armor into nuggets or iron tools into nuggets.
The upgrade itself is not broken- it still disenchants for Pedestal XP and there are a small few items (e.g. Golden Knife) that it can melt down for nuggets, but nothing that mobs drop.

### Steps to reproduce

1. Feed an enchanted armor piece into a Pedestal with the Recycler upgrade.
2. The enchant is removed as expected, but the armor piece cannot be recycled into nuggets.

### Expected behaviour

I feel as though the Recycler should be able to smelt items down into nuggets as expected.

### Additional information

Would reimplementing blasting-to-nugget recipes for gold/iron gear gated past metal catalysts fix this? It would probably require minor gating (zinc?) of the blast furnace but is the only solution I can think of that might fix this.

**Comment by Saereth** [comment]
while I appreciate the feedback and report this isnt something we'll likely go out of our way to implement for this pack at this time
