### ISSUE TITLE
Crashes by Start

### ISSUE THREAD

**Issue by xSabsi** [FTBTeam/FTB-Modpack-Issues#5236]
### Modpack

FTB Builders Paradise

### Modpack version

1.1.0

### Log Files

[hs_err_pid19224.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15381838/hs_err_pid19224.log)

### Describe the bug

Crashes when i try to Start the game

### Steps to reproduce

i klick on start and it is loading and then crashes without opening the game itself

### Expected behaviour

open the game

**Comment by Gaz492** [comment]
This may be caused by outdated graphics drivers, could you try updating your graphics drivers to see if this resolves the issue for you?
