### ISSUE TITLE
FPS Drops when entering/opening inventories

### ISSUE THREAD

**Issue by EnigmaConcept** [FTBTeam/FTB-Modpack-Issues#5237]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Describe the bug

Frame drops when entering inventory. 
AVG  60fps down to 14fps when entering inventory

### Steps to reproduce

Open Dimensional storage or crafting station, connected inventorys/ items within do not change framed drops

### Expected behaviour

no continues change of FPS

**Comment by Saereth** [comment]
new embedium has better batch rendering which should help with this in the next update
