### ISSUE TITLE
FTB Genesis Reinforced Pressure Tube missing crafting recipe

### ISSUE THREAD

**Issue by SgtKrazy** [FTBTeam/FTB-Modpack-Issues#5238]
### Modpack

FTB Genesis

### Modpack version

1.5.0

### Describe the bug

Cannot craft Pneumatic Craft reinforced pressure tube. There is no recipe for crafting.

### Steps to reproduce

1. Locate Reinforced Pressure tube (Red colored)
2. Look for recipe
3. No recipe found

### Expected behaviour

Craftable Reinforced Pressure Tube

### Screenshots

![2024-05-20_23 37 18](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/21181138/d401da04-e570-4ffc-b773-03641c103635)

**Comment by ArtpokeBr** [comment]
The Most Recent IC2c Update changed how the custom recipes are handled, but its already fixed in dev now :)
