### ISSUE TITLE
Energy meter on side of screen. 

### ISSUE THREAD

**Issue by Shortganon** [FTBTeam/FTB-Modpack-Issues#5241]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.9.0

### Describe the bug

This side menu displaying random things with % meters is just there. I have started a new game and server. To still see this. I'd like to know how to get rid of it.
![20240521_163101](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/170479329/bdf09893-af84-497c-91f7-a57807a7bb2b)

### Steps to reproduce

1. Open the game.
2. Play a world.

### Expected behaviour

.

### Screenshots

![20240521_163101](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/170479329/c845d961-a01e-406d-8284-8c3d1c77ee7c)
![20240521_163046](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/170479329/7fd29f51-f026-42eb-8a1e-7d17870bd6f1)

### Additional information

I've gone through controls and tried reinstalling the mod pack and nothing seems to work.

**Comment by Gaz492** [comment]
If you open your inventory, then click on the quest book in the top right to open the quests screen.
Try clicking on the Pin icon in the bottom right, this should remove that list for you.
