### ISSUE TITLE
rod of the terra firma doesn't work

### ISSUE THREAD

**Issue by charllot1** [FTBTeam/FTB-Modpack-Issues#5242]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

botania mod's rod of the terra firma doesn't work at all
with full mana tablet(mirror)

### Steps to reproduce

1. get rod of the terra firma and full mana tablet(mirror)
2. hold right click
3. nothing happens

### Expected behaviour

break the stones

**Comment by UnRealDinnerbone** [comment]
This issue was fixed in a newer version of Botania and does not seem like they are backporting fixes at this time
