### ISSUE TITLE
server crash when i join 

### ISSUE THREAD

**Issue by Getclxped** [FTBTeam/FTB-Modpack-Issues#5246]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Log Files

https://aternos.org/files/crash-reports/crash-2024-05-24_08.08.46-server.txt#L5

### Describe the bug

When i start my sserver and i join it it crash and when i go see the log it says this (The entity 'ironfurnaces:netherite_furnace' at the location 6, 0, -13 is causing issues while ticking.) and i dont know how to solve this
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/95150970/bad8e7aa-e048-4c0f-9e6d-7d93d6399807)

### Steps to reproduce

start a world place a netherite furnace and it crash

### Expected behaviour

my server would work again

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/95150970/793ae707-20b4-4983-aa27-d09dbb8f89ce)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/95150970/bad8e7aa-e048-4c0f-9e6d-7d93d6399807)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/95150970/9f089591-d4e7-4745-80b2-cc60109cd42b)

### Additional information

i place the furnace and it crash

**Comment by Gaz492** [comment]
If you go to the world folder on the server and open the serverconfig folder there should be a file named forge-server.toml, if you open this file you can find a setting named removeErroringBlockEntities, setting this to true should fix your issue.
You may also need to set removeErroringEntities to true as well.
