### ISSUE TITLE
Broken ingredients in recipes

### ISSUE THREAD

**Issue by Blocksnmore** [FTBTeam/FTB-Modpack-Issues#5249]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

I've found a couple of items where the recipes are broken
- Platinum Jetpack
- Desh Plates
- Steel Plates

### Steps to reproduce

Look up desh plates in jei and look at the create recipe
Loop up platinum jetpacks in jei 
Look up steel plates in jei and look at the create recipe

### Expected behaviour

These recipes work

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/51055767/6a7f97e3-8dbd-4b28-9ab2-05e595052a36)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/51055767/0ab517d8-8029-4527-8d28-99035fe3b87a)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/51055767/5a1325f3-4956-4133-8d3a-8f90203f63b1)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/51055767/97387d17-00fd-49f3-ade3-c8c689e265cd)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/51055767/b6e53f1f-fbdc-44a5-8bec-bb4d41ff53b9)

Edit: Added steel plates

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you?

**Comment by Blocksnmore** [comment]
> Can you please let me know if this issue is still happening for you?

All of the recipes other than the platinum jetpack are fixed but given that emerald jetpacks can now be made with diamond ones I don't think that's an issue
