### ISSUE TITLE
Wood is indestructible

### ISSUE THREAD

**Issue by WattieBoi** [FTBTeam/FTB-Modpack-Issues#5250]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Describe the bug

i made a new word, all the wood is indestructible even if i grow a sapling
![image_2024-05-25_100023808](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/170775808/1e461bc4-fff1-4ea2-9188-702e3edab8b4)

### Steps to reproduce

open a new word and go on any island. all the wood will be indestructible 

### Expected behaviour

for the wood to be able to be mined XD

### Screenshots

![image_2024-05-25_100148603](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/170775808/7c1707d4-3aba-4681-9adc-d9c73aa3b034)
![image_2024-05-25_100503381](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/170775808/b493fde2-5218-4791-8b26-79594e364058)
![Screenshot 2024-05-25 100408](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/170775808/43a85719-6ba6-448e-9d7d-7c2d9d276a17)

**Comment by botanySupremist** [comment]
Have... you paid attention to the quests? You need tools in order to be able to break stuff. 

You can get started on that by shift right clicking dirt, if I remember correctly
