### ISSUE TITLE
Animals and objects suddenly gone

### ISSUE THREAD

**Issue by Decula-HH** [FTBTeam/FTB-Modpack-Issues#5251]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Log Files

Log 1+2
[2024-05-25-1.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15441969/2024-05-25-1.log.gz)
[2024-05-25-2.log.gz](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15441970/2024-05-25-2.log.gz)

### Describe the bug

Hallo (English below),
ich habe ganz normal gespielt > Bienen vermehrt > Honigwabe in Honig verwandlet > nebenbei in der Mobfarm paar Mobs gekillt > wieder zurück zu den Honigwaben. Nichts ungewöhnliches, wenn man Sinnvoll Wartezeit nutzt.
Plötzlich bin ich rausgeworfen worden vom Server/Minecraft und kam nicht wieder in das Spiel rein. Erst als ich das Spiel neugestartet habe ging dies.
Als ich mich einloggte war ich tot in der Mobfarm, wo ich aber nicht als letzes war. Alle Honigwaben, Honig und alle bis auf eine Biene waren weg.
Am meisten ärgert ich das mit den Bienen, die man nicht wieder herzaubern kann.
---
I played quite normal > Bees multiplied > Honeycomb in honey related > incidentally in the Mobfarm couple Mobs killt > back to the honeycomb. Nothing unusual if you use reasonable waiting time.
Suddenly I got kicked out of the server/Minecraft and didn't get back into the game. Only when I restarted the game did this go.
When I logged in, I was dead at the mobile farm, where I wasn't the last. All honeycombs, honey and all but one bee were gone.
The most annoying thing I have is the bees that can't be conjured up again.

### Steps to reproduce

Ohne die Ausgangssituation, die ich nicht mehr habe, geht dies nicht
---
Without the initial situation, which I no longer have, this is not possible.

### Expected behaviour

Ich hätte gern die Bienen zurück und im besten Fall eine Lösung wie sich dies verhindern lässt. // I would like to have the bees back and at best a solution how this can be prevented.

**Comment by Decula-HH** [comment]
I can see that at one point even blocks are missing.

https://blockshot.ch/q95B

**Comment by Gaz492** [comment]
Unfortunately the logs you posted dont seem to point towards what may have caused this issue to happen and the screenshot you posted has expired.
As for the bees you lost, I would either suggest spawning them back in (if you can) or restore the world to a backup just before this happened to you.
