### ISSUE TITLE
FTB Magic World 2 wont start since 2024.05.20.

### ISSUE THREAD

**Issue by Athonaar** [FTBTeam/FTB-Modpack-Issues#5252]
### Modpack

FTB Magic World 2

### Modpack version

1.1.2

### Log Files

[AUTH][INFO] Starting authentication flow finished successfully
[AUTH][INFO] Contacting Xbox Live started 
[AUTH][INFO] Contacting Xbox Live finished successfully
[AUTH][INFO] Authenticating with Xbox Services started 
[AUTH][INFO] Authenticating with Xbox Services finished successfully
[AUTH][INFO] Logging in with Xbox Live started 
[AUTH][INFO] Logging in with Xbox Live finished successfully
[AUTH][INFO] Getting Minecraft Profile started 
[AUTH][INFO] Verifying ownership started 
[AUTH][INFO] Getting Minecraft Profile finished successfully
[AUTH][INFO] Verifying ownership finished successfully
[FTB APP][INFO] Pre-Start Tasks
[FTB APP][INFO] Validate Java Runtime
[FTB APP][INFO] Validate assets
[FTB APP][INFO] Validate libraries
[FTB APP][INFO] Validate client

### Describe the bug

After launching it, about in 10 seconds it closes itself without an error message

### Steps to reproduce

1. Open FTB Magic World 2
2. Click on Play
3. Wait about 10 secs
4. Instance closes without error message

### Expected behaviour

launch my game

**Comment by zZVizualZz** [comment]
Having the same issue

**Comment by Gaz492** [comment]
May I ask what operating system you are running and if you are running the overwolf version of the app or the new standalone version?

**Comment by Athonaar** [comment]
win 10 pro 64 bit, java v 8 update 411, overwolf version of the app

**Comment by Athonaar** [comment]
sorry, not the overwolf version, i downloaded the new app from their website, i use that one

**Comment by Athonaar** [comment]
Yesterday installed the new update, had to duplicate the instance and copy my saves to the new one, but it works now.
