### ISSUE TITLE
Unable to run server on Creeperhost

### ISSUE THREAD

**Issue by TakenAngel3** [FTBTeam/FTB-Modpack-Issues#5253]
### Modpack

FTB One

### Modpack version

2.8.3

### Describe the bug

-- Block entity being ticked --

Name: mekanism:basic_fluid_tank // mekanism.common.tile.TileEntityFluidTank

Block: Block{mekanism:basic_fluid_tank}[active=false,fluid_logged=empty]

Block location: World: (-22,65,-293), Section: (at 10,1,11 in -2,4,-19; chunk contains blocks -32,-64,-304 to -17,319,-289), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)

Block: Block{mekanism:basic_fluid_tank}[active=false,fluid_logged=empty]

Block location: World: (-22,65,-293), Section: (at 10,1,11 in -2,4,-19; chunk contains blocks -32,-64,-304 to -17,319,-289), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)

### Steps to reproduce

1: Use creeper host
2: Attempt to log into the server that says its up and running
3: be unable to connect at all.

### Expected behaviour

being able to log into the server with minimal hiccups

### Additional information

I mean i thought id be able to purchase a server from the host service you advertise, then let my partner join from another country to play on it together, but its turned into a whole different issue as now its just not working even with getting help from the support over there. 
Ive had to delete the mod Embedium in order to run the server because it always fails. 
I really love this server pack, its just making it harder and harder.
Please help me out..

**Comment by WyFryMU** [comment]
Seems you have an issue with a Mekanism Basic Fluid Tank. You can see if adding this mod to the server will help get rid of it: https://www.curseforge.com/minecraft/mc-mods/neruina/files/5361912
Otherwise, you can try to spam `/setblock -22,65,-293 dirt` in console. Or you can edit the region file and remove the block which is a but more tedious.
Otherwise, you'll have to use a backup.
