### ISSUE TITLE
FTB Inferno recent update

### ISSUE THREAD

**Issue by Marethyu997** [FTBTeam/FTB-Modpack-Issues#5254]
### Modpack

FTB Inferno

### Modpack version

Any
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15445400/latest.log)

### Log Files

Here is the end of the log:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff68ab56fa, pid=21496, tid=6180
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [igdgmm64.dll+0x3556fa]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\maret\AppData\Local\.ftba\instances\ftb inferno\hs_err_pid21496.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed

### Describe the bug

Program encounters fatal error when attempting to load instance. 

### Steps to reproduce

1. Start instance of 1.10.0.
2. Wait.
3. Game crashes before it can reach main menu.

### Expected behaviour

I expected the program to run and function?

**Comment by Gaz492** [comment]
Is Inferno the only modpack that you are having this issue on or does a modpack such as Direwolf 20 or Stoneblock 3 also have the same issue?

**Comment by Marethyu997** [comment]
> Is Inferno the only modpack that you are having this issue on or does a modpack such as Direwolf 20 or Stoneblock 3 also have the same issue?

@Gaz492 While I don't have those specific modpacks, I do have FTB Skies and FTB Genesis, and both of those work fine.

**Comment by Gaz492** [comment]
> > Is Inferno the only modpack that you are having this issue on or does a modpack such as Direwolf 20 or Stoneblock 3 also have the same issue?
> 
> @Gaz492 While I don't have those specific modpacks, I do have FTB Skies and FTB Genesis, and both of those work fine.

Ok, if you go into the settings page on the app then click on the App  category in the sidebar, you should see 3 blue buttons on the page it loads, click on the one named Home.
This should open windows explorer to where the app stores the files it uses to run minecraft.
Open the bin folder up then rename the runtime folder to something like runtime-old and start the modpack up again?

**Comment by Marethyu997** [comment]
> > > Is Inferno the only modpack that you are having this issue on or does a modpack such as Direwolf 20 or Stoneblock 3 also have the same issue?
> > 
> > 
> > @Gaz492 While I don't have those specific modpacks, I do have FTB Skies and FTB Genesis, and both of those work fine.
> 
> Ok, if you go into the settings page on the app then click on the App category in the sidebar, you should see 3 blue buttons on the page it loads, click on the one named Home. This should open windows explorer to where the app stores the files it uses to run minecraft. Open the bin folder up then rename the runtime folder to something like runtime-old and start the modpack up again?

Nope. Still failed. The log is nearly a clone of the original, too.

**Comment by Marethyu997** [comment]
Still having the same issue. Anyone know what might be causing it?

**Comment by Gaz492** [comment]
Unfortunately, I'm not sure what else to suggest, the only information I can really find is that this may be caused by your graphics drivers as igdgmm64.dll belongs to Intel's graphics drivers.

I would suggest seeing if updating your graphics drivers resolves the issue for you.
