### ISSUE TITLE
Immersive Engineering - no chunks with Core Sample Drill deposits

### ISSUE THREAD

**Issue by ArcheRion720** [FTBTeam/FTB-Modpack-Issues#5256]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Describe the bug

World generation doesn't create chunk-based "mineral deposits" feature for immersive engineering that can be used with excavator. Core Sample Drill/Mineral Survey Tools or command /ie mineral get all yield "no minerals found".

### Steps to reproduce

1. Create world
2. Go to any chunk
3. Use mineral survey tool / core sample drill / command "ie mineral get"

### Expected behaviour

At least some chunks should have any kind of mineral deposits.

### Screenshots

Using Mineral Survey Tool:
![2024-05-26_20 42 59](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20780895/8cd0d0f1-6a89-418d-a3c5-949ddb272311)

Using Core Sample Drill:
![2024-05-26_20 45 04](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20780895/404d34e8-54dd-483f-ac69-989d2e5bdf55)

Using command:
![2024-05-26_20 46 28](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/20780895/65616364-5def-4547-bd0e-e1ae8adde071)

### Additional information

I find this weird that it doesn't work, considering there are other machines like IF laser drills.

**Comment by UnRealDinnerbone** [comment]
With this being an older pack. And this being kind of feature request. I don't think it is worth adding. And also having the risk of breaking old worlds.
