### ISSUE TITLE
Crashes when clicking on a crafting station

### ISSUE THREAD

**Issue by Gawain24** [FTBTeam/FTB-Modpack-Issues#5257]
### Modpack

FTB Skies

### Modpack version

1.19.2

### Describe the bug

whenever i click on a crafting station, it goes to a saving screen and then crashes

### Steps to reproduce

start up game, join world, click on a crafting station

### Expected behaviour

leads to a saving screen and then crashes

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can take a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by Gawain24** [comment]
I'll look when I get home, I think I ended up getting rid of the modpack
though
