### ISSUE TITLE
FTB Infinity Evolved 1.7.10 | Graphik Problems

### ISSUE THREAD

**Issue by ZabZuuubMarc** [FTBTeam/FTB-Modpack-Issues#5258]
### Modpack

Other...

### Modpack version

3.1.0

### Log Files

There is nothing to see in the Logs... :(

### Describe the bug

I'll added a youtube video cause i cant upload more then 10mb.

The problem is only 

### Steps to reproduce

1. Open FTB
2. Select FTB Infinity Evolved 3.1.0 
3. Start it
4. Select either Server oder Singleplayer World

### Expected behaviour

You cant see most of the Mobs, neither Creeper or Sheeps and when u press E you getting a dark screen

### Screenshots

https://www.youtube.com/watch?v=_NEZCDXwfOg

**Comment by Gaz492** [comment]
May I ask what your computer specs are (CPU and GPU)
