### ISSUE TITLE
Compact Machines aren't running when placed in force-loaded chunks

### ISSUE THREAD

**Issue by md5i** [FTBTeam/FTB-Modpack-Issues#5261]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Describe the bug

It seems as if compact machines that are placed in a chunk-loaded chunk (marked as force-loaded in the FTB claims manager), the chunk containing the machine space is not chunk loaded.  This is contrary to my memory of versions of this mod in the past, and is contrary to the descriptive test in the "Compact Machines" quest.

### Steps to reproduce

I created a small compact machine, placed it in a force-loaded chunk, and put some chickens in it.  If I look at a chicken's time to lay a new egg, note it, and then leave the machine, when I come back the time to lay an egg has not updated in my absence.  This was tested without leaving the chunk the machine was placed in during the test.

As a second test, I placed a furnace in the compact machine with a single cobble in it and a piece of tiny coal.  I then left the machine and stood on top of it for several minutes.  When I came back, the cobble had not yet finished cooking.

### Expected behaviour

The chunks inside compact machines should be force-loaded when the chunk the machine is in is loaded.

**Comment by botanySupremist** [comment]
Same situation. I had to force load the chunk inside of the compact machine when I shouldn't have had to...

**Comment by md5i** [comment]
This issue from Compact Machines seems to be relevant: https://github.com/CompactMods/CompactMachines/issues/563

**Comment by Saereth** [comment]
updated compact machines
