### ISSUE TITLE
Pneumaticcraft molten plastic stuff (+ recipe) is present

### ISSUE THREAD

**Issue by botanySupremist** [FTBTeam/FTB-Modpack-Issues#5263]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Describe the bug

Title. The recipe for Molten Plastic from Pneumaticcraft is present despite Molten Plastic not being usable for anything.

### Steps to reproduce

I really don't see why you would need to be able to reproduce this- the biodiesel and charcoal recipe from the Thermopneumatic Processing Plant is still present. You can check JEI and such.

### Expected behaviour

It shouldn't be present, seeing as Molten Plastic cannot be made into sheets from Pneumaticcraft in any scenario with said sheets being gone from the pack.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/160211017/5620951a-5502-4d57-b6fa-cabbfefeaeaa
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/160211017/eb7e3127-c2c9-48ad-8834-40c2ea0aab38) )

**Comment by Saereth** [comment]
removed for next update
