### ISSUE TITLE
Trying to run a gregtech wire through a compact machine bricks the world.

### ISSUE THREAD

**Issue by Duck318** [FTBTeam/FTB-Modpack-Issues#5264]
### Modpack

FTB Presents F.A.M

### Modpack version

2.12.1

### Describe the bug

I tried to connect some gregtech machines using wires through a compact machine tunnel. The world now crashes upon load every time.

### Steps to reproduce

1) Have a gregtech wire outside a compact machine
2) Put a tunnel inside the compact machine
3) Have that tunnel point to the wire
4) Place another wire next to the tunnel
Guaranteed crash and world crashes again instantly upon loading

### Expected behaviour

That the 2 wires would connect without any issues

**Comment by Duck318** [comment]
Fixed the crash by deleting the everything inside the micromachine using amulet. Still lost everything that was in there.

**Comment by Gaz492** [comment]
If you run into the issue again, you can follow the guide below to upload a crash report so we can take a look.
https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
