### ISSUE TITLE
Redstone Links from the Create Mod do not receive signals

### ISSUE THREAD

**Issue by Mikecom32** [FTBTeam/FTB-Modpack-Issues#5265]
### Modpack

FTB Skies

### Modpack version

1.5.1

### Describe the bug

When attempting to use the Redstone Link from the Create modpack, the receiver does not receive the redstone signal from the transmitter. Seems to be a reoccurrence of #3665, which was previously marked as fixed.

Screenshots below with the debug information from Create on the right side. Shows the transmitter is powered, but the receiver is not.

Based on the official FTB Discord, Skies Expert is/was also affected:
- [FTB Skies Expert 1.7.0 (2024-05-27)](https://discord.com/channels/372448486723158016/1208057038438006865/1244631416004939847)
- [FTB Skies Expert (2024-04-08)](https://discord.com/channels/372448486723158016/1208057038438006865/1234179760091955262)

### Steps to reproduce

1. Create two redstone links from Create
2. Place each link down, spacing them out at least a few blocks
3. Add one or more blocks to the frequency boxes on both links (both sides should match)
4. Sneak right-click on one transmitter to set it to receiving mode (you'll see the antenna gain a small dish)
5. Activate the transmitter side using a redstone torch, lever, or other means

### Expected behaviour

The receiving link should light up and send out a redstone signal

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/5023826/bfeeb6c4-b99e-4894-a380-ccb372cdb64b)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/5023826/acadb647-8792-4ec2-a03d-2f9140691f20)

**Comment by iaxx** [comment]
I successfully replicated the issue. Can confirm this is a real blocker to our progression.

**Comment by Gaz492** [comment]
I've not had success in replicating this issue, out of curiosity, does this happen if you create a new world?

![img](https://i.wuffs.dev/2024/06/javaw_2024-06-14_09-17-21.png)
