### ISSUE TITLE
All rotational speed controllers that were on before stop spinning after rejoining singleplayer world. 

### ISSUE THREAD

**Issue by Br3ndaNE** [FTBTeam/FTB-Modpack-Issues#5266]
### Modpack

Other...

### Modpack version

FTB skies expert 

### Describe the bug

All rotational speed controllers that were on before stop spinning after rejoining singleplayer world. 

### Steps to reproduce

1. Have all speed controllers running
2. Exit
3. rejoin
4.

### Expected behaviour

Speed controller keeps running

**Comment by Vanojx1** [comment]
Following this coase i think its related to my issue. When i login all my Advanced Generators stop rotating the shaft connected. A redstone pulse on the generator makes it work again.

**Comment by Gaz492** [comment]
Would you be able to take a screenshot or video of your set-up so we can try and replicate this?

**Comment by Vanojx1** [comment]
![2024-06-16_12 13 17](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/15717390/5bd3a118-7bba-4637-9091-901f2a2fbf11)

I've replicated the issue in a creative world. Place an Advanced diesel generator and fill it with Force-Infused Biodiesel. As expected the shaft start rotating. Logoff and Login then the shaft is not rotating anymore.
