### ISSUE TITLE
Server version crashes at startup

### ISSUE THREAD

**Issue by hubertwisniewski0** [FTBTeam/FTB-Modpack-Issues#5267]
### Modpack

FTB Genesis

### Modpack version

1.6.0

### Log Files

[crash-2024-05-30_18.48.15-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/15503202/crash-2024-05-30_18.48.15-fml.txt)

### Describe the bug

Server version (clean install) crashes right at startup. It looks like the mod "Neko's Enchanted Books" is a client-only mod and should not be present in the server version.

### Steps to reproduce

1. Install the server version `12039` using the `serverinstall` script from the FTB Genesis official page,
2. run `start.sh`.

### Expected behaviour

The server should boot successfully and load the world.

### Additional information

Removing the offending mod solves the issue.

**Comment by Gaz492** [comment]
This issue should be resolved now, let us know if you have any further issues!
