### ISSUE TITLE
Updated FTB OceanBlock, now unable to load

### ISSUE THREAD

**Issue by Xida00** [FTBTeam/FTB-Modpack-Issues#527]
### What Operating System

Windows 10

### App Version

202111101147-418dcf2f3b-release

### UI Version

418dcf2f3b

### Log Files

[crash-2021-12-07_13.59.45-client.txt](https://github.com/FTBTeam/FTB-App-Feedback/files/7668818/crash-2021-12-07_13.59.45-client.txt)

### Debug Code

FTB-DBGTEBIZIGOYE

### Describe the bug

Updated FTB OceanBlock, now unable to load

### Steps to reproduce

1. Updated game version
2. Tried to open
3. Loaded in world
4. Crashed

### Expected behaviour

Load into save 

### Screenshots

![Screenshot 2021-12-07 140203](https://user-images.githubusercontent.com/95475917/145043046-c4e46e61-3f82-47db-8616-4c7727592a41.png)

### Additional information

Hi, 

just tried to update to the latest version of ocean block and am now unable to load into the save world, any help on this would be appriciated. 

Thanks

**Comment by Raidobw2** [comment]
This was solved in #433. Updating to 1.11.0 will also solve this issue, let me know otherwise.
