### ISSUE TITLE
FTB Skies Expert-server issue

### ISSUE THREAD

**Issue by maciejo06** [FTBTeam/FTB-Modpack-Issues#5272]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Log Files

[latest.log](https://github.com/user-attachments/files/15515348/latest.log)

### Describe the bug

I can't run server 

### Steps to reproduce

I want to start server but when I start it always have same error

### Expected behaviour

I want to start play on server

**Comment by techn1fire** [comment]
Same issue here with the non-Expert FTB Skies pack 1.5.1 server

**Comment by WyFryMU** [comment]
Remove Neko's Enchanted Books mod from the server, it's a clientside mod that isn't meant to be on the server.

**Comment by Gaz492** [comment]
This issue should be resolved now, let us know if you continue to have issues!

**Comment by jentej** [comment]
> This issue should be resolved now, let us know if you continue to have issues!

I still have issues when using the premade pack on pebblehost. Don't know if this is a modpack issue still or maybe the hosting service im using. -> created an addional issue, #5295, since I overlooked this one
