### ISSUE TITLE
FTB Genesis 1.6.0 - Crash after interaction in Modular Storage

### ISSUE THREAD

**Issue by dokodCZ** [FTBTeam/FTB-Modpack-Issues#5273]
### Modpack

FTB Genesis

### Modpack version

1.6.0

### Log Files

[crash-2024-06-01_00.28.48-client.txt](https://github.com/user-attachments/files/15519322/crash-2024-06-01_00.28.48-client.txt)
[latest.log](https://github.com/user-attachments/files/15519323/latest.log)

### Describe the bug

Trying to sort or change view type in Modular Storage crashes the game everytime. 

### Steps to reproduce

1. FTB Genesis 1.6.0 (on my server)
2. Modular Storage with tier 4 storage card
3. Change view type or click "Sort by" button
4. crash

### Expected behaviour

no crash

**Comment by manmaed** [comment]
Seems like it has been fixed in rftoolsstorage-1.19-4.1.3
