### ISSUE TITLE
FTB One - Fresh Server Install - Private VPS 

### ISSUE THREAD

**Issue by MrRenegade** [FTBTeam/FTB-Modpack-Issues#5275]
### Modpack

FTB One

### Modpack version

2.8.3 / 2.8.2

### Log Files

The just of it is this: 

	Mod File: /home/grimtol/server/mods/embeddium-0.2.12+mc1.19.2.jar
	Failure message: Embeddium (embeddium) has failed to load correctly

https://pste.ch/olurinezeh.rb

### Describe the bug

Fresh install on a Debian 12 LXC Container running on Proxmox 8.2.2  

Host Hardware: 

![Screenshot_2024-06-01_22-49-54](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/40728380/6d5961ed-cdd0-40c7-b269-deb3bb3b9350)

LXC Container Summary,

![Screenshot_2024-06-01_22-50-57](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/40728380/9e07f13e-597c-4c6a-8c11-5963703615ef)

### Steps to reproduce

Version: 2.8.3
1. Download serverinstall_97_11460 from site.
2. scp it to server.
3. chmod 755 serverinstall_97_11460 and then run it.
4. Tell it yes to all the defaults.
5. ./start.sh  and tell it yes to the eula.
6. wait for crash. 

Version: 2.8.2
1. Download serverinstall_97_11444 from site.
2. scp it to server.
3. chmod 755 serverinstall_97_11444 and then run it.
4. Tell it yes to all the defaults.
5. ./start.sh  and tell it yes to the eula.
6. wait for crash. 

### Expected behaviour

The mod pack actually load and not fail.  

### Additional information

Test and the last version to Actually start is 2.8.1 for the Linux Server side (download serverinstall_97_11433) on a dedicated private VPS.

**Comment by WyFryMU** [comment]
Embeddium is a client side mod, so remove it from the server and you're probably good to go.

**Comment by MrRenegade** [comment]
Thank you for the update, I tested your suggestion and the server loads just fine now after removing that mod. 

But respectfully to the mod developers.  Remove the client side only mods from the server installers.  Server Admins are not going to have the latest up to date information on every client side only mod a developer puts into their pack.  So please make sure client side mods don't land in the server installers.  This is ultimately up to the responsibility of the mod pack developers.
