### ISSUE TITLE
Nether aluminum ore is directly smeltable to ingots

### ISSUE THREAD

**Issue by Saereth** [FTBTeam/FTB-Modpack-Issues#5276]
### Modpack

FTB Genesis

### Modpack version

1.6.0

### Describe the bug

You can directly smelt silk touched nether ore, it should not directly smelt to alumium, should process like the raw ore does. 

### Steps to reproduce

silk touch nether alumium ore, bypass progression

### Expected behaviour

Not directly smelt

**Comment by manmaed** [comment]
Still Issue in 1.6.1 So recipe issue?
