### ISSUE TITLE
Direwolf20 1.6.4 isn’t working because it crashes upon startup

### ISSUE THREAD

**Issue by Rubyspiral** [FTBTeam/FTB-Modpack-Issues#5277]
### Modpack

FTB Presents Direwolf20 - 1.6.4

### Modpack version

1.0.23

### Describe the bug

The game crashes on the mom and logo after a couple minutes 

### Steps to reproduce

Download the mod, start the game 

### Expected behaviour

The game starts

**Comment by Gaz492** [comment]
Would you be able to upload any logs from the modpack and/or the app so we can have a look at what the issue may be?
As the pack is rather old we may not be able to fix the issue.
