### ISSUE TITLE
Bug with mining for long periods of time.

### ISSUE THREAD

**Issue by ExtremeLotus125** [FTBTeam/FTB-Modpack-Issues#5278]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Describe the bug

After mining for a period of time, the game just stops letting me mine anything. I am unable to do anything except crafting till I close the application, and restart it. I do think it has to do with using hammers to mine the white arcane blocks in the overwolrd. It specifies using netherite to mine it, but it's minable with an iron hammer. after mining it the game doesn't necessarily crash. But it doesn't let me mine anymore.

### Steps to reproduce

1. Mine to bedrock level. 
2. find a white arcane rune block
3. mine with a hammer instead of normal pickaxe
4. wait about one minuet.

### Expected behaviour

Game acts like it's mining a block, but the block doesn't break and the graphics do not show.

### Additional information

This is not the first time I have had this issue with the modpack.

**Comment by Gaz492** [comment]
Could you try either updating the NoMoWanderer to 1.6.4 or disabling the NoMoWanderer mod and see if this issue continues to happen to you?
