### ISSUE TITLE
Couple Bugs With the Cotton Mod pack

### ISSUE THREAD

**Issue by Skylen64** [FTBTeam/FTB-Modpack-Issues#528]
### What Operating System

Windows 10

### UI Version

4bdfd15050

### Debug Code

FTB-DBGAVEMACUTAV

### Describe the bug

Fairly consistent player freeze when exiting the End by death or portal. And a smaller bug, a Gilded Netherite Pickaxe doesn't register as a pickaxe to any modded ore. 

### Steps to reproduce

1. Enter the End and either, die or use the portal to come back.
2. You get frozen in place where you spawn outside the End.

### Expected behaviour

Not to freeze when coming out of the End. And for the Gilded Netherite Pickaxe to be the pickaxe I know it can be.

### Additional information

Me and my Girlfriend were playing, and she has the mentioned Pickaxe. She found out she couldn't break Certus Quartz with it, it was as slow as using her hand. And she has Efficiency 5 on it. she soon found out that wasn't the only ore she couldn't break.  
As for the End issue, I died first, no problems with the respawn. We use a bed by the portal for that reason. She then dies, and gets frozen in place where she spawned. I was still able to move and play while this happened. She then restarts the game, everything works ok. I die, and get frozen in place at where we set spawn. She then exits the game, only the game didn't close for me. at all. I was frozen still in her game online, and it didn't kick me. We then both exit the portal, and both freeze in place. The same issue with it not kicking me happens again. During the time we are frozen, we can still break things, but it shows up in our inventory buggy as well. 
ps. Is there a way to make sure the gravestones don't burn away? I've lost all my items twice because of that now.

**Comment by manmaed** [comment]
This  issue is now stale
