### ISSUE TITLE
Lightning bolt keeps hitting the same spot AE2

### ISSUE THREAD

**Issue by Sekido123** [FTBTeam/FTB-Modpack-Issues#5281]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Pack has been modified

- [ ] Yes

### Describe the bug

Automated AE2 charged certus quartz...... charged quartz automated to drop in water with a block of quartz with pedistals. now for whatever reason i get a bolt of lightning in the 1 x 1 block of water in the same spot every .5 second. please i need help. tried making a new server with the same world and i still get a lightning bolt in that same spot. i removed the water and all quartz. also killed all entities around me. no help at all.

### Steps to reproduce

make an automated certus quartz farm like dire did. with pedestals and AE2. lightning stuck my pool to make quart block buds. and wont stop

### Expected behaviour

no lightning at all

### Screenshots

![436486143_1516681895860136_9000990287161579078_n](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97376914/9b64950d-8cf8-49d9-b148-a601dd56f3aa)

### Additional information

help me lol i cant play my server

**Comment by Sekido123** [comment]
been running for a couple days btw no issues, until now

**Comment by Gaz492** [comment]
Would you mind uploading your world so we can take a look?
