### ISSUE TITLE
Game crashing after loading into world

### ISSUE THREAD

**Issue by ApexisDev** [FTBTeam/FTB-Modpack-Issues#5282]
### Modpack

FTB Builders Paradise 2

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Log Files

Logfiles can be found here: https://pastebin.com/bvwJ5RsQ

### Describe the bug

After loading into the world and moving a couple of blocks the game shows the "Saving World" screen and crashes

### Steps to reproduce

1. Launch the Game
2. Join a World
3. Move several blocks or wait about 10 seconds
4. Game crashes

### Expected behaviour

Not crashing when loading into world and playing as intended

**Comment by Gaz492** [comment]
Just looking to clarify is this happening to you when creating a new world, loading an existing world or both?

Could you also try disabling the roughly enough items mod to see if that resolves your issue?
You can disable mods through the FTB App by clicking on the modpack/instance you want to disable the mod on then clicking on the mods tab below the play button.
