### ISSUE TITLE
Skyfactory 3 Randomly Crashes

### ISSUE THREAD

**Issue by ResistingGuide4** [FTBTeam/FTB-Modpack-Issues#5283]
### Modpack

Other...

### Modpack version

Skyfactory 3 version 3.0.22

### Pack has been modified

- [X] Yes

### Log Files

[crash-2024-06-05_15.27.52-client.txt](https://github.com/user-attachments/files/15595594/crash-2024-06-05_15.27.52-client.txt)
Crashes with the exit code of -1
Gives this response: The game crashed whilst unexpected error. Error: java.lang.NullPointerExeption: Unexpected error

### Describe the bug

Game crashes whenever I open my inventory. I had installed the mods OpenBlocks, Veinminer, and Forgiving Void

### Steps to reproduce

1. Install Skyfactory 3 on curseforge
2. Turn on "Allow content management" in the profile settings
3. Add Forgiving Void, Veinminer, and OpenBlocks
4. Load up the world I have attatched in the log files
5. Open your inventory

Note: It may not work immediately

### Expected behaviour

Game to not crash when I open up my inventory

### Screenshots

![Crash Screen](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150295925/4d613b72-4bb6-4d45-8fc4-f4c25ee6e7cb)

### Additional information

May take a while to happen

**Comment by ResistingGuide4** [comment]
Here is the world download: 
[Minecraft World.zip](https://github.com/user-attachments/files/15595794/Minecraft.World.zip)

**Comment by Gaz492** [comment]
It looks like the mod googlyeyes is the cause of the crash you are having, I would suggest disabling the mod to see if that fixes the issue you are having.
Disabling the mod shouldn't cause any further issues as it's only a client mod.

**Comment by ResistingGuide4** [comment]
Thanks, I will get back to it as soon as possible.

**Comment by ResistingGuide4** [comment]
It has seemed to work. Thank you so much!
