### ISSUE TITLE
i tried downloading modpacks from the app, but they all crashed on startup

### ISSUE THREAD

**Issue by Rubyspiral** [FTBTeam/FTB-Modpack-Issues#5284]
### Modpack

FTB Presents Skyfactory 3

### Modpack version

3.0.21

### Pack has been modified

- [ ] Yes

### Log Files

[log.txt](https://github.com/user-attachments/files/15650995/log.txt)

### Describe the bug

when i launch the game with a modpack it crashes

### Steps to reproduce

1. download any modpack
2. start the game through the ftb launcher

### Expected behaviour

The game starts and makes it to the title screen then loads a moddeed world

**Comment by Gaz492** [comment]
Is the log you uploaded the full fml-client-latest.log thats available in the logs folder?
https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

Do you also have a crash report?
