### ISSUE TITLE
Tiny Progression Stone Armor Crash

### ISSUE THREAD

**Issue by Liverioss** [FTBTeam/FTB-Modpack-Issues#5285]
### Modpack

FTB Presents Skyfactory 3

### Modpack version

latest

### Pack has been modified

- [X] Yes

### Log Files

[2024-06-06-5.log](https://github.com/user-attachments/files/15687172/2024-06-06-5.log)

### Describe the bug

i wear stone armor and the game crashes because tp is in v1.1.0

### Steps to reproduce

make stone armor, wear it, crash

### Expected behaviour

wear stone armor

### Additional information

i know this is an old mod but the server host i use only allows the latest version of the official mod pack and i cant modify so i would appreciate it if you fixed it

**Comment by Gaz492** [comment]
When the game crashed did it generate a crash report?
Unfortunately the log you uploaded doesnt seem to be very helpful as it just shows the server having stopped.
