### ISSUE TITLE
Nature's Compass mod missing?

### ISSUE THREAD

**Issue by WyFryMU** [FTBTeam/FTB-Modpack-Issues#5289]
### Modpack

FTB Skies

### Modpack version

1.5.1

### Pack has been modified

- [ ] Yes

### Describe the bug

It appears between version 1.5.0 and 1.5.1, the nature's compass mod was removed. This creates a quest bug in the Gadgets & Gizmos quest chapter (travel.snbt). Since the nature's compass quest is still in the config, but the mod is removed from 1.5.1, this makes completing the chapter impossible without using commands to force complete the hidden nature compass quest.

### Steps to reproduce

1. Download 1.5.0
2. Notice in the gadgets & gizmos chapter, there is a nature compass quest
3. Download 1.5.1
4. Notice the quest appears to be gone
5. Check the travel.snbt chapter file
6. Notice the quest is in the file still
7. Try to complete all the quests in the Gizmo chapter (one by one, not the entire chapter at once)
8. Notice the chapter is still blue since the hidden compass quest isnt completed
9. Run /ftbquests change_progress {username} complete 004D6A4E53793430
10. Notice the chapter is now green since the hidden quest is completed

### Expected behaviour

Either add the nature compass mod back since the changelog doesnt mention it being removed, or remove the nature compass quest.

**Comment by Gaz492** [comment]
I spoke with our pack developers and it looks like the natures compass quest should have been removed not hidden.
This will be fixed in a future update for the pack.
