### ISSUE TITLE
crash report (ftb anniversary) 

### ISSUE THREAD

**Issue by Steftast1c** [FTBTeam/FTB-Modpack-Issues#529]
### Modpack

ftb ultimate anniversary

### Modpack version

1.1.0

### Log Files

[crash-2022-01-01_18.19.23-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7798074/crash-2022-01-01_18.19.23-server.txt)
[crash-2022-01-01_18.23.46-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7798075/crash-2022-01-01_18.23.46-server.txt)

### Describe the bug

all i know is a player on my server moved one block to another place and it thus made things broken

### Steps to reproduce

dont know

### Expected behaviour

N/A

**Comment by Gaz492** [comment]
Restoring a world backup or going into the world > serverconfig folder and setting `removeErroringTileEntities` to true should resolve the issue for you, but you may also need to set `removeErroringEntities` to true as well.
