### ISSUE TITLE
Diamond Slivers cannot be compressed

### ISSUE THREAD

**Issue by OutsiderRyder** [FTBTeam/FTB-Modpack-Issues#5290]
### Modpack

FTB Genesis

### Modpack version

1.6.0

### Pack has been modified

- [ ] Yes

### Describe the bug

The Diamond Slivers item produced by the IC2 crop flower cannot be used in the compressor to create diamonds.

### Steps to reproduce

1. Attempt to create diamonds form diamond slivers.

### Expected behaviour

The craft cannot be completed

**Comment by Lusaca87** [comment]
as a temp fix i addet 

"type": "ic2:nbt" 


in "\kubejs\data\ic2\ic2_recipes\compressor\diamond_compression2.json" like "diamond_compression.json" on my server and client (only personal use) to make it work.
