### ISSUE TITLE
Unexpected Crashes // Potential severe Memory Leaks

### ISSUE THREAD

**Issue by Supermarcel10** [FTBTeam/FTB-Modpack-Issues#5293]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Pack has been modified

- [X] Yes

### Log Files

Logs provide no crash report. I've sent 5 or 6 logs in the Discord server, and as far as some moderators noted - they also didn't see anything out of the ordinary, and neither did I.

### Describe the bug

A severe issue with the server pack, where the server suddenly and unexpectedly crashes. Log files do not contain any stacktrace related to the crash. No error is thrown.

My containerisation detects the server process in a crashed state with exit code 137 and out of memory state of true. This to me signalises that there is a severe memory leak somewhere in the modpack.

I have tested the container with both 10GiB, 16GiB and 32GiB. I've experienced an unexpected crash within about 120 seconds of restarting, 2 players online with 16GiB dedicated - to me it seems almost obviously like a memory leak which managed to fill up the entire dedicated heap memory within seconds.

From my testing, it's not specific to any player count or time running. I've also had very iffy and weird behaviour with FTB Backups 2. I have disabled it for a few days, but it was not the cause of the issue.

My server is running pretty much the barebones server pack. The only things that are modified (accurate as of downloading 1.8.1 on 09/06/2024 and running a diff):
```diff
- Controlling-forge-1.19.2-10.0+7.jar
- extremesoundmuffler-3.39-forge-1.19.2.jar
- MouseTweaks-forge-mc1.19-2.23.jar
- oculus-flywheel-compat-1.19.2.-0.2.1.jar
- ReAuth-1.19-Forge-4.0.7.jar
- ToastControl-1.19.2-7.0.0.jar
- yeetusexperimentus-1.0.1-build.2+mc1.19.1.jar
+ LuckPerms-Forge-5.4.46.jar
+ melody_forge_1.0.1_MC_1.19.2.jar
+ Necronomicon-Forge-1.4.2.jar
+ worldedit-mod-7.2.12.jar
```

### Steps to reproduce

1. Run FTB Skies Expert Server 1.8.1
2. Wait an unknown amount of time for the server to crash.

### Expected behaviour

No crash occurs

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/47798787/d2cc74d2-c63a-4a68-a540-846f8334aae8)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/47798787/ce3930e4-6c41-45a5-b921-6b28ccb06926)

**Comment by Gaz492** [comment]
Does the crashes still happen if you remove/disable World Edit?

**Comment by Supermarcel10** [comment]
Sorry for the long lead up time. I have removed worldedit, and it seems to make no effect. I have increased the memory on the container to prevent crashes but that's not an ideal solution long term.
