### ISSUE TITLE
1.8.1 crashes when creating fresh install

### ISSUE THREAD

**Issue by jentej** [FTBTeam/FTB-Modpack-Issues#5295]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Pack has been modified

- [ ] Yes

### Log Files

[crash-2024-06-10_18.23.09-fml.txt](https://github.com/user-attachments/files/15777815/crash-2024-06-10_18.23.09-fml.txt)

### Describe the bug

A fresh install for the modpack crashes and server won't come up properly.

### Steps to reproduce

Get fresh server and load the premade pack of 1.8.1. Server will start booting but eventually stop booting and crash but not go ofline.

### Expected behaviour

Server should start

**Comment by Gaz492** [comment]
It looks like the mod entity_model_features_forge_1.19.2-2.0.2.jar is trying to load client only code on the server, if you disable that mod by either deleting it from the server or renaming it to add .disabled after the .jar your server should start up

**Comment by Gaz492** [comment]
Just another question, may I ask how you created the server?
I just checked our server installer, and it does not install that mod, so I'm a little confused on how that mod ended up in your server files.

**Comment by jentej** [comment]
I just hired a server from Pebblehost and tried booting up the pack using the premade modpack for FTB Skies Expert. According to their support it worked fine on the 1.8.0 version but the 1.8.1 version is not.

**Comment by Gaz492** [comment]
Ok, its possible this was an issue back when 1.8.1 was released which has since been fixed, and they may be using a copy of the files from back then

**Comment by jentej** [comment]
Server seems to work now.

Fresh install -> failed due to entity_model_features_forge_1.19.2-2.0.2.jar - crash-2024-06-11_12.25.01-fml.txt
Removed entity_model_features_forge_1.19.2-2.0.2.jar and rebooted server -> crashed due to entity_texture_features_forge_1.19.2-6.0.1.jar - crash-2024-06-11_12.29.31-fml.txt
Removed entity_texture_features_forge_1.19.2-6.0.1.jar and rebooted -> working as expected so far

**Comment by manmaed** [comment]
Hello i have just used the server install from the FTB website and it installs and runs with out crashing. so it maybe pebblehost has a cached version of the pack
