### ISSUE TITLE
quantum storage old bug

### ISSUE THREAD

**Issue by Gustop2001** [FTBTeam/FTB-Modpack-Issues#5298]
### Modpack

FTB Sky Adventures

### Modpack version

1.5.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Hi there, 

that bug had already been reported some 3 years ago, but I guess that the problem still had not been solved

quantum storage mod is not working....     when we put the block and right-click to open, the world shutdown

### Steps to reproduce

when we put the block and right-click to open, the world shutdown

### Expected behaviour

shut the down de world

**Comment by Gaz492** [comment]
Duplicate of #2861
