### ISSUE TITLE
Stacks of Items Get Deleted When Item is Placed

### ISSUE THREAD

**Issue by Zerifore** [FTBTeam/FTB-Modpack-Issues#5301]
### Modpack

FTB University 1.19

### Modpack version

1.4.2

### Pack has been modified

- [ ] Yes

### Describe the bug

Whenever I place an item, there is a change I get a message in chat that says "[item_name] not found in inventory" and then it proceeds to delete all of that item that I have within my inventory. Thought it might be a world thing but I started a new world and it is doing it still on that world. It began after I placed some basic schematics from the Tetra Mod, broke them to move them closer to my workbench, then replaced them, in which they "placed" seeing as though there was an outline of the schematic but it was invisible, then when I broke it again it didn't drop the item. That is when it started at least.

### Steps to reproduce

Not entirely sure

### Expected behaviour

Place a block and not have all blocks of that type in inventory be deleted

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/94021479/b3363aff-a4fb-4e48-a8fa-5173d8458595)

**Comment by Gaz492** [comment]
When/if this happens again would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
