### ISSUE TITLE
Electric Motor Stopping and  then Starting over

### ISSUE THREAD

**Issue by logfrog512** [FTBTeam/FTB-Modpack-Issues#5302]
### Modpack

FTB StoneBlock 3

### Modpack version

1.9.0

### Pack has been modified

- [ ] Yes

### Describe the bug

When the Electric Motor from the create mod pack does not have or than one power pipe connected to it it will studder, even if one power supple have more than enough FE/t.

### Steps to reproduce

Place Electric Motor next to power supply greater than required.
Observe studder.
Place more power supplies.

### Expected behaviour

I expect the motor to work with one power supply.

**Comment by Gaz492** [comment]
It looks like this is a known issue that has not been fixed yet.
https://github.com/mrh0/createaddition/issues/642

**Comment by UnRealDinnerbone** [comment]
The issue on the mod has been open since last year, since it seems like the mod is not going to get an update. I'm going to close this issue
