### ISSUE TITLE
Recipie Missing

### ISSUE THREAD

**Issue by Reninsane** [FTBTeam/FTB-Modpack-Issues#5304]
### Modpack

FTB NeoTech

### Modpack version

1.0.1

### Pack has been modified

- [ ] Yes

### Describe the bug

There seems to be no recipie for the Lignite Coal, the MI villager has it as a trade. I was instructed by TheOnlyTazz to send a report through github. 

Fankoo and LUVS Reninsane

### Steps to reproduce

villager trade

### Expected behaviour

There be Lignite coal to trade with

**Comment by Saereth** [comment]
We'll add a conversion from normal coal to lignite to facilitate the trade

**Comment by Reninsane** [comment]
yay awsum, FANKOO

**Comment by JackCopland** [comment]
Did this get added? I'm running NeoTech 1.7.0 and have the same issue still - The Villager offers a trade for lignite coal, but there doesn't seem to be a way to get it.
