### ISSUE TITLE
FTB 1.20 modpack crashing upon trying to Launch

### ISSUE THREAD

**Issue by Lassoloth** [FTBTeam/FTB-Modpack-Issues#5306]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Pack has been modified

- [ ] Yes

### Log Files

REMOVED

### Describe the bug

modpack crashes when trying to launch it

### Steps to reproduce

1. Download
2. Launch ("Play")
3. *Crash*

### Expected behaviour

launching modpack 

### Screenshots

![Screenshot 2024-06-14 160206](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/172856220/10d63672-07f7-41e1-83be-e1ea3cbd4d06)

### Additional information

I tried to re-download the modpack and also tried different versions; no success, same results.

**Comment by MichaelHillcox** [comment]
I've removed your segfault log. That log contains your Minecraft Authentication token! Do not share that file with anyone without first removing your access token.

**Comment by WyFryMU** [comment]
Update your AMD GPU Drivers

**Comment by Lassoloth** [comment]
> Update your AMD GPU Drivers

just updated my drivers, they were indeed out of date, however, that did not fix the problem

**Comment by Gaz492** [comment]
Ok, would you be able to try downgrading your graphics drivers?
From a search of the error you are having people have had luck with using driver version 22.5.1 or 22.4.1

**Comment by Lassoloth** [comment]
> Ok, would you be able to try downgrading your graphics drivers? From a search of the error you are having people have had luck with using driver version 22.5.1 or 22.4.1

This appears to have resolved the issue! It both opens and runs without any obvious problems
