### ISSUE TITLE
Server Watchdog crashing the server 

### ISSUE THREAD

**Issue by BigKusa-tm** [FTBTeam/FTB-Modpack-Issues#5308]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Pack has been modified

- [ ] Yes

### Log Files

[crashreport.txt](https://github.com/user-attachments/files/15846295/crashreport.txt)

### Describe the bug

I was flying really fast with the jetpack mod to explore and when I reach region (r.8.-3.mca) the Watchdog crashes the server for reasons I could not find.

I could not join the server afterwards as I keep spawning back in the crash region, but by deleting the my player UUID and spawning back to starting area works.

The starting point of the problem seems to be further back from the region (r.8.-3.mca) as whenever a player enters the area between region (r.4.-3.mca) and region (r.5.-3.mca) the Watchdog crashes the server as well.

I have identified the region where the crash would occur and have tried deleting the whole region and a few next to it for good measure but it doesn't seem to delete the region and just reverts back to its deafult state where the crash still occur.

### Steps to reproduce

1.  Go fly really fast to unexplored chunks
2. Watchdog seems to detect somthing and crashes the server

### Expected behaviour

N/A

**Comment by Gaz492** [comment]
Could you try disabling the nomowanderer mod and let me know if that resolves your issue?
It looks like you are running into a known issue caused by that mod.

**Comment by BigKusa-tm** [comment]
> Could you try disabling the nomowanderer mod and let me know if that resolves your issue? It looks like you are running into a known issue caused by that mod.

Disabling the "nomowanderer" mod has fixed the issue, I can go to the region without crashing anymore.

thank you for your help!!!

**Comment by Gaz492** [comment]
Great to hear and no problem, we will hopefully release an update to the pack that should fix this issue soon.
