### ISSUE TITLE
Daylight cycle and night shades

### ISSUE THREAD

**Issue by Draylynn** [FTBTeam/FTB-Modpack-Issues#5309]
### Modpack

FTB NeoTech

### Modpack version

1.0.1

### Pack has been modified

- [ ] Yes

### Describe the bug

The natural night cycle slowly changing to day; the sky remains dark, the surface layer remains dark.
Pressing F2 to take a screenshot will make the sky bright again, but the terrain, buildings etc will still be shaded dark as if it's night, even after placing and removing a light source like a torch.
Mobs seem to respect the fact daylight is upon them and stop spawning and start burning during day.
Sleeping will change night to day as expected.
Using /time set day, will reset the terrain/buildings to their proper light levels, as will reloading the save.

### Steps to reproduce

Start a game.
Allow a day cycle to complete naturally over time from night to day without any interference from commands/bed etc.
Behold the darkness of the day.

### Expected behaviour

Daylight cycle triggers daylight lighting in the overworld/sky.

### Screenshots

![ShaderDay](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/45239550/ad93e815-63c7-42b3-8208-d8458c9d0e66)

### Additional information

Multiple reports from MineTogether and FTB Discord users experiencing similar issues.

**Comment by Draylynn** [comment]
Disabling Bad Optimizations mod stops this behaviour occurring.

**Comment by Saereth** [comment]
Thanks for looking into this! The dev released a fix yesterday and we'll update today with it included.
