### ISSUE TITLE
[Bug]: XP Drain Singularity Tank doesnt drain xp, but still gives fluid

### ISSUE THREAD

**Issue by XorOwl** [FTBTeam/FTB-Modpack-Issues#531]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Describe the bug

XP Drain Singularity tank does not subtract experience, while making fluid

Figured this out after day 3(irl) of draining xp into vast storages while my level stayed the same.

Currently have 35972 xp points, at level 4015. If i had to take an educated guess, i'd say that the tank drain can't handle a number that big or something and dies in the subtraction phase? 

### Steps to reproduce

Step one, get an 8x condensed xp pearl and eat it. become overleveled.
step two, /xp query <player> points
step three, stand on 4 drains at once with the fluid going somewhere out of the way
step four, run the /xp query <player> points command repeatedly
watch as fluid comes out of you but you lose no xp.

### Expected behaviour

not getting infinite xp fluid

### Screenshots

![image](https://user-images.githubusercontent.com/20416354/147883755-cc20ffa4-b56a-472f-9a05-92b125c285eb.png)
![image](https://user-images.githubusercontent.com/20416354/147883775-9f569f8e-be07-47dc-9387-90b0ec0c8b60.png)
![image](https://user-images.githubusercontent.com/20416354/147883790-a415815c-615a-499d-b1ee-78197b3b3aed.png)

### Additional information

unlimited xp right as you no longer need unlimited xp, lol

**Comment by Flanks255** [comment]
Fixed in 0.4.32
