### ISSUE TITLE
Lunchbag voids food

### ISSUE THREAD

**Issue by bo-jensen** [FTBTeam/FTB-Modpack-Issues#5310]
### Modpack

FTB NeoTech

### Modpack version

1.0.1

### Pack has been modified

- [ ] Yes

### Describe the bug

Food added to the Lunchbag from Spice of Life Onion will be voided after closing the interface.

### Steps to reproduce

1. Open a Lunchbag using shift+right-click.
2. Add food into the interface (e.g. 20 apples)
3. Close the interface
4. Unable to eat from the item and re-opening the interface reveals it to be empty.

### Expected behaviour

Food will be stored in the Lunchbag

### Additional information

Seems to be this issue reported on the mod specific issue tracker: https://github.com/CreativeMD/Spice-of-Life-Onion/issues/19

Suggestion: Disable Lunchbag items untill mod has been updated with a fix.

**Comment by Saereth** [comment]
currenlty  a mod option we cant fix, we'll disable it for now until the mod updates to fix it
