### ISSUE TITLE
Add Chisel and Bits & Other decorative mods 

### ISSUE THREAD

**Issue by fbigummy** [FTBTeam/FTB-Modpack-Issues#5311]
### Modpack

FTB NeoTech

### Is your suggestion related to a problem? Please describe.

The lack of  different block types in the pack make it rather difficult to make cool builds that line up with the Tech
Also #blamerush 

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/chisels-bits

**Comment by Saereth** [comment]
sadly it causes a crash with the pack so we couldn't add it during testing.
