### ISSUE TITLE
2 Steam Boilers Quest takes to wrong recipe

### ISSUE THREAD

**Issue by Rushmead** [FTBTeam/FTB-Modpack-Issues#5315]
### Modpack

FTB NeoTech

### Modpack version

1.0.1

### Pack has been modified

- [ ] Yes

### Describe the bug

When clicking on the 2 steel boilers or 4 bronze boilers quest and then clicking on the steel boilers recipe it takes you to the FTB Smart Filter recipe instead of the steel boilers.

### Steps to reproduce

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/1780637/0221a9cc-d62b-4feb-9978-522f4f9c4504

### Expected behaviour

Should show steel boilers recipe

**Comment by Saereth** [comment]
Fixed in the next update, thanks for the report!
