### ISSUE TITLE
Etching tank crafting not working

### ISSUE THREAD

**Issue by Gumilho** [FTBTeam/FTB-Modpack-Issues#5318]
### Modpack

FTB NeoTech

### Modpack version

1.0.1

### Pack has been modified

- [ ] Yes

### Describe the bug

The Recipe for Etching Tank from PneumaticCraft: Repressurized seems to be missing

### Steps to reproduce

Place the correct ingredients (2 Obsidians, a Glass Pane, 2 Reinforced Brick Walls, 1 Small Fluid Tank, 3 Reinforced Brick Slab) in the crafting table or click the Fill Recipe button in the EMI interface.

### Expected behaviour

It was supposed to show the Etching Tank block in the result

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/19142565/cd779e14-32b5-454f-979b-57c1c6999e73)

### Additional information

I've tried crafting with glass pane and connecting glass pane.

**Comment by YuriValle** [comment]
Issue persists on version 1.1.0

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/7388126/c94fd1ac-3db7-470d-a910-aac460ee7c7c)

**Comment by Saereth** [comment]
the fixed version hasnt been released yet, we'll close the issue once the update is out

**Comment by A-Baji** [comment]
@Saereth I am still having the same issue on the latest version (1.3.0)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/61991709/23a6a0c3-4ea8-427c-a643-3279aec45247)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/61991709/95118a57-391a-467b-bd13-9d1eba73fc35)
