### ISSUE TITLE
Furnace doubles the output after enchanting with exporting.

### ISSUE THREAD

**Issue by mk10k** [FTBTeam/FTB-Modpack-Issues#5319]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Not sure if it was intended or not, but after enchanting vanilla furnace with exporting I get two items instead of one.
One output item stays in the furnace, the second one is exported. 

### Steps to reproduce

1. Use the anvil to enchant vanilla furnace with exporting Enchanted Book.
2. Place the furnace on the ground. 
3. Place chest next to the furnace.
4. Put the item inside, for example, one cobblestone.
5. You recieve two stones. One will be in the chest, the other in the output slot of the furnace.

### Expected behaviour

One stone, for one cobblestone, etc.

### Screenshots

![2024-06-17_13 01 32](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/173055502/b49dc8fb-29ad-4612-8572-ea210b3f7832)
![2024-06-17_13 01 41](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/173055502/cde35951-8141-41b8-bc2a-8e94f3744f7c)
![2024-06-17_13 01 45](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/173055502/9319c0fb-9ad5-4648-9ece-09406675b4c2)
![2024-06-17_13 01 48](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/173055502/f5382eb7-e3a3-49d4-b21f-7beb1d983531)
![2024-06-17_13 01 51](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/173055502/a0b440c1-7f40-40f6-bfc5-a3b63162b2a3)
![2024-06-17_13 01 58](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/173055502/30527166-42f7-4c43-b686-93168d7eadde)

### Additional information

update
It seems it only doubles the output if there is no other item of that type in the chest.  For example, if there is a stone in a chest, smelting one cobblestone will result in one stone. If there is no stone in the chest, smelting one cobble will result in two stones.

**Comment by Mrbysco** [comment]
Fixed in the next Enchantable Blocks version
