### ISSUE TITLE
[Bug]: Server Files don't work 1.13.0

### ISSUE THREAD

**Issue by Mini-kun** [FTBTeam/FTB-Modpack-Issues#532]
### Modpack

Direwolf20 1.16

### Modpack version

1.13.0

### Log Files

https://pastebin.com/Yk1HPZyP

### Describe the bug

I just use the installer for The server files 1.13.0

### Steps to reproduce

1. Download the Server files for 1.13.0
2. use the downloader to get all the server files
3. gets Error when booting the server

### Expected behaviour

The server boot.

### Screenshots

None as it's the server files

**Comment by Jake-E** [comment]
Would you be able to provide the server installer log? And also could you try the install again? It seems you are missing some files.

**Comment by Mini-kun** [comment]
So i just use the serverinstall_79_2108 and i don't get and installer logs

**Comment by Raidobw2** [comment]
Yes please use the server installer again or get XNet directly from CurseForge: https://www.curseforge.com/minecraft/mc-mods/xnet/files/3557001.
You're missing XNet to properly boot the server.

To get the installer log, run the serverinstaller inside a command prompt or terminal. At the end of the install sequence you'll see those lines:
![image](https://user-images.githubusercontent.com/17010632/147897470-59d19a2c-d6e8-43dc-b612-40e3273670e6.png)
Let us know if you get any failed files, and in that case check your internet, or download XNet manually.

**Comment by Mini-kun** [comment]
it has not Failed or Imcomplete

**Comment by Raidobw2** [comment]
I see thanks for the information. We'll investigate on our side concerning that, sorry about the inconvenience, I hope that you will enjoy the modpack!

**Comment by Mini-kun** [comment]
Hello Raidobw2 

So Once agian This Problem happy for the 1.13.1 aswell Just as a Head up

**Comment by Raidobw2** [comment]
@Mini-kun Can you send us the XNet mod file on the FTB Discord? We investigated yesterday about it again and we think the mod file is there but that it is corrupted. Please verify in your mods folder if the Xnet file is there (not XnetGases, just Xnet) and contact me on the FTB Discord directly with it in that case. Thanks!

**Comment by Mini-kun** [comment]
I have now Dm u :)

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue?
If you are, would you be able to upload new log files for us so we can take a further look?
