### ISSUE TITLE
Dupe glitch

### ISSUE THREAD

**Issue by jaerf1** [FTBTeam/FTB-Modpack-Issues#5322]
### Modpack

FTB NeoTech

### Modpack version

1.01

### Pack has been modified

- [ ] Yes

### Describe the bug

Furnaces enchanted with yeild 3 give 4 ingots from one dust using the forge hammer you can turn one ingot to 1 dust neting 3 ingots this can be repeated infinity with almost any matrial steel bronze others

### Steps to reproduce

1.Have furnace with yeild 3 placed
2. have forge hammer
3. crush one ingot of choice with forge hammer to get dust
4. put dust in yeild 3 furnace
5. get 4 ingots back
6. go back to step 3

### Expected behaviour

to get one ingot from dusts

**Comment by Saereth** [comment]
update to 1.1.0, this was fixed already
