### ISSUE TITLE
Error with Immersive Engineering Alloy Kiln bronze recipe

### ISSUE THREAD

**Issue by ningoroth** [FTBTeam/FTB-Modpack-Issues#5324]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

When I try to alloy copper and tin to get bronze, I get nothing. It's like the recipe doesn't even exist.

When I click on the Alloy Kiln to see possible recipes, I can find the bronze recipe, but only without the bronze ingot showing.

### Steps to reproduce

1. Put copper and tin in Alloy Kiln. (Can be dust or ingot)
2. Wait for it to melt.
3. Recieve no bronze ingot.

### Expected behaviour

I expected to get a bronze ingot

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/56553883/47634392-d2e9-4062-a838-ec5ef280674f)

**Comment by ningoroth** [comment]
I just restarted my game - now everything works.

**Comment by ningoroth** [comment]
It seems the recipe for bronze disappears sometimes when I load up the game.
It can be fixed by reopening the game, but do become tedious after some time.

**Comment by Saereth** [comment]
I havent been able to reproduce this on 2 different servers 
<img width="428" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/7b50c496-f771-49b7-897d-59866a133fbc">

next time this occurs please send your latest.log to us here so I can review it

**Comment by AStickyWicket** [comment]
@Saereth This issue happens with the hammers not fitting in the forge hammer as well. KubeJS for whatever reason breaks sometimes on loading. Restarting fixes the issue but its much simpler to do /reload  . This bug is hard to reproduce because its seemingly random but it has happened numerous times in the discord chat to different people

**Comment by truepurpledino** [comment]
Having this on 1.1.0 too, sometimes randomly, KubeJS breaks and reloading fixes it.

**Comment by Saereth** [comment]
1.2 is out now which should have this fix

**Comment by PlasmaPower** [comment]
I believe this issue is still occurring and is the same issue as #6546
