### ISSUE TITLE
Upgrade Core is not craftable

### ISSUE THREAD

**Issue by cauliflower69** [FTBTeam/FTB-Modpack-Issues#5325]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Trying to craft the upgrade core for Forcecraft and unfortunatley it doesnt work. 

### Steps to reproduce

1. Look up recipe
2. Try to craft
3. Doesnt work

### Expected behaviour

The recipe to work

**Comment by Saereth** [comment]
Looks like the recipe maybe didnt gen correctly in the mod, this used to take the rod and tome with xp in it to make upgrade cores now the recipe shows as
<img width="437" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/5d74a828-7633-4a86-aa68-a81c54633f7d">

<img width="818" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/075706f1-9a07-4e19-ae80-ff409f767f40">

so presently a cyclic craft, gonna pass this one onto mr bysco

**Comment by Mrbysco** [comment]
Fixed in the next ForceCraft version
