### ISSUE TITLE
Some languages are not rendered correctly

### ISSUE THREAD

**Issue by Gaz492** [FTBTeam/FTB-Modpack-Issues#5326]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Some languages are not rendered correctly, instead of rendering the correct characters they are rendered as squares/rectangles.

### Steps to reproduce

1. Start pack up
2. Click on the languages button
3. Scroll down to find broken language

### Expected behaviour

Languages are rendered correctly

### Screenshots

![img](https://i.wuffs.dev/2024/06/javaw_2024-06-18_12-53-00.png)

### Additional information

From a quick test, disabling Modern UI resolved the issue, but I'm not 100% sure if it is the true cause of the issue as in a test env with only modern ui installed I did not run into this issue.

**Comment by Gaz492** [comment]
Did more digging and found it to be a conflict/compatability issue between modern ui and emojiful

**Comment by erialsan** [comment]
The issue was also identified in Japanese.

**Comment by prts4144** [comment]
This issue was identified in Korean
