### ISSUE TITLE
[Server] Horse teleport (X) sync.

### ISSUE THREAD

**Issue by Draylynn** [FTBTeam/FTB-Modpack-Issues#5327]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

It appears when multiple people are on a server, with tamed ridable horses, when players logout/login etc, the call wheel changes and people start seeing other people's horses instead of their own. (Edit: I brain-farted my language hard, fixed for easier reading).
Additionally, if you call someone else's horse whilst they're riding it, you also kidnap them too.
Getting back on one of your own tamed horses seems to reset the wheel to show your horses... Until someone logs out/in, *dismounts/remounts.

### Steps to reproduce

Make a NeoTech server.
Invite friends (more the merrier).
Get horse, tame, saddle, ride around etc.
Monitor the wheel as players login and logout.

### Expected behaviour

Tame horse, only you can summon your horse.

**Comment by Saereth** [comment]
Confirmed this as well

**Comment by Draylynn** [comment]
Looks like it's not just logout/login, but also when people mount/dismount.

**Comment by Draylynn** [comment]
Any news on what build this fix will be included in? Does this require a world restart?
