### ISSUE TITLE
[Bug]: Industrial Foregoing Laser Drill recipes are missing

### ISSUE THREAD

**Issue by zediious** [FTBTeam/FTB-Modpack-Issues#533]
### Modpack

FTB Ultimate: Anniversary Edition

### Modpack version

1.1.0 - 1.2.0 - 1.3.0

### Log Files

Not relevant

### Describe the bug

It appears as though only a few (Glowstone, Niter, and Ancient Debris) ores are available to be gathered/mined with the Industrial Foregoing Laser Drill. Whether this was intentional or not I am unsure, however I believe that it is in error due to Emendatus Enigmatica not having their ores added to the drill.

### Steps to reproduce

1: Open JEI and search "Laser Drill"
2: Press the "U" key over a component of the IF Laser Drill
3: View limited recipes

### Expected behaviour

I would expect vanilla/modded ores to be available with the Laser Drill

### Screenshots

![image](https://user-images.githubusercontent.com/17010632/147899075-b50889bc-2357-4b33-92c0-b6c04a9956dc.png)

Above is a screenshot of the JEI recipe viewer for the Laser Drill.

**Comment by Shadowner83** [comment]
I can confirm this exact issue. Have the exact same recipes only for the Laser Drill.

**Comment by Drycatoh** [comment]
From the look of it, it's due to the mod called "Emendatus Enigmatica" replacing every ore in the world with its own aliases to make them drop "Chunks" instead of ores... Why does it exist in the first place :c
Now my laser drill is useless :(

**Comment by NeariX67** [comment]
Finally found it. It is unrelated to Industrial Foregoing and Emendatus Enigmatica.

The FTB Team implemented some KubeJS scripts that alter some recipes for good reason.

## Fix:
* Go to `kubejs\server_scripts` inside your server folder
* Edit `unify.js` using nano or visual studio code for example
* Comment out or remove line 594: `event.remove({output: /emendatusenigmatica:.+_ore/})`
