### ISSUE TITLE
sweet berries

### ISSUE THREAD

**Issue by LWmods** [FTBTeam/FTB-Modpack-Issues#5330]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

not a big deal but you cant plant sweet berries on primogel soil. possibly the other types too but i haven't made it that far yet.

### Steps to reproduce

try to plant one it wont place

### Expected behaviour

be able to plant them as they can be planted on vanilla farmland

### Screenshots

n/a

**Comment by Saereth** [comment]
They just dont support bushes presently, this would be a feature you'd have to request direwolf to add to his mod. You can ask over on his tracker @ https://github.com/Direwolf20-MC/JustDireThings/issues
