### ISSUE TITLE
Drill Buffs Attack Dmg and Attack Speed stack and remain permanently

### ISSUE THREAD

**Issue by francisciancu** [FTBTeam/FTB-Modpack-Issues#5333]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

When equipping/mining with the drill the stats for Attack dmg and Attack Speed stack and remain permanently
They reset if you exit.

### Steps to reproduce

1. Have a drill (check what attachments I'm using - if they matter)
2. Equip the drill / Mine or Attack with the drill
3. Check stats
4. Buff remains and stacks even if the drill is no longer equipped

### Expected behaviour

Buffs should not stack and should not be permanent

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/b89a9275-519b-42e3-b77e-35c9a7232cdd)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/49ca0e78-b988-46aa-896a-39b715e4e080)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/b090dcfc-772b-4099-afa2-4e9276837e2a)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/c9a17a0f-03e9-4a72-8ec9-49bf4f857439)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/31c06a3a-ce9c-469f-a95c-f065717f177c)

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/44d73433-b459-48d9-9e63-e34db21aa5e2)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/eed2c0de-f651-4491-9aaf-3eca3ecde6df)

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/905134aa-5b1d-439c-841f-6feb2921277f)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/f3ac5bd5-c1f6-4fa1-b812-5d3b355d9aa7)

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/7fc79dfb-9b31-4976-b456-72edfc861e4d)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/73709ecd-f111-44d2-b9d7-e89faf1de59b)

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/7e7614ab-68d2-4c92-a72d-b77b1ad295e6)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/63097299/28c4ca60-9527-4bd3-b119-aa94a9815b33)

### Additional information

Took all my gear off. I have just the Drill and it still happenes

**Comment by Saereth** [comment]
reported to AA as this is a mod issue not something we can fix with the pack directly
https://github.com/Ellpeck/ActuallyAdditions/issues/1407

**Comment by Flanks255** [comment]
fixed in 1.2.14+mc1.20.4
