### ISSUE TITLE
Lim. Layers don't drop

### ISSUE THREAD

**Issue by Chesswick** [FTBTeam/FTB-Modpack-Issues#5334]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Different from other blocks from "Just Another Chisel Mod" I tested, the block Lim. Layers doesnt drop when mined. Has also been observed in 1.0.1

### Steps to reproduce

1. Place the block Lim. Layers
2. Mine it with any tool (silk touch does not matter)

### Expected behaviour

The block should drop an one should be able to pick it up

**Comment by Saereth** [comment]
confirmed, i'll do a datapack override to fix this for next update
