### ISSUE TITLE
Yeta wrench or any wrench doesnt change ENDERIO redstone conduits connections

### ISSUE THREAD

**Issue by Paxination** [FTBTeam/FTB-Modpack-Issues#5337]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.13.1

### Pack has been modified

- [ ] Yes

### Describe the bug

I try to force a connection of a redstone conduit to a redstone activated spawner from Apotheosis or at all and it does nothing.Your supposed to be able to force connections.

### Steps to reproduce

1. Place a spawner
2. click it with a redstone comparator
3. place a redstone conduit
4. click the conduit with a yeta wrench or any wrench, nothing happens.

### Expected behaviour

The conduit should connect to the spawner if i hit it with a wrench.

### Screenshots

https://i.imgur.com/fI0YqP8.png

### Additional information

hitting a redstone conduit with a wrench does nothing unless its already connected to a block.

**Comment by DinnerBeef** [comment]
This is a known issue. https://github.com/Team-EnderIO/EnderIO/issues/533. For now, you can just a redstone dust on top/next to the spawner to control it
