### ISSUE TITLE
Dimensional tanks are duplicated when broken with JustDireThings tools. 

### ISSUE THREAD

**Issue by aaronhealey** [FTBTeam/FTB-Modpack-Issues#5341]
### Modpack

FTB NeoTech

### Modpack version

1.0.1

### Pack has been modified

- [ ] Yes

### Describe the bug

When using any of the JustDireThings tools, dimensional tanks are duplicated. This is not the case with normal tools such as the ActuallyAdditions paxel. 

### Steps to reproduce

Use JustDireThings tools to break dimensional tanks. 

### Expected behaviour

One item drops. 

### Screenshots

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/43383239/bc904bb0-0991-49ed-b697-d1cb8ca993b9

**Comment by Gaz492** [comment]
This is still happening on 1.1.0

**Comment by Saereth** [comment]
opened an issue with Direwolf on his tracker here:
https://github.com/Direwolf20-MC/JustDireThings/issues/68

**Comment by Saereth** [comment]
also opened an issue with dim storage dev now
https://github.com/Edivad99/DimStorage/issues/59
