### ISSUE TITLE
Wrong recipe in "2 steel boiler" quest in LV page

### ISSUE THREAD

**Issue by Nillaes** [FTBTeam/FTB-Modpack-Issues#5343]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Opening the recipe by clocking on the steel boiler in the quest gives the recipe for the wrong item (smart filter from FTB filter systems)

### Steps to reproduce

Go to steel boiler quest in the LV page
click on steel boiler to see the recipe
shows wrong recipe

### Expected behaviour

Show the recipe for steel boiler

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/23139870/3f1d80db-55eb-48e7-afe4-598b293bd87a)

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/23139870/607706fd-7da4-45c3-a1ab-331cd2377a8e)

**Comment by Gaz492** [comment]
Looks like this is a duplicate of #5315 which was marked as fixed, but it appears to still be an issue

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/840990/e601835b-a4d8-4747-b171-c43828e7c893

**Comment by Saereth** [comment]
fixed for real in next update :p
