### ISSUE TITLE
Missing Molten Plastic 

### ISSUE THREAD

**Issue by fbigummy** [FTBTeam/FTB-Modpack-Issues#5344]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

The Recipe for molten Plastic is missing meaning no Etching Acid

### Steps to reproduce

No recipe 

### Expected behaviour

Have Recipe

**Comment by RyanRio** [comment]
@Saereth Is this released in 1.6.0? I still see no etching acid recipe.
