### ISSUE TITLE
Tool Belt issues

### ISSUE THREAD

**Issue by bo-jensen** [FTBTeam/FTB-Modpack-Issues#5346]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Items inserted into Tool Belt (from Tool Belt mod) will disappear in some cases.

### Steps to reproduce

1. Equip a Tool Belt (mine is upgraded with 2 Belt Pouches) in the special Tool Belt slot (Shift-B)
2. Insert tools into all slots using the radial menu (hold R)
3. Save and Quit to title
4. Enter the world
5. With an empty hand, extract a tool from the belt using the radial menu
6. Put the tool back into the belt and close the menu
7. Open the radial menu again and the tool will be gone

### Expected behaviour

Tool belt should not act as a trash can :P

### Additional information

After a tool disappears, the belt works fine for the session. After re-logging, the belt again becomes a hungry mimic.

Also, in some cases, I have had the extracted tool be useless, i.e. the Steam Diamond Drill could not mine deep slate (had both water and coal). This can be fixed with a re-log.

I was also able to dublicate a tool in one case.

I'm not sure how I did the last two here.... insert and extract tools at random I guess

**Comment by Saereth** [comment]
opened an issue with the dev here:
https://github.com/gigaherz/ToolBelt/issues/145
