### ISSUE TITLE
Curios loose slot tag upon login

### ISSUE THREAD

**Issue by bo-jensen** [FTBTeam/FTB-Modpack-Issues#5347]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Equiped curios will loose the "Slot: <slot name>" tag and be unequiped during login.

I have not been able to replicate this 100%, but below is the most "successful" sequence I have found.

### Steps to reproduce

1. Equip a curio, e.g. Slime Amulet
2. Hold another curio in main hand
3. Save and Quit to Title
4. Re-enter world
5. Curios become unequipped and will either be in inventory (if there is room) or dropped on floor

### Expected behaviour

Curios should remember they are curios :D

**Comment by Saereth** [comment]
I couldn't reproduce this, does it happen all the time or just some times? Also is this in SP or on a server?

**Comment by bo-jensen** [comment]
SP and it does not happen all of the time, so there might be some other contributing factor. I'll re-open issue if I observe more info.

**Comment by bo-jensen** [comment]
I experienced this again in today in 1.3.0.

I have provided latest debug log and a screenshot :)

[debug.zip.zip](https://github.com/user-attachments/files/15972782/debug.zip.zip)

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/7656776/660007d2-b393-4f56-8159-bdfa2142f7e3)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/7656776/e2bb520b-0510-4760-ab0e-7b8572b82a1b)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/7656776/d2064cfd-1d18-4eba-9888-28eb78814cce)

**Comment by bo-jensen** [comment]
After reloading pack

[debug.zip.zip](https://github.com/user-attachments/files/15972914/debug.zip.zip)

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/7656776/03cd7519-ccd3-4ba0-bbd8-8a9b2374a2b0)

**Comment by Saereth** [comment]
ok looks like race condition breaking tags, probably impacting some other things as well. Added a mod which I hope will resolve it.
