### ISSUE TITLE
Server download always fails x number of downloads

### ISSUE THREAD

**Issue by Vort3xGameStudios** [FTBTeam/FTB-Modpack-Issues#5348]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Log Files

https://pastebin.com/DZ1Qfifk (errors only)
https://paste.feed-the-beast.com/view/445546f1 (Full log)

### Describe the bug

I am trying to download the server installer for NeoTech 1.1.0 (and all previous versions) and every time i do the install for the server installer the download always failed with x number of downloads failed. If you continue pass by accepting the errors the server will start and run, I just do not know if these failed downloads will affect gameplay (assuming it could) and if i were to manually download them, where to place them. This is for windows.

### Steps to reproduce

1. Download the server installer from https://www.feed-the-beast.com/modpacks/server-files 2. place in a folder 3. double click to run 4. press enter to install to current directory 5. press y to still install 6. press y to continue with 1.1.0 version 7. read how many downloads failed and choose y to continue or n to not. 

### Expected behaviour

You start the server installer and everything downloads and the final message is server installed successfully. You can delete this installer file now if you wish

**Comment by Gaz492** [comment]
It looks like the files that errored are just neoforge libraries and that it for some reason failed to validate that the file it downloaded was what it expected.

These files should be downloaded again if you press `y` to continue, as the neoforge installer will also attempt to download the files.

If the server starts up after letting it continue, then everything should be fine.
I would also suggest reporting this issue directly to the server installer repo https://github.com/CreeperHost/modpacksch-serverdownloader/issues

**Comment by Vort3xGameStudios** [comment]
Sounds good! Server seems to be performing fine for now.
