### ISSUE TITLE
Modern Indust Item pipe causes ticking entity crash with steves cart cargo manager

### ISSUE THREAD

**Issue by AStickyWicket** [FTBTeam/FTB-Modpack-Issues#5353]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Log Files

https://pastebin.com/Fbsuw0dc

### Describe the bug

If you have a item pipe connected to a cargo manager and its pulling from a side that is set to insert into a cart or extract from a cart but isn't filtered to anything specific (Like engine compartment, etc) then eventually it will cause a soft lock crash where you can't get back into your world

### Steps to reproduce

1. Add MI item pipe on any side of cargo manager and set to pull
2. Set cargo manager to default settings
3. Have steves cart dock into cargo manager

### Expected behaviour

Pull from cargo manager inventory

**Comment by Saereth** [comment]
opened an issue with the MI dev here:
https://github.com/AztechMC/Modern-Industrialization/issues/745

**Comment by Saereth** [comment]
issue referred over to steves carts now
https://github.com/CreeperHost/StevesCarts2/issues/39
