### ISSUE TITLE
Cooking for Blockheads crash

### ISSUE THREAD

**Issue by bo-jensen** [FTBTeam/FTB-Modpack-Issues#5355]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Log Files

[crash-2024-06-20_19.23.56-client.txt](https://github.com/user-attachments/files/15919488/crash-2024-06-20_19.23.56-client.txt)
[crash-2024-06-20_21.50.48-client.txt](https://github.com/user-attachments/files/15919489/crash-2024-06-20_21.50.48-client.txt)

### Describe the bug

Using the Cooking Table (Cooking for Blockheads) to que up recipes in the connected Oven will sometime crash the game.

### Steps to reproduce

1. Build a kitchen with a Cooking Table, Oven, and Kitchen Counter.
2. Store some Peanut (Pam's HarvestCraft 2 - Crops) in the Kitchen Counter
3. Access the Cooking Table
4. Double click on the recipe for Roasted Peanut to que it up

### Expected behaviour

Don't crash ¯\_(ツ)_/¯

### Additional information

This happened to me twice. One for salmon and one for peanuts.

Guessing it's likely a mod issue.

**Comment by Saereth** [comment]
opened an issue with the mod dev https://github.com/TwelveIterationMods/CookingForBlockheads/issues/712
