### ISSUE TITLE
Invisible buffs

### ISSUE THREAD

**Issue by bo-jensen** [FTBTeam/FTB-Modpack-Issues#5356]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Buffs are not visible

### Steps to reproduce

1. Aquire a buff
2. Buff icon is not visible

### Expected behaviour

Buff should be visible next to inventory.

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/7656776/0e6b44a2-be89-47ea-97cd-bd40955e6c46)

### Additional information

In the screenshot I have:

- Strength I (from Spice of Life diversity)
- Regeneration I (from Spice of Life diversity)
- Speed I (from Spice of Life diversity)
- Bad Omen I (from killing Illager Captain)
- Jump Boost II (from Slime Amulet)

**Comment by Saereth** [comment]
Buffs dont show in the inventory in this pack they show in the upper left
<img width="1303" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/a09e1e09-1094-490c-aa59-209037402173">

You can edit this behavior in the stylish effects mod config
