### ISSUE TITLE
Ethanol can not be submitted as a quest

### ISSUE THREAD

**Issue by cauliflower69** [FTBTeam/FTB-Modpack-Issues#5358]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Cant submit the 1 B of Ethanol in Chapter 4.

### Steps to reproduce

1. Grab an Ethanol bucket
2. Go to the quest
3. Try and submit it

### Expected behaviour

For the quest to work 

### Screenshots

https://imgur.com/a/eP3ZHAf

**Comment by Saereth** [comment]
this must be piped into a task screen, I've updated the quest to clarify
<img width="506" alt="image" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/9200909/08eaac73-ae5f-4afd-99e3-028dfa6d352d">
