### ISSUE TITLE
JustDireThings Quest "Observe Shadowpulse Soil" points to wrong block.

### ISSUE THREAD

**Issue by xplinkoo** [FTBTeam/FTB-Modpack-Issues#5359]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

The Voidshimmer quest and Shadowpulse quest in the "Dire Technologies" tree are pointing to the same block, preventing Voidshimmer quest from completing.

### Steps to reproduce

1. Observe VoidShimmer Soil
2. Look in Quest Book to see the ShadowPulse Soil quest has been completed instead
3. Go into quest editing mode and notice the "Observe" rule is set to "goosoil_tier3" in both quests

### Expected behaviour

"Observe ShadowPulse Soil" should point to "justdirethings:goosoil_tier4"

### Screenshots

https://imgur.com/a/ETK9msk

**Comment by Saereth** [comment]
thanks for the report, this should be fixed in today's update
