### ISSUE TITLE
[Bug]: Wither death sounds plays across whole server

### ISSUE THREAD

**Issue by rmccarthy1504** [FTBTeam/FTB-Modpack-Issues#536]
### Modpack

FTB Ultimate Anniversary

### Modpack version

1.1.0

### Describe the bug

Player spawns wither
Kills wither
Death sound plays for all players.

### Steps to reproduce

Player spawns wither
Kills wither
Death sound plays for all players.

### Expected behaviour

Death sound should only play for nearby players

**Comment by zediious** [comment]
This mod is a great candidate for this. It unfortunately only works if the client has it installed, so needs to be in the modpack.

[https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded](https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded)

**Comment by Raidobw2** [comment]
Fixed by adding the mentioned mod above in the 1.3.0 update.
