### ISSUE TITLE
Typo in the "Primal Coal" quest

### ISSUE THREAD

**Issue by truepurpledino** [FTBTeam/FTB-Modpack-Issues#5361]
### Modpack

FTB NeoTech

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

The first instance of "charcoal" in the quest description is misspelled as "charocla" in the quest "Primal Coal" in the "Dire Technologies" quest category.

### Steps to reproduce

Open quest and read description.

### Expected behaviour

Correct spelling

**Comment by Saereth** [comment]
ty for the reports!
