### ISSUE TITLE
recipes switch of copper and gold in Enriching factory

### ISSUE THREAD

**Issue by The-JPK** [FTBTeam/FTB-Modpack-Issues#5363]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.13.1

### Pack has been modified

- [ ] Yes

### Describe the bug

The recipes for Copper and Gold Dust for the Enriching factory machine from Mekanism are swapped

### Steps to reproduce

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/81431676/bea9fef0-b49e-4dbf-ae6a-2b7f36c99d79)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/81431676/2b9a9e92-0097-4aec-bc22-0a903c410d67)

### Expected behaviour

Picture of the recipes

**Comment by Kaeldehta** [comment]
Same as my issue #5345

**Comment by Gaz492** [comment]
Closing as this is a duplicate
