### ISSUE TITLE
Upgraded Coke Oven seems like miss charcoal recipe

### ISSUE THREAD

**Issue by Apolomir** [FTBTeam/FTB-Modpack-Issues#5364]
### Modpack

FTB NeoTech

### Modpack version

1.2.1

### Pack has been modified

- [ ] Yes

### Describe the bug

Reopened https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5328

My coke oven setup:
1x Bronze item input hatch
1x Bronze item output hatch
1x Bronze fluid input hatch
1x Bronze fluid output hatch

Issues seems still present
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/60337783/93f5f674-e410-4330-848a-77fe4367f00a)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/60337783/6074d434-e8a7-431a-b2c2-476edff297fe)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/60337783/dbb6af97-29dc-4a0f-84ef-4fb17474c1cc)

### Steps to reproduce

1. Put logs in input hatch

### Expected behaviour

Logs should be processed to charcoal in upgraded coke oven

**Comment by Apolomir** [comment]
@Saereth Seems like issue is still present

**Comment by Saereth** [comment]
can you try this with a steel input hatch

**Comment by Apolomir** [comment]
> can you try this with a steel input hatch

@Saereth yea with steel input hatch it works. thanks! But this recipe is not even mentioned in EMI
