### ISSUE TITLE
Equivalent Exchange 4 transmutation table stops working

### ISSUE THREAD

**Issue by Juliuz316** [FTBTeam/FTB-Modpack-Issues#5366]
### Modpack

FTB NeoTech

### Modpack version

1.2.1

### Pack has been modified

- [ ] Yes

### Describe the bug

After learning a few EMC'able blocks, transmutation table and tablet cannot learn/unlearn new blocks, You can take all learnt items out for free

### Steps to reproduce

1. Create new world
2. Cheat in a transmutation tablet/table
3. Learn a few EMC'able blocks in the transmutation tablet/table
4. Close it and wait a bit
5. Try to learn a few more EMC'able blocks

Then it should not be possible to learn/unlearn blocks, items taken out will be free

### Expected behaviour

Transmutation tablet/table do not stop learning items

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/4627008/9ad3f4c2-17f5-4f88-9486-9c4287344f32)

**Comment by Saereth** [comment]
This should technically not even be possible XD can you please provide your latest.log and debug.log files from your /logs/ folder whenever you're able to reproduce this issue so that can further investigate? Ty

**Comment by Juliuz316** [comment]
Here You go

[debug.log](https://github.com/user-attachments/files/15937435/debug.log)
[latest.log](https://github.com/user-attachments/files/15937436/latest.log)

**Comment by Saereth** [comment]
I've opened an issue on the Equivalent exchange tracker and moved most of your comments over there, if you have anything more to add please let them know. Once its resolved on their end I'll get the update into the pack

https://github.com/FTBTeam/Equivalent-Exchange/issues/1

**Comment by Juliuz316** [comment]
Understood, thanks a lot
