### ISSUE TITLE
Crash when using campfire on a claimed chunk

### ISSUE THREAD

**Issue by wolfgangama111** [FTBTeam/FTB-Modpack-Issues#5367]
### Modpack

FTB Presents F.A.M

### Modpack version

1.2.0

### Pack has been modified

- [ ] Yes

### Log Files

[debug-1.log](https://github.com/user-attachments/files/15936105/debug-1.log)

### Describe the bug

Crash at the end of campfire when chunk is claimed

### Steps to reproduce

1. Claim chunk with map
2. use campfire to cook salmon slice

### Expected behaviour

do not crash

**Comment by Gaz492** [comment]
If there's a crash report in the crash-reports folder, would you be able to upload that so we can take a look at it?
https://docs.feed-the-beast.com/docs/app/Instances/instance-logs#locating-crashlogs

**Comment by wolfgangama111** [comment]
[crash-2024-06-22_09.54.04-client.txt](https://github.com/user-attachments/files/15937405/crash-2024-06-22_09.54.04-client.txt)

**Comment by Gaz492** [comment]
Thanks, I've not been able to reproduce this using the steps you provided, are you able to reproduce this?
If you are, would you be able to screen record it?

**Comment by wolfgangama111** [comment]
We can close it, it didn't crash on a new test
