### ISSUE TITLE
[Suggestion]: Easier Dirt Singularity?

### ISSUE THREAD

**Issue by zoller27osu** [FTBTeam/FTB-Modpack-Issues#537]
### Modpack

FTB University 1.16

### Is your suggestion related to a problem? Please describe.

Like Cobblestone, Dirt is hard to automate in the quantities required by the Singularity. Alternatives like Grass, Coarse Dirt, Mycelium, Podzol, and even "Meadow Dirt" pollute the Void Mining pool for Dirt.

My ideas in order of preference:
1. Make the Compressium 1x Compressed Dirt recipe accept any block with the `forge:dirt` tag (i.e. `recipe.replaceInput({output: 'compressium:dirt_1'}, 'minecraft:dirt', '#forge:dirt')`)? This would allow unification of `forge:dirt` blocks into normal Dirt much like Logs -> Oak Logs currently work via the Prefab "Timber" recipe given the setup in the screenshots below. (If you do this, giving the same treatment to `forge:cobblestone` would also be nice. If you also swapped the Void Miner weights of Stone and Cobblestone (since mass Cobblestone->Stone is easy with the Instant Furnace anyways), you could possibly remove the Cobblestone Singularity -> Compressed Cobblestone recipe?)
  - btw, a general way to unify from tags to default like this without using crazy workarounds would be nice. The Oredictionificator is restricted to converting only the tags specified under config/Mekanism/general.toml ([general.oredictionificator]), and the Storage Drawers' "Conversion Upgrade" [hasn't worked for a long time.](https://github.com/jaquadro/StorageDrawers/issues/913). But neither are really appropriate as they could be abused to, for example, mass produce Grass or Mycelium blocks.
2. Make a Dirt Singularity craftable into a higher compressed dirt, like you did with the Cobblestone singularity. (I personally feel that this might be a bit too far, since unlike Cobblestone, you can't build a vanilla Dirt generator.)

![2022-01-03_19 27 26](https://user-images.githubusercontent.com/12834978/148006390-09062254-4047-4d5c-994d-ee60222b40ca.png)
![2022-01-03_19 27 19](https://user-images.githubusercontent.com/12834978/148006396-d011629d-4dfb-4e9c-a7c1-d703e8cbc515.png)

**Comment by aaronhowser1** [comment]
Changed to need 1x Compressed, made it craftable out of any `forge:dirt`

**Comment by Jinxy2004** [comment]
The dirt singularity still requires 2x compressed dirt.
