### ISSUE TITLE
Occultism Crash

### ISSUE THREAD

**Issue by 222stoney** [FTBTeam/FTB-Modpack-Issues#5372]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.13.1

### Pack has been modified

- [ ] Yes

### Describe the bug

The game crashes when you attempt to use the Occultism mod to summon a mob.

### Steps to reproduce

1. create a Aviar's Circle
2. Place raw gold, raw silver, raw copper, raw iron, and a Book of Binding: Foliot (bound)
3. wait for ritual to complete
4. Game Crashes

### Expected behaviour

The game not to crash and spawn a mob

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by 222stoney** [comment]
[crash-2024-06-22_21.08.49-server.txt](https://github.com/user-attachments/files/15950987/crash-2024-06-22_21.08.49-server.txt)

**Comment by 222stoney** [comment]
https://paste.feed-the-beast.com/view/a14325c0

**Comment by Gaz492** [comment]
It looks like the crash was caused by SmartBrainLib, if you are unable to get back into your world, you can try following the guide below and setting `removeErroringEntities` to `true`
https://docs.feed-the-beast.com/docs/support/Troubleshooting/ticking-entities#packs-running-forge-114-and-newer

**Comment by 222stoney** [comment]
Following the guide caused the crash to no longer occur when I attempt to use the occultism mod, but still, no mob spawns, and my resources are used up. Is there any way to fix that issue?
