### ISSUE TITLE
FTB Builders Paradise 2, Can't install resource packs

### ISSUE THREAD

**Issue by LMclarke1** [FTBTeam/FTB-Modpack-Issues#5374]
### Modpack

FTB Builders Paradise 2

### Modpack version

1.1.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Trying to install dyslexicEnhanced so I can read the game. But all resource packs are greyed out.

### Steps to reproduce

1 Open resource pack
2 Open resource pack folder
3 drag dyslexic Enhanced into folder
4 Verify pack is in list in minecraft but it's greyed out and unelectable.

### Expected behaviour

To let me use the resource pack

### Screenshots

<img width="861" alt="resourcebug" src="https://github.com/FTBTeam/FTB-Modpack-Issues/assets/142124745/f3659607-6d45-46bb-b25b-3b89a902e12f">

**Comment by Saereth** [comment]
Generally that means minecraft isnt recognizing that as a valid resource pack. If you can send me a link to the resource pack I'll try it out and see whats going on with it for you
