### ISSUE TITLE
String Chicken, not giving string.

### ISSUE THREAD

**Issue by Draylynn** [FTBTeam/FTB-Modpack-Issues#5375]
### Modpack

FTB NeoTech

### Modpack version

1.2.1

### Pack has been modified

- [ ] Yes

### Describe the bug

The string chicken does not produce string. It produces spider eyes.
I assume it's meant to give string, being called a 'string' chicken and being rewarded with string when you make a string chicken?

### Steps to reproduce

Make string chicken.
Crack string chicken egg.
Get spider eye.

### Expected behaviour

String chicken gives string resources.

**Comment by Saereth** [comment]
This is a mod issue as we arent changing its drops, I'll get an issue opened up on Creeperhost's tracker about this. Thanks for the report!

**Comment by Saereth** [comment]
https://github.com/CreeperHost/Chickens/issues/81
