### ISSUE TITLE
FTB Skies Expert Endless witch portal possible crash?

### ISSUE THREAD

**Issue by litelesslive** [FTBTeam/FTB-Modpack-Issues#5379]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Pack has been modified

- [ ] Yes

### Log Files

[crash-2024-06-24_11.32.27-client.txt](https://github.com/user-attachments/files/15953055/crash-2024-06-24_11.32.27-client.txt)
[latest.log](https://github.com/user-attachments/files/15953057/latest.log)
[debug.log](https://github.com/user-attachments/files/15953058/debug.log)
[client.log](https://github.com/user-attachments/files/15953060/client.log)
[server.log](https://github.com/user-attachments/files/15953061/server.log)

### Describe the bug

I was doing the Endless Witch Portal; at wave 4, it spawned three witches, and at the same time, all 3 of them threw instant damage potion. I guess I died, and they died simultaneously, and the game crashed.

### Steps to reproduce

1. Start the endless witch portal event.
2. Die at the same time as all witches?
3. Crash?

### Expected behaviour

Not crash?

**Comment by Saereth** [comment]
mod has been updated in the new version, should resolve this
