### ISSUE TITLE
Nether Portal duplication whenever entering the nether 

### ISSUE THREAD

**Issue by TysonNguyen619** [FTBTeam/FTB-Modpack-Issues#5381]
### Modpack

FTB Genesis

### Modpack version

1.7.10

### Pack has been modified

- [X] Yes

### Log Files

The latest log if it helps:
https://api.mclo.gs/1/raw/RGrGjda

### Describe the bug

Going into the nether through the nether portal causes a new portal to be created nearby and I would be coming out of that one instead. This seems to happen every time I enter the nether

### Steps to reproduce

1. Go to the nether from the nether simulation
2. Exit the nether
3. Go back in

### Expected behaviour

I expected to travel back and forth through the same nether portal

### Screenshots

![2024-06-25_00 15 30](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150374817/da81cc48-d9af-41de-90b1-ba6a34a41d98)
![2024-06-25_00 16 03](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/150374817/0f1366e5-13db-4a53-960c-fd613efdaef7)

### Additional information

I added Radium Reforged version 0.8.2

**Comment by Gaz492** [comment]
It looks like this may be an issue with Radium Reforged, does this happen if you remove that mod?

**Comment by TysonNguyen619** [comment]
Yeah it still persists, tbh kinda expected as its just a performance mod

**Comment by Saereth** [comment]
can you give me your world seed or a world download, I can't reproduce this

**Comment by TysonNguyen619** [comment]
Hey uh I kinda moved on from the modpack and pretty much deleted the instance like 1 week ago so there's no way for me to send you the world, would love to tho as its kinda weird
