### ISSUE TITLE
Raw Biodiesel recipe input amount typo

### ISSUE THREAD

**Issue by ganagal** [FTBTeam/FTB-Modpack-Issues#5382]
### Modpack

FTB NeoTech

### Modpack version

1.2.1

### Pack has been modified

- [ ] Yes

### Describe the bug

Raw biodiesel recipe for IE refinery and MI chemical reactor has a different input ratio (probably a typo)
MI recipe has an extra zero for plant oil amount

### Steps to reproduce

check raw biodiesel recipe in EMI

### Expected behaviour

both recipes should have the same ratio

### Screenshots

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/78359772/51a1262f-5ad8-473a-90fb-88fed9099335

**Comment by Saereth** [comment]
the Ie refinery isnt a typo, its a different process with different catalyst ingredients and different ratios. MI and PNC have identical ratios which is intended
