### ISSUE TITLE
FTB Client is 1.3.0 but FTB website server files still only show 1.2.1

### ISSUE THREAD

**Issue by gotgoat** [FTBTeam/FTB-Modpack-Issues#5384]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Pack has been modified

- [ ] Yes

### Log Files

![Screenshot from 2024-06-24 16-08-49](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/24626779/623ee660-56c4-41ac-9341-e0fd6c0db8c8)

### Describe the bug

Can't download server update for 1.3.0 off FTB website.  

https://www.feed-the-beast.com/modpacks/123-ftb-neotech?tab=versions

### Steps to reproduce

Goto FTB website for NeoTEch

### Expected behaviour

Need server files to match client update on ftb client.

**Comment by Gaz492** [comment]
If you go to https://www.feed-the-beast.com/modpacks/server-files and select your operating system, you should be able to find neotech with the latest version there.

I will poke someone to clear the cache of the website so that it also updates

**Comment by Gaz492** [comment]
The website should be updated now

**Comment by gotgoat** [comment]
Thanks Gaz, i'll bookmark the other link also for future.
