### ISSUE TITLE
Force Track Emitter Uncraftable

### ISSUE THREAD

**Issue by raysilverstone** [FTBTeam/FTB-Modpack-Issues#5385]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.12.1

### Pack has been modified

- [ ] Yes

### Describe the bug

The Railcraft Reborn Force Track Emitter can not be crafted because it uses Railcraft Reborn Ender Dust. It needs to be ore dictionaried with ender dust from AE2. Railcraft Reborn Ender dust is made in a Railcraft Reborn Crusher but the crusher outputs AE2 Ender Dust. 

### Steps to reproduce

Tried to craft Railcraft Ender Dust in crusher and got AE2 Ender Dust.

### Expected behaviour

Expected to be able to craft the item with any ender dust

**Comment by DinnerBeef** [comment]
This issue has been resolved in a newer version of the pack! Please reopen this issue if you are still having problems.
