### ISSUE TITLE
trouble with Equivalent Exchange 4

### ISSUE THREAD

**Issue by enderr100** [FTBTeam/FTB-Modpack-Issues#5386]
### Modpack

FTB NeoTech

### Modpack version

1.2.1

### Pack has been modified

- [ ] Yes

### Describe the bug

When I use transmutation table/tablet if i take items out it doesn't lower total emc and i doesn't allow to add more emc into it. If i leave the world it will work as expected for the next minute or so but returned very shortly.

### Steps to reproduce

It does it every time I join the world after a few minutes pass

### Expected behaviour

Emc should go down when i remove items and should allow me to put items in.

**Comment by Gaz492** [comment]
Duplicate of #5366
