### ISSUE TITLE
Ethanol Bucket

### ISSUE THREAD

**Issue by DerRoffelcopter** [FTBTeam/FTB-Modpack-Issues#5387]
### Modpack

FTB NeoTech

### Modpack version

1.2.1

### Pack has been modified

- [ ] Yes

### Describe the bug

Can't get the achievement of "1 B of Ethanol" in the quest book, i already made more then 1 Bucket of Ethanol

### Steps to reproduce

1. go to the quest book, 2. click on number 4. Thhis Tier Is Kinda Mid, 3. there is the quest with the ethanol

### Expected behaviour

I want the achievement so i can go on at the quest book

**Comment by cauliflower69** [comment]
Have you tried using a task screen and pumping it in?

**Comment by Saereth** [comment]
you need to use a task screen, we added text to the quest to clarify this
