### ISSUE TITLE
Auto jump

### ISSUE THREAD

**Issue by Gaz492** [FTBTeam/FTB-Modpack-Issues#5388]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Pack has been modified

- [ ] Yes

### Describe the bug

Turing auto-jump off in the controls settings does not work.

### Steps to reproduce

Turn off auto-jump in the settings, walk up to a regular block and watch you automatically jump up that block

### Expected behaviour

Not to auto jump up blocks with the setting truned off

**Comment by Saereth** [comment]
looks like this broke due to removing apothic stats and placebo, readding them
