### ISSUE TITLE
Immersive Engineering steel wire can not be crafted.

### ISSUE THREAD

**Issue by cauliflower69** [FTBTeam/FTB-Modpack-Issues#5389]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

There is no recipe for steel wire from Immersive Engineering. The metal press will not accept the wire mold and there is no other recipe.

### Steps to reproduce

1. Try and place the wire mold into the press
2. It will not accept it 

### Expected behaviour

The recipe to work

### Screenshots

https://imgur.com/a/ot6JSzX

**Comment by phit** [comment]
this seems to be still an issue on 1.4.2
