### ISSUE TITLE
[Suggestion]: Twilight Forest quest progression should be based on mob trophies. Not random drops.

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#539]
### Modpack

FTB University 1.16

### Is your suggestion related to a problem? Please describe.

Every single boss in the twilight forest is guaranteed to drop their trophy the first time you kill them, and quest progression should be based on these trophies instead of common drops. For example, the Ice Queen has three different bows that she drops, each with equal chance to drop. Despite having killed her several times, I still haven't gotten the Tri-Bow required to advance the quests.

![Trophy Drops](https://user-images.githubusercontent.com/77522101/148096095-5919dd50-384a-4602-b003-bba8a10a6712.png)

**Comment by aaronhowser1** [comment]
The TF quests have the least love out of all the chapters, so I think I'm going to overhaul it eventually. For now though, fixed.
