### ISSUE TITLE
Drill speed augment 2 does not improve speed

### ISSUE THREAD

**Issue by Gumilho** [FTBTeam/FTB-Modpack-Issues#5390]
### Modpack

FTB NeoTech

### Modpack version

1.2.1

### Has the pack been modified

No

### Describe the bug

The drill speed augment 2 from actually additions makes the drill slower compared to augment 1.

### Steps to reproduce

1. Make a Light blue drill from actually additions
2. Add speed augment 1
3. Mine a block
4. Change it into speed augment 2
5. Mine the same type of block

### Expected behaviour

Speed augment 2 should be faster than speed augment 1

### Screenshots

https://github.com/FTBTeam/FTB-Modpack-Issues/assets/19142565/73fda9ed-0ed7-4195-af61-cb46bee6f7b3

**Comment by bo-jensen** [comment]
You must have both speed 1 and 2 in the drill at the same time :)

**Comment by Gumilho** [comment]
Oh, i'm so sorry, i should've read the quest better. Since tier 2 is made with tier 1, i thought you wouldn't need both.
