### ISSUE TITLE
Digital Miner CTD

### ISSUE THREAD

**Issue by cauliflower69** [FTBTeam/FTB-Modpack-Issues#5391]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Log Files

https://mclo.gs/fJYlxAI

### Describe the bug

1. I was using the Digital Miner in the UnderGarden 
2. Using the Item Filter for FrostSteel Ore & Regalium Ore
3. Pressed Start on DM and CTD
4. I can confirm this is repeatable
5. It worked fine with Regalium ore

### Steps to reproduce

1. I was using the Digital Miner in the UnderGarden 
2. Using the Item Filter for FrostSteel Ore & Regalium Ore
3. Pressed Start on DM and CTD
4. I can confirm this is repeatable
5. It worked fine with Regalium ore

### Expected behaviour

No CTD

**Comment by Saereth** [comment]
this should be fixed now in 1.5.0
