### ISSUE TITLE
FTB Genesis Gateways to Eternity not dropping loot rewards and missing from JEI

### ISSUE THREAD

**Issue by kenshin13850** [FTBTeam/FTB-Modpack-Issues#5394]
### Modpack

FTB Genesis

### Modpack version

1.6.1

### Has the pack been modified

Yes

### Describe the bug

The first one is pretty straightforward... The Gateways to Eternity items are not directly searchable in JEI and doing the mod search for Gate does not return any items at all. However, the items can be found by looking up recipes indirectly, for instance by right-clicking and scrolling through ender pearl recipes.

The second is a bit more annoying. I haven't tested it with larger gateways, but using the "Small Ghast Gate Pearl" from Gateways To Eternity spawns a gate and ghasts as intended, but defeating the waves does not reward any items (nor the do the Ghasts drop anything beyond experience bottles). I have tried multiple times both in the simulation chamber and in the nether. I have also tried once with a spider gate in the overworld.

I am not super far into the main quest line and got my ghast tears for this from the recycler and was hoping to use Gateways to Eternity as a more sustainable stopgap for getting mob drops. It almost feels like the mobs don't have the correct loot tables? Maybe that gets "fixed" later in the main quest progression though?

The only modification I have made to the pack is the installation of ftb-ultimine-forge-1902.4.1-build.90.

### Steps to reproduce

1. Craft a Small Ghast Gate Pearl
2. Use it on the ground (in a room with sufficient space)
3. Kill all the resulting Ghasts
4. Get no loot

### Expected behaviour

The gateway is supposed to roll the loot tables for the mobs a specified number of times after each wave. You also get a substantial number of bonus rolls for completing the final wave.

**Comment by Saereth** [comment]
This is not a bug, this is part of the pack
