### ISSUE TITLE
modern ind

### ISSUE THREAD

**Issue by ncalley21** [FTBTeam/FTB-Modpack-Issues#5396]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

my open hand becomes a half working wrench like highlights the blocks but wont let you do anything and all my actual wrenches have stopped working completely 

### Steps to reproduce

i just logged into my world this moring and it was like this when i relog into my world it fixes it for about 10-20 seconds 

### Expected behaviour

i excpected to be able to piick up my fluid tank with my wrench and i was unable

**Comment by AStickyWicket** [comment]
kubeJS error, type /reload should fix it
