### ISSUE TITLE
FTB presents direwolf20 1.20 version 1.14.0

### ISSUE THREAD

**Issue by Paxination** [FTBTeam/FTB-Modpack-Issues#5398]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.14.0

### Has the pack been modified

No

### Describe the bug

cant connect to my server.  Issue with JAOPCA.  Server reports version 4.4.10.17.  Client also reports 4.4.10.17.  Tried copying JAOPCA from my client to my server and i still cant connect, says the 2 have different versions, but it shows the same version on my screen.

### Steps to reproduce

update server and client to 1.14.0
try to connect.  as far as i know only affects updated.  Havent tried a fresh install because i dont want to start over.

### Expected behaviour

work

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
