### ISSUE TITLE
[Bug]: Draconic Evolution grinder causing 'waiting for server' error with Flux Networks when killing hostile mobs

### ISSUE THREAD

**Issue by ariosos** [FTBTeam/FTB-Modpack-Issues#540]
### Modpack

FTB OceanBlock

### Modpack version

1.11

### Describe the bug

I have a setup as follows from this screenshot in a test world. DE grinder, plus flux point. When the grinder kills any hostile mob, the server crashes (I can still move around, but mobs don't move and say "Waiting for Server"). Placing an alternate power source (energy cube, for example) doesn't have this problem. The area is not chunk loaded, and the flux controller/storage are set to default settings.

### Steps to reproduce

1 - Place a draconic evolution grinder (and entrap the area so mobs can't escape).
2 - As a comparison, Place an energy cube next to the grinder to give it power and spawn a mob. The mob is killed as expected.
3 - Replace the energy cube with a flux point, and set up the flux network (controller/storage).
4 - Spawn a hostile mob and let the grinder kill it. (This bug seems intermittent, but it happens most of the time it seems)

### Expected behaviour

The mob should be killed.

### Screenshots

![image](https://user-images.githubusercontent.com/7917753/148150209-c86517f8-7792-4b08-8627-f4766fb9a468.png)
![image](https://user-images.githubusercontent.com/7917753/148151473-3ef4ea38-bce3-4952-a25c-d33eb517a5da.png)

### Additional information

Game is on hard difficulty.

**Comment by Raidobw2** [comment]
This might be related to #247. When you use anything else than Flux Networks, say a Tesseract for a few days, does the problem persist?
Or course you might need to reply later haha, thanks in advance!

**Comment by Raidobw2** [comment]
Hi, there was an update to Flux Networks.
Can you try with https://www.curseforge.com/minecraft/mc-mods/flux-networks/files/3601194 and report back here if that solved the issue for you?
Thanks

**Comment by ariosos** [comment]
The error is still occurring, although it's more 50/50 now.

**Comment by Raidobw2** [comment]
I see, thanks for the reply. Currently I'm having communications with the Flux Network author, they have been pushing updates to solve issues.
I'll need to load in-game to see if it's due to another mod, but from your original report it still looks like it's Flux Networks.

**Comment by TheonlyTazz** [comment]
I have tested this issue for over half an hour without crashing.
This is with the latest version of Fluxnetworks that got shipped with v1.12.0

**Comment by TheonlyTazz** [comment]
I have let the game run for half a day with a similar setup and have not encountered this issue at all
I assume this issue has been resolved with the latest Fluxnetworks and will close this issue.
If it does happen again, please open a new Issue
