### ISSUE TITLE
[Bug]: Graphic Error, when moving.

### ISSUE THREAD

**Issue by crusender** [FTBTeam/FTB-Modpack-Issues#5402]
### Mod

FTB NeoTech

### Mod version

FTB NeoTech 1.21

### Forge / Fabric version

1.20.4-20.4.237

### Modpack & version

FTB NeoTech 1.21

### What issue are you having?

It is a clean install, lastest version, dont add any mod. When I move (walk/run) I see those writing in front of me, it look like it follow my arm movement. When I sneak moving, it show all the time.

It look like a box, whit white text a the top and black number 256* at bottom.

![NeoTech bug](https://github.com/FTBTeam/FTB-Mods-Issues/assets/8825886/0e35161b-842c-40a4-871d-99a0d598a192)

### Steps to reproduce

If I know how to reproduce it, I will have a idea what cause that problem.

I check if was a bug whit skin, It is not. It look random, but it do happen sometime at specific spot and direction too.

**Comment by AStickyWicket** [comment]
Hi, apparently this visual bug is from modern industrialization barrels.

**Comment by crusender** [comment]
I confirm, it cause by modern industrialization barrel.

**Comment by Saereth** [comment]
This is an issue with the MI barrels and Embeddium, we just have to wait for a fix from one of them

**Comment by Saereth** [comment]
fixed with new embedium update
