### ISSUE TITLE
Steve's carts2 cart assembler not taking coal with automation

### ISSUE THREAD

**Issue by Sir2Medis** [FTBTeam/FTB-Modpack-Issues#5403]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

there is no way to automate coal into the cart assembler. not with a hopper nor with pipes.

### Steps to reproduce

try to pipe with anything into the cart assembler

### Expected behaviour

being able to pump items in.

**Comment by Saereth** [comment]
https://github.com/CreeperHost/StevesCarts2/issues/40
