### ISSUE TITLE
FTB Genesis No Mob Drops?

### ISSUE THREAD

**Issue by kenshin13850** [FTBTeam/FTB-Modpack-Issues#5405]
### Modpack

FTB Genesis

### Modpack version

1.6.1

### Has the pack been modified

Yes

### Describe the bug

I posted a [similar bug report](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5394) recently, but in that report I was looking specifically at Gateways to Eternity. **Is is just a "feature" of FTB Genesis rather than a bug?** I'm just surprised I haven't found more discussions about it.

Anyways, I It feels like most mobs do not drop from their loot tables - instead they drop Bottle o' Enchanting and (rarely) paper. Some of the quest lines make this feel intentional - like the fact ender pearls are gated behind nether progression in the quest book. But other areas feel clunky. Because of this, it is exasperatingly difficult to get certain mob drops as well as apotheosis gear and gems.

This is true for:

All Overworld Mobs (I've encountered)
- Spiders (both naturally spawned and from spawners)
- Zombies (both naturally spawned and from spawners)
- Skeletons (both naturally spawned and from spawners)
- Endermen
- Husks

Nether Mobs (I've encountered)
- Ghasts (both naturally spawned and from Ghast Gates from Gateways to Eternity)

Notable Exceptions
- Foxhounds
- Blazes (in the simulation chamber - have not killed in nether)
- Magma Cubes (in the simulation chamber - have not killed in nether)

If a mob is not listed, then I have not killed it yet (e.g. piglins, zombie piglins, etc.).

### Steps to reproduce

1. Kill a mob
2. Pick up the Bottle o' Enchanting it drops

### Expected behaviour

Get loot

### Additional information

I modified my pack with FTB Ultimine at some point, but this has been a thing since before that.

**Comment by kenshin13850** [comment]
Oh to add to this - apotheosis bosses spawned by breaking mob spawners do not drop apothic weapons or armor (they're supposed to be guaranteed drops I think?).

**Comment by Saereth** [comment]
This is intended yeah, not a bug. You use Hostile neural networks if you want actual mob farm drops and there are crafting recipes for the apotheosis materials

**Comment by kenshin13850** [comment]
Thank you for the response! I didn't realize those crafting recipes were there for apotheosis.
