### ISSUE TITLE
Wither Skeleton Texture Bug on latest NeoTech

### ISSUE THREAD

**Issue by RedTechGamer236** [FTBTeam/FTB-Modpack-Issues#5406]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

The wither skeleton textures appear to still be bugged. I think it might be due to some incompatibility issues with one or some of the texture packs installed in the pack and/or one of the mods that adds OptiFine features.

### Steps to reproduce

Simply find a wither skeleton.

### Expected behaviour

N/A other than the wither skeleton appearing how it should

### Screenshots

![2024-06-27_13 25 09](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/105459386/91fa35b2-8c9f-444f-ba98-3836838a1432)

**Comment by Saereth** [comment]
should be fixed in the new version coming out 1.4.0
https://blockshot.ch/0Pcd

**Comment by RedTechGamer236** [comment]
I will test it when it comes out. If it isn't fixed, I will let you know.
