### ISSUE TITLE
[Bug]: RFTools Crafter

### ISSUE THREAD

**Issue by Michl7** [FTBTeam/FTB-Modpack-Issues#541]
### Modpack

FTB Endeavour

### Modpack version

1.8.0

### Describe the bug

Crafters don't display their recipes correct.
Mod got update already, pls update pack.

### Steps to reproduce

Open Crafter set recipe.
Come back later open crafter again.
Recipes are gone.

### Expected behaviour

Recipes should stay.

**Comment by Raidobw2** [comment]
Should be fixed in 1.9.0, if not let me know
