### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Hunsruz** [FTBTeam/FTB-Modpack-Issues#5413]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.20

### Has the pack been modified

Yes

### Describe the bug

Dead King area causes game to crash. As soon as i get near the area that the wayward compass is pointing to, the game crashes.

### Steps to reproduce

1. Create wayward compass
2. Get near area wayward compass points to
3. game crashes

### Expected behaviour

expected to get there and kill the dead king

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
