### ISSUE TITLE
ExtendedAE Mod will crash game if config is open

### ISSUE THREAD

**Issue by squyrrel27** [FTBTeam/FTB-Modpack-Issues#5414]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

Updating the client cause my character to have a "step-assist" feature that cannot be turned off. I tried going through config settings, only to find out that ExtendedAE, a mod recently added, will not even allow me to open the config settings.

### Steps to reproduce

1. Open Mods
2. Search for ExtendedAE
3. Hit Config
4. Modify Shared
5. Wait for the crash

### Expected behaviour

The game should not crash

### Additional information

Also, why remove the spatial sounds? They were cool. The sounds people *dislike* are the sounds of the items being switched to in the item bar.

**Comment by Saereth** [comment]
This is a bug in carbon config, openened an issue here 
https://github.com/Carbon-Config-Project/CarbonConfig/issues/33
The step assist feature is unrelated but should be fixed soon
