### ISSUE TITLE
Autofill lock recipe on assembler not working properly

### ISSUE THREAD

**Issue by Gumilho** [FTBTeam/FTB-Modpack-Issues#5415]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

I can't lock the correct recipe for diode on the assembler by clicking on the plus sign from the EMI

### Steps to reproduce

1. Right on an assembler to open its UI
2. Search for Diode in the EMI
3. Left click/press R to see its recipes
4. Click on the assembler menu
5. Click on the plus sign to lock the recipe
6. See error (glass is missing)

### Expected behaviour

The left side should have Steel plate, Silicon plate, Electrum fine wire and glass

**Comment by Gumilho** [comment]
Additional info: the recipe mentioned is the one without N-Doped silicon plate

**Comment by Saereth** [comment]
In this situation you should just drag the input item you want specifically from jei to the slot to lock it
