### ISSUE TITLE
Titanium recipie in electric blast furnace not working

### ISSUE THREAD

**Issue by enderr100** [FTBTeam/FTB-Modpack-Issues#5416]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

The recipe for titanium hot ingot will not work. Even in other worlds the crafting recipe does not work

### Steps to reproduce

1. put titanium raw ore and manganese sulfuric solution into EBF 
2. provide power
3. nothing happens

### Expected behaviour

should start EBF recipe and make titanium ingots

**Comment by Saereth** [comment]
I can't reproduce this, are you use your have your EBF configured correctly? I'll need some screenshots of your setup
