### ISSUE TITLE
Ender IO Power problem when I leave the world

### ISSUE THREAD

**Issue by AndreiMzQ** [FTBTeam/FTB-Modpack-Issues#5417]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.14.0

### Has the pack been modified

No

### Describe the bug

As I mentioned in the title, the energy stored in machines such as alloy smelter, sag mill, etc. disappears when they leave the world and enter again.
I repeated this several times, I also removed the cables so that there is no confusion, but constantly when I leave the world and enter again, the energy stored in the machines is lost from being fully charged to having nothing stored

### Steps to reproduce

1.Put a stirling generator together with a basic capacitor bank and an alloy smelter (they should be completely empty)
2.Don't forget to place any type of capacitors in the machines
3.Place a coal in the stirling generator and waits for the energy to reach the alloy smelter
4.Exist world
5.Enter world and you will see that the machine has no energy

### Expected behaviour

The energy stored in the machines should remain unchanged after they exit and re-enter the game

**Comment by AndreiMzQ** [comment]
Apparently in version 1.13.1 I don't have this problem

**Comment by DinnerBeef** [comment]
Can you please let me know if this issue is still happening for you? The mod was updated in the latest version of the pack. Version 1.15.0
