### ISSUE TITLE
Respawning Ender Dragon creates a bugged Dragon that does nothing and hovers in the Air until Killed

### ISSUE THREAD

**Issue by magisch** [FTBTeam/FTB-Modpack-Issues#5418]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

1. Respawn Ender Dragon with 4 End Crystals
2. Respawning Ender Dragon creates a bugged Dragon that does nothing and hovers in the Air until Killed

### Steps to reproduce

1. Respawn Ender Dragon with 4 End Crystals
2. Respawning Ender Dragon creates a bugged Dragon that does nothing and hovers in the Air until Killed

### Expected behaviour

The dragon would do something, and attack me, allowing me to collect Dragon's Breath

**Comment by Saereth** [comment]
This next update should have a fix for this now
