### ISSUE TITLE
Alloy Kiln recipes are randomly breaking

### ISSUE THREAD

**Issue by rushedman** [FTBTeam/FTB-Modpack-Issues#5419]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

Not sure if this is a bug with the Alloy Kiln or the custom recipes. But when you load up a save it will randomize all alloy kiln recipes. (As in items may be missing). Even if you know the recipe it won't work unless EMI shows the complete recipe. 

### Steps to reproduce

This is in Single Player
1. Load in a world
2. Check your alloy kiln for the recipes
3. confirm what is working, if what you want to work is working continue playing
4. If what you want is not working, leave the world and come back
5. Check again 

### Expected behaviour

All alloy kiln recipes are constant

### Screenshots

![2024-06-30_11 24 40](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/138314672/fa5c2b90-ffc6-4b77-989d-9d13e3e9d98f)
![2024-06-30_11 25 02](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/138314672/1a228ce8-9366-4cba-a2ee-318c4a582925)

### Additional information

As you leave the world and come back it seems to fill out more and more consistently until it fixes itself.

**Comment by Saereth** [comment]
looks to be  a tag loading issue, I've added a mod in the next update to try and force their loading
