### ISSUE TITLE
[Bug]: Game crashes on launch

### ISSUE THREAD

**Issue by sledgendary** [FTBTeam/FTB-Modpack-Issues#542]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Log Files

[crash-2022-01-05_12.39.43-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7817077/crash-2022-01-05_12.39.43-client.txt)

### Describe the bug

Anytime I try and launch OceanBlock, it crashes. It won't load past the mod loading phase. The error I receive states that there is an error loading an overlay.

### Steps to reproduce

1. Open FTB App
2. Launch OceanBlock
3. Early loading process completes
4. Mod Setup begins and then the game crashes

### Expected behaviour

I expected the game to launch

### Screenshots

<img width="864" alt="Screen Shot 2022-01-05 at 12 46 54 PM" src="https://user-images.githubusercontent.com/97190653/148272124-0544e1cd-5161-475d-a6a6-3a5753f2ce99.png">

### Additional information

I receive error code 255 from the Minecraft launcher whenever it crashes. I use a 2014 Macbook Pro and was previously able to run the game just fine up until today. Only change I made was updating my Java to Java 8 v311, previously it was 301. I tried downgrading back to 301 but the issue remains. No other changes have been made to my system. I've tried reinstalling tinker's construct since that seems to be the issue to no avail. Forgive me if I'm not using the proper channels to report this, first time reporting any issues for a Modpack but I love this pack so I'd love to see a fix if possible!

**Comment by Raidobw2** [comment]
Hello, I would say to start by reinstalling the modpack. It appears architectury `architectury-1.25.36-forge.jar` is in your files but `architectury-1.26.39.jar` is the latest mod version that was released with 1.11.0. Are you sure you are using the latest release 1.11.0?

Start by backing up your saves if you have any (if you didn't start playing yet you don't have saves).
Then, delete the `.localCache` folder inside your instances folder. This is the download cache.
Then, uninstall the modpack, and reinstall it on the latest version, 1.11.0.

Play it, and let me know if you still crash.

**Comment by sledgendary** [comment]
It worked! I very much appreciate the assistance, I was on the current version when the crashes started which is odd. Regardless, thanks again my friend! Have a wonderful day.
