### ISSUE TITLE
Thermo plant recipes broken

### ISSUE THREAD

**Issue by Rushmead** [FTBTeam/FTB-Modpack-Issues#5420]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

The recipes for making kerosene from diesel, gasoline from kerosene and lpg from gasoline are broken in the latest version. They show up in EMI but do not actually work.

### Steps to reproduce

1. Use a TPP to try and create kerosene from diesel.

### Expected behaviour

The recipes to work.

**Comment by Saereth** [comment]
Desht gave me an updated build of PNC that should solve this
