### ISSUE TITLE
Chance of the wrong steel ingots being created

### ISSUE THREAD

**Issue by Rushmead** [FTBTeam/FTB-Modpack-Issues#5424]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

There is a chance when starting / restarting / reloading a server that the Mekanism steel ingots do not get disabled properly and Mekanism machines will create the Mekanism steel ingots instead of the Modern Industrialisation. This seems like some kind of race condition?

### Steps to reproduce

Start server, have mekanism machine smelting steel dust into steel ingots and do /reload, see if it starts making the wrong ingots.

### Expected behaviour

Always disable the mekanism steel ingots

**Comment by Saereth** [comment]
tag issue agian similar to several other issues, put in several things to try and address it, cant current reproduce it on dev so hopefully its sorted

**Comment by Caellian** [comment]
In the meantime, you can easily fix this with CraftTweaker by adding a file with the following command to the `<instance>/scripts` directory:

```zs
# Remove mekasnism recipe
craftingTable.remove(<item:mekanism:ingot_steel>);
```
