### ISSUE TITLE
FTB Lite3 1.5.1 includes client only mod Custom Main Menu

### ISSUE THREAD

**Issue by JulianVennen** [FTBTeam/FTB-Modpack-Issues#5425]
### Modpack

FTB Lite 3

### Modpack version

1.5.1

### Has the pack been modified

No

### Log Files

https://mclo.gs/lgfz3K8

### Describe the bug

The server installation for this modpack crashes due to a client-only mod

### Steps to reproduce

1. Download the server installer
2. Run it

### Expected behaviour

The server should start without other intervention

**Comment by Gaz492** [comment]
This should be fixed now.
