### ISSUE TITLE
No Thermal Expansion Pipes

### ISSUE THREAD

**Issue by Ribster07** [FTBTeam/FTB-Modpack-Issues#5426]
### Modpack

FTB Ultimate: Anniversary Edition

### Modpack version

1.3.1

### Has the pack been modified

No

### Describe the bug

The modpack thermal expansion is missing thermal dynamics so we cant connect the different machines whith power sources

### Steps to reproduce

1 Play the game
2 Use thermal dynamics
3 you will miss wires to connect machines to power source

### Expected behaviour

Would be great to get an update for FTB Ultimate anniversary with the missing thermal dynamics mod or just a step by step info on how to install this missing mod by ourself

**Comment by Gaz492** [comment]
You can add a mod to the modpack by following the guide below.
https://docs.feed-the-beast.com/docs/app/Instances/add-mods-to-instance

I will also bring up that this mod is missing to our pack maintainers.

**Comment by Gaz492** [comment]
So it appears that thermal dynamics was never released for 1.16 so its not possible to add the mod to this pack unfortunately.
