### ISSUE TITLE
Bugged crafting recipe

### ISSUE THREAD

**Issue by Sidex06** [FTBTeam/FTB-Modpack-Issues#5427]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

Can't craft Etching Tank, Using JEI to auto fill recipe it filling everything but tank in the middle.

### Steps to reproduce

Try to craft Etching tank.
Use auto fill recipe fith JEI.

### Expected behaviour

Craft Etching tank

### Screenshots

![2024-07-01_17 53 40](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/126839612/fb7d9e69-d5ec-4189-b1d7-b8fffe637c7b)

**Comment by mjory80** [comment]
Looks like this was fixed in version 7.0.2 of pneumaticcraft:
https://modrinth.com/mod/pneumaticcraft-repressurized/version/7.0.2
