### ISSUE TITLE
Mods/modpacks refuse to open

### ISSUE THREAD

**Issue by EmissaryGaming** [FTBTeam/FTB-Modpack-Issues#5429]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Has the pack been modified

No

### Describe the bug

Every time I attempt to run Stoneblock 3 it will not open, giving me a different but similar slew of errors every time. I have verified files, uninstalled and reinstalled Stoneblock, and even did the same with the FTB app. Nothing I have done has worked.
This is the same for every other mod/modpack I have attempted to install. Everything I have attempted to do has done nothing.

### Steps to reproduce

1 (optional): Install StoneBlock 3.
2: Play StoneBlock 3.
3: Wait for errors.

### Expected behaviour

What I expected to happen was for Stoneblock 3 to run just fine. My friends installed Stoneblock 3 yesterday and ran into no troubles or issues, and I had not expected to run into any either.

### Screenshots

My screen is unable to capture each screenshot individually, so I have recorded them instead. THe file size was too large to put here, so I posted them on YouTube. Below is a link to the video with the errors.
https://youtu.be/38muHWHmM6U (I forgot to turn off various things, and my voice is echoed because of it. I hope you can understand what I'm saying, and I apologize in advance.)

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by EmissaryGaming** [comment]
[debug.log](https://github.com/user-attachments/files/16071662/debug.log)
[latest.log](https://github.com/user-attachments/files/16071668/latest.log)


> Would you be able to upload the logs from the modpack so we can have a look at them? A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
Hope this helps.

**Comment by Gaz492** [comment]
May I ask what your computer specifications are? Mainly your CPU, Memory and GPU?
From the video you posted and the logs, it looks like you may be running into memory related issues.

**Comment by EmissaryGaming** [comment]
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/174465373/bbe04aba-e220-45b2-8486-f81a1039a66e)
My dad bought me my computer so I know nothing about its info, but he said it is top of the line gaming stuff. I don't know how to check my specs myself, but I hope this works.

**Comment by Gaz492** [comment]
Thanks, if you try starting up vanilla minecraft with the vanilla launcher does that start up correctly for you?
If it does, would you be able to try installing any popular modpack using the curseforge app?

**Comment by EmissaryGaming** [comment]
Sorry for the late reply! Yes, vanilla minecraft opens with the vanilla launcher, and mods from curseforge open just fine.

**Comment by Gaz492** [comment]
Would you be able to try installing a newer FTB modpack such as neotech?
Im not 100% sure what the cause of the issue you are running into at the moment, as I am unable to replicate the issue.
