### ISSUE TITLE
[Suggestion]: Rename Trophy for Mod Completion

### ISSUE THREAD

**Issue by SeraTheWitch** [FTBTeam/FTB-Modpack-Issues#543]
### Modpack

FTB University 1.12.2 

### Is your suggestion related to a problem? Please describe.

When the NC:O quests are finished, rename the trophy for the mod from "Nuclear Physicist" to "Homer Simpson", a reference to The Simpsons, where Homer is one of the mcs and is a really bad safety inspector

**Comment by aaronhowser1** [comment]
I'd rather not. Just going "Homer Simpson" isn't really funny enough, it's just going `This is a reference`.

**Comment by SeraTheWitch** [comment]
Ah fair enough
