### ISSUE TITLE
Pressing middle button (sort feature) in Curios menu deletes items (backpacks, glasses) - still

### ISSUE THREAD

**Issue by LowPotato** [FTBTeam/FTB-Modpack-Issues#5430]
### Modpack

FTB Builders Paradise 2

### Modpack version

1.1.0

### Has the pack been modified

No

### Describe the bug

When I open the expanded slots for e.g. rings, move the mouse to any slot of the curios menu and press the scroll wheel, the item disappers into the nowhere. This happed to me with the backpack and the glasses, however, the belt for arrows wont disappear.

The problem has been discribed here before and was closed as it was fixed - but I still do have this problem.
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4148, https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4258,  https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5005 https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5005

### Steps to reproduce

1. Click Curios Sub-Menu
2. Hover Cursor over any inventory slot
3. Press middle mouse button "inventory sorting feature"

### Expected behaviour

Pressing the middle button was a reflex, I did not expect any behaviour

**Comment by LowPotato** [comment]
The bug is still active - now the bagpack wont disapper, but the glasses and the belt slot is cleared when "sortig" the curio

**Comment by Mentaleak** [comment]
Bug is still active in the 1902 builds

**Comment by Myrddin2008** [comment]
Issue still occurring in 2025! I accidentally deleted a Copper Backpack from Sophisticated Backpacks, and a Reservoir from Thermal. Will make my own Issue as well to track this.
