### ISSUE TITLE
reaper mod bug

### ISSUE THREAD

**Issue by Gofcior** [FTBTeam/FTB-Modpack-Issues#5433]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Has the pack been modified

No

### Describe the bug

reaper generator from the reaper mod has the capacity bug and per shot it can only capacity 4.8kFE and 

### Steps to reproduce

1.place reaper generator 2.spawn mobs near the generator 3.give reficiat rune to it 4.load reaper generator with soul catalyst
5.and you see the bug/// or just look at the screens

### Expected behaviour

to fix the bug 

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/174626651/ce778a33-7a1e-44b7-b462-ea3e92ae4dcf)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/174626651/d1c23785-6f2b-45b9-8e89-70a898bb6f08)

**Comment by Saereth** [comment]
this is not a bug, this is an intentional limited factor to the reaper generator
