### ISSUE TITLE
Direwolf20 (1.7) Rendering/Graphical Issues

### ISSUE THREAD

**Issue by TAult5** [FTBTeam/FTB-Modpack-Issues#5434]
### Modpack

FTB Presents Direwolf20

### Modpack version

1.7.10

### Has the pack been modified

No

### Describe the bug

Initially started with issues properly rendering the textures of certain items in the Nether. If the item that is having issues rendering is looked at with the player crosshairs, it will cause a full-screen color out. Restarting the game doesn't help the issue at all, the only thing is to attempt to get the blocks that are messed up off of the screen. This issue eventually started occurring with chests in my house. The chests are made from greatwood logs, and will not render their skins at all, so they appear as all-black chests. If i Look at the chests directly, my screen will turn a solid color (bright green, brown) until I look away. Additionally, if I attempt to craft one in my inventory, as soon as the chest appears in the crafting window, my entire inventory will glitch out. 

Attached are relevant images. Oddly enough, if I take a screenshot when my screen is colored out, the screenshot still appears as if I have a normal view of everything. 

![2024-07-03_23 03 18](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/69481011/ce6509f7-01d4-4006-8835-7ce64a22cb36)
![2024-07-03_23 03 23](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/69481011/d2597b5e-c934-440e-bf1f-156edf9006a1)
![2024-07-03_23 03 48](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/69481011/c463af5b-8770-434f-9106-d5784053083e)
![2024-07-03_23 03 57](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/69481011/3ca8b1c3-bd44-4d6e-9d53-7486771ec9ef)
![2024-07-03_23 04 12](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/69481011/03fc8b12-1816-46e4-b735-4a03a345d1d9)
![2024-07-03_23 04 13](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/69481011/083704f2-da6e-4e4c-ac1b-434e0bdccf4d)

### Steps to reproduce

I am unsure how to replicate this issue. This issue initially started in the Nether. My game was working fine until I encountered a partial chunk that didn't properly render. 

### Expected behaviour

Proper rendering of my items and no graphical issues. 

### Screenshots

![2024-07-03_23 03 18](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/69481011/98402f06-b359-4e9b-8b24-d5e7596b6fcc)
![2024-07-03_23 03 23](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/69481011/9ac5de00-5ac6-4940-984a-8db0645b0822)
![2024-07-03_23 03 48](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/69481011/e56a17f0-bac2-496a-8ca4-966b8a0a129e)
![2024-07-03_23 03 57](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/69481011/90abfcee-b575-41df-bb16-161b80b78b36)
![2024-07-03_23 04 12](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/69481011/adb4ac70-27ea-4cf1-8e6b-3a43fcbc567c)
![2024-07-03_23 04 13](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/69481011/7e7dc720-8d59-4de6-8ede-a91bf7634d14)

### Additional information

I don't think it's an issue with my machine. I have a 4080, 32gb ram, and an i9 processor. I've also allocated 10gb of ram for the game.

**Comment by Gaz492** [comment]
This may be a graphics driver issue, could you try making sure that your graphics drivers are up-to-date?

**Comment by TAult5** [comment]
I updated my driver after it started happening, and that did not fix the issue.

**Comment by Gaz492** [comment]
Ok, may I ask what specs your pc is (CPU, Memory GPU)
