### ISSUE TITLE
game close as soon i join my nitrado server

### ISSUE THREAD

**Issue by Nicinator420** [FTBTeam/FTB-Modpack-Issues#5437]
### Modpack

FTB Presents Direwolf20

### Modpack version

1.20 v1.12.1

### Has the pack been modified

No

### Log Files

[crash-2024-07-04_20.47.26-client.txt](https://github.com/user-attachments/files/16102180/crash-2024-07-04_20.47.26-client.txt)
![Screenshot 2024-07-04 204104](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/174741953/03876759-2e68-4ae5-99c5-2300e8e78859)

### Describe the bug

hi everybody. i rented a nitrado server to play direwolf with my friends. and now everytime i want to connect to the server my game crashes and close automatic. in singleplayermode its no problem to join a world.
with my friend its the same problem.
the versions are correct and i dont know what to do now...
had anyone of you the same problem?

### Steps to reproduce

1. launch nitrado server
2. install direwolf20 1.20-1.12.1
3. multiplayer
4. join server
5. load world
6. save world
7. minecraft down

### Expected behaviour

minecraft should start. half a year ago it worked

**Comment by Gaz492** [comment]
Would you be able to upload the server log as well?
I have a sneaking suspicion that the server didn't load any mods.

**Comment by Nicinator420** [comment]
[latest.log](https://github.com/user-attachments/files/16102278/latest.log)

**Comment by Gaz492** [comment]
Thanks, that log indeed confirms that the server didnt load any mods up.

I would recommend you contact nitrado support as it looks like their install for the modpack may have failed.
Also, version 1.12.1 of the modpack is rather old, 1.15.0 is the current latest of Direwolf20 1.20 and has fixed quite a lot of bugs in the latest version.

**Comment by Nicinator420** [comment]
okay thank you very much :)
