### ISSUE TITLE
Game crashes as soon as i launch

### ISSUE THREAD

**Issue by misuletu** [FTBTeam/FTB-Modpack-Issues#5438]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Log Files

https://pastebin.com/AcB1eW5H

### Describe the bug

i just try to launch the game normally and it crashes. Have not made any modifications, restarted the PC 3 times

### Steps to reproduce

1. launch from FTB App
2. Crash
3. ???

### Expected behaviour

The game would just launch as normal

**Comment by Gaz492** [comment]
Could you try renaming the minetogether.json file in the config folder of the modpack?

You can open the config folder of the modpack by going to the modpack in the app and clicking on it, then if you click on the 3 vertical dots next to the play button hover over `Open...` and click on the 	`Config folder` option it will open your file explorer to that folder.

**Comment by misuletu** [comment]
renamed it to something random, game still crashes
new crashlog: https://pastebin.com/fWbciY3f

**Comment by Gaz492** [comment]
Ok, for the time being if you disable the MineTogether mod it should hopefully let you start the pack up.
https://docs.feed-the-beast.com/docs/app/Instances/disable-mods-on-instance

**Comment by misuletu** [comment]
works for now, thank you!
