### ISSUE TITLE
Tin wires is not showing in barrels

### ISSUE THREAD

**Issue by Quazaka** [FTBTeam/FTB-Modpack-Issues#5439]
### Modpack

FTB NeoTech

### Modpack version

1.2.1

### Has the pack been modified

No

### Describe the bug

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/6616239/953e914a-798e-4e9f-b572-88bf75a26d61)

Tin wires is not shown in barrels. 

### Steps to reproduce

Pun tin wires in barrels.

### Expected behaviour

I can see the wires.

**Comment by Gaz492** [comment]
Could you please confirm if you are still experiencing this issue with the latest pack version? As I have not been able to replicate this issue.

**Comment by Quazaka** [comment]
I will update this weekend and let you know.

**Comment by Quazaka** [comment]
Still a problem for me in the newest version.

**Comment by Saereth** [comment]
reported to Sophisticated storage
