### ISSUE TITLE
[Bug]: Recipes missing Modular Powersuits and armor mods disappearing

### ISSUE THREAD

**Issue by nickrobi** [FTBTeam/FTB-Modpack-Issues#544]
### Modpack

FTB Ultimate Anniversary

### Modpack version

1.2.0

### Describe the bug

1. Many recipes missing for MachineMuse's Modular Powersuits. Glider wings, fall damage reduction boots, and mining enhancement modules for the gauntlets such as the soft touch mod, fortune mod, and others. These are visible from the tinkerers bench but not craftable with any of the available
2. Wearing a full suit of power armor while going into the Tinkerer's bench will sometimes poof (delete) various mods from the armor. Have to mod each piece one at a time to avoid losing batteries/mods.

### Steps to reproduce

1. Go to Tinkerer's Modular Workbench with power armor equipped
2. Click on the piece of armor / the glove
3. Click on install/salvage until it shows available modules
4. Look through recipe directory in Just Enough Items
5. Notice that recipes for various Power Armor modules are not in this modpack

### Expected behaviour

All recipes for modules for power armor should be available, all of the materials typically used in these recipes are already in the modpack

### Screenshots

![ween](https://user-images.githubusercontent.com/48817428/148287836-d1171e6e-2a7e-4967-80ce-b04d9860baff.png)

**Comment by Raidobw2** [comment]
Should be fixed in the latest 1.3.0 update after updating the mod! The mod update contained many fixes and added all unfinished recipes. Let me know if everything is there!

**Comment by GrandpaGage** [comment]
I am on the latest 1.3.0 and am still experiecing this. I have tried reinstalling and that has not worked for me 
https://pste.ch/kebumatohi
im not sure how i can be of more help besides the jei does not show the recipes for some of the items such as jetpack glider silk touch fortune ect i seem to be getting the exact same error in the new verision.

**Comment by Raidobw2** [comment]
Thanks for the feedback! After checking looks like they were still hidden by a script. If you look into your modpack folder, you will see a folder named `kubejs`. If you navigate to `kubejs/client_scripts/jei.hide.js`, you can remove that whole block of code since it is only client changes.
```
//Modules not implemented yet
event.hide("powersuits:invisibility");
event.hide("powersuits:swim_assist");
event.hide("powersuits:sprint_assist");
event.hide("powersuits:shock_absorber");
event.hide("powersuits:parachute");
event.hide("powersuits:jump_assist");
event.hide("powersuits:jetpack");
event.hide("powersuits:jet_boots");
event.hide("powersuits:glider");
event.hide("powersuits:flight_control");
event.hide("powersuits:dim_rift_gen");
event.hide("powersuits:climb_assist");
event.hide("powersuits:mob_repulsor");
event.hide("powersuits:aqua_affinity");
event.hide("powersuits:silk_touch");
event.hide("powersuits:fortune");
event.hide("powersuits:climb_assist");
```
Looks like that was an oversight on my part when making the update a few weeks back. Thanks for pointing it out, I'll have it fixed fully for the next update.

**Comment by NytSong** [comment]
Fun fact:
If you edit that script, you get to click through this error every time you launch that instance.

![warning](https://user-images.githubusercontent.com/61587778/167016519-585a054c-9f9a-4d74-9dec-df6ba214d4cb.png)

**Comment by Raidobw2** [comment]
I'll report that to the dev team, that message should only show once. Thanks for letting me know

**Comment by lupinedusk** [comment]
Hi. I am using 1.3.0 as the previous user was, and I am having the same exact issue. However, when I go looking for a kubejs file to attempt the fix you gave him, one does not exist for modular powersuits.

**Comment by coiledmocha** [comment]
Still an issue. I guess the pack never received any further updates. The "potantial invalid instance" message still appears repeadetly. The fix above works. But it should still be updated nonetheless. It cost me some time to figure out that the issue was JEI.
