### ISSUE TITLE
Thermopneumatic processing plant not inputting fluids

### ISSUE THREAD

**Issue by Kacper110505** [FTBTeam/FTB-Modpack-Issues#5441]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Log Files

[debug.log](https://github.com/user-attachments/files/16110398/debug.log)
[latest.log](https://github.com/user-attachments/files/16110400/latest.log)

### Describe the bug

i encounter this bug yet again, first time it was with virulent mix not pumping into thermopneumatic processing plant (tpp), now its LPG not wanting to go in, i tried fluid pipes from modern industrialization, mechanical pipes from mekanism, pretty pipes. Nothing seems to be working

### Steps to reproduce

place tpp and produe raw biodiesel with it, wait few hours, no more fluid inputs

### Expected behaviour

thermopneumatic processing plant not receiving fluid inputs

### Screenshots

![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/145325535/154ab3e3-e7c8-4eb1-ad2f-3536cddd1f72)
![image](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/145325535/02e1b015-19a3-4c24-8943-90d70ca2433a)

**Comment by firex20** [comment]
Hi, im playing 1.7.0 version and the same problem still persist, sometimes it fixes itself by reloading the world by going to the main menu and back to the world.

**Comment by Sainto3000** [comment]
I am encountering the same issue on version 1.8.2. It happens with different kinds of fluids. I tried standing next to the TPPs because I though maybe it's a chunkloading issue but it still happens. Restarting the server only momentarily fixes it.

**Comment by OlegGedzjuns** [comment]
Same issue for me, FTB NeoTech 1.20.2

**Comment by kykc** [comment]
Same issue with TPP and Purified Virulent Mix happened in my world just now on FTB NeoTech 1.11.2 (Single player)

Exiting/rejoining world didn't help, restarting client didn't help. Used MI pipes.

**Comment by NZGlitch** [comment]
Same issue running 1.11.2 Neotech and MI Pipes, tried going in and out of the menu and reloading the game several times to no avail.

**Comment by Saereth** [comment]
I'm still waiting on desht to accept the PR that fixes it then we can publish it https://github.com/TeamPneumatic/pnc-repressurized/pull/1518
