### ISSUE TITLE
Black Particles

### ISSUE THREAD

**Issue by hanky21** [FTBTeam/FTB-Modpack-Issues#5443]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

Sometimes particle effects turn fully black

### Steps to reproduce

Happens when wandering around the world/my base, can sometimes be seen through walls

### Expected behaviour

No fully black particles

### Screenshots

![2024-06-16_18 54 16](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/75486781/f4d8150a-095f-412f-8a19-41a617ee795e)

**Comment by Saereth** [comment]
This has been reported before but we've been unable to reproduce it in dev. Could you try messing with your render settings/graphics and see if anything improves it for you and let us know.

**Comment by 2ndRecon** [comment]
I have this same issue. Is particularly noticeable when inside a structure as it looks like bugs crawling on my PC screen. 

RTX 3090 Founders Edition 
Driver: v.555.85
Standard Clocks.

**Comment by crusender** [comment]
That is a bug? I was thinking it was how falling leaf mod was working...

**Comment by Saereth** [comment]
its some render setting with that mod yeah, you could disable falling leaves mod but I'd like to figure out the actual issue to see if we can fix it for those being impacted by it. I cant reproduce it myself and it doesnt happen for everyone so we need help tracking it down from those that can get it to happen by disabling mods that may interfere with it

**Comment by crusender** [comment]
I can say it is not cause by the MI Barrel bug (recreate my old base on version 1.3). 

I dont know if that help, but I will say I didnt see it happen, since I move my base to a Taiga biome, my old base was in a Forest biome.

**Comment by crusender** [comment]
I can make the leafs become black, each time I pick items of the ground. I to think it become black when I to mush particles active (not able to reprodure accuraly)
