### ISSUE TITLE
Macerators recipes missing components, Curios that were curios aren't curios anymore(They no longer go into the slots), Steel Hammer has no purpose, Villagers glitch occasionally.

### ISSUE THREAD

**Issue by Seroku03** [FTBTeam/FTB-Modpack-Issues#5447]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

1. Tin Ore (Normal or deepslate) can't go into the Macerator no more.
Lead Raw Ore can't be process into the macerator no more
Macerators are missing components in their recipes (Ingots, Gears, Plates, Raw Ore)

2. Yesterday Magnets were no longer a slot item, now it is again
Today tarot book and monocle(For horses) aren't slotted items.

3. Literally (Steel Hammers serve NO Purpose)

4. When seeing the Villager Tab (Professions or Trades) the render image glitch in and out.

### Steps to reproduce

1. Tin Ore (Normal or deepslate) can't go into the Macerator no more.
Lead Raw Ore can't be process into the macerator no more
Macerators are missing components in their recipes (Ingots, Gears, Plates, Raw Ore)

2. Yesterday Magnets were no longer a slot item, now it is again
Today tarot book and monocle(For horses) aren't slotted items.

3. Literally (Steel Hammers serve NO Purpose)

4. When seeing the Villager Tab (Professions or Trades) the render image glitch in and out.

### Steps to reproduce

1. 
a. Open up the Game
b. Look at *Show Recipes* on a Macerator
c. Scroll to the missing Items on the recipes.

2.
a. Open up the game
b. Hover over the Item (Tarot Book {Curio}, Monocle{Head})
c. Slot description no longer there

3.
a. Open up the game
b. Look into the EMI data base
c. No Purpose

4.
a. Open up the game
b. Look into the EMI data base
c. Open Profession/Trade Tab for villagers
d. Look at the Villager Renders

### Expected behaviour

Macerator to work, Curios Items to be consistent, Hammer to have purpose, Image to not glitch out

### Screenshots

![2024-07-05_18 38 04](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/514ba4dc-1ff1-4046-b1c0-77389159ad8b)
![2024-07-05_18 38 17](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/4b38cac2-83a2-4d5a-8595-37e785cffdc3)
![2024-07-05_18 39 12](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/baa11c66-ae6e-4af2-92aa-b8d8a4a0c516)
![2024-07-05_18 41 06](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/268cdffa-1556-42a0-abd7-31a97181e7d2)
![2024-07-05_18 41 17](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/1f9ed9af-b549-4db6-94ff-d611e81fcd37)
![2024-07-05_18 42 14](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/c98aa7df-3986-4896-bef7-9c566aa59423)
![2024-07-05_18 42 46](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/9b2edc9c-e5fd-4095-838e-55a2fd96962e)
![2024-07-05_18 43 35](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/f6c40f8a-afb8-4a2b-90a1-cda799c5ee6c)
![2024-07-05_18 44 37](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/3e8eb248-6b4a-4eb7-ab95-a118cb327b74)
![2024-07-05_18 44 59](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/a5cf7897-813a-4b49-bea9-765afc537811)
![2024-07-05_18 45 09](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/33bacd89-e38a-4ab5-a004-73a0bc7dbe60)
![2024-07-05_18 45 14](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/a6ca631d-c290-49ce-85a4-f04322be5859)
![2024-07-05_18 45 28](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/e580f410-cb7b-4208-8538-9c0452abc760)
![2024-07-05_18 45 33](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/fdf4f1da-91d8-407a-adc8-376e81a0871f)
![2024-07-05_18 45 51](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/655ad7d8-4901-4fba-83fe-3e19c0976298)
![2024-07-05_18 47 24](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/372d023d-50c4-4205-b665-9c633fa64602)
![2024-07-05_18 49 40](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/bd5a5777-3052-41b9-9ac2-40503ed81393)
![2024-07-05_18 49 46](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/d29d47f9-7356-4a93-a0e7-30fb8efcafda)
![2024-07-05_18 49 49](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/2a267fe5-e355-4f1a-a695-e7be0112eab1)
![2024-07-05_18 50 00](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/8148730c-ea19-4029-a9b3-58d63015dce6)
![2024-07-05_18 50 02](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/c4c34ade-e9f8-484d-913a-8f242a3b93e1)
![2024-07-05_18 50 03](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/53b46b4d-41ac-4e1d-9112-3e4d872fc99c)
![2024-07-05_18 50 06](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/16d33845-246e-43d4-b846-3eb1f1f4645d)
![2024-07-05_18 50 08](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/0086efe4-d3f3-4793-8279-bb0415d3e79b)
![2024-07-05_18 50 44](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/015acf50-9171-4f9f-98d9-e97be5046c62)
![2024-07-05_18 50 50](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/422e2ce2-c1a5-41dc-bd9e-e6ce955183bc)

### Additional information

Hope I have been concise enough.

**Comment by Seroku03** [comment]
***EDIT***

Upon attempting a REPAIR from the FTB Launcher, the issue with the missing ingredients from the Macerator and all the curio stuff got fix.

---------

The Steel Hammer is still USLESS and the Villagers are still glitchy.

***EDIT***

**Comment by LWmods** [comment]
kubejs is constantly bugging out in this pack /reload or relogging will fix it until a real fix is released.

**Comment by Saereth** [comment]
All of these should be fixed in the next update, in the future please make seperate issues for each thing, makes tracking and followup a lot better
