### ISSUE TITLE
MI Fluid and Item pipe dye recipes problem

### ISSUE THREAD

**Issue by davidgillen** [FTBTeam/FTB-Modpack-Issues#5448]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

The recipes for dying fluid or item pipes only work when the dye and pipe are horizontally arranged. Diagonally and Vertically result in no output. The same behaviour is in there for 2x2 and 3x3 grids.

### Steps to reproduce

Place an MI Fluid Pipe in the centre of a 3x3 crafting grid. Place a single dye in one of the 8 surrounding empty spaces, move the dye around testing in each of the spaces and observe where the dying works and doesn't work.

### Expected behaviour

Recipe would be completely shapeless.

**Comment by Saereth** [comment]
this isnt a bug, thats the recipe, 3x3 crafting grid, pipe in the center, dye on the left. This would be an issue for MI if you want their basic behavior changed as this is not something we've changed in the pack
