### ISSUE TITLE
No way to get phantom membrames  in the early game

### ISSUE THREAD

**Issue by linuxchr** [FTBTeam/FTB-Modpack-Issues#5449]
### Modpack

FTB Skies Expert

### Modpack version

1.8.1

### Has the pack been modified

Yes

### Describe the bug

The only way to get membrames is through antimatter.

### Steps to reproduce

Look it up in JEI

### Expected behaviour

A Toggle to let phantoms spawn or a way of crafting membrames.

**Comment by Quazaka** [comment]
Just don't sleep and kill the phantoms. It's a vanilla Minecraft mechanic.

**Comment by Gaz492** [comment]
As Quazaka mentioned, you can get them using the vanilla mechanic of not sleeping for a few nights to summon phantoms and kill them to get the membranes

**Comment by linuxchr** [comment]
The problem is that the phantoms dont spawn even if you dont sleep.

**Comment by Saereth** [comment]
The wandering trader wil now sell phantom membranes for infused fabrics
