### ISSUE TITLE
[Bug]: FTBIC Machines in multiplayer have broken energy capacity

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Modpack-Issues#545]
### Modpack

FTB Ultimate AE

### Modpack version

1.2.0

### Describe the bug

Title. Shows 0/0 instead of 0/30000

### Steps to reproduce

See screenshot

### Expected behaviour

Show 0/30000

### Screenshots

![image](https://user-images.githubusercontent.com/3844385/148383158-aca72a6b-494b-4c2a-b886-35c126b1dd91.png)

**Comment by LatvianModder** [comment]
https://github.com/FTBTeam/FTB-Mods-Issues/issues/158

**Comment by Shadowner83** [comment]
I have the same issue aswell on the Geothermal Generator.

**Comment by MichaelHillcox** [comment]
Closed as duplicate issue, see above comment.
