### ISSUE TITLE
AE2 EMI integration

### ISSUE THREAD

**Issue by Quazaka** [FTBTeam/FTB-Modpack-Issues#5450]
### Modpack

FTB NeoTech

### Is your suggestion related to a problem? Please describe.

EIM is a super cool mod, but it's frustrating when i am crafting for example 200 circuits and i cant hold all the items in my inventory. So when i dump them into my ae terminal, the items are no longer considered "crafted". I would be super nice if there was a way to remove item in my AE system from my "to be crafted" list. 

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/ae2-emi-crafting-integration

I belive this would fix it, but i am not sure.

**Comment by Saereth** [comment]
yeah unfortunately this mod isnt avaialble for 1.20.4 neotech, if it ever becomes available we'll gladly add it.
