### ISSUE TITLE
Cannot enter the nether

### ISSUE THREAD

**Issue by DerpQueen** [FTBTeam/FTB-Modpack-Issues#5451]
### Modpack

FTB Presents AbePack

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

Cannot enter the nether. Portal is lit and acts like we're being teleported, but nothing loads. 

### Steps to reproduce

Try to enter a nether portal?

### Expected behaviour

Go to the nether

**Comment by Gaz492** [comment]
I have not been able to replicate this issue.

Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
