### ISSUE TITLE
Callable horses only works with 1 player at a time

### ISSUE THREAD

**Issue by z1haze** [FTBTeam/FTB-Modpack-Issues#5452]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

Preface: I am not sure if this is the _only_ usecase, but definitely valid for my usecase

With 2 players in an FTB party, the callable horses summon menu only works for 1 player at a time. If player 1 is on their horse, they "take over" the summon menu. If player 2 then gets on their horse, they take over the summon menu, and player 1 can no longer press the x button to open to menu. Instead player 1 now sees "no tamed entities" message. This is pretty significant considering you can end up in a position where you lose your horse pretty easily, because you expect that your summon menu will just work.

### Steps to reproduce

1. Join FTB party with 2 players (not sure if this is relevant)
2. Player 1 ride horse, and press x, seeing that the summon menu is functioning
3. Player 2 ride horse, and press x, seeing that the summon menu is functioning
4. Player 1 again press x to see that their summon menu is not functioning, instead sees "no tamed entities" message.

This pattern will continue indefinitely, swapping which player has control over the summon menu.

### Expected behaviour

Each player should be able to independently control their callable horses menu

**Comment by Saereth** [comment]
This is a limitation of the mod and more importantly vanilla's taming behavior. A tamed animal can only have one master, the last person to ride the horse is considered the master in this regard.

**Comment by z1haze** [comment]
You did not read my issue clearly. The issue is not the same horse. They are separate horses. Please re-open.
