### ISSUE TITLE
Refinery Controller isnt craftable?

### ISSUE THREAD

**Issue by Neddyfoeee** [FTBTeam/FTB-Modpack-Issues#5454]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

Ive tried to craft it in several crafting grids and nothing works.

### Steps to reproduce

Try and craft the refinery controller

### Expected behaviour

I hope it can fixed

### Screenshots

![2024-07-08_13-55-03](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/175054463/a5b2ce46-1afe-4f0a-9945-6e29da8e5d38)

**Comment by incomingnerd** [comment]
Just to check: Is this the intended recipe for the Refinery Controller in this pack?

If so, I'll simply burn the components and cheat in a controller. This is blocking my progression right now.

**Comment by Neddyfoeee** [comment]
yes, and thats what i ended up doing
