### ISSUE TITLE
EE4 Repair Talisman

### ISSUE THREAD

**Issue by GregsGirl04** [FTBTeam/FTB-Modpack-Issues#5455]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

The repair talisman is not repairing anything.  I have tried it with alchemical coal, all the different covalence dusts, glowstone and gunpowder to no avail. I've tried it in my inventory and in an alchemy bag with all said items.

### Steps to reproduce

Simply have the talisman and items that need to be repaired and see that nothing happens.

### Expected behaviour

I expected it to repair tools and gear per name of item suggests.

### Additional information

I apologize if this shouldn't be reported here. I have never reported anything before.

**Comment by littlebluepixel** [comment]
I believe you need a Klein Star with some EMC to use the talisman now.

**Comment by Saereth** [comment]
yep it needs energy to repair now from a klein star
