### ISSUE TITLE
Experience Pump upgrade from Sophisticated Backpacks just dont work.

### ISSUE THREAD

**Issue by Pandw4833** [FTBTeam/FTB-Modpack-Issues#5456]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

The tank upgrade with experience pump upgrade from Sophisticated backpacks, just doest work the way that to work. I think is because of  "experience" liquid from Sophisticated Backpacks, because i tried to put Fluid XP from MobGrindingUtils in the tank upgrade and the things worked again.

### Steps to reproduce

Get a backpack with Tank Upgrade and put de Experience Pump upgrade. Your XP gonna go to the tank upgrade and you cannot take the XP back, or use to repair mending items.

### Expected behaviour

I just want to use Experience Pump upgrade to repair my mending items agai,

### Screenshots

![imagem_2024-07-08_190213352](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/96796255/6a67c24f-9fa4-4834-9b74-332ebc5e1806)

**Comment by Saereth** [comment]
looks like the experience tag got removed from it mistakenly, should be fixed in next update
