### ISSUE TITLE
FTB NeoTech 1.3.0 - quest completes for wrong chicken when picking up 'xx' Chicken

### ISSUE THREAD

**Issue by 2ndRecon** [FTBTeam/FTB-Modpack-Issues#5457]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

When using the chicken tickler to pick up a chicken, the wrong type chicken is recorded in the Celebration pop-up as well as the quest tree. 

I picked up a Log Chicken with the Chicken Tickler, and the quest completed for 'sand' chicken. 

### Steps to reproduce

1.) Get the chicken whacker
2.) Go find a Log Chicken
3.) Pick it up with the chick-o-stik
4.) Note you have now completed the Sand Chicken quest.

### Expected behaviour

Quest completion should match the type of chicken you picked up. 

### Screenshots

![This-is-log](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/39180607/257665a3-f885-4392-94c0-9399d056705c)
![This-isnt-Log](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/39180607/3d1c0c19-5425-4135-a349-d4b9572372a3)

**Comment by Gaz492** [comment]
Wasnt able to replicate this by catching a log chicken, but when catching a regular minecraft chicken, I had this happen to me.

!skip
