### ISSUE TITLE
[Bug]: Woot EXP shards do not have a compacting drawer recipe.

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#546]
### Modpack

FTB University 1.16.5

### Modpack version

1.4.0

### Describe the bug

Despite combining 9 lesser to 1 normal shard in the standard ingot to block way, the woot shards do not do so in a compacting drawer.

### Steps to reproduce

Put woot exp shards in the compacting drawer

### Expected behaviour

shards combine

**Comment by aaronhowser1** [comment]
You cannot uncraft 1 Shard into 9 Splinters, which is a requirement.
