### ISSUE TITLE
Integrate JAOPCA in FTB Revelation

### ISSUE THREAD

**Issue by Margatroidu** [FTBTeam/FTB-Modpack-Issues#5462]
### Modpack

FTB Revelation

### Is your suggestion related to a problem? Please describe.

When I put this mod myself, the game crashes

### Mod suggestion

Please integrate [JAOPCA ](https://www.curseforge.com/minecraft/mc-mods/jaopca) mod

**Comment by Margatroidu** [comment]
> Due to the age of the modpack, we currently have no plans on adding any additional mods to the modpack.

In that case can you tell me how I can make the modpack run with JAOPCA myself. I really need this mod, so I would appreciate it

Crash report:
[crash-2024-07-06_20.52.12-client.txt](https://github.com/user-attachments/files/16168227/crash-2024-07-06_20.52.12-client.txt)

**Comment by Gaz492** [comment]
The crash report is saying that 2 recipes are conflicting with each other, im not entirely sure how you would fix this, judging by the crash report you will need to edit line 180 of the ic2 config.

**Comment by Margatroidu** [comment]
I'll try changing config, thanks

**Comment by Margatroidu** [comment]
I've solved that problem. If you are interested, see here - https://github.com/TheLMiffy1111/JAOPCA/issues/309#issuecomment-2224073147
