### ISSUE TITLE
Coke Brick are now uncraftable.

### ISSUE THREAD

**Issue by Seroku03** [FTBTeam/FTB-Modpack-Issues#5467]
### Modpack

FTB NeoTech

### Modpack version

1.4.0

### Has the pack been modified

No

### Describe the bug

The recipe for coke bricks is no longer available.
You were previously able to craft coke brick (If memory serves me right, it was brick dust and clay) but now you can't.

### Steps to reproduce

1. Open the Game
2. Look for the recipe on EMI
3. There is non to craft *Coke Bricks*

### Expected behaviour

To be able to craft coke brick, not only to progress the quest but to make Coke Ovens at will.

### Screenshots

![2024-07-11_02 20 37](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/1488b883-1b0d-4164-b6cb-e46f07350c2d)
![2024-07-11_02 20 39](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/600f3e37-303c-4d2d-9f0d-9c290a354c93)
![2024-07-11_02 20 48](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/a7b0eb93-120d-4644-abd1-3e663701c0e7)
![2024-07-11_02 23 23](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/97684065/0dd73623-6f9f-459a-a22a-7ddb57fd1103)

**Comment by Gaz492** [comment]
Compared 1.3.0 and 1.4.0, you were able to smelt bricks into coke bricks in 1.3.0, but that recipe looks to have vanished now.
