### ISSUE TITLE
Dusts recipies for Mixer randomly disappear

### ISSUE THREAD

**Issue by Maetnicio** [FTBTeam/FTB-Modpack-Issues#5469]
### Modpack

FTB NeoTech

### Modpack version

1.4.1

### Has the pack been modified

No

### Describe the bug

After the last update 1.4.1 there is no way to see dust recipies in EMI nor using U key on any inventory, mixer icon disappeared and recipies using dust are broken
Closing both game and luncher then restarting don't solve the issue, it simply change the outcome at some point (screenshots from 2 different sessions with multiple items)

### Steps to reproduce

1. Use 1.4.1
2. Launch the game
3. Play a world
4. Press U on any dust or right click on EMI recipies
5. Sometimes Dust will not appear correctly, mixer page may not be present

### Expected behaviour

Most dust recipies should be present

### Screenshots

![2024-07-11_22 13 32](https://github.com/user-attachments/assets/08b3ff20-df9e-4dc7-8774-a2fa178d2bbc)
![2024-07-11_22 20 38](https://github.com/user-attachments/assets/825e2473-9dd0-4ea7-9c13-a94417087e1e)
![2024-07-11_22 24 05](https://github.com/user-attachments/assets/82890a02-d45a-4fd5-ac96-8443746a6551)
![2024-07-11_22 24 09](https://github.com/user-attachments/assets/a322b28a-3817-4ff2-b003-f3e77cb1736b)
![2024-07-11_22 24 14](https://github.com/user-attachments/assets/cd5aed8d-34eb-4b90-8754-4fc8fbefbe28)

**Comment by Maetnicio** [comment]
After some gameplay it seems that the bug doesn't only apply to dusts but also to other component, i won't add more informations as the issue is exactly the same: EMI crafting guide with U key or search and right click, craft appearing with random holes in random places mostly on modded machinery.

**Comment by Maetnicio** [comment]
For some reason the recipies work some times, doesn't other times, depends of how the game lunched

**Comment by Saereth** [comment]
This appears to be some kind of race condition, possibly from kubejs, all you can do for now is relaunch or /reload until a better resolution can be found

**Comment by Maetnicio** [comment]
restarting the game works so i will stick with that solution

**Comment by Seroku03** [comment]
It used to happen to me.
On the FTB Launcher, there is the option of "Repair" on Settings
Doing that and re-entering, helps.

**Comment by Saereth** [comment]
yeah seems we cant reliably reproduce this but reinstall or the /reload command usually fixes it for peope that have been able to reproduce this so im gonna mark this closed for now unless we can reproduce more directly
