### ISSUE TITLE
[Suggestion]: Mod suggestion: iron furnaces

### ISSUE THREAD

**Issue by legomax2000** [FTBTeam/FTB-Modpack-Issues#547]
### Modpack

FTB Oceanblock

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/iron-furnaces
I am always looking for a good faster furnace and seem to find the iron furnaces mod the fastest and best for automation with its wireless heat system. I just love this system and im kinda missing it in the pack.

**Comment by Sunekaer** [comment]
Thanks for the suggestion but we are not looking to add more mods.
