### ISSUE TITLE
Thermopneumatic processing plant recipes still broken

### ISSUE THREAD

**Issue by jonasclaes** [FTBTeam/FTB-Modpack-Issues#5470]
### Modpack

FTB NeoTech

### Modpack version

1.4.1

### Has the pack been modified

No

### Describe the bug

Thermopneumatic plant recipe for Diesel -> Kerosene not working in 1.4.1 update despite all requirements being met (Temp >= 300C, Pressure > 2.0 bar) as per EMI. Plant gives error that there are no valid ingredients.

### Steps to reproduce

1. Input MI Diesel into TPP
2. Provide TPP with sufficient heat and pressure

### Expected behaviour

Diesel starts processing to Kerosene

### Screenshots

![image](https://github.com/user-attachments/assets/21693f84-20aa-4858-a762-f45fc7d74469)

### Additional information

It now works for Gasoline to LPG, but not for Diesel to Kerosine.

**Comment by jonasclaes** [comment]
Related to #5466 and #5441.

**Comment by Saereth** [comment]
Diesel to kerosene isnt a supported recipe in this pack, it should not even show as a valid recipe since the diesel input is going to trying to execute the diesel boosting recipe. Can you verify that diesel->kerosene shows in EMI as a valid recipe? Might have not gotten properly removed

**Comment by NinjasInMyBasement** [comment]
Im not the original poster, but I have confirmed on a brand new install of version 1.4.1 Diesel -> Kerosene is a valid recipe in EMI.

**Comment by jonasclaes** [comment]
@Saereth, I can confirm this is a valid EMI recipe. I can also give some extra info about that though.

It shows up as Diesel to Kerosene.
There is another EMI recipe, that does indeed do the boosted diesel if I recall correctly, however, that recipe needs an extra item to work. I'm currently at work, but I can check later today if required. (CEST)
