### ISSUE TITLE
NeoTech crash on startup

### ISSUE THREAD

**Issue by B3rt3** [FTBTeam/FTB-Modpack-Issues#5471]
### Modpack

FTB NeoTech

### Modpack version

1.4.1

### Has the pack been modified

No

### Log Files

removed

### Describe the bug

Modpack fails to startup, tried versions: 1.4.1, 1.4.0, 1.3.0

### Steps to reproduce

Try to launch NeoTech from the FTB launcher (launcher  version 1.25.14)

### Expected behaviour

launch game :)

**Comment by Gaz492** [comment]
It looks like you are running into a known crash caused by either outdated AMD graphics drivers or faulty drivers.
I would recommend making sure that your AMD graphics drivers are up-to-date and if they are up-to-date, to try reinstalling them.

**Comment by B3rt3** [comment]
Did the whole AMD Adrenaline Edition update. The console still gave lots of errors (i know nothing about this level of programming, probably showing errors and then fixes them) but the game runs now, thanks alot! 😌
