### ISSUE TITLE
Thermoneumatic Processing Plant doesnt work with LPG

### ISSUE THREAD

**Issue by Aerei011** [FTBTeam/FTB-Modpack-Issues#5472]
### Modpack

FTB NeoTech

### Modpack version

4.1 

### Has the pack been modified

No

### Describe the bug

When you try to insert LPG in the Thermoneumatic processing Plant doesn't let you despite other recipes work like the Kerosene to Gasoline.
Its not a problem with the recipe, even dont let you to introduce the LPG.

### Steps to reproduce

1. Try to introduce LPG in the TPP via Tanks, buckets, fluid pipes etc
2. It doesnt works

### Expected behaviour

The LPG should be enter in the LPG and make Raw biodiesel as the older versions.

### Screenshots

![IMG-20240712-WA0000](https://github.com/user-attachments/assets/ac9ed5bb-496c-4438-94dc-acdee30d9b56)
![IMG-20240712-WA0001](https://github.com/user-attachments/assets/71c971e1-7420-486a-88c7-a3a2ad8d4a07)

**Comment by DinnerBeef** [comment]
Unable to reproduce this, issue. Please reopen if you are still having issues with this. Try reinstalling the modpack to see if that fixes it.

**Comment by rockyoros** [comment]
I also have had this same issue and can’t figure it out the lpg can not go into plant with pipes or buckets or anything just says missing ingredients, kerosine was also and issue but that one just got fixed

**Comment by rockyoros** [comment]
> Unable to reproduce this, issue. Please reopen if you are still having issues with this. Try reinstalling the modpack to see if that fixes it.

- just relaunched for second time and it’s working, weird how relaunching always fixes everything with this pack

**Comment by rockyoros** [comment]
> > Unable to reproduce this, issue. Please reopen if you are still having issues with this. Try reinstalling the modpack to see if that fixes it.
> 
> * just relaunched for second time and it’s working, weird how relaunching always fixes everything with this pack

- they really need to fix this mod tho, keeps messing up with the automation on different steps rn it’s making lfg and getting stuck with 60mb in it and now I got a weird glitch that’s it’s running by itself even if I move it making like 20mb of vegetable oil with nothing in it

**Comment by xxhertz** [comment]
TPP automation has been an absolute nightmare in this pack. bump 2 years later had this exact issue of it randomly not working and relaunching/reopening world fixing it sometimes and sometimes breaking it. security upgrades also just dont work anytime i relaunch the world, 2 of my 8 tpps work ever, genuinely such a headache
