### ISSUE TITLE
Add EMC to Smithing Templates

### ISSUE THREAD

**Issue by Joprebond** [FTBTeam/FTB-Modpack-Issues#5474]
### Modpack

FTB NeoTech

### Is your suggestion related to a problem? Please describe.

Add EMC to the smithing templates. Most of them are easily able to be copied. For Example Netherite template is 7 diamonds + 1 nether rack.

**Comment by Saereth** [comment]
this is not working with the emc json configs so we've passed it along to giga to try and implement within ee itself
