### ISSUE TITLE
Immersive engineering posts get duped when hammered then broken

### ISSUE THREAD

**Issue by bobuxman61** [FTBTeam/FTB-Modpack-Issues#5475]
### Modpack

FTB NeoTech

### Modpack version

1.4.1

### Has the pack been modified

No

### Describe the bug

Immersive engineering poles get duped when you break its extra arms in survival mode. Game recognizes the arm as other posts and you get an extra post despite the original post not being broken. Hammering the post requires no resources so the post gets duped.

### Steps to reproduce

1. place down any immersive enginnering post
2. use enginners hammer on it to get arms
3. break the arms in survival mode

### Expected behaviour

Breaking the posts arms should not give you any items.

### Additional information

you gotta hammer the top block

![bast](https://github.com/user-attachments/assets/ecdac6e5-a413-4d6a-b2c2-1139d389f2c2)
 then break the part that extends forward

![basting](https://github.com/user-attachments/assets/d4537105-0b93-4e7d-9cfe-b8cd1c83d498)

**Comment by Gaz492** [comment]
BluSunrize/ImmersiveEngineering/issues/6015

!skip

**Comment by Saereth** [comment]
marked fixed by bluesunrize but no mod update yet
