### ISSUE TITLE
Transmutation Table Bugs out with some items and does EMC dupe

### ISSUE THREAD

**Issue by Libery-Fogel** [FTBTeam/FTB-Modpack-Issues#5476]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

When Adding some items to the table(and tablet also) I'm not able to take any item out afterwards. As I play on a server I reconnect and the item in question is gone from the table and from the inventory. The EMC are rolled back some seconds/minutes?

So far I had that problem with the nether star and the anvil.

For replication I took out all 14  Million EMC and droped the anvil in. Table broke, I reconnected and had lost the anvil but again 14 million EMC in the table. And still the dark matter in the inventory from clearing out the EMC.

### Steps to reproduce

1. Open Transmutation table
2. Insert an anvil or nether star
3. try to take out anything at all

### Expected behaviour

Table doesn't break

**Comment by Gaz492** [comment]
Is this still an issue for you on the latest version of the modpack (1.4.1)?

**Comment by Libery-Fogel** [comment]
Update to 1.4.1:
Issue got resolved for that problem, new and different problem did appear. But the table not working with the items got resolved
