### ISSUE TITLE
Transmutation table picking item like a chest

### ISSUE THREAD

**Issue by Libery-Fogel** [FTBTeam/FTB-Modpack-Issues#5477]
### Modpack

FTB NeoTech

### Modpack version

1.4.1

### Has the pack been modified

No

### Describe the bug

When picking an item out of the transmutation table you litterally pick it out. Like you would out of a chest. The item you get, EMC goes down, the item vanishes from the table. Until you refresh the GUI (search or re-opening), then the item is there again and you can pick it again once.

### Steps to reproduce

1. Open transmutation table
2. pick any item
3. Have an empty spot where that item was picked out

### Expected behaviour

Item is there to pick again directly by left clickin it

### Additional information

Shift-clicking a full stack out of the table does work, item does stay visable and pickable

**Comment by Gaz492** [comment]
https://github.com/FTBTeam/Equivalent-Exchange/issues/11
