### ISSUE TITLE
[Bug]: Magical herbs trinket is not available via loot

### ISSUE THREAD

**Issue by cosmosgenius** [FTBTeam/FTB-Modpack-Issues#548]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Describe the bug

Magical herbs trinket is not available via loot. Not sure if this was intended or not. Seeing that swimming kubejs code  has dependency on Magical herbs it felt like a miss.

### Steps to reproduce

1. Open magical herbs in JEI
2. See that its not part of any loots

### Expected behaviour

magical herbs trinket to be part of loots.

**Comment by Raidobw2** [comment]
I'll check with the modpack dev, that might have been a reworked feature that was never added back. I'll add more info here when I get some, thanks for staying around.
