### ISSUE TITLE
Ftb one server crash on player join

### ISSUE THREAD

**Issue by daywalker90** [FTBTeam/FTB-Modpack-Issues#5480]
### Modpack

FTB One

### Modpack version

2.8.3

### Has the pack been modified

No

### Log Files

https://pste.ch/waxucexoti.pl

### Describe the bug

When a specific player joins on the server, the server sometimes crashes, no idea why. The base isn't even that big or crazy. After a restart everyone could join again without a crash. Happened 3 times already.

### Steps to reproduce

- Join server
- Server crashes sometimes

### Expected behaviour

no crash on join

**Comment by Gaz492** [comment]
The crashreport shows that the server watchdog stopped the server, as for why it did this is not clear as the log only mentions minecraft itself.
What you could try doing is setting the `max-tick-time` option in the server.properties file to `-1`, this will disable the watchdog from stopping your server if a tick takes too long. However, this is more of a hack than an actual fix, where you might get timed out from the server or experience severe lag.

**Comment by daywalker90** [comment]
I see, thanks for your quick reply
