### ISSUE TITLE
FTB NeoTech crash

### ISSUE THREAD

**Issue by AudeyQuebec** [FTBTeam/FTB-Modpack-Issues#5481]
### Modpack

FTB NeoTech

### Modpack version

1,4,2

### Has the pack been modified

No

### Log Files

This one is when i was loading into a new world.
[hs_err_pid5728.log](https://pste.me/@Z1NW32GMfPw)

This one is when i was trying to open the Modpack.
[hs_err_pid11248.log](https://pste.me/@sCvrTBYQDt4)

### Describe the bug

Hello !

When i first played the modpack, it worked beautifully ! I didn't like the world i was in, so i decided to make a different world. When i tried to load into this new world, my game whole pc crashed. 
Ever since then, my game has been crashing non-stop, either while opening the modpack, or while trying to get in a world. Sometimes, not only the game crashes, but my whole PC crashes too. It gives me a blue screen and my PC restart automatically. 

It happened the first time with version 1.4.1 and since tried the version 1.4.2 and it hasn't change much. I also tried to delete the modpack and reinstall it, it didn't work. I tried also to repair it, you can also get the outcome. 

I'm kinda sad about it because the little bit i played of it, i actually enjoyed the modpack, but now, i do not get to play it at all. :( 

**EDIT**
_I uninstalled the FTB launcher and nothing changed. I changed my RAM setting from DDR4-3200 back to DDR4-2800 (my bf changed it not long ago) and it seems to have helped my pc from crashing entierely, but the modpack still crash, but now it happens a short while after i start playing in my world._

### Steps to reproduce

1. Click on play to start the Modpack (sometimes it crashes there)
2.  If no crash, create a new world and load it up (it also crashes there)
3. If no crash, quit the world and go back into World creation. 
4. Delete the old world.
5. create a new world and load it up (should crash)

### Expected behaviour

Game or pc crash

**Comment by Gaz492** [comment]
Does this happen to other modpacks you play?

The error you are getting is common with either a software issue or hardware issue.

**Comment by AudeyQuebec** [comment]
This happened to all modpacks i played and also with plain minecraft vanilla. 
I was able to fix it by resetting my whole pc (redownload Windows and empty my SSD and hard drive).
I still don't know what caused the problem since everything was up to date before that and and uninstall everything Minecraft related and it still didn't help.

**Comment by Saereth** [comment]
This isnt a pack issue specifically so closing it out, glad you got your system sorted!
