### ISSUE TITLE
Volcanite Amulet doesn't work in FTB NeoTech

### ISSUE THREAD

**Issue by Git-Schlauch** [FTBTeam/FTB-Modpack-Issues#5488]
### Modpack

FTB NeoTech

### Modpack version

1.3.0

### Has the pack been modified

No

### Describe the bug

The Volcanite Amulet from Equivalent Exchange 4 does not work. Neither abilities nor lava walking in the nether.
At least from what I read here: https://technicpack.fandom.com/wiki/Volcanite_Amulet don't know if this is up to date.

### Steps to reproduce

Craft item and test its abilities.

### Expected behaviour

Working abilities and features of the item

**Comment by Gaz492** [comment]
Is this still an issue for you on the latest version of the modpack?
If you are, would you be able to upload new log files for us so we can take a further look?

**Comment by Git-Schlauch** [comment]
I just tied it on my server with version 1.4.2. I still took damage.
If I may ask what kind of log files do you need?
From the server or client?

**Comment by Saereth** [comment]
This amulent now requires EMC in the form of a klein star in your inventory to funciton
