### ISSUE TITLE
[Bug]: Mekanism ore tripling inconsistent among ores

### ISSUE THREAD

**Issue by LittleChronic** [FTBTeam/FTB-Modpack-Issues#549]
### Modpack

FTB Direwolf20

### Modpack version

1.13.0

### Describe the bug

Nickel and silver ore cannot be duplicated more than twice with Mekanism. As in you cannot triple ore using the purification station or quadruple it with chemical injection chamber or quintuple using chemical crystallizer.

### Steps to reproduce

1. Put any other ore than nickel and silver into the purification station and it process it. 
2. Nickel and silver ore does not even input into the purification station.

### Expected behaviour

For nickel and silver to be used with all of Mekanisms machines as intended.

**Comment by LittleChronic** [comment]
Just noticed it's the same with the following:

Tinker's construct
* Cobalt ore

Undergarden
* Regalium ore
* Utherium ore
* Froststeel ore
* Cloggium ore

Rats
* Oratchalcum Ore

Powah
* Uraninite Ore

MythicBotany
* Elementium Ore

Immersive Engineering
* Bauxite Ore

Create
* Zinc Ore

Astral Sorcery
* Starmetal Ore

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
