### ISSUE TITLE
Invisible block when placing certains fluids with the mekanism tank in bucket mode

### ISSUE THREAD

**Issue by squyrrel27** [FTBTeam/FTB-Modpack-Issues#5490]
### Modpack

FTB NeoTech

### Modpack version

1.4.2

### Has the pack been modified

No

### Describe the bug

When using the mekanis fluid tanks in "bucket mode", players can place a fluid block for fluids that don't have a corresponding fluid block. So, the placed block is an invisible block.

### Steps to reproduce

1. Fill mekanism tank w/ a fluid/gas that doesn't have a world block
2. Switch tank to "bucket mode"
3. Shift-Click to place block
4. Notice the transparent block

### Expected behaviour

Either no action at all, or a fluid if one exists

### Screenshots

![image](https://github.com/user-attachments/assets/c99aeb48-7126-4261-9a9f-2aef20415891)

**Comment by Saereth** [comment]
verified, will report to mekanism

**Comment by Saereth** [comment]
https://github.com/mekanism/Mekanism/issues/8168
marked as no longer supported already... oof dunno if we'll see a fix for this one

**Comment by squyrrel27** [comment]
Ah well, at least it's not really a game breaking bug.

I got another weird Mek one when ready, though I gotta test on the newest modpack version first.
