### ISSUE TITLE
Hardcrash to desktop after looking at a LaserIO Laser Node using the zoom feature

### ISSUE THREAD

**Issue by senic35** [FTBTeam/FTB-Modpack-Issues#5491]
### Modpack

FTB NeoTech

### Modpack version

1.4.1

### Has the pack been modified

No

### Log Files

[crash-2024-07-14_00.23.24-client.txt](https://github.com/user-attachments/files/16203827/crash-2024-07-14_00.23.24-client.txt)

### Describe the bug

After looking at a LaserIO Laser Node with the 'c'-key the game hard-crashes to desktop.

### Steps to reproduce

1. Place down a LaserIO Laser Node
2. Press C to look at it while still in interaction range
3. Game crashes to desktop

### Expected behaviour

Simply zooming in while not crashing the game

**Comment by Saereth** [comment]
This is actually sophisticated storage causing the crash. You can unbing the Run inventory interaction ugprades key from that key and it should solve the issue until SS can fix it on their end

**Comment by Saereth** [comment]
https://github.com/P3pp3rF1y/SophisticatedStorage/issues/447

**Comment by Saereth** [comment]
direwolf wont fix this so I guess just dont use that keybind while looking at the laserio node. He's fixing it in newer versions of the mod 1.21+
