### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) - FTB Inferno

### ISSUE THREAD

**Issue by tmeuschel** [FTBTeam/FTB-Modpack-Issues#5497]
### Modpack

FTB Inferno

### Modpack version

1.0.1 1.9.1 and 1.10.0

### Has the pack been modified

No

### Describe the bug

Hello,
I've been trying to run FTB Inferno on my pc (windows 10, Intel Arc A770 gpu) for this entire day now. I have researched this problem multiple times (finding only dead ends where both developers and intel just give up on people). I can accurately gauge the problem where there is an incompatibility with the modpack and my graphics card. On one side people keep on recommending I update my driver (which I have extensively in multiple different ways [even reinstalling windows]). The only useful bit of information I got was from intel graphics card forums saying that it might be the game developers who don't account for this type of gpu, and seeing FTB Inferno is a little niche compared to most games (and that the latest update happened 7 months ago) I thought it'd be useful to write this in hopes to garner some attention towards this issue. 

Other people like grencham has this issue go unresolved in the past as-well https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2529. 

*Reminder that I have reinstalled windows, graphics drivers, jdk runtime (seeing if my computer was missing a library), and removing bloatware (because I had to reinstall windows) 

*Also my friends who have FTB App downloaded it on their devices and are able to play the modpack without any complication (we just started using this modpack; so that doesn't really mean much except that they can start the modpack except me). 

The error appears like this on my side as well. 

A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa14b761ba, pid=6800, tid=13024
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [igdgmm64.dll+0x3561ba]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows

I can upload the log file if people wanted it, but at this time please contact me directly for that info. 

From
tmeuschel

### Steps to reproduce

1.Install/open FTB App
2.Download the FTB Inferno Modpack
3.Start the Modpack

> IF you have an intel arc A770 (specific to my case)
4. You will receive the error listed above

### Expected behaviour

To have a working modpack

### Screenshots

No. I would like to see if there is any personal info on there before uploading

### Additional information

Email me for more specific info

**Comment by Gaz492** [comment]
It looks like your graphics drivers may be out of date, the crash you are running into is commonly seen when your graphics drivers are out of date or if you are on a laptop with an integrated graphics and a dedicated graphics card, the modpack may be using the wrong graphics card.

To begin with, we recommend making sure that your graphics drivers are up-to-date by downloading the latest drivers from the manufacture's website.

**Comment by tmeuschel** [comment]
> It looks like your graphics drivers may be out of date, the crash you are running into is commonly seen when your graphics drivers are out of date or if you are on a laptop with an integrated graphics and a dedicated graphics card, the modpack may be using the wrong graphics card.
> 
> To begin with, we recommend making sure that your graphics drivers are up-to-date by downloading the latest drivers from the manufacture's website.


I have already downloaded the drivers from the specified gpu manufacturer. If it helps, I will post the specific drivers I used https://www.intel.com/content/www/us/en/products/sku/229151/intel-arc-a770-graphics-16gb/downloads.html. 

The reinstallation of windows I did was to make sure the intel arc drivers installed correctly (since any tampering with the drivers can result in errors and incorrect uninstallation can lead to software locks / faulty software)

**Comment by kirinon96** [comment]
Try reinstalling java and or try older versions? ya never know.

**Comment by AudeyQuebec** [comment]
i have the same issue and my graphics drivers are also up to date. i've had this happening to me on at least 2 different modpacks. I still don't have a solution for this, so i'm here now !

**Comment by tmeuschel** [comment]
### **Quick fix - Read Risks associated**

If you dedicate the instance (which in this case is the modpack) to run of a separate device like a cpu, the modpack would work since its using internal drivers. The issues, as I probably said before is the incompatibility gpu (for me its specifically for arc A770), and since a cpu can take care of gpu tasks (because gpus are specifically made for graphics computing, a cpu can do the same thing) I tried to find methods in which I can use solely my cpu. 

My method of doing this is that I forced one of my monitors to use the display port directly connected to the monitor (not the gpu) so windows / drivers associated with the display monitor would force use my cpu for calculations.
> Although for laptop users who join this thread I don't know how much my solution is, so

My recommended solution outside the one that worked for me is to find a software / windows solution to dedicating an app to run off of certain hardware on your computer (I wouldn't recommend doing this though so try at your own risk).


All things considered, this **issue is not resolved** and I'm pretty sure that its an FTB team bug that they need to fix because it clearly is not a driver problem for me and many others.

Risks:
> in my experience, running most of the calculations on a specified hardware like a cpu does not entirely help your computer since if you can divvy up the tasks being done at one time you get faster results (asynchronous functionality). This is the reason why parts of your computer are dedicated to certain stuff for example your gpu: both because it enables faster processing for hard to execute graphic mathematics and that it can run separately from your main processing device (cpu). So the expected problems to come from this is that it'll probably be laggy and have a possibility of easily overloading your cpu (depending on its strength)

Hope you have a great day
From
tmeuschel

**Comment by tmeuschel** [comment]
I still have tried with my gpu, running ftb_inferno and it didn't work. Will try different drivers for intel arc A770 if I get a chance, but I'm fine so far with the solution I have found so far.

**Comment by Gaz492** [comment]
Did this issue only happen on inferno or did it also happen to other modpacks/vanilla minecraft?
