### ISSUE TITLE
AE2 System not taking/giving 64 Items

### ISSUE THREAD

**Issue by Sanic69420** [FTBTeam/FTB-Modpack-Issues#5503]
### Modpack

FTB NeoTech

### Modpack version

1.4.2

### Has the pack been modified

No

### Describe the bug

When I want to add a stack of any itemor take a stack out from my AE2 ME System it doesnt take/give me 64 items but only 53.

### Steps to reproduce

1. Make an ME System with an Energy accepter
2. Add a storage Cell (any kind)
3. Try to put a stack in with Shift-Left click or take one out with Shift Left click

### Expected behaviour

It should only take/give 53 items and leave 11

**Comment by Saereth** [comment]
This happens when your system doesnt have enough internal energy to support the opertions, since power consumption is higher in this pack you'll need to add an energy cell onto your network to help buffer more power.
