### ISSUE TITLE
Flux Researcher Villager, need AE Charger has work station, but Charger recept is disable

### ISSUE THREAD

**Issue by crusender** [FTBTeam/FTB-Modpack-Issues#5506]
### Modpack

FTB NeoTech

### Modpack version

1.4.0

### Has the pack been modified

No

### Describe the bug

Villager Flux Researcher from Easy Villager mod need a AE Charger has work station, but the recept to craft the Charger is disable. 

### Steps to reproduce

1. Open EMI
2. Look at profession 
3. See that Flux Researcher need Charger

### Expected behaviour

the station should be craftable

### Screenshots

![2024-07-16_19 32 49](https://github.com/user-attachments/assets/33437c53-c4a1-4e7b-9bb2-6a8e42bc56b0)

**Comment by Saereth** [comment]
This is not a bug, this is intentional, you can only access its trades via the amadron network, randomly to limit endless certus and fluix trades before they would be attianable.
