### ISSUE TITLE
Mekanism tanks voiding content when mined

### ISSUE THREAD

**Issue by JayKevinMC** [FTBTeam/FTB-Modpack-Issues#5507]
### Modpack

FTB NeoTech

### Modpack version

1.4.2

### Has the pack been modified

No

### Describe the bug

when mining a mekanism tank under certain conditions, the tank will void the contents.
This is not a 100% occurring bug, but it does happen the majority of the time.

### Steps to reproduce

1. having an empty tank of the same kind in inventory
2. Mining the other tank with an AA drill, with silk touch augment

### Expected behaviour

The tank retain the contents

**Comment by Saereth** [comment]
we have several duplicates of this openinig, we're tracking it but closing the extras to make it easier, thanks for the report!
