### ISSUE TITLE
Atomic Dissassembler is not craftable

### ISSUE THREAD

**Issue by CzReloaded** [FTBTeam/FTB-Modpack-Issues#5509]
### Modpack

FTB Presents F.A.M

### Modpack version

1.1.1

### Has the pack been modified

No

### Describe the bug

The Atomic Dissassembler is not showing the crafting recipe even if the Leviathan is killed.

### Steps to reproduce

1. Go into inventory
2. Click on Atomic dissassembler in JEI
3. Recipe is not showing 

### Expected behaviour

I expected to see the crafting recipe after killing the leviathan

**Comment by Gaz492** [comment]
It looks like the recipe is intentionally disabled, but the tool tip saying it's unlocked after killing the leviathan didn't get removed.
!skip

**Comment by CzReloaded** [comment]
Okay, good to know, thank you!
