### ISSUE TITLE
FTB Builders Paradise 2 Keeps crashing on world start up

### ISSUE THREAD

**Issue by sidcaz** [FTBTeam/FTB-Modpack-Issues#5510]
### Modpack

FTB Builders Paradise 2

### Modpack version

1.1.0

### Has the pack been modified

No

### Log Files

[2024-07-18-1.log.gz](https://github.com/user-attachments/files/16277538/2024-07-18-1.log.gz)
[console.log](https://github.com/user-attachments/files/16277542/console.log)

### Describe the bug

Every time on world start up the mod crashes and my Minecraft does not respond. the modpack has not been updated and ive even reverted to old world saves in case i did anything game breaking. still nothing. Can anyone help?

### Steps to reproduce

1. start mod as usual
2. make sure its version 1.1.0
3. see if world will generate
4. if new world generates try an older world

### Expected behaviour

the game crashes as it loads the world

**Comment by Gaz492** [comment]
It looks like a hopper in your world is causing the issue, could you try changing the 2 settings mentioned in the guide below?
https://docs.feed-the-beast.com/docs/support/Troubleshooting/ticking-entities
