### ISSUE TITLE
Compact Machine Island unable to play

### ISSUE THREAD

**Issue by LouisOuellet** [FTBTeam/FTB-Modpack-Issues#5512]
### Modpack

FTB Skies

### Modpack version

1.6.0

### Has the pack been modified

Yes

### Describe the bug

[Issue #5214](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5214), still persist after latest update.

We still do not spawn with the tool required to enter the compact machine.

Starting a new world on this island, you receive a second copy of the quest book, some more bone meal and a second copy of the Akashic Tome.

Meaning you can essentially grab the compact machine and put the block in the world. But you can't enter it, you don't have any dirt to plant a sapling.

Note: Loaded an older save on a different island. The Quest "Starting Your Island" was reset and gave me the shrinking device. This should only be given on the compact machine map I believe.

### Steps to reproduce

Create Compact Machine Island in 1.6.0

### Expected behaviour

You should get items like shrinking device etc.

**Comment by Saereth** [comment]
This is not a bug, we now give the shrinking device out to everyone on that quest

**Comment by LouisOuellet** [comment]
> This is not a bug, we now give the shrinking device out to everyone on that quest

I think you missed a lot in the bug report. You may spawn with the quest giving out the shrinking device, but you can't do anything with nothing but a compact machine bone meal and some saplings. You can't plant those without dirt. Unless I missed something else. But when entering the compact machine, I am not getting anything else.

So still a Bug and this island is unplayable without cheat
