### ISSUE TITLE
game frezzing when going full screeen 

### ISSUE THREAD

**Issue by LostAstronaut175** [FTBTeam/FTB-Modpack-Issues#5513]
### Modpack

FTB NeoTech

### Modpack version

1.4.2

### Has the pack been modified

No

### Describe the bug

game starts fine in window mode as soon as i press f11 to go full screen screen frezzes but game still running  

### Steps to reproduce

1 start the game 
2 wait for it to load in window mode 
3 press f11 for it to freeze and the music anf game keeps loading but game screen dosent change 

### Expected behaviour

game should oppen full screen and not freeze

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by LostAstronaut175** [comment]
[latest.log](https://github.com/user-attachments/files/16325780/latest.log)

**Comment by LostAstronaut175** [comment]
[debug-5.log.gz](https://github.com/user-attachments/files/16325784/debug-5.log.gz)

**Comment by Saereth** [comment]
try disabling the ModernUI mod and see if the issue persists
