### ISSUE TITLE
Ars Noveau Launch Bug MacOS

### ISSUE THREAD

**Issue by sixwires** [FTBTeam/FTB-Modpack-Issues#5514]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Has the pack been modified

No

### Log Files

https://pste.ch/cecawipaca.md

### Describe the bug

The pack was working yesterday. All the sudden I can't get the pack to run?

### Steps to reproduce

Press launch on MacOS using FTB launcher

### Expected behaviour

Supposed to launch. It did yesterday

**Comment by Gaz492** [comment]
I've not been able to replicate this issue, could you try right-clicking on the modpack in the app, selecting settings then clicking on the repair button?

**Comment by sixwires** [comment]
> I've not been able to replicate this issue, could you try right-clicking on the modpack in the app, selecting settings then clicking on the repair button?

That didn't seem to fix it for me. I'm also seeing the error [mojang/narrator] Error while loading the narrator. Not sure if that has anything to do with it

**Comment by sixwires** [comment]
> I've not been able to replicate this issue, could you try right-clicking on the modpack in the app, selecting settings then clicking on the repair button?

That didn't work for me, however fully uninstalling and reinstalling seemed to do the trick
