### ISSUE TITLE
Thermoneumatic Proccesing plant

### ISSUE THREAD

**Issue by Drsnaki96** [FTBTeam/FTB-Modpack-Issues#5515]
### Modpack

FTB NeoTech

### Modpack version

1.4.2

### Has the pack been modified

No

### Describe the bug

Can not input virulent mix into the themopneumatic proccesing plant (TPP).
Tried inputing with:
-buckets
-mekanism mekanical pipe
-bucketing with mekanism tanks
-dispenser upgrade in pneumaticraft tank
-dimensional tank with eject mode on

In addition, i can not bucket the virulent mix back in a tank.

Sometimes on the first launch of the world after the first load I can insert the virulent mix in the TPP but the TPP is also making vegetable oil WITHOUT any items in it.

### Steps to reproduce

Place thermopneumatic proccesing plant (TPP)
Try to bucket virulent mix in th TPP

### Expected behaviour

Be able to input virulent mix in the thermopneumatic proccesign plant

### Additional information

All recipies from crude oil and forward are fine

I have been uptating the tank since 1.2 with the FTB launcher

**Comment by cchinchole** [comment]
I started playing as of the 1.6 release and was still seeing this issue, could not pipe virulent mix into the Thermopneumatic plant. Downgrading to version 1.3 (original version reporting the fix), then loading a  copied world from 1.6, I saw it worked. I proceeded to load this on 1.6 where it continued to work. I did not change any configuration during this process, is there something missing in 1.6 causing this?

**Comment by TWNateLo** [comment]
This is still a bug, i tried the datapack method but it is still the same. Please assist :)

<img width="1915" height="1032" alt="Image" src="https://github.com/user-attachments/assets/60eccf6a-0225-4ce8-82d3-6f5d42db2fe4" />

<img width="1918" height="1030" alt="Image" src="https://github.com/user-attachments/assets/2f11c447-bf16-4396-84ee-bf8a3d99a8ea" />

Cannot put virulent mix into any type of tank, thermopneumatic proccesign plant etc.

**Comment by mathert12** [comment]
You need to add the recipes attached to the pneumatic craft recipes, you also need to destroy any liquid attained previously for this to work.

[pneumaticcraft_fuel_recipes.zip](https://github.com/user-attachments/files/24719346/pneumaticcraft_fuel_recipes.zip)
