### ISSUE TITLE
No Mouse 

### ISSUE THREAD

**Issue by Jeanrealty** [FTBTeam/FTB-Modpack-Issues#5516]
### Modpack

FTB StoneBlock 2

### Modpack version

1.23.0

### Has the pack been modified

No

### Log Files

[debug.log](https://github.com/user-attachments/files/16310861/debug.log)

### Describe the bug

When launching the Game it starts in windowed mode then when i switch to fullscreen it removes my mouse cursor 

### Steps to reproduce

Launch game
make full screen

### Expected behaviour

mouse should just disappears but still works but can see it 

### Screenshots

![image](https://github.com/user-attachments/assets/e460e338-d82f-4b5d-8c73-0f9b6d200afc)

**Comment by Gaz492** [comment]
Ive not been able to reproduce this issue, if you alt + tab out of the game and back in does your mouse re-appear?
