### ISSUE TITLE
Stone block 3 crash then can't open.

### ISSUE THREAD

**Issue by DoubleSR7410** [FTBTeam/FTB-Modpack-Issues#5519]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Has the pack been modified

No

### Log Files

[crash-2024-07-20_19.27.39-client.txt](https://github.com/user-attachments/files/16321099/crash-2024-07-20_19.27.39-client.txt)

### Describe the bug

i can't open stone block 3 is crash every time
last hour it not yet crash
When crash then can't open it again

### Steps to reproduce

open it 

### Expected behaviour

maybe some mod crash but i don't know

**Comment by Gaz492** [comment]
Could you try disabling the minetogether mod and see if the pack starts up for you?

**Comment by DoubleSR7410** [comment]
@Gaz492 Thank You!!! it work
