### ISSUE TITLE
[Bug]: mekanism cardboard box crash

### ISSUE THREAD

**Issue by hachiimann** [FTBTeam/FTB-Modpack-Issues#552]
### Modpack

direwolf 20 1.16

### Modpack version

1.13.0

### Log Files

[crash-2022-01-09_18.12.53-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7836265/crash-2022-01-09_18.12.53-client.txt)
![crashlog](https://user-images.githubusercontent.com/89705856/148706899-a3017f8b-86ce-4fa5-a678-cd38b2bc79dd.JPG)

### Describe the bug

whenever you attempt to put a cardboard box over a spawner to transport it the game saves and the client crashes.

### Steps to reproduce

1: find spawner
2: click on spawner with cardboard box in hand

### Expected behaviour

should cover spawner and be able to be broken and drop box with spawner inside

**Comment by Raidobw2** [comment]
Should be fixed in the hotfix 1.13.1, if not let me know
