### ISSUE TITLE
neotech mod addition: just a battery

### ISSUE THREAD

**Issue by pikminman13** [FTBTeam/FTB-Modpack-Issues#5521]
### Modpack

FTB NeoTech

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/justabattery

Given that the battery options available aren't overly high, I would recommend adding in larger forms of personal energy storage.

Unfortunately, AA batteries are not configurable and MI batteries don't work as portable power storage.

**Comment by Saereth** [comment]
after some thought and testing I think between the aa batteries and personal generator from just dire things the remote energy storage options are about where I'd like to keep them presently
