### ISSUE TITLE
Electric Mixer is bugged with recipes using SAND and the machines used for this bugs afterwards.

### ISSUE THREAD

**Issue by Jauzs** [FTBTeam/FTB-Modpack-Issues#5527]
### Modpack

FTB NeoTech

### Modpack version

1.4.2

### Has the pack been modified

No

### Log Files

N/A

### Describe the bug

When a recipe is used with sand in the Electric Mixer. It puts it the wrong amounts of sand. I tried this with Industrial TNT. Afterwards these machines does not work with any other recipes it seems. They bug out in some way. It's quite strange.

### Steps to reproduce

Electric Mixer - Industrial TNT recipe from a pattern provider - It puts in to little sand. - Machine is broken afterwards.

### Expected behaviour

There should be enough sand to make whatever was requested.

### Screenshots

N/A

### Additional information

N/A

**Comment by Saereth** [comment]
this should be fixed now in the 1.5.0 udpate, tested in my dev instance and could no longer reproduce
