### ISSUE TITLE
Enchanted blocks cross mod incompatablity

### ISSUE THREAD

**Issue by Ozimundis** [FTBTeam/FTB-Modpack-Issues#5529]
### Modpack

FTB NeoTech

### Modpack version

1.4.2

### Has the pack been modified

Yes

### Describe the bug

Enchants like "Boiling III" applied to Magma Blocks make them invalid heat sources for pneumaticcraft. Blocks will not transmit heat to either Refinery controllers, TPP's or heat pipes. 

Unsure if Intended behavor, or misunderstanding on my part about intended purpose of the addional enchants.

*Pack is modified with "Decorative Blocks" mod - All testing done with mod disabled. 

### Steps to reproduce

Craft/Find Blocks with applicable enchants

Place adjacent to Heat sensitive blocks

See lack of interaction compared to unenchanted counterparts

### Expected behaviour

Enchanted blocks with boiling would add additional heat at the cost of lifespan/Heat management

### Screenshots

![2024-07-22_17 00 55](https://github.com/user-attachments/assets/61a07268-a547-45bc-995a-82e58828e1e8)
Both Magma blocks on left enchanted with Boiling 3, block on right unenchanted

**Comment by Saereth** [comment]
We have already reached out to bysco for more mod cross compatibility options, this will be up to him in the future and isnt something we can control on a pack level
