### ISSUE TITLE
Nei not working

### ISSUE THREAD

**Issue by Keodra** [FTBTeam/FTB-Modpack-Issues#553]
### Modpack

FTB Lite

### Modpack version

1.2.3

### Describe the bug

I'm playing FTB Lite and my problem is that the Nei mod is not working. It says there are no installed plugins for this mod.

### Steps to reproduce

1. Open FTB Lite in minecraft
2. Forge Mods
3. NEI

### Expected behaviour

Please solve my problem

**Comment by Raidobw2** [comment]
Hello, there is a bug with NEI and the vanilla launcher in 1.4.7. You will need to add the coremod "Vanilla NEI Fix" into your game's `coremods` folder to solve this.

You can get the mod from the CurseForge page: https://www.curseforge.com/minecraft/mc-mods/vanilla-nei-fix.
There is a Files tab where you can get the file.

In the FTB App you can navigate to the modpack page and click on Settings. Then scroll down and click Open Folder.
You need to add the mod to the `coremods` folder, and only that folder. Other folders won't work.

Then load the game and the problem will be resolved, NEI will be shown again.
Cheers.

**Comment by Raidobw2** [comment]
I'll update the modpack when I get the time, reopening for our records and also so I can remind me about it.
