### ISSUE TITLE
items and empty hand change in function on load occasionally

### ISSUE THREAD

**Issue by pikminman13** [FTBTeam/FTB-Modpack-Issues#5532]
### Modpack

FTB NeoTech

### Modpack version

1.4.2

### Has the pack been modified

No

### Describe the bug

In my experience, on load, I have sometimes had issues where my empty hand was acting as a Wrench (MI). I have also heard instances of the Steam Mining Drill acting as an axe.

### Steps to reproduce

Load the world and on occasion this bug might occur. No known consistent way to trigger it.

### Expected behaviour

Functional tools doing their own job

### Screenshots

![image](https://github.com/user-attachments/assets/4bf2567d-daf4-4a76-8228-3b935c5fe735)

note the harvestability in this image

**Comment by Saereth** [comment]
this seems to be a tag loading issue, potentially a race condition present in kjs, kjs and mi both got updates for 1.5.0 though so let me know if its persistent then, I cant reproduce it presently in my dev instance now

**Comment by 630R63** [comment]
I can confirm it just happened to me in version 1.6 of the pack
