### ISSUE TITLE
Crash on startup (MI Tweaks)

### ISSUE THREAD

**Issue by Draylynn** [FTBTeam/FTB-Modpack-Issues#5534]
### Modpack

FTB NeoTech

### Modpack version

1.5.0

### Has the pack been modified

No

### Log Files

[crash-2024-07-25_00.31.54-fml.txt](https://github.com/user-attachments/files/16368868/crash-2024-07-25_00.31.54-fml.txt)
[debug-1.log](https://github.com/user-attachments/files/16368869/debug-1.log)

### Describe the bug

Server installs of FTB NeoTech 1.5.0 are crashing on startup with an error that MI Tweaks is attempting to load client side code that is unsuitable for server distribution.

### Steps to reproduce

Install 1.5.0 NeoTech build server files, run them... Crash.

### Expected behaviour

Start server, fully load, login, play, no crash.

### Additional information

AlmaLinux OS 9.2

**Comment by hobnob11** [comment]
am experiencing the exact same issue on linux.

**Comment by esarnb** [comment]
Reproduceable on linux  Ubuntu 24.04 LTS x86_64 with install file `serverinstall_123_12313`

Deleted relevant folders in main server, `mv` moved folders from fresh install into main folder, 
I get the same err as the logfile in ticket

**Comment by Saereth** [comment]
We have a hotfix from the dev going out now, thanks for the reports!
