### ISSUE TITLE
Pipe Config Card causing server crash when using camouflage function 

### ISSUE THREAD

**Issue by devoobin** [FTBTeam/FTB-Modpack-Issues#5537]
### Modpack

FTB NeoTech

### Modpack version

1.5.1

### Has the pack been modified

No

### Log Files

[crash-2024-07-25_05.31.19-server.txt](https://github.com/user-attachments/files/16374669/crash-2024-07-25_05.31.19-server.txt)

### Describe the bug

When using the Pipe config Card from Modern Industrialization, shift right clicking to save a (any) block as camo to use on pipes instantly crashes the game.

### Steps to reproduce

1. Have Pipe Config Card from Modern Industrialization in hand.
2. Shift-Right Click on a block.
3. Server Crash

### Expected behaviour

For the block to be saved as camo and for the server not to crash

**Comment by Saereth** [comment]
Duplicate
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5535
