### ISSUE TITLE
Useless Steel ingots from mekanism exists 

### ISSUE THREAD

**Issue by MorteensG** [FTBTeam/FTB-Modpack-Issues#5538]
### Modpack

FTB NeoTech

### Modpack version

1.4.2

### Has the pack been modified

No

### Describe the bug

Steel dust, when smelting using normal furnace, gives Mekanism steel ingots, which cannot be used for anything in the modpack / does not exist.

Decrafting a block of steel from Modern Industrialisation also gives Mekanism Steel Ingots

### Steps to reproduce

1. get steel dust from metalurgic infuser (mekanism)
2. smelt it using normal furnace

1. smelt uncooked steel dust in electric blast furnace, and 
2. using compactor module for sophisticated storage, get block of steel
3. put it in your crafting menu to get steel ingots (mekanism)

### Expected behaviour

I should be getting steel ingots from Modern Industrialisation

### Screenshots

![image](https://github.com/user-attachments/assets/5cb5055d-c770-4a3a-a3b5-52cab23affdb)

### Additional information

Thanks for your assistance!

**Comment by Saereth** [comment]
This is fixed in v1.5.1 of the pack, please update
