### ISSUE TITLE
Thermopneumatic Processing plant doesn't accept coal dust on Server

### ISSUE THREAD

**Issue by smushis** [FTBTeam/FTB-Modpack-Issues#5539]
### Modpack

FTB NeoTech

### Modpack version

1.5.1

### Has the pack been modified

No

### Describe the bug

I cannot process Virulent Mix to Crude Oil with the Thermopneumatic Processing plant. Coal dust cannot be put inside the Processing plant as shown in the screenshot below. The error seems to be only on SERVER after discussion with the discord.

### Steps to reproduce

1. Open the JEI recipe of crude oil
or
1. Put Virulent Mix in the Thermopneumatic Processing plant.
2. Try to put coal dust inside

### Expected behaviour

As in previous version, we should be able to put coal dust inside to get Crude Oil

### Screenshots

![image](https://github.com/user-attachments/assets/dc79a75a-4888-4856-bed4-9319f0ec41a1)

**Comment by Saereth** [comment]
Carbon dust is defined in kubejs/server_scripts/tags.js and is confirmed working on both client and server for me, it would appear you have corrupt server install. I would suggest doing an in place reinstall of your server to correct the missing/corrupted files. Let me know if you still have issues after that.
