### ISSUE TITLE
Conflict between Easy Magic and Apothic Enchanting

### ISSUE THREAD

**Issue by BrandonThomas02** [FTBTeam/FTB-Modpack-Issues#5542]
### Modpack

FTB NeoTech

### Modpack version

1.5.1

### Has the pack been modified

No

### Describe the bug

Easy magic enchanting table does not interact correctly with Apothic enchanting shelves. The enchanting levels do not increase when placing Apothic Enchanting shelves near and enchanting table nor can you infuse the shelves within the table. Removing the Easy Magic mod from the pack fixes the issue but does not inherently address the issue.

### Steps to reproduce

1. place enchanting table
2. place Apothic Enchanting shelves near table
3. max enchanting level does not increase past base enchanting levels

### Expected behaviour

Apothic shelves should increase the max enchanting levels within the enchanting table

**Comment by GamerBoxMan** [comment]
removed Easy Magic on my server and client side fixed it for me
