### ISSUE TITLE
Cables not craftable

### ISSUE THREAD

**Issue by ArtemisFoulgen1** [FTBTeam/FTB-Modpack-Issues#5545]
### Modpack

FTB NeoTech

### Modpack version

1.5.1

### Has the pack been modified

No

### Describe the bug

steal wires from immersive engineering not craftable (needed for HV wires from same mod)
basic universal cable from mekanism doesnt craft 

### Steps to reproduce

there is just no crafting recipe
sufficient materialls and power was provided to assembler but it didnt start crafting the basic universal cable

### Expected behaviour

have an reciepe? / that it starts to craft?

**Comment by Saereth** [comment]
fixed the steel wires but the mek universal cables are working fine, I'll need to see a screenshot of your interface for the universal cables trying to craft to try and help diagnose
