### ISSUE TITLE
Server crashes when using pipe config card to select a block

### ISSUE THREAD

**Issue by Jondor123** [FTBTeam/FTB-Modpack-Issues#5548]
### Modpack

FTB NeoTech

### Modpack version

1.5.1

### Has the pack been modified

No

### Describe the bug

When you select a block with the pipe config card the server immediately crashes. Has no problem hiding cables but it's just selecting them which crashes.

### Steps to reproduce

1. Use the pipe config card to select a block.
2. The server should crash

### Expected behaviour

It should just select the block without issue

**Comment by BulletTomato** [comment]
Can confirm that I am experiencing this bug as well in the exact same conditions.

**Comment by Onktakh** [comment]
Hello can confirm the bug on a dedicated server copying pipe settings works. Transparency works but blocks for camo crash the server

**Comment by Onktakh** [comment]
Guys this issue is  a serious problem for server owners. Ppl use that card and crash the server intentionally or not, but its hard to track. Is there anything to prevent the use of the card for server owners ?
