### ISSUE TITLE
ForceCraft Spoils bags empty?

### ISSUE THREAD

**Issue by jag0k** [FTBTeam/FTB-Modpack-Issues#5551]
### Modpack

FTB NeoTech

### Modpack version

1.5.1

### Has the pack been modified

No

### Describe the bug

Forcecraft spoils bags don't open, and just vanish when used, presumably because they're generating empty.
(If that is intended, might be a good idea to change the last quest in the ForceCraft chapter, as it refers to making them)

### Steps to reproduce

1. get a spoils bag
2. open it
3. be sad

### Expected behaviour

bag should open and have something in it, or not be the culmination of the Forcecraft questline

**Comment by Saereth** [comment]
yeah they dont drop spoils in this pack, updated quest to reflect that
