### ISSUE TITLE
Empty and Non-Empty Fluid Tanks Stacking Under Specific Circumstances

### ISSUE THREAD

**Issue by BulletTomato** [FTBTeam/FTB-Modpack-Issues#5552]
### Modpack

FTB NeoTech

### Modpack version

1.5.1

### Has the pack been modified

No

### Describe the bug

When an empty fluid tank is picked up then a fluid tank that is not empty is also picked up in a relative quick succession it will stack the non-empty fluid tank onto the empty fluid tank, hence, making it empty.

### Steps to reproduce

1. First place an empty fluid tank and a non-empty fluid tank.
2. Using wrench or other means pick up the empty then the non-empty fluid tank in quick succession.
3. The two fluid tanks will stack as if both are empty.

### Expected behaviour

The empty and non-empty fluid tanks should not stack.

### Additional information

It seems to happen to any tier of the mekanism fluid tanks. It also only seems to happen when there is no more than 2 fluid tanks in total being picked up (one empty and one non-empty originally) and no other tanks of that tier are in your inventory.

**Comment by GamerBoxMan** [comment]
this has happen to me but with mekanism tanks

**Comment by Saereth** [comment]
This has been reported but is very inconsistent in reproducibility so its hard to track down, if you guys can get any circumstances where this is reproducible on a fresh install let us know

**Comment by BulletTomato** [comment]
Sorry, I made a mistake when writing this up, this bug is occurring for me with mekanism tanks as gamerboxman has stated. I can regularly reproduce the bug when I place two tanks down of the same tier, one with liquids and one empty and then pick up the empty and then the one with liquids quickly in that specific order. This bug doesn't seem to occur in any other circumstances for me. Although I haven't tried a clean install yet. Very very strange bug.
