### ISSUE TITLE
Crude oil not prcessing in refine controller

### ISSUE THREAD

**Issue by GamerBoxMan** [FTBTeam/FTB-Modpack-Issues#5553]
### Modpack

FTB NeoTech

### Modpack version

1.5.1

### Has the pack been modified

Yes

### Log Files

removed Easymagic mod that is conflicting with Apoth enchating

not sure if the error is there , dont know hot to look for it
[debug.log](https://github.com/user-attachments/files/16403029/debug.log)

### Describe the bug

Crude oil not getting processed in refinery controller "heat need for recips say 100" pused the heat even up to 800 and 0 progress

### Steps to reproduce

1.build refine controll
2.placed refinery output
3. coverd sides for heat
4.no errors in mach
5.add vortex for heat
6.pump crude oil in

### Expected behaviour

the process of the oil as recip stated

### Screenshots

![image](https://github.com/user-attachments/assets/6944f5c7-aa3d-4f5a-b1b3-fc1f669f48e0)
![image](https://github.com/user-attachments/assets/0cfab750-6747-46e7-82f9-4e3490b6e1ea)

**Comment by GamerBoxMan** [comment]
![image](https://github.com/user-attachments/assets/5ed406aa-894e-43eb-abf2-60c95e62f617)
![image](https://github.com/user-attachments/assets/c0c33456-d8a7-4419-b152-8b721b901629)

LPG liquid allso not pumping into "Thermopneumatic Processing plant" to make raw biodiesel
all other steps to there is working
Thermopneumatic Processing plant
{crude to diesel to kerosene to gasoline to LPG}

**Comment by Saereth** [comment]
should be fixed next update
<img width="605" alt="image" src="https://github.com/user-attachments/assets/4b4c5728-a245-4ec1-aed6-4d81ac52bb86">
<img width="492" alt="image" src="https://github.com/user-attachments/assets/98f26ac0-937a-4503-876a-56bc03f6c992">

**Comment by Onktakh** [comment]
It says completed and fixe din Dev but i have this issue with the actual built 1.6.0 on a dedicated server. 
The controller is properly set up nbo faces exposed pushed to 400 degree but not refining. 

Cans omeone help ? Please reopen for 1.6.0

**Comment by Onktakh** [comment]
> should be fixed next update <img alt="image" width="605" src="https://private-user-images.githubusercontent.com/9200909/352870749-4b4c5728-a245-4ec1-aed6-4d81ac52bb86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NjE2NTIsIm5iZiI6MTcyMjQ2MTM1MiwicGF0aCI6Ii85MjAwOTA5LzM1Mjg3MDc0OS00YjRjNTcyOC1hMjQ1LTRlYzEtYWVkNi00ZDgxYWM1MmJiODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMjEyOTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQzZTY0MDlmYjZmYjYwYjJhYmViOGM1YzcyZjRlYTc3Mjk0ZWE0Mjk3N2E1YmMwZTE1OTE3ZTZiMWM4NWQxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TCyWJi7wU6DqjWINKrVzkXQ86gi8B-Cib_l9Fs58DJ8"> <img alt="image" width="492" src="https://private-user-images.githubusercontent.com/9200909/352870771-98f26ac0-937a-4503-876a-56bc03f6c992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NjE2NTIsIm5iZiI6MTcyMjQ2MTM1MiwicGF0aCI6Ii85MjAwOTA5LzM1Mjg3MDc3MS05OGYyNmFjMC05MzdhLTQ1MDMtODc2YS01NmJjMDNmNmM5OTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMjEyOTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWU1ODkyYjQzNjZmMjJkM2NlY2Y2OTczYjdmMjYyNzM5ZmQ1YmI4ODJkMGIxNzgwM2VkYzc1ZTc1MjY4ZThkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._Mba3vVmFRO0JK8EYqvt0lpqA8abMPS2sO2CHgRkFvk">

Hi Saereth, i am on 1.6.0 but its not fixed at least not on dedicated server. Did i miss something ?
