### ISSUE TITLE
4. quest bug, 1b ethanol

### ISSUE THREAD

**Issue by GamerBoxMan** [FTBTeam/FTB-Modpack-Issues#5555]
### Modpack

FTB NeoTech

### Modpack version

1.5.1

### Has the pack been modified

Yes

### Log Files

removed easy mahic mod

### Describe the bug

got a bucket ethanol quest wont compleat

### Steps to reproduce

used sugar water to make ethanol
got a bucket of it

### Expected behaviour

to get he quest compleated

### Additional information

![image](https://github.com/user-attachments/assets/72ef52da-c08a-4aee-912d-1c87359e56e7)
![image](https://github.com/user-attachments/assets/1c9455d3-d742-401f-a710-0167e6446504)
![image](https://github.com/user-attachments/assets/55f881df-a4d3-484f-93bf-9feb3c26597d)

**Comment by usynelig** [comment]
You need to pump it into a "task screen", it will update the quest then.
Remember to select the correct quest in the task screen before doing so.

**Comment by Saereth** [comment]
Yeah as usynelig pointed out, and as per the quest instructions...
<img width="517" alt="image" src="https://github.com/user-attachments/assets/a2634d87-cb81-45fd-8644-bc952e827b73">
