### ISSUE TITLE
Memory usage dumps causing game to freeze every few seconds

### ISSUE THREAD

**Issue by HDgamerzPC** [FTBTeam/FTB-Modpack-Issues#5559]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

I get a lag every few seconds when the memory usage dumps. I've played around with various memory allocation amounts and have it set to the recommended amount per the FTB app (6GB) now. I've messed with various Java parameters (specifically the ones noted in the other memory usage dump GitHub report posted a few days ago). Can't seem to get it to stop lagging whenever the memory usage dumps. An image of my F3 information is provided in the screenshots section.

### Steps to reproduce

Persistent issue that exists whenever I'm playing the pack in single-player or MP. 

### Expected behaviour

Not to stutter when playing. 

### Screenshots

![download](https://github.com/user-attachments/assets/5b5a102a-3f6f-4e4d-a345-fd6981741602)

### Additional information

Here is a 60 second /spark profiler run while playing on a local server. https://spark.lucko.me/tiBFBsz7zO

**Comment by Onktakh** [comment]
I have same issue on 1.6.0 don´t know if it was existent on older versions too. The server i am playing on is a dedicated server. with 24gigs

**Comment by Saereth** [comment]
Unfortunately nothing in those spark logs seem to indicate minecraft doing anything bad there, and I cant reproduce this on our servers or my community server so I'm a bit at a loss... hopefully next update fixes it as there are a ton of mod updates, keep us posted.
