### ISSUE TITLE
Main FTB quests are all gone

### ISSUE THREAD

**Issue by MorteensG** [FTBTeam/FTB-Modpack-Issues#5560]
### Modpack

FTB NeoTech

### Modpack version

1.6

### Has the pack been modified

No

### Describe the bug

There are no quests available (locked or unlocked) after an update from 1.4.2 to 1.6.

### Steps to reproduce

1. Right click FTB questbook
 2. Empty questbook

### Expected behaviour

There should have been quests in it

### Additional information

Thank you! Would be nice if a solution is provided

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by MorteensG** [comment]
[debug.log](https://github.com/user-attachments/files/16409506/debug.log)

i could not use the apps stated for the logfile above, sorry.

latest.log:   https://paste.feed-the-beast.com/view/8ab481b6

if it is any help, it happened when my friend updated his server files to 1.6, which caused this to happen.

Thanks once again!

**Comment by Gaz492** [comment]
Could your friend (or you if you are able to) delete the ftb quests folder thats located in the config folder then update the server again?

**Comment by MorteensG** [comment]
My friend has done that, but it did not help. There were other issues with the world after the update, thus we are rolling back the update, thanks anyways.

**Comment by Gaz492** [comment]
Ok, if you do decide to update again, could you try installing a fresh copy of the modpack on the server and copy your world over to it?
Its possible that the server installer is not updating files correctly.

**Comment by ReginaldCal** [comment]
We have done the same now, questbook is "locked" on a new world going in but once we transferred over our old world it worked perfectly

**Comment by mkienenb** [comment]
I also had the same problem when I upgraded my server from 1.4.2 to 1.6.0 today.
The quests are all gone from the quest book.

Possibly-related -- the EMC'd items are also all missing (although the total amount of EMC is still the same).
