### ISSUE TITLE
Server Crashing at Player Login

### ISSUE THREAD

**Issue by Spleneticist** [FTBTeam/FTB-Modpack-Issues#5561]
### Modpack

FTB Presents Direwolf20 1.20

### Modpack version

1.16.0

### Has the pack been modified

No

### Log Files

https://pste.ch/itowexedus.rb

### Describe the bug

Over the last few days, if the server has been up for over an hour with no one logged into it, the first person to attempt to login causes the world to crash. This problem doesn't exist if you log in shortly after the world is started.

### Steps to reproduce

1. Start world
2. Wait longer than 1hr with no players logging into it
3. Attempt to login
4. Server hangs and crashes

### Expected behaviour

Clean login with no crashing

### Additional information

- Seems player agnostic, happens with the first login attempt from anyone
- Seems not to be a performance issue. World isn't utilizing all available memory and CPU doesn't spike more than ~25% utilization at player login
- Player sees and can move about in the world but can't interact with it; they get "Waiting on server..." when trying to interact with chests

In the terminal I see the following output:
```
[User Authenticator #1/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: UUID of player xxxxxxxx is xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Server thread/INFO] [net.minecraft.server.players.PlayerList/]: xxxxxxxx[/12.345.67.89:12345] logged in with entity id 1067 at (-120.8564912097339, 69.0625, 62.3753979897072)
[Server thread/INFO] [Modonomicon/]: Building books ...
[Server thread/INFO] [Modonomicon/]: Books built.
[Server thread/INFO] [net.minecraft.server.MinecraftServer/]: xxxxxxxx joined the game
[Server thread/INFO] [org.zeith.solarflux.SolarFlux/]: Sending solar panels to xxxxxxxx.
[Server thread/INFO] [mcjty.lib.setup.DefaultModSetup/]: Client logged in: sending dimlet packages
[Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 3333ms or 66 ticks behind
[spark-async-sampler-worker-thread/WARN] [spark/]: Timed out waiting for world statistics
[spark-async-sampler-worker-thread/WARN] [spark/]: Timed out waiting for world statistics
[Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerWatchdog/FATAL]: A single server tick took 120.00 seconds (should be max 0.05)
[Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerWatchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
[Server Watchdog/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 01b8596a-9d93-4cb1-a66f-b1f4ad48d44b
[Server Watchdog/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 4daa59be-60aa-434f-8a3d-1f26b4b1ceb4
[Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerWatchdog/]: This crash report has been saved to: ./crash-reports/crash-2024-07-29_08.41.11-server.txt
```

**Comment by Gaz492** [comment]
Could you try disabling the canary mod and see if the issue continues for you?

**Comment by Spleneticist** [comment]
Sure thing - dumb question but: How do I do that? I looked for a config file where I could just disable it but the config file I found for Canary is empty and states it is intentionally so. Should I just remove it from the Mods dir?

**Comment by Spleneticist** [comment]
I moved the canary mod out of the mods directory and that seems to have prevented it from loading. Since then, I've had several players log in and out through the day without a crash. I think that may have resolved the issue, but I'll keep watching and report back in a day or two.

**Comment by Spleneticist** [comment]
Have had a few more logins today without crashing. Looks like removing the Canary mod resolved my crashing issue, thanks!
