### ISSUE TITLE
Sulfuric crude oil and Crude Oil in Thermoneumatic Processing Plant

### ISSUE THREAD

**Issue by BIBLOFFXI** [FTBTeam/FTB-Modpack-Issues#5562]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

Sulfuric crude oil and Crude Oil won't go into in Thermoneumatic Processing Plant; I have tried /reload. even tried Refinery controller but crude oil won't go into it either.

### Steps to reproduce

Pump Sulfuric Crude Oil out of Chemical Reactor into THP.

### Expected behaviour

Get Crude Oil

**Comment by Saereth** [comment]
should both be working in the new update coming out today
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/01d682f9-9f6d-4c8f-b7a1-9c4c1c5fbcfb">
