### ISSUE TITLE
FTB Skies Won't authenticate me

### ISSUE THREAD

**Issue by MUMMALAMA** [FTBTeam/FTB-Modpack-Issues#5568]
### Modpack

FTB Skies Expert

### Modpack version

1.9.0

### Has the pack been modified

No

### Log Files

https://pste.ch/xetewipaye

### Describe the bug

I click on PLAY and it opens a web browser.  I log in and it take me back to the app.  A screen pops up with ticks running down.  When it gets to the bottom it says I dont have the game. 

![Capture](https://github.com/user-attachments/assets/3cf79309-0ee7-46d8-8541-489fd0f9f1d4)

### Steps to reproduce

as above

### Expected behaviour

I expect it to open the game.

### Screenshots

![Capture](https://github.com/user-attachments/assets/335ce5f4-89ab-4a4a-b1c4-5e06091d80dd)

**Comment by Gaz492** [comment]
Unfortunately, Microsoft is having issues currently, the only thing you can do is to keep trying.

**Comment by MUMMALAMA** [comment]
Incorrect.  It was a login issue which I explained on discord.  If I had
kept trying it would have never worked.
