### ISSUE TITLE
[Suggestion]:  Apotheosis

### ISSUE THREAD

**Issue by LittleChronic** [FTBTeam/FTB-Modpack-Issues#557]
### Modpack

FTB Direwolf20

### Is your suggestion related to a problem? Please describe.

There are a lot of enchantments in the pack but what if they could be better? Apotheosis does enchanting completely different than vanilla and it also has other features like improving that annoying wandering trader to actually make him useful and also changes how spawners work. And spawners is also another thing that would be great to have options for. Sure we can use the mob duplicator but that require essence & power and you can't really make it better than a vanilla spawner. With Apotheosis you can change the speed, the player requirement, set redstone control and so much more.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/apotheosis

As I said above I'd like to see better options for enchantments and for spawners. (Mostly spawners)

**Comment by Sunekaer** [comment]
We are currently not adding more content to this pack, we will keep it in mind if we do one day
