### ISSUE TITLE
Authentication servers are down, but they aren't!

### ISSUE THREAD

**Issue by CrowieLIVE** [FTBTeam/FTB-Modpack-Issues#5570]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Has the pack been modified

No

### Describe the bug

I am always getting the error "Authentication servers are down. Please try again later, sorry!" when joining my Nitrado server. I manually installed the modpack on the server (installed the correct forge version etc.), the server worked when I tried it locally, but on the dedicated server it doesn't. I already talked to Nitrado, they switched my server but it still didn't fix the problem. They told me it has something to do with the modpack itself.

### Steps to reproduce

1. Manually download forge
2. Download the server pack
3. Install the correct forge server version on the server
4. copy the "mods" folder from the server pack to the (nitrado,...) server
5. try to join the server

### Expected behaviour

Join the server

### Screenshots

![gimp-2 10_Rc3PLFxocM](https://github.com/user-attachments/assets/9409d802-91a0-4872-8cc2-9a37bdc15331)
![javaw_fBmW3YaTTp](https://github.com/user-attachments/assets/2becbc53-0951-4cc8-afb8-d3c5582c6f33)
![javaw_GnYYXZUk7J](https://github.com/user-attachments/assets/9b533f40-5433-4c1c-ba39-ff475b8bcbb1)

### Additional information

The mojang authentication servers are definitely not down, the problem is the same as a week ago

**Comment by Gaz492** [comment]
Is this still an issue for you? 

Microsoft were running into on and off issues with their authentication servers which should be resolved now.
If you are still having issues, try restarting the server.

**Comment by CrowieLIVE** [comment]
If you want I can give you full access to the server and you can have a look yourself.

**Comment by Gaz492** [comment]
Would you be able to upload the latest.log and debug.log from the server so I can take a look at them?

**Comment by CrowieLIVE** [comment]
of course, there you go
[debug.log](https://github.com/user-attachments/files/16444000/debug.log)
[latest.log](https://github.com/user-attachments/files/16444001/latest.log)

**Comment by Gaz492** [comment]
Try removing reauth from the mods folder on the server, other than that I'm not seeing anything that could be causing problems and I've also not been able to reproduce this issue on my own server.

**Comment by efinder2** [comment]
Same Problem here.

**Comment by ugh1849** [comment]
For anyone looking at this in the future, adding these args when starting the server fixed it for me when joining on my local network:

-Djava.net.preferIPv4Stack=true
-Djava.net.preferIPv4Addresses=true

Hope this helps!
