### ISSUE TITLE
NeoTech modern industrialization crash

### ISSUE THREAD

**Issue by yipawn** [FTBTeam/FTB-Modpack-Issues#5572]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Log Files

[crash-2024-07-30_22.13.24-client.txt](https://github.com/user-attachments/files/16436634/crash-2024-07-30_22.13.24-client.txt)

### Describe the bug

When building the large electric furnace from extended industrialization when holding either the wrench or input/output hatches that would show the outline of a multiblock causes a crash.

### Steps to reproduce

Holding an item that would show the multiblock structure would cause a crash instead of showing an outline of where to place the blocks.

### Expected behaviour

An outline of where to place the blocks should appear instead.

**Comment by Gaz492** [comment]
Could you try disabling the embedium mod and see if this issue still happens for you?

As a note to our pack devs, extended industrialization is rather outdated in the pack. it's still on beta 1.0.0 and latest is 1.1.3

**Comment by yipawn** [comment]
I disabled the mod but it didn't work. It is still crashing and it seems to be any multiblock.
[Uploading crash-2024-08-01_10.29.45-client.txt…]()

**Comment by rwywawn** [comment]
I am running into the same issue, after the first crash I would be stuck in a crash loop when I tried to log in. What fixed it temporarily was going into a single player creative world and building it then going back to the server I was playing on. 
[crash-2024-08-01_16.38.54-client.txt](https://github.com/user-attachments/files/16461807/crash-2024-08-01_16.38.54-client.txt)
