### ISSUE TITLE
NeoTech Mild Quest Issues

### ISSUE THREAD

**Issue by mrfrase3** [FTBTeam/FTB-Modpack-Issues#5574]
### Modpack

FTB NeoTech

### Is your suggestion related to a problem? Please describe.

Here are some observations I've made from my play through so far:

- **Time for Feedom** - asks for 20 _Chains_, when you only need 18
- **Vacuum Freezer** - requires 8 more _Frostproof Machine Casings_ then required. This was pretty annoying, as aluminum is pretty costly at that point
- ~~**Monzanite Byproducts** - _Neodymium Dust_ is required to make _Magnetic Stainless Steel Rods_, which is required for the _Advanced Motor_, i.e. **Monzanite Byproducts** should be before **Advanced Components**~~
- ~~**Silicon Wafer** - Iridium isn't required to make Silicon Wafers, this shouldn't have **Iridium Tiny Dust** as a requirement~~ - turns out I'm just blind
  - I'd suggest expanding on the **Air Intake** quest in Kinda Mid to lead on to an "Argon" quest given how much it's used, which then leads to silicon wafers.
- Another suggestion is adding a "Steel Gear" quest after the **Assembler** quest, in which you suggest the player checks out the _Metal Press_ in Actually Engineering, this could then lead to **We need a bigger tank!**, which would be very gear heavy. I only realised this whilst waiting around for aluminium to make the vacuum freezer, I could have saved a lot of time and effort not crafting gears by hand like a caveman.

This is more of a complaint, not sure if this is intentional or not, but AE2 _Crafting Units_ are basically blocked until the end of High Voltage by requiring _RAM_ and _Digital Circuits_. With the amount of back and forth required crafting and processing by hand, especially with the crafting tree requirements for a single _Digital Circuit_, it's all rather painful for someone who's used to AE2 in their playthroughs. I can see the point of view that this could be motivation to get to the end of the HV chapter, but boy is it a struggle. Maybe the following changes might make it a little easier:
- **Crafting Unit** quest is moved to be after **Assuming Direct Control** and **1k ME Storage Component**
  - You need both of these to do auto crafting anyway
- As the reward for **Assuming Direct Control** you get one _Crafting Unit_
- The requirement for **Crafting Unit** is changed to be a _4k Crafting Storage_.

Combined with the rewards from **Crafting Unit**, the player can then make a single limited autocrafting CPU, which would improve the road to the Extreme chapter, but still give a reason to take it if they want more auto crafting power. One could almost say that the quality of life improvement is a bonus for taking the early AE2 side quest.

Anyway, thanks for the modpack, I got a crafting system to make :+1:

**Comment by mkienenb** [comment]
@mrfrase3, Note that you can get Neodymium dust by centrifuging (redstone dust if I recall) so Monzanite Byproducts are not required first.

**Comment by mrfrase3** [comment]
oh man, I just spent 3 days mining whole chunks for Monzanite ore because I missed that. Redstone gives tiny dust, I was only looking at the full dust recipes :facepalm: 

Also checked the Ruby Dust quest which also mentions Neodymium as a byproduct.  :facepalm:  :facepalm:

Not sure how to prevent someone else making the same mistake, maybe I'm just too silly

**Comment by Saereth** [comment]
added some of these suggestions, thanks!
