### ISSUE TITLE
Mega cells aren't being rendered correctly

### ISSUE THREAD

**Issue by dev-cyprium** [FTBTeam/FTB-Modpack-Issues#5576]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Log Files

-

### Describe the bug

The MEGA CELLS cell doesn't have a render, when I place it it makes it see-through the world.
![image](https://github.com/user-attachments/assets/619d5334-d3fd-4b23-a71c-be5c3e8f50e6)

I've tried a co-processing unit, and also other units as well.

### Steps to reproduce

1. Make a simple AE2 system
2. Place a mega cell
3. X-ray through the world

### Expected behaviour

Not X-ray through the world

### Screenshots

Included in the bug description

**Comment by dev-cyprium** [comment]
Not interested in holding accountability for this issue anymore, closing it

**Comment by nickzandbergen** [comment]
F3 + T fixes this, there's a ticket that goes into more detail on the mega cells page.
