### ISSUE TITLE
Unable to split sophisticated double chests

### ISSUE THREAD

**Issue by Meryl** [FTBTeam/FTB-Modpack-Issues#5577]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

I accidentally joined two sophisticated chests, but I didn't want that. Now, I can't split them.

### Steps to reproduce

1. Place a sophisticated chest.
2. Place another next to it, so they join.
3. Try to pick up either by breaking them (any way works).
4. They drop as one packed chest.

### Expected behaviour

Be able to pick up either, esp. when empty

### Additional information

I assume this is because `dropPacked` is set to `true` in the sophisticatedstorage-common config.

**Comment by Saereth** [comment]
Yeah this isn't a bug, its working as the mod intended, if you want it to function different or suggest a change with them you should open an issue on their tracker.
