### ISSUE TITLE
[Bug]: Andesite, diorite, and granite seemingly absent

### ISSUE THREAD

**Issue by Newbytee** [FTBTeam/FTB-Modpack-Issues#558]
### Modpack

FTB Endeavour

### Modpack version

1.8.0

### Describe the bug

I have spent little over 10 hours playing together with someone in my current FTB Endeavour world, and we have not found a single block of andesite, diorite, or granite which is annoying as Create requires e.g. andesite for some recipes. R3GEN on Discord said this likely was a bug and asked me to report it here.

### Steps to reproduce

1. Enter a world
2. Dig down
3. Attempt to find any andesite, diorite, or granite
4. Fail spectacularly

### Expected behaviour

Andesite, diorite, and granite should be available underground in abundance

**Comment by Newbytee** [comment]
I think I might have been mistaken here. I have been able to find diorite in a different biome, so maybe it's just that some mod makes it so that the vanilla stone types only can be found in certain biomes?

**Comment by Raidobw2** [comment]
No worries 👍 I can look at it in-dev to make sure
