### ISSUE TITLE
PNC Refinery Controller with 4 outputs not processing Crude oil 

### ISSUE THREAD

**Issue by Onktakh** [FTBTeam/FTB-Modpack-Issues#5580]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

Bug was already present in 1.5.1 commented by dev as closed but its still existent in 1.6.0 dedicated server. 
Tried in SP world => works as intended in Recipe but not on dedicated server.

Pneumaticraft renifery controller properly set up is not refining crude oil as stated in recipe. 

### Steps to reproduce

1. Refine virulant mix to crude oil
2. Pump into properly set up pneumaticraft refinery controller with 4 outputs
3. Heat up and cover the Refinery controller from PNC no failures
4. Crude oil is not processing. 

### Expected behaviour

Process crude as recipe stated

### Screenshots

see this bug report same issue 
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5553
![image](https://github.com/user-attachments/assets/aeb5b5ee-b5d0-48be-8287-a41d0f9aeb68)
The refinery controller is not showing the temperature threshold in green letters as it is in single player world. 

### Additional information
Serverinstallation was done without failures (i always recheck on that) and also no failures in recipes were seen on the server. 
However a second 0 failrue reinstall solved that issue on the server.

**Comment by Gaz492** [comment]
Would you be able to try running the update on the server again?

It sounds like something didnt get updated correctly causing the recipe to not be fixed

**Comment by Onktakh** [comment]
Reinstalled again with 0 failures as before 👍 but i wondery why the installation on the server is so often hiccuping and not working although 0 failures are commented. 
![image](https://github.com/user-attachments/assets/78a17bd5-5c09-4f1d-b744-32a4b8028e3e)

Now we cooking. Thanks for the info
![image](https://github.com/user-attachments/assets/f0e5b290-df0c-41be-8d17-393bb8e6282e)

**Comment by Gaz492** [comment]
Its something we are currently looking into as it only happens to some files.
