### ISSUE TITLE
Can´t obtain tall grass to use it for empowering recipe for Emeradic Crystall AA

### ISSUE THREAD

**Issue by Onktakh** [FTBTeam/FTB-Modpack-Issues#5582]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

Using shears on tall grass drops 2xshort grass. No other possibility to obtain tall gras (silktouch with tools) or crafting. 
Had to cheat in tall grass. 

### Steps to reproduce

1. Use shears on tall grass
2. Drops 2x short grass
3. 

### Expected behaviour

Shears on tall grass are expected to drop tall grass

### Additional information

Tested on dedicated server 1.6.0 but also got confirmation from MTG players that they have same issue.

**Comment by Seroku03** [comment]
Hello, Player here.
Sadly, the only way (at the moment) to get Tall grass is as loot on chests in certain villages.
That is the vanilla way and there is no way around it.
If they; in the future, add another way to get it, it would be an option but that is how it is for now.
The following link is for reference
https://minecraft.wiki/w/Tall_Grass

**Comment by Saereth** [comment]
this is correct, you loot it but in the new update I've made it so you'll automatically get the EMC knowledge for it so you can start making it with emc right away.

**Comment by xxhertz** [comment]
this post is several years old at this point and i dont see any tall grass in the transmutation table

<img width="571" height="412" alt="Image" src="https://github.com/user-attachments/assets/4c728ec8-d167-4735-93de-c3ea500de6ae" />
