### ISSUE TITLE
Ukrainian localization

### ISSUE THREAD

**Issue by Kirkus26** [FTBTeam/FTB-Modpack-Issues#5585]
### Modpack

FTB NeoTech

### Is your suggestion related to a problem? Please describe.

I want to make a Ukrainian translation for modpack NeoTech. If I make it, where should I send the files, or how should it work?

**Comment by Saereth** [comment]
Thanks for your interest in doing this! We do fully support localizations now, if you want to translate it then you would just send me the new langfile (you can find the english version in kubejs\assets\ftbneotech\lang\en_us.json. You can just copy that and rename it uk_ua.json and put the translations in there. You can post a link to the file in an issue or contact me on discord and send the file directly (username is saereth).
