### ISSUE TITLE
Consistent lag spikes on EquivalentExchange "Saving bag inventory" message.

### ISSUE THREAD

**Issue by bluekatelo** [FTBTeam/FTB-Modpack-Issues#5589]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Log Files

https://pste.ch/porewejiti.md

### Describe the bug

Our server is experiencing pretty significant lag spikes almost every other minute. They consistently happen as you see in the logs listed above, alongside the EquivalentExchange "Saving bag inventory" messages. Server then can't keep up for about 10-15 seconds followed by everything being fine until the next event.

### Steps to reproduce

Playing the game normally triggers the issue eventually, regardless of what players do.

### Expected behaviour

Server operates without lag spikes

### Screenshots

![image](https://github.com/user-attachments/assets/9360ce62-7d38-4aeb-ba3c-5960d93ee477)
![image](https://github.com/user-attachments/assets/7135bae2-6e49-4673-906f-15d32feb18e7)
![image](https://github.com/user-attachments/assets/12210bcd-ec5f-4b5f-a365-7e21e654cbfc)
![image](https://github.com/user-attachments/assets/20a98a4f-e0e8-47d2-8762-e416ef4a1e90)

### Additional information

Server is running on a TrueNAS scale docker container.

**Comment by PerfectPink** [comment]
Did you somehow fixed this? we've got exactly the same problem today, except we're hosting by our own server pc
