### ISSUE TITLE
[Bug]: Crafting and Equipping a Living Chestplate from Blood Magic perma-breaks your game

### ISSUE THREAD

**Issue by wrincewind** [FTBTeam/FTB-Modpack-Issues#559]
### Modpack

FTB Oceanblock

### Modpack version

1.1.0

### Log Files

 https://github.com/WayofTime/BloodMagic/issues/1853
https://github.com/WayofTime/BloodMagic/blob/1.16.3/changelog.txt
This has been fixed in the latest version of Blood Magic, fortunately.

### Describe the bug

Due to an interaction between Blood Magic and certain other mods that interact with or modify how Elytra flight is handled, equipping Living Armour from Blood Magic will corrupt the player's data, causing them to hard crash any time they try to join a game. Currently, the only fix that i've found is to upgrade (or downgrade) to an un-affected version (either latest, or before the Elytra Flight upgrade was added), have the player log in, and make them unequip and destroy their chestplate.

Cheating one in via JEI will work as a reasonable substitute, as this chestplate will be properly initialised and won't cause unexpected NULLs in strange places. :) 

### Steps to reproduce

1) craft a full set of living armour (Arcane Ash ritual - Living reagent + iron armour pieces)
2) equip the full set
3) hard crash

### Expected behaviour

the armour to work as usual

### Additional information

upgrading to the latest version of BM should *really really super hopefully* fix it this time. We hope. :)

**Comment by Raidobw2** [comment]
Thanks for the report! We'll update this in the next release

**Comment by Dalmaron** [comment]
I have found steps to fully reproduce this issue in server and non server environments. 

1. Must craft full living armor set in survival.
2. Must equip full living armor set in survival.

Any sets of living armor gained through creative inventory, or crafting while in creative mode will not reproduce bug. Bug relevant as of latest stable Oceanblock release. Debug logs attached

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8010314/debug.log)

[crash-2022-02-06_08.49.20-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8010315/crash-2022-02-06_08.49.20-server.txt)
.
