### ISSUE TITLE
Fluid tank visual glitch

### ISSUE THREAD

**Issue by Novial-dev** [FTBTeam/FTB-Modpack-Issues#5592]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

Yes

### Describe the bug

Shift-right clicking with the Mekanism Fluid Tank on any block with a bucket mode on, will remove bucket's worth from the tank but will place a bugged see-trough block. Shift-right clicking more on the bugged block it keep removing the liquid without any difference.

### Steps to reproduce

1. Grab Mekanism's Fluid Tank (in my case Basic one) with a liquid in it (in my case, lubricant)
2. Shift-mouse scroll to turn bucket mode on
3. Shift-right click on any block (in my case stone block)
4. Invisible see-trough block will appear exposing blocks beyond
5. Continue shift-right clicking on the block to keep removing the liquid from the tank (this I believe is intended mechanic)

### Expected behaviour

No invisible see-trough block appearing.

### Screenshots

![2024-08-04_13 49 00](https://github.com/user-attachments/assets/f9c12f2f-6087-4132-b1bc-19bf17577ea8)

### Additional information

The invisible see-trough block can be destroyed in one hit and purple particles (particles of destroyed block) will appear upon doing so, indicating bad texture.

**Comment by Gaz492** [comment]
It looks like this is caused by the tank trying to place a pool of lubricant down, but modern industrialization doesnt normally allow you to do this using a bucket so the game is not sure how to render what the tank placed in the world.
