### ISSUE TITLE
Integrated Dynamics crashes when using Block Reader and Redstone Writer on certus farm

### ISSUE THREAD

**Issue by lurch9229** [FTBTeam/FTB-Modpack-Issues#5594]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Log Files

https://pastebin.com/8wTJm7sC

### Describe the bug

I am trying to use integrated dynmics to read when a budding certus has created a certus cluster. I have made a variable card that reads the block state using the block reader, and am then checking that card against a block card set to certus clusters, and have them using the == operator. When a redstone signal is produced my game crashes back to launcher.

I have tried using the Simple Block Breaker from Just Dire Things and I have tried using the Auto-Breaker from Actually Additions

### Steps to reproduce

place a block reader and redstone write on a logic network using cables.
Create a variable card for Block in the Block Reader
Using the logic programmer, make a Block card that matches to Certus Cluster
Using operator == create a final variable card using the block readers variable card and the certus cluster variable card
Place the first 2 cards into a variable store (the 2 block cards)
Place the final card into the redstone reader
Crash happens

### Expected behaviour

Redstone signal should output when block specified is true without crash

### Screenshots

![2024-08-04_15 23 09](https://github.com/user-attachments/assets/2b1bd03c-25fb-4fd5-9fda-b720462af4bc)
![2024-08-04_15 24 11](https://github.com/user-attachments/assets/415c1d6f-ceb2-432c-a04d-61d3b0c6a0f1)

### Additional information

I have also tried this in a creative world with the same issue
During further testing I have noticed that the Writer isn't updating vanilla redstone correctly.
I put a card with a true boolean inside it and it would output to the redstone, however when the card is removed there is no update. Placing this card into the pulse slot causes a crash too

**Comment by Gaz492** [comment]
Looks like this issue, has been fixed by the mod dev in a newer version of integrated dynamics.
https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics/files/5570432

If you're playing in singleplayer, you could try updating the mod to the version in the link above, we will also try and get an update out to fix this as soon as possible.
