### ISSUE TITLE
Recipes Missing from Immersive Engineering Crusher

### ISSUE THREAD

**Issue by Kataryx** [FTBTeam/FTB-Modpack-Issues#5595]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

Myself and others in the FTB discord are experiencing an issue with the Immersive Engineering Crusher. It seems that the multiblock is unable to crush most items, and according to the recipes GUI for the Crusher, most of them are blank/missing, especially for most of the ores in the pack. Is this intended for balance, or is it a bug?

### Steps to reproduce

1. Open EMI
2. Open Crusher recipe GUI
3. Most of the recipes listed are blank/missing.
4. Toss various ore blocks into the Crusher multiblock while it's receiving power, most do nothing. (Redstone ore seems to work fine, and refined materials such as ingots also work fine.)

### Expected behaviour

Crusher recipes to be available.

### Screenshots

https://github.com/user-attachments/assets/918adb80-a539-457d-83c0-b0a8295132a6

**Comment by Saereth** [comment]
This is a balancing thing, we'll try to make it more clear in the questbook and via tooltips. Most of the crushing processes should be running through macerator/unpackagers.
