### ISSUE TITLE
quest wont complete 

### ISSUE THREAD

**Issue by daedaim** [FTBTeam/FTB-Modpack-Issues#5596]
### Modpack

FTB NeoTech

### Modpack version

1.8

### Has the pack been modified

No

### Describe the bug

The quest rubber sheet will not complete. It shows 100% progress and a blue circle around the quest image.

### Steps to reproduce

Not sure how it happened 

### Expected behaviour

quest to complete and other quests become available.

**Comment by daedaim** [comment]
[debug-1.log.gz](https://github.com/user-attachments/files/16495364/debug-1.log.gz)

[2024-08-04-1.log.gz](https://github.com/user-attachments/files/16495366/2024-08-04-1.log.gz)

![Screenshot 2024-08-05 040924](https://github.com/user-attachments/assets/275df868-8ff8-4063-8ffc-b02c30a95f2e)
I hopefully correctly attached the two logs and a screenshot of what im talking about. The quest is rubber sheet in the caveman goes tech branch of quests.

**Comment by Saereth** [comment]
looks like an update caused pre-requisites to change so you'll have to go make sure they're all done and/or forcible reset them with edit mode (the pencil in the lower right hand corner)
