### ISSUE TITLE
FTB Lite 3 1.5.1 crashes

### ISSUE THREAD

**Issue by mrkivio** [FTBTeam/FTB-Modpack-Issues#5597]
### Modpack

FTB Lite 3

### Modpack version

1.5.1

### Has the pack been modified

Yes

### Log Files

[crash-2024-08-04_23.38.25-client.txt](https://github.com/user-attachments/files/16488859/crash-2024-08-04_23.38.25-client.txt)

### Describe the bug

it crashes 

### Steps to reproduce

I have no clue

### Expected behaviour

to launch normaly

### Additional information

so since my computer is really bad I added optifine to it and no other mod. Then I removed it but it still would crash

**Comment by mrkivio** [comment]
Same thing

**Comment by Gaz492** [comment]
Could you upload a fresh log so I can compare them?

**Comment by mrkivio** [comment]
I checked the crash-reports folder but there is no new report

**Comment by mrkivio** [comment]
dbg:alIpbSuLLCk

**Comment by Gaz492** [comment]
Thanks, according to the logs, the pack is running into a known issue with the graphics drivers on your computer.
I would recommend you to make sure you have the latest intel graphics driver installed
