### ISSUE TITLE
Watch of flowing time does nothing

### ISSUE THREAD

**Issue by set5u** [FTBTeam/FTB-Modpack-Issues#5598]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

Watch of flowing time added by EE4 does nothing. I tried right clicking, action key and charge key, but nothing happen.

### Steps to reproduce

1. Get Watch of flowing time by completing the quest.
2. The issue happen.

### Expected behaviour

Gives nearby tile entities 19 extra ticks per tick

**Comment by set5u** [comment]
Nothing seems to have changed.

**Comment by DanielBallaSZTE** [comment]
Confirmed still not working, neither on the pedestial, nor in hand.
