### ISSUE TITLE
[Suggestion]: Add mod-added mobs to Soul Shards entity list

### ISSUE THREAD

**Issue by zediious** [FTBTeam/FTB-Modpack-Issues#560]
### Modpack

FTB Ultimate: Anniversary Edition

### Is your suggestion related to a problem? Please describe.

Not really a bug, just a missing configuration change I would say. Currently the `soulshards.json` file contains only vanilla mobs for use with it. My suggestion is adding mod-added mobs to this list (within reason).

Example Mobs:
- Thermal Basalz, etc
- Natural spawning Ars Nouveau mobs

Current configuration file of the modpack;
 [https://gist.github.com/zediious/766bb6faf698ab98a618ae5f10f84fb8](https://gist.github.com/zediious/766bb6faf698ab98a618ae5f10f84fb8)

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
