### ISSUE TITLE
NeoTech Pam's Harvestcraft harvestable block duplication.

### ISSUE THREAD

**Issue by littleconnor1** [FTBTeam/FTB-Modpack-Issues#5600]
### Modpack

FTB NeoTech

### Modpack version

1.4.0

### Has the pack been modified

No

### Log Files

https://pste.ch/wunamaruzo.md

Note that this may not be very helpful.

### Describe the bug

Upon right clicking to harvest a harvestable object, like say, a Cinnamon Fruit Log or a Lemon Fruit from a tree, both the object meant to be harvested (Cinnamon or a single Lemon) as well as the block itself (the Cinnamon Fruit Log and the Lemon Fruit block) are dropped.  This bug is not consistently reproducable for some odd reason, as it seems to randomly occur in different sessions.

### Steps to reproduce

1. Launch the game and hope you have a bugged play session for some reason.
2. Find a harvestable block in-world and harvest when mature. 
     2a. It seems to occur more often when vein mining whatever it was originally on, but can occur randomly nonetheless.

### Expected behaviour

For the block to simply revert to 0% maturity and drop the expected harvestable item instead of cloning itself.

### Screenshots

_Harvestable Lemon Fruit_
![image](https://github.com/user-attachments/assets/21385714-97e3-4d6c-b2d6-54c906479b4c)
_Lemon Fruit Block and Lemon on the ground_
![image](https://github.com/user-attachments/assets/0b434fce-ccab-48de-99c8-adeb9032412d)
_Block in inventory_
![image](https://github.com/user-attachments/assets/bedf5db4-db1c-4e7f-a831-24f3cf5daa06)
_The Lemon Fruit block can be placed back on leaves, allowing for infinite lemon generation_
![image](https://github.com/user-attachments/assets/2a1acb13-56ca-41d4-b3bf-989a580145d8)

### Additional information

Not consistent, only appears to happen during some sessions and not others. Steps to reproduce are likely much more complex.

**Comment by littleconnor1** [comment]
EDIT: VERSION IS 1.6.0 NOT 1.4.0

**Comment by Saereth** [comment]
Pam's issue, should be fixed now
