### ISSUE TITLE
FTB Builder's Paradise (original, not 2) always freezes on loading stage 6/7 on brand new install.

### ISSUE THREAD

**Issue by Moltresrider** [FTBTeam/FTB-Modpack-Issues#5602]
### Modpack

Other...

### Modpack version

1.9.0

### Has the pack been modified

No

### Describe the bug

Every time I try to load FTB Builder's Paradise that I JUST downloaded, it always freezes when it gets to stage 6/7. I have made multiple attempts to reload Minecraft.

### Steps to reproduce

Download the FTB app
Download the original Builder's Paradise.
Import the Builder's Paradise into MiltiMC by selecting "FTB App import"
Run Builder's Paradise
Wait until stage 6/7
Indefinite freeze

### Expected behaviour

It should continue to load the files and proceed to the main menu.

### Additional information

Java has 6 - 8 GB RAM allocated. and it freezes with only 3 GB used according to the load screen. This is on a 16 GB system.

A Google search reveals a vast number of people having this issue, many of which posted on FTB forums, but nobody has gotten a response.

Being the sheer number of people who are having this problem, it appears to be an issue with the modpack, not with the user's computer or anything.

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by Moltresrider** [comment]
That link does not apply. I said that the instance is in MultiMC. FTB app will not have the logs

**Comment by Gaz492** [comment]
Ok, to rule out an issue with multimc, would you be able to try starting the pack using the FTB App?
