### ISSUE TITLE
Equivelant Integration crash

### ISSUE THREAD

**Issue by skyblockmodpackuser** [FTBTeam/FTB-Modpack-Issues#5604]
### Modpack

FTB Sky Odyssey

### Modpack version

1.3.0

### Has the pack been modified

Yes

### Log Files

https://mclo.gs/2YpD2OO

### Describe the bug

Upon installing a soulbound talisman in a Transmutation Chamber that is connected to a network, the game crashes and keeps crashing every time the world is re-loaded

### Steps to reproduce

1. Install Equivelant Integration v0.4.6 and mikesmodlib v1.0.2
2. Setup a small AE2 network consisting of a controller, inscriber, molecular assembler and a pattern terminal on a fluix cable
3. Attach a transmutation chamber to the network
4. Configure a soulbound talisman to yourself
5. Install it in the transmutation chamber
6. Game crashes

### Expected behaviour

Expected to function normally

**Comment by Gaz492** [comment]
If you follow the guide linked below, and turn on both config options mentioned, it may let you back into your world
https://docs.feed-the-beast.com/docs/support/Troubleshooting/ticking-entities#packs-running-forge-112-and-older
