### ISSUE TITLE
FTB Neotech Integrated Dynamics Crash

### ISSUE THREAD

**Issue by RyanRio** [FTBTeam/FTB-Modpack-Issues#5608]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Log Files

[crash-2024-08-07_09.22.36-server.txt](https://github.com/user-attachments/files/16531509/crash-2024-08-07_09.22.36-server.txt)

### Describe the bug

Integrated Dynamics crashes the game with NullPointerException upon using a '>' operator to compare redstone signal to a constant.

### Steps to reproduce

1. Place redstone reader, put variable card _(A)_ in slot for reading integer signal
2. Place variable store connected to redstone reader
3. Create integer constant _(B)_ in logic programmer and use the '>' operator to program a variable card to compare _(A)_ to _(B)_, creating _(C)_
4. Place display panel connected to redstone reader and variable storre
5. Place _(A)_ and _(B)_ in variable store
6. Place _(C)_ in display panel, observe crash

### Expected behaviour

The display panel should show the proper output of C

**Comment by Gaz492** [comment]
Closing this as it's the same underlying issue as mentioned in #5594 which should hopefully be fixed in the next pack update
