### ISSUE TITLE
[Bug]: Aspen Trapdoors cannot be turned back into planks in a Precision Sawmill

### ISSUE THREAD

**Issue by Newbytee** [FTBTeam/FTB-Modpack-Issues#561]
### Modpack

FTB Endeavour

### Modpack version

1.8.0

### Describe the bug

Unlike most other trapdoors, aspen trapdoors cannot be turned back into planks in the Precision Sawmill. This may also be the case for other trapdoors from Oh The Biomes You'll Go.

### Steps to reproduce

1. Put an aspen trapdoor in a Precision Sawmill
2. Observe that nothing happens
3. Put an oak trapdoor in a Precision Sawmill
4. Observe that it gets turned into planks

### Expected behaviour

The aspen trapdoor should get turned into planks.

**Comment by Raidobw2** [comment]
Will look into it, thanks for the report

**Comment by Newbytee** [comment]
Not sure what kind of reply I'm supposed to provide here.

**Comment by Newbytee** [comment]
Not sure what kind of reply I'm supposed to provide here.

**Comment by Newbytee** [comment]
If you just don't support this modpack any more please say that instead.

**Comment by Newbytee** [comment]
Not sure what kind of reply I'm supposed to provide here.

**Comment by Newbytee** [comment]
Not sure what kind of reply I'm supposed to provide here.

**Comment by Gaz492** [comment]
Apologies for the lack of any communication here and the annoying stale bot, unfortunately we are no longer releasing updates for this modpack, so this issue is likely never going to be fixed.
