### ISSUE TITLE
Quest description error: "invalid formatting can't nest multiple substitutes"

### ISSUE THREAD

**Issue by Linx-ESP** [FTBTeam/FTB-Modpack-Issues#5610]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

Some quests show a red text (seems like an error):  
  "Invalid formatting! Can't nest multiple substitutes"  
    
Quest that I have found have this issue:

- Ch. 2: Ferricore Ingot (page 2)
- Ch. 3: Full Steam Ahead!

### Steps to reproduce

1. Open quest book/page/window
2. Click on certain quests
3. Text description contains this error

### Expected behaviour

Either this text shouldn't show or something else should be in its place

### Screenshots

![image](https://github.com/user-attachments/assets/ec77d59c-1f70-4367-9af9-845ccba2f6a5)

### Additional information

I play the game in Spanish (es-es), changing back to English (US) with out restarting doesn't solve it. Haven't test full restart.

**Comment by nageih** [comment]
This is an issue with the translation key we added and will be fixed in 1.7
