### ISSUE TITLE
Feeding item for productive bees not showing in JEI

### ISSUE THREAD

**Issue by Nirke31** [FTBTeam/FTB-Modpack-Issues#5612]
### Modpack

FTB Genesis

### Modpack version

1.6.1

### Has the pack been modified

No

### Describe the bug

Unless I am mistaken, there is no way of knowing what feeding item a productive bee needs to produce its corresponding comb. 
- JEI does not show it and only tells me to look up the crafting receipt for the egg.
- There is no description of the actual bees in the game in the Big Book of Bees, the guide. 

### Steps to reproduce

No steps

### Expected behaviour

JEI showing the feeding item

### Screenshots

![grafik](https://github.com/user-attachments/assets/3f6d3bdd-ff6d-4c63-a93f-483b91844d91)
![grafik](https://github.com/user-attachments/assets/5e6e8beb-3cb4-4118-891f-714cea193153)
![grafik](https://github.com/user-attachments/assets/db396973-611b-43ab-a1de-d1236947113f)

### Additional information

Additionally, all (most?) recipes, feeding items, etc. have been changed. Which is good because else this mod would not be possible, but you cannot look up the feeding item online, as it has been changed. I had to watch a yt video to find out that the infernium bee needs an infernium block to work. For the ender bee, I just tried out random end items in creative until one worked. 

I created a bug and not a suggestion as this destroys the whole use of productive bees. It is completely unusable, which makes me think I must have missed something, but I cannot find the feeding items for the bees.

**Comment by Nirke31** [comment]
For everyone facing the same problem, my current workaround is to look into the mod sources.
How to:
1. Open Instance folder of FTB Genesis
2. Go into "mods" folder. 
3. Search for "productivebees" and copy the .jar somewhere else (desktop for example). 
4. Rename the file ending of the just copied productive bees jar from ".jar" to ".zip".
5. Open the zip and navigate to "./data/productivebees/produtivebees/".
6. In there you will find .json files for all types of bees and some seetings for them. You have to search here or in the available subdirectories for the bee you have. For example, for the fire crystal bee you first open the "elementalcraft" folder and in there you will find the "fire_crystal.json".
7. Open the .json of your respective bee and search for the key "flowerBlock" or "flowerTag" (note: there may be other names instead of only these two). The value is the item you need for feeding your bee.

**Comment by ArtpokeBr** [comment]
In the Next Update Spawn Eggs will be unhidden to make things easier, but you should be able to craft Bee specific Genes then make the Spawn Eggs for what you want.
