### ISSUE TITLE
Item recipes disappear/failing to properly validate

### ISSUE THREAD

**Issue by Saureil** [FTBTeam/FTB-Modpack-Issues#5616]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

Over the past few days, I have been noticing that each instance I run will validate (or fail to) recipes for early game materials. Example, last night I tried to throw my raw copper in the bronze steam macerator and nothing happened, checked EMI and there was no macerator recipe. I start it this morning and it starts chewing through my copper right away. Same with several other ores/item recipes in the crafting table. Not sure if this is just a failure of RAM allocation on my part, but any info helps. 

### Steps to reproduce

8gb ram allocated, start instance, try to macerate raw ores. Any ores that it fails to macerate, take note. Shut down and restart instance, then try to drop those ores in the macerator again. 

### Expected behaviour

All my recipes to still exist so I dont have to dedicate a chest to raw ores that wont work.

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
