### ISSUE TITLE
NeoTech lag spiking every few seconds

### ISSUE THREAD

**Issue by ehcraftermc** [FTBTeam/FTB-Modpack-Issues#5619]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Log Files

https://spark.lucko.me/1hNLOdY9T3

### Describe the bug

Every few seconds i get a lag spike. I tried disabling better f3 and removing my jvm arguments which helped reduce it, but not eliminate it

### Steps to reproduce

Problem is constant without a known issue. 

### Expected behaviour

Game should be smooth.

### Screenshots

https://youtu.be/-7LggRcNOkM

**Comment by Saereth** [comment]
let me know if the issue persists in 1.7.0+ of the pack (releasing today) lots of mods updated so we'll see if it hopefully got resolved

**Comment by ehcraftermc** [comment]
Alright. I'll give it another try.
