### ISSUE TITLE
[Bug]: Stoneblock 2, JER Crash

### ISSUE THREAD

**Issue by Subbmi00** [FTBTeam/FTB-Modpack-Issues#562]
### Modpack

FTB Stoneblock 2

### Modpack version

1.21.1

### Log Files

[crash-2022-01-14_21.57.21-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7873830/crash-2022-01-14_21.57.21-client.txt)
[crash-2022-01-14_22.10.47-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7873831/crash-2022-01-14_22.10.47-client.txt)

### Describe the bug

I found a game crashing bug in Stoneblock 2. Me and my friend is playing on a server that I made and we tried to find out how you get feathers. When we looked at the different ways to obtain it, we pressed the mob drop page and the game minimized into a small square, and the rest of the screen started to screen tear. The game then crashed and i got the message that a crash had occured. I just want you guys to know incase it might happen to others, cuz then you might want to fix it. I found out that the mods name is "just enough resources" or JER.

### Steps to reproduce

1. Open inventory (in Stoneblock 2)
2. Search for feathers
3. Press Feathers and press at the "Mob Drops" page, this is where the crash happened for me and my friend.

### Expected behaviour

To see how to get feathers?? Or what do i type here?

### Screenshots

![66388695250__7F38CF8B-3E8A-44F4-BDD1-3ECADE85E286](https://user-images.githubusercontent.com/97768507/149599391-69a8b263-e479-45f4-87cd-24839413ae07.jpg)

**Comment by Raidobw2** [comment]
I'll need to check it in-dev, looks like an issue caused by JER indeed `jeresources.util.RenderHelper.renderEntity` fails to draw correctly while trying to render an entity inside the JEI window. Thanks for the report, for now, don't check that tab.

All chickens drop feathers, that's probably what was written
