### ISSUE TITLE
FTB NeoTech v1.6.0 item tags missing / changed

### ISSUE THREAD

**Issue by Anoyomouse** [FTBTeam/FTB-Modpack-Issues#5620]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

I'm on the Edge of the HV chapter and wanted to make the EE stuff, but i can no longer make blazegold

~It looks like Modern Industilization coke dust no longer has the `forge:dusts/coal_coke` tag, which means we can't make blazegold~

Looks like immersive engineering coke was removed in a previous version, but i'm now stuck with immersive coke coal

There is also no way to make immersive engineering wires, so you cannot make wire coils, so you can't make some of the mekanism machines because you cannot make the LV coils.

~I would suggest adding the `forge:dusts/coke` to MI `coke_dust`, and changing the recipes to use that tag instead of `forge:dusts/coal_coke`~

I would also suggest tagging MI wires with the `forge:wires_copper` (and variants) and then changing the recipes to use the tagged items
```
immersiveengineering:wire_copper
 - #immersiveengineering:circuits/solder
 - #forge:wires
 - #forge:wires_copper
```

### Steps to reproduce

Start a game with cheats, make an immersive alloy kiln, and a coke oven, make some coke dust, and some raw blazegold, and you cannot make it with the MI coke dust

You can also look at the recipies for the copper wires from immersive, you cannot create them, and see they are used, but you cannot get an alternative for these

### Expected behaviour

have some options for lv_coils, and for coke coal (or a way of making blazegold semi late game

**Comment by Anoyomouse** [comment]
Just looking back at the game .. was this a byproduct of us upgrading from one of the previous versions, where the coke oven used to create the immersive engineering coke instead of the MI coke?

**Comment by Saereth** [comment]
looks like a bad install previously causing some missing unification scripts, it should always have been/should always be MI coal dust. Just verified in dev and server and its definitely MI coal dust and working as intended

<img width="640" alt="image" src="https://github.com/user-attachments/assets/a33c84da-05e8-4505-803e-9cb56302e852">
