### ISSUE TITLE
Chisel doesn't have a recipe or isn't shown in EMI

### ISSUE THREAD

**Issue by Linx-ESP** [FTBTeam/FTB-Modpack-Issues#5621]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

The chisel from "Just Another Chisel Mod" either doesn't have a recipe or it isn't shown in EMI

### Steps to reproduce

1. Open Inventory and EMI
2. Search for "chisel"
3. Press "show recipe" key on top of JACM's chisel

### Expected behaviour

Show the recipe

### Additional information

Any recipe for that mod (block-wise) only shows the option to be made in an stonecutter or similar, not with a chisel.    
Searching quests for "chisel" or "decorative" doesn't show anything, which might help if there is another way to make this from other mod.

**Comment by Saereth** [comment]
this is not a bug, we moved all chisel functionality to the stone cutter for automation
