### ISSUE TITLE
No faucet on bedrock edition? Tinker construct 

### ISSUE THREAD

**Issue by Frisoow** [FTBTeam/FTB-Modpack-Issues#5622]
### Modpack

Other...

### Modpack version

The newest I guess 

### Has the pack been modified

No

### Describe the bug

Me and some friends tried to build the smeltery on bedrock but we couldnt find the faucet anywhere in the recipes. So we went on YouTube figuring out how to. We found it and tried the correct recipe but it doesn't work for some reason 

### Steps to reproduce

Create a realm or world with the tinker construct add-on activated and try to craft a faucet

### Expected behaviour

It doesnt show up 

### Screenshots

![931d21d0-fbc0-4dc6-9878-c51dd9317aa4](https://github.com/user-attachments/assets/ce2b1922-80e2-4dc2-95c1-76e20763fc70)

### Additional information

I don't know if I have to restart the realm because idk if I'm doing something wrong or that its actually missing

**Comment by Gaz492** [comment]
There is a slight difference with the bedrock version where there is no faucet, instead extracting the fluids is done via the drain block
https://docs.feed-the-beast.com/docs/marketplace/Addons/tinkers/Docs/The%20Smeltery%20&%20Beyond/#seared-drain
