### ISSUE TITLE
Missing items charging station for all gadgets

### ISSUE THREAD

**Issue by jhendrix61978** [FTBTeam/FTB-Modpack-Issues#5623]
### Modpack

FTB Unstable 1.21

### Modpack version

1.0.1

### Has the pack been modified

No

### Describe the bug

basic charging station for all the gadgets is missing no way to craft cannot charge mining gadget or any of the building gadgets looks like the charging gadgets mod by direwolf is missing

### Steps to reproduce

open crafting grid search for charging gadget 
nothing found 

### Expected behaviour

to see and be able to craft charging gadget

**Comment by jhendrix61978** [comment]
charging Gadgets mod is what is missing does not seem to be included in the pack

**Comment by ArtpokeBr** [comment]
You don't exactly need Charging Gadgets to Charge stuff, you can use Mekanism's Energy Cubes for example.

But, I feel like adding Charging Gadgets shouldn't be a big deal, so it will be present next update :)
