### ISSUE TITLE
Integrated Dynamics Redstone Writer Crashing Server

### ISSUE THREAD

**Issue by Ayrtonno** [FTBTeam/FTB-Modpack-Issues#5626]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

Crashing when trying to send a redstone signal to any blocks using the redstone writer. It happened everytime when inserting the boolean card inside the writer.

### Steps to reproduce

1. Connect a redstone writer to anything.
2. Input a boolean card properly set that should turn on the redstone writer. 
3. Server crashes istantly.

### Expected behaviour

Not crashing the server.

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by Ayrtonno** [comment]
[2024-08-10-5.log](https://github.com/user-attachments/files/16591248/2024-08-10-5.log)

Here's the log from the crash while testing it.

**Comment by Saereth** [comment]
duplicate
