### ISSUE TITLE
Randomly losing fluids from Mekanism Portable Tanks when picking them up with a wrench.

### ISSUE THREAD

**Issue by Ayrtonno** [FTBTeam/FTB-Modpack-Issues#5627]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

Sometimes, when picking up a full/partially full mekanism dynamic tanks with a wrench (both modern industrialization and just dire things ones) they lose all their content.
More often then not, it happens when an empty tank is already present in inventory.
Happened multiple times with Synthetic Rubber and Creosote.
Tried on fresh install, client and server, out of 100 tests, 17 times fluid was lost on pickup, merging the empty and non empty tanks.

### Steps to reproduce

1. Pick up with a wrench any mekanism portable tank filled with fluids.
2. Check inventory if the tank has still anything inside.

### Expected behaviour

Tanks retaining their content.

**Comment by chrisjgray** [comment]
Ah, I had the same issue and came to look for this.

**Comment by Saereth** [comment]
duplicate issue report
