### ISSUE TITLE
[Bug]: FTBIC Iron Furnance stuck smelting if using Immersive Engineering External Heater

### ISSUE THREAD

**Issue by zediious** [FTBTeam/FTB-Modpack-Issues#563]
### Modpack

FTB Ultimate: Anniversary Edition

### Modpack version

1.2.0

### Describe the bug

It appears that if an Immersive Engineering External Heater is used to power an FTB Industrial Contraptions Iron Furnace, the Iron Furnace become stuck infinitely smelting. I am unsure if this is related to [this previous issue](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/545), but it is not just a visual bug.

### Steps to reproduce

1: Place an Iron Furnace next to an External Heater, and give the External Heater power.
2: Place something to smelt in the furnace.
3: Watch the furnace not complete the smelt task

### Expected behaviour

The furnace complete the smelt task

### Screenshots

![1](https://cdn.discordapp.com/attachments/916808914828423168/931973868040638474/lol_prog.PNG)
![2](https://cdn.discordapp.com/attachments/916808914828423168/931974084978425956/lol_prog_bug.PNG)

**Comment by Raidobw2** [comment]
Thanks for the report and the picture, I'll look into it whenever I can and report back here
