### ISSUE TITLE
FTB neotech Void dimension has no sunlight

### ISSUE THREAD

**Issue by Ch4rm-Quark** [FTBTeam/FTB-Modpack-Issues#5630]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

within the void dimension included with the pack, the world is described as "always sunny" in the quest, however it does not qualify  any solar thing's requirement for sunlight. (so far, at least. I am only up to LV, so some solar devices may work at higher tiers of power) specifically I am seeing issues with the StevesCarts solar generators, and the EnchantedBlocks solar enchantment for furnace type blocks. 

### Steps to reproduce

go to the void

place furnace with Solar radiance

place cookable item inside

item does not cook

### Expected behaviour

steve's cart charges / furnace cooks

### Screenshots

![2024-08-11_20 03 04](https://github.com/user-attachments/assets/907a61f9-76ae-424c-b7fa-014cfabab5aa)

### Additional information

also fell off and realized that there is indeed not a gravestone mod in this pack. might want to put a info quest to mention that in the starting section.

**Comment by Saereth** [comment]
not a bug, its intentional at to not provide an always days environment for solars. There is a gravestone mod in the pack however (Simply graves), so maybe something is messed up with your install?
