### ISSUE TITLE
Thermoelectric Generators do not accept MI uranium blocks

### ISSUE THREAD

**Issue by koh-gh** [FTBTeam/FTB-Modpack-Issues#5637]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

IE Thermoelectric Generator does not work with MI uranium block, even I can get this item as a reward.
IE uranium block and Mek uranium block works fine but I cannot get them.

### Steps to reproduce

1. Place Thermoelectric Generator
2. Place cold block like blue ice on one side and place MI uranium block on opposite side
3. No FE is generated

### Expected behaviour

generate FE

**Comment by Saereth** [comment]
fixed in next update
<img width="1304" alt="image" src="https://github.com/user-attachments/assets/6745e67c-82f5-44c4-b6eb-d5b762966e0c">
