### ISSUE TITLE
Menril leaves aren't affected by hoes like regular leaves

### ISSUE THREAD

**Issue by DragonBuster10k** [FTBTeam/FTB-Modpack-Issues#5638]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

Integrated Dynamics menril leaves are only affected by shears, and aren't affected by any other tools like a hoe that works on other leaves. I was recently hunting down a few menril trees and noticed they dropped the leaves themselves as opposed to saplings and the like, so I decided I would place the leaves down and break them manually (since I wanted more saplings to replant). I tried using a diamond hoe I found while out exploring and noticed it doesn't affect them, so I had to mine them by hand*.

### Steps to reproduce

1. Plant/find a menril tree, or just place down the leaves
2. Break them with an empty hand in survival mode, and take note of the speed
3. Try breaking them with some sort of hoe, e.g. diamond in my case
4. Notice how the break times aren't affected
5. Use shears on them too to notice how they are instamined

### Expected behaviour

I expected the diamond hoe to instamine the menril leaves much like it does with other leaf variants, but instead it didn't have an effect.

### Screenshots

![2024-08-15_12 55 46](https://github.com/user-attachments/assets/7e8bfbd7-676a-4007-bacb-6eef75efb823)
Notice that mining it normally obviously doesn't instamine (to be expected).

![2024-08-15_12 56 26](https://github.com/user-attachments/assets/080d89b2-79f9-4b5d-abe7-4600d2c4b2eb)
Mining with a regular diamond hoe doesn't instamine.

![2024-08-15_12 56 54](https://github.com/user-attachments/assets/8d78a2d8-4ebe-402e-8722-24f9f4636ebf)
Even if it's enchaned with efficiency 5, no difference.

(By the way, I tried making a superflat world for these screenshots, but it didn't work. See #5639 for more info.)

### Additional information

(I did use tick rate 5 to get those screenshots easier but I can assure you that the speeds are no different when tested with regular tick rate too. *Also, when I found out about this in my real survival world I didn't end up mining them by hand, I used shears instead since the leaves seemed to drop themselves for some reason anyway.)

**Comment by Saereth** [comment]
this is not a bug, the Integrated dynamics dev has specifically set them to be shears only as the valid tool, you could open a feature request with them to add hoe support additionally
