### ISSUE TITLE
Custom world types don't work (superflat, etc.)

### ISSUE THREAD

**Issue by DragonBuster10k** [FTBTeam/FTB-Modpack-Issues#5639]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

When trying to create a world with a custom type, such as superflat, single biome, etc., it loads in as a regular world as opposed to the custom type (I found this out when trying to test for #5638, I wanted to create a creative superflat world but couldn't)

### Steps to reproduce

1. Open the new world screen
2. Select the "superflat" world type (or any others like single biome or amplified*)
3. Create the world and notice that it generates with default world gen instead of superflat

* I haven't tested it with amplified and the others, I've only tested it with superflat and single biome so far.

### Expected behaviour

I expected it to generate a superflat world as opposed to a default-gen world

### Screenshots

![2024-08-15_12 51 29](https://github.com/user-attachments/assets/b7e4a6e2-cceb-402b-bf64-98f15817333a)
Proof of selecting the superflat world type option.

![2024-08-15_12 52 50](https://github.com/user-attachments/assets/94e27c2d-1a06-4c44-aa81-0e072c4b713b)
The exact same world after I created it.

### Additional information

I've tested this multiple times too just to ensure I didn't happen to misclick or anything, and can confirm it doesn't work. I believe this is most likely a problem with Terralith since I've noticed this a lot with other custom world gen mods in the past on other packs.

**Comment by Saereth** [comment]
yeah flat worlds will definitely break with this pack and are not supported directly. We've recently added Just another minig dimension so if you're looking for a superflat style playthrough it could be an option for you.
