### ISSUE TITLE
[Bug]: Unable to obtain Ender Dragon Essence using RFTool's Syringe

### ISSUE THREAD

**Issue by ixanza** [FTBTeam/FTB-Modpack-Issues#564]
### Modpack

FTB Oceanblock

### Modpack version

1.11

### Describe the bug

I'm trying to automate the ender dragon spawning. The only way I can think of is using the RFTools Spawner however I am unable to obtain any ender dragon essence from hitting it with a syringe.

Here's a video of me trying
https://mega.nz/file/pBByUbqa#L6v7qP7ogxgU8k1dtaFwEp41rcWLrvDK-ynhSBe8FSM

I have tried without the Ender Dragon being in stasis as well it doesn't work

### Steps to reproduce

1. Make Syringe
2. Hit Ender Dragon with Syringe
3. Syringe doesn't fill up

### Expected behaviour

Syringe fills up

### Additional information

Is there any other way to automate the ender dragon? I have no clue how integrated dynamics works and nothing else can actually place the end crystals to respawn the dragon.

**Comment by quietust** [comment]
Out of curiosity, for what purpose are you trying to automate the Ender Dragon?

**Comment by ixanza** [comment]
> Just out of curiosity, for what purpose are you trying to automate the Ender Dragon?

stupid self imposed challenge of not using mystical agriculture for production

**Comment by Raidobw2** [comment]
Unfortunately I don't think we can change the RFTools config to allow that. It looks like it only has one config field in 1.16. I'll talk with the modpack dev when I get the chance and see if we can add alternatives.
![image](https://user-images.githubusercontent.com/17010632/150261873-8c89c8da-40cc-4e21-8391-1fad440f56ba.png)

**Comment by ixanza** [comment]
Since I made this issue I found out you can automate placing the End Crystals using Player Simulators from Integrated Tunnels. However this has 2 issues:

1. Spawning the dragon causes a lag spike across the server
2. You need to be present in the end for this automation to work

I did do this over the course of 3-4 nights and I think I have enough Dragon Hearts and Dragon Eggs for this playthrough.

Yes I do understand seeds exist for this. I hope another alternative shows up. So far I've been able to automate everything the Ultimate Singularity requires without MA production crops. Getting Awakened Draconium requires Dragon Hearts which is what I was setting this farm up for

**Comment by Raidobw2** [comment]
I like the suggestion, so I'll definitely try to look into an opportunity to add an alternate way to complete the modpack, without MA. Thanks for the precision about the behavior of the dragon in the End as well.
