### ISSUE TITLE
Lettuce is a fruit?

### ISSUE THREAD

**Issue by jfbarras** [FTBTeam/FTB-Modpack-Issues#5644]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

The forge:fruits/vegetables as well as the neoforge:fruits/vegatables tag is confusing.
I think it should be crops/vegetables. It would make for better organisation, filters.
Looking for vegetables in JEI gives you different results (forge vs neoforge).
To look for fruits, you need to look for fruits/fruits, with varying results (forge vs neoforge).

### Steps to reproduce

Go in JEI.
Look for #fruits
Get all kinds of things, like lettuce.

### Expected behaviour

Improve tags

### Additional information

Nothing too game-breaking here.

**Comment by Saereth** [comment]
Yeaah this is a weird pams thing, not us lol I guess a lettuce is a fruit now XD
