### ISSUE TITLE
Map doesn't work

### ISSUE THREAD

**Issue by 7amoudy** [FTBTeam/FTB-Modpack-Issues#5648]
### Modpack

FTB Unstable 1.21

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

Honestly, I don't know how else to say this, but the map doesn't open at all. The M key (default map key) does not do anything and the FTB chunks button when the inventory is opened also seems to be taking the day off. this is my first time playing this pack and I don't know how it works. if u can fix it that would be nice because this seems like an awesome pack, regards *redacted*

### Steps to reproduce

Press M

### Expected behaviour

Map

### Screenshots

Can't screenshot an invisible Map

**Comment by ArtpokeBr** [comment]
This Issue seems to be fixed with a recent Mod Update, please reopen this issue if still persists after the next update.
