### ISSUE TITLE
Crash after 10/20 minutes of gameplay

### ISSUE THREAD

**Issue by Superredstone** [FTBTeam/FTB-Modpack-Issues#5650]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Log Files

https://pste.ch/eqomatuqib.md

### Describe the bug

After 10/20 minutes of gameplay the game has a lag spike and after 1 minute or so the game crashes

### Steps to reproduce

1. Enter a world (mp or sp) 

### Expected behaviour

The game should not crash

### Additional information

OS: Arch Linux (6.10.5)
GPU: NVIDIA RTX 4060 
CPU: 13th Gen Intel® Core™ i7-13620H
RAM: 16GB DDR5

**Comment by Saereth** [comment]
I need an actual crashlog from your crash-reports folder please

**Comment by Superredstone** [comment]
After updating the problem seems fixed
