### ISSUE TITLE
Impossible to craft "Lens of the Killer (WIP)" with the available "Sharpness V" books

### ISSUE THREAD

**Issue by nefalem** [FTBTeam/FTB-Modpack-Issues#5651]
### Modpack

FTB NeoTech

### Modpack version

1.6.0

### Has the pack been modified

No

### Describe the bug

I can't craft the Lens of the Killer using a "Sharpness V" book.

### Steps to reproduce

Try to craft a Lens of the Killer in a crafting table.

### Expected behaviour

I expect to be able to craft a "Lens of the Killer" using the "Sharpness V" I have

### Screenshots

![What I have](https://github.com/user-attachments/assets/b03761fd-f35d-4017-944e-ffd253d04e79)
![Capture d'écran 2024-08-19 002013](https://github.com/user-attachments/assets/58c0d93f-eb7f-418a-9322-72dd49622630)

**Comment by Microjett** [comment]
Can confirm that this is NOT fixed in 1.7.0 of Neotech. Enchanted book appears to be correct as far as I can tell. It matches all the way down to the NBT tags but still JEI flags the book as not correct and the recipe does not work.

**Comment by 0lli729** [comment]
Issue persists in 1.10.1 of Neotech as described by Microjett

**Comment by xxhertz** [comment]
still an issue 1.11.2
