### ISSUE TITLE
Crash whenever I search the word "egg" and "chicken" in JEI

### ISSUE THREAD

**Issue by Medic0525** [FTBTeam/FTB-Modpack-Issues#5652]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Has the pack been modified

No

### Describe the bug

The game would lag out and eventually crash whenever i search the word "egg" or "chicken" in stoneblock 3

### Steps to reproduce

1. open inventory
2. tap on search bar
3. input "egg" or "chicken"

### Expected behaviour

The game crashes

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by Medic0525** [comment]
[2024-08-20-4.log.gz](https://github.com/user-attachments/files/16674322/2024-08-20-4.log.gz)

**Comment by Medic0525** [comment]
Alright, here.
[debug.log](https://github.com/user-attachments/files/16674366/debug.log)
[latest.log](https://github.com/user-attachments/files/16674367/latest.log)

**Comment by Reble45** [comment]
Confirmed. As a matter of fact I came here to report the same bug.
[debug.log](https://github.com/user-attachments/files/16798541/debug.log)
[rei.log](https://github.com/user-attachments/files/16798542/rei.log)
[latest.log](https://github.com/user-attachments/files/16798543/latest.log)
[rei-issues.log](https://github.com/user-attachments/files/16798544/rei-issues.log)

**Comment by Gaz492** [comment]
Thanks, just a quick question, does this generate a crash report in the crash-reports folder for any of you?
