### ISSUE TITLE
ERROR projectE when join or create a new world

### ISSUE THREAD

**Issue by Mostafa103319** [FTBTeam/FTB-Modpack-Issues#5654]
### Modpack

FTB Continuum

### Modpack version

1.6.0

### Has the pack been modified

Yes

### Describe the bug

well i traid to disable oeintegration and i did but i did alot other thing before i was able to do it 
now after i disable it it show the photo i submit  up there
idk what i did wrong and i did re-install it from the launcher and the cursedforge and still show up 
idk if it's normal thing or no 
i did not disable oeintegration after i re-installed it 

### Steps to reproduce

go to mods in game 
search for oreEx
go to confg of the sec one 
disable the mode 

### Expected behaviour

i expected to disable the mod and nothing else will happen after it 

### Screenshots

![Screenshot_38](https://github.com/user-attachments/assets/460eff6a-9f27-4406-ad23-7ac02b51ebef)

**Comment by Gaz492** [comment]
Could you try the following?

Right click the modpack in the app, hover over `Open folder` and click on `Instance folder`

In the window that opens open the mods folder then find the `oeintegration-2.3.4.jar` and delete it.

Now try starting the modpack and see if the errors still happen.
