### ISSUE TITLE
StoneBlock 3 fails to launch on macOS with an "[LWJGL] Failed to load a library." error

### ISSUE THREAD

**Issue by Daz-wallace** [FTBTeam/FTB-Modpack-Issues#5663]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Has the pack been modified

No

### Log Files

[console.log](https://github.com/user-attachments/files/16715534/console.log)
[debug.log](https://github.com/user-attachments/files/16715535/debug.log)
[latest.log](https://github.com/user-attachments/files/16715536/latest.log)

### Describe the bug

When trying the launch StoneBlock 3 from the FTB launcher, a long list of output is shown, followed by a warning that the instance crashed during startup or whilst running. The full debug log ends with the following output:
```
[LWJGL] Loading library (system): lwjgl
[LWJGL] 	liblwjgl.dylib not found in java.library.path
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
```

With the same device and software, the mod packs StoneBlock 2 (version 1.23.0) and Better MC (version 30.5) load fine

### Steps to reproduce

1. Install FTB launcher 
2. Install FTB StoneBlock 3 
3. Click Launch
4. Allow full launch process to start
5. Wait for error
6. No other windows, applications or instances are launched 

### Expected behaviour

1. Launch process to complete
2. Instance to launch

### Screenshots
<img width="1499" alt="Screenshot 2024-08-22 at 18 47 47" src="https://github.com/user-attachments/assets/8cd49245-a5a5-4328-93e8-ac3f27760356">

### Additional information
MacBook Pro 13-Inch, M1, 2020
[LWJGL] Version: 3.2.1 SNAPSHOT
[LWJGL] 	 OS: Mac OS X v14.6.1
[LWJGL] 	JRE: 17.0.2 aarch64
[LWJGL] 	JVM: OpenJDK 64-Bit Server VM v17.0.2+8 by Eclipse Adoptium

**Comment by Gaz492** [comment]
Try downloading and installing the Java version linked below, then open the app and right-click the modpack in the app, click settings then scroll down until you see a Java Version setting.

If you click on the text `Recommended` it should show a list of Java versions available on your Mac

Click on the one that looks like `Eclipse Adoptium - 17.0.12 JRE (X64) - /Library/Java/JavaVirtualMachines/temurin-17.jre/Contents/Home/bin/java` (if it doesn't show up, try restarting the app) then try starting the modpack again.

https://adoptium.net/temurin/releases/?os=mac&arch=x64&package=jre&version=17

**Comment by Daz-wallace** [comment]
Thanks @Gaz492, that got me further along but I'm seeing a crash much later on in the load process. I'm guessing something/s in the mod pack require an Intel compiled version of Java rather than Apple Silicon. 
A Java instance spawns, and the log shows that it should be running but I'm not seeing a game window.
Less then a minute later, the launcher shows that the instance has crashed.
Screenshot and logs:
<img width="1501" alt="Screenshot 2024-08-23 at 10 05 39" src="https://github.com/user-attachments/assets/dfa53267-a4ed-4aa1-a061-6f60cfa05f11">
[console.log](https://github.com/user-attachments/files/16726383/console.log)
[debug.log](https://github.com/user-attachments/files/16726384/debug.log)
[latest.log](https://github.com/user-attachments/files/16726385/latest.log)
[rei-issues.log](https://github.com/user-attachments/files/16726386/rei-issues.log)
[rei.log](https://github.com/user-attachments/files/16726387/rei.log)

**Comment by Gaz492** [comment]
Im not 100% sure what the issue here is, but could you try the steps mentioned in the following guide?
https://docs.feed-the-beast.com/docs/app/Troubleshooting/disable-hide-progress

**Comment by Daz-wallace** [comment]
Hi @Gaz492 
Thanks for that suggestion, it has allowed the main screen to load fine. I'll give it a full test next week but happy to close this one off.
Looks like the original issue was something in the StoneBlock 3 mod pack needs Intel JRE instead of the Apple Silicon one.
The additional issue looks to be something with the option you've linked above.
Thank you again!

**Comment by Gaz492** [comment]
Great to hear, if you run into any further issues, feel free to either reopen this issue or create a new one.
