### ISSUE TITLE
Diorite appears absent from world gen

### ISSUE THREAD

**Issue by NeuralLink** [FTBTeam/FTB-Modpack-Issues#5666]
### Modpack

FTB Builders Paradise 2

### Modpack version

1.2.0

### Has the pack been modified

No

### Describe the bug

I have explored all around the world, both above and below ground and have been unable to find any diorite.

### Steps to reproduce

Go to y 20 and branch mine for significant distances. No diorite found.

### Expected behaviour

Diorite appears in the world

**Comment by NeuralLink** [comment]
Shortly after filing this bug, I discovered my first vein of diorite. It is oddly only one block wide, but quite tall and long.

**Comment by Saereth** [comment]
yeah it generates in large veins, glad you found some
