### ISSUE TITLE
Game dont responding

### ISSUE THREAD

**Issue by Filpus** [FTBTeam/FTB-Modpack-Issues#5670]
### Modpack

FTB Interactions Remastered

### Modpack version

1.1

### Has the pack been modified

No

### Describe the bug

The aplication stops responding at random times. This usually happens when you enter a menu or complete a task. 
The longer I play, the more often the game freezes and after about an hour it becomes unplayable.
Problem also happens in main menu.  
I was playing on lan muliplayer only, but i have good internet (300 Mb/s)

### Steps to reproduce

This is malicious error

### Expected behaviour

Not lagging and unresponding 

### Additional information

Device Specifications:
System: Windows 10 PRO
CPU: Intel(R) Core I5-1135G7 @ 2.4 GHZ 
GPU: Integrated - Intel Iris Xe Graphics
Ram assigned: 6,8 GB

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by for-lack-of-a-better-name-j** [comment]
Guys, I have this exact same problem, but for regular Interactions. Can I upload my logs here?
