### ISSUE TITLE
Can’t start game stuck on Mojang loading screen 

### ISSUE THREAD

**Issue by Luu7yn** [FTBTeam/FTB-Modpack-Issues#5671]
### Modpack

FTB Skies Expert

### Modpack version

Latest

### Has the pack been modified

No

### Log Files

Don’t have one or not sure how to 

### Describe the bug

When I click play on the ftb skies expert mod pack it’s load and is stuck on the Mojang loading screen 

### Steps to reproduce

Not sure 

### Expected behaviour

Install the mod pack. Play the game

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by Luu7yn** [comment]
Hello,

sorry forgot to close post. It’s seems to have fixed itself so it’s working right now. 

Thank you for taking your time to read the post 

good day
