### ISSUE TITLE
Client crash to title when combining Multiblock'd and JEC

### ISSUE THREAD

**Issue by Delfayne** [FTBTeam/FTB-Modpack-Issues#5672]
### Modpack

FTB Interactions Remastered

### Modpack version

1.0.1

### Has the pack been modified

No

### Log Files

https://mclo.gs/ae5wZwt

### Describe the bug

Attempting to use Multiblock'd controllers in calculation recipes crashes instantly. However, Mbd hatches etc seem fine

### Steps to reproduce

Open JustEnoughCalculation's Crafting calculator and attempt to put any Multiblock'd controller into the calculator (e.g. Improved Coke Oven). Imm

### Expected behaviour

To be able to use mbd and JEC together

**Comment by ArtpokeBr** [comment]
Added a Tooltip to Inform players about this.
