### ISSUE TITLE
Add 'Sound Device Options' Mod

### ISSUE THREAD

**Issue by lurch9229** [FTBTeam/FTB-Modpack-Issues#5674]
### Modpack

FTB Interactions Remastered

### Is your suggestion related to a problem? Please describe.

Older versions of Minecraft do not have the ability to change the sound device during play. If you get a headset disconnect or do a sleep with MC running etc. it will break the sound, requiring a pack restart.

This simple mod allow the changing of the sound device from the Music & Sounds options, mimicking new versions of MC

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/more-sound-config

**Comment by Delfayne** [comment]
Random Tweaks is in the mod that allows a reload of the sound system with Shift F8

**Comment by ArtpokeBr** [comment]
Good Suggestion :)
