### ISSUE TITLE
Network Protocol Error

### ISSUE THREAD

**Issue by TurboHass3** [FTBTeam/FTB-Modpack-Issues#5675]
### Modpack

FTB Unstable 1.21

### Modpack version

1.0.1

### Has the pack been modified

No

### Log Files

https://pste.ch/ufixafavij.coffeescript

### Describe the bug

3 people got this error at almost the same time, 2 local and 1 remote on a privately hosted server, we played last night with no issues and it just came out of the blue, no crafting was done or anything new so to speak.

Tried restarting the server and clients with no luck.

### Steps to reproduce

Cant connect to server without error in the Loading Terrain step

### Expected behaviour

Successful server login

**Comment by Gaz492** [comment]
First off, before trying what I suggest below, I would recommend you make a copy of your world just in case it breaks even more.

Would you be able to try disabling the trashcans mod on both the server and your clients, then see if the server starts up again and allows you to connect?

If you are able to start the server and connect, you should then be able to stop the server and your client then re-enable the trashcans mod.
