### ISSUE TITLE
[Bug]: https://paste.atlauncher.com/view/a0aefb4c-73c2-4be9-b843-d46e0efb81d6

### ISSUE THREAD

**Issue by Leafytreetops** [FTBTeam/FTB-Modpack-Issues#568]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Describe the bug

Minecraft opens to the menu to choose whether to play single player etc, but once I choose my game, it tries to load then crashes. A couple times, it has let me into the game, but then still normally crashes within a minute.

### Steps to reproduce

1. Not completely sure. I click on single player then choose the game and it crashes.

### Expected behaviour

game crashes after trying to start a game.

**Comment by MichaelHillcox** [comment]
Looks like you've tried to use a building gadget on a network cable from refined storage... am I right?

**Comment by Leafytreetops** [comment]
Yes I was.

**Comment by Raidobw2** [comment]
Restore a backup from the `backups` folder for now and build cables by hand. There's no other way around it for now you're experiencing a `Ticking block entity` error everytime. Apparently those cables were added in a blacklist in the patch you're playing on, but it looks like you were still able to place them with the gadget... I'll need to look into it in-dev when I get the chance.
Linked to #466

**Comment by Leafytreetops** [comment]
So to be sure, are the cables the problem, or is it laying the cables with the building gadget? Also do you know of a good step by step for restoring a backup? I'm not finding a good answer. Thank you so much

**Comment by Raidobw2** [comment]
Not really sure to be honest, by the looks of it the cables would be the issue, I'll have to investigate.
Thanks for your patience, I had a little delay here.
To restore a backup on the FTB App do the following:
Click the OceanBlock modpack tile:
![image](https://user-images.githubusercontent.com/17010632/150263787-d5e0d37d-2b20-4c5c-b923-c6c1d2b9046b.png)
Click settings:
![image](https://user-images.githubusercontent.com/17010632/150263830-0aa7a9bc-6705-4a15-825e-e858db073a8b.png)
Open the modpack folder:
![image](https://user-images.githubusercontent.com/17010632/150263860-77bfb165-f286-4f30-8d77-9e52b541294f.png)
Locate the backups folder and open it:
![image](https://user-images.githubusercontent.com/17010632/150263986-2abeedbe-1ddf-445e-a640-7d3745250ef3.png)
Inside you will see your backups. Sort them by date, and double click the latest one to enter it:
![image](https://user-images.githubusercontent.com/17010632/150264159-6e7f90a2-2512-407d-9d5a-69f59e265172.png)
Click on the world inside once to highlight it, then copy it with Ctrl + C for example:
![image](https://user-images.githubusercontent.com/17010632/150264307-a7518af3-625a-48f2-a3b2-f0c9b32c7590.png)
Go back in the modpack folder and open your Saves folder:
![image](https://user-images.githubusercontent.com/17010632/150264405-6775fa69-64e8-4911-8698-4ca1ff8dfabf.png)
Rename the original world that you have in there (right click then rename or highlight it and press F2):
![image](https://user-images.githubusercontent.com/17010632/150264595-d5a11059-b176-401b-9ee9-8712cef72cf9.png)
Paste in your backup that you copied from earlier, with Ctrl + V for example:
![image](https://user-images.githubusercontent.com/17010632/150264710-7718bbf9-db46-4666-b17c-66240a4c45c7.png)
Then load up your game and you'll see the original world that we renamed earlier. Take the other one, which should be your backup:
![image](https://user-images.githubusercontent.com/17010632/150265132-69f7fe85-d16b-4b2a-8eb3-d4723954ba6b.png)
Let me know if you have other questions.
Cheers.
