### ISSUE TITLE
Mac server file is not working for NeoTech 1.7.0

### ISSUE THREAD

**Issue by Alex5854** [FTBTeam/FTB-Modpack-Issues#5680]
### Modpack

FTB NeoTech

### Modpack version

1.7.0

### Has the pack been modified

No

### Describe the bug

When downloaded the file is like this:
{
  "code": "not_found",
  "message": "File with such name does not exist.",
  "status": 404
}

### Steps to reproduce

Download the serverfile for mac

### Expected behaviour

Working

**Comment by Gaz492** [comment]
This should be fixed now, let us know if you still run into issues

**Comment by Alex5854** [comment]
Hi, I tried again now, but it still doesn't work

**Comment by Alex5854** [comment]
The file downloaded from this link is practically empty: https://api.feed-the-beast.com/v1/modpacks/public/modpack/123/12404/server/mac
