### ISSUE TITLE
Problème d'enregistrement de modification de touche.

### ISSUE THREAD

**Issue by Recro-tech** [FTBTeam/FTB-Modpack-Issues#5681]
### Modpack

FTB Unstable 1.21

### Modpack version

1.0.1

### Has the pack been modified

No

### Describe the bug

Les modifications de touches dans les raccourcis clavier fonctionnent mais ne sont pas enregistrées après le redémarrage du jeu.

### Steps to reproduce

1. Allez dans le raccourcis clavier dans les paramètres 2. Changer la touche d'un mod 3. Utiliser cette touche dans le jeu 4. Fermer le jeu 5. Redémarrer le jeu 6.  Allez dans le raccourcis clavier dans les paramètres et constater la réinitialisation de base de la touche

### Expected behaviour

Sauvegarde des modifications de touches

**Comment by Gaz492** [comment]
Duplicate of #5631
