### ISSUE TITLE
Mystical Block the silicon that can be aquired is the wrong type and doesnt work with the quest

### ISSUE THREAD

**Issue by Galantous** [FTBTeam/FTB-Modpack-Issues#5683]
### Modpack

Other...

### Modpack version

1.16.5

### Has the pack been modified

No

### Describe the bug

it is not possible to get the silicon from refined storage, and that is the silicon that i need to go further in the quests, i have tried using the silicon from the ae2 mod as that is the only silicon that i can get but it simply doesnt work, so i cant even start the refined storage mod

### Steps to reproduce

get silicon on mystical block and it will be the wrong type.

### Expected behaviour

i expected to follow the crafting tree and get the material needed

**Comment by Gaz492** [comment]
Which modpack is this?

**Comment by Gaz492** [comment]
> > Which modpack is this?
> 
> it is mystical Block i got it on the ftb app

Ok, you will need to report the issue to them, as we didnt make that modpack.

You can find their issue tracker at https://legacy.curseforge.com/minecraft/modpacks/mystical-block/issues
