### ISSUE TITLE
Stoneblock 3 won't launch 

### ISSUE THREAD

**Issue by Krzysiex008** [FTBTeam/FTB-Modpack-Issues#5690]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Has the pack been modified

No

### Log Files

[FTB APP][INFO] Pre-Start Tasks
[FTB APP][INFO] Pre-Start Tasks Complete
[FTB APP][INFO] Validate Java Runtime
[FTB APP][INFO] Java Runtime Validated
[FTB APP][INFO] Validate assets
[FTB APP][INFO] Assets Validated
[FTB APP][INFO] Validate libraries
[FTB APP][INFO] Libraries Validated
[FTB APP][INFO] Validate client
[FTB APP][INFO] Client Validated
[FTB APP][INFO] Extract natives
[FTB APP][INFO] Natives Extracted
[FTB APP][INFO] Prepare process
[FTB APP][INFO] Process Prepared
Exception in thread "main" java.lang.reflect.InvocationTargetException
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.IllegalArgumentException
	at java.instrument/sun.instrument.InstrumentationImpl.appendToClassLoaderSearch0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.appendToBootstrapClassLoaderSearch(Unknown Source)
	at net.creeperhost.sa.AgentMain.premain(AgentMain.java:34)
	... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at e:\jenkins\tmp\workspace\build\src\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 422

### Describe the bug

When trying to luch Stoneblock 3, it stops at "Process Prepared" and a message pops up saying that the instance has crashed or has been externally closed
![image](https://github.com/user-attachments/assets/b90c5ba5-240c-41ef-b490-4177055c754d)

### Steps to reproduce

1. Download Stoneblock 3 via FTB app.
2. Click play

### Expected behaviour

Stoneblock 3 being lunched succesfully

### Screenshots

![image](https://github.com/user-attachments/assets/d2a54c92-425c-41cf-b60c-0d5ec838805e)

**Comment by Gaz492** [comment]
Would you be able to upload the debug.log and console.log from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by yembooo** [comment]
I have uninstalled and reinstalled both stoneblock 2 and 3 ..spent most of the day yesterday monkeying around ..and I cant get both to run either ...this is exactly wat happend for 3 to me also .. game crashes red box thingy ... sb2 actually load all the way to 7 out of 7 ... then freezes there wont go any farther

**Comment by Krzysiex008** [comment]
Hey so I think I found the files you were talking about, so here they are:

[console.log](https://github.com/user-attachments/files/16822549/console.log)
[latest.log](https://github.com/user-attachments/files/16822550/latest.log)
[debug.log](https://github.com/user-attachments/files/16822551/debug.log)

**Comment by Gaz492** [comment]
Thanks, it looks like you are running into an issue with one java agents the app uses, we have just put stoneblock 3 on curse, you could try downloading the pack on curseforge and see if it works there.
