### ISSUE TITLE
FTB NeoTech pack

### ISSUE THREAD

**Issue by StephJ2Fan** [FTBTeam/FTB-Modpack-Issues#5694]
### Modpack

Other...

### Modpack version

1.70

### Has the pack been modified

No

### Describe the bug

I can not get the map to show, either through the keybind or through the inventory screen button.

### Steps to reproduce

1. Go to inventory Screen
2. click map button
3. no screen open 

### Expected behaviour

Map to open

**Comment by Gaz492** [comment]
So to be able to open the map, you will need to complete the GPS Signal quest, once that quest is completed, the buttons on the inventory screen will work.

Ideally, those buttons would be hidden until the quest has been completed, we may look into doing this in future versions.
