### ISSUE TITLE
FTB ocean block

### ISSUE THREAD

**Issue by maciek211w** [FTBTeam/FTB-Modpack-Issues#5695]
### Modpack

FTB OceanBlock

### Modpack version

1.16.0

### Has the pack been modified

No

### Describe the bug

when i created a minecraft whiter i get crash and when i try to gen on this world i get crushed every time on non premium verssion

### Steps to reproduce

1 respawn whiter in lighthouse on non premium verssion 
2 and crash when he blew up

### Expected behaviour

some bug blocks can be destroyed i think

**Comment by Gaz492** [comment]
We dont offer support for players using cracked versions of minecraft.
