### ISSUE TITLE
Questbook Spelling Errors

### ISSUE THREAD

**Issue by MicahHaack** [FTBTeam/FTB-Modpack-Issues#5698]
### Modpack

FTB Interactions Remastered

### Modpack version

1.1.0

### Has the pack been modified

No

### Describe the bug

I've noticed some spelling/grammar errors in the quest book:
To avoid mentioning it too much, I think the word `also` is overly used throughout the entirety of the questbook.

- [x] - Quest: In Game Info! - (extra space before a period) `Humidity .` to `Humidity.`
- [x] - Quest: In Game Info! - `Usefull` to `Useful` (multiple cases)
- [x] - Quest: In Game Info! - `its` to `it's`
- [x] - Quest: In Game Info! - (might want to re-word the last sentence to `You may also want to set a (rest of sentence)`
- [x] - Quest: Having fun isn't hard when you got your library card - (quest title, `you` to `you've`
- [x] - Quest: Having fun isn't hard when you got your library card - `! simply` to `! Simply`
- [x] - Quest: Always double-tap - `Press shift twice while in Quest GUI ...` to `Press shift twice while in the Quest GUI ...`
- [x] - Quest: Primary Quest Chains - Missing period at the end of the description.
- [x] - Quest: Questline Completion - `They will often have instructions on which Quest Chains to focus next.` to `They will often have instructions on which Quest Chains to focus on next.`
- [x] - Quest: Knowledge Dispensary - `This will help you complete Quests ...` to `These will help you complete Quests ...`
- [x] - Quest: Hey, Listen! Hey, Listen!, Hey, Listen! - `It means that this sections contains Info that:` to `It means that these sections contain Info that:`
- [x] - Maybe look into re-writing "Time to be Transparent about something..." entirely? The quest honestly reads really awkwardly.
- [x] - Quest: This shouldn't even be necessary ... - `tho...` to `though.`
- [x] - Quest: The World is Your Table - `Note: You cannot Repair this tools yet` to `Note: You cannot Repair these tools yet`
- [x] - Consider changing the title of the quest "Call that a knife?" to "You call that a knife?"
- [x] - Quest: Call that a knife? - `Right now tho, ...` to `Right now though, ...`
- [x] - Quest: Sharping Interactions with Wood (In title) - `Sharping` to `Sharpening`
- [x] - Quest: Sharping Interactions with Wood - `Right now as you don't have the right tools ...` to `Right now, as you don't have the right tools ...`
- [x] - Quest: Sharping Interactions with Wood - Look into re-wording the final sentence, it also reads very awkwardly. Maybe just say: `Thankfully in this same quest book chapter you'll be able to properly automate Wooden Plank processing with a Water Powered Saw`
- [x] - Quest: Water you doing? - `If only I knew how physics worked I could melt ice into water.` to `If only I knew how physics worked, I could melt ice into water.`
- [x] - Quest: Stone Saw - `Still manual, but a quick way to make the most out of planks in wood.` to `Still manual, but a quick way to get more planks from logs.`
- [x] - Quest: In Dire need of String - `There's several ways to obtain String.` to `There are several ways to obtain String.`
- [x] - Quest: In Dire need of String - `Many Recipes accept Twine wich is a ...` to `Many Recipes accept Twine which is a ...`
- [x] - Quest: In Dire need of String - `And also, if you're unlucky with Cotton, you can also craft a Spider Tree Sapling, it produces String overtime on its leaves, not the best method but it works!` to `If you're unlucky with Cotton, you can craft a Spider Tree Sapling, it produces String slowly over time on its leaves.`
- [x] - Quest: Starving Artisan - `Also it handles fluids.` to `It also handles fluids.`
- [x] - Quest: I saw that - `If it doesn't work one way, try the other, (newline) Like a USB` to `If it doesn't work one orientation, try the other direction, like a USB.`
- [x] - Quest: Visual Guide to Automating the water saw - Change title to `Visual Guide to Automating the Water Saw`
- [x] - Quest: Architect's Sawbench - `To make your base prettier.` to `Use this to make your base prettier!`
- [x] - Quest: Healing Salve - `The pack has ...` to `This pack has ...`
- [x] - Quest: Let's make a Clay Kiln! - `usefull` to `useful`
- [x] - Quest: Let's make a Clay Kiln! - `Smelting with it should grant you ...` to `Smelting with it will grant you ...`
- [x] - Quest: Let's make a Clay Kiln! - `Smelting could take some time, perhaps it is a good idea to make more than one Kiln?` to `Smelting with a kiln takes some time, it's a good idea to make more than on Kiln.`
- [x] - Quest: Cotton - This quest has no description / rewards?
- [x] - Quest: Terra Spores - I would cut the entire second sentence.
- [x] - Quest: Formation Wand - `This wand will form blocks starting at a point you're looking at, very nice for quickly building large platforms at a distance or in directions the standard building wand doesn't allow for.` to `This wand forms blocks starting at the point you're looking at, which is very helpful for quickly building large platforms.`
- [x] - Quest: Dealing with Temperatures - `And that's why there's a Glove just for this!` to `Thankfully there's a Glove for this!`
- [x] - Quest: Dealing with Temperatures - `Also a good thing to notice is that if you store your fluids inside Steel+ Level Tanks there will be no side effects.` to `Storing fluids inside Steel+ will cause no side effects when held.`
- [x] - Quest: Rubber Tree Sapling - `This will allow you to grow rubber trees that will drop sticky resin.` to `This will allow you to grow trees that drop sticky resin.` (maybe rework that last sentence to something else?)
- [x] - Quest: Don't strain too hard for this - `early crafts and rituals` to `early crafts and rituals.`
- [x] - Quest: How to Automate a Pyre - `Usefull` to `Useful`
- [x] - Quest: How to Automate a Pyre - `on a block next to it in order to Automatically ...` to `on a block next to it to Automatically ...`
- [x] - Quest: How to Automate a Pyre - I believe there is a double space in the final sentence between provide and Materials
- [x] - Quest: How to Automate a Pyre - `simply place a Chest bellow it.` to `simply place a Chest below it.`
- [x] - Quest: The Early Game Building Aid - `it will solidify to lots of dirt.` to `it will solidify into lots of dirt.`
- [x] - Quest: Automate All the Things! - `One of the earliest automation methods is by using the conveyors` to `One of the earliest automation methods is conveyors.`
- [x] - Quest: Apple of Restoration - Maybe remove the second sentence? It seems redundant.
- [x] - Quest: I Heart You - `and convert them into a Villager. However to make ...` to `and convert it into a Villager. However, to make ...`
- [x] - Quest: I Heart You - `If you're impatient however, there's the faster way ...` to `If you're impatient however, there's a faster way ...`
- [x] - Quest: Yeet that Wheat - `you still have to craft them though.` to `you still have to craft them once, though.`
- [x] - Quest: fomdog melter - `and will be needed later.` to `and will be necessary later.` (just to avoid repetition).
- [x] - Quest: fomdog melter - `It seems that Porcelain Melter isn't ...` to `It seems that the Porcelain Melter isn't ...`
- [x] - Quest: Crying Obsidian - This quest has no description / rewards?
- [x] - Quest: If you scrolled here first, you're an overachiever - Missing period in first sentence, the last section could use a rewrite.

### Steps to reproduce

Check the quests I've listed.

### Expected behaviour

Words to be spelled correctly. (It's required to fill this out lol)

**Comment by ArtpokeBr** [comment]
Thanks for the Report, I had to rework a bunch of Quests and well... I'm a Non-Native English Speaker so Typos are bound to happen :)

Edited your issue, added some checkmarks to it and I'am making sure that everything is fixed.
