### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by KKamilS** [FTBTeam/FTB-Modpack-Issues#571]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Log Files

[hs_err_pid19680.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7884888/hs_err_pid19680.log)
[2022-01-17-1.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7884894/2022-01-17-1.log)

### Describe the bug

random crash during game play, once after 5 seconds, once after an hour.

### Steps to reproduce

Just getting into the game, once it will kick out after 5 seconds, once after an hour

### Expected behaviour

finding out what is causing the crash and how to fix it

**Comment by quietust** [comment]
This looks to be a variant of #40, but instead of crashing when trying to render the Modular Chestpiece, it's crashing when trying to render the Chaos Shard.

**Comment by KKamilS** [comment]
Is there anything I can do to fix this?

**Comment by quietust** [comment]
Read the discussion on bug #40 - [this](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40#issuecomment-966039154) comment includes instructions on how to reconfigure Draconic Evolution in order to avoid the crash.

**Comment by KKamilS** [comment]
looks like it helped, thanks for help

**Comment by Raidobw2** [comment]
Thanks quietust
