### ISSUE TITLE
Tinkers' Construct hammers are voided when broken by Worktable crafting

### ISSUE THREAD

**Issue by Benchifer** [FTBTeam/FTB-Modpack-Issues#5711]
### Modpack

FTB Interactions Remastered

### Modpack version

1.0.1

### Launcher

Other...

### Has the pack been modified

Yes

### Describe the bug

Tinkers' Construct hammers can be used in the tool slot for Basic Worktable recipes. However, when the hammer is broken by the recipe, instead of converting to its "Broken" state, it is voided the way a non-Tinkers' tool would be. This is unexpected, since Tinkers' tools usually cannot be voided like this, and they may represent a substantial investment from the player.

### Steps to reproduce

1. From JEI, spawn a Basic Worktable, a Stone Hammer from Tinkers' Construct, and six Iron Plates
2. Craft two Buckets
3. Observe that the second craft voids the hammer

### Expected behaviour

When the hammer has remaining durability less than or equal to what is required for the recipe, it is converted to its "Broken" state when the recipe is executed.

### Additional information

Launching via Prism Launcher. My only modification to the pack is adding Optifine.

**Comment by ArtpokeBr** [comment]
Yeah, not sure if the Dev from Artisan's Worktables will fix this (Please consider opening an Issue on his Git Repo).

But just to avoid any future issues, removing Tinker's Hammers from the artisanHammers OreDict until this is fixed.
