### ISSUE TITLE
Server crash with report 

### ISSUE THREAD

**Issue by Delfayne** [FTBTeam/FTB-Modpack-Issues#5713]
### Modpack

FTB Interactions Remastered

### Modpack version

1.0.1

### Launcher

Server

### Has the pack been modified

No

### Log Files

https://pastebin.com/9hvNr8wP

### Describe the bug

Unsure precisely when this crash occurs, I don't have direct access to this server. I'm afraid I can't help much. The classname is odd though, looks generated.

### Steps to reproduce

Uncertain

### Expected behaviour

Not to crash

**Comment by Gaz492** [comment]
Which modpack is this? It looks like you selected the wrong one while creating the issue as the crash log shows 1.12.2 as the minecraft version.

**Comment by Delfayne** [comment]
Aye sorry, this is FTB Interactions Remastered

**Comment by Gaz492** [comment]
Thanks, Does this happen while connecting to the server or after playing for a while?

The only thing of note in the crash report is to do with thaumcraft doing something with its config

**Comment by for-lack-of-a-better-name-j** [comment]
I have a similar issue in #5714 and I am the server owner and can get more information as needed.

**Comment by Delfayne** [comment]
Uncertain. I've heard that it's doing this as the server is shutting down, but I don't have enough information. I'm asking the server owner
