### ISSUE TITLE
Minecraft stuck during launch

### ISSUE THREAD

**Issue by aarontheo** [FTBTeam/FTB-Modpack-Issues#5716]
### Modpack

FTB Unstable 1.21

### Modpack version

1.1.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[console.log](https://github.com/user-attachments/files/16871662/console.log)

### Describe the bug

When launching the pack, things run without errors, but loading is stuck indefinitely right after these log messages:
[07:52:18] [modloading-worker-0/INFO] [th.ja.ma.MaterialHandler/]: Added 100 materials
[07:52:19] [FTB Backups Config Watcher 0/INFO] [ne.cr.ft.FTBBackups/]: Config at /Users/aarontheobald/Library/Application Support/.ftba/instances/ftb unstable 121/config/ftbbackups2.json has changed, reloaded!

### Steps to reproduce

Launch FTB Unstable 1.1.0

### Expected behaviour

The game should finish launching or crash without getting stuck.

### Screenshots

<img width="1583" alt="Screenshot 2024-09-04 at 8 02 54 AM" src="https://github.com/user-attachments/assets/d8ee03f4-b755-4c13-9a72-5f941db738e4">

### Additional information

The mojang/neoforge loading screen stops moving completely when it reaches this point, not even the heap bar moves or updates.

**Comment by Gaz492** [comment]
If you click on the modpack in the app, then click on the mods tab, search for midnightlib then disable it.
This should allow your pack to start.

This is a known issue with the mod on macOS right now.

**Comment by stevenliuxd** [comment]
@aarontheo I tested this on the newest 1.2.0 release on my mac and this is no longer happening; I also ran into this before on the previous version.
