### ISSUE TITLE
FTB Interactions' Curseforge release has a 1.20.1 modloader, in a 1.12.2 pack.

### ISSUE THREAD

**Issue by moosetwin0** [FTBTeam/FTB-Modpack-Issues#5719]
### Modpack

FTB Interactions

### Modpack version

2.12.1

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

The modpack is listed on curseforge as being for 1.12.2, but has a 1.20.1 modloader listed in the manifest.json file, which makes it impossible to run on both the Curseforge and Prism launchers.

### Steps to reproduce

1. Attempt to download the latest version of FTB Interactions 

### Expected behaviour

It installs and runs normally

### Screenshots

![image](https://github.com/user-attachments/assets/473fffdc-d397-40fc-8bdf-353c2673d39c)
![image](https://github.com/user-attachments/assets/273e4006-e03d-48e9-ab7c-a26760d296ed)
![keHxT2c](https://github.com/user-attachments/assets/1d19a8ab-5da4-4482-a9d3-56259c9830f9)
![stD4l5m](https://github.com/user-attachments/assets/c0a49dfa-7af4-49a1-b2f3-4ead5686b4ba)

**Comment by Gaz492** [comment]
Thanks, we will get this resolved asap
!skip

**Comment by Gaz492** [comment]
This should be fixed now, let us know if you still have issues with getting it installed do let us know!
