### ISSUE TITLE
Stone Block 3 turns PC off

### ISSUE THREAD

**Issue by Gesher98** [FTBTeam/FTB-Modpack-Issues#5722]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

I dont have a bug report as the pack turns my pc fully off as if you hold the turn on/off button for a few seconds when it begins to boot after the Minecraft launcher. Happens on both FTB and Curseforge

### Steps to reproduce

First ownload Stoneblock 3 via FTB App or CurseForge
Start Stoneblock 3
Click play in Minecraft launcher

### Expected behaviour

It shuts my pc down

### Additional information

AMD Ryzen 9 7900X 12-Core Processor 4.70 GHz
32GB RAM
RTX 3080

**Comment by Gesher98** [comment]
Forgot to add the Logs

[console.log](https://github.com/user-attachments/files/16896736/console.log)
[debug.log](https://github.com/user-attachments/files/16896738/debug.log)
[latest.log](https://github.com/user-attachments/files/16896742/latest.log)

**Comment by Gaz492** [comment]
Does this happen if you play vanilla or other modpacks? As the logs end as soon as the app tries to start minecraft, It sounds like your pc is running into a hardware issue.
I would recommend having a look through event viewer in windows to see if it shows why your pc is turning itself off.

**Comment by Gesher98** [comment]
Other mod packs work fine on both launchers. Today on FTB i downgraded to 1.8.1 and 1.9 then 1.10 to test the versions and apparently the issue fixed itself...
Both launchers seem to work now

**Comment by Gaz492** [comment]
> Other mod packs work fine on both launchers. Today on FTB i downgraded to 1.8.1 and 1.9 then 1.10 to test the versions and apparently the issue fixed itself... Both launchers seem to work now

Great to hear it's working correctly for you now, if you run into any further issues do let us know!
