### ISSUE TITLE
FTB Stoneblock 3 Crash during launch

### ISSUE THREAD

**Issue by budder-561** [FTBTeam/FTB-Modpack-Issues#5730]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

https://pste.ch/raw/ifomapexir

### Describe the bug

During launch, CPU usage jumps to 100%, and either the game will crash out, giving the crash report linked, or the PC blue screens with CLOCK_WATCHDOG_TIMEOUT. I'm running a 13700k, and no other mod packs give me problems, even other FTB packs.

### Steps to reproduce

1. Install FTB Stoneblock 3 on CurseForge
2. Launch mod pack

### Expected behaviour

I expect the mod pack to not use all of my CPU and to launch properly

**Comment by Gaz492** [comment]
So the log you posted may hint towards a software or driver issue, I would suggest making sure that any GPU drivers are up-to-date, the blue screen error you were getting is a bit more complicated, it suggests the CPU ran into an issue, now again this could be software/driver related or in some cases a hardware issue.
