### ISSUE TITLE
Industrial Foregoing Conveyor Splitter / Extractor / Inserter invisible

### ISSUE THREAD

**Issue by INCRD** [FTBTeam/FTB-Modpack-Issues#5731]
### Modpack

FTB Interactions Remastered

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

All "attachments" to the Industrial Foregoing Conveyors are invisible

### Steps to reproduce

1. Download Modpack via FTB App and start it
2. Create new world (Interactions Settings, don't change anything)
3. Either creative or normal
4. Build Conveyor and place it
5. Build Conveyor splitter / extractor / inserter and place it accordingly

### Expected behaviour

I can see the attachment

### Screenshots

With Sphax
![image](https://github.com/user-attachments/assets/aab3214f-039d-4d4b-9356-9d086ab95313)

Default
![image](https://github.com/user-attachments/assets/cca50de5-ac6b-45ab-a477-7d99ed4bc2be)

FTB Interactions Graphical Enhancement
![image](https://github.com/user-attachments/assets/60b43acb-06b6-4d8c-abc8-0ec3f61779bc)

### Additional information

I've tested different betterfps and graphic settings options. I am using Sphax, but I also attached a screenshot without sphax. I installed a fresh instance of Interactions Remastered. 
I've seen industrial foregoing 1.12.13 on a different modpack working fine. So I assume it is not an issue with the mod itself.

**Comment by tyreforhyred** [comment]
i recalled this was an issue in other packs with things like the Gregtech Lamps appearing invisible thanks to VintageFix and lo and behold it was the problem here.

anyway if you open up vintagefix.properties in the config folder and go down to line 15 you'll find
mixin.dynamic_resources=true
change it to 
mixin.dynamic_resources=false.
enjoy seeing things again.

**Comment by INCRD** [comment]
Wow thank you for your quick help. I just tested it out and this fix works great!
