### ISSUE TITLE
Extended Industrialization Brewers can't process modded potion recipes

### ISSUE THREAD

**Issue by RolaRoul** [FTBTeam/FTB-Modpack-Issues#5735]
### Modpack

FTB NeoTech

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

Yes

### Describe the bug

The Brewery machines added by Extended Industrialization can only process vanilla Minecraft potion recipes, and not recipes added by mods (ex. Potion of Slow Falling + Fermented Spider Eye = Potion of Levitation)

### Steps to reproduce

1. Place and power an Electric Brewer.
2. Insert a normal Potion of Slow Falling in the squares on the left.
3. Insert a Fermented Spider Eye in the ingredient slots on the top.

### Expected behaviour

Brewers should be able to process potion recipes added by mods.

**Comment by ArtpokeBr** [comment]
Unfortunatly the dev won't backport this fix :( so I'll be closing this issue.
