### ISSUE TITLE
game crash when loading world

### ISSUE THREAD

**Issue by W1esell** [FTBTeam/FTB-Modpack-Issues#5744]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[debug.log](https://github.com/user-attachments/files/16931204/debug.log)

### Describe the bug

When open up Minecraft Stoneblock 3 and I try to load my World (I have tried multiple) my Game freezes and is not responding.

### Steps to reproduce

1. start up FTB App 
2. start Stoneblock 3
3. go into singleplayer and open existing World (works when I start a completely new World but only until I close and restart the game)
4. Game is not responding and crashes

### Expected behaviour

being able to boot up my save World

### Screenshots

![image](https://github.com/user-attachments/assets/aace2329-11b6-457c-aeea-54f4776826eb)

**Comment by Gaz492** [comment]
If you create a new world then as soon as its loaded exit it, then try and open the world again does the issue happen?
The log you uploaded doen't shed much information about what may be causing the issues.
