### ISSUE TITLE
Missing/broken recipes: Compacting Drawers, Dough/SaltWater, etc...

### ISSUE THREAD

**Issue by Delfayne** [FTBTeam/FTB-Modpack-Issues#5745]
### Modpack

FTB Interactions Remastered

### Modpack version

1.2.0

### Launcher

Server

### Has the pack been modified

No

### Describe the bug

* Compacting drawers cannot be crafted. They require a framed drawer recipe component which does not exist. This also applies to drawer controllers. Pressing R on the framed drawer links to the craftable recipes, but this does not work
* The recipe for dough and salt water in a mixer collide. Dough requires flour salt and water. However the machine prefers to combine salt and water ignoring the flour. This can be worked around for now by providing <1000 water so that the salt water recipe does not trigger. One recipe here probably requires a circuit
* Thermal Sequential Fabricators cannot be crafted. I don't think these are OP in anyway so consider providing a recipe. Either that or remove them from JEI entirely. Being present with no recipe is not helpful
* Signs could potentially do with a slightly earlier recipe, or making it allowable to be crafted by Forge Microblocks saws in addition to GT saws. Labeling your crap early on shouldn't be gated past plates imho

Finally, and this might be a local issue but haven't traced it.
We have not been able to successfully craft Faint Amaranth via infusion on our server. It worked immediately when I tried it in our test world. I see nothing interfering on the server. I need to set up a simple test on a local server to confirm this. I'll feed back more on this issue when I know it

### Steps to reproduce

Described inline above

### Expected behaviour

Described inline above

**Comment by Delfayne** [comment]
I would also note here in potential missing recipes:
Cutting Machine recipes in GTCEu have water, distilled water, and lubricant variants. A few custom cutting machine recipes were missed from the addition of distilled water. I note that Ender Pearl + Distilled Water does not exist in the cutting machine and probable should, as simply upgrading the fluid type you use for the recipe should not prohibit this craft

**Comment by Delfayne** [comment]
@ArtpokeBr the dough recipe STILL conflicts with salt water, because salt water has no circuit

**Comment by ArtpokeBr** [comment]
-_- yeah I added the circuit to the dough recipe itself.

No problem, gonna fix this next update.
