### ISSUE TITLE
Universal Pipe from Pipez mod crashes game

### ISSUE THREAD

**Issue by isaacbugeja** [FTBTeam/FTB-Modpack-Issues#5746]
### Modpack

FTB Unstable 1.21

### Modpack version

1.20

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Universal Pipe from Pipez mod crashes game when placing on Modern Industrialization Fluid Input Hatch, works fine with Pipez Fluid Pipe.

### Steps to reproduce

Attach Universal Pipe from Pipez mod to activated Coke Oven Fluid Input Hatch

### Expected behaviour

It should connect normally

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
