### ISSUE TITLE
[Bug]: Warm Void trinket usage in Compact Machine dimension

### ISSUE THREAD

**Issue by EJROBERTS011** [FTBTeam/FTB-Modpack-Issues#575]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Describe the bug

When using the Warm Void trinket from Lost Trinkets (which has the description of "Falling into the void will teleport you to your spawn point") in the compact machine dimension from Compact Machines 4, the play will get stuck on a "Loading Terrain..." screen.

### Steps to reproduce

1. Equip "Warm Void" trinket from Lost Trinkets
2. Break outside of the Compact Machine with teleportation of some sort
3. Jump into the void

### Expected behaviour

The player should be teleported to their spawn point in the overworld.

**Comment by TheonlyTazz** [comment]
Not an Issue, Compact Machines shouldnt be broken out of. This would need the Lost Trinkets mod to update/change this
