### ISSUE TITLE
[Bug]: Minecolony bypasses claims

### ISSUE THREAD

**Issue by BasianBalarg** [FTBTeam/FTB-Modpack-Issues#576]
### Modpack

DW20

### Modpack version

1.16

### Describe the bug

the npcs from minecolony seem to be able to bypass claims from ftb.
this is a big problem as many servers would ban the mod due to high risk of people using minecolony for griefing and bypassing claims.

### Steps to reproduce

1. go into a server with atleast 1 other player.
2. let the other player make a claim.
3. start a minecolony and set the builder hut block so that the builder hut claim would overlap the other players claim.
4. let the builder build their hut.

### Expected behaviour

the builder npc will destroy stuff in the claim of a different player

**Comment by BasianBalarg** [comment]
when a developer of the minecolony mod or the dw20 1.16 modpack has read this, could they pls let me know if this is something that will be taken care of? im asking this because im keeping staff of a few servers using the dw20 1.16 modpack up to date about the issue. they would like to enable minecolonies on their servers but cant atm due to the too high risk of griefing. the minecolonies mod is something that attracts allot of attention to servers as it is very desired.

**Comment by Raidobw2** [comment]
I'm not exactly sure how this can be taken care of so I've reported it to the author of FTB Chunks. I'll probably ask Minecolonies as well in a few minutes.
There's a line in the Minecolonies server config (`world/serverconfig/minecolonies-server.toml`) that looks like this:
```
#Should colony protection be enabled? [Default: true]
	enablecolonyprotection = true
```
Maybe that overrides the FTB Chunks protection and you could try turning it off by setting it to false.
I'll have to investigate more when I get the chance, currently that's the only track I have.

**Comment by BasianBalarg** [comment]
bump

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
