### ISSUE TITLE
Missing conversion for Mek Salt to GT Salt

### ISSUE THREAD

**Issue by Delfayne** [FTBTeam/FTB-Modpack-Issues#5760]
### Modpack

FTB Interactions Remastered

### Modpack version

1.2.0

### Launcher

Server

### Has the pack been modified

No

### Describe the bug

Please provide a direct conversion for Mekanism salt to GT salt.

Mek salt can be acquired by mining rivers/ocean and is super easy to acquire in bulk early game. Without silk touch it drops as dust, but not directly convert to GT salt

### Steps to reproduce

As above

### Expected behaviour

Like Pam's Salt, Mek salt should convert to GT salt

### Additional information

There is a workaround for converting via making it a block and smashing it up again, but it's long-winded

**Comment by ArtpokeBr** [comment]
Mekanism Salt Blocks should break into GT's Salt now.
