### ISSUE TITLE
Bamboo has an 'oddly broken display' when inserted into Sophisticated Storage barrels 

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#5762]
### Modpack

FTB NeoTech

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

a picture is worth a thousand words-- see screenshot :-) 

basically bamboo is FRIGGIN YUGE somehow, when inserted into the barrel

### Steps to reproduce

1. make a 1x1 sophisticated storage barrel
2. insert a stack of bamboo
3. ...
4. PAIGE, NO!

### Expected behaviour

normal display of bamboo with item count visible, that doesn't overlap the bevel of the storage display

### Screenshots

![2024-09-12_23 21 35](https://github.com/user-attachments/assets/399a3dee-6692-4834-9a92-c09b1f8df91d)

**Comment by ArtpokeBr** [comment]
This is unfortunatly a Side effect of the 3D Bamboo Texture Pack that we use, its part of the Resource Pack called Vanilla Tweaks, so if you feel like it really bothers ya, feel free to open it and disable this specific module or either the entire resource pack.

If you find annoying to find the specific module for the 3D Bamboo, [here's](https://vanillatweaks.net/picker/resource-packs/) the Website for you to build your own Vanilla Tweaks Resource Pack without it.
