### ISSUE TITLE
Crashing issue with Pipez mod 

### ISSUE THREAD

**Issue by Valdoff** [FTBTeam/FTB-Modpack-Issues#5763]
### Modpack

FTB Unstable 1.21

### Modpack version

1.1.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

When using the universal cable (from the _Pipez_ mod), on an Oak Advanced Beehive from _Productive Bees_, it cause the game to crash.

### Steps to reproduce

Use universal cable on advanced beehive

### Expected behaviour

Crash

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
