### ISSUE TITLE
Gamecrash by typing in "Chicken"

### ISSUE THREAD

**Issue by pheliepe** [FTBTeam/FTB-Modpack-Issues#5765]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Searching for "Chicken" in my Just enough Items searchbar leads to a gamecrash. 

### Steps to reproduce

1. open Just enough Items menu
2. search for "Chicken" 
3. Game crashes (Mine and my frieds' ones too)

### Expected behaviour

Game freezes or crashes completely

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
