### ISSUE TITLE
FTB Interactions Remastered Crash during loading

### ISSUE THREAD

**Issue by skyblockmodpackuser** [FTBTeam/FTB-Modpack-Issues#5766]
### Modpack

FTB Interactions Remastered

### Modpack version

1.0.1

### Launcher

Other...

### Has the pack been modified

No

### Log Files

https://mclo.gs/WHp8Gsd

### Describe the bug

On loading the modpack, a screen appears saying that it cannot be loaded due to some error. It lists Simple RPC, Forge Mod Loader, and Forge as the suspected causes

### Steps to reproduce

1. Open Prism Launcher and select "Add Instance"
2. Select "Improt from FTB App"
3. Import the modpack
4. (Not sure if this happens on other devices) Change Java version from 17 to 8 in settings
5. Press Launch
6. During Loading, error occurs

### Expected behaviour

Modpack loading and opening normally

**Comment by Gaz492** [comment]
Is this still an issue for you on the latest version of the modpack?

**Comment by skyblockmodpackuser** [comment]
I removed the simple RPC mod and it seemed to have resolved, even though after saving a world to leave the game just freezes (although then force quitting it doesn't seem to cause corruption).I have not switched to 1.2.0 due to it being listed as a beta version on the site. If it is fully functional it would be appreciated if there was a guide to switch my world to it.

**Comment by skyblockmodpackuser** [comment]
It seems to work if I remove the SimpleRPC mod
