### ISSUE TITLE
Botania's Dice of Fate can give duplicate relics

### ISSUE THREAD

**Issue by mycroftjr** [FTBTeam/FTB-Modpack-Issues#5767]
### Modpack

FTB Sky Odyssey

### Modpack version

1.5.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Botania uses the advancements for each Dice of Fate relic to add their entries to the Lexica and remove them from the Dice pool, but since advancements were apparently completely removed for this pack (https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/376), none of that works.

Why were they even removed in the first place, and why is the BetterAdvancements mod in the pack if they're all removed???

Edit: found the how: Triumph's configs:
```
removeVanillaAdvancements(true)
removeModAdvancements(true)
```

### Steps to reproduce

1. Open a Dice of Fate
2. Your Lexica Botania won't tell you anything about the relic you got, like how to use it...
3. Instead of 6 Dice total you'll ever have to open to get all the relics, it's now completely random

### Expected behaviour

Advancements?

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.

**Comment by mycroftjr** [comment]
I mostly just wanted answers...
