### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by mcx-spear** [FTBTeam/FTB-Modpack-Issues#5768]
### Modpack

FTB Skies Expert

### Modpack version

1.19.2

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[2024-09-14-12.log.gz](https://github.com/user-attachments/files/17004270/2024-09-14-12.log.gz)
[console.log](https://github.com/user-attachments/files/17004272/console.log)
[debug.log](https://github.com/user-attachments/files/17004273/debug.log)
[debug-1.log.gz](https://github.com/user-attachments/files/17004274/debug-1.log.gz)
[debug-2.log.gz](https://github.com/user-attachments/files/17004275/debug-2.log.gz)
[debug-3.log.gz](https://github.com/user-attachments/files/17004277/debug-3.log.gz)
[debug-4.log.gz](https://github.com/user-attachments/files/17004278/debug-4.log.gz)
[debug-5.log.gz](https://github.com/user-attachments/files/17004279/debug-5.log.gz)
[latest.log](https://github.com/user-attachments/files/17004280/latest.log)
[custommachinery.log](https://github.com/user-attachments/files/17004282/custommachinery.log)

### Describe the bug

i start my world and it just crashes

### Steps to reproduce

1. normal steps to play 
2. singleplayer and choose a world

### Expected behaviour

i expected it to start playing

### Additional information

Device name	DESKTOP-6FV6BP2
Processor	Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz   2.50 GHz
Installed RAM	12.0 GB
Device ID	BBE94563-26DB-4CC8-A050-3AFF9BD159BD
Product ID	00326-10000-00000-AA502
System type	64-bit operating system, x64-based processor

141gb storage used out of 832gb

my memory is usually always taken up by ftb so idk if its that

**Comment by Gaz492** [comment]
If you right click the modpack in the FTB App and click on settings, try clicking the repair button and then see if the modpack starts up for you, it looks like a config file may have become corrupted

**Comment by mcx-spear** [comment]
yea i saw a repair button and it worked. i also think it was cuz the amount
of mobs i left alive in my mob grinder. thank you for your time.
