### ISSUE TITLE
[Bug]: Integrated dynamics facades cannot be crafted

### ISSUE THREAD

**Issue by Blockguy24** [FTBTeam/FTB-Modpack-Issues#577]
### Modpack

FTB Endeavour

### Modpack version

1.9.0

### Describe the bug

Facades from integrated dynamics need to be crafted with a block in a crafting table in order to be used, but the crafting recipe doesn't appear to work (crafting output is blank)

### Steps to reproduce

1. Get integrated dynamics facade
2. Get a block (I tested with stone and stone bricks)
3. Put both of them in a crafting table

### Expected behaviour

The textured facade is able to be crafted

### Screenshots

![image](https://user-images.githubusercontent.com/21016331/150625510-0d8cb477-9c0f-4e89-8d83-0607c26762ab.png)

**Comment by manmaed** [comment]
This issue is stale
