### ISSUE TITLE
Multiblock'd machines GUIs and HEI integration broken if GUI and HUD scale mismatched with ScalingGUIs

### ISSUE THREAD

**Issue by Meta-Didact** [FTBTeam/FTB-Modpack-Issues#5771]
### Modpack

FTB Interactions Remastered

### Modpack version

1.2.0

### Launcher

Other...

### Has the pack been modified

No

### Describe the bug

If using the large GUI scale and normal HUD scale in Scaling GUIs, Multiblock'd machines GUIs don't render correctly, either having cut off or missing text and missing item icons in HEI recipe view.
![2024-09-14_22 58 20](https://github.com/user-attachments/assets/5f67291d-a533-4032-a555-ce256ed2d6c7)
Incorrect
![2024-09-15_10 29 51](https://github.com/user-attachments/assets/e9291926-eca1-4eec-888b-ffc7a2e8485b)
Normal

### Steps to reproduce

1. Set GUI scale to "Large" with HUD scale "Normal" and open an ftbi/Multiblock'd machine GUI or their HEI recipe list.
2. See missing icons, cut off or missing text.
3. GUI renders correctly when GUI and HUD scale are the same.

### Expected behaviour

Text and icons should be visible in GUI at all scales.

### Screenshots

![2024-09-14_22 58 37](https://github.com/user-attachments/assets/3acbc3ec-e3a7-45bf-8ea6-4e9b188a0c16)
Missing item icons in recipes
![2024-09-14_22 59 08](https://github.com/user-attachments/assets/e4c0d799-0c6c-4ebe-b595-9765bcbfbc5f)
Normal UI and HUD scale
![2024-09-14_23 04 17](https://github.com/user-attachments/assets/799c45ed-25b0-42a2-a89d-01c784557c0e)
Not exclusive to Infernal Kiln
![2024-09-15_10 30 13](https://github.com/user-attachments/assets/6931f705-b0d7-4f24-af3d-b6d2fc3d374a)
Problematic GUI scales setting

### Additional information

Blacklisting `com.cleanroommc.multiblocked.api.gui.modular.ModularUIGuiContainer` in ScalingGUIs options "fixes" this for machine GUIs by ignoring the GUI Scale option and apparently rendering at HUD scale.

Does not fix the missing item icons in HEI recipe view.

**Comment by ArtpokeBr** [comment]
Reported  this in the ScalingGUI's Git repo, for now I'll be marking as fixed and removing the mod until this is properly fixed.
