### ISSUE TITLE
Infernal Kiln does not support all generic smelting recipes

### ISSUE THREAD

**Issue by Meta-Didact** [FTBTeam/FTB-Modpack-Issues#5772]
### Modpack

FTB Interactions Remastered

### Modpack version

1.2.0

### Launcher

Other...

### Has the pack been modified

No

### Describe the bug

Infernal Kiln multiblock smelter does not have all generic smelting recipes.

Notable exceptions are all smelting recipes that produce native ore clusters.

Quest book presents Infernal Kiln as complete replacement of other smelting options but the lack of recipes makes this false.

### Steps to reproduce

1. Look for smelting recipe that produces native ore clusters
2. See that there is no equivalent recipe for the Infernal Kiln

### Expected behaviour

Infernal Kiln multiblock should be able to process all generic smelting recipes.

**Comment by ArtpokeBr** [comment]
Importing all Recipes from the Vanilla Furnace would definitely impact performance a bit and would also be a challenging task.

So please, make sure to report more important recipes not added to it :)

I'll be updating the quest text to reflect this scenario and also adding those clusters recipes that you've mentioned to it.

**Comment by ArtpokeBr** [comment]
Actually, took some time to investigate this properly and now MOST recipes should be doable with it =)

Most stuff should be imported automatically now, but some really edge cases may require a manual addition.

**Comment by KlumsyKyller** [comment]
Adding to this, JEI says gold dust can be smelted in the infernal kiln into gold ingots, but it doesn't actually do anything.
