### ISSUE TITLE
Statue Mod Recipe Conflict.

### ISSUE THREAD

**Issue by rushedman** [FTBTeam/FTB-Modpack-Issues#5779]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.0.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

None (That I know of)

### Describe the bug

Seems to be a recipe conflict with the statues mod. Trying to make Level 2 Mobkiller which requires three blocks of lapis and one enchanted book. Well no enchanted book works. It seems to want a blank enchanted book for the recipe which there is no way to get.

### Steps to reproduce

1. Get a Statue Cored Statue to Level 2 (20 mob kills at least)
2. Use the S.T.A.T.U.E. to combine it with a Diamond Sword
3. Use Again to try and combine it with 3 Lapis Blocks and any Enchanted book
4. Recipe not recognized
5. Look in JEI to make sure you have it correct.
6. Do it again
7. Fail Again

### Expected behaviour

That the Statue will upgrade to Mob Killer II

**Comment by Saereth** [comment]
reported this to bysco, he's gonna look into it when he gets home

**Comment by rushedman** [comment]
Any updates?

**Comment by Mrbysco** [comment]
I'll look into it

**Comment by Saereth** [comment]
@Mrbysco on the case :D
