### ISSUE TITLE
World started Crashing with Minecolony's Lumberjack tool

### ISSUE THREAD

**Issue by lanallama20** [FTBTeam/FTB-Modpack-Issues#5782]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[2024-09-16-1.log.gz](https://github.com/user-attachments/files/17021726/2024-09-16-1.log.gz)
[2024-09-16-3.log.gz](https://github.com/user-attachments/files/17021776/2024-09-16-3.log.gz)

[debug-1.log.gz](https://github.com/user-attachments/files/17021736/debug-1.log.gz)
[debug-4.log.gz](https://github.com/user-attachments/files/17021777/debug-4.log.gz)

### Describe the bug

I went to make an area for the lumberjack and it crashed me. I've been playing this since yesterday and it only crashed once before when I tried feeding the colonists.

I tried used NBTEditor to get the minecolony lumberjack out of my inventory and it doesn't seem like it worked. That is also why I attached 2 logs one is before I edited it the other is after

i just got done mining

### Steps to reproduce

1. open the menu to the Forester block that just got a new colonist to it.
2. click the set area for a forest tool
3. crash game immediately after that

### Expected behaviour

get the tool and assign an area so they can chop things down

### Screenshots

N/A

### Additional information

does this modpack not have ftb backups or the mod that backs up the world? I'm not seeing a backups folder to revert

**Comment by lanallama20** [comment]
sorry for the edits i didn't see typos and characters I accidentally put in

**Comment by Saereth** [comment]
this is a duplicate and has already been reported (https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5769), closing to reduce clutter but ty for the report.
