### ISSUE TITLE
Duplicate recipes elevator/yurting mods

### ISSUE THREAD

**Issue by shank3001** [FTBTeam/FTB-Modpack-Issues#5784]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.10

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

There is a conflict between the just added elevator mod and the yurting mod. They have the same recipe. 

### Steps to reproduce

try to craft an elevator and you get a baog of yurtling instead.

### Expected behaviour

Seprate recipes.

**Comment by archmon** [comment]
ya, found this as well.  
![bug](https://github.com/user-attachments/assets/8e5d30f6-0156-47c3-82a9-5cebdb9f1987)
