### ISSUE TITLE
Pocket Storage or Dank

### ISSUE THREAD

**Issue by halvalla01** [FTBTeam/FTB-Modpack-Issues#5787]
### Modpack

FTB Presents Direwolf20 1.21

### Is your suggestion related to a problem? Please describe.

You end up getting a lot of certain things when out mining (lookin' at you, cobble). Adding either dank storage (don't know if it's out for 1.21) or Pocket Storage would be a nice quality of life improvement. 
Note: I played with Pocket Storage somewhat in All the mods 10 (mc 1.21) and it was a little buggy (duping mostly). I have no idea if they fixed it

### Mod suggestion

Pocket: https://www.curseforge.com/minecraft/mc-mods/pocket-storage
Dank: https://www.curseforge.com/minecraft/mc-mods/dank-storage

**Comment by Saereth** [comment]
Pocket storage will be in next update
