### ISSUE TITLE
Chrash during lunch. Even after Reinstalling FTB App

### ISSUE THREAD

**Issue by momo54656565** [FTBTeam/FTB-Modpack-Issues#5789]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[latest.log](https://github.com/user-attachments/files/17040921/latest.log)
[debug.log](https://github.com/user-attachments/files/17040925/debug.log)
[console.log](https://github.com/user-attachments/files/17040927/console.log)
[debug-1.log.gz](https://github.com/user-attachments/files/17040929/debug-1.log.gz)
[2024-09-18-1.log.gz](https://github.com/user-attachments/files/17040930/2024-09-18-1.log.gz)

### Describe the bug

It's the second day I want to lunch Stoneblock3. The first day I had no problems at all. 
On the second day (I changed nothing, I guess) the programm won't lunch. 
I tried reinstalling but this doesn't help. 

Maybe there is a problem with java. While opening Java there is an error. 

### Steps to reproduce

1. Open FTB App
2. Lunch Stoneblock3
3. error 

### Expected behaviour

Step by Step explanation how to fix the problem

### Screenshots

![image](https://github.com/user-attachments/assets/1507e70a-284f-4be0-9360-6ef7d3157bf1)

**Comment by Gaz492** [comment]
It looks like a config file may have become corrupted, if you right-click the modpack and then click on settings, you should then see an orange repair button, if you click the repair button, it may fix the issue with the config file for you.

**Comment by Strat0v** [comment]
Had the same problem, installed newest Java and changes the instance setting from java version: recommended to JDK 23 and after that it worked
