### ISSUE TITLE
Can't break Ars Nouveau Cointainment Jars with Entities inside

### ISSUE THREAD

**Issue by lucasjoviniano** [FTBTeam/FTB-Modpack-Issues#5790]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

https://pastebin.com/RpX8FHG1

### Describe the bug

An error occurs with rendering when I'm breaking a Containment Jar with an entity inside 

### Steps to reproduce

1. Place a Containment Jar and a Ritual Brazier in the world
2. Place a Containment Ritual in the brazier and right click with an empty hand to activate it
3. Spawn a mob and wait for it to be captured
4. Try to break the Containment Jar

### Expected behaviour

Being able to break the jar

### Additional information

I've testes it with creeper, skeleton and witch (spawned naturally). Also, I've created another instance with just ars and jei and it works on it.

**Comment by shank3001** [comment]
Same issue here. Workaround for now is to use a cardboard box.

**Comment by Saereth** [comment]
waiting for a fix from ars 
https://github.com/baileyholl/Ars-Nouveau/issues/1423
