### ISSUE TITLE
Mod: Polymorph and Polymorphic Energistics

### ISSUE THREAD

**Issue by halvalla01** [FTBTeam/FTB-Modpack-Issues#5792]
### Modpack

FTB Presents Direwolf20 1.21

### Is your suggestion related to a problem? Please describe.

To fix conflicting recipes, like the Elevator vs Bag of Yurting
Polymorphic Energistics adds polymorph support to AE

### Mod suggestion

Polymorph: https://www.curseforge.com/minecraft/mc-mods/polymorph 
PolyEnergistics: https://www.curseforge.com/minecraft/mc-mods/polymorphic-energistics

**Comment by Saereth** [comment]
we would prefer any recipes conflicts be reported so we can just fix them directly
