### ISSUE TITLE
Enchantable Blocks - Yield Enchantment Allows Easy Duplicating

### ISSUE THREAD

**Issue by Plobby** [FTBTeam/FTB-Modpack-Issues#5793]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The "yield" enchantment at max level (with apotheosis) on a furnace allows for incredibly easy duplication of resources etc

### Steps to reproduce

1. Enchant a Blast Furnace with the maximum level of "yield" - level 8
2. Provide furnace with fuel and insert material dust - such as iron dust, gold dust, netherite dust - into the smelting slot
3. Wait for output to smelt, providing the player with 9 of the relevant material (iron, gold, netherite)
4. Insert the resources into a Mekanism crusher to 9x your materials each iteration

### Expected behaviour

Yield enchantment should be capped at a reasonable level to make this less lucrative or disabled entirely

**Comment by LWmods** [comment]
came here to report this. 100% needs to be level capped or removed its way too strong

**Comment by LogicEngineer** [comment]
1. Enchant furnace with high yield enchant.
2. Smelt diamond ore into 5+ diamonds.
3. Crush diamonds in mekanism crusher to get diamond dust
4. Combine diamond dust with cobble in combiner to make diamond ore. 
5. Repeat to gain diamond ore. (This same process probably works for other ores. Didn't extensively check. 

Yield enchant definitely needs a cap at I or II or just a straight up removal for the sake of balance.
