### ISSUE TITLE
Drawers from Functional Storage become unbreakable

### ISSUE THREAD

**Issue by antiphysika** [FTBTeam/FTB-Modpack-Issues#5795]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[latest.log](https://gist.github.com/antiphysika/7db3bfe56544ebb89f5fa11c3048b040)

### Describe the bug

Drawers from the Function Storage mod have (recently?) become unbreakable. Had been using them without issue since 1.0.0, including breaking them without error. Now they no longer break with hand, tools or in creative mode. `/setblock` does work, however.

The bug is present in at least 1.1.1 and 1.1.2.

### Steps to reproduce

In singleplayer:
1. Place down one or more `functionalstorage:oak_1` drawers
2. Try and break with hand or pickaxe

### Expected behaviour

Drawer blocks break/drop

### Additional information

Linked log is from instance where More Overlays, Xaero's World/Mini Map and FPS Reducer mods added. Tested without just in case and the bug is still present.

**Comment by Saereth** [comment]
cannot reproduce, are you trying to break them from the from front? If so that wont work as it overrides the click interaction

**Comment by antiphysika** [comment]
You're right, I was sure I was testing on the borders where that wouldn't be an issue, but checking again and can't reproduce either.

**Comment by Pablo-Barros** [comment]
It happened to me aldo, don't know how it happened. They were breakable from behind.
