### ISSUE TITLE
Powah Energizing Orb missing recipes

### ISSUE THREAD

**Issue by lpacphantom** [FTBTeam/FTB-Modpack-Issues#5796]
### Modpack

FTB Presents Direwolf20 1.21

### Is your suggestion related to a problem? Please describe.

The Energizing Orb from Powah doesn't have any JEI recipes for what it can craft. The correct recipes still work, but you have to know them on your own, which for the crystals I was fine, but now I needed a reminder for the ender core (I'm going to look it up, but this should still get added).

**Comment by Power46-GitHub** [comment]
According to https://github.com/Technici4n/Powah/issues/188 this should be fixed in version 6.1.2 of Powah
