### ISSUE TITLE
Plant Sower of Industrial Foregoing not working with nether wart

### ISSUE THREAD

**Issue by GabrielPereira10** [FTBTeam/FTB-Modpack-Issues#5799]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I am using a Plant Sower of Industrial Foregoing to grow nether wart but it does not work even with the addon. I have soul sand on top and does not plant automatically. 

### Steps to reproduce

1. Place the machine Plant Sower 
2. Power up the machine
3. Place nether wart inside of machine
4. Place a Soul sand on top
5. Even after some time does not plant any nether wart

### Expected behaviour

It should plant Nether Wart on top of a soul sand.

### Additional information

It should be something wrong because on the same mod pack (Industrial Foregoing) even if I plant manually the Plant Gatherer can harvest when fully mature.

**Comment by Saereth** [comment]
reported to buuz https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1477
