### ISSUE TITLE
[Bug]: Possible missing quest draconium seeds

### ISSUE THREAD

**Issue by SsilverLeopard** [FTBTeam/FTB-Modpack-Issues#580]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Describe the bug

In the Mystical Agriculture section of the quest book, there is a quest for every possible seed you could ever think of, except for draconium/awakened draconium. However, I can still craft and plant these seeds (at least for normal draconium, I haven't reached awakened draconium) and they give me the essence to make the ingots. If they were meant to be disabled, it hasn't worked

### Steps to reproduce

1. Open JEI
2. Seach for draconium seeds
3. Create draconium seeds
4. Plant Draconium seeds (I did it in a botany pot)
5. No quest gets completed, but the seeds grow

### Expected behaviour

I expected a quest to be completed in the book and to get a "random reward" like I would with any other seed making quest

### Screenshots

![draconium essence jei](https://user-images.githubusercontent.com/90362124/150658813-82a746fa-fb4b-462e-ab5f-05347f0ae324.png)
![draconium growing](https://user-images.githubusercontent.com/90362124/150658814-cb71815a-e1a6-4de9-b0b5-31432c7e112b.png)
![crafting draconium](https://user-images.githubusercontent.com/90362124/150658911-f0565013-ec55-4477-995c-54f6dfa601d0.png)
![draconium seeds jei](https://user-images.githubusercontent.com/90362124/150658815-69e9dd6d-298d-4eb1-b85b-c67655373672.png)
![draconium seeds recipe jei](https://user-images.githubusercontent.com/90362124/150658816-eeb149c7-5ead-4bd6-b3b0-fa73fb0043d1.png)
![no quest](https://user-images.githubusercontent.com/90362124/150658817-797db2df-01b0-47c5-8763-94cc4f9a5e10.png)

**Comment by quietust** [comment]
On a similar note, there is no quest for making Air Essence Seeds, but that's understandable because they originally had zero uses (prior to #365 being fixed).
