### ISSUE TITLE
[Crash] Broken item from End quests reward

### ISSUE THREAD

**Issue by Delfayne** [FTBTeam/FTB-Modpack-Issues#5801]
### Modpack

FTB Interactions Remastered

### Modpack version

1.3.0

### Launcher

Server

### Has the pack been modified

Yes

### Describe the bug

The quest reward for Chaos Veins in the End chapter rewards 32 copies of a broken item with old GTCE codes. Unfortunately, GTCEu tries to render it, can't, and crashes the client.
The problematic quest is in this file:
`normal/chapters/8b3e4520/90552e70.snbt`
The reward in 2.x was 32x platinum wire. Double-check if that's still appropriate for this progression. It seems ab it weak now, perhaps.

### Steps to reproduce

Accept quest reward from Chaos Veins quest.
Mouse over the invisible "32x item"
Crash

### Expected behaviour

Correct the quest item so it does not crash

**Comment by Gaz492** [comment]
Would you be able to upload the crash log from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by Delfayne** [comment]
A crash log wouldn't provide any additional benefit here.

The item in the quest is a GregTech meta item, but it uses old IDs for GTCE which reference an invalid item in GTCEu (I know as I wrote this part of the pack).
