### ISSUE TITLE
Crash during Lunch; Repairing files didn't workd

### ISSUE THREAD

**Issue by momo54656565** [FTBTeam/FTB-Modpack-Issues#5802]
### Modpack

FTB StoneBlock 3

### Modpack version

1.10.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

Crash report: 
[crash-2024-09-21_09.33.06-client.txt](https://github.com/user-attachments/files/17083308/crash-2024-09-21_09.33.06-client.txt)

[debug-1.log.gz](https://github.com/user-attachments/files/17083306/debug-1.log.gz)
[2024-09-21-1.log.gz](https://github.com/user-attachments/files/17083307/2024-09-21-1.log.gz)

### Describe the bug

Crash during Lunch

### Steps to reproduce

Just lunching with the FTB App

### Expected behaviour

Step by Step explanation how to fix the problem

### Additional information

I tried to repair the instance but this didn't help. 

The problem came up after a game crash.

**Comment by momo54656565** [comment]
I saw an Error on "Minetogether", so I disabled the mod. Didn't help...

**Comment by Bissy80** [comment]
I am also having this Issue, but to be honest the mod has never worked for me.

**Comment by momo54656565** [comment]
I reinstalled the pack and the luncher. This fixed the problem. 
**Make sure to get a backup of your word/s :)**

**Comment by Bissy80** [comment]
I tried that but it didn't work.
