### ISSUE TITLE
Crash to desktop (can not relaunch game) when obtaining mine colony's forester's location tool.

### ISSUE THREAD

**Issue by maverickx29** [FTBTeam/FTB-Modpack-Issues#5805]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.21.1

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

[crash-2024-09-21_14.17.46-client.txt](https://github.com/user-attachments/files/17085419/crash-2024-09-21_14.17.46-client.txt)

### Describe the bug

Crashed when obtaining mine colony's forester's location tool. 
main crash message:
 java.lang.NullPointerException: Cannot invoke "net.minecraft.core.BlockPos.offset(int, int, int)" because the return value of "com.minecolonies.api.util.Tuple.getB()" is null

### Steps to reproduce

click the button in a mine colony's forester's UI to obtain the location tool. 

### Expected behaviour

not crash

### Screenshots

![image](https://github.com/user-attachments/assets/b957c775-4863-4feb-ae40-d1cf5e270267)
the offending button providing the forester's tool.

### Additional information

the tool was in my inventory in the last image when the game crashed, I attempted a few times to re-open the world and it didn't work with the same error message.

I deleted the item out of my inventory with NBTExplorer and which bypassed the crash. For testing, I was able to recreate the crash by re-obtaining the tool after this fix.

**Comment by Gaz492** [comment]
Hi, just wanted to check, is this still an issue in the latest version of the modpack for you?
I have not been able to recreate it.

**Comment by Saereth** [comment]
this should be definitely fixed after updating

**Comment by maverickx29** [comment]
it is fixed! thank you!
