### ISSUE TITLE
Ars Nouveau important structures not generating

### ISSUE THREAD

**Issue by MOPSKATER** [FTBTeam/FTB-Modpack-Issues#5806]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

"Wilden dens" not generating. This is a mod breaking bug.

### Steps to reproduce

Download serverinstaller as described on FTB.
Start server.

### Expected behaviour

"Wilden dens" generating.

**Comment by MOPSKATER** [comment]
If required, I can deliver the server files.

**Comment by MOPSKATER** [comment]
I opened an issue on the mods repo too. 
https://github.com/baileyholl/Ars-Nouveau/issues/1418

**Comment by Saereth** [comment]
As per the ars issue they do indeed appear to be spawning and the guardian dens are fixed in the update as well
<img width="1919" alt="image" src="https://github.com/user-attachments/assets/36d2d7c0-f01a-49e5-8e9b-432b511ee957">
