### ISSUE TITLE
Ars Nouveau Game crash issue

### ISSUE THREAD

**Issue by IamStig** [FTBTeam/FTB-Modpack-Issues#5808]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

Yes

### Describe the bug

Ars containment jar works fine with endermen but when a blaze has been captured the game crashed the instant I attempt to pick up the jar
[crash-2024-09-22_14.31.43-client.txt](https://github.com/user-attachments/files/17088311/crash-2024-09-22_14.31.43-client.txt)

### Steps to reproduce

1 set up a ritual brazier, click a tablet of containment on it, place a source jar containing source beside it and activate the ritual
2 place a containment jar beside this set-up.
3 release a blaze nearby
4 blaze will vanish and appear to be contained within the jar .....so far so good, no problem
5 use pickaxe to "break" the jar containing the blaze.....crashes on 1st "touch"

### Expected behaviour

jar breaks and is placed in inventory

### Screenshots

<img width="1269" alt="Ars bug" src="https://github.com/user-attachments/assets/a352b644-35c9-4981-8dbd-8c291542c728">

### Additional information

I can not tell you if any other contained mobs crash the game all I know for sure is that Endermen work as intended and Blaze crashes the game.

**Comment by IamStig** [comment]
Update - just jarred a cow and the crash occurred when I tried picking it up. Starting to wonder if the Enderman was a one off success. When I next play I will see if picking up the enderman works or crashes the game but I think the enderman was jarred in 1.1.2 (no earlier than 1.1.1) so I can't see any reason for it to now cause a crash.

**Comment by IamStig** [comment]
Update - a workaround. Moving the jars using Mekanisms cardboard box works and the "drops" from the mobs are created as normal.

**Comment by IamStig** [comment]
Further Update - I forgot to use the cardboard box and pickup a contained chicken without crashing.

**Comment by Gaz492** [comment]
I've been doing some testing on this, and it looks like it may be an issue between Ars and neat though im not entirely sure whos at fault.
The only solution I found was to disable the mod neat.

!skip

**Comment by Saereth** [comment]
closing as this is a duplicate and we're already tracking it
