### ISSUE TITLE
[Bug]: Oceanblock 1.11.0 unable to craft Creative drawer upgrade with the right recipe

### ISSUE THREAD

**Issue by Sagesheep** [FTBTeam/FTB-Modpack-Issues#581]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Describe the bug

Unable to craft creative storage upgrade from storage drawers.

All the creative item have been updated into public and ownerless.

![image](https://user-images.githubusercontent.com/51191517/150668049-eeb806f0-c984-4687-aad0-5e8acf02497e.png)

![image](https://user-images.githubusercontent.com/51191517/150668058-f0af6d41-2c50-49fb-8c22-9d471fc061bc.png)

![image](https://user-images.githubusercontent.com/51191517/150668064-b4077a7a-5a25-4e11-bbcc-8d2755d3db6e.png)

### Steps to reproduce

1. Try to craft the creative storage upgrade

### Expected behaviour

can craft the creative storage upgrade

**Comment by Sagesheep** [comment]
This might have something to do with NBT attached to the item itself. While i've cleaned the ownership and everything from the item, the creative power block have been used before.

**Comment by Sunekaer** [comment]
> This has something to do with NBT on the item after its used.
> 
> apparently it needs to be pristine item from the craft and can't be used, else the recipe won't recognised it

Which item?

**Comment by Sagesheep** [comment]
Any Creative item crafting. eg. creative battery for example, you can't use
it before if you want to use it in the draconic crafting, the crafter
refuse the usage of the item because now the item have tags init.

**Comment by TheonlyTazz** [comment]
Fixed the NBT tags on the Creative Energy Cube
