### ISSUE TITLE
Waystone config file resets on pack update

### ISSUE THREAD

**Issue by IamStig** [FTBTeam/FTB-Modpack-Issues#5810]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

Yes

### Describe the bug

I changed to waystone config to not use XP on version 1.0.0, I changed it again when the pack updated to 1.1.0 and then again on version 1.1.1

### Steps to reproduce

I think you can figure this one out.

### Expected behaviour

that the config change is carried over to the update.

**Comment by Saereth** [comment]
after 1.2.x we'll no longer distribute the waystone config
