### ISSUE TITLE
Waystones not retaining reordered list

### ISSUE THREAD

**Issue by IamStig** [FTBTeam/FTB-Modpack-Issues#5812]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

Yes

### Describe the bug

Simply put I make "Home" waystone to be at the top of the list and on restart I do it again because it has returned to 3rd page

### Steps to reproduce

open waystone menu, locate Home, shift click the up arrow, Home is now top of page 1.
Restart game and menu has reverted

### Expected behaviour

Keep the order I set

**Comment by IamStig** [comment]
Update - It appears to retain the order correctly if the destinations are moved one step at a time and not using shift click to send them to the top of page 1.

**Comment by Saereth** [comment]
this is something that will have to be resolved with waystones mod, its not something we can do anything about at the pack level. Please open your issue at https://github.com/TwelveIterationMods/Waystones/issues
