### ISSUE TITLE
Evil Craft purifier does not accept blood

### ISSUE THREAD

**Issue by jakubnabrdalik** [FTBTeam/FTB-Modpack-Issues#5814]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

When right clicking Evil Craft's purifier with a blood extractor (or a bucket) it does not fill it with blood but puts the blood extractor inside. The same with shift-right click. 
This makes it impossible to use purifier all together.

### Steps to reproduce

1. Fill a blood extractor with blood 
2. Right click on Evil Craft's purifier

### Expected behaviour

Evil Craft's purifier fills with blood on right click with blood extractor or a bucket

**Comment by Saereth** [comment]
fixed in 1.2 update
<img width="1412" alt="image" src="https://github.com/user-attachments/assets/8d8fdd84-ae8f-4913-85ca-693bcbdd17ba">
