### ISSUE TITLE
Energy Battery Auto Supply Nonfunctional. 

### ISSUE THREAD

**Issue by Darphbobo2024** [FTBTeam/FTB-Modpack-Issues#5815]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.21

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Integrated  Dynamics battery does not allow you to Shift + Right click to Auto supply power. Each attempt does nothing but 

### Steps to reproduce

1. Create energy battery
2. Give Battery Power
3. Place in hand and Shift + Right click.
4. Energy Battery does not give shimmer showing active.

### Expected behaviour

Energy Battery Shimmering showing active providing power to in selected hand item.

**Comment by Saereth** [comment]
reported to the mod dev
https://github.com/CyclopsMC/IntegratedDynamics/issues/1399

**Comment by Darphbobo2024** [comment]
> reported to the mod dev [CyclopsMC/IntegratedDynamics#1399](https://github.com/CyclopsMC/IntegratedDynamics/issues/1399)

Thank you!
