### ISSUE TITLE
Solar Generation; Panels of tier higher than hardened cannot be made due to missing resources 

### ISSUE THREAD

**Issue by 1JSIkora** [FTBTeam/FTB-Modpack-Issues#5816]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

Affected recipes from Solar Generation Src: 
    materials.put(SolarPanelLevel.REDSTONE, ResourceLocation.fromNamespaceAndPath("c", "nuggets/electrum"));
    materials.put(SolarPanelLevel.SIGNALUM, ResourceLocation.fromNamespaceAndPath("c", "nuggets/signalum"));
    materials.put(SolarPanelLevel.RESONANT, ResourceLocation.fromNamespaceAndPath("c", "nuggets/enderium"));
    materials.put(SolarPanelLevel.ADVANCED, ResourceLocation.fromNamespaceAndPath("c", "nuggets/lumium"));
    materials.put(SolarPanelLevel.ULTIMATE, ResourceLocation.fromNamespaceAndPath("c", "nuggets/platinum"));

### Describe the bug

The mod pack is missing several resources required to craft higher tiers of solar panels - these resources are provided via the OreLibrary mode which is missing from the pack

### Steps to reproduce

Attempt to craft redstone solar panel (or any of the tier above) - the recipe is not shown in JEI

### Expected behaviour

redstone and above tier solar panels should be craft-able

**Comment by Saereth** [comment]
This mod is not ported to 1.21 yet nor is thermal so for now until the mod or an addon adds further support the panels are limited to hardend.
