### ISSUE TITLE
Mod loading error has occurred: squatgrow-forge-2.0.2-build

### ISSUE THREAD

**Issue by OjiDsan** [FTBTeam/FTB-Modpack-Issues#5817]
### Modpack

FTB StoneBlock 3

### Modpack version

1.11.0

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

[latest.log](https://github.com/user-attachments/files/17094091/latest.log)
[crash-2024-09-23_09.12.22-fml.txt](https://github.com/user-attachments/files/17094092/crash-2024-09-23_09.12.22-fml.txt)

### Describe the bug

After starting the launcher, I start the game with the modpack. The game crashes while the mods are loading. Sometimes Windows 11 freezes and I have to restart my PC.

### Steps to reproduce

1.Start Curseforge 2.Start Minecraft Modpack -> Minecraft Launcher starts 3. Start the Game with the Modpacks

### Expected behaviour

I hope that it can be clarified whether the problem comes from the modpack or from my PC

### Additional information

PC:
AMD Ryzen 5 5600X
RTX 3080
32 GB 4000MHz

**Comment by Gaz492** [comment]
Could you open where the modpack is installed, then go to the config folder and upload the `squatgrow-common.yaml` as it looks like it may be having issues reading it.

**Comment by OjiDsan** [comment]
[squatgrow-common.zip](https://github.com/user-attachments/files/17095157/squatgrow-common.zip)
Unfortunately I had to pack it into a ZIP because the file format is not supported.

**Comment by Gaz492** [comment]
Unfortunately it looks like the zip file is corrupted as I'm not able to extract it

**Comment by OjiDsan** [comment]
[squatgrow.zip](https://github.com/user-attachments/files/17095214/squatgrow.zip)
Sorry, should work now

**Comment by Gaz492** [comment]
Thanks, if you right click the squat grow config and open it in notepad you should be able to fix it by copying and pasting the default config from https://dist.modpacks.ch/modpacks/2/FTB%20StoneBlock%203-1.4.0/config/93b36fa88c9210884614efd255f184cc1d69c8ca

**Comment by OjiDsan** [comment]
Fixed, thanks for the fast support
