### ISSUE TITLE
Craft the Iron’s Guidebook not craftable

### ISSUE THREAD

**Issue by Cosmicjedi** [FTBTeam/FTB-Modpack-Issues#5819]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

when trying to get started with Iron's spell n spellbooks I tried crafting the iron's guidebook and it did not produce the book it game me a book with no id tag that was unusable. 

### Describe the bug

when trying to get started with Iron's spell n spellbooks I tried crafting the iron's guidebook and it did not produce the book it game me a book with no id tag that was unusable. 

### Steps to reproduce

use arcane essence and a book in crafting table and get a broken guide

### Expected behaviour

Craft the Iron’s Guidebook

**Comment by Saereth** [comment]
already reported to ISS, waiting on a fix from them
https://github.com/iron431/irons-spells-n-spellbooks/issues/545

**Comment by Gaz492** [comment]
This looks to be fixed now, if you have any further issues do let us know
