### ISSUE TITLE
[Bug]: Crash on Launch

### ISSUE THREAD

**Issue by AlexRages12** [FTBTeam/FTB-Modpack-Issues#582]
### Modpack

FTB Ultimate Reloaded

### Modpack version

1.10.0

### Log Files

https://paste.feed-the-beast.com/view/c2b84856

### Describe the bug

Ive been playing for about 2 weeks and today I went to start my world and it crashes. I am able to load the modpack, but when i start my world it loads up to building terrain and then crashes.

### Steps to reproduce

1. Start Modpack
2. Start World
3. Crash on Load

### Expected behaviour

help with starting the pack

**Comment by Raidobw2** [comment]
Hi, try what was written in the crash log that should work:

EnderStorage was unable to read it's data, please delete the 'EnderStorage' folder Here: C:\Users\Alejandro\curseforge\minecraft\Instances\FTB Ultimate Reloaded\saves\Rage\EnderStorage and start the server again.

Let me know if that worked, and please close the issue if it did.

**Comment by AlexRages12** [comment]
Wow, I just asssumed the crash log was Mod gibberish and did not bother to read it =|. It worked, thank you!
