### ISSUE TITLE
Getting a new Fargo's guide every now and then

### ISSUE THREAD

**Issue by pwaksman973** [FTBTeam/FTB-Modpack-Issues#5821]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Not sure exactly when, it is not every login, but seems like you do get a new Fargo's guide on login (not always).
I have like 5 stored already, it is definitely not a drop.

### Steps to reproduce

Just play the game normally, exit and enter again couple of time, you end up with new Fargos guide

### Expected behaviour

Should receive it only at first time spawning the world, just like the other guide we get at starting a new world

### Screenshots

![image](https://github.com/user-attachments/assets/75b0afe5-1767-4bf5-a672-40280206f998)

**Comment by Saereth** [comment]
this was a bug, fixed in fargos update
