### ISSUE TITLE
Roots Summon villager ritual kills the internal server

### ISSUE THREAD

**Issue by JuiceyBeans** [FTBTeam/FTB-Modpack-Issues#5822]
### Modpack

FTB Interactions Remastered

### Modpack version

1.3.0

### Launcher

Other...

### Has the pack been modified

No

### Describe the bug

When I perform the ritual to summon a villager using Roots, the internal server stops working (I can walk around, but interactions don't happen and TOP says waiting for server)

### Steps to reproduce

Perform villager summoning ritual from Roots

### Expected behaviour

Summons villager without killing the server

**Comment by Gaz492** [comment]
Would you be able to upload the logs so we can take a look at them?

**Comment by Arpigah** [comment]
I have been experiencing the same issue.

Here is the latest log from my game. Let me know if this isnt the right file
[latest.log](https://github.com/user-attachments/files/17138521/latest.log)

**Comment by Derek1256** [comment]
experiencing the same issue on a server i play on, any update on a fix? based on the fact it seems RNG if it does or not, im gunna assume there isnt a fix.
(*i understand this is a old post.*)
(*ive tried recreating the bug on my own test server but with the fact it seems RNG, it doesnt wanna crash*)
