### ISSUE TITLE
Deep Learner does not 'fit' in designated curios slot

### ISSUE THREAD

**Issue by SaronGrave** [FTBTeam/FTB-Modpack-Issues#5824]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The curios menu has a designated slot for the Deep Learner for Hostile Neural Networks but the item will not go in the slot.

### Steps to reproduce

Open inventory
Pickup Deep Learner (from Hostile Neural Networks)
Try to drop in designated curios slot.
Nothing happens.

### Expected behaviour

Deep Learner should be equipped in the slot

### Screenshots

![Screenshot 2024-09-24 at 14 21 15](https://github.com/user-attachments/assets/fd895717-665a-4cce-a41b-9a0f5d77007b)

**Comment by becky15675** [comment]
I was just about to report this issue, so can confirm it exists

**Comment by Saereth** [comment]
This is a confirmed issue but wont be fixed yet, Shadows is waiting to see which curious fork ends up gaining the most traction
https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/issues/61

I did change it in the pack so it goes into the curio slot for next update but it doesnt gain mob kills while in the curio slot, that will have to wait for an official HNN update.
