### ISSUE TITLE
Add EMI

### ISSUE THREAD

**Issue by yi-fan-song** [FTBTeam/FTB-Modpack-Issues#5825]
### Modpack

FTB Presents Direwolf20 1.21

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/emi

EMI provides a modern, configurable UI for item searches and item recipes.
Some mods support only EMI and recipes are not in JEI.
EMI is fully compatible with JEI and when both are enabled, EMI UI is shown and JEI recipes are imported into EMI.

**Comment by Saereth** [comment]
You can add it yourself, the pack is fully compatible with it. Dire has elected not to ship it as a default however.
