### ISSUE TITLE
Remove Sea Serpent spawns in Overworld of FTB Interactions Remastered

### ISSUE THREAD

**Issue by MicahHaack** [FTBTeam/FTB-Modpack-Issues#5826]
### Modpack

FTB Interactions Remastered

### Is your suggestion related to a problem? Please describe.

Currently, overworld portals can place the player in the ocean in interactions remastered, which has a good chance of spawning sea serpents nearby. This in my opinion does not provide any interesting gameplay at this stage, as the players do not have any effective methods at killing the serpents before progressing farther in the overworld. Annoying spawncamps are a bigger issue, and serpents are not used in any important overworld progression points. I'd recommend moving them to spawn on a different planet instead, or adding a roots summoning ritual instead in case someone wants to fight them. The same could possibly be said for sirens as well, but they are less of an issue with much less health or one-shotting capabilities.

**Comment by ArtpokeBr** [comment]
please verify  if you have the "mobnether" stage, cause they're 100% staged to it.

**Comment by ArtpokeBr** [comment]
definetly weird then, cause in code they're staged =/
