### ISSUE TITLE
Change FTB Interactions Remastered Porcelain Chicken

### ISSUE THREAD

**Issue by MicahHaack** [FTBTeam/FTB-Modpack-Issues#5827]
### Modpack

FTB Interactions Remastered

### Is your suggestion related to a problem? Please describe.

Currently, while the questbook highly recommends making the porcelain chicken, it is effectively useless. The main problem is the chicken's main purpose was to reduce the bonemeal requirement for an early melter if the player takes the chicken route early in the skyblock section. However, the chicken requires molten clay to craft, which in turn requires the melter. By the time the player has already crafted the melter to be able to craft the chicken, it does not help the player at all.
![image](https://github.com/user-attachments/assets/b091f48d-38d7-45a6-82da-db3253efba99)
![image](https://github.com/user-attachments/assets/6b9d62d9-d7b7-4454-b251-83ff4759f297)

I'd suggest two possible changes to remedy this:
1. Change the chicken to produce bone meal instead of porcelain clay. This provides a benefit to the chicken past the melter (for bonemealing crops), as well as mild benefits to GT later (passive calcium production and automated white dye for concrete production).
2. OR Change the current recipe to use liquid dirt instead of molten clay, since liquid dirt is obtainable before making a melter via the alchemy array. This would restore the original benefit of making the melter easier if the player invests in chickens early.

Alternatively, both could be implemented, as chickens early (prior to time in a bottle) are a long investment to get started when there are plenty more things to do during the skyblock era.

**Comment by Delfayne** [comment]
The chicken definitely has uses past the skyblock section. Porcelain can convert to bricks and to Astral Sorcery's marble, as well as being a nice decorative on its own.
I never saw it as a way to make the melter easier, but I mildly like the idea of it being so. It always struck me as weird how early the porcelain chicken was introduced. I'm all for a liquid dirt recipe.
