### ISSUE TITLE
Add GeOre resource block decrafting

### ISSUE THREAD

**Issue by xaelith** [FTBTeam/FTB-Modpack-Issues#5829]
### Modpack

FTB Presents Direwolf20 1.21

### Is your suggestion related to a problem? Please describe.

The resource blocks from GeOre cannot currently be (un/de)crafted from a block back into four crystals, despite vanilla amethyst allowing this behavior. This renders the GeOre blocks as useless for anything other than decoration, negating any space-saving benefit that would usually come from crafting the block to begin with. It would be nice if something were added to allow the resource blocks to be crafted back into crystals, like Functional Storage compacting drawer compatibility, a recipe (change/addition), a change in what gets dropped when the block is broken, a machine recipe, etc.

**Comment by SaronGrave** [comment]
Common misconception but the vanilla amethyst block is also not able to be crafted back in to shards. Adding this ability would make this mod even more unbalanced in my opinion as it already gives an unlimited supply of shards with time.

**Comment by Saereth** [comment]
yeah this is intended to work the way it does for balance reasons, if you would like the mod changed you can discuss it with MrBysco on his mod page.
