### ISSUE TITLE
KubeJS Errors

### ISSUE THREAD

**Issue by ShiboNoTenshi** [FTBTeam/FTB-Modpack-Issues#5830]
### Modpack

FTB StoneBlock 3

### Modpack version

1.11.0

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

[server.txt](https://github.com/user-attachments/files/17129346/server.txt)

### Describe the bug

I always get an error message from KubeJS when I log in to the Game.

### Steps to reproduce

I have no idea what to write here, it's an error message.

### Expected behaviour

Fix the problem

**Comment by Gaz492** [comment]
If you download a fresh copy of stoneblock 3 does the issue still happen for you?
