### ISSUE TITLE
Not able to load the pack up at all

### ISSUE THREAD

**Issue by Kay1401** [FTBTeam/FTB-Modpack-Issues#5832]
### Modpack

FTB Skies

### Modpack version

1.6.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

https://pste.ch/oxalegivid.md

### Describe the bug

I am unable to load up this and other packs completely. I am able to load up bigger packs on curseforge no problem but I have issues on ftb launcher 

### Steps to reproduce

1. Open FTB Launcher
2. Click play pack
3. wait for it to crash/close

### Expected behaviour

The pack would open so i could play it 

### Screenshots

![Screenshot 2024-09-25 180412](https://github.com/user-attachments/assets/0560002a-7d3d-4403-a172-b90a4ada37c2)

**Comment by Gaz492** [comment]
It looks like your graphics drivers may be out of date, the crash you are running into is commonly seen when your graphics drivers are out of date or if you are on a laptop with an integrated graphics and a dedicated graphics card, the modpack may be using the wrong graphics card.

To begin with, we recommend making sure that your graphics drivers are up-to-date by downloading the latest drivers from the manufacture's website.

**Comment by Kay1401** [comment]
Problem Solved it was an out of date graphics drive! Thank you for your help!
