### ISSUE TITLE
Steallaris mod: cant craft rockets, missing mats

### ISSUE THREAD

**Issue by Nidaelie** [FTBTeam/FTB-Modpack-Issues#5833]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

STeallaris mod: the ingot used for the rocket body is not avaliable, if u go to single player mode u can check the ingot needed is not avaliable

### Steps to reproduce

try to crfat the rocket, u ll miss the 8x ingots needed for the body, not in game

### Expected behaviour

ingot exisiting and be able to craft it

### Screenshots

![rocket](https://github.com/user-attachments/assets/d53017e1-38cf-4917-869a-5d9f636d1cda)

**Comment by Saereth** [comment]
the new version of the pack 1.2 that is coming out soon allows any steel to be used there so it will work properly with mekanism steel ingots now

**Comment by Nidaelie** [comment]
In single player the 8 ingots needed arent Steel, it is an ubique i got
from the mod. Are u sure it ll work?

**Comment by Saereth** [comment]
yep, here is the recipe from the updated stellaris mod version

```
{
  "type": "stellaris:rocket_station",
  "ingredients": [
    {
      "item": "stellaris:rocket_nose_cone"
    },
    {
      "tag": "c:ingots/steel"
    },
    {
      "tag": "c:ingots/steel"
    },
    {
      "tag": "c:ingots/steel"
    },
    {
      "tag": "c:ingots/steel"
    },
    {
      "tag": "c:ingots/steel"
    },
    {
      "tag": "c:ingots/steel"
    },
    {
      "item": "stellaris:rocket_fin"
    },
    {
      "tag": "c:ingots/steel"
    },
    {
      "tag": "c:ingots/steel"
    },
    {
      "item": "stellaris:rocket_fin"
    },
    {
      "item": "stellaris:rocket_fin"
    },
    {
      "item": "stellaris:rocket_engine"
    },
    {
      "item": "stellaris:rocket_fin"
    }
  ],
  "output": {
    "id": "stellaris:rocket",
    "count": 1
  }
}
```

c:ingots/steel will allow any ingot tagged as steel now
