### ISSUE TITLE
Pipez energy pipe not supplying power to Mekanism Metallurgic Infusers

### ISSUE THREAD

**Issue by JakeMoe** [FTBTeam/FTB-Modpack-Issues#5834]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I've set up some Mekanism Heat Generators with lava for early passive power, and connected some energy Pipez from them to an Iron Furnace, that has been smelting fine using that power.  I'm now adding Mekanism Metallurgic Infusers, but they won't accept power.  If I change the side config to not accept power, I see Pipez disconnecting from the infuser, and if I configure the side to accept power again, the pipe reconnects.  But no power transfers in to the infusers.  Iron furnace still works fine.

If I swap out the Pipez Energy Pipe with Mekanism Basic Universal Cable, everything works.

### Steps to reproduce

Place Pipez Energy Pipe next to Mekanism Metallurgic Infuser
Pipe connects, but no RF goes into infuser

### Expected behaviour

Infuser gets RF

### Screenshots

![image](https://github.com/user-attachments/assets/41e3212d-0a99-493a-beb2-75088f785d1c)

**Comment by Saereth** [comment]
reported to mod dev https://github.com/henkelmax/pipez/issues/237
