### ISSUE TITLE
Keybinds getting reset on pack restart

### ISSUE THREAD

**Issue by Zeropainter2386** [FTBTeam/FTB-Modpack-Issues#5835]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

When booting up the pack, keybinds that were previously set get reset.

Ex; open Wireless terminal gets unbinded.

### Steps to reproduce

1. start pack
2. change keybind
3. reboot
4. keybind reset

### Expected behaviour

Keybinds to save after reboot

**Comment by Gaz492** [comment]
Just wanted to check, is this the Direwolf20 1.21 modpack or Unstable 1.21?
Currently, Direwolf20 1.21 doesn't have a version 1.2.0 but Unstable does.
