### ISSUE TITLE
Minecolonies bug

### ISSUE THREAD

**Issue by emilyxwardx** [FTBTeam/FTB-Modpack-Issues#5840]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.1.2

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Minecolonies is very buggy, the people are freezing and are needing to be reset constantly, or even not appearing as a person.

### Steps to reproduce

create a minecolonie
hire a person
doesnt do its job

### Expected behaviour

the person will get stuck, not ask for things and wont do their job

### Screenshots

![bug](https://github.com/user-attachments/assets/cd6e040e-4dba-4d0c-ba23-0455fa863bc2)

**Comment by Saereth** [comment]
new mc update should address this
