### ISSUE TITLE
FTB Direwolf 1.21 ctd

### ISSUE THREAD

**Issue by macqo004** [FTBTeam/FTB-Modpack-Issues#5842]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

cant even launch the game for the first time
it just gieves an error:
error could not create the java virtual machine 
Ive tried unstalling the latest java, seting system variables
DW1.20 pack launches fine

### Steps to reproduce

1. try to launch the game :)

### Expected behaviour

for game to work

**Comment by macqo004** [comment]
![image](https://github.com/user-attachments/assets/49d72c84-28f6-4ec6-ac8c-01e6ed245d66)
![image](https://github.com/user-attachments/assets/309ad4ff-dc38-453b-8df1-c57cd4f26f0b)

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs


I would also recommend removing the `-Xmx6024M` in the `_JAVA_OPTIONS` in your last screenshot as this can cause issues with our app and other minecraft apps out there.

**Comment by macqo004** [comment]
[console.log](https://github.com/user-attachments/files/17166280/console.log)
the only log there is

**Comment by jstansel** [comment]
> [console.log](https://github.com/user-attachments/files/17166280/console.log) the only log there is

The log only shows that "-p" is an unrecognized option. Are you able to launch any other MC 1.21.1 modpacks? Or even the vanilla 1.21.1 game?

**Comment by macqo004** [comment]
Vanilla 1.21 works for me
![image](https://github.com/user-attachments/assets/44cf08fc-ca5e-49ab-a37b-26842f0f9f6b)

**Comment by macqo004** [comment]
Tried to launch ftb unstable 1.21, failed
[console.log](https://github.com/user-attachments/files/17171830/console.log)
[debug.log](https://github.com/user-attachments/files/17171832/debug.log)
[latest.log](https://github.com/user-attachments/files/17171833/latest.log)

**Comment by macqo004** [comment]
Ive got it to work via CCurseForge nearly our of the box, just needed to use minecraft launcher and increase the ram allocation
