### ISSUE TITLE
Client Crash when Breaking Openblocks Wither Trophy

### ISSUE THREAD

**Issue by crippie** [FTBTeam/FTB-Modpack-Issues#5846]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[crash-2024-09-26_17.18.53-client.txt](https://github.com/user-attachments/files/17157404/crash-2024-09-26_17.18.53-client.txt)

### Describe the bug

I received an openblocks trophy after killing the wither one time. I placed it down, and then decided to move it, but any time I right click the statue my client crashes. I am playing on a server and the server stays up, but the client crashes every time.

### Steps to reproduce

1.) Obtain Openblocks Trophy from wither.
2.) Place Trophy In world.
3.) Try to break Trophy.
4.) Crash.

### Expected behaviour

The statue should break and drop as an item entity.

**Comment by ipaqmaster** [comment]
```
#  SIGSEGV (0xb) at pc=0x0000711ebce7ea40, pid=234588, tid=234597
#
# JRE version: OpenJDK Runtime Environment (21.0.4+7) (build 21.0.4+7)
# Java VM: OpenJDK 64-Bit Server VM (21.0.4+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x3f891]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/myUser/local/share/PrismLauncher/instances/FTB Presents Direwolf20 1.21/.minecraft/core.234588)
#
```

On left-click of these blocks.
