### ISSUE TITLE
Lootr chests sometimes not filled/broken

### ISSUE THREAD

**Issue by SaronGrave** [FTBTeam/FTB-Modpack-Issues#5850]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

https://pste.ch/ozuxiduhap.md

### Describe the bug

Some (not all) of the Lootr chests found in the world are empty or almost empty(and only seem to contain vanilla items). 
ALL lootr chest say 'loot not generated yet' at the top of the screen. 
In the included logs there are a lot of entries like this: 
`[14:32:01] [Worker-ResourceReload-5/ERROR] [minecraft/LootDataType]: Couldn't parse element ResourceKey[minecraft:root / minecraft:loot_table]:productivetrees:blocks/advanced_white_poplar_beehive - Failed to parse either. First: Unknown registry key in ResourceKey[minecraft:root / minecraft:block]: productivetrees:advanced_white_poplar_beehive; Second: Not a json array: {"block":"productivetrees:advanced_white_poplar_beehive","function":"productivelib:optional_copy_block_state","properties":["honey_level"]}`
Mostly from productivetrees entries. Not entirely sure if related though.
Is there a way to force/regenerate the loot/lootr chests? Or is this intended in some way?

### Steps to reproduce

1. Generate new world
2. find any structures with loot chests

I have had this on multiple worlds in multiple different locations.

### Expected behaviour

That there would be loot (or more loot) in the lootr chests, and that it is not in the 'loot not generated yet' state

### Screenshots

![Screenshot 2024-09-27 at 14 42 14](https://github.com/user-attachments/assets/737c1b74-45fb-4359-af68-71a8b0e7cf9d)

**Comment by Gaz492** [comment]
I believe the loot not yet generated message is normal as it only generates the loot content when you open the chest.
As for the content of the loot, im not sure what should, or should not be in them so I will let one of our pack devs look into that.
[](!skip)
