### ISSUE TITLE
Placing Plantation (from MineColonies) crashes server 

### ISSUE THREAD

**Issue by gotgoat** [FTBTeam/FTB-Modpack-Issues#5852]
[crash-2024-09-27_09.13.17-server.txt](https://github.com/user-attachments/files/17197619/crash-2024-09-27_09.13.17-server.txt)
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

Server

### Has the pack been modified

No

### Describe the bug

https://pste.ch/eciqexehut.coffeescript

### Steps to reproduce

1. Placing down any Plantation block immediately crashes server, broke the block multiple times and tried again, consistently crashes.

### Expected behaviour

Expect to get gui and area to assign worker to build plantation.

**Comment by Gaz492** [comment]
Would you be able to upload the crash report `crash-2024-09-27_09.13.17-server.txt` for us to have a look at?
It should contain more information about the crash.

**Comment by Appa1990** [comment]
[crash-2024-09-30_20.17.44-server.zip](https://github.com/user-attachments/files/17194548/crash-2024-09-30_20.17.44-server.zip)

I have the same modpack and the same issue when planting or dissamble the farming "blueprint"

**Comment by gotgoat** [comment]
> Would you be able to upload the crash report `crash-2024-09-27_09.13.17-server.txt` for us to have a look at? It should contain more information about the crash.

Added, thanks for looking.

**Comment by Gaz492** [comment]
Looks like this has been fixed by the mod author, https://github.com/ldtteam/minecolonies/issues/10285

This should be fixed in the next pack update
