### ISSUE TITLE
Powah dry ice not spawning in the world

### ISSUE THREAD

**Issue by dukinooo** [FTBTeam/FTB-Modpack-Issues#5857]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

Not really sure if it just hasnt been updated or if its a bug but i havent found anyone else saying anything about it, dry ice from the Powah mod isnt spawning in the world

### Steps to reproduce

1 create world
2 look for dry ice
3 find clay in places that seem like it should be dry ice
4 :(

### Expected behaviour

dry ice aquired

**Comment by mostlygizzards** [comment]
In previous modpacks, I was only able to craft dry ice.  I'm not particularly familiar with Powah's spawn mechanics though.  

![image](https://github.com/user-attachments/assets/630c0612-53fa-4319-84d7-69d2c322e596)

**Comment by mostlygizzards** [comment]
i'm currently using xycraft to create absurd amounts of ice that can be pumped into Powah! energizers for dry ice.

![image](https://github.com/user-attachments/assets/a063c593-95e8-42fe-8555-d9fb2ba6cc61)

**Comment by dukinooo** [comment]
Maybe Powah was changed at some point, in older versions I was able to find dry ice in the world but that is a good work around I hadn't thought of. Thanks!

**Comment by Saereth** [comment]
yeah you just need to craft it now
