### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DizzyDJW** [FTBTeam/FTB-Modpack-Issues#5859]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

Other...

### Has the pack been modified

No

### Log Files

Crash Log 1: https://pste.ch/esituhoyiq.coffeescript
Crash Log 2: https://pste.ch/owafekatad.rb

### Describe the bug

No clue. The first crash happened while trying to take an item from my backpack, and the second one just happened randomly while not even in a UI.

### Steps to reproduce

Yea... Idk

### Expected behaviour

Not that

**Comment by FaintSpeaker** [comment]
Gateways to Eternity needs to be updated to at least 5.0.1 due to `IFormattableAttribute` being removed from Apothic Attributes and being added into neoforge.

See https://github.com/Shadows-of-Fire/GatewaysToEternity/issues/62

**Comment by hhatcher** [comment]
I rolled my install back to 1.1.2 and I'm no longer having the issue.  Between that and the exception message, I suspect the crash is related to the ApothicAttributes mod update in the 1.2.1 version of the pack.

**Comment by Saereth** [comment]
this should be fixed in the new update
