### ISSUE TITLE
[Bug]: Jungle biome not existent

### ISSUE THREAD

**Issue by Raidobw2** [FTBTeam/FTB-Modpack-Issues#586]
### Modpack

FTB Revelation

### Modpack version

3.5.0

### Log Files

N/A

### Describe the bug

Jungle biomes might not exist, similar to how E2E had Integrated Dynamics Meneglin biome override the Jungle.
Might need to check it in-dev when I get time.

### Steps to reproduce

N/A

### Expected behaviour

N/A

### Screenshots

N/A

### Additional information

N/A

**Comment by TheonlyTazz** [comment]
Tested in latest In-Dev and had Jungle Biomes spawning in BoP worlds and Default ones
![grafik](https://user-images.githubusercontent.com/3908847/168484045-d9ed5bab-89ec-49ce-b81c-5239af12d2c2.png)

-Fixed in Future Version-
