### ISSUE TITLE
FTB Direwold20 1.21 Linux server don't start properly 

### ISSUE THREAD

**Issue by 4Source** [FTBTeam/FTB-Modpack-Issues#5862]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

Server

### Has the pack been modified

No

### Log Files

[debug.log](https://github.com/user-attachments/files/17174708/debug.log)
[latest.log](https://github.com/user-attachments/files/17174709/latest.log)

### Describe the bug

Direkt after install server is not starting properly.
It seems the server is running properly for now... at least I can connect to it.

### Steps to reproduce

1. Download and install of the server for linux 
2. start server with ``start.sh``
3. See lot of errors 
4. Server seems to kind of running

### Expected behaviour

Not so many errors 

### Additional information

Ubuntu 24.04

**Comment by sandalle** [comment]
It started fine for me on Linux Mint 21.3 after I copied the mods/ and configs/ folders from an installed client (there is no serverpack file to download that I could find) and then installed the matching NeoForge version using OpenJDK 21.0.4, then ran it.

**Comment by WyFryMU** [comment]
> It started fine for me on Linux Mint 21.3 after I copied the mods/ and configs/ folders from an installed client (there is no serverpack file to download that I could find) and then installed the matching NeoForge version using OpenJDK 21.0.4, then ran it.

Server files are located on the FTB site on the Versions tab of the modpack: https://www.feed-the-beast.com/modpacks/126-ftb-presents-direwolf20-121?tab=versions

**Comment by Gaz492** [comment]
May I ask what specific issue you are having?
With a modpack, it's rather common to have quite a few error messages pop up in the console while the server is starting, the general rule of thumb is, if you can connect, the world generated correctly, and you can craft modded items then everything is ok.

**Comment by 4Source** [comment]
I have really bad performance and I wondered this could come from the errors

**Comment by sandalle** [comment]
> I have really bad performance and I wondered this could come from the errors
Did you modify the "user_jvm_args.txt" file to set how much memory you want to give it? It has this note at the end, I just uncommented the bottom line to give it 4G of RAM:
```
# A good default for a modded server is 4GB.
# Uncomment the next line to set it.
-Xmx4G
```
Though it looks like their installer may ignore that as it specifies its own -Xmx and -Xms parameters in `start.sh` and then loads "user_jvm_args.txt", which may override their settings.

What type of performance issues are you having? The only issue I've had with this modpack, and not others I've run, is a periodic pause as something (not new chunks as this happens whether we're exploring or not) writes a lot of data to my disks (according to `pidstat` and `atop` ) every five minutes which causes latency in responsiveness
```
[12:31:45] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 6402ms or 128 ticks behind
[12:36:52] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 6972ms or 139 ticks behind
[12:41:59] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 6722ms or 134 ticks behind
[12:47:05] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 6257ms or 125 ticks behind
[12:52:11] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 5828ms or 116 ticks behind
[12:57:17] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 6151ms or 123 ticks behind
```

**Comment by 4Source** [comment]
> > I have really bad performance and I wondered this could come from the errors
> > Did you modify the "user_jvm_args.txt" file to set how much memory you want to give it? It has this note at the end, I just uncommented the bottom line to give it 4G of RAM:
> 
> ```
> # A good default for a modded server is 4GB.
> # Uncomment the next line to set it.
> -Xmx4G
> ```
> 
> Though it looks like their installer may ignore that as it specifies its own -Xmx and -Xms parameters in `start.sh` and then loads "user_jvm_args.txt", which may override their settings.

I gave the server 12G Ram and min of 4G also tried remove the statement in start.sh 

> What type of performance issues are you having? The only issue I've had with this modpack, and not others I've run, is a periodic pause as something (not new chunks as this happens whether we're exploring or not and not the ftbbackups which are every 30 minutes and do not cause so much disk I/O that it causes latency) writes a lot of data to my disks (according to `pidstat` and `atop` ) every five minutes which causes latency in responsiveness
> 
> ```
> [12:31:45] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 6402ms or 128 ticks behind
> [12:36:52] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 6972ms or 139 ticks behind
> [12:41:59] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 6722ms or 134 ticks behind
> [12:47:05] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 6257ms or 125 ticks behind
> [12:52:11] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 5828ms or 116 ticks behind
> [12:57:17] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 6151ms or 123 ticks behind
> ```

I have this message come up frequently if I just connected (only me) without moving ore anything build and every time this message is shown in the server console it is impossible to break blocks or interact with anything till there is a huge lag and for me this is unplayable if you have this very frequently. If this happens some times if multiple players discover new chunks, ok, I can understand that this could happen, but without doing anything.

**Comment by sandalle** [comment]
> I have this message come up frequently if I just connected (only me) without moving ore anything build and every time this message is shown in the server console it is impossible to break blocks or interact with anything till there is a huge lag and for me this is unplayable if you have this very frequently. If this happens some times if multiple players discover new chunks, ok, I can understand that this could happen, but without doing anything.

Yes, this is what I’m seeing as well. Something is causing Minecraft (or the java process running it) to do massive disk writes every five minutes, causing the server to be unresponsive for 5-10s. The console reports this happening even with no users online. Other modpacks (this is the only 1.21 or NeoForge one I’ve tried so far) haven’t exhibited this issue on my server.

I haven’t been able to narrow it down yet.
* I do see quite a bit of node in debug.log, but not enough to warrant this many disk writes.
* Maybe a java garbage collection issue and we need to tune the GC or memory parameters better
* Maybe some mod does some kind if pruning or generation periodically (5min) that modifies chuck data and requires all chunks to be written to disk again.

**Comment by Gaz492** [comment]
May I ask what the specs (CPU & Memory) of the machine you are running the server on is so we can try replicating this?

There may be a memory leak in the pack at the moment, but it may be client sided only.

**Comment by 4Source** [comment]
It is an old Laptop but I think the specs are not that bad 
i7-5500U 2.4GHz 2 Cores 4 Threads
16GB RAM DDR3 1600 MHz

**Comment by Gaz492** [comment]
So the issue may be the CPU here, looking up the exact specifications for that cpu, its single threaded performance is not great and as minecraft really depends on single threaded performance, this may be the cause of the performance issues you are running into.

**Comment by 4Source** [comment]
What performance is recommended?

**Comment by sandalle** [comment]
> May I ask what the specs (CPU & Memory) of the machine you are running the server on is so we can try replicating this?
> 
> There may be a memory leak in the pack at the moment, but it may be client sided only.

For mine I have:
- CPU: Intel(R) Xeon(R) CPU E5410  @ 2.33GHz
  - Other than start-up, at no point do any of my cores go above 6% usage, even when experiencing the delay)
- RAM: 32g of KINGSTON FB-DIMM DDR2 FB-DIMM Synchronous 667 MHz
  - At no point am I hitting swap (I have 32g of swap, 0% used)
- Disk drives: RAID-6 array of 6x 2t WDC WD20EFRX-68EUZN0 on 3Ware 9650SE SATA-II RAID PCIe card
  - This is where the delay appears to come from on mine as my array becomes 100% busy (30s average %util jumps from <8% to 25% and transactions per second (TPS) on disk go from <3 to 15-17) with writes from the Java instance running this modpack every 5 minutes). CPU utilization remains 96-98% idle during this pause and CPU %iowait increases from <1% to 3%.
    - Without Minecraft running, there is no spike in disk I/O ( %util <5%).
  - Even the world backup every 30 minutes by FTBBackup doesn't generate this much disk I/O, nor does it cause the server to pause (we don't even notice the backup other than the announcement to Ops users) as whatever the 5 minute interval issue is.
- OS: Linux Mint 21.3 Virginia x86_64
- Network Interfaces: 2x Intel Corporation 80003ES2LAN Gigabit Ethernet Controller (Copper) (rev 01) in a LACP 802.3ad (source-IP based balance) bond.
- At most I have 4 people on the server (`max-players=5` and `sync-chunk-writes=false` in server.properties as the new method generates too much/frequent I/O during exploration ).

I'll see if I can add a server profiler mod (used to have [Spark ](https://modrinth.com/mod/spark) on my old one) to see if I can help narrow it down. As other modpacks (granted, MC 1.20 and running Forge, so _not_ the latest :) ) e.g. [NST Trails & Tales](https://legacy.curseforge.com/minecraft/modpacks/nst-trails-tales) , do not experience this periodic pause.

**Comment by sandalle** [comment]
I found a work-around by putting my world/ folder into a RAMDISK instead of the local disks. I use https://wiki.archlinux.org/title/Anything-sync-daemon to keep it synced with local disks in case of power loss/reboot.
I moved `world` to `world.local`, then have `anything-sync-daemon` ( `asd` ) configured to manage `world.local`, then I created a symlink from `world` -> `asd`'s tmpfs (RAM) folder ( on mine it's `/tmp/asd-minecraft/home/minecraft/servers/ftb-presents-direwolf20-11/world.local`), the started up the Minecraft server and no pausing lag every five minutes. It's still writing a bunch of stuff it probably shouldn't be every five minutes, but honey RAM don't care. :)

```
$ sudo asd parse
Waiting for lock...
flock: getting lock took 0.000006 seconds
flock: executing /usr/bin/asd
Anything-sync-daemon v6.0.0 on Linux Mint 21.3

 Systemd service is currently active.
 Systemd resync service is currently active.
 Overlayfs v23 is currently active.

Asd will manage the following per /run/asd.conf settings:

 owner/group id:     minecraft/1006
 target to manage:   /home/minecraft/servers/ftb-presents-direwolf20-11/world.local
 sync target:        /home/minecraft/servers/ftb-presents-direwolf20-11/.world.local-backup_asd
 tmpfs target:       /tmp/asd-minecraft/home/minecraft/servers/ftb-presents-direwolf20-11/world.local
 dir size:           816M
 overlayfs size:     80M
 recovery dirs:      none
```
I still have FTBBackup running every 30 minutes so I have those backups as well, just in case. :)

**Comment by Saereth** [comment]
glad you found a work around, we also have some performance increasing mods coming in that should help a bit more as well
