### ISSUE TITLE
Creating Enderman gate pearl crashes the game

### ISSUE THREAD

**Issue by hhatcher** [FTBTeam/FTB-Modpack-Issues#5863]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

[crash-2024-09-28_15.57.23-client.txt](https://github.com/user-attachments/files/17174800/crash-2024-09-28_15.57.23-client.txt)
[crash-2024-09-28_15.55.21-client.txt](https://github.com/user-attachments/files/17174801/crash-2024-09-28_15.55.21-client.txt)

### Describe the bug

Creating an Enderman gate pearl causes a game crash.

### Steps to reproduce

Create an enderman gate pearl using a crafting table.

### Expected behaviour

An enderman gate pearl is placed in the player's inventory.

**Comment by FenixCrusader** [comment]
interacting with enderman gate pearls also crashes the game i had one crafted pre-update and after i updated, when taken into or removed from inventory the game will crash

**Comment by DizzyDJW** [comment]
Ah this may explain my crash then #5859 
No idea it was related to this until I saw this one.

**Comment by mostlygizzards** [comment]
Sounds like hover+shift is the key to the crash.

**Comment by hhatcher** [comment]
Updating to Gateways to Eternity 5.0.1 fixed this for me.  Seems like the
ApothicAttributes update in this version broke tooltips in the installed
version of Gateways to Eternity.

**Comment by mostlygizzards** [comment]
^ https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5859#issuecomment-2393906850
