### ISSUE TITLE
Observer has wrong Textures.

### ISSUE THREAD

**Issue by Dunnie97** [FTBTeam/FTB-Modpack-Issues#5864]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.21

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Most Sides of the Observer block are all using the textures of (I think) the direthings Blaze Goop.
![2024-09-28_20 03 33](https://github.com/user-attachments/assets/81f559da-b6d0-4bb3-a9b5-bf54a1fa29b9)

### Steps to reproduce

1. Craft Observer in Vanilla Crafting Table.
2. Place Observer facing downwards. 
3. Observer the Observer.

### Expected behaviour

Observer should have the Vanilla Textures.

### Screenshots

![2024-09-28_20 04 29](https://github.com/user-attachments/assets/5f3b04af-a9dc-4645-b900-66d1a2a7cf44)

**Comment by gamingwithpeter25** [comment]
that is Xycraft overide not a broken texture

**Comment by Dunnie97** [comment]
Okay but how do I fix it? Is there a config or setting I can edit or do I just nuke that mod?

**Comment by gamingwithpeter25** [comment]
it within the resource packs look for the Xycraft overide packs and move them over it should turn them off

**Comment by Dunnie97** [comment]
That works. Thanks.

**Comment by gamingwithpeter25** [comment]
your welcome
