### ISSUE TITLE
AE2 interfaces do not supply configured items

### ISSUE THREAD

**Issue by Delfayne** [FTBTeam/FTB-Modpack-Issues#5866]
### Modpack

FTB Interactions Remastered

### Modpack version

1.3.0

### Launcher

Server

### Has the pack been modified

No

### Describe the bug

The upper "Config" row in AE2 interfaces allows you to configure network items that the interface will supply, appearing in the second row.
Configuring items does not supply the items from the network.

### Steps to reproduce

Configure an item in the interface as per screenshot.
Item is not supplied.

### Expected behaviour

AE2 should supply the item

### Screenshots

![image](https://github.com/user-attachments/assets/7883bcb9-7ae8-46c1-ad2e-b57936195d30)

**Comment by ArtpokeBr** [comment]
Might be an issue with AE Itselt :T

**Comment by Delfayne** [comment]
Very likely. This is where we join the AE2EL discord and report this error there and/or on their GitHub and get it checked

**Comment by keeptpa** [comment]
Same here. Guess it's the mod's own problem. And downgrade this mod to 0.56.5 fixed it.
