### ISSUE TITLE
mineralis no work

### ISSUE THREAD

**Issue by BoxZen** [FTBTeam/FTB-Modpack-Issues#5868]
### Modpack

FTB Interactions Remastered

### Modpack version

1.2.0

### Launcher

Server

### Has the pack been modified

No

### Describe the bug

Astral sorcery's mineralis (chage stone to ore) didn't work on the ritual pedestal.

### Steps to reproduce

N/A

### Expected behaviour

N/A

**Comment by ArtpokeBr** [comment]
Does this happen in version 1.3?

**Comment by BoxZen** [comment]
Yes, and there's a new new.
It will chage stone to starmetal ore.
