### ISSUE TITLE
[Bug]: Crashing when opening quests

### ISSUE THREAD

**Issue by serbInit** [FTBTeam/FTB-Modpack-Issues#587]
### Modpack

FTB Academy 1.16

### Modpack version

1.3.0

### Log Files

https://crashy.net/giurUMLk2Rhb5pftBlHn  

### Describe the bug

When pressing [G] to open the quest book the game crashes

### Steps to reproduce

1. Join any server
2. Press key for Book
3. Crashed

### Expected behaviour

It should open the quest screen

### Additional information

It works on my other PC

**Comment by Raidobw2** [comment]
Hi, did you try a reinstall? Please let me know if Singleplayer works as well.
Thanks

**Comment by Raidobw2** [comment]
I assume this has not reappeared, or that the server was running vanilla Minecraft so I will be closing this issue
