### ISSUE TITLE
Data filter from LaserIo causing crash

### ISSUE THREAD

**Issue by Zeropainter2386** [FTBTeam/FTB-Modpack-Issues#5871]
### Modpack

FTB Unstable 1.21

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

When rightclicking with the data filter from laserIo. It will disconnect the user from a game giving the error "Failed to open a screeen with advanced data: java.lang.IndexOutOfBoundsException: readerIndex(5) + length(1) exceeds writerIndex(5): UnpooledHeapByteBuf(ridx: 5, widx: 5, cap: 5/5).

### Steps to reproduce

1. Have laserio data filter in hand
2. Rightclick
3. regret / connection crash
4. reconnect. and repeat

### Expected behaviour

open menu

### Screenshots

![image_2024-09-29_152736758](https://github.com/user-attachments/assets/e8340d4e-70d0-45a4-81dc-d1605404b079)

![image](https://github.com/user-attachments/assets/321246e6-18ae-41c9-a388-781a2e9dc9df)

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs
