### ISSUE TITLE
Pointing Simple Clicker at Enchanting Apparatus causes server crash

### ISSUE THREAD

**Issue by Wh00pAss** [FTBTeam/FTB-Modpack-Issues#5875]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[crash-2024-09-30_10.12.49-server.txt](https://github.com/user-attachments/files/17187494/crash-2024-09-30_10.12.49-server.txt)

### Describe the bug

When placing a Just Dire Things: Simple Clicker next to an Ars Nouveau: Enchanting Apparatus and orienting it with a Just Dire Things: Ferricore Wrech, as soon as it points towards the Enchanting Apparatus, the dedicated windows server throws an exception. It would seem the block position was saved on the exception as the server would crash on restart and I had to restore from the latest backup. I tested this again and it is repeatable.

### Steps to reproduce

1. Place an Ars Nouveau: Enchanting Apparatus
2. Place a Just Dire Things: Simple Clicker
3. While holding a Just Dire Things: Ferricore Wrech, rotate the Just Dire Things: Simple Clicker to point at the Ars Nouveau: Enchanting Apparatus

### Expected behaviour

To be able to point the clicker at the apparatus

### Screenshots

![image](https://github.com/user-attachments/assets/d4c8f2f4-5c40-45e6-85b8-ea88935287a0)

**Comment by Saereth** [comment]
reported to direwolf, should be fixed in the new update
