### ISSUE TITLE
[Bug]: Laterite gives the wrong titanium chunk

### ISSUE THREAD

**Issue by tigershark5639** [FTBTeam/FTB-Modpack-Issues#588]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Describe the bug

The Laterite mineral vein (used with the immersive engineering excavator) gives the better diving titanium chunk which has no use i assume it is meant to give the rid titanium chunk instead 

### Steps to reproduce

1. Check the immersive engineering book and go to the mineral deposits page 
2. It should display the wrong titanium chunk in the book
3. Finding a laterite deposit and building a excavator should also give the wrong chunk 

### Expected behaviour

To get a item that does anything 

### Screenshots

![2022-01-27_15 51 05-6](https://user-images.githubusercontent.com/68576691/151441799-cfc6c162-6466-4485-8878-7d81fdc0db23.png)

**Comment by TheonlyTazz** [comment]
Changed the config to generate all Veins with preferably `rid` Clusters, which should fix the issue
![javaw_d7vMfIYKwS](https://user-images.githubusercontent.com/3908847/168661778-cc7c4301-7988-488b-a8e2-76d4e738337a.gif)
