### ISSUE TITLE
Server Crashing on startup

### ISSUE THREAD

**Issue by Extroventerous** [FTBTeam/FTB-Modpack-Issues#5880]
### Modpack

FTB Presents Direwolf20 1.16

### Modpack version

1.16.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The server says it is closed upon startup when it was working just fine yesterday. it also shows that the server is functional, but when anyone in my home tries to log in, the server seems to reset. We believe it may be linked to the Rats mod and having the ridable chickens, as this is when it seemed to crash the first time.

### Steps to reproduce

tame a rat
Teach the rat to ride a chicken
attempt to have the rat ride the chicken

### Expected behaviour

server crash

**Comment by Gaz492** [comment]
Would you be able to upload the crash report from the server so we can take a look at it?

**Comment by Extroventerous** [comment]
Where can i find the report. Also i may have potentially emailed you guys
when it might be a server host issue. Not you

**Comment by Extroventerous** [comment]
There is unfortunately no crash report. So it must be the server thats
crashing.  Not FTB. Right?
