### ISSUE TITLE
Thaumcraft crucible not forming

### ISSUE THREAD

**Issue by imgshaver** [FTBTeam/FTB-Modpack-Issues#5884]
### Modpack

FTB Interactions Remastered

### Modpack version

1.12.2

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Thaumcraft crucible does not form after right clicking a cauldron with salis mundus

### Steps to reproduce

1. Place cauldron in world
2. Right click cauldron with salis mundus

### Expected behaviour

Cauldron will turn into thaumcraft crucible

**Comment by hiroooo1997** [comment]
@imgshaver 
Hello!
Please check if you unlocked crucible in Thaumonomicon.
Unless you unlock it, salis mundus won't work with cauldron.
You can unlock it in "Discovering Alchemy" on the first page of  Thaumonomicon.
