### ISSUE TITLE
Crash while opening singeplayer world

### ISSUE THREAD

**Issue by momo54656565** [FTBTeam/FTB-Modpack-Issues#5885]
### Modpack

FTB StoneBlock 3

### Modpack version

1.11.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[console.log](https://github.com/user-attachments/files/17210433/console.log)
[latest.log](https://github.com/user-attachments/files/17210434/latest.log)
[debug.log](https://github.com/user-attachments/files/17210435/debug.log)

[crash-2024-10-01_15.31.13-server.txt](https://github.com/user-attachments/files/17210439/crash-2024-10-01_15.31.13-server.txt)

### Describe the bug

instance is not responding while loading the world.

### Steps to reproduce

try to open the word

### Expected behaviour

Step by Step explanation how to fix the problem

### Additional information

I allready reinstalled the the App and the modpack.

the ftb debug tool gives this code: dbg:uqrQxJCOx6U

**Comment by Gaz492** [comment]
Apologies for the delay in getting back to you, are you still having this issue with the pack?
If you are would you be able to right click the modpack in the FTB App, hover on open folder then click on Worlds.
In the window that shows up, open your world folder then the serverconfigs folder and  upload the immersiveengineering-server.toml so I can have a look at it?

**Comment by momo54656565** [comment]
[immersiveengineering-server.zip](https://github.com/user-attachments/files/17647721/immersiveengineering-server.zip)

I couldn't upload the .toml-file, so I made a .zip-file. I hope this is fine.

**Comment by momo54656565** [comment]
@Gaz492 is there any solution?

**Comment by Gaz492** [comment]
Sorry, try deleting the immersiveengineering-server.toml config from the world/serverconfigs folder, according to the file, it's completely corrupted.
