### ISSUE TITLE
Potion brewer causes game to exit upon adding ingredients after netherwart

### ISSUE THREAD

**Issue by AntonLM** [FTBTeam/FTB-Modpack-Issues#5886]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

https://pastebin.com/iQQvcDzu

### Describe the bug

Adding ingredients to the Potion Brewer after netherwart caused the game to exit. I reloaded twice after that, and on each occasion the game exited after I clicked the R-arrow in the single-player screen - i.e., before showing my base.

### Steps to reproduce

Place, Potion Brewerm give power and water check both available. Add empty bottles. Add netherwart, and then add glistening melon. Watch as game dies.

### Expected behaviour

PB should commence brewing Health potion.

### Additional information

I've raised this as an issue with Ind Foregoing.

In the meantime, the game is unplayable for me.

**Comment by zeziba** [comment]
Had a similar issue with IF potion brewer. I just skipped it for now and used a combination of the AdvancedAE and super factor manager to automate the potions.

Using AdvancedAE pattern provider with the recipes to correctly input from the top and side, and then using SFM to pull out the potions if the top slot (ctrl + i) is empty in the brewer solved any issues I had with potion brewing but should be able to use the IF potion brewer none the less.
