### ISSUE TITLE
SolarGeneration Recipes missing

### ISSUE THREAD

**Issue by Yumeto2911** [FTBTeam/FTB-Modpack-Issues#5888]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

I tried to craft the Ultimate Solar Panel, but when i searched for the Recipe for the Cores are missing.

### Steps to reproduce

1. Open Inventory
2. Use JEI and search for solar panel
3. Left click Ultimate Solar Panel
4. Click on Core in Recipe
5. No Recipe is opening

### Expected behaviour

Adding the Recipes

**Comment by 4Source** [comment]
I have the same issue but it is not only for Ultimate it at:
- Redstone Solar Panel
- Signalum Solar Panel
- Rasonant Solar Panel
- Advanced Solar Panel
- Ultimate Solar Panel

I could imagine this is because of the missing ingots/Nuggets:
- Electrum
- Enderium
