### ISSUE TITLE
Amber recipe not working.

### ISSUE THREAD

**Issue by Zirica** [FTBTeam/FTB-Modpack-Issues#5889]
### Modpack

FTB Interactions Remastered

### Modpack version

1.3.0

### Launcher

Prism

### Has the pack been modified

No

### Describe the bug

Resin and certus quartz seed in the autoclave does not work to make amber

### Steps to reproduce

1. add resin and certus quartz seed in a autoclave
2. no Amber is made

### Expected behaviour

Get amber from the autoclave

### Screenshots

![image](https://github.com/user-attachments/assets/66a0bb4c-df9e-4533-96c7-57e51f17d535)

**Comment by ArtpokeBr** [comment]
hmmm this is definetly weird, just tested and I have 0 issues with this recipe.

**Comment by Zirica** [comment]
I can confirm getting the certus quartz seed from JEI works, 0% 33% and the 66% seeds. But the hand crafted seed from sand and certus quartz dust does not work to make amber
![image](https://github.com/user-attachments/assets/03d6bbca-b7ac-42e6-82fb-3eae2b42a24d)

**Comment by ArtpokeBr** [comment]
this is really odd, again, I've hand crafted a certus seed from certus dust and sand, placed in an autoclave with resin and recipe worked :T
