### ISSUE TITLE
OpenBlocks Trophy mining crashes game

### ISSUE THREAD

**Issue by RedDamer** [FTBTeam/FTB-Modpack-Issues#5897]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Both me and my friend are unable to mine a zombie trophy from the "OpenBlocks Trophies" mod that we placed down. Instead, as soon as you left click on it with any item (pickaxe, empty hand, etc.), our game crashes. Nice thing is the server stays fine at least so we're able to just relaunch and rejoin.

### Steps to reproduce

1. Place down a zombie trophy from the OpenBlocks Trophies mod
2. Attempt to break the trophy by any means possible.
3. Game will crash.

### Expected behaviour

Trophy should break and drop in world.

### Screenshots

![2024-10-02_16 34 22](https://github.com/user-attachments/assets/065d0346-0f0c-4030-bd65-6249cb8fc3c0)
![Screenshot 2024-10-02 163437](https://github.com/user-attachments/assets/aa869349-5a92-427a-861c-cf890eb296dc)

**Comment by RedDamer** [comment]
What does "not planned" mean?

**Comment by Gaz492** [comment]
In this case it just means I closed this issue as there is already an open issue for the issue you reported.
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5846

**Comment by RedDamer** [comment]
Ahhh okay. Sorry new to the whole github terms and all that. Thanks
