### ISSUE TITLE
Making brass has circular prerequisites

### ISSUE THREAD

**Issue by imgshaver** [FTBTeam/FTB-Modpack-Issues#5898]
### Modpack

FTB Interactions Remastered

### Is your suggestion related to a problem? Please describe.

I can't produce brass.

1. I need to unlock alchemical brass in the thaumonomicon to produce alchemical brass.
2. I need a research table to unlock alchemical brass.
3. I need liquid starlight to make the tables for the research table.
4. I need a lightwell to make liquid starlight.
5. I need a resonating wand to make a lightwell.
6. I need brass to make a resonating wand.

How do I get past these circular requirements?

**Comment by Delfayne** [comment]
The Crucible quest in the "What is this Sorcery" chapter provides a command as reward that learns all research required to make brass without making a research table first
