### ISSUE TITLE
Client Crashing when mousing over a certain item. 

### ISSUE THREAD

**Issue by yuriondelagrion** [FTBTeam/FTB-Modpack-Issues#5899]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

When searching for anchor, if you mouse over the last entry, it will crash the client. I am attaching the screenshot of the item in question.

### Steps to reproduce

1. Search for "anchor" in the JEI
2. Mouse over the last entry

### Expected behaviour

Not crashing the client

### Screenshots

![image](https://github.com/user-attachments/assets/b6cdd80d-4130-4384-bab1-a636009057ba)

**Comment by mostlygizzards** [comment]
Confirmed

[crash-2024-10-08_23.08.02-client.txt](https://github.com/user-attachments/files/17302320/crash-2024-10-08_23.08.02-client.txt)
