### ISSUE TITLE
[Bug]: KubeJS scripts do not recognize MekaSuit Helmet after (manual) Mekanism update

### ISSUE THREAD

**Issue by Mestrophis** [FTBTeam/FTB-Modpack-Issues#590]
### Modpack

FTB Oceanblock

### Modpack version

1.1.0

### Describe the bug

I am aware that this is a result of me updating the mod when the pack itself did not support said update, but i figured it was worth bringing up; when i started a new world after updating Mekanism (version 10.1.0 was released on 12/22/21) I noticed the mekasuit did not provide immunity to the "deepsea sickness" added by Oceanblock's scripts, even with an electrolytic breathing unit installed. after doing some research, i narrowed down the cause of the issue to the KubeJS scripts (possibly?) not interacting correctly with the mekasuit tags. this may be a result of an update to how the mekasuit exposes its nbt 

unfortunately i do not quite know where else i would bring this up, so please forgive me if this is not relevant enough to be in issues

### Steps to reproduce

1: Install Mekanism version 10.1.0 and all required dependencies (including updating Forge)
2: Load up a world and acquire a MekaSuit, with Electrolytic Breathing Modules installed in the helmet.
3: Enter the water (the interaction with End water is more visually apparent)

### Expected behaviour

The MekaSuit should provide immunity to OceanBlock's "deepsea sickness" effects, as a MekaSuit Helmet with an EBU installed is included within the accepted helmets in the script.

### Additional information

again, this was strictly derived from me manually updating Mekanism. curiously, an Oceanblock world i had from before i updated still had a functional MekaSuit Helmet, but once i uninstalled the EBUs in that one, it no longer provided immunity, even after reinstalling them.

**Comment by Raidobw2** [comment]
Thanks for the head ups, we'll give it particular attention when we get to update the mod!
