### ISSUE TITLE
Can't get to making brass

### ISSUE THREAD

**Issue by imgshaver** [FTBTeam/FTB-Modpack-Issues#5900]
### Modpack

FTB Interactions Remastered

### Modpack version

1.1.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I can't produce brass.

I need to unlock alchemical brass in the thaumonomicon to produce alchemical brass.
I need a research table to unlock alchemical brass.
I need liquid starlight to make the tables for the research table.
I need a lightwell to make liquid starlight.
I need a resonating wand to make a lightwell.
I need brass to make a resonating wand.
How do I get past these circular requirements?

### Steps to reproduce

Try to make alchemical brass without having made alchemical brass.

### Expected behaviour

I expect to have a way to get past this catch 22

**Comment by algul** [comment]
Weird, you shouldn't need to delve into AS at all. Thaumcraft alchemical brass is unlocked by the crucible quest reward.

**Comment by imgshaver** [comment]
The crucible quest reward unlocked the EVERFULLURN research instead.

**Comment by algul** [comment]
Either way its all that is needed. I just tested it. No research is necessary. Do you follow the progression in thaumonomicon? You need to scan some things, pick up the crucible and arcane crafting table and the research unlock on its own.

**Comment by Gaz492** [comment]
Just wanted to check, did you manage to solve your issue?

**Comment by imgshaver** [comment]
Yes.
