### ISSUE TITLE
Make Geore budding blocks movable like budding certuz blocks from AE2

### ISSUE THREAD

**Issue by yuriondelagrion** [FTBTeam/FTB-Modpack-Issues#5902]
### Modpack

FTB Presents Direwolf20 1.21

### Is your suggestion related to a problem? Please describe.

Don't you just hate it when you find a geore node and you have to keep those juicey budding blocks in place, instead of picking them up and moving them to a more convenient location, IE, your base. I certainly hate it. So make them movable like budding certus quartz blocks. It makes no sense for them to be immovable and if you wanna farm their drops, you gotta keep that chunk loaded, very inconvenient if you ask me.

**Comment by yuriondelagrion** [comment]
you can make new budding geores with Ars' Awakening ritual, so I guess its fine if you can't move those blocks.

**Comment by DrBretto** [comment]
You can make budding amethyst blocks. I don't see any way to make geores

**Comment by alecium** [comment]
While you can not (currently) **MOVE** the budding GeOre blocks like the quest mentions, you are able to **CREATE** budding GeOre blocks wherever you want them.

The process of creating budding GeOre blocks is as follows:
1.) Craft a Ritual Brazier, Tablet of Awakening, and a Dominion Wand from Ars
2.) Craft a chest
3.) Find the GeOre of the type you wish
4.) Place the Ritual Pedestal inside the GeOre so it is next to at least one Budding GeOre block, right click it with the tablet of Awakening, then right click with an empty hand to begin the ritual. This will spawn a Golem. Kill the golem so it drops it's token.
5.) Mine a non-budding version of the GeOre type and bring it to your desired location. Place the non-budding block where you want the budding version of the block to be.
6.) Click the non-budding version with the Golem Token to spawn the golem back in.
7.) Place a chest nearby
8.) Click the Golem with the Dominion wand, then sneak+click the chest to set it's "home"
9.) This will cause the golem to dance a bit. Particles will encircle the non-budding block and transform it into a budding version after which you can remove the golem (kill it again) and the chest.

You will end up with a Budding GeOre block in the position where you wish it to be (e.g. In your base, in a already chunk loaded area, etc) and can then use whatever method you wish to farm the clusters "locally".
