### ISSUE TITLE
Game Crash When Piping into Entangled Chest from the Nether to the Overworld

### ISSUE THREAD

**Issue by Aeternelle** [FTBTeam/FTB-Modpack-Issues#5911]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

Yes

### Log Files

[crash-2024-10-01_00.12.58-server.txt](https://github.com/user-attachments/files/17268220/crash-2024-10-01_00.12.58-server.txt)
[crash-2024-10-01_00.21.46-server.txt](https://github.com/user-attachments/files/17268221/crash-2024-10-01_00.21.46-server.txt)

### Describe the bug

Tried to Entangle a Chest (Overworld) and place the resulting block in the Nether. Pipez "Item Pipes" were used to input into the Entangled "Chest" Block for cross-dimensional item transport. Tested the setup by putting a random item in the chest to see if it'd input correctly into the Entangled "Chest" in the Nether, but appear in the inventory of the original Chest at the Overworld.

As soon as the item reaches the Entangled Chest, causes a crash. No way to access the world except by rolling back a save.

### Steps to reproduce

1. Put Chest in Overworld.
2. Bind Chest with Entangled Block and Entangler
3. Create a portal to the Nether
4. Place Entangled Chest
5. Use Item Pipes (Pipez) between the Entangled Chest and another Chest
6. Input an item into the Chest
7. Configure the Item Pipes (Pipez) with Wrench to pull/push item out of the Chest into the Entangled Chest

### Expected behaviour

The item should safely transport wirelessly, cross-dimensionnally.

### Screenshots

![connection_server](https://github.com/user-attachments/assets/747f6894-ba72-4842-a54b-f1f56beb4638)

### Additional information

The problem was first discovered by playing in a multiplayer server. We tried recreating the bug by creating a solo-creative world to try and figure out if the problem was cross-dimensionnal or whenever it was a problem an item was piped into the Entangled Inventory.

Pipez were place side-to-side (not connecting the "top" to "top".

**Comment by Gaz492** [comment]
The crash looks to be caused by the pipez mod, having also tested this, it seems that the entangled block doesn't properly link either.

I have reported the crash to the pipez developer and also reported the linking issue to the entangled developer
[](!skip)
