### ISSUE TITLE
Missing items

### ISSUE THREAD

**Issue by IamStig** [FTBTeam/FTB-Modpack-Issues#5919]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

Yes

### Describe the bug

Several "recipe" items are not obtainable  including budding amethyst required for the geode-encased bookshelf craft and chorus plant or chorus flower required to be placed for Xycraft extractor chorus fruit process. The amethyst CAN be moved with a cardboard box but can't be obtained as a block by silk touch they cease to exist as do the chorus blocks.  

### Steps to reproduce

Just 1 step - look in JEI for a method to obtain a required item without success.

### Expected behaviour

I .... expect a way to get a required item

### Additional information

I have a feeling I have come across other unobtainable blocks but ......

**Comment by FaintSpeaker** [comment]
Regarding 'Budding Amethyst': 

Budding Amethyst is created by infusing a block of Amethyst in the Enchanting Table. This gives you the block to use for crafting, and is the intended path for creating the Geode-Encased Bookshelf of Stability.

![image](https://github.com/user-attachments/assets/bdb0a8b0-0092-4c3a-9aa5-0a992e37bdbf)

**Comment by IamStig** [comment]
Thanks for that FaintSpeaker, I guess after spending too long trying to solve the Xycraft chorus problem I failed to look for an alternative to getting the in-world version of the amethyst. I hope I have missed something simple there too tbh.

**Comment by Chifilly** [comment]
You can get Chorus Flower by directly breaking the Chorus Flower on a grown plant in The End. You have to directly break the flower, if you break the stem things and bring the whole thing down, the flower breaks. I believe it has to be broken by an axe too.

**Comment by IamStig** [comment]
Chifilly.....while you are correct in that statement you failed to see the issue. 
"chorus plant or chorus flower required to be **placed** for Xycraft extractor chorus fruit process"
getting them is fine but placing them not so much. Yes the plant can be placed on endstone BUT neither the placed "flower" nor the stem that it becomes is a working block for the extractor.

**Comment by Chifilly** [comment]
Weird. Works perfectly fine for me. Are you sure you have the orientation correct? The extractor has to go _under_ the End Stone with the Chorus on top of that (and you'll want to have something above the Chorus to prevent it growing)

**Comment by zperk13** [comment]
I can confirm that it does have to go under. Here's a picture of my setup that works
![image](https://github.com/user-attachments/assets/1bea450b-cbba-4d5c-9fda-841fcb28b19e)

**Comment by Chifilly** [comment]
The extractor recipes are slightly confusing, but the diagram on the right of the recipe outlines where the extractor can go. The middle white block is the catalyst (in the Chorus case, End Stone, and is the one below the extractor in the recipe) and any of the green squares are where the extractor can go in relation to the catalyst, so for Chorus the only green square is below, so it has to go underneath the catalyst

**Comment by IamStig** [comment]
Thank you both, the image was helpful, I had tried that without the growth stopper ....it works now. Thanks again.
Could you help out with 1 more? 
Grains of infinity - I can not see what is not correct according to the diagram.
<img width="345" alt="RecipeJoined" src="https://github.com/user-attachments/assets/5ce93f6c-0665-416d-bfed-cdafa5f364da">

**Comment by IamStig** [comment]
BTW I have setup many of these processes successfully since this current official XyCraft release but some are frustratingly vague. 

<img width="578" alt="set" src="https://github.com/user-attachments/assets/964108b6-5b31-4ca6-b188-7d673d280f30">

**Comment by zperk13** [comment]
@IamStig
Try putting a fire under the reinforced obsidian block.
Relevant issue: #5843

**Comment by IamStig** [comment]
That worked. But so random and undocumented. Thank you. I mean it is a bit like the lave set up in that there is some logic to it... as in vanilla lava using dripstone has lava over a dripstone block so turning the diagram upside down makes sense. And the normal way to get grains is fire .... on bedrock not reinforced obsidian but still ... so some vague logic. Thanks again.
