### ISSUE TITLE
Crash when Using anvil

### ISSUE THREAD

**Issue by littlefyr** [FTBTeam/FTB-Modpack-Issues#5920]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

https://pastebin.com/g00EDZ2D

### Describe the bug

I've seen it a few times, always when interacting with some GUI, typically an inventory. In this case it was shift clicking a Blaze gold sword in to an anvil for enchanting. 

### Steps to reproduce

its relatively random when interacting with the player inventory in someway. I think mostly shift clicking an item is doing it but I don't know (terrible report, sorry)

### Expected behaviour

no crash

### Additional information

MacOS 
M2 chip

**Comment by mostlygizzards** [comment]
Noticing this (again)

```
Time: 2024-10-07 22:32:23
Description: Rendering screen
 
java.lang.NoClassDefFoundError: dev/shadowsoffire/apothic_attributes/api/IFormattableAttribute
	at TRANSFORMER/gateways@5.0.0/dev.shadowsoffire.gateways.gate.WaveModifier$AttributeModifier.appendHoverText(WaveModifier.java:112) ~[GatewaysToEternity-1.21.1-5.0.0.jar%23513!/:5.0.0] {re:classloading}
```

Do you have a gateway pearl in your inventory?

**Comment by littlefyr** [comment]
Yes I do, now that you mention it.

**Comment by mostlygizzards** [comment]
Just in case this is related to #5924

**Comment by mostlygizzards** [comment]
Shift+ hover will crash the game  (confirmed bug)

**Comment by littlefyr** [comment]
Ok thanks! It'll be a hard habit to get over ... but I don't plan to keep the pearl round too long.

**Comment by mostlygizzards** [comment]
Great find!
