### ISSUE TITLE
Crash while automating JustDireThings fuel

### ISSUE THREAD

**Issue by zperk13** [FTBTeam/FTB-Modpack-Issues#5922]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

Prism

### Has the pack been modified

No

### Log Files

[latest.log](https://pste.ch/bibanexeyi.md)
[debug.log](https://pste.ch/oqusatideh.md)

### Describe the bug

I had just finished building my automatic fuel maker with JustDireThhings. I put the items it needs in the system and was just watching it work. It was working for a bit before it crashed. I had broken and picked up a JustDireThings Energy Transmitter like 10 seconds before. I don't really think that's relevant but it's like the only thing that was different. I was in the void dimension. I think the problem is server side and not client side because when it crashed, the game didn't crash, it just acted like I disconnected from a server even though I was in a singleplayer world. I thought maybe it was a one time thing so I tried to load up the world, and it did the same thing again (no world got rendered to my screen before the crash). No crash report was generated (I'm guessing because of whatever is letting is fail more gracefully, isolating it to the server).

### Steps to reproduce

I honestly don't know. But if someone wants it, I can provide my world save.

### Expected behaviour

For the game to not crash

**Comment by Gaz492** [comment]
Could you share the world so I can poke around with it?

**Comment by zperk13** [comment]
Possibly related to #5923

**Comment by zperk13** [comment]
I downloaded the source code for JustDireThings, commented out the line that make the Item Collector render particles (no other particles are effected, only the item collector), compiled it and put it in my mod folder, and I'm not getting the crash. It's random so this isn't exactly scientific, but before it was always crashing within 10 seconds, and now it's been multiple minutes and no crash, so I feel fairly confident this is the issue. I've been trying to investigate what is wrong with the particle function, but haven't figured anything out yet. I'm not super familiar with minecraft mod programming so I don't know how to log things (if someone can tell me, I'd appreciate it).

No idea if this is actually the issue, but my programmer instincts are thinking maybe the the item collector tried to grab the item just as it got "deleted" turning the fuel into a different type of fuel, so therefor the item collector tried to grab an item that didn't exist anymore, which from the item management perspective it was maybe smart enough to handle, but then the particle system tried to generate particles that resemble an item that doesn't exist anymore, so it crashed. The fact that the log file mentions threads makes me lean towards this even more (race condition). I could be completely wrong on this though.

**Comment by zperk13** [comment]
Discussion in #5923 lends more credence to my "competing for item" theory

**Comment by zperk13** [comment]
I managed to consistently recreate the bug using a fairly simple setup. I made a bug report for it on the mod itself as you can see above this comment.

**Comment by zperk13** [comment]
Direwolf20 has made a commit (https://github.com/Direwolf20-MC/JustDireThings/commit/ee212cff9e2ed44d1661f821ef9929938d5c43d7) to fix this. I have not tested it but I trust that he did it successfully.
