### ISSUE TITLE
Stuck in peaceful mode

### ISSUE THREAD

**Issue by imgshaver** [FTBTeam/FTB-Modpack-Issues#5927]
### Modpack

FTB Interactions Remastered

### Modpack version

1.1.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I'm in peaceful mode. When I go to options and change my mode to easy/normal/hard, and then close options, nothing is changed. If I open options a second time, it still shows me as being in peaceful.

### Steps to reproduce

1. Go to option
2. Change game difficulty from peaceful to easy.
3. Leave options.
4. Go back into options and check whether difficulty has changed.

### Expected behaviour

I expect difficulty to change.

**Comment by Gaz492** [comment]
Are you able to change the difficulty using the command `/difficulty easy|normal|hard|peaceful`?

**Comment by imgshaver** [comment]
I'm playing in survival. It tells me I don't have permission to use that command.

**Comment by Gaz492** [comment]
If you open your world to lan, then in the menu where you do that, enable cheats/allow commands you should be able to then run the difficulty command.

**Comment by imgshaver** [comment]
Actually, it didn't work. The chat told me it changed the difficulty to easy, but no monsters are spawning in the overworld and it still says I'm in peaceful

**Comment by Gaz492** [comment]
Would you be able to share you world with us so we can take a look?
I have not been able to reproduce this issue.

**Comment by imgshaver** [comment]
It's not letting me upload my save folder. I can upload individual files from it, but not the whole folder.

**Comment by Gaz492** [comment]
You will likely need to use something like google drive/onedrive to share the files

**Comment by TheN1K0L4Z** [comment]
I'm getting this too.
