### ISSUE TITLE
[Bug]: Can‘t Spawning mobs

### ISSUE THREAD

**Issue by KuroPeach** [FTBTeam/FTB-Modpack-Issues#593]
### Modpack

FTB OceanBlock

### Modpack version

1.1.0

### Describe the bug

Playing in a multiplayer server, the player's island is not a warm deep sea, so no regular creatures are spawned, only fish and squid。
singleplayer
![image](https://user-images.githubusercontent.com/19620848/151907156-050ccb74-92a6-449a-918c-e6d2a0296fc1.png)
multiplayer
![image](https://user-images.githubusercontent.com/19620848/151907916-dd421470-8883-4510-b4d3-fb080288ff71.png)

### Steps to reproduce

no

### Expected behaviour

no

**Comment by KuroPeach** [comment]
It is not lost, the server file is automatically installed by serverinstall_91_2105.exe
![image](https://user-images.githubusercontent.com/19620848/152011314-cd19f65a-2f6c-42cd-b581-d3031265311a.png)

**Comment by Sunekaer** [comment]
Whats in the startup_scripts?

**Comment by KuroPeach** [comment]
they are the same 
![image](https://user-images.githubusercontent.com/19620848/152075518-191ff70f-b19c-4f17-b8e3-45112f688674.png)

**Comment by Sunekaer** [comment]
If you create a new world do you still have the issue? If so we need the log file

**Comment by KuroPeach** [comment]
OK, warm water and deep seas are generated, players who like to run maps to find ruins have found that, in a position far away from the player's island, I think it is the reason why I changed the distance between the islands to make it easier for teams to interact
