### ISSUE TITLE
Crashing when Alt Tabbing / Clicking off onto 2nd monitor

### ISSUE THREAD

**Issue by MindOfSynz** [FTBTeam/FTB-Modpack-Issues#5936]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

[direwolf crash.txt](https://github.com/user-attachments/files/17337111/direwolf.crash.txt)

### Describe the bug

Sometimes it just randomly crashes after a few minutes and or when I alt tab / click off screen

### Steps to reproduce

Open game
Load into world
Click off game

### Expected behaviour

game crash

**Comment by mostlygizzards** [comment]
@MindOfSynz You're not using optifine or any other client mods, I assume?

**Comment by zperk13** [comment]
Next time it crashes due to this, could you share your latest.log and debug.log files please

Also if it's really bothering you, a possible temporary fix might be to remove Sodium

**Comment by Saereth** [comment]
I'm not able to reproduce this so far, if you can help provide the latest and debug log as zperk suggested.
