### ISSUE TITLE
add Pam's Harvestcraft 2 mods

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#5939]
### Modpack

FTB Presents Direwolf20 1.21

### Is your suggestion related to a problem? Please describe.

I've seen these mods in DW20 packs before, but not in this latest Minecraft version, though they are available.

### Mod suggestion

https://www.curseforge.com/members/pamharvestcraft/projects

**Comment by Saereth** [comment]
since these rely on worldgen to get the crops and trees its something we'd have wanted to include from release. Unfortunately the mods weren't out when the pack released

**Comment by jlp1528** [comment]
I understand this concern, however Farming for Blockheads is also available, so players could use the market to acquire the seeds and saplings.
