### ISSUE TITLE
[Bug]: World crash

### ISSUE THREAD

**Issue by iBLooDY1380** [FTBTeam/FTB-Modpack-Issues#594]
### Modpack

FTB University 1.16

### Modpack version

1.4.0

### Log Files

https://crashy.net/SpzWOtcEoTcyNwZtQpZA

### Describe the bug

After restarting the PC, I can't enter my world. Immediately after trying to log into it, I get an error. Backup does not help either - everything also gives an error.

### Steps to reproduce

See crash-report

### Expected behaviour

I want to continue playing in my world

**Comment by Shadowner83** [comment]
See if this workaround fixes your issue.

https://bugs.mojang.com/browse/MC-50221

Main issue is the message: 
"IllegalArgumentException on save: Name and ID cannot both be blank"

**Comment by iBLooDY1380** [comment]
> Посмотрите, исправит ли этот обходной путь вашу проблему.
> 
> https://bugs.mojang.com/browse/MC-50221
> 
> Основная проблема заключается в сообщении: "Исключение IllegalArgumentException при сохранении: имя и идентификатор не могут быть пустыми одновременно"

But after all, I'm launching the world in a single-player game. Also now I noticed that when I try to create a new world, I get the same error. 
At the moment, I changed my nickname and everything worked for me, but all the achievements and quests flew off. This can be considered a solution to the problem, but I would like to figure out how I can enter my world with my first nickname

**Comment by Raidobw2** [comment]
Hello, did the provided workaround by Shadowner83 work to solve the issue? This might also have been caused by Mojang services themselves not working properly for a while. Please let me know if you still need help or this is resolved.

**Comment by iBLooDY1380** [comment]
> Hello, did the provided workaround by Shadowner83 work to solve the issue? This might also have been caused by Mojang services themselves not working properly for a while. Please let me know if you still need help or this is resolved.

Hello. No, it didn't help me, but I solved the problem as I wrote above - I changed my gaming account to a new one
