### ISSUE TITLE
Ars Nouveau Containment crash

### ISSUE THREAD

**Issue by Caffinatedjunkie** [FTBTeam/FTB-Modpack-Issues#5947]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

FTB App

### Has the pack been modified

Yes

### Log Files

[latest.log](https://github.com/user-attachments/files/17352795/latest.log)
[crash-2024-10-13_18.02.57-client.txt](https://github.com/user-attachments/files/17357237/crash-2024-10-13_18.02.57-client.txt)

### Describe the bug

There are multiple issues, but the main one is that if I try to break a containment jar from ARS, the mod pack crashes.  Also, if you die in the game and have a full inventory, items on your character get voided. 

### Steps to reproduce

Go to Ars nouveau and capture a creature (in my case a blaze) in the jar with the containment ritual. then try to break the jar when finished, and the game should crash regardless how you try to break it.

### Expected behaviour

crash

**Comment by coldfire80** [comment]
I also have the same issue. I used a wilden and got the same result.

**Comment by Caffinatedjunkie** [comment]
I tired it again today in creative and I looked at the crash report which I believe says it couldn't render the containment jar with the creature in it.
[crash-2024-10-13_18.02.57-client.txt](https://github.com/user-attachments/files/17357233/crash-2024-10-13_18.02.57-client.txt)
