### ISSUE TITLE
[Bug]: simple achievements

### ISSUE THREAD

**Issue by KrstoShaolin** [FTBTeam/FTB-Modpack-Issues#595]
### Modpack

FTB Presents Skyfactory 3

### Modpack version

3.0.21

### Log Files

https://github.com/FTBTeam/FTB-Modpack-Issues/files/7995301/latest.log need to download 

### Describe the bug

I played until the 60th day (in minecraft), and it happened to me that I opened the inventory and started typing for something and suddenly the screen froze and the game stopped working, I closed it and tried to get back into my world or just stood loading world. This is not the first time this has happened to me, this is the second time.

### Steps to reproduce

1. Go to logs and check 

### Expected behaviour

Uhhh

### Screenshots

https://user-images.githubusercontent.com/98963556/152363371-b2715ce1-91b4-4441-a969-c3a0c92226fa.PNG

### Additional information

And in the logs the man found a problem with Simple Achievements mod, And the only thing he found was that he didn't have time, and that means the second time it happens, I play normally and it happens once ...

**Comment by Raidobw2** [comment]
I think I answered already on the FTB Discord, please try checking this file:

> The file at `config/island.json` seems corrupted, is it currently empty? That's what contains the islands, their players and the position of those islands.

**Comment by Raidobw2** [comment]
Solved in the FTB Discord a while back with the above solution
