### ISSUE TITLE
Problem with FTB Skies Expert

### ISSUE THREAD

**Issue by YoggyFP** [FTBTeam/FTB-Modpack-Issues#5951]
### Modpack

FTB Skies Expert

### Modpack version

1.9.1

### Launcher

Other...

### Has the pack been modified

No

### Log Files

https://paste.ee/p/qF1am

### Describe the bug

Two days ago the game was working just fine. I'm using multimc, and now it just doesn't function. No idea why, other modpacks work properly, just this one's broken.

### Steps to reproduce

Install cyberpunk and hope for the best, i guess. That's what i've done since i played.

### Expected behaviour

Press play, hope to launch, doesn't launch, sad.

**Comment by Gaz492** [comment]
Would you be able to upload the debug.log from the logs folder, it should hopefully contain more information about whats going wrong.
