### ISSUE TITLE
[Suggestion] Requested Mods

### ISSUE THREAD

**Issue by DizzyDJW** [FTBTeam/FTB-Modpack-Issues#5957]
### Modpack

FTB Presents Direwolf20 1.21

### Mod suggestion

[Mahou Tsukai](https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai)
It's added in modpacks relatively regularly but gets little to no publicity, yet remains an incredible mod, especially in terms of damage output, it is 2nd to none.

[Forbidden & Arcanus](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)
A way to give items unbreakable, permanently. Also, just an all around enjoyable mod, really makes you work for the good items.

**All of [Yung'sBetter Mods](https://www.curseforge.com/minecraft/search?page=1&pageSize=20&sortBy=relevancy&search=yung%27s)**
The lack of grandiose structures and world-building puts a major damper on exploration.

> YungsAPI
> YungsBetterDesertTemples
> YungsBetterDungeons
> YungsBetterEndIsland
> YungsBetterJungleTemples
> YungsBetterMineshafts
> YungsBetterNetherFortresses
> YungsBetterOceanMonuments
> YungsBetterStrongholds
> YungsBetterWitchHuts
> YungsExtras

[Structory](https://www.curseforge.com/minecraft/mc-mods/structory)
Again, lack of structures to explore.

[Mob Grinding Utils](https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils)
Super handy mod for handling mobs, which is mostly already semi-doable with JustDireThings, but mostly needed for the beheading mechanic which does not exist in any other mod in this pack.

[Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
_**Not Yet Updated**_
Once it reaches 1.21, please add it, it adds such a cozy vibe and so many useful knick-knacks that really manage to brighten up the world.

**Comment by Saereth** [comment]
added a bunch of these in the next update, dire didnt want mahou this time around, forbidden arcanus has some really bad jei integration so it wasnt added for now. Most of the yungs mods were except for nether fotress and ocean monuments due to conflicting worldgen issues. Mob grinding utils was added. Supplementaries updated and was added.
