### ISSUE TITLE
Gallium catch 22

### ISSUE THREAD

**Issue by imgshaver** [FTBTeam/FTB-Modpack-Issues#5958]
### Modpack

FTB Interactions Remastered

### Modpack version

1.1.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I can't get gallium without first having gallium.
Gallium requires ores in the nether.
Getting to the nether requires thaumium ingots.
Thaumium ingots require stainless steel.
Stainless steel requires mv circuits.
Mv circuits require gallium.

### Steps to reproduce

Try to acquire gallium without already having gallium

### Expected behaviour

I expect a path to lead me to acquiring gallium.

**Comment by Delfayne** [comment]
There are multiple pages to the making thaumium recipes. You can also use steel or mana-infused ingots which do not require gallium
