### ISSUE TITLE
Conflicting Certus Quartz Dust Recipes in Enrichment Chamber

### ISSUE THREAD

**Issue by natebc** [FTBTeam/FTB-Modpack-Issues#5966]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

Other...

### Has the pack been modified

No

### Describe the bug

seems to be a regression of #5778

### Steps to reproduce

insert certus quartz dust
get silicon instead of certus quartz crystal

### Expected behaviour

only one outcome of recipe

### Screenshots

![image](https://github.com/user-attachments/assets/9629b7b8-2699-4220-b4f1-465b0e0eb284)

**Comment by Raidobw2** [comment]
This seems fixed in 1.4.1+
![image](https://github.com/user-attachments/assets/aa5be9be-a580-4958-a74d-f5fbc40cab46)
![image](https://github.com/user-attachments/assets/f3534fbb-b0ae-49f3-9429-50454d80adde)
