### ISSUE TITLE
Just Dire Things: Shovel with Lawnmower does not remove short grass from Project: Vibrant Journeys

### ISSUE THREAD

**Issue by zircuitz** [FTBTeam/FTB-Modpack-Issues#5967]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

Prism

### Has the pack been modified

No

### Describe the bug

When using the lawnmower function on the Shovel from Just Dire Things: It does not clear the "Short grass" from "Project: Vibrant Journeys".

### Steps to reproduce

1. Obtain A Shovel from Just Dire Things
2. Install the Lawnmower upgrade on it.
3. Right-click a patch of tall grass.

### Expected behaviour

All grass and plants should be cleared.

### Screenshots

![javaw_chgdo66bMa](https://github.com/user-attachments/assets/c0ae9d9a-2134-4310-8159-f157fe4298fa)

**Comment by Gaz492** [comment]
Looks like this can be done using a datapack
![](!skip)

**Comment by zircuitz** [comment]
Alright, Thanks :)
Closing the issue
