### ISSUE TITLE
crash after upgrade to FTB Interactions Remastered 1.4.0

### ISSUE THREAD

**Issue by alfredhdahl** [FTBTeam/FTB-Modpack-Issues#5968]
### Modpack

FTB Interactions Remastered

### Modpack version

1.4.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[crash-2024-10-14_18.08.10-server.txt](https://github.com/user-attachments/files/17380764/crash-2024-10-14_18.08.10-server.txt)

### Describe the bug

game crashed after upgrade to 1.4.0. 

### Steps to reproduce

1. backup "saves"..
2. Upgrade to 1.4.0
3. start game
4. try to load world

### Expected behaviour

no crashing

**Comment by Gaz492** [comment]
Would you be able to share your world with us so we can have a look?
Also just to confirm, this is happening every time you try loading the world?

**Comment by alfredhdahl** [comment]
well; I tried upgrading again, I got the same message (attached) but this time it has not crashed.
![Skjermbilde 2024-10-16 161438](https://github.com/user-attachments/assets/9474bc29-3c6b-4d1c-b252-9d1224964604)

**Comment by alfredhdahl** [comment]
I can share the world that crashed if you still want it

**Comment by Gaz492** [comment]
If you can that would be great

**Comment by ArtpokeBr** [comment]
This is not a Crash, Graduated Cylinders got removed, simply press yes to get back to your world :)

**Comment by alfredhdahl** [comment]
yes, so I did, and _then_ it crashed :) my save is a bit too big to be uploaded (28MB),

now I will try 1.4.0 -> 1.6.0

**Comment by alfredhdahl** [comment]
yes - well - nope. Upgraded 1.4.0->1.6.0. walking on dirt, throws me off the platform (I am still in the first dimension) and my grave ended up a few chunks away. getting som cobble for rescue, walked on dirt again, same thing happens. I'm sticking to 1.4 for now :D
