### ISSUE TITLE
[Bug]: Cannot configure Channel on Node from RFToolsControl in FTB DW20 1.16.5

### ISSUE THREAD

**Issue by basneder** [FTBTeam/FTB-Modpack-Issues#597]
### Modpack

FTB DW20 1.16.5

### Modpack version

1.13.2

### Log Files

[Render thread/ERROR] [mcjtylib/]: Could not find widget 'channel'!
[Render thread/INFO] [minecraft/NewChatGui]: [CHAT] Could not find component 'channel'!

### Describe the bug

When I place a "Node" from RFToolsControl in world and right-click it to set a Name and Channel, it reports in chat "Could not find component 'channel'"

The GUI to modify channel and name does appear, but I cannot type anything in to the 'channel' field.

### Steps to reproduce

1. Place Node (RFToolsControl) in world
2. Right-click the block
3. GUI screen appears and error appears in chat
4. Channel field cannot be edited

### Expected behaviour

Channel and Name of Node can be configured

**Comment by Co-Bolt** [comment]
We're having this exact same issue in FTB University 1.16.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
