### ISSUE TITLE
Ethanol bucket not recognised in the quest

### ISSUE THREAD

**Issue by visardoris** [FTBTeam/FTB-Modpack-Issues#5971]
### Modpack

FTB NeoTech

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I distilled a full bucket of ethanol (f****** finally) but the quest doesn't recognise its success.
The ethanol was pulled to the me system from the distillery und i took the full bucket out of the system.
I just checked again, the sole dependency "Chemical Reactor" is completed.

### Steps to reproduce

1. put sugar solution in the Distillery
2. let the ME system pull the etanol from the distillery via import bus
3. take the bucket of etanol out of the system
4. see how the quest doesn't complete

### Expected behaviour

Quest "1 B of Ethanol" completes

**Comment by visardoris** [comment]
The issue is from FTB NeoTech, not Direwolf20 1.21

i clicked on the link in the esc menu in NeoTech and expected to be forwarded to the specific NeoTech report site and failed to notice the wrong mod pack to be selected.

I would change the selection but sadly I cannot edit the issue after committing

**Comment by visardoris** [comment]
btw the quest shows 0 "mB /1 B [0%]" in the quest progress

**Comment by koh-gh** [comment]
You must insert the ethanol into the task screen using liquid pipes.
