### ISSUE TITLE
Minecraft Crash when im trying to load world

### ISSUE THREAD

**Issue by lplolo** [FTBTeam/FTB-Modpack-Issues#5973]
### Modpack

FTB NeoTech

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

Yes

### Log Files

[crash-2024-10-16_14.54.40-client.txt](https://github.com/user-attachments/files/17396127/crash-2024-10-16_14.54.40-client.txt)

### Describe the bug

when i try to start the world its goes from Loading the Terrain to Saving game and then it crashes 

### Steps to reproduce

[crash-2024-10-16_14.54.40-client.txt](https://github.com/user-attachments/files/17396152/crash-2024-10-16_14.54.40-client.txt)

### Expected behaviour

That you can help me with the mod that make this

**Comment by Gaz492** [comment]
The crash log seems to show that modern industrialization is running into an issue when reading nbt data from something.
I would probably recommend reloading a world backup from when the world was last able to load.

**Comment by lplolo** [comment]
Hello So i did load the oldest auto safe of this world. It is running but i some recepies arent working:/ Z.b. the recep for steel plates in the compressor isnt working anymoreBut thanks for the helpAm 18.10.24 um 12:30 schrieb Gareth Williams
                
            
            
                
                    Von: "Gareth Williams" ***@***.***>Datum: 18. Oktober 2024An: "FTBTeam/FTB-Modpack-Issues" ***@***.***>Cc: "Author" ***@***.***>,"lplolo" ***@***.***>Betreff: Re: [FTBTeam/FTB-Modpack-Issues] Minecraft Crash when im trying to load world (Issue #5973)
                
                
The crash log seems to show that modern industrialization is running into an issue when reading nbt data from something.
I would probably recommend reloading a world backup from when the world was last able to load.

**Comment by Gaz492** [comment]
> Hello So i did load the oldest auto safe of this world. It is running but i some recepies arent working:/ Z.b. the recep for steel plates in the compressor isnt working anymoreBut thanks for the help

The recipe issues, may be a bug where they didnt load correctly, if you close and reopen the modpack they may load correctly for you. If it doesnt, try closing the modpack, then in the app right click the modpack, select settings, then click on the repair button.
