### ISSUE TITLE
Porcelain is unobtainable

### ISSUE THREAD

**Issue by ivelieu** [FTBTeam/FTB-Modpack-Issues#5976]
### Modpack

FTB Interactions Remastered

### Modpack version

1.5.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I assume part of changes with #5827, there's just no recipe for porcelain outside the porcelain chicken, which itself requires a porcelain smelter.
![image](https://github.com/user-attachments/assets/395248f4-b32a-4b6f-a382-c219ca3ad6fd)

The chicken itself is also unobtainable as you need ticon liquid dirt, animus liquid dirt produced via arcane ashes is not accepted for the porcelain chicken recipe (although the QB describes it as optional) and ticon liquid dirt is only obtainable through porcelain smelter.
![image](https://github.com/user-attachments/assets/e031457a-b974-49e0-ac74-d1b0f991de84)

Since you need porcelain melter to progress into bronze age by making copper ingots, I just have to spawn it in to continue. 

### Steps to reproduce

JEI

### Expected behaviour

Normal porcelain recipe

**Comment by BaydenDora** [comment]
Also encountered this issue, as the bonemeal and clay recipe was removed before update 1.4.0(the version i encountered it on)

**Comment by ArtpokeBr** [comment]
Yeah, this wasn't intentional, instead of using the method of "add shapeless recipe for this" I accidentally used the "RE add shapeless recipe for this" so the original recipe was removed instead of coexisting with the porcelain egg to porcelain recipe.
