### ISSUE TITLE
Enchanted Blocks delete fuel cells upon reload. Breaking them loses enchantments.

### ISSUE THREAD

**Issue by MantasXVIII** [FTBTeam/FTB-Modpack-Issues#5978]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

https://github.com/user-attachments/assets/873ad0c2-cb02-457b-84ba-ed7e588336ce

A furnace is enchanted with Speed 7. A full fuel cell is placed inside. It works as intended.

Relog.

Fuel cell is now gone, furnace stays lit. When you break the furnace, it now loses its enchantments.

### Steps to reproduce

See above.

### Expected behaviour

Furnace should keep enchantments. Fuel cell shouldn't be deleted after relog.

**Comment by Gaz492** [comment]
I have not been able to replicate this on the latest version of the modpack (1.3.0). Would you be able to update and check if this is still an issue for you?
