### ISSUE TITLE
[Bug]: Game crash

### ISSUE THREAD

**Issue by Amjed21** [FTBTeam/FTB-Modpack-Issues#598]
### Modpack

FTB Skyblock 3 

### Modpack version

3.0.21

### Log Files

https://pastebin.com/51PN7MfG

### Describe the bug

..

### Steps to reproduce

..

### Expected behaviour

..

### Screenshots

..

### Additional information

..

**Comment by Raidobw2** [comment]
Hi, have you tried to backup your worlds and reinstall the modpack?

**Comment by Amjed21** [comment]
> Hi, have you tried to backup your worlds and reinstall the modpack?

yep, it's not work!

**Comment by Raidobw2** [comment]
Hmm that's odd. Do you only have 8GB of memory on your computer? Try to close some programs and then play the modpack.

You should also update your graphics drivers if they are not up to date. Let me know if it still crashes after that, I will need to research more about the error if it does.

**Comment by Amjed21** [comment]
> Hmm that's odd. Do you only have 8GB of memory on your computer? Try to close some programs and then play the modpack.
> 
> You should also update your graphics drivers if they are not up to date. Let me know if it still crashes after that, I will need to research more about the error if it does.

no i have 12GB.
ok, let me check out.

**Comment by Amjed21** [comment]
> Hmm that's odd. Do you only have 8GB of memory on your computer? Try to close some programs and then play the modpack.
> 
> You should also update your graphics drivers if they are not up to date. Let me know if it still crashes after that, I will need to research more about the error if it does.

I updated my graphics drivers, and it still doesn't work.

**Comment by Raidobw2** [comment]
I see you're not using the FTB App, I know that could cause issues since the modpack could be broken on other sources. Can you try with the FTB App and let me know if it works? Thanks.

**Comment by Raidobw2** [comment]
No other replies from user, closing this. Please try the FTB App, and if you experience issues on our App visit us in the FTB Discord.
