### ISSUE TITLE
Remove unnecessary petrol Oils or normalize their usage and recipes

### ISSUE THREAD

**Issue by bevilp** [FTBTeam/FTB-Modpack-Issues#5983]
### Modpack

FTB Interactions Remastered

### Is your suggestion related to a problem? Please describe.

Currently, there are 4 types of petrol oils available: Oil, Raw Oil, Light Oil and Heavy Oil.

Only regular "Oil" is searchable in JEI, but the other 3 are still obtainable (fluid rig, oil sands) and have distillery recipes.

Only regular Oil is actually worth using as it is the only one to have the Canola, lubricant and Sludge recipes, while the other 3 don't. The other 3 oils don't have any differences in usage and are all inferior to regular "Oil".

Having recipes to use those Oils with Canola to make Diesel would also give an alternative to having to use janky pumps, by using oils sands instead, for example.

**Comment by ArtpokeBr** [comment]
These oils are a default thing of gregtech, I don't se a reason to completely disable them.

I did found out that for some reason they were hidden, they should be unhidden now :p
