### ISSUE TITLE
Tesselating block model

### ISSUE THREAD

**Issue by howroyd** [FTBTeam/FTB-Modpack-Issues#5986]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.1

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

https://pastebin.com/mrpisqLU

### Describe the bug

The game crashed whilst tesselating block model
Error: java.lang.IllegalStateException: Missing elements in vertex: UV0, Normal
Exit code: -1

### Steps to reproduce

1. Hit OpenBlocks trophy (Skeleton) with pickaxe
2. Crash will happen immediately, right when I would expect the block to start looking cracked

### Expected behaviour

Expected the block to start showing the breaking animation after first hit with the pickaxe

### Screenshots

https://prnt.sc/fGoLCTEw56Oh

### Additional information

I am using a celestigem pickaxe.

**Comment by Gaz492** [comment]
Does this still happen if you update the modpack to the latest version (1.3.0)?
There was an issue with the mod neat that caused a crash if you punched an openblocks statue or an ars containment jar that should have been fixed in the latest update.

**Comment by howroyd** [comment]
@Gaz492 happy to report that the block breaks on `1.3.0` with no issues.

Much obliged and thank you for all the hard work, all.
