### ISSUE TITLE
sky odyssey crashes

### ISSUE THREAD

**Issue by jeffey55** [FTBTeam/FTB-Modpack-Issues#599]
### Modpack

FTB sky odyssey

### Modpack version

1.3.0

### Log Files

[crash-2022-02-03_19.45.06-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7999481/crash-2022-02-03_19.45.06-server.txt)

### Describe the bug

game crashes when you place down a tech reborn plat bending machine

### Steps to reproduce

open any game build or get a plate bending machine place it down in the world if that does nit do try and open the GUI for it 

### Expected behaviour

it should open the gui for the machine

**Comment by Raidobw2** [comment]
Hello, I've posted a fix back then on the FTB Discord, try this:

> You can update the mod that should fix the machine's code: I think https://www.curseforge.com/minecraft/mc-mods/techreborn/files/2966851 should be the one. Take the Tech Reborn mod from your mods folder and replace it with the new one.
> I don't think you'll need to update Reborn Core, but in case you crash, then you do: same thing https://www.curseforge.com/minecraft/mc-mods/reborncore/files/3330308.

**Comment by jeffey55** [comment]
Excellent thank you I appreciate your help

**Comment by Raidobw2** [comment]
I should update the modpack at some point as time allows it, for now this is resolved so I will go ahead and close it.
