### ISSUE TITLE
Just Dire Things, Duplicate upgrades

### ISSUE THREAD

**Issue by OniVodja** [FTBTeam/FTB-Modpack-Issues#5991]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

If you place some of the just dire things tools on a item frame it drops coppies of all the upgrades on the tool

### Steps to reproduce

1. Place item frame
2. Put Just Dire Things tool with upgrade in item frame
3. Duplicated upgrades drop on ground while tools still have the upgrades on them

### Expected behaviour

Tool to be placed in frame without duplicating the upgrades

**Comment by KoolKat69** [comment]
Can confirm this. My players reports this as well.

**Comment by Gaz492** [comment]
Unfortunately, this looks to be an issue with neoforge https://github.com/Direwolf20-MC/JustDireThings/issues/198
Which means there's not much we can do for now.
![](!skip)

**Comment by Tenchu98** [comment]
I suggest putting an if catch in place to desspawn the items before they actually drop. That would be the simplest fix.
