### ISSUE TITLE
Game Crashes when opening world to friends

### ISSUE THREAD

**Issue by Kanuncknar** [FTBTeam/FTB-Modpack-Issues#5993]
### Modpack

FTB OceanBlock

### Modpack version

1.16.0

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

The game crashed whilst rendering screen Error: java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### Describe the bug

the game crashes when opening the world to friends using the button in the pause menu

### Steps to reproduce

1 open world
2 open menu 
3 click open to friends 
4 game crashes after saving world

### Expected behaviour

expected the game to allow friends to join using minetogether

### Additional information

also crashes the same way on the feed the beast launcher

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by Kanuncknar** [comment]
[debug.log](https://github.com/user-attachments/files/17456466/debug.log)
[latest.log](https://github.com/user-attachments/files/17456467/latest.log)
[crash-2024-10-21_16.31.41-client.txt](https://github.com/user-attachments/files/17456507/crash-2024-10-21_16.31.41-client.txt)

**Comment by Gaz492** [comment]
Thanks, does this happen every time you try opening your world to friends?

**Comment by Kanuncknar** [comment]
yes everytime, im unable to play with a mate as it also happens when he try to host.

**Comment by Gaz492** [comment]
Could you try checking if the latest version of Minetogether fixes the issue for you?
Ive not been able to reproduce the issue so I cant tell if it does or not.

The latest version can be downloaded from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5993

**Comment by Kanuncknar** [comment]
Looks like that fixed it thanks for the help
