### ISSUE TITLE
[Suggestion]:  Quests for full primordial pearl

### ISSUE THREAD

**Issue by drcrazy** [FTBTeam/FTB-Modpack-Issues#6]
### Modpack

FTB University 1.12

### Is your suggestion related to a problem? Please describe.

There are no quests describing how to get full primordial pearl. This is causing a lot of questions from people trying to learn Thaumcraft for a first time. 

Example report is here: 

- https://github.com/FTBTeam/FTB-University/issues/326
- https://github.com/FTBTeam/FTB-University/issues/198
- Question how to get full primordial pearl was raised several times in Discord

**Comment by manmaed** [comment]
@aaronhowser1 any word on this has this been fixed or added?
