### ISSUE TITLE
[Bug]: Server crash while starting the server

### ISSUE THREAD

**Issue by Buldr1504** [FTBTeam/FTB-Modpack-Issues#600]
### Modpack

FTB Infinity Evolved Skyblock

### Modpack version

2.0.1

### Log Files

https://pastebin.com/W6VNdJE1

### Describe the bug

I downloaded the FTB Infinity Evolved Skyblock server files via FTB App and browser. After completing the installation, I started the server and agreed to the EULA. After a few seconds, the server stops while loading with the crash log seen in the link above. I'm trying to set up a local server just for me and I am not even close to understanding what the problem might be. I did not add or change any mods or files. 

If you need any additional files or information, please feel free to ask! I'm not really good with this kind of stuff, so I might need a little hint where to find said information. 

### Steps to reproduce

1. Download server files via FTB App
2. Successfully complete the installation
3. Start up the server, agree to the EULA
4. Wait a few seconds for the crash to happen

### Expected behaviour

No crash while starting the server

**Comment by Raidobw2** [comment]
Hi, we have a fix in the FTB Discord in the "infinity-evolved" channel, look in the pinned messages on that channel. Check it out and let me know if that resolves it, if it does, please close this issue and reach us in the Discord for future technical issues.
![image](https://user-images.githubusercontent.com/17010632/152626976-fc663add-1c50-4920-86f2-8d0a61c1200b.png)
Thanks!

**Comment by Buldr1504** [comment]
It works perfectly fine now. Not only did you help me fix my crashing server, you helped me with the issue of being stuck user side at phase 3 at 5/7 before I even knew I would run into it. Thank you very much, I really appreciate it. Issue is closed!
