### ISSUE TITLE
Andesite Amethyst 

### ISSUE THREAD

**Issue by Fireslar** [FTBTeam/FTB-Modpack-Issues#6002]
### Modpack

FTB Interactions Remastered

### Modpack version

1.6.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Andesite Amethyst can be gotten from asteroid mining but cannot be used for anything.

### Steps to reproduce

Check Andesite Amethyst uses

### Expected behavior

Andesite Amethyst have uses

### Screenshots

![2024-10-22_08 06 05](https://github.com/user-attachments/assets/cb648335-76e9-4f29-8402-4a19b610625a)
![2024-10-22_08 05 59](https://github.com/user-attachments/assets/5afb0dbe-0df2-491a-b684-a1a4eaaae15f)

### Additional information

if you place and break the block it becomes regular amethyst which can be used

**Comment by ArtpokeBr** [comment]
alright, asteroids shouldn't contain wrong variants, also for your already mined andesite ores, the squeezer should be able to process them :)
