### ISSUE TITLE
Universal Pipes bug

### ISSUE THREAD

**Issue by Valdoff96** [FTBTeam/FTB-Modpack-Issues#6003]
### Modpack

FTB Unstable 1.21

### Modpack version

1.20

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Using universal pipes from the Pipez mod causes the game to crash. I tried using them on Advanced Beehives and Mekanism machines.

### Steps to reproduce

1. Craft Universal Pipes
2. Attempt to place next to a block.
3. Game crashes

### Expected behaviour

Pipes are placed and usable

**Comment by ArtpokeBr** [comment]
Gonna be closing this issue as Pipez just got update on the newest update for the pack, let me know if this issue still persists :)
