### ISSUE TITLE
Laser Source uncraftable

### ISSUE THREAD

**Issue by Valdoff96** [FTBTeam/FTB-Modpack-Issues#6004]
### Modpack

FTB Unstable 1.21

### Modpack version

1.2

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The laser source from Laser Bridges and Doors mod shows up in the EMI, but when left clicking, no recipe shows up. Even if you know the recipe and try to manually craft, it does not work.

### Steps to reproduce

1. Go to EMI and type in "laser source."
2. Try left clicking to view recipe
3. Nothing happens.

### Expected behaviour

Recipe is viewable and item is craftable

**Comment by simonhebich** [comment]
Also uncraftable in FTB Evolution
