### ISSUE TITLE
Crafting recepie tree  Syntetic Favorites not showing for Some items

### ISSUE THREAD

**Issue by Malzbier** [FTBTeam/FTB-Modpack-Issues#6008]
### Modpack

FTB NeoTech

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Mod: 
The Crafting recepie tree function does not generate the "Syntetic Favorites" on some items after Selecting the Crafting recepie tree mode in the crafting tree overlay.

### Steps to reproduce

1. Open inventory (press E) .
2. Click in the EMI search bar.
3. Search for "Steel Boiler".
4. Click on the "Steel Boiler" icon in the Index section on the right side of the screen.
5. Select "View Recepie Tree" on any of the recepies.
6. Click on the magnifyingglass icon besides the "total Cost" text to cange to "Crafting Recepie Tree"
7. Close Tree screen / overlay with the escape key

### Expected behaviour

The Steam Boiler icon Show up on the left side of the Inventory screen in the Favorites section and on its side all the items / components needed to craft the item

### Screenshots

Search bar:
![grafik](https://github.com/user-attachments/assets/ca513661-0b4e-4dc1-acae-a713b6ac52c4)
Items in index:
![grafik](https://github.com/user-attachments/assets/6c919c22-fb49-4961-b0e5-f2756b5c42c8)
Recepie with "View Recepie Tree" buton:
![grafik](https://github.com/user-attachments/assets/fd53e880-672c-4b21-b145-adc11555f211)
Magnifyingglas button before pressing:
![grafik](https://github.com/user-attachments/assets/e6323520-4817-4823-ad28-164b66126d09)
Magnifyingglas button after pressing pressing:
![grafik](https://github.com/user-attachments/assets/25481423-48e7-4cd8-ad60-9c5d5cefd3c9)
EMI Favorites area "with" the missing Steel boliler icons and comonents
![grafik](https://github.com/user-attachments/assets/271406b1-e96f-4e47-a60e-41a965f183e8)
Working example with "Steel Solar Boiler"
![grafik](https://github.com/user-attachments/assets/72c12c7a-4988-4723-a7a4-718403e79ed3)

### Additional information

List of items that exibit the behavior:
Mod Modern Industrialization :
Steel Boiler
Steel Machine Casing
Steel Tank (other material versions work fine)
Steel Rod
Steam Mining Drill
Wrench
Mod: Minecraft :
Iron Sword
Torch
Mod: Actual additions:
Iron AITOT (others materials work fine)
Mod Mekanism : 
Baisc Fluid Tank (Advanced - Ultimate works)

Its all items i crafterd before with the feature but its not working anymore
but its not all items that i craft have the behavior after it.

(nothing aded to the log file ( /logs/debug.log ) when the action is done.

**Comment by Malzbier** [comment]
Seems to be Save / world Specific
In a new Test world on the same modpack instance it works fine...
Not sure what to change / compare to find out what is causing it or what to reset / modiyfy to fix it.

**Comment by Gaz492** [comment]
If you can provide your world, that may help us figure out whats going on.
