### ISSUE TITLE
Copy and Paste Tool vs AE2

### ISSUE THREAD

**Issue by DrLeandrin** [FTBTeam/FTB-Modpack-Issues#6010]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

latest

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

trying to copy a semi complex ae2 build currupted the world.

### Steps to reproduce

1. select de build you wanna copy

### Expected behaviour

not corrupt the save

**Comment by Gaz492** [comment]
Do you have a screenshot of part of your ae2 setup or can you share the world with us so we can best reproduce this?
