### ISSUE TITLE
EvilCraft Blood not recognised by key EvilCraft/Integrated Dynamics blocks

### ISSUE THREAD

**Issue by SolitaryScythe** [FTBTeam/FTB-Modpack-Issues#6011]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Certain EvilCraft and Integrated Dynamics machines including the Purifier, Dark Tank and Mechanical Drying Basin do not accept EvilCraft Blood as a valid fluid and will not accept either manual (via buckets or Blood Extractor) or automated (via Mekanism Basic Tanks and Pipez Fluid Pipes) insertion of it. Notably, this renders the Purifier unusable and removes several mod features as a result. 

### Steps to reproduce

1. Fill a bucket or Blood Extractor with Blood by any usual means (kills, Blood Infuser GUI etc.).
2. Attempt to right-click either item on the affected blocks.

### Expected behaviour

Using a filled Blood container on these blocks should add the contents to the block's fluid tank and in the case of the Purifier show Blood inside the depression similar to water in a vanilla Cauldron.

### Additional information

- Not a dupe of #5814, issue was fixed in 1.2.0 yet seems to have returned worse than ever in 1.3.0. 
- I have not experimented with later devices in the mod - more could be affected as well. 
- It should be noted that the Blood Infuser and manual Drying Basin work as normal and Blood can be inserted into Mekanism fluid tanks. It may or may not be relevant to this issue but Mekanism Pressurized Tubes cannot connect to the affected machines, as if they had no valid fluid inventories. Pipez will at least try to connect to them, to no avail.

**Comment by Raidobw2** [comment]
Seems to work again in 1.4.1
![blood](https://github.com/user-attachments/assets/d81e3522-fe4c-4c29-b141-89940a954f22)

**Comment by Gaz492** [comment]
This has been fixed in the latest version of the pack.
