### ISSUE TITLE
Just Dire Things upgrade dupe

### ISSUE THREAD

**Issue by StoobyMcDooby** [FTBTeam/FTB-Modpack-Issues#6013]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

Allay's will drop duplicate upgrade modules when taking items from you.

### Steps to reproduce

1. Equip any Just Dire Things weapon/armor/item that has upgrades installed in it.
2. Right click an Allay with said item.
3. When the Allay takes the item from you, they will throw all the installed upgrades on the ground.
4. When you right click the Allay to take the item back from them, it will still have the upgrades installed.

### Expected behaviour

I would imagine that if they take your item, it should not be throwing duplicate upgrades on the floor for you to pick up.

### Screenshots

You can use your imagination here

### Additional information

Great mod tho, thanks Dire!

**Comment by Gaz492** [comment]
Duplicate issue of #5991
