### ISSUE TITLE
Archaeologist [Quark: RotN Edition] is tradeable

### ISSUE THREAD

**Issue by bo-jensen** [FTBTeam/FTB-Modpack-Issues#6016]
### Modpack

FTB Interactions Remastered

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The villager Archaeologist [Quark: RotN Edition] is tradeable (not even through [grass](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5738)).

### Steps to reproduce

1. Locate an Archaeologist [Quark: RotN Edition]
2. Right-click to open trade window

### Expected behaviour

Trading window should not open as all villager trading should have been disabled.

### Screenshots

![image](https://github.com/user-attachments/assets/c967b369-5202-4552-99a5-6a0c5347cdcc)
![image](https://github.com/user-attachments/assets/42ec0494-3cd2-41fe-b73f-7f02f29e4344)

**Comment by ArtpokeBr** [comment]
Actually decided to not just entirely disable it, it should still exist, although its generation does not occur anymore.

Also, Archaeologists Hat's now provide a 50% chance to improve the yield of mined ores.
