### ISSUE TITLE
Certus quartz seed bug not fixed yet 

### ISSUE THREAD

**Issue by Nidaelie** [FTBTeam/FTB-Modpack-Issues#6018]
### Modpack

FTB Revelation

### Modpack version

3.7.0

### Launcher

Other...

### Has the pack been modified

No

### Describe the bug

Certus quartz seed... trying to automate with ae2 in a phytogenic issolator and the machine doesnt accept the seeds until u take then and the tag is modified cause the recipe is bugged.

### Steps to reproduce

Craft seeds take them to the machine and it doesnt accept thill u drop to the floor and take them, then the machine accepts them

### Expected behaviour

machine accepting the correct state of the seeds

### Screenshots

Bug reported 2 years ago, a code was posted to reinject to client but modpack files have not been updated

**Comment by Gaz492** [comment]
I have reopened that specific issue and will close this one.
#874
