### ISSUE TITLE
A crash could occur due pneumatic craft loot table

### ISSUE THREAD

**Issue by derry701** [FTBTeam/FTB-Modpack-Issues#6022]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.30

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Server could crash if a pneumatic craft mechanic house is present

### Steps to reproduce

Locate village with pneumatic craft mechanic house

### Expected behaviour

To be able to explore village

### Additional information

Tested pneumatic craft 8.2.2 1.21 and issue has been resolved

**Comment by Gaz492** [comment]
Would you be able to upload the crash logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs/#locating-crashlogs

**Comment by derry701** [comment]
@Gaz492 I have placed the debug log that I reviewed to determine where to look for a fix

Time of issue: 28Oct2024 02:49:31.983

Exception: Non [a-z0-9_.-] character in namespace of location: ResourceKey[minecraft:loot_table / pneumaticcraft:chests/mechanic_house]

[debug-2.log](https://github.com/user-attachments/files/17558456/debug-2.log)

**Comment by Gaz492** [comment]
Perfect, just wanted to double-check that the issue was fixed actually resolved in the latest version of the mod and not just a coincidence.
[](!skip)
