### ISSUE TITLE
Fatal server crash when opening lootr chests near the ocean / underwater

### ISSUE THREAD

**Issue by tokki-rabbit** [FTBTeam/FTB-Modpack-Issues#6023]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.30

### Launcher

CurseForge

### Has the pack been modified

Yes

### Log Files

https://pastebin.com/4VH5ahTZ

### Describe the bug

Fatal server crash when opening lootr chests near the ocean / underwater. Tested with lootr barrels and the crash was not occuring. Only modifications to the modpack was adding simple voice chat.

### Steps to reproduce

1. Open server on 1.30
2. Go to ocean find any sort of structure generating lootr chests in the ocean
3.  Attempt to open chest
4. Server crash / unresponsive

### Expected behaviour

Able to open lootr chests

**Comment by zperk13** [comment]
I think I might've encountered a similar issue a few hours ago. I didn't crash but I'd get a big lag spike whenever I opened Lootr chest/barrel for the first time in the ocean. Subsequent openings of the chest/barrel did not cause issues.
