### ISSUE TITLE
FTB: IR - unable to craft rocket fuel with just Liquid Hydrogen and Liquid Oxygen

### ISSUE THREAD

**Issue by crzyblue** [FTBTeam/FTB-Modpack-Issues#6025]
### Modpack

FTB Interactions Remastered

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Rocket fuel doesn't get made with MV chem reactor, Liquid Hydrogen and Liquid Oxygen.

### Steps to reproduce

Play 1 bucket of Liquid Hydrogen and 1 bucket of Liquid Oxygen in MV chem reactor

### Expected behaviour

Get Rocket Fuel

### Screenshots

![2024-10-29_09 42 11](https://github.com/user-attachments/assets/ac63a0a1-3a9f-48f0-8324-c69644a9b375)
![2024-10-29_09 42 06](https://github.com/user-attachments/assets/710148f8-13d4-4246-a628-35293f1986b0)
![2024-10-29_09 42 07](https://github.com/user-attachments/assets/13284a25-a30b-467f-9b4a-a69930f8f801)

**Comment by ArtpokeBr** [comment]
![image](https://github.com/user-attachments/assets/058da58f-a0f9-40d1-aefb-3c0c8656f4f5)

Weird, it seems to be working in my instance, no issues at all
