### ISSUE TITLE
Stellaris Fuel Refinery not converting Oil into Fuel

### ISSUE THREAD

**Issue by ScoobiousDubious** [FTBTeam/FTB-Modpack-Issues#6030]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Stellaris Fuel Refinery does not turn Oil into Fuel.

### Steps to reproduce

1. Place Bucket of Oil into Fuel Refinery machine
2. Power block with FE
3. Nothing happens

### Expected behaviour

From the Wiki: "If Oil is present in the first tank and if the block is powered, the oil will be transfered into Fuel."

### Screenshots

From the Wiki
![image](https://github.com/user-attachments/assets/8184cf44-2bf3-49b3-b924-b7e9b54278e2)

In Game
![image](https://github.com/user-attachments/assets/9c69ca5e-9b06-4b3a-bac4-8f8ca9549d3e)

**Comment by Raidobw2** [comment]
A possible solution could be to add the following code snippet to the `stellaris.js` script:

```js
// PneumaticCraft Crude Oil to fuel
event.custom({
    "type": "stellaris:fuel_refinery",
    "isFluidMB": true,
    "energy": 10,
    "ingredient": {
        "fluid": "pneumaticcraft:oil",
        "id": "pneumaticcraft:oil",
        "amount": 1
    },
    "result": {
        "fluid": "stellaris:fuel",
        "id": "stellaris:fuel",
        "amount": 1
    }
});

// PneumaticCraft Vegetable Oil to fuel
event.custom({
    "type": "stellaris:fuel_refinery",
    "isFluidMB": true,
    "energy": 10,
    "ingredient": {
        "fluid": "pneumaticcraft:vegetable_oil",
        "id": "pneumaticcraft:vegetable_oil",
        "amount": 1
    },
    "result": {
        "fluid": "stellaris:fuel",
        "id": "stellaris:fuel",
        "amount": 1
    }
});
```

This would convert both PneumaticCraft oils at the same speed as the Stellaris one would have.

![plant_oil](https://github.com/user-attachments/assets/a0799f2b-ba79-4f4e-91ea-8a3fb4dbdb2d)

**Comment by Gaz492** [comment]
This has been fixed in the latest version of the pack
