### ISSUE TITLE
this modpack can`t install

### ISSUE THREAD

**Issue by Nobodycare233** [FTBTeam/FTB-Modpack-Issues#6033]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

this modpack can`t install,look the log is neoforge not have 1.21.1.69,I look the download is not have .69,only have .70

### Describe the bug

neoforge not have 1.21.1.69,but have .70 and .72

### Steps to reproduce

only install new modpack

### Expected behaviour

updata!

**Comment by Gaz492** [comment]
Could you provide more detail about how we can reproduce this issue?
If you have any logs or screenshots that can help explain the issue, feel free to post them.

I am able to install and play the modpack through both the FTB App and CurseForge

**Comment by Nobodycare233** [comment]
sorry,It's my starter problem,Automatic download source selection is not enabled,Just turn on automatic selection of download source.




无人关心
***@***.***


---Original---
From: "Gareth ***@***.***&gt;
Date: Fri, Nov 1, 2024 15:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [FTBTeam/FTB-Modpack-Issues] this modpack can`t install (Issue#6033)




 
Could you provide more detail about how we can reproduce this issue?
 If you have any logs or screenshots that can help explain the issue, feel free to post them.
 
I am able to install and play the modpack through both the FTB App and CurseForge
