### ISSUE TITLE
MV machines can be made before accessing the nether

### ISSUE THREAD

**Issue by Tacete** [FTBTeam/FTB-Modpack-Issues#6036]
### Modpack

FTB Interactions Remastered

### Is your suggestion related to a problem? Please describe.

There are several methods to access a significant amount of both sulfur and aluminum at LV tier in the overworld without going to the nether. Sulfur can be obtained in large amounts from electrolyzing Galena as well as from processing cobaltite while aluminum can be made easily from sapphire electrolysis. I don't know if nether access was intended to gate progression to MV but it feels natural to the pack progression that it is (and I believe access to the quantities of rubber needed to really expand MV infrastructure was not possible in the original version of the pack without access to the sulfur veins in the nether). If the intent was to gate MV behind nether access it certainly doesnt work at the moment.

**Comment by Tacete** [comment]
I guess gallium is the limiter on making MV machines as it is required for the circuits

**Comment by Tacete** [comment]
Reopened because if a MV machine hull is crafted you get several MV tier circuits. This doesnt let you build much more than two machines. Just want to ask if this was intended.

**Comment by ArtpokeBr** [comment]
Yeah, the quest reward for the MV Hull Milestone should give you 4 LV Circuits, no MV ones thanks for the report :)

Just fixed this.
