### ISSUE TITLE
Disconnect with "Failed to encode packet 'clientbound/minecraft:set_equipment'"

### ISSUE THREAD

**Issue by JakeMoe** [FTBTeam/FTB-Modpack-Issues#6037]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[DW20-Logs.zip](https://github.com/user-attachments/files/17594399/DW20-Logs.zip)

### Describe the bug

Client randomly disconnects from server (locally hosted) with error:

Connection Lost

Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_equipment'

### Steps to reproduce

Unknown; it seems to happen randomly, sometimes when I'm idle and not even doing anything

### Expected behaviour

No disconnect

### Screenshots

![01-DW20-Error](https://github.com/user-attachments/assets/1aefcba2-dd4d-47a6-8d61-27a78d044a8c)

### Additional information

Happy to provide more info if required, please let me know

**Comment by Gaz492** [comment]
Would you be able to upload the server logs from when this happens as well?

**Comment by JakeMoe** [comment]
Sure, just debug.log and latest.log?   Will grab them next time it happens and note time.

**Comment by Gaz492** [comment]
> Sure, just debug.log and latest.log? Will grab them next time it happens and note time.

Yep just those 2 logs will be fine

**Comment by JakeMoe** [comment]
Sorry for the delay, I haven't played for a few days.  Happened earlier today while I was idling, logs attached.
[logs.zip](https://github.com/user-attachments/files/17613169/logs.zip)

**Comment by noellerjd** [comment]
Just wanted to say this has been happening to me as well. It seems like this has something to do with either the cosmetic armor or the charms possibly? Just a guess-- happened a lot recently after messing with the talismans, so possibly what could be causing it.

**Comment by JakeMoe** [comment]
@noellerjd  don't believe I've done anything with cosmetic armor, but do have a number of things in my charms / curios slots; wireless crafting terminal, backpack, Emerald Stoneplate Ring (found in chest), Hunter Belt (found in chest), and Simple Magnet's magnet.

**Comment by zperk13** [comment]
I doubt it's the terminal or magnet since I have those and haven't been experiencing this issue

**Comment by JakeMoe** [comment]
@Saereth Cheers for fixing this and #6051 for us.   I'm guessing this will be fixed in the next release?  Will that be 1.3.1, and any idea when that might get released?

**Comment by JakeMoe** [comment]
Heh, nevermind; the new version is out and I see the fixes for these two issues in the changelog.  Thanks for your efforts!

**Comment by theboo** [comment]
Curious how this was fixed? I'm seeing this in another pack and we're pulling out hair out trying to find the cause
