### ISSUE TITLE
[Suggestion]: Quark Matrix Enchanting Table

### ISSUE THREAD

**Issue by sarim** [FTBTeam/FTB-Modpack-Issues#604]
### Modpack

FTB Academy 1.16

### Is your suggestion related to a problem? Please describe.

I've been doing a playthrough in ftb academy to test how suitable it is to recommend to newcomers. Since this modpack is about introducing modded mc world to newcomers, Introducing them to Quark Matrix Enchanting Table would be nice. So prevent shock and surprise, instead of replacing vanilla Enchanting Table, It can be set to not replace vanilla table in config .toml.  

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/quark-oddities

Its already in the pack.

My suggestion is to enable `"Matrix Enchanting" = true`  
then setting this to false
```
#If you set this to false, the vanilla Enchanting Table will no longer automatically convert to the Matrix Enchanting table. You'll have to add a recipe for the Matrix Enchanting Table to make use of this.
"Automatically Convert" = false
```

Then a custom recipe can be added to obtain the `Matrix Enchanting Table`. A misc quest could be added to describe its functions.

**Comment by aaronhowser1** [comment]
Matrix enchanting is taught in University, and I don't feel like it's widely used enough to be needed in Academy.
