### ISSUE TITLE
Building gadgets settings menu will not open

### ISSUE THREAD

**Issue by peisach** [FTBTeam/FTB-Modpack-Issues#6048]
### Modpack

FTB Evolution

### Modpack version

1.0.0

### Launcher

FTB App

### Has the pack been modified

Yes

### Describe the bug

The settings menu for the copy/paste and cut/paste devices from building gadgets 2 will not open.
The only change that I have done with the pack is add distant horizons, but the bug is present whether or not distant horizons is present.

### Steps to reproduce

While holding the copy past tool, hit the "g" key to open the configuration screen and then click on the settings button

### Expected behaviour

the settings should open

### Additional information

https://www.curseforge.com/minecraft/mc-mods/building-gadgets

**Comment by Saereth** [comment]
This is a bug with the mod, reported to direwolf to fix, you can work around this by going into accessibility and turning the blur to 0
