### ISSUE TITLE
[Bug]: Endeavour Forge Outdated Upon Fresh Download

### ISSUE THREAD

**Issue by SophieFox23** [FTBTeam/FTB-Modpack-Issues#605]
### Modpack

Endeavour

### Modpack version

1.8.0

### Log Files

[crash-2022-02-06_22.35.07-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8012246/crash-2022-02-06_22.35.07-fml.txt)

### Describe the bug

The Forge version is out of date and I am not quite sure how to fix

### Steps to reproduce

1.Start modpack
2.crashes

### Expected behaviour

Minecraft stops loading

### Screenshots

![Screenshot (595)](https://user-images.githubusercontent.com/83872862/152723418-4614b35c-1b2e-4242-b1df-06cf568be998.png)

**Comment by Raidobw2** [comment]
A reinstall of the modpack fixed the issue, solved on the FTB Discord.
