### ISSUE TITLE
Crafting station and sophisticated storage crash

### ISSUE THREAD

**Issue by thxace** [FTBTeam/FTB-Modpack-Issues#6053]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

When shift crafting anything in a crafting station with a full inventory while the station is connected to a not full diamond chest, that is filled with more than a standard double chest of items with stack upgrades, that doesnt contain the resulting item the pack crashes to the desktop.

### Steps to reproduce

1. Fill a diamond double chest with random items till it has more stacks than a normal double chest
2. Place a crafting station next to it
3.  Fill your inventory
4. Try shift crafting anything thats not already in the chest
5. Crash

### Expected behaviour

no crash and use the not full chest

### Screenshots

![image](https://github.com/user-attachments/assets/6b0f76b3-a4f1-4619-a5b7-64065dd6ec7e)
![image](https://github.com/user-attachments/assets/6cb3a61b-5dff-4902-85ea-7b9bb8207cea)

### Additional information

It doesnt crash if you have one of the places in the chest empty that you can see while in the crafting station, so it probably is something in the combination of crafting station and sophisticated storage thats causing the crash

**Comment by Saereth** [comment]
please provide your crash report as we need this to track down the issue @thxace

**Comment by thxace** [comment]
[crash-2024-11-05_06.56.22-client.txt](https://github.com/user-attachments/files/17627590/crash-2024-11-05_06.56.22-client.txt)

**Comment by Saereth** [comment]
https://github.com/Leclowndu93150/Crafting-Station-JEI-Edition/issues/1
