### ISSUE TITLE
[Bug]: hydrogen cells and lava cell recipe mismatch in industrial centrifuge

### ISSUE THREAD

**Issue by Tomoyukiryu** [FTBTeam/FTB-Modpack-Issues#606]
### Modpack

FTB Ultimate Reloaded

### Modpack version

1.11.0

### Describe the bug

When I put 16 or more of hydrogen cells from tech reborn into industrial centrifuge  instead of 4 deutrium cell and 12 empty cells I get 18 tin ingot , 4 copper ingot , 1 electrum ingot and 1 small pile of tungsten dust. The recipe in jei is correct,but the output is wrong.

### Steps to reproduce

1. put 16 hydroge  cells(tech reborn) into industrial centrifuge
2. wait for process to end 

### Expected behaviour

industrial centrifuge outputs 12 empty cells and 4 deutrium cell

**Comment by Tomoyukiryu** [comment]
I found temporary fix . Put max 12 cells at one time and the oputput is correct

**Comment by EmmieAndreas** [comment]
> I found temporary fix . Put max 12 cells at one time and the oputput is correct

and how did you do that?
I wanted to automate my fusion but at the moment all cells are buggy(ignoring type of cell), if you give 1 hydrogen cell does calciumcarbonate if you give 16 does the lava one... it means that i must have between 5 and 15 cells inside to do the correct recipe

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
