### ISSUE TITLE
Xp of villager doesn't get stored because of Fargo's Talismans

### ISSUE THREAD

**Issue by cylian914** [FTBTeam/FTB-Modpack-Issues#6062]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

XP level of villager don't go up when trading, this affect both the entity and inside a eazy villager block.

https://github.com/STS15/Fargos-Talismans/pull/31 should fix it, just need to wait.

### Steps to reproduce

1. get a villager with a profession
2. trade

### Expected behaviour

xp level should be stored

**Comment by Robocraft999** [comment]
The mod is updated now
