### ISSUE TITLE
Immersive Engineering Coal Coke Furnace

### ISSUE THREAD

**Issue by DarthVorqes** [FTBTeam/FTB-Modpack-Issues#6063]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The coke oven from immersive engineering will not accept any coal and says it does not have any recipes.  The only item that can go in is a bucket (and I assume anything coded to accept liquid) into oil part of the UI.

### Steps to reproduce

1. Make a coke over from immersive engineering
2. try to put coal in the UI

### Expected behaviour

Coal is suppose to go in an be converted to coal coke and create crescent oil

**Comment by manmaed** [comment]
The only way to make it atm is via Modern Industrialization if this is the way you want it to be maybe disable the resipe for the IE coke oven :)
