### ISSUE TITLE
[Bug]: Joining server crashes my client and server

### ISSUE THREAD

**Issue by Aljeeeks** [FTBTeam/FTB-Modpack-Issues#607]
### Modpack

FTB Infinity Evolved 1.7

### Modpack version

3.1

### Log Files

https://paste.feed-the-beast.com/view/f9b6d479

### Describe the bug

After joing server, the whole server crashes and my client aswell

Normal minecraft is no problem to join any server

### Steps to reproduce

..

### Expected behaviour

Crash

**Comment by Raidobw2** [comment]
Hello, please don't post logs directly in the window. You will ping other people for no reason by pasting a lot of raw text like that (which happened), and it's not easy to read. Use https://paste.feed-the-beast.com/ to upload your logs, and put links here. I've edited your message.

As for the actual problem, make sure you got the modpack and server file from the FTB App and the FTB website respectively. If you have any additional mods, remove them. You can also try to turn off your firewall and join the server, see if that works.

Alternatively, there could be some information in either your client `latest.log` or the server `latest.log`. You could post one or both here as there will likely be context before it crashed, which might help finding the issue if it's not related to network. Use https://paste.feed-the-beast.com/ to post your logs.

**Comment by Raidobw2** [comment]
Did not get feedback from user, assuming that the issue got solved with the above advice. If you encounter similar problems, please create another issue as I will be closing this one currently
