### ISSUE TITLE
Compacting Drawer won't accept items from hoppers or item conduits when initially empty.

### ISSUE THREAD

**Issue by ipaqmaster** [FTBTeam/FTB-Modpack-Issues#6071]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

Prism

### Has the pack been modified

No

### Describe the bug

`Compacting Drawer`s seem to not accept items when empty. I am using one to compress some ice before it enters my network but it seems to not accept items before being given one to start with.

This is problematic as the network can easily extract one blue ice rendering the block empty momentarily making causing ice to get caught in the queue with no valid destination storage.

### Steps to reproduce

Place a Compacting Drawer

Try to pipe items into it. Hoppers and Item Conduits demonstrate this problem well.

### Expected behaviour

Accept items when empty.

**Comment by tiniestfeet** [comment]
I don't think this is a bug, I think this is intended from functional storage.

**Comment by ArtpokeBr** [comment]
This is a Feature from Compact Drawers, so I'll be closing this issue here.

Although, if you feel like it could behave differently, please make sure to open a suggestion [here](https://github.com/Buuz135/FunctionalStorage/issues)
