### ISSUE TITLE
EnderIO crafter gets stuck after a few minutes of crafting halting production lines

### ISSUE THREAD

**Issue by ipaqmaster** [FTBTeam/FTB-Modpack-Issues#6072]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

Prism

### Has the pack been modified

No

### Describe the bug

The EnderIO `crafter` stops crafting a target recipe after only just a few craft operations. There does not seem to be any reason for this to be the case.

This is happening when items are piped into it by EnderIO `item conduit`s.

### Steps to reproduce

1. Place a crafter next to a power source

2. Set a recipe

3. Use item conduit's to pipe something into it

4. Crafter will work initially but eventually just stops within a minute or two.

### Expected behaviour

Continue crafting indefinitely

**Comment by Gaz492** [comment]
Looks like this was an issue with enderio which has now been fixed.
We will update the mod in the next pack update.

https://github.com/Team-EnderIO/EnderIO/issues/844
