### ISSUE TITLE
Mystical Agriculture Seed Duping Disabled

### ISSUE THREAD

**Issue by KittenIsLive** [FTBTeam/FTB-Modpack-Issues#6074]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Mystical Agriculture seeds do not have a chance to drop a duplicate of a seed like the quest book says in the "Mystical Agriculture" and "Understanding Essence Farmland" quests.

### Steps to reproduce

1. Plant mystical agriculture crop on essence farmland
2. Repeatedly grow and harvest the crop
3. No duplicate seeds will be dropped

### Expected behaviour

Mystical Agriculture seeds would have a chance to duplicate

### Additional information

Probably because secondarySeedDrops is set to false in config > mysticalagriculture-common.toml
Either this is intentional and the quest book should be changed, or this isn't intentional and it should be changed to true.

**Comment by alfredggttv** [comment]
It is intentional for them not to drop extra seeds, but I wrote the quest before we had made the decision. I have updated the quest to be accurate now!
