### ISSUE TITLE
Crash With Mob Grinding Utils Spawn Eggs and Productive Bees

### ISSUE THREAD

**Issue by KittenIsLive** [FTBTeam/FTB-Modpack-Issues#6075]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Using a configurable bee spawn egg obtained through Mob Grinding Utils will crash any nearby players.

### Steps to reproduce

1. Use Mob Swab from Mob Grinding Utils on a specialized bee (like a Diamond Bee)
2. Craft the Mob Swab into GM Chicken Feed
3. Feed the GM Chicken Feed to a chicken
4. The chicken will drop a spawn egg named item.productivebees.spawn_egg_configurable_bee
5. Use the spawn egg
6. Any nearby players will crash. If on a server then the server will not crash

### Expected behaviour

Either I get a working bee spawn egg for the bee I swabbed, or the game doesn't let me use the DNA swab on the bee in the first place.

**Comment by manmaed** [comment]
Have tested:
Crash Report: https://pste.me/@luAbk8Cutgo
Debug Log: https://pste.me/@AATlTjn50hg
Latest Log: https://pste.me/@wE1-Cq8eWuY
!skip

**Comment by manmaed** [comment]
this cant be solved by enabling the removeErroringEntities & removeErroringBlockEntities 

!skip
