### ISSUE TITLE
Add compatibility for Just Dire Things and Stellaris ores to Theurgy

### ISSUE THREAD

**Issue by Rithenar** [FTBTeam/FTB-Modpack-Issues#6080]
### Modpack

FTB Presents Direwolf20 1.21

### Is your suggestion related to a problem? Please describe.

Just Dire Things and Stellaris steels are the only 2 ores I have found are not compatible with Theurgy. Theurgy is a decent alternative for early-ish game ore processing

**Comment by ArtpokeBr** [comment]
Please, make sure to open a report about this Theurgy Compat [here](https://github.com/klikli-dev/theurgy/issues) as this might be something that needs to be done on theird side :)
