### ISSUE TITLE
Can't craft Acacia log and apples with MA

### ISSUE THREAD

**Issue by pikojica** [FTBTeam/FTB-Modpack-Issues#6082]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Crafting acacia log with wood essence not possible only able to craft jungle log
Crafting apples with nature essence not possible only able to craft bamboo

### Steps to reproduce

1.see acacia recipe in jei
2.click plus to craft acacia log
3.get to craft jungle log instead of acacia
4.same process for apples

### Expected behaviour

expected to get acacia log and apples

### Screenshots

![Screenshot_178](https://github.com/user-attachments/assets/d960e906-ad9f-46b0-bf1d-64d7ef4867a6)
![Screenshot_179](https://github.com/user-attachments/assets/808a3870-f58e-4a8f-bed4-d16130a29d8a)
![Screenshot_180](https://github.com/user-attachments/assets/8b88f757-312f-4ac5-b7b0-e96af9b4cfb9)
![Screenshot_181](https://github.com/user-attachments/assets/8a4ceeb8-e499-4cc3-a5bd-84a76de908a7)

**Comment by alfredggttv** [comment]
When crafting in a regular crafting table, you can switch between the recipes. The issue seems to be not being able to choose within AE2
