### ISSUE TITLE
Rusty Crate Dupe Bug

### ISSUE THREAD

**Issue by togreglove** [FTBTeam/FTB-Modpack-Issues#6083]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Break a Nautec Rusty Crate with a Nautec Crowbar and receive 2 Rusty Crates. These can be placed to repeat as often as you like for potentially unlimited crates.

### Steps to reproduce

Find or place a Rusty Crate
Break with Crowbar
Receive 2 Rusty Crates

### Expected behaviour

Receive 1 Rusty Crate

**Comment by togreglove** [comment]
It's not just crowbar, breaking it with anything will dupe it.

**Comment by togreglove** [comment]
Additionally, after removing the rust and opening the Crates with the crowbar, they are all empty.

**Comment by Leclowndu93150** [comment]
will fix it.
