### ISSUE TITLE
Opening an Ender IO filter and dragging itself from the inventory over one of its filter slots crashes the server. "Server Closed"

### ISSUE THREAD

**Issue by ipaqmaster** [FTBTeam/FTB-Modpack-Issues#6084]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

Prism

### Has the pack been modified

No

### Describe the bug

It seems Ender IO filter's can have themselves recursively put inside their item filter list. This infinite recursion bug seems to kick all players with "Server Closed" while the server log complains about ticks taking too long.

### Steps to reproduce

1. Acquire the Ender IO `filter` item naturally or with creative mode.
2. With the filter in your hand, right click to open up its editing menu
3. Drag that same filter from your inventory into its own filter slots in the editing menu
4. The server immediately closes with log messages about server ticks taking too long.

### Expected behaviour

Don't let the player's inventory put a filter inside itself

**Comment by ipaqmaster** [comment]
[crash-2024-11-05_13.22.44-server.txt](https://github.com/user-attachments/files/17626189/crash-2024-11-05_13.22.44-server.txt)
[crash-2024-11-05_13.23.45-server.txt](https://github.com/user-attachments/files/17626192/crash-2024-11-05_13.23.45-server.txt)


An upload of each log created by a test server when this were tested.

The first showing the real crash reason: `java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0`

And the second showing the resulting lockup detected by the watchdog: `java.lang.Error: ServerHangWatchdog detected that a single server tick took 60000004.00 seconds (should be max 0.05)`

And then the And then the following

**Comment by leon0399** [comment]
Started experiencing the same issue with FTV Evolution, on a server with 10 Gb of RAM. `60000004.00 seconds` is about ~2 years, which is definitely incorrect
