### ISSUE TITLE
Major TPS/Server Lag Generating Deep Oceans (Seemingly Caused By Lava)

### ISSUE THREAD

**Issue by KittenIsLive** [FTBTeam/FTB-Modpack-Issues#6085]
### Modpack

FTB Evolution

### Modpack version

1.0.3 (Also occurs on 1.2.0 and 1.3.0)

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Generating chunks in the deep ocean has a very high chance of causing immense TPS/server lag due to the ocean generating on top of huge lava lakes.

### Steps to reproduce

1. Go to a deep ocean biome
2. Load a bunch of chunks until you load an area where the ocean floor is lava
3. Server ticks freeze until all the lava processes being turned into obsidian from the ocean

### Expected behaviour

Ocean generates normally without lag

### Screenshots

Picture of ocean floor where lava was turned into obsidian: https://imgur.com/a/6kBh2wC

**Comment by Saereth** [comment]
have some improvemnents coming for this in 1.2, let us know how it works out for you

**Comment by Geariko17** [comment]
Not sure if this is any help since this was posted by a different user, but I have also been having this issue and since the ver 1.2.0 update I have seen little to no improvement on this while playing on a private multiplayer server with a friend. It got so bad we ended up teleporting back to spawn and just avoiding deep oceans due to the chunks never loading.

**Comment by Vort3xGameStudios** [comment]
Same here, Super poor server performance when loading chunks in the ocean to the point where it crashes the server. Have had to steer away from any large bodies of water.

**Comment by KittenIsLive** [comment]
Issue is still happening in 1.2.0.

**Comment by KittenIsLive** [comment]
Still happening in 1.3.0.

**Comment by Saereth** [comment]
Can any of you provide a world download in a googeldrive link or something with coordinates where this is happening? I am having trouble reproducing this on a fresh world and it would help.

**Comment by Vort3xGameStudios** [comment]
https://drive.google.com/drive/folders/1H6OL61mZ3ivvjXW7IW-2p1p-3JrDTyDh?usp=sharing

https://drive.google.com/file/d/1sc1YfzATXaNXUsj6kKKLcKwod0voFo7J/view?usp=sharing (Map, red circles are regions that have already been generated *painfully* but the coordinates w instructions below should be close to ungenerated chunks

-1296 2445 (make sure the chunks havent been already loaded, would recommend picking a direction either South or West and just load new chunks in the deep ocean)

-305 1385 (go west further into the deep ocean)
250 -15777 (north)
1523 -1752 (north or west)

**Comment by leon0399** [comment]
Can this somehow be related to `A single server tick has taken 40001, more than 40000 milliseconds`? Also seems to happen during ocean generation.

Relevant logs: https://mclo.gs/dgqWxIY

**Comment by Vort3xGameStudios** [comment]
Most likely if you are trying to generate a lot of the deep ocean chunks and its bad enough that it crashes the server. For me it sometimes crashes the server if I try to generate too many, sometime itll kick my client out of the game, then sometimes itll just lag for a bit then recover if I dont load too many at one time. When I look at the console it says someone along the line of the server is behind XXXX ticks etc.

**Comment by KittenIsLive** [comment]
Issue still happens in 1.4.1
Seed: -8074861022765217629
X: -859
Z: -369

**Comment by KittenIsLive** [comment]
Both infinity caves version 0.61 and infinity caves 0.7 are included in the install for FTB Evolution, and the game is preferring to use 0.61 over 0.7, causing the issue to stay even though the mod update fixes part of the issue. Version 0.61 of infinity caves should probably be removed from the modpack and the issue will be mostly resolved.

**Comment by KittenIsLive** [comment]
Issue fixed in 1.5.0 due to Infinity Caves v0.7

**Comment by KittenIsLive** [comment]
Issue fixed in 1.5.0 due to Infinity Caves v0.7
