### ISSUE TITLE
Nitro Seed and Nitro Crux recipe missing

### ISSUE THREAD

**Issue by togreglove** [FTBTeam/FTB-Modpack-Issues#6091]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Quest for Nitro Seeds requires you to get (I assume craft) nitro seeds, but there is no recipe for it.
Similarly for the Nitro Crux
I may have missed a quest that just gives you the seeds and/or crux, but since it's not even listed in JEI, I'm thinking it was omitted.

### Steps to reproduce

Left click Nitro Seeds in the quest turn in, have nothing pop up.
Look up Nitro Seeds in JEI and find nothing.
Same for Crux

### Expected behaviour

Should be able to find recipes and craft the quest items.

**Comment by alfredggttv** [comment]
Removed the quest, nitro seeds aren't obtainable currently.
