### ISSUE TITLE
Continuous error in terminal - Evolution server

### ISSUE THREAD

**Issue by sanomi78** [FTBTeam/FTB-Modpack-Issues#6092]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

Server

### Has the pack been modified

No

### Log Files

https://gist.githubusercontent.com/FTBAuto/2ee24496898e9ee80fda209b1f8c48a6/raw/13e8d7d283e52a2c97582c0ca34992b0f4ee7565/message.txt

### Describe the bug

The server starts and works (you can connect), but this specific error keeps spamming the terminal

### Steps to reproduce

Start server

### Expected behaviour

The error not showing continuously.

**Comment by sanomi78** [comment]
I'using Debian/CasaOS/Crafty and i'm starting the server with:

java -javaagent:log4jfix/Log4jPatcher-1.0.0.jar -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx10240M -Xms4096M @user_jvm_args.txt @libraries/net/neoforged/neoforge/21.1.72/unix_args.txt nogui

**Comment by sanomi78** [comment]
I just installed - from scratch - the new version 1.2.0 of the server and the same error is still happening and flooding the terminal and the logs

**Comment by Saereth** [comment]
this should be fixed in 1.3.0
