### ISSUE TITLE
Torchflowers grow incorrectly

### ISSUE THREAD

**Issue by CraMagicka** [FTBTeam/FTB-Modpack-Issues#6094]
### Modpack

FTB Evolution

### Modpack version

1.0.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

When I grow torchflower seeds, they grow into some other random flower? This stops me progressing in Occultism.

### Steps to reproduce

1. Get torchflower seeds
2. Plant them on farmland
3. Bonemeal the seeds
4. Witness a random flower

### Expected behaviour

A torchflower to grow

**Comment by Kezzar** [comment]
This seems to be directly related to bonemealing them to get to 100%.  Letting it grow naturally caused it to grow normally, at least with the one I tried.

Also of note, the one I did bonemeal also caused a few other flowers to sprout nearby, and they were notably all flowers from the Sniffer's digging pool.

**Comment by ArtpokeBr** [comment]
sorry for the accidental labeling of this issue, but indeed this is so odd, can confirm that the torchflower crop doesn't like bonemealing O.o
