### ISSUE TITLE
Mod replacement (Ars Delight)

### ISSUE THREAD

**Issue by Irritated-Badger** [FTBTeam/FTB-Modpack-Issues#6096]
### Modpack

FTB Evolution

### Is your suggestion related to a problem? Please describe.

Replacing a mcreator mod with a well made mod.

### Mod suggestion

Ars Delight should be replaced with Ars Nouveau's Flavors and Delight. 

Reasons:
1. Ars Delight is a poorly made MCreator mod
2. Ars Flavors and Delight has better integration with both mods, isn't MCreator slop, has more and better content, and is just an all around better mod.

https://www.curseforge.com/minecraft/mc-mods/ars-nouveaus-flavors-delight

**Comment by alfredggttv** [comment]
Added in the next update. Thanks!
