### ISSUE TITLE
Bug to get 1,000,000 Health on all nearby players

### ISSUE THREAD

**Issue by CraMagicka** [FTBTeam/FTB-Modpack-Issues#6098]
### Modpack

FTB Evolution

### Modpack version

1.0.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[2024-11-06-1.log](https://github.com/user-attachments/files/17640399/2024-11-06-1.log)

### Describe the bug

Playing on a server with friends. One brought back a spawner from the End, with skeletons with higher health. Upon casting the Iron's spell 'Lob Creeper' at them, one or more of us usually crashes. Upon re-entering the game, we come back with a much higher health count. I have attached the log files of the server as we tried this out. I think the mobs may have also gained health so perhaps it is a spillover effect that makes them more powerful?

### Steps to reproduce

1. gather together some powerful spawned mobs
2. cast lob creeper at them
3. crash out the server
4. reconnect
5. See max health exponentially increased

### Expected behaviour

My health to not become higher and higher

**Comment by alfredggttv** [comment]
This is actually a bug due to our mob scaling script that was also affecting players. this is fixed in next update
