### ISSUE TITLE
LittleTiles (non)rendering issues

### ISSUE THREAD

**Issue by digitalseraphim** [FTBTeam/FTB-Modpack-Issues#6099]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The "Little Workbench" has an icon, but doesn't render in world, and any attempt to place down "bits" doesn't render, but if I can find them, there's a hitbox, and I can break them.

### Steps to reproduce

grab the workbench and place it
grab some cobble and the chisel, configure the chisel to place the cobble, and try to place.

### Expected behaviour

Visible workbench and bits

### Screenshots

![2024-11-05_22 00 02](https://github.com/user-attachments/assets/2076690d-c7eb-48a6-8c33-679ae85e62a5)

### Additional information

running /lt-optimize is saying that there are 3 blocks, but I have no idea where they are.

**Comment by Gaz492** [comment]
This looks to be a compatibility issue when sodium is installed, the mod author is looking into this, but at the moment, the only solution looks to be to disable sodium.

https://github.com/CreativeMD/LittleTiles/issues/1027
