### ISSUE TITLE
[Bug]: Mahou Tsukai Attuned Diamond won't store Mahou Mana

### ISSUE THREAD

**Issue by LucienOliveira** [FTBTeam/FTB-Modpack-Issues#610]
### Modpack

FTB University 1.16

### Modpack version

1.4.0

### Describe the bug

I can't play Mahou Tsukai because my Attuned Diamond wont store the Mahou mana it will use up my Mahou but wont store it in the attuned diamond

### Steps to reproduce

1. Unlock Mahou mana
2. Get a Attuned diamond
3. Use the Attuned diamond

### Expected behaviour

When i right click the Attuned diamond it should store the used Mahou 

### Additional information

Im playing on a server and doing further research I am able to store the Mahou in the Attuned Diamond in a singleplayer world

**Comment by Co-Bolt** [comment]
I've noticed this same issue as well. However, I found out that it actually does store the mana, it just doesn't display the amount in the attuned diamond/emerald.
Another thing to note is that this bug only happens in multiplayer, and it shows the amount of stored mana in singleplayer without issue.

**Comment by Co-Bolt** [comment]
Also if it's any help, the Mahou Tsukai dev is aware of this issue, and they think it's a conflict issue with the Epic Fight mod:
https://github.com/Yesssssman/epicfightmod/issues/857
