### ISSUE TITLE
[FTB Evolution] Villager Trade EXP and Levels Reset Per Trade

### ISSUE THREAD

**Issue by Whyareuhere** [FTBTeam/FTB-Modpack-Issues#6100]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Whenever trading with a villager, the villager gains EXP and even levels up. However, upon exiting the menu, you will notice that the villager EXP and levels have all reset to zero.

This means that it is impossible to obtain anything other than the lowest level items from the villagers.

Testing has revealed that this behavior occurs both with the Easy Villagers Trader as well as spawning and trading with villagers in the world (outside the Trader block).

### Steps to reproduce

1. Trade with villager (any villager trading works). This should accumulate some EXP.
2. Close out of villager trading menu
3. Open villager trading menu again

### Expected behaviour

Villager trading should have villagers gain EXP and keep their levels for higher tier trading.

**Comment by alfredggttv** [comment]
Testing this in the latest update. Can't replicate, so I'm guessing a mod update fixed it.
