### ISSUE TITLE
Unable to Insert Coal in Immersive Engineering Coke Oven

### ISSUE THREAD

**Issue by Volpamonhub** [FTBTeam/FTB-Modpack-Issues#6102]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The coke oven from Immersive Engineering isn’t working. It can be crafted, but once created with the hammer, it’s impossible to insert coal or charcoal into it. It doesn’t even have an associated recipe.

### Steps to reproduce

1. Craft the 27 coke bricks
2. Assemble them in a 3x3x3 structure
3. Right-click the center with the hammer
4. Open the Coke Oven GUI and observe that nothing can be inserted, and it’s not possible to view recipes by clicking on the coal icon.

### Expected behaviour

The expected outcome is to be able to insert coal to convert it into coke and creosote.

**Comment by alfredggttv** [comment]
Tested in the dev version. Building the structure allows me to place in coal and I can see the recipes. Will need to test to see if it is fixed in the next version of the pack!

**Comment by dadozito-cloud** [comment]
It's not completed I'm having the same issue
