### ISSUE TITLE
Cannot put the AE2 "Network Tool" into the AE2 network storage using a Terminal (Clicking does nothing)

### ISSUE THREAD

**Issue by ipaqmaster** [FTBTeam/FTB-Modpack-Issues#6103]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

Prism

### Has the pack been modified

No

### Describe the bug

I cannot seem to put AE2's Network Tool into my storage using the Wireless Crafting Terminal of the same mod. This also seems to be true when using the ME Crafting Terminal.

If I throw the Network Tool at an annihilation plane, that works.

### Steps to reproduce

1. Create or spawn in an AE2 storage network and a Wireless Crafting Terminal, or just use a normal ME Crafting Terminal
2. Attempt to insert the "Network Tool" into the network using either interface.

### Expected behaviour

Let me store the tool in the mod's own storage

**Comment by Raidobw2** [comment]
I think that might be intended from the mod author. If you put some upgrades in the network tool as shown below:
![image](https://github.com/user-attachments/assets/61674e0d-c1ed-48d4-9253-b0f56954268a)

Then other machines/GUIs from the same mod will integrate a portion of the UI for that tool's contents, no matter its position in your inventory.
![image](https://github.com/user-attachments/assets/abcca1bc-42ce-4519-adaa-45daddfb0ffb)

I could see this be mostly useful for upgrading your AE2 infrastructure quickly, such as upgrades in a Molecular Assembler!

![image](https://github.com/user-attachments/assets/e823f2d0-3588-4d7c-81ef-81cdd52ca85b)

**Comment by ArtpokeBr** [comment]
Closed as this seems to indeed be a feature, but if you feel like its a bug or would like to suggest the addition of this possibility, please make sure to open a ticket at their issue tracker [here](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues)
