### ISSUE TITLE
FTB Ultimine Issues

### ISSUE THREAD

**Issue by TheLoneDude** [FTBTeam/FTB-Modpack-Issues#6105]
### Modpack

FTB Evolution

### Modpack version

1.0.3

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

FTB Ultimine remains at 16 blocks maximum per use despite having Mining Upgrades increasing the maximum.

### Steps to reproduce

1. Have FTB Ultimine upgrades within the skill tree.
2. Attempt to use FTB Ultimine on blocks.

### Expected behaviour

It should attempt to mine the maximum amount of blocks available up to the maximum amount.

### Screenshots

![Screenshot (284)](https://github.com/user-attachments/assets/d69c7187-a565-4edf-8248-d0e59693a4a7)
![Screenshot (285)](https://github.com/user-attachments/assets/1a80be7b-135c-4111-a6a3-b3a07f4ddeef)

### Additional information

I believe when I originally got the upgrades, that it was mining the maximum amount (though I've been away for a while so I can't recall completely). When I relaunched the game today, this is what was occurring. (I don't know if a report is made about this already, so if there is, apologies.)

**Comment by TheLoneDude** [comment]
Additional Note: This issue is fixed when editing the config in the world folder, though follows the number entered as the max rather than the upgrade tier someone has. I tested via the defaultconfig folder as well and this did not work.

**Comment by alfredggttv** [comment]
This is currently a bug with the mod itself, and we're taking a look at it!

**Comment by alfredggttv** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6059

**Comment by Saereth** [comment]
closing due to duplicate
