### ISSUE TITLE
Game crash near minecolonies village

### ISSUE THREAD

**Issue by nik7007** [FTBTeam/FTB-Modpack-Issues#6109]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[crash-2024-11-07_19.30.59-server.txt](https://github.com/user-attachments/files/17667940/crash-2024-11-07_19.30.59-server.txt)

### Describe the bug

When I am near to my minecolonies village, the game crashes. Downgrade to 1.3.0, and everything works fine.

### Steps to reproduce

1. Open the world
2. Fly to the village
3. As soon as the village starts to load, the game crashes

### Expected behaviour

The game does not crash

**Comment by Gaz492** [comment]
As a temporary fix until we get this resolved, try disabling the mod `moonrise`
[](!skip)

**Comment by nik7007** [comment]
Without the mod moonrise the game seems to work fine, thanks!

**Comment by derry701** [comment]
Ran into this issue as well and removing moonrise fixed my issue as well.

**Comment by ArtpokeBr** [comment]
Moonrise have been removed from the Pack, so should be fixed :)
