### ISSUE TITLE
"Railcraft Reborn" steel doesn't have any usage.

### ISSUE THREAD

**Issue by Zizes** [FTBTeam/FTB-Modpack-Issues#6111]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Steel from "Railcraft Reborn" doesn't have any useful recipe, but can be bought by trade with villager "Toolsmith"
![ToolSmith - Trade](https://github.com/user-attachments/assets/5e46702a-a59a-452a-95b9-aae8f32815dd)

### Steps to reproduce

How to obtain "Railcraft Reborn" steel:
1. Create "Trader" from "Easy Villagers"
2. Find any villager
3. Create "Smithing Table"
4. Place "Smithing Table" and villager in "Trader"
5. Choose any trade and upgrade villager trading level (3 of 3 attempts got trade for steel from "Railcraft Reborn")
6. Buy "Railcraft Reborn" steel.
7. Check that it can't be used in any useful recipe r way to convert to "Mekanism" steel.

### Expected behaviour

Steel from "Railcraft Reborn" should be usable and convertible to steel from "Mekanism"

### Screenshots

![ToolSmith - Trade](https://github.com/user-attachments/assets/335310c5-7a50-4a7d-a31f-d0141420ac36)
![Railcraft Reborn Steel](https://github.com/user-attachments/assets/b49c5186-3f39-4c93-991f-e7953ab6fe99)

**Comment by Raidobw2** [comment]
Villager trades for RailCraft are embedded within the mod (https://github.com/railcraft-reborn/railcraft/blob/15d8424f960d1ad46041ffdf30a544466936efee/src/main/java/mods/railcraft/world/entity/npc/RailcraftVillagerTrades.java#L100), so a mod like "MoreJS" might be needed to modify this at the root.

Removing the two entries of `'railcraft:steel_ingot'` from the `global.js` might be a simpler solution to this.

This would allow "AlmostUnified" to unify the steel ingots and will automatically hide the RailCraft one and remove any item id based recipes, but keep those with the steel tag.

-> What I mean by this is that the RailCraft ingot will have 0 uses item id wise.

-> Tag wise it will be marked as steel, therefore this happens:

![image](https://github.com/user-attachments/assets/68b597f5-8f9b-4593-95df-488e100b6e88)
![image](https://github.com/user-attachments/assets/399fea3d-60e3-47d2-93c8-3a923a4ad8bb)
![image](https://github.com/user-attachments/assets/b750b8d8-8f33-48d2-86be-b246e73cd25c)

This keeps the Mekanism steel ingot as the primary steel ingot but allows the RailCraft one to still be used in recipes in case someone were to obtain some.

A consequence of this is that two ingots will show in the steel tag in steel-based recipes:
![image](https://github.com/user-attachments/assets/b6064fc2-aaf7-4c3e-9ce0-f49abf3f0f90)
