### ISSUE TITLE
Evolution Fails to launch

### ISSUE THREAD

**Issue by quigzerz** [FTBTeam/FTB-Modpack-Issues#6115]
### Modpack

FTB Evolution

### Modpack version

1.1.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

NeoForge was not updated correctly with the rest of the pack and as a result the pack will not load or function.

### Steps to reproduce

1. Run Evolution on version 1.1.0

### Expected behaviour

The game to be playable

**Comment by manmaed** [comment]
!skip
![https://ss.manmaed.net/1731032038.png](https://ss.manmaed.net/1731032038.png)

**Comment by ttechr** [comment]
Same issue on Server and Client.

**Comment by ttechr** [comment]
#6114

**Comment by MrFrequency** [comment]
Exactly the same issue: Neoforge's version is obviously not the right one.
