### ISSUE TITLE
Glassential Glass not walk-through able now in 1.4

### ISSUE THREAD

**Issue by RedDamer** [FTBTeam/FTB-Modpack-Issues#6116]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

After updating my pack to the 1.4 that came out today, I can no longer walk in to my two mob farm areas, where I was using Ethereal Glass from the "Glassential-renewed" mod. I even broke and replaced, and even crafted new glass to see, but I am now unable to pass through as of today.

### Steps to reproduce

1. Place down a wall of Glassentials-renewed Ethereal Glass
2. Try and walk through it.
3. Get stuck and don't pass through it.

### Expected behaviour

Glass should be non-solid to players.

### Screenshots

![2024-11-07_19 57 35](https://github.com/user-attachments/assets/e7af9f7c-116c-480f-b13d-5ebcfb531451)

**Comment by zperk13** [comment]
I'm getting the same issue. Possibly related, JustDireThings phase ability isn't working either

**Comment by zperk13** [comment]
Also Reverse Ethereal Glass blocks you like it should, but it's very jittery unlike before. Mobs go through it just fine though (as they should) though which is interesting

**Comment by RedDamer** [comment]
Glassential ethereal glass is no longer solid in the 1.4.1 version. Moonrise mod might've been the culprit?

**Comment by Raidobw2** [comment]
Yeah 1.4.1 I can walk in the block fine. I also think it was the Moonrise mod

**Comment by zperk13** [comment]
1.4.1, Phase is also working, yay!

**Comment by ArtpokeBr** [comment]
Yup, Moonrise got removed a while a go thankfully, so closing this issue ;)
