### ISSUE TITLE
Ender IO Fused Quartz (Not solid to players) Is now solid to players (1.4.0 from 1.3.0)

### ISSUE THREAD

**Issue by ipaqmaster** [FTBTeam/FTB-Modpack-Issues#6117]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.0

### Launcher

Prism

### Has the pack been modified

No

### Describe the bug

Ender IO Fused Quartz (Not solid to players) Is now solid to players after upgrading from 1.3.0 to 1.4.0 even after re-placing.

### Steps to reproduce

1. Place some Ender IO Fused Quartz (Not solid to players) which has been specially crafted to be not solid to players
2. Experience this block as a solid

### Expected behaviour

Being able to walk through the block

**Comment by RedDamer** [comment]
Ooh I just made a similar bug earlier tonight about the Glassentials glass doing the same thing

**Comment by ipaqmaster** [comment]
I ended up seeing that too. Something common must have failed here.

**Comment by RedDamer** [comment]
Just updated to 1.4.1, where the Moonrise mod was removed, and the glass seems to have fixed itself.

**Comment by ArtpokeBr** [comment]
yes, this have been fixed with the removal of Moonrise a while ago, so I'll be closing this issue! :)
