### ISSUE TITLE
[Bug]: OceanBlock, The power pot takes up the network IO a little bit seriously

### ISSUE THREAD

**Issue by KuroPeach** [FTBTeam/FTB-Modpack-Issues#612]
### Modpack

FTB OceanBlock

### Modpack version

1.1.0

### Describe the bug

The power pot takes up the network IO a little bit seriously.
I used 2 groups of four-level, the network IO reached 1.6M/s after power-on

![$YA@)14PS6V(K@4073JP3PU](https://user-images.githubusercontent.com/19620848/153621374-105badd2-7d4c-45d6-9d15-d01900cf0e32.png)

### Steps to reproduce

no

### Expected behaviour

no

**Comment by Raidobw2** [comment]
Thanks for the report, although this is already listed at #569. We'll keep only the other issue to keep track of this problem.
