### ISSUE TITLE
Block and item atlases broken

### ISSUE THREAD

**Issue by ZestyBlaze** [FTBTeam/FTB-Modpack-Issues#6120]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.0

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

https://mystb.in/f2a3dc104b7cb61f4f

### Describe the bug

Was playing through the pack, ran into a bed in the village and the entire block atlas broke causing no blocks or items to have textures. Persists on world reload so world is now unplayable

### Steps to reproduce

1. Go to a get in a village
2. Run into the bed
3. As you run into it, go to sleep
4. That's what I did to cause it, not sure if I can recreate it

### Expected behaviour

I actually have block and items textures

### Screenshots

![2024-11-08_15 11 50](https://github.com/user-attachments/assets/4257734c-e9cb-4149-93f6-1b462fe8a697)
![2024-11-08_15 12 34](https://github.com/user-attachments/assets/ba4b7e74-db55-4e77-bda0-1e9212806ca8)

**Comment by ArtpokeBr** [comment]
In my Dev Instance this doesn not seem to be happening anymore, and since this issue is from a old version gonna be closing the issue.

Please, if this still persists, make sure to reopen it again.
