### ISSUE TITLE
1.1 Update character inventory screen not showing tooltips

### ISSUE THREAD

**Issue by Volt-the-Insane** [FTBTeam/FTB-Modpack-Issues#6121]
### Modpack

FTB Evolution

### Modpack version

1.1.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

1.1 Update character inventory screen not showing tooltips when mousing over an item. when inside a chest or ME system or backpack the tooltips do show.

### Steps to reproduce

1. "E" 
2. Mouse over any item
3. nothing shows in tooltip upon mousing over

### Expected behaviour

a tooltip to show up.

### Screenshots

![image](https://github.com/user-attachments/assets/ffee6a7a-8f96-4fb6-8c56-c5d98f4ed1d7)

**Comment by Volt-the-Insane** [comment]
![image](https://github.com/user-attachments/assets/0df169bf-d778-4f2a-bc6c-e82fe8712e00)

**Comment by JakeThatDog** [comment]
I'm also having this exact same issue, A good temporary fix for now I'd recommend the curios menu since you can use full inv inside it

**Comment by alfredggttv** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6118

**Comment by Saereth** [comment]
duplicate issue
