### ISSUE TITLE
Cannot use my world folder. Server crashes. 

### ISSUE THREAD

**Issue by CraMagicka** [FTBTeam/FTB-Modpack-Issues#6123]
### Modpack

FTB Evolution

### Modpack version

1.1.1

### Launcher

Server

### Has the pack been modified

No

### Log Files

[crash-2024-11-08_16.27.10-server.txt](https://github.com/user-attachments/files/17681425/crash-2024-11-08_16.27.10-server.txt)

### Describe the bug

Tried to update my server from 1.0.0 to 1.1.1, this had 313 files fail. Used the install again, 0 files fail but the server failed to load.
I then installed a clean version of the server files for 1.1.1, this worked with a new world. However, removing this world and adding my world from 1.0.0 seems to make the server crash. 
I have now also tried it with 1.0.0 server install and this is failing now too. 
Please help!

### Steps to reproduce

1. Try to update a server to 1.1.1
2. Try to move my world folder to a new server install
3. Failure!

### Expected behaviour

Be able to run my server in 1.1.1

**Comment by alfredggttv** [comment]
This might be due to the Moonlight mod on the server, not the world. Try removing this file in the mods to see if it runs:
`Moonrise-NeoForge-0.1.0-beta.8+68ea18b.jar`

**Comment by CraMagicka** [comment]
Yes thank you, that worked! I've just seen you already submitted this too, I should have checked this first! Sorry about that.
