### ISSUE TITLE
Cursing diamonds in mek gives mek diamond dust

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Modpack-Issues#6124]
### Modpack

FTB Evolution

### Modpack version

1.1.1

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

N/A

### Describe the bug

mek Crusher makes mek dimond dust and not ftb mats one

### Steps to reproduce

see disc

### Expected behaviour

to be able to get dimond dust dust

**Comment by Tabbsen** [comment]
Same with Obsidian
