### ISSUE TITLE
Crash report says Husk.

### ISSUE THREAD

**Issue by squillis** [FTBTeam/FTB-Modpack-Issues#6125]
### Modpack

FTB Evolution

### Modpack version

1.1.1

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

https://mclo.gs/r05bkKB
https://mclo.gs/GOKavNi
https://mclo.gs/0tRHxMr

### Describe the bug

So my game keeps crashing, it says it's a husk, I'm trying to explore a dungeon arise dungeon.

### Steps to reproduce

log into game (singleplayer) crash...

### Expected behaviour

Not crash.

**Comment by Saereth** [comment]
fixed in next update by removing moonrise
