### ISSUE TITLE
Entering the bumblezone causes disconnect

### ISSUE THREAD

**Issue by N1co22** [FTBTeam/FTB-Modpack-Issues#6127]
### Modpack

FTB Evolution

### Modpack version

1.1.1

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

https://pastebin.com/01LWdpuB

### Describe the bug

Entering the bumblezone disconnects you from the server with a network protocol error

### Steps to reproduce

1. Enter the bumblezone
2. Get disconnected

### Expected behaviour

Dont get disconnected when entering the bumblezone

### Additional information

First tried to enter the bumblezone via waystone. Got disconnected and when trying to reconnect got stuck in a loop, because the game wanted to put me in the bumblezone. Only way to escape was by teleporting to a friend via commands. Entering the bumblezone by teleporting in a beehive with an ender pearl resulted in the same error. Even deleting the bumlezone world folder had no effect.

**Comment by Saereth** [comment]
moonrise bug,will be fixed in 1.2
