### ISSUE TITLE
Simple Magnets Crash

### ISSUE THREAD

**Issue by KittenIsLive** [FTBTeam/FTB-Modpack-Issues#6134]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

Crash Report 1: https://mclo.gs/jeab7nT
Crash Report 2: https://mclo.gs/2DzR3KO

### Describe the bug

Simple Magnets mod's Advanced Magnet GUI is crashing the game.

### Steps to reproduce

1. Get a Advanced Magnet
2. Open the GUI (you may just crash here)
3. Put items in/out of the filter

### Expected behaviour

GUi works and doesn't crash the game

### Additional information

Crash Report 1 is from changing items in the filter, Crash Report 2 is from just opening menu. This issue did not happen in 1.0.3

**Comment by Sovietsupporter69** [comment]
I can confirm this bug, tho it seems to just crash as soon as I open the GUI. Also I had a different crash reason for mine;
[latest.log](https://github.com/user-attachments/files/17685549/latest.log)
That's the latest.log that contains the bug repo at the bottom (seems to be trying to reference a non-existant config)
