### ISSUE TITLE
Direwolf20 1.21 always segfaults (SIGSEGV) on exit rather than just exiting

### ISSUE THREAD

**Issue by ipaqmaster** [FTBTeam/FTB-Modpack-Issues#6135]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.0 (Impacts all)

### Launcher

Prism

### Has the pack been modified

Yes

### Log Files

See below comment

### Describe the bug

On all versions of Direwolf 20 1.21 exiting the game in any way (Via its exit button or with the X in the corner of the window manager) runs into a segfault (SIGSEGV) and coredumps consuming a lot of memory.

Of the many packs I have played over the years this is the first to do this consistently every exit this past month or so.

### Steps to reproduce

Exit Direwolf20 1.21, any version

### Expected behaviour

Exit normally

**Comment by ipaqmaster** [comment]
```
[13:14:34] [Render thread/INFO] [minecraft/Minecraft]: Stopping!
[13:14:35] [Render thread/INFO] [FTB Chunks/]: Shutting down map thread
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000745d11a96a40, pid=68705, tid=68727
#
# JRE version: OpenJDK Runtime Environment (21.0.5+11) (build 21.0.5+11)
# Java VM: OpenJDK 64-Bit Server VM (21.0.5+11, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x3f891]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/me/.local/share/PrismLauncher/instances/FTB Presents Direwolf20 1.21/.minecraft/core.68705)
#
# An error report file with more information is saved as:
# /home/me/.local/share/PrismLauncher/instances/FTB Presents Direwolf20 1.21/.minecraft/hs_err_pid68705.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Process was killed by user.
```

**Comment by ipaqmaster** [comment]
[hs_err_pid68705.log](https://github.com/user-attachments/files/17685629/hs_err_pid68705.log)

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Added 'FTB Presents Direwolf20 1.21' to the modpack options and modified the version field to allow reporting impacts across all versions.

I also created pull request: https://github.com/FTBTeam/FTB-Modpack-Issues/pull/6136


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by ipaqmaster** [comment]
Found the problem. It was a client-side mod I added for accessibility which is known to be broken in 1.3.0 and 1.4.0 of this pack. I should have just removed it after it started spitting up errors weeks ago.

Issue resolved.
