### ISSUE TITLE
There no Powah bees except Uraninite

### ISSUE THREAD

**Issue by Alolag** [FTBTeam/FTB-Modpack-Issues#6139]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

There no Powah bees except Uraninite. There are bees for all powah resource: Energized Steel, Blazing Crystall, Niotic Crystal, Spirited Crystal, Nitro Crystal. I don't know if it on purpose or not, because there is has recept for get this from combs, but there not combs. Some examples:
![image](https://github.com/user-attachments/assets/a4b57742-e05f-48bb-919b-711a72ab5f59)
![image](https://github.com/user-attachments/assets/a445924a-e89f-43a8-90b9-87757fe255cf)
![image](https://github.com/user-attachments/assets/95b9ac46-81e2-41c7-bcb9-cdfa6439c3ff)

### Steps to reproduce

There're not powah bees:

1. Open JEI
2. Write in searchbar: `powah`
3. There are only Guide and Uraninite bee

Broken recepts:

1. Open JEI
2. Write in Searchbar: `@powah`
3. Click on Powah recource: Energized Steell and others
4. Go to the tab `Heated Centrifuge` or `Centrifuge` of Productive Bees
5. There're not input for combs or comb blocks (comb block is empty, it had not bee type)

### Expected behaviour

There are recepts for bees to generate powah resource or removed broken recepts.

**Comment by Alolag** [comment]
Another examples:
- Refind Obsidian Dust

**Comment by alfredggttv** [comment]
For the most part, anything that requires machines or power to craft do not have seeds or bees. This is intentional. I'll see about hiding the combs as well!
