### ISSUE TITLE
[Bug]: Loading World

### ISSUE THREAD

**Issue by BurnThemTacos** [FTBTeam/FTB-Modpack-Issues#614]
### Modpack

SkyFactory 3

### Modpack version

1.10.2

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8052269/latest.log)

### Describe the bug

When I reach the menu, I can go into SinglePlayer, but whenever I click on a world or try to make a new one, it's stuck on "Loading World"

### Steps to reproduce

1. Load into SkyFactory 3
2. Go to SinglePlayer
3. Load into a world or create a new one

### Expected behaviour

I expected the world to load

### Screenshots

![image](https://user-images.githubusercontent.com/99515866/153686534-016bbb46-e2e1-4284-8056-7458f8450e73.png)

**Comment by Raidobw2** [comment]
![image](https://user-images.githubusercontent.com/17010632/153703375-4ac32a73-f923-4399-8f42-2ce01d42f8ff.png)
Hi, I've seen this happen when people experience power cuts, a file becomes empty.

Try opening the modpack folder and checking the `config` folder. Inside should be a file called `island.json`. Open the file with a text editor such as Notepad. Normally there should be brackets "{}" (a BEGIN_OBJECT). In your case I think it's empty (STRING). If it is empty, delete that file and then try to play the modpack again. Please close the issue if this solved it!

**Comment by Raidobw2** [comment]
Closing as the above information shows how to solve it. We think it happens when one experiences a power cut, resulting in a corrupted config file
