### ISSUE TITLE
Server Connection Error: Unkown registry keys

### ISSUE THREAD

**Issue by hyperliskdev** [FTBTeam/FTB-Modpack-Issues#6145]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.1

### Launcher

Prism

### Has the pack been modified

No

### Log Files

```
[14:31:20] [Render thread/INFO] [minecraft/ConnectScreen]: Connecting to [ip_address], 25565
[14:31:22] [Render thread/WARN] [minecraft/ClientCommonPacketListenerImpl]: Client disconnected with reason: The server send registries with unknown keys: ResourceKey[minecraft:item / jaopca:dusts.xychorium]
```

### Describe the bug

Connecting to a server that was started on an older version causes some registry errors after updating the server. 

### Steps to reproduce

1. Update to latest direwolf20 Season 14 1.21 pack server and client.
2. Attempt connection to server.
3. Registry error

This server was also played on before the update.

### Expected behaviour

I should be able to just connect to the newly updated server

### Screenshots

![image](https://github.com/user-attachments/assets/f28d289a-b7c5-4c08-8b86-c2c1e81db8b0)

**Comment by BDTheNerdyMedic** [comment]
I believe something in the kubejs folder is not updating or purging properly. Try removing that folder and then rerun the update. If that doesn't work, try purging the config and defaultconfig folders too.

**Comment by Dnny44** [comment]
I also have this issue after updating to 1.4.1. I have attempted the fix that @BDTheNerdyMedic suggested in removing the kubejs and re-running the update did not resolve the issue. Also repeated the same process with the config and defaultconfig folders. Any direction would be spectacular!

**Comment by Saereth** [comment]
new updates should better handle this from now on
