### ISSUE TITLE
Add Growing Edelwood Saplings to the Market

### ISSUE THREAD

**Issue by Kezzar** [FTBTeam/FTB-Modpack-Issues#6149]
### Modpack

FTB Evolution

### Is your suggestion related to a problem? Please describe.

Edelwood seems to be either extremely rare or not spawning because of the biome overhauls, so adding saplings to the market would be helpful for Forbidden Arcanus progression.

**Comment by KittenIsLive** [comment]
Edelwood trees are not intended to generate anymore in the Forbidden Arcanus mod. You can either get an Edelwood sapling from a Wandering Trader (I made a Wandering Trader spawner), or get them from using a Dark Soul on an Oak Sapling. However, it'd be very nice to have them in the market as well, as it's very hard to find this information.

**Comment by Saereth** [comment]
yeah adding stuff to the market is very bugged right now so might have to revisit later, for now you'll have to stick to the normal way of making them
