### ISSUE TITLE
No Account created

### ISSUE THREAD

**Issue by picaro24** [FTBTeam/FTB-Modpack-Issues#6150]
### Modpack

FTB NeoTech

### Is your suggestion related to a problem? Please describe.

Hi, I downloaded FTB Luncher and I downloaded the Neotech modpack but when I try to start it it tells me that I don't have an account, how can I select the account from the FTB app?

**Comment by WyFryMU** [comment]
When you start the FTB App, in the bottom left corner, you should be able to log in to your Microsoft account.

**Comment by manmaed** [comment]
Hello This issue tracker is only for FTB Modpack issues for App Issues use: [FTB-App](https://github.com/FTBTeam/FTB-App/issues) or [Discord](http://go.ftb.team/discord)
