### ISSUE TITLE
Beneficial Perks hides JEI

### ISSUE THREAD

**Issue by keedux** [FTBTeam/FTB-Modpack-Issues#6157]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

When you have Beneficial perks in use, it'll hide JEI as well as the tool tips when you hover over an item.
![image](https://github.com/user-attachments/assets/c9461ec7-8ad4-463c-9389-a955e637bb29)

Here's an example of them hidden and it'll show JEI...
![image](https://github.com/user-attachments/assets/4a2aa321-d3bc-46ab-8208-b6e761b005ed)

### Steps to reproduce

1. Trigger some Beneficial perks.

### Expected behaviour

I expect to see the JEI regardless of perks active

### Screenshots

Already in explanation

**Comment by Vort3xGameStudios** [comment]
Would like to add that is also hides the "tool tip" when you hover over an item

**Comment by alfredggttv** [comment]
I'm not having the same issue in the current dev build. I believe this might have been due to a previous version of a mod. Will keep an eye on it for the next update!

**Comment by th3l0rdf0x** [comment]
Until the dev is released, this can be fixed for v1.1.0 - v1.2.0 by simply removing JEED and MEED from the mods. Seems to be an incompatability between these mods and some others.
