### ISSUE TITLE
Boon of Earth enchant causing block breaking bug.

### ISSUE THREAD

**Issue by squillis** [FTBTeam/FTB-Modpack-Issues#6159]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

See aboveWhen breaking blocks with Boon of Earth enchant with a hammer it causes this weird block breaking pattern and doesn't break all the blocks, making you break the same blocks multiple times until it finally clears out the area. 
![image](https://github.com/user-attachments/assets/f5acf0b5-9954-4ab7-b4f7-553604e5f595)

### Steps to reproduce

enchant hammer with boon
break blocks

### Expected behaviour

break all blocks in area and sometimes give you ores.

**Comment by ArtpokeBr** [comment]
Unfortunatly this might be something caused by the calculations required, added a tooltip to warn players about this.
