### ISSUE TITLE
[Bug]: Immersive Engineering Multiblock quests are not completing when built

### ISSUE THREAD

**Issue by SirDragonKnight** [FTBTeam/FTB-Modpack-Issues#616]
### Modpack

FTB University 1.16

### Modpack version

1.4.0

### Describe the bug

The multiblock quest won't complete when you build the multiblock machine. 

I have built the Metal Press, Assembler, and Crusher and could not get completion any of the 3.

havent' built the others yet but would assume they are probably broke also

### Steps to reproduce

1. Build the multiblock
2. Look at the finished build.

### Expected behaviour

Quest should get completed one of the multiblock has been completely built and activated.

**Comment by aaronhowser1** [comment]
Fixed, the observation tasks got reset to default or something. I also might have just forgotten to set them, but that sounds unlikely.
