### ISSUE TITLE
Factory Blocks bugged as there is no recipes to change it to other variants and won't drop item when mined

### ISSUE THREAD

**Issue by EisherzVII** [FTBTeam/FTB-Modpack-Issues#6162]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Factory Blocks blocks now can't be changed from the crafted Dotted Rusty Plate variant using the Mason Table or Chisel since there is no recipes for it anymore. Nor will it drop the block after being placed, and will take a long time to take to mine no matter what tool to use. This seems to happen after updating the modpack from FTB Evolution 1.1.1 to 1.2.0

### Steps to reproduce

1. Craft the Dotted Rusty Plate
2. Use the Mason Table or Chisel to try and change it to other Factory Block blocks
3. Can't
4. (Also placing the block on the world and trying to mine it will take a long time and won't drop the block)

### Expected behaviour

Able to craft other variants using Mason Table/Chisel

### Screenshots

Pressing the usage key on the Dotted Rusty Plate doesn't show any other recipes (e.g. Mason Table)
![2024-11-11_09 45 05](https://github.com/user-attachments/assets/1c8e74a0-ecfa-475c-ad98-8bcc34f0ea31)

**Comment by alfredggttv** [comment]
This seems to have been fixed in the newest mod update.
