### ISSUE TITLE
Tool belt can't be equipped in Curios belt slot

### ISSUE THREAD

**Issue by dzhang314** [FTBTeam/FTB-Modpack-Issues#6163]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The tool belt (from the Tool Belt mod) cannot be equipped in the Curios belt slot, or in fact, any Curios slot or any armor slot.

### Steps to reproduce

1. Craft or `/give` yourself a Tool Belt.
2. Open inventory.
3. Attempt to equip in belt slot (or any other slot).
4. Nothing happens.

### Expected behaviour

Belt should be equipped in the belt slot.

**Comment by Volpamonhub** [comment]
Hello,
There is a special menu for this mod called "**Open Belt Slot Inventory**" which is bound to the **V key by default**. It opens an interface window where you can place the belt in the designated slot, located to the right of your character, just above the shield.

**Comment by dzhang314** [comment]
Hey @Volpamonhub, thanks for the info! Wow, that's very unexpected. I have no way of knowing about this secret menu without stumbling upon this keybind. I would request the FTB authors to **add a note to the tool belt quest** about this alternate UI.

btw, huge thanks to the mod and modpack authors for FTB Evolution! This is my first experience with modded Minecraft in years, and I'm having a blast.

**Comment by Saereth** [comment]
switched this to enhancement so we can add a note on the quest for it
