### ISSUE TITLE
Skill Progress doesn't load on rejoining the world

### ISSUE THREAD

**Issue by Bluehanz** [FTBTeam/FTB-Modpack-Issues#6164]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

This happened specifically with Ultimine: I started a new world yesterday and progressed enough to get the first mining skill that increases the total blocks mined with ultimine from 16 to 32. I logged back today and the ultimine is back to mining 16 blocks, but with the first mining skill checked out

### Steps to reproduce

1. Create New World
2. Mine enough blocks to get the first mining skill
3. Exit World and Instance
4. Reload Instance and Re-enter World

### Expected behaviour

Ultimine should be able to target 32 blocks instead of 16

**Comment by alfredggttv** [comment]
This is something we've been trying to tackle for a few versions. We believe we might have a fix for the next update.
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6059
