### ISSUE TITLE
[Bug]: PackagedAuto is not working correctly

### ISSUE THREAD

**Issue by SirDragonKnight** [FTBTeam/FTB-Modpack-Issues#617]
### Modpack

FTB University 1.16

### Modpack version

1.4.0

### Describe the bug

It looks like there are 2 issues.
1. When you restart the game, AE no longer sees the package holder in the packager block and show the recipe missing if you try to make the item.
2. Once you fix the problem with #1 by pulling the  holder and and placing back in. the unpacker no longer recognized the packages to pull them into the unpackager.

I've tried moving the blocks around, wiping out the holders and even restarting and the resetting up, but nothing i've tried so far has fixed the issue. 

I've been using the recipe for Crystaltine Ingot as that is the only thing i have enough materials for atm.

Also I can manully put the packages into the unpackager and they will unpack.

### Steps to reproduce

not sure how to reproduce as it is an ongoing issue.

### Expected behaviour

Recipe should package items, and the packages should go to the unpackage to be finished.

**Comment by aaronhowser1** [comment]
Full setup
![image](https://user-images.githubusercontent.com/15698722/157033629-277b65be-b985-4fbf-a127-c8dda0c0c64d.png)

Recipe
![image](https://user-images.githubusercontent.com/15698722/157033548-0fc824b4-0844-45d4-83ac-f7279f22c6f3.png)

Requesting
![image](https://user-images.githubusercontent.com/15698722/157033566-a6ce005a-6861-402d-80fa-f6acea8913f1.png)

Ingredients sent
![image](https://user-images.githubusercontent.com/15698722/157033614-aceb58ec-c25e-4b63-9669-34a4b7288538.png)

Works for me. I also did a full game restart after taking the pictures, and it still works with no changes.

I don't see the connection to #1 though.
