### ISSUE TITLE
Crafting Stations from the Crafting Station mod do not allow you to fill recipes from JEI

### ISSUE THREAD

**Issue by Kandarth** [FTBTeam/FTB-Modpack-Issues#6171]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The crafting stations from the Crafting Station mod do not allow you to fill recipes from the JEI. Regular crafting tables and other 3x3 crafting methods still work, but these specifically do not. It will still show the button if you are missing the required materials, but as soon as you have all the materials, the button vanishes entirely. 
![2024-11-11_22 23 35](https://github.com/user-attachments/assets/39c4e4ca-28c8-47d2-a15f-3cca919b9498)
![2024-11-11_22 22 34](https://github.com/user-attachments/assets/a7c325c5-df7b-478d-bfac-9db7e32af04e)

### Steps to reproduce

Create either the Crafting Station or the Crafting Station Slab from Crafting Station, and attempt to autofill a recipe from JEI.

### Expected behaviour

On two separate worlds the Crafting Station and the Slab will both have their autofill buttons vanish as soon as you have the required materials to make the item

**Comment by Gaz492** [comment]
Looks like this is already reported to the mod developer https://github.com/Tfarcenim/crafting-station/issues/104

**Comment by ttechr** [comment]
Interesting thing with this. If there is an inventory next to it then it will work. On my server world I have a crafting station that is next to a furnace from Iron furnaces and the autofill works. Just setup a singleplayer to test some more and it looks like if you have a vanilla furnace it doesnt work, but a vanilla chest works.
