### ISSUE TITLE
Just dire things dupe glitch

### ISSUE THREAD

**Issue by punpun80** [FTBTeam/FTB-Modpack-Issues#6172]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

If you give an allay an upgraded tool from just dire things then it dupes the upgrade when it drops on the ground as well as keeping the original on the item

### Steps to reproduce

1. Have an upgraded Just dire things tool (ex. Ferricore Axe with tree feller)
2. Give the tool to an allay. The upgrade will drop like the item has been broken
3. Take the tool back. It will still have the upgrade

### Expected behaviour

Fix the duplication glitch

**Comment by ArtpokeBr** [comment]
Yeah, Unfortunately Dire won't be able to Fix this, as this is a Forge Bug, gonna be closing the issue here.
