### ISSUE TITLE
Harvester Pylon from Pylon is not working

### ISSUE THREAD

**Issue by JanKoch99** [FTBTeam/FTB-Modpack-Issues#6173]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Harvester Pylon from Pylon is not working at all.

### Steps to reproduce

Just craft a Haverster Pylon. It doesn't work at all.

### Expected behaviour

The Harverster Pylon should plant and harvest any seeds

**Comment by ttechr** [comment]
I have mine working on Inferium Seeds and its working just fine. 
I have mine placed inside a water source block that is at dirt level and then a barrel above it. I am currently using an iron hoe in mine.

**Comment by ttechr** [comment]
> you need to provide power to it as well, but yeah I just tested and its all working fine

Little clarification. I do not believe it needs power as I am not powering mine and its working fine.
