### ISSUE TITLE
Decreased mobs spawning

### ISSUE THREAD

**Issue by dreambhop** [FTBTeam/FTB-Modpack-Issues#6176]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I noticed mobs not really spawning anymore, firstly in the overworld where it used to be swarmed by hostiles at night. I still see groups of farm animals when I go around. But now I've especially noticed it in the end, where it was swarmed with endermen, and now there is not a single one in sight? Not really sure what could be causing it, it's not like there's a mob limit hit when there is nothing around.

I am playing on a server with a few friends.

If anyone knows anything about it, would be great!

![Untitled](https://github.com/user-attachments/assets/a7d0c81e-badb-4c72-96be-171508c255cb)

### Steps to reproduce

Not exactly sure how to reproduce it, spent more than 40 hours on a world, restarts included

### Expected behaviour

I should see a lot of mobs in certain areas, the same way as when I first started this world

**Comment by Saereth** [comment]
This definitely looks like mob cap limiting, you can increase your mob limit in the config/servercore configs to something more your likely, 70 is vanilla, we're shipping with 50 atm, if you have several players on at once you may want to increase it.

**Comment by LWmods** [comment]
i noticed this on my server last night, there was no endermen on the main island but they seemed to spawn normally on the outer islands
