### ISSUE TITLE
AppliedFlux Addon

### ISSUE THREAD

**Issue by LoRdCoBrA59** [FTBTeam/FTB-Modpack-Issues#6178]
### Modpack

FTB Evolution

### Is your suggestion related to a problem? Please describe.

Being able to power machines through AE2 helps keep automations clean. can also help cut down on lag cuz you don’t need to use so many gates to transfer power around your base. Also sometimes hooking power up to a set of machines that’s already got stuff hooked into it is impossible so having the ablility to send power through AE would make it a lot easier and cleaner.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/applied-flux
Adds the ablility to transfer power through AE2 Networks

**Comment by Saereth** [comment]
thanks for the suggestion, we decided not to add it right now but we might/likely will at some point in the future
