### ISSUE TITLE
Raw Tungsten

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Modpack-Issues#6179]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

N/A

### Describe the bug

Raw Tungsten has no smelting/basting rescipe

### Steps to reproduce

see desciption

### Expected behaviour

to smelt

**Comment by Saereth** [comment]
This is intended, it needs to be processed in the EBF
