### ISSUE TITLE
[Bug]: Interdimensional Modifier doesn't appear to be working in the Void Miner

### ISSUE THREAD

**Issue by SirDragonKnight** [FTBTeam/FTB-Modpack-Issues#618]
### Modpack

FTB University 1.16

### Modpack version

1.4.0

### Describe the bug

When I put the Interdimensional Modifier into a void miner in the end. It is not pulling items from the other dimensions as the tooltip specifies.

I've also tried this in the overworld and it doesn't pull the end stuff either.

Both these attempts were done in a creative world.

### Steps to reproduce

1 make a void miner and make sure 1 of the modifiers is a Interdemension modifier.

### Expected behaviour

void miner should pull in items from other dimensions.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/157036201-7e9e5ce4-ff4d-402f-baf9-663a090b5b49.png)

I seem to be having the exact opposite problem O_o

Putting an interdimensional modifier on an ore multi miner in the End isn't letting me mine Iron etc though, so bug confirmed.

EnviroTech doesn't have a github, so here's where I'm asking in their server
