### ISSUE TITLE
Lost Quest Button

### ISSUE THREAD

**Issue by Tempus-Aeternus** [FTBTeam/FTB-Modpack-Issues#6182]
### Modpack

FTB Evolution

### Modpack version

1.2.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I no longer have the button to open my quests menu. While attempting to resolve a separate bug I pressed the gear icon in the inventory and toggled the second to last option. This removed all the sidebar buttons, including the quests button. I have not found any config, key bind, or other option that would allow me to bring back this button.

### Steps to reproduce

1. Open Inventory
2. Press gear icon
3. Toggle sidebar visibility (second to last)

### Expected behaviour

I expected some way to recover these buttons.

### Additional information

The bug I was attempting to fix was having no JEI overlay or tooltips unless the curios inventory is open.

**Comment by Gaz492** [comment]
You can bring back the sidebar buttons by typing `/ftblibrary clientconfig` into chat then setting enable sidebar button to true

**Comment by Tempus-Aeternus** [comment]
Thank you! this solved the issue.
