### ISSUE TITLE
explosive jump

### ISSUE THREAD

**Issue by Talavezza** [FTBTeam/FTB-Modpack-Issues#6184]
### Modpack

Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I die for falling, i reach my things and then every jump i made i have a explosion in my feets
![imagen_2024-11-13_215359051](https://github.com/user-attachments/assets/7a6e37c0-41cd-4d12-8385-7e09df20ed54)

### Steps to reproduce

1.- die for falling
2.- grab your things
3.-jump

### Expected behaviour

nothing just jumping normal

### Screenshots

![2024-11-13_21 48 57](https://github.com/user-attachments/assets/6c63a352-820d-4b8b-8da7-4c146febc3ef)
![2024-11-13_21 48 58](https://github.com/user-attachments/assets/6c244b0e-1f83-4a30-a0e8-73d32bacb32a)
![2024-11-13_21 48 59](https://github.com/user-attachments/assets/5e48d959-0dd0-47e8-aeca-ffab98b34cbd)

**Comment by Gaz492** [comment]
I haven't been able to reproduce this, do you happen to have any special boots/other armour pieces equipped, an enchantment, curios item or something else in your inventory/armous/curios slots that may be causing this?

**Comment by Talavezza** [comment]
> I haven't been able to reproduce this, do you happen to have any special boots/other armour pieces equipped, an enchantment, curios item or something else in your inventory/armous/curios slots that may be causing this?

ok! i check and when i die i have a talisman in my inventory and when i click my things in the grave, the talisman goes to my curio!

Sorry!
