### ISSUE TITLE
Servinstall messed up the ftbquests folder

### ISSUE THREAD

**Issue by Volpamonhub** [FTBTeam/FTB-Modpack-Issues#6187]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Since updating to version 1.3.0 this morning, the chapter progression sidebar no longer shows the chapter names (as shown in the attached screenshot). I can still complete quests, make progress, and receive items, but the sidebar does not display correctly.

### Steps to reproduce

I attempted a repair via the FTB app, but it did not resolve the issue.
I'm not sure how to reproduce this bug, as I haven't been able to fix it to attempt further testing.

### Expected behaviour

The chapter titles should display correctly in the sidebar.

### Screenshots

![2024-11-14 15_52_36-FTB Evolution - Minecraft 1 21 1](https://github.com/user-attachments/assets/07082c1a-20e9-48f2-939f-eea352250926)

### Additional information

I had to use an NBT editor to remove items from my inventory from a mod that was removed during the update; otherwise, I couldn't connect to the server.

**Comment by Ninetailed** [comment]
I have also run into this one. I'd just updated a server from 1.2.0 and found this problem on connecting. I did not encounter the problem in a fresh single-player world, or with a clean server install, where it worked fine.

**Comment by Volpamonhub** [comment]
I tried reinstalling the client, but I'm still at the same point.
I tried a fresh install of the server (with a copy of the world), but I'm still at the same point.
I restored the ftbquests data (the world/ftbquest folder from my character before the upgrade to 1.3.0), but I'm still at the same point.
With all of that, at some point, I should have at least recovered the chapter names, right? I don't understand.

**Comment by Volpamonhub** [comment]
Apparently, during the server update via servinstall, it ended up deleting some things in the ftbquests folder. This is the second time I’ve updated the server with servinstall, and both times it caused weird issues. Anyway, the problem is resolved now.
