### ISSUE TITLE
Mining Dim / Void Dim Portal

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Modpack-Issues#6188]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

N/A

### Describe the bug

The Nether/End/Void Portals dont show up in JEI

### Steps to reproduce

search for portal

### Expected behaviour

to show

**Comment by th3l0rdf0x** [comment]
Same applies to Armory Cabinet from Functional Storage

If you obtain one from the creative menu, the recipe function works fine, it's just not visible in JEI from search.
