### ISSUE TITLE
Immersive Engineering workbench causing crash with blueprints

### ISSUE THREAD

**Issue by grandmafrosty** [FTBTeam/FTB-Modpack-Issues#6189]
### Modpack

FTB Inferno

### Modpack version

1.10.1

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

[crash-2024-11-14_16.03.06-client.txt](https://github.com/user-attachments/files/17759688/crash-2024-11-14_16.03.06-client.txt)

### Describe the bug

When I place a blueprint in the Immersive Engineering Workbench, the game freezes, closes (shows the saving game screen), then pops up with a crash report

### Steps to reproduce

1. Place Immersive Engineering Workbench
2. Insert crafted blueprint
3. Game crash

### Expected behaviour

No crash should occur

**Comment by Gaz492** [comment]
Duplicate of #5996
