### ISSUE TITLE
[Bug]: Baby Zombies/Drowned/Zombie villagers lose AI and can't be moved

### ISSUE THREAD

**Issue by mouro001** [FTBTeam/FTB-Modpack-Issues#619]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Describe the bug

When leaving a mob farm overnight in a server on, you might find zome baby zombies just stuck there.
You can punch them (it doesn't do anything). You can kill them with a powerful sword.

### Steps to reproduce

1. Setup a mob farm with cursed/blursed earth
2. Setup a few fans to move the mobs into a mob masher/spikes
3. Leave it for a couple hours 
4. See that there are zombies that didn't get pushed

### Expected behaviour

All mobs should be affected by the fan

### Screenshots

![image](https://user-images.githubusercontent.com/8522686/153753515-f8b82f86-dc9a-4628-b7a1-9b93ded5d119.png)
![image](https://user-images.githubusercontent.com/8522686/153753533-702d805d-3e09-48c6-9535-a7bd76b41577.png)

**Comment by Raidobw2** [comment]
Thank you for the report, however we will keep track of this problem in the already opened issue #415
