### ISSUE TITLE
Add More Overlays

### ISSUE THREAD

**Issue by tac-owo** [FTBTeam/FTB-Modpack-Issues#6196]
### Modpack

FTB Evolution

### Mod suggestion

I miss JEI search so much :(
This adds it.

https://modrinth.com/mod/more-overlays-updated/version/1.23.2-mc1.21-neoforge

**Comment by ArtpokeBr** [comment]
You can add the mod manually if you want :)

Unfortunatly it does add some memory impact so we can't press our userbase. Its a clientside mod so feel free to add to your instance ;)
