### ISSUE TITLE
JEI Missing or Not selectable recipes

### ISSUE THREAD

**Issue by Temil2006** [FTBTeam/FTB-Modpack-Issues#6197]
### Modpack

FTB Evolution

### Modpack version

1.1.0 had the issue, confirmed still a problem in 1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

There seems to be multiple recipes within JEI that are missing and/or not working as expected.

One example of missing recipe is "Fluid Hopper" .. I can manually craft it via the crafting menu by placing all the needed items, but the recipe doesn't show up for the item or for the mod name.

One example of non-working recipes.. meaning they are present in the JEI search, but can't craft them are multiple blueprints from "Silent Gear" .. for example, binding or grips ..can't craft there blueprint / templates by clicking on the item (no recipe shows for them). Also looked up the recipe, and can't craft them via default recipe manually without JEI.

as a test, we installed EMI over the top of JEI, and the "Fluid Hopper" shows in the EMI search, just not in the JEI .. however, EMI isn't really a great option because EMI is missing some as well such as some of the repair kit recipes.

### Steps to reproduce

in reference to missing recipes
1. open JEI
2. search for "Fluid Hopper"
3. only 1 item returns, and it's not the Fluid Hopper that should return.

in reference to non-working recipes
1. open JEI
2. search for "@silent grip"
3. select the template or blueprint, nothing happens (no recipe is displayed like all other blueprints)

### Expected behaviour

to have the recipes show and be usable.

**Comment by Gaz492** [comment]
Duplicate of #6118

**Comment by Temil2006** [comment]
The ticket 6118 isn't a valid duplicate issue. 
6118 == entire JEI interface not being viewable.

What i reported was not the same. I'm reporting that there are missing recipes from the JEI menu, and NOT that the JEI menu isn't displaying. 2 completely different issues.

Where in these 2 issues are they considered the same?

**Comment by Gaz492** [comment]
Apologies, it looks like I was in the wrong tab when I was closing similar issues.
