### ISSUE TITLE
[Bug]: Small ships rowing boat got me kicked from server

### ISSUE THREAD

**Issue by WauloK** [FTBTeam/FTB-Modpack-Issues#62]
### Modpack

FTB OceanBlock

### Modpack version

1.2.0

### Log Files

https://pastebin.com/bXgpxaxs

### Describe the bug

Twice within 5 mins while on the boat the game crashed with ArrayIndexOutOfBoundsException.
FTB OceanBlocks is running on a Linux server.
The error message in the console says:
Server thread/WARN20:01:37
WauloK was kicked for floating too long!
Server thread/INFO20:01:37
WauloK lost connection: Flying is not enabled on this server
WauloK left the game
Server thread/WARN20:01:37
handleDisconnection() called twice

Then the server boots my client and it crashes the client.

### Steps to reproduce

Standing on a floating raft and jump into the boat then paddle 5-6 blocks.

### Expected behaviour

Not to crash :)

**Comment by Sunekaer** [comment]
Set allow flying to true in the server properties.
