### ISSUE TITLE
Turtles not working correctly

### ISSUE THREAD

**Issue by Foxman124** [FTBTeam/FTB-Modpack-Issues#6200]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

CC Tweaked Turtles do not work correctly. They will mine one level and then stop before going down to the next leve. I see this issue previously reported in another ticket # 6143 that was closed. The issue was fixed in a later patch but it was on FTB evolution and not Direwolf20 1.2.1

### Steps to reproduce

1. Place mining Turtle 2. enter command either "excavate 3" or "tunnel 3" 3. Turtle will begin program, mine level it is currently on 4. once the turtle goes to descend a level and mine the next, it will stop and not respond to commands. 

### Expected behaviour

Wanted turtle to work as normal.

**Comment by ArtpokeBr** [comment]
Fixed in the Current Version
