### ISSUE TITLE
Railcraft Reborn Crusher disconnects from power on world reload

### ISSUE THREAD

**Issue by zperk13** [FTBTeam/FTB-Modpack-Issues#6201]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.1

### Launcher

Prism

### Has the pack been modified

No

### Describe the bug

Multiple energy moving options, including Mekanism universal cables, LaserIO energy cards, Powah Ender Gates, and AppliedFlux induction cards will properly connect to Railcraft Reborn crushers and transmit energy to it. Upon world reload however, all of these will no longer transmit power to the crusher and the ones that visibly connect to the crusher will no longer do so.

Interestingly, Pipez energy pipes don't seem to suffer from this bug, so for anyone also experiencing this issue, I recommend using that until it's fixed.

### Steps to reproduce

1. Build a Railcraft Reborn crusher (3x2x2 multiblock)
2. Put a Mekanism universal cable next to it
3. Observer that the cable connected to the crusher
4. Log out of the world
5. Log back into the world
6. Observe that the cable has disconnected and is no longer transmitting power to the crusher

### Expected behaviour

Energy should not disconnect on world relog

**Comment by ArtpokeBr** [comment]
Fixed in the Current Version
