### ISSUE TITLE
Storage issue with Jade and Vanilla Chests and Refined Storage Chests causing error on server

### ISSUE THREAD

**Issue by Ghost777737** [FTBTeam/FTB-Modpack-Issues#6202]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.3.0

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

https://pastebin.com/EAMi4KXZ

### Describe the bug

As soon as I am in the chunk of my chests the error message Data Size too large appears in the server console. This sometimes causes players to get kicked 

### Steps to reproduce

Open any chest in my Base

### Expected behaviour

For it to work without kicking me from the server

### Additional information

I have even reset the whole server but maybe the issue is with the world. I recently increased the RAM on the server. Maybe that caused an issue??

**Comment by ArtpokeBr** [comment]
Gonna be closing this issue as it seems to be from an Old Pack Version, please let us know if this still persists.
