### ISSUE TITLE
Downloading server files installer needs a progress bar

### ISSUE THREAD

**Issue by SfSec** [FTBTeam/FTB-Modpack-Issues#6209]
### Modpack

FTB Evolution

### Is your suggestion related to a problem? Please describe.

Super frustrated when I can't see how long a particular installation may take. Especially when the old method was to download the files and set it up my own way. I get that the server installer is meant to streamline that, but when I don't feel in control of the installation, I think it instead adds to a lot of frustration.

![image](https://github.com/user-attachments/assets/1a3b8ad7-ba68-4358-ae4d-0dcc262a2e35)

Looking at this screen for minutes or hours and figuring out if something is going wrong is frustrating. It would do the pack well to resolve this simple problem. Heck if you want to Ill make you a progress bar in powershell.

**Comment by Gaz492** [comment]
If you download our new server installer for a modpack again from our website or from https://github.com/FTBTeam/FTB-Server-Installer/releases/latest it has a progress bar

**Comment by SfSec** [comment]
Hi FTBTeam/Gaz,

Thanks for the quick turnaround on this, massively appreciate the QoL there.

Have a nice day folks at FTB.
________________________________
