### ISSUE TITLE
Server startup problem.

### ISSUE THREAD

**Issue by MissionWasabi** [FTBTeam/FTB-Modpack-Issues#621]
### Modpack

FTB Ultimate: Anniversary Edition

### Modpack version

1.2.0

### Log Files

[installer.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8061033/installer.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8061035/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8061036/debug.log)

### Describe the bug

Can't start server after installing it.

### Steps to reproduce

1. Get server installer from FTB App
2. Move it in folder and launch installer
3. Wait untill installing ends with no issues (I guess)
4. Launching start.bat file
5. It gives me some strange code in console and if I press any button, it closes without creating any additional files for server

### Expected behaviour

Server starts and I can play with my friends

### Screenshots

![image](https://user-images.githubusercontent.com/99662151/153873554-2d7ab121-f1cc-4361-bed6-164ee9e0ac0d.png)

### Additional information

Kinda same issue with FTB Endeavour modpack, so I guess, its my PC problem

**Comment by Sunekaer** [comment]
Issue is with the java version.
You will find older builds of Java 8 on Adoptium's website, at https://adoptium.net/archive.html?variant=openjdk8&jvmVariant=hotspot. Take the JRE for the jdk8u312-b07 section from 21 October 2021, otherwise more recent versions might be incompatible.

**Comment by MissionWasabi** [comment]
Thank you so much! It helped! =)
