### ISSUE TITLE
"It starts with some Goo" Quest not accepting Primogel goo crafted/inhand

### ISSUE THREAD

**Issue by Gloval** [FTBTeam/FTB-Modpack-Issues#6214]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

Prism

### Has the pack been modified

No

### Log Files

None

### Describe the bug

Craftig or just holding Primogel Goo does not triger the quest.
Tried resetting the quest and the entire Just Dire Things Chapter to no effect.

### Steps to reproduce

Open Quest book
Access Just Dire Things Quest.
Accept the initial quest to get book.
Make Primogel.

### Expected behaviour

Quest to complete

**Comment by myKrins** [comment]
Hi,
when I remember correctly, you need to do the quest with hunting 50 Zombies (from The Wild Hunt) before. Have you already done that? After that this quest is unlocked.

**Comment by Gloval** [comment]
We did discover this through playing. Sorry I forgot about this and didn't some back and close it out. 
Thank you!

**Comment by Gloval** [comment]
Resolved by killing 50 zombies.
