### ISSUE TITLE
Add peaceful way to get nether stars

### ISSUE THREAD

**Issue by toruPuchuu** [FTBTeam/FTB-Modpack-Issues#6216]
### Modpack

FTB Presents Direwolf20 1.21

### Is your suggestion related to a problem? Please describe.

Will you please add a way to get nether stars in peaceful? They are the first hostile mob drop that I have needed but couldn't find a way to get.  Thanks

**Comment by ArtpokeBr** [comment]
Hmm, with the recent addition of Oritech, you may be able to achieve this, let us know if you still don't.
