### ISSUE TITLE
Stop using Inventory Sorter

### ISSUE THREAD

**Issue by phit** [FTBTeam/FTB-Modpack-Issues#6218]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The mod has been mostly broken for a long time in various packs and isn't actively maintained.

See https://github.com/cpw/inventorysorter/pull/195, https://github.com/cpw/inventorysorter/issues/197

and some historical issues
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5052
https://github.com/cpw/inventorysorter/issues/194
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5997

there's dozens more on both this and ATM issue tracker

### Steps to reproduce

start a server for FTB Evolution and run, /stop it will happily crash https://github.com/cpw/inventorysorter/issues/198

### Expected behaviour

A working inventory sorting option that doesn't cause crashes or deletes items when sorting

**Comment by MichaelHillcox** [comment]
I'm actively maintaining this project now (Inventory Sorter) and have already pushed updates for 1.20 and 1.21. Please create issues on the Inventory Sorter project if you know of any issues

**Comment by phit** [comment]
I mean that's one way to approach this, are you gonna start adding a proper default config to avoid all the issues with the mod voiding items? that's been really the main benefit of a maintained mod like [InventoryTweaks Refoxed](https://github.com/JDKDigital/InvTweaksRefoxed/blob/b4af7181530363477f501540972133276f81d54f/src/main/java/invtweaks/config/InvTweaksConfig.java#L57)

**Comment by MichaelHillcox** [comment]
> I mean that's one way to approach this, are you gonna start adding a proper default config to avoid all the issues with the mod voiding items? that's been really the main benefit of a maintained mod like [InventoryTweaks Refoxed](https://github.com/JDKDigital/InvTweaksRefoxed/blob/b4af7181530363477f501540972133276f81d54f/src/main/java/invtweaks/config/InvTweaksConfig.java#L57)

Yes, the idea is to continue to improve the mod. Not just leave it to die off, I plan on adding more native integration very soon  :D
