### ISSUE TITLE
Missing Crafting Recipes and incompatible items

### ISSUE THREAD

**Issue by Kjosu** [FTBTeam/FTB-Modpack-Issues#6220]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

There are a few missing recipes/items in JEI and also incompatible crafting ingredients.

- AE2 cable facades not showing in JEI
- MI tin cable needs FTBR tin wires (which has no JEI recipe) instead of MI tin wires
- Forbidden Arcanus: Soul Binding Crystal not searchable in JEI
- cant use mekanism copper dust in MI mixer for bronze or cupronickel dust
- Advanced AE Quantum Infusion is missing JEI recipe to really produce it
  - When pressing "U" on Quantum Infused Dust the recipe shows up, but it does not show that it creates Quantum Infusion

### Steps to reproduce

search in JEI for the above listed recipes/items

### Expected behaviour

to have the recipes show and be usable.

### Additional information

Relates to:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6194
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6197

**Comment by Saereth** [comment]
Issues need to be separated issues please.Bulk issue posts are not useful in tasking, prioritizing or tracking.
