### ISSUE TITLE
JEI + Tooltips not showing up. And now my game is freezing up and I can no longer play the save.

### ISSUE THREAD

**Issue by SkinnyBacon** [FTBTeam/FTB-Modpack-Issues#6223]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

All of a sudden, the JEI doesn't appear to the right of my inventory and tooltips. Only buffs. I can't get it in the snippet, but when I hover my cursor over items, no tooltips appear, so I can't see the names of the items or anything.
The JEI toolbar only reappears when I click in its area, which 
I tried resetting the settings on the JEI mod, but nothing changed.
Update while typing this. I now cannot enter the world without crashing the game

### Steps to reproduce

I have no idea. It just happened while my inventory was open

### Expected behaviour

I expected to see the JEI toolbar

### Screenshots

![Screenshot 2024-11-19 154457](https://github.com/user-attachments/assets/dfbb12a9-d206-4fa8-8b8c-e39a2a9fffe2)
![Screenshot 2024-11-19 154525](https://github.com/user-attachments/assets/ce75e831-e04d-4b71-9978-d4b9340de176)

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by ttechr** [comment]
For the jei and tooltip thing this is a known bug and is looking to be caused by the just enough potion effects(or something like that) A workaround for this is to go into your inventory and right click the gear on the top left. Once there press the little red x on the top right of each of the options on the top row. That has worked for me.
