### ISSUE TITLE
[Bug]: Server crash and unable to access world after crafting plastic with refined storage

### ISSUE THREAD

**Issue by PottedRosePetal** [FTBTeam/FTB-Modpack-Issues#623]
### Modpack

Direwolf20

### Modpack version

1.13.2 / 1.16.5

### Describe the bug

The whole crafting process is firstly crafting the small dry rubber pellets, which does not have a recipe so I just put 5 buckets of water and one bucket of latex as a recipe, which works standalone (tho sometimes it just puts one bucket of water?) and that gives 10 pellets. Those then get crafted into a dry rubber and that gets smelted. 
When requesting plastic in my survival world the world instantly hard crashed, but in the creative world where I recreated the issue it took a few seconds. 
The following file contains a world JUST before it hard crashes, if you request plastic in there, it crashed for me. 
The world will be broken afterwards, as in it cant be loaded anymore.
[2022-02-15-12-09-39.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8068577/2022-02-15-12-09-39.zip)
 

### Steps to reproduce

1. go to attached world
2. request plastic
3. expect crash? if it does not, maybe request more plastic.

### Expected behaviour

I expected to get plastic.

**Comment by Raidobw2** [comment]
Fixed in v1.9.17+ of Refined Storage for Forge in 1.16.5
https://github.com/refinedmods/refinedstorage/issues/3157
