### ISSUE TITLE
Curios commands for adding slots not working

### ISSUE THREAD

**Issue by Skyknight46** [FTBTeam/FTB-Modpack-Issues#6230]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.1

### Launcher

FTB App

### Has the pack been modified

Yes

### Describe the bug

Whenever I try to run the curios command to add some curios slots the command runs without errors, but the slots don't get added to my player.
command ran:
![afbeelding](https://github.com/user-attachments/assets/97a9dfa4-ef4e-4df0-ac74-980f98a8c407)

curios slots after command:
![afbeelding](https://github.com/user-attachments/assets/decd4111-1fe8-4391-8c2a-4081e8cf7d59)

### Steps to reproduce

1.  Create any sort of world
2.  Check curios slots before command
3.  Run command "/curios add _PlayerName_ _SlotYouWouldLikeToAdd_ _amount you would like to add_"
4.  Check Curios slots to see the command failed to add said slot

### Expected behaviour

Extra curios slots of the specified type to be added to the player

### Additional information

Only modification to the pack has been the addition of `FTB ultimine`. 

Perhaps I'm doing something wrong?

**Comment by Gaz492** [comment]
It looks like this is a known issue with the mod at the moment https://github.com/JDKDigital/Adorned/issues/10
According to that issue report, you may be able to use datapacks to add the extra slot(s)
