### ISSUE TITLE
Aluminium ingot issues

### ISSUE THREAD

**Issue by JakeHumphries4** [FTBTeam/FTB-Modpack-Issues#6236]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

General issues with aluminium-related things - 

Immersive engineering recipes require FTB Resources aluminium, which cannot be acquired via Immersive Engineering. This means the player must get fairly deep into Modern Industrialisation ( the only other way).
- Some Xycraft recipes work with FTB Recources aluminium, whereas others do not.
- Xycraft aluminium can be crafted into FTB Resources blocks of aluminium and then uncrafted into FTB Resources aluminium ingots with no way of going back.
- Immersive engineering aluminium (bauxite ore) doesn't spawn (and rightly so), however, this causes the issue with the requirement as mentioned above.
Potentially a solution is to make bauxite ore drop raw aluminium, and process it the immersive engineering way. This would cause issues with Modern Industrialisation, however, as bauxite dust wouldn't exist.

### Steps to reproduce

1Try to craft anything with aluminium. 2. Notice issues

### Expected behaviour

Better ore dict behaviour/ better integration between mods

**Comment by JakeHumphries4** [comment]
Just to further this, FTB Resources Blocks of Raw Aluminium can be obtained using Eldritch Ancient Miner, as it generates Raw ore blocks directly.

**Comment by ArtpokeBr** [comment]
Currently XyCraft's Aluminum and MI's Aluminum are separated, IE should use the XyCraft's Variant.

I've fixed a couple of recipes that used the wrong tags, please let me know if I missed something! :)
