### ISSUE TITLE
Just Dire Things Simple Clicker causes crash when interact with Farmer's Delight cutting board

### ISSUE THREAD

**Issue by tlion1069** [FTBTeam/FTB-Modpack-Issues#6237]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[crash-2024-11-20_20.21.14-server.txt](https://github.com/user-attachments/files/17866356/crash-2024-11-20_20.21.14-server.txt)

### Describe the bug

When a Simple clicker is set to be right-clicking on a cutting board, the game crashes as it is trying to interact. Basically makes the world unplayable unless have the clicker removed by other means.

### Steps to reproduce

1. Place a cutting board
2. Place a simple clicker next to cutting board, facing it
3. Set clicker to right click and is constantly clicking (ignore redstone signal)
4. Crash

### Expected behaviour

Be clicking on the cutting board normally without crashing

**Comment by ArtpokeBr** [comment]
![image](https://github.com/user-attachments/assets/11148f6d-3842-47d5-91a6-1c6bdb729336)
seems to be fixed.
