### ISSUE TITLE
Rabbit Hide MA Pattern not creating Rabbit Hide

### ISSUE THREAD

**Issue by Volt-the-Insane** [FTBTeam/FTB-Modpack-Issues#6238]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Through JEI, the recipe to make rabbit hide through Mystical Agriculture with Rabbit Essence is creating a Rabbit Foot instead of the advertised Rabbit Hide. 

### Steps to reproduce

1. Open crafting grid
2. Search Rabbit hide
3. Hit R 
4. find the Mystical Agriculture recipe
5. hit the "+" 
6. Observe the pattern creating Rabbit's Foot instead of Rabbit Hide.

### Expected behaviour

I expected Rabbit Hide to show up in the crafting grid product.

### Screenshots

![image](https://github.com/user-attachments/assets/b6179c0d-5214-422d-a3da-cbb86cd9fcd0)
![image](https://github.com/user-attachments/assets/a094ea57-089a-4206-ad63-05a6ac9545d5)

**Comment by ArtpokeBr** [comment]
the dev fixed this 4 days ago, thankfully! =)
