### ISSUE TITLE
server disconnection on particle creation

### ISSUE THREAD

**Issue by Matthewhacksu** [FTBTeam/FTB-Modpack-Issues#6240]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[disconnect-2024-11-22_22.03.48-client.txt](https://github.com/user-attachments/files/17878219/disconnect-2024-11-22_22.03.48-client.txt)

### Describe the bug

Upon being attacked by a mob or attacking a mob, I will sometimes be disconnected from my single player world, and taken back to the server browser menu. 

### Steps to reproduce

do combat with some mobs
(I've been using projectile harm spell from ars nouveau, but I have been disconnected upon being attacked by blazes, creepers, slimes, and zombies)

### Expected behaviour

to not be disconnected from my world unless I choose to disconnect

**Comment by alfredggttv** [comment]
This is due to an issue with the Explosive Enhancement mod. We are removing this until an update comes out to fix the issue.

https://github.com/Xylonity/Explosive-Enhancement-Reforged/issues/1
