### ISSUE TITLE
Antimony Ingots do not allow making of battery alloy

### ISSUE THREAD

**Issue by TBV** [FTBTeam/FTB-Modpack-Issues#6243]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

When you smelt Antimony Dust (FTB Resources) into Antimony Ingots (Modern Industrialization) the ingots are no longer able to be used for any battery alloy recipes. This is crucial for progressing through the machine stages, and should be easy enough to remedy. You can save this soft lock by only turning Raw Antimony into Antimony dust and then alloy smelting the dust with lead (By retaining the FTB Resources tag on the antimony dust), but no other recipe is like this so I believe it to be a bug. 

### Steps to reproduce

Raw Antimony> Antimony Dust> Antimony Ingots(No longer compatible in any form for battery alloy)

### Expected behaviour

Antimony ingots should be cross compatible with the recipes for Antimony Ingots/Dust that has FTB Resources mod tag.

### Screenshots

![Screenshot_2](https://github.com/user-attachments/assets/770adb76-5366-4b95-a79d-2f4e4ff3683b)
![Screenshot_3](https://github.com/user-attachments/assets/255bd547-4d37-4092-9f4a-7cf60cdc871e)

**Comment by alfredggttv** [comment]
Fixed this, and also added a recipe to convert MI Antimony to FTB Antimony should you need it.
