### ISSUE TITLE
Ritual of awakening not working

### ISSUE THREAD

**Issue by nervi27** [FTBTeam/FTB-Modpack-Issues#6244]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Ritual of Awakening doesn't create any golems.
When I try it on amethyst, the budding amethyst block simply disappears.
![bug2](https://github.com/user-attachments/assets/5c95e130-d668-4b40-b9af-bac19d0704cc)
![bug3](https://github.com/user-attachments/assets/da13af83-0102-476c-8bf0-ae2fa89b140b)
When I try it on GeOre's Budding nodes, the ritual keeps running, without transforming any block.
![bug1](https://github.com/user-attachments/assets/6658066d-b6d9-4149-bb54-91baf5b25045)

### Steps to reproduce

1. Go to any geode.
2. Place down Ritual Brazier.
3. Right click with Tablet of Awakening in main hand.
4. Right click with empty hands to activate.
5. The ritual does not create Golems of any kind.

### Expected behaviour

The ritual should transform a budding node into a Golem.

**Comment by serretta** [comment]
Me too, and seems a few others on the ftb discord are also struggling

**Comment by alfredggttv** [comment]
Cannot reproduce on the current dev build, assuming it is fixed due to a mod being updated. Let me know if you continue to see this issue!

**Comment by Rexei** [comment]
Im having this issue too on the latest direwolrf pack.  1.5.0
