### ISSUE TITLE
XP Vaccum

### ISSUE THREAD

**Issue by Gexx3300** [FTBTeam/FTB-Modpack-Issues#6245]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.1

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

XP Vaccum crafted with "activated" texture and doesn't allow XP too be put in too activate it nor does it pick up XP

### Steps to reproduce

1. Craft XP Vaccum
2. Try to use as intended 

### Expected behaviour

Suck up XP

**Comment by ArtpokeBr** [comment]
Hmmm, the XP Vacuum from EnderIO seems to be working normally in the latest version, if this still persists, let us know.
