### ISSUE TITLE
Hostile Neural Networks and Curios intergration

### ISSUE THREAD

**Issue by Ccconvict72** [FTBTeam/FTB-Modpack-Issues#6246]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

with having the deep learner from Hostile Neural Networks in the Curio slot any kills made do not count and if you try to open the deep learner with the hot key to add or remove a data model it will delete(for taking out) or duplicate(for adding to). 

### Steps to reproduce

1a. Put deep learner in Curio Slot
2a. Kill mobs that are associated with the model you currently have active
1b. Use hotkey to open the deep learner from curio slot
2b. insert or remove a model from the deep learner

### Expected behaviour

1a) Mob kills to count 1b) be able to switch out models

**Comment by ArtpokeBr** [comment]
Seems to be working in the latest version, let us know if this still persists though.
