### ISSUE TITLE
Possible Memory Leak in pack

### ISSUE THREAD

**Issue by Shadowfire86** [FTBTeam/FTB-Modpack-Issues#6247]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.1

### Launcher

FTB App

### Has the pack been modified

Yes

### Log Files

https://pastebin.com/z3tAmyVb, https://pastebin.com/rvRB9MhR. 

### Describe the bug

Lately I have a crash about every few minutes to 3 or 4 hours if I'm away, and either it reports a ticking LaserIO node, F3 shows 99% Memory Usage, or I get the attached Crashes. I HAVE recently started messing with computercraft, but I have never left any code running. One modification to pack is increased chunk loads from 25-75 through FTB Chunks.

### Steps to reproduce

Start Single Player world. 
Open to LAN (to let farms, reactors etc Run)
Lock Computer (Win+L)
Walk Away
Come back a few hours later
Crashed or just 1 frame per 5-10 minutes.

### Expected behaviour

.. Walk Away, Come back, Server still running, memory usage under 70%.

### Additional information

Would do screenshots of the F3, but it's lagging so bad my computer would probably catch on fire by the time it finished expanding from the sides of the screen.

**Comment by Shadowfire86** [comment]
Yeah. If I sit and watch the F3 screen, Allocated slowly crawls upwards until the limit and the memory usage does the same. I've tried as low as 6GB, and so far as much as 12. Same result.

**Comment by maraudir** [comment]
I too experience these issues.

**Comment by ArtpokeBr** [comment]
Hmmm, not entirely sure if this till persists or not, but please, if it does, let dire know in his issue tracker [here](https://github.com/Direwolf20-MC/LaserIO/issues)

**Comment by Shadowfire86** [comment]
As of last week, it does. I had to migrate my world to a server I both host and access from my own computer to avoid the issue. It does indeed appear to likely be related to the "Open to LAN" feature.
