### ISSUE TITLE
[Bug]: Some items duplicate when using a cardboard box

### ISSUE THREAD

**Issue by ralmeida** [FTBTeam/FTB-Modpack-Issues#625]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Describe the bug

Using a cardboard box on a basic krate or diamond chest (maybe any chest) will duplicate (from just playing the game)
- Charged Certus Quarts Crystals
- Wyvern Pickaxes 

This is happening EVERY time I use the cardboard box.

### Steps to reproduce

1) Have one or more of the items in a chest (it happened to me on Basic Krate and a Diamond Chest)
2) Put a cardboard box on the chest
3) the Duplicated items will pop out

### Expected behaviour

Items should not just duplicate

### Screenshots

BEFORE 
![2022-02-15_17 08 46](https://user-images.githubusercontent.com/167082/154157948-eef853b4-70b0-4b48-aa88-e953d41eea87.png)

AFTER using a Cardboard Box
![2022-02-15_17 10 30](https://user-images.githubusercontent.com/167082/154158193-1fc3367a-2326-41df-a504-0f10cbe1c8fd.png)

**Comment by Raidobw2** [comment]
Hi, thanks for the report. This problem is already listed at #33, so I will keep only that other one, closing this current issue.
The bug is fixed in the newest version of Mekanism, which will come in the next modpack update.
