### ISSUE TITLE
Unable to launch Direwolf 1.21 modpack

### ISSUE THREAD

**Issue by Freikugel-012** [FTBTeam/FTB-Modpack-Issues#6253]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.1

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

ORIGINAL MODPACK LOGS
https://pastebin.com/5RaLJXd3

MODIFIED LOGS (INTERGRATED DYNAMICS UPDATED TO LATEST)
https://pastebin.com/840thnrX

### Describe the bug

Game does not launch and has a chance to cause either memory management bsod or kernel security check failure bsod

### Steps to reproduce

1. launch app
2. click play on modpack
3. game crashes. if not
4. game goes to mojang loading screen and either CTDs or BSODs

### Expected behaviour

game launches fine

### Screenshots

N/A

**Comment by Freikugel-012** [comment]
just tried to load the pack now and got a "attempted to write to read only memory" BSOD

**Comment by WyFryMU** [comment]
What CPU do you have?

**Comment by Freikugel-012** [comment]
I have a 12700kf, no undervolt and no overclock. Howeved E cores are disabled

**Comment by ArtpokeBr** [comment]
If this still persists on the newest version, let us know, Integrated Dynamics was updated to its latest version so you shouldn't need to this manually anymore btw ;)
