### ISSUE TITLE
Quest Reward for Chaos Dragon Ore Vein Causes Crash

### ISSUE THREAD

**Issue by GoddessViolet** [FTBTeam/FTB-Modpack-Issues#6258]
### Modpack

FTB Interactions Remastered

### Modpack version

1.1.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

https://mclo.gs/l0HU501

### Describe the bug

Completing the quest "" rewards a Wyvern Broad Blade, and 32 of "something." It has no name, and once it's in your inventory, trying to open your inventory causes a crash. I don't know what it's *supposed* to be, but I'd like for it to either be out of my inventory, or alternatively, to just not crash the game when collected.

### Steps to reproduce

Complete the "Chaos Dragon Veins" quest
Accept quest rewards
Open inventory
Cry

### Expected behaviour

Based on the crash report, it's probably supposed to be a cable of some kind?

**Comment by Gaz492** [comment]
If you can upload your playerdata file for me I can have a go at fixing your inventory for you. The player data can be found in the `saves\<world name>\playerdata` folder and will be have the file name of your UUID, you can use https://mcuuid.net/ to find your UUID

**Comment by GoddessViolet** [comment]
[playerdata dot zip.zip](https://github.com/user-attachments/files/17909681/playerdata.dot.zip.zip)

In hindsight I definitely should've just, y'know. Not clicked on it? But that would mean leaving a quest reward just sitting in the ether, unclaimed, taunting me.

**Comment by Gaz492** [comment]
Ohh, I will let someone know that there are beta version hiding, they should be marked as release.

Also hopefully this should have your inventory fixed
[playerdata.zip](https://github.com/user-attachments/files/17915727/playerdata.zip)

**Comment by GoddessViolet** [comment]
It _didn't_, on account of the game not wanting to load without the original, unmodified playerdata folder, lmao. Fortunately I managed to actually destroy the offending glitch item in-game through some shenanigans. And since the quest reward seems to already be fixed in 1.10, I'm gonna just close this one down.

Man. All this over what should've just been some platinum cables, eh? Seems aggressively not worth it.
