### ISSUE TITLE
Advancements Not Showing

### ISSUE THREAD

**Issue by SavannahSchl** [FTBTeam/FTB-Modpack-Issues#6261]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.21

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

My achievements tab isn't working, it's just fuzzy and shows a little icon and that's it, nothing else.

### Steps to reproduce

Clicking escape
Clicking achievements tab

### Expected behaviour

Being able to see achievements

### Screenshots

![IMG_4816](https://github.com/user-attachments/assets/03200112-48a4-44ad-af22-5e8657048049)

**Comment by ArtpokeBr** [comment]
Are you running the latest update of the pack? if this still persists, let us know.

**Comment by yy214** [comment]
Same issue with FTB Direwolf 1.8.2 (latest), noticed the bug recently after not opening my advancements tab for a while.

Suspected issues:
- 2 pages of advancements (previously only had 1 if I remember properly)
- screen aspect ratio (was 1920x1080, now using 2736x1824)

![2024-12-29_21 53 05](https://github.com/user-attachments/assets/a43437b9-9a29-4b2c-ab37-59707eefd739)
