### ISSUE TITLE
Add info about Statues needing power to quest

### ISSUE THREAD

**Issue by melbellrocks** [FTBTeam/FTB-Modpack-Issues#6264]
### Modpack

FTB Evolution

### Is your suggestion related to a problem? Please describe.

Might be handy to have a quick mention in the Statue quest that the statues require power to work.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated the FTB Evolution option in the modpack dropdown to include a note about statues requiring power to work. This addresses the user's suggestion to mention this information in the Statue quest.

You can review changes in this commit: https://github.com/lkilu6456546/FTBTeam-FTB-Modpack-Issues-6264/commit/1e46d4579164681e971f911f7b604e00de2bf6d1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Saereth** [comment]
Brilliant Solution lmao

**Comment by ArtpokeBr** [comment]
![image](https://github.com/user-attachments/assets/28a20d66-a75d-47b4-97ff-f271cc7a5f6a)

lol, fixed.
