### ISSUE TITLE
Conflicting recipes

### ISSUE THREAD

**Issue by Corn-man** [FTBTeam/FTB-Modpack-Issues#6265]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.50

### Launcher

ATLauncher

### Has the pack been modified

No

### Describe the bug

The elevators share the same recipe with another item. 
![image](https://github.com/user-attachments/assets/fd2b5d0c-d50b-4e9c-aaf7-ce829957101d)

### Steps to reproduce

1. Go to crafting table. 2. Put ender pearl in center with wool around it. 3. Should be elavator as the result, but its a pouch.

### Expected behaviour

Should create an elevator 

### Screenshots

![image](https://github.com/user-attachments/assets/7e9d59dd-c397-4b48-b9e6-3c865bb288f5)

**Comment by Corn-man** [comment]
This is the recipe in JEI
![image](https://github.com/user-attachments/assets/d003da11-e929-4aad-9712-91259967d3b1)

**Comment by ArtpokeBr** [comment]
This have been fixed in the latest version of the pack :)
