### ISSUE TITLE
No Custom Menu Screen

### ISSUE THREAD

**Issue by linuxchr** [FTBTeam/FTB-Modpack-Issues#6268]
### Modpack

FTB Skies Expert

### Modpack version

1.10.0

### Launcher

ATLauncher

### Has the pack been modified

No

### Log Files

https://paste.atlauncher.com/view/831d9e8d-7df8-4d5e-baee-49d5d6fd421f

### Describe the bug

Mojang loading bar is red.
Fancy Menu Screen at the start.
Not FTB  Selection menu.

### Steps to reproduce

Install in ATLauncher.
Start Minecraft.

### Expected behaviour

The same as with FTB Launcher. Blue Loading Bar. No Fancy Menu at start. Ftb Multiplayer and Singleplayer selection menu.

### Screenshots

![grafik](https://github.com/user-attachments/assets/cd3a634d-e8fd-46ad-8aeb-cd0927597bcc)
![grafik](https://github.com/user-attachments/assets/994d5e47-37ce-40d1-bf60-0a3305aa688d)

**Comment by Gaz492** [comment]
Could you try repairing the modpack or reinstalling it?
It seems some files were not downloaded when the pack was installed/updated.

**Comment by linuxchr** [comment]
Already tried repairing and reinstalling it multiple times.

**Comment by linuxchr** [comment]
Only ATLauncher has this problem, FTB and Prism not.

**Comment by Gaz492** [comment]
Ok, it sounds like they may not be downloading something or not putting a file in the correct place.
You will need to report this issue to ATLauncher as there is nothing we can do if the FTB App and Prism works as it sounds like a launcher specific issue.

**Comment by linuxchr** [comment]
Its a new issue with the 1.10 version of skies

**Comment by Gaz492** [comment]
So I had a quick look at ATLauncher and it looks to be downloading files to the wrong place, if you open the FTB Skies Expert folder that ATlauncher creates, you can see that there are a lot of files that start with config/defaultconfig and so on, these should be in folders named config/defaultconfig ect, so its not creating/putting the downloaded configs and assets into the correct place.
