### ISSUE TITLE
Worn backpack contents moving to placed backpack

### ISSUE THREAD

**Issue by FreetheFr0gs** [FTBTeam/FTB-Modpack-Issues#6273]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

Player on my server is having their backpack's content "deleted." After the first time it happened we figured it was something to do with a server rollback, however we just found the contents that were originally in the backpack they were wearing, inside of a placed backpack in another player's base that had never been visited. TLDR: Player's backpack contents are getting moved to a placed backpack upon login

This has happened twice and I'm unsure of exactly how to replicate it

### Steps to reproduce

Backpack placed in world
Backpack worn on player
Player leaves and rejoins server

### Expected behaviour

Contents of worn backpack moves to placed backpack

### Additional information

freethefr0gs on discord if you want me to test anything further, i do not check github regularly at all

**Comment by alfredggttv** [comment]
This seems like it might be related to this issue here: https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/1127

It might be the issue with UUIDs being duplicated. Did this happen to a new backpack that you created?

**Comment by FreetheFr0gs** [comment]
I can't say for sure but it's very possible (and most likely) that they were both backpacks that we got from loot chests

**Comment by sirjoekcb** [comment]
I just had the same thing happen where I was given a backpack as a random quest reward and it was one that an offline player had been wearing. When they logged in they had an empty backpack

**Comment by P3pp3rF1y** [comment]
Took a look and I am pretty sure these backpacks came from quests as there are 3 defined in quests that include UUID, which means that all players that get these initially get the same ID for that backpack until two of them are online at the same time and UUID dedupe logic assigns new ID to one of them.

These backpacks in quests need to have their `sophisticatedcore:storage_uuid` components removed for this to not happen.
```
		{ item: { components: { "sophisticatedcore:number_of_inventory_slots": 27, "sophisticatedcore:number_of_upgrade_slots": 1, "sophisticatedcore:render_info_tag": { upgradeItems: [{ }] }, "sophisticatedcore:storage_uuid": [I; 1945932756, 501369058, -1944435234, -266669644 ] }, count: 1, id: "sophisticatedbackpacks:backpack" }, weight: 25.0f }
		{ item: { components: { "sophisticatedcore:number_of_inventory_slots": 54, "sophisticatedcore:number_of_upgrade_slots": 2, "sophisticatedcore:render_info_tag": { upgradeItems: [ { }, { } ] }, "sophisticatedcore:storage_uuid": [I; -969483764, -617528243, -1428852339, -1571954954 ] }, count: 1, id: "sophisticatedbackpacks:iron_backpack" }, weight: 10.0f }
		{ item: { components: { "sophisticatedcore:number_of_inventory_slots": 81, "sophisticatedcore:number_of_upgrade_slots": 3, "sophisticatedcore:render_info_tag": { upgradeItems: [ { }, { }, { } ] }, "sophisticatedcore:storage_uuid": [I; 1086987800, 508774838, -1337358257, -63102458 ] }, count: 1, id: "sophisticatedbackpacks:gold_backpack" } }
```

**Comment by alfredggttv** [comment]
Interesting. I removed the UUID from the backpacks given out as a reward before, but this must be a bug with ftb quests not saving nbt data on rewards. I've had a few issues with NBT data not saving as rewards (mostly with Fluid Tanks), so I'll probably be removing these as quest rewards for now.

Thanks for pointing it out!
