### ISSUE TITLE
Gameworld freeze when attempting to put Mekanism items in the Charging Gadgets Charging Station

### ISSUE THREAD

**Issue by Kribylet** [FTBTeam/FTB-Modpack-Issues#6278]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Putting a digital miner or energy cube from the mekanism mod into a charging gadgets charging station immediately freezes the world in single-player and multiplayer. In multiplayer, all players lose connection to the server and cannot reconnect.

### Steps to reproduce

1. Set up a charging station with power (not sure if power matters, but that's what I did)
2. Put a digital miner in the charging station
3. Gameworld freezes

### Expected behaviour

Charging Station charges the object or disallows it from being inserted.

### Additional information

I haven't exhaustively tested putting every Mekanism item into the charging station but there may be more cases like this.

**Comment by Gaz492** [comment]
Would you be able to upload the logs from the modpack so we can have a look at them?
A guide on finding the logs can be found at: https://docs.feed-the-beast.com/docs/app/Instances/instance-logs

**Comment by ArtpokeBr** [comment]
Yeah, tested with both blocks you've mentioned, might be a good idea to report this to Dire [here](https://github.com/Direwolf20-MC/ChargingGadgets/issues) =)

**Comment by ArtpokeBr** [comment]
@Gaz492 Here's the Log btw https://paste.feed-the-beast.com/view/9daed7a6
