### ISSUE TITLE
[Bug]: comparator doesnt get signal from blood altar when using redstone lamp below it.

### ISSUE THREAD

**Issue by SirDragonKnight** [FTBTeam/FTB-Modpack-Issues#628]
### Modpack

FTB University 1.16

### Modpack version

1.4.0

### Describe the bug

Comparator for bloodstone alter is not working when using a redstone lamp below the altar.

### Steps to reproduce

1. have a Blood alter down with some life essence in it.
2. setup a comparator off of the altar. (signal will work )
3. add a redstone lamp below the altar (this is used to signal when alter has finished crafting something)
4. comparator no longer get a signal from altar at this point.

### Expected behaviour

comparator should measure how much life essence is in alter when using redstone lamp below altar.

### Additional information

Not sure if this is a Modpack or mod issue, so submitting it here.

**Comment by aaronhowser1** [comment]
*Fascinating.* WayofTime/BloodMagic/issues/1882

**Comment by aaronhowser1** [comment]
This is apparently intended behavior. Placing a lamp under it replaces the comparator functionality, so it emits a pulse when it's done. You can't have both at once.
