### ISSUE TITLE
coliseum hangs game

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6280]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.5.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Getting near an Iron's Spells and Spellbooks (???) coliseum structure in normal difficulty causes the game to hang indefinitely.

### Steps to reproduce

1. Find a coliseum structure.
2. Get close enough to the structure or press a button in it in peaceful.
3. Game hangs.

### Expected behaviour

game should not hang

**Comment by ArtpokeBr** [comment]
Hmm this doesn't seem to be happening the current version 1.7.0, at least from what I've tested.

So if the issue still persists on your side, please re-open this issue.
