### ISSUE TITLE
no uses for Railcraft Reborn sulfur

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6285]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.5.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Railcraft Reborn sulfur is obtainable but has no uses.

### Steps to reproduce

1. Attempt to look up uses for Railcraft Reborn sulfur in JEI.
2. No results.

### Expected behaviour

sulfur should be sulfur

**Comment by KZumbusch** [comment]
I also got a bunch of sulfur from Railcraft Reborn from automated mining and first I had no clou how, but I finally found out how to obtain it: mining Sulfur Ore from Railcraft Reborn gets you Mekanism's sulfur dust while mining Deepslate Sulfur Ore from Railcraft Reborn gets you Railcraft Reborn's sulfur which is not listed in JEI at all and cannot be used in any recipe. And I also don't see any Railcraft Reborn related recipes for Mekanism's sulfur dust. Should there be any suitable recipes from Railcraft Reborn that use sulfur?
