### ISSUE TITLE
Railcraft Reborn Iron Tank Bug

### ISSUE THREAD

**Issue by Bashy311** [FTBTeam/FTB-Modpack-Issues#6288]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.2.2

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

Normaly if you craft the Railcraft Reborn Iron Tank u place a Multiblock and if you are finished its a usable block. 
The Bug is, if you try to connect a pipe or place/break a block near the Tank it will go back to the mutliblock "Stage"

### Steps to reproduce

Place a Iron Tank Multi Block 
Try to connect anything 

### Expected behaviour

Usable Tank will go back to Multiblock stage

### Screenshots

![2024-11-29_00 13 46](https://github.com/user-attachments/assets/c98c5128-953c-489b-b95d-b9922d32be0f)
![2024-11-29_00 14 17](https://github.com/user-attachments/assets/c81c7860-4923-4b09-9b3e-c4093280bf7d)

**Comment by ArtpokeBr** [comment]
![image](https://github.com/user-attachments/assets/51a6edc4-0efb-41cf-8459-8348df1042ae)
Seems to be working on the latest version, if you're still encountering this issue, please reopen this issue.
