### ISSUE TITLE
LaserIO Advanced laser connectors not linking together

### ISSUE THREAD

**Issue by Carlcamp** [FTBTeam/FTB-Modpack-Issues#6289]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

laserio advanced laser connectors not connecting to each other.

### Steps to reproduce

place 2 alc ,use wrench on both and nothing happens, just a red line, no green color change, no cords, just this.
in case you're wondering ,yes the node is linked to the alc.

### Expected behaviour

to have them link like they normally would.

### Screenshots

![Screenshot 2024-11-28 180141](https://github.com/user-attachments/assets/04b54332-8189-44f9-aa2d-f69943bfd081)

### Additional information

im on a server.

**Comment by Jaeiya** [comment]
This is because of shaders. All of direwolfs mods have some issues with rendering certain things under shaders.

**Comment by Carlcamp** [comment]
that would explain why other mods are not have there animations work ether. 
would the shaiders affect the display of where there connected to when hovering over the connector?

**Comment by Jaeiya** [comment]
Yes, it will not display the coords, you would have to turn off shaders to see the coords. Seeing the laser go up in the air like that, is the only indicator you have (when shaders are enabled) that it's connected.

**Comment by Carlcamp** [comment]
gotcha, thanks for the reply.
