### ISSUE TITLE
[Suggestion]: Replace ReAuth with Oauth

### ISSUE THREAD

**Issue by Targren** [FTBTeam/FTB-Modpack-Issues#629]
### Modpack

FTB Oceanblock

### Is your suggestion related to a problem? Please describe.

In a few weeks, Microsoft Account migration will no longer be optional ([Announcement](https://www.minecraft.net/en-us/article/last-call-voluntarily-migrate-java-accounts)), and ReAuth doesn't support Microsoft Accounts. 

### Mod suggestion

The [OAuth mod](https://www.curseforge.com/minecraft/mc-mods/oauth) does support relogging in to Microsoft accounts (or purports to, at least)

**Comment by Sunekaer** [comment]
Hi,
ReAuth has been updated to support Microsoft, so we will just be updating.
