### ISSUE TITLE
Golden Egg doesn't spawn vanilla mobs

### ISSUE THREAD

**Issue by Migraine78** [FTBTeam/FTB-Modpack-Issues#6291]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.50

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Golden Egg doesn't seem to spawn vanilla mobs

### Steps to reproduce

Use golden egg.

### Expected behaviour

spawn chicken / sheep / cows ect.

**Comment by ArtpokeBr** [comment]
![image](https://github.com/user-attachments/assets/ed796384-e2a1-45ca-a42a-775b910fc67d)
Seems to be working on the latest version, but if this still happens with you, make sure to reopen this issue.
