### ISSUE TITLE
request for addition of mods in ftb oceanblock.

### ISSUE THREAD

**Issue by Deepakqw** [FTBTeam/FTB-Modpack-Issues#63]
please add modular routers and rs infinity booster or ae2 wireless terminal mods for infinite range.
please change simply backpacks with sophisticated backpacks.

**Comment by brendon0203** [comment]
I was thinking something like this would be awesome. An AE2 expansion. I would kill for some larger AE2 cells. I

But it appears that the Extra Cells mod hasn't been updated since ~1.12 unfortunately which I',m pretty sure where all that stuff came from.

**Comment by Sunekaer** [comment]
Suggestion template not used.
Please open a new suggestion using the template.
