### ISSUE TITLE
the Rocket failed to ignite fix ?

### ISSUE THREAD

**Issue by DasCxbweb** [FTBTeam/FTB-Modpack-Issues#6305]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.11.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I think it is ment to  be like that but i just wanted to know how i can change that to normal. 
Im in the early game of Legend of the eyes and want to use rockets with my elytra but if i try it just says ,,the Rocket failed to ignite,,
I think that is because i will unlock this later in progress but i want to change it to normal from the begining.
can anyone help i would really aprecheate it 

### Steps to reproduce

as said

### Expected behaviour

as said

### Screenshots

.

### Additional information

...

**Comment by Gaz492** [comment]
If you open the folder where you have the modpack installed then open kubejs -> server_scripts > playerhandler.js.

Find 
```js
// Disable Firework Rockets
ItemEvents.rightClicked('minecraft:firework_rocket', event => {
    const {player} = event
    if (player.persistentData.eyecounter <= 11){
        event.cancel()
        if (player.getChestArmorItem().toString().contains('elytra') ||
            player.getChestArmorItem().toString().contains('modular')) player.tell('The Rocket fails to ignite.')
    }
})
```
and replace it with 
```js
// Disable Firework Rockets
// ItemEvents.rightClicked('minecraft:firework_rocket', event => {
//     const {player} = event
//     if (player.persistentData.eyecounter <= 11){
//         event.cancel()
//         if (player.getChestArmorItem().toString().contains('elytra') ||
//             player.getChestArmorItem().toString().contains('modular')) player.tell('The Rocket fails to ignite.')
//     }
// })
```

If you then start the modpack up rockets should be enabled
