### ISSUE TITLE
menril leaves are not blue on map

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6308]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.5.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

see title

### Steps to reproduce

1. Find a menril tree.
2. Look at map - leaves are default green.

### Expected behaviour

blue leaves should be blue on map

**Comment by Gaz492** [comment]
This should be fixed in the next pack update that updates FTB Chunks
[](!skip)

**Comment by ArtpokeBr** [comment]
Yup, this have been fixed already =)
