### ISSUE TITLE
FTB Evolution Installer for Linux Version 1.3.0 (x64) wants to install 1.2.0

### ISSUE THREAD

**Issue by hofq** [FTBTeam/FTB-Modpack-Issues#6309]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

Server

### Has the pack been modified

No

### Log Files

![grafik](https://github.com/user-attachments/assets/bae33d48-1e00-4b05-8c04-3305403594bf)
![grafik](https://github.com/user-attachments/assets/39e183d0-fbb4-40fe-ad25-c9730cdbc020)
Filename: serverinstall_125_12629

### Describe the bug

The Server asks me to install 1.2.0 of the modpack. I want and selected 1.3.0

### Steps to reproduce

Go to the Modpack site
Go to Version
Click Linux in x64 section

### Expected behaviour

It installs 1.3.0

**Comment by Gaz492** [comment]
From the screenshot you posted it looks like you have an old version of the server installer.
Could you try either going to https://feed-the-beast.com/modpacks/125-ftb-evolution?tab=versions hard refreshing the page pressing <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> or go to https://feed-the-beast.com/modpacks/server-files and download the file from there

**Comment by hofq** [comment]
seemed fine on latest version
