### ISSUE TITLE
Add Direwolf20 v1.5.0 to curseforge

### ISSUE THREAD

**Issue by FelixHe** [FTBTeam/FTB-Modpack-Issues#6312]
### Modpack

FTB Presents Direwolf20 1.21

### Is your suggestion related to a problem? Please describe.

Currently I'm using docker to deploy the newest version of the modpacks. The newest version of the direwolf20 pack is 1.5.0 now but that version is only deployed to FTB currently and not to curseforge. The docker image I'm using uses the following API to retrieve the versions: https://api.modpacks.ch/public/modpack/126

Thanks for your help in advance!

**Comment by framerunner** [comment]
I've had the same issue, despite pulling from FTB and not curse.
(I'm using itzg/minecraft-server to be more specific)
For now you can add "FTB_MODPACK_VERSION_ID" to your Env and set it to "100001" so it's forced to pull the latest version.
(Douplicate/Edit your container)
Make sure that "TYPE" is set to "FTBA", so you pull from FTB.

**Comment by FelixHe** [comment]
Yes, exactly. The startup log states: "Error fetching modpack: version does not exist" if I put the FTB_MODPACK_VERSION_ID 100001 in it.

**Comment by Gaz492** [comment]
We are working on getting the modpack uploaded to curseforge, we just need to update a few mods and wait for the version to be approved.

As for the issue you are having with your docker image, our API has changed, as an example the API url for DW20 1.21 is now https://api.feed-the-beast.com/v1/modpacks/public/modpack/126

**Comment by FelixHe** [comment]
Hi!
The docker image author (itzg/docker-minecraft-server) changed the API to use the new one you mentioned. Now it correctly gets the new version but when it tries to start the ftbinstaller with the newer modpack version ID it fails again with the message:
"ERROR fetching modpack: version does not exist"

What I could see is that the script tries to execute the following command on the shell:
ftb-installer "126" "100001" --noscript --auto > ftb-installer.log

That should be correct shouldn't it?

**Comment by Gaz492** [comment]
Ahh, they will also need to change some parameters on the server installer command as we also released a new version which changes it a bit.

I don't know if you can change the command or if the maintainer of the docker image needs to (i'm not familiar with that docker image).

The new command to run the installer would be `ftb-installer -pack "MODPACK_ID" -version "MODPACK_VERSION" -auto -force`
-no-script is no longer an option as it just modifies the standard forge/neoforge scripts that gets generated
-force is a new flag that just tells the installer to ignore any warnings that may require user input when using -auto

```
Usage of ./installer_125:
  -auto
        Dont ask questions, just install the server
  -dir string
        Installation directory
  -force
        Force the modpack install (only works with -auto)
  -latest
        Gets the latest version of the modpack
  -no-colours
        Do not use colours
  -no-java
        Do not install Java
  -pack int
        Modpack ID
  -provider string
        Modpack provider (Currently only 'ftb' is supported) (default "ftb")
  -skip-modloader
        Skip installing the modloader
  -threads int
        Number of threads to use (Default: CPU Cores * 2) (default 20)
  -validate
        Validate the modpack after install
  -verbose
        Verbose output
  -version int
        Modpack version ID, if not provided, the latest version will be used
```

**Comment by FelixHe** [comment]
Thanks for your very quick reply!
I forwarded this issue and your comment to the author of the docker image and hope he could implement the new parameters.

Thanks!

**Comment by ArtpokeBr** [comment]
This seems to have been fixed, so I'am going to close the issue =)
