### ISSUE TITLE
clay, glowstone, nether quartz, and amethyst blocks are not uncraftable

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6314]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.5.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

In previous DW20 packs, some block reversal recipes were added for items/blocks like these, presumably so they would work in simple compacting drawers. These convenient recipes are absent in the MC 1.21 pack.

### Steps to reproduce

1. Place any blocks from title in the top of a simple compacting drawer.
2. "Fragment" form of blocks is not available.

### Expected behaviour

these reversal recipes should be present, as they are required for these items/blocks to work in simple compacting drawers

**Comment by BDTheNerdyMedic** [comment]
Probably not needed, but I'd already written this code for my modpack.

```javascript
ServerEvents.recipes(event => {
    const decompressions = [
        { block: 'minecraft:quartz_block', item: 'minecraft:quartz', amount: 4 },
        { block: 'minecraft:amethyst_block', item: 'minecraft:amethyst_shard', amount: 4 },
        { block: 'minecraft:clay', item: 'minecraft:clay_ball', amount: 4 },
        { block: 'minecraft:glowstone', item: 'minecraft:glowstone_dust', amount: 4 },
        { block: '#minecraft:wool', item: 'minecraft:string', amount: 4 },
        { block: 'minecraft:honeycomb_block', item: 'minecraft:honeycomb', amount: 4 }
    ];

    decompressions.forEach(entry => {
        event.shapeless(Item.of(entry.item, entry.amount), [entry.block]);
    });
});
```

**Comment by jlp1528** [comment]
So I decided to try these in a simple compacting drawer anyway and quartz, glowstone, and amethyst all work, while clay does not. I thought compatibility with drawers was based on having both block and item recipes. Clay should definitely have a recipe and work in drawers, since it's just break blocks for 4 items.

**Comment by ArtpokeBr** [comment]
@BDTheNerdyMedic, Thanks for the contribution, I've added your snippet of code to the pack, with the correct credits of course.

But I did remove the Wool to String Recipe as I feel it OP hehe :p
