### ISSUE TITLE
two different ancient debris processing recipes visible in JEI for Mekanism enrichment chamber

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6316]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.5.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

See title and screenshot. Currently, 1 ancient debris produces 5 netherite scrap dust.

### Steps to reproduce

1. Look up ancient debris uses in enrichment chamber
2. Observe two different recipes (first is correct).

### Expected behaviour

one and only one recipe for processing ancient debris in enrichment chamber

### Screenshots

![image](https://github.com/user-attachments/assets/0c09c41a-9794-468a-8fee-618f78747a90)

**Comment by ArtpokeBr** [comment]
Fixed for both Packs =)
