### ISSUE TITLE
some building gadget modes are incorrectly offset

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6317]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.5.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

see title and screenshot

### Steps to reproduce

1. Use cut paste gadget or building gadget in stairs mode (may be other modes, probably applies to all gadgets)
2. Observe offset.

### Expected behaviour

no offset

**Comment by Gaz492** [comment]
Hi,

Would you be able to explain a little more about what you mean the offset is incorrect?

**Comment by jlp1528** [comment]
I understand that this might be intended for stairs, but the copy paste gadget was acting really weird. Now I can't get it to happen again. Maybe something was set wrong? Either way I'm closing this issue as it seems to have resolved itself.
