### ISSUE TITLE
Game chrashes when i manually jump.

### ISSUE THREAD

**Issue by LeviP146** [FTBTeam/FTB-Modpack-Issues#632]
### Modpack

FTB ultimate anniversary edition

### Modpack version

1.3.0

### Log Files

-

### Describe the bug

I have a problem with the ftb anniversary edition mc mod. It randomly started some days back when i logged in to my server. I was walking around but when i jumped the game crashed. I can do anything else. I can dig, ride a boat, hit mobs, i can jump with auto-jump on but when i manually jump the game crashes and it shows exit code -1 . I have been struggling with this problem now for days and it isn't because of the space bar.
(I don't know why that would be the problem, but i just really want to play my game normally so i tried everything)
Im not really an expert at these things so i hope you would like to help.

### Steps to reproduce

I don't know how i got it.

### Expected behaviour

I expected my minecraft to work normaly and not crash when i manually jump.

### Screenshots

-

### Additional information

I already told everything.

**Comment by MichaelHillcox** [comment]
Provide a crashlog...

**Comment by RyePL** [comment]
I have an identical issue, though it's for 1.2.0 since the pack would not launch at all in 1.3.0. Here is the crashlog

https://pastebin.com/4tpZyeKA

**Comment by LeviP146** [comment]
> I have an identical issue, though it's for 1.2.0 since the pack would not launch at all in 1.3.0. Here is the crashlog
> 
> https://pastebin.com/4tpZyeKA

My minecraft jumping works again. I don't know if it works for you but i just downgraded the version back to 1.2.0 and then back to 1.3.0 and i could jump normaly again without crashing. maby you should try to downgrade to 1.1.0 and back 1.2.0 then.

**Comment by Raidobw2** [comment]
#630
