### ISSUE TITLE
Ftb evolution ars nouveau ritual of awakening not working.

### ISSUE THREAD

**Issue by schristofersen** [FTBTeam/FTB-Modpack-Issues#6324]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

ATLauncher

### Has the pack been modified

No

### Describe the bug

Ars nouveau ritual of awaking doesn’t seem to work. It runs but does not produce an amethyst golem, similarly it runs but does not complete on geore budding blocks, it will run and complete on archwood trees but produces no wold. 

### Steps to reproduce

Use ritual of awakening on budding amethyst, budding geore, or archwood tree. Does seem to work for bookwyrm charms. 

### Expected behaviour

Produce amethyst golem charm or wold.

**Comment by alfredggttv** [comment]
This has been reported before, but I can't seem to replicate the issue. Whenever I do the ritual, everything works like normal and a GeOre Golem is spawned (or an Amethyst Golem).

The only Weald I couldn't create was from a "Flashing" one, but that's from Ars Elemental. If you could update to 1.4.0 and let me know if you still the issue, we can crack down on it!

**Comment by Cooper-McKinlay** [comment]
> This has been reported before, but I can't seem to replicate the issue. Whenever I do the ritual, everything works like normal and a GeOre Golem is spawned (or an Amethyst Golem).
> 
> The only Weald I couldn't create was from a "Flashing" one, but that's from Ars Elemental. If you could update to 1.4.0 and let me know if you still the issue, we can crack down on it!

I was having the same issue of amethyst golem not spawning with 1.3.0, but since updating to 1.4.0 it seems to be functioning,
