### ISSUE TITLE
Formation plane not working

### ISSUE THREAD

**Issue by Skyknight46** [FTBTeam/FTB-Modpack-Issues#6325]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.5.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

AE2 formation plane not working when online and hooked up to a system that contains the filtered items

### Steps to reproduce

1. Set up a (small) ae2 network containing some items
2. Place a formation plane 
3. Try to place/drop those items

### Expected behaviour

Formation plane drops/places filtered items when they're inside the ae2 network

### Screenshots

![afbeelding](https://github.com/user-attachments/assets/25e21fdb-ccaf-47a4-9e56-c0fb415bf21e)
formationplane settings
![afbeelding](https://github.com/user-attachments/assets/aaf2c031-c05c-44d8-b09e-998d98a058f1)
AE2 network the plane is hooked up to

### Additional information

I don't know if this is the case but I have a feeling it has to do with something along the lines of the pack not recognizing the original player anymore since the latest update creating a new player with the same id. This because since the last update I'm seeing myself on the map twice (once as a white arrow and once as my player head). I also had to re-bind my player transmit module of Powah after the update

**Comment by ItMeCorban** [comment]
I've encountered a similar bug with them not placing - I have a tree farm and a latex extractor setup, the formation pane is set to place oak logs but once it's broken another isn't placed until I take out/insert an oak log from the system, simply clicking on the stack and putting it straight back in causes the formation pane to trigger again
I am however still on 1.4.1 so possibly not relevant in 1.5

**Comment by ArtpokeBr** [comment]
Hmmm can you guys confirm that this is also happening on the latest pack version? If so, please make sure to report this in the [Official AE2 Issue Tracker](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues), as it might be something for them to fix.

**Comment by ItMeCorban** [comment]
Will do when I update - just to add I've since noticed the formation pane only places when the items is inserted into the network, removing any doesn't cause it to place, even if there are more in the system

**Comment by Skyknight46** [comment]
I have been testing it today (latest version of the pack) and this behavior still seems to occur. Although I have noticed that it does place when you start messing with the priorities. So unfortunately having to mess with subnets and priorities seems to be the intended functionality. Luckily I've managed to find a workaround using an export bus into a placer to achieve the same result.
