### ISSUE TITLE
Pistons make me and some of my friends get kicked from the server 

### ISSUE THREAD

**Issue by Dennis7042** [FTBTeam/FTB-Modpack-Issues#6327]
### Modpack

Other...

### Modpack version

Vanilla 1.21.1 neoforge 21.1.80

### Launcher

CurseForge

### Has the pack been modified

Yes

### Log Files

[disconnect-2024-12-04_19.55.26-client.txt](https://github.com/user-attachments/files/18014933/disconnect-2024-12-04_19.55.26-client.txt)

### Describe the bug

We have a vanilla minecraft Server 1.21.1 Version with neoforge 21.1.80 with some quality of life mods they are listed in the.txt above everytime a piston is activated me and some of my friends getting kicked of the server no matter if chunks are claimed or not but only if we near by

### Steps to reproduce

Activate piston 

### Expected behaviour

Not get kicked

**Comment by jlp1528** [comment]
This is not the place to report issues with custom made mod packs. This is for FTB modpacks only. Try Reddit.
