### ISSUE TITLE
Ring of expulsion particles cause a network protocol error

### ISSUE THREAD

**Issue by Tomska95** [FTBTeam/FTB-Modpack-Issues#6337]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

Prism

### Has the pack been modified

No

### Log Files

https://pste.ch/buqidewuwe.md

### Describe the bug

When the effect of the ring triggers and the player (or some other player nearby) is looking slightly down from horizontal the game runs into an error while trying to render the particles and disconnects from the server (affects single player as well) with a Network protocol error.

The provided log file ends in a disconnect and there are a couple other disconnects further up as we were testing the conditions for the bug to occur. I made a report here first as I can't deduct from the log file if the issue is with Iron's spells or if this is caused by a conflict.

This issue was tested on 2 separate systems both in multiplayer and singleplayer and we are able to reliably reproduce it on both machines.

### Steps to reproduce

1. Equip ring of Expulsion
2. keep your camera pointed slightly down (We haven't managed to trigger it while looking up or straight down)
3. take damage from a source that triggers the passive air burst of the ring
4. You are now most likely disconnected from the server

### Expected behaviour

The particle doesn't cause a critical error and the player can continue fighting after taking damage

### Additional information

I can provide a video/screenshots later if reproducing the bug ends up being an issue.

**Comment by wpetrowski** [comment]
Seconding this one - I encountered this as well on 1.3.0.

**Comment by x-kazumi** [comment]
same here. was hitting my friend to test some stuff and after 3-4 of those explosions i got thze particle error. see log below.

[disconnect-2024-12-06_11.36.58-client.txt](https://github.com/user-attachments/files/18036855/disconnect-2024-12-06_11.36.58-client.txt)

**Comment by alfredggttv** [comment]
This is fixed in the latest version, 1.4.0.
