### ISSUE TITLE
[Bug]: FTB Infinity Evolved Skyblock

### ISSUE THREAD

**Issue by Kai29100** [FTBTeam/FTB-Modpack-Issues#634]
### Modpack

FTB Infinity Evolved Skyblck

### Modpack version

2.0.1

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8104781/latest.log)

### Describe the bug

every time I start FTB Infinity Evolved Skyblock with FTB launcher it hangs at Phase 3/Mantle

### Steps to reproduce

1.Go at FTB launcher
2.Downlod FTB Infinity Evolved Skyblock v.2.0.1
3.Start FTB Infinity Evolved Skyblock

### Expected behaviour

that i can play FTB Infinity Evolved Skyblock

**Comment by Raidobw2** [comment]
Hi, we have a fix in the FTB Discord for it in the "infinity-evolved" channel until myself or a colleague is able to update it. Here's the fix below:

> Fix and info for FTB Infinity Evolved Skyblock v2.0.1 on the FTB App (user/server).
> You might encounter a bug during "Initializing mods Phase 3" where it stops at "5/7" during "Post Initialization - Ex Compressum".
> 
> Users: you have two options to solve this, choose only one:
> Option 1: In the `/mods` folder, you need to replace the old `excompressum-mc1.7.10-1.1.149.jar` with the newer `excompressum-mc1.7.10-1.2.0.jar` found on CurseForge (https://www.curseforge.com/minecraft/mc-mods/ex-compressum/files/all). Don't forget to delete the old file and leave only the newer version.
> Option 2: In the `/config` folder, locate and edit the file `excompressum.cfg` with a text editor and change to true in the following line: `B:"Skip Auto Sieve Skins"=false` becomes `B:"Skip Auto Sieve Skins"=true`.
> 
> Both fixes will require you to navigate in the files: reach the modpack page, click "Settings", then click "Open Folder". That's all for the user part.
> 
> Server operators (v2.0.1): You need to apply one of the above options to your server as well, and tell your players about which fix you chose. Additionally, you will need to remove those clientside only mods from your server's `/mods` folder: `CustomMainMenu-MC1.7.10-1.9.2.jar`, `Lockdown-1.7.2-2.0.0-universal.jar`, `ResourceLoader-MC1.7.10-1.3.jar`. Don't forget to make the server use Java 8 if you happen to encounter an error mentioning java.base/jdk.internal in the crash. Some information for island management is found at https://www.curseforge.com/minecraft/mc-mods/ftb-islands or by using in-game commands. Creating an island (ops only) `/island_create Steve`. Joining an island (user) `/island_join Steve`. Name the islands after the player names. That's all for healthy servers. 

Please close the issue if that solved it!
