### ISSUE TITLE
ProductiveTrees crashing Direwolf20 server

### ISSUE THREAD

**Issue by ItMeCorban** [FTBTeam/FTB-Modpack-Issues#6348]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.7.0

### Launcher

Server

### Has the pack been modified

Yes

### Log Files

https://pste.ch/ujokevutul.sql

### Describe the bug

Upgraded my server from 1.4.1 to 1.7.0 and it appears productive trees is crashing relating to it's datapack.

I've added simpleplanes 5.3.4, vampirism 1.10.0

The client loads fine and all mods appear to be working as normal, so it's specific to the server

### Steps to reproduce

Run latest 1.7.0 server files
server fails on productive trees datapack

### Expected behaviour

server runs

**Comment by ArtpokeBr** [comment]
try to remove ´´´pmc-1.0.1.jar´´´ see if can help

**Comment by ArtpokeBr** [comment]
`Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / vampirism:vampire_forest]`

Yeah, this is caused by Vampirism, We can't support ya in this case =)

**Comment by ItMeCorban** [comment]
Strange that the client works without issue, will investigate further

**Comment by ItMeCorban** [comment]
Hmm adding the same version to 1.4.1 is working fine, and the server on 1.7.0 does indeed work without the mod so I guess I'll raise it with them
