### ISSUE TITLE
[Bug]: Modpack wont launch anymore (FTB Stoneblock 2)

### ISSUE THREAD

**Issue by G-SUS420** [FTBTeam/FTB-Modpack-Issues#635]
### Modpack

FTP Stoneblock 2

### Modpack version

1.21.1 & 1.22.0

### Describe the bug

I press play and I get exit code -1.  Every once and a while when I try and relaunch the game it will give me a normal output log that tells me I need more permissions but I don't know how to launch the Minecraft launcher in admin mode through ftb and the internet has not helped. This has been happening for around 3 days now and it happened when I tried to remove an item from a chest and it crashed my server and my game. Hasn't worked since. I didn't not re launch the game after it crashed that night so I don't know if its related.

### Steps to reproduce

Open launcher
press play

### Expected behaviour

the game will not launch

### Screenshots

![Screenshot (41)](https://user-images.githubusercontent.com/100096114/154864356-0ee62f73-3db2-4dad-98a4-64eff9479970.png)

**Comment by Raidobw2** [comment]
Hello, can you check inside the `crash-reports` folder if there are any logs in there?
To access that folder, you click the modpack tile to enter the overview page for StoneBlock 2. Then you click on Settings, and scroll down to Open Folder.
If you got a crash and it won't start usually it's a local file or configuration that went blank. The crash log should tell us more about it if you have one.
Drag the file here or use https://paste.feed-the-beast.com/ to post it here.

**Comment by TheonlyTazz** [comment]
without log unsolvable, if issue happens again, post logs and reopen issue (or create a new one)
