### ISSUE TITLE
Mekanism electric pump does not work on sink

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6353]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

"no fluid" error when placed above sink

### Steps to reproduce

1. Place a Mekanism pump above a sink.
2. "no fluid" error

### Expected behaviour

pump should work

**Comment by ArtpokeBr** [comment]
You don't need a pump for this, simple use any type of Fluid Cable and you'll be good to go!

 - You should be fine with Fluid Conduits from Ender IO for example :)
