### ISSUE TITLE
Server start Probleme

### ISSUE THREAD

**Issue by RalleTrain** [FTBTeam/FTB-Modpack-Issues#6360]
### Modpack

FTB Ultimate Reloaded

### Modpack version

1.11.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Server nicht findbar, server Gportal stürtzt Permanetnt ab, mit dem unten aufgefürten fehler cod. bei Screenshots

### Steps to reproduce

Fehlercod

### Expected behaviour

Fehlerbehebung 

### Screenshots

![support server ftb](https://github.com/user-attachments/assets/ec351292-65a7-42b1-83e3-0ec2ad992ca5)

**Comment by WyFryMU** [comment]
Delete the MineTogether mod from your server's `mods` folder.
