### ISSUE TITLE
Water strainer nets cannot be made with twine, as mentioned in the quest

### ISSUE THREAD

**Issue by joral** [FTBTeam/FTB-Modpack-Issues#6368]
### Modpack

FTB Interactions Remastered

### Modpack version

1.10

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

When attempting to create the net for the water strainer in the crafting table, the only options for usable materials are string and silk thread.  In the previous version, the nets were created in the worktable, and the options for material were string, silk thread, and twine.  

The quest book still says to use twine until string is available, but this is not working.

### Steps to reproduce

create crafting table
gather 3 twine
attempt to place in row on crafting table
See that no valid craft is available.

### Expected behaviour

Should be able to create the water strainer net.

### Screenshots

![image](https://github.com/user-attachments/assets/841d44a9-6548-47f0-bbeb-d7b5b576f778)
![image](https://github.com/user-attachments/assets/23674df2-d83b-44a8-9aaa-f5d91186c57d)

**Comment by joral** [comment]
Also applies to the dense net.

**Comment by ArtpokeBr** [comment]
![image](https://github.com/user-attachments/assets/0276d8e1-83c3-41b1-b684-1767a3d107c7)
![image](https://github.com/user-attachments/assets/7321814f-c8e8-4303-bc40-0ab9bc32215e)

I think something is wrong with your Installation....

**Comment by joral** [comment]
Ok, that's odd.  

For me, when I upgraded from 1.9 to 1.10 on the FTB app, it failed as shown above. 

I deleted my instance, and installed 1.10 directly and it was fine.

**Comment by ArtpokeBr** [comment]
O.o well indeed weird, but I'am glad it worked out in the end,
