### ISSUE TITLE
cut paste gadget deleted an entire build

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6369]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I had a certus quartz crystal farm consisting of 4 flawless budding certus quartz, two growth accelerators, some blazing powah cables, a spirited ender gate, and a Just Dire Things advanced block breaker. The whole setup was simply gone when I tried to cut and paste it. All that was left was one of the dirt blocks I had placed in a corner to select it.

### Steps to reproduce

I described the setup. I assume one or more of the involved blocks caused the data to become corrupted.

### Expected behaviour

being able to move setups without yeeting them into the void

**Comment by Gaz492** [comment]
Do you have a debug.log or a latest.log from when this happened?

**Comment by jlp1528** [comment]
In attempting to reproduce this issue for a log file, I found out that it was a quirk in how the cut paste gadget renders the preview of where you're placing the cut build. It's still confusing, but it did not void the build. It was simply rendering the _top_ dirt block on the ground instead of the _bottom_ dirt block. When I attempted to paste it anyway it pasted into the ground.
