### ISSUE TITLE
[Bug]: InventoryPets' Cloud pet appears to prohibit joining an external server.

### ISSUE THREAD

**Issue by The-Shortman** [FTBTeam/FTB-Modpack-Issues#637]
### Modpack

FTB Sky Odyssey

### Modpack version

1.3.0

### Log Files

https://paste.feed-the-beast.com/view/d7482955

### Describe the bug

The cloud pet from inventory pets appears to be causing a server-side crash, preventing players with the item from joining the server.

### Steps to reproduce

Either:
1. Open a Legendary loot crate on an externally hosted server until the cloud pet is obtained (original cause)
2. Get a cloud pet any other way on an externally hosted server

### Expected behaviour

The cloud pet works as intended and doesn't prohibit joining.

### Screenshots

Screenshot of the logs annotated by R3GEN
![](https://cdn.discordapp.com/attachments/896493039051243520/945270900603899974/unknown.png)

### Additional information

This issue happened on an Aternos hosted server, which doesn't have the option to access the mods folder to remove or add mods.

Cloud pet appears to be the only pet to cause this. Black hole pet and slime pet do not cause this issue from what I have observed.

This does not happen on a singleplayer world.

**Comment by Raidobw2** [comment]
I saw your post saying only a specific pet doesn't work and that the rest appear fine. That's alright, I'll see if it needs to be removed or just that pet can be disabled/unobtainable. Once I get some time I'll look into updating this. Thanks again for the report!

**Comment by TheonlyTazz** [comment]
Issues don't occur on the latest in-dev, closing issue. If it does happen again, feel free to create a new one
