### ISSUE TITLE
Adding MrCrayfish Furniture to FTB Evolution

### ISSUE THREAD

**Issue by znowfox** [FTBTeam/FTB-Modpack-Issues#6373]
### Modpack

FTB Evolution

### Mod suggestion

Hey guys i feel the one and only missing mod to make Evolution the latest & greatest (which includes being better than craftoria) is MrCrayfish Furniture! Thank you.

**Comment by ArtpokeBr** [comment]
We've conducted some tests and it seems like the mod adds around 300 ~ 400mb memory consumption and we are already pressing system specs of our users, so unfortunately this mod can't be natively added, feel free to add it to your instance yourself as the mod should be compatible :)
