### ISSUE TITLE
Duplicate Curios mod files

### ISSUE THREAD

**Issue by bartu26** [FTBTeam/FTB-Modpack-Issues#6375]
### Modpack

FTB Evolution

### Modpack version

1.4.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I had issues using the different /curios commands. It showed me in the chat, that the commands were "succesfull", but they didnt change anything in the gui. Like adding an additonal curio slot.
After trying to look into the config files in game, I couldnt find them via the search. They were however in the filesystem.
After looking into the mod files, I stumbled upon another curios mod files:
![grafik](https://github.com/user-attachments/assets/0cc0cb60-00ba-437c-b426-392f1dab1a02)
After deleting it, it started working as expected.

### Steps to reproduce

1. Delete Mod: curios-neoforge-9.1.4+1.21.0 (seems to be the wrong version)
2. Restart Game
3. Curios commands work as intended & configs are found in the ingame config editor

### Expected behaviour

There should only be one instance of the curios mod

**Comment by WyFryMU** [comment]
I thought maybe it was an issue with updating the pack from x -> 1.4.1. So I did a fresh install and yeah I see both curios jars too. That other version is from an older version of the pack.

**Comment by Volpamonhub** [comment]
The same issue exists with InfinityCave, except that due to the mod's poor version naming management, the old version gets loaded instead of the new one.
