### ISSUE TITLE
Missing Crafting Recipe for AE2 Cable Facades

### ISSUE THREAD

**Issue by Kjosu** [FTBTeam/FTB-Modpack-Issues#6378]
### Modpack

FTB Evolution

### Modpack version

1.4.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

AE2 cable facades not showing in JEI

### Steps to reproduce

search in JEI for the above listed recipes/items

### Expected behaviour

to have the recipes show and be usable.

**Comment by ArtpokeBr** [comment]
![image](https://github.com/user-attachments/assets/93097e5e-931d-4fda-83d8-fcf16d5ae004)
They're not Disabled, but added a tooltip to help with this :)
