### ISSUE TITLE
[Bug]: RFTools Spawner recipe for thermal basalz mob is missing

### ISSUE THREAD

**Issue by sarim** [FTBTeam/FTB-Modpack-Issues#638]
### Modpack

FTB Academy 1.16

### Modpack version

1.3.0

### Log Files

[20:34:35] [Server thread/ERROR] [mcjtylib/]: The mob spawn amounts list for mob thermal:basalz is missing!

### Describe the bug

Putting a syringe of basalz mob inside rftools spawner doesn't work. At that time, server log spams that one line. From my research it seems like rftools spawner works based on recipes, and there is no spawner recipe to spawn basalz mob. Maybe a kubejs script is needed to add recipes for missing mobs.

### Steps to reproduce

1. Find a basalz, punch it with syringe until syringe is full.
2. Put syringe inside rftools spawner.

### Expected behaviour

Spawner GUI showing RF amount and items needed to spawn the mob.

**Comment by Raidobw2** [comment]
I'm not sure if that's possible in 1.16.5 as the configuration options for the spawner have changed compared to 1.12.2, but our modpack dev will look into it, thanks for the report.

**Comment by aaronhowser1** [comment]
McJtyMods/RFToolsUtility/issues/128

**Comment by sarim** [comment]
Hmm, that's a separate bug, Rftools could introduce a config like `LogMissingSpawnerRecipe` default = false.
