### ISSUE TITLE
Mekanism copper dust crafting compatibility with other mods

### ISSUE THREAD

**Issue by Kjosu** [FTBTeam/FTB-Modpack-Issues#6380]
### Modpack

FTB Evolution

### Modpack version

1.4.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

cant use mekanism copper dust in MI mixer for bronze or cupronickel dust

### Steps to reproduce

cant use mekanism copper dust in MI mixer for bronze or cupronickel dust

### Expected behaviour

use mekanism copper dust in the same recipes as copper dust from other mods

**Comment by ArtpokeBr** [comment]
Copper Dust from Mekanism is disabled, you should be able to convert them into the Correct Ones.

Also, you shouldn't be able to obtain them, where did you get them? O.o

**Comment by Kjosu** [comment]
I think by just putting raw copper ore/copper ingot in a mekanism crusher
