### ISSUE TITLE
Forbidden Arcanus: Soul Binding Crystal not searchable in JEI

### ISSUE THREAD

**Issue by Kjosu** [FTBTeam/FTB-Modpack-Issues#6381]
### Modpack

FTB Evolution

### Modpack version

1.4.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Forbidden Arcanus: Soul Binding Crystal not searchable in JEI

### Steps to reproduce

search in jei for "Soul Binding Crystal"

### Expected behaviour

to have the recipes show and be usable

**Comment by ArtpokeBr** [comment]
![image](https://github.com/user-attachments/assets/dc16e405-3f44-4ad2-a95d-992dceb3d820)
The Item is Hidden in JEI due to Clutter Reasons, but the recipe does work and exists! you should be able to craft it normally :)
