### ISSUE TITLE
Server pack that BisectHosting installs from FTB install files v.1.7 doesn't sync with v.1.7 client

### ISSUE THREAD

**Issue by ncottrill** [FTBTeam/FTB-Modpack-Issues#6385]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.7

### Launcher

CurseForge

### Has the pack been modified

No

### Log Files

https://mclo.gs/G6cg1H5

164 errors 

### Describe the bug

I can't connect to the server.
I have successfully managed ATM 10 server for a dozen players since ATM 10 began. I don't know why I can't get this modpack to work. 

It would be a 200% help to have a server version of the modpack on CurseForge. Otherwise, I can't tell what the blazes BisectHosting is actually installing.

### Steps to reproduce

Install whatever you gave BisectHosting to install on the server - on a server somehwere
Try to connect to that server
You'll either get registries don't sync or ... null_pointer_exception ... or both

### Expected behaviour

I expect to be able to connect to server

### Screenshots

![image](https://github.com/user-attachments/assets/f251ade7-d003-4d6d-990a-59fc8b4b8268)

**Comment by Gaz492** [comment]
Was this a clean install of the modpack on the server or an update from a previous version?
The errors you are getting is suggesting either something such as a config file or kubejs was not downloaded correctly or didn't update correctly.

Are you able to try running the install for the modpack again to see if that resolves the issue?

Im not familiar with what bisect uses to install our modpacks but I did a test of installing 1.7 DW20 1.21 with our server installer and used the curseforge version of the pack and I was able to connect to the test server I made.

**Comment by ncottrill** [comment]
The biggest issue I have with this pack is that there isn't a server modpack published on CurseForge. If there were a server modpack published on CurseForge (like there is ATM 10), I could install it myself.

**Comment by WyFryMU** [comment]
> The biggest issue I have with this pack is that there isn't a server modpack published on CurseForge. If there were a server modpack published on CurseForge (like there is ATM 10), I could install it myself.

Download the server installer yourself. Place it into a new folder on your PC. Run it. Then zip the files. Upload to your server. It generates the files that you normally find in a zip. It wont start the server locally.

**Comment by ncottrill** [comment]
I have a Windows computer. I believe that the server is linux based. I will try this and probably will just manually move the files. I was concerned that a Windows installation of this modpack would open ports in my firewall. Will it?

**Comment by Gaz492** [comment]
No, the server installer is just a fancy file downloader, it doesn't do anything other than downloading the modpack files the server needs.
We don't use zips as they use up more bandwidth which is expensive and the server installer downloads the mods from curseforge itself, which means the author of the mods should see the download from the server installer.
