### ISSUE TITLE
Watering Can and Modular Router

### ISSUE THREAD

**Issue by Canopik** [FTBTeam/FTB-Modpack-Issues#6388]
### Modpack

FTB Evolution

### Modpack version

1.4.1

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Hello, I don't know if this was intended in the pack or not, but when using Modular Router and Watering Can to accelerate plant growth, nothing happens. The fakeWateringCan = false parameter is specified in the game config.

### Steps to reproduce

1. Place Modular Router
2. Setup Activator module and insert watering can

### Expected behaviour

Growth Accelerates

**Comment by ArtpokeBr** [comment]
Hmm, might break some things/be too op if enabled, so better not forcefully enable this config :)

Also, since we have other options of crop acceleration in the pack, might be fine to not worry about this ;)
