### ISSUE TITLE
subpart form advanced pattern providers do not work

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6389]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

The AE system does not see advanced pattern providers as valid devices unless they are in full block form.

### Steps to reproduce

1. Craft an advanced pattern provider.
2. Craft it into subpart form.
3. Place advanced pattern provider - no channel used and patterns not visible in terminal.

### Expected behaviour

advanced pattern providers should work in either form

**Comment by ArtpokeBr** [comment]
![image](https://github.com/user-attachments/assets/69cc69b6-9b54-4a5f-9b8c-f91fdd77796d)
![image](https://github.com/user-attachments/assets/0e111ba9-5c08-436f-a5a0-e7146df57b63)
![image](https://github.com/user-attachments/assets/ccf0dd36-378c-4ebb-bc4e-a353a6640ad8)

It seems to be working here 🤔

**Comment by jlp1528** [comment]
I really need to try reloading the world before I report bugs. IDK what happened. They definitely were not working when I posted this.
