### ISSUE TITLE
[Bug]: /home sending players to RFTools dimensions

### ISSUE THREAD

**Issue by Tokoshoran** [FTBTeam/FTB-Modpack-Issues#639]
### Modpack

Direwolf20 1.16

### Modpack version

1.13.2

### Describe the bug

While brand new, named home points seem to work just fine, old home points seem to get redirected to RFTools dimensions, at least on populated servers. Even the /back command seems to be unable to process the difference between dimensions, warping to the RFTools dimension when it should have warped to Overworld.

### Steps to reproduce

1. Set a homepoint on a server with other players
2. Wait a day or two
3. Try to warp to your homepoint
4. Realize you're suddenly in another dimension and need to use a waystone to get out

### Expected behaviour

Homepoints recognize dimensions

**Comment by Tokoshoran** [comment]
If relevant, the two major dimensions this seems to happen with are named __redstone__ and __diamonda__.

**Comment by Raidobw2** [comment]
Hello, when you say "homepoints" do you mean you have many homes? And none in the dimensions I assume?

**Comment by Tokoshoran** [comment]
Some players only have a single homepoint, others have several. None of the homepoints are set in those dimensions, but suddenly redirect to them, even if the player has only been in the overworld the whole time.

**Comment by Tokoshoran** [comment]
Been told this likely originated from some personal tweaks the host was attempting, so it seems likely unrelated to any official part of the pack.
