### ISSUE TITLE
ME import bus can pull from INPUT slot of mechanical squeezer

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6390]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

See title. I am now aware that you have to pull outputs out from the bottom, but this issue still should not happen.

### Steps to reproduce

1. Place an import bus on a mechanical squeezer.
2. Place items inside - items pulled from input.

### Expected behaviour

import buses, like any other piping system, should never pull from the input slots of machines

**Comment by ArtpokeBr** [comment]
Well, this is a default behavior from Integrated Dynamics, Squeezers are Sided Machines.

So if you feel like they shouldn't or either only the mechanical shouldn't, please make sure to report your feedback to the mod author [here](https://github.com/CyclopsMC/IntegratedDynamics/issues).
