### ISSUE TITLE
FTB Lite wont start. Last error in Console is Buildcraft Version Check failed

### ISSUE THREAD

**Issue by PaulH4lbr3in** [FTBTeam/FTB-Modpack-Issues#6399]
### Modpack

FTB Lite

### Modpack version

1.2.3

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[log.txt](https://github.com/user-attachments/files/18100943/log.txt)

### Describe the bug

After not playing for a long time, I decided to download the FTB Launcher on my new computer (ARM Mac running macOS 15.1.1). After downloading FTB Lite and starting it, the last line in the console shows "[INFO] [Buildcraft] Version check failed" and then nothing happens until I kill the instance.

### Steps to reproduce

1. Install fresh instance of FTB Lite through FTB Launcher
2.  Launch FTB Lite

### Expected behaviour

The game doesn´t start.

**Comment by Gaz492** [comment]
Unfortunately there is a bug in one of the core mods that causes the screen to stay blank in most if not all of our 1.4.7 modpacks if you are on an arm based mac.

We are currently unaware of any method to get around or resolve this issue.
[](!skip)

**Comment by Gaz492** [comment]
Yes, it should run on an intel mac and windows machine

**Comment by PaulH4lbr3in** [comment]
Windows emulation using Parallels worked for me. Thanks!
