### ISSUE TITLE
[Bug]: FTB University 1.16 server start.bat crashing

### ISSUE THREAD

**Issue by brooksbutler** [FTBTeam/FTB-Modpack-Issues#640]
### Modpack

FTB University

### Modpack version

1.16

### Log Files

[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8113659/debug.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8113661/latest.log)

### Describe the bug

Pretty much as the description states. After a fresh install of the FTB University 1.16 server through the FTB app running the start.bat file crashes due to some missing properties in "mixins".

### Steps to reproduce

1. Go to FTB App
2. Select FTB University 1.16
3. Select "Versions" --> Server files
4. Download installer for windows
5. Run the installer
6. Run start.bat

### Expected behaviour

The server would start

**Comment by Raidobw2** [comment]
Hello, Java8u321 is incompatible with that current Forge version. Use Java8u312 to start the server.
See #578 for example and please close the issue if it solved it.

**Comment by seyfahni** [comment]
FOr those searching for a way to get that java version, here's the direct download: https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/tag/jdk8u312-b07
