### ISSUE TITLE
cressey

### ISSUE THREAD

**Issue by tycoomw1** [FTBTeam/FTB-Modpack-Issues#6410]
### Modpack

FTB Genesis

### Modpack version

1.4.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[crash-2024-12-13_17.28.51-client.txt](https://github.com/user-attachments/files/18123623/crash-2024-12-13_17.28.51-client.txt)

### Describe the bug

When I install and run there is a problem. Why is that?

### Steps to reproduce

1.4.0 Installation execution Crash occurred

### Expected behaviour

solve

**Comment by tycoomw1** [comment]
The method I know doesn’t work either.

**Comment by Gaz492** [comment]
Could you try disabling the Minetogether mod and see if the pack starts up for you?

**Comment by tycoomw1** [comment]
Another problem arises

**Comment by Gaz492** [comment]
What would that problem be...

**Comment by tycoomw1** [comment]
fancymenu

**Comment by tycoomw1** [comment]
Mekanism and FancyMenuThere is a compatibility issue, so the related mod does not work
