### ISSUE TITLE
7x7x7 quantum computer not forming

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6421]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.8.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

See title and reference https://github.com/pedroksl/AdvancedAE/issues/76

### Steps to reproduce

1. Try to build a 7x7x7 AdvancedAE quantum computer per the instructions. 3x3x3 and 5x5x5 form. 7x7x7 does not.

### Expected behaviour

formed multiblock

**Comment by Gaz492** [comment]
Using the template you put in the other issue you created on the AdvancedAE repo and changing the config so the max size is 7, I have not been able to reproduce this, the computer formed correctly for me 
![java_8RNVHXlr](https://github.com/user-attachments/assets/642cdd8a-abb4-4d74-939a-1263cba9e6bd)
