### ISSUE TITLE
crash on load from raid until "enchant with mob" disabled

### ISSUE THREAD

**Issue by jlp1528** [FTBTeam/FTB-Modpack-Issues#6423]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.8.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

https://pste.ch/uxurufuruv.pl

### Describe the bug

see title

### Steps to reproduce

Initiate a raid and get unlucky I guess?

### Expected behaviour

If I could go ONE WEEK without a world-locking crash that would be nice.

**Comment by Gaz492** [comment]
Closing this in favour of https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6431
