### ISSUE TITLE
Modpack Loader Crash

### ISSUE THREAD

**Issue by madhecklar** [FTBTeam/FTB-Modpack-Issues#6428]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.8.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[crash-2024-12-14_23.16.25-client.txt](https://github.com/user-attachments/files/18139011/crash-2024-12-14_23.16.25-client.txt)

### Describe the bug

simple_weather-1.0.7.jar crashes modpack load upon initiation. "Error during Mod Load."

### Steps to reproduce

1) download modpack
2) Click Play
3) Mod Pack Load Crashes

### Expected behaviour

Mod pack load without crash

### Additional information

when modpack version downgraded. issue still exists. also after complete reinstall of java, App and Modpack. When simple_weather-1.0.7.jar is removed Mod pack crashes and minecolonies and jaopaca throws error.

**Comment by madhecklar** [comment]
also, have been playing modpack foor a couple months just fine. this is a recent issue

**Comment by Gaz492** [comment]
Would you be able to upload the simple-weather-client.toml config file so I can take a look at it?
This file can be found by right clicking the modpack in the FTB app then selecting Open folder > Configs

**Comment by madhecklar** [comment]
[simple_weather-client.txt](https://github.com/user-attachments/files/18141146/simple_weather-client.txt)

Thank you! I appreciate your help.
It doesnt like toml file here so copied it to notepad.
also, just wanted to point out that it should be a fresh config. no saves loaded. I reinstalledFTB Electron App.  after uninstalling and removing .ftba, Redownloaded ftb-app-1.26.3-x64 from https://www.feed-the-beast.com/ftb-app. Reinstalled the modpack without putting in any saves, Alotted full memory (10GB). Crash happens at mid load. I removed simple_weather-client.toml config hoping it would generate one that works, to no avail.

**Comment by Gaz492** [comment]
Could you try replacing the simple_weather-1.0.7.jar with this version and see if the issue still happens for you?
https://www.curseforge.com/minecraft/mc-mods/simple-weather/files/5984086

Ive not been able to reproduce this issue unfortunately.

**Comment by madhecklar** [comment]
Again, thank you for your help.
Loaded simple_weather-1.0.13.jar..  no dice. still Java exception:
[crash-2024-12-16_16.46.46-client.txt](https://github.com/user-attachments/files/18157928/crash-2024-12-16_16.46.46-client.txt)

**Comment by madhecklar** [comment]
What Java are you using to run your environment?

**Comment by Gaz492** [comment]
Direwolf20 1.21 needs Java 21.

Out of interest, could you try and disable the rain shield mod then see if the issue still happens?

**Comment by madhecklar** [comment]
issue still exists after rain shield disabled. can you tell me why this was listed as completed?

**Comment by madhecklar** [comment]
I was able to fix it. I removed all traces of FTB Electron App. DLed latest Java 21. Reinstalled FTB App. Reinstalled Pack. Disabled AV and it loaded right up. Thank you for all the help.
