### ISSUE TITLE
[Bug]: SHA-1 checksums on stoneblock server 1.22.0 beta do not match on 3 files

### ISSUE THREAD

**Issue by lever1209** [FTBTeam/FTB-Modpack-Issues#643]
### Modpack

FTB Stoneblock 2

### Modpack version

1.22.0

### Log Files

https://pastebin.com/zBiY6PmA - your server installer
https://pastebin.com/t0F6GMWT - my server installer (does not handle forge, minecraft, or a jre)

### Describe the bug

invalid sha-1 checksums

### Steps to reproduce

run the ftb official stoneblock 2 1.22.0 installation binary
proceed with the installation
wait for the installer to tell you that it failed with 3 invalid downloads

### Expected behaviour

it should succeed with the installation

### Additional information

there should also be an included way to launch the server under a custom java path as not everyone uses java 8 anymore (https://pastebin.com/ky8fuch0 when running jdk 17)

**Comment by lever1209** [comment]
im sorry, i forgot to include the 3 files mentioned outside of the log file

Cache#-1135820533.png
2400b947ec96a6cba5804d94612b0eef7d0cd8ae - generated
c45fb3e10d704273ce1d5e33e320dba529ef9d03 - provided

Cache#-1183039813.png
2400b947ec96a6cba5804d94612b0eef7d0cd8ae
00671bbeb63bf485fee781462609499fc1e995de

Cache#2134442667.png
80ea83dff5d78762ce9bc073366aebc6695ff1b1
4b7d6116c154167f6cc851ab9ddd0c93a7d11a65

**Comment by Raidobw2** [comment]
Hello lever1209, thank you for the report!

Jake this is the issue for the checksum I talked about recently

**Comment by lever1209** [comment]
i dont know if this is a good place for it, but, is it possible to open source the installation binary? or at least provide a solid archive?
making the script in java may also help with some of the development process because its cross platform, but these are small suggestions

**Comment by lever1209** [comment]
> i dont know if this is a good place for it, but, is it possible to open source the installation binary? or at least provide a solid archive? making the script in java may also help with some of the development process because its cross platform, but these are small suggestions

i would like to correct my previous statement, i was under the impression that the server installation binary was a simple install script

**Comment by Raidobw2** [comment]
To answer your question, it's open source and at the location https://github.com/CreeperHost/modpacksch-serverdownloader. Cheers.

**Comment by Raidobw2** [comment]
I believe our app devs and infrastructure team solved this issue working together, as well as all possible checksum mismatchs for other modpacks. I will be closing this as a result
