### ISSUE TITLE
The server send registries with unknown keys: ResourceKey[minecraft:menu / appmek:portable_chemical_cell]

### ISSUE THREAD

**Issue by jpinz** [FTBTeam/FTB-Modpack-Issues#6436]
### Modpack

FTB Evolution

### Modpack version

1.5.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Error when joining server:
 Client disconnected with reason: The server send registries with unknown keys: ResourceKey[minecraft:menu / appmek:portable_chemical_cell]

### Steps to reproduce

1. Spin up a server using: `curl -JLO "https://api.feed-the-beast.com/v1/modpacks/public/modpack/125/100010/server/linux" && chmod +x serverinstall_125_100010`
2. Connect to it after it has launched

### Expected behaviour

Users can join server

### Screenshots

![Image](https://github.com/user-attachments/assets/fd1650e4-bc08-4688-83e7-b0347fd62d46)

**Comment by jpinz** [comment]
After restarting the client and reinstalling the server it appears to work fine, sorry!

**Comment by racerxdl** [comment]
Happened here as well. No idea why, one of my server users reported it, others are working fine.

**Comment by TDY2012** [comment]
I got this error too while my friend didn't. He can joined the server fine.
