### ISSUE TITLE
InfinityCaves Gen

### ISSUE THREAD

**Issue by NoodlesWithRice** [FTBTeam/FTB-Modpack-Issues#6437]
### Modpack

FTB Evolution

### Modpack version

1.3.0

### Launcher

CurseForge

### Has the pack been modified

No

### Describe the bug

The worldgen of the inifinity caves is super weird, this world has only every existed in 1.3 and only has been opened in 1.3. Hope this isnt a double post.

### Steps to reproduce

Load world, search the Infinity Caves.

### Expected behaviour

Weird lava-walls

### Screenshots

![2024-12-16_18 54 25](https://github.com/user-attachments/assets/758937f2-d763-4e22-9416-20b746bfd1fb)
![2024-12-16_18 56 15](https://github.com/user-attachments/assets/d7fd42cb-3153-4477-b979-832739dd4a21)
![2024-12-16_18 56 21](https://github.com/user-attachments/assets/43e27d34-5dfc-4d37-a5f5-da8248465a1e)
![2024-12-16_18 57 09](https://github.com/user-attachments/assets/d52afee5-659a-4cfc-9f56-181261f9b78c)

**Comment by KittenIsLive** [comment]
@NoodlesWithRice This was fixed in pack version 1.5.0 which changed to infinity caves v0.7, though I think it may spawn chunks of water instead now.
