### ISSUE TITLE
Gold Gear Recipe Missing from Industrial Foregoing

### ISSUE THREAD

**Issue by maraudir** [FTBTeam/FTB-Modpack-Issues#6438]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.8.2

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Only the railcraft gold gear is present in JEI.  The Foregoing recipe is gone and has broken my AE2 crafting recipe.

### Steps to reproduce

1. Search JEI for Gold Gear 2. Look at gears for Foregoing.

### Expected behaviour

Gold Gear should be seen in JEI and buildable.

**Comment by jlp1528** [comment]
The recipe will accept any gold gear. As a tip, program the working gold gear first and the AE system will use the gear that is now available to craft.

**Comment by maraudir** [comment]
Hi there, no, this isn't the case.  Only one gold gear can be created and it's not the Industrial Foregoing version.
![image](https://github.com/user-attachments/assets/93c9bade-06ac-4d33-85d8-48783f68767a)
![image](https://github.com/user-attachments/assets/138e9015-ed1c-4dc8-add7-47b5a20e547a)

**Comment by jlp1528** [comment]
Exactly. Just reprogram that to the other gold gear and any machines that use gold gears to the new one.

**Comment by maraudir** [comment]
I know how I can fix it, but this is a bug report.  Also, it's a cascade effect on other recipes that use Gold Gears and will cause me to fix many recipes.

**Comment by ArtpokeBr** [comment]
This is due a recent Unification Adjustments, there shouldn't be more than 1 Gold Gear in the Modpack.

And since FTB Materials is not used in Dire's Pack we had to make a choice, its unfortunate that you'll have to update your Recipe Patterns but this kind of adjustments shouldn't happen unless necessary, Sorry for the inconvenience =)
