### ISSUE TITLE
Ongoing aluminum recipe issues

### ISSUE THREAD

**Issue by mgnay** [FTBTeam/FTB-Modpack-Issues#6439]
### Modpack

FTB Evolution

### Modpack version

1.5.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

There is 3 different types of alumin(i)um ingots and stuff like ores, rods, plates etc. Also i can't turn some aluminum nuggets to ingots too, there is some weird recipes there that makes things complicated while crafting stuff with it. Additionally there are more than a few aluminum recipes that are requiring direct items instead of their corresponding item tags.

### Steps to reproduce

1. Mine an Aluminum ore
2. Smelt and get an Xycraft Aluminum Ingot
3. Make it block and ingot again to get FTB Resources one
4. Idk how did i get the Immersive Engineering one, probably from 1.4.1

### Expected behaviour

Recipes to work with items with the same tags

### Screenshots

![image](https://github.com/user-attachments/assets/515675d1-8d97-4e76-857f-a4906d5c17c3)

**Comment by ArtpokeBr** [comment]
The reason why its a bit confusing is that we need to keep Modern Industrialization's Aluminum and Xycraft's Aluminum Separated.

So Simple Aluminum Recipes like IE ones and of course XC ones use Xy's Aluminum and more complex ones use FTB Materials's Aluminium.
