### ISSUE TITLE
[Bug]: Mekanism Logistical Pipes /w Immersive Engineering Garden Cloche

### ISSUE THREAD

**Issue by quikenb** [FTBTeam/FTB-Modpack-Issues#644]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Describe the bug

When using Mechanical Pipes from Mekanism the water gets inputted into the Garden Cloche

When using Logistical Pipes from Mekanism the items DO NOT get exported/imported even with the right setup

When using Universal Cable from Mekanism energy also gets imported

### Steps to reproduce

Just setup a Garden Cloche with Logistical Pipes and the pipe will not import/export

### Expected behaviour

Fix compatibility

**Comment by Raidobw2** [comment]
Hello, I know sometimes the information is hard to come accross but useful information about the Garden Cloche is listed in the Immersive Engineering in-game manual. This comes shipped with the Akashic Tome at the start of the game.
![image](https://user-images.githubusercontent.com/17010632/155702527-b56cb171-f376-4e8a-bfb1-cf9bde30444f.png)
![image](https://user-images.githubusercontent.com/17010632/155702630-3dc7cb5b-6cba-4d6e-adc1-02daaa82a687.png)
The bottom ports can be used for power, water input or item input. The top of the dome is used for power as well. The front of the dome is the only way to extract items. Mekanism's Logistical Transporters don't expose an inventory like some other pipes do, so they need to be set in extraction mode. This is done with a Configurator, by Shift Right Clicking the connection to the Garden Cloche. Alternatively, you can put a chest or drawer directly in front of the Cloche and it will auto output to it. This solution is commonly used.
![example_with_mekanism](https://user-images.githubusercontent.com/17010632/155702973-e3016769-b9d8-4cc7-8dcd-c28339f19a17.gif)
A Storage Drawer 1x2 showing its contents after using a Quantify Key on it.
![image](https://user-images.githubusercontent.com/17010632/155703270-25ad2c4e-91f9-4f44-9535-b7d8415119e3.png)
![image](https://user-images.githubusercontent.com/17010632/155703310-2ae381fc-3ba9-4b94-b563-39c25ce471db.png)
Applying a redstone signal to the bottom of the cloche will disable it, use a lever when you have enough resources.
![image](https://user-images.githubusercontent.com/17010632/155703810-1ed57c64-d850-426d-8da6-74b83e4607d5.png)
Input Bone Meal or other fertilizer from the big input hatches at the bottom.
![image](https://user-images.githubusercontent.com/17010632/155704705-2ac75fe9-d36d-498e-9680-358327deed2b.png)
Please close the issue if that fixed it and cheers.
