### ISSUE TITLE
[crash-2024-12-17_15.28.34-fml.txt](https://github.com/user-attachments/files/18171025/crash-2024-12-17_15.28.34-fml.txt)

### ISSUE THREAD

**Issue by Volutus43** [FTBTeam/FTB-Modpack-Issues#6446]
[crash-2024-12-17_15.28.34-fml.txt](https://github.com/user-attachments/files/18171025/crash-2024-12-17_15.28.34-fml.txt)

_Originally posted by @Volutus43 in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6425#issuecomment-2549555510_

**Comment by Volutus43** [comment]
I wanted to post this to hopefully make it a reopened issue as I am having the problem again.

**Comment by Volutus43** [comment]
I also didn't know how to reopen a case on github so I thought this would work

**Comment by Gaz492** [comment]
Ive reopened the other issue
