### ISSUE TITLE
Bug with the Electrolizer from Modern Industrialisation

### ISSUE THREAD

**Issue by Lorddistrict** [FTBTeam/FTB-Modpack-Issues#6456]
### Modpack

FTB Evolution

### Modpack version

1.5.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

I've got an electrolizer with a ME Pattern Interface linked and an Ultimate Tank.
I put inside x64 bauxite dust for the recipe : x10 bauxite = x4 Aluminum Dust + x3 Titanium Tiny Dust + 2.000mB Oxygen
But the Electrolizer isn't starting. It's like it doesn't understand the recipe.

I tried with & without Overdrive Module.

I tried as well with Emerald Dust to get Beryllium it doesn't work as well.
I tried both with Almost Unified and without.

However, it works for the Charged Certus Quartz Crystal very well.

### Steps to reproduce

1. Make a setup
2. Power it
3. Put bauxite dust inside
4. Wait until GTA 6 is coming out (joke)

### Expected behaviour

The machine working & processing

### Screenshots

![image](https://github.com/user-attachments/assets/9831a591-7efd-472e-9877-739fae749394)

![image](https://github.com/user-attachments/assets/72af542a-28ef-489d-a124-eb7fec744b2f)

![image](https://github.com/user-attachments/assets/de6d7bae-c28a-4775-8ff5-b338835af2f0)

![image](https://github.com/user-attachments/assets/df288264-329f-4cfa-bfde-5f420315d5df)

**Comment by Lorddistrict** [comment]
After a logout/log in from another map for more testings, the block is starting running but is acting strange with overclock :

![image](https://github.com/user-attachments/assets/e301ee1c-7fa1-4dac-b5eb-25fedbda69a5)

**Comment by ArtpokeBr** [comment]
![image](https://github.com/user-attachments/assets/3dd2f9d0-8724-4109-bc3c-c116398ed653)

Not sure if this is after a recent Mod update in our Dev Instance, but this seems to be fixed, maybe you're not providing enough energy? Idk, with a LV Diesel Generator it worked just fine here.

**Comment by Lorddistrict** [comment]
It makes the same again and I don't know why. As you can see, I've got enough energy, enough resources, 300M+ FE stored & I'm using an EnderIO cable filled up with energy.

The only way It works is to update the block by removing the Overdrive Module and putting it back. So is it maybe a mod bug ?

![image](https://github.com/user-attachments/assets/bbec81ab-7c26-483f-a255-559f532c72fd)
![image](https://github.com/user-attachments/assets/d779109e-9bb9-45eb-aae0-981845347290)
![image](https://github.com/user-attachments/assets/2f697df1-779b-4b67-90f4-9b9441bac8be)
![image](https://github.com/user-attachments/assets/6106db94-4e23-464c-99a5-409138a41df8)

**Comment by Lorddistrict** [comment]
Hello, thanks for your answers I have mine : The Overdrive Module (OM) works this way : It keeps the efficiency at it's current level for the SAME recipe. So if i'm crafting a charged certus quartz and I'm at 64/64 efficiency, while I'm not removing the OM, the next recipe will not be crafted.

As someone said on Reddit, Modern Industrialization goal is to have one machine paipeline by recipe. So if I want to keep the OM, I have to craft an Electrolizer for each recipe.

It doesn't match very well with AE2 Pattern system but I understand now :)
