### ISSUE TITLE
FTB Skies Expert crashing with mod compatibility issues after upgrading to 1.10.1

### ISSUE THREAD

**Issue by res0nat0r** [FTBTeam/FTB-Modpack-Issues#6472]
### Modpack

FTB Skies Expert

### Modpack version

10.10.1

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

https://gist.github.com/res0nat0r/756ca971b5d8444088aeb87dade6f075

### Describe the bug

After upgrading to `1.10.1` the game crashes with mod compatibility issues.

### Steps to reproduce

1. Update FTB Skies expert in the FTB app to `1.10.1`
2. Launch game.
3. Game aborts during startup due to mod issues.

### Expected behaviour

The world should load without crashing.

### Screenshots

![2024-12-20 23_37_21-NVIDIA GeForce Overlay DT](https://github.com/user-attachments/assets/90e22400-de32-43f3-b6a4-4112cf6856b4)

### Additional information

I've attached a crash report to this issue via the Github Gist link above.
I've also tried the repair option, but am still getting the error above.

**Comment by TREEJAP** [comment]
Same problem. Had to delete and re-install to an old version

**Comment by sme23** [comment]
This can be fixed by removing `flywheel-forge-1.19.2-0.6.8.a.jar`. Versions of Flywheel beyond 0.6.8 are bundled with Create. Presumably, the legacy standalone version was grabbed and included by some automatic dependency checker

**Comment by SlayGoatQueen** [comment]
> This can be fixed by removing `flywheel-forge-1.19.2-0.6.8.a.jar`. Versions of Flywheel beyond 0.6.8 are bundled with Create. Presumably, the legacy standalone version was grabbed and included by some automatic dependency checker

This worked for me.  Thank you!

**Comment by Gaz492** [comment]
This is fixed in 1.10.2
