### ISSUE TITLE
[Bug]: Connecting Powah cable to Pipez energy cable causes StackOverflowError

### ISSUE THREAD

**Issue by PlusLake** [FTBTeam/FTB-Modpack-Issues#650]
### Modpack

FTB Academy 1.16

### Modpack version

1.3.0

### Log Files

https://bytebin.lucko.me/lkbgK5HACr

### Describe the bug

Connecting Powah cable to Pipez energy cable causes server crash.
You cannot restart the server anymore and you must recover it from a backup.

Cable types does not matter, any type of Powah connecting to Pipez's universal cable / energy cable can reproduce it.
It will not crash when no energy is transferring.

### Steps to reproduce

1. Place 2 * Powah cable (any rank) and 2 * Pipez energy cable or universal cable. (see screenshot 1)
2. Provide energy to the Powah cable, make sure there is energy moving.
3. Use a wrench to connect the Powah cable and Pipez cable.
4. Game crashed. Loading the same chunk will cause crash again.

### Expected behaviour

Not crashing.

### Screenshots

![image](https://user-images.githubusercontent.com/42900821/155850971-e167b9e5-34db-4e10-94e5-0867fcdea9cf.png)
![image](https://user-images.githubusercontent.com/42900821/155850975-8349bd81-b0a2-4f90-901f-0d6cc64a5cf1.png)

**Comment by Raidobw2** [comment]
Report made to mod author of Pipez ^
