### ISSUE TITLE
Sifter go brr quest - not working 

### ISSUE THREAD

**Issue by SamuUndici** [FTBTeam/FTB-Modpack-Issues#6500]
### Modpack

FTB Skies Expert

### Modpack version

1.10.2

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

By crafting the items required by the quest it marks the two items crafted but the quest is 0% completed 

### Steps to reproduce

Open Quests -> Getting Started -> Sifter go Brrr

### Expected behaviour

Getting rewards

### Screenshots

![Immagine 2024-12-25 093224](https://github.com/user-attachments/assets/c87476dc-ad62-4440-bb7a-fb6d47d9c433)

**Comment by md5i** [comment]
It is likely that you have not completed all the dependent quests.  There is a quest above that one which is a dependent for "Sifter go brr".

**Comment by SamuUndici** [comment]
Actually my bad, i haven't noticed it. Thanks a lot
