### ISSUE TITLE
[Bug]: Quest Rewards give not implemented modules

### ISSUE THREAD

**Issue by Targren** [FTBTeam/FTB-Modpack-Issues#651]
### Modpack

FT Oceanblock

### Modpack version

1.11.0

### Describe the bug

Random Quest rewards can give "Remote Storage Modules" (rftoolsstorage:storage_module6) from RFToolsStorage. These modules don't do anything, as they [aren't yet implemented.](https://github.com/McJtyMods/RFToolsStorage/issues/25)

### Steps to reproduce

1. Complete Quest
2. Pray to RNGesus
3. Receive Remote Storage Module

### Expected behaviour

Don't give unimplemented items as rewards

**Comment by Raidobw2** [comment]
Hmm, I guess we could change this for a Storage Control Screen Module instead. It would achieve a similar thing with a Tablet and a Storage Scanner. Good catch, thanks for the report!
