### ISSUE TITLE
Immersive Engineering Steel armor incorrect armor values

### ISSUE THREAD

**Issue by KamuiLord** [FTBTeam/FTB-Modpack-Issues#6518]
### Modpack

FTB Evolution

### Modpack version

1.6.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

Steel Armor from Immersive Engineering has its armor stat the same as its durability value.

### Steps to reproduce

1. Look up item on JEI or just craft it. 

### Expected behaviour

Item should have more reasonable  armor value.

### Screenshots

![bug](https://github.com/user-attachments/assets/b36ad40a-d94c-45ce-a991-305ac7cc62f7)

**Comment by Gaz492** [comment]
Putting this here for tracking https://github.com/BluSunrize/ImmersiveEngineering/issues/6124

**Comment by Gaz492** [comment]
Actually as there is another open issue about this, im going to close this issue.
To track this issue please follow https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6320

**Comment by DawsonCamp** [comment]
im having the same issue
