### ISSUE TITLE
[Bug]: Continuum can't join team

### ISSUE THREAD

**Issue by aximus11** [FTBTeam/FTB-Modpack-Issues#654]
### Modpack

FTB continuum

### Modpack version

1.12

### Describe the bug

I cant seem to join my friends party in game. It freezes and wont let me leave my own party and it wont let my friends invite me or anything. I tried to go to the discord but no one answered. If someone can help that would be nice

### Steps to reproduce

download ftb continuum 
join friends server 
log in and get in the server
cant join friends party or leave your own

### Expected behaviour

I expected the party system to work?

**Comment by Raidobw2** [comment]
Hello, I'll show you some instructions to join the party for the quests, let me know at any point if it fails and I'll dig up some information so you can have quests together.
1. Click leave team
![image](https://user-images.githubusercontent.com/17010632/156376911-1514a52d-3d46-4d9d-b55d-0b3435fe97bc.png)
![image](https://user-images.githubusercontent.com/17010632/156376961-400aad33-51da-4e05-b105-cf697f146a1e.png)
2. Click back
![image](https://user-images.githubusercontent.com/17010632/156377050-facec0ec-f39a-4c37-83a9-4414239113ab.png)
3. Click party
![image](https://user-images.githubusercontent.com/17010632/156377093-0bfaa189-ecd7-4e53-93cb-39b43e1e4de7.png)
4. Create party
![image](https://user-images.githubusercontent.com/17010632/156377146-4d01e985-1beb-40dd-90b5-93781fe9e189.png)
5. Click invite
![image](https://user-images.githubusercontent.com/17010632/156377196-1a50e34e-587d-49bd-9ff2-d86d1b408aa0.png)
6. Type friend's name and click Invite
![image](https://user-images.githubusercontent.com/17010632/156377397-5052d8d9-1e9f-4676-a57d-be5249f4652b.png)
7. Your friend needs to check their questing book in the Party section and they should have an invite.

Let me know if you still experience issues. Also, you can add them to your FTB team and they will be able to claim chunks with you, as a team.
![image](https://user-images.githubusercontent.com/17010632/156377759-6b4078a0-1c7e-474a-99b2-f5d560e1a24f.png)
Cheers and I hope that helps, let me know.
