### ISSUE TITLE
[Bug]: Direwolf20 1.13.2 (1.16.5) no Stencil Table & Fabulous! Graphics issue

### ISSUE THREAD

**Issue by Johnnii360** [FTBTeam/FTB-Modpack-Issues#655]
### Modpack

Direwolf20

### Modpack version

1.13.2

### Log Files

debug.log: https://pste.ch/udefuzehaj.md
latest.log: https://pste.ch/ihepaxivax.bash

### Describe the bug

1. There is no Stencil Table to create more tools like e.g. the Excavator. I already downgraded of the Beta to the 1.12.0 but nothing. It's also not craftable. I also looked into the configs but didn't found anything about it.
2. When I want to enable Fabolous! graphics Minecraft report that my graphic card isn't supported. I think my Nvidia Geforce RTX 2070 is strong enough. :)

Btw. I'm playing in single player mode and survival.

### Steps to reproduce

Just search for "stencil". There is nothing for Tinker's Construct.

### Expected behaviour

To see the Stencil Table.

### Screenshots

![Bildschirmfoto von 2022-03-02 14-49-41](https://user-images.githubusercontent.com/15824634/156374368-109a3671-f5d1-4acf-98f1-c1d80a4e7558.png)
![Bildschirmfoto von 2022-03-02 14-50-52](https://user-images.githubusercontent.com/15824634/156374389-3e449f16-0300-4360-84fe-fe76d919e3ca.png)

### Additional information

Systeminfo: https://gist.github.com/Johnnii360/bb0655cbf07b76f5ed3c3dd8852d89e8

**Comment by Raidobw2** [comment]
Hello, the new Tinker's Construct is different and it's important to read the guides if you haven't touched it in a long time. The first book "Materials and You" contains information for "Stencils" and they are now called Patterns. They are integrated within the Part Builder.
![image](https://user-images.githubusercontent.com/17010632/156493538-daa587a0-a4a0-4b89-842a-d9949be84378.png)
As for building an Excavator or other tools, make sure to check the other guides as well. In "Mighty Smelting", you'll see how to make an Excavator. There is no head for that tool: it's 2 large plates and 2 tough handles.
![image](https://user-images.githubusercontent.com/17010632/156493762-5f08af15-6421-4c48-bdd7-f87aa53c2f46.png)
As for Fabulous video settings, you can enable them even if it says your graphics card is unsupported. Simply click the button:
![image](https://user-images.githubusercontent.com/17010632/156496200-1a1ed9b6-04bb-4eaa-ba23-459be775c2fd.png)
This doesn't change anything much by default but can allow resource packs to add shaders and effects, here's an example for cellshading.
![image](https://user-images.githubusercontent.com/17010632/156496152-b0aa7314-bc34-447b-8e1c-8eb2f9738b0a.png)
![image](https://user-images.githubusercontent.com/17010632/156496222-7c275342-942f-41f8-af68-26c8eefc1c55.png)
Perhaps you can check https://www.reddit.com/r/Minecraft/comments/hkm40f/minecraft_116s_fabulous_graphics_option_allows/ for more information on that topic. Note that this is very similar to what Optifine on Forge and Iris on Fabric can give you. Unless you have another question, please close this issue upon reading it and I hope that it helped, cheers.

**Comment by Johnnii360** [comment]
Thanks a lot for your help! I see, it's a long time ago I used Tinker's Construct. My last touch was with the mod "Dungeons, Dragons and Spaceshuttles". It really has changed a lot! :)

**Comment by Raidobw2** [comment]
Ah I see. Have fun learning the new one then, it's pretty cool!
