### ISSUE TITLE
[Bug]: BYG dummy biome appearing with Terraforged worlds

### ISSUE THREAD

**Issue by Camora0** [FTBTeam/FTB-Modpack-Issues#656]
### Modpack

FTB University 1.16

### Modpack version

1.4.0

### Describe the bug

When in worlds utilizing the Terraforged mod's worldtype, occasionally the unusued blank dummy biome will appear. This biome doesn't generate any structures, trees, or even flowers and grass. The grass is a really grating bright green, making the whole biome an eyesore.

### Steps to reproduce

1. Generate a world in the terraforged generation type.
2. Give yourself a nature's compass.
3. Search for Dummy biome.

### Expected behaviour

The Dummy biome should not appear during normal generation.

**Comment by aaronhowser1** [comment]
TerraForged/tracker/issues/179

**Comment by aaronhowser1** [comment]
Set the dummy biome's weight to 0
