### ISSUE TITLE
[Bug]: Server wont start

### ISSUE THREAD

**Issue by KickaBytes** [FTBTeam/FTB-Modpack-Issues#657]
### Modpack

OceanBlock

### Modpack version

1.11.0

### Log Files

Install Log:  https://paste.feed-the-beast.com/view/819bed09

Server Log: https://paste.feed-the-beast.com/view/5cd7753a

### Describe the bug

The server won't start up upon running Start.bat

### Steps to reproduce

Run Start.Bat

Let the consol run as normal

The server does not start.

### Expected behaviour

Server to start

### Additional information

This is a fresh install and didn't touch much of anything other than naming the directory folder and accepting the EULA.

**Comment by Raidobw2** [comment]
Hello, please check my message at #578 and let me know if that fixes it for you. You'll basically need to use another Java 8 version to start the server, I recommend Java 8 update 312. Currently, you are using Java 8 update 321 which is incompatible with that version of the modpack.

**Comment by KickaBytes** [comment]
> Hello, please check my message at #578 and let me know if that fixes it for you. You'll basically need to use another Java 8 version to start the server, I recommend Java 8 update 312. Currently, you are using Java 8 update 321 which is incompatible with that version of the modpack.

That fixed the issue! Thank you!
