### ISSUE TITLE
[Bug]: Cursed Earth quest is lacking the tag for detecting when you look at the block for completion and other things

### ISSUE THREAD

**Issue by GriSphera** [FTBTeam/FTB-Modpack-Issues#659]
### Modpack

FTB University 1.16

### Modpack version

1.4.0

### Describe the bug

Cursed Earth is a bit funky at the moment. For example, it's quest isn't detecting when it should activate. It says and is desingned to trigger when you look at the placed block, but it is lacking the tag, so it isn't working. Adding it back solves the problem. 
"cursedearth:cursed_earth".

The other issues are probably with the mod itself, but I'm not sure because I can't seem to find anything about it, not even in the mod page, apart from one testimony in the FTB discord and my own experience, so I'm not sure if it is something mod or modpack related.

The first one is that the block isn't burning in sunlight, but the server config by default says that it should. Not only that, but also the block can and will spread into other dirt blocks, something that should also only happen in the darkness. Again, I'm not sure if this is mod specific, but I can't find anything about it.

The second one is that the block doesn't shows it's spawns when you sneak-right click on it, neither when holding it nor in world.  Again, I couldn't find anything like and issue or a comment in regard to this. 
This function is  only mentioned by the mod page though. It is not adressed in the modpack, so it may just be that it doesn't applies to this version of the mod.  

### Steps to reproduce

1. Enter or create any world in this version of the modpack.
2. Place or create cursed earth anywhere. That's the quest issue.
3. Place or create cursed earth under the sun. It probably won't burn out, and if there are dirt blocks under air nearby it will multiply to those.
4. Sneak right click the block with an empty hand. It probably won't do anything. 

### Expected behaviour

Complete the quest when looking at the block, the block burning and not spreading under the sun, and seeing the spawns form it.

**Comment by aaronhowser1** [comment]
Fixed
