### ISSUE TITLE
[Suggestion]: Add Create

### ISSUE THREAD

**Issue by ShakterNano** [FTBTeam/FTB-Modpack-Issues#66]
### Modpack

FTB OceanBlock

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/create

Just a cool mod in general, and even if it's outclassed by other mods functionally it's still nice to have in builds due to its moving parts.

**Comment by MichaelHillcox** [comment]
From what I know and we'll wait for @Sunekaer to confirm this, he feels this mod does not fit in with the packs feel, it is also quite a large mod to add so late into the pack

**Comment by Sunekaer** [comment]
Thanks for the suggestion but create wont be added to the pack as it is right now, maybe if we make a 2.0.0 update for the pack.
