### ISSUE TITLE
[Bug]: World not loading properly after quitting

### ISSUE THREAD

**Issue by Stefan08p** [FTBTeam/FTB-Modpack-Issues#660]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Describe the bug

When I quit my world and join back in right after, it not loaded properly, its basically unplayable, it's not a big deal because all it takes is a modack reset but it's annoying. It maybe a problem with my computer, however it's unlikely. Also I'm using OSX.

### Steps to reproduce

Open the mudpack, then join in a world, quit the world after a while, then join back in immediately.

### Expected behaviour

I hope that this small issue is fixed.

**Comment by Raidobw2** [comment]
Hello do you have an image of the error? You can also add your game log here (the `latest.log` in your `logs` folder for that modpack)

**Comment by Stefan08p** [comment]
It's not an error, the only thing you can do is walk around. Mobs are frozen, machines and item like the Akashic tome, backpack etc. don't work, you just can't open the GUI.
