### ISSUE TITLE
[Bug]: Immersive engineering Toolbox loosing inventory

### ISSUE THREAD

**Issue by SmokeShadowfox** [FTBTeam/FTB-Modpack-Issues#661]
### Modpack

FTB university 1.16

### Modpack version

1.4.0

### Log Files

none available

### Describe the bug

Anything placed in toolbox vanishes from various changes to status. Not sure on exact triggers. Currently running on a dedicated server, have not tested in solo-world. 

### Steps to reproduce

1> make a toolbox (of course)
2> load it with random things like food tools from immersive engineering, wires or blocks.
3> change to creative then back to survival. Or placing it in certain storage containers logging out and back in. (not sure the exact trigger as I have done other things in between those changes before opening or combination of them together will test more in a bit)
4> open toolbox and find inventory empty. 

### Expected behaviour

Toolbox to keep inventory properly

### Additional information

Server is an older gaming pc and is serving to a private network for my kids, wife, and me to enjoy so generally only has 2-3 accounts on at any time.

**Comment by aaronhowser1** [comment]
BluSunrize/ImmersiveEngineering/issues/5230
