### ISSUE TITLE
[Bug]: /ftbteamislandscreate dont work

### ISSUE THREAD

**Issue by andyHandy69** [FTBTeam/FTB-Modpack-Issues#671]
### Modpack

ocean block

### Modpack version

1.1,0

### Log Files

idk

### Describe the bug

i can get an island on my server whit the code , /ftbteamislandscreate  or  /ftbteamislands
help?

### Steps to reproduce

just i try typing in  /ftbteamislands         or      /ftbteamislandscreate but it dont work

### Expected behaviour

 expecting to get a island

### Screenshots

![Uploading 2022-03-11 (1).png…]()

### Additional information

idk

**Comment by Raidobw2** [comment]
Hello, are you creating your island with `/ftbteamislands create`? There is a space between the two words, here's an example:
![create_island_example](https://user-images.githubusercontent.com/17010632/158054659-2294a0e1-8d98-4490-90a6-9f5e5d1f3865.gif)
If that command doesn't work, make sure the server was started with the `start.bat` script.
Let me know if that worked
