### ISSUE TITLE
[Bug]: 512mb of ram

### ISSUE THREAD

**Issue by kubapola1olo** [FTBTeam/FTB-Modpack-Issues#674]
### Modpack

All

### Modpack version

All

### Describe the bug

 When I turn on the any modpack (Ocean Block, Stoneblock 2 etc.), I have 512 mb of ram, but I have 4 gb of ram set in the application.
Minecraft starts up but shuts down in a moment and the screen goes dark. Please help!

### Steps to reproduce

IDK how

### Expected behaviour

To see menu minecraft, not the FTB app.

### Screenshots

![image](https://user-images.githubusercontent.com/83823233/158031681-04020bcc-ebb7-45da-aae8-a5e7270ba528.png)

**Comment by Raidobw2** [comment]
Hello, I've posted instructions for some users on the FTB Discord, next time go there when you have an issue I can easily link you solutions. Here's why and how to fix it:

> You want to press Windows + R and type `SystemPropertiesAdvanced` in the box and click Ok. This will open up a small window, at the bottom you'll have a button for Environment Variables, click it.
> 
> You're looking for any environment variable called `_JAVA_OPTIONS` and set to `-Xmx512M`. This is actually the issue and will always cause your game to use 512 MB of RAM only.
> Delete all the entries associated with it in the top half of the window and the bottom half of the window. Most Apps don't use this and have settings files, just like the FTB App does. Make sure you Apply/hit Ok after.
> 
> Then close the FTB App and Overwolf completely. Open the FTB App again, and now the program will respect the amount of RAM you gave it in each modpack's settings page.

Please close the issue if that did it and cheers

**Comment by kubapola1olo** [comment]
thx for help
