### ISSUE TITLE
[Bug]: Incorrect spelling in Quest description/text

### ISSUE THREAD

**Issue by SeraTheWitch** [FTBTeam/FTB-Modpack-Issues#675]
### Modpack

FTB University 1.12

### Modpack version

1.12

### Log Files

N/A

### Describe the bug

In the blood magic quest, "Tier 1 Sigils", the Divination Sigil is spelt "Division Sigil" and the word "looking" is spelt "loking"

### Steps to reproduce

1. Open the quests gui
2. Open blood magic
3.  Click "Tier 1 Sigils" quest

### Expected behaviour

Division -> Divination and loking -> looking

### Screenshots

![16471401098641549432685](https://user-images.githubusercontent.com/96894840/158042962-d47ce3cb-4128-48c8-b9ca-7bc98d9f9a7d.jpg)

**Comment by Raidobw2** [comment]
Thanks for the report

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
