### ISSUE TITLE
[Bug]: Immersive Engineering blast furnace Preheater has bugged appearance

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#678]
### Modpack

FTB University

### Modpack version

1.4.0

### Describe the bug

Upon first placement of newly created Blast Furnace Preheaters from Immersive Engineering, it appears that it has somehow gotten railgun (I think?) textures attached to it in some way. placed the first one and thought it looked a bit weird, so I plonked the other one down in the middle of the room and Ohmy

### Steps to reproduce

1. build preheaters according to standard recipe
2. place them wherever 
3. boggle at the weirdness

### Expected behaviour

Normal preheater appearance

### Screenshots

![2022-03-15_02 42 04](https://user-images.githubusercontent.com/1612570/158323858-bce409a0-04b8-4399-a26c-82fa88140630.png)
![2022-03-15_02 41 48](https://user-images.githubusercontent.com/1612570/158323856-1f4ddc28-517f-429a-8547-af7d8d38a1ca.png)
![2022-03-15_02 41 57](https://user-images.githubusercontent.com/1612570/158323857-d22f5904-79ac-4f74-b435-5251bed401c5.png)

### Additional information

standard installation, no other mods or tweaks applied, no optifine.

**Comment by Raidobw2** [comment]
What version of Immersive Engineering is in your mods folder? Apparently that is fixed after `ImmersiveEngineering-1.16.5-5.0.6-141.jar`, see https://github.com/BluSunrize/ImmersiveEngineering/issues/5131

The latest version of University should have `ImmersiveEngineering-1.16.5-5.0.7-143`
Let us know and thanks for reporting!

**Comment by WebDragon** [comment]
Apparently it has not persisted over the last reboot I just did this morning, and I have NO idea what caused it. Haven't diddled with the resourcepacks either. 

the version is whatever is default with 1.4.0, so lessee ... ImmersiveEngineering-1.16.5-5.0.6-141, so wait, did you update in the meantime and I didn't notice ? You DID, you sneaky folks, you.  OK so imma update, and hopefully that resolves this. gonna close for now and will report back if symptoms persist
