### ISSUE TITLE
[Bug]: Crash on Launch

### ISSUE THREAD

**Issue by SaltSouls** [FTBTeam/FTB-Modpack-Issues#679]
### Modpack

FTB OceanBlock

### Modpack version

1.11.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8257838/latest.log)

### Describe the bug

The game crashes immediately upon starting.

### Steps to reproduce

1. Install latest pack.
2. Start game.
3. Crash.

### Expected behaviour

Should start like normal.

**Comment by Raidobw2** [comment]
See #677, it's a Java error
