### ISSUE TITLE
[Suggestion]: New Mod: Agricraft

### ISSUE THREAD

**Issue by Tannan1** [FTBTeam/FTB-Modpack-Issues#68]
### Modpack

FTB Oceanblock

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/agricraft

With all the seeds  from Mystical Agriculture, Farmers Delight, Thermal Series ect it would be nice to do something more than just planting=harvesting them. This mods big focus is on plant breeding. Breed wheat seed with another and the "child" will have better stats like growth speed and amount gained per growth sequence.

This mod has compatibility with Botany Pots and every other crop mod in FTB Oceanblock

**Comment by Sunekaer** [comment]
Thanks for the suggestion, we tested the mod doing beta and just found way to many issues with and therefor at the current state of the mod it wont be added.
