### ISSUE TITLE
[Bug]: chest inventory

### ISSUE THREAD

**Issue by Magma10k** [FTBTeam/FTB-Modpack-Issues#680]
### Modpack

FTB Academy 1.16

### Modpack version

1.3.0

### Describe the bug

Can't open any chest inventory 

### Steps to reproduce

Go into a survival, find/place a chest, try and open it, can't

### Expected behaviour

The chest to open and for me to see its inventory

**Comment by Raidobw2** [comment]
Hello, do you have a picture describing the issue? Also, are you in the claimed chunks or someone else?

If you are in claimed chunks, they need to add you as an ally or member before being able to interact with chests and other blocks
