### ISSUE TITLE
[Bug]: unable to make Immersive Engineering Concrete

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#681]
### Modpack

FTB University

### Modpack version

1.5.0

### Describe the bug

IE Concrete can't be made due to fact that the Blast Furnace insists on making Thermal Slag and not IE slag, but they are not 100% recipe-interchangeable

### Steps to reproduce

make some steell in the Immersive Engineering Blast Furnace (or Improved one)
try to make IE Concrete instead of standard concrete powder but fail
Search for IE Concrete in JEI, find it, attempt to click it into the crafting table, but also fail

### Expected behaviour

IE concrete should exist alongside the rest, and I'd expect an IE machine to make IE Slag OR that the recipe would work cross compatibly

### Screenshots

![FTB University 1 16 3_17_2022 2_13_49 AM](https://user-images.githubusercontent.com/1612570/158829361-ffbcd18c-fdd3-4751-a607-03c0fc7bd8c8.png)

**Comment by aaronhowser1** [comment]
This recipe is very stubborn, a replaceInput wasn't fixing it (which was already in existing versions, ig I didn't check if it worked). Fully removed the recipe and added my own, thank you for the report.
