### ISSUE TITLE
[crash]: Not 1 ftb build does not start

### ISSUE THREAD

**Issue by zzZver01** [FTBTeam/FTB-Modpack-Issues#684]
### Modpack

FTB Presents SkyFactory 3

### Modpack version

3.0.21

### Log Files

https://github.com/zzZver01/log.git

### Describe the bug

Not 1 ftb assembly does not start, in all assemblies 1 and too. I can't figure out why it doesn't work

### Steps to reproduce

I start the assembly, it reaches the middle of the launch and throws out

### Expected behaviour

want to play(

**Comment by Raidobw2** [comment]
Hello, we do not support cracked launchers. `[21:57:32] [Client thread/INFO]: used the old auth tlauncher service`. You will need to buy the Java version of the game on https://www.minecraft.net/ and you can then use the FTB App to play any Feed the Beast modpack https://feed-the-beast.com/app or any other modpacks on CurseForge https://www.curseforge.com/minecraft/modpacks.
Thank you for your comprehension

**Comment by zzZver01** [comment]
> 

if I now go from an adequate launcher and I get the same error, will you help me?
