### ISSUE TITLE
[Bug]: How? Storage drawers compacting drawers not properly utilizing inputs 

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#685]
### Modpack

FTB University 

### Modpack version

1.5.0

### Describe the bug

HOW did you crazy cats manage to break storage drawers? 

 the inconsistent behaviour of inserting ingots into compacting drawers right now is going to drive me utterly **bnans**. 

I have to insert (deliberately) nuggets in the first drawer segment or most of them assume I don't want it to have nuggets, it only fills two of the three slots. 

LEAD however, despite the fact you can make nuggets of them, if you put the nugget in the drawer, then that's ALL you get. can't also insert ingots and blocks. But put in a lead ingot and boom no nuggets.

Most of the other ingots types are similarly bugged; if I find any other outliers like Lead, I will follow up this initial report with more specifics.

### Steps to reproduce

1. make new empty compacting drawer
2. put in ingots
3. attempt to also put in nuggets
4. blink repeatedly in disbelief

### Expected behaviour

inserting ingots autofills blocks and nuggets, inserting blocks autofills ingots and nuggets, inserting nuggets autofills ingots and blocks, each with their respective placeholders

### Screenshots

![2022-03-19_00 20 39](https://user-images.githubusercontent.com/1612570/159107528-46699b5a-f316-4987-8bd4-987f6305fd5c.png)
I have never before in my life experienced compacting drawers behaving in this manner

### Additional information

'smee again. rackin up those bug report miles

RE: the Copper and Lead above, both ingots and nuggets are Thermal Series; literally created the nuggets in-hand with one of the ingots I was trying to insert, because it didn't auto-populate the nugget slot with the respective item

**Comment by WebDragon** [comment]
update: neither Nickel nor Zinc exhibit the bug. when ingots are inserted, placeholders are made for both blocks and nuggets.

**Comment by zoller27osu** [comment]
the "not populating the nugget slot unless you use a nugget in the lower right slot" thing I have seen before, but the Lead thing is definitely a modpack issue

**Comment by WebDragon** [comment]
I've literally never seen storage drawers do this thing before this pack, and I've been farting around with FTB packs since  Infinity Evolved.

**Comment by aaronhowser1** [comment]
jaquadro/StorageDrawers/issues/1021
