### ISSUE TITLE
[Bug]: Same crash on launch for multiple modpacks.

### ISSUE THREAD

**Issue by sixtrx** [FTBTeam/FTB-Modpack-Issues#688]
### Modpack

FTB Academy 1.16 / FTB University 1.16

### Modpack version

FTB Academy 1.3.0 / FTB University 1.5.0

### Log Files

https://bytebin.lucko.me/nUwodQ0skK

### Describe the bug

MineTogether refused to load and I'm not really using it  so just deleted it 
(MineTogether (minetogether) encountered an error during the sided_setup event phase).

But now I have this error which probably about a mods called "Rhino" and "KubeJS UI". Tried to manually update/reinstall did not work.
Thanks.

### Steps to reproduce

1. Install mod packs via MultiMC.
2. Launch mod packs via MultiMC.

### Expected behaviour

I expected the launch the game.

### Screenshots

![2022-03-23 03_29_34-](https://user-images.githubusercontent.com/45739801/159598903-88b2b560-a0c8-453e-8d26-c42cc2de4851.png)

### Additional information

Clean installation of Java did not fix the problem.

Java VMs I've tried:

1. IBM Semeru OpenJ9 8u312b07 x64
2. Java 8u321 x64 (Classical HotSpot from java.com)
3. Eclipse Adoptium OpenJDK 11.0.13_8

Reinstalling modpacks also did not work.

**Comment by Raidobw2** [comment]
If you remove MineTogether then you'll have to remove the main menu script otherwise it'll crash.
`kubejs/client_scripts/main_menu.js` needs to have that block removed:
```
// If MT is loaded
        if (Platform.mods.minetogether.id) {
            //MineTogether friends list
            ui.button((b) => {
                b.name = Text.translate("minetogether.multiplayer.friends");
                b.color = textColor;
                b.hoverColor = textHoverColor;
                b.width = 70;
                b.x = ui.width - b.width - 5;
                b.y = 5;
                b.action = "minetogether:friends_list";
                b.shadow = false;
            });

            //MineTogether chat
            ui.imageButton((b) => {
                b.width = 20;
                b.x = ui.width - b.width - 77;
                b.y = 5;
                b.action = "minetogether:chat";
                b.texture = "ftbacademy:textures/menu/chat.png";
            });

            //MineTogether order server
            ui.imageButton((b) => {
                b.width = 20;
                b.x = ui.width - b.width - 5;
                b.y = ui.height - b.height - 5;
                b.action = "minetogether:order";
                b.texture = "ftbacademy:textures/menu/creeper.png";
            });
        }
```
Otherwise if it crashes on a default install or without that code block, then you can add the game log here.

Also consider using the FTB App to support our work. https://feed-the-beast.com/app

**Comment by sixtrx** [comment]
> 

Fixed with removing provided code block, thanks.
