### ISSUE TITLE
[Bug]: Ocean Block Cannot Connect to public server

### ISSUE THREAD

**Issue by HalogenicSun** [FTBTeam/FTB-Modpack-Issues#689]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Log Files

https://pste.ch/irerevusul.md

### Describe the bug

Can not connect to any server. It instantly closes the connection and says disconnected

### Steps to reproduce

1. connect to server
2. cry

### Expected behaviour

Let the client stay log into the server

### Additional information

The version of ReAuth is out of date and cannot relog accounts anymore.

**Comment by Raidobw2** [comment]
Hi, the server refused your connection: `io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused`. Can you try another one or check with the host/owner for potential issues, such as the firewall blocking connections?

**Comment by HalogenicSun** [comment]
it looks to be an issue with the server, since the client was able to connect to the 2 or 3 other servers ive tried.

**Comment by Raidobw2** [comment]
I'll go ahead and close this in that case 👍
