### ISSUE TITLE
[Bug]: "Let the flux build"

### ISSUE THREAD

**Issue by zoller27osu** [FTBTeam/FTB-Modpack-Issues#690]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.22.0

### Describe the bug

Unable to complete the "Let the flux build" research task in Thaumcraft to unlock the researches of how to cleanup Flux.
"Wuss mode" is enabled in the configs, but even if you turn that off, Flux Portals do not spawn.

Is it intended that the Crimson Rites have to be completed to unlock the Flux researches (via Void Seed from infusion recipe smelted in a furnace for Void Metal Ingots) or?...

### Steps to reproduce

1. Let the flux in your chunk build to 3/4 the vis cap (or something like that)

### Expected behaviour

A Flux Portal should spawn, or some other method of completing the research

**Comment by Raidobw2** [comment]
I'll have to investigate when I get the time, thanks for the report. Wuss mode being activated is intentional though, but it looks like it could have an undesirable side effect.

**Comment by zoller27osu** [comment]
Turns out you literally can't grow vis crystals with any flux in the chunk... so I sure would like to be able to clean that up

**Comment by zoller27osu** [comment]
The ProjectE Tome of Knowledge allows you to print Primordial Pearls, which solves the upper half of the previous comment for the very late game.
Ancient Stone, Eldritch Stone, and Apprentice's Rings still cannot be acquired at all, however.

**Comment by MajorPoison** [comment]
> Turns out you literally can't grow vis crystals with any flux in the chunk... so I sure would like to be able to clean that up

especially since flux leaks between chunks...

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
