### ISSUE TITLE
[Bug]: Bad Login

### ISSUE THREAD

**Issue by Shadowkenny** [FTBTeam/FTB-Modpack-Issues#691]
### Modpack

FTB Mind Crack

### Modpack version

8.3.2

### Describe the bug

Every time I wanna Join my Nitrado Server(is installed for FTB Mindcrack) i can't login with the FTB client.

### Steps to reproduce

Start MindCrack through FTB Client
go to Multiplayer
Click on Server to connect
Connection Lost Failed to Login: Bad Login

### Expected behaviour

that i can login. Since update i can't join

### Screenshots

![image](https://user-images.githubusercontent.com/17010632/159764139-dbcc9fb7-5248-498a-ba7c-ce3667a28b16.png)

**Comment by Raidobw2** [comment]
Looking into it, give me 2-3 hours to find something to fix that with the team. I know a workaround but I don't prefer it at all, I'll try and see if there's a better solution. Thanks for your patience in advance

**Comment by Shadowkenny** [comment]
Any News from my Problem?

**Comment by Raidobw2** [comment]
Yes sorry, thanks for reminding me. You can change `online-mode=false` in your `server.properties` file. I highly recommend having good backups every 1 or 2 hours as well as using a whitelist (enabled in `server.properties` as well). Let me know if that works, and make sure you have automated backups, that's really important.

**Comment by Shadowkenny** [comment]
It worked after much trying. Thank you very much for the help!
