### ISSUE TITLE
[Bug]: FTB Beyond crashes in Forge

### ISSUE THREAD

**Issue by aonaem** [FTBTeam/FTB-Modpack-Issues#693]
### Modpack

FTB Beyond

### Modpack version

1.11.0

### Log Files

https://www.toptal.com/developers/hastebin/udepamakot.yaml

### Describe the bug

When I start the mod Forge starts working. After a few minutes of loading in Forge, the program suddenly stops working and crashes. I screenshotted the fail report in the console and copied the log into the hastebin link. I think its probably a problem of my laptop, but I am not able to see whats the issue.

### Steps to reproduce

1. Open the FTB Launcher
2. Download FTB Beyond
3. Start the Modpack
(4. The modpack crashes in Forge after a minute of loading)

### Expected behaviour

The Modpack opens and I can play it

### Screenshots

![Screenshot (4)](https://user-images.githubusercontent.com/102372919/160151935-5103cee7-f889-43e7-af12-f95a299092c3.png)
[hs_err_pid4380.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8351880/hs_err_pid4380.log)

**Comment by Raidobw2** [comment]
That looks like an error with Intel Drivers (and hardware acceleration). You can attempt some fixes listed on https://bugs.mojang.com/browse/MC-32606 such as the VBOs in Video Settings and updating/downgrading your driver.

**Comment by manmaed** [comment]
This issue is stale and pack is no longer being worked on
