### ISSUE TITLE
[Bug]: Quark Bee variant causing crash

### ISSUE THREAD

**Issue by drkanbs** [FTBTeam/FTB-Modpack-Issues#695]
### Modpack

FTB University

### Modpack version

1.16

### Log Files

https://crashy.net/1etCWH14FK77UkfIIi2p

### Describe the bug

I placed the Bee Farm and it crashed, showed me that it was trying to place a bee that didn't quite exist?

### Steps to reproduce

Place a Bee farm, in particular I was placing mine in a meadows biome.  That's all there is to it, I don't know if it will reproduce, but it won't let me into the same save anymore. 

### Expected behaviour

Place a Bee farm, so I can...farm bees

**Comment by Raidobw2** [comment]
Hello, please edit `config/quark-common.toml` in your files and change the following to false:
`"Enable L G B T Bees" = true` becomes
-> `"Enable L G B T Bees" = false`
Then play the game and let me know if that is fixed, that could be a bug

**Comment by drkanbs** [comment]
It worked, there was no crash and the bee farm remained.  Thanks!  guess
that'll need adjusting or something huh?

**Comment by Raidobw2** [comment]
It would have, although it looks like version 1.5.0 of University already contains that configuration... Make sure you are using version 1.5.0 of FTB University 1.16.5
(Tested with a fresh server installation)
![image](https://user-images.githubusercontent.com/17010632/160737332-3bd61781-e1bb-42b0-b79e-7d490f122542.png)
As a result of this already being configured properly in 1.5.0, I will be closing this

**Comment by nickjbenson** [comment]
The line you're pointing to in that image is not the same line you referred to for the crash fix:
![image](https://user-images.githubusercontent.com/4485426/164929055-74a6dac6-d889-4aa7-b465-ac9090874b42.png)

As of 1.5.0 the second line is still set to "true" by default. Setting it to "false" fixed the crash for me as well.

**Comment by Raidobw2** [comment]
You're right, I missed that. Our pack dev will be able to change the config for a future update

**Comment by aaronhowser1** [comment]
Disabled in dev
