### ISSUE TITLE
[Bug]: Crash while teleporting using RFTools matter receiver, with newly acquired dog in tow.

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#696]
### Modpack

ftb University 1.16

### Modpack version

1.5.0

### Log Files

[crash-2022-03-28_02.39.04-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8360389/crash-2022-03-28_02.39.04-client.txt)

### Describe the bug

after arriving home from exploring with new dog in tow, I teleported to my base and discovered dog teleported with me, so I did it again to the other nearby matter receiver near my blood magic area, saw dog teleported too, went 'cool' and proceeded to teleport back to my basement again, only to be met with the crash

### Steps to reproduce

not sure if reproducible

### Expected behaviour

normal arrival at matter receiver

### Additional information

it crashed so hard it was apparently having trouble writing a save file and I might need to restore a previous backup because I was forced to kill it with task manager for slowing down the whole system long enough I feared to attempt to let it finish

**Comment by WebDragon** [comment]
oh yes, and it was broad daylight, not dawn/dusk/night at the time

**Comment by aaronhowser1** [comment]
[Pastebin version of crash](https://pastebin.com/3Nq8ZXCr)
