### ISSUE TITLE
[Bug]: Applied Energistics pattern terminal shows thermal machine recipes as without an output

### ISSUE THREAD

**Issue by hRobert12** [FTBTeam/FTB-Modpack-Issues#698]
### Modpack

FTB OceanBlock

### Modpack version

1.12.0

### Describe the bug

When attempting to use JEI to make a processing pattern for a thermal recipe in AE2, it will say that the recipe has no outputs.

### Steps to reproduce

1. Setup an AE2 network with a pattern terminal
2. In JEI, look up a recipe in a thermal machine
3. Hover over the plus to see that you cannot fill in the recipe because "Recipe has no output"

### Expected behaviour

I can fill in the recipe

### Screenshots

![2022-03-28_22 13 06](https://user-images.githubusercontent.com/15806419/160538569-568d85b0-d549-4ea7-b037-0e822f55d3ae.png)

**Comment by Raidobw2** [comment]
I've asked in their Discord at https://discord.com/channels/399037120930512897/434101214548852746/958560363157291048, I'll wait for an answer.

For now you can manually put the ingredients and results in the recipe pattern and it will work.

**Comment by Raidobw2** [comment]
Hmm apparently this mod https://www.curseforge.com/minecraft/mc-mods/not-enough-energistics fixes it. Can you install the 1.16 version in your mods folder and let me know if that fixed the issue? Thanks

**Comment by hRobert12** [comment]
With not enough energistics, I can click the plus button now, but all of them show as yellow and it fills in the wrong ingredients for the pack. (Such as filing in a Mekanism diamond dust when you can only get the thermal diamond dust.)

**Comment by Raidobw2** [comment]
Hmm I see. The diamond dust represents a bigger problem, since it's basically using the Forge ore dictionary. That diamond dust must be higher in the list. This is kinda hard to fix since we'd have to remove the ore tags on all unused products. If you enable ore substitutions in the pattern terminal, can you check if the recipe works? In my opinion that might be good enough, since the recipe is using ore dictionary itself anyways.

**Comment by hRobert12** [comment]
Unless I missed something, you can't enable substitutions on a processing recipe in AE2.
