### ISSUE TITLE
[Bug]:  After restarting game single player world resets

### ISSUE THREAD

**Issue by MoonEclipses** [FTBTeam/FTB-Modpack-Issues#699]
### Modpack

FTB University 1.12

### Modpack version

1.2.1

### Describe the bug

When launching the game and entering world after restart, all world progress resets everytime. The world is becoming like just genereted. 

### Steps to reproduce

1.Create new world
2.Do something on map
3.Restart game
4.enter world again

### Expected behaviour

world not resets

### Additional information
In the start of the world i went to the other generation dimension (not sure which), maybe it 
related to problem

**Comment by Raidobw2** [comment]
Hello, how are you quitting the game after a play session? With the save and quit button?

As well, if your instances are in a synced location (for example by OneDrive) try moving that instance to a non-synced location.
Feel free to bring me more information, as I have little to work with right now!

**Comment by MoonEclipses** [comment]
I made some researchs. That issue happens only in worlds where you go into dimension with other generation(quest with portals).  I tried only first portal.

**Comment by Raidobw2** [comment]
Hmm that is odd. Avoid those dimensions for now. Our modpack dev will verify if they can replicate it. If they can't replicate it, they might be closing this issue as we would not be sure what's causing the issue

**Comment by aaronhowser1** [comment]
I'll likely end up removing the mod entirely honestly. It causes a LOT of problems
