### ISSUE TITLE
[Bug]: Performance Issue While Crafting

### ISSUE THREAD

**Issue by wyndman** [FTBTeam/FTB-Modpack-Issues#7]
### Modpack

FTB Oceanblock

### Modpack version

1.00, 1.10

### Describe the bug

When crafting items are slow to drag into the crafting table, both the normal crafting table and within inventory. Crafting over all is sluggish and slow to respond. This was in both version 1.00 and the latest release. No other aspects if the game are affected ie blocks break normally etc.

### Steps to reproduce

Open inventory craft planks into sticks experience a slow down. More so when crafting larger items using a crafting table.

### Expected behaviour

Items to move at a normal responsive rate.

**Comment by Sunekaer** [comment]
I can not reproduce this issue in my dev, can you provide more information on this? 

What crafting table are you using?
Does It happen with other crafting tables from other mods?
Can you show the issue?

**Comment by wyndman** [comment]
I tracked the issues down to the Blur mod, it seems that it will put a tremendous strain on the GPU while in use. I've disabled it and can now enjoy the pack!
