### ISSUE TITLE
[Bug]: No recipe for RFTools Destination Analyzer

### ISSUE THREAD

**Issue by Seegras** [FTBTeam/FTB-Modpack-Issues#70]
### Modpack

FTP University 1.16

### Modpack version

1.2.0

### Describe the bug

The RFTools Destination Analyzer has no recipe

### Steps to reproduce

Try to craft the RFTools Destination Analyzer

### Expected behaviour

The RFTools Destination Analyzer has a recipe

**Comment by aaronhowser1** [comment]
Removed the quest since it apparently isn't implemented
