### ISSUE TITLE
[Bug]: Odd stuttering with DireWolf20 1.7.10 mod pack

### ISSUE THREAD

**Issue by MinkeWhalinton** [FTBTeam/FTB-Modpack-Issues#700]
### Modpack

DireWolf20 1.7

### Modpack version

1.7.10

### Describe the bug

Hi, I haven't played modded Minecraft in a while and I wanted to play it again. However, I am experiencing some kind of odd stuttering in the game while playing in this specific mod pack, Direwolf20 1.6.4 doesn't stutter, Direwolf20 1.16 doesn't stutter and neither do other packs such as 1.16 University. I originally thought it was due to low FPS but this is not the case as my game was reporting way above 200 FPS. So I load into the world, get a huge lag spike which is to be expected because all the chunks are loading in, I play for the first minute or so and it's relatively smooth, but then there is this really odd effect where if I walk in a straight line, the game stutters like if you were to pause and then unpause a video over and over again.  If I was to look side to side, I would have the same thing happening, so would running and jumping around the world. Then it would look like my mouse cursor would be stuttering a bit as well. I'm not sure if this is a problem with my PC, my Java. I have allocated more than enough RAM, I allocate 8GB, still had the stuttering, then 12 and then 16, still had the same issue. When I played this pack previously, I did not have this issue, I'm not sure what is wrong or what is causing this so if anyone knows what is happening and knows how to fix it, it would be great if you could lend a hand, a detailed explanation of the steps to fix it would be nice as I am not well versed in the world of modding or coding. I'm not sure exactly if this is a bug or if it's something to do with my PC, so if it is something to do with my PC, shedding some light on how you fixed it if you had this issue before would be much appreciated! :D

### Steps to reproduce

I'm not sure what to put in here to reproduce it but I set my RAM at 8GB, 12GB and then 16GB. I downloaded the pack normally off of FTB, launch the instance from FTB as usual.

### Expected behaviour

I just expected to get back into playing modded Minecraft and have a seamless experience without stuttering

**Comment by Raidobw2** [comment]
Hi, I tried to replicate the issue yesterday on a local instance but couldn't. I might have some questions in that case to see what differs from your game than mine.

- Are you using any java arguments? These are found in the settings of the modpack on the FTB App
- Allocate at most 5GB, this is sufficient to run the game
- Are your drivers up to date, including those from the graphics card, if you have one?
- Make sure an antivirus is not running in the background or that your CPU/Disk is being used a lot. Basically everything on a computer passes by the "bus", which is like an electron highway. All information passes on there. If the Disk's work is very high for example, then a lot of data may be passing onto that bus. This can cause the rest of the information from other components to basically enter a "traffic jam", so they have to wait that some information passes. Sometimes that can cause stutters, or short freezes.
- If other modpacks look okay, then it's likely not thermal throttling (when components become too heated and with reduced efficiency). Although it's always good to check that information. I use CPU-Z and GPU-Z for temperatures. Windows has the GPU temperature in Task Manager as well.

Let me know about the points above and if you think it can be related to any of those, thanks

**Comment by MinkeWhalinton** [comment]
Hi Raidobw2,

I will follow these steps and I will let you know the results, if the issue persists, is there a way to upload a short video? Stuttering can not be obviously shown in screenshot picture form.

**Comment by Raidobw2** [comment]
There is yeah sure, I personally use OBS to record videos, although you can pick any video recorder out there. I think Overwolf has a way to do it as well (probably through an app in the store) and Nvidia GeForce Experience can record the screen too. You'll find quick guides for these on the web. As far as I know simply drag and drop the MP4 or video files here, and leave a space before and after the link and it will be embed.

**Comment by Raidobw2** [comment]
You can likely put it on any cloud service such as Google Drive and share the link here, that works too

**Comment by MinkeWhalinton** [comment]
Ahh right, yes didn't think of that haha!

Here it is, this is just me panning and walking around in the world with all the parameters I mentioned above:
https://drive.google.com/drive/folders/1r8OsG-ENdUWfSyJzPVqxvaB1R-_T0cST?usp=sharing

**Comment by Raidobw2** [comment]
Hmm I see. Are you using Vsync in Video Settings? (Try it if not using it). As well, it still looks like your frames drop for a fraction of a second -- you're at 200 frames, then suddenly quickly drop to 130 and back up to 190. Are you using any Java arguments for garbage collection?

As well, I'd also recommend to check with the CurseForge App what kind of performance you get. This old pack should be available I think on CurseForge. Do your tests with 6GB of RAM it's plenty. Sometimes arguments are different by a little bit between launchers, and this would be a good test for validating if it's the software or hardware that could be at cause. Hopefully this gives us more information!

**Comment by MinkeWhalinton** [comment]
Yes hi,

Sorry for the late response, I was busy with school assignments for the past couple of days. I did try the Vsync for FTB, did not work too well. I play tested CurseForge as you recommended, exited and reloaded the game multiple times, works like a charm, no stuttering (I did these tests on 3GB RAM). This is definitely strange.

**Comment by Raidobw2** [comment]
Hello again, thanks for the reply. It looks like there might be a little something that's different between the two launchers then. I can look that up on my side and investigate with the team. Although I don't recommend doing that for all FTB modpacks since updates come on the FTB App only for newer content, for that one I'd say to use the CurseForge App if it works. Let me know if you are fine with that for this modpack; if yes you can close this issue.
Good success to you on your studies as well!
