### ISSUE TITLE
[Bug]: Blood Magic sigil of blood lamp accidental skyward firing persists across reboots frozen in mid-air

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#701]
### Modpack

FTB University 1.16

### Modpack version

1.5.0

### Describe the bug

they're just hanging there in the sky. you can't interact with them in any way, and they don't seem to be doing anything. I suspect its a remnant of an accidental firing off of the blood magic Sigil of the Blood Lamp, into the sky, instead of nomming the food I intended to eat, because I scrollwheeled too far on the hotbar, but why it should persist is a mystery

### Steps to reproduce

accidentally shoot some bood lamp sigils off into the distance with only sky as the target
come back later after several reboots 
attempt to wipe shmutz off your screen
realize that it isn't shmutz and investigate

### Expected behaviour

once they reach the distance that mobs cease moving, without hitting a target, I would think they should merely disappear

### Screenshots

![2022-03-29_06 41 35](https://user-images.githubusercontent.com/1612570/160596075-8c4d60bf-5883-4b33-b61b-125dfca66e1c.png)
![2022-03-29_06 44 12](https://user-images.githubusercontent.com/1612570/160596068-efb13044-4fd2-46b4-8652-4cc81188eed1.png)
![2022-03-29_06 44 39](https://user-images.githubusercontent.com/1612570/160596070-0c63ae0d-e68d-419f-836d-858b7e682173.png)
![2022-03-29_06 45 57](https://user-images.githubusercontent.com/1612570/160596072-a7fbc335-3593-462e-acea-e105ba66b564.png)

**Comment by Raidobw2** [comment]
Reported ^
