### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 3less** [FTBTeam/FTB-Modpack-Issues#705]
### Modpack

BetterMinecraft 1.16.5

### Modpack version

v56 

### Log Files

Not possible i play on a public server and singleplayer has no error Logs to this problem

### Describe the bug

In the Quest Book we have at the End Section:
-Enter End Dimension
- Kill the Dragon
- Kill the Ender Golem
- Kill a Ender Guardian
- Kill the Shelterer (Optional)
- Summon and Kill a Void Worm

The Ender Guardian/Ender Golem are from the Cataclysm Mod. I asked the Mod Owner and he said the Issue is from FTB Teams/Quests. You can kill the Ender Guardian with a Sword or Void Runes but it doesnt count. You can rejoin/relog, restart your Minecraft/PC but nothing happens. You can drop the Gauntlet of Guardian (Drop) and pick it up again nothing happens.

The Problem is you cant go forward if u dont complete the Quest. (Forward to Abyss) 

### Steps to reproduce

1. Enter the End / Kill the Dragon / Kill a Ender Golem
2. Find a Ruined Citadel and kill the Ender Guardian (basement) 
3. There you go! You dont got the achievment on the Quest Book
4. 

### Expected behaviour

Completed Quest and Reward which u can get from the Quest Book

### Screenshots

![Quests](https://user-images.githubusercontent.com/86152560/160924548-b3f3115c-5b4c-43b7-b274-f3520ae6a84c.PNG)
![Quest1](https://user-images.githubusercontent.com/86152560/160924554-ca259a04-f02b-4e25-a8b6-a7b561aa6a1d.PNG)

### Additional information

Please fix that bug. The Server is only updating all 3 Months so it dont interest me, but its not nice for every other Player.
FROM THE CATACLYSM MOD!!

**Comment by Raidobw2** [comment]
Hello, please use their respective modpack issue tracker to report the issue: https://github.com/LunaPixelStudios/Better-Minecraft/issues.
We take here problems with our modpacks, and that is not one of them.
If the authors of that modpack are unable to fix it through verifying and configurating the quest or through scripts, then they can make a report on https://github.com/FTBTeam/FTB-Mods-Issues/issues and we will look at it.
Thanks
