### ISSUE TITLE
[RFE]: make sure to clear the curio slots for schools

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#707]
### Modpack

ftb university 1.16

### Modpack version

1.5.0

### Describe the bug

dunno if anyone's made the suggestion/RFE yet, but for the school for the Rannuncarpus, you might want to hide a floating solegnolia below the platform, so that when you flip the switch, the Ring of Magnetization you're wearing that wasn't swapped away by the school command, won't suck up all the dropped stone blocks before the rannuncarpus can do its thing

either that or also make sure to clear and reset the curio slots when entering or leaving the schools

### Steps to reproduce

enter school
curio slots are not cleared so my ring of magnetization continues to work and sucks away the stone before the rannuncarpus can place them

### Expected behaviour

curio slots cleared or floating solegnolia hidden below platform to negate the ring

**Comment by Raidobw2** [comment]
Thanks for the report
