### ISSUE TITLE
[Bug]: error when breaking forestry engines

### ISSUE THREAD

**Issue by teathebest** [FTBTeam/FTB-Modpack-Issues#708]
### Modpack

ftb university 1.12 

### Modpack version

1.2.1

### Log Files

when it didn't crash  [crash-2022-03-29_16.48.46-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8387220/crash-2022-03-29_16.48.46-client.txt)
when it did
[crash-2022-03-31_01.43.00-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8387235/crash-2022-03-31_01.43.00-server.txt)

### Describe the bug

when breaking an forestry engine it will say there was an error and the block will not drop. and  if you place a block where the engine was it will do the give another error and remove my item when broken . also when I walked on the area where the engine was and placed another block my game crashed.

### Steps to reproduce

1. Place a forestry engine 
2. break the engine 
3. place another block where you had the engine
4. break the other block

### Expected behaviour

what I expected to happen was I would get my block back

**Comment by aaronhowser1** [comment]
Known bug
