### ISSUE TITLE
[Bug]: My game won't start anymore and I don't know why.

### ISSUE THREAD

**Issue by SahneGipfel** [FTBTeam/FTB-Modpack-Issues#709]
### Modpack

FTB Infinity Evolved

### Modpack version

3.1.0

### Describe the bug

Im trying to add AE2 Stuff to my game but now it won't let me open it. It crashes even before I can read the log. 
I've tried many different version of AE2 and Applied energistics but I can't fix it. They say AE2 is only compatible with Applied v2 and not v3 but if i install Apllied v2 it says "Applied v3 is the oldes allowed version" and my game won't start too. Please help me my gf and me really wan't to play together :(.

### Steps to reproduce

1. Install FTB Infinity Evolved
2. Install AE2 stuff
3. Try to run the game

### Expected behaviour

The game will crash while trying to start.

### Screenshots

![screen1](https://user-images.githubusercontent.com/102735721/161048623-e3223423-8773-460c-a9fc-dff2dceb0960.PNG)
![screen2](https://user-images.githubusercontent.com/102735721/161048629-80c97728-aa5f-4e02-8f43-9f3a9edd58c9.PNG)

**Comment by Raidobw2** [comment]
Works for me with a brand new FTB Infinity Evolved 1.7.10 and https://www.curseforge.com/minecraft/mc-mods/ae2-stuff/files/2270295, so try that file. If you reinstall FTB Infinity Evolved make sure you've copied any worlds before doing so.
![image](https://user-images.githubusercontent.com/17010632/161124036-7c166c3d-cc79-4c89-b825-02a22c4f7102.png)
Please close this ticket if that solved it and cheers

**Comment by SahneGipfel** [comment]
Worked our perfectly! Thank you so much! <3
