### ISSUE TITLE
[Bug]: Unable to get Environmental Tech Void Miner working

### ISSUE THREAD

**Issue by Seegras** [FTBTeam/FTB-Modpack-Issues#71]
### Modpack

FTB University 1.16

### Modpack version

1.2.0

### Describe the bug

The automatic build of the void miner does not work. Also, I do not seem to be able to build it by hand, so it gets recognized as multiblock. This wasn't a problem with the solar panels.

### Steps to reproduce

I followed the tutorial by the Environmental Tech author at https://www.youtube.com/watch?v=GB7CvGQ7I40 
- It's looking up at the void, no obstructions
- I do have a program inserted
- I did give it power
- I have an inventory connected
- the structure looks good; I did try with and without modifiers (instead of 2 panels)
Still, the beam does not come up, and the controller says "Duration -1, Tick Cost: 0)

It might be that I'm doing something wrong, but the mod behaves very flaky, the "preview" also does only work partially, and behaves weirdly. 

### Expected behaviour

beam comes up and it starts working

**Comment by zoller27osu** [comment]
The preview option works fine for me on 1.2 and 1.3 and I've used it to build every tier of Void Miner.
If you provide pictures, I could try to diagnose your specific issue for you.

**Comment by Seegras** [comment]
fixed in 1.3.0 anyway
