### ISSUE TITLE
[Bug]: runs at 9 fps 

### ISSUE THREAD

**Issue by Mrskipper309** [FTBTeam/FTB-Modpack-Issues#710]
### Modpack

ftb university 1.16

### Modpack version

1.5.0 

### Describe the bug

it doest use the ram it neads to run smooth 

### Steps to reproduce

1. start Modpack
2. select singlplayer 
3. starts world 
4. runs at 9fps
5. increaseing ram doesnt work

### Expected behaviour

more fps

**Comment by Raidobw2** [comment]
Try this:

> Disabling mipmapping on an AMD graphics card will boost FPS. This is because AMD handles OpenGL mipmapping differently than NVIDIA does, and it makes the graphics card work super hard. Open the menu in-game and click Options, then Video Settings. Slide the Mipmap Levels slider to the left to "OFF", and resume playing.

And this:

> In your modpack folder, open the config folder and the file forge-client.toml with a text editor. Change the setting alwaysSetupTerrainOffthread to true, save the file, and start your game. This setting boosts FPS mostly in Singleplayer, since rendering will be done on a separate thread. It also solves lag related to block placement.

If you still have low FPS add Magnesium to your mods folder for 1.16.5: https://www.curseforge.com/minecraft/mc-mods/sodium-reforged

Please close the issue if that did it!

**Comment by Mrskipper309** [comment]
it helpt a Little bit now it runs at 20-30 fps can i add some more fps mods?

**Comment by WebDragon** [comment]
might recommend going to Settings, & adding the following to the java runtime arguments: 

`
-XX:+UseG1GC -Xmx8192M -Xms8192M -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
`

as well as setting the memory slider to 8.5gb, which should eke out slightly more as well as reducing the lagspikes a tad.

I've been using these for years, worked out by better minds than mine, tweaking them over time as improved versions came along; can't even recall anymore where I found them, but it was around the time of SkyFactory 3 where my laptop at the time was not up to par with the default arguments

**Comment by Mrskipper309** [comment]
it helpt really gut but can i still change something so that it runs smoother (i  have 16bg of ram in my pc)

**Comment by Raidobw2** [comment]
Have you tried Magnesium as suggested?

**Comment by Mrskipper309** [comment]
yes

**Comment by Raidobw2** [comment]
If you turned off mipmaps as well then that's the only things I know of to boost performance. Maybe https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance can help a bit as well. Reduce the render distance and you should get more FPS

**Comment by Mrskipper309** [comment]
thx
