### ISSUE TITLE
[Bug]: Can't cover mekanism cables

### ISSUE THREAD

**Issue by MeeyoMy** [FTBTeam/FTB-Modpack-Issues#713]
### Modpack

FTB University 1.16

### Modpack version

1.5.0

### Describe the bug

Hello, i started playing FTB University 1.16 recently and when i got to Mekanism, i always place cables instead of floor block and just cover them with CB Microblock covers, but when i try to place them on the universal cables, they just place above the cable like a nomral block would, and not inside as it used to in older version of the game, can anyone help me with this issue? 

### Steps to reproduce

1. Place few cables
2. Try to cover them with panel/cover/hollow cover onto them and you can see you can't

### Expected behaviour

The cover places on top of cable within the same block

### Screenshots

![image](https://user-images.githubusercontent.com/73001928/161381018-1a80ebca-d305-478c-bf8d-7eb43aa4e340.png)
![image](https://user-images.githubusercontent.com/73001928/161381027-b3d00b6d-512b-4d22-ae4f-5313c423c475.png)
![image](https://user-images.githubusercontent.com/73001928/161381043-9b4993a8-04b0-44eb-9b9f-9996ccea4d79.png)

**Comment by aaronhowser1** [comment]
This functionality does not exist in 1.16
