### ISSUE TITLE
[Bug]: advancements integrated dynamics are not active

### ISSUE THREAD

**Issue by StephanieUpland** [FTBTeam/FTB-Modpack-Issues#714]
### Modpack

FTB Oceanblock

### Modpack version

1.11.0

### Describe the bug

I want to start working on the 8 advancements of integrated dynamics that are not linked to the main connections. When I click on it, it only says that it's dependencies are the _chunks and ores_ advancements, which I have already achieved. I can't do anything else with them, nor can I seem to find any other reason why I can't make the advancements

### Steps to reproduce

1. go to advancements
2. go to integrated dynamics
3. click on 1 of the 8 separate advancements (doesn't matter which one for me)
4. click on the task to see what item you need to craft
5. nothing happens

### Expected behaviour

I would expect clicking on the task would give me the craftable items and then give me the achievement when I have made the item

**Comment by Raidobw2** [comment]
Hi, hit Escape and then "Open to LAN", and select Enable cheats then start the LAN server. This will give you cheats in your game for a while.

Type in `/ftbquests editing_mode true` to turn on editing mode for quests. For the quests that are problematic, right click them and choose "Complete Instantly". You can also "uncomplete" them and try to complete them again with that trick.

To turn off editing mode, type `/ftbquests editing_mode false`.
To turn off cheats, just Save & Exit and then log back in your world.

Let me know if you managed to fix it that way!

**Comment by quietust** [comment]
Those 8 quests don't actually involve the crafting of any items - instead, they are triggered by unlocking Achievements (technically now Advancements) within Integrated Dynamics.

**Comment by StephanieUpland** [comment]
> Those 8 quests don't actually involve the crafting of any items - instead, they are triggered by unlocking Achievements (technically now Advancements) within Integrated Dynamics.

this actually makes sense... I hadn't realized the achievements are now advancements... going to test it now!

**Comment by TheonlyTazz** [comment]
Those 8 Quests actually work, once you unlock  "Chunk and Ores" quest at the Getting Started Tab

once you then get the Advancements in Integrated Dynamics, those Quests will complete aswell
![grafik](https://user-images.githubusercontent.com/3908847/168580104-767c3853-14e0-48d3-8367-d5563bec323b.png)
