### ISSUE TITLE
[Bug]: Chisels & Bits causing insane lag  (zero FPS)

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#715]
### Modpack

FTB University 1.16

### Modpack version

1.5.0

### Describe the bug

made a diamond chisel & bits chisel after following the hint (wink wink) on the matter condenser to use chisel bits-- not really sure how to automate that and given the TPS drop I saw I doubt I'd follow up on this for now

### Steps to reproduce

make chisel
scroll or use radial menu to adjust mode to Grid Snapped Cube (Full)
watch the fps tank and tps bottom out while the chisel is being held in the mainhand

### Expected behaviour

normal framerate

### Screenshots

![2022-04-07_00 01 40](https://user-images.githubusercontent.com/1612570/162121710-0a63761e-592f-4b9a-91e1-8e6f2028bdf1.png)
![2022-04-07_00 02 52](https://user-images.githubusercontent.com/1612570/162121711-c86d17a1-53f2-41de-9412-5f93b24b7449.png)

### Additional information

The mod, Magnesium-1.5.jar is installed

**Comment by aaronhowser1** [comment]
Can confirm from testing, and other people have it too

ChiselsAndBits/Chisels-and-Bits/issues/886

**Comment by OrionDevelopment** [comment]
Please join the C&B discord, I have gone to extreme lengths to prevent this, but I can not reproduce this anymore in the latest versions.

**Comment by egorananyev** [comment]
I'm having this issue on Enigmatica 6... Removing optifine did not help.

This is so unfortunate, since I love this mod!
