### ISSUE TITLE
[Bug]: Cannot Right-Click on 

### ISSUE THREAD

**Issue by duncanwebb** [FTBTeam/FTB-Modpack-Issues#716]
### Modpack

FTB OceanBlock

### Modpack version

1.0.9

### Describe the bug

With two Simply Backpacks' Epic Backpack, right-clicking a tempered jar fails to open the processing window. Placing one of the backpacks in a chest, then the right-click works.

### Steps to reproduce

https://user-images.githubusercontent.com/4198031/162230406-0f17cce6-dfb2-49e2-936e-b7f005787586.mp4

### Expected behaviour

Should open the processing GUI

### Screenshots

![image](https://user-images.githubusercontent.com/4198031/162229759-589d7d66-e1f1-4198-96cf-8ae2add9cd1b.png)
![image](https://user-images.githubusercontent.com/4198031/162229878-69d54176-e20c-4864-bbb1-dd63141a101b.png)

### Additional information

Reporting this as it may help other players.

**Comment by Raidobw2** [comment]
Hi, thanks for the report, this has also been reported at #278 and to the mod devs on FTBTeam/FTB-Mods-Issues#117. I will be closing this as a result, since our mod devs will have to fix this and update the mod.
