### ISSUE TITLE
[Bug]: Server Crash from Ars Nouveau Projectile Spells

### ISSUE THREAD

**Issue by brooksbutler** [FTBTeam/FTB-Modpack-Issues#717]
### Modpack

FTB University 1.16

### Modpack version

1.5.0

### Log Files

[crash-2022-04-07_21.13.20-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8447761/crash-2022-04-07_21.13.20-server.txt)

### Describe the bug

I am running a dedicated FTB University 1.16 server on my machine and recently it keeps consistently crashing due to server ticks taking too long.

Looking at the crash report, it seems to hint at the Ars Nouveau projectile spell as the cause for the crashes. However, even after taking down any and all Ars Nouveau blocks present in the world (spell turrets, source relays, etc.) the server keeps running behind and eventually crashing and still includes the Ars Nouveau projectile spell function as the potential cause.

I've tried increasing the server memory as well as trying to locate the chunk causing the server to lag but with no success. Any help or suggestions would be much appreciated. Thanks!

### Steps to reproduce

.

### Expected behaviour

The server should not be lagging from Ars Nouveau if no Ars Nouveau blocks are present.

**Comment by Raidobw2** [comment]
Try restoring a backup from the `backups` folder and see if that works (extract to obtain a world). I'm not sure what to think of the crash log as watchdog crashes sometimes spit out random stackstraces. Do you remember what happened before it crashed?
