### ISSUE TITLE
[Bug]: FTB anniversary refuses to work

### ISSUE THREAD

**Issue by HumanLastName** [FTBTeam/FTB-Modpack-Issues#718]
### Modpack

Ftb university 

### Modpack version

1.5.0 AKA latest version

### Log Files

https://paste.ee/p/LBZjW

### Describe the bug

never gotten passed the load screen yet, tried it with java 17 and 8 still no luck

### Steps to reproduce

just download it from multi mc and launch it and voila it doesn't work (atleast for me)

all other modpacks work

### Expected behaviour

any way to solve it ?

**Comment by Raidobw2** [comment]
Consider using the FTB App to support us -- the correct Java version is used for modpacks and you'll get modpack updates.

You have to use a specific version of Java 8:

> Some modpacks require older versions of Java 8 or 11. Open https://adoptium.net/temurin/archive/ in your browser and select either OpenJDK 8 or OpenJDK 11. You can install those exact versions from the archive:
> MC 1.16.5 or less => jdk8u312-b07 from 21st of October 2021.
> MC 1.16.5 for performance => jdk-11.0.13+8 from 21st of October 2021.

Please close the issue if it was fixed with that info, thanks
