### ISSUE TITLE
[Bug]: Players get teleported a short distance when they enter render distance

### ISSUE THREAD

**Issue by Pizza4Ever** [FTBTeam/FTB-Modpack-Issues#72]
### Modpack

FTB Endeavour

### Modpack version

1.5.0

### Log Files

Regular and debug logs show no mention of anything

### Describe the bug

Moving in render distance (10 chunks) of another player causes both players to be teleported to their floored x/y/z coordinates.

https://drive.google.com/file/d/1j6x9Dh8jqaMgq2YnE8Z-59VC9FW4_Xg8/view?usp=sharing 

### Steps to reproduce

1. Move away from other player
2. Move back to other player
3. Get teleported to floored x/y/z values

### Expected behaviour

Not being teleported

### Screenshots

https://drive.google.com/file/d/1j6x9Dh8jqaMgq2YnE8Z-59VC9FW4_Xg8/view?usp=sharing

### Additional information

It does not appear to be lag related, as the issue is replicated 100% of the time (on my pc), without noticable spikes in cpu usage. (The fact that this is not a rollback, but a flooring of the x/y/z enforces this)

**Comment by Raidobw2** [comment]
Pizza4Ever found that the issue is with the mod "Shrink":

`https://github.com/gigabit101/Shrink/blob/master/src/main/java/net/gigabit101/shrink/events/PlayerEvents.java`

> The issue is caused by the shrink mod, I guess somewhere here
```
public static void handle(PacketShrink message, Supplier<Context> ctx) {
            ((Context)ctx.get()).enqueueWork(() -> {
                ClientWorld world = Minecraft.func_71410_x().field_71441_e;
                if (world != null) {
                    Entity entity = world.func_73045_a(message.entityID);
                    if (entity instanceof LivingEntity) {
                        entity.getCapability(ShrinkAPI.SHRINK_CAPABILITY).ifPresent((iShrinkProvider) -> {
                            iShrinkProvider.deserializeNBT(message.nbt);
                            entity.func_213323_x_();
                            entity.func_70107_b((double)entity.func_233580_cy_().func_177958_n(), (double)entity.func_233580_cy_().func_177956_o(), (double)entity.func_233580_cy_().func_177952_p());
                            if (!(entity instanceof PlayerEntity)) {
                                if (iShrinkProvider.isShrunk()) {
                                    entity.field_213325_aI = new EntitySize(iShrinkProvider.scale(), iShrinkProvider.scale() * 2.0F, true);
                                    entity.field_213326_aJ = iShrinkProvider.defaultEyeHeight() * iShrinkProvider.scale();
                                } else {
                                    entity.field_213325_aI = iShrinkProvider.defaultEntitySize();
                                    entity.field_213326_aJ = iShrinkProvider.defaultEyeHeight();
                                }
                            }

                        });
                    }
                }

            });
            ((Context)ctx.get()).setPacketHandled(true);
        }
```

> that uses func_70107_b to set xyz is the culprit

**Comment by Raidobw2** [comment]
gigabit101/Shrink#52

Thank you Pizza4Ever
