### ISSUE TITLE
[Bug]: FTB Oceanblock fails to load, stalls at "Mod Setup: Final completion" on OS X 12.3.1 (3.3 GHz Dual-Core Intel Core i7)

### ISSUE THREAD

**Issue by tuo2** [FTBTeam/FTB-Modpack-Issues#721]
### Modpack

FTB Oceanblock

### Modpack version

1.12.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8462064/latest.log)

### Describe the bug

FTB Oceanblock fails to load, stalls at "Mod Setup: Final completion" on OS X 12.3.1 (3.3 GHz Dual-Core Intel Core i7)
 

### Steps to reproduce

1. Launch FTB-App
2. Launch Oceanblock
3. Wait for load
4. Stalls on "Mod Setup: Final Completion"

### Expected behaviour

Modpack progresses to Start Screen

### Screenshots

![Screen Shot 2022-04-11 at 4 15 52 pm](https://user-images.githubusercontent.com/28597109/162690551-a9c5ec6f-6089-4b0a-b971-7efae73087b9.png)

### Additional information

Using FTB-App default downloaded JRE 8u312-b07.

Happy to help with further debugging, I'm reasonably proficient so hopefully I can help. :)

**Comment by tuo2** [comment]
Note, on the advice of @dazzleman on the FTB Discord, I tried closing the FTB App after the java window had appeared, and that allowed the loading to complete. I'll leave the issue open, just in case there is debugging information that would be useful to you. Let me know if you want me to close it.

**Comment by Raidobw2** [comment]
You can leave it open, I'll give you feedback here once this is fixed. I've poked the devs about it again and added some of the info you discussed on the Discord earlier to help them.
Note to other devs reading this: Please leave this issue opened so I can link back and give feedback to the user.
