### ISSUE TITLE
[Bug]: Typo in the Chemical Dissolution Chamber quest

### ISSUE THREAD

**Issue by GriSphera** [FTBTeam/FTB-Modpack-Issues#722]
### Modpack

FTB University 1.16

### Modpack version

1.5.0

### Describe the bug

The Chemical Dissolution Chamber quest has a typo, referring to the Ore Slurry as Ore lurry. That's it.

### Steps to reproduce

1. Join a world
2. Open the quests tab, specificaclly the Mekanism ones
3. Look for the Chemical Dissolution Chamber quest

### Expected behaviour

For it to say Ore Slurry

### Screenshots

![2022-04-12_11 57 59](https://user-images.githubusercontent.com/88846902/163032692-e75e65f1-8fda-44e6-aefa-f56b5c53addd.png)

**Comment by aaronhowser1** [comment]
Fixed
