### ISSUE TITLE
[Bug]: Server Crash Help

### ISSUE THREAD

**Issue by Anzulo1984** [FTBTeam/FTB-Modpack-Issues#723]
### Modpack

FTB Oceanblock

### Modpack version

1.12

### Log Files

https://pastebin.com/raw/fXBjUUYw

https://pastebin.com/raw/pge7qkRj

### Describe the bug

Server crashes from time to time either during login, or just right after login

### Steps to reproduce

Its just random and can't be safely reproduce

### Expected behaviour

not crashing

**Comment by Raidobw2** [comment]
Hello, do you happen to have Cursed/Blursed earth or similar that is underwater? Or are some of your animals underwater or in water as well?

**Comment by Anzulo1984** [comment]
I have blessed earth which is on sea level, earlyer it happened that some animals jumped over the wall and landed in the water, but currently there are no animals inside the water not other mobs beside drowned

**Comment by Raidobw2** [comment]
Can you keep the animals out of water at all cost and let me know if the crashes happen or not. I think it might be related to a mod taking in effect when animals fall into water, Better Diving

**Comment by TheonlyTazz** [comment]
Issue has gone stale, if this issue is still relevant, feel free to reopen (or create a new issue)
