### ISSUE TITLE
[Bug]: FTB revelation thermal dynamics crash

### ISSUE THREAD

**Issue by deuwe** [FTBTeam/FTB-Modpack-Issues#724]
### Modpack

FTB Revelation

### Modpack version

3.4.0

### Log Files

https://pastebin.com/EtK4zpwk

### Describe the bug

Seems like a error with thermal dynamics and transferring items through itemducts with servo's. Once the error happens the server stop instantly, seems like it's a error with the slots?

### Steps to reproduce

Honestly I have no clue. I just made a mobfarm which gets the items and transfers it through servo's/itemducts.

### Expected behaviour

The items being succesfully transfered without the server crashing

### Screenshots

![error](https://user-images.githubusercontent.com/44008284/163490553-45159d28-135d-4f48-9ee5-79207bcd8b4a.png)

**Comment by Raidobw2** [comment]
Start with updating to 3.5.0 -- this might take care of the issue itself.

The error seems to come from `com.buuz135.industrial.tile.misc.BlackHoleControllerTileReworked` (Black Hole Controller) in its insertItem method. If updating to 3.5.0 doesn't fix it, then we'll need to fix this later on. You could use a Drawer Controller as a replacement, and have upgraded Drawers and some trash can block to manipulate your flow of items from the farm.

If the server keeps crashing, restore the world from a backup from the `backups` folder.

**Comment by deuwe** [comment]
Just to let you know I've just updated to 3.5.0, sadly this did not solve the issue. Guess I will have to replace my setup for the time being.

Thanks for the help! :)

**Comment by TheonlyTazz** [comment]
Could not replicate this on the latest Version.
