### ISSUE TITLE
[Bug]: Cannot launch modpack with Java 17

### ISSUE THREAD

**Issue by toby696969** [FTBTeam/FTB-Modpack-Issues#725]
### Modpack

ftb direwolf 1.16

### Modpack version

1.16.5

### Log Files

https://paste.ee/p/Wt85d

### Describe the bug

cant launch game 

### Steps to reproduce

open game crash on loading 

### Expected behaviour

not launching

**Comment by Raidobw2** [comment]
Hi, it's a Java issue, see #677 for a fix.

Consider using the FTB App if you want to support us and like our content. We handle the Java versions on the FTB App so you don't have to and you'll also get modpacks updates! https://feed-the-beast.com/app

Please close the issue if this is solved and have a good day
