### ISSUE TITLE
[Bug]: Cyclic energy cable does not power AE2 Energy Acceptor

### ISSUE THREAD

**Issue by lobo235** [FTBTeam/FTB-Modpack-Issues#728]
### Modpack

FTB Endeavour

### Modpack version

1.9.0

### Describe the bug

The Energy Cable from the Cyclic mod will not power the Energy Acceptor from the Applied Energistics mod. I had to connect a Stirling Dynamo from the Thermal Series mod directly to the Energy Acceptor without any Cyclic mod Energy Cable in between.

### Steps to reproduce

1. Place a Stirling Dynamo and put a fuel source into it
2. Place an Energy Cable from the Cyclic mod at the end of the stirling dynamo
3. Then, place an Energy Acceptor from Applied Energistics connected to the Energy Cable
5. Observe that no power flows to the Energy Acceptor and if you try to power any Applied Energistics blocks using the Energy Acceptor in this configuration they receive no power.

### Expected behaviour

Power should flow from the Energy Cable to the Energy Acceptor

**Comment by Raidobw2** [comment]
I see! Thanks for the report. I'll look into it and link back an issue from Cyclic to here.

Alternatives to transfer energy for now can be energy pipes from the Refined Pipes mod, or universal cables from Mekanism

**Comment by manmaed** [comment]
This issue is stale
