### ISSUE TITLE
[Suggestion]: Thaumcraft quest inconsistency

### ISSUE THREAD

**Issue by zoller27osu** [FTBTeam/FTB-Modpack-Issues#729]
### Modpack

FTB Presents Stoneblock 2

### Is your suggestion related to a problem? Please describe.

1.22.0
The Sword of the Zephyr quest requires the enchantment the Sword comes with (Arcing II) whereas the other "of the" tools do not - meaning they can be easily printed from a Transmutation Tablet with the Tome of Knowledge, while the Sword cannot.

Consistency would be nice, but it's up to y'all whether you want to check for the genuine articles or not.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
