### ISSUE TITLE
[Bug]: The Enhanced Vat JEI uses does not include Vat processing recipes

### ISSUE THREAD

**Issue by zoller27osu** [FTBTeam/FTB-Modpack-Issues#731]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.22.0

### Describe the bug

"The Enhanced Vat" apparently does not belong to the same category as "The Vat" in JEI, processing recipe-wise. The recipes still work, they just don't appear in JEI.

### Steps to reproduce

1. Press U on The Enhanced Vat or right-click its icon in JEI

### Expected behaviour

The Vat recipes should appear among the results

### Screenshots
the processing category in question (note the lack of the icon for The Enhanced Vat in the upper left)
![2022-04-22_18 45 33](https://user-images.githubusercontent.com/12834978/164861800-0a392dd1-2a78-4cce-b320-cfbb6c4023bc.png)
vs the "Uses" for The Enhanced Vat (the processing category is missing from the results along the top)
![2022-04-22_18 45 40](https://user-images.githubusercontent.com/12834978/164861804-6ae4d774-a5eb-41ab-9d94-8ec2a8c02888.png)

**Comment by Raidobw2** [comment]
Hmm I'm not sure I can fix that in the future, but I'll look into it at some point and see. Thanks for the report
