### ISSUE TITLE
[Suggestion]: Make Runic Matrix automatable

### ISSUE THREAD

**Issue by zoller27osu** [FTBTeam/FTB-Modpack-Issues#732]
### Modpack

FTB Presents Stoneblock 2

### Is your suggestion related to a problem? Please describe.

The Runic Matrix for Thaumcraft Infusion must be activated by being right-clicked with a Caster's Gauntlet by a "player" who knows  (i.e. has the research for) the recipe being attempted. Sadly, not even your own Golems holding a Caster's Gauntlet can do it - the right-click achieves nothing for them (at least, on multiplayer - possibly related is the "Only your golems can do this task" toggle preventing the Golem from using the item, even though you placed the Golem?). A Mechanical User (with a Caster's Gauntlet) could do it if there was any way to share your Thaumcraft knowledge with it (like a Tome of Knowledge Sharing from Thaumic Tinkers).

**Comment by zoller27osu** [comment]
I think https://github.com/FTBTeam/FTB-Modpack-Issues/issues/734 would fix this with the Arcane Assembler?

**Comment by Raidobw2** [comment]
I don't think that's possible from what I know of. We could implement modular machinery for it, but what is the exact use of automating the Runic Matrix? I'm not aware of direct benefits, since normally magic mods like Thaumcraft or for example Astral Sorcery are not meant to be automated in the same way Botania is. What are your thoughts and the uses of automating the Runic Matrix?

**Comment by zoller27osu** [comment]
Mostly I just hate having to find my gauntlet every time I start an Infusion and would love to be able to do so with the press of an (in-game) button, but most other parts of the process (other than having the right essentia counts) are easily automated by AE2 for example.

This would also be easy with any equivalent to ProjectEX's "Knowledge Sharing Book" or making the quest reward for the Crimson Rites an item that runs a command (and is not consumed, or has an EMC value for re-creation) instead of the command itself, as placing such an item along with the Gauntlet into a Mechanical User should work out-of-the-box due to the Mechanical User's fake player.

**Comment by Raidobw2** [comment]
Thanks for the feedback. Once I get to it, I'll see if I can make some of the recipes automatable, possibly if a config or command would allow it for fake players. I can't guarantee I'll be able to, but I'll try.
