### ISSUE TITLE
[Bug]: Ender IO Endergy Exchanger Core Tier 2 cannot be crafted

### ISSUE THREAD

**Issue by zoller27osu** [FTBTeam/FTB-Modpack-Issues#733]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.22.0

### Describe the bug

The Ender IO Endergy Exchanger Core Tier 2 can only currently be crafted from enderio:block_holy_fog (Glowstone Nano-Particles (Old)), which has been deprecated (and as such, is no longer obtainable) in favor of enderio:block_holier_fog (Glowstone Nano-Particles). Optimally the recipe would support both, as most recipes using such deprecated items do.
(also, the description on the newer version of the Glowstone Nano-Particles item should probably mention that it prevents spawning in the affected areas)

### Steps to reproduce

1. Check uses for the newer Glowstone Nano-Particles in JEI

### Expected behaviour

The Ender IO Endergy Exchanger Core Tier 2 should show up

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
