### ISSUE TITLE
[Suggestion]: Add Thaumic Energistics

### ISSUE THREAD

**Issue by zoller27osu** [FTBTeam/FTB-Modpack-Issues#734]
### Modpack

FTB Presents Stoneblock 2

### Is your suggestion related to a problem? Please describe.

Use Thaumic Energistics instead of ThaumicTerminal?

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/thaumic-energistics

**Comment by Raidobw2** [comment]
I think that Thaumic Terminal was made by one of the old modpack creators probably for StoneBlock or another idea. After a while, unless the mod is gamebreaking, we no longer change mods. I unfortunately cannot accept this request to change the mod, but thanks for suggesting it. We will think of it for the future, if Thaumcraft 1.18+ is to come out some day and has similar addons.
