### ISSUE TITLE
[Suggestion]: Weird interaction between Dank and Inventory Sorter

### ISSUE THREAD

**Issue by Akiminos** [FTBTeam/FTB-Modpack-Issues#74]
### Modpack

FTB University 1.16

### Is your suggestion related to a problem? Please describe.

  When in a Dank inventory while in bag mode (from Dank Storage mod), using the auto-sort button from Inventory Sorter in the inventory will "Unstack" the content of the Dank and erase the content stored in it in the process.

  To reproduce, take any dank and fill on item with enough stack so that it would fill a whole chest for example normally, then sort using Inventory Sorting.
  
I don't know where else to address this, to me it's not really a bug, but it definitely breaks the 
Dank mechanic, way too easily. Maybe there is a way to prevent auto-sorting inside a dank ?

**Comment by aaronhowser1** [comment]
Moved to Inventory Tweaks Renewed. Inventory Sorter crashed when I tried to add GUIs to the blacklist, ITR works.
