### ISSUE TITLE
Warmup on FTB Essentials commands like /home

### ISSUE THREAD

**Issue by SmallSansSerif** [FTBTeam/FTB-Modpack-Issues#740]
### Modpack

FTB Chocolate

### Is your suggestion related to a problem? Please describe.

People use this command to get out of danger or harms way by teleporting instantly.

**Comment by MichaelHillcox** [comment]
This would be a mod request not a pack request and please supply more information on what you want here... any teleport command can be abused... you can already add a timeout on the command if I recall correctly

**Comment by SmallSansSerif** [comment]
Sorry, was looking for a warmup timer, which is different than the cooldown, before the command teleports the user. So if a user types /home it will warmup for 3s or similar. Typically if player takes damage it would cancel this type of warmup timer. FTB has had this functionality in some previous packs via an FTB mod.

**Comment by manmaed** [comment]
This  issue is now Stale
