### ISSUE TITLE
[Bug]: The Simple Discord Rich Presence Mod File ends in .jard

### ISSUE THREAD

**Issue by FridoWe** [FTBTeam/FTB-Modpack-Issues#741]
### Modpack

FTB University 1.16

### Modpack version

1.5.0

### Describe the bug

The Simple Discord Rich Presence Mod File ends in .jard

### Steps to reproduce

Just open the mods file

### Expected behaviour

the Modpack wont start

**Comment by aaronhowser1** [comment]
I forgot to un-disable it 🤦‍♂️
