### ISSUE TITLE
[Bug]: Sorting buttons all out of wack while in crafting station for tinkers

### ISSUE THREAD

**Issue by select1v** [FTBTeam/FTB-Modpack-Issues#742]
### Modpack

FTB University 1.16

### Modpack version

1.5.0

### Describe the bug

![image](https://user-images.githubusercontent.com/98625802/165864787-2877139e-416b-48ca-9365-730ecf947d8f.png)
I think this image sums up the bug pretty well, this isnt as much of an issue when the crafting station is not connected to an inventory, as seen here
![image](https://user-images.githubusercontent.com/98625802/165864875-83333073-9167-4699-95a0-183bea43914d.png)

### Steps to reproduce

1. grab a Tinkers Construct Crafting Station
2. Attach any inventory to the crafting station
3. Watch the crafting table bug out

### Expected behaviour

The crafting table should not be obstructed by crafting tweaks

**Comment by aaronhowser1** [comment]
reo-ar/InvTweaksRenewed/issues/63

The mod hasn't been updated in a couple years, but 1.16 is very much lacking in inventory sorting mods and this was the best I could find
