### ISSUE TITLE
[Bug]: Website: Version Tags missing for Oceanblock?

### ISSUE THREAD

**Issue by Ludi87** [FTBTeam/FTB-Modpack-Issues#743]
### Modpack

FTB Oceanblock

### Modpack version

-

### Log Files

![image](https://user-images.githubusercontent.com/13112051/165907214-79a28525-6b37-4723-a8c8-5f99a2237983.png)

### Describe the bug

If you select 1.16 or 1.16.5 versions on the website, Oceanblock isn't in the list of Modpacks.

### Steps to reproduce

- Select Version 1.16 or 1.16.5
- Pack missing from list

### Expected behaviour

Pack in list

**Comment by Sunekaer** [comment]
Fixed, give the cache a bit to clear and it will show
