### ISSUE TITLE
[Bug]: Immersive Engineering Quests not completing when Multiblock Machine finished.

### ISSUE THREAD

**Issue by Furious1964** [FTBTeam/FTB-Modpack-Issues#745]
### Modpack

FTB Oceanblock

### Modpack version

1.12.0

### Log Files

https://pastebin.com/2NnPFvdr

### Describe the bug

Built the Metal Press, Silo and the Advanced Engineers Workbench, looked at them and Quest does not complete. Have all the requirements to complete them.

### Steps to reproduce

1. Made required blocks
2. Assembled the machines.
3. Looked at said machines...
4. Nothing..

### Expected behaviour

Expected it to work.

### Screenshots

https://imgur.com/u1HzN5K
https://imgur.com/5opHWBf
https://imgur.com/ZYsUDnI
https://imgur.com/T2z0Knw

### Additional information

Seems only to be the Quests that are for Immersive Engineering.

Tried with a fresh install of the modpack and same thing.

**Comment by Raidobw2** [comment]
Hello, try looking closely (1 block apart) at each of the 7 "blocks" in the Metal Press. That takes a few seconds at most, don't try and look for too long if nothing happens! If that is the case, it's indeed broken and we'll have to fix it.

You can press Escape and select Open to LAN. Enable cheats, and in chat you'll be able to type `/ftbquests editing_mode`. Open your questbook and right click the malfunctioning quests, choose "Complete instantly". Writing `/ftbquests editing_mode` again will turn off editing mode and return you to a normal questbook, so you can resume proper gameplay.

**Comment by Furious1964** [comment]
Nope, totally buggered, Mate. Stared at each block for 5 to 10 seconds and nothing. Definitely a bug somewhere.

**Comment by TheonlyTazz** [comment]
Fixed in next update, Quests had empty "Observe", not being able to be finished
