### ISSUE TITLE
[Bug]: No use for creosote oil (Thermal series)

### ISSUE THREAD

**Issue by dsm2k1** [FTBTeam/FTB-Modpack-Issues#748]
### Modpack

Academy

### Modpack version

1.16

### Describe the bug

JEI is showing no use for creosote oil for both verisons of the item only recipe that comes up is obtatining it and putting it into a bucket using the fluid encapsulator.

### Steps to reproduce

Just opening up uses for it on JEI

### Expected behaviour

The wiki says it should be able to use it as some fluid fuel at least.

### Screenshots

![image](https://user-images.githubusercontent.com/61108526/166307326-bff8bc26-5c4d-48f1-a373-f19fcce1c62a.png)

**Comment by pson** [comment]
The issue I came here for feels like a part of this issue, I tried to auto-craft a _Creosote Oil Bucket_ and I had over nine buckets of _Creosote oil_ (IE). It took me quite a while to figure out that what I wanted to craft was a _Bucket of creosote oil_. Maybe the two types of creosote oil should be equivalent?
