### ISSUE TITLE
[Bug]: Graphical glitches as player looks around

### ISSUE THREAD

**Issue by RaycePenguin1** [FTBTeam/FTB-Modpack-Issues#749]
### Modpack

All of them

### Modpack version

1.7.10,1.5.2

### Describe the bug

I am having a weird issue on all old versions of minecraft where the textures flash and break, its kinda hard to discribe but i have some screenshots

### Steps to reproduce

i dont know it happens whenever i open any modpack on an old version of minecraft

### Expected behaviour

the textures around you break and flash

### Screenshots

![Screenshot 2022-05-03 105530](https://user-images.githubusercontent.com/104859502/166516366-a53ad5e1-6edd-493b-9a75-a286ad9462a0.png)
![Screenshot 2022-05-03 105214](https://user-images.githubusercontent.com/104859502/166516390-dd05b1c5-d92b-42df-ace6-8839524ba7c1.png)
![Screenshot 2022-05-03 105353](https://user-images.githubusercontent.com/104859502/166516412-9648b993-51a3-41ee-aa19-04007a114f53.png)
![Screenshot 2022-05-03 105431](https://user-images.githubusercontent.com/104859502/166516435-ca3c1b94-1b29-4825-91f0-cd0d967cd1f6.png)
![Screenshot 2022-05-03 105450](https://user-images.githubusercontent.com/104859502/166516446-19b9cc64-ab3d-4dd5-8847-78d6cdc44486.png)
![Screenshot 2022-05-03 105506](https://user-images.githubusercontent.com/104859502/166516454-98aa9932-aa43-4bc8-a472-b55c2433debf.png)

### Additional information

also items on the ground are invisible

**Comment by Raidobw2** [comment]
If using Optifine, don't use it.

Then I recommend updating your graphics drivers directly from the manufacturer's site, or through AMD software or Nvidia GeForce Experience.

Try putting it fullscreen with F11 as well.

Saying which modpack this happens on is important. We support FTB modpacks, and I'll try to find solutions if that's one of ours. If it's not a FTB modpack, then this issue is on the wrong tracker, but try some of the tips above

**Comment by RaycePenguin1** [comment]
these screenshots were taken on ftb infinity evolved but the problem persists on ftb unleashed, (with 1 added mod) i did not add anything to infinity evolved and had no optifine on either

**Comment by RaycePenguin1** [comment]
what website would i go to to get official drivers for Intel iRISx integrated graphics

**Comment by RaycePenguin1** [comment]
sorry about the confusion im new to github lol

**Comment by RaycePenguin1** [comment]
I Updated my graphics drivers again and it seems to have fixed

**Comment by RaycePenguin1** [comment]
For future people: you can fix it by seriously downgrading your drivers OR by updating it to the newest version cause they just fixed it! hope this helps :D

**Comment by RaycePenguin1** [comment]
also it only happens on intel integrated graphics so make sure your gpu is being utilised if you have one. it is fixed on modern windows ten drivers if u have 11 its not fixed yet

**Comment by RaycePenguin1** [comment]
and this is the same bug that causes the whole screen to be one color when you look around so same steps will fix if you have that problem

**Comment by Thebigdravens** [comment]
i am currently experiencing these issues
