### ISSUE TITLE
[Bug]: Missing Botany Pot Seed Recipies

### ISSUE THREAD

**Issue by hammackj** [FTBTeam/FTB-Modpack-Issues#75]
### Modpack

FTB Oceanblock

### Modpack version

1.1.0

### Describe the bug

Unable to plant the following seeds in the Botany Pot.

- Apatite Seeds
- Pig Iron Seeds
- Manyullyn Seeds
- Rose Gold Seeds
- Slimesteel Seeds
- Tinker's Bronze Seeds

### Steps to reproduce

1. Create a Hopper Botany Pot,
2. Put Insanium Farmland in pot
3. Try to plant see

### Expected behaviour

I expect all seeds to be able to be planted in the hopper pot.

**Comment by Sunekaer** [comment]
This is fixed in 1.2.0 which was released some days ago now

**Comment by hammackj** [comment]
I updated to 1.2 and the issue still exists.
