### ISSUE TITLE
[Bug]: Yung's Bridges do not function properly in Twilight Forest

### ISSUE THREAD

**Issue by NytSong** [FTBTeam/FTB-Modpack-Issues#750]
### Modpack

FTB Utlimate: Anniversary Edition

### Modpack version

1.3.0

### Describe the bug

Yung's bridges uses the overworld "sea level" for the base Y coordinates.  
Twilight forest sits at a base Y of 32 (ish?).
This makes bridges added there all sorts of borkity borked (yes, that's a technical term).
Essentially the pillars the bridges stand on are super tall put the bridge up high where it does no good.  
Bridge generation should really be turned off for anything twilight forest related if possible.

### Steps to reproduce

Nothing really to do other than generate a world with twilight forest and have bridges generate there.

### Expected behaviour

should see normal bridges 

### Screenshots

![stilt-bridge](https://user-images.githubusercontent.com/61587778/166735666-e2e942e6-6a8f-447b-864d-f44ef10ebd93.png)

### Additional information

The mod dev did end up marking the reported issue as a bug about a day ago. It'll likely be a bit before seeing a fix from that side and even then, it would require this modpack be loaded with the fixed version, naturally.
https://github.com/YUNG-GANG/YUNGs-Bridges/issues/8

**Comment by Raidobw2** [comment]
I see, the mod author could add a config for other dimensions which then we can configure. I haven't checked yet if the current config can do that, but I guess we'll see with the error being reported to the mod author's repo. Thanks for the report
