### ISSUE TITLE
[Suggestion]: Forge 1.18 launching issues: add ServerStarter mod?

### ISSUE THREAD

**Issue by demethan** [FTBTeam/FTB-Modpack-Issues#751]
### Modpack

FTB  1.18 packs

### Is your suggestion related to a problem? Please describe.

Hi,

At Breakfastcraft.com we are a small community of adults that plays modded Minecraft. The admin team is mostly IT professionals but we are not java developers. We use an internal wrapper to manage our MC servers. It is similar to MarkII with some discord bots. The purpose of this post is to ask if you would possibly add a server launcher to your 1.18 packs. The way our wrapper is designed, it needs a jar in the root of the pack to start and cannot run the .sh included with the 1.18 packs. The Enigmatica team uses [this](https://github.com/BloodyMods/ServerStarter) in their pack and it makes it easier to adapt to the 1.18 change. Actually, I'm mad at Forge for changing, but I haven't seen any other post against it, so I didn't complain to them. There is probably a good reason for the change.

We wanted to feature FTB Chocolate but cannot launch it with our infrastructure. I am trying to muddle my way into adding that server launcher but I am no java dev.

Thank you for considering this.

Luc Levesque (Breakfastcraft team)

### Mod suggestion

ServerStarter mod for Forge 1.18 packs.

**Comment by Raidobw2** [comment]
I'll ask the team and link them this issue as reference, thanks for the suggestion

**Comment by manmaed** [comment]
This  issue is now Stale
