### ISSUE TITLE
[Bug]: mine together

### ISSUE THREAD

**Issue by boyersh** [FTBTeam/FTB-Modpack-Issues#752]
### Modpack

FTB Academy 1.16

### Modpack version

1.3.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8636851/latest.log)

### Describe the bug

Mine together encountered  an error during the sided_setup event phase 
java.lang.nullpointerexception: null

### Steps to reproduce

1.just open the pack and wait until freezing data then the error comes out

### Expected behaviour

I just wanted the modpack to enter the main menu when loading finished

**Comment by Raidobw2** [comment]
Hello, remove Optifine and try again, sometimes it causes issues.

Also, you should try with the FTB App since we've noticed sometimes that other launchers have issues with our packs: https://feed-the-beast.com/app

Please let me know if removing Optifine or using the FTB App fixed it

**Comment by boyersh** [comment]
> Hello, remove Optifine and try again, sometimes it causes issues.
> 
> Also, you should try with the FTB App since we've noticed sometimes that other launchers have issues with our packs: https://feed-the-beast.com/app
> 
> Please let me know if removing Optifine or using the FTB App fixed it

ftb app fixed it thx for help

**Comment by Raidobw2** [comment]
You're welcomed, enjoy the modpack 🙂
