### ISSUE TITLE
[Bug]: FTB Stoneblock 2 crashes if you search for "@Microblock" in JEI

### ISSUE THREAD

**Issue by Tiranajunge** [FTBTeam/FTB-Modpack-Issues#753]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.22.0

### Log Files

https://pastebin.com/hNiu4vce

### Describe the bug

Minecraft crashes when I open the Inventory. Apparently I have searched something with a rendering issue.

### Steps to reproduce

1. Join a Server
2. Open the Inventory and search for "@Microblock"

### Expected behaviour

That searching "@Microblock" doesn't crash the game

### Screenshots

![image](https://user-images.githubusercontent.com/65712579/167117065-5c393a86-ec02-4349-89ca-46285c482df5.png)
Before I press "E"
![image](https://user-images.githubusercontent.com/65712579/167117125-12f48017-51cb-4cef-910e-ff276da23939.png)
As soon as I try to open my inventory

### Additional information

User added Mods:
Optifine (disabled and the error still occurs)
FullscreenWindowed

**Comment by Raidobw2** [comment]
Hi, Optifine is still in the stacktrace of that log: `net.optifine.reflect.Reflector.callVoid`. Could you remove Optifine from the mods folder fully and see if it crashes again? You can post another log here, I'll have a look. If you can reproduce it after removing the mod fully, I'll add this to our todo list. This might take some time however, so it is possible that if the issue persists that you will be unable to use covers for your playthrough. Thanks in advance

**Comment by Tiranajunge** [comment]
@Raidobw2 
Ok removing Optifine completely fixed the crashes. 
Thanks for the help
I tough disabling Optifine would be enough but I was wrong.

![image](https://user-images.githubusercontent.com/65712579/167295869-6239de6a-2ae6-4dab-9e4a-557b3737c542.png)
