### ISSUE TITLE
[Bug]: Multifarm tasks can't be completed if material is not stone bricks

### ISSUE THREAD

**Issue by Ricozero** [FTBTeam/FTB-Modpack-Issues#754]
### Modpack

FTB University 1.12

### Modpack version

1.2.1

### Describe the bug

If you make multifarm components using material that is not stone bricks, the tasks can not be completed.

### Steps to reproduce

Craft any multifarm component not using stone bricks.

### Expected behaviour

Any material should be valid according to the task description.

**Comment by Gaz492** [comment]
Thank you for creating this issue/suggestion, however this modpack is now considered a legacy pack and is therefore no longer receiving any bug fix updates or mod updates.
Any updates to this pack will only be released if there is a security issue.
