### ISSUE TITLE
[Bug]: there is no window to even play the game

### ISSUE THREAD

**Issue by Littletigger11** [FTBTeam/FTB-Modpack-Issues#755]
### Modpack

FTB Chocolate

### Modpack version

1.10

### Describe the bug

Everytime i try to boot up FTB chocolate it never loads correctly, my drivers are up to date and so is my computer, everything is working as intended, but after pressing "PLAY" a small window pops up for a split second before dissapearing and never reappearing, there have been no error reports or crashes to cause this, its just done it since installing, i know the modpack works too because after about a minute or so the music in the menu starts playing, im not sure what bug is causing this.

ive tried allocating more RAM to it, changing the display, uninstalling than reinstalling, restarting my computer and installing any new driver updates and still nothing, and as much as i can see is that nobody else that i can see is having this issue. ive looked all over forums and reddit posts, even the FTB official twitter and nobody has ever mentioned this issue since its happened to me.

i hope someone knows whats wrong and will help me figure out whats wrong.

### Steps to reproduce

im not sure if its just my launcher but what you do is:

1. go into the overwolf launcher
2. find FTB chocolate
3. install it (version doesnt seem to matter)
4. once installed click "PLAY"

### Expected behaviour

what i expected to happen after clicking play was the launcher loading and the game menu popping up so i can start a new world

### Additional information

if there are people that have tried recreating this issue and have failed than i have no idea what else to do but uninstall it and hope it gets fixed in the future

**Comment by Raidobw2** [comment]
Hello, can you try to click play on the FTB App and leave the window as it is, let it load for 5-7 minutes. The program will need enough RAM of course. Let me know if the window pops back up at the end, you may need to wait a bit more after hearing the main menu music

**Comment by Littletigger11** [comment]
> 

so, doing exactly as youve asked, as well as allocating about 12gb's of ram since most modpacks seem to work well with that amount, and waiting an hour with the menu music going still nothing, no window ever popped up.

i appreciate the suggestion but im so confused on why this is happening still TnT

**Comment by Raidobw2** [comment]
Which OS do you have on your computer? I know of some weird bug with Mac is why I'm asking

**Comment by Littletigger11** [comment]
i play it on windows 11, i played stoneblock 2 previously with the same OS and it works perfectly

**Comment by Raidobw2** [comment]
I can try to assist you through here but it might take more time than in the FTB Discord. Tomorrow we're Monday and I'll be checking the Discord.

If you want to keep going, do other modpacks do that as well? What happens if you close the FTB App while it is loading (the modpack will continue loading in the background)? Does the game icon show up in the menu when pressing and holding Alt + Tab?

**Comment by Littletigger11** [comment]
thats alright, i work a lot so i dont usually get a whole lotta time to play minecraft, but, yes other modpacks do work, revelations, infinity evolved, stoneblock 2, and skyfactory 4 work perfectly fine, FTB chocolate is the only one that has acted this way

and to answer the Alt+Tab question, no, it does not work

**Comment by Raidobw2** [comment]
Please try to close the FTB App while the game is loading and let me know if the modpack loads fully and pop up at the end. If that doesn't work, try a clean reinstall of the modpack.

To do a clean reinstall, you'll press Windows + R and paste `%localappdata%\.ftba\instances` in the box, then press Ok. In the view that opens up, delete the folder called `.localCache`. This is the download cache, and unless deleted, each reinstall won't fetch new fresh files for the modpack.

Then reinstall the modpack by deleting it and browsing for it, I assume you are familiar with these steps already.

That's a quite odd issue if it persists. You could try closing as much unused programs in Task Manager and seeing if Minecraft loads correctly after that. Antivirus/Network enhancing programs do count in that list of programs, if you have some.

**Comment by Littletigger11** [comment]
alright so after the first two options that you had suggested and a few thing uninstalled of my computer it seems to be working, i knew the modpack was relatively small so i knew RAM wouldnt be an issue

but this issue being so odd i wasnt sure if anyone knew what to do, it seems to be working anytime i open it now so lets hope it doesnt continue any further

i thank you for your time and for helping me out, have a nice day!

**Comment by Raidobw2** [comment]
No problem! Although we don't really know what solved it, we'll say it's either the reinstall or you clearing up some programs. Thank you, have a good day as well and enjoy playing 🙂

**Comment by Littletigger11** [comment]
so i had a few antivirus apps downloaded on my computer and after uninstalling all of them it worked, seemed that those were the issue
