### ISSUE TITLE
[Bug]: FTB Lite 3 V 1.5.0 crashes on Start-Up

### ISSUE THREAD

**Issue by DaJugoSeiMuata** [FTBTeam/FTB-Modpack-Issues#756]
### Modpack

FTB Lite 3

### Modpack version

1.5.0

### Log Files

[fml-client-latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8645514/fml-client-latest.log)

### Describe the bug

As written in the headline

### Steps to reproduce

I have no clue

### Expected behaviour

To start the Modpack

### Additional information

Java 8 Build 1.8.0_333-b02

**Comment by Raidobw2** [comment]
Hello, try this from the FTB Discord:

> 1. In the FTB App, navigate to the modpack's page and select "Settings". Then navigate down and click "Open Folder". This will open a window. Keep this window open at all times during the process.
> 2. Close the FTB App and the Minecraft launcher if any are open.
> 3. In the window that had opened, open the mods folder and delete `CodeChickenCore-1.7.10-1.0.7.47-universal.jar`.
> 4. In that mods folder, open the other folder `1.7.10`. Inside, you will delete `CodeChickenLib-1.7.10-1.1.3.136-universal.jar`.
> 5. Download the file `CodeChickenCore-1.7.10-1.0.7.48-universal.jar` from https://www.curseforge.com/minecraft/mc-mods/codechickencore/files. It will be in your Downloads.
> 6. Take the file you just downloaded, and move it to the mods folder from earlier. It will be directly inside the mods folder.
> 7. Close the windows you opened, start the FTB App.
> 8. Select FTB Lite 3, hit play, and have fun!

Some old packs are broken, but I have them on my todo list for this summer. For now this workaround should work

**Comment by DaJugoSeiMuata** [comment]
Thanks man it worked

**Comment by Raidobw2** [comment]
Awesome! :) Leave this opened please, that way I can remind myself to fix it this summer and not forget that bug!

**Comment by Gaz492** [comment]
This should be fixed now
