### ISSUE TITLE
[Bug]: Warning of duplicate scripts/mods followed by crash during startup

### ISSUE THREAD

**Issue by kamodius** [FTBTeam/FTB-Modpack-Issues#760]
### Modpack

Direwolf20 1.18

### Modpack version

1.0.0 (Beta)

### Log Files

https://pastebin.com/9QamKbv9

### Describe the bug

Fresh install, no changes from default.  Click Play, get "Potentially invalid instance - Your instance appears to have duplicate mods or invalid scripts.  It is highly recommended that you re-install your instance."

### Steps to reproduce

1. Install DW20 1.18 modpack in FTB launcher
2. Click Play
3. Get warning about potentially invalid instance
    3a. Reinstall, changes nothing, or
4. Click Launch, modpack begins to load until halting with the linked crash. 

### Expected behaviour

Expect to launch normally and arrive at main in-game menu.

### Screenshots

![image](https://user-images.githubusercontent.com/35677803/168312690-22847a2e-a98e-40fe-9ee9-1f45182fc85d.png)

### Additional information

Have tried both default memory options and my typical setting of 12gb (I have 32gb in system)

**Comment by Sunekaer** [comment]
Could you try and restart your pc, then open the app delete the instance and install it again?

**Comment by kamodius** [comment]
> Could you try and restart your pc, then open the app delete the instance and install it again?

No change.  Restarted, removed from app, deleted folder, reinstall.

**Comment by Sunekaer** [comment]
Does other mod packs work for you?

**Comment by Sunekaer** [comment]
Thats a different issue

**Comment by kamodius** [comment]
> Does other mod packs work for you?

I have both Anniversary Edition and OceanBlock installed, both launch just fine.  This is the first time I've seen this error/crash in the FTB app.

**Comment by wendictive** [comment]
k

**Comment by Sunekaer** [comment]
Hm okay lets try this, go to the instance and click settings -> open folder -> then in the folder it opens go one back to instances.
Close the FTB app, delete the .localCache folder and then start the app and reinstall the pack

**Comment by kamodius** [comment]
> Hm okay lets try this, go to the instance and click settings -> open folder -> then in the folder it opens go one back to instances. Close the FTB app, delete the .localCache folder and then start the app and reinstall the pack

Seems to have done it.  No warnings, no crashes.  Thank you for the help.
