### ISSUE TITLE
[Bug]: squeezer loses recipe for string from wool after 1-2 uses

### ISSUE THREAD

**Issue by remotedeck** [FTBTeam/FTB-Modpack-Issues#761]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.0.0

### Describe the bug

after squeezing(integrated dynamics squeezer) wool to get string the recipe goes away and the squeezer wont produce string, the recipie also goes away in the recpie screen. 

### Steps to reproduce

1. put wool in squeezer
2. squeeze the wool by jumping on it
3. get 2-4 string
4. put wool in squeezer again
5. squeeze the wool by jumping on it
6. get 0-2 string
7. put wool in squeezer again 
8. squeeze the wool by jumping on it 
9. get wool back

### Expected behaviour

the recpie for string stays after you use it once

### Screenshots

![index](https://user-images.githubusercontent.com/58578350/168317789-c72f8ca2-d2b1-4077-a951-5883aac05a50.png)

**Comment by remotedeck** [comment]
sorry i dont know how to add flairs im trying to add them

**Comment by Sunekaer** [comment]
https://github.com/CyclopsMC/IntegratedDynamics/issues/1166

**Comment by remotedeck** [comment]
oh ok so should i close the issue then?

**Comment by Sunekaer** [comment]
No leave it until its fixed or we close it.

**Comment by MacChuck** [comment]
This is marked as fixed now in the integrated dynamics mod bug report.
https://github.com/CyclopsMC/IntegratedDynamics/issues/1166
