### ISSUE TITLE
stuck on startup[Bug]: 

### ISSUE THREAD

**Issue by wendictive** [FTBTeam/FTB-Modpack-Issues#762]
### Modpack

FTB direwolf20 1.18

### Modpack version

1.18

### Log Files

cant get a log file .. only thing i can do is kill instance

### Describe the bug

just installed it  and it get stuck on Deepscan of valhelsia_core.....etc
ive tried restart
updating java

it just stays like that for 30 min +

### Steps to reproduce

just start it up

### Expected behaviour

for the pack to load so i could play

### Screenshots

https://ibb.co/Cn8s7wz

**Comment by Sunekaer** [comment]
Please provide the full log.

**Comment by SmogShadowSeth** [comment]
Got the same issue, here are my logs:
[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8689285/console.log)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8689287/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8689289/debug.log)
.

**Comment by wendictive** [comment]
https://pastebin.com/nY8ny3Pi    console.log
https://pastebin.com/M3YP2cpM   debug.log
https://pastebin.com/byX0gRHf     latest.log
these are all i could find ... there are no error log etc

**Comment by Sunekaer** [comment]
Honestly no clue whats causing this but lets try this:
go to the instance and click settings -> open folder -> then in the folder it opens go one back to instances.
Close the FTB app, delete the .localCache folder and then start the app and reinstall the pack

**Comment by SmogShadowSeth** [comment]
Thank you, your fix worked for me; the pack is now launching properly. Do you have an idea of what may have caused this problem?

**Comment by Sunekaer** [comment]
Im guessing a file just broke on download

**Comment by wendictive** [comment]
it did indeed work ty Sune ... maybe keep the post for future fix that people follow?

**Comment by SmogShadowSeth** [comment]
I experimented a bit, and so far, it looks like this problem only occurs when adding the FTB ultimine mod to the pack. No need to delete the .locale rep to fix that, but you must delete and re-install the modpack for it to work again. I tried adding another mod (openblocks elevator), and it ran like a charm. Don't know what's causing Ultimine specifically to cause that.
