### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CinnamonShaey** [FTBTeam/FTB-Modpack-Issues#765]
### Modpack

Direwolf20 1.18.2

### Modpack version

1.0.0

### Log Files

FTB-DBGJUGAFINUVI

### Describe the bug

whenever i launch the pack it stops completely with loading 
![image](https://user-images.githubusercontent.com/80605917/168393464-dd54cb66-2a0e-44d3-abf9-a7aa39a27d56.png)
never gets further than this

### Steps to reproduce

launch the pack

### Expected behaviour

finish loading

### Screenshots

![image](https://user-images.githubusercontent.com/80605917/168393566-6dc98338-d6b2-471e-ae46-1f025dd2d11d.png)
![image](https://user-images.githubusercontent.com/80605917/168393625-99bdceb4-5945-4cfc-90bf-b81c04243d50.png)
![image](https://user-images.githubusercontent.com/80605917/168393647-db43344c-06ba-4e7f-afe1-83beb0658b8a.png)

### Additional information

i did add 2 mods ultimine and borderless window, but even when removing those still gets stuck, and its not cause it does not "support" the mods cause if i take the mods and configs and use a vanilla launcher it launches just fine well "fine" all entities were invisible including my hand, myself, dropped items, and mobs, but it launched, the ftb apps custom launch sequence does not launch the pack properly when you add any extra mods

**Comment by Sunekaer** [comment]
Reinstall the pack and it should work.
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/762

**Comment by CinnamonShaey** [comment]
tried multiple times, it works on first launch and then i add the mods and then it does the same, but again it works if i dont use the ftb app so something else is up and my pc dont really enjoy running the game without being in borderless

**Comment by Raidobw2** [comment]
Borderless window may have an incompatibility with the launcher's wrapper mechanic. What I'll do is have it reported to the app developers, but you won't be able to use borderless window. Instead you can press F11 in-game and you'll enter fullscreen, which will work

**Comment by CinnamonShaey** [comment]
true but the issue is my screen is running an unsupported resolution which is why i need borderless 2560z1080 is not an option in minecraft, but its not only borderless just ultimine alone does the same

**Comment by CinnamonShaey** [comment]
yea reinstalled the pack, this time with ultimine only, got stuck on the exact same point

**Comment by Raidobw2** [comment]
Minecraft is adaptative I don't understand. In-game, press the Windows button and the up arrow key, this will adapt the window to your resolution

**Comment by CinnamonShaey** [comment]
yeah but that does not get rid of the windows bar and top bar like full screen and borderless does

**Comment by Raidobw2** [comment]
Press F11 after that

**Comment by Raidobw2** [comment]
Borderless mod cannot work right now on FTB App

**Comment by CinnamonShaey** [comment]
F11 takes it into full screen but i get black bars in the sides cause its a wide screen

**Comment by MichaelHillcox** [comment]
Locked, use discord
