### ISSUE TITLE
[Bug]: Multiple Bugs For the nether and Draconic mod

### ISSUE THREAD

**Issue by Yolomic** [FTBTeam/FTB-Modpack-Issues#767]
### Modpack

FTB Sky Oddysey

### Modpack version

1.3.0

### Describe the bug

Issue 1
Modpack Version:1.3.0

Issue:When Going to the nether the portal to go back never works no matter what i tried and the nether inventory pet is broken in suck a way that it teleports you to random coords no matter where you are 

Link to Log or Crash File Paste: None?

Is it Repeatable?:Yes

Mod/s Affected:Vanilla,(Inventory pets maybe)

Known Fix:No Known Fix
Issue 2
Modpack Version:1.3.0

Issue:Getting multple Crafting Injectors or Crafting in general broken after making a wyvern level injector by building the basic craft injector multiblock the crafter allowed no other crafting and would refuse to give anything (also this may be intended but the crafting injectors have no emc value)

Link to Log or Crash File Paste:None Again?

Is it Repeatable?:Yes

Mod/s Affected:Draconic Evolution

Known Fix:No Known Fix!

### Steps to reproduce

Mentioned Above

### Expected behaviour

Being able to teleport Back home and being able to craft normally?

**Comment by Raidobw2** [comment]
About the inventory pets, we'll handle it at #637.

For the Draconic Bug, could you attach a picture next time you load in the game, if possible? That would help us understand where the issue is exactly (in which machine).

Thank for the report!

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/184836276-dd02a5f1-b4d0-4e6e-bd56-81ee3347dfc1.png)
Fusion Crafting does actually work, you just have to have ONLY the exact items in ur injectors, any additional item and the crafter breaks.
Tested out the Nether portal and Nether Portal Pet and both worked in the latest in-dev

If these Issues still occur on the next update, please make a new issue
