### ISSUE TITLE
[Bug]: Krate with compacting upgrade

### ISSUE THREAD

**Issue by MisterZam** [FTBTeam/FTB-Modpack-Issues#77]
### Modpack

FTB Oceanblock

### Modpack version

1.2.0

### Log Files

No logs

### Describe the bug

When Krate is full of inventory, it will continue compacting which results to voiding of items.

### Steps to reproduce

1. Put a stack of any chunk in the krate and fill the rest of the slots with anything.
2. Put compacting upgrade and set it to 2x2
3. Should start compacting but never receives the compacted items.

### Expected behaviour

No idea what should happen but my guess it should stop compacting when theres no space for the compacted item to go to.

### Additional information

Not additional information but suggestion instead. When sorting the inventory of the krate, the filter upgrades get yeeted in the slot and be sorted together in the inventory. Really annoying and destroys the automation in some cases. Hope this gets fixed thanks

**Comment by MichaelHillcox** [comment]
Please open an issue with the mod as this won't be something we can effect, many thanks.

https://github.com/owmii/krate/issues
