### ISSUE TITLE
[Bug]: AE2 certus quartz ore doesn't generate in multiplayer

### ISSUE THREAD

**Issue by zifnab06** [FTBTeam/FTB-Modpack-Issues#771]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.0.0

### Describe the bug

AE2 certus quartz is not generating on multiplayer worlds. This was tested in vanilla and terralith biomes. 

### Steps to reproduce

- generate multiplayer world
- give self scanner setup looking for certus quartz ore 
- go to between -34 and 36 (https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/init/worldgen/InitFeatures.java#L67-L68)
- no ores are found

### Expected behaviour

certus quartz is available between -34 and 36, like it is in singleplayer. 

### Screenshots

scannable setup: 
![image](https://user-images.githubusercontent.com/283805/168458423-5ee7f091-e95c-4658-ad72-34c9cff5bb37.png)

results of scanning on freshly generated multiplayer world (note, the scanner does find other ores/blocks): 
![image](https://user-images.githubusercontent.com/283805/168458462-d512e875-979e-4281-bab7-cc0692cff016.png)

result of scanning on freshly generated singleplayer world: 
![image](https://user-images.githubusercontent.com/283805/168458514-f036443f-5c4f-41a4-b85e-a0c6d352c849.png)

**Comment by UNST4BL3** [comment]
There is also no Certus oregen in the JAMD-world.
