### ISSUE TITLE
[Bug]: Configurator Not wrenching up items

### ISSUE THREAD

**Issue by Demonknight1434** [FTBTeam/FTB-Modpack-Issues#772]
### Modpack

Direwolf20 1.18.2

### Modpack version

1.18.2

### Describe the bug

Configurator created from Mekanism mod to use as Wrench

Configurator is in Wrench mode to pick up items quickly 

Wrench Mode will rotate items away from player, But not pick items up. Must use other tool to do so. 

### Steps to reproduce

1. Create Configurator
2. Put down any machine, pipe, Generator.
3. Put in wrench mode
4. Try to use wrench to pick up item

### Expected behaviour

Item gets picked up quickly and drop to ground for player to pick up

**Comment by Raidobw2** [comment]
I'm not fully sure this is how the Mekanism configurator works, but we'll test it in-game. Thanks for the report

**Comment by Demonknight1434** [comment]
Dont knwo whats happening but its working now weird .......i tried everything imma chalk it up to IT looking and now it works
