### ISSUE TITLE
[Bug]: Deep Resonance in Direwolf20 1.18

### ISSUE THREAD

**Issue by peisach** [FTBTeam/FTB-Modpack-Issues#773]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.0

### Describe the bug

The DeepResonance mod documentation is not working and the smelter does not work despite lava below it and a fluid tank above it.

### Steps to reproduce

Place a DeepResonance tank with lava (at around 50%), a DeepResource smelter and another tank all in a column.  Provide RF power to the smelter.  When you place resonating ore, it will not smelt.

### Expected behaviour

Expected to melt the DeepResonance ore into liquid crystal that is pumped to the above tank

### Screenshots

<img width="1392" alt="Screen Shot 2022-05-15 at 11 05 37 AM" src="https://user-images.githubusercontent.com/4675201/168479753-bf5139a1-55f0-4cbd-9871-095ab186e039.png">
<img width="1392" alt="Screen Shot 2022-05-15 at 11 05 32 AM" src="https://user-images.githubusercontent.com/4675201/168479757-464d38a4-0dbb-4e6b-af1d-e76bd2f9b74c.png">
<img width="1392" alt="Screen Shot 2022-05-15 at 11 05 21 AM" src="https://user-images.githubusercontent.com/4675201/168479759-d204240d-7cf0-4f3c-bd26-2916db860a59.png">

**Comment by Sunekaer** [comment]
Im not able to recreate this issue.
Is this in SP or MP?

**Comment by peisach** [comment]
By SP or MP do you mean single player versus multiplayer?  I run a server on an old Macbook pro and play the client on a slightly newer gaming PC that I built.  I would be happy to send you a copy of my world or invite you to log into the server yourself to take a look.

**Comment by Sunekaer** [comment]
Can you recreate this issue in Singleplayer?
Please also provide latest.log from server and client.

**Comment by peisach** [comment]
It seems unreproducible at the moment.  I came home, started up the server and connected, and found it working exactly how I left it before.  My apologies.  

I will close this bug.

**Comment by Sunekaer** [comment]
No problem, if it happens again, i would recommend creating a issue on their tracker so they can help you debug it :)
