### ISSUE TITLE
[Bug]: Animals Failing to Produce Baby when Bred [Direwolf20 1.18]

### ISSUE THREAD

**Issue by Aeper** [FTBTeam/FTB-Modpack-Issues#774]
### Modpack

Direwolf20 1.18

### Modpack version

1.0.0

### Describe the bug

When breeding or using spawn eggs with passive animals they fail to produce a child or animal. you get the xp and the visual effects but no baby.

### Steps to reproduce

1. Use Wheat on 2 Cows
2. Wait for effects
3. fail to see child spawn

### Expected behaviour

For a baby to appear

**Comment by CtNeal** [comment]
I am also having the same issue.

**Comment by Sp0rtiva** [comment]
Same issue for me. 
Animals and other passive mobs won't spawn from eggs either.

**Comment by Jared87** [comment]
Have this issue too, even when i Shift Rightclick Animals and drop them they disappear. 

I tested a bit around:
The `/summon minecraft:sheep ` command is also not working, something seems to disable spawning of mobs. I removed my Mega Torch to test if its the problem. But still no sheep. `/summon minecraft:skeleton` is working also with Mega Torch on the ground.
`/summon minecraft:chicken` works once and not a second time as long the summoned chicken lives. I was able to move and spawn a sheep once, but had to move ~200blocks away. I think its the same as the living chicken.

**Comment by Sunekaer** [comment]
Is this in Multiplayer or Singelplayer?

**Comment by Sp0rtiva** [comment]
For me it was single player

**Comment by Jared87** [comment]
Multiplayer

**Comment by CtNeal** [comment]
Single player for me.

> Is this in Multiplayer or Singelplayer?

**Comment by AdvogatoDaCivil** [comment]
Same for me, I hope they fix it soon
