### ISSUE TITLE
[Bug]: FTBIC Geothermal Generator Crash

### ISSUE THREAD

**Issue by sme23** [FTBTeam/FTB-Modpack-Issues#775]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.0.0

### Log Files

https://pastebin.com/V7BAeYdk

### Describe the bug

Game immediately crashes upon trying to pipe lava into an FTBIC Geothermal Generator

### Steps to reproduce

1. Place a Geothermal Generator
2. Place some tank containing lava
3. Configure a Pipez Fluid Pipe to pipe the lava into the bottom of the Geothermal Generator
4. Game immediately crashes, and reentering the world gives the same crash

### Expected behaviour

Geothermal Generator to fill with lava

**Comment by Raidobw2** [comment]
Thanks for the report
