### ISSUE TITLE
[Bug]: Cool Things reset quest button only works once

### ISSUE THREAD

**Issue by Avatarded** [FTBTeam/FTB-Modpack-Issues#778]
### Modpack

FTB University 1.16.5

### Modpack version

1.5.0

### Describe the bug

In the Misc-er section of the quest log, clicking the Cool Things quest reward to reset the quest only works once. After that it is flagged as an awarded reward and unclickable again. Once completed a second time, that's it. The quest is locked in the completed status and cannot be repeated after.

### Steps to reproduce

1. Go to cool things quest.
2. Sacrifice 5 levels to complete quest.
3. Reset quest.

### Expected behaviour

Cool Things quest infinite repeatable

### Screenshots
![Cool Bug, bro](https://user-images.githubusercontent.com/77522101/168499904-a061c18d-d204-47e5-bae4-90a8c3479717.png)

**Comment by Raidobw2** [comment]
Thanks for the report!

**Comment by aaronhowser1** [comment]
FTBTeam/FTB-Mods-Issues/issues/111

**Comment by aaronhowser1** [comment]
It should work after a relog, but this has to be fixed on a mod level, sorry
