### ISSUE TITLE
[Bug]: Client crash if you press M while logged into server

### ISSUE THREAD

**Issue by kdx7214** [FTBTeam/FTB-Modpack-Issues#780]
### Modpack

FTB Direwolf 20

### Modpack version

1.18

### Describe the bug

Log into a Direwolf20 1.18 server that you have setup on linux.   Launch the client and log in.  Press the M key and client crashes

### Steps to reproduce

1.  Load server (linux)
2. Load client (Windows)
3. Log into server
4. press M on the client
5. watch client crash w/o error message

### Expected behaviour

Should have brought up the map like it does in single player

**Comment by Raidobw2** [comment]
Linked to https://github.com/FTBTeam/FTB-Mods-Issues/issues/70, thanks for the report

**Comment by cungefehr** [comment]
Hey - i cannot reproduce this issue with a Ubuntu 20.04.4 LTS and windows 10 client.

**Comment by Raidobw2** [comment]
This error is random, you can't really reproduce it apart from dimension hopping and even then it's inconsistent. Michael knows about this issue, it's something on his todo list

**Comment by Sunekaer** [comment]
Crash log please
