### ISSUE TITLE
[Bug]: DW20 1.18 Bamboo Fence Gate Uncraftable

### ISSUE THREAD

**Issue by alans** [FTBTeam/FTB-Modpack-Issues#781]
### Modpack

FTB Direwolf 1.18

### Modpack version

1.0.0

### Describe the bug

When trying to make a 'Bamboo Fence Gate', it requires 'Bamboo Bundle' from the same mod. However, when trying to make a Bamboo Bundle, it instead makes a 'Block of Bamboo' from the Thermal Series mod, and does not work to make the fence gate.

### Steps to reproduce

Try to make Bamboo Fence Gate
Try to make Bamboo Bundle for fence gate
Makes Block of Bamboo instead
???
Bug!

### Expected behaviour

When making a Bamboo bundle, either it should overwrite the Block of Bamboo, or they both should be the same dictionary.

**Comment by Raidobw2** [comment]
Thanks for reporting!
