### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ClaymooreEOC** [FTBTeam/FTB-Modpack-Issues#782]
### Modpack

DW20 1.18

### Modpack version

1.0.0

### Describe the bug

Blaze heads from tinkers are not listed as mob drops so the mob grinding utils grinder with beheading modifiers cannot aquire them.

### Steps to reproduce

Build a mob grinder by a blaze spawner.
Insert beheading modifiers.
Loot blazes.

### Expected behaviour

Blaze heads should drop from the mob grinder

**Comment by Sunekaer** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/4863

**Comment by TheonlyTazz** [comment]
Hardcoded in Mob-grinding-utils
https://github.com/vadis365/Mob-Grinding-Utils/issues/201

**Comment by Flanks255** [comment]
Fixed in 1.18.2-0.4.38
