### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AdvogatoDaCivil** [FTBTeam/FTB-Modpack-Issues#783]
### Modpack

Direwolf20 Modpack

### Modpack version

1.18.2

### Describe the bug

Animals won't spawn even with commands or eggs

### Steps to reproduce

1. Create world
2. After exploring animals wills stop spawning
3. after a while even commands ow eggs won't make they appear 

### Expected behaviour

Animal spawn

**Comment by Sunekaer** [comment]
#774
