### ISSUE TITLE
[Bug]: Game will not let me play and sticks me in a loading error screen

### ISSUE THREAD

**Issue by TheEternalDerp** [FTBTeam/FTB-Modpack-Issues#784]
### Modpack

FTB Oceanblock

### Modpack version

1.12.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8703994/latest.log)
[crash-2022-05-16_19.32.58-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8703995/crash-2022-05-16_19.32.58-fml.txt)

### Describe the bug

I just downloaded the modpack and tried to launch it. When it loads I am told "Error loading mods; 3 errors have occured during loading." Those errors are

- ReAuth has failed to load correctly java.lang.ExceptionInInitializerError: null
- Failed to load mod
- Failed to load mod

I just want to play the modpack and I do not know how to fix this issue :(

![Capture](https://user-images.githubusercontent.com/74376738/168699344-ecd566ec-db12-4c29-a2e7-dde45a7210db.JPG)

### Steps to reproduce

I just downloaded the pack and ran it through multimc when it was done. I'm hopeful this is just a me problem though

### Expected behaviour

I expected the pack to load all the way and allow me to play the game

### Screenshots

![Capture](https://user-images.githubusercontent.com/74376738/168699344-ecd566ec-db12-4c29-a2e7-dde45a7210db.JPG)

### Additional information

I said it above, but this is the first time I have downloaded this pack in order to play it.

**Comment by TheonlyTazz** [comment]
You are using Minecraft 1.16.5 but used java 17.0.2.
![grafik](https://user-images.githubusercontent.com/3908847/168741218-349f5d79-7c95-4e54-9d87-db495c8c08e0.png)
Minecraft 1.16.5 uses Java 8.x.
Using the FTBApp should directly use the correct version of Java.
If you do want to use MultiMC, be sure to check the Java Installation thats being used by clicking `Edit Instance` and go to settings
![grafik](https://user-images.githubusercontent.com/3908847/168741432-dc50faba-c6c1-47ad-a525-d08e726a18b1.png)


Please test this and report if that fixes your issue

**Comment by TheEternalDerp** [comment]
That fixed the problem, thank you!
