### ISSUE TITLE
[Bug]: Squeezer recipe bug for Diamonds

### ISSUE THREAD

**Issue by Almandor** [FTBTeam/FTB-Modpack-Issues#787]
### Modpack

Direwolf20 1.18

### Modpack version

1.1.0

### Describe the bug

Diamond Recipe gets removed from squeezer after one use

### Steps to reproduce

When you look up the recipe for Diamonds in the squeezer you'll find:

DiamondOre drop 100% 100% 70% 70% Diamonds. This can be confirmed by putting a block of diamond ore in the squeezer and jumping on it.

After the block is processed the recipe changes. Now diamond ore does not show any output though the recipe still can be found by clicking on a diamond in JEI.

The no result can be confirmed by adding a block of Diamond Ore in the squeezer and jumping on it. No dops occur.

### Expected behaviour

Recipe stays active and can be done over and over again.

### Screenshots

![after](https://user-images.githubusercontent.com/19967786/168865466-47a2a70f-2ad5-4b20-841e-0f9fb9b9515b.jpg)
![before](https://user-images.githubusercontent.com/19967786/168865476-30cf07c6-9b20-40e3-a5df-6860ecd9e96a.jpg)

**Comment by Sunekaer** [comment]
#761
