### ISSUE TITLE
[Bug]: 2 of 3 phyto-gro recipes call for non-existent resources.

### ISSUE THREAD

**Issue by NytSong** [FTBTeam/FTB-Modpack-Issues#788]
### Modpack

FTB University 1.16

### Modpack version

1.4.0

### Describe the bug

Two of the three phyto-gro recipes call for apatite and I could not find any.  Asked about it in discord and was shown that apatite is configured to not spawn in the world.  
I didn't look to see if the resources for the third one are available or not.

### Steps to reproduce

search for phyto-gro
look at available recipes to make it
see that two call for apetite

 

### Expected behaviour

For a required resource to be available or for the recipe to be changed/hidden

### Screenshots

![phyto-gro_recipes](https://user-images.githubusercontent.com/61587778/168871967-223a65e7-ae8c-45d4-91b9-0359454ec42d.png)

![world-generation-settings](https://user-images.githubusercontent.com/61587778/168871983-07c1ac86-0ee4-4247-a89c-88170e4ba35b.png)

**Comment by TheonlyTazz** [comment]
According to the source, its stated that the worldgen of Apatite is set to true
![grafik](https://user-images.githubusercontent.com/3908847/168878642-640d9948-63fd-44d7-83e2-fed58dd5a498.png)

this has been changed 6 months ago, i will check thecurrent 1.4.0 version to see if this update actually got pushed to 1.4.0 or if its part of 1.5.0

**Comment by NytSong** [comment]
> I just checked on a fresh 1.4.0 Instance and it definetly has Apatite set to true (and Cinnabar set to false) so i can only assume you generated your world in 1.3.0?

You flagged this as Academy. I'm playing University.  
aaronhowser1 is the one who showed me why I wasn't seeing apatite in Discord

![troubleshooting](https://user-images.githubusercontent.com/61587778/168938027-1974c29f-7150-4a9b-a3c6-3c652b603691.png)

Also, yes, I am 100% absolutely certain I have 1.4.0 installed.  

![Modpack-Version](https://user-images.githubusercontent.com/61587778/168938469-67d33c57-31f8-44d7-be14-2e5d5d023163.png)


I guess if he had it wrong then that would be where the wrong info came from.

I finally found what file this is referred to and you are correct, it does say apatite is set to true.
Though it is extremely odd that I haven't seen a single bit of it here when I was swimming in it on Ultimate Anniversary.

**Comment by NytSong** [comment]
Zero idea if this means anything or not so forgive me.  I like to poke about and look but am still learning my way around what is found where and means what.  
In looking through world-gen.json I see mention of all the other ores, but no mention of apatite.
[world-gen.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8712737/world-gen.zip)

**Comment by TheonlyTazz** [comment]
I accidently tagged the wrong modpack, but i did actually test this on University.
Upon opening a fresh name world and fly around for a bit, i noticed it infact doesnt spawn.
It also seems that Apatite ore is hidden in REI, so further investigation is definetly needed

**Comment by NytSong** [comment]
At least I know I'm not insane.  I'd mentioned tagging the wrong modpack mainly to see if it was changable so if anyone else happens to come looking. 
Thanks for confirming, I'll stop hunting.

**Comment by aaronhowser1** [comment]
Apparently Apatite only generates if Thermal _Cultivation_ is installed, which it is not. I'll remove its recipes, sorry for the confusion!
