### ISSUE TITLE
[Bug]: MineColonies missing Localization

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-Modpack-Issues#790]
### Modpack

Direwolf20

### Modpack version

1.1.0

### Log Files

N/A

### Describe the bug

MineColonies missing job Localizations

### Steps to reproduce

1. make coloney
2. build a buider or other hut if have builds
3. open npcs GUI
4. open there job tab

### Expected behaviour

not to see a loc key

### Screenshots

 ![](https://ss1.manmaed.net/1652826709.png)

### Additional information

checked newest version still happens reported to autor: https://github.com/ldtteam/minecolonies/issues/8385

**Comment by Sunekaer** [comment]
https://github.com/ldtteam/minecolonies/issues/8385

**Comment by manmaed** [comment]
https://github.com/ldtteam/minecolonies/issues/8385 has been closed and should be out?
