### ISSUE TITLE
[Bug]: copper duplication glitch in stonecutter

### ISSUE THREAD

**Issue by Craftchunks** [FTBTeam/FTB-Modpack-Issues#791]
### Modpack

Direwolf 1.18

### Modpack version

1.0.0

### Describe the bug

infinite copper duping glitch in stonecutter

### Steps to reproduce

1. put block of copper in stonecutter
2. select block of copper and take out four blocks of copper for every 1 block put in

### Expected behaviour

this recipe to not exist

**Comment by mdelz** [comment]
And the recipe `minecraft:copper_block` => 4x `minecraft:cut_copper` is missing.
