### ISSUE TITLE
[Bug]: Deepslate Certus Ore missing regular Certus Ore Enrichment Chamber recipe

### ISSUE THREAD

**Issue by lpacphantom** [FTBTeam/FTB-Modpack-Issues#799]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.2.0

### Describe the bug

There's an Enrichment Chamber recipe for Certus Quartz ore to 5 Certus Quartz Dust, but the Deepslate Certus Quartz Ore doesn't.

### Steps to reproduce

1. Attempt to use Deepslate Certus Quartz ore in Enrichment Chamber - or - Look in JEI for uses of Deepslate vs regular Certus Quartz ore.

### Expected behaviour

Deepslate Certus Quartz to act as regular Certus Quartz

**Comment by Raidobw2** [comment]
Thanks for the report
