### ISSUE TITLE
[Suggestion]: Refined Storage RSInfinityBooster

### ISSUE THREAD

**Issue by Hexeption** [FTBTeam/FTB-Modpack-Issues#80]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

Be nice to have able to have unlimited range on Refined Storage wireless terminal.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/rsinfinitybooster

**Comment by Sunekaer** [comment]
Duplicate of #21
