### ISSUE TITLE
[Bug]: Refined Storage - Compacting Drawer w/ Creative Vending upgrade not working 

### ISSUE THREAD

**Issue by neldridge** [FTBTeam/FTB-Modpack-Issues#803]
### Modpack

FTB Oceanblock

### Modpack version

1.12.0

### Describe the bug

Creative vending upgrade in compacting drawers causes certain items to not be able to be extracted through refined storage.

### Steps to reproduce

1. Compacting drawer with creative vending upgrade
2. Electrum ingot
3. External storage to Refined Storage system (on controller or drawer directly)
4. Attempt to get items through refined storage (doesn't work)
5. Pull directly from drawer (works as expected)

### Expected behaviour

Able to extract items from compacting drawers through refined storage

### Screenshots

![image](https://user-images.githubusercontent.com/720437/169310521-eccf4e9b-d51d-465e-a963-15a00c515bea.png)

### Additional information

I've noticed this only occurs for certain ingots, I'll do some more testing and report back with a list of working and non-working items.

**Comment by neldridge** [comment]
I've put every type of ingot I could find into a compacting drawer with a creative vending upgrade. The behavior is bizarre, often when trying to extract them for the first time it actually pulls the ingot from the drawer entirely and I have to reinsert.
This behavior doesn't happen when I pull from the drawer directly first.

No ingots seem to behave as I would expect with the vending upgrade though.

![image](https://user-images.githubusercontent.com/720437/169332719-f4ef0a40-bb55-4fcb-8ffb-76f11ac3f26d.png)

Happy to share the world, if needed.

**Comment by TheonlyTazz** [comment]
Thanks alot @neldridge! 
I forwarded this to the Storagedrawer Github because this issue still occurs with the latest version of Storagedrawers.

https://github.com/jaquadro/StorageDrawers/issues/1022

**Comment by Gaz492** [comment]
Unfortunately, it looks like the mod author never replied to the issue we opened, so there is very little chance that this issue will be resolved.
