### ISSUE TITLE
[Bug]: Thermal machinery causes ticking exception

### ISSUE THREAD

**Issue by WTFFFS** [FTBTeam/FTB-Modpack-Issues#804]
### Modpack

Direwofl20 1.18

### Modpack version

1.0.0

### Log Files

https://paste.ee/p/8cVpb

### Describe the bug

When using the coin mould (numismatic die) in the multiservo press the world corrupts with a ticking entity error repeatably, as soon as the craft finishes. EDIT: Crap I uploaded the wrong crash log to pastebin this is the correct log https://paste.ee/p/11EnQ

### Steps to reproduce

Place coin mould in a multiservo press, put in copper ingot (minecraft ingot), as soon as the craft finishes and before there is any output the game will CTD. Press was running on a Flux Capacitor with a Reinforced upgrade (just in case that may be a factor)

### Expected behaviour

I expected it to not crash my world and make it unusable.

**Comment by lord-ne** [comment]
Can confirm this also happens with magma blocks with the unpacking die, and that it still happens in the newest version of the pack (1.2.0)
