### ISSUE TITLE
[Bug]: DW20 1.18.2 1.2 Functional Storage (Drawers) Not respecting ore nuggets

### ISSUE THREAD

**Issue by BrewingCoder** [FTBTeam/FTB-Modpack-Issues#805]
### Modpack

DW20 1.18.2

### Modpack version

1.2

### Log Files

N/A

### Describe the bug

Functional Storage does not respect all nuggets/fragments

Biggest complaints:   Copper nuggets, ender fragments

### Steps to reproduce

put down function storage compacting drawer

Crush/wash some copper in a Create setup, getting copper nugs

attempt to put nugs in compacting drawer.

### Expected behaviour

the ability to configure compressing drawers to support all the nugs

**Comment by quietust** [comment]
To make things worse, the compacting drawer doesn't understand that Quartz Bricks aren't actually a "compressed" form of Quartz Blocks, and as a result it allows quartz to be infinitely duplicated.

**Comment by TheonlyTazz** [comment]
![grafik](https://user-images.githubusercontent.com/3908847/178483752-92a1857a-2791-450b-8d7d-905df0bbfa44.png)
The Quartz dupe has been fixed, the Copper nuggets can be solved by placing in a nugget first. Ender Fragments into pearls is not going to get fixed bcause of the way Forbidden&Arcanus is doing the recipe, its not an actual compacting recipe
