### ISSUE TITLE
[Bug]: ae2 ranged booster is uncraftable

### ISSUE THREAD

**Issue by zifnab06** [FTBTeam/FTB-Modpack-Issues#806]
### Modpack

Direwolf20 1.18

### Modpack version

1.2.0

### Describe the bug

ae2:wireless_booster is uncraftable because no items tagged forge:dusts/ender_pearl are craftable (the only craftable ender pearl dust is tagged forge:dusts/ender from ftbic). 

### Steps to reproduce

- try to craft ae2 wireless booster
- fail

### Expected behaviour

craftable item

### Screenshots

![image](https://user-images.githubusercontent.com/283805/169469290-77b42b13-bc44-4676-a584-5511ffc36518.png)
![image](https://user-images.githubusercontent.com/283805/169469331-0c63d145-8ace-402d-9f2b-fc02868ab673.png)
![image](https://user-images.githubusercontent.com/283805/169469360-33cdd6d2-9916-42e1-a098-67ef1bc03cff.png)
![image](https://user-images.githubusercontent.com/283805/169469382-dbb654fd-7911-422e-bfa0-6dc5338628a9.png)

**Comment by Jared87** [comment]
This is the same bug i mentioned in #795, i already mentioned the fix is not working. The creation process of exploding an singularity with ender dust is also still not working in 1.2
