### ISSUE TITLE
[Bug]: No mob spawn with spawn agitator from Pneumaticraft

### ISSUE THREAD

**Issue by Ceruleann** [FTBTeam/FTB-Modpack-Issues#807]
### Modpack

FTP Presents Direwolf20 1.18

### Modpack version

1.2.0

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8740005/console.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8740006/debug.log)

### Describe the bug

Using Pneumaticraft's Spawner Agitator prevents the spawn of mobs. Removing the Spawner Agitator allows for the mobs to spawn from the same Vanilla spawner.

### Steps to reproduce

1. Pick up a vanilla spawner using Mekanism's cardboard box. Only tried with Zombie spawner.
2. Place cardboard box in unlit area.
3. Remove cardboard box by right click sneaking to unpack the vanilla spawner.
4. Place spawner agitator on spawner.
5. Zombies do not spawn regardless if player is within 16 blocks or not of spawner.
6. Remove spawner agitator by picking up the spawner using Carry On mod shift-right click.
7. Place the spawner again. After a while Zombies spawn as per Vanilla mechanics.

### Expected behaviour

Zombies should spawn

**Comment by TheonlyTazz** [comment]
could not replicate this issue on the latest in-dev (future 1.6.0)
