### ISSUE TITLE
[Bug]: Mobs not spawning with Mob Grinding Utils' Dreadful Dirt

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#808]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.2.0

### Describe the bug

Background: I built a small mob farm using dreadful dirt and a few other bits from Mob Grinding Utils plus redstone-controlled lighting using SImply Lights's blocks. After a lot of nil-spawns, it did work once out of roughly a dozen tries but have had no luck getting hostile mobs to spawn since then.

I've reduced things down in a creative test world to a 5x5x3 internal structure as seen in the picture (with the middle 9 blocks placed unlike in the screenshot) and still no mob spawns. Game mode, distance from the structure, Y level etc. makes no difference.

![image](https://user-images.githubusercontent.com/17010632/169678548-d4123747-b845-4d82-93a3-7e4b883ed5f2.png)

### Steps to reproduce

1. Create structure as in screenshot
2. Wait for mobs not to spawn

### Expected behaviour

Mobs spawn correctly

**Comment by Raidobw2** [comment]
Hello, thanks for the report! If mobs still don't spawn a lot, please let us know here. If mobs don't spawn at all, let us know as well. If the issue seems to have resolved itself, please close the issue!

**Comment by TechGeekMonster** [comment]
In 1.18 you need absolutely no light at all for mobs to spawn. Is that condition met?

**Comment by Sunekaer** [comment]
Yes, the lighting changed in 1.18 and you need to meet those conditions.
Also in my testing, the mobs disappear as soon as they spawn do you also have that issue?

**Comment by ukmcplyr** [comment]
Yep, light levels are at 0 inside the kill chamber where the dreadful dirt is placed.

No change since a few days ago: mobs spawn in small numbers but only at night. There're not disappearing here at least, though, which is a plus!

**Comment by TheonlyTazz** [comment]
please try again on the latest version, i could not replicate this on the latest stable, if this does happen again, feel free to tell me and we will reopen

![javaw_9xhYhbnKWT](https://user-images.githubusercontent.com/3908847/178476058-8c61b5e9-bbc7-40f2-b7f3-8a34fa40d9ae.png)
