### ISSUE TITLE
[Bug]: Opening certain wooden chests causes the server to crash

### ISSUE THREAD

**Issue by Br00t4L17y** [FTBTeam/FTB-Modpack-Issues#809]
### Modpack

Direwolf20

### Modpack version

1.2.0

### Log Files

[crash-2022-05-20_15.34.51-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8743705/crash-2022-05-20_15.34.51-server.txt)
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8743707/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8743708/debug.log)

### Describe the bug

We disabled lootr by adding "minecraft:overworld" to the `location_blacklist` variable in the `lootr-common.toml` config file. Now that we are rendering new chunks, we find vanilla chests again. However on occasion when trying to open one of these chests, the entire server crashes.

### Steps to reproduce

1. Open vanilla chests
2. Find one that doesn't open
3. Server crashes shortly after

### Expected behaviour

Server does not crash :)

**Comment by Sunekaer** [comment]
could you test the following?
-     Note the location of the chest
-     Copy the world seed
-     Disable lootr
-     Create a new world using the exact same pack & settings with the current seed
-     Open the chest without Lootr

Let me know if it still crashes.

**Comment by Sunekaer** [comment]
Also please provide the seed and location of this issue

**Comment by noobanidus** [comment]
It doesn't appear to be an issue with Lootr specifically, but rather the structure that is being targeted by the map function contained in the chest.

I think blacklisting the overworld is a good way of testing this issue and demonstrating that Lootr isn't the problem, although it would be useful to have the seed and location of the chest to determine *which map* is causing this issue specifically.

Once the type of map is known, testing with the structure `locate` command might also give more insight.

**Comment by TelepathicGrunt** [comment]
Try without terrablender. Also do /data get block on the chest before opening it and if it crashes, tell us what the loot table is so we can get a sense of what structure it could be trying to find with the explorer map

**Comment by TelepathicGrunt** [comment]
![CF6929B4-4BF5-4118-974E-C81B6CA51866](https://user-images.githubusercontent.com/40846040/170089541-c3a94c12-d6b4-4672-855a-4a99e1ac2ca6.png)

here’s the command to run and test if it fixes the issue
/scoreboard players set %DISABLE_MAP tr.disable_maps 1

**Comment by Br00t4L17y** [comment]
Thanks for your work on this. I originally had blown up the chests with tnt (which removed the chest). I will post back if I run into another bugged chests. In the meantime I will run this command and keep an eye out.

**Comment by TelepathicGrunt** [comment]
The biome that terralith’s dummy structure spawns in may not be spawning due to terrablender or something. And with Repurposed Structures on (assuming you have to mod), it expands the search from 100 to 2000 for locating structures which could make the map take too long to find the structure for servers as it cannot spawn and searches too far. I’ll work on RS and try to make the expanded search only apply for certain rs structures instead

**Comment by MacChuck** [comment]
Is the command from that discord screenshot confirmed working as a temporary fix?
