### ISSUE TITLE
[Bug]: Gilded Netherite Pickaxe

### ISSUE THREAD

**Issue by Jack-NZ** [FTBTeam/FTB-Modpack-Issues#81]
### Modpack

FTB Cotton

### Modpack version

1.10

### Log Files

N/A

### Describe the bug

The Gilded Netherite Pickaxe from Gilded Netherite is not able to mine any modded ores. Wailia reports that the block is not harvestable. 

### Steps to reproduce

1. Obtain Gilded Netherite Pickaxe
2. Mine any modded ore

### Expected behaviour

The pickaxe should mine these ores.

### Screenshots

[https://i.imgur.com/Ga3VrAE.png](url)
[https://i.imgur.com/AYZHSED.png](url)

**Comment by manmaed** [comment]
This  issue is now stale
