### ISSUE TITLE
[Bug]: Mekanism ore processing DW20 1.18

### ISSUE THREAD

**Issue by Mechantronic** [FTBTeam/FTB-Modpack-Issues#810]
### Modpack

Direwolf 1.18

### Modpack version

1.2

### Describe the bug

When trying to double the ore chunks trough mekanism. I found out that the following chunks cant be processed trough mekanism :  aluminum chunks, raw nickel, iridium and silver. the enrichment chamber works, but the later stages dont.

### Steps to reproduce

Open purifaction chamber
try to insert the following ore chunks  aluminum chunks, raw nickel, iridium and silver

### Expected behaviour

the ore chunks should be inserted into purifaction chamber and be proccesed

**Comment by Sunekaer** [comment]
That's because there are no clump versions of those metals in mekanism
