### ISSUE TITLE
[Bug]: Ender Dust

### ISSUE THREAD

**Issue by DinnerBeef** [FTBTeam/FTB-Modpack-Issues#811]
### Modpack

DW20 1.18

### Modpack version

1.2.0

### Describe the bug

The only ender dust that can be made is form FTB:IC. However that dust cant be used in the Induction Smelter to make enderium looks like it need the forge:dusts/ender_pearl tag 

### Steps to reproduce

Try and put ender dust in induction smelter 

### Expected behaviour

Ender Dust to work for enderium

**Comment by quietust** [comment]
Same root cause as #806. Also, modpack is 1.18, not 1.15.

**Comment by DinnerBeef** [comment]
yep it is
