### ISSUE TITLE
[Bug]: Integrated Dynamics Squeezer/CarryOn Dupe Bug

### ISSUE THREAD

**Issue by MaxFirestorm** [FTBTeam/FTB-Modpack-Issues#818]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.2.0

### Describe the bug

When using CarryOn on the Integrated Dynamics Squeezer that currently has an item inside of it, the item will pop out of the Squeezer when it is placed back down, but the item will still be inside of the Squeezer and can be removed, giving you two of the items.

### Steps to reproduce

1. Place item inside ID Squeezer (either through automation or manually)
2. Use CarryOn to pick up the Squeezer into your hands
3. Use CarryOn to place the Squeezer back down again
4. Item inside of Squeezer will pop out onto the floor, but a copy of the item will remain inside
5. Right click with empty hand to remove original item, giving you two when counting the popped-out item from Step 4

### Expected behaviour

Item not popping out of Squeezer, or item being removed from squeezer when item pops out

### Screenshots

Not a screenshot, but was streaming at the time so grabbed a clip - https://clips.twitch.tv/AmericanLongSoymilkTebowing-N0vlpS6ffB-wH9wv

**Comment by Novakrae** [comment]
Still present in 1.3.1
