### ISSUE TITLE
[Bug]: Recipe Conflicts

### ISSUE THREAD

**Issue by sme23** [FTBTeam/FTB-Modpack-Issues#819]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.2.0

### Describe the bug

Just a list of recipe conflicts

Build Tool (Structurize) & Stone Wand (Construction Wand)
Scan Tool (Structurize) & Iron Wand (Construction Wand)
Boom Arrow (Forbidden & Arcanus) & Explosive Arrow (Archer's Paradox)
3x Brick Vertical Slab (Quark) & 1x Red Brick Vertical Slab (Create Deco) 
Scoria (Create) & Vile Dust (Soul Shards)

RebornStorage Fluid Storage recipes accept lower-tier Refined Storage Storage Parts in their recipes when they shouldn't:
256k Fluid Storage Disk (Refined Storage) & 4096K Fluid Storage Disk (RebornStorage)
1024k Fluid Storage Disk (Refined Storage) & 16384K Fluid Storage Disk (RebornStorage)
4096k Fluid Storage Disk (Refined Storage) & 49152K Fluid Storage Disk (RebornStorage)
4096k Fluid Storage Part (Refined Storage) & 49152K Fluid Storage Part (RebornStorage)

### Steps to reproduce

Attempt to craft any of the above items and be unable to obtain one of the two in each pair due to conflicting recipes.

### Expected behaviour

Non-conflicting recipes

**Comment by Sunekaer** [comment]
https://github.com/TechReborn/RebornStorage/issues/174

**Comment by Sunekaer** [comment]
Fixed first part.
