### ISSUE TITLE
[Bug]: Skill books generated by Woot factory is not well formed and causes crash on usage

### ISSUE THREAD

**Issue by Akiminos** [FTBTeam/FTB-Modpack-Issues#82]
### Modpack

FTB University 1.16

### Modpack version

1.2.0

### Log Files

[crash-2021-10-04_16.49.13-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7278943/crash-2021-10-04_16.49.13-client.txt)

### Describe the bug

Opening a skill book from Epic Fight Mod generated by a Woot factory is causing the game to crash

### Steps to reproduce

1. Put in place a Woot factory (mine was tier 1, Zombie type)
2. Wait until you get a skill book drop from Epic Fight Mod
3. Take and open the book
4. Game crashes

### Expected behaviour

The book should be a valid one that should be "learnable"

**Comment by aaronhowser1** [comment]
Them crashing has been fixed inn update to EFM, but I'll poke the Woot dev about being able to blacklist items.

**Comment by aaronhowser1** [comment]
Actually wait, that's already in. Fixed!
