### ISSUE TITLE
[Bug]: DW20 Narslimmus not working

### ISSUE THREAD

**Issue by Kurotsune77** [FTBTeam/FTB-Modpack-Issues#821]
### Modpack

Direwolf20

### Modpack version

1.2.0

### Describe the bug

the Botania mana generating flower Narslimmus totally ignores naturally spawned slimes
![2022-05-22_18 11 53](https://user-images.githubusercontent.com/96918301/169706506-ece18f12-d34f-43c0-ba6a-d2b3fb9bddc8.png)

presumably some mod causes the botania's tag for designating naturally spawned slimes to false
![image](https://user-images.githubusercontent.com/96918301/169706563-4ce0774e-1135-4ecd-8746-93c3a5dd7ff8.png)

when I manually spawn a slime with the tag set to true
![image](https://user-images.githubusercontent.com/96918301/169706579-65a14443-9f5c-4121-95e6-3a804db113ad.png)

it works as intended

### Steps to reproduce

1. Find a slime chunk (for survival)
2. Place Narslimmus
3. wait for slime to spawn
4. watch it just casually jump on the Narslimmus, like it's not supposed to just die and be converted to mana

### Expected behaviour

From what I read and experimented with forge-40.1.21 and only Botania-1.18.2-432 +dependencies,
Naturally spawned Slimes should have the botania tag set to true and thus be consumed by Narslimmus the moment they enter it's work radius, doesn't even have to be in a slime chunk

**Comment by farigiss** [comment]
The mod that causes this problem is WYML (Why You Make Lag). Disabling it fixes narslimmus behaviour on versions 1.3.1 and 1.5.1 of the pack.
