### ISSUE TITLE
[Suggestion]: Increase number of Curios charm slots

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#823]
### Modpack

FTB Presents Direwolf20 1.18

### Is your suggestion related to a problem? Please describe.

There are a number of handy tools/charms in this modpack but only one can be equipped in the Curios inventory. I've played other packs which had half a dozen or more charm slots which may be a bit OP for some, but just one or two extra slots would be a nice quality-of-life addition.

**Comment by Sunekaer** [comment]
Slots wont be increased, but thanks for the suggestion
