### ISSUE TITLE
[Suggestion]: Storing sand in compacting drawer

### ISSUE THREAD

**Issue by skupr** [FTBTeam/FTB-Modpack-Issues#824]
### Modpack

FTB OceanBlock 1.12.0

### Is your suggestion related to a problem? Please describe.

Currently, if Sand block is put into Compacting Drawer (from Storage Drawers mod), it'll be compacted as a Sandstone.
But I think it's more proper for this pack to compact sand into "1x Compressed Sand" and "2x Compressed Sand".

Moreover, it allows to easily convert sandstone back into sand - which I guess isn't supposed to be, as there's no such crafting recipe (it should be done via some kind of crushing).

This can be fixed by changing config file `storagedrawers-common.toml` by adding compacting rule:
```
	compactingRules = [... , "rid:1x_compressed_sand, minecraft:sand, 9"]
```

Attaching the whole fixed config (based on config from FTB Oceanblock 1.12.0)
[storagedrawers-common.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8754411/storagedrawers-common.zip)

**Comment by skupr** [comment]
Additional note: I've tried to workaround this by putting "1x Compressed Sand" or "2x Compressed Sand" to different slots of Storage Drawers, but in any case Storage Drawer was set up as the following combination:
* 1x Compressed Sand
* 2x Compressed Sand
* 3x Compressed Sand
which does not allow to put regular sand into it.

**Comment by TheonlyTazz** [comment]
Thanks alot for your Issue and directly offering the fix for it!
I have implemented it into the in-Dev and will be pushed with the future update.
