### ISSUE TITLE
[Suggestion]: Fix new chloroform recipe to conform to stoichiometric ratios

### ISSUE THREAD

**Issue by linaposting** [FTBTeam/FTB-Modpack-Issues#825]
### Modpack

FTB Interactions

### Is your suggestion related to a problem? Please describe.

The new chloroform recipe violates stoichiometric ratios, and is too cheap.

### Mod suggestion

CH4(g) + 3Cl2(g) -> CHCl3(l) + 3HCl(g) correct

C(s) + HCl(g) -> CHCl3(l) incorrect

c(s) + 3HCl(g) -> CHCl3(l) + H2(g) corrected

The new recipe should require 1 carbon dust, 3 buckets of HCl, and net 1 bucket of chloroform and 2 buckets of hydrogen gas.

**Comment by Saereth** [comment]
This is intentional, many of the gt recipes violate stoichiometric ratios, they're there when they're good and make sense but when an automation flow process doesnt work the way we'd like sometimes its a bit off. This isnt exactly pack breaking so its not something that will be changed
