### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by siasassassin** [FTBTeam/FTB-Modpack-Issues#829]
### Mod

rftool

### Mod version

rftoolsbuilder-1.18-4.0.10

### Forge / Fabric version

 forge 40.1.20

### Modpack & version

ftb direwolf20 1.18

### What issue are you having?

i bullied  a rftool builder for a quarry its dig line miss a line or 2 and  start to dig again  dont  know if a bug or just missing sumthing new from 1.16.5 i last use it 

 
![2022-05-23_16 16 19](https://user-images.githubusercontent.com/106096734/169851983-ee2b3689-b752-4d59-b8fa-bf88908894ab.png)

![2022-05-23_16 23 51](https://user-images.githubusercontent.com/106096734/169853413-a7cd1643-f2f8-4dfe-bf87-16e6d25b4304.png)

![2022-05-23_16 23 55](https://user-images.githubusercontent.com/106096734/169853435-e0a6f6c3-2d49-4706-a830-8f83e7b7ac8c.png)

### Steps to reproduce

its starts doing it as u first start it running

**Comment by Sunekaer** [comment]
I see your card is set to Hollow.
Change it to Solid.
