### ISSUE TITLE
[Bug]: Phytogenic Insulator doesn't work with Certus Quartz Seed

### ISSUE THREAD

**Issue by crims0nHD** [FTBTeam/FTB-Modpack-Issues#83]
### Modpack

FTB Revelations

### Modpack version

3.5.1

### Describe the bug

Phytogenic insulators (from Thermal Expansions) used to take in glowstone dust and a certus quartz seed to make a pure certus quartz crystal. However, now I can't even put the certus quartz seed into the phytogenic insulator. When I restart the game, sometimes it works, but stops working after some time.
https://github.com/Cazadorsniper/PO3/issues/1221 (describes the problem)

### Steps to reproduce

1. Place down the phytogenic insulator
2. Hook it up to a rf power source and water pipe
3. Put in the glowstone and try to put in the certus quartz seed

### Expected behaviour

I expected the certus quartz seed to be able to be put into a phytogenic insulator

### Screenshots

![image](https://user-images.githubusercontent.com/49682210/135896805-ce44bbdb-77cb-4d26-84b5-fa05a5d40ce6.png)

**Comment by feeedback** [comment]
?

**Comment by TheonlyTazz** [comment]
Fixed in V3.6.0
