### ISSUE TITLE
[Bug]: Immersive Engineering Thermoelectric Generator

### ISSUE THREAD

**Issue by Vypir** [FTBTeam/FTB-Modpack-Issues#830]
### Modpack

Direwolf20 1.18

### Modpack version

1.2.0

### Describe the bug

Crafting uranium blocks only allows the FTB Industrial Contraptions Block of Uranium.  This block doesn't work with the Immersive Engineering Thermoelectric Generator as a heat source.

Going through the minecraft creative menu, only the blocks of uranium from Mekanism and Immersive Engineering work as applicable heat sources, but there is no way to create either of them.

### Steps to reproduce

Place down a thermoelectric generator and energy storage on top set to input from the generator.
place cold blue Ice on one side and make a uranium block, the only one you can craft in any way is the one from industrial contraptions, for the other side.  Notice that the generator isn't producing energy.

Replace the block of uranium with lava, or switch to creative and pull a block of uranium from immersive engineering and place that, and the generator produces electricity

### Expected behaviour

The block of uranium should act as a heat source for the thermoelectric generator.

**Comment by phit** [comment]
this is still an issue in 1.5.1, might be fixable with a datapack or adding the needed tag to the uranium block from contraptions 
https://github.com/BluSunrize/ImmersiveEngineering/blob/1.18.2/src/generated/resources/data/immersiveengineering/recipes/thermoelectric/uranium.json

**Comment by TheonlyTazz** [comment]
fixed issue, the item has the tag, not the block
