### ISSUE TITLE
[Bug]: Gold Auto-Hammer doesn't hammer compressed blocks

### ISSUE THREAD

**Issue by Nilsen02** [FTBTeam/FTB-Modpack-Issues#831]
### Modpack

FTB OceanBlock

### Modpack version

1.12.0

### Describe the bug

While the Iron Auto-Hammer hammers 1xCompressed Cobblestone into 9x Gravel, the Gold Auto-Hammer only accepts 1x Cobblestone into 1x Gravel ie. making it effectively worse, even though it has a faster progress.

I tested this on Cobblestone, Gravel, Dirt and Sand - having not unlocked the rest yet.

The Diamond Auto-Hammer works as expected, hammering 2xCompressed Cobblestone into 81x Gravel and vice versa.

### Steps to reproduce

1. Place Compressed Cobblestone and Cobblestone into an inventory.
2. Place Gold Auto-Hammer next to it.
3. Watch as the Gold Auto-Hammer only takes regular blocks.

### Expected behaviour

Gold Auto-Hammer should hammer 1xCompressed Cobblestone.

**Comment by Nilsen02** [comment]
EDIT: 
I'm very sorry to have opened this as a bug, as it seems like the Gold Hammer doesn't hammer 1xCompressed Blocks either. 

Having this as a suggestion to make the Gold tier able to Hammer 1xCompressed would be more ideal, as it would make more sense progression wise.

**Comment by Nilsen02** [comment]
Bear with me here, I suck at fully testing something:
Playing around with piping items into the Auto-Hammer vs. using the auto-input of the Auto-Hammer itself shows, that while the Auto-Hammer input is restricted to a certain level of compression (Iron = 1x, Gold = 0x, Diamond = 2x, Netherite = 3x?) you can pipe a higher level of compression into the Auto-Hammer, and it hammers it correctly (Tested 2xCompressed into an Iron Auto-Hammer). I wonder if this is intentional or not?

**Comment by TheonlyTazz** [comment]
Yes, golden hammers are actually to weak to break compressed blocks.
The piping of higher level compressed blocks into the hammer with lower tiered hammers is definitly an issue i adress forward thanks!

**Comment by DinnerBeef** [comment]
This is working as intended. Gold is faster, but I can't do everything.
