### ISSUE TITLE
[Bug]: Passive mobs entity cramming too easily if holding a trackable food item.

### ISSUE THREAD

**Issue by ariosos** [FTBTeam/FTB-Modpack-Issues#832]
### Modpack

Direwolf20 1.18

### Modpack version

1.2.0

### Describe the bug

Passive mobs seem to ignore entity collision, causing them to quickly reach entity cramming when attracted to a favored food item. I'm wondering if this is a side-effect due to something like "AI Improvements" to reduce entity collision checks. If so, I'm not sure what mod is doing this, or what config option is turning off entity collision detection, if that is the cause.

### Steps to reproduce

1 - Make a 9x9 interior pen (fences in an 11x11 perimeter).
2 - Spawn 32 cows (any number higher than 24 will do).
3 - Go to a corner with some wheat.

Also, test this in vanilla. The cows in vanilla obey entity collision rules and is harder for them to cram into one spot. I suspect there's an AI tweak to reduce lag. This is compounded when trying to breed cows, and with each baby born, the parents die.

### Expected behaviour

Passive mobs should respect entity collision rules and not try to path find to the same block.

### Screenshots

32 Cows.
![image](https://user-images.githubusercontent.com/7917753/169915531-84be9185-d232-4f45-8433-05c944f01809.png)

32 Cows trying to reach the same corner.
![image](https://user-images.githubusercontent.com/7917753/169915567-972bb87d-46f1-4072-9a41-e0c51ec8360b.png)

Top-down view - (after entity cramming deaths)
![image](https://user-images.githubusercontent.com/7917753/169915789-450e5744-1825-4081-b6b8-5774c03dcfdc.png)

### Additional information

What's difficult to show in pictures is that the cows are constantly in a loop of trying to get to the corner block, then rubber-banding back to their original spot a block or two away.

**Comment by farigiss** [comment]
The mod WYML (Why You Make Lag) seems to be causing it. Removing it from the pack fixes the issue.
WYML has a feature to "Rate limit entity pushing", which I assume is the culprit.
