### ISSUE TITLE
[Bug]: Making a creative thaumonomicon before completing all the free research quests breaks the quests

### ISSUE THREAD

**Issue by nat212** [FTBTeam/FTB-Modpack-Issues#835]
### Modpack

FTB Interactions

### Modpack version

2.0.9,2.12.0,2.12.1

### Describe the bug

If you create the creative thaumonomicon before completing the free research quests in the quest book (hedging our bets, infuse this, etc). The quests are rendered unable to be completed. If this happens, you can click the checkmark next to each quest, but clicking on the reward immediately marks the quest as incomplete.  This renders the chapter unable to be completed.

### Steps to reproduce

1. Complete what is this sorcery chapter up until I HATE RESEARCH
2. Create and use the creative thaumonomicon
3. Try and complete the free research quests and accept their rewards

### Expected behaviour

The quests get marked as completed, allowing you to complete the chapter.

### Screenshots

![image](https://user-images.githubusercontent.com/42024975/170004844-e7ddf803-a5f4-41d9-87af-6013eebc30b8.png)
![image](https://user-images.githubusercontent.com/42024975/170004917-99624e8b-c77c-4b51-aa39-22f77943dacb.png)

**Comment by Saereth** [comment]
Those quests are marked optional (as they are) and do not impede progress through the pack or quest lines
