### ISSUE TITLE
[Bug]: Loading into the world doesn't start the player on full health

### ISSUE THREAD

**Issue by nat212** [FTBTeam/FTB-Modpack-Issues#836]
### Modpack

FTB Interactions

### Modpack version

2.0.9

### Describe the bug

I have a lot of bonus health, from heart containers, from astral sorcery perks, and from nutrition bonuses. My max health is on the second pink health bar, but if I quit the game and log back in, I get reset down to a few green hearts. I think it's the health from AS that's lost on startup.

### Steps to reproduce

1. Give yourself more health with AS perks, heart canisters, and nutrition bonuses.
2. Heal yourself to max HP
3. Quit the game and log back in.

### Expected behaviour

The player should have full health when logging back in.

### Screenshots

![image](https://user-images.githubusercontent.com/42024975/170005559-b002c680-97c8-4ef4-a27e-b035694d2a01.png)
Max health when fully healed.

![image](https://user-images.githubusercontent.com/42024975/170005775-2923b041-e134-4301-af93-d9ff9c0cf6da.png)
Max health after quitting and restarting the world.

**Comment by nat212** [comment]
Apologies for the overlay on the screenshots, the game paused when I took the screenshots

**Comment by TheonlyTazz** [comment]
I am afraid that this is an issue with Astral Sorcery. HellfirePVP commented on this issue already, this isnt getting resolved, i am sorry. You still have the health, you just have to regen it.
https://github.com/HellFirePvP/AstralSorcery/issues/1166#issuecomment-521430336
