### ISSUE TITLE
[Bug]: no player render in 3rd,1st, person no item render on ground or in hand

### ISSUE THREAD

**Issue by x4element** [FTBTeam/FTB-Modpack-Issues#837]
### Modpack

Direwolf20 1.18.2 

### Modpack version

all versions

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8765207/latest.log)

### Describe the bug

no player render in 3rd,1st, person no item render on ground or in hand, I tried resetting the instance and creating new world it did not fix it.

### Steps to reproduce

literally no clue

### Expected behaviour

player and items being rendered

### Screenshots

1st person holding tinkers book materials and you
https://blockshot.ch/ALaS

3rd person no player render
https://blockshot.ch/Tpms

> Did you add or remove anything in the pack? Please also provide log file
i did add ultiminer but i had to reinstall my instance because the game did not want to start
[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8764969/latest.log)

**Comment by Sunekaer** [comment]
Did you add or remove anything in the pack?
Please also provide log file

**Comment by ixanza** [comment]
I have this happen all the time when I configure any mods configs within the game. Was trying to configure light level overlay and without fail it would produce this behavior. Restarting the client and joining the game immediately after seems to prevent it from happening
