### ISSUE TITLE
[Bug]: Aquatic Entangler prevents world load

### ISSUE THREAD

**Issue by rastrof** [FTBTeam/FTB-Modpack-Issues#841]
### Modpack

FTB presents direwolf20 1.18

### Modpack version

1.2.0

### Log Files

[console.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8772213/console.log)

### Describe the bug

Upon loading the world (singleplayer) I fall through the world. ( having played the pack for a few days )

/kill
/home
/tp ~100 ~
/gamemode creative

All dont work or respond when falling

### Steps to reproduce

Load the world
Fall through

### Expected behaviour

Load normally

### Screenshots

![afbeelding](https://user-images.githubusercontent.com/169951/170289755-ecbdabfb-b5e0-448a-bdc4-81918dbac920.png)

### Additional information

I uploaded the save to my onedrive:
https://1drv.ms/u/s!AoxQsLAOGDTPoynTwujSfE32LDw9?e=ABgI6z

( yes, its called corrupt again, had to restore a backup yesterday because the world kept infinitely loading on IE-retrogen)

**Comment by Kroptik** [comment]
Did you have an Aquatic Entangler in your world? If so, I suggest you check the solution I posted here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/814

**Comment by rastrof** [comment]
On second thought, I'll leave the ticket for the devs to fix the Aquatic Entangler as this is a critical bug.
