### ISSUE TITLE
[Bug]: Tinker Pickaxe mining level not working as expected

### ISSUE THREAD

**Issue by lauchlinmac** [FTBTeam/FTB-Modpack-Issues#845]
### Modpack

Direwolf20 1.18

### Modpack version

1.20

### Describe the bug

I created a pickaxe with bronze and also one with osmium, hovering over iron and copper indicate "Mining Level: Stone", while both pickaxes show "Mining Level: Iron".  The pickaxe does not work on the ore.

### Steps to reproduce

1. create a tinkers pickaxe of level bronze
2. Try and mine

### Expected behaviour

Wrong level of ore mining

### Screenshots

v
![image](https://user-images.githubusercontent.com/8878872/170336838-aa694e52-f27a-46b9-a951-cb8a57cd0b49.png)
![image](https://user-images.githubusercontent.com/8878872/170336891-1c57dc42-db11-4f43-949a-6be3ca3d006f.png)

**Comment by lauchlinmac** [comment]
Extra Info - Issue only seems to be related to Minecraft Ores.  I am able to mine Tin without issue

**Comment by lauchlinmac** [comment]
And some stone
![image](https://user-images.githubusercontent.com/8878872/170396649-955f3b20-990e-4021-9fc1-23904ac432ef.png)
(same pickaxe)

**Comment by quietust** [comment]
Presumably because you made a Pick**adze** instead of a Pick**axe**, it only has a harvest tier of "Gold", so it likely has the same properties as a vanilla Golden Pickaxe which actually has a **lower** mining level than an Iron Pickaxe and is only capable of mining Coal Ore.
