### ISSUE TITLE
[Bug]: ArithmeticException kills Refined Storage network requiring server restart

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#846]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.2.0

### Log Files

[latest.log](https://pste.ch/womajagoxi.md)
[debug.log](https://pste.ch/ikavixulok.md)

### Describe the bug

Whilst building the Reborn Storage multi-block I got the following shortly after placing crafting frame blocks directly below an RS cable connected to a controller:

```
[25May2022 22:15:31.546] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 2290ms or 45 ticks behind
[25May2022 22:26:03.105] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket@17d51c4e, suppressing error
java.lang.ArithmeticException: / by zero
[...stack trace...]
```

Thereafter the RS network in inaccessible without restarting the server, but everything seems to work okay again after a reboot.

I've tried to reproduce this and can't so unsure what repro steps to propose bar placing crafting frame blocks directly underneath an RS cable.

Screenshot [here](https://blockshot.ch/bFN5) of what I'd placed and where and the full stack trace in the linked debug.log.

### Steps to reproduce

N/A

### Expected behaviour

No crash

**Comment by ukmcplyr** [comment]
Nope, so far so good on 1.3.1.

**Comment by Sunekaer** [comment]
Thanks for the update
