### ISSUE TITLE
[Bug]: dedicated server doesn't exit on "stop"

### ISSUE THREAD

**Issue by MacChuck** [FTBTeam/FTB-Modpack-Issues#847]
### Modpack

Direwolf 20 1.18

### Modpack version

1.2.0

### Describe the bug

Linux dedicated server doesn't end the java process when stopped. It sits at the ">" minecraft console after saving, and leaves java running.

### Steps to reproduce

Launch dedicated server.
Wait for it to load up fully.
Issue a stop command in the minecraft console.

### Expected behaviour

Console should close and java should exit upon stop, after save.

### Additional information

Using ctrl+c or ending the process manually after all the save messages seems to have no ill effect. I left the server at the saved and stopped, but not exited state for a few hours and it never exited.

**Comment by Duckgrass** [comment]
Our server is also having this issue. The console shows no issues, but nothing continues after the following message of finishing ender chest unloading.
![image](https://user-images.githubusercontent.com/68453016/170799388-9b91fcdc-779d-4916-8d2c-86c1aca96f2a.png)

**Comment by MacChuck** [comment]
> Our server is also having this issue. The console shows no issues, but nothing continues after the following message of finishing ender chest unloading. ![image](https://user-images.githubusercontent.com/68453016/170799388-9b91fcdc-779d-4916-8d2c-86c1aca96f2a.png)

Yep. I use a custom startup script to run the server in a screen session in linux, so for now my nightly reboot script just waits a minute after sending stop, sends a ^c to the screen, waits 30 seconds, does it again, and that seems to take care of it. Looks like from the tags there's an nod update that may fix it.

**Comment by Raidobw2** [comment]
Try updating FTB Backups 2 manually and see if that works, apparently it should: https://www.curseforge.com/minecraft/mc-mods/ftb-backups-2/files/3805761

To update it you just stop the server and delete the old mod file in the mods folder. Then put the new one in and start the server

**Comment by Duckgrass** [comment]
We dont have any version of FTB Backups installed on our server.

**Comment by DLCIncluded** [comment]
Attempted the fix by @Raidobw2 on my DW201.18 v1.2.0 server that was also experiencing the issue.

Replaced 
ftbbackups2-forge-1.18.2-1.0.5.jar
with
ftbbackups2-forge-1.18.2-1.0.9.jar

And the server no longer hangs on shutdown / restarts. Thank you for the fix, it was getting rather annoying.

**Comment by Duckgrass** [comment]
We just updated the pack to 1.3.0 and installed v1.0.9 of the ftbbackups, but we are still experiencing the same lack of not exiting and server output staying at "Finished Unloading Ender Chest Data".

**Comment by Raidobw2** [comment]
Do you have two versions of ftb backups on the server? That's odd. Try installing it in a separate folder and update the mod manually, then see if it works. If it does, completely replace the mods folder from the "old" server with files from the freshly installed one. If it doesn't work, I don't know what's going on...

**Comment by DLCIncluded** [comment]
I take my previous comment back. We're not out of the woods yet. 

We upgraded to 1.31 of the pack today on our server, so the server is using ftbbackups2 1.0.7.

Upon the scheduled reboot we got to the same point as Duckgrass where it finished loading the chest data.
Ending of that log here: https://pastebin.com/m2tXqASG 

We had to kill the process and start it manually. We are going to try 1.09 as well with pack version 1.3.1 and see if we also get the same point on the scheduled restart.

If it helps, we are using AMP server by cubecoders to manage our servers. We have other 1.18 packs that the restart is working properly on so it appears limited to a mod in this pack, or this pack in general. Hope this helps. Will report back upon our next reboot.

**Comment by DLCIncluded** [comment]
@Duckgrass @MacChuck try updating your ftbbackups2 to v1.0.10
It seems to have resolved the issue, the team over there made quick work and got an update out. Its been running on my server for 24 hours with out an issue with auto restarts every 4 hours.

**Comment by Duckgrass** [comment]
For some reason, our server crashes due to refined storage making a tick take too long for our watchdog. We don't have any version of ftb backups2 installed before or now, so at this point, it might be related to that somehow.

**Comment by DLCIncluded** [comment]
@Sunekaer Apologies for bumping this thread after close, but what pack version has the fix? We recently updated from pack 1.3.1 to 1.4.1 and the issue returned, even with removing FTB backups 2. When stopping / restarting the server it sticks at "Finished Unloading EnderChest Data" and never fully shuts down:
![image](https://user-images.githubusercontent.com/23517228/172888224-bb18fe1e-4c02-490c-809e-1eb85bd28787.png)

**Comment by collatzcoder** [comment]
Same issue here but without the ftb modpack, just some other mods:
![image](https://github.com/user-attachments/assets/4cd1561f-f176-457f-b74d-08d760cfd0f2)
