### ISSUE TITLE
[Bug]: Unable to break graves while at Ocean Monument

### ISSUE THREAD

**Issue by Duckgrass** [FTBTeam/FTB-Modpack-Issues#849]
### Modpack

Direwolf20 1.18

### Modpack version

1.2.0

### Describe the bug

When in proximity to an elder guardian/ocean monument, the player is forced to be unable to break any blocks while all elder guardians are defeated. The issue is that this extends to graves, which means you either need to switch to creative or kill all guardians until you can retrieve any graves in the vicinity. 

### Steps to reproduce

1. Go to an ocean monument.
2. In survival, wait until the text "seems you're approaching an ocean monument...defeat all the Elder Guardians... you'll not be able to break blocks." appears in chat.
3. Die while under the effect mentioned in the chat message.
4. Head back to the grave and try to break the block in survival.

### Expected behaviour

You can break any of your grave while around active ocean monument

### Screenshots

This is the chat message in full for the indication you are unable to break blocks.
![Capture](https://user-images.githubusercontent.com/68453016/170434435-beb0635f-5888-42ed-89e3-da8ccb075fac.PNG)

### Additional information

Obviously, you can kill the guardians to get rid of the issue, but this can easily lead to a frustrating death loop for early-game players which seems very out of place for this style of pack.

**Comment by quietust** [comment]
The inability to break blocks has nothing to do with the chat message - it's merely due to the Mining Fatigue effect inflicted by the Elder Guardians every minute or so. If you bring along a few buckets of Milk, you should be able to cancel the effect and harvest your grave before it gets reapplied.

Actually "fixing" this would likely require switching to a different Gravestone mod which permits harvesting them via right-click (assuming that such a mod is even available for 1.18.2).

**Comment by MacChuck** [comment]
There's a config option for this gravestone mod to switch it from mining it to sneaking on it. No need to switch mods.

In: gravestone-server.toml 
```
#If this is set to true you get your items back into your inventory by sneaking on the grave
sneak_pickup = false
```

**Comment by westfallk** [comment]
> 

There is no mining fatigue. Something is forcing you into a sort of adventure mode where you can't even trigger the block breaking animation.

**Comment by TheonlyTazz** [comment]
Not an Issue, there are ways to kill the Elder Guardians without breaking blocks. If you want this changed, you can do so on your own instance with the suggestion MacChuck posted
