### ISSUE TITLE
[Bug]: ProjectRed/Ultimine dupes redstone logic items

### ISSUE THREAD

**Issue by Matakor** [FTBTeam/FTB-Modpack-Issues#85]
### Modpack

FTB Oceanblock

### Modpack version

1.2.0

### Describe the bug

Placing items from ProjectRed Integration AND Transmission (possibly more) can be duped when mining with ultimine. I'm not sure this is something that can be fixed directly just via the pack, and I have NOT changed config settings for either mod.

This may be a mod interaction bug, but it should be fixable by blacklisting those items for ultimine if that can be done.

### Steps to reproduce

1. Place ProjectRed logic circuits or wires
2. Use ultimine to mine all of them at once
3. receive duped items

### Expected behaviour

Not duped items

### Additional information

should be noted that it's not an exact duplication, as only the items not directly mined are duplicated (most times, it's not exactly the same each time), but I placed 14 redwire and got 27 back :P

**Comment by Raidobw2** [comment]
I'll put this low priority as it's not something i think would break the progression of the modpack. The modpack dev will see if he wants to fix it (blacklist in ultimine if it's worth the time, but there might be other items as you mentioned that do this, probably not a 100% fix either way).

**Comment by Sunekaer** [comment]
Blacklisted all CB Multiparts
