### ISSUE TITLE
[Bug]: Chisel causing issues with Coal Coke Block crafting

### ISSUE THREAD

**Issue by dragonkid828** [FTBTeam/FTB-Modpack-Issues#850]
### Modpack

FTB Revelations

### Modpack version

3.6.0

### Describe the bug

Crafting coal coke (railcraft tested, unsure about Immersive Engineering), and then turning it into a block, and then back to the original causes it to be the IC2 Coal Coke rather than the Immersive Engineering, Thermal Foundation or Railcraft.

Attempted to fix by disabling the recipe (created by Chisel) didn't work, would just fail to execute the script properly.

### Steps to reproduce

1. Create Railcraft Coal Coke
2. Craft into a Coal Coke Block
3. Craft back into Coal Coke, turns into IC2 Coal Coke instead of a unified version of Coal Coke

### Expected behaviour

Should be a unified version of coal coke rather than multiple different kinds

### Additional information

Fix seems to be to disable Coal Coke in the Chisel mod, but it should be possible to fix via CraftTweaker?

**Comment by TheonlyTazz** [comment]
Quick fix for this Issue untill a new update has been pushed:
```
# Unify Coalcoke blocks into unified Coal Coke
recipes.remove(<thermalfoundation:storage_resource:1>);

recipes.addShapeless(<railcraft:fuel_coke>*9,
	[<ore:blockFuelCoke>]
);
```
will be fixed in next version

**Comment by TheonlyTazz** [comment]
I have unified all blocks to uncraft into Immersive Engineering blocks:
https://i.imgur.com/IRfqWkY.gif


if you want to fix this yourself, you can add this to 01_unification.zs

```
# Unify Coalcoke blocks into unified Coal Coke


blockFuelCoke.add(<railcraft:generic:6>);

recipes.removeByRecipeName("chisel:uncraft_blockfuelcoke");
recipes.removeByRecipeName("immersiveengineering:stone_decoration/cokeblock_uncraft");
recipes.removeByRecipeName("thermalfoundation:material_58");
recipes.removeByRecipeName("thermalfoundation:storage_resource_1");

recipes.addShapeless(<immersiveengineering:material:6>*9,
	[<ore:blockFuelCoke>
]);

recipes.addShaped(<immersiveengineering:stone_decoration:3>,
	[
		[<ore:fuelCoke>,<ore:fuelCoke>,<ore:fuelCoke>],
		[<ore:fuelCoke>,<ore:fuelCoke>,<ore:fuelCoke>],
		[<ore:fuelCoke>,<ore:fuelCoke>,<ore:fuelCoke>]
	]
);
```

**Comment by dragonkid828** [comment]
Thank you so much for your prompt response, it's much appreciated! Have a good rest of your weekend!

**Comment by TheonlyTazz** [comment]
I am sorry, i forgot that i added 
`val blockFuelCoke = <ore:blockFuelCoke>;` 
to the variables on top, i will share the latest 01_unification.zs here so you can just replace the current on.
just be sure to rename it from `01_unification.txt` to `01_unification.zs`
this fix will be pushed to the next release of the pack
[01_unification.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8802557/01_unification.txt)
e

**Comment by dragonkid828** [comment]
Thank you so much!
