### ISSUE TITLE
[Bug]: Direwolf 20 1.16 server tag error

### ISSUE THREAD

**Issue by picabo4591** [FTBTeam/FTB-Modpack-Issues#851]
### Modpack

FTB direwolf 20 1.16

### Modpack version

1.16

### Log Files

https://pste.ch/gewemikuwu.css

### Describe the bug

i can launch the server with no problem with the minecraft_server.1.16.5.jar 
but i cant join i always received the server tags error

### Steps to reproduce

1.launch server
2.connect server
3.receive error

### Expected behaviour

you get a error

**Comment by Raidobw2** [comment]
You have to use the start script with the forge jar, that is what you have to do. Using the minecraft_server jar will never work.

If the start script doesn't work, then it's probably that your java updated automatically and now it doesn't work. Some packs use a specific version of java. We have this in the ftb discord for those cases, I also suggest going to the ftb discord for support:

Some modpacks require older versions of Java 8 or 11. Open https://adoptium.net/temurin/archive/ in your browser and select either OpenJDK 8 or OpenJDK 11. You can install those exact versions from the archive:
MC 1.16.5 or less => jdk8u312-b07 from 21st of October 2021.
MC 1.16.5 for performance => jdk-11.0.13+8 from 21st of October 2021.
Servers: uninstall all other versions of Java, fix your path variable or directly reference the path to the java binary if you still get an error. Example: https://discord.com/channels/372448486723158016/560188834592063488/934734172419936277.

**Comment by picabo4591** [comment]
Thank you, it was indeed the version of Java that was causing error.
thank you for the fast and useful reply !

**Comment by Raidobw2** [comment]
No problem, you're welcomed. Enjoy the pack!
