### ISSUE TITLE
[Bug]: Forbidden arcanus issues

### ISSUE THREAD

**Issue by peisach** [FTBTeam/FTB-Modpack-Issues#852]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.2

### Describe the bug

I am trying Forbidden & Arcanus out and I have been finding problems.

1) There is no recipe for the Hephaestus Forge in JEI, so I do not know how to make it.
2) I believe Arcane Crystal Dust is supposed to be able to convert farmland into Magical Farmland, required for planting Golden Orchid Seeds.  It does not.

### Steps to reproduce

1. Create farmland with a hoe
2. Trying using Arcane Crystal Dust to convert the farmland to Magical Farmland

1. Look for recipe on making Haephestus Forge

### Expected behaviour

Find a recipe for the Forge or the farmland to convert

**Comment by Kurotsune77** [comment]
For Hephaestus forge, not entirely sure if you need the "multiblock" for it to work, but you right click smithing table with mundabitur dust, does even JEI support this kinda recipes?

**Comment by Sunekaer** [comment]
https://wiki.valhelsia.net/external-mods/forbidden-and-arcanus/wiki/blocks#hephaestus-forge

**Comment by anigeluk** [comment]
The issue with #2 still exists You cannot right click farmland with arcane crystal dust and cannot plant the golden orchid seed
