### ISSUE TITLE
[Bug]: DeepResonance Tanks Duplicating fluids

### ISSUE THREAD

**Issue by Trizplayz189** [FTBTeam/FTB-Modpack-Issues#853]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.2.0

### Describe the bug

i tried to empty a tank with pipez and when i picked it up and replaced it the fluid was back in the tank and the other tank still has the fluid

### Steps to reproduce

1.place DeepResonance Tank
2.with with lava
3.place another DeepResonance Tank next to it
4.break one of them
5.place down the tank and use pipez ,a bucket or the mekanism tank to empty tank
6.break the empty tank
7.place the broken tank down

### Expected behaviour

the full tank to empty and not contain fluid when moved

**Comment by i2smrt4u** [comment]
I have this same issue. Right-clicking with portable tank also duplicates.

1-Place DR multiblock Tank
2-Fill with lava
3-Break one tank
4-Place away from multiblock
5-Drain
6-Break
7-Repeat 4-6

I filled a 64b Portable Tank twice this way with a DR tank that was stuck at 7350mb

**Comment by Sunekaer** [comment]
Should be fixed, based on what i read in https://github.com/McJtyMods/DeepResonance/issues/304
