### ISSUE TITLE
Reborn Storage Multiblock not working [Bug]: 

### ISSUE THREAD

**Issue by ReptarKing0Zone** [FTBTeam/FTB-Modpack-Issues#855]
### Modpack

Direwolf 20 1.18

### Modpack version

1.2.0

### Describe the bug

Reborn storage multiblock will not work. It says that certain blocks are in the incorrect position even when they are not. I went into creative to see if I could get it to work and I could not. 

### Steps to reproduce

1. load in
2. try to build the mutiblock auto crafting system and try to get it to work.

### Expected behaviour

It should have worked.

**Comment by Raidobw2** [comment]
Hi, could you add a picture of it to help us reproduce it? Thanks in advance!

**Comment by ReptarKing0Zone** [comment]
Was the bug fixed?
