### ISSUE TITLE
Thermal Aquatic Entangler Brakes game [Bug]: 

### ISSUE THREAD

**Issue by ReptarKing0Zone** [FTBTeam/FTB-Modpack-Issues#856]
### Modpack

Direwolf 20 1.18

### Modpack version

1.2.0

### Describe the bug

After placing the aquatic entangler into your world you are not longer able to load in. It just sits at the "100%" loading screen.

### Steps to reproduce

1. Place the aquatic entanger from thermal mod into the water.
2. save and close your game.
3. Try to reload in.

### Expected behaviour

I was hoping to be able to load back into my world.

**Comment by quietust** [comment]
See also #814.

**Comment by Raidobw2** [comment]
Thanks for the report! There's one issue opened at #841, we'll use that one to keep track of the problem. If you manually update the thermal mods you will no longer have that issue. Of course, this will be fixed in the next pack update as well.
