### ISSUE TITLE
[Bug]: mek polonium gas transforming into hydrogen when put into a chemical tank DW20/1.18

### ISSUE THREAD

**Issue by TearForger** [FTBTeam/FTB-Modpack-Issues#857]
### Modpack

Direwolf20 1.18

### Modpack version

1.2.0

### Describe the bug

this one is wierd.

I have a polonium farm and I am trying to store it in a mek chemical tank in prep for starting a fusion reactor.

with a freshly crafted ultimate tank attached to ultimate pressure pipes the tank had hydrogen in it.  there is no way for it to have gotten hydrogen in it.  the nearest hydrogen is 20 blocks away.

So I vented it.  the tank is now empty. and polonium is not entering the tank.  Made a new tank with the same result.

screenshots below.  all mekanism parts.

### Steps to reproduce

nuclear waste into solar neutron output polonium gas to ultimate pressure pipes filled with polonium gas
craft new ultimate chemical tank.  attach to pressure pipes.

hydrogen in tank?  no idea why maybe its supposed to be polonium but there is a logical mixup?

vent tank to clear hydrogen

polonium will not enter tank even when empty.  even with all sides configured for input.

### Expected behaviour

polonium gas should eb stored in chemical tank.

### Screenshots

![gas config](https://user-images.githubusercontent.com/106101692/170800317-0948dd91-03ab-49c3-a226-27ce0226e79b.png)
![why hydrogen](https://user-images.githubusercontent.com/106101692/170800322-2c6dcb9b-2b48-4eb8-b2cc-1e2705c049a8.png)

**Comment by quietust** [comment]
Polonium gas is radioactive, and therefore it is not possible to store it in a chemical tank.

**Comment by TearForger** [comment]
whelp thats a derp.  closing.
