### ISSUE TITLE
[Bug]: Unable to craft Applied Energistics 2 Wireless Booster and the Ender Dust item for it.

### ISSUE THREAD

**Issue by Vessaras** [FTBTeam/FTB-Modpack-Issues#859]
### Modpack

Direwolf20 1.18

### Modpack version

1.2.0

### Describe the bug

The Applied Energistics 2 Wireless Booster Card is unable to be crafted alongside the Ender Dust from Applied Energistics 2 and Thermal (according to FEI). Using FTB Industrial Contraptions Ender Pearl Dust doesn't work with it either.

### Steps to reproduce

1. Open Inventory
2. Use FEI to search for Wireless Booster in the Applied Energistics 2 mod
3. Click on Wireless Booster
4. In the recipe window left click on the Ender Dust/Ender Pearl Dust component.
5. Doesn't respond. Unable to craft it.
6. Search for Ender Pearl Dust under FTB Industrial Contraptions
7. Left click to get recipe. Is available.
8. Unable to use the Ender Pearl Dust with the Applied Energistics 2 Wireless Booster Recipe

### Expected behaviour

Expect Ender Dust/Ender Pearl Dust to be compatible across mods. Expect more mods capable of crafting it such as Mekanism. Largely just expect recipe to be craftable. (Sorry I am tired)

**Comment by Vessaras** [comment]
Ah sorry someone else has already reported this bug

**Comment by Raidobw2** [comment]
Yup this is fixed in development at #806. Thanks for reporting anyways! I'll go ahead and close this since we'll use the other issue to track the problem
