### ISSUE TITLE
[Bug]: Unable to create Cherrywood Slabs recipe conflict creates cherrywood stairs instead

### ISSUE THREAD

**Issue by Vessaras** [FTBTeam/FTB-Modpack-Issues#860]
### Modpack

Direwolf20 1.18

### Modpack version

1.2.0

### Describe the bug

When attempting to create Cherrywood Slabs it creates stairs instead

### Steps to reproduce

Add 3 Cherrywood Planks in a horiztonal line on a crafting grid. Gives stairs instead of slabs

### Expected behaviour

Expect to craft slabs not stairs

**Comment by Sunekaer** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/903
