### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CurlyQ1222** [FTBTeam/FTB-Modpack-Issues#864]
### Modpack

FTB Presents Stoneblock 2

### Modpack version

1.22.0

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8791747/latest.log)

### Describe the bug

Trying to load Stoneblock 2 from FTB app, does not get past the finishing up stage. The top under the loading bar says "finishing up // mantle" and the log below ended with
 [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: Finished Aspect ItemStack Thread.
It will stay on this line for many minutes.

My partner has the exact same issue on his machine. We loaded everything fine yesterday. 

### Steps to reproduce

1. open FTB app
2. launch Stoneblock 2 version 1.22.0
3. watch?

### Expected behaviour

the modpack to finish loading and the game launches

### Additional information

I can provide the entire log or screenshots if you need them, just ask. Thank you!

**Comment by Raidobw2** [comment]
Hmm I've seen this problem once I think but couldn't find out why it was acting like that. In the FTB App you can click Versions on the StoneBlock 2 page and then select another version. Click "Downgrade". Once it finished downgrading, update again. This will basically repair the install.

You can also try turning off antivirus/VPN to see if that's the issue, if you have any.

Then play it, and let me know if it's working or not

**Comment by CurlyQ1222** [comment]
Apologies, I meant to update this last night.
I opened my laptop later and stoneblock was loaded. When I went back to the
FTB app a screen popped up talking about the new app update. STB2 loaded
just fine.

So I guess it was a launcher version issue or it was in the middle of
updating when we were trying to launch.

Thanks!

**Comment by Raidobw2** [comment]
Ahh I understand. It could possibly have been that App update. I'll keep it in mind for other people. Glad you managed to open the game! I'll go ahead and close this. Enjoy the modpack!
