### ISSUE TITLE
[Bug]: Zinc cannot be processed by pulverizer.

### ISSUE THREAD

**Issue by NotPiffany** [FTBTeam/FTB-Modpack-Issues#865]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.3.0

### Describe the bug

Raw zinc can't be processed in a Thermal Dynamics pulverizer the way that other raw metals can be. Is this intentional? It can be processed by other methods, so leaving this one out seems weird.

### Steps to reproduce

1. Take raw zinc.
2. Try to put it into a pulverizer.
3. It won't go in.

### Expected behaviour

I expected the pulverizer to break raw zinc into dust, with a 33% possibility of getting a second dust.

**Comment by quietust** [comment]
There is no "zinc dust" item into which the raw ore could be pulverized. The same applies to Cobalt and Elementium.

**Comment by NotPiffany** [comment]
Fair. It could be turned into the Create crushed zinc ore, though.
