### ISSUE TITLE
[Bug]: Texture Errors on ALL FTB Modpacks, client & Server

### ISSUE THREAD

**Issue by mithradates0146** [FTBTeam/FTB-Modpack-Issues#867]
### Modpack

FTB Tech World 2

### Modpack version

1.1.6

### Describe the bug

On both single player and multiplayer Minecraft (1.6.4) the textures glitch when attempting to play.  This occurs with any other Minecraft mod & vanilla when launched through FTB. The worst texture glitches manifest when placing blocks. 

![Color Errors](https://user-images.githubusercontent.com/106461056/170852500-8f209917-019d-483d-b488-df41d8cc8998.png)
![menu error](https://user-images.githubusercontent.com/106461056/170852502-0faba39c-ed9c-45eb-bda8-0a941d5daed2.png)
![Mob error](https://user-images.githubusercontent.com/106461056/170852503-c823a362-fa8a-4adb-ab97-5a0868d8743d.png)
![Texture error](https://user-images.githubusercontent.com/106461056/170852504-bcfeb2c1-b282-4e3a-af89-4c48920ac349.png)

### Steps to reproduce

1. Launch Minecraft through FTB
2. Observe minor textural glitches within hot bar and mobs
3. Place blocks. 
4. observe severe textural glitches.

### Expected behaviour

proper texture renderings

### Screenshots

![Color Errors](https://user-images.githubusercontent.com/106461056/170852608-f8f84457-e0b1-4b6c-ae51-bf95c5be4813.png)
![menu error](https://user-images.githubusercontent.com/106461056/170852609-3a91e307-6b73-4a6f-bc0c-8546caa1ba76.png)
![Mob error](https://user-images.githubusercontent.com/106461056/170852610-5905ab94-dae8-478e-8506-1d6aa5c7c9dd.png)
![Texture error](https://user-images.githubusercontent.com/106461056/170852611-91801c96-641c-47bd-b8c2-49e15103bfaa.png)

**Comment by Raidobw2** [comment]
Hello, which GPU is being used in your Task Manager when playing Minecraft? I've seen similar problems and people had integrated graphics as well as a dedicated video card (Nvidia, AMD) in their laptops. The solution to that is to go in Nvidia/Radeon software and select the right GPU to use for Java, which is the program Minecraft runs on.
Here's an explanation on how to check that with Nvidia Control Panel. Simply type "Nvidia control" on your Windows button and you'll see it.
> Open the Nvidia Control Panel and click "Manage 3D settings" (at the left). Then click "Program settings" in the tabs at the right. Select the program you want to change the used graphics card for, such as Java, then click the dropdown "preferred graphics processor" and choose your Nvidia GPU.

**Comment by manmaed** [comment]
This i an old mod pack and is unlikely to get updated added @Raidobw2 if he gets time
