### ISSUE TITLE
[Bug]: Direwolf20 issues with Hexcasting: Won't load properly

### ISSUE THREAD

**Issue by Master-Guy** [FTBTeam/FTB-Modpack-Issues#868]
### Modpack

Direwolf20 - HexCasting

### Modpack version

1.3.0

### Log Files

https://pastebin.com/uLXP5AJb

### Describe the bug

Just updated my Direwolf20 1.18.2 installation from 1.2.0 to 1.3.0, and after joining the server I got a Hex Notebook. The bottom right gives a Loading error:

```
Error building entry hexcasting:greatwork/directrix
Error while loading entry hexcasting:greatwork/directrix page 3
Unknown entity id:
```

### Steps to reproduce

Update Direwolf20 server from 1.2.0 to 1.3.0

### Expected behaviour

No errors shown ingame

### Screenshots

![image](https://user-images.githubusercontent.com/566429/170856825-5f75e3cd-b587-4f5a-834f-e71eed916aa8.png)

**Comment by Xverion** [comment]
Same for me but it seems to be a error with every single Patchouli book(including the lexical Botania)

**Comment by Xverion** [comment]
1.3.1 Seems to have fixed it!
