### ISSUE TITLE
[Bug]: Integrated Dynamics + Mekanism allows infinite ore duplication

### ISSUE THREAD

**Issue by quietust** [FTBTeam/FTB-Modpack-Issues#871]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.3.1

### Describe the bug

The Mechanical Squeezer from Integrated Dynamics can currently be used to convert silk-touched ore blocks into 12 raw ore chunks (8 + 2 + 2, all with 100% success), and the Mekanism Combiner can be used to turn 8 of those raw ore chunks (and some cobblestone or deepslate) into a silk-touched ore.

This works with iron, gold, tin, lead, uranium, and osmium - with just 100 RF/t of power production, some item pipes, and a cobblestone generator, any of these metals can be multiplied infinitely once you obtain at least 8 raw chunks.

### Steps to reproduce

1. Place a Mechanical Squeezer and provide it with power.
2. Place a Mekanism Combiner and provide it with power and cobblestone.
3. Obtain an Ore block for Iron, Gold, Tin, Lead, Uranium, or Osmium
4. Place the ore block in the Mechanical Squeezer and receive 12 raw ore chunks.
5. Place 8 of the raw ore chunks in the Combiner and receive another ore block.
6. Smelt the other 4 raw ore chunks into ingots.
7. Repeat steps 4-6 as necesary.
8. Profit.

### Expected behaviour

It shouldn't be possible to infinitely duplicate ores this way

### Additional information

The Mechanical Squeezer ore recipes are listed as producing three outputs: one stack of 8 with 100% chance, one stack of 2 with 100% chance, and another stack of 2 with 100% chance. By comparison, most of the other recipes have the second outputs at only 50% chance.

The Mechanical Squeezer also gives 12x ore multiplication on Aluminum, Zinc, and Cobalt, but no loop is possible with those because they cannot be crafted back into ore blocks.

The normal Squeezer produces 8 chunks from various ores (4 with 100% chance, 2 with 100% chance, and 2 more with 100% chance). This is also significantly overpowered (given that Fortune III only gives 1-4), but it does not result in a loop.

Please don't tell Soaryn.

**Comment by quietust** [comment]
The secondary/tertiary outputs from the Squeezer having a 100% chance appears to be due to the logic in `kubejs/server_scripts/unify.js` - if I disable the logic for one metal, its non-primary outputs drop to a 50% chance.

Presumably, this is a separate bug in the KubeJS `recipes.replaceOutput(tag, item)` logic.

**Comment by quietust** [comment]
Several people on Direwolf20's Discord server have reported that in pack version 1.2.0 and earlier, the Mechanical Squeezer only gave 1 (100%) + 1 (50%) + 1 (50%) raw chunks when processing various types of ores.

None of the KubeJS script modifications between 1.2.0 and 1.3.0 look like they should have had any effect on these recipes, so it's possible that one of the other mod additions/updates is responsible for this change in behavior.

**Comment by MacChuck** [comment]
Tested in 1.2.0 and 1.3.1. Issue is not present in 1.2.0, so a change in the update caused this.
1.2.0: iron ore in a mechanical squeezer outputs 1-3 raw iron.
1.3.1: iron ore in a mechanical squeezer outputs 12 raw iron.

**Comment by quietust** [comment]
It would appear that there was a bug in KubeJS version 1802.5.2 build 425 that caused recipe ingredient substitutions (as performed by `kubejs/server_scripts/unify.js`) to reset the quantity to 1.

Pack version 1.3.0 updated KubeJS to version 1802.5.3 build 444 which fixed that problem but introduced the above-mentioned bug of resetting the output chance to 100%.

**Comment by quietust** [comment]
I just checked the above-linked IntegratedDynamics issue, and it appears that they've "fixed" this by reducing ore yields as follows:

Manual Squeezer:
* Copper: 4 (100%) + 2 (50%) + 2 (50%), exactly the same as before (which is fine, because copper should be higher)
* All other metals: 2 (100%) + 1 (75%)

Mechanical Squeezer
* Copper: 8 (100%) + 2 (50%) + 2 (25%), slightly less than before but still okay (see above)
* Iron: 3 (100%) + 1 (50%) + 1 (50%), averaging at 4x
* All other metals: 3 (100%) + 2 (50%) + 2 (50%), averaging at 5x

Thus, this pack might still want to reduce them further in order to bring them in line with the other mods - since the Squeezer gives raw ore chunks, it would make sense to balance it against the yields from Fortune III (which gives 2-20 chunks [avg 7.7] from Copper and 1-4 chunks [avg 2.2] from everything else).

**Comment by TheonlyTazz** [comment]
fixed in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/881#issuecomment-1158725287
