### ISSUE TITLE
[Bug]: Unstable drum dupe

### ISSUE THREAD

**Issue by CaptIChaos** [FTBTeam/FTB-Modpack-Issues#872]
### Modpack

FTB OceanBlock

### Modpack version

1.12.0

### Describe the bug

 Using a mekanism cardboard box on an unstable drum causes the drum to be duplicated.

### Steps to reproduce

1 Make Unstable Drum and a cardboard box
2 Right click Cardboard box on an Unstable Drum placed in the world
3 The box Goes on the Drum and a Drum a new Drum is dropped
3 The Drum in the box is still there and you have a brand new one

### Expected behaviour

There should be no item dropped when the box is placed on the drum

### Additional information

Further testing has shown that this is true for all drum types not just Unstable Drum

**Comment by TheonlyTazz** [comment]
Thank you for mentioning this issue, i have forwarded it to the MiniUtilities issue Tracker.
If they cannot resolve this Issue, we will disable MiniUtilities blocks from being picked up with the Cardboardbox
