### ISSUE TITLE
[Bug]: Refined Storage and Functional Storage issues

### ISSUE THREAD

**Issue by Sabster** [FTBTeam/FTB-Modpack-Issues#873]
### Modpack

FTB Presents Direwolf20

### Modpack version

1.3.1

### Log Files

I don't know which log to upload - so let me know if you do need it.

### Describe the bug

I took a drawer (functional storage) and connected it to a controller) - when the drawer is locked, you cannot add Immersive Engineering stuff (Hemp in this case) to it (or FTB Industrial Contraptions - specifically silicon)

You also can't double click the controller with the silicon or the hemp like you can with normal items...

And since the controller isn't recognizing it, Refined Storage can't see it.

### Steps to reproduce

Build a controller and attach it to a drawer
Put some hemp in the drawer - double click the controller with the hemp, and it will not add to the drawer

This seems to work fine with normal items (ingots, glass, etc...)

### Expected behaviour

It should add the item to the drawer

### Screenshots

![2022-05-29_18 41 50](https://user-images.githubusercontent.com/5185451/170902329-0e65a9ac-4834-45de-90fb-36abfb6845c5.png)
![2022-05-29_18 41 55](https://user-images.githubusercontent.com/5185451/170902330-d79e4f96-1fd4-4d19-b92e-ff4894a87878.png)

### Additional information

I can't tell exactly where the bug is, but suspect it's Functional Storage's issue....

**Comment by Sabster** [comment]
In the picture above, you'll see all the ores and glass are showing in Refined Storage - the Hemp and the Silicon (which are clearly in screen #1) are not present...

**Comment by Sabster** [comment]
Another update:  If you put the items that can't be seen by the controller into a compacting drawer, it starts working...  Strangely Spruce Logs were also buggy...

**Comment by TheonlyTazz** [comment]
![javaw_9BVRF3tS0I](https://user-images.githubusercontent.com/3908847/171109951-f89ed808-61b1-44fc-9866-8a5624f7a1a4.gif)
I could not replicate this bug with Hemp, be sure to have the drawers linked to the drawer controller.
Be sure to set the item before you lock it, because it does seem that locking it while empty prevents any  item to be inserted.

**Comment by Sabster** [comment]
They are - if it matters; I am using spruce drawers....

**Comment by Sabster** [comment]
Yup, works with oak - try it with spruce drawers and see if you can replicate it  :)

**Comment by phit** [comment]
I'm seeing similar weird behavior with AE2, sometimes inserting or extracting items manually from the drawer makes the drawer content show up in the terminal, this happens both when using the drawer controller and drawer directly.

**Comment by TheonlyTazz** [comment]
I havent had this issue since the latest 1.9.1 

please try again, and if it does happen again, feel free to reopen or make a new issue
