### ISSUE TITLE
[Bug]: Some recipes only accepting vanilla Chests.

### ISSUE THREAD

**Issue by Jared87** [FTBTeam/FTB-Modpack-Issues#876]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.3.1

### Describe the bug

Some recipes, mainly from RFTools (e.g. the Knowledge Holder), are requiring the vanilla chest, but this is only craftable by non valilla wood etc. from Quark, Forbidden & Arcanus, Tinkers Construct, Ars Nouveau and Botania.

Maybe the recipes only accepting the vanilla chest should accept the Quark chests. 

### Steps to reproduce

Try to craft an RFToolsDimensions Knowledge Holder with an Quark chest.

### Expected behaviour

Any chest could be used.

**Comment by quietust** [comment]
It should be possible to convert Quark Chests into vanilla Chests by placing them in any crafting grid.
