### ISSUE TITLE
[Bug]: When launching pack doesn't load 

### ISSUE THREAD

**Issue by Caleb1234567890** [FTBTeam/FTB-Modpack-Issues#88]
### Modpack

Stoneblock 2

### Modpack version

1.21.1

### Describe the bug

Load into the Minecraft launcher and says play demo try to play and doesn't work 
Why is it a demo version have tried the other available versions does the same thing 
And was playing on curse forge with the mod pack it crashed due to Dank Null and CodeChicken Lib colliding spoke to someone about it and they said have to play on the FTB launcher due to it being the most updated version of the pack, wanting to move files from curse forge to FTB launcher
  

### Steps to reproduce

go onto FTB launcher find pack and press play 
takes to Minecraft launcher and says play demo at own risk 
click demo and soon after crashes  

### Expected behaviour

the pack to work correctly due to it being the most updated version of the pack

### Screenshots

![FTB](https://user-images.githubusercontent.com/91944767/135991041-36e622ec-ad48-4de1-b266-c0065479ba70.PNG)
![Demo](https://user-images.githubusercontent.com/91944767/135991047-469113ea-dda5-49f6-8dd7-7c5ac574008d.PNG)
![minecraft crash](https://user-images.githubusercontent.com/91944767/135991080-d767b4d1-649e-4c63-bdac-8eb637e9d2c5.PNG)

### Additional information

don't know much in terms of programing 
just want a fix not sure why this is happening 

thank you

**Comment by Caleb1234567890** [comment]
bottom photo is the crash from Curse Forge

**Comment by MichaelHillcox** [comment]
You must own and be signed into the Minecraft Launcher to use Minecraft / Modded Minecraft mod packs on FTB App

**Comment by Raidobw2** [comment]
@Caleb1234567890 MichaelHillcox is right. You must own Minecraft. You can sign in with your account in the top left corner in the Minecraft Launcher.
Please let us know when you've done so, and then launch the modpack.

**Comment by Caleb1234567890** [comment]
just launched pack and transferred files from curse forge over to FTB launcher went all good until I tried to launch the world. this came up when i did it 
![MInecraft 1](https://user-images.githubusercontent.com/91944767/136166338-561e64cd-11a1-41cb-ae14-35ecc471df4f.PNG)

have tried a old world that is new with nothing done to it as well 
Wondering if its from updates or a potential problem

**Comment by Caleb1234567890** [comment]
hello again everything seems to be working thank you both and enjoy
