### ISSUE TITLE
[Bug]: Deep Resonance Lens doesnt have a crafting recipe

### ISSUE THREAD

**Issue by TheDragonicSlayer** [FTBTeam/FTB-Modpack-Issues#880]
### Modpack

DireWolf20 1.18

### Modpack version

1.3.1

### Describe the bug

The title is pretty self explanatory

### Steps to reproduce

1) Type @deepresonance lens in JEI
2) Left click on the lens or press R while hovering over it

### Expected behaviour

It should show a recipe for the lens to be crafted

**Comment by tantalum8516** [comment]
If you attempt to use the laser without the laser lens it crashes everything. Server and PC.
