### ISSUE TITLE
[Bug]: InDy Mechanical Squeezer Recipies Interact Explosively with Other Ore Duplication, Leading to Massive Ratios

### ISSUE THREAD

**Issue by KirinDave** [FTBTeam/FTB-Modpack-Issues#881]
### Modpack

FTB Direwolf20

### Modpack version

1.3.1

### Describe the bug

Currently the Mechanical Squeezer, when given a silk touched ore, has a 100% chance of giving 12x ore yield. This is a massive ratio to award from a single block that takes less than 20rf/t. But even worse, this system outputs raw ore, which can then be processed further by other mods. 

Part of this problem has been reported in #871, where InDy + Mekanism can lead to infinite ore duplication. But even if that loop is not abused, you can interact directly with the Mekanism pipeline to get at least 32x processing. Even a modest power gen (~150rf/t) and mid-tier upgraded Thermal expansion machines (i.e., an electrum upgrade and 2 secondary boosters) can yield 24x ore output for a system that runs off the output of one upgraded Stirling Dynamo, for nearly all ores.

This degree of interaction essentially ruins the design space for ore processing. You do this, or you don't do it at all. It's early game and very easy to make and power, so there's no reason to do anything else but this. 

I've recommended a few fixes below to address both this problem and #871

### Steps to reproduce

1. Create a mechanical squeezer
2. Acquire silk touch either via boss drops or tinkers construct
3. Enjoy 12x ore processing off a single dynamo and machine.

### Expected behaviour

The Mechanical Squeezer *should* be a way to make Silk Touch and Fortune III equivalent.

### Additional information

I have 2 recommendations for how to fix this and #871.

Firstly, using KubeJS, substitute all raw ore outputs for their dust equivalents, not their raw ore equivalents. This immediately reduces interaction and clears #871 with only a handful of lines of KubeJS. This still means that the squeezer is the best ore processor in the modpack, but it's not as explosive nor does it admit ore duplication loops.

The second option is more involved, but not difficult. You could remove the existing squeezer recipes and instead turn them into reliable doubling recipes. Doubling with silk touch is still very doable "early" in the progression of the pack and is still very good, but no longer has overwhelming explosive results, and Fortune III + Processing will still yield competitive results (and superior results for gems).

**Comment by Manaisle** [comment]
Hello, I have no Idea if people like me posting code here, but I have played around a bit, and the following KubeJS script works for me. It is pretty much your second option. It just takes the recipies with raw ore output form the squeezers and changes the outputs.

	onEvent("recipes", (event) => {
		event.forEachRecipeAsync({type: "integrateddynamics:squeezer"}, recipe => {
			if (recipe.hasOutput({tag: "forge:raw_materials"}, false)) {
				let newOutputItem = recipe.outputItems.get(0).withCount(2).withChance(1.0);
				recipe.outputItems.clear();
				recipe.outputItems.add(newOutputItem);
			}
		});
	
		event.forEachRecipeAsync({type: "integrateddynamics:mechanical_squeezer"}, recipe => {
			if (recipe.hasOutput({tag: "forge:raw_materials"}, false)) {
				let newOutputItem = recipe.outputItems.get(0).withCount(2).withChance(1.0);
				recipe.outputItems.clear();
				recipe.outputItems.add(newOutputItem);
			}
		});
	});

As mentioned in #871, somehow, changing the chance does nothing, it always gets set to 100%. But the amount works luckily.
Also I'm no developer or anything, so don't expect this to be optimal.

**Comment by TheonlyTazz** [comment]
> Hello, I have no Idea if people like me posting code here, but I have played around a bit, and the following KubeJS script works for me. It is pretty much your second option. It just takes the recipies with raw ore output form the squeezers and changes the outputs.
> 
> ```
> onEvent("recipes", (event) => {
> 	event.forEachRecipeAsync({type: "integrateddynamics:squeezer"}, recipe => {
> 		if (recipe.hasOutput({tag: "forge:raw_materials"}, false)) {
> 			let newOutputItem = recipe.outputItems.get(0).withCount(2).withChance(1.0);
> 			recipe.outputItems.clear();
> 			recipe.outputItems.add(newOutputItem);
> 		}
> 	});
> 
> 	event.forEachRecipeAsync({type: "integrateddynamics:mechanical_squeezer"}, recipe => {
> 		if (recipe.hasOutput({tag: "forge:raw_materials"}, false)) {
> 			let newOutputItem = recipe.outputItems.get(0).withCount(2).withChance(1.0);
> 			recipe.outputItems.clear();
> 			recipe.outputItems.add(newOutputItem);
> 		}
> 	});
> });
> ```
> 
> As mentioned in #871, somehow, changing the chance does nothing, it always gets set to 100%. But the amount works luckily. Also I'm no developer or anything, so don't expect this to be optimal.

thanks alot, i have implented this into our test build, and we shall ship this in our next version.
