### ISSUE TITLE
[Suggestion]: Allow for crafting of an Akashic Tome preloaded with most or all available books

### ISSUE THREAD

**Issue by HunterGiannini** [FTBTeam/FTB-Modpack-Issues#883]
### Modpack

FTB Presents Direwolf20 1.18

### Is your suggestion related to a problem? Please describe.

I have noticed in this pack that, unlike in the past, a decent amount of the guidebooks in the game are showing up in JEI as being from Patchouli rather than from the mod that they document. While this isn't necessarily a problem if you know what to search for, a player newer to modded Minecraft may have a difficult time finding in-game documentation for. For example, Pneumaticraft: Reloaded, as they may not know that it is shortened to PNC:R for its manual, or that the neat DeepResonance crystal they found is actually considered a part of RFTools and has documentation in its book.

Furthermore, I think that giving players access to the various guidebooks would allow players to get a better understanding of what experiences the modpack has to offer them, especially in a modpack such as this with a large variety and no quest system to guide them.

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/177321591-04c64536-2d2e-4ee3-929c-d5b87ac32223.png)
added this to starteritems
