### ISSUE TITLE
[Bug]: [Bug]: Death by Brown Gold. [World crash bug!] Just by looking at them.

### ISSUE THREAD

**Issue by NJM1564** [FTBTeam/FTB-Modpack-Issues#884]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.3.1

### Log Files

https://pastebin.com/CtzMCEPT

### Describe the bug

Seed: -457391360
Loc: Nether 426,65,1029

Attempt to break nether coffee from farmers respite with shears causes crash.
Correction: Just looking at them is causing it!!!
Restarting the world crashes instantly.
Had to use NBT exit to warp to a different location to get in.

### Steps to reproduce

Loc: Nether around 426,65,1029
Look at Coffee. World crashes.

### Expected behaviour

Not killing the world!

**Comment by Sunekaer** [comment]
What changes have you made to the pack?

**Comment by NJM1564** [comment]
Added: bonsaitrees3-3.1.0, EverlastingAbilities-1.18.2-1.7.3, ExtraStorage-1.18.2-2.1.0, ftb-hide, ftb-progress, libnonymous-2.1.0, RSInfinityBooster-1.18.2-2.1+16, universalgrid-1.18.2-1.0321

**Comment by TheonlyTazz** [comment]
could not reproduce this issue
