### ISSUE TITLE
[Bug]: Unable to insert Silicon on to Refined Storage System

### ISSUE THREAD

**Issue by XikoCat** [FTBTeam/FTB-Modpack-Issues#886]
### Modpack

FTB Direwolf 20 1.18

### Modpack version

1.3.1

### Describe the bug

Silicon (from FTB Industrial Contraptions) is not able to enter a Refined Storage system.

### Steps to reproduce

1. Have a simple Refined Storage system. (Crafting) Grid, Controller receiving energy, Disk Drive and any Storage Disks that aren't full inside it.
2. Attempt inserting the Silicon from Industrial Contraptions on to the RS system.
3. Be disappointed

Tried:
- Shift + click from inventory;
- drag and drop;
- placing on crafting table part of the Crafting Grid and then pressing the clear button.

### Expected behavior

Silicon should be allowed to enter the RS system

### Additional information

- Disks have space, only 1 disk is full 7 are empty.
- RS Controller is full with and is receiving more energy than spending.

**Comment by Sunekaer** [comment]
I'm not able to recreate this issue.
Do you already have silicon in the system on the full disk?
Are there any other items you cant insert?

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/174274090-1937db0e-a8f4-4eab-bda8-0e2142301632.png)
cannot reproduce in 1.5.1, if this Issue still occurs for you, please reopen this issue or open a new issue

**Comment by XikoCat** [comment]
Just tested again, and it's still happening to me on 1.5.1
