### ISSUE TITLE
[Bug]: Create Mod, Mechanical Press can't produce Iron Sheets

### ISSUE THREAD

**Issue by ilbeyataberkcan** [FTBTeam/FTB-Modpack-Issues#888]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.3.1

### Describe the bug

I wanted to produce iron sheets using Create Contruptions. But I can't see the recipe in JEI and can't produce them.

However I was able to produce Gold Sheets with Mechanical Press 

It appears in the recipes of other blocks. But when I search it in JEI it doesn't appear.

### Steps to reproduce

Put an Iron into Depot of Create Mod that has a Mechanical Press Above it.
Or look at JEI for the recipe for Iron Sheets of Create Mod/

### Expected behaviour

It should press the Iron Ingots into Iron Sheets as it does with Gold Ingots

### Screenshots

![2022-06-02_19 51 41](https://user-images.githubusercontent.com/32396853/171683029-86e5ad1c-f016-4f56-b282-6d9b2ff5db3a.png)

**Comment by Sunekaer** [comment]
Hi
What do you need the sheet for?
You should be able to use an iron plate for what your trying to make

**Comment by TheonlyTazz** [comment]
you can make iron plates (which are our unified version for all plates) with iron ingots and the mechanical press

**Comment by ilbeyataberkcan** [comment]
I had a problem with FTB Industrial Contruptions mod. I disabled it to play the game. Apparently that was the problem. 

Thank you for your tip.

**Comment by zckrii** [comment]
Hi, if you're using KubeJS it'll interfere with recipes, some modpacks use kubejs to create compatibility with other mods, finding pressing.js in kubejs/server_scripts/reciipes and adjusting it in java will fix this, or try deleting it.
