### ISSUE TITLE
[Suggestion]: Mac server files

### ISSUE THREAD

**Issue by Kadamitas** [FTBTeam/FTB-Modpack-Issues#889]
### Modpack

FTB Website

### Is your suggestion related to a problem? Please describe.

There is no section on how to run these files nor an intuitive mac program to run these. I didn't even know what type of file this was since it wasn't a shell script, a java class, just a bunch of unreadable code.

I had to look around for a good bit to find how to actually run the mac server files.

### Mod suggestion

https://www.feed-the-beast.com/modpack/79_ftb_presents_direwolf20_1_16/server-files

Add like a little pop-up or question mark next to the mac server files that say you need to in terminal chmod +x them, and run them. 
Or change these to a shell script.

**Comment by Raidobw2** [comment]
We can look into adding info to the FTB Website, for now a procedure is available at https://go.ftb.team/create-a-server

**Comment by Gaz492** [comment]
Updated guide https://docs.feed-the-beast.com/docs/support/Guides/create-a-server
