### ISSUE TITLE
[Bug]: RFTools Dimension Builder crash

### ISSUE THREAD

**Issue by Trinknix** [FTBTeam/FTB-Modpack-Issues#890]
### Modpack

Direwolf20 1.18

### Modpack version

1.3.1

### Log Files

[crash-2022-06-03_10.46.20-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8831030/crash-2022-06-03_10.46.20-server.txt)

### Describe the bug

Creating bigger dimensions causes the client/server to crash. Ive tried it with different dimlets, but I believe its the amount.
1-3 Dimlets usually seem to work properly, but anything above crashes.
After restarting the game, the dimension is created and can be used. Its just the initial creation.

In Singleplayer my client crashes and the game closes.
In Multiplayer the server crashes, but the game stays open.

I have seen other players having the same issue on the discord server.

### Steps to reproduce

1. Get a **Dimension Builder** and power it with any power cell (I used Mekanism's **Creative Energy Cube**)
2. Create a dimension in the **Enscriber**
3. Place the dimension tab in the **Dimension Builder**
4. At 99%, the game crashes

### Expected behaviour

The client not crashing

### Screenshots

Here is a video of what I did in singleplayer:
https://youtu.be/1eqZaGpzFJw

### Additional information

Best way to contact me is via discord: 
Trinknix#9647 
on the official FTB server

**Comment by TheonlyTazz** [comment]
Can you retry this on the latest 1.5.1 Version, we have updated all RFTools mods and was able to create my own custom dimension without any issue

**Comment by Trinknix** [comment]
Tried it on 1.5.1, seems to work now ^^
