### ISSUE TITLE
[Bug]: Random game crash at mining world

### ISSUE THREAD

**Issue by tuntematonjr** [FTBTeam/FTB-Modpack-Issues#891]
### Modpack

Direwolf 1.18

### Modpack version

1.3.1

### Log Files

https://gist.github.com/tuntematonjr/3890666f9bef0aa59f31eeffa31975b5

### Describe the bug

i was just randomly mining with mining gadged laser at Mining World from just another mining dimension and game crashed.

### Steps to reproduce

not sure

### Expected behaviour

Not to crash

**Comment by TheonlyTazz** [comment]
can you try to replicate this on the latest 1.5.1 Version?
