### ISSUE TITLE
[Bug]: DeepResonance Smelter Does Not Export to Tank Above

### ISSUE THREAD

**Issue by i2smrt4u** [FTBTeam/FTB-Modpack-Issues#892]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.3.1?

### Describe the bug

When placing a multiblock DR tank ontop of a powered DR Smelter on top of a lava multiblock DR tank, the smelter did not export 12 out 12 blocks of Resonating Ore that were input, but did play the GUI animation. The smelter refused to accept more than those 12 blocks. Tank is empty, fluid could not be drained, when broken the mouseover displays as empty.

### Steps to reproduce

1-Create Lave/Smelter/Output setup
2-Input 12 blocks of Resonating Ore
3-No fluid will be output

### Expected behaviour

Tank above would fill with 12*200mb of liquid

### Screenshots

![tank](https://user-images.githubusercontent.com/106843452/171956782-4c9ec1fc-186d-4088-8d82-817fc2dc18a9.png)

### Additional information

-DR Smelter does not have a JEI recipe for Resonating Ore. Possibly related?

**Comment by Morelyn** [comment]
if thats your lava tank below the smelter, unfortunately the issue is user error... you need a specific amount of lava under the smelter for correct operation, you need to limit the tank to about 8 or 9 buckets.

**Comment by i2smrt4u** [comment]
> if thats your lava tank below the smelter, unfortunately the issue is user error... you need a specific amount of lava under the smelter for correct operation, you need to limit the tank to about 8 or 9 buckets.
> 
> heres an image of a correct setup (not tested in 1.18 yet) https://i.imgur.com/EfruReP.png
> 
> tested in direwolf 1.18 1.4, you need 5 buckets of lava for clean smelting.

I had previously tested it with a comparator reading a one to five tanks with every value between 3 and 15 power with no success. I do not believe the fullness of the tank to have been the problem, pictured is just the state of the tank at the end of my testing.


I just loaded up my world and it is working as is with no modifications to my setup. I can only guess at the cause of the problem or the cause of the fix. For the latter, I would assume that the update from 1.3.1 to 1.4.1 has fixed it. I do not know whether to close as ""fixed" or "cannot reproduce", I will choose the latter to be corrected as you see fit.
