### ISSUE TITLE
[Bug]: Dungeon structures generating in Compact Machines and JAMD Mining dimensions

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#894]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.3.1

### Describe the bug

A few days ago I noticed dungeons were being generated in the JAMD mining dimension and assumed that was intended. By chance I've just entered a compact machine and seen that less ideally dungeons are generating there, too. Plus, Nasty Mobs' mobs are spawning as can be seen in screenshot 2/2 below.

### Steps to reproduce

1. Go to either JAMD mining dimension or enter a compact machine
2. Zoom around in spectator until you find a dungeon

### Expected behaviour

No dungeon structures generated

### Screenshots

![Screenshot 1](https://gcdnb.pbrd.co/images/ih32iBIKbOAz.png?o=1)

![Screenshot 2](https://gcdnb.pbrd.co/images/sOPWBUCxTSQB.png?o=1)

**Comment by 5ully** [comment]
This is a mod bug that happen due to quark being in the pack. This one describes the issue:
https://github.com/FTBBeta/Beta-Testing-Issues/issues
