### ISSUE TITLE
[Bug]: FTB OceanBlock crashes when opening any gui

### ISSUE THREAD

**Issue by iamnoob999** [FTBTeam/FTB-Modpack-Issues#898]
### Modpack

FTB OceonBlock

### Modpack version

1.12.0

### Describe the bug

whenever i open any gui  it crashes my game

### Steps to reproduce

open your world then open your any gui and then it crashes

### Expected behaviour

i expected the game to let me open the guis but it crashes

### Screenshots

![image_2022-06-05_113903343](https://user-images.githubusercontent.com/106923397/172060542-8608cadd-e050-40c0-8849-661ebf930011.png)

**Comment by Raidobw2** [comment]
See https://github.com/FTBTeam/FTB-Modpack-Issues/issues/40 for a fix and please close this if that did it

**Comment by iamnoob999** [comment]
I think i got it thank you =D
