### ISSUE TITLE
[Bug]: Sophisticated Backpack shift-click tool to hotbar behaves in opposite manner than expected

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#899]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.3.1

### Describe the bug

Weird thing with Sophisticated Backpacks. 

In normal inventory, if I shift click an item from my inventory into my hotbar, it goes into the _leftmost_ open slot on the hotbar. 

**_However_**, (and annoyingly so), when shift clicking a tool from the __backpack__ into my hotbar it goes into the _rightmost_ empty slot in the hotbar. 

How uncool is that?

### Steps to reproduce

1. empty the middle four slots of your hotbar, and put the cursor on slot 4 in anticpation of using the tool
2. test shift-clicking some tools from your inventory into the hotbar and you see they wind up in slot 4 if it's empty, ready to use 
3. now press B to open your backpack 
4. now test shift-clicking some tools into your inventory and you will see they wind up in slot 7 not slot 4 and now you have to either undo and use a number key to move the tool to the chosen slot, or mousewheel over to it to use it
5. grind your teeth when this happens for the umpteenth time 

### Expected behaviour

exactly as it works when doing it from personal inventory

### Screenshots

*From Inventory*
 ![2022-06-05_12 25 18](https://user-images.githubusercontent.com/1612570/172060504-17000651-81f4-4e04-a58d-bc4aa20d4e42.png) 
 ![2022-06-05_12 25 25](https://user-images.githubusercontent.com/1612570/172060505-51fc8e80-44f2-46b4-8b1c-d223b093168d.png) 

*From Sophisticated Backpack*
 ![2022-06-05_12 25 36](https://user-images.githubusercontent.com/1612570/172060506-f9771975-e939-46c5-9e3f-ef3b16c9b9ff.png)
 ![2022-06-05_12 25 42](https://user-images.githubusercontent.com/1612570/172060507-7303c74c-a4c0-4923-814f-59a443b828b9.png)

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/174426405-6f740964-09d6-4654-99f6-eb335d002a00.png)
Quote from P3pp3rf1y, seen how its intented i will close this issue
