### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PfluorescentZebra** [FTBTeam/FTB-Modpack-Issues#902]
### Modpack

Plexiglass Mountain

### Modpack version

1.0.1

### Describe the bug

In the Rapid Mod Rundown of the Guidebook, the recipe for the Tinker's Construct guidebook shows the book for Mystical Agriculture instead.  The text on the left page is correct, but the right page says Mystical Agriculture and the wrong book.

### Steps to reproduce

1. Open Inventory
2. Click Guidebook
3. Click Rapid Mod Rundown
4. Click Tinker's Construct
5. Observe recipe for Mystical Agriculture instead

### Expected behaviour

Recipe should be the Materials and You book recipe of a book and a tinker's pattern item. 

### Screenshots

![image](https://user-images.githubusercontent.com/43716457/172074459-022473da-dfb5-4315-befb-00907e8633b4.png)

**Comment by Raidobw2** [comment]
Fixed in 1.0.2
