### ISSUE TITLE
[Bug]: Contiguous modes on the iChisel only chisel a single block

### ISSUE THREAD

**Issue by frisbii** [FTBTeam/FTB-Modpack-Issues#904]
### Modpack

FTB Oceanblock

### Modpack version

1.12.0

### Describe the bug

The contiguous and contiguous 2D modes for the iChisel from the Chisel mod do not work as expected, only chiseling a single block when used instead of the contiguous areas. The 3x3 and 3x1 options work as expected.

### Steps to reproduce

1. Make a platform of some chisel-able material, like cobblestone. 
2. Open the iChisel menu, select that platform material, select a new pattern and select either the contiguous or contiguous 2D modes
3. Left click the iChisel on the platform. Only the block clicked will be chiseled; the rest of the platform will remain as they were before

### Expected behaviour

A contiguous area around where is clicked should be chiseled in the selected pattern

**Comment by TheonlyTazz** [comment]
Yes, i am afraid this issue has been around for quite some time with no information of the devs on fixing this.
