### ISSUE TITLE
[Bug]: DW20 1.18 will not install on MultiMC

### ISSUE THREAD

**Issue by TheKLC** [FTBTeam/FTB-Modpack-Issues#906]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.3.1

### Describe the bug

Pack will not download on MultiMC, please fix URLs.

### Steps to reproduce

1 - Add Instance in MultiMC
2 - Select FTB tab
3 - Find Direwolf20 1.18 (either from search or scrolling)
4 - Select Version 1.3.1
5 - Select OK and wait for install
6 - Error appears while downloading mods

### Expected behaviour

Mods download properly and creates instance on MultiMC

### Screenshots

![Screenshot (23)](https://user-images.githubusercontent.com/63223287/172097240-32a67b94-318a-4fc7-80fc-354a23b7f1b0.png)

**Comment by MichaelHillcox** [comment]
We don't support multimc, also not a modpack issue, feel free to report it to multimc and or our app repo
