### ISSUE TITLE
[Bug]: Forbidden and arcanus unable to create magical farmland

### ISSUE THREAD

**Issue by anigeluk** [FTBTeam/FTB-Modpack-Issues#908]
### Modpack

Direwolf 20 1.18

### Modpack version

1.4.0

### Describe the bug

Forbidden and arcanus arcane crystal dust cannot be right clicked onto farmland to create magical farmland, and the golden orchid seed cannot be planted. 

This was originally mentioned as a part 2 of #852 which was closed after answering part 1 but nothing was said about part 2

### Steps to reproduce

1. Obtains arcane crystal dust 
2. Turn a block of grass or dirt into farmland
3. Right click arcane crystal dust on farmland.
Nothing happens when attempting to right click the arcane crystal dust from main hand onto farmland

### Expected behaviour

Farmland should be transformed into magical farmland and you can then plant the golden orchid seed

**Comment by sneed-feed-seed** [comment]
You use arcane bonemeal on farmland to crate magical farmland, not the arcane crystal dust

**Comment by anigeluk** [comment]
Thanks. Looks like I was reading instructions for an old version where it was dust instead of bonemeal. 

Closing issue
