### ISSUE TITLE
[Bug]: Client crash when clicking button in Mine Colonies' UI

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#909]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.3.1

### Log Files

[crash.log](https://pste.ch/xicedotalu.pl)

### Describe the bug

On placing a Mine Colonies supply camp, clicking the "Open Un-Redo Window" button in the UI crashes the client.

### Steps to reproduce

1. Use supply camp/ship
2. Click on "Open Un-Redo Window" button

### Expected behaviour

No crash

### Screenshots

![Screenshot](https://gcdnb.pbrd.co/images/vNGvU1t62FgW.png?o=1)

**Comment by TheonlyTazz** [comment]
cannot reproduce in latest In-Dev with the updated `Minecolonies-1.18.2-1.0.792-ALPHA.jar`  so i assume this issue has been fixed since then
