### ISSUE TITLE
[Bug]: Fermentation Barrels placed in world crash game after 1.4.0 update

### ISSUE THREAD

**Issue by jjgarciajz** [FTBTeam/FTB-Modpack-Issues#911]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.4.0

### Log Files

[crash-2022-06-06_21.42.20-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8847596/crash-2022-06-06_21.42.20-server.txt)

### Describe the bug

After updating to 1.4.0 the world crashes when loading. 
The crash log points out to the Fermentation Barrel interface from SushiGoCrafting mod and I can confirm that's the problem. 
See the additional notes section.

### Steps to reproduce

My world had "Cheats" enabled (maybe it's relevant)

- Play a world using ModPack v1.4.0.
- Place a SushiGoCrafting Fermentation Barrel in the spawning point of your world while
- Try to open that block's interface.

or

- Place a Fermentation Barrel in a world while playing ModPack v1.3.1.
- Exit & update ModPack to 1.4.0.
- Open that savegame.

### Expected behaviour

The world should not crash on load with Fermentation Barrels on it.

### Additional information

I had two Fermentation Barrels in my world's "base", they seemed to be the problem.

I downgraded to 1.3.1, removed the placed barrels from the world and updated back to 1.4.0 works. It solved the problem.

While in 1.4.0, I tried to place the barrels again and it was fine until I tried to open the barrel's interface. Game crashed again.
Hope this helps.

**Comment by quietust** [comment]
This looks like the exact same crash described in #910.

**Comment by jjgarciajz** [comment]
Based in the crash log, it may perfectly have the same origin, indeed.
