### ISSUE TITLE
[Bug]: Delightful Dirt only spawn Drygmys

### ISSUE THREAD

**Issue by luchokoldo** [FTBTeam/FTB-Modpack-Issues#912]
### Modpack

Direwolf20 1.18

### Modpack version

1.4.0

### Describe the bug

if you set place the Delightful Dirt in a low Y level ( 18 or lower ) only spawns Drygmys, if I change the config in Ars Nouveau to prevent that mob to spawn then no mobs spawns

### Steps to reproduce

1. Go to Y level 15
2. Place Delightful Dirt
3. Place torchs to light the area
4. Only Drygmys will spawn

### Expected behaviour

more passive mobs spawns

### Screenshots

![image](https://user-images.githubusercontent.com/6044994/172249194-37204aec-aae1-449f-b5be-9b0be05d203d.png)

### Additional information

This only happen in low Y level

**Comment by quietust** [comment]
I suspect this might be due to Vertical Biomes being a thing - if you pillar up a few blocks, does your Biome change to something else?

**Comment by luchokoldo** [comment]
> 

looks like the biome change at Y level 20 aprox

**Comment by Raidobw2** [comment]
That might be intended since Andesite Caves are from Terralith and there are a lot of mob spawn changes in Terralith
