### ISSUE TITLE
[Bug]: Unable to craft Vile Dust / Conflicting recipe

### ISSUE THREAD

**Issue by DLCIncluded** [FTBTeam/FTB-Modpack-Issues#913]
### Modpack

Direwolf20 1.18

### Modpack version

1.3.1

### Describe the bug

You are unable to progress with the mod SoulShards due to a conflicting recipe with Create. 

### Steps to reproduce

1. Smelt Soul Sand in furnace, redstone furnace, etc.
2. Get Scoria

### Expected behaviour

Get Vile Dust

### Screenshots

JEI Recipes
Vile Dust Recipe:
https://blockshot.ch/gLqh
Scoria Recipe:
https://blockshot.ch/XzSk

Actual Output:
https://blockshot.ch/ZsnR

**Comment by anigeluk** [comment]
Appears to be working in 1.4 where the recipe for vile dust is to put scoria into the furnace

**Comment by Sunekaer** [comment]
This is fixed

**Comment by Staegrin** [comment]
Recipes.js says:


  event.remove({ output: "soulshards:vile_dust" });
  smelting("soulshards:vile_dust", "create:scoria").xp(0.7);

Shouldn't it be:
 event.remove({ output: "soulshards:vile_dust" });
  event.smelting("soulshards:vile_dust", "create:scoria").xp(0.7);
    });

**Comment by TheonlyTazz** [comment]
correct, this must have slipped under my radar... unlucky i just pushed a new update, i might add this to a hotfix if there is anything coming up
