### ISSUE TITLE
[Bug]: Scooporator MX200 Turbo (GenDustry) won't charge in Wired Charger (EnderIO)

### ISSUE THREAD

**Issue by dragonkid828** [FTBTeam/FTB-Modpack-Issues#916]
### Modpack

FTB Revelations

### Modpack version

3.6.0

### Describe the bug

Despite being in the list of things that are able to be charged, it doesn't seem to accept the Scooporator MX200 Turbo.

### Steps to reproduce

1. Open Wired Charger (EnderIO).
2. Try to insert Scooporator MX200 Turbo.
3. Be disappointed as you cannot.

### Expected behaviour

Wired Charger charges Scooporator MX200 Turbo

### Additional information

I've seen this issue in other github's, but thought I'd mention it here as well. Unsure if it's fixable though.

**Comment by TheonlyTazz** [comment]
I am sorry but this issue cannot be fixed, please use the Thermal "Energetic Infuser" to charge this.
This issue has been brought up at the developers from Enderio (who dont maintain 1.12 anymore and to Gendustry, who ignored the issue and never resolved it
https://github.com/bdew-minecraft/gendustry/issues/290
