### ISSUE TITLE
[Bug]: Integrated Dynamics batteries craft full of power.

### ISSUE THREAD

**Issue by Morelyn** [FTBTeam/FTB-Modpack-Issues#918]
### Modpack

Direwolf 20 1.18

### Modpack version

1.4 and 1.4.1

### Describe the bug

when crafting an integrated dynamics battery, they start full with 2 billion RF, other crafting seems to work fine (combining batteries to increase their max rf) just lots of free RF

### Steps to reproduce

1. Craft a battery
2. See an overful durability bar
3. place the battery in the world, see a garbage pillar rendered above the battery.

### Expected behaviour

new batteries should be empty on craft.

### Screenshots

![2022-06-07_19 00 14](https://user-images.githubusercontent.com/32840350/172451240-47ad58c8-d875-4c00-bd3a-3b62c4644d7d.png)

**Comment by TheonlyTazz** [comment]
This needs a mod update, already reported at Integrated Dynamics Github:
https://github.com/CyclopsMC/IntegratedDynamics/issues/1179
