### ISSUE TITLE
[Bug]: Can't get Academy 1.16 to load correctly

### ISSUE THREAD

**Issue by Warrof** [FTBTeam/FTB-Modpack-Issues#92]
### Modpack

FTB Academy 1.16

### Modpack version

1.2.0

### Describe the bug

Firstly, my download did not get several of the Library type mods. 
Specifically: **cofh_core**, **mcjitylib, observerlib**, **rhino_forge**, and **titanium**.
Not sure why, but after several uninstalls and re-downloads the problem persisted, so I just manually downloaded the exact versions shown in the Mods section of the modpack page in FTB app.

[crash-2021-10-06_08.35.39-fml.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7295765/crash-2021-10-06_08.35.39-fml.txt)

After that the modpack seemed to load just fine, but then it threw an unusual error basically stating that Minecraft Crashed, but no mod was responsible.
![Academy Screenshot](https://user-images.githubusercontent.com/21962742/136247204-d9b44543-135d-4356-a13e-42264ccb8e78.PNG)
[crash-2021-10-06_09.22.24-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/7295763/crash-2021-10-06_09.22.24-client.txt)

P.S. My internet can be really slow/poor at times (hotspotting off cellphone), this may have caused a file corruption somewhere like it did when I downloaded Stoneblock 2.

### Steps to reproduce

1. Start modpack with out those mods
2. Get annoyed and download and put them in mods folder manually.
3. Start Modpack again, and crash

### Expected behaviour

Normal Download and Launching of Modpack

**Comment by Raidobw2** [comment]
Rhino crashed, you can see that in the stacktrace. I'll be back to you in a bit, but for now this is what i see. Wrong version maybe?

If you get another crash after trying some things post it here i'll look it up in a bit.

**Comment by JL2210** [comment]
For anyone having this issue now, it's caused by deleting the MineTogether mod. You can re-download it and disable it in configs or comment out the lines in main_menu.js
