### ISSUE TITLE
[Suggestion]: Addition of Agricraft and Industrial foregoing

### ISSUE THREAD

**Issue by edotenseilove** [FTBTeam/FTB-Modpack-Issues#920]
### Modpack

Direwolf 20 1.18

## Mod suggestion
Industrial foregoing
Link to mod: https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing
I think this mod is a nice and a clasical one for direwolf packs.
Agricraft
Link to mod: https://www.curseforge.com/minecraft/mc-mods/agricraft
I think that this mod provides a nice addition in terms of better farming options/improvements. Especialy nice is the compatibility with Industrial Foregoing harvester. Also I believe it will be a fun automation challenge for dire:-).

P.S.:If agricraft were to be added I would change Use GUIs option in config file to true to avoid possible issues with animations which could result in crash

**Comment by TheonlyTazz** [comment]
Industrial Foregoing got added
