### ISSUE TITLE
[Bug]: Various mob spawners not working when player is over 128 blocks away

### ISSUE THREAD

**Issue by perlguy** [FTBTeam/FTB-Modpack-Issues#922]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.3.1

### Describe the bug

Mob spawners stop working if the player is more than 128 blocks away in the same dimension.

When I go to another dimension, they DO work.

Tested with Pneumatic Craft agitators, tier 5 soul shards cages, and dreadful dirt.  Using mob grinding utils for killing mobs and absorption hopper and item collector feeding into an ender chest.

Not sure if these matter, as they are both well over 128 blocks
Render distance: 16 chunks
Simulation distance: 32 chunks

I lowered them both to 8 chunks, and there was no change in behavior.

### Steps to reproduce

Move 128+ blocks away from mob spawner, drops stop showing up in ender chest.  moving back into range you can see the mobs start spawning again.

### Expected behaviour

Mobs continue to spawn even when player is out of range but in the same dimension.

**Comment by NJM1564** [comment]
Chunks loaded? 
Minecraft tends to not unload chunks when you change dems. And Pneumatic Craft agitators, tier 5 soul shards cages, and dreadful dirt won't keep chunks loaded by themselves.

**Comment by MacChuck** [comment]
Might be due to https://www.curseforge.com/minecraft/mc-mods/it-shall-not-tick

**Comment by perlguy** [comment]
Yes, I forgot to mention that I tested with both ftb chunks (part of the pack) and chunk loaders (added from curseforge).

**Comment by embeddedt** [comment]
As far as I know this is vanilla behavior. Here is the logic that runs in loaded chunks, for each mob:

1. Check if there are any players in the same dimension.
2. If not, keep the mob spawned.
3. If there are, check how far away they are.
4. If there are no players within 128 blocks of the mob, despawn it.

What this means is that dimensions with no players will work perfectly for mob farms, but dimensions with any players in them will need a player close by at all times.

The mobs are probably spawning in your case but immediately despawning afterwards.
