### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by NJM1564** [FTBTeam/FTB-Modpack-Issues#924]
### Modpack

FTB Direwolf 20 1.18

### Is your suggestion related to a problem? Please describe.

In the last version I was able to equip the minecolony villagers with atomic dissemblers as pickaxes and shovels that they did not need to replace. In the new version (1.4.1) that is no longer allowed. (Probably do to them not breaking.) I would like that changed back. The atomic disassembler are hardly cheap and shouldn't be considered overpowered in comparison to making diamond tools. Even if you have to make the diamond ones over and over again.

**Comment by Sunekaer** [comment]
Nothing we can do about this from what I know I would recommend opening a issue on minecolony's issue tracker.
