### ISSUE TITLE
[Bug]: ftb contraption solar panels not working in mining dimension

### ISSUE THREAD

**Issue by vizzair** [FTBTeam/FTB-Modpack-Issues#925]
### Modpack

ftb presents direwolf20

### Modpack version

1.18

### Describe the bug

none of the ftb contraptions solar generators work in the mining dimension, but work ok in the overworld.

### Steps to reproduce

go to mining dimension
place solar generators on ground

### Expected behaviour

should be generating zaps

**Comment by MacChuck** [comment]
Not a bug. The mining dimension is designed to not provide solar or wind power.

**Comment by Sunekaer** [comment]
As Mac said not a bug
