### ISSUE TITLE
[Bug]: Recipe Conflict Gold Bars -> Gold Panel Bars

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#926]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.4.1

### Describe the bug

Recipe conflict with creating gold panel bars

### Steps to reproduce

1. snag some golden bars from a nether fort
2. change their form in a crafting table and then use U to see how it can be used
3. note that there are two recipes it can make both of which are the same but the result is not

### Expected behaviour

working recipe

### Screenshots

![2022-06-09_03 34 11](https://user-images.githubusercontent.com/1612570/172800070-31969e83-8966-4230-b7f7-5cab29cc474c.png)

**Comment by TheonlyTazz** [comment]
After quite some fiddling around i come up with a clean solution which would let you cycle through the bars
![javaw_uDLEXzwr44](https://user-images.githubusercontent.com/3908847/173336864-78936439-ce66-4293-ab2f-37114581e1ef.gif)

I'll consider this fixed In-Dev for now
