### ISSUE TITLE
[Bug]: plexiglass mountain language bug?

### ISSUE THREAD

**Issue by haorza** [FTBTeam/FTB-Modpack-Issues#928]
### Modpack

FTB plexiglass mountain 

### Modpack version

latest

### Describe the bug

basically whenever i launch the game its all the special characters idk why 

### Steps to reproduce

open the game

### Expected behaviour

i dont know

### Screenshots

![2022-06-09_18 25 36](https://user-images.githubusercontent.com/107202050/172884842-79a0399b-23a8-4b23-b41f-786b86455197.png)
![2022-06-09_18 26 52](https://user-images.githubusercontent.com/107202050/172884885-a5ed5a33-b2c9-49b9-b487-76623767063c.png)

### Additional information

the second screenshot is the language page in minecraft

**Comment by Raidobw2** [comment]
That's weird 0_o is this on the FTB App?

**Comment by MichaelHillcox** [comment]
Restart the pack, sometimes loading breaks

**Comment by Raidobw2** [comment]
Hello @haorza, please try the fix I mentioned in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1076. I think that might be due to the locale/language your operating system uses. It looks like that worked for the other user, so I believe it will work for you as well, so I'll close this!
