### ISSUE TITLE
[Bug, IronChests]: Diamond Chest upgrade recipe is swapped

### ISSUE THREAD

**Issue by Jody24** [FTBTeam/FTB-Modpack-Issues#93]
### Modpack

FTB OceanBlock

### Modpack version

1.2.0

### Describe the bug

Both "Diamond to Crystal Chest Upgrade" and "Diamond to Obsidian Chest Upgrade" recipe is swapped.

### Steps to reproduce

1. search "diamond to" in the jei search bar
2. look up the recipe between crystal chest upgrade and obsidian chest upgrade

### Expected behaviour

Both recipe is not swapped

### Screenshots

![image](https://user-images.githubusercontent.com/20773098/136289006-b3affa6e-eb3d-4528-a9b7-769141138007.png)
![image](https://user-images.githubusercontent.com/20773098/136289047-2f7af2d0-18af-401f-b617-c978daf725b3.png)

**Comment by Sunekaer** [comment]
https://github.com/progwml6/ironchest/issues/235
