### ISSUE TITLE
[Bug]: DeepResonance Radiation Monitor Not Printing To Chat

### ISSUE THREAD

**Issue by i2smrt4u** [FTBTeam/FTB-Modpack-Issues#930]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.4.1

### Describe the bug

In 1.3.1 the Radiation Monitor worked correctly, printing the current radiation as stated on the mod's FTB wiki page. It no longer does this, only displaying the radiation on mouseover. The radiation monitor does correctly 'animate' when held.

### Steps to reproduce

1. Create radiation
2. Click radiation monitor
3. Expected behaviour does not occur

### Expected behaviour

Radition monitor prints radiation level in chat

### Screenshots

![drissue2](https://user-images.githubusercontent.com/106843452/173000104-47d5358e-cd02-47d1-807b-323c96ed9262.png)

**Comment by Sunekaer** [comment]
DeepResonance had an update in 1.7.0 of the pack, is it still an issue in that version or newer?
