### ISSUE TITLE
[Bug]: Unable to join an FTB University 1.16 v1.6.0 server

### ISSUE THREAD

**Issue by Cosmishadow11** [FTBTeam/FTB-Modpack-Issues#933]
### Modpack

FTB University 1.16

### Modpack version

1.6.0

### Log Files

https://pastebin.com/D5NrBQPu

### Describe the bug

Following the update from 1.5.0 to 1.6.0 players are now unable to join the server due to an "IndexOutOfBoundsException"

### Steps to reproduce

1. Create or update a 1.6.0 server using the Linux "serverinstall" files on ubuntu server 
2. Attempt to join using a windows client

### Expected behaviour

Users should be able to join the server

### Additional information

This issue seems to occur regardless of wether or not the server has just been updated from 1.5.0 or is a fresh install of 1.6.0.

The exception seems to be caused by the mod **Recipie Buffers** however disabling it did not fix all issues. Namely other mods then started to misbehave on my updated server with one example being immediate client crashing upon performing a Mana and Artifice ritual

**Comment by aaronhowser1** [comment]
The MaA issue is possibly unrelated, can't know without a crash report. Confirming the bug with Recipe Buffers, might also be a compatibility issue with Blood Magic from the log?

**Comment by Cosmishadow11** [comment]
Hi, thanks for the confirmation.
I've looked into the MaA crashing a bit more and got a couple more crash reports (I had more but they're basically all the same):
https://pastebin.com/UNA5E8Gs
https://pastebin.com/sm42XUxx

Seems to be that the MaA rituals themselves are trying to render certain things that are null? As you say, most likely completely unrelated. Nothing interesting on the server end either so this seems to be entirely a client rendering problem.

**Comment by aaronhowser1** [comment]
Can you make a new separate issue for this?
