### ISSUE TITLE
[Bug]: Server start script incomplete/wrong

### ISSUE THREAD

**Issue by wutterfly** [FTBTeam/FTB-Modpack-Issues#935]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.4.1

### Describe the bug

For the Modpack FTB Direwolf20 1.18, Version 1.4.1 and Target arm linux,
the start.sh script still contains a placeholder value for the jar file to run.

./jre/jdk-17.0.2+8-jre/bin/java -javaagent:log4jfix/Log4jPatcher-1.0.0.jar -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx6144M -Xms4096M -jar insert-jar-here.jar nogui

### Steps to reproduce

1. download serverfiles for arm linux
2. run installer 
3. set permissions
4. try to run ./start.sh
5. returns error "Unable to access jarfile insert-jar-here.jar"

### Expected behaviour

running start.sh should start the server

### Additional information

I tried replacing  "insert-jar-here.jar" with "minecraft_server.1.18.2.jar", this started a server i could join to, but it was just a vanilla server with corrupted world gen

**Comment by Raidobw2** [comment]
https://github.com/CreeperHost/modpacksch-serverdownloader/issues/13

**Comment by pjfranke** [comment]
Did you look at the entire log file for errors?  If the Forge installer doesn't run successfully, it won't update the start.sh file with the correct jar file, or reference to the unix_args.txt file.  See my issue https://github.com/FTBTeam/FTB-App/issues/618, specifically here, where I mention that running the installer without a functioning Java in your $PATH will lead to that same result:

>This results in the above log tail, with a "failed Forge install" message, and start.sh isn't valid:

>./jre/jdk-17.0.2+8-jre/bin/java -javaagent:log4jfix/Log4jPatcher-1.0.0.jar -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx6144M -Xms4096M -jar **insert-jar-here.jar** nogui

```
2022/06/20 20:56:06 [723/723] Downloaded jre/jre.tar.gz from https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.2%2B8/OpenJDK17U-jre_x64_linux_hotspot_17.0.2_8.tar.gz
2022/06/20 20:56:06 Downloaded 723 successful, 0 failed, 0 incomplete.
2022/06/20 20:56:06 Running Forge installer
2022/06/20 20:56:06 Running forge installer failed with exec: "java": executable file not found in $PATH. You may wish to install forge 40.1.47 for Minecraft 1.18.2 manually
```
