### ISSUE TITLE
[Bug]: Copper Dupe Bug

### ISSUE THREAD

**Issue by BlueMagnus** [FTBTeam/FTB-Modpack-Issues#936]
### Modpack

Direwolf 20 1.18

### Modpack version

1.4.1

### Describe the bug

I set up a smeltery/foundry for my ore processing. It turns the molten ore into nuggets which then goes into a Sophisticated Chest with the Advanced Compacting Upgrade. All the ores get auto converted from nuggets > ingots > blocks. 
This is fine for most metals except Copper. Copper converts from nuggets > ingots > blocks > cut copper.
The only way to convert it back to regular copper blocks is in a stone cutter. When converted back it doubles the amount of copper.
I've tried black listing the conversion to cut copper but it doesn't seem to work all the time. 
I am not particularly concerned for my own single player game but it might be an issue for other. 

### Steps to reproduce

Put copper in Sophisticated Chest with Advanced Compacting Upgrade. 
Take cut copper produced and reconvert in stone cutter. 
Doubles copper blocks.

### Expected behaviour

I didn't expect to get cut copper. Expect just regular copper blocks.

**Comment by DasBrain** [comment]
You can simply craft 4 cut copper block for 1 copper block in the stone cutter, then convert the cut copper block back into 4 copper blocks, ending up with 16 copper blocks from 1 copper block.

**Comment by TheonlyTazz** [comment]
![grafik](https://user-images.githubusercontent.com/3908847/173331170-d1c3e392-96d9-4a9e-ae17-e80031c011f3.png)

![grafik](https://user-images.githubusercontent.com/3908847/173331223-ff60fe15-2821-46f3-8ea7-4228cadfc5a2.png)

fixed in-dev

**Comment by TheonlyTazz** [comment]
![grafik](https://user-images.githubusercontent.com/3908847/173331450-ed7e9d89-9857-4fdb-b520-a6f605cd6253.png)

![grafik](https://user-images.githubusercontent.com/3908847/173331477-25c9643d-40c3-4b13-b188-470fee4ec360.png)

Fixed in-dev

**Comment by BlueMagnus** [comment]
Thanks for the update. While in a single player it might be that big of a deal, but for a server with some sort of economy in place it might be a problem. I really wanted to bring it to pack dev notice if they hadn't known.
