### ISSUE TITLE
[Bug]: Tesseracts do not accept items from Pipez or the Absorption Hopper from Mob Grinding Utils

### ISSUE THREAD

**Issue by DeciTM** [FTBTeam/FTB-Modpack-Issues#937]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.4.0

### Describe the bug

Tesseracts do not accept items from Pipez or the Absorption Hopper from Mob Grinding Utils. The source storage (like a vanilla chest) still contain the items.

### Steps to reproduce

Pipez item pipes do show visual connection (both from and to) but items do not transfer _into_ a Tesseract. I'm able to use a hopper as a stop-gap in the mean time as a means to connect the pipe to the Tesseract. Oddly enough, in this configuration the item pipes can remove items from the Tesseract on the other side of the connection. This tells me that the issue is likely with the Tesseract mod not appearing as a valid inventory target to move the items into for mods, which must be why vanilla hoppers work.

This issue occurs in both SP and MP in the same chunk.

### Expected behaviour

I'm expecting the items to go in.

**Comment by MaxFirestorm** [comment]
To add on to this:

Fluids can be inserted into Tesseracts with Pipez pipes, but on the other end it doesn't seem to be able to extract them. I've had to use a Pneumaticraft Fluid Hopper to be able to pull honey out of a Tesseract on the receiving end as Pipez Universal and Fluid Pipes didn't want to work.

**Comment by TheonlyTazz** [comment]
https://github.com/SuperMartijn642/Tesseract/issues/44
![image](https://user-images.githubusercontent.com/3908847/175009769-48670e7b-b983-4686-83b1-19a8c48116f4.png)
