### ISSUE TITLE
[Bug]: Possible server bug - FTBRanks not assigning name prefix/colors properly Direwolf20 1.18

### ISSUE THREAD

**Issue by DLCIncluded** [FTBTeam/FTB-Modpack-Issues#938]
### Modpack

Direwolf20 1.18

### Modpack version

1.4.1

### Log Files

![image](https://user-images.githubusercontent.com/23517228/173160344-e6ae98f9-2f4d-4845-b37e-75bcf1d6b1b4.png)
![image](https://user-images.githubusercontent.com/23517228/173160357-3892f3e9-c4a4-4be8-910c-caf74520bff1.png)

### Describe the bug

Created ranks on the server on version 1.2.0, and have since updated to 1.3.1 then 1.4.1. 
The ranks worked up until updating to 1.4.1

I grabbed a copy of the original ranks.snbt and it persists. 
This is our ranks file:

`
{
	member: {
		name: "Member"
		power: 1
		condition: "always_active"
		ftbranks.name_format: "<{name}>"
	}
	vip: {
		name: "VIP"
		power: 50
		ftbranks.name_format: "<&bVIP {name}&r>"
	}
	admin: {
		name: "Admin"
		power: 1000
		condition: "op"
		ftbranks.name_format: "<&2{name}&r>"
	}
}
`

And I gave the rank 'vip' to another player, and I am opped. This screenshot is from my client as an opped player, which is showing my account properly:
![image](https://user-images.githubusercontent.com/23517228/173161046-3967c914-7f93-4dd7-bcaf-2eeaeeff7395.png)

Then this is a snip of his client:
![image](https://user-images.githubusercontent.com/23517228/173161085-b4cba0da-80d0-405f-af25-7a9aa484ebe8.png)

This happens for all players on the server. You can see your own name style, but not those of others. 

I first thought maybe it was the server, however, we can see that the server console is correctly showing the name in the server console:
![image](https://user-images.githubusercontent.com/23517228/173161159-7ff4120f-c78b-4dd9-ac4e-2716ea36c46b.png)

I spun up a fresh 1.4.1 with no modifications at all to config / mods using "serverinstall_95_2138" on ubuntu with out our server manager, we joined and I Opped my account, gave VIP to my friends, and we replicated the issue:
![image](https://user-images.githubusercontent.com/23517228/173162232-834ee2b5-7370-4a18-bdd2-a4e61c8043fc.png)
![image](https://user-images.githubusercontent.com/23517228/173162305-43f67168-6793-4494-8c23-9670a1d769d9.png)

The server sees the nickname, but not the clients. 

I do not know what would cause this, as it does not appear that the version of FTB Ranks changes from 1.3.1 to 1.4.1, however, something broke. Please let me know if there is any other information I can provide

Thanks for any assistance, and for all you guys do. 

### Steps to reproduce

Install 1.4.1 server
Apply a rank to a user (ex. VIP)
type in chat

### Expected behaviour

Name styles should sync to all players/clients

**Comment by DLCIncluded** [comment]
I'm not sure if this is related to this pack alone at this point. 
I installed versions 1.3.1 and 1.2.0 on a test server and two pc's in my house, and its not working going back to those either. 
I'm not sure why it would have stopped across all versions now, since it was working with in the last week for us. 

I am going to attempt a pack with just FTB ranks and see if I can replicate it with only forge and ftb ranks.

**Comment by DLCIncluded** [comment]
Client 1 & server console
![image](https://user-images.githubusercontent.com/23517228/173165824-47f753bc-0096-486e-a25a-55cb2ad66bbb.png)
Client 2
![image](https://user-images.githubusercontent.com/23517228/173165899-c171aa63-d98a-4d5f-b5c8-c8b12b9ee5be.png)

This appears to be a wider issue than the DW20 pack. I'm curious if theres something in the way mojang/microsoft handles the chat that changed. I'll close this for now as its nothing you can fix.

**Comment by phit** [comment]
hey, thanks for your research into this, this lead me to test this with just a simple test mod and open an issue on the Forge tracker https://github.com/MinecraftForge/MinecraftForge/issues/8729

**Comment by DLCIncluded** [comment]
That's at least good news, I see you dove deep into that thanks for the update
