### ISSUE TITLE
[Bug]: Advanced Incriber voiding itens

### ISSUE THREAD

**Issue by dinhoarakaki** [FTBTeam/FTB-Modpack-Issues#940]
### Modpack

Plexiglass Mountain

### Modpack version

1.0.2

### Describe the bug

If you use the block Advanced Inscriber of AE2 Things with Applied Energistics 2 energy(AE) the resulting item of it is voided, but by using Mekanism's energy(FE) the crafting occurs normally

### Steps to reproduce

plug the Advanced Inscriber in a Applied Energistics 2 cable(with AE power) then insert the press and the respective ore(inscriber logic press and a gold ingot for example) in it then would be resulting item will not be crafted and the resources will be wasted.

### Expected behaviour

the block to work with the type of energy it should

**Comment by Raidobw2** [comment]
Oof that's an issue... I'll report to the mod author and see for any configs. I may disable the block in the case it cannot be solved, thanks for the report!

**Comment by dinhoarakaki** [comment]
Hey there R3gen! Sorry for this late reply

We haven’t played any version other than the one we had the issue. When we
tested, we also run the block “off grid” to check if the item was being
pulled by any other mean but it still kept voiding, so it was not any other
block/cable. I really hope it was just a glitch of the older version but if
you need to be sure I can talk with my friends for us to test in the same
fashion as before.

Em sex., 8 de jul. de 2022 às 08:27, R3GEN ***@***.***>
escreveu:

**Comment by Saereth** [comment]
Thanks for the reply. I also tested separately in both single player and multiplayer and cannot reproduce the issue. Please update your pack to the latest version and if you experience this issue again create a new issue or re-open this one. Thank you
