### ISSUE TITLE
[Bug]: Ingot doubling through rolling plates and then turning those plates back

### ISSUE THREAD

**Issue by superbrias** [FTBTeam/FTB-Modpack-Issues#941]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.4.1

### Describe the bug

Iron, Copper, Gold, Zinc, Tin, Lead, Uranium, Iridium, Aluminum, Enderium, Bronze, Silver, Nickel, Constantan, Electrum, Steel, Invar, Signalum, Lumium, and even Netherite ingots can all be duplicatetd through a processing loop involving FTB Industrial Contraption's Roller and any method of turning plates back into ingots, for example Immersive Engineering's Arc Furnace (direct) and Tinker's Construct's Smeltery or Foundry. (melted down then re-cast)

This can be achieved because, unlike every other method of producing plates, the roller produces 2 plates per ingot, and the two example methods turn each plate back into 1 ingot.

### Steps to reproduce

1.Set up and power a Industrial Contraption's Roller however you like.
2.Set up and power/fuel any of Immersive Engineering's Arc Furnace and/or Tinker's Construct Smeltery or Foundry with ingot/block casts.
3.Start with a finite number of any of the above Ingots, lets say a Netherite Ingot for one of the most broken showcase.
4.Run your aforementioned ingot of choice through the Roller and observe getting twice as many of the related plates as you started ingots.
5.Use either and any method to reprocess the plates back into ingots and observe not only that you get 1 ingot from each plate, but that you end up with twice the amount of ingots you started with.
6.Repeat the non-observation parts of steps 4-5 as desired for the amount of ingots you would like.

### Expected behaviour

When running Ingots through FTB Industrial Contraption's Roller you should get only 1 plate per ingot or when melting down plates you should get no more than a half-ingot's worth per plate.

### Screenshots

![2022-06-11_11 56 58](https://user-images.githubusercontent.com/20515465/173201444-507f1117-249e-4e2a-9506-a4ffeaaa8e4c.png)
![2022-06-11_11 57 07](https://user-images.githubusercontent.com/20515465/173201446-0e59044e-9074-4acc-87fd-83c668569702.png)

### Additional information

Something to note is that if you do half the return from plates you should increase the return on some methods of getting plates to be in line with the Roller, things like Create's press, Immersive Engineering's Press, Thermal's Multiservo Press, and especially Tinker's Plate Mold should all make 2 plate from a single ingot; in Tinker's case it would be making a plate from a half-ingots worth of material, generally 45mb.

If you go this method I would give major points if you made Minecolonies' Blacksmith have a method of producing 2 plates from an ingot as well, weather it need a upgrade to do or just change his hammer recipe to make 2 would be quite thematic.

**Comment by TheonlyTazz** [comment]
for unification sake i decided to make the IC rolling machine make 1 Ingot : 1 Plate and in turn make 4 plates into 1 gear aswell.
This issue is fixed in-dev and will be pushed next update

![grafik](https://user-images.githubusercontent.com/3908847/173328640-39e4e69c-e17d-4c5b-aeb8-db3962158688.png)
![grafik](https://user-images.githubusercontent.com/3908847/173328679-8a44dded-fff4-4659-b0e8-658363c8c881.png)
