### ISSUE TITLE
[Bug]: Lazier AE2 machines changed item IDs in between versions

### ISSUE THREAD

**Issue by GriSphera** [FTBTeam/FTB-Modpack-Issues#942]
### Modpack

FTB University 1.16

### Modpack version

1.6.0

### Describe the bug

It seems that Lazier AE2 changed how their ID system works, and at least the machines have new IDs. That causes two things:

1. The quests referring to this machines now request invalid items for completion.
![2022-06-11_13 45 13](https://user-images.githubusercontent.com/88846902/173202746-299662ee-420a-4f02-973e-17759198bdb2.png)
![2022-06-11_13 45 24](https://user-images.githubusercontent.com/88846902/173202749-befb1e38-b16f-4bde-bb1e-df8e2eb57ff0.png)
![2022-06-11_13 48 03](https://user-images.githubusercontent.com/88846902/173202752-e2497bc6-110b-456c-8be8-1a0abaecbe9b.png)
2. All in-world machines dissapear, since they no longer have the corresponding IDs.

### Steps to reproduce

1. Open a world in version 1.5.0 of the modpack
2. Go to the applied energistics 2 section and look at the lazierae2 quests, and/or place those machines in world.
3. Close the world and update the modpack to 1.6.0.
4. Re-enter the world.

### Expected behaviour

Have the correct machines in the quests. I don't know if there is a work around to the machines dissapearing, but maybe advising the player to not build the complete machines until they upgrade to 1.6.0 or higher.

**Comment by aaronhowser1** [comment]
There's nothing I can do to fix the items vanishing from your world on update, unfortunately. The quests have been updated to use the new IDs however.
