### ISSUE TITLE
[Bug]: Neat with little contraptions

### ISSUE THREAD

**Issue by DinnerBeef** [FTBTeam/FTB-Modpack-Issues#943]
### Modpack

DW20 1.18

### Modpack version

1.4.1

### Log Files

NONE

### Describe the bug

Neat makes the contraption barge have very strange mob health bar
(https://s.dinnerbeef.com/gOXe5/rEgiYEkE36.mp4/raw)

### Steps to reproduce

Place down contraption barge

### Expected behaviour

Not have a very glitchy bar on the mpb

**Comment by Raidobw2** [comment]
For modpack dev:

1.
`config/neat-client.toml`
`Blacklist = ["minecraft:shulker", "minecraft:armor_stand", "minecraft:cod", "minecraft:salmon", "minecraft:pufferfish", "minecraft:tropical_fish", "littlecontraptions:contraption_barge"]`

2.
`kubejs/assets/littlecontraptions/lang/en_us.json`
```
{
    "entity.littlecontraptions.contraption_barge": "Contraption Barge"
}
```

Reported to author through Discord
![image](https://user-images.githubusercontent.com/17010632/173208253-5dff4a7b-1dcc-435c-82e5-cc7e4bad1631.png)
![image](https://user-images.githubusercontent.com/17010632/173208263-204a5ab2-bd71-4561-8395-cc3bdbbefff0.png)
