### ISSUE TITLE
[Bug]: World not loading 

### ISSUE THREAD

**Issue by FilipVem** [FTBTeam/FTB-Modpack-Issues#945]
### Modpack

Plexiglass Mountain

### Modpack version

1.18.2

### Describe the bug

![2022-06-12_16 29 07](https://user-images.githubusercontent.com/107357512/173238042-45330b20-da74-4152-9b90-2708cba2b3c3.png)

I hope this enough as "describing" the bug.

### Steps to reproduce

create a world and join it

### Expected behaviour

That the game loads the world

**Comment by Raidobw2** [comment]
Hmm. I've had this once or twice in dev. I think it was when I was going back and forth to the main menu from in-game. Possibly it's a RAM issue (I know the RAM usage raises when going back to main menu for some reason) or a mod causing a problem. Can you confirm if your game was freshly launched or if it had been running for a while? I'll investigate in-dev in any case. Thanks in advance for your help and the report!

**Comment by FilipVem** [comment]
Actually i had accidentally created a world before (with the wrong
settings) which i removed and the created that one instead

Den mån 13 juni 2022 08:42R3GEN ***@***.***> skrev:

**Comment by Raidobw2** [comment]
Hello @FilipVem, have you had the time to play in the past weeks and did it work after a restart? Did the error happen again? 
 Thanks in advance

**Comment by FilipVem** [comment]
No the bug has not happened again and its working!

Den fre 8 juli 2022 01:17R3GEN ***@***.***> skrev:
