### ISSUE TITLE
[Bug]:  Fatal Exception whilst installing modpacks

### ISSUE THREAD

**Issue by Nightfall143** [FTBTeam/FTB-Modpack-Issues#946]
### Modpack

Direwolf 20 1.18

### Modpack version

1.18

### Describe the bug

Upon attempting to install modpacks on the launcher I get a message of Fatal Exception whilst installing modpack.  Appears to be on several modpacks

### Steps to reproduce

1 go to launcher
2 click on the green arrow
3 get error

### Expected behaviour

it to install

**Comment by Raidobw2** [comment]
Hi, try following this procedure for now: https://www.notion.so/Manually-installing-Java-17-in-the-FTB-App-454cede2874947818aa2f41e26c1efd6. Let me know if that fixes it, thanks in advance!

**Comment by Nightfall143** [comment]
Worked, much appreciated.
