### ISSUE TITLE
[Bug]: sophisticated backpack with stack tier upgrade and/or inventory sorter voided items

### ISSUE THREAD

**Issue by Xalorous** [FTBTeam/FTB-Modpack-Issues#948]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.0.2

### Describe the bug

I went mining in the overworld with a sophisticated backpack equipped with a magnet upgrade, and  Stack Tier Upgrade I.

I opened the backpack and hit middle mouse button.  The items were sorted into 64 item stacks, where many  had been 128.  The items which were 'pushed' off the bottom of the list were voided.

### Steps to reproduce

In the overworld, 
Have enough items with 2+ stacks in sophisticated backpack with stack upgrade I that the backpack could not hold all the items if they were unstacked to single stacks.  
Press middle mousebutton for inventory sort.  double stacks are unstacked, and items that don't fit get voided.

### Expected behaviour

in dw20 1.18.2, and in NTC2, soph backpack with item upgrade sorts without voiding

**Comment by Raidobw2** [comment]
See https://github.com/FTBTeam/FTB-Modpack-Issues/issues/923 for a fix
