### ISSUE TITLE
[Bug]: Server Crash on user login in Direwolf 1.18 pack

### ISSUE THREAD

**Issue by bheisler** [FTBTeam/FTB-Modpack-Issues#949]
### Modpack

Direwolf20

### Modpack version

1.3.1

### Log Files

https://pste.ch/iwukapumul.cs

### Describe the bug

When I logged in to my server earlier today, the client framerate dropped and the average server tick time gradually grew out of control until the server crashed. This continued to happen on every login until I reverted my world to an earlier backup. After doing this, it seemed to work again until I logged in again this evening and the same thing happened again, and again I had to revert the world to a backup.

### Steps to reproduce

I'm sorry, I don't have reproduction steps. I'm hoping there's something useful in the crash log.

### Expected behaviour

It shouldn't crash.

### Additional information

I don't know if it helps, but both times I had done some unlocking of glyphs and made some Ars Nouveau curios shortly before the problem happened? I think that's about the only thing I did both times. I'll add more details if it happens a third time.

It did cause the server to jump straight to 100% on all CPUs when it happened, which I thought was unusual. Normally a single thread goes out of control, not all of them.

I did try copying the world over to my main PC so I could run it in single-player mode but that caused the same crash.

**Comment by bheisler** [comment]
On further consideration, a few other possible causes:
- Both times it happened I had crafted a Sophisticated Backpacks advanced feeding upgrade and installed it in my backpack.
- I did forget to chunk-load a chunk that contained my Source generator (Ars Nouveau again). Without a steady supply of source, Whirlisprigs and Drygmys seem to build up particles around their home block without limit; I have seen some buggy behavior relating to this before. It's possible that after several hours of this the accumulated particles might have overwhelmed the server and/or client.

**Comment by TheonlyTazz** [comment]
Looking at your Log, you have over 7000 Item Entities loaded, which probably just brought your server to its knees
![image](https://user-images.githubusercontent.com/3908847/174450778-a0d19663-6d67-4ed4-b05c-ca1ae743885d.png)

so please fix all your farms and dropped item entities...
you can try to use
`/kill @e[type=item]`
to delete all items
