### ISSUE TITLE
missing block items for use with minecolonies in direwolf20 1.18 pack

### ISSUE THREAD

**Issue by stikerdegrey** [FTBTeam/FTB-Modpack-Issues#950]
### Modpack

direwolf20 1.18

### Modpack version

1.4.1

### Describe the bug

missing items for minecolonies 
structure blocks for some buildings missing - ex. framed oak planks

### Steps to reproduce

not available to create

### Expected behaviour

add block items?

**Comment by stikerdegrey** [comment]
thanks

**Comment by TheonlyTazz** [comment]
not a bug then
