### ISSUE TITLE
[Bug]: Moving Minecraft's Bee Hive or Nest with Carry On causes console spam in servers

### ISSUE THREAD

**Issue by mja00** [FTBTeam/FTB-Modpack-Issues#951]
### Modpack

Direwolf20 1.18

### Modpack version

1.4.1

### Log Files

`[Server thread/WARN] [minecraft/EntityType]: Skipping Entity with id` spammed every tick.

### Describe the bug

Currently if you pick up a beehive or nest and place it back down, any loaded chunks containing those placed down blocks will immediately start spamming the console with `[Server thread/WARN] [minecraft/EntityType]: Skipping Entity with id` every tick that they are loaded. Removing these hives and nests from the chunks or unloading them causes the warning to cease. I don't blame the Carry On mod author for this as hives and nests are a bit of a mess in Minecraft.

Adding both blocks to the blacklist for Carry On will ensure that players can't accidentally pick them up and cause this issue. 

### Steps to reproduce

1. Find a natural bee nest out in the world.
2. Pick it up with Carry On.
3. Bring it back to your base and place it down.
4. Notice the console of the server being spammed with "Skipping Entity with id"

### Expected behaviour

No spam

### Screenshots

![image](https://user-images.githubusercontent.com/11252574/173381582-da7a55dd-2c57-4365-a9b4-d8e2e66bcf4e.png)

### Additional information

I know this isn't a bug with the modpack itself but added both `minecraft:bee_nest` and `minecraft:beehive` to the Carry On blacklist will stop this issue from arising. I don't really blame the author of Carry On for this bug as these blocks are quite odd themselves. I do plan on reporting the bug to Carry On to see if it is fixable on their end but this workaround seems for the best as it makes the console and logs unreadable.

**Comment by TheonlyTazz** [comment]
Thanks for posting the issue here, and also directly on the CarryOn Github! We will keep track of it and I'll disable the bee_nest and beehive from theconfig
https://github.com/Tschipp/CarryOn/issues/391
