### ISSUE TITLE
[Bug]: Mana And Artifice Rituals causing clients to crash

### ISSUE THREAD

**Issue by Cosmishadow11** [FTBTeam/FTB-Modpack-Issues#953]
### Modpack

FTB University 1.16

### Modpack version

1.6.0

### Log Files

https://pastebin.com/UNA5E8Gs
https://pastebin.com/sm42XUxx

### Describe the bug

When attempting to perform any ritual the client crashes upon the begining of ritual animation. In certain cases this forces server rollback as clients are unable to rejoin the world because the ritual is incomplete.

### Steps to reproduce

1. Begin performing a ritual by placing down chalk in the pattern of any valid ritual (Specified the the modpacks guide book)
2. Use purified vinteum dust on the central rune (Usually this is the moment of the crash)
3. Complete the ritual by placing the required items and use the purified vinteum dust on the central rune again
4. The client will now be booted from the server 

### Expected behaviour

The ritual should begin animating 

### Additional information

This only seems to occur on servers and not on singleplayer clients. That being said the server itself doesn't throw any errors leading me to believe the issue is client based.

At present I have been unable to test this on a fresh server installation and only on my updated 1.5.0 to 1.6.0 server. I'll update in a comment if that makes a difference when I get the chance

**Comment by aaronhowser1** [comment]
Try again with 1.6.2, which should hopefully be releasing shortly

**Comment by Cosmishadow11** [comment]
Ah yes. This issue seems to be fixed now. I did need to update the server twice but I feel that's unrelated (Probably just a corrupted download). In either case Mana and Artifice rituals are now fixed. Many Thanks!
