### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gabriel-awad** [FTBTeam/FTB-Modpack-Issues#955]
### Modpack

Direwolf20 1.18

### Modpack version

1.18

### Describe the bug

Any time I pick up a Sophisticated Storage chest and try to open a crafting bench it crashes the game all the way back to the launcher. 

### Steps to reproduce

1. Shift right click on sophisticated storage chest to pick it up. 
2. right click on a crafting table. 
3. game will crash

### Expected behaviour

I thought it would open up the crafting table GUI

**Comment by TheonlyTazz** [comment]
I will forward this to the Carry On! Github, but in the meantime... just dont open a Crafting Bench while moving your chests with Carry on.

This happens with everything you carry with CarryOn, not just Sophisticated Storage
