### ISSUE TITLE
[Bug]: Game crashes on mods screen from main menu (mob catcher(v1.1.1))

### ISSUE THREAD

**Issue by caner42345** [FTBTeam/FTB-Modpack-Issues#956]
### Modpack

Plexiglass Mountain

### Modpack version

1.0.2

### Describe the bug

In mods screen from main menu if you click mob catcher mod then game crashes.

### Steps to reproduce

1. Go to mods  from main menu
2. Click mob catcher (v1.1.1)

### Expected behaviour

Game crash

### Additional information

I was reading for what mods installed and what they are. I know its not a huge bug but its bug.

**Comment by Raidobw2** [comment]
Update available https://www.curseforge.com/minecraft/mc-mods/mob-catcher-fabric/files/3834612
