### ISSUE TITLE
[Bug]: Random crash from IntegratedDynamics, IFacadeable.hasFacade()

### ISSUE THREAD

**Issue by quietust** [FTBTeam/FTB-Modpack-Issues#958]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.4.1

### Log Files

[crash-2022-06-14_16.19.25-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8904251/crash-2022-06-14_16.19.25-client.txt)

### Describe the bug

On seemingly random occasions, my client is crashing while attempting to render an Integrated Dynamics cable just at the edge of my render distance. The cable in question occupies only a single block and is connected to a Fluid Importer (placed on a Sink) and two Fluid Interfaces (connected to a Thermal Evaporation Plant and a Fission Reactor).

From where I'm standing, the cable isn't actually visible because it's completely behind the Thermal Evaporation Plant, so I'm not sure why it's trying to render it in the first place. The cable does *not* have a facade on it, though that probably wouldn't have stopped it from crashing.

### Steps to reproduce

Steps currently unknown

### Expected behaviour

Game shouldn't crash

### Additional information

If necessary, I can upload a world backup once I trim it down (from its current size of 500MB compressed), but even that might not be sufficient because the crash doesn't happen consistently.

**Comment by quietust** [comment]
The best I can do is to upgrade my pack to 1.5.1 and see if the crash happens again - if I don't find anything in the next week or two, it's probably safe to assume that it's been fixed.

**Comment by TheonlyTazz** [comment]
could you perhaps offer a world download?  As i cannot replicate this issue

**Comment by quietust** [comment]
I've attached a heavily trimmed-down world snapshot here - hopefully it will still be sufficient to trigger the problem.
[FTB-Modpack-Issues-958.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8943900/FTB-Modpack-Issues-958.zip)

As I noted above, the crash happens almost completely at random, and it could easily take *hours* of gameplay for it to crash.

Useful locations:
* Around 0,0 - an underground base with my ME system inside it, accessible via a white Elevator visible from the surface
* Just southeast - two Thermal Evaporation Plants, and a Fission Reactor + Turbine + SPS.
* Just east of the Thermal Evaporation Plants - an island with a MineColony on it. Flying around this island, especially going further south/east and coming back, seems to be the most likely to trigger the crash.

**Comment by TheonlyTazz** [comment]
I have forwarded this to CyclopsMC, maybe he can figure out why this is crashing

**Comment by TheonlyTazz** [comment]
should be fixed in next update
