### ISSUE TITLE
[Bug]: Minetogether possibly causing server to just crash after entering /stop

### ISSUE THREAD

**Issue by gdharron** [FTBTeam/FTB-Modpack-Issues#96]
### Modpack

FTB OceanBlcok

### Modpack version

1.2.0

### Log Files

https://pastebin.com/L3WJYmjQ

### Describe the bug

My OceanBlock server has recently started crashing when I am trying to restarting the server by doing /stop. It instantly hard crashes the server (causing a rollback after reboot) and even crashes people's clients for some reason. It looks like something to do with minetogether from what the logs say but I could be wrong. It wasn't always doing this just started about 4 days ago.

### Steps to reproduce

1. Run OceanBlock 1.2.0
2. Type /stop into the console
3. Server hard crashes instantly 

### Expected behaviour

A proper server shutdown after /stop command

**Comment by legitswitch** [comment]
#67 

Have you tried downgrading or removing Minetogether while the fixed dev version releases? Since it fixed client crashes, it could work for your server too.

**Comment by gdharron** [comment]
> 1. No
> 2. The server won't crash anymore, but if the clients are still using the latest MineTogether, then may still crash if they get disconnected.

I will remove mine together from the pack then and see if this helps with the server shutting down. Will update when possible. Thanks

**Comment by Sunekaer** [comment]
Pack has been updated with new version of minetogether.
