### ISSUE TITLE
[Bug]: Mystical Ag Growth Accelerator Recipe Is Uncraftable

### ISSUE THREAD

**Issue by superfreckledninja** [FTBTeam/FTB-Modpack-Issues#961]
### Modpack

FTB Plexiglass

### Modpack version

1.0.2

### Describe the bug

Inferium growth accelerator requires an item called 'rich soil farmland' which is not obtainable except in-world. There doesn't seem to be a way to get the block into your inventory without it reverting to 'rich soil' and there is no crafting recipe.

### Steps to reproduce

1. Load modpack and open world
2. search for and view recipe for inferium growth accelerator
3. note that it requires 'rich soil farmland'

There is no crafting recipe for rich soil farmland and no known alternative method to obtain the block.

### Expected behaviour

Rich soil farmland has a crafting recipe and/or inferium growth accelerator simply requires 'rich soil.'

**Comment by jasoncollege24** [comment]
This applies to all tiers of growth accelerator. Just wanted to make that known, in case the other recipes weren't checked.
