### ISSUE TITLE
[Bug]: Engineering hammer can only be used once

### ISSUE THREAD

**Issue by RobVor** [FTBTeam/FTB-Modpack-Issues#962]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.0.2

### Describe the bug

Engineering hammer breaks one chunk then becomes unusable.

### Steps to reproduce

1) Obtain any ore chunck
2) Craft engineering hammer (2 iron, 1 string, 2 sticks)
3) Crush chunk into dust with the hammer (Crafting table or inventory crafting)
4) First chunk turns to dust
5) No further chunks can be crushed

### Expected behaviour

ngineering hammer can be used until the durability reaches zero, and not just use the hammer once

### Additional information

Seems that I can break one of each ore chunk once with engineering hammer.
Exiting the game and reloading allows for one more action of attempting to crush ore chunks.

**Comment by Raidobw2** [comment]
In the next update this should be fixed with all ore and raw ore

**Comment by Raidobw2** [comment]
Fixed in 1.1.0 by updating IE
