### ISSUE TITLE
[Bug]: Zombie Villager not spawning with Zen Altar

### ISSUE THREAD

**Issue by DigMic** [FTBTeam/FTB-Modpack-Issues#963]
### Modpack

FTB Interaction

### Modpack version

1.12.2

### Describe the bug

Playing with FTB Interactive...
I have to create Zombie villager but it doesn't spawn.
I tried in créative too and using egg but same things

Sorry for my english its not very good i know.

### Steps to reproduce

1. Created Altar
2. I put the right element in the altar and i can see them spinning
3. I add the last one "bone"
4. I can see animation with ingredients going up
5. The zombie not spaw ... ican heard it or sometime see it flashing and disapear
6. Tried in "god mod" with same results

### Expected behaviour

Maybe make it work or explain me what i m doing wrong thnx alot :)

**Comment by Saereth** [comment]
send me your latest.log when you try to summon it, also are you playing in peaceful by chance?

**Comment by DigMic** [comment]
Hoooo gosh

I feel so ashamed...
You are right my game was in peacefull.
I don't know how its happend. I never thought to check this option.
Again sorry and thnx alot

**Comment by Saereth** [comment]
No problem, have fun! :)
