### ISSUE TITLE
[Bug]: Axes don't fell Rubber Trees from Myrtrees

### ISSUE THREAD

**Issue by ixanza** [FTBTeam/FTB-Modpack-Issues#966]
### Modpack

FTB One

### Modpack version

1.0.0

### Describe the bug

Using an axe on a rubber tree from Myrtrees only takes out 1 log rather than taking out the whole tree like every vanilla tree

### Steps to reproduce

1. Find Tree
2. Chop it down

### Expected behaviour

Like vanilla trees, the whole tree should be chopped down

**Comment by MaxNeedsSnacks** [comment]
One solution would be to add both Myrtrees wood blocks to a tag (`myrtrees:rubber_wood` for example) and then tell Ultimine to merge that tag by default (https://github.com/FTBTeam/FTB-Ultimine/blob/1.19/dev/common/src/main/java/dev/ftb/mods/ftbultimine/config/FTBUltimineServerConfig.java#L43-L49 is a thing :P)

**Comment by Saereth** [comment]
This is intentionally a seperate block not meant to be vein mined as its your latex producer can can still go destroy it but it's more intentional.
