### ISSUE TITLE
[Bug]: MineColonies Quarry not working correctly

### ISSUE THREAD

**Issue by Letsdrajl** [FTBTeam/FTB-Modpack-Issues#967]
### Modpack

FTB Direwolf20 1.18.2

### Modpack version

1.4.1

### Describe the bug

Quarry is going tobe built normal but when quarrier mines in it, he will deconstruct his progress and

### Steps to reproduce

1. Create a Colony from MineColonies mod
2. Build a Mine and a Quarry to assign a quarrier
3. Quarry not working correctly

### Expected behaviour

Quarry working normaly

**Comment by Letsdrajl** [comment]
The issue doesn't seem to be fixed. Although i tried the mod itself in its newest version standalone, where it worked.
I also asked at their own github page.

[Here](https://youtu.be/OrTF8y2Ok2U) a Video of the issue

**Comment by Jared87** [comment]
Had this issue on 1.4.1 too, the quarry does not accept any worker. The quarry gui has an empty assign window with no citizen listed, every other building can select its workers. As i have crashes after my 1.5.1 update i couldn't check this now, i'll have to fix this first and can give an update afterwards.
![image](https://user-images.githubusercontent.com/6816946/174432282-688cfcbc-43e0-4029-afa4-157534bb4ed3.png)
![image](https://user-images.githubusercontent.com/6816946/174432288-b051b03d-a727-4bfa-a832-a483149057da.png)

**Comment by Letsdrajl** [comment]
You need to have a quarrier hired in a mine.
After that you can assign that quarrier in the quarry.
But the Mine can only have either one of them.

**Comment by TheonlyTazz** [comment]
What Letsdrajl said, not an issue then

**Comment by Letsdrajl** [comment]
But Jared87's issue is unrelated to mine. He didn't have a worker while my worker destroys it's own work and makes it impossible to get out without teleporting or smth like this. There seems to be something broken in the schematic or some other mod is interfering.

**Comment by Jared87** [comment]
I fixed my "issue" and saw the same @Letsdrajl had (if i understood it correctly). 
My Quarriers first started to remove the quarry frame (idk why), but not to dig, they just ran back and forth.
So i can confirm this issue.

The problem i had ist not related to this problem and was just the, for me unintuitive, way to define quarriers and im really unhappy with the solution how it works and i think its a bit unintuitive to build an mine and send the miner to another building, it's like the courier warehouse logik, but the courier hasn't an "own digging hole". But that is not the problem of this issue and i'll adress it in the minecolonies discord.
