### ISSUE TITLE
[Bug]: DireWolf20 1.18 1.5.0 OreBerries regression - broken recipes and Patchouli (again)

### ISSUE THREAD

**Issue by JakeMoe** [FTBTeam/FTB-Modpack-Issues#968]
### Modpack

DireWolf20 1.18

### Modpack version

1.5.0

### Describe the bug

Looks to be a recurrence of #866; I'm unable to look up recipes in JEI, and Patchouli books seem broken (errors in the book).   OreBerries has reverted again to 0.1.6, updating to 0.1.7 fixes it.

### Steps to reproduce

1. Upgrade to 1.5.0
2. Log in to server
3. Look up recipe, most recipes fail to display
5. Open Patchouli book, see error

### Expected behaviour

Recipes display and Patchouli books show content

**Comment by lanoyo** [comment]
I am having the exact same issue. Updated to 1.5 and cannot click anything in jei. I can occasionally spam click things and get a recipe to pull up or something, but not consistent at all.

**Comment by Mac-or-Mac** [comment]
Same issue, updated to 1.5 both on the server (Apex Hosting) and Client. No way to use JEI Recipies.

**Comment by Sabster** [comment]
Moving to OreBerries-Replanted-1.18.2-0.1.7.jar fixes the issue again.

**Comment by Dracos99** [comment]
This is the same issue as we had in 1.3.0 and 1.4.0

**Comment by TheonlyTazz** [comment]
Guys, this was my bad! I recently took over the maintaining DW20 pack and wasnt aware of this issue, we have pushed a Hotfix 1.5.1 with the fixed Oreberries (somehow it "updated" to an older version)
