### ISSUE TITLE
[Bug]: Recipes not showing up in Multiplayer

### ISSUE THREAD

**Issue by Firestar311** [FTBTeam/FTB-Modpack-Issues#970]
### Modpack

Direwolf20 1.18

### Modpack version

1.5.0

### Describe the bug

When joining a multiplayer world, most of the normal crafting table recipes don't show up, however they do show up in Single Player. Some of the machine recipes show up though. 

Also, AE2 patterns became invalid, not sure if this is related to this issue or to AE2 update

### Steps to reproduce

1. Make a Direwolf20 1.18 multiplayer server
2. Join it
3. Check recipes in JEI and see that there are none, or check AE pattern recipes

### Expected behaviour

Recipes should show up

**Comment by Raidobw2** [comment]
Handled at #968, thanks for the report in any case!
