### ISSUE TITLE
[Bug]: Ars Nouveau + Storage Drawer Block Duplication

### ISSUE THREAD

**Issue by Sarrdonous** [FTBTeam/FTB-Modpack-Issues#971]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.0.2

### Describe the bug

The interaction between an Ars Nouveau Spell Turret and a Storage Drawer drawer allows for infinite duplication of any block. This includes duplicating a Better Crates crate with any item inside. When the turret is set to pull from a Storage Drawer, it does not use up an item when pulling and instead spawns a duplicate.

### Steps to reproduce

1. Place an Ars Nouveau Spell Turret, provide it with Source, and give it the spell Touch -> Place Block -> Break -> Extract.
2. Place a Storage Drawer next to the turret.
3. Add any block into the Storage Drawer.
4. Give the Spell Turret a redstone signal.

### Expected behaviour

I would expect the Spell Turret to use up an item in the Storage Drawer for the Place Block spell.

**Comment by farigiss** [comment]
I've experienced a very similar problem when having a turret take items from a Sophisticated Backpack placed adjacent to it. The backpack seems to empty but as soon as you break the backpack and open it from inventory, all the items a that the turret placed are also still in the backpack.

**Comment by Raidobw2** [comment]
Dupe bug should be fixed in 1.2.0
