### ISSUE TITLE
[Bug]: FTB Industrial Contraptions Roller Metal Ingot Plate Duplication Glitch

### ISSUE THREAD

**Issue by dzil123** [FTBTeam/FTB-Modpack-Issues#973]
### Modpack

FTB Direwolf 20 1.18

### Modpack version

1.4.1

### Describe the bug

Using the FTB Industrial Contraptions Roller it is possible to duplicate metals.

All tech mod recipes (tinkers, create, industrial engineering, etc) give 1 metal plate for 1 ingot (iron, copper, bronze, etc), but the Roller gives 2 metal plates. These plates can be melted in a Tinker's Smeltery or an IE Arc Furnace for 1 ingot each.

### Steps to reproduce

1. Aquire 1 iron ingot.
2. Use a Roller to create 2 iron plates.
3. Melt the plates in a Smeltery.
4. Cast the liquid metal into 2 ingots.

### Expected behaviour

This duplication glitch should not be possible. Either you should not be able to recycle metal plates into ingots, or the Roller recipe should be changed to give 1 plate from 1 ingot.

### Screenshots

![image](https://user-images.githubusercontent.com/5725958/174206743-0ecd449e-b0e4-4767-9863-4f8f0dce2381.png)

**Comment by TheonlyTazz** [comment]
Duplicate and fixed in 1.5.0
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/941
