### ISSUE TITLE
[Bug]: Upgrading client from 1.3.1 to 1.5.1 wipes options.txt, JEI bookmarks etc

### ISSUE THREAD

**Issue by ukmcplyr** [FTBTeam/FTB-Modpack-Issues#974]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.5.1

### Describe the bug

Reporting as a bug in the hope this shouldn't have happened but have a faint memory of previous FTB packs acting similarly.

Basically, options.txt, JEI bookmarks plus added mods (Xaero's World/Mini map and FPS Reducer in this case) have been kept across upgrades from the first beta up until at least 1.3.1, but on upgrading to 1.5.1 those files are removed.

Any chance this is a bug and not a feature? :grin: 

### Steps to reproduce

1. Upgrade from 1.3.1 with e.g. custom key binds
2. Start over with clean slate

### Expected behaviour

options.txt etc is preserved

**Comment by ukmcplyr** [comment]
I think this might actually be a bug in the app, apologies.

Even though I updated via the in-instance ```Versions -> 1.5.1 -> Update``` button, a new instance with a new UUID was created instead, leaving the original (1.3.1) instance apparently untouched.

Exiting the app, deleting the newer of the two instances, re-launching and then upgrading works as expected.

**Comment by DietmarKrause** [comment]
same here. i updated from 1.4.1. to 1.51 and the first time the instance was not updated, instead there was created a new instance feor 1.51 without the world files etc.open your old instance (1.3.1 ?), clilck on settings, then open folder and copy the folder "saves" (your world) "local" (maps and waypoints) and the file options.txt.
