### ISSUE TITLE
[Bug]: AE2 Wireless Crafting Terminal in Curio Charm slots crashes the local game and prevents login

### ISSUE THREAD

**Issue by aharrisw** [FTBTeam/FTB-Modpack-Issues#975]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.5.1

### Log Files

https://pastebin.com/Pq6pqbL0

### Describe the bug

Placing the AE2 wireless crafting terminal (id: ae2:wireless_crafting_terminal) in GUI charm slots 3 and 4 crashes the game entirely so you have to re-load the instance and then also prevents the user from logging back into the game. It went into slots 1 and 2 just fine.

I tried other items in those slots like the Advanced Magnet, Flux Capacitor and RebornStorage's Super Wireless Grid and those went in just fine and function as expected, no crash. 

### Steps to reproduce

1. Open your inventory
2. Click the button to open your Curio slots
3. Scroll down to see the 4 Charm slots
4. Place the AE2 Wireless Crafting Terminal into the visible 3 or 4 Charm slot
5. Experience crash
6. Re-load the modpack instance
7. Attempt to log in again
8. Note crash persists

### Expected behaviour

I expect to be able to place the Curio item in any designated Charm slot

### Additional information

To resolve the player not being able to log in, I have to modify the playerdata .dat file and delete the entry from their curios:inventory.

**Comment by TheonlyTazz** [comment]
i  dont know what adds these additional slots as back on 1.4.1 we only had 1 charm slot, i will probably revert it back to the way it was when i know what happened there

**Comment by TheonlyTazz** [comment]
This issue was fixed by the ae2wtlib mod. however we will still look in a way to remove 3 of the charm slots, as 4 charmslots is definetly to much
