### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JackMcNaughton** [FTBTeam/FTB-Modpack-Issues#976]
### Modpack

Direwolf29 1.18

### Modpack version

1.5.1

### Describe the bug

Quark adds new recipes to replace Minecraft Chests and I am trying to craft the Crafting Storage from the RebornStorage Mod, It does not accept Quarks Chest. I have been able to make a Chest from Minecraft, but I needed to get rubber logs. I am unable to get normal Minecraft chests any other way. 

### Steps to reproduce

1, Try to craft  the RebornStorage item using Quark Chests
2. Try to craft using Minecraft Chests. 

### Expected behaviour

I expected the Quark Chest to be usable to craft the Crafting Storage item from RebornStorage as it seems its goal is to replace chests.

### Screenshots

![image](https://user-images.githubusercontent.com/48554833/174401786-100de471-ad6b-4b38-bd5e-338059e5a986.png)
![image](https://user-images.githubusercontent.com/48554833/174401841-38ba5e5d-cafe-48f7-8cc9-695389159fed.png)
![image](https://user-images.githubusercontent.com/48554833/174402028-25096463-d5de-438e-961a-826b5d3712af.png)
![image](https://user-images.githubusercontent.com/48554833/174402157-75031056-35b1-453d-bd22-26c2cb00e258.png)
Also tried it in a normal crafting grid.

**Comment by ukmcplyr** [comment]
With Quark you can get a vanilla chest by placing e.g. an oak chest in a crafting grid (recipe no. 4 for minecraft:chest in JEI).

**Comment by JackMcNaughton** [comment]
> With Quark you can get a vanilla chest by placing e.g. an oak chest in a crafting grid (recipe no. 4 for minecraft:chest in JEI).

I see, shouldn't Quarks chest still work considering it works with a lot of other recipes with that used to be Minecraft Chests
