### ISSUE TITLE
[Suggestion]: Fast Leaf Decay

### ISSUE THREAD

**Issue by DrZomgaming** [FTBTeam/FTB-Modpack-Issues#978]
### Modpack

FTB One

### Is your suggestion related to a problem? Please describe.

Leaves become ugly when they are not attached to a plant or a tree. This mod is a simple way to get rid of hanging leaf blocks faster.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay
This mod makes naturally generated leaves decay within seconds after removing the log that they are attached to.

**Comment by TheonlyTazz** [comment]
Fast Leaf Decay was suggested during development but we decided against it because there are other ways to remove leaves fast, and it can cause performance issues when generating new chunks.

Feel free to add it to you own instance tho
