### ISSUE TITLE
[Bug]: No recipe to create yellorium fluid available

### ISSUE THREAD

**Issue by h0ppsen** [FTBTeam/FTB-Modpack-Issues#979]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.5.1

### Describe the bug

With Yellorium disabled it is not possible to create yellorium fluid. Hence, it's no possible to use yellorium for fluid mixing.

### Steps to reproduce

1. Try to insert Uran in Fluidizer

### Expected behaviour

You are able to create yellorium fluid or yellorium fluid has an valid substitution.

### Additional information

- Woraround: 
  - Build a reactor, insert uran as fuel, than eject it. It's ejected as yellorium (Technically, you use another bug as workaroud - but hey, it's not stupid if it works ;) )

- Possible Solution: 
  - add to kubejs/server_scripts/recipes.js:
  `event.custom({
  "type": "bigreactors:fluidizersolid",
  "ingredient": {
    "ingredient": {
      "item": "ftbic:uranium_ingot"
    },
    "count": 1
  },
  "result": {
    "fluid": "bigreactors:yellorium",
    "count": 1000
  }
});`

**Comment by quietust** [comment]
One downside of using a Reactor to convert Uranium into Yellorium is that the solid input ports are lossy and it takes 2 Uranium ingots to get 1 Yellorium ingot - from what I understand, this is the whole reason why you want to use the Fluidizer instead.

**Comment by TheonlyTazz** [comment]
The worldgen for Extreme Reactors got disabled in favor for using FTBIC Uranium, i have now modified the Fluidmixing recipe to accept Molten Uranium and added a recipe to smelt uranium ingots/blocks into molten Uranium in the fluidizer
![image](https://user-images.githubusercontent.com/3908847/174676184-7fc94c3a-3c4f-43f3-9b9a-3fa17aef3b3f.png)
![image](https://user-images.githubusercontent.com/3908847/174676205-2feccfff-97de-405f-adb7-34ac6ab47b39.png)
