### ISSUE TITLE
[Suggestion]: JAOPCA or similar mod for ore processing compatibility

### ISSUE THREAD

**Issue by Bulluk** [FTBTeam/FTB-Modpack-Issues#98]
### Modpack

FTB OceanBlock

### Is your suggestion related to a problem? Please describe.

It's nice to be able to for example make Mekanism Ore Slurries from all the Ores/Clusters. Enabling the quintupling of all ores.

### Mod suggestion

https://www.curseforge.com/minecraft/mc-mods/jaopca

**Comment by Bulluk** [comment]
For the Chemical Dissolution Chamber (Mekanism) the following are in my opinion missing:

Aluminium Cluster/Bauxite Ore
Nickel Cluster/Ore
Copper Cluster/Ore
Silver Cluster/Ore
Draconium Ore
Cobalt Cluster/Ore
Thallasium Ore

More options for Dimensional Shard ore, currently only automatable in a Pulverizer. Couple of suggestions that I can think of right now:

Immersive Engineering - Crusher 
Intergrated Dynamics - Mechanical Squeezer

**Comment by Sunekaer** [comment]
Okay so regarding the Chemical Dissolution Chamber that would require completely new recipes and fluids added to the game, this is something there will be very low prio if it even will be done for this.

For the Dim share i have changed so the it also works in other machines
