### ISSUE TITLE
[Bug]: Stall on server start

### ISSUE THREAD

**Issue by john01dav** [FTBTeam/FTB-Modpack-Issues#980]
### Modpack

FTB Direwolf20 1.18

### Modpack version

1.4.1

### Log Files

https://cdn.discordapp.com/attachments/922372454368813066/987820702491086898/crash-2022-06-18_22.46.36-server.txt
https://cdn.discordapp.com/attachments/922372454368813066/987814025310126140/crash-2022-06-18_22.20.04-server.txt

Lots more exist due to autorestarts.

### Describe the bug

We have had an intermittent issue where the server gets in a mode where after every startup it stalls and then automatically reboots (we have an automatic restart script). It started a few versions ago and seems to come and go. Sometimes updating to the latest version temporary solves it.

It seems like this is related to #211. We are not running Sponge.

### Steps to reproduce

1. Start the server
2. Wait
3. See it stall
4. Repeat

I can share server files privately with a FTB representative to help debug.

### Expected behaviour

I expect the server to start without stalling

### Screenshots

Not applicable

### Additional information

```       _,met$$$$$gg.          <user>@<hostname> 
    ,g$$$$$$$$$$$$$$$P.       -------------------------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 10 (buster) x86_64 
 ,$$P'              `$$$.     Host: B360 HD3P-LM 
',$$P       ,ggs.     `$$b:   Kernel: 4.19.0-16-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 368 days, 7 hours, 11 mins 
 $$P      d$'     ,    $$P    Packages: 971 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.0.3 
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/1 
 Y$$.    `.`"Y$$$$P"'         CPU: Intel i9-9900K (16) @ 5.000GHz 
 `$$b      "-.__              GPU: Intel Device 3e98 
  `Y$$                        Memory: 56755MiB / 64333MiB 
   `Y$$.
     `$$b.                                            
       `Y$$b.
          `"Y$b._
              `"""

openjdk 17.0.3 2022-04-19 LTS
OpenJDK Runtime Environment Microsoft-32931 (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Microsoft-32931 (build 17.0.3+7-LTS, mixed mode, sharing)

```

**Comment by quietust** [comment]
Does the problem still happen with modpack version 1.5.1 (which was released a few days ago)?

**Comment by phit** [comment]
yes, I've tracked this down to Refined Storage(?) here's a visualvm profiling snapshot from the server starting right after the map loaded until it unfreezes
[serverstart.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8939041/serverstart.zip)

**Comment by john01dav** [comment]
> Does the problem still happen with modpack version 1.5.1 (which was released a few days ago)?

I just updated to 1.6.1, and the issue persisted.

**Comment by john01dav** [comment]
> yes, I've tracked this down to Refined Storage(?) here's a visualvm profiling snapshot from the server starting right after the map loaded until it unfreezes [serverstart.zip](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8939041/serverstart.zip)

I did my own visualvm snapshot, and it's different. It reflects stalling in the stack trace that I posted in my original stall reports instead. I don't think that we have the same issue. Furthermore, my issue never unfreezes.
