### ISSUE TITLE
[Bug]: Crashes on startup RFTools Bug? 

### ISSUE THREAD

**Issue by Fredriik98** [FTBTeam/FTB-Modpack-Issues#981]
### Modpack

Direwolf20 1.18

### Modpack version

1.5.1

### Log Files

[crash-2022-06-18_21.46.28-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8934383/crash-2022-06-18_21.46.28-server.txt)

### Describe the bug

RFTools modular storage mod, placed a block in Modular stoarge, then crashed.

### Steps to reproduce

place a "remote storage module" in a "modular storage" block 

### Expected behaviour

not to crash?

### Screenshots

![IMG_1807](https://user-images.githubusercontent.com/107775075/174457966-57bdf2a0-421e-4c2a-95e6-a42946bc5e70.jpg)

### Additional information

tried removing the mods from modpack, tried downgrading to an older version.

**Comment by TheonlyTazz** [comment]
i have tried this with multiple instances and wasnt able to replicate it, i'll be forwarding this towards RFtools Github

**Comment by McJty** [comment]
The Remote Storage Module is not yet supported in 1.16. Don't use it
