### ISSUE TITLE
[Bug]: Entities do not render after exiting world until game is restarted

### ISSUE THREAD

**Issue by e-SonOfAnder** [FTBTeam/FTB-Modpack-Issues#982]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.5.1

### Describe the bug

After saving and exiting from a single player world, if you go back into it, no entities render. This includes the player, tile entities like chests, mobs, etc. The only way to fix it is to completely shut the game down and relaunch.

### Steps to reproduce

1. Launch the game, and load a single player world
2. Do stuff
3. Save and exit the game
4. Hit the Mods button to look at the list of mods (have done this several times recently to submit bugs for other things)
5. Go back into the single player world
6. See that the player's hand is missing, along with any other entities around you.

### Expected behaviour

Entities should always render properly.

**Comment by e-SonOfAnder** [comment]
This may have been related to https://github.com/FTBTeam/FTB-Mods-Issues/issues/313; I am no longer able to reproduce the entity rendering bug as described above. There is a secondary issue that still occurs (and I assumed was related) where a huge number of recipe unlock toast notifications scroll by after re-entering the game using the above steps, and this is still happening. I can create a new issue for this one if you'd like.

**Comment by Sunekaer** [comment]
Im not able to recreate the recipe toast issue, can you recreate it?

**Comment by e-SonOfAnder** [comment]
As of my last comment, yes - that was on version 1.6.1 of the modpack; I am updating to 1.8.0 now and will retest.

**Comment by e-SonOfAnder** [comment]
Just tested with 1.8.0 and still see the described behavior. I did a screen record, and will include a link to the video, as it is too large to embed here in the ticket.

https://drive.google.com/file/d/1D_wnc-iOkTsNf08O3hAxnbvp_Rm2UrL3/view?usp=sharing

**Comment by Raidobw2** [comment]
The file currently cannot be viewed, you might have to recheck that it's public for the read permission so Sunekaer can see it

**Comment by e-SonOfAnder** [comment]
Google did not save my changes the first time; file should be viewable now.

**Comment by TheonlyTazz** [comment]
still couldnt replicate this @e-SonOfAnder seeing how this is such a small issue im going to put this on low priority
