### ISSUE TITLE
[Bug]: Nasty Mobs spawning at light levels greater than 0

### ISSUE THREAD

**Issue by jasoncollege24** [FTBTeam/FTB-Modpack-Issues#990]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.0.2

### Describe the bug

So, I've been trying to figure out why nasty skeletons have been spawning so close to my base, which is quite lit up, and figured they were just wandering in from beyond the perimeter... that is, until I made a cow farm...

Inside the cow farm, there is a single torch. The light level inside the farm drops to no lower than 6, yet nasty mobs are still spawning inside the fence.

I checked the config file, which claims the required light levels are supposed to be 0, but it looks like it's being ignored, and using spawn rules from before 1.16

### Steps to reproduce

1. Light up a large area, so that no blocks have a light level of 0
2. ensure that the test area has blocks with light levels between 1, and 7
3. move to the required spawn distance
4. wait during night time (Might have to wait more than one night)
5. watch a nasty skeleton spawn

### Expected behaviour

No nasty mobs should spawn, with block light level greater than 0

### Screenshots

![Screenshot (56)](https://user-images.githubusercontent.com/22086680/174590867-362b23ea-c717-4e6b-98a3-9c412203c31c.png)

### Additional information

This is on a server, located on my home LAN, running ubuntu 20.04. All players play in survival, and server side configs are all defaults, except RAM, which was allocated up to 6GB. 

The included screenshot shows a mob that spawned moments before it was taken, obviously where the light level is not 0.

Did not include logs, because I've been playing for hours, and don't know what portion of the logs would have any helpful info.

**Comment by Raidobw2** [comment]
Thanks for the report, I see you talked with the mod author at https://github.com/Lupicus/NastyMobs/issues/4, I'll talk to them as well

**Comment by jasoncollege24** [comment]
Yup. There is another mod doing the same thing. Do you want a separate report for that mod as well?

**Comment by Raidobw2** [comment]
Please yes, the other issue will be easier to track on there. Thanks!

**Comment by Raidobw2** [comment]
Reverting a part in the config from 0 >> 7 seems to have fixed it. I've used that to fix it. The resource creepers might be something else with InControl, I'll follow up with the InControl author. (I kinda have to use InControl since otherwise dimension-specific creepers aren't possible).
I'm releasing a hotfix 1.1.1 tomorrow with that fix
