### ISSUE TITLE
[Bug]: Lead Block is missing Extreme Reactor's moderator and coil ability

### ISSUE THREAD

**Issue by aharrisw** [FTBTeam/FTB-Modpack-Issues#991]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.5.1

### Describe the bug

Extreme Reactors defines blocks as moderators/coils to go into the reactor/turbine and lead is one of those; however, only the FTB Industrial Contraptions version is visible in JEI and unfortunately that's the only one of the three in the pack that doesn't have that moderator definition.

### Steps to reproduce

1. Turn on advanced tooltips (F3+H)
2. Search JEI for `lead block`
3. Hover over the only result that returns (from FTBic)
4. Note there is no yellow text stating it's a moderator block
5. Go into Creative Mode
6. Search for `block of lead`
7. Note both Thermal and Immersive Engineering versions correctly have the yellow text

### Expected behaviour

Any variation of a Lead Block should be flagged as a moderator and coil block

### Screenshots

![lead_block_missing_er](https://user-images.githubusercontent.com/10736665/174591355-ecd4be5f-a398-4aec-a801-5590986083f0.png)

### Additional information

I tried using the FTBic block in the reactor to see if maybe it'd still work without that text but it didn't. The multiblock would not complete itself if I had the FTBic variant.

I noticed the Bronze Block is in a similar situation where FTBic is not showing it as an Extreme Reactors block however with bronze, if I search it in JEI, I can still craft the other variants. For some reason the lead block has the others filtered out.

**Comment by TheonlyTazz** [comment]
![image](https://user-images.githubusercontent.com/3908847/175120060-da512304-ae05-4171-ad10-e930a0f9645c.png)
Fixed indev
