### ISSUE TITLE
[Bug]: Missing world gen of an Extreme Reactors material

### ISSUE THREAD

**Issue by aharrisw** [FTBTeam/FTB-Modpack-Issues#992]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.5.1

### Describe the bug

The Extreme Reactors material (Anglesite) is set to not generate in the world which wasn't a problem until a recent Extreme Reactors update added a recipe where a liquid requires it (Tangerium).

### Steps to reproduce

1. Look at the recipe for Tangerium in JEI
2. Click on the Anglesite crystal
3. Note there is no way to craft it
4. Look at the world gen section of the Extreme Reactors config and see that it's disabled

### Expected behaviour

I should be able to find and harvest an Anglesite crystal in the world to complete the Tangerium recipe

### Screenshots

![anglesite_recipe_tangerium](https://user-images.githubusercontent.com/10736665/174658123-d2274ae7-fb6d-4c60-b050-b869bc283128.png)

### Additional information

I believe the following in `config\extremereactors\common.toml` needs to be changed:

Line 95 (`enableWorldGen`): change to `true`
Line 98 (`enableWorldRegeneration`): change to `true`
Line 102 (`userWorldGenVersion`): change to `2`
Line 115 (`anglesiteOreEnableWorldGen`): change to `true`

**Comment by TheonlyTazz** [comment]
Anglesite is going to be enabled on 1.6.0 with worldregen
