### ISSUE TITLE
[Bug]: Steel Ingot/Block display error in JEI, plus possible recipe conflict with Immersive Engineering, Mekanism and Create: Alloyed

### ISSUE THREAD

**Issue by Mundif** [FTBTeam/FTB-Modpack-Issues#993]
### Modpack

FTB Presents Direwolf 20 1.18

### Modpack version

1.5.1

### Describe the bug

Steel ingot in JEI is Immersive Engineering one which shows no recipes for IE how to make steel ingot, I made IE blast furnace and made steel ingot, result was Mekanism Steel ingot, when checked for recipes with R key on it, only shows IE machines with Mek steel ingot being result, not IE one shown in JEI, and no way shown how to make it with Create: Alloyed in either case. 

Similar issue with steel blocks, Create:A shows no recipes for its steel block while it is being shown in JEI, the other Steel block being displayed in JEI at same time is IE one, which has no recipes for IE shown, ie 'block of iron to block of steel' , and making steel block from iron block in IE mahines results in Mek steel block which again only shows IE recipes for it. 

Another issue being when you craft those Mek steel ingots to a block you end up with IE steel block that crafts to IE steel ingots which then grants "The Upgrade!" advancement from IE for making steel ingot, which did not trigger with Mek ones.

### Steps to reproduce

I think, I explained 'how to', above.

### Expected behaviour

Recipes being shown properly for all ways to craft and not ending up with different results after crafting, so you dont have same but different ingots and blocks at same time.

**Comment by TheonlyTazz** [comment]
This is very strange, as we have a special "unify" script that will specify every craft to use the same type
```js
{
      name: "steel",
      hasOre: false,
      rawItem: "",
      rawBlock: "",
      nuggetItem: "immersiveengineering:nugget_steel",
      ingotItem: "immersiveengineering:ingot_steel",
      blockItem: "immersiveengineering:storage_steel",
      dustItem: "immersiveengineering:dust_steel",
      plateItem: "immersiveengineering:plate_steel",
      rodsItem: "immersiveengineering:stick_steel",
      gearItem: "thermal:steel_gear",
      crushedItem: "",
    },```

when checking the blast furnace usage, it also shows IE steel ingots and even after testing it in a blast furnace myself i have gotten Immersive steel
![image](https://user-images.githubusercontent.com/3908847/175006220-d2f5839e-f7bc-4398-b0d2-dfbb8d7bdee3.png)
![image](https://user-images.githubusercontent.com/3908847/175006279-ef717765-9569-4d5a-b31a-4409f63b9468.png)

please try using a clean instance of the pack to ensure your kubeJS scripts are in check and report if its fixed so we can close the issue or further investigate

**Comment by Mundif** [comment]
I think I found the script you meant, it is in both old and new instance as you shown. 
![KubeScript](https://user-images.githubusercontent.com/38189757/175103295-ad48d054-a0c8-4b6f-b003-88ee7b279608.jpg)

**Comment by TheonlyTazz** [comment]
correct, thats the unify script we use.
its just server_script is whats run while playing the game, which can be reloaded with /reload
singleplayer is also kind of a server on its own

ill bee looking into this later today

**Comment by Mundif** [comment]
Well... I used that /reload and... Immersive ingots and blocks replaced everything, that Create steel block with no recipes still shows though.

**Comment by TheonlyTazz** [comment]
> Well... I used that /reload and... Immersive ingots and blocks replaced everything, crafting shows as well, that Create steel block with no recipes still shows though.

that create steel block will be removed next update.
about the /reload issue, this will get addressed next update aswell
