### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by thederpykrafter** [FTBTeam/FTB-Modpack-Issues#994]
### Modpack

FTB Presents Direwolf20 1.18

### Modpack version

1.5.1

### Describe the bug

Superflat worlds generate with default tarrain. only mod added to pack is FTB Ultimine.

### Steps to reproduce

Generate world using superflat setting
get world with default terrain

### Expected behaviour

get flat terrain

**Comment by TheonlyTazz** [comment]
The issue here is the Terralith mod, because its a Datapack ported to a mod and enabled by default, which changes the worldgen... you need to disable the jar in the mods folder to create a flat world.
