### ISSUE TITLE
[Bug]: Server crash on opening lootchest in Direwolf20 1.18 FTB: 1.5.1 

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [FTBTeam/FTB-Modpack-Issues#995]
### Modpack

direwolf20 1.18 1.5.1

### Modpack version

1.5.1 

### Log Files

[crash-2022-06-21_21.17.11-server.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/8952246/crash-2022-06-21_21.17.11-server.txt)

### Describe the bug

When opening a lootbox, sometimes, about 1 of 50 tries, the server stalls and crashes. I believe it is because of some item it can't load when it's randomizing the loot. 

### Steps to reproduce

1. Go on a hosted server (not sure if it's a problem in vanilla) 
2. open a lot of lootchests 
3. it will eventually hang or crash 

### Expected behaviour

It shouldn't crash. 

### Additional information

Server is running configured to use JVMAX 8GB ram, number of players are usually between 3 and 5. Peak 8.

**Comment by TheonlyTazz** [comment]
while this doesnt fix the issue, you can try to set the max-tick-time to -1 for now in the server.properties untill i found the culprit of this issue

server.properties:
`max-tick-time=-1`
