### ISSUE TITLE
[Bug]: Sophisticated Backpacks and Sorting

### ISSUE THREAD

**Issue by RowleyRS** [FTBTeam/FTB-Modpack-Issues#998]
### Modpack

FTB Plexiglass Mountain

### Modpack version

1.0.2

### Describe the bug

When using sophisticated backpacks with stack upgrades.

If you sort inside the backpack it will separate all the large stack items into smaller stacks and delete everything else.

### Steps to reproduce

Sophisticated backpack, put at least the first tier of stack upgrade in it.
Fill half the backpack with stacks (128 because of the upgrade.) of an item. (eg. Dirt)
Fill the rest of the pack slots with any other item(s)
Middle Mouse Sort.

### Expected behaviour

an inventory check to determine if there's space and how much.

**Comment by Raidobw2** [comment]
See #923 for a fix, the new update will contain a fix only for new players (the default key will be bound correctly).
