### ISSUE TITLE
[Bug]: quest for jetpacks require only vibrant jetpack

### ISSUE THREAD

**Issue by joinmod** [FTBTeam/FTB-Modpack-Issues#999]
### Modpack

FTB academy 1.12

### Modpack version

1.4.0

### Describe the bug

so i trying to complete a quest for simply jetpacks 2, i need make a leadstone jetpack from description, but quest accepts only a vibrant jetpack which i cant make it because modpack doesn't have a ender io, and i think second stage of that quest are broken too 

### Steps to reproduce

1. make a leadstone jetpack
2. profit

### Expected behaviour

complete a quest

### Screenshots

https://imgur.com/a/vREemMH

**Comment by manmaed** [comment]
@aaronhowser1 any word on this has this been fixed
this will auto close in 2 weeks if no response

**Comment by aaronhowser1** [comment]
It has not been
